### ISSUE TITLE
unable to check signature after installing youtube-dl. 'public key not found' error

### ISSUE THREAD

**Issue by kimbaudi** [rg3/youtube-dl#10005]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.03.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.03.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information
After successfully installing youtube-dl, I am unable to check the signature on my Ubuntu machine. I followed the instructions on https://rg3.github.io/youtube-dl/download.html

I installed using curl:
> sudo curl -L https://yt-dl.org/downloads/2016.07.03.1/youtube-dl -o /usr/local/bin/youtube-dl
> sudo chmod a+rx /usr/local/bin/youtube-dl

I tried to check the signature:
> sudo wget https://yt-dl.org/downloads/2016.07.03.1/youtube-dl.sig -O youtube-dl.sig
> gpg --verify youtube-dl.sig /usr/local/bin/youtube-dl
> rm youtube-dl.sig

I get the following output:
> gpg: Signature made Sun 03 Jul 2016 07:30:08 AM PDT using RSA key ID 18A9236D
> gpg: Can't check signature: public key not found

How can I check the signature?

**Comment by yan12125** [comment]
See #9647

**Comment by YuvalZilber** [comment]
i have the same problem.
i saw [#9647](https://github.com/rg3/youtube-dl/issues/9647) and he gives a download for a .asc file.
what should i do with that?
