### ISSUE TITLE
dailymotion video download fails 

### ISSUE THREAD

**Issue by fmitha** [rg3/youtube-dl#1000]
youtube-dl  
    http://www.dailymotion.com/video/xuh369_osdc-fr-2012-changesets-evolution-mercurial-secoue-le-monde-du-dvcs_tech
   
    [dailymotion] xuh369: Downloading webpage
    [dailymotion] xuh369: Extracting information
    ERROR: Unable to extract video URL; please report this issue on GitHub.

    $ youtube-dl --version
    2013.06.21

**Comment by dstftw** [comment]
Works fine with latest version.
