### ISSUE TITLE
Cannot download "shared" YouTube videos

### ISSUE THREAD

**Issue by arter97** [rg3/youtube-dl#10007]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.05**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

URL : https://www.youtube.com/shared?ci=1nEzmT-M4fU
It looks like YouTube has a new feature called "Sharing" with .com/shared prefix.
And current version of youtube-dl does not support it.

Simply downloading the webpage and searching for "videoId" seems to return a video ID that can be used to "https://www.youtube.com/watch?v=ID_HERE".
e.g) `<meta itemprop="videoId" content="uPDB5I9wfp8">`

Can this be added to youtube-dl support?

```
arter97@arter97-X99:/tmp$ youtube-dl -F --verbose https://www.youtube.com/shared?ci=1nEzmT-M4fU
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'--verbose', u'https://www.youtube.com/shared?ci=1nEzmT-M4fU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.05
[debug] Python version 2.7.11+ - Linux-4.4.14-zen+-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[youtube:user] shared: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] shared: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 390, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1955, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by yan12125** [comment]
Thanks for the report. The new URL scheme looks interesting, and of course we are always trying our best to support everything YouTube provides!
