### ISSUE TITLE
Downloading a playlist's subtitles does not work.

### ISSUE THREAD

**Issue by babadoctor** [rg3/youtube-dl#10010]
Downloading a playlist's subtitles does not work.
Example:
youtube-dl --all-subs --skip-download https://www.youtube.com/user/LinusTechTips/videos
It states:
WARNING: video doesn't have subtitles
http://pastebin.com/SDEZNJb5

**Comment by babadoctor** [comment]
Clearly the videos have subtitles.

**Comment by yan12125** [comment]
Its subtitle is auto-generated. Use ```--write-auto-sub``` instead.

**Comment by babadoctor** [comment]
thanks!
