### ISSUE TITLE
New regression : spiegel

### ISSUE THREAD

**Issue by anisse** [rg3/youtube-dl#10018]
Maybe introduced in  252a1f7 . Ping @remitamine

See: https://travis-ci.org/anisse/youtube-dl/jobs/142500098

Please tell me if you mind this type of report.

**Comment by remitamine** [comment]
thanks for the report, forget to update test for related extractor(SpiegelArticleIE).
> Please tell me if you mind this type of report.

for me, it's actually helpful.
