### ISSUE TITLE
[https @ 0x84063a0] HTTP error 403 Forbidden Unable to open key file https://nbcmpx-vh.akamaihd.net/ ...

### ISSUE THREAD

**Issue by Albretch** [rg3/youtube-dl#10015]
`[https @ 0x84063a0] HTTP error 403 Forbidden
Unable to open key file https://nbcmpx-vh.akamaihd.net/i/video/372/711/140208_2723709_Trump_Divorce_Cold_Opening_anvver_3_mpx_,1696,1296,896,696,496,306,150,240,64,.mp4.csmil/crypt.key?null=0&id=AgBI5ZPOFwMNXji1e1dXrjKa5eFSU%2f2aKJr1sUiE32egpXkdidM3W+LZT4GPJrGpZKLFmmGUn1yJ8w%3d%3d&hdntl=exp=1467811512~acl=/i/video/372/711/140208_2723709_Trump_Divorce_Cold_Opening_anvver_3_mpx_*~data=hdntl~hmac=7158090afb8fc6f1cb7db9a13f4a86a87d08795e79839fbc5d04114fbfd35a96
[http @ 0x8098240] HTTP error 403 Forbidden
[crypto @ 0x84063a0] Unable to open input
https://nbcmpx-vh.akamaihd.net/i/video/372/711/140208_2723709_Trump_Divorce_Cold_Opening_anvver_3_mpx_,1696,1296,896,696,496,306,150,240,64,.mp4.csmil/index_0_av.m3u8?null=0&id=AgBI5ZPOFwMNXji1e1dXrjKa5eFSU%2f2aKJr1sUiE32egpXkdidM3W+LZT4GPJrGpZKLFmmGUn1yJ8w%3d%3d&hdntl=exp=1467811512~acl=%2fi%2fvideo%2f372%2f711%2f140208_2723709_Trump_Divorce_Cold_Opening_anvver_3_mpx_*~data=hdntl~hmac=7158090afb8fc6f1cb7db9a13f4a86a87d08795e79839fbc5d04114fbfd35a96: Input/output error

ERROR: ffmpeg exited with code 1
~
$ _ODIR="/media/sda6/LklWb/com/nbc/www/saturday-night-live/video/"
$ _URLS_IFL="http://www.nbc.com/saturday-night-live/video/trump-divorce-cold-opening/n9870"
$ 
$ date; time youtube-dl --format best --proxy "${_HTTP_PRX}" --max-filesize "${_MXSz}" --user-agent "${_UA}" --referer "${_REFR}" --no-overwrites --ignore-errors --continue --verbose --no-progress --console-title --output ${_ODIR}"/"'%(title)s'_'%(id)s'.'%(ext)s'  "${_URLS_IFL}"
Tue Jul  5 09:23:45 EDT 2016
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--format', u'best', u'--proxy', u'', u'--max-filesize', u'8192m', u'--user-agent', u'Mozilla/5.0 (Windows NT 6.1; U; nl; rv:1.9.1.6) Gecko/20091201 Firefox/3.5.6 Opera 11.01', u'--referer', u'http://www.bing.com/search?q=youtube&', u'--no-overwrites', u'--ignore-errors', u'--continue', u'--verbose', u'--no-progress', u'--console-title', u'--output', u'/media/sda6/LklWb/com/nbc/www/saturday-night-live/video//%(title)s_%(id)s.%(ext)s', u'http://www.nbc.com/saturday-night-live/video/trump-divorce-cold-opening/n9870']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.03.1
[debug] Python version 2.7.8 - Linux-3.16.3-64-x86_64-with-debian-7.6
[debug] exe versions: avconv 11-6, avprobe 11-6, ffmpeg 11-6
[debug] Proxy map: {}
[NBC] n9870: Downloading webpage
[ThePlatform] 9e53cc234e7eec4fdbcaa5451417ed63: Downloading webpage
[ThePlatform] 9e53cc234e7eec4fdbcaa5451417ed63: Downloading SMIL data
[ThePlatform] 9e53cc234e7eec4fdbcaa5451417ed63: Downloading m3u8 information
[ThePlatform] 9e53cc234e7eec4fdbcaa5451417ed63: Downloading JSON metadata
[debug] Invoking downloader on u'https://nbcmpx-vh.akamaihd.net/i/video/372/711/140208_2723709_Trump_Divorce_Cold_Opening_anvver_3_mpx_,1696,1296,896,696,496,306,150,240,64,.mp4.csmil/index_0_av.m3u8?null=0&id=AgBI5ZPOFwMNXji1e1dXrjKa5eFSU%2f2aKJr1sUiE32egpXkdidM3W+LZT4GPJrGpZKLFmmGUn1yJ8w%3d%3d&hdntl=exp=1467811512~acl=%2fi%2fvideo%2f372%2f711%2f140208_2723709_Trump_Divorce_Cold_Opening_anvver_3_mpx_*~data=hdntl~hmac=7158090afb8fc6f1cb7db9a13f4a86a87d08795e79839fbc5d04114fbfd35a96'
[download] Destination: /media/sda6/LklWb/com/nbc/www/saturday-night-live/video//Trump Divorce Cold Opening_n9870.mp4
[debug] avconv command line: avconv -y -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Cookie: _alid_=CXhs35c3tqijnj8Sd2IaMA==
Referer: http://www.bing.com/search?q=youtube&
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 6.1; U; nl; rv:1.9.1.6) Gecko/20091201 Firefox/3.5.6 Opera 11.01
' -i 'https://nbcmpx-vh.akamaihd.net/i/video/372/711/140208_2723709_Trump_Divorce_Cold_Opening_anvver_3_mpx_,1696,1296,896,696,496,306,150,240,64,.mp4.csmil/index_0_av.m3u8?null=0&id=AgBI5ZPOFwMNXji1e1dXrjKa5eFSU%2f2aKJr1sUiE32egpXkdidM3W+LZT4GPJrGpZKLFmmGUn1yJ8w%3d%3d&hdntl=exp=1467811512~acl=%2fi%2fvideo%2f372%2f711%2f140208_2723709_Trump_Divorce_Cold_Opening_anvver_3_mpx_*~data=hdntl~hmac=7158090afb8fc6f1cb7db9a13f4a86a87d08795e79839fbc5d04114fbfd35a96' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:/media/sda6/LklWb/com/nbc/www/saturday-night-live/video//Trump Divorce Cold Opening_n9870.mp4.part'
avconv version 11-6:11-1, Copyright (c) 2000-2014 the Libav developers
  built on Sep 13 2014 21:27:59 with gcc 4.9.1 (Debian 4.9.1-12)
[https @ 0x84063a0] HTTP error 403 Forbidden
Unable to open key file https://nbcmpx-vh.akamaihd.net/i/video/372/711/140208_2723709_Trump_Divorce_Cold_Opening_anvver_3_mpx_,1696,1296,896,696,496,306,150,240,64,.mp4.csmil/crypt.key?null=0&id=AgBI5ZPOFwMNXji1e1dXrjKa5eFSU%2f2aKJr1sUiE32egpXkdidM3W+LZT4GPJrGpZKLFmmGUn1yJ8w%3d%3d&hdntl=exp=1467811512~acl=/i/video/372/711/140208_2723709_Trump_Divorce_Cold_Opening_anvver_3_mpx_*~data=hdntl~hmac=7158090afb8fc6f1cb7db9a13f4a86a87d08795e79839fbc5d04114fbfd35a96
[http @ 0x8098240] HTTP error 403 Forbidden
[crypto @ 0x84063a0] Unable to open input
https://nbcmpx-vh.akamaihd.net/i/video/372/711/140208_2723709_Trump_Divorce_Cold_Opening_anvver_3_mpx_,1696,1296,896,696,496,306,150,240,64,.mp4.csmil/index_0_av.m3u8?null=0&id=AgBI5ZPOFwMNXji1e1dXrjKa5eFSU%2f2aKJr1sUiE32egpXkdidM3W+LZT4GPJrGpZKLFmmGUn1yJ8w%3d%3d&hdntl=exp=1467811512~acl=%2fi%2fvideo%2f372%2f711%2f140208_2723709_Trump_Divorce_Cold_Opening_anvver_3_mpx_*~data=hdntl~hmac=7158090afb8fc6f1cb7db9a13f4a86a87d08795e79839fbc5d04114fbfd35a96: Input/output error

ERROR: ffmpeg exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/media/sda1/inst/sw/youtube/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/__init__.py", line 420, in main
    _real_main(argv)
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/__init__.py", line 410, in _real_main
    retcode = ydl.download(all_urls)
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/YoutubeDL.py", line 1740, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/YoutubeDL.py", line 687, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/YoutubeDL.py", line 758, in process_ie_result
    new_result, download=download, extra_info=extra_info)
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/YoutubeDL.py", line 733, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/YoutubeDL.py", line 1386, in process_video_result
    self.process_info(new_info)
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/YoutubeDL.py", line 1648, in process_info
    success = dl(filename, info_dict)
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/YoutubeDL.py", line 1590, in dl
    return fd.download(name, info)
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/downloader/external.py", line 43, in real_download
    self.get_basename(), retval))
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/downloader/common.py", line 161, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/YoutubeDL.py", line 550, in report_error
    self.trouble(error_message, tb)
  File "/media/sda1/inst/sw/youtube/youtube-dl/youtube_dl/YoutubeDL.py", line 512, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

real	0m6.969s
user	0m1.430s
sys	0m0.190s
$
`

**Comment by yan12125** [comment]
It's a bug of avconv. ffmpeg works fine. There are two solutions:

* Install ffmpeg and add ```--prefer-ffmpeg```. For example:

```
youtube-dl -v "http://www.nbc.com/saturday-night-live/video/trump-divorce-cold-opening/n9870" --prefer-ffmpeg
```

* Install [python-crypto](https://packages.debian.org/search?keywords=python-crypto) and add ```--hls-prefer-native```. For example:
```
youtube-dl -v "http://www.nbc.com/saturday-night-live/video/trump-divorce-cold-opening/n9870" --hls-prefer-native
```
You may also want to add ```--fixup never``` as avconv can't handle the downloaded video well.

**Comment by Albretch** [comment]
still same error:

` youtube-dl -v "http://www.nbc.com/saturday-night-live/..." --prefer-ffmpeg

$ which ffmpeg
/usr/bin/ffmpeg

$ ffmpeg -version
avconv version 11-6:11-1, Copyright (c) 2000-2014 the Libav developers
  built on Sep 13 2014 21:27:59 with gcc 4.9.1 (Debian 4.9.1-12)
avconv 11-6:11-1
libavutil     54.  3. 0 / 54.  3. 0
libavcodec    56.  1. 0 / 56.  1. 0
libavformat   56.  1. 0 / 56.  1. 0
libavdevice   55.  0. 0 / 55.  0. 0
libavfilter    5.  0. 0 /  5.  0. 0
libavresample  2.  1. 0 /  2.  1. 0
libswscale     3.  0. 0 /  3.  0. 0
$ 
 which python
/usr/bin/python

$ python --version
Python 2.7.8
$ 
`

**Comment by dstftw** [comment]
Your ffmpeg is symlinked to avconv:
>$ ffmpeg -version
avconv version 11-6:11-1, Copyright (c) 2000-2014 the Libav developers
