### ISSUE TITLE
Can't download from Rutube.ru - <HTTPError 404: 'NOT FOUND'>

### ISSUE THREAD

**Issue by diman82** [rg3/youtube-dl#10021]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
c:\Python36\Scripts>youtube-dl.exe --verbose https://rutube.ru/metainfo/tv/1523/#!/season7
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://rutube.ru/metainfo/tv/1523/#!/season7']
[debug] Encodings: locale cp1255, fs mbcs, out cp862, pref cp1255
[debug] youtube-dl version 2016.07.06
[debug] Python version 3.6.0a2 - Windows-10-10.0.10586-SP0
[debug] exe versions: ffmpeg N-80912-gce466d0, ffprobe N-80912-gce466d0
[debug] Proxy map: {}
[rutube:movie] 1523: Downloading movie JSON
[rutube:movie] 1523: Downloading page 1
[rutube:movie] 1523: Downloading page 2
[rutube:movie] 1523: Downloading page 3
[rutube:movie] 1523: Downloading page 4
[rutube:movie] 1523: Downloading page 5
[rutube:movie] 1523: Downloading page 6
[rutube:movie] 1523: Downloading page 7
[rutube:movie] 1523: Downloading page 8
[rutube:movie] 1523: Downloading page 9
[rutube:movie] 1523: Downloading page 10
[rutube:movie] 1523: Downloading page 11
[rutube:movie] 1523: Downloading page 12
[rutube:movie] 1523: Downloading page 13
[rutube:movie] 1523: Downloading page 14
[rutube:movie] 1523: Downloading page 15
[rutube:movie] 1523: Downloading page 16
[download] Downloading playlist: Орел и решка
[rutube:movie] playlist Орел и решка: Collected 307 video ids (downloading 307 of them)
[download] Downloading video 1 of 307
[rutube] 00edfacb5263897caf516de2bcee327d: Downloading video JSON
[rutube] 00edfacb5263897caf516de2bcee327d: Downloading options JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: NOT FOUND (caused by <HTTPError 404: 'NOT FOUND'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python36\lib\site-packages\youtube_dl\extractor\common.py", line 390, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 1955, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python36\lib\urllib\request.py", line 537, in open
    response = meth(req, response)
  File "c:\python36\lib\urllib\request.py", line 647, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python36\lib\urllib\request.py", line 575, in error
    return self._call_chain(*args)
  File "c:\python36\lib\urllib\request.py", line 509, in _call_chain
    result = func(*args)
  File "c:\python36\lib\urllib\request.py", line 655, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

I can't download from Rutube.ru - it starts traversing the links, but immediately fails on download start of the 1-st video.

**Comment by remitamine** [comment]
this error appear in video wabpage:
> Sorry, this video is temporarily unavailable.

use `-i` option to skip errors.
