### ISSUE TITLE
Problem with downloading specific language subtitles for youtube videos

### ISSUE THREAD

**Issue by babadoctor** [rg3/youtube-dl#10023]
I can not download a specific language (english) when i youtube-dl subtitles for a youtube video!
It does not state anywhere which letters stand for what, so...
if anyone has the answer please let me know
It doesnt state anywhere what stands for the english language.
My code:
'youtube-dl --all-subs --skip-download --write-auto-sub https://www.youtube.com/user/LinusTechTips/videos'
In which it downloads 50 different languages.

**Comment by dstftw** [comment]
Don't use `--all-subs` if you don't need all subs. `--list-subs` for list of available langs and `--sub-lang` to select particular one.
