### ISSUE TITLE
Languages not correlating to the --list-subs output.

### ISSUE THREAD

**Issue by babadoctor** [rg3/youtube-dl#10036]
>Type youtube-dl --list-subs to find all available languages for a specific video.
Okay.
What does...

C:\Users\babadoctor>youtube-dl --list-subs https://www.youtube.com/watch?v=o2wj6xZhgng
[youtube] o2wj6xZhgng: Downloading webpage
[youtube] o2wj6xZhgng: Downloading video info webpage
[youtube] o2wj6xZhgng: Extracting video information
WARNING: video doesn't have subtitles
[youtube] o2wj6xZhgng: Looking for automatic captions
[youtube] o2wj6xZhgng: Downloading MPD manifest
Available automatic captions for o2wj6xZhgng:
Language formats
sr       vtt, ttml
jv       vtt, ttml
mk       vtt, ttml
fa       vtt, ttml
ro       vtt, ttml
la       vtt, ttml
ceb      vtt, ttml
fy       vtt, ttml
haw      vtt, ttml
ta       vtt, ttml
gl       vtt, ttml
id       vtt, ttml
sw       vtt, ttml
ps       vtt, ttml
nl       vtt, ttml
ny       vtt, ttml
xh       vtt, ttml
hmn      vtt, ttml
hy       vtt, ttml
gu       vtt, ttml
uz       vtt, ttml
sv       vtt, ttml
sk       vtt, ttml
tg       vtt, ttml
zu       vtt, ttml
kn       vtt, ttml
is       vtt, ttml
es       vtt, ttml
hi       vtt, ttml
km       vtt, ttml
ga       vtt, ttml
el       vtt, ttml
ko       vtt, ttml
sm       vtt, ttml
mn       vtt, ttml
yi       vtt, ttml
ne       vtt, ttml
am       vtt, ttml
so       vtt, ttml
su       vtt, ttml
tr       vtt, ttml
st       vtt, ttml
pt       vtt, ttml
te       vtt, ttml
uk       vtt, ttml
vi       vtt, ttml
pa       vtt, ttml
cy       vtt, ttml
ig       vtt, ttml
my       vtt, ttml
mr       vtt, ttml
si       vtt, ttml
sq       vtt, ttml
ms       vtt, ttml
az       vtt, ttml
sd       vtt, ttml
lo       vtt, ttml
mi       vtt, ttml
fr       vtt, ttml
co       vtt, ttml
lt       vtt, ttml
eu       vtt, ttml
kk       vtt, ttml
ur       vtt, ttml
ka       vtt, ttml
zh-Hans  vtt, ttml
et       vtt, ttml
ku       vtt, ttml
de       vtt, ttml
mt       vtt, ttml
bn       vtt, ttml
da       vtt, ttml
yo       vtt, ttml
ca       vtt, ttml
be       vtt, ttml
fi       vtt, ttml
hu       vtt, ttml
cs       vtt, ttml
sn       vtt, ttml
eo       vtt, ttml
lv       vtt, ttml
pl       vtt, ttml
bs       vtt, ttml
ru       vtt, ttml
ht       vtt, ttml
ky       vtt, ttml
hr       vtt, ttml
lb       vtt, ttml
en       vtt, ttml
mg       vtt, ttml
fil      vtt, ttml
gd       vtt, ttml
sl       vtt, ttml
th       vtt, ttml
ja       vtt, ttml
ha       vtt, ttml
af       vtt, ttml
zh-Hant  vtt, ttml
no       vtt, ttml
ar       vtt, ttml
bg       vtt, ttml
ml       vtt, ttml
iw       vtt, ttml
it       vtt, ttml

Can someone explain what these letters have anything to do with the languages that they are suppose to correlate to?

Which language is english?
This is not stated in the readme.

**Comment by rg3** [comment]
"en", which is present in the list. Please see this. It's a known convention.

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
