### ISSUE TITLE
Anime on Demand: No files found for series with sub and dub

### ISSUE THREAD

**Issue by Rikku1990** [rg3/youtube-dl#10031]
Make sure you are using the latest version: run youtube-dl --version and ensure your version is 2016.07.07. If it's not read this FAQ entry and update. Issues with outdated version will be rejected.

[x ] I've verified and I assure that I'm running youtube-dl 2016.07.07

Before submitting an issue make sure you have:

[x ] At least skimmed through README and most notably FAQ and BUGS sections
[x ] Searched the bugtracker for similar issues including closed ones
What is the purpose of your issue?

 [X]Bug report (encountered problems with youtube-dl)
 [ ] Site support request (request for adding support for a new      site)
 [ ]Feature request (request for a new functionality)
 [ ]Question
 [ ]Other

Hello, when i try to download a not-subtitle-only series from Anime on Demand, youtube-dl can not find the streams.

I have used the newest youtube-dl version.

```
youtube-dl https://www.anime-on-demand.de/anime/185 -u xxx -p xxx -f best
[AnimeOnDemand] Downloading login page
[AnimeOnDemand] Logging in as xxx
[AnimeOnDemand] 185: Downloading webpage
[download] Downloading playlist: Tekken - Blood Vengeance
[AnimeOnDemand] playlist Tekken - Blood Vengeance: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: Tekken - Blood Vengeance
```
and when I use this commandline
youtube-dl https://www.anime-on-demand.de/anime/185 -u xxx -p xxx -f best -v -g

```
youtube-dl https://www.anime-on-demand.de/anime/185 -u xxx -p xxx -f best -v -g
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.anime-on-demand.de/anime/185', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f', 'best', '-v', '-g']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.07.07
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
```
break it off here

The solution to the problem to fix this https://github.com/rg3/youtube-dl/commit/8c97e7efb6ab273f0b7c91f0aa9ac6869c911bf1
 not working with this video.

Regards

**Comment by dstftw** [comment]
For any further investigations you have to provide credentials of account capable to access the video.
