### ISSUE TITLE
Regression after test update on python 2.6

### ISSUE THREAD

**Issue by anisse** [rg3/youtube-dl#10030]
Hi @yan12125 , after you updated test_cmdline_umlauts in dfe5fa49a , it's now failing in Python 2.6 only. See this build:
https://travis-ci.org/anisse/youtube-dl/jobs/143000979
I'm not sure if it's the expected behaviour or not.

**Comment by yan12125** [comment]
Thanks for that. I've just found my mistake and fixed it in ec3518725b2d33c2bd664a965ead007e000dec37.
