### ISSUE TITLE
Youtube Playlist fails

### ISSUE THREAD

**Issue by ericMedeiros93** [rg3/youtube-dl#10043]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.09**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
WINDOWS: 

C:\Users\ericm\Desktop\Chinobix>youtube-dl -v https://www.youtube.com/watch?v=1b-qw1yV5yk&list=RD1b-qw1yV5yk&index=1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=1b-qw1yV5yk']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.07.07
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-80924-gb450b82, ffprobe N-80924-gb450b82
[debug] Proxy map: {}
[youtube] 1b-qw1yV5yk: Downloading webpage
[youtube] 1b-qw1yV5yk: Downloading video info webpage
[youtube] 1b-qw1yV5yk: Extracting video information
[youtube] 1b-qw1yV5yk: Downloading MPD manifest
[download] Akeboshi - Wind-1b-qw1yV5yk.mp4 has already been downloaded and merged
'list' is not recognized as an internal or external command,
operable program or batch file.
'index' is not recognized as an internal or external command,
operable program or batch file.

OS X:

Eric:Chinobix eric$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=1b-qw1yV5yk']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.07
[debug] Python version 2.7.10 - Darwin-15.5.0-x86_64-i386-64bit

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Trying to download a playlist from youtube yields the results above one Windows. Tried on 4 machines (two windows 10 pro, one windows 8.1 enterprise and one mac OS X 10.11). Downloading a single video works fine. On OS X youtube-dl get stuck on Downloading MPD manifest and hangs until I cancel it. youtube-dl and ffmpeg up to date on all machines.

**Comment by dstftw** [comment]
You have to either put the URL into quotes or manually escape all the special shell characters. Read [FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for details.
