### ISSUE TITLE
Format unavailable cause a error

### ISSUE THREAD

**Issue by vgrimmer** [rg3/youtube-dl#1005]
IMHO, the preferable format not found should jump to the default format if they are available, otherwise return with en error info. 

$ youtube-dl -f 22 --verbose  http://www.youtube.com/watch?v=zut2NLMVL_k
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', '22', '--verbose', 'http://www.youtube.com/watch?v=zut2NLMVL_k']
[debug] youtube-dl version 2013.07.05
[debug] Python version 2.7.3 - CYGWIN_NT-6.2-WOW64-1.7.18-0.263-5-3-i686-32bit
[debug] Proxy map: {}
[youtube] Setting language
[youtube] zut2NLMVL_k: Downloading video webpage
[youtube] zut2NLMVL_k: Downloading video info webpage
[youtube] zut2NLMVL_k: Extracting video information
ERROR: requested format not available; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbo                                                                                                                                            se flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 312, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 92, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 601, in _real_extract
    raise ExtractorError(u'requested format not available')
ExtractorError: requested format not available; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with th                                                                                                                                            e --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Format preference can now be specified with slash in order to jump to first available format, e.g. `-f 22/best`. See [format selection](https://github.com/rg3/youtube-dl#format-selection).
