### ISSUE TITLE
idowatch.net for seek

### ISSUE THREAD

**Issue by AnimAlf** [rg3/youtube-dl#10056]
> ### What is the purpose of your *issue*?
> - [ ] Bug report (encountered problems with youtube-dl)
> - [x ] Site support request (request for adding support for a new site)
> - [ ] Feature request (request for a new functionality)
> - [ ] Question
> - [ ] Other
> #########################################################

idowatch.net site works in generic. Pls, look at it :)) for resume

Greetings & thanks for your work

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
