### ISSUE TITLE
Windows 10 x64 - Fatal Python error: Py_Initialize: unable to load the file system codec

### ISSUE THREAD

**Issue by esamo** [rg3/youtube-dl#10053]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.09.2**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Windows\system32>youtube-dl -v
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'

Current thread 0x000019a0 (most recent call first):
...
<end of log>
```

---

Regards & respect

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/blob/master/README.md#installation

**Comment by weituotian** [comment]
thanks for this issues!
i solve my problem.
`except ` should be bold

**Comment by unknown81311** [comment]
for me it still happens even if its in my user directory??
im trying to make a url protocol that runs it yt-dl from the browser
running it manually it works fine but I get the error trying to use the browser to do it.
