### ISSUE TITLE
"Rental" videos not supported

### ISSUE THREAD

**Issue by SelfDestructor** [rg3/youtube-dl#10059]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.09.2*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.09.2**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
U:\_Video Tools\YouTube-DL>youtube-dl -u xxxxxx https://www.youtube.com/watch?v=i1Ko8UG-Tdo --verbose
[debug] System config: []
[debug] User config: ['-o', 'U:\\_Video Tools\\YT Downloads\\%(uploader)s - %(title)s (%(id)s) %(resolution)s.%(ext)s', '-f', 'bestvideo+bestaudio', '--all-sub', '--convert-subs', 'srt', '--embed-subs']
[debug] Command-line args: ['-u', 'PRIVATE', 'https://www.youtube.com/watch?v=i1Ko8UG-Tdo', '--verbose']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.07.09.2
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-78358-g674cc26
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
[youtube] i1Ko8UG-Tdo: Downloading webpage
[youtube] i1Ko8UG-Tdo: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: "rental" videos not supported; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpumvs6cap\build\youtube_dl\YoutubeDL.py", line 681, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpumvs6cap\build\youtube_dl\extractor\common.py", line 345, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpumvs6cap\build\youtube_dl\extractor\youtube.py", line 1382, in _real_extract
youtube_dl.utils.ExtractorError: "rental" videos not supported; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=i1Ko8UG-Tdo
- Playlist: https://www.youtube.com/playlist?list=PLOl4b517qn8hr_5QTAaGdGJhxU-zMka-9

---

### Description of your *issue*, suggested solution and other information

As of last weekend, paid for YouTube Red videos returns the error **"rental" videos not supported"**.
On June 30th 2016 with back then's latest version, downloading purchased videos worked fine but last Sunday (July 3rd 2016) I got the error above and have not been able to download any YouTube Red videos since then.

The videos in question are paid for by myself with the correct account and accessible in my country.

Also when signing in, it accepts my username and password but the 2-step verification request does not show up after entering my password. In the past it has shown up at every login.

Using a cookie file does not help either.

**Comment by dstftw** [comment]
Does it work with 2016.07.11?

**Comment by SelfDestructor** [comment]
It does! Thank you!
