### ISSUE TITLE
Video url saved with metadata [feature request]

### ISSUE THREAD

**Issue by philipzae** [rg3/youtube-dl#10061]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.11*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

It would be useful if the video url was saved with the metadata, so it is easy to find the same video irrespective of the formatting of the filename.

**Comment by dstftw** [comment]
Original video URL is already present in `--dump-json` as `webpage_url`.

**Comment by philipzae** [comment]
Though available in `--dump-json`, my request was intended to be about having it embedded into the file with `--add-metadata`.

**Comment by dstftw** [comment]
`--add-metadata` [adds](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/postprocessor/ffmpeg.py#L411) it either.

**Comment by philipzae** [comment]
Unfortunately `add('purl', 'webpage_url')` isnt working as URL isnt getting added to the file.

`youtube-dl -f 43 https://www.youtube.com/watch?v=M3Yx_CGxRIU --add-metadata`

![ghex youtube_dl](https://cloud.githubusercontent.com/assets/4412114/17083990/7ae0eea0-51c2-11e6-8ad4-54be484df23e.png)

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/2368#issuecomment-131857469

**Comment by philipzae** [comment]
sorry my bad, the screenshot was from `-f 18` (mp4) and not `-f 43` (webm), so its not related to #2368.
