### ISSUE TITLE
403 Forbidden when going through Tor

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#10069]
Trying to access Norwegian content using Tor while abroad. My effective IP is Norwegian, but I get a 403 from the host (Akamai). Do they blacklist Tor IPs, or what could be the cause?

Found similar posted issues, but posting this in case this is a unique issue. Using a version that's three days old since I'm on Homebrew (doubt that's the cause). Let me know how I can be of further help.

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--proxy', u'socks5://127.0.0.1:9050/', u'--verbose', u'https://tv.nrk.no/serie/tidsbonanza/DMPF71004116/sesong-1/episode-11']
[debug] Encodings: locale UTF-8, fs utf-8, out None, pref UTF-8
[debug] youtube-dl version 2016.07.09.2
[debug] Python version 2.7.12 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0, ffprobe 3.0, rtmpdump 2.4
[debug] Proxy map: {u'http': u'socks5://127.0.0.1:9050/', u'https': u'socks5://127.0.0.1:9050/'}
[NRKTV] DMPF71004116: Downloading media element JSON
[NRKTV] DMPF71004116: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[NRKTV] DMPF71004116: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[NRKTV] DMPF71004116: Downloading f4m manifest
ERROR: Unable to download f4m manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
Can you watch this video in browsers with Tor? If I remember it correctly Tor chooses a random exit node in each connection so it may be outside Norway.

**Comment by dstftw** [comment]
This can be forced with `ExitNodes {no}` in `.torrc`.

**Comment by yan12125** [comment]
@dstftw Much thanks for that! It's definitely helpful.

**Comment by dstftw** [comment]
There are only [8 exit nodes from NO](https://torstatus.blutmagie.de/index.php) all of which are banned by NRK.

**Comment by forthrin** [comment]
The eternal cat and mouse game. I suspected as much. You really need to be ahead to win at this...
