### ISSUE TITLE
New regression: dbtv

### ISSUE THREAD

**Issue by anisse** [rg3/youtube-dl#10064]
Maybe introduced by 8a8590a (ping @remitamine )

See this build:
https://travis-ci.org/anisse/youtube-dl/jobs/143927550

**Comment by remitamine** [comment]
this is already fixed with f1b4af7d79e5ee5d74fddf5fe46ce4c6f661ad8d.

**Comment by anisse** [comment]
Thanks, sorry I should have checked.

**Comment by remitamine** [comment]
it's actually my fault, the order of the commits was wrong.
