### ISSUE TITLE
Inconsistent quality behavior?

### ISSUE THREAD

**Issue by Tanksenior** [rg3/youtube-dl#10065]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.11*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Hello, I have a little question about what seems to be inconsistent behavior regarding format/quality selection. Or perhaps my expectations about said options are inaccurate? I hope someone can help clarify if that is the case.

I'll explain/show my actions and results below.

Video used as example: https://www.youtube.com/watch?v=f25R9Gl6FWc

Download without any parameters(for reference):
http://imgur.com/GS4fSku

Media info:
http://imgur.com/kT0uW9R

Now for the interesting part, download with parameters taken from the "Format selection examples" section. (https://github.com/rg3/youtube-dl#format-selection-examples)

> \# Download best mp4 format available or any other best if no mp4 available
$ youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'

http://imgur.com/VOrVs9N

Media info:
http://imgur.com/LnjUqHl

Now for the final result using -f best
http://imgur.com/LVQP4QI

Media info:
http://imgur.com/BDuaDNx

Note the significantly larger file size and higher bit rates for both audio and video.

Why does "\# Download best mp4 format available or any other best if no mp4 available" not actually return the best quality mp4 available but -f best does? Am I misunderstanding things? Am I doing something wrong? Are my expectations off?

Please explain if you can, thanks in advance.

**Comment by dstftw** [comment]
Read [format selection](https://github.com/rg3/youtube-dl#format-selection). It explains everything or use search.

**Comment by Tanksenior** [comment]
Do you honestly think I didn't read that about 100 times before posting this?

Nothing in there explains what I'm asking.

Kind of ironic since you obviously didn't take the time to actually read my questions.

**Comment by Hrxn** [comment]
Well, the format selection guide is correct. But results depend on the site/extractor.
And not even all videos on YouTube, for example, are available in all formats. There is some variation, partially depending on the age of the video upload.

You can list the available formats for any chosen video with `-F,` or `--list-formats`

**Comment by yan12125** [comment]
It's a limitation of youtube-dl: sometimes the actual quality is unknown until the file is downloaded. In this example, ```bestvideo``` is:
```
136          mp4        1280x720   720p  278k , avc1.4d401f, 30fps, video only, 48.46MiB
```
And ```best``` is:
```
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)
```
As both formats have the same dimension, the only factor is their bitrates. Unfortunately, YouTube does not provide the bitrate information for format 22 of this video. In most cases, ```bestvideo``` is better than ```best```, so we make it the default. This video is a good counterexample, but we can do nothing without sufficient information. If you know how to determine video qualities without actual downloading, please propose it. There are already lots of related feature requests. For example, a not-so-good idea was proposed at #6055. (It downloads some portion of the video, which slows down the extraction step.)

**Comment by Tanksenior** [comment]
I see, thank you so much for explaining yan12125! That's the information I was looking for.

Until a solution is found I guess it's going to be a bit trial-and-error to find the highest quality in some cases, I'm just happy to know why it happens though, thanks again.

**Comment by VitCN** [comment]
Downloading portions of the video to test the bit rates doesn't seem like such a bad solution to this and a few additional megabytes is rather tame. I think having it as an option would be great.

**Comment by yan12125** [comment]
> bigger is usually better

Not always true. Comparing bitrates among different codecs is meaningless. See https://github.com/rg3/youtube-dl/issues/6018#issuecomment-114008839 and https://en.wikipedia.org/wiki/Video_quality. You need some mathematical metrics, such as SSIM, PSNR, etc.
