### ISSUE TITLE
Downloading 4K resolution not working

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [rg3/youtube-dl#10071]
When trying to download a 4K video in full resolution, using `-f best`, the video gets only downloaded with 1280x642.
The link I've used: https://www.youtube.com/watch?v=gGqFUDYZ8yk 

![image](https://cloud.githubusercontent.com/assets/5278928/16769748/3fcb3798-484a-11e6-9bf9-d3adb5fc0556.png)

**Comment by dstftw** [comment]
`-f best` won't download best overall quality. Do not pass any `-f`. [FAQ](https://github.com/rg3/youtube-dl#format-selection).

**Comment by TRox1972** [comment]
Try `-f bestvideo+bestaudio` or don't specify `-f` (4K video is available in video-only format, so it won't be chosen with `-f best`)

**Comment by Karlheinzniebuhr** [comment]
Thanks for the clarification @TRox1972 
It seems to work without passing -f
