### ISSUE TITLE
Unable to download youtube playlist

### ISSUE THREAD

**Issue by kamalsomani** [rg3/youtube-dl#10078]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.11*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [*] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
ksomani:youtube-dl kamalsomani$ ./youtube-dl --yes-playlist -vi https://www.youtube.com/watch?v=y0yYQxvNBmA&list=PL0lNJEnwfVVMfDKsTKIvJmBQWmhYLsM4A
[1] 13765
ksomani:youtube-dl kamalsomani$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--yes-playlist', u'-vi', u'https://www.youtube.com/watch?v=y0yYQxvNBmA']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.11
[debug] Python version 2.7.10 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4
[debug] Proxy map: {}
[youtube] y0yYQxvNBmA: Downloading webpage
[youtube] y0yYQxvNBmA: Downloading video info webpage
[youtube] y0yYQxvNBmA: Extracting video information
[youtube] y0yYQxvNBmA: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Mega Tutorial - Build a Web App - Introduction-y0yYQxvNBmA.mkv has already been downloaded and merged
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information
When ever I try to download a playlist from youtube, it only download 1st video and stops after that, it dose not continue further. It used to work earlier I guess2 months back :(.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by kamalsomani** [comment]
wow ... what an instant response.
