### ISSUE TITLE
--password does not allow for asking interactively

### ISSUE THREAD

**Issue by JohnScott623** [rg3/youtube-dl#10075]
`youtube-dl`'s `--help` page says

`-p, --password PASSWORD          Account password. If this option is left out, youtube-dl will ask interactively.`

This means that, when the argument to `-p` (and `--password`, respectively) is omitted, it is to prompt for the user's password for downloading a video. This is a useful feature to have, as typing a password as plain text into one's shell is insecure, especially if it saves a log of commands run (i.e. GNU Bash).

However, with the current latest stable version of `youtube-dl`, the following error can be seen when attempting to make `youtube-dl` prompt for the password.

`youtube-dl: error: --password option requires an argument`

However, the `--help` page states that `--password` should not require an argument so that it can allow one to be prompted for a password. This shows a conflict between `youtube-dl`'s behavior and its documentation.

**Comment by dstftw** [comment]
Left out means `-p` should not be passed in command line at all only `-u`.

**Comment by phihag** [comment]
Note that the `--help` says option, not argument. The error message should make that distinction clear, but nevertheless, if you can suggest a better wording, we may use that.
