### ISSUE TITLE
Unable to download vedios using youtube-dl

### ISSUE THREAD

**Issue by YadavKamal** [rg3/youtube-dl#10070]

**Comment by YadavKamal** [comment]
![screenshot from 2016-07-12 19 06 18](https://cloud.githubusercontent.com/assets/20402730/16768936/109ea33c-4864-11e6-81c5-182262c3b9d7.png)

**Comment by YadavKamal** [comment]
help me out

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by YadavKamal** [comment]
where to find it sir.
