### ISSUE TITLE
An existing connection was forcibly closed by remote host.

### ISSUE THREAD

**Issue by ana9t** [rg3/youtube-dl#10084]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.13*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl.exe -v -c -f 1-540 https://www.lynda.com/Security-tutorials/Foundations-IT-Security-Core-Concepts/410329-2.html --username=xxxxxx@gmail.com --password=aayyyy
([download] Downloading video 15 of 24
[lynda] 430060: Downloading video JSON
[lynda] 430060: Checking 0-720 video format URL
[lynda] 430060: Checking 0-360 video format URL
[lynda] 430060: Checking 0-540 video format URL
[lynda] 430060: Checking 2-720 video format URL
[lynda] 430060: Checking 2-360 video format URL
[lynda] 430060: Checking 2-540 video format URL
[lynda] 430060: Checking 1-720 video format URL
ERROR: Unable to download webpage: [WinError 10054] An existing connection was forcibly closed by the remote host (caused by ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\YoutubeDL.py", line 1955, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\utils.py", line 838, in http_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1186, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1227, in getresponse
  File "C:\Python\Python34\lib\http\client.py", line 386, in begin
  File "C:\Python\Python34\lib\http\client.py", line 348, in _read_status
  File "C:\Python\Python34\lib\socket.py", line 378, in readinto


C:\youtube-dl>''')
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

**Comment by bluequadustglobal** [comment]
[verbose_log_1.txt](https://github.com/rg3/youtube-dl/files/367017/verbose_log_1.txt)
[verbose_log_2.txt](https://github.com/rg3/youtube-dl/files/367018/verbose_log_2.txt)

**Comment by teenzy** [comment]
Same happens for PluralSight
[verbose_log_1.txt](https://github.com/rg3/youtube-dl/files/367042/verbose_log_1.txt)
[verbose_log_2.txt](https://github.com/rg3/youtube-dl/files/367043/verbose_log_2.txt)

**Comment by dstftw** [comment]
This indicates an issue with your internet connection. Can you watch it in browser? If you are using a proxy you must pass with `--proxy`.

**Comment by ana9t** [comment]
yes got it.
It may be internet connection because now its working fine.
Not using any proxy.
