### ISSUE TITLE
New regression: rtve

### ISSUE THREAD

**Issue by anisse** [rg3/youtube-dl#10097]
Test rtvealacarta is a new fail (ping @jaimeMF ) since maybe c39b2ed9901 or 233b58dec7362.
See this build:
https://travis-ci.org/anisse/youtube-dl/jobs/145224376

**Comment by anisse** [comment]
It's more likely to be introduced by c39b2ed990105e640456f126321ef3d771884405.

**Comment by jaimeMF** [comment]
I have reverted the change, thanks for the report.
