### ISSUE TITLE
soundcloud - download explicitly allowed tracks only

### ISSUE THREAD

**Issue by mitsukuri** [rg3/youtube-dl#10113]
Is it possible to download only those tracks from Soundcloud that are _explicitly_ marked as downloadable by author? I see there is a `--match-filter` option, tried `--match-filter "download"`, which didn't work (unsurprisingly so). If it's impossible right now, it would be a nice addition for those respecting authors' decisions. There are enough profiles where a fraction of tracks are allowed for download - it's no good combing them manually when such a brilliant tool exists.

**Comment by yan12125** [comment]
Can you give some concrete examples?

**Comment by mitsukuri** [comment]
sure!
https://soundcloud.com/shimmering-moods-records
https://soundcloud.com/nitenichiryu

**Comment by dstftw** [comment]
One of the main purposes of youtube-dl is to be able to download from places that does not provide you with explicit ability to do so thus this option will be useless for most of the extractors.
Moreover if you really want to respect author's decision then also respect a way author expects you to download, i.e. using a website.

**Comment by yan12125** [comment]
Hmm actually it's possible:
```
$ youtube-dl -v -f download https://soundcloud.com/shimmering-moods-records --ignore-errors                 
```

**Comment by mitsukuri** [comment]
**dstftw**, I guess I've triggered some emotions with the phrase "_respect author's decision_". Sorry about that, I should have be cautious saying that out loud here. Mind you, I'm not against the ability to download anything without someone's explicit permission.
Now, to the strawman about the way authors expecting their tracks to be downloaded. I got my own soundcloud profile, and yes, I upload my own tracks there. When I mark my tracks as downloadable, there's nothing in the UI, nor is there in my mind as to how exactly my listeners would download them. I don't care if they download them from the site or by some h4Xx0r means, including binary telepathy. I just want them to be freely available. Sure, even those tracks I don't mark as such can be downloaded and I don't mind that either. That 'download' button is just about 'fair play' for those who care, akin to opensource licenses.

**Comment by mitsukuri** [comment]
**yan12125**, wow, that seems to work, thank you! Care to explain how? Doesn't look obvious :)

**Comment by yan12125** [comment]
The downloadable link has the format ID ```download```. ```-f download``` tries to choose this format. If not found an error is raised. ```--ignore-erros``` can ignore all errors. The overall effect is just what you want.

**Comment by mitsukuri** [comment]
Thank you even more! I would like to add this to the readme.md. Any thoughts as to which section this should go to, or if this is a good idea at all?

**Comment by yan12125** [comment]
There's an FAQ section, while I guess it's not so common to be in FAQ.

**Comment by mitsukuri** [comment]
That's what I thought too. Maybe adding it to _FORMAT SELECTION_ section as a remark somewhere at the bottom would do?

**Comment by yan12125** [comment]
Such a usage is site-specific. Format selection should contain generic information only.

**Comment by mitsukuri** [comment]
How about adding a _SITE SPECIFIC_ section between _VIDEO SELECTION_ and _FAQ_? I guess it might grow in the future as I think many sites are not without their quirks.

**Comment by yan12125** [comment]
> I guess it might grow in the future as many sites are not without their quirks.

That's my concern. README.md is already too long. [github search](https://github.com/rg3/youtube-dl/search?q=soundcloud&type=Issues&utf8=%E2%9C%93) should be enough.
