### ISSUE TITLE
Converted MP3 modified date and created date.

### ISSUE THREAD

**Issue by jx2014** [rg3/youtube-dl#10112]
I downloaded a play list and convert it to MP3 using this command line:

time youtube-dl -ci --playlist-start=1 --playlist-end=-1 -x --audio-format mp3 https://www.youtube.com/playlist?list=someplaylist -o "%(title)s.%(playlist_index)s" | tee log.log

All is well, except the mp3 files' "Date Modified" and "Date Created" is the date when the media was uploaded to the server. How do I make the timestamp for at least "Date Created" to be the date the mp3 file was actually created?

**Comment by yan12125** [comment]
```--no-mtime``` should work.
```
--no-mtime          Do not use the Last-modified header to set the file modification time
```
