### ISSUE TITLE
Downloading flv and converting causes re-downloads. Error on CrunchyRoll.

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#10120]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.17**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I ran into two issues on a download from crunchyroll. One are not a function of crunchyroll, but a function of downloading flv and converting to mp4:

1. Repeating the download command does not skip files that are already downloaded. When the last episode did not download the first time, I tried re-fetching, only to see it download episoide 1 again.

EDIT: Not an error; CrunchyRoll now requires signing up for the newest stuff.
[s]2. An error on the last one: 
```
keybounceMBP:ReZero michael$ youtube-dl -v --playlist-start 17 http://www.crunchyroll.com/rezero-starting-life-in-another-world-
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=480]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--write-sub', u'--write-auto-sub', u'--sub-lang', u'en,enUS', u'--sub-format', u'srt/ass/best', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Command-line args: [u'-v', u'--playlist-start', u'17', u'http://www.crunchyroll.com/rezero-starting-life-in-another-world-']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.17
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[crunchyroll:playlist] rezero-starting-life-in-another-world-: Downloading webpage
[download] Downloading playlist: Re:ZERO -Starting Life in Another World-
[crunchyroll:playlist] playlist Re:ZERO -Starting Life in Another World-: Collected 17 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Crunchyroll] 702431: Downloading webpage
ERROR: This is a sample clip. To watch the full video, start a free trial today!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/crunchyroll.py", line 280, in _real_extract
    raise ExtractorError(note_m)
ExtractorError: This is a sample clip. To watch the full video, start a free trial today!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
[/s]

**Comment by yan12125** [comment]
> Repeating the download command does not skip files that are already downloaded. When the last episode did not download the first time, I tried re-fetching, only to see it download episoide 1 again.

Sounds like ```--download-archive``` is what you need.

> An error on the last one: 

I can't watch this video due to georestriction. I guess the message "This is a sample clip. To watch the full video, start a free trial today!" have pointed out the problem.

**Comment by keybounce** [comment]
Ha. Going to the site, it turns out that CrunchyRoll now has a "You must sign up for the newest videos" feature. Even at the site. So YouTube-dl is working correctly.

As for --download-archive: Thanks for pointing that one out. Note that for everything else, yt-dl already detects that the video is already downloaded, so I've been relying on that auto-detection.

**Comment by yan12125** [comment]
In general youtube-dl need to analyze web pages to know whether a video is already downloaded or not. ```--download-archive``` compares video IDs with those in the archive file. Such IDs are site-specific. They are less accurate and it's possible to miss some videos.
