### ISSUE TITLE
How to set a SOCKS5 process?

### ISSUE THREAD

**Issue by N1CEyk** [rg3/youtube-dl#10123]
I want to set a SOCKS5 proxy ,but the parameter ,--proxy URL, can only set HTTP/HTTPS proxy.

**Comment by yan12125** [comment]
Use ```--proxy socks5://ip:port/```. See [network options](https://github.com/rg3/youtube-dl/blob/master/README.md#network-options) for more information.

**Comment by N1CEyk** [comment]
I don't know why? See below
C:\Users\Administrator\Desktop>youtube-dl.exe --proxy socks5://
127.0.0.1:1080 -F https://www.youtube.com/watch?v=DCgbD4HE-WQ
[youtube] DCgbD4HE-WQ: Downloading webpage
ERROR: Unable to download webpage: <urlopen error EOF occurred in violation
of protocol (_ssl.c:590)> (caused by URLError(SSLEOFError(8, u'EOF occurred
in violation of protocol (_ssl.c:590)'),))

2016-07-19 17:39 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
Which proxy software are you using? Also, always include the ```-v``` flag in your commands to print more debugging information.

**Comment by N1CEyk** [comment]
shadowsocks
C:\Users\Administrator\Desktop>youtube-dl.exe -v  --proxy socks5://
127.0.0.1:1080 -F https://www.youtube.com/watch?v=DCgbD4HE-WQ
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--proxy', u'socks5://127.0.0.1:1080',
u'-F', u'https://www.youtube.com/watch?v=DCgbD4HE-WQ']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77234-g906c0b7
[debug] Proxy map: {u'http': u'socks5://127.0.0.1:1080', u'https':
u'socks5://127.0.0.1:1080'}
[youtube] DCgbD4HE-WQ: Downloading webpage
[youtube] DCgbD4HE-WQ: Downloading video info webpage
[youtube] DCgbD4HE-WQ: Extracting video information
[youtube] DCgbD4HE-WQ: Downloading DASH manifest
WARNING: [youtube] DCgbD4HE-WQ: Skipping DASH manifest:
ExtractorError(u"Could not download DASH manifest: <urlopen error EOF
occurred in violation of protocol (_ssl.c:590)> (caused by
URLError(SSLEOFError(8, u'EOF occurred in violation of protocol
(_ssl.c:590)'),))",)
[info] Available formats for DCgbD4HE-WQ:
format code  extension  resolution note
249          webm       audio only DASH audio   54k , opus @ 50k, 3.54MiB
250          webm       audio only DASH audio   72k , opus @ 70k, 4.48MiB
140          m4a        audio only DASH audio  128k , m4a_dash container,
aac  @128k, 8.94MiB
171          webm       audio only DASH audio  133k , vorbis@128k, 7.98MiB
251          webm       audio only DASH audio  140k , opus @160k, 8.51MiB
278          webm       256x144    DASH video  111k , webm container, vp9,
30fps, video only, 7.04MiB
160          mp4        256x144    DASH video  113k , avc1.4d400c, 30fps,
video only, 7.74MiB
133          mp4        426x240    DASH video  255k , avc1.4d4015, 30fps,
video only, 17.26MiB
242          webm       426x240    DASH video  257k , vp9, 30fps, video
only, 16.27MiB
243          webm       640x360    DASH video  484k , vp9, 30fps, video
only, 29.96MiB
134          mp4        640x360    DASH video  640k , avc1.4d401e, 30fps,
video only, 31.12MiB
244          webm       854x480    DASH video  925k , vp9, 30fps, video
only, 53.70MiB
135          mp4        854x480    DASH video 1173k , avc1.4d401f, 30fps,
video only, 58.10MiB
247          webm       1280x720   DASH video 1888k , vp9, 30fps, video
only, 105.01MiB
136          mp4        1280x720   DASH video 2345k , avc1.4d401f, 30fps,
video only, 105.34MiB
302          webm       1280x720   DASH video 3161k , vp9, 60fps, video
only, 172.95MiB
248          webm       1920x1080  DASH video 3348k , vp9, 30fps, video
only, 187.25MiB
298          mp4        1280x720   DASH video 3502k , h264, 60fps, video
only, 171.50MiB
137          mp4        1920x1080  DASH video 4381k , avc1.640028, 30fps,
video only, 185.93MiB
303          webm       1920x1080  DASH video 5317k , vp9, 60fps, video
only, 304.66MiB
299          mp4        1920x1080  DASH video 5802k , h264, 60fps, video
only, 298.92MiB
17           3gp        176x144    small ,  mp4a.40.2, mp4v.20.3

2016-07-19 18:09 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
> [debug] youtube-dl version 2015.12.13

SOCKS5 support is added in May 2016. Please [update to the latest version](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) (2016.07.17)

**Comment by N1CEyk** [comment]
C:\Users\Administrator\Desktop>youtube-dl.exe -U
Updating to version 2016.07.17 ...
ERROR: no write permissions on youtube-dl.exe

2016-07-19 18:25 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
Seems the same problem as #2718. In short: updating is broken if the current directory (C:\Users\Administrator\Desktop) is not where youtube-dl.exe is. This is also fixed in May 2016, but your version is too old.

**Comment by N1CEyk** [comment]
My problem isn't like that.I run it, but it doesn't work in everywhere.I
 discover it even can't download the video.See below

C:\Users\Administrator\Desktop>youtube-dl.exe -U
ERROR: can't find the current version. Please try again later.

C:\Users\Administrator\Desktop>youtube-dl.exe
https://www.youtube.com/watch?v=kJ1XFnrssvE
[youtube] kJ1XFnrssvE: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL:
CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused
by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate
verify failed (_ssl.c:590)'),))

2016-07-19 18:46 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
Hmm I've once heard that Github subdomains are blocked in Mainland China. Can you download this file? https://rg3.github.io/youtube-dl/update/LATEST_VERSION

**Comment by N1CEyk** [comment]
So interseting.hmmmm.
Thank u all the same.I actually put it in environmental variable. After
looking at that issue,I try to update it in its original directory and be
with "--no-check-certificate".Then it update successfully.
I observe it is ok to update in everywhere,I have confused it so
much.Whatever the process is,I really thanks for your giving me a hand.

2016-07-19 20:01 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by N1CEyk** [comment]
I want the second line which is explannatin in youtube-dl.conf dosen't
work,how to do it?

This is youtube-dl.conf's text.
--proxy socks5://127.0.0.1:1080
？?--proxy 127.0.0.1:8087？?
--console-title
-i
--socket-timeout 75

2016-07-19 20:28 GMT+08:00 Yk Yang <n1ce0571@gmail.com>:

**Comment by yan12125** [comment]
If the protocol is not specified, the actual protocol depends on the connection. http://127.0.0.1:8087 is used for HTTP connections, and https://127.0.0.1:8087 is used for HTTPS connections. AFAIK Shadowsocks uses SOCKS only, so neither works.

**Comment by N1CEyk** [comment]
There is a new problem to happren.It's OK When I download video with
Shadowsocks
Proxy,however, when I do it with http://127.0.0.1:8087 ,it has problem
that is "ERROR: Unable to download webpage: <urlopen error [SSL:
CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused
by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate
verify failed (_ssl.c:600)'),))"
I search this kind of problem and discover its original is to
update openssl or uninstall  and reinstall it with command,rm -rf
/usr/local/etc/openssl and brew install openssl,in Unix.
Unforunately,my system is Windos,I don,t know how to do that in Windos

2016-07-19 22:00 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
Shadowsocks uses SOCKS and http://127.0.0.1:8087 sounds like XX-Net - Shadowsocks has no built-in HTTP proxies. If it's really XX-Net, ```--no-check-certificate``` is inevitable for all HTTPS connections.

**Comment by N1CEyk** [comment]
Yes it's XX-NET.That's OK.I will keep on trying it.Thanks

2016-07-19 22:33 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by N1CEyk** [comment]
Eventualy I watch this,https://www.youtube.com/watch?v=H8GxM9ApkYc,that
help me install Openssl.Thank you all right.

2016-07-19 23:17 GMT+08:00 Yk Yang <n1ce0571@gmail.com>:

**Comment by yan12125** [comment]
Congratulations :)

**Comment by yan12125** [comment]
Note to myself: according to GreatFire.org, https://rg3.github.io/youtube-dl/update/LATEST_VERSION is [not completely blocked in China](https://zh.greatfire.org/https/rg3.github.io/youtube-dl/update/LATEST_VERSION). Otherwise we'll have to find another host for binaries.

**Comment by N1CEyk** [comment]
what's your purpose?

2016-07-20 16:02 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
We're currently considering moving binary files from Github to Cloudflare. (#9690) If Github.com is blocked in China, this move becomes urgent.

**Comment by N1CEyk** [comment]
I have tried to surf Github.com without proxy,unifortunately,Github.com is
acturally  blocked in China.

2016-07-20 16:11 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
Got it. Time to reconsider #9690.

**Comment by mehhrad** [comment]
boo yeah youtube-dl with socks5 is way faster than vpns ... thanks
