### ISSUE TITLE
Support youtube shared link: https://www.youtube.com/shared?ci=8A940MXKFmQ

### ISSUE THREAD

**Issue by Khang-NT** [rg3/youtube-dl#10137]
YouTube mobile app have updated new sharing url pattern like this:
`https://www.youtube.com/shared?ci=8A940MXKFmQ`

This url not includes video id like old one (https://youtu.be/videoid).

Could you guys add feature to get video with shared url like above.

Thanks!

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by jsiva001** [comment]
Hi am also facing that same issue, could you please give me the solution for that?

**Comment by dstftw** [comment]
Did you even read the answer?

**Comment by jsiva001** [comment]
sorry i didn't understand , i have used youtube player api to be playing  video by video id so in that how do i get the video id from the sharing url? and has any other way to do? Please help.
