### ISSUE TITLE
Restructured website breaks automated rebuilds on packman build service

### ISSUE THREAD

**Issue by lemmy04** [rg3/youtube-dl#10134]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.17**

IRRELEVANT TO MY ISSUE, SEE ABOVE
### Before submitting an *issue* make sure you have:

IRRELEVANT TO MY ISSUE, SEE ABOVE

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [X] Other

---

I have set up an automated build process that generates new RPM packages for youtube-dl every time the version number. This relies on the past structure of the downloads link.

Now that everything is done on github, it does not work anymore.

Please find a way to provide the latest version as http://youtube-dl.org/latest/youtube-dl.tar.gz again, without all the redirects that the openSUSE build service can't handle.

**Comment by yan12125** [comment]
The new link for the tarball is at http://yt-dl.org/downloads/latest/youtube-dl-2016.07.17.tar.gz. Is there any technical issue in the OpenSUSE build service for the new URL?

**Comment by lemmy04** [comment]
I had to adapt the automation in my build job a bit, but now all is well.

**Comment by dstftw** [comment]
We never provided tarballs as http://youtube-dl.org/latest/youtube-dl.tar.gz only http://youtube-dl.org/latest/youtube-dl-VERSION.tar.gz. We don't host files on youtube-dl.org anymore thus you'll have to fix your builder to support redirects.

**Comment by lemmy04** [comment]
it is already fixed in my build process.
