### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by zouhua** [rg3/youtube-dl#10149]
[root@vagrant-centos65 vagrant]# youtube-dl --proxy socks5://127.0.0.1:1080/ -F https://www.youtube.com/watch?v=eFphrMVWB3E
	[youtube] eFphrMVWB3E: Downloading webpage
	[youtube] eFphrMVWB3E: Downloading video info webpage
	[youtube] eFphrMVWB3E: Extracting video information
	[youtube] eFphrMVWB3E: Downloading js player en_US-vflIB5TLK
	ERROR: Signature extraction failed: Traceback (most recent call last):
	  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
	    video_id, player_url, s
	  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
	    res = self._parse_sig_js(code)
	  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
	    initial_function = jsi.extract_function(funcname)
	  File "/usr/local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
	    raise ExtractorError('Could not find JS function %r' % funcname)
	youtube_dl.utils.ExtractorError: Could not find JS function 'Yy'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	 (caused by ExtractorError("Could not find JS function 'Yy'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by shanemikel** [comment]
Would you mind explaining this?

**Comment by yan12125** [comment]
Usually it's due to out-dated youtube-dl version.
