### ISSUE TITLE
Wait for user-confirm before download function

### ISSUE THREAD

**Issue by spookyahell** [rg3/youtube-dl#10147]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### Description of your *issue*, suggested solution and other information
It would be nice to have an option in youtube-dl,
that could be something like "--wait-before-download" which would work like this:
URL fetching and information getting, then wait for any keystroke, a specific letter and then continue with the actual download process

One helpful situation is when using system proxy for fetching information and download links,
when proxy isn't needed for actual content.

**Comment by dstftw** [comment]
This won't prevent youtube-dl from using proxy since it's taken from environment youtube-dl is started with. Moreover in case of long confirmation time download links may expire for extractors that generate such links.

**Comment by spookyahell** [comment]
What about ffmpeg? Same thing there? I mean: Also gets proxy from youtube-dl startup?

**Comment by dstftw** [comment]
Yes. When youtube-dl starts ffmpeg it passes [an env based on own settings](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/downloader/external.py#L203-L213).
