### ISSUE TITLE
Functionality broken down

### ISSUE THREAD

**Issue by nisal** [rg3/youtube-dl#10143]
C:\Users\Housing\Downloads>youtube-dl.exe --verbose http://www.youtube.com/watch?v=9bZkp7q19f0
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.youtube.com/watch?v=9bZkp7q19f0']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.07.22
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 9bZkp7q19f0: Downloading webpage
ERROR: Unable to download webpage: (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:600)'),))
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpra3yzk2s\build\youtube_dl\extractor\common.py", line 394, in _request_webpage
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpra3yzk2s\build\youtube_dl\YoutubeDL.py", line 1985, in urlopen
File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpra3yzk2s\build\youtube_dl\utils.py", line 1002, in https_open
File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open 

it works fine with another version on same machine: 

G:>job\lion.exe --verbose https://www.youtube.com/watch?v=9mdJV5-eias
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=9mdJ
V5-eias']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.05.15
[debug] Python version 2.7.8 - Windows-7-6.1.7600
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 9mdJV5-eias: Downloading webpage
[youtube] 9mdJV5-eias: Extracting video information
[debug] Invoking downloader on u'https://r2---sn-h557snel.googlevideo.com/videop
layback?ip=111.93.141.82&requiressl=yes&cnr=14&itag=22&lmt=1462155256119709&id=o
-ALWAEzCsotwnjDLqcTiEfBV3aIpHeeL83EzkEUoe97Eb&dur=67.012&source=youtube&key=yt6&
mm=31&mn=sn-h557snel&ei=gHSSV4OnKoL3oQOaw6mYBA&ms=au&mt=1469215475&mv=m&pl=24&si
gnature=AA6A6CC13B29458EB84A65169906711EE8ECCF5B.8098ACA143FFC37D381AA39C1A52595
0CDFCE361&fexp=9406174%2C9416891%2C9422596%2C9427767%2C9428398%2C9431012%2C94327
19%2C9433096%2C9433223%2C9433946%2C9435526%2C9435876%2C9437066%2C9437553%2C94377
42%2C9438662%2C9439581%2C9439652%2C9440880%2C9442425&sver=3&sparams=cnr%2Cdur%2C
ei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh
%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=Lt3kEU0tmsU&mime=vid
eo%2Fmp4&nh=IgpwcjAyLm1hYTAzKgkxMjcuMC4wLjE&ipbits=0&ratebypass=yes&initcwndbps=
410000&expire=1469237472'
[download] Kabali Tamil Movie _ Official Teaser _ Rajinikanth _ Radhika Apte _ P
a Ranjith-9mdJV5-eias.mp4 has already been downloaded
[download] 100% of 10.98MiB

**Comment by yan12125** [comment]
Most likely this is due to unstable network. Feel free to open a new issue if you can reproduce it reliably.
