### ISSUE TITLE
CBS hls content no proxy needed

### ISSUE THREAD

**Issue by spookyahell** [rg3/youtube-dl#10146]
## Please follow the guide _below_
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.07.22_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.22**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### Description of your _issue_, suggested solution and other information

Okay, now here's the thing: CBS needs to know that we are in the United States to get access to their video content. So when you are not in US, you can use a proxy in youtube-dl. That's all nice, but when passing the OnceURL link to ffmpeg it seems to pass it with the proxy even though the actual video content (and with 1hour-video that can be a lot of data) it isn't neccesary to use a proxy. Fetching content via proxy can be slow and annoying if ffmpeg doesn't catch all parts.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by spookyahell** [comment]
Basicly any URL from CBS, for example: http://www.cbs.com/shows/zoo/video/D33076BF-B427-6A87-EC52-A26D3E01F3E1/zoo-collision-point/

**Comment by remitamine** [comment]
will be supported in the next version using `--geo-verification-proxy` option.
