### ISSUE TITLE
Support for coursera.org and edx.org

### ISSUE THREAD

**Issue by Ayman97** [rg3/youtube-dl#10150]

**Comment by dstftw** [comment]
Duplicate.

**Comment by fharper** [comment]
I didn't try it, but I saw https://github.com/coursera-dl/coursera-dl that would do it for coursera!

**Comment by Ayman97** [comment]
> I didn't try it, but I saw https://github.com/coursera-dl/coursera-dl that would do it for coursera!

Yes I tried it. it's awesome
