### ISSUE TITLE
Lynda download issue

### ISSUE THREAD

**Issue by lonsdaleit** [rg3/youtube-dl#10156]
during downloadind a playlist from Lynda after couple of files I got the following issue:

ERROR: Unable to download webpage: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I'd appreciate you help.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
