### ISSUE TITLE
Wait for a youtube live stream, then download it when it starts?

### ISSUE THREAD

**Issue by AndrewJDR** [rg3/youtube-dl#10154]
I'm going to be away at the time a youtube live stream is starting, and I'd like a way to start downloading it using youtube-dl as it starts. I'm not sure whether the live stream will be archived.

Is it possible to have youtube-dl check for any active live streams on a channel and start downloading the live stream(s) if it finds one? Or any other solution that someone can think of?

This is a question, not a bug report.

**Comment by dstftw** [comment]
That is not possible with youtube-dl alone. You may want to write a wrapper that will periodically run youtube-dl on live stream URL and check. Or if you know the exact time you can schedule a cron job.

**Comment by AndrewJDR** [comment]
No problem setting up a crontab, but if I don't know the live stream URL ahead of time, but I know that it will appear in a certain channel, is there any way around that that you know of?
i.e. is there a way to check for **any** active live streams on a channel and retrieve the urls to those streams?

**Comment by dstftw** [comment]
You always know the URL of live stream that is http://www.youtube.com/user/username/live or http://www.youtube.com/channel/channel_id/live.
