### ISSUE TITLE
passwords with quotes (single, double, backtick) and other special characters like "!"

### ISSUE THREAD

**Issue by SanjeevKSharma** [rg3/youtube-dl#10166]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.24**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.07.24
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

Is there a way to enter passwords with non-alphanumeric characters?  does youtube-dl use One of the ways python/perl/shell do it?

I use quotes -single, double & backticks  - this is the main question at the moment

I also use passwords with characters from the to top QWERTY row shifted (#~!@$^) - the big issue here so far is the exclamation mark which must be quoted for the shell otherwise they'll make a history entry.

**Comment by yan12125** [comment]
> the big issue here so far is the exclamation mark which must be quoted for the shell otherwise they'll make a history entry.

The solution depends on the shell you're using. It's a limitation of shells. You can omit ```-p <password>```, so that there's a password prompt:
```
youtube-dl -u <username> <video URL>
```
Or use ```.netrc``` to pass in credentials.

**Comment by midas02** [comment]
I've done some experimenting with this using Windows. What seemed to work for me, was to pass the password between double quotes. I haven't tested all possible "special characters", but it seemed to work for &, !, @, and some others.

So my fix for now:
>youtube-dl` http://url -u username -p "password"

Would be nice to get some feedback if this works for others as well.

**Comment by felagund** [comment]
Or one can escape the exclamation point with "\" - enclosing the whole password into double quotes did not work for me, it would say `bash: !ED7iW0s5: event not found` - the  "!ED7iW0s5" is the second art of the password I was trying to enter.

**Comment by rautamiekka** [comment]
You should use single quotes in shells/terminals which support them for using for raw strings (whose meanings aren't interpreted), such as Bash/Zsh/PowerShell. In Bash/Zsh "`!`" is a built-in called logical NOT but might only be interpreted when preceding a string while maybe not within or trailing a string.
