### ISSUE TITLE
Underscores instead of whitespaces in filenames.

### ISSUE THREAD

**Issue by bat999** [rg3/youtube-dl#10162]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other
```
Hi
Is there an option to replace the whitespaces in the filenames with underscores?
If not, please log this as a feature request.

To change this...
THEME FROM ITV SCHOOLS SERIES 'PICTURE BOX' - 'MANECHE' BY JACQUES LASRY-3o_NTPtW8NU.ogg
into this...
THEME_FROM_ITV_SCHOOLS_SERIES_'PICTURE_BOX'_-_'MANECHE'_BY_JACQUES_LASRY-3o_NTPtW8NU.ogg

--------------------------------------------------------------------------
```
@Xubuntu:~$ youtube-dl --version
2016.07.24
```

```
@Xubuntu:~$ youtube-dl -f 171 -v -x http://www.youtube.com/watch?v=3o_NTPtW8NU
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'171', u'-v', u'-x', u'http://www.youtube.com/watch?v=3o_NTPtW8NU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.24
[debug] Python version 2.7.6 - Linux-3.19.0-49-generic-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg git-2016-07-24-b8aaedc, ffprobe git-2016-07-24-b8aaedc, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 3o_NTPtW8NU: Downloading webpage
[youtube] 3o_NTPtW8NU: Downloading video info webpage
[youtube] 3o_NTPtW8NU: Extracting video information
[youtube] 3o_NTPtW8NU: Downloading MPD manifest
[debug] Invoking downloader on u'https://r6---sn-8pgbpohxqp5-ac5l.googlevideo.com/videoplayback?id=de8fcd4cfb56f0d5&itag=171&source=youtube&requiressl=yes&mn=sn-8pgbpohxqp5-ac5l&pcm2cms=yes&ms=au&mv=m&pl=22&mm=31&initcwndbps=2235000&ratebypass=yes&mime=audio/webm&gir=yes&clen=1443561&lmt=1401601960828101&dur=121.619&key=dg_yt0&fexp=9405984,9416891,9418778,9419451,9422596,9425078,9428398,9429263,9431012,9432067,9433096,9433223,9433946,9433997,9435526,9435692,9435772,9435876,9436591,9436618,9436847,9436982,9437066,9437552,9437742,9438313,9438662,9439580,9439652,9440150,9440369,9440880,9441911,9442424&mt=1469461815&sver=3&signature=1BA7AEA8FEC2AABDC08669A5307C9DDC93161902.570BCA8B7BEAD6A92EB6D337FE53CD5E9A784857&upn=f2qRbI98DVY&ip=81.102.161.127&ipbits=0&expire=1469483852&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,pcm2cms,ms,mv,pl,mm,initcwndbps,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: THEME FROM ITV SCHOOLS SERIES 'PICTURE BOX' - 'MANECHE' BY JACQUES LASRY-3o_NTPtW8NU.webm
[download] 100% of 1.38MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams 'file:THEME FROM ITV SCHOOLS SERIES '"'"'PICTURE BOX'"'"' - '"'"'MANECHE'"'"' BY JACQUES LASRY-3o_NTPtW8NU.webm'
[ffmpeg] Destination: THEME FROM ITV SCHOOLS SERIES 'PICTURE BOX' - 'MANECHE' BY JACQUES LASRY-3o_NTPtW8NU.ogg
[debug] ffmpeg command line: ffmpeg -y -i 'file:THEME FROM ITV SCHOOLS SERIES '"'"'PICTURE BOX'"'"' - '"'"'MANECHE'"'"' BY JACQUES LASRY-3o_NTPtW8NU.webm' -vn -acodec copy 'file:THEME FROM ITV SCHOOLS SERIES '"'"'PICTURE BOX'"'"' - '"'"'MANECHE'"'"' BY JACQUES LASRY-3o_NTPtW8NU.ogg'
Deleting original file THEME FROM ITV SCHOOLS SERIES 'PICTURE BOX' - 'MANECHE' BY JACQUES LASRY-3o_NTPtW8NU.webm (pass -k to keep)
```
--------------------------------------------------------------------------

---

**Comment by dstftw** [comment]
`--restrict-filenames`.

**Comment by bat999** [comment]
Thanks :-)
