### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by 3allas** [rg3/youtube-dl#10167]
im just wondering how could i use youtube-dl for telegram bot thats mean if i send the link to the bot will replay to me with voice message i found a bot like this before but it dosent work anymore so im trying to make my own with your help ty :)

**Comment by phihag** [comment]
youtube-dl does not do voice synthesis. However, if you send a message (say, a URL or a search term), youtube-dl will happily download a video. Have a look at the [options](https://github.com/rg3/youtube-dl/blob/master/README.md#options), in particular `-x`, `-o`, and `--default-search`.
