### ISSUE TITLE
A download issue

### ISSUE THREAD

**Issue by N1CEyk** [rg3/youtube-dl#10173]
I want to download the latest version in win7,but it always prompt the sofware is virus and canceld by win7.I don't know why

**Comment by yan12125** [comment]
2 possibilities:
1. It's a false alert. VirusTotal says it's safe: https://virustotal.com/en/file/3360d5d5610898f958a84ab085570bee9b82816981f27bb60c4753303a3331aa/analysis/
2. Your file is contaminated. Check its SHA256 checksum and the GPG signature.

**Comment by N1CEyk** [comment]
What file is it?

**Comment by yan12125** [comment]
The latest Windows binary: https://yt-dl.org/downloads/2016.07.26.2/youtube-dl.exe
