### ISSUE TITLE
[Crunchyroll] youtube-dl does not detect *all* the subtitles

### ISSUE THREAD

**Issue by SammieRULES** [rg3/youtube-dl#10172]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.26.2**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

Verbose output of command:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--skip-download', u'--list-subs', u'http://www.crunchyroll.com/naruto-shippuden/episode-463-the-no-1-most-unpredictable-ninja-696235']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.26.2
[debug] Python version 2.7.11+ - Linux-4.4.0-22-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 696235: Downloading webpage
[Crunchyroll] 696235: Downloading media info for 360p
[Crunchyroll] 696235: Downloading media info for 480p
[Crunchyroll] 696235: Downloading media info for 720p
[Crunchyroll] 696235: Downloading media info for 1080p
[Crunchyroll] 696235: Downloading media info
[Crunchyroll] 696235: Downloading subtitles for English (US)
[Crunchyroll] 696235: Downloading subtitles for العربية
[Crunchyroll] 696235: Downloading subtitles for Italiano
[Crunchyroll] 696235: Downloading subtitles for Deutsch
Available subtitles for 696235:
Language formats
deDE     ass, srt
arME     ass, srt
itIT     ass, srt
enUS     ass, srt

youtube-dl only recognizes 4 out of 7 subtitles available for this episode: http://www.crunchyroll.com/naruto-shippuden/episode-463-the-no-1-most-unpredictable-ninja-696235

screenshot of all the subtitles available: https://u.teknik.io/g4rVQ.jpg
Spanish (esLA), Spanish (esES) and Portuguese (pt) are available, yet they do not appear when running youtube-dl.

Am I doing something wrong? Thanks for your time.

**Comment by dstftw** [comment]
Not available for me.
![image](https://cloud.githubusercontent.com/assets/1908898/17179357/188712ec-5443-11e6-9748-14039d49a7eb.png)

**Comment by dstftw** [comment]
That depends on IP geolocation.
Spanish IP, 6 subtitles and 4 formats served:
```
PS C:\dev\youtube-dl\master> py -2.7 .\youtube_dl\__main__.py http://www.crunchyroll.com/naruto-shippuden/episode-463-the-no-1-most-unpredictable-ninja-696235 --list-sub --proxy 85.62.224.30:3128
[Crunchyroll] 696235: Downloading webpage
[Crunchyroll] 696235: Downloading media info for 360p
[Crunchyroll] 696235: Downloading media info for 480p
[Crunchyroll] 696235: Downloading media info for 720p
[Crunchyroll] 696235: Downloading media info for 1080p
[Crunchyroll] 696235: Downloading media info
[Crunchyroll] 696235: Downloading subtitles for English (US)
[Crunchyroll] 696235: Downloading subtitles for Español
[Crunchyroll] 696235: Downloading subtitles for Español (España)
[Crunchyroll] 696235: Downloading subtitles for العربية
[Crunchyroll] 696235: Downloading subtitles for Italiano
[Crunchyroll] 696235: Downloading subtitles for Deutsch
Available subtitles for 696235:
Language formats
esES     ass, srt
deDE     ass, srt
esLA     ass, srt
enUS     ass, srt
arME     ass, srt
itIT     ass, srt
```
Mexican IP, 7 subtitles and 4 formats served:
```
PS C:\dev\youtube-dl\master> py -2.7 .\youtube_dl\__main__.py http://www.crunchyroll.com/naruto-shippuden/episode-463-the-no-1-most-unpredictable-ninja-696235 --list-sub  --proxy 200.76.251.166:3128
[Crunchyroll] 696235: Downloading webpage
[Crunchyroll] 696235: Downloading media info for 360p
[Crunchyroll] 696235: Downloading media info for 480p
[Crunchyroll] 696235: Downloading media info for 720p
[Crunchyroll] 696235: Downloading media info for 1080p
[Crunchyroll] 696235: Downloading media info
[Crunchyroll] 696235: Downloading subtitles for English (US)
[Crunchyroll] 696235: Downloading subtitles for Español
[Crunchyroll] 696235: Downloading subtitles for Español (España)
[Crunchyroll] 696235: Downloading subtitles for Português (Brasil)
[Crunchyroll] 696235: Downloading subtitles for العربية
[Crunchyroll] 696235: Downloading subtitles for Italiano
[Crunchyroll] 696235: Downloading subtitles for Deutsch
Available subtitles for 696235:
Language formats
esES     ass, srt
itIT     ass, srt
esLA     ass, srt
enUS     ass, srt
deDE     ass, srt
arME     ass, srt
ptBR     ass, srt
```
US IP, 4 subtitles and 2 formats served:
```
PS C:\dev\youtube-dl\master> py -2.7 .\youtube_dl\__main__.py http://www.crunchyroll.com/naruto-shippuden/episode-463-the-no-1-most-unpredictable-ninja-696235 --list-sub --proxy 142.0.128.217:8088
[Crunchyroll] 696235: Downloading webpage
[Crunchyroll] 696235: Downloading media info for 360p
[Crunchyroll] 696235: Downloading media info for 480p
[Crunchyroll] 696235: Downloading media info
[Crunchyroll] 696235: Downloading subtitles for English (US)
[Crunchyroll] 696235: Downloading subtitles for العربية
[Crunchyroll] 696235: Downloading subtitles for Italiano
[Crunchyroll] 696235: Downloading subtitles for Deutsch
Available subtitles for 696235:
Language formats
deDE     ass, srt
arME     ass, srt
itIT     ass, srt
enUS     ass, srt
```
