### ISSUE TITLE
--output TEMPLATE missing %(codec)s

### ISSUE THREAD

**Issue by davidhedlund** [rg3/youtube-dl#10183]
youtube-dl -f 251 https://www.youtube.com/watch?v=nhNUlAudx8E -o "%(title)s.%(format_id)s.%(ext)s"

That will download the file as
> Electric Universe - Freedom.251.webm

However, "251" will cause confusion as people do not know that it is "Opus". I would like it add the actual codec like this:
> Electric Universe - Freedom.opus.webm

How do I do that?

**Comment by phihag** [comment]
Use the [`-o` option to set an output template](https://github.com/rg3/youtube-dl/blob/master/README.md#output-template):
```
$ youtube-dl -f 251 nhNUlAudx8E -o "%(title)s-%(id)s.%(acodec)s.%(ext)s" --get-filename
Electric Universe - Freedom-nhNUlAudx8E.opus.webm
```

**Comment by davidhedlund** [comment]
@phihag Thank you.

**Comment by davidhedlund** [comment]
@phihag Why do

> youtube-dl -x -f 251 nhNUlAudx8E -o "%(title)s-%(id)s.%(acodec)s.%(ext)s"
> Electric Universe - Freedom-nhNUlAudx8E.mp3

rather than 
> Electric Universe - Freedom-nhNUlAudx8E.opus

**Comment by phihag** [comment]
The default `--audio-format` happens to be mp3 in some cases.

If you want opus, say so, and don't include `-f` at all, as you seem to have done. `-f 251` literally means: pick format 251 - nothing more, nothing less. It's better to describe the desired result and let youtube-dl figure out how to get there.

**Comment by davidhedlund** [comment]
@phihag 
> youtube-dl -F nhNUlAudx8E | grep 251
> 251          webm       audio only DASH audio  138k , opus @160k, 6.02MiB

It says webm and opus, not webm and mp3.

**Comment by phihag** [comment]
Indeed, but that's all just the video format (although this happens to be one video format that contains audio only). `--audio-format` controls the behavior of `--extract-audio` which advises youtube-dl to extract an audio file from the video file.

**Comment by yan12125** [comment]
```youtube-dl -x -f 251 nhNUlAudx8E``` works as expected for me:
```
$ youtube-dl -v -x -f 251 nhNUlAudx8E -o "%(title)s-%(id)s.%(acodec)s.%(ext)s" --get-filename
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-x', '-f', '251', 'nhNUlAudx8E', '-o', '%(title)s-%(id)s.%(acodec)s.%(ext)s', '--get-filename']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.28
[debug] Git HEAD: 0cacae2
[debug] Python version 3.5.2 - Linux-4.6.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump 2.4
[debug] Proxy map: {}
Electric Universe - Freedom-nhNUlAudx8E.opus.webm
```

**Comment by davidhedlund** [comment]
@yan12125 @phihag 

> youtube-dl -v -x -f 251 nhNUlAudx8E -o "%(title)s-%(id)s.%(acodec)s.%(ext)s"

gives me

> Electric Universe - Freedom-nhNUlAudx8E.opus.mp3
