### ISSUE TITLE
How to  get list titles grammatically 

### ISSUE THREAD

**Issue by moiseyo** [rg3/youtube-dl#10189]
### Description of your *issue*, suggested solution and other information

I'd like to use python code  to retrieve   ids and  titles .

Is there any  samples ?

**Comment by dstftw** [comment]
```python
from __future__ import unicode_literals

from youtube_dl import YoutubeDL

with YoutubeDL({}) as ydl:
    info_dict = ydl.extract_info('BaW_jenozKc', download=False)
    # info_dict['id']
    # info_dict['title']
```

**Comment by moiseyo** [comment]
Thank you , I made a little   extension :

entries= info_dict['entries']
for e in entries:
   print e['id']
   print e['title']



Moisey O

moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.
