### ISSUE TITLE
Embedding thumbnail raise errors 

### ISSUE THREAD

**Issue by gigalala** [rg3/youtube-dl#10181]
Hi,
When i added "embed thumbnail" option to my script i got error:

`thumbnail_filename = info['thumbnails'][-1]['filename'] KeyError: 'filename'`

Here is my code:

```
        ydl_opts = {
            'key':'IgnoreErrors',
            'format': 'bestaudio/best',
            'download_archive': self.songs_data,
            'outtmpl': '/'+download_path+'/'+'%(title)s.%(ext)s',
            'progress_hooks': [self.my_hook],
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '192'},
                {'key': 'EmbedThumbnail'},]}
```

Not sure if its a bug or just me doing something wrong but i tried everything

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
