### ISSUE TITLE
How merge of video and audio is done by youtube-dl

### ISSUE THREAD

**Issue by jd1008** [rg3/youtube-dl#10198]
Currently using youtube-dl version 2016.06.27

When I run youtube-dl -ctli  <url>

it often tells me that it is merging incompatible formats, and thus the output will be in mkv format.

What I want to know is the command used to invoke ffmpeg to
merge the video and the audio into an mkv file.

Thanx for your help.

**Comment by dstftw** [comment]
Use `-v`.
