### ISSUE TITLE
No Suitable InfoExtractor URL on safaribooksonline.com

### ISSUE THREAD

**Issue by danifunker** [rg3/youtube-dl#10202]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.30**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

C:\Users\USERNAME\Downloads\RHCE-Prep>youtube-dl.exe --username myuserID https://www.safaribooksonline.com/library/view/learning-path-red/978013
4664057/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--username', 'PRIVATE', 'https://www.safaribooksonl
ine.com/library/view/learning-path-red/9780134664057/', '--verbose']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.07.30
[debug] Python version 3.4.4 - Windows-2012ServerR2-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[safari:course] Downloading login form
[safari:course] Logging in as myuserID
[safari:course] Login successful
[safari:course] 9780134664057: Downloading course JSON
[download] Downloading playlist: Learning Path: Red Hat Certified Engineer (RHCE)
[safari:course] playlist Learning Path: Red Hat Certified Engineer (RHCE): Collected 223 video ids (downloading 223 of them)
[download] Downloading video 1 of 223
ERROR: no suitable InfoExtractor for URL https://www.safaribooksonline.com/api/v1/book/9780134664057/chapter/RHCE_Introduction.html
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\build\youtube_dl\__init__.py", line 422, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\build\youtube_dl\__init__.py", line 412, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\build\youtube_dl\YoutubeDL.py", line 1775, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\build\youtube_dl\YoutubeDL.py", line 693, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\build\youtube_dl\YoutubeDL.py", line 854, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\build\youtube_dl\YoutubeDL.py", line 746, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\build\youtube_dl\YoutubeDL.py", line 708, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\build\youtube_dl\YoutubeDL.py", line 556, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\bu
ild\youtube_dl\YoutubeDL.py", line 518, in trouble

C:\Users\USERNAME\Downloads\RHCE-Prep>youtube-dl -U
youtube-dl is up-to-date (2016.07.30)

---

### Description of your *issue*, suggested solution and other information

When I try to download a video course from www.safaribooksonline.com it fails with a no suitable InfoExtractor URL error. I believe this website might have gone through a big change in the last few months.

**Comment by dash17291** [comment]
@dstftw Thank you for the quick fix.

**Comment by dash17291** [comment]
Wish it also could download closed captions.

``youtube-dl --verbose --list-subs --username xxx --password xxx "https://www.safaribooksonline.com/library/view/learning-path-programming/9781491958049/part00.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--list-subs', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://www.safaribooksonline.com/library/view/learning-path-programming/9781491958049/part00.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.01
[debug] Python version 2.7.9 - Linux-4.6.0-0.bpo.1-amd64-x86_64-with-debian-8.5
[debug] exe versions: none
[debug] Proxy map: {}
[safari] Downloading login form
[safari] Logging in as cscs
[safari] Login successful
[safari] 9781491958049/part00: Downloading webpage
[safari] 9781491958049/part00: Downloading kaltura session JSON
[Kaltura] 9781491958049-video225711: Downloading webpage
[Kaltura] 0_l5ye1133: Downloading m3u8 information
[Kaltura] 0_l5ye1133: Checking mp4-56 video format URL
[Kaltura] 0_l5ye1133: Checking mp4-444 video format URL
[Kaltura] 0_l5ye1133: Checking mp4-566 video format URL
[Kaltura] 0_l5ye1133: Checking mp4-645 video format URL
[Kaltura] 0_l5ye1133: Checking mp4-1252 video format URL
[Kaltura] 0_l5ye1133: Checking -1325 video format URL
[Kaltura] 0_l5ye1133: Checking mp4-1445 video format URL
[Kaltura] 0_l5ye1133: Checking mp4-1562 video format URL
[Kaltura] 0_l5ye1133: Checking hls-meta video format URL
[Kaltura] 0_l5ye1133: Checking hls-454 video format URL
[Kaltura] 0_l5ye1133: Checking hls-579 video format URL
[Kaltura] 0_l5ye1133: Checking hls-660 video format URL
[Kaltura] 0_l5ye1133: Checking hls-1282 video format URL
[Kaltura] 0_l5ye1133: Checking hls-57 video format URL
0_l5ye1133 has no subtitles``

**Comment by yan12125** [comment]
@dash17291 Please open a new issue for closed captions.
