### ISSUE TITLE
unable to download iqiyi's licence-geo restricted videos

### ISSUE THREAD

**Issue by BreadDan** [rg3/youtube-dl#10209]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.01**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```

c:\New folder>youtube-dl.exe -v --geo-verification-proxy 218.202.111.10:80 http://www.iqiyi.com/a_19rrhadt7x.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--geo-verification-proxy', '218.202.111.10:80', 'http://www.iqiyi.com/a_19rrhadt7x.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.08.01
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] 203560001: Download playlist page 2
[download] Downloading playlist: 魔法使光之美少女
[iqiyi] playlist 魔法使光之美少女: Collected 27 video ids (downloading 27 of them)
[download] Downloading video 1 of 27
[iqiyi] temp_id: download video page
[iqiyi] 95184494fb6f1f1d53353e383cf726f3: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnq4x675r\build\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnq4x675r\build\youtube_dl\YoutubeDL.py", line 1985, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

```
### Description of your _issue_, suggested solution and other information

Right now, youtube-dl is unable to download iqiyi's licence anime, which is both geo-restricted(mainland China), and originally can not be buffed by its own client.

The proxy I used is from http://cn-proxy.com/

In fact, in May 15, youtube-dl could download the so-called "iqiyi's licence anime", they may have fixed it after that. It is my appreciation that youtube-dl helped.

**Comment by yan12125** [comment]
Looks like a problem of your proxy. Can you watch this video in browsers with ```218.202.111.10:80```?

**Comment by yan12125** [comment]
Closing as no response for a long time. Feel free to post new information if any.
