### ISSUE TITLE
Custom option --bind-address

### ISSUE THREAD

**Issue by vanilla38** [rg3/youtube-dl#1020]
Hello, since I use tortoise svn i cannot make a pull request so I share it this way:

I made a new option --bind-address which let you choose what address you will use to download with youtube-dl, of course, this address should be available for your computer.

in __init__.py @ line 152, add this:

general.add_option('--bind-address', dest='bindaddress', default=None, help='Use the specified ip address', metavar='CUSTOMIP')

Then in __init__.py @ line 350 after:  opts, args = parser.parse_args(argv)
add this:

if opts.bindaddress:
    true_socket = socket.socket
    def bound_socket(*a, **k):
        sock = true_socket(*a, **k)
        sock.bind(("%s" % opts.bindaddress, 0))
        return sock
    socket.socket = bound_socket

Finally still in __init__.py, add this @ line 590:
'bindaddress': opts.bindaddress,

Sorry for this way of posting but i'm not familiar with Git.

**Comment by phihag** [comment]
Starting from youtube-dl 2015.01.10.1, you can make use of the [`--source-address` option](https://github.com/rg3/youtube-dl/blob/master/README.md#network-options). See [our FAQ](https://yt-dl.org/update) if you need help updating.
