### ISSUE TITLE
Youtube history analysis

### ISSUE THREAD

**Issue by Jessime** [rg3/youtube-dl#10204]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.30*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.30**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v youtube-dl -u "{}" -p "{}" -o "{}" --skip-download --write-info-json -i https://www.youtube.com/feed/history
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.30
[debug] Python version 3.5.2 - Linux-3.16.0-77-generic-x86_64-with-debian-jessie-sid
[debug] exe versions: ffmpeg N-80901-gfebc862, ffprobe N-80901-gfebc862
[debug] Proxy map: {}
[youtube:history] Downloading login page
[youtube:history] Logging in
[youtube:history] Youtube History: Downloading webpage
[download] Downloading playlist: Youtube History
[youtube:history] playlist Youtube History: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: Youtube History
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

I've written a package to download and analyze a user's Youtube history. The problem is that sometimes (it's been inconsistent) 0 videos are downloaded, as shown above. The reason I've left out the username and passwords for the google account is because I don't have the passwords which are causing errors. I have access to three Google accounts and can use all of them in the program without issue. 

It appears that Google is blocking some of the requests as suspicious. Is there anyway to get around this?

I'm currently running all of these off my single laptop, which I think may be contributing to the issue, but I don't know enough about this to be certain. Finally, I realize that this might not be a problem with `youtube-dl` per-se, but I didn't know where else to ask. Thanks!

**Comment by dstftw** [comment]
Post the output with `--dump-pages` with same such behavior.

**Comment by Jessime** [comment]
Will do. I currently don't have access to any of the passwords that cause the issue, but I should be able to get one in the next day or two.

**Comment by Jessime** [comment]
[youtube_debug.txt](https://github.com/rg3/youtube-dl/files/398468/youtube_debug.txt)

Here are the results of --dump-pages. I attempted to log on from my laptop, and wasn't able to download any videos. A couple minutes later my friend (who owns the account) was able to successfully start the download.

**Comment by dstftw** [comment]
This is what YouTube ask you to do:
![image](https://cloud.githubusercontent.com/assets/1908898/17351951/245f0a38-595d-11e6-9fac-06ad2e97fb89.png)

Log in with browser and verify. Then you may need to export cookies and pass to youtube-dl.

**Comment by Jessime** [comment]
Excellent, thank you. I would have had a tough time figuring that out myself.
