### ISSUE TITLE
multiple videos at same time

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#10214]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.01**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.01
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

hi Sir
i want to ask question
is it possible to download multiple videos from playlist ?
for example i want to download lynda or udemy course but i want that its start downloading atleast 5 video lectures at same time not one by one

**Comment by dstftw** [comment]
Not possible. For parallel downloads spawn multiple youtube-dl instances.

**Comment by TRox1972** [comment]
Though it's worth nothing that a [PR allowing for parallel downloads](https://github.com/rg3/youtube-dl/pull/129) was opened some time ago.

**Comment by Hrxn** [comment]
Since I don't see the point in downloading 5 videos in parallel, and OP didn't explain the reasoning, I'd assume that you are just trying to download more than one video at all, i.e. without executing the program again.

Which you actually can do, of course:
> -a, --batch-file FILE            
>File containing URLs to download ('-' for stdin)

So, for example `youtube-dl -a FILE`.
Just put the URLs of the desired videos in FILE.
You might want to use the `-i` (or `--ignore-errors`) option as well, because youtube-dl aborts on every error as default.

**Comment by cmd64** [comment]
I writed a C# windows form. It is executes commands in textbox text. Create a new C# windows form application and add 1 button 2 textboxes. Button click event inside write below codes.

`var list = textBox1.Text.Split(new string[] { "\n" }, StringSplitOptions.RemoveEmptyEntries);

            foreach (var item in list)
            {
                Process p = new Process();
                p.StartInfo.FileName = "youtube-dl";
                p.StartInfo.UseShellExecute = false;
                p.StartInfo.Arguments = item;
                p.StartInfo.RedirectStandardOutput = true;
                p.Start();
                textBox2.AppendText(p.StandardOutput.ReadToEnd());
                textBox2.AppendText("--------------------------");
            }`
