### ISSUE TITLE
Turn the volume up or down in audio files

### ISSUE THREAD

**Issue by onlineaccount** [rg3/youtube-dl#10217]
I want to ask if there is an option/parameter for change volume audio when download a youtube video/playlist. In ffmpeg is possible to up or down the volume audio with this option:

https://trac.ffmpeg.org/wiki/How%20to%20change%20audio%20volume%20up-down%20with%20FFmpeg

With youtube-dl it is possible to do this? If you download a playlist it is useful to set a dB value for all audio files to maintain equal sound.

Many thanks for your help!

**Comment by yan12125** [comment]
There's an implementation at #8733.

**Comment by onlineaccount** [comment]
What version it is implemented that implementation?

**Comment by yan12125** [comment]
There's no official versions yet. Here's a quick start:
1. Install Python 2.6+ or 3.2+
2. Download https://github.com/phnahes/youtube-dl/archive/audio-level.zip and extract it
3. ```python ./youtube_dl/__main__.py```

**Comment by onlineaccount** [comment]
Thanks!
