### ISSUE TITLE
New regression: test_NationalGeographic

### ISSUE THREAD

**Issue by anisse** [rg3/youtube-dl#10229]
Commit 1891ea2d760a49d356a472516db40bad8309ef3c (ping @remitamine ) introduced regressions for test_NationalGeographic and test_NationalGeographic_1 .

See this build:
https://travis-ci.org/anisse/youtube-dl/jobs/149751474

```
FAIL: test_NationalGeographic_1 (test.test_download.TestDownload)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/anisse/youtube-dl/test/test_download.py", line 187, in test_template

    self.assertTrue(os.path.exists(tc_filename), msg='Missing file ' + tc_filename)

AssertionError: Missing file 3TmMv9OvGwIR.mp4
```

@dstftw

**Comment by remitamine** [comment]
it's not actually a regression as i doesn't change the code of the old extractors i only changed the names of the extractors which make your script think that there is a regression.

**Comment by anisse** [comment]
Thanks, sorry for the false positives, interpretating the results is not always easy ^^
