### ISSUE TITLE
Verbosity: File Size

### ISSUE THREAD

**Issue by newbieg** [rg3/youtube-dl#10227]
I have to say that I'm a big fan of this program, It's actually the reason that I passed calculus 1A last semester (downloading math tutoring play-lists then watching at home).

I have a pay-by-usage web connection, so I'm asking for an additional option in the simulate/verbosity area of the program. I see options to get-description, get-filename, get-format, etc. but I don't see an option to get-filesize. The only way I see to get that information is by actually starting the download of a file and stop it quickly if it looks too big. 

I'm thinking something like this command:
youtube-dl --get-filesize -f 18 youtube.com/watch/etc

Even if it is just an estimate, or if it returns the occasional error of size-not-known, it would save me quite a few precious mb's when I'm at home.

Thank you.

**Comment by dstftw** [comment]
When available file sizes are displayed in `-F` and also present in `--dump-json`.

**Comment by newbieg** [comment]
Ah.. that's embarrassing.  Yes they are, thank you for your time.
