### ISSUE TITLE
Unable to download webpage: HTTP Error 403

### ISSUE THREAD

**Issue by kidz4545** [rg3/youtube-dl#10225]
I get the following error message while trying to download: 

youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' 'http://184.173.146.34/einthusancom/cold/B2147.mp4.m3u8?st=ZuDbzye8kB64zsRdYdsLmw&e=1469384005' -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', u'http://184.173.146.34/einthusancom/cold/B2147.mp4.m3u8?st=ZuDbzye8kB64zsRdYdsLmw&e=1469384005', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.01
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1
[debug] Proxy map: {}
[generic] B2147.mp4: Requesting header
WARNING: Could not send HEAD request to http://184.173.146.34/einthusancom/cold/B2147.mp4.m3u8?st=ZuDbzye8kB64zsRdYdsLmw&e=1469384005: HTTP Error 403: Forbidden
[generic] B2147.mp4: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 394, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1985, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
This gives the same 403 error in browser. What else do you expect to see?

**Comment by kidz4545** [comment]
This doesn't give 403 error in my browser. Which region are you accessing from?

**Comment by yan12125** [comment]
Also got 403 from Taiwan, with Firefox on Linux.

**Comment by yan12125** [comment]
> This doesn't give 403 error in my browser.

**Comment by yan12125** [comment]
> This doesn't give 403 error in my browser.

By the way, this looks like a m3u8 manifest. AFAIK current browsers does not support playing m3u8 manifests directly. Which browser are you using?

**Comment by kidz4545** [comment]
I am now getting 403 as well. I was able to download couple of videos successfully last week. It is not working for some reason now. I am able to go to http://www.einthusan.com/movies/watch.php?hindimoviesonline=Baaghi+%282016%29&lang=hindi&id=2981 and play the video on the browser though.

**Comment by yan12125** [comment]
An m3u8 URL can be loaded in the web page does not indicate that it can be downloaded. For this case, it's a copyrighted movie so youtube-dl [won't support it](https://github.com/rg3/youtube-dl/blob/master/README.md#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
