### ISSUE TITLE
New regression: 5min test_no_duplicates

### ISSUE THREAD

**Issue by anisse** [rg3/youtube-dl#10228]
I'm not sure about this one, it might be a side effect of fixing the IE by delegating to AolIE, but test_no_duplicates is a new regression since commit 2396062c747ee81420dac0eac914d531ec8df910 ping @remitamine 

```
FAIL: test_no_duplicates (test.test_all_urls.TestAllURLsMatching)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/anisse/youtube-dl/test/test_all_urls.py", line 94, in test_no_duplicates

    self.assertTrue(ie.suitable(url), '%s should match URL %r' % (type(ie).__name__, url))

AssertionError: False is not true : FiveMinIE should match URL 'http://delivery.vidible.tv/aol?playList=518013791
```

See this build:
https://travis-ci.org/anisse/youtube-dl/jobs/149816265

**Comment by remitamine** [comment]
thanks for the report there was a small error in the `_VALID_URL` regex.
