### ISSUE TITLE
How to download the best video along with the best compatible audio?

### ISSUE THREAD

**Issue by Daemonster** [rg3/youtube-dl#10221]
### Purpose of the *issue*:
- [x] Question
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Feature request (request for a new functionality)
- [ ] Site support request (request for adding support for a new site)
- [ ] Other

### [How to download the best video along with the best compatible audio?](http://askubuntu.com/q/807877/161741)

I want to use a format selector that is something like **`-f bestvideo+`*****`best audio whose extension is compatible with the video extension`*** so that they don't need to be muxed into an mkv.

How to do that?

**Comment by dstftw** [comment]
You must explicitly specify which extensions to download in format selection. Read [FAQ](https://github.com/rg3/youtube-dl#format-selection-examples).
