### ISSUE TITLE
Unable to install youtube-dl

### ISSUE THREAD

**Issue by long-horse** [rg3/youtube-dl#10231]
I tried `sudo pip install --upgrade youtube-dl` and got back

> The directory '/Users/tyler/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/Users/tyler/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Requirement already up-to-date: youtube-dl in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages

but then `youtube-dl --version` tells me 

> -bash: youtube-dl: command not found

I tried without sudo but it still tells me

> Requirement already up-to-date: youtube-dl in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages

I can't figure out how to install this. I'm pretty new to python but I've gotten a few other python programs installed with pip and haven't gotten this error before.

Edit: I thought I'd try setuptools, `easy_install youtube-dl` worked and now `youtube-dl --version` returns 2016.08.01. I would still like to know why pip wouldn't install it :/

**Comment by yan12125** [comment]
Could you uninstall existing versions with ```pip uninstall youtube-dl```, reinstall it and show installed files via ```pip show -f youtube-dl```?

And, which Mac version are you using? Since El Capitan (10.11), installing youtube-dl globally does not work due to a Mac bug. See #7139 for alternative installation approaches.

**Comment by long-horse** [comment]
I seem to have fixed it. I sudo uninstalled pip and then reinstalled it and `pip install youtube-dl` worked and downloading videos works. It's installed to `/Library/Frameworks/Python.framework/Versions/2.7/bin/youtube-dl` according to `which youtube-dl`

**Comment by dstftw** [comment]
Good for you.

**Comment by aptwebapps** [comment]
FYI for anyone else, if you install Python via Macports you probably want to add something like `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin` to your PATH environment variable.
