### ISSUE TITLE
Mixcloud error 403

### ISSUE THREAD

**Issue by ratkins** [rg3/youtube-dl#10246]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl --verbose https://www.mixcloud.com/jameszabiela/james-zabiela-live-main-room-studio338-july-2016/?utm_campaign=notification_new_upload&utm_medium=email&utm_source=notification&utm_content=html
[1] 3576
[2] 3577
[3] 3578
[2]-  Done                    utm_medium=email
[3]+  Done                    utm_source=notification
$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.mixcloud.com/jameszabiela/james-zabiela-live-main-room-studio338-july-2016/?utm_campaign=notification_new_upload']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.06
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[mixcloud] jameszabiela-james-zabiela-live-main-room-studio338-july-2016: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 394, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1985, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)


[1]+  Exit 1                  youtube-dl --verbose https://www.mixcloud.com/jameszabiela/james-zabiela-live-main-room-studio338-july-2016/?utm_campaign=notification_new_upload
$
```
---
Interestingly, when I go to mixcloud.com from a browser I get a "Tick this box to prove you're not a robot" captcha, and then it redirects me to Mixcloud as normal. I've noticed this from a few sites here at home (my ISP is Vodafone cable in Berlin.) So this *may* not be a `youtube-dl` issue?

**Comment by dstftw** [comment]
* [Pass authenticated cookies](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl)
* [Pass URL correctly](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
