### ISSUE TITLE
iqiyi VIP video 

### ISSUE THREAD

**Issue by yangfan3333** [rg3/youtube-dl#10244]
Only download section

 can not download the full video

I have used  the   cookies 

youtube-dl-0806  this version 

D:\yy>youtube-dl.exe *** ***.txt  http://www.iqiyi.com/v_19rrmenh3
8.html
[iqiyi] temp_id: download video page
[iqiyi] 1d0192bf4e8a1d7f4b23575f05b5e243: Downloading JSON metadata
[download] 探魔导师          -1d0192bf4e8a1d7f4b23575f05b5e243.mp4 has already b
een downloaded
[download] 100% of 67.39MiB
WARNING: 1d0192bf4e8a1d7f4b23575f05b5e243: malformated aac bitstream. Install ff
mpeg or avconv to fix this automatically.

Although  can download VIP Video

But the video is not complete

**Comment by yan12125** [comment]
Duplicate #9839. Iqiyi VIP support has been broken for a long time.
