### ISSUE TITLE
Segmentation Fault with new OpenSSL

### ISSUE THREAD

**Issue by hymie0** [rg3/youtube-dl#10248]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.06**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ ./youtube-dl -v
zsh: segmentation fault  ./youtube-dl -v
$ ./youtube-dl
zsh: segmentation fault  ./youtube-dl
$ 
```
---

### Description of your *issue*, suggested solution and other information

I recently upgraded my version of OpenSSL from the very old 0.9.8-something to a more recent 1.0.2h.  Now I cannot run youtube-dl.  I downloaded the newest 2016-08-06 on a different computer running OpenSSL 1.0.2a and it works perfectly on that machine.  Both machines should be configured roughly the same (but probably not exactly the same).  

If I reinstall the old OpenSSL 0.9.8 libraries, then youtube-dl works correctly.  But I don't want the old version conflicting with any other software that I have.

When I uninstall both 0.9.8 and 1.0.2 , I get this error:

```
newlaptop-pts/0:~% youtube-dl
Traceback (most recent call last):
  File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "youtube-dl/__main__.py", line 16, in <module>
  File "youtube-dl/youtube_dl/__init__.py", line 15, in <module>
  File "youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "youtube-dl/youtube_dl/downloader/__init__.py", line 3, in <module>
  File "youtube-dl/youtube_dl/downloader/common.py", line 8, in <module>
  File "youtube-dl/youtube_dl/compat.py", line 25, in <module>
  File "/usr/lib/python2.6/urllib2.py", line 91, in <module>
    import hashlib
  File "/usr/lib/python2.6/hashlib.py", line 136, in <module>
    md5 = __get_builtin_constructor('md5')
  File "/usr/lib/python2.6/hashlib.py", line 63, in __get_builtin_constructor
    import _md5
ImportError: No module named _md5
```

Perhaps I compiled OpenSSL incorrectly, but nothing else has complained.

**Comment by yan12125** [comment]
Which OS are you using? I guess you need to recompile Python after upgrading OpenSSL.

**Comment by hymie0** [comment]
I'm sorry.  Slackware 13 / Linux 3.18.25 .  I will try to upgrade Python...

**Comment by hymie0** [comment]
Resolved.  Thanks for the tip.
