### ISSUE TITLE
feature request add support for http://you.rtl2.de/

### ISSUE THREAD

**Issue by timo13235** [rg3/youtube-dl#10257]
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.08.07_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.07**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://you.rtl2.de/youplayer/index.html?vid=7980
- Single video: http://you.rtl2.de/video/115/7982/dragon-ball/65-der-sechste-dragonball
- Playlist: http://you.rtl2.de/video/115/7981/dragon-ball
- Playlist: http://you.rtl2.de/videos/115/dragon-ball

---
### Description of your _issue_, suggested solution and other information

Hi, hope ive done this new questionnaire correct... i wasnt sure if i should include it or just check it for my own.

I have found out how i can download videos from http://you.rtl2.de/ on which are manny full episodes. First of all i have to look for the iframe leading to a page like: http://you.rtl2.de/youplayer/index.html?vid=7980 , then i have to open that page in opera or crome and open the development tool with the network view, switch to persistant mode, disable cache (maybe works also with) and click to all given parts (Teil 1 and Teil 2 in german) for all parts in the network view under category xhr a file beginning with master.m3u8 will appere. This file can be saved (to its on directory because of youtube-dl wount download files with the same name again and they are all the same), all lines but the lines with the best quality listed can be deletet and then the content can be retrived using:

 youtube-dl -a master3.m3u8 

it would be grate if you could add this page to automatisate theese steps.

thanks in advacne

**Comment by remitamine** [comment]
i found a problem here, the site used CryptoJS To decrypt the url, but trying to do the same thing using `aes_cbc_decrypt` does not work.
this is the code for decryption(after deobfuscation):
```js
window.youStreamDecrypt = function(b) {
    var a = new window.ysd;
    if (a.inArray(a.tld, ["rtl2.de", "rtl2apps.de", "umwerk.me"])) {
        a = CryptoJS.enc.Base64.parse("6VfkLjwquBrStpLzQ9PvTBsDKrtiSMAD/2/C8iiqqiE=");
        b = CryptoJS.enc.Utf8.stringify(CryptoJS.enc.Base64.parse(b));
        streamUrlSplit = b.split(":");
        b = streamUrlSplit[0];
        var c = CryptoJS.enc.Base64.parse(streamUrlSplit[1]),
            a = CryptoJS.AES.decrypt(b, a, {
                iv: c
            });
        return b = CryptoJS.enc.Utf8.stringify(a)
    }
    console.log(a.msg)
};
```
