### ISSUE TITLE
BBC Linux 720P  HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by jiangjiangflies** [rg3/youtube-dl#10250]
youtube-dl -f iplayer_stb_streaming_hd_akamai_hls_open-2388 http://www.bbc.co.uk/iplayer/episode/b07ncx07/bbc-weekend-news-07082016

2.5% of ~1014.28MiB at 44.82MiB/s ETA 00:55ERROR: unable to download video data: HTTP Error 404: Not Found

**Comment by dstftw** [comment]
Duplicate of #10247.
