### ISSUE TITLE
How do i actually download a video playlist?

### ISSUE THREAD

**Issue by devky** [rg3/youtube-dl#10264]
I cant find it anywhere in the documentation. Also the windows.exe opens then closes.

**Comment by phihag** [comment]
I'm not sure what windows.exe is - do you mean the terminal window? youtube-dl is a command-line application; start a terminal window and type

    youtube-dl https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re

in there. Of course, replace the playlist URL with the one you actually want to download.
