### ISSUE TITLE
Fix line endings handling for downloaded web pages

### ISSUE THREAD

**Issue by lkho** [rg3/youtube-dl#10268]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

This error is found while trying to download a subtitle from http://d2anahhhmp1ffz.cloudfront.net/1828211116/0de60692c14fea8784203ca9f696a6be874beb52, format: SRT, encoding: utf-8, line ending: CRLF. the first 70 bytes of the response is
`b'\xef\xbb\xbf1\r\n00:00:20,173 --> 00:00:21,303\r\n(Episode 1)\r\n\r\n2\r\n00:00:50,559 --'`

However the written subtitle file has all '\r\n' replaced to '\r\r\n', which breaks the SRT format and caused some players not rendering the correct subtitle lines.

#### Suggested solution

fix the decoding of downloaded webpage content with io streams instead of bytes.decode(), so python will handle the normalization of line endings, at
`C:\Users\Me\git\youtube-dl\youtube_dl\extractor\common.py: def _webpage_read_content()`

**Comment by yan12125** [comment]
Which URL are you trying to downloading?

**Comment by lkho** [comment]
I was downloading `https://www.viu.com/ott/hk/zh-hk/vod/16061/`, with a custom extractor (https://github.com/rg3/youtube-dl/pull/8131) not built in the current release.

**Comment by yan12125** [comment]
Fixed as  #10269 merged. Thanks!
