### ISSUE TITLE
Lynda.com account credentials - ERROR: Unable to login: The username or password is invalid.

### ISSUE THREAD

**Issue by meetbryce** [rg3/youtube-dl#10263]
Was receiving error:

`ERROR: Unable to login: The username or password is invalid.`

After a whole lot of research, I realised that my password had characters that needed to be escaped - I just added a `\` before the special characters in my password. 

nb: posting for others in the same situation.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
