### ISSUE TITLE
New regression: sohu

### ISSUE THREAD

**Issue by anisse** [rg3/youtube-dl#10260]
test_Sohu_3 is a new regression since b2bd968f4b6795ffe3fc2d923cc73171687c2980 on python 2.7. 

See this build:
https://travis-ci.org/anisse/youtube-dl/jobs/150464166

Test tends to be unreliable, but might fail on python2.6 as well:
https://travis-ci.org/anisse/youtube-dl/jobs/150464158
Or Python 3.3:
https://travis-ci.org/anisse/youtube-dl/jobs/150464186

**Comment by anisse** [comment]
Ping @yan12125

**Comment by yan12125** [comment]
Thanks for the report. Kuwo is unrelated to Sohu. Anyway I've updated it.
