### ISSUE TITLE
http://v.qq.com/x/cover/9p2fomrafyui6l4/a0021co0rqf.html

### ISSUE THREAD

**Issue by dainixiao** [rg3/youtube-dl#10276]
[generic] a0021co0rqf: Requesting header
msgWarning-->Falling back on generic information extractor.
[generic] a0021co0rqf: Downloading webpage
[generic] a0021co0rqf: Extracting information
msgWarning-->unable to extract JSON-LD;

**Comment by yan12125** [comment]
Duplicate of #6831. QQ videos are not supported yet.
