### ISSUE TITLE
Error launching "youtube-dl.exe" due missing file "msvcr100.dll" on Windows XP SP3 into VMware

### ISSUE THREAD

**Issue by Baqan** [rg3/youtube-dl#10278]
Hi,

When I try to launch the latest version 2016.08.10 of youtube-dl.exe in my clean copy of Windows XP SP3 (with original CD and genuine license key) running into my VMWare 12.1.1 I get a error message that missing msvcr100.dll and the application aborts. Its the unique application which is causing  error when is launched. So my question is if recent versions of youtube-dl.exe depends of this DLL file to run it, because in Windows XP SP3 is not included. Please see the following snapshot:

http://i.imgur.com/8QYmX3G.png

Any help is welcome. Thanks in advance.

**Comment by dstftw** [comment]
Read http://rg3.github.io/youtube-dl/download.html.

**Comment by Baqan** [comment]
@dstftw: Thanks!!!

**Comment by Jochen-sys** [comment]
Unfortunately it does not work for me anyway. I still get the error, that the mscvr100.dll can't be found.

**Comment by turbosmurfen** [comment]
> 
> 
> Unfortunately it does not work for me anyway. I still get the error, that the mscvr100.dll can't be found.

Have you tried to uninstall 2015-2019 Visual C++ pack before you install 2010 Visual C++?
Because this works for me. I had the same error and was mad. But I remember that Visual C++ need to be installed from beginning to end.

**Comment by fredskis** [comment]
> Some typical MSWin weirdness that I'm not aware of will explain why an `x86` app installs a `dll` to what seems to be an `x64` directory. (And vice versa if you happen to also install the `x64` Redistributable.)

To clarify, it's not weirdness. 
The regular paths (system32, Program Files, etc) all lead to paths for 64 bit binaries on a 64 bit Windows install. If a 32 bit application tries to access these, they won't work as they need a 32 bit binary, hence, for 32 bit processes Windows redirects the paths (to SysWOW64, Program Files (x86) etc). The idea is that if you simply recompile your application as a 64 bit one, you don't have to make any pathing changes and everything just works, and legacy applications all just work on a 64 bit OS. 
Youtube-dl.exe is a 32 bit application so it needs the 32 bit MSVCR100.dll file, not the 64 bit one. Regardless of whether you use 32 bit or 64 bit Windows, you need to install the appropriate DLL for the application you intend to run - in this case, 32 bit (x86) version.
