### ISSUE TITLE
Unable to download from vidbom

### ISSUE THREAD

**Issue by Animis09** [rg3/youtube-dl#10272]
youtube-dl -f SD http://vidbom.com/h74thtl5o5ln.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'SD', u'http://vidbom.com/h74thtl5o5ln.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.07
[debug] Proxy map: {}
[generic] h74thtl5o5ln: Requesting header
WARNING: Falling back on generic information extractor.
[generic] h74thtl5o5ln: Downloading webpage
[generic] h74thtl5o5ln: Extracting information
WARNING: unable to extract JSON-LD; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[generic] 6jmn3cjytyazsalriwxad6vxaykrru7v6yn5k6mnkexau4sa7vcvzncl5qxa: Downloading m3u8 information
[debug] Invoking downloader on u'http://5.196.85.27/6jmn3cjytyazsalriwxad6vxaykrru7v6yn5k6mnkexau4sa7vcvzncl5qxa/h74thtl5o5ln.m3u8'
[download] Destination: Watch ZX14 Central Intelligence 2016 1080p HDRip Cima4U mkv-6jmn3cjytyazsalriwxad6vxaykrru7v6yn5k6mnkexau4sa7vcvzncl5qxa.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,_;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
' -i http://5.196.85.27/6jmn3cjytyazsalriwxad6vxaykrru7v6yn5k6mnkexau4sa7vcvzncl5qxa/h74thtl5o5ln.m3u8 -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Watch ZX14 Central Intelligence 2016 1080p HDRip Cima4U mkv-6jmn3cjytyazsalriwxad6vxaykrru7v6yn5k6mnkexau4sa7vcvzncl5qxa.mp4.part'
ffmpeg 
  configuration: --enable-gpl --enable-nonfree --enable-postproc --enable-pthreads --enable-x11grab --enable-swscale --enable-version3 --enable-shared --disable-yasm --enable-filter=movie --enable-frei0r --enable-libdc1394 --enable-libfaac --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-libfreetype --enable-libvorbis --enable-libgsm --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libvpx --enable-libvo-amrwbenc --enable-libvo-aacenc --enable-libaacplus --enable-libxavs --enable-bzlib --enable-openssl --enable-gnutls --enable-openal --enable-libv4l2 --enable-libpulse --enable-libmodplug --enable-libass --enable-libcdio --enable-vdpau --enable-libbluray
  libavutil      52. 66.100 / 52. 66.100
  libavcodec     55. 52.102 / 55. 52.102
  libavformat    55. 33.100 / 55. 33.100
  libavdevice    55. 10.100 / 55. 10.100
  libavfilter     4.  2.100 /  4.  2.100
  libswscale      2.  5.102 /  2.  5.102
  libswresample   0. 18.100 /  0. 18.100
  libpostproc    52.  3.100 / 52.  3.100
[http @ 0x3b057e0] HTTP error 404 Not Found
http://5.196.85.27/6jmn3cjytyazsalriwxad6vxaykrru7v6yn5k6mnkexau4sa7vcvzncl5qxa/h74thtl5o5ln.m3u8: Input/output error
Conversion failed!

ERROR: ffmpeg exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/**init**.py", line 422, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 412, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1775, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 693, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 739, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1421, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1683, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1625, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/external.py", line 43, in real_download
    self.get_basename(), retval))
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 161, in report_error
    self.ydl.report_error(_args, *_kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 556, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 518, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

Thank you for your help.

**Comment by yan12125** [comment]
This video is a copyrighted product of Warner Bros. youtube-dl won't support copyright infringing websites. Do you have another example?
