### ISSUE TITLE
external downloader

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#10274]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.07**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.07
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

hi Sir
i need help
i generate download links of some vidoes and i can download videos via internet download manager by import these links which i generate. but now i want to download via youtube-dl i have all list of videos links which i generate but i dont know how can i import these links in youtube-dl
i know only have command of --external-downloader
but can you tell me full command how can i import generated links and it will download alls

thanks

**Comment by dstftw** [comment]
`-a file_with_links.txt`.

**Comment by jaan143** [comment]
plz check i got this error
PS C:\Users\vicky\downloads> youtube-dl --verbose -a links.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-a', 'links.txt']
[debug] Batch file urls: ['h\x00t\x00t\x00p\x00s\x00:\x00/\x00/\x00r\x001\x00-\x00-\x00-\x00s\x00n\x00-\x002\x00u\x00j\x00a\x00-\x00a\x00i\x00x\x00d\x00.\x00g\x00o\x00o\x00g\x00l\x00e\x00v\x00i\x00d\x00e\x00o\x00.\x00c\x00o\x00m\x00/\x00v\x00i\x00d\x00e\x00o\x00p\x00l\x00a\x00y\x00b\x00a\x00c\x00k\x00?\x00k\x00e\x00y\x00=\x00y\x00t\x006\x00&\x00f\x00e\x00x\x00p\x00=\x009\x004\x001\x008\x007\x007\x008\x00%\x002\x00C\x009\x004\x001\x009\x004\x005\x002\x00%\x002\x00C\x009\x004\x002\x002\x005\x009\x006\x00%\x002\x00C\x009\x004\x002\x008\x003\x009\x008\x00%\x002\x00C\x009\x004\x003\x001\x000\x001\x002\x00%\x002\x00C\x009\x004\x003\x003\x000\x009\x006\x00%\x002\x00C\x009\x004\x003\x003\x002\x002\x003\x00%\x002\x00C\x009\x004\x003\x003\x009\x004\x006\x00%\x002\x00C\x009\x004\x003\x005\x000\x003\x006\x00%\x002\x00C\x009\x004\x003\x005\x005\x002\x006\x00%\x002\x00C\x009\x004\x003\x005\x006\x006\x007\x00%\x002\x00C\x009\x004\x003\x007\x005\x005\x002\x00%\x002\x00C\x009\x004\x003\x008\x003\x002\x007\x00%\x002\x00C\x009\x004\x003\x008\x006\x006\x002\x00%\x002\x00C\x009\x004\x003\x008\x007\x006\x006\x00%\x002\x00C\x009\x004\x003\x008\x008\x000\x005\x00%\x002\x00C\x009\x004\x003\x009\x003\x005\x007\x00%\x002\x00C\x009\x004\x003\x009\x005\x008\x000\x00%\x002\x00C\x009\x004\x004\x000\x001\x005\x003\x00%\x002\x00C\x009\x004\x004\x000\x002\x001\x006\x00%\x002\x00C\x009\x004\x004\x000\x003\x008\x008\x00%\x002\x00C\x009\x004\x004\x000\x007\x003\x007\x00%\x002\x00C\x009\x004\x004\x001\x001\x005\x000\x00%\x002\x00C\x009\x004\x004\x002\x004\x002\x004\x00%\x002\x00C\x009\x004\x004\x002\x005\x000\x002\x00%\x002\x00C\x009\x004\x004\x003\x000\x004\x009\x00%\x002\x00C\x009\x004\x004\x003\x004\x000\x003\x00%\x002\x00C\x009\x004\x004\x003\x005\x005\x000\x00&\x00m\x00n\x00=\x00s\x00n\x00-\x002\x00u\x00j\x00a\x00-\x00a\x00i\x00x\x00d\x00&\x00m\x00m\x00=\x003\x001\x00&\x00m\x00s\x00=\x00a\x00u\x00&\x00e\x00i\x00=\x00B\x00f\x00q\x00p\x00V\x005\x00K\x008\x00J\x00s\x00j\x00M\x00i\x00w\x00b\x00z\x006\x00Y\x00m\x00Q\x00B\x00w\x00&\x00m\x00v\x00=\x00m\x00&\x00p\x00l\x00=\x001\x008\x00&\x00m\x00t\x00=\x001\x004\x007\x000\x007\x005\x006\x009\x004\x009\x00&\x00s\x00i\x00g\x00n\x00a\x00t\x00u\x00r\x00e\x00=\x007\x006\x005\x007\x008\x00A\x005\x000\x007\x00F\x000\x003\x00E\x000\x000\x00F\x001\x001\x00F\x001\x00B\x007\x009\x003\x00E\x002\x000\x00A\x00B\x006\x009\x00F\x004\x002\x001\x008\x005\x006\x00D\x006\x00.\x003\x009\x00D\x001\x003\x007\x005\x00C\x00E\x00E\x00B\x003\x00C\x00E\x009\x004\x00B\x001\x00F\x002\x00E\x00B\x00A\x008\x009\x008\x003\x009\x00E\x008\x00E\x000\x00F\x007\x00C\x006\x001\x007\x008\x00A\x00&\x00i\x00p\x00=\x001\x001\x009\x00.\x001\x005\x005\x00.\x004\x00.\x006\x006\x00&\x00r\x00e\x00q\x00u\x00i\x00r\x00e\x00s\x00s\x00l\x00=\x00y\x00e\x00s\x00&\x00s\x00p\x00a\x00r\x00a\x00m\x00s\x00=\x00d\x00u\x00r\x00%\x002\x00C\x00e\x00i\x00%\x002\x00C\x00i\x00d\x00%\x002\x00C\x00i\x00n\x00i\x00t\x00c\x00w\x00n\x00d\x00b\x00p\x00s\x00%\x002\x00C\x00i\x00p\x00%\x002\x00C\x00i\x00p\x00b\x00i\x00t\x00s\x00%\x002\x00C\x00i\x00t\x00a\x00g\x00%\x002\x00C\x00l\x00m\x00t\x00%\x002\x00C\x00m\x00i\x00m\x00e\x00%\x002\x00C\x00m\x00m\x00%\x002\x00C\x00m\x00n\x00%\x002\x00C\x00m\x00s\x00%\x002\x00C\x00m\x00v\x00%\x002\x00C\x00p\x00l\x00%\x002\x00C\x00r\x00a\x00t\x00e\x00b\x00y\x00p\x00a\x00s\x00s\x00%\x002\x00C\x00r\x00e\x00q\x00u\x00i\x00r\x00e\x00s\x00s\x00l\x00%\x002\x00C\x00s\x00o\x00u\x00r\x00c\x00e\x00%\x002\x00C\x00u\x00p\x00n\x00%\x002\x00C\x00e\x00x\x00p\x00i\x00r\x00e\x00&\x00i\x00t\x00a\x00g\x00=\x004\x003\x00&\x00l\x00m\x00t\x00=\x001\x004\x002\x008\x007\x002\x008\x003\x006\x003\x009\x005\x005\x009\x001\x005\x00&\x00i\x00d\x00=\x00o\x00-\x00A\x00D\x00o\x00I\x006\x00V\x00Z\x00d\x00y\x00U\x00P\x004\x00I\x00V\x00t\x00r\x00e\x000\x00b\x007\x00o\x00D\x00r\x00I\x00f\x00c\x00A\x00a\x006\x00u\x002\x00D\x00p\x00Q\x00M\x00v\x00g\x00e\x007\x00q\x00h\x009\x00f\x00y\x00&\x00d\x00u\x00r\x00=\x000\x00.\x000\x000\x000\x00&\x00s\x00o\x00u\x00r\x00c\x00e\x00=\x00y\x00o\x00u\x00t\x00u\x00b\x00e\x00&\x00u\x00p\x00n\x00=\x00U\x00t\x006\x00w\x00t\x00Y\x00M\x00m\x009\x00f\x00Q\x00&\x00m\x00i\x00m\x00e\x00=\x00v\x00i\x00d\x00e\x00o\x00%\x002\x00F\x00w\x00e\x00b\x00m\x00&\x00i\x00p\x00b\x00i\x00t\x00s\x00=\x000\x00&\x00r\x00a\x00t\x00e\x00b\x00y\x00p\x00a\x00s\x00s\x00=\x00y\x00e\x00s\x00&\x00i\x00n\x00i\x00t\x00c\x00w\x00n\x00d\x00b\x00p\x00s\x00=\x001\x002\x008\x007\x005\x000\x00&\x00e\x00x\x00p\x00i\x00r\x00e\x00=\x001\x004\x007\x000\x007\x007\x008\x009\x008\x001\x00&\x00s\x00v\x00e\x00r\x00=\x003\x00', '\x00', '\x00']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.07.16
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[generic]  v i d e o p l a y b a c k ? k e y = y t 6 & f e x p = 9 4 1 8 7 7 8 % 2 C 9 4 1 9 4 5 2 % 2 C 9 4 2 2 5 9 6 % 2 C 9 4 2 8 3 9 8 % 2 C 9 4 3 1 0 1 2 % 2 C 9 4 3 3 0 9 6 % 2 C 9 4 3 3 2 2 3 % 2 C 9 4 3 3 9 4 6 % 2 C 9 4 3 5 0 3 6 % 2 C 9 4 3 5 5 2 6 % 2 C 9 4 3 5 6 6 7 % 2 C 9 4 3 7 5 5 2 % 2 C 9 4 3 8 3 2 7 % 2 C 9 4 3 8 6 6 2 % 2 C 9 4 3 8 7 6 6 % 2 C 9 4 3 8 8 0 5 % 2 C 9 4 3 9 3 5 7 % 2 C 9 4 3 9 5 8 0 % 2 C 9 4 4 0 1 5 3 % 2 C 9 4 4 0 2 1 6 % 2 C 9 4 4 0 3 8 8 % 2 C 9 4 4 0 7 3 7 % 2 C 9 4 4 1 1 5 0 % 2 C 9 4 4 2 4 2 4 % 2 C 9 4 4 2 5 0 2 % 2 C 9 4 4 3 0 4 9 % 2 C 9 4 4 3 4 0 3 % 2 C 9 4 4 3 5 5 0 & m n = s n - 2 u j a - a i x d & m m = 3 1 & m s = a u & e i = B f q p V 5 K 8 J s j M i w b z 6 Y m Q B w & m v = m & p l = 1 8 & m t = 1 4 7 0 7 5 6 9 4 9 & s i g n a t u r e = 7 6 5 7 8 A 5 0 7 F 0 3 E 0 0 F 1 1 F 1 B 7 9 3 E 2 0 A B 6 9 F 4 2 1 8 5 6 D 6 . 3 9 D 1 3 7 5 C E E B 3 C E 9 4 B 1 F 2 E B A 8 9 8 3 9 E 8 E 0 F 7 C 6 1 7 8 A & i p = 1 1 9 . 1 5 5 . 4 . 6 6 & r e q u i r e s s l = y e s & s p a r a m s = d u r % 2 C e i % 2 C i d % 2 C i n i t c w n d b p s % 2 C i p % 2 C i p b i t s % 2 C i t a g % 2 C l m t % 2 C m i m e % 2 C m m % 2 C m n % 2 C m s % 2 C m v % 2 C p l % 2 C r a t e b y p a s s % 2 C r e q u i r e s s l % 2 C s o u r c e % 2 C u p n % 2 C e x p i r e & i t a g = 4 3 & l m t = 1 4 2 8 7 2 8 3 6 3 9 5 5 9 1 5 & i d = o - A D o I 6 V Z d y U P 4 I V t r e 0 b 7 o D r I f c A a 6 u 2 D p Q M v g e 7 q h 9 f y & d u r = 0 : Requesting header
WARNING: Could not send HEAD request to http://h t t p s : / / r 1 - - - s n - 2 u j a - a i x d . g o o g l e v i d e o . c o m / v i d e o p l a y b a c k ? k e y = y t 6 & f e x p = 9 4 1 8 7 7 8 % 2 C 9 4 1 9 4 5 2 % 2 C 9 4 2 2 5 9 6 % 2 C 9 4 2 8 3 9 8 % 2 C 9 4 3 1 0 1 2 % 2 C 9 4 3 3 0 9 6 % 2 C 9 4 3 3 2 2 3 % 2 C 9 4 3 3 9 4 6 % 2 C 9 4 3 5 0 3 6 % 2 C 9 4 3 5 5 2 6 % 2 C 9 4 3 5 6 6 7 % 2 C 9 4 3 7 5 5 2 % 2 C 9 4 3 8 3 2 7 % 2 C 9 4 3 8 6 6 2 % 2 C 9 4 3 8 7 6 6 % 2 C 9 4 3 8 8 0 5 % 2 C 9 4 3 9 3 5 7 % 2 C 9 4 3 9 5 8 0 % 2 C 9 4 4 0 1 5 3 % 2 C 9 4 4 0 2 1 6 % 2 C 9 4 4 0 3 8 8 % 2 C 9 4 4 0 7 3 7 % 2 C 9 4 4 1 1 5 0 % 2 C 9 4 4 2 4 2 4 % 2 C 9 4 4 2 5 0 2 % 2 C 9 4 4 3 0 4 9 % 2 C 9 4 4 3 4 0 3 % 2 C 9 4 4 3 5 5 0 & m n = s n - 2 u j a - a i x d & m m = 3 1 & m s = a u & e i = B f q p V 5 K 8 J s j M i w b z 6 Y m Q B w & m v = m & p l = 1 8 & m t = 1 4 7 0 7 5 6 9 4 9 & s i g n a t u r e = 7 6 5 7 8 A 5 0 7 F 0 3 E 0 0 F 1 1 F 1 B 7 9 3 E 2 0 A B 6 9 F 4 2 1 8 5 6 D 6 . 3 9 D 1 3 7 5 C E E B 3 C E 9 4 B 1 F 2 E B A 8 9 8 3 9 E 8 E 0 F 7 C 6 1 7 8 A & i p = 1 1 9 . 1 5 5 . 4 . 6 6 & r e q u i r e s s l = y e s & s p a r a m s = d u r % 2 C e i % 2 C i d % 2 C i n i t c w n d b p s % 2 C i p % 2 C i p b i t s % 2 C i t a g % 2 C l m t % 2 C m i m e % 2 C m m % 2 C m n % 2 C m s % 2 C m v % 2 C p l % 2 C r a t e b y p a s s % 2 C r e q u i r e s s l % 2 C s o u r c e % 2 C u p n % 2 C e x p i r e & i t a g = 4 3 & l m t = 1 4 2 8 7 2 8 3 6 3 9 5 5 9 1 5 & i d = o - A D o I 6 V Z d y U P 4 I V t r e 0 b 7 o D r I f c A a 6 u 2 D p Q M v g e 7 q h 9 f y & d u r = 0 . 0 0 0 & s o u r c e = y o u t u b e & u p n = U t 6 w t Y M m 9 f Q & m i m e = v i d e o % 2 F w e b m & i p b i t s = 0 & r a t e b y p a s s = y e s & i n i t c w n d b p s = 1 2 8 7 5 0 & e x p i r e = 1 4 7 0 7 7 8 9 8 1 & s v e r = 3 : nonnumeric port: ' '
[generic]  v i d e o p l a y b a c k ? k e y = y t 6 & f e x p = 9 4 1 8 7 7 8 % 2 C 9 4 1 9 4 5 2 % 2 C 9 4 2 2 5 9 6 % 2 C 9 4 2 8 3 9 8 % 2 C 9 4 3 1 0 1 2 % 2 C 9 4 3 3 0 9 6 % 2 C 9 4 3 3 2 2 3 % 2 C 9 4 3 3 9 4 6 % 2 C 9 4 3 5 0 3 6 % 2 C 9 4 3 5 5 2 6 % 2 C 9 4 3 5 6 6 7 % 2 C 9 4 3 7 5 5 2 % 2 C 9 4 3 8 3 2 7 % 2 C 9 4 3 8 6 6 2 % 2 C 9 4 3 8 7 6 6 % 2 C 9 4 3 8 8 0 5 % 2 C 9 4 3 9 3 5 7 % 2 C 9 4 3 9 5 8 0 % 2 C 9 4 4 0 1 5 3 % 2 C 9 4 4 0 2 1 6 % 2 C 9 4 4 0 3 8 8 % 2 C 9 4 4 0 7 3 7 % 2 C 9 4 4 1 1 5 0 % 2 C 9 4 4 2 4 2 4 % 2 C 9 4 4 2 5 0 2 % 2 C 9 4 4 3 0 4 9 % 2 C 9 4 4 3 4 0 3 % 2 C 9 4 4 3 5 5 0 & m n = s n - 2 u j a - a i x d & m m = 3 1 & m s = a u & e i = B f q p V 5 K 8 J s j M i w b z 6 Y m Q B w & m v = m & p l = 1 8 & m t = 1 4 7 0 7 5 6 9 4 9 & s i g n a t u r e = 7 6 5 7 8 A 5 0 7 F 0 3 E 0 0 F 1 1 F 1 B 7 9 3 E 2 0 A B 6 9 F 4 2 1 8 5 6 D 6 . 3 9 D 1 3 7 5 C E E B 3 C E 9 4 B 1 F 2 E B A 8 9 8 3 9 E 8 E 0 F 7 C 6 1 7 8 A & i p = 1 1 9 . 1 5 5 . 4 . 6 6 & r e q u i r e s s l = y e s & s p a r a m s = d u r % 2 C e i % 2 C i d % 2 C i n i t c w n d b p s % 2 C i p % 2 C i p b i t s % 2 C i t a g % 2 C l m t % 2 C m i m e % 2 C m m % 2 C m n % 2 C m s % 2 C m v % 2 C p l % 2 C r a t e b y p a s s % 2 C r e q u i r e s s l % 2 C s o u r c e % 2 C u p n % 2 C e x p i r e & i t a g = 4 3 & l m t = 1 4 2 8 7 2 8 3 6 3 9 5 5 9 1 5 & i d = o - A D o I 6 V Z d y U P 4 I V t r e 0 b 7 o D r I f c A a 6 u 2 D p Q M v g e 7 q h 9 f y & d u r = 0 : Downloading webpage
ERROR: Unable to download webpage: nonnumeric port: ' ' (caused by InvalidURL("nonnumeric port: '\x00'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python34\lib\site-packages\youtube_dl\extractor\common.py", line 394, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1985, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python34\lib\urllib\request.py", line 463, in open
    response = self._open(req, data)
  File "c:\python34\lib\urllib\request.py", line 481, in _open
    '_open', req)
  File "c:\python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "c:\python34\lib\site-packages\youtube_dl\utils.py", line 838, in http_open
    req)
  File "c:\python34\lib\urllib\request.py", line 1152, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "c:\python34\lib\site-packages\youtube_dl\utils.py", line 775, in _create_http_connection
    hc = http_class(*args, **kwargs)
  File "c:\python34\lib\http\client.py", line 750, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "c:\python34\lib\http\client.py", line 791, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])

PS C:\Users\vicky\downloads>
