### ISSUE TITLE
error in prepare_manpage.py

### ISSUE THREAD

**Issue by remitamine** [rg3/youtube-dl#10273]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.07**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
```
make
zip --quiet youtube-dl youtube_dl/*.py youtube_dl/*/*.py
zip --quiet --junk-paths youtube-dl youtube_dl/__main__.py
echo '#!/usr/bin/env python' > youtube-dl
cat youtube-dl.zip >> youtube-dl
rm youtube-dl.zip
chmod a+x youtube-dl
COLUMNS=80 /usr/bin/env python youtube_dl/__main__.py --help | /usr/bin/env python devscripts/make_readme.py
/usr/bin/env python devscripts/make_contributing.py README.md CONTRIBUTING.md
pandoc -f markdown -t plain README.md -o README.txt
/usr/bin/env python devscripts/prepare_manpage.py youtube-dl.1.temp.md
Traceback (most recent call last):
  File "devscripts/prepare_manpage.py", line 74, in <module>
    main()
  File "devscripts/prepare_manpage.py", line 39, in main
    readme = filter_options(readme)
  File "devscripts/prepare_manpage.py", line 57, in filter_options
    option, description = re.split(r'\s{2,}', line.lstrip())
ValueError: not enough values to unpack (expected 2, got 1)
make: *** [Makefile:72: youtube-dl.1] Error 1
```

---

### Description of your *issue*, suggested solution and other information

the error is related to:
```python
            if line.lstrip().startswith('-'):
                option, description = re.split(r'\s{2,}', line.lstrip())
```
when it tries to process this line in `README.md`:
```
                                     --max-sleep-interval.
```

**Comment by yan12125** [comment]
Thanks. It's my fault that not considering such a case at the first time.
