### ISSUE TITLE
can't dl videos from france3-regions.francetvinfo.fr

### ISSUE THREAD

**Issue by XXXXXXXian** [rg3/youtube-dl#10289]
I can't dl videos from france3-regions.francetvinfo.fr
Here are the logs :
youtube-dl --verbose "france3-regions.francetvinfo.fr/limousin/emissions/jt-1920-limousin.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'france3-regions.francetvinfo.fr/limousin/emissions/jt-1920-limousin.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.01
[debug] Python version 2.7.10 - Linux-4.2.0-42-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[francetvinfo.fr] jt-1920-limousin: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/francetv.py", line 229, in _real_extract
    webpage, 'video id').split('@')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 650, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
There is no video at http://france3-regions.francetvinfo.fr/limousin/emissions/jt-1920-limousin.html.
