### ISSUE TITLE
youtube-dl playlist downloading problem

### ISSUE THREAD

**Issue by gauravjain99** [rg3/youtube-dl#10287]
$ youtube-dl https://www.youtube.com/playlist?list=PLwPHfM4tydcmxAbNkOTOTK--aN5mKcsmZ
[youtube:playlist] PLwPHfM4tydcmxAbNkOTOTK--aN5mKcsmZ: Downloading webpage
[download] Downloading playlist: The Best of Latin Angels Music
[youtube:playlist] playlist The Best of Latin Angels Music: Downloading 28 videos
[download] Downloading video 1 of 28
[youtube] 6B19MhpSxPw: Downloading webpage
[youtube] 6B19MhpSxPw: Downloading video info webpage
[youtube] 6B19MhpSxPw: Extracting video information
[youtube] 6B19MhpSxPw: Downloading js player en_US-vflxMAwM7
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 820, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 883, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'hy'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'hy'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
