### ISSUE TITLE
Support NBC Olympics

### ISSUE THREAD

**Issue by PsychoDex** [rg3/youtube-dl#10295]
Hello guys 
First I want to say that I am new here and I have absolutely no knowledge about programming and other things.
BUT there are exactly 2 videos I definitely want to have for own use. So I downloaded youtube-dl and Python and I wanted to download those two links: 
http://stream.nbcolympics.com/tennis-day-1-court-2-match-3
http://stream.nbcolympics.com/tennis-day-1-court-3-match-5

i have to say that I live in Europe so I can only watch them with 'Unlimited Free VPN - Hola' and only for a 30 minute trial. 
After that i did my research and found youtube-dl and tried to download it but it is still not working.

So my question is: Is there something I can do to get those videos or would there be someone who can download them for me and send them to me mybe by e-mail ????

And this is what I get when i try to download them : 

C:\Users\Pascal\Desktop\youtube-dl>youtube-dl http://stream.nbcolympics.com/tenn
is-day-1-court-2-match-3
[generic] tennis-day-1-court-2-match-3: Requesting header
WARNING: Falling back on generic information extractor.
[generic] tennis-day-1-court-2-match-3: Downloading webpage
[generic] tennis-day-1-court-2-match-3: Extracting information
ERROR: Unsupported URL: http://stream.nbcolympics.com/tennis-day-1-court-2-match
-3

I hope I can find someone who can help me

Regards

**Comment by ProgrammerAKL** [comment]
I am quite sure that the short videos at nbcolympics.com are quite distinct from the long videos at stream.nbcolympics.com. We may even need two different extractors, one for www.nbcolympics.com and another for stream.nbcolympics.com. [So, should this be divided into two separate issues, with www.nbcolympics.com being the less complicated site to add support for?]
Please act on this soon as I am not sure when the videos will disappear.

**Comment by superxuxin** [comment]
Any updates on this? Would like to download http://stream.nbcolympics.com/table-tennis-day-12-evening-session

**Comment by PsychoDex** [comment]
Hey Guys
I havent't found a solution yet yet but I found a method in another forum that should work. With AdobeHDS.php you should be able to catch the content from stream.nbcolympics.com. I couldn't try it yet so I can't guarantee  you success. 
Here is the link to the eplanation: http://stream-recorder.com/forum/trying-download-vod-cbc-sports-cbc-olympics-t22074p4.html?s=40d281819b08118cb0f7e9a6bc5996bd&amp;

Maybe you can give a feedback here if this works

**Comment by yan12125** [comment]
Dunno why, but suddenly all stream.nbcolympics.com videos stop working for me. There's neither error message nor login prompt - it just hangs, so I add support for www.nbcolympics.com only. Can anyone check whether stream.nbcolympics.com is still running?
