### ISSUE TITLE
Fetching YouTube mp4 URL for iOS

### ISSUE THREAD

**Issue by jmgirven** [rg3/youtube-dl#10302]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.12**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

The HCYouTubeParser (https://github.com/hellozimi/HCYoutubeParser) library for iOS is supposed to return a URL to an MP4 file for a given YouTube link. It is no longer supported and does not seem to work with videos that have adverts on them / unlicensed music. I noticed that version 2015.02.28 of this library also seemed to have a similar problem. When updating to version 2016.8.12, everything works fine. Would you be able to point me to an issue or set of pull requests that go about fixing this issue for youtube-dl, such that I could understand the fix?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/commits/master/youtube_dl/extractor/youtube.py
