### ISSUE TITLE
CANNOT DOWNLOAD THE REST OF THE VIEDEOS IF ERROR IS ENCOUNTERED

### ISSUE THREAD

**Issue by ssjc02** [rg3/youtube-dl#10314]
collo@collo:~/Music$ youtube-dl --yes-playlist --extract-audio --audio-format mp3 "https://www.youtube.com/watch?v=1cQh1ccqu8M&index=13&list=PLkgWEYvTsgqHO6vTqQEqWxBlW_6ykRmYz"
[youtube:playlist] Downloading playlist PLkgWEYvTsgqHO6vTqQEqWxBlW_6ykRmYz - add --no-playlist to just download video 1cQh1ccqu8M
[youtube:playlist] PLkgWEYvTsgqHO6vTqQEqWxBlW_6ykRmYz: Downloading webpage
[download] Downloading playlist: My Favorite Songs, Rock Playlist, Alternative Rock Playlist, Movie Soundtracks, etc.
[youtube:playlist] PLkgWEYvTsgqHO6vTqQEqWxBlW_6ykRmYz: Downloading page #1
[youtube:playlist] PLkgWEYvTsgqHO6vTqQEqWxBlW_6ykRmYz: Downloading page #2
[youtube:playlist] PLkgWEYvTsgqHO6vTqQEqWxBlW_6ykRmYz: Downloading page #3
[youtube:playlist] playlist My Favorite Songs, Rock Playlist, Alternative Rock Playlist, Movie Soundtracks, etc.: Downloading 336 videos
[download] Downloading video 1 of 336
[youtube] ktvTqknDobU: Downloading webpage
[youtube] ktvTqknDobU: Downloading video info webpage
[youtube] ktvTqknDobU: Extracting video information
[download] Destination: Imagine Dragons - Radioactive-ktvTqknDobU.webm
[download] 100% of 3.81MiB in 00:02
[ffmpeg] Destination: Imagine Dragons - Radioactive-ktvTqknDobU.mp3
Deleting original file Imagine Dragons - Radioactive-ktvTqknDobU.webm (pass -k to keep)
[download] Downloading video 2 of 336
[youtube] CSvFpBOe8eY: Downloading webpage
[youtube] CSvFpBOe8eY: Downloading video info webpage
[youtube] CSvFpBOe8eY: Extracting video information
[download] Destination: System Of A Down - Chop Suey!-CSvFpBOe8eY.webm
[download] 100% of 3.15MiB in 00:01
[ffmpeg] Destination: System Of A Down - Chop Suey!-CSvFpBOe8eY.mp3
Deleting original file System Of A Down - Chop Suey!-CSvFpBOe8eY.webm (pass -k to keep)
[download] Downloading video 3 of 336
[youtube] mWRsgZuwf_8: Downloading webpage
[youtube] mWRsgZuwf_8: Downloading video info webpage
[youtube] mWRsgZuwf_8: Extracting video information
[download] Destination: Imagine Dragons - Demons (Official)-mWRsgZuwf_8.webm
[download] 100% of 3.38MiB in 00:05
[ffmpeg] Destination: Imagine Dragons - Demons (Official)-mWRsgZuwf_8.mp3
Deleting original file Imagine Dragons - Demons (Official)-mWRsgZuwf_8.webm (pass -k to keep)
[download] Downloading video 4 of 336
[youtube] kXYiU_JCYtU: Downloading webpage
[youtube] kXYiU_JCYtU: Downloading video info webpage
[youtube] kXYiU_JCYtU: Extracting video information
[download] Destination: Numb (Official Video) - Linkin Park-kXYiU_JCYtU.webm
[download] 100% of 2.77MiB in 00:01
[ffmpeg] Destination: Numb (Official Video) - Linkin Park-kXYiU_JCYtU.mp3
Deleting original file Numb (Official Video) - Linkin Park-kXYiU_JCYtU.webm (pass -k to keep)
[download] Downloading video 5 of 336
[youtube] vx2u5uUu3DE: Downloading webpage
[youtube] vx2u5uUu3DE: Downloading video info webpage
[youtube] vx2u5uUu3DE: Extracting video information
[download] Destination: Bon Jovi - It's My Life-vx2u5uUu3DE.webm
[download] 100% of 3.89MiB in 00:05
[ffmpeg] Destination: Bon Jovi - It's My Life-vx2u5uUu3DE.mp3
Deleting original file Bon Jovi - It's My Life-vx2u5uUu3DE.webm (pass -k to keep)
[download] Downloading video 6 of 336
[youtube] nIjVuRTm-dc: Downloading webpage
[youtube] nIjVuRTm-dc: Downloading video info webpage
[youtube] nIjVuRTm-dc: Extracting video information
[download] Destination: Maroon 5 - She Will Be Loved-nIjVuRTm-dc.webm
[download] 100% of 4.41MiB in 00:06
[ffmpeg] Destination: Maroon 5 - She Will Be Loved-nIjVuRTm-dc.mp3
Deleting original file Maroon 5 - She Will Be Loved-nIjVuRTm-dc.webm (pass -k to keep)
[download] Downloading video 7 of 336
[youtube] 5anLPw0Efmo: Downloading webpage
[youtube] 5anLPw0Efmo: Downloading video info webpage
[youtube] 5anLPw0Efmo: Extracting video information
[download] Destination: Evanescence - My Immortal-5anLPw0Efmo.webm
[download] 100% of 4.54MiB in 00:03
[ffmpeg] Destination: Evanescence - My Immortal-5anLPw0Efmo.mp3
Deleting original file Evanescence - My Immortal-5anLPw0Efmo.webm (pass -k to keep)
[download] Downloading video 8 of 336
[youtube] 3YxaaGgTQYM: Downloading webpage
[youtube] 3YxaaGgTQYM: Downloading video info webpage
[youtube] 3YxaaGgTQYM: Extracting video information
[download] Destination: Evanescence - Bring Me To Life-3YxaaGgTQYM.webm
[download] 100% of 3.86MiB in 00:03
[ffmpeg] Destination: Evanescence - Bring Me To Life-3YxaaGgTQYM.mp3
Deleting original file Evanescence - Bring Me To Life-3YxaaGgTQYM.webm (pass -k to keep)
[download] Downloading video 9 of 336
[youtube] YlUKcNNmywk: Downloading webpage
[youtube] YlUKcNNmywk: Downloading video info webpage
ERROR: YouTube said: This video is available in Andorra, Albania, Argentina, Austria, Australia, Bosnia and Herzegovina, Belgium, Bulgaria, Bolivia, Plurinational State of, Bonaire, Sint Eustatius and Saba, Brazil, Canada, Switzerland, Chile, China, Colombia, Cuba, Curaçao, Cyprus, Czech Republic, Germany, Denmark, Estonia, Egypt, Spain, Finland, France, United Kingdom, Greece, Hong Kong, Croatia, Hungary, Indonesia, Ireland, Israel, India, Iran, Islamic Republic of, Iceland, Italy, Japan, Korea, Democratic People's Republic of, Korea, Republic of, Lithuania, Luxembourg, Latvia, Monaco, Montenegro, Macedonia, the Former Yugoslav Republic of, Malta, Mexico, Malaysia, Nigeria, Netherlands, Norway, New Zealand, Peru, Papua New Guinea, Philippines, Poland, Portugal, Paraguay, Romania, Serbia, Russian Federation, Sweden, Singapore, Slovenia, Slovakia, South Sudan, Sint Maarten (Dutch part), Syrian Arab Republic, Thailand, Turkey, Taiwan, Province of China, Ukraine, United States, Uruguay, Venezuela, Bolivarian Republic of, South Africa only
collo@collo:~/Music$

**Comment by dstftw** [comment]
Use `-i`.
