### ISSUE TITLE
An IE for Redbull.com

### ISSUE THREAD

**Issue by yasoob** [rg3/youtube-dl#1032]
Example url `http://www.redbull.com/en/motorsports/offroad/stories/1331600645172/video-phantom-cam-footage-from-red-bull-romaniacs`

It uses brightcove.com for videos. However [cfe50f0](https://github.com/rg3/youtube-dl/commit/cfe50f04edba5235ec0f33a95fe2093a62b53b62) added support for automatically detecting brightcove videos on some websites but it is not able to detect videos on redbull.

**Comment by renaudguerin** [comment]
Hi, what would it take to add support for redbull.tv too ?

**Comment by dstftw** [comment]
@renaudguerin, at least a new issue with a proper [site support request](https://github.com/rg3/youtube-dl#bugs).

**Comment by renaudguerin** [comment]
@dstftw Sorry, didn't read properly. There's an issue already at #3919 actually, I've just added to it.
