### ISSUE TITLE
Site Support Request: ketnet.be

### ISSUE THREAD

**Issue by mahtavaa** [rg3/youtube-dl#10343]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.13*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://www.ketnet.be/kijken/w817/reeks-3-aflevering-64
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.ketnet.be/kijken/w817/reeks-3-aflevering-64']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.08.13
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: ffmpeg N-80363-g403a53c, ffprobe N-80363-g403a53c
[debug] Proxy map: {}
[generic] reeks-3-aflevering-64: Requesting header
WARNING: Falling back on generic information extractor.
[generic] reeks-3-aflevering-64: Downloading webpage
[generic] reeks-3-aflevering-64: Extracting information
ERROR: Unsupported URL: https://www.ketnet.be/kijken/w817/reeks-3-aflevering-64
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 347, in extract
    return self._real_extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\generic.py", line 2344, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.ketnet.be/kijken/w817/reeks-3-aflevering-64
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.ketnet.be/kijken/w817/reeks-3-aflevering-64
- Single video: https://www.ketnet.be/kijken/spring/aflevering-134

---

### Description of your *issue*, suggested solution and other information

This site uses vrt player 2.11.2 and is (probably) geo-restricted to Belgium only.
But neither the existing extractors vrt.py or canvas.py are currently able to do the job.

**Comment by yan12125** [comment]
The first video is available in Taiwan, and the second video says it's limited to Belgium.
