### ISSUE TITLE
Can't download from VGTV

### ISSUE THREAD

**Issue by duiz** [rg3/youtube-dl#10348]
I'm trying to download a documentary from VGTV but I am getting an error.

C:\Users\User\Downloads>youtube-dl --verbose "http://www.vgtv.no/#!/video/127205/inside-the-mind-of-favela-funk"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.vgtv.no/#!/video/127205/inside-the-mind-of-favela-funk']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.13
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[VGTV] 127205: Downloading media JSON
[VGTV] 127205: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[VGTV] 127205: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\vgtv.py", line 199, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\common.py", line 901, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This video is geo restricted. Can you watch it in browser in the first place?

**Comment by duiz** [comment]
Yeah, though through VPN since I am currently on vacation.

**Comment by dstftw** [comment]
If it's regular VPN then it must be active when you run youtube-dl. If you're using a browser plugin like Hola VPN then it won't work since only browser is affected.

**Comment by duiz** [comment]
My VYPR VPN is active while running it.

**Comment by yan12125** [comment]
Not all VPNs affect the whole system. You may want to ask the VPN provider for how to use it in applications other than browsers.
