### ISSUE TITLE
Unable to Download Webpage 

### ISSUE THREAD

**Issue by psycomani** [rg3/youtube-dl#10340]
Im having This issuse during istall.

ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Please someone Help .
Thanks

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by psycomani** [comment]
It is worth More , The way how i wrote it , or The isuse that im Writing
there.
This isnt fair..
