### ISSUE TITLE
Unable to Download Webpage 

### ISSUE THREAD

**Issue by psycomani** [rg3/youtube-dl#10341]
#Hello 

Im having an isusse when trying to download any Youtube Video .
When i put ( youtube-dl https://www.youtube.com/watch/xxxxxx  ) .

Putty Gives me this 

ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I Have try To Reboot the Server Linux but it didnt work.
I Also have the latest version of youtube-dl.

Please Help .. ??

**Comment by dstftw** [comment]
1. https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required
2. #5138.
