### ISSUE TITLE
Cannot download all video from playlist becouse "ERROR: os6aP5w46TM: YouTube said: Please sign in to view this video"

### ISSUE THREAD

**Issue by patsevanton** [rg3/youtube-dl#10346]
youtube-dl -v https://www.youtube.com/playlist?list=PL6CB751D81C7CB539
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'bestvideo+bestaudio/best', u'-v', u'https://www.youtube.com/playlist?list=PL6CB751D81C7CB539']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.12
[debug] Python version 2.7.12 - Linux-4.4.0-31-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PL6CB751D81C7CB539: Downloading webpage
[download] Downloading playlist: Conversational Arabic
[youtube:playlist] playlist Conversational Arabic: Downloading 39 videos
......
ERROR: os6aP5w46TM: YouTube said: Please sign in to view this video.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1321, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: os6aP5w46TM: YouTube said: Please sign in to view this video.

**Comment by yan12125** [comment]
Please provide credentials via ```--username``` and ```--password``` or ```--netrc```. If you don't want non-public videos, add ```--ignore-errors```.
