### ISSUE TITLE
Bug report: malformed URL returned

### ISSUE THREAD

**Issue by tgragnato** [rg3/youtube-dl#10357]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.13**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### Version

youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.13
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

This affects at least 2016.08.13 (brew install --HEAD youtube-dl) & 2016.08.10 (brew install youtube-dl).

### Bug Report

The output of `youtube-dl -g http://vidto.me/3u9q0f3awai7.html` is
>http://198.16.68.106/gjjhpi5jhyqwws4phx5dun6hwxoawrinoy5pt7drztqqo7rccmfwyuvtyjna/video.mp4"},{label:"360p

The correct URL is obviously
>http://198.16.68.106/gjjhpi5jhyqwws4phx5dun6hwxoawrinoy5pt7drztqqo7rccmfwyuvtyjna/video.mp4

### Note

I am aware of #7032, but I am also aware that VidTo is XFileShare based and actually supported.

**Comment by yan12125** [comment]
This movie is a copyrighted product of Village Roadshow Pictures ([Wikipedia](https://en.wikipedia.org/wiki/The_Legend_of_Tarzan_(film))). Do you have another example?

**Comment by tgragnato** [comment]
Do not worry and sorry for the hassle, I'll look into it.
