### ISSUE TITLE
TV3Play has now changed to Viafree

### ISSUE THREAD

**Issue by infSup33** [rg3/youtube-dl#10358]
It redirects to viafree.no, and the extractor isn't working anymore

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by infSup33** [comment]
http://www.viafree.no/programmer/underholdning/det-beste-vorspielet/sesong-2/episode-1

**Comment by dstftw** [comment]
Original URL not redirected.

**Comment by infSup33** [comment]
@dstftw what do you mean?
