### ISSUE TITLE
nbcolympics short videos

### ISSUE THREAD

**Issue by ProgrammerAKL** [rg3/youtube-dl#10361]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.17
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```
Here is the command I ran -
```
youtube-dl.exe -o "E:/yt-dl-test1" "http://www.nbcolympics.com/video/justin-roses-son-leo-was-tears-after-his-dad-won-gold" --no-check-certificate --verbose
```

Here is the log -
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-o', 'E:/yt-dl-test1', 'http://www.nbcolympics.com/
video/justin-roses-son-leo-was-tears-after-his-dad-won-gold', '--no-check-certif
icate', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.08.17
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] justin-roses-son-leo-was-tears-after-his-dad-won-gold: Requesting head
er
WARNING: Falling back on generic information extractor.
[generic] justin-roses-son-leo-was-tears-after-his-dad-won-gold: Downloading web
page
[generic] justin-roses-son-leo-was-tears-after-his-dad-won-gold: Extracting info
rmation
ERROR: Unsupported URL: http://www.nbcolympics.com/video/justin-roses-son-leo-wa
s-tears-after-his-dad-won-gold
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpigau_o17\bu
ild\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpigau_o17\bu
ild\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpigau_o17\bu
ild\youtube_dl\extractor\generic.py", line 2362, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.nbcolympics.com/v
ideo/justin-roses-son-leo-was-tears-after-his-dad-won-gold
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included:

- Single video: http://www.nbcolympics.com/video/justin-roses-son-leo-was-tears-after-his-dad-won-gold
- Single video: http://www.nbcolympics.com/video/david-feherty-talks-olympic-gold-medal-winner-justin-rose

---

### Description of your *issue*, suggested solution and other information

Please add support for the short-form videos at nbcolympics.com - the specific URLs I provided above are the priorities. Note that these are just short clips - this request is not about the long videos of complete events. Hopefully this should be quite straightforward. Thank you.

**Comment by yan12125** [comment]
Just found there's already a request at #10295. Please move there for further discussions.
