### ISSUE TITLE
Download from cbsnews error

### ISSUE THREAD

**Issue by MrD37jncj** [rg3/youtube-dl#10362]
Hi there, today i download video from cbsnews and get error:
youtube-dl --verbose http://www.cbsnews.com/videos/blood-and-money/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.cbsnews.com/videos/blood-and-money/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.17
[debug] Python version 2.7.12 - Linux-4.4.0-22-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg N-81246-gc5cc3b0, ffprobe N-81246-gc5cc3b0, rtmpdump 2.4
[debug] Proxy map: {}
[CBSNews] blood-and-money: Downloading webpage
[CBSNews] Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 433, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 423, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1786, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/cbsnews.py", line 66, in _real_extract
    return self._extract_video_info('byGuid=%s' % guid, guid)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/cbs.py", line 29, in _extract_video_info
    'manifest': 'm3u',
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/theplatform.py", line 308, in _extract_feed_info
    entry = self._download_json(real_url, video_id)['entries'][0]
IndexError: list index out of range

i tried many time and some videos still download sucssesfully some one not.

**Comment by dstftw** [comment]
This video does not play in browser.

**Comment by snnn** [comment]
How about this one?
$ ./youtube-dl --verbose 'http://www.cbsnews.com/videos/819-zika-cluster-in-miami-beach-white-missouri-womans-slave-cabin-sparks-race-talk/'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.cbsnews.com/videos/819-zika-cluster-in-miami-beach-white-missouri-womans-slave-cabin-sparks-race-talk/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.19
[debug] Python version 2.7.12 - Linux-4.6.6-300.fc24.x86_64-x86_64-with-fedora-24-Twenty_Four
[debug] exe versions: ffmpeg 3.1.2, ffprobe 3.1.2
[debug] Proxy map: {}
[CBSNews] 819-zika-cluster-in-miami-beach-white-missouri-womans-slave-cabin-sparks-race-talk: Downloading webpage
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 433, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 423, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1786, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
  File "./youtube-dl/youtube_dl/extractor/cbsnews.py", line 66, in _real_extract
  File "./youtube-dl/youtube_dl/extractor/cbs.py", line 29, in _extract_video_info
  File "./youtube-dl/youtube_dl/extractor/theplatform.py", line 308, in _extract_feed_info
IndexError: list index out of range

**Comment by remitamine** [comment]
already reported in #10393 and .
it will be fixed in the next version:
```
youtube-dl -F http://www.cbsnews.com/videos/819-zika-cluster-in-miami-beach-white-missouri-womans-slave-cabin-sparks-race-talk/
[CBSNews] 819-zika-cluster-in-miami-beach-white-missouri-womans-slave-cabin-sparks-race-talk: Downloading webpage
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading SMIL data
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading m3u8 information
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading HLS SMIL data
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading m3u8 information
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading m3u8 information
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading m3u8 information
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading m3u8 information
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading m3u8 information
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading m3u8 information
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading m3u8 information
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading RTMP SMIL data
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading WIFI SMIL data
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Checking video URL
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Checking video URL
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading 3G SMIL data
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Checking video URL
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Checking video URL
[CBSNews] CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt: Downloading JSON metadata
[info] Available formats for CUId6q_bNgKvB9xx6hVoxmlpxuz6WPHt:
format code  extension  resolution note
hls-meta     mp4        multiple   Quality selection URL 
hls-42       mp4        audio only   42k , mp4a.40.2
hls-1        mp4        400x224       1k 
hls-110      mp4        400x224     110k 
http-150     mp4        400x224     150k 
hls-169      mp4        400x224     169k , avc1.66.30, mp4a.40.2
http-240     mp4        400x224     240k 
hls-250      mp4        400x224     250k 
hls-313      mp4        400x224     313k , avc1.66.30, mp4a.40.2
rtmp-364     flv        384x216     364k 
http-440     mp4        400x224     440k 
rtmp-496     flv        640x360     496k 
hls-500      mp4        512x288     500k 
hls-552      mp4        512x288     552k , avc1.66.30, mp4a.40.2
http-740     mp4        640x360     740k 
rtmp-796     flv        640x360     796k 
hls-800      mp4        640x360     800k 
hls-863      mp4        640x360     863k , avc1.66.30, mp4a.40.2
hls-1200     mp4        768x432    1200k 
hls-1293     mp4        768x432    1293k , avc1.77.30, mp4a.40.2
rtmp-1296    flv        640x360    1296k 
hls-1800     mp4        960x540    1800k 
hls-1919     mp4        960x540    1919k , avc1.77.30, mp4a.40.2
rtmp-1928    flv        1280x720   1928k 
hls-2694     mp4        1024x576   2694k , avc1.77.30, mp4a.40.2
hls-3733     mp4        1280x720   3733k , avc1.77.30, mp4a.40.2 (best)
```
