### ISSUE TITLE
MTV Services download error

### ISSUE THREAD

**Issue by pepoluan** [rg3/youtube-dl#10363]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
% youtube-dl --verbose 'http://www.mtv.com/news/2887508/zootopia-directors-fandom-nick-judy-fanart/'
[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg', u'--ffmpeg-location', u'/usr/local/bin/ffmpeg']
[debug] Command-line args: [u'--verbose', u'http://www.mtv.com/news/2887508/zootopia-directors-fandom-nick-judy-fanart/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.17
[debug] Python version 2.7.10 - CYGWIN_NT-10.0-2.5.2-0.297-5-3-x86_64-64bit
[debug] exe versions: ffmpeg N-80256-g0a9e781, ffprobe N-80256-g0a9e781
[debug] Proxy map: {}
[generic] zootopia-directors-fandom-nick-judy-fanart: Requesting header
WARNING: Falling back on generic information extractor.
[generic] zootopia-directors-fandom-nick-judy-fanart: Downloading webpage
[generic] zootopia-directors-fandom-nick-judy-fanart: Extracting information
[mtvservices:embedded] f1ef5427-f7e6-4fcf-a9ea-164f51f10d2a: Downloading XML
ERROR: Unable to download XML: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 394, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1996, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```

### Description of your *issue*, suggested solution and other information

I was just trying to download a video embedded in [this page](http://www.mtv.com/news/2887508/zootopia-directors-fandom-nick-judy-fanart/). It seems like youtube-dl successfully identified the embedded video and even the embedded video's provider, but for unclear reasons (to me) failed to follow through.

**Comment by yan12125** [comment]
@pepoluan Thanks for the report. Such MTVServices embedded videos will work again in the next version.
