### ISSUE TITLE
Suggestion for --download-archive option to improve playlist downloads

### ISSUE THREAD

**Issue by keith4141** [rg3/youtube-dl#10373]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Hi.

I would like to suggest an additional option for use with the --download-archive option.  This is to help with keeping playlists downloaded from youtube complete, and not missing videos.  When I say missing videos, I don't mean that its a bug but rather how the download archive option works.

For example,
Say we have a single video that is in 2 different playlists.  Using the --download-archive option, the video will be downloaded for playlist1 and added to the download-archive file.  It will be skipped for playlist2 as it has already been downloaded for playlist1.

But I think it would be nice to have the option to ALSO download that video again to keep a playlist complete.  Perhaps something like --ignore-forplaylists or some such.  So when we get to downloading playlist2, it will also download the video to have playlist2 complete, even though it was already downloaded for playlist1.

The main reason for this is if I'm watching a playlist that has 10 videos, but 2 of them were already downloaded in some other playlist - well, I need to go hunting for these 2 videos in the other downloaded playlists so that I can watch the videos in sequence, as they are missing from playlist2.

I hope this makes sense.

Thanks alot, I appreicate the work thats gone into the script and just want to say it works great.

Cheers,
Keith.

**Comment by keith4141** [comment]
Sorry I forgot to mention why I am using the --download-archive option to download the playlists.

I run youtube-dl 2 times for a channel, once to download the playlists and then another time to download the other videos that are not in a playlist.  This helps to keep things organised.

For this second run, I certainly don't want to download the videos again if they were already been downloaded for a playlist previously.

Thanks,
Keith.

**Comment by dstftw** [comment]
Use separate download archive per playlist.

**Comment by keith4141** [comment]
Hi.

If I used a separate download archive per playlist, I would manually need to merge them together and strip out duplicates for when I run youtube-dl a second time to catch all of the videos not downloaded for any of those playlists.  While I can certainly do this, would this additional option not be of benefit?

Cheers,
Keith.
