### ISSUE TITLE
Doesn't work with Pandora.tv

### ISSUE THREAD

**Issue by whitesiroi** [rg3/youtube-dl#10374]
I'm using the newest youtube-dl
```
youtube-dl --version
2016.08.17

```
When I try to run this command:

`youtube-dl http://jp.channel.pandora.tv/channel/video.ptv?ch_userid=sbs-tv&prgid=53371620&categid=all&page=1&ref=ch&lot=cthum2_1_1`

I'm getting this error:
`ERROR: Invalid URL`

Or with -v flag:
```
 [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://jp.channel.pandora.tv/channel/video.ptv?ch_userid=sbs-tv']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.17
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8
[debug] Proxy map: {}
ERROR: Invalid URL
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pandoratv.py", line 43, in _real_extract
    raise ExtractorError('Invalid URL', expected=True)
ExtractorError: Invalid URL
```

**Comment by dstftw** [comment]
You have to either put the URL into quotes or manually escape all the special shell characters. Read [FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for details.

**Comment by whitesiroi** [comment]
Thank you for your response.

I have tried with quotes too:

$ youtube-dl 'http://jp.channel.pandora.tv/channel/video.ptv?ch_userid=sbs-tv&prgid=53371620&categid=all&page=1&ref=ch&lot=cthum2_1_1'
[pandora.tv] 53371620: Downloading JSON metadata
ERROR: unable to download video data: IncompleteRead(0 bytes read)

$ youtube-dl "http://jp.channel.pandora.tv/channel/video.ptv?ch_userid=sbs-tv&prgid=53371620&categid=all&page=1&ref=ch&lot=cthum2_1_1"
[pandora.tv] 53371620: Downloading JSON metadata
ERROR: unable to download video data: IncompleteRead(0 bytes read)

**Comment by whitesiroi** [comment]
I updated to 2016.08.22 & it does work now. Thank you very much
