### ISSUE TITLE
Cannot download from bilibili.com

### ISSUE THREAD

**Issue by AhernWalker** [rg3/youtube-dl#10384]
F:\B\upload>d http://www.bilibili.com/video/av5893532/
[BiliBili] 5893532: Downloading webpage
[BiliBili] 9569763: Downloading video info page
ERROR: No videos found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Duplicate of #10375. Bilibili is currently broken.
