### ISSUE TITLE
discoverygo parsing error

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#10387]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.19**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
E:\>youtube-dl http://www.discoverygo.com/the-presidents-gatekeepers/a-powerful-fraternity --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.discoverygo.com/the-presidents-gatekeepers/a-powerful-fraternity', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.19
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[DiscoveryGo] a-powerful-fraternity: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('stream',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\discoverygo.py", line 56, in _real_extract
KeyError: 'stream'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\discoverygo.py", line 56, in _real_extract
KeyError: 'stream'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\common.py", line 353, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('stream',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
```

E:\>youtube-dl https://www.animalplanetgo.com/north-woods-law/long-shot/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.animalplanetgo.com/north-woods-law/long-shot/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.19
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[DiscoveryGo] long-shot: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('stream',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\discoverygo.py", line 56, in _real_extract
KeyError: 'stream'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\discoverygo.py", line 56, in _real_extract
KeyError: 'stream'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\common.py", line 353, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('stream',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.animalplanetgo.com/north-woods-law/long-shot/
- Single video: http://www.discoverygo.com/the-presidents-gatekeepers/a-powerful-fraternity

---

**Comment by remitamine** [comment]
> SIGN IN WITH YOUR TV PROVIDER
You’re just a few clicks away from the show you want to watch. Please sign in with your TV provider to watch this episode and other great programs.

it works with `--cookies` option:
```
youtube-dl -o '%(season)s/%(episode_number)s - %(title)s.%(ext)s' --cookies ~/cookies.txt https://www.ahctvgo.com/codes-and-conspiracies/founding-fathers/
[DiscoveryGo] founding-fathers: Downloading webpage
[DiscoveryGo] founding-fathers: Downloading m3u8 information
WARNING: ar subtitles not available for 55b690e76b66d1ea0a2f9633
[info] Writing video subtitles to: Season 2/1 - Founding Fathers.en.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 270
[download] Destination: Season 2/1 - Founding Fathers.mp4
[download]  10.0% of ~1.01GiB at 301.72KiB/s ETA 34:00
```

**Comment by StevenDTX** [comment]
Thank you!

This is the first time I have ever gotten a cookies file to work.

**Comment by dare2** [comment]
I hate to comment on an old closed issue, but I am clueless on how to get the cookie info for discoverygo, or really any cookie.

**Comment by StevenDTX** [comment]
@dare2 

I use Chrome, so these are the instructions for Chrome.

1) Install https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg?hl=en-US to get the cookies.txt for discoverygo.com
2) Play the video you want in Chrome, making sure you are logged into your provider.
3) Click the cookies.txt icon in the Chrome toolbar.  It looks like this:  http://i.imgur.com/wE7Kuhh.png
4) Copy the contents of the window to a text file. Mine is called cookies-DISCGO.txt
5) Use this command line to download the show:  youtube-dl.exe --restrict-filenames --continue --no-check-certificate --verbose --cookies e:\cookies-DISCGO.txt -o Bering.Sea.Gold.S07E04.mp4 https://www.discoverygo.com/bering-sea-gold/double-jeopardy/

**Comment by dare2** [comment]
Thank you, I found that blurb on my own, and got it to work. I had just come in here to edit/delete my comment. :)
