### ISSUE TITLE
How do you download multiple formats and skip merging?

### ISSUE THREAD

**Issue by vibrasphere** [rg3/youtube-dl#10399]
Each time I have to enter -k to keep both formats I downloaded (e.g. -f http720+http1080 -k), but it still merge it, which I don't need.

How I skip merge?

**Comment by yan12125** [comment]
Well, just curious - why you need unmerged formats?

**Comment by vibrasphere** [comment]
Various reasons, encoding, testing on multiple devices. I usually work with 480p 540p 720p and 1080p files.

**Comment by yan12125** [comment]
From the [format selection](https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection) section:

> If you want to download several formats of the same video use comma as a separator, e.g. -f 22,17,18 will download all these three formats, of course if they are available. Or more sophisticated example combined with precedence feature -f 136/137/mp4/bestvideo,140/m4a/bestaudio

Sounds that's what you need, isn't it? It's indeed not so obvious. Will add an example to [format selection examples](https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection-examples)

**Comment by vibrasphere** [comment]
OK, great. Thanks for help
