### ISSUE TITLE
another way to bypass geo-restricted youtube video

### ISSUE THREAD

**Issue by wangtubs** [rg3/youtube-dl#10394]
Make sure you are using the latest version: run youtube-dl --version and ensure your version is 2016.08.19. If it's not read this FAQ entry and update. Issues with outdated version will be rejected.

 I've verified and I assure that I'm running youtube-dl 2016.08.19
Before submitting an issue make sure you have:

 At least skimmed through README and most notably FAQ and BUGS sections
 Searched the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Other
### Description of your *issue*, suggested solution and other information

I find some other websites like keepvid.com use a different way to get youtube videos and they can bypass geo-restricted, copyright protected, and age restricted youtube videos. for example, 
http://www.youtube.com/watch?v=K2m_HTIFSS0
i can download it on my own computer, using youtube-dl, but other people in a different country can't download. however, keepvid.com can bypass this restrict,
http://keepvid.com/?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DK2m_HTIFSS0,

the download url is like http://redirect.googlevideo.com/XXXXXX
everyone from the world can download the video without any problems. I think they use a different way to parse youtube video. Do you have an idea how they do it? Maybe youtube-dl can use the same way to make it more powerful.

Thanks

**Comment by dstftw** [comment]
This video can be downloaded from multiple locations worldwide without any problem when final URL is resolved on the same machine. The only difference in extraction process is [this](https://github.com/rg3/youtube-dl/issues/9001#issuecomment-201991818). The general youtube-dl rule is that [download request must come from the same IP with the same set of cookies and headers](https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-webbrowser).
