### ISSUE TITLE
Discovery GO not working for Deadliest Catch

### ISSUE THREAD

**Issue by PRMan99** [rg3/youtube-dl#10406]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -v "https://www.discoverygo.com/deadliest-catch/the-widowmaker-part-2/" "c:\temp\Deadliest Catch.mp4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.discoverygo.com/deadliest-catch/the-widowmaker-part-2/', 'c:\\temp\\Deadliest Catch.mp4']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.27
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-80801-gc0cb53c, ffprobe N-80801-gc0cb53c
[debug] Proxy map: {}
[generic] the-widowmaker-part-2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-widowmaker-part-2: Downloading webpage
[generic] the-widowmaker-part-2: Extracting information
ERROR: Unsupported URL: https://www.discoverygo.com/deadliest-catch/the-widowmaker-part-2/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\extractor\common.py", line 343, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\extractor\generic.py", line 2161, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.discoverygo.com/deadliest-catch/the-widowmaker-part-2/
```
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.discoverygo.com/deadliest-catch/the-widowmaker-part-2/
- Playlist: https://www.discoverygo.com/deadliest-catch/

---

### Description of your *issue*, suggested solution and other information

I keep getting "Unsupported URL" even though DiscoveryGO is listed as being available.

**Comment by StevenDTX** [comment]
I can download that URL just fine when using a cookie file.

```
E:\>youtube-dl -v "https://www.discoverygo.com/deadliest-catch/the-widowmaker-part-2/" --cookies e:\cookies-DISCGO.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.discoverygo.com/deadliest-catch/the-widowmaker-part-2/', '--cookies', 'e:\\cookies-DISCGO.txt']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.22
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[DiscoveryGo] the-widowmaker-part-2: Downloading webpage
[DiscoveryGo] the-widowmaker-part-2: Downloading m3u8 information
[debug] Invoking downloader on 'https://dscusvod-vh.akamaihd.net/i/longform/2016-08/03/157378.018.01.001-38123-,500k,200k,350k,800k,1200k,1600k,2200k,3000k,4500k,.mp4.csmil/index_8_av.m3u8?null=0&hdntl=exp=1471982690~acl=%2f*~data=hdntl~hmac=58ec13b2b6816f5be133b5e4dd2c945fda277e0b707d8ee8488e4acc004d4887'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 609
[download] Destination: The Widowmaker - Part 2-57a2be606b66d1cd0345eeab.mp4
[download]   2.3% of ~3.38GiB at  5.66MiB/s ETA 14:49
```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by PRMan99** [comment]
I didn't realize that -U doesn't really update but actually creates a .exe.new file next to the .exe file.

It does work with the latest version.  Thanks.

**Comment by dstftw** [comment]
-U does **exactly** update.
