### ISSUE TITLE
https://yt-dl.org site dont work

### ISSUE THREAD

**Issue by RosadinTV** [rg3/youtube-dl#10402]
The site where *.exe are stored doesn't work:
https://yt-dl.org/latest/youtube-dl.exe

**Comment by Starsam80** [comment]
Downloads just fine for me, and could you clarify what "doesn't work"? Do any errors pop up?

**Comment by dstftw** [comment]
Uberspace has been [under attack](https://blog.uberspace.de/strassenkampf/) today. Currently everything seems to be working.
Also *.exe is not stored on yt-dl.org.

**Comment by RosadinTV** [comment]
The site keeps loading and then timeout (502)

![ytdl_report](https://cloud.githubusercontent.com/assets/13382316/17839441/6862b670-67be-11e6-801b-ef6c827b0241.JPG)

**Comment by Starsam80** [comment]
Then try the github link: https://github.com/rg3/youtube-dl/releases/download/2016.08.19/youtube-dl.exe

**Comment by RosadinTV** [comment]
The problem is i have a program that checks for YTDL updates in https://yt-dl.org/latest/youtube-dl.exe but, thanks anyway, in a few hours may work, @dstftw say Uberspace was under attack.

**Comment by phihag** [comment]
For what it's worth, yt-dl.org now works fine for me, both via IPv6 and IPv4.

**Comment by yan12125** [comment]
Still unavailable from Taiwan:
```
$ ping 95.143.172.170
PING 95.143.172.170 (95.143.172.170) 56(84) bytes of data.
^C
--- 95.143.172.170 ping statistics ---
67 packets transmitted, 0 received, 100% packet loss, time 66008ms

$ curl -4 -v http://yt-dl.org/
*   Trying 95.143.172.170...
* connect to 95.143.172.170 port 80 failed: Connection timed out
* Failed to connect to yt-dl.org port 80: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to yt-dl.org port 80: Connection timed out

$ curl -6 -v http://yt-dl.org/
*   Trying 2001:1a50:11:0:5f:8f:acaa:177...
* connect to 2001:1a50:11:0:5f:8f:acaa:177 port 80 failed: Connection timed out
* Failed to connect to yt-dl.org port 80: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to yt-dl.org port 80: Connection timed out
```

**Comment by Ivoz** [comment]
Same from Australia and [isup.me](http://isup.me/yt-dl.org), still down

**Comment by phihag** [comment]
There is still a massive attack (24GBit/s) ongoing; as a workaround, traffic from outside Europe is being blackholed. We should look into CloudFlare in order to protect us against these kinds of DoS.

**Comment by RosadinTV** [comment]
@phihag Thanks for the info 👍
