### ISSUE TITLE
bravotv extractor update

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#10407]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.22**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
E:\>youtube-dl --verbose http://www.bravotv.com/flipping-out/season-9/ep-6-its-not-your-fault
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.bravotv.com/flipping-out/season-9/ep-6-its-not-your-fault']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.22
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ep-6-its-not-your-fault: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ep-6-its-not-your-fault: Downloading webpage
[generic] ep-6-its-not-your-fault: Extracting information
ERROR: Unsupported URL: http://www.bravotv.com/flipping-out/season-9/ep-6-its-not-your-fault
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\generic.py", line 2377, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.bravotv.com/flipping-out/season-9/ep-6-its-not-your-fault


E:\>youtube-dl --verbose http://www.bravotv.com/flipping-out/season-9/ep-6-its-not-your-fault --netrc
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.bravotv.com/flipping-out/season-9/ep-6-its-not-your-fault', '--netrc']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.22
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ep-6-its-not-your-fault: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ep-6-its-not-your-fault: Downloading webpage
[generic] ep-6-its-not-your-fault: Extracting information
ERROR: Unsupported URL: http://www.bravotv.com/flipping-out/season-9/ep-6-its-not-your-fault
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\generic.py", line 2377, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.bravotv.com/flipping-out/season-9/ep-6-its-not-your-fault


E:\>youtube-dl --verbose http://www.bravotv.com/flipping-out/season-9/ep-6-its-not-your-fault --cookies e:\cookies-BRAVOTV.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.bravotv.com/flipping-out/season-9/ep-6-its-not-your-fault', '--cookies', 'e:\\cookies-BRAVOTV.txt']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.22
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ep-6-its-not-your-fault: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ep-6-its-not-your-fault: Downloading webpage
[generic] ep-6-its-not-your-fault: Extracting information
ERROR: Unsupported URL: http://www.bravotv.com/flipping-out/season-9/ep-6-its-not-your-fault
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\generic.py", line 2377, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.bravotv.com/flipping-out/season-9/ep-6-its-not-your-fault

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.bravotv.com/flipping-out/season-9/ep-6-its-not-your-fault
- Single video: http://www.bravotv.com/below-deck/season-3/ep-15-reunion-part-2
- Single video: http://www.bravotv.com/watch-what-happens-live/season-13/hugh-grant-simon-helberg

---

### Description of your *issue*, suggested solution and other information

It seems that the extractor is not properly parsing the URL. I have tried with --netrc and --cookies.  I get the same results with any BravoTV.com video.  It works if there is a */videos/* in the URL.

Thanks!

**Comment by remitamine** [comment]
> It works if there is a /videos/ in the URL.

the extractor was working incorrectly(select the wrong video).
> It seems that the extractor is not properly parsing the URL.

these kind of urls will work in the next version.
note that the only supported TV provider for now is DirecTV with a netrc file https://github.com/rg3/youtube-dl/issues/10345#issuecomment-239691778.

**Comment by StevenDTX** [comment]
Thanks, @remitamine, its working great!
