### ISSUE TITLE
[Crackle] - Movies not recognised as valid URL's

### ISSUE THREAD

**Issue by zoocey** [rg3/youtube-dl#10419]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.08.22_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.22**
### Before submitting an _issue_ make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\you>youtube-dl.py -F -v http://www.crackle.com/angel-of-death
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'-v', u'http://www.crackle.com/angel-of-deat
h']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.22
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-80953-gd4c8e93, ffprobe N-80953-gd4c8e93
[debug] Proxy map: {}
[generic] angel-of-death: Requesting header
WARNING: Falling back on generic information extractor.
[generic] angel-of-death: Downloading webpage
[generic] angel-of-death: Extracting information
ERROR: Unsupported URL: http://www.crackle.com/angel-of-death
Traceback (most recent call last):
  File "C:\you\youtube-dl.py\youtube_dl\extractor\generic.py", line 1633, in _re
al_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "C:\you\youtube-dl.py\youtube_dl\compat.py", line 2525, in compat_etree_f
romstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=
_element_factory)))
  File "C:\you\youtube-dl.py\youtube_dl\compat.py", line 2514, in _XML
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 22, column 385
Traceback (most recent call last):
  File "C:\you\youtube-dl.py\youtube_dl\YoutubeDL.py", line 691, in extract_info

    ie_result = ie.extract(url)
  File "C:\you\youtube-dl.py\youtube_dl\extractor\common.py", line 347, in extra
ct
    return self._real_extract(url)
  File "C:\you\youtube-dl.py\youtube_dl\extractor\generic.py", line 2377, in _re
al_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.crackle.com/angel-of-death
```

---
### Description of your _issue_, suggested solution and other information

Every movie from the movie section on Crackle fails as being recognized from Crackle and falls back to the generic extractor (which fails).

**Comment by yan12125** [comment]
Superseded by #11775. Like the newer report, I can't find videos in http://www.crackle.com/angel-of-death. If anyone know how to watch crackle videos outside US, feel free to proposed it.
