### ISSUE TITLE
[KickStarter] unable to extract OpenGraph description.

### ISSUE THREAD

**Issue by stepshal** [rg3/youtube-dl#10415]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ y -v 'https://www.kickstarter.com/projects/1420158244/power-drive-2000/widget/video.html'
[debug] System config: []
[debug] User config: ['-4', '-f', 'best', '--prefer-free-formats', '--no-cache-dir', '--no-mtime', '--youtube-skip-dash-manifest']
[debug] Command-line args: ['-v', 'https://www.kickstarter.com/projects/1420158244/power-drive-2000/widget/video.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.22
[debug] Python version 3.6.0a4 - Linux-4.7.0-rc7-686-i686-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.1.2, ffprobe 3.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[KickStarter] 1420158244: Downloading webpage
WARNING: unable to extract OpenGraph description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Invoking downloader on 'https://ksr-video.imgix.net/projects/1784048/video-533555-h264_high.mp4'
```
https://www.kickstarter.com/projects/1420158244/power-drive-2000/widget/video.html

**Comment by yan12125** [comment]
Thanks. This video does not have a description, and there would not be warnings in this case.
