### ISSUE TITLE
Unable to download or upgrade youtube-dl.exe for Windows

### ISSUE THREAD

**Issue by kimbaudi** [rg3/youtube-dl#10410]
I am no longer able to upgrade youtube-dl.exe for Windows using the command `youtube-dl.exe -U`. 

```shell
D:\youtube-dl>youtube-dl.exe -U
Updating to version 2016.08.22 ...
ERROR: unable to download latest version
```

I also tried to re-download youtube-dl.exe for Windows from the download page (https://rg3.github.io/youtube-dl/download.html), but I get a connection timed out error.

**Comment by dstftw** [comment]
yt-dl.org is currently inaccessible outside Europe due to DDoS at our hoster. Use https://github.com/rg3/youtube-dl/releases for downloads.

**Comment by Ivoz** [comment]
Why are you closing issues for an issue that is currently unresolved?

**Comment by dstftw** [comment]
Cause it not a problem within youtube-dl itself. Searching for closed issues is something they **must** agree when filling [new issue template](https://github.com/rg3/youtube-dl/issues/new):
>- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
