### ISSUE TITLE
How to pass the args, when use the option --external-downloader. for example use axel.

### ISSUE THREAD

**Issue by magj2006** [rg3/youtube-dl#10429]
How to pass the args, when use the option --external-downloader. 
It's error, when I use --external-downloader axel --external-downloader-args '-n 10'

**Comment by yan12125** [comment]
Post the full output of your command.

**Comment by magj2006** [comment]
youtube-dl -citk --playlist-start 1 --playlist-end 78 -f webm --external-downloader axel --external-downloader-args '-n 10'  https://www.youtube.com/playlist?list=........

**Comment by yan12125** [comment]
Axel uses HTTP even if fed with HTTPS URLs, and YouTube now reject all non-HTTP URLs. Please forward this bug to the Axel team.

**Comment by yan12125** [comment]
FWIW, this fork works for me: https://github.com/eribertomota/axel. Seems the official Axel has been dead and there's no updates since 6 years ago.

**Comment by magj2006** [comment]
@yan12125 Thank you very much.
