### ISSUE TITLE
Can't download password-protected shows from DiscoveryGo.com

### ISSUE THREAD

**Issue by PRMan99** [rg3/youtube-dl#10425]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.24.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.discoverygo.com/alaskan-bush-people/made-in-the-wild/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.24.1
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-80892-g2a8dadb, ffprobe N-80892-g2a8dadb, rtmpdump 2.3
[debug] Proxy map: {}
[DiscoveryGo] made-in-the-wild: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('stream',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvarrvgfb\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvarrvgfb\build\youtube_dl\extractor\discoverygo.py", line 56, in _real_extract
KeyError: 'stream'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvarrvgfb\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvarrvgfb\build\youtube_dl\extractor\discoverygo.py", line 56, in _real_extract
KeyError: 'stream'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvarrvgfb\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvarrvgfb\build\youtube_dl\extractor\common.py", line 353, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('stream',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


C:\ytdl>
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.discoverygo.com/alaskan-bush-people/made-in-the-wild/

---

### Description of your *issue*, suggested solution and other information

Can't download this show using cable provider username and password.  Downloading the last 2-3 episodes without credentials on DiscoveryGo.com works, as these do not require a login.

**Comment by yan12125** [comment]
Login for discoverygo.com is not implemented yet.

**Comment by remitamine** [comment]
it works with cookies #10387.

**Comment by yan12125** [comment]
Maybe youtube-dl should add a tip to use ```--cookies```, or there would be more similar bug reports.

**Comment by remitamine** [comment]
adultswim has a similar error code i think it can be used in this case as well.

**Comment by PRMan99** [comment]
Is there a reason that a cookies file can't be the default?  It seems like it wouldn't harm anything and we might see improvement on a lot of sites.

**Comment by yan12125** [comment]
There's no standard path for a cookie file. You can add the following line to [your configuration file](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration):
```
--cookies "C:\your_cookies.txt"
```
