### ISSUE TITLE
 Trying to download cover art from soundcloud. "ERROR: ffmpeg or avconv not found. Please install one." (Mac OSX)

### ISSUE THREAD

**Issue by ghy213134** [rg3/youtube-dl#10432]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.24.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

$ youtube-dl --embed-thumbnail https://soundcloud.com/ghyppa-142353405/sets/dl-1/s-CNcux
[soundcloud:set] ghyppa-142353405/sets/dl-1/s-CNcux: Resolving id
[soundcloud:set] ghyppa-142353405/sets/dl-1/s-CNcux: Downloading JSON metadata
[download] Downloading playlist: DL
[soundcloud:set] playlist DL: Collected 17 video ids (downloading 17 of them)
[download] Downloading video 1 of 17
[soundcloud] torylanez/diamonds: Resolving id
[soundcloud] torylanez/diamonds: Downloading info JSON
[soundcloud] 278720618: Downloading track url
[soundcloud] 278720618: Checking fallback video format URL
[soundcloud] 278720618: fallback video format URL is invalid, skipping
[soundcloud] 278720618: Checking http_mp3_128_url video format URL
[soundcloud] 278720618: Downloading thumbnail ...
[soundcloud] 278720618: Writing thumbnail to: DIAMONDS (PROD. C-SICK) _ I TOLD YOU  - AUGUST 19.-278720618.jpg
[download] Destination: DIAMONDS (PROD. C-SICK) _ I TOLD YOU  - AUGUST 19.-278720618.mp3
[download] 100% of 2.73MiB in 00:00
[ffmpeg] Adding thumbnail to "DIAMONDS (PROD. C-SICK) _ I TOLD YOU  - AUGUST 19.-278720618.mp3"
ERROR: ffmpeg or avconv not found. Please install one.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Playlist: https://soundcloud.com/ghyppa-142353405

---

### Description of your *issue*, suggested solution and other information

how do i fix this error?

**Comment by dstftw** [comment]
>ERROR: ffmpeg or avconv not found. Please install one.
