### ISSUE TITLE
Receiving "could not find JS function 'gz' all the sudden (latest version 8/24.1)

### ISSUE THREAD

**Issue by CollinChaffin** [rg3/youtube-dl#10446]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.24.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.24.1
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

Just began receiving this error when downloading from Youtube:

[youtube] aaFNcJT4aQQ: Downloading webpage
[youtube] aaFNcJT4aQQ: Downloading video info webpage
[youtube] aaFNcJT4aQQ: Extracting video information
[youtube] aaFNcJT4aQQ: Downloading js player en_US-vflrza-6I
ERROR: Signature extraction failed: Traceback (most recent call last):
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\jsinterp.py", line 241, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'gz'; please report
this issue on https://yt-dl.org/bug . Make sure you are using the latest version
; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.
(caused by ExtractorError("Could not find JS function 'gz'; please report this
issue on https://yt-dl.org/bug . Make sure you are using the latest version; typ
e youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag
and include its complete output.",)); please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type youtube-dl -U to up
date. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by CollinChaffin** [comment]
Sorry here is an example of a youtube video generating this error using verbose switch:

D:\Downloads>youtube-dl -v "https://www.youtube.com/watch?v=aaFNcJT4aQQ"
[debug] System config: []
[debug] User config: ['--continue', '--ignore-errors', '--no-overwrites', '-f',
'best', '--output', '%(playlist_index)s_%(upload_date)s_%(height)sP_%(title)s.%(
ext)s']
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=aaFNcJT4aQQ']

[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.14
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-80256-g0a9e781, ffprobe N-80256-g0a9e781
[debug] Proxy map: {}
[youtube] aaFNcJT4aQQ: Downloading webpage
[youtube] aaFNcJT4aQQ: Downloading video info webpage
[youtube] aaFNcJT4aQQ: Extracting video information
[youtube] {22} signature length 40.43, html5 player en_US-vflrza-6I
[youtube] aaFNcJT4aQQ: Downloading player https://s.ytimg.com/yts/jsbin/player-e
n_US-vflrza-6I/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\jsinterp.py", line 241, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'gz'; please report
this issue on https://yt-dl.org/bug . Make sure you are using the latest version
; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'gz'; please report this
issue on https://yt-dl.org/bug . Make sure you are using the latest version; typ
e  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag
and include its complete output.",)); please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type  youtube-dl -U  to up
date. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\jsinterp.py", line 241, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'gz'; please report
this issue on https://yt-dl.org/bug . Make sure you are using the latest version
; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\jsinterp.py", line 241, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'gz'; please report
this issue on https://yt-dl.org/bug . Make sure you are using the latest version
; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\common.py", line 342, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 1570, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 1007, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most re
cent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\jsinterp.py", line 241, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'gz'; please report
this issue on https://yt-dl.org/bug . Make sure you are using the latest version
; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'gz'; please report this
issue on https://yt-dl.org/bug . Make sure you are using the latest version; typ
e  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag
and include its complete output.",)); please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type  youtube-dl -U  to up
date. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by CollinChaffin** [comment]
Just ran this:

C:\Data\Scripts\Sync\Scripts>youtube-dl -U
youtube-dl is up-to-date (2016.08.24.1)

Is there a newer version?  Why is the update command not finding something newer than 8.24.1?

**Comment by dstftw** [comment]
>[debug] youtube-dl version 2016.06.14

**Comment by CollinChaffin** [comment]
Yep, so sorry in this folder had prior issue and forgot I had manually downloaded another older version to test some time ago and not deleted it.  <user error> :)

Sorry go ahead and close this issue!
