### ISSUE TITLE
Thisav add HTML5 video

### ISSUE THREAD

**Issue by mogu1121** [rg3/youtube-dl#10447]
E:\youtube-dl --verbose http://www.thisav.com/video/239069/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.thisav.com/video/239069/']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.08.24.1
[debug] Python version 3.4.4 - Windows-10-10.0.10240
[debug] exe versions: ffmpeg N-79068-g6b7ce0e, ffprobe N-79068-g6b7ce0e, rtmpdump 2.4
[debug] Proxy map: {}
[ThisAV] 239069: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvarrvgfb\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvarrvgfb\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvarrvgfb\build\youtube_dl\extractor\thisav.py", line 31, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvarrvgfb\build\youtube_dl\extractor\common.py", line 659, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvarrvgfb\build\youtube_dl\extractor\common.py", line 650, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

-----------------------------------------------------------------------------

<script type="text/javascript">
	jwplayer("myElement").setup ({
	file: "http://vs27.thisav.com/dl/LhnmL2eROWXAwicvRQcYrQ,1472219320/239069.mp4",       
	startparam: "start",
	width: 640,
	height: 360,
	});
</script>

**Comment by yan12125** [comment]
I got no videos. Can you watch it?

**Comment by uosen123** [comment]
Thank you for a good app.

Now, ThisAV has two kinds of video source.
The first is supported by youtube-dl. eg. http://www.thisav.com/video/29670/123123.html
In this case,  youtube-dl searches "so.addVariable('file" of html source.

But, the second is't. eg. http://www.thisav.com/video/242352/nerdy-18yo-big-ass-tattoos-and-glasses.html
In this case, youtube-dl have to search ""<script type="text/javascript">
            jwplayer("myElement").setup ({
        file: "". Of course, only  "       file: "", OK.

ThisAV often is busy. Then, we can't watch a video.

I am looking forward to your work.

**Comment by uosen123** [comment]
jwplayer("myElement").setup ({
        file: "". Of course, only  "       file: "", OK.

ThisAV often is busy. Then, we can't watch a video.

I am looking forward to your work.

**Comment by yan12125** [comment]
Thanks for the report. HTML5 videos will be recognized in the next version.
