### ISSUE TITLE
[THVideo] Remove exctractor

### ISSUE THREAD

**Issue by stepshal** [rg3/youtube-dl#10464]
http://thvideo.tv
Site closed:
https://www.reddit.com/r/touhou/comments/4wed3j/rip_thvideotv/

**Comment by yan12125** [comment]
According to a screenshot at http://tieba.baidu.com/p/4691302183, thvideo is "temporarily" shut down. However, I see no clues for the site to be up again, so I removed its support.

/cc @diffycat, if you find thvideo is up again, feel free to open a new issue or pull request.
