### ISSUE TITLE
Unable to download webpage

### ISSUE THREAD

**Issue by MingYANGpy** [rg3/youtube-dl#10463]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.08.28_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.28**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---

Unable to download the videos. Please help! Thank you.
Code as below:
PS F:\python\Scripts> .\youtube-dl -f 18 https://www.youtube.com/watch?v=RLpsIuh
Tb8k
[youtube] RLpsIuhTb8k: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 10060] > (caused by URL
Error(error(10060, ''),))
PS F:\python\Scripts>

**Comment by yan12125** [comment]
Post the output of ```.\youtube-dl -v -f 18 https://www.youtube.com/watch?v=RLpsIuhTb8k```.

Before more information, this looks like a network issue. Can you watch this video in browsers without any proxy/VPN? Other previous reports indicate particular antivirus or firewall softwares are blocking youtube-dl. Could you try again with turning them off?
