### ISSUE TITLE
[MyVidster] Change test url

### ISSUE THREAD

**Issue by stepshal** [rg3/youtube-dl#10473]
Current not working.
http://www.myvidster.com/video/73284291/Kill_Or_Be_Killed_Season_3_EMPIRE

**Comment by yan12125** [comment]
Hi @stepshal would you like to open pull requests?

**Comment by stepshal** [comment]
@yan12125 If i known how to retrieve metadata.

**Comment by yan12125** [comment]
http://www.myvidster.com/video/73284291/Kill_Or_Be_Killed_Season_3_EMPIRE uses YouTube player and can be recognized by ```GenericIE```. Is there an example not using YouTube? If not I'm going to remove ```MyVidsterIE```.

**Comment by remitamine** [comment]
http://www.myvidster.com/video/73438293/CNN_Student_News_-_082916 uses cnn and it also work using `GenericIE`.

**Comment by yan12125** [comment]
Actually http://www.myvidster.com/video/73284291/Kill_Or_Be_Killed_Season_3_EMPIRE is still working. The failed test is updated.
