### ISSUE TITLE
Add audio sample rate

### ISSUE THREAD

**Issue by davidhedlund** [rg3/youtube-dl#10487]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.28**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Feature request (request for a new functionality)

### Description of your *issue*, suggested solution and other information
Audio bitrate (--audio-quality 128K) can be set but not audio sample rate.

It should be possible to select both audio bitrate and audio sample rate at the same time.

sox require identical audio sample rates to merge files with
>sox track1.ogg track2.ogg merged.ogg

or I it give this error message
>sox FAIL sox: Input files must have the same sample-rate

**Comment by yan12125** [comment]
Please paste an example URL and the command you use to download these files.

**Comment by davidhedlund** [comment]
@yan12125
>youtube-dl --extract-audio --audio-format vorbis --audio-quality 128K Y6ihmqRahKg

**Comment by yan12125** [comment]
Use format selection: ```-f 'bestaudio[asr=44100]'```. Here "asr" is abbreviation of audio sample rate.

By the way, ```--audio-quality``` is used in re-encoding, not for selection.

**Comment by davidhedlund** [comment]
@yan12125 Thank you.
