### ISSUE TITLE
Unable to download channel with /channel/ username

### ISSUE THREAD

**Issue by jamestopkek** [rg3/youtube-dl#10494]
Hello, i'm using ver 2016.08.28
if i try (say a channel)
/channel/UOxVOo9zs8EN5tte_qoeE_Ic0
(^just an example, not a real channel)
ytuser:UOxVOo9zs8EN5tte_qoeE_Ic0
i get a:

[youtube:user] UOxVOo9zs8EN5tte_qoeE_Ic0: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] UOxVOo9zs8EN5tte_qoeE_Ic0: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; see  https://yt-dl.org/update  on how to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 394,
 in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1998, in ur
lopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Thank you! :)

**Comment by phihag** [comment]
The YouTube user UOxVOo9zs8EN5tte_qoeE_Ic0 does not exist, therefore an error is the correct behavior here. If there is a real URL you're having problems with, please post the **complete** output you get with that when called with `-v`, either in this issue or a new one.

**Comment by jamestopkek** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'ytuser:UCsqjHFMB_JYTaEnf_vmTNqg']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.28
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81489-ga37e6dd, ffprobe N-81489-ga37e6dd
[debug] Proxy map: {}
[youtube:user] UCsqjHFMB_JYTaEnf_vmTNqg: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] UCsqjHFMB_JYTaEnf_vmTNqg: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; see  https://yt-dl.org/update  on how to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 394,
 in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1998, in ur
lopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Here is a real channel, sorry about the OP, i should've known.
