### ISSUE TITLE
[youtube live] Failed to open segment of playlist 0 

### ISSUE THREAD

**Issue by 9191521** [rg3/youtube-dl#10490]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.28*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.28**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

E:\Program Files\Downloader\代理>360

E:\Program Files\Downloader\代理>youtube-dl.exe --verbose --proxy socks5://127.0
.0.1:1012 --geo-verification-proxy socks5://127.0.0.1:8088 --all-subs --embed-su
bs --limit-rate 1.2M -f "[height<=? 480]" "https://www.youtube.com/watch?v=y60wD
zZt8yg"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--proxy', 'socks5://127.0.0.1:1012', '
--geo-verification-proxy', 'socks5://127.0.0.1:8088', '--all-subs', '--embed-sub
s', '--limit-rate', '1.2M', '-f', '[height<=? 480]', 'https://www.youtube.com/wa
tch?v=y60wDzZt8yg']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.08.28
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81470-gc752733, rtmpdump 2.3
[debug] Proxy map: {'http': 'socks5://127.0.0.1:1012', 'https': 'socks5://127.0.
0.1:1012'}
[youtube] y60wDzZt8yg: Downloading webpage
[youtube] y60wDzZt8yg: Downloading video info webpage
[youtube] y60wDzZt8yg: Extracting video information
WARNING: video doesn't have subtitles
[youtube] y60wDzZt8yg: Downloading formats manifest
[youtube] y60wDzZt8yg: Downloading MPD manifest
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/hl
s_playlist/id/y60wDzZt8yg.4/itag/94/source/yt_live_broadcast/requiressl/yes/rate
bypass/yes/live/1/cmbypass/yes/goi/160/sgoap/itag%3D140/sgovp/itag%3D135/hls_chu
nk_host/r4---sn-ogueln7y.googlevideo.com/gcr/jp/playlist_type/DVR/mm/32/mn/sn-og
ueln7y/ms/lv/mv/u/nh/IgpwcjAzLm5ydDE5Kg4xMTcuMTAzLjE3Ny4xNw/pl/26/dover/3/sver/3
/upn/6iq7ecnXYa8/mt/1472465806/ip/104.238.151.50/ipbits/0/expire/1472488132/spar
ams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoa
p,sgovp,hls_chunk_host,gcr,playlist_type,mm,mn,ms,mv,nh,pl/signature/07D98E4C75F
CC2D95C214816FEEE0E242AC5AC26.85536492B41C15F506EADA6D407D2DF600A7DE7B/key/dg_yt
0/playlist/index.m3u8'
[download] Destination: Sky News Live-y60wDzZt8yg.mp4
WARNING: ffmpeg does not support SOCKS proxies. Downloading may fail.
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Charset: ISO-8859-1,utf-
8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0
 (Chrome)
' -i https://manifest.googlevideo.com/api/manifest/hls_playlist/id/y60wDzZt8yg.4
/itag/94/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/
yes/goi/160/sgoap/itag%3D140/sgovp/itag%3D135/hls_chunk_host/r4---sn-ogueln7y.go
oglevideo.com/gcr/jp/playlist_type/DVR/mm/32/mn/sn-ogueln7y/ms/lv/mv/u/nh/Igpwcj
AzLm5ydDE5Kg4xMTcuMTAzLjE3Ny4xNw/pl/26/dover/3/sver/3/upn/6iq7ecnXYa8/mt/1472465
806/ip/104.238.151.50/ipbits/0/expire/1472488132/sparams/ip,ipbits,expire,id,ita
g,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,gcr,
playlist_type,mm,mn,ms,mv,nh,pl/signature/07D98E4C75FCC2D95C214816FEEE0E242AC5AC
26.85536492B41C15F506EADA6D407D2DF600A7DE7B/key/dg_yt0/playlist/index.m3u8 -c co
py -f mp4 -bsf:a aac_adtstoasc 'file:Sky News Live-y60wDzZt8yg.mp4.part'
ffmpeg version N-81470-gc752733 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dx
va2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-lib
ebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --ena
ble-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfree
type --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enab
le-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-lib
openh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschr
oedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheor
a --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvo
rbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --ena
ble-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --e
nable-decklink --enable-zlib
  libavutil      55. 29.100 / 55. 29.100
  libavcodec     57. 54.100 / 57. 54.100
  libavformat    57. 48.100 / 57. 48.100
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 57.100 /  6. 57.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
[hls,applehttp @ 02fc9080] Failed to open segment of playlist 0
    Last message repeated 3 times

**Comment by yan12125** [comment]
Here's a warning:

> WARNING: ffmpeg does not support SOCKS proxies. Downloading may fail.

Actually it's almost definite that downloading with ffmpeg fails. Could you try with ```--hls-prefer-native```?

**Comment by 9191521** [comment]
thx
