### ISSUE TITLE
[RTE.ie] failing to download

### ISSUE THREAD

**Issue by schwindp** [rg3/youtube-dl#10498]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.28**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
/usr/local/bin/youtube-dl --verbose "http://www.rte.ie/player/at/show/keeping-ireland-alive-the-health-service-in-a-day-30004189/10616459/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.rte.ie/player/at/show/keeping-ireland-alive-the-health-service-in-a-day-30004189/10616459/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.28
[debug] Python version 2.7.11 - Linux-4.6.7-200.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
[debug] exe versions: none
[debug] Proxy map: {}
[rte] 10616459: Downloading webpage
[rte] 10616459: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 433, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 423, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1788, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rte.py", line 55, in _real_extract
IndexError: list index out of range
```

---
### Description of your _issue_, suggested solution and other information

youtube-dl fails downloading from RTE.ie, though this should work and there have been resolved bugs during the last weeks/months.

**Comment by txt3rob** [comment]
RTE streams are DRM now so this might not work
