### ISSUE TITLE
[Facebook] Extractor not including upload date in metadata

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#10508]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.31*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.31**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.31
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

Extraction 

``` youtube-dl https://www.facebook.com/georgehtakei/videos/1661660187196761/ ```

This gives me the JSON of:

```
{"playlist_index": null, "extractor": "facebook", "display_id": "1661660187196761", "url": "https://scontent-amt2-1.xx.fbcdn.net/v/t42.9040-29/10000000_1098138380251811_2099266616_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InYzXzQyNl9jcmZfMjNfbWFpbl8zLjBfc2QifQ%3D%3D&oh=fac168537d554c27df7bbeeaa086d134&oe=57C6D251", "uploader": null, "formats": [{"http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)"}, "url": "https://scontent-amt2-1.xx.fbcdn.net/v/t42.9040-29/10000000_1098138380251811_2099266616_n.mp4?efg=eyJybHIiOjc1NiwicmxhIjo0MDk2LCJ2ZW5jb2RlX3RhZyI6InYzXzQyNl9jcmZfMjNfbWFpbl8zLjBfc2QifQ%3D%3D&rl=756&vabr=420&oh=fac168537d554c27df7bbeeaa086d134&oe=57C6D251", "format_id": "progressive_sd_src", "ext": "mp4", "protocol": "https", "format": "progressive_sd_src - unknown", "preference": -10}, {"http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)"}, "url": "https://scontent-amt2-1.xx.fbcdn.net/v/t42.9040-29/10000000_1098138380251811_2099266616_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InYzXzQyNl9jcmZfMjNfbWFpbl8zLjBfc2QifQ%3D%3D&oh=fac168537d554c27df7bbeeaa086d134&oe=57C6D251", "format_id": "progressive_sd_src_no_ratelimit", "ext": "mp4", "protocol": "https", "format": "progressive_sd_src_no_ratelimit - unknown", "preference": -10}], "playlist": null, "webpage_url_basename": "1661660187196761", "webpage_url": "https://www.facebook.com/georgehtakei/videos/1661660187196761/", "http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)"}, "id": "1661660187196761", "fulltitle": "Facebook video #1661660187196761", "preference": -10, "protocol": "https", "ext": "mp4", "_filename": "Facebook video #1661660187196761-1661660187196761.mp4", "title": "Facebook video #1661660187196761", "extractor_key": "Facebook", "format": "progressive_sd_src_no_ratelimit - unknown", "format_id": "progressive_sd_src_no_ratelimit"}
```

But theres no upload date. This causes a script I'm using that relies on it for archival to choke. Normally I'd adapt around it but given that every other extractor pulls the date I figured I'd report this.

**Comment by dstftw** [comment]
>every other extractor pulls the date

That's incorrect.

**Comment by vxbinaca** [comment]
@dstftw apologies and thanks for the bug fix
