### ISSUE TITLE
CBS not getting the Highest Bitrate (4400K)

### ISSUE THREAD

**Issue by qwerty480** [rg3/youtube-dl#10515]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.31*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
```
youtube-d
l -F -v "http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/6IU_R
58_HFgD3iAKPvMdfnPK0KIfkPES/the-late-show-8-30-2016-john-krasinski-adam-brody-st
-paul-and-the-broken-bones-/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', '-v', 'http://www.cbs.com/shows/the-late-show-
with-stephen-colbert/video/6IU_R58_HFgD3iAKPvMdfnPK0KIfkPES/the-late-show-8-30-2
016-john-krasinski-adam-brody-st-paul-and-the-broken-bones-/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.31
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81400-g15dd56c, ffprobe N-81400-g15dd56c
[debug] Proxy map: {}
[CBS] 6IU_R58_HFgD3iAKPvMdfnPK0KIfkPES: Downloading SMIL data
[CBS] 6IU_R58_HFgD3iAKPvMdfnPK0KIfkPES: Downloading m3u8 information
[CBS] 6IU_R58_HFgD3iAKPvMdfnPK0KIfkPES: Downloading HLS SMIL data
[CBS] 6IU_R58_HFgD3iAKPvMdfnPK0KIfkPES: Downloading RTMP SMIL data
[CBS] 6IU_R58_HFgD3iAKPvMdfnPK0KIfkPES: Downloading WIFI SMIL data
[CBS] 6IU_R58_HFgD3iAKPvMdfnPK0KIfkPES: Downloading 3G SMIL data
[CBS] 6IU_R58_HFgD3iAKPvMdfnPK0KIfkPES: Downloading JSON metadata
[info] Available formats for 6IU_R58_HFgD3iAKPvMdfnPK0KIfkPES:
format code  extension  resolution note
hls-meta     mp4        multiple   Quality selection URL
hls-58       mp4        audio only   58k , mp4a.40.2
hls-187      mp4        400x224     187k , avc1.66.30, mp4a.40.2
hls-332      mp4        400x224     332k , avc1.66.30, mp4a.40.2
rtmp-364     flv        384x216     364k
rtmp-496     flv        640x360     496k
hls-582      mp4        512x288     582k , avc1.66.30, mp4a.40.2
rtmp-796     flv        640x360     796k
hls-899      mp4        640x360     899k , avc1.66.30, mp4a.40.2
rtmp-1296    flv        640x360    1296k
hls-1334     mp4        768x432    1334k , avc1.77.30, mp4a.40.2
rtmp-1928    flv        848x480    1928k
hls-1969     mp4        960x540    1969k , avc1.77.30, mp4a.40.2
hls-2759     mp4        1024x576   2759k , avc1.77.30, mp4a.40.2
hls-3816     mp4        1280x720   3816k , avc1.77.30, mp4a.40.2 (best)
...
<end of log>
```

I was once able to download from CBS at 4400k. For example, if I wanted to download the latest “The Late Show with Stephen Colbert”, I would get the highest option as 
“hls-4400     mp4        1280x720   4400k , mp4a.40.2, avc1.640028”
As evident in the output given here [9932](https://github.com/rg3/youtube-dl/issues/9932).

A bug occurred in youtube-dl in which CBS was not working and was fixed in 
 [10393](https://github.com/rg3/youtube-dl/issues/10393) 

However, after the fix, I am not able to get the 4400k bit-rate for any video. 
It appears that the highest bit-rate (3798k) is being downloaded  from the address
http://cbsios-vh.akamaihd.net. I remember that when I was getting the 4400k  stream, it was coming from unicornmedia.com. I remember the links looked like the ones in these comments [8893#issuecomment-198378951](https://github.com/rg3/youtube-dl/issues/8893#issuecomment-198378951), though I don't know if they are exclusive to Android devices.

Thank you for your help.

**Comment by yan12125** [comment]
Ping @remitamine

**Comment by remitamine** [comment]
Once formats was not working at the time of fixing the extraction, i guess it was a temporary error.
