### ISSUE TITLE
[PORN.COM] Request to include categories/tags to extractor

### ISSUE THREAD

**Issue by razor1907** [rg3/youtube-dl#10510]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.31*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.porn.com/videos/cutie-with-short-hair-shows-off-her-goodies-1903149']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.31
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.porn.com/videos/cutie-with-short-hair-shows-off-her-goodies-1903149

### Description of your *issue*, suggested solution and other information
Metadata like "categories" and "tags" are not included when downloading videos from porn.com

This is most likely to be solved if `'categories': list,` or `'tags': list,` will be added to current extractor command.

**Comment by razor1907** [comment]
Thank you. Is there a way I can donate a small amount for your effort? 


-------- Oorspronkelijk bericht --------
Van: "Sergey M." <notifications@github.com> 
Datum: 31-08-16  17:25  (GMT+01:00) 
Aan: rg3/youtube-dl <youtube-dl@noreply.github.com> 
Cc: razor1907 <webmaster@youramateurporn.com>, Author <author@noreply.github.com> 
Onderwerp: Re: [rg3/youtube-dl] [PORN.COM] Request to include categories/tags to
  extractor (#10510) 

Closed #10510 via 7a3e849.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rg3/youtube-dl","title":"rg3/youtube-dl","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rg3/youtube-dl"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #10510 via 7a3e849f6eaf51b1d86b843a63664012ced2258c."}],"action":{"name":"View Issue","url":"https://github.com/rg3/youtube-dl/issues/10510#event-773824157"}}}

**Comment by dstftw** [comment]
You can donate to youtube-dl project here: https://rg3.github.io/youtube-dl/donations.html.
