### ISSUE TITLE
Site Support Request for truTV.com

### ISSUE THREAD

**Issue by jdunn0** [rg3/youtube-dl#10519]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.31*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://www.trutv.com/shows/adam-ruins-everything/videos/why-you-dont-need-eight-glasses-of-water-a-day.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.trutv.com/shows/adam-ruins-everything/videos/why-you-dont-need-eight-glasses-of-water-a-day.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.31-gentoo_no_offensive_sites
[debug] Python version 2.7.10 - Linux-4.4.6-gentoo-x86_64-Intel-R-_Core-TM-_i7_CPU_920_@_2.67GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] why-you-dont-need-eight-glasses-of-water-a-day: Requesting header
WARNING: Falling back on generic information extractor.
[generic] why-you-dont-need-eight-glasses-of-water-a-day: Downloading webpage
[generic] why-you-dont-need-eight-glasses-of-water-a-day: Extracting information
ERROR: Unsupported URL: http://www.trutv.com/shows/adam-ruins-everything/videos/why-you-dont-need-eight-glasses-of-water-a-day.html
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- No Authentication Needed video: http://www.trutv.com/shows/adam-ruins-everything/videos/why-you-dont-need-eight-glasses-of-water-a-day.html
- TV Provider Authentication Required Video: http://www.trutv.com/full-episodes/adam-ruins-everything/2084661/index.html

---

### Description of your *issue*, suggested solution and other information
I would like support for truTV.com videos.
Some of the videos require TV Provider Authentication and some don't require it.

**Comment by yan12125** [comment]
@dstftw Seems it's a wrong label?

**Comment by Transcodes** [comment]
if 'jdunn0 ' what provided is not enough,
please use the following links

"site support request please provide all kinds of example URLs support for which should be included (replace following example URLs by yours):

may require TV login
see if it can be bypassed

All
http://www.trutv.com/full-episodes/index.html

shows list
http://www.trutv.com/full-episodes/adam-ruins-everything/index.html

http://www.trutv.com/full-episodes/the-carbonaro-effect/index.html

http://www.trutv.com/full-episodes/those-who-cant/index.html

http://www.trutv.com/full-episodes/hack-my-life/index.html

http://www.trutv.com/full-episodes/billy-on-the-street/index.html

show playlist
http://www.trutv.com/full-episodes/impractical-jokers/index.html

playslit episodes
http://www.trutv.com/full-episodes/impractical-jokers/2075772/index.html
http://www.trutv.com/full-episodes/impractical-jokers/2075772/index.html
http://www.trutv.com/full-episodes/impractical-jokers/2084634/index.html
http://www.trutv.com/full-episodes/impractical-jokers/2084634/index.html
http://www.trutv.com/full-episodes/impractical-jokers/2084633/index.html
http://www.trutv.com/full-episodes/impractical-jokers/2084633/index.html
http://www.trutv.com/full-episodes/impractical-jokers/2084632/index.html
http://www.trutv.com/full-episodes/impractical-jokers/2084632/index.html
http://www.trutv.com/full-episodes/impractical-jokers/2084631/index.html
http://www.trutv.com/full-episodes/impractical-jokers/2084631/index.html
http://www.trutv.com/full-episodes/impractical-jokers/2084630/index.html
http://www.trutv.com/full-episodes/impractical-jokers/2084630/index.html
http://www.trutv.com/full-episodes/impractical-jokers/2084629/index.html
http://www.trutv.com/full-episodes/impractical-jokers/2084629/index.html


thank you

**Comment by jdunn0** [comment]
It might be worth noting that truTV is owned by "Turner Entertainment Networks" so an extractor for it maybe similar to the ones for other Turner Networks like TBS and Cartoon Network.
