### ISSUE TITLE
TV Noe (Czech Christian TV)

### ISSUE THREAD

**Issue by mcepl** [rg3/youtube-dl#10520]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.31**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
matej@mitmanek: ~$ youtube-dl -v --xattrs 'http://www.tvnoe.cz/video/10362'
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'-v', u'--xattrs', u'http://www.tvnoe.cz/video/10362']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.31
[debug] Python version 2.7.5 - Linux-3.10.0-498.el7.x86_64-x86_64-with-redhat-7.3-Maipo
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 10362: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 10362: Downloading webpage
[generic] 10362: Extracting information
ERROR: Unsupported URL: http://www.tvnoe.cz/video/10362
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1644, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/lib/python2.7/site-packages/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/lib/python2.7/site-packages/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: junk after document element: line 51, column 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2388, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.tvnoe.cz/video/10362
...
<end of log>
```
- Single video: http://www.tvnoe.cz/video/10362
---

Plain MP4 file can be downloaded at http://video.tvnoe.cz/media/b85614af1b14e3b9c272361f87f1b301/57c7fb31/nunxb/nunxb0130.404p.mp4

**Comment by mcepl** [comment]
Apparently, when the correct iframe is found, then ``youtube-dl 'http://video.tvnoe.cz/getVideo.php?code=bnVzbjEwYjAxMzA='`` works with a generic extractor.

**Comment by MyloshB** [comment]
Hi devs, I want to inform you that extractor for TV Noe does not work in "fresh" version 2002.02.16.
Could you, please, fix this bug?
Thanks in advance, Mylosh B.

The error messages are these:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', '--verbose', '--no-overwrites', '--restrict-filenames', '--output', 'D:\\Temp\\%(title)s_%(autonumber)s.%(ext)s', '--batch-file', 'C:\\Program Files (x86)\\YouTube-DL\\youtube-dl.lst']
[debug] Batch file urls: ['http://www.tvnoe.cz/porad/26669-mse-svata-z-kostela-nanebevzeti-panny-marie-slapanice']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[generic] 26669-mse-svata-z-kostela-nanebevzeti-panny-marie-slapanice: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 26669-mse-svata-z-kostela-nanebevzeti-panny-marie-slapanice: Downloading webpage
[generic] 26669-mse-svata-z-kostela-nanebevzeti-panny-marie-slapanice: Extracting information
ERROR: Unsupported URL: http://www.tvnoe.cz/porad/26669-mse-svata-z-kostela-nanebevzeti-panny-marie-slapanice
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\generic.py", line 3350, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.tvnoe.cz/porad/26669-mse-svata-z-kostela-nanebevzeti-panny-marie-slapanice

**Comment by mcepl** [comment]
Hmm, ``youtube-dl https://noe-vod-prep-sec.ssl.cdn.cra.cz/kbeGvhH0DNhXTlizEGqzoA==,1582402326/vod_Noe/_definst_/0055/7022/cze-ao-sd1-sd2-sd3-sd4-hd1-hd2-tNDoeHA7.smil/manifest.mpd`` works, but I wonder how to get from there to here.
