### ISSUE TITLE
bravotv:  HTTP Error 400 (on some videos)

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#10527]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.31*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.31**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
E:\>c:\support\youtube-dl.exe --netrc --verbose "http://www.bravotv.com/flipping-out/season-9/ep-7-i-know-what-you-did-last-saturday"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--netrc', '--verbose', 'http://www.bravotv.com/flipping-out/season-9/ep-7-i-know-what-you-did-last-saturday']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.31
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[BravoTV] ep-7-i-know-what-you-did-last-saturday: Downloading webpage
[BravoTV] OIqX_ver0PdU: Retrieving Media Token
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\build\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\build\youtube_dl\YoutubeDL.py", line 1998, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video (NOT working): http://www.bravotv.com/flipping-out/season-9/ep-7-i-know-what-you-did-last-saturday
- Single video (NOT working): http://www.bravotv.com/below-deck-mediterranean/season-1/ep-1-its-all-greek-to-me
- Single video (working): http://www.bravotv.com/watch-what-happens-live/season-13/hugh-grant-simon-helberg

---

### Description of your *issue*, suggested solution and other information

HTTP Error 400, but only on some videos.

I have my DirecTV credentials in the .netrc file.

**Comment by remitamine** [comment]
try to check in the next version if these videos work again, if not then i will need more information.

**Comment by StevenDTX** [comment]
Will do. Thanks.

**Comment by StevenDTX** [comment]
Thanks, @remitamine.  It's working again.
