### ISSUE TITLE
CBC Radio link error - "An extractor error has occurred. (caused by KeyError(u'clipId',))"

### ISSUE THREAD

**Issue by jenningsthecat** [rg3/youtube-dl#10539]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.31*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
user@ComputerName:~$ youtube-dl --verbose http://www.cbc.ca/radio/popup/audio/listen.html?autoPlay=true&clipIds=&mediaIds=2687122049&contentarea=radio&subsection1=radio1&subsection2=currentaffairs&subsection3=the_current&contenttype=audio&title=2016/04/19/1.3542277-the-current-for-april-19-2016&contentid=1.3542277
[1] 8428
[2] 8429
[3] 8430
[4] 8431
[5] 8432
[6] 8433
[7] 8434
[8] 8435
[9] 8436
[2]   Done                    clipIds=
[3]   Done                    mediaIds=2687122049
[6]   Done                    subsection2=currentaffairs
user@ComputerName:~$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.cbc.ca/radio/popup/audio/listen.html?autoPlay=true']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.31
[debug] Python version 2.7.6 - Linux-3.13.0-95-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[cbc.ca] listen.html: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'clipId',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cbc.py", line 109, in _real_extract
    clip_id = player_info['clipId']
KeyError: u'clipId'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 353, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'clipId',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

^C
[1]   Exit 1                  youtube-dl --verbose http://www.cbc.ca/radio/popup/audio/listen.html?autoPlay=true
[4]   Done                    contentarea=radio
[5]   Done                    subsection1=radio1
[7]   Done                    subsection3=the_current
[8]-  Done                    contenttype=audio
[9]+  Done                    title=2016/04/19/1.3542277-the-current-for-april-19-2016

<end of log>
```
---
---

### Description of your *issue*, suggested solution and other information

When I attempt to download the audio content at  "http://www.cbc.ca/radio/popup/audio/listen.html?autoPlay=true&clipIds=&mediaIds=2687122049&contentarea=radio&subsection1=radio1&subsection2=currentaffairs&subsection3=the_current&contenttype=audio&title=2016/04/19/1.3542277-the-current-for-april-19-2016&contentid=1.3542277", I receive the error shown in the log above. I found other CBC issues in earlier bug reports, but none of them looked to be the same as the error I'm seeing here.

The URL works in my browser, which is Pale Moon version 26.2.2.  I have looked at the page source code and can't find any other media-containing URL on which to attempt a download. The video player that shows up in the page does not load in a separate frame, so as far as I can tell the page source I looked at is the only source available.

The source of the URL above is the "Listen to Full Episode" link from the following URL:
http://www.cbc.ca/radio/thecurrent/the-current-for-april-20-2016-1.3544290

Thanks!

**Comment by dstftw** [comment]
You have to either put the URL into quotes or manually escape all the special shell characters. Read [FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for details.

**Comment by jenningsthecat** [comment]
Thank you very much!
--------------------------------------------
On Fri, 9/2/16, Sergey M. <notifications@github.com> wrote:

 Subject: Re: [rg3/youtube-dl] CBC Radio link error - "An extractor error has occurred. (caused by KeyError(u'clipId',))" (#10539)
 To: "rg3/youtube-dl" <youtube-dl@noreply.github.com>
 Cc: "jenningsthecat" <jenningsthecat@yahoo.ca>, "Author" <author@noreply.github.com>
 Received: Friday, September 2, 2016, 3:24 PM
 
 You have to either put the URL
 into quotes or manually escape all the special shell
 characters. Read FAQ
 entry for details.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
