### ISSUE TITLE
Detected as Malware (BrowserModifier: Win32/Zwangi) by Windows Defender

### ISSUE THREAD

**Issue by zmni** [rg3/youtube-dl#10534]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.31*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### Description of your *issue*, suggested solution and other information

Download from [this url](https://yt-dl.org/latest/youtube-dl.exe) and [this url](https://yt-dl.org/downloads/2016.08.31/youtube-dl.exe), both detected as malware (BrowserModifier: Win32/Zwangi) by Windows Defender on WIndows 8.1 and 10.

Screenshot from 8.1
![ytdl](https://cloud.githubusercontent.com/assets/841523/18201392/0ea00e56-7134-11e6-923e-e92afe393a80.jpg)

**Comment by yan12125** [comment]
Maybe your file is polluted. Check the SHA256 sum and signature listed at https://rg3.github.io/youtube-dl/download.html. If all checksums match, report it to Microsoft.

**Comment by phihag** [comment]
Can you post the file and/or its hashes somewhere?

Here is the virustotal.com scan of the current youtube-dl.exe (SHA256 191c7e8e046f1ab70ff4f761324f695f0c669b1e34a7c9ea9f941d8319e3236c): https://virustotal.com/en/file/191c7e8e046f1ab70ff4f761324f695f0c669b1e34a7c9ea9f941d8319e3236c/analysis/1472758968/

**Comment by zmni** [comment]
I can't even download the file, it get blocked by defender in an instant. Ok, I'll disable defender temporarily, I'll double check the sha and signature. Thanks for the reply.
