### ISSUE TITLE
vimeo download url not working: racing4everyone.eu

### ISSUE THREAD

**Issue by petgithub** [rg3/youtube-dl#10533]
I cannot download vimeo url https://player.vimeo.com/video/180633686
its says it not the embedded url 
it is a private video of a formula 1 race from 
http://racing4everyone.eu/2016/07/30/formula-1-2016-round12-germany/

I used to be able to download from this site....but not anymore
Can u please check thanks

**Comment by dstftw** [comment]
It's not possible to download or watch with direct URL since they require passing Referer header, Use original URL http://racing4everyone.eu/2016/07/30/formula-1-2016-round12-germany/.
