### ISSUE TITLE
ERROR: <video-id>: YouTube said: This video has been removed by the user. program halts

### ISSUE THREAD

**Issue by msj2** [rg3/youtube-dl#10545]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.03**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*
1) Passing list of youtube URL's in a file, invoking youtube-dl -a <filename>
2) One URL fails with ERROR: <video-id>: YouTube said: This video has been removed by the user. **program halts.**
3) I expect youtube-dl to proceed to next url in the file, but it won't. It halts after the above error.
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -v -a 3
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-a', u'3']
[debug] Batch file urls: [u'https://www.youtube.com/watch?v=<video-id>', u'https://www.youtube.com/watch?v=<video-id no. 2>']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.03
[debug] Python version 2.7.6 - Linux-3.13.0-93-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] <video-id>: Downloading webpage
[youtube] <video-id>: Downloading video info webpage
[youtube] <video-id>: Extracting video information
[youtube] <video-id>: Downloading MPD manifest
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Invoking downloader on u'https://r2---sn-5jucgv5qc5oq-cags.googlevideo.com/videoplayback?mime=video%2Fmp4&key=yt6&pl=24&initcwndbps=2117500&ipbits=0&ratebypass=yes&expire=1472951545&lmt=1471162428825977&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&source=youtube&upn=JSPvyeGELTk&sver=3&dur=60.162&id=o-AIy3M45nGrdeagmImy51PjI1qAv9IcClH2iy6pxrMj0H&mn=sn-5jucgv5qc5oq-cags&mm=31&signature=777000A35A87A9028316B6B4079A67CC7501861C.2AA3FFDFA56BD15DFFA3EBC4EFD698E8DBEC0818&ms=au&mv=m&mt=1472929278&ip=106.51.131.206&requiressl=yes&ei=mSDLV87vEdapogO35IiYDw&itag=22'
[download] <Video Description>-<video-id>.mp4 has already been downloaded
[download] 100% of 11.91MiB
[youtube] <video-id no. 2>: Downloading webpage
[youtube] <video-id no. 2>: Downloading video info webpage
ERROR: <video-id no. 2>: YouTube said: This video has been removed by the user.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1327, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: <video-id no. 2>: YouTube said: This video has been removed by the user.

<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

1) Passing list of youtube URL's in a file, invoking youtube-dl -a <filename>
2) One URL fails with ERROR: <video-id>: YouTube said: This video has been removed by the user. **program halts.**
3) I expect youtube-dl to proceed to next url in the file, but it won't. It halts after the above error.

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

1) Passing list of youtube URL's in a file, invoking youtube-dl -a <filename>
2) One URL fails with ERROR: <video-id>: YouTube said: This video has been removed by the user. **program halts.**
3) I expect youtube-dl to proceed to next url in the file, but it won't. It halts after the above error.

**Comment by dstftw** [comment]
Use `-i`.

**Comment by msj2** [comment]
Thank you for the swift reply. My mistake, that I didn't explore -i option.
