### ISSUE TITLE
vimeo.com: Support for embed-only videos

### ISSUE THREAD

**Issue by palashcode** [rg3/youtube-dl#10541]
$ youtube-dl -v -c -f http-360p https://player.vimeo.com/video/130333203
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-c', u'-f', u'http-360p', u'https://player.vimeo.com/video/130333203']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.03
[debug] Python version 2.7.10 - Linux-4.2.0-42-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 130333203: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 409, in _real_extract
    webpage = self._download_webpage(request, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 414, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 403, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 418, in _real_extract
    expected=True)
ExtractorError: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.

**Comment by yan12125** [comment]
Where did you find this URL?

**Comment by palashcode** [comment]
It's a private video from the course I purchased online.
page embedding video is http://eclassesbyravindra.com/mod/page/view.php?id=954
video url is http://player.vimeo.com/video/114434227

**Comment by palashcode** [comment]
problem started from 2016.08.31 before that it was downloading fine

**Comment by yan12125** [comment]
Try this:
```
$ youtube-dl -v "http://player.vimeo.com/video/114434227" --referer "http://eclassesbyravindra.com/mod/page/view.php?id=954"   
```

**Comment by palashcode** [comment]
works this way but how do I do it when downloading batch files like this
youtube-dl -v -c -f http-360p --batch-file=pointer

**Comment by yan12125** [comment]
Could you try:
```
youtube-dl -v -c -f http-360p --batch-file=pointer --referer "http://eclassesbyravindra.com/"
```

**Comment by palashcode** [comment]
it Works thanks a lot :+1:

**Comment by yan12125** [comment]
OK please move to #9735 for further discussions.

**Comment by vivekm7** [comment]
how to get Vimeo video URL? I'm not able to download please help bro?
