### ISSUE TITLE
youtube-dl is downloading multiple copies

### ISSUE THREAD

**Issue by scottbomb** [rg3/youtube-dl#10551]
Most recent version (dated today). Running Kubuntu 16.04.1. Bizarre behavior. Every time I start a download, the client starts it again - and again - and again... It appears to be infinite. After waiting several minutes with the download not making any apparent traction, I looked in my home folder and there were over a hundred copies downloading. CTRL-C doesn't kill it, either. It just re-spawns with a new download (of the same video). I have to close the terminal to make it quit.

My output:

scottbomb@main:~$ youtube-dl -v  https://www.youtube.com/watch?v=iXZV5uAYMJI&index=4&list=PLGeM09tlguZQyemL0Y5CdpEFrBs-hGGM8
[1] 11227
[2] 11228
scottbomb@main:~$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=iXZV5uAYMJI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.03
[debug] Python version 2.7.12 - Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[youtube] iXZV5uAYMJI: Downloading webpage
[youtube] iXZV5uAYMJI: Downloading video info webpage
[youtube] iXZV5uAYMJI: Extracting video information
[youtube] iXZV5uAYMJI: Downloading MPD manifest
[youtube] iXZV5uAYMJI: Downloading MPD manifest
[debug] Invoking downloader on u'https://r1---sn-q4f7sn7d.googlevideo.com/videoplayback/id/897655e6e0183092/itag/136/source/youtube/requiressl/yes/ms/au/pl/14/initcwndbps/710000/mv/m/mm/31/nh/IgpwcjA1LmRmdzA2Kg03Mi4xNC4yMTkuMTI1/mn/sn-q4f7sn7d/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/243859953/lmt/1472499061959056/dur/2840.499/mt/1472960426/key/dg_yt0/upn/8W5GGcGobWY/sver/3/signature/94A728DF0E0B273FFDEDD3772CCE1EEB8E2C4CEA.1890BB6C12D2E870C0060C76F0F2FB1F63FA84E1/ip/70.113.37.11/ipbits/0/expire/1472982490/sparams/ip,ipbits,expire,id,itag,source,requiressl,ms,pl,initcwndbps,mv,mm,nh,mn,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 534
[download] Destination: Who Authored the Kernel Recovering Token-Level Authorship Information from Git by Daniel German-iXZV5uAYMJI.f136.mp4
[download]   0.9% of ~344.40MiB at  1.25MiB/s ETA 25:21^C
[2]+  Done                    index=4
[download]   2.1% of ~353.98MiB at 826.13KiB/s ETA 24:48^C
[download]   2.2% of ~337.97MiB at  1.42MiB/s ETA 24:27^C
[download]   2.8% of ~307.11MiB at  1.40MiB/s ETA 23:08^C

## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.03**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.09.03
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

**Comment by remitamine** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by scottbomb** [comment]
Thank you for pointing that out but I had the same problem when using single or double quotes.

**Comment by yan12125** [comment]
Could you paste the new log?

**Comment by scottbomb** [comment]
Output (see also directory listing below):

scottbomb@main:~$ youtube-dl -v  "https://www.youtube.com/watch?v=iXZV5uAYMJI&index=4&list=PLGeM09tlguZQyemL0Y5CdpEFrBs-hGGM8"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=iXZV5uAYMJI&index=4&list=PLGeM09tlguZQyemL0Y5CdpEFrBs-hGGM8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.03
[debug] Python version 2.7.12 - Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLGeM09tlguZQyemL0Y5CdpEFrBs-hGGM8 - add --no-playlist to just download video iXZV5uAYMJI
[youtube:playlist] PLGeM09tlguZQyemL0Y5CdpEFrBs-hGGM8: Downloading webpage
[download] Downloading playlist: LinuxCon + ContainerCon North America 2016
[youtube:playlist] playlist LinuxCon + ContainerCon North America 2016: Downloading 40 videos
[download] Downloading video 1 of 40
[youtube] e_TevoPsQ90: Downloading webpage
[youtube] e_TevoPsQ90: Downloading video info webpage
[youtube] e_TevoPsQ90: Extracting video information
[youtube] e_TevoPsQ90: Downloading MPD manifest
[youtube] e_TevoPsQ90: Downloading MPD manifest
[debug] Invoking downloader on u'https://r5---sn-q4f7sn76.googlevideo.com/videoplayback/id/7bf4debe83ec43dd/itag/136/source/youtube/requiressl/yes/nh/IgpwcjA4LmRmdzA2KgkxMjcuMC4wLjE/initcwndbps/807500/pl/14/mv/m/ms/au/mn/sn-q4f7sn76/mm/31/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/123842863/lmt/1472498615049997/dur/1180.666/key/dg_yt0/signature/272471FFA02C8ACD7EF717E5A7847BDE033C9C32.95103411153BB4A2EE99A2A81DDC1D9FEE44731F/sver/3/upn/EGr3TaawSVU/mt/1473000800/ip/70.113.37.11/ipbits/0/expire/1473023418/sparams/ip,ipbits,expire,id,itag,source,requiressl,nh,initcwndbps,pl,mv,ms,mn,mm,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 223
[download] Destination: Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4
[download]  14.0% of ~175.62MiB at  1.46MiB/s ETA 02:12^C
ERROR: Interrupted by user

Partial directory listing after terminating:

Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Init
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg0
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg1
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg10
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg11
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg12
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg13
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg14
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg15
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg16
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg17
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg18
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg19
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg2
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg20
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg21
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg22
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg23
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg24
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg25
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg26
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg27
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg28
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg29
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg3
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg30.part
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg4
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg5
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg6
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg7
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg8
Keynote - Welcome and Opening Remarks by Jim Zemlin-e_TevoPsQ90.f136.mp4.part-Seg9

**Comment by dstftw** [comment]
This is DASH format served in segments. Segments are removed after download is complete.

**Comment by scottbomb** [comment]
Thank you. I've never seen that before and I've been using youtube-dl for years. I let it run the full course and after creating almost 200 files, it did indeed delete them all before it terminated. Last night, I had 5 terminals opened, each one downloading a video so you can imagine my alarm when I noticed my home directory filling up with hundreds of files that looked like duplicates.
