### ISSUE TITLE
site support request for Pornspot.com

### ISSUE THREAD

**Issue by LearningToF1y** [rg3/youtube-dl#10555]
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.09.04.1_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.04.1**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
WARNING: Falling back on generic information extractor. ERROR: Unsupported URL: https://www.pornspot.com/video33657/stunning-alexis-adams-fucks-during-yoga-session
...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.pornspot.com/video48461/mi-verga

---
### Description of your _issue_, suggested solution and other information

It looks like the download URL is directly in the source of the video, check source for: **data-video**

Also thanks for running youtube-dl I use it for all my videos I hope I can help by making site support request!

**Comment by raszpl** [comment]
1 LOL
2 weird that generic extractor cant pick up src element from ordinary VIDEO tag?

`<video class="jw-video jw-reset" x-webkit-airplay="allow" webkit-playsinline="" src="https://lg-cdn-ssl.xpagemedia.com/media/xpage/ef/a8/efa8869e-d6f2-4d59-8ae4-436e0db866ba/public/video/240p.mp4?stime=1473143528&amp;etime=1473147188&amp;hash=0cacb9844a3d91e2ee6d3"></video>`

even primitive bruteforce method of searching website source for .mp4 string would yield result.

**Comment by LearningToF1y** [comment]
The <video> part isn't in the source code I think that's why youtube-dl doesn't find it.
I think still it should be possible to add because the whole url for all the formats is in the source code you can get the urls with regex `data-video*=('|")(.*)('|")` (no idea if this works. new to regex)

**Comment by yan12125** [comment]
The example video looks like from passion-hd.com. If pornnspot reupload videos downloaded from passion-hd.com, youtube-dl won't support it as it violates copyright. Do you have other examples?

**Comment by tomcorbett** [comment]
@yan12125 just so you know, a lot of the content on this site is paid for content and scraping it would copyright

**Comment by Hrxn** [comment]
It would copyright what?

**Comment by tomcorbett** [comment]
@Hrxn apologies - I mean that a lot of the content on that site is paid for and copyrighted content so there are legal issues - just adding to what @yan12125 was saying

**Comment by LearningToF1y** [comment]
OK, here is one without copyright: https://www.pornspot.com/video48461/mi-verga

**Comment by mpenkov** [comment]
Looks like the domain is parked now. I think we can close this ticket.
