### ISSUE TITLE
youtube-dl hangs when trying to log in to facebook,  youtube, etc.?

### ISSUE THREAD

**Issue by clampak** [rg3/youtube-dl#10550]
## Please follow the guide below

---

- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.03**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)

```
$ youtube-dl -v -u email@gmail.com https://www.facebook.com/videosbelike/videos/621781174652183/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'https://www.facebook.com/videosbelike/videos/621781174652183/']


$ youtube-dl -v -u "email@gmail.com" "https://youtu.be/hYWF9M19UeM?list=PLyxXU2_2uYjHCb85x2ubsg8MrzcMlUjqN"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'https://youtu.be/hYWF9M19UeM?list=PLyxXU2_2uYjHCb85x2ubsg8MrzcMlUjqN']
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

Any video I attempt to download on facebook or youtube (haven't checked other sites) results in youtube-dl hanging at the '[debug] Command-line args' line, as above.   The issue doesn't change  whether I try to use a password on the command line or not.

**Comment by dstftw** [comment]
Post the output of `youtube-dl --version`, ```md5sum `which youtube-dl` ``` and `strace -f youtube-dl -v`.

**Comment by clampak** [comment]
```
$ youtube-dl --version
2016.09.03

$ md5sum `which youtube-dl`
478f7c08557da3f55149fb3c0124b8fa */cygdrive/c/Python27/Scripts/youtube-dl

$ strace -f youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2016.09.03
[debug] Python version 2.7.11 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg git-2016-05-16-8767470, ffprobe git-2016-05-16-8767470, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
--- Process 3172 created
--- Process 3172 loaded C:\WINDOWS\system32\ntdll.dll at 7C900000
--- Process 3172 loaded C:\WINDOWS\system32\kernel32.dll at 7C800000
--- Process 3172 loaded C:\WINDOWS\system32\shlwapi.dll at 77F60000
--- Process 3172 loaded C:\WINDOWS\system32\advapi32.dll at 77DD0000
--- Process 3172 loaded C:\WINDOWS\system32\rpcrt4.dll at 77E70000
--- Process 3172 loaded C:\WINDOWS\system32\secur32.dll at 77FE0000
--- Process 3172 loaded C:\WINDOWS\system32\gdi32.dll at 77F10000
--- Process 3172 loaded C:\WINDOWS\system32\user32.dll at 7E410000
--- Process 3172 loaded C:\WINDOWS\system32\msvcrt.dll at 77C10000
--- Process 3172 loaded C:\WINDOWS\system32\imm32.dll at 76390000
--- Process 3172 loaded C:\WINDOWS\system32\lpk.dll at 629C0000
--- Process 3172 loaded C:\WINDOWS\system32\usp10.dll at 74D90000
--- Process 3172 exited with status 0x2

**Comment by dstftw** [comment]
Why not just use youtube-dl.exe directly?

**Comment by clampak** [comment]
I installed it via pip, and this is the way I've always used it.  Shouldn't it work this way?

**Comment by dstftw** [comment]
Installed via pip on Windows under cygwin instead of just using Windows binary directly. Or using pip under Windows directly. What is the point of such complexity?
Latest cygwin does not seem to support Windows XP anymore, so I'm not able even to try reproducing.

**Comment by clampak** [comment]
It's not complex.  I use Cygwin all the time, so yes, I used pip under Cygwin to install youtube-dl.  This issue started at least a few months ago prior to the (very recent) Cygwin change which removed support for XP.  I've just been busy with other things and hadn't gotten around to reporting it.

And you can still install Cygwin 2.5.2 via the setup program, which does have support for XP.

I realize there are multiple ways to install youtube-dl.  Shouldn't they all work?  Why wouldn't this one work?  It's very easy to update via pip, that's why I do it.  I don't have issues with anything else installed this way.

**Comment by yan12125** [comment]
As @dstftw said, there are several options if want to use pip:

* Use ```C:\Python27\Scripts\pip.exe``` from ```cmd.exe``` to install youtube-dl
* Use Cygwin's own Python

In your log I see you are trying to run applications in ```C:\Python27``` from Cygwin. Files in ```C:\Python27``` is built with Visual Studio while Cygwin uses GCC. They are not compatible, and random things may break. I've seen some failures when mixing them together, and my conclusion is that don't mix the two variants.

**Comment by dstftw** [comment]
Just checked Cygwin 2.5.2, works fine for me.

**Comment by dstftw** [comment]
With system python, it stops on [password prompt](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/__init__.py#L132) that is most likely caused by aforementioned mixing. When password is provided on command line it works fine, so this is wrong:
>The issue doesn't change whether I try to use a password on the command line or not.
