### ISSUE TITLE
How to embed downloading date in filename

### ISSUE THREAD

**Issue by urza** [rg3/youtube-dl#10558]
Hi,
I know there is unix timestamp, but I would like to have just YYYYMMDD date of when the video was downloaded as part of the output filename. Is this possible?

**Comment by yan12125** [comment]
```%(upload_date)s``` should work.

**Comment by urza** [comment]
I am not interested in "upload date"  but "download date".

**Comment by yan12125** [comment]
Sorry I misunderstood you. It's not possible with youtube-dl only. An approach can be using ```--exec``` with some script to rename the downloaded file.

**Comment by urza** [comment]
Can I suggest this as feature somewhere?

**Comment by phihag** [comment]
What's wrong with

    youtube-dl -o "$(date +%Y%m%d)-%(title)s-%(id)s.%(ext)s" your_url_here

? I don't think we need to add any features to youtube-dl for that. Or are you really running youtube-dl jobs that span days?

**Comment by yan12125** [comment]
Thanks @phihag. I wasn't aware of such a simple solution.

**Comment by urza** [comment]
Excellent, I didn't know I could do this. I am not as experienced with command line.
Maybe it would be worth noting in the documentation?

**Comment by phihag** [comment]
Not really, composability is a primary feature of any decent shell. There are thousands of simple and useful compositions, and billions in general. We can't list them all, and that's out of scope of youtube-dl.

**Comment by urza** [comment]
Hi, could you help me please? 
I tried to put the date in the filename as suggested by adding the _$(date +%Y%m%d)_ into the output filename but youtube-dl is returning and error when I try to download the videos:
"_ERROR: Error in output template: unsupported format character 'Y' (0x59) at index 54 (encoding: 'UTF-8')_"

My download command is in file dowload_yt.sh and looks like this:
```
#!/bin/bash
/usr/local/bin/youtube-dl --download-archive '/poolgarden/urza/media/VIDEOS/SHORT/movement/downloaded.txt' -o '/poolgarden/urza/media/VIDEOS/SHORT/movement/$(date +%Y%m%d)-%(uploader)s-%(title)s-%(id)s.%(ext)s' -w --restrict-filenames 'https://www.youtube.com/playlist?list=PLq4GeMnWONsS8bLDYF8zvpfz1fEyk22T9' -i
```

Thanks for any help.

**Comment by urza** [comment]
Nevermind, I have it working:

#!/bin/bash
 -o '/path/**'$(date +"%Y%m%d")'**-%(uploader)s-%(title)s-%(id)s.%(ext)s' -w --restrict-filenames  ...

**Comment by SimonEast** [comment]
Apologies for commenting on a very old thread, however this still shows up when Googling this question, so I thought it could use an updated answer.

On Windows command line the `$(date...)` syntax will not work.

Instead you can use `-o "%(epoch)s"`

```
%(epoch)s                            Prints the time as a number, e.g. "1739155332"
%(epoch>%Y-%m-%d %H-%M-%S)s          UTC time, e.g. "2025-02-10 12-50-15"
%(epoch+36000>%Y-%m-%d %H-%M-%S)s    Add/subtract the number of seconds to reach your timezone
```

When you're troubleshooting filename output formats, remember to use:

```
yt-dlp --print filename --output "..." [URL]
```

This will dump only the filename to your terminal (without doing any downloading) so you can check that it appears as you want it.
