### ISSUE TITLE
Support Nanairo

### ISSUE THREAD

**Issue by steamymotel** [rg3/youtube-dl#10562]
### What is the purpose of your *issue*?
- [ x ] Site support request (request for adding support for a new site)

Support website : nanairo.co/en/
Collective site with various certain studio from Japan Porn

Free timer should be enough to tested for complete video for ona, blowjob etc video.
nanairo.co/en/#plan_and_coin

I am no sure the technology behind the website, if anyone can point out what technology of streaming, and if any existing youtubedl website script can be use as modifies to support it.
I am glad to help.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by yan12125** [comment]
Closing as no response for a long time.
