### ISSUE TITLE
after updating i got this error: the program cant start because msvcr100.dll is missing from your computer

### ISSUE THREAD

**Issue by angel100w** [rg3/youtube-dl#10564]
hello, after i updated i got this error: the program cant start because msvcr100.dll is missing from your computer

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#the-exe-throws-an-error-due-to-missing-msvcr100dll

**Comment by angel100w** [comment]
but it used to work before

**Comment by dstftw** [comment]
It won't now.
