### ISSUE TITLE
[TUBE8] Add functionality to extract more metadata (categories & tags)

### ISSUE THREAD

**Issue by razor1907** [rg3/youtube-dl#10579]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.04.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.04.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x ] Feature request (request for a new functionality)
- [x] Question
- [x] Other

### full verbose output as follows:
$ youtube-dl -v 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.tube8.com/amateur/faketaxi-playing-cowboys-and-indians-for-4th-july/31897341/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.31
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}

### example URL:

- Single video: http://www.tube8.com/amateur/faketaxi-playing-cowboys-and-indians-for-4th-july/31897341/

### Description of your *issue*, suggested solution and other information

Metadata like "categories" and "tags" are not included when downloading videos from tube8.com.
This is most likely to be solved if 'categories': list, or 'tags': list, will be added to current extractor command.

thank you very much

**Comment by advertcn** [comment]
You can use their hubtraffic.com to get a detailed CSV file and use youtube-dl to download videos only

**Comment by razor1907** [comment]
I have Youtube-dl integrated in a CMS which does 99% of the work automatically, including assigning the categories/tags etc etc to related videos, so for me it is very important Youtube-dl includes the category and tags command :)
