### ISSUE TITLE
AETV && Provider Logins

### ISSUE THREAD

**Issue by OverlordQ** [rg3/youtube-dl#10571]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.04.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.04.1**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://www.aetv.com/shows/intervention/season-15/episode-18 --cookies cookies.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.aetv.com/shows/intervention/season-15/episode-18', u'--cookies', u'cookies.txt']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.04.1
[debug] Python version 2.7.12+ - Linux-4.5.0-2-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.1.2-1, ffprobe 3.1.2-1
[debug] Proxy map: {}
[aenetworks] intervention/season-15/episode-18: Downloading webpage
[aenetworks] 743234115902: Downloading JSON metadata
[aenetworks] 743234115902: Downloading SMIL data
ERROR: This content requires a valid, unexpired auth token.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.9.4.1-py2.7.egg/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.9.4.1-py2.7.egg/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.9.4.1-py2.7.egg/youtube_dl/extractor/aenetworks.py", line 121, in _real_extract
    formats, subtitles = self._extract_theplatform_smil(media_url, video_id)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.9.4.1-py2.7.egg/youtube_dl/extractor/theplatform.py", line 40, in _extract_theplatform_smil
    raise ExtractorError(error_element.attrib['abstract'], expected=True)
ExtractorError: This content requires a valid, unexpired auth token.
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

AETV works unless it's a video that requires provider login. I've included DirecTV credentials into the .netrc file but it doesn't seem to help.

```
$ cat ~/.netrc
machine DTV
  login <email>
  password <password>
```

**Comment by remitamine** [comment]
you didn't specify to load credentials from netrc file:
```
-n, --netrc                      Use .netrc authentication data
```

**Comment by OverlordQ** [comment]
I'm an idiot, that worked.
