### ISSUE TITLE
Vessel Authentication Broke

### ISSUE THREAD

**Issue by Kilo19** [rg3/youtube-dl#10586]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.04.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.04.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
```
$ youtube-dl -v https://www.vessel.com/videos/UVKzKf25U -u 'MYVESSELUSER' -p 'MYVESSELPASS'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.vessel.com/videos/UVKzKf25U', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.09.04.1
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Vessel] Logging in
ERROR: Wrong login info: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\users\sajuuk\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 394, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\sajuuk\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1998, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\sajuuk\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 471,in open
    response = meth(req, response)
  File "c:\users\sajuuk\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 581,in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\sajuuk\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 509,in error
    return self._call_chain(*args)
  File "c:\users\sajuuk\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 443,in _call_chain
    result = func(*args)
  File "c:\users\sajuuk\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 589,in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
...
<end of log>
```

### Description of your *issue*, suggested solution and other information
Downloading exclusive videos on Vessel with username and password used to work a couple of days ago, and now I can only pass cookies. I believe a 7 or 10 day free trial for Vessel membership is available, or ask people watching LinusTechTips on Vessel. If neither is possible, email admin@nixiesubs.com for a valid credential. Please include the URL of this issue.

**Comment by badp** [comment]
If you're ever going to fix this, the time is now, since the service is going down literally tomorrow.

**Comment by Kilo19** [comment]
Since Vessel is going down (no pun intended), I'll close the issue myself.

**Comment by badp** [comment]
Thank you for mentioning the `--add-header` workaround. I guess I'll spend some words on how to do that.

1. Log into vessel on your browser
2. HIt F12 to open the developer tools
3. Click on the Network tab
4. Refresh the Vessel webpage
5. Back to the network tab, scroll to the top and click on the first request
6. Look at the Cookie header and copy it. ![](http://i.imgur.com/ksQFeEb.png)
7. At the prompt type `youtube-dl --add-header '`, then paste what you copied, then `' ` followed by the url(s) you want to preserve.
