### ISSUE TITLE
[Tou.tv] UnicodeDecodeError: 'utf8' codec can't decode byte 0x96 in position 17: invalid start byte

### ISSUE THREAD

**Issue by jnbdz** [rg3/youtube-dl#10599]
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.09.08_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.08**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$  youtube-dl -v http://ici.tou.tv/vox-pop/S01E02
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://ici.tou.tv/vox-pop/S01E02']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.08
[debug] Python version 2.7.12 - Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[tou.tv] vox-pop/S01E02: Downloading JSON metadata
[radiocanada] 122195: Downloading ipad XML
[radiocanada] 122195: Downloading m3u8 information
[radiocanada] 122195: Downloading android XML
[radiocanada] 122195: Downloading m3u8 information
[radiocanada] 122195: Downloading f4m manifest
[radiocanada] 122195: Downloading m3u8 information
[radiocanada] 122195: Downloading f4m manifest
[radiocanada] 122195: Downloading m3u8 information
[radiocanada] 122195: Downloading f4m manifest
[radiocanada] 122195: Downloading m3u8 information
[radiocanada] 122195: Downloading f4m manifest
[radiocanada] 122195: Downloading m3u8 information
[radiocanada] 122195: Downloading f4m manifest
[radiocanada] 122195: Downloading metadata XML
[debug] Invoking downloader on u'http://medias-rtsp.tou.tv/vodtoutv/_definst_/mp4:012/mp4/v/2016-04-26_19_30_00_voxpop_0013_3000.mp4/chunklist.m3u8?wowzasessionid=1817449880'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 130
[download] Destination: Épisode 2-122195.mp4
[download]  62.3% of ~503.38MiB at  2.46MiB/s ETA 01:35Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 434, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 424, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1788, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 702, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 773, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 748, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1432, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1698, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2133, in error_to_compat_str
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x96 in position 17: invalid start byte

<end of log>
```

**Comment by yan12125** [comment]
Looks like a network issue. Could you try again? Also, if the problem persists, could you try youtube-dl on Python 3?
