### ISSUE TITLE
Help me to use external downloader

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#10595]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.04.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.04.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
PS C:\Users\vicky\downloads> youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.09.04.1
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
PS C:\Users\vicky\downloads>
```
### Description of your *issue*, suggested solution and other information

i need help to use external downloader 
i generate downloading url from video streaming site and its save in link.txt using your command 
like this
youtube-dl --verbose http://app.pluralsight.com/courses/nodejs-security-express-angular-get-started --get-url --username 12345@hotmail.com --password 12345 > links.txt

after that its save links in txt file but now i want to download these videos through external download so can you plz explain me what is exact command to use it and it will read this txt file and download all videos

this txt file saving in this directory 
C:\Users\vicky\Downloads

thanks

**Comment by yan12125** [comment]
Check the manual of your favorite downloader and feed links.txt to it.

**Comment by jaan143** [comment]
can you plz recommenced other than IDM ?
because IDM is not download with original title name

**Comment by yan12125** [comment]
If you need to keep titles in filenames, use --external-downloader instead. For example:
```
youtube-dl --external-downloader <the downloader name> <video URL>
```
Currently only aria2c,avconv,axel,curl,ffmpeg,httpie and wget are supported. Please follow #9861 if you need IDM.

**Comment by jaan143** [comment]
you mean like this ?
youtube-dl --verbose --external-downloader idm https://udemy-assets-on-demand2.udemy.com/2016-07-16_21-09-36-bb6f58d7a5e8ad2e11e4cdb1120cb143/WebHD_1080.mp4?nva=20160908173957&token=0ef939fa1f107a684af46

**Comment by yan12125** [comment]
Yeah, but idm is not supported yet. You may want to change idm to one of aria2c, avconv, axel, curl, ffmpeg, httpie or wget.

**Comment by jaan143** [comment]
but Sir for this way i need to download all videos one by one ? because i generated links in txt file then need put one by one with this command ?

**Comment by yan12125** [comment]
It should work for playlists, too. By the way, you may want to try axel or aria2c, both of which use multiple connections for downloading.

**Comment by jaan143** [comment]
i figure out its not problem of IDM because when i generate links its not generated with original title name its generated with some numbers and idm download with that numbers filename 
see here
http://vid.pluralsight.com/expiretime=1473338970/af682fd0e7e066508914173cd326e767/clip-videos/matthew-renze/r-mastering-data-visualization-m0/r-mastering-data-visualization-m0-01/1280x720mp4/20160907153219.mp4
http://vid.pluralsight.com/expiretime=1473338976/b86730a2bfd8e0b264c3490d5d9907fd/clip-videos/matthew-renze/r-mastering-data-visualization-m1/r-mastering-data-visualization-m1-01/1280x720mp4/20160907153258.mp4

i generated these with youtube-dl so is it possible to generate with original titles ?
or if its generate with my specific numbers 
for example
http://vid.pluralsight.com/expiretime=1473338970/af682fd0e7e066508914173cd326e767/clip-videos/matthew-renze/r-mastering-data-visualization-m0/r-mastering-data-visualization-m0-01/1280x720mp4/1.mp4
http://vid.pluralsight.com/expiretime=1473338976/b86730a2bfd8e0b264c3490d5d9907fd/clip-videos/matthew-renze/r-mastering-data-visualization-m1/r-mastering-data-visualization-m1-01/1280x720mp4/2.mp4
http://vid.pluralsight.com/expiretime=1473338980/04c96f0df403c90c5c70bd7a4047a105/clip-videos/matthew-renze/r-mastering-data-visualization-m1/r-mastering-data-visualization-m1-02/1280x720mp4/3.mp4

see end 1.mp4
2.mp4
3.mp4
but auto its generated with this filename
20160907153258.mp4
20160907153219.mp4

**Comment by yan12125** [comment]
Those URLs are fetched from Pluralsight not generated by youtube-dl. If you change it, videos won't be downloaded. If you want IDM to save URLs with a different name, check IDM manuals.

**Comment by jaan143** [comment]
i download aria2c and youtube-dl downloading with that
but its cant read all url txt file and download all videos automatically ?
is it possible or not if yes then plz help me about this command

thanks

**Comment by yan12125** [comment]
What's your command and the result?

**Comment by jaan143** [comment]
like this
youtube-dl --external-downloader aria2c http://vid.pluralsight.com/expiretime=1473347773/f846d9607da92f9f4c88b9817c7ba283/clip-videos/vlad-catrinescu/planning-sharepoint-server-2016-topology-services-m0/planning-sharepoint-server-2016-topology-services-m0-01/1280x720mp4/20160907153653.mp4

**Comment by jaan143** [comment]
it will not ask password ?

**Comment by yan12125** [comment]
If this video requires password, it will. The full command is like:
```
youtube-dl --verbose --external-downloader aria2c http://app.pluralsight.com/courses/nodejs-security-express-angular-get-started --username 12345@hotmail.com --password 12345
```

**Comment by jaan143** [comment]
actually bro if i use username then pluralsight banned account to download too fast so thats why i am generating links then i change ip and downloading all videos with that links through idm so when i generate links.txt is it possible with this way to read link.txt file and download all videos ?
because after generate links we can downnload as anonymous

**Comment by yan12125** [comment]
Currently your link.txt contains plain URLs only, so there are no titles in filenames. Check IDM manual if it provides another format that reads in titles and URLs at the same time.

**Comment by jaan143** [comment]
ohh ok :(

**Comment by yan12125** [comment]
Here are some discussions about how to prevent pulralsight accounts from banning: #6090 #6842. Of course there's no guarantee.

**Comment by jaan143** [comment]
bro with area2c can read txt file and download all videos ? no matter with original name or not

**Comment by yan12125** [comment]
https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-i

**Comment by remitamine** [comment]
it's possible with some scripting to do what you want using aria2c, the links file should be like this:
```
url1
 out=file1.mp4
url2
 out=file2.mp4
```

**Comment by jaan143** [comment]
yeah links are like this bro
http://vid.pluralsight.com/expiretime=1473347773/f846d9607da92f9f4c88b9817c7ba283/clip-videos/vlad-catrinescu/planning-sharepoint-server-2016-topology-services-m0/planning-sharepoint-server-2016-topology-services-m0-01/1280x720mp4/20160907153653.mp4

**Comment by jaan143** [comment]
#remitamine can you plz explain me little bit ?

**Comment by remitamine** [comment]
for example you have to change the links file to something like:
```
http://vid.pluralsight.com/expiretime=1473347773/f846d9607da92f9f4c88b9817c7ba283/clip-videos/vlad-catrinescu/planning-sharepoint-server-2016-topology-services-m0/planning-sharepoint-server-2016-topology-services-m0-01/1280x720mp4/20160907153653.mp4
 out=Course Overview.mp4
http://vid.pluralsight.com/expiretime=1473338976/b86730a2bfd8e0b264c3490d5d9907fd/clip-videos/matthew-renze/r-mastering-data-visualization-m1/r-mastering-data-visualization-m1-01/1280x720mp4/20160907153258.mp4
 out=Course Introduction.mp4
...
```

**Comment by jaan143** [comment]
no its not downloading with that i tried yesterday because with numbers its original url and when we change numbers to title then url going to dead

**Comment by remitamine** [comment]
i didn't said that you have to change the url, i said:
```
original_url
 out=filename.mp4
```
