### ISSUE TITLE
[AdobePass] Support ROGERS Cable authentication

### ISSUE THREAD

**Issue by level42ca** [rg3/youtube-dl#10606]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.08*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.08**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\Jeff\Desktop\youtube-dl>youtube-dl -v "http://www.aetv.com/shows/shipping-wars/season-5/episode-1"
[debug] System config: []
[debug] User config: ['-o', '~/Movies/%(title)s.%(ext)s', '-n']
[debug] Command-line args: ['-v', 'http://www.aetv.com/shows/shipping-wars/season-5/episode-1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.09.08
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[aenetworks] shipping-wars/season-5/episode-1: Downloading webpage
[aenetworks] 79213123917: Downloading JSON metadata
[aenetworks] 79213123917: Downloading Provider Redirect Page
[aenetworks] 79213123917: Downloading Provider Login Page
[aenetworks] 79213123917: Logging in
[aenetworks] 79213123917: Confirming Login
[aenetworks] 79213123917: Retrieving Session
ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2ypwv0j\build\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2ypwv0j\build\youtube_dl\YoutubeDL.py", line 1998, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.aetv.com/shows/shipping-wars/season-4/episode-4
- Single video: http://www.aetv.com/shows/shipping-wars/season-4/episode-5
- Playlist: http://www.aetv.com/shows/shipping-wars/season-4

---

From what I understand, aenetworks currently only works with Direct TV.

I'm in Canada with Rogers as my cable provider, and I was simply wondering if someone could point me to a bug, or thread related to this issue where I can track the problem.

Much appreciated. Thank you!

**Comment by yan12125** [comment]
> From what I understand, aenetworks currently only works with Direct TV.

You're right.

> I was simply wondering if someone could point me to a bug, or thread related to this issue where I can track the problem.

Let this one be!

**Comment by yan12125** [comment]
By the way, could you provide a concrete example URL?

**Comment by level42ca** [comment]
Thank you for setting this up for me. I hope the links I provided in the original post will suffice :)

**Comment by level42ca** [comment]
Ok, we'll I've made the changes in my .netrc file, but I'm unsure as to how to make the changes to the adobepass.py file.

**Comment by yan12125** [comment]
Oh didn't notice you're using the Windows exe. It's a compressed file and there's no easy to change files in it. If you know how to install and use Python on Windows, you may want to check [developer instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#developer-instructions).

**Comment by level42ca** [comment]
I've already got Python, but the instructions for compiling youTube-DL are unclear. All it is, from what I can see, is a list of software requirements ...

**Comment by yan12125** [comment]
There's no need to compile. Downloading the source, it should be OK to run. Does this command work?
```
python.exe -m youtube_dl
```

**Comment by Hrxn** [comment]
Alternatively, you can simply download the source archive (green button, upper right corner of item list), extract it (default folder name should be `youtube-dl-master`) and then run it like this:

`python youtube-dl-master\youtube_dl\__main__.py`

Or go into the `youtube_dl` (Underscore) subdir and run it directly
`python __main__.py`

The `extractor` dir is located in the same place, there are the source files you can simply edit.

**Comment by level42ca** [comment]
Ok, so I downloaded a clone of the git, changed the code in adobepass.py, as recommended, and finally figured out how to run my changes. However, it seems to be worse now.

```
C:\Python27>python youtube-dl-master\youtube_dl\__main__.py -v -n http://www.aetv.com/shows/shipping-wars/season-5/episode-1
[debug] System config: []
[debug] User config: [u'-o', u'~/Movies/%(title)s.%(ext)s', u'-n']
[debug] Command-line args: [u'-v', u'-n', u'http://www.aetv.com/shows/shipping-wars/season-5/episode-1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.09.08
[debug] Python version 2.7.12 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[aenetworks] shipping-wars/season-5/episode-1: Downloading webpage
[aenetworks] 79213123917: Downloading JSON metadata
[aenetworks] 79213123917: Downloading Provider Redirect Page
[aenetworks] 79213123917: Downloading Provider Login Page
Traceback (most recent call last):
  File "youtube-dl-master\youtube_dl\__main__.py", line 19, in <module>
    youtube_dl.main()
  File "C:\Python27\youtube-dl-master\youtube_dl\__init__.py", line 434, in main
    _real_main(argv)
  File "C:\Python27\youtube-dl-master\youtube_dl\__init__.py", line 424, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Python27\youtube-dl-master\youtube_dl\YoutubeDL.py", line 1788, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Python27\youtube-dl-master\youtube_dl\YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python27\youtube-dl-master\youtube_dl\extractor\common.py", line 347, in extract
    return self._real_extract(url)
  File "C:\Python27\youtube-dl-master\youtube_dl\extractor\aenetworks.py", line 117, in _real_extract
    url, video_id, requestor_id, resource)
  File "C:\Python27\youtube-dl-master\youtube_dl\extractor\adobepass.py", line 81, in _extract_mvpd_auth
    provider_redirect_page, 'Downloading Provider Login Page')
  File "C:\Python27\youtube-dl-master\youtube_dl\extractor\adobepass.py", line 67, in post_form
    'Content-Type': 'application/x-www-form-urlencoded',
  File "C:\Python27\youtube-dl-master\youtube_dl\extractor\common.py", line 507, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Python27\youtube-dl-master\youtube_dl\extractor\common.py", line 414, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Python27\youtube-dl-master\youtube_dl\extractor\common.py", line 394, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Python27\youtube-dl-master\youtube_dl\YoutubeDL.py", line 1998, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 421, in open
    protocol = req.get_type()
  File "C:\Python27\lib\urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: authorize?oauth_token=oWgArttyE1Q9ABK04AMTUA%3d%3d
```

**Comment by yan12125** [comment]
Seems Rogers are quite different than DTV, and replacing variables does not work. Need someone to check it as I don't have a Rogers account.

**Comment by michaelaris** [comment]
bump, I'm also interested in a Rogers config

**Comment by dstftw** [comment]
For any further work on this you have to provide account credentials.

**Comment by level42ca** [comment]
Who would I need to provide credentials too?

**Comment by dstftw** [comment]
To one of the developers who is willing to. Maybe @remitamine as the most expertise with Adobe Pass.

**Comment by level42ca** [comment]
Do I reach out to @remitamine? Or wait for @remitamine to come to me?

**Comment by dstftw** [comment]
Wait for some time first.

**Comment by level42ca** [comment]
Will do, thank you!

**Comment by remitamine** [comment]
you can contact me at remitamine[at]gmail[dot]com.

**Comment by level42ca** [comment]
Thanks @remitamine, I've sent you an email now.

**Comment by remitamine** [comment]
will be supported in the next version.

**Comment by level42ca** [comment]
Thanks @remitamine.
