### ISSUE TITLE
How to setup the %HOME% environment variable manually (On Windows 10)

### ISSUE THREAD

**Issue by level42ca** [rg3/youtube-dl#10601]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.08*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.08**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

Sorry if this question is vague, but in following the directions here: https://github.com/rg3/youtube-dl/blob/master/README.md#authentication-with-netrc-file

I cannot figure out how to do the following:

"On Windows you may also need to setup the %HOME% environment variable manually."

Thus, I keep getting the following error:

WARNING: parsing .netrc: Could not find .netrc: $HOME is not set

**Comment by dstftw** [comment]
http://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10
