### ISSUE TITLE
Error downloading YouTube videos with new signature length 92

### ISSUE THREAD

**Issue by Baqan** [rg3/youtube-dl#1060]
Hi,

I have problems when I try to downloads videos from YouTube since some hours ago. Apparently, there is a new signature length (92).

C:\yt-dl>youtube-dl http://www.youtube.com/watch?v=j5-yKhDd64s
[youtube] Setting language
[youtube] j5-yKhDd64s: Downloading video webpage
[youtube] j5-yKhDd64s: Downloading video info webpage
[youtube] j5-yKhDd64s: Extracting video information
[youtube] j5-yKhDd64s: Encrypted signatures detected.
ERROR: Unable to decrypt signature, key length 92 not supported; retrying might
work; please report this issue on https://yt-dl.org/bug . Be sure to call youtub
e-dl with the --verbose flag and include its complete output.

I don't know what can I do it. Any fix? Thank in advance.

**Comment by chaoming** [comment]
@awojnowski in which Javascript variable I can pick up the 92 signature?
