### ISSUE TITLE
Site request: REN.TV documentary

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#10620]
Authors, hello again!
I asked you ppl to make YOUTUBE-DL compatible with ren.tv site, it worked sometimes OK, but now I see that not all video pages on this ren.tv are available for YOUTUBE-DL to be downloaded.

I speak of "Dobrov v efire" news on ren.tv: http://ren.tv/video/epizod/120233
As you can see - YOUTUBE-DL getting 5 seconds promo clip only, although - if you visit this url - you'll see that whole video is longer than 1 hour as usual.

The main request is to make YOUTUBE-DL compatible with playlists of ren.tv (and http://ren.tv/video/epizod/120233 for example), so user like me can download full video , not promo video only.
Thanks in advance !:)

**Comment by nmr50** [comment]
remitamine, the new extractor seems like does not work as I asked before. Here is the log:
R:\>youtube-dl.exe -v -f 135+140 http://ren.tv/video/epizod/120233
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-f', '135+140', 'http://ren.tv/video/epizod/120233']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.10.25
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81391-g2a3720b
[debug] Proxy map: {}
[generic] 120233: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 120233: Downloading webpage
[generic] 120233: Extracting information
[download] Downloading playlist: "Добров в эфире"
[generic] playlist "Добров в эфире": Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] ISYayZeoe8I: Downloading webpage
[youtube] ISYayZeoe8I: Downloading video info webpage
[youtube] ISYayZeoe8I: Extracting video information
[youtube] ISYayZeoe8I: Downloading MPD manifest
[debug] Invoking downloader on 'https://r5---sn-oxuctoxu-n8ve.googlevideo.com/vi
deoplayback?id=21261ac997a87bc2&itag=135&source=youtube&requiressl=yes&mn=sn-oxu
ctoxu-n8ve&mm=31&ms=au&mv=m&pl=26&initcwndbps=4173750&ratebypass=yes&mime=video/
mp4&gir=yes&clen=314763&lmt=1410830360737055&dur=4.960&key=dg_yt0&mt=1477473798&
upn=bJrGNI3iuJg&signature=3613D70E14BCA5FF6B0EC58472EF123F1410513E.2AF3D863BECA2
EA3AFD8BA29B35651185B3F0067&ip=89.20.134.92&ipbits=0&expire=1477495443&sparams=i
p,ipbits,expire,id,itag,source,requiressl,mn,mm,ms,mv,pl,initcwndbps,ratebypass,
mime,gir,clen,lmt,dur'
[download] Destination: Добров в Эфире-ISYayZeoe8I.f135.mp4
**[download] 100% of 307.39KiB in 00:00**
[debug] Invoking downloader on 'https://r5---sn-oxuctoxu-n8ve.googlevideo.com/vi
deoplayback?id=21261ac997a87bc2&itag=140&source=youtube&requiressl=yes&mn=sn-oxu
ctoxu-n8ve&mm=31&ms=au&mv=m&pl=26&initcwndbps=4173750&ratebypass=yes&mime=audio/
mp4&gir=yes&clen=81941&lmt=1410830347930094&dur=5.061&key=dg_yt0&mt=1477473798&u
pn=bJrGNI3iuJg&signature=2938599E73BD5FAE1DE09830A0CF8C22573C2434.334CC9A11F4C57
2C1B37259CC35CE7741FD2C2D6&ip=89.20.134.92&ipbits=0&expire=1477495443&sparams=ip
,ipbits,expire,id,itag,source,requiressl,mn,mm,ms,mv,pl,initcwndbps,ratebypass,m
ime,gir,clen,lmt,dur'
[download] Destination: Добров в Эфире-ISYayZeoe8I.f140.m4a
**[download] 100% of 80.02KiB in 00:00**
[ffmpeg] Merging formats into "Добров в Эфире-ISYayZeoe8I.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Добров в Эфире-ISYayZeoe8I.f135.
mp4' -i 'file:Добров в Эфире-ISYayZeoe8I.f140.m4a' -c copy -map 0:v:0 -map 1:a:0
 'file:Добров в Эфире-ISYayZeoe8I.temp.mp4'
Deleting original file Добров в Эфире-ISYayZeoe8I.f135.mp4 (pass -k to keep)
Deleting original file Добров в Эфире-ISYayZeoe8I.f140.m4a (pass -k to keep)
[download] Finished downloading playlist: "Добров в эфире"

-- I am getting this promo clip only, again...

**Comment by remitamine** [comment]
the new extractor will be included in the next version:
```
python __main__.py http://ren.tv/video/epizod/120233
[RENTV] 120233: Downloading webpage
[RENTV] 120233: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 335
[download] Destination: 'Добров в эфире'-120233.mp4
[download]   0.3% of ~453.71MiB at 69.71KiB/s ETA 01:57:05
```

**Comment by nmr50** [comment]
remitamine; Thanks you very much, I'll be waiting for the updated version !:)

**Comment by nmr50** [comment]
It works fine by now. THANNKS !!:)
