### ISSUE TITLE
Extract subs from OpenLoad videos

### ISSUE THREAD

**Issue by bishiboosh** [rg3/youtube-dl#10625]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.11.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.11.1**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://openload.co/embed/jzsMDm13XWE/
- Single video: https://openload.co/embed/hJwNVrTqpuk/

---

### Description of your *issue*, suggested solution and other information

OpenLoad videos can have subtitle files, but they are not returned when using `--list-subs`. I did not manage to find where the file is specified in the page, or in the Javascript, but when observing the page with web tools, a .vtt file is clearly downloaded, with a specific name scheme.

I think what there is to do is to find how this name scheme work, in order to download the subtitle file.

Example of subtitle files corresponding to the two videos specified above :
- https://thumb.oloadcdn.net/subtitle/jzsMDm13XWE/tYAtG45F4As.vtt
- https://thumb.oloadcdn.net/subtitle/hJwNVrTqpuk/4OKeK3DqCho.vtt

**Comment by bishiboosh** [comment]
Ok, I found where the vtt comes from. In the page HTML, we can see :
```<track kind="captions" src="https://thumb.oloadcdn.net/subtitle/jzsMDm13XWE/tYAtG45F4As.vtt" srclang="fr" label="French" default />```

I don't really know Python, so I don't know how this can be used. I'll try to understand how youtube-dl is developped and see if I can do something, but I'd like the help.

**Comment by yan12125** [comment]
Steven Universe is a copyrighted product of Cartoon Network. Do you have other examples with subtitles?

**Comment by bishiboosh** [comment]
You can use https://openload.co/embed/rjC09fkPLYs which is an upload of http://lachuteduneplume.free.fr/?-English-, an open-source movie. It contains english subtitles, which can be found as seen previously with the `track` tag

**Comment by bishiboosh** [comment]
Do you need me to remove the example links in the first message to avoid copyright issues ?

**Comment by yan12125** [comment]
Thanks for the new example.

> Do you need me to remove the example links in the first message to avoid copyright issues ?

Yeah it should be better to do so.

**Comment by yan12125** [comment]
Subtitles on openload will be recognized in the next version. Thanks for the report and the example.
