### ISSUE TITLE
PromptFile URL Parsing Error

### ISSUE THREAD

**Issue by HatBeardMe** [rg3/youtube-dl#10634]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.11.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.11.1**

```
youtube-dl -U
youtube-dl is up-to-date (2016.09.11.1)
```

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
# youtube-dl http://www.promptfile.com/l/07247DA006-C77ED97278 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.promptfile.com/l/07247DA006-C77ED97278', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.11.1
[debug] Python version 2.7.12 - Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
[PromptFile] 07247DA006-C77ED97278: Downloading webpage
[PromptFile] 07247DA006-C77ED97278: Downloading video page
ERROR: Unable to extract URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/promptfile.py", line 43, in _real_extract
    url = self._html_search_regex(r'url:\s*\'([^\']+)\'', webpage, 'URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 659, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 650, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.promptfile.com/l/9FD7EFDC80-D5AE30F56A
- And any others at PromtFile

---

### Description of your *issue*, suggested solution and other information

Have successfully used `youtube-dl` in the past to download from promptfile, but I cannot any longer. Not sure what version I was using before, it's been a while.
Other downloaders tried are failing to parse aspects of the page - so I imagine that PromptFile has tweaked the page a bit.

**Comment by OndrejIT** [comment]
https://github.com/rg3/youtube-dl/pull/10751 fixed ;)

**Comment by HatBeardMe** [comment]
Hmm, still encountering errors on new version: (for science, I have tried the same video)


```
macbook-pro in ~
○ → youtube-dl --verbose http://www.promptfile.com/l/07247DA006-C77ED97278
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.promptfile.com/l/07247DA006-C77ED97278']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.24
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[PromptFile] 07247DA006-C77ED97278: Downloading webpage
[PromptFile] 07247DA006-C77ED97278: Downloading video page
ERROR: Unable to extract URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 355, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/promptfile.py", line 43, in _real_extract
    url = self._html_search_regex(r'url:\s*\'([^\']+)\'', webpage, 'URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 667, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 658, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
FYI: #10751 is not merged yet.

**Comment by OndrejIT** [comment]
https://github.com/rg3/youtube-dl/pull/10751 Merged ;)
