### ISSUE TITLE
Site request : please add Videum support

### ISSUE THREAD

**Issue by BastienMottier** [rg3/youtube-dl#10636]
Hello,

Someone can add site support for [https://www.videum.com/](https://www.videum.com/) ? This website provide free medical video. 

This website used blob for provide video. I don't know how to get mp4 from it so I can't make script for that.

**Comment by yan12125** [comment]
Hi, could you give the URL for a specific video?

**Comment by BastienMottier** [comment]
[https://www.videum.com/video/trimesters/#.V9gFE3WLSHs](https://www.videum.com/video/trimesters/#.V9gFE3WLSHs)

**Comment by BastienMottier** [comment]
Work since the brightcove support, thanks guys !
