### ISSUE TITLE
TBS.com Episode Download returns "ERROR: Authentication required"

### ISSUE THREAD

**Issue by jdunn0** [rg3/youtube-dl#10642]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.11.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.11.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://www.tbs.com/videos/full-frontal-with-samantha-bee/season-1/episode-22/latinos-for-trump.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.tbs.com/videos/full-frontal-with-samantha-bee/season-1/episode-22/latinos-for-trump.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.11.1-gentoo_no_offensive_sites
[debug] Python version 2.7.10 - Linux-4.4.6-gentoo-x86_64-Intel-R-_Core-TM-_i7_CPU_920_@_2.67GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {}
[TBS] latinos-for-trump: Downloading webpage
[TBS] latinos-for-trump: Downloading XML
[TBS] 2061474: Downloading XML
ERROR: Authentication required
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/tbs.py", line 57, in _real_extract
    'tokenizer_src': 'http://www.%s.com/video/processors/services/token_ipadAdobe.do' % domain,
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/turner.py", line 80, in _extract_cvp_info
    raise ExtractorError(error_msg, expected=True)
ExtractorError: Authentication required
```

---

### Description of your *issue*, suggested solution and other information

Trying to download episode from http://www.tbs.com/videos/full-frontal-with-samantha-bee/season-1/episode-22/latinos-for-trump.html with youtube-dl returns the message "ERROR: Authentication required".
I have tried using the --cookies parameter with cookies file exported from Firefox with an Add-on I found and trying passing my TV Provider Authentication info via the --username parameter but neither worked.

**Comment by StevenDTX** [comment]
Just to add to this. Not sure if it helps anyone or not.  It would appear that the stream has DRM.

```
E:\>c:\support\php\php AdobeHDS.php --manifest "http://phds-vod.cdn.turner.com/tbshds/2016-09/TBSE1008051600033085/set_TBSE1008051600033085.f4m?hdnea=st=1474059125~exp=1474059425~acl=/tbshds/2016-09/TBSE1008051600033085/*~hmac=2acd9a0dfe41b5fefa808e5b7e4412b5136614801fe64abbb84c1c8c5c5f20a0&hdcore=3.4.1.1" --delete --auth "als=0,3,NaN,0,0,NaN,0,0,0,273,f,0,1281.38,f,s,XVRMAJXZFMKS,3.4.1,273&hdcore=3.4.1&plugin=aasp-3.4.1.1.1" --useragent "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" --quality high

                            KSV Adobe HDS Downloader

Processing manifest info....
Quality Selection:
 Available: 1900 1000 600
 Selected : 1900
Fragments Total: 321, First: 1, Start: 1, Parallel: 8
This stream is encrypted with FlashAccess DRM. Decryption of such streams isn't currently possible with this script.
```

**Comment by remitamine** [comment]
there are other formats available(HLS, RTMPE).

**Comment by jdunn0** [comment]
How would one go about using the other available formats?
Running `youtube-dl http://www.tbs.com/videos/full-frontal-with-samantha-bee/season-1/episode-22/latinos-for-trump.html --list-formats` returns "ERROR: Authentication required" so I don't have a list of available formats to try.

**Comment by remitamine** [comment]
for now there is no support for Adobe Pass auth in TBS, TNT, CN, AS sites.
i said that there are other formats as a response for @StevenDTX it's possible to extract other formats.
for me, i have two problems while trying to add support AP:
- the site keep asking for TV provider credentials after successfull login.
- second is that the site uses flash player whitch is very slow and sometimes it crash(low system resources).

**Comment by remitamine** [comment]
will be supported in the next version
