### ISSUE TITLE
youtube live video downloading but not able to play immediately.

### ISSUE THREAD

**Issue by sant527** [rg3/youtube-dl#10658]
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.11.1**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ X] Question
- [ ] Other

i am trying to download the live video from youtube.

the link is https://www.youtube.com/watch?v=KJS2JyQZowo

I am trying the following command:

youtube-dl -f 91 --postprocessor-args '-movflags faststart' "https://www.youtube.com/watch?v=KJS2JyQZowo"

Its downloading the file named: Lalbaugcha Raja LIVE Visarjan Sohala 2016-KJS2JyQZowo.mp4.part

if  i open it with mpv it says:

santhosh % mpv "Lalbaugcha Raja LIVE Visarjan Sohala 2016-KJS2JyQZowo.mp4.part"
Playing: Lalbaugcha Raja LIVE Visarjan Sohala 2016-KJS2JyQZowo.mp4.part
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
Failed to recognize file format.

Exiting... (Errors when loading file)

So how long i have to wait to watch the live video. Or can i start playing as it is keep downloading

**Comment by yan12125** [comment]
Could you try to download with ```--hls-use-mpegts```?

**Comment by sant527** [comment]
can you give me the full command. i dont know about --hls-use-mpegts. even in google i couldnt find

**Comment by yan12125** [comment]
Like this:
```
youtube-dl -f 91 --hls-use-mpegts "https://www.youtube.com/watch?v=KJS2JyQZowo"
```

**Comment by yan12125** [comment]
I'm closing this ticket as the command work for other live streams. Feel free to ask if there are still problems.
