### ISSUE TITLE
--recode-video argument affecting audio files

### ISSUE THREAD

**Issue by Saklad5** [rg3/youtube-dl#10652]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.11.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I’ve **verified** and **I assure** that I'm running youtube-dl **2016.09.11.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
---
---

### Description of your *issue*, suggested solution and other information

I use the argument “--recode-video mp4” in my config, as I prefer the format’s portability. However, I have noticed that this flag actually results in music (i.e. Bandcamp) being converted to MP4 as well, despite having no video file. I assume this behavior isn’t intended, judging by the argument itself. Could you modify the argument’s functionality to only affect something with a video component?

**Comment by dstftw** [comment]
That is expected behavior. Option name is most likely a remnant of the old times where no audio-only extractors existed. No, we won't change it in order not to break backward compatibility.

**Comment by Saklad5** [comment]
Could you add anything that would solve the problem I described, then?
