### ISSUE TITLE
[kuwo:song] unable to extract singer name, album id

### ISSUE THREAD

**Issue by stepshal** [rg3/youtube-dl#10650]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.11.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.11.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[kuwo:song] 635632: Download song detail info
WARNING: unable to extract singer name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[kuwo:song] 635632: Download ape url info
[kuwo:song] 635632: Download mp3-320 url info
[kuwo:song] 635632: Download mp3-192 url info
[kuwo:song] 635632: Download mp3-128 url info
[kuwo:song] 635632: Download wma url info
[kuwo:song] 635632: Download aac url info
WARNING: unable to extract album id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Invoking downloader on 'http://other.web.ra01.sycdn.kuwo.cn/382fc6e0fd7b8dfefca46efaad4aa3d0/57d977e6/resource/m2/firstApe/27/7/1926694376.ape'
[download] 好音质 用酷我-635632.ape has already been downloaded
[download] 100% of 29.87MiB
```
http://www.kuwo.cn/yinyue/635632/

**Comment by yan12125** [comment]
Thanks. Actually http://www.kuwo.cn/yinyue/635632/ is removed. In browsers it redirects to http://www.kuwo.cn/. I've added more codes to detect such cases.
