### ISSUE TITLE
[Openload.co] - The file download always lower than 32MB?

### ISSUE THREAD

**Issue by okgame** [rg3/youtube-dl#10656]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.11.1**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[root@li872-81 ~]# youtube-dl -o test.mp4 https://openload.co/f/p7ROawY_8Pk/WHX-012-720-FINAL.mp4 -v;
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-o', u'test.mp4', u'https://openload.co/f/p7ROawY_8Pk/WHX-012-720-FINAL.mp4', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.11.1
[debug] Python version 2.7.5 - Linux-4.6.5-x86_64-linode71-x86_64-with-centos-7.1.1503-Core
[debug] exe versions: none
[debug] Proxy map: {}
[Openload] p7ROawY_8Pk: Downloading webpage
[debug] Invoking downloader on u'https://openload.co/stream/p7ROawY_8Pk~1473988689~2400:8901::~ZjBqBxG[?mime=true'
[download] Destination: test.mp4
[download] 100% of 31.86MiB in 00:22
[root@li872-81 ~]#


---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://openload.co/f/p7ROawY_8Pk/WHX-012-720-FINAL.mp4
- Single video: https://openload.co/embed/p7ROawY_8Pk/


---

### Description of your *issue*, suggested solution and other information

I have test download some openload video, but the file size always lower than 32mb.

**Comment by kasper93** [comment]
See https://github.com/rg3/youtube-dl/issues/10408

**Comment by yan12125** [comment]
Thanks you @kasper93.
