### ISSUE TITLE
Chrunchyroll Preview Clip

### ISSUE THREAD

**Issue by Daiskun** [rg3/youtube-dl#10655]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.11.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.11.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--sub-lang', 'esLA', '--verbose', '-o', '-', 'http://www.crunchyroll.com/rezero-starting-life-in-another-world-/episode-24-the-self-proclaimed-knight-and-the-greatest-knight-702447']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.09.11.1
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 702447: Downloading webpage
ERROR: Este es un clip de muestra. Para ver el video completo, inicie una prueba gratuita hoy!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\extractor\crunchyroll.py", line 295, in _real_extract
youtube_dl.utils.ExtractorError: Este es un clip de muestra. Para ver el video completo, inicie una prueba gratuita hoy!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description of your *issue*, suggested solution and other information

I'm trying to stream chunchyroll to mpc-hc but it always says that it's a preview clip. I tried with cookies, .netcr and manualy typing username and password giving always the same error

**Comment by anonyme02** [comment]
Exactly the same error since yesterday.

**Comment by NizarAloui** [comment]
Yes we have the same problem on crunchy , something has changed :)

**Comment by NizarAloui** [comment]
It seems that somerhing has changed in the login form. So when requesting a video the website seems to not recognize the account.

**Comment by Kojirosan** [comment]
Same, it's a login problem with youtube-dl

**Comment by acristobo** [comment]
Exactamente el mismo Error / El form login de Chrunchyroll fue cambiado el 13/09/2016 
(Exactly the same error / Crunchyroll... login form was changed on 13/09)
----------------------------------
 <script>
    $(function initializePage() {
      $('#login_form').validationManager(getValidationManagerOptions());
      $('#signup_form').validationManager(getValidationManagerOptions());
    });
  </script>
  
---------------------------------

**Comment by Kojirosan** [comment]
Just wait the update of the exe now ^^

**Comment by acristobo** [comment]
thanks
...now, waiting the update of the exe

**Comment by Daiskun** [comment]
Wow thanks. I'll wait then ^.^
