### ISSUE TITLE
Unable to download webpage: IncompleteRead

### ISSUE THREAD

**Issue by mengbingrock** [rg3/youtube-dl#10667]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.15**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
mengbing@mengbing-H55M-S2:~/Videos$ youtube-dl --proxy socks5://127.0.0.1:1080/ --verbose --dateafter now-1day https://www.youtube.com/user/schooloflifechannel
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--proxy', u'socks5://127.0.0.1:1080/', u'--verbose', u'--dateafter', u'now-1day', u'https://www.youtube.com/user/schooloflifechannel']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.15
[debug] Python version 2.7.6 - Linux-3.13.0-95-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.7, avprobe 11.7, ffmpeg N-81641-ga50ca6b, ffprobe N-81641-ga50ca6b
[debug] Proxy map: {u'http': u'socks5://127.0.0.1:1080/', u'https': u'socks5://127.0.0.1:1080/'}
[youtube:user] schooloflifechannel: Downloading channel page
[youtube:playlist] UU7IcJI8PUf5Z3zKxnZvTBog: Downloading webpage
[download] Downloading playlist: Uploads from The School of Life
[youtube:playlist] UU7IcJI8PUf5Z3zKxnZvTBog: Downloading page #1
[youtube:playlist] UU7IcJI8PUf5Z3zKxnZvTBog: Downloading page #2
[youtube:playlist] UU7IcJI8PUf5Z3zKxnZvTBog: Downloading page #3
[youtube:playlist] UU7IcJI8PUf5Z3zKxnZvTBog: Downloading page #4
[youtube:playlist] playlist Uploads from The School of Life: Downloading 380 videos
[download] Downloading video 1 of 380
[youtube] XwVJJYfEV1g: Downloading webpage
[youtube] XwVJJYfEV1g: Downloading video info webpage
[youtube] XwVJJYfEV1g: Extracting video information
[youtube] XwVJJYfEV1g: Downloading MPD manifest
[download] 2016-09-14 upload date is not in range 2016-09-15 - 9999-12-31
[download] Downloading video 2 of 380
[youtube] BY6bGhcnDDs: Downloading webpage
ERROR: Unable to download webpage: IncompleteRead(2905 bytes read, 1951 more expected) (caused by IncompleteRead(2905 bytes read, 1951 more expected)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 394, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 899, in http_response
    content = resp.read()
  File "/usr/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 549, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 618, in _read_chunked
    value.append(self._safe_read(chunk_left))
  File "/usr/lib/python2.7/httplib.py", line 666, in _safe_read
    raise IncompleteRead(''.join(s), amt)
<end of log>
```

---
mengbing@mengbing-H55M-S2:~/Videos$ youtube-dl -U
youtube-dl is up-to-date (2016.09.15)

### Description of your *issue*, suggested solution and other information

ERROR: Unable to download webpage: IncompleteRead(3453 bytes read, 731 more expected) (caused by IncompleteRead(3453 bytes read, 731 more expected)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This is most likely caused by your proxy.
