### ISSUE TITLE
[tou.tv] problem with authentication

### ISSUE THREAD

**Issue by oxidius2** [rg3/youtube-dl#10669]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Here's what I tried and the result I got:

Downloading free videos works fine, but I can<t manage to download restricted video, I tried to log in like this:
```
C:\youtube-dl.exe -o "C:\test.mp4" -u mysecretmail@x.com -p mysecretpass -f "(mp4,webm)bestvideo[height<=2160]+bestaudio/best[height<=2160]" http://ici.tou.tv/catherine/S01E01?lectureauto=1
[tou.tv] catherine/S01E01: Downloading JSON metadata
[radiocanada] 112213: Downloading ipad XML
ERROR: radiocanada said: Le contenu sélectionné est  disponible seulement en premium
```

I then tried login in in chrome, exporting cookies and using them, but still no luck:

```
C:\youtube-dl.exe -o "C:\test.mp4" --cookies "C:\cookies.txt" -f "(mp4,webm)bestvideo[height<=2160]+bestaudio/best[height<=2160]" http://ici.tou.tv/catherine/S01E01?lectureauto=1
[tou.tv] catherine/S01E01: Downloading JSON metadata
[radiocanada] 112213: Downloading ipad XML
ERROR: radiocanada said: Le contenu sélectionné est  disponible seulement en premium
```

Someone has an idea how I could manage to download "premium" content?

I found youtube-dl only this morning so I'm sorry if I'm not asking support the right way.

**Comment by oxidius2** [comment]
I just saw the "account-needed", I could provide my account info if it is needed.

**Comment by remitamine** [comment]
if you want me to work on it, you can contact me at remitamine[at]gmail[dot]com.

**Comment by remitamine** [comment]
will be supported in the next version.

**Comment by MonsieurClavet** [comment]
running version 2016.06.25 on Debian seems to be broken now, i also have a premium account if you need.

`youtube-dl http://ici.tou.tv/mes-petits-malheurs/S01E06`
`[generic] S01E06: Requesting header`
`WARNING: Falling back on generic information extractor.`
`[generic] S01E06: Downloading webpage`
`[generic] S01E06: Extracting information`
`[redirect] Following redirect to http://ici.tou.tv/non-supportes.html`

**Comment by remitamine** [comment]
@MonsieurClavet, you are using an outdated version of youtube-dl. Read this FAQ entry if you have troubles updating.

**Comment by MonsieurClavet** [comment]
@remitamine sorry about that, i did updated it with APT. i removed it and it's flawless.  sorry again !
