### ISSUE TITLE
youtube-dl Crunchyroll ERROR: No video formats found!;

### ISSUE THREAD

**Issue by alexfernandojs** [rg3/youtube-dl#10665]
youtube-dl Crunchyroll ERROR: No video formats found!;

ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

ALL VIDEOS 
THANKS

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
