### ISSUE TITLE
Unable to download videos from Dorkly.com.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#10677]
$ youtube-dl -v http://www.dorkly.com/video/80646/super-mario-undertale
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.dorkly.com/video/80646/super-mario-undertale']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.15
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
[debug] exe versions: ffmpeg 3.0.2-4, ffprobe 3.0.2-4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] super-mario-undertale: Requesting header
WARNING: Falling back on generic information extractor.
[generic] super-mario-undertale: Downloading webpage
[generic] super-mario-undertale: Extracting information
[generic] 80646: Requesting header
WARNING: Could not send HEAD request to https://www.dorkly.com/e/80646: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[generic] 80646: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 394, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 473, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/home/ant/bin/youtube-dl/youtube_dl/utils.py", line 1011, in https_open
    req, **kwargs)
  File "/usr/lib/python3.4/urllib/request.py", line 1176, in do_open
    raise URLError(err)

--

$  youtube-dl -v http://www.dorkly.com/video/80646/super-m                                         ario-undertale
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.dorkly.com/video/80646/super-mar                                         io-undertale']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.15
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
[debug] exe versions: ffmpeg 3.0.2-4, ffprobe 3.0.2-4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] super-mario-undertale: Requesting header
WARNING: Falling back on generic information extractor.
[generic] super-mario-undertale: Downloading webpage
[generic] super-mario-undertale: Extracting information
[generic] 80646: Requesting header
WARNING: Could not send HEAD request to https://www.dorkly.com/e/80646: <urlopen                                          error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
[generic] 80646: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILE                                         D] certificate verify failed (_ssl.c:581)> (caused by URLError(SSLError(1, u'[SS                                         L: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 394, in _                                         request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/ant/bin/youtube-dl/youtube_dl/utils.py", line 1011, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)

--

Thank you in advance. :)

**Comment by yan12125** [comment]
It's a bug of Dorkly.com. Use ```--no-check-certificate``` before they've fixed it:
```
youtube-dl -v --no-check-certificate http://www.dorkly.com/video/80646/super-mario-undertale
```
If anyone is going to report a bug to Dorkly.com, tell them their SSL certificate should contain the full certificate chain.

**Comment by antdude** [comment]
Thank you Yan12125. I sent an e-mail to general@dorkly.com. :)
