### ISSUE TITLE
CrunchyRoll is not showing HD and FHD streams

### ISSUE THREAD

**Issue by SaikyoKid** [rg3/youtube-dl#10671]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.15**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
YTDL>youtube-dl.exe --verbose "http://www.crunchyroll.com/naruto-shippuden/episode-475-the-final-valley-716127" -F -u myEmail -p myPassword
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.crunchyroll.com/naruto-shippuden/episode-475-the-final-valley-716127', '-F', '-u', 'PRIVATE', '-p', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.09.11.1
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-80906-gd5edb6c, rtmpdump 2.5
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 716127: Downloading webpage
[Crunchyroll] 716127: Downloading media info for 360p
[Crunchyroll] 716127: Downloading m3u8 information
[Crunchyroll] 716127: Downloading media info for 480p
[Crunchyroll] 716127: Downloading m3u8 information
[Crunchyroll] 716127: Downloading media info
[info] Available formats for 716127:
format code  extension  resolution note
hls-meta-0   mp4        multiple   Quality selection URL
hls-meta-1   mp4        multiple   Quality selection URL
hls-566      mp4        640x360     566k , avc1.4d001e, mp4a.40.2
hls-810      mp4        848x480     810k , avc1.4d001e, mp4a.40.2 (best)
...
<end of log>
```

---

---

### Description of your *issue*, suggested solution and other information

I used this Command :
```
youtube-dl.exe --verbose "http://www.crunchyroll.com/naruto-shippuden/episode-475-the-final-valley-716127" -F -u myEmail -p myPassword
```

I've been using this command for a long time and it has been working just fine, expect since this morning. Crunchyroll is showing only HLS steams now and till only 480p.
Yes, my logins are correct and I triple checked it by logging in via my browser manually, which worked just fine. And yes, I am a premium member. I can play 1080p videos in my browser just fine.
But, youtube-dl won't show me anything above 480p.

I tried to check if it is actually logging in or not, so I gave the wrong password to check it. It did not show that login was wrong or anything. Which is weird.

**Comment by Xonshiz** [comment]
Your youtube-dl version says `2016.09.11.1`. Update it and it'll work.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
