### ISSUE TITLE
Can't get a full title in ThisAV

### ISSUE THREAD

**Issue by uosen123** [rg3/youtube-dl#10682]
Thank you for a good app.

youtube-dl can't get a full title from ThisAV. For example,
youtube-dl --get-title "http://www.thisav.com/video/41336/%E5%88%B0%E5%A5%B3%E5%90%8C%E5%AD%B8%E5%AE%B6%E9%81%8E%E5%A4%9C%E5%B9%B9%E5%AE%8C%E5%A7%90%E5%A7%90%E5%B9%B9%E4%BA%8C%E5%A6%B9%E5%B9%B9%E5%AE%8C%E4%BA%8C%E5%A6%B9%E5%86%8D%E5%B9%B9%E4%B8%89%E5%A6%B9%E9%81%AD%E4%BA%86%E8%A2%AB%E5%A5%B9%E5%AA%BD%E7%99%BC%E7%8F%BE%E4%BA%86.html"
到女同學家過夜,幹完姐姐幹二妹,幹...

The full title is 到女同學家過夜,幹完姐姐幹二妹,幹完二妹再幹三妹,遭了,被她媽發現了. Namely, youtube-dl get a shorten title.
This is because youtube-dl seaeches `<h1>XXX</h1>` in html source.

To get a full title, it needs to search `<title>XXX</title>` and delete  - 視頻 - ThisAV.com-世界第一中文成人娛樂網站.
In line 29 of youtube-dl/blob/master/youtube_dl/extractor/thisav.py, it is needed to change from
`title = self._html_search_regex(r'<h1>([^<]*)</h1>',`
to
`title = self._html_search_regex(r'<title>([^<]*) - 視頻 - ThisAV.com-世界第一中文成人娛樂網站</title>',`
.

**Comment by uosen123** [comment]
Sorry for the bad presentation. I don't well understand the description of code in this site.
Can you understand the above report?

**Comment by yan12125** [comment]
I know. I understand Chinese, too ;)

**Comment by yan12125** [comment]
Well, this video looks like a copyrighted product. Do you have other examples?

**Comment by yan12125** [comment]
I've fixed it anyway as other legal videos may be affected as well. Thanks for the report!

**Comment by uosen123** [comment]
Sorry for using a copyrighted product.
I couldn't have judged. It is difficult.
But I agree with your policy. I have deleted the link.
