### ISSUE TITLE
openload bug 

### ISSUE THREAD

**Issue by daniel100097** [rg3/youtube-dl#10685]
youtube-dl "url"
[Openload] vP0pfAjlwM0: Downloading webpage
[download] Resuming download at byte 523264
[download] Destination: tvs-izombie-dd51-ded-dl-7p-ithd-avc-101.mkv.mp4-vP0pfAjl
[download] 100% of 31.86MiB in 00:19

output openload video with "website youre watching..."

**Comment by dstftw** [comment]
Duplicate of #10408.
