### ISSUE TITLE
crunchyroll premuim videos can't download 

### ISSUE THREAD

**Issue by asdirmoad** [rg3/youtube-dl#10680]
[Crunchyroll] 715673: Downloading webpage
ERROR: This is a sample clip. To watch the full video, start a free trial today!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

plz fix

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
