### ISSUE TITLE
Support website of output file name

### ISSUE THREAD

**Issue by uosen123** [rg3/youtube-dl#10683]
We can use much data in output names, where we can't use what website names.
But, youtube-dl has the data
[youtube] tdwbYGe8pv8: Downloading webpage
[youtube] tdwbYGe8pv8: Downloading video info webpage
from the below log.
youtube!! if generic,  website name scan be able to get from domain names. 
In most of websites, we can get them with 
https?//([-a-zA-Z0-9]+)backslash.[-a-zA-Z0-9]+/.*
or
https?//[-a-zA-Z0-9]+backslash.([-a-zA-Z0-9]+)(backslash.([-a-zA-Z0-9]+){1,2}/.*
.

I re

youtube-dl -F https://www.youtube.com/watch?v=tdwbYGe8pv8
[youtube] tdwbYGe8pv8: Downloading webpage
[youtube] tdwbYGe8pv8: Downloading video info webpage
[youtube] tdwbYGe8pv8: Extracting video information
[youtube] tdwbYGe8pv8: Downloading MPD manifest
[info] Available formats for tdwbYGe8pv8:
format code  extension  resolution note
249          webm       audio only DASH audio   56k , opus @ 50k (48000Hz), 4.46MiB
250          webm       audio only DASH audio   82k , opus @ 70k (48000Hz), 5.92MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k (44100Hz), 11.26MiB
171          webm       audio only DASH audio  138k , vorbis@128k (44100Hz), 10.98MiB
251          webm       audio only DASH audio  158k , opus @160k (48000Hz), 11.64MiB
278          webm       256x144    DASH video  122k , webm container, vp9, 24fps, video only, 8.66MiB
160          mp4        256x144    DASH video  151k , avc1.4d400c, 24fps, video only, 9.76MiB
133          mp4        426x240    DASH video  266k , avc1.4d4015, 24fps, video only, 21.75MiB
242          webm       426x240    DASH video  298k , vp9, 24fps, video only, 19.82MiB
243          webm       640x360    DASH video  529k , vp9, 24fps, video only, 36.71MiB
134          mp4        640x360    DASH video  663k , avc1.4d401e, 24fps, video only, 51.61MiB
244          webm       854x480    DASH video  981k , vp9, 24fps, video only, 67.25MiB
135          mp4        854x480    DASH video 1210k , avc1.4d401e, 24fps, video only, 96.74MiB
247          webm       1280x720   DASH video 1927k , vp9, 24fps, video only, 133.91MiB
136          mp4        1280x720   DASH video 2397k , avc1.4d401f, 24fps, video only, 190.68MiB
248          webm       1920x1080  DASH video 3924k , vp9, 24fps, video only, 236.00MiB
137          mp4        1920x1080  DASH video 4494k , avc1.640028, 24fps, video only, 354.02MiB
264          mp4        2560x1440  DASH video 10780k , avc1.640032, 24fps, video only, 829.57MiB
271          webm       2560x1440  DASH video 12298k , vp9, 24fps, video only, 759.31MiB
313          webm       3840x2160  DASH video 22654k , vp9, 24fps, video only, 1.53GiB
266          mp4        3840x2160  DASH video 23446k , avc1.640033, 24fps, video only, 1.82GiB
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3,  mp4a.40.2
43           webm       640x360    medium , vp8.0,  vorbis@128k
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)

**Comment by dstftw** [comment]
So you want domain name of the input URL in downloaded file's name or what?

**Comment by uosen123** [comment]
I want the name of a web site on an output name.
Now we can't recognize what website a video is downloaded from by an output name. 
For example, title-id-website.ext.

**Comment by dstftw** [comment]
Use `%(extractor)s` or `%(extractor_key)s`.
