### ISSUE TITLE
_VERY IMPORTANT SITE REQUEST, today only!!! : VYBORY.MOS.RU

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#10692]
Hello everyone!
Now I want you to take **precise and rapid attention** and make YOUTUBE-DL compatible with **_one day working_** video feed site dedicated to Moscow Gosduma elections **_today_**:

http://vybory.mos.ru/#precinct/13636

To those ppl in team who can read Russian, please follow this URL which explains how to operate with those chunks in that feed here, the info actual for 2013: https://habrahabr.ru/post/192590/

AND this url, actual for 2012: https://geektimes.ru/post/139292/

Both of those URLs explaining not only how to take current feed, but how to take _period_ (how many minutes/hours) and _time_ (when video was taken) of this video feed.

I'll be **VERY grateful** if someone will pay attention on this issue and make such great addon to YOUTUBEL-DL before/upto **14:00-15:00 MSK (UTC+03/GMT+03)**.

**Comment by yan12125** [comment]
The two videos can be downloaded with the following two commands: (With ffmpeg installed)
```
youtube-dl -v --hls-use-mpegts -o "camera1.%(ext)s" "http://188.254.112.20/master.m3u8?sid=921dab20-6569-11e6-b736-002590718f7e"
youtube-dl -v --hls-use-mpegts -o "camera2.%(ext)s" "http://188.254.112.50/master.m3u8?sid=921dde2e-6569-11e6-b736-002590718f7e"
```

**Comment by nmr50** [comment]
yan12125: VERY NICE OF YOU to show Your KNOWLEDGE, THANKS !!!:)

Now I have another Q that is not closely related to YOUTUBE-DL but - please answer!:
I stuck in one process - getting list of all cameras and then add tokens (sid=) for them.
If YOUTUBE-DL can get feed without problems "from scratch", and it does! - can someone explain to me how to 1) get all cameras list in batch mode, 2) get all tokens related to those cameras - like the same you got token for the 1st posted videofeed ? 

Thank in advance !

**Comment by yan12125** [comment]
I got these URLs by capturing network traffic in Firefox. You may also want to have a look at the newly added extractor in 14ae11efab64baf4994688490474609554c1bf80.

**Comment by nmr50** [comment]
Yep, I've looked at 14ae11e and found that YOUTUBE-DL will now know **only one place with two cameras**, related to **one voting place**.
Yan12125, what about adding very nice feature to get list of ALL cameras, with addresses, and URLs with tokens, the same it works for video formats from one place-F ?
Example: yotube-dl  -F http://vybory.mos.ru/json/id_search > cameras.list.urls
where 1st field will be token and 2nd field will be voting place address ?
Or even more - to generate complete URL with youtube-dl like you did - with token - at 1st field, the second will be voting place address ?

This one is not rapid to be added, of course, but - can it be done ?:)
THANKS in advance!:)

**Comment by dstftw** [comment]
That's out of scope of youtube-dl.

**Comment by nmr50** [comment]
But this option is a close mirror of -F because it lists all available addresses with tokens like -F lists all available formats from one place.. why not ?:/

**Comment by yan12125** [comment]
First you need a list of all voting places. youtube-dl can't imagine it from nowhere.

**Comment by nmr50** [comment]
yan12125: I pulled this question to the pal of mine, so I hope I'll get this voting places scanner soon.
One Q is left: please tell me, what exact name of network capture plugin for FF you've used to get that SID, whole url ? Thanks in advance!

**Comment by dstftw** [comment]
Ctrl+Shift+Q. No plugin is needed.
