### ISSUE TITLE
[Funimation] No resolution shows up for any stream & direct links missing

### ISSUE THREAD

**Issue by Xonshiz** [rg3/youtube-dl#10696]
---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.09.18_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.18**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
E:\Youtube-DL>youtube-dl "http://www.funimation.com/shows/first-love-monster/videos/official/a-proper-rom-com-for-once" -F -u MyEmail -p MyPassword --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.funimation.com/shows/first-love-monster/
videos/official/a-proper-rom-com-for-once', '-F', '-u', 'PRIVATE', '-p', 'PRIVAT
E', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.09.18
[debug] Python version 3.4.4 - Windows-2012ServerR2-6.3.9600
[debug] exe versions: ffmpeg N-80906-gd5edb6c, rtmpdump 2.5
[debug] Proxy map: {}
[Funimation] Logging in as MYEMAILIDHERE
[Funimation] a-proper-rom-com-for-once: Downloading webpage
[Funimation] a-proper-rom-com-for-once: Downloading m3u8 information
[Funimation] a-proper-rom-com-for-once: Downloading m3u8 information
[Funimation] a-proper-rom-com-for-once: Downloading m3u8 information
[Funimation] a-proper-rom-com-for-once: Downloading m3u8 information
[Funimation] a-proper-rom-com-for-once: Downloading m3u8 information
[Funimation] a-proper-rom-com-for-once: Downloading m3u8 information
[info] Available formats for 34021:
format code                  extension  resolution note
FLMJPNocVsaW0010-hls-meta-0  mp4        multiple   Quality selection URL
FLMJPNocVsaW0010-hls-meta-1  mp4        multiple   Quality selection URL
FLMJPNocVsaW0010-hls-meta-2  mp4        multiple   Quality selection URL
FLMENG7V9ist0010-hls-meta-0  mp4        multiple   Quality selection URL
FLMENG7V9ist0010-hls-meta-1  mp4        multiple   Quality selection URL
FLMENG7V9ist0010-hls-meta-2  mp4        multiple   Quality selection URL
FLMJPNocVsaW0010-hls-750-0   mp4        unknown     750k
FLMJPNocVsaW0010-hls-750-1   mp4        unknown     750k
FLMJPNocVsaW0010-hls-750-2   mp4        unknown     750k
FLMJPNocVsaW0010-hls-1500-0  mp4        unknown    1500k
FLMJPNocVsaW0010-hls-1500-1  mp4        unknown    1500k
FLMJPNocVsaW0010-hls-1500-2  mp4        unknown    1500k
FLMJPNocVsaW0010-hls-2000-0  mp4        unknown    2000k
FLMJPNocVsaW0010-hls-2000-1  mp4        unknown    2000k
FLMJPNocVsaW0010-hls-2500-0  mp4        unknown    2500k
FLMJPNocVsaW0010-hls-2500-1  mp4        unknown    2500k
FLMJPNocVsaW0010-hls-4000    mp4        unknown    4000k
FLMENG7V9ist0010-hls-750-0   mp4        unknown     750k
FLMENG7V9ist0010-hls-750-1   mp4        unknown     750k
FLMENG7V9ist0010-hls-750-2   mp4        unknown     750k
FLMENG7V9ist0010-hls-1500-0  mp4        unknown    1500k
FLMENG7V9ist0010-hls-1500-1  mp4        unknown    1500k
FLMENG7V9ist0010-hls-1500-2  mp4        unknown    1500k
FLMENG7V9ist0010-hls-2000-0  mp4        unknown    2000k
FLMENG7V9ist0010-hls-2000-1  mp4        unknown    2000k
FLMENG7V9ist0010-hls-2500-0  mp4        unknown    2500k
FLMENG7V9ist0010-hls-2500-1  mp4        unknown    2500k
FLMENG7V9ist0010-hls-4000    mp4        unknown    4000k  (best)
```

---

---
### Description of your _issue_, suggested solution and other information

Youtube-dl isn't showing the `Resolution` for any of the Funimation streams. I've tried on multiple videos and it just shows `Unknown`. I know I can see the `format code` to determine the Audio and the bitrate depicts the stream resolution. But, it kinda bugs me to see this.

Another thing I'd like to know is that why is youtube-dl using `hls` stream only? I mean, funimation provides a DDL link. Why not use that as well?

And another thing is that as you can see there are two format codes for the same resolution and language. For example : `FLMENG7V9ist0010-hls-2500-0` and `FLMENG7V9ist0010-hls-2500-1`, I downloaded both of them to check the difference... there was none.

If you need a raw script to fetch the DDL, I can put it up on pastebin or somewhere and maybe some one can merge it?

I'll leave some example URLs to replicate the issue : 
http://www.funimation.com/shows/first-love-monster/videos/official/a-proper-rom-com-for-once

http://www.funimation.com/shows/handa-kun/videos/official/handa-kun-and-the-cultural-festival-preparations

http://www.funimation.com/shows/saikik/videos/official/industry-leading-top-ranking-company-father-s-job

**Comment by Xonshiz** [comment]
BTW, you can still download the SD streams without an account. All you need is a US Proxy/VPN/Location. It won't show stream resolution in any case.

**Comment by dstftw** [comment]
No resolution info is provided in m3u8.

**Comment by dstftw** [comment]
Direct links are not extracted due to [this](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/funimation.py#L145). Don't know what is the rationale but it works fine without it for me. Ping @yan12125.

**Comment by yan12125** [comment]
When I was writing that patch, Funimation required the browser that generated the cookie matched the browser used to download the webpage. Now the patch is no longer necessary. You can revert it if it brings new problems.

**Comment by Xonshiz** [comment]
Ah, that cloudflare would pose problem. But, even if you used that cookie you generated from your browser and added to yt-dl for funimation to work, it still won't download the file either way, right? or the m3u8 is fetched irrespective of geo-location?

**Comment by yan12125** [comment]
Yes videos now require an US IP. Cookies are irrelevant now.

**Comment by yan12125** [comment]
Yeah I got the same results. I mean: to download a video, an US IP is always necessary. (I'm not sure for this, only a few videos tested) In this case cookies are no longer necessary. It's good that youtube-dl tells users precise error messages, but not good if some features like direct mp4 links are broken.

**Comment by Xonshiz** [comment]
Cookies have been irrelevat for a long time. Once you solve that reCaptcha, Funimaion will let you browse their site, view all the anime information of any anime they stream. But, to be able to watch, you need a US IP. It is with every video, no exception.

As long as you have a US IP, you can download any stream from Funimation. Even the 720p and 1080p streams. I wrote something for it, I'll post later, you might be able to do something with that?

Besides, Direct links are available for every video funimation has and they show the resolution as well.

And there are certain shows that Funimation streams via HULU. I'll test youtube-dl and my script on those, just to see what happens.

**Comment by Xonshiz** [comment]
Found the script : https://gist.github.com/Xonshiz/93b2841ffc77b19bdf15d7e486e9d50e

Wrote this about 2-3 months ago or so. This is downloading just 1080p streams. You can tailor it to download others.

I've used 'PhantomJS' to open Funimation and fetch the 'source code' of the page.

There's an explanation from line 87 to 96, take a look at that explanation.

**Comment by Xonshiz** [comment]
There is something that you'll need to take care of actually.

Some shows have both, the "Dub Version" and "Sub Version". You'll have to fetch the FunimationID for both of them seperately. Because `FunimationID` will be different for both the languages.

Example Link : http://www.funimation.com/shows/handa-kun/videos/official/handa-kun-and-a-girls-friendship

**Comment by matoro** [comment]
Just to tack onto this - why does youtube-dl download the 480p video by default, instead of the 1080p one?  Using the -F flag also does not even list 1080p, however simply replacing the 1500k in the url with 4000k generates a valid link for the 1080p video.
