### ISSUE TITLE
ERROR: requested format not available[x]

### ISSUE THREAD

**Issue by Luxios** [rg3/youtube-dl#10695]
C:\Users\xxx>youtube-dl -f https://www.youtube.com/watch?v=fLe_qO4AE-M
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

C:\Users\xxx>youtube-dl -f url https://www.youtube.com/watch?v=fLe_qO4AE-M
[youtube] fLe_qO4AE-M: Downloading webpage
[youtube] fLe_qO4AE-M: Downloading video info webpage
[youtube] fLe_qO4AE-M: Extracting video information
[youtube] fLe_qO4AE-M: Downloading MPD manifest
ERROR: requested format not available

My network works well.Why does it happen?

**Comment by dstftw** [comment]
Either provide correct argument to `-f` or remove it completely:
```
youtube-dl https://www.youtube.com/watch?v=fLe_qO4AE-M
```
