### ISSUE TITLE
Add support for Adobe Pass Auth provider watchtveverywhere.com

### ISSUE THREAD

**Issue by jdunn0** [rg3/youtube-dl#10709]
I saw that youtube-dl has support for Adobe Pass Auth and it currently supports DirecTV and Rodgers Cable.
My ISP is [Wave Broadband](http://www.wavebroadband.com) and the Auth provider they use is [watchtveverywhere.com](http://watchtveverywhere.com).
It would be nice to have support for watchtveverywhere.com in youtube-dl so I could download videos that require it.
As shown on the home page for watchtveverywhere.com, it appears many other ISPs use it too so depending on how it works, one provider for watchtveverywhere.com could work for more then just Wave Broadband.
I tested my theory that a watchtveverywhere.com account works for any ISP that works with them by going to truTV.com and saying my ISP was "3 Rivers Communications".
Just like when I tell it my ISP is Wave, I got the login screen for watchtveverywhere.com and the truTV video loaded. The only difference is that the truTV web site showed a logo for "3 Rivers Communications" instead of Wave.
I can provide my watchtveverywhere.com login info to help with this if needed.

**Comment by remitamine** [comment]
> I can provide my watchtveverywhere.com login info to help with this if needed.

if you want me to work on it, you can contact me at remitamine[at]gmail[dot]com.

**Comment by remitamine** [comment]
will be supported in the next version.
