### ISSUE TITLE
when dowloading from mva.microsoft it just download the first vedeo in the series

### ISSUE THREAD

**Issue by MoHD20** [rg3/youtube-dl#10701]
### What is the purpose of your *issue*?
Bug report (encountered problems with youtube-dl)

### Description of your *issue*, suggested solution and other information
when I tried to  download a course from mva it just download the first course of the series
the command I used is :
youtube-dl -f 540p --all-subs  https://mva.microsoft.com/en-US/training-courses/cloud-at-microsoft-12099?l=UwIcB60HB_1605193246

the result was that it just downloaded the Introduction!

**Comment by dstftw** [comment]
To download complete course you must use course URL https://mva.microsoft.com/en-US/training-courses/cloud-at-microsoft-12099 not single video.

**Comment by amrboxit4me** [comment]
@dstftw  what do you use to make course name folder/ chapter1 / 1.title.mp4 ?
because 
-Output %(playlist)s/%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s not work fine to MVA

it works for me except **chapter_number** is not in the json so it make NA
