### ISSUE TITLE
Site Request: Beam.pro 

### ISSUE THREAD

**Issue by yopalien** [rg3/youtube-dl#10702]
https://beam.pro/

It's a videogame streaming site recently bought by Microsoft. VODs and livestream download would be great.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by dear-reader** [comment]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.02**
```
$ youtube-dl --version
2016.10.02
```
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### VERBOSE OUTPUT LOG
```
$ youtube-dl -v https://beam.pro/marux
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://beam.pro/marux']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.10.02
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81462-gbcd1153, ffprobe N-81462-gbcd1153
[debug] Proxy map: {}
[generic] marux: Requesting header
WARNING: Falling back on generic information extractor.
[generic] marux: Downloading webpage
[generic] marux: Extracting information
ERROR: Unsupported URL: https://beam.pro/marux
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmbxreb                                                                             nz\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmbxreb                                                                             nz\build\youtube_dl\extractor\common.py", line 355, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmbxreb                                                                             nz\build\youtube_dl\extractor\generic.py", line 2432, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://beam.pro/marux

...
<end of log>
```

---

### EXAMPLE URLS
- Channel stream: https://beam.pro/marux
- Channel recording: https://beam.pro/esperterra?vod=362163

---

### DESCRIPTION

I'm requesting site support for https://beam.pro

Beam is a general purpose video streaming site, much like Twitch. It allows you to watch live streamed video and recordings of previous streams. 

Caveat: Not all Beam streams are streamed in the same way, some use their proprietary protocol (?) called FTL. In their own words `FTL is our brand new streaming protocol that allows for sub-second video latency when streaming`. I'm not sure if this will need special consideration or if it works like the normal streams for the purposes of youtube-dl. If it's an insurmountable problem for some reason, leaving it unsupported would still be better than having no support for the site at all.

**Comment by yan12125** [comment]
From what I can tell this site uses WebSocket to transfer video frames. It's not supported in youtube-dl yet.

**Comment by shizeeg** [comment]
Kudos to @dstftw Great Job!

**Comment by voltagex** [comment]
Additional log with a current VOD.

```
PS C:\Users\Adam\Videos> youtube-dl.exe -vvv https://beam.pro/ForzaMotorsport?vod=2334608
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vvv', 'https://beam.pro/ForzaMotorsport?vod=2334608']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.07
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-82836-g0022313, ffprobe N-82836-g0022313
[debug] Proxy map: {}
[Beam:live] ForzaMotorsport: Downloading JSON metadata
ERROR: ForzaMotorsport is offline
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpt73_83v_\build\youtube_dl\YoutubeDL.py", line 760,
in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpt73_83v_\build\youtube_dl\extractor\common.py", lin
e 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpt73_83v_\build\youtube_dl\extractor\beampro.py", li
ne 49, in _real_extract
youtube_dl.utils.ExtractorError: ForzaMotorsport is offline
```
