### ISSUE TITLE
Always get suspended when run youtube-dl in background

### ISSUE THREAD

**Issue by cxbig** [rg3/youtube-dl#10706]
I found that I have no way to run `youtube-dl` in background.
I tried all possible options to make it running in silence. But I still get 'suspended' job: 
```sh
% stty -tostop && youtube-dl -q -i --no-warnings -o '%(id)s.%(ext)s'  $video_url >/dev/null 2>&1 &
[1] 53435
%
[1]  + 53435 suspended (tty output)  youtube-dl -q -i --no-warnings -o '%(id)s.%(ext)s'  > /dev/null 2>&1
```

Local env
```
[debug] youtube-dl version 2016.08.10
[debug] Python version 2.7.12 - Darwin-15.6.0-x86_64-i386-64bit
```

**Comment by jdunn0** [comment]
How are you launching youtube-dl? From a shell or inside a shell script?

**Comment by yan12125** [comment]
A workaround:

* Create ```~/ffmpeg_wrapper.sh``` with the following contents:
```
#!/bin/bash
ffmpeg -d $*
```
* ```youtube-dl -o '%(id)s.%(ext)s' --ffmpeg-location ~/tmp/ffmpeg_wrapper.sh $video_url```

See https://github.com/FFmpeg/FFmpeg/blob/ae1dd0c/ffmpeg.c#L384 for what's broken and why ```-d``` works.

**Comment by yan12125** [comment]
Oops, there's something wrong in my previous post. I've updated it. Could you try again?

**Comment by cxbig** [comment]
@yan12125 Thanks, your solution is working well.

**Comment by yan12125** [comment]
Thanks for your feedback. I'll check whether including ```-d``` in youtube-dl is OK or not.

**Comment by yan12125** [comment]
Thanks to @johnhawkinson (#10996), this will be fixed in the next version.
