### ISSUE TITLE
Site request: CTC.RU (videomore.ru?)

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#10717]
Hello authors!
Thanks for quick and USEFUL reply on my request on 19sep, now I want to ask you to make YOUTUBE-DL compatible with CTC.RU site which is showing legal videos which I'd like to have on local storage rather than been playing on web page:
http://ctc.ru/projects/filmi/pyatyy-element/

Source code for this URL's html contain this, I think because videomore.ru is provider for CTC tv channel:
http://videomore.ru/module_player/VideoCore.swf?v=21&amp;autostart=true&amp;config=http%3A%2F%2Fvideomore.ru%2Fvideo%2Ftracks%2F373717.xml&amp;container=%2F%2Fvideomore.ru%2Fvideocontainer.swf&amp;share_url=http%3A%2F%2Fctc.ru%2Fprojects%2Ffilmi%2Fpyatyy-element%2F&amp;ui_url=%2F%2Fvideomore.ru%2Fmodule_player%2FUIMore.swf%3Fv%3D21&amp;url_ad=%2F%2Fvideomore.ru%2Fadvcontainer.swf%3Fv%3D21

Please notice that CTC/videomore offers three quality options, LQ, MQ, HQ (low, middle, high).
THANKS in advance!:)

**Comment by dstftw** [comment]
It's already covered by generic extractor.

**Comment by SlazE888** [comment]
> It's already covered by generic extractor.

I'm running youtube-dl version **2019.08.02**. I got this error logs:
**Verbose log**
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://ctc.ru/projects/filmi/ya_vse_esche_zdes/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.08.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] ya_vse_esche_zdes: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ya_vse_esche_zdes: Downloading webpage
[generic] ya_vse_esche_zdes: Extracting information
[videomore] 476830: Downloading video XML
ERROR: Could not find XML element video url
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\videomore.py", line 131, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\utils.py", line 1898, in xpath_text
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\utils.py", line 1891, in xpath_element
youtube_dl.utils.ExtractorError: Could not find XML element video url

**Comment by em92** [comment]
For those, who is planning to make plugin(?) for ctc.ru. Here is how it probably works:

1. Example: https://ctc.ru/projects/show/fort_boyard__vozvraschenie/video/1-sezon/7-vypusk/
2. In source code there is something like this:
```
<meta content="https://videomore.ru/embed/898093?skin_id=4&amp;share_url=https://ctc.ru/projects/show/fort_boyard__vozvraschenie/video/1-sezon/7-vypusk/" name="twitter:player" />
```
3. In `https://videomore.ru/embed/898093` you will have in json
```
https://videomore.ru/video/file/132bcd990e59bc35dbe8f360a0816c89/1573399466/888677.live
```
Which redirects to master.m3u8 url, which is good for `mpv + youtube-dl`
