### ISSUE TITLE
NHL - ERROR: unable to download video data

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#10713]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
>youtube-dl.py -v "https://www.nhl.com/predators/video/poile-laviolette-on-subban-trade/t-277437416/c-44315003"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.nhl.com/predators/video/poile-laviolette-on-subban-trade/t-277437416/c-44315003']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.09.19
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[nhl.com] 44315003: Downloading JSON metadata
[nhl.com] 44315003: Downloading m3u8 information
[nhl.com] 44315003: Downloading m3u8 information
[nhl.com] 44315003: Downloading m3u8 information
[nhl.com] 44315003: Downloading m3u8 information
[nhl.com] 44315003: Downloading m3u8 information
[nhl.com] 44315003: Downloading m3u8 information
[debug] Invoking downloader on 'http://md-akc.med.nhl.com/hls/nhl/2016/06/29/fc44f4d5-ff37-41ff-9845-23a7a4eca6a8/1467241107954/asset_5000k.m3u8'
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\common.py", line 354, in download
    return self.real_download(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\hls.py", line 61, in real_download
    manifest = self.ydl.urlopen(man_url).read()
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Program Files\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "C:\Program Files\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\Python35\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python35\lib\urllib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
...
<end of log>
```

---

---

### Description of your *issue*, suggested solution and other information

NHL extractor fails.

Thanks 
Ringo

**Comment by kaplanlior** [comment]
I'm not sure if that's an extractor fail, as the m3u8 files have info about 5000k files, while the HTML source only refers to 1800k files (the mp4 5000k files don't exist as shown in the 404 error above).

**Comment by yan12125** [comment]
Currently I check all formats one by one. If there's a better approach, please leave a comment here or open a new issue.
