### ISSUE TITLE
Problems with CSPAN video

### ISSUE THREAD

**Issue by AJVicens** [rg3/youtube-dl#10712]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.09.19_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.19**
### Before submitting an _issue_ make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
adminlocals-MacBook-Pro:Desktop avicens$ youtube-dl --verbose https://www.c-span.org/video/?c4620848/sen-warren-wells-fargo-ceo
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.c-span.org/video/?c4620848/sen-warren-wells-fargo-ceo']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.19
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[CSpan] c4620848: Downloading webpage
[CSpan] 4620848: Downloading JSON metadata
[CSpan] 4620848: Downloading XML
[download] Downloading playlist: Sen. Warren and Wells Fargo CEO
[CSpan] playlist Sen. Warren and Wells Fargo CEO: Collected 21 video ids (downloading 21 of them)
[download] Downloading video 1 of 21
[debug] Invoking downloader on u'https://media.c-spanvideo.org/dynamic/2016/09/20/20160920085928003_hd/20160920085928003_hd.MP4-M20.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9tZWRpYS5jLXNwYW52aWRlby5vcmcvZHluYW1pYy8yMDE2LzA5LzIwLzIwMTYwOTIwMDg1OTI4MDAzX2hkLzIwMTYwOTIwMDg1OTI4MDAzX2hkLk1QNC1NMjAubXA0IiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDc0NDAxMzkxfSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjIwNy44Ny4yMDguMjI2In19fV19&Key-Pair-Id=APKAIHKVWBEAXX562G7Q&Signature=aaFjeMQawt~YPWDxwE-HmgJEbSkyv4Jn7QPAJXcoqZVkqG5sN2yaFw2GO831dt0wQVRhdKABJH5MkB2ZwBbT26OIKsjjrqRjst20zQiB45HDX2~k1eN5dLeliO~qFzpMyiKHw6P1T5z3I5YyOofobjBOVf3C9ZmURLMhXEKAa68_'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 354, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---
### Description of your _issue_, suggested solution and other information

Hi, I see [you've addressed CSPAN videos](https://github.com/rg3/youtube-dl/issues/5302) (specifically ones hosted by the Senate) but I can't seem to get this to work on a user-generated clip (the one described above). Many apologies if this is operator error, but I was hoping you could take a look. Thank you.

**Comment by yan12125** [comment]
Downloading works  for me. Could you upload the output of the following command?
```
youtube-dl -v --dump-pages "https://www.c-span.org/video/?c4620848/sen-warren-wells-fargo-ceo"
```

**Comment by fnadde42** [comment]
With `Python version 2.7.6` I get an error but with `Python version 3.4.3` I can download. Seems like a Python problem.

A solution can be to download the lastest Python and running youtube-dl through that instead.

**Comment by yan12125** [comment]
It's suggested to use 2.7.9 or above - 2.7.6 is way too old. There are lots of significant network-related improvements in 2.7.9.
Feel free to open a new issue if you found the latest 2.7 (2.7.13) is broken for some videos.
