### ISSUE TITLE
Fix openload.co

### ISSUE THREAD

**Issue by daniel100097** [rg3/youtube-dl#10727]
code fix for openload.co resolv
http://hastebin.com/femivusima.py

parts of the code can be use in youtube-dl

**Comment by yan12125** [comment]
Are you the original author of this code? If so could you declare this script to be in public domain or released with UNLICENSE, the license youtube-dl uses.

**Comment by daniel100097** [comment]
Yes i'm the original author of this code. how can i declare the code as public ?

**Comment by yan12125** [comment]
An approach is like this: https://gist.github.com/gdkchan/2f88297203cd3189a41893e366faba8b - put a comment block in the file.

**Comment by daniel100097** [comment]
http://hastebin.com/ojajegakey.py

**Comment by aminpaks** [comment]
Not working anymore, Openload has changed its contents again,
Now the encryptions are inside of DIV
`<div style="display:none;">
<span id="zuBCRW4KWj">57H=D?&lt;v|vHO`cfcebgcabO`bg]aah]_]_OG|&amp;=cf=v</span>
<span id="zuBCRW4KWjx">57H=D?&lt;v|vHO`cfcebgcabO`bg]aah]_]_OG|&amp;=cf=)</span>
<span id="streamurl">HERE IS THE LINK</span>
</div>`

And the encode function doesn't work, at least I couldn't get the correct result with it.

**Comment by daniel100097** [comment]
http://hastebin.com/tuberiwoxu.py ??? it's still working

**Comment by aminpaks** [comment]
You're right, I found openload algorithm on their website, and yours is its equivalent.
Not sure why didn't work in the first time!

Thanks.

**Comment by yan12125** [comment]
Thanks you all! I've adapted the algorithm into youtube-dl.

**Comment by JustMeDaFaq** [comment]
Is it just me, or did they changed it again? Following doesnt work anymore, lol. 


// OpenLoad algorithm written in JavaScript

// Encrypted stream info
var x = 'v;&>ACB&}$gO`cfcebhgdhO`bg]aah]_]_Ou$\d\'v!3';
// Rotation
var s=[];
for (var i=0;i<x.length;i++){
  var j=x.charCodeAt(i);
  if ((j>=33)&&(j<=126)){
    s[i]=String.fromCharCode(33+((j+14)%94));
  } else {
    s[i]=String.fromCharCode(j);
  }
}
var tmp=s.join("");
var unecrypted_str = tmp.substring(0, tmp.length - 1) + String.fromCharCode(tmp.slice(-1).charCodeAt(0) + 2);

**Comment by yan12125** [comment]
@JustMeDaFaq The latest commit of youtube-dl is still working. Didn't check it thoroughly, though.

**Comment by JustMeDaFaq** [comment]
C:\Users\XXXX\Downloads>youtube-dl https://openload.co/embed/2hoEy3X94as/The.Simpsons.S27E22.HDTV.x264-FLEET.mkv
[Openload] 2hoEy3X94as: Downloading webpage
ERROR: Unable to extract encrypted data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


-> Looks like broken :/

**Comment by yan12125** [comment]
Works with commit 4ddcb5999d0323fb83c5b879127d31763f5d63e2 or newer:
```
$ youtube-dl -v "https://openload.co/embed/2hoEy3X94as/The.Simpsons.S27E22.HDTV.x264-FLEET.mkv" 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://openload.co/embed/2hoEy3X94as/The.Simpsons.S27E22.HDTV.x264-FLEET.mkv']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.19
[debug] Git HEAD: 71ad00c
[debug] Python version 3.5.2 - Linux-4.7.4-1-ARCH-x86_64-with-arch
[debug] exe versions: avconv v12_dev0-3198-g75d98e3, avprobe v12_dev0-3198-g75d98e3, ffmpeg 3.1.3, ffprobe 3.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[Openload] 2hoEy3X94as: Downloading webpage
[debug] Invoking downloader on 'https://openload.co/stream/2hoEy3X94as~1474744110~140.112.0.0~HrgqkB0K?mime=true'
[download] Destination: The.Simpsons.S27E22.HDTV.x264-FLEET.mkv.mp4-2hoEy3X94as.mp4
[download]   6.2% of 127.79MiB at 221.68KiB/s ETA 09:13^CException ignored in: <_io.FileIO name='The.Simpsons.S27E22.HDTV.x264-FLEET.mkv.mp4-2hoEy3X94as.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='The.Simpsons.S27E22.HDTV.x264-FLEET.mkv.mp4-2hoEy3X94as.mp4.part'>

ERROR: Interrupted by user
```
The latest fix is not included in the latest version yet. If you can't wait, have a look at https://github.com/rg3/youtube-dl/blob/master/README.md#developer-instructions for how to get the latest commit.

**Comment by Hrxn** [comment]
In my opinion, the developer instructions are slightly overkill for just running _youtube-dl_.
You don't need any build tools for this or _git_ on your system.

You can get the latest version directly from the tree, like this:
![1](https://cloud.githubusercontent.com/assets/12064918/18799126/4f360602-81d6-11e6-967a-1100e2d6c1d9.png)

This is all you need, the full program, _Python_ source code.
Only requirement is _Python_ on your system. If you run any Linux distribution, you should already have it. Otherwise, install via your package manager. OS X should ship with it as well, if not, installers for OS X - and Windows - are here: https://www.python.org/downloads/

###### NB: If you are on Windows, you don't actually need to install anything, just unpack the _Python_ interpreter to a directory and run the executable from there.

**Comment by yan12125** [comment]
@Hrxn thanks for those instructions. Maybe it's time to add a section or an FAQ entry in ```README.md``` for cutting-edge fans as well as testers.
