### ISSUE TITLE
YouTube-dl - autonumber to distinguish between different playlists mentioned in batch-file

### ISSUE THREAD

**Issue by ismail783** [rg3/youtube-dl#10729]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

**My youtube-dl.conf is -**
```
-u <User Name>
-p <Password>
-i
-c
--no-warnings
--console-title
--batch-file='batch-file.txt'
--autonumber-size 3 
-o 'MyVideos/%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(autonumber)s-%(title)s.%(ext)s'
-f 'bestvideo[height<=720]+bestaudio/best[height<=720]'
```

**batch-file.txt is -**
```
URL1
URL2
URL3
```

The problem is, when I put multiple playlist in the batch file, the autonumber can not distinguish between different playlists.

For Example, if URL1 (Which is an URL of a Playlist) has 21 videos, and the last video has the autonumber 21, then the URL2 (second playlist) will have 22 as the autonumber of its first video.

I want each playlist to start with 1.

Is there any solution to this problem.

**Comment by dstftw** [comment]
Use `%(playlist_index)s`.
