### ISSUE TITLE
[Help] HTTP Error 429

### ISSUE THREAD

**Issue by yas9999** [rg3/youtube-dl#10722]
Hello,
i got this error while i'm using youtube-dl only from YOUTUBE:
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
PS: i'm using the last update of youtube-dl (2016.09.19)

please help 😄

**Comment by yan12125** [comment]
See https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required and #5138.
