### ISSUE TITLE
problems with channel names not accepting spaces

### ISSUE THREAD

**Issue by hamzalatif7** [rg3/youtube-dl#10725]
I have a question I will not say if its a bug because maybe i am doing something wrong hear 
attempting to download a whole channel called DJ Hasan Music however it only sees  and tries to download the dj part it does not seem to know that I wrote Hasan Music. 
hear is the command i do youtube-dl ytuser:DJ Hasan Music any ideas on what i am doing wrong I am using sonar gnu linux and i have python  installed so downloading works fine but its not accepting channels with spaces for some reason sonar is based off the manjaro framework

**Comment by remitamine** [comment]
use channel url: https://www.youtube.com/user/IDJHasanI.

**Comment by hamzalatif7** [comment]
i get an error 404 when downloading the channel i do this youtube-dl 
ytuser:https://www.youtube.com/user/IDJHasanIOn should i just do 
youtube-dl then the url i did that a while back and it did not download 
the whole channel21/09/16 22:44, remitamine wrote:

**Comment by remitamine** [comment]
> should i just do youtube-dl then the url i did that a while back and it did not download the whole channel

not it will download all the videos in the channel, it will collect at least 600 videos:
```
youtube-dl https://www.youtube.com/user/IDJHasanI
WARNING: parsing .netrc: No authenticators for youtube (None, line None)
[youtube:user] IDJHasanI: Downloading channel page
WARNING: parsing .netrc: No authenticators for youtube (None, line None)
[youtube:playlist] UUqphjkdhGAhRu04Tt4nuWTQ: Downloading webpage
[download] Downloading playlist: Uploads from DJ Hasan Music
[youtube:playlist] UUqphjkdhGAhRu04Tt4nuWTQ: Downloading page #1
[youtube:playlist] UUqphjkdhGAhRu04Tt4nuWTQ: Downloading page #2
[youtube:playlist] UUqphjkdhGAhRu04Tt4nuWTQ: Downloading page #3
[youtube:playlist] UUqphjkdhGAhRu04Tt4nuWTQ: Downloading page #4
[youtube:playlist] UUqphjkdhGAhRu04Tt4nuWTQ: Downloading page #5
[youtube:playlist] UUqphjkdhGAhRu04Tt4nuWTQ: Downloading page #6
[youtube:playlist] UUqphjkdhGAhRu04Tt4nuWTQ: Downloading page #7
[youtube:playlist] playlist Uploads from DJ Hasan Music: Downloading 607 videos
[download] Downloading video 1 of 607
WARNING: parsing .netrc: No authenticators for youtube (None, line None)
[youtube] fbWcv2onPHg: Downloading webpage
[youtube] fbWcv2onPHg: Downloading video info webpage
[youtube] fbWcv2onPHg: Extracting video information
WARNING: video doesn't have subtitles
[youtube] fbWcv2onPHg: Downloading MPD manifest
[download] Destination: DJ Hasan - Passenger-fbWcv2onPHg.mp4

09/22 06:53:43 [NOTICE] Downloading 1 item(s)
[#bcd84b 2.2MiB/10MiB(22%) CN:4 DL:609KiB ETA:13s]
```
