### ISSUE TITLE
Older video from CBS not available...

### ISSUE THREAD

**Issue by spookyahell** [rg3/youtube-dl#10728]
... even though can be played in browser

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', '-v', 'http://www.cbs.com/shows/big_bang_theor
y/video/794877409/the-big-bang-theory-sheldon-s-little-idea/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.09.19
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-78252-gb62825a, ffprobe N-78252-gb62825a, rtmpdum
p 2.4
[debug] Proxy map: {}
[CBS] 794877409: Downloading SMIL data
ERROR: None of the allowed formats for this user agent were available.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpigpzdgyq\bu
ild\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpigpzdgyq\bu
ild\youtube_dl\extractor\common.py", line 355, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpigpzdgyq\bu
ild\youtube_dl\extractor\cbs.py", line 76, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpigpzdgyq\bu
ild\youtube_dl\extractor\cbs.py", line 53, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpigpzdgyq\bu
ild\youtube_dl\extractor\theplatform.py", line 40, in _extract_theplatform_smil
youtube_dl.utils.ExtractorError: None of the allowed formats for this user agent
 were available.
```

### Description of your *issue*, suggested solution and other information
Example: http://www.cbs.com/shows/big_bang_theory/video/794877409/the-big-bang-theory-sheldon-s-little-idea/
This video exists on CBS.com and there is at least a RTMP stream (that I haven't been able to get so far yet)
Also case for some other older videos.

**Comment by spookyahell** [comment]
Definetly related to https://github.com/rg3/youtube-dl/issues/10723

**Comment by remitamine** [comment]
will be fixed in the next version.
> Definetly related to #10723

no, it's not.
