### ISSUE TITLE
Periscope video in tweet

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#10737]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\>youtube-dl.py -v "https://twitter.com/OPP_HSD/status/779210622571536384"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://twitter.com/OPP_HSD/status/7792106225
71536384']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.09.03
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[twitter] 779210622571536384: Downloading webpage
ERROR: There's no video in this tweet.; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
Traceback (most recent call last):
  File "C:\youtube-dl.py\youtube_dl\YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\common.py", line 347, in extract
    return self._real_extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\twitter.py", line 340, in _real_ex
tract
    raise ExtractorError('There\'s no video in this tweet.')
youtube_dl.utils.ExtractorError: There's no video in this tweet.; please report
this issue on https://yt-dl.org/bug . Make sure you are using the latest version
; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://twitter.com/OPP_HSD/status/779210622571536384

---

### Description of your *issue*, suggested solution and other information

Apparently you can tweet a periscope video...who knew??
The direct periscope link (https://www.periscope.tv/OPP_HSD/1zqKVVlkqLaKB?t=7) does download correctly...but the the "tweeted" version does not.

Thanks 
Ringo

**Comment by yan12125** [comment]
Thanks for the report. Periscope videos in tweets will be recognized in the next version.
