### ISSUE TITLE
dctp.tv - rtmpdump error

### ISSUE THREAD

**Issue by qfvldaa2xn** [rg3/youtube-dl#10734]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Downloading from dctp.tv doesn't work. But with a German IP it should work.
But I get an _ERROR: rtmpdump exited with code 1_

See log:

```
$ youtube-dl -v http://www.dctp.tv/filme/uhren-des-lebens/[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.dctp.tv/filme/uhren-des-lebens/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.19
[debug] Python version 3.5.2 - Linux-4.7.4-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[DctpTv] uhren-des-lebens: Determining file version
[DctpTv] uhren-des-lebens: Fetching object ID
[DctpTv] uhren-des-lebens: Downloading metadata
[DctpTv] uhren-des-lebens: Downloading server list
[debug] Invoking downloader on 'rtmpe://dctpfs.fplive.net/dctp/'
[download] Destination: Uhren des Lebens-1238.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmpe://dctpfs.fplive.net/dctp/ -o 'Uhren des Lebens-1238.flv.part' --playpath mp4:c41b8f90fd6c4af0a72f10ba51c5a083_dctp_0500_4x3.m4v --realtime --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : dctpfs.fplive.net
[rtmpdump] DEBUG: Parsed app     : dctp
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : dctpfs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:c41b8f90fd6c4af0a72f10ba51c5a083_dctp_0500_4x3.m4v
[rtmpdump] DEBUG: tcUrl    : rtmpe://dctpfs.fplive.net:1935/dctp
[rtmpdump] DEBUG: app      : dctp
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : dctpfs.fplive.net
[rtmpdump] DEBUG: Parsed app     : dctp
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : dctpfs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:c41b8f90fd6c4af0a72f10ba51c5a083_dctp_0500_4x3.m4v
[rtmpdump] DEBUG: tcUrl    : rtmpe://dctpfs.fplive.net:1935/dctp
[rtmpdump] DEBUG: app      : dctp
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.


ERROR: rtmpdump exited with code 1
```

When I try youtube-dl -g and use rtmpdump then I get following error:
```
WARNING: HandShake: Type mismatch: client sent 6, server answered 9
INFO: Connected...
ERROR: rtmp server sent error
ERROR: rtmp server requested close
```

**Comment by yan12125** [comment]
Thanks for the report and sorry for the delay. dctp support will be back in the next version.
