### ISSUE TITLE
youtube-dl doesn't recognize ffmpeg

### ISSUE THREAD

**Issue by PannenkoekenNL** [rg3/youtube-dl#10747]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.24**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

### Description of your *issue*, suggested solution and other information
Youtube-dl doesn't recognize ffmpeg, it is located in D:\yt\ffmpeg\bin\ffmpeg.exe and Youtube-dl is located in D:\yt\youtube-dl

**Comment by Hrxn** [comment]
Try this in Cmd: `where ffmpeg.exe`

Also, sub-directories are not part of the directory defined in PATH

**Comment by PannenkoekenNL** [comment]
Sorry I have no idea what you mean, when I do `where ffmpeg.exe` in D:\yt I get `INFO: Could not find files for the given pattern(s).` and when I do it in D:\yt\ffmpeg\bin I get `D:\yt\ffmpeg\bin\ffmpeg.exe`

**Comment by dstftw** [comment]
`ffmpeg.exe` must be located in the same directory with `youtube-dl.exe` or in any directory from `%PATH%`.
