### ISSUE TITLE
Unable to download from www.gameinformer.com again.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#10741]
$ youtube-dl -v http://www.gameinformer.com/b/features/archive/2016/09/23/replay-star-wars-demolition.aspx
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.gameinformer.com/b/features/archive/2016/09/23/replay-star-wars-demolition.aspx']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.24
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 3.0.2-4, ffprobe 3.0.2-4, rtmpdump 2.4
[debug] Proxy map: {}
[GameInformer] replay-star-wars-demolition: Downloading webpage
ERROR: Unable to extract brightcove id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 355, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/gameinformer.py", line 27, in _real_extract
    brightcove_id = self._search_regex(r"getVideo\('[^']+video_id=(\d+)", webpage, 'brightcove id')
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 658, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract brightcove id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thank you in advance. :)

**Comment by yan12125** [comment]
Thanks @EnginePod. It's broken for me, too.
