### ISSUE TITLE
Sound dropouts

### ISSUE THREAD

**Issue by dermiff** [rg3/youtube-dl#10759]
I use the newest version on Mac OS X Yosemite. I want to load:
http://www.prosieben.de/tv/das-prosieben-auswaertsspiel/video/11-ganze-folge-das-prosieben-auswaertsspiel-ganze-folge

After the download the sound drops outs all two seconds.
What could be the reason for this?

## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.09.24
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dermiff** [comment]
Here is a example how it sounds:
http://www.wikiupload.com/HSNFALZLB667ZDH

Picture is ok, but sound is not usable.

**Comment by yan12125** [comment]
Is it extracted from the downloaded file or it's a recording?

**Comment by dermiff** [comment]
This is a recording from the flv-file that youtube-dl created.

**Comment by yan12125** [comment]
Would you like to share the downloaded file? Maybe there's some clue in this file.

Also please paste the full download log. That identifies some common issues, too.

**Comment by dermiff** [comment]
A short example for the URL:
http://www.7tv.de/ran-an-den-mann/2-bloss-nicht-aufgeben-clip

[Bloß nicht aufgeben-4657154.flv.zip](https://github.com/rg3/youtube-dl/files/504328/Bloss.nicht.aufgeben-4657154.flv.zip)

**Comment by dermiff** [comment]
How can i create a download log?

**Comment by yan12125** [comment]
In general the output of the command is enough:
```
youtube-dl -v http://www.prosieben.de/tv/das-prosieben-auswaertsspiel/video/11-ganze-folge-das-prosieben-auswaertsspiel-ganze-folge
```

**Comment by yan12125** [comment]
The file in Bloß nicht aufgeben-4657154.flv.zip plays fine on mpv. Which player are you using?

**Comment by dermiff** [comment]
This is crazy. I use the VLC. With mpv it works here too.

**Comment by yan12125** [comment]
That's the point. You may want to ask VLC people why playing sound fails.
