### ISSUE TITLE
[Newgrounds] Https URLs invokes downloading from http URL.

### ISSUE THREAD

**Issue by stepshal** [rg3/youtube-dl#10752]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ y -v https://www.newgrounds.com/portal/view/673111
[debug] System config: []
[debug] User config: ['-4', '-f', 'best', '--prefer-free-formats', '--no-cache-dir', '--no-mtime', '--youtube-skip-dash-manifest']
[debug] Command-line args: ['-v', 'https://www.newgrounds.com/portal/view/673111']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.24
[debug] Python version 3.6.0b1 - Linux-4.8.0-rc5-686-i686-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[Newgrounds] 673111: Downloading webpage
[debug] Invoking downloader on 'http://uploads.ungrounded.net/alternate/971000/971450_alternate_31675.mp4'
[download] Destination: Dancin-673111.mp4
[download] 100% of 29.73MiB in 00:02
```
https://www.newgrounds.com/audio/listen/549479
https://www.newgrounds.com/portal/view/673111

Downloading video/audio from https URLs should invokes downloading from https URL, otherwise, what's the point in downloading from https URLs in first place?

**Comment by dstftw** [comment]
There is absolutely no relation between the original URL's scheme and download URL's scheme. youtube-dl provides download URLs that hoster serves itself.

**Comment by stepshal** [comment]
Can't it be forced to https by youtube-dl?

**Comment by dstftw** [comment]
No, it does not make any sense. They may not even serve it via https.

**Comment by stepshal** [comment]
@dstftw If it can't be done technically, then okay.
> No, it does not make any sense.
Then it does not make sense to download original URL's scheme in https in first place.
> They may not even serve it via https.
Yes, but usually they do. Like this hoster.

**Comment by dstftw** [comment]
>Then it does not make sense to download original URL's scheme in https in first place.

As I've already said there is no connection between that. They can provide whatever they want whichever way they want. youtube-dl just extracts what they provide no more no less.

**Comment by yan12125** [comment]
In Firefox HTTP video/audio files are used even if the webpage is in HTTPS, so there's a warning in the address bar. It's a bug of Newgrounds, not youtube-dl.
