### ISSUE TITLE
[HS] youtube-dl for android 

### ISSUE THREAD

**Issue by yas9999** [rg3/youtube-dl#10753]
Hello,
i wonder if there is any possibility to make youtube-dl for android 
if it's already done can you reference me please
Best regards,

**Comment by dstftw** [comment]
Duplicate of #967.

**Comment by yas9999** [comment]
ok i guess there is no pure android application !

**Comment by codaman** [comment]
is there any way to use youtube-dl on android app. There is 2 possible way first; add executable youtube-dl file to android project and run it with command codes second way add scripts to android project and run it. i succeed second way as running scripts on ios project. and also i cant use youtube-dl executable file on android project. i am searching a native example project that can run python codes
