### ISSUE TITLE
Google Drive Video links redirector.googlevideo.com

### ISSUE THREAD

**Issue by aalireza439** [rg3/youtube-dl#10756]
when i am get google drive video link it's only work with my ip , when i am change `c.docs.google.com` to `https://redirector.googlevideo.com/ ` its not working and give 404 page.

i want know there is any way solve this and why  `https://redirector.googlevideo.com/ `  work with youtube video links ?

**Comment by dstftw** [comment]
Ask Google why. Closing since not a youtube-dl issue.

**Comment by aalireza439** [comment]
i know it's not youtube-dl issue , since there is couple website using google drive for hosting their videos and  `redirector.googlevideo.com ` successfully work for them , i just want know maybe there is a way to this and you could help me.

**Comment by JovanyRocha** [comment]
How are obtained the "https://redirector.googlevideo.com/" links?
