### ISSUE TITLE
ERROR: Signature extraction failed: 

### ISSUE THREAD

**Issue by enricota** [rg3/youtube-dl#10767]
Hi,
it doesn't work only with this video.

pi@raspberrypi:~/video $ youtube-dl  O1UrY_tRADk -o chitarra3.mp4
[youtube] Setting language
[youtube] O1UrY_tRADk: Downloading webpage
[youtube] O1UrY_tRADk: Downloading video info webpage
[youtube] O1UrY_tRADk: Extracting video information
[youtube] O1UrY_tRADk: Encrypted signatures detected.
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflHlG7su/base.js'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by enricota** [comment]
It works. Thanks a Lot
enrico

2016-09-26 14:31 GMT, Sergey M. <notifications@github.com>:
