### ISSUE TITLE
Is Support for Dramafever.com Possible?

### ISSUE THREAD

**Issue by LAP2008** [rg3/youtube-dl#1076]
I don't know if you guys could make it possible to download videos and subtitles from this site. On older videos i see a regular flash player and on newer and current they have hulu player 4.21.205644

a video with hulu player
http://www.dramafever.com/drama/4250/1/You%27re_the_Best%2C_Lee_Soon_Shin/?ap=1

a video with the other player
http://www.dramafever.com/drama/4114/1/Inkigayo/?ap=1

**Comment by dstftw** [comment]
Dramafever is supported for quite some time already.
