### ISSUE TITLE
Why I get “PermissionError: [WinError 5] Access is denied” error when I using youtube-dl in c# process class?

### ISSUE THREAD

**Issue by parsasaei** [rg3/youtube-dl#10766]
## PermissionError: [WinError 5] Access is denied
- When I run youtube-dl.exe with c# process class on server, it returns below error in StandardOutput:

`Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\__init__.py", line 449, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\__init__.py", line 416, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\YoutubeDL.py", line 367, in __init__
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\YoutubeDL.py", line 2100, in _setup_opener
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\utils.py", line 642, in make_HTTPS_handler
  File "C:\Python\Python34\lib\ssl.py", line 439, in create_default_context
  File "C:\Python\Python34\lib\ssl.py", line 390, in load_default_certs
  File "C:\Python\Python34\lib\ssl.py", line 377, in _load_windows_store_certs
PermissionError: [WinError 5] Access is denied`
### My Version is `youtube-dl --version: 2016.0.31.0` and also when I used latest version,this problem was occured too.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.0.31.0**

What is these errors?**I don't have these paths and files with these directories.**
And Here is my code

```
string ydlPath = Server.MapPath("/ydlPath/youtube-dl.exe");
string tempLocation = Server.MapPath("/ydlPath/");

    System.IO.StreamReader errorreader;
    System.Diagnostics.Process proc = new System.Diagnostics.Process();
    proc.EnableRaisingEvents = false;
    proc.StartInfo.ErrorDialog = false;
    proc.StartInfo.RedirectStandardError = true;
    proc.StartInfo.FileName = ydlPath ;
    //proc.StartInfo.Arguments = "-F \"" + Url + "\"";
    proc.StartInfo.WorkingDirectory = tempLocation;
    proc.StartInfo.Arguments = "-f bestvideo[ext=mp4]+bestaudio[ext=m4a] \"" + Url + "\"";
    proc.StartInfo.Verb = "runas";
    proc.StartInfo.UseShellExecute = false;
    proc.StartInfo.CreateNoWindow = false;
    proc.StartInfo.RedirectStandardOutput = true;
    proc.Start();
    errorreader = proc.StandardError;
    string Output = proc.StandardOutput.ReadToEnd();

    proc.WaitForExit();
    proc.Close();
```
### My Description

I used this on my local and it works fine. Also when I use youtube-dl.exe **with cmd on server or on my local** I don't have problem.

**Comment by yan12125** [comment]
Are you using IIS? It's a Python bug. Could you install Python 2.7.12 or 3.5.2 and use [the zipped version](http://yt-dl.org/downloads/latest/youtube-dl) of youtube-dl?

**Comment by parsasaei** [comment]
yes,I'm using iis,and I installed python 3.4.0 in C:\Python\Python34\

**Comment by parsasaei** [comment]
how can I install this zipped version?

**Comment by yan12125** [comment]
Download that file, then
```
C:\PythonXY\python.exe C:\some\directory\youtube-dl
```

**Comment by parsasaei** [comment]
What should I type In cmd? I ask this question because when I use this in cmd, I can configure it on my server code.

**Comment by yan12125** [comment]
Just replace the path to python.exe and youtube-dl to real paths. Anything wrong?

**Comment by parsasaei** [comment]
Thank you very much.It worked with your beneficial helps.
After install python 3.5 in c:\Python35
I use it in my code :
```
string ydlPath = @"C:\Python35\python.exe";
string ydl = @"C:\YoutubeDownload\ydlPath\youtube-dl";
string tempLocation = Server.MapPath("/ydlPath/");
        System.IO.StreamReader errorreader;
        System.Diagnostics.Process proc = new System.Diagnostics.Process();
        proc.EnableRaisingEvents = false;
        proc.StartInfo.ErrorDialog = false;
        proc.StartInfo.RedirectStandardError = true;
        proc.StartInfo.FileName = ffmpegPath;
        //proc.StartInfo.Arguments = "-F \"" + Url + "\"";
        proc.StartInfo.WorkingDirectory = tempLocation;
        proc.StartInfo.Arguments = ydl + " -f bestvideo[ext=mp4]+bestaudio[ext=m4a] \"" + Url + "\"";
        proc.StartInfo.Verb = "runas";
        proc.StartInfo.UseShellExecute = false;
        proc.StartInfo.CreateNoWindow = false;
        proc.StartInfo.RedirectStandardOutput = true;
        proc.Start();
        errorreader = proc.StandardError;
        string Output = proc.StandardOutput.ReadToEnd();

    proc.WaitForExit();
    proc.Close();
```
Thank You.

**Comment by yan12125** [comment]
Glad to see that fixed :)

**Comment by parsasaei** [comment]
With this compressed python version,I can't download from somelinks,but with exe version it's work.
How can I handle it? can I?
have this compressed python a new version for this isssue or I should do anything?

**Comment by yan12125** [comment]
@parsasaei Could you post the command line output of both versions?

**Comment by parsasaei** [comment]
yes. exe version download file and here exists output of it:
```
[youtube] MZctQy6uEo8: Downloading webpage
[youtube] MZctQy6uEo8: Downloading video info webpage
[youtube] MZctQy6uEo8: Extracting video information
[download] Destination: Come Alive-MZctQy6uEo8.f137.mp4
[download] 100% of 7.56MiB in 00:35
[download] Destination: Come Alive-MZctQy6uEo8.f140.m4a
[download] 100% of 4.48MiB in 00:20
[ffmpeg] Merging formats into "Come Alive-MZctQy6uEo8.mp4"
Deleting original file Come Alive-MZctQy6uEo8.f137.mp4 (pass -k to keep)
Deleting original file Come Alive-MZctQy6uEo8.f140.m4a (pass -k to keep) 
```
but python compressed output is empty and not return anything.

**Comment by yan12125** [comment]
How did you run the compressed version?

**Comment by parsasaei** [comment]
With process class of c#

**Comment by yan12125** [comment]
Could you paste relevant C# codes?

**Comment by parsasaei** [comment]
In top of this topic it's there

**Comment by yan12125** [comment]
Nothing printed to StandardError either?

**Comment by parsasaei** [comment]
it's print:
ERROR: MZctQy6uEo8: YouTube said: This video is not available.

**Comment by yan12125** [comment]
For https://www.youtube.com/watch?v=MZctQy6uEo8, I got "This video is not available." here too. Does the exe version and the Python version run on the same PC?

**Comment by parsasaei** [comment]
No.I check with exe version my local pc,and check with python verion on server

**Comment by parsasaei** [comment]
On server, exe vesrion return **YouTube said: This video is not available** too.

**Comment by parsasaei** [comment]
What is the reason of it?is it related to location ip?

**Comment by yan12125** [comment]
Yes, and I guess you need a proxy on the server. From the youtube page, it says only the following countries are allowed to watch this video: AS,AU,BE,CA,DK,FI,FR,GB,GU,IE,IS,KR,LU,MP,MX,NL,NO,NZ,PR,SE,US,VI. Full names for those abbreviations can be found in http://data.okfn.org/data/core/country-list

**Comment by parsasaei** [comment]
My server location is on "United States, Illinois, Chicago", and with this recommendation,it must be download.

**Comment by yan12125** [comment]
Does your server allow running browsers? (IE, edge, etc.) If so could you open https://www.youtube.com/watch?v=MZctQy6uEo8 and check whether it plays or not?

**Comment by parsasaei** [comment]
It can't open on browser of server.

**Comment by parsasaei** [comment]
Sorry my server location is on Netherlands but Netherlands exists in countries which can access to watch this video too.

**Comment by yan12125** [comment]
youtube-dl tries its best to mimic browsers. If you got "This video is not available" in youtube-dl, I bet you'll get the same in browsers. You may want to ask Google why blocking your server. AFAIK there are reports that geolocation detection misbehaves.

**Comment by parsasaei** [comment]
Thank you so much.

**Comment by ThePirate42** [comment]
I had activated ISS only for curiosity, and since then, even after deactivating it, youtube-dl binaries on my PC fail with this error (unless I have administrative privileges). I need to use the youtube-dl exe version for compability with MPC-HC [https://github.com/clsid2/mpc-hc/issues/301](url) what I have to do to make youtube-dl work again?

**Comment by falcorr** [comment]
[WinError 5] Access is denied:

Python v3.8.5
