### ISSUE TITLE
Support for smotret-anime.ru

### ISSUE THREAD

**Issue by Albatrosicks** [rg3/youtube-dl#10779]
**Video URL:** https://smotret-anime.ru/catalog/mob-psycho-100-14302/12-seriya-140426
**Page contains:**
- 1080p-360p mp4 formats
- Subtitles for russian and english languages from different translate teams
- Russian dub

**API access:** info@smotret-anime.ru

### Also: 
**Video list > anime:** https://smotret-anime.ru/catalog/mob-psycho-100-14302
**Anime list > genres:** https://smotret-anime.ru/catalog/genres
**Anime list > search:** https://smotret-anime.ru/catalog/search?q=Mob+Psycho&undefined=
**Anime list > ongoing:** https://smotret-anime.ru/ongoing

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
