### ISSUE TITLE
I use the "-i" option for Youtube playlist, but youtube-dl won't move onto next video if current video " has already been downloaded and merged"

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#10771]
---
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.24**
### Before submitting an _issue_ make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
## \- [X] Question

```
$ youtube-dl -i -v https://www.youtube.com/watch?v=pA-x-zsDDeI&list=PLAZ27CqbEinagPtU4pFLXg9Kj711wR6YF
[1] 5249
h2g@laptop ~ $ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-i', u'-v', u'https://www.youtube.com/watch?v=pA-x-zsDDeI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.19
[debug] Python version 2.7.12 - Linux-4.4.0-36-generic-x86_64-with-LinuxMint-18-sarah
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[youtube] pA-x-zsDDeI: Downloading webpage
[youtube] pA-x-zsDDeI: Downloading video info webpage
[youtube] pA-x-zsDDeI: Extracting video information
[youtube] pA-x-zsDDeI: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Setting Up An Innocent Subject _ Derren Brown - The Guilt Trip-pA-x-zsDDeI.mkv has already been downloaded and merged
>
```
### Description of your _issue_, suggested solution and other information

I'm trying to download all seven videos in this playlist: https://www.youtube.com/watch?v=pA-x-zsDDeI&list=PLAZ27CqbEinagPtU4pFLXg9Kj711wR6YF.

I may have some of the vids already downloaded.  When I get to videos that I've already downloaded, I'd like youtube-dl  to move onto the next video on the playlist and download. 

I added the **-i** (ignore) option, thinking that this option would help, but download does not move on to the next video. it just stops  at the already downloaded video with this message similar to:

>  [download] VideoTitle pA-x-zsabcI.mkv has already been downloaded and merged

How can I resolve this problem?

**Comment by Vatba** [comment]
This hasn't been resolved, not to me at least.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
