### ISSUE TITLE
Download same titled videos

### ISSUE THREAD

**Issue by FatihErdem** [rg3/youtube-dl#10783]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.27*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

I am trying to download all the videos of one of huge channel and converting to mp3. It has more than 3 tousand videos. But there is a problem. There is multiple videos with same title. I want to download all of them. 

For example there are more than one videos with title "Brand X Music - Retribution". I want to save them like:

* Brand X Music - Retribution
* Brand X Music - Retribution(1)
* Brand X Music - Retribution(2)

I didn't make it. Which parameter do I have to use. Thank you.

**Comment by dstftw** [comment]
This works out of the box since default filename output template includes video id to provide uniqueness. Don't override default output template.

**Comment by FatihErdem** [comment]
I have to override because I don't want to see video id in the title. Is there any workaround?

**Comment by dstftw** [comment]
`%(playlist_id)s`, `%(autonumber)s`.
