### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by Knocks83** [rg3/youtube-dl#10802]
Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

This is the error that i get when i try to download a soundcloud song (i tried to download this: https://soundcloud.com/foxamoore/still-alive) 

I can't give you more information because the bot is hosted by ts3index.com

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
