### ISSUE TITLE
Question:  attempting to use --ap-mso but don't see Verizon or Comcast on the MSO list.  Does youtube-dl support these providers?

### ISSUE THREAD

**Issue by streammonkey** [rg3/youtube-dl#10803]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.09.27_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.27**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.09.27
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---
### Description of your _issue_, suggested solution and other information

Explanation of your _issue_ in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your _issue_ requires account credentials please provide them or explain how one can obtain them.

**Comment by jdunn0** [comment]
To answer the question in the title:
No, youtube-dl doesn't currently support Comcast or Verizon.

Support can be added if the following is true:
1. A youtube-dl developer wants to work on support for it.
2. You have a Comcast or Verizon account and are willing to share that account info with that developer (over email, not the public github issue tracker).

**Comment by yan12125** [comment]
Thanks @jdunn0, that's definitely correct.

@streammonkey Please paste an example URL.

**Comment by streammonkey** [comment]
> @streammonkey Please paste an example URL.

http://www.tbs.com/videos/full-frontal-with-samantha-bee/season-1/episode-24/presidential-debate-special.html

http://www.aetv.com/shows/oj-speaks-the-hidden-tapes/season-1/episode-1

There are two examples of shows that require a provider login before you can get to the video.

Thanks.

**Comment by spookyahell** [comment]
I have account info for verizon

**Comment by spookyahell** [comment]
Whoom do I share it with?

**Comment by spookyahell** [comment]
In other words: Who would want to work on it?

**Comment by tchawes** [comment]
I have TWC login if anyone wants to work on it...

**Comment by remitamine** [comment]
if you want me to work on it, you can contact me at remitamine[at]gmail[dot]com.

**Comment by tchawes** [comment]
remitamine is unable to do it right now, anyone else want to work on TWC?

**Comment by mvbattista** [comment]
Is there an update on adding Verizon to the MSO? Should that be a separate request?

**Comment by yan12125** [comment]
In general different providers should go to different issues. In this case, this issue already covers Verizon.

**Comment by mvbattista** [comment]
@yan12125 In regards to the new tag and as stated previously in the ticket, @spookyahell was willing to provide his Verizon account. It's just lacking the collaborator resources.

**Comment by mvbattista** [comment]
@yan12125 @remitamine Are collaborator resources still waiting for this and cannot reach out to @spookyahell directly?

**Comment by SkiTheSlicer** [comment]
Never contributed to the project before. This worked with my Verizon credentials.
