### ISSUE TITLE
title char '?'

### ISSUE THREAD

**Issue by dcambria** [rg3/youtube-dl#10805]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.27*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.27**

### Before submitting an *issue* make sure you have:
- [ x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ danielcambria$ youtube-dl --output '%(title)s-%(id)s.%(ext)s' https://youtu.be/jQLtEjuwyFw -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--output', '%(title)s-%(id)s.%(ext)s', 'https://youtu.be/jQLtEjuwyFw', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.24
[debug] Python version 3.5.2 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.1.3, ffprobe 3.1.3
[debug] Proxy map: {}
[youtube] jQLtEjuwyFw: Downloading webpage
[youtube] jQLtEjuwyFw: Downloading video info webpage
[youtube] jQLtEjuwyFw: Extracting video information
[youtube] jQLtEjuwyFw: Downloading MPD manifest
[debug] Invoking downloader on 'https://r3---sn-bg07dnlk.googlevideo.com/videoplayback?id=8d02ed123bb0c85c&itag=136&source=youtube&requiressl=yes&nh=IgpwcjAyLmdydTA5KgkxMjcuMC4wLjE&mn=sn-bg07dnlk&mm=31&pl=15&mv=m&ms=au&initcwndbps=492500&ratebypass=yes&mime=video/mp4&gir=yes&clen=68348302&lmt=1475116957307891&dur=415.266&signature=35705F0E388B57992FAA4B7E1E78271917CEEB72.5E0544A7CB0A1E627EAFB94FD00CDEFE7D06038C&upn=gi7yIGbQf4A&mt=1475192932&key=dg_yt0&ip=187.75.230.220&ipbits=0&expire=1475214824&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,mn,mm,pl,mv,ms,initcwndbps,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Adotar ou comprar um cãozinho-jQLtEjuwyFw.f136.mp4
[download] 100% of 65.18MiB in 00:18
[debug] Invoking downloader on 'https://r3---sn-bg07dnlk.googlevideo.com/videoplayback?id=8d02ed123bb0c85c&itag=140&source=youtube&requiressl=yes&nh=IgpwcjAyLmdydTA5KgkxMjcuMC4wLjE&mn=sn-bg07dnlk&mm=31&pl=15&mv=m&ms=au&initcwndbps=492500&ratebypass=yes&mime=audio/mp4&gir=yes&clen=6597200&lmt=1475116931884727&dur=415.335&signature=8998631C61AEB9FBE9B650D438B135CA451CB561.4377C9F67F32F52535477C241F4D3A7C1F8F5326&upn=gi7yIGbQf4A&mt=1475192932&key=dg_yt0&ip=187.75.230.220&ipbits=0&expire=1475214824&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,mn,mm,pl,mv,ms,initcwndbps,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Adotar ou comprar um cãozinho-jQLtEjuwyFw.f140.m4a
[download] 100% of 6.29MiB in 00:04
[ffmpeg] Merging formats into "Adotar ou comprar um cãozinho-jQLtEjuwyFw.mp4"
[debug] ffmpeg command line: avconv -y -i 'file:Adotar ou comprar um cãozinho-jQLtEjuwyFw.f136.mp4' -i 'file:Adotar ou comprar um cãozinho-jQLtEjuwyFw.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Adotar ou comprar um cãozinho-jQLtEjuwyFw.temp.mp4'
Deleting original file Adotar ou comprar um cãozinho-jQLtEjuwyFw.f136.mp4 (pass -k to keep)
Deleting original file Adotar ou comprar um cãozinho-jQLtEjuwyFw.f140.m4a (pass -k to keep)
```

### Description of your *issue*, suggested solution and other information

Var "title" is excluding character '?'

**Comment by yan12125** [comment]
Question marks are not accepted in file names. To get unmodified title, use ```--get-title```:
```
$ youtube-dl --get-title "jQLtEjuwyFw"
Adotar ou comprar um caozinho?
```
