### ISSUE TITLE
Can't download content from the new mitele.es webpage

### ISSUE THREAD

**Issue by Bartesco** [rg3/youtube-dl#10824]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.27**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\mikel>youtube-dl -v http://www.mitele.es/programas-tv/gran-hermano/57ee05daca15da8a588b4586/player
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.mitele.es/programas-tv/gran-hermano/57ee05daca15da8a588b4586/player']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.09.27
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-81489-ga37e6dd, ffprobe N-81489-ga37e6dd
[debug] Proxy map: {}
[generic] player: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player: Downloading webpage
[generic] player: Extracting information
ERROR: Unsupported URL: http://www.mitele.es/programas-tv/gran-hermano/57ee05daca15da8a588b4586/player
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\extractor\common.py", line 355, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\extractor\generic.py", line 2424, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.mitele.es/programas-tv/gran-hermano/57ee05daca15da8a588b4586/player
...
<end of log>
```
### Description of your _issue_, suggested solution and other information

Hi, I have problems with the website mitele.es, since they redesigned the whole webpage I can't download anything, could you fix it? Thank you :)

**Comment by DarkZeros** [comment]
I can confirm they changed completely the website. Even the player is different (ooyala now)
Download links are still m3u8 and the content is in the same format, only the player has changed.

I will try to parse the new player data if I have time, since I have some needs of downloading as well.

If somebody can help first, please go on.
