### ISSUE TITLE
[go] abc.go.com has issue with authentication

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#10831]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.09.27_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.27**
### Before submitting an _issue_ make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
E:\>youtube-dl.exe --restrict-filenames --continue --no-check-certificate --verbose --cookies e:\cookies\cookies-ABC.txt -o shark.tank.S08E02.mp4 "http://abc.go.com/shows/shark-tank/episode-guide/season-08/2-episode-2"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--restrict-filenames', '--continue', '--no-check-certificate', '--verbose', '--cookies', 'e:\\cookies\\cookies-ABC.txt', '-o', 'shark.tank.S08E02.mp4', 'http://abc.go.com/shows/shark-tank/episode-guide/season-08/2-episode-2']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.09.27
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[Go] episode-2: Downloading webpage
[Go] 3413012: Downloading JSON metadata
[Go] 3413012: Downloading JSON metadata
ERROR: Go said: 1007:Unable to retrieve required files for playback. Please try again in a few minutes.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\extractor\common.py", line 355, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\extractor\go.py", line 74, in _real_extract
youtube_dl.utils.ExtractorError: Go said: 1007:Unable to retrieve required files for playback. Please try again in a few minutes.


E:\>youtube-dl.exe --restrict-filenames --continue --no-check-certificate --verbose --ap-mso DTV --ap-username PRIVATE --ap-password PRIVATE -o shark.tank.S08E02.mp4 "http://abc.go.com/shows/shark-tank/episode-guide/season-08/2-episode-2"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--restrict-filenames', '--continue', '--no-check-certificate', '--verbose', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-o', 'shark.tank.S08E02.mp4', 'http://abc.go.com/shows/shark-tank/episode-guide/season-08/2-episode-2']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.09.27
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[Go] episode-2: Downloading webpage
[Go] 3413012: Downloading JSON metadata
[Go] 3413012: Downloading JSON metadata
ERROR: Go said: 1007:Unable to retrieve required files for playback. Please try again in a few minutes.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\extractor\common.py", line 355, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\extractor\go.py", line 74, in _real_extract
youtube_dl.utils.ExtractorError: Go said: 1007:Unable to retrieve required files for playback. Please try again in a few minutes.

```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://abc.go.com/shows/shark-tank/episode-guide/season-08/2-episode-2

---

"Free" videos work just fine. I have tries both with --cookies and --ap-mso and neither seem to allow me to download videos requiring authentication.

**Comment by krind24** [comment]
Thanks for opening this, StevenDTX. I didn't try the command with cookies and stuff, but the --ap-mso did not work for me either. I do have a workaround, which is to use the "inspect element," specifically the "Network" tab, when you fire up a "locked" video (requires sign in). I use chrome and just search for m3u8 to find the playlist file. I open the m3u8 playlist URL in a new tab and it downloads the file, from which I grab the HD playlist URL. Then I just use ffmpeg through cmd with that URL and it's able to download the video.

**Comment by StevenDTX** [comment]
bump :)

**Comment by StevenDTX** [comment]
Thanks @remitamine , it works great.
