### ISSUE TITLE
Is mms still supported?

### ISSUE THREAD

**Issue by slcmalec** [rg3/youtube-dl#10838]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.02**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v 'mms://kentro.kaist.ac.kr/200907/MilesReid(0709).wmv'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'mms://kentro.kaist.ac.kr/200907/MilesReid(0709).wmv']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.02
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.4, ffprobe 3.1.4
[debug] Proxy map: {}
[generic] MilesReid(0709): Requesting header
WARNING: Could not send HEAD request to mms://kentro.kaist.ac.kr/200907/MilesReid(0709).wmv: <urlopen error unknown url type: mms>
[generic] MilesReid(0709): Downloading webpage
ERROR: Unable to download webpage: <urlopen error unknown url type: mms> (caused by URLError(u'unknown url type: mms',))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 402, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 454, in _open
    'unknown_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1265, in unknown_open
    raise URLError('unknown url type: %s' % type)
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: mms://kentro.kaist.ac.kr/200907/MilesReid(0709).wmv

---

### Description of your *issue*, suggested solution and other information
I'm trying to download some files that are streaming through mms (one of them is listed above). The readme says this should work as long as I have mpv or mplayer installed. I have both, and it's still telling me that mms is an unknown type. Am I just missing something?

I realize mms support is probably not remotely at the top of your todo list, but I thank you for any help you can offer!

**Comment by yan12125** [comment]
IIRC direct MMS links weren't supported. In the next version they will.
