### ISSUE TITLE
youtube-dl under java , help needed

### ISSUE THREAD

**Issue by siddht1** [rg3/youtube-dl#10841]
i have been coding so that youtube-dl could work directly from java 

method 1:
java code --> jvm ---> python ---> youtube-dl 

method 2:
java code --> jvm ---> jython ---> youtube-dl 

both of them shows error  when i call  file __main__.py  from my java  code
please assistme 

error shown

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by yan12125** [comment]
Jython has lots of bugs. As of now method 2 does not work. Anyway please paste the error message.

**Comment by siddht1** [comment]
surely  ,  under jython youtube-dl is able to work  with minor fixes ,  would create a new repo to maintain it
