### ISSUE TITLE
Patreon for youtube-dl

### ISSUE THREAD

**Issue by wamatt** [rg3/youtube-dl#10852]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---
### Description of your *issue*, suggested solution and other information

Just wanted to say to the core team what a fantastic job you folks are doing. 👍 

Myself and others would love to be able to support the project in non-git ways. Perhaps it would be ok to consider having a Patreon (or similar) account?

**Comment by dstftw** [comment]
I don't think we will ever do any crowd-funding or at least while we have enough donations to cover our hosting expenses. Also I personally don't want to take any responsibility that may be related to this. youtube-dl is open source project and provides you no guarantees, takes no responsibilties and gives no promises, you use it solely at your own risk.
Donations page we have is generally enough if you are willing to donate.

**Comment by Hrxn** [comment]
Patreon isn't necessarily crowdfunding, it can simply be used as a platform for donations. No binding agreement involving responsibilities. Unless someone explicitly wants to.

**Comment by yan12125** [comment]
I guess not everyone know how to donate to youtube-dl as http://rg3.github.io/youtube-dl/donations.html is not listed on the main page. (#2524) IMO Paypal and Bitcoin is enough.
