### ISSUE TITLE
Can't download 360 video from Facebook

### ISSUE THREAD

**Issue by yvonneng** [rg3/youtube-dl#10850]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --verbose https://www.facebook.com/WITNESS/videos/10154958249510329/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/WITNESS/videos/10154958249510329/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.02
[debug] Python version 2.7.6 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0, ffprobe 3.0, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 10154958249510329: Downloading webpage
ERROR: Cannot find video formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 355, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 334, in _real_extract
    webpage, info_dict = self._extract_from_url(real_url, video_id, fatal_if_no_video=False)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 301, in _extract_from_url
    raise ExtractorError('Cannot find video formats')
ExtractorError: Cannot find video formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.facebook.com/WITNESS/videos/10154958249510329/

---

### Description of your *issue*, suggested solution and other information

I can't seem to download 360-video from Facebook.  I've downloaded other videos from this FB page no problem.

**Comment by yan12125** [comment]
d9ee2e5 fixed detection and this video can be downloaded now. Note that 3D videos are actually 6 small videos from different cameras, so you need a 3D-enabled video player to play it correctly.

**Comment by raj6996** [comment]
how to batch download from video category: 
expl: https://www.facebook.com/acervoarrocha.com.br/videos/

**Comment by yan12125** [comment]
@raj6996 User videos are not supported yet. See #10563

**Comment by endeavorfrazer** [comment]
If you like to download 360 degree vr videos from Facebook, youtube or porn video websites, you may try this method http://www.allavsoft.com/how-to/download-360-video-from-facebook.html
