### ISSUE TITLE
youtube-dl does not sleeping at all

### ISSUE THREAD

**Issue by hamzazia1** [rg3/youtube-dl#10865]
Hi,

I am using youtube-dl version 2016.10.02 installed through pip with python version 2.7.2 GCC 4.9 20140827 on android version 4.04.

I am invoking youtube-dl through another python script with the following options and this manner (fragment shown only)
	`	ydl_opts = {
			'sleep': sleepinterval,
			'verbose': True,
			'useragent' : useragent,      
			'username' : username,     
			'password': password,       
			'abortonerror' : True,
			'continue' : True,
			'nooverwrites': True,
			'playliststart': playliststart,
			}     
		with youtube_dl.YoutubeDL(ydl_opts) as ydl:
			ydl.download([courseurl])
`

What I am observing is that youtube-dl is not sleeping at all for the specified in the _sleepinterval_ variable

For the json key of sleep I have tried variations such as sleep-interval, sleepinterval but nothing can put youtube-dl to sleep between downloading consecutive videos in the playlist. There is a random 3-5 seconds delay to avoid throttling which is the default behavior of youtube-dl.

What option should I use so that youtube-dl sleeps.

Thanks in advance for your time

**Comment by dstftw** [comment]
It's not `sleep` but `sleep_interval`.

**Comment by hamzazia1** [comment]
Thanks @dstftw it worked
