### ISSUE TITLE
 ERROR: ffprobe or avprobe not found. Please install one.

### ISSUE THREAD

**Issue by imadsh** [rg3/youtube-dl#10868]
Hi , 
i can't download youtube as mp3
i'm using RedHat Enterprise 7.2 Linux 
i'm using the latest version of youtube-dl 

my command line 
 sudo /usr/local/bin/youtube-dl --verbose --extract-audio 'https://www.youtube.com/watch?v=PEVUFKfpp5Y'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--extract-audio', u'https://www.youtube.com/watch?v=PEVUFKfpp5Y']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.02
[debug] Python version 2.7.5 - Linux-3.10.0-327.28.3.el7.x86_64-x86_64-with-redhat-7.2-Maipo
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] PEVUFKfpp5Y: Downloading webpage
[youtube] PEVUFKfpp5Y: Downloading video info webpage
[youtube] PEVUFKfpp5Y: Extracting video information
[youtube] PEVUFKfpp5Y: Downloading MPD manifest
[youtube] PEVUFKfpp5Y: Downloading MPD manifest
[debug] Invoking downloader on u'https://r2---sn-n4v7kn76.googlevideo.com/videoplayback/id/3c455414a7e9a796/itag/140/source/youtube/requiressl/yes/mn/sn-n4v7kn76/mm/31/mv/m/pl/20/ms/au/nh/IgpwcjA0LnNqYzA3Kg01Mi45NS4yMTYuMTEy/initcwndbps/7243750/ratebypass/yes/mime/audio%2Fmp4/otfp/1/gir/yes/clen/1818768/lmt/1384815770568646/dur/114.474/mt/1475845313/signature/0986C9D4C0EF249D72E640FF85F9D9463D824E63.3553551E44D5636B6448A2F0141030C5B3331540/upn/wVqhXQ4rQ0c/key/dg_yt0/ip/52.53.178.145/ipbits/0/expire/1475867457/sparams/ip,ipbits,expire,id,itag,source,requiressl,mn,mm,mv,pl,ms,nh,initcwndbps,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 13
[download] Destination: 9 months old twins dancing and trying to get the music back-PEVUFKfpp5Y.m4a
[download] 100% of 1.73MiB in 00:00
WARNING: PEVUFKfpp5Y: writing DASH m4a. Only some players support this container. Install ffmpeg or avconv to fix this automatically.
ERROR: ffprobe or avprobe not found. Please install one.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1837, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 229, in run
    filecodec = self.get_audio_codec(path)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 144, in get_audio_codec
    raise PostProcessingError('ffprobe or avprobe not found. Please install one.')
PostProcessingError

any solution for this please ?

**Comment by yan12125** [comment]
As stated in the error message, install one of them. ```--extract-audio``` requires it.

**Comment by imadsh** [comment]
how can i install them ? ? ? i couldn't install both

**Comment by yan12125** [comment]
In general they're in libav or avconv or ffmpeg packages.

**Comment by imadsh** [comment]
i tried a lot but i couldn't file the command for any of theses package with red hat

**Comment by yan12125** [comment]
Seems Red Hat does not provide ffmpeg/libav to RHEL, so you'll need to compile it manually.
