### ISSUE TITLE
Allocine error

### ISSUE THREAD

**Issue by GuillaumeAmat** [rg3/youtube-dl#10860]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl "http://www.allocine.fr/article/fichearticle_gen_carticle=18656511.html" -v
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'http://www.allocine.fr/article/fichearticle_gen_carticle=18656511.html', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.02
[debug] Python version 2.7.12 - Linux-4.7.5-200.fc24.x86_64-x86_64-with-fedora-24-Twenty_Four
[debug] exe versions: ffmpeg 3.0.3, ffprobe 3.0.3
[debug] Proxy map: {}
[Allocine] 18656511: Downloading webpage
ERROR: Unable to extract data model; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 355, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/allocine.py", line 69, in _real_extract
    model = self._search_regex(r'data-model="([^"]+)">', webpage, 'data model')
  File "./youtube-dl/youtube_dl/extractor/common.py", line 658, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract data model; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
---

Be carefull to not break this kind of url though : http://www.allocine.fr/video/video-19565387
They are still working ;)

Thanks for your good work anyway!

**Comment by yan12125** [comment]
Thanks for the report. It will be fixed in the next version.
