### ISSUE TITLE
Can't download video from FB in 1080

### ISSUE THREAD

**Issue by shadowfolder** [rg3/youtube-dl#10870]
Here is url: https://www.facebook.com/video.php?v=1767461283528622
When i'm trying to download, youtube-dl downloading only 720
Here is output:
youtube-dl https://www.facebook.com/video.php?v=1767461283528622 -F
[facebook] 1767461283528622: Downloading webpage
[info] Available formats for 1767461283528622:
format code                      extension  resolution note
progressive_sd_src               mp4        unknown
progressive_sd_src_no_ratelimit  mp4        unknown
progressive_hd_src               mp4        unknown
progressive_hd_src_no_ratelimit  mp4        unknown    (best)

Or i'm typing invalid command? How i can download this video in 1080p?

**Comment by shadowfolder** [comment]
Guys? Anyone?

**Comment by yan12125** [comment]
This video is gone or not public anymore.

**Comment by shadowfolder** [comment]
What about this https://www.facebook.com/CWLegendsofTomorrow/videos/1770434619897955/ ?

**Comment by yan12125** [comment]
> What about this https://www.facebook.com/CWLegendsofTomorrow/videos/1770434619897955/ ?

In Firefox, it plays a 720p video when "HD" option is checked.

**Comment by shadowfolder** [comment]
Youtube-dl's user agent problem? In chrome i have 1080p http://imgur.com/a/3EI3a
Any suggestions how i can download 1080p with current yt-dl version?

**Comment by yan12125** [comment]
Got up to 720p too in Chrome:
![screenshot from 2016-10-14 18-24-16](https://cloud.githubusercontent.com/assets/1937689/19384444/e997c080-923b-11e6-8490-4d01883f2c81.png)

**Comment by yan12125** [comment]
Superseded by #11073, in which I can get the 1080P version from the provided link.
