### ISSUE TITLE
Please re-consider again adding support for gloria.tv

### ISSUE THREAD

**Issue by adamryczkowski** [rg3/youtube-dl#10885]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

## The issue itself:

I know that in #9553 you decided that the hosted material is copyrighted. I have a counter-example: a public sermon done by a priest Olszewski https://gloria.tv/video/NsFxeem1KCgT1isvRm4V6k3vF, which is incidentally also available on already present extractor for youtube: https://www.youtube.com/watch?v=MH7uPs7RSZc . 

Generally, the gloria.tv is full of recorded radio and tv streams. Maybe some of them are copyrighted, but most are of political/religious nature with the implicit intent to be as broadly distributed as possible. 

Is my arguing compelling enough to re-open the case for support of gloria.tv, or should I contact the site for written permission?

**Comment by yan12125** [comment]
> Maybe some of them are copyrighted

81.6% of search results on Google are removed. [1] That's not "some". Individual legal videos does not sound persuasive.

> the gloria.tv is full of recorded radio and tv streams

Redistributing full radio and TV streams definitely violates copyrights, at least in my country (Taiwan). If gloria.tv has bought legal permissions from radio and TV stream creators, that's OK. In this case you need to provide some materials, like news about agreements between gloria.tv and other companies. A previous example is QQ music (#5249), who has bought redistribution permissions from Warner, Sony and more music producing companies.

[1] https://www.google.com/transparencyreport/removals/copyright/searchdata/domains/?id=gloria.tv
