### ISSUE TITLE
ABC iView videos without an episode number or title don't download

### ISSUE THREAD

**Issue by zayuim** [rg3/youtube-dl#10895]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
$ youtube-dl --verbose http://iview.abc.net.au/programs/diaries-of-a-broken-mind/ZX9735A001S00
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://iview.abc.net.au/programs/diaries-of-a-broken-mind/ZX9735A001S00']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.4, ffprobe 3.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[abc.net.au:iview] ZX9735A001S00: Downloading webpage
[abc.net.au:iview] ZX9735A001S00: Downloading f4m manifest
[abc.net.au:iview] ZX9735A001S00: Downloading m3u8 information
WARNING: unable to extract episodeNumber; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract episode_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 445, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 435, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 705, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 751, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1435, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1500, in process_info
TypeError: object of type 'NoneType' has no len()
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Downloading an ABC iView video that doesn't have any episode number or title (e.g. a documentary such as http://iview.abc.net.au/programs/diaries-of-a-broken-mind/ZX9735A001S00) will result in an error in which the script failed to find an episode number or title

**Comment by yan12125** [comment]
Thanks for the report. Support for such videos will be fixed in the next version.
