### ISSUE TITLE
orf tvthek: urls changed (old give 500, new give "unsupported URL")

### ISSUE THREAD

**Issue by chrysn** [rg3/youtube-dl#10898]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.07**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
guest@hephaistos:~$ ./youtube-dl http://tvthek.orf.at/profile/Universum/35429 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://tvthek.orf.at/profile/Universum/35429', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.7.12+ - Linux-4.8.0-rc6-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 3.1.3-2, avprobe 3.1.3-2, ffmpeg 3.1.3-2, ffprobe 3.1.3-2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 35429: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 35429: Downloading webpage
[generic] 35429: Extracting information
ERROR: Unsupported URL: http://tvthek.orf.at/profile/Universum/35429
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 1648, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: undefined entity: line 12, column 0
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2431, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://tvthek.orf.at/profile/Universum/35429

guest@hephaistos:~$
```

### Description of your *issue*, suggested solution and other information

downloads from orf tvthek do not work any more; old urls went away server-side (500), and the new ones give the above errors. it is not sufficient to just change the "program" regexp part in orf.py to "profile", that results in an error about "Unable to extract segments".

**Comment by mudumat** [comment]
same problem here. example link:
http://tvthek.orf.at/profile/Wie-tickst-du/13886259/Wie-tickst-Du-Sind-Frauen-Menschen-wie-wir-Mit-Stermann-Grissemann/13890849
