### ISSUE TITLE
Vimeo review IE with React

### ISSUE THREAD

**Issue by davekaro** [rg3/youtube-dl#10900]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.07**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.7.12 - Darwin-16.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```

---

The `VimeoReviewIE` (https://github.com/rg3/youtube-dl/blob/55642487f072565bea3b2826b836a1a3159a3807/youtube_dl/extractor/vimeo.py#L800) appears to have stopped working recently. Here is an example

```
$ youtube-dl -v -f http-720p https://vimeo.com/tennisproian/review/126630560/a2f786769e
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'http-720p', u'https://vimeo.com/tennisproian/review/126630560/a2f786769e']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.7.12 - Darwin-16.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3
[debug] Proxy map: {}
[vimeo:review] 126630560: Downloading webpage
ERROR: This video is protected by a password, use the --video-password option
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 858, in _real_extract
    config_url = self._get_config_url(url, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 851, in _get_config_url
    self._verify_video_password(webpage_url, video_id, webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 63, in _verify_video_password
    raise ExtractorError('This video is protected by a password, use the --video-password option', expected=True)
ExtractorError: This video is protected by a password, use the --video-password option
```

Note that you can visit the [vimeo URL](https://vimeo.com/tennisproian/review/126630560/a2f786769e) and download the video with no password. The issue is (I think) that vimeo recently updated this webpage to be a React app. So, if you look at the HTML for the page, it's mostly empty until the React app loads. I debugged youtube-dl myself and at line https://github.com/rg3/youtube-dl/blob/55642487f072565bea3b2826b836a1a3159a3807/youtube_dl/extractor/vimeo.py#L846 - the `webpage` variable only showed the HTML without the rendered HTML from React. So, the `config_url` was blank, even though in the browser it is there (after React loads).

Do any other extractors require JavaScript to work? How can we add JavaScript support to the `VimeoReviewIE`?

**Comment by yan12125** [comment]
Fixed. Thanks for analyzing the problem. That's definitely helpful!

**Comment by davekaro** [comment]
Oh wow, thanks for the quick fix! It works great.
