### ISSUE TITLE
Issue Template for TV Provider support

### ISSUE THREAD

**Issue by jdunn0** [rg3/youtube-dl#10907]
The current new issue template has the options "Bug Report", "Site support request", "Feature request", "Question" and Other.
I was thinking that adding a "TV Provider support request" option to the new issue template would be helpful.
It could have the options of "TV Provider Name", "TV Provider Web Site" along with information how to send account name/password to a developer via a listed email address or something.

**Comment by yan12125** [comment]
There are few requests for adding TV provider supports. Just specify what you want in the description is enough.

> information how to send account name/password to a developer via a listed email address or something.

When a developer is interested, he/she will ask for it and provide his/her email address.
