### ISSUE TITLE
download failure washingtonpost.com

### ISSUE THREAD

**Issue by klwramb72** [rg3/youtube-dl#10903]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.07**
Result of: ~/youtube-dl --version
2016.10.07

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*
error downloading.  ERROR: unable to download video data: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
---

### If the purpose of this *issue* is a *bug report*,  or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ ~/youtube-dl -v https://www.washingtonpost.com/video/sponsored-video/berlin-station-premieres-october-16th-on-epix-at-9-pm-etpt/2016/09/15/c2473e00-7ae1-11e6-8064-c1ddc8a724bb_video.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.washingtonpost.com/video/sponsored-video/berlin-station-premieres-october-16th-on-epix-at-9-pm-etpt/2016/09/15/c2473e00-7ae1-11e6-8064-c1ddc8a724bb_video.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.7.8 - Darwin-16.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-74581-g1bbb5ea-tessus, ffprobe N-74581-g1bbb5ea-tessus
[debug] Proxy map: {}
[washingtonpost] c2473e00-7ae1-11e6-8064-c1ddc8a724bb: Downloading JSON metadata
[washingtonpost] c2473e00-7ae1-11e6-8064-c1ddc8a724bb: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
[washingtonpost] c2473e00-7ae1-11e6-8064-c1ddc8a724bb: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
[washingtonpost] c2473e00-7ae1-11e6-8064-c1ddc8a724bb: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
[debug] Invoking downloader on u'https://videos.posttv.com/washpost-production/TWP/20160915/57d9f5f2e4b0fb838dc932e1/57d9f60de4b030287c57aee2_1439411933958-zgatlb_t_1473902297871_1920_1080_5400.mp4'
ERROR: unable to download video data: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
Traceback (most recent call last):
  File "/Users/slewak/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/Users/slewak/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/Users/slewak/youtube-dl/youtube_dl/downloader/common.py", line 354, in download
    return self.real_download(filename, info_dict)
  File "/Users/slewak/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/Users/slewak/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/Users/slewak/youtube-dl/youtube_dl/utils.py", line 1034, in https_open
    req, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>


```

---

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Attempting to download from washingtonpost tv:
https://www.washingtonpost.com/video/sponsored-video/berlin-station-premieres-october-16th-on-epix-at-9-pm-etpt/2016/09/15/c2473e00-7ae1-11e6-8064-c1ddc8a724bb_video.html

**Comment by yan12125** [comment]
Washington Post sites now require a feature called SNI (Server Name Indication), which is available in Python > 2.7.9 only, and you're using 2.7.8. Please upgrade your Python.
