### ISSUE TITLE
vidzi.com don't work fine

### ISSUE THREAD

**Issue by best-job** [rg3/youtube-dl#10908]
The Website "Vidzi" stopped working well on the day 11/10/2016
Please solve the problem as soon as
thank you very much

**Comment by scottfromsf** [comment]
I think I'm having the same issue as @best-job as Vidzi stopped working for me about a week ago as well. Here's what I'm seeing:

```
$ youtube-dl --verbose http://vidzi.tv/of3940308m2b.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://vidzi.tv/of3940308m2b.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.16
[debug] Python version 2.7.12 - Darwin-16.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.4, ffprobe 3.1.4
[debug] Proxy map: {}
[Vidzi] of3940308m2b: Downloading webpage
ERROR: Unable to extract jwplayer data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vidzi.py", line 40, in _real_extract
    self._search_regex(r'setup\(([^)]+)\)', code, 'jwplayer data'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 659, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract jwplayer data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by best-job** [comment]
Please solve this problem as soon as possible

**Comment by plexigras** [comment]
vidzi.com now en and decodes  the jwplayer code

### example js implementation
```
console.log(decrypt(str1 , 36, 108, str2.split('|')));

function decrypt(p, a, c, k, e, d) {
  while (c--)
    if (k[c]) p = p.replace(new RegExp('\\b' + c.toString(a) + '\\b', 'g'), k[c]);
  return p;
}
```

- str1 is the encrypted jwplayer code
- str2 is a list of keys separated by `|` used to decode str1
- 36 is the radix which appears to be a constant
- 105 is the length of str2.split('|')

str1, str2, 36 and 108 can all be found in the html code.

### regex pcre example
https://regex101.com/r/69uJ1R/1

- group 1: str1
- group 2: 36
- group 3: length of split str2
- group 4: str2

### have fun implementing this in lua

i don't know much lua so this is all i can do to help.

**Comment by scottfromsf** [comment]
Thanks for the analysis, @plexigras. Guess Vidzi is trying to make it difficult to someone to download directly from them. Unfortunately I'm not in a good position to work on a fix for this due to my limited internet access so hopefully a contributor can look at it.

**Comment by scottfromsf** [comment]
Thanks so much, @plexigra and @dstftw .  Vidzi is working great once again.
