### ISSUE TITLE
ERROR: Unable to extract video info

### ISSUE THREAD

**Issue by Sab1703** [rg3/youtube-dl#10901]
Good evening !

When I try to download a video : this is the error message I receive :

```
sab@sab-HP-14-TS-Notebook-PC:~$ youtube-dl http://www.dailymotion.com/video/x221sqs_les-incorruptibles-s-01-e-22-la-dame-aux-oiseaux_shortfilms
[dailymotion] x221sqs: Downloading webpage
[dailymotion] x221sqs: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
sab@sab-HP-14-TS-Notebook-PC:~$ youtube-dl --version
2016.10.07
sab@sab-HP-14-TS-Notebook-PC:~$
```

I've purged and removed youtube-dl then I've installed it again but the message still the same :(

OS : Ubuntu 16.04

Have a nice evening !
Bye
Sab

**Comment by jazzsinatra** [comment]
`
>youtube-dl -U
youtube-dl is up-to-date (2016.10.07)

>youtube-dl --verbose http://www.dailymotion.com/video/k4ZRnWwGOQDIjWk7xkq
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.dailymotion.com/video/k4ZRnWwGOQDIjWk7xkq']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.10.07
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[dailymotion] k4ZRnWwGOQDIjWk7xkq: Downloading webpage
[dailymotion] k4ZRnWwGOQDIjWk7xkq: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpayz9vyze\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpayz9vyze\build\youtube_dl\extractor\common.py", line 356, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpayz9vyze\build\youtube_dl\extractor\dailymotion.py", line 237, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpayz9vyze\build\youtube_dl\extractor\common.py", line 659, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

>`

**Comment by smolleyes** [comment]
same thing here :p

**Comment by pztop** [comment]
I got the same error:
# youtube-dl --verbose -F http://dai.ly/x4x067d
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-F', u'http://dai.ly/x4x067d']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.6.6 - Linux-2.6.32-642.4.2.el6.x86_64-x86_64-with-centos-6.8-Final
[debug] exe versions: ffmpeg 2.6.4, ffprobe 2.6.4
[debug] Proxy map: {}
[generic] x4x067d: Requesting header
[redirect] Following redirect to http://www.dailymotion.com/video/x4x067d_%25E9%2594%25B5%25E9%2594%25B5%25E4%25B8%2589%25E4%25BA%25BA%25E8%25A1%258C-20161011-%25E5%25BC%25A0%25E9%259D%2593%25E9%25A2%2596%25E6%25AF%258D%25E4%25BA%25B2%25E5%258F%2591%25E5%2585%25AC%25E5%25BC%2580%25E4%25BF%25A1-%25E6%2598%258E%25E7%25A1%25AE%25E5%258F%258D%25E5%25AF%25B9%25E5%25A5%25B3%25E5%2584%25BF%25E4%25B8%258E%25E5%2586%25AF%25E8%25BD%25B2%25E5%25A9%259A%25E4%25BA%258B_tv
[dailymotion] x4x067d: Downloading webpage
[dailymotion] x4x067d: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 237, in _real_extract
    'video info', flags=re.MULTILINE),
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 659, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Thanks for the report. Dailymotion support will be back in the next version.
