### ISSUE TITLE
Issue : IQIYI not downloading 1080P video again

### ISSUE THREAD

**Issue by ztytian** [rg3/youtube-dl#10906]
I'm using the latest version of 2016.10.07
I failed to download any 1080P video from IQIYI since a few days ago.
Only 540P available.
It seems that something has changed at IQIYI.

Nothing special was spotted in the debug log, bug the fragments found was less than it used to have. The size of downloaded video shrinked to half. Besides, there's nothing different between the 1080P downloads I had before.

**Comment by ztytian** [comment]
Problem solved after getting cookies.txt of my VIP account
So there can be two explanations:
1st: iQiyi changed sth back
2nd:They somehow blocked non-VIP users from downloading 1080P contents

**Comment by yan12125** [comment]
Any example video?

**Comment by ztytian** [comment]
After re-downloading the video it was 1080P again.
Seems to be a temporary issue.

**Comment by yan12125** [comment]
OK. If you have any new finding, feel free to leave comments or open a new issue.
