### ISSUE TITLE
parliamentliveuk.py - case sensitivity in URLs

### ISSUE THREAD

**Issue by edjw** [rg3/youtube-dl#10912]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.12
[debug] Python version 2.7.10 - Darwin-16.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information
The URLs for the pages on the site parliamentlive.tv appear to be case-insensitive but parliamentliveuk.py appears to require that URL needs to be changed to upper case Event and Index

This URL works in youtube-dl: http://parliamentlive.tv/Event/Index/3f24936f-130f-40bf-9a5d-b3d6479da6a4

This URL doesn't work: http://parliamentlive.tv/event/index/3f24936f-130f-40bf-9a5d-b3d6479da6a4

youtube-dl http://parliamentlive.tv/event/index/3f24936f-130f-40bf-9a5d-b3d6479da6a4
[generic] 3f24936f-130f-40bf-9a5d-b3d6479da6a4: Requesting header
[redirect] Following redirect to http://parliamentlive.tv/home/_404?aspxerrorpath=/event/index/3f24936f-130f-40bf-9a5d-b3d6479da6a4
[generic] 3f24936f-130f-40bf-9a5d-b3d6479da6a4: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3f24936f-130f-40bf-9a5d-b3d6479da6a4: Downloading webpage
[generic] 3f24936f-130f-40bf-9a5d-b3d6479da6a4: Extracting information
ERROR: Unsupported URL: http://parliamentlive.tv/home/_404?aspxerrorpath=/event/index/3f24936f-130f-40bf-9a5d-b3d6479da6a4

**Comment by yan12125** [comment]
Thanks for the report. URLs on parliamentlive.uk are now matched case-insensitively.
