### ISSUE TITLE
ERROR: YouTube said: The uploader has not made this video available in your country.

### ISSUE THREAD

**Issue by andrewhilson** [rg3/youtube-dl#1091]
Hi,

I can't get this to download some youtube videos. I receive the error:

ERROR: YouTube said: The uploader has not made this video available in your country.

examples:
http://www.youtube.com/watch?v=BrbxWOMpwfs
http://www.youtube.com/watch?v=LrUvu1mlWco

---

[root@vps scripts]# python2.7 ./youtube-dl http://www.youtube.com/watch?v=LrUvu1mlWco --max-quality 22 -x --audio-format m4a -o '/var/www/html/storage/%(id)s.%(ext)s' -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.youtube.com/watch?v=LrUvu1mlWco', '--max-quality', '22', '-x', '--audio-format', 'm4a', '-o', '/var/www/html/storage/%(id)s.%(ext)s', '-v']
[debug] youtube-dl version 2013.07.19
[debug] Python version 2.7.3 - Linux-2.6.18-348.el5xen-x86_64-with-redhat-5.9-Final
[debug] Proxy map: {}
[youtube] Setting language
[youtube] LrUvu1mlWco: Downloading video webpage
[youtube] LrUvu1mlWco: Downloading video info webpage
ERROR: YouTube said: The uploader has not made this video available in your country.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 312, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 96, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 462, in _real_extract
    raise ExtractorError(u'YouTube said: %s' % video_info['reason'][0], expected=True)
ExtractorError: YouTube said: The uploader has not made this video available in your country.

**Comment by bhattjigar** [comment]
I have similar issue i have some solution for this **YouTube said: This video is available in India only**.
simple youtube-dl command 
youtube-dl  -F  https://www.youtube.com/watch?v=P4z_NkQDLRI
# Solution 
use proxy server from **india** 
**http_proxy="182.74.243.47:3128" youtube-dl -F https://www.youtube.com/watch?v=P4z_NkQDLRI**

# List of india proxy server with speed 
http://spys.ru/free-proxy-list/IN/

**Comment by selfiebd** [comment]
_**join our channel**_
[https://t.me/url_uploder_yv](url)
