### ISSUE TITLE
subtitles not in mkv file

### ISSUE THREAD

**Issue by KevinMcCready** [rg3/youtube-dl#10910]
```
 $ youtube-dl -v https://youtu.be/6ZavARcYf9s
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://youtu.be/6ZavARcYf9s']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.12
[debug] Python version 2.7.12 - Linux-4.4.0-21-generic-i686-athlon-with-LinuxMint-18-sarah
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[youtube] 6ZavARcYf9s: Downloading webpage
[youtube] 6ZavARcYf9s: Downloading video info webpage
[youtube] 6ZavARcYf9s: Extracting video information
[youtube] 6ZavARcYf9s: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.

```

**Comment by yan12125** [comment]
You need to add ```--embed-subs --write-sub``` to your command.

**Comment by KevinMcCready** [comment]
I did the following but only ended up with a vtt text file of the subtitles. This time I have no video.
youtube-dl -v --write-sub https://youtu.be/6ZavARcYf9s
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--write-sub', u'https://youtu.be/6ZavARcYf9s']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.12
[debug] Python version 2.7.12 - Linux-4.4.0-21-generic-i686-athlon-with-LinuxMint-18-sarah
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[youtube] 6ZavARcYf9s: Downloading webpage
[youtube] 6ZavARcYf9s: Downloading video info webpage
[youtube] 6ZavARcYf9s: Extracting video information
[youtube] 6ZavARcYf9s: Downloading MPD manifest
[info] Writing video subtitles to: #Add1Challenge day 90 - Learning New Zealand Sign Language in 90 days-6ZavARcYf9s.en.vtt
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r6---sn-8vq54voxo1-53as.googlevideo.com/videoplayback?id=e996af0117187fdb&itag=134&source=youtube&requiressl=yes&ms=au&mv=m&pl=22&initcwndbps=1673750&mm=31&mn=sn-8vq54voxo1-53as&ratebypass=yes&mime=video/mp4&gir=yes&clen=56753066&lmt=1472123201612786&dur=1498.951&mt=1476354410&signature=2DF08BCCB28EED9211E58948CBC2241450E96950.4D04E33261AE5BD81119D10C01D4ED822F6FD0CA&upn=2KJFlinESmA&key=dg_yt0&ip=47.72.219.230&ipbits=0&expire=1476376451&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,pl,initcwndbps,mm,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: #Add1Challenge day 90 - Learning New Zealand Sign Language in 90 days-6ZavARcYf9s.f134.mp4
[download] 100% of 54.12MiB in 00:47
[debug] Invoking downloader on u'https://r6---sn-8vq54voxo1-53as.googlevideo.com/videoplayback?id=e996af0117187fdb&itag=251&source=youtube&requiressl=yes&ms=au&mv=m&pl=22&initcwndbps=1673750&mm=31&mn=sn-8vq54voxo1-53as&ratebypass=yes&mime=audio/webm&gir=yes&clen=17634289&lmt=1472136564860416&dur=1498.961&mt=1476354410&signature=592CBA70515D1175F7078A31EE231D56073ECDD6.3B5C63CF6D3C37316CD6D93E4BB917F38FE587BB&upn=2KJFlinESmA&key=dg_yt0&ip=47.72.219.230&ipbits=0&expire=1476376451&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,pl,initcwndbps,mm,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: #Add1Challenge day 90 - Learning New Zealand Sign Language in 90 days-6ZavARcYf9s.f251.webm
[download] 100% of 16.82MiB in 00:14
[ffmpeg] Merging formats into "#Add1Challenge day 90 - Learning New Zealand Sign Language in 90 days-6ZavARcYf9s.mkv"
[debug] ffmpeg command line: ffmpeg -y -i 'file:#Add1Challenge day 90 - Learning New Zealand Sign Language in 90 days-6ZavARcYf9s.f134.mp4' -i 'file:#Add1Challenge day 90 - Learning New Zealand Sign Language in 90 days-6ZavARcYf9s.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:#Add1Challenge day 90 - Learning New Zealand Sign Language in 90 days-6ZavARcYf9s.temp.mkv'
Deleting original file #Add1Challenge day 90 - Learning New Zealand Sign Language in 90 days-6ZavARcYf9s.f134.mp4 (pass -k to keep)
Deleting original file #Add1Challenge day 90 - Learning New Zealand Sign Language in 90 days-6ZavARcYf9s.f251.webm (pass -k to keep)
