### ISSUE TITLE
[Once][CBS] m3u8 URL is no longer correct.

### ISSUE THREAD

**Issue by Forcer78** [rg3/youtube-dl#10918]
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.10.12_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.12**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

```
$ ./youtube_dl/__main__.py -vF http://www.cbs.com/shows/star_trek/video/620451538/star-trek-the-original-series-mirror-mir
ror/
[debug] System config: []
[debug] User config: [u'--no-playlist']
[debug] Command-line args: [u'-vF', u'http://www.cbs.com/shows/star_trek/video/620451538/star-trek-the-original-series-mirror-mirror/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.12
[debug] Git HEAD: 580d411
[debug] Python version 2.7.12 - Darwin-16.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.4, ffprobe 3.1.4, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://127.0.0.1:8118', 'https': 'http://127.0.0.1:8118'}
[CBS] 620451538: Downloading XML
[CBS] 620451538: Downloading RTMP SMIL data
[CBS] 620451538: Downloading WIFI SMIL data
[CBS] 620451538: Checking video URL
[CBS] 620451538: Checking video URL
[CBS] 620451538: Downloading 3G SMIL data
[CBS] 620451538: Checking video URL
[CBS] 620451538: Checking video URL
[CBS] 620451538: Downloading StreamPack SMIL data
[CBS] 620451538: Downloading m3u8 information
[CBS] 620451538: Downloading OnceURL SMIL data
[CBS] 620451538: Checking video URL
[CBS] 17ce6dae-c222-462b-86ea-c0fd00c1d465: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[CBS] 620451538: Downloading JSON metadata
[info] Available formats for 620451538:
format code  extension  resolution note
hls-meta     mp4        multiple   Quality selection URL
hls-47       mp4        audio only   47k , mp4a.40.2
http-150     mp4        400x304     150k
hls-166      mp4        288x224     166k , avc1.66.30, mp4a.40.2
http-240     mp4        400x304     240k
hls-311      mp4        288x224     311k , avc1.66.30, mp4a.40.2
rtmp-364     flv        384x292     364k
http-440     mp4        400x304     440k
rtmp-496     flv        480x360     496k
hls-569      mp4        384x288     569k , avc1.66.30, mp4a.40.2
http-740     mp4        640x486     740k
rtmp-796     flv        480x360     796k
hls-879      mp4        480x360     879k , avc1.66.30, mp4a.40.2
hls-1290     mp4        576x432    1290k , avc1.77.30, mp4a.40.2
rtmp-1296    flv        480x360    1296k
hls-1907     mp4        704x540    1907k , avc1.77.30, mp4a.40.2
rtmp-1928    flv        640x480    1928k  (best)
```

---
### Description of your _issue_, suggested solution and other information

The higher-resolution video options from CBS (720p etc.) haven't been detected for several months now. The m3u8 playlist that contains them is not where the extractors think it is. In this example, the code is calling `_extract_once_formats()` in once.py and building the URL `http://once.unicornmedia.com/now/master/playlist/bb0b18ba-64f5-4b1b-a29f-0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/17ce6dae-c222-462b-86ea-c0fd00c1d465/content.m3u8` using the `ADAPTIVE_URL_TEMPLATE`, but this is returning a 404. If the path has changed, this should be updated.

**Comment by Forcer78** [comment]
Re: the "account-needed" tag:
CBS provides free videos that sometimes rotate out but do not require an account. Example: http://www.cbs.com/shows/the_twilight_zone/video/626428813/the-twilight-zone-time-enough-at-last/

However, youtube-dl will actually download any video from the site without the need for an account, and prior to August/September it did so at full quality.

**Comment by remitamine** [comment]
the orginal urls returned from the platform return this error:
```
Error: Media item not found.  Media Item GUID []. Foreign Key []
```
so it's not an error in youtube-dl.
