### ISSUE TITLE
Having problems playing songs Ver 2016.10.12 

### ISSUE THREAD

**Issue by nakashbar** [rg3/youtube-dl#10921]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.12**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.10.12
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by nakashbar** [comment]
Hey,

Im using the youtube_dl as a library on a server and what we see is for w id=DONblKZmDHk  with player //s.ytimg.com/yts/jsbin/player-iw_IL-vfl-d-kGk/base.js the following    return lambda s: initial_function([s])
  File "/base/data/home/apps/s~vodio-int/urlrdr:101.396308480248623455/lib/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/base/data/home/apps/s~vodio-int/urlrdr:101.396308480248623455/lib/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/base/data/home/apps/s~vodio-int/urlrdr:101.396308480248623455/lib/youtube_dl/jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: u'Qv'

Any idea?

**Comment by nakashbar** [comment]
This is the latest log:

uri:lib uritwig$ python -m youtube_dl -v https://www.youtube.com/watch?v=QI1ruAQypxc
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=QI1ruAQypxc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.12
[debug] Git HEAD: 5ddb0a4
[debug] Python version 2.7.8 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.4.3, ffprobe 2.4.3
[debug] Proxy map: {}
[youtube] QI1ruAQypxc: Downloading webpage
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[youtube] QI1ruAQypxc: Downloading video info webpage
[youtube] QI1ruAQypxc: Extracting video information
[youtube] {43} signature length 42.43, html5 player pt_BR-vfl9fBd1-
[youtube] QI1ruAQypxc: Downloading player https://s.ytimg.com/yts/jsbin/player-pt_BR-vfl9fBd1-/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "youtube_dl/extractor/youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "youtube_dl/jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: u'Qv'
 (caused by KeyError(u'Qv',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "youtube_dl/extractor/youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "youtube_dl/jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: u'Qv'
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "youtube_dl/extractor/youtube.py", line 1593, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "youtube_dl/extractor/youtube.py", line 1015, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "youtube_dl/extractor/youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "youtube_dl/jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: u'Qv'
 (caused by KeyError(u'Qv',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

uri:lib uritwig$

**Comment by yan12125** [comment]
Could you run:
```
python -m youtube_dl -v https://www.youtube.com/watch?v=QI1ruAQypxc --write-pages
```
And zip all *.dump files and upload?

**Comment by nakashbar** [comment]
[QI1ruAQypxc_https_-_www.youtube.com_get_video_info_video_id=QI1ruAQypxc_el=info_ps=default_eurl=_gl=US_hl=en.dump.zip](https://github.com/rg3/youtube-dl/files/529392/QI1ruAQypxc_https_-_www.youtube.com_get_video_info_video_id.QI1ruAQypxc_el.info_ps.default_eurl._gl.US_hl.en.dump.zip)

**Comment by urit** [comment]
This is the fix:

    def extract_object(self, objname):

        obj = {}
        obj_m = re.search(
            (r'(?:var\s+)?%s\s*=\s*\{' % re.escape(objname)) +
            r'\s*(?P<fields>([a-zA-Z$0-9]+\s*:\s*function\(.*?\)\s*\{.*?\}(?:,\s*)?)+)' +
            r'\}\s*;',
            self.code)
        fields = obj_m.group('fields')
        # Currently, it only supports function definitions
        fields_m = re.finditer(
            r'(?P<key>[a-zA-Z$0-9]+)\s*:\s*function'
            r'\((?P<args>[a-z,]+)\){(?P<code>[^}]+)}',
            fields)
        for f in fields_m:
            argnames = f.group('args').split(',')
            obj[f.group('key')] = self.build_function(argnames, f.group('code'))


        return obj

**Comment by dstftw** [comment]
There is no such commit 5ddb0a4. You are using a modified version of youtube-dl. You must provide full output with `--dump-pages` with original youtube-dl code.
