### ISSUE TITLE
Iqiyi An extractor error has occurred

### ISSUE THREAD

**Issue by wulue90** [rg3/youtube-dl#10920]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.10.12_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.12**
### Before submitting an _issue_ make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Link:http://www.iqiyi.com/v_19rr9m7zzs.html

youtube-dl.exe -v http://www.iqiyi.com/v_19rr9m7zzs.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.iqiyi.com/v_19rr9m7zzs.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.10.12
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-81256-gd3426fb
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[iqiyi] 551345300: Download playlist page 2
ERROR: An extractor error has occurred. (caused by KeyError('data',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0kv97by3\build\youtube_dl\extractor\common.py", line 356, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0kv97by3\build\youtube_dl\extractor\iqiyi.py", line 340, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0kv97by3\build\youtube_dl\extractor\iqiyi.py", line 326, in _extract_playlist
KeyError: 'data'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0kv97by3\build\youtube_dl\extractor\common.py", line 356, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0kv97by3\build\youtube_dl\extractor\iqiyi.py", line 340, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0kv97by3\build\youtube_dl\extractor\iqiyi.py", line 326, in _extract_playlist
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0kv97by3\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0kv97by3\build\youtube_dl\extractor\common.py", line 362, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('data',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Works fine with the latest git master. Feel free to open new issues if things are still broken.
```
$ youtube-dl -v http://www.iqiyi.com/v_19rr9m7zzs.html --geo-verification-proxy socks4://221.6.206.114:1080 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.iqiyi.com/v_19rr9m7zzs.html', '--geo-verification-proxy', 'socks4://221.6.206.114:1080']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Git HEAD: 01cb57016
[debug] Python version 3.6.1 - Linux-4.10.11-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] 15c0e3e5f7d0b215480e639a0f4ac6c3: Downloading JSON metadata
[debug] Invoking downloader on 'http://cache.m.iqiyi.com/mus/text/204253701/c887741b4393e274223e64a3490c7deb/afbe8fd3d73448c9//20161014/ec/c7/42a124ba96320ebe4014921482d6648d.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=551345300&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1493131157355&qd_sc=4242c7191727d12e045afb258cc54cf0&qypid=551345300_04022000001000000000_4&qd_k=caed79835a69f7818e9bede5eeeeb0c5&qd_ip=221.6.206.114&other='
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 651
[download] Destination: 偶滴歌神啊第3季：2016-10-13期 第12期 謝娜魔性熱舞《癢》-15c0e3e5f7d0b215480e639a0f4ac6c3.mp4
[download]   4.0% of ~761.72MiB at 986.71KiB/s ETA 15:34^CException ignored in: <_io.FileIO name='偶滴歌神啊第3季：2016-10-13期 第12期 謝娜魔性熱舞《癢》-15c0e3e5f7d0b215480e639a0f4ac6c3.mp4.part-Frag26.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='偶滴歌神啊第3季：2016-10-13期 第12期 謝娜魔性熱舞《癢》-15c0e3e5f7d0b215480e639a0f4ac6c3.mp4.part-Frag26.part'>

ERROR: Interrupted by user
Exception ignored in: <_io.FileIO name='偶滴歌神啊第3季：2016-10-13期 第12期 謝娜魔性熱舞《癢》-15c0e3e5f7d0b215480e639a0f4ac6c3.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.FileIO name='偶滴歌神啊第3季：2016-10-13期 第12期 謝娜魔性熱舞《癢》-15c0e3e5f7d0b215480e639a0f4ac6c3.mp4.part' mode='wb' closefd=True>
```
