### ISSUE TITLE
Bad HTML escaping when using --proxy URL

### ISSUE THREAD

**Issue by madduci** [rg3/youtube-dl#10930]
### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl -v --proxy $PROXYURL --add-metadata --embed-thumbnail -x --audio-format mp3 https://www.youtube.com/playlist?list=PLKyb3jXG1Xj_1oMeaaKK6uOeWp6_VXCq6
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.12
[debug] Python version 3.5.2 - Linux-4.4.24-1-MANJARO-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.1.4, ffprobe 3.1.4, rtmpdump 2.4
[debug] Proxy map: {}
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Playlist: https://www.youtube.com/playlist?list=PLKyb3jXG1Xj_1oMeaaKK6uOeWp6_VXCq6

---

### Description of your *issue*, suggested solution and other information

I'm trying to run different proxies from [Hide my Ass](http://proxylist.hidemyass.com/search-1297492#listable) and on most of them I'm getting the error:

`ERROR: Unable to download webpage: <html>
 (caused by BadStatusLine('<html>\r\n',));`

**Comment by dstftw** [comment]
This usually means the proxy misbehaves that is common for public proxies. If you can't normally browse with it are won't be ably to use it with youtube-dl either.
