### ISSUE TITLE
Youtube-dl downloads flawed video from Facebook Live

### ISSUE THREAD

**Issue by danburd** [rg3/youtube-dl#10931]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://www.facebook.com/CousinSalsSureThing/videos/676704372487705/
[debug] System config: ['--restrict-filenames']
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/CousinSalsSureThing/videos/676704372487705/']
[debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.10.12
[debug] Python version 3.5.2 - Linux-4.4.24-2-ARCH-armv7l-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.1.4, ffprobe 3.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 676704372487705: Downloading webpage
[debug] Invoking downloader on 'https://video-iad3-1.xx.fbcdn.net/v/t43.1792-2/14511953_1752015608380891_5938740469470068736_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=0c76dc0af75fd678dd3473d5a7c10bb5&oe=58026BE6'
[download] Destination: Facebook_video_676704372487705-676704372487705.mp4
[download] 100% of 31.09MiB in 00:03
```
---

### Description of your *issue*, suggested solution and other information

The resulting video file downloaded from this command is flawed. It does not play at all in the Chrome OS video player, and attempting to open it in the browser only plays the first frame or first fraction of a second of the video.

**Comment by dstftw** [comment]
That is the problem of Chrome OS video player since it plays fine with vlc and mpv.
