### ISSUE TITLE
falling back on generic extractor pluralsight

### ISSUE THREAD

**Issue by asbcit** [rg3/youtube-dl#10941]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://app.pluralsight.com/player?course=ccn
a-intro-networking&author=ross-bagurdes&name=ccna-intro-networking-m06&clip=0']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.10.16
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] player?course=ccna-intro-networking&author=ross-bagurdes&name=ccna-int
ro-networking-m06&clip=0: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player?course=ccna-intro-networking&author=ross-bagurdes&name=ccna-int
ro-networking-m06&clip=0: Downloading webpage
[generic] player?course=ccna-intro-networking&author=ross-bagurdes&name=ccna-int
ro-networking-m06&clip=0: Extracting information
ERROR: Unsupported URL: https://app.pluralsight.com/player?course=ccna-intro-net
working&author=ross-bagurdes&name=ccna-intro-networking-m06&clip=0
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpna76borx\bu
ild\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpna76borx\bu
ild\youtube_dl\extractor\common.py", line 356, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpna76borx\bu
ild\youtube_dl\extractor\generic.py", line 2431, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://app.pluralsight.com/
player?course=ccna-intro-networking&author=ross-bagurdes&name=ccna-intro-network
ing-m06&clip=0
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://app.pluralsight.com/player?course=ccna-intro-networking&author=ross-bagurdes&name=ccna-intro-networking-m06&clip=0

---

### Description of your *issue*, suggested solution and other information

Dear Sir/Madam,

I can't download a single video of pluralsight and i'm using an updated version of youtube-dl kindly check the below screenshot for more details. thank you. 

http://prnt.sc/cuwuv1

- single video: https://app.pluralsight.com/player?course=ccna-intro-networking&author=ross-bagurdes&name=ccna-intro-networking-m06&clip=0

- cmd line that i used: path/ youtube-dl "link"

specs:
OS: Windows 7 64bit
Python version 2.7

**Comment by asbcit** [comment]
Sir,

what should i do? need to wait for new update?

thank you.

**Comment by dstftw** [comment]
Wait for next release or use codes from master.

**Comment by asbcit** [comment]
is it complicated to do that? maybe i will just wait for the update.

thank you.

**Comment by dstftw** [comment]
Not that much, [developer instructions](https://github.com/rg3/youtube-dl#developer-instructions).
