### ISSUE TITLE
YouTube: Video selection option to only download Live Streams in progress

### ISSUE THREAD

**Issue by andrewparks** [rg3/youtube-dl#10956]
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Scenario: A youtuber makes live streams available from time to time, but does not allow rewinds or downloads after the live stream ends

Problem: Currently impossible to write a script that calls youtube-dl every few minutes and instruct it to ONLY download from a youtube channel URL if there is a current live stream in progress

Proposed solution: Please include a video selection option that will ONLY download any available live streams that are CURRENTLY IN PROGRESS from the youtube channel URL specified

Thank you very much, youtube-dl is fantastic!

**Comment by dstftw** [comment]
Use live stream in progress URL https://www.youtube.com/channel/name/live.
