### ISSUE TITLE
dotsub.com not working

### ISSUE THREAD

**Issue by balunet** [rg3/youtube-dl#10964]
dotsub.com website is not working. Below I attach a trace.

---

```
--$ youtube-dl https://dotsub.com/view/747bcf58-bd59-45b7-8c8c-ac312d084ee6 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://dotsub.com/view/747bcf58-bd59-45b7-8c8c-ac312d084ee6', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.16
[debug] Python version 2.7.6 - Linux-3.13.0-40-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.2.git, ffprobe 2.2.git
[debug] Proxy map: {}
[Dotsub] 747bcf58-bd59-45b7-8c8c-ac312d084ee6: Downloading JSON metadata
[Dotsub] 747bcf58-bd59-45b7-8c8c-ac312d084ee6: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/dotsub.py", line 40, in _real_extract
    webpage, 'video url')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 659, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

**Comment by yan12125** [comment]
Thanks for the report. Vimeo embed will be supported in the next version.
