### ISSUE TITLE
Unable to download certain PBS videos - Could not send HEAD request - 403 Error  

### ISSUE THREAD

**Issue by justanybody** [rg3/youtube-dl#10968]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

c:\PBS>ytdl -v "http://d6uz0or6bt1ws.cloudfront.net/videos/frontline/430d482e-b475-4225-b20a-92b5b5e13e81/13798/hd-mezzanine-16x9/00003103-16x9-mp4-2500k.mp4" -o insideobama.mp4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://d6uz0or6bt1ws.cloudfront.net/videos/frontline/430d482e-b475-4225-b20a-92b5b5e13e81/13798/hd-mezzanine-16x9/00003103-16x9-mp4-2500k.mp4', '-o', 'insideobama.mp4']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.10.07
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 00003103-16x9-mp4-2500k: Requesting header
WARNING: Could not send HEAD request to http://d6uz0or6bt1ws.cloudfront.net/videos/frontline/430d482e-b475-4225-b20a-92b5b5e13e81/13798/hd-mezzanine-16x9/00003103-16x9-mp4-2500k.mp4: HTTP Error 403: Forbidden
[generic] 00003103-16x9-mp4-2500k: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpayz9vyze\build\youtube_dl\extractor\common.py", line 403, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpayz9vyze\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

Hey guys. Firstly I wanted to thank you all for your work. I just recently discovered the downloader and this forum and couldn't be more grateful. Thank all of you who have worked on this and who provide support to the community.

I am running into an issue on the PBS site where some videos will not download, giving me the error I pasted above. This error occurs only on certain videos but with a significant percentage of them, maybe 15-20% of those I've tried to download. The link for the video above is **http://www.pbs.org/video/2325679851/**

A few of the other videos I am also having trouble downloading:
**http://www.pbs.org/video/1468710007/**
**http://www.pbs.org/video/1810338755/**
**http://www.pbs.org/video/1342007771/**

I came across this program randomly, have no experience with code and have been using this (https://www.youtube.com/watch?v=qeqL8TfTwy0) method to download. This works for most videos on the PBS site, but as I said, not all of them.

Any help would be appreciated. Thank you.

**Comment by remitamine** [comment]
http://d6uz0or6bt1ws.cloudfront.net/videos/frontline/430d482e-b475-4225-b20a-92b5b5e13e81/13798/hd-mezzanine-16x9/00003103-16x9-mp4-2500k.mp4 is not available.
all of the other urls you have posted works without a problem.
```
youtube-dl http://www.pbs.org/video/2325679851/
[pbs] 2325679851: Downloading widget/partnerplayer page
[pbs] 2325679851: Downloading portalplayer page
[pbs] 2325679851: Downloading ipad-16x9 video url info
[pbs] 2325679851: Downloading m3u8 information
[pbs] 2325679851: Downloading mp4-baseline-16x9 video url info
[pbs] 2325679851: Downloading mp4-800k-16x9 video url info
[pbs] 2325679851: Checking http-600k video URL
[pbs] 2325679851: http-600k video URL is invalid, skipping
[pbs] 2325679851: Checking http-2500k video URL
[pbs] 2325679851: http-2500k video URL is invalid, skipping
[pbs] 2325679851: Checking http-1200k video URL
[pbs] 2325679851: Checking http-400k video URL
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 323
[download] Destination: FRONTLINE - Inside Obama's Presidency-2325679851.mp4
[download]   0.5% of ~818.69MiB at 320.33KiB/s ETA 42:15
```
```
youtube-dl http://www.pbs.org/video/1468710007/
[pbs] 1468710007: Downloading widget/partnerplayer page
[pbs] 1468710007: Downloading portalplayer page
[pbs] 1468710007: Downloading ipad-16x9 video url info
[pbs] 1468710007: Downloading m3u8 information
[pbs] 1468710007: Downloading mp4-baseline-16x9 video url info
[pbs] 1468710007: Downloading mp4-800k-16x9 video url info
[pbs] 1468710007: Checking http-600k video URL
[pbs] 1468710007: http-600k video URL is invalid, skipping
[pbs] 1468710007: Checking http-2500k video URL
[pbs] 1468710007: http-2500k video URL is invalid, skipping
[pbs] 1468710007: Checking http-1200k video URL
[pbs] 1468710007: Checking http-400k video URL
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 339
[download] Destination: FRONTLINE - Obama's Deal-1468710007.mp4
[download]   0.4% of ~893.40MiB at 238.15KiB/s ETA 44:06
```
```
youtube-dl http://www.pbs.org/video/1810338755/
[pbs] 1810338755: Downloading widget/partnerplayer page
[pbs] 1810338755: Downloading portalplayer page
[pbs] 1810338755: Downloading ipad-16x9 video url info
[pbs] 1810338755: Downloading m3u8 information
[pbs] 1810338755: Downloading mp4-baseline-16x9 video url info
[pbs] 1810338755: Downloading mp4-800k-16x9 video url info
[pbs] 1810338755: Checking http-600k video URL
[pbs] 1810338755: http-600k video URL is invalid, skipping
[pbs] 1810338755: Checking http-2500k video URL
[pbs] 1810338755: http-2500k video URL is invalid, skipping
[pbs] 1810338755: Checking http-1200k video URL
[pbs] 1810338755: Checking http-400k video URL
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 323
[download] Destination: FRONTLINE - Revolution in Cairo-1810338755.mp4
[download]   0.1% of ~663.31MiB at 325.19KiB/s ETA 43:41
```
```
youtube-dl http://www.pbs.org/video/1342007771/
[pbs] 1342007771: Downloading widget/partnerplayer page
[pbs] 1342007771: Downloading portalplayer page
[pbs] 1342007771: Downloading ipad-16x9 video url info
[pbs] 1342007771: Downloading m3u8 information
[pbs] 1342007771: Downloading mp4-baseline-16x9 video url info
[pbs] 1342007771: Downloading mp4-800k-16x9 video url info
[pbs] 1342007771: Checking http-600k video URL
[pbs] 1342007771: http-600k video URL is invalid, skipping
[pbs] 1342007771: Checking http-2500k video URL
[pbs] 1342007771: http-2500k video URL is invalid, skipping
[pbs] 1342007771: Checking http-1200k video URL
[pbs] 1342007771: Checking http-400k video URL
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 338
[download] Destination: FRONTLINE - The Card Game-1342007771.mp4
[download]   0.3% of ~684.30MiB at 319.82KiB/s ETA 38:52
```

**Comment by justanybody** [comment]
Using the method shown in the video (copying the link address of the desired .m3u8 file), I am unable to download. Just tried again. Is there another method that I should be using?

**Comment by dstftw** [comment]
Did you even read @remitamine's post?

**Comment by remitamine** [comment]
yes, i read the post but didn't look at the video.

**Comment by justanybody** [comment]
I did. I suppose I should have clarified. I tried downloading with the links he said were working. I even tried copying his method which differs from the one I was taking. The Obama's Deal link for example:

c:\PBS>ytdl "http://www.pbs.org/video/1468710007/" -o obamasdeal.mp4
[pbs] 1468710007: Downloading widget/partnerplayer page
[pbs] 1468710007: Downloading portalplayer page
[pbs] 1468710007: Downloading ipad-16x9 video url info
[pbs] 1468710007: Downloading m3u8 information
[pbs] 1468710007: Downloading mp4-baseline-16x9 video url info
[pbs] 1468710007: Downloading mp4-800k-16x9 video url info
[pbs] 1468710007: Checking http-600k video URL
[pbs] 1468710007: http-600k video URL is invalid, skipping
[pbs] 1468710007: Checking http-2500k video URL
[pbs] 1468710007: http-2500k video URL is invalid, skipping
[pbs] 1468710007: Checking http-1200k video URL
[pbs] 1468710007: Checking http-400k video URL
[download] Destination: obamasdeal.mp4
ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.

**Comment by dstftw** [comment]
>ffmpeg or avconv could not be found. Please install one.

**Comment by justanybody** [comment]
Alright, just downloaded ffmpeg but am unsure how to unpack/install it. I'll have to play with it later when I have some time. Thanks for pointing me in a direction.
