### ISSUE TITLE
Vimeo not working

### ISSUE THREAD

**Issue by balunet** [rg3/youtube-dl#10963]
Vimeo extractor does not work. Below you'll find a trace:

---

```
--$ youtube-dl https://vimeo.com/187161170 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://vimeo.com/187161170', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.16
[debug] Python version 2.7.6 - Linux-3.13.0-40-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.2.git, ffprobe 2.2.git
[debug] Proxy map: {}
[vimeo] 187161170: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 403, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

**Comment by remitamine** [comment]
```
youtube-dl https://vimeo.com/187161170
[vimeo] 187161170: Downloading webpage
[vimeo] 187161170: Extracting information
[vimeo] 187161170: Downloading webpage
[vimeo] 187161170: Downloading JSON metadata
[vimeo] 187161170: Checking Original video URL
[vimeo] 187161170: Original video URL is invalid, skipping
[vimeo] 187161170: Downloading m3u8 information
[download] Destination: We Buy Houses Milwaukee-187161170.mp4

10/19 09:12:01 [NOTICE] Downloading 1 item(s)
[#68c97a 4.3MiB/4.6MiB(93%) CN:2 DL:345KiB]                                    
10/19 09:12:16 [NOTICE] Download complete: /home/amine/Videos/We Buy Houses Milwaukee-187161170.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
68c97a|OK  |   333KiB/s|/home/amine/Videos/We Buy Houses Milwaukee-187161170.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 4893938 bytes
[download] 100% of 4.67MiB
```

**Comment by vibrasphere** [comment]
Can confirm, not working.

**Comment by siddht1** [comment]
please update your packages

**Comment by siddht1** [comment]
youtube-dl https://vimeo.com/187161170 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://vimeo.com/187161170', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.16
[debug] Python version 2.7.12 - Linux-4.4.0-21-generic-x86_64-with-LinuxMint-18-sarah
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[vimeo] 187161170: Downloading webpage
[vimeo] 187161170: Extracting information
[vimeo] 187161170: Downloading webpage
[vimeo] 187161170: Downloading JSON metadata
[vimeo] 187161170: Checking Original video URL
[vimeo] 187161170: Downloading m3u8 information
[debug] Invoking downloader on u'https://vimeo.com/187161170/download?t=1476868694&v=618009219&s=cbdaf95e257d1912b3a66174acaef0ad67d4c7a74be8e452864b7c8b4d78fd46'
[download] Destination: We Buy Houses Milwaukee-187161170.asx
[download] 100% of 7.08MiB in 00:11

**Comment by vibrasphere** [comment]
http://i.imgur.com/Jw7ZEK0.png

who's user dst?

**Comment by remitamine** [comment]
@vibrasphere, it's better to post the log in it's text form not as an image.
your error is diffrent than the error reported in this issue, the error you're getting happen for an ondemend(possibly drm protected) video https://vimeo.com/ondemand/rocketjump/185420111.

**Comment by balunet** [comment]
It's not a bug. Vimeo blocked my IP address due to a "high number of connection errors".
I managed to unblock myself by going through the browser and filling a captcha that was prompted to me.

Apologies for the inconvenience.
