### ISSUE TITLE
 lynda returned error: Session has expired

### ISSUE THREAD

**Issue by iitjee** [rg3/youtube-dl#10966]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

`youtube-dl -v  https://www.lynda.com/Web-tutorials/role-HTML/483022/505734-4.html --username abc@gmail.com --password abc`

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.lynda.com/Web-tutorials/role-HTML/483022/505734-4.html', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.30
[debug] Python version 2.7.10 - Darwin-16.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[lynda] Downloading signin page
[lynda] Submitting email
[lynda] Submitting password
[lynda] 505734: Downloading video JSON
ERROR: lynda returned error: Session has expired
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_dl/extractor/lynda.py", line 124, in _real_extract
    'lynda returned error: %s' % video['Message'], expected=True)
ExtractorError: lynda returned error: Session has expired
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.lynda.com/Web-tutorials/role-HTML/483022/505734-4

- Playlist: https://www.lynda.com/Web-tutorials/Becoming-Web-Developer-Full-Stack-vs-Front-End/483022-2.html
---

### Description of your *issue*, suggested solution and other information

I'm a **BASIC-MONTHLY** user of Lynda.com

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by iitjee** [comment]
```

**Comment by yan12125** [comment]
> [debug] youtube-dl version 2016.07.30

FYI: the latest version is 2016.10.16.

**Comment by iitjee** [comment]
Ah right! I'd to restart the terminal to run with the updated version. Thanks! :)
