### ISSUE TITLE
[AdultSwim] Unable to find stream or clips

### ISSUE THREAD

**Issue by stepshal** [rg3/youtube-dl#10979]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
[AdultSwim] friday-october-14th-2016: Downloading webpage
ERROR: Unable to find stream or clips; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/adultswim.py", line 172, in _real_extract
    raise ExtractorError('Unable to find stream or clips')
youtube_dl.utils.ExtractorError: Unable to find stream or clips; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

http://www.adultswim.com/videos/toonami/friday-october-14th-2016/

**Comment by yan12125** [comment]
Thanks will be fixed in the next version.
