### ISSUE TITLE
Can't downlaod the new Logan trailre.

### ISSUE THREAD

**Issue by olikami** [rg3/youtube-dl#10978]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x]  I've **verified** and **I assure** that I'm running youtube-dl **2016.10.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
```
$ youtube-dl -v http://trailers.apple.com/trailers/fox/logan/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://trailers.apple.com/trailers/fox/logan/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.19
[debug] Python version 2.7.12 - Linux-4.4.0-43-generic-x86_64-with-LinuxMint-18-sarah
[debug] exe versions: ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1
[debug] Proxy map: {}
[appletrailers] logan: Downloading webpage
[appletrailers] 18067: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 404: Not Found
[appletrailers] logan: Downloading XML
[appletrailers] logan-trailer-1: Downloading settings json
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 403, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```

---

### Description of your *issue*, suggested solution and other information

Not possible to download the video. It plays fine in my browser. I can download other videos (tested with [this](http://trailers.apple.com/trailers/marvel/guardians-of-the-galaxy-vol-2/)) form trailers.apple.com.

**Comment by remitamine** [comment]
```
youtube-dl http://trailers.apple.com/trailers/fox/logan/
[appletrailers] logan: Downloading webpage
[appletrailers] 18067: Downloading JSON metadata
[download] Downloading playlist: Logan
[appletrailers] playlist Logan: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[download] Destination: Trailer-logan-trailer.mov

10/20 18:01:37 [NOTICE] Downloading 1 item(s)
[#fb70f0 0.9MiB/67MiB(1%) CN:4 DL:96KiB ETA:11m50s]
```

**Comment by olikami** [comment]
After purging, reinstalling and some time it worked fine. Thanks for this awesome tool.
