### ISSUE TITLE
Unable to download orlandosentinel.com's videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#10973]
For an example:
$ youtube-dl -v http://www.orlandosentinel.com/entertainment/news/91698282-132.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.orlandosentinel.com/entertainment/news/91698282-132.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.19
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 3.1.3-1, ffprobe 3.1.3-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 91698282-132: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 91698282-132: Downloading webpage
[generic] 91698282-132: Extracting information
ERROR: Unsupported URL: http://www.orlandosentinel.com/entertainment/news/91698282-132.html
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2431, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.orlandosentinel.com/entertainment/news/91698282-132.html

Thank you in advance. :)

**Comment by yan12125** [comment]
Superseded by #11155
