### ISSUE TITLE
subtitles not found on some YouTube videos

### ISSUE THREAD

**Issue by az0** [rg3/youtube-dl#10974]
I can see the subtitles for this video on YouTube and download them using [DownSub](http://downsub.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DtVtGMQTjYT8), but the latest youtube-dl does not download the subtitles. I have noticed this is a problem for half the videos in a particular series from the same publisher.

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
---

$ /tmp/youtube-dl -v --all-subs --skip-download "https://www.youtube.com/watch?v=tVtGMQTjYT8"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--all-subs', u'--skip-download', u'https://www.youtube.com/watch?v=tVtGMQTjYT8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.19
[debug] Python version 2.7.12 - Linux-4.4.0-42-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] tVtGMQTjYT8: Downloading webpage
[youtube] tVtGMQTjYT8: Downloading video info webpage
[youtube] tVtGMQTjYT8: Extracting video information
WARNING: video doesn't have subtitles
[youtube] tVtGMQTjYT8: Downloading MPD manifest

**Comment by remitamine** [comment]
this video has only auto generated subtitles.
```
--write-auto-sub                 Write automatically generated subtitle file
                                 (YouTube only)
```
