### ISSUE TITLE
How login in vk using smplayer with mpv?Please Help!!!

### ISSUE THREAD

**Issue by apolo188** [rg3/youtube-dl#10986]
Hi, i new in this site, i started to use smplayer in puppy linux.I cant play videos from vk.com.I put this in preferences-advanced -mplayer/mpv-options:youtube-dl --username xxxxxxxxxx --password xxxxxxx then send me this:Error parsing option username (option not found)
Setting command line option '--username=' failed.
Exiting... (Fatal error)
Here a link from vk http://vk.com/video185471254_171697608
I doing something wrong?Please help me with this.
Regards!

**Comment by dstftw** [comment]
Read smplayer docs/ask smplayer developers.
