### ISSUE TITLE
unable to download videos

### ISSUE THREAD

**Issue by godhoomrohit** [rg3/youtube-dl#10983]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$youtube-dl --username *** --password *** --verbose  https://app.pluralsight.com/library/courses/understanding-machine-learning/table-of-contents

[pluralsight] understanding-machine-learning-m0-0: Downloading webpage
**ERROR**: Unable to extract initial state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpv25gpk4f\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpv25gpk4f\build\youtube_dl\extractor\common.py", line 356, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpv25gpk4f\build\youtube_dl\extractor\pluralsight.py", line 170, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpv25gpk4f\build\youtube_dl\extractor\common.py", line 659, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract initial state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

F:\videos\machine learning\understanding-machine-learning>youtube-dl -U
youtube-dl is up-to-date (2016.10.19)


### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Unable to download videos from pluralsight. It was working fine till yesterday with same command

**Comment by Hrxn** [comment]
> `https://app.pluralsight.com/library/courses/understanding-machine-learning/table-of-contents`

Is that a valid video URL?

**Comment by godhoomrohit** [comment]
The given url "https://app.pluralsight.com/library/courses/understanding-machine-learning/table-of-contents" contains list of videos.   The full trace:

[debug] User config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose', 'https://app.pluralsight.com/library/courses/understanding-machine-learning/table-of-contents']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.28
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] understanding-machine-learning: Downloading course JSON
[pluralsight:course] understanding-machine-learning: Downloading course data JSON
[download] Downloading playlist: Understanding Machine Learning
[pluralsight:course] playlist Understanding Machine Learning: Collected 21 video ids (downloading 21 of them)
[download] Downloading video 1 of 21
[pluralsight] Downloading login page
[pluralsight] Logging in as ***
[pluralsight] understanding-machine-learning-m0-0: Downloading webpage
ERROR: Unable to extract initial state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpp03txo2p\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpp03txo2p\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpp03txo2p\build\youtube_dl\extractor\pluralsight.py", line 167, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpp03txo2p\build\youtube_dl\extractor\common.py", line 650, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract initial state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
