### ISSUE TITLE
[Errno 13] Permission denied:

### ISSUE THREAD

**Issue by squadgazzz** [rg3/youtube-dl#10982]
Hello!
I'm running on Win10 64 with cmd as administrator.

`c:\>D:\JavaCore\youtube-dl.exe https://www.youtube.com/playlist?list=PLoij6udfBnciBZf7aLRmayAzcisWfAwOY -o D:\JavaCore
[youtube:playlist] PLoij6udfBnciBZf7aLRmayAzcisWfAwOY: Downloading webpage
[download] Downloading playlist: Java Core December 2013 AllinOne
[youtube:playlist] PLoij6udfBnciBZf7aLRmayAzcisWfAwOY: Downloading page #1
[youtube:playlist] playlist Java Core December 2013 AllinOne: Downloading 118 videos
[download] Downloading video 1 of 118
[youtube] HQgoL9JmwyI: Downloading webpage
[youtube] HQgoL9JmwyI: Downloading video info webpage
[youtube] HQgoL9JmwyI: Extracting video information
[youtube] HQgoL9JmwyI: Downloading MPD manifest
ERROR: unable to open for writing: [Errno 13] Permission denied: 'D:\\JavaCore'`

Any folder on any drive - access denied. I'm the only administrator on PC.

**Comment by dstftw** [comment]
`-o` is not an output directory. Read [FAQ](https://github.com/rg3/youtube-dl#output-template).
