### ISSUE TITLE
[Hornbunny] New Video Format Not supported

### ISSUE THREAD

**Issue by RandomBoyFromAustria** [rg3/youtube-dl#10981]
[X] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.19**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
PS C:\mpv> .\youtube-dl.exe --verbose http://hornbunny.com/videos/panty-slut-jerk-off-instruction-5227.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://hornbunny.com/videos/panty-slut-jerk-off-instruction-5227.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.10.19
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[HornBunny] 5227: Downloading initial webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete outp
ut.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpv25gpk4f\build\youtube_dl\YoutubeDL.py", line 694,
in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpv25gpk4f\build\youtube_dl\extractor\common.py", lin
e 356, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpv25gpk4f\build\youtube_dl\extractor\hornbunny.py",
line 34, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpv25gpk4f\build\youtube_dl\extractor\common.py", lin
e 668, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpv25gpk4f\build\youtube_dl\extractor\common.py", lin
e 659, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make s
ure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag
 and include its complete output.
<end of log>


```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://hornbunny.com/videos/panty-slut-jerk-off-instruction-5227.html
Note: this is the same video as used in the current code

---

### Description of your *issue*, suggested solution and other information

"A friend of mine" noticed that the Hornbunny functionality broke when Hornbunny updated their website. Could you guys fix it for 'my friend'

**Comment by yan12125** [comment]
Thanks for the report. Hornbunny will be fixed in the next version.
