### ISSUE TITLE
Can't download some video on bilibili.com

### ISSUE THREAD

**Issue by shikkoku** [rg3/youtube-dl#10991]
youtube-dl.exe -v http://www.bilibili.com/video/av6759147
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.bilibili.com/video/av6759147']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.10.21.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[BiliBili] 6759147: Downloading webpage
ERROR: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphn9u2rzv\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphn9u2rzv\build\youtube_dl\extractor\common.py", line 356, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphn9u2rzv\build\youtube_dl\extractor\bilibili.py", line 48, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphn9u2rzv\build\youtube_dl\extractor\common.py", line 659, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

But some one none copyright videos can download fine.

**Comment by ztytian** [comment]
Proxy can be obtained here: https://vnet.one/?rc=2879
You can register unlimited free accounts which temp emails for unlimited 256 MB data, which is what I am using currently...
Use Google Chrome for translation if you don't understand the web page
@yan12125

**Comment by yan12125** [comment]
This video has a new URL now, which will be supported in the next version:
```
$ youtube-dl -v "http://bangumi.bilibili.com/anime/5532/play#96395" --geo-verification-proxy https://secure.uku.im:993/ 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://bangumi.bilibili.com/anime/5532/play#96395', '--geo-verification-proxy', 'https://secure.uku.im:993/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.01
[debug] Git HEAD: bd8f48c78
[debug] Python version 3.6.0 - Linux-4.9.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[BiliBili] 96395: Downloading webpage
[BiliBili] Downloading episode 96395. To download all videos in anime 5532, re-run youtube-dl with http://bangumi.bilibili.com/anime/5532
[BiliBili] 96395: Downloading JSON metadata
[BiliBili] 96395: Downloading video info page
[debug] Invoking downloader on 'http://ws.acgvideo.com/1/39/11006760-1hd.mp4?wsTime=1486058583&wsSecret2=04d779e8673aa22b623eb32bfbddba6f&oi=2344923069&rate=190'
[download] Destination: 少女编号-96395.mp4
[download]  19.0% of 182.86MiB at 190.24KiB/s ETA 13:17^CException ignored in: <_io.FileIO name='少女编号-96395.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='少女编号-96395.mp4.part'>

ERROR: Interrupted by user
```
