### ISSUE TITLE
Ignore SSL certificate and request for collegehumor.com

### ISSUE THREAD

**Issue by spookyahell** [rg3/youtube-dl#11001]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.21.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.21.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.collegehumor.com/video/6853117/loo
k-at-this-instagram-nickelback-parody']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.10.12
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] look-at-this-instagram-nickelback-parody: Requesting header
WARNING: Falling back on generic information extractor.
[generic] look-at-this-instagram-nickelback-parody: Downloading webpage
[generic] look-at-this-instagram-nickelback-parody: Extracting information
[generic] 6853117: Requesting header
WARNING: Could not send HEAD request to https://www.collegehumor.com/e/6853117:
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.
c:600)>
[generic] 6853117: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILE
D] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL
: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0kv97by3\bu
ild\youtube_dl\extractor\common.py", line 403, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0kv97by3\bu
ild\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0kv97by3\bu
ild\youtube_dl\utils.py", line 1034, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.collegehumor.com/video/6853117/look-at-this-instagram-nickelback-parody
- Single video: https://www.collegehumor.com/video/7041046/pretend-you-can-afford-a-home-with-zillow
---

### Description of your *issue*, suggested solution and other information
Please add support for CollegeHumor site and:
It would be good to be able to turn off SSL certificate verification. as an option.
Like: --ssl-no-verify

**Comment by yan12125** [comment]
> It would be good to be able to turn off SSL certificate verification. as an option.

FYI: There's already ```--no-check-certificate```. And youtube-dl works fine with this option:
```
$ youtube-dl -v --no-check-certificate https://www.collegehumor.com/e/6853117 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--no-check-certificate', 'https://www.collegehumor.com/e/6853117']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.21.1
[debug] Git HEAD: e034cbc
[debug] Python version 3.5.2 - Linux-4.8.3-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.1.4, ffprobe 3.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 6853117: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6853117: Downloading webpage
[generic] 6853117: Extracting information
[download] Downloading playlist: Look at this Instagram (Nickelback Parody) on CollegeHumor
[generic] playlist Look at this Instagram (Nickelback Parody) on CollegeHumor: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 4524396810001: Downloading webpage
[brightcove:new] 4524396810001: Downloading JSON metadata
[brightcove:new] 4524396810001: Downloading m3u8 information
[brightcove:new] 4524396810001: Downloading m3u8 information
[debug] Invoking downloader on 'https://udso-a.akamaihd.net/4244402466001/4244402466001_4758341266001_4524396810001.mp4?pubId=4244402466001&videoId=4524396810001'
[download] Destination: Look at this Instagram (Nickelback Parody)-4524396810001.mp4
[download]   6.1% of 96.31MiB at 510.56KiB/s ETA 03:01
```

**Comment by spookyahell** [comment]
Sorry forgot that.
