### ISSUE TITLE
'list' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ronyphdu** [rg3/youtube-dl#11007]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.21.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.21.1**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.10.21.1
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by kevinmarsden88** [comment]
I have encountered the same problem,when attempting to perform a download and extraction of audio.

The command and output used was 

C:\Users\XX\Downloads>youtube-dl -v https://www.youtube.com/watch?v=yu18kV88OPk&list=PLIoba2FKuOvudx9uyzWt7cF07t8VuQUYi  --extract-audio --ffmpeg-location C:\Users\Kevin\Downloads\ffmpeg-20171102-d5995c5-win64-static\bin
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=yu18kV88OPk']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] yu18kV88OPk: Downloading webpage
[youtube] yu18kV88OPk: Downloading video info webpage
[youtube] yu18kV88OPk: Extracting video information
[youtube] yu18kV88OPk: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r3---sn-8vq5jvh15-2gte.googlevideo.com/videoplayback?key=yt6&mime=video%2Fwebm&gir=yes&itag=43&signature=6981458E7CD1C2995129E16C623C93502BD1EC69.6D4277B58AB738884FF9DE5EE9238C1F3CE08972&clen=4241409&dur=0.000&ipbits=0&expire=1509667382&ratebypass=yes&requiressl=yes&ip=41.0.165.119&ms=au&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mv=m&mt=1509645691&pl=24&id=o-AElmf-KXSy1aKqFGEZ5F97NIc95uDEBZwYw9814sXtVg&mn=sn-8vq5jvh15-2gte&mm=31&lmt=1298878154002809&source=youtube&initcwndbps=301250&ei=1l37WcnYI4SSV7KUkPgC'
[download] Potatoheadz - Narcotic (Radio Edit)-yu18kV88OPk.webm has already been downloaded
[download] 100% of 4.04MiB
'list' is not recognized as an internal or external command,
operable program or batch file.

I was able to subsequently extract the audio using FFmpeg,output as follows 

C:\Users\XX\Downloads\ffmpeg-20171102-d5995c5-win64-static\bin>ffmpeg.exe -i ./"Potatoheadz - Narcotic (Radio Edit)-yu18kV88OPk.webm" -vn -acodec copy ./output.ogg
ffmpeg version N-88514-gd5995c531d Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      56.  0.100 / 56.  0.100
  libavcodec     58.  1.100 / 58.  1.100
  libavformat    58.  0.102 / 58.  0.102
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  0.101 /  7.  0.101
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, matroska,webm, from './Potatoheadz - Narcotic (Radio Edit)-yu18kV88OPk.webm':
  Metadata:
    encoder         : google
  Duration: 00:03:43.84, start: 0.000000, bitrate: 151 kb/s
    Stream #0:0: Video: vp8, yuv420p(progressive), 480x360, SAR 1:1 DAR 4:3, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1: Audio: vorbis, 44100 Hz, stereo, fltp (default)
Output #0, ogg, to './output.ogg':
  Metadata:
    encoder         : Lavf58.0.102
    Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp (default)
    Metadata:
      encoder         : Lavf58.0.102
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=    2650kB time=00:03:43.44 bitrate=  97.2kbits/s speed=2.79e+003x
video:0kB audio:2622kB subtitle:0kB other streams:0kB global headers:4kB muxing overhead: 1.065937%

The output from youtube-dl -U was 

C:\Users\XX\Downloads>youtube-dl -U
youtube-dl is up-to-date (2017.10.29)

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
