### ISSUE TITLE
Site Support Request: Disney Videos

### ISSUE THREAD

**Issue by DoomTay** [rg3/youtube-dl#11000]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.10.21.1_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.21.1**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\Taylor>youtube-dl http://www.starwars.com/video/fan-film-awards-2016-star-wars-identity-thieves -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.starwars.com/video/fan-film-awards-2016-star-wars-identity-thieves', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.10.21.1
[debug] Python version 3.5.2 - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg N-81947-gc45ba26, ffprobe N-81947-gc45ba26
[debug] Proxy map: {}
[generic] fan-film-awards-2016-star-wars-identity-thieves: Requesting header
WARNING: Falling back on generic information extractor.
[generic] fan-film-awards-2016-star-wars-identity-thieves: Downloading webpage
[generic] fan-film-awards-2016-star-wars-identity-thieves: Extracting information
[debug] Invoking downloader on 'http://secure.vp.disney.go.com/xd_shortform/swff/dmvr-1496/a463d8-hdmvr-1496_pswff-star-wars-identity-thieves-h264m_aac_848x480_536x64.mp4'
[download] Destination: Star Wars Fan Film _ Star Wars - Identity Thieves-a463d8-hdmvr-1496_pswff-star-wars-identity-thieves-h264m_aac_848x480_536x64.mp4
[download] 100% of 21.57MiB in 00:03
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.starwars.com/video/fan-film-awards-2016-star-wars-identity-thieves
- Single video: http://www.starwars.com/video/rogue-one-a-star-wars-story-trailer-2
- Single video: http://www.starwars.com/video/swtor-knights-of-the-eternal-throne-betrayed-trailer
- Single video: http://www.starwars.com/video/star-wars-rebels-welcome-to-the-rebellion-wedge
- Single video: http://www.starwars.com/video/the-star-wars-show-episode-23
- Single video: http://video.disney.com/watch/star-wars-rebels-complete-season-2-now-available-53b64ee0f5d9e72ae8084c71
- Single video: http://video.disney.com/watch/disneychannel-we-re-gonna-do-it-again-53e39bdb7569cde52fb0c0a6

---
### Description of your _issue_, suggested solution and other information

Technically, support for this kind of videos is already supported, as seen above, but the video downloaded is not of the best quality, plus metadata such as the summary are not included.

Some videos, such as http://video.disney.com/watch/disneychannel-we-re-gonna-do-it-again-53e39bdb7569cde52fb0c0a6 appear to be Flash-only

**Comment by yan12125** [comment]
For video.disney.com URLs, I'm always redirected to http://www.disney.com.tw/ even with a United States proxy. Is it geo-restricted?

**Comment by DoomTay** [comment]
Not sure, but http://www.starwars.com, which appears to use the same "engine" for its videos, doesn't appear to be

**Comment by joaquinito01** [comment]
In the URLs of video.disney.com, redirecciona to tv.disney.es nothing more than a proxy of the United States. Is it Geo-restricted?
