### ISSUE TITLE
[Twitter] Support STREAMABLE embed

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#11012]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.10.21.1_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.21.1**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\>youtube-dl.py -v "https://twitter.com/FutbolsaCountry/status/790253463028568
065"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://twitter.com/FutbolsaCountry/status/79
0253463028568065']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.10.21.1
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.1.4, ffprobe 3.1.4
[debug] Proxy map: {}
[twitter] 790253463028568065: Downloading webpage
[twitter:card] 790253463028568065: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\youtube-dl.py\youtube_dl\YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\common.py", line 356, in extract
    return self._real_extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\twitter.py", line 175, in _real_ex
tract
    self._sort_formats(formats)
  File "C:\youtube-dl.py\youtube_dl\extractor\common.py", line 923, in _sort_for
mats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.
...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://twitter.com/FutbolsaCountry/status/790253463028568065

---
### Description of your _issue_, suggested solution and other information

Pointing directly to the streamable video DOES work correclty:
https://streamable.com/l5zg

Thanks 
Ringo

**Comment by yan12125** [comment]
https://streamable.com/l5zg is dead. Any new example?

**Comment by yan12125** [comment]
Closing as no new example for a long time. Feel free to leave comments below or open a new issue if there's a new one.
