### ISSUE TITLE
Vidzi does not work, despite last updated it

### ISSUE THREAD

**Issue by best-job** [rg3/youtube-dl#11019]
Vidzi.com does not work, despite last updated it .
Please solve the problem as soon as .

ERROR: Unable to download webpage: HTTP Error 504: Gateway Time-out (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Please paste the **full** output of the following command:
```
youtube-dl -v <the video URL>
```

**Comment by yan12125** [comment]
Closing as no response for a long time
