### ISSUE TITLE
Download a cours from pluralsight

### ISSUE THREAD

**Issue by LemmingsWay** [rg3/youtube-dl#11010]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.21.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.21.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.10.21.1
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Okey,
so I am  download this course from pluralsight. 
https://www.pluralsight.com/courses/powershell-getting-started

So i'v downloaded a few videos, and this is what the output of the file name looks like:

Sub title                              -Video title                                  - course name                     -sub nr - videonr     
Introduction to PowerShell -Introduction to PowerShell       -powershell-getting-started - m1      - 01
Introduction to PowerShell -Who Is this Course For              -powershell-getting-started - m1      - 02
Introduction to PowerShell -What Is Windows PowerShell    -powershell-getting-started - m1      - 03
PowerShell Basics - What We'll Cover-powershell-getting-started-m2-01

this is what i would like:

[x] make a folder with the course name (bat file)
[] make a folder under the course name with the sub folder name
[] change the title of the video to this; videonr - video title

is this possible or do I have to do it all manually?

**Comment by dstftw** [comment]
Use [output template](https://github.com/rg3/youtube-dl#output-template).

**Comment by LemmingsWay** [comment]
does not work, it only outputs: %(title)s etc etc not the title

**Comment by dstftw** [comment]
Works perfectly. Bother to read [what I've posted](https://github.com/rg3/youtube-dl#output-template-and-windows-batch-files).

**Comment by woeterman94** [comment]
Can you please give a clear example. Based on the question asked here?
What code should we use to download something from pluralsight?

I'm using: 

youtube-dl --username myname@email.com --password yolo11 https://app.pluralsight.com/courses/ethical-hacking-understanding -o "C:\Users\me\Downloads\pl%(playlist)s/%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s" --sleep-interval 10
