### ISSUE TITLE
Possibility to pipe downloaded file to Django response

### ISSUE THREAD

**Issue by nlhkh** [rg3/youtube-dl#11011]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like
---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.10.21.1_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.21.1**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other
---
### Description of your _issue_, suggested solution and other information

I am using `youtube_dl` with `Django`. Currently I have `youtube_dl` download files to a temporary location, and send that file to a request. I wonder if I can somehow stream the file directly to the client without having to materialize a file on disk. This is possible with `node_ytdl_core` because NodeJS has good support for async operation and pipeline. I can also do this with Java.

I think this is doable if `youtube_dl` exposes a stream object programmatically, but I have not yet found out how to do so.

**Comment by yan12125** [comment]
Use ```-o -``` with ```subprocess.Popen```?

**Comment by nlhkh** [comment]
Could you elaborate? I thought `-o` is just to indicate a final filename template.

**Comment by nlhkh** [comment]
I guess `-o -` will pipe the file content to stdout?

**Comment by yan12125** [comment]
> I guess ```-o -``` will pipe the file content to stdout?

Yes you're right.

**Comment by yan12125** [comment]
No feedback for a long time, so I assume things are working fine. Feel free to leave comments if there's still something wrong.

**Comment by nlhkh** [comment]
Thanks :)
