### ISSUE TITLE
Unable to download webpage

### ISSUE THREAD

**Issue by Mahmoud-Mardeni** [rg3/youtube-dl#11016]
I am running youtube-dl from an android application context and can not get it to work. It was working just fine before the last two releases.

I have tried it fro pc and its also working fine. Below you can find the error log.

Thank you for your help.

## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.21.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.21.1**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --format best --verbose --dump-json https://www.youtube.com/watch?v=ypmcr_-bV0o
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--format', u'best', u'--verbose', u'--dump-json', u'https://www.youtube.com/watch?v=ypmcr_-bV0o']
[debug] Encodings: locale None, fs None, out None, pref UTF-8
[debug] youtube-dl version 2016.10.21.1
[debug] Python version 2.7.10 - Linux-3.4.0-1548638-armv7l-with-libc
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to download webpage: <urlopen error [Errno 2] temporary failure in name resolution.> (caused by URLError(gaierror(2, 'temporary failure in name resolution.'),))
  File "/data/data/com.sprtapk.moslsl/files/youtube-dl/youtube_dl/extractor/common.py", line 403, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/data/data/com.sprtapk.moslsl/files/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/home/shimoda/python-for-android.git/python-build/python_arm/python-ext/python/urllib2.py", line 431, in open
  File "/home/shimoda/python-for-android.git/python-build/python_arm/python-ext/python/urllib2.py", line 449, in _open
  File "/home/shimoda/python-for-android.git/python-build/python_arm/python-ext/python/urllib2.py", line 409, in _call_chain
  File "/data/data/com.sprtapk.moslsl/files/youtube-dl/youtube_dl/utils.py", line 1036, in https_open
    req, **kwargs)
  File "/home/shimoda/python-for-android.git/python-build/python_arm/python-ext/python/urllib2.py", line 1197, in do_open
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
>temporary failure in name resolution

Your DNS does not work.

**Comment by Mahmoud-Mardeni** [comment]
When I tried using it from Pc which is connected to the same network and uses same DNS it does work fine.

Although it does not work from the android app.

**Comment by yan12125** [comment]
Does AndroidManifest.xml include proper permissions for accessing the Internet?

**Comment by Mahmoud-Mardeni** [comment]
Yes it does. and when I use older releases of youtube-dl it work fine.

**Comment by yan12125** [comment]
> when I use older releases of youtube-dl it work fine.

Which version?

**Comment by Mahmoud-Mardeni** [comment]
2016.07.13
