### ISSUE TITLE
How to *only* download subtitles vtt (WebVTT) files with youtube-dl

### ISSUE THREAD

**Issue by guitargurus** [rg3/youtube-dl#11026]
I mistakenly downloaded over 200GB of playlists before realizing I didn't have the --write-auto-sub switch on.  I would like to rerun youtube-dl against my playlists but have it only download the vtt files.  I would like to do it with youtube-dl becuase it will automatically give them all the correct file name (has to match in my application).

I would like to know how to use youtube-dl to only download subtitles for all videos in a given playlist.

Thank you

**Comment by dstftw** [comment]
`--skip-download --sub-format vtt --write-sub`.

**Comment by 1c7** [comment]
```
youtube-dl https://www.youtube.com/watch?v=1-xiSOvgNvw&t=6s --skip-download --sub-format vtt --write-sub
```
@dstftw  Thanks
still work in 2019.
here is a example for copy & paste
