### ISSUE TITLE
UKTV Play (Dave, Really, Drama, etc) no longer working

### ISSUE THREAD

**Issue by Akibo95** [rg3/youtube-dl#11027]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.10.25_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.25**
  (see log later)
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
Y:\>youtube-dl http://uktvplay.uktv.co.uk/shows/red-dwarf/watch-
online/?video=5134544417001 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://uktvplay.uktv.co.uk/shows/red-dwarf/watch-on
line/?video=5134544417001', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.10.25
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 2.2.3, rtmpdump 2.3
[debug] Proxy map: {}
[generic] ?video=5134544417001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?video=5134544417001: Downloading webpage
[generic] ?video=5134544417001: Extracting information
ERROR: Unsupported URL: http://uktvplay.uktv.co.uk/shows/red-dwarf/watch-online/
?video=5134544417001
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9smmfv95\bu
ild\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9smmfv95\bu
ild\youtube_dl\extractor\common.py", line 356, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9smmfv95\bu
ild\youtube_dl\extractor\generic.py", line 2431, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://uktvplay.uktv.co.uk/s
hows/red-dwarf/watch-online/?video=5134544417001
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Playlist: http://uktvplay.uktv.co.uk/shows/red-dwarf/watch-online/#series-11
- Single video: http://uktvplay.uktv.co.uk/shows/red-dwarf/watch-online/?video=5134544417001

---
### Description of your _issue_, suggested solution and other information

Until recently, this just worked. It did fall back on the generic information extractor, and then was able to download videos. But now it would appear something has changed and youtube-dl reports that the site is not supported.

Apologies for multiple-categorisation; I'm not sure which category is appropriate for this issue.

**Comment by oxhey** [comment]
Is there any progress on this issue? I tried a uktv link with the username and password flags, but it also said unsupported url.
