### ISSUE TITLE
How to list file names in playlist files without downloading the file?

### ISSUE THREAD

**Issue by scotty264** [rg3/youtube-dl#11021]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.25**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

In past playlists downloads from YOUTUBE, I did not use the "-o" option to sort the video names by playlist order.  I would like to use the "--flat-playlist" feature or some other method to list the playlist file names in playlist order so I can manually rename them with a number prefix so they will sort by playlist order.  How do I perform this function?

The "--flat-playlist" option only says "Downloading video XX or XX" for each video but the file name is not printed.

Thank you.

Peace and blessings.

**Comment by Starsam80** [comment]
Wouldn't `%(playlist_index)s` work?

**Comment by dstftw** [comment]
`-o ... --get-filename`.
