### ISSUE TITLE
not able to dl mp4 file from 'new' VK

### ISSUE THREAD

**Issue by LandisTwo** [rg3/youtube-dl#11022]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.25**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
landis@linux-e6420:~/Downloads/x-media> sudo youtube-dl -U
root's password:
Updating to version 2016.10.25 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
landis@linux-e6420:~/Downloads/x-media> youtube-dl -v -f [height=480] --username 'MY.USERNAME@vk' --password=MYPassword https://vk.com/video-102753747_456257621
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'[height=480]', u'--username', u'PRIVATE', u'--password=PRIVATE', u'https://vk.com/video-102753747_456257621']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.25
[debug] Python version 2.7.12 - Linux-3.16.7-42-desktop-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[vk] Downloading login page
[vk] Logging in as landis.reed@yandex.ru
[vk] -102753747_456257621: Downloading webpage
ERROR: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/vk.py", line 372, in _real_extract
    data_json = self._search_regex(r'var\s+vars\s*=\s*({.+?});', info_page, 'vars')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 659, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.
---

I know VK (ВКонтаке) has been re-writing how it streams videos. Some still use FF downloader, ant, some can / could be dl'd with get and all could be dl'd with youtube-dl... Now it takes some extra steps.

But, this is No an issue with how I do it, but yt-dl just wont.
On VK I have to pass my username & password. 
Example: 
#> youtube-dl -v -f [height=480] username='MyUser.Name@VK' password=MyPassword https://vk.com/path/to/video

any ideas?

thank you for working on this project!
LandisTwo

**Comment by sudovijay** [comment]
Vk just updated it source code ! insted of **var vars** switch it to this `"params":\[({.+?\})\]`

**Comment by LandisTwo** [comment]
So, you've closed this report, Does that mean you've fixed the issue, you're fixing it, you're Not going to fix it or are we (am i) supposed to edit some source with the 'Fix extraction' snippet ?

Thanks for the program, love it.
Landis.

**Comment by Hrxn** [comment]
It's fixed..

**Comment by LandisTwo** [comment]
Спасибо! Thank You.
I updated using zypper, but it still didn't work.
ran # youtube-dl --version & found still 10.25 version
ran # youtube-dl -U and got 2016.10.26
Now the world is beautiful again. : )

Thanks.
