### ISSUE TITLE
Moving file to other directory after it is done downloading [Solved]

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#11038]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.26**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Question
----

Hi there. 

I would like to move a converted video file once youtube-dl has downloaded the bestvideo and bestaudio from my _/home/user/Videos/youtube_ on my SSD to my shared folder in _/mnt/sharedfolder/youtube_. However I would like to automate it say if i download a whole channel. 
Download a video, convert it, and move it to the share. it is quicker to convert the file locally on the ssd instead of over the share.

To do that I would do the following

- Run this command:

`youtube-dl -f bestvideo+bestaudio -o /home/user/Videos/youtube/%(title)s.%(ext)s https://www.youtube.com/watch?v=eminWvN1O88`
- Wait for the download and conversion to finish and run:

`mv /home/user/Videos/youtube/* /mnt/sharedfolder/youtube/`

----
Is there a way I can tell youtube-dl to just move the file it just downloaded so I don't have to stare at it and wait for it to finish? Is there a way to tell it to move after each video in a channel/playlist is downloaded?
----

The reason I want it to move the file to the share is, if the video happens to be downloaded before I leave the house, plex sync will automatically send that new file to my phone and I will be able to watch it on the go.

Thank you.

**Comment by JCAndresen** [comment]
Closed.

**Comment by Stonedestroyer** [comment]
How did you solve this issue?

**Comment by yan12125** [comment]
@Stonedestroyer you can use --exec

**Comment by cwd0204** [comment]
youtube-dl -f bestvideo+bestaudio   -exec 'mv {} %s' %s(your_folder,youtube_url)
