### ISSUE TITLE
Check other directory to see if file already exists

### ISSUE THREAD

**Issue by jandresen** [rg3/youtube-dl#11039]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.26*. 
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Question

----

Hey there. 

I am using youtube-dl to download a specific channel. 
Directory A is the directory I download and convert videos to. it could be /home/user/Videos/Yotube
Directory B is the directory I keep my downloaded videos in. /media/nas/Videos/Youtube

I download my videos to A since it is way quicker than downloading and converting over the network.

My config file looks like this:

_-f bestvideo+bestaudio
-o %(title)s.%(ext)s`
--exec 'mv {} /media/nas/Videos/Youtube'_ 

I run `youtube-dl https://www.youtube.com/channel/UCboMX_UNgaPBsUOIgasn3-Q/videos` from Directory A but **is there a way I can get it to check if the -o file matches any file in Directory B before downloading (and if there does, skip the video). which it does perfectly if I ran the command from Directory B?** 

Thank you.

**Comment by dstftw** [comment]
Not possible. `--download-archive` should be used instead in such cases.

**Comment by jandresen** [comment]
@dstftw Hey Sergey, 

Can I add current videos to the --download-archive file?

**Comment by dstftw** [comment]
`-o '%(extractor)s %(id)s' --get-filename`.

**Comment by jandresen** [comment]
Alright perfect thank you very much for the help.
