### ISSUE TITLE
Problem encoding video title

### ISSUE THREAD

**Issue by ObaidGH** [rg3/youtube-dl#11045]
I have problem encoding video title while retrieving video title using `--get-title` command

cannot encode hindi characters :disappointed:

**Comment by yan12125** [comment]
Could you paste your command and the output? Also the output of ```youtube-dl -v```

**Comment by ObaidGH** [comment]
#### The original title is this: `Taarak Mehta Ka Ooltah Chashmah - तारक मेहता - Episode 2056 - 25th October, 2016`
##### 1. Command: `-v --get-title`  doest not get the hindi characters
![-v --get-title](https://cloud.githubusercontent.com/assets/14979775/19802912/b0b785d2-9d23-11e6-944b-997c51d2a4e7.PNG)

##### 2. Command `--get-title` also gives the same output
![-v](https://cloud.githubusercontent.com/assets/14979775/19802936/cf921396-9d23-11e6-9416-857cb6483bab.PNG)

##### 3. GUI, this is the method  i used to get the title using `--get-title` command
```c#
private  string GetFileName(string url)
        {
            Process cmd = new Process();
            cmd.StartInfo.FileName = ex1;
            cmd.StartInfo.RedirectStandardInput = true;
            cmd.StartInfo.RedirectStandardOutput = true;
            cmd.StartInfo.CreateNoWindow = true;
            cmd.StartInfo.UseShellExecute = false;
            cmd.StartInfo.Arguments = " --get-title " + url;
            cmd.StartInfo.StandardOutputEncoding = Encoding.UTF8;
            cmd.Start();
            cmd.WaitForExit();
            return cmd.StandardOutput.ReadLine();
        }
```
##### output:
![output](https://cloud.githubusercontent.com/assets/14979775/19803285/79dc43d4-9d25-11e6-995d-23cdeb2f59b7.PNG)

You see that the Hindi characters are not printed

**Comment by linglung** [comment]
work fine on update version. tested 
[http://image.prntscr.com/image/6d9a176f40804b208626ff6ef072f15f.png](url)

**Comment by ObaidGH** [comment]
👍
