### ISSUE TITLE
-site-support-request- Plz Add new german public service broadcasting sites

### ISSUE THREAD

**Issue by watchmoretv** [rg3/youtube-dl#11040]
-site-support-request-
-geo-restricted-

Since you support nearly all german public service broadcasting authorities like ARD, ZDF...,
please add their new platform and sites:

http : //  funk .net (www . funk . net/serien)
http : // one . ard. de /mediathek/

As the future developement of the popular program "mediathekview" (https://github.com/mediathekview/MediathekView) is unclear, youtube-dl will become even more important here in DE.
A big "Thank you" to the whole youtube-dl developer team.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
