### ISSUE TITLE
Part file detected as font file of text

### ISSUE THREAD

**Issue by rugk** [rg3/youtube-dl#11049]
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

A MP4 video download e.g. creates these files during the download: `.mp4.part-Frag0`.
In GNOME these are recognized as `application/x-font-tex-tfm` - a part of the font system of TeX.

So maybe you want to change the file extension. :smiley:

**Comment by dstftw** [comment]
That's not our problem.
