### ISSUE TITLE
2016.10.26 broke CBS and NBC

### ISSUE THREAD

**Issue by jimbolaya** [rg3/youtube-dl#11056]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

This is actually a regression from youtube-dl 2016.10.25 since both work flawlessly in that version. I think they may be related since the errors are similar. It may be a timing issue?

This is what I get from CBS:

youtube-dl 'http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q/the-late-show-10-27-2016-mary-louise-parker-pusha-t-the-record-company-/'
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Downloading XML
ERROR: Unable to download XML: [Errno 104] Connection reset by peer (caused by error(104, 'Connection reset by peer')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

However, when I run with a verbose flag, it works:

youtube-dl -v 'http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q/the-late-show-10-27-2016-mary-louise-parker-pusha-t-the-record-company-/'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q/the-late-show-10-27-2016-mary-louise-parker-pusha-t-the-record-company-/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.26
[debug] Python version 2.7.6 - Linux-3.13.0-100-generic-x86_64-with-LinuxMint-17-qiana
[debug] exe versions: avconv N-80901-gfebc862, avprobe N-80901-gfebc862, ffmpeg N-80901-gfebc862, ffprobe N-80901-gfebc862, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Downloading XML
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Downloading RTMP SMIL data
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Downloading StreamPack SMIL data
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 104] Connection reset by peer>
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Downloading OnceURL SMIL data
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Checking video URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Downloading m3u8 information
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-1200 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-1200 video format URL is invalid, skipping
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-4400 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-4400 video format URL is invalid, skipping
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-2000 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-2000 video format URL is invalid, skipping
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-764 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-764 video format URL is invalid, skipping
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-512 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-512 video format URL is invalid, skipping
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-264 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-264 video format URL is invalid, skipping
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-60 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-60 video format URL is invalid, skipping
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Downloading JSON metadata
[debug] Invoking downloader on u'http://once-aws-us-west-2-lb.unicornmedia.com/now/media/playlist/bb0b18ba-64f5-4b1b-a29f-0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/468fb310-a585-11e4-bfdb-005056837bc7/250e4f15-a933-4720-8a7b-17ac0718908e/0/0/2485/content.m3u8?visitguid=4dbc6045-886d-4523-8b7a-6c1d354896c3&segmentlength=10&adsegmentlength=0&protocolversion=3'
[download] Destination: The Late Show - 10_27_2016 (Mary-Louise Parker, Pusha T, The Record Company)-7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q.mp4
[debug] avconv command line: avconv -y -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
' -i 'http://once-aws-us-west-2-lb.unicornmedia.com/now/media/playlist/bb0b18ba-64f5-4b1b-a29f-0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/468fb310-a585-11e4-bfdb-005056837bc7/250e4f15-a933-4720-8a7b-17ac0718908e/0/0/2485/content.m3u8?visitguid=4dbc6045-886d-4523-8b7a-6c1d354896c3&segmentlength=10&adsegmentlength=0&protocolversion=3' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:The Late Show - 10_27_2016 (Mary-Louise Parker, Pusha T, The Record Company)-7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q.mp4.part'
...
And it finished downloading the video.

No such luck with NBC. Here is the error from NBC:

youtube-dl -v 'http://www.nbc.com/late-night-with-seth-meyers/video/kate-beckinsale-colin-hanks/3117213'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.nbc.com/late-night-with-seth-meyers/video/kate-beckinsale-colin-hanks/3117213']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.26
[debug] Python version 2.7.6 - Linux-3.13.0-100-generic-x86_64-with-LinuxMint-17-qiana
[debug] exe versions: avconv N-80901-gfebc862, avprobe N-80901-gfebc862, ffmpeg N-80901-gfebc862, ffprobe N-80901-gfebc862, rtmpdump 2.4
[debug] Proxy map: {}
[NBC] 3117213: Downloading webpage
[ThePlatform] 3117213: Downloading webpage
[ThePlatform] 3117213: Downloading SMIL data
[ThePlatform] 3117213: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 104] Connection reset by peer>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 273, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 923, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
It can't be a regression since there were no changes in cbs or nbc.

Both work with for me:
```
PS C:\dev\youtube-dl\master> py -2.7 .\youtube_dl\__main__.py 'http://www.cbs.com/shows/the-late-show-with-stephen-colbe
rt/video/7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q/the-late-show-10-27-2016-mary-louise-parker-pusha-t-the-record-company-/' --pr
oxy socks5://96.225.38.251:32299
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Downloading XML
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Downloading RTMP SMIL data
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Downloading StreamPack SMIL data
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Downloading m3u8 information
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Downloading OnceURL SMIL data
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Checking video URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Downloading m3u8 information
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-1200 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-1200 video format URL is invalid, skipping
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-4400 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-4400 video format URL is invalid, skipping
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-2000 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-2000 video format URL is invalid, skipping
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-764 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-764 video format URL is invalid, skipping
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-512 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-512 video format URL is invalid, skipping
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-264 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-264 video format URL is invalid, skipping
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: Checking http-60 video format URL
[CBS] 250e4f15-a933-4720-8a7b-17ac0718908e: http-60 video format URL is invalid, skipping
[CBS] 7QR7Ea2Qm5KwGQQIcNbSMKADTq0b3h0q: Downloading JSON metadata
[download] Destination: The Late Show - 10_27_2016 (Mary-Louise Parker, Pusha T, The Record Company)-7QR7Ea2Qm5KwGQQIcNb
SMKADTq0b3h0q.mp4
WARNING: ffmpeg does not support SOCKS proxies. Downloading is likely to fail. Consider adding --hls-prefer-native to yo
ur command.
ffmpeg version N-81192-g04da20e Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --ena
ble-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --ena
ble-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --e
nable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-lib
openjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspee
x --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx
--enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzim
g --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 51.100 / 57. 51.100
  libavformat    57. 44.100 / 57. 44.100
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 49.100 /  6. 49.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, hls,applehttp, from 'http://once-aws-us-east-1-lb.unicornmedia.com/now/media/playlist/bb0b18ba-64f5-4b1b-a29f-
0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/468fb310-a585-11e4-bfdb-005056837bc7/250e4f15-a933-4720-8a7b-17ac07189
08e/0/0/2485/content.m3u8?visitguid=e5dada0a-2454-4452-97f5-7fa6d9975dbe&segmentlength=10&adsegmentlength=0&protocolvers
ion=3':
  Duration: 00:41:24.95, start: 1.466733, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 29.97 fps
, 29.97 tbr, 90k tbn, 59.94 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
[mp4 @ 0000000002469f60] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar in
stead.
    Last message repeated 1 times
Output #0, mp4, to 'file:The Late Show - 10_27_2016 (Mary-Louise Parker, Pusha T, The Record Company)-7QR7Ea2Qm5KwGQQIcN
bSMKADTq0b3h0q.mp4.part':
  Metadata:
    encoder         : Lavf57.44.100
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 2
9.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  640 fps=117 q=-1.0 Lsize=   10757kB time=00:00:21.26 bitrate=4143.0kbits/s speed=3.88x
video:10060kB audio:682kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.143693%
Exiting normally, received signal 2.
```
```
PS C:\dev\youtube-dl\master> py -2.7 .\youtube_dl\__main__.py 'http://www.nbc.com/late-night-with-seth-meyers/video/kate
-beckinsale-colin-hanks/3117213' --proxy socks5://96.225.38.251:32299
[NBC] 3117213: Downloading webpage
[ThePlatform] 3117213: Downloading webpage
[ThePlatform] 3117213: Downloading SMIL data
[ThePlatform] 3117213: Downloading m3u8 information
[ThePlatform] 3117213: Downloading JSON metadata
[download] Destination: Kate Beckinsale, Colin Hanks-3117213.mp4
WARNING: ffmpeg does not support SOCKS proxies. Downloading is likely to fail. Consider adding --hls-prefer-native to your command.
ffmpeg version N-81192-g04da20e Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 51.100 / 57. 51.100
  libavformat    57. 44.100 / 57. 44.100
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 49.100 /  6. 49.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, hls,applehttp, from 'https://nbcmpx-vh.akamaihd.net/i/video/134/634/161017_3117213_Kate_Beckinsale__Colin_Hanks_mpx_,1696,1296,896,696,496,306,150,240,64,.mp4.csmil/index_0_av.m3u8?null=0&id=AgBg4Sb7FwMNnTpsE1jcwa1tVy%2fZRMKmvx%2fg96RVcnkrGggGp8bYxXNuZXW4%2fqfpgI9A8F+slF%2fFZw%3d%3d&hdntl=exp=1477754298~acl=%2fi%2fvideo%2f134%2f634%2f161017_3117213_Kate_Beckinsale__Colin_Hanks_mpx_*~data=hdntl~hmac=cf0d2785b81bb4825024a9aeaf79cc7db40ea28ddf1576c624bb4f2a6a94c1d4':
  Duration: 00:41:25.23, start: 0.100511, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720, Closed Captions, 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
[mp4 @ 0000000003259740] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
    Last message repeated 1 times
Output #0, mp4, to 'file:Kate Beckinsale, Colin Hanks-3117213.mp4.part':
  Metadata:
    encoder         : Lavf57.44.100
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p, 1280x720, q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 5247 fps=111 q=-1.0 Lsize=   48530kB time=00:03:38.84 bitrate=1816.6kbits/s speed=4.62x
video:45849kB audio:2564kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.240178%
Exiting normally, received signal 2.
```

Judging on
>[Errno 104] Connection reset by peer

it's clearly a connectivity issue on your side.

**Comment by Hrxn** [comment]
Do you mind me asking a little question here?

About this: `py -2.7`

Is this some extension/script for PS, that I've never heard of before?

**Comment by dstftw** [comment]
Python Launcher for Windows shipped with python 3.

**Comment by Hrxn** [comment]
Thanks!

Never tried that before..
