### ISSUE TITLE
support for youtube 3d videos

### ISSUE THREAD

**Issue by siddht1** [rg3/youtube-dl#11066]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.26**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.10.26
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

i want to download 3d videos from youtube , but youtube-dl doesnt seem to extract them.
so add 3d videos support too

youtube-dl -v https://www.youtube.com/watch?v=DUVHSS5yaUw -F
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=DUVHSS5yaUw', u'-F']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.26
[debug] Python version 2.7.12 - Linux-4.4.0-21-generic-x86_64-with-LinuxMint-18-sarah
[debug] exe versions: ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] DUVHSS5yaUw: Downloading webpage
[youtube] DUVHSS5yaUw: Downloading video info webpage
[youtube] DUVHSS5yaUw: Extracting video information
[youtube] DUVHSS5yaUw: Downloading MPD manifest
[info] Available formats for DUVHSS5yaUw:
format code  extension  resolution note
249          webm       audio only DASH audio   60k , opus @ 50k (48000Hz), 759.82KiB
250          webm       audio only DASH audio   89k , opus @ 70k (48000Hz), 1013.80KiB
140          m4a        audio only DASH audio  127k , m4a_dash container, mp4a.40.2@128k (44100Hz), 1.82MiB
171          webm       audio only DASH audio  142k , vorbis@128k (44100Hz), 1.91MiB
251          webm       audio only DASH audio  224k , opus @160k (48000Hz), 2.41MiB
160          mp4        256x144    DASH video  110k , avc1.4d400c, 13fps, video only, 1.56MiB
278          webm       256x144    DASH video  131k , webm container, vp9, 13fps, video only, 1.53MiB
242          webm       426x240    DASH video  185k , vp9, 25fps, video only, 2.03MiB
133          mp4        426x240    DASH video  251k , avc1.4d4015, 25fps, video only, 3.51MiB
243          webm       640x360    DASH video  342k , vp9, 25fps, video only, 3.69MiB
134          mp4        640x360    DASH video  423k , avc1.4d401e, 25fps, video only, 4.16MiB
244          webm       854x480    DASH video  562k , vp9, 25fps, video only, 5.97MiB
135          mp4        854x480    DASH video  762k , avc1.4d401e, 25fps, video only, 7.89MiB
247          webm       1280x720   DASH video  971k , vp9, 25fps, video only, 10.44MiB
136          mp4        1280x720   720p 1272k , avc1.4d401f, 25fps, video only, 14.52MiB
248          webm       1920x1080  DASH video 1701k , vp9, 25fps, video only, 18.64MiB
137          mp4        1920x1080  1080p 2018k , avc1.640028, 25fps, video only, 26.32MiB
298          mp4        1280x720   DASH video 2101k , avc1.4d4020, 50fps, video only, 26.60MiB
299          mp4        1920x1080  DASH video 4305k , avc1.64002a, 50fps, video only, 49.08MiB
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3,  mp4a.40.2
43           webm       640x360    medium , vp8.0,  vorbis@128k
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)

**Comment by dstftw** [comment]
It's not a 3D video.
