### ISSUE TITLE
Errors when there is a missing embedded video.

### ISSUE THREAD

**Issue by JudgeGroovyman** [rg3/youtube-dl#11070]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
Tank-Pump-Studios:forcedtostrip johnny$ youtube-dl -v http://forcedstrip.tumblr.com/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://forcedstrip.tumblr.com/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.26
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1
[debug] Proxy map: {}
[generic] forcedstrip.tumblr: Requesting header
WARNING: Falling back on generic information extractor.
[generic] forcedstrip.tumblr: Downloading webpage
[generic] forcedstrip.tumblr: Extracting information
[download] Downloading playlist: Forced to Strip
[generic] playlist Forced to Strip: Collected 5 video ids (downloading 5 of them)
[download] Downloading video 1 of 5
[dailymotion] x27ocek: Downloading webpage
[dailymotion] x27ocek: Downloading m3u8 information
[dailymotion] x27ocek: Downloading m3u8 information
[dailymotion] x27ocek: Downloading m3u8 information
[dailymotion] x27ocek: Downloading m3u8 information
[dailymotion] x27ocek: Downloading m3u8 information
[debug] Invoking downloader on u'https://www.dailymotion.com/cdn/H264-848x480/video/x27ocek.mp4?auth=1477953888-2562-9jlml4p2-571cbadd4e4c99141c1287db605519c8'
[download] ENF nude girl humiliated at school-x27ocek.mp4 has already been downloaded
[download] 100% of 3.46MiB
[download] Downloading video 2 of 5
[dailymotion] x2cmt0y: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 403, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Please don't send me a workaround and say this is done.

It looks like youtube-dl is getting tripped up on this tumblr having an embedded missing video but that shouldn't trip it up!  I am sure there is a command line option to tell it to skip errors like this (which I will find) but the default option needs to be as much success as possible.

**Comment by dstftw** [comment]
This is expected behavior. `-i` to ignore errors.
