### ISSUE TITLE
Won't download facebook 1080p

### ISSUE THREAD

**Issue by itchyballsack** [rg3/youtube-dl#11073]
On firefox it gives the options for hd or sd no matter what (hd being 720). In chrome it has 360, 720, 1080 etc... But it only allows 1080 when logged in. Is there a way to get 1080p facebook videos with youtube-dl because the best it gets is 720, even on a 1080p video

**Comment by yan12125** [comment]
Any example link?

**Comment by itchyballsack** [comment]
https://www.facebook.com/cnn/videos/10155529876156509/

**Comment by itchyballsack** [comment]
That thread is closed and you said that you could only see 720, which is probably because you are not logged in

**Comment by yan12125** [comment]
> which is probably because you are not logged in

I don't want to leak my sensitive information to Google, so I don't use Facebook on Chrome/Chromium. With d9ee2e5 public 1080P videos are correctly detected, so I guess youtube-dl should also work for login-required ones.

**Comment by itchyballsack** [comment]
Thanks for the link to the python file, are you able to explain to me how to use it? I am not very good with this sort of stuff

**Comment by itchyballsack** [comment]
https://www.facebook.com/dulcedelight/videos/1260234880666006/

**Comment by yan12125** [comment]
> are you able to explain to me how to use it?

That's a change in youtube-dl. You can either wait for the next release or follow [developer instructions](https://github.com/rg3/youtube-dl#developer-instructions) for how to try the cutting-edge version.

**Comment by itchyballsack** [comment]
Sorry for so many questions, but how often do they update the exe?

**Comment by yan12125** [comment]
> roughly how often do they update the exe

Usually no longer than one or two weeks

> will the update have the change you made with facebook.py

Yes.

**Comment by itchyballsack** [comment]
Thank you for the help :)

**Comment by itchyballsack** [comment]
They released the update and it still didn't fix the issue
Here is an example 1080 video that I found which only downloads 720 https://www.facebook.com/dulcedelight/videos/1251846471504847/

**Comment by Hrxn** [comment]
Where do you see the 1080p video there? Only with Facebook account? Because the browser also shows me just 720p..

**Comment by itchyballsack** [comment]
Yes you have to be logged in to see 1080, that is the case with many fb videos, and it is the reason why I posted the question

**Comment by yan12125** [comment]
Still no 1080p with ```--username``` and ```--password```?

**Comment by itchyballsack** [comment]
what do you mean by that?

**Comment by itchyballsack** [comment]
can you write the full command

**Comment by itchyballsack** [comment]
I didn't know you could use your credentials with youtube-dl

**Comment by yan12125** [comment]
Like this:
```
youtube-dl --username (your username) --passowrd (your password) URL
```

**Comment by itchyballsack** [comment]
Thanks so much, I will test it now

**Comment by itchyballsack** [comment]
Hmmmn, a few questions. Do I keep the brackets? Also on facebook do I use my email as the username? Also I tried (using email and pass) with and without brackets and it says no such option --password

**Comment by itchyballsack** [comment]
Never mind, you spelled password wrong

**Comment by itchyballsack** [comment]
All that happens is it gets the wrong video and it is still 720

**Comment by itchyballsack** [comment]
No matter what url I write from the page, it gets the same video

**Comment by itchyballsack** [comment]
I tried logging in using the old youtube-dl before you made the change to the facebook.py and it got the right video but still 720

**Comment by yan12125** [comment]
I got a Facebook account and watch this video in Chrome. It's still 720p:
![facebook-720p](https://cloud.githubusercontent.com/assets/1937689/19848945/6aef48ae-9f8b-11e6-8be3-12262c81ebbe.png)

**Comment by itchyballsack** [comment]
http://i.imgur.com/A3HU2zj.png

**Comment by Hrxn** [comment]
Okay, tried it as well.. (Don't really use Facebook, but still have an old account)

Used my .netrc for credentials..

```
C:\Users\Hrxn>youtube-dl.exe -v -n -F --ignore-config "https://www.facebook.com/dulcedelight/videos/1251846471504847/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-n', '-F', '--ignore-config', 'https://www.facebook.com/dulcedelight/videos/1251846471504847/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.10.31
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82143-gbf14393, ffprobe N-82143-gbf14393
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 1251846471504847: Downloading webpage
[info] Available formats for 1251846471504847:
format code               extension  resolution note
1583686988324332ad        m4a        audio only [eng] DASH audio   49k , mp4a.40.29 (48000Hz)
1583686991657665vd        mp4        426x240    [eng] DASH video  267k , avc1.4d401e, video only
1583687101657654v         mp4        640x360    [eng] DASH video  500k , avc1.4d401e, video only
1583687631657601v         mp4        854x480    [eng] DASH video  774k , avc1.4d401e, video only
1583687544990943v         mp4        1280x720   [eng] DASH video 1442k , avc1.64001f, video only
dash_sd_src               mp4        unknown
dash_sd_src_no_ratelimit  mp4        unknown
dash_hd_src               mp4        unknown
dash_hd_src_no_ratelimit  mp4        unknown    (best)

C:\Users\Hrxn>
```

The video is 1280x720p btw...

**Comment by itchyballsack** [comment]
It is 1080, see the image I posted, I download the 720 through youtubedl compare to the 1080 in chrome and there is visible difference

**Comment by Hrxn** [comment]
> They released the update and it still didn't fix the issue
> Here is an example 1080 video that I found which only downloads 720 https://www.facebook.com/dulcedelight/videos/1251846471504847/

Okay, used Chrome to sign-in into my old Facebook account, here is what I see:
![Imgur](http://i.imgur.com/RjEoFWb.png)

**Comment by itchyballsack** [comment]
Your chrome is up to date?

**Comment by yan12125** [comment]
> Your chrome is up to date?

From ```chrome://help/```: Version 54.0.2840.71 (64-bit)

**Comment by itchyballsack** [comment]
http://i.imgur.com/IoIbFuY.jpg

**Comment by itchyballsack** [comment]
Left is through chrome 1080, right is after youtube-dl 720

**Comment by itchyballsack** [comment]
Maybe facebook only allows 1080 in some countries I don't know

**Comment by yan12125** [comment]
God knows. Only those who can watch 1080P are able to fix this.

**Comment by itchyballsack** [comment]
Thanks for the help by the way. Also, you may want to remove the change you made to facebook.py. It causes problems when you use login info

**Comment by itchyballsack** [comment]
At least for me it did, worked with old youtube-dl

**Comment by Hrxn** [comment]
Yeah, latest Chrome stable, of course..

Next two guesses would be:
* Geo IP filter. Could be tested with VPN, just use the right exit
* There are different tiers/categories of Facebook accounts ('Pro', Premier, VIP, god knows..)

Does anyone know anything about that?

**Comment by itchyballsack** [comment]
Don't know about tiers but I created a facebook account with no info other than name like 10 minutes ago and I was able to see 1080, I think it is to do with location

**Comment by yan12125** [comment]
Where are you?

**Comment by itchyballsack** [comment]
new zealand
