### ISSUE TITLE
Issues downloading from tudou

### ISSUE THREAD

**Issue by itchyballsack** [rg3/youtube-dl#11074]
Here is an example url youtube-dl "http://www.tudou.com/programs/view/hiFqRBvzzhc/"
the download stops after part 1, any ideas?
I know it works for some url's but for many it just can't get past a certain part

**Comment by yan12125** [comment]
Works fine for me, all videos are downloaded:
```
$ youtube-dl -v "http://www.tudou.com/programs/view/hiFqRBvzzhc/" 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.tudou.com/programs/view/hiFqRBvzzhc/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.26
[debug] Git HEAD: d9ee2e5
[debug] Python version 3.5.2 - Linux-4.8.4-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.1.5, ffprobe 3.1.5, rtmpdump 2.4
[debug] Proxy map: {}
[tudou] hiFqRBvzzhc: Downloading JSON metadata
[tudou] hiFqRBvzzhc: found 8 parts
[download] Downloading playlist: 小K黑白光影起稿
[tudou] 226570559: Opening the info XML page
[tudou] 226570560: Opening the info XML page
[tudou] 226570561: Opening the info XML page
[tudou] 226570562: Opening the info XML page
[tudou] 226570563: Opening the info XML page
[tudou] 226570564: Opening the info XML page
[tudou] 226570565: Opening the info XML page
[tudou] 226570566: Opening the info XML page
[tudou] playlist 小K黑白光影起稿: Downloading 8 videos
[download] Downloading video 1 of 8
[debug] Invoking downloader on 'http://183.203.12.91/f4v/90/195218190.h264_1_seg_0.04001208005397F6131C156B49543BF3FBFF1F-E4FD-B1CC-FAEC-000226570559.f4v?key=6f0a11d24a62259fd173ef5815e4780040908c9f9a&qrs=1527565239&p=13893658678057396744&playtype=12&tk=75749402255057153200589704&brt=12&bc=0&xid=04001208005397F6131C156B49543BF3FBFF1F-E4FD-B1CC-FAEC-000226570559&nt=0&nw=1&bs=0&ispid=2013&rc=206&inf=12&si=un&npc=4402&pp=-1&ul=0&mt=0&sid=0&pc=0&cip=140.112.230.216&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=226570559&fi=0&sz=11397472'
[download] Destination: 小K黑白光影起稿-226570559.f4v
[download] 100% of 10.87MiB in 00:02
[download] Downloading video 2 of 8
[debug] Invoking downloader on 'http://218.60.18.17/f4v/90/195218190.h264_1_seg_1.04001208015397F613AF324507EAE3B23EAFA3-2430-CB0C-1943-000226570560.f4v?key=ef740fc057586e9e0a36375815e4780040908c9f9a&qrs=286407898&p=1895155021172568641&playtype=12&tk=143483474680011746480121180&brt=12&bc=0&xid=04001208015397F613AF324507EAE3B23EAFA3-2430-CB0C-1943-000226570560&nt=0&nw=1&bs=0&ispid=2013&rc=206&inf=12&si=un&npc=4411&pp=-1&ul=0&mt=0&sid=0&pc=0&cip=140.112.230.216&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=226570560&fi=0&sz=10114131'
[download] Destination: 小K黑白光影起稿-226570560.f4v
[download] 100% of 9.65MiB in 00:05
[download] Downloading video 3 of 8
[debug] Invoking downloader on 'http://58.205.218.9/f4v/90/195218190.h264_1_seg_2.04001208025397F61398BB973E086F9EAA8778-ADFB-FE5F-EBD1-000226570561.f4v?key=593b3e050b6275392a19d45815e4790040908c9f9a&qrs=165334330&p=17619816853973520779&playtype=12&tk=76469989190552710330571671&brt=12&bc=0&xid=04001208025397F61398BB973E086F9EAA8778-ADFB-FE5F-EBD1-000226570561&nt=0&nw=1&bs=0&ispid=2013&rc=200&inf=12&si=un&npc=1172&pp=-1&ul=0&mt=0&sid=0&pc=0&cip=140.112.230.216&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=226570561&fi=0&sz=9617730'
[download] Destination: 小K黑白光影起稿-226570561.f4v
[download] 100% of 9.17MiB in 00:26
[download] Downloading video 4 of 8
[debug] Invoking downloader on 'http://58.205.218.5/f4v/90/195218190.h264_1_seg_3.04001208035397F613E038D365B49C2F831E2D-CECD-831C-B7B8-000226570562.f4v?key=4bba1d155944c4fcc598d55815e4790040908c9f9a&qrs=98225466&p=10693297200344034699&playtype=12&tk=76469978195436432570449360&brt=12&bc=0&xid=04001208035397F613E038D365B49C2F831E2D-CECD-831C-B7B8-000226570562&nt=0&nw=1&bs=0&ispid=2013&rc=200&inf=12&si=un&npc=1168&pp=-1&ul=0&mt=0&sid=0&pc=0&cip=140.112.230.216&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=226570562&fi=0&sz=6190533'
[download] Destination: 小K黑白光影起稿-226570562.f4v
[download] 100% of 5.90MiB in 00:06
[download] Downloading video 5 of 8
[debug] Invoking downloader on 'http://58.205.218.10/f4v/90/195218190.h264_1_seg_4.04001208045397F6135583CFB4600ADBD755EC-ED44-9B69-0811-000226570563.f4v?key=5af695e836412092c55f575815e47a0040908c9f9a&qrs=182111546&p=9019887527204486956&playtype=12&tk=144204094600856136900247296&brt=12&bc=0&xid=04001208045397F6135583CFB4600ADBD755EC-ED44-9B69-0811-000226570563&nt=0&nw=1&bs=0&ispid=2013&rc=200&inf=12&si=un&npc=1173&pp=-1&ul=0&mt=0&sid=0&pc=0&cip=140.112.230.216&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=226570563&fi=0&sz=9637106'
[download] Destination: 小K黑白光影起稿-226570563.f4v
[download] 100% of 9.19MiB in 00:08
[download] Downloading video 6 of 8
[debug] Invoking downloader on 'http://58.205.218.10/f4v/90/195218190.h264_1_seg_5.04001208055397F613D3B702CF60159CDFF5EC-C071-B50A-F8F8-000226570564.f4v?key=78a113da2c683005033c705815e47a0040908c9f9a&qrs=182111546&p=4032737933325729924&playtype=12&tk=75749446235522264260465708&brt=12&bc=0&xid=04001208055397F613D3B702CF60159CDFF5EC-C071-B50A-F8F8-000226570564&nt=0&nw=1&bs=0&ispid=2013&rc=200&inf=12&si=un&npc=1173&pp=-1&ul=0&mt=0&sid=0&pc=0&cip=140.112.230.216&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=226570564&fi=0&sz=11878230'
[download] Destination: 小K黑白光影起稿-226570564.f4v
[download] 100% of 11.33MiB in 00:13
[download] Downloading video 7 of 8
[debug] Invoking downloader on 'http://183.203.12.91/f4v/90/195218190.h264_1_seg_6.04001208065397F6133ABF36BDB5391A306916-4D4A-4308-E8A7-000226570565.f4v?key=be341fab32338565e835155815e47b0040908c9f9a&qrs=1527565239&p=3985873892984952908&playtype=12&tk=75749424245289708750554214&brt=12&bc=0&xid=04001208065397F6133ABF36BDB5391A306916-4D4A-4308-E8A7-000226570565&nt=0&nw=1&bs=0&ispid=2013&rc=206&inf=12&si=un&npc=4402&pp=-1&ul=0&mt=0&sid=0&pc=0&cip=140.112.230.216&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=226570565&fi=0&sz=16695404'
[download] Destination: 小K黑白光影起稿-226570565.f4v
[download] 100% of 15.92MiB in 00:04
[download] Downloading video 8 of 8
[debug] Invoking downloader on 'http://58.205.218.8/f4v/90/195218190.h264_1_seg_7.04001208075397F613C33B868F7F2594DABD45-DECA-3A77-A51B-000226570566.f4v?key=0d38d521e355c36e6c825f5815e47b0040908c9f9a&qrs=148557114&p=15452484519233782021&playtype=12&tk=76469901229622488270422732&brt=12&bc=0&xid=04001208075397F613C33B868F7F2594DABD45-DECA-3A77-A51B-000226570566&nt=0&nw=1&bs=0&ispid=2013&rc=200&inf=12&si=un&npc=1171&pp=-1&ul=0&mt=0&sid=0&pc=0&cip=140.112.230.216&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=226570566&fi=0&sz=13080509'
[download] Destination: 小K黑白光影起稿-226570566.f4v
[download] 100% of 12.47MiB in 00:08
[download] Finished downloading playlist: 小K黑白光影起稿
```
Could you paste the output of ```youtube-dl -v "http://www.tudou.com/programs/view/hiFqRBvzzhc/"```?

**Comment by itchyballsack** [comment]
`[download] Downloading video 2 of 8
[debug] Invoking downloader on 'http://122.72.21.37/f4v/90/195218190.h264_1_seg_1.04001208015397F613AF324507EAE3B23EAFA3-2430-CB0C-1943-000226570560.f4v?key=aeb9d0cbc35f6f26447acc58167aa20040908c9f9a&qrs=622151802&p=5140511443121469457&playtype=12&tk=76469989190553094740824375&brt=12&bc=0&xid=04001208015397F613AF324507EAE3B23EAFA3-2430-CB0C-1943-000226570560&nt=0&nw=1&bs=0&ispid=1004&rc=200&inf=12&si=un&npc=1913&pp=0&ul=0&mt=0&sid=0&pc=0&cip=203.109.149.156&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=226570560&fi=0&sz=10114131'
ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 871, in connect
  File "C:\Python\Python34\lib\socket.py", line 516, in create_connection
  File "C:\Python\Python34\lib\socket.py", line 507, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9z7q18a_\build\youtube_dl\YoutubeDL.py", line 1699, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9z7q18a_\build\youtube_dl\YoutubeDL.py", line 1641, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9z7q18a_\build\youtube_dl\downloader\common.py", line 353, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9z7q18a_\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9z7q18a_\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9z7q18a_\build\youtube_dl\utils.py", line 872, in http_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>`

**Comment by itchyballsack** [comment]
Also the facebook 1080p video update doesn't work, it downloads differently but it still only gets 720, please take a look at the thread again

**Comment by yan12125** [comment]
> [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

That's an issue of Tudou. Their servers are known to be unstable. The only solution is repeating the download. A China proxy may help.

**Comment by itchyballsack** [comment]
To use a proxy with youtube-dl, do I change the proxy settings of my computer? Or, can I use a proxy using a youtube-dl command, (if so, can you please show the command). Thank you

**Comment by yan12125** [comment]
FYI: ```--proxy proxy_ip:proxy_port```

**Comment by itchyballsack** [comment]
Thanks so much, now the download works perfectly
