### ISSUE TITLE
Using --match-filter for comparison playlist_id. Always being skipped.

### ISSUE THREAD

**Issue by rocxteady** [rg3/youtube-dl#11082]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.31*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--cookies', u'cookies.txt', u'--download-archive', u'downloaded.txt', u'--no-post-overwrites', u'--match-filter', u'playlist_index!=NA & playlist_id=504183', u'-o', u'%(playlist_index)s - %(title)s.%(ext)s', u'https://www.lynda.com/Swift-tutorials/AVFoundation-Essentials-iOS-Swift/504183-2.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.31
[debug] Python version 2.7.10 - Darwin-16.1.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

I am trying to make a filter using playlist_id. Example:

youtube-dl -v  --match-filter \"playlist_id=504183\" -o '%(playlist_index)s - %(title)s.%(ext)s' \"https://www.lynda.com/Swift-tutorials/AVFoundation-Essentials-iOS-Swift/504183-2.html\"

But it fails. youtube-dl always skipping event the playlist_id is 504183 for the given URL. I retrieved the JSON file and only thing that I noticed that the playlist_id is a string. Am I writing wrong the comparison?

**Comment by xecodroid** [comment]
I have the same problem when downloading playlists from lynda website.
