### ISSUE TITLE
Google drive link --get-url returns unauthorized URL

### ISSUE THREAD

**Issue by nramirez** [rg3/youtube-dl#11084]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.31*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Google drive links return an unauthorized URL

Log:
```
youtube-dl https://drive.google.com/open?id=0Bxx9FgEMmELFc1ZJXzRXT3AwZm8 --get-url --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://drive.google.com/open?id=0Bxx9FgEMmELFc1ZJXzRXT3AwZm8', u'--get-url', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.20
[debug] Python version 2.7.11 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {'http': 'http://127.0.0.1:8888', u'https': 'http://127.0.0.1:8888'}
WARNING: "id" field is not a string - forcing string conversion
https://r4---sn-q4f7snll.c.docs.google.com/videoplayback?requiressl=yes&id=8bcb6009e7e729cb&itag=18&source=webdrive&ttl=transient&app=texmex&ip=65.111.106.174&ipbits=0&expire=1477954651&cp=QVJMWUpfU1ZTQlhNOll4ZTdKM1l1ZXlY&sparams=requiressl%2Cid%2Citag%2Csource%2Cttl%2Cip%2Cipbits%2Cexpire%2Ccp&signature=A6D614A04BE6A576CE5444ED6516307C4A66C33D.3A3A8338BB838EEC04F0AB2B19EF81B137995B95&key=ck2&mm=30&mn=sn-q4f7snll&ms=nxu&mt=1477940137&mv=m&nh=IgpwcjA0LmRmdzA2Kg03Mi4xNC4yMTMuMTE5&pl=21&sc=yes

```

This URL redirects to an unauthorized path:
```
https://r4---sn-q4f7snll.c.docs.google.com/videoplayback?requiressl=yes&id=8bcb6009e7e729cb&itag=18&source=webdrive&ttl=transient&app=texmex&ip=65.111.106.174&ipbits=0&expire=1477954651&cp=QVJMWUpfU1ZTQlhNOll4ZTdKM1l1ZXlY&sparams=requiressl%2Cid%2Citag%2Csource%2Cttl%2Cip%2Cipbits%2Cexpire%2Ccp&signature=A6D614A04BE6A576CE5444ED6516307C4A66C33D.3A3A8338BB838EEC04F0AB2B19EF81B137995B95&key=ck2&mm=30&mn=sn-q4f7snll&ms=nxu&mt=1477940137&mv=m&nh=IgpwcjA0LmRmdzA2Kg03Mi4xNC4yMTMuMTE5&pl=21&sc=yes
```
This happens for any google drive URL.

![image](https://cloud.githubusercontent.com/assets/1899538/19867908/2881cfe6-9f7c-11e6-9fd6-9a8a8a4eb080.png)

**Comment by yan12125** [comment]
The result link requires cookies.
