### ISSUE TITLE
youtube-dl shows me as a owner  , pull request bug maybe

### ISSUE THREAD

**Issue by siddht1** [rg3/youtube-dl#11092]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.02**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.11.02
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

i just updated my youtube-dl branch (repo) and it shows me as an owner ,

![Uploading Screenshot_2016-11-02_11-39-27.jpg…]()

is it a bug

**Comment by siddht1** [comment]
https://github.com/siddht1/youtube-dl/pull/18

**Comment by yan12125** [comment]
Yes, you are the owner of siddht1/youtube-dl. Anyway, that's controlled by Github Inc., not us.

**Comment by siddht1** [comment]
and you youtube-dl collaborator

**Comment by yan12125** [comment]
Yeah @rg3 added me about 1.5 years ago. It's my pleasure to write codes for this awesome tool!

**Comment by siddht1** [comment]
@yan12125 can you teach me to write the extractors code ,  i want to add support to more sites but i m unable to understand it

**Comment by yan12125** [comment]
First check how to get the video URL. In general looking into the network log of developer tools is useful. Both the latest [Firefox](https://developer.mozilla.org/en-US/docs/Tools) and Chrome have built-in developer tools. Then check some small extractors for how to use functions like ```_download_webpage```, ```_html_search_regex```, etc.

**Comment by siddht1** [comment]
then
i get video id through this ,
i generally use wget or aria if thats indeed a download link ,  

but how to code it for youtube-dl

**Comment by yan12125** [comment]
Here's an example: https://github.com/rg3/youtube-dl/blob/master/README.md#adding-support-for-a-new-site. Add ```'url': video_url``` to the returned dict if there's only one format. Otherwise, use ```'formats'``` for videos with multiple formats.

**Comment by siddht1** [comment]
is any option to directly dump the porn sitez supported by youtube-dl

**Comment by yan12125** [comment]
@siddht1 There's a request #6497 but rejected due to technical complexity of proposed solutions

**Comment by siddht1** [comment]
@yan12125   is it possible to use the age limit to  set it in the other bracket i.e  in a way   (age>18)

**Comment by yan12125** [comment]
I guess ```--match-filter``` works

**Comment by siddht1** [comment]
@yan12125 please give the entire usage , if present  ,  by the way https://github.com/rg3/youtube-dl/issues/6497  is just the opposite i wanted , but can work i.e instead of blocking it , use them with a priority as normal extractor vs porn extractor

**Comment by yan12125** [comment]
Not quite sure what you want. Anyway IRC is a better place for discussions about youtube-dl usages

**Comment by siddht1** [comment]
well dump meant the extractor built for porn sites .  
priority:  
below 18  -> normal
above 18 > porn

**Comment by yan12125** [comment]
You can get a list of extractors by search "age_limit": https://github.com/rg3/youtube-dl/search?utf8=%E2%9C%93&q=age_limit&type=Code

If you want to block normal videos, try ```--match-filter "age_limit >= 18"```

**Comment by siddht1** [comment]
i just noticed there is gh-pages , download-server,rtmp_test  , these branches are inside youtube-dl and no way connected to the youtube-dl python project. whats the purpose

**Comment by siddht1** [comment]
got the previous using find . -name "*.py" | xargs grep -E 'age_limit'   command

**Comment by yan12125** [comment]
gh-pages: Google it!
download-server: for yt-dl.org
rtmp_test: was for #1601, which has been landed, so it should be deleted. Dunno why it's still there
