### ISSUE TITLE
Include the changelog for each version in the Releases posts

### ISSUE THREAD

**Issue by spongbros** [rg3/youtube-dl#11094]
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

When a new version of youtube-dl is released, an entry is created on the [Releases](https://github.com/rg3/youtube-dl/releases) page. On other GitHub projects, each release is usually accompanied by the changelog for that version. However, on the youtube-dl project, the text just reads "Release " followed by the version number. I like to track new releases and changes through RSS/Atom and GitHub provides such feeds of Releases as standard. Unfortunately, as it stands it's not easy to get the latest version's changes in feed form. Keeping tabs on every commit to [the ChangeLog file](https://github.com/rg3/youtube-dl/blob/master/ChangeLog) is unreasonable if one just wants to know what's changed in each release.

Having a changelog (#1626) is helpful but it'd be really useful if it was posted in the Releases for each version. Please and thank you.

**Comment by siddht1** [comment]
i had also requested this idea a long time ago , they suggested me to do it .
turns out its harder to maintain 
but it easy to create
