### ISSUE TITLE
can't download from shahid Plus (Paid Member)

### ISSUE THREAD

**Issue by W5x** [rg3/youtube-dl#11091]
the program don't detect the video from paid links (i'm already paid member there) even if i add my account on Tvideodownloader

but i can download it normally using ffmpeg directly 

please fix that 

thanks in advance

**Comment by W5x** [comment]
@remitamine , give me your  email to send the account privately.

**Comment by remitamine** [comment]
remitamine[at]gmail[dot]com

**Comment by W5x** [comment]
@remitamine Account sent to your email

**Comment by W5x** [comment]
so i have to wait for the next release to have the fix applied right ?

**Comment by remitamine** [comment]
yes.
