### ISSUE TITLE
`Unable to extract video ids` Facebook video URL

### ISSUE THREAD

**Issue by todrobbins** [rg3/youtube-dl#11103]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.02**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ youtube-dl --verbose https://www.facebook.com/yonasda/posts/10154913970456412
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/yonasda/posts/10154913970456412']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.02
[debug] Python version 2.7.10 - Darwin-16.1.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.2, ffprobe 3.2
[debug] Proxy map: {}
[facebook] 10154913970456412: Downloading webpage
ERROR: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 329, in _real_extract
    webpage, 'video ids', group='ids'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 660, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description of your *issue*, suggested solution and other information

Not sure if this is a `facebook.py` parsing issue or not. Thanks!

**Comment by yan12125** [comment]
Yes that's a known bug and I haven't found a way to fix it. For this video, you can download it with:
```
youtube-dl https://www.facebook.com/yonasda/videos/10154913951561412/
```
Please move to #11017 for further discussion.

**Comment by todrobbins** [comment]
Gotcha! So manually swap out the `/posts` slug for `/videos`?

**Comment by yan12125** [comment]
> So manually swap out the ```/posts``` slug for ```/videos``` as a workaround for now?

yeah
