### ISSUE TITLE
%(title)s for output filename is wrong

### ISSUE THREAD

**Issue by Spenhouet** [rg3/youtube-dl#11108]
`youtube-dl -x --audio-format "mp3" --audio-quality 0 --metadata-from-title "%(artist)s - %(title)s" -o "/Music/%(uploader)s/%(title)s.%(ext)s" https://www.youtube.com/watch?v=0sjR0-EG3BM`

The title and artist is parsed correctly:

> [fromtitle] parsed title: Changes
> [fromtitle] parsed artist: DOPEDROP

But for `%(title)s.%(ext)s` the output filename is `DOPEDROP - Changes.mp3`.
I did expect: `Changes.mp3`
When using `%(track)s` or `%(artist)s` the output is `NA`.

Version: 2016.11.02
OS: Windows 10

**Comment by Hrxn** [comment]
Yes and no..

Afaik, the `%(title)s` you use in your output template (-o) is the full title of the video, i.e. that was YouTube is displaying directly below the video frame. And that is in this case: *DOPEDROP - Changes*

Try to use `%(track)s` again..

**Comment by yan12125** [comment]
```--metadata-from-title``` only affects ```--add-metadata```. Variables like ```%(title)s``` are unchanged.

What you want may be an option like --variables-from-title

**Comment by Spenhouet** [comment]
@yan12125 Shouldn't it still affect variables like `%(track)s` or `%(artist)s` ?

If not, than it's not a bug but `--variables-from-title` would be great feature.

**Comment by jblachly** [comment]
> If not, than it's not a bug but --variables-from-title would be great feature.

Yes, 100% this!

I was coming to file a bug report about my output template generating a bunch of `NA - SNAENA - NA.<ext>` files despite that youtube-dl was correctly interpreting the metadata from the title according to the template string I laid out.

Lack of this feature makes youtube-dl use incredibly painful.

One pain point in terms of adding a feature like `--variables-from-title` is that at least in the output I see, the metadata parsing happens after all the files are downloaded, so it would have to rename all the files (and also inteliigently avoid the `NA` thing.

**Comment by yan12125** [comment]
Superseded by #11747. Please move to there for further discussions.
