### ISSUE TITLE
Still problem with svtplay

### ISSUE THREAD

**Issue by norden1** [rg3/youtube-dl#11102]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.02**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.11.02
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by norden1** [comment]
Its still not possible to download from svtplay with latest Youtube dl update 2/11
http://www.svtplay.se/video/10640214/om-ett-hjarta/om-ett-hjarta-sasong-1-avsnitt-1
http://www.svtplay.se/video/10721503/om-ett-hjarta/om-ett-hjarta-sasong-1-avsnitt-2
http://www.svtplay.se/video/10838201/om-ett-hjarta/om-ett-hjarta-sasong-1-avsnitt-3

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by norden1** [comment]
I dont know what you mean the problem is still there why you Close everytime what should i do?

**Comment by dstftw** [comment]
Start reading what I post with eyes.

**Comment by yan12125** [comment]
It's already solved.
```
$ youtube-dl -v "http://www.svtplay.se/video/10640214/om-ett-hjarta/om-ett-hjarta-sasong-1-avsnitt-1"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.svtplay.se/video/10640214/om-ett-hjarta/om-ett-hjarta-sasong-1-avsnitt-1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.02
[debug] Git HEAD: cc99a77
[debug] Python version 3.5.2 - Linux-4.8.4-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[SVTPlay] 10640214: Downloading webpage
[SVTPlay] 1123494-001A: Downloading JSON metadata
[SVTPlay] 1123494-001A: Downloading f4m manifest
[SVTPlay] 1123494-001A: Downloading MPD manifest
[SVTPlay] 1123494-001A: Downloading m3u8 information
[SVTPlay] 1123494-001A: Downloading m3u8 information
[debug] Invoking downloader on 'http://svtplay5g-f.akamaihd.net/d/world/open/delivery/20161014/1123494-001A/dash-live/./'
[dashsegments] Total fragments: 568
[download] Destination: Avsnitt 1-1123494-001A.fdashhbbtv-PG-1123494-001A-OMETTHJARTA-02_2796_1.mp4
[download]   4.0% of ~1.03GiB at  2.19MiB/s ETA 14:49^C
ERROR: Interrupted by user
Exception ignored in: <_io.FileIO name='Avsnitt 1-1123494-001A.fdashhbbtv-PG-1123494-001A-OMETTHJARTA-02_2796_1.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='Avsnitt 1-1123494-001A.fdashhbbtv-PG-1123494-001A-OMETTHJARTA-02_2796_1.mp4.part'>
```
If things are broken for you, paste verbose log or we can do nothing.

**Comment by norden1** [comment]
Now it seems to work. I use Youtube dlg its that problem instead of use only Youtube dl. I update Youtube dlg every time its coming update on Youtube dl i use the update button in Youtube dlg. I miss a function to see which version in Youtube dlg which are in use i hope the program update when i push update.
Thanks for help so long
