### ISSUE TITLE
No metadata saved

### ISSUE THREAD

**Issue by Spenhouet** [rg3/youtube-dl#11107]
`youtube-dl -x --audio-format "mp3" --audio-quality 0 --metadata-from-title "%(artist)s - %(title)s" -o "/Music/%(uploader)s/%(title)s.%(ext)s" https://www.youtube.com/watch?v=0sjR0-EG3BM`

The title and artist is parsed correctly:

> [fromtitle] parsed title: Changes
> [fromtitle] parsed artist: DOPEDROP

But the .mp3 file doesn't contain any metadata.

Version: 2016.11.02
OS: Windows 10

**Comment by dstftw** [comment]
No `--add-metadata` is supplied.

**Comment by Spenhouet** [comment]
With `--add-metadata` it also doesn't save any metadata.

`youtube-dl -x --audio-format "mp3" --audio-quality 0 -o "/Music/%(uploader)s/%(title)s.%(ext)s" --metadata-from-title "%(artist)s - %(title)s" --add-metadata https://www.youtube.com/watch?v=0sjR0-EG3BM`
