### ISSUE TITLE
Support for local FOX affiliate website videos

### ISSUE THREAD

**Issue by rudolphos** [rg3/youtube-dl#11110]
---
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I would like to see fox9.com and possibility to download videos from other local news stations (NBC, CBS, FOX).

Here's an example link for fox9.com
http://www.fox9.com/news/215123287-story

**Comment by Vangelis66** [comment]
@rudolphos wrote: 

> I would like to see fox9.com and possibility to download videos
> (snip) 
> Here's an example link for fox9.com
> http://www.fox9.com/news/215123287-story

Surprisingly
1. This is not geo-blocked (i.e. US-only)! 
2. They are using unencrypted progressive download for the stream!

So, if your only goal is to download the clip, 
you can use URL sniffing (e.g. via Firefox's Web Console) 
to identify the direct clip URI over HTTP; for the 
specific clip referenced, the direct link is: 

`http://pmd.lakana.com/media.fox9.com/video/video_studio/2016/11/02/Bear_climbs_tree_in_downtown_Duluth_314473_1800.mp4` 

Happy downloading!
