### ISSUE TITLE
req help: digital-tutors not parsing properly.

### ISSUE THREAD

**Issue by FredThompsonII** [rg3/youtube-dl#11117]
Would someone please tell me how to configure a digital-tutors job so that it parses properly?

When I use this in a Windoze batch call:

youtube-dl.exe -u username -p password -v --sleep-interval 120 --all-subs -o "C:\Working\Newest\Downloads\-- Cache\digital-tutors" %var_path%

The files don't download and there is a report that the URL isn't formatted properly.

Here's a sample URL:

http://www.digitaltutors.com/tutorial/1832-Your-First-Day-with-WordPress-CMS

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
