### ISSUE TITLE
How to get json in paython

### ISSUE THREAD

**Issue by mitguru007** [rg3/youtube-dl#11112]
I use bellow code but not get in json formate in paython like bellow command
youtube-dl -j url
_________
ydl_opts = {
        'dumpjson': True,
     }

ydl = YoutubeDL(ydl_opts)
     info  = ydl.extract_info(url, download=False)

_______
Why ydl_opts dumpjson not working?

Please help me if and mistek in code then please give me correct code of python.
Thanks in advance.
I use latest youtube-dl version with django..

**Comment by dstftw** [comment]
There is no such option `dumpjson`. Moreover you don't need any option if you get it as return value of `extract_info` that works fine.

**Comment by mitguru007** [comment]
Is extract_info return all avalible formate or only one?
If posible get all avalible formate then how to get all avalible formate?
May be my code return only one url.

**Comment by mitguru007** [comment]
Is extract_info return all avalible formate or only one?
If posible get all avalible formate then how to get all avalible formate?
May be my code return only one formate.

**Comment by yan12125** [comment]
> Is extract_info return all avalible formate or only one?

all

**Comment by mitguru007** [comment]
Okay thanks so much fot your help...

**Comment by mitguru007** [comment]
need some help: 
i use django but only get one url when i use bellow code. how to get all url in loop with link?
please help me..
------------
from django.shortcuts import render
from django.http import HttpResponse
from youtube_dl.version import __version__
from youtube_dl import YoutubeDL
def index(request):
     url = 'https://www.youtube.com/watch?v=pvAsqPbz9Ro'
     ydl = YoutubeDL()
     info  = ydl.extract_info(url, download=False)
     vurl = info['url']
     vtitle = info['title']
     ext = info['ext']
     output = "<a href="+ vurl + "&title="+ vtitle +">Download - "+ ext + "</a>"
     return HttpResponse(output)

**Comment by yan12125** [comment]
Check ```info['formats']``` instead of ```info['url']```
