### ISSUE TITLE
OPENSSL_1.0.2' not found

### ISSUE THREAD

**Issue by hassanghalami** [rg3/youtube-dl#11127]
`ImportError: /opt/lampp/lib/libssl.so.1.0.0: version OPENSSL_1.0.2 not found (required by /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so)`
 this error occured with this code: `echo exec("youtube-dl --help 2>&1",$output);`

**Comment by yan12125** [comment]
You need to either recompile Python or set correct ```$LD_LIBRARY_PATH```.

**Comment by hassanghalami** [comment]
export LD_LIBRARY_PATH="/usr/lib"
i think i totally cleared my library path !!!!

**Comment by yan12125** [comment]
I guess lampp has done something evil. Did you put the ```export``` line in ```exec()```?

**Comment by hassanghalami** [comment]
i did reinstall python ! 
i changed LD_LIBRARY_PATH to /usr/lib but still no change !

**Comment by hassanghalami** [comment]
export LD_LIBRARY_PATH=/usr/lib
i think i totally cleared my library path !!!!

**Comment by yan12125** [comment]
Could you try:
```
exec("LD_LIBRARY_PATH=/usr/lib youtube-dl --help 2>&1",$output)
```

**Comment by hassanghalami** [comment]
resualt:
(currently supported: srt|ass|vtt)

**Comment by yan12125** [comment]
How did you set it? If /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so is still linked to /opt/lampp/lib/libssl.so.1.0.0, you didn't set $LD_LIBRARY_PATH correctly.

**Comment by yan12125** [comment]
> resualt:
(currently supported: srt|ass|vtt)

Yeah that's the last line of ```youtube-dl --help```. You may want to use another function as PHP's exec only returns the last line.

**Comment by hassanghalami** [comment]
OMG , it's working!!!!
thaaaaaaaaaank you my tai friend :D ;)

**Comment by yan12125** [comment]
:smile:
