### ISSUE TITLE
[Bloomberg] ERROR: Unable to extract id

### ISSUE THREAD

**Issue by maXity** [rg3/youtube-dl#11139]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.04*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.bloomberg.com/news/videos/2016-11-07/steve-ballmer-bloomberg-studio-1-0-11-06']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.11.04
[debug] Python version 3.4.4 - Windows-10-10.0.10240
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[Bloomberg] steve-ballmer-bloomberg-studio-1-0-11-06: Downloading webpage
ERROR: Unable to extract id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqdvyr8vw\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqdvyr8vw\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqdvyr8vw\build\youtube_dl\extractor\bloomberg.py", line 52, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqdvyr8vw\build\youtube_dl\extractor\common.py", line 660, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Downloading Bloomberg Studio videos results in aforementioned error. Tried rtmpdump 2.3, 2.4 and none at all, same result. I think this worked before, so I hope it can be fixed?

**Comment by yan12125** [comment]
Could you run this command and upload all *.dump files?
```
youtube-dl -v --write-pages http://www.bloomberg.com/news/videos/2016-11-07/steve-ballmer-bloomberg-studio-1-0-11-06
```

**Comment by maXity** [comment]
Hi Yan, thanks for your reply.

To my surprise, running the same command again worked flawlessly today, although I made no other changes.

Maybe it was a server-side issue?

Thanks for your help though!
