### ISSUE TITLE
[MTV.com] ERROR: Unable to extract mgid

### ISSUE THREAD

**Issue by Transcodes** [rg3/youtube-dl#11148]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.08.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.08.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://www.mtv.com/full-episodes/94bd0m/sweet-vicious-the-blueprint-season-1-ep-101
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.mtv.com/full-episodes/94bd0m/sweet-vicious-the-blueprint-season-1-ep-101']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.11.08.1
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[mtv] sweet-vicious-the-blueprint-season-1-ep-101: Downloading webpage
ERROR: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\mtv.py", line 230, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\mtv.py", line 224, in _extract_mgid
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", line 660, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.mtv.com/full-episodes/dphz30/mary-and-jane-neighborhood-watch-season-1-ep-109
- Single video: http://www.mtv.com/full-episodes/c2xry0/acting-out-acting-out-ep-101-season-1-ep-101
- Playlist: http://www.mtv.com/shows/mary-and-jane/episode-guide

---

### Description of your *issue*, suggested solution and other information

"Unable to extract mgid"
yt-dl worked successfully till 20th Oct 2016
same links do not work anymore..
Please update the extractor so it supports the site again
thanks

**Comment by dstftw** [comment]
This video does not play in browser.

**Comment by mrplePurple** [comment]
This issue still occurs.

Here is a video that does play in browser:
http://www.mtv.com/full-episodes/7kqkgc/real-world-seattle-bad-blood-petered-out-season-32-ep-3207

**Comment by yan12125** [comment]
@mrplePurple your example requires login. Did you provide your credentials?

**Comment by mrplePurple** [comment]
@yan12125 Yes I was, using my APO, username and password in my config file. I'm pretty sure it's something to do with a change in the resulting successful login page.

**Comment by yan12125** [comment]
Could you run this command and upload all the output? Of course remove username and password before uploading.

```
youtube-dl -v --ap-mso (provider ID) --ap-username (username) --ap-password (password) --dump-pages http://www.mtv.com/full-episodes/7kqkgc/real-world-seattle-bad-blood-petered-out-season-32-ep-3207
```

**Comment by mrplePurple** [comment]
Just so you know, I get the same output by simply running

```
youtube-dl -v --ignore-config --dump-pages http://www.mtv.com/full-episodes/7kqkgc/real-world-seattle-bad-blood-petered-out-season-32-ep-3207
```

**Comment by yan12125** [comment]
OK let me reopen it first

**Comment by jonas5** [comment]
MTV does actually not require a login as long as you have a valid ip address from US.

**Comment by StevenDTX** [comment]
bump
