### ISSUE TITLE
Could not find JS function u'yn'

### ISSUE THREAD

**Issue by rchawdhari** [rg3/youtube-dl#11156]
youtube-dl https://youtu.be/mZC868US_IY[youtube] mZC868US_IY: Downloading webpage
[youtube] mZC868US_IY: Downloading video info webpage
[youtube] mZC868US_IY: Extracting video information
[youtube] mZC868US_IY: Downloading js player en_US-vfllAQuZd
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 820, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 883, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'yn'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'yn'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks

**Comment by yan12125** [comment]
You are using an out-dated version. Please check https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl and make sure you're using version 2016.11.08.1
