### ISSUE TITLE
Queue Support + Error Log in Verbose mode

### ISSUE THREAD

**Issue by TehBotolSosro** [rg3/youtube-dl#11151]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.08.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.08.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Please add support for queue, i know you can pass more than one url in youtube-dl #8761 but that seem doesn't really work if we use the -o filename, especially since sometime we really need the -o filename (for each of the url ) due to the original filename aren't supported in windows (eg. more than 250 char)

also using ffmpeg in hls downloader i always get timeout on some of the video segment due to my internet acting up, and knowing these error means the complete video isn't really complete (missing some scene) but i seem never get any error if i use the native hls downloader even if i use verbose mode, so is there any error handling in native hls downloader? like what if some of the segment failed to download, is youtube-dl will warn me about this? and will it warn me when youtube-dl try to retry them? if no then please add a notice when youtube-dl failed to download some of the segment.

thank you so much

**Comment by dstftw** [comment]
1. Multiple URLs works fine with `-o`.
2. Native hls retries each segment on HTTP error 10 times by default (`--fragment-retries`) and stops if error persists. `--skip-unavailable-fragments` will skip unavailable fragments. It will warn in all cases.

**Comment by TehBotolSosro** [comment]
@dstftw i got "ERROR: fixed output name but more than one file to download" when downloading multiple hls (m3u8) url and with multiple -o

thanks again

**Comment by dstftw** [comment]
You are completely misusing `-o`. Bother to read [FAQ](https://github.com/rg3/youtube-dl#output-template).

**Comment by TehBotolSosro** [comment]
@dstftw oops sorry totally missed that >_> 

since the video url doesn't have filename/title (token number) 
i use this -o "Movie%(autonumber)s.%(ext)s" --restrict-filenames

and it's working fine now, result in movie00001.mp4
sorry to bother you thanks :)
