### ISSUE TITLE
Unable to extract json

### ISSUE THREAD

**Issue by SerVerXPlanet** [rg3/youtube-dl#11153]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.08.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
$ youtube-dl -uUSER -pPASSWORD --verbose https://vk.com/video-85296934_456246691
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-uUSER', u'-pPASSWORD', u'--verbose', u'https://vk.com/video-85296934_456246691']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.08.1
[debug] Python version 2.7.12 - Linux-4.4.0-47-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1
[debug] Proxy map: {}
[vk] Downloading login page
[vk] Logging in as USER
[vk] -85296934_456246691: Downloading webpage
ERROR: Unable to extract json
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/vk.py", line 381, in _real_extract
    r'<!json>\s*({.+?})\s*<!>', info_page, 'json'),
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 660, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract json
```
---

**Comment by dstftw** [comment]
>You need to be a member of this group to view its video files.

**Comment by SerVerXPlanet** [comment]
Sorry, but I did not understand the essence of this error. Your response has become a "You need to be a member of this group to view its video files."
