### ISSUE TITLE
could not download videos from spesific youtube channel

### ISSUE THREAD

**Issue by kaveinthran** [rg3/youtube-dl#11162]
hi,I am kaveinthran from Malaysia, and a blind computer user. Thanks for your software, this command line utility helps me a lot.

I am using youtube DL for windows, and had tried to download all videos from the tEDX channel https://www.youtube.com/user/TEDxTalks

after initiating the download, youtube dl scrolled the channel until pg86, and it stopped there for a moment. next,  return an error saying the surver never responded.

downloading from other channel works perfectly.

hope possible update can resolve this,

thanks

**Comment by yan12125** [comment]
> return an error saying the surver never responded.

Sounds an temporary issue. If the problem persists, ```--download-archive``` and ```--ignore-errors``` are useful in such a case.

**Comment by kaveinthran** [comment]
I've tried again, and  after 1 minute, it returns the following
ERROR: Unable to download JSON metadata: <urlopen error [WinError
10060] A connection attempt failed because the connected party did not
properly respond after
a period of time, or established connection failed because connected
host has failed to respond> (caused by URLError(TimeoutError(10060, 'A
connection attempt failed because the connected party did not properly
respond after a period of tim
e, or established connection failed because connected host has failed
to respond

**Comment by yan12125** [comment]
In general TimeoutError are caused by unstable networks. Can you watch TED talks without any halting?

**Comment by kaveinthran** [comment]
BUT, OTHER VIDEOS FROM OTHER CHANNELS ARE DOWNLOADING JUST FINE WITH
GOOD KBPS, SHOULD THERE BE PROBLEMS WITH THE LOADS OF videos in that
TEDX chanel, as the client just scrolling the page, the output will be
like, downloading page1, page 11, page 22, page33, etc.

**Comment by kaveinthran** [comment]
if you want, I can give you the log, after initiation of the download,
what is the command to generate log?

**Comment by yan12125** [comment]
TED's channel are no different than other channels. I'm not sure why either.

This command can be used to generate logs: ```youtube-dl -v https://www.youtube.com/user/TEDxTalks```

**Comment by kaveinthran** [comment]
had tried to generate log, but can't find it in my directory, a good
news is this time, it went until dowloding page 190 , and after
sometime,again, the json download error is back.

**Comment by kaveinthran** [comment]
hi,
now I had set the retries to "infinite" and there're python errors there,

ERROR: Unable to download JSON metadata: <urlopen error [WinError 10060] A conne
ction attempt failed because the connected party did not properly respond after
a period of time, or established connection failed because connected host has fa
iled to respond> (caused by URLError(TimeoutError(10060, 'A connection attempt f
ailed because the connected party did not properly respond after a period of tim
e, or established connection failed because connected host has failed
to respond  ', None, 10060, None),))  File
"C:\Users\dst\AppData\Roaming\Build
archive\youtube-dl\rg3\tmpee_sdt7t\bu
tild\youtube_dl\extractor\common.py", line 404, in _request_webpage
cFile "C:\Users\dst\AppData\Roaming\Build
archive\youtube-dl\rg3\tmpee_sdt7t\bu aild\youtube_dl\YoutubeDL.py",
line 2001, in urlopen iFile
"C:\Python\Python34\lib\urllib\request.py", line 464, in open
File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
\File "C:\Python\Python34\lib\urllib\request.py", line 442, in
_call_chain
File "C:\Users\dst\AppData\Roaming\Build
archive\youtube-dl\rg3\tmpee_sdt7t\bu \ild\youtube_dl\utils.py", line
1036, in https_open
File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open p
o
cI:\TEDX> \
d

**Comment by yan12125** [comment]
The output of that command should be enough for debugging, Could you paste them all?

And by the way, the following command may be useful:
```
youtube-dl -v --ignore-errors --download-archive TED-archive.txt https://www.youtube.com/user/TEDxTalks
```
Run it multiple times and you'll be able to download the whole channel sooner or later.

**Comment by kaveinthran** [comment]
your commands made it work,! theree're about 80 thousand videos in
that channel, it took just about 10 minutes even to just download all
the pages, is there any commands to filter my downloads, so that it
would only download spesific videos, say, english-language, or that
have spesific words? thanks for the assistance!

**Comment by yan12125** [comment]
> is there any commands to filter my downloads, so that it would only download spesific videos, say, english-language, or that have spesific words?

For language: unforunately that's not possible yet as seems YouTube does not provide language information for a video. (only subtitles have such informatoin) If you know how to know the language of a video, please share it

```that have spesific words?```: that's not implemented yet, either. If you want it, feel free to open a new issue

**Comment by kaveinthran** [comment]
hi, sure, will open new issue regarding keyword filters, but for
language, I suppose we could analyse unicode character under a
filename,

**Comment by yan12125** [comment]
> I suppose we could analyse unicode character under a filename

I doubt its accuracy :/
