### ISSUE TITLE
Recursively resolve youtube live channels' name

### ISSUE THREAD

**Issue by baco** [rg3/youtube-dl#11164]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.08.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.08.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Youtube-dl is unable to find video in Youtube channle live

When trying to access a live stream via its channel url's alias, youtube-dl is unable to determine the youtube's URL for the main video and crashes. For example the site https://youtube.com/lanacionmas/live is an alias for the channel https://youtube.com/channel/UCba3hpU7EFBSk817y9qZkiA/live

If I run: ```$ youtube-dl -F https://youtube.com/channel/UCba3hpU7EFBSk817y9qZkiA/live --verbose``` I obtain the expected result, but if I use its alias name *lanacionmas* when running youtube-dl ```$ youtube-dl -F https://youtube.com/lanacionmas/live --verbose``` I get an exception:

    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'-F', u'https://youtube.com/lanacionmas/live', u'--verbose']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2016.11.08.1
    [debug] Python version 2.7.12+ - Linux-4.7.0-1-amd64-x86_64-with-debian-stretch-sid
    [debug] exe versions: avconv 3.1.3-2, avprobe 3.1.3-2, ffmpeg 3.1.3-2, ffprobe 3.1.3-2, rtmpdump 2.4
    [debug] Proxy map: {}
    [youtube:user] lanacionmas: Downloading channel page
    WARNING: Unable to download webpage: HTTP Error 404: Not Found
    [youtube:user] lanacionmas: Downloading page #1
    ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
      File "/tmp/mpv/youtube-dl/youtube_dl/extractor/common.py", line 404, in _request_webpage
        return self._downloader.urlopen(url_or_request)
      File "/tmp/mpv/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
        return self._opener.open(req, timeout=self._socket_timeout)
      File "/usr/lib/python2.7/urllib2.py", line 435, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 473, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by v1kn** [comment]
I am getting similar errors, but the video is no longer live

```
youtube-dl -v https://www.youtube.com/watch?v=jvGDaLqkpTg                                                                                                                                               [1/8976]
[debug] System config: []
[debug] User config: ['-R', '5', '-v', '-w', '-c', '-f', 'best', '-o', '~/Videos/%(title)s.%(ext)s']
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=jvGDaLqkpTg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.08.1
[debug] Python version 3.5.1+ - Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] jvGDaLqkpTg: Downloading webpage
[youtube] jvGDaLqkpTg: Downloading video info webpage
[youtube] Downloading multifeed video (jvGDaLqkpTg, 3AKt1R1aDnw, RtAMM00gpVc, 6N2fdlP3C5U) - add --no-playlist to just download video jvGDaLqkpTg
[download] Downloading playlist: Tom Clancy Free Weekend Rainbow Whatever
[youtube] playlist Tom Clancy Free Weekend Rainbow Whatever: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
[youtube] jvGDaLqkpTg: Downloading webpage
[youtube] jvGDaLqkpTg: Downloading video info webpage
[youtube] jvGDaLqkpTg: Extracting video information
[youtube] jvGDaLqkpTg: Downloading MPD manifest
[debug] Invoking downloader on 'https://redirector.googlevideo.com/videoplayback?requiressl=yes&ip=89.228.161.79&mime=video%2Fmp4&ipbits=0&ratebypass=yes&signature=240E5A83071B2581523841FD27AE32584C46B03F.31D21A93
45EEB2EF0A143BCCFBE215208FE1DFAE&sparams=ei%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Cmime%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&id=jvGDaLqkpTg.1&ei=qromWIPzBIOLd57kkJAO&upn=v3ptTqXZE1c&gcr=pl&itag=18&expire=1
478954762&source=youtube&key=yt6'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/vlkn/.local/pyvenv/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/home/vlkn/.local/pyvenv/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/home/vlkn/.local/pyvenv/lib/python3.5/site-packages/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/home/vlkn/.local/pyvenv/lib/python3.5/site-packages/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/home/vlkn/.local/pyvenv/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by yan12125** [comment]
@v1kn That's a different problem. Could you open a new issue?

**Comment by v1kn** [comment]
@yan12125  Sure, done
