### ISSUE TITLE
--no-part still makes part files

### ISSUE THREAD

**Issue by GraphicsComputing** [rg3/youtube-dl#11169]
Downloading from Periscope
--no-part continues to make .part files.

This particular video makes around 2000 files.

sample:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.periscope.tv/w/1dRJZRbdkzDJB', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.11.08.1
[debug] Python version 2.7.12 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82274-g34aeb5d, ffprobe N-82274-g34aeb5d
[debug] Proxy map: {}
[periscope] 1dRJZRbdkzDJB: Downloading JSON metadata
[periscope] 1dRJZRbdkzDJB: Downloading JSON metadata
[debug] Invoking downloader on u'https://replay.periscope.tv/Aq6UK-W-on2ZTn-emwEewlIkSdcpCHV3PqC3Pdp2R-QkuRXuhC8534JHSBkotHH75mpmm6veWFYzosBqP9eHWA/playlist_1478937354892111396.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1720
[download] Destination: kevin escoto - Trump protest pdx-1dRJZRbdkzDJB.mp4
[download] 100% of 220.89MiB in 05:56
[debug] ffmpeg command line: ffprobe -show_streams 'file:kevin escoto - Trump protest pdx-1dRJZRbdkzDJB.mp4'
[ffmpeg] Fixing malformated aac bitstream in "kevin escoto - Trump protest pdx-1dRJZRbdkzDJB.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:kevin escoto - Trump protest pdx-1dRJZRbdkzDJB.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:kevin escoto - Trump protest pdx-1dRJZRbdkzDJB.temp.mp4'

**Comment by yan12125** [comment]
Those are fragments not ```.part``` files. If you don't want fragments, either add ```--hls-prefer-ffmpeg``` or check #9937
