### ISSUE TITLE
Comedy Central playlist URL download fails

### ISSUE THREAD

**Issue by voltagex** [rg3/youtube-dl#11171]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.08.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.08.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
PS C:\Users\live\Videos> youtube-dl.exe --verbose http://www.cc.com/shows/chappelle-s-show/episode-guide
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.cc.com/shows/chappelle-s-show/episode-guide']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.11.08.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 3.1.4, ffprobe 3.1.4, rtmpdump 2.3
[debug] Proxy map: {}
[ComedyCentral] episode-guide: Downloading webpage
ERROR: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ve
rsion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\YoutubeDL.py", line 694,
in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", lin
e 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\mtv.py", line 2
30, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\mtv.py", line 2
24, in _extract_mgid
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", lin
e 660, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make su
re you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag
and include its complete output....
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Can't download from Comedy Central

**Comment by yan12125** [comment]
Comedy Central playlists are not supported yet. See #10003
