### ISSUE TITLE
Udemy specific lectures

### ISSUE THREAD

**Issue by TarekSalama** [rg3/youtube-dl#11183]
Hello,

Is there a possible way to tell youtube-dl to download lectures x through y?
The only way I tried right now is simply download every lecture on its own which is time consuming.

Thanks and I'm sorry if it's been mentioned somewhere else but I couldn't find an answer in the read me.

**Comment by dstftw** [comment]
```
--playlist-start NUMBER          Playlist video to start at (default is 1)
--playlist-end NUMBER            Playlist video to end at (default is last)
--playlist-items ITEM_SPEC       Playlist video items to download. Specify
                                 indices of the videos in the playlist
                                 separated by commas like: "--playlist-items
                                 1,2,5,8" if you want to download videos
                                 indexed 1, 2, 5, 8 in the playlist. You can
                                 specify range: "--playlist-items
                                 1-3,7,10-13", it will download the videos
                                 at index 1, 2, 3, 7, 10, 11, 12 and 13.
```

**Comment by TarekSalama** [comment]
Thanks for your reply @dstftw .
This method works however the numbering system is probably different.
I trying to download lectures 117 to 121 in a certain Udemy course but youtube-dl insists on downloading from lecture 141. I tried messing around and downloading different lectures but I couldn't find a pattern. It seems that the first "Udemy Section" downloads fine, and then the numbering starts going wrong. Any clue what's going on?

**Comment by TarekSalama** [comment]
@dstftw A reminder just in case you missed my post.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient
