### ISSUE TITLE
windows version can't get all of the youtube descriptions

### ISSUE THREAD

**Issue by Sofronio** [rg3/youtube-dl#11189]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.14.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.14.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.11.14.1
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

For example of the video youtube video BD1-mlqBVvU

I can only get part of the description like this.

> Are you wondering why does it cost 1000$? First of all our main chef is an Owl and his name is Mr.Ramsay... Also those are the only lamb chops that are cooke...

**Comment by dstftw** [comment]
```
> py -2.6 .\youtube_dl\__main__.py BD1-mlqBVvU --get-description
Are you wondering why does it cost 1000$? First of all our main chef is an Owl and his name is Mr.Ramsay... Also those are the only lamb chops that are cooked in the wild forest, near the mountain lake, from 100% organic ingredients such as free-range lamb from Rtanj mountain, wild mountain blueberries for the sauce, homemade cheese from free-range mixed milk, homemade butter, organic parlsey and lemon thyme... Unique taste of the meat is achieved by lamb's special food, that consists of rare Rtanj herbs also used in famous Rtanj herb tea.

This is more than a cooking video, it's a therapy that will satisfy all your sences at once and bring you deep relaxation and peace (probably an ASMR too)! Enjoy!

Ingredients:
600g free-range Rtanj lamb chops
handful of fresh organic thyme and parsley
1 tbsp. homemade butter
200g wild mountain blueberries
1 tbsp. brown sugar
homemade mixed milk cheese (goat and cow)
homemade olive oil
salt, pepper

Help our channel to improve:
Patreon: https://www.patreon.com/AlmazanKtichen

SUBSCRIBE: https://www.youtube.com/c/AlmazanKitchen

Follow us:
Facebook: https://www.facebook.com/AlmazanKitchenRecipes
Twitter: https://twitter.com/almazan_kitchen
Instagram: https://instagram.com/almazan_kitchen
```

**Comment by Sofronio** [comment]
it is a windows version bug, and i'm using the latest version.

**Comment by dstftw** [comment]
It's windows output. Same for executable.

>i'm using the latest version

You've not proved that.

**Comment by Sofronio** [comment]
i got it.
I'm using a youtube-dl gui on the latest version of youtube-dl.
and with the same -f 137+140/best --restrict-filenames --write-sub --write-description --write-thumbnail

if i use -f 137+140/best --restrict-filenames --write-sub --write-description --write-thumbnail in the cmd.exe, the output is right.

but if i use it within youtube-dl gui, it can produce the wrong output.

i'll check it out.

btw

> E:\Bilibili\Tools\youtube-dl>youtube-dl --version
> 2016.11.14.1

**Comment by Sofronio** [comment]
i see.

the youtube-dlg use this path for it's own youtube-dl.exe

> C:\Users\username\AppData\Roaming\youtube-dlg

thank you for your reply.
