### ISSUE TITLE
Videos from xmovies8.org not downloading. ERROR: Unsupported url

### ISSUE THREAD

**Issue by pkgodara** [rg3/youtube-dl#11194]
I tried command "youtube-dl https://xmovies8.org/watch?v=The_Infiltrator_2016#video=8Jm3uGKIRb_pseKu4xzbI4gMnaksmejUnzoRrTH032A" 

Output : 

[generic] watch?v=The_Infiltrator_2016#video=8Jm3uGKIRb_pseKu4xzbI4gMnaksmejUnzoRrTH032A: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=The_Infiltrator_2016#video=8Jm3uGKIRb_pseKu4xzbI4gMnaksmejUnzoRrTH032A: Downloading webpage
[generic] watch?v=The_Infiltrator_2016#video=8Jm3uGKIRb_pseKu4xzbI4gMnaksmejUnzoRrTH032A: Extracting information
ERROR: Unsupported URL: https://xmovies8.org/watch?v=The_Infiltrator_2016#video=8Jm3uGKIRb_pseKu4xzbI4gMnaksmejUnzoRrTH032A

-[] Please try to add this too.

**Comment by pkgodara** [comment]
If I copy video link from right click on playing video and then tried , it worked. 
But didn't work with page url on top bar of browser.

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
