### ISSUE TITLE
Download subtitle Crunchyroll

### ISSUE THREAD

**Issue by Com3Carne** [rg3/youtube-dl#11197]
I'm having difficulty downloading subtitles with specific language, which in the case is Portuguese from Brazil.
I am using command:
`youtube-dl --skip-download --sub-lang ptBR`
I've tried other languages and nothing.
Can anyone tell me where I'm going wrong?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
