### ISSUE TITLE
Issue downloading videos with youtube-dl from udemy course , I already update youtube-dl to latest version.

### ISSUE THREAD

**Issue by sharmakhimlal** [rg3/youtube-dl#11201]
[udemy:course] Downloading login popup
[udemy:course] Logging in as xxx@aaaaxxxx.com
[udemy:course] draft: Downloading webpage
[udemy:course] 138926: Downloading course curriculum
[download] Downloading playlist: 138926
[udemy:course] playlist 138926: Collected 58 video ids (downloading 58 of them)
[download] Downloading video 1 of 58
[udemy] Downloading login popup
[udemy] 850438: Downloading webpage
[udemy] 850438: Downloading lecture JSON
[udemy] 850438: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: 'NoneType' object has no attribute 'copy'

#youtube-dl --version
2016.11.14.1

Please look into the issue and let me know , when this will fix ??

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
