### ISSUE TITLE
Issue downloading videos with youtube-dl from udemy course

### ISSUE THREAD

**Issue by sharmakhimlal** [rg3/youtube-dl#11202]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.14.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.14.1**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[udemy:course] Downloading login popup
[udemy:course] Logging in as xxx@aaaaxxxx.com
[udemy:course] draft: Downloading webpage
[udemy:course] 138926: Downloading course curriculum
[download] Downloading playlist: 138926
[udemy:course] playlist 138926: Collected 58 video ids (downloading 58 of them)
[download] Downloading video 1 of 58
[udemy] Downloading login popup
[udemy] 850438: Downloading webpage
[udemy] 850438: Downloading lecture JSON
[udemy] 850438: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: 'NoneType' object has no attribute 'copy'

Please look into the issue and let me know , when this will fix ??
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.udemy.com/draft/138926/learn/v4/t/lecture/850438

---

### Description of your *issue*, suggested solution and other information

$youtube-dl --version
2016.11.14.1

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by sharmakhimlal** [comment]
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.udemy.com/draft/138926/learn/v4/t/lecture/850438', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.14.1
[debug] Python version 3.4.5 - Linux-2.6.32-642.6.1.el6.x86_64-x86_64-with-centos-6.8-Final
[debug] exe versions: ffmpeg 2.2.1, ffprobe 2.2.1
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as xxxx@xxxaaa.com
[udemy:course] draft: Downloading webpage
[udemy:course] 138926: Downloading course curriculum
[download] Downloading playlist: 138926
[udemy:course] playlist 138926: Collected 58 video ids (downloading 58 of them)
[download] Downloading video 1 of 58
[udemy] Downloading login popup
[udemy] 850438: Downloading webpage
[udemy] 850438: Downloading lecture JSON
[udemy] 850438: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 470, in open
    response = meth(req, response)
  File "/usr/lib64/python3.4/urllib/request.py", line 580, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.4/urllib/request.py", line 508, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 588, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by dstftw** [comment]
> Warning: The Amazon Web Services Certified Solutions Architect - AL course is no longer available to purchase on the Udemy platform. We apologize for any inconvenience. If you have already purchased this course, please log in to your Udemy account to access it.

**Comment by sharmakhimlal** [comment]
I already purchased this course from Udemy but I need to download this course for offline. So for this I need your help to fix this issue ASAP.

**Comment by dstftw** [comment]
For any further investigations you have to provide credentials of account capable to access the course.

**Comment by horusra** [comment]
I have this same issue. if it can be fixed by providing account, I will allow access to my account to one of the developers

**Comment by giacomocerquone** [comment]
I have a 404 error only on this particular course: https://www.udemy.com/react-redux/learn/v4/content

I will not give my credentials (of course), but I'll try to solve the problem somehow and submit a PR when I can

**Comment by vitorpiovezam** [comment]
Error 404: 'NOT FOUND'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
