### ISSUE TITLE
downloaded audio but not video?

### ISSUE THREAD

**Issue by alexbronstein** [rg3/youtube-dl#11218]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

I'm a new user, and even though i checked the --help, the bug is probably me. :)
I tried to download a video from Utube by entering (in a Windows cmd window) after downloading the youtube-dl.exe from your website today:
C:>youtube-dl http://www.youtube.com/watch?v=eJRKiweYxgM

I ended up with a file:
thai life-eJRKiweYxgM.mp4
which only has the soundtrack, when I play it with VLC, but no video.
I'm attaching a zip of it to this ticket.
[thai life-eJRKiweYxgM.zip](https://github.com/rg3/youtube-dl/files/598194/thai.life-eJRKiweYxgM.zip)

I'd be very grateful for any assistance.
Alex Bronstein
alex_bronstein@ieee.org

- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.11.18
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by alexbronstein** [comment]
here is the verbose log:
C:\p\tools>youtube-dl --version
2016.11.18

C:\p\tools>youtube -v http://www.youtube.com/watch?v=eJRKiweYxgM
'youtube' is not recognized as an internal or external command,
operable program or batch file.



C:\p\tools>youtube-dl -v http://www.youtube.com/watch?v=eJRKiweYxgM
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.youtube.com/watch?v=eJRKiweYxgM']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.11.18
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] eJRKiweYxgM: Downloading webpage
[youtube] eJRKiweYxgM: Downloading video info webpage
[youtube] eJRKiweYxgM: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] eJRKiweYxgM: Downloading MPD manifest
[debug] Invoking downloader on 'https://r5---sn-gphvo-ua8e.googlevideo.com/video
playback?ratebypass=yes&itag=18&id=o-ACBMF8_RM-R-N108VL2n1JpU-4WVly_2tC4ujgcZT04
v&lmt=1393852148982197&signature=780C53D169FDDEF9ABA5F116E0795FF6923ACE34.0AAE4F
BA309FB203039D695FCF3D943533A672B1&dur=94.969&initcwndbps=18426250&key=yt6&ip=95
.86.119.20&pl=24&expire=1479430888&mv=m&mt=1479409140&ms=au&mm=31&mn=sn-gphvo-ua
8e&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2C
ms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&source=youtube&ip
bits=0&mime=video%2Fmp4&upn=gnMYtWCM_tU&requiressl=yes'
[download] thai life-eJRKiweYxgM.mp4 has already been downloaded
[download] 100% of 4.09MiB

**Comment by alexbronstein** [comment]
Sorry, I had forgotten to delete the previous output of your program, hence the ".mp4 already exists". Here is a log when starting from scratch:

C:\p\tools>youtube-dl -v http://www.youtube.com/watch?v=eJRKiweYxgM
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.youtube.com/watch?v=eJRKiweYxgM']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.11.18
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] eJRKiweYxgM: Downloading webpage
[youtube] eJRKiweYxgM: Downloading video info webpage
[youtube] eJRKiweYxgM: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] eJRKiweYxgM: Downloading MPD manifest
[debug] Invoking downloader on 'https://r5---sn-gphvo-ua8e.googlevideo.com/video
playback?lmt=1393852148982197&ms=au&source=youtube&dur=94.969&mv=m&pl=24&ip=95.8
6.119.20&requiressl=yes&id=o-AC0dndsRUGK2v1Hp6xo2m7J60UrSEGWgqLh3prd3h6kL&key=yt
6&signature=DB7F278A00597EA59FDED77737B6B51C2AEA1AA0.ABA5523BB3F00CB86F5AA38C56A
DE7797651F2F8&mm=31&mn=sn-gphvo-ua8e&itag=18&mt=1479409444&mime=video%2Fmp4&upn=
w5ew7Wylh2I&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cm
m%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&expire=1
479431178&initcwndbps=18907500&ratebypass=yes&ipbits=0'
[download] Destination: thai life-eJRKiweYxgM.mp4
[download] 100% of 4.09MiB in 00:11

**Comment by dstftw** [comment]
Your zipped file plays fine with latest VLC. Most likely your VLC is outdated.

**Comment by alexbronstein** [comment]
Thanks much. DUK (dumb user on keyboard) as i expected... :)

YAB
