### ISSUE TITLE
very slow download from youtube using windows 10 bash

### ISSUE THREAD

**Issue by Hayderalamily** [rg3/youtube-dl#11212]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.14.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.14.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-cit', u'https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.14.1
[debug] Python version 2.7.12 - Linux-3.4.0+-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv N-81995-gd790e48, avprobe N-81995-gd790e48, ffmpeg N-81995-gd790e48, ffprobe N-81995-gd790e48, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc: Downloading webpage



<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Before , I think 4 days, I encounter very slow down download from Youtube, at first i think this problem from youtube but i do update to my bash and reinstall and install youtube-dl also do a lot of example but same .... the download begin very slow after i hit enter then "Downloading webpage" then it took very long time to proceeds and if i try to download playlist, it take very very long time

- youtube-dl -cit https://www.youtube.com/watch?v=PK0VBj31QuU&list=PLB907756AE023EFAE
- youtube-dl -cit -f 22 https://www.youtube.com/watch?v=PK0VBj31QuU&list=PLB907756AE023EFAE

**Comment by dstftw** [comment]
Most definitely it's an issue with your network connection. youtube-dl does not impose any limits until told so.
`-4` to disable IPv6.
Also carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
