### ISSUE TITLE
Can't DL Last Week Tonight...

### ISSUE THREAD

**Issue by sjmyst** [rg3/youtube-dl#11215]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.14.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.14.1**

[smyst] I ran into the problem and first thing I did was "-U" to get to the latest version.  Still seeing the problem.  After upgrading I see:
bash.exe"-3.1$ youtube-dl --version
2016.11.14.1

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
[smyst] I use youtube-dl in scripts.  It has worked for years.  And, continues to work for other sites.  It appears that this site has been broken (I assume by the website).
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
[sjmyst] Yes.  Found some old (over 1 year old) allmyvideos.net issues.  But, none that seemed related.

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I am providing the output for one of the URLs with '-v'.  I had another issue opened over a year ago that suggested that I remove the "embed" part.  A year ago, that helped.  But, now it seems that both formats of the URL don't work:

bash.exe"-3.1$ youtube-dl --verbose http://allmyvideos.net/embed-fdfwb0butcza.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://allmyvideos.net/embed-fdfwb0butcza.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.11.14.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-67467-g2b14593, ffprobe N-67467-g2b14593, rtmpdump 2.4
[debug] Proxy map: {}
[Moniker] fdfwb0butcza: Downloading webpage
[Moniker] fdfwb0butcza: Downloading video page ...
ERROR: Unable to download webpage: HTTP Error 405: Not Allowed (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9fh1o2s3\build\youtube_dl\extractor\common.py", line 404, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9fh1o2s3\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

bash.exe"-3.1$ youtube-dl --verbose http://allmyvideos.net/fdfwb0butcza.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://allmyvideos.net/fdfwb0butcza.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.11.14.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-67467-g2b14593, ffprobe N-67467-g2b14593, rtmpdump 2.4
[debug] Proxy map: {}
[Moniker] fdfwb0butcza: Downloading webpage
[Moniker] fdfwb0butcza: Downloading video page ...
ERROR: Unable to download webpage: HTTP Error 405: Not Allowed (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9fh1o2s3\build\youtube_dl\extractor\common.py", line 404, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9fh1o2s3\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

bash.exe"-3.1$

Is allmyvideos.net not supported anymore?

Regards,
sjmyst

**Comment by dstftw** [comment]
It does not even work in browser for me.

**Comment by sjmyst** [comment]
I see that now.  Closing this ticket.
