### ISSUE TITLE
Nowvideo problem with some streams

### ISSUE THREAD

**Issue by apolo188** [rg3/youtube-dl#11214]
Some streams works fine like this:http://www.nowvideo.sx/video/c0fdbd803f1fe but others like this :http://www.nowvideo.sx/video/36b65b8c28de1 [ytdl_hook] ERROR: Unable to extract filekey; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update,Idont know why

**Comment by yan12125** [comment]
Duplicate of #10414
