### ISSUE TITLE
Brightcove Issues

### ISSUE THREAD

**Issue by andys87** [rg3/youtube-dl#11227]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Hi, 

Im having the following issue. Pasted is my -v Log - Running on Mac 10.12.1, updated youTube-DL, made sure FFMPEG is configured for SSl support

[generic] michael-moore-in-trumpland: Requesting header
[generic] michael-moore-in-trumpland: Downloading webpage
[generic] michael-moore-in-trumpland: Extracting information
[download] Downloading playlist: Michael Moore In Trumpland
[generic] playlist Michael Moore In Trumpland: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5193943996001: Downloading webpage
[brightcove:new] 5193943996001: Downloading JSON metadata
[brightcove:new] 5193943996001: Downloading m3u8 information
[brightcove:new] 5193943996001: Downloading m3u8 information
[brightcove:new] 5193943996001: Downloading MPD manifest
[debug] Invoking downloader on u'https://secure.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=5193979102001&secure=true&expiration=1479695340000&token=7b5d7f99c6d63d3d15c419baf766886c32e0c272&pubId=2199827728001&videoId=5193943996001'
[hlsnative] Downloading m3u8 manifest
[download] Destination: Michael Moore - I Love You Donald J Trump-5193943996001.mp4
[debug] avconv command line: avconv -y -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
' -i 'https://secure.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=5193979102001&secure=true&expiration=1479695340000&token=7b5d7f99c6d63d3d15c419baf766886c32e0c272&pubId=2199827728001&videoId=5193943996001' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Michael Moore - I Love You Donald J Trump-5193943996001.mp4.part'

**Comment by yan12125** [comment]
Anything wrong? The log looks all good

**Comment by andys87** [comment]
Sorry, I didn't put the whole log in. Pasted below.


[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://tenplay.com.au/channel-one/michael-moore-in-trumpland']
[debug] Encodings: locale UTF-8, fs utf-8, out None, pref UTF-8
[debug] youtube-dl version 2016.11.18
[debug] Python version 2.7.10 - Darwin-16.1.0-x86_64-i386-64bit
[debug] exe versions: avconv 12, avprobe 12, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
WARNING: hlsnative has detected features it does not support, extraction will be delegated to ffmpeg
avconv version 12, Copyright (c) 2000-2016 the Libav developers
  built on Nov 18 2016 11:26:49 with Apple LLVM version 8.0.0 (clang-800.0.42.1)
**https://secure.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=5193979102001&secure=true&expiration=1479695340000&token=7b5d7f99c6d63d3d15c419baf766886c32e0c272&pubId=2199827728001&videoId=5193943996001: Protocol not found
ERROR: ffmpeg exited with code 1**
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 444, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 434, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 705, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 866, in process_ie_result
    extra_info=extra)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 758, in process_ie_result
    extra_info=extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 705, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 751, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1435, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 74, in real_download
    return fd.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/external.py", line 43, in real_download
    self.get_basename(), retval))
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 568, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 530, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by yan12125** [comment]
From the log avconv is used instead of ffmpeg. Worse, it can't find ffmpeg. Where did you install ffmpeg?

**Comment by andys87** [comment]
I did 

$ brew install ffmpeg --with-openssl 
Warning: ffmpeg-3.2 already installed

**Comment by yan12125** [comment]
Could you paste the output of ```ffmpeg -version```?

**Comment by andys87** [comment]
ffmpeg version 3.2 Copyright (c) 2000-2016 the FFmpeg developers
built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
configuration: --prefix=/usr/local/Cellar/ffmpeg/3.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-opencl --enable-openssl --disable-lzma --enable-nonfree --enable-vda
libavutil      55. 34.100 / 55. 34.100
libavcodec     57. 64.100 / 57. 64.100
libavformat    57. 56.100 / 57. 56.100
libavdevice    57.  1.100 / 57.  1.100
libavfilter     6. 65.100 /  6. 65.100
libavresample   3.  1.  0 /  3.  1.  0
libswscale      4.  2.100 /  4.  2.100
libswresample   2.  3.100 /  2.  3.100
libpostproc    54.  1.100 / 54.  1.100

**Comment by yan12125** [comment]
Could you try this:
```
youtube-dl -v --ffmpeg-location /usr/local/bin/ffmpeg https://tenplay.com.au/channel-one/michael-moore-in-trumpland
```
Here ```/usr/local/bin/ffmpeg``` is typical path for ffmpeg. If you install it somewhere else, replace the path with the output of ```which ffmpeg```

**Comment by andys87** [comment]
Thanks, That worked!

**Comment by yan12125** [comment]
Great!
