### ISSUE TITLE
Unable to download youtube videos 

### ISSUE THREAD

**Issue by pinetreegator** [rg3/youtube-dl#11238]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\saturn5>youtube-dl -v https://www.youtube.com/watch?v=gGQrsSEaZkI
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=gGQrsSEaZkI']

[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.11.18
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] gGQrsSEaZkI: Downloading webpage
[youtube] gGQrsSEaZkI: Downloading video info webpage
[youtube] gGQrsSEaZkI: Extracting video information
[youtube] gGQrsSEaZkI: Downloading MPD manifest
[debug] Invoking downloader on 'https://r6---sn-j5caxoxu-pn2l.googlevideo.com/vi
deoplayback?ei=6ZAvWPuGPMWE8wSrkLPQBg&key=yt6&pcm2cms=yes&source=youtube&upn=V9y
LxRDlz68&signature=11E69D855A7831484E036FA538AE05C24D8422A5.DF7FA0927594D5A5A219
81116D465904F60E3205&ratebypass=yes&lmt=1479469176990033&expire=1479533898&requi
ressl=yes&ipbits=0&mime=video%2Fmp4&mv=m&dur=1005.098&mt=1479512075&itag=22&ms=a
u&initcwndbps=1302500&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2
Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csourc
e%2Cupn%2Cexpire&id=o-ADi54lBW0l2Mlab92mCVIwI2qy2Vq000nJ-XdxsQMy2L&mn=sn-j5caxox
u-pn2l&ip=24.228.85.167&mm=31&pl=26'
ERROR: unable to download video data: <urlopen error [WinError 10060] A connecti
on attempt failed because the connected party did not properly respond after a p
eriod of time, or established connection failed because connected host has faile
d to respond>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1279, in connect
  File "C:\Python\Python34\lib\http\client.py", line 871, in connect
  File "C:\Python\Python34\lib\socket.py", line 516, in create_connection
  File "C:\Python\Python34\lib\socket.py", line 507, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected
 party did not properly respond after a period of time, or established connectio
n failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\bu
ild\youtube_dl\YoutubeDL.py", line 1699, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\bu
ild\youtube_dl\YoutubeDL.py", line 1641, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\bu
ild\youtube_dl\downloader\common.py", line 353, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\bu
ild\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\bu
ild\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\bu
ild\youtube_dl\utils.py", line 1036, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt fail
ed because the connected party did not properly respond after a period of time,
or established connection failed because connected host has failed to respond>

C:\Users\saturn5>
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

I updated to the latest version of youtube-dl today and noticed that youtube videos are hit and miss now using the script with most of the times leading to failure to download videos. I've attached the verbose logs above of one of the videos I tried to download. When entering the command in the command prompt it hangs for a few seconds before spitting out the error message.

**Comment by dstftw** [comment]
This error is an indication of connectivity issue between you and YouTube.
