### ISSUE TITLE
Can't download from youtube anymore after updating to latest version

### ISSUE THREAD

**Issue by rudolphos** [rg3/youtube-dl#11232]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.18**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

So this is the script I usually use as .bat where I input youtube video URL or playlist URL (%input%)

```
set /p input="Input URL: "
youtube-dl -ci --write-thumbnail --sub-format ass/srt/best --write-auto-sub -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 "/Videos/%%(uploader)s - %%(title)s (%%(id)s).%%(ext)s" %input%
```

It depends on the video, some videos start downloading, but with some the cmd window just closes.

```
C:\Users\COMPUTER\Desktop\ytdl>youtube-dl -ci --write-thumbnail --sub-format ass/srt/best --write-auto-sub -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 "/Videos/%(uploader)s - %(title)s (%(id)s).%(ext)s" https://www.youtube.com/watch?v=videoID
WARNING: The url doesn't specify the protocol, trying with http
[generic] %(uploader)s - %(title)s (%(id)s): Requesting header
WARNING: Could not send HEAD request to http:///Videos/%(uploader)s - %(title)s (%(id)s).%(ext)s: <urlopen error no host given>
[generic] %(uploader)s - %(title)s (%(id)s): Downloading webpage
ERROR: Unable to download webpage: <urlopen error no host given> (caused by URLError('no host given',))
...
```

**Comment by yan12125** [comment]
You're missing ```-o``` before "/Videos/%(uploader)s - %(title)s (%(id)s).%(ext)s"

**Comment by rudolphos** [comment]
Thanks, it works now. I guess this is a something new, because it was working all the time until I updated.

**Comment by yan12125** [comment]
What's your original version? ```-o``` is there for more than 1 year.

**Comment by rudolphos** [comment]
I guess I might have somehow accidentally removed the `-o`. 
Because I checked the other .bat script which I have (downloads batch of videos, and it has `--output`).

`youtube-dl -ci --write-thumbnail --sub-format ass/srt/best --write-auto-sub -f bestvideo+bestaudio/best --output "%%(uploader)s - %%(title)s (%%(id)s).%%(ext)s" --batch-file="ytdllinks.txt"`

Anyway, it works now, thanks for the help.
