### ISSUE TITLE
Can't download from tf1.fr

### ISSUE THREAD

**Issue by agateau** [rg3/youtube-dl#11249]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://www.tf1.fr/tf1/danse-avec-les-stars/videos/danse-stars-19-novembre-2016.html  
[debug] System config: []  
[debug] User config: []  
[debug] Command-line args: [u'-v', u'http://www.tf1.fr/tf1/danse-avec-les-stars/videos/danse-stars-19-novembre-2016.html']  
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8  
[debug] youtube-dl version 2016.11.18  
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.6  
[debug] exe versions: ffmpeg 2.7.1-static, ffprobe 2.7.1-static, rtmpdump 2.4  
[debug] Proxy map: {}  
[TF1] danse-stars-19-novembre-2016: Downloading webpage  
[wat.tv] 13271048: Downloading JSON metadata  
[wat.tv] 13271048: Downloading JSON metadata  
[wat.tv] 13271048: Downloading m3u8 information  
[wat.tv] 13271048: Downloading f4m manifest  
[wat.tv] 13271048: Extracting http url  
WARNING: Unable to download webpage: HTTP Error 404: Not Found  
[wat.tv] 13271048: Downloading MPD manifest  
[debug] Invoking downloader on u'http://das.q1.tf1.fr/2/USP-0x0/10/48/13271048/ssm/13271048.ism/dash/'  
[dashsegments] Total fragments: 3147  
[download] Destination: Danse avec les stars du 19 novembre 2016-13271048.fdash-video=2500203.mp4  
[download]   0.5% of ~1.74GiB at 103.22KiB/s ETA 01:46:38ERROR: unable to download video data: ''  
Traceback (most recent call last):  
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1693, in process_info  
    partial_success = dl(fname, new_info)  
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl  
    return fd.download(name, info)  
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download  
    return self.real_download(filename, info_dict)  
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 73, in real_download  
    if not process_segment(segment, ctx['tmpfilename'], i):  
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 46, in process_segment  
    success = ctx['dl'].download(target_filename, {'url': segment_url})  
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download  
    return self.real_download(filename, info_dict)  
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download  
    data = self.ydl.urlopen(request)  
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen  
    return self._opener.open(req, timeout=self._socket_timeout)  
  File "/usr/lib/python2.7/urllib2.py", line 431, in open  
    response = self._open(req, data)  
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open  
    '_open', req)  
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain  
    result = func(*args)  
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 872, in http_open  
    req)  
  File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open  
    r = h.getresponse(buffering=True)  
  File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse  
    response.begin()  
  File "/usr/lib/python2.7/httplib.py", line 444, in begin  
    version, status, reason = self._read_status()  
  File "/usr/lib/python2.7/httplib.py", line 408, in _read_status  
    raise BadStatusLine(line)  
BadStatusLine: ''
```

### Description of your *issue*, suggested solution and other information

I can't download a replay of the "Danse avec les stars" show from tf1.fr. It used to work well, I guess they changed their site.

**Comment by midas02** [comment]
Just FYI, works fine for me with version 2016.10.19.

**Comment by dstftw** [comment]
It has nothing to do with versions. It was an intermittent server-side issue.
