### ISSUE TITLE
How exactly do I get this to work/install? (Windows)

### ISSUE THREAD

**Issue by tenminute** [rg3/youtube-dl#11254]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.11.18
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

First time noob here. How exactly do I use/install the Windows .exe? It doesn't actually "install" install right? I downloaded it, put it in a folder, pressed Shift+right-clicked "Open command window here" (Command Prompt opens), I type "youtube-dl.exe https://www.youtube.com/watch?v=DW5jfjN-5RI" (without quotes), and pressed enter.

I seemed to have worked? But where is file? I can't find it anywhere! Is there a way to change the output directory (sorry, haven't looked that up yet)?

Last but not least, how would I enter a live stream to work and not for a download? Just enter the url after "youtube-dl.exe"?

![2016-11-20 at 21-49-06](https://cloud.githubusercontent.com/assets/16367997/20470520/fe75170a-af6e-11e6-8b21-a381cd81713e.jpg)

Edit: Do I, or do I not need Python with the Windows .exe?

**Comment by yan12125** [comment]
You already know everything to make it working :)

> But where is file?

In ```C:\Program Files\youtube-dl```. See the prompt in CMD

> Is there a way to change the output directory

There's an option ```-o```. [Some examples](https://github.com/rg3/youtube-dl/blob/master/README.md#output-template-examples)

> how would I enter a live stream to work and not for a download?

Live streams are tricky. If you want to watch before the download is completed, add ```--hls-use-mpegts```

> Do I, or do I not need Python with the Windows .exe?

Both are fine. youtube-dl comes with its own Python

**Comment by tenminute** [comment]
Thanks @yan12125 

I even tried it twice and it says that it's downloaded already. I know that's normal (from reading/searching), but the file is not there. I can not find it anywhere!

![2016-11-21 at 00-11-18](https://cloud.githubusercontent.com/assets/16367997/20472401/2092b03a-af7f-11e6-9b8f-52cb18def597.jpg)

**Comment by yan12125** [comment]
What's the result if you type ```dir``` in CMD?

**Comment by tenminute** [comment]
This?
![2016-11-21 at 00-42-24](https://cloud.githubusercontent.com/assets/16367997/20473071/bb3ac4c0-af83-11e6-88e4-5e7d01a3fa0b.jpg)

**Comment by yan12125** [comment]
Sorry that's out of my knowledge. Maybe cd to Desktop first is better

**Comment by tenminute** [comment]
Ughhh... don't want it that way. But I guess I may have to do so.

Last question though, if you don't mind answering. Streams are really that tricky, though? If that's really the case and youtube-dl doesn't work for streams... then I will just stick with Livestreamer/Streamlink.

(I was looking for an alternative and I thought this was the way to go for STREAMING)

**Comment by yan12125** [comment]
Reports have that livestreamer is better on handling live streams (#9349), so I guess your answer is there

**Comment by tenminute** [comment]
Well... I'm still trying to find that file I downloaded! =/

Thanks again!

**Comment by jdunn0** [comment]
Write access to directories like `C:\Program Files` are restricted to Administrators on Windows Vista and higher.
For compatibility with older programs that just assume they can write to that directory, Windows will automatically redirect any files written to that directory by a an application without the correct privileges to a VirtualStore folder in your user profile's local appdata directory.
If you ran the Command Prompt without Administrator Access (the default) and the current directory was `C:\Program Files\youtube-dl` then the file you downloaded with youtube-dl is probably in the directory `%LocalAppData%\VirtualStore\Program Files\youtube-dl`.
You could run the Command Prompt with Administrator Access and the file write wouldn't get redirected but that is less secure and would be more hassle as you would need to go through a UAC prompt each time you opened the Command Prompt.

In the future, you should set your current directory to a folder you have write access to like C:\Users\[UserName] (Which is the default directory Command Prompt opens to) and then run youtube-dl from there.
In that case you will need to either run youtube-dl by typing out the full path `"C:\Program Files\youtube-dl\youtube-dl.exe"` or add `C:\Program Files\youtube-dl` to your PATH environment variable and you can just type `youtube-dl.exe` regardless of the current directory you are in.

**Comment by tenminute** [comment]
@jdunn0 Totally forgot about this... but yep! That's where it was, Thanks!
