### ISSUE TITLE
Vodlocker doesn't work half of the time

### ISSUE THREAD

**Issue by tastytea** [rg3/youtube-dl#11268]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --verbose --get-url http://vodlocker.com/lhtpwteyxhea
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--get-url', 'http://vodlocker.com/lhtpwteyxhea']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.22
[debug] Python version 3.4.3 - Linux-4.4.32-gentoo-x86_64-Intel-R-_Core-TM-2_Duo_CPU_T7300_@_2.00GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Video lhtpwteyxhea does not exist
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/vodlocker.py", line 36, in _real_extract
    raise ExtractorError('Video %s does not exist' % video_id, expected=True)
youtube_dl.utils.ExtractorError: Video lhtpwteyxhea does not exist
```

---

### Description of your *issue*, suggested solution and other information

Sometimes vodlocker links work, sometimes not. Even if I use the same URL. When trying to watch a Video in my browser, I often get the message: "The file was removed by administrator". When I reload the page, the video appears.

**Comment by sa7mon** [comment]
This seems like a VodLocker issue. If the video was truly removed by an administrator, youtube-dl won't help you.
