### ISSUE TITLE
Dailymotion and VK issues

### ISSUE THREAD

**Issue by danimalik-54** [rg3/youtube-dl#11264]
## Youtube-dl (Dailymotion and VK) Issues on amazon ubuntu virtual machines 

I have developed an application (GUI) for youtube dl and its working good on local environment however 2 sites are not working when deploying on server here i what i have done already

- Deployed on **Amazon** server (Dedicated Ubuntu 16.04 VM West US region) dailymotion and vk was not working, i though that might be some regional issues, so i have tested it on 12 different amazon regions
- Deployed in **MS Azure** server (Dedicated Ubuntu 16.04 VM) and other then dailymotion and vk i faced issues in some youtube videos as well. 

do they have some kind of IP range restriction or is this some other issue?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
