### ISSUE TITLE
thisoldhouse.com has changed their video urls (again) 

### ISSUE THREAD

**Issue by jmricker** [rg3/youtube-dl#11271]
This is related to closed issue #10837 

## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
J:\Media\Videos>youtube-dl.exe https://www.thisoldhouse.com/tv-episode/ask-toh-s
helf-rough-electric -v 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.thisoldhouse.com/tv-episode/ask-toh-she
lf-rough-electric', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.11.22
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-82151-g1e660fe, ffprobe N-82151-g1e660fe
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://www.thisoldhouse.com/tv-episode/ask-toh-shelf-ro
ugh-electric
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0yt5fyka\bu
ild\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0yt5fyka\bu
ild\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0yt5fyka\bu
ild\youtube_dl\extractor\generic.py", line 2443, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.thisoldhouse.com
/tv-episode/ask-toh-shelf-rough-electric...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.thisoldhouse.com/tv-episode/ask-toh-shelf-rough-electric

---

### Description of your *issue*, suggested solution and other information

This is an easy one. The extractor for AskThisOldHouse.com works fine for most urls except one which for some reason is the only one that deviates from the pattern of the other urls. What is needed is a small change in youtube-dl/youtube_dl/extractor/thisoldhouse.py at line #8.

from
    `_VALID_URL = r'https?://(?:www\.)?thisoldhouse\.com/(?:watch|how-to)/(?P<id>[^/?#]+)'`
to
  `  _VALID_URL = r'https?://(?:www\.)?thisoldhouse\.com/(?:watch|how-to|tv-episode)/(?P<id>[^/?#]+)'`

**Comment by yan12125** [comment]
Thanks for the report and the fix. It will be included in the next version.
