### ISSUE TITLE
Linux Academy Support 

### ISSUE THREAD

**Issue by Ayman97** [rg3/youtube-dl#11289]
I hope to make youtube-dl supported to this site 
https://linuxacademy.com

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by stalledstalin88** [comment]
@Ayman97 Please try https://github.com/vassim/linuxacademy-dl. It's still in its early-alpha but damn cool and useful!

**Comment by Ayman97** [comment]
@stalledstalin88  Thanks alot , i will try it for sure 👍
