### ISSUE TITLE
Unable to download http://newyork.cbslocal.com/'s videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#11285]
Example:
$  youtube-dl -v http://newyork.cbslocal.com/video/3580809-a-very-blue-anniversary/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://newyork.cbslocal.com/video/3580809-a-very-blue-anniversary/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.22
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 3.2-2, ffprobe 3.2-2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 3580809-a-very-blue-anniversary: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3580809-a-very-blue-anniversary: Downloading webpage
[generic] 3580809-a-very-blue-anniversary: Extracting information
ERROR: Unsupported URL: http://newyork.cbslocal.com/video/3580809-a-very-blue-anniversary/
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2443, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://newyork.cbslocal.com/video/3580809-a-very-blue-anniversary/

Thank you in advance. :)

**Comment by yan12125** [comment]
Thanks for the example. CBSLocal New York will be supported in the next version
