### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED on Playlists with --no-check-certificate workaround on

### ISSUE THREAD

**Issue by OliverRC** [rg3/youtube-dl#11293]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*
```
$ youtube-dl.exe https://www.youtube.com/watch?v=PJw3eix8SnA&list=PLueuagiLstKwskpeDxYmKM6OLRiqk7OM2 --no-check-certificate -v
[youtube] PJw3eix8SnA: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
'list' is not recognized as an internal or external command,
operable program or batch file.=
```

### Description

I sit behind a corporate firewall which tends to break SSL ceritifacates. The `no-check-certificate` option works perfectly on single videos from Youtube but not seem to work including a playlist. 
If you include a `list=PLueuagiLstKwskpeDxYmKM6OLRiqk7OM2` parameter it fails with a SSL: CERTIFICATE_VERIFY_FAILED error.

**Comment by yan12125** [comment]
You need to put the URL in double quotes:
```
youtube-dl.exe "https://www.youtube.com/watch?v=PJw3eix8SnAlist=PLueuagiLstKwskpeDxYmKM6OLRiqk7OM2" --no-check-certificate -v
```
See also [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)

**Comment by OliverRC** [comment]
So simple! Thanks for replying, looks like it is working :)
