### ISSUE TITLE
Downloading stops because of restricted content

### ISSUE THREAD

**Issue by computerfreak105** [rg3/youtube-dl#11294]
This YouTube channel contains more Videos than are downloaded because of Content restrictions. Parameters -c should resume downloading, or is there another way to ignore warnings and Keep on downloading? I tried --no-warnings but this doesn't work either.

G:\>youtube-dl --cookies cookies.txt --username <my username> --pas
sword <my password> -f 140/m4a -o G:\yt/%(uploader)s/%(title)s_%(upload_date)s.%(ex
t)s -a you.txt -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', '--username', 'PRIVATE',
 '--password', 'PRIVATE', '-f', '140/m4a', '-o', 'G:\\yt/%(uploader)s/%(title)s_
%(upload_date)s.%(ext)s', '-a', 'you.txt', '-v']
[debug] Batch file urls: ['https://www.youtube.com/channel/UCbcLsAtHOpDJoX9d5ZPn
xiw']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.11.22
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:channel] Downloading login page
[youtube:channel] Logging in
[youtube:channel] UCbcLsAtHOpDJoX9d5ZPnxiw: Downloading channel page
[youtube:playlist] Downloading login page
[youtube:playlist] Logging in
[youtube:playlist] UUbcLsAtHOpDJoX9d5ZPnxiw: Downloading webpage
[download] Downloading playlist: Uploads from A10
[youtube:playlist] UUbcLsAtHOpDJoX9d5ZPnxiw: Downloading page #1
[youtube:playlist] UUbcLsAtHOpDJoX9d5ZPnxiw: Downloading page #2
[youtube:playlist] playlist Uploads from A10: Downloading 126 videos
[download] Downloading video 1 of 126
[youtube] Downloading login page
[youtube] Logging in
[youtube] AlMvruyUDTI: Downloading webpage
[youtube] AlMvruyUDTI: Downloading video info webpage
[youtube] AlMvruyUDTI: Extracting video information
[youtube] {22} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {43} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {18} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {36} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {17} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {136} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {247} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {135} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {244} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {134} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {243} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {133} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {242} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {160} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {278} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {140} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {171} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {249} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {250} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {251} signature length 16.68, html5 player en_US-vflSldmkq
[debug] Invoking downloader on 'https://r7---sn-nfpnnjvh-9anz.googlevideo.com/vi
deoplayback?itag=140&clen=4341317&key=yt6&mime=audio%2Fmp4&gir=yes&keepalive=yes
&ei=HNs3WNelN5GXWJruq5gL&lmt=1480013649581228&initcwndbps=2758750&upn=XvSEZvX5nf
s&source=youtube&pl=26&id=o-ALkLGdNhpAhCSgSR1xfrPBKsfGNdYHg6OuFcjPsI2JkC&mn=sn-n
fpnnjvh-9anz&mm=31&requiressl=yes&ip=85.3.176.221&ms=au&sparams=clen%2Cdur%2Cei%
2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn
%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mv=m&mt=1480055498&dur=364.
948&ipbits=0&expire=1480077181&signature=13EE5AC4F56796D28C4D7043053BBFF896C0394
5.D35874502D72FC70846C743F7765C266FC79E410&ratebypass=yes'
[download] Destination: G:\yt\A10\Ask za 280+ odberatelu dekuji_20161124.m4a
[download] 100% of 4.14MiB in 00:01
WARNING: AlMvruyUDTI: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 2 of 126
[youtube] WTfLUq2yz5s: Downloading webpage
[youtube] WTfLUq2yz5s: Downloading video info webpage
[youtube] WTfLUq2yz5s: Extracting video information
[youtube] {22} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {43} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {18} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {36} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {17} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {136} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {247} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {135} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {244} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {134} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {243} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {133} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {242} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {160} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {278} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {140} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {171} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {249} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {250} signature length 16.68, html5 player en_US-vflSldmkq
[youtube] {251} signature length 16.68, html5 player en_US-vflSldmkq
[debug] Invoking downloader on 'https://r8---sn-nfpnnjvh-9anz.googlevideo.com/vi
deoplayback?ipbits=0&lmt=1479926683216954&source=youtube&dur=105.534&key=yt6&mim
e=audio%2Fmp4&pl=26&clen=1255957&expire=1480077183&keepalive=yes&mm=31&mn=sn-nfp
nnjvh-9anz&ei=H9s3WKn9EIaeWdD6togF&itag=140&ms=au&mt=1480055498&mv=m&upn=t5sDkiu
eeT4&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckee
palive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpir
e&initcwndbps=2758750&gir=yes&ip=85.3.176.221&requiressl=yes&id=o-AN6bNJ9o6x16IG
P65gjEut3bHXK-tOWftC9-WS0JqVn2&signature=29888E57426869418B5F09CE9DC9B9ACFDBEA6B
B.870F35A9A6C1A475BC668FBF392B5C94D3C9B57B&ratebypass=yes'
[download] Destination: G:\yt\A10\Dalsí postavy do miraculous ladybug_20161123.m
4a
[download] 100% of 1.20MiB in 00:00
WARNING: WTfLUq2yz5s: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 3 of 126
[youtube] ydkhdoZeV4s: Downloading webpage
[youtube] ydkhdoZeV4s: Downloading video info webpage
ERROR: ydkhdoZeV4s: YouTube said: This video contains content from On Entertainm
ent, who has blocked it in your country on copyright grounds.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0yt5fyka\bu
ild\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0yt5fyka\bu
ild\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0yt5fyka\bu
ild\youtube_dl\extractor\youtube.py", line 1327, in _real_extract
youtube_dl.utils.ExtractorError: ydkhdoZeV4s: YouTube said: This video contains
content from On Entertainment, who has blocked it in your country on copyright g
rounds.

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.22**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.11.22
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.
-c should make YouTube-dl to continue downloading the next file when one Fails, right?

**Comment by dstftw** [comment]
Use `-i`.
