### ISSUE TITLE
Pipe downloading video to opencv

### ISSUE THREAD

**Issue by austinmilt** [rg3/youtube-dl#11291]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.22**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ X] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I am writing a program to analyze the contents of a Youtube video using opencv. Ideally, I would like to be able to analyze the video while it is downloading (i.e. as if it were streaming on Youtube), and then throw away frames that have already been analyzed without ever writing to disk. Is it possible for me to pipe youtube_dl's download directly to another process rather than to disk, or some other workaround that would achieve my aims?

**Comment by yan12125** [comment]
Like this:
```
youtube-dl -o - <the URL> | your_program
```

**Comment by austinmilt** [comment]
Thanks for your reply yan12125, but you didnt answer my question. Perhaps I need to be more explicit...
 
Let's say I have a Youtube URL and I'm interested in analyzing the video without saving it to disk. Further, I am interested in doing this analysis using opencv in Python. In my Python script, I would write:

`
import cv2, youtube_dl
options = {'outtmpl': #SOMETHING#}
Y = youtube_dl.YoutubeDL(options)
Y.extract_info(r'http://some.url')
`

Does this make more sense?

**Comment by yan12125** [comment]
The ```youtube_dl``` Python library doesn't support streaming to Python objects yet, so the current solution is using ```subprocess.Popen```. For YouTube, things are simpler as they serve plain HTTP files, so you can do something like this:
```Python
info_dict = Y.extract_info(url, download=False)
video_stream = urllib.request.urlopen(info_dict['url'])
# video_stream is a file-like object with read() method
```

**Comment by austinmilt** [comment]
Thanks for your response. I am able to get a stream as you have indicated, but I dont understand what to do with it. How do I decode the stream into a useable format? Others suggest that for live streams you can use opencv's cv2.imdecode and numpy's numpy.fromstring, but I am only getting nonsense from this. Is there further I can do using youtube_dl or do I need to start looking elsewhere after I get the url?

**Comment by yan12125** [comment]
YouTube videos are served as mp4 or webm files. Those files are usually compressed, so you need to decompress them first to get frame-by-frame images.

**Comment by austinmilt** [comment]
Thanks for your help. I'm at a loss for now and can live with downloading the video.
