### ISSUE TITLE
Add subtitle support to FoxNews

### ISSUE THREAD

**Issue by xubuntu4iran** [rg3/youtube-dl#11303]
I learned videos have subtitles, please add support

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by xubuntu4iran** [comment]
http://video.foxnews.com/v/5225271874001/

**Comment by dstftw** [comment]
```
> py -2.7 .\youtube_dl\__main__.py http://video.foxnews.com/v/5225271874001/?#sp=show-clips --list-sub
[foxnews] Downloading Akamai AMP feed
[foxnews] 5225271874001: Downloading f4m manifest
[foxnews] 5225271874001: Downloading m3u8 information
Available subtitles for 5225271874001:
Language formats
en-us    dfxp
```

**Comment by xubuntu4iran** [comment]
is that subtitle suitable for desktop players

**Comment by xubuntu4iran** [comment]
please add srt support, i think that format is not suitable for desktop player which is similar to what you did about Lynda

**Comment by dstftw** [comment]
No srt is provided. Use `--convert-subtitles`.

**Comment by xubuntu4iran** [comment]
it does not post proccess for me and no srt sub
<pre>
C:\Users\IS PC>youtube-dl -v --skip-download --write-sub --convert-subs srt http
://video.foxnews.com/v/5225271874001/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--skip-download', '--write-sub', '--convert-s
ubs', 'srt', 'http://video.foxnews.com/v/5225271874001/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.11.18
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[foxnews] Downloading Akamai AMP feed
[foxnews] 5225271874001: Downloading f4m manifest
[foxnews] 5225271874001: Downloading m3u8 information
[info] Writing video subtitles to: Marco Rubio on what Castro's death means for
Cuba-5225271874001.en-us.dfxp
</pre>

**Comment by dstftw** [comment]
`--convert-subtitles` does not work with `--skip-download`.
