### ISSUE TITLE
Unable to download from http://tv2-stream-od.online.no

### ISSUE THREAD

**Issue by vasilyeu-pavel** [rg3/youtube-dl#11306]
C:\Users\PAVEL\Desktop\1>youtube-dl -v "http://tv2-stream-od.online.no/dashvod3/
_definst_/amlst:1083013_ps12270_pd10755630.smil/manifest.mpd"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://tv2-stream-od.online.no/dashvod3/_defi
nst_/amlst:1083013_ps12270_pd10755630.smil/manifest.mpd']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.11.04
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-52233-gee94362, ffprobe N-52233-gee94362
[debug] Proxy map: {}
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqdvyr8vw\bu
ild\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqdvyr8vw\bu
ild\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqdvyr8vw\bu
ild\youtube_dl\extractor\generic.py", line 1652, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqdvyr8vw\bu
ild\youtube_dl\extractor\common.py", line 924, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.

C:\Users\PAVEL\Desktop\1>yoytube-dl -v "http://tv2-stream-od.online.no/dashvod3/
_definst_/amlst:1083013_ps12270_pd10755630.smil/manifest.mpd"

**Comment by dstftw** [comment]
>404 - File or directory not found.

**Comment by vasilyeu-pavel** [comment]
a Norwegian site and need to get geoblocks apparently so does not work. I have 90% of the files swinging, only 10% of such links does not want to work

**Comment by yan12125** [comment]
Formats in http://tv2-stream-od.online.no/dashvod3/_definst_/amlst:1083013_ps12270_pd10755630.smil/manifest.mpd are all encrypted with libWidevine, which are not supported yet. See #1753
