### ISSUE TITLE
Embeded youtube-dl: persist authentication between multiple instances

### ISSUE THREAD

**Issue by brpaz** [rg3/youtube-dl#11301]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.22**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Hello.  
I am working on a simple python script to be able to backup a list of playlists from Youtube.
The problem is that I have to enter the TFA code for every playlist.
Is there any way I can avoid that? I tried enabling the cookies option but its not working. I think this happens because I am creating a new instance of YoutubeDL for each playlist, but I need to do it, so I can override the output template.

This is the snippet of my code:

```python
  for playlist_id, target_path in playlists.iteritems():
      print colored("Downloading  %s to %s ..." % (playlist_id, target_path ), 'yellow')

      ydl_opts['outtmpl'] = os.path.join(target_path, OUTPUT_FILE_PATTERN)

      ydl = youtube_dl.YoutubeDL(ydl_opts)
      ydl.download([YOUTUBE_PLAYLIST_BASE_URL + playlist_id])
```

It forces me to enter TFA code for each loop iteration.

Any suggestions to overcome this? 
It would be nice if I could just changing the outtmpl property without having to create an entire new YoutubeDL object, but I couldnt find any setter method.

**Comment by dstftw** [comment]
You may use [`cookiefile`](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L198).
