### ISSUE TITLE
SyntaxError: Non-ASCII character '\x92' in file /usr/local/bin/youtube-dl on line 3

### ISSUE THREAD

**Issue by cyberjacob** [rg3/youtube-dl#1131]
[~] # python2.7 /usr/local/bin/youtube-dl 
    File "/usr/local/bin/youtube-dl", line 2
    SyntaxError: Non-ASCII character '\x92' in file /usr/local/bin/youtube-dl on line 3, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
And yes, I read the FAQ

    [~] # python2.7 --version
    Python 2.7.3

**Comment by reoxb** [comment]
I remove youtube-dl and put all this. 

In my case: sudo apt-get remove youtube-dl

# wget https://yt-dl.org/latest/youtube-dl -O /usr/local/bin/youtube-dl
# python2.7  /usr/local/bin/youtube-dl 
youtube-dl https://www.youtube.com/playlist?list=PLg_F6Ppg7ZkHQL0oQEdDG4ST5FK6KCoVt 

for example. and it works for me.
