### ISSUE TITLE
Youtube-dl stops downloading the whole YT playlist when 1 single video is removed

### ISSUE THREAD

**Issue by PannenkoekenNL** [rg3/youtube-dl#11314]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.27**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

Youtube-dl stops downloading the whole YouTube playlist when 1 single video in the playlist is removed.

**Comment by dstftw** [comment]
Use `-i`.
