### ISSUE TITLE
Channel9 videos won't download

### ISSUE THREAD

**Issue by m42a** [rg3/youtube-dl#11323]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.27*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://channel9.msdn.com/Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://channel9.msdn.com/Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.27
[debug] Python version 3.5.2 - Linux-4.8.8-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading web page
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading RSS
[download] Downloading playlist: Comment Feed for Channel 9 - Inside Windows 8: Pedro Teixeira - Thread pools
[channel9] playlist Comment Feed for Channel 9 - Inside Windows 8: Pedro Teixeira - Thread pools: Collected 15 video ids (downloading 15 of them)
[download] Downloading video 1 of 15
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading web page
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading RSS
[download] Downloading playlist: Comment Feed for Channel 9 - Inside Windows 8: Pedro Teixeira - Thread pools
[channel9] playlist Comment Feed for Channel 9 - Inside Windows 8: Pedro Teixeira - Thread pools: Collected 15 video ids (downloading 15 of them)
[download] Downloading video 1 of 15
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading web page
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading RSS
[download] Downloading playlist: Comment Feed for Channel 9 - Inside Windows 8: Pedro Teixeira - Thread pools
[channel9] playlist Comment Feed for Channel 9 - Inside Windows 8: Pedro Teixeira - Thread pools: Collected 15 video ids (downloading 15 of them)
[download] Downloading video 1 of 15
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading web page
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading RSS
[download] Downloading playlist: Comment Feed for Channel 9 - Inside Windows 8: Pedro Teixeira - Thread pools
[channel9] playlist Comment Feed for Channel 9 - Inside Windows 8: Pedro Teixeira - Thread pools: Collected 15 video ids (downloading 15 of them)
[download] Downloading video 1 of 15
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading web page
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading RSS
[download] Downloading playlist: Comment Feed for Channel 9 - Inside Windows 8: Pedro Teixeira - Thread pools
[channel9] playlist Comment Feed for Channel 9 - Inside Windows 8: Pedro Teixeira - Thread pools: Collected 15 video ids (downloading 15 of them)
[download] Downloading video 1 of 15
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading web page
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading RSS
[download] Downloading playlist: Comment Feed for Channel 9 - Inside Windows 8: Pedro Teixeira - Thread pools
[channel9] playlist Comment Feed for Channel 9 - Inside Windows 8: Pedro Teixeira - Thread pools: Collected 15 video ids (downloading 15 of them)
[download] Downloading video 1 of 15
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading web page
[channel9] Shows/Going+Deep/Inside-Windows-8-Pedro-Teixeira-Thread-pool: Downloading RSS
^C
ERROR: Interrupted by user
```
---

### Description of your *issue*, suggested solution and other information

Trying to download a video from Channel9 downloads the rss feed instead, which contains a list of comments pointing to the video page, which causes an infinite loop.  Videos without comments (like https://channel9.msdn.com/Events/CPP/CppCon-2015/Ranges-for-the-Standard-Library) are treated as a playlist with no videos in them, and exit without downloading anything.  This happens even when using `--no-playlist`.

**Comment by splendid25** [comment]
Same problem for me, the website has been redesigned and the channel9 extractor goes into an infinite loop...

**Comment by linglung** [comment]
same here

**Comment by ismail** [comment]
Still the same problem with the 2016.12.09 release.
