### ISSUE TITLE
Send python variable to subprocess

### ISSUE THREAD

**Issue by bokiroki** [rg3/youtube-dl#11325]
Hi i cant find simple answer how to send variable to cmd from python in subrocess.call, variable is url.

from tkinter import Tk
mis = Tk()
adresa = mis.clipboard_get()

import requests
from bs4 import BeautifulSoup
r = requests.get(adresa)
r.content
soup = BeautifulSoup(r.content, "html.parser")
print (soup.prettify())
soup.find_all("iframe", class_="mfp-iframe")
for link in soup.find_all("iframe", class_="mfp-iframe"):
	print (link.get("src"))

**_video_** = (link.get("src"))

import subprocess
subprocess.call('C:\\Users\Boris\Desktop\youtube-dl.exe **_'print (video)'_** -f mp4 -o C:/Users/Boris/Desktop/%(title)s --write-sub --convert-subs srt', shell=True)

**Comment by yan12125** [comment]
LIke this:
```
subprocess.call('youtube-dl ' + video + ' -o foo.mp4')
```
