### ISSUE TITLE
No longer able to download Soundcloud Songs

### ISSUE THREAD

**Issue by NickWinston123** [rg3/youtube-dl#11328]
root@VMServer:/files/anthony# youtube-dl http://soundcloud.com/littlen420/greenaqua --embed-thumbnail -o "%(title)s.%(ext)s" -f mp3 --prefer-ffmpeg --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://soundcloud.com/littlen420/greenaqua', u'--embed-thumbnail', u'-o', u'%(title)s.%(ext)s', u'-f', u'mp3', u'--prefer-ffmpeg', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.27
[debug] Python version 2.7.11+ - Linux-4.4.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[soundcloud] littlen420/greenaqua: Resolving id
[soundcloud] littlen420/greenaqua: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

root@VMServer:/files/anthony#

Ive tried on two different operating systems and as root or not as root and I can still not get it to work

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.
