### ISSUE TITLE
[API] Possible to perform chunked downloads?

### ISSUE THREAD

**Issue by xrisk** [rg3/youtube-dl#11322]
I am trying to use youtube-dl where there is limited disk space. However, I can process chunks of the file separately. 

I am wondering if it is possible to instruct youtube-dl to download a certain range of bytes of the video? I can then process that range, delete the resulting file, and so on.

**Comment by dstftw** [comment]
There is no explicit interface for downloading range of bytes. Moreover it does not make much sense in some cases. For example, some videos are already delivered as chunks (hls, hds, dash, ism). Some are streamed via protocols youtube-dl utilizes 3rdparty tools for. Even in case of plain HTTP download remote server may not support partial downloads and just ignore Range header.

**Comment by xrisk** [comment]
Thank you for your response. I think my best bet right now is to make a fork and modify the http downloader since I am looking to download only from Youtube.

**Comment by dstftw** [comment]
Youtube streams in DASH as well bot only in plain HTTP.
