### ISSUE TITLE
How to Assign Multiple Language Playlist Title?

### ISSUE THREAD

**Issue by Hussard-Wang** [rg3/youtube-dl#11324]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.27*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

- Playlist: https://www.youtube.com/playlist?list=PLYfJOvcvKb2Rh9SEyVqCBVT0ervSc6CXZ

My question is: how to get filenames in correct language when I try download this multi-language playlist above via youtube-dl?

This playlist has multiple language title, it means when I change my default language as zh_cn in google account settings, all titles and descriptions of all videos of this playlist will be all in Simplified Chinese, otherwise it will be English.
When I used youtube-dl to download all videos in this playlist, all titles could only be English. I tried to add login-in in config file or use cookie exported from Chrome, but nothing changed.

Thank all of you.

**Comment by yan12125** [comment]
Looks similar to #10758

**Comment by yan12125** [comment]
Well, my Google account uses "English (Hong Kong)", and I got Chinese playlist titles:
```
$ youtube-dl -vF "https://www.youtube.com/playlist?list=PLYfJOvcvKb2Rh9SEyVqCBVT0ervSc6CXZ"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vF', 'https://www.youtube.com/playlist?list=PLYfJOvcvKb2Rh9SEyVqCBVT0ervSc6CXZ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.27
[debug] Git HEAD: c2530d3
[debug] Python version 3.5.2 - Linux-4.8.10-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.1, ffprobe 3.2.1
[debug] Proxy map: {}
[youtube:playlist] PLYfJOvcvKb2Rh9SEyVqCBVT0ervSc6CXZ: Downloading webpage
[download] Downloading playlist: 【人間菩提】2016年度
[youtube:playlist] PLYfJOvcvKb2Rh9SEyVqCBVT0ervSc6CXZ: Downloading page #1
[youtube:playlist] PLYfJOvcvKb2Rh9SEyVqCBVT0ervSc6CXZ: Downloading page #2
[youtube:playlist] PLYfJOvcvKb2Rh9SEyVqCBVT0ervSc6CXZ: Downloading page #3
[youtube:playlist] playlist 【人間菩提】2016年度: Downloading 333 videos
[download] Downloading video 1 of 333
[youtube] 9ulb3l4uVQA: Downloading webpage
^C
ERROR: Interrupted by user
```

**Comment by Hussard-Wang** [comment]
@yan12125 This playlist title is in Chinese, but the video names are in Multi-languages. 
I tried again just minutes ago, all filenames now become Chinese, while with the same settings, they were English hours ago. So my problem looks like has been solved...
So funny.
I don't know should this issue be closed or still be kept open.

**Comment by yan12125** [comment]
Just tried again and filenames are still English for me. Anyway this issue is the same as #10758, so closing

**Comment by Hussard-Wang** [comment]
Thank you for your help. @yan12125
