### ISSUE TITLE
output template playlist_index issue

### ISSUE THREAD

**Issue by iMrQuake** [rg3/youtube-dl#11339]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.27**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

hi
i have a youtube-dl bug regarding output template naming using playlist_id
 if youtube playlist contains for instance 20 videos
if you ask download 9-10 videos, in output template using playlist_index, I got 1 for video 9 and 2 for video 10
 i want youtube-dm to keep the original index, not the index in the sub set of selected video to download

Youtube-dl nom$ youtube-dl --ignore-config --simulate --playlist-items 3-4 -o "%(playlist_index)s.%(ext)s"   "https://www.youtube.com/playlist?list=PLhCH_nPE4JTrTYw0SCfuv94RPWMMmml0F" --verbose --get-filename
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-config', u'--simulate', u'--playlist-items', u'3-4', u'-o', u'%(playlist_index)s.%(ext)s', u'https://www.youtube.com/playlist?list=PLhCH_nPE4JTrTYw0SCfuv94RPWMMmml0F', u'--verbose', u'--get-filename']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.27
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.1, ffprobe 3.2.1
[debug] Proxy map: {}
1.mp4
2.mp4

Expected filename:
3.mp4
4.mp4

[many thanks

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by yan12125** [comment]
Thanks for the report. It's a known bug (#10591) and there's a possible fix at #10622
