### ISSUE TITLE
increase duration between downloads on Pluralsight 

### ISSUE THREAD

**Issue by mohamed-elsaka** [rg3/youtube-dl#11340]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ x] Feature request (request for a new functionality)
- [ ] Question
- [ x] Other

---
### Description of your *issue*, suggested solution and other information

I received this message from Pluralsight
We have blocked your account because our security systems have flagged your Pluralsight account for an unusual amount activity. This does mean a high volume of requests that are in the realm of a request every 10-30 seconds for a prolonged period of time. Please note that this high volume of activity is in violation of our terms of service [https://www.pluralsight.com/terms].

If you're not aware of anything that could cause this high amount of activity, it's possible that your account may be compromised and you might want to consider changing your password. We will unblock your account when you acknowledge our terms of use by replying to this email and please let us know if you have any questions.

Kamron A. 
Customer Service 
Pluralsight 

---Solution:
Increase duration between downloads > 30 seconds

**Comment by mohamed-elsaka** [comment]
we need to pass arguments of min & max duration here
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/pluralsight.py#L254

**Comment by yan12125** [comment]
You can specify --min-sleep-interval and --max-sleep-interval values to avoid account banning. There are some suggesstions in #6090
