### ISSUE TITLE
vimeo: how to escape special characters like " and * in password(!) (not URL) on windows shell?

### ISSUE THREAD

**Issue by mayowalug** [rg3/youtube-dl#11345]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

As stated in subject line:
vimeo: how to escape special characters like " and * in password(!) (not URL) on windows shell?

If there is no way to do this in the shell, how about adding an option for the --video-password feature that reads from a text file?

thanks

**Comment by dstftw** [comment]
[Similarly to URL](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).

**Comment by mayowalug** [comment]
No. Wouldn't have asked if that worked. Tried it of cource. Not working.

**Comment by hishamhaniffa** [comment]
Guys who still end-up here and the above suggested way doesn't work for you. You can use the interactive password mode in order to bypass the special characters in your password.

**Comment by bitraid** [comment]
Or you can use quotes, for example:
`echo asterisk"*"quote"""` outputs `aterisk*quote"`

**Comment by rautamiekka** [comment]
See if prepending with `^` works since that's Batch's way of escaping.
