### ISSUE TITLE
Site support request: abc.go.com

### ISSUE THREAD

**Issue by ProgrammerAKL** [rg3/youtube-dl#11352]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -o "C:/Video/test-a1" "http://abc.go.com/shows/this-week-with-george-stephanopoulos/episode-guide/2016-11/27-donald-trump-continues-transition-as-fidel-castro-passes" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-o', 'C:/Video/test-a1', 'http://abc.go.com/shows/t
his-week-with-george-stephanopoulos/episode-guide/2016-11/27-donald-trump-contin
ues-transition-as-fidel-castro-passes', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 27-donald-trump-continues-transition-as-fidel-castro-passes: Requestin
g header
WARNING: Falling back on generic information extractor.
[generic] 27-donald-trump-continues-transition-as-fidel-castro-passes: Downloadi
ng webpage
[generic] 27-donald-trump-continues-transition-as-fidel-castro-passes: Extractin
g information
ERROR: Unsupported URL: http://abc.go.com/shows/this-week-with-george-stephanopo
ulos/episode-guide/2016-11/27-donald-trump-continues-transition-as-fidel-castro-
passes
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\bu
ild\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\bu
ild\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\bu
ild\youtube_dl\extractor\generic.py", line 2433, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://abc.go.com/shows/this
-week-with-george-stephanopoulos/episode-guide/2016-11/27-donald-trump-continues
-transition-as-fidel-castro-passes
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included:
- Single video: http://abc.go.com/shows/this-week-with-george-stephanopoulos/episode-guide/2016-11/27-donald-trump-continues-transition-as-fidel-castro-passes
- More URLs and a new URL each week can be found at http://abc.go.com/shows/this-week-with-george-stephanopoulos

---

### Description of your *issue*, suggested solution and other information

May require U.S. IP address and/or U.S. cable account credentials?

**Comment by remitamine** [comment]
```
youtube-dl http://abc.go.com/shows/this-week-with-george-stephanopoulos/episode-guide/2016-11/27-donald-trump-continues-transition-as-fidel-castro-passes
[Go] 27-donald-trump-continues-transition-as-fidel-castro-passes: Downloading webpage
[Go] 3546928: Downloading JSON metadata
[Go] 3546928: Downloading JSON metadata
[Go] 3546928: Downloading m3u8 information
WARNING: ar subtitles not available for 3546928
WARNING: en subtitles not available for 3546928
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 730
[download] Destination: This Week 11_27_16 - Donald Trump Continues Transition as Fidel Castro Passes-3546928.mp4
[download]   0.0% of ~1.19GiB at 20.37KiB/s ETA 20:15:26
```
