### ISSUE TITLE
Rutube site downloading support

### ISSUE THREAD

**Issue by XVilka** [rg3/youtube-dl#1136]
Is it possible to have Rutube (http://rutube.ru) downloading support?

**Comment by unchartedmeridians** [comment]
Is there a reason that ffmpeg is necessary? JDownloader can download from Rutube much faster, I assume because it's not converting on the fly.

**Comment by unchartedmeridians** [comment]
Followup: It seems like JDownloader simply combines the downloaded fragments without reencoding whereas youtube-dl has ffmpeg reencode them on the fly.
