### ISSUE TITLE
[Bug report] exporting youtube playlist links to text file doesnot export all download links if a deleted video exists somewhere in between

### ISSUE THREAD

**Issue by Ctrl-Shift-Escape** [rg3/youtube-dl#11378]
example playlist:
[https://www.youtube.com/playlist?list=PLyXl5CNwJ_jurJpF5heFK75oeWpq9AdvP](https://www.youtube.com/playlist?list=PLyXl5CNwJ_jurJpF5heFK75oeWpq9AdvP)

where video number 53 is a broken link

I am using the windows exe youtube-dl of version 2016.12.01 and using this command on windows

`youtube-dl -g https://www.youtube.com/playlist?list=PLyXl5CNwJ_jurJpF5heFK75oeWpq9AdvP>downloadlinks.txt`

The above command returns only the download links of first 52 videos. The 53rd one is a deleted video causing the program to stop in between.

It gives this error on command line.

> ERROR: rtWUdYZbANI: YouTube said: This video is no longer available because the
YouTube account associated with this video has been terminated.

**Comment by dstftw** [comment]
Use `-i`.

**Comment by Ctrl-Shift-Escape** [comment]
@dstftw thanks for the quick response. can you also tell me how to get the file name the same as video name while downloading from such links.
