### ISSUE TITLE
<urlopen error [Errno 11004] getaddrinfo failed>

### ISSUE THREAD

**Issue by kaymatrix** [rg3/youtube-dl#11388]
I m running youtubedl from a third party tool. When I run in usual DOS command line, Its working fine. But when I run from a tool, its throwing below error message. 
Using: Win7

> Command: E:\YoutubeDownloader\bin\youtube-dl.exe  --output "D:\Youtubes\Qtest\Test.%%(ext)s" --recode-video mp4 "https://www.youtube.com/watch?v=ujFcyRNta7U"
> Working Dir: E:\YoutubeDownloader\bin
> Process Status: Starting
> Process Status: Running
> 
> WARNING: The url doesn't specify the protocol, trying with http
> 
> [generic] watch?v=ujFcyRNta7U": Requesting header
> 
> WARNING: Could not send HEAD request to http://--output "D:\Youtubes\Qtest\Test.%%(ext)s" --recode-video mp4 "https://www.youtube.com/watch?v=ujFcyRNta7U": <urlopen error [Errno 11004] getaddrinfo failed>
> 
> [generic] watch?v=ujFcyRNta7U": Downloading webpage
> 
> ERROR: Unable to download webpage: <urlopen error [Errno 11004] getaddrinfo failed> (caused by URLError(gaierror(11004, 'getaddrinfo failed'),))
> 
> 
> Process Status: NotRunning (Could be completed/Crashed/Stopped/Not yet Started)
> --ProcessCompleted-ExitCode:--1

Same output for verbose too

**Comment by yan12125** [comment]
> When I run in usual DOS command line, Its working fine. But when I run from a tool, its throwing below error message.

Apparently the problem is in that tool. Most likely it didn’t pass correct arguments to youtube-dl.
