### ISSUE TITLE
[Not working] Youtube 1080x1920 mp4

### ISSUE THREAD

**Issue by 98se** [rg3/youtube-dl#11381]
It has not been working since yesterday.

Working: 4K Video Downloader
Sample image: http://i.imgur.com/4b1N5XY.png

Not Working: youtube-dl v2016.12.01
Sample command option : youtube-dl -f 266+140 https://www.youtube.com/watch?v=nSDw6D6bWDM

**Comment by Hrxn** [comment]
YouTube website doesn't show 4K availability for me.

Really sure that this "4K Video Downloader" gets you such a file?

**Comment by yan12125** [comment]
This is the 152.5MB video I get from 4K downloader:
```
$ ffprobe 161206\ KBS\ 희망콘서트\ 여자친구\(GFRIEND\)\ 너\ 그리고\ 나\(NAVILLERA\)\ 예린\ 직캠\ @KBS\ 아레나\(KBS\ 88체육관\).mp4   
ffprobe version 3.2.1 Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 6.2.1 (GCC) 20160830
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-netcdf --enable-shared --enable-version3 --enable-x11grab
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '161206 KBS 희망콘서트 여자친구(GFRIEND) 너 그리고 나(NAVILLERA) 예린 직캠 @KBS 아레나(KBS 88체육관).mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 00:03:42.15, start: 0.000000, bitrate: 5763 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920 [SAR 1:1 DAR 9:16], 5632 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
```
It's 1080x1920.

4K downloader should report correct resolutions.

**Comment by sushipan** [comment]
@Hrxn YES, I just use it , they can download  1080x1920 mp4 file

**Comment by yan12125** [comment]
@sushipan For the video mentioned above, ```--recode-video mp4``` can help. If that doesn't work for you, please paste your logs.

**Comment by sushipan** [comment]
recode video will cost a lot of time,is there an other way?

**Comment by yan12125** [comment]
@sushipan Which video are you downloading?

**Comment by sushipan** [comment]
such as this video
https://www.youtube.com/watch?v=4H4dqBqGS2s

**Comment by Hrxn** [comment]
Well, in accordance with YouTube site regulations, this is the new way where 1080p or 2160p are only available as WebM apparently.

But since WebM is a subset of Matroska, basically, you should be able to demux the files with [mkvtoolnix](https://mkvtoolnix.download/), i.e. extracting the stream from the file.

It should be possible to use these with MP4, I think. Try it with [MP4Box](https://gpac.wp.imt.fr/mp4box/).

**Comment by yan12125** [comment]
I created #13206 after analyzing the behavior of 4K video downloader. It works for https://www.youtube.com/watch?v=4H4dqBqGS2s but I'm not sure whether there will be drawbacks or not. Please test it, thanks!
```
$ youtube-dl -F "https://www.youtube.com/watch?v=4H4dqBqGS2s"
[youtube] 4H4dqBqGS2s: Downloading webpage
[youtube] 4H4dqBqGS2s: Downloading video info webpage
[youtube] 4H4dqBqGS2s: Extracting video information
[youtube] 4H4dqBqGS2s: Downloading MPD manifest
[info] Available formats for 4H4dqBqGS2s:
format code  extension  resolution note
139          m4a        audio only DASH audio   48k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
249          webm       audio only DASH audio   52k , opus @ 50k, 1.29MiB
250          webm       audio only DASH audio   68k , opus @ 70k, 1.71MiB
171          webm       audio only DASH audio  120k , vorbis@128k, 3.06MiB
140          m4a        audio only DASH audio  127k , m4a_dash container, mp4a.40.2@128k (44100Hz)
251          webm       audio only DASH audio  132k , opus @160k, 3.38MiB
278          webm       82x144     144p   36k , webm container, vp9, 30fps, video only, 943.07KiB
160          mp4        82x144     DASH video   39k , avc1.4d400b, 30fps, video only
242          webm       136x240    144p   80k , vp9, 30fps, video only, 2.02MiB
133          mp4        136x240    DASH video   83k , avc1.4d400c, 30fps, video only
243          webm       202x360    240p  148k , vp9, 30fps, video only, 3.72MiB
134          mp4        202x360    DASH video  203k , avc1.4d400d, 30fps, video only
244          webm       270x480    240p  282k , vp9, 30fps, video only, 6.90MiB
135          mp4        270x480    DASH video  370k , avc1.4d4015, 30fps, video only
247          webm       406x720    360p  567k , vp9, 30fps, video only, 13.59MiB
136          mp4        406x720    DASH video  739k , avc1.4d401e, 30fps, video only
248          webm       608x1080   480p  964k , vp9, 30fps, video only, 23.84MiB
137          mp4        608x1080   DASH video 1395k , avc1.64001f, 30fps, video only
271          webm       810x1440   720p 3200k , vp9, 30fps, video only, 77.09MiB
264          mp4        810x1440   DASH video 3316k , avc1.640020, 30fps, video only
313          webm       1216x2160  1080p 6094k , vp9, 30fps, video only, 153.85MiB
266          mp4        1216x2160  DASH video 7470k , avc1.640032, 30fps, video only
272          webm       2160x3840  2160p 18844k , vp9, 30fps, video only, 479.71MiB
138          mp4        2160x3840  DASH video 19728k , avc1.640033, 30fps, video only
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        136x240    small , mp4v.20.3, mp4a.40.2
18           mp4        202x360    medium , avc1.42001E, mp4a.40.2@ 96k
43           webm       640x360    medium , vp8.0, vorbis@128k
22           mp4        406x720    hd720 , avc1.64001F, mp4a.40.2@192k (best)
```

**Comment by Hrxn** [comment]
And no one noticed this before? Well, okay..

I guess this should be tested now with videos that exhibited the problem in the old issue report, which would be what, music videos in 4k?

**Comment by yan12125** [comment]
> And no one noticed this before? Well, okay..

If I can get 1080P, I don't care it's mp4 or webm or mkv. Maybe other people think similar :D

> I guess this should be tested now with videos that exhibited the problem in the old issue report, which would be what, music videos in 4k?

Good idea. It turns out that there's already a test case at https://github.com/yan12125/youtube-dl/blob/5c3ab739ae534e23e405cd649c993039aaf89bbd/youtube_dl/extractor/youtube.py#L749-L764

**Comment by Hrxn** [comment]
> If I can get 1080P, I don't care it's mp4 or webm or mkv. Maybe other people think similar :D

True..
Although WebM with VP9 has benefits, it's more efficient than AVC, allowing for smaller file sizes with no difference in visual quality, which might not make a big difference with lower resolutions, but after a couple of FHD or 4k videos you'll start to notice 😉

**Comment by sushipan** [comment]
But currently, WebM not perform very well on  iOS device, I use libvpx to decode it , but it cost a lot cpu,and the video frames slower than the audio

**Comment by Hrxn** [comment]
Yes, MP4/AVC also has benefits, just pick whatever suits your needs best 😉

**Comment by sushipan** [comment]
@Hrxn @yan12125 
youtube-dl run perfectly all the time on last year, But since last week it  can not get the 1080x1920 videos of mp4 
the same address:https://www.youtube.com/watch?v=4H4dqBqGS2s
Can you help me?
