### ISSUE TITLE
Only one website has a 104 error

### ISSUE THREAD

**Issue by ncs19960831** [rg3/youtube-dl#11395]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.pornhub.com/view_video.php?viewkey=ph582eb46f52fd7', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.5.2+ - Linux-4.1.19-v7-armv7l-with-Kali-kali-rolling-kali-rolling
[debug] exe versions: ffmpeg 3.2.1-1, ffprobe 3.2.1-1, rtmpdump 2.4
[debug] Proxy map: {}
[PornHub] ph582eb46f52fd7: Downloading webpage
ERROR: Unable to download webpage: [Errno 104] Connection reset by peer (caused by ConnectionResetError(104, 'Connection reset by peer')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3/dist-packages/youtube_dl/utils.py", line 872, in http_open
    req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)



...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.pornhub.com/view_video.php?viewkey=ph582eb46f52fd7 
---

### Description of your *issue*, suggested solution and other information

Why am I Debian using the latest version and can not download this movie, but in my computer on the windows system using an older version can be downloaded?Them use the same network.And I can use my browser to visit this website and see film at chrome.
When I want to use a latest version with my computer , but my windows 10 said “This application cannot running with your computer”
Seems that I have some problems ssh, the wrong code can not be a good copy. If you have any questions about the error code, please let me know.
Thank you for your early reply.

**Comment by ncs19960831** [comment]
Hi,I have made new progress.
I downloaded the latest version again on my computer. This time, the software can work and download this site, but I still have a same “104” error in my Debian.

**Comment by dstftw** [comment]
This error indicates a network issue on your Debian.
