### ISSUE TITLE
[Bug Report] exported download links doesnot save as file names

### ISSUE THREAD

**Issue by Ctrl-Shift-Escape** [rg3/youtube-dl#11392]
I am using windows exe version 2016.12.01. I am using the following command to export download links from a youtube playlist to a text file:

`youtube-dl -g -i https://www.youtube.com/playlist?list=PLyXl5CNwJ_jurJpF5heFK75oeWpq9AdvP>downloadlinks.txt`

when i do batch import of links into my download manager(idm), the videos save with the name videoplayback, videoplayback2, videoplayback3,etc and not as the video name in the youtube webpage.

**Comment by yan12125** [comment]
Filenames are different from URLs. If you want filenames, use ```-j``` instead of ```-g```
