### ISSUE TITLE
Downloaded the wrong video from Facebook

### ISSUE THREAD

**Issue by elasca** [rg3/youtube-dl#11409]
Hi, i tried to download this video https://www.facebook.com/TheWalkingDeadAMC/videos/1755353511157466/ but the video i have download it's not the video i have seen in the web, seems to be like youtube-dl online download the last uploaded video of these page, whatever url i tried the video it's always the same, any idea to fix this trouble?

**Comment by elasca** [comment]
The trouble is fixed, if you don't get the video that you want, try on the mobile version, it worked for me.

**Comment by dstftw** [comment]
The video is no longer available and it's most likely fixed with 19b4900b7b33047e439ae9c960f1a8516ecf3ff8.
