### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by Aztek-iwnl** [rg3/youtube-dl#11408]
when i try to play a music in discord with my music bot using soundcloud this message appear:ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)

is there a way to fix this issue

**Comment by yan12125** [comment]
It's already fixed in the latest version. Please check whether you're using version 2016.12.09 or not.
