### ISSUE TITLE
check storage before sending out network requests

### ISSUE THREAD

**Issue by treakiandroid** [rg3/youtube-dl#11401]
Hi,

have a look at this:

```
$ youtube-dl https://bs.to/out/2474073
[generic] 2474073: Requesting header
[redirect] Following redirect to https://vivo.sx/4554d891b6
[Vivo] 4554d891b6: Downloading webpage
WARNING: "id" field is not a string - forcing string conversion
ERROR: unable to open for writing: [Errno 5] Input/output error: 'Doctor.Who.2005.S01E08.Vatertag.German.Dubbed.WS.DVDRiP.XviD.mp4-4554d891b6.mp4.part'
```

you see what, it is requesting all information which are needed to download through the world wide network until it has to find out that it cant store them locally. I think it would be a good idea to check if there is sufficient storage before doing anything else.

thanks

**Comment by dstftw** [comment]
You don't know how many storage is needed in general beforehand until the whole extraction is finished.
This also may be an intermittent issue or not related to storage at all.
