### ISSUE TITLE
update mtime file if it already exist

### ISSUE THREAD

**Issue by crazyiop** [rg3/youtube-dl#11417]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

When I donwload a file that has already been downloaded with the `--no-mtime` option, the mtime of the file is not updated.
The file is not downloaded again, wich is the correct behaviour, but I think the mtime should be updated (like a `touch`).

It would be better to have a filesystem state indepedent of the pre-existence of the file. This will make scripting more coherent and reproduceable. 

#### use case exemple
I have a little app that get video link from users to download them. Later, another program play the videos ordered from the last submited. In the current state, if a video has already been downloaded, I have to treat that edge case to make it goes to the top of the list. With the requested change, a simple date ordering from the file will always be the correct order. 

#### corollary
Alternatively if I first download a file with `--no-mtime`  option and then again without it. It also makes sense to update the file date to the server upload date instead of keeping the first download date. This will solve #10038 in a more consistent manner.

**Comment by yan12125** [comment]
Sorry, but that's impossible. mtime value is from HTTP's ```Last-Modified``` header, which is a supplementary information during the download. There's no  way to get server information without actual downloading.

By the way, as CDNs are popular nowadays, the same video may return different URLs each time and have different ```Last-Modified``` values. It's not a good idea to update a previous downloaded file with information from possibly different links.

**Comment by crazyiop** [comment]
ok for the corollary part then, but my main point, is still feasible : if I run a download several time with `--no-mtime` it should update an existing file's mtime to the current PC date.

**Comment by yan12125** [comment]
The semantic of ```mtime``` is "the last modified time of the corresponding file on the server". For your purpose, ```--exec``` is useful. You may need to write a custom post-processor to detect whether the file is already downloaded or not, see https://github.com/rg3/youtube-dl/pull/11231#issuecomment-261619186

**Comment by crazyiop** [comment]
thanks ! didn't knew of that options.
for reference `--exec "touch {}"` actually does the job.
