### ISSUE TITLE
Facebook no longer working

### ISSUE THREAD

**Issue by imparatu** [rg3/youtube-dl#11410]
[facebook] 1017507131711311: Downloading webpage
[facebook] 1017507131711311: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Downloading facebook videos no longer supported... 

Thank you!

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
