### ISSUE TITLE
Can't download from techtalks.tv

### ISSUE THREAD

**Issue by hrishikeshvganu** [rg3/youtube-dl#11414]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.12.09
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**The file download keeps on rewin**
/tmp youtube-dl -v http://techtalks.tv/talks/hands-on-learning-to-search-for-structured-prediction/61566/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://techtalks.tv/talks/hands-on-learning-to-search-for-structured-prediction/61566/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.09
[debug] Python version 2.7.11 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4, rtmpdump 2.4
[debug] Proxy map: {}
[TechTalks] 61566: Downloading webpage
[debug] Invoking downloader on u'rtmp://64.16.214.85:1935/vod'
[download] Destination: Hands-on Learning to Search for Structured Prediction-61566.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmp://64.16.214.85:1935/vod -o 'Hands-on Learning to Search for Structured Prediction-61566.flv.part' --playpath naacl/2015/mp4:t1.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : 64.16.214.85
[rtmpdump] DEBUG: Parsed app     : vod
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : 64.16.214.85
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : naacl/2015/mp4:t1.mp4
[rtmpdump] DEBUG: tcUrl    : rtmp://64.16.214.85:1935/vod
[rtmpdump] DEBUG: app      : vod
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:          trackinfo, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:	30000.00>
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:	269919000.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:	eng>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:	avc1>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:	48000.00>
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:	431872000.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:	eng>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:	mp4a>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: Property: <Name:      audiochannels, NUMBER:	2.00>
[rtmpdump] DEBUG: Property: <Name:    audiosamplerate, NUMBER:	48000.00>
[rtmpdump] DEBUG: Property: <Name:     videoframerate, NUMBER:	30.00>
[rtmpdump] DEBUG: Property: <Name:             aacaot, NUMBER:	2.00>
[rtmpdump] DEBUG: Property: <Name:           avclevel, NUMBER:	41.00>
[rtmpdump] DEBUG: Property: <Name:         avcprofile, NUMBER:	77.00>
[rtmpdump] DEBUG: Property: <Name:       audiocodecid, STRING:	mp4a>
[rtmpdump] DEBUG: Property: <Name:       videocodecid, STRING:	avc1>
[rtmpdump] DEBUG: Property: <Name:              width, NUMBER:	1280.00>
[rtmpdump] DEBUG: Property: <Name:             height, NUMBER:	720.00>
[rtmpdump] DEBUG: Property: <Name:         frameWidth, NUMBER:	1280.00>
[rtmpdump] DEBUG: Property: <Name:        frameHeight, NUMBER:	720.00>
[rtmpdump] DEBUG: Property: <Name:       displayWidth, NUMBER:	1280.00>
[rtmpdump] DEBUG: Property: <Name:      displayHeight, NUMBER:	720.00>
[rtmpdump] DEBUG: Property: <Name:          framerate, NUMBER:	30.00>
[rtmpdump] DEBUG: Property: <Name:       moovposition, NUMBER:	32.00>
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:	8997.33>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: File has duration: 8997.333333
[rtmpdump] DEBUG: bAudioOnly: 0, size: 18061403
[rtmpdump] DEBUG: Last keyframe found at: 24000 ms, size: 36984, type: 09
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Type Answer   : 03
[rtmpdump] DEBUG: HandShake: Server Uptime : 96850052
[rtmpdump] DEBUG: HandShake: FMS Version   : 3.0.1.1
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 2500000
[rtmpdump] DEBUG: HandleClientBW: client BW = 2500000 2
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 0, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream Begin 0
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 261 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:	FMS/3,5,7,7009>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:	31.00>
[rtmpdump] DEBUG: Property: <Name:               mode, NUMBER:	1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Connection succeeded.>
[rtmpdump] DEBUG: Property: <Name:               data, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            version, STRING:	3,5,7,7009>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: Property: <Name:           clientid, NUMBER:	356200523.00>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:	0.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=24000, stopTime=0, sending play: naacl/2015/mp4:t1.mp4
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 145 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Reset>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Playing and resetting naacl/2015/t1.mp4.>
[rtmpdump] DEBUG: Property: <Name:           clientid, NUMBER:	356200523.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Reset
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 4, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream IsRecorded 1
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 0, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream Begin 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 153 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Start>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Started playing naacl/2015/t1.mp4.>
[rtmpdump] DEBUG: Property: <Name:           clientid, NUMBER:	356200523.00>
[rtmpdump] DEBUG: Property: <Name:         isFastPlay, BOOLEAN:	FALSE>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Start
[rtmpdump] DEBUG: Continuing at TS: 24000 ms
[rtmpdump] Resuming download at: 17423.479 kB / 24.000 sec (0.2%)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 24 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 44 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Data.Start>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 604 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:          trackinfo, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:	30000.00>
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:	269919000.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:	eng>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:	avc1>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:	48000.00>
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:	431872000.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:	eng>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:	mp4a>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: Property: <Name:      audiochannels, NUMBER:	2.00>
[rtmpdump] DEBUG: Property: <Name:    audiosamplerate, NUMBER:	48000.00>
[rtmpdump] DEBUG: Property: <Name:     videoframerate, NUMBER:	30.00>
[rtmpdump] DEBUG: Property: <Name:             aacaot, NUMBER:	2.00>
[rtmpdump] DEBUG: Property: <Name:           avclevel, NUMBER:	41.00>
[rtmpdump] DEBUG: Property: <Name:         avcprofile, NUMBER:	77.00>
[rtmpdump] DEBUG: Property: <Name:       audiocodecid, STRING:	mp4a>
[rtmpdump] DEBUG: Property: <Name:       videocodecid, STRING:	avc1>
[rtmpdump] DEBUG: Property: <Name:              width, NUMBER:	1280.00>

**Comment by dstftw** [comment]
There is no error in the log. Remove partially downloaded file and redownload.

**Comment by hrishikeshvganu** [comment]
Well there's no error in the log but I can see that the download progress goes till say 1.2% and then again restarts from 0%. So it keeps on ` rewinding`, so to say.
