### ISSUE TITLE
I just download the youtube-dl and get the error like this.

### ISSUE THREAD

**Issue by woshichuanqilz** [rg3/youtube-dl#11415]
I am in Chinese and I use the proxy I already set the `https_proxy`

![20161211172304.bmp](http://7xpvdr.com1.z0.glb.clouddn.com/20161211172304.bmp)

**Comment by dstftw** [comment]
Proxy address does not look valid. [This](http://stackoverflow.com/a/28153935/4749894) is how it should look like.
