### ISSUE TITLE
ffmpeg works ok but youtube-dl fails 

### ISSUE THREAD

**Issue by xczheng** [rg3/youtube-dl#11424]
Here the ffmpeg works fine but youtube-dl throws exception with 'Error opening filters!'. Is there an integration problem between youtube-dl and ffmpeg?

Thanks,
Colin

goyoutub@box276$ youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 https://www.youtube.com/watch?v=C0DPdy98e4c --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--extract-audio', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'https://www.youtube.com/watch?v=C0DPdy98e4c', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.12
[debug] Python version 2.7.12 - Linux-3.12.65-20161020.132.ELK6.x86_64-x86_64-with-glibc2.3
[debug] exe versions: ffmpeg 3.2.2-static, ffprobe 3.2.2-static
[debug] Proxy map: {}
[youtube] C0DPdy98e4c: Downloading webpage
[youtube] C0DPdy98e4c: Downloading video info webpage
[youtube] C0DPdy98e4c: Extracting video information
[youtube] C0DPdy98e4c: Downloading MPD manifest
[debug] Invoking downloader on u'https://r2---sn-a5mlrn76.googlevideo.com/videoplayback?id=0b40cf772f7c7b87&itag=140&source=youtube&requiressl=yes&ms=au&mv=u&nh=IgpwcjAzLmxheDE2KgkxMjcuMC4wLjE&pl=23&mm=31&mn=sn-a5mlrn76&ratebypass=yes&mime=audio/mp4&gir=yes&clen=283612&lmt=1407412007036143&dur=17.600&mt=1481546959&signature=5F645614A67511A81A31ED61563D356B0338ADAD.3CC11473240E446772EA6063C45454F7844B5CE7&upn=rl10RMcdWfI&key=dg_yt0&ip=69.89.31.76&ipbits=0&expire=1481568656&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,nh,pl,mm,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] TEST VIDEO-C0DPdy98e4c.m4a has already been downloaded
[download] 100% of 274.68KiB
[ffmpeg] Correcting container in "TEST VIDEO-C0DPdy98e4c.m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'file:TEST VIDEO-C0DPdy98e4c.m4a' -c copy -f mp4 'file:TEST VIDEO-C0DPdy98e4c.temp.m4a'
[debug] ffmpeg command line: ffprobe -show_streams 'file:TEST VIDEO-C0DPdy98e4c.m4a'
[ffmpeg] Destination: TEST VIDEO-C0DPdy98e4c.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:TEST VIDEO-C0DPdy98e4c.m4a' -vn -acodec libmp3lame -q:a 0 'file:TEST VIDEO-C0DPdy98e4c.mp3'
ERROR: audio conversion failed: Error opening filters!
Traceback (most recent call last):
  File "/home2/goyoutub/python27/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1837, in post_process
    files_to_delete, info = pp.run(info)
  File "/home2/goyoutub/python27/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 296, in run
    'audio conversion failed: ' + e.msg)
PostProcessingError

[ ~/ffmpeg-3.2.2-64bit-static ]
goyoutub@box276$ ffmpeg -y -i 'file:TEST VIDEO-C0DPdy98e4c.m4a' -c copy -f mp4 'file:TEST VIDEO-C0DPdy98e4c.temp.m4a'
ffmpeg version 3.2.2-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.1 (Debian 5.4.1-4) 20161202
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-5 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:TEST VIDEO-C0DPdy98e4c.m4a':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf57.56.100
  Duration: 00:00:17.60, start: 0.000000, bitrate: 127 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Output #0, mp4, to 'file:TEST VIDEO-C0DPdy98e4c.temp.m4a':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf57.56.100
    Stream #0:0(und): Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 125 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=     275kB time=00:00:17.57 bitrate= 128.0kbits/s speed=2.42e+03x
video:0kB audio:270kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.650115%
[ ~/ffmpeg-3.2.2-64bit-static ]
goyoutub@box276$ ffprobe -show_streams 'file:TEST VIDEO-C0DPdy98e4c.m4a'
ffprobe version 3.2.2-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 5.4.1 (Debian 5.4.1-4) 20161202
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-5 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:TEST VIDEO-C0DPdy98e4c.m4a':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf57.56.100
  Duration: 00:00:17.60, start: 0.000000, bitrate: 127 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[STREAM]
index=0
codec_name=aac
codec_long_name=AAC (Advanced Audio Coding)
profile=LC
codec_type=audio
codec_time_base=1/44100
codec_tag_string=mp4a
codec_tag=0x6134706d
sample_fmt=fltp
sample_rate=44100
channels=2
channel_layout=stereo
bits_per_sample=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/44100
start_pts=0
start_time=0.000000
duration_ts=776204
duration=17.600998
bit_rate=125769
max_bit_rate=125769
bits_per_raw_sample=N/A
nb_frames=758
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
TAG:language=und
TAG:handler_name=SoundHandler
[/STREAM]
[ ~/ffmpeg-3.2.2-64bit-static ]
goyoutub@box276$ ffmpeg -y -i 'file:TEST VIDEO-C0DPdy98e4c.m4a' -vn -acodec libmp3lame -q:a 0 'file:TEST VIDEO-C0DPdy98e4c.mp3'
ffmpeg version 3.2.2-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.1 (Debian 5.4.1-4) 20161202
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-5 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:TEST VIDEO-C0DPdy98e4c.m4a':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf57.56.100
  Duration: 00:00:17.60, start: 0.000000, bitrate: 127 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Output #0, mp3, to 'file:TEST VIDEO-C0DPdy98e4c.mp3':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    TSSE            : Lavf57.56.100
    Stream #0:0(und): Audio: mp3 (libmp3lame), 44100 Hz, stereo, fltp (default)
    Metadata:
      handler_name    : SoundHandler
      encoder         : Lavc57.64.101 libmp3lame
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
size=     119kB time=00:00:17.60 bitrate=  55.3kbits/s speed= 102x
video:0kB audio:118kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.290099%
[ ~/ffmpeg-3.2.2-64bit-static ]

**Comment by yan12125** [comment]
Could you run youtube-dl with ```--keep-video``` and then run only the second ffmpeg command (conversion to mp3)?

**Comment by xczheng** [comment]
I can't even re-produce this very ODD problem now:
goyoutub@box276$ youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 https://www.youtube.com/watch?v=C0DPdy98e4c --verbose --keep-video
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--extract-audio', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'https://www.youtube.com/watch?v=C0DPdy98e4c', u'--verbose', u'--keep-video']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.12
[debug] Python version 2.7.12 - Linux-3.12.65-20161020.132.ELK6.x86_64-x86_64-with-glibc2.3
[debug] exe versions: ffmpeg 3.2.2-static, ffprobe 3.2.2-static
[debug] Proxy map: {}
[youtube] C0DPdy98e4c: Downloading webpage
[youtube] C0DPdy98e4c: Downloading video info webpage
[youtube] C0DPdy98e4c: Extracting video information
[youtube] C0DPdy98e4c: Downloading MPD manifest
[debug] Invoking downloader on u'https://r2---sn-a5mlrn76.googlevideo.com/videoplayback?id=0b40cf772f7c7b87&itag=133&source=youtube&requiressl=yes&nh=IgpwcjA0LmxheDE2KgkxMjcuMC4wLjE&ms=au&mv=u&pl=23&mm=31&mn=sn-a5mlrn76&ratebypass=yes&mime=video/mp4&gir=yes&clen=503705&lmt=1407412011429135&dur=16.521&signature=859765E3CEC9DCFA156D9192685481D9AA10F0EE.0896662202CA90CC4BAD9A84BAE529382144A903&upn=T6I9RgNHSHs&key=dg_yt0&mt=1481572753&ip=69.89.31.76&ipbits=0&expire=1481594488&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,ms,mv,pl,mm,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: TEST VIDEO-C0DPdy98e4c.f133.mp4
[download] 100% of 491.90KiB in 00:00
[debug] Invoking downloader on u'https://r2---sn-a5mlrn76.googlevideo.com/videoplayback?id=0b40cf772f7c7b87&itag=140&source=youtube&requiressl=yes&nh=IgpwcjA0LmxheDE2KgkxMjcuMC4wLjE&ms=au&mv=u&pl=23&mm=31&mn=sn-a5mlrn76&ratebypass=yes&mime=audio/mp4&gir=yes&clen=283612&lmt=1407412007036143&dur=17.600&signature=31BAA7CF5327384FBEB3A5E5C9D24872D76E68A1.259EB02D9A33D9B391D6D00BD2F9B38303E6F243&upn=T6I9RgNHSHs&key=dg_yt0&mt=1481572753&ip=69.89.31.76&ipbits=0&expire=1481594488&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,ms,mv,pl,mm,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: TEST VIDEO-C0DPdy98e4c.f140.m4a
[download] 100% of 276.96KiB in 00:00
[ffmpeg] Merging formats into "TEST VIDEO-C0DPdy98e4c.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:TEST VIDEO-C0DPdy98e4c.f133.mp4' -i 'file:TEST VIDEO-C0DPdy98e4c.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:TEST VIDEO-C0DPdy98e4c.temp.mp4'
[debug] ffmpeg command line: ffprobe -show_streams 'file:TEST VIDEO-C0DPdy98e4c.mp4'
[ffmpeg] Destination: TEST VIDEO-C0DPdy98e4c.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:TEST VIDEO-C0DPdy98e4c.mp4' -vn -acodec libmp3lame -q:a 0 'file:TEST VIDEO-C0DPdy98e4c.mp3'
[ ~/cmedia ]
goyoutub@box276$ youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 https://www.youtube.com/watch?v=C0DPdy98e4c --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--extract-audio', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'https://www.youtube.com/watch?v=C0DPdy98e4c', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.12
[debug] Python version 2.7.12 - Linux-3.12.65-20161020.132.ELK6.x86_64-x86_64-with-glibc2.3
[debug] exe versions: ffmpeg 3.2.2-static, ffprobe 3.2.2-static
[debug] Proxy map: {}
[youtube] C0DPdy98e4c: Downloading webpage
[youtube] C0DPdy98e4c: Downloading video info webpage
[youtube] C0DPdy98e4c: Extracting video information
[youtube] C0DPdy98e4c: Downloading MPD manifest
[debug] Invoking downloader on u'https://r2---sn-a5mlrn76.googlevideo.com/videoplayback?id=0b40cf772f7c7b87&itag=140&source=youtube&requiressl=yes&mv=u&nh=IgpwcjAxLmxheDE2KgkxMjcuMC4wLjE&mn=sn-a5mlrn76&mm=31&ms=au&pl=23&ratebypass=yes&mime=audio/mp4&gir=yes&clen=283612&lmt=1407412007036143&dur=17.600&mt=1481572753&key=dg_yt0&signature=8D405B61C17752596900812ACDCE903B21C18997.53E35384FAF7CA10AA4E698EC171AC2413641A5D&upn=ESEqz3n-K7M&ip=69.89.31.76&ipbits=0&expire=1481594500&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,nh,mn,mm,ms,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: TEST VIDEO-C0DPdy98e4c.m4a
[download] 100% of 276.96KiB in 00:00
[ffmpeg] Correcting container in "TEST VIDEO-C0DPdy98e4c.m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'file:TEST VIDEO-C0DPdy98e4c.m4a' -c copy -f mp4 'file:TEST VIDEO-C0DPdy98e4c.temp.m4a'
[debug] ffmpeg command line: ffprobe -show_streams 'file:TEST VIDEO-C0DPdy98e4c.m4a'
[ffmpeg] Destination: TEST VIDEO-C0DPdy98e4c.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:TEST VIDEO-C0DPdy98e4c.m4a' -vn -acodec libmp3lame -q:a 0 'file:TEST VIDEO-C0DPdy98e4c.mp3'
Deleting original file TEST VIDEO-C0DPdy98e4c.m4a (pass -k to keep)


Since it's all good now, I am going to close this issue.

Thanks for looking into it.
