### ISSUE TITLE
Add string for playlists with elements from multiple uploaders

### ISSUE THREAD

**Issue by J316** [rg3/youtube-dl#11427]
When downloading something like ".../%(uploader)s/%(playlist)s/%(title)s.%(ext)s" if the playlist contains videos from different channels a subfolder for each channel will be created. A command should be added to create a  subfolder only for the creator of the playlist, for example "%(playlist_uploader)s"

**Comment by J316** [comment]
@yan12125
When downloading the playlists of a channel, often those playlists contain videos from other channels talking about the same matter, so when I use a command like ".../%(uploader)s/%(playlist)s/%(title)s.%(ext)s" it downloads the videos from other authors into other folders named by the author of the video, not the author of the playlist, which is tedious. So adding a command like "%(playlist_uploader)s" would solve this issue without me entering the name of the uploader instead of the much convenient "%(uploader)s" string.

**Comment by yan12125** [comment]
I might be unclear. Could you paste an URL of such a playlist? It would be helpful in debugging with real examples.

**Comment by J316** [comment]
@yan12125 
You could pick any, but [here's an example
](https://www.youtube.com/playlist?list=PLVzN38k1pRfdCFtg4ElmpVphff42zPr5Q)

**Comment by yan12125** [comment]
Thanks for the example; I see your need.

**Comment by mozbugbox** [comment]
I'd like to see playlist owner/creator in --json --flat-playlist output too.

**Comment by Kimi-Arthur** [comment]
Please also add the playlist owner/creator in Python API when you come back to this issue.

Thanks!
