### ISSUE TITLE
Feature request - viavisolutions.com

### ISSUE THREAD

**Issue by ds2k5** [rg3/youtube-dl#11421]
- [X] Feature request (request for a new functionality)

Download from: http://www.viavisolutions.com/en-us/services-and-support/services/training/webinars

for example

http://www.viavisolutions.com/en-us/webinars/2016/minimize-network-downtime-effective-fiber-monitoring

Thanks

**Comment by coreynicholson** [comment]
The example you posted links to a brightcove video which seems to already be supported by youtube-dl.

The url in question: http://players.brightcove.net/4303072872001/default_default/index.html?videoId=5205582144001

**Comment by ds2k5** [comment]
thanks, how did you find the Video URL ?

**Comment by coreynicholson** [comment]
When I clicked the "Watch the recording" button it opened a new tab with that link in the url bar.
Also you can right click the button and copy the link.

**Comment by ds2k5** [comment]
thanks a lot!

**Comment by ds2k5** [comment]
can you help me with some other links too ?

for example:

http://www.viavisolutions.com/en-us/webinars/2016/how-catch-hacker

http://www.viavisolutions.com/en-us/webinars/2016/wireshark-week-security-secrets-network-teams

**Comment by coreynicholson** [comment]
Those links seem to require you to register. Maybe after you register it will link you to another video on brightcove? I'm not sure, you'd have to register and find out.

**Comment by ds2k5** [comment]
Hi,
>Those links seem to require you to register.
thanks but got only this URL: https://attendee.gotowebinar.com/registration.tmpl
And there is a enbedded  "Flash" see attach please

[Uploading site_source.zip…]()


another Problem with this URL: http://observer.viavisolutions.com/wireshark-week/webinars/simple-workflows-for-rapid-troubleshooting.php

got only 2,5MB but the video is a hour long or so...

**Comment by remitamine** [comment]
> got only 2,5MB but the video is a hour long or so...

http://players.brightcove.net/2797134697001/default_default/index.html?videoId=5231966653001

**Comment by ds2k5** [comment]
Thanks for the LINK
can you tell me how dow you find the LINK please ?
