### ISSUE TITLE
youtube-dl hangs after downloading first video

### ISSUE THREAD

**Issue by kirk86** [rg3/youtube-dl#11429]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.12**
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Dear all, I'm facing the following issue where the youtube-dl hangs after downloading only the first video file from a playlist.

Here is the command that I used:

```
youtube-dl -v -i --restrict-filenames -k -f "bestvideo[ext=mp4, height=480]" https://www.youtube.com/watch?v=2Op3QLzMgSY&list=PLE18841CABEA24090
[1] 47709
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-i', u'--restrict-filenames', u'-k', u'-f', u'bestvideo[ext=mp4, height=480]', u'https://www.youtube.com/watch?v=2Op3QLzMgSY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.12
[debug] Python version 2.7.12 - Darwin-16.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.4, ffprobe 3.1.4
[debug] Proxy map: {}
[youtube] wIq4CssPoO0: Downloading webpage
[youtube] wIq4CssPoO0: Downloading video info webpage
[youtube] wIq4CssPoO0: Extracting video information
[youtube] wIq4CssPoO0: Downloading MPD manifest
[debug] Invoking downloader on u'https://r6---sn-q0c7dn7l.googlevideo.com/videoplayback?id=c08ab80acb0fa0ed&itag=135&source=youtube&requiressl=yes&pl=16&ms=au&mm=31&mn=sn-q0c7dn7l&initcwndbps=698750&mv=m&ratebypass=yes&mime=video/mp4&gir=yes&clen=3066074&lmt=1474646862341616&dur=133.967&key=dg_yt0&upn=Zln8BQMfq94&mt=1481575923&signature=4A6C147DCC4D4B5E27B518B29EC558E387020A6D.01ACD723D74428CACB11826CF5DE5426146171AD&ip=143.239.81.123&ipbits=0&expire=1481597824&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,ms,mm,mn,initcwndbps,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] 1.1.1_Welcome_to_6.042-wIq4CssPoO0.mp4 has already been downloaded
[download] 100% of 2.92MiB
```

**Comment by dstftw** [comment]
You have to either put the URL into quotes or manually escape all the special shell characters. Read [FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for details.
