### ISSUE TITLE
Best way to download latest videos from a channel?

### ISSUE THREAD

**Issue by mfessi** [rg3/youtube-dl#11437]
Hello,

first of all - thank you for this awesome tool!

To automatical download all new videos from a channel i use the "--dateafter now-1day" switch.
But this means that every time all playlists and every single video informations* 
had du be downloaded before it checks that the upload date is in range or not.

*Downloading webpage, Downloading video info webpage, Extracting video information,  Downloading MPD manifest...

Is there any faster way to download only the latest video?

Thank you,
best regards

Martin

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#how-do-i-download-only-new-videos-from-a-playlist

**Comment by mfessi** [comment]
Thank you so much!

**Comment by mfessi** [comment]
@dstftw 
Thank you so much!
