### ISSUE TITLE
Dailymotion support seems broken

### ISSUE THREAD

**Issue by RomainBoulay** [rg3/youtube-dl#11438]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.12**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple 

```
WARNING: unable to extract comment count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl-2016.12.12-py2.7.egg/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python2.7/site-packages/youtube_dl-2016.12.12-py2.7.egg/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/usr/lib/python2.7/site-packages/youtube_dl-2016.12.12-py2.7.egg/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python2.7/site-packages/youtube_dl-2016.12.12-py2.7.egg/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/lib/python2.7/site-packages/youtube_dl-2016.12.12-py2.7.egg/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

```
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.12
[debug] Python version 2.7.12 - Linux-2.6.32.12-ppc-with-glibc2.0
[debug] exe versions: ffmpeg 2.7.1
[debug] Proxy map: {}
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

The downloading for any Dailymotion video seems broken, got HTTP Error 403 even though the videos were public. I believe you can reproduce the error with any link, regardless of the command line flags too.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by RomainBoulay** [comment]
Hey @dstftw,

I've reformatted my post, the bug still exists and I hope I gave all the needed info.

Cheers.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by RomainBoulay** [comment]
My bad. I've upgraded the software and updated this PR's description as the issues persist

**Comment by yan12125** [comment]
Works for me.
```
$ youtube-dl -v "http://www.dailymotion.com/video/x55kf8p_miss-france-miss-mayotte-elue-mis-gamelle-avec-une-chute-spectaculaire-en-gros-plan_tv"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.dailymotion.com/video/x55kf8p_miss-france-miss-mayotte-elue-mis-gamelle-avec-une-chute-spectaculaire-en-gros-plan_tv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.18
[debug] Git HEAD: 954529c10
[debug] Python version 2.7.12 - Linux-4.8.13-1-ARCH-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] x55kf8p: Downloading webpage
WARNING: unable to extract comment count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[dailymotion] x55kf8p: Downloading m3u8 information
[dailymotion] x55kf8p: Downloading m3u8 information
[dailymotion] x55kf8p: Downloading m3u8 information
[dailymotion] x55kf8p: Downloading m3u8 information
[debug] Invoking downloader on u'https://www.dailymotion.com/cdn/H264-512x384/video/x55kf8p.mp4?auth=1482293200-2562-yqnwls4j-07e7e9d4f70e50c4644fead3cd05e6d1'
[download] Destination: Miss France - Miss Mayotte élue... Mis Gamelle avec une chute spectaculaire en gros plan  !-x55kf8p.mp4
[download] 100% of 845.58KiB in 00:00
```

**Comment by RomainBoulay** [comment]
Ok I think I understood the issue. When a client is downloading several dailymotion videos, the website presents a login page that prevents `youtube-dl` to work normally.

I tried to workaround the issue using ```--username ... --password ...``` but that does not solve the issue. Any idea how one could make it work?

cheers

**Comment by yan12125** [comment]
Dailymotion authentication are not supported yet. You may want to open a new issue for that.

**Comment by RomainBoulay** [comment]
Thanks. I created another issue here: https://github.com/rg3/youtube-dl/issues/11491
