### ISSUE TITLE
Youtube Video not found BUG

### ISSUE THREAD

**Issue by Mondanzo** [rg3/youtube-dl#11435]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] Encodings: locale cp1252, fs mbcs, out UTF-8, pref cp1252
[debug] youtube-dl version 2016.12.12
[debug] Python version 3.5.1 - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg N-80052-g64fe1ee, ffprobe N-80052-g64fe1ee
[debug] Proxy map: {}
[youtube] haeqvlazgky: Downloading webpage
[youtube] haeqvlazgky: Downloading video info webpage
ERROR: haeqvlazgky: YouTube said: This video does not exist.
Traceback (most recent call last):
  File "C:\Dev Kram\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "C:\Dev Kram\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 357, in extract
    return self._real_extract(url)
  File "C:\Dev Kram\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1327, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: haeqvlazgky: YouTube said: This video does not exist.
<end of log>
```

---

### Description of your *issue*, suggested solution and other information
Randomly the Youtube Downloader couldn't download any songs from Youtube anymore,
Other Sites like Soundcloud are working but no video from Youtube.
The Videos are existing!
It could be an error because i tried to download from germany (Frankfurt).

**Comment by dstftw** [comment]
Video haeqvlazgky does not exist that is clearly stated in the error message and when trying to play it in browser.

**Comment by skarbs001** [comment]
I have same problem. Is there any solution this problem or What should I do for skipping this youtube url.
For example, https://www.youtube.com/watch?v=50NJtOZ5qO4
