### ISSUE TITLE
download video/audio but need audio in aac

### ISSUE THREAD

**Issue by vertex11** [rg3/youtube-dl#11431]
I want to download a video/audio from youtube using youtube-dl.  The file that is produced has an Opus audio which fails in my media player.  I want the audio in aac.  The downloaded video is fine.

How do I do this?

I tried:

youtube-dl --audio-format aac "URL"

But the downloaded file remains Opus audio, but I need aac

So, what syntax should I use?

**Comment by dstftw** [comment]
`-f bestaudio[ext=m4a]+bestvideo[ext=mp4]/best[ext=mp4]`.
