### ISSUE TITLE
the ina

### ISSUE THREAD

**Issue by leachong** [rg3/youtube-dl#1144]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.ina.fr/personnalites/bernard-hinault/']
[debug] youtube-dl version 2013.07.25.2
[debug] Python version 2.7.3 - Windows-7-6.1.7600
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
[generic] : Downloading webpage
[generic] : Extracting information
ERROR: Invalid URL: http://www.ina.fr/personnalites/bernard-hinault/; please report this issue on https://yt-dl.org/bug
. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 312, in extract_info
  File "youtube_dl\extractor\common.pyo", line 96, in extract
  File "youtube_dl\extractor\generic.pyo", line 148, in _real_extract
ExtractorError: Invalid URL: http://www.ina.fr/personnalites/bernard-hinault/; please report this issue on https://yt-dl
.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Continued in #24756.
