### ISSUE TITLE
support for facebookcorewwwi.onion (facebook on tor network)

### ISSUE THREAD

**Issue by affinityv** [rg3/youtube-dl#11443]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v --proxy http://127.0.0.1:8118  https://www.facebookcorewwwi.onion/dailypicksandflicks/videos/1050912691595461/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--proxy', u'http://127.0.0.1:8118', u'https://www.facebookcorewwwi.onion/dailypicksandflicks/videos/1050912691595461/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.12
[debug] Python version 2.7.12 - Linux-4.4.0-53-generic-x86_64-with-LinuxMint-18-sarah
[debug] exe versions: avconv 2.8.8-0ubuntu0.16.04.1, avprobe 2.8.8-0ubuntu0.16.04.1, ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1
[debug] Proxy map: {u'http': u'http://127.0.0.1:8118', u'https': u'http://127.0.0.1:8118'}
[generic] 1050912691595461: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1050912691595461: Downloading webpage
[generic] 1050912691595461: Extracting information
[redirect] Following redirect to https://www.facebookcorewwwi.onion/dailypicksandflicks/videos/1050912691595461/?_fb_noscript=1
[generic] ?_fb_noscript=1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?_fb_noscript=1: Downloading webpage
[generic] ?_fb_noscript=1: Extracting information
ERROR: Unsupported URL: https://www.facebookcorewwwi.onion/dailypicksandflicks/videos/1050912691595461/?_fb_noscript=1
Traceback (most recent call last):
  File "/home/andrewm/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1626, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/andrewm/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/andrewm/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: duplicate attribute: line 11, column 38820
Traceback (most recent call last):
  File "/home/andrewm/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/andrewm/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/home/andrewm/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2433, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.facebookcorewwwi.onion/dailypicksandflicks/videos/1050912691595461/?_fb_noscript=1


```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video:  https://www.facebookcorewwwi.onion/dailypicksandflicks/videos/1050912691595461/

---

### Description of your *issue*, suggested solution and other information

If the URL domain is changed from facebookcorewwwi.onion to facebook.com ... then it works, but I would prefer to be able to use either option and better to use facebook.com processing via the .onion address only when it is given.

**Comment by yan12125** [comment]
Thanks for the example link. It will be supported in the next version:
```
$ youtube-dl -v "https://www.facebookcorewwwi.onion/dailypicksandflicks/videos/1050912691595461/" --proxy socks5://127.0.0.1:9050/ 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.facebookcorewwwi.onion/dailypicksandflicks/videos/1050912691595461/', '--proxy', 'socks5://127.0.0.1:9050/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.12
[debug] Git HEAD: 30918999f
[debug] Python version 3.5.2 - Linux-4.8.13-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {'https': 'socks5://127.0.0.1:9050/', 'http': 'socks5://127.0.0.1:9050/'}
[facebook] 1050912691595461: Downloading webpage
[facebook] 1050912691595461: Downloading webpage
[debug] Invoking downloader on 'https://video-yyz1-1.xx.fbcdn.net/v/t42.1790-2/12492846_1579763975612266_1900617615_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfMTI4MF9jcmZfMjdfaGlnaF8zLjFfZnJhZ18yX3ZpZGVvIn0=&oh=bdfebb8c96bf948a4dbe69d079bb54e4&oe=5851AABD'
[download] Destination: Geese Parade-1050912691595461.f1579763972278933v.mp4
[download] 100% of 4.09MiB in 00:48
[debug] Invoking downloader on 'https://video-yyz1-1.xx.fbcdn.net/v/t42.1790-2/12483936_1509361779394645_1582810494_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfMjU2X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfYXVkaW8ifQ==&oh=9e7277cfe954b07cf087a13a0a6c6361&oe=5851ADEA'
[download] Destination: Geese Parade-1050912691595461.f1509361776061312ad.m4a
[download] 100% of 67.82KiB in 00:01
[ffmpeg] Merging formats into "Geese Parade-1050912691595461.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Geese Parade-1050912691595461.f1579763972278933v.mp4' -i 'file:Geese Parade-1050912691595461.f1509361776061312ad.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Geese Parade-1050912691595461.temp.mp4'
Deleting original file Geese Parade-1050912691595461.f1579763972278933v.mp4 (pass -k to keep)
Deleting original file Geese Parade-1050912691595461.f1509361776061312ad.m4a (pass -k to keep)
```

**Comment by affinityv** [comment]
Please use the .onion address for downloads, especially when .netrc is used; if the URL passed to youtube-dl is a dot onion address, keep it using the dot onion address and don't revert to the standard facebook.com address -- doing a revert causes fb to force password changes due to an account compromise that has not occurred.

**Comment by affinityv** [comment]
bump

**Comment by affinityv** [comment]
This still causes problems with FB when using a facebookcorewwwi.onion address for the video download.  A clearnet login process is used even though FB believes the IP address is foreign -- then FB forces you to change the password even when you tell them it was you.  You need to login to www.facebookcorewwwi.onion and not www.facebook.com ... and using .netrc

I DO NOT EVER WANT TO LOGIN USING THE www.facebook.com DOMAIN NAME, but we need to login for videos that require a login.
