### ISSUE TITLE
How to get youtube-dl.exe for win32 of pac-support?

### ISSUE THREAD

**Issue by winways** [rg3/youtube-dl#11445]
how to get youtube-dl.exe of pac-support?
I have already built pacparser.dll and got pacparser pymod.(I can import pacparser and use it's member functions)
I run setup.py within IDLE but got nothing and no any exception except some user warnings.(with VC++2008 installed)
It is to say that try to change py to exe,isnt it?
```
try:
    # This will create an exe that needs Microsoft Visual C++ 2008
    # Redistributable Package
    import py2exe
except ImportError:
    if len(sys.argv) >= 2 and sys.argv[1] == 'py2exe':
        print("Cannot import py2exe", file=sys.stderr)
        exit(1)
```
Could you give me a tip?Thanks a lot.

**Comment by yan12125** [comment]
Use this command to build a binary:
```
python setup.py py2exe
```
