### ISSUE TITLE
Issue when using the output option

### ISSUE THREAD

**Issue by JunkyardCat** [rg3/youtube-dl#11453]
Im using windows 7 and encounters an issue when using the output option

here is my code:
`youtube-dl --download-archive archive.log --add-metadata -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio --merge-output-format mkv --all-subs --embed-subs -i --embed-thumbnail --output "%(uploader)s\%(title)s.%(ext)s" "http://www.youtube.com/watch?v=P9pzm5b6FFY"
`
pause

here is the error message i get
F:\Videos\Youtube-DL\Tools>youtube-dl --download-archive archive.log --add-metad
ata -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio --merge-output-
format mkv --all-subs --embed-subs -i --embed-thumbnail --output "(title)s.//www
.youtube.com/watch?v=P9pzm5b6FFY"
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

F:\Videos\Youtube-DL\Tools>pause
Press any key to continue . . .

i tried removing all other option but issue still persists

`youtube-dl --output "%(uploader)s\%(title)s.%(ext)s" "http://www.youtube.com/watch?v=P9pzm5b6FFY"`

pause

here is the error message

F:\Videos\Youtube-DL\Tools>youtube-dl --output "(title)s.//www.youtube.com/watch
?v=P9pzm5b6FFY"
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

F:\Videos\Youtube-DL\Tools>pause
Press any key to continue . . .

**Comment by dstftw** [comment]
>F:\Videos\Youtube-DL\Tools>youtube-dl --download-archive archive.log --add-metad
ata -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio --merge-output-
format mkv --all-subs --embed-subs -i --embed-thumbnail --output "(title)s.//www
.youtube.com/watch?v=P9pzm5b6FFY"
Usage: youtube-dl [OPTIONS] URL [URL...]

You didn't provide any URL and your output template is invalid.

If you'are using it in batch script read [this](https://github.com/rg3/youtube-dl#output-template-and-windows-batch-files).

**Comment by JunkyardCat** [comment]
Thanks that worked man
