### ISSUE TITLE
Feature Request: After downloading Youtube video, mark it as "Watched" in Youtube.com

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#11454]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.15**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

- [X] Feature request (request for a new functionality)
---

### Description of your *issue*, suggested solution and other information

After I download a Youtube video, I would like to option to let Youtube know that I've watched the video. I realize this means giving youtube-dl my google account credentials. Perhaps there are other youtube-dl  users who also would like to have this option.

This is in the same vein as https://github.com/rg3/youtube-dl/issues/9733 ("Feature Request - Remove Videos from YouTube Playlist after Download")

**Comment by yan12125** [comment]
Yes there's an option: ```--mark-watched```

**Comment by hub2git** [comment]
Yan, thank you so much! Is there a way to have "--mark-watched" as the default setting? In other words, is there a way to have `youtube-dl http://youtube.com/somevideo` to automatically downloaded as though it had the `--mark-watched` option attached?

**Comment by yan12125** [comment]
Configuration files should fit your need: https://github.com/rg3/youtube-dl/blob/master/README.md#configuration

**Comment by hub2git** [comment]
Thanks, Yan! That link helped.
