### ISSUE TITLE
[Site support request]: www.thedrive.com

### ISSUE THREAD

**Issue by crgmrgn** [rg3/youtube-dl#11459]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.thedrive.com/video/6531/we-gave-spike-feresten-a-ferrari-488-spider-and-a-mclaren-570gt
- Single video: http://www.thedrive.com/muscle-cars/6254/car-porn-porsche-917-gulf

---

### Description of your *issue*, suggested solution and other information

Website "thedrive.com" videos are not recognised, further suitable instances are listed at http://www.thedrive.com/video, I've plucked two suitable direct video URLs out for the example above, site doesn't seem to provide playlist functionality.

Embedded player seems to be the Brightcove v5.11.4 player.

**Comment by remitamine** [comment]
```
youtube-dl http://www.thedrive.com/video/6531/we-gave-spike-feresten-a-ferrari-488-spider-and-a-mclaren-570gt
[generic] we-gave-spike-feresten-a-ferrari-488-spider-and-a-mclaren-570gt: Requesting header
WARNING: Falling back on generic information extractor.
[generic] we-gave-spike-feresten-a-ferrari-488-spider-and-a-mclaren-570gt: Downloading webpage
[generic] we-gave-spike-feresten-a-ferrari-488-spider-and-a-mclaren-570gt: Extracting information
[generic] 5249496318001: Checking possible brightcove video URL
[download] Downloading playlist: We Gave Spike Feresten a Ferrari 488 Spider and a McLaren 570GT
[generic] playlist We Gave Spike Feresten a Ferrari 488 Spider and a McLaren 570GT: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5249496318001: Downloading webpage
[brightcove:new] 5249496318001: Downloading JSON metadata
[brightcove:new] 5249496318001: Downloading m3u8 information
[brightcove:new] 5249496318001: Downloading m3u8 information
[download] Destination: We Gave Spike Feresten a Ferrari 488 Spider and a McLaren 570GT-5249496318001.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2  154M    2 4043k    0     0   559k      0  0:04:42  0:00:07  0:04:35  829k
```
```
youtube-dl http://www.thedrive.com/muscle-cars/6254/car-porn-porsche-917-gulf
[generic] car-porn-porsche-917-gulf: Requesting header
WARNING: Falling back on generic information extractor.
[generic] car-porn-porsche-917-gulf: Downloading webpage
[generic] car-porn-porsche-917-gulf: Extracting information
[generic] 5229555225001: Checking possible brightcove video URL
[download] Downloading playlist: Car Porn: Porsche 917 Gulf
[generic] playlist Car Porn: Porsche 917 Gulf: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5229555225001: Downloading webpage
[brightcove:new] 5229555225001: Downloading JSON metadata
[brightcove:new] 5229555225001: Downloading m3u8 information
[brightcove:new] 5229555225001: Downloading m3u8 information
[download] Destination: Car Porn - Porsche 917 Gulf-5229555225001.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.8M  100 18.8M    0     0   760k      0  0:00:25  0:00:25 --:--:--  838k
```
