### ISSUE TITLE
Site stopped working

### ISSUE THREAD

**Issue by seojoohyun** [rg3/youtube-dl#11455]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.dramalove.tv/drama/weightlifting-fairy-kim-bok-joo/wfkbj-episode-1/
---

### Description of your *issue*, suggested solution and other information

I was able to download from the www.dramalove.tv site up until yesterday, today using the same version that had previously worked I get Unsupported URL error. Updated to latest version, no difference.
```
ytdl -v http://www.dramalove.tv/drama/weightlifting-fairy-kim-bok-joo/wfkbj-episode-1/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.dramalove.tv/drama/weightlifting-fairy-kim-bok-joo/wfkbj-episode-1/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.15
[debug] Python version 2.7.6 - Linux-3.13.0-52-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[generic] wfkbj-episode-1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] wfkbj-episode-1: Downloading webpage
[generic] wfkbj-episode-1: Extracting information
ERROR: Unsupported URL: http://www.dramalove.tv/drama/weightlifting-fairy-kim-bok-joo/wfkbj-episode-1/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1626, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 65, column 12
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2433, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.dramalove.tv/drama/weightlifting-fairy-kim-bok-joo/wfkbj-episode-1/
```

**Comment by seojoohyun** [comment]
Okay, the whole site seems to be gone now.. all I get is a 404 error. I guess we can forget this one.

**Comment by yan12125** [comment]
OK feel free to open a new issue if the site is back.
