### ISSUE TITLE
can't download a specific youtube video, got server HTTP error. 

### ISSUE THREAD

**Issue by inhahe** [rg3/youtube-dl#11463]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```


[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-x', '-v', 'https://www.youtube.com/watch?v=DOkx_zPW4k4']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.12.15
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-76123-g002b049, ffprobe N-76123-g002b049
[debug] Proxy map: {}
[youtube] DOkx_zPW4k4: Downloading webpage
[youtube] DOkx_zPW4k4: Downloading video info webpage
[youtube] DOkx_zPW4k4: Extracting video information
[youtube] {22} signature length 42.38, html5 player en_US-vfljAVcXG
[youtube] {43} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {18} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {36} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {17} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {137} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {248} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {136} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {247} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {135} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {244} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {134} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {243} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {133} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {242} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {160} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {278} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {140} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {171} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {249} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {250} signature length 42.40, html5 player en_US-vfljAVcXG
[youtube] {251} signature length 42.40, html5 player en_US-vfljAVcXG
[debug] Invoking downloader on 'https://r4---sn-hp57kn7z.googlevideo.com/videoplayback?source=youtube&mime=audio%2Fwebm&pl=52&id=o-ADdDu6iaxxIGdt27txtoW4xi-mS2Z
UHiSRiNUJndcxpO&key=yt6&expire=1481938897&nh=IgpwcjAxLm1pYTA0KgkxMjcuMC4wLjE&ei=cENUWOimOMPZ-wXplKnYAg&itag=251&mv=m&sparams=aol%2Cclen%2Cdur%2Cei%2Cgcr%2Cgir%2
Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ms=au&mt=1481917065&dur=249.1
01&aol=yes&clen=4209518&ip=2602%3A306%3Acf64%3Aaf20%3Afc6d%3A3188%3A42f7%3Aa157&initcwndbps=6250000&gir=yes&mm=31&ipbits=0&mn=sn-hp57kn7z&lmt=1442961060937893&g
cr=us&upn=H-PQA7Pv9bA&requiressl=yes&keepalive=yes&signature=2B1FA2B3E579654F9DEC0110F5A89A9D59902423.7D09B1A7513FF5B3ADDEFF1D6F18427AAB7AD5CC&ratebypass=yes'
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpeuo2y5u2\build\youtube_dl\__init__.py", line 444, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpeuo2y5u2\build\youtube_dl\__init__.py", line 434, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpeuo2y5u2\build\youtube_dl\YoutubeDL.py", line 1791, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpeuo2y5u2\build\youtube_dl\YoutubeDL.py", line 705, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpeuo2y5u2\build\youtube_dl\YoutubeDL.py", line 751, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpeuo2y5u2\build\youtube_dl\YoutubeDL.py", line 1435, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpeuo2y5u2\build\youtube_dl\YoutubeDL.py", line 1699, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpeuo2y5u2\build\youtube_dl\YoutubeDL.py", line 1641, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpeuo2y5u2\build\youtube_dl\downloader\common.py", line 353, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpeuo2y5u2\build\youtube_dl\downloader\http.py", line 131, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpeuo2y5u2\build\youtube_dl\downloader\common.py", line 162, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpeuo2y5u2\build\youtube_dl\YoutubeDL.py", line 568, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpeuo2y5u2\build\youtube_dl\YoutubeDL.py", line 530, in trouble
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

I'm using the Windows exe version of youtube-dl (2016.12.15). I get the error "Got server HTTP error" whenever I try to download the a specific video, https://www.youtube.com/watch?v=DOkx_zPW4k4 . All other YouTube videos (I've been downloading dozens and dozens over the past few days) work fine (except one other one had a slight glitch, it couldn't retrieve the name of the account that posted the video for some reason, but that one still downloaded), including videos I downloaded after I attempted downloading this one. 

The URL opens and plays just fine in the browser (Chrome).

In actuality I haven't been downloading videos, I've been downloading the audio from videos by using -x, which I also passed as a parameter when trying the above URL as you can see in the debug info.

**Comment by Ectomind1990** [comment]
I think there's something unusual about that [DOkx_zPW4k4](https://www.youtube.com/watch?v=DOkx_zPW4k4) video.  When I go to it now in Firefox I see `This video is not available.   Sorry about that.`

Normally when a video has been deleted or made private, I **can't** see anything else about it.  I just get a fairly minimal You Tube page with the error message.  But on this video page I **can** see everything except the video itself.  I can see the video title, the channel it's on, and "Published on Sep 24, 2015".  The Subscribe and Like/Dislike buttons are present. and so is the "Up next" panel on the right.

I don't remember ever seeing this combination of symptoms.

**Comment by yan12125** [comment]
Yep seems there's a bug in YouTube. Anyway a feature request in #3721 may be useful
