### ISSUE TITLE
problem with this url : http://www.vh1.com/full-episodes/cqxu0a/americas-next-top-model-business-brand-boss-season-23-ep-2301

### ISSUE THREAD

**Issue by theennev** [rg3/youtube-dl#11464]
getting : 
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/cqxu0a/americas-next-top-model-business-brand-boss-season-23-ep-2301

Thanks for the great work !

**Comment by yan12125** [comment]
It says: "SORRY, THIS VIDEO IS UNAVAILABLE". See also #9613 for previous discussions.
