### ISSUE TITLE
Feature request: select best for a given container

### ISSUE THREAD

**Issue by videonerd** [rg3/youtube-dl#11479]
The current behaviour for bestaudio+bestvideo is format agnostic and therefore many youtube videos are merged as mkv (mp4+vorbis). It would be good to be able to download the best for a given container e.g. webm - download vp9+vorbis or similarly for mp4 - mp4+aac

Thank you!

**Comment by dstftw** [comment]
It's already possible, read [FAQ](https://github.com/rg3/youtube-dl#format-selection).
