### ISSUE TITLE
[Vimeo] No download of 2K/4K format (at least via HTTP)

### ISSUE THREAD

**Issue by basicmaster** [rg3/youtube-dl#11490]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl -F -v https://vimeo.com/130032076
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'-v', u'https://vimeo.com/130032076']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.18
[debug] Python version 2.7.6 - Linux-4.4.0-53-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 130032076: Downloading webpage
[vimeo] 130032076: Extracting information
[vimeo] 130032076: Downloading webpage
[vimeo] 130032076: Downloading JSON metadata
[info] Available formats for 130032076:
format code  extension  resolution note
http-360p    mp4        640x268    25fps
http-720p    mp4        1280x536   25fps
http-1080p   mp4        1920x804   25fps (best)
```

### Description of your *issue*, suggested solution and other information

The mentioned video is in 4K can be played at Vimeo in this five resolutions:
* 360p / 720p / 1080p / 2K / 4K

However youtube-dl only offers:
* 360p / 720p / 1080p

Looking into the [player source](https://player.vimeo.com/video/130032076) (view e.g. in [JS Beautifier](http://jsbeautifier.org/)) it turns out that via HTTP indeed only these three resolutions are available. The complete five ones are only available via MPEG-DASH or HLS.

So the Vimeo extractor should be modified to also take MPEG-DASH and/or HLS formats into account (or perhaps completely switch to one of these).

**Comment by Hrxn** [comment]
Did Vimeo changed their site recently?

Because downloading via HLS definitely worked before, don't know why it isn't listed in the format list above.

**Comment by basicmaster** [comment]
Thank you for fixing this so fast!
