### ISSUE TITLE
Download from Pluzz fails with latest version, ok with 2016.12.01

### ISSUE THREAD

**Issue by dwyart** [rg3/youtube-dl#11507]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.20*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ ~/youtube-dl/youtube-dl -v "http://pluzz.francetv.fr/videos/le_monde_de_jamy_,150486050.html"
[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg']
[debug] Command-line args: [u'-v', u'http://pluzz.francetv.fr/videos/le_monde_de_jamy_,150486050.html']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2016.12.20
[debug] Python version 2.7.13 - Linux-4.9.0-rc8-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 3.2.2, avprobe 3.2.2, ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[pluzz.francetv.fr] le_monde_de_jamy_,150486050: Downloading webpage
[pluzz.francetv.fr] 150486050: Downloading video JSON
[pluzz.francetv.fr] 150486050: Downloading geo restriction info
[pluzz.francetv.fr] 150486050: Downloading m3u8 information
[pluzz.francetv.fr] 150486050: Downloading m3u8 information
ERROR: Both formats hls_v5_os-1467 and hls_v5_os-189 are video-only, you must specify "-f video+audio"
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/dw/youtube-dl/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/home/dw/youtube-dl/youtube-dl/youtube_dl/__init__.py", line 444, in main
    _real_main(argv)
  File "/home/dw/youtube-dl/youtube-dl/youtube_dl/__init__.py", line 434, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/dw/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/dw/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 705, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/dw/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 751, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/dw/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 1424, in process_video_result
    formats_to_download = list(format_selector(ctx))
  File "/home/dw/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 1069, in selector_function
    for format in f(ctx):
  File "/home/dw/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 1188, in final_selector
    return selector_function(ctx_copy)
  File "/home/dw/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 1079, in selector_function
    picked_formats = list(f(ctx))
  File "/home/dw/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 1180, in selector_function
    yield _merge(pair)
  File "/home/dw/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 1152, in _merge
    % (format_1, format_2))
  File "/home/dw/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 568, in report_error
    self.trouble(error_message, tb)
  File "/home/dw/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 530, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

For comparison, here is the same output with version 2016.12.01:
```
$ youtube-dl -v "http://pluzz.francetv.fr/videos/le_monde_de_jamy_,150486050.html"
[debug] System config: []
[debug] User config: ['--prefer-ffmpeg']
[debug] Command-line args: ['-v', 'http://pluzz.francetv.fr/videos/le_monde_de_jamy_,150486050.html']
[debug] Encodings: locale ISO-8859-1, fs iso8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.5.2+ - Linux-4.9.0-rc8-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[pluzz.francetv.fr] le_monde_de_jamy_,150486050: Downloading webpage
[pluzz.francetv.fr] 150486050: Downloading video JSON
[pluzz.francetv.fr] 150486050: Downloading geo restriction info
[pluzz.francetv.fr] 150486050: Downloading m3u8 information
[pluzz.francetv.fr] 150486050: Downloading m3u8 information
[debug] Invoking downloader on 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif_france-dom-tom/2016/S51/J3/150486050-585afa909ff3f-,standard1,standard2,standard3,standard4,standard5,qad,.mp4.csmil/index_4_av.m3u8?null=0'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 677
[download] Destination: Le monde de Jamy - Feux d'artifice, cirques, parcs d'attractions  - des étoiles plein les yeux !-150486050.mp4
[download]   0.0% of ~1.24GiB at 203.91KiB/s ETA 02:23:21^C
ERROR: Interrupted by user
```
---
---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

As seen on the two previous logs, there seems to be a regression on the pluzz.fr site.

Thanks in advance for your help.

**Comment by dwyart** [comment]
I do not know if this is related or not, but the logs show that the first invocation is using python2.7 while the other is using python3.5. The handling of options also looks different in the two cases.
The first case is a clone of the repo with "make youtube-dl" while the other is a Debian package.

**Comment by remitamine** [comment]
Thanks for the report, it should be fixed in the next version.
