### ISSUE TITLE
How to get mp4 address from youku.com?

### ISSUE THREAD

**Issue by CoXier** [rg3/youtube-dl#11512]
## Why mp4?
I am a android developer and recently I want to play some videos from www.youku.com, however I can only use `webview` to show it.In order to show video on android native video player, I have to get [mp4 address].

## What I found?
In the youtube_dl/extractor,I found `youku.py`. But I am strange to python.So I want to ask you how to get mp4 address from youku.com?

Thank you very much.

**Comment by dstftw** [comment]
`-f best[ext=mp4]`.

**Comment by CoXier** [comment]
Yes,it does dowload files as mp4 format.But I want to know the address and skip dowload.

**Comment by yan12125** [comment]
Use -g to get URL(s)
