### ISSUE TITLE
long time with ipv6

### ISSUE THREAD

**Issue by TuxNuX** [rg3/youtube-dl#11516]
my config
Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
youtube-dl version 2016.12.22
Python version 2.7.9 - Linux-4.4.36-desktop-2.mga5-x86_64-with-mandrake-5-Official
exe versions: ffmpeg 3.1.3, ffprobe 3.1.3, rtmpdump 2.4

for exemple
youtube-dl -F https://www.youtube.com/watch?v=_VgjyM2NmhI

Takes several minutes for downloading
[youtube] _VgjyM2NmhI: Downloading webpage
[youtube] _VgjyM2NmhI: Downloading video info webpage
[youtube] _VgjyM2NmhI: Extracting video information
[youtube] _VgjyM2NmhI: Downloading MPD manifest

If I use
youtube-dl -F --force-ipv4 https://www.youtube.com/watch?v=_VgjyM2NmhI

good work Just a few seconds

I added in /etc/youtube-dl.conf
--force-ipv4
And now work well

I never had this problem before
Recent problem with latest updates

**Comment by yan12125** [comment]
There are no recent changes in IPv4/IPv6 handling. Most likely your system or network environment is changed. If you've just updated kernel or Python, that's possibly the cause. To check what's wrong with IPv6, tools like ```strace```, ```wireshark``` and ```traceroute``` are useful.
