### ISSUE TITLE
Site support request : anime and drama

### ISSUE THREAD

**Issue by nghiemvien** [rg3/youtube-dl#11511]
Please support anime site, drama site 

http://kissanime.ru/
http://kissasian.com/
http://ww1.gogoanime.io/

**Comment by Starsam80** [comment]
https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
