### ISSUE TITLE
[resolution] - How to show only resolutions

### ISSUE THREAD

**Issue by pishiii9** [rg3/youtube-dl#11527]
I am trying to show only resolutions like in the screenshot is it possible? if yes , then how?
![screenshot_14](https://cloud.githubusercontent.com/assets/24755635/21468088/0e9fcf6e-ca25-11e6-9fd9-cdbc907b458f.png)

**Comment by yan12125** [comment]
You'll need to use API. See https://github.com/rg3/youtube-dl#embedding-youtube-dl for a reference.

**Comment by yan12125** [comment]
You'll need to write some Python scripts first and then call them from PHP.

**Comment by pishiii9** [comment]
$cmd_image = 'youtube-dl --get-thumbnail '. escapeshellarg($url);
      $process_img = shell_exec($cmd_image);
      echo $process_img;
      $cmd = 'youtube-dl --get-title '. escapeshellarg($url);
      $title = shell_exec($cmd);
      echo $title;

I could print the thumbnail and title on my webpage. The only problem is with formats .. Help me to overcome this issue.

**Comment by yan12125** [comment]
Only resolutions does not provide much sense, so youtube-dl does not provide it. If you really need it, use the python API:
```
$ python -c "
import youtube_dl

with youtube_dl.YoutubeDL({'quiet': True}) as ydl:
    info = ydl.extract_info('https://www.youtube.com/watch?v=HxIct0i-CcA', download=False)
    for i in info['formats']:
        if i['vcodec'] != 'none':
            print('{0}x{1}'.format(i['width'], i['height']))
"
256x144
256x144
426x240
426x240
640x360
640x360
854x480
854x480
1280x720
1280x720
1920x1080
1920x1080
176x144
320x180
640x360
640x360
1280x720
```

**Comment by pishiii9** [comment]
Hello @yan12125  Can't i take the data from --dump-json using PHP only and then show resolutions from there?

**Comment by yan12125** [comment]
Apparently you already know another way to do it ;)

**Comment by pishiii9** [comment]
@yan12125  I am trying to get the exact  formats "(multiple - Quality Selection URL)" Like in the screenshot but i got only the below formats. Can you help me with that?
Please Do it with json and php. Or you can call @phihag  .

**Comment by yan12125** [comment]
```php
$data = json_decode(`youtube-dl -j test:cctv`, true);
foreach($data['formats'] as $f)
{
    print $f['format'] . "\n";
}
```
The result is:
```
meta - multiple (Quality selection URL)
204 - 320x180
460 - 480x270
870 - 640x360
1228 - 1280x720
2048 - 1280x720
```

**Comment by pishiii9** [comment]
I am getting the ERR  when i try to download from Adult websites .. Here is the result i get using "youtube-dl -v [URL] " command. 

Can you help me with that?
By the way my ISP has blocked Adult websites.
![screenshot_21](https://cloud.githubusercontent.com/assets/24755635/21609382/eafd8760-d1e3-11e6-8dd9-a3cdac69589a.png)

**Comment by yan12125** [comment]
> By the way my ISP has blocked Adult websites.

youtube-dl can't escape ISP restrictions automatically. If you can watch them with proxies or VPNs, add ```--proxy``` to the command line.
