### ISSUE TITLE
Twitch.tv chat log download

### ISSUE THREAD

**Issue by Rosuav** [rg3/youtube-dl#11524]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

Twitch.tv now records the (text) chat alongside videos. I would like to be able to download a video and have the chat as some form of associated download - maybe subtitles or other annotations. A couple of examples:

https://www.twitch.tv/cookingfornoobs/v/83226931 - a short clip (made by the broadcaster; clips made by viewers don't have associated chat)
https://www.twitch.tv/lilbumblebear/v/109190561 - a full-length VOD (will eventually expire, presumably making this a dead link)

Chat emotes might be a bit problematic. I'm okay with them being included either way - in their textual form ("noobsLove"), or as links (https://static-cdn.jtvnw.net/emoticons/v1/109023/1.0).

**Comment by Rosuav** [comment]
Wow! You are *FAST*! Thank you!

Emotes come out in their text form ("noobsLove") and in a mapping {"77681":[[0,9]]}. I've no idea what that part means, but I can run with the text. Much appreciated!

**Comment by Gorrrg** [comment]
So how do I get the chat now?

**Comment by yan12125** [comment]
@Gorrrg Chat messages are available as subtitles. See https://github.com/rg3/youtube-dl/blob/master/README.md#subtitle-options

**Comment by Gorrrg** [comment]
Ah, I tried that out. But it seems it only download the first few messages. I remember something about the Twitch API only offering 5 second chunks of chat messages per request.

**Comment by yan12125** [comment]
Could you open a new issue for incomplete messages?

**Comment by Gorrrg** [comment]
Yep, I will.
