### ISSUE TITLE
Please add support to www.veyqo.net/ (Use OpenLoad)

### ISSUE THREAD

**Issue by ibrahimovic1** [rg3/youtube-dl#11536]
I use the newest version and unfortunately found out this is not on the support list. 

The website have clean interface and navigate mainly by the pages down below. It actually just grab videos from Openload (which already supported) but it would be great if youtube-dl could download it all automatically like how downloading a playlist works in Youtube. 

The video pick better quality videos into one website so please consider adding it :)

[VEYQO](http://veyqo.net/) @

**Comment by yan12125** [comment]
Please paste a concrete video URL instead of the main page's.

**Comment by ibrahimovic1** [comment]
Hi, thank you for looking at this. This is my first time so bear with me :)

**URL** - http://www.veyqo.net/rkprime-aidra-fox-get-closet-24-12-2016/


**This is the command I use for the error to appear** (XXX is my directory location)
C:\XXX>youtube-dl -f 18 "http://www.veyqo.net/rkprime-aidra-fox-get-closet-24-12-2016/" --ignore-errors
[generic] rkprime-aidra-fox-get-closet-24-12-2016: Requesting header
WARNING: Falling back on generic information extractor.
[generic] rkprime-aidra-fox-get-closet-24-12-2016: Downloading webpage
[generic] rkprime-aidra-fox-get-closet-24-12-2016: Extracting information
ERROR: Unsupported URL: http://www.veyqo.net/rkprime-aidra-fox-get-closet-24-12-2016/

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.
