### ISSUE TITLE
can't dowload from dailymotion.com and from replay.gulli.fr

### ISSUE THREAD

**Issue by Sab1703** [rg3/youtube-dl#11539]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.22**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.12.22
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

utilisateur@utilisateur-Aspire-5738:~$ youtube-dl -v utilisateur@utilisateur-Aspire-5738:~$ youtube-dl --verbose http://www.dailymotion.com/video/x3jgfyn_south-park-saison-8-maternelle_shortfilms

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'utilisateur@utilisateur-Aspire-5738:~$', u'youtube-dl', u'--verbose', u'http://www.dailymotion.com/video/x3jgfyn_south-park-saison-8-maternelle_shortfilms']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.22
[debug] Python version 2.7.12 - Linux-4.4.0-57-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.10-0ubuntu0.16.04.1, ffprobe 2.8.10-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: u'utilisateur@utilisateur-Aspire-5738:~$' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:utilisateur@utilisateur-Aspire-5738:~$" ) to search YouTube
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 358, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1531, in _real_extract
    % (url, url), expected=True)
ExtractorError: u'utilisateur@utilisateur-Aspire-5738:~$' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:utilisateur@utilisateur-Aspire-5738:~$" ) to search YouTube

utilisateur@utilisateur-Aspire-5738:~$ [debug] System config: []
[debug] : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$ [debug] User config: []
[debug] : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$ [debug] Command-line args: [u'--verbose', u'http://www.dailymotion.com/video/x3jgfyn_south-park-saison-8-maternelle_shortfilms']
[debug] : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$ [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$ [debug] youtube-dl version 2016.02.22
[debug] : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$ [debug] Python version 2.7.12 - Linux-4.4.0-57-generic-i686-with-Ubuntu-16.04-xenial
[debug] : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$ [debug] exe versions: ffmpeg 2.8.10-0ubuntu0.16.04.1, ffprobe 2.8.10-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$ [debug] Proxy map: {}
[debug] : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$ [dailymotion] x3jgfyn: Downloading webpage
[dailymotion] : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$ WARNING: unable to extract comment count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: : commande introuvable
please : commande introuvable
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%{ <-- HERE (.*?)}/ at /usr/bin/see line 528.
Error: no such file ":https://yt-dl.org/update"
Error: no such file "on"
Error: no such file "how"
Error: no such file "to"
Error: no such file "update."
Error: no such file "Be"
Error: no such file "sure"
Error: no such file "to"
Error: no such file "call"
Error: no such file "youtube-dl"
Error: no such file "with"
Error: no such file "the"
Error: no such file "flag"
Error: no such file "and"
Error: no such file "include"
Error: no such file "its"
Error: no such file "complete"
Error: no such file "output."
utilisateur@utilisateur-Aspire-5738:~$ [dailymotion] x3jgfyn: Downloading embed page
[dailymotion] : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$ ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: : commande introuvable
please : commande introuvable
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%{ <-- HERE (.*?)}/ at /usr/bin/see line 528.
Error: no such file ":https://yt-dl.org/update"
Error: no such file "on"
Error: no such file "how"
Error: no such file "to"
Error: no such file "update."
Error: no such file "Be"
Error: no such file "sure"
Error: no such file "to"
Error: no such file "call"
Error: no such file "youtube-dl"
Error: no such file "with"
Error: no such file "the"
Error: no such file "flag"
Error: no such file "and"
Error: no such file "include"
Error: no such file "its"
Error: no such file "complete"
Error: no such file "output."
utilisateur@utilisateur-Aspire-5738:~$ Traceback (most recent call last):
bash: erreur de syntaxe près du symbole inattendu « most »
utilisateur@utilisateur-Aspire-5738:~$   File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
La commande « File » est introuvable, vouliez-vous dire :
 La commande « zile » du paquet « zile » (universe)
 La commande « kile » du paquet « kile » (universe)
 La commande « file » du paquet « file » (main)
 La commande « vile » du paquet « vile » (universe)
File : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$     ie_result = ie.extract(url)
bash: erreur de syntaxe près du symbole inattendu « ( »
utilisateur@utilisateur-Aspire-5738:~$   File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 316, in extract
La commande « File » est introuvable, vouliez-vous dire :
 La commande « kile » du paquet « kile » (universe)
 La commande « file » du paquet « file » (main)
 La commande « vile » du paquet « vile » (universe)
 La commande « zile » du paquet « zile » (universe)
File : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$     return self._real_extract(url)
bash: erreur de syntaxe près du symbole inattendu « ( »
utilisateur@utilisateur-Aspire-5738:~$   File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/dailymotion.py", line 228, in _real_extract
La commande « File » est introuvable, vouliez-vous dire :
 La commande « kile » du paquet « kile » (universe)
 La commande « vile » du paquet « vile » (universe)
 La commande « file » du paquet « file » (main)
 La commande « zile » du paquet « zile » (universe)
File : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$     'video info', flags=re.MULTILINE),
bash: erreur de syntaxe près du symbole inattendu « ) »
utilisateur@utilisateur-Aspire-5738:~$   File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 611, in _search_regex
La commande « File » est introuvable, vouliez-vous dire :
 La commande « vile » du paquet « vile » (universe)
 La commande « file » du paquet « file » (main)
 La commande « zile » du paquet « zile » (universe)
 La commande « kile » du paquet « kile » (universe)
File : commande introuvable
utilisateur@utilisateur-Aspire-5738:~$     raise RegexNotFoundError('Unable to extract %s' % _name)
bash: erreur de syntaxe près du symbole inattendu « ( »
utilisateur@utilisateur-Aspire-5738:~$ RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
RegexNotFoundError: : commande introuvable
please : commande introuvable
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%{ <-- HERE (.*?)}/ at /usr/bin/see line 528.
Error: no such file ":https://yt-dl.org/update"
Error: no such file "on"
Error: no such file "how"
Error: no such file "to"
Error: no such file "update."
Error: no such file "Be"
Error: no such file "sure"
Error: no such file "to"
Error: no such file "call"
Error: no such file "youtube-dl"
Error: no such file "with"
Error: no such file "the"
Error: no such file "flag"
Error: no such file "and"
Error: no such file "include"
Error: no such file "its"
Error: no such file "complete"
Error: no such file "output."
utilisateur@utilisateur-Aspire-5738:~$ 

utilisateur@utilisateur-Aspire-5738:~$ youtube-dl http://replay.gulli.fr/dessins-animes/Magic-Famille-feerique/VOD68291658765000
[generic] VOD68291658765000: Requesting header
WARNING: Falling back on generic information extractor.
[generic] VOD68291658765000: Downloading webpage
[generic] VOD68291658765000: Extracting information
ERROR: Unsupported URL: http://replay.gulli.fr/dessins-animes/Magic-Famille-feerique/VOD68291658765000
utilisateur@utilisateur-Aspire-5738:~$

**Comment by efstathiosntonas** [comment]
same here using 2017.01.05 version

**Comment by yan12125** [comment]
@efstathiosntonas Could you open a new issue? This one is not readable.
