### ISSUE TITLE
not able to get output hls.

### ISSUE THREAD

**Issue by engkazim2000** [rg3/youtube-dl#11546]
Hi,

Can you please check as we are not able to get m3u8 file in output side logs are also pasted below.
we want to use that parameter "--hls-use-mpegts" because as per our requirement we want m3u8 file in out so at the same time we will watch the content in STB

E:\ff\ff\bin>youtube-dl_2.exe -v --hls-prefer-native https://www.youtube.com/watch?v=Ik5mjLELa9c
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--hls-prefer-native', 'https://www.youtube.com/watch?v=Ik5mjLELa9c']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.12.22
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82889-g54931fd, ffprobe N-82889-g54931fd
[debug] Proxy map: {}
[youtube] Ik5mjLELa9c: Downloading webpage
[youtube] Ik5mjLELa9c: Downloading video info webpage
[youtube] Ik5mjLELa9c: Extracting video information
[youtube] Ik5mjLELa9c: Downloading formats manifest
[youtube] Ik5mjLELa9c: Downloading MPD manifest
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/hls_playlist/id/Ik5mjLELa9c.0/itag/94/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D135/hls_chunk_host/r3---sn-2uja-3ip6.googlevideo.com/playlist_type/DVR/gcr/pk/mm/32/mn/sn-2uja-3ip6/ms/lv/mv/m/pl/23/dover/6/upn/kuzLcNS2ufg/mt/1482852740/ip/182.191.87.62/ipbits/0/expire/1482874413/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,playlist_type,gcr,mm,mn,ms,mv,pl/signature/52D0D42336ACEE387DE07B397C24D453CBCF21C4.6E7F04F0F0E0254E5D8235ECBB82313DE4EC233F/key/dg_yt0/playlist/index.m3u8'
[hlsnative] Downloading m3u8 manifest
WARNING: hlsnative has detected features it does not support, extraction will be delegated to ffmpeg
[download] Destination: DawnNews - Live Stream-Ik5mjLELa9c.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
' -i https://manifest.googlevideo.com/api/manifest/hls_playlist/id/Ik5mjLELa9c.0/itag/94/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D135/hls_chunk_host/r3---sn-2uja-3ip6.googlevideo.com/playlist_type/DVR/gcr/pk/mm/32/mn/sn-2uja-3ip6/ms/lv/mv/m/pl/23/dover/6/upn/kuzLcNS2ufg/mt/1482852740/ip/182.191.87.62/ipbits/0/expire/1482874413/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,playlist_type,gcr,mm,mn,ms,mv,pl/signature/52D0D42336ACEE387DE07B397C24D453CBCF21C4.6E7F04F0F0E0254E5D8235ECBB82313DE4EC233F/key/dg_yt0/playlist/index.m3u8 -c copy -f mp4 -bsf:a aac_adtstoasc 'file:DawnNews - Live Stream-Ik5mjLELa9c.mp4.part'
ffmpeg version N-82889-g54931fd Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 43.100 / 55. 43.100
  libavcodec     57. 68.100 / 57. 68.100
  libavformat    57. 61.100 / 57. 61.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 68.100 /  6. 68.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Input #0, hls,applehttp, from 'https://manifest.googlevideo.com/api/manifest/hls_playlist/id/Ik5mjLELa9c.0/itag/94/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D135/hls_chunk_host/r3---sn-2uja-3ip6.googlevideo.com/playlist_type/DVR/gcr/pk/mm/32/mn/sn-2uja-3ip6/ms/lv/mv/m/pl/23/dover/6/upn/kuzLcNS2ufg/mt/1482852740/ip/182.191.87.62/ipbits/0/expire/1482874413/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,playlist_type,gcr,mm,mn,ms,mv,pl/signature/52D0D42336ACEE387DE07B397C24D453CBCF21C4.6E7F04F0F0E0254E5D8235ECBB82313DE4EC233F/key/dg_yt0/playlist/index.m3u8':
  Duration: N/A, start: 39496.023000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 854x480 [SAR 1:1 DAR 427:240], 30 fps, 30 tbr, 90k tbn, 60 tbc
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:DawnNews - Live Stream-Ik5mjLELa9c.mp4.part':
  Metadata:
    encoder         : Lavf57.61.100
    Stream #0:0: Video: h264 (Main) ([33][0][0][0] / 0x0021), yuv420p, 854x480 [SAR 1:1 DAR 427:240], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  180 fps= 37 q=-1.0 Lsize=     373kB time=00:00:05.98 bitrate= 511.1kbits/s speed=1.24x
video:278kB audio:92kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.099221%
Exiting normally, received signal 2.

**Comment by yan12125** [comment]
It in this line:

> [debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/hls_playlist/id/Ik5mjLELa9c.0/itag/94/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D135/hls_chunk_host/r3---sn-2uja-3ip6.googlevideo.com/playlist_type/DVR/gcr/pk/mm/32/mn/sn-2uja-3ip6/ms/lv/mv/m/pl/23/dover/6/upn/kuzLcNS2ufg/mt/1482852740/ip/182.191.87.62/ipbits/0/expire/1482874413/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,playlist_type,gcr,mm,mn,ms,mv,pl/signature/52D0D42336ACEE387DE07B397C24D453CBCF21C4.6E7F04F0F0E0254E5D8235ECBB82313DE4EC233F/key/dg_yt0/playlist/index.m3u8'

To get m3u8 URLs only, use -g:
```
youtube-dl -g "https://www.youtube.com/watch?v=Ik5mjLELa9c"
```

**Comment by engkazim2000** [comment]
Hi,

I just check the provided command but its not working for me
Next we want to dump m3u8 file instend of mp4

On 27-Dec-2016 8:51 PM, "Yen Chi Hsuan" <notifications@github.com> wrote:

It in this line:

[debug] Invoking downloader on 'https://manifest.googlevideo.
com/api/manifest/hls_playlist/id/Ik5mjLELa9c.0/itag/94/
source/yt_live_broadcast/requiressl/yes/ratebypass/yes/
live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/
sgovp/gir%3Dyes%3Bitag%3D135/hls_chunk_host/r3---sn-2uja-
3ip6.googlevideo.com/playlist_type/DVR/gcr/pk/mm/32/mn/sn-
2uja-3ip6/ms/lv/mv/m/pl/23/dover/6/upn/kuzLcNS2ufg/mt/
1482852740/ip/182.191.87.62/ipbits/0/expire/1482874413/
sparams/ip,ipbits,expire,id,itag,source,requiressl,
ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,
playlist_type,gcr,mm,mn,ms,mv,pl/signature/52D0D42336ACEE387DE07B397C24D4
53CBCF21C4.6E7F04F0F0E0254E5D8235ECBB82313DE4EC233F/key/dg_yt0/
playlist/index.m3u8'

To get m3u8 URLs only, use -g:

youtube-dl -g "https://www.youtube.com/watch?v=Ik5mjLELa9c"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rg3/youtube-dl/issues/11546#issuecomment-269343403>,
or mute
the thread

**Comment by yan12125** [comment]
> I just check the provided command but its not working for me

Any errors?

**Comment by engkazim2000** [comment]
No its not showing any error even if we get the link its loaded but stuck
on first frame

Is there any why to save m3u8 file and also keep update in back ground

Example video is attached which we want to build.

https://www.youtube.com/watch?v=u1scw0qLsZw&t=39s

**Comment by yan12125** [comment]
> even if we get the link its loaded but stuck on first frame

How did you get frames? ffmpeg can get frames fine - with some warnings, though.

> Is there any why to save m3u8 file and also keep update in back ground

Just keep requesting the same m3u8 URL.

**Comment by engkazim2000** [comment]
Hi,

even if we get the link its loaded but stuck on first frame

How did you get frames? ffmpeg can get frames fine - with some warnings,
though.

We are checking in vlc

is the parameter works "--hls-use-mpegts"

--hls-use-mpegts                 Use the mpegts container for HLS videos,
                                 allowing to play the video while
                                 downloading (some players may not be able
                                 to play it)

Have you check the youtube video  which we share

**Comment by engkazim2000** [comment]
Hi,

We will create bash script but once it start saving m3u8 file instead of
mp4.

**Comment by yan12125** [comment]
I got stuck on VLC, too. Apparently VLC is broken as mpv works fine.

> Have you check the youtube video which we share

Yes, but I have never used IPTV so I can't give any opinion

> is the parameter works "--hls-use-mpegts"

That doesn't matter. It's only relevant in downloading.

By the way, here's my mpv command:
```
mpv "$(youtube-dl -g "https://www.youtube.com/watch?v=Ik5mjLELa9c")"
```

**Comment by engkazim2000** [comment]
Hi,

mpv "$(youtube-dl -g "https://www.youtube.com/watch?v=Ik5mjLELa9c")"

thanks the provided command is working

do you have any idea how we save the output in m3u8 file

**Comment by engkazim2000** [comment]
Hi,

once the m3u8 file will start creating i will make test it IPTV right now
we are facing issue in first step.

**Comment by yan12125** [comment]
> do you have any idea how we save the output in m3u8 file

I use curl:
```
curl "$(youtube-dl -g "https://www.youtube.com/watch?v=Ik5mjLELa9c")" > output.m3u8
```

**Comment by engkazim2000** [comment]
Hi,

can you please check the output file is not working.

**Comment by yan12125** [comment]
Ah, that's a ffmpeg security mechanism - m3u8 files on the disk are not allowed to access remote files. Instead, you'll need to feed to m3u8 URL to your favorite player.

**Comment by engkazim2000** [comment]
Ah, that's a ffmpeg security mechanism - m3u8 files on the disk are not
allowed to access remote files. Instead, you'll need to feed to m3u8 URL to
your favorite player.

Is there any solution in your view we will use nginx to play the output
file. right now i am trying in vlc and mpv

**Comment by yan12125** [comment]
Download it on the server and feed the downloaded file to users?

**Comment by engkazim2000** [comment]
Hi,

Thats not the solution because the live stream never end and downloading
allways keep running and we are also not able to watch content during the
downloading and its also take too much usage of resources

**Comment by yan12125** [comment]
I'm not quite sure what you want. Does your clients support Javascripts? There are lots of web players that supports m3u8.
