### ISSUE TITLE
Problem downloading video from cspan.

### ISSUE THREAD

**Issue by dethrophes** [rg3/youtube-dl#11547]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.22**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
youtube-dl -U --verbose https://www.c-span.org/video/\?114917-1/armed-services
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-U', u'--verbose', u'https://www.c-span.org/video/?114917-1/armed-services']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.12.22
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6
[debug] Proxy map: {}
youtube-dl is up-to-date (2016.12.22)
[CSpan] 114917: Downloading webpage
ERROR: unable to find video id and type; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/dethrophes/scripts/python/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/dethrophes/scripts/python/youtube-dl/youtube_dl/extractor/common.py", line 358, in extract
    return self._real_extract(url)
  File "/home/dethrophes/scripts/python/youtube-dl/youtube_dl/extractor/cspan.py", line 85, in _real_extract
    raise ExtractorError('unable to find video id and type')
ExtractorError: unable to find video id and type; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by mpatel501** [comment]
I can't seem to access this video from browser. Have you tried another link on their website?

**Comment by dethrophes** [comment]
I seem to not have a great time with the cspan website, I'm not sure if there aren't some georetrictions or something.

Anyway If I open https://www.c-span.org/video/?114917-1/armed-services it doesn't show a video.
However if I look at the source and use the iframe link it works.
<input type='hidden' id='bandwidth' value=''><iframe
					src='http://www.ustream.tv/embed/recorded/58428542'
					width='100%'
					frameborder='0'
					id='video-iframe'>


e.g. http://www.ustream.tv/embed/recorded/58428542


From what I can piece together, they have different sources for congressional/house hearings, they direct link to the congress videos when they are available. 
It looks like the congress ay have switched sources, at some point, they now self host the videos, it looks like they previously used ustream to host them.

Or something like that.

**Comment by yan12125** [comment]
Thanks for the report. Ustream videos on C-Span will be supported in the next version.

**Comment by yan12125** [comment]
> Doesn't seem to be working with the inlined videos hosted on the senate site. e.g.https://www.c-span.org/video/?419435-1/emerging-us-defense-challenges-worldwide-threats

Apparently this video has been gone
