### ISSUE TITLE
How to set youtube-dl to not download more than 1mb of file size

### ISSUE THREAD

**Issue by sant527** [rg3/youtube-dl#11557]
How to tell youtube-dl to stop after it reaches a file size of 1mb

**Comment by yan12125** [comment]
Currently there's no direct support in youtube-dl. A workaround can be:
```
youtube-dl -v URL -o - | head -c 1000000 > output.mp4
```
What is your use case? Just curious.

**Comment by sant527** [comment]
Can i make use of %{title} etc in the output.mp4
