### ISSUE TITLE
INE Video download support

### ISSUE THREAD

**Issue by jessica19921** [rg3/youtube-dl#11554]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.22**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

Can you please advice if youtube-dl supports ine.com video downloads, if so what should be the syntax.

**Comment by dstftw** [comment]
`youtube-dl URL`.

**Comment by jessica19921** [comment]
whats youtube-dl URL.

**Comment by jessica19921** [comment]
Can you please advice if youtube-dl supports ine.com video downloads

**Comment by jessica19921** [comment]
if so what should be the syntax.

**Comment by dstftw** [comment]
>whats youtube-dl URL.

The syntax.

If this does not work then it's not supported.
