### ISSUE TITLE
youtube-dl.conf

### ISSUE THREAD

**Issue by Dimsok** [rg3/youtube-dl#11564]
Why not save config file near youtube-dll.exe for Windows instead of Documents and settings? That will be much more convenient. Youtube-dll is portable soft, no any setup, just exe, so don't know why not store config file near to exe.

**Comment by dstftw** [comment]
Cause it's standard acknowledged way to store config. youtube-dl is crossplatform and uses standard mechanisms for that. youtube-dl also stores cache and can't be considered completely portable.
