### ISSUE TITLE
Twitter Not Downloading MP4 (only M3U8)

### ISSUE THREAD

**Issue by RazoRIX** [rg3/youtube-dl#11569]
I want to grab direct video links (mp4) from Twitter videos, but when using Youtube-dl it is only fetching M3U8 streams.
The problem is, I want to get direct links to MP4 (I've seen some websites based on Youtube-dl doing this) and I want to do the same.

Any suggestions on how to extract links from M3U8 file? or any other ideas on how to get MP4 links from twitter videos?

**Comment by dstftw** [comment]
http://yt-dl.org/format-selection

**Comment by yan12125** [comment]
See https://github.com/rg3/youtube-dl/issues/10668#issuecomment-247655367
