### ISSUE TITLE
Subtitles are 10 hours out of sync

### ISSUE THREAD

**Issue by ducedo** [rg3/youtube-dl#11562]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v --write-sub --convert-subtitles srt "http://mediathek.daserste.de/Die-Wiwaldi-Show/G%C3%A4ste-Sonya-Kraus-Joachim-Llambi/Video?bcastId=11140718&documentId=33721104"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--write-sub', u'--convert-subtitles', u'srt', u'http://mediathek.daserste.de/Die-Wiwaldi-Show/G%C3%A4ste-Sonya-Kraus-Joachim-Llambi/Video?bcastId=11140718&documentId=33721104']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.22
[debug] Python version 2.7.10 - Darwin-16.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[ARD:mediathek] 33721104: Downloading webpage
[ARD:mediathek] 33721104: Downloading media JSON
[ARD:mediathek] 33721104: Downloading m3u8 information
[info] Writing video subtitles to: Gäste - Sonya Kraus, Joachim Llambi-33721104.de.ttml
[debug] Invoking downloader on u'http://hls.daserste.de/i/videoportal/Film/c_600000/604892/format,699600,699614,699599,699615,699598,.mp4.csmil/index_4_av.m3u8'
[download] Destination: Gäste - Sonya Kraus, Joachim Llambi-33721104.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: _alid_=xjUlIkzhY2CynUy8VOgGCw==
' -i http://hls.daserste.de/i/videoportal/Film/c_600000/604892/format,699600,699614,699599,699615,699598,.mp4.csmil/index_4_av.m3u8 -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Gäste - Sonya Kraus, Joachim Llambi-33721104.mp4.part'
ffmpeg version 3.2.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.2.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[NULL @ 0x7f8636022800] non-existing SPS 0 referenced in buffering period
[NULL @ 0x7f8636022800] SPS unavailable in decode_picture_timing
[h264 @ 0x7f8635003800] non-existing SPS 0 referenced in buffering period
[h264 @ 0x7f8635003800] SPS unavailable in decode_picture_timing
Input #0, hls,applehttp, from 'http://hls.daserste.de/i/videoportal/Film/c_600000/604892/format,699600,699614,699599,699615,699598,.mp4.csmil/index_4_av.m3u8':
  Duration: 00:29:02.17, start: 0.100667, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv), 960x540 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Gäste - Sonya Kraus, Joachim Llambi-33721104.mp4.part':
  Metadata:
    encoder         : Lavf57.56.100
    Stream #0:0: Video: h264 (Main) ([33][0][0][0] / 0x0021), yuv420p(tv), 960x540 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=43553 fps= 99 q=-1.0 Lsize=  424649kB time=00:29:02.14 bitrate=1996.8kbits/s speed=3.95x    
video:383898kB audio:40293kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.107842%
[ffmpeg] Downloaded 434840233 bytes
[download] 100% of 414.70MiB
[ffmpeg] Converting subtitles
WARNING: You have requested to convert dfxp (TTML) subtitles into another format, which results in style information loss
Deleting original file Gäste - Sonya Kraus, Joachim Llambi-33721104.de.ttml (pass -k to keep)
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Several of the videos I've tried come with subtitles that seem to be exactly 10 hours out of sync. For example, the first timestamp in one file claims 10:03:57.600 which doesn't show any subs until I delete or replace the 1 to a zero, giving: 00:03:57.600. One of the URLs below seem to work without problem despite being from the same site. The subtitles are originally in .ttml format and I've both tried to download them as they are and convert them into .srt with the same issue.

- Error: http://mediathek.daserste.de/Comedy-Satire-im-Ersten/3-Stock-links-Die-Offenbarung/Video?bcastId=25304236&documentId=38856018
- Error: http://mediathek.daserste.de/Die-Wiwaldi-Show/G%C3%A4ste-Sonya-Kraus-Joachim-Llambi/Video?bcastId=11140718&documentId=33721104
- Error: http://www.ardmediathek.de/tv/Tatort/Nie-wieder-frei-sein/Das-Erste/Video?bcastId=602916&documentId=39310346
- Working: http://www.ardmediathek.de/tv/Tagesschau/tagesschau-20-00-Uhr/Das-Erste/Video?bcastId=4326&documentId=39736606

**Comment by dstftw** [comment]
Original .ttml subtitles' timestamps are 10h shifted thus that's not an youtube-dl issue.
