### ISSUE TITLE
download video from kabeleins.de by video id

### ISSUE THREAD

**Issue by kamenn0** [rg3/youtube-dl#11566]
is it possible to download the video from kabeleins.de which is not availble anymore if you know its id?

the source page was http://www.kabeleins.de/musik/metallica-live-in-concert/metallica-live-in-concert-ganze-folge

the video id was 4761633

the download link for SD version (640x360) was http://progressive-ak-mdp.glomex.com/clips/13/f3/4761633-zoldxf-tp06.mp4?hdnea=st=1480717013~exp=1480803413~acl=%2Fclips%2F13%2Ff3%2F4761633-zoldxf-tp06.mp4%2A~hmac=9bbaf8a52ee1da3e3eb8f960564cf3273287c535c2cb7eb520ef750bd4874bce&access_token=kabeleins&video=1296000&bp=AAH6g4t8dZQXOa3S_qzkl4RUVuiDsjdDnUQYupBSjmbfqH4

though the video is not available on the web site, maybe it's somehow possible to get it from the providers' servers? the other videos from kabeleins.de lead to glomex.com and sim-technik.de. i am not familiar with scripting, so if someone know wether it's possible and if yes then how please let me know.

the thing is i downloaded it when it's was available, but in SD (about 1000 kbps). and now i discovered it could be downloaded in HD with bitrate up to 3500 kbps. and it makes me restless.

thanks for everyone's help in advance.

**Comment by dstftw** [comment]
Not possible.
