### ISSUE TITLE
how to download from Arkena

### ISSUE THREAD

**Issue by ovess** [rg3/youtube-dl#11568]
I can't get it work. Can anyone explain that for me?
This for example. 
http://video.arkena.com/play2/embed/player?accountId=472718&mediaId=35763b3b-00090078-bf604299&pageStyling=styled

**Comment by dstftw** [comment]
https://play.arkena.com/embed/avp/v2/player/media/35763b3b-00090078-bf604299/1/472718

**Comment by ovess** [comment]
Thanks, and how do you get that url?

**Comment by ovess** [comment]
How do you get play.arkena.com.. url?

**Comment by dstftw** [comment]
Wrote it by hand.
