### ISSUE TITLE
Avconv not detected?

### ISSUE THREAD

**Issue by iarspider** [rg3/youtube-dl#11563]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl --verbose -C --prefer-avconv https://www.twitch.tv/iarspider/v/110629920 -o "Skyrim_001.mp4"
[debug] System config: []
[debug] User config: [u'--ffmpeg-location', u'/home/sysadmin/libav']
[debug] Command-line args: [u'--verbose', u'-C', u'--prefer-avconv', u'https://www.twitch.tv/iarspider/v/110629920', u'-o', u'Skyrim_001.mp4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.22
[debug] Python version 2.7.6 - Linux-3.13.0-98-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Public IP address: xxx.xxx.xxx.xxx
[twitch:vod] 110629920: Downloading vod info JSON
[twitch:vod] 110629920: Downloading vod access token
[twitch:vod] 110629920: Downloading m3u8 information
[debug] Invoking downloader on u'https://vod146-ttvnw.akamaized.net/v1/AUTH_system/vods_9922/iarspider_24070824080_573097007/chunked/index-dvr.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 5678
[download] Destination: Skyrim_001.mp4
[download] 100% of 759.23MiB in 22:38
WARNING: v110629920: malformated aac bitstream. Install ffmpeg or avconv to fix this automatically.
```

---

### Description of your *issue*, suggested solution and other information

Since I'm still on Ubuntu 14.04, I have decided to build libav from source myself (so that youtube-dl won't complain every time). Everything worked until now. 

lib av version 12:
```
$ /home/sysadmin/libav/bin/avconv
avconv version 12, Copyright (c) 2000-2016 the Libav developers
  built on Dec 31 2016 10:47:44 with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
Hyper fast Audio and Video encoder
usage: avconv [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man avconv'
```

**Comment by dstftw** [comment]
```
    --ffmpeg-location PATH           Location of the ffmpeg/avconv binary;
                                     either the path to the binary or its
                                     containing directory.
```

>either the path to **the binary** or **its directory**

**Comment by iarspider** [comment]
Oops and thanks!
