### ISSUE TITLE
Site support request: NJPW World

### ISSUE THREAD

**Issue by AdmiralDal59** [rg3/youtube-dl#11561]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\apps\ydl>youtube-dl.exe -v http://njpwworld.com/p/s_series_00155_1_9/e/sp/1396
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://njpwworld.com/p/s_series_00155_1_9/e/s
p/1396']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.12.22
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-78598-g98a0053, ffprobe N-78598-g98a0053
[debug] Proxy map: {}
WARNING: Could not send HEAD request to http://njpwworld.com/p/s_series_00155_1_
9/e/sp/1396: HTTP Error 403: Forbidden
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://njpwworld.com/p/s_series_00155_1_9/e/sp/1396
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\bu
ild\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\bu
ild\youtube_dl\extractor\common.py", line 358, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\bu
ild\youtube_dl\extractor\generic.py", line 2453, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://njpwworld.com/p/s_series_00155_1_/e/sp/1396
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://njpwworld.com/p/s_series_00155_1_9/e/sp/1396

---

### Description of your *issue*, suggested solution and other information

Most video require subscription, but there are some free videos that are up for a limited time. Source: http://www.foxsports.com/wwe/story/how-to-watch-new-japan-pro-wrestling-wrestle-kingdom-matches-122016

**Comment by AdmiralDal59** [comment]
yan12125, I sent details to your email address listed in your profile.

**Comment by yan12125** [comment]
Thanks. I've added this site. Don't forget to change your password.

**Comment by yan12125** [comment]
Side note: in this example the m3u8 manifest and the AES key file are hosted on different servers. Only the native HLS downloader can handle it. (of course pycrypto should be installed first)

I've issued an FFMpeg feature request: http://trac.ffmpeg.org/ticket/6190

**Comment by AdmiralDal59** [comment]
Thank you.
