### ISSUE TITLE
[NRKTV] Add support for downloading series (playlist)

### ISSUE THREAD

**Issue by oddstr13** [rg3/youtube-dl#11571]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
- Series: http://tv.nrksuper.no/serie/wallace-og-gromit
- Series: https://tv.nrk.no/serie/skam
- Series: https://tv.nrk.no/serie/oppfinneren
- Series: https://tv.nrk.no/serie/nytt-paa-nytt
- Series: https://tv.nrk.no/serie/broedrene-dal-og-professor-droevels-hemmelighet
- Series extras: https://tv.nrk.no/extramaterial/skam
- Episode listing (Series season): https://tv.nrk.no/program/Episodes/skam/70522
- Episode listing (Series season): https://tv.nrk.no/program/Episodes/game-of-thrones/27567
- Episode listing (Series season): https://tv.nrk.no/program/Episodes/game-of-thrones/75362
- Episode listing (Series season): https://tv.nrk.no/program/Episodes/game-of-thrones/86355

Some series/episodes are available world wide until end of time. Some have time and or geo restrictions.

---

### Description of your *issue*, suggested solution and other information

Add support for downloading all (available), or a subset of episodes of a TV Series from the domains tv.nrk.no and tv.nrksuper.no.

**Comment by oddstr13** [comment]
Episodes listing download is now **working**. `https://tv.nrk.no/program/Episodes/gubben-og-katten/74302`
Full series download does **not work**. `https://tv.nrk.no/serie/gubben-og-katten`

---

Season and Episode number information not properly populated in format string;
 - Format: `/mnt/Media/youtube-dl/%(extractor)s/series/%(series)s/%(season_number)s - %(season)s/[%(id)s] - %(episode_number)s - %(episode)s %(title)s/[%(id)s] - %(title)s.%(ext)s`
- Output: `/mnt/Media/youtube-dl/NRK/series/Gubben og katten/NA - NA/[OBUI53006605AA] - NA - 6_6 Gubben og katten og nissemaskinen 6_6/[OBUI53006605AA] - Gubben og katten og nissemaskinen 6_6.mp4`
- Expected output: `/mnt/Media/youtube-dl/NRK/series/Gubben og katten/2 - Sesong 2/[OBUI53006605AA] - 6 - 6_6 Gubben og katten og nissemaskinen 6_6/[OBUI53006605AA] - Gubben og katten og nissemaskinen 6_6.mp4` or somewhere along those lines.

---
Season and episode number can be extracted from a couple locations in the json meta file, in addition to the `data.episodeNumberOrDate`.
 - `data.episodeNumberOrDate`
   * `"5:6"`
   * `"01.01.2017"`
 - `data.scoresStatistics.springStreamStream`
   * `"programspiller/odm/barn/gubben-og-katten/s02e05.gubben-og-katten-og-nissemaskinen.OBUI53006505"`
   * `"programspiller/odm/nyheter/dagsrevyen/s201701e0101.dagsrevyen.NNFA19010117"`
 - `data.relativeOriginUrl`
   * `"serie/gubben-og-katten/OBUI53006505/sesong-2/episode-5"`
   * `"serie/dagsrevyen/NNFA19010117/01-01-2017"`

I have not extensively checked different shows to see if they follow the same pattern, but I've noticed the `season-x/episode-y` part of the URL on several occasions over time. The statistics one I found now, after having a look at the json file dumped by youtube-dl. From the few samples I've had a look at, it seems to follow a rather strict `sxxeyy` structure.
Not sure which is best overall, but `S201701 E0101` is sortable by name giving chronological order, which is always a good thing. `01.01.2017` or `01-01-2017` not so much, as that is `%d-%m-%Y`... or is it `%m-%d-%Y`? I always mix those together.

**Comment by dstftw** [comment]
Cherry-picked, thanks.
