### ISSUE TITLE
download from universal-music.de in hd

### ISSUE THREAD

**Issue by kamenn0** [rg3/youtube-dl#11582]
is it possible to download videos in hd from this web site?
i downloaded the video in sd (640x360) with IDM, but maybe there are hd formats available to download with youtube-dl?
link to source page:
http://www.universal-music.de/metallica/videos/detail/video:421339/metallica-live-in-berlin-konzert-bei-circus-halligalli
sd download link:
rtmp://mediadelivery.universal-music-services.de:80/umusicstream/autofill/s/storage/4/2/1/3/3/9/content/686/file
thanks in advance.

**Comment by yan12125** [comment]
FYI, HD (1024x576) link: http://mediadelivery.universal-music-services.de/vod/mp4:autofill/storage/4/2/1/3/3/9/content/836/file/playlist.m3u8

You can download with "youtube-dl http://mediadelivery.universal-music-services.de/vod/mp4:autofill/storage/4/2/1/3/3/9/content/836/file/playlist.m3u8"

**Comment by kamenn0** [comment]
thanks yan12125, but the video from your link has even lower bitrate than from IDM, though a higher resolution. any other options for this video?

**Comment by yan12125** [comment]
There's an implementation at #11584 yet it requires some fixes.

**Comment by kamenn0** [comment]
oh, i see. thanks for clarifying. how will i know when it's implemented (fixed)?
i apologize if my questions are incorrect.
thanks.

**Comment by yan12125** [comment]
Seems there are quite a few issues in #11584. I don't expect it merged soon.

**Comment by yan12125** [comment]
I don't know. The format 1024x576 is what I get on Firefox, and there are no other formats provided.

**Comment by kamenn0** [comment]
hi yan12125. first i thought it was your implementation. now i see it wasn't. so i'll have to contact flatt3rn for more details. but anyway thanks for your help.

**Comment by remitamine** [comment]
the qualities available for this video are: 483x272, 640x360, 1024x576.

**Comment by kamenn0** [comment]
so no hd? it's sad.
