### ISSUE TITLE
Can't download anymore because of error: ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by computerfreak105** [rg3/youtube-dl#11583]
Since yesterday I can't download anything anymore on my windows 7 64-bit machine. The program is still working on a windows XP notebook.
I'm not sure what happened here. Should I reinstall pyton 3.4? Or how can I fix this? Thanks very much for your help.

Here is the log:

G:\>youtube-dl --cookies cookies.txt --username MyUsername
 --password MyPassword -f 140/m4a -i -o G:\yt/%(uploader)s/%(title)s_%(upload_date)s.%
(ext)s -a you.txt -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', '--username', 'PRIVATE',
 '--password', 'PRIVATE', '-f', '140/m4a', '-i', '-o', 'G:\\yt/%(uploader)s/%(ti
tle)s_%(upload_date)s.%(ext)s', '-a', 'you.txt', '-v']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=qvcPsu7E9a0']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.02
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Downloading login page
WARNING: unable to fetch login page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAI
LED] certificate verify failed (_ssl.c:600)>
[youtube] qvcPsu7E9a0: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILE
D] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL
: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0hst59yw\bu
ild\youtube_dl\extractor\common.py", line 406, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0hst59yw\bu
ild\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0hst59yw\bu
ild\youtube_dl\utils.py", line 1041, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/11573#issuecomment-269896421

**Comment by a1iraxa** [comment]
#11573 fixed
