### ISSUE TITLE
Add support to download streams from adultswim.com

### ISSUE THREAD

**Issue by gnurt1** [rg3/youtube-dl#11587]
C:\Users\xxxxx> youtube-dl.exe http://www.adultswim.com/videos/streams/williams-stream

[AdultSwim] williams-stream: Downloading webpage
ERROR: Unable to extract bootstraped data; please report this issue on https://y
t-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
to update. Be sure to call youtube-dl with the --verbose flag and include its co
mplete output.

**Comment by yan12125** [comment]
AdultSwim has been broken for a long time. See #11042

**Comment by stepshal** [comment]
@gnurt1 you can watch them with https://github.com/streamlink/streamlink
