### ISSUE TITLE
Broswer error ERROR: ffprobe or avprobe not found.

### ISSUE THREAD

**Issue by deangelo200** [rg3/youtube-dl#11599]
Can someone please help me. When i open my terminal and run my code i am able to download videos/ mp3 etc i have ffprobe  avprobe installed and in my path. I used brew to install them and everything is working. But when i try to run my code through my virtual local server i get this error. Can someone tell me what am doing wrong. I think i have to add the ffprobe or avprobe to my virtual host path ? I dont know if that make sense am confused and lost

[Wed Jan 04 03:16:20.177686 2017] [cgi:error] [pid 869] [client 127.0.0.1:63747] AH01215: youtube_dl.utils.DownloadError: ERROR: ffprobe or avprobe not found. Please install one.: /Users/deangeloalmeus/server/index.py, referer: http://myserver.dev/

**Comment by yan12125** [comment]
> I think i have to add the ffprobe or avprobe to my virtual host path ?

Yep that sounds like the most possible solution, or you may want to specify the path to ffprobe/avprobe with ```--ffmpeg-location```.

**Comment by deangelo200** [comment]
I wanted to do this with python

**Comment by yan12125** [comment]
Then try passing ```ffmpeg_location``` to ```YoutubeDL```

**Comment by deangelo200** [comment]
Can you show me how to do this with python?

**Comment by yan12125** [comment]
```
ydl_opts = {
    'ffmpeg_location': '/path/to/the/folder/with/ffprobe',
}

with YoutubeDL(ydl_opts) as ydl:
   # whatever you want to do
```

**Comment by deangelo200** [comment]
thanks bro but i noticed the problem i had to download libav then go in the bin folder and copy the files in the bin folder and put it in the same folder my youtbe-dl.exe :)
