### ISSUE TITLE
zdf extractor currently doesn't work

### ISSUE THREAD

**Issue by leooleo-habbib** [rg3/youtube-dl#11590]
Hi, here is the debug:

jachmann@hurx:/tmp>youtube-dl -v  'https://www.zdf.de/filme/taunuskrimi/die-lebenden-und-die-toten-1---ein-taunuskrimi-100.html'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.zdf.de/filme/taunuskrimi/die-lebenden-und-die-toten-1---ein-taunuskrimi-100.html']
[debug] Encodings: locale ISO8859-15, fs ISO8859-15, out ISO8859-15, pref ISO8859-15
[debug] youtube-dl version 2017.01.02
[debug] Python version 2.7.13 - FreeBSD-10.3-STABLE-i386-32bit-ELF
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] die-lebenden-und-die-toten-1---ein-taunuskrimi-100: Requesting header
WARNING: Falling back on generic information extractor.
[generic] die-lebenden-und-die-toten-1---ein-taunuskrimi-100: Downloading webpage
[generic] die-lebenden-und-die-toten-1---ein-taunuskrimi-100: Extracting information
ERROR: Unsupported URL: https://www.zdf.de/filme/taunuskrimi/die-lebenden-und-die-toten-1---ein-taunuskrimi-100.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1669, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 141, column 162
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 359, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2486, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.zdf.de/filme/taunuskrimi/die-lebenden-und-die-toten-1---ein-taunuskrimi-100.html

somehow the regex has to be  changend.

**Comment by yan12125** [comment]
ZDF has been broken for a long time. See #11055 and an incomplete fix at #11063

**Comment by leooleo-habbib** [comment]
Tue, Jan 03, 2017 at 02:30:04AM -0800, Yen Chi Hsuan :
> ZDF has been broken for a long time. See #11055 and an incomplete fix at #11063

Yes, i read that. Any idea whan this works again ?

Or what could i do to help ?

Thanks,

Christian Jachmann

**Comment by yan12125** [comment]
Apparently bastik, the author of #11063 is not going to continue the work. You may want to continue the work based on #11063 or wait for someone else to do that.
