### ISSUE TITLE
youtube-dl fails to download some videos from youtube.com

### ISSUE THREAD

**Issue by orbea** [rg3/youtube-dl#11616]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
~$ youtube-dl --verbose https://www.youtube.com/watch?v=OEh6JK9ECSU
[debug] System config: []
[debug] User config: ['--prefer-free-formats', '--format', 'webm/ogg/best']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=OEh6JK9ECSU']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.05
[debug] Python version 3.5.2 - Linux-4.9.0-x86_64-AMD_FX-tm-6350_Six-Core_Processor-with-slackware-14.2
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] OEh6JK9ECSU: Downloading webpage
[youtube] OEh6JK9ECSU: Downloading embed webpage
[youtube] OEh6JK9ECSU: Refetching age-gated info webpage
ERROR: OEh6JK9ECSU: YouTube said: <a href="http://www.youtube.com/watch?v=OEh6JK9ECSU&feature=player_embedded" target="_blank">Watch this video on YouTube.</a>
Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/common.py", line 359, in extract
    return self._real_extract(url)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1327, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: OEh6JK9ECSU: YouTube said: <a href="http://www.youtube.com/watch?v=OEh6JK9ECSU&feature=player_embedded" target="_blank">Watch this video on YouTube.</a>
Playback on other websites has been disabled by the video owner.
```
### Description of your *issue*, suggested solution and other information

Youtube-dl fails to download some videos from youtube.com.

Example - https://www.youtube.com/watch?v=OEh6JK9ECSU

**Comment by dstftw** [comment]
This video is only available with YouTube account credentials.
