### ISSUE TITLE
youtube-dl can I store the size of the video in a variable to access outside

### ISSUE THREAD

**Issue by sant527** [rg3/youtube-dl#11611]
I am using linux and youtube-dl

I saw
filesize: The number of bytes, if known in advance
filesize_approx: An estimate for the number of bytes

how to store that in a vriable in my shell script.

I dont want to download videos > 20MB or so.

**Comment by yan12125** [comment]
> how to store that in a vriable in my shell script.

Use -j and parse the result

> I dont want to download videos > 20MB or so.

```--max-filesize``` can help.
