### ISSUE TITLE
Ignore specific options from configuration file

### ISSUE THREAD

**Issue by Tony-il-Capo** [rg3/youtube-dl#11615]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.05**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

Hi there
Is there a way to ignore specific options from config file? Like, if the options are present on command line, the same options on configuration file are ignored.

I make use of configuration file because I use proxy and custom downloader options, if not, is hard to write them every time.
I read here about having multiple config files, but don't seems implemented.

Anyway, it's something that shouldn't take much priority nor time.

_Btw, youtube-dl runs great on my OpenWrt router (WR1043NDv2), Rpi 3 and Linux STB (Vu+ Duo2), thanks so much for this awesome tool._

**Comment by dstftw** [comment]
>Like, if the options are present on command line, the same options on configuration file are ignored.

Options passed on command line override the same options from configuration file.

>I read here about having multiple config files, but don't seems implemented.

Wrong, it's implemented: `--config-location`.

**Comment by Tony-il-Capo** [comment]
Thanks, I tested this before and somehow it was not working, it would still use options from configuration file. I need to check this again.

Could this info be clarified on readme page?
I only find this
> You can use --ignore-config if you want to disable the configuration file for a particular youtube-dl run.

Thanks again and sorry about this.

**Comment by heikoherold** [comment]
> > Like, if the options are present on command line, the same options on configuration file are ignored.
> 
> Options passed on command line override the same options from configuration file.

What about options with mandatory arguments, where we want to override to the default?

E. g. config file contains _--recode-video mkv_ but we don't want to recode for this execution.
Just adding _--recode-video_ generates an error _youtube-dl: error: invalid video recode format specified_.

Note: selecting another config file is far less useful because you need to copy the standard config file and edit it.
