### ISSUE TITLE
Unable to download a video... Please ignore, works with latest version.

### ISSUE THREAD

**Issue by flajann2** [rg3/youtube-dl#11617]
On Ubuntu 16.04, latest available from apt-get

youtube-dl https://youtu.be/FCWHoXMt3G4

Version 2016.02.22, but this is the latest available from the repo.

failed to work, resulting in the following:

[youtube] FCWHoXMt3G4: Downloading webpage
[youtube] FCWHoXMt3G4: Downloading video info webpage
[youtube] FCWHoXMt3G4: Extracting video information
[youtube] FCWHoXMt3G4: Downloading js player en_US-vflz_1lv2
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 820, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 883, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'zt'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

And with the --verbose flag:

 youtube-dl --verbose https://youtu.be/FCWHoXMt3G4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://youtu.be/FCWHoXMt3G4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.12 - Linux-4.4.0-57-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.10-0ubuntu0.16.04.1, ffprobe 2.8.10-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] FCWHoXMt3G4: Downloading webpage
[youtube] FCWHoXMt3G4: Downloading video info webpage
[youtube] FCWHoXMt3G4: Extracting video information
[youtube] {43} signature length 45.42, html5 player en_US-vflz_1lv2
[youtube] FCWHoXMt3G4: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflz_1lv2/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 820, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 883, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'zt'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'zt'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 820, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 883, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'zt'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1407, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 915, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 820, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 883, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'zt'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'zt'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.05**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.01.05
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by kmestri99** [comment]
I have an issue while downloading videos using youtube-dl 
kalpesh@dell-Vostro-1450:~$ youtube-dl -f 22 $ youtube-dl -v youtube-dl -f 22 https://www.youtube.com/watch?v=iLRZ9A26XMc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'22', u'$', u'youtube-dl', u'-v', u'youtube-dl', u'-f', u'22', u'https://www.youtube.com/watch?v=iLRZ9A26XMc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.26
[debug] Python version 2.7.12 - Linux-4.4.0-21-generic-x86_64-with-LinuxMint-18.1-serena

[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
ERROR: u'$' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:$" ) to search YouTube
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1804, in _real_extract
    % (url, url), expected=True)
ExtractorError: u'$' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:$" ) to search YouTube

kalpesh@dell-Vostro-1450:~$ [debug] System config: []
[debug]: command not found
kalpesh@dell-Vostro-1450:~$ [debug] User config: []
[debug]: command not found
kalpesh@dell-Vostro-1450:~$ [debug] Custom config: []
[debug]: command not found
kalpesh@dell-Vostro-1450:~$ [debug] Command-line args: [u'-v', u'youtube-dl', u'-f', u'22', u'https://www.youtube.com/watch?v=iLRZ9A26XMc']
[debug]: command not found
kalpesh@dell-Vostro-1450:~$ [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug]: command not found
kalpesh@dell-Vostro-1450:~$ [debug] youtube-dl version 2017.04.26
[debug]: command not found
kalpesh@dell-Vostro-1450:~$ [debug] Python version 2.7.12 - Linux-4.4.0-21-generic-x86_64-with-LinuxMint-18.1-serena
[debug]: command not found
kalpesh@dell-Vostro-1450:~$ [debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug]: command not found
kalpesh@dell-Vostro-1450:~$ [debug] Proxy map: {}
[debug]: command not found
kalpesh@dell-Vostro-1450:~$ ERROR: u'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube
bash: syntax error near unexpected token `('
kalpesh@dell-Vostro-1450:~$ Traceback (most recent call last):
bash: syntax error near unexpected token `most'
kalpesh@dell-Vostro-1450:~$   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
No command 'File' found, did you mean:
 Command 'zile' from package 'zile' (universe)
 Command 'file' from package 'file' (main)
 Command 'vile' from package 'vile' (universe)
 Command 'kile' from package 'kile' (universe)
File: command not found
kalpesh@dell-Vostro-1450:~$     ie_result = ie.extract(url)
bash: syntax error near unexpected token `('
kalpesh@dell-Vostro-1450:~$   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
No command 'File' found, did you mean:
 Command 'file' from package 'file' (main)
 Command 'vile' from package 'vile' (universe)
 Command 'kile' from package 'kile' (universe)
 Command 'zile' from package 'zile' (universe)
File: command not found
kalpesh@dell-Vostro-1450:~$     ie_result = self._real_extract(url)
bash: syntax error near unexpected token `('
kalpesh@dell-Vostro-1450:~$   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1804, in _real_extract
No command 'File' found, did you mean:
 Command 'kile' from package 'kile' (universe)
 Command 'vile' from package 'vile' (universe)
 Command 'file' from package 'file' (main)
 Command 'zile' from package 'zile' (universe)
File: command not found
kalpesh@dell-Vostro-1450:~$     % (url, url), expected=True)
bash: syntax error near unexpected token `url,'
kalpesh@dell-Vostro-1450:~$ ExtractorError: u'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube
bash: syntax error near unexpected token `('
kalpesh@dell-Vostro-1450:~$

**Comment by kmestri99** [comment]
kalpesh@dell-Vostro-1450:~$ youtube-dl --version
2017.04.26

**Comment by yan12125** [comment]
@kmestri99 Please follow #12885
