### ISSUE TITLE
South Park videos (southpark.cc.com) fail to download, connection timeouts

### ISSUE THREAD

**Issue by nicofanu** [rg3/youtube-dl#11624]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v http://southpark.cc.com/clips/104400/vote-or-die
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://southpark.cc.com/clips/104400/vote-or-die']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.05
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.9
[debug] exe versions: avconv 0.8.17-6, avprobe 0.8.17-6, ffmpeg 0.8.17-6, ffprobe 0.8.17-6, rtmpdump 2.4
[debug] Proxy map: {}
[southpark.cc.com] vote-or-die: Downloading webpage
[southpark.cc.com] a79f456c-ed00-11e0-aca6-0026b9414f30: Downloading info
[southpark.cc.com] a79f456c-ed00-11e0-aca6-0026b9414f30: Extracting information
[southpark.cc.com] a79f456c-ed00-11e0-aca6-0026b9414f30: Downloading video urls
[download] Downloading playlist: Vote or Die
[southpark.cc.com] playlist Vote or Die: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Invoking downloader on u'http://viacommtvstrmfs.fplive.net/gsp.comedystor/com/sp/season-8/0808/clips/sp_0808_clipHD_05_B_1280x720_1200.mp4'
ERROR: unable to download video data: <urlopen error [Errno 110] Connection timed out>
Traceback (most recent call last):
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/bin/youtube-dl/youtube_dl/utils.py", line 877, in http_open
    req)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 110] Connection timed out>
```

---

### Description of your *issue*, suggested solution and other information

I'm getting connection timeouts when trying to download videos from southpark.cc.com. Possibly related to [this issue](https://github.com/rg3/youtube-dl/issues/11600).  I can watch videos on the site just fine. Wget also times out when trying to download the direct link:

```
$ wget http://viacommtvstrmfs.fplive.net/gsp.comedystor/com/sp/season-8/0808/clips/sp_0808_clipHD_05_B_1280x720_1200.mp4
--2017-01-06 13:31:17--  http://viacommtvstrmfs.fplive.net/gsp.comedystor/com/sp/season-8/0808/clips/sp_0808_clipHD_05_B_1280x720_1200.mp4
Resolving viacommtvstrmfs.fplive.net... 192.221.127.125
Connecting to viacommtvstrmfs.fplive.net|192.221.127.125|:80... failed: Connection timed out.
Retrying.

--2017-01-06 13:32:22--  (try: 2)  http://viacommtvstrmfs.fplive.net/gsp.comedystor/com/sp/season-8/0808/clips/sp_0808_clipHD_05_B_1280x720_1200.mp4
Connecting to viacommtvstrmfs.fplive.net|192.221.127.125|:80... ^C
```

**Comment by vitusson** [comment]
Same thing happens since few days for othe Comedycentral sites, here Daily show with Trevor Noah

Only difference : I get a 404 and no timeout
But they both end on same Viacom server viacommtvstrmfs.fplive.net

[debug] Invoking downloader on u'http://viacommtvstrmfs.fplive.net/gsp.comedystor/com/dailyshow/TDS/season_22/042/ds_22_042_act1_qc7xopkgol_640x360_1028.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
