### ISSUE TITLE
video or audio url

### ISSUE THREAD

**Issue by vasvasvas** [rg3/youtube-dl#11621]
Hi!
I would like to ask the following questions:
1.	Is it possible to get the video link (e.g. http://......... .mpeg) without downloading the video file? I want to use this link in order to stream YouTube videos through Winamp. Winamp does not have any related plug-in. Furthermore I am not interested in using any other player (like VLC).
2.	Is it possible to get the audio link(e.g. http://......... .mp3) without downloading the audio file?

If yes, which commands I have to use?
Thank you

**Comment by yan12125** [comment]
You can use ```-g``` to get URLs and use ```-f``` to choose from video/audio.

**Comment by vasvasvas** [comment]
Hi!
I only get the YouTube link (https://www.youtube.com/watch?....) and not the video link or any audio link. Please write a code example to get the audio link.
Thank you

**Comment by yan12125** [comment]
For example, to get URL of the video stream,
```
youtube-dl -f bestvideo -g "https://www.youtube.com/watch?v=4uU8PmWPfMM"
```
And audio:
```
youtube-dl -f bestaudio -g "https://www.youtube.com/watch?v=4uU8PmWPfMM"
```
Or you can combine both:
```
youtube-dl -f bestvideo+bestaudio -g "https://www.youtube.com/watch?v=4uU8PmWPfMM"
```
As ```-f bestvideo+bestaudio``` is the default, it can be simplified as:
```
youtube-dl -g "https://www.youtube.com/watch?v=4uU8PmWPfMM"
```

**Comment by vasvasvas** [comment]
Hi! Thank you for helping me!
I get the following link:
https://r6---sn-4vguioxu-n3be.googlevideo.com/videoplayback/id/e2e53c3e658f7cc3/itag/140/source/youtube/requiressl/yes/ei/PcVvWOb5IsPAW6KLi6AN/initcwndbps/1111250/pl/21/mn/sn-4vguioxu-n3be/mm/31/ms/au/mv/m/ratebypass/yes/mime/audio%2Fmp4/otfp/1/gir/yes/clen/3966550/lmt/1432662451723912/dur/249.707/upn/yA_Dc_yITCU/mt/1483719758/signature/327DCA27216DB10C292B5D26FEAA49435080E331.7471AB4CFFF7EC1812396645CC920BF9150D1DDC/key/dg_yt0/ip/77.49.72.182/ipbits/0/expire/1483741597/sparams/ip,ipbits,expire,id,itag,source,requiressl,ei,initcwndbps,pl,mn,mm,ms,mv,ratebypass,mime,otfp,gir,clen,lmt,dur/

How can I get a direct link (…. .mp3) in order to insert it to Winamp?
Thank you

**Comment by dstftw** [comment]
YouTube does not serve mp3.

**Comment by vasvasvas** [comment]
Hi!
…any other direct link? 
“mp3” was an example.

Thank you

**Comment by dstftw** [comment]
Select any [other format](https://github.com/rg3/youtube-dl#format-selection).
