### ISSUE TITLE
How can i check if the url is a valid url before downloading ?

### ISSUE THREAD

**Issue by deangelo200** [rg3/youtube-dl#11649]
How can i check if the url is a valid url before downloading ?

**Comment by yan12125** [comment]
Use ```self._is_valid_url()```

**Comment by deangelo200** [comment]
Where would i have to use ? completely lost

**Comment by yan12125** [comment]
Are you writing extractors or just using youtube-dl as a CLI program?

**Comment by deangelo200** [comment]
Writing an extractor
` with youtube_dl.YoutubeDL(ydl_opts) as ydl:
                    info_dict = ydl.extract_info(url, download=False)
                    video_id = info_dict.get("id", None)
                    video_title = info_dict.get('title', None)
                    video_thumb = info_dict.get('thumbnail',None)
                    context = {
                                'form': form,
                                'title':video_title,
                                'id': video_id,
                                'thumbnails':video_thumb

                    }`

**Comment by yan12125** [comment]
Well, at this level _is_valid_url is not available. Need other approaches. What's your scenario?

**Comment by deangelo200** [comment]
I want to add a feature to my website to let persons download songs but if the person entered an invalid url i want to run some functions

**Comment by yan12125** [comment]
I guess I've got you. Just catch ```ExtractorError``` and analyze it

**Comment by deangelo200** [comment]
How to do this ? Can you give me a short example please

**Comment by yan12125** [comment]
Like this. Do whatever you want to ```e```.
```Python
from youtube_dl.utils import ExtractorError

try:
    info_dict = ydl.extract_info(url, download=False)
except ExtractorError as e:
    print(e)
```

**Comment by deangelo200** [comment]
thanks. if you dont mind can you hit me up a quick email deangeloalmeus@gmail.com

**Comment by deangelo200** [comment]
![image](https://cloud.githubusercontent.com/assets/12830940/21762988/8e827f50-d629-11e6-8782-30c18673d29b.png)
Hey am getting this error instead of getting this error i want to send the user to a page

**Comment by Hrxn** [comment]
How about using Regular Expressions to check? Pretty much the standard way to validate form input.

**Comment by deangelo200** [comment]
I was thinking the same thing but i want to send the users to an error page if their is an error in the url.

**Comment by yan12125** [comment]
Oops I forgot DownloadError wraps ExtractorError. Replace ExtractorError in the previous code with DownloadError

**Comment by deangelo200** [comment]
![image](https://cloud.githubusercontent.com/assets/12830940/21780533/f9ea17c6-d679-11e6-8ada-7f81ba260bd7.png)
Are you familiar with Django

**Comment by deangelo200** [comment]
Dont worry i got it to work thanks guys :)
