### ISSUE TITLE
[watchdisneychannel.go.com] Add support for locked episodes (with TV-Provider login)

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#11640]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.05**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
```
C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe -f best --embed-subs --all-subs --convert-subs srt --username ag316805@gmail.com --password july1987 --ap-username ag316805@gmail.com --ap-password july1987 --ap-mso DTV http://watchdisneychannel.go.com/girl-meets-world/video/vdka3613338/03/19-world-meets-girl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--embed-subs', '--all-subs', '--convert-subs', 'srt', '--username', 'PRIVATE', '--password', 'PRIVATE', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--ap-mso', 'DTV', 'http://watchdisneychannel.go.com/girl-meets-world/video/vdka3613338/03/19-world-meets-girl', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.05
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82889-g54931fd
[debug] Proxy map: {}
[Go] 3613338: Downloading JSON metadata
[Go] 3613338: Downloading JSON metadata
ERROR: Unable to download JSON metadata: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp023qj2d_\build\youtube_dl\extractor\common.py", line 406, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp023qj2d_\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp023qj2d_\build\youtube_dl\utils.py", line 1041, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
```
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://watchdisneychannel.go.com/girl-meets-world/video/vdka3613338/03/19-world-meets-girl'
- Single video: http://watchdisneyxd.go.com/star-wars-rebels/video/vdka3615846/03/11-ghosts-of-geonosis-part-1
- Playlist: http://watchdisneychannel.go.com/disney-mickey-mouse/video/vdka3572406/03/101-duck-the-halls-a-mickey-mouse-christmas-special#playlist=PL551978168

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

PS: It works fine with episodes that doesn't require TV-Provider login, but it doesn't work when you have to.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/11573#issuecomment-269896421
