### ISSUE TITLE
Encoding UTF-8 

### ISSUE THREAD

**Issue by linglung** [rg3/youtube-dl#11650]
I've read many documentations here about utf8, and still i face this issue. 
`youtube-dl --version`
`2017.01.08`

Execute youtube-dl.exe for windows in native windows cmd. 
>youtube-dl -e --encoding utf-8 "https://www.youtube.com/watch?v=E_JXrNAxGzM" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-e', '--encoding', 'utf-8', 'https://www.youtube.com/watch?v=E_JXrNAxGzM', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref utf8
[debug] youtube-dl version 2017.01.08
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-82966-g6993bb4
[debug] Proxy map: {}
27/12/2016 µÖÜΘûôµû░Φü₧ µÑèσ«╢Θº┐τ¢┤µÆ¡τ¥çµëïµ⌐ƒ

it gives strange and wrong output like this
27/12/2016 µÖÜΘûôµû░Φü₧ µÑèσ«╢Θº┐τ¢┤µÆ¡τ¥çµëïµ⌐ƒ

inside of the original title :
 27/12/2016 晚間新聞 楊家駿直播睇手機

While using Git Bash, it gives different wrong output 
27/12/2016 æéæ°è æ¥å®¶é§¿ç´æ­çææ©

>youtube-dl -e --encoding utf-8 "https://www.youtube.com/watch?v=E_JXrNAxGzM" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-e', '--encoding', 'utf-8', 'https://www.youtube.com/watch?v=E_JXrNAxGzM', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref utf-8
[debug] youtube-dl version 2017.01.08
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-82966-g6993bb4
[debug] Proxy map: {}
27/12/2016 æéæ°è æ¥å®¶é§¿ç´æ­çææ©

To solve this in git bash, i have to set the locale options first to utf 8 (Options - text- locale), but not for windows cmd.  

So how to solve this in most generic windows OS without git bash window?  or without set git bash options setting?

**Comment by yan12125** [comment]
Does this work? ```youtube-dl -e "https://www.youtube.com/watch?v=E_JXrNAxGzM" -v```

**Comment by linglung** [comment]
@yan12125  nope.  I already tried that. All unicode title were stripped.
` youtube-dl -e "https://www.youtube.com/watch?v=E_JXrNAxGzM" -v`
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-e', 'https://www.youtube.com/watch?v=E_JXrNAxGzM', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2017.01.08
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-82966-g6993bb4
[debug] Proxy map: {}
27/12/2016

**Comment by linglung** [comment]
Actually seems the output of cmd Windows is correct, tried  to change the font of  cmd windows to  `Lucida console`. It Just couldn't display the actual character. 
 
![correct](https://cloud.githubusercontent.com/assets/16808184/21768843/5004b5ce-d6ae-11e6-8b2e-1bf0c36ebf4f.png)

But when the logs were copied into clipboard and paste here, it's correct. 
So the problem is my CMD windows ? 

youtube-dl -e "https://www.youtube.com/watch?v=E_JXrNAxGzM" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-e', 'https://www.youtube.com/watch?v=E_JXrNAxGzM', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.08
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-82966-g6993bb4
[debug] Proxy map: {}
27/12/2016 晚間新聞 楊家駿直播睇手機

**Comment by yan12125** [comment]
Can you use Chinese fonts in CMD?

Forget git bash - such UNIX emulators never work perfectly in Windows.

**Comment by yan12125** [comment]
By the way, could you also try Python 3.6? It's multi-language support is better than youtube-dl's built-in version (3.4.4)

**Comment by linglung** [comment]
Python installed already 3.6, but didn't know why youtube-dl log said it as 3.4.4 
![python version](https://cloud.githubusercontent.com/assets/16808184/21769552/d7111f0a-d6b1-11e6-89b4-4aed9881aa71.png)

> Can you use Chinese fonts in CMD?

Nope. It shows only box square character. Tried with chcp 6500/1, 1252.  Same result

**Comment by linglung** [comment]
How to use my python installed rather than youtube-dl built in?

**Comment by yan12125** [comment]
> Nope. It shows only box square character. Tried with chcp 6500/1, 1252. Same result

I mean the font dialog in CMD properties. For example, on my machine I can use MingLiU(細明體) to display Chinese characters.

> How to use my python installed rather than youtube-dl built in?

Download the UNIX version at https://github.com/rg3/youtube-dl/releases/download/2017.01.08/youtube-dl and run
```
C:\>python youtube-dl
```

**Comment by linglung** [comment]
Tried it with Unix version 
![unix version](https://cloud.githubusercontent.com/assets/16808184/21770753/2f21675e-d6b7-11e6-8cab-fa2a1d397a99.png)

**Comment by yan12125** [comment]
> out utf-8

This encoding is used for printing things to terminal. As it's already utf-8, the problem is apparently in CMD.

**Comment by yan12125** [comment]
By "font dialog", I meant this dialog. Do you have other choices than Lucida Console? IIRC it's not designed for Chinese so characters may be missing.
![font](https://cloud.githubusercontent.com/assets/1937689/21771167/3e833a42-d6c1-11e6-8949-8d644b0e1981.png)

**Comment by linglung** [comment]
Sadly there is no font like yours. 
![not](https://cloud.githubusercontent.com/assets/16808184/21771462/05cc1f40-d6ba-11e6-8904-5281cbd01069.png)

**Comment by yan12125** [comment]
Some people say that Consolas can display Chinese. If still broken you may want to find how to install additional fonts to CMD.

**Comment by linglung** [comment]
Yes. Great idea. I've already did add more fonts into CMD. And my screenshot above shows it with **courier new** font added , while it's not available before. 
This done after i read your comment, at this point: 
> I mean the font dialog in CMD properties. For example, on my machine I can use MingLiU(細明體) to display Chinese characters.

Now will try it with chinese font.

**Comment by linglung** [comment]
Again, thank you very much @yan12125  after adding chinese font. It works like a charm !! .
Works also with youtube-dl python built in.  

![works](https://cloud.githubusercontent.com/assets/16808184/21773927/5cd74b26-d6c3-11e6-93b9-1dbe79058114.png)

**Comment by yan12125** [comment]
Glad to see that works.

Windows sucks as usual, and this time you overcome it :)

**Comment by Hrxn** [comment]
Windows CMD normally uses codepage 437 or 850, defined by your locale.

You can change it to unicode with `chcp 65001`. Or CMD with `CMD /U`.

For reference: http://ss64.com/nt/chcp.html
