### ISSUE TITLE
cc.com - comedy central fails

### ISSUE THREAD

**Issue by streammonkey** [rg3/youtube-dl#11656]
For the past week or so comedy central (cc.com) has not been working.  The following error gets reported:

>youtube-dl http://www.cc.com/full-episodes/78qqym/-midnight-with-chris-hardwick-extended---thursday--january-5--2017---uncensored-season-4-ep-4042
[ComedyCentralFullEpisodes] 78qqym/-midnight-with-chris-hardwick-extended---thursday--january-5--2017---uncensored-season-4-ep-4042: Downloading webpage
[ComedyCentralFullEpisodes] 78qqym/-midnight-with-chris-hardwick-extended---thursday--january-5--2017---uncensored-season-4-ep-4042: Downloading JSON metadata
[ComedyCentralFullEpisodes] 2d23c620-b85a-11e6-bfd4-0026b9414f30: Downloading info
[ComedyCentralFullEpisodes] 3ac1c111-cfe0-4ee3-ad7e-6bfbcf9472af: Extracting information
[ComedyCentralFullEpisodes] 3ac1c111-cfe0-4ee3-ad7e-6bfbcf9472af: Downloading video urls
[ComedyCentralFullEpisodes] 165d07ce-5349-4c1f-a831-36c4dd59b58a: Extracting information
[ComedyCentralFullEpisodes] 165d07ce-5349-4c1f-a831-36c4dd59b58a: Downloading video urls
[ComedyCentralFullEpisodes] 7d669e02-fbae-4aa8-b9d5-0686504672e9: Extracting information
[ComedyCentralFullEpisodes] 7d669e02-fbae-4aa8-b9d5-0686504672e9: Downloading video urls
[ComedyCentralFullEpisodes] 64eb26b4-fb86-48d1-b347-443b6f186687: Extracting information
[ComedyCentralFullEpisodes] 64eb26b4-fb86-48d1-b347-443b6f186687: Downloading video urls
[download] Downloading playlist: Extended - Thursday, January 5, 2017 - Uncensored
[ComedyCentralFullEpisodes] playlist Extended - Thursday, January 5, 2017 - Uncensored: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

**Comment by japanesephundroid** [comment]
This was [fixed](https://github.com/rg3/youtube-dl/issues/11600) with the latest update, at least for full episodes, try updating youtube-dl.

**Comment by streammonkey** [comment]
Brilliant!  I thought I had updated but apparently something went wrong.

Many thanks.  You guys are the best!
