### ISSUE TITLE
[gaskrank.tv] Please support site (german language motorcycle fun)

### ISSUE THREAD

**Issue by motophil** [rg3/youtube-dl#11659]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.08**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

- [x] Site support request (request for adding support for a new site)

- Single video with HQ button for high resolution video: http://www.gaskrank.tv/tv/motorrad-fun/strike-einparken-durch-anfaenger-crash-mit-groesserem-flurschaden.htm
- Single video without HQ button: http://www.gaskrank.tv/tv/motorrad-fun/motorrad-verladen-ohne-rampe-boss-modus.htm

**Comment by motophil** [comment]
Note: I'm working on this myself right now. First time using git, first time contributing to an open source project, so expect some f-ups. I'll do my best.

**Comment by motophil** [comment]
OK, I got all the way through
https://github.com/rg3/youtube-dl/blob/master/README.md#developer-instructions
and then failed close to the end:

-----------------
phil@main$ git push origin gaskrank
ERROR: Permission to rg3/youtube-dl.git denied to motophil.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
-----------------

Any hint on what's wrong here?

Thanks,

- Philip

**Comment by motophil** [comment]
Pull request added.

**Comment by ThomasChr** [comment]
Added this site. Default download is high quality.

**Comment by yan12125** [comment]
Now it's done. Thanks @motophil!
