### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last) version 2017.01.08

### ISSUE THREAD

**Issue by trongnguyentcec** [rg3/youtube-dl#11664]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.08*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.08**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'hO6kISKcmvY']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2017.01.08
[debug] Python version 2.6.6 - Linux-2.6.32-504.8.1.el6.x86_64-x86_64-with-centos-6.7-Final
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "***/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "***/youtube-dl/youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "***/youtube-dl/youtube_dl/extractor/youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "***/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "***/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "***/youtube-dl/youtube_dl/jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: u'qC'
 (caused by KeyError(u'qC',));
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by aster1sk** [comment]
Using the latest version I'm experiencing the same issue :

```
app_1      | [youtube] OEcBz6VtyDg: Downloading webpage
app_1      | [youtube] OEcBz6VtyDg: Downloading video info webpage
app_1      | [youtube] OEcBz6VtyDg: Extracting video information
app_1      | [youtube] OEcBz6VtyDg: Downloading js player en_US-vflsagga9
app_1      | ERROR: Signature extraction failed: Traceback (most recent call last):
app_1      |   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
app_1      |     video_id, player_url, s
app_1      |   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function
app_1      |     cache_res = res(test_string)
app_1      |   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 984, in <lambda>
app_1      |     return lambda s: initial_function([s])
app_1      |   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 254, in resf
app_1      |     res, abort = self.interpret_statement(stmt, local_vars)
app_1      |   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
app_1      |     v = self.interpret_expression(expr, local_vars, allow_recursion)
app_1      |   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 174, in interpret_expression
app_1      |     return obj[member](argvals)
app_1      | KeyError: u'qC'
app_1      |  (caused by KeyError(u'qC',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Using arguments :

```
@gen.coroutine
def download(**kwargs):
    url = kwargs.get('url')
    logging.info("DOWNLOADING URL FROM : %s" % url)
    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': '/library/%(title)s.%(ext)s',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '128',
        }],
        'progress_hooks': [download_hook],
    }
    with YoutubeDL(ydl_opts) as ydl :
        ydl.download([url])

```

Happy to provide more information.

**Comment by yan12125** [comment]
See #11663
