### ISSUE TITLE
[aenetworks] Playlists no longer work

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#11669]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.10**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
E:\>youtube-dl.exe --download-archive D:\scripts\Auto-TV-Download\archive.txt --restrict-filenames --continue --no-check-certificate --ignore-errors --verbose -o Duck.Dynasty.S11E%(episode_number)s.%(title)s.mp4 "http://www.aetv.com/shows/duck-dynasty/season-11"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--download-archive', 'D:\\scripts\\Auto-TV-Download\\archive.txt', '--restrict-filenames', '--continue', '--no-check-certificate', '--ignore-errors', '--verbose', '-o', 'Duck.Dynasty.S11E%(episode_number)s.%(title)s.mp4', 'http://www.aetv.com/shows/duck-dynasty/season-11']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.10
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[aenetworks] duck-dynasty/season-11: Downloading webpage
[download] Downloading playlist: 237816358703
[aenetworks] playlist 237816358703: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: 237816358703
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Playlist: http://www.aetv.com/shows/duck-dynasty/season-11

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Season playlists no longer work.  Individual episode links (http://www.aetv.com/shows/duck-dynasty/season-11/episode-1) do still download.

**Comment by ldexterldesign** [comment]
Hey,

Thanks for software

+1

The following options still generate output but it's not correct:

```
playlist: Name or id of the playlist that contains the video
playlist_index: Index of the video in the playlist padded with leading zeros according to the total length of the playlist
playlist_id: Playlist identifier
playlist_title: Playlist title
```

For example, use of ``playlist``, despite the channel/user having >1 playlist, will only generate "Uploads from [channel/user]"

Let me know if you have any issues - happy to help

Hope this is clear/useful

Hope to hear back

Yours faithfully

**Comment by ldexterldesign** [comment]
BUMP

**Comment by yan12125** [comment]
@StevenDTX Seems it's working:
```
$ youtube-dl -F "http://www.aetv.com/shows/duck-dynasty/season-11" -i 
[aenetworks] duck-dynasty/season-11: Downloading webpage
[download] Downloading playlist: 237816358703
[aenetworks] playlist 237816358703: Collected 10 video ids (downloading 10 of them)
[download] Downloading video 1 of 10
[aenetworks] duck-dynasty/season-11/episode-10: Downloading webpage
[aenetworks] 857518147873: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
[download] Downloading video 2 of 10
[aenetworks] duck-dynasty/season-11/episode-9: Downloading webpage
[aenetworks] 852662851814: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
[download] Downloading video 3 of 10
[aenetworks] duck-dynasty/season-11/episode-8: Downloading webpage
[aenetworks] 846659651858: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
[download] Downloading video 4 of 10
[aenetworks] duck-dynasty/season-11/episode-7: Downloading webpage
[aenetworks] 840682563950: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
[download] Downloading video 5 of 10
[aenetworks] duck-dynasty/season-11/episode-6: Downloading webpage
[aenetworks] 838609475799: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
[download] Downloading video 6 of 10
[aenetworks] duck-dynasty/season-11/episode-5: Downloading webpage
[aenetworks] 832971843969: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
[download] Downloading video 7 of 10
[aenetworks] duck-dynasty/season-11/episode-4: Downloading webpage
[aenetworks] 826268739822: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
[download] Downloading video 8 of 10
[aenetworks] duck-dynasty/season-11/episode-3: Downloading webpage
[aenetworks] 816759875563: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
[download] Downloading video 9 of 10
[aenetworks] duck-dynasty/season-11/episode-2: Downloading webpage
[aenetworks] 815180355674: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
[download] Downloading video 10 of 10
[aenetworks] duck-dynasty/season-11/episode-1: Downloading webpage
[aenetworks] 810485827672: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
[download] Finished downloading playlist: 237816358703
```
I don't have an Adobe Pass account so I can't download it. At least 10 episodes are recognized correctly. Are you still encountering problems?

@ldexterldesign Sounds a different problem. If you think it's a bug/missing feature, please open a new issue and describe your expectations and actual results.

**Comment by remitamine** [comment]
i guess locked issues can't be closed from commit message, this is a problem, i think it affect some of the other commits as well.

**Comment by StevenDTX** [comment]
I thought I saw a note about this working a couple of versions ago, but now I cannot find where that was posted.

It is working now.  Thanks!

**Comment by ldexterldesign** [comment]
Apologies for delay

Ignore https://github.com/rg3/youtube-dl/issues/11669#issuecomment-271834583 - I was using syntax incorrectly for my requirement (i.e. give me a user's videos organised by playlist)

I expected playlist criteria to output in the file name but it actually outputs in the folder structure, so something like this works for me:

```youtube-dl -o '%(playlist)s/%(playlist_index)s - %(upload_date)s - %(title)s.%(ext)s' [url] --ignore-errors --playlist-reverse```

Hope this is clear/useful

Regards
