### ISSUE TITLE
YouTube SSL certificate verify failure (python?)

### ISSUE THREAD

**Issue by Denon7** [rg3/youtube-dl#11661]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.08*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.08**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

Hi, very recently youtube-dl gives me this error everytime I use it. Can someone please help to solve this? What can I do to fix it please? I installed python 3.6 hoping to fix it but still doing it.

"J:\_Food Videos\_Chinese\Happy Wok>youtube-dl -cit -v -f bestvideo+bestaudio "ht
tps://www.youtube.com/channel/UCaUR4ViaAVLLzKQ2ex6u1Sg" --download-archive FILE.
txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-cit', '-v', '-f', 'bestvideo+bestaudio', 'https://
www.youtube.com/channel/UCaUR4ViaAVLLzKQ2ex6u1Sg', '--download-archive', 'FILE.t
xt']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.08
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-80924-gb450b82
[debug] Proxy map: {}
[youtube:channel] UCaUR4ViaAVLLzKQ2ex6u1Sg: Downloading channel page
WARNING: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAI
LED] certificate verify failed (_ssl.c:600)>
[youtube:channel] UCaUR4ViaAVLLzKQ2ex6u1Sg: Downloading page #1
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILE
D] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL
: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\bu
ild\youtube_dl\extractor\common.py", line 406, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\bu
ild\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\bu
ild\youtube_dl\utils.py", line 1041, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open

J:\_Food Videos\_Chinese\Happy Wok>pause
Press any key to continue . . ."

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/11573#issuecomment-269896421
