### ISSUE TITLE
ERROR: Signature extraction failed (latest youtube-dl version)

### ISSUE THREAD

**Issue by adrianTNT** [rg3/youtube-dl#11665]
I am getting these errors, program version seems to be latest:

`[root@h1 httpdocs]# youtube-dl --version`

> 2017.01.08

`youtube-dl https://www.youtube.com/watch?v=IqepOwZWdNM`

> [youtube] IqepOwZWdNM: Downloading webpage
> [youtube] IqepOwZWdNM: Downloading video info webpage
> [youtube] IqepOwZWdNM: Extracting video information
> [youtube] IqepOwZWdNM: Downloading js player en_US-vflsagga9
> ERROR: Signature extraction failed: Traceback (most recent call last):
>   File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
>     video_id, player_url, s
>   File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function
>     cache_res = res(test_string)
>   File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 984, in <lambda>
>     return lambda s: initial_function([s])
>   File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
>     res, abort = self.interpret_statement(stmt, local_vars)
>   File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
>     v = self.interpret_expression(expr, local_vars, allow_recursion)
>   File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 174, in interpret_expression
>     return obj[member](argvals)
> KeyError: u'qC'
>  (caused by KeyError(u'qC',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by adrianTNT** [comment]
Even thou I had --version showing latest version, I had to do a `yum remove youtube-dl.noarch`
