### ISSUE TITLE
Only download videos shorter/longer than X time/length/duration. FEATURE REQUEST

### ISSUE THREAD

**Issue by sirylj** [rg3/youtube-dl#11675]
I searched through the readme before posting this and didn't find anything.

Can you add an option similar to --dateafter/--datebefore for the length of the video/recording?

eg.
--morethan 5m or --morethan 600s (Only download videos longer than 5 minutes)

--lessthan 5m or --lessthan 600s (Only download videos shorter than 5 minutes)

**Comment by dstftw** [comment]
`--match-filter 'duration < 600'`/`--match-filter 'duration > 600'`.

**Comment by sirylj** [comment]
Ah, sorry, I didn't notice the match filter option when searching for length/duration/time. Thank you very much for the help!
