### ISSUE TITLE
Can't read the source of HTML? Error in Python code lines.

### ISSUE THREAD

**Issue by rmbeer** [rg3/youtube-dl#11672]
$ youtube-dl https://www.youtube.com/watch?v=QcErRVXRSK8
[youtube] QcErRVXRSK8: Downloading webpage
[youtube] QcErRVXRSK8: Downloading video info webpage
[youtube] QcErRVXRSK8: Extracting video information
[youtube] QcErRVXRSK8: Downloading js player en_US-vflsagga9
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

This result is all that have.

**Comment by apollo11w** [comment]
This error looks like mine, I will compare them with Meld

**Comment by sleibrock** [comment]
Same error with version 2016.12.22. Might be a result of some YouTube update.

**Comment by jorgicio** [comment]
The same error. Tried with 2016.12.22, 2016.12.31 and 2017.01.05.
Yes, It may be some YouTube update.

**Comment by apollo11w** [comment]
Yeah I pretty much got the same error, but I yaourt -Syu'd to version 2017-01-10 and now it's working.

**Comment by sleibrock** [comment]
Yep, that'll do it. I just ran `pip install --upgrade youtube-dl` and it's fine on 2017.01.10

**Comment by apollo11w** [comment]
Pip? Nuuuuu you must accept pacman as your lord and savior!

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by apollo11w** [comment]
@dstftw Thank you guys for keeping Youtube-dl up to date!

**Comment by peterdolan** [comment]
Thanks guys! Appreciate the help!
