### ISSUE TITLE
Daily Motion gives lots of "Content too short" errors

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#11673]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.08*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.08**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ x] Other
Bug / issue with a specific site
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
keybounceMBP:Mlp michael$ youtube-dl -v http://www.dailymotion.com/video/x55wjj8_my-little-pony-fim-s03e03-too-many-pinkie-
pies_fun
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=480]/\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--write-sub', u'--write-auto-sub', u'--sub-lang', u'en,enUS', u'--sub-format', u'srt/ass/best', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.dailymotion.com/video/x55wjj8_my-little-pony-fim-s03e03-too-many-pinkie-pies_fun']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.08
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] x55wjj8: Downloading webpage
WARNING: unable to extract comment count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[dailymotion] x55wjj8: Downloading m3u8 information
[dailymotion] x55wjj8: Downloading m3u8 information
[dailymotion] x55wjj8: Downloading m3u8 information
[dailymotion] x55wjj8: Downloading m3u8 information
[dailymotion] x55wjj8: Downloading m3u8 information
[dailymotion] x55wjj8: Downloading m3u8 information
[dailymotion] x55wjj8: Downloading m3u8 information
WARNING: enUS subtitles not available for x55wjj8
[info] Writing video subtitles to: My Little Pony - FiM S03E03 - Too Many Pinkie Pies.en.srt
[debug] Invoking downloader on u'https://www.dailymotion.com/cdn/H264-848x480/video/x55wjj8.mp4?auth=1484291075-2562-bbq230w0-0f0041a342fc8426a86271417b3b6de8'
[download] Resuming download at byte 31455605
[download] Destination: My Little Pony - FiM S03E03 - Too Many Pinkie Pies.mp4
[download]  27.1% of 131.13MiB at 102.54KiB/s ETA 15:54ERROR: content too short (expected 137501817 bytes and served 37330415)
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/Users/michael/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/Users/michael/bin/youtube-dl/youtube_dl/downloader/http.py", line 238, in real_download
    raise ContentTooShortError(byte_counter, int(data_len))
ContentTooShortError

```

On Daily Motion, I get lots of "ContentTooShort" errors. I never have issues playing back in my browser.

Searching only turned up an issue from 2013. The work-around in that thread was to use "until youtube-dl ; do sleep 5; done". That works, but I'm wondering if something can be done to improve this site because of the large frequency of the issue.

**Comment by dstftw** [comment]
Works fine for me. Most likely it's a connectivity issue between you and dailymotion.

>I never have issues playing back in my browser.

Browser uses hls by default.
