### ISSUE TITLE
Provide a way to choose the best resolution

### ISSUE THREAD

**Issue by utack** [rg3/youtube-dl#11686]
Hi,
currently there seems to be no way of choosing the best resolution video.
Example: I'd like vp9 where possible from Youtube, but would take a 480p H264 stream over the 360p VP9 stream.
Is there a method to achieve this?
If not, it would be great if you could provide something to pick the best resolution video.

Thank you

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

**Comment by jdmoore0883** [comment]
try running:
youtube-dl -f bestvideo "<YOUTUBE_URL>"

**Comment by utack** [comment]
That works, but unfortunately it ignores the codec preference. For cases where 1080p H264 and VP9 are available it chooses H264

**Comment by shizeeg** [comment]
try to add `--prefer-free-formats` to your `youtube-dl` command line parameters

**Comment by utack** [comment]
Unfortunately the prefer free formats option applied to youtube-dl in mpv still chooses the 360p version

**Comment by linglung** [comment]
You want to select best available format? why didn't use `youtube-dl -F ` to check it first before downloading? then pick `-f number`

**Comment by utack** [comment]
>You want to select best available format? why didn't use youtube-dl -F to check it first before downloading? then pick -f number  
  
Thanks for letting me know, but I read the docs and realized that works  
Unfortunately it does not solve the problem the format stream should be able to automatically sort out the one that is best by certain criteria, like for example has the highest resolution. I watch 30+ youtube videos a day starting mpv and youtube-dl from a browser plugin, sorting them out manually is not an option

**Comment by shizeeg** [comment]
>> Unfortunately the prefer free formats option applied to youtube-dl in mpv still chooses the 360p version

@utack you can pass `youtube-dl` parameters using `mpv`'s `--ytdl-raw-options` or `--ytdl-format` like that:
`$ mpv --ytdl-format=bestvideo --ytdl-raw-options='--prefer-free-formats='`
take a note of final `=`

**Comment by yan12125** [comment]
> I'd like vp9 where possible from Youtube, but would take a 480p H264 stream over the 360p VP9 stream.

Sounds like you want to compare resolutions first and then video codecs. That's a missing feature, see #6018.

**Comment by fireattack** [comment]
@yan12125 Is there any way to compare resolution first, then video _bitrate_ (I don't care codecs)?

**Comment by dstftw** [comment]
Not possible.

**Comment by livelybit** [comment]
> Is there any way to compare resolution first, then video _bitrate_ (I don't care about codecs)? Because you know, sometimes the higher resolution ones have lower bitrates.

@dstftw it's been quite some time, is this still true as of today? Are there workarounds (ignoring bitrate altogether)?
