### ISSUE TITLE
Have i been blocked form using this.

### ISSUE THREAD

**Issue by xorenio** [rg3/youtube-dl#11690]
![image](https://cloud.githubusercontent.com/assets/11992984/21886153/6315f5be-d8b2-11e6-8217-31331b904e97.png)

I keep getting this message each time. I have this setup to run hourly I wouldn't have thought that would have been classed as spam

**Comment by dstftw** [comment]
1. https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required
2. #5138.
