### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last):   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1006, in _decrypt_signature     video_id, player_url, s   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 933, in _extract_signature_function     cache_res = res(test_string)   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 985, in <lambda>     return lambda s: initial_function([s])   File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf     res, abort = self.interpret_statement(stmt, local_vars)   File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement     v = self.interpret_expression(expr, local_vars, allow_recursion)   File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 174, in interpret_expression     return obj[member](argva

### ISSUE THREAD

**Issue by shivamzaz** [rg3/youtube-dl#11692]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.10**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.01.10
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by linglung** [comment]
Working fine here with latest version same as yours (2017.01.10),  just it's python 3.4.4 built in. 
btw, can you edit and short your title of your issue, please?
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.youtube.com/watch?v=BaW_jenozKcj', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2017.01.10
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-82966-g6993bb4
[debug] Proxy map: {}
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading video info webpage
[youtube] BaW_jenozKc: Extracting video information
[youtube] BaW_jenozKc: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r3---sn-npoeen7d.googlevideo.com/videoplayback?id=05a5bf8de9e8cca7&itag=137&source=youtube&requiressl=yes&mm=31&mv=m&ms=au&initcwndbps=6627500&pl=18&mn=sn-npoeen7d&nh=IgpwcjAyLnNpbjExKg03NC4xMjUuNTEuMTcz&ratebypass=yes&mime=video/mp4&gir=yes&clen=2208750&lmt=1387961822987808&dur=9.800&signature=1575318CF2763653FBDD3D4531F43967368B4B47.6303611335E1E6183FAA72B42F70C77831D19D37&key=dg_yt0&mt=1484266548&upn=qoNsd7npI58&ip=128.199.217.235&ipbits=0&expire=1484288375&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mv,ms,initcwndbps,pl,mn,nh,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: youtube-dl test video ''_▒-BaW_jenozKc.f137.mp4
[download] 100% of 2.11MiB in 00:03
[debug] Invoking downloader on 'https://r3---sn-npoeen7d.googlevideo.com/videoplayback?id=05a5bf8de9e8cca7&itag=251&source=youtube&requiressl=yes&mm=31&mv=m&ms=au&initcwndbps=6627500&pl=18&mn=sn-npoeen7d&nh=IgpwcjAyLnNpbjExKg03NC4xMjUuNTEuMTcz&ratebypass=yes&mime=audio/webm&gir=yes&clen=190742&lmt=1422348740429751&dur=9.841&signature=8F017070F73C65DE53D8BEE56673C225101A8ED4.1EAE6A8AC36E62BD35EE04E407409E8A1749E46E&key=dg_yt0&mt=1484266548&upn=qoNsd7npI58&ip=128.199.217.235&ipbits=0&expire=1484288375&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mv,ms,initcwndbps,pl,mn,nh,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: youtube-dl test video ''_▒-BaW_jenozKc.f251.webm
[download] 100% of 186.27KiB in 00:00
[ffmpeg] Merging formats into "youtube-dl test video ''_▒-BaW_jenozKc.mkv"
[debug] ffmpeg command line: ffmpeg -y -i 'file:youtube-dl test video '"'"''"'"'_▒-BaW_jenozKc.f137.mp4' -i 'file:youtube-dl test video '"'"''"'"'_▒-BaW_jenozKc.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:youtube-dl test video '"'"''"'"'_▒-BaW_jenozKc.temp.mkv'
Deleting original file youtube-dl test video ''_▒-BaW_jenozKc.f137.mp4 (pass -k to keep)
Deleting original file youtube-dl test video ''_▒-BaW_jenozKc.f251.webm (pass -k to keep)

```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
