### ISSUE TITLE
Wrapper for other languages

### ISSUE THREAD

**Issue by devkhan** [rg3/youtube-dl#11691]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.10**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description

Are there any (usable) binding to other languages of `yt-dl`, specifically C#?

I want to get buffered video, either by streaming directly or to a file, and use that in a C# application. Right now, the only option seems to run the CLI tool. Is there any other way?

Is this even a good enough approach? The end goal here is to be able to play the stream or file in the app. So, calling the CLI with so many options can get messy(needs to be x-platform), a nice and clean API (may be a DLL) would be nice. If one doesn't exists, I'm eager to take up the initiative if someone can guide through the workings of yt-dl.

PS: There's [this](https://github.com/detaybey/WrapYoutubeDl), but outdated. 😞

**Comment by yan12125** [comment]
Out of the scope for a pure Python project. Of course you can write one or improving existing projects and advertise your results here.

In general, two approach for writing a wrapper:

1. Use the CLI interface
2. Use the Python API with C#-Python bridge. I've heard IronPython but never tried it

The first approach is easier to write, while the second approach provides more flexibility.
