### ISSUE TITLE
[nick.com] Force HLS like CC.com

### ISSUE THREAD

**Issue by Transcodes** [rg3/youtube-dl#11700]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v  http://www.nick.com/videos/clip/the-loud-house-101-full-episode.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.nick.com/videos/clip/the-loud-house-101-full-episode.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.10
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-83034-gf48b6b8, ffprobe N-83034-gf48b6b8
[debug] Proxy map: {}
[nick.com] the-loud-house-101-full-episode.html: Downloading webpage
[nick.com] 9859a898-5d33-11e5-8ff7-0026b9414f30: Downloading info
[nick.com] e9eff1f2-0be4-11e6-8a89-0026b9414f30: Extracting information
[nick.com] e9eff1f2-0be4-11e6-8a89-0026b9414f30: Downloading video urls
[nick.com] e9eea158-0be4-11e6-8a89-0026b9414f30: Extracting information
[nick.com] e9eea158-0be4-11e6-8a89-0026b9414f30: Downloading video urls
[nick.com] e9ed5dc0-0be4-11e6-8a89-0026b9414f30: Extracting information
[nick.com] e9ed5dc0-0be4-11e6-8a89-0026b9414f30: Downloading video urls
[nick.com] e9ebf5c0-0be4-11e6-8a89-0026b9414f30: Extracting information
[nick.com] e9ebf5c0-0be4-11e6-8a89-0026b9414f30: Downloading video urls
[download] Downloading playlist: The Loud House: "Left in the Dark/Get the Message"
[nick.com] playlist The Loud House: "Left in the Dark/Get the Message": Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
[debug] Invoking downloader on 'http://viacommtvstrmfs.fplive.net/gsp.alias/mediabus/kids/.com/2016/04/26/03/31/33/ffd3b2aae6ad42d88256eac44df40dbf/916687/abcY2EksRB_HDLDH101A1_916687_5960829_1920x1080_5128.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\YoutubeDL.py", line 1699, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\YoutubeDL.py", line 1641, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\downloader\common.py", line 353, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.nick.com/videos/clip/the-loud-house-101-full-episode.html
http://www.nick.com/videos/clip/the-loud-house-204-full-episode.html

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Used U.S IP
http://www.nick.com/videos/clip/the-loud-house-101-full-episode.html
does not require authentication
plays fine on browser

still not able to download videos using youtube-dl
https://cp479184-vh.akamaihd.net/i/mtvnorigin/gsp.alias/mediabus/kids/.com/2016/04/26/03/30/27/5ab56259748d479c8f42055a1c8bde68/916689/voF8P8bypN_HDLDH101A3_916689_5960829_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil/index_6_av.m3u8

Nick.com  should work when cc.com does(both use same source)
but nick.com still fails to download any video

I tried these commands
still no luck
  --hls-prefer-native              Use the native HLS downloader instead of ffmpeg
    --hls-prefer-ffmpeg              Use ffmpeg instead of the native HLS downloader
    --hls-use-mpegts

Force HLS in nick.py
switch to m3u8/akamai from viacommtvstrmfs.fplive.net on all scripts

In 2017, all switched from fplive , update all the scripts to reflect changes

disable' import MTVServicesInfoExtractor' in nick.py
ComedyCentral now works after the recent commit ,apply the same to nick

http://www.nick.com/videos/clip/the-loud-house-204-full-episode.html

**Comment by dstftw** [comment]
This is already fixed.

**Comment by Transcodes** [comment]
@dstftw Have you tried to download
"http://www.nick.com/videos/clip/the-loud-house-101-full-episode.html" using youtube-dl ?

It keeps fetching viacommtvstrmfs.fplive.net urls which do not exist
fails to retrieve subs too

please provide ' alternative m3u8' as default
thanks

**Comment by dstftw** [comment]
This is fixed in master. Wait for the next release or run from sources.
