### ISSUE TITLE
cbc.ca: Page with multiple videos, downloads only one

### ISSUE THREAD

**Issue by iwsbarker** [rg3/youtube-dl#11704]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.10**

- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

- [x] Feature request (request for a new functionality)

An example page with multiple videos is: http://www.cbc.ca/news/canada/calgary/dog-indoor-exercise-winter-1.392823

Note: There are similar feature requests for other sites, but they all seem to be specific to those sites, so I'm submitting this feature request for the cbc.ca site.

**Comment by dstftw** [comment]
http://www.cbc.ca/news/canada/calgary/dog-indoor-exercise-winter-1.392823 redirects to http://www.cbc.ca/news/canada/calgary/halifax-smokers-boxed-in-1.392823 that contains no videos at all.

**Comment by iwsbarker** [comment]
Apologies. I left off the last digit of the URL:
http://www.cbc.ca/news/canada/calgary/dog-indoor-exercise-winter-1.3928238

**Comment by iwsbarker** [comment]
I just updated my version of youtube-dl to 2017.01.14, but it still doesn't download the multiple videos on the sample page I mentioned.

**Comment by dstftw** [comment]
It's not released.

**Comment by iwsbarker** [comment]
I tested with the latest release (2017.01.16) and it works great. Thanks!
