### ISSUE TITLE
ERROR: Unable to download webpage:

### ISSUE THREAD

**Issue by wukongtea** [rg3/youtube-dl#11714]
dont work  in viki.com  or dramfever.com
https://www.viki.com/videos/1113149v-romantic-doctor-kim-episode-18  
ERROR:
youtube-dl.exe --all-formats https://www.viki.com/videos/1113149v-romantic-doctor-kim-episode-18
[generic] Doctor_Romantic: Requesting header
WARNING: Could not send HEAD request to https://www.viki.com/videos/1113149v-romantic-doctor-kim-episode-18: ''
[generic] Doctor_Romantic: Downloading webpage
ERROR: Unable to download webpage: '' (caused by BadStatusLine("''",)); please r
eport this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --ve
rbose flag and include its complete output.

**Comment by wukongtea** [comment]
https://www.dramafever.com/zh-cn/drama/4972/15/Doctor_Romantic/
it also doesn't work.  can  you fix the problem  from  viki.con  and dramafever.com.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
