### ISSUE TITLE
apt-get package out of date

### ISSUE THREAD

**Issue by arderyp** [rg3/youtube-dl#11713]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [I have on a pip installed version, and it works perfectly fine]  I've **verified** and **I assure** that I'm running youtube-dl **2017.01.14**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [X ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
```
...
```
---
---

### Description of your *issue*, suggested solution and other information

I installed youtube-dl via `sudo apt-get update && sudo apt-get install youtube-dl`.  The package installed, but is quite out of date. Attempting to force update it via apt-get causes apt-get to inform me that my package is already up to date:

```
$ date
Fri Jan 13 23:17:19 PST 2017
$ youtube-dl --version
2016.02.22
$ sudo apt-get update && sudo apt-get upgrade youtube-dl
Ign:1 ...
Hit:2 ...
Ign:3 ...
Hit:4 ...
Hit:5 ...
Hit:6 ...
Hit:7 ...
Hit:8...
Hit:9 ...
Hit:11 ...
Hit:13 ...
Reading package lists... Done 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
youtube-dl is already the newest version (2016.02.22-1).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

I am successfully able to download/install/update youtube-dl through pip, but just want to make you aware of the apt issue, if you are still hoping to serve current packaged through it.  Or, if pip is the only supported provider on linux, then I suppose you can close this issue.

**Comment by dstftw** [comment]
>if you are still hoping to serve current packaged through it

We are not serving packages through it and we are not anyhow affiliated with your distro's software repository. It's maintained by your distro package maintainers not us. This is clearly stated in FAQ.
