### ISSUE TITLE
it's hard to download this video

### ISSUE THREAD

**Issue by thrt** [rg3/youtube-dl#11712]
it's hard to download this video
when i use format h5/h4-0/h3
>youtube-dl.exe -F http://v.youku.com/v_show/id_XMTQyNjc2NjgyOA==.html
[youku] XMTQyNjc2NjgyOA: Downloading JSON metadata
[download] Downloading playlist: 【怪咖搞笑】盘点2015各国疯狂挑战大合集
[youku] playlist 【怪咖搞笑】盘点2015各国疯狂挑战大合集: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
[info] Available formats for XMTQyNjc2NjgyOA_part1:
format code  extension  resolution note
h5           mp4        512x288    26.00MiB
h4-0         flv        512x288    14.39MiB
h3           mp4        672x378    26.26MiB
h4-1         flv        1104x622   29.92MiB (best)
[download] Downloading video 2 of 4
[info] Available formats for XMTQyNjc2NjgyOA_part2:
format code  extension  resolution note
h4-0         flv        512x288    10.35MiB
h3           mp4        672x378    21.16MiB
h4-1         flv        1104x622   30.01MiB (best)
[download] Downloading video 3 of 4
[info] Available formats for XMTQyNjc2NjgyOA_part3:
format code  extension  resolution note
h4           flv        1104x622   25.22MiB
[download] Downloading video 4 of 4
[info] Available formats for XMTQyNjc2NjgyOA_part4:
format code  extension  resolution note
h4           flv        1104x622   18.40MiB
[download] Finished downloading playlist: 【怪咖搞笑】盘点2015各国疯狂挑战大合集

>youtube-dl.exe -f h4-0 http://v.youku.com/v_show/id_XMTQyNjc2NjgyOA==.html
[youku] XMTQyNjc2NjgyOA: Downloading JSON metadata
[download] Downloading playlist: 【怪咖搞笑】盘点2015各国疯狂挑战大合集
[youku] playlist 【怪咖搞笑】盘点2015各国疯狂挑战大合集: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
[download] Destination: 【怪咖搞笑】盘点2015各国疯狂挑战大合集-XMTQyNjc2NjgyOA_part1.flv
[download] 100% of 14.39MiB in 00:28
[download] Downloading video 2 of 4
[download] Destination: 【怪咖搞笑】盘点2015各国疯狂挑战大合集-XMTQyNjc2NjgyOA_part2.flv
[download] 100% of 10.35MiB in 00:17
[download] Downloading video 3 of 4
ERROR: requested format not available

**Comment by dstftw** [comment]
`-f '[format_id^=h4]'`.

**Comment by thrt** [comment]
Yup , i try it [youtube-dl.exe -f h4-0 http://v.youku.com/v_show/id_XMTQyNjc2NjgyOA==.html] correctly. but i still receive an error message => ERROR: requested format not available

**Comment by dstftw** [comment]
What is not clear in the error message?
