### ISSUE TITLE
Youtube-dl binary becomes 0 byte file. Re-surface of an old issue

### ISSUE THREAD

**Issue by 1001jesussmith1001** [rg3/youtube-dl#11710]
I cannot submit any youtube-dl output as the file becomes a 0 byte binary and i get the message:

 "youtube-dl.exe is not a valid Win32 application"

it seems to be the same as this issue from Sep 6, 2013 marked as closed:

https://github.com/rg3/youtube-dl/issues/1379

note: I am running win 7 professional with no updates and the standard in the box service pack -- i run the latest 2016-2017 CAD software without problems -- i have no issues with any other programs ---

*THE FIX* is to simply copy and replace the 0 byte youtube-dl binary with the latest  youtube-dl binary exe file. 

"C:\yl>youtube-dl.exe  --version
2017.01.10"

**Comment by dstftw** [comment]
What makes it become 0 bytes file? What did you do to achieve that?

**Comment by RuneMagle** [comment]
Happens to me to sometimes, but I honestly don't know why. But I just re-download latest version.

**Comment by dstftw** [comment]
Closing due to no response.
