### ISSUE TITLE
I can not get the link google drive

### ISSUE THREAD

**Issue by haibk** [rg3/youtube-dl#11723]
Hi Team!
I use the latest version youtube-dl.
I can not get link on google drivers. Specifically I run:
youtube-dl -j https://drive.google.com/file/d/0B4tqnk-1ANICRGZMeFRvUDUtazA
I get the link: https://r1---sn-i3b7knek.c.docs.google.com/videoplayback?requiressl=yes&id=547a3a15843f95f7&itag=18&source=webdrive&ttl=transient&app=texmex&ip=123.31.43.86&ipbits=0&expire=1484472838&cp= QVJNVkVfUVhRSVhNOmd1WGZWa0xHNWM2 & sparams = requiressl% 2Cid% 2Citag% 2Csource% 2Cttl% 2Cip% 2Cipbits% 2Cexpire% 2Ccp% 2Caol% 2Cinitcwndbps% 2Cmm% 2Cmn% 2Cms% 2Cmv% 2Cnh% 2Cpl & signature = 4CFDF90F47C034CD2E78509194A3CA66DA71A27F.B615765C503A7F27DA976FEC65A0AD3352DCFFDF & key = CK2 & aol = yes & initcwndbps = 5000000 & mm = 30 & mn = sn- i3b7knek & ms = 1484458410 & nxu & mt = mv = u & pl = nh = IgpwcjA0LmhrZzAxKgkxMjcuMC4wLjE & 24
But I can not play this link! Error message does not have access (Error: 403)
I have configured the video sharing on the internet public. Please tell me how can I get the link to download and play the video.
Thanks you!

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-webbrowser
#10905
