### ISSUE TITLE
upload youtube_dl

### ISSUE THREAD

**Issue by mdoulabi** [rg3/youtube-dl#11725]
what patch youtube_dl folder for reading python script?

**Comment by yan12125** [comment]
> what patch youtube_dl folder for reading python script?

What does that mean? Could you describe more about your scenario and your needs?

**Comment by yan12125** [comment]
Closing as no response for a long time.

**Comment by mdoulabi** [comment]
i have problem , i have not centos learning
i should compile python files for youtube-dl?
i dont undrestand extractor folder should copy in /usr/bin?
what work ??
