### ISSUE TITLE
Download error for some Banccamp albums

### ISSUE THREAD

**Issue by desbma** [rg3/youtube-dl#11727]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

--

For some Bandcamp albums (like [this one](https://insulters.bandcamp.com/album/we-are-the-plague)), youtube-dl throws an error, although the album is playable on the page without issues. For most other Bandcamp URLs, everything works fine.

    $ youtube-dl -v 'https://insulters.bandcamp.com/album/we-are-the-plague'
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: ['-v', 'https://insulters.bandcamp.com/album/we-are-the-plague']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2017.01.14
    [debug] Python version 3.6.0 - Linux-4.4.42-1-lts-x86_64-with-arch
    [debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
    [debug] Proxy map: {}
    [Bandcamp:album] we-are-the-plague: Downloading webpage
    [download] Downloading playlist: WE ARE THE PLAGUE
    [Bandcamp:album] playlist WE ARE THE PLAGUE: Collected 11 video ids (downloading 11 of them)
    [download] Downloading video 1 of 11
    [Bandcamp] intro: Downloading webpage
    [Bandcamp] 871370034: Downloading free downloads page
    ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/home/maxime/py-venvs/tmp-bf7736bb155aaf0/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
        ie_result = ie.extract(url)
      File "/home/maxime/py-venvs/tmp-bf7736bb155aaf0/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 359, in extract
        return self._real_extract(url)
      File "/home/maxime/py-venvs/tmp-bf7736bb155aaf0/lib/python3.6/site-packages/youtube_dl/extractor/bandcamp.py", line 141, in _real_extract
        self._sort_formats(formats)
      File "/home/maxime/py-venvs/tmp-bf7736bb155aaf0/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 926, in _sort_formats
        raise ExtractorError('No video formats found')
    youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Thanks for the report. It's because that youtube-dl mistreat tracks without songs as real tracks. It will be fixed in the next version.

**Comment by desbma** [comment]
Thanks for the fix
