### ISSUE TITLE
Changes to NBC News site

### ISSUE THREAD

**Issue by ddurdle** [rg3/youtube-dl#11736]
Example:

http://tvenbcnews.nbcuni.com/now/dateline/full-episode/after-the-storm/855288387677

[generic] 855288387677: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 855288387677: Downloading webpage
[generic] 855288387677: Extracting information
ERROR: Unsupported URL

**Comment by StevenDTX** [comment]
FYI...

They download just fine from the nbc.com site:  http://www.nbc.com/dateline/episodes

http://www.nbc.com/dateline/video/vanished/3445907

**Comment by ddurdle** [comment]
They post episodes on the dateline show site and on the news site.  The dateline show site is usually 1+ month late.

Up until this week, the news site used to be nbcnews.com in the URL, but it looks like they revamped the site and changed the URLs

**Comment by yan12125** [comment]
Duplicate of #2947
