### ISSUE TITLE
Downloading video and audio files????

### ISSUE THREAD

**Issue by srburnzy** [rg3/youtube-dl#11739]
Ok, I downloaded youtube-dl, created and tested a batch file to download video files from my YouTube playlists.  Next, I wanted to extract audio from the video files in my playlist. So I downloaded FFmpeg.  I created a batch file to extract the audio from the files.  Tested the batch file and it worked.  Went back to run the batch file to download the videos and it now converts them to audio mp3 format?? Here is what I have:

Using: youtube-dl 2017.01.14
FFmpeg and youtube-dl in system variable path

Audio command line:
youtube-dl -i -o "C:\YouTube\Audio\\%%(playlist)s/%%(playlist_index)s - %%(title)s.%%(ext)s" --batch-file "C:\Youtubedl\Batch Files\Playlists.txt" --extract-audio --audio-format mp3

Video Command Line:
youtube-dl -i -o "C:\YouTube\Video\\%%(playlist)s/%%(playlist_index)s - %%(title)s.%%(ext)s" --batch-file "C:\Youtubedl\Batch Files\Playlists.txt"

What am I missing?  Download videos worked fine before downloading FFmpeg?

Thanks for the help!

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
