### ISSUE TITLE
unable to extract

### ISSUE THREAD

**Issue by MrRobot37** [rg3/youtube-dl#11733]
WARNING: unable to extract user description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Unable to extract playlist title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 Hi I tried to download a playlist from mixcloud and this is the message i got. I've just updated youtube-dl today before getting that message. I'm reporting the issue so that a solution can be found.
Thank You
Mr Robot

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
