### ISSUE TITLE
[Youtube] files don't merge on android 6.0.1 non-rooted

### ISSUE THREAD

**Issue by Serkan-devel** [rg3/youtube-dl#11742]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.14**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.01.14
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

I've installed a command line app called Termux python- and pip-packages for youtube-dl.
It installed fine and worked properly until the end, where it doesn't merge files.

The input I made was <code>youtube-dl -v https://youtu.be/C3td3OY5JcM -f 'bestvideo+bestaudio/best'</code> (I was unable to copy-paste from terminal)
 
This gave me two separate audio and video files 
![tmp_24396-screenshot_20170116-155956910176418](https://cloud.githubusercontent.com/assets/16866642/21987730/f28fd50c-dc04-11e6-8f41-4bb4ee90254c.png)

The output of the output.txt file was:
<pre>[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtu.be/C3td3OY5JcM', '-f', 'bestvideo+bestaudio/best']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.14
[debug] Python version 3.5.2 - Linux-3.10.61-8826787-aarch64-with-libc
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] C3td3OY5JcM: Downloading webpage
[youtube] C3td3OY5JcM: Downloading video info webpage
[youtube] C3td3OY5JcM: Extracting video information
[youtube] C3td3OY5JcM: Downloading MPD manifest
WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r2---sn-4g5e6nez.googlevideo.com/videoplayback?id=0b7b5ddce63925c3&itag=137&source=youtube&requiressl=yes&pl=14&initcwndbps=1128750&mv=m&ms=au&mn=sn-4g5e6nez&mm=31&nh=IgpwcjA2LmZyYTE1Kg03NC4xMjUuNDguMTIz&ratebypass=yes&mime=video/mp4&gir=yes&clen=332396691&lmt=1484511536833687&dur=1250.048&signature=71ED919A031E547037DBE497B91F8F5F8571A26A.18454DB76F49E58037D5CA6613386FB86FBE2934&upn=5RTgo_emjbA&key=dg_yt0&mt=1484576757&ip=92.77.94.112&ipbits=0&expire=1484598524&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,initcwndbps,mv,ms,mn,mm,nh,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Gusis Freunde zerstören mich... _ JF not Kennedy-C3td3OY5JcM.f137.mp4

[download]   0.0% of 317.00MiB at 23.26KiB/s ETA 03:54:17
[download]   0.0% of 317.00MiB at 65.15KiB/s ETA 01:25:11
[download]   0.0% of 317.00MiB at 121.27KiB/s ETA 44:41
[download]   0.0% of 317.00MiB at 251.71KiB/s ETA 21:32
[download]   0.0% of 317.00MiB at 500.92KiB/s ETA 10:49
[download]   0.0% of 317.00MiB at 921.97KiB/s ETA 05:52
[download]   0.0% of 317.00MiB at  1.19MiB/s ETA 04:27
[download]   0.1% of 317.00MiB at  1.00MiB/s ETA 05:16
[download]   0.2% of 317.00MiB at  1.48MiB/s ETA 03:34
[download]   0.3% of 317.00MiB at  1.56MiB/s ETA 03:23
[download]   0.6% of 317.00MiB at  1.61MiB/s ETA 03:15
[download]   1.2% of 317.00MiB at  1.65MiB/s ETA 03:09
[download]   1.7% of 317.00MiB at  1.67MiB/s ETA 03:06
[download]   2.2% of 317.00MiB at  1.68MiB/s ETA 03:04
[download]   2.8% of 317.00MiB at  1.69MiB/s ETA 03:02
[download]   3.3% of 317.00MiB at  1.69MiB/s ETA 03:01
[download]   3.8% of 317.00MiB at  1.69MiB/s ETA 03:00
[download]   4.4% of 317.00MiB at  1.69MiB/s ETA 02:59
[download]   4.9% of 317.00MiB at  1.69MiB/s ETA 02:58
[download]   5.5% of 317.00MiB at  1.70MiB/s ETA 02:56
[download]   6.0% of 317.00MiB at  1.69MiB/s ETA 02:55
[download]   6.5% of 317.00MiB at  1.70MiB/s ETA 02:54
[download]   7.1% of 317.00MiB at  1.70MiB/s ETA 02:53
[download]   7.6% of 317.00MiB at  1.70MiB/s ETA 02:52
[download]   8.2% of 317.00MiB at  1.70MiB/s ETA 02:51
[download]   8.7% of 317.00MiB at  1.69MiB/s ETA 02:50
[download]   9.2% of 317.00MiB at  1.70MiB/s ETA 02:49
[download]   9.8% of 317.00MiB at  1.70MiB/s ETA 02:48
[download]  10.3% of 317.00MiB at  1.70MiB/s ETA 02:47
[download]  10.8% of 317.00MiB at  1.70MiB/s ETA 02:46
[download]  11.4% of 317.00MiB at  1.70MiB/s ETA 02:45
[download]  11.9% of 317.00MiB at  1.70MiB/s ETA 02:44
[download]  12.5% of 317.00MiB at  1.70MiB/s ETA 02:43
[download]  13.0% of 317.00MiB at  1.70MiB/s ETA 02:42
[download]  13.5% of 317.00MiB at  1.70MiB/s ETA 02:41
[download]  14.1% of 317.00MiB at  1.70MiB/s ETA 02:40
[download]  14.6% of 317.00MiB at  1.70MiB/s ETA 02:39
[download]  15.2% of 317.00MiB at  1.70MiB/s ETA 02:38
[download]  15.7% of 317.00MiB at  1.70MiB/s ETA 02:37
[download]  16.2% of 317.00MiB at  1.70MiB/s ETA 02:35
[download]  16.8% of 317.00MiB at  1.70MiB/s ETA 02:35
[download]  17.3% of 317.00MiB at  1.70MiB/s ETA 02:33
[download]  17.9% of 317.00MiB at  1.70MiB/s ETA 02:32
[download]  18.4% of 317.00MiB at  1.70MiB/s ETA 02:31
[download]  18.9% of 317.00MiB at  1.70MiB/s ETA 02:30
[download]  19.5% of 317.00MiB at  1.70MiB/s ETA 02:29
[download]  20.0% of 317.00MiB at  1.70MiB/s ETA 02:28
[download]  20.6% of 317.00MiB at  1.70MiB/s ETA 02:27
[download]  21.1% of 317.00MiB at  1.70MiB/s ETA 02:26
[download]  21.6% of 317.00MiB at  1.70MiB/s ETA 02:25
[download]  22.2% of 317.00MiB at  1.70MiB/s ETA 02:24
[download]  22.7% of 317.00MiB at  1.70MiB/s ETA 02:23
[download]  23.3% of 317.00MiB at  1.70MiB/s ETA 02:22
[download]  23.8% of 317.00MiB at  1.70MiB/s ETA 02:21
[download]  24.3% of 317.00MiB at  1.70MiB/s ETA 02:20
[download]  24.9% of 317.00MiB at  1.70MiB/s ETA 02:19
[download]  25.4% of 317.00MiB at  1.71MiB/s ETA 02:18
[download]  26.0% of 317.00MiB at  1.70MiB/s ETA 02:17
[download]  26.5% of 317.00MiB at  1.71MiB/s ETA 02:16
[download]  27.0% of 317.00MiB at  1.71MiB/s ETA 02:15
[download]  27.6% of 317.00MiB at  1.71MiB/s ETA 02:14
[download]  28.1% of 317.00MiB at  1.71MiB/s ETA 02:13
[download]  28.7% of 317.00MiB at  1.71MiB/s ETA 02:12
[download]  29.2% of 317.00MiB at  1.71MiB/s ETA 02:11
[download]  29.7% of 317.00MiB at  1.71MiB/s ETA 02:10
[download]  30.3% of 317.00MiB at  1.71MiB/s ETA 02:09
[download]  30.8% of 317.00MiB at  1.71MiB/s ETA 02:08
[download]  31.4% of 317.00MiB at  1.71MiB/s ETA 02:07
[download]  31.9% of 317.00MiB at  1.71MiB/s ETA 02:06
[download]  32.4% of 317.00MiB at  1.71MiB/s ETA 02:05
[download]  33.0% of 317.00MiB at  1.71MiB/s ETA 02:04
[download]  33.5% of 317.00MiB at  1.71MiB/s ETA 02:03
[download]  34.1% of 317.00MiB at  1.71MiB/s ETA 02:02
[download]  34.6% of 317.00MiB at  1.71MiB/s ETA 02:01
[download]  35.2% of 317.00MiB at  1.71MiB/s ETA 02:00
[download]  35.7% of 317.00MiB at  1.71MiB/s ETA 01:59
[download]  36.2% of 317.00MiB at  1.71MiB/s ETA 01:58
[download]  36.8% of 317.00MiB at  1.71MiB/s ETA 01:57
[download]  37.3% of 317.00MiB at  1.71MiB/s ETA 01:56
[download]  37.8% of 317.00MiB at  1.71MiB/s ETA 01:55
[download]  38.4% of 317.00MiB at  1.71MiB/s ETA 01:54
[download]  38.9% of 317.00MiB at  1.71MiB/s ETA 01:53
[download]  39.5% of 317.00MiB at  1.71MiB/s ETA 01:52
[download]  40.0% of 317.00MiB at  1.71MiB/s ETA 01:51
[download]  40.6% of 317.00MiB at  1.71MiB/s ETA 01:50
[download]  41.1% of 317.00MiB at  1.71MiB/s ETA 01:49
[download]  41.6% of 317.00MiB at  1.71MiB/s ETA 01:48
[download]  42.2% of 317.00MiB at  1.71MiB/s ETA 01:47
[download]  42.7% of 317.00MiB at  1.71MiB/s ETA 01:46
[download]  43.3% of 317.00MiB at  1.71MiB/s ETA 01:45
[download]  43.8% of 317.00MiB at  1.71MiB/s ETA 01:44
[download]  44.3% of 317.00MiB at  1.71MiB/s ETA 01:43
[download]  44.9% of 317.00MiB at  1.71MiB/s ETA 01:42
[download]  45.4% of 317.00MiB at  1.71MiB/s ETA 01:41
[download]  45.9% of 317.00MiB at  1.71MiB/s ETA 01:40
[download]  46.5% of 317.00MiB at  1.71MiB/s ETA 01:39
[download]  47.0% of 317.00MiB at  1.71MiB/s ETA 01:38
[download]  47.6% of 317.00MiB at  1.71MiB/s ETA 01:37
[download]  48.1% of 317.00MiB at  1.71MiB/s ETA 01:36
[download]  48.7% of 317.00MiB at  1.71MiB/s ETA 01:35
[download]  49.2% of 317.00MiB at  1.71MiB/s ETA 01:34
[download]  49.7% of 317.00MiB at  1.71MiB/s ETA 01:33
[download]  50.3% of 317.00MiB at  1.71MiB/s ETA 01:32
[download]  50.8% of 317.00MiB at  1.71MiB/s ETA 01:31
[download]  51.4% of 317.00MiB at  1.71MiB/s ETA 01:30
[download]  51.9% of 317.00MiB at  1.71MiB/s ETA 01:29
[download]  52.4% of 317.00MiB at  1.71MiB/s ETA 01:28
[download]  53.0% of 317.00MiB at  1.71MiB/s ETA 01:27
[download]  53.5% of 317.00MiB at  1.71MiB/s ETA 01:26
[download]  54.1% of 317.00MiB at  1.71MiB/s ETA 01:25
[download]  54.6% of 317.00MiB at  1.71MiB/s ETA 01:24
[download]  55.2% of 317.00MiB at  1.71MiB/s ETA 01:23
[download]  55.7% of 317.00MiB at  1.71MiB/s ETA 01:22
[download]  56.2% of 317.00MiB at  1.71MiB/s ETA 01:21
[download]  56.8% of 317.00MiB at  1.71MiB/s ETA 01:20
[download]  57.3% of 317.00MiB at  1.71MiB/s ETA 01:19
[download]  57.9% of 317.00MiB at  1.71MiB/s ETA 01:18
[download]  58.4% of 317.00MiB at  1.71MiB/s ETA 01:17
[download]  58.9% of 317.00MiB at  1.71MiB/s ETA 01:16
[download]  59.5% of 317.00MiB at  1.71MiB/s ETA 01:15
[download]  60.0% of 317.00MiB at  1.71MiB/s ETA 01:14
[download]  60.6% of 317.00MiB at  1.71MiB/s ETA 01:13
[download]  61.1% of 317.00MiB at  1.71MiB/s ETA 01:12
[download]  61.7% of 317.00MiB at  1.71MiB/s ETA 01:11
[download]  62.2% of 317.00MiB at  1.71MiB/s ETA 01:10
[download]  62.7% of 317.00MiB at  1.71MiB/s ETA 01:09
[download]  63.3% of 317.00MiB at  1.71MiB/s ETA 01:08
[download]  63.8% of 317.00MiB at  1.71MiB/s ETA 01:07
[download]  64.4% of 317.00MiB at  1.71MiB/s ETA 01:06
[download]  64.9% of 317.00MiB at  1.71MiB/s ETA 01:05
[download]  65.4% of 317.00MiB at  1.71MiB/s ETA 01:04
[download]  66.0% of 317.00MiB at  1.71MiB/s ETA 01:03
[download]  66.5% of 317.00MiB at  1.71MiB/s ETA 01:02
[download]  67.1% of 317.00MiB at  1.71MiB/s ETA 01:01
[download]  67.6% of 317.00MiB at  1.71MiB/s ETA 01:00
[download]  68.1% of 317.00MiB at  1.71MiB/s ETA 00:59
[download]  68.7% of 317.00MiB at  1.71MiB/s ETA 00:58
[download]  69.2% of 317.00MiB at  1.71MiB/s ETA 00:57
[download]  69.8% of 317.00MiB at  1.71MiB/s ETA 00:56
[download]  70.3% of 317.00MiB at  1.71MiB/s ETA 00:55
[download]  70.8% of 317.00MiB at  1.71MiB/s ETA 00:54
[download]  71.4% of 317.00MiB at  1.71MiB/s ETA 00:53
[download]  71.9% of 317.00MiB at  1.71MiB/s ETA 00:51
[download]  72.5% of 317.00MiB at  1.71MiB/s ETA 00:50
[download]  73.0% of 317.00MiB at  1.71MiB/s ETA 00:49
[download]  73.6% of 317.00MiB at  1.71MiB/s ETA 00:48
[download]  74.1% of 317.00MiB at  1.71MiB/s ETA 00:47
[download]  74.6% of 317.00MiB at  1.71MiB/s ETA 00:46
[download]  75.2% of 317.00MiB at  1.71MiB/s ETA 00:45
[download]  75.7% of 317.00MiB at  1.71MiB/s ETA 00:44
[download]  76.3% of 317.00MiB at  1.71MiB/s ETA 00:43
[download]  76.8% of 317.00MiB at  1.71MiB/s ETA 00:42
[download]  77.3% of 317.00MiB at  1.71MiB/s ETA 00:41
[download]  77.9% of 317.00MiB at  1.71MiB/s ETA 00:40
[download]  78.4% of 317.00MiB at  1.71MiB/s ETA 00:39
[download]  79.0% of 317.00MiB at  1.71MiB/s ETA 00:38
[download]  79.5% of 317.00MiB at  1.71MiB/s ETA 00:37
[download]  80.1% of 317.00MiB at  1.71MiB/s ETA 00:36
[download]  80.6% of 317.00MiB at  1.71MiB/s ETA 00:35
[download]  81.1% of 317.00MiB at  1.71MiB/s ETA 00:34
[download]  81.7% of 317.00MiB at  1.71MiB/s ETA 00:33
[download]  82.2% of 317.00MiB at  1.71MiB/s ETA 00:32
[download]  82.7% of 317.00MiB at  1.71MiB/s ETA 00:31
[download]  83.3% of 317.00MiB at  1.71MiB/s ETA 00:30
[download]  83.8% of 317.00MiB at  1.71MiB/s ETA 00:29
[download]  84.4% of 317.00MiB at  1.71MiB/s ETA 00:28
[download]  84.9% of 317.00MiB at  1.71MiB/s ETA 00:27
[download]  85.4% of 317.00MiB at  1.71MiB/s ETA 00:26
[download]  86.0% of 317.00MiB at  1.71MiB/s ETA 00:25
[download]  86.5% of 317.00MiB at  1.71MiB/s ETA 00:24
[download]  87.1% of 317.00MiB at  1.71MiB/s ETA 00:23
[download]  87.6% of 317.00MiB at  1.71MiB/s ETA 00:22
[download]  88.1% of 317.00MiB at  1.71MiB/s ETA 00:21
[download]  88.7% of 317.00MiB at  1.71MiB/s ETA 00:20
[download]  89.2% of 317.00MiB at  1.71MiB/s ETA 00:19
[download]  89.8% of 317.00MiB at  1.71MiB/s ETA 00:18
[download]  90.3% of 317.00MiB at  1.71MiB/s ETA 00:17
[download]  90.8% of 317.00MiB at  1.71MiB/s ETA 00:16
[download]  91.4% of 317.00MiB at  1.71MiB/s ETA 00:15
[download]  91.9% of 317.00MiB at  1.71MiB/s ETA 00:14
[download]  92.5% of 317.00MiB at  1.71MiB/s ETA 00:13
[download]  93.0% of 317.00MiB at  1.71MiB/s ETA 00:12
[download]  93.5% of 317.00MiB at  1.71MiB/s ETA 00:11
[download]  94.1% of 317.00MiB at  1.71MiB/s ETA 00:10
[download]  94.6% of 317.00MiB at  1.71MiB/s ETA 00:09
[download]  95.2% of 317.00MiB at  1.71MiB/s ETA 00:08
[download]  95.7% of 317.00MiB at  1.71MiB/s ETA 00:07
[download]  96.1% of 317.00MiB at  1.71MiB/s ETA 00:07
[download]  96.7% of 317.00MiB at  1.71MiB/s ETA 00:06
[download]  97.2% of 317.00MiB at  1.71MiB/s ETA 00:05
[download]  97.8% of 317.00MiB at  1.71MiB/s ETA 00:04
[download]  98.3% of 317.00MiB at  1.71MiB/s ETA 00:03
[download]  98.8% of 317.00MiB at  1.71MiB/s ETA 00:02
[download]  99.4% of 317.00MiB at  1.71MiB/s ETA 00:01
[download]  99.9% of 317.00MiB at  1.71MiB/s ETA 00:00
[download] 100.0% of 317.00MiB at  1.71MiB/s ETA 00:00
[download] 100% of 317.00MiB in 03:05
[debug] Invoking downloader on 'https://r2---sn-4g5e6nez.googlevideo.com/videoplayback?id=0b7b5ddce63925c3&itag=251&source=youtube&requiressl=yes&pl=14&initcwndbps=1128750&mv=m&ms=au&mn=sn-4g5e6nez&mm=31&nh=IgpwcjA2LmZyYTE1Kg03NC4xMjUuNDguMTIz&ratebypass=yes&mime=audio/webm&gir=yes&clen=20263029&lmt=1484514296688806&dur=1250.121&signature=85AB03C5027D922A4E1C9391CE7CBD3B9A11A02E.5FA41CA5B12223821A61D0C0874C7506C475A2C0&upn=5RTgo_emjbA&key=dg_yt0&mt=1484576757&ip=92.77.94.112&ipbits=0&expire=1484598524&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,initcwndbps,mv,ms,mn,mm,nh,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Gusis Freunde zerstören mich... _ JF not Kennedy-C3td3OY5JcM.f251.webm

[download]   0.0% of 19.32MiB at 34.26KiB/s ETA 09:38
[download]   0.0% of 19.32MiB at 100.68KiB/s ETA 03:16
[download]   0.0% of 19.32MiB at 229.86KiB/s ETA 01:26
[download]   0.1% of 19.32MiB at 480.33KiB/s ETA 00:41
[download]   0.2% of 19.32MiB at 881.11KiB/s ETA 00:22
[download]   0.3% of 19.32MiB at 909.55KiB/s ETA 00:21
[download]   0.6% of 19.32MiB at  1.17MiB/s ETA 00:16
[download]   1.3% of 19.32MiB at  1.04MiB/s ETA 00:18
[download]   2.6% of 19.32MiB at  1.49MiB/s ETA 00:12
[download]   5.2% of 19.32MiB at  1.60MiB/s ETA 00:11
[download]  10.3% of 19.32MiB at  1.62MiB/s ETA 00:10
[download]  18.8% of 19.32MiB at  1.66MiB/s ETA 00:09
[download]  27.7% of 19.32MiB at  1.67MiB/s ETA 00:08
[download]  36.4% of 19.32MiB at  1.68MiB/s ETA 00:07
[download]  45.3% of 19.32MiB at  1.69MiB/s ETA 00:06
[download]  54.2% of 19.32MiB at  1.69MiB/s ETA 00:05
[download]  63.0% of 19.32MiB at  1.70MiB/s ETA 00:04
[download]  72.0% of 19.32MiB at  1.70MiB/s ETA 00:03
[download]  80.8% of 19.32MiB at  1.70MiB/s ETA 00:02
[download]  89.5% of 19.32MiB at  1.70MiB/s ETA 00:01
[download]  98.5% of 19.32MiB at  1.70MiB/s ETA 00:00
[download] 100.0% of 19.32MiB at  1.70MiB/s ETA 00:00
[download] 100% of 19.32MiB in 00:11
</pre>

**Comment by dstftw** [comment]
>WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.

**Comment by Serkan-devel** [comment]
Thanks

I've installed ffmpeg and it now works
