### ISSUE TITLE
Not really an issue, just a question or suggestion... 

### ISSUE THREAD

**Issue by rexorp** [rg3/youtube-dl#11745]
Would it be possible, in Kodi, to have this add-on launched by activation of the record button on the play screen or maybe by a different button with other menu options? There by eliminating the need to go back to the home menu or program add-ons menu or otherwise exiting the play screen to launch. Or am I missing something all together obvious?

**Comment by yan12125** [comment]
FYI: Kodi addons are not developed by us. Go ahead and ask its developers.
