### ISSUE TITLE
Question: youtube-dl creates -lots of- .Frag files

### ISSUE THREAD

**Issue by redical** [rg3/youtube-dl#11750]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
Question:

I use this command (*) to download the best dash quality of some youtube videos:

`youtube-dl -f 137+140 http://www.youtube.com/watch?v=3JZ_D3ELwOQ`

*Source: http://unix.stackexchange.com/questions/272868/download-only-format-mp4-on-youtube-dl/272934

Sometimes this command creates lots of .Frag-files in the home folder - and sometimes not. It happens with large videos and shorter ones but not consistent. Crawling the readme gave no hints on that. So can anybody explain why youtube-dl creates this fragments? 

cheers
red

**Comment by dstftw** [comment]
Some videos served in fragments. In this case frag files are created.

**Comment by linglung** [comment]
I'm also curious about this. Sorry if i ask a bit more here. Just want to know, Then when a video served in fragments, it will be downloaded as separated frag files first by youtube-dl? or is it possible to download it with no frag files?

**Comment by yan12125** [comment]
@linglung See #9937

**Comment by brokendash** [comment]
Can you set maybe a run time working dir for youtube-dl to use till its ready to copy the finished concatenated file whatever the main env $CWD was when the initial command was run?

**Comment by yan12125** [comment]
@brokendash See #10993. Before that is implemented, you can use ```--exec```

**Comment by brokendash** [comment]
Ahhh exactly what I'm looking for!  Thanks Sir... :-)
