### ISSUE TITLE
Feature request include pytoutv

### ISSUE THREAD

**Issue by danyboy666** [rg3/youtube-dl#11759]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.01.16
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

--- 

Please would it be possible to add the pytoutv library to youtube-dl? 

Site: http://ici.tou.tv
Show example : http://ici.tou.tv/district-31
Code link : https://github.com/bvanheu/pytoutv

Thanks

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by yan12125** [comment]
ici.tou.tv is already supported:
```
$ youtube-dl -v "http://ici.tou.tv/district-31" 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://ici.tou.tv/district-31']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.16
[debug] Git HEAD: c1c2fe204
[debug] Python version 3.6.0 - Linux-4.9.0-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[tou.tv] district-31: Downloading JSON metadata
[radiocanada] 127175: Downloading metadata XML
[radiocanada] 127175: Downloading ipad XML
[radiocanada] 127175: Downloading m3u8 information
[radiocanada] 127175: Downloading android XML
[radiocanada] 127175: Downloading m3u8 information
[radiocanada] 127175: Downloading f4m manifest
[radiocanada] 127175: Downloading m3u8 information
[radiocanada] 127175: Downloading f4m manifest
[radiocanada] 127175: Downloading m3u8 information
[radiocanada] 127175: Downloading f4m manifest
[radiocanada] 127175: Downloading m3u8 information
[radiocanada] 127175: Downloading f4m manifest
[debug] Invoking downloader on 'http://medias-rtsp.tou.tv/vodtoutv/_definst_/mp4:012/mp4/d/2017-01-17_19_00_00_district31_0066_2000.mp4/chunklist.m3u8?wowzasessionid=1135881146'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 127
[download] Destination: Épisode 66-127175.mp4
[download]   0.8% of ~354.32MiB at 235.98KiB/s ETA 26:41^C
ERROR: Interrupted by user
Exception ignored in: <_io.FileIO name='Épisode 66-127175.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.FileIO name='Épisode 66-127175.mp4.part' mode='wb' closefd=True>
```

**Comment by danyboy666** [comment]
youtube-dl -v "http://ici.tou.tv/district-31"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://ici.tou.tv/district-31']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.18
[debug] Python version 2.7.11+ - Linux-4.4.0-22-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[tou.tv] district-31: Downloading JSON metadata
[radiocanada] 127199: Downloading metadata XML
[radiocanada] 127199: Downloading ipad XML
[radiocanada] 127199: Downloading m3u8 information
[radiocanada] 127199: Downloading android XML
[radiocanada] 127199: Downloading m3u8 information
[radiocanada] 127199: Downloading f4m manifest
[radiocanada] 127199: Downloading m3u8 information
[radiocanada] 127199: Downloading f4m manifest
[radiocanada] 127199: Downloading m3u8 information
[radiocanada] 127199: Downloading f4m manifest
[radiocanada] 127199: Downloading m3u8 information
[radiocanada] 127199: Downloading f4m manifest
[debug] Invoking downloader on u'http://medias-rtsp.tou.tv/vodtoutv/_definst_/mp4:012/mp4/d/2017-01-18_19_00_00_district31_0067_2000.mp4/chunklist.m3u8?wowzasessionid=121049205'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 130
[download] Destination: Épisode 67-127199.mp4
[download]   4.6% of ~349.00MiB at  2.70MiB/s ETA 02:45ERROR: unable to download video data: P`
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 121, in real_download
    'http_headers': info_dict.get('http_headers'),
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 883, in http_open
    req)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 431, in _read_status
    raise BadStatusLine(line)
BadStatusLine: P`

My bad I didn't notice at first it was already included. 

There must be something wrong though the download errors out.

**Comment by yan12125** [comment]
I guess that's a temporary network issue.
```
$ youtube-dl -v "http://ici.tou.tv/district-31" 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://ici.tou.tv/district-31']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.16
[debug] Git HEAD: 136078966
[debug] Python version 3.6.0 - Linux-4.9.0-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[tou.tv] district-31: Downloading JSON metadata
[radiocanada] 127199: Downloading metadata XML
[radiocanada] 127199: Downloading ipad XML
[radiocanada] 127199: Downloading m3u8 information
[radiocanada] 127199: Downloading android XML
[radiocanada] 127199: Downloading m3u8 information
[radiocanada] 127199: Downloading f4m manifest
[radiocanada] 127199: Downloading m3u8 information
[radiocanada] 127199: Downloading f4m manifest
[radiocanada] 127199: Downloading m3u8 information
[radiocanada] 127199: Downloading f4m manifest
[radiocanada] 127199: Downloading m3u8 information
[radiocanada] 127199: Downloading f4m manifest
[debug] Invoking downloader on 'http://medias-rtsp.tou.tv/vodtoutv/_definst_/mp4:012/mp4/d/2017-01-18_19_00_00_district31_0067_2000.mp4/chunklist.m3u8?wowzasessionid=957101376'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 130
[download] Destination: Épisode 67-127199.mp4
[download] 100% of 343.27MiB in 27:14
[debug] ffmpeg command line: ffprobe -show_streams 'file:Épisode 67-127199.mp4'
[ffmpeg] Fixing malformated aac bitstream in "Épisode 67-127199.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Épisode 67-127199.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Épisode 67-127199.temp.mp4'
```
