### ISSUE TITLE
File Size for Best available format

### ISSUE THREAD

**Issue by linglung** [rg3/youtube-dl#11756]
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
Can you add **file size info** for best format selected by default (format code 22) when using `-F` option?. 
For example : 

22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k, **103.57MiB**  (best)

I think this is useful for user like me to know the file size before we decide to download it. I often chose best format, but in some cases when  file size is far too big then i cancel it and select other format available.

**Comment by dstftw** [comment]
No file size metadata is available for non DASH formats.
