### ISSUE TITLE
how can login for download private my account in youtube?

### ISSUE THREAD

**Issue by mdoulabi** [rg3/youtube-dl#11762]
i want upload video in youtube with private permission ,
how i can download my video?

**Comment by yan12125** [comment]
See https://github.com/rg3/youtube-dl/blob/master/README.md#authentication-options

**Comment by mdoulabi** [comment]
thank u , 
if upload video copyright or adult in youtube with permission private , youtube delete my video?

**Comment by yan12125** [comment]
that's possible, especially for copyrighted videos

**Comment by mdoulabi** [comment]
i use -u and -p 

[youtube] Downloading login page
[youtube] Logging in
[youtube] LBLhIXCkGCM: Downloading webpage
[youtube] LBLhIXCkGCM: Downloading embed webpage
[youtube] LBLhIXCkGCM: Refetching age-gated info webpage
ERROR: LBLhIXCkGCM: YouTube said: Please sign in to view this video.

**Comment by yan12125** [comment]
Could you watch LBLhIXCkGCM when logged as arashmahdavi333@gmail.com?

**Comment by mdoulabi** [comment]
yea , coz upload LBLhIXCkGCM  by arashmahdavi333@gmail.com

**Comment by yan12125** [comment]
That would be wierd. "Please sign in to view this video" is exactly what YouTube returns. Could you run this command:
```
youtube-dl -v -f best --ignore-config -u arashmahdavi333@gmail.com -p ***** https://www.youtube.com/watch?v=LBLhIXCkGCM --write-pages
```
And upload all *.dump files? Of course check whether there are sensitive data or not before uploading.

**Comment by mdoulabi** [comment]
[host@server ~]$ youtube-dl -v -f best --ignore-config -u arashmahdavi333@gmail.com -p ***** https://www.youtube.com/watch?v=LBLhIXCkGCM --write-pages
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'best', u'--ignore-config', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.youtube.com/watch?v=LBLhIXCkGCM', u'--write-pages']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.14
[debug] Python version 2.6.6 - Linux-2.6.32-573.el6.x86_64-x86_64-with-centos-6.7-Final
[debug] exe versions: ffmpeg N-78980-ga008a7c, ffprobe 2.2.1
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Saving request to None_https_-_accounts.google.com_ServiceLogin.dump
[youtube] Logging in
[youtube] Saving request to None_https_-_accounts.google.com_signin_challenge_sl_password.dump
[youtube] LBLhIXCkGCM: Downloading webpage
[youtube] Saving request to LBLhIXCkGCM_https_-_www.youtube.com_watchv=LBLhIXCkGCM_gl=US_hl=en_has_verified=1_bpctr=9999999999.dump
[youtube] LBLhIXCkGCM: Downloading embed webpage
[youtube] Saving request to LBLhIXCkGCM_https_-_www.youtube.com_embed_LBLhIXCkGCM.dump
[youtube] LBLhIXCkGCM: Refetching age-gated info webpage
[youtube] Saving request to LBLhIXCkGCM_https_-_www.youtube.com_get_video_infovideo_id=LBLhIXCkGCM_eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FLBLhIXCkGCM_sts=17180.dump
ERROR: LBLhIXCkGCM: YouTube said: Please sign in to view this video.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 359, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1333, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: LBLhIXCkGCM: YouTube said: Please sign in to view this video.
