### ISSUE TITLE
Can you force youtube-dl to use a specific extractor?

### ISSUE THREAD

**Issue by joetex72** [rg3/youtube-dl#11761]
Sometimes when a particular extractor is used the download goes well, but if it switches to the generic extractor for the same site it says unsupported url.

This is more of a general question.

**Comment by yan12125** [comment]
> if it switches to the generic extractor for the same site it says unsupported url.

That would be a bug/missing feature. Force a specific extractor does not make sense as extractors are designed to handle a set of known URL patterns.
