### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by techhk** [rg3/youtube-dl#1178]
Got this error on both public and private video.

ERROR: unable to open for writing: [Errno 22] invalid mode ('wb') or filename:

URL:
http://www.youtube.com/watch?v=R-qjyEn3bjs&list=PLxgo3AdNW0Ln1G1xcELNyH2w7A8MNI6hZ

Thank you.

**Comment by kiev78** [comment]
For me the issue was because the exe didn't have write access to the c: folder i was trying to download the video into on my windows 8 box. I moved it to another folder and all was ok after that
