### ISSUE TITLE
Received video link from remote server doesn't works when runned on local machine

### ISSUE THREAD

**Issue by cristalix** [rg3/youtube-dl#11782]
Hi, 
when I run this command:

`youtube-dl -f 18 -g https://www.youtube.com/watch?v=GWKtoSza8lM`

on remote server, I can access (download video). When I try to view this video on my local machine, browser stays blank (and vice versa). Server is in Netherlands and I sit in Belgium.

What is it? Video link is user-agent or IP-address specific? It's a bug or feature?

**Comment by yan12125** [comment]
> Video link is user-agent or IP-address specific?

Both. See https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser
