### ISSUE TITLE
Display absolute links to downloaded files via youtube-dl?

### ISSUE THREAD

**Issue by aidinzolghadr** [rg3/youtube-dl#11789]
Hi,

I've set up youtube-dl on my shared Debian 3 host so I can access it via an URL to pass address to what I want to download so it would download it on my host.

I was wondering if there is a way to display URL links to file(s) downloaded by last request on a web page for easier download.

So for example, if you call domain.com/youtubedl.php?url=www.youtube.com/watch?v=000000 would download it and then display this on the page:

http://domain/download_directory/youtubefile.mp4

so you can easily download it by clicking on that link.

Thanks

**Comment by dstftw** [comment]
>I've set up youtube-dl on my shared Debian 3 host so I can access it via an URL to pass address to what I want to download so it would download it on my host.

youtube-dl does not provide such functionality. Ask support of the web front-end you are using.

**Comment by aidinzolghadr** [comment]
I'm not using any frond-end. I've wrote a bunch of php files to handle my calls to youtube-dl.

Also if you `var_dump` output of youtube-dl, you can see the relative addresses of the files it's downloaded but it also has a lot of other info that I do not need and the paths are not absolute as well. So I was wondering if it's possible to achieve what I asked for with it.

**Comment by yan12125** [comment]
all youtube-dl paths are relative to the current directory.
