### ISSUE TITLE
HTMLParser incorrectly decodes string as HTML entities

### ISSUE THREAD

**Issue by einstein95** [rg3/youtube-dl#11798]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Due to the reliance of HTMLParser, any site such as PornFlip (see #11795) that contains the string `&sectime` in the mpd manifest URL gets incorrectly decoded to `§ime`. I have no knowledge of why HTMLParser does this, as `§` HTML-encoded is `&sect;` (note the semicolon, like other HTML-encoded symbols). It is due to this that I had to rely on extracting the MP4 links rather than simply calling `_parse_html5_media_entries`.
I felt that I needed to inform the developers of this, in case this or a similar problem happens to any current or future developer.

**Comment by dstftw** [comment]
HTML5 [allows](https://www.w3.org/TR/html5/syntax.html#named-character-references) entities without a semicolon. Thus this is perfectly legal.

**Comment by einstein95** [comment]
Albeit very stupid

**Comment by yan12125** [comment]
I guess it's PornFlip that provides broken HTML. ```fix_xml_ampersands``` can be used in such cases. If you believe there's a bug in HTMLParser, report it to http://bugs.python.org/ instead.
