### ISSUE TITLE
Unicode Character in Youtube Track Title

### ISSUE THREAD

**Issue by alyssonrpg** [rg3/youtube-dl#11791]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

The youtube video "https://www.youtube.com/watch?v=QImBolnTVH8" contain unicode characters in the title. That title is not passed correctly to ffmpeg and it can't convert to mp3 file. 

Command Arguments:  youtube-dl.exe -x -v https://www.youtube.com/watch?v=QImBolnTVH8

Output:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '-v', 'https://www.youtube.com/watch?v=QImBolnTVH8']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.18
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[youtube] QImBolnTVH8: Downloading webpage
[youtube] QImBolnTVH8: Downloading video info webpage
[youtube] QImBolnTVH8: Extracting video information
[youtube] {22} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {43} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {18} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {36} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {17} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {137} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {248} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {136} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {247} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {135} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {244} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {134} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {243} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {133} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {242} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {160} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {278} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {140} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {171} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {249} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {250} signature length 0.82, html5 player en_US-vflamKXEP
[youtube] {251} signature length 0.82, html5 player en_US-vflamKXEP
[debug] Invoking downloader on 'https://r5---sn-jxhpb-jo4e.googlevideo.com/videoplayback?ipbits=0&gir=yes&pcm2cms=yes&lmt=1450146225397064&source=youtube&itag=251&clen=3576915&initcwndbps=591250&expire=1484955923&upn=cZU75T1EIi8&ei=s0yCWIaVDYKR-gXQp7KQBA&key=yt6&keepalive=yes&mm=31&ip=177.128.108.249&mn=sn-jxhpb-jo4e&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mt=1484934054&pl=23&mv=m&ms=au&requiressl=yes&mime=audio%2Fwebm&pfsc=ltr&id=o-AM5s_5edv2YLc9ANK_c0hDzUKKU12mdQf1sFbw2XoaNW&dur=226.921&signature=283A74D201EC8B4CE5F825D919C6C8D4E8DB35C0.525DFB3B2DE63F25F17638AE09CAA431B02C01A0&ratebypass=yes'
[download] Destination: [Official Video] JAM Project - THE HERO !! -  'One Punch Man' Opening Theme ワンパンマン-QImBolnTVH8.webm
[download] 100% of 3.41MiB in 00:01
[debug] ffmpeg command line: ffprobe -show_streams 'file:[Official Video] JAM Project - THE HERO !! -  '"'"'One Punch Man'"'"' Opening Theme ワンパンマン-QImBolnTVH8.webm'
[ffmpeg] Destination: [Official Video] JAM Project - THE HERO !! -  'One Punch Man' Opening Theme ワンパンマン-QImBolnTVH8.opus
[debug] ffmpeg command line: ffmpeg -y -i 'file:[Official Video] JAM Project - THE HERO !! -  '"'"'One Punch Man'"'"' Opening Theme ワンパンマン-QImBolnTVH8.webm' -vn -acodec copy 'file:[Official Video] JAM Project - THE HERO !! -  '"'"'One Punch Man'"'"' Opening Theme ワンパンマン-QImBolnTVH8.opus'
Deleting original file [Official Video] JAM Project - THE HERO !! -  'One Punch Man' Opening Theme ワンパンマン-QImBolnTVH8.webm (pass -k to keep)

C:\Temp\y>

---

---

**Comment by alyssonrpg** [comment]
The unicode characters are converted and showed as "?" characters

**Comment by yan12125** [comment]
From the log everything is fine. Maybe a screenshot explain things better?

By the way, if you want mp3 instead of opus, add ```--audio-format mp3```

**Comment by alyssonrpg** [comment]
On disk, the original, downloaded audio file is stored with correct unicode glyphs/characters.

On prompt and arguments passed to ffmpeg, the unicode characters are converted and shown as "?" characters... I imagine the ffmpeg cant localize the file because this translation of characters.

The output went to clipboard with correct unicode characters, but, as you see on the print-screen, its printed with "?" characters

![image](https://cloud.githubusercontent.com/assets/25252071/22159621/f83fdd2c-df28-11e6-9271-8bda50cc6714.png)

**Comment by yan12125** [comment]
That's the problem of CMD. ```chcp``` command may help

**Comment by alyssonrpg** [comment]
It's not problem of CMD.. Maybe, but the printed characteres is not the main concern.

Try yourself to download and extract audio as mp3 of the "https://www.youtube.com/watch?v=QImBolnTVH8" video.

Youtube-dl download the opus file, but fail to convert to mp3 with ffmpeg. The mp3 file is not generated. I guess the ffmpeg is not correctly locating the file due the characters translations.

**Comment by dstftw** [comment]
Post the log where you are trying to convert to mp3.

**Comment by alyssonrpg** [comment]
Log of the download and conversion:
![image](https://cloud.githubusercontent.com/assets/25252071/22160041/d710a210-df2a-11e6-9164-f909fe145cb6.png)

Directory of the downloaded and converted file:
![image](https://cloud.githubusercontent.com/assets/25252071/22160088/03cea5b8-df2b-11e6-8ee6-c5260ad755b8.png)

No mp3 was generated.

**Comment by dstftw** [comment]
Do you even read what is addressed to you?
>if you want mp3 instead of opus, add ```--audio-format mp3```
