### ISSUE TITLE
collegehumor invlaid URL

### ISSUE THREAD

**Issue by canavan** [rg3/youtube-dl#1179]
$ ./youtube-dl  --verbose   http://www.collegehumor.
com/e/6902835
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.collegehumor.com/e/6902835']
[debug] youtube-dl version 2013.08.02
[debug] Python version 2.7.3 - IRIX64-6.5-IP35-mips-n32bit-ELF
[debug] Proxy map: {'http': 'http://10.2.4.16:3128/', 'https': 'http://10.2.4.16:3128/'}
WARNING: Falling back on generic information extractor.
[generic] 6902835: Downloading webpage
[generic] 6902835: Extracting information
ERROR: Invalid URL: http://www.collegehumor.com/e/6902835; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 312, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 96, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 148, in _real_extract
    raise ExtractorError(u'Invalid URL: %s' % url)
ExtractorError: Invalid URL: http://www.collegehumor.com/e/6902835; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output.

/e/ are embed URLs, http://www.collegehumor.com/video/6902835 works.

**Comment by fictionic** [comment]
The problem has surfaced again, but in a worse form. Trying to download [this video](http://www.collegehumor.com/video/3440739/backwards-hardly-working) gives 

```
[generic] backwards-hardly-working: Requesting header
WARNING: Falling back on generic information extractor.
[generic] backwards-hardly-working: Downloading webpage
[generic] backwards-hardly-working: Extracting information
[generic] 3440739: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3440739: Downloading webpage
[generic] 3440739: Extracting information
ERROR: Unsupported URL: https://www.collegehumor.com/e/3440739
```

Note that this only happens for *some* CollegeHumor videos. Most of them work just fine (they are embedded in a variety of ways).
