### ISSUE TITLE
Unable to get the audio of the vedios, 

### ISSUE THREAD

**Issue by shivamzaz** [rg3/youtube-dl#11792]
249          webm       audio only DASH audio   51k , opus @ 50k (48000Hz), 2.39MiB
250          webm       audio only DASH audio   66k , opus @ 70k (48000Hz), 3.03MiB
171          webm       audio only DASH audio   81k , vorbis@128k (44100Hz), 3.62MiB
140          m4a        audio only DASH audio   96k , m4a_dash container, mp4a.40.2@128k (44100Hz), 4.51MiB
251          webm       audio only DASH audio   99k , opus @160k (48000Hz), 4.52MiB
278          webm       244x144    DASH video   63k , webm container, vp9, 30fps, video only, 1.03MiB
242          webm       406x240    DASH video   78k , vp9, 30fps, video only, 1.12MiB
160          mp4        244x144    DASH video  108k , avc1.4d400c, 30fps, video only, 2.66MiB
243          webm       610x360    DASH video  142k , vp9, 30fps, video only, 1.73MiB
134          mp4        610x360    DASH video  211k , avc1.4d401e, 30fps, video only, 2.33MiB
133          mp4        406x240    DASH video  243k , avc1.4d400d, 30fps, video only, 4.51MiB
244          webm       812x480    DASH video  246k , vp9, 30fps, video only, 2.54MiB
135          mp4        812x480    DASH video  385k , avc1.4d401f, 30fps, video only, 3.70MiB
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
36           3gp        320x190    small , mp4v.20.3,  mp4a.40.2
18           mp4        608x360    medium , avc1.42001E,  mp4a.40.2@ 96k
43           webm       640x360    medium , vp8.0,  vorbis@128k (best)

**Comment by shivamzaz** [comment]
249          webm       audio only DASH audio   51k , opus @ 50k (48000Hz), 2.39MiB
250          webm       audio only DASH audio   66k , opus @ 70k (48000Hz), 3.03MiB
171          webm       audio only DASH audio   81k , vorbis@128k (44100Hz), 3.62MiB
140          m4a        audio only DASH audio   96k , m4a_dash container, mp4a.40.2@128k (44100Hz), 4.51MiB
251          webm       audio only DASH audio   99k , opus @160k (48000Hz), 4.52MiB
278          webm       244x144    DASH video   63k , webm container, vp9, 30fps, video only, 1.03MiB
242          webm       406x240    DASH video   78k , vp9, 30fps, video only, 1.12MiB
160          mp4        244x144    DASH video  108k , avc1.4d400c, 30fps, video only, 2.66MiB
243          webm       610x360    DASH video  142k , vp9, 30fps, video only, 1.73MiB
134          mp4        610x360    DASH video  211k , avc1.4d401e, 30fps, video only, 2.33MiB
133          mp4        406x240    DASH video  243k , avc1.4d400d, 30fps, video only, 4.51MiB
244          webm       812x480    DASH video  246k , vp9, 30fps, video only, 2.54MiB
135          mp4        812x480    DASH video  385k , avc1.4d401f, 30fps, video only, 3.70MiB
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
36           3gp        320x190    small , mp4v.20.3,  mp4a.40.2
18           mp4        608x360    medium , avc1.42001E,  mp4a.40.2@ 96k
43           webm       640x360    medium , vp8.0,  vorbis@128k (best)

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by shivamzaz** [comment]
I resolved it but BTW thanks for taking upto the point
