### ISSUE TITLE
Priority over qualities?

### ISSUE THREAD

**Issue by aidinzolghadr** [rg3/youtube-dl#11804]
Hi,

Is it possible to set several qualities in order of importance so if youtube-dl cannot find first specified quality for that file, would fall back to other ones like 720p->480p->360p ?

Thanks

**Comment by dstftw** [comment]
Provide concrete examples.

**Comment by aidinzolghadr** [comment]
For example when you want to download a file, instead of passing one quality setting via -f switch, add several in order of importance like -f 720p,480p,240p so when youtube-dl wants to download the file with 720p, if it encounters with error that such quality is not available for that file, it would got for the next requested quality which is 480p in this case.

**Comment by dstftw** [comment]
This is already supported. Bother to read [FAQ](https://github.com/rg3/youtube-dl#format-selection).

**Comment by aidinzolghadr** [comment]
I can't find it in the FAQ.

**Comment by bezdupel** [comment]
It's [here](https://github.com/rg3/youtube-dl#format-selection).

Try something like this:
`-f "best[height=720]/best[height=480]/best[height=240]"`

Or for any available quality up to 720p:
`-f "best[height<=?720]"`
