### ISSUE TITLE
[chaturbate] Always "ERROR: Room is currently offline"

### ISSUE THREAD

**Issue by guruharu** [rg3/youtube-dl#11802]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.18**

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'link to any room']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.18
[debug] Python version 2.7.12 - Linux-4.4.0-59-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[Chaturbate] room: Downloading webpage
ERROR: Room is currently offline
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 359, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/chaturbate.py", line 48, in _real_extract
    raise ExtractorError(error, expected=True)
ExtractorError: Room is currently offline
```

### Description of your *issue*, suggested solution and other information
probably the problem is with the regular expression for .m3u8 file. I'm not good at python or building regular expressions. That's just my suggestion. The regular expression now looks like this `src=(["\'])(?P<url>http.+?\.m3u8.*?)\1` but the .m3u8 links are now stored in javascript variables, not in src attributes.

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.
