### ISSUE TITLE
Please support Afreeca.tv

### ISSUE THREAD

**Issue by LeonSheldon** [rg3/youtube-dl#11807]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.22**

- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ youtube-dl http://afreeca.tv/36855042/v/58130 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://afreeca.tv/36855042/v/58130', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.18
[debug] Python version 2.7.12 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2
[debug] Proxy map: {}
[generic] 58130: Requesting header
[redirect] Following redirect to http://www.afreeca.tv/
[generic] www.afreeca: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.afreeca: Downloading webpage
[generic] www.afreeca: Extracting information
ERROR: Unsupported URL: http://www.afreeca.tv/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1720, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 27, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 359, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2555, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.afreeca.tv/
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://afreeca.tv/36855042/v/58130

---

### Description of your *issue*, suggested solution and other information

This site is not supported (afreecatv.com, the Korean version of the site is, but the afreeca.tv domain is English/international). It would be great if support could be added, thanks.

**Comment by yan12125** [comment]
By the way, all old Korean Afreeca TV URLs in ```afreecatv.py``` are now invalid:
```
http://live.afreecatv.com:8079/app/index.cgi?szType=read_ucc_bbs&szBjId=dailyapril&nStationNo=16711924&nBbsNo=18605867&nTitleNo=36164052&szSkin=
http://afbbs.afreecatv.com:8080/app/read_ucc_bbs.cgi?nStationNo=16711924&nTitleNo=36153164&szBjId=dailyapril&nBbsNo=18605867
http://www.afreecatv.com/player/Player.swf?szType=szBjId=djleegoon&nStationNo=11273158&nBbsNo=13161095&nTitleNo=36327652
http://vod.afreecatv.com/PLAYER/STATION/15055030
```
@pmrowla or anyone else knows what happened to those videos?

**Comment by pmrowla** [comment]
It looks like the VODs that I used for those test URLs might have been removed at some point. I should have some free time over the next week so I'll take a look into updating the test URLs, and see what I can do regarding support for the international site as well.

**Comment by yan12125** [comment]
Thanks. I thought there are some changes in the Korean version. If so afreeca.py may need to be completely rewritten. I hope to solve them together, but first I need some information from those who are familiar with Afreecatv.
