### ISSUE TITLE
[prosiebensat1] WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by z1atk0** [rg3/youtube-dl#11810]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.22**

[zlatko@disclosure]:~$ youtube-dl --version
2017.01.22

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

youtube-dl actually asked me to report this bug, so I'm just doing as I'm told. ;-)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[zlatko@disclosure]:~$ youtube-dl --verbose -F "http://www.prosiebenmaxx.at/tv/when-sharks-attack-hai-alarm/video/11-florida-ganze-folge"
[debug] System config: []
[debug] User config: [u'--proxy', u'', u'--rate-limit', u'12M']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-F', u'http://www.prosiebenmaxx.at/tv/when-sharks-attack-hai-alarm/video/11-florida-ganze-folge']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.22
[debug] Python version 2.7.13 - Linux-4.8.15-i686-Intel-R-_Core-TM-_i3-3220_CPU_@_3.30GHz-with-slackware-14.2
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[prosiebensat1] tv/when-sharks-attack-hai-alarm/video/11-florida-ganze-folge: Downloading webpage
[prosiebensat1] 4779896: Downloading videos JSON
[prosiebensat1] 4779896: Downloading sources JSON
[prosiebensat1] 4779896: Downloading urls JSON
[prosiebensat1] 4779896: Downloading f4m manifest
[prosiebensat1] 4779896: Downloading urls JSON
[prosiebensat1] 4779896: Downloading m3u8 information
[prosiebensat1] 4779896: Downloading urls JSON
[prosiebensat1] 4779896: Downloading MPD manifest
[prosiebensat1] 4779896: Downloading urls JSON
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[info] Available formats for 4779896:
format code         extension  resolution note
hls-meta            mp4        multiple   Quality selection URL 
dash-audio=64000    m4a        audio only [de] DASH audio   64k , mp4a.40.2 (48000Hz)
dash-audio=96000    m4a        audio only [de] DASH audio   96k , mp4a.40.2 (48000Hz)
dash-audio=128000   m4a        audio only [de] DASH audio  128k , mp4a.40.2 (48000Hz)
dash-video=200000   mp4        416x234    [de] DASH video  200k , avc1.42C00D, video only
dash-video=400000   mp4        480x270    [de] DASH video  400k , avc1.42C015, video only
dash-video=600000   mp4        640x360    [de] DASH video  600k , avc1.42C01E, video only
dash-video=1200000  mp4        640x360    [de] DASH video 1200k , avc1.42C01E, video only
dash-video=1800000  mp4        960x540    [de] DASH video 1800k , avc1.4D401F, video only
dash-video=2200000  mp4        960x540    [de] DASH video 2200k , avc1.4D401F, video only
dash-video=2500000  mp4        1280x720   [de] DASH video 2500k , avc1.4D401F, video only
dash-video=3500000  mp4        1280x720   [de] DASH video 3500k , avc1.4D401F, video only
hds-264             flv        416x234     264k 
hls-280             mp4        416x234     280k , avc1.42C00D, mp4a.40.2
hds-496             flv        480x270     496k 
hls-526             mp4        480x270     526k , avc1.42C015, mp4a.40.2
hds-728             flv        640x360     728k 
hls-772             mp4        640x360     772k , avc1.42C01E, mp4a.40.2
http-1296           mp4        unknown    1296k 
hds-1328            flv        640x360    1328k 
hls-1408            mp4        640x360    1408k , avc1.42C01E, mp4a.40.2
http-1896           mp4        unknown    1896k 
hds-1928            flv        960x540    1928k 
hls-2044            mp4        960x540    2044k , avc1.4D401F, mp4a.40.2
hds-2328            flv        960x540    2328k 
hls-2468            mp4        960x540    2468k , avc1.4D401F, mp4a.40.2
hds-2628            flv        1280x720   2628k 
hls-2786            mp4        1280x720   2786k , avc1.4D401F, mp4a.40.2
hds-3628            flv        1280x720   3628k 
hls-3846            mp4        1280x720   3846k , avc1.4D401F, mp4a.40.2 (best)
```

### Description of your *issue*, suggested solution and other information

The actual download worked fine, again, I'm just following the request after the "WARNING:" to report this as a bug. ;-)

**Comment by ThomasChr** [comment]
I have a patch, how do I include it? Pull request?

diff --git a/youtube_dl/extractor/prosiebensat1.py b/youtube_dl/extractor/prosiebensat1.py
index 03e1b1f..9a7a07f 100644
--- a/youtube_dl/extractor/prosiebensat1.py
+++ b/youtube_dl/extractor/prosiebensat1.py
@@ -349,6 +349,7 @@ class ProSiebenSat1IE(ProSiebenSat1BaseIE):
         r'<p class="att-description">\s*(.+?)\s*</p>',
         r'<p class="video-description" itemprop="description">\s*(.+?)</p>',
         r'<div[^>]+id="veeseoDescription"[^>]*>(.+?)</div>',
+        r'<meta property="og:description" content="(.*?)">',
     ]
     _UPLOAD_DATE_REGEXES = [
         r'<meta property="og:published_time" content="(.+?)">',
