### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by garilla22** [rg3/youtube-dl#11827]
This happened when I was going to download anime channel. URL: https://www.youtube.com/playlist?list=PLvLLdpIEhbhxBG4xiE6tHOHEk4yvKnUYR
Here are screenshots
![screenshot_2017-01-12-14-52-34](https://cloud.githubusercontent.com/assets/19745988/22250612/a088c69c-e258-11e6-84f4-ea6911c208f0.png)
![screenshot_2017-01-12-14-52-58](https://cloud.githubusercontent.com/assets/19745988/22250613/a0974136-e258-11e6-830c-8bddcde447cb.png)

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
