### ISSUE TITLE
yb file broken? how to start from point onwards

### ISSUE THREAD

**Issue by rubiohiguey** [rg3/youtube-dl#1182]
I am trying to use youtube-dl

youtube-dl -f 22 -o reydavid01.mp4 http://www.youtube.com/watch?v=fRwA0IagPik

The problem is that HD version (fmt 22) stops at 20% and 480p version stops at 67%. I cannot get past this point
Looks like the video file is broken. Even when I get the exact HTML link through DownloadHelper and use wget, it only gets to this particular % point.

BUT I can see the whole youtube video online fine. So I want to know if there is any way to start downloading form certain byte-point (e.g 328556227 onwards) or form a specific time point (e.g. 10 minutes 3 seconds). If this was possible I still might be able to download video in chunks.

Thank you.

**Comment by naglis** [comment]
Duplicate of #1184.
