### ISSUE TITLE
VRTNU.be - new extractor needed

### ISSUE THREAD

**Issue by midas02** [rg3/youtube-dl#11829]
Hello guys, a bit of work for you.

Flemish broadcaster VRT has just launched their new video on demand website. You should be able to find it on http://VRTNU.be, which redirects to http://vrt.be/vrtnu.

So a new extractor will be required. Mind you, the videos use the exact same streaming engine as the existing VRT websites (deredactie.be, canvas.be, een.be, ketnet.be), for which extractors already exist (vrt.py/canvas.py/ketnet.py), so I trust you should be able to fit it into one of the existing ones.

Here's a sample video if you need one: https://www.vrt.be/vrtnu/a-z/het-journaal.relevant/

Oh, and by the way, they propose live streaming as well now. That wasn't the case before. You'll find the links here (just click on one of the channel logos): https://www.vrt.be/vrtnu/kanalen/een
Live channels stream from live.stream.vrt.be, whereas the VoDs stream from vod.stream.vrt.be. Up to you if you want to implement live stream capturing as well.

Rgds

**Comment by mrBliss** [comment]
I have got something working here: mrBliss/youtube-dl@b57d1a655e3635e49835e73fee9c4a9e140a391f
Please try it out on some more videos.

I haven't looked at live streaming yet.

Before I submit a pull request I have to figure out the policy on tests for sites requiring authentication.

**Comment by belgicano** [comment]
Any update on the extractor? 

And/or could someone explain me how I can test this?:
https://github.com/mrBliss/youtube-dl/commit/b57d1a655e3635e49835e73fee9c4a9e140a391f

**Comment by Invictaz** [comment]
How can I test this on Windows?

**Comment by bertvandepoel** [comment]
I can confirm this works on Linux with https://github.com/mrBliss/youtube-dl/commit/57fc66764242654892928a69d444467c7586fc95 (latest commit on the vrtnu branch)

**Comment by SamyCoenen** [comment]
Yep just did a git clone of rg3/youtube-dl, cd youtube-dl && git checkout vrtnu && make && ./youtube-dl http://www.vrt.be/vrtnu/a-z/reizen-waes/3/reizen-waes-s3a10-compilatie/ --username . --password .
and had a successful download

**Comment by thibmaek** [comment]
What if your account is a Facebook account? Will that work by just providing those details?

**Comment by bertvandepoel** [comment]
I logged in using facebook, then chose to change my password inside VRTNU. So it's a bit weird, but it works.

**Comment by githuba98** [comment]
I think you have to create an new extractor e.g. VRTNU, because i can't see the extractor changing in the master
