### ISSUE TITLE
youtube-dl no longer works on Chaturbate

### ISSUE THREAD

**Issue by randyrandersn** [rg3/youtube-dl#11824]
They seem to have changed the way they stream, now I get...
```
$ youtube-dl https://chaturbate.com/[room-id]
[Chaturbate] [room-id]: Downloading webpage
ERROR: Room is currently offline
```
Room is not offline.

Same behaviour in both Windows and Linux.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
