### ISSUE TITLE
Some youtube videos not working (UnavailableVideoError)

### ISSUE THREAD

**Issue by StevenHickson** [rg3/youtube-dl#1183]
Things were working fine around late July and I updated to the newest version but now I'm getting a weird error:

$ uname -a
Linux Fedora 3.8.11-200.fc18.x86_64

$ python --version
Python 2.7.3

$ youtube-dl --version
2013.08.02

$ youtube-dl -v --no-check-certificate -t "https://www.youtube.com/watch?v=mEpfyBOdKxU"
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['-v', '--no-check-certificate', '-t', 'https://www.youtube.com/watch?v=mEpfyBOdKxU']
[debug] youtube-dl version 2013.08.02
[debug] Python version 2.7.3 - Linux-3.8.11-200.fc18.x86_64-x86_64-with-fedora-18-Spherical_Cow
[debug] Proxy map: {}
[youtube] Setting language
[youtube] mEpfyBOdKxU: Downloading video webpage
[youtube] mEpfyBOdKxU: Downloading video info webpage
[youtube] mEpfyBOdKxU: Extracting video information
[youtube] mEpfyBOdKxU: Encrypted signatures detected.
[youtube] encrypted signature length 83 (42.40), itag 46, html5 player vflI2-Cew
[youtube] encrypted signature length 83 (42.40), itag 37, html5 player vflI2-Cew
[youtube] encrypted signature length 83 (42.40), itag 45, html5 player vflI2-Cew
[youtube] encrypted signature length 83 (42.40), itag 22, html5 player vflI2-Cew
[youtube] encrypted signature length 81 (40.40), itag 44, html5 player vflI2-Cew
[youtube] encrypted signature length 83 (42.40), itag 35, html5 player vflI2-Cew
[youtube] encrypted signature length 83 (42.40), itag 43, html5 player vflI2-Cew
[youtube] encrypted signature length 83 (42.40), itag 34, html5 player vflI2-Cew
[youtube] encrypted signature length 83 (42.40), itag 18, html5 player vflI2-Cew
[youtube] encrypted signature length 83 (42.40), itag 5, html5 player vflI2-Cew
[youtube] encrypted signature length 83 (42.40), itag 36, html5 player vflI2-Cew
[youtube] encrypted signature length 83 (42.40), itag 17, html5 player vflI2-Cew
ERROR: unable to download video
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 573, in download
    videos = self.extract_info(url)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 327, in extract_info
    return self.process_ie_result(ie_result, download=download)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 410, in process_ie_result
    for r in ie_result['entries']
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 357, in process_ie_result
    self.process_info(ie_result)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 550, in process_info
    raise UnavailableVideoError()
UnavailableVideoError

**Comment by dstftw** [comment]
Works with latest version. Closing.
