### ISSUE TITLE
[Youtube] ERROR: Incomplete YouTube ID

### ISSUE THREAD

**Issue by j16180339887** [rg3/youtube-dl#11839]
```
$ youtube-dl "https://www.youtube.com/watch?v=NBWv5GWODaE"
ERROR: Incomplete YouTube ID NBWv5GWDaE. URL https://www.youtube.com/watch?v=NBWv5GWDaE looks truncated.
```

youtube-dl with -v flag:

```
$ youtube-dl -v "https://www.youtube.com/watch?v=NBWv5GWODaE"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=NBWv5GWDaE']
[debug] Encodings: locale UTF-8, fs utf-8, out utf8, pref UTF-8
[debug] youtube-dl version 2017.01.25
[debug] Python version 3.4.5 - CYGWIN_NT-10.0-2.6.1-0.305-5-3-x86_64-64bit-WindowsPE
[debug] exe versions: ffmpeg git-2016-12-10-edb4f5d, ffprobe git-2016-12-10-edb4f5d
[debug] Proxy map: {}
ERROR: Incomplete YouTube ID NBWv5GWDaE. URL https://www.youtube.com/watch?v=NBWv5GWDaE looks truncated.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 359, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 2566, in _real_extract
    expected=True)
youtube_dl.utils.ExtractorError: Incomplete YouTube ID NBWv5GWDaE. URL https://www.youtube.com/watch?v=NBWv5GWDaE looks truncated.
```

What's this? thanks!

**Comment by dstftw** [comment]
Read the error message. https://www.youtube.com/watch?v=NBWv5GWDaE is not a valid video URL.

**Comment by j16180339887** [comment]
Oh, I know what the problem is.

URL is [https://www.youtube.com/watch?v=NBWv5GWODaE](https://www.youtube.com/watch?v=NBWv5GWODaE)

But I have this code in my .zshrc

```
bindkey "OC" forward-word
bindkey "OD" backward-word
```

So [https://www.youtube.com/watch?v=NBWv5GWODaE](https://www.youtube.com/watch?v=NBWv5GWODaE)

becomes [https://www.youtube.com/watch?v=NBWv5GWDaE](https://www.youtube.com/watch?v=NBWv5GWDaE)

:p

**Comment by kabirnayeem99** [comment]
Facing the same problem on **Windows 10** on **Powershell** with **Youtube-DL 2021.03.03**. The command was-
` youtube-dl https://www.youtube.com/watch?v=ho91w`
The error was-
`ERROR: Incomplete YouTube ID ho91w. URL https://www.youtube.com/watch?v=ho91w looks truncated.`

**Comment by z0xyz** [comment]
I had the same error , and indeed the video URL i passed to youtube-dl by the shell got one or two letters truncated ; due to the fact the URL in my case contained the capital letter "F" which was bound as a key binding within the .bashrc file .

**Comment by jazzman1825** [comment]
Faced the same issue. Just launch the yt-dlp from cmd, not powershell.
