### ISSUE TITLE
[mtv] Unsupported URL (looks like MTV changed something again)

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#11837]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.25**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
E:\>youtube-dl http://www.mtv.com/episodes/g8xu7q/teen-mom-2-breaking-the-wall-season-7-ep-713 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.mtv.com/episodes/g8xu7q/teen-mom-2-breaking-the-wall-season-7-ep-713', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.25
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[generic] teen-mom-2-breaking-the-wall-season-7-ep-713: Requesting header
WARNING: Falling back on generic information extractor.
[generic] teen-mom-2-breaking-the-wall-season-7-ep-713: Downloading webpage
[generic] teen-mom-2-breaking-the-wall-season-7-ep-713: Extracting information
ERROR: Unsupported URL: http://www.mtv.com/episodes/g8xu7q/teen-mom-2-breaking-the-wall-season-7-ep-713
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppmszswf3\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppmszswf3\build\youtube_dl\extractor\common.py", line 359, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppmszswf3\build\youtube_dl\extractor\generic.py", line 2551, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.mtv.com/episodes/g8xu7q/teen-mom-2-breaking-the-wall-season-7-ep-713
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.mtv.com/episodes/g8xu7q/teen-mom-2-breaking-the-wall-season-7-ep-713

As of 2017-01-25, this is a "free" video.

---

### Description of your *issue*, suggested solution and other information

This worked for about a week, but it would appear that MTV changed something yet again.

**Comment by joetex72** [comment]
They did change something. I was gonna open an issue the other day.

"full-episodes"
`http://www.mtv.com/full-episodes/94bd0m/sweet-vicious-the-blueprint-season-1-ep-101`

now resolves to just "episodes" (dropping the "full-")
`http://www.mtv.com/episodes/94bd0m/sweet-vicious-the-blueprint-season-1-ep-101`

**Comment by StevenDTX** [comment]
Thanks, @joetex72.  I modified my script to replace `/episodes/` with `/full-episodes/` and it works just fine.
