### ISSUE TITLE
yb file broken? how to start from point onwards

### ISSUE THREAD

**Issue by rubiohiguey** [rg3/youtube-dl#1184]
I have a problem downloading a certain file from youtube.

youtube-dl http://www.youtube.com/watch?v=fRwA0IagPik

it gets to the point where

[download]  20.4% of 1.70GiB at  1.39MiB/s ETA 16:39
ERROR: content too short (expected 1828409431 bytes and served 373290937)

When i try to resume get the error

[download] Resuming download at byte 373290937
ERROR: Did not get any data blocks

What can b wrong? Looks like this file is broken, because even why I try to download the whole youtube link with wget (I get the link from other software) it only gets to 373290937 bytes and stops there.

The video on yb seems fine because I can watch it form any time point onwards.

Can this issue be helped, and can i get yb to start downloading form certain point onward? e.g. from 16 minutes 30 seconds, etc.

Thank you.

**Comment by yan12125** [comment]
@rubiohiguey The first example is now private. Are problems still?
