### ISSUE TITLE
Site support for euronews.com 

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#11840]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

─[$] youtube-dl -vF "http://www.euronews.com/2017/01/25/naples-airport-growing-at-double-the-national-average"                      
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'http://www.euronews.com/2017/01/25/naples-airport-growing-at-double-the-national-average']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.25
[debug] Python version 2.7.13 - Linux-4.9.0-1-amd64-x86_64-with-debian-9.0
[debug] exe versions: ffmpeg 3.2.2-1, ffprobe 3.2.2-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] naples-airport-growing-at-double-the-national-average: Requesting header
WARNING: Falling back on generic information extractor.
[generic] naples-airport-growing-at-double-the-national-average: Downloading webpage
[generic] naples-airport-growing-at-double-the-national-average: Extracting information
[info] Available formats for 170124_FLWB_160A0-144304_E:
format code  extension  resolution note
0            mp4        unknown 

---

- Single Video - "http://www.euronews.com/2017/01/25/naples-airport-growing-at-double-the-national-average"                     

Saw that the video is served jw platform and have seen youtube being able to download some which are served by jwplatform so shouldn't be too much work.

**Comment by dstftw** [comment]
This is covered by the generic extractor.

**Comment by shirishag75** [comment]
@dstftw Sergey, if you think so, then why wasn't it able to extract the video, it should have extracted the video, right ?

**Comment by dstftw** [comment]
It did. See your log.

**Comment by shirishag75** [comment]
@dstftw at the very end it says - 

```
[info] Available formats for 170124_FLWB_160A0-144304_E:
format code extension resolution note
0 mp4 unknown
```

What am I supposed to read into that, there is a video file on that page, and it doesn't give info. about any format that I know/can understand about. Please explain.

**Comment by dstftw** [comment]
You've asked it to list formats with `-F`. It listed you an mp4 format. What's not clear here?
