### ISSUE TITLE
[youtube] Can't download entire video

### ISSUE THREAD

**Issue by Kagami** [rg3/youtube-dl#11847]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl -v "https://www.youtube.com/watch?v=wi1BefrfTos"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=wi1BefrfTos']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.25
[debug] Python version 3.4.5 - Linux-4.8.12-gentoo-r1-x86_64-Intel-R-_Core-TM-_i7-3820_CPU_@_3.60GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg N-83169-g8a1759a, ffprobe N-83169-g8a1759a, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] wi1BefrfTos: Downloading webpage
[youtube] wi1BefrfTos: Downloading video info webpage
[youtube] wi1BefrfTos: Extracting video information
[youtube] wi1BefrfTos: Downloading MPD manifest
[debug] Invoking downloader on 'https://r3---sn-uxap5a8-gpml.googlevideo.com/videoplayback?id=c22d4179fadf4e8b&itag=136&source=youtube&requiressl=yes&mn=sn-uxap5a8-gpml&mm=31&mv=u&pl=26&ms=au&ratebypass=yes&mime=video/mp4&gir=yes&clen=654308069&lmt=1472833972132499&dur=6406.432&upn=Hp5J3R4DeFw&signature=367D556D20C0705E7D5BE3F970B4B83424D4AEE2.9AE2DF9E840A312992B79C1B0C08B94C891FD19C&key=dg_yt0&mt=1485517903&ip=<removed>&ipbits=0&expire=1485539682&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,mm,mv,pl,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: SPIE Royalty-Free Video-wi1BefrfTos.f136.mp4
[download] 100% of 624.00MiB in 00:59
[debug] Invoking downloader on 'https://r3---sn-uxap5a8-gpml.googlevideo.com/videoplayback?id=c22d4179fadf4e8b&itag=140&source=youtube&requiressl=yes&mn=sn-uxap5a8-gpml&mm=31&mv=u&pl=26&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=101751371&lmt=1472834118433895&dur=6406.501&upn=Hp5J3R4DeFw&signature=6B42F7A09C5686603ECC2E601DDC4AEB266B0206.34DBCD929107733DF316DF309C75214E2765F681&key=dg_yt0&mt=1485517903&ip=<removed>&ipbits=0&expire=1485539682&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,mm,mv,pl,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: SPIE Royalty-Free Video-wi1BefrfTos.f140.m4a
[download] 100% of 97.04MiB in 00:09
[ffmpeg] Merging formats into "SPIE Royalty-Free Video-wi1BefrfTos.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:SPIE Royalty-Free Video-wi1BefrfTos.f136.mp4' -i 'file:SPIE Royalty-Free Video-wi1BefrfTos.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:SPIE Royalty-Free Video-wi1BefrfTos.temp.mp4'
Deleting original file SPIE Royalty-Free Video-wi1BefrfTos.f136.mp4 (pass -k to keep)
Deleting original file SPIE Royalty-Free Video-wi1BefrfTos.f140.m4a (pass -k to keep)

$ ffprobe -hide_banner SPIE\ Royalty-Free\ Video-wi1BefrfTos.mp4 |& grep Duration
  Duration: 01:46:46.50, start: 0.000000, bitrate: 948 kb/s
```

### Description of your *issue*, suggested solution and other information

Downloaded video has 1h46m47s duration, although [in web browser](https://www.youtube.com/watch?v=wi1BefrfTos) I can watch the entire 3h42m27s talk. What might be the reason for that?

Note that at [videos page](https://www.youtube.com/channel/UCK2q3q4dshZHzn-EP3ZdUeA/videos) duration of this video is specified to be 1h46m47s, the same duration being downloaded.

**Comment by ThomasChr** [comment]
Note: I can only view 1:46:46 in the Browser (using Firefox 50.1.0).
I have no problem to view the entire 3:42:27 in Chrome (55.0).

So this problem seems not to be (only) related to youtube-dl. There's more going on.

**Comment by dstftw** [comment]
All mp4 formats served for this video are truncated at 01:46:46.46 while webms are complete. mp4 happens to be the `bestvideo` format for this video that's why you get a video file of 01:46:46.46 length. In browser you are most likely served with webm.
