### ISSUE TITLE
multiple URLs on command-line: stops at first private youtube URL

### ISSUE THREAD

**Issue by jpluimers** [rg3/youtube-dl#11860]
(note I've obfuscated the username and URLs below as they are not to be publicised)

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.28*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.28**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v --username someone@example.org https://youtu.be/link1 https://youtu.be/link2 https://youtu.be/link3 https://youtu.be/link4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--username', u'PRIVATE', u'https://youtu.be/link1', u'https://youtu.be/link2', u'https://youtu.be/link3', u'https://youtu.be/link4']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.28
[debug] Python version 2.7.10 - Darwin-16.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
[youtube] link1: Downloading webpage
[youtube] link1: Downloading video info webpage
[youtube] link1: Extracting video information
[youtube] link1: Downloading MPD manifest
[youtube] link1: Downloading MPD manifest
[download] The Composer Animatie Deel 5-link1.mp4 has already been downloaded and merged
[youtube] link2: Downloading webpage
[youtube] link2: Downloading video info webpage
ERROR: link2: YouTube said: This video is private.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 359, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1379, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: link2: YouTube said: This video is private.
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Youtube-dl finished downloading link1, then finds out link2 is private but does not continue with the rest of the links.

I expected youtube-dl to continue trying to download with link3 and further so it can show which of the links were OK and which ones were private.

This saves running youtube-dl multiple times with different URLs each requiring entering the password manually.

I can share affected URLs privately if needed to solve the issue.

**Comment by dstftw** [comment]
This is expected behavior. Use `-i`.
