### ISSUE TITLE
Support for http://onwathseries.to urls with simple base64 decode

### ISSUE THREAD

**Issue by torriem** [rg3/youtube-dl#11879]
Youtube-dl does not support downloading from  http://onwathseries.to currently, since the actual video url (which youtube-dl often can download from) is obfuscated by javascript.  However it turns out the obfuscation is very simple and you don't even need to retrieve the http://onwatchseries.to video page to get it.  Most urls look like this:

http://onwatchseries.to/cale.html?r=STRING

Where STRING turns out to be the base64 encoding of the actual video url.  I may try my hand at a handler.  But in the meantime if someone else gets to it, it's very simple.

**Comment by yan12125** [comment]
Please give real examples.

**Comment by torriem** [comment]
Here's an example show page: http://onwatchseries.to/episode/adventures_of_superman_s6_e12.html

Here are the onwatchseries.to urls that page contains:
http://onwatchseries.to/cale.html?r=aHR0cDovL2dvcmlsbGF2aWQuaW4vdjRyenZiYnFqc3hk
http://onwatchseries.to/cale.html?r=aHR0cDovL2dvcmlsbGF2aWQuaW4vbjFqNjAyaGgxZ2gx
http://onwatchseries.to/cale.html?r=aHR0cDovL2RhY2xpcHMuaW4vYWhmeWF3dnF2aHlj
http://onwatchseries.to/cale.html?r=aHR0cDovL2RhY2xpcHMuaW4vOTVzaGIzcGp6dHU0
http://onwatchseries.to/cale.html?r=aHR0cDovL21vdnBvZC5pbi82OHpzdGllZGpzZW4=
http://onwatchseries.to/cale.html?r=aHR0cDovL21vdnBvZC5pbi90MTE0ZnZvejV4eW4=
http://onwatchseries.to/cale.html?r=aHR0cDovL21vdnBvZC5pbi9ldHp5ZThoODFieWc=
http://onwatchseries.to/cale.html?r=aHR0cDovL21vdnBvZC5pbi9mcHR1bHB0dm52dTY=
http://onwatchseries.to/cale.html?r=aHR0cDovL21vdnBvZC5pbi96ZnNwZ3lieGp3ZWk=
http://onwatchseries.to/cale.html?r=aHR0cDovL2dvcmlsbGF2aWQuaW4vcmxtNHRmcHMxMDlt
http://onwatchseries.to/cale.html?r=aHR0cDovL2dvcmlsbGF2aWQuaW4vYjB3Zm01ODhoMG9r
http://onwatchseries.to/cale.html?r=aHR0cDovL2dvcmlsbGF2aWQuaW4vcTBtMzVuOG16Nmw5
http://onwatchseries.to/cale.html?r=aHR0cDovL2RhY2xpcHMuaW4vb3BlNTVuM2c1enY0
http://onwatchseries.to/cale.html?r=aHR0cDovL2RhY2xpcHMuaW4vZ3A1YWtlbHI3cjB0

And here are the base64 decoded values for the above urls--many of which youtube-dl already has handlers for which is all we need to worry about in my opinion:
http://gorillavid.in/v4rzvbbqjsxd
http://gorillavid.in/n1j602hh1gh1
http://daclips.in/ahfyawvqvhyc
http://daclips.in/95shb3pjztu4
http://movpod.in/68zstiedjsen
http://movpod.in/t114fvoz5xyn
http://movpod.in/etzye8h81byg
http://movpod.in/fptulptvnvu6
http://movpod.in/zfspgybxjwei
http://gorillavid.in/rlm4tfps109m
http://gorillavid.in/b0wfm588h0ok
http://gorillavid.in/q0m35n8mz6l9
http://daclips.in/ope55n3g5zv4
http://daclips.in/gp5akelr7r0t

**Comment by torriem** [comment]
I suppose the ideal would be to have the handler work with the onwatchseries.to episode page and parse out and try the list of urls, but I think just recognizing an individual base64-encoded url manually copied and pasted would be sufficient.  Fairly low priority since it's trivial to write a wrapper bash script around youtube-dl, which is what I've done for now.

**Comment by remitamine** [comment]
the site link to copyrighted content that they don't have rights to distribute.

**Comment by yan12125** [comment]
Yep sorry for didn't notice that. @torriem do you have other examples?

**Comment by torriem** [comment]
I'll take a look and get back to you later today.

**Comment by torriem** [comment]
Closing this request.
