### ISSUE TITLE
If a video is no longer available the entire query array is stopped short

### ISSUE THREAD

**Issue by Mochlate** [rg3/youtube-dl#11881]
The third video in this list "is not available", but the fourth is.  In this case you only get the first 2 back, is this a known bug?  It should either return an empty object or just ignore the object all together.  Not just ignore the rest.

Is there any way around this or ?

```
var youtubedl = require('youtube-dl');
var queryArr = [ 'https://www.youtube.com/watch?v=NCuoBRAgwJE',
   		 'https://www.youtube.com/watch?v=KX4GNDb4RSI',
  		 'https://www.youtube.com/watch?v=tn8IK7YtOYE',
  		 'https://www.youtube.com/watch?v=R4obXWnK3Xo' ];
youtubedl.getInfo(queryArr, [], {maxBuffer: 10000*1024}, function(err, info) {
  if (err) throw err;
  for(s in info) {
    console.log(info[s].webpage_url);
  }
});
```

**Comment by jaimeMF** [comment]
You are using a javascript module for youtube-dl, you should report the issue to them.

A way to solve it (if the module allows it) is to pass the `--ignore-errors` option, it will skip the video that is not available.
