### ISSUE TITLE
randomize playlist order, i.e.  --playlist-random

### ISSUE THREAD

**Issue by glenn-slayden** [rg3/youtube-dl#11889]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.29**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)

Please add support for **randomizing the playlist** download order via  `--playlist-random` (or whatever other switch name).

Since there is already an option for `--reverse-playlist`, I don't think this should be too hard? (I'd contribute it myself if I was more confident in my python skills.)

The motivation for this feature is that it could be used in conjunction with `--max-downloads` (i.e. set to a low value) to randomly "sample" a variety of videos from across a channel with lots of videos, as opposed to just being able to get the first few (or last few, using `--reverse-playlist`).

**Comment by glenn-slayden** [comment]
I should also add that the "random sampling" scenario I outlined above should be possible because you would be able to combine it with `--download-archive` to ensure that you don't get repeated videos in the random selection.

Here I'm referencing the fact `youtube-dl` already does the correct thing when you combine `--download-archive` with `--max downloads N`, namely, that you get the ***next*** "N" files that you haven't already downloaded--as opposed to "the ***N-or-fewer*** files  out of the ***first N*** according to the selected playlist order." The latter is a perfectly valid interpretation—and could have been the implemented behavior—for the interaction between `--max-downloads` and `--download-archive` when both switches are present.

**Comment by ThomasChr** [comment]
New parameter added. Pull request created.

**Comment by ThomasChr** [comment]
Oh, I tested my code with '--max-downloads' and '--download-archive' - seems to work as intended!

**Comment by yan12125** [comment]
Thanks to @ThomasChr, there's --playlist-random now!

**Comment by glenn-slayden** [comment]
Very many thanks!
