### ISSUE TITLE
[spiderman.marvelkids.com] Site Support

### ISSUE THREAD

**Issue by joetex72** [rg3/youtube-dl#11882]
### What is the purpose of your *issue*?
- [x ] Site support request (request for adding support for a new site)

- Single video: http://spiderman.marvelkids.com/videos/ultimate-spider-man-attack-of-the-synthezoids

Is it possible to add support for this Disney site?
```
C:\>youtube-dl http://spiderman.marvelkids.com/videos/ultimate-spider-man-attack-of-the-synthezoids --verbose
[debug] System config: []
[debug] User config: ['-o', 'G:\\Video\\Audials Imported Movies\\%(extractor)s-%(timestamp)s %(title)s.%(ext)s', '--write-sub', '--add-metadata', '--ignore-errors', '--prefer-ffmpeg']
[debug] Custom config: []
[debug] Command-line args: ['http://spiderman.marvelkids.com/videos/ultimate-spider-man-attack-of-the-synthezoids', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.29
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: avconv v12_dev0-3162-gf01f7a7, avprobe v12_dev0-3162-gf01f7a7, ffmpeg N-83133-ge664730, ffprobe N-83133-ge664730, rtmpdump 2.4-20151223-gfa8646d-LibreSSL_2.5.0-x86_64-static
[debug] Proxy map: {}
[generic] ultimate-spider-man-attack-of-the-synthezoids: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ultimate-spider-man-attack-of-the-synthezoids: Downloading webpage
[generic] ultimate-spider-man-attack-of-the-synthezoids: Extracting information
ERROR: Unsupported URL: http://spiderman.marvelkids.com/videos/ultimate-spider-man-attack-of-the-synthezoids
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\generic.py", line 2551, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://spiderman.marvelkids.com/videos/ultimate-spider-man-attack-of-the-synthezoids
```

**Comment by ThomasChr** [comment]
I can't view the video with the direct link you provided. I just get redirected to http://marvelkids.disney.de/spiderman/

**Comment by 0x8BADFOOD** [comment]
I've checked. Video is available for me. No redirect.

**Comment by joetex72** [comment]
I don't think it can be viewed from Germany which is why you got redirected.

**Comment by gkoelln** [comment]
Here is my proposal: https://github.com/gkoelln/youtube-dl/raw/Disney/youtube_dl/extractor/disney.py

**Comment by joetex72** [comment]
That works, [gkoelln](https://github.com/gkoelln).

**Comment by gkoelln** [comment]
Shortened:
https://github.com/gkoelln/youtube-dl/raw/Disney/youtube_dl/extractor/disney.py
https://github.com/gkoelln/youtube-dl/raw/Disney/youtube_dl/extractor/extractors.py

**Comment by gkoelln** [comment]
I would do a PR, but I'm afraid my fork is so screwed up and I can't figure out how to remove and/or squash some commits.

**Comment by ThomasChr** [comment]
Just switch to your feature branch and do: git rebase -i master

Than type s in front of the commits you would like to squash. Piece of cake :-)

**Comment by gkoelln** [comment]
My master is what's screwed up.  I accidentally commited some changes to the master instead of just a branch, or doing a PR.  I feel like I may need do just delete my repository and start over.

**Comment by ThomasChr** [comment]
Just reset your head to the last "official" commit with "git reset SHA1 --hard". Then add the official repository as upstream and do a "pull upstream master". Should be a fast forward pull now without any problems.

**Comment by ThomasChr** [comment]
Oh, if you need your commits on another branch you should put them there by checking out the branch and rebasing it from master.

**Comment by yan12125** [comment]
You can move branches with ```git branch -f```. There's no need to do rebasing in this case

**Comment by joetex72** [comment]
StarWars works but marvelkids got broken with the shortened fix. Getting **ERROR: no suitable InfoExtractor for URL**.

**Comment by gkoelln** [comment]
Thanks, @remitamine!

**Comment by joetex72** [comment]
Do you still have the long fix you had first @gkoelln ? The fix being used now seem to be missing the 1080p qualities for full episodes (clips are okay) on  **spiderman.marvelkids.com**. They were available with your first fix.

**Comment by gkoelln** [comment]
Are you sure the 1080p version is available?  I checked http://spiderman.marvelkids.com/videos/graduation-day-part-1 source and it doesn't seem to have 1080p available.

**Comment by joetex72** [comment]
That's the thing, 1080p doesn't show up anymore for full episodes but it did before. Unless they removed them.

**Comment by remitamine** [comment]
qualities heigher than 480p for full episodes are protected by Adobe Flash Access.
