### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by loheer** [rg3/youtube-dl#11907]
### Description of your *issue*, suggested solution and other information

mpsyt --debug --logging
mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.2 (youtube-dl backend)
youtube-dl version : 2016.12.01
Python version     : 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Linux-4.9.0-1-amd64-x86_64-with-debian-9.0
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/helohe/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.utf8
env:LANGUAGE       : en_US:en
--

Enter /search-term to search or [h]elp                                          
> /bach cello
--

Searching for 'bach cello'                                             
--

Num  Title                                                               Time
 1   J.S. Bach Cello Suites No.1-6 BWV 1007-1012, Ralph Kirshbaum     2:21:03
 2   Mischa Maisky plays Bach Cello Suite No.1 in G (full)              19:28
 3   J.S. Bach - The six cello suites - Pau Casals, 1936/39           2:10:12
 4   Yo Yo Ma - Bach Six Cello Suites - BBC Proms 2015                2:42:38
 5   Jean-Guihen Queyras - J.S.Bach, Cello Suites                     2:10:01
 6   J.S. Bach - Suites for cello solo - Antonio Janigro (1954)       2:30:17
 7   The Cello Song - (Bach is back with 7 more cellos) - The Piano     03:59
 8   Bach - Cello Suite No. 1 in G Major BWV1007 - Mov. 1-3/6           09:28
 9   Bach Cello Suite No.1 - Prelude (Yo-Yo Ma)                         02:46
10   Ophélie Gaillard, Bach, Prelude, Cello suite n. 1                  02:57
11   Jacqueline du Pré - Bach, Suites for Solo Cello No. 1 & 2          41:39
12   Yo-Yo Ma Bach Cello Suite No.1 in G Major                          18:19
13   Bach, Cello suite Nº 1 (completa) Música Clásica                   18:43
14   Inbal Segev performs Bach's Cello Suite No. 1 in G major: Prelu    03:03
15   (FULL ALBUM) Bach - Cello Suites No.1, 3 and 5 - Prelude - Robe    69:50
16   Rostropovich plays the Prelude from Bach's Cello Suite No. 1       02:00
17   BACH - SUITE PARA VIOLONCHELO 1 - MSTISLAV ROSTROPOVICH \m/        16:38
18   Yo-Yo Ma Bach Cello Suite No  6 in D Major                         31:55
19   Bach Cello Suite 1 Prelude BWV1007 Bono Bass Solo                  02:04
20   Bach Chaconne for Four Cellos                                      14:22

Search results for bach cello                           [1/25>
> ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/usr/lib/python3/dist-packages/youtube_dl/utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Oliy1492** [comment]
I have the same error :/

**Comment by gise88** [comment]
me too

**Comment by Novanormandy** [comment]
same here... it worked 2 days ago, did youtube change something?

**Comment by Oliy1492** [comment]
From what I heard youtube changed something that broke how youtube-dl works and my friend said they usually get a fix pretty fast, but who knows how long it will be.

**Comment by ThomasChr** [comment]
@Oliy1492 In fact: It's already resolved. Khang-NT has provided a fix for the problem and as soon as this fix has been added to youtube-dl it'll work just fine.
If you feel up to it you can use the fix on your own version to make it work again.

**Comment by Oliy1492** [comment]
Thanks so much you are my hero

**Comment by ThomasChr** [comment]
I think @Khang-NT is the hero here :-)
