### ISSUE TITLE
Bug: Signature extraction failed

### ISSUE THREAD

**Issue by ZacharieALES** [rg3/youtube-dl#11909]
Hello,

I am using version 2017.01.29 on Kubuntu 15.04. I am using the following command:

`$ youtube-dl --verbose -q -t --extract-audio --audio-format mp3  https://www.youtube.com/watch?v=Yq4KA0mUnC8
`

And I obtain the following error:

    [debug] System config: []

    [debug] User config: []

    [debug] Custom config: []

    [debug] Command-line args: [u'--verbose', u'-q', u'-t', u'--extract-audio', u'--audio-format', u'mp3', u'https://www.youtube.com/watch?v=Yq4KA0mUnC8']

    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8

    [debug] youtube-dl version 2017.01.29

    [debug] Python version 2.7.9 - Linux-3.19.0-68-generic-x86_64-with-Ubuntu-15.04-vivid

    [debug] exe versions: ffmpeg 2.5.10-0ubuntu0.15.04.1, ffprobe 2.5.10-0ubuntu0.15.04.1, rtmpdump 2.4

    [debug] Proxy map: {}

    ERROR: Signature extraction failed: Traceback (most recent call last):

    File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s

    File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)

    File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)

    File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle

    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)

    File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)

    File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)

    File "/usr/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()

    File "/usr/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original

    ValueError: unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js
    (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

The complete error message contained three identical tracebacks but I just kept the first one.

Do you know why I obtain this error?

**Comment by gise88** [comment]
duplicate: https://github.com/rg3/youtube-dl/issues/11907

**Comment by ThomasChr** [comment]
@gise88: I'm counting 12 duplicates as of now.
I've provided a list in the Pull Request to solve the issue: https://github.com/rg3/youtube-dl/pull/11892

**Comment by gise88** [comment]
Ehehehe! From a great lib comes a lot of issues.. Just kidding! I didn't count them.. Thanks for the reference of the pr! I'm waiting for the merge/release..
