### ISSUE TITLE
[BUG] Unable to download from rtbf.be

### ISSUE THREAD

**Issue by Animis09** [rg3/youtube-dl#11923]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.31*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---
```
youtube-dl -v www.rtbf.be/auvio/emissions/detail_les-carnets-d-emeraude?id=10823 -F
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'www.rtbf.be/auvio/emissions/detail_les-carnets-d-emeraude?id=10823', '-F']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.31
[debug] Python version 3.2.3 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-7
[debug] exe versions: ffmpeg 2.2.2, ffprobe 2.2.2, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[generic] detail_les-carnets-d-emeraude?id=10823: Requesting header
WARNING: Falling back on generic information extractor.
[generic] detail_les-carnets-d-emeraude?id=10823: Downloading webpage
[generic] detail_les-carnets-d-emeraude?id=10823: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[info] Available formats for detail_les-carnets-d-emeraude?id=10823:
format code  extension  resolution note
0            ogg        unknown
1            webm       unknown
2            mp4        unknown    (best)
[download] Downloading video 2 of 2
[info] Available formats for detail_les-carnets-d-emeraude?id=10823:
format code  extension  resolution note
0            ogg        unknown
1            webm       unknown
2            mp4        unknown    (best)
[download] Finished downloading playlist: None


root@tuvserver:~# youtube-dl -v www.rtbf.be/auvio/emissions/detail_les-carnets-d-emeraude?id=10823 -f 2
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'www.rtbf.be/auvio/emissions/detail_les-carnets-d-emeraude?id=10823', '-f', '2']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.31
[debug] Python version 3.2.3 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-7
[debug] exe versions: ffmpeg 2.2.2, ffprobe 2.2.2, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[generic] detail_les-carnets-d-emeraude?id=10823: Requesting header
WARNING: Falling back on generic information extractor.
[generic] detail_les-carnets-d-emeraude?id=10823: Downloading webpage
[generic] detail_les-carnets-d-emeraude?id=10823: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[debug] Invoking downloader on 'http://www.rtbf.be/auvio/emissions/{{ mp4_video }}'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.2/urllib/request.py", line 376, in open
    response = meth(req, response)
  File "/usr/lib/python3.2/urllib/request.py", line 488, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.2/urllib/request.py", line 414, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 348, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 496, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Thank you for your help.

**Comment by Animis09** [comment]
Any idea ?

**Comment by yan12125** [comment]
rtbf.py needs rewriting. Now it uses <iframe> with embedded data instead of the old API endpoint: http://www.rtbf.be/auvio/embed/media?id=2182605&autoplay=0

**Comment by remitamine** [comment]
the api for audio files is diffrent:
http://www.rtbf.be/api/media/audio?method=getAudioDetail&args[]=2182605

**Comment by jfstenuit** [comment]
I second @yan12125 comment : API has changed and rtbf.py needs rewriting.

The current API works as follow :
Origin URL : https://www.rtbf.be/auvio/emissions/detail_les-schtroumpfs?id=5828

In the body of the first page, you find an iframe :
`                    <iframe class="embed-responsive-item js-embed-iframe"
                            allowfullscreen="true"
                            scrolling="no"
                            mozallowfullscreen="true"
                            webkitallowfullscreen="true"
                            frameborder="0"
                            src="https://www.rtbf.be/auvio/embed/media?id=2246261&autoplay=0"
                            title="Lecteur video"></iframe>`

Downloading the iframe, you get a page with playlist encoded in javascript :

`<div id="js-embed-player" class="js-embed-player embed-player" data-media="...&quot;https:\/\/rtbf-vod.l3.freecaster.net\/vod\/rtbf\/geo\/be\/0\/0Cbhno8kbS\/master.m3u8&quot;...`

The playlist URL can be used directly by ffmpeg :

`ffmpeg -i "https://rtbf-vod.l3.freecaster.net/vod/rtbf/geo/be/0/0Cbhno8kbS/master.m3u8" -c copy test.mp4`
