### ISSUE TITLE
Youtube playlists not working

### ISSUE THREAD

**Issue by Thomas-Neill** [rg3/youtube-dl#11932]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.31*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --version
2017.01.31
$ youtube-dl -v https://www.youtube.com/playlist?list=PLpJl5XaLHtLX-pDk4kctGxtF4nq6BIyjg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/playlist?list=PLpJl5XaLHtLX-pDk4kctGxtF4nq6BIyjg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.31
[debug] Python version 2.7.12 - Linux-4.4.0-59-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.10-0ubuntu0.16.04.1, ffprobe 2.8.10-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube:playlist] PLpJl5XaLHtLX-pDk4kctGxtF4nq6BIyjg: Downloading webpage
[download] Downloading playlist: Undertale OST
[youtube:playlist] PLpJl5XaLHtLX-pDk4kctGxtF4nq6BIyjg: Downloading page #1
ERROR: Unable to download JSON metadata: <urlopen error [Errno 111] Connection refused> (caused by URLError(error(111, 'Connection refused'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1048, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)

...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.
  
I'm trying to download videos from a playlist instead of manually, but I'm getting a URL error when I try to do that. The strange thing is that normal videos work fine, but once youtube-dl sees a playlist, it breaks trying to get the JSON data.

EDIT:

This is becoming really frustrating, because I just tried to download a different playlist (the Cave Story OST) and it worked! However, I'm still having the same issue with the playlist I've tried to download in the log.

**Comment by ThomasChr** [comment]
Works for me. Maybe you are blocked in some kind? Could you try from another computer?

**Comment by Thomas-Neill** [comment]
Did you try it with that exact URL? It worked when I tried a different url ( [https://www.youtube.com/playlist?list=PL0A12ED38862DB0F5](url) )

**Comment by Thomas-Neill** [comment]
Did you try it with that exact URL? It worked when I tried a different url ( [https://www.youtube.com/playlist?list=PL0A12ED38862DB0F5](url) )

**Comment by yan12125** [comment]
Works here, too.
```
$ youtube-dl python2 -v --flat-playlist "https://www.youtube.com/playlist?list=PLpJl5XaLHtLX-pDk4kctGxtF4nq6BIyjg"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--flat-playlist', u'https://www.youtube.com/playlist?list=PLpJl5XaLHtLX-pDk4kctGxtF4nq6BIyjg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.31
[debug] Git HEAD: 000f20794
[debug] Python version 2.7.13 - Linux-4.9.6-1-ARCH-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLpJl5XaLHtLX-pDk4kctGxtF4nq6BIyjg: Downloading webpage
[download] Downloading playlist: Undertale OST
[youtube:playlist] PLpJl5XaLHtLX-pDk4kctGxtF4nq6BIyjg: Downloading page #1
[youtube:playlist] playlist Undertale OST: Downloading 101 videos
[download] Downloading video 1 of 101
[download] Downloading video 2 of 101
[download] Downloading video 3 of 101
[download] Downloading video 4 of 101
[download] Downloading video 5 of 101
[download] Downloading video 6 of 101
[download] Downloading video 7 of 101
[download] Downloading video 8 of 101
[download] Downloading video 9 of 101
[download] Downloading video 10 of 101
[download] Downloading video 11 of 101
[download] Downloading video 12 of 101
[download] Downloading video 13 of 101
[download] Downloading video 14 of 101
[download] Downloading video 15 of 101
[download] Downloading video 16 of 101
[download] Downloading video 17 of 101
[download] Downloading video 18 of 101
[download] Downloading video 19 of 101
[download] Downloading video 20 of 101
[download] Downloading video 21 of 101
[download] Downloading video 22 of 101
[download] Downloading video 23 of 101
[download] Downloading video 24 of 101
[download] Downloading video 25 of 101
[download] Downloading video 26 of 101
[download] Downloading video 27 of 101
[download] Downloading video 28 of 101
[download] Downloading video 29 of 101
[download] Downloading video 30 of 101
[download] Downloading video 31 of 101
[download] Downloading video 32 of 101
[download] Downloading video 33 of 101
[download] Downloading video 34 of 101
[download] Downloading video 35 of 101
[download] Downloading video 36 of 101
[download] Downloading video 37 of 101
[download] Downloading video 38 of 101
[download] Downloading video 39 of 101
[download] Downloading video 40 of 101
[download] Downloading video 41 of 101
[download] Downloading video 42 of 101
[download] Downloading video 43 of 101
[download] Downloading video 44 of 101
[download] Downloading video 45 of 101
[download] Downloading video 46 of 101
[download] Downloading video 47 of 101
[download] Downloading video 48 of 101
[download] Downloading video 49 of 101
[download] Downloading video 50 of 101
[download] Downloading video 51 of 101
[download] Downloading video 52 of 101
[download] Downloading video 53 of 101
[download] Downloading video 54 of 101
[download] Downloading video 55 of 101
[download] Downloading video 56 of 101
[download] Downloading video 57 of 101
[download] Downloading video 58 of 101
[download] Downloading video 59 of 101
[download] Downloading video 60 of 101
[download] Downloading video 61 of 101
[download] Downloading video 62 of 101
[download] Downloading video 63 of 101
[download] Downloading video 64 of 101
[download] Downloading video 65 of 101
[download] Downloading video 66 of 101
[download] Downloading video 67 of 101
[download] Downloading video 68 of 101
[download] Downloading video 69 of 101
[download] Downloading video 70 of 101
[download] Downloading video 71 of 101
[download] Downloading video 72 of 101
[download] Downloading video 73 of 101
[download] Downloading video 74 of 101
[download] Downloading video 75 of 101
[download] Downloading video 76 of 101
[download] Downloading video 77 of 101
[download] Downloading video 78 of 101
[download] Downloading video 79 of 101
[download] Downloading video 80 of 101
[download] Downloading video 81 of 101
[download] Downloading video 82 of 101
[download] Downloading video 83 of 101
[download] Downloading video 84 of 101
[download] Downloading video 85 of 101
[download] Downloading video 86 of 101
[download] Downloading video 87 of 101
[download] Downloading video 88 of 101
[download] Downloading video 89 of 101
[download] Downloading video 90 of 101
[download] Downloading video 91 of 101
[download] Downloading video 92 of 101
[download] Downloading video 93 of 101
[download] Downloading video 94 of 101
[download] Downloading video 95 of 101
[download] Downloading video 96 of 101
[download] Downloading video 97 of 101
[download] Downloading video 98 of 101
[download] Downloading video 99 of 101
[download] Downloading video 100 of 101
[download] Downloading video 101 of 101
[download] Finished downloading playlist: Undertale OST
```

**Comment by Thomas-Neill** [comment]
I´ll try the --flat-playlist flag.

**Comment by yan12125** [comment]
Well, --flat-playlist just tells youtube-dl don't recurse into individual videos of a playlist. In your case I guess --dump-pages can give useful information for why the extraction fails.

**Comment by Thomas-Neill** [comment]
--dump-pages just fills my console with undecipherable text, and [https://www.youtube.com/watch?v=XCO4eViY2cQ&list=PL5AFAB0251FF4912F](url) is also broken for me. I'll get on another computer and try it again.

**Comment by yan12125** [comment]
If --dump-pages brings too much noise, try --write-pages and upload *.dump files.

**Comment by Thomas-Neill** [comment]
[dump.txt](https://github.com/rg3/youtube-dl/files/747827/dump.txt)

**Comment by ThomasChr** [comment]
Making a Wireshark Dump could also add some insights - if it's worth the effort.
I'm pretty sure the problem is not from youtube-dl...

**Comment by Thomas-Neill** [comment]
I agree. Testing on my Mac, it works perfectly.
