### ISSUE TITLE
aenetworks DTV Unable to extract post url 

### ISSUE THREAD

**Issue by dlehman83** [rg3/youtube-dl#11935]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.01**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
```
youtubedl>youtube-dl.exe --netrc  --ap-mso DTV --write-pages --verbos http://www.history.com/shows/the-curse-of-oak-island/season-4/episode-12
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--netrc', '--ap-mso', 'DTV', '--write-pages', '--verbos', 'http://www.history.com/shows/the-curse-of-oak-island/season-4/episode-12']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.01
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-65107-ga507623, ffprobe N-65107-ga507623
[debug] Proxy map: {}
[aenetworks] the-curse-of-oak-island/season-4/episode-12: Downloading webpage
[aenetworks] Saving request to the-curse-of-oak-island_season-4_episode-12_http_-_www.history.com_shows_the-curse-of-oak-island_season-4_episode-12.dump
[aenetworks] 866208835843: Downloading JSON metadata
[aenetworks] Saving request to 866208835843_http_-_link.theplatform.com_s_xc6n8B_media_s0NL0Y1ml0vEformat=preview.dump
[aenetworks] 866208835843: Downloading Provider Redirect Page
[aenetworks] Saving request to 866208835843_https_-_sp.auth.adobe.com_adobe-services_authenticate_saml.dump
[aenetworks] 866208835843: Downloading Provider Login Page
[aenetworks] Saving request to 866208835843_https_-_idp.dtvce.com_dtv-idp-authn_authn_v2.dump
[aenetworks] 866208835843: Logging in
[aenetworks] Saving request to 866208835843_https_-_sp.auth.adobe.com_sp_saml_SAMLAssertionConsumer.dump
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4a0k6hcr\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4a0k6hcr\build\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4a0k6hcr\build\youtube_dl\extractor\aenetworks.py", line 117, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4a0k6hcr\build\youtube_dl\extractor\adobepass.py", line 1418, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4a0k6hcr\build\youtube_dl\extractor\adobepass.py", line 1322, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4a0k6hcr\build\youtube_dl\extractor\common.py", line 681, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4a0k6hcr\build\youtube_dl\extractor\common.py", line 672, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

---

### Description of your *issue*, suggested solution and other information

I cannot download videos from history.com that requires a TV provider.  I can download videos that do not require login perfectly.  

When attempting to download the video I get youtube_dl.utils.RegexNotFoundError: Unable to extract post url;

I have tried entering username and password on the command line, I have tried using cookies, and now I have setup .netrc file.  

Thank you,

**Comment by dstftw** [comment]
For any further investigations you have to provide TV provider credentials.

**Comment by dlehman83** [comment]
Since DTV was the first to be supported as far as I can tell. I thought @remitamine had an account.

**Comment by remitamine** [comment]
no i don't have an account, the account for DTV was provided for testing the same as the other TV Providers that i have added(Rogers and watchtveverywhere MSOs).

**Comment by StevenDTX** [comment]
This works just fine for me.

```
E:\>youtube-dl.exe --restrict-filenames --continue --no-check-certificate --ap-mso DTV --ap-username USERNAME --ap-password PASSWORD "http://www.history.com/shows/the-curse-of-oak-island/season-4/episode-12"
[aenetworks] the-curse-of-oak-island/season-4/episode-12: Downloading webpage
[aenetworks] 866208835843: Downloading JSON metadata
[aenetworks] 866208835843: Retrieving Authorization Token
[aenetworks] 866208835843: Retrieving Media Token
[aenetworks] 866208835843: Downloading SMIL data
[aenetworks] 866208835843: Checking video URL
[aenetworks] 866208835843: Checking video URL
[aenetworks] 866208835843: Checking video URL
[aenetworks] 866208835843: Checking video URL
[aenetworks] 866208835843: Checking video URL
[aenetworks] 866208835843: Checking video URL
[aenetworks] 866208835843: Checking video URL
[aenetworks] 866208835843: Checking video URL
[download] Destination: Hyde_Park_and_Go_Seek-866208835843.mp4
[download]   0.7% of 809.03MiB at  3.07MiB/s ETA 04:21
ERROR: Interrupted by user
```

**Comment by dlehman83** [comment]
I think there must be something with my ISP.  
I tried on a different computer / ISP and was able to download videos.  
I have tried on Windows and Linux both, here they do not work, at the other computers / ISP they do.  
I used both netrc and username / password.  

Any ideas on how to see what the issue may be.  

Thanks,

**Comment by dlehman83** [comment]
More evidence for an ISP issue.  I went to a neighbors with the  same ISP and it did not work, I have CenturyLink.

**Comment by dlehman83** [comment]
I tried using the geo proxy option and it did not work, so I then used the proxy option and was able to download videos on my home connection.  

Thanks,
