### ISSUE TITLE
Disney Junior (sort of works) - site request

### ISSUE THREAD

**Issue by jschwalbe** [rg3/youtube-dl#11936]
youtube_dl/extractor/disney.py already works for disney videos, but it doesn't work for the main video URL such as:
http://disneyjunior.disney.com/toy-hospital-the-mayor-s-speech-the-lake-monster <-- doesn't work

Loading this page and finding the embed URL from the source, as below, works perfectly.

http://disneyjunior.disney.com/embed/546a28123f7f2d1612e4005d  <-- works

Is there a way to get youtube-dl to search the site and grab the /embed/ url?

**Comment by yan12125** [comment]
> Video expired and no longer available

Any new examples?

**Comment by jschwalbe** [comment]
http://disneyjunior.disney.com/toy-hospital-made-to-be-a-nurse-rescue-at-the-ranch

**Comment by yan12125** [comment]
It says:
```
We're sorry, this video cannot be played in your region.
```
Which country is necessary? Tried an US proxy but no luck.

**Comment by jschwalbe** [comment]
Must be US then as that's where I'm at.

**Comment by yan12125** [comment]
Apparently they are blocking proxies.

**Comment by jschwalbe** [comment]
Here is the HTML content from that URL:  http://pastebin.com/H5AFxiCU - see line 219 for the url **http://disneyjunior.disney.com/embed/54282c6acce73f5a7f2a5b5c** 
This /embed/ URL works with youtube-dl:
```
[Disney] 54282c6acce73f5a7f2a5b5c: Downloading webpage
[Disney] 54282c6acce73f5a7f2a5b5c: Downloading m3u8 information
[download] Destination: Toy Hospital -  Made to Be A Nurse _ Rescue at The Ranch-54282c6acce73f5a7f2a5b5c.mp4
[download]   0.4% of 517.90MiB at  2.87MiB/s ETA 03:00^C
```
