### ISSUE TITLE
tab completion.

### ISSUE THREAD

**Issue by cardshuffler** [rg3/youtube-dl#11934]
using 2017.02.01 on ubuntu mate 16.10.

tab completion seems to no longer work.

i type 'you" then press tab and all is normal. i then proceed to type '--hls' then press tab but nothing happens. the expected outcome is 'youtube-dl --hls-prefer-native'.

**Comment by chim1aap** [comment]
There are three options: --hls-prefer-ffmpeg  --hls-prefer-native  --hls-use-mpegts.
Press tab a few times and bash should list all options.

**Comment by yan12125** [comment]
Thanks @chim1aap that's right

**Comment by cardshuffler** [comment]
nothing happens.

**Comment by yan12125** [comment]
Did you set tab completion correctly?

**Comment by cardshuffler** [comment]
yes. as stated if i type 'you' then press tab it works fine. it's when i type '--*' that the issue arises. --version doesn't work either.

**Comment by yan12125** [comment]
On Arch Linux I have to run ```source /usr/share/bash-completion/completions/youtube-dl``` before tab completion works. That's an Arch Linux bug. Maybe Ubuntu has similar bugs.

**Comment by cardshuffler** [comment]
i've tried a different keyboard just in case and the problem is still present.

i'll try the arch workaround when i can.
