### ISSUE TITLE
general question:  vers. 2017.02.01 vs. 2016.11.22

### ISSUE THREAD

**Issue by durian808** [rg3/youtube-dl#11940]
I have been using 2016.11.22 w/ Python 2.6 successfully for youtube.com downloads for a long time on a CentOS 6 box.

Now I have installed 2017.02.01 on a CentOS 7 box  w/ Python 2.7, and the behavior is very different.

With the older version, the download would start almost immediately and if I ran it in the background, I could see the file growing in the directory.

With the new version it is very sluggish, starting out with the message "Downloading webpage".  The download itself doesn't start for a long time.

Here's the start of the execution... it sits for a long time on "Downloading webpage"...

```
% ./youtube-dl --newline -v https://www.youtube.com/watch?v=fB6yRxK_fts
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--newline', u'-v', u'https://www.youtube.com/watch?v=fB6yRxK_fts']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.01
[debug] Python version 2.7.5 - Linux-3.10.0-514.6.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] fB6yRxK_fts: Downloading webpage
```

Then after a while "Downloading video info webpage" appears.

Then "Extracting video information" and "Downloading MPD manifest"... and then it sits there.

Finally, I see:
`[debug] Invoking downloader on u'https://r3---sn-a8au-2ime.googlevideo.com/videoplayback?dur=3154.036&mn=sn-a8au-2ime&mm=31&lmt=1471416464701937&ms=au&mv=m&mt=1486029623&ipbits=0&key=yt6&ip=206.225.82.240&upn=5Xy51cltqpI&ei=qAOTWPTiF4btogOYk7aABQ&id=o-AMyOWulMcf4aSDSKUOi1FSL3HX0TsOkRPnIcy2Kk-p-g&ratebypass=yes&initcwndbps=6465000&requiressl=yes&signature=8B2E70E64BC1ED891DB9B236F762BAFE3336B7E3.6224FB2D67584990D2750DF3FC85D3E3ECDBC28A&pl=21&source=youtube&mime=video%2Fmp4&expire=1486051336&itag=22&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire'
`
And it sits here for a long time.  Then I see "[download] Destination: <name of the video>.mp4", rapidly followed by the download progress lines...

```
[download]   0.0% of 591.53MiB at Unknown speed ETA Unknown ETA
[download]   0.0% of 591.53MiB at Unknown speed ETA Unknown ETA
[download]   0.0% of 591.53MiB at Unknown speed ETA Unknown ETA
[download]   0.0% of 591.53MiB at Unknown speed ETA Unknown ETA
[download]   0.0% of 591.53MiB at Unknown speed ETA Unknown ETA
[download]   0.0% of 591.53MiB at 43.48MiB/s ETA 00:13
[download]   0.0% of 591.53MiB at  6.76MiB/s ETA 01:27
[download]   0.0% of 591.53MiB at  6.18MiB/s ETA 01:35
[download]   0.1% of 591.53MiB at  2.56MiB/s ETA 03:50
[download]   0.2% of 591.53MiB at  4.97MiB/s ETA 01:58
[download]   0.3% of 591.53MiB at  5.73MiB/s ETA 01:42
[download]   0.7% of 591.53MiB at  8.63MiB/s ETA 01:08
[download]   1.4% of 591.53MiB at 11.48MiB/s ETA 00:50
[download]   2.0% of 591.53MiB at 16.17MiB/s ETA 00:35
[download]   2.7% of 591.53MiB at 16.71MiB/s ETA 00:34
[download]   3.4% of 591.53MiB at 17.50MiB/s ETA 00:32
[download]   4.1% of 591.53MiB at 18.33MiB/s ETA 00:30
[download]   4.7% of 591.53MiB at 17.87MiB/s ETA 00:31
[download]   5.4% of 591.53MiB at 17.25MiB/s ETA 00:32
[download]   6.1% of 591.53MiB at 18.93MiB/s ETA 00:29
[download]   6.8% of 591.53MiB at 18.81MiB/s ETA 00:29
[download]   7.4% of 591.53MiB at 19.86MiB/s ETA 00:27
[download]   8.1% of 591.53MiB at 19.42MiB/s ETA 00:27
[download]   8.8% of 591.53MiB at 19.65MiB/s ETA 00:27
[download]   9.5% of 591.53MiB at 19.89MiB/s ETA 00:26
[download]  10.1% of 591.53MiB at 19.57MiB/s ETA 00:27
[download]  10.8% of 591.53MiB at 20.30MiB/s ETA 00:25
• • •
[download]  98.1% of 591.53MiB at 22.43MiB/s ETA 00:00
[download]  98.7% of 591.53MiB at 22.39MiB/s ETA 00:00
[download]  99.4% of 591.53MiB at 22.43MiB/s ETA 00:00
[download] 100.0% of 591.53MiB at 22.46MiB/s ETA 00:00
[download] 100% of 591.53MiB in 00:26
```

Is this the normal behavior of vers. 2017.02.01?  Am I missing something?  Can this be speeded up?

much thanks

**Comment by yan12125** [comment]
> Is this the normal behavior of vers. 2017.02.01?

No. The new version should work just like earlier ones. Could you run youtube-dl under strace and see why it stops responding?

**Comment by durian808** [comment]
Here's the first part of the trace, probably around where "Downloading video info webpage" is shown...
[trace.txt](https://github.com/rg3/youtube-dl/files/747525/trace.txt)

**Comment by yan12125** [comment]
Seems IPv6 problems. Try --force-ipv4

**Comment by durian808** [comment]
Bingo!  592M in 9 seconds!

thanks for your help :-)
