### ISSUE TITLE
I can't get video from youtube due to SSL Error

### ISSUE THREAD

**Issue by KiYugadgeter** [rg3/youtube-dl#11943]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

The following is verbose output.
```
$ youtube-dl -v https://www.youtube.com/watch?v=9WwuaSFiE70
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=9WwuaSFiE70']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.01
[debug] Python version 3.6.0 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg present, ffprobe present
[debug] Proxy map: {}
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/utils.py", line 1048, in https_open
    req, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)


<end of log>
```
I tried `brew reinstall openssl`, However the error keep causing yet.
But enable no-check-certificate option, it works.

**Comment by ThomasChrTest** [comment]
Works for me. Is your date correct on your server/computer?

**Comment by ThomasChr** [comment]
Works for me. Is the date on your server/computer correct?

**Comment by Cysioland** [comment]
Also works for me, same version, Antergos Linux.

**Comment by yan12125** [comment]
Python 3.6 on macOS requires additional administrative configurations for working SSL certificate verification. See http://bugs.python.org/issue29065#msg283984

**Comment by ThomasChr** [comment]
@yan12125 Blazing fast solution to this issue. Wow!

**Comment by Celthi** [comment]
@yan12125 I got the same problem, but in win 10. Is there a way to solve the problem for win 10.

**Comment by ThomasChrTest** [comment]
Ich bin bis 09.03.2017 abwesend.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten. /
I'll answer your message after my return.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[rg3/youtube-dl] I can't get video from youtube due to SSL Error (#11943)"
gesendet am 04.03.2017 07:39:27.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
