### ISSUE TITLE
Udemy Videos Sound gets mute if you keep jumping on the time line.

### ISSUE THREAD

**Issue by almustaness** [rg3/youtube-dl#11942]
I downloaded many courses from Udemy. I noticed something strange:
**If I keep jumping from place to another in a video timeline, the sound gets mute !** 
By the way, I use version 19-6-20116

**Comment by ThomasChr** [comment]
To me it sounds like a problem in the file. Possibly something for which youtube-dl is not responsible.
Could you provide me with a link or at least upload the file somewhere so that I can verify the problem?

**Comment by dstftw** [comment]
Not reproducible with mpv and vlc. Thus your player is most likely a culprit.

**Comment by almustaness** [comment]
@ThomasChr 
this is one video i downloaded. By the way I tried it with **Windows Media Palyer and Media Player Classic**
[https://drive.google.com/file/d/0B5GOTiBoOMtVVFNSQUlHREZQRUU/view?usp=sharing](url)

**Comment by yan12125** [comment]
This file works just fine in VLC and mpv. I jump to various time points at least 10 times and the audio plays fine. You may want to report a bug to Media Player Classic.
