### ISSUE TITLE
This program is really good

### ISSUE THREAD

**Issue by stefan-reich** [rg3/youtube-dl#11952]
This is like an anti-issue - I like to praise the program. So stable and versatile. I think it actually works (that's a praise). I'm using the tool as a part of a Java-based automatic video processing system.

Oh wait, there is an issue. I'm having a problem calling youtube-dl.exe on Windows. It doesn't work in a .bat (youtube-dl says it got no parameters), but on the prompt, the same line works.

I'm not supporting Windows though =)

On my Linux, yt-dl installs and runs great.

**Comment by dstftw** [comment]
youtube-dl works fine from Windows batch. Most likely your batch [code calling youtube-dl is incorrect](https://github.com/rg3/youtube-dl#output-template-and-windows-batch-files).
