### ISSUE TITLE
PHP - youtube-dl: command not found

### ISSUE THREAD

**Issue by clarityworld** [rg3/youtube-dl#11967]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.01**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ X] Other

---

Hello!
I'm trying to run youtube-dl via PHP. It's all working when im logged in on Terminal.
When I try to run via exec, I get this Eerror:"sh: youtube-dl: command not found"
My Php
`<?php
$cmd = 'youtube-dl https://www.youtube.com/watch?v=jRpp--g3oNY';
exec($cmd." 2>&1", $output);
echo "<pre>";
var_dump($output);
echo "</pre>";
?>`

> array(1) {
  [0]=>
  string(33) "sh: youtube-dl: command not found"
}

**Comment by yan12125** [comment]
Most likely $PATH is not correctly set. You may want to use absolute paths.

**Comment by clarityworld** [comment]
Dare to explain a little more. I don't know. $PATH is something server side ,or in the php file?

**Comment by clarityworld** [comment]
Added:
putenv('PATH=/usr/local/bin');
Now 
string(47) "/usr/bin/env: python: No such file or directory"

**Comment by yan12125** [comment]
putenv is the correct way, but /usr/local/bin is not enough. /usr/local/bin:/usr/bin should work I guess.

**Comment by clarityworld** [comment]
Thank you !

**Comment by QianMuXiao** [comment]
youtube-dl install successfully
but when I type youtube-dl -H
it just shows
zsh: command not found: youtube-dl
