### ISSUE TITLE
Can't get a valid video file URL from certain youtube videos

### ISSUE THREAD

**Issue by jcohenho** [rg3/youtube-dl#11962]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

```
youtube-dl -g -v https://www.youtube.com/watch?v=WKziXvr6ug8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-g', u'-v', u'https://www.youtube.com/watch?v=WKziXvr6ug8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.01
[debug] Python version 2.7.13 - Darwin-15.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.1, ffprobe 3.2.1
[debug] Proxy map: {}
https://r3---sn-a5mekned.googlevideo.com/videoplayback/id/58ace25efafaba0f/itag/136/source/yt_otf/requiressl/yes/nh/IgpwZjAxLmxheDI4Kg4yMDkuODUuMTczLjE3Nw/initcwndbps/1012500/mn/sn-a5mekned/mm/31/ms/au/mv/m/pl/15/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1484354480091958/signature/2C281BC03DF3F11A78F149517236627D48A0F219.3229F608007E133759E50499CCC8A17C1DC23137/key/dg_yt0/upn/dbEpnJXegPo/mt/1486176561/ip/76.94.213.86/ipbits/0/expire/1486198205/sparams/ip,ipbits,expire,id,itag,source,requiressl,nh,initcwndbps,mn,mm,ms,mv,pl,ratebypass,mime,otfp,otf,lmt/
https://r3---sn-a5mekned.googlevideo.com/videoplayback/id/58ace25efafaba0f/itag/140/source/youtube/requiressl/yes/nh/IgpwZjAxLmxheDI4Kg4yMDkuODUuMTczLjE3Nw/initcwndbps/1012500/mn/sn-a5mekned/mm/31/ms/au/mv/m/pl/15/ratebypass/yes/mime/audio%2Fmp4/otfp/1/gir/yes/clen/147410/lmt/1484354115012441/dur/9.241/signature/03940939F7C1362E8BB50012972935B880C67DDC.670BA82FD76DFBE5DE46D50EA66650EF8D01A236/key/dg_yt0/upn/dbEpnJXegPo/mt/1486176561/ip/76.94.213.86/ipbits/0/expire/1486198205/sparams/ip,ipbits,expire,id,itag,source,requiressl,nh,initcwndbps,mn,mm,ms,mv,pl,ratebypass,mime,otfp,gir,clen,lmt,dur/
```

I am struggling to retrieve the correct video URL from this youtube URL:
`https://www.youtube.com/watch?v=WKziXvr6ug8`

I can download the video just fine with `youtube-dl https://www.youtube.com/watch?v=WKziXvr6ug8`, but what I really want to do is to just retrieve a valid video URL with

`youtube-dl -g --skip-download https://www.youtube.com/watch?v=WKziXvr6ug8` but the URLs that are returned are invalid. Are there any workarounds that can help me here?

**Comment by yan12125** [comment]
This video provides DASH segments. That is, a stream is composed of multiple files. To get URLs of all segments, run this command:
```
youtube-dl -j "https://www.youtube.com/watch?v=WKziXvr6ug8"
```
Segment URLs for bestvideo and bestaudio are in ```.requested_formats[0].fragments``` and ```.requested_formats[1].fragments```, respectively.
