### ISSUE TITLE
Error code (0xc000007b)

### ISSUE THREAD

**Issue by LiveSide** [rg3/youtube-dl#11961]
Hello at all,

im using a virtual Windows Web Server 2008 R2 with SP1
If im starting the youtube-dl.exe i got always this error.
http://image.prntscr.com/image/90a8f5f13ac64416b7c2c8414f3f0542.png

I want use the application with "sinusbot" and they just say: youtube-dl is missing

can anyone help me?

Sorry for my bad english im from germany maybe can anyone answer in german

**Comment by LiveSide** [comment]
okay 
after around 50hours start installing "sinusbot"
after around 45hours after start istall youtube-dl.exe
after more than 10 Rolebacks of my virtual server
after alot of cups with coffee
after crying, smiling and yawning
after thinkin
after 2 hours after post.
ONE Moment.... IT WORKS

i dont know what file let it works but
http://image.prntscr.com/image/b7b5c9929fb647b3b5decfb737d4eac7.png
i installed all windows visual c++ and i heard the sinusbot talked to me

i hope some help this post

**Comment by yan12125** [comment]
Glad to see you've found a solution. FYI, Visual C++ 2010 is the key: https://github.com/rg3/youtube-dl#the-exe-throws-an-error-due-to-missing-msvcr100dll

**Comment by antonio8909** [comment]
After doing this in a Windows 10 Insider Preview setup, it doesnt work

**Comment by yan12125** [comment]
Maybe Windows 10 Insider Preview has removed Visual C++ 2010 runtime libraries? Did you try to install it again?

**Comment by antonio8909** [comment]
Yes @yan12125 and it doesn't work

**Comment by yan12125** [comment]
Sorry I'm not familiar with Windows and I don't have a Windows 10 machine for testing. I've heard Dependency Walker can help diagnosing such problems. Maybe it's worth a try.

**Comment by antonio8909** [comment]
@yan12125 That's from old builds. Not applicable to new ones.

**Comment by yan12125** [comment]
Hmm I didn't notice that. Let's wait for someone that uses Windows 10.

**Comment by antonio8909** [comment]
It looks like it's a problem of the x64 version of Windows 10. I installed the stable one and the same error appears :/ I'll ask in Windows 10 forums about this

**Comment by dstftw** [comment]
It has nothing to do with x64 or Windows version.

**Comment by antonio8909** [comment]
@dstftw x86: works x64: No
c++ 2010 installed. Why is it failling then?

**Comment by dstftw** [comment]
Prove it's installed.

**Comment by antonio8909** [comment]
After chat with Microsoft I fixed it

STEPS

Download the missing dll https://es.dll-files.com/msvcr100.dll.html (32bit)
Paste it in System32 and SysWOW64
Close explorer.exe and open it again.

The program will work as expected.

**Comment by akuan10** [comment]
@antonio8909
holy shit you solved my problem, thank you so much

**Comment by rautamiekka** [comment]
> @antonio8909
> holy shit you solved my problem, thank you so much

You should install both the x86 (32-bit) and x64 (64-bit) of the Visual C++ 2010 before getting an individual DLL.
