### ISSUE TITLE
remux to webm or mkv

### ISSUE THREAD

**Issue by chpio** [rg3/youtube-dl#11980]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Is it possible to convert the output file to webm if possible (vp9/vp8+opus/vorbis) or else to mkv? Not working "alternatives":
* `-f "webm/mkv"` is just a filter for the input streams and
* `--merge-output-format` allows only one option.

**Comment by dstftw** [comment]
This is the default behavior, it outputs original container if possible or uses mkv otherwise.

**Comment by chpio** [comment]
> it outputs original container
Yes, that's why im asking for this feature.

**Comment by joetex72** [comment]
You can try setting the output container to mkv or manually copying to mkv with ffmpeg.

**Comment by chpio** [comment]
> manually copying to mkv with ffmpeg.

that's what im doing right now (using mkvtoolnix gui to convert it to mkv). that's kind of a workaround, but it's working. i just wondered if there is a more convenient way to do that.

**Comment by yan12125** [comment]
@chpio could you paste an example video for what's your expectation and the actual results?
