### ISSUE TITLE
Postprocessing fodler

### ISSUE THREAD

**Issue by Stonedestroyer** [rg3/youtube-dl#11985]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.04.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.04.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Is it possible to have a postprocessing folder where everything gets merged and then transferred, I am using rclone mount to mount a cloud drive and doing all the merging there messes up the drive.

**Comment by yan12125** [comment]
You can download things to a temporary folder and move the final result via ```--exec```

**Comment by Stonedestroyer** [comment]
I've tried exec but I can not get it to work, it seems to parse my stuff differently and also I don't see a way to get it to retain the same folder layout and not just move it to a static folder?

**Comment by yan12125** [comment]
I see. Apparently using a temporary folder for intermediate files is a simpler option. See #10993
