### ISSUE TITLE
5.1 sound

### ISSUE THREAD

**Issue by Dimsok** [rg3/youtube-dl#12004]
I still don't know support it youtube or not, I've read some saying they can play 5.1 sound in chrome, but youtbe-dl downloads all in stereo. If there are no any 5.1 enabled video in youtube, why there are many tests like this:

https://www.youtube.com/watch?v=PqVCPE8_ntE&hd=1

**Comment by yan12125** [comment]
How to enable 5.1 audio in Chrome? For this video I got itag 251 in Chromium, which is stereo.

**Comment by Dimsok** [comment]
http://superuser.com/questions/820845/how-to-get-5-1-audio-in-google-chrome/1055177#1055177

**Comment by yan12125** [comment]
In chrome://flags/, there's no option #try-supported-channel-layouts. I've also tried flags from https://www.youtube.com/watch?v=dcUZXRYroZM. Maybe youtube won't use 5.1 audios if I don't have a 5.1 output?

**Comment by Dimsok** [comment]
Did you try add params to the Chrome shortcut or cmd? And maybe it depends on Adobe flash player, But i've read that youtube's 5.1 is not native, something with html5.

**Comment by yan12125** [comment]
Yes I've tried --disable-audio-output-resampler, --try-supported-channel-layouts and --force-wave-audio.

> maybe it depends on Adobe flash player

I can't find a way to force Flash on YouTube. And it does not make sense - Google is urging on killing Flash.

Can you right-click on the video and choose "Stats for Nerds"? What's the value of item "DASH"?

**Comment by Dimsok** [comment]
160/250
I have an old Chrome and Win XP, try to add params to Chrome, but maybe it's too old to support it, Can't get make sounds from center, rear speakers and woofer.

**Comment by yan12125** [comment]
Audio 250 is also stereo.

> Can't get make sounds from center, rear speakers and woofer.

Actually there are also rumors that YouTube does not support 5.1 audios at all. See https://productforums.google.com/d/msg/youtube/jMoMzEyFJak/OrJWAeMCAQAJ

It's impossible to have youtube-dl support more than browsers, so I'm closing this. If you find a way to play 5.1 audios from YouTube, feel free to leave comments and I'll reopen this.

**Comment by nareshbtech** [comment]
I have used Youtube apps on TV hooked to a receiver and I am able get 5.1 audio.

even youtube allows to 5.1 +stereo
Advanced encoding settings

Audio codec: AAC-LC
•Channels: Stereo or Stereo + 5.1
•Sample rate 96 khz or 48 kHz

and why youtube-dl -F dose not show this available

**Comment by yan12125** [comment]
Most likely youtube-dl mimics normal browsers, so YouTube returns stereo audios only. It may help if you specify the User-Agent string of that App via ```--user-agent```.

**Comment by blshkv** [comment]
I have found few samples which youtube-dl can download with 5.1 quality:
```
https://www.youtube.com/watch?v=FgulvA9sc_s
https://www.youtube.com/watch?v=DRjbuXjNwrk
https://www.youtube.com/watch?v=Ec1pwCHrm-8
https://www.youtube.com/watch?v=thedigitaltheater
```

Hopefully, this will help you to investigate what's wrong with other videos. I can see two possibilities: they either were uploaded before youtube started to support 5.1 or it is an youtube-dl issue.

P.S. Once downloaded, you can check media info with the following:
```
ffprobe <file>
```

**Comment by dstftw** [comment]
Once again: Youtube does not support 5.1. None of these videos are actually 5.1.
