### ISSUE TITLE
Videos from Pornhub is not possible to download

### ISSUE THREAD

**Issue by Modryz** [rg3/youtube-dl#12007]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
# youtube-dl -v http://www.pornhub.com/view_video.php?viewkey=ph574f0d                                                                                        6f2d8fa
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.pornhub.com/view_video.php?viewk                                                                                        ey=ph574f0d6f2d8fa']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968,                                                                                         pref ANSI_X3.4-1968
[debug] youtube-dl version 2017.02.07
[debug] Python version 2.7.6 - Linux-3.16.6-042stab120.11-x86_64-with-Ubuntu-14.                                                                                        04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[PornHub] ph574f0d6f2d8fa: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug                                                                                         . Make sure you are using the latest version; see  https://yt-dl.org/update  on                                                                                         how to update. Be sure to call youtube-dl with the --verbose flag and include i                                                                                        ts complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 69                                                                                        6, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py",                                                                                         line 369, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/pornhub.py",                                                                                         line 193, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py",                                                                                         line 936, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-d                                                                                        l.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/u                                                                                        pdate  on how to update. Be sure to call youtube-dl with the --verbose flag and                                                                                         include its complete output.

```

---

### Description of your *issue*, suggested solution and other information
Videos from Pornhub.com is not possible to download. There is an error: No video formats found

**Comment by wizardbitcoin** [comment]
+1

**Comment by arielesp** [comment]
+1

**Comment by ThomasChr** [comment]
The right Test-URL is: http://www.pornhub.com/view_video.php?viewkey=ph574f0d6f2d8fa
(was cut of in the issue)

It seems that pornhub changed quite a lot in there URLs - now there is some parsing of Javascript-Code needed:
`var player_quality_240p=player_quality_240p06 + player_quality_240p6`

**Comment by ThomasChr** [comment]
I've opend PR #12015 - I'm not quite there yet. If anyone would like to help: Come and join the PR :-)

**Comment by ThomasChr** [comment]
PR #12018 fixes the extractor.

**Comment by ThomasChr** [comment]
Waiting for review of PullRequest...

**Comment by arielesp** [comment]
fix not working here ... using exec ... no download too

**Comment by ThomasChr** [comment]
hmmm, thats odd. i had no problems at all.
do you habe a test url for me?

**Comment by arielesp** [comment]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.pornhub.com/view_video.php?viewkey=ph587b95772718f', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.07
[debug] Python version 2.7.5 - Linux-3.10.0-514.6.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 3.2.2-static, ffprobe 3.2.2-static
[debug] Proxy map: {}
[PornHub] ph587b95772718f: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 696, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 193, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 936, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ThomasChr** [comment]
No problem here. Video downloads just fine.

> python -m youtube_dl -v http://www.pornhub.com/view_video.php?viewkey=ph587b95772718f
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.pornhub.com/view_video.php?viewkey=ph587b95772718f']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.10
[debug] Git HEAD: 5abcca9
[debug] Python version 2.7.12 - Linux-4.4.0-59-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.10-0ubuntu0.16.04.1, ffprobe 2.8.10-0ubuntu0.16.04.1
[debug] Proxy map: {}
[PornHub] ph587b95772718f: Downloading webpage
[debug] Invoking downloader on u'http://cv.pornhub.phncdn.com/videos/201701/15/102431772/720P_1500K_102431772.mp4?a5dcae8e1adc0bdaed975f0d67fb5e0527c20903c5bb57a6cad7e6cb50bc41fbb1152c24e90ee001fe80e3affff13ed17724d884a04f253e59a8be6a2147d880ba16c908a20528d51ef149d3dc8ab5759b15b2af5bc7d5ccf94e1b6981e7f6aee772e7e3f9b003cab8888031f334816b8ef8f60b324358be4f09a10b'
[download] Destination: Tiny Teen Babysitter Rachel James Caught In The Act-ph587b95772718f.mp4
[download]   2.9% of 69.99MiB at  1.74MiB/s ETA 00:39^C

The fix is integrated into '2017.02.10' - so make sure you're using this version.
I think you maybe made a error when applying my Fix.

**Comment by ThomasChr** [comment]
Hi @dstftw - would you mind telling me what is not working with my proposed fix?

**Comment by dstftw** [comment]
They've changed the obfuscation again.

**Comment by ThomasChr** [comment]
Outch! 
But it does seem solveable. We just need to cut out all the comments (/* */) and then replace the other variables as before. We just need to take attention to the detail that the variables do not start with 'player_quality' anymore, only the url's do.
Should I give it a shot or would you like to fix it?
I'm pretty sure you would be faster (and better) but I think I can solve this if you want.

**Comment by dstftw** [comment]
I don't see much point since they'll change it again. They are trying to block tools.
`JSInterpreter` should be used instead and enhanced if necessary.

**Comment by Markaos** [comment]
Still doesn't work in 2017.2.10, I get this error from urllib when I try to download video:
`ValueError: unknown url type: /*c38bcfb0cf3db8164c7a76153627b*/d22a0186a17d816/*bc3e590ceb075691*/aed0f52637bd1235e09f45449b6d2/*d22a0186a17d816*/fb54d72dd77ddbd5620eda8e7031/*fc2*/cc30fdf5e9899218aa8/*d48b23a9cbf14876c*/c38bcfb0cf3db8164c7a76153627b/*a499d13*/a499d13/*d48b23a9cbf14876c*/cfc42903c4e9ab85e/*d54898b1a343127eedff7092db1734c8*/f6d133051cf2d648021/*a499d13*/ee003d810/*c2b9883a460a74265f93*/d54898b1a343127eedff7092db1734c8/*d8131198c1dbc498c367d*/c2b9883a460a74265f93/*d22a0186a17d816*/fcea8/*d48b23a9cbf14876c*/d48b23a9cbf14876c/*bc3e590ceb075691*/f79c1792b9eb9129/*c2b9883a460a74265f93*/bc3e590ceb075691/*dd6a9e4083d0b95104394a*/fc2/*c2b9883a460a74265f93*/dd6a9e4083d0b95104394a/*fb54d72dd77ddbd5620eda8e7031*/d8131198c1dbc498c367d`

**Comment by yan12125** [comment]
Closing in favor of #12129
