### ISSUE TITLE
ytuser doesn't download with template

### ISSUE THREAD

**Issue by Dees7** [rg3/youtube-dl#12003]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\work\2017.02.07-12.55.26>youtube-dl -v ytuser:Zefar91 --write-description -f best[ext=mp4]/best -w -i -o "(upload_date)s-(id)s.(ext)s"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'ytuser:Zefar91', '--write-description', '-f', 'best[ext=mp4]/best', '-w', '-i', '-o', '(upload_date)s-(id)s.(ext)s']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.02.07
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:user] Zefar91: Downloading channel page
[youtube:playlist] UUFI31dsn8yxaarw6LZpSHWw: Downloading webpage
[download] Downloading playlist: Uploads from Электротехника и электроника для программистов
[youtube:playlist] UUFI31dsn8yxaarw6LZpSHWw: Downloading page #1
[youtube:playlist] UUFI31dsn8yxaarw6LZpSHWw: Downloading page #2
[youtube:playlist] UUFI31dsn8yxaarw6LZpSHWw: Downloading page #3
[youtube:playlist] playlist Uploads from Электротехника и электроника для программистов: Downloading 338 videos
[download] Downloading video 1 of 338
[youtube] CjU8HiWmhLs: Downloading webpage
[youtube] CjU8HiWmhLs: Downloading video info webpage
[youtube] CjU8HiWmhLs: Extracting video information
[youtube] CjU8HiWmhLs: Downloading MPD manifest
[info] Writing video description to: (upload_date)s-(id)s.(ext)s.description
[debug] Invoking downloader on 'https://r4---sn-ug5onuxaxjvh-n8vs.googlevideo.com/videoplayback?ipbits=0&initcwndbps=2277500&signature=5D005D32B97C12386B5DFD41D02A4B2E
2A02658E.C2EEBD87376503DC824D69BD2DF4705363789714&ratebypass=yes&expire=1486477286&mime=video%2Fmp4&pl=21&itag=22&dur=558.045&source=youtube&requiressl=yes&sparams=dur
%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&lmt=1486453382522223&ei=hoOZWIPFL
ZCiNOLfnbgJ&mn=sn-ug5onuxaxjvh-n8vs&mm=31&id=o-AE5IWZ4Oh-Yw3istTW_5xlh-bIFjKH3aNRlkqR5eZPUy&upn=ocNpt3TqiwY&key=yt6&ip=62.33.207.199&mv=m&mt=1486455622&ms=au'
[download] Destination: (upload_date)s-(id)s.(ext)s
[download]  11.0% of 78.82MiB at  1.09MiB/s ETA 01:04
ERROR: Interrupted by user
...
<end of log>
```

--

### Description of your *issue*, suggested solution and other information

It doesn't work correctly with option "-o" if I use ytuser option.
FE: youtube-dl ytuser:Zefar91 --write-description -f best[ext=mp4]/best -w -i  -o "%(uploader)s-%(upload_date)s-%(title)s-%(id)s.%(ext)s"
It always saves to "upload_date)s-(id)s.(ext)" 

If i use -l option inteard of ytuser then it works well
FE: youtube-dl -a list --write-description -f best[ext=mp4]/best -w -i  -o "%(uploader)s-%(upload_date)s-%(title)s-%(id)s.%(ext)s"

**Comment by dstftw** [comment]
You've missed `%` in output template.
>-v ytuser:Zefar91 --write-description -f best[ext=mp4]/best -w -i -o "(upload_date)s-(id)s.(ext)s"

>"(upload_date)s-(id)s.(ext)s"

**Comment by Dees7** [comment]
Oh. there are double-% needed in windows cmd files.
Big thanks.
