### ISSUE TITLE
Site support request: www.programme-tv.net

### ISSUE THREAD

**Issue by loby66** [rg3/youtube-dl#12005]
[x ] Site support request

`
>youtube-dl.exe -U
youtube-dl is up-to-date (2017.02.07)

>youtube-dl.exe -v http://www.programme-tv.net/videos/extraits/81095-guillaume-canet-evoque-les-rumeurs-d-infidelite-de-marion-cotillard-avec-brad-pitt-dans-vivement-dimanche/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.programme-tv.net/videos/extraits/81095-guillaume-canet-evoque-les-rumeurs-d-infidelite-de-marion-cotillard-avec-brad-pitt-dans-vivement-dimanche/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.07
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 2.8.4, ffprobe N-81045-g450cf40, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 81095-guillaume-canet-evoque-les-rumeurs-d-infidelite-de-marion-cotillard-avec-brad-pitt-dans-vivement-dimanche: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 81095-guillaume-canet-evoque-les-rumeurs-d-infidelite-de-marion-cotillard-avec-brad-pitt-dans-vivement-dimanche: Downloading webpage
[generic] 81095-guillaume-canet-evoque-les-rumeurs-d-infidelite-de-marion-cotillard-avec-brad-pitt-dans-vivement-dimanche: Extracting information
ERROR: Unsupported URL: http://www.programme-tv.net/videos/extraits/81095-guillaume-canet-evoque-les-rumeurs-d-infidelite-de-marion-cotillard-avec-brad-pitt-dans-vivement-dimanche/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\build\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\build\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\build\youtube_dl\extractor\generic.py", line 2589, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.programme-tv.net/videos/extraits/81095-guillaume-canet-evoque-les-rumeurs-d-infidelite-de-marion-cotillard-avec-brad-pitt-dans-vivement-dimanche/`

**Comment by yan12125** [comment]
Custom brightcove:new embed. You can download this video with:
```
youtube-dl http://players.brightcove.net/800000640001/Hyx5mvd4_default/index.html?videoId=5311302538001
```
