### ISSUE TITLE
[NBC] Add provider support

### ISSUE THREAD

**Issue by gkoelln** [rg3/youtube-dl#12006]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other
---
### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\WINDOWS\system32>youtube-dl http://www.nbc.com/timeless/video/the-worlds-columbian-exposition/3452716 -s -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.nbc.com/timeless/video/the-worlds-columbian-exposition/3452716', '-s', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.07
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.3
[debug] Proxy map: {}
[NBC] 3452716: Downloading webpage
[ThePlatform] 3452716: Downloading webpage
[ThePlatform] 3452716: Downloading SMIL data
ERROR: This content requires a valid, unexpired auth token.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\build\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\build\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\build\youtube_dl\extractor\theplatform.py", line 274, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\build\youtube_dl\extractor\theplatform.py", line 42, in _extract_theplatform_smil
youtube_dl.utils.ExtractorError: This content requires a valid, unexpired auth token.
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Some NBC videos require Adobe authorization, which is currently not supported.

**Comment by yan12125** [comment]
FYI: https://github.com/rg3/youtube-dl/blob/master/README.md#adobe-pass-options

**Comment by gkoelln** [comment]
Yes, I'm aware of the option, thank you, but when I add my locally updated MSO:

```
[NBC] 3142497: Downloading webpage
[ThePlatform] 3142497: Downloading webpage
[ThePlatform] 3142497: Downloading SMIL data
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'http://www.nbc.com/timeless/video/party-at-castle-varlar/3142497', '-s', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2017.02.01
[debug] Python version 3.6.0 - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.3
[debug] Proxy map: {}
ERROR: This content requires a valid, unexpired auth token.
Traceback (most recent call last):
  File "C:\python36\lib\youtube-dl\youtube_dl\YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "C:\python36\lib\youtube-dl\youtube_dl\extractor\common.py", line 369, in extract
    return self._real_extract(url)
  File "C:\python36\lib\youtube-dl\youtube_dl\extractor\theplatform.py", line 274, in _real_extract
    formats, subtitles = self._extract_theplatform_smil(smil_url, video_id)
  File "C:\python36\lib\youtube-dl\youtube_dl\extractor\theplatform.py", line 42, in _extract_theplatform_smil
    raise ExtractorError(error_element.attrib['abstract'], expected=True)
youtube_dl.utils.ExtractorError: This content requires a valid, unexpired auth token.
```
So, it's not even trying to authenticate, or get an auth token.

**Comment by gkoelln** [comment]
So, IMO, we need to add the authentication to either NBC or theplatform. It's just a bit above me, or I'd do it myself.

**Comment by yan12125** [comment]
Oops, I forgot you're the author of Dish authenticator. Yes nbc.py needs an update.

**Comment by gkoelln** [comment]
Thanks!
