### ISSUE TITLE
Warning message on svt

### ISSUE THREAD

**Issue by norden1** [rg3/youtube-dl#12014]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.02.07
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by norden1** [comment]
I get warning message and cant download this
http://www.svtplay.se/klipp/3909543/hans-roslings-brandtal

**Comment by yan12125** [comment]
Please paste the full log, including all warning messages

**Comment by MR-2** [comment]
http://api.svt.se/videoplayer-api/video/3909543
API is returning
{"message":"Error when accessing clip API","status":400}.
This is an issue for the provider to deal with.

**Comment by norden1** [comment]
I Think the link is temporarly broken it works yesterday.  Maybe I can found the clip on another site.

**Comment by MR-2** [comment]
Nonetheless this issue is currently related to the provider. If you want it resolved I suggest that you file a complaint with the provider. This issue can be closed

**Comment by yan12125** [comment]
Or maybe it's geo-restricted to Sweden? Some websites doesn't handle georestrictions well and just failed.

**Comment by MR-2** [comment]
I'm using a Swedish ISP. Their player returns that the "Unit can't play the video" it returns that because the manifests return a 404 error and therefor can't be played

**Comment by yan12125** [comment]
Thanks. Now I'm sure that the problem is in the SVT website.

**Comment by MR-2** [comment]
@yan12125 Just a note this clip isn't Geo-blocked "geoBlockedSweden":false". @norden1 Whether or not that the clip was working yesterday I don't know but I highly doubt that it was because if it would have been working you would most likely not have encountered any problems with downloading it. Please notify the provider about this publishing issue.

**Comment by norden1** [comment]
I have sent a mail to the provider (SVT.se) and i get back when i get answer from them.
Thanks for your time and interest.
And if it geo restricted or not should not have effect for me because i leave in Sweden and also pay the license.

**Comment by MR-2** [comment]
@norden1 seems like the provider has made the decision to unpublish this clip.

**Comment by norden1** [comment]
Hi again now i get answer from svt. They wrote that the link has expired. Now the link are away. I get Little confused when i tried to download  and the link work the day before and without a message that say how long the link is Active. I often download from svt with Youtube dlg and it works very good for me. And svt use to wrote  how long the programme are available but not in this way.
