### ISSUE TITLE
Add support for putlockers.ch 

### ISSUE THREAD

**Issue by gnurt1** [rg3/youtube-dl#12029]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

### Before submitting an *issue* make sure you have:
- [] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Putlockers.ch has films that don't have copyrights. That i want to download:
https://en.wikipedia.org/wiki/List_of_films_in_the_public_domain_in_the_United_States
THE AMAZING MR. X (1948) http://putlockers.ch/watch-the-amazing-mr-x-online-free-putlocker.html
A FAREWELL TO ARMS (1957) http://putlockers.ch/watch-a-farewell-to-arms-1957-online-free-putlocker.html
THE DEVIL (1940) http://putlockers.ch/watch-the-devil-bat-online-free-putlocker.html
BLOOD ON THE SUN (1945) http://putlockers.ch/watch-blood-on-the-sun-online-free-putlocker.html
THE GENERAL (1926) http://putlockers.ch/watch-the-general-1926-online-free-putlocker.html

(There are many more) So can you please add support for the website.

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
