### ISSUE TITLE
ESPNFC falls back to generic

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#12028]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.py -v "http://espnfc.com/video/espnfc/video?id=3056052"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://espnfc.com/video/espnfc/video?id=305
6052']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.07
[debug] Python version 2.7.6 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-83410-gb1e2192, rtmpdump 2.4
[debug] Proxy map: {}
[generic] video?id=3056052: Requesting header
[redirect] Following redirect to http://www.espnfc.com/video/espn-fc-tv/86/video
/3056052
[generic] 3056052: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3056052: Downloading webpage
[generic] 3056052: Extracting information
ERROR: Unsupported URL: http://www.espnfc.com/video/espn-fc-tv/86/video/3056052
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 1
741, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\compat.py", line 2526, in com
pat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=
_element_factory)))
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\compat.py", line 2515, in _XM
L
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 11, column 561
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 696, in e
xtract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 36
9, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 2
589, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.espnfc.com/video/espn-fc-tv/86/vid
eo/3056052


---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.espnfc.com/video/espn-fc-tv/86/video/3056052


- Direct link to video DOES WORK:
http://media.video-cdn.espn.com/motion/ESPNi/2017/0207/int_170207_Whats_wrong_with_Ranieri_and_his_players/hls/804_4778593_HBR.m3u8



Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

At one point in the past I believe there was an extractor for ESPNFC, but I no longer see it listed. (not certain?)
As noted above, the direct link to the video on ESPN does download correctly;  So maybe the ESPNFC.COM domain might just need to be added to the ESPN extractor?


Thanks
Ringo

**Comment by yan12125** [comment]
> At one point in the past I believe there was an extractor for ESPNFC, but I no longer see it listed

It's never merged https://github.com/rg3/youtube-dl/pull/8053

And for this link, it redirects to, http://www.espnfc.com/video/espn-fc-tv/86/video/3056052, which is actually the same as #7858 (www.espnfc.com and www.espnfc.us are interchangeable)
