### ISSUE TITLE
Return completed flag for use in script?

### ISSUE THREAD

**Issue by SkydiverFL** [rg3/youtube-dl#12022]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

Is there a way for youtube-dl to load the manifest of videos to download and **return a status or code (especially in quiet mode)** to indicate if all of the videos have been downloaded or not?  I would like to use this status in a script to determine if work still needs to be done.  For example, if downloading an entire Youtube channel or Pluralsight course.

**Comment by dstftw** [comment]
What signal are you talking about? When you run youtube-dl either as a process or a python script using `YoutubeDL.download` or so, it won't return until the work is done (assuming you you pass ignore errors option). When it returns then it's done - that is your signal.
