### ISSUE TITLE
[xtube] broken extraction

### ISSUE THREAD

**Issue by paulguy** [rg3/youtube-dl#12023]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'redacted, happens with all videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.07
[debug] Python version 2.7.12 - Linux-4.4.26-gentoo-x86_64-Intel-R-_Core-TM-_i7-2600_CPU_@_3.40GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.8.8, ffprobe 2.8.8, rtmpdump 2.4
[debug] Proxy map: {}
[XTube] redacted: Downloading webpage
ERROR: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 696, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/xtube.py", line 63, in _real_extract
    r'sources\s*:\s*({.+?}),', webpage, 'sources'), video_id)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 672, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
---

### Description of your *issue*, suggested solution and other information

Site changed in some ways.  I narrowed it down to changing `r'sources\s*:\s*({.+?}),'` to `r'\"sources\"\s*:\s*({.+?}),'`, changing `Runtime:` to `Runtime` and `Views:` to `Views`.

**Comment by ThomasChr** [comment]
@paulguy So you got it working again? Than all you need to do is make a pull request for your fixes.

**Comment by paulguy** [comment]
Last time I made a pull request to this project, I was presented with the usual programmer's rudeness so they can just put the fixes in themselves, or don't.

**Comment by ThomasChr** [comment]
@paulguy I know exactly what you mean and I'm sorry for that! I'll try a PR tomorrow with your changes, let's see what happens.

**Comment by ThomasChr** [comment]
@paulguy I had no problems downloading from this page. Could you please provide me with a testlink?

**Comment by paulguy** [comment]
Downloading http://www.xtube.com/video-watch/bbc-breeding-white-bottom-30051611 with curl with the cookies mentioned in the extractor still shows the `sources:` string changed to `"sources":` on line 214, although I would have to revert back my fixes to test if it actually does fail to extract information.  "Views" and "Runtime" still appear to be missing their colons.
