### ISSUE TITLE
Ebaumsworld.com ERROR: Unable to download XML: HTTP Error 403: Forbidden (caused by HTTPError())

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#12024]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.py -v "http://www.ebaumsworld.com/videos/pats-fan-t
hrows-ball-to-victory-float-from-his-window-5-pats-sign-it-and-throw-it-back/852
60513/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.ebaumsworld.com/videos/pats-fan-
throws-ball-to-victory-float-from-his-window-5-pats-sign-it-and-throw-it-back/85
260513/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.07
[debug] Python version 2.7.6 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-83410-gb1e2192, rtmpdump 2.4
[debug] Proxy map: {}
[EbaumsWorld] 85260513: Downloading XML
ERROR: Unable to download XML: HTTP Error 403: Forbidden (caused by HTTPError())
; please report this issue on https://yt-dl.org/bug . Make sure you are using th
e latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl wit
h the --verbose flag and include its complete output.
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 41
6, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 2006, in
urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.ebaumsworld.com/videos/pats-fan-throws-ball-to-victory-float-from-his-window-5-pats-sign-it-and-throw-it-back/85260513/

- Single video: http://www.ebaumsworld.com/videos/the-pussy-slap-girls-take-their-prank-war-to-a-whole-new-level/85260829/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

Thanks
Ringo

**Comment by ThomasChr** [comment]
No problem here.

> [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.ebaumsworld.com/videos/pats-fan-throws-ball-to-victory-float-from-his-window-5-pats-sign-it-and-throw-it-back/85260513/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.07
[debug] Git HEAD: c8b8fb0
[debug] Python version 2.7.12 - Linux-4.4.0-59-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.10-0ubuntu0.16.04.1, ffprobe 2.8.10-0ubuntu0.16.04.1
[debug] Proxy map: {}
[EbaumsWorld] 85260513: Downloading XML
[debug] Invoking downloader on u'http://level3.ebaumsworld.com/mediaFiles/video/2183782/2469/85260513.mp4'
[download] Destination: Pats Fan Throws Ball To Victory Float From His Window, 5 Pats Sign It And Throw It Back-85260513.mp4
[download] 100% of 2.92MiB in 00:00

**Comment by RingoTheDog** [comment]
#FAIL
Seems there is some inconsistency with our firewall (sometimes works and sometimes does not !?!?)

Sorry
