### ISSUE TITLE
Why youtube-dl cannot download this Youtube Video? 

### ISSUE THREAD

**Issue by almustaness** [rg3/youtube-dl#12036]
I am trying to download this video but it does not download. It seems because of the Arabic Title:
https://www.youtube.com/watch?v=ZKuvdUy1a50

**Comment by MR-2** [comment]
I can't reproduce this issue, which version are you using?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by ThomasChr** [comment]
No problem here.
I'm thinking you're not using the most recent version.

**Comment by almustaness** [comment]
@MR-2 @dstftw @ThomasChr 
Today i tried it again and it is working. I do not know what was the issue
