### ISSUE TITLE
Errors downloading youtube playlists. Error 404. Python 3

### ISSUE THREAD

**Issue by tfree87** [rg3/youtube-dl#12032]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --verbose -x -i --audio-format vorbis --audio-quality 6 "https://www.youtube.com/watch\?v\=XebG4TO_xss\&list\=PLmKbqjSZR8TYD9bf1-N9MYe_cSEwQAx43"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-x', '-i', '--audio-format', 'vorbis', '--audio-quality', '6', 'https://www.youtube.com/watch\\?v\\=XebG4TO_xss\\&list\\=PLmKbqjSZR8TYD9bf1-N9MYe_cSEwQAx43']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.07
[debug] Python version 3.5.2 - Linux-4.9.7-201.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five
[debug] exe versions: ffmpeg 3.1.5, ffprobe 3.1.5
[debug] Proxy map: {}
[generic] watch\?v\=XebG4TO_xss\&list\=PLmKbqjSZR8TYD9bf1-N9MYe_cSEwQAx43: Requesting header
WARNING: Could not send HEAD request to https://www.youtube.com/watch\?v\=XebG4TO_xss\&list\=PLmKbqjSZR8TYD9bf1-N9MYe_cSEwQAx43: HTTP Error 404: Not Found
[generic] watch\?v\=XebG4TO_xss\&list\=PLmKbqjSZR8TYD9bf1-N9MYe_cSEwQAx43: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2006, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib64/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

While trying to extract audio from Youtube playlists, I seem to always receive an HTTP Error 404 from urllib request.py.

I have used other software programs that function similarly to Youtube-dl and have not had any issues with those so I know the links are fine. In addition, if I right click on an individual video and select "Copy video url" and use that as an argument for youtube-dl the video always downloads and extracts the audio properly. I have updated the youtube-dl script regularly on Fedora using pip3 and I can tell from the verbose command output that youtube-dl is using Python 3 libraries. I know this issue has come up in Python 2 (#8918) so I made sure to run the command with and without forcing the command to run under Python 3.

This seems to have only happened after I upgraded Fedora from 24 to 25. Prior to that I never had any difficulty downloading videos with youtube-dl.

**Comment by dstftw** [comment]
You either escape special characters or enclose URL in quotes. Not both at the same time.

**Comment by tfree87** [comment]
I see, somehow my ZSH has switched to automatically escaping pasted characters and I did not catch this issue.

**Comment by tfree87** [comment]
Thanks for the quick response and I am sorry for wasting time on such a simple fix.
