### ISSUE TITLE
can't download playlist of youtube video

### ISSUE THREAD

**Issue by Primus-zhao** [rg3/youtube-dl#12033]
youtube-dl --verbose https://www.youtube.com/watch\?v\=F620ommtjqk\&index\=1\&list\=PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=F620ommtjqk&index=1&list=PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.07
[debug] Python version 2.7.12 - Linux-3.19.0-66-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6
[debug] Proxy map: {'http': 'http://127.0.0.1:8118', 'https': 'https://127.0.0.1:8118'}
[youtube:playlist] Downloading playlist PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2 - add --no-playlist to just download video F620ommtjqk
[youtube:playlist] PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2: Downloading webpage
[download] Downloading playlist: Intro to Parallel Programming
[youtube:playlist] PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2: Downloading page #1
ERROR: Unable to download JSON metadata: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2006, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1048, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
youtube-dl --version
2017.02.07

**Comment by ThomasChr** [comment]
I can't reproduce it. The link https://www.youtube.com/watch?v=F620ommtjqk&index=1&list=PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2 is a single video which works fine to download.

Also downloading the playlist https://www.youtube.com/playlist?list=PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2 works fine (458 videos).

**Comment by Primus-zhao** [comment]
@ThomasChr 
Sorry, my fault, i intend to download all videos from the playlist but copy the wrong url,  the log file is as follows:
 youtube-dl --verbose https://www.youtube.com/playlist?list=PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/playlist?list=PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.07
[debug] Python version 2.7.12 - Linux-4.4.0-62-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {'http': 'http://127.0.0.1:8118', 'https': 'https://127.0.0.1:8118'}
[youtube:playlist] PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2: Downloading webpage
[download] Downloading playlist: Intro to Parallel Programming
[youtube:playlist] PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2: Downloading page #1
ERROR: Unable to download JSON metadata: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2006, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1048, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
And the version is 2017.02.07

**Comment by ThomasChr** [comment]
Sorry for that, but no problem on my machine:

> [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/playlist?list=PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.07
[debug] Git HEAD: b049757
[debug] Python version 2.7.12 - Linux-4.4.0-59-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.10-0ubuntu0.16.04.1, ffprobe 2.8.10-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube:playlist] PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2: Downloading webpage
[download] Downloading playlist: Intro to Parallel Programming
[youtube:playlist] PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2: Downloading page #1
[youtube:playlist] PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2: Downloading page #2
[youtube:playlist] PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2: Downloading page #3
[youtube:playlist] PLAwxTw4SYaPnFKojVQrmyOGFCqHTxfdv2: Downloading page #4
[youtube:playlist] playlist Intro to Parallel Programming: Downloading 458 videos
[download] Downloading video 1 of 458
[youtube] F620ommtjqk: Downloading webpage
[youtube] F620ommtjqk: Downloading video info webpage
[youtube] F620ommtjqk: Extracting video information
[youtube] F620ommtjqk: Downloading MPD manifest
[debug] Invoking downloader on u'https://r5---sn-4g57knsy.googlevideo.com/videoplayback?id=17adb4a269ad8ea9&itag=137&source=youtube&requiressl=yes&mv=u&mn=sn-4g57knsy&mm=31&ms=au&pl=20&ratebypass=yes&mime=video/mp4&gir=yes&clen=11178760&lmt=1443263549755353&dur=48.715&signature=6B5BD544B9B07C061116EECBAE588753A6B1F8FE.91FC46B6F8EE8461FD0F4F57C905F7FB3185BFA7&upn=eD-eM6yfZmU&mt=1486650099&beids=%5B9452307%5D&key=dg_yt0&ip=188.68.35.138&ipbits=0&expire=1486671832&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,mn,mm,ms,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Intro to the Class - Intro to Parallel Programming-F620ommtjqk.f137.mp4
[download] 100% of 10.66MiB in 00:00

**Comment by Primus-zhao** [comment]
Ok, got it, i think it's net connection problem. Thks for you quick reply! @ThomasChr
