### ISSUE TITLE
QuestTV.co.uk/video is supported in youtube-dl

### ISSUE THREAD

**Issue by BridgeUK** [rg3/youtube-dl#12038]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.exe -v http://www.questtv.co.uk/video
/#4855337231001
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.questtv.co.uk/video/#4855337231001
']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.07
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] #4855337231001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] #4855337231001: Downloading webpage
[generic] #4855337231001: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: Quest On Demand
[generic] playlist Quest On Demand: Collected 1 video ids (downloading 1 of them
)
[download] Downloading video 1 of 1
[brightcove:legacy] 4855337231001: Downloading webpage
[brightcove:legacy] 4855337231001: Extracting information
[debug] Invoking downloader on 'http://discoveryint1.edgeboss.net/download/disco
veryint1/byocdn/media/21742340001/201604/3073/21742340001_4855462589001_ESD-8640
96B-QUEST.mp4'
[download] Destination: How It's Made - Bottle Tops_Chocolate_Pills_Pasta-485533
7231001.mp4
[download] 100% of 272.27MiB in 00:18
[download] Finished downloading playlist: Quest On Demand
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.questtv.co.uk/video/#4855337231001

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

This posting isn't an issue, it's just to say the website www.QuestTV.co.uk/video is supported in youtube-dl and to ask can the website be added to the list of supported websites http://rg3.github.io/youtube-dl/supportedsites.html thank you very much

**Comment by dstftw** [comment]
This site is supported as Brightcover embed via generic extractor.
