### ISSUE TITLE
Wrong video on GolfChannel.com

### ISSUE THREAD

**Issue by BridgeUK** [rg3/youtube-dl#12044]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Feature request (request for a new functionality)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.exe -v http://www.golfchannel.com/topics/shows/golftalkcentral.htm
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.golfchannel.com/topics/shows/golftalkcentral.htm']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.07
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] golftalkcentral: Requesting header
WARNING: Falling back on generic information extractor.
[generic] golftalkcentral: Downloading webpage
[generic] golftalkcentral: Extracting information
ERROR: Unsupported URL: http://www.golfchannel.com/topics/shows/golftalkcentral.htm
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\bu
ild\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\bu
ild\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\bu
ild\youtube_dl\extractor\generic.py", line 2589, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.golfchannel.com/topics/shows/golftalkcentral.htm
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.golfchannel.com/topics/shows/golftalkcentral.htm

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

If I type youtube-dl.exe -v http://www.golfchannel.com/topics/shows/golftalkcentral.htm the video can't be found by youtube-dl because it's embedded with an iframe, by going directly to the iframe the video downloads with youtube-dl.exe -v http://player.theplatform.com/p/BxmELC/gc_player/select/MvpaHSLOYmcu

**Comment by yan12125** [comment]
Thanks for the report. Such embedded URLs will be detected in the next version.

**Comment by BridgeUK** [comment]
Thank you very much.

**Comment by BridgeUK** [comment]
@yan12125 Thank you very much.

**Comment by BridgeUK** [comment]
@yan12125 I just updated to the latest version to try again, but the first (main) video doesn't download, a different one does instead

`youtube-dl.exe -v http://www.golfchannel.com/topics/shows/golftal
kcentral.htm
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.golfchannel.com/topics/shows/golft
alkcentral.htm']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.17
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-83410-gb1e2192, ffprobe N-83410-gb1e2192
[debug] Proxy map: {}
[generic] golftalkcentral: Requesting header
WARNING: Falling back on generic information extractor.
[generic] golftalkcentral: Downloading webpage
[generic] golftalkcentral: Extracting information
[download] Downloading playlist: Golf Central
[generic] playlist Golf Central: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[ThePlatform] L4qXAX4dC0UU: Downloading SMIL data
[ThePlatform] L4qXAX4dC0UU: Checking video URL
[ThePlatform] L4qXAX4dC0UU: Checking video URL
[ThePlatform] L4qXAX4dC0UU: Checking video URL
[ThePlatform] L4qXAX4dC0UU: Checking video URL
[ThePlatform] L4qXAX4dC0UU: Checking video URL
[ThePlatform] L4qXAX4dC0UU: Downloading JSON metadata
[debug] Invoking downloader on 'http://golfchannelvod-amd.akamaized.net/NBCU_Spo
rts_Group_-_GolfChannel/290/887/2017-02-17T18-42-53.148Z--50.718__399946.mp4'
[download] Destination: Wie 'clawing' up the leaderboard in Australia-L4qXAX4dC0
UU.mp4
[download] 100% of 20.69MiB in 00:06
[download] Finished downloading playlist: Golf Central`

**Comment by yan12125** [comment]
Here's what I got:
```
$ youtube-dl -v "http://www.golfchannel.com/topics/shows/golftalkcentral.htm"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.golfchannel.com/topics/shows/golftalkcentral.htm']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.17
[debug] Git HEAD: 70bcc444a
[debug] Python version 3.6.0 - Linux-4.9.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[generic] golftalkcentral: Requesting header
WARNING: Falling back on generic information extractor.
[generic] golftalkcentral: Downloading webpage
[generic] golftalkcentral: Extracting information
[download] Downloading playlist: Golf Central
[generic] playlist Golf Central: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[ThePlatform] _4D5PkdK4vAe: Downloading SMIL data
[ThePlatform] _4D5PkdK4vAe: Checking video URL
[ThePlatform] _4D5PkdK4vAe: Checking video URL
[ThePlatform] _4D5PkdK4vAe: Checking video URL
[ThePlatform] _4D5PkdK4vAe: Checking video URL
[ThePlatform] _4D5PkdK4vAe: Checking video URL
[ThePlatform] _4D5PkdK4vAe: Checking video URL
[ThePlatform] _4D5PkdK4vAe: Checking video URL
[ThePlatform] _4D5PkdK4vAe: Downloading JSON metadata
[debug] Invoking downloader on 'http://golfchannelvod-amd.akamaized.net/NBCU_Sports_Group_-_GolfChannel/514/511/1487372403.154--882.863c1487373406.958--525.087c1487374083.234--345.844c1487374550.434--157.825c1487374873.891--419.687c1487375459.544--106.506c1487375716.801--285.271__480818.mp4'
[download] Resuming download at byte 94633984
[download] Destination: Golf Central - February 17, 2017-_4D5PkdK4vAe.mp4
[download]  11.3% of 1.02GiB at  1.29MiB/s ETA 11:53^CException ignored in: <_io.FileIO name='Golf Central - February 17, 2017-_4D5PkdK4vAe.mp4.part' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='Golf Central - February 17, 2017-_4D5PkdK4vAe.mp4.part'>

ERROR: Interrupted by user
```
It's 45 minutes long. Is that "the main video"?

**Comment by BridgeUK** [comment]
@yan12125 yeah that's the main video

**Comment by yan12125** [comment]
Could you run ```youtube-dl -v "http://www.golfchannel.com/topics/shows/golftalkcentral.htm" --write-pages``` and upload all *.dump files?

**Comment by BridgeUK** [comment]
That's strange, it's downloading now, I'm not sure what happened before, it's working, thank you very much

**Comment by yan12125** [comment]
Alright. Feel free to leave comments if something is wrong again.
