### ISSUE TITLE
Determine completed status without downloading videos?

### ISSUE THREAD

**Issue by SkydiverFL** [rg3/youtube-dl#12047]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

How can I determine from bash if youtube-dl still has work to do for a particular playlist WITHOUT downloading videos?  For example, if youtube-dl is used to CONTINUE downloading an existing playlist (for example, a Pluralsight course, a Youtube channel, etc.), youtube-dl loads the manifest and determines one-by-one if a video has already been downloaded.  I would like to use youtube-dl to determine if all of the videos have already been downloaded WITHOUT doing the actual download.  The goal is to mark the Pluralsight course or Youtube channel as "complete" so I may continue with other automated processing.

**Comment by dstftw** [comment]
Store video ids in `--download-archive` per playlist. List ids for a playlist with `-o '%(extractor)s %(id)s' --get-filename` and match against the archive file. If all of them present in the archive file then it's finished.
