### ISSUE TITLE
Unable to rip liveleak url

### ISSUE THREAD

**Issue by dprski33** [rg3/youtube-dl#12053]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.10**
2017.02.07
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

```
youtube-dl -v -k -f mp4 -o '/tmp/liveleak037_1486100393.mp4'  'https://www.liveleak.com/view?i=037_1486100393'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-k', u'-f', u'mp4', u'-o', u'/tmp/liveleak037_1486100393.mp4', u'https://www.liveleak.com/view?i=037_1486100393']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.07
[debug] Python version 2.7.6 - Linux-3.13.0-93-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-80901-gfebc862, ffprobe N-80901-gfebc862
[debug] Proxy map: {}
[LiveLeak] 037_1486100393: Downloading webpage
ERROR: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 696, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/liveleak.py", line 107, in _real_extract
    webpage, 'embed URL')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 672, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.liveleak.com/view?i=037_1486100393

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information
It's unclear why this Liveleak URL cannot be ripped

**Comment by memkeytm** [comment]
1 http://www.liveleak.com/view?i=4f7_1392687779 has **lost**.

2 liveleak has changed again. the code is new extract:
```
    def _real_extract(self, url):
        video_id = self._match_id(url)
        webpage = self._download_webpage(url, video_id)

        video_title = self._og_search_title(webpage).replace('LiveLeak.com -', '').strip()
        video_description = self._og_search_description(webpage)
        video_uploader = self._html_search_regex(
            r'By:.*?(\w+)</a>', webpage, 'uploader', fatal=False)
        age_limit = int_or_none(self._search_regex(
            r'you confirm that you are ([0-9]+) years and over.',
            webpage, 'age limit', default=None))
        video_thumbnail = self._og_search_thumbnail(webpage)

        formats = []
        for (_, url, _, label) in re.findall(r'source src=(["\'])(?P<url>.+?)\1.+?label=(["\'])(?P<label>.+?)\3', webpage):
            format_id = self._search_regex(r'_(\d+?)p', url, 'format_id', default=None)
            a_format = { 'format_note': label, 'url': url }
            if format_id:
                a_format['format_id'] = '%s' % format_id
            formats.append(a_format)
        if len(formats) > 0:
            self._sort_formats(formats)
            return {
                'id': video_id,
                'title': video_title,
                'description': video_description,
                'uploader': video_uploader,
                'formats': formats,
                'age_limit': age_limit,
                'thumbnail': video_thumbnail,
            }
        else:
            alt_source = self._search_regex(
                r'(file: ".*?"),', webpage, 'video URL', default=None)
            if alt_source:
                sources_raw = '[{ %s}]' % alt_source
            else:
                # Maybe an embed?

                embed_url = self._search_regex(
                    r'<iframe[^>]+src="((?:https?:)?//(?:www\.)?(?:prochan|youtube)\.com/embed[^"]+)"',
                    webpage, 'embed URL', default=None)
                if not re.match(r'https?:', embed_url):
                    mobj = re.search(r'(https?:)', url)
                    protocol = mobj.group(1) if mobj else 'http:'
                    embed_url = '%s%s' % (protocol, embed_url)
                return {
                    '_type': 'url_transparent',
                    'url': embed_url,
                    'id': video_id,
                    'title': video_title,
                    'description': video_description,
                    'uploader': video_uploader,
                    'age_limit': age_limit,
                }
```

**Comment by dprski33** [comment]
Any update on this?

**Comment by enterhaken** [comment]
Ran into this as well, as I think:
~ date
Mit Mai 10 07:37:09 CEST 2017
                                --- 07:37:09, Mit Mai 10 ---
~ sudo youtube-dl -U
youtube-dl is up-to-date (2017.05.09)
                                --- 07:37:21, Mit Mai 10 ---
~ youtube-dl --verbose https://www.liveleak.com/view?i=018_1494125504
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.liveleak.com/view?i=018_1494125504']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.09
[debug] Python version 2.7.9 - Linux-4.9.0-0.bpo.2-amd64-x86_64-with-debian-8.7
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6, rtmpdump 2.4
[debug] Proxy map: {}
[LiveLeak] 018_1494125504: Downloading webpage
ERROR: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/liveleak.py", line 107, in _real_extract
    webpage, 'embed URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Hrxn** [comment]
Yes, can confirm, same error here.
```
ERROR: Unable to extract embed URL;
...
..\youtube_dl\extractor\common.py", line 782, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract embed URL; 
```
 Liveleak is listed as a [supported](https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md) site, so this is a legit issue.

Okay, this already has a suitable label.

**Comment by yan12125** [comment]
Thanks for the report and sorry for the late response. Liveleak videos will be supported again in the next version.
