### ISSUE TITLE
Site Request: funimationnow.uk

### ISSUE THREAD

**Issue by BridgeUK** [rg3/youtube-dl#12064]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.10**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Site support request (request for adding support for a new site)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.exe -v https://www.funimationnow.uk/shows
/akibas-trip-the-animation/akibas-first-trip/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.funimationnow.uk/shows/akibas-tri
p-the-animation/akibas-first-trip/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.07
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-83410-gb1e2192, ffprobe N-83410-gb1e2192
[debug] Proxy map: {}
[generic] akibas-first-trip: Requesting header
WARNING: Falling back on generic information extractor.
[generic] akibas-first-trip: Downloading webpage
[generic] akibas-first-trip: Extracting information
ERROR: Unsupported URL: https://www.funimationnow.uk/shows/akibas-trip-the-anima
tion/akibas-first-trip/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\bu
ild\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\bu
ild\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\bu
ild\youtube_dl\extractor\generic.py", line 2589, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.funimationnow.uk
/shows/akibas-trip-the-animation/akibas-first-trip/
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.funimationnow.uk/shows/akibas-trip-the-animation/akibas-first-trip/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I'd like to request for funimationnow.uk please, thank you.

**Comment by yan12125** [comment]
I got an almost blank page on https://www.funimationnow.uk/shows/akibas-trip-the-animation/akibas-first-trip/. Is the video still available? Or maybe it's limited to UK?

**Comment by BridgeUK** [comment]
It's working on this end, yeah I think it's limited to the UK.

**Comment by yan12125** [comment]
Got it. I set "cant-reproduce" first as I am unable to play the video

**Comment by kaithar** [comment]
I'd rather like support for this site... what information do you need?

**Comment by yan12125** [comment]
Just got an UK proxy and I can finally see a video on https://www.funimationnow.uk/shows/akibas-trip-the-animation/akibas-first-trip/. However, it's restricted:

> This video contains mature content.
To continue, log in or create an account.

If would be great if there's another video available to everyone.

**Comment by kaithar** [comment]
Okie, how about this one?
https://www.funimationnow.uk/shows/ouran-high-school-host-club/starting-today-you-are-a-host/
Public non-nsfw :)

**Comment by yan12125** [comment]
Thanks. That's a big help.

**Comment by Starsam80** [comment]
Could you also take a look at #11773 and kill 2 birds with 1 stone? I don't have a UK proxy to compare the sites but since they are both funimation, they should work the same.

**Comment by yan12125** [comment]
Thanks for the information. Yep they look the same. funimation.com is redirected to funimationnow.uk with UK proxies, and the UK URL is redirected to funimation.com with US proxies. I guess they are identical, so I'd like to merge the two requests. For further discussions, please move to #11773
