### ISSUE TITLE
Put a sleep between downloads for batch-mode downloads

### ISSUE THREAD

**Issue by sevakmaheshr** [rg3/youtube-dl#12063]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

So let's say I am downloading a youtube or udemy playlist. I am not certain who's doing it, but, youtube-dl stops working after some time. I have killall python, and then restart the download process.

What I would like is this: when downloading a playlist ... youtube-dl should automatically insert a "sleep <some small value like say 30s>" between multiple downloads. So, e.g., youtube-dl could sleep for 30s after downloading 5 or 10 videos. And then the download op can continue downloading further.

Why do I need this feature? Because it is my (unproven) belief that the peeps admining the servers are somehow reseting my download connection as soon as they realize that a particular host if "downloading" rather than browsing and watching the videos.

Appreciate if you add this feature.

**Comment by dstftw** [comment]
There is only sleep between each download available.
```
--sleep-interval SECONDS         Number of seconds to sleep before each
                                 download when used alone or a lower bound
                                 of a range for randomized sleep before each
                                 download (minimum possible number of
                                 seconds to sleep) when used along with
                                 --max-sleep-interval.
--max-sleep-interval SECONDS     Upper bound of a range for randomized sleep
                                 before each download (maximum possible
                                 number of seconds to sleep). Must only be
                                 used along with --min-sleep-interval.
```
