### ISSUE TITLE
could not get single streaming url containing audio + video of youtube videos

### ISSUE THREAD

**Issue by arushijain45** [rg3/youtube-dl#12061]
I am trying to get streaming url of youtube video using following command
youtube-dl -g <video-url>
but it is giving me two different streaming urls one for audio-only and other for video-only. However I have seen in other applications like (NewPipe) which is getting single streaming url containing both audio and video. So how I can achieve this?

**Comment by yan12125** [comment]
```youtube-dl -g -f best <your URL>```

**Comment by arushijain45** [comment]
wow... thanku so much sir... can you please provide me the link of documentation because I could not find it in readme.md

**Comment by yan12125** [comment]
https://github.com/rg3/youtube-dl#format-selection should be useful

**Comment by arushijain45** [comment]
okay thanku...
