### ISSUE TITLE
-g option no longer working with Youtube /  MPC-HC please fix it

### ISSUE THREAD

**Issue by silvercool2k** [rg3/youtube-dl#12074]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
This is how I do it, I copy the youtube link to the clipboard then I run this windows script. 

@echo off
for /f %%i in ('paste.exe') do set id=%%i
youtube-dl.exe -g %id% > Youtube.m3u8

start Youtube.m3u8 /fullscreen

--------------
This starts MPC-HC in fullscreen and runs the youtube video stream, yesterday it stopped working. 

It now says "cannot render the file."

I don't know what  changed... VLC can play it, but I don't like VLC. 


Here's the Link: https://www.youtube.com/watch?v=zkKteggEqrU

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

It was working fine up until yesterday and I've had it for months, now it says "cannot render file". No change has been made. I've updated to the latest version, still same issue. 
---

### Description of your *issue*, suggested solution and other information

Something changed in Youtube I'm guessing an update or something, new encryption settings or something? I don't know... All I know is that it was working well for months and all the sudden yesterday it doesn't work.

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by silvercool2k** [comment]
2017.02.10

youtube-dl.exe -v -g https://www.youtube.com/watch?v=zkKteggEqrU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-g', 'https://www.youtube.com/watch?v=zkKtegg
EqrU']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.10
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
https://r2---sn-ugpjvh-nupl.googlevideo.com/videoplayback?upn=dP--Mwb6vT8&lmt=12
98903458197046&expire=1486768875&ratebypass=yes&mime=video%2Fwebm&ipbits=0&initc
wndbps=827500&pl=23&signature=8413613B9159E2BBC14B5319C9501CD25EF85108.DF59D8648
1105D1AF01AE53A74B3534CBFDC8BA7&key=yt6&ip=190.94.58.162&itag=43&sparams=clen%2C
dur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2C
ms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ei=i_adWK6SGoym-g
Wm8IaoCg&requiressl=yes&source=youtube&clen=15083782&mt=1486747224&mv=m&ms=au&gi
r=yes&mm=31&mn=sn-ugpjvh-nupl&id=o-ABbJuFmprn0qvOWDfi-dXuDlPjgjO5glJ6o0ehknM9KU&
dur=0.000

**Comment by yan12125** [comment]
> I don't know what changed... VLC can play it, but I don't like VLC.

Clearly the problem is in MPC-HC. Report a bug to them

**Comment by silvercool2k** [comment]
it was working fine for months...

**Comment by yan12125** [comment]
YouTube servers may change to a different codec. I guess VLC can support both the new one and the old one, yet MPC-HC not.

**Comment by silvercool2k** [comment]
not about the codec its about the video stream url

**Comment by yan12125** [comment]
I don't know the real cause. That was just my guess. As I've said, if VLC works but MPC-HC not, it's clear that MPC-HC has problems. Go ahead to https://trac.mpc-hc.org/wiki/How_to_Report_Issues and report a bug there, just like what you've done here on youtube-dl.

**Comment by silvercool2k** [comment]
why would you close a ticket if you don't know the real cause? is this how you handle all tickets?

**Comment by yan12125** [comment]
Because the problem is in MPC-HC, not in youtube-dl.

**Comment by silvercool2k** [comment]
not true! have you read anything I've said? it was working fine for months... .ok lets do this... which other site does youtube-dl works with? lets test a different site ok? you tell me....

**Comment by silvercool2k** [comment]
I was also getting this error/ Unable to extract uploader nickname

**Comment by dstftw** [comment]
1. The link provided works just fine with youtube-dl thus the problem is not in youtube-dl.
```
PS C:\Dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py -f best https://www.youtube.com/watch?v=zkKteggEqrU
[youtube] zkKteggEqrU: Downloading webpage
[youtube] zkKteggEqrU: Downloading video info webpage
[youtube] zkKteggEqrU: Extracting video information
[youtube] zkKteggEqrU: Downloading MPD manifest
[download] Destination: Tribu del Sol - Por ti-zkKteggEqrU.webm
[download]  27.8% of 14.39MiB at 10.53MiB/s ETA 00:00
ERROR: Interrupted by user
```
2. Your script is fundamentally incorrect because download URLs extracted with `-g` must be visited with the [same set of headers and cookies](https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser) that youtube-dl does. Neither of them you honour.
