### ISSUE TITLE
When youtube-dl requires authentication when download YouTube video

### ISSUE THREAD

**Issue by Khang-NT** [rg3/youtube-dl#12080]
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Seem like youtube-dl always does "login" in init phase with all videos if user specify "username" and "password" parameter. 

```python
    def _real_initialize(self):
        if self._downloader is None:
            return
        self._set_language()
        if not self._login():
            return
```

Usually it is not necessary with public youtube video and no age restriction. 
My question is which YouTube video requires authentication? Could "youtube-dl" only login when in forced situation?
Login many times can move us into bad situation like: blocking or "security notice" requires sms verify.

I integrated youtube-dl to my system which makes ~ 100.000 requests per day, so login 100.000 times is impossible. 

_youtube-dl_ is awesome project, thanks your team!

**Comment by dstftw** [comment]
Use `--cookies` instead of providing credentials.
