### ISSUE TITLE
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found 

### ISSUE THREAD

**Issue by rituparnog** [rg3/youtube-dl#12094]
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found 
for Plural site
https://app.pluralsight.com/library/courses/azure-sql-data-warehouse-first-look/table-of-contents
updated to version:2017.02.11 still getting error

command: youtube-dl https://app.pluralsight.com/library/courses/azure-sql-data-warehouse-first-look/table-of-contents --username XXXX --password XXXX
version:2017.02.11

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by rituparnog** [comment]
I am using latest version --- 2017.02.11 still getting error.

**Comment by Locheed** [comment]
Not a bug. Downloading at the moment myself. youtube-dl [options] [URL].

Also remove table-of-contents from the end url.

**Comment by dstftw** [comment]
Prove that.
