### ISSUE TITLE
youtube-dl-mp3

### ISSUE THREAD

**Issue by rst0git** [rg3/youtube-dl#12092]
Hi, I am using youtube-dl for a while now and I think it is amazing. I would contribute to the project somehow.

One thing that might be useful could be the shortcut I'm using to download the best audio format in "mp3".

```sh
/usr/bin/youtube-dl-mp3
-------------------------------------
#!/bin/bash
youtube-dl --extract-audio --audio-format mp3 -f bestaudio --ignore-errors -o "%(title)s.%(ext)s" $@
```

**Comment by yan12125** [comment]
Ha. Name conflicts :) https://github.com/jweslley/youtube-dl-mp3
