### ISSUE TITLE
1080p support for Hotstar

### ISSUE THREAD

**Issue by johnsmathew** [rg3/youtube-dl#12096]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.11*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Hotstar shows upto 720p videos on their website and youtube-dl supports all of them. However, modifying the m3u8 file url gives 1080p videos. Does adding support to download a higher quality video than the ones provided in the original website violates any of the terms of youtube-dl?

**Comment by yan12125** [comment]
> modifying the m3u8 file url gives 1080p videos

Please give an example video and how to do such a modification

**Comment by johnsmathew** [comment]
Modifying the format_url as follows after getting it from `format_data['src']`

`format_url = re.sub(r'(_STAR.mp4)', r'3000,4500,\1', format_url)`

youtube-dl then lists 1080p with the available video formats.

**Comment by yan12125** [comment]
Interesting. How did you find this hack?

**Comment by johnsmathew** [comment]
Today I had to download few videos from hotstar and found this in a forum. This has been around for over an year. But everyone suggested manually modifying the link and using ffmpeg to capture the stream. So I thought I would share it here.

**Comment by yan12125** [comment]
It's OK to add dirty heuristics, just need to check URLs with _is_valid_url

**Comment by johnsmathew** [comment]
Please see this PR #12098
