### ISSUE TITLE
DailyMotion downloaded video broken

### ISSUE THREAD

**Issue by fireattack** [rg3/youtube-dl#12093]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.11*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\Administrator\Desktop>youtube-dl -v http://www.dailymotion.com/video/x5
7z7rb -f http-240 >a.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.dailymotion.com/video/x57z7rb', '-
f', 'http-320']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.02.11
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 2.8.4
[debug] Proxy map: {}
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

It seems downloading certain videos from DailyMotion always ends up a broken video that can't be played. 

This is no error during the download, but the result is a broken video: I can only 
 the first few minutes.
Video in question: http://www.dailymotion.com/video/x57z7rb

I tried several times with different quality (http-720, http-480, http-380), all same results.

I also tried different players (MPC, VLC, even Chrome), so I am pretty positive the video is actually broken, not just my player can't play it.

**Comment by yan12125** [comment]
Format http-1080 plays fine in VLC 2.2.4, MPV 0.23.0, Chromium 56.0.2924.87 and Firefox 51.0.1. It might be a system problem if multiple players are broken.

**Comment by fireattack** [comment]
I didn't try 1080p. Did you try http-720, http-480, http-320 as I mentioned?

**Comment by fireattack** [comment]
Hi, 

I just confirmed that http-1080 works fine. So the problem may be restricted to lower quality?

**Comment by fireattack** [comment]
Weird.. now everything is back to normal. I guess yesterday DailyMotion's server has some problem, then.

Thanks
