### ISSUE TITLE
How do i parse paylist json in php 

### ISSUE THREAD

**Issue by Deimos15** [rg3/youtube-dl#12107]
Hey wassup guys when i run:

`$output = shell_exec ('youtube-dl --flat-playlist --dump-json https://www.youtube.com/playlist?list=PLIzwoo4wkH0R97RBlZVARDTyWrjq5-Cvt');` in php i get a json output but how can i get the id's and titles in different variables?

**Comment by dstftw** [comment]
Use PHP's JSON parser obviously.
Offtopic.
