### ISSUE TITLE
ValueError: unknown url type

### ISSUE THREAD

**Issue by garilla22** [rg3/youtube-dl#12108]
Periodically observe the glitch after upgrade 10 days ago, nothing has changed. See screenshots.
![screenshot_2017-02-13-01-53-05](https://cloud.githubusercontent.com/assets/19745988/22868361/0bb28a3c-f1a6-11e6-9daa-9c8edeef20b7.png)
![screenshot_2017-02-13-01-53-19](https://cloud.githubusercontent.com/assets/19745988/22868362/0bb8b664-f1a6-11e6-8622-a89d1eb6533f.png)
My version youtube-dl: 2017.01.29. I use the app qPython. This same problem occurs with this playlist: https://www.youtube.com/watch?v=fkzGLro1PXI&list=PLTCvoQuRThNp41WNnl02lHiY-5zMtIwOM. I can give you even more than a hundred links to are experiencing this problem, but many video he shakes without any problems.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
