### ISSUE TITLE
Youtube 2160p - No H.264?

### ISSUE THREAD

**Issue by goldensun87** [rg3/youtube-dl#12106]
I've been noticing in many recent 2160p uploads, that there seems to be no h.264 mp4 option, only VP9 codec in .webm container.  Is Youtube phasing out h.264 for their 2160p uploads?  I'm sorry if this is not actually an issue, but I honestly did not know anywhere else to ask about this.  Here is an example url, with my -F results.

https://www.youtube.com/watch?v=Is3WqWwSF2Y

format code  extension  resolution note
249          webm       audio only DASH audio   55k , opus @ 50k, 1.37MiB
250          webm       audio only DASH audio   71k , opus @ 70k, 1.73MiB
171          webm       audio only DASH audio  105k , vorbis@128k, 2.57MiB
251          webm       audio only DASH audio  123k , opus @160k, 3.04MiB
140          m4a        audio only DASH audio  127k , m4a_dash container, mp4a.40.2@128k, 3.37MiB
278          webm       256x144    144p  100k , webm container, vp9, 24fps, video only, 2.44MiB
160          mp4        256x144    144p  113k , avc1.4d400c, 24fps, video only, 2.95MiB
242          webm       426x240    240p  201k , vp9, 24fps, video only, 3.25MiB
133          mp4        426x240    240p  249k , avc1.4d4015, 24fps, video only, 6.52MiB
134          mp4        640x360    360p  305k , avc1.4d401e, 24fps, video only, 6.49MiB
243          webm       640x360    360p  358k , vp9, 24fps, video only, 5.90MiB
135          mp4        854x480    480p  564k , avc1.4d401e, 24fps, video only, 13.42MiB
244          webm       854x480    480p  585k , vp9, 24fps, video only, 9.47MiB
247          webm       1280x720   720p 1089k , vp9, 24fps, video only, 18.60MiB
136          mp4        1280x720   720p 1119k , avc1.4d401f, 24fps, video only, 26.80MiB
248          webm       1920x1080  1080p 1953k , vp9, 24fps, video only, 34.44MiB
137          mp4        1920x1080  1080p 2198k , avc1.640028, 24fps, video only, 52.31MiB
271          webm       2560x1440  1440p 4493k , vp9, 24fps, video only, 87.94MiB
264          mp4        2560x1440  1440p 6440k , avc1.640032, 24fps, video only, 144.18MiB
313          webm       3840x2160  2160p 15035k , vp9, 24fps, video only, 322.70MiB
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3,  mp4a.40.2
43           webm       640x360    medium , vp8.0,  vorbis@128k
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)

**Comment by dstftw** [comment]
This should be addressed to YouTube.

**Comment by Hrxn** [comment]
I think it's intentional. Besides from being Google's format, VP9 doesn't have the patent issues of h.264, and it's more efficient.

**Comment by goldensun87** [comment]
@dstftw I don't think it is a good idea to directly admit to Youtube, that I am saving videos off their site with third party software.  That is why I asked here.

@Hrxn Thanks for the info.  I wouldn't have a problem with it, if the variable framerate was not persistent.  When an h.264 video from Youtube or anywhere else has a variable framerate, demuxing and remuxing the video gets rid of the VFR, but that does not seem to work with the VP9 video.
