### ISSUE TITLE
Equivalent of --get-url for subtitles?

### ISSUE THREAD

**Issue by lixoof** [rg3/youtube-dl#12110]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.11**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

I want to print URL for the subtitle file, so after reading README I tried this:

`youtube-dl --get-url --sub-format "srt" "http://example.com"`

however, this does not work and will only print the video URL. I able to see part of the subtitle URL by doing this:

`youtube-dl --skip-download --print-traffic --write-sub --sub-format "srt" "http://example.com"`

but that will also download the subtitles and generates alot of ouput. I only want a single line with the full URL.

What is the equivalent of this:

`youtube-dl --get-url "http://example.com"`

just for printing the subtitle URL?

**Comment by dstftw** [comment]
No such equivalent. Use `--dump-json`.
