### ISSUE TITLE
Error downloading Facebook video

### ISSUE THREAD

**Issue by girlsapink** [rg3/youtube-dl#12128]
If you try to download Facebook 1080p video, 720p video will be downloaded.
Do you have a solution?

**Comment by yan12125** [comment]
Could you give an example?

**Comment by girlsapink** [comment]
Youtube-dl.exe opens up a command prompt window in Windows and puts youtube-dl.exe 
https://www.facebook.com/nenechicken4479/videos/1221259967995415/ into the workspace. It will be downloaded as 720 images.
http://imgur.com/3zoUjLD
http://imgur.com/rRfMhRj

**Comment by yan12125** [comment]
See discussion on #11073

**Comment by girlsapink** [comment]
--username (name) --password (pass) url
I followed the instructions above, but the result is 720. Facebook supports 1080 itself, but I log in, but the download is the same

**Comment by girlsapink** [comment]
warning: unnable to log in: bad username/password, or exceeded login rate limit (~2/min). check credenntials or wait.

**Comment by girlsapink** [comment]
The ID password is correct, but the same problem still occurs.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
