### ISSUE TITLE
Bug: crunchyroll [--write-description]

### ISSUE THREAD

**Issue by BridgeUK** [rg3/youtube-dl#12124]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.14**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

---

- Single video: http://www.crunchyroll.com/11eyes/episode-1-piros-jszaka-red-night-535080
- Single video: http://www.crunchyroll.com/91-days/episode-5-blood-will-have-blood-715661

---

- Description of issue

When using the --write-description command for a crunchyroll video, if in the description quotation marks are used it breaks the description file by ending it early with a back slash.

Edit: I've added a second example of the break in description when the quotation marks are used.

**Comment by yan12125** [comment]
Thanks for the report. Descriptions with quotes will be correctly extracted in the next version.

**Comment by BridgeUK** [comment]
Many Thanks
