### ISSUE TITLE
Fix clone instructions in README.md: use https instead of ssh

### ISSUE THREAD

**Issue by trson** [rg3/youtube-dl#12125]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

In step 2. of the "Adding support for a new site" section of README.md, the suggested command line for cloning the newly forked repository fails with the current default configuration of github repositories:

    git clone git@github.com:YOUR_GITHUB_USERNAME/youtube-dl.git

I get the error:

    Permission denied (publickey).
    fatal: Could not read from remote repository.

One should clone the repo using https instead:

    git clone https://github.com/YOUR_GITHUB_USERNAME/youtube-dl.git

**Comment by yan12125** [comment]
In the section "Adding support for a new site", it's assumed that people comes here for writing codes and open pull requests. To do that you need a working Github account. If you got permission denied, there's something wrong in your github account settings.
