### ISSUE TITLE
amc.com ERROR: Unable to extract theplatform_path

### ISSUE THREAD

**Issue by dwaderich** [rg3/youtube-dl#12127]
C:\temp>youtube-dl.exe -F "http://www.amc.com/shows/the-walking-dead/full-episodes/season-07/episode-09/rock-in-the-road"
[AMCNetworks] rock-in-the-road: Downloading webpage
ERROR: Unable to extract theplatform_path; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\temp>youtube-dl.exe -F "http://www.amc.com/shows/the-walking-dead/full-episodes/season-07/episode-09/rock-in-the-road" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'http://www.amc.com/shows/the-walking-dead/full-episodes/season-07/episode-09/rock-in-the-road', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.14
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-71320-gc4b2017, ffprobe N-80912-gce466d0
[debug] Proxy map: {}
[AMCNetworks] rock-in-the-road: Downloading webpage
ERROR: Unable to extract theplatform_path; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\extractor\amcnetworks.py", line 58, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\extractor\common.py", line 672, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract theplatform_path; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dare2** [comment]
Same for me on a different show:

C:\files>youtube-dl -F http://www.amc.com/shows/humans/full-episodes/season-02/episode-01/201-2 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'http://www.amc.com/shows/humans/full-episodes/season-02/episode-01/201-2', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.10
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81707-g11777eb, ffprobe N-81707-g11777eb, rtmpdump 2.4
[debug] Proxy map: {}
[AMCNetworks] 201-2: Downloading webpage
ERROR: Unable to extract theplatform_path; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\extractor\common.py", line 359, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\extractor\amcnetworks.py", line 58, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\extractor\common.py", line 662, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract theplatform_path; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dwaderich** [comment]
how do i get a windows exe with the modified code?

**Comment by dare2** [comment]
youtube-dl -U

will update to the latest version

**Comment by dwaderich** [comment]
latest version available is 2.14.2017, but this code was modified on 2.15.2017

**Comment by yan12125** [comment]
> how do i get a windows exe with the modified code?

Before a new release arrives, you can clone this repo and run ```python setup.py py2exe```.

**Comment by dare2** [comment]
The new release is now available. I just updated to 2017.02.16

**Comment by dwaderich** [comment]
thanks all for resolving the issue

**Comment by tchawes** [comment]
Is it possible to adjust the extractor to support wetv.com?  It is an AMC network.

**Comment by dstftw** [comment]
wetv is already supported.

**Comment by tchawes** [comment]
@dstftw 

`youtube-dl http://www.wetv.com/shows/mama-june-from-not-to-hot/full-episode/season-01/thin-tervention --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.wetv.com/shows/mama-june-from-not-to-hot/full-episode/season-01/thin-tervention', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-81489-ga37e6dd, ffprobe N-81489-ga37e6dd
[debug] Proxy map: {}
[generic] thin-tervention: Requesting header
WARNING: Falling back on generic information extractor.
[generic] thin-tervention: Downloading webpage
[generic] thin-tervention: Extracting information
[download] Downloading playlist: Thin-Tervention
[generic] playlist Thin-Tervention: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[ThePlatform] tv4KquQXTO41: Downloading SMIL data
[ThePlatform] tv4KquQXTO41: Checking video URL
[ThePlatform] tv4KquQXTO41: video URL is invalid, skipping
[ThePlatform] tv4KquQXTO41: Checking video URL
[ThePlatform] tv4KquQXTO41: video URL is invalid, skipping
[ThePlatform] tv4KquQXTO41: Checking video URL
[ThePlatform] tv4KquQXTO41: video URL is invalid, skipping
[ThePlatform] tv4KquQXTO41: Checking video URL
[ThePlatform] tv4KquQXTO41: video URL is invalid, skipping
[ThePlatform] tv4KquQXTO41: Checking video URL
[ThePlatform] tv4KquQXTO41: video URL is invalid, skipping
[ThePlatform] tv4KquQXTO41: Checking video URL
[ThePlatform] tv4KquQXTO41: video URL is invalid, skipping
[ThePlatform] tv4KquQXTO41: Checking video URL
[ThePlatform] tv4KquQXTO41: video URL is invalid, skipping
[ThePlatform] tv4KquQXTO41: Checking video URL
[ThePlatform] tv4KquQXTO41: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\extractor\theplatform.py", line 277, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\extractor\common.py", line 1023, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
