### ISSUE TITLE
How to autoplay file after download?

### ISSUE THREAD

**Issue by rhazor** [rg3/youtube-dl#12134]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

How do you auto play the downloaded file? E.g. `youtube-dl youtube.com=asdasdas video_player`

I did read docu in `-h`

Video players VLC or MPC-HC.

**Comment by dstftw** [comment]
Use `--exec` option.
