### ISSUE TITLE
[8bodiesmovie.com] Site Support

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#12137]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.14**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### Purpose
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs http://www.8bodiesmovie.com/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', 'http://www.8bodiesmovie.com/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.14
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[generic] www.8bodiesmovie: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.8bodiesmovie: Downloading webpage
[generic] www.8bodiesmovie: Extracting information
ERROR: Unsupported URL: http://www.8bodiesmovie.com/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\extractor\generic.py", line 2579, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.8bodiesmovie.com/
...
<end of log>
```

---
- Single video: http://www.8bodiesmovie.com/

---

### Description of your my issue.
The site has a short movie available until 10pm PST, I wonder if you can support site so I can download it.

**Comment by gkoelln** [comment]
https://vod-meta.wix.com/secure-files/68080d725fde423c8b6501311c4e6a62.mp4?secure_data=c2F2ZV9hc19uYW1lPTglMjBCT0RJRVMlMjBGRUIxMS5tcDQmbm9uY2U9ZGZjZDE0ZWY2NzFjJmV4cGlyYXRpb25fdHM9MTQ4NzE0ODEyNCZmaWxlX3VybD0vMjYzY2E5Y2YtZGM2NC00OTZiLTgzOGYtY2JlZGEzZmMzMDcwL3ZpZGVvLzY4MDgwZDcyNWZkZTQyM2M4YjY1MDEzMTFjNGU2YTYyLzEwODBwL21wNC9maWxlLm1wNCZidWNrZXQ9dmlkZW8ud2l4c3RhdGljLmNvbQ==&secure_sig=05269d5245bd8df91e015733cb47db16d1c70726

**Comment by RuneMagle** [comment]
youtube-dl won't download:
`C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs https://vod-meta.wix.com/secure-files/68080d725fde423c8b6501311c4e6a62.mp4?secure_data=c2F2ZV9hc19uYW1lPTglMjBCT0RJRVMlMjBGRUIxMS5tcDQmbm9uY2U9ZGZjZDE0ZWY2NzFjJmV4cGlyYXRpb25fdHM9MTQ4NzE0ODEyNCZmaWxlX3VybD0vMjYzY2E5Y2YtZGM2NC00OTZiLTgzOGYtY2JlZGEzZmMzMDcwL3ZpZGVvLzY4MDgwZDcyNWZkZTQyM2M4YjY1MDEzMTFjNGU2YTYyLzEwODBwL21wNC9maWxlLm1wNCZidWNrZXQ9dmlkZW8ud2l4c3RhdGljLmNvbQ==&secure_sig=05269d5245bd8df91e015733cb47db16d1c70726 -v
[generic] 68080d725fde423c8b6501311c4e6a62: Requesting header
WARNING: Could not send HEAD request to https://vod-meta.wix.com/secure-files/68080d725fde423c8b6501311c4e6a62.mp4?secure_data=c2F2ZV9hc19uYW1lPTglMjBCT0RJRVMlMjBGRUIxMS5tcDQmbm9uY2U9ZGZjZDE0ZWY2NzFjJmV4cGlyYXRpb25fdHM9MTQ4NzE0ODEyNCZmaWxlX3VybD0vMjYzY2E5Y2YtZGM2NC00OTZiLTgzOGYtY2JlZGEzZmMzMDcwL3ZpZGVvLzY4MDgwZDcyNWZkZTQyM2M4YjY1MDEzMTFjNGU2YTYyLzEwODBwL21wNC9maWxlLm1wNCZidWNrZXQ9dmlkZW8ud2l4c3RhdGljLmNvbQ==: HTTP Error 405: Method Not Allowed
[generic] 68080d725fde423c8b6501311c4e6a62: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'secure_sig' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by gkoelln** [comment]
Put it in the browser.

**Comment by RuneMagle** [comment]
But I don't think if I put it in the browser that I will get the highest quality.

**Comment by gkoelln** [comment]
Trust me--it's 1080p.

**Comment by RuneMagle** [comment]
I downloaded it. Its 1920x818

Which is not 1080p.

**Comment by RuneMagle** [comment]
But only close.

**Comment by gkoelln** [comment]
Well, yeah, because of the aspect ratio, but it's the highest quality file available.  If you view the source for this: https://vod.wix.com/public/play/47059628-674fccd9b5b84c2aa81051da4183756e?instance=VQ1KXM84Hq6RpS3EXksmVYsXj-adDsMOsk8x_s4MCcU.eyJpbnN0YW5jZUlkIjoiYzc4NjdhNDktM2MyZS00MTgzLTg4N2ItMTMwNmVmNzU3ZDM4Iiwic2lnbkRhdGUiOiIyMDE3LTAyLTE0VDIyOjQxOjUxLjUxMloiLCJ1aWQiOm51bGwsImlwQW5kUG9ydCI6IjEwOC4xNjEuMC4yNDIvNTU1MzYiLCJ2ZW5kb3JQcm9kdWN0SWQiOm51bGwsImRlbW9Nb2RlIjpmYWxzZSwiYWlkIjoiMDg5MGM5MmItY2E5My00MzlkLWI4NzEtNmVlN2M4ZTFlZDMxIiwiYmlUb2tlbiI6ImQ4NzAxYzI1LTM2MmQtMGI3Zi0xMWIxLTAyZGVjNWEwODAzMiIsInNpdGVPd25lcklkIjoiMjYzY2E5Y2YtZGM2NC00OTZiLTgzOGYtY2JlZGEzZmMzMDcwIn0 you'll see the options.

**Comment by RuneMagle** [comment]
Ok. Thanks!

How did you get this link? Because I could only find it by playing the movie on my iPhone. But I couldn't copy it.

**Comment by gkoelln** [comment]
I just followed the http traffic until I could find it.

**Comment by RuneMagle** [comment]
Ok. I'll close this issue.
