### ISSUE TITLE
New option --crunchyroll-session-id which allows the user to specify a specific API session ID

### ISSUE THREAD

**Issue by starchivore** [rg3/youtube-dl#12130]
Reference:
[Option to set crunchyroll session ID](https://github.com/streamlink/streamlink/pull/535)
[Support providing a custom Crunchyroll session ID](https://github.com/streamlink/streamlink/issues/505)

Link to 32-digit **session ID** for [crunchyroll.com](http://www.crunchyroll.com):
[https://cr.onestay.moe/getId](https://cr.onestay.moe/getId)
[https://github.com/Onestay/CR-Unblocker/blob/master/extension/background_script.js](https://github.com/Onestay/CR-Unblocker/blob/master/extension/background_script.js)
[https://chrome.google.com/webstore/detail/cr-unblocker/agapeeilkibacbfeijlidlgppmjaaijn](https://chrome.google.com/webstore/detail/cr-unblocker/agapeeilkibacbfeijlidlgppmjaaijn)

Link to crunchyroll.py with **"session_id"** implemented successfully:
[https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/crunchyroll.py](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/crunchyroll.py)

Since they already got that working and both of you are writing codes in Python, it should be a piece of cake to add an option **--crunchyroll-session-id** for [crunchyroll.py](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/crunchyroll.py) and thanks a lot!

**Comment by dstftw** [comment]
youtube-dl does not use crunchyroll APIs.

**Comment by Atemu** [comment]
Sorry for necrobumping but wouldn't it be possible to implement this feature using cookies instead of the API?

Onestay's [CR-Unblocker](https://github.com/onestay/CR-Unblocker) plugin does it this way.
