### ISSUE TITLE
how to know before downloading whether the moov atom is at the beginning or end

### ISSUE THREAD

**Issue by sant527** [rg3/youtube-dl#12143]
example link:  "http://video.nationalgeographic.com/video/greenhouse-what-counts-env?gc=%2Fvideo%2Fenvironment%2Fenergy" 

`youtube-dl "http://video.nationalgeographic.com/video/greenhouse-what-counts-env?gc=%2Fvideo%2Fenvironment%2Fenergy" `

How to know the whether the moov atom exist  beginning or end of file.

Here the file is small. But in somecase  the videos are 30MB+. I have to wait till the entire video is downloaded.

If i know the what type of file  w.r.t moov atom then i can decide whether to download or not

**Comment by yan12125** [comment]
> how to know before downloading

Impossible. You can check whether moov is already there after the download just starts.

**Comment by sant527** [comment]
how to check that

**Comment by yan12125** [comment]
IIRC ffprobe will report an error is moov is missing

**Comment by sant527** [comment]
Ok.
