### ISSUE TITLE
slect format: video only with width < 600

### ISSUE THREAD

**Issue by sant527** [rg3/youtube-dl#12145]
In youtube-dl: I am using -f '[width<=600]' 

it selects formats with width <= 600 having both audio and video

If the format is video only then its not selecting.

I am fine if it selects video only format or video+audio format. I am more concerned about the width

how to select any format with width <= 600

**Comment by dstftw** [comment]
Read [FAQ](https://github.com/rg3/youtube-dl#format-selection-examples).

**Comment by bezdupel** [comment]
`-f 'bestvideo[width<=?600]+bestaudio/best'`

**Comment by sant527** [comment]
working
