### ISSUE TITLE
[Request] - A --reject-uploader for youtube.com

### ISSUE THREAD

**Issue by Piokaz** [rg3/youtube-dl#12142]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.14**

- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)

---

Didn't see this anywhere in the issues.
Possible to have a param to exclude some uploaders from youtube.com,  like the --reject-title one ?

Thanks.

**Comment by ThomasChr** [comment]
Parameters added. See PR #12144

**Comment by yan12125** [comment]
This should work:
```
youtube-dl --match-filter "uploader != (uploader name)"
```

**Comment by Piokaz** [comment]
@ThomasChr Thank you, that was fast !

@yan12125 Doesn't work.

Already tried it before this request, from the docs, comparisons with match-filter (<,>,=, != etc..) only work with numbers, so with likes, dislikes, duration (and probably others vars with numbers).

**Comment by dstftw** [comment]
`--match-filter` works just fine for that. Since db13c16ef8968613680e2bbc85f373c3e74faf98 it's also possible to use string literals in quotes, e.g. if you need to match string with spaces: `--match-filter "uploader = 'some string' & duration > 30"`.
