### ISSUE TITLE
Bug: [--batch-file] breaks for crunchyroll on preview clip

### ISSUE THREAD

**Issue by BridgeUK** [rg3/youtube-dl#12156]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.16**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

---
- Playlist #1: http://www.crunchyroll.com/akibas-trip-the-animation
- Playlist #2: http://www.crunchyroll.com/alderamin-on-the-sky
---

### Description of your *issue*, suggested solution and other information

If you have multiple playlists (links above) inside a text file for a batch download, and a playlist (#1 above) has a preview clip (which is only available to premium members until it's released about a week later to everyone else) instead of youtube-dl continuing to download the next playlist (#2 above) the batch download process breaks with the following error message...

"ERROR: This is a sample clip. To watch the full video, start a free trial today!
; please report this issue on https://yt-dl.org/bug . Make sure you are using th
e latest version"

It's my understanding youtube-dl should skip the preview clip and move on to the next playlist.

**Comment by dstftw** [comment]
This is intentional. Use `-i`.

**Comment by BridgeUK** [comment]
thank you.
