### ISSUE TITLE
[pornhub] Extract all formats

### ISSUE THREAD

**Issue by dstftw** [rg3/youtube-dl#12166]
Currently, only best is extracted:
```
> py -3.6 .\youtube_dl\__main__.py http://www.pornhub.com/view_video.php?viewkey=648719015 -F
[PornHub] 648719015: Downloading webpage
[PornHub] 648719015: Downloading webpage
[info] Available formats for 648719015:
format code  extension  resolution note
0            mp4        unknown
```

**Comment by sebma** [comment]
Hi,
I'm not sure you should tag this as a "Request" because pornhub has been in the list of supported sites for a long time now : https://rg3.github.io/youtube-dl/supportedsites.html

Maybe you should tag this issue as a bug report instead, don't you agree ?
