### ISSUE TITLE
warning unable to extract uploader nickname on simple output template

### ISSUE THREAD

**Issue by Pivion** [rg3/youtube-dl#12164]
Bug-- 

batch script--
call youtube-dl.exe -v -o "temp\vid\%%(title)s.%%(ext)s"  https://www.youtube.com/watch?v=hS5CfP8n_js

problem-- 
output file name i get is: (ext)s
if i don't use -v option i get: "warning unable to extract uploader nickname"

verbose--
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', 'temp\\vid\\(ext)s', 'https://www.youtube.com/watch?v=hS5CfP8n_js']
[debug] Encodings: locale cp1257, fs mbcs, out cp775, pref cp1257
[debug] youtube-dl version 2017.02.16
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] hS5CfP8n_js: Downloading webpage
[youtube] hS5CfP8n_js: Downloading video info webpage
[youtube] hS5CfP8n_js: Extracting video information
[youtube] {22} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {43} signature length 42.40, html5 player en_US-vflg9Wu9U
[youtube] {18} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {36} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {17} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {137} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {248} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {136} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {247} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {135} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {244} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {134} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {243} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {133} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {242} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {160} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {278} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {140} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[youtube] {171} signature length 82.1.0, html5 player en_US-vflg9Wu9U
[debug] Invoking downloader on 'https://r3---sn-agujoxufvg3-8ove.googlevideo.com/videoplayback?initcwndbps=897500&ratebypass=yes&pl=17&requiressl=yes&key=yt6&ip=89.116.94.73&ipbits=0&ei=L-qmWLC6HNfBdfigqZAJ&id=o-AGwfzbEt-FvDwClMeq6iKermpckggoxXLv0JEbb8PSpz&upn=r_vWyNnysOs&mm=31&mn=sn-agujoxufvg3-8ove&dur=55.681&mt=1487333724&mv=m&ms=au&lmt=1472328189356236&mime=video%2Fmp4&source=youtube&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&itag=22&expire=1487355535&signature=5EC5B7E3A3821AE06EEC6D1198F6B6D823347C6A.3D1C70646A41478880DD2AF80541C7751408AD84'
[download] Destination: temp\vid\(ext)s
[download] 100% of 7.22MiB in 00:25

**Comment by dstftw** [comment]
Do not use call or double percents one more time.
