### ISSUE TITLE
vid.me support broken (again)

### ISSUE THREAD

**Issue by 4trdg** [rg3/youtube-dl#12161]
#### Steps to reproduce:
- Go to https://vid.me/
- Copy the URL of any of the videos on the home page
- Try downloading via the latest version of youtube-dl

_Vidme is included in the list of [supported sites](https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md)_

**Comment by dstftw** [comment]
Works fine:
```
PS C:\dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py https://vid.me/oQkO
[vidme] oQkO: Downloading JSON metadata
[download] Destination: switch OS-oQkO.mp4
[download]   0.4% of 128.87MiB at  1.19MiB/s ETA 01:48
ERROR: Interrupted by user
```
