### ISSUE TITLE
Afreecatv has failed

### ISSUE THREAD

**Issue by ivanda** [rg3/youtube-dl#12179]
C:\Users\wd\AppData\Local\Programs\Python\Python35-32\python.exe C:/Users/wd/Desktop/youtube-dl-master/youtube_dl/__main__.py http://vod.afreecatv.com/PLAYER/STATION/18650793
[afreecatv] 18650793: Downloading XML
ERROR: Specified AfreecaTV video does not exist

Process finished with exit code 1

**Comment by mcerdeira** [comment]
Seems like it is expecting the video url in the path "track/video/file" from the downloaded xml, but it is does not exists.
This is the XML it parses and gets now:
[link xml](http://afbbs.afreecatv.com:8080/api/video/get_video_info.php?nTitleNo=18650793)
[get_video_info.php.xml.zip](https://github.com/rg3/youtube-dl/files/786082/get_video_info.php.xml.zip)

If I have to guess, the xml has changed and now the link is here:

`<video duration="107">rtmp://flv10.afreecatv.com/afflv10/mp4:AFFLV/00/7/29/10_00_1487406867466338_2147483647.mp4`

**Comment by mcerdeira** [comment]
Maybe, some hack like the one I did on my own repository?
[https://github.com/mcerdeira/youtube-dl/commit/3bc24cffea944ea3a15a6aa3697dfa85d5c4165a](https://github.com/mcerdeira/youtube-dl/commit/3bc24cffea944ea3a15a6aa3697dfa85d5c4165a)

**Comment by ivanda** [comment]
Yeah , you are right .

Right xml:
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Contents>
<track>
<bj_id>tjdbs0274</bj_id>
<nickname>
<![CDATA[ 새벽러임 ]]>
</nickname>
<flag>SUCCEED</flag>
<logo>
http://stimg.afreecatv.com/LOGO/tj/tjdbs0274/tjdbs0274.jpg
</logo>
<title>
<![CDATA[ 공부 ]]>
</title>
<duration>149</duration>
<titleImage>
http://videoimg.afreecatv.com/php/SnapshotLoad.php?rowKey=20170218_F8599C69_188956549_1_r
</titleImage>
<video type="realmedia" playCount="1" category="00210000">
http://ad.afreecatv.com/RealMedia/ads/adstream_sx.ads/www.afreeca.com/VOD_21c@x67
</video>
<video chat="true" thumbnail="true" partition="true" partitionSize="60">
<log>
http://afbbs.afreecatv.com:8080/api/video/set_video_log.php
</log>
<file duration="149" key="20170218_F8599C69_188956549_1">
http://222.122.117.204/mvod/20170218/549/F8599C69_188956549_1.mp4
</file>
</video>
<overlay_advert>false</overlay_advert>
</track>
<share>
<link>http://vod.afreecatv.com/PLAYER/STATION/18650795</link>
<iframe>
<![CDATA[
<iframe width="0" height="0" src="http://www.afreecatv.com/player/player.html?nTitleNo=18650795" frameborder="0" allowfullscreen="true"></iframe>
]]>
</iframe>
</share>
</Contents>`

Faild Xml:
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Contents>
<track>
<bj_id>badkids</bj_id>
<nickname>
<![CDATA[ 윈아디 ]]>
</nickname>
<flag>SUCCEED</flag>
<logo>
http://stimg.afreecatv.com/LOGO/ba/badkids/badkids.jpg
</logo>
<title>
<![CDATA[ 오늘은 다르다! 쏘님의 우월한 위아래~ 댄스리액션! ]]>
</title>
<duration>107</duration>
<titleImage>
http://iflv10.afreecatv.com/AFFLV/00/7/29/10_00_1487406867466338_2147483647.jpg
</titleImage>
<video type="realmedia" playCount="1" category="00080000">
http://ad.afreecatv.com/RealMedia/ads/adstream_sx.ads/www.afreeca.com/VOD_8c@x67
</video>
<video duration="107">
rtmp://flv10.afreecatv.com/afflv10/mp4:AFFLV/00/7/29/10_00_1487406867466338_2147483647.mp4
<log>
http://afbbs.afreecatv.com:8080/api/video/set_video_log.php
</log>
</video>
<overlay_advert>false</overlay_advert>
</track>
<share>
<link>http://vod.afreecatv.com/PLAYER/STATION/18650793</link>
<iframe>
<![CDATA[
<iframe width="0" height="0" src="http://www.afreecatv.com/player/player.html?nTitleNo=18650793" frameborder="0" allowfullscreen="true"></iframe>
]]>
</iframe>
</share>
</Contents>`

However,there are a lot of faild xml files.

**Comment by mcerdeira** [comment]
Yeah, I don´t know if the xml is failed, seems to be just another format... may be this is silly to ask but: is there any specification from afreecatv?

**Comment by ivanda** [comment]
Sorry,i don't know.I test a few urls .There are just two xml styles above .One is rtmp video ,i can not download this video by youtube-dl.

**Comment by mcerdeira** [comment]
Ok, so I think that we need to test for method 1, and then, if the tag is not present, go for method 2, similar to my proposed fix here using a flag (or not): [https://gist.github.com/mcerdeira/cf83dedf6ba553b5e34ad5b5e8371f31#file-gistfile1-py-L115](https://gist.github.com/mcerdeira/cf83dedf6ba553b5e34ad5b5e8371f31#file-gistfile1-py-L115)
```
        if xpath_element(video_xml, './track/video/file') is None:
            method_b = True
            #raise ExtractorError('Specified AfreecaTV video does not exist',
#                     expected=True)
```

**Comment by yan12125** [comment]
Sorry for being late. I've pushed the fix to master. Thanks for identifying and diagnosing the problem, @mcerdeira and @ivanda! The fix will be included in the next version.
