### ISSUE TITLE
Unsupported URL - Einthusan (New Issue)

### ISSUE THREAD

**Issue by ramshakhar** [rg3/youtube-dl#12174]
Hi,

While downloading movies from einthusan:

The following link got downloaded without any problem:
"https://einthusan.tv/movie/watch/2918/?lang=tamil"

But when adding this link:
"https://einthusan.tv/movie/watch/xVWB/?lang=tamil"

I got unsupported URL error.

I guess the issue is after "watch/" it has text instead of number.

Please suggest a fix.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by ramshakhar** [comment]
Fixed. My previous version was 2017.2.16. Just upgraded to 2017.2.17.
