### ISSUE TITLE
[miomio] Video URLs treated as empty playlists, resulting in no download

### ISSUE THREAD

**Issue by SamuSoft** [rg3/youtube-dl#12170]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --verbose http://www.miomio.tv/watch/cc309625/
[debug] System config: [u'-o', u'~/Movies/%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.miomio.tv/watch/cc309625/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.16
[debug] Python version 2.7.13 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[miomio.tv] 309625: Downloading webpage
[miomio.tv] 309625: Downloading player webpage
[download] Downloading playlist: 秘密のケンミンSHOW打倒香川 新うどん王国福岡県 セクシー山形弁講座 20170209
[miomio.tv] playlist 秘密のケンミンSHOW打倒香川 新うどん王国福岡県 セクシー山形弁講座 20170209: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: 秘密のケンミンSHOW打倒香川 新うどん王国福岡県 セクシー山形弁講座 20170209
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

The link is identified wrongfully as an empty playlist, resulting in a Finished announcement but no downloaded files

**Comment by yan12125** [comment]
Working fine here:
```
$ youtube-dl -v "http://www.miomio.tv/watch/cc309625/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.miomio.tv/watch/cc309625/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.17
[debug] Git HEAD: 70bcc444a
[debug] Python version 3.6.0 - Linux-4.9.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[miomio.tv] 309625: Downloading webpage
[miomio.tv] 309625: Downloading player webpage
[debug] Invoking downloader on 'http://mtv-kj.aplmm.com/A461DF4C90412017B0F010AFBB0C02145866170209MTQ4NzQxMDQ1OTUwODg4MjY0MTQ1OD14586614874104560044A9C899B05C6E.ic'
[download] Destination: 秘密のケンミンSHOW打倒香川 新うどん王国福岡県 セクシー山形弁講座 20170209-309625.mp4
[download]   0.9% of 380.35MiB at 74.83KiB/s ETA 01:26:00^CException ignored in: <_io.FileIO name='秘密のケンミンSHOW打倒香川 新うどん王国福岡県 セクシー山形弁講座 20170209-309625.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='秘密のケンミンSHOW打倒香川 新うどん王国福岡県 セクシー山形弁講座 20170209-309625.mp4.part'>

ERROR: Interrupted by user
```
Could you run ```youtube-dl -v "http://www.miomio.tv/watch/cc309625/" --write-pages``` and upload all *.dump files?

**Comment by SamuSoft** [comment]
When redone now there is another result, with the invoking of the downloader failing. 

(
The requested *.dump files are also zipped and attached here: 
[dumpfiles[miomio].zip](https://github.com/rg3/youtube-dl/files/785325/dumpfiles.miomio.zip)
)

In your case **mtv-kj.aplmm.com** is used, but mine is invoked on **hdus.qqfire.com/** and subsequently failing. Here is what mine shows right now:

```
youtube-dl -v http://www.miomio.tv/watch/cc309625/
[debug] System config: [u'-o', u'~/Movies/%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.miomio.tv/watch/cc309625/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.16
[debug] Python version 2.7.13 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[miomio.tv] 309625: Downloading webpage
[miomio.tv] 309625: Downloading player webpage
[debug] Invoking downloader on u'http://hdus.qqfire.com/70C2ED38AE832017328A93B94BB502144375170209MTQ4NzQ1MTQ0OTUwODg4MjY0MTQ0Mz144375148745144200448949A091029D.ic'
ERROR: unable to download video data: <urlopen error [Errno 60] Operation timed out>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1704, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1646, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2006, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 896, in http_open
    req)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 60] Operation timed out>
```

**Comment by yan12125** [comment]
I got timeout today, too. On Firefox this video leads to a ```hdus.qqfire.com``` URL, too, so there's no video even in browsers today. Apparently miomio.tv is quite unstable.

**Comment by R0GGER** [comment]
I didn't had this problem too... Untill I did a clean install from a docker container. It has the same issues with youtube playlists.

**Comment by yan12125** [comment]
As it's a server-side issue, I'll close it first. Feel free to leave comments here if things are changed.
