### ISSUE TITLE
Add support for toongoggles.com

### ISSUE THREAD

**Issue by PannenkoekenNL** [rg3/youtube-dl#12171]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.17**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Site support request (request for adding support for a new site)

### Description of your *issue*, suggested solution and other information

Please add support for toongoggles.com. Example URL: http://www.toongoggles.com/shows/936/origami-warriors/episodes/961/unfold-the-power

**Comment by mcerdeira** [comment]
From a really quick analysis, video url seems to be here:
```
<video class="persistentNativePlayer nativeEmbedPlayerPid" 
poster="data:image/png,%89PNG%0D%0A%1A%0A%00%00%00%0DIHDR%00%00%00%01%00%00%00%01%08%02%00%00%00%90wS%DE%00%00%00%01sRGB%00%AE%CE%1C%E9%00%00%00%09pHYs%00%00%0B%13%00%00%0B%13%01%00%9A%9C%18%00%00%00%07tIME%07%DB%0B%0A%17%041%80%9B%E7%F2%00%00%00%19tEXtComment%00Created%20with%20GIMPW%81%0E%17%00%00%00%0CIDAT%08%D7c%60%60%60%00%00%00%04%00%01'4'%0A%00%00%00%00IEND%AEB%60%82" 
id="pid_player-0_5uylzcw8" kentryid="0_5uylzcw8" kuiconfid="25723481" kwidgetid="_513551" kpartnerid="513551" 
preload="auto" style="position: absolute; left: 0px; top: 0px;" 
src="http://cdnapi.kaltura.com/p/513551/sp/51355100/playManifest/entryId/0_5uylzcw8/flavorId/1_m8n6mh8d/format/url/protocol/http/a.mp4?ks=NWRiZmIyODcwZTIzOGJiMzBhNzMwMDZkZDc4OTBmZTM5ZDI1NTkxOXw1MTM1NTE7NTEzNTUxOzE0ODc2ODE0ODY7MDsxNDg3NTk1MDg2LjU4MDQ7MDt2aWV3Oiosd2lkZ2V0OjE7Ow==&amp;referrer=aHR0cDovL3d3dy50b29uZ29nZ2xlcy5jb20=&amp;clientTag=html5:v2.16&amp;playSessionId=22ae0e19-9ac2-1439-7a07-fa7b16dc6558&amp;uiConfId=25723481" x-webkit-airplay="allow" width="926" height="521"></video>
```

**Comment by yan12125** [comment]
Yep that's a kaltura embedded video: http://cdnapi.kaltura.com/html5/html5lib/v2.16/mwEmbedFrame.php?&wid=_513551&uiconf_id=25723481&entry_id=0_5uylzcw8&flashvars[externalInterfaceDisabled]=false&flashvars[autoPlay]=true&playerId=player-0_5uylzcw8&forceMobileHTML5=true&urid=2.16&callback=mwi_player05uylzcw80
