### ISSUE TITLE
 ERROR: unable to open for writing: [Errno 13] Permission denied (UBUNTU)

### ISSUE THREAD

**Issue by JackieApkon** [rg3/youtube-dl#12184]
I'm sorry my english, is not native language.

I to be with a problem after of finish all process of install.
When goes execute the code, this error occur:

Error Output: ================ ERROR: unable to open for writing: [Errno 13] Permission denied: "Video File...." in /home/.../vendor/symfony/process/Process.php:233 Stack trace: #0 /home/.../vendor/norkunas/youtube-dl-php/src/YoutubeDl.php(102): Symfony\Component\Process\Process->mustRun(Object(Closure)) #1 /var/.../youtube-dl/index.php(25): YoutubeDl\YoutubeDl->download('https://www.you...') #2 {main}

Please, help. What going on? :/

**Comment by dstftw** [comment]
Ask the authors of youtube-dl-php.

**Comment by rafayexalter** [comment]
@JackieApkon did you find the solution?
