### ISSUE TITLE
qq.com is not supported

### ISSUE THREAD

**Issue by oxygenbus** [rg3/youtube-dl#12187]
I thought the qq.com is supported but it is not:

youtube-dl -vv https://y.qq.com/portal/mv/v/g0022zctdxo.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vv', 'https://y.qq.com/portal/mv/v/g0022zctdxo.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.17
[debug] Python version 3.6.0 - Linux-3.2.61-grsec-modsign-x86_64-with-debian-wheezy-sid
[debug] exe versions: avconv 0.8.17-4, avprobe 0.8.17-4, ffmpeg 3.2.2-static, ffprobe 3.2.2-static
[debug] Proxy map: {}
[generic] g0022zctdxo: Requesting header
WARNING: Falling back on generic information extractor.
[generic] g0022zctdxo: Downloading webpage
[generic] g0022zctdxo: Extracting information
ERROR: Unsupported URL: https://y.qq.com/portal/mv/v/g0022zctdxo.html
Traceback (most recent call last):
  File "/home/colinz/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 696, in extract_info
    ie_result = ie.extract(url)
  File "/home/colinz/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 370, in extract
    return self._real_extract(url)
  File "/home/colinz/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 2604, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://y.qq.com/portal/mv/v/g0022zctdxo.html

**Comment by yan12125** [comment]
Only QQMusic is supported. Videos are not supported yet. See #6831 for previous discussions
