### ISSUE TITLE
Number Mask for season_number and episode_number

### ISSUE THREAD

**Issue by jaylweb** [rg3/youtube-dl#12189]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Please add the ability to provide an optional number mask for season_number and episode_number outputs.  For example, I would want "s1e1" to be "s01e01".  

This allows my files to line up in the correct order in my file system.  I also use Plex, which uses the naming convention "ShowName - sXXeYY - Optional_Info.ext" for TV shows, where XX is the season number and YY is the episode number.

**Comment by jaylweb** [comment]
I am sorry this is a duplicate.  I did search and did not find anything related.

**Comment by jaylweb** [comment]
Would you be able to show me which issue this is a duplicate of?  Maybe I am not searching the correct terms?

**Comment by dstftw** [comment]
#5185 #9966 #9978.
