### ISSUE TITLE
MP3 audio extraction - ERROR: Unsupported URL: https://www.youtube.com/

### ISSUE THREAD

**Issue by mdemori** [rg3/youtube-dl#12182]
Hi, 

thank you for this awesome tool!

When I try to download an MP3 directly i receive the unsupported URL error, please find below the command line and verbose log.

youtube-dl -v --extract-audio --audio-format mp3  https://www.youtube.com/watch?v=gq1s8vJb_qc

Result

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--extract-audio', '--audio-format=mp3', 'http                                        s://www.youtube.com/watch?v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.17
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-81947-gc45ba26, ffprobe N-81947-gc45ba26
[debug] Proxy map: {}
[generic] watch?v: Requesting header
[redirect] Following redirect to https://www.youtube.com/
[generic] www.youtube: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.youtube: Downloading webpage
[generic] www.youtube: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\bu                                        ild\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\bu                                        ild\youtube_dl\extractor\common.py", line 370, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\bu                                        ild\youtube_dl\extractor\generic.py", line 2604, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/

**Comment by dstftw** [comment]
You are passing an invalid URL https://www.youtube.com/watch?v.

**Comment by mdemori** [comment]
Thank you very much! just for future reference after you comment i realized that the problem lies on some strange behavior of windows cmd file parameters expansion, I've a little script that did something like this:

getfile.cmd:  youtube-dl --extract-audio --audio-format mp3 "%1"

and i use this command like:

getfile.cmd https://www.youtube.com/watch?v=gq1s8vJb_qc

when i use the command i don't realize that the %1 is expanded in a strange way and the url is truncated after = sign

if i use the same command from the normal shell everything work fine! thank you very much.. i will investigate more on this behavior
