### ISSUE TITLE
Fail to download with aria2c

### ISSUE THREAD

**Issue by Dimsok** [rg3/youtube-dl#12192]
Try to download with aria2c (v.1.31.0) as external downloader, but get:

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page
 for details.

ERROR: aria2c exited with code 1

Have tried without arguments and with them, The same result as was given above.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
