### ISSUE TITLE
404 Not Found when attempting to download a specific TVLand Impastor link. 

### ISSUE THREAD

**Issue by arcanez** [rg3/youtube-dl#12196]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.tvland.com/full-episodes/hbb3yo/impastor-buddy-s-prayer-season-2-ep-203', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.17
[debug] Python version 2.7.13 - Linux-4.9.0-15-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: avconv 3.2.4-1build1, avprobe 3.2.4-1build1, ffmpeg 3.2.4-1build1, ffprobe 3.2.4-1build1, rtmpdump 2.4
[debug] Proxy map: {}
[tvland.com] impastor-buddy-s-prayer-season-2-ep-203: Downloading webpage
[tvland.com] Downloading JSON metadata
[tvland.com] 08228fb2-6519-11e6-bfd4-0026b9414f30: Downloading info
[tvland.com] c3358e1b-30a7-4557-915e-90cbfae58ada: Extracting information
[tvland.com] c3358e1b-30a7-4557-915e-90cbfae58ada: Downloading video urls
[tvland.com] c3358e1b-30a7-4557-915e-90cbfae58ada: Downloading m3u8 information
[tvland.com] a51a99a2-518e-41cc-8969-4de83528c621: Extracting information
[tvland.com] a51a99a2-518e-41cc-8969-4de83528c621: Downloading video urls
[tvland.com] a51a99a2-518e-41cc-8969-4de83528c621: Downloading m3u8 information
[tvland.com] fda51402-1eaf-4507-a732-88efc503948f: Extracting information
[tvland.com] fda51402-1eaf-4507-a732-88efc503948f: Downloading video urls
[tvland.com] fda51402-1eaf-4507-a732-88efc503948f: Downloading m3u8 information
[tvland.com] 090a7f3b-7c8c-4382-9774-b55e8e93be24: Extracting information
[tvland.com] 090a7f3b-7c8c-4382-9774-b55e8e93be24: Downloading video urls
[tvland.com] 090a7f3b-7c8c-4382-9774-b55e8e93be24: Downloading m3u8 information
[tvland.com] b1c47876-26a4-4209-b6fb-35b58e9152ec: Extracting information
[tvland.com] b1c47876-26a4-4209-b6fb-35b58e9152ec: Downloading video urls
[tvland.com] b1c47876-26a4-4209-b6fb-35b58e9152ec: Downloading m3u8 information
[tvland.com] fcebe6d6-c0e9-48a5-b3b2-31b403f2db40: Extracting information
[tvland.com] fcebe6d6-c0e9-48a5-b3b2-31b403f2db40: Downloading video urls
[tvland.com] fcebe6d6-c0e9-48a5-b3b2-31b403f2db40: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 417, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2006, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

### Description of your *issue*, suggested solution and other information
youtube-dl encounters a 404 Not Found when attempting to download a specific TVLand Impastor link.

**Comment by mcerdeira** [comment]
Could this be related to Geo restrictions? (here from Argentina I can't watch the video from the site) Just a thought...

**Comment by arcanez** [comment]
the rest of the episodes work fine.

**Comment by gkoelln** [comment]
When I go through a browser, it prompts for sign in.  (Unfortunately, Dish isn't a valid provider, or I would test it.)

**Comment by arcanez** [comment]
@gkoelln it's just odd because I have no issues with the rest of the links.

**Comment by yan12125** [comment]
I got 404 in Firefox, even with a US proxy. @gkoelln @arcanez Maybe it's geo-restricted? Which country are you in?

**Comment by gkoelln** [comment]
I'm in the US and I'm now getting a 404 as well.  I guess the video was taken down.

**Comment by gkoelln** [comment]
Now it looks like only Season 1, Episodes 1-10 are available.

**Comment by yan12125** [comment]
Thanks for the feedback.

> the rest of the episodes work fine.

This issue can be closed as the problematic video is gone. If there's another video that works in browsers but not in youtube-dl, feel free to open new issues.
