### ISSUE TITLE
[dailymotion] "unable to extract comment count" warning

### ISSUE THREAD

**Issue by scfc** [rg3/youtube-dl#12209]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.21*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[tim@passepartout /tmp/tmp.yut8CyFERW]$ ./youtube-dl -v http://www.dailymotion.com/video/x5cnyfr
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.dailymotion.com/video/x5cnyfr']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.21
[debug] Python version 2.7.13 - Linux-4.9.9-200.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five
[debug] exe versions: ffmpeg 3.1.7, ffprobe 3.1.7, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] x5cnyfr: Downloading webpage
WARNING: unable to extract comment count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[dailymotion] x5cnyfr: Downloading m3u8 information
[dailymotion] x5cnyfr: Downloading m3u8 information
[dailymotion] x5cnyfr: Downloading m3u8 information
[dailymotion] x5cnyfr: Downloading m3u8 information
[dailymotion] x5cnyfr: Downloading m3u8 information
[dailymotion] x5cnyfr: Downloading m3u8 information
[dailymotion] x5cnyfr: Downloading m3u8 information
[debug] Invoking downloader on u'https://www.dailymotion.com/cdn/H264-1920x1080/video/x5cnyfr.mp4?auth=1487877568-2562-7l2uz9qg-63451a3fef7415ac564a60576bf5b36b'
[download] Resuming download at byte 56119163
[download] Destination: Air Crash Investigation - Killer Attitude (S17E01)-x5cnyfr.mp4
[download]   2.8% of 1.90GiB at  1.33MiB/s ETA 23:37^C
ERROR: Interrupted by user
[tim@passepartout /tmp/tmp.yut8CyFERW]$
```

---

### Description of your *issue*, suggested solution and other information

The `[dailymotion]` downloader warns: "unable to extract comment count".

**Comment by yan12125** [comment]
http://www.dailymotion.com/video/x5cnyfr has gone. Any new examples?

**Comment by scfc** [comment]
http://www.dailymotion.com/video/x2sq97f_air-disasters-mayday-munich-season-3-episode-2_tv?  IIRC this happens for all Dailymotion videos.
