### ISSUE TITLE
Add support for Linux Academy

### ISSUE THREAD

**Issue by vicenterusso** [rg3/youtube-dl#12207]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://linuxacademy.com/cp/courses/lesson/course/346/lesson/1/module/38
- Playlist: https://linuxacademy.com/cp/modules/view/id/38

**Comment by vicenterusso** [comment]
Should I sent to your gmail?

**Comment by helloguangxue** [comment]
Videos in Linux Academy are streaming videos. The videos are cutted into different segments and sent by AJAX. If youtube-dl could support this site, that would be awesome!!

**Comment by vicenterusso** [comment]
Ok, no answer? Where do I send my credentinals? o.O

**Comment by Dedsec1** [comment]
Hey @vicenterusso  i found an working downloader for Linux Academy enjoy https://pypi.python.org/pypi/linuxacademy-dl

**Comment by tempseptember** [comment]
Yes, tried it but it's failing on many courses. So, it would be be helpful if youtube-dl provides the support.

**Comment by tempseptember** [comment]
@dstftw Shared the credentials to your gmail with the subject line "#12207 - Account Credential Details - Site Support Request - Linux Academy"

**Comment by hb3b** [comment]
Any updates on this?

**Comment by boschkundendienst** [comment]
Just informational. It should be quite easy to add Linux Academy to youtube-dl. I found a semi-automated way to download videos using youtube-dl by

a) saving the cookie from your browser to cookies.txt after login to Linux Academy manually
b) find the course URL which is something like https://linuxacademy.com/cp/modules/view/id/courseid
c) grep the lessons URLs from the above page with something like

```
curl -s \
     --user-agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.79 Safari/537.1' \
     --cookie ./cookies.txt \
     "$url" \
     | grep lesson | sed 's/^.*<a.*="\///g' | sed 's/".*//g' | sed 's/^\s.*$//g' | sed 's/^$//g'  > lessons.txt
```

c) iterate through lessons.txt, parse values to create $title and download all of them with youtube-dl like this:

```
youtube-dl --user-agent "$agent" --force-generic-extractor --cookies "$cookie" "$pageurl" -o "$title.mp4"
```

I am not a programmer and can not do the essentials needed to directly support it with youtube-dl but since there are free courses available at Linux Academy (after free registration) one could try it and then contribute to youtube-dl?

Here is a list of free courses (after free registration - community member) for someone to test:

```
https://linuxacademy.com/cp/modules/view/id/85
https://linuxacademy.com/cp/modules/view/id/87
https://linuxacademy.com/cp/modules/view/id/260
https://linuxacademy.com/cp/modules/view/id/282
https://linuxacademy.com/cp/modules/view/id/289
https://linuxacademy.com/cp/modules/view/id/276
https://linuxacademy.com/cp/modules/view/id/250
https://linuxacademy.com/cp/modules/view/id/276
https://linuxacademy.com/cp/modules/view/id/140
```

**Comment by rdzberisha** [comment]
did someone try to work on this ?

**Comment by samhagin** [comment]
thanks for your solution @boschkundendienst, I put together a quick script using selenium and this can be used to download Linux Academy videos 

You first need to get cookies from Linux Academy manually, you can use this Chrome extension https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg?hl=en , and save it to a file

```
from __future__ import unicode_literals
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

import time
import youtube_dl

# initiate browser
driver = webdriver.Chrome()

# navigate to Linux Academy
driver.get("https://linuxacademy.com/")

# click login link
time.sleep(5)
link = driver.find_element_by_partial_link_text('Log In')
link.click()

# wait until login screen appears
time.sleep(5)

# login
user = driver.find_element_by_name('username')
user.send_keys('<replace with your username>')
password = driver.find_element_by_name('password')
password.send_keys('<replace with your password>')
password.send_keys(Keys.RETURN)

# navigate to course page
driver.get('<url for course page>') # example https://linuxacademy.com/cp/modules/view/id/140


# get lesson links
time.sleep(5)
lessons = driver.find_elements_by_tag_name('a')
urls = []

for i in lessons:
    try:
       lesson  =  i.get_attribute('href')
       if '/courses/' in lesson:
          urls.append( lesson )
    except:
      print('ignoring URL')

print( urls )

# call youtube-dl
ydl_opts = { 'cookiefile': '</path/to/cookie/file>', 'force_generic_extractor': True , 'outtmpl':   '%(autonumber)s-%(title)s.%(ext)s', 'restrictfilenames': True , 'sleep_interval': 30 }

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download( urls  )
```

**Comment by boschkundendienst** [comment]
Hi, good job.

If I understand it correctly you automated the login procedure. Wouldn't it be possible with this solution to login automatically and retrieve the cookie afterwards to get full automation?

**Comment by samhagin** [comment]
I actually had selenium grab the cookies and passed it on to youtube-dl in my first iteration of the code however the cookie format youtube-dl uses is different from selenium so that did not work. I will have to find a way to convert the selenium cookie to Netscape format to get this fully automated. 

Thanks

**Comment by samhagin** [comment]
I converted cookies from selenium to a format youtube-dl can read however i was still getting this error

```
does not look like a Netscape format cookies file
```

so I had to resort to curl to convert the cookie file and pass it on to youtube-dl, this works now without having to download the cookies manually 

```
from __future__ import unicode_literals
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

import sys, time
import youtube_dl
import os

username = sys.argv[1]
pwd = sys.argv[2]
url = sys.argv[3] 

cookie_file = 'cookies.txt'
f = open( cookie_file, 'a+')

def get_cookies():
  # write cookie file

  expiry = 0
  for i in driver.get_cookies():
    if not i.get('expiry'):
        expiry = 0
    else:
        expiry = i.get('expiry')
    cookie = '{}\t{}\t{}\t{}\t{}\t{}\t{}\n'.format( i['domain'], str( i['httpOnly'] ).upper(), i['path'], str( i['secure'] ).upper(), expiry, i['name'], i['value'] )
    f.write( cookie )


# initial browser 
driver = webdriver.Chrome()

# navigate to Linux Academy
driver.get("https://linuxacademy.com/")

# click login link
link = driver.find_element_by_partial_link_text('Log In')
link.click()

# get cookies from login.linuxacademy.com
get_cookies()

# wait until login screen appears 
time.sleep(5)

user = driver.find_element_by_name('username')
user.send_keys( username )
password = driver.find_element_by_name('password')
password.send_keys( pwd )
password.send_keys(Keys.RETURN)
driver.get( url )

# get cookies from .linuxacademy.com
get_cookies()

# get lesson links 
time.sleep(5)
lessons = driver.find_elements_by_tag_name('a')
urls = []

for i in lessons:
    try:
       lesson  =  i.get_attribute('href')
       if '/courses/' in lesson:
          urls.append( lesson )
    except:
      print('ignoring URL')

print( urls )

# close file handle
f.close()

# convert cookie using curl
cleaned_file = 'curlcookies.txt'
os.system('curl -b {} --cookie-jar {} {}'.format( cookie_file, cleaned_file, url  ) )

# call youtube-dl
ydl_opts = { 'cookiefile': cleaned_file, 'force_generic_extractor': True , 'outtmpl':   '%(autonumber)s-%(title)s.%(ext)s', 'restrictfilenames': True , 'sleep_interval': 30 }

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download( urls  )
```

Simply save the script to a file and call it like so 
python script.py username password url_to_course_page

Hope this helps

**Comment by yakzie** [comment]
First of all, thank You alot @samhagin

I was only able to download the first video in each course. Am I doing something wrong? Also I could not use urls like https://linuxacademy.com/cp/courses/lesson/course/1498/lesson/3/module/154 for downloading. It just gives "ERROR: Unsupported URL"

**Comment by samhagin** [comment]
You should use the URL to the course home page for instance, https://linuxacademy.com/cp/modules/view/id/154 and not a URL to a lesson. The URL to the course home page is needed since it has a list of URLs to each lesson. Let me know if that works for you

**Comment by yakzie** [comment]
I can only get the first video on the list. How can I get them all?

**Comment by samhagin** [comment]
I made a quick change to the script and it should work now. The new script is at https://github.com/samhagin/linuxacademy-dl/blob/master/download.py and it now has it own repo so it will be easier to track issues

**Comment by boschkundendienst** [comment]
Nice! - Thanks a lot, that's how community should work!

**Comment by sanudatta11** [comment]
Any way to make oauth login support in Linuxacademy-dl

**Comment by kh411d** [comment]
> Any way to make oauth login support in Linuxacademy-dl

Hi, I know this might not the answer, but it much more easier if you set your username and password other than oauth login support, I actually did that

**Comment by wywywywy** [comment]
It looks like now they redirect to another page when they detect that it's from youtube-dl.

User agent & referrer don't seem to help.

Has anyone any success?

**Comment by RahulShaw** [comment]
> It looks like now they redirect to another page when using youtube-dl.
> 
> User agent & referrer don't seem to help.
> 
> Has anyone any success?
The difference between the headers passed by a browser and youtube-dl is, the browser passes a `Connection: keep-alive` and youtube-dl passes `Connection: close`
Can that be a problem?

**Comment by wywywywy** [comment]
Sorry it seems to be a problem with the download.py script above, not youtube-dl itself.

I'll report it over there instead.

**Comment by jianleisun** [comment]
> Sorry it seems to be a problem with the download.py script above, not youtube-dl itself.
> 
> I'll report it over there instead.

Any way to address the following "redirect" issue?

Starting download..
[generic] 245: Requesting header
[redirect] Following redirect to https://linuxacademy.com/amazon-web-services/training/lesson/course/aws-certified-solutions-architect-professional-2018/name/course-introduction
[generic] course-introduction: Requesting header
WARNING: Forcing on generic information extractor.
[generic] course-introduction: Downloading webpage
[generic] course-introduction: Extracting information
ERROR: Unsupported URL: https://linuxacademy.com/amazon-web-services/training/lesson/course/aws-certified-solutions-architect-professional-2018/name/course-introduction
Traceback (most recent call last):
'''

**Comment by wywywywy** [comment]
Yea use the cookies.txt Chrome extension to get the cookies, then directly use youtube-dl to download.  I.e. ignoring the download.py script completely.
