### ISSUE TITLE
Vidzi.tv Don't work Now

### ISSUE THREAD

**Issue by best-job** [rg3/youtube-dl#12201]
youtube-dl 2017.02.17
Error :
 Unable to download webpage: HTTP Error 504: Gateway Time-out (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Please solve the problem quickly
Thanks

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
