### ISSUE TITLE
ERROR: Unable to download webpage: '' (caused by BadStatusLine("''",))

### ISSUE THREAD

**Issue by ringofyre** [rg3/youtube-dl#12216]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.21*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
PS D:\Incoming> youtube-dl.exe -v https://au.tv.yahoo.com/plus7/my-kitchen-rules/-/watch/34469498/my-kitchen-rules-wed-2
2-feb-season-8-episode-15/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://au.tv.yahoo.com/plus7/my-kitchen-rules/-/watch/34469498/my-kitchen-rules-wed-
22-feb-season-8-episode-15/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.21
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-83454-g3aae1ef, ffprobe N-83454-g3aae1ef
[debug] Proxy map: {}
[Yahoo] my-kitchen-rules-wed-22-feb-season-8-episode: Downloading webpage
ERROR: Unable to download webpage: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bu
g . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --ve
rbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\build\youtube_dl\extractor\common.py", lin
e 496, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\build\youtube_dl\YoutubeDL.py", line 2036,
 in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\build\youtube_dl\utils.py", line 1082, in
https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1186, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1227, in getresponse
  File "C:\Python\Python34\lib\http\client.py", line 386, in begin
  File "C:\Python\Python34\lib\http\client.py", line 356, in _read_status
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I've had a look at the open and closed issues with "BadStatusLine" errors. Most of them appear to be related to being behind a proxy. This is a direct connection and not behind a proxy so I am logging this as a bug report. Thank you.

**Comment by dstftw** [comment]
Obviously, network related issue on your side.
```
> py -3.6 .\youtube_dl\__main__.py -v https://au.tv.yahoo.com/plus7/my-kitchen-rules/-/watch/34469498/my-kitchen-ru
les-wed-2
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://au.tv.yahoo.com/plus7/my-kitchen-rules/-/watch/34469498/my-kitchen-rules-wed-2']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2017.02.21
[debug] Git HEAD: 71e9577
[debug] Python version 3.6.0 - Windows-10-10.0.10240-SP0
[debug] exe versions: ffmpeg N-83152-gf7e9275, ffprobe N-83152-gf7e9275, rtmpdump 2.4
[debug] Proxy map: {}
[Yahoo] my-kitchen-rules-wed: Downloading webpage
[brightcove:legacy] ref:34469498: Downloading webpage
[brightcove:legacy] ref:34469498: Extracting information
[debug] Invoking downloader on 'https://yahoo7p-a.akamaihd.net/2376984108001/201702/1944/2376984108001_5332018143001_5331967514001.mp4'
[download] Resuming download at byte 1047552
[download] Destination: My Kitchen Rules - Wed 22 Feb, season 8 episode 15-5331967514001.mp4
[download]   0.4% of 740.76MiB at 11.00MiB/s ETA 01:07
ERROR: Interrupted by user
```
