### ISSUE TITLE
ERROR: G8d2xyXP7DA: Failed to parse JSON  (caused by ValueError('Expecting value : line 1 column 1 (char 0)',)); when downloading video from www.tudou.com

### ISSUE THREAD

**Issue by haislandcn** [rg3/youtube-dl#12214]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.21*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
E:\download>youtube-dl --verbose "http://www.tudou.com/programs/view/G8d2xyXP7DA
"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.tudou.com/programs/view/G8d
2xyXP7DA']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.02.21
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[tudou] G8d2xyXP7DA: Downloading JSON metadata
ERROR: G8d2xyXP7DA: Failed to parse JSON  (caused by ValueError('Expecting value
: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bu
g . Make sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete outp
ut.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\bu
ild\youtube_dl\extractor\common.py", line 660, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\bu
ild\youtube_dl\extractor\common.py", line 660, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\bu
ild\youtube_dl\YoutubeDL.py", line 704, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\bu
ild\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\bu
ild\youtube_dl\extractor\tudou.py", line 77, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\bu
ild\youtube_dl\extractor\common.py", line 654, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\bu
ild\youtube_dl\extractor\common.py", line 664, in _parse_json
youtube_dl.utils.ExtractorError: G8d2xyXP7DA: Failed to parse JSON  (caused by V
alueError('Expecting value: line 1 column 1 (char 0)',)); please report this iss
ue on https://yt-dl.org/bug . Make sure you are using the latest version; type
youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
 include its complete output.
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

When trying to download any video from www.tudou.com which was uploaded since 2017/2/19, an error about "Failed to parse JSON" occur, below is the error info in normal usage, I had dumped all info with youtube-dl --verbose "http://www.tudou.com/programs/view/G8d2xyXP7DA/" in above section.

I tried this in Windows 7 both of 32bit and 64bit, also I tried it in Windows XP 32bit, error will occur in all of them. I have no Windows 8 and Windows 10, so I did not give it a try.

E:\download>youtube-dl.exe --download-archive 1.txt "http://www.tudou.com/progra
ms/view/G8d2xyXP7DA/"
[tudou] G8d2xyXP7DA: Downloading JSON metadata
ERROR: G8d2xyXP7DA: Failed to parse JSON  (caused by ValueError('Expecting value
: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bu
g . Make sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete outp
ut.

**Comment by haislandcn** [comment]
Downloading video which was uploaded before 2017/2/19 with same environment is OK.

For example: youtube-dl.exe --download-archive 1.txt "http://www.tudou.com/programs/view/tBGssIQnOq0/" works well.

**Comment by fireattack** [comment]
I can confirm tudou is broken, but it's not restricted to "video which was uploaded before 2017/2/19" here.

http://www.tudou.com/programs/view/YTaG61s7Usg
http://www.tudou.com/programs/view/WkBloIE86Yk/

I tried these two quickly, can't download either (they're uploaded in 2010).

**Comment by haislandcn** [comment]
Yes, I did try an older link which was uploaded in 2016 and can be downloaded before, but they are not work now. Seems this error is related with tudou, not youtube-dl?

**Comment by fireattack** [comment]
yeah, for the two videos I listed, I actually downloaded them like half a month ago, succesfully. It's likely because Tudou changed something in their end. Nevertheless, it's the nature of web service we have to adapt.

**Comment by dkl3** [comment]
Very sorry--I didn't notice this issue and didn't think somebody else would use Tudou with youtube-dl. Anyway, hopefully this issue willl get fixed.

**Comment by haislandcn** [comment]
Never mind. youtube-dl is greate, we always using it download the video from many sites besides of youtube.com. :) That will be greate if we can support tudou.com again.

**Comment by yan12125** [comment]
Tudou is merge into Youku now, and youtube-dl will be able to download it in the next version.
