### ISSUE TITLE
ERROR: An extractor error has occurred. (caused by KeyError(u'vcodec',));

### ISSUE THREAD

**Issue by awei78** [rg3/youtube-dl#12211]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.21*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

[Issue]
url:http://video.toggle.sg/en/series/whoopie-s-world/ep3/478601
parse error:
[toggle] 478601: Downloading video page
[toggle] 478601: Downloading video info json
[toggle] 478601: Downloading STBMain m3u8 information
[toggle] 478601: Downloading iPhoneMain m3u8 information
[toggle] 478601: Downloading iPadMain m3u8 information
[toggle] 478601: Downloading Android m3u8 information
[toggle] 478601: Downloading HLS_Mobile m3u8 information
ERROR: An extractor error has occurred. (caused by KeyError(u'vcodec',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[Rolution]
youtube_dl\extractor\common.py
line1408:
`if audio_in_video_stream.get(last_info.get('AUDIO')) is False and f['vcodec'] != 'none':`
modified to
`if audio_in_video_stream.get(last_info.get('AUDIO')) is False and f.get('vcodec', 'none') != 'none':`

It works fine!

**Comment by vikivivi** [comment]
Any chance to fix this issue #12211using @awei78 patch ?
This issue is still present using version 2017.04.09 (3f2ce6896acfd487ce915788255ddee1e04794b3)
```bash
$ git diff youtube_dl/extractor/common.py
diff --git a/youtube_dl/extractor/common.py b/youtube_dl/extractor/common.py
index ae8af61..8bb998f 100644
--- a/youtube_dl/extractor/common.py
+++ b/youtube_dl/extractor/common.py
@@ -1424,7 +1424,7 @@ class InfoExtractor(object):
                         'abr': abr,
                     })
                 f.update(parse_codecs(last_info.get('CODECS')))
-                if audio_in_video_stream.get(last_info.get('AUDIO')) is False and f['vcodec'] != 'none':
+                if audio_in_video_stream.get(last_info.get('AUDIO')) is False and f.get('vcodec', 'none') != 'none':
                     # TODO: update acodec for audio only formats with the same GROUP-ID
                     f['acodec'] = 'none'
                 formats.append(f)
```
