### ISSUE TITLE
what is the command to play streams in vlc?

### ISSUE THREAD

**Issue by brlala** [rg3/youtube-dl#12218]
would like to play a stream from 斗鱼 using VLC, https://www.douyu.com/fengtimo

tried using this command but it doesn't work.

> youtube-dl -p vlc https://www.douyu.com/fengtimo

> Usage:
 > you [OPTIONS] URL [URL...]
> you: error: account username missing

am able to download it just not stream it in VLC

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#how-do-i-stream-directly-to-media-player
