### ISSUE TITLE
Need to go to dedicated Youtube playlist page instead of just being able to download playlists via the normal play URL

### ISSUE THREAD

**Issue by jancborchardt** [rg3/youtube-dl#12220]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.21**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
jan@Rechenknecht:~/youtubedl$ youtube-dl -v https://www.youtube.com/watch?v=fy-J_E55rw0&list=PLAwxTw4SYaPlr4Uq3RoYuwlDADp0WQdGl
[1] 30358
jan@Rechenknecht:~/youtubedl$ [debug] System config: []
[debug] User config: []
[debug] Custom config: []
**[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=fy-J_E55rw0']**
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.21
[debug] Python version 2.7.12 - Linux-4.4.0-63-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] fy-J_E55rw0: Downloading webpage
[youtube] fy-J_E55rw0: Downloading video info webpage
[youtube] fy-J_E55rw0: Extracting video information
[youtube] fy-J_E55rw0: Downloading MPD manifest
[debug] Invoking downloader on u'https://r20---sn-4g57kner.googlevideo.com/videoplayback?id=7f2f89fc4e79af0d&itag=137&source=youtube&requiressl=yes&initcwndbps=2307500&mm=31&mn=sn-4g57kner&pl=24&ms=au&mv=m&ratebypass=yes&mime=video/mp4&gir=yes&clen=16424110&lmt=1387481014582605&dur=67.701&mt=1487774368&signature=96A3AA7BCCEA214F0D92E28360B14C9D76144136.665A74682EB52987D7C68FCB11E331985871DCD9&key=dg_yt0&upn=nQ8bir-W9Lk&ip=212.121.131.210&ipbits=0&expire=1487796083&sparams=ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,mm,mn,pl,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Welcome to the Course - Intro to the Design of Everyday Things-fy-J_E55rw0.f137.mp4
[download] 100% of 15.66MiB in 02:01
[debug] Invoking downloader on u'https://r20---sn-4g57kner.googlevideo.com/videoplayback?id=7f2f89fc4e79af0d&itag=140&source=youtube&requiressl=yes&initcwndbps=2307500&mm=31&mn=sn-4g57kner&pl=24&ms=au&mv=m&ratebypass=yes&mime=audio/mp4&gir=yes&clen=1077484&lmt=1387480932116651&dur=67.802&mt=1487774368&signature=67D47674CD8539B405A355BA316DB3AB8F32D64C.0BBF0C376B2F3AEDDF50682081679E11FE5523AD&key=dg_yt0&upn=nQ8bir-W9Lk&ip=212.121.131.210&ipbits=0&expire=1487796083&sparams=ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,mm,mn,pl,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Welcome to the Course - Intro to the Design of Everyday Things-fy-J_E55rw0.f140.m4a
[download] 100% of 1.03MiB in 00:08
[ffmpeg] Merging formats into "Welcome to the Course - Intro to the Design of Everyday Things-fy-J_E55rw0.mp4"
[debug] ffmpeg command line: avconv -y -i 'file:Welcome to the Course - Intro to the Design of Everyday Things-fy-J_E55rw0.f137.mp4' -i 'file:Welcome to the Course - Intro to the Design of Everyday Things-fy-J_E55rw0.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Welcome to the Course - Intro to the Design of Everyday Things-fy-J_E55rw0.temp.mp4'
Deleting original file Welcome to the Course - Intro to the Design of Everyday Things-fy-J_E55rw0.f137.mp4 (pass -k to keep)
Deleting original file Welcome to the Course - Intro to the Design of Everyday Things-fy-J_E55rw0.f140.m4a (pass -k to keep)
^C
[1]+  Fini                    youtube-dl -v https://www.youtube.com/watch?v=fy-J_E55rw0
jan@Rechenknecht:~/youtubedl$ 
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

I have been using youtube-dl for single videos and I read it also does playlists. Instinctively I assumed that I can just paste the URL I get when I am on the first video of a playlist, hand it to youtube-dl, and all videos will be downloaded.

But only the first video will be downloaded. Even with `--yes-playlist` there’s no difference. youtube-dl doesn’t even properly end and give me a command line again, I need to do Ctrl-C to get out of it.

The issue seems to be the line 6 I highlighted above in the log. The URL I give is https://www.youtube.com/watch?v=fy-J_E55rw0&list=PLAwxTw4SYaPlr4Uq3RoYuwlDADp0WQdGl, but the argument taken is only `Command-line args: [u'-v', u'https://www.youtube.com/watch?v=fy-J_E55rw0']`, without the `&list=PLAwxTw4SYaPlr4Uq3RoYuwlDADp0WQdGl` part.

I need to manually go to `https://www.youtube.com/playlist?list=PLAwxTw4SYaPlr4Uq3RoYuwlDADp0WQdGl` to make it work. Until I found that out I was thinking youtube-dl is broken, tried a lot of things, and finally saw it on a forum post. Sure it’s also in the help, but honestly for such a basic (and useful) functionality that should not be required reading. :)

The design enhancement suggestion would be to handle these URLs with the `watch?v` which also have a `list` attribute like playlists. If that is not desirable, the `--no-playlist` flag can be respected.

**Comment by dstftw** [comment]
You have to either put the URL into quotes or manually escape all the special shell characters. Read [FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for details.

**Comment by jancborchardt** [comment]
Ah, thanks a lot! I didn’t check that FAQ entry cause there was no error – thanks!
