### ISSUE TITLE
discoverygo

### ISSUE THREAD

**Issue by markybob** [rg3/youtube-dl#12223]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.22**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
markybob@dellfuck:~$ ./bin/youtube-dl -v
[debug] System config: []
[debug] User config: [u'--mark-watched']
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.22
[debug] Python version 2.7.13 - Linux-4.9.4-x86_64-with-debian-9.0
[debug] exe versions: avconv 3.2.4-1, avprobe 3.2.4-1, ffmpeg 3.2.4-1, ffprobe 3.2.4-1, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options....
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.discoverygo.com/the-last-alaskans/no-mans-land/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

trying to download an episode from discoverygo. you need a cable account, which i have. i can watch it in browser. with youtube-dl this is what happens:
markybob@dellfuck:~/Fresh/the last alaskans/season 1$ /home/markybob/bin/youtube-dl --ap-mso TWC --ap-username **email**@gmail.com --ap-password **pass** "https://www.discoverygo.com/the-last-alaskans/no-mans-land/"
[DiscoveryGo] no-mans-land: Downloading webpage
ERROR: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.

i also have a comcast xfinity account which i tried. same error.

thanks.

**Comment by StevenDTX** [comment]
Discovery sites require cookies, not adobe pass.
