### ISSUE TITLE
Download progress percentage can go backwards

### ISSUE THREAD

**Issue by mrj** [rg3/youtube-dl#12224]
The downloaded progress percentage doesn't monotonically increase, but often goes backwards. e.g.
```
[download]   3.2% of ~62.28MiB at  4.15MiB/s ETA 00:19
[download]   6.4% of ~62.28MiB at  4.23MiB/s ETA 00:16
[download]  11.8% of ~62.28MiB at  4.25MiB/s ETA 00:14
[download]  11.8% of ~62.28MiB at  4.25MiB/s ETA 00:14
[download]   8.8% of ~82.93MiB at 92.11KiB/s ETA 00:20
[download]   8.8% of ~82.93MiB at 273.49KiB/s ETA 00:20
[download]   8.8% of ~82.93MiB at 634.85KiB/s ETA 00:20
[download]   8.9% of ~82.93MiB at  1.32MiB/s ETA 00:20
```
This causes progress bars to jump backwards unless backward jumps are filtered out.

- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.22**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Bug report (encountered problems with youtube-dl)

**Comment by dstftw** [comment]
Total file size for fragmented data is extrapolated based on fragments downloaded so far. Otherwise it would require sending HTTP requests for content length for all fragments before starting downloading that is unwanted.

**Comment by mrj** [comment]
Thanks for the explanation.
