### ISSUE TITLE
Add support for v.douyu.com

### ISSUE THREAD

**Issue by brlala** [rg3/youtube-dl#12228]
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

---

```
C:\Windows\system32>youtube-dl -v https://v.douyu.com/show/rjNBdvnARNWE2ywK
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://v.douyu.com/show/rjNBdvnARNWE2ywK']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.02.17
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-83585-ga5c1c7a, ffprobe N-83585-ga5c1c7a
[debug] Proxy map: {}
[generic] rjNBdvnARNWE2ywK: Requesting header
WARNING: Falling back on generic information extractor.
[generic] rjNBdvnARNWE2ywK: Downloading webpage
[generic] rjNBdvnARNWE2ywK: Extracting information
ERROR: Unsupported URL: https://v.douyu.com/show/rjNBdvnARNWE2ywK
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\extractor\common.py", line 370, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\extractor\generic.py", line 2604, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://v.douyu.com/show/rjNBdvnARNWE2ywK
```

Not able to download uploaded content videos from douyu斗鱼 even thou it is listed on the supported page.

**Comment by yan12125** [comment]
This page says:

> 您播放的视频出错了！

(There's something wrong in the video you played!)

Can you watch this video in browsers?

**Comment by dstftw** [comment]
Plays fine.

**Comment by yan12125** [comment]
Thanks dstftw. They serve plain HTTP m3u8 streams on HTTPS websites, and I've configured Firefox to blocks such requests in the past. Worked fine with ```security.mixed_content.block_display_content``` set to false.

**Comment by brlala** [comment]
Single video: https://v.douyu.com/show/rjNBdvnVXNzvE2yw
P/S I am told that the video is separated into 10sec clip which makes the download process very hard, therefore in order to download from this website, one has to download a playlist and then merge the files together. Does the website behaves like this and is it possible to add support to this site in terms of coding?

An easier way is to obtain the link directly using Internet Explorer agent, using other browser such as Chrome/Firefox to obtain the link will return an error upon download.

**Comment by yan12125** [comment]
Sorry for the late response. Douyu shows will be supported in the next version.
