### ISSUE TITLE
ERROR: Unable to download JSON metadata: HTTP Error 500

### ISSUE THREAD

**Issue by break1** [rg3/youtube-dl#12238]
---

- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.22**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)

---

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-o', 'D:\\lynda\\Design\\Graphic Design Tips & Tricks\\%(playlist_index)s - %(title)s.%(ext)s', '--all-subs', '--external-downloader', 'aria2c.exe', '--verbose', 'https://www.lynda.com/Color-tutorials/Graphic-Design-Tips-Tricks/365959-2.html']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2017.02.22
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Downloading signin page
[lynda:course] Submitting email
[lynda:course] Submitting password
[lynda:course] 365959: Downloading course JSON
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkf42q19b\build\youtube_dl\extractor\common.py", line 496, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkf42q19b\build\youtube_dl\YoutubeDL.py", line 2036, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
...
<end of log>
```

---

---

### Description of your *issue*, suggested solution and other information

I downloaded a lot from lynda.com till date 02/22/2017 with no error. On 02/22/2017 this error ocurs on most links on lynda.com, and I start searching the web for a solution, I discovered youtube-dl have an update on this date, I made the update but nothing was changed ...so on 02/22/2017 all my downloads from lynda.com was broken. I have premium account on lynda with rights for download.

**Comment by jackiedn** [comment]
Me too, lol, still don't know how to resolve this

**Comment by Bachsau** [comment]
http://mediathek.daserste.de/Reportage-Dokumentation/Die-Story-im-Ersten-Autoland-abgebrannt/Video?bcastId=799280&documentId=38510062

http://www.ardmediathek.de/tv/Reportage-Dokumentation/Die-Story-im-Ersten-Autoland-abgebrannt/Das-Erste/Video?bcastId=799280&documentId=38510062

**Comment by break1** [comment]
Thank you, is working now.

**Comment by Bachsau** [comment]
Not for me.
`[ARD:mediathek] Video: Downloading media JSON
ERROR: Video: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by dstftw** [comment]
@Bachsau learn how to [use command line](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).
