### ISSUE TITLE
Vimeo video download fails

### ISSUE THREAD

**Issue by sabihalam** [rg3/youtube-dl#12233]
One of my script that was downloading vimeo videos with youtube-dl is not working anymore. 

e.g. youtube-dl -f mp4 -o f1f4679a-f9da-11e6-b1fc-000c291952a8.mp4 https://www.vimeo.com/160758186

ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 version I am using is 2017.02.22

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
