### ISSUE TITLE
FUNCTION REQUEST: Use free ram to store chunk or other small files

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#12230]
Hello dearest codes!
I've noticed many times when YDL is getting hundreds of chunks then to make one .mkv/.mp4 file at the end. Almost 98% of those 'chunked' files are from news blocks being got from several TV sites yet those blocks are not more than 300-600mb in sum as usual, so: It will be pretty nice to add feature to YDL, to specify what amount of memory YDL can use to store temp.files, instead of using HDD for those files - in case, user like me has 16gb on board, and 8-10gb free.

Thanks in advance!

**Comment by yan12125** [comment]
Another requested feature at #10993 can achieve this: creating a ramdisk and use that as the temporary directory. Please move there for further discussions.

**Comment by yan12125** [comment]
> Ramdisk is costs some money

Ramdisks are implemented by softwares. Not sure what you're referring to?

**Comment by nmr50** [comment]
| Not sure what you're referring to?
I mean that good Ramdisk software costs some money while others are pierces with ads inside, very limited in usage...

**Comment by yan12125** [comment]
Ah. I guess you're using Windows? On Linux and Mac ramdisks are built-in features (e.g. available out-of-box). On the other hand, implementing such a feature is almost as hard as implementing a virtual file system. After #10993 is done, we can re-visit this issue and see how it can be extended to support temporary files in the memory.

Another related feature: #9937 (remove the concept of temporary segments from youtube-dl)

**Comment by nmr50** [comment]
Yes, I am Win7 user:) But what about implementing flag to specify folder for temp files at least ?

**Comment by yan12125** [comment]
> what about implementing flag to specify folder for temp files at least ?

That's exactly what #10993 is talking about :)

**Comment by nmr50** [comment]
OK, I'll be waiting for tmp folder flag then :) Thanks !!!
