### ISSUE TITLE
CBC Radio Functionality

### ISSUE THREAD

**Issue by corvaxmuzzy** [rg3/youtube-dl#12249]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

```
# youtube-dl --verbose http://www.cbc.ca/radio/popup/audio/player.html?autoPlay=true&clipIds=2678738964&mediaIds=2678739061
[1] 22764
[2] 22765
xxx@xxx:/home/xxx# [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.cbc.ca/radio/popup/audio/player.html?autoPlay=true']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.7
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6, rtmpdump 2.4
[debug] Proxy map: {}
[cbc.ca] player.html: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'clipId',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cbc.py", line 128, in _real_extract
    for player_init in re.findall(r'CBC\.APP\.Caffeine\.initInstance\(({.+?})\);', webpage)]
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cbc.py", line 111, in _extract_player_init
    clip_id = player_info['clipId']
KeyError: u'clipId'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'clipId',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.cbc.ca/radio/popup/audio/listen.html?autoPlay=true&clipIds=2678738964
- Single video: http://www.cbc.ca/radio/popup/audio/listen.html?autoPlay=true&clipIds=2678738964&mediaIds=2678739061&contentarea=radio&subsection1=radio1&subsection2=currentaffairs&subsection3=back_story&contenttype=audio&title=2016/12/23/1.3317621-the-earthquake-and-the-aftermath-david-gutnick-haiti-2010&contentid=1.3317621

---

### Description of your *issue*, suggested solution and other information
CBC Radio support is stated for youtube-dl.  I could not make it work.  If it is supported, could you please provide an example command & URL?

**Comment by dstftw** [comment]
You have to either put the URL into quotes or manually escape all the special shell characters. Read [FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for details.

**Comment by corvaxmuzzy** [comment]
I just wanted to apologize for not thinking of trying that.  Thank you for all of your hard work.
