### ISSUE TITLE
--exec does not work as expected: Command returned error code 2

### ISSUE THREAD

**Issue by sebma** [rg3/youtube-dl#12248]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

---

Hi,

The `--exec` option does not work as expected :

`$ youtube-dl -v http://www.youtube.com/watch?v=S5XBBA1DTAI
[debug] System config: []
[debug] User config: [u'--no-warnings', u'--ignore-errors', u'--continue', u'-o', u'%(title)s__%(format_id)s__%(id)s.%(ext)s', u'-f', u'mp4/flv', u'--add-metadata', u'--embed-subs', u'--restrict-filenames', u'--all-sub', u'--prefer-ffmpeg', u'--embed-thumbnail', u'--exec', u'mp4tags -m "%(url)s" {}']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=S5XBBA1DTAI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 2.7.6 - Linux-4.4.0-59-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg git-2017-01-22-f1214ad, ffprobe git-2017-01-22-f1214ad, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] S5XBBA1DTAI: Downloading webpage
[youtube] S5XBBA1DTAI: Downloading video info webpage
[youtube] S5XBBA1DTAI: Extracting video information
[youtube] S5XBBA1DTAI: Downloading MPD manifest
[youtube] S5XBBA1DTAI: Downloading MPD manifest
[youtube] S5XBBA1DTAI: Downloading thumbnail ...
[youtube] S5XBBA1DTAI: Writing thumbnail to: Joseph_Prince_Dead_To_Sin_How__18__S5XBBA1DTAI.jpg
[debug] Invoking downloader on u'https://r14---sn-4gxx-25gel.googlevideo.com/videoplayback?requiressl=yes&ratebypass=yes&clen=171586191&mime=video%2Fmp4&key=yt6&ipbits=0&mm=31&signature=307FECA6443CA0505E8ED4CA37EFB5A57FEB16B9.82E191686D46BB2154EFC3FF2245CC8F92D3AB24&mn=sn-4gxx-25gel&itag=18&gir=yes&dur=4431.969&mt=1487952028&mv=m&ms=au&ip=78.243.8.240&lmt=1487214775941738&pcm2cms=yes&ei=1luwWNb2DMuNc8LAkogO&id=o-AF62MrLHehsJM-9MMhzbubyjCCqk_UtlSdkBfgE-_qFp&expire=1487974454&upn=CiO1LfIzjO0&nh=EAE&beids=%5B9452307%5D&pl=12&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&source=youtube&initcwndbps=963750'
[download] Joseph_Prince_Dead_To_Sin_How__18__S5XBBA1DTAI.mp4 has already been downloaded                                                                               
[download] 100% of 165.89MiB
[ffmpeg] Adding metadata to 'Joseph_Prince_Dead_To_Sin_How__18__S5XBBA1DTAI.mp4'
[debug] ffmpeg command line: ffmpeg -y -i file:Joseph_Prince_Dead_To_Sin_How__18__S5XBBA1DTAI.mp4 -c copy -metadata comment= -metadata description= -metadata 'artist=Febin T. Shajan' -metadata 'title=Joseph Prince Dead To Sin How' -metadata date=20170215 -metadata 'purl=https://www.youtube.com/watch?v=S5XBBA1DTAI' file:Joseph_Prince_Dead_To_Sin_How__18__S5XBBA1DTAI.temp.mp4
[ffmpeg] There aren't any subtitles to embed
[atomicparsley] Adding thumbnail to "Joseph_Prince_Dead_To_Sin_How__18__S5XBBA1DTAI.mp4"
[debug] AtomicParsley command line: AtomicParsley Joseph_Prince_Dead_To_Sin_How__18__S5XBBA1DTAI.mp4 --artwork Joseph_Prince_Dead_To_Sin_How__18__S5XBBA1DTAI.jpg -o Joseph_Prince_Dead_To_Sin_How__18__S5XBBA1DTAI.temp.mp4
[exec] Executing command: mp4tags -m "%(url)s" Joseph_Prince_Dead_To_Sin_How__18__S5XBBA1DTAI.mp4
$ mp4info Joseph_Prince_Dead_To_Sin_How__18__S5XBBA1DTAI.mp4 | grep Description
 Short Description: %(url)s`

Can you try and fix this ?

**Comment by dstftw** [comment]
`--exec` is not expected to work with output template. If you want to request this feature open a new issue with proper explanation.
