### ISSUE TITLE
Can't download anything from YouTube

### ISSUE THREAD

**Issue by dhofverberg** [rg3/youtube-dl#12258]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24.1**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [X] Other

---

I can't seem to download anything from YouTube. I have tried with dozens of videos, but get "Operation not permitted" on every single one. I'm using the latest Windows .EXE binary of youtube-dl. Operating system is Windows 7.

I assume the problem is specific to my computer, but I have no idea what the problem is.

Example of one such problematic video:
https://www.youtube.com/watch?v=rDR17nf2nbQ

Here is a verbose output of youtube-dl:

`
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=rDR17nf2nbQ']

[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: avconv N-33818-gd049257, ffmpeg N-83622-gdcd3418, ffprobe
N-52045-g694fa00
[debug] Proxy map: {}
[youtube] rDR17nf2nbQ: Downloading webpage
[youtube] rDR17nf2nbQ: Downloading video info webpage
[youtube] rDR17nf2nbQ: Extracting video information
[youtube] rDR17nf2nbQ: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mk
v.
[debug] Invoking downloader on 'https://r1---sn-cgxqc5oqufv-0hxe.googlevideo.com/videoplayback?id=ac3475ee77f69db4&itag=137&source=youtube&requiressl=yes&initcw
ndbps=3051250&pl=21&mm=31&mn=sn-cgxqc5oqufv-0hxe&ms=au&mv=m&ratebypass=yes&mime=video/mp4&gir=yes&clen=257993571&lmt=1394126726130081&dur=1036.441&beids=%5B9452
306%5D&key=dg_yt0&signature=46399CE1DB9D988AA2CFC9BD503E17EA658628E1.82D6ACD6B096D41BDDBF4F012320A9D943CA9B00&mt=1488008781&upn=ArrihShkGTg&ip=62.220.169.72&ipb
its=0&expire=1488030496&sparams=ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,pl,mm,mn,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Den Objudna Gästen - Kortfilm Komedi-rDR17nf2nbQ.f137.mp4
[download] 100% of 246.04MiB in 00:25
[debug] Invoking downloader on 'https://r1---sn-cgxqc5oqufv-0hxe.googlevideo.com/videoplayback?requiressl=yes&keepalive=yes&upn=HB9A3rJKD_E&expire=1488030495&lm
t=1423230047214044&id=o-AJ59RZc7_O4P0H9s6ipvUfH3lYWttTQ8rw-RgcmL5UE3&ipbits=0&mm=31&mn=sn-cgxqc5oqufv-0hxe&initcwndbps=3051250&clen=20216802&ip=62.220.169.72&ms
=au&mt=1488008781&mv=m&dur=1036.481&gir=yes&signature=E0FCA123320FA55CCE1202BAC19C1C9E3DCD02CB.40DDD2E7D44428E2DCE416EC3D7E856D1571E56A&beids=%5B9452306%5D&spar
ams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ei=vzax
WOr9HsyTd7mflNgP&itag=251&key=yt6&mime=audio%2Fwebm&pl=21&source=youtube&ratebypass=yes'
[download] Destination: Den Objudna Gästen - Kortfilm Komedi-rDR17nf2nbQ.f251.webm
[download] 100% of 19.28MiB in 00:02
[ffmpeg] Merging formats into "Den Objudna Gästen - Kortfilm Komedi-rDR17nf2nbQ.mkv"
[debug] ffmpeg command line: avconv -y -i 'file:Den Objudna Gästen - Kortfilm Komedi-rDR17nf2nbQ.f137.mp4' -i 'file:Den Objudna Gästen - Kortfilm Komedi-rDR17nf
2nbQ.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Den Objudna Gästen - Kortfilm Komedi-rDR17nf2nbQ.temp.mkv'
ERROR: file:Den Objudna Gästen - Kortfilm Komedi-rDR17nf2nbQ.f137.mp4: Operation not permitted
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\bu
ild\youtube_dl\YoutubeDL.py", line 1929, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\bu
ild\youtube_dl\postprocessor\ffmpeg.py", line 444, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\bu
ild\youtube_dl\postprocessor\ffmpeg.py", line 192, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Den Objudna Gästen - Kortfilm Komedi-rDR17nf2nbQ.f137.mp4: Operation not permitted`

---
Can anyone tell what the problem is, or suggesting how to fix it?

**Comment by Hrxn** [comment]
What happens if you remove `avconv` from yout PATH temporarily?

**Comment by dhofverberg** [comment]
Thanks for the help. Removing that from the PATH seems to solve the problem, strangely enough. I can then download episodes just fine.

So what is actually the problem, if it solves removing that path from the PATH environment variable?

**Comment by dstftw** [comment]
`avconv` on your system is/points to ffmpeg that is 6 years old.
