### ISSUE TITLE
[Request] Flag to stop execution of script if date is not in range

### ISSUE THREAD

**Issue by jhpratt** [rg3/youtube-dl#12256]
I'm download entire channels on YT, and would like to keep them up to date. In doing so, youtube-dl checks every single video against my most recent update, even though as soon _one_ is encountered that is out of the date range, all of the others will be as well.

Basically, if a video is not in the date range provided, stop execution of the script, which would dramatically speed up my automated script.

**Comment by yan12125** [comment]
```--match-filter``` can do that.

> I'm download entire channels on YT, and would like to keep them up to date

Another feature ```--download-archive``` may be useful, too

**Comment by jhpratt** [comment]
`--download-archive` is what I was looking for. Thanks!
