### ISSUE TITLE
Feature request: Use folder containing thumbnails as a batch-file (download list)

### ISSUE THREAD

**Issue by ogekve** [rg3/youtube-dl#12252]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24.1**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Feature request (request for a new functionality)

---

The ability to use a file with a list of URLs to download is great, but it requires a bit of work and management. A nice feature would be to allow for users to do the following:
1 Download thumbnails into a folder. (which users can already do easily) The thumbnails should have the youtube random digits at the end of the thumbnail name, which I think is the default.
2 Users manually organize the thumbnails based on which videos they want to download, by removing thumbnails of video they don't want.
3 Telling youtube-dl to treat the directory/folder as a batch-file (similar to "-a"), so that each thumbnail in that folder is converted back to a URL and placed into youtube-dl for download.

**Comment by dstftw** [comment]
1. Filename is governed by output template and may not contain the video id.
2. Even though filename contains video id, it's not possible in general to restore the original video URL by id.
3. Nothing prevents you from doing the same with list of URLs.
