### ISSUE TITLE
My pc doesn't support youtube-dl?

### ISSUE THREAD

**Issue by JustKais** [rg3/youtube-dl#12253]
When i did update my ts i saw that my bot doesn't work anymore. So i deleted sinusbot and reinstalled ts3 on version 3.0.19.4.
Now when i run youtube-dl (Installed python on the latest version.) I get this error: https://gyazo.com/43ab4a49c2a01789d221922369d69db5

When i had the old version it all just worked.

**Comment by Hrxn** [comment]
?

Can you please clarify what the issue is here?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
