### ISSUE TITLE
When giving sequential commands with && it goes crazy

### ISSUE THREAD

**Issue by J316** [rg3/youtube-dl#12261]
When I type `youtube-dl (some playlist link) && youtube-dl (other links)` it starts overlapping downloads and the output is a mess, this is the only program that doesn't respect the order assigned `(command1) && (command2)`

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by J316** [comment]
@yan12125

**Comment by yan12125** [comment]
If you're looking for diagnosing, please provide enough information: the actual command you use. Fake parameters like ```(some playlist link)``` doesn't help.
