### ISSUE TITLE
How to increase the youtube-dl speed as its taking 1/10 th of my current speed

### ISSUE THREAD

**Issue by rituparnog** [rg3/youtube-dl#12265]
How to increase the youtube-dl speed as its taking 1/10 th of my current speed
I used below command
youtube-dl https://app.pluralsight.com/library/courses/tactical-design-patternsdot-net --username XX --password XXX--all-subs

**Comment by dstftw** [comment]
Ask either your ISP or site you are downloading from. youtube-dl does not impose any bandwidth limitations.
