### ISSUE TITLE
Installing in /usr/local/bin/youtube-dl doesn't work

### ISSUE THREAD

**Issue by J316** [rg3/youtube-dl#12260]
When installing in the /usr/local/bin folder like shown in the guide doesn't work, when using the program I get `-bash: /usr/bin/youtube-dl: No such file or directory`. To make it work I have to do the steps the guide shows but changing the path to `/usr/bin/youtube-dl`, but I found nowhere someone with a similar issue. What's wrong?

**Comment by dstftw** [comment]
Did you even restart/rehash you bash session?
Maybe similar to #11478.
In any case that is a problem with your configuration not youtube-dl issue.

**Comment by Fabian42** [comment]
Confirmed that restarting the console fixes it. That should probably be in readme.

**Comment by nawafisuren** [comment]
16  history
   17  youtube-dl https://www.youtube.com/watch?v=lC45Moj_Tyw&list=PLQqrki3E1Hi7HB9agDgPDf0nDiLpBhZZz&index=2&t=0s
   18  youtube-dl -vt "http://www.youtube.com/watch?v=1XSa-u2ZgRc" --format 18
   19  youtube-dl -vt -F actVLwGDZQY
   20  youtube-dl http://youtube.com/watch?v=actVLwGDZQYk
   21  youtube-dl -U
   22  youtube-dl -update
   23  youtube-dl --update
   24  sudo youtube-dl --update
   25  sudo apt-get youtube-dl --update
   26  sudo apt-update youtube-dl
   27  pip install --upgrade youtube-dl
   28  youtube-dl --version
   29  sudo youtube-dl -U
   30  sudo apt-get install python-setuptools
   31  sudo easy_install pip
   32  sudo pip install --upgrade youtube-dl
   33  wget -O - https://yt-dl.org/downloads/latest/youtube-dl | sudo tee /usr/local/bin/youtube-dl >/dev/null
   34  sudo chmod a+x /usr/local/bin/youtube-dl
   35  sudo pip install --upgrade youtube-dl
   36  sudo apt-get remove youtube-dl
   37  youtube-dl
   38  sudo pip install --upgrade youtube-dl
   39  youtube-dl https://www.youtube.com/watch?v=lC45Moj_Tyw&list=PLQqrki3E1Hi7HB9agDgPDf0nDiLpBhZZz&index=2&t=0s
   40  sudo apt-get update
   41  youtube-dl https://www.youtube.com/watch?v=lC45Moj_Tyw&list=PLQqrki3E1Hi7HB9agDgPDf0nDiLpBhZZz&index=2&t=0s
   42  sudo pip install --upgrade youtube_dl
   43  youtube "https://www.youtube.com/watch?v=lC45Moj_Tyw&list=PLQqrki3E1Hi7HB9agDgPDf0nDiLpBhZZz&index=2&t=0s"
   44  youtube-dl "https://www.youtube.com/watch?v=lC45Moj_Tyw&list=PLQqrki3E1Hi7HB9agDgPDf0nDiLpBhZZz&index=2&t=0s"
   45  sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
   46  sudo chmod a+rx /usr/local/bin/youtube-dl
   47  youtube-dl "https://www.youtube.com/watch?v=lC45Moj_Tyw&list=PLQqrki3E1Hi7HB9agDgPDf0nDiLpBhZZz&index=2&t=0s"


   48  sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/bin/youtube-dl
   49  sudo chmod a+rx /usr/bin/youtube-dl

   50  youtube-dl "https://www.youtube.com/watch?v=lC45Moj_Tyw&list=PLQqrki3E1Hi7HB9agDgPDf0nDiLpBhZZz&index=2&t=0s"

basobox@basobox-69:~$
