### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by video2000** [rg3/youtube-dl#12263]
videoporno-25152@nc1159 ~ $  php /var/www/videopornoitalia.it/htdocs/admin/scraper_cron.php
  [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--dump-json', 'https://it.xhamster.com/movies/7263980/la_mia_vicina.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 3.4.5 - Linux-4.4.26-gentoo-x86_64-Intel-R-_Xeon-R-_CPU_E5-2630_0_@_2.30GHz-with-gentoo-2.3
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xhamster.py", line 85, in _real_extract
    webpage, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 768, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 759, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--dump-json', 'https://it.xhamster.com/movies/7259962/la_sorellina_vergine.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 3.4.5 - Linux-4.4.26-gentoo-x86_64-Intel-R-_Xeon-R-_CPU_E5-2630_0_@_2.30GHz-with-gentoo-2.3
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
Array
(
    [title] => La Sorellina Vergine
    [url] => http://2.xhcdn.com/key=bE6KDHwQt3Wdp5uIl6lSFg,end=1488040759,limit=3/data=185.46.229.159-dvp/speed=150k/initial_buffer=3540368/7259962.mp4
    [description] => La Sorellina Vergine
    [keywords] =>
)
--2017-02-25 13:39:19--  http://2.xhcdn.com/key=bE6KDHwQt3Wdp5uIl6lSFg,end=1488040759,limit=3/data=185.46.229.159-dvp/speed=150k/initial_buffer=3540368/7259962.mp4
Resolving 2.xhcdn.com... 88.208.9.4
Connecting to 2.xhcdn.com|88.208.9.4|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://ip47689061.ahcdn.com/key=gkITc9lQoNwq2iVIt7fPcg,end=1488040759,limit=3/data=185.46.229.159-dvp/state=uS7l/buffer=750000:3540368,4559.6/speed=150000/reftag=5412162/1/21/6/47273436/7259962.mp4 [following]
--2017-02-25 13:39:19--  http://ip47689061.ahcdn.com/key=gkITc9lQoNwq2iVIt7fPcg,end=1488040759,limit=3/data=185.46.229.159-dvp/state=uS7l/buffer=750000:3540368,4559.6/speed=150000/reftag=5412162/1/21/6/47273436/7259962.mp4
Resolving ip47689061.ahcdn.com... 176.56.189.230
Connecting to ip47689061.ahcdn.com|176.56.189.230|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 254546527 (243M) [video/mp4]
Saving to: ‘/var/www/videopornoitalia.it/htdocs/content/58b17af789a92.mp4’

             /var/www/videoporno   1%[>
On your serveur youtub-dl binary is up to date :

@nc1159 ~ $ youtube-dl -U
youtube-dl is up-to-date (2017.02.24.1)

**Comment by dstftw** [comment]
>Questo video è visibile solo dagli amici di marcoalfa123456

**Comment by video2000** [comment]
sorry I do not understand why you have closed the ticket I have a problem with youtube-dl 

    Il Sabato 25 Febbraio 2017 14:20, Sergey M. <notifications@github.com> ha scritto:
 

 
Questo video è visibile solo dagli amici di marcoalfa123456

**Comment by dstftw** [comment]
This is what reported by https://it.xhamster.com/movies/7263980/la_mia_vicina.html.
