### ISSUE TITLE
facebook parser downloading incorrect video

### ISSUE THREAD

**Issue by dehylton** [rg3/youtube-dl#12273]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-n', '--merge-output-format', 'mkv', '-v', 'facebook:2607618319261211']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 3.4.4 - Darwin-16.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 2607618319261211: Downloading webpage
WARNING: unable to extract uploader; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Invoking downloader on 'https://video-atl3-1.xx.fbcdn.net/v/t42.1790-2/16918869_2617053721651004_8294026558079762432_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfODU0X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ==&oh=60e75fa445aa5c459c9a51e2d50c4b41&oe=58B285E7'
[download] Destination: UNILAD. 26,204,203 likes · 37,551,979 talking about this. Snapchat - uniladsn...-2607618319261211.f2617053688317674v.mp4
[download] 100% of 19.06MiB in 00:10
[debug] Invoking downloader on 'https://video-atl3-1.xx.fbcdn.net/v/t42.1790-2/16869623_2617052701651106_3854550178258223104_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNDI2X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfYXVkaW8ifQ==&oh=822226d9913029ccf8352259b0616c56&oe=58B2835A'
[download] Destination: UNILAD. 26,204,203 likes · 37,551,979 talking about this. Snapchat - uniladsn...-2607618319261211.f2617052691651107ad.m4a
[download] 100% of 1.30MiB in 00:00
[ffmpeg] Merging formats into "UNILAD. 26,204,203 likes · 37,551,979 talking about this. Snapchat - uniladsn...-2607618319261211.mkv"
[debug] ffmpeg command line: ffmpeg -y -i 'file:UNILAD. 26,204,203 likes · 37,551,979 talking about this. Snapchat - uniladsn...-2607618319261211.f2617053688317674v.mp4' -i 'file:UNILAD. 26,204,203 likes · 37,551,979 talking about this. Snapchat - uniladsn...-2607618319261211.f2617052691651107ad.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:UNILAD. 26,204,203 likes · 37,551,979 talking about this. Snapchat - uniladsn...-2607618319261211.temp.mkv'
Deleting original file UNILAD. 26,204,203 likes · 37,551,979 talking about this. Snapchat - uniladsn...-2607618319261211.f2617053688317674v.mp4 (pass -k to keep)
Deleting original file UNILAD. 26,204,203 likes · 37,551,979 talking about this. Snapchat - uniladsn...-2607618319261211.f2617052691651107ad.m4a (pass -k to keep)
```

---

### Description of your *issue*, suggested solution and other information

currently, downloading incorrect videos from facebook. as of yesterday, a recent (january) version of ytd downloaded the correct video but failed to extract the video name. so i updated to current, and now ytd is downloading the incorrect video (though it now handles the video name again - the one which matches the incorrect video).

**Comment by yan12125** [comment]
Now it can't parse any data. Please move on to #12323 for further discussions.
