### ISSUE TITLE
Youtube-dl is very slow

### ISSUE THREAD

**Issue by BurningPixels** [rg3/youtube-dl#12270]
Can someone help me?
https://youtu.be/ndyNfsQbMQQ

**Comment by yan12125** [comment]
Wild guess: --force-ipv4

If it doesn't work, paste the result of ```strace -tt -f youtube-dl <the URL>```

**Comment by BitLooter** [comment]
Having a similar issue, --force-ipv4 fixed it.

**Comment by BurningPixels** [comment]
--force-ipv4 doesn't work (btw i disabled ipv6 for my network interface)

**Comment by yan12125** [comment]
Could you run the strace command and paste/upload results?

**Comment by BurningPixels** [comment]
Can you help me? I tryed to catch the output with tee and with > but nothing worked

**Comment by hedii** [comment]
@yan12125 I am experiencing the same lag with youtube-dl since 1 or 2 weeks on a server, not on my personal computer.
Here is the strace from my server (big file): https://gist.github.com/hedii/c2023994202cabdf53053b411bc0af15

--force-ipv4 didn't speed up anything

**Comment by hedii** [comment]
(server is running on ubuntu 16.04 lts, youtube-dl installed from pip)

**Comment by yan12125** [comment]
@BurningPixels Sorry for the late response. This should work:
```
strace youtube-dl "http://xxx" >& strace-log.txt
```

**Comment by dstftw** [comment]
Closing due to no response.

**Comment by tonydiep** [comment]
--force-ipv4 fixed it for me as well.

**Comment by laravelish** [comment]
--force-ipv4 makes it blazing fast

**Comment by ksaj** [comment]
I've been trying to debug this for weeks, since the symptom just sort of sprung up out of nowhere. I use it to download guitar backing tracks (the guitar version of karaoke, I suppose) so I can record my jams and do the personal-critique thing. The --force-ipv4 arg worked for me. Going to add that as an alias so I don't have to think about it anymore.

Thanks yan12125!

**Comment by blacpythoz** [comment]
works for me..

**Comment by barisyesilcimen** [comment]
not works for me. i tested youtube-dl 3 vps (Linode, Scaleway) with diffrent commands. Youtube-dl downloading 130-150 kb/s.

**Comment by sirx** [comment]
ytdl also slow for me tested on 1gbit server also tried with --force-ipv4 but changed nothing, does youtube limit?

**Comment by hmenke** [comment]
@yan12125 Very interesting.  Can you please explain *why* `--force-ipv4` fixes this problem?

**Comment by barisyesilcimen** [comment]
tried 30-40 diffrent commands and nothing. 50-190 kbps/s.

**Comment by Hrxn** [comment]
Yes, it's rate limited by YouTube.

**Comment by max1220** [comment]
I recently was having issues like this, and what solved it form me was passing "--format best"(Tested on my VPS and PC). I think that's because if youtube-dl fetches the "normal" browser formats, the connection isn't metered. Maybe that's todo with how they organize caching for the media.

**Comment by cbaggers** [comment]
@max1220's suggestion of `--format best` worked for me

**Comment by hedii** [comment]
@cbaggers @max1220 it is not a solution, because with `--format best` you cannot be 100% sure of the resulting file extension (what if i always want .mp4 best quality).

**Comment by cbaggers** [comment]
@hedii Great point, I should clarify that this isnt the solution, just  another datapoint  to @max1220's comment.
