### ISSUE TITLE
Pluralsight no longer working

### ISSUE THREAD

**Issue by glinkot** [rg3/youtube-dl#12277]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\penny>youtube-dl --version
2017.02.24.1

C:\Users\penny>C:\temp\youtube-DL\youtube-dl.exe --verbose --download-archive "C:\temp\Youtube-DL\Angular 2 Fundamentals
\dlarchive.txt"  --username myUserName --password myPassword --sleep-interval 70 -o "C:\temp\Youtube-DL\Angular
2 Fundamentals/%(autonumber)s - %(title)s.%(ext)s" https://app.pluralsight.com/library/courses/angular-fundamentals/tabl
e-of-contents
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--download-archive', 'C:\\temp\\Youtube-DL\\Angular 2 Fundamentals\\dlarchive.
txt', '--username', 'PRIVATE', '--password', 'PRIVATE', '--sleep-interval', '70', '-o', 'C:\\temp\\Youtube-DL\\Angular 2
 Fundamentals/%(autonumber)s - %(title)s.%(ext)s', 'https://app.pluralsight.com/library/courses/angular-fundamentals/tab
le-of-contents', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.11.08.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] angular-fundamentals: Downloading course JSON
[pluralsight:course] angular-fundamentals: Downloading course data JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on
https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", lin
e 404, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\YoutubeDL.py", line 2001,
 in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

---


### Description of your *issue*, suggested solution and other information

Pluralsight worked fine with this command line a few weeks ago, but I guess the JSON structure has changed.  I now get the above error.  I have an individual account (so it isn't the issue I saw elsewhere in the log where people were trying free and corporate accounts).  The works fine for other purposes, and I've used this exact commandline successfully in the past.  

Many thanks!

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by glinkot** [comment]
Apologies.  The one in my 'path' was updated but not the explicit one I called in the command line.  Sorry for wasting your time :(
