### ISSUE TITLE
instagram - patch to deal with images with wrong "video" type

### ISSUE THREAD

**Issue by trson** [rg3/youtube-dl#12284]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

Sometimes an instagram profile contains an image which is wrongly described in the json data as having `type: video`, instead of `type: image`. (On the website these are displayed as images with a little square icon in the top-right corner, dunno what that means)

When youtube-dl runs into one of these images, it aborts with the following error:

```
ERROR: An extractor error has occurred. (caused by KeyError('videos',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/instagram.py", line 264, in _real_extract
    } for k, v in it['videos'].items()]

KeyError: 'videos'
```

This happens because the "fake" video item is in fact an image, so it doesn't have the `videos` json element (which describes the available video formats and urls for the item).

For a quick fix: add a check for existence of the `videos` element, see the attached patch for `/extractor/instagram.py`

(This works for me, I'm not sure if other changes are needed/better, please review).

[instagram.py.txt](https://github.com/rg3/youtube-dl/files/802267/instagram.py.txt)

**Comment by dstftw** [comment]
1. Provide example URL.
2. If you want this to be merged you have to add a test and open a pull request.

**Comment by yan12125** [comment]
Closing as no response for a long time.
