### ISSUE TITLE
how to have best quality, but mp4, not mkv?

### ISSUE THREAD

**Issue by rediscu** [rg3/youtube-dl#12299]
Hello! Please help me with this: 
I want to download YT playlist with best quality video and audio (OPUS should be better than default 128k m4a commonly used with 1080p video),
and merge it to _mp4_ container instead of mkv. What command should I use
to dl both streams, convert audio and merge?

**Comment by yan12125** [comment]
See the first example in https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection-examples

**Comment by rediscu** [comment]
yan12125: In this example I'll have best m4a audio (usually 125k), but i want to dl OPUS (which, I believe is better), convert it to m4a using ffmpeg and merge with mp4 video

**Comment by yan12125** [comment]
Sorry I misread your question. Currently it's impossible with command line only because merge (```FFmpegMergerPP```) always occurs before format conversion. (```FFmpegVideoConvertorPP```)

**Comment by rediscu** [comment]
@yan12125 may be it's possible in two or more batch passes?

**Comment by yan12125** [comment]
I don't think there's a simple way because ```FFmpegMergerPP``` relies on the relationship between format_id (itag) and file extensions for correct merging, yet ```FFmpegVideoConvertorPP``` changes this relationship.

**Comment by yan12125** [comment]
Here's a workaround: merge it into mkv and convert to mp4. ```-vcodec copy``` guarantees that re-encoding occurs in audio tracks only.
```
youtube-dl -v 9SF5NcELH9E -f 'bestvideo[ext=mp4]+bestaudio[acodec=opus]' --recode-video mp4 --postprocessor-args '-vcodec copy'
```

**Comment by rediscu** [comment]
@yan12125 having this: 
![q](https://cloud.githubusercontent.com/assets/26082520/23401814/18449c34-fdba-11e6-9dce-16e33794c495.png)

**Comment by yan12125** [comment]
Ah, on Windows you need double quotes instead of single quotes.

**Comment by rediscu** [comment]
@yan12125 ok, that worked, but I'm having the same audio bitrate that I tried to avoid ~128k

used this command: youtube-dl -v lL7vgDRZxfo -f "bestvideo[ext=mp4]+bestaudio[acodec=opus]" --recode-video mp4 --audio-quality 256k --postprocessor-args "-vcodec copy"

**Comment by yan12125** [comment]
For lL7vgDRZxfo, Youtube does not provide a format higher than ~130k.

FYI: --audio-quality is an option for --extract-audio. It does not make sense to specify higher bitrates than the original.

**Comment by rediscu** [comment]
@yan12125  it has 251 webm 153k opus@160k 
afaik opus compression is more effective than m4a, so transcoding opus to m4a with higher bitrate than original opus makes sence

**Comment by yan12125** [comment]
> 251 webm 153k opus@160k

YouTube seldom gives correct numbers in those fields.

> opus compression is more effective than m4a, so transcoding opus to m4a with higher bitrate than original opus makes sence

Got it. This should work:
```
youtube-dl -v lL7vgDRZxfo -f "bestvideo[ext=mp4]+bestaudio[acodec=opus]" --recode-video mp4 --keep-video --postprocessor-args "-vcodec copy -b:a 256k"
```

**Comment by rediscu** [comment]
Looks like I have better audio specrum now  (16-20 khz is not killed anymore). Thank you very much, @yan12125 !

**Comment by yan12125** [comment]
Glad that works. As existing options suffice and they're not super complicated, I'll close this.
