### ISSUE TITLE
[Miomio] Downloader invocation on http://hdus.qqfire.com/ fails

### ISSUE THREAD

**Issue by SamuSoft** [rg3/youtube-dl#12291]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
```
$ youtube-dl -v http://www.miomio.tv/watch/cc312326/
[debug] System config: [u'-o', u'~/Movies/%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.miomio.tv/watch/cc312326/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 2.7.13 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[miomio.tv] 312326: Downloading webpage
[miomio.tv] 312326: Downloading player webpage
[debug] Invoking downloader on u'http://hdus.qqfire.com/789BB66D3FF62017136B28A7B67F02149173170226MTQ4ODE0MzkzYzIxNzJkZjBjMTQ5MT149173148814393500482E89603C021B.ic'
ERROR: unable to download video data: <urlopen error [Errno 60] Operation timed out>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1733, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2093, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 918, in http_open
    req)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 60] Operation timed out>
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

Derrived from issue #12170, since the downloader invocation fails on the the newly used video server hdus.qqfire.com

**Comment by yan12125** [comment]
Can you watch it in browsers (Chrome/Firefox/...)?

**Comment by SamuSoft** [comment]
Yes, it plays without problems on Safari(10.0.3) and on a clean install of Firefox(51.0.1)

**Comment by yan12125** [comment]
Well, I get no video in a clean Firefox 51

**Comment by SamuSoft** [comment]
I had to refresh once or twice to get it streaming though on Firefox, but Safari works right of the bat

**Comment by yan12125** [comment]
Refresh several times on both Sierra and Firefox but still no videos.

**Comment by SamuSoft** [comment]
There seems to be some videos that require specific plug-ins, but this shouldn't have been one of these. For example: 
Works for me:
http://www.miomio.tv/watch/cc313610/

Doesn't work:
http://www.miomio.tv/watch/cc313254/

Once the picture of the video loads, you should press play and then wait for a while (sometimes up to 5 minutes for me)

As for now there is also a new problem with the webpage downloader, detailed in issue #12388

**Comment by yan12125** [comment]
Thanks this will be fixed in the next issue. Now http://www.miomio.tv/watch/cc312326/ reports a 404 error when loading the video, so this issue is no longer valid.
