### ISSUE TITLE
Question about Crunchyroll

### ISSUE THREAD

**Issue by BridgeUK** [rg3/youtube-dl#12290]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24.1**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Question

---

Hi, this is just a quick question not related to youtube-dl, if anyone could help it would be most appreciated, I have a premium crunchyroll account, I'm logged in at the moment, I'd like to download a few episodes in a different resolution to what youtube-dl downloaded, could anyone tell me please if there is an addon for chrome or firefox that will show me the location of the video files so I can manually download them in the resolution I'm after, thank you very much.

**Comment by yan12125** [comment]
IRC is a better place for non-youtube-dl questions. See https://github.com/rg3/youtube-dl/blob/master/README.md#bugs for more about IRC.

**Comment by BridgeUK** [comment]
thanks
