### ISSUE TITLE
get video=720p if not available then lower quality

### ISSUE THREAD

**Issue by nedz14** [rg3/youtube-dl#12308]
How to get video=720p if not available then lower quality  + best audio, cause my pc is not equipped to handle 1080p or more.
i need an option line for mpv.
thnx

**Comment by dstftw** [comment]
Read [FAQ](https://github.com/rg3/youtube-dl#format-selection-examples).

**Comment by nedz14** [comment]
i read FAQ 
Thats All I Could Come Up With,
--ytdl-format=136+bestaudio
it download only 720p.

**Comment by nedz14** [comment]
I found it.
Download best format available but not better that 720p
youtube-dl -f 'bestvideo[height<=720]+bestaudio/best[height<=720]'
thx
