### ISSUE TITLE
[douyu.com] HTTP error 403: Forbidden

### ISSUE THREAD

**Issue by stevencsc** [rg3/youtube-dl#12301]

**Comment by hewenping1996** [comment]
The same issue with you.
end with 

- ERRO:Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()).

However,It worked pretty good last night /smugshrug

**Comment by yan12125** [comment]
Thanks for the report. It will be fixed in the next version.

**Comment by yan12125** [comment]
Note that ffmpeg doesn't support live streams well. livestreamer/streamlink has better support for that. For example:
```
streamlink --player=mpv hls://$(youtube-dl -g <douyu URL>) best
```

Related: #9349
