### ISSUE TITLE
[YouTube]youtube-dl.exe: error: You must provide at least one URL

### ISSUE THREAD

**Issue by gabriellluz** [rg3/youtube-dl#12302]
Hi, I can't download YouTube playlists anymore.

My command line:

`youtube-dl -i -w --username gabrielluz --password 123456 --format m4a -o "D:/DropBox/DropBox/YTTempGAB/%(playlist)s/%(title)s.%(ext)s" https://www.youtube.com/playlist?list=PLH_sdszYGo1nsOe2CoSF4WvOH5QDWlGEB`

It always worked. Now it's not working anymore. Yes, it is updated.
The output is:

`youtube-dl.exe: error: You must provide at least one URL.`

It's weird because it always worked. I run it as a task every hour on Windows.

**Comment by Hrxn** [comment]
Enclose the URL with double quotation marks?

**Comment by gabriellluz** [comment]
I've tried this to no avail. I had to create a config file for this.

`youtube-dl -i --no-overwrites --ignore-errors -u gabito -p 123456 -f m4a --config-location D:/AUTO/gabyoutube.conf "http://www.youtube.com/playlist?list=PLH_sdszYGo1nsOe2CoSF4WvOH5QDWlGEB"`

Now it works. But it was working last month which was the last time I ran this batch file.

**Comment by dstftw** [comment]
Post the complete verbose output of the command that fails.

**Comment by heyhler** [comment]
I am having the same issue on 2019.08.13:




## Checklist



- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones
#12302 is similar. 

## Verbose log

Sorry for any gross formatting, this is from iSH
```
youtube-dl -F --verbose 'https://m.youtube.com/watch?v=3PYBusAsn3Y'                              
[debug] System config: []                              
[debug] User config: []                                
[debug] Custom config: []                              
[debug] Command-line args: [u'-F', u'--verbose', u'http
s://m.youtube.com/watch?v=3PYBusAsn3Y']                
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, p
ref UTF-8                                              
[debug] youtube-dl version 2019.08.13                  
[debug] Python version 2.7.16 (CPython) - Linux-3.2.0-i
sh-i686-with                                           
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3      
[debug] Proxy map: {}                                  
[youtube] 3PYBusAsn3Y: Downloading webpage             
ERROR: Unable to download webpage: <urlopen error [Errn
o -3] Try again> (caused by URLError(gaierror(-3, 'Try 
again'),))                                             
  File "/usr/lib/python2.7/site-packages/youtube_dl/ext
ractor/common.py", line 627, in _request_webpage       
    return self._downloader.urlopen(url_or_request)    
  File "/usr/lib/python2.7/site-packages/youtube_dl/You
tubeDL.py", line 2229, in urlopen                      
    return self._opener.open(req, timeout=self._socket_
timeout)                            
 File "/usr/lib/python2.7/urllib2.py", line 429, in op
en                                                     
    response = self._open(req, data)                   
  File "/usr/lib/python2.7/urllib2.py", line 447, in _o
pen                                                    
    '_open', req)                                      
  File "/usr/lib/python2.7/urllib2.py", line 407, in _c
all_chain                                              
    result = func(*args)                               
  File "/usr/lib/python2.7/site-packages/youtube_dl/uti
ls.py", line 2724, in https_open                       
    req, **kwargs)                                     
  File "/usr/lib/python2.7/urllib2.py", line 1198, in d
o_open                                                 
    raise URLError(err)                                
```


## Description

This is specific to this video. 

Not sure why I'm encountering this issue. I'm trying to get the format codes so I can just download the audio. I am also having this issue on 2019.08.02. When I just try to download the video on its own, I also get this error.

**Comment by alxobr** [comment]
> Enclose the URL with double quotation marks?

Worked with version 2019.10.22
