### ISSUE TITLE
Double underscores in the value of %(uploader_id)s are truncated

### ISSUE THREAD

**Issue by Ectomind1990** [rg3/youtube-dl#12317]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.28*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.28**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v --skip-download -o '%(uploader_id)s/%(id)s.%(ext)s' https://youtu.be/nmeZVeXo7O4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--skip-download', u'-o', u'%(uploader_id)s/%(id)s.%(ext)s', u'https://youtu.be/nmeZVeXo7O4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.28
[debug] Python version 2.7.12 - Linux-4.4.0-64-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] nmeZVeXo7O4: Downloading webpage
[youtube] nmeZVeXo7O4: Downloading video info webpage
[youtube] nmeZVeXo7O4: Extracting video information
[youtube] {22} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {43} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {18} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {36} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {17} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {137} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {248} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {136} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {247} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {135} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {244} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {134} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {243} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {133} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {242} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {160} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {278} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {140} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {171} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {249} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {250} signature length 40.44, html5 player en_US-vflVlxFvV
[youtube] {251} signature length 40.44, html5 player en_US-vflVlxFvV
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

When using Output Templates, if the value of `%(uploader_id)s` should contain a double underscore, the actual behaviour is as if there is only a single underscore at that position.

This can be seen in the command I gave above.  It creates a directory named...
`UC_Bdma6rGmzx9EBtSCQNpQ` but it **should** be named...
`UC__Bdma6rGmzx9EBtSCQNpQ`

YouTube's Channel IDs are always 24 characters long, so clearly the single underscore version is wrong.  You can also demonstrate that it is wrong by trying these two URLs:
https://www.youtube.com/channel/UC_Bdma6rGmzx9EBtSCQNpQ
https://www.youtube.com/channel/UC__Bdma6rGmzx9EBtSCQNpQ
The single underscore URL gives the following error: "This channel does not exist."

### Additional Info

If you use  **--write-info-json**, the values of the `uploader_id` and `uploader_url` fields in the JSON file are *not* affected by the bug.  The value of the `_filename` field *is* affected.

It is not just directory creation that is affected by this bug.  If you use a different Output Template so that the value of `%(uploader_id)s` gets included in the filename, you still see the bug.

YouTube's [Channel IDs](https://support.google.com/youtube/answer/3250431?hl=en) always start with "UC".  The channel I've given as an example is UC__Bdma6rGmzx9EBtSCQNpQ - in which the double underscore comes immediately after the "UC".  But the bug still happens when the double underscore is found at other positions. E.g. channel UCtk1Yv__Jcsw2NWbmZcCqsA

**Comment by glenn-slayden** [comment]
I can confirm that this bug also affected the `%(channel_id)s` feature (see [#9676](https://github.com/rg3/youtube-dl/issues/9676)), and that commit [40df485](https://github.com/rg3/youtube-dl/commit/40df485f554ec3fff81ca988b5bf961d54d8e41b) fixes it.
