### ISSUE TITLE
Bug on vorbis quality option

### ISSUE THREAD

**Issue by pprw** [rg3/youtube-dl#12312]
Hi,

The audio quality seems to works backward.  I obtained a bigger file with the worse quality setting than with the better (for vorbis)  

>--audio-quality QUALITY
>        Specify ffmpeg/avconv audio quality, insert a value between 0 (better) and 9 (worse) for  VBR
>        or a specific bitrate like 128K (default 5)
> 

`youtube-dl -x --audio-format vorbis --audio-quality 0 https://www.youtube.com/watch?v=oDoegcuUBfk  `

gives me a 6.3Mo ogg file with 64 kbits/s.

`youtube-dl -x --audio-format vorbis --audio-quality 9 https://www.youtube.com/watch?v=oDoegcuUBfk `

gives me a 26.9Mo ogg file with 320 kbits/s.

Shouldn't it be the opposite?

**Comment by dstftw** [comment]
The description is for mp3 VBR. For vorbis it's opposite. In general it's container specific.

**Comment by pprw** [comment]
Ok, it could be worthy to put this information in the man page don't you think?  ffmpeg/avconv audio quality does not mean mp3 VBR.
