### ISSUE TITLE
youtube rental video not supported

### ISSUE THREAD

**Issue by GaelicGrime** [rg3/youtube-dl#12324]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.28*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.28**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
_will_ on _deskwill_ [20170302.0147] ~/.config/youtube-dl U_ youtube-dl --verbose "https://www.youtube.com/watch?v=bG9WIDkuh6g" &>~/.config/youtube-dl/rentalerror.txt

[debug] System config: []
[debug] User config: [u'--output', u'/storage/media/%(extractor)s/[u-%(uploader)s]/[c-%(creator)s]/%(title)s_%(autonumber)s_%(id)s.%(ext)s', u'--no-progress', u'--ignore-errors', u'--restrict-filenames', u'--autonumber-size', u'4', u'--continue', u'--write-description',$
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=bG9WIDkuh6g']
WARNING: --autonumber-size is deprecated. Use output template with %(autonumber)0Nd, where N in the number of digits instead.
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2017.02.28
[debug] Python version 2.7.9 - Linux-4.9.0-0.bpo.1-amd64-x86_64-with-debian-8.7
[debug] exe versions: avconv v13_dev0-733-g7ff018c, avprobe v13_dev0-733-g7ff018c, ffmpeg 2.6.9, ffprobe 2.6.9, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] bG9WIDkuh6g: Downloading webpage
[youtube] bG9WIDkuh6g: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: "rental" videos not supported; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1457, in _real_extract
    raise ExtractorError('"rental" videos not supported')
ExtractorError: "rental" videos not supported; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.



---

---

I notice several closed, and am really just doing as told by the errors, this was found in a playlist, and will stop without the --ignore-errors (which I have started putting in my config file because of the number of times I have seen the same error recently).

Perhaps a way to recognize and totally ignore such videos, especially on youtube, that seems to be the only place I have seen them that has a list capability.

**Comment by yan12125** [comment]
Please move on to #359 for further discussions. All other issues are closed because they are duplicates.

> am really just doing as told by the errors

Indeed a better message is necessary
