### ISSUE TITLE
[youtube] issue with downloading a 9 hour vid

### ISSUE THREAD

**Issue by johny1** [rg3/youtube-dl#12326]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.28*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.28**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
I'm having an issue with downloading this video.

https://www.youtube.com/watch?v=UxRg9Fgxios

It only downloads a portion of it and then stops. I tried multiple times. Other long videos from the same channel seem to DL fine.

Here's the log, as you see it downloaded about 400mb and then stopped. i tried it again with the -v option and it said it already downloaded the file.

C:\Users\User\Desktop\ytdl>youtube-dl https://www.youtube.com/watch?v=UxRg9Fgxios

[youtube] UxRg9Fgxios: Downloading webpage
[youtube] UxRg9Fgxios: Downloading video info webpage
[youtube] UxRg9Fgxios: Extracting video information
[youtube] UxRg9Fgxios: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mk
v.
[dashsegments] Total fragments: 229
[download] Destination: 2017 Bathurst 12 Hour - Top 10 Shoot Out and Support Cat
egories-UxRg9Fgxios.f137.mp4
[download] 100% of 66.23MiB in 01:04
[download] Destination: 2017 Bathurst 12 Hour - Top 10 Shoot Out and Support Cat
egories-UxRg9Fgxios.f251.webm
[download] 100% of 392.32MiB in 01:34
[ffmpeg] Merging formats into "2017 Bathurst 12 Hour - Top 10 Shoot Out and Supp
ort Categories-UxRg9Fgxios.mkv"
Deleting original file 2017 Bathurst 12 Hour - Top 10 Shoot Out and Support Cate
gories-UxRg9Fgxios.f137.mp4 (pass -k to keep)
Deleting original file 2017 Bathurst 12 Hour - Top 10 Shoot Out and Support Cate
gories-UxRg9Fgxios.f251.webm (pass -k to keep)

C:\Users\User\Desktop\ytdl>youtube-dl -v https://www.youtube.com/watch?v=UxRg9Fgx
ios
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=UxRg9Fgxios']

[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.28
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-77234-g906c0b7
[debug] Proxy map: {}
[youtube] UxRg9Fgxios: Downloading webpage
[youtube] UxRg9Fgxios: Downloading video info webpage
[youtube] UxRg9Fgxios: Extracting video information
[youtube] UxRg9Fgxios: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mk
v.
[download] 2017 Bathurst 12 Hour - Top 10 Shoot Out and Support Categories-UxRg9
Fgxios.mkv has already been downloaded and merged

Can anyone try downloading this vid and see if it works for them?

Thanks.

**Comment by dstftw** [comment]
All mp4 formats served for this video are truncated at 00:19:23 while webms are complete. mp4 happens to be the `bestvideo` format for this video that's why you get a video file of 00:19:23 length. Select webm format to download full video. Similar issue #11847.
