### ISSUE TITLE
npo.nl stopped working

### ISSUE THREAD

**Issue by vandenoever** [rg3/youtube-dl#12320]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.28*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.28**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ env -u http_proxy -u https_proxy youtube-dl --no-call-home --verbose --continue http://www.npo.nl/pauw-jinek-de-verkiezingen/27-02-2017/KN_1689019
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--no-call-home', u'--verbose', u'--continue', u'http://www.npo.nl/pauw-jinek-de-verkiezingen/27-02-2017/KN_1689019']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.28
[debug] Python version 2.7.13 - Linux-4.4.50-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 3.1.7, ffprobe 3.1.7, rtmpdump 2.4
[debug] Proxy map: {}
[npo] KN_1689019: Downloading JSON metadata
[npo] KN_1689019: Downloading token
ERROR: Unable to download webpage: HTTP Error 410: Gone (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/nix/store/xj21si5rdv56hi5b3bgc6c16ic81viz8-youtube-dl-2017.02.28/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 496, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/nix/store/xj21si5rdv56hi5b3bgc6c16ic81viz8-youtube-dl-2017.02.28/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2093, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/nix/store/l4v7h3zaiffrnqfqzy60f14h0s1mcp7a-python-2.7.13/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/nix/store/l4v7h3zaiffrnqfqzy60f14h0s1mcp7a-python-2.7.13/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/nix/store/l4v7h3zaiffrnqfqzy60f14h0s1mcp7a-python-2.7.13/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/nix/store/l4v7h3zaiffrnqfqzy60f14h0s1mcp7a-python-2.7.13/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/nix/store/l4v7h3zaiffrnqfqzy60f14h0s1mcp7a-python-2.7.13/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by vandenoever** [comment]
@dstftw Which bug is this a duplicate to? I'd like to follow it. I do not see other sites that give `Unable to download webpage: HTTP Error 410: Gone`.

**Comment by supercoil** [comment]
Duplicate of #12311 Version 2017-03-02 fixes this issue.
