### ISSUE TITLE
Error when ffmpeg merging downloads into mp4

### ISSUE THREAD

**Issue by TimeCompass** [rg3/youtube-dl#12329]
Archlinux 4.9.11 using youtube-dl 2017.02.28

At first I'm using youtube-dl's  AUR package,  and get an 'AtomicParsley error'
Googled it and 'pacman -S atomicparsley' solved it, then I get 'Last message repeated 1 times' error.
I have tried other youtube videos and everything goes right.
After that I removed the AUR package and download the latest version on github.
Still get this error.

```
$ /usr/local/bin/youtube-dl https://www.youtube.com/watch?v=LMGMdSMAfYE --verbose
[debug] System config: []
[debug] User config: ['--ignore-errors', '--geo-bypass', '--skip-unavailable-fragments', '--hls-prefer-ffmpeg', '--external-downloader', 'aria2c', '--continue', '--no-overwrites', '--write-thumbnail', '--no-warnings', '--no-check-certificate', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', '--referer', 'https://www.youtube.com', '--youtube-skip-dash-manifest', '--merge-output-format', 'mp4', '--format', 'bestvideo+bestaudio/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--yes-playlist', '--no-resize-buffer', '--no-cache-dir', '--prefer-insecure', '--prefer-ffmpeg', '--output', '/home/hibiki/youtube/%(title)s-%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=LMGMdSMAfYE', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.28
[debug] Python version 3.6.0 - Linux-4.9.11-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] LMGMdSMAfYE: Downloading webpage
[youtube] LMGMdSMAfYE: Downloading video info webpage
[youtube] LMGMdSMAfYE: Extracting video information
[youtube] LMGMdSMAfYE: Thumbnail is already present
[debug] Invoking downloader on 'http://r13---sn-i3b7knel.googlevideo.com/videoplayback?key=yt6&source=youtube&pl=24&mime=video%2Fwebm&beids=%5B9452306%5D&signature=9914A005E1579DB352374F1E0F16B7D0C523008E.0B7CD4A2AE700B613C43876DDCF411FEB7F15713&itag=247&gir=yes&sparams=clen%2Cdur%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Csource%2Cupn%2Cexpire&mn=sn-i3b7knel&ipbits=0&mm=31&id=o-AOJPZkl3U9L55LVZu3azOP2p_oWdUnbrTzLhZrcVEgf1&mv=u&dur=1883.400&mt=1488466650&ms=au&ip=14.136.211.86&clen=182167207&lmt=1482659042544723&expire=1488488470&upn=Kt7mpxrJ4-I&ratebypass=yes'
[download] /home/hibiki/youtube/【艦これ】残響ノ鎮魂歌【響のオリジナル曲】＜キネマ106＞-LMGMdSMAfYE.f247.webm has already been downloaded
[download] 100% of 173.73MiB
[debug] Invoking downloader on 'http://r13---sn-i3b7knel.googlevideo.com/videoplayback?key=yt6&source=youtube&pl=24&mime=audio%2Fwebm&beids=%5B9452306%5D&signature=A04E168A9B3A54EBFF96BA000EBA106B69521257.7BC76E0FBA953A72B79D47953BD4D141ACBFBBC4&itag=251&gir=yes&sparams=clen%2Cdur%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Csource%2Cupn%2Cexpire&mn=sn-i3b7knel&ipbits=0&mm=31&id=o-AOJPZkl3U9L55LVZu3azOP2p_oWdUnbrTzLhZrcVEgf1&mv=u&dur=1883.481&mt=1488466650&ms=au&ip=14.136.211.86&clen=31451764&lmt=1482655135021461&expire=1488488470&upn=Kt7mpxrJ4-I&ratebypass=yes'
[download] /home/hibiki/youtube/【艦これ】残響ノ鎮魂歌【響のオリジナル曲】＜キネマ106＞-LMGMdSMAfYE.f251.webm has already been downloaded
[download] 100% of 29.99MiB
[ffmpeg] Merging formats into "/home/hibiki/youtube/【艦これ】残響ノ鎮魂歌【響のオリジナル曲】＜キネマ106＞-LMGMdSMAfYE.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:/home/hibiki/youtube/【艦これ】残響ノ鎮魂歌【響のオリジナル曲】＜キネマ106＞-LMGMdSMAfYE.f247.webm' -i 'file:/home/hibiki/youtube/【艦これ】残響ノ鎮魂歌【響のオリジナル曲】＜キネマ106＞-LMGMdSMAfYE.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:/home/hibiki/youtube/【艦これ】残響ノ鎮魂歌【響のオリジナル曲】＜キネマ106＞-LMGMdSMAfYE.temp.mp4'
ERROR:     Last message repeated 1 times
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 444, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 192, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:     Last message repeated 1 times
```

**Comment by yan12125** [comment]
> --merge-output-format mp4

You can't use opus in mp4.

**Comment by mrkapqa** [comment]
i am also getting this error

[ffmpeg] Merging formats into "Alles was Recht ist - Peter I - wie geht es nach der Freilassung nun weiter-LHKrq6XZ6jg.mp4"
ERROR:     Last message repeated 1 times


i am trying to 

youtube-dl --ignore-errors --write-sub -f 'bestvideo[height<=480]+bestaudio/best[height<=480]' https://www.youtube.com/channel/UCdQma4IKtiaZFT8LscKn_sw --embed-subs --merge-output-format mp4



this is my ffmpeg

ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
  configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-librsvg --enable-libtheora --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libsoxr --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-libjack --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libxcb --disable-libxcb-shm --disable-libxcb-xfixes --disable-indev=jack --enable-opencl --disable-outdev=xv --enable-audiotoolbox --enable-videotoolbox --enable-sdl2 --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --arch=x86_64 --enable-x86asm --enable-libx265 --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
