### ISSUE TITLE
[YouTube] Downloading 60fps video as mp4

### ISSUE THREAD

**Issue by sn0wyfall** [rg3/youtube-dl#12337]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I'm want to download a 60fps YouTube video at 1080p or even 2K with audio as a `.mp4` file. However, when I use `-F` to see which formats I can download, it seems like all 60fps options which are 1080p or above are `.webm` files. Is this a limitation with YouTube? Does this mean that it is impossible to download 1080p 60fps video as a `.mp4` directly with YouTube? The reason I ask is that some programs such as 4K Video Downloader download files as `.mp4` files, so I was wondering if the same was possible with youtube-dl.

Sorry for the noobish question!

**Comment by dstftw** [comment]
>it seems like all 60fps options which are 1080p or above are `.webm` files

Incorrect. Here is the example URL with 1080 60fps mp4:
```
> py -3.6 .\youtube_dl\__main__.py https://www.youtube.com/watch?v=Z6lYqgWAmrg -F
[youtube] Z6lYqgWAmrg: Downloading webpage
[youtube] Z6lYqgWAmrg: Downloading video info webpage
[youtube] Z6lYqgWAmrg: Extracting video information
[info] Available formats for Z6lYqgWAmrg:
format code  extension  resolution note
249          webm       audio only DASH audio   53k , opus @ 50k, 1.28MiB
250          webm       audio only DASH audio   67k , opus @ 70k, 1.48MiB
171          webm       audio only DASH audio  107k , vorbis@128k, 2.42MiB
251          webm       audio only DASH audio  119k , opus @160k, 2.84MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 3.49MiB
160          mp4        256x144    144p  110k , avc1.42c00c, 15fps, video only, 2.99MiB
278          webm       256x144    144p  114k , webm container, vp9, 30fps, video only, 2.59MiB
133          mp4        426x240    240p  253k , avc1.4d4015, 30fps, video only, 6.73MiB
242          webm       426x240    240p  267k , vp9, 30fps, video only, 5.59MiB
243          webm       640x360    360p  488k , vp9, 30fps, video only, 10.40MiB
134          mp4        640x360    360p  611k , avc1.4d401e, 30fps, video only, 11.82MiB
244          webm       854x480    480p  916k , vp9, 30fps, video only, 18.84MiB
135          mp4        854x480    480p 1123k , avc1.4d401f, 30fps, video only, 23.11MiB
247          webm       1280x720   720p 1905k , vp9, 30fps, video only, 37.94MiB
136          mp4        1280x720   720p 2253k , avc1.4d401f, 30fps, video only, 44.70MiB
302          webm       1280x720   720p60 3137k , vp9, 60fps, video only, 63.14MiB
248          webm       1920x1080  1080p 3196k , vp9, 30fps, video only, 67.74MiB
298          mp4        1280x720   720p60 3325k , avc1.4d4020, 60fps, video only, 74.19MiB
137          mp4        1920x1080  1080p 4224k , avc1.640028, 30fps, video only, 81.71MiB
303          webm       1920x1080  1080p60 5129k , vp9, 60fps, video only, 109.29MiB
299          mp4        1920x1080  1080p60 5537k , avc1.64002a, 60fps, video only, 128.89MiB
264          mp4        2560x1440  1440p 10125k , avc1.640032, 30fps, video only, 192.97MiB
271          webm       2560x1440  1440p 10498k , vp9, 30fps, video only, 209.84MiB
308          webm       2560x1440  1440p60 14676k , vp9, 60fps, video only, 319.24MiB
266          mp4        3840x2160  2160p 22834k , avc1.640033, 30fps, video only, 491.75MiB
313          webm       3840x2160  2160p 26094k , vp9, 30fps, video only, 483.65MiB
315          webm       3840x2160  2160p60 31943k , vp9, 60fps, video only, 701.52MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
```
If there is no higher resolution 60 fps mp4 listed then no such formats exist for your particular video.

>some programs such as 4K Video Downloader download files as .mp4 files

Did you actually tried to check whether downloaded (and not re-encoded) files are actually 60fps?

**Comment by sn0wyfall** [comment]
@dstftw Well, okay, I meant for 2K and above then I guess. But I'm not sure about whether those downloaded `.mp4`s are 6- fps, now that you mention it. Thank you for your time.
