### ISSUE TITLE
ERROR: Cannot parse data

### ISSUE THREAD

**Issue by vchryssos** [rg3/youtube-dl#12342]
vassilis@dtop:/tmp > youtube-dl --verbose https://www.facebook.com/eggGR/videos/715680401922338
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/eggGR/videos/715680401922338']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.19
[debug] Python version 2.7.6 - Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6
[debug] Proxy map: {}
[facebook] 715680401922338: Downloading webpage
[facebook] 715680401922338: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 671, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/facebook.py", line 308, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/facebook.py", line 238, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by goggle** [comment]
You are using youtube-dl version 2016.04.19, which is almost a year old. Please use the issue template and report bugs only for the newest available youtube-dl version.

**Comment by yan12125** [comment]
@goggle is right. Facebook was just fixed in the latest version.

**Comment by vchryssos** [comment]
Thanx a lot @goggle. The repo I use (Linux Mint 17.3 Rosa) installs the older version. I will search for the latest.

**Comment by Karthik-Rg** [comment]
Am using youtube-dl version 2016.08.13. Need help to resolve this issue.
