### ISSUE TITLE
PluralSight download ERROR

### ISSUE THREAD

**Issue by rgmorato** [rg3/youtube-dl#12345]
Hello.
Since 01/03/2017 the following error I started to have error to download the videos of the site of PluralSight. Today I updated the version of youtube-dl, installed in Ubuntu, and the following error was shown:
_youtube-dl -i -v -u user -p password -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" --all-subs "https://app.pluralsight.com/library/courses/windows-server-2012-mcsa-70-410"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'-v', u'--sleep-interval', u'60', u'--max-sleep-interval', u'100', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-o', u'%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', u'--all-subs', u'https://app.pluralsight.com/library/courses/windows-server-2012-mcsa-70-410']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.02
[debug] Python version 2.7.6 - Linux-3.4.0+-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] windows-server-2012-mcsa-70-410: Downloading course JSON
[download] Downloading playlist: Windows Server 2012 R2 (70-410) MCSA and the 70-410 Exam
[pluralsight:course] playlist Windows Server 2012 R2 (70-410) MCSA and the 70-410 Exam: Collected 13 video ids (downloading 13 of them)
[download] Downloading video 1 of 13
[pluralsight] Downloading login page
[pluralsight] Logging in as rgmorato@hotmail.com
**ERROR:** Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 426, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 384, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 60, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 100, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
**ERROR: '**NoneType' object has no attribute 'copy'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 772, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 950, in process_ie_result
    extra_info=extra)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 845, in process_ie_result
    new_result = info.copy()
AttributeError: 'NoneType' object has no attribute 'copy'_

What could be going wrong?

Thank you!

**Comment by rgmorato** [comment]
And....I can login by website.
![2017-03-03_16-36-19](https://cloud.githubusercontent.com/assets/26164098/23566185/9ce5f614-002f-11e7-8e7b-159863cf2816.jpg)

**Comment by dstftw** [comment]
Add `--dump-pages` and post the output.

**Comment by rgmorato** [comment]
Hi.
The dump file is attached.

[youtube-dl_issue_12345_dump_pages.txt](https://github.com/rg3/youtube-dl/files/817728/youtube-dl_issue_12345_dump_pages.txt)

**Comment by rgmorato** [comment]
How To Get a Free Full Plural Sight Subscription / Download Courses automatically from PluralSight

[https://andrewramzyblog.wordpress.com/2016/04/25/how-to-get-a-free-full-plural-sight-subscription-download-courses-automatically-from-pluralsight/](url)

**Comment by dstftw** [comment]
This is what pluralsight have said to you:
![image](https://cloud.githubusercontent.com/assets/1908898/23566817/12dbb51a-0086-11e7-9a50-a3db9e025508.png)

**Comment by rgmorato** [comment]
Great, resolved!
Thank you!

**Comment by andreifilip** [comment]
Hi @rgmorato 
How did you solved this one.
I did log out and log in again, but nothing happened

Thanks
