### ISSUE TITLE
bestvideo doesn't get best quality video?

### ISSUE THREAD

**Issue by sn0wyfall** [rg3/youtube-dl#12343]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

In the docs, it says:

> `bestvideo`: Select the best quality video-only format

Let's say I find a [4K 60fps video](https://www.youtube.com/watch?v=iNJdPyoqt8U). I put it in youtube-dl and examine what formats exist:

    youtube-dl -F "https://www.youtube.com/watch?v=iNJdPyoqt8U"

```
format code  extension  resolution note
249          webm       audio only DASH audio   58k , opus @ 50k, 1.91MiB
250          webm       audio only DASH audio   90k , opus @ 70k, 2.64MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k (44100Hz), 4.67MiB
251          webm       audio only DASH audio  165k , opus @160k, 5.14MiB
171          webm       audio only DASH audio  171k , vorbis@128k, 5.01MiB
160          mp4        256x144    DASH video  110k , avc1.4d400c, 30fps, video only, 3.85MiB
278          webm       256x144    144p  113k , webm container, vp9, 30fps, video only, 3.47MiB
133          mp4        426x240    DASH video  274k , avc1.4d4015, 30fps, video only, 8.60MiB
242          webm       426x240    240p  275k , vp9, 30fps, video only, 7.39MiB
243          webm       640x360    360p  514k , vp9, 30fps, video only, 13.66MiB
134          mp4        640x360    DASH video  632k , avc1.4d401e, 30fps, video only, 14.50MiB
244          webm       854x480    480p  943k , vp9, 30fps, video only, 24.52MiB
135          mp4        854x480    DASH video 1153k , avc1.4d401f, 30fps, video only, 28.44MiB
247          webm       1280x720   720p 1828k , vp9, 30fps, video only, 49.38MiB
136          mp4        1280x720   DASH video 2299k , avc1.4d401f, 30fps, video only, 55.05MiB
248          webm       1920x1080  1080p 3239k , vp9, 30fps, video only, 87.46MiB
137          mp4        1920x1080  DASH video 4385k , avc1.640028, 30fps, video only, 102.19MiB
271          webm       2560x1440  1440p 10210k , vp9, 30fps, video only, 270.64MiB
264          mp4        2560x1440  DASH video 12166k , avc1.640032, 30fps, video only, 273.52MiB
266          mp4        3840x2160  DASH video 23868k , avc1.640033, 30fps, video only, 669.87MiB
138          mp4        3840x2160  DASH video 24322k , avc1.640033, 30fps, video only, 573.82MiB
313          webm       3840x2160  2160p 31379k , vp9, 30fps, video only, 678.65MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
```

(Actually this is strange... why doesn't it show any 60fps versions? The video itself is 60fps.)

Why does it show that the best video is the 720p video in the last line? I would expect it to be the 313. Is there anything I'm missing here? Is there a way to automatically select the video with the highest resolution and frame rate? (Sorry, I looked in the documentation, but it doesn't seem like there's anything about this there).

As a second question: in the docs, it says this:

> You can also use a file extension... to download the best quality format of a particular file extension served as a single file, e.g. `-f webm` will download the best quality format with the `webm` extension served as a single file.

However, when I insert this command:

    youtube-dl -f webm "https://www.youtube.com/watch?v=iNJdPyoqt8U"

what's downloaded is a video like **18**, which is really strange as it seems to be the _worst_ quality, not the best.

Again, sorry if these are elementary questions. I scoured the documentation but couldn't find anything relating to this there.

**Comment by yan12125** [comment]
First this video is not 60fps: https://www.youtube.com/watch?v=iNJdPyoqt8U&lc=z13hdreyksrlsrx2c22hzblxoufhcjjcj

Of course we shouldn't believe random comments on the Internet. Right-click on the video, choose "Stats for nerds" and check its frame rate.

> Why does it show that the best video is the 720p video in the last line?

The order of -F is bestaudio, bestvideo and best.

> what's downloaded is a video like 18

Install ffmpeg and try again.

**Comment by dstftw** [comment]
>(Actually this is strange... why doesn't it show any 60fps versions? The video itself is 60fps.)

No, it's not:
![image](https://cloud.githubusercontent.com/assets/1908898/23562809/9ddf6dba-0076-11e7-853b-c14f76240e16.png)

>Resolution:3840 x 2160@30

>Why does it show that the best video is the 720p video in the last line?

Because you did not read [FAQ](https://github.com/rg3/youtube-dl#format-selection):
>`best`: Select the best quality format **represented by a single file** with video and audio.
>`bestvideo`: Select the best quality **video-only format** (e.g. DASH video). May not be available.

>Is there anything I'm missing here?

Read [FAQ](https://github.com/rg3/youtube-dl#format-selection). It's all explained.

>Is there a way to automatically select the video with the highest resolution and frame rate?

Read [FAQ](https://github.com/rg3/youtube-dl#format-selection).

>what's downloaded is a video like 18, which is really strange as it seems to be the worst quality, not the best.

Cause it's applied to single file formats.

**Comment by sn0wyfall** [comment]
@dstftw Thanks a lot for your reply.

> No, it's not:

I find it mind-blowing that a video with 45 million views can put such an inaccurate statement in the title. I tried looking for the 60fps option but couldn't find it, and assumed it was because I was using Safari and not Chrome. Additionally, I looked in the comments of that video to find out if anyone was complaining that it _wasn't_ 60fps, and no one was, so I assumed that it was. I can't believe it...

~~Now, as for your other comments, I did read the FAQ, but my questions weren't answered there at all. Unless you meant the documentation? I looked over that too (specifically the "format selection"), but I couldn't find anything. Please don't be angry at me, I did try looking before I asked this question.~~

I have no idea why I made this issue.
