### ISSUE TITLE
ERROR: unable to open for writing: [Errno 36] File name too long  @ ubuntu server 14.04

### ISSUE THREAD

**Issue by orangercat** [rg3/youtube-dl#12351]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.02**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
Request Method:	POST
Request URL:	
Django Version:	1.10.5
Exception Type:	DownloadError
Exception Value:	
ERROR: unable to open for writing: [Errno 36] File name too long: './download/പല ഐറ്റംസ് കയ്യിലുണ്ടെന്ന് പറഞ്ഞപ്പോൾ ഇങ്ങനൊരു ഐറ്റം ആകുമെന്ന് ഒരിക്കലും പ്രതീക്ഷിച്ച മോളേ......mp4.part'
Exception Location:	/usr/local/lib/python3.4/dist-packages/youtube_dl/YoutubeDL.py in trouble, line 540
Python Executable:	/usr/local/bin/uwsgi
Python Version:	3.4.3
Python Path:	
['.',
 '',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/lib/python3/dist-packages']
...
<end of log>
```
```
debug] Invoking downloader on 'https://r1---sn-n4v7kn7l.googlevideo.com/videoplayback?id=6f53638c2b065c6a&itag=134&source=youtube&requiressl=yes&mn=sn-n4v7kn7l&mm=31&initcwndbps=5260000&mv=m&pl=20&ms=au&ratebypass=yes&mime=video/mp4&gir=yes&clen=1377658&lmt=1488522780279099&dur=56.866&signature=702FDCDE4BCACD5EB8DE299BE822992C0E5F0438.5151A75908F59DD92F15F929FE4F636D4DCE6CC3&mt=1488782605&upn=noB0sDJwOhw&key=dg_yt0&ip=192.241.227.106&ipbits=0&expire=1488804307&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,mm,initcwndbps,mv,pl,ms,ratebypass,mime,gir,clen,lmt,dur'
ERROR: unable to open for writing: [Errno 36] File name too long: 'പല ഐറ്റംസ് കയ്യിലുണ്ടെന്ന് പറഞ്ഞപ്പോൾ ഇങ്ങനൊരു ഐറ്റം ആകുമെന്ന് ഒരിക്കലും പ്രതീക്ഷിച്ച മോളേ.....-b1NjjCsGXGo.f134.mp4.part'
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/downloader/http.py", line 175, in real_download
    (stream, tmpfilename) = sanitize_open(tmpfilename, open_mode)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/utils.py", line 448, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 36] File name too long: 'പല ഐറ്റംസ് കയ്യിലുണ്ടെന്ന് പറഞ്ഞപ്പോൾ ഇങ്ങനൊരു ഐറ്റം ആകുമെന്ന് ഒരിക്കലും പ്രതീക്ഷിച്ച മോളേ.....-b1NjjCsGXGo.f134.mp4.part'

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
https://www.youtube.com/watch?v=b1NjjCsGXGo

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

hi i use 
```
ydl_opts = {
            'outtmpl': '/%(title)s.%(ext)s',
```
@ ubuntu server 14.04. it said file name too long, but this code is fine at MacOS. i want to know how i can output filename with only a specify long (ex: 20 byte).thank you

**Comment by yan12125** [comment]
Hello @orangercat, first sorry for the late response. This problem is already discussed in #5921 and there's no simple and generic solution yet. For Python applications, you can inherit the ```YoutubeDL``` class, override ```prepare_filename()``` and implement your own filename truncation logic.

**Comment by wallebot1** [comment]
I have same problem with intermedio program.
http://www.atresplayer.com/television/programas/el-intermedio/temporada-12/capitulo-65-12-12-17-crtica-wyoming-sanidad-pblica-antes-llambamos-seguridad-social-ahora-siniestro-total_2017121200840.html

Many time title is 255 chars bigger.


I think this is a good advice
For Python applications, you can inherit the YoutubeDL class, override prepare_filename() and implement your own filename truncation logic.

**Comment by sputnick-dev** [comment]
Hi,

what I does in a bash wrapper script : 

```
#!/bin/bash
  
filename=$(youtube-dl --get-filename -o '%(title)s.%(ext)s' "$@")
bytes_filename_size=$(wc -c <<< "$filename")

# cut first 200 bytes if filename is too long
if (($bytes_filename_size >= 250)); then
    filename=$(cut -c 1-250 <<< "$filename")
else
    filename='%(title)s.%(ext)s'
fi

exec youtube-dl -f best --restrict-filenames -o "$filename" "$@"
```
