### ISSUE TITLE
Add support for voot.com (India region block)

### ISSUE THREAD

**Issue by PannenkoekenNL** [rg3/youtube-dl#12350]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.02**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Site support request (request for adding support for a new site)

### Description of your *issue*, suggested solution and other information

Please add support for voot.com. Example URL: https://www.voot.com/kids/characters/mighty-cat-masked-niyander-e-/400478/school-bag-disappears/440925

**Comment by 0880** [comment]
There is already a site support request (#10255).

**Comment by yan12125** [comment]
Thanks @0880. For further discussions, please move to #10255
