### ISSUE TITLE
Possible BUG with "&" character in password.

### ISSUE THREAD

**Issue by rgmorato** [rg3/youtube-dl#12377]
When the password contains the & character, the following error occurs:
"Youtube-dl: error: You must provide at least one URL."

youtube-dl -i -v --sleep-interval 60 --max-sleep-interval 100 -u PRIVATE -p PRIVATE -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" --all-sub
s "https://app.pluralsight.com/library/courses/windows-server-2012-70-411-configure-network-services"
[1] 201
XXXX: command not found
#[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'-v', u'--sleep-interval', u'60', u'--max-sleep-interval', u'100', u'-u', u'PRIVATE', u'-p', u'PRIVATE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.02
[debug] Python version 2.7.6 - Linux-3.4.0+-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

XXX is part of password, after the & character.

**Comment by yan12125** [comment]
You need to enclose your password with single or double quotes. See https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
