### ISSUE TITLE
No Metadata/Thumbnail MP3 Format

### ISSUE THREAD

**Issue by AdrianGabriel96** [rg3/youtube-dl#12375]
This is the command with -v output:
youtube-dl  --extract-audio --audio-format mp3 --audio-quality 0  --no-part --no-mtime --embed-thumbnail --add-metadata https://www.youtube.com/watch?v=XyL3YKK_1BI  -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--extract-audio', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'--no-part', u'--no-mtime', u'--embed-thumbnail', u'--add-metadata', u'https://www.youtube.com/watch?v=XyL3YKK_1BI', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.06
[debug] Python version 2.7.5 - Linux-3.10.0-514.6.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2
[debug] Proxy map: {}
[youtube] XyL3YKK_1BI: Downloading webpage
[youtube] XyL3YKK_1BI: Downloading video info webpage
[youtube] XyL3YKK_1BI: Extracting video information
[youtube] {22} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {43} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {18} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {36} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {17} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {137} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {248} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {136} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {247} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {135} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {244} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {134} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {243} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {133} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {242} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {160} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {278} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {140} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {171} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {249} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {250} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {251} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] XyL3YKK_1BI: Downloading thumbnail ...
[youtube] XyL3YKK_1BI: Writing thumbnail to: Meghan Trainor - I'm a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.jpg
[debug] Invoking downloader on u'https://r17---sn-25g7sn7d.googlevideo.com/videoplayback?gcr=fr&initcwndbps=8452500&gir=yes&pl=23&source=youtube&upn=LHUHOlq5jRA&mime=audio%2Fwebm&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cusequic%2Cexpire&beids=%5B9452306%5D&id=o-ACvKOWVwOu86NH3EBc10PiunFrLqACAj64z19fQ-GBpn&itag=171&ei=gNK8WIeMMJnNc5zvm6AN&key=yt6&ip=MY_IP&usequic=no&dur=163.778&lmt=1488488952311079&ms=au&clen=2679342&keepalive=yes&mv=m&mt=1488769581&expire=1488791264&requiressl=yes&ipbits=0&mn=sn-25g7sn7d&mm=31&signature=67011319140772B5D92AE18188B4A8C912F84806.0F7F43D7F2ABCF40FDDB614CCBE6AE1C179E2CD4&ratebypass=yes'
[download] Destination: Meghan Trainor - I'm a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.webm
[download] 100% of 2.56MiB in 00:00
[ffmpeg] Adding metadata to 'Meghan Trainor - I'm a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.webm'
[debug] ffmpeg command line: ffmpeg -y -i 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.webm' -c copy -metadata 'comment=From the motion picture SMURFS: THE LOST VILLAGE   To find release dates and other information about SMURFS: THE LOST VILLAGE  Go here: http://www.smurfsmovie.com/  Or here: SmurfsMovie.net

Purchase "I'"'"'m A Lady (From the motion picture SMURFS: THE LOST VILLAGE)" at iTunes Here:  smarturl.it/ImaLady
Apple Music - smarturl.it/ImaLady_AM
Spotify - smarturl.it/ImaLady_Sptfy
Google Play - smarturl.it/ImaLady_GP
Amazon - smarturl.it/ImaLady_Dig

https://www.facebook.com/meghantrainorsongs
https://twitter.com/meghan_trainor
http://instagram.com/meghan_trainor
http://www.meghan-trainor.com/

(C) 2017 Epic Records, a division of Sony Music Entertainment

http://vevo.ly/tWKwbe' -metadata 'description=From the motion picture SMURFS: THE LOST VILLAGE   To find release dates and other information about SMURFS: THE LOST VILLAGE  Go here: http://www.smurfsmovie.com/  Or here: SmurfsMovie.net

Purchase "I'"'"'m A Lady (From the motion picture SMURFS: THE LOST VILLAGE)" at iTunes Here:  smarturl.it/ImaLady
Apple Music - smarturl.it/ImaLady_AM
Spotify - smarturl.it/ImaLady_Sptfy
Google Play - smarturl.it/ImaLady_GP
Amazon - smarturl.it/ImaLady_Dig

https://www.facebook.com/meghantrainorsongs
https://twitter.com/meghan_trainor
http://instagram.com/meghan_trainor
http://www.meghan-trainor.com/

(C) 2017 Epic Records, a division of Sony Music Entertainment

http://vevo.ly/tWKwbe' -metadata artist=MeghanTrainorVEVO -metadata 'title=Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS: THE LOST VILLAGE)' -metadata date=20170303 -metadata 'purl=https://www.youtube.com/watch?v=XyL3YKK_1BI' 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.temp.webm'
[debug] ffmpeg command line: ffprobe -show_streams 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.webm'
[ffmpeg] Destination: Meghan Trainor - I'm a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.webm' -vn -acodec libmp3lame -q:a 0 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.mp3'
Deleting original file Meghan Trainor - I'm a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.webm (pass -k to keep)
[ffmpeg] Adding thumbnail to "Meghan Trainor - I'm a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.mp3"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.mp3' -i 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.jpg' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.temp.mp3'

I don't think that it is a ffmpeg issue because I can add a thumbnail using ffmpeg with this command:
'ffmpeg -i in.mp3 -i '.$img.' -map 0:0 -map 1:0 -c copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (Front)" out.mp3
Thanks.

**Comment by yan12125** [comment]
There are no errors in your log. And I can see thumbnails in mpv from the downloaded file by running the same command as yours. What's the player you're using?

**Comment by AdrianGabriel96** [comment]
I use Poweramp (for mobile) and the standard one for windows 10 (Groove Music).

**Comment by yan12125** [comment]
Could you try this:
```
youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 --no-part --no-mtime --embed-thumbnail --add-metadata "https://www.youtube.com/watch?v=XyL3YKK_1BI" -v --postprocessor-args "-id3v2_version 3"
```

**Comment by AdrianGabriel96** [comment]
The Cover Art works now, but no metadata.

**Comment by AdrianGabriel96** [comment]
This is the output:
youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 --no-part --no-mtime --embed-thumbnail --add-metadata "https://www.youtube.com/watch?v=XyL3YKK_1BI" -v --postprocessor-args "-id3v2_version 3"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--extract-audio', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'--no-part', u'--no-mtime', u'--embed-thumbnail', u'--add-metadata', u'https://www.youtube.com/watch?v=XyL3YKK_1BI', u'-v', u'--postprocessor-args', u'-id3v2_version 3']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.06
[debug] Python version 2.7.5 - Linux-3.10.0-514.6.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2
[debug] Proxy map: {}
[youtube] XyL3YKK_1BI: Downloading webpage
[youtube] XyL3YKK_1BI: Downloading video info webpage
[youtube] XyL3YKK_1BI: Extracting video information
[youtube] {22} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {43} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {18} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {36} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {17} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {137} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {248} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {136} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {247} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {135} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {244} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {134} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {243} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {133} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {242} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {160} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {278} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {140} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {171} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {249} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {250} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] {251} signature length 40.40, html5 player en_US-vflDQGgxm
[youtube] XyL3YKK_1BI: Downloading thumbnail ...
[youtube] XyL3YKK_1BI: Writing thumbnail to: Meghan Trainor - I'm a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.jpg
[debug] Invoking downloader on u'https://r5---sn-25ge7nls.googlevideo.com/videoplayback?pl=23&mime=audio%2Fwebm&id=o-AKa44LtLC9ji_eo-7sn0hNMFDMDFTe3dNY53YL-v0NwQ&mn=sn-25ge7nls&mm=31&ipbits=0&gcr=fr&requiressl=yes&ip=62.210.178.161&ms=au&gir=yes&mt=1488792146&usequic=no&dur=163.778&ei=uyq9WNSvGZOuc_y_t6gO&initcwndbps=6410000&mv=m&expire=1488813851&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cusequic%2Cexpire&clen=2679342&source=youtube&upn=TPjuGRn_vEk&itag=171&beids=%5B9452307%5D&keepalive=yes&lmt=1488488952311079&key=yt6&signature=CC5E9E46C008D03347979B687E936D857B887CDA.A6416D1BCA622E7B2445278AA52258F2600E6180&ratebypass=yes'
[download] Destination: Meghan Trainor - I'm a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.webm
[download] 100% of 2.56MiB in 00:00
[ffmpeg] Adding metadata to 'Meghan Trainor - I'm a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.webm'
[debug] ffmpeg command line: ffmpeg -y -i 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.webm' -c copy -metadata 'comment=From the motion picture SMURFS: THE LOST VILLAGE   To find release dates and other information about SMURFS: THE LOST VILLAGE  Go here: http://www.smurfsmovie.com/  Or here: SmurfsMovie.net




Purchase "I'"'"'m A Lady (From the motion picture SMURFS: THE LOST VILLAGE)" at iTunes Here:  smarturl.it/ImaLady
Apple Music - smarturl.it/ImaLady_AM
Spotify - smarturl.it/ImaLady_Sptfy
Google Play - smarturl.it/ImaLady_GP
Amazon - smarturl.it/ImaLady_Dig

https://www.facebook.com/meghantrainorsongs
https://twitter.com/meghan_trainor
http://instagram.com/meghan_trainor
http://www.meghan-trainor.com/

(C) 2017 Epic Records, a division of Sony Music Entertainment

http://vevo.ly/tWKwbe' -metadata 'description=From the motion picture SMURFS: THE LOST VILLAGE   To find release dates and other information about SMURFS: THE LOST VILLAGE  Go here: http://www.smurfsmovie.com/  Or here: SmurfsMovie.net




Purchase "I'"'"'m A Lady (From the motion picture SMURFS: THE LOST VILLAGE)" at iTunes Here:  smarturl.it/ImaLady
Apple Music - smarturl.it/ImaLady_AM
Spotify - smarturl.it/ImaLady_Sptfy
Google Play - smarturl.it/ImaLady_GP
Amazon - smarturl.it/ImaLady_Dig

https://www.facebook.com/meghantrainorsongs
https://twitter.com/meghan_trainor
http://instagram.com/meghan_trainor
http://www.meghan-trainor.com/

(C) 2017 Epic Records, a division of Sony Music Entertainment

http://vevo.ly/tWKwbe' -metadata artist=MeghanTrainorVEVO -metadata 'title=Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS: THE LOST VILLAGE)' -metadata date=20170303 -metadata 'purl=https://www.youtube.com/watch?v=XyL3YKK_1BI' -id3v2_version 3 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.temp.webm'
[debug] ffmpeg command line: ffprobe -show_streams 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.webm'
[ffmpeg] Destination: Meghan Trainor - I'm a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.webm' -vn -acodec libmp3lame -q:a 0 -id3v2_version 3 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.mp3'
Deleting original file Meghan Trainor - I'm a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.webm (pass -k to keep)
[ffmpeg] Adding thumbnail to "Meghan Trainor - I'm a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.mp3"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.mp3' -i 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.jpg' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' -id3v2_version 3 'file:Meghan Trainor - I'"'"'m a Lady (From the motion picture SMURFS - THE LOST VILLAGE)-XyL3YKK_1BI.temp.mp3'

**Comment by yan12125** [comment]
Thanks for testing. I guess this is similar to #5957. I use neither Windows nor Poweramp. Need someone else for further investigation.

**Comment by AdrianGabriel96** [comment]
I checked with VLC now, and the same problem, just the title metatag is set to the name of the file (before even the title metatag was not there)

**Comment by yan12125** [comment]
Hmm I guess I misunderstood the problem. This seems more related to #5594. It should be fixed in the next version.

**Comment by AdrianGabriel96** [comment]
thank you very much, now it is solved.
