### ISSUE TITLE
Modified-time often gets useless values and is of questionable value

### ISSUE THREAD

**Issue by dsoprea** [rg3/youtube-dl#12379]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.06**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

This issue indicates that the modified-time is set based on the "Last-Modified" header: https://github.com/rg3/youtube-dl/issues/9386

I'm not sure that setting the modified-time produces much value. I downloaded one video and the mtime is exactly one year earlier than the date on the YouTube page. I downloaded another and the mtime is set to now. If the timestamp isn't intuitive, predictable, or what people otherwise expect it to be, then it seems useless and confusing.

I'm +1 for killing it. It seems like most people would prefer passing the switch to disable it if they knew how truly unpredictable it could be. Thoughts?

**Comment by yan12125** [comment]
There was a discussion for the same issue: #1709. Please move there for further discussions, thanks!
