### ISSUE TITLE
--dump-json missing information for .mp4s from twitch.tv

### ISSUE THREAD

**Issue by jrogozen** [rg3/youtube-dl#12383]
Seems like running the --dump-json command doesn't return all information for twitch.tv clips

running

```
youtube-dl https://clips-media-assets.twitch.tv/24708907632-offset-5632-854x480.mp4 --dump-json
```

outputs

`{"upload_date": "20170306", "protocol": "https", "extractor": "generic", "direct": true, "fulltitle": "24708907632-offset-5632-854x480", "id": "24708907632-offset-5632-854x480", "playlist": null, "title": "24708907632-offset-5632-854x480", "_filename": "24708907632-offset-5632-854x480-24708907632-offset-5632-854x480.mp4", "playlist_index": null, "webpage_url_basename": "24708907632-offset-5632-854x480.mp4", "display_id": "24708907632-offset-5632-854x480", "format": "mp4 - unknown", "requested_subtitles": null, "format_id": "mp4", "url": "https://clips-media-assets.twitch.tv/24708907632-offset-5632-854x480.mp4", "extractor_key": "Generic", "vcodec": null, "http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)"}, "ext": "mp4", "webpage_url": "https://clips-media-assets.twitch.tv/24708907632-offset-5632-854x480.mp4", "formats": [{"protocol": "https", "format": "mp4 - unknown", "url": "https://clips-media-assets.twitch.tv/24708907632-offset-5632-854x480.mp4", "vcodec": null, "http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)"}, "ext": "mp4", "format_id": "mp4"}]}
`

it is missing the duration info. is this an error in the encoding of twitch's mp4s, or something on the youtube-dl side?

thanks!

**Comment by dstftw** [comment]
https://clips-media-assets.twitch.tv/24708907632-offset-5632-854x480.mp4 is a **direct** link where is it supposed to get duration from?

**Comment by jrogozen** [comment]
what about something like https://clips.twitch.tv/RoundLitigiousMangetoutKippa ?

**Comment by dstftw** [comment]
There is no duration available.

**Comment by jrogozen** [comment]
Ah, so a limitation of the twitch api? I think I had the assumption that youtube-dl would download create a stream of the video file extracted from the url and pass it into ffprobe or something to get info. 

But it probably calls w/e 3rd party api to get information based on the url

**Comment by dstftw** [comment]
There is no API. It parses a webpage.

**Comment by jrogozen** [comment]
Oh! Thanks for clearing that up
