### ISSUE TITLE
How to get the file name with ext

### ISSUE THREAD

**Issue by deangelo200** [rg3/youtube-dl#12384]
Hey does anyone know how to get the file name not title but the name of the file for example "Mymusic.mp3". I want to get the file name using python code.

**Comment by dstftw** [comment]
`_filename` key of info dict.

**Comment by deangelo200** [comment]
` file_name = info_dict.get('_filename', None)`

did not work..

**Comment by deangelo200** [comment]
`file_name = info_dict.get('_filename', None)`

not working...

**Comment by yan12125** [comment]
@deangelo200: See #10987

**Comment by deangelo200** [comment]
thanks for all the help but i have a big problem with encoding. Popcaan -
Addicted (January 2017)🔥 this is the name of a song i want to download but
because of "🔥" it gave me an error
[image: Inline image 1]

**Comment by yan12125** [comment]
Most likely you didn't handle encodings correctly. By the way images are not shown if you reply this thread with emails.

**Comment by deangelo200** [comment]
UnicodeEncodeError at /

'latin-1' codec can't encode character '\U0001f525' in position 121:
ordinal not in range(256)

Request Method: POST
Request URL: http://muzilla-mp3.com/
Django Version: 1.10.5
Exception Type: UnicodeEncodeError
Exception Value:

'latin-1' codec can't encode character '\U0001f525' in position 121:
ordinal not in range(256)
