### ISSUE TITLE
Error : Unable to log in Pluralsight.

### ISSUE THREAD

**Issue by martinserafim93** [rg3/youtube-dl#12398]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.07**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)

Hi, I have a problem, it say "ERROR: Unable to log in;". I try to download on Pluralsight. This my output ::
$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.07
[debug] Python version 2.7.12+ - Linux-4.8.0-39-generic-x86_64-with-Ubuntu-16.10-yakkety
[debug] exe versions: ffmpeg 3.0.7-0ubuntu0.16.10.1, ffprobe 3.0.7-0ubuntu0.16.10.1, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

And this it issue :: 
$ youtube-dl --username *****************@************* --password ************ --write
-sub https://app.pluralsight.com/library/courses/aspdotnetcore-efcore-bootstrap-angular-web-app --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--write-sub', u'https://app.pluralsight.com/library/courses/aspdotnetcore-efcore-bootstrap-angular-web-app', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.07
[debug] Python version 2.7.12+ - Linux-4.8.0-39-generic-x86_64-with-Ubuntu-16.10-yakkety
[debug] exe versions: ffmpeg 3.0.7-0ubuntu0.16.10.1, ffprobe 3.0.7-0ubuntu0.16.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[pluralsight:course] aspdotnetcore-efcore-bootstrap-angular-web-app: Downloading course JSON
[download] Downloading playlist: Building a Web App with ASP.NET Core, MVC 6, EF Core, and Angular
[pluralsight:course] playlist Building a Web App with ASP.NET Core, MVC 6, EF Core, and Angular: Collected 112 video ids (downloading 112 of them)
[download] Downloading video 1 of 112
[pluralsight] Downloading login page
[pluralsight] Logging in as *************@***********
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 426, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 384, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 60, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 100, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by luizconrado** [comment]
Same problem here:

C:\Users\xxxx.xxxx\Downloads\Pluralsight - Angular 2 First Look>youtube-dl --username xxxx.xxx@xxxxxx.com --password xxxxxxx --rate-limit 512K --verbose --sleep-interval 180 -o "%(autonumber)s - %(title)s.%(ext)s" --all-subs --playlist-start 1 https://app.pluralsight.com/library/courses/xxxxx-xx-xxxxx-xxxx
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--rate-limit', '512K', '--verbose', '--sleep-interval', '180', '-o', '%(autonumber)s - %(title)s.%(ext)s', '--all-subs', '--playlist-start', '1', 'https://app.pluralsight.com/library/courses/angular-2-first-look']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.07
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] angular-2-first-look: Downloading course JSON
[download] Downloading playlist: Angular 2: First Look
[pluralsight:course] playlist Angular 2: First Look: Collected 95 video ids (downloading 95 of them)
[download] Downloading video 1 of 95
[pluralsight] Downloading login page
[pluralsight] Logging in as xxxxx.xxxx@xxxxx.com
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvin3ute2\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvin3ute2\build\youtube_dl\extractor\common.py", line 426, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvin3ute2\build\youtube_dl\extractor\common.py", line 384, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvin3ute2\build\youtube_dl\extractor\pluralsight.py", line 60, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvin3ute2\build\youtube_dl\extractor\pluralsight.py", line 100, in _login
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by serendipity30** [comment]
Same issue here for me too

**Comment by aasteins** [comment]
Got the same error, w/ 2017.03.07 and 2017.02.x version.

**Comment by luizconrado** [comment]
Please, reply on this thread. Thanks.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/12345#issuecomment-284054428
