### ISSUE TITLE
Can't download from www.miomio.tv

### ISSUE THREAD

**Issue by whitesiroi** [rg3/youtube-dl#12402]
$ youtube-dl http://www.miomio.tv/watch/cc313396/

> [miomio.tv] 313396: Downloading webpage
> ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl -U
youtube-dl is up-to-date (2017.03.07)

**Comment by yan12125** [comment]
Thanks this will be fixed in the next version.

**Comment by whitesiroi** [comment]
Hi, again getting error:

```
youtube-dl is up-to-date (2020.06.16.1)

$ youtube-dl https://miomio.us/q200628.html
[generic] q200628: Requesting header
WARNING: Falling back on generic information extractor.
[generic] q200628: Downloading webpage
[generic] q200628: Extracting information
ERROR: Unsupported URL: https://miomio.us/q200628.html
```

Thank you

**Comment by taike48** [comment]
This.
