### ISSUE TITLE
SITE REQUEST: Videomore.ru (add/fix functionality)

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#12401]
Hello dearest coders. I just updated YDL, yet I am trying to get video from VIDEOMORE.RU site, seeing no success at all. Here is the log of what's happening:
R:\>youtube-dl -v -F http://videomore.ru/prividenie
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'http://videomore.ru/prividenie']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.03.07
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[videomore:video] prividenie: Downloading webpage
[videomore] 260998: Downloading video XML
[videomore] 260998: Downloading f4m manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvin3ute2\build\youtube_dl\YoutubeDL.py", line 761,in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvin3ute2\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvin3ute2\build\youtube_dl\extractor\videomore.py",line 112, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvin3ute2\build\youtube_dl\extractor\common.py", line 1023, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . 

I have seen Videomore in --list-formats, yet I want to ask you to investigate this stuff, yet add "what is changed" to videomore section of YDL. Thanks in advance!

**Comment by dstftw** [comment]
This video is DRM protected.

**Comment by nmr50** [comment]
Heck.. To be honest - this video won't play in any browser I tried - although no DRM messages, no "pay to me now!" messages appear... in other case I'd have to insist to change YDL code:)

**Comment by dstftw** [comment]
Video plays fine in browser. DRM has nothing necessarily to do with paying out, it's just protected.

>I'd have to insist to change YDL code

Go for it.
