### ISSUE TITLE
If the video is deleted or blocked after the download playlist will be interrupted, can be modified to automatically skip the invalid video? this is a problem

### ISSUE THREAD

**Issue by oac05757** [rg3/youtube-dl#12412]
If the video is deleted or blocked after the download playlist will be interrupted, can be modified to automatically skip the invalid video? this is a problem

example:
Https://www.youtube.com/playlist?list=PL2571E8573C31EC0D

He will automatically interrupt the download in the fourth video of the time

**Comment by dstftw** [comment]
`-i`.
