### ISSUE TITLE
[tv.nrk.no] Unable to download JSON metadata: HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by PellePolitibil** [rg3/youtube-dl#12415]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: ['-v', '--restrict-filenames', '-o', '\\Download\\%(series)s\\%(title)s.%(height)sp.%(ext)s', '--write-sub', '--convert-subs', 'srt', '--embed-subs', '--recode-video', 'mkv', '--ffmpeg-location', 'C:\\Users\\Something\\Downloads\\ffmpeg-20161025-c117343-win64-static\\bin\\', '--download-archive', 'nrk_archive.txt', '-a', 'showsToDownload.txt']
[debug] Custom config: []
[debug] Command-line args: []
[debug] Batch file urls: ['https://tv.nrk.no/serie/brannmann-sam/OBUI27008308/sesong-3/episode-33']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.03.07
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82117-gc117343, ffprobe N-82117-gc117343
[debug] Proxy map: {}
[debug] Using fake IP 84.214.88.171 (NO) as X-Forwarded-For.
[NRKTV] OBUI27008308: Downloading mediaelement JSON
ERROR: Unable to download JSON metadata: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvin3ute2\build\youtube_dl\extractor\common.py", line 496, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvin3ute2\build\youtube_dl\YoutubeDL.py", line 2093, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

### Description of your *issue*, suggested solution and other information

Had a script running for quite some time to archive shows to my HDD but suddenly today it failed.
Not sure why and it says in the error message to post it here, and here we are.  Tried both with ydl in a python script and using the youtube-dl.exe file in windows, both failed.  I am able to watch the show I am trying to download in the browser.

**Comment by dstftw** [comment]
Works fine for me.
Add `--no-geo-bypass` and try again.

**Comment by PellePolitibil** [comment]
Seems that the issue might have been caused by something on the providers site.  The script is now working again without any changes.
