### ISSUE TITLE
'ascii' codec can't decode

### ISSUE THREAD

**Issue by one2gov** [rg3/youtube-dl#12417]
ubuntu 16.04
python 2.7.12+
command: youtube-dl --print-json https://www.youtube.com/watch?v=VA0rAN0GRY4
gives alot of ascii characters 
"tags": ["Citroen", "Citro\u00ebn",
same with command: youtube-dl --encoding utf-8 --print-json https://www.youtube.com/watch?v=VA0rAN0GRY4
or youtube-dl --encoding utf-8 --write-info-json https://www.youtube.com/watch?v=VA0rAN0GRY4

**Comment by dstftw** [comment]
This is perfectly valid JSON.
Duplicate of #11696.
