### ISSUE TITLE
[cuatro.com] Telecinco extractor error

### ISSUE THREAD

**Issue by jcarlosgarciasegovia** [rg3/youtube-dl#12430]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.10**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)
$ youtube-dl -v http://www.cuatro.com/chesterinlove/a-carta/chester-chester_in_love-chester_edu_2_2331030022.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.cuatro.com/chesterinlove/a-carta/chester-chester_in_love-chester_edu_2_2331030022.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.10
[debug] Python version 2.7.13 - Linux-4.9.13
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Telecinco] chester-chester_in_love-chester_edu_2_2331030022: Downloading webpage
[Telecinco] 81cWcxYTE6H23sReEiWyu8ymHzbYqx8a: Downloading config JSON
ERROR: An extractor error has occurred. (caused by KeyError(u'mmc',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/telecinco.py", line 54, in _real_extract
    info = self._get_player_info(url, webpage)
  File "youtube_dl/extractor/mitele.py", line 30, in _get_player_info
    mmc_url = config['services']['mmc']
KeyError: u'mmc'
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 440, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'mmc',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jcarlosgarciasegovia** [comment]
Thank you for the progress, but it still does not work as it tries to download from a not existing domain:
[Telecinco] chester-chester_in_love-chester_edu_2_2331030022: Downloading webpage
[Ooyala] 81cWcxYTE6H23sReEiWyu8ymHzbYqx8a: Downloading JSON metadata
[Ooyala] 81cWcxYTE6H23sReEiWyu8ymHzbYqx8a: Downloading JSON metadata
[Ooyala] 81cWcxYTE6H23sReEiWyu8ymHzbYqx8a: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno -3] Temporary failure in name resolution>
[Ooyala] 81cWcxYTE6H23sReEiWyu8ymHzbYqx8a: Downloading m3u8 information
[Ooyala] 81cWcxYTE6H23sReEiWyu8ymHzbYqx8a: Downloading MPD manifest
[debug] Invoking downloader on u'http://ignore.mediaset.es/81cWcxYTE6H23sReEiWyu8ymHzbYqx8a/DOcJ-FxaFrRg4gtDEwOjI5cDowODE7AZ'
ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known>


Were you able to download that from that URL?

**Comment by dstftw** [comment]
```
> py -3.6 .\youtube_dl\__main__.py http://www.cuatro.com/chesterinlove/a-carta/chester-chester_in_love-chester_edu_2_2331030022.html -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.cuatro.com/chesterinlove/a-carta/chester-chester_in_love-chester_edu_2_2331030022.html', '-v']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2017.03.16
[debug] Git HEAD: dfd5fd9
[debug] Python version 3.6.0 - Windows-10-10.0.10240-SP0
[debug] exe versions: ffmpeg N-83622-gdcd3418, ffprobe N-83622-gdcd3418, rtmpdump 2.4
[debug] Proxy map: {}
[Telecinco] chester-chester_in_love-chester_edu_2_2331030022: Downloading webpage
[Ooyala] 81cWcxYTE6H23sReEiWyu8ymHzbYqx8a: Downloading JSON metadata
[Ooyala] 81cWcxYTE6H23sReEiWyu8ymHzbYqx8a: Downloading JSON metadata
[Ooyala] 81cWcxYTE6H23sReEiWyu8ymHzbYqx8a: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 503: Service Unavailable
[Ooyala] 81cWcxYTE6H23sReEiWyu8ymHzbYqx8a: Downloading m3u8 information
[Ooyala] 81cWcxYTE6H23sReEiWyu8ymHzbYqx8a: Downloading MPD manifest
[debug] Invoking downloader on 'http://miteleooyala-a.akamaihd.net/81cWcxYTE6H23sReEiWyu8ymHzbYqx8a/1/dash/'
[dashsegments] Total fragments: 2636
[download] Destination: Chester in love_Season_1_Episode_14_fbe1f8b1631141f6b25b06502892cb3e-81cWcxYTE6H23sReEiWyu8ymHzbYqx8a.fdash-1.mp4
[download]   0.0% of ~776.41MiB at 604.35KiB/s ETA 01:55:34
ERROR: Interrupted by user
```
