### ISSUE TITLE
Parameter outtmpl is bytes , but should be a unicode string. Put  from __future__ import unicode_literals  at the top of your code f ile or consider switching to Python 3.x.

### ISSUE THREAD

**Issue by Jfeng3** [rg3/youtube-dl#12438]
Just made a web app using youtube-dl python package
the app run perfectly on local mac os machine
when I deploy to aws elasticbeanstalk, ( which is linux machine ) . it gave the **error** 
```
Parameter outtmpl is bytes , but should be a unicode string. Put  from __future__ import unicode_literals  at the top of your code file or consider switching to Python 3.x.
```

Any clue how to resolve this

**Comment by dstftw** [comment]
It's not an error but a warning in the first place. Did you even read the the text?! It clearly states that `outtmpl` must be unicode string not bytestring.
