### ISSUE TITLE
a particular youtube channel could not be downloaded,

### ISSUE THREAD

**Issue by kaveinthran** [rg3/youtube-dl#12442]
I tried to download the channel https://www.youtube.com/user/livedreams2. After executing the command, it tried to download the pages and says that the channel had been terminated.  but, I still can access the channel and watch videos in the channel. Could it be problems with the downloader?
thanks

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
