### ISSUE TITLE
How to check recursively in folders if video has already been downloaded?

### ISSUE THREAD

**Issue by HummusSamurai** [rg3/youtube-dl#12440]
After downloading some videos, I occasionally sort them into folders according to their category.

However I would often need to update a youtube playlist folder that has new additions, and I am forced to find the folder and then put it back in root to be checked.

Is there an option to check recursively in folders? If not, is it possible to add it to the code? (I can do it if pointed to the relevant files to modify)

**Comment by dstftw** [comment]
Use [download archive](https://github.com/rg3/youtube-dl#how-do-i-download-only-new-videos-from-a-playlist).
