### ISSUE TITLE
Cant get concrete filename after download

### ISSUE THREAD

**Issue by C0DK** [rg3/youtube-dl#12456]
I am trying to download songs from youtube, via the embedded system, and then after it is converted to MP3, have it added to my MPD server's queue. however i cannot seem to find the filename after the file has been converted. i hoped i could use a hook upon finishing, however "finish" is when the download is finished - not when the conversion is finished. I hoped that i could get the finished filename from the "extract_info" method, however it only returns the title name - the outtmpl removes certain characters from the filename ("(",")" as an example) which makes it quite hard to figure out what the finished songname will be. Is it possible to get this filename upon conversion?

Thank  you!

**Comment by johnhawkinson** [comment]
Are you saying that `--exec "add-to-queue.sh {}"` does not work?

**Comment by dstftw** [comment]
You can't get exact filename after conversion, but you can provide unique name via `outtmpl` yourself, like `uuid.%(ext)s`. Assuming the final extension is `mp3` it's easy to build final filename. `(` and `)` are not sanitized until you explicitly require to do so. Refs #5710, #10987.
