### ISSUE TITLE
Make the --max-quality option support human-readable quality identifiers

### ISSUE THREAD

**Issue by romanrm** [rg3/youtube-dl#1245]
Hello,

Can you please support using the actual quality settings in --max-quality, and not just codes for video formats?

The user-facing "quality of video" nomenclature in YouTube is: "1080p, 720p, 480p", and so on.

So I expected I could download a video with:

--max-quality 720p

I do not care at this point whether this will be webm or mp4.

But this seems to be not possible. I have to look up what is the code for the format I need, then specify something like "-f 22/45" instead. And if in the future YouTube migrates to some h265 format with some "code 99 = h265 @ [1280x720]", my script will break, or not download the best possible format anymore.

**Comment by jaimeMF** [comment]
With the last versions you can use `-f 'best[height<=720]'`. Thanks for the report!
