### ISSUE TITLE
how i can download structure of the video

### ISSUE THREAD

**Issue by francyfre** [rg3/youtube-dl#12469]
for example i use youtube-dl to download at pluralsight.com... this program download all the video in one folder without the structure (lesson structure)

for this reason i want to ask this question, i read manual and dont find nothing about this question

thankYouVeryMuch

francesco

**Comment by dstftw** [comment]
Read [FAQ](https://github.com/rg3/youtube-dl#output-template).

**Comment by francyfre** [comment]
excuseMe... there is nothing about video structure... or i dont understand... can you help me please?

**Comment by dstftw** [comment]
I've provided the URL that clearly explains how to do this, bother to read it.
