### ISSUE TITLE
Selecting Wrong Video Height

### ISSUE THREAD

**Issue by QuasarX** [rg3/youtube-dl#12463]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Youtube-DL>youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2017.03.15
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-83882-g58f0bbc, ffprobe N-83882-g58f0bbc
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by QuasarX** [comment]
`youtube-dl --list-formats https://www.youtube.com/watch?v=hHKJ5eE7I1k`

```
C:\Youtube-DL>youtube-dl --list-formats https://www.youtube.com/watch?v=hHKJ5eE7I1k
[youtube] hHKJ5eE7I1k: Downloading webpage
[youtube] hHKJ5eE7I1k: Downloading video info webpage
[youtube] hHKJ5eE7I1k: Extracting video information
[youtube] hHKJ5eE7I1k: Downloading MPD manifest
[info] Available formats for hHKJ5eE7I1k:
format code  extension  resolution note
249          webm       audio only DASH audio   58k , opus @ 50k, 1.10MiB
250          webm       audio only DASH audio   84k , opus @ 70k, 1.54MiB
140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k (44100Hz), 2.87MiB
171          webm       audio only DASH audio  141k , vorbis@128k, 2.57MiB
251          webm       audio only DASH audio  167k , opus @160k, 3.03MiB
160          mp4        256x144    DASH video  111k , avc1.4d400c, 15fps, video only, 2.39MiB
278          webm       256x144    144p  169k , webm container, vp9, 30fps, video only, 2.12MiB
133          mp4        426x240    DASH video  252k , avc1.4d4015, 30fps, video only, 5.45MiB
242          webm       426x240    240p  299k , vp9, 30fps, video only, 4.55MiB
243          webm       640x360    360p  511k , vp9, 30fps, video only, 8.46MiB
134          mp4        640x360    DASH video  612k , avc1.4d401e, 30fps, video only, 9.88MiB
244          webm       854x480    480p  926k , vp9, 30fps, video only, 15.59MiB
135          mp4        854x480    DASH video 1126k , avc1.4d401f, 30fps, video only, 19.55MiB
247          webm       1280x720   720p 1803k , vp9, 30fps, video only, 31.41MiB
136          mp4        1280x720   DASH video 2241k , avc1.4d401f, 30fps, video only, 38.40MiB
248          webm       1920x1080  1080p 3213k , vp9, 30fps, video only, 55.07MiB
137          mp4        1920x1080  DASH video 4202k , avc1.640028, 30fps, video only, 70.66MiB
264          mp4        2560x1440  DASH video 9974k , avc1.640032, 30fps, video only, 161.22MiB
271          webm       2560x1440  1440p 10152k , vp9, 30fps, video only, 175.80MiB
313          webm       3840x2160  2160p 21647k , vp9, 30fps, video only, 378.08MiB
266          mp4        3840x2160  DASH video 22233k , avc1.640033, 30fps, video only, 374.81MiB
138          mp4        3840x2160  DASH video 25128k , avc1.640033, 30fps, video only, 414.82MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
```

I want to select `1080pvideo(mp4)+bestaudio(m4a)`

`youtube-dl -f "[ext=mp4][height<=1080]+bestaudio[ext=m4a]"   https://www.youtube.com/watch?v=hHKJ5eE7I1k`

But it is selecting `f22` (720p)
```
C:\Youtube-DL>youtube-dl -f "[ext=mp4][height<=1080]+bestaudio[ext=m4a]"   https://www.youtube.com/watch?v=hHKJ5eE7I1k
[youtube] hHKJ5eE7I1k: Downloading webpage
[youtube] hHKJ5eE7I1k: Downloading video info webpage
[youtube] hHKJ5eE7I1k: Extracting video information
[youtube] hHKJ5eE7I1k: Downloading MPD manifest
[download] Resuming download at byte 148480
[download] Destination: Panasonic LUMIX GH4 'Light of the Yucatan' in 4K by Bryan Harvey-hHKJ5eE7I1k.f22.mp4
[download]   1.6% of 41.23MiB at 351.64KiB/s ETA 01:58
ERROR: Interrupted by user
```

This code working with this video; https://www.youtube.com/watch?v=hHKJ5eE7I1k
`-f "bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]"`

But not work with; https://www.youtube.com/watch?v=tU3Bgo5qJZE
It is selecting **format code 133 not `134`** 

```
C:\Youtube-DL>youtube-dl --list-formats https://www.youtube.com/watch?v=tU3Bgo5qJZE
[youtube] tU3Bgo5qJZE: Downloading webpage
[youtube] tU3Bgo5qJZE: Downloading video info webpage
[youtube] tU3Bgo5qJZE: Extracting video information
[youtube] tU3Bgo5qJZE: Downloading MPD manifest
[info] Available formats for tU3Bgo5qJZE:
format code  extension  resolution note
249          webm       audio only DASH audio   51k , opus @ 50k, 1010.34KiB
250          webm       audio only DASH audio   61k , opus @ 70k, 1.17MiB
171          webm       audio only DASH audio  109k , vorbis@128k, 2.02MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k (44100Hz), 2.48MiB
251          webm       audio only DASH audio  143k , opus @160k, 2.72MiB
278          webm       256x140    144p   97k , webm container, vp9, 15fps, video only, 865.40KiB
160          mp4        256x140    DASH video  129k , avc1.4d400c, 15fps, video only, 1.08MiB
242          webm       426x234    240p  135k , vp9, 30fps, video only, 1.13MiB
243          webm       640x350    360p  221k , vp9, 30fps, video only, 1.94MiB
134          mp4        640x350    DASH video  282k , avc1.4d401e, 30fps, video only, 2.84MiB
133          mp4        426x234    DASH video  302k , avc1.4d4015, 30fps, video only, 2.43MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x176    small , mp4v.20.3, mp4a.40.2
18           mp4        640x350    medium , avc1.42001E, mp4a.40.2@ 96k
43           webm       640x360    medium , vp8.0, vorbis@128k (best)
```

**How I can select `bestvideo Equal or less than 1080p , file format mp4, fps Equal or less than 30 fps`**

**Comment by dstftw** [comment]
`-f "bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4][height<=1080]"`.

**Comment by QuasarX** [comment]
Did you try with this video? It is not work.

youtube-dl -f "bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4][height<=1080]" https://www.youtube.com/watch?v=tU3Bgo5qJZE
