### ISSUE TITLE
Download speed go down at second video when download a channel

### ISSUE THREAD

**Issue by minhchick** [rg3/youtube-dl#1246]
Everytime I had to hold Crt+C to stop the program and start It again.
At the first video It alway download with max speed, but Speed will stop or very slow at second video.
the image here:
http://ft.trillian.im/725ef445207e36aa8491e5853f6e463b34885f5f/6iTgvNtfGRGvF8VD8KVW7OOcqFelT.jpg

as you can see, I have to stop it and start again and again. This mean if I want to download a channel with 50vids I will need to do it 50 times. 
How to fix that problem?
I'm using windows 8
my Internet was good.

**Comment by dstftw** [comment]
Closing as non youtube-dl issue. Most likely you are shaped by your ISP.
