### ISSUE TITLE
how to increase buffer size

### ISSUE THREAD

**Issue by fjjhdsvjhsdjj** [rg3/youtube-dl#12460]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
I download youtube videos on my raspberrypi 24/7
I am looking at a way to reduce the number of writes to the SD card.
I know the option --buffer-size SIZE (1024 or 16K).  But that does not reduce the number of writes to the SD card even when I give the parameter 1024k.
I see the file size increase every second.

Is there any option to buffer the downloaded bytes (up to 10MB or 50MB) and then write to disk/card?

**Comment by yan12125** [comment]
```--buffer-size``` is used in HTTP operations rather than disk operations.

> I am looking at a way to reduce the number of writes to the SD card.

I believe modern operating systems have buffering. That is, files written to the disk are buffered in the kernel and then written to the actual media later. Increasing in the file size does not indicate that the contents are already written to the SD card. If the OS on Pi does not implement buffering, an alternative is downloading files to tmpfs and move it to the SD card with ```--exec```.
