### ISSUE TITLE
can't download from soundcloud lubuntu 14.04

### ISSUE THREAD

**Issue by zios121** [rg3/youtube-dl#12467]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.16**

- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)

So, since i think the middle of feb i haven't been able to download music from soundcloud. 
(thing that i would do daily) and i've searched and searched, and i still cant figure this out alone. 
from my noob point of view that barely knows how to handle linux, and from the info i gathered its something to do with the version of python that im using? but i cant install no other on this lubuntu 14.04 that im running? this is all the clues i have. Once again i would like to say how sorry i am for not being able to do it by myself what is probably a trivial problem. 
also taking a moment to apologize any bad grammar that you read trough, english is not my first language etc etc
love from a humanities student.  

$smooth@smooth-1005PX:~$ youtube-dl --verbose --extract-audio --audio-format mp3 --output "%(title)s%(uploader)s.%(ext)s" https://soundcloud.com/enzors/visao
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--extract-audio', u'--audio-format', u'mp3', u'--output', u'%(title)s%(uploader)s.%(ext)s', u'https://soundcloud.com/enzors/visao']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.16
[debug] Python version 2.7.6 - Linux-4.4.0-66-generic-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6
[debug] Proxy map: {}
[soundcloud] enzors/visao: Resolving id
[soundcloud] enzors/visao: Downloading info JSON
ERROR: Unable to download JSON metadata: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> (caused by URLError(SSLError(1, '_ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 496, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2093, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1083, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/12462#issuecomment-287030759
