### ISSUE TITLE
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by rhazor** [rg3/youtube-dl#12473]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
https://vimeo.com/ondemand/theouts/196740639 --skip-download --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vimeo.com/ondemand/theouts/196740639', '--skip-download', '--verbose']
[debug] Encodings: locale cp1257, fs mbcs, out cp775, pref cp1257
[debug] youtube-dl version 2017.02.14
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-83975-g6c4665d, ffprobe N-83975-g6c4665d
[debug] Proxy map: {}
[vimeo:ondemand] theouts: Downloading webpage
[vimeo] 196740639: Downloading webpage
[vimeo] 196740639: Extracting information
[vimeo] 196740639: Downloading JSON metadata
**WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden**
[vimeo] 196740639: Downloading fastly_skyfire m3u8 information
[vimeo] 196740639: Downloading akfire_interconnect m3u8 information
[vimeo] 196740639: Downloading fastly_skyfire MPD information
[vimeo] 196740639: Downloading fastly_skyfire MPD information
[vimeo] 196740639: Downloading akfire_interconnect_quic MPD information
[vimeo] 196740639: Downloading akfire_interconnect_quic MPD information
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

This happens to all Vimeo Video on Demand videos, paid and free. This particular link is free and doesn't need account, so you can test it too.

**Comment by dstftw** [comment]
So what? It's just a warning.
