### ISSUE TITLE
[Question] Get youtube-dl compatible URLs from playlists

### ISSUE THREAD

**Issue by Babbie** [rg3/youtube-dl#12485]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I am currently making a Discord bot that will use youtube-dl to obtain music files and play them from URLs (so the usual). To make this a little easier, I wanted to run a command with youtube-dl to obtain URLs from a playlist, so I could perform individual handling on each entry in such a playlist. The problem is that, at least with YouTube playlists, the (two) URLs that are returned per video will not work if they are then supplied to youtube-dl again, presumably due to some security handling. My question is: How do I get youtube-dl compatible URLs out of a playlist using youtube-dl? Of course, I want to avoid having to manually insert the correct URL before the video ID (eg. prepending http://youtube.com/v/ to the ID) as this would bloat my code significantly and make it much more difficult to keep it up to date with new services added to youtube-dl.

For a concrete example:
I want to run something like
```
youtube-dl --get-url https://www.youtube.com/playlist?list=PLWAMgeSbi1zHcUg7V8g9gCaGzIR0APqG7
```
and then run
```
youtube-dl <url>
```
on the individual URLs that are returned, separately, but the URLs that are returned cannot do this (they always return errors)

**Comment by dstftw** [comment]
Provide concrete example with concrete URLs of what are you trying to do.

**Comment by Babbie** [comment]
Updated.

**Comment by dstftw** [comment]
`--flat-playlist --dump-json` and parse from JSON.

**Comment by Babbie** [comment]
I did not realise that only an ID is sufficient for YouTube specifically. Thanks for the heads-up and sorry for the superfluous issue.
