### ISSUE TITLE
Download  Youtube video but "videoplayback.mp4" name

### ISSUE THREAD

**Issue by kale20** [rg3/youtube-dl#12481]
Hello
I'm genarete video source via youtube-dl app and add &title option to source url.

 Exp: http://x.googlevideo.com/xx.mp4&blabla&title=MY_NEW_TITLE
Enter video source url on my pc with chrome and save as video.
Always always download name "videoplayback.mp4".

https://github.com/jeckman/YouTube-Downloader
This php script this style working and download with &title= name.
Thank you for Youtube-dl.
Best app for all timesé!

How to solution this ?
The reason for the difference between these two applications ?

using 
"#root youtube-dl -g -f 18 b3HeLs8Yosw‎"

**Comment by dstftw** [comment]
You are not allowed to modify final download URL otherwise there are no guarantees it will work. You also not guaranteed this will work this way at all since download request should come from the same IP with the same HTTP headers.

**Comment by AdnanHussainTurki** [comment]
Actually, you can.

Watch this : https://www.youtube.com/watch?v=XKUEvqOwgdc

**Comment by yan12125** [comment]
That say - using ```Content-Disposition``` header is out of the scope of youtube-dl as the latter handles filenames on its own. If you want to see a friendly filename in browsers, a way is writing a wrapper around youtube-dl. As mentioned above, you take the risk of invalidate final URLs.

For further discussions, please move to #13325.
