### ISSUE TITLE
Cannot download CBS.com shows

### ISSUE THREAD

**Issue by test3423** [rg3/youtube-dl#12499]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.20*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
 youtube-dl --verbose http://www.cbs.com/shows/kevin-can-wait/video/3E15F9FC-A653-DFA5-8121-C845754DFCB0/kevin-can-wait-showroom-showdown/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.cbs.com/shows/kevin-can-wait/video/3E15F9FC-A653-DFA5-8121-C845754DFCB0/kevin-can-wait-showroom-showdown/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.20
[debug] Python version 2.7.3 - Linux-4.1.19-v7+-armv7l-with-debian-7.11
[debug] exe versions: avconv v13_dev0-467-g4d960a1, avprobe v13_dev0-467-g4d960a1, ffmpeg 0.8.17-6
[debug] Proxy map: {}
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading XML
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading Downloadable SMIL data
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Checking video URL
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: video URL is invalid, skipping
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading OnceURL SMIL data
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Checking video URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Downloading m3u8 information
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-1200 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-1200 video format URL is invalid, skipping
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-4400 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-4400 video format URL is invalid, skipping
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-2000 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-2000 video format URL is invalid, skipping
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-764 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-764 video format URL is invalid, skipping
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-512 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-512 video format URL is invalid, skipping
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-264 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-264 video format URL is invalid, skipping
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-60 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-60 video format URL is invalid, skipping
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading StreamPack SMIL data
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading m3u8 information
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading WIFI SMIL data
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Checking video URL
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Checking video URL
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading 3G SMIL data
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Checking video URL
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Checking video URL
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading RTMP SMIL data
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading JSON metadata
[debug] Invoking downloader on u'http://once-aws-us-west-2-lb.unicornmedia.com/now/media/playlist/bb0b18ba-64f5-4b1b-a29f-0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/468fb310-a585-11e4-bfdb-005056837bc7/9e7dd12a-2cfd-4f76-9a21-55aac1022202/0/0/1287/content.m3u8?visitguid=866cff74-dc60-4c6c-8eaf-fcd362be8f54&segmentlength=10&adsegmentlength=0&protocolversion=3'
[download] Destination: Kevin Can Wait - Showroom Showdown-3E15F9FC-A653-DFA5-8121-C845754DFCB0.mp4
[debug] avconv command line: avconv -y -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
' -i 'http://once-aws-us-west-2-lb.unicornmedia.com/now/media/playlist/bb0b18ba-64f5-4b1b-a29f-0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/468fb310-a585-11e4-bfdb-005056837bc7/9e7dd12a-2cfd-4f76-9a21-55aac1022202/0/0/1287/content.m3u8?visitguid=866cff74-dc60-4c6c-8eaf-fcd362be8f54&segmentlength=10&adsegmentlength=0&protocolversion=3' -c copy -f mp4 'file:Kevin Can Wait - Showroom Showdown-3E15F9FC-A653-DFA5-8121-C845754DFCB0.mp4.part'
avconv version v13_dev0-467-g4d960a1, Copyright (c) 2000-2016 the Libav developers
  built on Nov 19 2016 21:21:54 with gcc 4.6 (Debian 4.6.3-14+rpi1)
[mpegts @ 0x2934960] Estimating duration from bitrate, this may be inaccurate
Input #0, hls,applehttp, from 'http://once-aws-us-west-2-lb.unicornmedia.com/now/media/playlist/bb0b18ba-64f5-4b1b-a29f-0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/468fb310-a585-11e4-bfdb-005056837bc7/9e7dd12a-2cfd-4f76-9a21-55aac1022202/0/0/1287/content.m3u8?visitguid=866cff74-dc60-4c6c-8eaf-fcd362be8f54&segmentlength=10&adsegmentlength=0&protocolversion=3':
  Duration: 00:21:26.68, start: 1.466733, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) [[27][0][0][0] / 0x001B]
      yuv420p, 1280x720 [PAR 1:1 DAR 16:9]
      29.97 fps, 90k tbn
    Stream #0:1: Audio: aac (LC) [[15][0][0][0] / 0x000F]
      48000 Hz, stereo, fltp, 6 kb/s
Output #0, mp4, to 'file:Kevin Can Wait - Showroom Showdown-3E15F9FC-A653-DFA5-8121-C845754DFCB0.mp4.part':
  Metadata:
    encoder         : Lavf57.9.0
    Stream #0:0: Video: h264 (High) [[33][0][0][0] / 0x0021]
      yuv420p, 1280x720 [PAR 1:1 DAR 16:9], q=2-31, PAR 1:1 DAR 16:9
      90k tbn
    Stream #0:1: Audio: aac (LC) [[64][0][0][0] / 0x0040]
      48000 Hz, stereo, fltp, 6 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press ctrl-c to stop encoding
Non-monotonous DTS in output stream 0:1; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
[mp4 @ 0x2a3d520] Timestamps are unset in a packet for stream 1. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
Non-monotonous DTS in output stream 0:1; previous: 1, current: 0; changing to 2. This may result in incorrect timestamps in the output file.
[mp4 @ 0x2a3d520] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 1 >= 1
av_interleaved_write_frame(): Invalid argument


ERROR: ffmpeg exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/bin/youtube-dl/youtube_dl/__init__.py", line 464, in main
    _real_main(argv)
  File "/bin/youtube-dl/youtube_dl/__init__.py", line 454, in _real_main
    retcode = ydl.download(all_urls)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1884, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 772, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 826, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in process_video_result
    self.process_info(new_info)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in process_info
    success = dl(filename, info_dict)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1733, in dl
    return fd.download(name, info)
  File "/bin/youtube-dl/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/bin/youtube-dl/youtube_dl/downloader/external.py", line 47, in real_download
    self.get_basename(), retval))
  File "/bin/youtube-dl/youtube_dl/downloader/common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 551, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
...
<end of log>
```

---

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by johnhawkinson** [comment]
> [debug] exe versions: avconv v13_dev0-467-g4d960a1, avprobe v13_dev0-467-g4d960a1, ffmpeg 0.8.17-6

ffmpeg 0.8 was from four years ago. Try upgrading to something current, like ffmpeg 3.2?

**Comment by test3423** [comment]
I compiled the latest ffmpeg from github, and still seeing the same issue.

youtube-dl --verbose http://www.cbs.com/shows/kevin-can-wait/video/3E15F9FC-A653-DFA5-8121-C845754DFCB0/kevin-can-wait-showroom-showdown/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.cbs.com/shows/kevin-can-wait/video/3E15F9FC-A653-DFA5-8121-C845754DFCB0/kevin-can-wait-showroom-showdown/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.20
[debug] Python version 2.7.3 - Linux-4.1.19-v7+-armv7l-with-debian-7.11
[debug] exe versions: avconv v13_dev0-467-g4d960a1, avprobe v13_dev0-467-g4d960a1, ffmpeg N-84234-g4563a86, ffprobe N-84234-g4563a86
[debug] Proxy map: {}
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading XML
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading Downloadable SMIL data
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Checking video URL
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: video URL is invalid, skipping
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading OnceURL SMIL data
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Checking video URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Downloading m3u8 information
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-1200 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-1200 video format URL is invalid, skipping
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-4400 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-4400 video format URL is invalid, skipping
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-2000 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-2000 video format URL is invalid, skipping
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-764 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-764 video format URL is invalid, skipping
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-512 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-512 video format URL is invalid, skipping
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-264 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-264 video format URL is invalid, skipping
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: Checking http-60 video format URL
[CBS] 9e7dd12a-2cfd-4f76-9a21-55aac1022202: http-60 video format URL is invalid, skipping
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading StreamPack SMIL data
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading m3u8 information
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading WIFI SMIL data
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Checking video URL
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Checking video URL
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading 3G SMIL data
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Checking video URL
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Checking video URL
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading RTMP SMIL data
[CBS] 3E15F9FC-A653-DFA5-8121-C845754DFCB0: Downloading JSON metadata
[debug] Invoking downloader on u'http://once-aws-us-west-2-lb.unicornmedia.com/now/media/playlist/bb0b18ba-64f5-4b1b-a29f-0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/468fb310-a585-11e4-bfdb-005056837bc7/9e7dd12a-2cfd-4f76-9a21-55aac1022202/0/0/1287/content.m3u8?visitguid=85337dc2-9865-4fcc-b984-9ea84bed04c0&segmentlength=10&adsegmentlength=0&protocolversion=3'
[download] Destination: Kevin Can Wait - Showroom Showdown-3E15F9FC-A653-DFA5-8121-C845754DFCB0.mp4
[debug] avconv command line: avconv -y -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
' -i 'http://once-aws-us-west-2-lb.unicornmedia.com/now/media/playlist/bb0b18ba-64f5-4b1b-a29f-0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/468fb310-a585-11e4-bfdb-005056837bc7/9e7dd12a-2cfd-4f76-9a21-55aac1022202/0/0/1287/content.m3u8?visitguid=85337dc2-9865-4fcc-b984-9ea84bed04c0&segmentlength=10&adsegmentlength=0&protocolversion=3' -c copy -f mp4 'file:Kevin Can Wait - Showroom Showdown-3E15F9FC-A653-DFA5-8121-C845754DFCB0.mp4.part'
avconv version v13_dev0-467-g4d960a1, Copyright (c) 2000-2016 the Libav developers
  built on Nov 19 2016 21:21:54 with gcc 4.6 (Debian 4.6.3-14+rpi1)
[mpegts @ 0x1267960] Estimating duration from bitrate, this may be inaccurate
Input #0, hls,applehttp, from 'http://once-aws-us-west-2-lb.unicornmedia.com/now/media/playlist/bb0b18ba-64f5-4b1b-a29f-0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/468fb310-a585-11e4-bfdb-005056837bc7/9e7dd12a-2cfd-4f76-9a21-55aac1022202/0/0/1287/content.m3u8?visitguid=85337dc2-9865-4fcc-b984-9ea84bed04c0&segmentlength=10&adsegmentlength=0&protocolversion=3':
  Duration: 00:21:26.68, start: 1.466733, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) [[27][0][0][0] / 0x001B]
      yuv420p, 1280x720 [PAR 1:1 DAR 16:9]
      29.97 fps, 90k tbn
    Stream #0:1: Audio: aac (LC) [[15][0][0][0] / 0x000F]
      48000 Hz, stereo, fltp, 6 kb/s
Output #0, mp4, to 'file:Kevin Can Wait - Showroom Showdown-3E15F9FC-A653-DFA5-8121-C845754DFCB0.mp4.part':
  Metadata:
    encoder         : Lavf57.9.0
    Stream #0:0: Video: h264 (High) [[33][0][0][0] / 0x0021]
      yuv420p, 1280x720 [PAR 1:1 DAR 16:9], q=2-31, PAR 1:1 DAR 16:9
      90k tbn
    Stream #0:1: Audio: aac (LC) [[64][0][0][0] / 0x0040]
      48000 Hz, stereo, fltp, 6 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press ctrl-c to stop encoding
Non-monotonous DTS in output stream 0:1; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
[mp4 @ 0x1370520] Timestamps are unset in a packet for stream 1. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
Non-monotonous DTS in output stream 0:1; previous: 1, current: 0; changing to 2. This may result in incorrect timestamps in the output file.
[mp4 @ 0x1370520] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 1 >= 1
av_interleaved_write_frame(): Invalid argument


ERROR: ffmpeg exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/bin/youtube-dl/youtube_dl/__init__.py", line 464, in main
    _real_main(argv)
  File "/bin/youtube-dl/youtube_dl/__init__.py", line 454, in _real_main
    retcode = ydl.download(all_urls)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1884, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 772, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 826, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in process_video_result
    self.process_info(new_info)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in process_info
    success = dl(filename, info_dict)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1733, in dl
    return fd.download(name, info)
  File "/bin/youtube-dl/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/bin/youtube-dl/youtube_dl/downloader/external.py", line 47, in real_download
    self.get_basename(), retval))
  File "/bin/youtube-dl/youtube_dl/downloader/common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 551, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by dstftw** [comment]
Either remove `avconv` from `PATH` or pass `--prefer-ffmpeg`.

**Comment by johnhawkinson** [comment]
Yeah, I was mislead by
> ERROR: ffmpeg exited with code 1

Is that a youtube-dl bug, reporting that ffmpeg was what errored out when actually something else was run?

**Comment by test3423** [comment]
--prefer-ffmpeg option seems to work. Thanks for looking into this.
