### ISSUE TITLE
[Feature Request] Write errors to text file.

### ISSUE THREAD

**Issue by BridgeUK** [rg3/youtube-dl#12494]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.16**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Feature request (request for a new functionality)

---

### Description of your *issue*, suggested solution and other information

I think it would be beneficial to the user, or at least it would be to me, if there was a command which writes out any error messages to a text file for easy reading, for example "--write-error error.txt", when using the batch command it's easy to miss error's, for example sometimes I'm getting error's 500 and 502 on crunchyroll, and it would be beneficial if these errors were written to a text file so I can know what didn't download, thank you very much.

**Comment by dstftw** [comment]
Just redirect `stderr` to file.

**Comment by BridgeUK** [comment]
@dstftw can you elaborate on that please

**Comment by BridgeUK** [comment]
@dstftw can you explain what you mean, please

**Comment by BridgeUK** [comment]
@dstftw I've tried "> output.txt" at the end of the command, but what happens is the errors are displayed in the command prompt and the successful output is put into the text file, but the errors that are displayed in the command prompt window don't have the corresponding filename so I cannot see which files didn't download
