### ISSUE TITLE
ERROR: Cannot parse data - video in closed facebook group

### ISSUE THREAD

**Issue by brylcreem** [rg3/youtube-dl#12496]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\tools\win-youtube-dl>youtube-dl.exe https://www.facebook.com/NAME/videos/10211688275223809/ --username XXX@XXX.XXX --password YYY --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.facebook.com/NAME/videos/10211688275223809/', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.03.16
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-75794-gd1c8368, ffprobe N-75794-gd1c8368, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 10211688275223809: Downloading webpage
[facebook] 10211688275223809: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\extractor\facebook.py", line 412, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\extractor\facebook.py", line 329, in _extract_from_url
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

This is a video uploaded by a user in a closed group on Facebook. I am able to view the video in the closed group. I had to turn off two-factor authentication to be able to get youtube-dl into it, otherwise I would just get a pop-up on my phone (and PC) asking me if I had just logged in.

I used the "--dump-pages" option to verify what was happening, and I do indeed get the webpage of the group, with the video itself focused, so the login is working, but the download itself fails.

I am not FB-friends with the person who uploaded the video. 

_If work on your *issue* requires account credentials please provide them or explain how one can obtain them._

My Facebook-login? Uh. Not in an open forum - please provide me with a way to give it to you securely.

**Comment by brylcreem** [comment]
Okay, now I closed the brackets around the check boxes, so that the check boxes actually appear on the list of issues - I *was* wondering what the deal with "0 of 4" was. Now I know 💃

**Comment by brylcreem** [comment]
Do you need any more information than I've already given?

About the login, I am able to send GPG-encrypted mail, if that is what's holding it up :)

**Comment by AlexisWilke** [comment]
Did you try to use the `--username` and `--password` command line options?

**Comment by uberRegenbogen** [comment]
I've been having this issue for the past several versions—including 2018.02.11.
It only occurs when using --netrc, or --username/--password.

**Comment by Natim** [comment]
I guess it doesn't make sense to use `_user: 0` when the user is logged in: https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/facebook.py#L358

**Comment by Natim** [comment]
@remitamine Can you tell me how I can help? That's the only message we get from youtube-dl. I tried investigating by running it from the source code and I would be glad to give you more information.

**Comment by remitamine** [comment]
first, post a **no modified full verbose log** with latest changes.

**Comment by Natim** [comment]
Thanks @remitamine I created https://github.com/rg3/youtube-dl/issues/17050 as a follow up
