### ISSUE TITLE
Problem download udacity nanodegree

### ISSUE THREAD

**Issue by banpie** [rg3/youtube-dl#12490]
I try to use `youtube-dl -u xxx -p xxx -o '~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://classroom.udacity.com/nanodegrees/nd001/` to download udacity nanodegree course, but get error message of "Unsupported URL: https://classroom.udacity.com/nanodegrees/nd001", does youtu-dl support udacity?

thanks!

**Comment by dstftw** [comment]
Not supported.
