### ISSUE TITLE
[iqiyi] Unable to extract album title

### ISSUE THREAD

**Issue by markhavemann** [rg3/youtube-dl#12504]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.20*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.20**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### OUTPUT: 

C:\Windows\System32>youtube-dl -v http://www.iqiyi.com/a_19rrhbcuq9.html
[debug] System config: []
[debug] User config: ['-o', 'Z:/Downloads/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.iqiyi.com/a_19rrhbcuq9.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.20
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-83280-gcba4f0e, ffprobe N-83280-gcba4f0e
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] 203227901: Download playlist page 2
[iqiyi] 203227901: Download playlist page 3
[iqiyi] 203227901: Download playlist page 4
[iqiyi] 203227901: Download playlist page 5
[iqiyi] 203227901: Download playlist page 6
[download] Downloading playlist: ??Z ???
[iqiyi] playlist ??Z ???: Collected 291 video ids (downloading 291 of them)
[download] Downloading video 1 of 291
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[iqiyi] 203227901: Download playlist page 2
[iqiyi] 203227901: Download playlist page 3
[iqiyi] 203227901: Download playlist page 4
[iqiyi] 203227901: Download playlist page 5
[iqiyi] 203227901: Download playlist page 6
[download] Downloading playlist: 203227901
[iqiyi] playlist 203227901: Collected 251 video ids (downloading 251 of them)
[download] Downloading video 1 of 251
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 740 video ids (downloading 740 of them)
[download] Downloading video 1 of 740
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 740 video ids (downloading 740 of them)
[download] Downloading video 1 of 740
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 740 video ids (downloading 740 of them)
[download] Downloading video 1 of 740
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 740 video ids (downloading 740 of them)
[download] Downloading video 1 of 740
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4

ERROR: Interrupted by user

<end of log>

---
### Description of your *issue*, suggested solution and other information

I have downloaded other media from this website successfully but this playlist keeps giving me errors. I just updated to the latest version and it still doesn't work. It is quite a long playlist so perhaps that is the problem. 

My configuration file looks like this: 

# Save options
-o Z:/Downloads/%(title)s.%(ext)s

**Comment by markhavemann** [comment]
Just to clarify, I am currently in China and can access the website without any problems, even though it may be restricted in other countries.

**Comment by yan12125** [comment]
I got a China proxy and it's working for me:
```
$ youtube-dl -v "http://www.iqiyi.com/a_19rrhbcuq9.html" --geo-verification-proxy "222.186.161.215:3128"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.iqiyi.com/a_19rrhbcuq9.html', '--geo-verification-proxy', '222.186.161.215:3128']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.24
[debug] Git HEAD: 54b960f34
[debug] Python version 3.6.0 - Linux-4.10.4-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] 203227901: Download playlist page 2
[iqiyi] 203227901: Download playlist page 3
[iqiyi] 203227901: Download playlist page 4
[iqiyi] 203227901: Download playlist page 5
[iqiyi] 203227901: Download playlist page 6
[download] Downloading playlist: 龙珠Z 国语版
[iqiyi] playlist 龙珠Z 国语版: Collected 291 video ids (downloading 291 of them)
[download] Downloading video 1 of 291
[iqiyi] temp_id: download video page
[iqiyi] a935566d7740de75d85ab11802691a80: Downloading JSON metadata
[debug] Invoking downloader on 'http://cache.m.iqiyi.com/mus/text/203227901/194ad02f3cbad88598bb4bb2ebe0d019/afbe8fd3d73448c9//20151120/37/f1/0b38282cd4d60651f7fef8336ec52602.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=419250000&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1490435521980&qd_sc=668ba80921aace4e55c970cec7468461&qypid=419250000_04022000001000000000_4&qd_k=e8353de4dc9a60cd022e919aae854c06&other='
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 169
[download] Destination: 龍珠Z 國語版：第1集 迷你悟饭-a935566d7740de75d85ab11802691a80.mp4
[download]   7.1% of ~88.95MiB at  5.14MiB/s ETA 00:16^C
ERROR: Interrupted by user
Exception ignored in: <_io.FileIO name='龍珠Z 國語版：第1集 迷你悟饭-a935566d7740de75d85ab11802691a80.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.FileIO name='龍珠Z 國語版：第1集 迷你悟饭-a935566d7740de75d85ab11802691a80.mp4.part' mode='wb' closefd=True>
```

Could you run ```youtube-dl -v http://www.iqiyi.com/a_19rrhbcuq9.html --write-pages``` and upload all *.dump files?

**Comment by markhavemann** [comment]
For some reason I couldn't upload the files directly so here is a link to them on Microsoft OneDrive: 

https://1drv.ms/u/s!Aga1JaEdoW7Rhm68JuOeBr9ZlzWX

**Comment by yan12125** [comment]
There should be a file called ```temp_id_http_-_www.iqiyi.com_a_19rrhbcuq9.html.dump```. Could you check again you've included all files in ```Youtube-dl Dumps Files.zip```? Also, could you paste the log of this command?
```
youtube-dl -v "http://www.iqiyi.com/a_19rrhbcuq9.html" --write-pages
```

**Comment by markhavemann** [comment]
Sorry for the long delay in my reply. I've uploaded the file you requested here: 

https://1drv.ms/u/s!Aga1JaEdoW7RiX5pRZd3aHw-K00r

I've also included two other dump files that were with it that might be needed. Is this what you mean by the log of that command:

PS C:\Users\User> youtube-dl -v "http://www.iqiyi.com/a_19rrhbcuq9.html" --write-pages
[debug] System config: []
[debug] User config: ['-o', 'Z:/Downloads/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.iqiyi.com/a_19rrhbcuq9.html', '--write-pages']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.20
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-83280-gcba4f0e, ffprobe N-83280-gcba4f0e
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] Saving request to temp_id_http_-_www.iqiyi.com_a_19rrhbcuq9.html.dump
[iqiyi] 203227901: Download playlist page 2
[iqiyi] Saving request to 203227901_http_-_cache.video.qiyi.com_jp_avlist_203227901_2_50_.dump
[iqiyi] 203227901: Download playlist page 3
[iqiyi] Saving request to 203227901_http_-_cache.video.qiyi.com_jp_avlist_203227901_3_50_.dump
[iqiyi] 203227901: Download playlist page 4
[iqiyi] Saving request to 203227901_http_-_cache.video.qiyi.com_jp_avlist_203227901_4_50_.dump
[iqiyi] 203227901: Download playlist page 5
[iqiyi] Saving request to 203227901_http_-_cache.video.qiyi.com_jp_avlist_203227901_5_50_.dump
[iqiyi] 203227901: Download playlist page 6
[iqiyi] Saving request to 203227901_http_-_cache.video.qiyi.com_jp_avlist_203227901_6_50_.dump
[download] Downloading playlist: ??Z ???
[iqiyi] playlist ??Z ???: Collected 291 video ids (downloading 291 of them)
[download] Downloading video 1 of 291
[iqiyi] temp_id: download video page
[iqiyi] Saving request to temp_id_http_-_www.iqiyi.com_v_19rrkoguv0.html.dump
WARNING: unable to extract album title; please report this issue on https://yt-dl.org/bug . Make sure you are using the
latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[iqiyi] 203227901: Download playlist page 2
[iqiyi] Saving request to 203227901_http_-_cache.video.qiyi.com_jp_avlist_203227901_2_50_.dump
[iqiyi] 203227901: Download playlist page 3
[iqiyi] Saving request to 203227901_http_-_cache.video.qiyi.com_jp_avlist_203227901_3_50_.dump
[iqiyi] 203227901: Download playlist page 4
[iqiyi] Saving request to 203227901_http_-_cache.video.qiyi.com_jp_avlist_203227901_4_50_.dump
[iqiyi] 203227901: Download playlist page 5
[iqiyi] Saving request to 203227901_http_-_cache.video.qiyi.com_jp_avlist_203227901_5_50_.dump
[iqiyi] 203227901: Download playlist page 6
[iqiyi] Saving request to 203227901_http_-_cache.video.qiyi.com_jp_avlist_203227901_6_50_.dump
[download] Downloading playlist: 203227901
[iqiyi] playlist 203227901: Collected 251 video ids (downloading 251 of them)
[download] Downloading video 1 of 251
[iqiyi] temp_id: download video page
[iqiyi] Saving request to temp_id_http_-_www.iqiyi.com_v_19rrok4nt0.html.dump
WARNING: unable to extract album title; please report this issue on https://yt-dl.org/bug . Make sure you are using the
latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_2_50_.dump
[iqiyi] 202861101: Download playlist page 3
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_3_50_.dump
[iqiyi] 202861101: Download playlist page 4
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_4_50_.dump
[iqiyi] 202861101: Download playlist page 5
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_5_50_.dump
[iqiyi] 202861101: Download playlist page 6
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_6_50_.dump
[iqiyi] 202861101: Download playlist page 7
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_7_50_.dump
[iqiyi] 202861101: Download playlist page 8
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_8_50_.dump
[iqiyi] 202861101: Download playlist page 9
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_9_50_.dump
[iqiyi] 202861101: Download playlist page 10
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_10_50_.dump
[iqiyi] 202861101: Download playlist page 11
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_11_50_.dump
[iqiyi] 202861101: Download playlist page 12
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_12_50_.dump
[iqiyi] 202861101: Download playlist page 13
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_13_50_.dump
[iqiyi] 202861101: Download playlist page 14
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_14_50_.dump
[iqiyi] 202861101: Download playlist page 15
[iqiyi] Saving request to 202861101_http_-_cache.video.qiyi.com_jp_avlist_202861101_15_50_.dump
[iqiyi] 202861101: Download playlist page 16

ERROR: Interrupted by user
PS C:\Users\User> youtube-dl -v "http://www.iqiyi.com/a_19rrhbcuq9.html" --write-pages

**Comment by nuomi1** [comment]
This is same for me in China.
[Youtube-dl Dumps Files.zip](https://github.com/rg3/youtube-dl/files/907955/Youtube-dl.Dumps.Files.zip)

**Comment by yan12125** [comment]
Sorry for the delay. I've tried to fix the issue based on those dump files. Could you verify it? @nuomi1 @markhavemann

**Comment by nuomi1** [comment]
@yan12125 OK.

**Comment by yan12125** [comment]
@nuomi1 Do you mean my patch indeed fixes the problem or you're going to try?

**Comment by markhavemann** [comment]
@yan12125 looks like it's worked for me! I can download without any errors so far. 

Thank you so much!!

**Comment by yan12125** [comment]
Thanks for the feedback. Feel free to leave comments if similar issues emerge again.
