### ISSUE TITLE
Unable to download multiple requested files of a single video

### ISSUE THREAD

**Issue by zeronotnull** [rg3/youtube-dl#12500]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.20*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'266/264/137/136,171', u'-k', u'-w', u'--no-mtime', u'https://www.youtube.com/watch?v=iNJdPyoqt8U', u'--merge-output-format', u'mkv', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.20
[debug] Python version 2.7.12 - Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] iNJdPyoqt8U: Downloading webpage
[youtube] iNJdPyoqt8U: Downloading video info webpage
[youtube] iNJdPyoqt8U: Extracting video information
[youtube] iNJdPyoqt8U: Downloading MPD manifest
[info] iNJdPyoqt8U: downloading video in 2 formats
[debug] Invoking downloader on u'https://r7---sn-vuxbavcx-5uie.googlevideo.com/videoplayback?id=88d25d3f2a2ab7c5&itag=266&source=youtube&requiressl=yes&pl=16&mv=m&ms=au&mn=sn-vuxbavcx-5uie&initcwndbps=826250&mm=31&pcm2cms=yes&ratebypass=yes&mime=video/mp4&gir=yes&clen=702406140&lmt=1478651470501289&dur=308.508&mt=1489960882&signature=675E20692C4672647DDF8CAA8DFB95DF303A972D.34BCF6AEFC186B38BD74BF925D5620CC70CF9A6C&key=dg_yt0&upn=buVw8DTcoUY&ip=94.66.41.198&ipbits=0&expire=1489982581&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mv,ms,mn,initcwndbps,mm,pcm2cms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: COSTA RICA IN 4K 60fps (ULTRA HD) w_ Freefly Movi-iNJdPyoqt8U.mp4
[download] 100% of 669.87MiB in 11:00
[debug] Invoking downloader on u'https://r7---sn-vuxbavcx-5uie.googlevideo.com/videoplayback?pcm2cms=yes&clen=5256850&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=audio%2Fwebm&ipbits=0&initcwndbps=826250&requiressl=yes&lmt=1473220729676385&dur=308.508&source=youtube&key=yt6&signature=487262F24C0C89AD6C9DC5D82AF3E7F38C276C48.4BB1006BA0E49BB48F1041BBA54FE2FB2FB2A9BA&gir=yes&expire=1489982581&upn=skL3jbwwUyU&itag=171&pl=16&ip=94.66.41.198&ms=au&ei=FQDPWPnQD5OiWP7HjZAC&mv=m&mt=1489960882&id=o-AAFVEs8sxlKb1p8980U_b_ysIWvQM3nxaB5mrE3nWViV&mn=sn-vuxbavcx-5uie&mm=31&keepalive=yes&ratebypass=yes'
[download] Destination: COSTA RICA IN 4K 60fps (ULTRA HD) w_ Freefly Movi-iNJdPyoqt8U.webm
[download] 100% of 5.01MiB in 00:04
```

---

---

### Description of your *issue*, suggested solution and other information

My Full HD Samsung TV cannot play 4K videos. As a result I have to bring any 4K video in its native resolution. In order to avoid typing multiple commands I followed the information written in the help files and issued the below commands but I only got one video file not four as I expected.

command for the URL:
var="https://www.youtube.com/watch?v=iNJdPyoqt8U"

command for the videos list:
youtube-dl -F -k -w --no-mtime --prefer-free-formats --audio-format "best" --audio-quality 0 $var --verbose

command for the combo downloading:
youtube-dl -f 266/264/137/136,171 -k -w --no-mtime $var --merge-output-format mkv --verbose

the following commands were also tried and gave similar poor results:
youtube-dl -f 266/264/137/136 -k -w --no-mtime $var --merge-output-format mkv --verbose
youtube-dl -f 136/137/264/266 -k -w --no-mtime $var --merge-output-format mkv --verbose
youtube-dl -f 266,264,137,136 -k -w --no-mtime $var --merge-output-format mkv --verbose
youtube-dl -f 266+171,264+171,137+171,136+171 -k -w --no-mtime $var --merge-output-format mkv --verbose
youtube-dl -f 266+264+137+136+171 -k -w --no-mtime $var --merge-output-format mkv --verbose
youtube-dl -f 266+264+137+136 -k -w --no-mtime $var --merge-output-format mkv --verbose

**Comment by dstftw** [comment]
Provide **full complete** log of what you type and what you get.

**Comment by dstftw** [comment]
With `-f 266/264/137/136,171` you get two videos not one as it clearly seen from the log:
```
[info] iNJdPyoqt8U: downloading video in 2 formats
...
[download] Destination: COSTA RICA IN 4K 60fps (ULTRA HD) w_ Freefly Movi-iNJdPyoqt8U.mp4
...
[download] Destination: COSTA RICA IN 4K 60fps (ULTRA HD) w_ Freefly Movi-iNJdPyoqt8U.webm
```
`-f 266/264/137/136,171` is not supposed to download 4 videos. Several videos to be downloaded are separated with comma not slash. Bother to read [FAQ](https://github.com/rg3/youtube-dl#format-selection).
If you download several formats with the same extension you must provide [output template](https://github.com/rg3/youtube-dl#output-template) with `format_id` to ensure filename unicity.
