### ISSUE TITLE
Is it possible to restart a failed download till its successful?

### ISSUE THREAD

**Issue by bythckr** [rg3/youtube-dl#12509]
### What is the purpose of your *issue*?
- [ ] Question

I am using OSX + iterm + zsh.

This issue was [already asked](https://github.com/rg3/youtube-dl/issues/6404), but the solution was to use MPV and I do not want to play the video immediately after download. Is it possible to repeat until successful?

**Comment by dstftw** [comment]
Write a sh script that will loop until successful exitcode.
