### ISSUE TITLE
Extractor for streamuj.tv / sosac.tv

### ISSUE THREAD

**Issue by tb3d** [rg3/youtube-dl#12510]
Hello, can you help me write a script that extracts stream URL and subtitles from player on this URL (e.g.) http://tv.sosac.tv/cs/player/na-dozivoti-s2-e21 

This is an addon, that works in Kodi:
https://github.com/kodi-czsk/plugin.video.sosac.ph?files=1

Thanks everyone for help!

**Comment by tb3d** [comment]
Is there someone, who knows how to help me? Thank you for any answer and solution.

**Comment by yan12125** [comment]
Tried http://tv.sosac.tv/cs/player/na-dozivoti-s2-e21 and several other videos on that site, but got no videos. Is the site broken?

**Comment by yan12125** [comment]
Closing as no reply for a long time.
