### ISSUE TITLE
Possible Bug: --reject-title not rejecting?

### ISSUE THREAD

**Issue by BridgeUK** [rg3/youtube-dl#12521]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.22**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

---

### Description of your *issue*, suggested solution and other information

Hi, I'm not 100% sure if this is a bug or not, when I use "--reject-title REGEX" it should be skipping a matching file, instead it still shows "[ffmpeg] Fixing malformated aac bitstream" for each file, is there a way I can stop "[ffmpeg] Fixing malformated aac bitstream" from appearing when a matching file is found, thank you very much

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by BridgeUK** [comment]
@dsftw sorry I forgot to paste that in

```
youtube-dl.exe --write-sub --sub-format srt --sub-lang enUS --wri
te-description http://www.crunchyroll.com/07-ghost/episode-1-the-future-of-painf
ul-thoughts-is-573284 --reject-title REGEX --ignore-errors -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--write-sub', '--sub-format', 'srt', '--sub-lang',
'enUS', '--write-description', 'http://www.crunchyroll.com/07-ghost/episode-1-th
e-future-of-painful-thoughts-is-573284', '--reject-title', 'REGEX', '--ignore-er
rors', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.03.22
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-83410-gb1e2192, ffprobe N-83410-gb1e2192
[debug] Proxy map: {}
[Crunchyroll] 573284: Downloading webpage
[Crunchyroll] 573284: Downloading media info for 360p
[Crunchyroll] 573284: Downloading m3u8 information
[Crunchyroll] 573284: Downloading media info for 480p
[Crunchyroll] 573284: Downloading m3u8 information
[Crunchyroll] 573284: Downloading media info
[Crunchyroll] 573284: Downloading subtitles for English (US)
[info] Writing video description to: 07 Ghost Episode 1 - The Future of Painful
Thoughts is-573284.description
[info] Writing video subtitles to: 07 Ghost Episode 1 - The Future of Painful Th
oughts is-573284.enUS.srt
[debug] Invoking downloader on 'https://v.vrv.co/evs/assets/7ynblen9uq7h2k0_1567
575.mp4/index-v1-a1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92
LnZydi5jby9ldnMvYXNzZXRzLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9j
aFRpbWUiOjE0OTAxNDI3NDd9fX1dfQ__&Signature=Eiw-kC3NZEc0EUoC-GVxro6M6j8xXP~N9Oc-L
FPGEKGyx9yV0zDyjMklOupsVxKwRQEkYKg1ajfwrXzoOE~~KChr~nbQr~rw5iYiHotUPdtVccYj5PCVH
DhziXJ9qYRTzFTb-tTJnsC7F7djMC4~Paz0BQZ5tjeWt1Qpv3Ti4s~hKSzsypnBdmaKu7a25RxdJsZq1
VePWFuKoOBW70tinpXUO8KvgnYG6rPHwXz~jWFibD5ZAhICkm2NVLkkZDRurGZW48TBfdXKBBBsA2CMp
bt2eq-YYAMIAlDkPRGLLVYJs88Y1dpPdtSqibT9LTCK90MjDjPM5fUcDasqX25~zQ__&Key-Pair-Id=
APKAJKQQ2INNHTYFB44A'
[download] 07 Ghost Episode 1 - The Future of Painful Thoughts is-573284.mp4 has
 already been downloaded
[download] 100% of 119.89MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:07 Ghost Episode 1 - Th
e Future of Painful Thoughts is-573284.mp4'
[ffmpeg] Fixing malformated aac bitstream in "07 Ghost Episode 1 - The Future of
 Painful Thoughts is-573284.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:07 Ghost Episode 1 - The Future
of Painful Thoughts is-573284.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:07
Ghost Episode 1 - The Future of Painful Thoughts is-573284.temp.mp4'
```

**Comment by dstftw** [comment]
Did you even read the description of `--reject-title`?

**Comment by BridgeUK** [comment]
@dstftw I did, it says, "Skip download for matching titles"

**Comment by BridgeUK** [comment]
I'm just wondering why it still does "[ffmpeg] Fixing malformated aac bitstream" even though it doesn't edit the file

**Comment by dstftw** [comment]
`REGEX` must be
>(regex or caseless sub-string)

not a "REGEX" literal.

**Comment by BridgeUK** [comment]
@dstftw "--reject-title regex" still doesn't skip the "[ffmpeg] Fixing malformated aac bitstream" though

**Comment by dstftw** [comment]
:man_facepalming:
it should be **your custom string** that will be used for rejecting by title, e.g. `--reject-title facepalm` will reject all videos with "facepalm" in it's title.

**Comment by BridgeUK** [comment]
@dstftw i'm really sorry i didn't understand before, now i fully understand, thank you very much for your time and help, i really appreciate it

**Comment by BridgeUK** [comment]
I'd just like to add, in case anyone reads this, I make a mistake, this was not what I was after, but I have sorted it now :+1:  thanks @dstftw
