### ISSUE TITLE
No video Format Found

### ISSUE THREAD

**Issue by MYounas** [rg3/youtube-dl#12528]
youtube -dl version is 2017.3.22
I:\>youtube-dl --verbose -u temp -p temp -o "/Building a Web App with ASP.NET Core, MVC 6, EF Core, and Angular/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s" https://app.pluralsight.com/library/courses/aspdotnetcore-efcore-bootstrap-angular-web-app/table-of-contents
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '-o', '/Building a Web App with ASP.NET Core, MVC 6, EF Core, and Angular/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s', 'https://app.pluralsight.com/library/courses/aspdotnetcore-efcore-bootstrap-angular-web-app/table-of-contents']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.22
[debug] Python version 3.5.2 - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg N-83096-g6596b34, ffprobe N-83096-g6596b34
[debug] Proxy map: {}
[pluralsight:course] aspdotnetcore-efcore-bootstrap-angular-web-app: Downloading course JSON
[download] Downloading playlist: Building a Web App with ASP.NET Core, MVC 6, EF Core, and Angular
[pluralsight:course] playlist Building a Web App with ASP.NET Core, MVC 6, EF Core, and Angular: Collected 112 video ids (downloading 112 of them)
[download] Downloading video 1 of 112
[pluralsight] Downloading login page
[pluralsight] Logging in as younus.ubit@outlook.com
[pluralsight] aspdotnetcore-efcore-bootstrap-angular-web-app-m0-0: Downloading JSON metadata
[pluralsight] aspdotnetcore-efcore-bootstrap-angular-web-app-m0-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] aspdotnetcore-efcore-bootstrap-angular-web-app-m0-0: Waiting for 4 seconds to avoid throttling
[debug] Invoking downloader on 'http://vid20.pluralsight.com/clip-videos/shawn-wildermuth/aspdotnetcore-efcore-bootstrap-angular-web-app-m0/aspdotnetcore-efcore-bootstrap-angular-web-app-m0-01/1280x720mp4/20160722151418.mp4?MMXhiEXQF1S1U_Lulla0sntnwukgy2cnwFAdv2fYuVKz3d1IzCOoDEh6dWcdUEDlnlXLj40AN1h_TvyPPuKJxW_hD9KICpHETRZPvL8pFz5NMMrHvzj-9yBI5ePw-XmgI3MceakZMiQumw4sTqxgPCfUWfPgDC39pf83K8msJsC0F8wWX2qgn9ZdKFkGxe1bzexIsPe1sM1hga9NU4phaKDfMTDC64RJGDxc2eoPk61DZdd6n80GJGWtS3lRfPZzBQY12Ul9eAENvFq3lWXIpfXAn-Uv3Lgr7P6cor0xHzDk'
[download] Building a Web App with ASP.NET Core, MVC 6, EF Core, and Angular\1 - Course Overview\Course Overview.mp4 has already been downloaded
[download] 100% of 4.67MiB
[download] Downloading video 2 of 112
[pluralsight] aspdotnetcore-efcore-bootstrap-angular-web-app-m1-0: Downloading JSON metadata
[pluralsight] aspdotnetcore-efcore-bootstrap-angular-web-app-m1-0: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Unauthorized
[pluralsight] aspdotnetcore-efcore-bootstrap-angular-web-app-m1-0: Waiting for 5 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\my\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\my\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 428, in extract
    ie_result = self._real_extract(url)
  File "c:\users\my\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\pluralsight.py", line 288, in _real_extract
    self._sort_formats(formats)
  File "c:\users\my\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 1031, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Can you watch it in browser in the first place? Prove with screenshot of the second video being played.

**Comment by MYounas** [comment]
Soory It was my bad,
my pluralsight subscription is just end,thats why it not proceed,Thankx for response.
