### ISSUE TITLE
When using ytuser:ChannelName, the "playlist_title" doesn't work

### ISSUE THREAD

**Issue by komarnicki** [rg3/youtube-dl#12522]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.22**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I'm trying to download all videos from a YouTube channel and put them in a directory that matches playlist name.

`youtube-dl ytuser:ChannelFooBarBaz -f best -o '%(playlist_title)s/%(playlist_index)s_%(upload_date)s_%(title)s'`

The problem with the above syntax is that all videos are being pulled to the same directory called `Uploads from ChannelFooBarBaz` instead of playlist name's a particular video is assigned to.

For example if channel has `Playlist Foo` and `Playlist Bar` it should create 2 directories and pull corresponding video there. Now everything lands in `Uploads from ChannelFooBarBaz`.

The issue is probably around `%(playlist_title)s` but according to the docs:

>	playlist_title (string): Playlist title

it should be pretty straightforward.

Problem is solved only when I replace `ytuser:ChannelFooBarBaz` with explicit URL to a single playlist. Then directory name is correct, but if a channel has 50 playlists, I don't want to manually do this 50 times.

What am I doing wrong?

**Comment by dstftw** [comment]
You must use playlists URL not ytuser: https://www.youtube.com/user/.../playlists.
