### ISSUE TITLE
Request: Some type of support for URL's that have season/epsiode info in the titles

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#12533]
Youtube-dl does not currently give a good filename for URL's like:

youtube-dl http://abc.go.com/shows/time-after-time/episode-guide/season-01/4-secrets-stolen

This is not really YouTube-dl's fault -- ABC is returning a filename of "Secrets-stolen". This is affecting at least all of TimeAfterTime and OnceUponATime at ABC. It may affect others as well.

But note that the season and episode number info is in the URL, even if not in the filename supplied at the remote end.

This is a request for some ability to generate season/episode numbers into the output filename when there isn't any. And yes, I know that's a hard problem in general, but I figure there's some heuristics available, such as looking for a leading number in the filename / numbers in the URL.

**Comment by dstftw** [comment]
This can't be used as general purpose heuristic.
