### ISSUE TITLE
How can I avoid the DASH format?

### ISSUE THREAD

**Issue by montanaflynn** [rg3/youtube-dl#12531]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

We have ran into problems with the DASH format served by youtube and would like to avoid that format. I couldn't find out how to do this with the format selectors. I did find a somewhat related issue (https://github.com/rg3/youtube-dl/issues/1808) which would allow us to avoid them but that is a super old and unclosed issue.

Here's the video and all it's formats:

```
youtube-dl -F  "https://www.youtube.com/watch?v=lC6dgtBU6Gs"
[youtube] lC6dgtBU6Gs: Downloading webpage
[youtube] lC6dgtBU6Gs: Downloading video info webpage
[youtube] lC6dgtBU6Gs: Extracting video information
[youtube] lC6dgtBU6Gs: Downloading MPD manifest
[info] Available formats for lC6dgtBU6Gs:
format code  extension  resolution note
140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k (44100Hz), 2.80MiB
171          webm       audio only DASH audio  135k , 1fps, vorbis@128k, 2.54MiB
160          mp4        256x144    DASH video  110k , avc1.4d400c, 15fps, video only, 2.37MiB
242          webm       426x238    240p  184k , vp9, 1fps, video only, 3.37MiB
133          mp4        426x238    DASH video  249k , avc1.4d4015, 30fps, video only, 5.32MiB
243          webm       640x358    360p  355k , vp9, 1fps, video only, 6.27MiB
134          mp4        640x358    DASH video  375k , avc1.4d401e, 30fps, video only, 6.07MiB
244          webm       854x478    480p  664k , vp9, 1fps, video only, 11.78MiB
135          mp4        854x478    DASH video  716k , avc1.4d401f, 30fps, video only, 12.19MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
18           mp4        640x358    medium , avc1.42001E, mp4a.40.2@ 96k
43           webm       640x360    medium , vp8.0, vorbis@128k (best)
```

**Comment by dstftw** [comment]
`-f bestvideo[protocol!=http_dash_segments]`.

**Comment by montanaflynn** [comment]
Thanks!

**Comment by 4goettma** [comment]
I didn't had success with the solution given by @dstftw . Also the `--youtube-skip-dash-manifest` flag just works for videos on Youtube.
The solution I came up with was using `-f best`. To cite the [README.md/Format Selection](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection): "best: Select the best quality format represented by a single file with video and audio." Since dash format is often composed of a seperate audio and video track, this parameter forced youtube-dl to choose the conventional video file.
