### ISSUE TITLE
cannot download youtube-dl.exe

### ISSUE THREAD

**Issue by luoyanghero** [rg3/youtube-dl#12537]
I can visit youtube page, but I cannot download youtube-dl.exe , I have tried many times. Is there some limits?

**Comment by Hrxn** [comment]
Probably because of Internet in China...

**Comment by luoyanghero** [comment]
Now I have download youtube-dl.exe.
I can visit youtube page.
This is a page about jinyong https://www.youtube.com/watch?v=fHhk9fDe_MQ
But cannot download the video using youtube-dl, the error as following:
> _>youtube-dl.exe https://www.youtube.com/watch?v=fHhk9fDe_MQ
> [youtube] fHhk9fDe_MQ: Downloading webpage
> ERROR: Unable to download webpage: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。> (caused by URLError(TimeoutError(10060, '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。', None, 10060, None),))_
>

**Comment by stdlog** [comment]
use proxy with youtube-dl , e.g
 youtube-dl --proxy PROXY_ADDRESS https://www.youtube.com/watch?v=fHhk9fDe_MQ
if you use ss ,then proxy_address could be socks5://127.0.0.1:1080/
proxy usage documented here: https://github.com/rg3/youtube-dl#network-options

**Comment by yan12125** [comment]
@luoyanghero Could you watch videos without proxies or VPNs in browsers? What @Hrxn said is a possible reason. AFAIK in China, YouTube is blocked and connections to GitHub are interfered. @stdlog's suggestion should be useful, too.

**Comment by dstftw** [comment]
Closing since it's most definitely not a youtube-dl issue.

**Comment by luoyanghero** [comment]
@stdlog yes, it needs proxy option

**Comment by berxtjkl** [comment]
> youtube-dl --proxy PROXY_ADDRESS https://www.youtube.com/watch?v=fHhk9fDe_MQ

Thanks bro, it helps.
