### ISSUE TITLE
Help wanted: Information on "optimum" subtitle format

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#12534]
So I'm getting a lot of .ttml subtitle files. And having a separate subtitle file isn't too big of a problem.

But neither vlc nor mplayer can handle these.

And while youtube-dl does have a "convert subtitle" option, it isn't (as far as I can tell) "convert ttml to this, convert tt to that", it is "convert everything to one unifying all-encompassing format".

And I don't know the advantages/disadvantages of one subtitle format over another, nor even the limitations of youtube-dl's ability to convert.

So what is the recommended "This is the 15th format that obsoletes all the earlier 14 formats" ultimate subtitle format to convert to?

**Comment by dstftw** [comment]
There is no such format.

**Comment by keybounce** [comment]
Fair enough.

What is the "best" way to deal with being served some "useful" subtitles, and some that need to be converted -- how do I convert the ones that are not usable as-is (ttml, tt), and what should they be converted to, without converting the ones that are good as-is?

**Comment by dstftw** [comment]
Convert to the format supported by your player. Again, there is no "not usable as-is" or "good as-is" formats, check which is supported by your player and convert correspondingly.
