### ISSUE TITLE
Custom Extractor - Get data from video

### ISSUE THREAD

**Issue by tb3d** [rg3/youtube-dl#12542]
Hello, I am working on custom extractor and it's first thing, which I'm programming in Python.

When I open URL of video in my browser, video starts auto play. But when I get HTML code from extractor in "def _real_extract", I get only HTML, where video is not played, so I don't have any access to the video sources and subtitles. So, how can I "play" this video from Python and extract information from new HTML code? 

Thanks! And sorry for english.

**Comment by dstftw** [comment]
You can't play it without browser, What you should do is to reverse engineer browser's behavior and reproduce it as python code.

**Comment by tb3d** [comment]
Do you have some example code? Because I really don't know, how it everything works. :(
