### ISSUE TITLE
402 payment required, help me 

### ISSUE THREAD

**Issue by brandonj159** [rg3/youtube-dl#12553]
2017/03/25 09:03:03 2ec30916 217f93c5 INFO   PRIVATE-CHAT [!                   вяαη∂ση] !ytdl [URL]https://www.youtube.com/watch?v=FA0vHL_WrLg&t=555s[/URL]
2017/03/25 09:03:03 2ec30916 217f93c5 INFO   CHAT 1 [admin @ !                   вяαη∂ση] < !ytdl [URL]https://www.youtube.com/watch?v=FA0vHL_WrLg&t=555s[/URL] > / OK
2017/03/25 09:03:03 2ec30916 217f93c5 INFO   PRIVATE-CHAT [мιnecraғт aυтнenтιc gaмerѕ] Downloading https://www.youtube.com/watch?v=FA0vHL_WrLg&t=555s
2017/03/25 09:03:04 2ec30916 217f93c5 INFO   PRIVATE-CHAT [мιnecraғт aυтнenтιc gaмerѕ] Download failed for https://www.youtube.com/watch?v=FA0vHL_WrLg&t=555s; file not found

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
