### ISSUE TITLE
Error with Windows %HOMEPATH%, shows unsupported format character 'H'

### ISSUE THREAD

**Issue by iripu** [rg3/youtube-dl#12556]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\>youtube-dl -v https://www.youtube.com/watch?v=KblOFvCM98E
[debug] System config: []
[debug] User config: ['-o', 'C:\\%HOMEPATH%\\Desktop\\%%(title)s.%%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=KblOFvCM98E']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.24
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-84348-gdb7a05d, ffprobe N-84348-gdb7a05d
[debug] Proxy map: {}
[youtube] KblOFvCM98E: Downloading webpage
[youtube] KblOFvCM98E: Downloading video info webpage
[youtube] KblOFvCM98E: Extracting video information
[youtube] KblOFvCM98E: Downloading MPD manifest
ERROR: Error in output template: unsupported format character 'H' (0x48) at index 4 (encoding: 'cp1252')
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\YoutubeDL.py", line 676,
in prepare_filename
ValueError: unsupported format character 'H' (0x48) at index 4
```

### Description of your *issue*, suggested solution and other information

I have tried using single % in `%%(title)s.%%(ext)s`, gives same error. Also, tried `-o "%HOMEPATH%\Desktop\%%(title)s.%%(ext)s"`, same error except last line says `...at index 1`.

**Comment by dstftw** [comment]
Post the output of `echo %HOMEPATH%` from the same session.

**Comment by iripu** [comment]
`\Users\ripu`

**Comment by iripu** [comment]
Same issue reppeared:
```
F:\>youtube-dl https://www.youtube.com/watch?v=ZVQfR27ISjM
[youtube] ZVQfR27ISjM: Downloading webpage
[youtube] ZVQfR27ISjM: Downloading video info webpage
[youtube] ZVQfR27ISjM: Extracting video information
ERROR: Error in output template: unsupported format character 'H' (0x48) at index 4 (encoding: 'cp1252')
```

I tried to download this video: [https://www.youtube.com/watch?v=ZVQfR27ISjM](https://www.youtube.com/watch?v=ZVQfR27ISjM).

My config has this line:

`-o "C:\%HOMEPATH%\Desktop\%(title)s-%(height)sp.%(ext)s"`

If I comment that line it works. My homepath is: `C:\Users\ripu`

**Comment by iripu** [comment]
Same issue reppeared:
```

F:\>youtube-dl -v https://www.youtube.com/watch?v=ZVQfR27ISjM
[debug] System config: []
[debug] User config: ['--no-mtime', '--console-title', '-o', 'C:\\%HOMEPATH%\\Desktop\\%(title)s-%(height)sp.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=ZVQfR27ISjM']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-84348-gdb7a05d, ffprobe N-84348-gdb7a05d
[debug] Proxy map: {}
[youtube] ZVQfR27ISjM: Downloading webpage
[youtube] ZVQfR27ISjM: Downloading video info webpage
[youtube] ZVQfR27ISjM: Extracting video information
[youtube] {22} signature length 40.40, html5 player vflppxuSE
[youtube] {43} signature length 40.40, html5 player vflppxuSE
[youtube] {18} signature length 40.40, html5 player vflppxuSE
[youtube] {36} signature length 40.40, html5 player vflppxuSE
[youtube] {17} signature length 40.40, html5 player vflppxuSE
[youtube] {137} signature length 40.40, html5 player vflppxuSE
[youtube] {248} signature length 40.40, html5 player vflppxuSE
[youtube] {136} signature length 40.40, html5 player vflppxuSE
[youtube] {247} signature length 40.40, html5 player vflppxuSE
[youtube] {135} signature length 40.40, html5 player vflppxuSE
[youtube] {244} signature length 40.40, html5 player vflppxuSE
[youtube] {134} signature length 40.40, html5 player vflppxuSE
[youtube] {243} signature length 40.40, html5 player vflppxuSE
[youtube] {133} signature length 40.40, html5 player vflppxuSE
[youtube] {242} signature length 40.40, html5 player vflppxuSE
[youtube] {160} signature length 40.40, html5 player vflppxuSE
[youtube] {278} signature length 40.40, html5 player vflppxuSE
[youtube] {140} signature length 40.40, html5 player vflppxuSE
[youtube] {171} signature length 40.40, html5 player vflppxuSE
[youtube] {249} signature length 40.40, html5 player vflppxuSE
[youtube] {250} signature length 40.40, html5 player vflppxuSE
[youtube] {251} signature length 40.40, html5 player vflppxuSE
ERROR: Error in output template: unsupported format character 'H' (0x48) at index 4 (encoding: 'cp1252')
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\YoutubeDL.py", line 675,
in prepare_filename
ValueError: unsupported format character 'H' (0x48) at index 4
```

I tried to download this video: [https://www.youtube.com/watch?v=ZVQfR27ISjM](https://www.youtube.com/watch?v=ZVQfR27ISjM).

My config has this line:

`-o "C:\%HOMEPATH%\Desktop\%(title)s-%(height)sp.%(ext)s"`

If I comment that line it works. My homepath is: `C:\Users\ripu`
