### ISSUE TITLE
videos converted to mp3 remerge mp3 even though video download is skipped; mp3 processing should be skipped too

### ISSUE THREAD

**Issue by IsraelTorres** [rg3/youtube-dl#12557]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v --extract-audio --audio-format mp3 --prefer-ffmpeg --ffmpeg-location "/videobins" "https://www.youtube.com/channel/UCfgmMDI7T5tOQqjnOBRe_wg"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--extract-audio', u'--audio-format', u'mp3', u'--prefer-ffmpeg', u'--ffmpeg-location', u'/videobins', u'https://www.youtube.com/channel/UCfgmMDI7T5tOQqjnOBRe_wg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.24
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.4-tessus, ffprobe 3.1.4-tessus
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

currently using a workaround (mp3 funnel) that matches the video ID to existing converted mp3 in download directory and skips download attempt. Must first pull down video IDs separately and use the artifact as a guide to match against. Would be great if it was integrated as smart as the existing videos are instead of remerging them, even after dupe detection... literally watching my mp3s getting overwritten on each update :(

---

### Description of your *issue*, suggested solution and other information

videos converted to mp3 are not skipped and still merged when unnecessary, even though when video is detected as duplicate; the conversion takes place regardless making for a less efficient means of downloading small updates on a channel.

**Comment by dstftw** [comment]
Use `--download-archive`.
