### ISSUE TITLE
Download Instagram Stories live videos

### ISSUE THREAD

**Issue by Bangaio64** [rg3/youtube-dl#12551]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs 

`https://scontent-gru2-1.cdninstagram.com/hvideo-ash1/v/dash-hd/17864477266113759.mpd?_nc_rl=AfAoand0aCNvXEPA&oh=d61cd78abd6caa2993a4413c596ead1e&oe=58D82BF0`

```
<?xml version="1.0"?>
<MPD
    type="dynamic"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    availabilityStartTime="2017-03-08T21:51:21-08:00"
    availabilityEndTime="2017-03-08T21:54:14-08:00"
    publishFrameTime="21"
    minimumUpdatePeriod="PT1S"
    minBufferTime="PT1S"
    timeShiftBufferDepth="P00Y00M00DT00H00M10.00S"
    suggestedPresentationDelay="PT2S"
    profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:mpeg:dash:profile:isoff-live:2011"
    xmlns:xsi="http://www.w3.org/2011/XMLSchema-instance"
    xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd">
  <Period start="PT0S" id="dash">
    <AdaptationSet
        id="1"
        segmentAlignment="true"
        maxWidth="396"
        maxHeight="704"
        maxFrameRate="30">
      <Representation
          id="live-hd_H264"
          mimeType="video/mp4"
          codecs="avc1.4d401f"
          width="396"
          height="704"
          FBQualityClass="sd"
          FBQualityLabel="396p"
          frameRate="30"
          sar="1:1"
          startWithSAP="1"
          bandwidth="768000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="17862473032125030-$Time$.m4v"
            initialization="17862473032125030-init.m4v">
          <SegmentTimeline>
             <S t="163000" d="1000"/>
             <S t="164000" d="1000"/>
             <S t="165000" d="1000"/>
             <S t="166000" d="1000"/>
             <S t="167000" d="1000"/>
             <S t="168000" d="1000"/>
             <S t="169000" d="1000"/>
             <S t="170000" d="1000"/>
             <S t="171000" d="1000"/>
             <S t="172000" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet
        id="2"
        segmentAlignment="true">
      <AudioChannelConfiguration
          schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
          value="1"/>
      <Representation
          id="17862473032125030_AAC"
          mimeType="audio/mp4"
          codecs="mp4a.40.2"
          audioSamplingRate="44100"
          startWithSAP="1"
          bandwidth="64000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="17862473032125030-$Time$.m4a"
            initialization="17862473032125030-init.m4a">
          <SegmentTimeline>
             <S t="163000" d="1000"/>
             <S t="164000" d="1000"/>
             <S t="165000" d="1000"/>
             <S t="166000" d="1000"/>
             <S t="167000" d="1000"/>
             <S t="168000" d="1000"/>
             <S t="169000" d="1000"/>
             <S t="170000" d="1000"/>
             <S t="171000" d="1000"/>
             <S t="172000" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

---

### Description of your *issue*, suggested solution and other information

Instagram Stories live videos use .mpd manifests, and as youtube-dl has a mpd downloader, I thought it may be possible to download them. I used the chrome extension "Chrome IG Story", then the network inspector to grab the mpd file.

**Comment by sabriele** [comment]
May I know which issue this is a duplicate of please? Is there already support for Instagram's **Live Videos** (not Stories) and how should I go about downloading them with youtube-dl?

**Comment by hanoii** [comment]
I'd like to know as well

**Comment by danieltroger** [comment]
@dstftw can you please provide a link to the duplicate issue?

**Comment by ale-carra** [comment]
I tried using youtube-dl to download the Instagram live video stream using the dash url used by instagram that I grabbed using Firefox developer tools. However it fails with a 403 error. I tried setting the cookies, referer and user agent to those used by Firefox but it didn't work.

**Comment by Diti** [comment]
Why is this issue closed?
