### ISSUE TITLE
Unable to login. Twitch said: Please complete the CAPTCHA correctly.

### ISSUE THREAD

**Issue by flugasak** [rg3/youtube-dl#12564]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Output

$ ./youtube-dl -f high -u flugasak -p hunter2 https://www.twitch.tv/videos/125404543 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'high', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.twitch.tv/videos/125404543', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.26
[debug] Python version 2.7.12 - Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[twitch:vod] Downloading login page
[twitch:vod] Logging in as flugasak
ERROR: Unable to login. Twitch said: Please complete the CAPTCHA correctly.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/twitch.py", line 83, in login_step
    headers=headers)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 651, in _download_json
    encoding=encoding, data=data, headers=headers, query=query)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 619, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 526, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 506, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
    self.initialize()
  File "./youtube-dl/youtube_dl/extractor/common.py", line 385, in initialize
    self._real_initialize()
  File "./youtube-dl/youtube_dl/extractor/twitch.py", line 56, in _real_initialize
    self._login()
  File "./youtube-dl/youtube_dl/extractor/twitch.py", line 106, in _login
    'password': password,
  File "./youtube-dl/youtube_dl/extractor/twitch.py", line 88, in login_step
    fail(response['message'])
  File "./youtube-dl/youtube_dl/extractor/twitch.py", line 65, in fail
    'Unable to login. Twitch said: %s' % message, expected=True)
ExtractorError: Unable to login. Twitch said: Please complete the CAPTCHA correctly.

```
---

### Description 

I was trying to download a twitch video from a channel I subscribe to, but it seems twitch has changed something with the captcha. It's happened before, and those times I've simply updated to the latest version of youtube-dl, which has fixed it. This time that wasn't enough, so apparently twitch is updating it more often now.

Either way, it seems youtube-dl can't get past the captcha at the moment.

**Comment by dstftw** [comment]
youtube-dl is not supposed to bypass captcha - it's your responsibility. Go to website and solve it, then export cookies and pass to youtube-dl with `--cookies`.

**Comment by flugasak** [comment]
Then I suggest the error message for this be changed to reflect this. Perhaps with some instructions or, at least, tips on how to do that. 

But at the very least remove this part:

> Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); **please report this issue on https://yt-dl.org/bug**

**Comment by Cryspart** [comment]
Instead of logging with your personal account, is there a way of using your personal client-id and twitch api secret to download a subscriber only vod without the captcha ? (and without the need to use the cookie)

I have tested:
`--add-header client-id:$CLIENT_ID`+`--add-header twitch-api-secret:$SECRET`
But it doesn't seem to work, I have also tested to use only the client-id or only the secret.

The client-id and secret I am using correspond to a subscribed account to the channel

I have youtube-dl version: `2017.03.26`

command: `youtube-dl -F --add-header client-id:$CLIENT_ID --add-header twitch-api-token:$SECRET https://www.twitch.tv/videos/131806791 --verbose`

output:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'--add-header', u'client-id:$CLIENT_ID', u'--add-header', u'twitch-api-token:$SECRET', u'https://www.twitch.tv/videos/131806791', u'--verbose']
[debug] Adding header from command line option client-id:$CLIENT_ID
[debug] Adding header from command line option twitch-api-token:$SECRET
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2017.03.26
[debug] Python version 2.7.6 - Linux-4.9.13-moby-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg git-2017-01-22-f1214ad, ffprobe git-2017-01-22-f1214ad
[debug] Proxy map: {'no': '*.local, 169.254/16'}
[twitch:vod] 131806791: Downloading vod info JSON
[twitch:vod] 131806791: Downloading vod access token
[twitch:vod] 131806791: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 403: ERROR (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 497, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2094, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```
