### ISSUE TITLE
[Major] Completly wrong duration of video (seems twice longer) because of `--embed-subs` option

### ISSUE THREAD

**Issue by sebma** [rg3/youtube-dl#12568]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.03.26
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

---

Hi,

When downloading this video (http://www.youtube.com/watch?v=srffsSlR0og) without the`--embed-subs` option, the duration is "01:20:28.59" but when downloading it with the`--embed-subs` option, the duration becomes "02:39:05.95" (almost twice longer !) : 

```
$ youtube-dl -v --embed-subs http://www.youtube.com/watch?v=srffsSlR0og;ffprobe Joseph_Prince_2016_online_-_The_Root_Cause_Of_Your_Problem_Is_Condemnation__18__srffsSlR0og.mp4 2>&1 | egrep "Input|Duration:"

[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg', u'--no-warnings', u'--restrict-filenames', u'-o', u'%(title)s__%(format_id)s__%(id)s.%(ext)s', u'--format', u'mp4/webm/best', u'--add-metadata', u'--write-auto-sub']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--embed-subs', u'http://www.youtube.com/watch?v=srffsSlR0og']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.26
[debug] Python version 2.7.6 - Linux-4.4.0-67-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 3.2.4-2, ffprobe 3.2.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] srffsSlR0og: Downloading webpage
[youtube] srffsSlR0og: Downloading video info webpage
[youtube] srffsSlR0og: Extracting video information
[youtube] srffsSlR0og: Looking for automatic captions
[youtube] srffsSlR0og: Downloading MPD manifest
[info] Writing video subtitles to: Joseph_Prince_2016_online_-_The_Root_Cause_Of_Your_Problem_Is_Condemnation__18__srffsSlR0og.en.vtt
[debug] Invoking downloader on u'https://r6---sn-4gxx-25gel.googlevideo.com/videoplayback?pcm2cms=yes&expire=1490591663&ipbits=0&ei=T0vYWK6vCtSYWKrWiLgP&upn=uS3suHl28tk&lmt=1483269182168830&clen=215841664&key=yt6&gir=yes&nh=EAE&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&ratebypass=yes&mt=1490569941&mime=video%2Fmp4&signature=83DCC85BEC19DC6DC446710F1FCF3189221DCAC3.C1EE351FB06DCDBC9FA36F71AACEDD97DD5E3A16&ms=au&source=youtube&mv=m&id=o-AM8bYGZTsD6XlXvNkOXEmcJBvZfR7jxfNzav6wt_fFNg&initcwndbps=941250&pl=16&dur=4828.589&itag=18&ip=78.243.8.240&mm=31&mn=sn-4gxx-25gel'
[download] Joseph_Prince_2016_online_-_The_Root_Cause_Of_Your_Problem_Is_Condemnation__18__srffsSlR0og.mp4 has already been downloaded
[download] 100% of 207.37MiB
[ffmpeg] Adding metadata to 'Joseph_Prince_2016_online_-_The_Root_Cause_Of_Your_Problem_Is_Condemnation__18__srffsSlR0og.mp4'
[debug] ffmpeg command line: ffmpeg -y -i file:Joseph_Prince_2016_online_-_The_Root_Cause_Of_Your_Problem_Is_Condemnation__18__srffsSlR0og.mp4 -c copy -metadata 'comment=Joseph Prince 2016 online - The Root Cause Of Your Problem Is Condemnation - November 11th 2016 (MUST LISTEN)' -metadata 'description=Joseph Prince 2016 online - The Root Cause Of Your Problem Is Condemnation - November 11th 2016 (MUST LISTEN)' -metadata 'artist=Noma Armstead' -metadata 'title=Joseph Prince 2016 online - The Root Cause Of Your Problem Is Condemnation' -metadata date=20161123 -metadata 'purl=https://www.youtube.com/watch?v=srffsSlR0og' file:Joseph_Prince_2016_online_-_The_Root_Cause_Of_Your_Problem_Is_Condemnation__18__srffsSlR0og.temp.mp4
[ffmpeg] Embedding subtitles in 'Joseph_Prince_2016_online_-_The_Root_Cause_Of_Your_Problem_Is_Condemnation__18__srffsSlR0og.mp4'
[debug] ffmpeg command line: ffmpeg -y -i file:Joseph_Prince_2016_online_-_The_Root_Cause_Of_Your_Problem_Is_Condemnation__18__srffsSlR0og.mp4 -i file:Joseph_Prince_2016_online_-_The_Root_Cause_Of_Your_Problem_Is_Condemnation__18__srffsSlR0og.en.vtt -map 0 -c copy -map -0:s -c:s mov_text -map 1:0 -metadata:s:s:0 language=eng file:Joseph_Prince_2016_online_-_The_Root_Cause_Of_Your_Problem_Is_Condemnation__18__srffsSlR0og.temp.mp4
Deleting original file Joseph_Prince_2016_online_-_The_Root_Cause_Of_Your_Problem_Is_Condemnation__18__srffsSlR0og.en.vtt (pass -k to keep)
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Joseph_Prince_2016_online_-_The_Root_Cause_Of_Your_Problem_Is_Condemnation__18__srffsSlR0og.mp4':
  Duration: 02:39:05.95, start: 0.000000, bitrate: 182 kb/s

```
Can you please have a look at this issue ?

**Comment by dstftw** [comment]
Probably a ffmpeg bug. There is nothing we can do.
