### ISSUE TITLE
Error 402 Payment required yt-dl.

### ISSUE THREAD

**Issue by brandonj159** [rg3/youtube-dl#12562]
Hello what happens is that I write the command to download a download and I get the error HTTP Error 402: Payment Required and wanted to know if I could help with this error
:~# youtube-dl --verbose -f 18 http://www.youtube.com/watch?v=vfndCiKYO40
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'18', u'http://www.youtube.com/watch?v=vfndCiKYO40']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.24
[debug] Python version 2.7.6 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] vfndCiKYO40: Downloading webpage
[youtube] vfndCiKYO40: Downloading video info webpage
ERROR: unable to download video info webpage: HTTP Error 402: Payment Required (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 497, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2094, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by Hrxn** [comment]
Seems to work in browser on my side, what happens when you try that?

**Comment by brandonj159** [comment]
When I try to download I get the error that I eat you before and do not let me download anything is the 1 time that happens

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required
