### ISSUE TITLE
Cant download video on pluralsight

### ISSUE THREAD

**Issue by ngohungphuc** [rg3/youtube-dl#12574]
I want to download into the folder .I run the following command

` youtube-dl -o "D:\Download\Programs" --username myemail --password mypassword --list-subs "https://app.pluralsight.com/library/courses/node-intro/table-of-contents"`

After the download complete message show I cant find any video downloaded.Is there something I have missed ? Thanks you for your help

**Comment by dstftw** [comment]
You are misusing output template. Read [FAQ](https://github.com/rg3/youtube-dl#output-template).
