### ISSUE TITLE
[mixcloud] Downloads keep hanging

### ISSUE THREAD

**Issue by Aeilko** [rg3/youtube-dl#12579]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl https://www.mixcloud.com/GebroedersScooter/gebroeders-scooter-totale-escalatie-3d/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.mixcloud.com/GebroedersScooter/gebroeders-scooter-totale-escalatie-3d/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.26
[debug] Python version 3.5.0 - Linux-4.4.38-v7+-armv7l-with-debian-8.0
[debug] exe versions: ffmpeg N-83436-g8efb7f5, ffprobe N-83436-g8efb7f5
[debug] Proxy map: {}
[mixcloud] GebroedersScooter-gebroeders-scooter-totale-escalatie-3d: Downloading webpage
[debug] Invoking downloader on 'https://stream4.mixcloud.com/c/m4a/64/b/c/0/8/65a9-6922-4298-8b22-2dc7bda14a9f.m4a'
[download] Destination: Gebroeders Scooter - Totale Escalatie 3D-GebroedersScooter-gebroeders-scooter-totale-escalatie-3d.m4a
[download]  13.2% of 30.36MiB at 10.26MiB/s ETA 00:02
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Yesterday i did a reïnstall of a music bot for Discord (https://github.com/Just-Some-Bots/MusicBot), which included an update of  youtube-dl. After the reïnstall i noticed the bot could no longer play music from mixcloud. After some searching and testing it appeared to only happen with mixcloud songs (as far as i tested) and to be caused by the downloader, since using the youtube-dl resulted in the same problem: The download would start but never finish.
I tried reïnstalling youtube-dl, pip and python, non had any effect on the outcome, the bot starts the download, but never updates the download progress and the file is not being downloaded. It just hangs on the same percentage, speed and ETA.
A new file is created, in case of the example it's called "Gebroeders Scooter - Totale Escalatie 3D-GebroedersScooter-gebroeders-scooter-totale-escalatie-3d.m4a.part", but it is never completed.

I found a similar issue (i think) from the 18th of january (https://github.com/rg3/youtube-dl/issues/11763), but this was rejected as invalid.

**Comment by dstftw** [comment]
It does not hang. Mixcloud shapes speed after first couple of megabytes.
