### ISSUE TITLE
Improved playlist download progress information

### ISSUE THREAD

**Issue by OaktreeTM** [rg3/youtube-dl#12571]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When downloading a playlist, improved information about progress would be helpful, e.g.:
* "Current: "[====>          ] x.x of x.x MiB" (video n / [playlistLength])
* "Total:      [====>           ] y.y of y.y GiB" 
* Estimated time remaining: m minutes (current), t minutes (whole playlist)

This would assist if calling youtube-dl from other programs, e.g. pausing when reaching a certain download quota, or if resuming at a certain video after having stopped for any reason (need to know which video was the last completed, before using --playlist-start).

P.S.: Thanks to all developers. You're amazing. If I knew your languages, I'd help, but I'm very appreciative of your excellent work. Thank you!

**Comment by dstftw** [comment]
No filesize and duration metadata is known beforehand thus not possible to calculate overall progress.

**Comment by OaktreeTM** [comment]
Thank you for the info and the lightening fast response.
