### ISSUE TITLE
YouTube video only has only one format

### ISSUE THREAD

**Issue by Khang-NT** [rg3/youtube-dl#12572]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
The result of command below contain only one format (mp4), but usually It should contain: dash video, dash audio and full video, so we have around 10 formats per video. 

https://www.youtube.com/watch?v=ztcGVcldOEI
```
$ youtube-dl -v -j ztcGVcldOEI
```

I don't know if this is `youtube-dl` problem or just because the video hasn't encoded to DASH yet.

**Comment by dstftw** [comment]
Only one format is available for this video.
