### ISSUE TITLE
Playlist download gets stuck

### ISSUE THREAD

**Issue by bisherbas** [rg3/youtube-dl#12570]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.26
[debug] Python version 2.7.6 - Linux-3.4.0+-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-81995-gd790e48, ffprobe N-81995-gd790e48
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

I am trying to download a playlist using the following command

`youtube-dl -ixv --audio-format mp3 --audio-quality 8 -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=lBdfnJamCP8&list=PLWAJ5JHERaUjTXlyildAGjUvLv7jb33IN`

First video is downloaded and converted to MP3 successfully but the process will not continue. **Stuck at**

`Deleting original file Souad Massi - Le Bien et Mal.webm (pass -k to keep)`

If I try the download archive argument as seen below

`youtube-dl --download-archive downloaded.txt -ixv --audio-format mp3 --audio-quality 8 -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=lBdfnJamCP8&list=PLWAJ5JHERaUjTXlyildAGjUvLv7jb33IN`

**Process gets stuck at**

`[download] Souad Massi - Le Bien et Mal has already been recorded in archive`

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by bisherbas** [comment]
At least show the decency to tell me what I have missed. I thought I did carefully read the template and provided everything asked.

**Comment by bisherbas** [comment]
@dstftw What is missing exactly? I cannot figure it out. Please indicate the missing part so I can add it.

**Comment by gkoelln** [comment]
Run this:

`youtube-dl -ixv --audio-format mp3 --audio-quality 8 -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=lBdfnJamCP8&list=PLWAJ5JHERaUjTXlyildAGjUvLv7jb33IN -v
`

And provide the output.

**Comment by roberdaniel** [comment]
Same problem here.
It stucks in "Deleting original file"
ti2@olivetti:~/Música/Inglés$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.11
[debug] Python version 2.7.13 - Linux-4.9.0-2-amd64-x86_64-with-Sparky-4-Tyche
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

Please let me know what you need i do and I'll try it and post the results.
Regards

**Comment by roberdaniel** [comment]
I have more info about it.
It is not stuck, process disappears from memory!!! i.e. the process dies.
By the way, intermediate file is correctly deleted from disk ;)

**Comment by nikhil-bhandari** [comment]
More Info:

Playlist download works if URL is a playlist page 

eg: 

```
$ ./youtube-dl https://www.youtube.com/playlist?list=SOME_PLAYLIST_ID
```
But this fails

```
$ ./youtube-dl https://www.youtube.com/watch?v=SOME_VIDEO_ID&list=SOME_PLAYLIST_ID
```

I'm not sure if this is intended behaviour but I remember both used to work.

Thanks for the awesome tool :+1:

**Comment by dstftw** [comment]
@nikhil-bhandari learn how to [use command line](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).
