### ISSUE TITLE
[Windows] Portable youtube-dl with separate python executable

### ISSUE THREAD

**Issue by romaincointepas** [rg3/youtube-dl#12588]
I am trying to embed `youtube-dl` in a Windows application with youtube-dl-only/frequent auto-update mechanism, so youtube-dl.exe has to be both portable (Windows 7+ compatibility) and easily auto-updatable (faster update frequency than the application itself).

Embedding and updating the official `youtube-dl.exe` (and putting `msvcr100.dll` in the same folder) works like a charm. However, because of the fact that python is included in the exe, the auto-update redownload 7MB each time there is a youtube-dl release.

I was wondering if someone could give some advice to *separate* python and youtube-dl (so only youtube-dl is updated every few days). Again, python has to be entirely shipped with the app and work on Windows 7+, 32 and 64-bit.

I couldn't find portable python 2.7 exe (it only comes as a huge installer), and I'm not sure [WinPython](https://winpython.github.io/) is the right way to go (and it's still ~25MB).

Any tips welcome, thanks!

**Comment by dstftw** [comment]
Offtopic.
