### ISSUE TITLE
[adobepass] Add MSOs

### ISSUE THREAD

**Issue by gkoelln** [rg3/youtube-dl#12581]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

I have a question before I submit any pull requests. I have some proposed changes for adobepass, but I wondered if it was better to add one MSO at a time and wait for testing, than to add several MSOs  at once. In other words, should I submit separate pull requests as they're approved, even though it's one file being updated? I think I've found a way to make all MSOs work as long as they are in the dict, but have no way of testing more than one.

**Comment by dstftw** [comment]
That depends. The general rule is to have a separate PR for a separate functionality or a feature.
