### ISSUE TITLE
Playlist download gets stuck

### ISSUE THREAD

**Issue by bisherbas** [rg3/youtube-dl#12580]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.26
[debug] Python version 2.7.6 - Linux-3.4.0+-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-81995-gd790e48, ffprobe N-81995-gd790e48
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Playlist: https://www.youtube.com/watch?v=lBdfnJamCP8&list=PLWAJ5JHERaUjTXlyildAGjUvLv7jb33IN

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I am trying to download a playlist using the following command

youtube-dl -ixv --audio-format mp3 --audio-quality 8 -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=lBdfnJamCP8&list=PLWAJ5JHERaUjTXlyildAGjUvLv7jb33IN

First video is downloaded and converted to MP3 successfully but the process will not continue. Stuck at

Deleting original file Souad Massi - Le Bien et Mal.webm (pass -k to keep)

If I try the download archive argument as seen below

youtube-dl --download-archive downloaded.txt -ixv --audio-format mp3 --audio-quality 8 -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=lBdfnJamCP8&list=PLWAJ5JHERaUjTXlyildAGjUvLv7jb33IN

Process gets stuck at

[download] Souad Massi - Le Bien et Mal has already been recorded in archive

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by bisherbas** [comment]
It's in there. You should not have closed this issue. Check again.

**Comment by dstftw** [comment]
It's not. Maybe start reading my posts already?
> youtube-dl -v <your command line>

>\<your command line>

>i.e. **add** `-v` flag to **your command line**

**Comment by bisherbas** [comment]
Are you a joke? It's  there. Why are you wasting my time?

```
$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.26
[debug] Python version 2.7.6 - Linux-3.4.0+-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-81995-gd790e48, ffprobe N-81995-gd790e48
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
```

Above code is included in my original post.

**Comment by dstftw** [comment]
Post the **FULL OUTPUT** of `youtube-dl -ixv --audio-format mp3 --audio-quality 8 -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=lBdfnJamCP8&list=PLWAJ5JHERaUjTXlyildAGjUvLv7jb33IN`, damn it.

**Comment by bisherbas** [comment]
Then you should design a better template.
