### ISSUE TITLE
YouTube auto-generated subtitles are not detected

### ISSUE THREAD

**Issue by tylerknott** [rg3/youtube-dl#12591]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ ./youtube-dl -v --all-subs --simulate https://www.youtube.com/watch?v=ICfD1lACsm4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--all-subs', u'--simulate', u'https://www.youtube.com/watch?v=ICfD1lACsm4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.26
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.7
[debug] exe versions: ffmpeg 2.8.10, ffprobe 2.8.10, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ICfD1lACsm4: Downloading webpage
[youtube] ICfD1lACsm4: Downloading video info webpage
[youtube] ICfD1lACsm4: Extracting video information
WARNING: video doesn't have subtitles
[youtube] ICfD1lACsm4: Downloading MPD manifest
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

Youtube-dl is not detecting auto-generated subtitles on videos which have them (such as https://www.youtube.com/watch?v=ICfD1lACsm4). If a video has both auto-generated and manually-created subtitles (such as https://www.youtube.com/watch?v=AUvICKyXnqU) it will detect the manually-created subtitles correctly but not the auto-generated ones.

**Comment by dstftw** [comment]
```
PS C:\dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py ICfD1lACsm4 --list-sub
[youtube] ICfD1lACsm4: Downloading webpage
[youtube] ICfD1lACsm4: Downloading video info webpage
[youtube] ICfD1lACsm4: Extracting video information
WARNING: video doesn't have subtitles
[youtube] ICfD1lACsm4: Looking for automatic captions
[youtube] ICfD1lACsm4: Downloading MPD manifest
Available automatic captions for ICfD1lACsm4:
Language formats
af       vtt, ttml
sq       vtt, ttml
am       vtt, ttml
ar       vtt, ttml
hy       vtt, ttml
az       vtt, ttml
bn       vtt, ttml
eu       vtt, ttml
be       vtt, ttml
bs       vtt, ttml
bg       vtt, ttml
my       vtt, ttml
ca       vtt, ttml
ceb      vtt, ttml
zh-Hans  vtt, ttml
zh-Hant  vtt, ttml
co       vtt, ttml
hr       vtt, ttml
cs       vtt, ttml
da       vtt, ttml
nl       vtt, ttml
en       vtt, ttml
eo       vtt, ttml
et       vtt, ttml
fil      vtt, ttml
fi       vtt, ttml
fr       vtt, ttml
gl       vtt, ttml
ka       vtt, ttml
de       vtt, ttml
el       vtt, ttml
gu       vtt, ttml
ht       vtt, ttml
ha       vtt, ttml
haw      vtt, ttml
iw       vtt, ttml
hi       vtt, ttml
hmn      vtt, ttml
hu       vtt, ttml
is       vtt, ttml
ig       vtt, ttml
id       vtt, ttml
ga       vtt, ttml
it       vtt, ttml
ja       vtt, ttml
jv       vtt, ttml
kn       vtt, ttml
kk       vtt, ttml
km       vtt, ttml
ko       vtt, ttml
ku       vtt, ttml
ky       vtt, ttml
lo       vtt, ttml
la       vtt, ttml
lv       vtt, ttml
lt       vtt, ttml
lb       vtt, ttml
mk       vtt, ttml
mg       vtt, ttml
ms       vtt, ttml
ml       vtt, ttml
mt       vtt, ttml
mi       vtt, ttml
mr       vtt, ttml
mn       vtt, ttml
ne       vtt, ttml
no       vtt, ttml
ny       vtt, ttml
ps       vtt, ttml
fa       vtt, ttml
pl       vtt, ttml
pt       vtt, ttml
pa       vtt, ttml
ro       vtt, ttml
ru       vtt, ttml
sm       vtt, ttml
gd       vtt, ttml
sr       vtt, ttml
sn       vtt, ttml
sd       vtt, ttml
si       vtt, ttml
sk       vtt, ttml
sl       vtt, ttml
so       vtt, ttml
st       vtt, ttml
es       vtt, ttml
su       vtt, ttml
sw       vtt, ttml
sv       vtt, ttml
tg       vtt, ttml
ta       vtt, ttml
te       vtt, ttml
th       vtt, ttml
tr       vtt, ttml
uk       vtt, ttml
ur       vtt, ttml
uz       vtt, ttml
vi       vtt, ttml
cy       vtt, ttml
fy       vtt, ttml
xh       vtt, ttml
yi       vtt, ttml
yo       vtt, ttml
zu       vtt, ttml
ICfD1lACsm4 has no subtitles
```

**Comment by tylerknott** [comment]
Yeah, sorry. I just realized after I submitted it that there was a separate option to download the automatic subtitles.
