### ISSUE TITLE
Unable to Download Youtube WatchLater Playlist

### ISSUE THREAD

**Issue by GvnCampbell** [rg3/youtube-dl#12590]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**
- [x] At least skimmed through [README][FAQ][BUGS]
- [x] [Searched] the bugtracker for similar issues including closed ones

- [x] Bug report (encountered problems with youtube-dl)

---

I am currently unable to download the watch later playlist.  It use to work and the last time was probably around January 10th.  As you can see it now reports that the playlist no longer exists.  I have a feeling youtube change something to break this functionality.

If I try other playlists it works just not with the WL playlist.

---
youtube-dl is up-to-date (2017.03.26)
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '--download-archive', 'archive.txt', 'https://www.youtube.com/playlist?list=WL', '--cookies', 'cookies.txt', '-o', '//HomeServer/tv/[Gavin]/Youtube Watch Later List/%(uploader)s - %(title)s_%(upload_date)s.%(ext)s', '--write-thumbnail', '--mark-watched']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.03.26
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Logging in
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\extractor\common.py", line 428, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\extractor\youtube.py", line 2520, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\extractor\youtube.py", line 2062, in _extract_playlist
youtube_dl.utils.ExtractorError: This playlist does not exist.
---

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by GvnCampbell** [comment]
Hopefully this works.
Here is the output from the command.

Maybe there is a video in my list that is causing it to choke.  Maybe you will see that in the output.

[output.txt](https://github.com/rg3/youtube-dl/files/876493/output.txt)

**Comment by dstftw** [comment]
![image](https://cloud.githubusercontent.com/assets/1908898/24418478/52972736-1416-11e7-907d-05202b5d1f79.png)

**Comment by GvnCampbell** [comment]
Thank you.  Makes sense.  I'll look into that.
