### ISSUE TITLE
what is the protocol used while download a content?

### ISSUE THREAD

**Issue by rils** [rg3/youtube-dl#12596]
Hi,

Youtube streaming protocol is special TCP ( or UDP?) or youtubes own protocol. Online materials still confuse me in this.
My real question is what is the protocol used by youtube.dl for downloading a youtube content ?

Thanks
Rilwan

**Comment by dstftw** [comment]
HTTP(S) over TCP/IP.

**Comment by rils** [comment]
Thank you. Offtopic, but you might know the answer. what is the protocol
used in streaming youtube a video from youtube app/browser

**Comment by dstftw** [comment]
Don't known what is "youtube app/browser".

**Comment by rils** [comment]
i mean what is the protocol used by youtube mobile apps(android/ios) or
stream youtube from a web browser.

**Comment by dstftw** [comment]
They all use one of the higher level protocols over HTTP(S).

**Comment by rils** [comment]
Thank you. So basically TCP only. Not at all UDP. Correct. Thank you~

**Comment by Hrxn** [comment]
Maybe SPDY / QUIC

**Comment by Hrxn** [comment]
https://en.wikipedia.org/wiki/QUIC#Adoption
