### ISSUE TITLE
How to Run youtube-dl along with my site on a post

### ISSUE THREAD

**Issue by hdbabu** [rg3/youtube-dl#12595]
Hello Everyone please help me...

This is my site - https://hdbabu.com/ . And I want to do that like - I have write a post containing a download link of movie i.e. already on youtube and I wants to provide them a direct download link of that movie i.e. already on youtube.. but when i generate the direct download link using youtube-dl in windows.. its expired after few hours...

So how can i add... there are many sites doing the same...

Please help me... if any one can... I have tried lots of solutions but didn't get solutions for it... please please please please help

**Comment by dstftw** [comment]
Offtopic.
