### ISSUE TITLE
I am getting this error.Please help

### ISSUE THREAD

**Issue by Parvez1995** [rg3/youtube-dl#12597]
ERROR: An extractor error has occurred. (caused by KeyError('_Request__r_host',)); please report this issue on https://y
t-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to c
all youtube-dl with the --verbose flag and include its complete output.

my youtube-dl is upto date with version 2017.03.26

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
