### ISSUE TITLE
Autonumbering after the completion of download

### ISSUE THREAD

**Issue by rohanvakharia** [rg3/youtube-dl#12607]
I have downloaded a playlist from youtube. I forgot to autonumber the list. Is it possible to autonumber it after the completion of download?

I have archive.txt file saved for the future download.

home@desktop:/home# youtube-dl --version
2017.03.26

**Comment by dstftw** [comment]
Not possible.

**Comment by rohanvakharia** [comment]
Thanks @dstftw 
Now I have to write shell script to do this.
