### ISSUE TITLE
I am getting this issue while downloading course from udemy.(i enrolled for the course)

### ISSUE THREAD

**Issue by Parvez1995** [rg3/youtube-dl#12602]
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

PS C:\Users\parvez> youtube-dl -u username -p password https://www.udemy.com/complete-android-n-de
veloper-course/learn/v4/overview
[udemy:course] Downloading login popup
[udemy:course] Logging in as username
[udemy:course] complete-android-n-developer-course: Downloading webpage
[udemy:course] 951618: Downloading course curriculum
[download] Downloading playlist: The Complete Android N Developer Course
[udemy:course] playlist The Complete Android N Developer Course: Collected 166 video ids (downloading 166 of them)
[download] Downloading video 1 of 166
[udemy] Downloading login popup
[udemy] 5689934: Downloading webpage
[udemy] 5689934: Downloading lecture JSON
[udemy] 6931870: Downloading m3u8 information
ERROR: An extractor error has occurred. (caused by KeyError('_Request__r_host',)); please report this issue on https://y
t-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to c
all youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Post the output of `youtube-dl -v -u username -p password https://www.udemy.com/complete-android-n-developer-course/learn/v4/overview`.
