### ISSUE TITLE
trailing / in shell script

### ISSUE THREAD

**Issue by Twwwwizz** [rg3/youtube-dl#12611]
If I run the command 

youtube-dl https://vimeo.com/192440102

from Terminal in Mac OS, this downloads fine.

If I place it in a .sh shell script and run the script I get:-
youtube-dl: Downloading page 1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); 

I discovered the fix, which is to add a "/" to the URL thus:-

youtube-dl https://vimeo.com/192440102/

youtube-dl --version
2017.03.26
MacOS Sierra
10.12.3 (16D32)

**Comment by dstftw** [comment]
Most likely your script is malformed.
