### ISSUE TITLE
Potential risk to the project by using "youtube" in the name

### ISSUE THREAD

**Issue by OaktreeTM** [rg3/youtube-dl#12619]

**Comment by OaktreeTM** [comment]
Closed

**Comment by dstftw** [comment]
There is no legal entity behind youtube-dl thus there is nobody to make legal mess for. All development is voluntary and I doubt there are any risks apart from being shut down on GitHub via request according to GitHub's DMCA Takedown Policy.
Changing name will double the costs for domains and probably break some stuff and all this ado just for nothing.
