### ISSUE TITLE
increase Internal sleep time  viewclip calls 

### ISSUE THREAD

**Issue by maheshkhiste** [rg3/youtube-dl#12613]
I am trying for Pluralsight.
I have checked documentation and no parameter to increase Internal sleep time  viewclip calls (which is diff than sleep interval which is sleep in between downloads)
I think its random between 3 to 5 seconds. I am not aware of  python.
I saw some posts mentioning changes into pluralsight.py but i don't know what to do after or how to generate windows executable after changing it.
Any help is appreciated.

**Comment by dstftw** [comment]
There is no way to increase this time. Sleep interval between downloads is enough since viewclip is called only once for each video.
