### ISSUE TITLE
Resuming m3u8 stream

### ISSUE THREAD

**Issue by TheDcoder** [rg3/youtube-dl#12614]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*
---

### Description of your *issue*, suggested solution and other information

Hello, I am trying to resume a m3u8 stream (not a live stream) but I cannot! `--continue` isn't helping either. `youtube-dl` used `ffmpeg` to download the stream so I decided try with the native hls downloader this time with `--hls-prefer-native` but it is still not resuming the download, I have the `.part` file backed up. Every time I resume, the download starts from the start.

Thanks for the help in advance :)

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by TheDcoder** [comment]
Hi @dstftw, I have read the new issue several times but I don't see any lack of information in my description... Maybe I am blind.

**Comment by dstftw** [comment]
>### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
>
>Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
>```
>$ youtube-dl -v <your command line>
>[debug] System config: []
>[debug] User config: []
>[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
>[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
>[debug] youtube-dl version 2017.03.26
>[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
>[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
>[debug] Proxy map: {}
>...
><end of log>
>```

**Comment by AndrewHuntC** [comment]
Surprised to see something which I was interested about, a while back I was wondering how to resume m3u8 downloads. I can provide the command output:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', '13.mp4', 'https://vootvideo.akamaized.n
et/enc/fhls/p/1982551/sp/198255100/serveFlavor/entryId/0_00yjrrgm/v/2/pv/1/flavo
rId/0_7plps0ki/name/a.mp4/index.m3u8']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.26
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[generic] index: Requesting header
[generic] index: Downloading m3u8 information
[debug] Invoking downloader on 'https://vootvideo.akamaized.net/enc/fhls/p/19825
51/sp/198255100/serveFlavor/entryId/0_00yjrrgm/v/2/pv/1/flavorId/0_7plps0ki/name
/a.mp4/index.m3u8'
[download] Destination: 13.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0
 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
' -i https://vootvideo.akamaized.net/enc/fhls/p/1982551/sp/198255100/serveFlavor
/entryId/0_00yjrrgm/v/2/pv/1/flavorId/0_7plps0ki/name/a.mp4/index.m3u8 -c copy -
f mp4 file:13.mp4.part
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-d3d11va --enable-dxva2
--enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontcon
fig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libb
luray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --e
nable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-l
ibopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libope
njpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --en
able-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enabl
e-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable
-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --e
nable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, hls,applehttp, from 'https://vootvideo.akamaized.net/enc/fhls/p/198255
1/sp/198255100/serveFlavor/entryId/0_00yjrrgm/v/2/pv/1/flavorId/0_7plps0ki/name/
a.mp4/index.m3u8':
  Duration: 00:42:27.58, start: 0.101000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 640x360 [
SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, flt
p
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:13.mp4.part':
  Metadata:
    encoder         : Lavf57.56.101
    Stream #0:0: Video: h264 (Main) ([33][0][0][0] / 0x0021), yuv420p, 640x360 [
SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   51 fps= 45 q=-1.0 size=      78kB time=00:00:02.00 bitrate= 319.3kbits/
frame=  101 fps= 48 q=-1.0 size=     155kB time=00:00:04.00 bitrate= 316.5kbits/
frame=  148 fps= 56 q=-1.0 size=     304kB time=00:00:05.88 bitrate= 423.2kbits/
frame=  151 fps= 44 q=-1.0 size=     387kB time=00:00:06.00 bitrate= 528.9kbits/
frame=  187 fps= 46 q=-1.0 size=     553kB time=00:00:07.44 bitrate= 609.0kbits/
frame=  230 fps= 51 q=-1.0 size=     730kB time=00:00:09.16 bitrate= 652.6kbits/
frame=  251 fps= 46 q=-1.0 size=     857kB time=00:00:10.00 bitrate= 701.9kbits/
frame=  268 fps= 43 q=-1.0 Lsize=     982kB time=00:00:10.68 bitrate= 753.2kbits
/s speed= 1.7x
video:891kB audio:88kB subtitle:0kB other streams:0kB global headers:0kB muxing
overhead: 0.305998%
Exiting normally, received signal 2.

ERROR: Interrupted by user

```
The half downloaded part file is already placed as 13.mp4. The video download from start! Please help! Much appreciated!

**Comment by TheDcoder** [comment]
@dstftw I thought that command output was not necessary in this case since this is a question... looks like it's becoming an issue 😕. I could not provide the commandline output because I had deleted the `.part` file and re-downloaded the video. It is big and I cannot afford to download it again because of my limited internet data usage imposed by my ISP. Thanks to @AndrewHuntC for helping me 😄

**Comment by dstftw** [comment]
ffmpeg does not support resuming, `--hls-prefer-native` does. If you're claiming it's not then provide verbose log proving that.
