### ISSUE TITLE
BUG OR FEATURE? youtube-dl doesn't react on "q" or/and "?" buttons while working

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#12616]
Hello dearest coders! I've was little bit interested in stream downloading by YDL, but when I've tried it, I've seen that YDL offers "q" to quit recoring, and "?" to see help while recording is proceeding.
Nice one, but I don't see no answer on my keys press attempts. Can you tell me, please, what is this, and how to fix it ?

Here is the log:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'hls-800', 'http://www.vesti.ru/onair/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.03.26
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Vesti] onair/: Downloading page
[RUTV] 21: Downloading JSON
[RUTV] 21: Downloading m3u8 information
[debug] Invoking downloader on 'https://livehlsvgtrk.cdnvideo.ru/live/smil:r24.smil/chunklist_b800000.m3u8'
[download] Destination: Россия 24. Прямой эфир 2017-04-01 16_11-21.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept: text/html,application/x
html+xml,application/xml;q=0.9,*/*;q=0.8
Cookie: e=1491080900; md5=eeCyTNREZomnCWD7gLspfg
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0
 (Chrome)
Accept-Language: en-us,en;q=0.5
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
' -i https://livehlsvgtrk.cdnvideo.ru/live/smil:r24.smil/chunklist_b800000.m3u8
-c copy -f mp4 'file:Россия 24. Прямой эфир 2017-04-01 16_11-21.mp4.part'
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-d3d11va --enable-dxva2
--enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontcon
fig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libb
luray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --e
nable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-l
ibopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libope
njpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --en
able-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enabl
e-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable
-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --e
nable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, hls,applehttp, from 'https://livehlsvgtrk.cdnvideo.ru/live/smil:r24.sm
il/chunklist_b800000.m3u8':
  Duration: N/A, start: 54100.164856, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p(tv), 1024x576 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:╨а╨╛╤Б╤Б╨╕╤П 24. ╨Я╤А╤П╨╝╨╛╨╣ ╤Н╤Д╨╕╤А 2017-04-01 16_11
-21.mp4.part':
  Metadata:
    encoder         : Lavf57.56.101
    Stream #0:0: Video: h264 (Constrained Baseline) ([33][0][0][0] / 0x0021), yu
v420p(tv), 1024x576 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (HE-AAC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (copy)
**Press [q] to stop, [?] for help**
frame=  749 fps= 32 q=-1.0 size=    3153kB time=00:00:29.95 bitrate= 862.3kbits/
frame= 1049 fps= 30 q=-1.0 size=    4418kB time=00:00:41.94 bitrate= 862.9kbits/
frame= 1274 fps= 29 q=-1.0 size=    5381kB time=00:00:50.99 bitrate= 864.4kbits/
s speed=1.15x

**Comment by dstftw** [comment]
youtube-dl does not offer q to quit, it's the output of ffmpeg. To stop you should use Ctrl+C.

**Comment by nmr50** [comment]
I see.. Thanks !!!:)
