### ISSUE TITLE
Add incremental number at the end of file name if file with same name exists

### ISSUE THREAD

**Issue by Razor-13** [rg3/youtube-dl#12626]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.02**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Question

---

Is it possible to do this? My current config is
`youtube-dl --fixup warn -f best -o "%(title)s %(upload_date)s.%(ext)s" $*`

using "autonumber" doesn't make it for me because it adds a number on all files, not only on cases where the file ends with the same filename.

**Comment by dstftw** [comment]
Not possible.

**Comment by Razor-13** [comment]
Should I make a new issue requesting this as a feature? Or can I edit and re-open this?

**Comment by Razor-13** [comment]
Also autonumber doesn't seem to work as intended, after downloading the first video, on the second download the number stays at 00001, it doesn't increase

**Comment by gkoelln** [comment]
Perhaps you didn't realize that autonumber is for playlists, not numbering if files already exist.
