### ISSUE TITLE
[packtpub] Add support for authentication

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#12622]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.02**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.04.02
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

hi i am getting this error about video is locked but i can watch online in browser every lecture

PS C:\Users\HDNLUF037\downloads> youtube-dl --verbose -o '~/downloads/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)
s' https://www.packtpub.com/mapt/video/application-development/9781786462978 --sleep-interval 90 --username 123@g
mail.com --password 123
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-o', u'~/downloads/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', u'h
ttps://www.packtpub.com/mapt/video/application-development/9781786462978', u'--sleep-interval', u'90', u'--username', u'
PRIVATE', u'--password', u'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.02
[debug] Python version 2.7.12 - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[PacktPubCourse] 9781786462978: Downloading JSON metadata
[download] Downloading playlist: Getting Started With Julia [Video]
[PacktPubCourse] playlist Getting Started With Julia [Video]: Collected 46 video ids (downloading 46 of them)
[download] Downloading video 1 of 46
[PacktPub] 19840: Downloading JSON video
[PacktPub] 19840: Downloading JSON metadata
[debug] Invoking downloader on u'https://d1ft11egbn8l.cloudfront.net/Mastering Julia programming/Package/videos/video1_1
.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2QxZnQxMWVnYm44bC5jbG91ZGZyb250Lm5ldFwvTWFzdGVyaW5nJTIwSnVs
aWElMjBwcm9ncmFtbWluZ1wvUGFja2FnZVwvdmlkZW9zXC92aWRlbzFfMS5tcDQiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRp
bWUiOjE0OTExNTUwOTJ9fX1dfQ__&Signature=IUu-vCiG9BNxj8c-0Ew4VlFqGKtvc4FHMc~NmU2ytOg9OvUUNB1whSeOmq--3i2EvwKm~SpN2WpROEjKh
u4GxR~j908Kb8zLcSAO~2CMXPpcmaoV9SWJ-VoaHOHyjF2didBSNIHG7gTO9L9BoYtjCN4bu6iJ1dJYlE8K5nSqmAY_&Key-Pair-Id=APKAJTJLPJQL5PVZ
47FA'
[download] Sleeping 90 seconds...
[download] Destination: C:\Users\HDNLUF037\downloads\Getting Started With Julia [Video]\01 - The Course Overview.mp4
[download] 100% of 39.82MiB in 00:04
[download] Downloading video 2 of 46
[PacktPub] 19841: Downloading JSON video
ERROR: This video is locked
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 428, in extract
    ie_result = self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\packtpub.py", line 61, in _real_extract
    raise ExtractorError('This video is locked', expected=True)
ExtractorError: This video is locked

PS C:\Users\HDNLUF037\downloads>

**Comment by dstftw** [comment]
Authentication is not supported. You must provide account credentials.

**Comment by jaan143** [comment]
where can i send you account detail ?

**Comment by jaan143** [comment]
@dstftw  please check you email i sent you details

**Comment by jaan143** [comment]
@dstftw will you please add login details ?
plz

**Comment by jaan143** [comment]
@remitamine can you please add login details in python file ?
i already send my account details to @dstftw but he didn't response me yet
if you can add then give me your email and i will send you login details

thanks

**Comment by remitamine** [comment]
> give me your email and i will send you login details

you can find my email in @remitamine.

**Comment by wkk5** [comment]
@remitamine would it be possible to also add cookies.txt support?  Thx!

**Comment by jaan143** [comment]
@remitamine  please check your email i send you login details
thanks

**Comment by jaan143** [comment]
@remitamine  bro sins yesterday its not working again getting login error but account is working in browser

[debug] Command-line args: ['--verbose', '-o', '~/downloads/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ex
t)s', 'https://www.packtpub.com/mapt/video/web-development/9781788290616', '--username', 'PRIVATE', '--password', 'PRIVA
TE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.03
[debug] Python version 3.5.2 - Windows-10-10.0.14393-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[PacktPubCourse] 9781788290616: Downloading JSON metadata
[download] Downloading playlist: Learn to Write Functional Javascript [Video]
[PacktPubCourse] playlist Learn to Write Functional Javascript [Video]: Collected 17 video ids (downloading 17 of them)
[download] Downloading video 1 of 17
[PacktPub] None: Downloading webpage
[PacktPub] Logging in as 123@gmail.com
[PacktPub] Downloading Authorization Token
[PacktPub] 24237: Downloading JSON video
[PacktPub] 24237: Downloading JSON metadata
[debug] Invoking downloader on 'https://d1ft11egbn8l.cloudfront.net/Learn to Write Functional Javascript/Package/videos/
video1_1.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2QxZnQxMWVnYm44bC5jbG91ZGZyb250Lm5ldFwvTGVhcm4lMjB0
byUyMFdyaXRlJTIwRnVuY3Rpb25hbCUyMEphdmFzY3JpcHRcL1BhY2thZ2VcL3ZpZGVvc1wvdmlkZW8xXzEubXA0IiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNz
VGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDk2MjU1Njk0fX19XX0_&Signature=JQyQb673cilI8-nAJnGNhSVONSKeVtECYnFKVOfDTEWdWl5KdKBgvIEaR
sx1wCaDHJXekrZiOqS4x5~P5PPqCv4PNe~zauDl13Y6gmXzdsTZUUXp8RZW6TSV~TzPHTO1url93guzLiRrGIFEe9z35TI3rqMFPnTjyjCAF-58ziM_&Key-
Pair-Id=APKAJTJLPJQL5PVZ47FA'
[download] Destination: C:\Users\vicky\downloads\Learn to Write Functional Javascript [Video]\1 - Understanding Foundati
ons of Functional Programming\The Course Overview.mp4
[download] 100% of 31.12MiB in 02:18
[download] Downloading video 2 of 17
[PacktPub] 22286: Downloading JSON video
ERROR: This video is locked. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 761, in e
xtract_info
    ie_result = ie.extract(url)
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\extractor\common.py", line 42
9, in extract
    ie_result = self._real_extract(url)
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\extractor\packtpub.py", line
94, in _real_extract
    self.raise_login_required('This video is locked')
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\extractor\common.py", line 70
9, in raise_login_required
    expected=True)
youtube_dl.utils.ExtractorError: This video is locked. Use --username and --password or --netrc to provide account crede
ntials.

PS C:\Users\vicky\downloads>
