### ISSUE TITLE
v.douyu.com

### ISSUE THREAD

**Issue by brlala** [rg3/youtube-dl#12620]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)
- [x] Question

---

**Site Support** request for v.douyu.com
- Single video: https://v.douyu.com/show/rjNBdvnVXNzvE2yw
I am told that the video is separated into 10sec clip which makes the download process very hard, therefore in order to download from this website, one has to download a playlist and then merge the files together. Does the website behaves like this and is it possible to add support to this site in terms of coding?
---

**Question**
I have Internet Download Manager, however I noticed a strange behaviour is that, I am able to obtain and download the full video as a single file if I opened the link with Internet Explorer. While if the links are opened in other browser like Chrome, Firefox, the links obtained will return a "Some sites do not allow requesting the same file twice error" which means totally not able to download. Why does it work on IE and not Chrome?
```
IE link: http://vodhls1.douyucdn.cn/live/normal_live-67373rv02pVBufFF--20170401224045/playlist.m3u8?k=1bc5254160b07e5f876c113f35bae466&t=58e07fed&u=0&ct=web&vid=454636&d=0A74A2B44A17507659E82C20863589DE

Chrome link: http://vodhls1.douyucdn.cn/live/normal_live-67373rv02pVBufFF--20170401224045/playlist.m3u8?k=098ab4c27bf9e0965e3d0718023662d8&t=58e08289&u=40163949&ct=web&vid=454636&d=CADA9FB4EFD7F7A5C5A876BA9FFD325F
```

**Comment by dstftw** [comment]
This is youtube-dl issue tracker. Questions regarding IDM should be addressed to IDM developers.
