### ISSUE TITLE
download playlist from a specific video

### ISSUE THREAD

**Issue by Joseph65** [rg3/youtube-dl#12624]
i tried to download a playlist but when i reach to the 19th video it exits because it says its not available
so what i wanted to do is resume to the number 20th video of the playlist rather than downloading them again, here is the playlist i  tried to download [https://www.youtube.com/playlist?list=PLavtzqgE9oN7kCi7oSO57Rz1QVVG-qQF4](url)

**Comment by dstftw** [comment]
Use `-i`.
