### ISSUE TITLE
Cannot get metadata for Vimeo videos that disallow embedding

### ISSUE THREAD

**Issue by amhed** [rg3/youtube-dl#12636]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Cannot get metadata for Vimeo videos that disallow embedding

A non-embeddable video like https://vimeo.com/202854234 
returns an invalid URL using `--get-url`: https://skyfire.vimeocdn.com/1491277824-0xb0756a8ca3d9f1ccabbb01dd01a99228580507d3/202854234/sep/video/716807024,716807023/../

The weird thing about this, is that if I chose to only download the video without previewing the metadata it works, so there's definitely a way to get to the source file and download it. I believe this must be a bug

Output
```bash
> $ youtube-dl -v --get-url https://vimeo.com/202854234                 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--get-url', u'https://vimeo.com/202854234']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.03
[debug] Python version 2.7.11 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
https://skyfire.vimeocdn.com/1491277824-0xb0756a8ca3d9f1ccabbb01dd01a99228580507d3/202854234/sep/video/716807024,716807023/../
https://skyfire.vimeocdn.com/1491277824-0xb0756a8ca3d9f1ccabbb01dd01a99228580507d3/202854234/sep/video/716807024,716807023/../
```

**Comment by dstftw** [comment]
These are the base URLs of the DASH manifests because best formats are served via DASH.

**Comment by amhed** [comment]
Any guidance on how to get the URL I'm looking for? or simply not possible for non-embeddable videos?

**Comment by Hrxn** [comment]
> WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden

Is this expected?

**Comment by denmarkin** [comment]
@dstftw so how one gets a download URL for this file? The JSON embed config is not available for this non-embeddable video, and if lower quality can be downloaded, it would be nice to have instead of DASH.

**Comment by denmarkin** [comment]
Tried:
````
$ youtube-dl -f bestvideo+bestaudio "https://skyfire.vimeocdn.com/1491439395-0xa169686f1ca8fcb465aaa76494d0eb4b701769aa/202854234/video/716807024,716807023/master.mpd?base64_init=1"
[generic] master: Requesting header
WARNING: Falling back on generic information extractor.
[generic] master: Downloading webpage
[generic] master: Extracting information
ERROR: requested format not available
````

**Comment by denmarkin** [comment]
@dstftw

**Comment by 1000heads-luke** [comment]
**STEER CLEAR OF dash-downloader**

Looks like the domain expired, and someone caught it and have redirected it to dodgy websites.
