### ISSUE TITLE
Doesn't list 1080p quality

### ISSUE THREAD

**Issue by anga83** [rg3/youtube-dl#12632]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**
- [x] Bug report (encountered problems with youtube-dl)

Hi there!
Since a few weeks or so youtube-dl doesn't list all available resolutions anymore. Most YouTube videos I want to download are in 1080p60, but youtube-dl doesn't list it.

However, it does list a 1920x1080 DASH video, but it's video-only. The "best" resolution is always 720p30. 

Do I really have to mux a video- and audio-only file or is this in fact an issue?

Kind regards!

**Comment by dstftw** [comment]
>Do I really have to mux a video- and audio-only file

You do. There is no single file 1080p.

**Comment by Hrxn** [comment]
Muxing? youtube-dl does this automatically for you..
