### ISSUE TITLE
Periscope is broken (again!)

### ISSUE THREAD

**Issue by GGGunrunner** [rg3/youtube-dl#12639]
They changed something again, so it stopped to work. Anyone has a fix?

youtube-dl --version
2017.03.10

root@:~# youtube-dl https://www.pscp.tv/xxxx/1djxXvqdV5LGZ
[generic] 1djxXvGZ: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1djdV5LGZ: Downloading webpage
[generic] 1djxV5LGZ: Extracting information
[generic] card: Requesting header
WARNING: Falling back on generic information extractor.
[generic] card: Downloading webpage
[generic] card: Extracting information
ERROR: Unsupported URL: https://www.pscp.tv/w/1dqYGZ/card

**Comment by dstftw** [comment]
Outdated version.

**Comment by siddht1** [comment]
use sudo youtube-dl -U  , to update
