### ISSUE TITLE
output encoding error with Cyrillic video names

### ISSUE THREAD

**Issue by waitforminute** [rg3/youtube-dl#12630]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

youtube-dl.exe -v --get-filename https://www.vbox7.com/play:ce87ed7f96
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--get-filename', 'https://www.vbox7.com/play:
ce87ed7f96']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.03
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 1.2
[debug] Proxy map: {}
[debug] Using fake IP 95.42.120.253 (BG) as X-Forwarded-For.
WARNING: unable to extract JSON-LD; please report this issue on https://yt-dl.or
g/bug . Make sure you are using the latest version; type  youtube-dl -U  to upda
te. Be sure to call youtube-dl with the --verbose flag and include its complete
output.
????????? ??? ? ???????????? ?? ????? ??? ???? ?? ?????????-ce87ed7f96.mp4

---

- Single video: https://www.vbox7.com/play:ce87ed7f96

---
The problem is with the name of the video, which is in Cyrillic

youtube-dl is executed on Windows 7 Home Edition
Region And Language (Windows System Settings)
Location: United States
System Locale: English(United States)

**Comment by dstftw** [comment]
Your console font does not support Cyrillic. Select another.
