### ISSUE TITLE
Opus audio conversion failure

### ISSUE THREAD

**Issue by krzyzowiec** [rg3/youtube-dl#1263]
When trying to extract and convert audio from a youtube video into an opus-encoded audio file I get "ERROR: audio conversion failed:" with no further explanation. Both libopus0 and opus-tools are installed and I have no problems with other codecs like vorbis. I'm not sure if this is because of the ffmpeg/avconv issue in Ubuntu or a bug in youtube-dl.

Distribution: Ubuntu 13.04
Version: 2013.08.17

Debug output:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 589, in post_process
    keep_video_wish,new_info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/PostProcessor.py", line 205, in run
    raise PostProcessingError(msg)
PostProcessingError

**Comment by kstohr** [comment]
I am getting the same error message using youtube-dl installed with `--enable-libopus`.  I am trying to extract audio from an .mp4 file. The audio codec in the container is 'aac'. I am trying to extract the audio and convert it to ogg/opus for transcription.  Any insight into why this is happening very much appreciated. 

I have tried uninstalling and reinstalling/compiling both Youtube-dl and FFMPEG. I confirmed that libopus is enabled. 

I get the following error message running Python 3.6.2 on OS 10.11.6 with FFMPEG 3.3.4 using the [sample code](https://github.com/rg3/youtube-dl#embedding-youtube-dl) provided for embedding youtube-dl in python scripts: 

`Python 3.6.2 (default, Jul 17 2017, 16:44:47) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
 from pblc.audio_video_utils import DownloadConvert
 file_input = "https://s3-us-west-2.amazonaws.com/pblc02/media/test_video/sausalito_nov2016_5min_conv.mp4"
 file_output = './test/test_files/sausalito_nov2016_5min_conv.ogg'
 audio_codec = 'opus'
 dl = DownloadConvert(file_input, file_output, audio_codec)
 dl.download_convert_file()
Done downloading, now converting ...
ERROR: audio conversion failed: Conversion failed!`

Here is the traceback: 

`
Traceback (most recent call last):
  File "/Users/kate/dev/pblc_dev/pblc_02/web_app/venv3/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 234, in run_ffmpeg
    FFmpegPostProcessor.run_ffmpeg(self, path, out_path, opts)
  File "/Users/kate/dev/pblc_dev/pblc_02/web_app/venv3/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 208, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/Users/kate/dev/pblc_dev/pblc_02/web_app/venv3/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!'
`
Converting to flac works just fine: 

`
2.amazonaws.com/pblc02/media/test_video/sausalito_nov2016_5min_conv.mp4"
 file_output = './test/test_files/sausalito_nov2016_5min_conv.flac'
 audio_codec = 'flac'
 dl = DownloadConvert(file_input, file_output, audio_codec)
 dl.download_convert_file()
Done downloading, now converting ...
File conversion done.`
`
FFMPEG config info: 

`$ ffmpeg -version
ffmpeg version 3.3.4 Copyright (c) 2000-2017 the FFmpeg developers
built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
configuration: --prefix=/usr/local/Cellar/ffmpeg/3.3.4 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libopus --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma --enable-vda
libavutil      55. 58.100 / 55. 58.100
libavcodec     57. 89.100 / 57. 89.100
libavformat    57. 71.100 / 57. 71.100
libavdevice    57.  6.100 / 57.  6.100
libavfilter     6. 82.100 /  6. 82.100
libavresample   3.  5.  0 /  3.  5.  0
libswscale      4.  6.100 /  4.  6.100
libswresample   2.  7.100 /  2.  7.100
libpostproc    54.  5.100 / 54.  5.100`
