### ISSUE TITLE
--prefer-ffmpeg: command not found

### ISSUE THREAD

**Issue by winterflags** [rg3/youtube-dl#12647]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -f hls-238 https://www.svtplay.se/video/13049986/aktuellt/aktuellt-28-mar-21-00-1?start=auto&tab=senaste --prefer-ffmpeg -v
[1] 57386
-bash: --prefer-ffmpeg: command not found
[SVTPlay] 13049986: Downloading webpage
[SVTPlay] 1377163-050L: Downloading JSON metadata
[SVTPlay] 1377163-050L: Downloading m3u8 information
[SVTPlay] 1377163-050L: Downloading m3u8 information
[SVTPlay] 1377163-050L: Downloading MPD manifest
[SVTPlay] 1377163-050L: Downloading f4m manifest
[download] 100% of 78.63MiB
[ffmpeg] Fixing malformated aac bitstream in "28 mar 21.00 - textat-1377163-050L.mp4"
ERROR: av_interleaved_write_frame(): Invalid argument
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

After updating to 2017.04.03, `--prefer-ffmpeg` is no longer a recognized command. Note that while the site I'm downloaded from isn't Youtube.com, the very same command I use above has worked in previous months without problem, including `--prefer-ffmpeg`.

**Comment by dstftw** [comment]
You have to either put the URL into quotes or manually escape all the special shell characters. Read [FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for details.
