### ISSUE TITLE
Skipping unavailable vidoes

### ISSUE THREAD

**Issue by skarbs001** [rg3/youtube-dl#12640]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
I have a problem to collect explosion videos. Is there any solution of this problem or What should I do for skipping this youtube url?
For example, https://www.youtube.com/watch?v=50NJtOZ5qO4
```
$ youtube-dl -v -g -i 'https://www.youtube.com/watch?v=50NJtOZ5qO4'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-g', u'-i', u'https://www.youtube.com/watch?v=50NJtOZ5qO4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.03
[debug] Python version 2.7.5 - Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
ERROR: 50NJtOZ5qO4: YouTube said: This video is not available.
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
ie_result = ie.extract(url)
File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 429, in extract
ie_result = self._real_extract(url)
File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1403, in _real_extract
expected=True, video_id=video_id)
ExtractorError: 50NJtOZ5qO4: YouTube said: This video is not available.
...
<end of log>
```

**Comment by dstftw** [comment]
You already skip it with `-i`.

**Comment by skarbs001** [comment]
It does not solved. With python, my script is broke down that url. Is it possible not to display error message?
```
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
ie_result = ie.extract(url)
File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 429, in extract
ie_result = self._real_extract(url)
File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1403, in _real_extract
expected=True, video_id=video_id)
ExtractorError: 50NJtOZ5qO4: YouTube said: This video is not available.'''
 This video is not available.?
```

**Comment by Hrxn** [comment]
True, but not really helpful.

Okay, I think it's because you try to extract the URLs with `-g`.
I guess that's why DASH fails here somehow, also, might or might not be related: You should update ffmpeg.
