### ISSUE TITLE
Unable to extract IMDB webpage description error

### ISSUE THREAD

**Issue by itsthejb** [rg3/youtube-dl#12642]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl --verbose "http://www.imdb.com/video/imdb/vi2537731865/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.imdb.com/video/imdb/vi2537731865/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.03
[debug] Python version 2.7.5 - Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[imdb] 2537731865: Downloading webpage
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[imdb] 2537731865: Downloading player page
[imdb] 2537731865: Downloading info for SD format
[imdb] 2537731865: Downloading info for 1080p HD format
[debug] Invoking downloader on u'http://video-http.media-imdb.com/MV5BZmRlYTNlZTctNmI4OS00YmI2LThhZmMtODBkZWUzMzkzNmJmXkExMV5BbXA0XkFpbWRiLWV0cy10cmFuc2NvZGU@.mp4?Expires=1491350120&Signature=3rtLd1zcgvt1KfKYVVs3hKoflTOLrth1XhcuWJDeO-cmYkCHhNvTSdxnsZ-rshJrviXAdU8Q-gPrzZ-~PMVb-su8U76R~VGe5RPMKG6JmzSojT61c9DMwhiPF~79mMfVGMhN6XCa5CKeP2-2FMic4nBgp84FNUvqegT5zsQyp2Q_&Key-Pair-Id=APKAILW5I44IHKUN2DYA'
[download] Destination: Moonlight Trailer (Official Trailer)-2537731865.mp4
[download]   0.4% of 65.98MiB at 315.83KiB/s ETA 03:33^C
ERROR: Interrupted by user
```

---

### Description of your *issue*, suggested solution and other information

Description cannot be extracted for provided URL. Warning is thrown.

**Comment by isaacm** [comment]
The sample video link provided doesn't include a description in the scraped data. According to [REAMDE.md](https://github.com/rg3/youtube-dl/blob/master/README.md) the description field is optional and a warning is emitted when a description cannot be parsed.

Otherwise a default value can be added when an imdb trailer description is not present by setting a sane default [here](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/imdb.py#L43-L45).

**Comment by itsthejb** [comment]
Ok, great, thanks @isaacm. The warning seemed to suggest this might be a parsing issue that might require a fix. I'll do as you suggest and close this.
