### ISSUE TITLE
Downloading using only video id

### ISSUE THREAD

**Issue by devkhan** [rg3/youtube-dl#12656]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**

- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Does downloading a video using only an ID works for youtube only? Or any other sites are also supported?

e.g. `youtube-dl -g IfYjGxI6A`

**Comment by dstftw** [comment]
YouTube only. Otherwise there is an ambiguity.

**Comment by devkhan** [comment]
@dstftw Thanks.
