### ISSUE TITLE
[vidlo] Site support request

### ISSUE THREAD

**Issue by best-job** [rg3/youtube-dl#12660]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**

- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
youtube-dl -v http://www.vidlo.us/embed-gx39ehlfrlis.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.vidlo.us/embed-gx39ehlfrlis.html']
[debug] Encodings: locale cp1256, fs mbcs, out cp720, pref cp1256
[debug] youtube-dl version 2017.04.03
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[generic] embed-gx39ehlfrlis: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed-gx39ehlfrlis: Downloading webpage
[generic] embed-gx39ehlfrlis: Extracting information
ERROR: Unsupported URL: http://www.vidlo.us/embed-gx39ehlfrlis.html
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\extractor\common.py", line 428, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\extractor\generic.py", line 2667, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.vidlo.us/embed-gx39ehlfrlis.html
...
<end of log>
```
---
- Single video: http://www.vidlo.us/embed-gx39ehlfrlis.html
---

**Comment by dstftw** [comment]
Video does not play in browser.
