### ISSUE TITLE
Cannot download YouTube DASH audio format 140 : ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>

### ISSUE THREAD

**Issue by sebma** [rg3/youtube-dl#12666]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.04.03
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

---
Hi,

When I try and download the M4A of a youtube video : 
```
$ youtube-dl -F http://www.youtube.com/watch?v=FXsRDxcxmTA | grep m4a
140          m4a        audio only DASH audio  132k , m4a_dash container, mp4a.40.2@128k (44100Hz)
```
Here is what I see only on this selected format : 
```
$ youtube-dl -v -f 140 http://www.youtube.com/watch?v=FXsRDxcxmTA
[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg', u'--no-warnings', u'--restrict-filenames', u'-o', u'%(title)s__%(format_id)s__%(id)s.%(ext)s', u'--format', u'mp4/webm/best', u'--add-metadata', u'--write-auto-sub']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'140', u'http://www.youtube.com/watch?v=FXsRDxcxmTA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.03
[debug] Python version 2.7.6 - Linux-4.4.0-67-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 3.2.4-2, ffprobe 3.2.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] FXsRDxcxmTA: Downloading webpage
[youtube] FXsRDxcxmTA: Downloading video info webpage
[youtube] FXsRDxcxmTA: Extracting video information
[youtube] FXsRDxcxmTA: Looking for automatic captions
[youtube] FXsRDxcxmTA: Downloading MPD manifest
[debug] Invoking downloader on u'https://r15---sn-4gxx-25gel.googlevideo.com/videoplayback/id/157b110f17319930/itag/140/source/youtube/requiressl/yes/mm/31/ms/au/initcwndbps/938750/mv/m/nh/EAE/pcm2cms/yes/mn/sn-4gxx-25gel/pl/12/ratebypass/yes/mime/audio%2Fmp4/otfp/1/gir/yes/clen/86358412/lmt/1485506838722202/dur/5437.323/key/dg_yt0/upn/eu4sv-vHg8g/signature/1B72FBBA602D778A83A1A69C237DD8A50836416F.02056518723E722F0CC6021CB3F7055B15CBD833/mt/1491476846/ip/78.243.8.240/ipbits/0/expire/1491498520/sparams/ip,ipbits,expire,id,itag,source,requiressl,mm,ms,initcwndbps,mv,nh,pcm2cms,mn,pl,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 545
[download] Destination: A_Touch_of_His_Presence_2_Joseph_Prince_Songs__140__FXsRDxcxmTA.m4a
[download]   1.1% of ~68.88MiB at  1.53MiB/s ETA 01:44ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1797, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1739, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 76, in real_download
    if not process_segment(segment, ctx['tmpfilename'], i):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 48, in process_segment
    'http_headers': info_dict.get('http_headers'),
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2100, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1089, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 101] Network is unreachable>

$ echo $?
1
```
Can you help

**Comment by dstftw** [comment]
Fix your network connection.

**Comment by sebma** [comment]
My network is working OK otherwise I would not be able to download other audio DASH format like this one : 
```
$ youtube-dl -f 171 http://www.youtube.com/watch?v=FXsRDxcxmTA
[youtube] FXsRDxcxmTA: Downloading webpage
[youtube] FXsRDxcxmTA: Downloading video info webpage
[youtube] FXsRDxcxmTA: Extracting video information
[youtube] FXsRDxcxmTA: Looking for automatic captions
[youtube] FXsRDxcxmTA: Downloading MPD manifest
[download] Destination: A_Touch_of_His_Presence_2_Joseph_Prince_Songs__171__FXsRDxcxmTA.webm
[download] 100% of 66.04MiB in 00:34
```

I'm not saying `youtube-dl` is reponsible maybe it is coming from another reason : 
"YouTube cache servers located in France having issues ?"

Or maybe I have to trick the `--fragment-retries` parameter ?

**Comment by ManuCart** [comment]
Same problem for me with 100% sure good network

**Comment by sebma** [comment]
@dstftw I'm also 100% sure my network is OK,  please reopen this issue !
