### ISSUE TITLE
Some ustream videos can't be downloaded

### ISSUE THREAD

**Issue by sifadil** [rg3/youtube-dl#12662]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

```
youtube-dl.exe -v  "http://www.ustream.tv/recorded/100659713"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.ustream.tv/recorded/100659713']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.04.03
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-85266-g1229007, ffprobe N-85266-g1229007
[debug] Proxy map: {}
[ustream] 100659713: Downloading JSON metadata
[ustream] 100659713: Downloading connection info
[ustream] 100659713: Downloading stream info
[ustream] 100659713: Downloading connection info (try 2)
[ustream] 100659713: Downloading stream info (try 2)
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\ustream.py", line 217, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\common.py", line 1042, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

### Description of the *issue*, suggested solution and other information

Hello.
Some (not all) videos from ustream as the one present in the output above are not supported by youtube-dl.
Here is the callstack of the execution interrupted right at the point where the problem appear:
```
InfoExtractor._download_json in common line 665	Python
UstreamIE._get_stream_info in ustream line 106	Python
UstreamIE._get_streams in ustream line 113	Python
UstreamIE._real_extract in ustream line 204	Python
InfoExtractor.extract in common line 429	Python
YoutubeDL.extract_info in YoutubeDL line 761	Python
YoutubeDL.download in YoutubeDL line 1890	Python
```

Inside "InfoExtractor._download_json" the function "_download_webpage" is called to download a JSON-formatted file containing some infos about the video.

Here is the last few lines of a JSON file describing an ustream video that youtube-dl can download:
```
   "stream":[
               {
                  "name":"uhls",
                  "url":"http://c742eece-lp-live.ums.ustream.tv/playlist/auditorium/recorded/100652907/playlist.m3u8?token=17518093_1491439035019&appType=11&appVersion=2&ts=1491439035&chunkingType=improved&geo=US&sgn=887863d4a1b5549864f56e941dadae2a5f874363&cdnHost=uhs-akamai.ustream.tv/"
               }
            ]
         }
      ],
      "cmd":"moduleInfo"
   }
```
And the next snippet is from the JSON file of the video I'm trying to download:
```
"args":[
         {
            "stream":[

            ]
         }
      ],
      "cmd":"moduleInfo"
   }
```
It seems that the stream link (m3u8 file) is missing in the above JSON file.

Unfortunatly, I have no idea how to solve the issue. And my zero knowledge about python isn't helping me either.

**Comment by sifadil** [comment]
It seems that the video was deleted because it reached 30 day.
Here is annother one with the same problem
http://www.ustream.tv/recorded/101156587

**Comment by yan12125** [comment]
http://www.ustream.tv/recorded/101156587 is also gone. Any new example?

**Comment by yan12125** [comment]
Closing as no response for a long time. Feel free to open a new issue if another Ustream video breaks youtube-dl.
