### ISSUE TITLE
Unable to download webpage

### ISSUE THREAD

**Issue by timr2000** [rg3/youtube-dl#12677]
## Please follow the guide below
When it's trying to download a song

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\timre>youtube-dl -v https://www.youtube.com/watch?v=PKB4cioGs98&index=1&list=PL88Ww8rCURdYZdsydJbCftUT8WOMDdipj
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=PKB4cioGs98']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.04.03
[debug] Python version 3.5.1 - Windows-10-10.0.14393-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] PKB4cioGs98: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [WinError 10060] Een verbindingspoging is mislukt omdat de verbonden party niet correct heeft geantwoord na een bepaalde tijd, of de gemaakte verbinding is mislukt omdat de verbonden host niet heeft geantwoord> (caused by URLError(TimeoutError(10060, 'Een verbindingspoging is mislukt omdat de verbonden party niet correct heeft geantwoord na een bepaalde tijd, of de gemaakte verbinding is mislukt omdat de verbonden host niet heeft geantwoord', None, 10060, None),))
  File "c:\users\timre\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\extractor\common.py", line 498, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\timre\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2100, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\timre\appdata\local\programs\python\python35\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "c:\users\timre\appdata\local\programs\python\python35\lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "c:\users\timre\appdata\local\programs\python\python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "c:\users\timre\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\utils.py", line 1089, in https_open
    req, **kwargs)
  File "c:\users\timre\appdata\local\programs\python\python35\lib\urllib\request.py", line 1242, in do_open
    raise URLError(err)

'index' is not recognized as an internal or external command,
operable program or batch file.
'list' is not recognized as an internal or external command,
operable program or batch file.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by masonelmore** [comment]
The ampersand (`&`) is used to "separate multiple commands on one command line" (https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/ntcmds_shelloverview.mspx).

You can work around that by surrounding the URL with double-quotes (`"`) like this:
`youtube-dl -v "https://www.youtube.com/watch?v=PKB4cioGs98&index=1&list=PL88Ww8rCURdYZdsydJbCftUT8WOMDdipj"`

**Comment by LeLobster** [comment]
The `&` isn't causing the issue, the `WinError 10060` seems to come and go no matter what url you pass to `youtube-dl`
I think it's a Google server thing, not software related.

**Comment by masonelmore** [comment]
Oh, right.  I missed the `WinError 10060`.  Yeah, it's a network issue, not youtube-dl.
