### ISSUE TITLE
How to extract dynamic live youtube url from youtube channel

### ISSUE THREAD

**Issue by limiteddi** [rg3/youtube-dl#12684]
Youtube channel periodically changes URL for its live channel.
https://www.youtube.com/user/10TVNewsChannel
What is the best way to extract live url from this channel?

**Comment by dstftw** [comment]
https://www.youtube.com/user/10TVNewsChannel/live

**Comment by limiteddi** [comment]
Thank you!

**Comment by limiteddi** [comment]
How about something like this
https://www.youtube.com/channel/UCFLM-M7PthQgxyulzSSVYrA
Here, the link is not located in https://www.youtube.com/channel/UCFLM-M7PthQgxyulzSSVYrA/live
