### ISSUE TITLE
Batch file is not working

### ISSUE THREAD

**Issue by AngularLover** [rg3/youtube-dl#12691]
Hi,

I have created a batch file with the following:

start /b "" "D:\Youtube\youtube-dl.exe" --min-sleep-interval 35 --max-sleep-interval 40 -u xxxxxxx -p yyyyyyy -o /%(playlist)s/%(playlist_index)s-%(chapter)s-%(title)s.%(ext)s --batch-file batchfile.txt

The only issue is it is downloading the file with **(playlist_index)s-(title)s.(ext)s** name. The next file over writing the file with the same name.

Thanks

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#output-template-and-windows-batch-files
