### ISSUE TITLE
Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 403

### ISSUE THREAD

**Issue by abuzaforbg** [rg3/youtube-dl#12703]
I'm using latest version of youtube-dl. Everything was fine but from now (at the date of writing: 04/10/2017) I'm getting error like:

`WARNING: [youtube] _********: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)`

Though the video is downloading after the error message appearing but it's extremely slow.

**Comment by LeLobster** [comment]
@dstftw I think there is something going on though, it's not a coincidence multiple reports have come in about this, all around the same time. And simply saying 'Fix your network connection.' doesn't solve anything.

Because nothing changed in my network when this error started showing up.
