### ISSUE TITLE
[Request] yesmovies.to

### ISSUE THREAD

**Issue by its0x08** [rg3/youtube-dl#12702]
please make an extractor  for yesmovies.to ...
its an awesome site for series and movies and is based on googlevideo so is as fast as youtube !!
I hope u consider my extractor request!

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by its0x08** [comment]
damn with u guys 
y do i need to do pass through the whole template just to request a new extractor .?!
btw u can make a template only for requests!!
thanks in advance
