### ISSUE TITLE
[Extractro Request] YesMovies.to

### ISSUE THREAD

**Issue by its0x08** [rg3/youtube-dl#12705]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.09**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### *site support request* 
- Playlist: https://yesmovies.to/movie/the-flash-season-3-16869/509432-8/watching.html
---

### Description of your *issue*, suggested solution and other information

I would like for you guys to add YesMovies.to site extractor to this project.
As far as I know it doesn't violate any copyright.
*Note:* there is just one URL for the playlist, so I would like to ask 2 separated extractors. One for single video and the other for the whole list !

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
https://www.google.com/transparencyreport/removals/copyright/searchdata/domains/?id=yesmovies.to

**Comment by its0x08** [comment]
-_-
for example XNXX has 99.99% of media stolen from MOFOS and Brazzers but u still added an extractor of XNXX
I dont even understand have to check sites on google -_- !!
u guys r trying to look cool but most of stuff u do and say doesn't really make sense !!
@dstftw  @rg3
