### ISSUE TITLE
How do you get the source url (youtube-dl -g) when the webpage returns a manifest? such as m3u8 (get highest quality video from the m3u8).. thank you.﻿

### ISSUE THREAD

**Issue by putout** [rg3/youtube-dl#12710]
Im able to use the -g option to get the source video of a url example

youtube-dl -g www.example.com/videopage.htm
would echo a playlist on certain sites but what if the playlist is a m3u8 im able to use the option from help to dump the playlist but not echo a url from it. thank you.

youtube-dl -g --dump-single-json  hwww.example.com/videopage.htm

**Comment by dstftw** [comment]
m3u8 is set of fragments. There is no single video URL.

**Comment by putout** [comment]
are you sure its fragments, it has a list of mp4 urls beginging in http
