### ISSUE TITLE
Video on www.c8.fr fails to be downloaded and raises ExtractorError.

### ISSUE THREAD

**Issue by xaba** [rg3/youtube-dl#12711]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.11*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### Full verbose output:
$ youtube-dl  --verbose http://www.c8.fr/c8-divertissement/ms-salut-les-terriens/pid7527-emission.html?vid=14438
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.c8.fr/c8-divertissement/ms-salut-les-terriens/pid7527-emission.html?vid=14438']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.11
[debug] Python version 2.7.13 - Linux-4.9.0-1-amd64-x86_64-with-debian-9.0
[debug] exe versions: avconv 3.2.4-1, avprobe 3.2.4-1, ffmpeg 3.2.4-1, ffprobe 3.2.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[Canalplus] pid7527-emission: Downloading webpage
[Canalplus] 14438: Downloading video JSON
ERROR: An extractor error has occurred. (caused by StopIteration()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/xavier/src/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/home/xavier/src/youtube-dl/youtube-dl/youtube_dl/extractor/canalplus.py", line 137, in _real_extract
    fmt_url = next(iter(media.get('VIDEOS')))
StopIteration
Traceback (most recent call last):
  File "/home/xavier/src/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/home/xavier/src/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 442, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by StopIteration()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

<end of log>

---

### Description of your *issue*, suggested solution and other information

This video couldn't be downloaded.

**Comment by dstftw** [comment]
>Désolé, ce contenu n'est plus disponible.

**Comment by xaba** [comment]
Hi, why is this issue invalid please?

**Comment by dstftw** [comment]
Read my post.
