### ISSUE TITLE
tbs f4m not found

### ISSUE THREAD

**Issue by gavbn** [rg3/youtube-dl#12714]
Hi,I was trying to rip subs from tbs and I am getting an error stating that "Warning:Unable to download f4m manifest:HTTP Error 404:Not found" and here is code that I used to rip subs from tbs youtube-dl --skip-download --all-subs --sub-format "srt"  "http://www.tbs.com/videos/american-dad/season-12/episode-8/whole-slotta-love.html" --ap-mso Comcast_SSO --ap-u user --ap-p password.I am using the latest version of youtube-dl: youtube-dl 2017.04.11

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
