### ISSUE TITLE
8K 60 fps support?

### ISSUE THREAD

**Issue by abdullahseba** [rg3/youtube-dl#12715]
Hi
This is an awesome piece of software but 8K 60FPS support would help a lot.
Right now it seems to support up to 4K.
8K 60FPS example:
https://www.youtube.com/watch?v=1La4QzGeaaQ
All the YouTube downloaders I use to use for 8K are paid for now.
Thanks.

**Comment by dstftw** [comment]
>272          webm       7680x4320  4320p60 90128k , vp9, 60fps, video only, 2.70GiB
