### ISSUE TITLE
Can I skip when certain error occurs but continue when others raise?

### ISSUE THREAD

**Issue by Vargnatt** [rg3/youtube-dl#12729]
I use python to load youtube_dl pakcage and scheduled a download list. What I want to do is to get the exact type of error. For example, I expect download continue if video is region restricted or private, as `ignoreerror` is on, but if network goes down, say, `urlopen error` or somewhat `Errno -3` , I want program save a checkpoint and exit.

**Comment by dstftw** [comment]
Handle exceptions appropriately.
