### ISSUE TITLE
"token" parameter not in video inf o for unknown reason

### ISSUE THREAD

**Issue by r-leafar** [rg3/youtube-dl#12727]
C:\Users\a1300105\Downloads>youtube-dl.py --no-check-certificate "https://www.yo
utube.com/watch?v=hmbkDw287dY" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', 'https://www.youtube.com/w
atch?v=hmbkDw287dY', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.04.11
[debug] Python version 3.6.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] hmbkDw287dY: Downloading webpage
[youtube] hmbkDw287dY: Downloading video info webpage
ERROR: hmbkDw287dY: "token" parameter not in video info for unknown reason; plea
se report this issue on https://yt-dl.org/bug . Make sure you are using the late
st version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
--verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\a1300105\Downloads\youtube-dl.py\youtube_dl\YoutubeDL.py", line
 761, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\a1300105\Downloads\youtube-dl.py\youtube_dl\extractor\common.py
", line 429, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\a1300105\Downloads\youtube-dl.py\youtube_dl\extractor\youtube.p
y", line 1407, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: hmbkDw287dY: "token" parameter not in video inf
o for unknown reason; please report this issue on https://yt-dl.org/bug . Make s
ure you are using the latest version; type  youtube-dl -U  to update. Be sure to
 call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by r-leafar** [comment]
C:\Users\a1300105\Downloads>youtube-dl.py --no-check-certificate "https://youtu.
be/cQoGjF6zW8A" --verbose --dump-pages
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', 'https://youtu.be/cQoGjF6z
W8A', '--verbose', '--dump-pages']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.04.14
[debug] Python version 3.6.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] cQoGjF6zW8A: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [WinError 10060] Uma tentativa
 de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu> (caused by URLError(TimeoutError(10060, '
Uma tentativa de conexão falhou porque o componente conectado não respondeu\r\nc
orretamente após um período de tempo ou a conexão estabelecida falhou\r\nporque
o host conectado não respondeu', None, 10060, None),))
  File "C:\Users\a1300105\Downloads\youtube-dl.py\youtube_dl\extractor\common.py
", line 498, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\a1300105\Downloads\youtube-dl.py\youtube_dl\YoutubeDL.py", line
 2100, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 504, in _call_cha
in
    result = func(*args)
  File "C:\Users\a1300105\Downloads\youtube-dl.py\youtube_dl\utils.py", line 108
9, in https_open
    req, **kwargs)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)

**Comment by dstftw** [comment]
Second error is different and indicates a network issue on your side.

**Comment by frozenstein** [comment]
I can reproduce this issue with youtube-dl right after commit 00a9a25cf9ff72a83aaef7dae6e4e16296f74d89 and this video: https://www.youtube.com/watch?v=cpbbuaIA3Ds

**Comment by JamesSPACE** [comment]
Just reinstall the package using:
sudo apt-get remove youtube-dl
and
sudo apt-get install youtube-dl
