### ISSUE TITLE
can't download pornhub

### ISSUE THREAD

**Issue by denotexist** [rg3/youtube-dl#12722]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.11*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.exe --verbose https://www.pornhub.com/view_video.php?viewkey=ph574a0b11d3b62
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.pornhub.com/view_video.php?viewkey=ph574a0b11d3b62']
[debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[debug] youtube-dl version 2017.04.11
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[PornHub] ph574a0b11d3b62: Downloading webpage
[PornHub] ph574a0b11d3b62: Downloading webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsqdjcx2e\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsqdjcx2e\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsqdjcx2e\build\youtube_dl\extractor\pornhub.py", line 137, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsqdjcx2e\build\youtube_dl\extractor\common.py", line 778, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
- Single video:  https://www.pornhub.com/view_video.php?viewkey=ph574a0b11d3b62

Recently, pornhub started using ssl.
the parsing part does not seem to work.
Probably because of ssl?

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by bitshifter52** [comment]
https://www.pornhub.com/view_video.php?viewkey=ph574a0b11d3b62 - I was able to download this using youtube-dl.

**Comment by dstftw** [comment]
Most likely you are hit by #5930.
Post the output with `--dump-pages`.

**Comment by denotexist** [comment]
thanks for advice.

this is result.

`youtube-dl.exe --verbose --dump-pages https://www.pornhub.com/view_video.php?viewkey=ph574a0b11d3b62
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--dump-pages', 'https://www.pornhub.com/view_video.php?viewkey=ph574a0b11d3b62']
[debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[debug] youtube-dl version 2017.04.15
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[PornHub] ph574a0b11d3b62: Downloading webpage
[PornHub] Dumping request to http://www.pornhub.com/view_video.php?viewkey=ph574a0b11d3b62
PGh0bWw+PHNjcmlwdD4KdmFyIGFyZyA9ICJodHRwOi8vd2FybmluZy5vci5rciI7CnZhciBzdHIgPSBuZXcgQXJyYXkoKTsKc3RyID0gYXJnLnNwbGl0KCImIiwgMSk7CnZhciBhID0gbmV3IEFycmF5KCk7CmEgPSBzdHJbMF0uc3BsaXQoIj0iKTsKdmFyIGIgPSBNYXRoLmZsb29yKGFbMV0gLyAxMDApOwp2YXIgYyA9IG5ldyBBcnJheSgpOwppZihiID09IDEwKXtsb2NhdGlvbi5yZXBsYWNlKCJodHRwOi8vd3d3Lm5hdmVyLmNvbSIpO30KZWxzZSBpZihiID09IDIwKXtsb2NhdGlvbi5yZXBsYWNlKCJodHRwOi8vd3d3LmRhdW0ubmV0Iik7fQplbHNlIGlmKGIgPT0gMzApe2xvY2F0aW9uLnJlcGxhY2UoImh0dHA6Ly93d3cucGFyYW4uY29tIik7fQplbHNleyBjID0gYVswXS5zcGxpdCgiPyIpOwpsb2NhdGlvbi5yZXBsYWNlKGNbMF0pO30KPC9zY3JpcHQ+PC9odG1sPgo=
[PornHub] ph574a0b11d3b62: Downloading webpage
[PornHub] Dumping request to http://www.pornhub.com/view_video.php?viewkey=ph574a0b11d3b62
PGh0bWw+PHNjcmlwdD4KdmFyIGFyZyA9ICJodHRwOi8vd2FybmluZy5vci5rciI7CnZhciBzdHIgPSBuZXcgQXJyYXkoKTsKc3RyID0gYXJnLnNwbGl0KCImIiwgMSk7CnZhciBhID0gbmV3IEFycmF5KCk7CmEgPSBzdHJbMF0uc3BsaXQoIj0iKTsKdmFyIGIgPSBNYXRoLmZsb29yKGFbMV0gLyAxMDApOwp2YXIgYyA9IG5ldyBBcnJheSgpOwppZihiID09IDEwKXtsb2NhdGlvbi5yZXBsYWNlKCJodHRwOi8vd3d3Lm5hdmVyLmNvbSIpO30KZWxzZSBpZihiID09IDIwKXtsb2NhdGlvbi5yZXBsYWNlKCJodHRwOi8vd3d3LmRhdW0ubmV0Iik7fQplbHNlIGlmKGIgPT0gMzApe2xvY2F0aW9uLnJlcGxhY2UoImh0dHA6Ly93d3cucGFyYW4uY29tIik7fQplbHNleyBjID0gYVswXS5zcGxpdCgiPyIpOwpsb2NhdGlvbi5yZXBsYWNlKGNbMF0pO30KPC9zY3JpcHQ+PC9odG1sPgo=
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxijbmwes\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxijbmwes\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxijbmwes\build\youtube_dl\extractor\pornhub.py", line 137, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxijbmwes\build\youtube_dl\extractor\common.py", line 778, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by dstftw** [comment]
Looks like pornhub is blocked by some Korean authorities:
```
<html><script>
var arg = "http://warning.or.kr";
var str = new Array();
str = arg.split("&", 1);
var a = new Array();
a = str[0].split("=");
var b = Math.floor(a[1] / 100);
var c = new Array();
if(b == 10){location.replace("http://www.naver.com");}
else if(b == 20){location.replace("http://www.daum.net");}
else if(b == 30){location.replace("http://www.paran.com");}
else{ c = a[0].split("?");
location.replace(c[0]);}
</script></html>
```
Try accessing it in browser you will be redirected to http://warning.or.kr.

**Comment by denotexist** [comment]
@dstftw
Thanks to you, I have figured out why.
