### ISSUE TITLE
Video download error: http://c.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=5047621992001&pubId=219646971&videoId=5047563058001

### ISSUE THREAD

**Issue by noped** [rg3/youtube-dl#12736]
http://c.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=5047621992001&pubId=219646971&videoId=5047563058001

This is the output of youtube-dl -v 

youtube-dl -v --no-check "http://c.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=5047621992001&pubId=219646971&videoId=5047563058001"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-check', 'http://c.brightcove.com/service
s/mobile/streaming/index/rendition.m3u8?assetId=5047621992001&pubId=219646971&vi
deoId=5047563058001']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.04.14
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-80980-g7af44ce
[debug] Proxy map: {}
[brightcove:legacy] 5047563058001: Downloading webpage
ERROR: brightcove said: A valid ID was not sent for this player.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpykl6x8ju\bu
ild\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpykl6x8ju\bu
ild\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpykl6x8ju\bu
ild\youtube_dl\extractor\brightcove.py", line 287, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpykl6x8ju\bu
ild\youtube_dl\extractor\brightcove.py", line 310, in _get_video_info
youtube_dl.utils.ExtractorError: brightcove said: A valid ID was not sent for th
is player.

**Comment by johnhawkinson** [comment]
Use `--force-generic`; where does this URL come from?

**Comment by noped** [comment]
yes works with that command, its comes from here

https://tinyurl.com/mj8wrap

**Comment by johnhawkinson** [comment]
> yes works with that command, its comes from here
> https://tinyurl.com/mj8wrap

Which is http://ew.com/article/2016/07/23/comic-con-emerald-city-adria-arjona/

I'm not quite sure what you're getting at, since the original raw m3u8 URL is not the sort of thing you would encounter directly. You would get it if you ran `youtube-dl -g http://ew.com/article/2016/07/23/comic-con-emerald-city-adria-arjona/` if that site were properly supported.

#12178 adds support for Brightcove embeds like that page features. If it gets merged, then you would just use `youtube-dl http://ew.com/article/2016/07/23/comic-con-emerald-city-adria-arjona/`

I'm not sure if this is a significant bug or not; it's only apparent because there are more serious problems, I think. But a case could be made that `_VALID_URL` should be more tight in `brightcove.py`:

```py
class BrightcoveLegacyIE(InfoExtractor):
    IE_NAME = 'brightcove:legacy'
    _VALID_URL = r'(?:https?://.*brightcove\.com/(services|viewer).*?\?|brightcove:)(?P<query>.*)'
```

**Comment by yan12125** [comment]
Thanks to @johnhawkinson, this's already supported in the latest version.
```
$ youtube-dl -v "http://ew.com/article/2016/07/23/comic-con-emerald-city-adria-arjona/" 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://ew.com/article/2016/07/23/comic-con-emerald-city-adria-arjona/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.01
[debug] Git HEAD: 50ad078b7
[debug] Python version 3.6.1 - Linux-4.10.13-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] comic-con-emerald-city-adria-arjona: Requesting header
WARNING: Falling back on generic information extractor.
[generic] comic-con-emerald-city-adria-arjona: Downloading webpage
[generic] comic-con-emerald-city-adria-arjona: Extracting information
[generic] 5047563058001: Checking possible brightcove video URL
[download] Downloading playlist: Dorothy won't have ruby red slippers in 'Emerald City', star reveals
[generic] playlist Dorothy won't have ruby red slippers in 'Emerald City', star reveals: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5047563058001: Downloading webpage
[brightcove:new] 5047563058001: Downloading JSON metadata
[brightcove:new] 5047563058001: Downloading m3u8 information
[brightcove:new] 5047563058001: Downloading m3u8 information
[debug] Invoking downloader on 'https://timeincsecure-a.akamaihd.net/rtmp_uds/219646971/201607/3258/219646971_5047621995001_5047563058001.mp4?pubId=219646971&videoId=5047563058001'
[download] Destination: Dorothy won't have ruby red slippers in Emerald City, star reveals-5047563058001.mp4
[download]   3.2% of 62.66MiB at  1.39MiB/s ETA 00:43^CException ignored in: <_io.FileIO name="Dorothy won't have ruby red slippers in Emerald City, star reveals-5047563058001.mp4.part" mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name="Dorothy won't have ruby red slippers in Emerald City, star reveals-5047563058001.mp4.part">

ERROR: Interrupted by user
```
