### ISSUE TITLE
[XTube] Older (flv) videos unsupported

### ISSUE THREAD

**Issue by gnu-andrew** [rg3/youtube-dl#12734]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.14**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.04.14
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

$ youtube-dl http://www.xtube.com/video-watch/A-Super-Run-Part-1-YT-9299752 http://www.xtube.com/video-watch/A-Super-Run-Part-2-XT-9302425
[debug] System config: []
[debug] User config: [u'-v', u'--proxy', u'localhost:8118', u'--restrict-filenames', u'--mark-watched', u'--embed-subs', u'--embed-thumbnail', u'--add-metadata', u'--abort-on-error', u'-f', u'bestvideo[height<=?1080]+bestaudio/best']
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'--restrict-filenames', u'http://www.xtube.com/video-watch/A-Super-Run-Part-1-YT-9299752', u'http://www.xtube.com/video-watch/A-Super-Run-Part-2-XT-9302425']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.11
[debug] Python version 2.7.12 - Linux-4.8.1-gentoo.rivendell-x86_64-Intel-R-_Xeon-R-_CPU_X5482_@_3.20GHz-with-gentoo-2.3
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {u'http': u'localhost:8118', u'https': u'localhost:8118'}
[XTube] A-Super-Run-Part-1-YT: Downloading webpage
ERROR: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/xtube.py", line 72, in _real_extract
    webpage, 'sources', group='sources'), video_id)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 778, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Same with 2017.04.14

$ youtube-dl http://www.xtube.com/video-watch/A-Super-Run-Part-1-YT-9299752 http://www.xtube.com/video-watch/A-Super-Run-Part-2-XT-9302425
[debug] System config: []
[debug] User config: [u'-v', u'--proxy', u'localhost:8118', u'--restrict-filenames', u'--mark-watched', u'--embed-subs', u'--embed-thumbnail', u'--add-metadata', u'--abort-on-error']
[debug] Custom config: []
[debug] Command-line args: [u'--restrict-filenames', u'http://www.xtube.com/video-watch/A-Super-Run-Part-1-YT-9299752', u'http://www.xtube.com/video-watch/A-Super-Run-Part-2-XT-9302425']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.14
[debug] Python version 2.6.6 - Linux-2.6.32-696.el6.x86_64-x86_64-with-redhat-6.9-Santiago
[debug] exe versions: ffmpeg 0.10.16, ffprobe 0.10.16
[debug] Proxy map: {u'http': u'localhost:8118', u'https': u'localhost:8118'}
[XTube] A-Super-Run-Part-1-YT: Downloading webpage
ERROR: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/andrew/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/home/andrew/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/home/andrew/bin/youtube-dl/youtube_dl/extractor/xtube.py", line 72, in _real_extract
    webpage, 'sources', group='sources'), video_id)
  File "/home/andrew/bin/youtube-dl/youtube_dl/extractor/common.py", line 778, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Recent XTube videos do work.

sources is present:

sources:{flv:"https:\/\/cdn1-l-ha-e7.xtube.com\/videos\/2010\/20100301pm\/5139G63ciDI.flv?validfrom=1492106467&validto=1492113667&rate=30&burst=100000&hash=IAfluGlQIaHuHpPgi99GgSZ72WA%3D",480:"https:\/\/cdn1-l-ha-e7.xtube.com\/videos\/2010\/20100301pm\/5139G63ciDI.flv?validfrom=1492106467&validto=1492113667&rate=30&burst=100000&hash=IAfluGlQIaHuHpPgi99GgSZ72WA%3D"}

**Comment by paulguy** [comment]
The fix for this is to change
```
        sources = self._parse_json(self._search_regex(
            r'(["\'])sources\1\s*:\s*(?P<sources>{.+?}),',
            webpage, 'sources', group='sources'), video_id)
```
to
```
        sources = self._parse_json(self._search_regex(
            r'(["\']?)sources\1\s*:\s*(?P<sources>{.+?}),',
            webpage, 'sources', group='sources'), video_id,
            transform_source=js_to_json)
```
and at the under `from ..utils import { ... }` add `js_to_json,`.

**Comment by yan12125** [comment]
Thanks to @paulguy, this will be fixed in the next version.
