### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jfw19051** [rg3/youtube-dl#12735]
Hello!
I would like to know how to download this url:
rtmp://sv02.newmfx.com/mfx3//mp4:MF-6712-1-1/MF-6712-1-1_12000.mp4
I would get the file in mp4 is it possible?

**Comment by dstftw** [comment]
Not possible without more context.

**Comment by jfw19051** [comment]
Why not?

**Comment by jfw19051** [comment]
On your website, you can download jwplayer.
