### ISSUE TITLE
--add-metadata seem to don't work...

### ISSUE THREAD

**Issue by axel584** [rg3/youtube-dl#12742]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
axel@axel-B85M-D2V:/var/www/html/wl$ youtube-dl -x --audio-format mp3 --youtube-skip-dash-manifest --add-metadata https://www.youtube.com/watch?v=uFhDd1bXnfY
[youtube] uFhDd1bXnfY: Downloading webpage
[youtube] uFhDd1bXnfY: Extracting video information
[download] Destination: Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.webm
[download] 100% of 8.43MiB in 00:14
[ffmpeg] Destination: Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3
Deleting original file Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.webm (pass -k to keep)
[ffmpeg] Adding metadata to 'Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3'
axel@axel-B85M-D2V:/var/www/html/wl$ id3tool Visite\ d\'un\ supermarché\ de\ Tokyo\ avec\ une\ famille\ japonaise-uFhDd1bXnfY.mp3 
Filename: Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3
No ID3 Tag

axel@axel-B85M-D2V:/var/www/html/wl$ 
...
<end of log>
```

---
I don't understand how i could add ID3 in my mp3 file ?

**Comment by dstftw** [comment]
```
PS C:\dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py  -x --audio-format mp3 --youtube-skip-dash-manifest --add-metadata https://www.youtube.com/watch?v=uFhDd1bXnfY
[youtube] uFhDd1bXnfY: Downloading webpage
[youtube] uFhDd1bXnfY: Extracting video information
[download] Destination: Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.webm
[download] 100% of 8.43MiB in 00:02
[ffmpeg] Destination: Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3
Deleting original file Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.webm (pass -k to keep)
[ffmpeg] Adding metadata to 'Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3'
PS C:\dev\youtube-dl\master> ffmpeg.exe -i '.\Visite d''un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3'
ffmpeg version N-83622-gdcd3418 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
...
Input #0, mp3, from '.\Visite d'un supermarch├й de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3':
  Metadata:
    artist          : DenisBaupin
    title           : Visite d'un supermarch├й de Tokyo avec une famille japonaise
    date            : 20111024
    description     : Eva Joly et Denis Baupin ont pass├й 1h30 dans un supermarch├й, en compagnie de familles japonaises montrant comment elles tentent de limiter les d├йg├вts sanitaires li├йs ├а la catastrophe nucl├йaire pour leurs enfants, en choisissant soigneusement leurs
    comment         : Eva Joly et Denis Baupin ont pass├й 1h30 dans un supermarch├й, en compagnie de familles japonaises montrant comment elles tentent de limiter les d├йg├вts sanitaires li├йs ├а la catastrophe nucl├йaire pour leurs enfants, en choisissant soigneusement leurs
    purl            : https://www.youtube.com/watch?v=uFhDd1bXnfY
    encoder         : Lavf57.66.102
  Duration: 00:06:12.38, start: 0.023021, bitrate: 65 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, s16p, 65 kb/s
    Metadata:
      encoder         : Lavc57.81
At least one output file must be specified
```
![image](https://cloud.githubusercontent.com/assets/1908898/25051846/ec9557e4-2178-11e7-872b-470246e38346.png)

**Comment by axel584** [comment]
It doesn't work with aconv (under Ubuntu) : 

```
axel@axel-B85M-D2V:/var/www/html/wl$ youtube-dl -x --audio-format mp3  --add-metadata -v https://www.youtube.com/watch?v=uFhDd1bXnfY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-x', u'--audio-format', u'mp3', u'--add-metadata', u'-v', u'https://www.youtube.com/watch?v=uFhDd1bXnfY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.15
[debug] Python version 2.7.12 - Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] uFhDd1bXnfY: Downloading webpage
[youtube] uFhDd1bXnfY: Downloading video info webpage
[youtube] uFhDd1bXnfY: Extracting video information
[youtube] uFhDd1bXnfY: Downloading MPD manifest
[debug] Invoking downloader on u'https://r3---sn-4gxx-25gy.googlevideo.com/videoplayback?ei=IR7xWIaNCI22cL6iqbAD&itag=251&pcm2cms=yes&keepalive=yes&requiressl=yes&signature=0C2A362811963676E91F6E74B6ED739ED7E1A689.942B78F58A9D98852330EB7A67DBA521C2426881&key=yt6&expire=1492218497&gir=yes&mn=sn-4gxx-25gy&mm=31&ip=82.239.0.181&ms=au&mv=m&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mt=1492196790&pl=13&mime=audio%2Fwebm&id=o-ALlT-Jy2VlGQ3dKm8WnFK454KscMpFwC5REg4xx3G3kE&upn=gGom0l_O7Qk&lmt=1427921110881658&ipbits=0&beids=%5B9466593%5D&nh=EAE&initcwndbps=747500&source=youtube&dur=372.341&clen=8842025&ratebypass=yes'
[download] Destination: Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.webm
[download] 100% of 8.43MiB in 00:09
[debug] avconv command line: avprobe -show_streams 'file:Visite d'"'"'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.webm'
[ffmpeg] Destination: Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3
[debug] ffmpeg command line: avconv -y -i 'file:Visite d'"'"'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.webm' -vn -acodec libmp3lame -q:a 5 'file:Visite d'"'"'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3'
Deleting original file Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.webm (pass -k to keep)
[ffmpeg] Adding metadata to 'Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3'
[debug] ffmpeg command line: avconv -y -i 'file:Visite d'"'"'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3' -c copy -metadata 'comment=Eva Joly et Denis Baupin ont passé 1h30 dans un supermarché, en compagnie de familles japonaises montrant comment elles tentent de limiter les dégâts sanitaires liés à la catastrophe nucléaire pour leurs enfants, en choisissant soigneusement leurs aliments.' -metadata 'description=Eva Joly et Denis Baupin ont passé 1h30 dans un supermarché, en compagnie de familles japonaises montrant comment elles tentent de limiter les dégâts sanitaires liés à la catastrophe nucléaire pour leurs enfants, en choisissant soigneusement leurs aliments.' -metadata artist=DenisBaupin -metadata 'title=Visite d'"'"'un supermarché de Tokyo avec une famille japonaise' -metadata date=20111024 -metadata 'purl=https://www.youtube.com/watch?v=uFhDd1bXnfY' 'file:Visite d'"'"'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.temp.mp3'
axel@axel-B85M-D2V:/var/www/html/wl$ id3v2 -l Visite\ d\'un\ supermarché\ de\ Tokyo\ avec\ une\ famille\ japonaise-uFhDd1bXnfY.mp3 
Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3: No ID3 tag

```

**Comment by axel584** [comment]
It doesn't work with avconv under Ubuntu

`
axel@axel-B85M-D2V:/var/www/html/wl$ youtube-dl -x --audio-format mp3 --youtube-skip-dash-manifest --add-metadata --hls-prefer-ffmpeg -v https://www.youtube.com/watch?v=uFhDd1bXnfY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-x', u'--audio-format', u'mp3', u'--youtube-skip-dash-manifest', u'--add-metadata', u'--hls-prefer-ffmpeg', u'-v', u'https://www.youtube.com/watch?v=uFhDd1bXnfY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.15
[debug] Python version 2.7.12 - Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] uFhDd1bXnfY: Downloading webpage
[youtube] uFhDd1bXnfY: Extracting video information
[debug] Invoking downloader on u'https://r3---sn-4gxx-25gel.googlevideo.com/videoplayback?mm=31&mn=sn-4gxx-25gel&key=yt6&clen=8842025&signature=827FED49F69B2B5810661EC702360017B1477BA0.8A015DEC7742F6B82CB8F65BA70FA46DC8ABBE3A&ei=0yLxWI_aI43OWee-idgI&ms=au&mt=1492197988&mv=m&pl=13&requiressl=yes&itag=251&lmt=1427921110881658&keepalive=yes&ip=82.239.0.181&dur=372.341&source=youtube&pcm2cms=yes&id=o-AE68JFOT8XBxpBG_0A9T-H03DCM11UFItOxcxTd9MCEI&nh=EAE&upn=sVZyQijD9-E&mime=audio%2Fwebm&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&expire=1492219699&ipbits=0&initcwndbps=707500&gir=yes&ratebypass=yes'
[download] Destination: Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.webm
[download] 100% of 8.43MiB in 00:07
[debug] avconv command line: avprobe -show_streams 'file:Visite d'"'"'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.webm'
[ffmpeg] Destination: Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3
[debug] ffmpeg command line: avconv -y -i 'file:Visite d'"'"'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.webm' -vn -acodec libmp3lame -q:a 5 'file:Visite d'"'"'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3'
Deleting original file Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.webm (pass -k to keep)
[ffmpeg] Adding metadata to 'Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3'
[debug] ffmpeg command line: avconv -y -i 'file:Visite d'"'"'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3' -c copy -metadata 'comment=Eva Joly et Denis Baupin ont passé 1h30 dans un supermarché, en compagnie de familles japonaises montrant comment elles tentent de limiter les dégâts sanitaires liés à la catastrophe nucléaire pour leurs enfants, en choisissant soigneusement leurs aliments.' -metadata 'description=Eva Joly et Denis Baupin ont passé 1h30 dans un supermarché, en compagnie de familles japonaises montrant comment elles tentent de limiter les dégâts sanitaires liés à la catastrophe nucléaire pour leurs enfants, en choisissant soigneusement leurs aliments.' -metadata artist=DenisBaupin -metadata 'title=Visite d'"'"'un supermarché de Tokyo avec une famille japonaise' -metadata date=20111024 -metadata 'purl=https://www.youtube.com/watch?v=uFhDd1bXnfY' 'file:Visite d'"'"'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.temp.mp3'
axel@axel-B85M-D2V:/var/www/html/wl$ id3v2 -l Visite\ d\'un\ supermarché\ de\ Tokyo\ avec\ une\ famille\ japonaise-uFhDd1bXnfY.mp3 
Visite d'un supermarché de Tokyo avec une famille japonaise-uFhDd1bXnfY.mp3: No ID3 tag

`
