### ISSUE TITLE
Youku.com has stopped working for some reason

### ISSUE THREAD

**Issue by someziggyman** [rg3/youtube-dl#12743]
hey guys. Got a problem with Youku.com videos. It used to work today in the morning (14 April), however now I get an extractor error.  Tried earlier versions of youtube-dl, same error message occurs..

Please see the output with --verbose parameter:

 ./youtube-dl --verbose http://v.youku.com/v_show/id_XMjYxNTM0MjYxNg==.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://v.youku.com/v_show/id_XMjYxNTM0MjYxNg==.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.14
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youku] XMjYxNTM0MjYxNg: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'stream_fileid',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./vydl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "./vydl/youtube_dl/extractor/youku.py", line 255, in _real_extract
    video_urls_dict = self.construct_video_urls(data)
  File "./vydl/youtube_dl/extractor/youku.py", line 108, in construct_video_urls
    fileid = stream['stream_fileid']
KeyError: u'stream_fileid'
Traceback (most recent call last):
  File "./vydl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "./vydl/youtube_dl/extractor/common.py", line 442, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'stream_fileid',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Already fixed.

**Comment by someziggyman** [comment]
Cool! Will there be an updated version? Tried just now again and it gives me the same error...

**Comment by wenlanhuitai** [comment]
**## I have the same error ：** ERROR: An extractor error has occurred. (caused by KeyError(u'stream_fileid',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
