### ISSUE TITLE
Udemy Issues - No video formats found

### ISSUE THREAD

**Issue by MartinGebske** [rg3/youtube-dl#12744]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.04.15
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Hey folks, I encountered an issue on Udemy. Yesterday my downloads went fine.
Today I bought a course and got this error... 

Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. Alle Rechte vorbehalten.

PS C:\Users\marti> cd c:\videos
PS C:\videos> youtube-dl --output "%(playlist_index)s - %(title)s.%(ext)s" -v --retries 15 -u <myEmail>e -
p <myPassword> https://www.udemy.com/csharp-advanced/learn/v4/overview
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--output', '%(playlist_index)s - %(title)s.%(ext)s', '-v', '--retries', '15', '-u', 'PRIVAT
E', '-p', 'PRIVATE', 'https://www.udemy.com/csharp-advanced/learn/v4/overview']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.04.15
[debug] Python version 3.6.1 - Windows-10-10.0.14393-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as <myEmail>
[udemy:course] csharp-advanced: Downloading webpage
[udemy:course] 356030: Downloading course curriculum
[download] Downloading playlist: C# Advanced Topics: Take Your C# Skills to the Next Level
[udemy:course] playlist C# Advanced Topics: Take Your C# Skills to the Next Level: Collected 17 video ids (downloading 1
7 of them)
[download] Downloading video 1 of 17
[udemy] Downloading login popup
[udemy] 1988782: Downloading webpage
[udemy] 1988782: Downloading lecture JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ve
rsion; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include i
ts complete output.
Traceback (most recent call last):
  File "c:\python\lib\site-packages\youtube_dl\YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "c:\python\lib\site-packages\youtube_dl\extractor\common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "c:\python\lib\site-packages\youtube_dl\extractor\udemy.py", line 297, in _real_extract
    self._sort_formats(formats, field_preference=('height', 'width', 'tbr', 'format_id'))
  File "c:\python\lib\site-packages\youtube_dl\extractor\common.py", line 1042, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure y
ou are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --
verbose flag and include its complete output.

**Comment by dstftw** [comment]
For any further investigations you have to provide account credentials.

**Comment by MartinGebske** [comment]
I dropped you an email. I hope this works out?
