### ISSUE TITLE
ERROR: Unable to extract video URL

### ISSUE THREAD

**Issue by raedov818** [rg3/youtube-dl#1274]
raedov@mo:~$ youtube-dl -v "http://video.xnxx.com/video5062796/big_butt_bends_over_for_some_big_dick" 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://video.xnxx.com/video5062796/big_butt_bends_over_for_some_big_dick']
[debug] youtube-dl version 2013.08.17
[debug] Python version 2.7.3 - Linux-3.10.7-031007-generic-x86_64-with-elementary_OS-0.2-luna
[debug] Proxy map: {}
[XNXX] 5062796: Downloading webpage
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 312, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 96, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xnxx.py", line 35, in _real_extract
    webpage, u'video URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 220, in _search_regex
    raise ExtractorError(u'Unable to extract %s' % _name)
ExtractorError: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

raedov@mo:~$ sudo  youtube-dl -U
[sudo] password for raedov: 
youtube-dl is up-to-date (2013.08.17)

**Comment by dstftw** [comment]
Works with latest version. Closing.
