### ISSUE TITLE
 "token" parameter not in video info for unknown reason

### ISSUE THREAD

**Issue by runrun** [rg3/youtube-dl#12753]
youtube-dl --proxy "127.0.0.1:8087" "https://www.youtube.com/watch?v=GJieIpex_nE" --verbos
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', '127.0.0.1:8087', 'https://www.youtube.com/watch?v=GJieIpex_nE', '--verbos']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.04.16
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-66289-gb76d613, ffprobe N-66289-gb76d613
[debug] Proxy map: {'https': '127.0.0.1:8087', 'http': '127.0.0.1:8087'}
[youtube] GJieIpex_nE: Downloading webpage
[youtube] GJieIpex_nE: Downloading video info webpage
ERROR: GJieIpex_nE: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvjlkz75_\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvjlkz75_\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvjlkz75_\build\youtube_dl\extractor\youtube.py", line 1392, in _real_extract
youtube_dl.utils.ExtractorError: GJieIpex_nE: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

>>>
youtube-dl download used to run fine, until last month.... 
proxy is working fine, and viewing without any issue, just youtube-dl stop working somehow.

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by spookyahell** [comment]
You do know the given video was blocked for copyright reasons, right?

**Comment by spookyahell** [comment]
I mean, at least that is what it says if I open the video directly.

**Comment by spookyahell** [comment]
So I guess this should get a cant-reproduce label at this point

**Comment by lotress** [comment]
请换个代理，GoAgent跟youtube-dl搭不来
It seems some proxy like GoAgent does not return full video_info in one request and youtube-dl doesn't try to fetch more.
127.0.0.1 - [2017-04-23 19:24:30] GAE 61.91.161.217 "GET https://www.youtube.com/get_video_info?&video_id=4f2apLEnRM4&ps=default&eurl=&gl=US&hl=en HTTP/1.1" 200 8606
The last number 8606 in the log seems to be the content length in first request, which is much smaller than a typical get_video_info response.

**Comment by yan12125** [comment]
Closing as no response for a long time. For further discussions, output from either --dump-pages or --write-pages is necessary.

**Comment by yan12125** [comment]
> 请换个代理，GoAgent跟youtube-dl搭不来
It seems some proxy like GoAgent does not return full video_info in one request and youtube-dl doesn't try to fetch more.

That's not true. GoAgent-based XX-Net works fine here. (I use another video as https://www.youtube.com/watch?v=GJieIpex_nE is gone)
```
$ youtube-dl --proxy "http://127.0.0.1:8087" "https://www.youtube.com/watch?v=sNWjte7bSs4" --verbose --no-check-certificate                                                                                                  
[debug] System config: []                                                                                       
[debug] User config: []                                                                                         
[debug] Custom config: []                                                                                       
[debug] Command-line args: ['--proxy', 'http://127.0.0.1:8087', 'https://www.youtube.com/watch?v=sNWjte7bSs4', '--verbose', '--no-check-certificate']                                                                           
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8                                                
[debug] youtube-dl version 2017.05.01                                                                           
[debug] Git HEAD: 50ad078b7                                                                                     
[debug] Python version 3.6.1 - Linux-4.10.13-1-ARCH-x86_64-with-arch                                            
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3, rtmpdump 2.4                                                     
[debug] Proxy map: {'http': 'http://127.0.0.1:8087', 'https': 'http://127.0.0.1:8087'}
[youtube] sNWjte7bSs4: Downloading webpage
[youtube] sNWjte7bSs4: Downloading video info webpage
[youtube] sNWjte7bSs4: Extracting video information
[youtube] sNWjte7bSs4: Downloading MPD manifest
[debug] Invoking downloader on 'https://r2---sn-u5oxu-un5e.googlevideo.com/videoplayback?id=b0d5a3b5eedb4ace&itag=137&source=youtube&requiressl=yes&initcwndbps=6112500&ms=au&gcr=tw&pl=22&mm=31&mn=sn-u5oxu-un5e&ei=AygMWcSjOoHt4QLjhLgg&mv=m&ratebypass=yes&mime=video/mp4&gir=yes&clen=1442047852&lmt=1493733104013650&dur=2694.091&upn=PXwRr5V9ouQ&signature=94E8D5DCB66C7307D82205530C7ACF4D85524F5D.5389DB7F84C4D8141CF114F51F0F617B776E83B3&key=dg_yt0&mt=1493968821&ip=140.112.28.103&ipbits=0&expire=1493990500&sparams=ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,ms,gcr,pl,mm,mn,ei,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: 【你對你的好友真的沒遐想？超赤裸腦波實測！】 20170502 綜藝大熱門 X SUGAR糖果手機-sNWjte7bSs4.f137.mp4
[download]   0.1% of 1.34GiB at  1.23MiB/s ETA 18:38^CException ignored in: <_io.FileIO name='【你對你的好友真的沒遐想？超赤裸腦波實測！】 20170502 綜藝大熱門 X SUGAR糖果手機-sNWjte7bSs4.f137.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='【你對你的好友真的沒遐想？超赤裸腦波實測！】 20170502綜藝大熱門 X SUGAR糖果手機-sNWjte7bSs4.f137.mp4.part'>

ERROR: Interrupted by user
```
