### ISSUE TITLE
[Youtube] Extract comment_count

### ISSUE THREAD

**Issue by liudatutu** [rg3/youtube-dl#12756]
I want to download the infomation of movie in youtube,this is my code:

import youtube_dl
ydl_opts = {'encoding':'utf-8','outtmpl':'E:/Movie/%(title)s.%(ext)s'}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    meta = ydl.extract_info(
        'https://www.youtube.com/watch?v=95a0THw88Bg', download=False)
print type(meta)
for i in meta.keys():
    print i,'**',meta[i]

but there's not key "comment_count" in meta, how can i get the value of the key.

**Comment by yan12125** [comment]
Sorry I have to reject this request here. Extracting the comment count requires an additional request to the YouTube server, which brings latency to normal uses.
