### ISSUE TITLE
SAML fail on watchdisneychannel.go.com

### ISSUE THREAD

**Issue by spookyahell** [rg3/youtube-dl#12757]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'http://watchdisneychannel.go.com/liv-an
d-maddie/video/vdka3736366/04/14-voicearooney', '--ap-mso', 'Verizon', '--ap-use
rname', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.04.16
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Go] 14-voicearooney: Downloading webpage
[Go] 3736366: Downloading JSON metadata
[Go] 3736366: Downloading Provider Redirect Page
[Go] 3736366: Downloading SAML Login Page
ERROR: Unable to extract SAML Login URL; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
 update. Be sure to call youtube-dl with the --verbose flag and include its comp
lete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvjlkz75_\bu
ild\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvjlkz75_\bu
ild\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvjlkz75_\bu
ild\youtube_dl\extractor\go.py", line 98, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvjlkz75_\bu
ild\youtube_dl\extractor\adobepass.py", line 1445, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvjlkz75_\bu
ild\youtube_dl\extractor\common.py", line 778, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract SAML Login URL; please re
port this issue on https://yt-dl.org/bug . Make sure you are using the latest ve
rsion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --ver
bose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://watchdisneychannel.go.com/liv-and-maddie/video/vdka3736366/04/14-voicearooney

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

The issue is provided above. Fails to download. I do know that MSO was recently added, so isssues may occur, but I'm hoping someone can work on this.

**Comment by spookyahell** [comment]
Once again I can give someone by email account data needed for logging in

**Comment by SkiTheSlicer** [comment]
Is this still an issue? The listed video is no longer available, but I was able to download this comparable video successfully with my Verizon account: http://watchdisneychannel.go.com/liv-and-maddie/video/vdka3441772/04/03-scarearooney

**Comment by spookyahell** [comment]
Yeah it is I cant download that video or get format info yet.... hmm... I wonder why it's so different...

**Comment by SkiTheSlicer** [comment]
I am running a version with pull request https://github.com/rg3/youtube-dl/pull/14363 in place that I submitted earlier today, so that could be the difference.

**Comment by spookyahell** [comment]
Yes it could... it probably is... if that works that would be totally awesome, does mean that change will apply to the next version?

**Comment by SkiTheSlicer** [comment]
As long as the pull request gets approved, it would be included in the version following its approval. Just to be sure, are you able to log into the Disney Channel website with your Verizon account with a browser to watch the video to confirm that your subscription actually includes that site/video?

**Comment by spookyahell** [comment]
Yes I tried it. It works... I've tried your's as I saw your message and I also watched some other shows from that site earlier today that can only be watched with that subscription...

**Comment by spookyahell** [comment]
This issue is now resolved.. thank you very much @SkiTheSlicer !
