### ISSUE TITLE
VTM.be does not work (internal server error)

### ISSUE THREAD

**Issue by Smile4ever** [rg3/youtube-dl#12762]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [ x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x ] Bug report (encountered problems with youtube-dl)

---
C:\Users\ultimate\Downloads>youtube-dl.exe -U
youtube-dl is up-to-date (2017.04.17)

C:\Users\ultimate\Downloads>youtube-dl.exe https://vtm.be/video/volledige-afleve
ringen/id/257091504828000 --username computergeoffrey@zoho.com --password ******** -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vtm.be/video/volledige-afleveringen/id/2570
91504828000', '--username', 'PRIVATE', '--password', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.04.17
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Medialaan] 257091504828000: Downloading webpage
[Medialaan] Logging in
[Medialaan] 257091504828000: Downloading JSON metadata
[Medialaan] 257091504828000: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 500: Internal Server Erro
r (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . M
ake sure you are using the latest version; type  youtube-dl -U  to update. Be su
re to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\bu
ild\youtube_dl\extractor\common.py", line 498, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\bu
ild\youtube_dl\YoutubeDL.py", line 2106, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt

### Description of your *issue*, suggested solution and other information

I tried downloading https://vtm.be/video/volledige-afleveringen/id/257091504828000

You need an account, but it can be obtained for free when you attempt to load the video.

@mrBliss could you look at it?

**Comment by mrBliss** [comment]
You are not the first one to report that videos of De Zonen van Van As don't work. Unfortunately, there is not much we can do about this, as it is an internal server error caused on VTM's side.

If you can still watch the video in your browser, it is because your browser will use another video stream than the one youtube-dl uses, one that uses DRM, which youtube-dl doesn't support.
