### ISSUE TITLE
How to get current livestream from a channel?

### ISSUE THREAD

**Issue by Bangaio64** [rg3/youtube-dl#12766]
Using channel/$channel_id/live doesn't work for all channels.

Example:
https://www.youtube.com/channel/UCj6PcyLvpnIRT_2W_mwa9Aw/live
Actual live id: https://www.youtube.com/watch?v=0tek2aa8hAQ

I tried:
youtube-dl -f "best" --get-id --get-title --max-downloads 1 --match-title "en directo" https://www.youtube.com/channel/UCR9120YBAqMfntqgRTKmkjQ

But the livestream video isn't always the latest one. Maybe a boolean isLive variable to use with --match-title?

**Comment by dstftw** [comment]
No way to get current live stream then. Parse it from channel page on your own.
