### ISSUE TITLE
[youtube] Some youtube streams can not be downloaded

### ISSUE THREAD

**Issue by WildPenquin** [rg3/youtube-dl#12765]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl -v https://www.youtube.com/watch?v=vyvpbqlNaEw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=vyvpbqlNaEw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.03
[debug] Python version 3.6.0 - Linux-4.10.9-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] vyvpbqlNaEw: Downloading webpage                                                                                                                   
[youtube] vyvpbqlNaEw: Downloading video info webpage                                                                                                        
[youtube] vyvpbqlNaEw: Extracting video information                                                                                                          
[youtube] vyvpbqlNaEw: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r11---sn-uxap5nvoxg5-ixhs.googlevideo.com/videoplayback?id=bf2be96ea94d684c&itag=137&source=youtube&requiressl=yes&mm=31&mn=sn-uxap5nvoxg5-ixhs&ms=au&mv=m&pl=17&pcm2cms=yes&initcwndbps=1478750&ei=ksjzWNeLIsK8Y6ODtoAC&ratebypass=yes&mime=video/mp4&gir=yes&clen=100356881&lmt=1419003277942824&dur=197.800&upn=Mr3LPb1U83Q&mt=1492371499&signature=2A8F3D66521D0E913F0AC590E35FCE1EF55F125E.6DC7C1714C307B0ADA4A0165FBDE0E83060E51D8&key=dg_yt0&ip=84.248.115.246&ipbits=0&expire=1492393202&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,pcm2cms,initcwndbps,ei,ratebypass,mime,gir,clen,lmt,dur'
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
ERROR: unable to download video data: Remote end closed connection without response
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1791, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1739, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2100, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/site-packages/youtube_dl/utils.py", line 1089, in https_open
    req, **kwargs)
  File "/usr/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
``` 
### Description of your *issue*, suggested solution and other information

Hi,

Youtube-dl can not download certain youtube streams, while others work.

Some streams giving me problems:
https://www.youtube.com/watch?v=vyvpbqlNaEw
https://www.youtube.com/watch?v=Sx5_QGdFmq4
https://www.youtube.com/watch?v=zB4I68XVPzQ

There are others. Most streams (>70%) seem to work fine.

**Comment by WildPenquin** [comment]
Sorry, I posted the wrong log. It is informative in that way it demonstrates that a slightly older version gave an HTTP error. The current one seems to hang (indefinitely) - until I press CTRL+C:

´´´´
$ youtube-dl -v https://www.youtube.com/watch?v=zB4I68XVPzQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=zB4I68XVPzQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 3.6.0 - Linux-4.9.20-1-MANJARO-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] zB4I68XVPzQ: Downloading webpage
[youtube] zB4I68XVPzQ: Downloading video info webpage
[youtube] zB4I68XVPzQ: Extracting video information
[youtube] zB4I68XVPzQ: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r11---sn-uxap5nvoxg5-ixhs.googlevideo.com/videoplayback?id=cc1e08ebc5d53f34&itag=137&source=youtube&requiressl=yes&initcwndbps=1477500&pcm2cms=yes&mm=31&mn=sn-uxap5nvoxg5-ixhs&pl=17&mv=m&ei=JczzWM2QJZWuYMyyt_AE&ms=au&ratebypass=yes&mime=video/mp4&gir=yes&clen=37649622&lmt=1492178861497064&dur=132.006&mt=1492372399&upn=pHFdsTBooZc&signature=81704059F288E7C7B632FE3C930F2BD52A35FF4F.597FFD2773664C882EC75BD0B7DB8C1174C6B4B1&key=dg_yt0&ip=84.248.115.246&ipbits=0&expire=1492394117&sparams=ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,pcm2cms,mm,mn,pl,mv,ei,ms,ratebypass,mime,gir,clen,lmt,dur'
´´´´

**Comment by WildPenquin** [comment]
Hi,

I see this was closed as a duplicate, however I can not find the duplicate issue (it was not referred). Can you kindly point me to it so I can track this issue?

**Comment by yan12125** [comment]
FYI: #3721
