### ISSUE TITLE
NA started to appear in upload_date, release_date and timestamp for BBC World News

### ISSUE THREAD

**Issue by adamryczkowski** [rg3/youtube-dl#12778]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$/usr/local/bin/youtube-dl -c http://www.bbc.com/news/10462520 -o "%(upload_date)s %(timestamp)s %(title)s (%(id)s).mp4" --verbose

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-c', 'http://www.bbc.com/news/10462520', '-o', '%(upload_date)s %(timestamp)s %(title)s (%(id)s).mp4', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 3.5.2 - Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[bbc] 10462520: Downloading webpage
[bbc] p050ds2n: Downloading media selection XML
[bbc] p050ds2n: Downloading m3u8 information
[download] Downloading playlist: One-minute World News
[bbc] playlist One-minute World News: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Invoking downloader on 'http://cp401491-vh.akamaihd.net/i/mps_h264_hi/public/news_bulletins/news_heads_world/1279000/1279640_h264_1500k.mp4/index_0_av.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 7
[download] Destination: NA NA One-Minute World News (p050ds2n).mp4
[download] 100% of 11.71MiB in 05:14
[debug] avconv command line: avprobe -show_streams 'file:NA NA One-Minute World News (p050ds2n).mp4'
[ffmpeg] Fixing malformated aac bitstream in "NA NA One-Minute World News (p050ds2n).mp4"
[debug] ffmpeg command line: avconv -y -i 'file:NA NA One-Minute World News (p050ds2n).mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:NA NA One-Minute World News (p050ds2n).temp.mp4'
[download] Finished downloading playlist: One-minute World News
```

---

I used to have video names that included the `release_date` and the `timestamp` for the same invocation of the youtube-dl, like this: `20170405 1491377662 One-Minute World News (p04z39pp).mp4`

If that information is still available from the web scraper/parser, I would be grateful if you reintroduced it.

**Comment by vvasuki** [comment]
Having installed the latest version with `sudo pip install git+https://github.com/rg3/youtube-dl/@master -U` , so that 
```
youtube-dl --version
2017.09.24
```
I still face the problem on the vArtAvalI playlist: 
```
youtube-dl --extract-audio --audio-format mp3 -o "vArtAvalI-upl-%(release_date)s-%(title)s.%(ext)s" https://www.youtube.com/watch?v=mXWm_pm03_Y
[youtube] mXWm_pm03_Y: Downloading webpage
[youtube] mXWm_pm03_Y: Downloading video info webpage
[youtube] mXWm_pm03_Y: Extracting video information
[youtube] mXWm_pm03_Y: Downloading MPD manifest
[download] Resuming download at byte 1657925
[download] Destination: vArtAvalI-upl-NA-Vaartavali - Weekly Sanskrit Magazine _ 23_09_2017.m4a
[download]   7.6% of 23.43MiB at 59.89KiB/s ETA 06:10^C
```
Could you reopen and fix?

**Comment by dstftw** [comment]
Youtube videos have no release date.

**Comment by vvasuki** [comment]
Thank you for clarifying.

Separately: It might be useful to include `sudo pip install git+https://github.com/rg3/youtube-dl/@master -U` in the readme as well so that folks can easily get the bleeding edge version of the tool

**Comment by vvasuki** [comment]
Also, it might be a good idea to fix the man page to include the fact that Youtube videos have no release date. It currently reads:

`       · release_date (string): The date (YYYYMMDD) when the video was released`

**Comment by dstftw** [comment]
And if you bother to read it further it reads:
>Note that some of the sequences are not guaranteed to be present since they depend on the metadata obtained by a particular extractor. Such sequences will be replaced with `NA`.

**Comment by vvasuki** [comment]
I did read that - but did not deduce that this applies to YouTube. It feels that being more explicit would avoid futile attempts by users..

**Comment by dstftw** [comment]
There are about 1k extractors apart from YouTube. It's technically infeasible and pointless to try documenting every meta field availability for every extractor.

**Comment by vvasuki** [comment]
Ah - I didn't realize that. Would it be possible to make youtube-dl print all valid tags that can be extracted from a given website? (Or has it already been proposed and implemented?)

**Comment by dstftw** [comment]
There is no such thing as *tags that can be extracted from a particular website* as it depends on extraction of a particular URL and can't be guessed beforehand.

**Comment by kruug** [comment]
Upload_Date used to actually show the date the video was uploaded to YouTube.  This stopped working as well, being replaced by NA.

If that's something that YouTube changed, fine, but to just dismiss it as "not our problem because multiple websites" seems like your not testing the issue before coming up with a reason.
