### ISSUE TITLE
Bilibili download stops at 4 MiB

### ISSUE THREAD

**Issue by 41zu** [rg3/youtube-dl#12783]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

[dominik@antergos-dome-pc ~]$ youtube-dl -v https://www.bilibili.com/video/av9659846/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bilibili.com/video/av9659846/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 3.6.0 - Linux-4.10.10-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3, rtmpdump 2.4
[debug] Proxy map: {}
[BiliBili] 9659846: Downloading webpage
[BiliBili] 9659846: Downloading video info page
[debug] Invoking downloader on 'http://ws.acgvideo.com/9/8f/15964598-1-hd.mp4?wsTime=1492564331&platform=pc&wsSecret2=fc3d70d510b106902931ccbb89caf78f&oi=1528154482&rate=700'
[download] Destination: 【灯泡】妹抖龙高能乱入 The End-9659846.mp4
[download]  13.7% of 29.21MiB at  7.20MiB/s ETA 00:03^C
ERROR: Interrupted by user
[dominik@antergos-dome-pc ~]$

---

### Description of your *issue*, suggested solution and other information

I interrupted the download with Cntr + C, because it always stops at ~14%. I watched other issues in the bugtracker but they where older and closed. I downloaded already videos from this site a month ago or so and it worked. I saw that bilibili.py was last edited 3 months ago, so I through, that bilibili changed somethink at their site again. 
If this submission is not helpful you can delete it.

**Comment by yan12125** [comment]
Maybe unstable network?
```
$ youtube-dl -v "https://www.bilibili.com/video/av9659846/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bilibili.com/video/av9659846/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Git HEAD: 06d0ad9a4
[debug] Python version 3.6.1 - Linux-4.10.11-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3
[debug] Proxy map: {}
[BiliBili] 9659846: Downloading webpage
[BiliBili] 9659846: Downloading video info page
[debug] Invoking downloader on 'http://ws.acgvideo.com/9/8f/15964598-1-hd.mp4?wsTime=1492600727&platform=pc&wsSecret2=2b8b7021463911db48000dd81285a1d5&oi=2356157543&rate=800'
[download] Destination: 【灯泡】妹抖龙高能乱入 The End-9659846.mp4
[download] 100% of 29.21MiB in 00:11
```

**Comment by 41zu** [comment]
No, the network is really stable. You can always see that I am downloading the video with over 7 MiB/s. I tried this time a random video with a total of 6.76 MiB and he stops at 59.1%, that makes 4 MiB. With the previous video he stopped at 13.7% at a total size of 29.2 MiB, that makes 4 MiB again. 
I want to add, I tried to download this random video 3 times. The first time he stopped at 59.1%. The second time he downloaded the whole video and the third time he stopped at 59.1% again. 
The normal Bilibili website is working fine. 
Personaly I think, the problem is that if you start watching the video he downloads at the beginning 4 MiB and if you proceed with watching, the player proceeds the download if needed. Just like Youtube does with their webplayer. 

[dominik@antergos-dome-pc ~]$ youtube-dl -v https://www.bilibili.com/video/av9915530/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bilibili.com/video/av9915530/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 3.6.0 - Linux-4.10.10-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3, rtmpdump 2.4
[debug] Proxy map: {}
[BiliBili] 9915530: Downloading webpage
[BiliBili] 9915530: Downloading video info page
[debug] Invoking downloader on 'http://ws.acgvideo.com/f/e0/16398172-1-hd.mp4?wsTime=1492614955&platform=pc&wsSecret2=0188124dabed82732757586a3458ce29&oi=1528154482&rate=800'
[download] Destination: 【东方手绘】妖梦酱跳纱雾之舞【埃罗芒阿老师 ED再现】-9915530.mp4
[download]  59.1% of 6.76MiB at  7.12MiB/s ETA 00:00^C
ERROR: Interrupted by user
[dominik@antergos-dome-pc ~]$

**Comment by eqmo** [comment]
I have the same issue, if I retry again the same URL the download continues for about ~3Mb more, then stalls again. Eventually the download ends correctly.

**Comment by yan12125** [comment]
I remember it - the patch at #11476 can solve it. Please move to #11476 or #6923 for further discussions.
