### ISSUE TITLE
Downloaded video has rotated wrong. (Periscope)

### ISSUE THREAD

**Issue by Erilbeth** [rg3/youtube-dl#12799]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

$ youtube-dl -v https://www.periscope.tv/22dakika/1ZkKzlXkOMoJv
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.periscope.tv/22dakika/1ZkKzlXkOMoJv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.5 - Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg N-83902-ge90ad88, ffprobe N-83902-ge90ad88
[debug] Proxy map: {}
[periscope] 1ZkKzlXkOMoJv: Downloading JSON metadata
[periscope] 1ZkKzlXkOMoJv: Downloading JSON metadata
[debug] Invoking downloader on u'https://prod-video-us-west-2.periscope.tv/NzTclw-9UB2h7yef2Bi7W4YnQjqNZNmjQq9Ywaz023wmqxNlup9qItkT3bo8HZLxsk2Wdg2S9niFOWoUQCu_PA==/replay/us-west-2/periscope-replay-direct-live/playlist.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 142
[download] Destination: 22dakika - Canlı posketimiz başladı...-1ZkKzlXkOMoJv.mp4
[download] 100% of 33.65MiB in 01:32
[debug] ffmpeg command line: ffprobe -show_streams 'file:22dakika - Canlı posketimiz başladı...-1ZkKzlXkOMoJv.mp4'
[ffmpeg] Fixing malformated aac bitstream in "22dakika - Canlı posketimiz başladı...-1ZkKzlXkOMoJv.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:22dakika - Canlı posketimiz başladı...-1ZkKzlXkOMoJv.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:22dakika - Canlı posketimiz başladı...-1ZkKzlXkOMoJv.temp.mp4'
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.pscp.tv/22dakika/1ZkKzlXkOMoJv
- Single video: https://www.periscope.tv/22dakika/1ZkKzlXkOMoJv

---

### Description of your *issue*, suggested solution and other information

I've downloaded a video from periscope. When i played the video(with vlc) it has shown rotated 90 degrees.
This is the example screenshot:
![screenshot from 2017-04-20 11-47-26](https://cloud.githubusercontent.com/assets/17575794/25223717/d66d7460-25c4-11e7-9cd7-0dd763083c2d.png)

This is the ffprobe of downloaded video:
$ ffprobe 22dakika\ -\ Canlı\ posketimiz\ başladı...-1ZkKzlXkOMoJv.mp4 
ffprobe version N-83902-ge90ad88 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-11)
  configuration: --enable-libvpx --enable-libvorbis
  libavutil      55. 48.100 / 55. 48.100
  libavcodec     57. 83.100 / 57. 83.100
  libavformat    57. 66.104 / 57. 66.104
  libavdevice    57.  3.100 / 57.  3.100
  libavfilter     6. 76.100 /  6. 76.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '22dakika - Canlı posketimiz başladı...-1ZkKzlXkOMoJv.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.66.104
  Duration: 00:08:30.51, start: 0.000000, bitrate: 508 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 320x568, 435 kb/s, 29.90 fps, 29.97 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 64 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

This is output of list-formats command:
$ youtube-dl --list-formats https://www.periscope.tv/22dakika/1ZkKzlXkOMoJv
[periscope] 1ZkKzlXkOMoJv: Downloading JSON metadata
[periscope] 1ZkKzlXkOMoJv: Downloading JSON metadata
[info] Available formats for 1ZkKzlXkOMoJv:
format code  extension  resolution note
0            mp4        unknown

**Comment by dstftw** [comment]
The original video has this rotation.
