### ISSUE TITLE
Crunchyroll

### ISSUE THREAD

**Issue by DaviSojogos** [rg3/youtube-dl#12794]
youtube-dl.exe --recode-video "mkv" --audio-quality "9" --audio-format "best" --embed-subs --all-subs --add-metadata --embed-thumbnail -v http://www.crun
chyroll.com/akashic-records-of-bastard-magical-instructor/episode-2-just-the-slightest-bit-of-motivation-733625
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--recode-video', 'mkv', '--audio-quality', '9', '--audio-format', 'best', '--embed-subs', '--all-subs', '--add-metadata', '--embed-thumbnail', '-v', 'http://www.crunchyroll.com/akashic-records-of-bastard-magical-instructor/episode-2-just-the-slightest-bit-of-motivation-733625']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.04.17
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[Crunchyroll] Downloading login page
ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\build\youtube_dl\extractor\common.py", line 498, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\build\youtube_dl\YoutubeDL.py", line 2106, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

###########################

root@Davi-PC:/mnt/e/Entretendimento/Animes/Crunchyroll# python Crun.2.6.3.py
akashic-records-of-bastard-magical-instructor
[Crunchyroll] Downloading login page
ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by HTTPError()); please repor
t this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be s
ure to call youtube-dl with the --verbose flag and include its complete output.
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--recode-video', u'mkv', u'--audio-quality', u'9', u
'--audio-format', u'best', u'--embed-subs', u'--all-subs', u'--add-metadata', u'--embed-thumbnail', u'-v', u'http://www.
crunchyroll.com/akashic-records-of-bastard-magical-instructor/episode-1-the-unmotivated-bastard-733623']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.6 - Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}

youtube-dl -u "##########" -p "#####################" --recode-video "mkv" --audio-quality "9" --audio-format "best" --embed-subs --all-subs --add-metadata --embed-thumbnail -v http://www.crunchyroll.com/akashic-records-of-bastard-magical-instructor/episode-2-just-the-slightest-bit-of-motivation-733625

**Comment by Starsam80** [comment]
This is normal, Crunchyroll does this sometimes. Try again in a hour or so.
