### ISSUE TITLE
Unable to access my own private youtube videos with login

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#12796]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
keybounceMBP:hack michael$ youtube-dl https://www.youtube.com/playlist?list=PLFYVR-tqmunU78gZwywcSenBhzMX0cJqz
 --username keybounce
Type account password and press [Return]: 
[youtube:playlist] Downloading login page
[youtube:playlist] Logging in
[youtube:playlist] PLFYVR-tqmunU78gZwywcSenBhzMX0cJqz: Downloading webpage
ERROR: This playlist is private, use --username or --netrc to access it.
keybounceMBP:hack michael$ youtube-dl -v https://www.youtube.com/playlist?list=PLFYVR-tqmunU78gZwywcSenBhzMX0c
Jqz --username keybounce
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--ap-mso', u'Dish', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'--write-sub', u'--write-auto-sub', u'--sub-lang', u'en,enUS,en-us', u'--sub-format', u'ass/srt/best', u'--convert-subs', u'ass', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/playlist?list=PLFYVR-tqmunU78gZwywcSenBhzMX0cJqz', u'--username', u'PRIVATE']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Logging in
[youtube:playlist] PLFYVR-tqmunU78gZwywcSenBhzMX0cJqz: Downloading webpage
ERROR: This playlist is private, use --username or --netrc to access it.
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2102, in _real_extract
    has_videos, playlist = self._extract_playlist(playlist_id)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2045, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist is private, use --username or --netrc to access it.

keybounceMBP:hack michael$ 

```

---

I am attempting to download a playlist of mine. The videos are private, as is the playlist.

I know that I logged on well enough for YouTube to send me an email saying, Your Google Account keybounce@gmail.com was just used to sign in from Firefox on Linux.

It's a 10+ hour playlist, from a twitch stream that was uploaded as 15 minute videos. My plan was to look through them for junkable garbage / keepable good stuff, and trim appropriately.

Version is latest head from git -- 8abc7dca39236462c0652932df23862acda92d51

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by keybounce** [comment]
Oddly, if I give the wrong password, I get an explicit invalid password error. With the right password, I get this error.

Here's dump pages.
https://gist.github.com/keybounce/bfcf815078747aac7ab0aa27c1caf367

**Comment by dstftw** [comment]
![image](https://cloud.githubusercontent.com/assets/1908898/25311432/f1e97ec4-282a-11e7-99c6-d7b4020dc94d.png)
Login with clean browser session and do what it asks you to do.

**Comment by keybounce** [comment]
... so Google doesn't like me. I log in, then youtube-dl "works" (see below) for a while, and then dies; I have to log in on google.com again.

Now, it gets a bit farther, and dies with a different error:

NB: Youtube-dl was just updated to git head 3019cb0c9976481cf2afaf0a2005d90040204fa0

keybounceMBP:hack michael$ youtube-dl -v https://www.youtube.com/playlist?list=PLFYVR-tqmunU78gZwywcSenBhzMX0cJqz --username keybounce
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s-%(timestamp)6i.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--ap-mso', u'Dish', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'--write-sub', u'--write-auto-sub', u'--sub-lang', u'en,enUS,en-us', u'--sub-format', u'ass/srt/best', u'--convert-subs', u'ass', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/playlist?list=PLFYVR-tqmunU78gZwywcSenBhzMX0cJqz', u'--username', u'PRIVATE']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Logging in
[youtube:playlist] PLFYVR-tqmunU78gZwywcSenBhzMX0cJqz: Downloading webpage
[download] Downloading playlist: Hack 'n' Slash "Lets play" -- Viewer suggestions
[youtube:playlist] playlist Hack 'n' Slash "Lets play" -- Viewer suggestions: Downloading 41 videos
[download] Downloading video 1 of 41
[youtube] Downloading login page
[youtube] Logging in
[youtube] QeI2bmYm4xw: Downloading webpage
[youtube] QeI2bmYm4xw: Downloading video info webpage
[youtube] QeI2bmYm4xw: Extracting video information
WARNING: unable to download video subtitles: Unable to download XML: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] QeI2bmYm4xw: Looking for automatic captions
[youtube] QeI2bmYm4xw: Downloading MPD manifest
[youtube] QeI2bmYm4xw: Downloading MPD manifest
[youtube] QeI2bmYm4xw: Marking watched
WARNING: enUS subtitles not available for QeI2bmYm4xw
WARNING: en-us subtitles not available for QeI2bmYm4xw
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/michael/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/Users/michael/bin/youtube-dl/youtube_dl/__init__.py", line 464, in main
  File "/Users/michael/bin/youtube-dl/youtube_dl/__init__.py", line 454, in _real_main
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1896, in download
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 771, in extract_info
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 962, in process_ie_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 832, in process_ie_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 771, in extract_info
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 825, in process_ie_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1539, in process_video_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1617, in process_info
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 675, in prepare_filename
TypeError: %d format: a number is required, not unicode
keybounceMBP:hack michael$ 
keybounceMBP:hack michael$

**Comment by keybounce** [comment]
Thank you!
