### ISSUE TITLE
How to download multi-part streams from twitch?

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#12798]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

So what is the best way to download a bunch of videos from a twitch stream?

Each time the stream is stopped and restarted, there's a new video. But the name of the stream does not change, the videos have the same name as seen by youtube-dl, and instead of getting all of them, each one overwrites the previous and I wind up with just one.

What's a good way to have numbered downloads?

Example: https://www.twitch.tv/keybounce/videos/all

**Comment by dstftw** [comment]
[Output template](https://github.com/rg3/youtube-dl#output-template).

**Comment by keybounce** [comment]
1. Is there a way to ask "What meta-data is available for this video"? I'm thinking of all the existing "--get-" options. Specifically, I'm interested in working with the episode/series information, but that's (apparently, if I read the manual correctly) dependent on that meta-data being available. I'd want to query some of the things I download regularly, and see what info is available, to figure out what to use.

2. Is there a way to make the output format source-site dependent, or "if this meta-data is present" dependent / any form of conditional? Right now, I can put something into ~/.config/youtube-dl/config, and it works for everything. I use this for formats. But for output filename template, most of the time there is already season and episode info in titles (oddly, the three big networks and BBC are the exceptions), and playlist index number will change every time things are added to the top of the playlist / will vary for the same video for some playlists, but be consistent for other playlists.

Interestingly, I had in that config file this:
-o %(title)s.%(ext)s
which I only realized after seeing that the default is
%(title)s-%(id)s.%(ext)s
