### ISSUE TITLE
Playing webm audio file does not show time

### ISSUE THREAD

**Issue by rieje** [rg3/youtube-dl#12806]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
I downloaded an audio file with a .webm extension. When I play it with `mpv <file>.webm`, it plays the audio without a GUI (which is fine, not needed), and the input controls work. However, it doesn't show [current timestamp]:[total audio length], which is crucial to have some sort of context of where I am on when listening to content (I would like to know how much time until the content is over, etc.).

**Comment by dstftw** [comment]
How is this related to youtube-dl? Playback related questions should be addressed to player you're using.
