### ISSUE TITLE
[Youtube & VideoPress] Unable to download all the videos on a web page that contains both Youtube and VideoPress videos

### ISSUE THREAD

**Issue by jnbdz** [rg3/youtube-dl#12805]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://tifrib.com/said-rageah/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://tifrib.com/said-rageah/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.12 - Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
[generic] said-rageah: Requesting header
WARNING: Falling back on generic information extractor.
[generic] said-rageah: Downloading webpage
[generic] said-rageah: Extracting information
[download] Downloading playlist: Said Rageah
[generic] playlist Said Rageah: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] vNpMVo7hXXk: Downloading webpage
[youtube] vNpMVo7hXXk: Downloading video info webpage
[youtube] vNpMVo7hXXk: Extracting video information
[youtube] vNpMVo7hXXk: Downloading MPD manifest
[debug] Invoking downloader on u'https://r2---sn-ab5l6nzy.googlevideo.com/videoplayback?expire=1492740711&clen=23205853&initcwndbps=6407500&ipbits=0&mime=video%2Fwebm&dur=0.000&source=youtube&ratebypass=yes&lmt=1365432378682397&key=yt6&pl=19&id=o-AE-R7HVFYgEu0duadpZ4IJoWlWRvjC8JUZbBppJLmfst&requiressl=yes&ip=107.170.45.127&signature=6E7236329231DF68CB47158803705ABA63FA3B4C.4ED21F8BA43C1C4E8F0BC5FBBDCCA9E685DF5399&gir=yes&mv=m&mt=1492719031&itag=43&ms=au&ei=Bxb5WO3tEOaZ8gSE6pjgDQ&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=WAut0lqh1TE&mn=sn-ab5l6nzy&mm=31'
[download] Destination: Said Rageah - Abu Huraira Centre-vNpMVo7hXXk.webm
[download] 100% of 22.13MiB in 00:00
[download] Finished downloading playlist: Said Rageah
...
<end of log>
```

---

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

The videos found on this web page are from Youtube and VideoPress. Both are already supported by Youtube-dl. The issue is that only one video is being downloaded when I think all of them should be downloaded.

Thank you for your help.

**Comment by jnbdz** [comment]
Where is the first issue ticket for this one?

**Comment by yan12125** [comment]
FYI: #5587
