### ISSUE TITLE
how to get the "comment_count" in the meta ?

### ISSUE THREAD

**Issue by liudatutu** [rg3/youtube-dl#12808]
this is my code:

import youtube_dl
ydl_opts = {'forcetitle':'True','ignoreerrors':True,
            'encoding':'utf-8','outtmpl':u'E:/Movie/%(title)s.%(ext)s'}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    meta = ydl.extract_info(
        'https://www.youtube.com/watch?v=RGNTdUHN64Q', download=False)
print type(meta)
#print meta
print 'comment_count:',meta.get('comment_count','None')

>>>
>>>
[youtube] RGNTdUHN64Q: Downloading webpage
[youtube] RGNTdUHN64Q: Downloading video info webpage
[youtube] RGNTdUHN64Q: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] RGNTdUHN64Q: Downloading MPD manifest
WARNING: "id" field is not a string - forcing string conversion
<type 'dict'>
comment_count: None

Process finished with exit code 0

**Comment by dstftw** [comment]
`comment_count` is not extracted for YouTube.
