### ISSUE TITLE
Can't download videos from 91porn

### ISSUE THREAD

**Issue by sisuclimber** [rg3/youtube-dl#12814]
I run the download command line one my vps. It shows contents as follows: 
[root@localhost youtube]# youtube-dl --verbose http://91porn.com/view_video.php?viewkey=a4e5cecaa15e0e61b8a3
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://91porn.com/view_video.php?viewkey=a4e5cecaa15e0e61b8a3']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.6.6 - Linux-2.6.32-042stab116.1-i686-with-centos-6.9-Final
[debug] exe versions: none
[debug] Proxy map: {}
[91porn] a4e5cecaa15e0e61b8a3: Downloading webpage
ERROR: Unable to extract file id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/porn91.py", line 48, in _real_extract
    r'so.addVariable\(\'file\',\'(\d+)\'', webpage, 'file id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 778, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract file id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Please help me to solve this problem. Thanks.

**Comment by yan12125** [comment]
Thanks for the report. This will be fixed in the next version.
