### ISSUE TITLE
Why does `file youtube-dl` output "youtube-dl: data"?

### ISSUE THREAD

**Issue by psycho23** [rg3/youtube-dl#12810]
I'm 70% sure I tried the latest `file' command, and yet this still happens:

`cd ~/Downloads #good`
`wget https://yt-dl.org/downloads/latest/youtube-dl #good`
`file youtube-dl #bad`
youtube-dl: data

What is this file? How is it executable? This is wrong. If `file' can't detect the filetype, how can the OS?

**Comment by dstftw** [comment]
It's a zipped python app.

**Comment by psycho23** [comment]
And yet there is no indication otherwise by `file'.
Is there a `file' magic file that can at least say something like: 
youtube-dl: Stand-alone python zip executable

**Comment by dstftw** [comment]
Wrong:
>$ file youtube-dl
>youtube-dl: a /usr/bin/env python script executable (binary data)

**Comment by psycho23** [comment]
What? That's impossible!

psycho23@shiva ~ $ file --version
file-5.14
magic file from /etc/magic:/usr/share/misc/magic

psycho23@shiva ~ $ cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Ubuntu 14.04.3 LTS"

**Comment by dstftw** [comment]
5.14 is 4 years old.
