### ISSUE TITLE
How to install manpage

### ISSUE THREAD

**Issue by ahangarha** [rg3/youtube-dl#12817]
Hi

I am currently using Ubuntu 16.04 and latest version of youtube-dl. I used to have youtube-dl which was installed from Ubuntu repository. Since it was outdated, I went through removing it and then, I installed it manually using pip.

Since then, I have no manpage for youtube-dl.

Is there any way to do install it manually? Have I done something wrong?

**Comment by yan12125** [comment]
If you follow the installation guide at https://github.com/rg3/youtube-dl#installation

> sudo -H pip install --upgrade youtube-dl

The man page will be installed to /usr/share/man/man1/youtube-dl.1. That's the default path for system man pages, so you can just run ```man youtube-dl``` and read it. Could you check whether the file is there or not?

**Comment by ahangarha** [comment]
Actually I used to update it by running
`sudo youtube-dl --update`
But running 
`sudo -H pip install --upgrade youtube-dl`
solved the problem

If using built-in `--update` option is not working, then isn't it better to remove or disable it?

Thank you.

**Comment by yan12125** [comment]
FYI: ```--update``` and ```pip install``` target different usages. ```--update``` is for single program mode (no man pages, shell completion script, etc.), which is absolutely useful on Windows, and ```pip``` provides a complete package.

By the way, it's better to remove the youtube-dl binary if you decided to go the pip way.
