### ISSUE TITLE
When will the new version of the Youtube-dl be released ?

### ISSUE THREAD

**Issue by best-job** [rg3/youtube-dl#12821]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---
When will the new version of the Youtube-dl be released after solving the new issues?
---

**Comment by dstftw** [comment]
No ETA.
