### ISSUE TITLE
Downloading private playlist with --username is not possible

### ISSUE THREAD

**Issue by godspeedyou** [rg3/youtube-dl#12820]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
 youtube-dl-single PLFxMph_JHJZwgNKi2tYLaP2LL7O9rHmdZ --username user@gmail.com -v --dump-pages > debug.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-iwx', u'--audio-format', u'mp3', u'-f', u'bestaudio', u'PLFxMph_JHJZwgNKi2tYLaP2LL7O9rHmdZ', u'--username', u'PRIVATE', u'-v', u'--dump-pages']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.12 - Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: This playlist is private, use --username or --netrc to access it.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 2102, in _real_extract
    has_videos, playlist = self._extract_playlist(playlist_id)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 2045, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist is private, use --username or --netrc to access it.
[debug.txt](https://github.com/rg3/youtube-dl/files/949576/debug.txt)
```
I used the command `youtube-dl-single PLFxMph_JHJZwgNKi2tYLaP2LL7O9rHmdZ --username user@gmail.com -v --dump-pages` to download a private youtube list. I get asked for my password, but the above error message appears. Yes, I used the correct username (not user@gmail.com) and the correct password.

I also tried the --netrc command, which is not working either. The .netrc file does not seem to support my password. Maybe this is the root cause of this issue as well. My password contains spaces, slashes and quotes. As the syntax highlighting of my shell editor suggests, this seems to be breaking my password for the netrc file.

If I set the private playlist to unlisted, I can download the playlist via youtube-dl.

**Comment by godspeedyou** [comment]
[debug.txt](https://github.com/rg3/youtube-dl/files/949580/debug.txt)

**Comment by dstftw** [comment]
Duplicate of #12927.
