### ISSUE TITLE
abcnews.go.com embedded urls

### ISSUE THREAD

**Issue by hildred** [rg3/youtube-dl#12831]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$  youtube-dl -v 'http://abcnews.go.com/video/embed?id=46979033'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://abcnews.go.com/video/embed?id=46979033']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.13 - Linux-4.9.0-1-rt-686-pae-i686-with-debian-9.0
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] embed?id=46979033: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed?id=46979033: Downloading webpage
[generic] embed?id=46979033: Extracting information
ERROR: Unsupported URL: http://abcnews.go.com/video/embed?id=46979033
Traceback (most recent call last):
  File "/home/ben/.bin/youtube-dl/youtube_dl/extractor/generic.py", line 1898, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/ben/.bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/ben/.bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 30, column 3
Traceback (most recent call last):
  File "/home/ben/.bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/home/ben/.bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/home/ben/.bin/youtube-dl/youtube_dl/extractor/generic.py", line 2765, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://abcnews.go.com/video/embed?id=46979033
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://abcnews.go.com/video/embed?id=46979033

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

This is not  #4661 (Add support for abc.go.com) because abc.go.com and abcnews.go.com use different backends.

This could be #3992 but embeded urls appear to be significantly different and apparently basic support is working.

**Comment by yan12125** [comment]
Thanks to dstftw (164fcbfeb75787cfeb1f0a84188ba4c11ac4a009), this is already fixed since 2017.05.29.
