### ISSUE TITLE
Can't use --dump-single-json on a playlist that contains a private video

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#12835]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--dump-single-json', u'https://www.youtube.com/user/bunnyhopshow/playlists', u'-v', u'-f', u'best']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.7
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: NiB-cdIZRmY: YouTube said: This video is private.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1388, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: NiB-cdIZRmY: YouTube said: This video is private.
```

---

### Description of your *issue*, suggested solution and other information

When a playlist contains a private video, `--dump-single-json` will fail instead of just ignoring the private video.

**Comment by dstftw** [comment]
This is expected.

**Comment by Rudloff** [comment]
Excuse me but what's the point? What if I want to get info about all the other videos?
It's quite frustrating to have youtube-dl run for several minutes on a large playlist then fail without returning anything because there is one private video in the middle.

**Comment by dstftw** [comment]
Bother to use search it's answered million of times.
