### ISSUE TITLE
Arte.tv no longer works

### ISSUE THREAD

**Issue by mariussoutier** [rg3/youtube-dl#12837]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

Arte.tv used to work but does no longer after they redesigned the website.

Example:

```
$ youtube-dl -v "http://www.arte.tv/de/videos/048696-000-A/der-kluge-bauch-unser-zweites-gehirn"

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.arte.tv/de/videos/048696-000-A/der-kluge-bauch-unser-zweites-gehirn']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.13 - Darwin-16.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 12, avprobe 12, ffmpeg 3.3, ffprobe 3.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] der-kluge-bauch-unser-zweites-gehirn: Requesting header
WARNING: Falling back on generic information extractor.
[generic] der-kluge-bauch-unser-zweites-gehirn: Downloading webpage
[generic] der-kluge-bauch-unser-zweites-gehirn: Extracting information
ERROR: Unsupported URL: http://www.arte.tv/de/videos/048696-000-A/der-kluge-bauch-unser-zweites-gehirn
```

**Comment by JensC** [comment]
Yes I can confirm this ... used version 2017.04.17 on Mac OSX 10.12.4 (16E195). Thanks a lot for the great tool!

**Comment by passionaqua** [comment]
I also have the same issue with this version of youtube-dl.
The website just have change the URLs of their webpages I think.
