### ISSUE TITLE
Udemy Video Not Working

### ISSUE THREAD

**Issue by bubundas17** [rg3/youtube-dl#12838]
I am getting a issue while downloading a video fron Udemy.com. Please Fix The Issue.
Video Link: https://www.udemy.com/learn-nodejs-by-building-an-employee-to-business-rating-app
I am using Ubuntu VPS Server.

[udemy:course] Downloading login popup
[udemy:course] Logging in as **********7399@gmail.com
[udemy:course] learn-nodejs-by-building-an-employee-to-business-rating-app: Downloading webpage
[udemy:course] 1107524: Downloading course curriculum
[download] Downloading playlist: The Complete NodeJS Course: Build a Full Business Rating App
[udemy:course] playlist The Complete NodeJS Course: Build a Full Business Rating App: Collected 61 video ids (downloading 61 of them)
[download] Downloading video 1 of 61
[udemy] Downloading login popup
[udemy] 6554280: Downloading webpage
[udemy] 6554280: Downloading lecture JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
