### ISSUE TITLE
Prefer video type

### ISSUE THREAD

**Issue by luutran2002** [rg3/youtube-dl#12833]
Hello,

For example, there are youtube videos with 1080 resolution for both MP4 and MKV (or WEBM) types. when I download the video using youtube-dl, I would like to be able to specify which type to download.

So the requirements would be...

for this setting
-f bestvideo+bestaudio

if the best video has multiple types then allow user to pick a type.
if the type user had picked doesn't exist then use the default type.

If this feature doesn't exist, can you please add it and let me know when you're done. If it already existed then please teach me how to do this.

Thanks.

**Comment by dstftw** [comment]
Bother to read [FAQ](https://github.com/rg3/youtube-dl#format-selection).

**Comment by luutran2002** [comment]
I did and I don't see anything allow me to do what I have stated. do you mind point me to the right section of the document?

**Comment by luutran2002** [comment]
if you're referring to the FORMAT section where you separate the format choices with / then I did try that and it doesn't work like they way I wanted.

for example there is a youtube video which has mp4 at 480 and webm at 1080.

I used

 -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/bestvideo+bestaudio"

it won't download the 1080, it keeps downloadin the mp4 which is 480

there is another youtube video with mp4 at 1080 and mkv at 1080. using the same switch, it keeps downloading the mkv file instead of mp4 like the above example. so it behave differently...

that's the problem.

**Comment by luutran2002** [comment]
I want something like

-f bestvideo+bestaudio+mp4

find the max resolution, if multiple types exit then choose mp4, if mp4 doesn't exist then pick one (like the way it work now)

**Comment by luutran2002** [comment]
hey why did you close it?

**Comment by luutran2002** [comment]
not very nice
