### ISSUE TITLE
Download stops at 5,10,15,etc. percent

### ISSUE THREAD

**Issue by TammysHead** [rg3/youtube-dl#12840]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
**[debug] Command-line args: ['-v', 'http://www.crunchyroll.com/the-idolmster-cind
erella-girls-theater/episode-4-ill-keep-asking-until-its-all-gone-734005', '--co
okies', 'cookies.txt', '--no-check-certificate', '-f', 'best[height=720]']**
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.26
[debug] Python version 3.4.4 - Windows-2012Server-6.2.9200-SP0
[debug] exe versions: ffmpeg N-84814-gad7aff0, ffprobe N-84814-gad7aff0
[debug] Proxy map: {}
[Crunchyroll] 734005: Downloading webpage
[Crunchyroll] 734005: Downloading media info for 360p
[Crunchyroll] 734005: Downloading m3u8 information
[Crunchyroll] 734005: Downloading media info for 480p
[Crunchyroll] 734005: Downloading m3u8 information
[Crunchyroll] 734005: Downloading media info for 720p
[Crunchyroll] 734005: Downloading m3u8 information
[Crunchyroll] 734005: Downloading media info for 1080p
[Crunchyroll] 734005: Downloading m3u8 information
[Crunchyroll] 734005: Downloading media info
[debug] Invoking downloader on 'https://v.vrv.co/evs/eb0ced2f0c878b968e02fc4f3af
5900f/assets/59c90fbb82c265b931f0612f0a3735c2_3211935.mp4/index-v1-a1.m3u8?Polic
y=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvZWIwY2VkMmYwYz
g3OGI5NjhlMDJmYzRmM2FmNTkwMGYvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOk
Vwb2NoVGltZSI6MTQ5MzMxMzE0N319fV19&Signature=dFMb5tKT5ROcLXpSZKx~M5RZrkvh8bqOxeW
vE5UdSH~k1ZQnrEJmwO0VCiqw~0znQly6Nfzk28AuDEXzm~vKLWo~W0r3wTcCk~82dZG~8q~hvEoMKmg
3Rdkn3lfRfjniFWaNU~B0NIDxyjafp4NjD5R~KV6HIXHBs0Wnr1stYqP24JaeOHZXicD81fPdJORi6sF
yD5-EtxroEjWQOkWrm50XHQakArgXmFH-4LfhYWVTKYRSwEnBBMVEooZoHQeTQHHwN1XImcDTRJ9RKie
pRQmf3rlo-gzqLqbsGqqn0Y~pNQnmTjNucYLjUQBeh~VOPyGRutkAixJkWR0Xu22goQ__&Key-Pair-I
d=APKAJKQQ2INNHTYFB44A'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 20
[download] Destination: THE [email protected]_ _ CINDERELLA GIRLS Theater Folge
4 - Ich frage weiter, bis alle weg sind _ Wie sweet es ist _ Ich überlasse dir d
en Text-734005.mp4

### my problem

I download videos from crunchyroll as always and on my Remote PC it doesnt work anymore. It works fine on my pc, but not on the Remote Desktop. It just stops at 5,10,15 etc. percent. I updated it, but it didnt help.

**Comment by dstftw** [comment]
Provide complete log where it clearly seen as it "stops".

**Comment by TammysHead** [comment]
It never stops. After max 35% It puts the FRAG Parts into 1 PART File and stops. So i have a 1kb .YTDL File and a not finished .PART File

**Comment by dstftw** [comment]
Decide already whether it stops or not.
>Download stops at 5,10,15,etc. percent

**Comment by TammysHead** [comment]
It stops sometimes at 5%, sometimes at 10% to maximal 30% and then tries to fix it into a stream, i think.

**Comment by TammysHead** [comment]
I run this on a vServer. On my computer it works fine. It always worked on my vServer, but now it has this bug.

**Comment by dstftw** [comment]
It's pretty obvious that's a not a bug if it works everywhere apart from some single machine. In any case you must provide the log that clearly demonstrates an issue you still did not provide.
