### ISSUE TITLE
Subtitles in UTF8?

### ISSUE THREAD

**Issue by TammysHead** [rg3/youtube-dl#12849]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
Microsoft Windows [Version 6.2.9200]
(c) 2012 Microsoft Corporation. All rights reserved.

Microsoft Windows [Version 6.2.9200]
(c) 2012 Microsoft Corporation. All rights reserved.

youtube-dl.exe -v --cookies cookies.txt http://www.crunchyroll.com/room-mate/episode-3-nishina-aoi-relaxes-734461 -f "best[height=720]" --all-subs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies.txt', 'http://www.crunch
yroll.com/room-mate/episode-3-nishina-aoi-relaxes-734461', '-f', 'best[height=72
0]', '--all-subs']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.17
[debug] Python version 3.4.4 - Windows-2012Server-6.2.9200-SP0
[debug] exe versions: ffmpeg N-84814-gad7aff0, ffprobe N-84814-gad7aff0
[debug] Proxy map: {}
[Crunchyroll] 734461: Downloading webpage
[Crunchyroll] 734461: Downloading media info for 360p
[Crunchyroll] 734461: Downloading m3u8 information
[Crunchyroll] 734461: Downloading media info for 480p
[Crunchyroll] 734461: Downloading m3u8 information
[Crunchyroll] 734461: Downloading media info for 720p
[Crunchyroll] 734461: Downloading m3u8 information
[Crunchyroll] 734461: Downloading media info for 1080p
[Crunchyroll] 734461: Downloading m3u8 information
[Crunchyroll] 734461: Downloading media info
[Crunchyroll] 734461: Downloading subtitles for English (US)
[Crunchyroll] 734461: Downloading subtitles for Español
[Crunchyroll] 734461: Downloading subtitles for Español (España)
[Crunchyroll] 734461: Downloading subtitles for Français (France)
[Crunchyroll] 734461: Downloading subtitles for Português (Brasil)
[Crunchyroll] 734461: Downloading subtitles for Italiano
[Crunchyroll] 734461: Downloading subtitles for Deutsch
[info] Writing video subtitles to: Room Mate Folge 3 - Nishina Aoi entspannt sic
h-734461.frFR.ass
[info] Writing video subtitles to: Room Mate Folge 3 - Nishina Aoi entspannt sic
h-734461.deDE.ass
[info] Writing video subtitles to: Room Mate Folge 3 - Nishina Aoi entspannt sic
h-734461.enUS.ass
[info] Writing video subtitles to: Room Mate Folge 3 - Nishina Aoi entspannt sic
h-734461.esLA.ass
[info] Writing video subtitles to: Room Mate Folge 3 - Nishina Aoi entspannt sic
h-734461.ptBR.ass
[info] Writing video subtitles to: Room Mate Folge 3 - Nishina Aoi entspannt sic
h-734461.esES.ass
[info] Writing video subtitles to: Room Mate Folge 3 - Nishina Aoi entspannt sic
h-734461.itIT.ass
[debug] Invoking downloader on 'https://v.vrv.co/evs/fac3eb57a926c4eeb9b0b8bf038
f39ed/assets/0d19d168c92f588549913423fbfc0aa6_3211551.mp4/index-v1-a1.m3u8?Polic
y=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvZmFjM2ViNTdhOT
I2YzRlZWI5YjBiOGJmMDM4ZjM5ZWQvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOk
Vwb2NoVGltZSI6MTQ5MzQwNDk2NX19fV19&Signature=AzLMyrz~nMk-tmwFU3SpA~oaD5AcquyPsLk
rOpRDpHzbVX85yfEYWHWcOxBKW6w38u6tZWOzHUy3IuoFpzENxeVZN-rL2As3JmK1YwzRVT7sU2oghux
adnYuh9h8eH04xzRYadHa8FapTNm-DUBhsAOt2hTaVZmZXGR~jEgbejxxjoaLtomnC1f~hjezCaJOSNR
dRwwLvipRntjW6RHKps~ReihZmWlKO3t8hf83sHjGRNSzqjUuYsUX61PnWT3fqSlvo54RcN8m2y9xUJ8
eyR2~lvYfLIs9vE~Q0hrxT-kaGGS0S4~Qb03JSrgwajf8kr5pCPrenqt1wUEp89F1gA__&Key-Pair-I
d=APKAJKQQ2INNHTYFB44A'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 25
[download] Destination: Room Mate Folge 3 - Nishina Aoi entspannt sich-734461.mp
4
[download] 100% of 68.47MiB in 00:05
[debug] ffmpeg command line: ffprobe -show_streams 'file:Room Mate Folge 3 - Nis
hina Aoi entspannt sich-734461.mp4'
[ffmpeg] Fixing malformated aac bitstream in "Room Mate Folge 3 - Nishina Aoi en
tspannt sich-734461.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Room Mate Folge 3 - Nishina Aoi
entspannt sich-734461.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Room Mate F
olge 3 - Nishina Aoi entspannt sich-734461.temp.mp4'

---


### Description of your *issue*, suggested solution and other information

So i download the streams and mux it into a mkv and what happens is, that in German the Ä Ö Ü gets weird letters. i must convert it to UTF8 everytime. Can youtube-dl do this too or can you implent it?
![mstsc_2017-04-26_20-48-35](https://cloud.githubusercontent.com/assets/26443095/25451283/efcf01d8-2ac1-11e7-9377-e1b8b13bce79.png)

**Comment by dstftw** [comment]
Subtitles are **already** in UTF-8.

![image](https://cloud.githubusercontent.com/assets/1908898/25451859/c9a1a750-2aed-11e7-8c07-286adfb6edc5.png)

**Comment by TammysHead** [comment]
But if i mux this, it changes to the error shown in the picture. It is saved as ANSI, and not as UTF-8. Please mux it with a video and test it again.

**Comment by dstftw** [comment]
Once again: it's saved as UTF-8. Period. If you do subs embedding yourself then it's **your responsibility** to properly setup your tools you use for embedding. youtube-dl does subs embedding with `--embed-subs` just fine:

![image](https://cloud.githubusercontent.com/assets/1908898/25452393/b1e401a6-2aef-11e7-8339-5ee4e5dd0c25.png)
