### ISSUE TITLE
MixCloud download gets stuck at 10-20% and then connection time outs.

### ISSUE THREAD

**Issue by someziggyman** [rg3/youtube-dl#12843]
Looks like MixCloud's download is broken. The download will start as expected, but it gets stuck forever, until timeout. 

youtube-dl can get all the data via --dump-json, so it's not the issue with corrupt data or something..
please see the --verbose log below:

--verbose https://www.mixcloud.com/dublab_de/dublab-session-w-jay-scarlett
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.mixcloud.com/dublab_de/dublab-session-w-jay-scarlett']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.26
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[mixcloud] dublab_de-dublab-session-w-jay-scarlett: Downloading webpage
[debug] Invoking downloader on u'https://stream8.mixcloud.com/c/m4a/64/c/b/e/4/1904-d716-4def-b709-24226be7398e.m4a'
[download] Resuming download at byte 4190208
[download] Destination: dublab Session w_ Jay Scarlett (Prototype Excursions)-dublab_de-dublab-session-w-jay-scarlett.m4a
[download]  21.3% of 37.46MiB at  6.80MiB/s ETA 00:04

**Comment by dstftw** [comment]
It's not stuck. Mixcloud shapes speed after first couple of megabytes.
There is no connection timeout in the log. Provide log that clearly demonstrates a download error due to timeout.
