### ISSUE TITLE
HTTP Error 403 Pluralsight Download

### ISSUE THREAD

**Issue by JerryNinh** [rg3/youtube-dl#12862]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.26**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVA

TE', '--password', 'PRIVATE', '-o', 'e:\\Pluralsights\\C++ Fundamentals\\01. Context\\01. Introduction.mp4', '--playlist-start', '1', '--playlist-end', '1', '--max-downloads', '1', '-r', '6M', 'https://app.pluralsight.com/library/courses/cpp-fundamentals/table-of-contents', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.26
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] cpp-fundamentals: Downloading course JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\common.py", line 498, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\YoutubeDL.py", line 2106, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

```

**Comment by dstftw** [comment]
Can you watch it in browser in the first place?

**Comment by JerryNinh** [comment]
How send account to you?

**Comment by dstftw** [comment]
Answer my question first.

**Comment by JerryNinh** [comment]
First time, I watch pluralsight show check Captcha. After don't show anytime.
Pluralsight don't show HTTP Error as image
![pluralsight](https://cloud.githubusercontent.com/assets/10335193/25491360/f35abbc0-2b99-11e7-97d8-9bf8ca652c89.png)

**Comment by dstftw** [comment]
You need to do [this](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).

**Comment by JerryNinh** [comment]
I will checked again. Thanks

**Comment by JerryNinh** [comment]
I use cookies but youttube-dl show  Error: HTTP Error 403

**Comment by JerryNinh** [comment]
Version 2017.04.28 is fix it. Thanks
