### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by drmaq** [rg3/youtube-dl#12860]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.26**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.26
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-84679-gd65b595, ffprobe N-84679-gd65b595
[debug] Proxy map: {}
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.
I get this error after downloading a list of urls,
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'Chain Chronicle - The Light of Haecceitas -\\Chain Chronicle - The Light of Haecceitas - (TV Version)\\The Sword That Rends Darkness -  Chain Chronicle - The Light of Haecceitas - (TV Version) Episode 10 – The Sword That Rends Darkness.mp4.part-Frag0.part'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\downloader\http.py", line 175, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\utils.py", line 449, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'Chain Chronicle - The Light of Haecceitas -\\Chain Chronicle - The Light of Haecceitas - (TV Version)\\The Sword That Rends Darkness -  Chain Chronicle - The Light of Haecceitas - (TV Version) Episode 10 – The Sword That Rends Darkness.mp4.part-Frag0.part'

the odd part is that some how a "\\" is added to the file path when i have not included that in the command line. I have also tried this with just the specific video link but to no avail.

This is my output -o "%(series)s/%(season)s/%(episode)s -  %(title)s.%(ext)s"

**Comment by dstftw** [comment]
>### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
>
>Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
