### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last): 

### ISSUE THREAD

**Issue by rodzky** [rg3/youtube-dl#12887]
I am using version 2017.04.26 please help fix the issue.

ERROR: Signature extraction failed: Traceback (most recent call last):   File "C:\\Users\\dst\\AppData\\Roaming\\Build archive\\youtube-dl\\rg3\\tmpi8nwgst1\\build\\youtube_dl\\extractor\\youtube.py", line 1081, in _decrypt_signature   File "C:\\Users\\dst\\AppData\\Roaming\\Build archive\\youtube-dl\\rg3\\tmpi8nwgst1\\build\\youtube_dl\\extractor\\youtube.py", line 969, in _extract_signature_function youtube_dl.utils.ExtractorError: Cannot identify player \'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js\'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.  (caused by ExtractorError("Cannot identify player \'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js\'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by heylouiz** [comment]
This issue was already reported (twice!), first issue with a possible fix: #12885

**Comment by rodzky** [comment]
I am currently using the Windows exe file adding 'lang_REGION' inthe player url regex may not fix the issue?
