### ISSUE TITLE
Download failed "ERROR: unable to open for writing: [Errno 2] No such file or directory:  "

### ISSUE THREAD

**Issue by drmaq** [rg3/youtube-dl#12882]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.26**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.26
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-84679-gd65b595, ffprobe N-84679-gd65b595
[debug] Proxy map: {}
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.
I get this error after downloading a list of urls,
```
[info] Writing video subtitles to: Chain Chronicle - The Light of Haecceitas -\Chain Chronicle - The Light of Haecceitas - (TV Version)\The Sword That Rends Darkness -  Chain Chronicle - The Light of Haecceitas - (TV Version) Episode 10 – The Sword That Rends Darkness.frFR.ass
[debug] Invoking downloader on 'https://v.vrv.co/evs/18dd6062798f52331efbb74c49485128/assets/193fafd10143a31ccc03f5604aac95af_3158961.mp4/index-v1-a1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvMThkZDYwNjI3OThmNTIzMzFlZmJiNzRjNDk0ODUxMjgvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTQ5MzUwMzY2NH19fV19&Signature=Xi3IC~wfXGZ9ACHhyS0G3MYj2LhghHq95lVsKkDKVeiYpCyukAZz7sKTJGHinuEtDxbPz6~Tdz8B5VuoZlBn2mZIVKLoiNH6-BZTRLScNjGze2NsEWMNMRJK~sfZj1ACawxDwoI36axwZCiWToViZzxxmh0BR9C6Mjhx5HgzabkJ65ftkf7fplm4yabdt4MNvJwOa6rAa9xJHarwpTuGG0rlJaRHJrRtNo-SgbFhMlyC~Q4jLjwGd4tVuhXFpVq~u3trYkJUjojqzxcqfwo7wKT~TUux1ns2fK0A-7FQabRheFF0qQqxxXbIkXYhx0su1hZAMdsaM8dmxP3Ap--SzA__&Key-Pair-Id=APKAJKQQ2INNHTYFB44A'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 145
[download] Destination: Chain Chronicle - The Light of Haecceitas -\Chain Chronicle - The Light of Haecceitas - (TV Version)\The Sword That Rends Darkness -  Chain Chronicle - The Light of Haecceitas - (TV Version) Episode 10 – The Sword That Rends Darkness.mp4
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'Chain Chronicle - The Light of Haecceitas -\\Chain Chronicle - The Light of Haecceitas - (TV Version)\\The Sword That Rends Darkness -  Chain Chronicle - The Light of Haecceitas - (TV Version) Episode 10 – The Sword That Rends Darkness.mp4.part-Frag0.part'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\downloader\http.py", line 175, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\utils.py", line 449, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'Chain Chronicle - The Light of Haecceitas -\\Chain Chronicle - The Light of Haecceitas - (TV Version)\\The Sword That Rends Darkness -  Chain Chronicle - The Light of Haecceitas - (TV Version) Episode 10 – The Sword That Rends Darkness.mp4.part-Frag0.part'
```
the odd part is that some how a "\\" is added to the file path when i have not included that in the command line. I have also tried this with just the specific video link but to no avail.

This is my output``` -o "%(series)s/%(season)s/%(episode)s -  %(title)s.%(ext)s" ```

in order to get the download to work you need a cookie file from the website crunchyrool 
and I user the following incantation 
``` 
youtube-dl -o "%(series)s/%(season)s/%(episode)s -  %(title)s.%(ext)s" --all-sub --sub-format best -c --cookies cookies.txt --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36" --no-check-certificate -u ***** -p ***** -a Download.txt -v --print-traffic -C 
```
Please message me to get the password and username.

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by drmaq** [comment]
is there a length restriction?
