### ISSUE TITLE
Youtube-dl + axel - Error HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by AndreiArba** [rg3/youtube-dl#1290]
I'm using youtube-dl -g to get a download link from youtube and then I'm trying to download it using axel download accelerator and sometimes I'm getting a HTTP/1.1 403 Forbidden error and it's not about vevo encryption, which is now fixed by youtube-dl.I think it could be something about headers. Do you have any idea, why I get this error?

**Comment by remitamine** [comment]
try to use --external-downloader option.
if it didn't work than post the output you get and we will reopen this issue.
