### ISSUE TITLE
HTTP Error 404: Not Found on Recently Live Videos

### ISSUE THREAD

**Issue by Saamoz** [rg3/youtube-dl#12904]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.28*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.28**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\Gaming PC>youtube-dl https://www.youtube.com/watch?v=zydJaURF7Wg --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=zydJaURF7Wg', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.28
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] zydJaURF7Wg: Downloading webpage
[youtube] zydJaURF7Wg: Downloading video info webpage
[youtube] zydJaURF7Wg: Extracting video information
[youtube] {22} signature length 40.40, html5 player vflppxuSE
[youtube] {18} signature length 40.40, html5 player vflppxuSE
[youtube] {36} signature length 40.40, html5 player vflppxuSE
[youtube] {17} signature length 40.40, html5 player vflppxuSE
[youtube] zydJaURF7Wg: Downloading MPD manifest
[debug] Invoking downloader on 'https://redirector.googlevideo.com/videoplayback?source=youtube&upn=6k7IILD26e8&ei=-jQDWfXzE9idWNvbofAM&requiressl=yes&id=zydJaURF7Wg.0&expire=1493403994&gcr=sa&ratebypass=yes&beids=%5B9466592%5D&sparams=ei%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Cmime%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ip=87.101.206.112&key=yt6&ipbits=0&itag=22&mime=video%2Fmp4&signature=2DC3D7D57FFEB9D30350D20C4B53B97F07F008A4.8C511E415EB803DAA9DF9A2224BAE174E1D898C3'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\build\youtube_dl\YoutubeDL.py", line 1803, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\build\youtube_dl\YoutubeDL.py", line 1745, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\build\youtube_dl\downloader\common.py", line 360, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\build\youtube_dl\YoutubeDL.py", line 2106, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```
### Description of your *issue*, suggested solution and other information

It seems that when using youtube-dl to download videos that were recently streamed live, it results in an HTTP Error 404. The video resulting in the error above, found at [this url](https://www.youtube.com/watch?v=zydJaURF7Wg), was streamed live approximately 1 hour before attempting to download it which consistently produced the error. However after spending some time searching for a solution and retrying the same command, it worked like a normal video. My best guess would be some caching or processing of the live video on Youtube's end before it is available for programs like youtube-dl to download, however I was able to watch the video on Youtube's website while the problem occurred. Unfortunately I don't know enough about youtube-dl's algorithm to comment on why this may have happened.

Due to the strict timeframe of this problem, it may be difficult to reproduce and it is trivial to solve considering the download worked for me after some time passed. However I am documenting it here for the sake of completeness in case some developer decides to take a look, so that perheps others may benefit.

**Comment by yan12125** [comment]
Thanks for the report. There are already quite a few reports about issues on just-ended live streams, and there's also a generic proposal for handling such problems. See #3721.
