### ISSUE TITLE
[FEATURE] skip videos based on video duration

### ISSUE THREAD

**Issue by nkv123** [rg3/youtube-dl#12911]
- [x] Verified and I assure that I'm running youtube-dl 2017.04.28
 - [x] At least skimmed through README and most notably FAQ and BUGS sections
# Purpose of this issue?
 - [x] Feature request (request for a new functionality)
# Description:
in Video Selection:
Adding options to skip download of videos which are too long or too short.
--max-duration SEC
--min-duration SEC
With support of 1m for 1 minute and 1h for one hour.
as a time counterpart of 
--min-filesize SIZE
--max-filesize SIZE

**Comment by Tithen-Firion** [comment]
Use `--match-filter` option.

**Comment by yan12125** [comment]
Thanks @Tithen-Firion. He/She is definitely right.
