### ISSUE TITLE
[YouTube] Unable to download own watchlater playlist

### ISSUE THREAD

**Issue by formtapez** [rg3/youtube-dl#12917]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.28**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-o', u'/mnt/pool/youtube/%(upload_date)s_%(uploader)s_-_%(title)s_%(id)s.%(ext)s', u'--restrict-filenames', u'--no-overwrites', u'--mark-watched', u'--socket-timeout', u'30', u'--retries', u'25', u'--fragment-retries', u'25', u'--no-call-home', u'--cookies', u'/root/scripts/youtube-sync.cookies', u'--download-archive', u'/root/scripts/youtube-sync.archive', u'--audio-format', u'm4a', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.28
[debug] Python version 2.7.12 - Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Logging in
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2504, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2046, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.
```

---

### Description of your *issue*, suggested solution and other information

Since yesterday i can't download my own [watchlater playlist](https://www.youtube.com/playlist?list=WL) from youtube anymore. Einstein from the IRC channel says the google login changed.

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by formtapez** [comment]
I deleted my cookies file and now it is working.
