### ISSUE TITLE
Unable to download webpage: IncompleteRead

### ISSUE THREAD

**Issue by yulcheung** [rg3/youtube-dl#12915]
[youtube] qA9u6N4Rp98: Downloading webpage
ERROR: Unable to download webpage: IncompleteRead(15017 bytes read, 1341 more expected) (caused by IncompleteRead(15017 bytes read, 1341 more expected)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Green software\youtube>youtube-dl -U
youtube-dl is up-to-date (2017.04.28)

C:\Green software\youtube>

**Comment by Tithen-Firion** [comment]
_Be sure to call youtube-dl with the **--verbose** flag and include its **complete output**._
