### ISSUE TITLE
ERROR: unable to download video

### ISSUE THREAD

**Issue by AndreiArba** [rg3/youtube-dl#1291]
I'm getting this error, while downloading a video from youtube. This error occurs only sometimes if I try several downloads for the same video:

[youtube] Setting language
[youtube] 2Rz9SRNRias: Downloading video webpage
[youtube] 2Rz9SRNRias: Downloading video info webpage
[youtube] 2Rz9SRNRias: Extracting video information
[youtube] 2Rz9SRNRias: Encrypted signatures detected.
ERROR: unable to download video

**Comment by dstftw** [comment]
All mentioned URLs downloads well with latest version. Closing.
