### ISSUE TITLE
Authenticating into Youtube Fails. 

### ISSUE THREAD

**Issue by Togame-san** [rg3/youtube-dl#12927]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.28*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.28**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl --username "Username@gmail.com" --password SomePassword -v https://www.youtube.com/watch?v=GU-2C8Ec6co
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.youtube.com/playlist?list=PLpTleIvqKJUfi5klQ1s-kzJn24FhjBmuN']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.28
[debug] Python version 2.7.13 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: avconv 12, avprobe 12
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Logging in
[youtube:playlist] PLpTleIvqKJUfi5klQ1s-kzJn24FhjBmuN: Downloading webpage
ERROR: This playlist is private, use --username or --netrc to access it.
Traceback (most recent call last):
  File "/Users/arman/anaconda2/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/Users/arman/anaconda2/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/Users/arman/anaconda2/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 2103, in _real_extract
    has_videos, playlist = self._extract_playlist(playlist_id)
  File "/Users/arman/anaconda2/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 2046, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist is private, use --username or --netrc to access it.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information
The issue i have is that I have provided my login information but the program does not appear to recognize it. It appears that it does not login incorrectly. Please assume I have provided the correct username and password. The playlist I am accessing is a test playlist that is private.

**Comment by Togame-san** [comment]
Please note that the current URL points to just a video. I added the wrong command. Here is the log for an actual attempt to access a private playlist. 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.youtube.com/playlist?list=PLpTleIvqKJUfi5klQ1s-kzJn24FhjBmuN']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.28
[debug] Python version 2.7.13 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: avconv 12, avprobe 12
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Logging in
[youtube:playlist] PLpTleIvqKJUfi5klQ1s-kzJn24FhjBmuN: Downloading webpage
ERROR: This playlist is private, use --username or --netrc to access it.
Traceback (most recent call last):
  File "/Users/arman/anaconda2/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/Users/arman/anaconda2/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/Users/arman/anaconda2/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 2103, in _real_extract
    has_videos, playlist = self._extract_playlist(playlist_id)
  File "/Users/arman/anaconda2/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 2046, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist is private, use --username or --netrc to access it.

**Comment by Togame-san** [comment]
The format of the command is as in the previous log; the url is the only thing changed.

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by Togame-san** [comment]
[dump.txt](https://github.com/rg3/youtube-dl/files/966492/dump.txt)

**Comment by Togame-san** [comment]
What I want to do is create a script so that I can access all the playlists a youtube user has and download the one that he or she specifies.

**Comment by HPP8140** [comment]
Happens to me as well....works most of the time. I think it is related to new sign-in page.
https://support.google.com/accounts/answer/7338427?visit_id=0-636291563247234608-2983872999&p=signin_newlook&rd=1

**Comment by HPP8140** [comment]
Thanks

**Comment by sdudley7** [comment]
Same issue

**Comment by perpi** [comment]
I have encountered this error using this command over Tor network:

    youtube-dl -u myid@gmail.com -p mypass --write-auto-sub --sub-lang en --convert-subs "srt" --output ~/%\(title\)s https://youtube.com/playlist?list=somestringshere


`ERROR: This playlist is private, use --username or --netrc to access it.`
