### ISSUE TITLE
YOUKU Download failed

### ISSUE THREAD

**Issue by saku1119** [rg3/youtube-dl#12928]
use youtube-dl 2017.04.28

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>youtube-dl http://v.youku.com/v_show/id_XMjczMzQyOTk4OA==
.html?spm=a2hzp.8244740.0.0&from=y1.7-1.1
[youku] XMjczMzQyOTk4OA: Downloading JSON metadata
[download] Downloading playlist: 10 强者不屈,勇者无惧
[youku] playlist 10 强者不屈,勇者无惧: Collected 31 video ids (downloading 31 of
 them)
[download] Downloading video 1 of 31
[download] Destination: 10 强者不屈,勇者无惧-XMjczMzQyOTk4OA_part1.flv
[download] 100% of 46.91MiB in 00:11
[download] Downloading video 2 of 31
[download] Destination: 10 强者不屈,勇者无惧-XMjczMzQyOTk4OA_part2.flv
[download] 100% of 42.52MiB in 00:11
[download] Downloading video 3 of 31
[download] Destination: 10 强者不屈,勇者无惧-XMjczMzQyOTk4OA_part3.flv
[download] 100% of 56.58MiB in 00:15
[download] Downloading video 4 of 31
ERROR: unable to download video data: HTTP Error 404: Not Found
'from' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Administrator>

**Comment by yan12125** [comment]
You need to enclose the URL in double quotes. For example:
```
youtube-dl "http://v.youku.com/v_show/id_XMjczMzQyOTk4OA==.html?spm=a2hzp.8244740.0.0&from=y1.7-1.1"
```
See https://github.com/rg3/youtube-dl/blob/master/README.md#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by saku1119** [comment]
Thanks so much for your help! But it still didn't work.There are 31 parts of videos in total,but only the first one，second one and third one can be downloaded. 
This situation started from last week.Before last week，all the videos are available.
Thank you again for your kindness! 


Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>youtube-dl "http://v.youku.com/v_show/id_XMjczMzQyOTk4OA==.html?spm=a2hzp.8244740.0.0&from=y1.7-1.1"
[youku] XMjczMzQyOTk4OA: Downloading JSON metadata
[download] Downloading playlist: 10 强者不屈,勇者无惧
[youku] playlist 10 强者不屈,勇者无惧: Collected 31 video ids (downloading 31 of
 them)
[download] Downloading video 1 of 31
[download] Destination: 10 强者不屈,勇者无惧-XMjczMzQyOTk4OA_part1.flv
[download] 100% of 46.91MiB in 00:10
[download] Downloading video 2 of 31
[download] Destination: 10 强者不屈,勇者无惧-XMjczMzQyOTk4OA_part2.flv
[download] 100% of 42.52MiB in 00:10
[download] Downloading video 3 of 31
[download] Destination: 10 强者不屈,勇者无惧-XMjczMzQyOTk4OA_part3.flv
[download] 100% of 56.58MiB in 00:13
[download] Downloading video 4 of 31
ERROR: unable to download video data: HTTP Error 404: Not Found

C:\Users\Administrator>

**Comment by saku1119** [comment]
I have the membership of Youku, is it possible that I download videos with this software？

**Comment by ckz1211** [comment]
@saku1119  See https://pan.baidu.com/s/1dFILEl7

**Comment by yan12125** [comment]
If you want to download youku videos with youtube-dl, you can export cookies.txt via browser extensions and feed it to youtube-dl:
```
youtube-dl -v (the URL) --cookies cookies.txt
```

**Comment by saku1119** [comment]
to ckz1211， Thank you so much, it works！

to yan12125，Thank you for your kind reply！But it's shown in system that‘http.cookiejar.loaderror’can not be downloaded.

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>youtube-dl -v "http://v.youku.com/v_show/id_XMjczMzQzMDA2
NA==.html?from=zpdvip.001" --cookies cookies.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://v.youku.com/v_show/id_XMjczMzQzMDA2NA=
=.html?from=zpdvip.001', '--cookies', 'cookies.txt']
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\bu
ild\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\bu
ild\youtube_dl\__init__.py", line 432, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\bu
ild\youtube_dl\YoutubeDL.py", line 388, in __init__
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\bu
ild\youtube_dl\YoutubeDL.py", line 2189, in _setup_opener
  File "C:\Python\Python34\lib\http\cookiejar.py", line 1781, in load
  File "C:\Python\Python34\lib\http\cookiejar.py", line 2005, in _really_load
http.cookiejar.LoadError: 'cookies.txt' does not look like a Netscape format coo
kies file

C:\Users\Administrator>

**Comment by saku1119** [comment]
to ckz1211 Thank you so much, it works！but lost part3 and part16.

to yan12125 Thank you for your kind reply！it works perfectly!
