### ISSUE TITLE
[Youtube] --abort-on-error is triggered for planned streams

### ISSUE THREAD

**Issue by VADemon** [rg3/youtube-dl#12920]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.28*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.28**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: ['--rate-limit', '4.2M', '-f', 'bestvideo[height<=720]+bestaudio/bestvideo[width<=1920]+bestaudio/bestvideo+bestaudio/best']
[debug] Custom config: []
[debug] Command-line args: ['-v', '--write-pages', 'youtu.be/sCc4edfDAyI']
[debug] Encodings: locale cp1251, fs mbcs, out cp1251, pref cp1251
[debug] youtube-dl version 2017.04.28
[debug] Python version 3.4.4 - Windows-7
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[youtube] sCc4edfDAyI: Downloading webpage
[youtube] Saving request to sCc4edfDAyI_https_-_www.youtube.com_watchv=sCc4edfDAyI_gl=US_hl=en_has_verified=1_bpctr=9999999999.dump
[youtube] sCc4edfDAyI: Downloading video info webpage
[youtube] Saving request to sCc4edfDAyI_https_-_www.youtube.com_get_video_info_video_id=sCc4edfDAyI_el=info_ps=default_eurl=_gl=US_hl=en.dump
[youtube] sCc4edfDAyI: Extracting video information
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\build\youtube_dl\extractor\youtube.py", line 1715, in _real_extract
youtube_dl.utils.ExtractorError: This video is unavailable.
```
---

- Example video: https://www.youtube.com/watch?v=sCc4edfDAyI

I'm using `--abort-on-error` to download my subscriptions, so I don't miss any video by mistake. The current logic makes it impossible to proceed downloading of the subscription list because of a planned stream that is not yet available for playback/download.

Since it can't be downloaded, youtube-dl aborts further operation. In my opinion such planned streams should not trigger this option and be ignored - it's up to a discussion though.

**Proposal:** If possible, detect if it's a planned stream and if so, do not abort the download even when the option is present.

**Dump files:**

[sCc4edfDAyI_https_-_www.youtube.com_get_video_info_video_id=sCc4edfDAyI_el=info_ps=default_eurl=_gl=US_hl=en.dump.txt](https://github.com/rg3/youtube-dl/files/966159/sCc4edfDAyI_https_-_www.youtube.com_get_video_info_video_id.sCc4edfDAyI_el.info_ps.default_eurl._gl.US_hl.en.dump.txt)

[sCc4edfDAyI_https_-_www.youtube.com_watchv=sCc4edfDAyI_gl=US_hl=en_has_verified=1_bpctr=9999999999.dump.txt](https://github.com/rg3/youtube-dl/files/966160/sCc4edfDAyI_https_-_www.youtube.com_watchv.sCc4edfDAyI_gl.US_hl.en_has_verified.1_bpctr.9999999999.dump.txt)

**Comment by dstftw** [comment]
Use `-i` instead.

**Comment by VADemon** [comment]
`-i` ignores any error, the request is to ignore this specific error for planned streams.
