### ISSUE TITLE
Ver.04.28 can not use aria2c as --external-downloader

### ISSUE THREAD

**Issue by KwToPA** [rg3/youtube-dl#12923]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.28*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.28**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -v --external-downloader aria2c "link" --external-downloader-args "-s100 -k1M -x100"


[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--external-downloader', u'aria2c', u'https://www.youtube.com/watch?v=nq0hUIaD_ds', u'--external-downloader-args', u'-s100 -k1M -x100']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.28
[debug] Python version 2.7.5 - Linux-4.10.10-1.el7.elrepo.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[youtube] nq0hUIaD_ds: Downloading webpage
[youtube] nq0hUIaD_ds: Downloading video info webpage
[youtube] nq0hUIaD_ds: Extracting video information
[youtube] nq0hUIaD_ds: Downloading MPD manifest
[debug] Invoking downloader on u'link'
[dashsegments] Total fragments: 1235
[download] Destination:xx.mp4
[download]  10.4% of ~2.47GiB at 312.51KiB/s ETA 11:44^C

```

```--external-downloader aria2c``` and ``` --external-downloader-args "-s100 -k1M -x100"``` do not work as before

**Comment by KwToPA** [comment]
aria2c -v
aria2 version 1.31.0
Copyright (C) 2006, 2016 Tatsuhiro Tsujikawa

**Comment by dstftw** [comment]
This is DASH served in segments not a single file.
