### ISSUE TITLE
Savefrom.net: unable to download geo-restricted youtube videos

### ISSUE THREAD

**Issue by mujunk** [rg3/youtube-dl#12931]
Below is an example.
http://en.savefrom.net/#url=http://youtube.com/watch?v=1NGkbema9qw&utm_source=youtube.com&utm_medium=short_domains&utm_campaign=ssyoutube.com
NB: I can download the file using google chrome, but cannot view on youtube due to geo-restriction.

**Comment by dstftw** [comment]
Offtopic.

**Comment by mujunk** [comment]
How is this offtopic?
Savefrom.net is listed under supported sites

**Comment by dstftw** [comment]
Extraction is delegated to youtube extractor. Can you watch http://youtube.com/watch?v=1NGkbema9qw in browser?

**Comment by mujunk** [comment]
Thanks for your response. Since that video is geo-restricted it is not watchable on youtube. Savefrom.net provides the ultimate googlevideo url which is not geo-restricted hence can be downloaded.
Could you please consider modifying the extractor so that video links are picked up from the savefrom.net page instead of youtube.

**Comment by yan12125** [comment]
In general youtube-dl should fetch videos directly from the original site with regards to privacy. For redirector.googlevideo.com URLs, see #11779.
