### ISSUE TITLE
Specifying output-filename in batch-file

### ISSUE THREAD

**Issue by seiz** [rg3/youtube-dl#12935]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.28**
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Feature request: Specify the output filename in batch-file
I have youtube-dl download files via the -a parameter, a text file with URLs and cron to later watch them via Plex. Works beautifully. But for TV-Episodes, i'd like to already specify the output-filename in the batch file, because Plex has rather strict requirements for filenames (e.g. SeriesNames01e01.mp4).

My suggestion is, that we could just start lines in the batch-file with regular youtube-dl arguments. So specifying an output-filename and url in a batch file might look like this:

    -o "Watchit s01e01.mp4" http://myurl.example.com/my-movie-e01.mp4
    -o "Watchit s01e02.mp4" http://myurl.example.com/my-movie-e02.mp4
    …

Thanks for a great tool!
Stefan

**Comment by dstftw** [comment]
Batch file is not supposed to carry configuration. Output template supports substitutions for `%(season_number)s` and so on.
