### ISSUE TITLE
Unknown MIME type application/mp4 in DASH manifest

### ISSUE THREAD

**Issue by xavave** [rg3/youtube-dl#12947]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.exe -v --verbose -f bestvideo+bestaudio https://cdn.pluzzvad.ftv.vualto.com/usp/content/27576/Web_prog_1500K_vf_169_25644.ism/.mpd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--verbose', '-f', 'bestvideo+bestaudio', 'https://cdn.pluzzvad.ftv.vualto.com/usp/content/27576/Web_prog_1500K_vf_169_25644.ism/.mpd']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[generic] .mpd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] .mpd: Downloading webpage
[generic] .mpd: Extracting information
WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\generic.py", line 1973, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 1052, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
<end of log>
```

**Comment by xavave** [comment]
youtube-dl -v --verbose **--print-traffic --dump-pages**  -f  bestvideo+bestaudio https://cdn.pluzzvad.ftv.vualto.com/usp/content/27576/Web_prog_1500K_vf_169_25644.ism/.mpd

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--verbose', '--print-traffic', '--dump-pages', '-f', 'bestvideo+bestaudio', 'https://cdn.pluzzvad.ftv.vualto.com/usp/content/27576/Web_prog_1500K_vf_169_25644.ism/.mpd']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[generic] .mpd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] .mpd: Downloading webpage
[generic] Dumping request to https://cdn.pluzzvad.ftv.vualto.com/usp/content/27576/Web_prog_1500K_vf_169_25644.ism/.mpd
PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBDcmVhdGVkIHdpdGggVW5pZmllZCBTdHJlYW1pbmcgUGxhdGZvcm0odmVyc2lvbj0xLjcuMjUpIC0tPgo8TVBECiAgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIKICB4bWxucz0idXJuOm1wZWc6ZGFzaDpzY2hlbWE6bXBkOjIwMTEiCiAgeHNpOnNjaGVtYUxvY2F0aW9uPSJ1cm46bXBlZzpkYXNoOnNjaGVtYTptcGQ6MjAxMSBodHRwOi8vc3RhbmRhcmRzLmlzby5vcmcvaXR0Zi9QdWJsaWNseUF2YWlsYWJsZVN0YW5kYXJkcy9NUEVHLURBU0hfc2NoZW1hX2ZpbGVzL0RBU0gtTVBELnhzZCIKICB4bWxuczpjZW5jPSJ1cm46bXBlZzpjZW5jOjIwMTMiCiAgeG1sbnM6bWFzPSJ1cm46bWFybGluOm1hczoxLTA6c2VydmljZXM6c2NoZW1hczptcGQiCiAgdHlwZT0ic3RhdGljIgogIG1lZGlhUHJlc2VudGF0aW9uRHVyYXRpb249IlBUNTBNMy40MzQ2NjZTIgogIG1heFNlZ21lbnREdXJhdGlvbj0iUFQxTSIKICBtaW5CdWZmZXJUaW1lPSJQVDEwUyIKICBwcm9maWxlcz0idXJuOm1wZWc6ZGFzaDpwcm9maWxlOmlzb2ZmLWxpdmU6MjAxMSx1cm46Y29tOmRhc2hpZjpkYXNoMjY0Ij4KICA8UGVyaW9kCiAgICBkdXJhdGlvbj0iUFQ1ME0zLjQzNDY2NlMiPgogICAgPEJhc2VVUkw+ZGFzaC88L0Jhc2VVUkw+CiAgICA8QWRhcHRhdGlvblNldAogICAgICBncm91cD0iMSIKICAgICAgY29udGVudFR5cGU9ImF1ZGlvIgogICAgICBsYW5nPSJmciIKICAgICAgbWluQmFuZHdpZHRoPSIxMjU0MzYiCiAgICAgIG1heEJhbmR3aWR0aD0iMTI1NDM2IgogICAgICBzZWdtZW50QWxpZ25tZW50PSJ0cnVlIgogICAgICBhdWRpb1NhbXBsaW5nUmF0ZT0iNDgwMDAiCiAgICAgIG1pbWVUeXBlPSJhdWRpby9tcDQiCiAgICAgIGNvZGVjcz0ibXA0YS40MC4yIj4KICAgICAgPEF1ZGlvQ2hhbm5lbENvbmZpZ3VyYXRpb24KICAgICAgICBzY2hlbWVJZFVyaT0idXJuOm1wZWc6ZGFzaDoyMzAwMzozOmF1ZGlvX2NoYW5uZWxfY29uZmlndXJhdGlvbjoyMDExIgogICAgICAgIHZhbHVlPSIyIj4KICAgICAgPC9BdWRpb0NoYW5uZWxDb25maWd1cmF0aW9uPgogICAgICA8IS0tIENvbW1vbiBFbmNyeXB0aW9uIC0tPgogICAgICA8Q29udGVudFByb3RlY3Rpb24KICAgICAgICBzY2hlbWVJZFVyaT0idXJuOm1wZWc6ZGFzaDptcDRwcm90ZWN0aW9uOjIwMTEiCiAgICAgICAgdmFsdWU9ImNlbmMiCiAgICAgICAgY2VuYzpkZWZhdWx0X0tJRD0iREM4OEI0MjAtOUMxMy1DNUM2LTY2MjUtNTc3MjgyNzlCMTk4Ij4KICAgICAgPC9Db250ZW50UHJvdGVjdGlvbj4KICAgICAgPCEtLSBQbGF5UmVhZHkgLS0+CiAgICAgIDxDb250ZW50UHJvdGVjdGlvbgogICAgICAgIHNjaGVtZUlkVXJpPSJ1cm46dXVpZDo5QTA0RjA3OS05ODQwLTQyODYtQUI5Mi1FNjVCRTA4ODVGOTUiCiAgICAgICAgdmFsdWU9Ik1TUFIgMi4wIj4KICAgICAgPC9Db250ZW50UHJvdGVjdGlvbj4KICAgICAgPCEtLSBBZG9iZUFjY2VzcyAtLT4KICAgICAgPENvbnRlbnRQcm90ZWN0aW9uCiAgICAgICAgc2NoZW1lSWRVcmk9InVybjp1dWlkOkYyMzlFNzY5LUVGQTMtNDg1MC05QzE2LUE5MDNDNjkzMkVGQiIKICAgICAgICB2YWx1ZT0iQWRvYmVBY2Nlc3MgNS4wIj4KICAgICAgPC9Db250ZW50UHJvdGVjdGlvbj4KICAgICAgPCEtLSBXaWRldmluZSAtLT4KICAgICAgPENvbnRlbnRQcm90ZWN0aW9uCiAgICAgICAgc2NoZW1lSWRVcmk9InVybjp1dWlkOkVERUY4QkE5LTc5RDYtNEFDRS1BM0M4LTI3RENENTFEMjFFRCI+CiAgICAgIDwvQ29udGVudFByb3RlY3Rpb24+CiAgICAgIDwhLS0gTWFybGluIC0tPgogICAgICA8Q29udGVudFByb3RlY3Rpb24KICAgICAgICBzY2hlbWVJZFVyaT0idXJuOnV1aWQ6NUU2MjlBRjUtMzhEQS00MDYzLTg5NzctOTdGRkJEOTkwMkQ0Ij4KPG1hczpNYXJsaW5Db250ZW50SWRzPgogIDxtYXM6TWFybGluQ29udGVudElkPnVybjptYXJsaW46a2lkOmRjODhiNDIwOWMxM2M1YzY2NjI1NTc3MjgyNzliMTk4PC9tYXM6TWFybGluQ29udGVudElkPgo8L21hczpNYXJsaW5Db250ZW50SWRzPgogICAgICA8L0NvbnRlbnRQcm90ZWN0aW9uPgogICAgICA8U2VnbWVudFRlbXBsYXRlCiAgICAgICAgdGltZXNjYWxlPSI0ODAwMCIKICAgICAgICBpbml0aWFsaXphdGlvbj0iV2ViX3Byb2dfMTUwMEtfdmZfMTY5XzI1NjQ0LSRSZXByZXNlbnRhdGlvbklEJC5kYXNoIgogICAgICAgIG1lZGlhPSJXZWJfcHJvZ18xNTAwS192Zl8xNjlfMjU2NDQtJFJlcHJlc2VudGF0aW9uSUQkLSRUaW1lJC5kYXNoIj4KICAgICAgICA8U2VnbWVudFRpbWVsaW5lPgogICAgICAgICAgPFMgdD0iMCIgZD0iMzY4NjQwIiByPSIzOTAiIC8+CiAgICAgICAgICA8UyBkPSIyNTYwMCIgLz4KICAgICAgICAgIDxTIGQ9IjEwMjQiIC8+CiAgICAgICAgPC9TZWdtZW50VGltZWxpbmU+CiAgICAgIDwvU2VnbWVudFRlbXBsYXRlPgogICAgICA8UmVwcmVzZW50YXRpb24KICAgICAgICBpZD0idmY9MTI1NDM2IgogICAgICAgIGJhbmR3aWR0aD0iMTI1NDM2Ij4KICAgICAgPC9SZXByZXNlbnRhdGlvbj4KICAgIDwvQWRhcHRhdGlvblNldD4KICAgIDxBZGFwdGF0aW9uU2V0CiAgICAgIGdyb3VwPSIzIgogICAgICBjb250ZW50VHlwZT0idGV4dCIKICAgICAgbGFuZz0iZnIiCiAgICAgIG1pbkJhbmR3aWR0aD0iMTAwMCIKICAgICAgbWF4QmFuZHdpZHRoPSIxMDAwIgogICAgICBtaW1lVHlwZT0iYXBwbGljYXRpb24vbXA0IgogICAgICBjb2RlY3M9InN0cHAiPgogICAgICA8Um9sZQogICAgICAgIHNjaGVtZUlkVXJpPSJ1cm46bXBlZzpkYXNoOnJvbGU6MjAxMSIKICAgICAgICB2YWx1ZT0iY2FwdGlvbiI+CiAgICAgIDwvUm9sZT4KICAgICAgPFNlZ21lbnRUZW1wbGF0ZQogICAgICAgIHRpbWVzY2FsZT0iMTAwMCIKICAgICAgICBpbml0aWFsaXphdGlvbj0iV2ViX3Byb2dfMTUwMEtfdmZfMTY5XzI1NjQ0LSRSZXByZXNlbnRhdGlvbklEJC5kYXNoIgogICAgICAgIG1lZGlhPSJXZWJfcHJvZ18xNTAwS192Zl8xNjlfMjU2NDQtJFJlcHJlc2VudGF0aW9uSUQkLSRUaW1lJC5kYXNoIj4KICAgICAgICA8U2VnbWVudFRpbWVsaW5lPgogICAgICAgICAgPFMgdD0iMCIgZD0iNjAwMDAiIHI9IjQ4IiAvPgogICAgICAgICAgPFMgZD0iNDM3MjAiIC8+CiAgICAgICAgPC9TZWdtZW50VGltZWxpbmU+CiAgICAgIDwvU2VnbWVudFRlbXBsYXRlPgogICAgICA8UmVwcmVzZW50YXRpb24KICAgICAgICBpZD0idGV4dHN0cmVhbV9mcmE9MTAwMCIKICAgICAgICBiYW5kd2lkdGg9IjEwMDAiPgogICAgICA8L1JlcHJlc2VudGF0aW9uPgogICAgPC9BZGFwdGF0aW9uU2V0PgogICAgPEFkYXB0YXRpb25TZXQKICAgICAgZ3JvdXA9IjIiCiAgICAgIGNvbnRlbnRUeXBlPSJ2aWRlbyIKICAgICAgbGFuZz0iZW4iCiAgICAgIHBhcj0iMTY6OSIKICAgICAgbWluQmFuZHdpZHRoPSI4MDYwMDAiCiAgICAgIG1heEJhbmR3aWR0aD0iMTUwNjAwMCIKICAgICAgbWluV2lkdGg9IjY0MCIKICAgICAgbWF4V2lkdGg9IjgzMiIKICAgICAgbWluSGVpZ2h0PSIzNjAiCiAgICAgIG1heEhlaWdodD0iNDY4IgogICAgICBzZWdtZW50QWxpZ25tZW50PSJ0cnVlIgogICAgICBmcmFtZVJhdGU9IjI1IgogICAgICBtaW1lVHlwZT0idmlkZW8vbXA0IgogICAgICBjb2RlY3M9ImF2YzEuNEQwMDI4IgogICAgICBzdGFydFdpdGhTQVA9IjEiPgogICAgICA8IS0tIENvbW1vbiBFbmNyeXB0aW9uIC0tPgogICAgICA8Q29udGVudFByb3RlY3Rpb24KICAgICAgICBzY2hlbWVJZFVyaT0idXJuOm1wZWc6ZGFzaDptcDRwcm90ZWN0aW9uOjIwMTEiCiAgICAgICAgdmFsdWU9ImNlbmMiCiAgICAgICAgY2VuYzpkZWZhdWx0X0tJRD0iREM4OEI0MjAtOUMxMy1DNUM2LTY2MjUtNTc3MjgyNzlCMTk4Ij4KICAgICAgPC9Db250ZW50UHJvdGVjdGlvbj4KICAgICAgPCEtLSBQbGF5UmVhZHkgLS0+CiAgICAgIDxDb250ZW50UHJvdGVjdGlvbgogICAgICAgIHNjaGVtZUlkVXJpPSJ1cm46dXVpZDo5QTA0RjA3OS05ODQwLTQyODYtQUI5Mi1FNjVCRTA4ODVGOTUiCiAgICAgICAgdmFsdWU9Ik1TUFIgMi4wIj4KICAgICAgPC9Db250ZW50UHJvdGVjdGlvbj4KICAgICAgPCEtLSBBZG9iZUFjY2VzcyAtLT4KICAgICAgPENvbnRlbnRQcm90ZWN0aW9uCiAgICAgICAgc2NoZW1lSWRVcmk9InVybjp1dWlkOkYyMzlFNzY5LUVGQTMtNDg1MC05QzE2LUE5MDNDNjkzMkVGQiIKICAgICAgICB2YWx1ZT0iQWRvYmVBY2Nlc3MgNS4wIj4KICAgICAgPC9Db250ZW50UHJvdGVjdGlvbj4KICAgICAgPCEtLSBXaWRldmluZSAtLT4KICAgICAgPENvbnRlbnRQcm90ZWN0aW9uCiAgICAgICAgc2NoZW1lSWRVcmk9InVybjp1dWlkOkVERUY4QkE5LTc5RDYtNEFDRS1BM0M4LTI3RENENTFEMjFFRCI+CiAgICAgIDwvQ29udGVudFByb3RlY3Rpb24+CiAgICAgIDwhLS0gTWFybGluIC0tPgogICAgICA8Q29udGVudFByb3RlY3Rpb24KICAgICAgICBzY2hlbWVJZFVyaT0idXJuOnV1aWQ6NUU2MjlBRjUtMzhEQS00MDYzLTg5NzctOTdGRkJEOTkwMkQ0Ij4KPG1hczpNYXJsaW5Db250ZW50SWRzPgogIDxtYXM6TWFybGluQ29udGVudElkPnVybjptYXJsaW46a2lkOmRjODhiNDIwOWMxM2M1YzY2NjI1NTc3MjgyNzliMTk4PC9tYXM6TWFybGluQ29udGVudElkPgo8L21hczpNYXJsaW5Db250ZW50SWRzPgogICAgICA8L0NvbnRlbnRQcm90ZWN0aW9uPgogICAgICA8U2VnbWVudFRlbXBsYXRlCiAgICAgICAgdGltZXNjYWxlPSIyNTAwMCIKICAgICAgICBpbml0aWFsaXphdGlvbj0iV2ViX3Byb2dfMTUwMEtfdmZfMTY5XzI1NjQ0LSRSZXByZXNlbnRhdGlvbklEJC5kYXNoIgogICAgICAgIG1lZGlhPSJXZWJfcHJvZ18xNTAwS192Zl8xNjlfMjU2NDQtJFJlcHJlc2VudGF0aW9uSUQkLSRUaW1lJC5kYXNoIj4KICAgICAgICA8U2VnbWVudFRpbWVsaW5lPgogICAgICAgICAgPFMgdD0iMCIgZD0iMTkyMDAwIiByPSIzOTAiIC8+CiAgICAgICAgICA8UyBkPSIxMzAwMCIgLz4KICAgICAgICA8L1NlZ21lbnRUaW1lbGluZT4KICAgICAgPC9TZWdtZW50VGVtcGxhdGU+CiAgICAgIDxSZXByZXNlbnRhdGlvbgogICAgICAgIGlkPSJ2aWRlb19lbmc9ODA2MDAwIgogICAgICAgIGJhbmR3aWR0aD0iODA2MDAwIgogICAgICAgIHdpZHRoPSI2NDAiCiAgICAgICAgaGVpZ2h0PSIzNjAiCiAgICAgICAgc2NhblR5cGU9InByb2dyZXNzaXZlIj4KICAgICAgPC9SZXByZXNlbnRhdGlvbj4KICAgICAgPFJlcHJlc2VudGF0aW9uCiAgICAgICAgaWQ9InZpZGVvX2VuZz0xMTA2MDAwIgogICAgICAgIGJhbmR3aWR0aD0iMTEwNjAwMCIKICAgICAgICB3aWR0aD0iNzY4IgogICAgICAgIGhlaWdodD0iNDMyIgogICAgICAgIHNjYW5UeXBlPSJwcm9ncmVzc2l2ZSI+CiAgICAgIDwvUmVwcmVzZW50YXRpb24+CiAgICAgIDxSZXByZXNlbnRhdGlvbgogICAgICAgIGlkPSJ2aWRlb19lbmc9MTUwNjAwMCIKICAgICAgICBiYW5kd2lkdGg9IjE1MDYwMDAiCiAgICAgICAgd2lkdGg9IjgzMiIKICAgICAgICBoZWlnaHQ9IjQ2OCIKICAgICAgICBzY2FuVHlwZT0icHJvZ3Jlc3NpdmUiPgogICAgICA8L1JlcHJlc2VudGF0aW9uPgogICAgPC9BZGFwdGF0aW9uU2V0PgogIDwvUGVyaW9kPgo8L01QRD4K
[generic] .mpd: Extracting information
WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\generic.py", line 1973, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 1052, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
DRM protected video.

**Comment by xavave** [comment]
if i specify username and password for my pluzztv account it doesn't work neither
