### ISSUE TITLE
YtSubs Skip Live Video?

### ISSUE THREAD

**Issue by sdudley7** [rg3/youtube-dl#12946]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -u user -p pw :ytsubs -v

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I use youtube-dl to download my subscriptions and it works flawlessly except it hangs on live videos. I've tried skipping durations, sizes, etc. Is there any way I can just ignore all live videos and not even attempt to download them?

**Comment by dstftw** [comment]
`--match-filter '!is_live'`.

**Comment by sdudley7** [comment]
It is giving me invalid match filter. I am on the most recent YouTube-Dl

Thanks!,
Scott Dudley
(540) 819-7509

**Comment by beigexperience** [comment]
I'll leave this here if anyone stumbles on this via google. For some reason the quotes around !is_live had to be double quotes for it to work. 

Tried `--match-filter "!is_live"` and it worked. This was on Windows 10.

**Comment by sdudley7** [comment]
@beigexperience You the man!

**Comment by AndCycle** [comment]
I look through the `OUTPUT TEMPLATE` and there is no mention about this, maybe someone could add related description about this?
