### ISSUE TITLE
Cannot identify player   Python  crashes  

### ISSUE THREAD

**Issue by moiseyo** [rg3/youtube-dl#12952]
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### 
$ youtube-dl -v <your command line>
C:\temp\short>youtube-dl -v http://www.youtube.com/watch?v=a0Xm5D9CGqk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.youtube.com/watch?v=a0Xm5D9CGqk']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.26
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-79056-gd0a9114, ffprobe N-79056-gd0a9114
[debug] Proxy map: {}
[youtube] a0Xm5D9CGqk: Downloading webpage
[youtube] a0Xm5D9CGqk: Downloading video info webpage
[youtube] a0Xm5D9CGqk: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {43} signature length 40.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 1642, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 1091, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

<end of log>

**Comment by Dave-ts** [comment]
Additional environment information, same error


```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.26
[debug] Python version 3.5.3 - Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2, rtmpdump 2.4
```

**Comment by gnat42** [comment]
Same issue Fedora 25 (youtube-dl-2017.04.09-1.fc25.noarch)

**Comment by maop** [comment]
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . **Make sure you are using the latest version**; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by gnat42** [comment]
I also just updated to 2017.04.17 with the same output.

**Comment by maop** [comment]
```
maop ~ $ youtube-dl --version
2017.05.01

```
i'm using pip `pip install -U youtube-dl `

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by moiseyo** [comment]
I use daily update

foreach ($lb in $libs) {
Invoke-Expression " $pip_exe  install  --upgrade  $lb" 2>&1 | Tee-Object
-append -FilePath $LOG_FILE
}
Invoke-Expression "$pip_exe list" 2>&1 | Tee-Object -append -FilePath
$LOG_FILE

cd c:\bin
c:\bin\youtube-dl.exe -U 2>&1 | Tee-Object -append -FilePath $LOG_FILE

and today have a new issue

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '
http://www.youtube.com/watch?v=tMpfqtGMN98']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-79056-gd0a9114, ffprobe N-79056-gd0a9114
[debug] Proxy map: {}
[youtube] tMpfqtGMN98: Downloading webpage
[youtube] tMpfqtGMN98: Downloading video info webpage
ERROR: tMpfqtGMN98: YouTube said: "НОВИНКА! комедия секса! Ген..."
The YouTube account associated with this video has been terminated due to
multiple third-party notifications of copyright infringement.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build
archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\YoutubeDL.py", line
760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build
archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py",
line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build
archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\youtube.py",
line 1388, in _real_extract
youtube_dl.utils.ExtractorError: tMpfqtGMN98: YouTube said: "НОВИНКА!
комедия секса! Ген..."
The YouTube account associated with this video has been terminated due to
multiple third-party notifications of copyright infringement.





Moisey O

moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.

**Comment by dstftw** [comment]
@moiseyo bother to read the error message.
