### ISSUE TITLE
Issue with duration

### ISSUE THREAD

**Issue by google32465** [rg3/youtube-dl#12958]
Hiya

I have an issue with the video duration

It returns 8:5 for a video that is 8:05

Is there to return the duration with the leading 0s or even return it as a number in seconds so I can create my own time from it

Thanks

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by google32465** [comment]
edited....

**Comment by dstftw** [comment]
>Please make sure the description is worded well enough to be understood. Provide as much context and examples as possible.

There are no telepathists here. Clearly explain what are you doing.

**Comment by google32465** [comment]
I am calling a video and getting the JSON file and the duration array it returns for a video of duration 8:05 returns 8:5, meaning it doesn't include zeros. https://gyazo.com/46a637777ff973a9522ac17b87610667 is what it returns for the video I just explained. It returns wthout zeros

**Comment by dstftw** [comment]
Show your complete code.

**Comment by dstftw** [comment]
>PS C:\dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py eUt5kzEoOp4 --dump-json | jq .duration
368
