### ISSUE TITLE
Vice URL Unsupported

### ISSUE THREAD

**Issue by annomatik** [rg3/youtube-dl#12968]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

c:\>youtube-dl -v https://www.vice.com/en_us/article/on-set-with-the-woman-making-mormon-porn-in-utah
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.vice.com/en_us/article/on-set-with-the-woman-making-mormon-porn-in-utah']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77197-gdf2ce13, ffprobe N-77197-gdf2ce13
[debug] Proxy map: {}
[generic] on-set-with-the-woman-making-mormon-porn-in-utah: Requesting header
WARNING: Falling back on generic information extractor.
[generic] on-set-with-the-woman-making-mormon-porn-in-utah: Downloading webpage
[generic] on-set-with-the-woman-making-mormon-porn-in-utah: Extracting information
ERROR: Unsupported URL: https://www.vice.com/en_us/article/on-set-with-the-woman-making-mormon-porn-in-utah
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\generic.py", line 2834, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.vice.com/en_us/article/on-set-with-the-woman-making-mormon-porn-in-utah

**Comment by yan12125** [comment]
Thanks for the report. Vice articles will be supported in the next version.

**Comment by annomatik** [comment]
Thank You!
