### ISSUE TITLE
Youtube fails to authenticate consistently

### ISSUE THREAD

**Issue by HPP8140** [rg3/youtube-dl#12973]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
**Failed:**
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u':ytwatchlater', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v', u'-s', u'-j', u'--flat-playlist']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2017.05.01
[debug] Python version 2.7.9 - Linux-3.14.0-kirkwood-tld-1-armv5tel-with-debian-8.5
[debug] exe versions: avconv 11.6-6, avprobe 11.6-6, ffmpeg 0.8.20-6
[debug] Proxy map: {}
WARNING: unable to log in: bad username or password
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/lib/python2.7/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/youtube_dl/extractor/youtube.py", line 2504, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/lib/python2.7/youtube_dl/extractor/youtube.py", line 2046, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.

**Worked a couple minutes later (after a few tries):**
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u':ytwatchlater', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v', u'-s', u'-j', u'--flat-playlist']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2017.05.01
[debug] Python version 2.7.9 - Linux-3.14.0-kirkwood-tld-1-armv5tel-with-debian-8.5
[debug] exe versions: avconv 11.6-6, avprobe 11.6-6, ffmpeg 0.8.20-6
[debug] Proxy map: {}
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

Youtube fails to authenticate consistently...works 50/50. I think it is related to new sign-in page.
https://support.google.com/accounts/answer/7338427?visit_id=0-636291563247234608-2983872999&p=signin_newlook&rd=1.

**Comment by dstftw** [comment]
Duplicate of #12927.
