### ISSUE TITLE
Prime Video [Amazon]

### ISSUE THREAD

**Issue by SamWillson** [rg3/youtube-dl#12985]
I have the month trial started for primevideo.com 

Can anyone add the primevideo support. It is an amazon product which streams tv shows.

**Comment by gkoelln** [comment]
This isn't likely going to happen, since it's DRM-protected. (See #1753.)

**Comment by yan12125** [comment]
@gkoelln Thanks for pointing out the related issue.

@SamWillson Please move on there for further discussions.
