### ISSUE TITLE
Does Youtube-dl support YouTube mixes?

### ISSUE THREAD

**Issue by Justify05** [rg3/youtube-dl#12984]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other
---
Sorry for a question.
So the question in the topic. I use discord bot and when I want to add a youtube mix (Eample: https://www.youtube.com/watch?v=IcrbM1l_BoI&list=RDQMVCAPd5cwBcg) it just download first video that's all. And i don't know is it my trouble or youtube-dl doesn't support yt mixes?

**Comment by dstftw** [comment]
It does.
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
