### ISSUE TITLE
youtube subscriptions ":ytsubs" not working anymore?

### ISSUE THREAD

**Issue by MatrixView** [rg3/youtube-dl#12992]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
---------------------

It seems my youtube subscriptions feed stopped working with Youtube-DL. Maybe youtube changed their site?  On the site itself (https://www.youtube.com/feed/subscriptions) it shows many videos, so hopefully you can find out why it finds none with youtube-dl.

Thanx a lot in advance!

```
D:\>youtube-dl -u [user] -p [pass] :ytsubs --no-check-certificate -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', ':ytsubs', '--no-check-certificate', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-67388-g37425fc, ffprobe N-67388-g37425fc, rtmpdump 2.4-47-gc26c541
[debug] Proxy map: {}
[youtube:subscriptions] Downloading login page
[youtube:subscriptions] Logging in
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: Youtube Subscriptions

```

**Comment by MatrixView** [comment]
Ehmm, I'd understand if both my issues were possibly related, and therefore one could be seen as a duplicates of the other, but I don't get why BOTH of them are actually closed with a status duplicate. To what original issue-nr are both my issue-nrs "duplicates" of?

Thanx!

**Comment by dstftw** [comment]
#12927.
