### ISSUE TITLE
arte.tv:+7, ydl downloads only the first chunk and then stops

### ISSUE THREAD

**Issue by AlanTnr** [rg3/youtube-dl#13000]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**
- [x] At least skimmed ...
- [x] [Searched] ... the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)

---

youtube-dl was recently modified for arte.tv, in view of bug reports #12837 and #12852.  

Now youtube-dl does recognize arte.tv.  However, in the following case, it only downloads the first chunk of an emission.  

This example attempts to download the fifth emission in the six-part series "Temoin sous Silence."  youtube-dl only downloads the first "chunk" (...-A.mp4) and then stops.  This chunk lasts only 1m 37s, whereas the whole emission would be nearly an hour long.  I imagine youtube-dl should continue downloading the succeeding chunks ...B.mp4, ...C.mp4, ..., and then concatenate them.

Thank you for this great program!

BookPro% ydl -v 'http://www.arte.tv/fr/videos/057427-005-A/temoin-sous-silence-5-6'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.arte.tv/fr/videos/057427-005-A/temoin-sous-silence-5-6']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.01
[debug] Python version 2.7.2 - Darwin-12.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[arte.tv:+7] temoin-sous-silence-5-6: Downloading webpage
[arte.tv:+7] temoin-sous-silence-5-6: Downloading JSON metadata
[arte.tv:+7] temoin-sous-silence-5-6: Checking HTTPS_SQ_1 video format URL
[arte.tv:+7] temoin-sous-silence-5-6: Checking HTTPS_EQ_1 video format URL
[arte.tv:+7] temoin-sous-silence-5-6: Checking HLS_XQ_1 video format URL
[arte.tv:+7] temoin-sous-silence-5-6: Checking HTTPS_HQ_1 video format URL
[arte.tv:+7] temoin-sous-silence-5-6: Checking HTTPS_MQ_1 video format URL
[debug] Invoking downloader on u'https://arteptweb-a.akamaihd.net/am/ptweb/057000/057400/057427-005-A_EXT_SQ_2_VF-STF_02991149_MP4-2200_AMM-PTWEB_EXTRAIT_jwvJRxpxI.mp4'
[download] Destination: Témoin sous silence (5_6)-057427-005-A.mp4
[download] 100% of 29.17MiB in 01:32

BookPro% ls -ls T*
59744 -rw-r--r--  1 xxx  yyy  30587749 Apr 13 22:21 Témoin sous silence (5_6)-057427-005-A.mp4

**Comment by dstftw** [comment]
It downloads exactly same video that is played in browser. There are no more videos available on this page.
