### ISSUE TITLE
Possible to use the '--referer' option in Python scripts?

### ISSUE THREAD

**Issue by vaibhav101** [rg3/youtube-dl#13009]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

I am trying to download a domain restricted (embed-only) Vimeo video by embedding youtube-dl in a python script.

From the CLI, I can write
`youtube-dl --referer siteFromWhichIGotTheLink.com https://player.vimeo.com/video/189295917`
to download this video.

But I have been unable to find such an option for embedding youtube-dl in a Python script

This is what my script looks like at the moment:

```
import youtube_dl

ydl_opts = {'outtmpl' : unicode('vid-name.mp4'), 'referer' : 'http://xyz.com'}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://player.vimeo.com/video/189295917'])
```

**Comment by dstftw** [comment]
Put it as HTTP header in `utils.std_headers`.

**Comment by vaibhav101** [comment]
Thanks a lot, it works now.

For anyone unsure of how to do what @dstftw just said:
1. Open the file <Python_directory>\Lib\site-packages\youtube_dl\utils.py
2. Find the dictionary 'std_headers'
3. Add the key-value pair 'referer' : 'http://embedSite.com' to it
4. Done!

**Comment by flysee** [comment]
But it's global settings.How to set it up when the different site? @vaibhav101 @dstftw

**Comment by vaibhav101** [comment]
> it's global settings

That's right. You could either let that stay (it doesn't really affect downloading from other websites), or remove it once you are done with your script.

**Comment by simpss** [comment]
as this was the first response from google. I'll update this issue with a solution that doesn't require the file change in site-packages.

We're essentially doing the same thing.

```python
import youtube_dl
youtube_dl.utils.std_headers['Referer'] = "http://your.referer.here/"

....
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
     .....
```

@flysee this would also allow you to change it on the fly, in between downloads.

**Comment by flysee** [comment]
Yeah,thx a lot! @simpss

**Comment by DavidLin3** [comment]
if you use yt-dlp in Python Scripts, you can add 'Referer' in http_headers opts.
`from yt_dlp import YoutubeDL

headers = {
    'Referer': 'http://xyz.com',
}
opts = {
  'http_headers': headers,
}
ydl = YoutubeDL(opts)
ydl.download(['https://player.vimeo.com/video/189295917'])
`

**Comment by dirkf** [comment]
>...
`opts = {
  'http_headers': headers,
}`
...


That doesn't work in any version of _youtube-dl_ so far. A valid solution [was already provided](https://github.com/ytdl-org/youtube-dl/issues/13009#issuecomment-375724086).
