### ISSUE TITLE
[Site support] (certain) SPIEGEL TV videos require to dig into a frame

### ISSUE THREAD

**Issue by Wikinaut** [rg3/youtube-dl#13006]
Certain SPIEGEL TV pages.

A current example:

Pages like

*  http://www.spiegel.de/sptv/spiegeltv/sechzehneichen-psychothriller-mit-heike-makatsch-a-1146263.html

have their video Url in a frame. Youtube-dl has to dig into that and then extract to a form such as 
* http://www.spiegel.tv/filme/alleskino-sechzehneichen/

which then can be used as target url for yt-dl (the second url works fine).

I don't know, if this step of conversion/extraction can be fixed programmatically, but I suggest this site support request. (Pls. close the issue, if this could not be fixed in yt-dl.)

**Comment by dstftw** [comment]
No longer available.
