### ISSUE TITLE
Download multiple HTML5 video tags

### ISSUE THREAD

**Issue by Candlestone** [rg3/youtube-dl#1300]
At http://firstautodesk.wordpress.com/assemblies/ there are a number of videos, and giving youtube-dl that URL only downloads the first video. If a page has multiple HTML5 video tags, it would be neat if youtube-dl would treat it as a playlist somehow.

**Comment by remitamine** [comment]
supported since v2016.10.02(https://github.com/rg3/youtube-dl/commit/bd2644120526429783c55e885f7042633826d7da)
