### ISSUE TITLE
[issue re-appeared] Windows %HOMEPATH% error, shows unsupported format character 'H'

### ISSUE THREAD

**Issue by iripu** [rg3/youtube-dl#13008]
### Make sure you are using the *latest* version:
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

```

F:\>youtube-dl -v https://www.youtube.com/watch?v=ZVQfR27ISjM
[debug] System config: []
[debug] User config: ['--no-mtime', '--console-title', '-o', 'C:\\%HOMEPATH%\\Desktop\\%(title)s-%(height)sp.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=ZVQfR27ISjM']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-84348-gdb7a05d, ffprobe N-84348-gdb7a05d
[debug] Proxy map: {}
[youtube] ZVQfR27ISjM: Downloading webpage
[youtube] ZVQfR27ISjM: Downloading video info webpage
[youtube] ZVQfR27ISjM: Extracting video information
[youtube] {22} signature length 40.40, html5 player vflppxuSE
[youtube] {43} signature length 40.40, html5 player vflppxuSE
[youtube] {18} signature length 40.40, html5 player vflppxuSE
[youtube] {36} signature length 40.40, html5 player vflppxuSE
[youtube] {17} signature length 40.40, html5 player vflppxuSE
[youtube] {137} signature length 40.40, html5 player vflppxuSE
[youtube] {248} signature length 40.40, html5 player vflppxuSE
[youtube] {136} signature length 40.40, html5 player vflppxuSE
[youtube] {247} signature length 40.40, html5 player vflppxuSE
[youtube] {135} signature length 40.40, html5 player vflppxuSE
[youtube] {244} signature length 40.40, html5 player vflppxuSE
[youtube] {134} signature length 40.40, html5 player vflppxuSE
[youtube] {243} signature length 40.40, html5 player vflppxuSE
[youtube] {133} signature length 40.40, html5 player vflppxuSE
[youtube] {242} signature length 40.40, html5 player vflppxuSE
[youtube] {160} signature length 40.40, html5 player vflppxuSE
[youtube] {278} signature length 40.40, html5 player vflppxuSE
[youtube] {140} signature length 40.40, html5 player vflppxuSE
[youtube] {171} signature length 40.40, html5 player vflppxuSE
[youtube] {249} signature length 40.40, html5 player vflppxuSE
[youtube] {250} signature length 40.40, html5 player vflppxuSE
[youtube] {251} signature length 40.40, html5 player vflppxuSE
ERROR: Error in output template: unsupported format character 'H' (0x48) at index 4 (encoding: 'cp1252')
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\YoutubeDL.py", line 675,
in prepare_filename
ValueError: unsupported format character 'H' (0x48) at index 4

```

---

### Description of your *issue*, suggested solution and other information

I tried to download this video: [https://www.youtube.com/watch?v=ZVQfR27ISjM](https://www.youtube.com/watch?v=ZVQfR27ISjM).

Shows error `unsupported format character 'H' (0x48) at index 4`

My config has this line:

`-o "C:\%HOMEPATH%\Desktop\%(title)s-%(height)sp.%(ext)s"`

If I comment that line it works. My homepath is: `C:\Users\ripu`
[Same bug was reported by me and it was fixed](https://github.com/rg3/youtube-dl/issues/12556), now re-appeared.

**Comment by dstftw** [comment]
This won't fix. Use `$` for env variables in configuration file.

**Comment by iripu** [comment]
Great. Example on Readme.md still has `C:\%HOMEPATH%`, you should update that.
