### ISSUE TITLE
may any issue after google account new login page?

### ISSUE THREAD

**Issue by jomyhuang** [rg3/youtube-dl#13003]
may any issue after google account new login page?

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--download-archive', 'archive.txt', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.youtube.com/playlist?list=PLl2I-JN_VQ3IYO4lsJN9KQW1wZ3EDA5l4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.5.2 - Darwin-16.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Logging in
[youtube:playlist] PLl2I-JN_VQ3IYO4lsJN9KQW1wZ3EDA5l4: Downloading webpage
[download] Downloading playlist: BWPRO
[youtube:playlist] playlist BWPRO: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] Downloading login page
[youtube] Logging in
[youtube] 1-MP_rw4CzA: Downloading webpage
[youtube] 1-MP_rw4CzA: Downloading embed webpage
[youtube] 1-MP_rw4CzA: Refetching age-gated info webpage
ERROR: 1-MP_rw4CzA: YouTube said: This video is private.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1388, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: 1-MP_rw4CzA: YouTube said: This video is private.

**Comment by dstftw** [comment]
Duplicate of #12927.
