### ISSUE TITLE
Facebook Live streams cannot be downloaded, only MPD manifest is downloaded

### ISSUE THREAD

**Issue by nyuszika7h** [rg3/youtube-dl#13005]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v --ignore-config 'https://www.facebook.com/TinitaStoesel/videos/vb.319498788156732/1216713528435249/?type=3&theater'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', 'https://www.facebook.com/TinitaStoesel/videos/vb.319498788156732/1216713528435249/?type=3&theater']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.6.1 - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg N-85653-gb4330a0, ffprobe N-85653-gb4330a0
[debug] Proxy map: {}
[facebook] 1216713528435249: Downloading webpage
[debug] Invoking downloader on 'https://video-vie1-1.xx.fbcdn.net/hvideo-ash5/v/rsj-8ajufLiq6Hwbn4qLX/live-dash/dash-abr4/1216713535101915.mpd?_nc_rl=AfBlhwENxcvk74Ko&oh=d410d77d24b83e6ac4124f1681d2e0b5&oe=59110169'
[download] Destination: FRANKFURT  Live from the final show on my #GotMeStartedTOUR, thank you all ...-1216713528435249.mpd
[download] 100% of 5.50KiB in 00:00
```

---

### Description of your *issue*, suggested solution and other information

I'm trying to download a Facebook live stream, but all youtube-dl does is download the MPD manifest, which is not very helpful.

**Comment by dstftw** [comment]
MPD livestreams are not supported.
