### ISSUE TITLE
YouTube DASH 1080p & ffmpeg causes stuttering

### ISSUE THREAD

**Issue by qw3rty2017** [rg3/youtube-dl#13002]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\...>youtube-dl -v -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" 9xYLXHx3g80
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '9xYLXHx3g80']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[youtube] 9xYLXHx3g80: Downloading webpage
[youtube] 9xYLXHx3g80: Downloading video info webpage
[youtube] 9xYLXHx3g80: Extracting video information
[youtube] 9xYLXHx3g80: Downloading MPD manifest
[youtube] 9xYLXHx3g80: Downloading MPD manifest
[debug] Invoking downloader on [URL]
[dashsegments] Total fragments: 337
[download] Destination: Show and tell for ASMR-9xYLXHx3g80.f137.mp4
[download] 100% of 572.48MiB in 06:29
[debug] Invoking downloader on [URL]
[dashsegments] Total fragments: 170
[download] Destination: Show and tell for ASMR-9xYLXHx3g80.f140.m4a
[download] 100% of 25.46MiB in 01:31
[ffmpeg] Merging formats into "Show and tell for ASMR-9xYLXHx3g80.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Show and tell for ASMR-9xYLXHx3g80.f137.mp4' -i 'file:Show and tell for ASMR-9xYLXHx3g80.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Show and tell for ASMR-9xYLXHx3g80.temp.mp4'
Deleting original file Show and tell for ASMR-9xYLXHx3g80.f137.mp4 (pass -k to keep)
Deleting original file Show and tell for ASMR-9xYLXHx3g80.f140.m4a (pass -k to keep)
```
---

Example video: https://www.youtube.com/watch?v=9xYLXHx3g80

---

When downloading fragmented DASH videos from YouTube (1080p) and using ffmpeg (I tested ffmpeg 3.2.4, ffmpeg 2.8.4 and ffmpeg N-85750-ga75ef15) the resulting video starts stuttering after 5 seconds.
I also tried avconv v11.7 with avprobe v11.7 which does not cause this problem.

**Comment by dstftw** [comment]
Most likely the problem is in your player.

**Comment by qw3rty2017** [comment]
I tried VLC (on two different PCs), Media Player Classic HC and the Samsung Android Player. The problem occurs in all those players.

I also noticed a difference in filesize:
Show and tell for ASMR-9xYLXHx3g80 **avconv v11.7**, avprobe v11.7, ffmpeg 2.8.4.mp4
-> No stuttering, **612.587 KB**
Show and tell for ASMR-9xYLXHx3g80 **ffmpeg 2.8.4**
-> Stutters, **613.013 KB**
Show and tell for ASMR-9xYLXHx3g80 **ffmpeg 3.2.4**, ffprobe 3.2.4
-> Stutters, **613.013 KB**
Show and tell for ASMR-9xYLXHx3g80 **ffmpeg N-85750-ga75ef15**, ffprobe N-85750-ga75ef15
-> Stutters, **613.013 KB**

There seem to be DASH videos with and without "dashsegments". **It only happens on videos with "dashsegments" and 1080p.**

To rule out windows I downloaded the same way on Debian Jessie (GNU/Linux 4.9.20-std-1 x86_64) with youtube-dl version 2017.05.01 and  exe versions: ffmpeg 3.2.4-1, ffprobe 3.2.4-1. The resulting file turned out to be the same 613.013 KB and it stutters as well.

**Comment by dstftw** [comment]
Plays fine with mpv. If you think there is a bug in ffmpeg report it to ffmpeg not here.
