### ISSUE TITLE
Site support: coursehunters.net

### ISSUE THREAD

**Issue by Pluralsight-test2** [rg3/youtube-dl#13014]
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.07**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Site support request (request for adding support for a new site)

---
### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://coursehunters.net/course/udemy-angular-4-2-the-complete-guide

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://coursehunters.net/course/udemy-angular-4-2-the-complete-guide']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.07
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[generic] udemy-angular-4-2-the-complete-guide: Requesting header
WARNING: Falling back on generic information extractor.
[generic] udemy-angular-4-2-the-complete-guide: Downloading webpage
[generic] udemy-angular-4-2-the-complete-guide: Extracting information
WARNING: [generic] udemy-angular-4-2-the-complete-guide: Failed to parse JSON Invalid control character at: line 6 column 144 (char 247)
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpt73_83v_\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpt73_83v_\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpt73_83v_\build\youtube_dl\YoutubeDL.py", line 1896, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpt73_83v_\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpt73_83v_\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpt73_83v_\build\youtube_dl\extractor\generic.py", line 2738, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpt73_83v_\build\youtube_dl\extractor\common.py", line 2279, in _parse_jwplayer_data
TypeError: 'str' object does not support item assignment

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Single video: https://vs1.coursehunters.net/udemy-angular4/001.mp4
- Single video: https://vs1.coursehunters.net/udemy-angular4/011.mp4
- Single video: https://vs1.coursehunters.net/udemy-angular4/101.mp4
- Single video: https://vs1.coursehunters.net/egghead-angular-2-di/01.mp4
- Single video: https://vs1.coursehunters.net/egghead-angular-2-di/07.mp4
- Single video: https://vs1.coursehunters.net/fm-angular2/_lesson1.mp4
- Single video: https://vs1.coursehunters.net/fm-angular2/_lesson35.mp4

- Playlist: https://coursehunters.net/course/udemy-angular-4-2-the-complete-guide
- Playlist: https://coursehunters.net/course/angular2-frontendmasters
---

### Description of your *issue*, suggested solution and other information
coursehunters.net is a website that provides access to full video courses for development and design from a lot of course providers

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
