### ISSUE TITLE
programming hook for getting info_dict

### ISSUE THREAD

**Issue by d0u9** [rg3/youtube-dl#13017]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Hello,  everybody,

I want to embed youtube-dl into my project, and I want to obtain the **info_dict** before the actually download. I checked `youtube_dl/YoutubeDL.py` but find noting. There only exists a `forcejson` option related to this purpose. I can write a simple logger and filter the dumpled messages to obtain this json string. However, this implementation is not clean and graceful.

So, is there some hooks can help?

**Comment by dstftw** [comment]
`YoutubeDL.extract_info(url, download=False)`.
