### ISSUE TITLE
Skip videos with errors in Playlist

### ISSUE THREAD

**Issue by thornhill** [rg3/youtube-dl#13033]
youtube-dl stops once it reaches a file with an error is there a way to alleviate this and skip the error in the playlist .
dev@security [~/Music/Jim Reeves] ○                                   [15:14:59]
> youtube-dl PL970F05250E73F279 -x --audio-format mp3
[youtube:playlist] PL970F05250E73F279: Downloading webpage
[download] Downloading playlist: 100 Songs by Jim Reeves
[youtube:playlist] PL970F05250E73F279: Downloading page #1
[youtube:playlist] playlist 100 Songs by Jim Reeves: Downloading 115 videos
[download] Downloading video 1 of 115
[youtube] iWwssySbMJ0: Downloading webpage
[youtube] iWwssySbMJ0: Downloading video info webpage
[youtube] iWwssySbMJ0: Extracting video information
[download] Destination: Jim Reeves - The Flowers,The Sunset,The Trees.-iWwssySbMJ0.m4a
[download] 100% of 2.06MiB in 00:01
[ffmpeg] Correcting container in "Jim Reeves - The Flowers,The Sunset,The Trees.-iWwssySbMJ0.m4a"
[ffmpeg] Destination: Jim Reeves - The Flowers,The Sunset,The Trees.-iWwssySbMJ0.mp3
Deleting original file Jim Reeves - The Flowers,The Sunset,The Trees.-iWwssySbMJ0.m4a (pass -k to keep)
[download] Downloading video 2 of 115
[youtube] nECoA-uVGfw: Downloading webpage
[youtube] nECoA-uVGfw: Downloading video info webpage
[youtube] nECoA-uVGfw: Extracting video information
[youtube] nECoA-uVGfw: Downloading MPD manifest
[download] Destination: Jim Reeves - I Love You Because-nECoA-uVGfw.webm
[download] 100% of 3.82MiB in 00:03
[ffmpeg] Destination: Jim Reeves - I Love You Because-nECoA-uVGfw.mp3
Deleting original file Jim Reeves - I Love You Because-nECoA-uVGfw.webm (pass -k to keep)
[download] Downloading video 3 of 115
[youtube] 9AqESKOaeGk: Downloading webpage
[youtube] 9AqESKOaeGk: Downloading video info webpage
[youtube] 9AqESKOaeGk: Extracting video information
[download] Destination: Jim Reeves ~ Distant Drums-9AqESKOaeGk.webm
[download] 100% of 3.22MiB in 00:02
[ffmpeg] Destination: Jim Reeves ~ Distant Drums-9AqESKOaeGk.mp3
Deleting original file Jim Reeves ~ Distant Drums-9AqESKOaeGk.webm (pass -k to keep)
[download] Downloading video 4 of 115
[youtube] Smlaq1ezQRM: Downloading webpage
[youtube] Smlaq1ezQRM: Downloading video info webpage
[youtube] Smlaq1ezQRM: Extracting video information
[download] Destination: Jim Reeves ~ He'll Have To Go-Smlaq1ezQRM.webm
[download] 100% of 2.69MiB in 00:02
[ffmpeg] Destination: Jim Reeves ~ He'll Have To Go-Smlaq1ezQRM.mp3
Deleting original file Jim Reeves ~ He'll Have To Go-Smlaq1ezQRM.webm (pass -k to keep)
[download] Downloading video 5 of 115
[youtube] r_sU0pAE-fE: Downloading webpage
[youtube] r_sU0pAE-fE: Downloading video info webpage
[youtube] r_sU0pAE-fE: Extracting video information
[download] Destination: Welcome To My World - Jim Reeves-r_sU0pAE-fE.m4a
[download] 100% of 2.17MiB in 00:01
[ffmpeg] Correcting container in "Welcome To My World - Jim Reeves-r_sU0pAE-fE.m4a"
[ffmpeg] Destination: Welcome To My World - Jim Reeves-r_sU0pAE-fE.mp3
Deleting original file Welcome To My World - Jim Reeves-r_sU0pAE-fE.m4a (pass -k to keep)
[download] Downloading video 6 of 115
[youtube] H2fyFumisiU: Downloading webpage
[youtube] H2fyFumisiU: Downloading video info webpage
[youtube] H2fyFumisiU: Extracting video information
[download] Destination: The Blizzard - Jim Reeves - Tall Tales Short Tempers-H2fyFumisiU.m4a
[download] 100% of 3.12MiB in 00:02
[ffmpeg] Correcting container in "The Blizzard - Jim Reeves - Tall Tales Short Tempers-H2fyFumisiU.m4a"
[ffmpeg] Destination: The Blizzard - Jim Reeves - Tall Tales Short Tempers-H2fyFumisiU.mp3
Deleting original file The Blizzard - Jim Reeves - Tall Tales Short Tempers-H2fyFumisiU.m4a (pass -k to keep)
[download] Downloading video 7 of 115
[youtube] 5B1nm1Co9wA: Downloading webpage
[youtube] 5B1nm1Co9wA: Downloading video info webpage
[youtube] 5B1nm1Co9wA: Extracting video information
[download] Destination: Suppertime - Jim Reeves-5B1nm1Co9wA.m4a
[download] 100% of 2.60MiB in 00:02
[ffmpeg] Correcting container in "Suppertime - Jim Reeves-5B1nm1Co9wA.m4a"
[ffmpeg] Destination: Suppertime - Jim Reeves-5B1nm1Co9wA.mp3
Deleting original file Suppertime - Jim Reeves-5B1nm1Co9wA.m4a (pass -k to keep)
[download] Downloading video 8 of 115
[youtube] lngT2EMhdlo: Downloading webpage
[youtube] lngT2EMhdlo: Downloading video info webpage
[youtube] lngT2EMhdlo: Extracting video information
[youtube] lngT2EMhdlo: Downloading MPD manifest
[download] Destination: Jim Reeves - Stand at Your Window-lngT2EMhdlo.m4a
[download] 100% of 1.49MiB in 00:01
[ffmpeg] Correcting container in "Jim Reeves - Stand at Your Window-lngT2EMhdlo.m4a"
[ffmpeg] Destination: Jim Reeves - Stand at Your Window-lngT2EMhdlo.mp3
Deleting original file Jim Reeves - Stand at Your Window-lngT2EMhdlo.m4a (pass -k to keep)
[download] Downloading video 9 of 115
[youtube] ucvcoWMFmW8: Downloading webpage
[youtube] ucvcoWMFmW8: Downloading video info webpage
[youtube] ucvcoWMFmW8: Extracting video information
[download] Destination: Jim Reeves - Adios Amigo-ucvcoWMFmW8.m4a
[download] 100% of 2.30MiB in 00:01
[ffmpeg] Correcting container in "Jim Reeves - Adios Amigo-ucvcoWMFmW8.m4a"
[ffmpeg] Destination: Jim Reeves - Adios Amigo-ucvcoWMFmW8.mp3
Deleting original file Jim Reeves - Adios Amigo-ucvcoWMFmW8.m4a (pass -k to keep)
[download] Downloading video 10 of 115
[youtube] U9R5bQhxnTM: Downloading webpage
[youtube] U9R5bQhxnTM: Downloading video info webpage
ERROR: U9R5bQhxnTM: YouTube said: "JIM REEVES - HAVE THINE ..."
The YouTube account associated with this video has been terminated due to multiple third-party notifications of copyright infringement.

**Comment by dstftw** [comment]
This is expected. Use `-i`.
