### ISSUE TITLE
Site support request: pluzz.francetv.fr became www.france.tv

### ISSUE THREAD

**Issue by Animis09** [rg3/youtube-dl#13034]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

---

```
youtube-dl -v https://www.france.tv/france-3/plus-belle-la-vie/saison-13/138979-plus-belle-la-vie.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.france.tv/france-3/plus-belle-la-vie/saison-13/138979-plus-belle-la-vie.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.07
[debug] Proxy map: {}
[generic] 138979-plus-belle-la-vie: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 138979-plus-belle-la-vie: Downloading webpage
[generic] 138979-plus-belle-la-vie: Extracting information
ERROR: Unsupported URL: https://www.france.tv/france-3/plus-belle-la-vie/saison-13/138979-plus-belle-la-vie.html
Traceback (most recent call last):
  File "/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/youtube-dl/youtube_dl/extractor/generic.py", line 2834, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.france.tv/france-3/plus-belle-la-vie/saison-13/138979-plus-belle-la-vie.html
```

### Description of your *issue*, suggested solution and other information

As I mentioned in the title, the website pluzz.francetv.fr has changed its domain name to www.france.tv. Can you add this new site into YDL? 
Thank you for your help.

**Comment by jalba69** [comment]
pluzz platfrom used before is not more, now all gets regrouped on the france.tv website, they regroup quite some channels replays ( and live streams too ) 

https://www.france.tv/france-2/
https://www.france.tv/france-3/
https://www.france.tv/france-5/
https://www.france.tv/france-4/
https://www.france.tv/france-o/ < it's a o not a zero

live streams at those url's ( in case it matters for something ) : 
https://www.france.tv/france-2/direct.html
https://www.france.tv/france-3/direct.html
https://www.france.tv/france-5/direct.html
https://www.france.tv/france-4/direct.html
https://www.france.tv/france-o/direct.html


a few examples of new URL's for the replays : 

https://www.france.tv/france-2/journal-13h00/140985-edition-du-lundi-8-mai-2017.html
https://www.france.tv/documentaires/histoire/136517-argentine-les-500-bebes-voles-de-la-dictature.html
https://www.france.tv/documentaires/histoire/136611-la-face-cachee-de-naples.html
https://www.france.tv/jeux-et-divertissements/divertissements/133965-le-web-contre-attaque.html
https://www.france.tv/france-2/infrarouge/112981-ils-sont-gendarmes.html
https://www.france.tv/france-o/investigations/119007-investigations.html
https://www.france.tv/france-o/foudre/saison-5/131845-un-nouveau-depart.html
https://www.france.tv/france-5/entree-libre/saison-6/137033-entree-libre.html
https://www.france.tv/france-4/une-saison-au-zoo/saison-7/134929-une-saison-au-zoo.html
https://www.france.tv/france-3/nils-holgersson/139027-le-propulseur.html

Also those are from the same group  : http://education.francetv.fr/  with for example as url : 
http://education.francetv.fr/matiere/decouverte-des-sciences/ce2/video/memoire-d-ecran-le-nucleaire
Might work the same way as others and easy to regroup too.

Thank you very much for the work done on this amazing tool,
best regards to all the guys involved in this project.
