### ISSUE TITLE
[Site support request] new france.tv replay and specific subsites

### ISSUE THREAD

**Issue by ymartin59** [rg3/youtube-dl#13038]
### Description

France Television sites have been full reworked: https://www.france.tv/

Please add support for videos hosted in:
- Replay: https://www.france.tv/
- Éducation: http://education.francetv.fr/
- Zouzous: http://www.zouzous.fr/
- Ludo: http://www.ludo.fr/
- FranceInfo direct: http://www.francetvinfo.fr/
- FranceInfo Geopolis: http://geopolis.francetvinfo.fr/
- FranceInfo CultureBox: http://culturebox.francetvinfo.fr/
- FranceInfo outre-mer: http://la1ere.francetvinfo.fr/
- FranceInfo Régions: http://france3-regions.francetvinfo.fr/
- francetvsport: http://sport.francetvinfo.fr/
- FranceInfo nouvelles écritures IRL http://irl.nouvelles-ecritures.francetv.fr/
- FranceInfo nouvelles écritures Studio 4 http://studio-4.nouvelles-ecritures.francetv.fr/

Whaouh so many hostnames and brands for a single media group... and I have left apart http://www.lesite.tv/edutheque/ because its access is restricted to teachers.

Many thanks in advance

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by ymartin59** [comment]
OK so I will submit a request per site... but most used same broadcasting.
