### ISSUE TITLE
the three formats failed to merge. The log says ffmpeg merged them but the output file listed does not exist

### ISSUE THREAD

**Issue by macks2008** [rg3/youtube-dl#13049]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.09** 
comment: I can even provide a screenshot of the pertinent CMD.exe output if you like 😛

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
comment: I'm currently reading the bugs section. I will have finished reading it thoroughly enough to be within reason by the time I submit this though.
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
comment: I did search, and I didn't find anything. I have to admit though, I wasn't quite sure what search terms to use. I hope I didn't miss anything, but feel free to reference a similar issue if I did.

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
<"youtube-dl -v https://www.youtube.com/watch?v=zlM_ESz0yhI > verbose.log" executed in CMD.exe>
<verbose.log begins here>
[youtube] zlM_ESz0yhI: Downloading webpage
[youtube] zlM_ESz0yhI: Downloading video info webpage
[youtube] zlM_ESz0yhI: Extracting video information
[youtube] zlM_ESz0yhI: Downloading MPD manifest
[debug] Invoking downloader on 'https://r6---sn-gjo-2ial.googlevideo.com/videoplayback?initcwndbps=2428750&gir=yes&source=youtube&pl=19&signature=8F78AEA755C887F0DF36556671B9B05EC5020617.96073C809A0CDA976A2C74FC4FD707939028571F&upn=-5NayOHDhsk&mime=video%2Fwebm&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&id=o-AJd5aQYHatK14jUOjj53zS3YYr9d3VsJd1Y2X_eM9E8c&itag=247&key=yt6&ip=216.15.65.253&keepalive=yes&dur=167.066&ei=HoYTWdPAOYjF8wTgyrCICw&lmt=1493087553825994&clen=13243074&ms=au&mt=1494451645&mv=m&expire=1494473343&requiressl=yes&ipbits=0&mm=31&mn=sn-gjo-2ial&ratebypass=yes'
[download] Destination: MMD UndertaleStronger Than You  (ver. Frisk)-zlM_ESz0yhI.f247.webm

[download]   0.0% of 12.63MiB at 25.89KiB/s ETA 08:19
[download]   0.0% of 12.63MiB at 77.67KiB/s ETA 02:46
[download]   0.1% of 12.63MiB at 181.24KiB/s ETA 01:11
[download]   0.1% of 12.63MiB at 221.57KiB/s ETA 00:58
[download]   0.2% of 12.63MiB at 370.18KiB/s ETA 00:34
[download]   0.5% of 12.63MiB at 743.41KiB/s ETA 00:17
[download]   1.0% of 12.63MiB at  1.46MiB/s ETA 00:08 
[download]   2.0% of 12.63MiB at  2.40MiB/s ETA 00:05 
[download]   4.0% of 12.63MiB at  3.08MiB/s ETA 00:03 
[download]   7.9% of 12.63MiB at  4.16MiB/s ETA 00:02 
[download]  15.8% of 12.63MiB at  4.87MiB/s ETA 00:02 
[download]  31.7% of 12.63MiB at  5.57MiB/s ETA 00:01 
[download]  63.3% of 12.63MiB at  6.00MiB/s ETA 00:00 
[download]  95.0% of 12.63MiB at  6.37MiB/s ETA 00:00 
[download] 100.0% of 12.63MiB at  6.44MiB/s ETA 00:00 
[download] 100% of 12.63MiB in 00:02                  
[debug] Invoking downloader on 'https://r6---sn-gjo-2ial.googlevideo.com/videoplayback?initcwndbps=2428750&gir=yes&source=youtube&pl=19&signature=3CC5EC8667AE196EAE812F15E29423EF7A494AC2.AC44C4BE715489D778D58DE9BF6B7DC9FFADFE70&upn=-5NayOHDhsk&mime=audio%2Fwebm&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&id=o-AJd5aQYHatK14jUOjj53zS3YYr9d3VsJd1Y2X_eM9E8c&itag=251&key=yt6&ip=216.15.65.253&keepalive=yes&dur=167.141&ei=HoYTWdPAOYjF8wTgyrCICw&lmt=1493087324334566&clen=2914249&ms=au&mt=1494451645&mv=m&expire=1494473343&requiressl=yes&ipbits=0&mm=31&mn=sn-gjo-2ial&ratebypass=yes'
[download] Destination: MMD UndertaleStronger Than You  (ver. Frisk)-zlM_ESz0yhI.f251.webm

[download]   0.0% of 2.78MiB at 498.49KiB/s ETA 00:05
[download]   0.1% of 2.78MiB at  1.46MiB/s ETA 00:01 
[download]   0.2% of 2.78MiB at  2.27MiB/s ETA 00:01 
[download]   0.5% of 2.78MiB at  4.87MiB/s ETA 00:00 
[download]   1.1% of 2.78MiB at  1.89MiB/s ETA 00:01 
[download]   2.2% of 2.78MiB at  1.50MiB/s ETA 00:01 
[download]   4.5% of 2.78MiB at  2.29MiB/s ETA 00:01 
[download]   9.0% of 2.78MiB at  3.14MiB/s ETA 00:00 
[download]  18.0% of 2.78MiB at  4.71MiB/s ETA 00:00 
[download]  35.9% of 2.78MiB at  6.09MiB/s ETA 00:00 
[download]  71.9% of 2.78MiB at  6.82MiB/s ETA 00:00 
[download] 100.0% of 2.78MiB at  7.22MiB/s ETA 00:00 
[download] 100% of 2.78MiB in 00:00                  
[ffmpeg] Merging formats into "MMD UndertaleStronger Than You  (ver. Frisk)-zlM_ESz0yhI.webm"
[debug] ffmpeg command line: ffmpeg -y -i 'file:MMD UndertaleStronger Than You  (ver. Frisk)-zlM_ESz0yhI.f247.webm' -i 'file:MMD UndertaleStronger Than You  (ver. Frisk)-zlM_ESz0yhI.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:MMD UndertaleStronger Than You  (ver. Frisk)-zlM_ESz0yhI.temp.webm'
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.
---
<my explanation begins here>

    What the problem is: for whatever reason, when I run the downloader with the aarguments specified in the code block above, I end up with three .webm files, but none of which have both audio and video tracks in one file. One is the video track (it has .2247 appended to the file name but before the file extension), one is the audio track (this one has .2251 appended the same way as the first one), and one doesn't even seem to be in a playable format for VLC media player, I.e. I open it and nothing happens besides the file being added to the active playlist (this one has .temp at the end).
    How it could be fixed: I don't know how everything is supposed to work, but I suggest doing whatever  necessary to make ff
    How your proposed solution would look like: a resulting file that is playable and has both video and audio tracks, rather than three split files. Honestly the dysfunction here makes me wonder if I missed something, but I don't know what it would be

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by macks2008** [comment]
@dstftw I did post the full output? I ran it with -v for verbose logging and used > to redirect the output to a file. I'm not sure what else you expect me to do. It's Microshit Windows...

**Comment by macks2008** [comment]
oh, apparently some of the output that I was expecting would go to the log file instead still went to the command prompt window. My bad. Not sure how I can make it print to file properly though? I suppose I could transcribe the text manually, but that seems like a really inefficient option best saved for last resort.

**Comment by macks2008** [comment]
@dstftw OP updated to include the missing information. Please reopen the issue when you get this.

**Comment by dstftw** [comment]
Update ffmpeg.

**Comment by macks2008** [comment]
@dstftw How would I go about doing that? I don't even fully understand what it does... other than apparently leave videos in pieces when it doesn't work?
