### ISSUE TITLE
Add support for france.tv (pluzz replacement)

### ISSUE THREAD

**Issue by aurelg** [rg3/youtube-dl#13042]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.france.tv/france-5/c-dans-l-air/137029-emission-du-lundi-8-mai-2017.html

The formerly supported french public televisions website `pluzz.francetv.fr` [has been replaced](https://www.nextinpact.com/news/104228-france-tv-france-televisions-regroupe-ses-contenus-et-promet-mises-a-jour-tres-regulieres.htm) by `france.tv`. `youtube-dl` cannot download video from this new website yet:

```
youtube-dl https://www.france.tv/france-5/c-dans-l-air/137029-emission-du-lundi-8-mai-2017.html
[FranceTV] 137029-emission-du-lundi-8-mai-2017: Downloading webpage
[FranceTV] 157542173: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by remitamine** [comment]
> Impossible de lire la vidéo.

can't be played in the browser.

**Comment by aurelg** [comment]
Sorry, the link I posted was valid yesterday. Check this one instead: https://www.france.tv/actualites-et-societe/politique/137117-speciale-c-politique.html

I believe this bug should not be closed.

**Comment by remitamine** [comment]
if it's not working for you then post full verbose output with the latest version.
```
youtube-dl https://www.france.tv/actualites-et-societe/politique/137117-speciale-c-politique.html
[FranceTV] 137117-speciale-c-politique: Downloading webpage
[FranceTV] 157542203: Downloading video JSON
[FranceTV] 157542203: Downloading geo restriction info
[FranceTV] 157542203: Downloading m3u8 information
[FranceTV] 157542203: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 861
[download] Destination: On change de monde-157542203.mp4
[download]   0.0% of ~1.59GiB at 91.54KiB/s ETA 06:51:38
```

**Comment by aurelg** [comment]
Sorry, for the report. It work now. Thanks for your help - it seems I needed it ! ^^
