### ISSUE TITLE
ICE - Media

### ISSUE THREAD

**Issue by viisauksena** [rg3/youtube-dl#13058]
### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Germanys main Railway Operator "Deutsche Bahn" (DB) has know free Wifi and also some Entertainment on Board.

---
On German ICE Train you have a Media System - it would be awesome if it would be possible to download Video or audiobooks - to finish listening while leaving train

they do Kinda javascript magic, also the given Links cant be downloaded twice. (so copy the functioning link from browser to curl wont work - didnt try to use correct headers actually)

Note that they reroute the DNS of portal.imice.de to a local adress, which in my case happen to be on 172.18.1.110

here is one Example .. 
https://portal.imice.de/#/ContentPage/1259480820/3700000000002
https://portal.imice.de/aod-audiobooks/d6a3f0398fbbd3370b6e322b099cf05f/59152bd4/37-000000000006/002_Urlaubsdusche_Spanisch_Lektion02.m4a

the error which occurs on curl is 410 http error - Content gone

i add a complete save of the page including the obfuscatet javascript
[some example with all files included](http://s000.tinyupload.com/index.php?file_id=34353744615138764078)

one other example request has this headers 

```Host: portal.imice.de
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
X-Features: {"video":["hds","mp4","ogg"],"audio":["hds","m4a","mpeg","ogg"],"game":["flash","html5"],"device":"Sonstiges Device"}
Referer: https://portal.imice.de/
Cookie: dbsession=d383328d.54f4a96957871; scr=1280x0800; vzn=ICE275
Connection: keep-alive
```

**Comment by dstftw** [comment]
To request support you must either provide an example URL that is accessible from global network or provide a way to access this local URL from global network.

**Comment by viisauksena** [comment]
this will mostly never happen - and if - its because i , or someone else made a proxy for some hours of triptime

**Comment by pelim** [comment]
video is impossible because it is DRM protected but for audio books there are already a python script https://gist.github.com/xflr6/759737dc06b290a009352d3307782a2b
