### ISSUE TITLE
Make youtube-dl available as flatpak package

### ISSUE THREAD

**Issue by ExTechOp** [rg3/youtube-dl#13064]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Please make youtube-dl available as a flatpak package, to make latest version more promptly available on all supported platforms. For example, the latest version currently available as a rpm package on Fedora 25 is 2017.04.17 — this of course makes it difficult to report problems without resorting to manual installing.

**Comment by dstftw** [comment]
Just use any method from [here](https://github.com/rg3/youtube-dl#installation).

**Comment by alex285** [comment]
hello @dstftw  

> Just use any method from [here](https://github.com/rg3/youtube-dl#installation).

that wont work good on Fedora Silverblue (Atomic) installations. apart we lose the auto-updates, we also need to install codecs on OSTree image, that isn't very good practice, so still a Flatpak youtube-dl would be welcome

**Comment by bilelmoussaoui** [comment]
I can help with that.
