### ISSUE TITLE
TheScene Fails to Download

### ISSUE THREAD

**Issue by remlap** [rg3/youtube-dl#13061]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl https://thescene.com/watch/vogue/73-questions-selena-gomez?pl_id=73-questions-season-3 -F -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://thescene.com/watch/vogue/73-questions-selena-gomez?pl_id=73-questions-season-3', '-F', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.09
[debug] Python version 3.5.3 - Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2, rtmpdump 2.4
[debug] Proxy map: {}
[TheScene] 73-questions-selena-gomez: Downloading webpage
[TheScene] 73-questions-selena-gomez: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('quality',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/remlap/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/home/remlap/.local/lib/python3.5/site-packages/youtube_dl/extractor/thescene.py", line 54, in _real_extract
    } for f in info['sources']]
  File "/home/remlap/.local/lib/python3.5/site-packages/youtube_dl/extractor/thescene.py", line 54, in <listcomp>
    } for f in info['sources']]
KeyError: 'quality'
Traceback (most recent call last):
  File "/home/remlap/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/home/remlap/.local/lib/python3.5/site-packages/youtube_dl/extractor/thescene.py", line 54, in _real_extract
    } for f in info['sources']]
  File "/home/remlap/.local/lib/python3.5/site-packages/youtube_dl/extractor/thescene.py", line 54, in <listcomp>
    } for f in info['sources']]
KeyError: 'quality'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/remlap/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/home/remlap/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 446, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('quality',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://thescene.com/watch/vogue/73-questions-selena-gomez?pl_id=73-questions-season-3
- Single video: http://video.vogue.com/watch/73-questions-selena-gomez

### Description of the *issue*.

Videos fail to download, extractor seems broken?

**Comment by Hrxn** [comment]
Yes, same here.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', 'https://thescene.com/watch/vogue/73-questions-selena-gomez?pl_id=73-questions-season-3', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.05.09
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[TheScene] 73-questions-selena-gomez: Downloading webpage
[TheScene] 73-questions-selena-gomez: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('quality',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
```

Previously: #12235 `[TheScene] ERROR: Unable to extract info json`

Video from last issue gives the same new error.

Site probably changed *again*
