### ISSUE TITLE
Download through proxy does not work with new site FranceTV

### ISSUE THREAD

**Issue by ymartin59** [rg3/youtube-dl#13071]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.09**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ export http_proxy=http://178.32.218.91:80
$ ~/bin/youtube-dl -v --proxy $http_proxy --write-description --write-info-json https://www.france.tv/france-5/sid-le-petit-scientifique/137375-sauvons-la-souche.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--proxy', u'http://178.32.218.91:80', u'--write-description', u'--write-info-json', u'--ignore-errors', u'https://www.france.tv/france-5/sid-le-petit-scientifique/137375-sauvons-la-souche.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.09
[debug] Python version 2.7.12 - Linux-3.2.40-i686-with-glibc2.0
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {u'http': u'http://178.32.218.91:80', u'https': u'http://178.32.218.91:80'}
[FranceTV] 137375-sauvons-la-souche: Downloading webpage
ERROR: Unable to download webpage: <urlopen error Tunnel connection failed: 500 Internal Server Error> (caused by URLError(error('Tunnel connection failed: 500 Internal Server Error',),))
  File "/var/services/homes/admin/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/var/services/homes/admin/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2106, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/var/services/homes/admin/bin/youtube-dl/youtube_dl/utils.py", line 1090, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
```

### Description

Download of a video through an HTTP proxy no longer work with `FranceTV` site whereas it was used to work with `pluzz` and same proxy. Of course I checked that the HTTP proxy I used works properly for other usage. I am not sure if trouble may be worked-around in `youtube-dl` itself if proxy usage is detected and rejected server-side.

Again many thanks for the great job you do with this tool.

**Comment by dstftw** [comment]
Your proxy is either dead or blocked.
