### ISSUE TITLE
Do post-processing in background

### ISSUE THREAD

**Issue by jemand771** [rg3/youtube-dl#13085]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I am downloading large amounts of music from a playlist, converting it to mp3 with the `-x` flag. The first video gets downloaded and then converted into mp3. (As specified in the command).
The second download starts after the first conversion has finished, the third after the second, and so on.

Now, lets assume it's downloading half of the time and converting half of the time (i know, that really depends on cpu and internet conneciton, which btw are both really bad in my case)
Half of the time, the cpu is doing nothing (almost) because youtube-dl is busy downloading, abd the other half of the time, the internet connection is bored because ffmpeg is busy.
That doubles execution time, which is bad. (Well not too bad, but it could be improved)

I know this might get complicated with veryfying the output files, but maybe there is some way.

That's exactly what i'm doing inside of a shell script, just to mention:
`youtube-dl --download-archive archive.txt -k -i --no-post-overwrite -f bestaudio/webm/m4a -x --audio-format mp3 "$url"`

I think there is no need for command output because this isn't really specific for any case.
And btw, youtube-dl is awesome anyway, thank you :)

**Comment by dstftw** [comment]
Just run several instances of youtube-dl.

**Comment by jemand771** [comment]
this doesn't seem practical to me at all.

would i have to run youtube-dl with playlist to get all the video ids (i know thats possible) and start a new shell for every of those urls or is there an easy way?

The playlist contains about 1300 videos, and i don't download them all in one run

**Comment by jemand771** [comment]
oh, i think i misunderstood something. I'm sorry

Thank you for your quick response :)
