### ISSUE TITLE
Youtube-dl giving wrong youtube title

### ISSUE THREAD

**Issue by mattjis** [rg3/youtube-dl#13084]
**Steps to reproduce:**
1. Run command: `youtube-dl --skip-download --write-info-json --output example "https://www.youtube.com/watch?v=S5C76qN4y8k"`
2. Open `example.info.json` and notice `"fulltitle": "YAYAYI  333%"`

**REAL:** "YAYAYI 333%"
**YTDL:** "YAYAYI  333%"

Youtube-DL has randomly added 2 extra spaces to this title...

**Comment by dstftw** [comment]
No, it's not. `YAYAYI  333%` is the real title. Check the page source if you don't believe.
