### ISSUE TITLE
Youtube/Google Play Movie Purchases Garbled/Cutoff after 10 seconds

### ISSUE THREAD

**Issue by japzone1** [rg3/youtube-dl#13081]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl "https://www.youtube.com/watch?v=efBgXjbd2uQ" --cookie cookies.txt -f 142 -o CACW.mp4 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=efBgXjbd2uQ', '--cookie', 'cookies.txt', '-f', '142', '-o', 'CACW.mp4', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2017.05.14
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-84679-gd65b595, ffprobe N-84679-gd65b595
[debug] Proxy map: {}
[youtube] efBgXjbd2uQ: Downloading webpage
[youtube] efBgXjbd2uQ: Downloading video info webpage
[youtube] efBgXjbd2uQ: Extracting video information
[youtube] {53} signature length 40.40, html5 player vflxXnk_G
[youtube] {60} signature length 40.40, html5 player vflxXnk_G
[youtube] {52} signature length 40.40, html5 player vflxXnk_G
[youtube] {145} signature length 40.40, html5 player vflxXnk_G
[youtube] {224} signature length 40.40, html5 player vflxXnk_G
[youtube] {225} signature length 40.40, html5 player vflxXnk_G
[youtube] {144} signature length 40.40, html5 player vflxXnk_G
[youtube] {222} signature length 40.40, html5 player vflxXnk_G
[youtube] {223} signature length 40.40, html5 player vflxXnk_G
[youtube] {143} signature length 40.40, html5 player vflxXnk_G
[youtube] {142} signature length 40.40, html5 player vflxXnk_G
[youtube] {161} signature length 40.40, html5 player vflxXnk_G
[youtube] {148} signature length 40.40, html5 player vflxXnk_G
[youtube] {149} signature length 40.40, html5 player vflxXnk_G
[youtube] {150} signature length 40.40, html5 player vflxXnk_G
[youtube] {259} signature length 40.40, html5 player vflxXnk_G
[youtube] {261} signature length 40.40, html5 player vflxXnk_G
[youtube] {326} signature length 40.40, html5 player vflxXnk_G
WARNING: Unknown codec dtse[youtube] {329} signature length 40.40, html5 player vflxXnk_G
WARNING: Unknown codec eac3[youtube] {350} signature length 40.40, html5 player vflxXnk_G
[youtube] {351} signature length 40.40, html5 player vflxXnk_G
[youtube] {352} signature length 40.40, html5 player vflxXnk_G
[youtube] efBgXjbd2uQ: Downloading MPD manifest
[debug] Invoking downloader on 'https://r2---sn-8xgp1vo-2iak.googlevideo.com/videoplayback?expire=1494759980&upn=msPGblYCiYo&ei=zOUXWfCDFoPH8gT9mYi4AQ&key=yt6&mime=video%2Fmp4&initcwndbps=2818750&mn=sn-8xgp1vo-2iak&pcm2cms=yes&clen=276500446&gir=yes&lmt=1474658195500730&dur=8860.433&ctier=A&source=youtube&gcr=us&pfa=5&sparams=clen%2Ccmbypass%2Cctier%2Cdur%2Cei%2Cgcr%2Cgir%2Chightc%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpfa%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&ipbits=0&itag=142&mm=31&ip=108.2.204.126&mv=m&mt=1494738317&ms=au&hightc=yes&pl=16&keepalive=yes&cmbypass=yes&id=o-AOsZtWZAkRgXbiQkRvVMupKh9wpjTcTMpiL5vBmNdBho&signature=CFBEA4EFD73FFAF6EDC0E35117482848BC0E736C.A2EC4E04FAE479BE3E366F2E843DFFF6D52DF09E&ratebypass=yes'
[download] Destination: CACW.mp4
[download] 100% of 263.69MiB in 00:32
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=efBgXjbd2uQ

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I've been trying to download some purchased videos. The downloading process goes well enough, and I end up with a file at the expected size and with the expected codecs. However whenever I play the downloaded videos I get 10 seconds in and then the video just hangs. I've tested this with multiple different videos and the result is the same, 10 seconds in and it hangs. Potplayer, VLC, MPC-HC, and more all showed similar results. They get 10 seconds in and then either, video freezes/becomes garbled but the player doesn't notice and thinks it's still playing, the player itself freezes/crashes, or the player reports "this file is corrupt". I've tried downloading different qualities, and even downloaded the separate tracks to make sure it wasn't ffmpeg screwing something up, but the result was the same. Even the audio tracks cut out at exactly 10 seconds in.

**Comment by dstftw** [comment]
It's either DRM protected or broken YouTube side (in that case you won't be able to play it in browser).
