### ISSUE TITLE
Doubt developing extractors

### ISSUE THREAD

**Issue by AllanDaemon** [rg3/youtube-dl#13095]
I have a doubt about **developing extractors**.

When creating or developing an extractor, can I save data (state) in a instance of the extractor (like `class MyExtractorIE(InfoExtractor)`?  In all the code I saw until now, it seems to avoid saving state in the IE object, working with a more functional approach and passing data just as functions arguments. Many helper methods in the class `InfoExtractor` (in `extractor/common.py`) kinda follow this behaving like static methods.

So, in an extractor, can I save data like the video id and others parameters in the object (eg. `self.webpage = fetched_webpage`), or assuming that each download item creates a new instance of an `InfoExtractor` is wrong, or something else is wrong.

**Comment by dstftw** [comment]
Extractors are reused so you can't keep any data that affects extraction between downloads. Needless to say it does not even make any sense to store it.
