### ISSUE TITLE
How to determine which audio track is the best quality one?

### ISSUE THREAD

**Issue by fafner5** [rg3/youtube-dl#13105]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

---

---

### Description of your *issue*, suggested solution and other information

Determining the best video track is pretty straightforward.
However when it comes to choosing the best audio track i am confused. I've found that 3 different audio tracks exists on some videos (track 140, 171 and 251). These 3 tend to have very similar bit-rates if not the same bit-rates and it differs from video to video which one of these has the highest bit-rate. For example 

this video (https://www.youtube.com/watch?v=NI5dAMYNZpc) has this:
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 2.31MiB
171          webm       audio only DASH audio  128k , vorbis@128k, 2.21MiB
251          webm       audio only DASH audio  137k , opus @160k, 2.35MiB
140 and 171 have exactly the same bit-rate and 251 is higher than both of them but not by a lot.

this video (https://www.youtube.com/watch?v=pb3IdLdIc6s) has this:
140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k, 3.89MiB
251          webm       audio only DASH audio  142k , opus @160k, 3.85MiB
171          webm       audio only DASH audio  144k , vorbis@128k, 3.86MiB
here 251 and 171 are extremely close but 171 is higher.

I've found a video where 140 is higher than both 171 and 251 but don't remember the video.

So these 3 tracks seems to change places in having the highest bit-rates. And they all use different audio codecs? and compression? I've found that 251 is usually the highest, 171 middle and 140 lowest. So how do i determine which one of these tracks offer the best audio quality. I do not care about file size nor do i care compatibility all i care about is audio quality. Up until know i have downloaded 2 separate versions of the same video one with 140 and the other with 251 but this has been doubling up the space each video takes on my HDD and now that i found that even 171 can have the highest bit-rate i am confused.
Which track would "bestaudio" choose? the one with the highest bit-rate, file size or the one with the highest track number?

**Comment by Hrxn** [comment]
Track number? You mean that first number? That is just the IDs used by YouTube, I think they call it `itag` or something. Has nothing to do with quality. You could maybe say that higher `itag` means newer format, i.e. has been added to YouTube more recently.

Bit-rate is important, but also compatibility. Depends on what you want to do with these files. If it's just about quality, just go with Opus and the highest bit-rate.

**Comment by dstftw** [comment]
[Metadata preference for sorting formats](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/common.py#L1111-L1126).
