### ISSUE TITLE
Download doesn't work with timestamp in youtube link

### ISSUE THREAD

**Issue by GorganRazvan** [rg3/youtube-dl#13102]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

https://www.youtube.com/watch?v=2Yh1IJLvKPM&t=3626s
---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

The problem starts like this:

I did a yt-audio alias in Linux:

alias yt-audio='youtube-dl --no-playlist --extract-audio --audio-format mp3 --audio-quality 0 --embed-thumbnail -o "/media/something/Stuff/Windows/Downloads/youtube-dl/audio/random/%(title)s.%(ext)s" '

The this is that while I listen to a song and I observe that I like, I shoot the < yt-audio link > command. Now, there are times when the timestamp remain in the link, looking like this:

https://www.youtube.com/watch?v=2Yh1IJLvKPM&t=3626s

And, it seems this one disturb my command and stops at [debug] without download.

Message I get after it hit: yt-audio https://www.youtube.com/watch?v=2Yh1IJLvKPM&t=3626s

something@something-HP-EliteBook-8540p:~$ yt-audio https://www.youtube.com/watch?v=2Yh1IJLvKPM&t=3626s
[3] 27186
something@something-HP-EliteBook-8540p:~$ [debug] System config: []
[debug] User config: [u'-u', u'PRIVATE', u'-c', u'--newline', u'-v', u'--ignore-errors']
[debug] Custom config: []
[debug] Command-line args: [u'--no-playlist', u'--extract-audio', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'--embed-thumbnail', u'-o', u'/media/something/Stuff/Windows/Downloads/youtube-dl/audio/random/%(title)s.%(ext)s', u'https://www.youtube.com/watch?v=2Yh1IJLvKPM']

It would be cool to eliminate the last &t=3626s timestamp automatically. Without it, the command works perfectly:)

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
