### ISSUE TITLE
Download stops at 5,10,15,etc. percent

### ISSUE THREAD

**Issue by johnxian1** [rg3/youtube-dl#13111]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ √] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.14**

### Before submitting an *issue* make sure you have:
- [ √] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [√ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [√ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.05.14
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--newline', '--verbose', 'http://www.letv.com/ptv/vplay/643584.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.05.14
[debug] Python version 3.4.4 - Windows-2012ServerR2-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 643584: Requesting header
[redirect] Following redirect to http://www.le.com/ptv/vplay/643584.html
[debug] Using fake IP 36.138.34.65 (CN) as X-Forwarded-For.
[Le] 643584: Downloading webpage
[Le] 643584: Downloading flash playJson data
[Le] 643584: Download JSON metadata for format 1300
[Le] 643584: Downloading m3u8 information for format 1300
[Le] 643584: Download JSON metadata for format 350
[Le] 643584: Downloading m3u8 information for format 350
[Le] 643584: Download JSON metadata for format 1000
[Le] 643584: Downloading m3u8 information for format 1000
[debug] Invoking downloader on 'data:application/vnd.apple.mpegurl;base64,I0VYVE0zVQ0KI0VYVC1YLVZFUlNJT046Mw0KI0VYVC1YLU1FRElBLVNFUVVFTkNFOjANCiNFWFQtWC1BTExPVy1DQUNIRTpZRVMNCiNFWFQtWC1UQVJHRVREVVJBVElPTjoyMA0KI0VYVC1MRVRWLU0zVTgtVFlQRTpWT0QNCiNFWFQtTEVUVi1NM1U4LVZFc.............................'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 387
[download] Destination: ߧୀѽ׭643584.mp4
[download]   0.0% of ~30.67MiB at Unknown speed ETA 17:22
[download]   0.0% of ~30.67MiB at Unknown speed ETA 05:57
[download]   0.0% of ~30.67MiB at Unknown speed ETA 02:33
[download]   0.0% of ~30.67MiB at  1.07MiB/s ETA 01:38
[download]   0.1% of ~30.67MiB at  2.07MiB/s ETA 00:48
[download]   0.2% of ~30.67MiB at  2.17MiB/s ETA 00:30
[download]   0.3% of ~30.67MiB at  2.80MiB/s ETA 00:23
[download]   0.3% of ~30.67MiB at  2.80MiB/s ETA 00:23
[download]   0.2% of ~42.53MiB at  2.80MiB/s ETA 00:50
[download]   0.2% of ~42.53MiB at  2.80MiB/s ETA 00:48
[download]   0.2% of ~42.53MiB at  2.80MiB/s ETA 00:46
[download]   0.2% of ~42.53MiB at  1.07MiB/s ETA 00:48
[download]   0.3% of ~42.53MiB at  2.07MiB/s ETA 00:41
[download]   0.3% of ~42.53MiB at  2.17MiB/s ETA 00:36
[download]   0.5% of ~42.53MiB at  2.95MiB/s ETA 00:28
[download]   0.5% of ~42.53MiB at  3.27MiB/s ETA 00:26
[download]   0.5% of ~42.53MiB at  3.27MiB/s ETA 00:26
[download]   0.2% of ~121.42MiB at  3.27MiB/s ETA 01:33
[download]   0.2% of ~121.42MiB at  3.27MiB/s ETA 01:32
[download]   0.2% of ~121.42MiB at  3.27MiB/s ETA 01:31
[download]   0.2% of ~121.42MiB at  1.07MiB/s ETA 01:35
[download]   0.2% of ~121.42MiB at  2.07MiB/s ETA 01:29
[download]   0.2% of ~121.42MiB at  2.10MiB/s ETA 01:26
[download]   0.3% of ~121.42MiB at  2.15MiB/s ETA 01:20
[download]   0.4% of ~121.42MiB at  3.40MiB/s ETA 01:02
[download]   0.6% of ~121.42MiB at  4.82MiB/s ETA 00:46
[download]   0.8% of ~121.42MiB at  6.21MiB/s ETA 00:36
[download]   0.8% of ~121.42MiB at  6.21MiB/s ETA 00:36
[download]   0.4% of ~223.30MiB at  6.21MiB/s ETA 01:16
[download]   0.4% of ~223.30MiB at  6.21MiB/s ETA 01:16
[download]   0.4% of ~223.30MiB at  6.21MiB/s ETA 01:15
[download]   0.4% of ~223.30MiB at  1.01MiB/s ETA 01:18
[download]   0.4% of ~223.30MiB at  1.96MiB/s ETA 01:17
[download]   0.4% of ~223.30MiB at  2.04MiB/s ETA 01:18
[download]   0.5% of ~223.30MiB at  2.77MiB/s ETA 01:16
[download]   0.5% of ~223.30MiB at  4.19MiB/s ETA 01:11
[download]   0.6% of ~223.30MiB at  6.48MiB/s ETA 01:01
[download]   0.9% of ~223.30MiB at 10.56MiB/s ETA 00:47
[download]   1.0% of ~223.30MiB at 12.63MiB/s ETA 00:41
[download]   1.0% of ~223.30MiB at 12.63MiB/s ETA 00:41
[download]   0.8% of ~305.00MiB at 12.63MiB/s ETA 01:01
[download]   0.8% of ~305.00MiB at 12.63MiB/s ETA 01:01
[download]   0.8% of ~305.00MiB at 12.63MiB/s ETA 01:01
[download]   0.8% of ~305.00MiB at  1.07MiB/s ETA 01:02
[download]   0.8% of ~305.00MiB at  2.22MiB/s ETA 01:02
[download]   0.8% of ~305.00MiB at  2.25MiB/s ETA 01:03
[download]   0.8% of ~305.00MiB at  3.02MiB/s ETA 01:03
[download]   0.8% of ~305.00MiB at  3.59MiB/s ETA 01:03
[download]   0.9% of ~305.00MiB at  5.27MiB/s ETA 01:00
[download]   1.1% of ~305.00MiB at  8.39MiB/s ETA 00:53
[download]   1.3% of ~305.00MiB at 12.96MiB/s ETA 00:45
[download]   1.3% of ~305.00MiB at 12.96MiB/s ETA 00:45
[download]   1.2% of ~317.15MiB at 12.96MiB/s ETA 00:50
[download]   1.2% of ~317.15MiB at 12.96MiB/s ETA 00:50
[download]   1.2% of ~317.15MiB at 12.96MiB/s ETA 00:50
[download]   1.2% of ~317.15MiB at  1.07MiB/s ETA 00:51
[download]   1.3% of ~317.15MiB at  2.06MiB/s ETA 00:51
[download]   1.3% of ~317.15MiB at  2.10MiB/s ETA 00:51
[download]   1.3% of ~317.15MiB at  2.15MiB/s ETA 00:53
[download]   1.3% of ~317.15MiB at  3.35MiB/s ETA 00:52
[download]   1.4% of ~317.15MiB at  4.78MiB/s ETA 00:52
[download]   1.6% of ~317.15MiB at  7.87MiB/s ETA 00:48
[download]   1.6% of ~317.15MiB at  7.87MiB/s ETA 00:48
[download]   1.2% of ~401.50MiB at  7.87MiB/s ETA 01:04
[download]   1.2% of ~401.50MiB at  7.87MiB/s ETA 01:04
[download]   1.2% of ~401.50MiB at  7.87MiB/s ETA 01:04
[download]   1.2% of ~401.50MiB at  1.00MiB/s ETA 01:05
[download]   1.2% of ~401.50MiB at  1.94MiB/s ETA 01:05
[download]   1.2% of ~401.50MiB at  2.10MiB/s ETA 01:05
[download]   1.3% of ~401.50MiB at  2.76MiB/s ETA 01:06
[download]   1.3% of ~401.50MiB at  4.11MiB/s ETA 01:05
[download]   1.3% of ~401.50MiB at  5.49MiB/s ETA 01:05
[download]   1.5% of ~401.50MiB at  9.30MiB/s ETA 01:00
[download]   1.7% of ~401.50MiB at 14.83MiB/s ETA 00:53
[download]   1.8% of ~401.50MiB at 16.45MiB/s ETA 00:51
[download]   1.8% of ~401.50MiB at 16.45MiB/s ETA 00:51
[download]   1.6% of ~467.34MiB at 16.45MiB/s ETA 01:02
[download]   1.6% of ~467.34MiB at 16.45MiB/s ETA 01:02
[download]   1.6% of ~467.34MiB at 16.45MiB/s ETA 01:02
[download]   1.6% of ~467.34MiB at  1.00MiB/s ETA 01:03
[download]   1.6% of ~467.34MiB at  2.07MiB/s ETA 01:03
[download]   1.6% of ~467.34MiB at  2.10MiB/s ETA 01:03
[download]   1.6% of ~467.34MiB at  2.82MiB/s ETA 01:04
[download]   1.6% of ~467.34MiB at  4.18MiB/s ETA 01:03
[download]   1.7% of ~467.34MiB at  5.61MiB/s ETA 01:03
[download]   1.8% of ~467.34MiB at  9.22MiB/s ETA 01:00
[download]   2.0% of ~467.34MiB at 15.74MiB/s ETA 00:54
[download]   2.1% of ~467.34MiB at 17.54MiB/s ETA 00:53
[download]   2.1% of ~467.34MiB at 17.54MiB/s ETA 00:53
[download]   1.8% of ~536.95MiB at 17.54MiB/s ETA 01:03
[download]   1.8% of ~536.95MiB at 17.54MiB/s ETA 01:03
[download]   1.8% of ~536.95MiB at 17.54MiB/s ETA 01:03
[download]   1.8% of ~536.95MiB at  1.07MiB/s ETA 01:03
[download]   1.8% of ~536.95MiB at  2.21MiB/s ETA 01:03
[download]   1.8% of ~536.95MiB at  2.25MiB/s ETA 01:04
[download]   1.8% of ~536.95MiB at  3.02MiB/s ETA 01:04
[download]   1.8% of ~536.95MiB at  4.55MiB/s ETA 01:04
[download]   1.9% of ~536.95MiB at  7.00MiB/s ETA 01:03
[download]   2.0% of ~536.95MiB at 11.37MiB/s ETA 01:01
[download]   2.2% of ~536.95MiB at 18.27MiB/s ETA 00:57
[download]   2.3% of ~536.95MiB at 23.16MiB/s ETA 00:53
[download]   2.3% of ~536.95MiB at 23.16MiB/s ETA 00:53
[download]   2.0% of ~630.94MiB at 23.16MiB/s ETA 01:05
[download]   2.0% of ~630.94MiB at 23.16MiB/s ETA 01:05
[download]   2.0% of ~630.94MiB at 23.16MiB/s ETA 01:05
[download]   2.0% of ~630.94MiB at  1.07MiB/s ETA 01:06
[download]   2.0% of ~630.94MiB at  1.07MiB/s ETA 01:06
[download]   2.0% of ~630.94MiB at  1.47MiB/s ETA 01:07
[download]   2.0% of ~630.94MiB at  2.19MiB/s ETA 01:07
[download]   2.0% of ~630.94MiB at  3.49MiB/s ETA 01:07
[download]   2.1% of ~630.94MiB at  5.56MiB/s ETA 01:07
[download]   2.1% of ~630.94MiB at  9.30MiB/s ETA 01:05
[download]   2.3% of ~630.94MiB at 15.05MiB/s ETA 01:02
[download]   2.6% of ~630.94MiB at 22.85MiB/s ETA 00:56
[download]   2.6% of ~630.94MiB at 22.85MiB/s ETA 00:56
[download]   2.4% of ~671.56MiB at 22.85MiB/s ETA 01:04
[download]   2.4% of ~671.56MiB at 22.85MiB/s ETA 01:04
[download]   2.4% of ~671.56MiB at 22.85MiB/s ETA 01:04
[download]   2.4% of ~671.56MiB at  1.07MiB/s ETA 01:05
[download]   2.4% of ~671.56MiB at  2.21MiB/s ETA 01:05
[download]   2.4% of ~671.56MiB at  1.54MiB/s ETA 01:06
[download]   2.4% of ~671.56MiB at  2.35MiB/s ETA 01:06
[download]   2.5% of ~671.56MiB at  3.75MiB/s ETA 01:06
[download]   2.5% of ~671.56MiB at  6.01MiB/s ETA 01:06
[download]   2.6% of ~671.56MiB at  9.93MiB/s ETA 01:04
[download]   2.7% of ~671.56MiB at 16.50MiB/s ETA 01:01
[download]   2.8% of ~671.56MiB at 20.97MiB/s ETA 00:59
[download]   2.8% of ~671.56MiB at 20.97MiB/s ETA 00:59
[download]   2.7% of ~708.11MiB at 20.97MiB/s ETA 01:04
[download]   2.7% of ~708.11MiB at 20.97MiB/s ETA 01:04
[download]   2.7% of ~708.11MiB at 20.97MiB/s ETA 01:04
[download]   2.7% of ~708.11MiB at  1.16MiB/s ETA 01:04
[download]   2.7% of ~708.11MiB at  1.19MiB/s ETA 01:05
[download]   2.7% of ~708.11MiB at  1.62MiB/s ETA 01:05
[download]   2.7% of ~708.11MiB at  2.44MiB/s ETA 01:05
[download]   2.7% of ~708.11MiB at  3.86MiB/s ETA 01:05
[download]   2.8% of ~708.11MiB at  5.49MiB/s ETA 01:06
[download]   2.8% of ~708.11MiB at  9.14MiB/s ETA 01:04
[download]   3.0% of ~708.11MiB at 14.83MiB/s ETA 01:02
[download]   3.1% of ~708.11MiB at 18.83MiB/s ETA 01:00
[download]   3.1% of ~708.11MiB at 18.83MiB/s ETA 01:00
[download]   3.1% of ~717.45MiB at 18.83MiB/s ETA 01:02
[download]   3.1% of ~717.45MiB at 18.83MiB/s ETA 01:02
[download]   3.1% of ~717.45MiB at 18.83MiB/s ETA 01:02
[download]   3.1% of ~717.45MiB at  1.15MiB/s ETA 01:03
[download]   3.1% of ~717.45MiB at  2.21MiB/s ETA 01:03
[download]   3.1% of ~717.45MiB at  2.25MiB/s ETA 01:03
[download]   3.1% of ~717.45MiB at  2.95MiB/s ETA 01:03
[download]   3.1% of ~717.45MiB at  4.47MiB/s ETA 01:03
[download]   3.1% of ~717.45MiB at  6.90MiB/s ETA 01:03
[download]   3.2% of ~717.45MiB at 11.12MiB/s ETA 01:02
[download]   3.3% of ~717.45MiB at 17.64MiB/s ETA 01:00
[download]   3.4% of ~717.45MiB at 18.76MiB/s ETA 01:00
[download]   3.4% of ~717.45MiB at 18.76MiB/s ETA 01:00
[download]   3.1% of ~769.38MiB at 18.76MiB/s ETA 01:06
[download]   3.1% of ~769.38MiB at 18.76MiB/s ETA 01:06
[download]   3.1% of ~769.38MiB at 18.76MiB/s ETA 01:06
[download]   3.1% of ~769.38MiB at  1.00MiB/s ETA 01:06
[download]   3.1% of ~769.38MiB at  2.07MiB/s ETA 01:06
[download]   3.1% of ~769.38MiB at  2.10MiB/s ETA 01:06
[download]   3.1% of ~769.38MiB at  2.76MiB/s ETA 01:07
[download]   3.2% of ~769.38MiB at  4.11MiB/s ETA 01:07
[download]   3.2% of ~769.38MiB at  1.12MiB/s ETA 01:18
[download]   3.3% of ~769.38MiB at  2.08MiB/s ETA 01:17
[download]   3.4% of ~769.38MiB at  3.92MiB/s ETA 01:15
ERROR: unable to download video data: timed out
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckrszvwp\build\youtube_dl\YoutubeDL.py", line 1803, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckrszvwp\build\youtube_dl\YoutubeDL.py", line 1745, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckrszvwp\build\youtube_dl\downloader\common.py", line 360, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckrszvwp\build\youtube_dl\downloader\hls.py", line 124, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckrszvwp\build\youtube_dl\downloader\fragment.py", line 97, in _download_fragment
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckrszvwp\build\youtube_dl\downloader\common.py", line 360, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckrszvwp\build\youtube_dl\downloader\http.py", line 165, in real_download
  File "C:\Python\Python34\lib\http\client.py", line 537, in read
  File "C:\Python\Python34\lib\http\client.py", line 576, in readinto
  File "C:\Python\Python34\lib\socket.py", line 378, in readinto
socket.timeout: timed out

**Comment by dstftw** [comment]
This indicated an issue with your network connection.
