### ISSUE TITLE
yt-dl as vivaldi-browser extension not working, possibly ffmpeg issue?

### ISSUE THREAD

**Issue by le-mon** [rg3/youtube-dl#13127]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Question
--

I wrote an extension for chrome/chromium to download youtube videos and convert it to mp3, and wanted to use it in [vivaldi](https://vivaldi.com) as well. 
I set up a [NativeMessagingHost](https://developer.chrome.com/extensions/nativeMessaging) in python, wich reacts to messages from the extension. 
In theory as followed:

1. go to youtube
2. check if valid video url
3. send url to NativeMessagingHost
4. use [embedded youtube-dl](https://github.com/rg3/youtube-dl/blob/master/README.md#embedding-youtube-dl) (python) to get video

chrome & chromium do what they were told to, but vivaldi doesn't like it. 
Here ist the NativeMessagingHost in python:

[ytconv-host.txt](https://github.com/rg3/youtube-dl/files/1011120/ytconv-host.txt)

the output is:
[output.txt](https://github.com/rg3/youtube-dl/files/1011121/output.txt)

and the logfile generated by the python script:
[log.txt](https://github.com/rg3/youtube-dl/files/1011124/log.txt)

I'm not sure if it's related to youtube-dl, especially the ffmpeg functions or if vivaldi has different environment var stuff etc.

I guess the problem could be traced by that line:
`ERROR: Did you mean file:file:`
Why is file named twice?

vivaldi version: 1.9.818.50 (Stable channel) (64-Bit)

**Comment by dstftw** [comment]
Add `'verbose': True` to `ydl_opts`, then run ffmpeg command that fails directly from you env to figure out the reason.

**Comment by le-mon** [comment]
the script runs fine if startet directly from console. 
Through nativemessaging in vivaldi something goes wrong, verbose says:

`[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.14
[debug] Python version 3.6.1 - Linux-4.10.13-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3, rtmpdump 2.4
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1942, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 530, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/usr/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 208, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Did you mean **file:file**:/home/user/Downloads/thevideotitle.m4a?

I don't know if it's related to vivaldi or youtube-dl. 
`
