### ISSUE TITLE
I Got this error This i missed any thing ?

### ISSUE THREAD

**Issue by InnocentOongZ** [rg3/youtube-dl#13131]
root@Holfz:/usr/local/bin# youtube-dl https://www.youtube.com/watch?v=Ta-va7qfhnE
[youtube] Ta-va7qfhnE: Downloading webpage
[youtube] Ta-va7qfhnE: Downloading video info webpage
[youtube] Ta-va7qfhnE: Extracting video information
[youtube] Ta-va7qfhnE: Downloading js player vfl8jhACg
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1162, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1085, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1138, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'oE["do"](a,67)'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u'Unsupported JS expression u\'oE["do"](a,67)\'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
root@Holfz:/usr/local/bin# ^C
root@Holfz:/usr/local/bin# pip3 install -U youtube-dl
-bash: pip3: command not found
root@bro-vm:/usr/local/bin# pip install -U youtube-dl
Requirement already up-to-date: youtube-dl in /usr/local/lib/python2.7/dist-packages
Cleaning up...

**Comment by InnocentOongZ** [comment]
Please make it close. i Sloved

**Comment by Sheogorath2** [comment]
How have you solved it? I have the same problem.

**Comment by InnocentOongZ** [comment]
I reinstall it. it work some video

I wait for this Issue too #13123

**Comment by Oliyy** [comment]
Reinstalling doesn't work? It's YouTube they changed something which has broken it and we have to wait for fix.

**Comment by InnocentOongZ** [comment]
Yea. "Some" video it work for me

**Comment by Sheogorath2** [comment]
Update with pip and pip3 no success. Now trying with apt-get.

**Comment by Oliyy** [comment]
From what I understand, without physical code change nothing will work.

**Comment by InnocentOongZ** [comment]
apt-get no success too.

**Comment by InnocentOongZ** [comment]
We have to Wait For fix
