### ISSUE TITLE
Unable to obtain file audio codec with ffprobe

### ISSUE THREAD

**Issue by jona8690** [rg3/youtube-dl#13146]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.18.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.18.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Hi

Im trying to set up youtube-dl on my raspberry pi. I've installed ffmpeg, and used the manual install guide for youtube-dl.

Trying to run the program, and extract the audio, but it gives me some codec error. I can see from the verbose, that ffmpeg is present, which I have also verifyed myself on the system.

> pi@raspberrypi:~ $ sudo youtube-dl -x --verbose https://www.youtube.com/watch?v=nbXgHAzUWB0
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-x', u'--verbose', u'https://www.youtube.com/watch?v=nbXgHAzUWB0']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2017.05.18.1
> [debug] Python version 2.7.9 - Linux-4.4.50+-armv6l-with-debian-8.0
> [debug] exe versions: ffmpeg present, ffprobe present, rtmpdump 2.4
> [debug] Proxy map: {}
> [youtube] nbXgHAzUWB0: Downloading webpage
> [youtube] nbXgHAzUWB0: Downloading video info webpage
> [youtube] nbXgHAzUWB0: Extracting video information
> [youtube] {22} signature length 43.42, html5 player vfl8jhACg
> [youtube] {43} signature length 43.42, html5 player vfl8jhACg
> [youtube] {18} signature length 43.42, html5 player vfl8jhACg
> [youtube] {36} signature length 43.42, html5 player vfl8jhACg
> [youtube] {17} signature length 43.42, html5 player vfl8jhACg
> [youtube] {137} signature length 43.42, html5 player vfl8jhACg
> [youtube] {248} signature length 43.42, html5 player vfl8jhACg
> [youtube] {136} signature length 43.42, html5 player vfl8jhACg
> [youtube] {247} signature length 43.42, html5 player vfl8jhACg
> [youtube] {135} signature length 43.42, html5 player vfl8jhACg
> [youtube] {244} signature length 43.42, html5 player vfl8jhACg
> [youtube] {134} signature length 43.42, html5 player vfl8jhACg
> [youtube] {243} signature length 43.42, html5 player vfl8jhACg
> [youtube] {133} signature length 43.42, html5 player vfl8jhACg
> [youtube] {242} signature length 43.42, html5 player vfl8jhACg
> [youtube] {160} signature length 43.42, html5 player vfl8jhACg
> [youtube] {278} signature length 43.42, html5 player vfl8jhACg
> [youtube] {140} signature length 43.42, html5 player vfl8jhACg
> [youtube] {171} signature length 43.42, html5 player vfl8jhACg
> [youtube] {249} signature length 43.42, html5 player vfl8jhACg
> [youtube] {250} signature length 43.42, html5 player vfl8jhACg
> [youtube] {251} signature length 43.42, html5 player vfl8jhACg
> [debug] Invoking downloader on u'https://r3---sn-ovgq0oxu-j2ie.googlevideo.com/videoplayback?mt=1495128329&clen=4068946&key=yt6&requiressl=yes&gir=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&keepalive=yes&beids=%5B9466591%5D&initcwndbps=5772500&id=o-AKxgSeluBDD13eNqZgAK0oBgpjuZq5i9pwXOzrHaFTww&pl=17&dur=250.061&mime=audio%2Fwebm&ms=au&source=youtube&mv=m&mm=31&ipbits=0&mn=sn-ovgq0oxu-j2ie&itag=251&expire=1495150022&lmt=1449812687269932&ei=ZtkdWYy3F9TXYs7akYAJ&upn=kjUKBSeDZq8&ip=130.226.70.90&signature=5F7820D65CCD91BE21E42A2060B3F56654135437.856EDFF2FBCECED2F18EA26EEEEF09728723A761&ratebypass=yes'
> [download] Axwell _ Ingrosso - Sun Is Shining-nbXgHAzUWB0.webm has already been downloaded
> [download] 100% of 3.88MiB
> [debug] ffmpeg command line: ffprobe -show_streams 'file:Axwell _ Ingrosso - Sun Is Shining-nbXgHAzUWB0.webm'
> ERROR: WARNING: unable to obtain file audio codec with ffprobe
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1942, in post_process
>     files_to_delete, info = pp.run(info)
>   File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 243, in run
>     raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
> PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe
>

**Comment by dstftw** [comment]
Post the output of `ffprobe -show_streams 'file:Axwell _ Ingrosso - Sun Is Shining-nbXgHAzUWB0.webm'`.

**Comment by jona8690** [comment]
Returns:
> Illegal instruction

**Comment by dstftw** [comment]
Meaning you ffmpeg is broken.

**Comment by jona8690** [comment]
Ah, great, only spent half a night trying to get that installed.

Thank you for quick support!
