### ISSUE TITLE
Issue while trying to download EVERY video (Signature extraction failed)

### ISSUE THREAD

**Issue by Javinator9889** [rg3/youtube-dl#13144]
While trying to get every video, I'm getting this error:

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/javialonso/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    else:
  File "/home/javialonso/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1004, in _extract_signature_function
    },
  File "/home/javialonso/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1057, in <lambda>
    assert os.path.basename(func_id) == func_id
  File "/home/javialonso/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/home/javialonso/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/javialonso/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression 'oE["do"](a,67)'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError('Unsupported JS expression \'oE["do"](a,67)\'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output

**Comment by NixBoy** [comment]
For fuck sake, stop closing and tell us what to do.
I've been searching for hours and cannot find anything in the search shit..

Please...

**Comment by Hrxn** [comment]
Stop opening duplicate issues...

**Comment by bealparslan** [comment]
Fixed, please update youtube-dl.

**Comment by NixBoy** [comment]
@bealparslan I hope you're not joking, ill update it now.

**Comment by Javinator9889** [comment]
@bealparslan update with pip?

**Comment by NixBoy** [comment]
Fuck yes, its fixed.. just update.

Don't make this duplicate.. close it so ppl will see.

**Comment by NixBoy** [comment]
do do youtube-dl -U

or 

/usr/local/bin/youtube-dl -U

**Comment by Javinator9889** [comment]
@NixBoxy update with pip?

**Comment by Javinator9889** [comment]
@NixBoy update with pip?

**Comment by deadrop** [comment]
pip install --upgrade youtube-dl==2017.5.18.1

**Comment by NixBoy** [comment]
@Javinator9889 

just put this in console:/usr/local/bin/youtube-dl -U
you might not have pip.

**Comment by Javinator9889** [comment]
__DONE!!__ 
Just use _python3 -m pip install --upgrade_ for upgrading 
- Use _youtube-dl -U_ for installed versions
