### ISSUE TITLE
No sound when play the video

### ISSUE THREAD

**Issue by nikko24** [rg3/youtube-dl#13157]
Hi, i have problem with sound.

I play video via the omxplayer, video work good, but there is no sound output.

Script: omxplayer -o hdmi `youtube-dl -f "youtube URL"` OR .... -o both ....

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by nikko24** [comment]
Please reopen my Issue.
