### ISSUE TITLE
[feature request] Do not print NA in filenames if metadata does not exist for it.

### ISSUE THREAD

**Issue by rieje** [rg3/youtube-dl#13153]
I use an output format suitable for Youtube videos, but for other sites, they don't use some of the metadata (or at least properly). In the videos from these sites, I often get several `NA` in the filename (e.g. `Cat video - NA (NA).mp4`). 

How about an option to not print the metadata at all if it would report `NA` otherwise?

**Comment by dstftw** [comment]
What's the point? How come `Cat video -  ().mp4` is better?
