### ISSUE TITLE
Can't download YouTube subs - TFA failure

### ISSUE THREAD

**Issue by AcouBass** [rg3/youtube-dl#13151]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.18.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.18.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
pi@raspberrypi:~ $ youtube-dl -i -u censoreduser@gmail.com :ytsubs -p 'censoredpassword' -2 745042 --dateafter now-10days -v --download-archive ~/youtubearchive
[debug] System config: []
[debug] User config: [u'--prefer-free-formats', u'-c', u'--output', u'~/Videos/youtubes/%(title)s %(id)s.%(ext)s', u'--no-mtime', u'--download-archive', u'~/pipes/youtubearchive']
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'-u', u'PRIVATE', u':ytsubs', u'-p', u'PRIVATE', u'-2', u'745042', u'--dateafter', u'now-10days', u'-v', u'--download-archive', u'/home/pi/youtubearchive']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.18.1
[debug] Python version 2.7.9 - Linux-4.9.22-v7+-armv7l-with-debian-8.0
[debug] exe versions: ffmpeg 3.2.2-1, ffprobe 3.2.2-1, rtmpdump 2.4-n78-git3a1e20c-ppa8
[debug] Proxy map: {}
[youtube:subscriptions] Downloading login page
[youtube:subscriptions] Looking up account info
[youtube:subscriptions] Logging in
[youtube:subscriptions] Submitting TFA code
WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error
WARNING: Unable to extract CheckCookie URL
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: Youtube Subscriptions

```

---

### Description of your *issue*, suggested solution and other information

I use the pasted script (usually in the form of a .sh script, but have been running from the command line to test) to yank my YouTube subscriptions on a fairly often basis, however for recent versions this has stopped working, with the HTTP Error 500 shown. Just to test, I also tried with --cookies, as well as with an app password from my Google account, though generally I use my 'regular' Google password.

**Comment by bmintz** [comment]
@dstftw what issue does this one duplicate?
