### ISSUE TITLE
Python API: how to --force-ipv4

### ISSUE THREAD

**Issue by fenollp** [rg3/youtube-dl#13150]
Hi there, love your work, thank you a lot for your time.

I can't find the Python version of option `--force-ipv4` anywhere.
Also I can't find much documentation on the Python API in general.

Is this implemented in the Python API?
If not, where should I start to add it?

Thanks

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L257

**Comment by strafe** [comment]
Since the link above no longer shows the relevant line, the option to do this is [`source_address`](https://github.com/rg3/youtube-dl/blob/84f085d4bdb66ee025fb337bcd571eab7469da97/youtube_dl/YoutubeDL.py#L262).

Example usage if your server's public IPv4 address is `1.1.1.1`:
```Python
with youtube_dl.YoutubeDL({"source_address": "1.1.1.1"}) as ydl:
	ydl.download(["https://www.youtube.com/watch?v=eZqrGXgHHV4"])
```
