### ISSUE TITLE
UPDATE SITE : PLUZZ.FR -> FRANCE.TV

### ISSUE THREAD

**Issue by githubaobab** [rg3/youtube-dl#13165]
Hi,

Please, can you update to accept downloding from : https://www.france.tv
An example : https://www.france.tv/france-2/un-oeil-sur-la-planete/141889-cannabis-quelle-bonne-politique.html

Thanks in advance for this resquest from France !

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by githubaobab** [comment]
Sorry, thx for answer.
