### ISSUE TITLE
v.douyu.com(similar to youtube) video not able to seek

### ISSUE THREAD

**Issue by brlala** [rg3/youtube-dl#13164]
- [ x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.18.1**
- [ x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

- [ x ] Bug report (encountered problems with youtube-dl)

---
Not able to use the seek function when playing uploaded video contents at v.douyu.com
---

you -v -o - "https://v.douyu.com/show/paRbBv32jGyW6PYV"   | vlc -
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', '-', 'https://v.douyu.com/show/paRbBv32jGyW6PYV']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.05.18.1
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-85091-g23ae3cc, ffprobe N-85091-g23ae3cc
[debug] Proxy map: {}
[DouyuShow] paRbBv32jGyW6PYV: Downloading webpage
[DouyuShow] paRbBv32jGyW6PYV: Downloading JSON metadata
[DouyuShow] paRbBv32jGyW6PYV: Downloading m3u8 information
[debug] Invoking downloader on 'http://vodhls1.douyucdn.cn/live/normal_live-761727rqckCO8m1k--20170515212455/playlist.m3u8?k=c9ba0dbbd624b4f841b26859e27b7f94&t=591f3a92&u=0&ct=h5&vid=652191&d='
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 720
[download] Destination: -
[download]   0.1% of ~1.11GiB at 197.17MiB/s ETA 05:39
...
<end of log>
```

---

Even if the video is uploaded content, the video is not seek-able using the fast forward bar.

**Comment by dstftw** [comment]
`--hls-prefer-ffmpeg`.

**Comment by brlala** [comment]
> [DouyuShow] paRbBv32jGyW6PYV: Downloading webpage
> [DouyuShow] paRbBv32jGyW6PYV: Downloading JSON metadata
> [DouyuShow] paRbBv32jGyW6PYV: Downloading m3u8 information
> [download] Destination: 6个鱼翅办卡，海口户外唱歌 2017-05-15 21点场-paRbBv32jGyW6PYV.mp4
> ffmpeg version N-86175-g64ea4d1 Copyright (c) 2000-2017 the FFmpeg developers
>   built with gcc 6.3.0 (GCC)
>   configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
>   libavutil      55. 63.100 / 55. 63.100
>   libavcodec     57. 96.101 / 57. 96.101
>   libavformat    57. 72.101 / 57. 72.101
>   libavdevice    57.  7.100 / 57.  7.100
>   libavfilter     6. 90.100 /  6. 90.100
>   libswscale      4.  7.101 /  4.  7.101
>   libswresample   2.  8.100 /  2.  8.100
>   libpostproc    54.  6.100 / 54.  6.100
> Input #0, hls,applehttp, from 'http://vodhls1.douyucdn.cn/live/normal_live-761727rqckCO8m1k--20170515212455/playlist.m3u8?k=c488920bdb58f6505cfef5b3105d5b8f&t=59207768&u=0&ct=h5&vid=652191&d=':
>   Duration: 02:00:03.12, start: 1.480000, bitrate: 0 kb/s
>   Program 0
>     Metadata:
>       variant_bitrate : 0
>     Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 368x640, 25 fps, 25 tbr, 90k tbn, 50 tbc
>     Metadata:
>       variant_bitrate : 0
>     Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, mono, fltp
>     Metadata:
>       variant_bitrate : 0
> file:6涓奔缈呭姙鍗★紝娴峰彛鎴峰鍞辨瓕 2017-05-15 21鐐瑰満-paRbBv32jGyW6PYV.mp4.part: Permission denied
> 
> 
> ERROR: ffmpeg exited with code 1
