### ISSUE TITLE
[Feature-Request] - Incorporate switch to execute ffmpeg or ffplay with the link

### ISSUE THREAD

**Issue by james28909** [rg3/youtube-dl#13184]
I just spent 5 hours or better trying to figure out how to send the output from youtube-dl to ffmpeg in cmd on windows 10(64bit). i ended up using this if anyone wants it:
`for /f "delims=" %i in ('youtube-dl -g "ytsearch:**query**" -f bestaudio') do set var=%i & ffmpeg -y -i "%i%" -f opus pipe:1 | ffplay -i -`

**Comment by james28909** [comment]
or if someone has a better way to do it, please enlighten me :)

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#how-do-i-stream-directly-to-media-player
