### ISSUE TITLE
Downloaded vimeo video has no audio

### ISSUE THREAD

**Issue by ShadowLandWalker** [rg3/youtube-dl#13189]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.23**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
Download Log for url: https://thecorrespondent.com/6285/shell-made-a-film-about-climate-change-in-1991-then-neglected-to-heed-its-own-warning/692663565-875331f6

Waiting
[generic] 692663565-875331f6: Requesting header
WARNING: Could not send HEAD request to https://thecorrespondent.com/6285/shell-made-a-film-about-climate-change-in-1991-then-neglected-to-heed-its-own-warning/692663565-875331f6: HTTP Error 405: Not Allowed
[generic] 692663565-875331f6: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 692663565-875331f6: Extracting information
[download] Downloading playlist: Shell made a film about climate change in 1991 (then neglected to heed its own warning)
[generic] playlist Shell made a film about climate change in 1991 (then neglected to heed its own warning): Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[vimeo] 205917267: Downloading webpage
[vimeo] 205917267: Extracting information
[vimeo] 205917267: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 205917267: Downloading fastly_skyfire_h2 m3u8 information
[vimeo] 205917267: Downloading akfire_interconnect m3u8 information
[vimeo] 205917267: Downloading fastly_skyfire_h2 MPD information
[vimeo] 205917267: Downloading akfire_interconnect_quic MPD information
WARNING: There's no description to write.
[dashsegments] Total fragments: 286
[download] Destination: C:\Users\Bob\Downloads\YouTube-Downloader\vimeo\Climate of Concern - The film oil giant Shell made in 1991 to warn the world about climate change - De Correspondent (NA) 205917267.mp4
[download]   0.3% of ~227.63KiB at 265.30KiB/s ETA 01:10
[download]  10.0% of ~252.37MiB at 907.59KiB/s ETA 04:19
[download]  20.0% of ~251.55MiB at 920.52KiB/s ETA 03:49
[download]  30.1% of ~260.39MiB at  1.49MiB/s ETA 03:28
[download]  40.0% of ~275.40MiB at  1.34MiB/s ETA 03:10
[download]  50.0% of ~277.42MiB at 615.87KiB/s ETA 02:39
[download]  49.9% of ~277.70MiB at 615.87KiB/s ETA 02:40
[download]  50.0% of ~277.70MiB at  2.28MiB/s ETA 02:40
[download]  60.0% of ~283.58MiB at  1.23MiB/s ETA 02:11
[download]  70.0% of ~287.58MiB at  1.33MiB/s ETA 01:39
[download]  80.1% of ~291.37MiB at  2.69MiB/s ETA 01:14
[download]  90.0% of ~294.00MiB at  2.47MiB/s ETA 00:35
Download Worker Finished.
[generic] 692663565-875331f6: Requesting header
WARNING: Could not send HEAD request to https://thecorrespondent.com/6285/shell-made-a-film-about-climate-change-in-1991-then-neglected-to-heed-its-own-warning/692663565-875331f6: HTTP Error 405: Not Allowed
[generic] 692663565-875331f6: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 692663565-875331f6: Extracting information
[download] Downloading playlist: Shell made a film about climate change in 1991 (then neglected to heed its own warning)
[generic] playlist Shell made a film about climate change in 1991 (then neglected to heed its own warning): Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[vimeo] 205917267: Downloading webpage
[vimeo] 205917267: Extracting information
[vimeo] 205917267: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 205917267: Downloading fastly_skyfire_h2 m3u8 information
[vimeo] 205917267: Downloading akfire_interconnect m3u8 information
[vimeo] 205917267: Downloading akfire_interconnect_quic MPD information
[vimeo] 205917267: Downloading fastly_skyfire_h2 MPD information
WARNING: There's no description to write.
[dashsegments] Total fragments: 286
[download] Destination: C:\Users\Bob\Downloads\YouTube-Downloader\vimeo\Climate of Concern - The film oil giant Shell made in 1991 to warn the world about climate change - De Correspondent (NA) 205917267.mp4
[download] 100.0% of ~296.73MiB at  2.13MiB/s ETA 00:00
[download] 100% of 296.73MiB in 00:21
[ffmpeg] Not converting video file C:\Users\Bob\Downloads\YouTube-Downloader\vimeo\Climate of Concern - The film oil giant Shell made in 1991 to warn the world about climate change - De Correspondent (NA) 205917267.mp4 - already is in target format mp4
[download] Finished downloading playlist: Shell made a film about climate change in 1991 (then neglected to heed its own warning)
Download Worker Finished.
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-errors', '--newline', '-v', '-i', '--format', 'mp4', '--recode-video', 'mp4', '--write-description', '-o', 'C:\\Users\\Bob\\Downloads\\YouTube-Downloader\\%(extractor)s\\%(title)s - %(uploader)s (%(upload_date)s) %(id)s.%(ext)s', 'https://thecorrespondent.com/6285/shell-made-a-film-about-climate-change-in-1991-then-neglected-to-heed-its-own-warning/692663565-875331f6']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2017.05.23
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.1.5, ffprobe 3.1.5
[debug] Proxy map: {}
[generic] 692663565-875331f6: Requesting header
WARNING: Could not send HEAD request to https://thecorrespondent.com/6285/shell-made-a-film-about-climate-change-in-1991-then-neglected-to-heed-its-own-warning/692663565-875331f6: HTTP Error 405: Not Allowed
[generic] 692663565-875331f6: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 692663565-875331f6: Extracting information
[download] Downloading playlist: Shell made a film about climate change in 1991 (then neglected to heed its own warning)
[generic] playlist Shell made a film about climate change in 1991 (then neglected to heed its own warning): Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[vimeo] 205917267: Downloading webpage
[vimeo] 205917267: Extracting information
[vimeo] 205917267: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 205917267: Downloading akfire_interconnect m3u8 information
[vimeo] 205917267: Downloading fastly_skyfire_h2 m3u8 information
[vimeo] 205917267: Downloading fastly_skyfire_h2 MPD information
[vimeo] 205917267: Downloading akfire_interconnect_quic MPD information
WARNING: There's no description to write.
[debug] Invoking downloader on 'https://skyfire-h2.vimeocdn.com/1495603266-0xbb449eeec45fd12dc6067586f9b1f5b2b3fcdcf3/205917267/sep/video/701356075,701356080/../'
[dashsegments] Total fragments: 286
[download] Destination: C:\Users\Bob\Downloads\YouTube-Downloader\vimeo\Climate of Concern - The film oil giant Shell made in 1991 to warn the world about climate change - De Correspondent (NA) 205917267.mp4
[download]   0.3% of ~227.63KiB at Unknown speed ETA 01:09
[download]  10.0% of ~252.37MiB at 888.65KiB/s ETA 03:30
[download]  20.0% of ~251.55MiB at  1.26MiB/s ETA 03:06
[download]  30.1% of ~260.39MiB at  1.46MiB/s ETA 02:41
[download]  40.0% of ~275.40MiB at  1.83MiB/s ETA 02:19
[download]  50.0% of ~277.42MiB at  2.08MiB/s ETA 01:54
[download]  49.9% of ~277.70MiB at 499.98KiB/s ETA 01:54
[download]  50.0% of ~277.70MiB at  2.28MiB/s ETA 01:54
[download]  60.0% of ~283.58MiB at  1.50MiB/s ETA 01:33
[download]  70.0% of ~287.58MiB at  1.39MiB/s ETA 01:09
[download]  80.1% of ~291.37MiB at  1.87MiB/s ETA 00:46
[download]  90.0% of ~294.00MiB at  1.41MiB/s ETA 00:23
[download] 100.0% of ~296.73MiB at  1.57MiB/s ETA 00:00
[download] 100% of 296.73MiB in 03:55
[ffmpeg] Not converting video file C:\Users\Bob\Downloads\YouTube-Downloader\vimeo\Climate of Concern - The film oil giant Shell made in 1991 to warn the world about climate change - De Correspondent (NA) 205917267.mp4 - already is in target format mp4
[download] Finished downloading playlist: Shell made a film about climate change in 1991 (then neglected to heed its own warning)
Download Worker Finished.

...
<end of log>
```

---

---

### Description of your *issue*, suggested solution and other information

This vimeo video plays correctly using the embedded web page player (https://thecorrespondent.com/6285/shell-made-a-film-about-climate-change-in-1991-then-neglected-to-heed-its-own-warning/692663565-875331f6).  However, the downloaded .mp4 file is missing the audio component.  I have tried to download the file several times - each download has same file size (303,849 KB) and no audio.  I've not had this problem with other vimeo videos I've downloaded before or after this video. 

Downloaded file is too large to attach.  

The following is the output from running ffprobe against the downloaded file:

C:\Users\Bob\Downloads\YouTube-Downloader>ffprobe.exe "C:\Users\Bob\Downloads\YouTube-Downloader\vimeo\Climate of Concern - The film oil giant Shell made in 1991 to warn the world about climate change - De Correspondent (NA) 205917267.mp4"
ffprobe version 3.1.5 Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Bob\Downloads\YouTube-Downloader\vimeo\Climate of
Concern - The film oil giant Shell made in 1991 to warn the world about climate change - De Correspondent (NA) 205917267.mp4':
  Metadata:
    major_brand     : iso5
    minor_version   : 512
    compatible_brands: iso6mp41
    encoder         : Lavf57.72.100
  Duration: 00:28:31.44, start: 0.000000, bitrate: 1454 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 720x540 [SAR 1:1 DAR 4:3], 1446 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler

After 30 seconds of play, VLC listed this information about the file:

General
-------
Encoded by: Lavf57.72.100

Codec Tab
---------
>Stream 0
	Type: Video
	Codec: H264 - MPEG-4 AVC (part10) (avc1)
	Resolution: 720x540
	Display resolution: 720x540
	Frame rate: 25
	Decoded format: Planar 4:2:0 YUV

Statistics Tab
--------------
>Audio
	Decoded:  0 blocks
	Played:   0 buffers
	Lost:     0 buffers

>Video
	Decoded:     797 blocks
	Displayed:  3056 frames
	Lost:          1 frames

>Input/Read
	Media data size:        6900 KiB
	Input bitrate:          1434 kb/s
	Demuxed data size:      6054 KiB
	Content bitrate:        1434 kb/s
        Discarded (corrupted)      0
	Dropped (discontinued)     0

youtube-dl is running on 64 bit Windows OS.  
ffmpeg files downloaded from https://ffmpeg.zeranoe.com/builds/ and extracted from ffmpeg-3.1.5-win64-static.zip

Thanks in advance for looking at this issue!

**Comment by ShadowLandWalker** [comment]
Thanks to Sergey M. this problem has been resolved in youtube-dl version 2017.05.26.  I've just downloaded the vimeo video again and now the sound component is included.

Thanks, Sergey, for the fast turn-around of the resolution to this problem!

**Comment by ShadowLandWalker** [comment]
This problem has been resolved in youtube-dl version 2017.05.26.  I've just downloaded the vimeo video again and now the sound component is included.

Thanks, Sergey, for the fast turn-around of the resolution to this problem!
Bob S.

**Comment by dandrei** [comment]
Hi @dstftw I'm writing this to report a potential issue in version `2020.03.24`.

If the parameter `--format=mp4` is added, the video is downloaded with no audio. I tried several videos on Vimeo with the same result.

This one has no sound:
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: ['--title', '--verbose', '--format=mp4', 'https://vimeo.com/259422408']
    WARNING: --title is deprecated. Use -o "%(title)s-%(id)s.%(ext)s" instead.
    [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
    [debug] youtube-dl version 2020.03.24
    [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
    [debug] exe versions: ffmpeg N-94492-gc29d81e736, ffprobe N-94492-gc29d81e736
    [debug] Proxy map: {}
    [vimeo] 259422408: Downloading webpage
    [vimeo] 259422408: Extracting information
    [vimeo] 259422408: Downloading JSON metadata
    [vimeo] 259422408: Downloading JSON metadata
    [vimeo] 259422408: Downloading akfire_interconnect_quic m3u8 information
    [vimeo] 259422408: Downloading fastly_skyfire m3u8 information
    [vimeo] 259422408: Downloading akfire_interconnect_quic MPD information
    [vimeo] 259422408: Downloading akfire_interconnect_quic MPD information
    [vimeo] 259422408: Downloading fastly_skyfire MPD information
    [vimeo] 259422408: Downloading fastly_skyfire MPD information
    [debug] Invoking downloader on 'https://skyfire.vimeocdn.com/1588414158-0x17a95ce401f1da7b6866f859527f16aba724cc99/259422408/sep/video/952937505/playlist.m3u8'
    [hlsnative] Downloading m3u8 manifest
    [hlsnative] Total fragments: 6
    [download] Destination: Golf Course - Sample Aerial Video-259422408.mp4
    [download] 100% of 21.68MiB in 00:16
    [debug] ffmpeg command line: ffprobe -show_streams "file:Golf Course - Sample Aerial Video-259422408.mp4"

This one has sound:
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: ['--title', '--verbose', 'https://vimeo.com/259422408']
    WARNING: --title is deprecated. Use -o "%(title)s-%(id)s.%(ext)s" instead.
    [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
    [debug] youtube-dl version 2020.03.24
    [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
    [debug] exe versions: ffmpeg N-94492-gc29d81e736, ffprobe N-94492-gc29d81e736
    [debug] Proxy map: {}
    [vimeo] 259422408: Downloading webpage
    [vimeo] 259422408: Extracting information
    [vimeo] 259422408: Downloading JSON metadata
    [vimeo] 259422408: Downloading JSON metadata
    [vimeo] 259422408: Downloading fastly_skyfire m3u8 information
    [vimeo] 259422408: Downloading akfire_interconnect_quic m3u8 information
    [vimeo] 259422408: Downloading fastly_skyfire MPD information
    [vimeo] 259422408: Downloading fastly_skyfire MPD information
    [vimeo] 259422408: Downloading akfire_interconnect_quic MPD information
    [vimeo] 259422408: Downloading akfire_interconnect_quic MPD information
    [debug] Default format spec: bestvideo+bestaudio/best
    [debug] Invoking downloader on 'https://skyfire.vimeocdn.com/1588414038-0xe7008f1af535959732b7c31e3a7fa2243ab24cad/259422408/sep/video/952937505/playlist.m3u8'
    [hlsnative] Downloading m3u8 manifest
    [hlsnative] Total fragments: 6
    [download] Destination: Golf Course - Sample Aerial Video-259422408.fhls-fastly_skyfire-5169.mp4
    [download] 100% of 21.68MiB in 00:39
    [debug] Invoking downloader on 'https://skyfire.vimeocdn.com/1588414038-0xe7008f1af535959732b7c31e3a7fa2243ab24cad/259422408/sep/audio/952937514/playlist.m3u8'
    [hlsnative] Downloading m3u8 manifest
    [hlsnative] Total fragments: 6
    [download] Destination: Golf Course - Sample Aerial Video-259422408.fhls-fastly_skyfire-audio-medium-audio.mp4
    [download] 100% of 602.37KiB in 00:01
    [ffmpeg] Merging formats into "Golf Course - Sample Aerial Video-259422408.mp4"
    [debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Golf Course - Sample Aerial Video-259422408.fhls-fastly_skyfire-5169.mp4" -i "file:Golf Course - Sample Aerial Video-259422408.fhls-fastly_skyfire-audio-medium-audio.mp4" -c copy -map "0:v:0" -map "1:a:0" "file:Golf Course - Sample Aerial Video-259422408.temp.mp4"
    Deleting original file Golf Course - Sample Aerial Video-259422408.fhls-fastly_skyfire-5169.mp4 (pass -k to keep)
    Deleting original file Golf Course - Sample Aerial Video-259422408.fhls-fastly_skyfire-audio-medium-audio.mp4 (pass -k to keep)

Just a heads-up.

**Comment by AdrianSimionov** [comment]
I second this issue.
