### ISSUE TITLE
Shahid Download "Movies Problem"

### ISSUE THREAD

**Issue by mshmomo** [rg3/youtube-dl#13181]
Hello
by this program I was able to download movies and series from Plus Account on Shahid.net
but today I cant the message display to me says "ERROR: This video is DRM protected."
![screenshot_13](https://cloud.githubusercontent.com/assets/4062621/26287556/63f5eb42-3e7e-11e7-8dcf-8ac76883f18f.png)
I f you know there are some movies are still can be downloaded but the new movies have the DRM encryption, if you know when I watch the movie from the site itself I see from "network tab" MP4 links like this one 
http://media.level3.shahid.net/u/Assets/a1/27/4D/a1-2300370/s1-18768250/video-7.mp4

so dose there any way to make the file readable and able to be downloaded?
Thanks.

**Comment by remitamine** [comment]
duplicate of #8196.
