### ISSUE TITLE
Suggestion: Turn off netrc/authentication (from config) if we're not downloading the video (i.e.description/audio/file format check)

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#13187]
This is my etc/youtube-dl conf:

```
# Save all videos under Movies directory in your home directory
-o ~/Videos/youtube-dl/%(title)s_%(id)s.%(ext)s

# Use .netrc authentication data
--netrc

# Restrict filenames to only ASCII characters, and avoid "&" and spaces in filenames
--restrict-filenames

# Write video description to a .description file
--write-description

--write-sub
--yes-playlist
--ignore-errors
```

 In my youtube-dl  config file, I have the `--netrc` option so that  I can check Youtube.com for which videos are "Watched Videos".  I learned, though, that logging-in takes some time. 

So for some circumstances, I don't want o waste time with logging in. For example,

- I'm just downloading the audio
- I'm just checking the file formats available (`-F`)

Is there a way to negate just one part of my configuration? I want to negate the line about authentication/logging-in, but I want the other options to be heeded (e.g. output template).

Can we make youtube-dl  smart and automatically turn off log-in/authentication when it detects that we're not downloading any videos?

**Comment by dstftw** [comment]
There is no such option but you can make separate config and use it with `--config-location`. Also, generally video may require authentication so I'll have to log in anyway to get it working in all cases.

**Comment by hub2git** [comment]
@dstftw Thanks for your reply.

>generally video may require authentication
Could you expand on that? What do you mean they generally require authentication? Are you saying that if you don't log in, you can't access the videos?

**Comment by Hrxn** [comment]
Yes, in some cases I think...
