### ISSUE TITLE
Unable to Download Webpage Error after installing latest version v2017.05.23

### ISSUE THREAD

**Issue by nomanali1** [rg3/youtube-dl#13188]
I just install the latest youtube -dl version to download a udemy course. My query was
[youtube-dl -u username -p xxxxxxxxx -o '~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/ %(playlist_index)s - %(title)s.%(ext)s' https://www.udemy.com/learn-how-to-convert-psd-to-html-and-css- responsive/learn/v4/overview](url) As soon as I click enter I got this error [http://imgur.com/a/NPbXl](url)

> PS C:\Users\CitizenFour> youtube-dl -u username -p xxxxxxxx -o '~/MyVideos/%(playlist)s/%(chapter_number)s
 - %(chapter)s/ %(playlist_index)s - %(title)s.%(ext)s' https://www.udemy.com/learn-how-to-convert-psd-to-html-and-css-
responsive/learn/v4/overview
[udemy:course] Downloading login popup
[udemy:course] Logging in as username
[udemy:course] learn-how-to-convert-psd-to-html-and-css-: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: NOT FOUND (caused by <HTTPError 404: 'NOT FOUND'>); please report thi
s issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to
update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
PS C:\Users\CitizenFour>

I have added the path in my environment variables and I don't know what is the issue here. I have been download the videos with the same method earlier but after this new update I am facing this issue.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
