### ISSUE TITLE
Download only subs = hieroglyphs?

### ISSUE THREAD

**Issue by TammysHead** [rg3/youtube-dl#13180]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.18.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.18.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies.txt', '--no-check-certif
icate', '--skip-download', '--all-subs', 'http://www.crunchyroll.com/monster-str
ike/episode-8-ceo-madarame-734305']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.18.1
[debug] Python version 3.4.4 - Windows-2012Server-6.2.9200-SP0
[debug] exe versions: ffmpeg N-84814-gad7aff0, ffprobe N-84814-gad7aff0
[debug] Proxy map: {}
[Crunchyroll] 734305: Downloading webpage
[Crunchyroll] 734305: Downloading media info for 360p
[Crunchyroll] 734305: Downloading m3u8 information
[Crunchyroll] 734305: Downloading media info for 480p
[Crunchyroll] 734305: Downloading m3u8 information
[Crunchyroll] 734305: Downloading media info for 720p
[Crunchyroll] 734305: Downloading m3u8 information
[Crunchyroll] 734305: Downloading media info for 1080p
[Crunchyroll] 734305: Downloading m3u8 information
[Crunchyroll] 734305: Downloading media info
[Crunchyroll] 734305: Downloading subtitles for English (US)
[Crunchyroll] 734305: Downloading subtitles for Español
[Crunchyroll] 734305: Downloading subtitles for Español (España)
[Crunchyroll] 734305: Downloading subtitles for Français (France)
[Crunchyroll] 734305: Downloading subtitles for Português (Brasil)
[Crunchyroll] 734305: Downloading subtitles for Português (Portugal)
[Crunchyroll] 734305: Downloading subtitles for Italiano
[Crunchyroll] 734305: Downloading subtitles for Deutsch
[info] Writing video subtitles to: Monster Strike Folge 8 - Madarame CEO-734305.
deDE.ass
[info] Writing video subtitles to: Monster Strike Folge 8 - Madarame CEO-734305.
ptBR.ass
[info] Writing video subtitles to: Monster Strike Folge 8 - Madarame CEO-734305.
esLA.ass
[info] Writing video subtitles to: Monster Strike Folge 8 - Madarame CEO-734305.
frFR.ass
[info] Writing video subtitles to: Monster Strike Folge 8 - Madarame CEO-734305.
enUS.ass
[info] Writing video subtitles to: Monster Strike Folge 8 - Madarame CEO-734305.
itIT.ass
[info] Writing video subtitles to: Monster Strike Folge 8 - Madarame CEO-734305.
ptPT.ass
[info] Writing video subtitles to: Monster Strike Folge 8 - Madarame CEO-734305.
esES.ass
---

### Description of your *issue*, suggested solution and other information

So, i posted this earlier once, but i didnt get help. I am downloading the Subtitles from Crunchyroll, but they are in ANSI, which makes a huge problem. The problem is that the letters ä, ö and ü are not allowed in ANSI. If i mux them with an MP4, they are hieroglyphs then.
![vlc_2017-05-21_19-28-46](https://cloud.githubusercontent.com/assets/26443095/26286054/154f289a-3e5c-11e7-9cb2-0bb8c52e7050.png)
I must convert the subtitles to UTF-8 manually everytime and i hope for an fix. I don't want to use --embed-subs . Could you add a feature, which converts the Subtitles to UTF-8 everytime? Thanks for this and for developing this awesome program!

**Comment by dstftw** [comment]
I've clearly answered in #12849.
