### ISSUE TITLE
multiple links with highest quality

### ISSUE THREAD

**Issue by raedov818** [rg3/youtube-dl#1319]
hello guys, this is not an issue but a question

What if i have 50 videos in YouTube playlist, some of them with 1080p quality,720p,480p ..etc I want youtube-dl download all the videos in playlist with the highest quality available for every video, so if the videos #1 with 1080p that means youtube-dl will recognize the highest quality and will download it with that quality.

If is that possible plz how can i do it ? i used before this command
youtube-dl -cit "link of the youtube playlist" but this command download videos not with the highest quality

i hope u understand me, sorry English is not my native language. My pleasure.

**Comment by jaimeMF** [comment]
youtube-dl downloads the best format by default, feel free to comment here if it doesn't.
