### ISSUE TITLE
Youku now breaks

### ISSUE THREAD

**Issue by ztytian** [rg3/youtube-dl#13191]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

youtube-dl http://v.youku.com/v_show/id_XMjc4MTEzNDMwMA==.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://v.youku.com/v_show/id_XMjc4MTEzNDMwMA==.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.23
[debug] Python version 2.7.12 - Darwin-16.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 12, avprobe 12, ffmpeg 3.3.1, ffprobe 3.3.1
[debug] Proxy map: {}
[youku] XMjc4MTEzNDMwMA: Downloading JSON metadata
ERROR: Youku server reported error -603: 客户端无权播放,603; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youku.py", line 253, in _real_extract
    raise ExtractorError(msg)
ExtractorError: Youku server reported error -603: \u5ba2\u6237\u7aef\u65e0\u6743\u64ad\u653e,603; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

As shown, Youku fails to download. I think they've changed their API as you-get also fails.

**Comment by ztytian** [comment]
They probably changed their API and ct=10/ct=12 returns 603.

**Comment by dream4today18888** [comment]
i also have the same problem

**Comment by xfort** [comment]
i also have the same problem

**Comment by yan12125** [comment]
Any other example? http://v.youku.com/v_show/id_XMjc4MTEzNDMwMA==.html is limited to China, which makes debugging very hard.

**Comment by dream4today18888** [comment]
right，you could go to youku ，can't access everyone，those address become failed now。please resolve，maybe youku change their api？

**Comment by dream4today18888** [comment]
right，you could go to youku ，can't access everyone，those address become failed now。please resolve，maybe youku change their api？



发自网易邮箱大师
On 05/25/2017 20:55, Yen Chi Hsuan wrote:

Any other example? http://v.youku.com/v_show/id_XMjc4MTEzNDMwMA==.html is limited to China, which makes debugging very hard.

**Comment by yan12125** [comment]
Confirmed that non-georestricted videos are also broken. An example is http://v.youku.com/v_show/id_XMTc1ODE5Njcy.html

**Comment by yan12125** [comment]
Here's an untested version: https://github.com/yan12125/youtube-dl/tree/wip-youku. Be cautious as it may break at any time.

**Comment by dream4today18888** [comment]
when release this version wait your new version。




发自网易邮箱大师
On 05/26/2017 14:22, Yen Chi Hsuan wrote:

Here's an untested version: https://github.com/yan12125/youtube-dl/tree/wip-youku. Be cautious as it may break at any time.

**Comment by leenchan** [comment]
Here's an untested version: https://github.com/yan12125/youtube-dl/tree/wip-youku. Be cautious as it may break at any time.
-----------
tested. same problem

**Comment by yan12125** [comment]
@leenchan: which video? Could you paste your logs?

**Comment by ztytian** [comment]
I can confirm that none works. Same output as before.

**Comment by yan12125** [comment]
I tried several videos and all download fine, and I've pushed the fix to master. If the latest git version doesn't work for you, please paste the full log like this:
```
$ youtube-dl -v "http://v.youku.com/v_show/id_XODgxNjg1Mzk2_ev_1.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://v.youku.com/v_show/id_XODgxNjg1Mzk2_ev_1.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.23
[debug] Git HEAD: 59ed87cbd
[debug] Python version 3.6.1 - Linux-4.11.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3.1, ffprobe 3.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youku] XODgxNjg1Mzk2: Retrieving cna info
[youku] XODgxNjg1Mzk2: Downloading JSON metadata
[debug] Invoking downloader on 'http://pl-ali.youku.com/playlist/m3u8?vid=XODgxNjg1Mzk2&type=hd2&ups_client_netip=140.112.28.103&ups_ts=1495797790&utid=Hv6uEUDPilACAYxwHGfhyVBw&ccode=0401&psid=be3c3705bdcb5b0c7c94e4c85dce2e2a&ckey=&duration=1999&expire=18000&ups_key=feb5c3089ac40ca418891349a6aa3253'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 203
[download] Destination: 武媚娘传奇 85-XODgxNjg1Mzk2.mp4
[download]   2.9% of ~320.61MiB at 555.32KiB/s ETA 02:03^C
ERROR: Interrupted by user
```
Please make sure there's a line "**Retrieving cna info**". If not most likely you have multiple versions installed. Please remove all and install again from git.

**Comment by leihuayi** [comment]
Hi, I have the same issue as before. My version is 2018.09.10. I am downloading from mainland China.

$ youtube-dl -v "http://v.youku.com/v_show/id_XODgxNjg1Mzk2_ev_1.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://v.youku.com/v_show/id_XODgxNjg1Mzk2_ev_1.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.6.6 (CPython) - Linux-4.15.0-20-generic-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6
[debug] Proxy map: {}
[youku] XODgxNjg1Mzk2: Retrieving cna info
[youku] XODgxNjg1Mzk2: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/manu/anaconda3/envs/thesisenv/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/manu/anaconda3/envs/thesisenv/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/home/manu/anaconda3/envs/thesisenv/lib/python3.6/site-packages/youtube_dl/extractor/youku.py", line 189, in _real_extract
    raise ExtractorError(msg)
youtube_dl.utils.ExtractorError: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
