### ISSUE TITLE
After Windows 10 Creators Update - Missing MSVCR100.dll?

### ISSUE THREAD

**Issue by Varbaek** [rg3/youtube-dl#13198]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.23**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### Description of your *issue*, suggested solution and other information

Whenever I attempt to run youtube-dl.exe I receive the following error:
youtube-dl.exe - System Error

Content of error window:
The code execution cannot proceed because MSVCR100.dll was not found. Reinstalling the program may fix this problem.

I have tried downloading the latest (Windows binary) version from your website. Did not work. 

Product versions tested:
- 2017.05.23
- 2017.05.01

Certutil output for latest version tested:
MD5 hash of file youtube-dl.exe:
bd16394ea36fae29adcec5119c7d538b
CertUtil: -hashfile command completed successfully.

Yes I can run other executables from the cmd.exe terminal. (I tried an older version of vlc.exe and I can also run python.exe from my %PATH%.)

Python version:
2.7.13

Using the python version of youtube-dl works perfectly.

**Comment by Varbaek** [comment]
Update:
I already have Microsoft Visual C++ 2010 Redistributable Package installed.

When I try to reinstall this package (x86 and x86_64), I receive the following "error":
A newer version of Microsoft Visual C++ 2010 Redistributable has been detected on the machine.

**Comment by dstftw** [comment]
Most likely something is broken in your system.

**Comment by tomasorti** [comment]
Having this same issue and Windows 10 just installed...
