### ISSUE TITLE
The latest version can't download,why???? need help

### ISSUE THREAD

**Issue by dream4today18888** [rg3/youtube-dl#13200]
/usr/local/bin/youtube-dl   -i --skip-download  http://v.youku.com/v_show/id_XOTY1OTQyNDQ4.html --list-formats
[youku] XOTY1OTQyNDQ4: Downloading JSON metadata
ERROR: Youku server reported error -603: 瀹㈡埛绔棤鏉冩挱鏀603; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by AraHaan** [comment]
are you using python version or not? if so just simply do ``pip install --upgrade youtube_dl``

**Comment by dream4today18888** [comment]
[root]# youtube-dl --version
2017.05.23
the version is latest,you could download?

**Comment by AraHaan** [comment]
Well then idk because I use the windows version that is installed from pip and I only use soundcloud / youtube ones.
