### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by aram535** [rg3/youtube-dl#13217]
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Would be great if you could replace your archive.txt if it was overriden by mistake.  
The closest I was able to do it with was: 
`# youtube-dl --get-id --skip-download --ignore-config --download-archive archive.txt https://www.youtube.com/xxx > archive.txt
`
The script still goes through every video to check the video and for a large playlist it take a while.  Out of the 1400 videos I only want the last 5 + 1 more in the middle.

**Comment by dstftw** [comment]
You can replace download archive any time it's a simple text file. Clearly explain what are you doing and what is not correct.

**Comment by aram535** [comment]
Nothing is incorrect.   This is more of a use-case request.  

How can I re-create the full --download-archive from a channel without going through every video?

**Comment by dstftw** [comment]
You can't. In general you don't know the video id until you go through every video.
