### ISSUE TITLE
[mylifetime.com] ERROR: Unable to extract post url

### ISSUE THREAD

**Issue by AdmiralDal59** [rg3/youtube-dl#13233]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.29*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\apps\ydl>youtube-dl.exe
[debug] System config: []
[debug] User config: ['-v', '-o', 'K:\\videos\\%(title)s.%(epoch)s.%(ext)s', '-a', 'C:\\apps\\yd
l\\cfg\\list.txt', '-f', 'bestvideo[ext=mp4]+bestaudio[ext!=webm]/best', '--no-part', '--write-d
escription', '--write-annotations', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-passwor
d', 'PRIVATE', '--netrc']
[debug] Custom config: []
[debug] Command-line args: []
[debug] Batch file urls: ['http://www.mylifetime.com/movies/michael-jackson-searching-for-neverl
and/full-movie']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.29
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-86175-g64ea4d1, ffprobe N-86175-g64ea4d1, rtmpdump 2.4
[debug] Proxy map: {}
[aenetworks] michael-jackson-searching-for-neverland: Downloading webpage
[aenetworks] 953424963836: Downloading JSON metadata
[aenetworks] 953424963836: Downloading Provider Redirect Page
[aenetworks] 953424963836: Downloading Provider Login Page
[aenetworks] 953424963836: Logging in
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure
 you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl wi
th the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\Y
outubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\e
xtractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\e
xtractor\aenetworks.py", line 143, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\e
xtractor\adobepass.py", line 1476, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\e
xtractor\adobepass.py", line 1348, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\e
xtractor\common.py", line 791, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\e
xtractor\common.py", line 782, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on htt
ps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update.
 Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Cannot download videos from mylifetime.com, error log provided above. I can provide login credentials if needed via email/PM.

http://www.mylifetime.com/movies/michael-jackson-searching-for-neverland
http://www.mylifetime.com/shows/the-rap-game/season-3/episode-11

**Comment by yan12125** [comment]
Apparently logging with DTV is broken. See #12997
