### ISSUE TITLE
Cannot download SoundCloud files on Ubuntu 16.04.2

### ISSUE THREAD

**Issue by forgehe** [rg3/youtube-dl#13238]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.29*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
Error Output
```
root@forgehe:~# youtube-dl --verbose https://soundcloud.com/ntreboot/suki
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://soundcloud.com/ntreboot/suki  ']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode   all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968,   pref ANSI_X3.4-1968
[debug] youtube-dl version 2017.05.29
[debug] Python version 2.7.12 - Linux-2.6.32-042stab093.5-x86_64-with-Ubuntu-16.  04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16  .04.1, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] ntreboot/suki: Resolving id
[soundcloud] ntreboot/suki: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 504: Gateway Time-out (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2106, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

---

### Description of your *issue*, suggested solution and other information

Fails when trying to download off soundcloud. Youtube works.

Windows exe works when downloading the same link. Fails on Ubuntu 16.04.2. Haven't tested it on any other system.

I just noticed that youtube-dl uses python version 2.7, but I also have python 3 (and 3.5?) installed in my VPS as well. Maybe that causes problems?

Found this issue that looks like it's having the same problem
https://github.com/rg3/youtube-dl/issues/9198

**Comment by dstftw** [comment]
Most likely your VPS is blocked by soundcloud.
