### ISSUE TITLE
YOUKU Video duration error

### ISSUE THREAD

**Issue by saku1119** [rg3/youtube-dl#13237]
It's turns into that the videos partly divided before become ONE whole video this week. The video I need to download lasts one hour. The mega bites of the video are right after the downloading, but it's only a two minutes video when I played it. Is it possible that I do the downloading partly as before？I can combine them myself.

site：youku.com

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
