### ISSUE TITLE
Eroshare permissions issue

### ISSUE THREAD

**Issue by nova-techies** [rg3/youtube-dl#13234]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.29*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
paul@ripbox:/mnt/dump/transfer-folder$ sudo youtube-dl -f best -v https://v.eroshare.com/0atb9hde.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'best', u'-v', u'https://v.eroshare.com/0atb9hde.mp4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.29
[debug] Python version 2.7.12 - Linux-4.4.0-78-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[generic] 0atb9hde: Requesting header
[debug] Invoking downloader on u'https://v.eroshare.com/0atb9hde.mp4'
ERROR: unable to open for writing: [Errno 13] Permission denied: '0atb9hde-0atb9hde.mp4.part'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 175, in real_download
    (stream, tmpfilename) = sanitize_open(tmpfilename, open_mode)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 450, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
IOError: [Errno 13] Permission denied: '0atb9hde-0atb9hde.mp4.part'
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

I am unable to fetch any videos from Eroshare as I am getting a permissions issue.  I am able to manually right click the video and save it through my broswer but youtube-dl does not like to play nicely with this.  I chmod'd the folder to 0777 and it still wouldn't let me scrap the URL.

Seems to me to be a handshake issue with https but I have an account with eroshare.  Plus it is forcing to the generic extractor and i can't force it otherwise.

**Comment by Hrxn** [comment]
Why do you use the direct link? (`https://v.eroshare.com/0atb9hde.mp4`)

Just use the link to the video page on the site, just as in the browser.

**Comment by nova-techies** [comment]
Tried that as well same result

**Comment by Hrxn** [comment]
Just noticed that Eroshare is not listed as a [supported site](https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md), to my own surprise.

Always assumed it would already be included.
Relevant issue is here: #6256

Alleged to work with the generic extractor.

Okay, if the URL is not the culprit it probably is a permission problem with the file system.
Did you try it on a local machine?

**Comment by nova-techies** [comment]
I found out it was an inherited folder that was causing the problems.  Worked fine on a VM I spun up.

I'll close this out.
