### ISSUE TITLE
Improving support for piping to stdout

### ISSUE THREAD

**Issue by Jiriss** [rg3/youtube-dl#13243]
youtube-dl pipes the live stream to an external video player correctly using parameter "o" as shown below

youtube-dl http://domainname-example.org/playlist.m3u8 -o - | vlc -

A problem is when user close an external video player but youtube-dl still continues downloading stream. Does youtube-dl include some parameter that could help in this problem or can you improve support for piping to stdout? Now the downloading of the stream is stopped only when terminal window is closed or using Ctrl+C keys.

I use the newest version on Ubuntu 14.04 LTS

youtube-dl --version
2017.05.29

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
