### ISSUE TITLE
ytsearch time realted

### ISSUE THREAD

**Issue by mobvd** [rg3/youtube-dl#13249]
hello
            i want use ytsearch result as last  24 hours uploaded videos
    like https://www.youtube.com/results?filters=today&search_query=funny+videos&lclk=today

    plz tell me how i use "upload date" filter in ytsearch results

**Comment by dstftw** [comment]
Use search URL.

**Comment by mobvd** [comment]
plz explain more i try this

youtube-dl -f 22 -o '%(title)s.%(ext)s' --dateafter now-1day  --force-ipv4 "ytsearch50:funny videos"

but it skip all videos because ytsearch related videos not as latest videos
