### ISSUE TITLE
403 error onl the bilibili link

### ISSUE THREAD

**Issue by DoctorLai** [rg3/youtube-dl#13242]
youtube-dl -v -f 'best[ext=mp4]/best' -g http://www.bilibili.com/video/av10815497/?tg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'best[ext=mp4]/best', u'-g', u'http://www.bilibili.com/video/av10815497/?tg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.29
[debug] Python version 2.7.12 - Linux-3.13.0-24-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
http://ws.acgvideo.com/e/84/17875194-1-hd.mp4?wsTime=1496250503&platform=pc&wsSecret2=70b863588472e924406f1451afd66068&oi=1318963333&rate=700

**  the link  is always 403  forbidden error ***

Thanks

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser
