### ISSUE TITLE
unable to download from packt

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#13240]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.29*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.29**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.05.29
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

hello Sir
i am getting error while download course from packt but my account is working fine on browser i checked other courses also and getting same error evan previous courses which i downloaded via youtube-dl now getting error also here is error detail

 
PS C:\Users\vicky\downloads> youtube-dl --verbose -o '~/downloads/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)
s.%(ext)s' https://www.packtpub.com/mapt/video/web-development/9781788290616 --username 123@gmail.com --password 123
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', '~/downloads/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ex
t)s', 'https://www.packtpub.com/mapt/video/web-development/9781788290616', '--username', 'PRIVATE', '--password', 'PRIVA
TE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.29
[debug] Python version 3.5.2 - Windows-10-10.0.14393-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[PacktPubCourse] 9781788290616: Downloading JSON metadata
[download] Downloading playlist: Learn to Write Functional Javascript [Video]
[PacktPubCourse] playlist Learn to Write Functional Javascript [Video]: Collected 17 video ids (downloading 17 of them)
[download] Downloading video 1 of 17
[PacktPub] None: Downloading webpage
[PacktPub] Logging in as 123@gmail.com
[PacktPub] Downloading Authorization Token
[PacktPub] 24237: Downloading JSON video
[PacktPub] 24237: Downloading JSON metadata
[debug] Invoking downloader on 'https://d1ft11egbn8l.cloudfront.net/Learn to Write Functional Javascript/Package/videos/
video1_1.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2QxZnQxMWVnYm44bC5jbG91ZGZyb250Lm5ldFwvTGVhcm4lMjB0
byUyMFdyaXRlJTIwRnVuY3Rpb25hbCUyMEphdmFzY3JpcHRcL1BhY2thZ2VcL3ZpZGVvc1wvdmlkZW8xXzEubXA0IiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNz
VGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDk2MjU4NjY2fX19XX0_&Signature=IeuD-BjuD3JxSqU6CFZz2avccQ56pYIxA08yT9t830W4Dzga-yOFRWMNG
syAg-yJ~I2p0mgZ8~JkVSbVfkcWqrB1bp5m5lXctT64xoB7ua5gslwvTUR~ABEadSob~WozaFk9bJWcu9tJaUpZyezGr-opeFQP9jyqb4zi~SnTcX4_&Key-
Pair-Id=APKAJTJLPJQL5PVZ47FA'
[download] C:\Users\vicky\downloads\Learn to Write Functional Javascript [Video]\1 - Understanding Foundations of Functi
onal Programming\The Course Overview.mp4 has already been downloaded
[download] 100% of 31.12MiB
[download] Downloading video 2 of 17
[PacktPub] 22286: Downloading JSON video
ERROR: This video is locked. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 760, in e
xtract_info
    ie_result = ie.extract(url)
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\extractor\common.py", line 43
3, in extract
    ie_result = self._real_extract(url)
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\extractor\packtpub.py", line
94, in _real_extract
    self.raise_login_required('This video is locked')
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\extractor\common.py", line 71
3, in raise_login_required
    expected=True)
youtube_dl.utils.ExtractorError: This video is locked. Use --username and --password or --netrc to provide account crede
ntials.

PS C:\Users\vicky\downloads>

**Comment by jaan143** [comment]
plz put this login url in python file
https://www.packtpub.com/mapt/login

**Comment by remitamine** [comment]
i did check now with the account that you have sent before and i can't access the video in the browser, i get `This video is locked`.

**Comment by jaan143** [comment]
because that my old account is expired 
i sent you another working account detail in email
plz check
