### ISSUE TITLE
ZDF_neo download error

### ISSUE THREAD

**Issue by herbyda** [rg3/youtube-dl#13241]
'% youtube-dl --verbose https://www.zdf.de/filme/stralsund/stralsund-kreuzfeuer-104.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.zdf.de/filme/stralsund/stralsund-kreuzfeuer-104.html']
[debug] Encodings: locale ISO8859-1, fs ISO8859-1, out ISO8859-1, pref ISO8859-1
[debug] youtube-dl version 2017.05.29
[debug] Python version 2.7.12 - FreeBSD-9.2-RELEASE-p15-amd64-64bit-ELF
[debug] exe versions: ffmpeg 2.8.8, ffprobe 2.8.8, rtmpdump 2.4
[debug] Proxy map: {'ftp': 'http://montoya:8000', 'http': 'http://montoya:8080', u'https': 'http://montoya:8080'}
[ZDF] stralsund-kreuzfeuer-104: Downloading webpage
[ZDF] stralsund-kreuzfeuer-104: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'formitaeten',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/zdf.py", line 230, in _real_extract
    return self._extract_mobile(video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/zdf.py", line 191, in _extract_mobile
    for f in document['formitaeten']:
KeyError: u'formitaeten'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 446, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'formitaeten',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.'

**Comment by chkuendig** [comment]
Any reason you closed this again? I have the same issue (youtube_dl 2017.05.29, url https://www.zdf.de/comedy/neo-magazin-mit-jan-boehmermann/neo-magazin-royale-mit-jan-boehmermann-vom-23-februar-2017-100.html )

**Comment by herbyda** [comment]
Hello,

video is availible until 6.6.2017 23:59. It can be seen on the 
ZDF-Mediathek.

Regards.
herby

---------------------------------------------------------------

Video verfügbar bis 06.06.2017, 23:59
Produktionsland und -jahr:
     Deutschland 2014

Am 31.05.2017 um 22:35 schrieb Christian Kündig:

**Comment by herbyda** [comment]
Problem still exists (Video has not expired),.
Closing this issue was a mistake.
Sorry.

**Comment by dstftw** [comment]
>Video leider nicht mehr verfügbar
