### ISSUE TITLE
Some Youku playlist only get one data page, can not download all videos

### ISSUE THREAD

**Issue by Cye3s** [rg3/youtube-dl#13248]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
$ youtube-dl -v http://list.youku.com/show/id_z60db2a18fba811e0a046.html
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://list.youku.com/show/id_z60db2a18fba811e0a046.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.29
[debug] Python version 2.7.6 - Linux-4.4.0-78-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6
[debug] Proxy map: {}
[youku:show] z60db2a18fba811e0a046: Downloading webpage
[youku:show] z60db2a18fba811e0a046: Downloading playlist data page 1
[download] Downloading playlist: 小猪佩奇
[youku:show] playlist 小猪佩奇: Collected 10 video ids (downloading 10 of them)
[download] Downloading video 1 of 10

...
<end of log>
```

---
- Playlist: http://list.youku.com/show/id_z60db2a18fba811e0a046.html   (156 video ids but only get 10)
- Playlist: http://list.youku.com/show/id_zefbfbd70efbfbd780bef.html   (26 video ids but only get 10)
---
Some Youku playlist only get only one playlist data page(list above).
But some playlist work fine (get two pages and 50 video ids):
http://list.youku.com/show/id_zc7c670be07ff11e48b3f.html

**Comment by levinie** [comment]
yes. Playlist : http://list.youku.com/show/id_zcc001f06962411de83b1.html
only get 10 items

**Comment by yan12125** [comment]
Youku playlists are all fixed in the next version. For http://list.youku.com/show/id_z60db2a18fba811e0a046.html, I got no episodes in browsers, either (maybe because I'm outside Mainland China?), so youtube-dl fails.
