### ISSUE TITLE
How to  force login everytime

### ISSUE THREAD

**Issue by PaulDevI** [rg3/youtube-dl#13250]
I want to download multiple files using youtube-dl from a site the needs login.

The issue that I have is that youtube-dl is login for the first video with no issue, but doesn't login again for next video.

How do I force youtube-dl to login for each video, every time the function is called ?

def video_download(path, url):

        ydl = youtube_dl.YoutubeDL(
            {
                'outtmpl': path + '.mp4',
                'format': 'bestvideo+bestaudio/best',
                'username': email,
                'password': password,
                'cachedir': False,
                'noplaylist': True
                # 'quiet': True

            })

        with ydl:
            ydl.download([url])
        time.sleep(45)

**Comment by dstftw** [comment]
Create new instance `YoutubeDL` for each call of `download`.

**Comment by PaulDevI** [comment]
please give me more details. I tried the below code and is not working

def video_download(path, url, email, password, i):

        ydl = {}
        ydl[i] = youtube_dl.YoutubeDL(
