### ISSUE TITLE
command line does not support downloading all mp4 formats only (in sorting order).

### ISSUE THREAD

**Issue by DoctorLai** [rg3/youtube-dl#13255]
I have tried this:

youtube-dl -g  -f "video[ext=mp4]"  "https://www.youtube.com/watch?v=2d0wK8bM3VU"
ERROR: requested format not available

My expected output is something like this:

mp4 url of 1080p   
mp4 url of 720p
mp4 url of 360p
..
..

basically, the quality of mp4 url in descending order.

**Comment by dstftw** [comment]
Bother to read [FAQ](https://github.com/rg3/youtube-dl#format-selection).
