### ISSUE TITLE
cannot download youku video

### ISSUE THREAD

**Issue by saitofun** [rg3/youtube-dl#13256]
sincos@Saito-MBP:~/Downloads$ youtube-dl --list-formats http://v.youku.com/v_show/id_XMjQ4MTQwODU5Ng==.html
[youku] XMjQ4MTQwODU5Ng: Downloading JSON metadata
ERROR: Youku server reported error -603: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by yan12125** [comment]
This is already fixed in the latest version. https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl can be useful.
