### ISSUE TITLE
Video ID in output file name

### ISSUE THREAD

**Issue by luboss** [rg3/youtube-dl#13267]
Hi there!

I'm working on 2 new extractors. My concern is name of the output file. It contains video ID which is 36 characters long. The file name looks pretty ugly in such case. I could provide an empty id but what's the point of mandatory ID then? :-) Dash/minus character couldn't be removed that way anyway.

Is there way to remove dash and video ID suffix from the name? Title I provide contains video release date (with leading zeros) so the uniqueness of the name shouldn't be an issue.

Thanks in advance!

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#output-template

**Comment by luboss** [comment]
Ok, but this is just for end user, not for extractor developer to construct a default name. User has to explicitly think about the file name in advance.
If there is no other way out, OK. I just wanted to know so I can be 100% sure I cannot do anything about it.

**Comment by dstftw** [comment]
End user decided what will be the output name. As developer you should not touch it.
