### ISSUE TITLE
Adding track # metadata to mp3 downloads by using the playlist_index #

### ISSUE THREAD

**Issue by playlistindex** [rg3/youtube-dl#13271]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.29**

your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

As the title says, I'd like to download audio from youtube playlists while adding track numbers to each audio file based on its position in said youtube playlist.

I have tried tracking down the correct set of command modifiers and have managed to download perfectly healthy .mp3 files, but i have not found the proper set to add the track # metadata so i don't have to add it manually with audacity.

Thanks in advance.

**Comment by playlistindex** [comment]
is this a duplicate of #7393? yes.  has #7393 been dead for a year and remained unresolved?  also yes

**Comment by playlistindex** [comment]
@dstftw

**Comment by br3wski3** [comment]
Opened pull request #14991 which I believe may support the OP request
