### ISSUE TITLE
Support MPEG-DASH Subtitle Download

### ISSUE THREAD

**Issue by Saullric** [rg3/youtube-dl#13278]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [x] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.29*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [√] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.29**

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [√] Feature request (request for a new functionality)
- [x] Question
- [x] Other

---

### Description of your *issue*, suggested solution and other information

subsegmentAlignment="true" is this saied that subtitles can  be downloaded ？
If so , support for downloading subtitles is an very important function .THX

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
