### ISSUE TITLE
gdcvault

### ISSUE THREAD

**Issue by sophiepeithos** [rg3/youtube-dl#13276]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.29*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
PS C:\Users\x\Downloads>   .\youtube-dl.exe -v "http://sevt.dispeak.com/ubm/gdc/eur10/player.html?xml=11256_1282118587281VNIT.xml&amp;videoid=8e0135b6736f2c850e671013700&amp;token=976c5fd89fe8a5ab16aae"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://sevt.dispeak.com/ubm/gdc/eur10/player.html?xml=11256_1282118587281VNIT.xml&amp;videoid=8e0135b6736f2c850e671013700&amp;token=976c5fd89fe8a5ab16aae']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.05.29
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[generic] player.html?xml=11256_1282118587281VNIT: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player.html?xml=11256_1282118587281VNIT: Downloading webpage
[generic] player.html?xml=11256_1282118587281VNIT: Extracting information
ERROR: Unsupported URL: http://sevt.dispeak.com/ubm/gdc/eur10/player.html?xml=11256_1282118587281VNIT.xml&amp;videoid=8e0135b6736f2c850e671013700&amp;token=976c5fd89fe8a5ab16aae
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\extractor\generic.py", line 2795, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://sevt.dispeak.com/ubm/gdc/eur10/player.html?xml=11256_1282118587281VNIT.xml&amp;videoid=8e0135b6736f2c850e671013700&amp;token=976c5fd89fe8a5ab16aae
...
<end of log>
```

---
---

### Description of your *issue*, suggested solution and other information
[video address](http://www.gdcvault.com/play/1013700/Advanced-Material)

this video can be viewed in google chrome.

**Comment by yan12125** [comment]
Thanks for the report. Such videos will be recognized in the next version.
