### ISSUE TITLE
How can I numerate Udemy chapter episodes?

### ISSUE THREAD

**Issue by nikola1970** [rg3/youtube-dl#13273]
This is a tamplate:

youtube-dl -u user -p password -o '~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/java-tutorial/

So i need some kind of ID like we have %(chapter_number)s, but for every video in the chapter. Something like:

%(chapter)s/%(VIDEO_ID_HERE)s%(title)s.%(ext)s'

Is there an option for this? Thanks :)

**Comment by dstftw** [comment]
Choose any from https://github.com/rg3/youtube-dl#output-template.
