### ISSUE TITLE
Downloads videos from Nick.com as multiple files

### ISSUE THREAD

**Issue by tv21** [rg3/youtube-dl#13286]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
Far too much output to attach. example 
youtube-dl http://www.nick.com/the-thundermans/videos/21-dump-street-s4-full-episode/

---

### Description of your *issue*, suggested solution and other information

Video downloads in 4 separate fragments that are not joined together.

**Comment by dstftw** [comment]
Original video is served in parts.

**Comment by tv21** [comment]
So there is no way to have them combined automatically?

**Comment by RuneMagle** [comment]
Not with yt-dl. I use a software called [MKVToolNix]([url]https://www.fosshub.com/MKVToolNix.html(url)), if you download it, you can append the files, so they can get joined together. I can tell you more if you want.
