### ISSUE TITLE
Safaribooksonline.com only 1 min video

### ISSUE THREAD

**Issue by hunter86bg** [rg3/youtube-dl#13288]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.05**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[user@localhost Downloads]$ youtube-dl -v  https://www.safaribooksonline.com/library/view/learning-path-bash/9780134656045/BSHF_02_09.html?autoStart=True
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.safaribooksonline.com/library/view/learning-path-bash/9780134656045/BSHF_02_09.html?autoStart=True']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.05
[debug] Python version 2.7.13 - Linux-4.10.17-200.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five
[debug] exe versions: none
[debug] Proxy map: {}
[safari] 9780134656045/BSHF_02_09: Downloading webpage
[Kaltura] 9780134656045-BSHF_02_09: Downloading webpage
[Kaltura] 0_d5z42dyd: Downloading video info JSON
[Kaltura] 0_d5z42dyd: Downloading m3u8 information
[debug] Invoking downloader on u'http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/0_d5z42dyd/format/url/protocol/http/flavorId/0_glqeu7b4'
[download] Destination: 2.9 Using Command Substitution-0_d5z42dyd.mp4
[download] 100% of 18.56MiB in 00:16

```
---

### Description of your *issue*, suggested solution and other information
Downloading is successful but video is trimmed to 1 min only,while any video tried is above that 1 min limit.

**Comment by dstftw** [comment]
You did not provide account credentials.

**Comment by hunter86bg** [comment]
Sadly , I'm not allowed to - but I can do the testing job.

**Comment by dstftw** [comment]
It never worked without credentials for restricted videos. You must provide credentials to **youtube-dl**.
