### ISSUE TITLE
Vimeo video downloads but audio is not extracted

### ISSUE THREAD

**Issue by cmanallen** [rg3/youtube-dl#13294]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

I can not extract the audio from this URL (https://vimeo.com/121209380) when an outtmpl is specified.

Most videos from Vimeo I can download and extract the audio without issue.  However, this particular video's audio is not extracted when `outtmpl` is specified.  I have tried videos of similar length from the same publisher.  All of which download and extract without issue.

When I remove my `outtmpl`, the video downloads and the audio is extracted as expected.

My code:

```
options = {
    'outtmpl': 'test.m4a',
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'm4a',
        'preferredquality': '192',
    }]
}
with youtube_dl.YoutubeDL(options) as youtube:
    youtube.download(['https://vimeo.com/121209380'])
```

Is there a way to return the filename of a downloaded video without specifying an `outtmpl`?

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
Do not hardcode extension in output template.

**Comment by cmanallen** [comment]
@dstftw Using `%(ext)s` still causes the same issue.

**Comment by dstftw** [comment]
Prove with verbose log.

**Comment by cmanallen** [comment]
@dstftw How can I do this if I'm running a script?  eg `python test.py`.

**Comment by cmanallen** [comment]
@dstftw Invalid.  The extension was causing the error.
