### ISSUE TITLE
[Question] Extract redirection only

### ISSUE THREAD

**Issue by parkmino** [rg3/youtube-dl#13307]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.05**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

I want to get only the redirection url 'mms://...' which is changing constantly.
Please advise me.

$ youtube-dl -g http://juoradio.appspot.com/kbs1
WARNING: Could not send HEAD request to http://juoradio.appspot.com/kbs1: HTTP Error 405: Method Not Allowed
ERROR: Unable to download webpage: HTTP Error 302: Found - Redirection to url 'mms://kong.kbs.gscdn.com/1fm?id=2101&si=0&secure=YzBkMzZiMTMxMmI5OTE0OTQ0NTVmYTg1NGIyMWJhM2VkOTYyYWIxZTM2ODE3OWUxODkzMjA1ZGNkZDFhODc5MzUxOTJlYjlkZTk2NDRmMWY0ZWVlMGEyYTE4YzU3ZDE2OGY0ZGFjMWNmODdhODMwY2YyZmUyOGM5ZWI0OWExMDIxOGMwYjFlNTUxNTFiZTliYjM0ZDQ1YmU0NmVhZjFhODA4NTgwNzE3NWZhMmFmNzQ0ZWJkNzUyYTVmYjc2OWVjMTE5MDdjZDU5NjY5MTRiZGQyMTg3MDdkNTA0YmIxNzhiYTkxMWYzNDcwMDhhNjVh&csu=false' is not allowed (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
There's no need to use youtube-dl here. For example curl can do that:
```
$ curl -X GET -I http://juoradio.appspot.com/kbs1 | grep -i '^Location:' | cut -d ' ' -f 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
mms://kong.kbs.gscdn.com/1fm?id=2101&si=0&secure=YzBkMzZiMTMxMmI5OTE0OWViMjBmNWU5ZmFmY2ZlMDAzYTEwZDUzNzRjZTFlZjNhNTM2OTY2NTUzNzAxMzhlNDBlYzYxZDE2YTFlNTY4MzEzYmJjMDllYTVmYWZhY2FiMTQ1ZDM4MmIxZWE4M2Y1MGRiOTc4YTVlOWU5N2NkYzY3NzNkZmVmYjc0OWI3YzE2YTM3YjAwNzVhZmE0NDdkOTIwZDcyOWUxY2Y5ZmM2ZDYyNzYxMDJkOThmZmQwN2RlY2U2OGNkMmE5N2RkODlhYzFhMjk3YmMzZjQ3M2RmMTE4ZjI3YmI4NGZkOWU2ZTQ2&csu=false
```

**Comment by parkmino** [comment]
Thanks for your information and have a good day!

2017-06-07 15:51 GMT+09:00 Yen Chi Hsuan <notifications@github.com>:
