### ISSUE TITLE
Can implement document or other else for udemy ?

### ISSUE THREAD

**Issue by natsupy** [rg3/youtube-dl#13314]
Like tittle, this's awesome if yes, thank you so much or using number of playlist like udemy, ex here number of lecture 4 is 4 but your is 3, can fix that ! Thank you so much !
http://i.imgur.com/iL0ror9.png

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
