### ISSUE TITLE
youtube-dl get-url videoplayback.mp4 not videotitle.mp4 

### ISSUE THREAD

**Issue by AdnanHussainTurki** [rg3/youtube-dl#13325]
Hello, Friends.

I am trying to fetch the URL of a video via --get-url and it is giving me a URL looks like
https://r15---sn-4g57knlz.googlevideo.com/videoplayback?expire=1497021992&keepalive=yes&mv=m&mt=1497000273&ms=au&ei=yGk6WcLjCNqw8wSimYHgCQ&mn=sn-4g57knlz&mm=31&ipbits=0&requiressl=yes&itag=134&source=youtube&id=o-AG-urEi46umUqTe6H5w-0ZrCiqgqNw6bwDggUMhFUbEL&lmt=1496955572204598&dur=203.786&ip=167.114.210.100&key=yt6&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mime=video%2Fmp4&pl=25&gir=yes&initcwndbps=772500&clen=3330292&signature=4AE80109039EC8BD9B08120A1A5A1FFD0C7EA6A3.5430E1D3818868AC98DC4AEBC1080BB264913360&ratebypass=yes

when i try to download it, its filename is videoplayback.mp4

what I need is the file I download is videotitle.mp4

I have seen various other sites which do so by adding a &title= attribute into the URL. But in this case, this is not working.

Hope this question is worth asking. Please help me out.

**Comment by yan12125** [comment]
YouTube servers do not specify a filename, so the last part in the path (```videoplayback```) will be used as the filename. If you want an alternative filename, you'll need to specify it manually.

**Comment by abou7mied** [comment]
@AdnanHussainTurki did you find any workaround for this issue?

**Comment by AdnanHussainTurki** [comment]
@abou7mied Nope. Still working for it.

**Comment by AdnanHussainTurki** [comment]
Actually, I got the solution.

**Comment by abou7mied** [comment]
@yan12125 
After some testing using this tool and online tools.
The other tools adds query to the url **&title=video_title**
Then the response headers contains
`content-disposition: attachment; filename="video_title.mp4"`
Then the browser start download the file with the name video_title.mp4

But even If I added **title query** to links got by **youtube-dl** , server doesn't respond with **content-disposition** header
I noticed the links got by youtube-dl has two extra Query in url **&gir=yes&clen=xxxxxx**
Because of the link has signature, the link won't work by removing these two queries

**Comment by abou7mied** [comment]
@AdnanHussainTurki how? :grinning:

**Comment by AdnanHussainTurki** [comment]
@abou7mied 
Actually, the link provided by youtube-dl is of type 
https://something.googlevideo.com/videoplayback?....

this kind of link does not support the explicit additional of parameters like your title one.

for adding and resolving this issue, you need to encourage google to add a legit title parameter for you in the url.


For doing so, you need to replace https://something.googlevideo.com/ of the url by https://redirector.googlevideo.com/ and then add title parameter.

For example:
youtube-dl URL:
https://r2---sn-a5mekner.googlevideo.com/videoplayback?initcwndbps=626250&key=yt6&id=o-AD2L6YrCgNPRWYyhZJ6vlHVPzf8zu1Iw-jffCUvlMaiu&source=youtube&dur=11402.274&ip=167.114.210.100&lmt=1470910187958312&itag=22&requiressl=yes&pl=25&mv=m&mt=1497420514&ms=au&ratebypass=yes&ei=SNNAWfnsI4We8wT9iaG4Bw&ipbits=0&signature=95D2D7F20D0B18422D5A43F5447C2CE28137FD79.1A5B37B79C2F6C9EFE259A6F4FF5A15BF258B778&expire=1497442216&mime=video%2Fmp4&mn=sn-5uh5o-f5fz&mm=31&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&title=The%20Secret%20of%20the%20Seven%20Sisters-Rebaz%20Zedbagi%20[DLYouTube.tk]

tweaked URL:
https://redirector.googlevideo.com/videoplayback?initcwndbps=626250&key=yt6&id=o-AD2L6YrCgNPRWYyhZJ6vlHVPzf8zu1Iw-jffCUvlMaiu&source=youtube&dur=11402.274&ip=167.114.210.100&lmt=1470910187958312&itag=22&requiressl=yes&pl=25&mv=m&mt=1497420514&ms=au&ratebypass=yes&ei=SNNAWfnsI4We8wT9iaG4Bw&ipbits=0&signature=95D2D7F20D0B18422D5A43F5447C2CE28137FD79.1A5B37B79C2F6C9EFE259A6F4FF5A15BF258B778&expire=1497442216&mime=video%2Fmp4&mn=sn-5uh5o-f5fz&mm=31&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&title=The%20Secret%20of%20the%20Seven%20Sisters-Rebaz%20Zedbagi%20[DLYouTube.tk]

This is how you can do it.

Moreover, I am going to add a complete series on youtube regarding this at my channel https://www.youtube.com/myPHPnotes, you may check out the whole there.

**Comment by AdnanHussainTurki** [comment]
Moreover, this thing works only on bestvideo format. For others, you need to url_encode etc things.

**Comment by Rohit-Dalal** [comment]
I am having same problem and tried out all methods but still not able to download  video
