### ISSUE TITLE
Hotstar Problem

### ISSUE THREAD

**Issue by bentheguitarman** [rg3/youtube-dl#13327]
### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

- Single video: youtube-dl.exe http://www.hotstar.com/tv/malcolm-in-the-middle/12117/grandma-sues/1000114289

I have been downloading from Hotstar the show "Malcolm in The Middle" and am now encountering a problem this is what comes up in the log

Warning: Failed to download m3u8 information: HTTP Error 502: Bad Gateway
ERROR: No video formats found; please report this issue on https:yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl - U to update 

I have updated Youtube-dl and tried an Indian proxy (wasnt needed for some reason) but won't work either way.

**Comment by cyberjacob** [comment]
Please add the -v flag to your command line you run youtube-dl with, copy the whole output and insert it here.

**Comment by bentheguitarman** [comment]
C:\Users\Ben\Downloads\Compressed\ffmpeg-20170503-a75ef15-win64-static\bin>youtube-dl.exe -v http://www.hotstar.com/tv/malcolm-in-the-middle/12117/grandma-sues/1000114289
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.hotstar.com/tv/malcolm-in-the-middle/12117/grandma-sues/1000114289']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.06.05
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-85750-ga75ef15, ffprobe N-85750-ga75ef15
[debug] Proxy map: {}
[HotStar] 1000114289: Downloading JSON metadata
[HotStar] 1000114289: Downloading JIO JSON metadata
[HotStar] 1000114289: Downloading m3u8 information

Im unsure how to copy the rest as the program shuts straight after, I am not the most tech savvy person when it comes to command line stuff

**Comment by bentheguitarman** [comment]
This is my BAT file in Notepad, just added the -v

youtube-dl.exe -v http://www.hotstar.com/tv/malcolm-in-the-middle/12117/grandma-sues/1000114289

**Comment by cyberjacob** [comment]
If you add another line at the end of the file with `pause` (just on it's own, nothing else) the command window should stay open for you to copy from it. It'll wait for you to press any key before finishing the BAT and closing.

**Comment by bentheguitarman** [comment]
C:\Users\Ben\Downloads\Compressed\ffmpeg-20170503-a75ef15-win64-static\bin>youtube-dl.exe -v http://www.hotstar.com/tv/malcolm-in-the-middle/12117/grandma-sues/1000114289
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.hotstar.com/tv/malcolm-in-the-middle/12117/grandma-sues/1000114289']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.06.05
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-85750-ga75ef15, ffprobe N-85750-ga75ef15
[debug] Proxy map: {}
[HotStar] 1000114289: Downloading JSON metadata
[HotStar] 1000114289: Downloading JIO JSON metadata
[HotStar] 1000114289: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 502: Bad Gateway
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\extractor\hotstar.py", line 89, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\extractor\common.py", line 1056, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


C:\Users\Ben\Downloads\Compressed\ffmpeg-20170503-a75ef15-win64-static\bin>pause
Press any key to continue . . .

**Comment by bentheguitarman** [comment]
I am wondering if perhaps it is an issue on Hotstar side of things as error 502 Bad gateway

**Comment by bentheguitarman** [comment]
I am off to bed anyway, hopefully it is a minor issue

**Comment by bentheguitarman** [comment]
back again, still have the same problem

**Comment by bentheguitarman** [comment]
anyone able to help at all. If it helps I have new info, using express vpn Mumbai server I cant actually watch the show on hotstar either but if I choose the Chenai one I can watch it in browser (firefox) but still wont let me download the stream (error 502)

**Comment by bentheguitarman** [comment]
just in a rush as the show I want to download will be gone on june 30th

**Comment by bentheguitarman** [comment]
.
