### ISSUE TITLE
Windows - Can't download from Filelist - Youtube

### ISSUE THREAD

**Issue by hash2k2** [rg3/youtube-dl#13323]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.05**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*
I created a txt file list with some youtube links in it.
starting the download: ERROR
Using single links without filelist works like a charm
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

C:\ProgramData\chocolatey\bin>youtube-dl.exe --restrict-filenames -x --audio-format "mp3" --audio-quality 256K -a "C:\Users\testc_000\songlist.txt" --verbose
[debug] System config: []
[debug] User config: ['-x', '--no-mtime', '-o', '~/Movies/%(title)s.%(ext)s']
[debug] Command-line args: ['--restrict-filenames', '-x', '--audio-format', 'mp3', '--audio-quality', '256K', '-a', 'C:\\Users\\testc_000\\songlist.txt', '--verbose']
[debug] Batch file urls: [u'https://www.youtube.com/watch?v=y4lRnFFgpsU', u'https://www.youtube.com/watch?v=Uo_iblfpjqg', u'https://www.youtube.com/watch?v=IlvGNn14FG0', u'https://www.youtube.com/watch?v=tWl6iDH_qFo', u'https://www.youtube.com/watch?v=5ugGDH0JrOA', u'https://www.youtube.com/watch?v=MI9bb2JYksM']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.11.04
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-52233-, ffprobe N-52233-
[debug] Proxy map: {}
[youtube] Confirming age
[youtube] y4lRnFFgpsU: Downloading webpage
[youtube] y4lRnFFgpsU: Downloading video info webpage
[youtube] y4lRnFFgpsU: Extracting video information
[youtube] y4lRnFFgpsU: Encrypted signatures detected.
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] {22} signature length 42.43, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 539, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 435, in _extract_signature_function
ExtractorError: Cannot identify player u'/yts/jsbin/player-vflZ_L_3c/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
 (caused by ExtractorError(u"Cannot identify player u'/yts/jsbin/player-vflZ_L_3c/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.",)); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 539, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 435, in _extract_signature_function
ExtractorError: Cannot identify player u'/yts/jsbin/player-vflZ_L_3c/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 536, in extract_info
  File "youtube_dl\extractor\common.pyo", line 199, in extract
  File "youtube_dl\extractor\youtube.pyo", line 934, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 549, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 539, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 435, in _extract_signature_function
ExtractorError: Cannot identify player u'/yts/jsbin/player-vflZ_L_3c/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
 (caused by ExtractorError(u"Cannot identify player u'/yts/jsbin/player-vflZ_L_3c/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.",)); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
