### ISSUE TITLE
Questions on the binary version and about the CLI

### ISSUE THREAD

**Issue by kepoorhampond** [rg3/youtube-dl#13330]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

I have a couple questions: is it possible to specify a logger or progress hook through the CLI? Can the binary release of `youtube-dl` still be "`imported`" into the rest of a python file? If it's not possible, then can a binary version that can do that be made? On that same tangent, is the binary release of `youtube-dl` only for the CLI?

**Comment by yan12125** [comment]
Yes it's possible:
```
$ python
Python 3.6.1 (default, Mar 27 2017, 00:27:06) 
[GCC 6.3.1 20170306] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append('./youtube-dl')
>>> import youtube_dl
>>> youtube_dl
<module 'youtube_dl' from 'youtube-dl/youtube_dl/__init__.py'>
```
