### ISSUE TITLE
Loading too much on --get-url and -g Please help me

### ISSUE THREAD

**Issue by praburamWAPKA** [rg3/youtube-dl#13333]
hii,
 im trying to print fastly direct download link using youtube-dl but loading very slowly and i also tried direct  python script because youtube-dl unzip and excuting the --get-url operation..

demo : [http://tamilkaka.net/utub.php?v=EnMsVPamT9E](demo link)
please help me 

`<?php

/Made By Praburam if Any Error Kindly Contact Me +919087811646 For Support Help/

$url = 'https://youtube.com/watch?v='.$_GET['v'].'';

$cmd =' youtube-dl -g -f36  ' . escapeshellarg($url);
$ss=shell_exec($cmd);
$vonee = preg_split('/\s+/', trim($ss));
$pat = '/^(https:\/\/)[a-zA-Z0-9\-.]+.googlevideo.com\//';
$prabu = print_r($vonee[0],true);
$results1 = preg_replace($pat, 'https://redirector.googlevideo.com/', $prabu);

$cmd2 =' python /usr/bin/yt/youtube-dl-master/youtube_dl/_main_.py -g  -f18  ' . escapeshellarg($url);
$ss1=shell_exec($cmd2);
$vonee1 = preg_split('/\s+/', trim($ss1));
$results2 = print_r($vonee1[0], true);
$results3 = preg_replace($pat, 'https://redirector.googlevideo.com/', $results2);

$cmd3 =' python /usr/bin/yt/youtube-dl-master/youtube_dl/_main_.py -g  -f22   ' . escapeshellarg($url);
$ss2=shell_exec($cmd3);
$vonee2 = preg_split('/\s+/', trim($ss2));
$results4 = print_r($vonee2[0], true);
$results5 = preg_replace($pat, 'https://redirector.googlevideo.com/', $results4);

$cmd4 =' python /usr/bin/yt/youtube-dl-master/youtube_dl/_main_.py -g  -f17  ' . escapeshellarg($url);
$ss3=shell_exec($cmd4);
$vonee3 = preg_split('/\s+/', trim($ss3));
$results33 = print_r($vonee3[0], true);
$results34 = preg_replace($pat, 'https://redirector.googlevideo.com/', $results33);

$name =' python /usr/bin/yt/youtube-dl-master/youtube_dl/_main_.py  -e ' .  escapeshellarg($url);
$ss4=shell_exec($name);
$vonee4 = preg_split('/\s+/', trim($ss4));
$outputs = print_r($ss4,true);

echo '<a href="'.$results34.'&title=[Tamilkaka.Net]'.$outputs.'.3gp">Download 3gp 176x144p</a>
<br/>
<a href="'.$results1.'&title=[TamilKAKA.Net]'.$outputs.'.mp4">Download MP4 320x240p</a><br/><a href="'.$results3.'&title=[TamilKAKA.Net]'.$outputs.'.mp4">Download MP4 640x360p</a><br/><a href="'.$results5.'&title=[TamilKAKA.Net]'.$outputs.'.mp4">Download MP4 HD720p</a><br/>
';
?>`

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
