### ISSUE TITLE
"--ffmpeg-location" in the embedded version of Youtube-dl

### ISSUE THREAD

**Issue by kepoorhampond** [rg3/youtube-dl#13337]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

Is there anyway to specify the `--ffmpeg-location` flag from the CLI into the embedded version of youtube-dl? Something like this?
```python
ydl_opts = {
    'ffmpeg-location': '/home/kepoor/.ffmpeg-binaries/
}

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download([video_url])
```
If it's not possible, it really should be, anything available in the CLI *should be easy to implement into the module version, right?

\* I'd think it would, but I don't know this for a fact.

**Comment by dstftw** [comment]
`ffmpeg_location`.
