### ISSUE TITLE
Unable to download JSON metadata: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by helloguangxue** [rg3/youtube-dl#13343]
youtube-dl --verbose https://app.pluralsight.com/library/courses/php-get-started/table-of-contents[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://app.pluralsight.com/library/courses/php-get-started/table-of-contents']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.05
[debug] Python version 2.7.10 - Darwin-16.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 12, avprobe 12, ffmpeg 3.3.1, ffprobe 3.3.1
[debug] Proxy map: {}
[pluralsight:course] php-get-started: Downloading course JSON
[download] Downloading playlist: PHP: Get Started
[pluralsight:course] playlist PHP: Get Started: Collected 34 video ids (downloading 34 of them)
[download] Downloading video 1 of 34
[pluralsight] php-get-started-m1-0: Downloading JSON metadata
[pluralsight] php-get-started-m1-0: Downloading mp4-high viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] php-get-started-m1-0: Waiting for 4 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 287, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1056, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl -U
**youtube-dl is up-to-date (2017.06.05)**

**Comment by dstftw** [comment]
You did not provide account credentials.

**Comment by Hrxn** [comment]
Just a blind guess, but maybe it is related:

You can get the same error
> WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden

on other sites, e.g. Vimeo. Regardless of account options. And it only appears for some videos, for example mostly older ones, I think.

Here is one that returns this error: https://vimeo.com/14074949
