### ISSUE TITLE
No manifest requested for Youtube non-live

### ISSUE THREAD

**Issue by tarunmangla** [rg3/youtube-dl#13345]
For live content I see calls made to manifest.googlevideo.com. However, for non-live content no such calls are made. Can you please tell me how does youtube-dl downloads manifest for non-live content? Plus, how is the manifest downloaded in a regular browser, given that there are no calls to manifest.googlevideo.com in the browser network trace.

**Comment by yan12125** [comment]
Some formats are served via DASH, which are available as manifests. Browsers may pick non-DASH formats so no manifests are downloaded.

**Comment by tarunmangla** [comment]
Can you please elaborate or point me where to look at on what other non-DASH formats does Youtube uses? I was under the impression that most of the adaptive streaming protocols such as MPEG-DASH and HLS require a manifest to be downloaded. Thanks!

**Comment by yan12125** [comment]
In general, YouTube uses monolithic files for non-DASH formats in non-live streams. You can get their URLs with ```--get-url``` via youtube-dl. On the webpage it's usually stored in a variable ```url_encoded_fmt_stream_map```.
