### ISSUE TITLE
How to organize a lynda downloaded course ? 

### ISSUE THREAD

**Issue by a-eid** [rg3/youtube-dl#13352]
** this is not an issue its just a question ** 
Hi

I have used `youtube-dl` to download from pluralsight and I use this regular expression to organize folder structure as well as videos names 
`/home/user-name/data/pluralsight/%(playlist)s/%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s`

however, this doesn't work with Lynda Idk why?

Thank you.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
