### ISSUE TITLE
Unrecognized option 'k'.

### ISSUE THREAD

**Issue by leiserfg** [rg3/youtube-dl#13362]
When running  
`youtube-dl 'https://twitter.com/TimeIapsevids/status/874448913901735936' `
it fails and prints:
```
Unrecognized option 'k'.
Error splitting the argument list: Option not found

ERROR: ffmpeg exited with code 1
```
 
ffmpeg version  3.3.2 
youtube-dl  2017.06.12

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
