### ISSUE TITLE
youtube-dl error content too short

### ISSUE THREAD

**Issue by Astril** [rg3/youtube-dl#13386]
Hi i need help in error content too short... ( using youtube-dl latest version on windows 8.1). Iam using this bat script for auto retry

if [%1]==[] echo URL missing & goto :EOF :retry youtube-dl %1 if ERRORLEVEL 1 goto retry

But the problem is i cant use --playlist--start and --no-part options with this bat file so can you help me with it?

**Comment by theStupidProwler** [comment]
why can't you use theses options? Do you have an error? be more precise. And, most of the time, the "avanced" options aren't working in batch files due to characters misundersting issues with cmd.exe

**Comment by theStupidProwler** [comment]
and use the [https://github.com/rg3/youtube-dl/issues/new](url)

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
