### ISSUE TITLE
ERROR: WARNING: unable to obtain file audio codec with ffprobe

### ISSUE THREAD

**Issue by bdriffield** [rg3/youtube-dl#13398]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v --extract-audio --audio-format mp3  --audio-quality  0 https://youtu.be/urge4dvw6gU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', 'https://youtu.be/urge4dvw6gU']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.12
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-86482-gbc40674, ffprobe N-86482-gbc40674
[debug] Proxy map: {}
[youtube] urge4dvw6gU: Downloading webpage
[youtube] urge4dvw6gU: Downloading video info webpage
[youtube] urge4dvw6gU: Extracting video information
[youtube] urge4dvw6gU: Downloading MPD manifest
[debug] Invoking downloader on 'https://r5---sn-vgqs7nel.googlevideo.com/videoplayback?clen=57622640&itag=251&expire=1497599428&keepalive
99.253.229.71&initcwndbps=1440000&ipbits=0&mime=audio%2Fwebm&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeep
DE3D5D4.53C695FFDCB274049E504F756F307BF08A3B74B9&lmt=1493359051932373&source=youtube&dur=3543.381&requiressl=yes&ratebypass=yes'
[download] ♫ Best Uplifting Trance Mix 2017 Vol. #2 [HD] ♫-urge4dvw6gU.webm has already been downloaded
[download] 100% of 54.95MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:♫ Best Uplifting Trance Mix 2017 Vol. #2 [HD] ♫-urge4dvw6gU.webm'
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\YoutubeDL.py", line 1965, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\postprocessor\ffmpeg.py", line 243, in run
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://youtu.be/urge4dvw6gU
- Single video: https://youtu.be/urge4dvw6gU
- Playlist: 

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

When attempting to extract audio using youtube-dl it fails with the following error message: Error: WARNING: unable to obtain file audio codec with ffprobe

**Comment by raniesantos** [comment]
Having the same problem.

**Comment by seanvree** [comment]
Having the same issue as well:

```
ERROR: WARNING: unable to obtain file audio codec with ffprobe
ERROR: WARNING: unable to obtain file audio codec with ffprobe
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
[09/22/17 18:01:26] WARNING: unable to extract uploader nickname
[09/22/17 18:03:45] ERROR: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[09/22/17 18:24:42] WARNING: unable to extract uploader nickname
[09/22/17 18:33:45] [debug] System config: []
[09/22/17 18:33:45] [debug] User config: []
[09/22/17 18:33:45] [debug] Custom config: []
[09/22/17 18:33:45] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\Administrator\\Downloads\\%(title)s.%(ext)s', '-f', '136', '-v', '--hls-prefer-native', 'https://www.youtube.com/watch?v=CMXiCR2gQw0']
[09/22/17 18:33:45] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[09/22/17 18:33:45] [debug] youtube-dl version 2017.09.15
[09/22/17 18:33:45] [debug] Python version 3.4.4 - Windows-10-10.0.15063
[09/22/17 18:33:45] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[09/22/17 18:33:45] [debug] Proxy map: {}
[09/22/17 18:39:30] [debug] System config: []
[09/22/17 18:39:30] [debug] User config: []
[09/22/17 18:39:30] [debug] Custom config: []
[09/22/17 18:39:30] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\Administrator\\Downloads\\%(title)s.%(ext)s', '-f', '22', '-v', '--hls-prefer-native', 'https://www.youtube.com/watch?v=CMXiCR2gQw0']
[09/22/17 18:39:30] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[09/22/17 18:39:30] [debug] youtube-dl version 2017.09.15
[09/22/17 18:39:30] [debug] Python version 3.4.4 - Windows-10-10.0.15063
[09/22/17 18:39:30] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[09/22/17 18:39:30] [debug] Proxy map: {}
[09/22/17 18:44:46] [debug] System config: []
[09/22/17 18:44:46] [debug] User config: []
[09/22/17 18:44:46] [debug] Custom config: []
[09/22/17 18:44:46] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\Administrator\\Downloads\\%(title)s.%(ext)s', '-x', '--audio-format', 'mp3', '--audio-quality', '0', '-v', '--hls-prefer-native', 'https://www.youtube.com/watch?v=CMXiCR2gQw0']
[09/22/17 18:44:46] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[09/22/17 18:44:46] [debug] youtube-dl version 2017.09.15
[09/22/17 18:44:46] [debug] Python version 3.4.4 - Windows-10-10.0.15063
[09/22/17 18:44:46] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[09/22/17 18:44:46] [debug] Proxy map: {}
```

**Comment by michaelcaterisano** [comment]
Same issue. Works on some videos but not others. 

```
youtube-dl -x -v https://www.youtube.com/watch?v=QOmSQfYB1iE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '-v', 'https://www.youtube.com/watch?v=QOmSQfYB1iE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 3.6.0 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg present, ffprobe present
[debug] Proxy map: {}
[youtube] QOmSQfYB1iE: Downloading webpage
[youtube] QOmSQfYB1iE: Downloading video info webpage
[youtube] QOmSQfYB1iE: Extracting video information
[youtube] QOmSQfYB1iE: Downloading MPD manifest
[debug] Invoking downloader on 'https://r1---sn-8xgp1vo-xfgl.googlevideo.com/videoplayback?lmt=1496647424296569&dur=345.021&clen=5857113&gir=yes&signature=638502396DE19CED354E5E58D9895FC3A1DA186E.A52E0B38DDFAE1D131F642A68DB6A4855C33B776&initcwndbps=1100000&pcm2cms=yes&key=yt6&mime=audio%2Fwebm&expire=1508474512&ei=MCrpWZPHF4eQ8wTv_rW4AQ&pl=24&keepalive=yes&id=o-AD61mw7LqA-JPdqsJBOZmqnOeQWJ_y9XbAG3w7RmbJ6h&mv=m&mt=1508452828&ms=au&mn=sn-8xgp1vo-xfgl&mm=31&ip=98.113.120.102&ipbits=0&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&requiressl=yes&itag=251&source=youtube&ratebypass=yes'
[download] Destination: Jerry Seinfeld - The Supermarket Experience-QOmSQfYB1iE.webm
[download] 100% of 5.59MiB in 00:06
[debug] ffmpeg command line: ffprobe -show_streams 'file:Jerry Seinfeld - The Supermarket Experience-QOmSQfYB1iE.webm'
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/Users/michaelcaterisano/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2031, in post_process
    files_to_delete, info = pp.run(info)
  File "/Users/michaelcaterisano/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 243, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe
```

**Comment by Hrxn** [comment]
What version is that actually supposed to be?
> `[debug] exe versions: ffmpeg present, ffprobe present`

Maybe try updating FFmpeg.

**Comment by bdriffield** [comment]
I tired updating everything and nothing worked for me so I took matters into my own hands a found a work around.

* I downloaded youtube-dl and extracted it into it's own folder
* Next I downloaded and extracted the contents of ffmpeg, ffplay, ffprobe and placed it all into the same folder
* Finally I just navigate to the folder directly and initiate my downloads calling the exe from there while pointing to same directory as the target for --ffmpeg

===============================================================
 .\youtube-dl.exe -x --audio-format mp3  --audio-quality 320K https://www.youtube.com/watch?v=WlJcmMT1BYY --ffmpeg-location C:\Users\bdriffield\Downloads\youtube-dl\ffmpeg.exe
===============================================================

PS C:\Users\bdriffield\Downloads\youtube-dl>

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2017-10-17   3:35 PM                Music
-a----       2015-03-08  10:12 PM       48487732 avcodec-56.dll
-a----       2015-03-08  10:12 PM         117056 avcodec.lib
-a----       2015-03-08  10:12 PM         817048 avconv.exe
-a----       2015-03-08  10:12 PM         129955 avdevice-55.dll
-a----       2015-03-08  10:12 PM           4594 avdevice.lib
-a----       2015-03-08  10:12 PM        2970299 avfilter-5.dll
-a----       2015-03-08  10:12 PM          38090 avfilter.lib
-a----       2015-03-08  10:12 PM       14516805 avformat-56.dll
-a----       2015-03-08  10:12 PM          77214 avformat.lib
-a----       2015-03-08  10:12 PM         918085 avplay.exe
-a----       2015-03-08  10:12 PM         366914 avprobe.exe
-a----       2015-03-08  10:12 PM         451231 avresample-2.dll
-a----       2015-03-08  10:12 PM          17914 avresample.lib
-a----       2015-03-08  10:12 PM         856146 avutil-54.dll
-a----       2015-03-08  10:12 PM         201902 avutil.lib
-a----       2017-09-19  12:14 AM       42311680 ffmpeg.exe
-a----       2017-09-19  12:14 AM       42193920 ffplay.exe
-a----       2017-09-19  12:14 AM       42219520 ffprobe.exe
-a----       2017-09-21  10:29 AM       30369534 libav-11.3-win64.7z
-a----       2014-11-22   7:13 AM         192283 libexpat-1.dll
-a----       2014-11-09   5:51 PM         817226 libfdk-aac-0.dll
-a----       2014-11-09   7:48 PM         633671 libgmp-10.dll
-a----       2014-11-09   7:48 PM          67739 libgmpxx-4.dll
-a----       2014-11-25   6:21 AM         337671 libjpeg-62.dll
-a----       2014-11-18   3:57 AM         337533 libmp3lame-0.dll
-a----       2014-11-15   6:36 PM          51417 libogg-0.dll
-a----       2014-11-19  12:08 AM         247091 libopencore-amrnb-0.dll
-a----       2014-11-19  12:08 AM         121932 libopencore-amrwb-0.dll
-a----       2014-11-15   6:38 PM         378546 libopus-0.dll
-a----       2014-11-25   6:24 AM         269928 libpng16-16.dll
-a----       2014-11-25   6:21 AM         364205 libturbojpeg-0.dll
-a----       2014-11-22   6:36 AM         156574 libvo-aacenc-0.dll
-a----       2014-11-19  12:09 AM         152049 libvo-amrwbenc-0.dll
-a----       2014-11-15   6:37 PM         223946 libvorbis-0.dll
-a----       2014-11-15   6:37 PM        1665673 libvorbisenc-2.dll
-a----       2014-11-15   6:37 PM          65441 libvorbisfile-3.dll
-a----       2014-11-25   6:26 AM         358927 libwebp-4.dll
-a----       2014-11-25   6:26 AM         207685 libwebpdecoder-0.dll
-a----       2014-11-25   6:26 AM          40801 libwebpdemux-0.dll
-a----       2014-11-25   6:26 AM          58927 libwebpmux-0.dll
-a----       2014-11-22   6:43 AM        1218719 libx264-142.dll
-a----       2015-03-08  10:12 PM        1442712 swscale-3.dll
-a----       2015-03-08  10:12 PM          28616 swscale.lib
-a----       2017-09-21  10:25 AM        7792744 youtube-dl.exe
-a----       2014-11-22   7:11 AM         137857 zlib1.dll

**Comment by Hrxn** [comment]
?

Fix that formatting please.
And on Windows, you can use `where ffmpeg` in _CMD_ to find out which ffmpeg binary gets used (first).

**Comment by bdriffield** [comment]
So I used `where ffmpeg` and it's location is below:

`C:\Users\bdriffield\scoop\shims\ffmpeg.exe`

I then proceeded to change the location from the target folder to the where it's located in windows and got the same error

```
 C:\Users\bdriffield\Downloads\youtube-dl>
 .\youtube-dl.exe -x --audio-format mp3  --audio-quality 320K https://www.youtube.com/watch?v=WlJcmMT1BYY --ffmpeg-location C:\Users\bdriffield\scoop\shims\ffmpeg.exe
[youtube] WlJcmMT1BYY: Downloading webpage
[youtube] WlJcmMT1BYY: Downloading video info webpage
[youtube] WlJcmMT1BYY: Extracting video information
[youtube] WlJcmMT1BYY: Downloading MPD manifest
[download] Destination: ♫ Best Progressive House Mix 2017 Vol. #19 [HD] ♫-WlJcmMT1BYY.webm
[download] 100% of 116.05MiB in 00:01
ERROR: WARNING: unable to obtain file audio codec with ffprobe
```

I also updated scoop and ran it again and still received the same error. I even also updated ffprobe as well and still receive the same error.

**Comment by Hrxn** [comment]
Okay, first of all, that result of `where` is good, and it you don't need to use `--ffmpeg-location` then, because that's already what is used.

I'm starting to think it's not the ffmpeg version.

I will see if I can reproduce..

Second, for debugging etc. please run youtube-dl with `-v` and `--ignore-config`, in general.

Like this:
````
youtube-dl.exe -v --ignore-config -x --audio-format mp3 --audio-quality 320K https://www.youtube.com/watch?v=WlJcmMT1BYY
````

**Comment by bdriffield** [comment]
Ok that seemed to work fine with no errors and the mp3 file is in the directory opposed to the .webm file:

```
PS C:\Users\bdriffield\Downloads\youtube-dl> youtube-dl.exe -v --ignore-config -x --audio-format mp3 --audio-quality 320K https://www.youtube.com/watch?v=WlJcmMT1BYY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '-x', '--audio-format', 'mp3', '--audio-quality', '320K', 'https://www.youtube.com/watch?v=WlJcmMT1BYY']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg N-87327-g18821e3, ffprobe N-87327-g18821e3
[debug] Proxy map: {}
[youtube] WlJcmMT1BYY: Downloading webpage
[youtube] WlJcmMT1BYY: Downloading video info webpage
[youtube] WlJcmMT1BYY: Extracting video information
[youtube] WlJcmMT1BYY: Downloading MPD manifest
[debug] Invoking downloader on 'https://r1---sn-tt1e7n7k.googlevideo.com/videoplayback?keepalive=yes&clen=121684434&gir=yes&key=yt6&signature=DF8A6DA9D1F093CA3E5B99C9EA26124A728803C1.C6CFCC555920C9D9371B2F7D03D07180F5DF30D4&mime=audio%2Fwebm&initcwndbps=19570000&lmt=1508402534728895&itag=251&expire=1508533894&ipbits=0&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&source=youtube&dur=7199.961&requiressl=yes&id=o-AEE2IsOx2K2ARLPZJR8oWTqBw3BL1_8nAHT5lNphlxfz&pl=21&mn=sn-tt1e7n7k&mm=31&ms=au&mv=m&mt=1508512217&ip=216.40.38.249&ei=JRLqWZi5OcLIDa20voAM&ratebypass=yes'
[download] Destination: ♫ Best Progressive House Mix 2017 Vol. #19 [HD] ♫-WlJcmMT1BYY.webm
[download] 100% of 116.05MiB in 00:01
[debug] avconv command line: avprobe -show_streams "file:♫ Best Progressive House Mix 2017 Vol. #19 [HD] ♫-WlJcmMT1BYY.webm"
[ffmpeg] Destination: ♫ Best Progressive House Mix 2017 Vol. #19 [HD] ♫-WlJcmMT1BYY.mp3
[debug] ffmpeg command line: avconv -y -i "file:♫ Best Progressive House Mix 2017 Vol. #19 [HD] ♫-WlJcmMT1BYY.webm" -vn -acodec libmp3lame "-b:a" 320k "file:♫ Best Progressive House Mix 2017 Vol. #19 [HD] ♫-WlJcmMT1BYY.mp3"
Deleting original file ♫ Best Progressive House Mix 2017 Vol. #19 [HD] ♫-WlJcmMT1BYY.webm (pass -k to keep)
```

**Comment by Hrxn** [comment]
Good. Yeah, just wanted to say, works for me as well.
Conversion takes a while (longer than download), but okay, probably expected.

**Comment by bdriffield** [comment]
I'm definitely ok with waiting a little bit longer for conversion vc having it flat out fail. Thanks for the recommendation and your help @Hrxn !.

**Comment by michaelcaterisano** [comment]
Still doesn't work for me.

`youtube-dl -v --ignore-config -x --audio-format mp3 --audio-quality 320K https://mail.google.com/mail/u/0/#inbox/15f3a0e0acc13c03
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '-x', '--audio-format', 'mp3', '--audio-quality', '320K', 'https://mail.google.com/mail/u/0/#inbox/15f3a0e0acc13c03']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 3.6.0 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg present, ffprobe present
[debug] Proxy map: {}
[generic] 15f3a0e0acc13c03: Requesting header
[redirect] Following redirect to https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.google.com/mail/&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1
[generic] &ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] &ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1: Downloading webpage
[generic] &ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1: Extracting information
[download] Downloading playlist: Gmail
[generic] playlist Gmail: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[debug] Invoking downloader on "https://accounts.google.com/Captcha?v=2&ctoken='+_.Mv(a)+'&kind=audio"
[download] Destination: Gmail (1)-&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1-1.unknown_video
[download] 100% of 29.36KiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams 'file:Gmail (1)-&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1-1.unknown_video'
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/Users/michaelcaterisano/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2031, in post_process
    files_to_delete, info = pp.run(info)
  File "/Users/michaelcaterisano/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 243, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe`

**Comment by Hrxn** [comment]
> I'm definitely ok with waiting a little bit longer for conversion vs having it flat out fail.

Of course.. and after all, it's a two hours long audio file.

@michaelcaterisano Try it with an updated ffmpeg version..

**Comment by michaelcaterisano** [comment]
I'm on version 3.4 which is the highest I can find.

**Comment by remitamine** [comment]
@michaelcaterisano i don't understand why you pass a Gmail urls to youtube-dl, obviously the file that has been downloaded is not a media file(most likely it's an html file) and ffmpeg won't be able to anything with it.

**Comment by michaelcaterisano** [comment]
wowie, typo in the thread. Same result with this youtube link though. 

`youtube-dl -v --ignore-config -x --audio-format mp3 --audio-quality 320K https://www.youtube.com/watch?v=9lHjeEkS1WE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '-x', '--audio-format', 'mp3', '--audio-quality', '320K', 'https://www.youtube.com/watch?v=9lHjeEkS1WE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 3.6.0 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg present, ffprobe present
[debug] Proxy map: {}
[youtube] 9lHjeEkS1WE: Downloading webpage
[youtube] 9lHjeEkS1WE: Downloading video info webpage
[youtube] 9lHjeEkS1WE: Extracting video information
[youtube] 9lHjeEkS1WE: Downloading MPD manifest
[debug] Invoking downloader on 'https://r3---sn-8xgp1vo-xfgee.googlevideo.com/videoplayback?keepalive=yes&clen=2380453&gir=yes&source=youtube&key=yt6&signature=3080A7019F433F7FC0C8CE4111C8962DEB3C2A31.86E26C4D8367EDE63664F9413812C74BB5B9BC8D&mime=audio%2Fwebm&lmt=1487947932033491&initcwndbps=1158750&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&expire=1508561085&ipbits=0&dur=136.101&requiressl=yes&id=o-AEVhOpHR1kgoylnU-QJ9RfeInHjmU3SRQ7wBPta4FbpZ&pl=24&mn=sn-8xgp1vo-xfgee&mm=31&ip=98.113.120.102&ms=au&mv=m&mt=1508539371&ei=XXzqWb2XK6OX8gT9jq64DA&itag=251&ratebypass=yes'
[download] Destination: Thundercat - 'Uh Uh'-9lHjeEkS1WE.webm
[download] 100% of 2.27MiB in 00:01
[debug] ffmpeg command line: ffprobe -show_streams 'file:Thundercat - '"'"'Uh Uh'"'"'-9lHjeEkS1WE.webm'
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/Users/michaelcaterisano/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2031, in post_process
    files_to_delete, info = pp.run(info)
  File "/Users/michaelcaterisano/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 243, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe`

**Comment by Hrxn** [comment]
That still shows
> `[debug] exe versions: ffmpeg present, ffprobe present`

I don't know what this is. Normally, ffmpeg always prints it real version number, or the commit ID if it's a git build, but not `present`

Not completely sure about macOS, but I'd guess it is the same there.

**Comment by remitamine** [comment]
works fine for me:
```
youtube-dl -v --ignore-config -x --audio-format mp3 --audio-quality 320K https://www.youtube.com/watch?v=9lHjeEkS1WE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '-x', '--audio-format', 'mp3', '--audio-quality', '320K', 'https://www.youtube.com/watch?v=9lHjeEkS1WE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.01
[debug] Python version 3.6.2 - Linux-4.9.50-1-MANJARO-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 9lHjeEkS1WE: Downloading webpage
[youtube] 9lHjeEkS1WE: Downloading video info webpage
[youtube] 9lHjeEkS1WE: Extracting video information
[youtube] {22} signature length 43.43, html5 player vflcNAJUd
[youtube] 9lHjeEkS1WE: Downloading player https://www.youtube.com/yts/jsbin/player-vflcNAJUd/en_US/base.js
[youtube] {43} signature length 43.43, html5 player vflcNAJUd
[youtube] {18} signature length 43.43, html5 player vflcNAJUd
[youtube] {36} signature length 43.43, html5 player vflcNAJUd
[youtube] {17} signature length 43.43, html5 player vflcNAJUd
[youtube] {137} signature length 43.43, html5 player vflcNAJUd
[youtube] {248} signature length 43.43, html5 player vflcNAJUd
[youtube] {136} signature length 43.43, html5 player vflcNAJUd
[youtube] {247} signature length 43.43, html5 player vflcNAJUd
[youtube] {135} signature length 43.43, html5 player vflcNAJUd
[youtube] {244} signature length 43.43, html5 player vflcNAJUd
[youtube] {134} signature length 43.43, html5 player vflcNAJUd
[youtube] {243} signature length 43.43, html5 player vflcNAJUd
[youtube] {133} signature length 43.43, html5 player vflcNAJUd
[youtube] {242} signature length 43.43, html5 player vflcNAJUd
[youtube] {160} signature length 43.43, html5 player vflcNAJUd
[youtube] {278} signature length 43.43, html5 player vflcNAJUd
[youtube] {140} signature length 43.43, html5 player vflcNAJUd
[youtube] {171} signature length 43.43, html5 player vflcNAJUd
[youtube] {249} signature length 43.43, html5 player vflcNAJUd
[youtube] {250} signature length 43.43, html5 player vflcNAJUd
[youtube] {251} signature length 43.43, html5 player vflcNAJUd
[youtube] 9lHjeEkS1WE: Downloading MPD manifest
[debug] Invoking downloader on 'https://r3---sn-5abxgpxuxaxjvh-j1ae.googlevideo.com/videoplayback?key=yt6&mime=audio%2Fwebm&keepalive=yes&clen=2380453&gir=yes&id=o-ALrA6LmmbNZCFZ0ETIX_kGdq6qL8vUyaNktNkIR2Kd2a&ei=xVbrWciOKJSTcuTfoeAP&ip=105.107.170.77&ms=au&mv=m&mt=1508595291&itag=251&dur=136.101&requiressl=yes&source=youtube&pl=18&mn=sn-5abxgpxuxaxjvh-j1ae&mm=31&expire=1508616997&ipbits=0&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&initcwndbps=70000&lmt=1487947932033491&signature=948B15804FEC538A3D475EE5B4D0B592BBD9DADE.D5F0A6F4AA09CDB5D797A8262B3CF6E7964CBEC8&ratebypass=yes'
[download] Destination: Thundercat - 'Uh Uh'-9lHjeEkS1WE.webm
[download] 100% of 2.27MiB in 00:06
[debug] ffmpeg command line: ffprobe -show_streams 'file:Thundercat - '"'"'Uh Uh'"'"'-9lHjeEkS1WE.webm'
[ffmpeg] Destination: Thundercat - 'Uh Uh'-9lHjeEkS1WE.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:Thundercat - '"'"'Uh Uh'"'"'-9lHjeEkS1WE.webm' -vn -acodec libmp3lame -b:a 320k 'file:Thundercat - '"'"'Uh Uh'"'"'-9lHjeEkS1WE.mp3'
Deleting original file Thundercat - 'Uh Uh'-9lHjeEkS1WE.webm (pass -k to keep)
```
@michaelcaterisano post the output of `ffmpeg -version`

**Comment by stasbar** [comment]
Solved by `brew upgrade ffmpeg`
```sh
~ » youtube-dl --extract-audio --audio-format mp3 "https://youtu.be/xxx"                                                                                                            stasbar@stasbar
[youtube] eT3at25Kits: Downloading webpage
[youtube] eT3at25Kits: Downloading video info webpage
[download] Destination: xxx.webm
[download] 100% of 2.32MiB in 00:00
ERROR: WARNING: unable to obtain file audio codec with ffprobe
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~ » ffmpeg -v                                                                                                                                                                          stasbar@stasbar
dyld: Library not loaded: /usr/local/opt/x265/lib/libx265.165.dylib
  Referenced from: /usr/local/bin/ffmpeg
  Reason: image not found
[1]    31817 abort      ffmpeg -v
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~ » brew upgrade ffmpeg
...
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~ » youtube-dl --extract-audio --audio-format mp3 "https://youtu.be/xxx"                                                                                                            stasbar@stasbar
[youtube] eT3at25Kits: Downloading webpage
[youtube] eT3at25Kits: Downloading video info webpage
[download] xxx.webm has already been downloaded
[download] 100% of 2.32MiB
[ffmpeg] Destination: xxx.mp3
Deleting original file Mr. xxx.webm (pass -k to keep)
```
