### ISSUE TITLE
youtube-dl latest version error The connection has timed out  The server at r7---sn-bvvbax-nuae.googlevideo.com is taking too long to respond.

### ISSUE THREAD

**Issue by rdxhere** [rg3/youtube-dl#13409]
## youtube-dl latest version error

The connection has timed out  The server at r7---sn-bvvbax-nuae.googlevideo.com is taking too long to respond.

youtube stop to download extract videos on youtube-dl

The server at r7---sn-bvvbax-nuae.googlevideo.com is taking too long to respond.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
---
i updated youtube-dl -U on My Centos6

**Comment by yan12125** [comment]
This is most likely the same situation as #11779.
