### ISSUE TITLE
limit_rate does not limit rate when downloading with python

### ISSUE THREAD

**Issue by PhantomGitHub** [rg3/youtube-dl#13401]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.12**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

The issue is that the "limit_rate" argument to the youtube_dl library in python seems not to be working. exmaple code:
`import youtube_dl`
`youtube_dl.YoutubeDL({'limit_rate':'50K'}).download(['dQw4w9WgXcQ'])`
The code above preforms download at very high rates, higher than 50Kbps. On my internet connection it was higher than 1MBps, that's more that 20 times the wanted rate.
What am i missing?
Thanks!

**Comment by yan12125** [comment]
The name in Python API is ```ratelimit```, not ```limit_rate```.

**Comment by PhantomGitHub** [comment]
Oh, sorry about that.

Where can i find the list of all the names in the Python API? i couldn't find it in the documentation.

**Comment by yan12125** [comment]
FYI: Almost all field names can be found in the following places:
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L134
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/downloader/common.py#L29

**Comment by PhantomGitHub** [comment]
Thanks for the reference, but the correction you suggested does not seem to be working. the line:

`youtube_dl.YoutubeDL({'ratelimit': '50K'}).download(['dQw4w9WgXcQ'])`

Seems to be doing the same thing. I got way more that 1MBps with that line as well.

**Comment by yan12125** [comment]
Well, it should be:

youtube_dl.YoutubeDL({'ratelimit': 50000}).download(['dQw4w9WgXcQ'])

The value should be a number.

**Comment by PhantomGitHub** [comment]
Hmm... thanks. It seems like the documentation is a bit lacking in this subject. I assumed it was the same format from the command line interface.

**Comment by dstftw** [comment]
You did not read documentation carefully. It clearly states:
>Most likely, you'll want to use various options. For a list of options available, have a look at [`youtube_dl/YoutubeDL.py`](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L129-L279).

**Comment by PhantomGitHub** [comment]
Oh, thanks, I did not see that line, sorry.
