### ISSUE TITLE
VVVVID -> video/kenc -> manifest link is different, also the fragments links -> http 403

### ISSUE THREAD

**Issue by FaX-GitHub** [rg3/youtube-dl#13406]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.12**

- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.vvvvid.it/#!show/173/terra-formars/219/458056/mutazione', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.12
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[VVVVID] Downloading JSON metadata
[VVVVID] 458056: Downloading JSON metadata
[VVVVID] 458056: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[VVVVID] 458056: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[VVVVID] 458056: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[VVVVID] 458056: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\...\youtube_dl\YoutubeDL.py", line 762, in extract_info
  File "C:\...\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\...\youtube_dl\extractor\vvvvid.py", line 124, in _real_extract
  File "C:\...\youtube-dl\extractor\common.py", line 1056, in _sort_formats
```

webpage url
`https://www.vvvvid.it/#!show/173/terra-formars/219/458056/mutazione`

manifest link decoded from json:
`http://vvvvid-vh.akamaihd.net/z/Dynit2/Terraformars/TerraFormarsU_Ep01m.mp4/manifest.f4m`

to get the full link for the manifest:
`https://www.vvvvid.it/kenc?action=kt&url=http://vvvvid-vh.akamaihd.net/z/Dynit2/Terraformars/TerraFormarsU_Ep01m.mp4/manifest.f4m&conn_id=CONNECTIONIDHERE`

reply (json)
```
{
    "message": "encoded string, the same way as embed_info",
   "result": "ok"
}
```
corect link:
`manifesturl + ? + decoded string from the other link + &hdcore=3.6.0&plugin=aasp-3.6.0.50.41`

also the segmnets link are different from video/rcs

**Comment by wxjeacen** [comment]
same 403 Error occurred in my Server...

Any updates?
