### ISSUE TITLE
proxychains youtube-dl https://www.youtube.com/watch?v=SarlTxrAbIY

### ISSUE THREAD

**Issue by liangzi1216** [rg3/youtube-dl#13412]
proxychains youtube-dl https://www.youtube.com/watch?v=SarlTxrAbIY
ProxyChains-3.1 (http://proxychains.sf.net)
[youtube] SarlTxrAbIY: Downloading webpage
|S-chain|-<>-127.0.0.1:1080-<><>-61.91.161.217:443-<><>-OK
ERROR: Unable to download webpage: IncompleteRead(2249 bytes read) (caused by IncompleteRead(2249 bytes read)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
~

**Comment by liangzi1216** [comment]
>zypper info youtube-dl
正在加载软件源数据...
正在读取已安装的软件包...


软件包 youtube-dl 的信息：
--------------------------
软件源     : tsinghua-packman                   
名称       : youtube-dl                         
版本       : 2017.06.12-1.1                     
架构       : noarch                             
厂商       : http://packman.links2linux.de      
已安装大小 : 1.6 MiB                            
已安装     : 是                                 
状态       : 最新                               
源代码包   : youtube-dl-2017.06.12-1.1.src      
摘要       : A tool for downloading from Youtube
描述       :                                    
    youtube-dl is a small command-line program to retrieve videos from
    YouTube.com and a few more sites.

**Comment by dstftw** [comment]
`--proxy`.
