### ISSUE TITLE
How do I skip live streams when archiving a youtube channel? 

### ISSUE THREAD

**Issue by beigexperience** [rg3/youtube-dl#13418]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other
    
How do I skip live streams when archiving a youtube channel? Is there an option to ignore streams which are live right now?

**Comment by yan12125** [comment]
See #12946.
