### ISSUE TITLE
Gui and browser plug in

### ISSUE THREAD

**Issue by jemilu2** [rg3/youtube-dl#13428]
Please is there any plan to create a gui version of this program and also a browser plug in that would pop up just like idm. I am seriously thinking about it because I have been yearning for an IDM alternative for a while now and I know I am not the only one. I have been using youtubedl on my linux distro but I am hoping to make it available to a wider audience

**Comment by h1z1** [comment]
"make it available to a wider audience" ??? Why would anyone want to do this?  Quickest way to get sites banning ytdl and pushing DRM.

Please, do not do this.

**Comment by dstftw** [comment]
No such plans.

**Comment by jemilu2** [comment]
I didn't know that youtubedl could be banned from some websites. But if the project is not meant to be available to a wider audience, why does it exist anyway.
On Jun 19, 2017 1:25 AM, h1z1 <notifications@github.com> wrote:"make it available to a wider audience" ??? Why would anyone want to do this?  Quickest way to get sites banning ytdl and pushing DRM.
Please, do not do this.

**Comment by h1z1** [comment]
There's a difference between personal use and profit.   There already are sites that exist for no other reason but to steal content and offer it as their own under the same guise.   They are for example a cancer on cam sites.

**Comment by dstftw** [comment]
Offtopic.
