### ISSUE TITLE
[Vrt, Ketnet] Extractors broken

### ISSUE THREAD

**Issue by midas02** [rg3/youtube-dl#13426]
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

[VRT] terzake: Downloading webpage
[VRT] 3004078: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 11001] getaddrinfo failed>
[VRT] 3004078: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno 11001] getaddrinfo failed>
[VRT] 3004078: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno 11001] getaddrinfo failed>
ERROR: unable to download video data: <urlopen error [Errno 11001] getaddrinfo failed>

### Description of your *issue*, suggested solution and other information
Sample links:
http://deredactie.be/cm/vrtnieuws/videozone/programmas/journaal/
http://sporza.be/cm/sporza/videozone/programmas/sportweekend
http://www.ketnet.be/kijken/karrewiet/17-juni-2017-uitzending

**Comment by midas02** [comment]
For VRT.py the process can be fixed by adding something like:

```     
        mzid = self._search_regex(
            r'data-video-mzid="([^"]+)"', webpage, 'video mzid', default=None)

...

        if mzid:
            display_id = self._match_id(url)
            data = self._download_json('https://mediazone.vrt.be/api/v1/polopoly/assets/'+mzid, display_id)
            for target in data['targetUrls']:
                format_url, format_type = target.get('url'), target.get('type')
                if not format_url or not format_type:
                    continue
                if format_type == 'HLS':
                    formats.extend(self._extract_m3u8_formats(
                        format_url, display_id, entry_protocol='m3u8_native',
                        ext='mp4', preference=0, fatal=False, m3u8_id=format_type))
                elif format_type == 'HDS':
                    formats.extend(self._extract_f4m_formats(
                        format_url, display_id, f4m_id=format_type, fatal=False))
                elif format_type == 'MPEG_DASH':
                    formats.extend(self._extract_mpd_formats(
                        format_url, display_id, mpd_id=format_type, fatal=False))
                else:
                    formats.append({
                        'format_id': format_type,
                        'url': format_url,
                    })
        elif src:

**Comment by midas02** [comment]
For Ketnet.py, the following could be used:

```
      mzid = config.get('mzid')
        if mzid:
            display_id = self._match_id(url)
            data = self._download_json('https://mediazone.vrt.be/api/v1/ketnet/assets/'+mzid, display_id)
            for target in data['targetUrls']:
                format_url, format_type = target.get('url'), target.get('type')
                if not format_url or not format_type:
                    continue
                if format_type == 'HLS':
                    formats.extend(self._extract_m3u8_formats(
                        format_url, display_id, entry_protocol='m3u8_native',
                        ext='mp4', preference=0, fatal=False, m3u8_id=format_type))
                elif format_type == 'HDS':
                    formats.extend(self._extract_f4m_formats(
                        format_url, display_id, f4m_id=format_type, fatal=False))
                elif format_type == 'MPEG_DASH':
                    formats.extend(self._extract_mpd_formats(
                        format_url, display_id, mpd_id=format_type, fatal=False))
                else:
                    formats.append({
                        'format_id': format_type,
                        'url': format_url,
                    })
        else:

**Comment by midas02** [comment]
@yan12125 I have a question for you. When I look at the format codes for the following video, I get:

> C:\>youtube-dl.exe http://deredactie.be/cm/vrtnieuws/videozone/ookdatnog/1.3002814 -F
[VRT] 1.3002814: Downloading webpage
[VRT] 3002814: Downloading m3u8 information
[VRT] 3002814: Downloading f4m manifest
[VRT] 3002814: Downloading MPD manifest
[VRT] 3002814: Downloading SMIL file
[info] Available formats for 3002814:
format code  extension  resolution note
dash-p0a1r1  m4a        audio only [eng] DASH audio   62k , mp4a.40.2 (24000Hz)
...
dash-p0a0r0  mp4        960x540    DASH video 1907k , avc1.4d401f, 25fps, video only
hds-204      flv        416x234     204k
....
hls-2096     mp4        960x540    2096k
http-2096    mp4        960x540    2096k  (best)

So the last entry is marked as "BEST". However, when I start downloading it without adding '-f best', it downloads the DASH entry. It's only when I explicitly add '-f best', that it downloads the last entry.
Is this some kind of bug?

**Comment by yan12125** [comment]
> Is this some kind of bug?

Nope. The default format has been '-f bestvideo+bestaudio' for a while. In this case bestvideo is the DASH one.

**Comment by midas02** [comment]
@yan12125 Ok, but in this case the last entry has the same resolution, and even has a higher bitrate than the individual video and audio streams combined. I'm trying to understand why he still goes for the DASH segments, which, on top of that, requires additional postprocessing (multiplexing).

**Comment by midas02** [comment]
Links like thise one will need fixing as well: http://sporza.be/cm/sporza/voetbal/1.3009787
