### ISSUE TITLE
Vimeo extracter not returning valid mp4 URLs

### ISSUE THREAD

**Issue by smithb1994** [rg3/youtube-dl#13433]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --get-url --format=mp4 https://vimeo.com/221447808 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--get-url', u'--format=mp4', u'https://vimeo.com/221447808', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.18
[debug] Python version 2.7.12 - Linux-4.8.0-54-generic-x86_64-with-LinuxMint-18.1-serena
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}  
  
https://skyfire.vimeocdn.com/1497896520-0x6d08e294d0eac34d6cae41733e4ed3f3458152b5/221447808/video/773179232,773179234,773179233,773179230/../
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

I'm trying to get an mp4 url link back from vimeo, but every time when I do the command `youtube-dl --get-url --format=mp4 <vimeo_link>` with any new vimeo links, I get either an invalid url, or I get an m3u8 file.  

Example:
Command
`youtube-dl --get-url --format=mp4 https://vimeo.com/221447808`
Output
`https://skyfire.vimeocdn.com/1497897157-0x477f5dd17b9b6623dfd7dbf5970927e83b093a95/221447808/video/773179232,773179234,773179233,773179230/../`

Command  
`youtube-dl --get-url --format=mp4 https://vimeo.com/221901475`  
Output  
`https://skyfire.vimeocdn.com/1497897059-0xb2edd2c6fc153178cb65f717f57188e326ca6d8c/221901475/video/774640155/playlist.m3u8`  
  

And yes, I'm on an up to date version `2017.06.18`

**Comment by dstftw** [comment]
Best quality mp4 for https://vimeo.com/221447808 served as DASH so you get base URL to DASH manifest.
Best qualifty mp4 for https://vimeo.com/221901475 served as m3u8 so you get URL to m3u8 manifest.

**Comment by smithb1994** [comment]
@dstftw  But how do I get just a regular .mp4 file link with youtube-dl. Some links give me it, and some don't. I just want the url to an mp4 file when I ask for mp4 format, instead I'm getting an m3u8. Is there a command in youtube-dl to just get the raw mp4 link? I couldn't find an answer to this going through the docs, or the past github issues. Can you answer it here for future reference?

**Comment by dstftw** [comment]
`-f '([protocol=https]/[protocol=http])[ext=mp4]'`. Read [FAQ](https://github.com/rg3/youtube-dl#format-selection).
