### ISSUE TITLE
[ComedyCentralFullEpisodes] Extractor "ERROR: Failed to download m3u8 information: HTTP Error 404: Not Found (caused by HTTPError());"

### ISSUE THREAD

**Issue by Wandang** [rg3/youtube-dl#13452]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl --verbose http://www.cc.com/shows/the-daily-show-with-trevor-noah/full-episodes
[debug] System config: [u'-o', u'~/youtube-dl/%(title)s.%(ext)s', u'-c']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.cc.com/shows/the-daily-show-with-trevor-noah/full-episodes']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.18
[debug] Python version 2.7.13 - Linux-4.9.0-3-amd64-x86_64-with-debian-9.0
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentralFullEpisodes] the-daily-show-with-trevor-noah/full-episodes: Downloading webpage
[ComedyCentralFullEpisodes] Downloading JSON metadata
[ComedyCentralFullEpisodes] edbcbc58-271c-11e7-bfd4-0026b9414f30: Downloading info
[ComedyCentralFullEpisodes] 8a53efac-abfe-4f23-8e7a-74b555894b45: Extracting information
[ComedyCentralFullEpisodes] 8a53efac-abfe-4f23-8e7a-74b555894b45: Downloading video urls
[ComedyCentralFullEpisodes] 8a53efac-abfe-4f23-8e7a-74b555894b45: Downloading m3u8 information
[ComedyCentralFullEpisodes] b1575281-3c76-4bf5-8b73-ea72d0bc0cc3: Extracting information
[ComedyCentralFullEpisodes] b1575281-3c76-4bf5-8b73-ea72d0bc0cc3: Downloading video urls
[ComedyCentralFullEpisodes] b1575281-3c76-4bf5-8b73-ea72d0bc0cc3: Downloading m3u8 information
[ComedyCentralFullEpisodes] 411bd56f-eb70-4961-8e82-1d471c969690: Extracting information
[ComedyCentralFullEpisodes] 411bd56f-eb70-4961-8e82-1d471c969690: Downloading video urls
[ComedyCentralFullEpisodes] 411bd56f-eb70-4961-8e82-1d471c969690: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2129, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

...
<end of log>
```

### Description of your *issue*, suggested solution and other information

[ComedyCentralFullEpisodes] Extractor says: "ERROR: Failed to download m3u8 information: HTTP Error 404: Not Found (caused by HTTPError());" and therefore does not work at the moment.

**Comment by GravisZro** [comment]
I can confirm this.  Same issue happens with a specific episode. (e.g. http://www.cc.com/episodes/970fkb/the-daily-show-with-trevor-noah-extended---june-20--2017---john-harris-season-22-ep-22123 )

**Comment by blahmoomoo** [comment]
It would appear that the third segment of the 6/20 episode is simply missing. The browser player also can't access it. That segment is also available as a clip here, and it starts downloading no problem.

http://www.cc.com/video-clips/dyaght/the-daily-show-with-trevor-noah-john-harris---how-politico-is-adapting-to-the-trump-era---extended-interview

Other episodes also download no problem.

**Comment by Wandang** [comment]
was fixed by comedy central
