### ISSUE TITLE
Downloading a file form Visual Studio and change the file name is not working

### ISSUE THREAD

**Issue by Ailincai-Nicolae-Rares** [rg3/youtube-dl#13457]
I am trying to download a file from youtube in Visual Studio but when i want to change the file name, is not working. I Mean the file is not downloaded.
`        private Process downlaodMusic(string url, string fileName)
        {
            Process currentsong = new Process();

            currentsong.StartInfo = new ProcessStartInfo
            {
                FileName = "cmd.exe",
                Arguments = $"/C youtube-dl.exe {url} -output {fileName}",
                UseShellExecute = false,
                RedirectStandardOutput = true,
                CreateNoWindow = true
            };

            currentsong.Start();
            return currentsong;
        }`

**Comment by dstftw** [comment]
Long options must be written with double dash `--output`.
