### ISSUE TITLE
Progress hook is not called if video file is not downloaded but metadata is.

### ISSUE THREAD

**Issue by EraYaN** [rg3/youtube-dl#13466]
- [#] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

The documentation states:

```
Progress hooks are guaranteed to be called at least once
    (with status "finished") if the download is successful.
```

Now when skip_download or simulate are True the progress_hook is never called. Even though there are files downloaded (metadata etc.)

Used options are:

```python
self.ydl_opts = {
            'writeinfojson':True,       
            'writethumbnail':True,
            #'writesubtitles':True,
            #'writeautomaticsub':True,
            #'allsubtitles':True,
            'noprogress':True,
            'quiet':True,
            'prefer_ffmpeg':True,
            'encoding': 'utf-8',
            'cachedir': 'cache/',
            'outtmpl': os.path.realpath(os.path.join(root,'data/videos/%(uploader)s/%(title)s-%(id)s.%(ext)s')),
            'call_home': False,
            'logger': self.logger,
            'format':'bestaudio/audio_only/Audio_Only',
            'skip_download':True,
            'progress_hooks': [ self.progress_hook ]
        }
```

Now this works as long as neither of the mentions options are true. Now there is no way for the calling script to figure out where the file went.

Now I wonder is this a missing feature or is it by design?

**Comment by dstftw** [comment]
`progress_hooks` works for video downloading only. In case of `skip_download` no video is downloaded thus no hooks delivered.

**Comment by EraYaN** [comment]
Well then it is a feature request to still get the filename data from the call.

**Comment by dstftw** [comment]
There is a `_filename` in info dict.
