### ISSUE TITLE
[Request] Support funk.net

### ISSUE THREAD

**Issue by codingHahn** [rg3/youtube-dl#13465]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.funk.net/serien/5940e15073f6120001657956/items/593efbb173f6120001657503
- Playlist: https://www.funk.net/serien/5940e15073f6120001657956

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

The site is legal and made by ARD and ZDF.

EDIT: If I select the URL of the "Manifest..." file, I can download the show.

**Comment by Musashi69** [comment]
Would love to have this site supported, too :-)

**Comment by monreal** [comment]
>> If I select the URL of the "Manifest..." file

What URL exactly? How did you get it?

**Comment by asheiner** [comment]
+1 from me for this site

**Comment by codingHahn** [comment]
@monreal You click on a specific episode, e.g. https://www.funk.net/serien/5940e2f43e87930001fb600f/items/593f0f673e87930001fb5ad2 and then press F12, reload and right click the "Manifest.." file. In this case "Manifest(format=mpd.." and select ```Copy URL```. Now paste your clipboard into youtube-dl.

**Comment by Musashi69** [comment]
Not working for me - either they changed stuff on the site (the URL mentioned above doesn't work anymore) or I need more details to reproduce the solution mentioned by codingHahn

EDIT: Wrapping the URL of the Manifest file into "s does the trick for me.
