### ISSUE TITLE
Some questions about embedded youtube-dl

### ISSUE THREAD

**Issue by Coco1905** [rg3/youtube-dl#13463]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

#############################################################################

Hello everybody, 

Since some days, I am working on a project for my internship which is about extracting audio from a big list (.csv) of Youtube videos. We have chosen to use YouTube-dl library in python, which seems to be powerful . 

I have found many explanations about Youtube-dl in command line, but I am interested in a program using this library. 

1) Does a documentation about equivalence between command line and embedded youtube-dl exist ?
  
2) We would like to obtain a bunch of audio files with the same features for all of them. I achieved to extract only the audio and to chose the extension (.wav). However, I would like to have all my files with the same sample rate (44.1kHz). I have seen that, in command line, I can use '-f bestaudio[asr=44100]'. But how can I do that in a python program ? Is it possible ? 

3) I didn't see anything about mono or stereo file. I would like to extract my audio files in mono. Do I have to use another tool ? Or is a feature like that existing or will exist ?

Thank you in advance for your help !
Coralie

**Comment by Coco1905** [comment]
2. I achieved to do something. Here is the line to put in the options : 'format': 'bestaudio[asr=44100]/best' 
But, if the asr wanted is not available, there is no error : it is just not taken into account.

**Comment by dstftw** [comment]
1. https://github.com/rg3/youtube-dl#embedding-youtube-dl
2. See 1.
3. You'll need to do conversion yourself.

**Comment by OutBoundMan** [comment]
Is it possible to create a program like this: https://youtu.be/HcVa3LfG59E

Can you email me iamoutbound@gmail.com ?
