### ISSUE TITLE
Add support for Adobe Pass Auth TV Provider DIRECTV NOW

### ISSUE THREAD

**Issue by allai** [rg3/youtube-dl#13472]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.23**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Would it be possible to add DIRECTV NOW as a provider for Adobe Pass MSO? Its code is "ATTOTT". I can provide account info privately if needed.

**Comment by peppy6582** [comment]
Would also be willing to provide account info privately if needed.

**Comment by dstftw** [comment]
Can do this via mail in my profile.

**Comment by peppy6582** [comment]
On the way.  Thanks.

**Comment by dstftw** [comment]
Supported since youtube-dl 2017.06.25.
