### ISSUE TITLE
Extract Error

### ISSUE THREAD

**Issue by MichelGeorgesNajarian** [rg3/youtube-dl#13488]
I've encountered the following error: 

C:\Users\migeo\Music\download>youtube-dl.exe -F https://www.youtube.com/watch?v=PgzuOXKd6Sg&list=PL6MzJecijvlhFQVF52VDXexjmwZQpFMfq&index=14
[youtube] PgzuOXKd6Sg: Downloading webpage
[youtube] PgzuOXKd6Sg: Downloading video info webpage
[youtube] PgzuOXKd6Sg: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\extractor\youtube.py", line 897, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player '/yts/jsbin/player-vflmgXZN3/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player '/yts/jsbin/player-vflmgXZN3/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'list' is not recognized as an internal or external command,
operable program or batch file.
'index' is not recognized as an internal or external command,
operable program or batch file.

Not sure  what else I can say to help debug.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
