### ISSUE TITLE
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTP Error())

### ISSUE THREAD

**Issue by EverythingEverything** [rg3/youtube-dl#13487]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\PC>"C:\Users\PC\Desktop\youtube-dl.exe" --all-subs --skip-download http://www.atresplayer.com/television/series/refugiados/temporada-1/capitulo-1-captulo_2015050700327.html
[AtresPlayer] capitulo-1-captulo: Downloading webpage
[AtresPlayer] 20150507-EPISODE-01001-false: Downloading player JSON
[AtresPlayer] capitulo-1-captulo: Downloading timestamp
[AtresPlayer] capitulo-1-captulo: Downloading windows video JSON
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.atresplayer.com/television/series/refugiados/temporada-1/capitulo-1-captulo_2015050700327.html

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Hi there. I use Youtube-DL for a few days now, and I wanted to try it on Atresplayer. I can watch shows on that website and I wanted to download them with subtitles (they're available). But it just doesn't work. I don't know If i'm doing something wrong... so please, help me? I tried it in two ways : downloading only subtitles, and downloading only an episode. But it still doesn't work.

Regards

**Comment by dstftw** [comment]
You did not provide account credentials to youtube-dl.

**Comment by EverythingEverything** [comment]
Thank you for that quick reply. But... how am I supposed to do this, please?

**Comment by dstftw** [comment]
Read [FAQ](https://github.com/rg3/youtube-dl#authentication-options).
