### ISSUE TITLE
dumping current status as json

### ISSUE THREAD

**Issue by siddht1** [rg3/youtube-dl#13485]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.23**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X ] Feature request (request for a new functionality)
- [X ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.06.23
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

----------------------------------------------------------------------------------------------------------------------

Hey there I was trying to dump my current downloading status as json(any text file format should have work),so that as it reached 95 %,the process would start the next file in queue without waiting for the file to download,get complete,mixing the audio and video and then the second file in queue.I opted for dump-json and print-json but it didnt work.

The second part is I want the size of the unlisted video size but unable to do this as there is no way --get-size is there,but this was my shot as the file downloaded would have helped me. 

---------------------------------------------------------------------------------------------------------------------------
example: [download]  18.5% of 79.04MiB at  105.36KiB/s
as {"status":"download","file_size":79.04MiB,"downloaded_percent":"18.5","speed":105.36},

**Comment by dstftw** [comment]
Use `progress_hooks`.

**Comment by siddht1** [comment]
@dstftw please guide me what did you meant,is it a youtube-dl command or done manually in python

**Comment by siddht1** [comment]
found here https://github.com/rg3/youtube-dl#embedding-youtube-dl .  and does youtube-dl supports file lock

**Comment by siddht1** [comment]
i need a help,   this is my python external code to download via youtube_dl       :   from __future__ import unicode_literals
import youtube_dl
import os
import json

_url_=input("\n Enter the video url :")
_i=len(_url_)

#1: 
#2:
#3:
_faa='a'+'.json'
fo = open(_faa, "w")
class MyLogger(object):
    def debug(self, msg):
        pass

    def warning(self, msg):
        pass

    def error(self, msg):
        print(msg)

def my_hook(d):
    
    if d['status'] == 'finished':
        print('File downloaded ')
    else:
        #fo.write(d)
        os.system('clear')
        #_a_file=[]
        #_a_file[0].append(d['downloaded_bytes'])
        #_a_file[1].append(d['speed'])
        #_a__=str(d['downloaded_bytes']
        #_nm=d['eta']
        #print(d)
        
        _json=json.dumps(d)
        print(_json)
        fo.write(_json)




ydl_opts = {
    'format': '480p',
    'postprocessors': [],
    'logger': MyLogger(),
    'progress_hooks': [my_hook],
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download([_url_]) 
fo.close()    
    
 
I need to know what are the other parameters supported in ydl_opts and how to implement command line reading from text file in ydl_opts i.e "youtube-dl -a 1.list".

**Comment by siddht1** [comment]
i need a help,   this is my python external code to download via youtube_dl       :   from __future__ import unicode_literals
import youtube_dl
import os
import json

_url_=input("\n Enter the video url :")
_i=len(_url_)

#1: 
#2:
#3:
_faa='a'+'.json'
fo = open(_faa, "w")
class MyLogger(object):
    def debug(self, msg):
        pass

    def warning(self, msg):
        pass

    def error(self, msg):
        print(msg)

def my_hook(d):
    
    if d['status'] == 'finished':
        print('File downloaded ')
    else:
        #fo.write(d)
        os.system('clear')
        #_a_file=[]
        #_a_file[0].append(d['downloaded_bytes'])
        #_a_file[1].append(d['speed'])
        #_a__=str(d['downloaded_bytes']
        #_nm=d['eta']
        #print(d)
        
        _json=json.dumps(d)
        print(_json)
        fo.write(_json)




ydl_opts = {
    'format': '480p',
    'postprocessors': [],
    'logger': MyLogger(),
    'progress_hooks': [my_hook],
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download([_url_]) 
fo.close()    
    
 
I need to know what are the other parameters supported in ydl_opts and how to implement command line reading from text file in ydl_opts i.e "youtube-dl -a 1.list".
