### ISSUE TITLE
"ffprobe not found" when using 'ffmpeg_location' on binary

### ISSUE THREAD

**Issue by GorganRazvan** [rg3/youtube-dl#13498]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I'm using sl4a to run a python script on Android which uses the YoutubeDL API. I want to download from youtube and convert to .mp3, thus I've taken a prebuilt binary from [https://github.com/WritingMinds/ffmpeg-android] , put it in the script root directory path and used 'ffmpeg_location' in the ydl_opts dict (code and error pictures below). 

The problem is it gives me a "ffprobe not found" error. Isn't the ffprobe included in the ffmpeg binary? What could be a solution?

```
ydl_opts = {
		'ffmpeg_location': '/sdcard/sl4a/scripts/yt-sync/ffmpeg',
		'format': 'bestaudio/best',
		'postprocessors': [{
			'key': 'FFmpegExtractAudio',
        	'preferredcodec': 'mp3',
        	'preferredquality': '320',
		}]
	}
	
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://www.youtube.com/watch?v=WHRnvjCkTsw'])

```
Picture when setting the wrong ffmpeg binary file path:
![screenshot_2017-06-26-14-53-24](https://user-images.githubusercontent.com/17186774/27538611-85db9a6c-5a81-11e7-9ff1-f702a206eb87.png)

Here I've set the correct path and the error dissapeard meaning YoutubeDL got the ffmpeg.
![screenshot_2017-06-26-14-54-16](https://user-images.githubusercontent.com/17186774/27538619-8ad8fd20-5a81-11e7-9001-20ca7a744380.png)

Thank you.

**Comment by dstftw** [comment]
ffprobe is a standalone binary. The solution is to install ffprobe.
