### ISSUE TITLE
Higher quality videos not detected, despite being available to AdobeHDS.php

### ISSUE THREAD

**Issue by Twombs** [rg3/youtube-dl#13492]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Higher quality videos not detected.
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs 

http://iview.abc.net.au/programs/doctor-who/ZW0979A011S00
---

### Description of your *issue*, suggested solution and other information
http://iview.abc.net.au/programs/doctor-who/ZW0979A011S00
(1) If I use the AdobeHDS.php script for this same web page, then it detects and downloads the new High Quality video files that are available. But youtube-dl only sees the old low quality video files. If I grab the manifest data using the HDS Link Detector for Firefox, and use that with youtube-dl, then it downloads the High Quality video file.
(2) Is there someway I can download the manifest file or data with youtube-dl ... or specify that be used?

**Comment by TheDcoder** [comment]
Links:
[AdobeHDS.php](https://github.com/K-S-V/Scripts/blob/master/AdobeHDS.php)
[HDS Link Detector](https://addons.mozilla.org/en-US/firefox/addon/hds-link-detector/)

**Comment by Twombs** [comment]
Thanks for adding them in bud, I guess. However, they are not really needed.
It is the fact, that something (they) can detect and download the higher resolution files, that is all important. It shows they are there and available. Something that I guess youtube-dl should also be able to do, but isn't.
ABC (iView) have only just started making these higher resolution version videos available.

**Comment by d2au** [comment]
https://github.com/rg3/youtube-dl/pull/13489

**Comment by TheDcoder** [comment]
> Is there someway I can download the manifest file

Did you try the `--get-url` option to get the URL of the manifest file?

**Comment by Twombs** [comment]
nope, don't recall seeing that one ... and I went through them all enough times. will give it a go. thanks

**Comment by Twombs** [comment]
I do now recall the --get-url_ option, as I checked that and the other get options out. Seeing it on its own, it looked unfamiliar.

In any case, it just gets the m3u8 link, not the manifest.

**Comment by Twombs** [comment]
However, not being a nerd head, I did not understand the significance of anything JSON related, but I was inspired to do a dump (ha ha ha), and so used the --dump-json command. In amongst all the data it returned, was several m3u8 entries, but more importantly, some .f4m (manifest) ones too.

Alas though, looking at them, they don't quite match up with what AdobeHDS.php gets.
http://iviewum-vh.akamaihd.net/z/playback/_definst_/_video/ZW0979A011S00MA1D1_0b2d3a57_,650000,500000,220000,60000,.mp4.csmil/manifest.f4m?hdcore=3.7.0
as opposed to the AdobeHDS one
http://iviewum-vh.akamaihd.net/z/playback/_definst_/_video/ZW0979A011S00MA1D1_0b2d3a57_,1500000,1000000,650000,500000,220000,.mp4.csmil/manifest.f4m?hdcore=true&hdnea=st=1498384615~exp=1498394614~acl=/*~hmac=4a2f4794a201b7b0caf6262afd6c40974a0352fd6c6ddb6aa3fb2f96a1bc70da&g=CCBMFNRSEQJC&plugin=jwplayer-3.9.0.0

It is possible I guess, that adding the missing elements might work for other videos too ... or maybe just some of them. Need to do some testing.

**Comment by TheDcoder** [comment]
Hopefully we will have a fixed version of yotube-dl thanks to @d2au's contribution 😁

**Comment by 0880** [comment]
Seems to work with #13489 ...

```
youtube-dl "http://iview.abc.net.au/programs/doctor-who/ZW0979A011S00" -F
[abc.net.au:iview] ZW0979A011S00: Downloading webpage
[abc.net.au:iview] ZW0979A011S00: Downloading f4m manifest
[abc.net.au:iview] ZW0979A011S00: Downloading m3u8 information
[info] Available formats for ZW0979A011S00:
format code  extension  resolution note
hds-200      flv        unknown     200k
hls-200      mp4        320x180     200k , avc1.77.30, mp4a.40.2
hds-388      flv        unknown     388k
hls-388      mp4        512x288     388k , avc1.77.30, mp4a.40.2
hds-505      flv        unknown     505k
hls-505      mp4        640x360     505k , avc1.77.30, mp4a.40.2
hds-774      flv        unknown     774k
hls-774      mp4        800x450     774k , avc1.640028, mp4a.40.2
hds-1162     flv        unknown    1162k
hls-1162     mp4        1024x576   1162k , avc1.640028, mp4a.40.2 (best)
```
```
Video: MPEG4 Video (H264) 1024x576 25fps [V: h264 high L4.0, yuv420p, 1024x576]
Audio: AAC 44100Hz stereo 130kbps [A: aac lc, 44100 Hz, stereo, 130 kb/s]
```
Python - latest version for Windows: https://www.python.org/downloads/ + youtube-dl ...
```
pip install --upgrade youtube-dl
Collecting youtube-dl
  Downloading youtube_dl-2017.6.25-py2.py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 239kB/s
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2017.6.25
```
... + #13489 copied to `C:\Python\Lib\site-packages\youtube_dl\extractor\abc.py`

**Comment by Saklad5** [comment]
Is it possible that this would affect other extractors? I’ve noticed that TBS has a similar problem, but I assumed that was because it was only able to access the Android-targeted manifest, and that the higher-quality ones required some terrible DRM plugin that Android didn’t support.
