### ISSUE TITLE
The Late Show with Stephen Colbert June 20, 2017: None of the available releases match the specified AssetType and/or Format preferences

### ISSUE THREAD

**Issue by ryandesign** [rg3/youtube-dl#13490]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/Ve1PQPLiu8GD5Uj1YP4Sv34W2K0NDBWM/the-late-show-6-20-2017-ice-cube-marc-maron-jason-isbell-and-the-400-unit-/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/Ve1PQPLiu8GD5Uj1YP4Sv34W2K0NDBWM/the-late-show-6-20-2017-ice-cube-marc-maron-jason-isbell-and-the-400-unit-/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.25
[debug] Python version 3.6.1 - Darwin-16.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] Ve1PQPLiu8GD5Uj1YP4Sv34W2K0NDBWM: Downloading XML
[CBS] Ve1PQPLiu8GD5Uj1YP4Sv34W2K0NDBWM: Downloading OnceURL SMIL data
ERROR: None of the available releases match the specified AssetType and/or Format preferences
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/cbs.py", line 100, in _real_extract
    return self._extract_video_info(content_id)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/cbs.py", line 79, in _extract_video_info
    'Downloading %s SMIL data' % asset_type)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 42, in _extract_theplatform_smil
    raise ExtractorError(error_element.attrib['abstract'], expected=True)
youtube_dl.utils.ExtractorError: None of the available releases match the specified AssetType and/or Format preferences
```

---

### Description of your *issue*, suggested solution and other information

The June 20, 2017 episode of [The Late Show with Stephen Colbert](http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/) does not download. Previous and subsequent episodes work fine.

**Comment by japanesephundroid** [comment]
Confirmed. Same thing here, the video plays normally in browser.

**Comment by kucksdorfs** [comment]
This has happened again with the URL: http://www.cbs.com/shows/bull/video/sb4atUdwyQ_C3TTD8YLxun21_NLlnWvr/bull-witness-for-the-prosecution/
