### ISSUE TITLE
Download a portion of a video with embedded Youtube-dl 

### ISSUE THREAD

**Issue by Coco1905** [rg3/youtube-dl#13499]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

#############################################################################

Hello everybody, 

I am trying to extract only a portion of a video thanks to embedded Youtube-dl. 

I didn't find any option to do this. I have tried with this type of line: 
" with youtube_dl.YoutubeDL(ydl_opts) as ydl: 
                ydl.download(['http://www.youtube.com/v/--4gqARaEJE?start=0&end=10']) "
but it doesn't seem to work. 

Is something possible with the Youtube-dl library ? 

Thanks in advance for your help !

**Comment by dstftw** [comment]
Not possible.
