### ISSUE TITLE
How do I install ffmpeg on Android for YouTube-dl running in sl4a python script?

### ISSUE THREAD

**Issue by GorganRazvan** [rg3/youtube-dl#13496]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Since I know a bit of python I decided to make a .mp3 downloader Android app for myself using a python interpreter, sl4a, some scripts, webviewer and youtube-dl.

I can’t make ffmpeg available to youtube-dl (called in a python script) in Android. Most answers are for Java implementations, using JNI.

**Comment by siddht1** [comment]
you can download the arm version of ffmpeg

**Comment by siddht1** [comment]
i had manually done it from https://github.com/guardianproject/android-ffmpeg,or you can visit here https://trac.ffmpeg.org/wiki/CompilationGuide/Android. 
I don't consider this to be any bug/issue with youtube-dl so I would ask maintainers to close this issue

**Comment by siddht1** [comment]
look here,this needs to be called if you are compiling yourself,better use some ideas from this instead http://dentex.github.io/ (external project) or better check this https://github.com/rg3/youtube-dl/issues/967

**Comment by yan12125** [comment]
Thanks @siddht1 for providing such useful info. What you need is preparing a ffmpeg binary somewhere, and feed the path via ```--ffmpeg-location /path/to/ffmpeg``` (CLI) or ```'ffmpeg_location': '/path/to/ffmpeg'``` in ```YoutubeDL``` options. (Python API)

**Comment by alexanderadam** [comment]
I just want to add that it would be absolutely great if someone would package `youtube-dl` for android and publishes it to [F-Droid](https://f-droid.org/de/).
A functionality like using a share button in the browser where `youtube-dl` appears and downloads the video would be _very_ cool.

The current state of `youtube-dl` on mobile devices seem to be pretty complicated and [error prone](https://github.com/rg3/youtube-dl/issues/967) (see also [here](https://github.com/rg3/youtube-dl/issues/1859), [here](https://github.com/rg3/youtube-dl/issues/1654) or [here](https://github.com/rg3/youtube-dl/issues/4864)).
I have the feeling that there's a demand to have it on mobile devices ([1](https://github.com/rg3/youtube-dl/issues/10753), [2](https://github.com/rg3/youtube-dl/issues/7452), [3](https://github.com/rg3/youtube-dl/issues/8003), [4](https://github.com/rg3/youtube-dl/issues/3462), [5](https://github.com/rg3/youtube-dl/issues/11528)).

PS: Just to be sure: [this](http://dentex.github.io/apps/youtubedownloader/) app is not related to `youtube-dl`, right?

**Comment by yan12125** [comment]
> this app is not related to youtube-dl, right?

I can't give a guarantee, but looks like not as its functionality is rather limited in comparison to youtube-dl (no support for login-required videos and live videos)

In general, this repository handles only core functionality. An Android app can be maintained in an external repo, just like many GUI wrapper out there. I have some scripts at https://github.com/yan12125/python3-android/ that builds a working ```python``` binary for running youtube-dl. Just that I have no idea how to write a F-Droid build script.
