### ISSUE TITLE
Question about available formats

### ISSUE THREAD

**Issue by Coco1905** [rg3/youtube-dl#13504]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

#############################################################################

Hello everybody, 

I am using embedded youtube-dl to extract all my audio files with the same format.

For the moment, I ask them to have an sample rate of 44.1kHz with 
'format': 'bestaudio[asr=48000]/best'
in the options. 

The best for me would have been an asr of 48kHz. But, when I try with the same line, but with asr=48000, all the files have not the same sample rate that I want. Indeed, when I use 
'listformats': 'True'
the 171 is always available (44.1kHz) but not one with 48kHz. 

So, I am wondering : how the available formats are chosen ? Does it come from youtube directly ? (I am only downloading youtube videos.) 

Thanks in advance!

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#format-selection
