### ISSUE TITLE
Viafree.dk JSON Expecting Error

### ISSUE THREAD

**Issue by fidodkk** [rg3/youtube-dl#13509]
I get a JSON Expecting error with all videoes i want to download from viafree.dk like this one:

D:\Downloads\>youtube-dl --output Amalies.Baby.S01E01.mkv https://www.viafree.dk/programmer/reportage/amalies-baby/saeson-1/episode-1
[Viafree] episode-1: Downloading webpage
**WARNING: [Viafree] episode-1: Failed to parse JSON Expecting ',' delimiter: line 1 column 10847 (char 10846)**
[mtg] 731552: Downloading video JSON
[mtg] 731552: Downloading streams JSON
[mtg] 731552: Downloading m3u8 information
[mtg] 731552: Downloading f4m manifest
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 10
[download] Destination: Amalies.Baby.S01E01.mkv
[download] 100% of 31.94MiB in 00:05
[ffmpeg] Fixing malformated aac bitstream in "Amalies.Baby.S01E01.mkv"

**Comment by dstftw** [comment]
This is not an error.
