### ISSUE TITLE
Adding Out-of-range Videos to the archive

### ISSUE THREAD

**Issue by cooro** [rg3/youtube-dl#13500]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Is it possible to record a video in my archive if it is out of the date range of my command? 
I run this command periodically, and the command takes a long time passing the channels with infrequent uploads because they have videos that are within the ten most recent uploads but posted before 2017.02.09. My current command is as follows, for reference:
youtube-dl -f 'best[height<=720]' --youtube-skip-dash-manifest --playlist-end 10 --no-playlist -cio '%(upload_date)s-%(title)s.%(ext)s' --batch-file urls.txt --download-archive archive.txt --dateafter "20170209"

**Comment by dstftw** [comment]
Only downloaded videos are recorded in download archive, the opposite does not make any sense. This command shouldn't take long since it uses download archive and limits number of videos.
