### ISSUE TITLE
Adding thumbnail to mp3 file 

### ISSUE THREAD

**Issue by enigmavision** [rg3/youtube-dl#13514]
youtube-dl  --extract-audio -i --audio-format mp3 --audio-quality 0 --no-part --no-mtime --embed-thumbnail --add-metadata https://www.youtube.com/playlist/761AB0FC7 -v --postprocessor-args "-id3v2_version 3"

This is whats read out......

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--extract-audio', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'--no-part', u'--no-mtime', u'--embed-thumbnail', u'--add-metadata', u'https://www.youtube.com/playlist?list=AB0FC7', u'-v', u'--postprocessor-args', u'-id3v2_version 3']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.25
[debug] Python version 2.7.10 - Darwin-16.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}

This is what im using. When its downloaded they are 2 seperate files one jpg and one mp3. I want the thumbnail to be on the mp3. whats the resolution?

**Comment by enigmavision** [comment]
Im looking for the jpg thumbnail and mp3 files to download as ONE. Is this possible?

**Comment by dstftw** [comment]
This command does exactly what you are asking.
