### ISSUE TITLE
KIJK.nl support broken, unsupported URL

### ISSUE THREAD

**Issue by dt4621** [rg3/youtube-dl#13519]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

# youtube-dl -g -vF http://www.kijk.nl/sbs6/stegemanopdebres/videos/IK8qrhopqIs/aflevering-6
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-g', u'-vF', u'http://www.kijk.nl/sbs6/stegemanopdebres/videos/IK8qrhopqIs/aflevering-6']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.25
[debug] Python version 2.7.12 - Linux-4.4.38-std-1-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.kijk.nl/sbs6/stegemanopdebres/videos/IK8qrhopqIs/aflevering-6
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1971, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2796, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.kijk.nl/sbs6/stegemanopdebres/videos/IK8qrhopqIs/aflevering-6

Kijk.nl seems to be broken somehow while it used to work?

**Comment by MKaterbarg** [comment]
It looks like, using the above example, the actual video is located on https://embed.kijk.nl/video/IK8qrhopqIs

youtube-dl is able to find the qualities that are available, and it attempting a download. The download fails, but does show a .mp4 file path. Complete debug log (different video, same site):



[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://embed.kijk.nl/video/OnJsPsOOUxO', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.15
[debug] Python version 2.7.6 - Linux-3.19.0-25-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] OnJsPsOOUxO: Requesting header
WARNING: Falling back on generic information extractor.
[generic] OnJsPsOOUxO: Downloading webpage
[generic] OnJsPsOOUxO: Extracting information
[download] Downloading playlist: Shownieuws
[generic] playlist Shownieuws: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5510750645001: Downloading webpage
[brightcove:new] 5510750645001: Downloading JSON metadata
[brightcove:new] 5510750645001: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
[debug] Invoking downloader on u'rtmp://pssbsfs.fplive.net/pssbsfs'
[download] Destination: Shownieuws-5510750645001.mp4
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmp://pssbsfs.fplive.net/pssbsfs' -o Shownieuws-5510750645001.mp4.part --playpath 'mp4:ra/01/7598852d2c6a5462d82e26fa125532b25f26fb/mp4/sbs6_shownieuwslateeditie_S00E2017071701025657_170718000132759885-bg-1885.mp4' --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : pssbsfs.fplive.net
[rtmpdump] DEBUG: Parsed app     : pssbsfs
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : pssbsfs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:ra/01/7598852d2c6a5462d82e26fa125532b25f26fb/mp4/sbs6_shownieuwslateeditie_S00E2017071701025657_170718000132759885-bg-1885.mp4
[rtmpdump] DEBUG: tcUrl    : rtmp://pssbsfs.fplive.net:1935/pssbsfs
[rtmpdump] DEBUG: app      : pssbsfs
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Type Answer   : 03
[rtmpdump] DEBUG: HandShake: Server Uptime : 1756454969
[rtmpdump] DEBUG: HandShake: FMS Version   : 4.5.3.1
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 184 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  error>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetConnection.Connect.Rejected>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  [ Server.Reject ] : (_defaultRoot_, _defaultVHost_) : Application (pssbsfs) is not defined.>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_error>
[rtmpdump] ERROR: rtmp server sent error
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 18 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <close>
[rtmpdump] ERROR: rtmp server requested close
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : pssbsfs.fplive.net
[rtmpdump] DEBUG: Parsed app     : pssbsfs
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : pssbsfs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:ra/01/7598852d2c6a5462d82e26fa125532b25f26fb/mp4/sbs6_shownieuwslateeditie_S00E2017071701025657_170718000132759885-bg-1885.mp4
[rtmpdump] DEBUG: tcUrl    : rtmp://pssbsfs.fplive.net:1935/pssbsfs
[rtmpdump] DEBUG: app      : pssbsfs
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.


ERROR: rtmpdump exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1941, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 978, in process_ie_result
    extra_info=extra)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 848, in process_ie_result
    extra_info=extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1584, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1848, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1790, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 163, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 604, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 566, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())


Perhaps someone who has more knowledge than me can figure out the rest

**Comment by MKaterbarg** [comment]
Using fiddler I was able to obtain 2 .m3u8 files files, of which the last ones showed URLs to all the .ts files for the actual video. 
I myself am not able to program for this however, someone who can pick it up? I can provide files if required.

**Comment by MKaterbarg** [comment]
It looks like they disabled an SSL version, and have SNI enabled, as well as are using a new root CA, which you may not have in your system yet. 

Make sure you update the ca-certificates package. That together with upgrading to Python 2.7.12 (from 2.7.6) AND using the embedded URL worked for me.

The embedded URL for yours would be: https://embed.kijk.nl/video/IK8qrhopqIs

Perhaps someone can write some code that enables using the embedded URL? I'm not a python programmer
