### ISSUE TITLE
[kaltura] Downloads only first couple of minutess of video

### ISSUE THREAD

**Issue by fnadde42** [rg3/youtube-dl#13517]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl https://www.somedomain.com/library/view/name-of-series/2441675490031/NAME-episode_x.html -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.somedomain.com/library/view/name-of-series/2441675490031/NAME-episode_x.html', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.25
[debug] Python version 2.7.12 - Linux-4.4.0-53-generic-x86_64-with-LinuxMint-18.1-serena
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[safari] 2441675490031/NAME-episode_x: Downloading webpage
[Kaltura] 2441675490031-NAME-episode_x: Downloading webpage
[Kaltura] 0_yw7ycr44: Downloading video info JSON
[Kaltura] 0_yw7ycr44: Downloading m3u8 information
[debug] Invoking downloader on u'http://cdnapi.kaltura.com/p/1603929/sp/160392900/playManifest/entryId/0_yw7ycr44/format/url/protocol/http/flavorId/0_b434rnaz'
[download] Form-0_yw7ycr44.mp4 has already been downloaded
[download] 100% of 20.08MiB

```

### Description of your *issue*, suggested solution and other information

I'm trying to download a video from Kaltura so I can watch it offline but `youtube-dl` only downloads the first couple of minutes of the video. I have tried with other videos but I get the same result.

**Comment by dstftw** [comment]
You did not provide safari account credentials to youtube-dl.
