### ISSUE TITLE
Thumbnail Image & Mp3 File seperate issue 

### ISSUE THREAD

**Issue by enigmavision** [rg3/youtube-dl#13516]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.06.25
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Ive spent hours trying to fix this! Please help

How do I add a thumbnail to my mp3 downloads? When I do it, it downloads the jpg file (thumbnail) and mp3 file seperatly... I want them to be together in ONE.

**Comment by dstftw** [comment]
`--embed-thumbnail`.

**Comment by enigmavision** [comment]
It does not work for me

**Comment by dstftw** [comment]
Bother to read new issue template and provide all requested data.

**Comment by enigmavision** [comment]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-x', u'-i', u'--audio-format', u'm4a', u'--audio-quality', u'0', u'--no-part', u'--no-mtime', u'--embed-thumbnail', u'https://www.youtube.com/playlist?list=PL35BA110761AB0FC7', u'-v', u'--postprocessor-args', u'-id3v2_version', u'3']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.25
[debug] Python version 2.7.10 - Darwin-16.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Looking up account info
[youtube:playlist] Logging in

**Comment by dstftw** [comment]
Provide **complete** log.

**Comment by enigmavision** [comment]
youtube-dl -u <private> -p <private> -x -i --audio-format m4a --audio-quality 0 --no-part --no-mtime --embed-thumbnail  https://www.youtube.com/playlist?list=PL30761AB0FC7 -v --postprocessor-args -id3v2_version 3 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-x', u'-i', u'--audio-format', u'm4a', u'--audio-quality', u'0', u'--no-part', u'--no-mtime', u'--embed-thumbnail', u'https://www.youtube.com/playlist?list=PL35BA110761AB0FC7', u'-v', u'--postprocessor-args', u'-id3v2_version', u'3']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.25
[debug] Python version 2.7.10 - Darwin-16.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Looking up account info
[youtube:playlist] Logging in
Type 2-step verification code and press [Return]: 
[youtube:playlist] Submitting TFA code
[youtube:playlist] Checking cookie
[youtube:playlist] PL35BA111AB0FC7: Downloading webpage
WARNING: [youtube:playlist] Youtube gives an alert message: One or more videos have been removed from the playlist because they were deleted from YouTube.
[download] Downloading playlist: Screwzoo
[youtube:playlist] playlist Screwzoo: Downloading 25 videos
[download] Downloading video 1 of 25
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] JghjBjE5V9k: Downloading webpage
1[youtube] JghjBjE5V9k: Downloading video info webpage
ERROR: JghjBjE5V9k: YouTube said: This video contains content from UMG, who has blocked it on copyright grounds.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1536, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: JghjBjE5V9k: YouTube said: This video contains content from UMG, who has blocked it on copyright grounds.

[download] Downloading video 2 of 25
[youtube] pWPIb-nUYrI: Downloading webpage
[youtube] pWPIb-nUYrI: Downloading video info webpage
[youtube] pWPIb-nUYrI: Extracting video information
[youtube] {43} signature length 43.40, html5 player vflV4eRc2
[youtube] pWPIb-nUYrI: Downloading player https://www.youtube.com/yts/jsbin/player-vflV4eRc2/en_US/base.js
[youtube] {18} signature length 43.40, html5 player vflV4eRc2
[youtube] {36} signature length 43.40, html5 player vflV4eRc2
[youtube] {17} signature length 43.40, html5 player vflV4eRc2
[youtube] {135} signature length 43.40, html5 player vflV4eRc2
[youtube] {244} signature length 43.40, html5 player vflV4eRc2
[youtube] {134} signature length 43.40, html5 player vflV4eRc2
[youtube] {243} signature length 43.40, html5 player vflV4eRc2
[youtube] {133} signature length 43.40, html5 player vflV4eRc2
[youtube] {242} signature length 43.40, html5 player vflV4eRc2
[youtube] {160} signature length 43.40, html5 player vflV4eRc2
[youtube] {278} signature length 43.40, html5 player vflV4eRc2
[youtube] {140} signature length 43.40, html5 player vflV4eRc2
[youtube] {171} signature length 43.40, html5 player vflV4eRc2
[youtube] {249} signature length 43.40, html5 player vflV4eRc2
[youtube] {250} signature length 43.40, html5 player vflV4eRc2
[youtube] {251} signature length 43.40, html5 player vflV4eRc2
[youtube] pWPIb-nUYrI: Downloading MPD manifest
[youtube] pWPIb-nUYrI: Downloading thumbnail ...
[youtube] pWPIb-nUYrI: Writing thumbnail to: DJ Screw - Leanin' On A Switch (Disk 1 & 2)-pWPIb-nUYrI.jpg
[debug] Invoking downloader on u'https://r2---sn-q4fl6nlr.googlevideo.com/videoplayback?requiressl=yes&pl=22&initcwndbps=942500&itag=251&expire=1498740791&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&source=youtube&beids=%5B9466592%5D&mime=audio%2Fwebm&keepalive=yes&lmt=1496975773065754&clen=93219556&mt=1498719101&mv=m&ms=au&mm=31&mn=sn-q4fl6nlr&dur=5588.081&gir=yes&ei=16NUWZTvLM79uQXW7Y3YDA&id=o-AE71PkYHST8Y6hGJE2JLJJn2_oZy6NGk_DCktw-HiLBY&key=yt6&ip=173.239.232.56&ipbits=0&signature=9329C35FCF62001B9C9AF09555B47F57FC753C93.1CA8869BFDDF53403936C09E24D876C5A928EBB2&ratebypass=yes'
[download] Destination: DJ Screw - Leanin' On A Switch (Disk 1 & 2)-pWPIb-nUYrI.webm
[download] 100% of 88.90MiB in 00:36
[debug] ffmpeg command line: ffprobe -show_streams 'file:DJ Screw - Leanin'"'"' On A Switch (Disk 1 & 2)-pWPIb-nUYrI.webm'
[ffmpeg] Destination: DJ Screw - Leanin' On A Switch (Disk 1 & 2)-pWPIb-nUYrI.m4a
[debug] ffmpeg command line: ffmpeg -y -i 'file:DJ Screw - Leanin'"'"' On A Switch (Disk 1 & 2)-pWPIb-nUYrI.webm' -vn -acodec aac '-q:a' 0 '-bsf:a' aac_adtstoasc -id3v2_version 'file:DJ Screw - Leanin'"'"' On A Switch (Disk 1 & 2)-pWPIb-nUYrI.m4a'
ERROR: audio conversion failed: At least one output file must be specified
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1973, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 308, in run
    'audio conversion failed: ' + e.msg)
PostProcessingError: audio conversion failed: At least one output file must be specified

ERROR: AtomicParsley was not found. Please install.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1973, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/embedthumbnail.py", line 59, in run
    raise EmbedThumbnailPPError('AtomicParsley was not found. Please install.')
EmbedThumbnailPPError: AtomicParsley was not found. Please install

**Comment by dstftw** [comment]
Must be `--postprocessor-args '-id3v2_version 3'` not `--postprocessor-args -id3v2_version 3`.

**Comment by enigmavision** [comment]
@dstftw 

I changed it and It still shows two seperate files

**Comment by dstftw** [comment]
>Provide **complete** log.

**Comment by enigmavision** [comment]
@dstftw 

youtube-dl -u <private> -p <private> -x -i --audio-format m4a --audio-quality 0 --no-part --no-mtime --embed-thumbnail --add-metadata  https://www.youtube.com/playlist?list=PL35BA110761AB0FC7 -v --postprocessor-args '-id3v2_version 3' 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-x', u'-i', u'--audio-format', u'm4a', u'--audio-quality', u'0', u'--no-part', u'--no-mtime', u'--embed-thumbnail', u'--add-metadata', u'https://www.youtube.com/playlist?list=PL35BA110761AB0FC7', u'-v', u'--postprocessor-args', u'-id3v2_version 3']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.25
[debug] Python version 2.7.10 - Darwin-16.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Looking up account info
[youtube:playlist] Logging in
Type 2-step verification code and press [Return]: 
[youtube:playlist] Submitting TFA code
[youtube:playlist] Checking cookie
[youtube:playlist] PL35BA110761AB0FC7: Downloading webpage
WARNING: [youtube:playlist] Youtube gives an alert message: One or more videos have been removed from the playlist because they were deleted from YouTube.
[download] Downloading playlist: Screwzoo
[youtube:playlist] playlist Screwzoo: Downloading 25 videos
[download] Downloading video 1 of 25
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] JghjBjE5V9k: Downloading webpage
[youtube] JghjBjE5V9k: Downloading video info webpage
ERROR: JghjBjE5V9k: YouTube said: This video contains content from UMG, who has blocked it on copyright grounds.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1536, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: JghjBjE5V9k: YouTube said: This video contains content from UMG, who has blocked it on copyright grounds.

[download] Downloading video 2 of 25
[youtube] pWPIb-nUYrI: Downloading webpage
[youtube] pWPIb-nUYrI: Downloading video info webpage
[youtube] pWPIb-nUYrI: Extracting video information
[youtube] {43} signature length 43.40, html5 player vflV4eRc2
[youtube] {18} signature length 43.40, html5 player vflV4eRc2
[youtube] {36} signature length 43.40, html5 player vflV4eRc2
[youtube] {17} signature length 43.40, html5 player vflV4eRc2
[youtube] {135} signature length 43.40, html5 player vflV4eRc2
[youtube] {244} signature length 43.40, html5 player vflV4eRc2
[youtube] {134} signature length 43.40, html5 player vflV4eRc2
[youtube] {243} signature length 43.40, html5 player vflV4eRc2
[youtube] {133} signature length 43.40, html5 player vflV4eRc2
[youtube] {242} signature length 43.40, html5 player vflV4eRc2
[youtube] {160} signature length 43.40, html5 player vflV4eRc2
[youtube] {278} signature length 43.40, html5 player vflV4eRc2
[youtube] {140} signature length 43.40, html5 player vflV4eRc2
[youtube] {171} signature length 43.40, html5 player vflV4eRc2
[youtube] {249} signature length 43.40, html5 player vflV4eRc2
[youtube] {250} signature length 43.40, html5 player vflV4eRc2
[youtube] {251} signature length 43.40, html5 player vflV4eRc2
[youtube] pWPIb-nUYrI: Downloading MPD manifest
[youtube] pWPIb-nUYrI: Downloading thumbnail ...
[youtube] pWPIb-nUYrI: Writing thumbnail to: DJ Screw - Leanin' On A Switch (Disk 1 & 2)-pWPIb-nUYrI.jpg
[debug] Invoking downloader on u'https://r2---sn-q4fl6nlr.googlevideo.com/videoplayback?mn=sn-q4fl6nlr&source=youtube&clen=93219556&dur=5588.081&ms=au&mv=m&mt=1498722042&ip=2602%3A306%3Acd22%3A8660%3A5c9d%3Afe8b%3Ac59%3Ada45&ei=Ua9UWYXxOdb9uAXJrIdQ&mm=31&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AO4KddxDclZ-geKII7XTcpzT0p9taJ86Cq5qki5XuBUC&initcwndbps=905000&gir=yes&expire=1498743730&requiressl=yes&keepalive=yes&pl=52&itag=251&key=yt6&mime=audio%2Fwebm&ipbits=0&lmt=1496975773065754&signature=9D04E80D12A3092CAFCBFCE81F689D7866D12B83.5D59E24B5FEBD961E12C7C9458C8656BD0CAFBD6&ratebypass=yes'
[download] Destination: DJ Screw - Leanin' On A Switch (Disk 1 & 2)-pWPIb-nUYrI.webm
[download] 100% of 88.90MiB in 00:38
[debug] ffmpeg command line: ffprobe -show_streams 'file:DJ Screw - Leanin'"'"' On A Switch (Disk 1 & 2)-pWPIb-nUYrI.webm'
[ffmpeg] Destination: DJ Screw - Leanin' On A Switch (Disk 1 & 2)-pWPIb-nUYrI.m4a
[debug] ffmpeg command line: ffmpeg -y -i 'file:DJ Screw - Leanin'"'"' On A Switch (Disk 1 & 2)-pWPIb-nUYrI.webm' -vn -acodec aac '-q:a' 0 '-bsf:a' aac_adtstoasc -id3v2_version 3 'file:DJ Screw - Leanin'"'"' On A Switch (Disk 1 & 2)-pWPIb-nUYrI.m4a'

**Comment by enigmavision** [comment]
anything? @dstftw  

Ive been spending hours trying to figure this out

**Comment by dstftw** [comment]
Log clearly states:
>ERROR: AtomicParsley was not found. Please install.

**Comment by enigmavision** [comment]
well thats a hastle... now I have to config another program just to get the image thumbnail embedded?
