### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by Metalhead33** [rg3/youtube-dl#13529]
I am not sure if it is already possible, but is it possible to download a video without the audio?
If it is not possible, it "should" be... or rather, I personally need that feature. That's all.

**Comment by dstftw** [comment]
You can only download audio without video if it's served as audio-only with `-f bestaudio`.

**Comment by Metalhead33** [comment]
I meant video WITHOUT audio, not the other way around. Silent video.

**Comment by gkoelln** [comment]
You could query the formats and if the format is video only, you could download that.  Alternately, there are some post-processing FFMPEG commands that would probably take care of that.
