### ISSUE TITLE
YouTube ERROR: content too short when used with "-f best"

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#13526]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```

C:\>youtube-dl.py "https://www.youtube.com/watch?v=QLvJ5R0tv9Y" -v -f best
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=QLvJ5R0tv9Y', '-v', '-f', 'best']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.25
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] QLvJ5R0tv9Y: Downloading webpage
[youtube] QLvJ5R0tv9Y: Downloading video info webpage
[youtube] QLvJ5R0tv9Y: Extracting video information
[youtube] QLvJ5R0tv9Y: Downloading MPD manifest
[debug] Invoking downloader on 'https://r8---sn-cxaaj5o5q5-tt1k.googlevideo.com/videoplayback?source=youtube&mm=31&mn=sn-cxaaj5o5q5-tt1k&ip=199.85.73.12&ratebypass=yes&mt=1498767836&mv=m&pl=24&id=o-AE
KgjQqusKB-C-24G543Cq1T71KVNcgeHjFYWvzkLntI&ei=RGJVWbDzCpnkDsnDhxg&ms=au&key=yt6&initcwndbps=13148750&lmt=1469779567592727&requiressl=yes&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%
2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&expire=1498789540&ipbits=0&signature=B67A6182AF7437EDFC129E015C685B1BB8289327.46F0A1031FCA407A18831D7FA63661187754
458C&pcm2cms=yes&dur=43.305&mime=video%2Fmp4&itag=22'
[download] Destination: Shapovalov Wows Crowd With Double Hot Shot Toronto 2016-QLvJ5R0tv9Y.mp4
[download]   0.0% of 8.46MiB at 17.01KiB/s ETA 08:29         ERROR: content too short (expected 8875291 bytes and served 1087)
Traceback (most recent call last):
  File "C:\TRANSMOGRIFIER\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1834, in process_info
    success = dl(filename, info_dict)
  File "C:\TRANSMOGRIFIER\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1776, in dl
    return fd.download(name, info)
  File "C:\TRANSMOGRIFIER\youtube-dl.py\youtube_dl\downloader\common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "C:\TRANSMOGRIFIER\youtube-dl.py\youtube_dl\downloader\http.py", line 238, in real_download
    raise ContentTooShortError(byte_counter, int(data_len))
youtube_dl.utils.ContentTooShortError: Downloaded 1087 bytes, expected 8875291 bytes

<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=QLvJ5R0tv9Y

---

### Description of your *issue*, suggested solution and other information

The exact same YouTube URL downloads correctly without the "-f best" option.

Thanks as always...
Ringo

**Comment by dstftw** [comment]
Not available at Youtube side.
