### ISSUE TITLE
Add argument to return the extractor that will be used?

### ISSUE THREAD

**Issue by thehunmonkgroup** [rg3/youtube-dl#13539]
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Curious how hard it would be to add an argument that would simply print the extractor that will be used based on the URL passed? 

Looks like that could happen around https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L752, after the ie.working() check? Not sure, as the try/catch block afterwards seems to suggest that the final successful extractor isn't known until it actually executes something.

My use case is that I'm building a simple wrapper around youtube-dl for downloading videos from YouTube and Vimeo, which use different access control strategies. If I could run something like ```youtube-dl --show-extractor [url]```, and have it spit out the name of the extractor it will use for the url in question, I could provide a bit simpler interface for entering credentials to access private videos.

I suppose I could just steal the regex that's used for Vimeo and do my own check against the URL I receive, I just thought it would be cleaner to get the answer from youtube-dl iteself

**Comment by dstftw** [comment]
Matching extractor's `suitable` does not mean this extractor will be the final one. Extractors may delegate extraction to another extractors when necessary so it's technically impossible to know the final extractor until extraction is finished.

**Comment by thehunmonkgroup** [comment]
Cool, thanks for the quick response, it's trivial to handle on my end with a regex...
