### ISSUE TITLE
SoundCloud Playlists -

### ISSUE THREAD

**Issue by dst702** [rg3/youtube-dl#13537]
Every time I download a playlist of songs from soundcloud, it never seems to add the ID3 tag information, only always downloads at 128kbps and adds 10 numbers to the end of every song. Anyway to rectify any of this? I'm pretty sure the bitrate can't be changed because thats what its uploaded as or compressed to? What about not adding numbers to the end or adding tag information so I don't have to tag every track ? Any help would be greatly appreciated!

**Comment by dstftw** [comment]
1. https://github.com/rg3/youtube-dl#output-template
2. `--add-metadata`.
