### ISSUE TITLE
Date format.

### ISSUE THREAD

**Issue by Quaraxkad** [rg3/youtube-dl#13547]
I'd like to propose that when specifying %(upload_date)s or %(release_date)s in the filename template that the returned date be in the ISO standard format of yyyy-MM-dd. The current format is yyyyMMdd with no delimiter. As far as I know, this is not possible to do using the Python string formatting options.

**Comment by dstftw** [comment]
Rejected. This will break backward compatibility.

**Comment by Quaraxkad** [comment]
I'm not suggesting to change the **internal** date format, only what it sets as the output filename. How could this _possibly_ break anything?

**Comment by dstftw** [comment]
It will change **all output templates** that use these meta fields. This breaks **everything that relies on old format**, e.g. file directories autocreated based on output template.
