### ISSUE TITLE
Download to separate folders

### ISSUE THREAD

**Issue by Sonicpromo** [rg3/youtube-dl#13553]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ x] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

Hello
I got few links (whole youtube channel) to download but all videos from them are downloading into 1 folder, I want them to be downloaded into separated folders depending on the channel's name, how can I do that?
Thanks

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#output-template

**Comment by Sonicpromo** [comment]
I saw this but I don't know how to do this exactly in my case

**Comment by Sonicpromo** [comment]
@artifexor Yes its probably it, but I'm not really good with PC. Should I just put this into command line? I just want to download few channels and their videos should be in different (not 1) folder

**Comment by Sonicpromo** [comment]
E.g. save path/channel1, save path/ channel2, etc
And one more question maybe you know it: is it possible to download 1080p then convert to 720p without 3rd party software?

**Comment by Hrxn** [comment]
Put the output template into your [config file](https://github.com/rg3/youtube-dl#configuration).

This way it always uses your directory hierarchy, e.g. `%(playlist)s/%(author)s/%(title)s.%(ext)s` and so on..

> And one more question maybe you know it: is it possible to download 1080p then convert to 720p without 3rd party software?

Uh, with youtube-dl? No. Use ffmpeg or something, although I don't see the point in converting 1080p to 720p

**Comment by Sonicpromo** [comment]
@Hrxn Thanks but that didn't work out I put it in config but still all files are in the same folder
Same thing with the command line and if I remove CL and change it in config only still all files goes to 1 folder :-(

**Comment by Sonicpromo** [comment]
Simply wont create a folder for videos and won't sort them, 2 different channels saved into 1 final folder

**Comment by Hrxn** [comment]
Post your output of `youtube-dl -v` please, this will show active config settings etc.

**Comment by Sonicpromo** [comment]
Should I just put it into command line? Because after restart I don't see anything happen
Maybe it is because I use portable version? I tried to update but it said that "program download correctly"

**Comment by Hrxn** [comment]
Portable version? youtube-dl is just a static binary, hence it's always portable?

**Comment by Sonicpromo** [comment]
I don't know as I said I'm not good with PC. I use this version with GUI https://github.com/MrS0m30n3/youtube-dl-gui/releases
and if I enter -v or --v it wont do anything for me? Maybe I do something wrong

**Comment by Sonicpromo** [comment]
They redirected me to this forum (to post questions or bugs about the program) dunno why

**Comment by Sonicpromo** [comment]
@Hrxn Do you have any idea how to fix it or I should write to them? I thought its the same software just with GUI?

**Comment by Hrxn** [comment]
It is the same program, yes.

youtube-dl is bundled with this GUI application, as it seems, but it might be outdated.

You can download the latest youtube-dl here: https://github.com/rg3/youtube-dl/releases

I think you're on Windows? Then use `youtube-dl.exe`, download it and put it into a directory you find again, open `CMD`, go to this directory and run `youtube-dl -v`.

**Comment by Sonicpromo** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\1\Desktop\YT TEST>youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.07.02
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

C:\Users\1\Desktop\YT TEST>

Like this?

**Comment by Hrxn** [comment]
Yes, exactly.

> [debug] System config: []
[debug] User config: []

This means that no config options are active. You need to create a configuration file (correct file name), put it in the right location so that youtube-dl finds it.

Inside the config file you can use the same options as on the command line..
An example for the output template: `-o "D:/Temp/Media/%(extractor)s/%(title)s-%(id)s.%(ext)s"`

And if you run `youtube-dl -v`, you should see these options.

**Comment by Sonicpromo** [comment]
Thanks for the help but I think I should better stick to GUI version or any other software that can do such a simple option by default without doing thousands unnecessary steps

**Comment by Hrxn** [comment]
Well, your decision. But it's actually really easy.

If your username is _1_, then it's just this file:
`C:\Users\1\youtube-dl.conf`

And inside this file just the line for the output template, e.g. 
`-o "D:/Temp/Media/%(extractor)s/%(title)s-%(id)s.%(ext)s"`

**Comment by Sonicpromo** [comment]
I understand that but I did it and things don't work out. I assume you think that I use youtube-dl via cmd, but that's not true. This setting is probably doesn't work correctly with GUI version
Same story with config.txt or youtube-dl.conf in %appdata%/roaming. I guess I should use cmd in that case?

**Comment by dstftw** [comment]
youtube-dl does not have an official GUI. Any youtube-dl's GUI is a 3rd party software that is not affiliated with youtube-dl. Contact its developers/issue tracker for any help.
How to achieve this with youtube-dl right away is clearly explained in FAQ:
https://github.com/rg3/youtube-dl#configuration
https://github.com/rg3/youtube-dl#output-template
