### ISSUE TITLE
Problem when extracting Opus

### ISSUE THREAD

**Issue by NicoxDJ** [rg3/youtube-dl#13560]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-x', u'-v', u'--audio-format', u'opus', u'https://www.youtube.com/watch?v=2ciLHgyzGbs']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.01
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.2-tessus, ffprobe 3.3.2-tessus, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 2ciLHgyzGbs: Downloading webpage
[youtube] 2ciLHgyzGbs: Downloading video info webpage
[youtube] 2ciLHgyzGbs: Extracting video information
[youtube] 2ciLHgyzGbs: Downloading MPD manifest
[debug] Invoking downloader on u'https://r6---sn-nv47lned.googlevideo.com/videoplayback?requiressl=yes&clen=4036743&signature=AD058CE83266F4EADF3F232F0196992BDE498F38.891079CE440592BF29F7DEB8EFC0BDA8B162518C&id=o-AP0intEVsh17HPppoTKDRSsphCk7cFeiXpF-h_2Z-rbX&mn=sn-nv47lned&mm=31&pl=21&dur=219.999&lmt=1493903630021379&ip=77.78.61.242&ms=au&ei=g4hbWdzDK4usco7QqaAI&keepalive=yes&mv=m&source=youtube&expire=1499192547&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&key=yt6&gir=yes&ipbits=0&mime=audio%2Fwebm&initcwndbps=1972500&itag=171&mt=1499170834&ratebypass=yes'
[download] Destination: videoname.webm
[download] 100% of 3.85MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams 'file:videoname.webm'
[ffmpeg] Destination: videoname.opus
[debug] ffmpeg command line: ffmpeg -y -i 'file:videoname.webm' -vn -acodec opus -b:a 5k 'file:videoname.opus'
Deleting original file videoname.webm (pass -k to keep)
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Hello.
I just noticed something. I'm using this command:
 youtube-dl -x --audio-format opus $1;
In most videos its downloading the correct opus file.
But in some videos is "Downloading MPD manifest" and than on "[ffmpeg] Destination:" freeze for a bit, and than the opus file is limited with lowpass to 5khz and the file is like 200kb instead of 4mb.
The video that i'm having problem with downloading good Opus is: https://www.youtube.com/watch?v=2ciLHgyzGbs
PS: i tried: --youtube-skip-dash-manifest, but it doesn't help

**Comment by dstftw** [comment]
You are converting bestaudio format that is vorbis to opus with default `--audio-quality`.

**Comment by NicoxDJ** [comment]
You didn't get my point... The problem is existing only one some videos. + I have another browser extension, that downloads the full opus, as supposed to be...

**Comment by Hrxn** [comment]
What browser extension?

Is that something you are trying to use together with youtube-dl?
I don't really get what you are describing, to be honest.

**Comment by NicoxDJ** [comment]
This is the extension http://en.savefrom.net (sorry for the ad...)
1. youtube-dl has downloading opus, but just in SOME videos doesn't download it with the proper size.
2. just to be sure, i try to download the opus of the same video with that extension, and i download it correctly.
3. the video that i have problem with downloading the correct opus file is noted above.
4. I tried to download the source as "best" not "opus" and youtube-dl download .ogg, but still if this is the best audio, why the browser extension can extract opus?

**Comment by dstftw** [comment]
1. It downloads exactly what you ask it to download - `bestaudio`. `bestaudio` is not always opus.
2. You ask it to convert to opus - you get `bestaudio` that is vorbis converted to opus.
3. If you want it to download opus, ask it to download opus: `-f bestaudio[acodec=opus]`.
4. Bother to read [FAQ](https://github.com/rg3/youtube-dl#format-selection) already.
