### ISSUE TITLE
Vevo videos can not extract it by youtube-dl (I have compile last version to day 4-7-2017) .. (Dreambox Mytube Plugin)

### ISSUE THREAD

**Issue by fairbird** [rg3/youtube-dl#13566]
[youtube] YQHsXMglC9A: Downloading webpage
[youtube] YQHsXMglC9A: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflotiWiu/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflotiWiu/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
W/  [VideoUrlRequest._request] :: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflotiWiu/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflotiWiu/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Playing URL broken...

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by fairbird** [comment]
Thank you for your answer ..
But it is not an outdated version .. It is latest version I have compile and using ..
I have compiled and built it by this recipe to use it for Dreambox images..

`SUMMARY = "Download videos from YouTube (and more sites)"
DESCRIPTION = "youtube-dl is a small command-line program to download videos \
from YouTube.com and a few more sites. It requires the Python interpreter \
(2.6, 2.7, or 3.2+), and it is not platform specific"
HOMEPAGE = "http://rg3.github.io/youtube-dl/"
SECTION = "devel/python"
LICENSE = "LGPLv2.1"
PACKAGE_ARCH = "all"
LIC_FILES_CHKSUM = "file://LICENSE;md5=7246f848faa4e9c9fc0ea91122d6e680"
DEPENDS = "libxml2 python-html bash-completion"
SRCREV = "16a09aefe33ba2d0122926d761f89a93c0c7e7d6"
PV = "2017.07.04"

SRC_URI = "git://github.com/rg3/youtube-dl.git;branch=master"

S = "${WORKDIR}/git"

inherit setuptools

EXTRA_OEMAKE = "PYTHON=${PYTHON}"

do_compile_prepend() {
    oe_runmake lazy-extractors youtube-dl.bash-completion
}

do_install_append() {
    mv ${D}${datadir}/etc ${D}${sysconfdir}
    install -m 0755 -d ${D}${sysconfdir}/bash_completion.d
    install -m 0644 youtube-dl.bash-completion ${D}${sysconfdir}/bash_completion.d
}

RDEPENDS_${PN} = " \
    python-email \
    python-gdata \
    python-subprocess \
    python-unixadmin \
    python-ctypes \
    python-argparse \
    "

PACKAGES =+ " ${PN}-src"
RDEPENDS_{PN}-src = "${PN}"
FILES_${PN}-src = " \
    ${libdir}/${PYTHON_DIR}/site-packages/*/*.py \
    ${libdir}/${PYTHON_DIR}/site-packages/*/*/*.py \
    ${libdir}/${PYTHON_DIR}/site-packages/*/*/*/*.py \
    ${libdir}/${PYTHON_DIR}/site-packages/*/*/*/*/*.py \
    ${libdir}/${PYTHON_DIR}/site-packages/youtube_dl-*-py2.7.egg-info/* \
    ${datadir}/etc/* \
    ${sysconfdir} \
    "`
Thank you

**Comment by dstftw** [comment]
No, it's not. Prove with verbose log.

**Comment by fairbird** [comment]
I update my recipe and build newest files ..

and I have got new error ..


[youtube] uAVUl0cAKpo: Downloading webpage
[gRC] main thread is non-idle! display spinner!
[youtube] uAVUl0cAKpo: Extracting video information
WARNING: "id" field is not a string - forcing string conversion, there is an error in extractor
Playing URL https://r1---sn-8p85-c5il.googlevideo.com/videoplayback?ms=au&mt=1499221711&mv=m&source=youtube&ip=94.76.6.25&mime=video%2Fmp4&key=yt6&itag=22&id=o-ABIg35MPeqT0K1W08R-r-HQM8WsqmX2oKfYGBFYGJovJ&requiressl=yes&dur=226.998&mm=31&mn=sn-8p85-c5il&pl=21&ipbits=0&ratebypass=yes&expire=1499243385&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ei=GE9cWc2XNMHNcOv7ovAD&initcwndbps=7590000&lmt=1486823606846679&signature=DFE6F04542D831748C8C68AE00ED64A922D46188.4831D179701B6E6B52C8F7C3C9D3B1610A585E05
setSeekState
No Service found
evEOF=8
seekable status changed!
setSeekState
trying to switch to playing- state: 1
No Service found
playing 4097:0:0:0:0:0:0:0:0:0:https%3a//r1---sn-8p85-c5il.googlevideo.com/videoplayback?ms=au&mt=1499221711&mv=m&source=youtube&ip=94.76.6.25&mime=video%252Fmp4&key=yt6&itag=22&id=o-ABIg35MPeqT0K1W08R-r-HQM8WsqmX2oKfYGBFYGJovJ&requiressl=yes&dur=226.998&mm=31&mn=sn-8p85-c5il&pl=21&ipbits=0&ratebypass=yes&expire=1499243385&sparams=dur%252Cei%252Cid%252Cinitcwndbps%252Cip%252Cipbits%252Citag%252Clmt%252Cmime%252Cmm%252Cmn%252Cms%252Cmv%252Cpl%252Cratebypass%252Crequiressl%252Csource%252Cexpire&ei=GE9cWc2XNMHNcOv7ovAD&initcwndbps=7590000&lmt=1486823606846679&signature=DFE6F04542D831748C8C68AE00ED64A922D46188.4831D179701B6E6B52C8F7C3C9D3B1610A585E05:Sabrina Carpenter - Thumbs (Official Video)
[servicelist] search for service in userbouquets
[servicelist] service not found in any userbouquets
eServiceApp::fillSubservices - failed to retrieve subservices, not supported url
PlayerBackend::gotMessage - tStart
PlayerApp::processStart: exteplayer3 "https://r1---sn-8p85-c5il.googlevideo.com/videoplayback?ms=au&mt=1499221711&mv=m&source=youtube&ip=94.76.6.25&mime=video%2Fmp4&key=yt6&itag=22&id=o-ABIg35MPeqT0K1W08R-r-HQM8WsqmX2oKfYGBFYGJovJ&requiressl=yes&dur=226.998&mm=31&mn=sn-8p85-c5il&pl=21&ipbits=0&ratebypass=yes&expire=1499243385&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ei=GE9cWc2XNMHNcOv7ovAD&initcwndbps=7590000&lmt=1486823606846679&signature=DFE6F04542D831748C8C68AE00ED64A922D46188.4831D179701B6E6B52C8F7C3C9D3B1610A585E05" -a -d -w -l -s 
PlayerBackend::recvStopped - retval = 0
PlayerBackend::thread_finished
[eRCDeviceInputDev] 0 160 1
PlayerBackend::gotMessage - stop
eServiceApp::gotExtPlayerMessage - stop
eServiceApp::isCurrentlySeekable
resolved to PLAY
eServiceApp::unpause
setSeekState
service is pausable
evEOF=8
Event EOF

Thank you

**Comment by dstftw** [comment]
youtube-dl did its job:
>Playing URL https://r1---sn-8p85-c5il.googlevideo.com/videoplayback?ms=au&mt=1499221711&mv=m&source=youtube&ip=94.76.6.25&mime=video%2Fmp4&key=yt6&itag=22&id=o-ABIg35MPeqT0K1W08R-r-HQM8WsqmX2oKfYGBFYGJovJ&requiressl=yes&dur=226.998&mm=31&mn=sn-8p85-c5il&pl=21&ipbits=0&ratebypass=yes&expire=1499243385&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ei=GE9cWc2XNMHNcOv7ovAD&initcwndbps=7590000&lmt=1486823606846679&signature=DFE6F04542D831748C8C68AE00ED64A922D46188.4831D179701B6E6B52C8F7C3C9D3B1610A585E05

The rest is output from Dreambox, contact with its support.
