### ISSUE TITLE
FaceBook: youtube_dl.utils.ExtractorError: Cannot parse data;

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#13567]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
>youtube-dl.py -v "https://www.facebook.com/1283046064/videos/10213198784825866/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/1283046064/videos/10213198784825866/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.07.02
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 10213198784825866: Downloading webpage
[facebook] 10213198784825866: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\facebook.py", line 412, in _real_extract
    video_id, fatal_if_no_video=True)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\facebook.py", line 329, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.


```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.facebook.com/1283046064/videos/10213198784825866/

---

FWIW...direct link worked with generic extractor:

https://video.fybz2-2.fna.fbcdn.net/v/t43.1792-2/19676819_321098884968596_7819949193228713984_n.mp4?efg=eyJybHIiOjI2MTAsInJsYSI6MTAyNCwidmVuY29kZV90YWciOiJzdmVfaGQifQ%3D%3D&rl=2610&vabr=1740&oh=f1b697b49168f5ce2f4ae67fd9cbfae5&oe=595C2384

Thanks
Ringo

**Comment by yan12125** [comment]
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', 'https://www.facebook.com/1283046064/videos/10213198784825866/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.25
[debug] Lazy loading extractors enabled
[debug] Python version 3.6.1 - Linux-4.11.5-1-ARCH-x86_64-with-arch
[debug] exe versions: avconv v13_dev0-1201-g61f589e31, avprobe v13_dev0-1201-g61f589e31, ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[facebook] 10213198784825866: Downloading webpage
[debug] Invoking downloader on 'https://video-tpe1-1.xx.fbcdn.net/v/t42.1790-2/19752645_173946619810891_7554897445608488960_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNDI2X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ==&oh=fd8472bd2a1f3a574a74c2dacbf9bec3&oe=595CC4B4'
[download] Destination: Meanwhile in Sooke 有 1,885 位成員。 Sooke seen through the eyes of it's community...-10213198784825866.f173946616477558vd.mp4
[download] 100% of 4.45MiB in 00:00
[debug] Invoking downloader on 'https://video-tpe1-1.xx.fbcdn.net/v/t42.1790-2/19797883_855693554607411_3961246563279306752_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNDI2X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfYXVkaW8ifQ==&oh=99f2e7a3b88844946c6ab3ef6cc15980&oe=595CAFFB'
[download] Destination: Meanwhile in Sooke 有 1,885 位成員。 Sooke seen through the eyes of it's community...-10213198784825866.f855693547940745ad.m4a
[download] 100% of 291.09KiB in 00:00
[ffmpeg] Merging formats into "Meanwhile in Sooke 有 1,885 位成員。 Sooke seen through the eyes of it's community...-10213198784825866.mp4"
[debug] ffmpeg command line: avconv -y -i 'file:Meanwhile in Sooke 有 1,885 位成員。 Sooke seen through the eyes of it'"'"'s community...-10213198784825866.f173946616477558vd.mp4' -i 'file:Meanwhile in Sooke 有 1,885 位成員。 Sooke seen through the eyes of it'"'"'s community...-10213198784825866.f855693547940745ad.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Meanwhile in Sooke 有 1,885 位成員。 Sooke seen through the eyes of it'"'"'s community...-10213198784825866.temp.mp4'
Deleting original file Meanwhile in Sooke 有 1,885 位成員。 Sooke seen through the eyes of it's community...-10213198784825866.f173946616477558vd.mp4 (pass -k to keep)
Deleting original file Meanwhile in Sooke 有 1,885 位成員。 Sooke seen through the eyes of it's community...-10213198784825866.f855693547940745ad.m4a (pass -k to keep)
```

Works here. Could you run youtube-dl with --write-pages and upload *.dump files somewhere?

**Comment by RingoTheDog** [comment]
[10213198784825866_https_-_www.facebook.com_video_video.phpv=10213198784825866.dump.txt](https://github.com/rg3/youtube-dl/files/1125458/10213198784825866_https_-_www.facebook.com_video_video.phpv.10213198784825866.dump.txt)
[10213198784825866_https_-_www.facebook.com_1283046064_videos_10213198784825866_.dump.txt](https://github.com/rg3/youtube-dl/files/1125459/10213198784825866_https_-_www.facebook.com_1283046064_videos_10213198784825866_.dump.txt)

**Comment by yan12125** [comment]
Hmmm is it resolved?
