### ISSUE TITLE
Shouldn't running process name show "youtube-dl", not "python"

### ISSUE THREAD

**Issue by bendover22** [rg3/youtube-dl#13577]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

More of a question, really.
In Linux System Monitor, or in NetStat output, the Youtube-dl running process name shows as "**python"**, beside the PID and / or port number that YT-dl is using.

`Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 127.0.0.1:40222         127.0.0.1:9150          ESTABLISHED 1000       320748      22379/python`

Shouldn't it show the actual application name?  I've never seen other application's running process name shown as 'C++' or 'Perl.'

If trying to verify which port YT-dl is using, or using a proxy correctly, etc., not showing the real process name makes it difficult to identify the correct process.

In Linux, there are many running processes with 'python' or 'py' -  as part of the name.

Thanks.

**Comment by yan12125** [comment]
It should have been done in ```youtube_dl.utils.setproctitle()```, but it's now partially broken due to unknown reasons. Only thread names are changed, so you need ```ps -eL``` or ```ps -eT``` to see it.

**Comment by yan12125** [comment]
Hmmm seems it's impossible with pure Python. There was a patch to Python but rejected: https://mail.python.org/pipermail/python-list/2001-August/073640.html.
If CPython eventually adds this function, we can reopen this ticket.
