### ISSUE TITLE
can this script be incorporated with clipbucket.com script ?

### ISSUE THREAD

**Issue by spirogg** [rg3/youtube-dl#13585]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ X] Other
I am using clipbucket.com script - http://demo.clipbucket.com/
https://github.com/arslancb/clipbucket

 it has capability to upload videos and uses ffmpeg to convert them to mp4 also has capability to embed youtube videos adding them as embed videos in the mysql database to view.

My Question is how can I add this script to use this script to copy and paste URL of youtube video in clipbucket area where we embed video and it would process it and download the video instead and add it to the database of clipbucket script 
![clipbucket-script-youtube-grab-area](https://user-images.githubusercontent.com/17736688/27934563-ef4556f4-626b-11e7-9a97-ae32dbc9727f.PNG)

I have inserted a picture of what the form looks like when we grab a youtube video but would like user to add the url there and script to be used to download youtube video and place it in database for viewing 

thanks spiro
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
This question should be addressed to clipbucket.
