### ISSUE TITLE
Session expired problem when downloading from Lynda.com!

### ISSUE THREAD

**Issue by OnlyMihir** [rg3/youtube-dl#13589]
I tried downloading some courses from lynda.com today using cookies.txt file,with this command ("youtube-dl.exe --cookies cookies.txt --all-subs PasteCourseLinkHere").I have downloaded many courses from Lynda.com in the past using this command but since today i can't download more than 7 videos from a course as after that some json error occurs and when i tried this command again i get a session expired error.In chrome my lynda.com session is not expired but in youtube-dl it shows session expired.There is a workaround to this issue that we have to again create cookies.txt file and paste it in youtube-dl option and start again and by this way we can download whole course but if the course is big than it's not possible to create cookies.txt again and again.And yes my youtube-dl is fully updated.

**Comment by OnlyMihir** [comment]
![error](https://user-images.githubusercontent.com/22279924/27953051-11da0446-6328-11e7-8cab-0ed5512f2ecb.png)

**Comment by codewizard13** [comment]
@OnlyMihir Did you find a solution? Why did you close this? I am eager to learn what you discovered with this downloading from Lynda issue.

**Comment by OnlyMihir** [comment]
I closed this thread because no one from the youtube-dl team came here to answer my problem and the issue is still not solved.
