### ISSUE TITLE
ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>

### ISSUE THREAD

**Issue by junmuzi** [rg3/youtube-dl#13581]
I hit follow issue on my ubuntu 16.04, could anybody help to solve my issue, thanks very much.

As follows show:
root@yingzi:~# proxychains youtube-dl https://www.youtube.com/watch?v=BcWX6lyRxsE
ProxyChains-3.1 (http://proxychains.sf.net)
[youtube] BcWX6lyRxsE: Downloading webpage
|D-chain|-<>-127.0.0.1:1080-<><>-61.91.161.217:443-<><>-OK
[youtube] BcWX6lyRxsE: Downloading video info webpage
|D-chain|-<>-127.0.0.1:1080-<><>-61.91.161.217:443-<><>-OK
[youtube] BcWX6lyRxsE: Extracting video information
[youtube] BcWX6lyRxsE: Downloading MPD manifest
|D-chain|-<>-127.0.0.1:1080-<><>-216.58.200.33:443-<><>-OK
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
|D-chain|-<>-127.0.0.1:1080-<><>-219.76.4.73:443-<><>-OK
ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>

**Comment by junmuzi** [comment]
Somebody say it is due to the limit of youtube site. Is it right?

**Comment by yan12125** [comment]
Apparently you've solved it :) https://github.com/rg3/youtube-dl/issues/10782#issuecomment-313457387

> Somebody say it is due to the limit of youtube site. Is it right?

Usually YouTube returns HTTP error 429 for restriction. They don't use confusing words like "EOF occurred in violation of protocol"

**Comment by jackpgao** [comment]
Same problem.

**Comment by alfredo-f** [comment]
Just happened in the middle of a download:

youtube-dl --config-location /private/etc --retries "infinite" --fragment-retries "infinite" --limit-rate "190K" -o "[omitted]/%(title)s.%(ext)s" https://youtu.be/RvpwzsXGltY

[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] RvpwzsXGltY: Downloading webpage
[youtube] RvpwzsXGltY: Downloading video info webpage
[youtube] RvpwzsXGltY: Extracting video information
[youtube] RvpwzsXGltY: Downloading MPD manifest
[youtube] RvpwzsXGltY: Downloading MPD manifest
[dashsegments] Total fragments: 1557
[download] Destination: [omitted].f135.mp4
[download]  72.1% of ~177.65MiB at 67.26KiB/s ETA 07:45ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>

System: OSX El Capitan Version 10.11.6 (15G1611)

**Comment by dvdobrovolskiy** [comment]
same

**Comment by TheCrott** [comment]
@dvdobrovolskiy The solution is simple: just update your youtube-dl. I encountered eof error and when I check youtube-dl's repo there's new version, so I simply upgrade via pip
