### ISSUE TITLE
[Feature Request]Download the infoq presentation slides together

### ISSUE THREAD

**Issue by flyisland** [rg3/youtube-dl#13586]
The infoq presentation is combined with a video and a set of slides. It'd be great if youtube-dl could download the slides and create a offline web page to play the video synced with the slides.

**Comment by vdm** [comment]
https://github.com/cykl/infoqscraper

**Comment by flyisland** [comment]
@vdm, thanks

**Comment by yegortimoshenko** [comment]
Infoqscraper doesn't work anymore (ever since InfoQ switched to HTML5 videos). Would like to see this reopened for visibility.

**Comment by remitamine** [comment]
@yegortimoshenko if it's not working for then you can open a new with all the necessary information, and make sure that you're using the latest version.
