### ISSUE TITLE
Problem to play some youtube link on Discord musikbot

### ISSUE THREAD

**Issue by Warnyx** [rg3/youtube-dl#13582]
Have update my youtube-dl and use the update_deps.exe but its still happen when i whant that my bot play a link i got this report: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    {
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 897, in _extract_signature_function
    },
youtube_dl.utils.ExtractorError: Cannot identify player '/yts/jsbin/player-vfl3RjfTG/en_US/base.js'
 (caused by ExtractorError("Cannot identify player '/yts/jsbin/player-vfl3RjfTG/en_US/base.js'",))
 

I will be happy if someone can help me

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by Warnyx** [comment]
i have update it with this "this FAQ entry " your send but still the same

**Comment by dstftw** [comment]
Bother to read new issue template and **prove** with verbose log.

**Comment by Warnyx** [comment]
how can i send you my log that you can see it?(sry im realy new at the)

**Comment by Warnyx** [comment]
fix it self was that he put both version at the same place and he load the old one
