### ISSUE TITLE
Unable to download JSON metadata (www.atresplayer.com) with private videos

### ISSUE THREAD

**Issue by edumj** [rg3/youtube-dl#13597]
### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
"youtube-dl.exe" "http://www.atresplayer.com/television/programas/hormiguero/temporada-6/capitulo-154-steve-carell-kristen-wiig_2017062900851.html" -o "%%(title)s (%%(extractor_key)s) %var_resolucion_txt%.%%(ext)s"	--verbose	--no-mtime --console-title -f  best	
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [' http://www.atresplayer.com/television/programas/hormiguero/temporada-6/capitulo-154-steve-carell-kristen-wiig_2017062900851.html', '-o', '%(title)s (%(extractor_key)s) .%(ext)s', '--verbose', '--no-mtime', '--console-title', '-f', 'best', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.07.02
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-65201-gd0f56ca
[debug] Proxy map: {}
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\extractor\common.py", line 502, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\YoutubeDL.py", line 2137, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default


```

--

### Description of your *issue*, suggested solution and other information

Hi, I can view and download videos from this site, but only the first 7 days, then the video becomes "private" and I have to put username and password in order to watch them. The problem is that YouTube-dl gives that error when 7 days past, even if I put my user and password:
--username xxxx	--password xxx

You must register to see that error happening, or I can send you my user/pass if you need it.

Thanks.

**Comment by dstftw** [comment]
Duplicate of #12961.
