### ISSUE TITLE
yt-dl no longer downloading from http://www.arte.tv/fr

### ISSUE THREAD

**Issue by PorkPieHat** [rg3/youtube-dl#13592]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl --verbose -F http://www.arte.tv/fr/videos/041012-003-A/la-valse-des-continents
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-F', u'http://www.arte.tv/fr/videos/041012-003-A/la-valse-des-continents']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.02
[debug] Python version 2.7.12 - Linux-4.8.0-56-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 3.3-static, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[arte.tv:+7] la-valse-des-continents: Downloading webpage
[arte.tv:+7] la-valse-des-continents: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'VID',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/arte.py", line 203, in _real_extract
    return self._extract_from_webpage(webpage, video_id, lang)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/arte.py", line 246, in _extract_from_webpage
    return self._extract_from_json_url(json_url, video_id, lang, title=title)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/arte.py", line 86, in _extract_from_json_url
    title = (player_info.get('VTI') or title or player_info['VID']).strip()
KeyError: u'VID'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 446, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'VID',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

azed@azed-H270N:~$
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

yt-dl no longer downloading from http://www.arte.tv/fr

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by PorkPieHat** [comment]
azed@azed-H270N:~$ youtube-dl --verbose --dump-pages -F http://www.arte.tv/fr/videos/041012-003-A/la-valse-des-continents
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--dump-pages', u'-F', u'http://www.arte.tv/fr/videos/041012-003-A/la-valse-des-continents']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.02
[debug] Python version 2.7.12 - Linux-4.8.0-56-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 3.3-static, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[arte.tv:+7] la-valse-des-continents: Downloading webpage
[arte.tv:+7] Dumping request to http://www.arte.tv/fr/videos/041012-003-A/la-valse-des-continents
PCFkb2N0eXBlIGh0bWw+CgoKICAgICAgICAgICAgICAgICAgICAKPGh0bWwgY2xhc3M9Im5vLWpzIiBsYW5nPSJmciIKICAgIGRhdGEtYmFzZS11cmw9IiIKICAgIGRhdGEtZW52PSJwcm9kIgogICAgZGF0YS1oZWFkZXItYmFzZS11cmw9Imh0dHBzOi8vc3RhdGljLWNkbi5hcnRlLnR2L3N0YXRpYy9zdHlsZWd1aWRlLzIuNy4xL3NyYy8iCiAgICBk...

[A huge amount of the above alphabet soup]

...ICAia2luZCI6ICJTSE9XIiwKICAgICAgICAia2luZExhYmVsIjogIlBST0dSQU1NRSIsCiAgICAgICAgImNvbGxlY3Rpb25zIjogW10sCiAgICAgICAgImFydGVDbHViIjogZmFsc2UsCiAgICAgICAgInByb2dyYW1UeXBlIjogIkJST0FEQ0FTVCIsCiAgICAgICAgInBhcmVudFByb2dyYW1JZCI6ICIwNDEwMTItMDAzLUEiLAogICAgICAgICJtYXJraW5ncyI6IFtdCiAgICB9Cn0=
[arte.tv:+7] la-valse-des-continents: Checking HTTPS_SQ_1 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HTTPS_SQ_2 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HTTPS_MQ_8 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HTTPS_MQ_2 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HTTPS_MQ_1 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HLS_XQ_2 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HTTPS_EQ_2 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HTTPS_EQ_1 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HLS_XQ_1 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HTTPS_HQ_8 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HTTPS_SQ_8 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HLS_XQ_8 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HTTPS_EQ_8 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HTTPS_HQ_1 video format URL
[arte.tv:+7] la-valse-des-continents: Checking HTTPS_HQ_2 video format URL
[info] Available formats for 041012-003-A:
format code  extension  resolution note
HLS_XQ_2     m3u8       1280x720   VA, Allemand (Doublé) 2200k 
HTTPS_HQ_2   mp4        640x360    VA, Allemand (Doublé)  800k 
HTTPS_MQ_2   mp4        384x216    VA, Allemand (Doublé)  300k 
HTTPS_EQ_2   mp4        720x406    VA, Allemand (Doublé) 1500k 
HTTPS_SQ_2   mp4        1280x720   VA, Allemand (Doublé) 2200k 
HLS_XQ_8     m3u8       1280x720   VOF-STMF, Version française - ST sourds/mal 2200k 
HTTPS_HQ_8   mp4        640x360    VOF-STMF, Version française - ST sourds/mal  800k 
HTTPS_MQ_8   mp4        384x216    VOF-STMF, Version française - ST sourds/mal  300k 
HTTPS_EQ_8   mp4        720x406    VOF-STMF, Version française - ST sourds/mal 1500k 
HTTPS_SQ_8   mp4        1280x720   VOF-STMF, Version française - ST sourds/mal 2200k 
HLS_XQ_1     m3u8       1280x720   VOF, Français (original) 2200k 
HTTPS_HQ_1   mp4        640x360    VOF, Français (original)  800k 
HTTPS_MQ_1   mp4        384x216    VOF, Français (original)  300k 
HTTPS_EQ_1   mp4        720x406    VOF, Français (original) 1500k 
HTTPS_SQ_1   mp4        1280x720   VOF, Français (original) 2200k  (best)
azed@azed-H270N:~$

**Comment by dstftw** [comment]
Post the **FULL** output.

**Comment by dstftw** [comment]
As clearly seen from the log it worked fine last time.

**Comment by PorkPieHat** [comment]
Sorry to bother you with this. Yt-dl is indeed working fine. Great piece of kit by the way.
