### ISSUE TITLE
Download all DASH audio and video formats from YouTube

### ISSUE THREAD

**Issue by edent** [rg3/youtube-dl#13594]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

I can't download *all* DASH formats from a YouTube video.

At the moment I'm using:

```
youtube-dl  -f 139,140,160,133,134,135,136,137 -o '%(format)s.%(ext)s' youtube.com/....
```

Can I assume that those format numbers will always be the same for DASH video and audio?  Or will some YouTube videos use different numbers?

If I use `-f m4a` I only get the highest quality m4a, rather than all variants.

I'm aware that I could use `--all-formats` - but that will also get me things I don't want, like 3gp files.

If I use `-f "[protocol=http_dash_segments]"` or ` -f "[ext=m4a]"` I get `ERROR: requested format not available`

So...

* Are `139,140,160,133,134,135,136,137` the only DASH formats available?
* If not, is there an option I can use to get them all?

**Comment by dstftw** [comment]
1. No guarantees on format ids.
2. `-f 'all[acodec=none]'`.
