### ISSUE TITLE
[Bilibili] can not download video from bilibili playlist

### ISSUE THREAD

**Issue by Luxios** [rg3/youtube-dl#13590]
### What Happened
> youtube-dl http://www.bilibili.com/video/av2070056/index_2.html

WARNING: Assuming --restrict-filenames since file system encoding cannot encode
 all characters. Set the LC_ALL environment variable to fix this.
[BiliBili] 2070056: Downloading webpage
ERROR: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### Version Information
Name: youtube-dl
Version: 2017.7.2
Summary: YouTube video downloader
Home-page: https://github.com/rg3/youtube-dl
Author: Sergey M.
Author-email: dstftw@gmail.com

**Comment by yan12125** [comment]
Bilibili said http://www.bilibili.com/video/av2070056/index_2.html is gone:

![default](https://user-images.githubusercontent.com/1937689/27958306-039f2c9e-6355-11e7-8c49-8be75e05811a.png)

Is this video limited to China or it requires an account?

**Comment by siddht1** [comment]
@yan12125 this does not require account,http://www.bilibili.com/video/av11896645/ works ,youtube-dl http://www.bilibili.com/video/av11896645/
[BiliBili] 11896645: Downloading webpage
[BiliBili] 11896645: Downloading video info page
[download] Destination: 【MAD_小魔女学园-戴亚】关于亚可的烦恼-11896645.mp4
[download]   2.5% of 15.83MiB at 147.39KiB/s ETA 01:47^C
ERROR: Interrupted by user

just cant stop to laugh seeing the 404 error and the site name,for us bili means cat

**Comment by siddht1** [comment]
@yan12125 If clarification is needed from my side then http://www.bilibili.com/video/av2070056/index_2.html  is gone forever,the cartoon or comic you see is a custom 404 error.
so to test the working condition of the site i tested http://www.bilibili.com/video/av11896645/  thats works.

So now need @Luxios to provide any alternate video id

**Comment by leesei** [comment]
e.g. https://www.bilibili.com/video/av996200/
There are 56 videos, `youtube-dl  https://www.bilibili.com/video/av996200/` only downloads the first one.

**Comment by yan12125** [comment]
FYI: https://www.bilibili.com/video/av996200/ has the same issue as http://www.bilibili.com/video/av9291699/ (#12654).

As the original author does not respond, I'm going to close this issue.
