### ISSUE TITLE
Can't download videos from Dailymotion

### ISSUE THREAD

**Issue by jin78** [rg3/youtube-dl#13604]
Hi,

I can't download videos from Dailymotion, so let's do a recap:

- **OS**: Debian 8 (Jessy)
- **youtube-dl installed from:** pip
- youtube-dl -v output:
[debug] System config: []                                                                                               [debug] User config: []                                                                                                 [debug] Custom config: []                                                                                               [debug] Command-line args: [u'-v']                                                                                      [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8                                                        [debug] youtube-dl version 2017.07.02                                                                                   [debug] Python **version 2.7.9** - Linux-4.9.29-8-osmc-armv7l-with-debian-8.8                                               [debug] exe versions: none                                                                                              [debug] Proxy map: {}

Why doesn't it download any video?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by jin78** [comment]
You could have at least tried to reproduce the issue instead of closing it...
