### ISSUE TITLE
[youtube] parsing titles

### ISSUE THREAD

**Issue by jjousun** [rg3/youtube-dl#13608]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

Used youtube-dl to retrieve json objects of a user's youtube history. Relevant fields from the json files are `title` and `categories`. After filtering by the category 'Music,' trying to parse titles into 'artist' and 'title' - but this isn't 100% accurate. 

Is there a way that youtube-dl will allow for parsing of this data? Will working with the --add-metadata or --metadata-from-title be able to parse the artist and title cleanly (especially if the audio or video isn't needed)?

**Comment by dstftw** [comment]
`--add-metadata` or `--metadata-from-title` are postprocessing options thus only work during media postprocessing stuff. Metadata extracted via `--metadata-from-title` is not reflected in exported JSON.
