### ISSUE TITLE
Feature request - keyword search

### ISSUE THREAD

**Issue by kgoerbig** [rg3/youtube-dl#13615]
Pull request wasn't available, so I am posting here. Any chance keyword search for xxx extractors and youtube can be added? Search results return keyword from titles/description, and include unique download id's to easily do a keyword search, and download video with youtube-dl based on the id #.

**Comment by dstftw** [comment]
>make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
