### ISSUE TITLE
[googledrive] Add support for subtitles

### ISSUE THREAD

**Issue by nyuszika7h** [rg3/youtube-dl#13619]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '--write-sub', 'https://drive.google.com/file/d/0B0Pcx5-LUToEblNxcXRPWmtmS00/view', '-o', 'Ha felhő lehetnék E20.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.09
[debug] Python version 3.6.1+ - Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: ffmpeg 3.3.2-1, ffprobe 3.3.2-1, rtmpdump 2.4
[debug] Proxy map: {}
[GoogleDrive] 0B0Pcx5-LUToEblNxcXRPWmtmS00: Downloading webpage
[debug] Invoking downloader on 'https://r4---sn-c0q7lne6.c.docs.google.com/videoplayback?id=851eb6773c9a6ff5&itag=18&source=webdrive&requiressl=yes&mm=30&mn=sn-c0q7lne6&ms=nxu&mv=u&pl=21&sc=yes&ttl=transient&ei=nXZiWbLkKonFqgWjz4boDw&driveid=0B0Pcx5-LUToEblNxcXRPWmtmS00&mime=video/mp4&lmt=1499099742696479&mt=1499625042&ip=84.2.121.30&ipbits=0&expire=1499639517&cp=QVJOQUdfWFVPSFhNOkxoNkR2Tk5NTUhw&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Csc%2Cttl%2Cei%2Cdriveid%2Cmime%2Clmt%2Ccp&signature=70F7ADDD5EF99714F7B845E73866DAEF28648FAB.13576CE76EE0231268989BFFEFB65B82469414A2&key=ck2&app=texmex'
[download] Ha felhő lehetnék E20.mp4 has already been downloaded
[download] 100% of 330.39MiB
```

---

### Description of your *issue*, suggested solution and other information

[This video](https://drive.google.com/file/d/0B0Pcx5-LUToEblNxcXRPWmtmS00/view) has Hungarian subtitles, but youtube-dl doesn't recognize them.

Subtitle URL: https://drive.google.com/timedtext?authuser=0&id=0B0Pcx5-LUToEblNxcXRPWmtmS00&vid=851eb6773c9a6ff5&hl=en-US&v=0B0Pcx5-LUToEblNxcXRPWmtmS00&type=track&lang=hu&name&kind&fmt=1

**Comment by parmjitv** [comment]
Hi @nyuszika7h,

As @dstftw has noted, the extractor for Google Drive videos should be updated to include any available captions.  I will give this one a shot if no one has any objections.

How did you deduce the URL for the Hungarian subtitles?  I was not able to find a reference for this anywhere in the page source for this video.

Cheers,

Parmjit V.

**Comment by nyuszika7h** [comment]
I just loaded the page in Firefox and used the network request logger. There's a request to some `captions.js` before that, which may be helpful. I'll also take a closer look at it.

**Comment by siddht1** [comment]
the subtitle you mentioned is in raw xml form,so the closest format one can either obtain is pure xml or webvtt also known as vtt.So a little parse and this can be obtained.I have simply converted xml to vtt and srt.Just remove .txt as github doesnt recognize xml,vtt,srt.
[hu.vtt.txt](https://github.com/rg3/youtube-dl/files/1135035/hu.vtt.txt)
[hu.srt.txt](https://github.com/rg3/youtube-dl/files/1135036/hu.srt.txt)



[hu.xml.txt](https://github.com/rg3/youtube-dl/files/1135034/hu.xml.txt)

**Comment by parmjitv** [comment]
@nyuszika7h - Cool.  I will look into that further as well.  Basically I am looking for a generic URL that can be used to extract the caption data for a given video, Hungarian or otherwise.  If such a URL exists we should be able to use it in the extractor to fetch the subtitle info.

@siddht1 - Thank you!  Did you have to convert the XML file manually?

I believe youtube-dl supports both SRT and VTT file formats for captions - please correct me if I am mistaken?

**Comment by siddht1** [comment]
@parmjitv  not at all just did necessary changes to my javascript code to output likewise,Its not a big deal in js but I dont know how to do it in py.I can provide the js code if you like.

youtube-dl supports all subtitle but it wont recognize a standard xml as an subtitle.In fact no player can,so the easiest and the closest it vtt(subtitle based on xml standard)

**Comment by parmjitv** [comment]
@siddht1 - OK.  I have figured out the URL schema for the captions and should have a new PR ready in the next day or so.

I am going to compose the subtitles as SRT files, using the example file you have provided as a template.  There are some utilities already available in the codebase to help us out - if this does not work we can look at using the VTT format as you suggest instead.

**Comment by siddht1** [comment]
@parmjitv  ok but I am just showing you a small part of the js code I used to convert the xml to vtt.

`<script>
var request = new XMLHttpRequest();
request.open("GET", "hu.xml", false);
request.send();
var xml = request.responseXML;
var users = xml.getElementsByTagName("transcript");
var user,names;
for(var i = 0; i < users.length; i++) 
{
    user = users[i];
    names = user.getElementsByTagName("text");
    for(var j = 0; j < names.length; j++) {
     document.write(names[j].childNodes[0].nodeValue+"<br>");
      //document.write(names[j]+"<br>");
   }
}
//document.write(users.length+"<br>")
//document.write(names[0].start)
</script> 


hope this helps too.
 
`

**Comment by nyuszika7h** [comment]
youtube-dl [already supports](https://github.com/rg3/youtube-dl/blob/a02682fd13ce5ba88d2508c90559eaa7f43b65d5/youtube_dl/postprocessor/ffmpeg.py#L580) TTML (XML) subtitles, there is no need for additional conversion. Perhaps `xml` could be added to the file extension list, though.

**Comment by siddht1** [comment]
@nyuszika7h the  subtitle specified was actually an unformed ttml but the transcript tag might have failed to identify it anyways now its better as things can be handled that way too.Still  the reporter  warning   https://github.com/rg3/youtube-dl/blob/master/youtube_dl/postprocessor/ffmpeg.py#L581-L583  still means its a kind of fix rather being fully supported means there are chances ffmpeg returing 1 here.Still testing it anyways.

**Comment by remitamine** [comment]
google already serve `vtt` and `ttml` subtitles, there is no need for any kind of convertion(for now).

**Comment by siddht1** [comment]
@remitamine can you provide the link or the get request to do that.Seems everything is there but was just not parsed properly.My tests failed though.

**Comment by siddht1** [comment]
As per the given url,the subtitle are in location https://drive.google.com/timedtext?authuser\u003d0\u0026id\u003d0B0Pcx5-LUToEblNxcXRPWmtmS00\u0026vid\u003d851eb6773c9a6ff5 . This is the array of array which has the data ["ttsurl","https://drive.google.com/timedtext?authuser\u003d0\u0026id\u003d0B0Pcx5-LUToEblNxcXRPWmtmS00\u0026vid\u003d851eb6773c9a6ff5"].               youtube-dl  understands the file as track which was good.  youtube-dl https://drive.google.com/timedtext?authuser=0&id=0B0Pcx5-LUToEblNxcXRPWmtmS00&vid=851eb6773c9a6ff5&hl=en-US&v=0B0Pcx5-LUToEblNxcXRPWmtmS00&type=track&lang=hu&name&kind&fmt=1
[1] 15353
[2] 15354
[3] 15355
[4] 15356
[5] 15357
[6] 15358
[7] 15359
[8] 15360
[9] 15361
[2]   Done                    id=0B0Pcx5-LUToEblNxcXRPWmtmS00
[3]   Done                    vid=851eb6773c9a6ff5
[4]   Done                    hl=en-US
[5]   Done                    v=0B0Pcx5-LUToEblNxcXRPWmtmS00
[6]   Done                    type=track
[7]   Done                    lang=hu



anybody knows how to set type=track  to vtt,srt or anything

**Comment by remitamine** [comment]
vtt subtitle: https://drive.google.com/timedtext?vid=851eb6773c9a6ff5&v=0B0Pcx5-LUToEblNxcXRPWmtmS00&type=track&lang=hu&name&kind&fmt=vtt
english generated vtt subtitle: https://drive.google.com/timedtext?vid=851eb6773c9a6ff5&v=0B0Pcx5-LUToEblNxcXRPWmtmS00&type=track&lang=hu&name&kind&fmt=vtt&tlang=en
ttml subtitle: https://drive.google.com/timedtext?vid=851eb6773c9a6ff5&v=0B0Pcx5-LUToEblNxcXRPWmtmS00&type=track&lang=hu&name&kind&fmt=ttml
french generated ttml subtitle: https://drive.google.com/timedtext?vid=851eb6773c9a6ff5&v=0B0Pcx5-LUToEblNxcXRPWmtmS00&type=track&lang=hu&name&kind&fmt=ttml&tlang=fr

**Comment by parmjitv** [comment]
Thanks for the info everyone!  I will use the caption URLs already made available to us and see what happens.

What happened to @siddht1 - I no longer see his contributions in this thread?
