### ISSUE TITLE
auto integrate of youtube-dl on server

### ISSUE THREAD

**Issue by kiranbulley** [rg3/youtube-dl#13623]
i am developing a package to editing video and i need to integrate youtube-dl library with package installation. package developed in PHP. can we do auto integration of library on server

**Comment by siddht1** [comment]
this can be done simply calling exec function in php.   sample code :
 <?php
//$out=shell_exec("youtube-dl");
//$out=exec("youtube-dl -version");
//var_dump($out);
$url = 'https://www.youtube.com/watch?v=GMuZdN84PJg'; #any url 

//$url='-v';
$cmd = 'youtube-dl -o "/home/siddht1/div/tmp/%(id)s.%(ext)s" ' . escapeshellarg($url);
exec($cmd, $output, $ret);
echo 'output: ';
var_export($output);
echo "\nret: ";
var_export($ret);

print_r(shell_exec());
?> 


other projects based on similar ideas are https://github.com/labzone/Youtube-dl-php ,https://github.com/norkunas/youtube-dl-php.

**Comment by yan12125** [comment]
Thanks @siddht1. For further discussions, please move to #152.
