### ISSUE TITLE
Youtube-dl hangs during Cron or remote run

### ISSUE THREAD

**Issue by jackalblood** [rg3/youtube-dl#13627]
[Log]

System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-a', u'/home/user/webriplist.txt', u'-o', u'/home/user/Media/Webrips/%(title)s-%(id)s.%(ext)s']
[debug] Batch file urls: [u'http://roosterteeth.com/episode/rt-podcast-2017-podcast-439-post-show-wg94jg', u'http://achievementhunter.roosterteeth.com/episode/off-topic-the-achievement-hunter-podcast-2017-84-jgioyj', u'http://achievementhunter.roosterteeth.com/episode/off-topic-the-achievement-hunter-podcast-2017-last-call-84-diofg4', u'http://funhaus.roosterteeth.com/episode/gameplay-2017-syshack']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2017.07.02
[debug] Python version 2.7.12 - Linux-4.4.0-78-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg git-2017-05-18-e434840, ffprobe git-2017-05-18-e434840, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: unable to extract OpenGraph description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[Issue Report}

When running Youtube-dl i will run into this issue however this only occurs if the command is run remotely using ssh user@ip -p 22 /path/to/shscript.sh
or if the same script is run using crontab it will have the same error

however if i ssh into the server and then manually run the script with the same links the error will not occur so it only hangs if run by cron or as part of a ssh command from another server 

this has been happening for months and ive always been up to date ive tried install by pip and by ppa repo for Ubuntu 

if there is anymore info i can provide please just ask very happy to help fix this issue since the program when run manually is flawless

**Comment by jackalblood** [comment]
id like to but it comes up blank hence why i also replicated it using remote connection

**Comment by dstftw** [comment]
There is no difference running it locally or remotely. How do you even determine it "hangs", it may be just downloading videos.

**Comment by jackalblood** [comment]
because as you can see the error is at the end  of the debug log however if you run as the user directly it will complete the download 

so like ive shown above if i run  ssh user@ip -p 22 /path/to/youtubedl.sh ill get the error

but if i do 

ssh user@ip -p 22 (press enter)

/path/to/youtubedl.sh (press enter)

it completes just fine

**Comment by jackalblood** [comment]
Solved the issue by first invoking a screen on remote server then running the .sh script 

example 

screen -dmS (name) /path/to/script.sh
