### ISSUE TITLE
[ted] After June 22 2017 update, subtitles cannot be listed or downloaded

### ISSUE THREAD

**Issue by Martin-Laclaustra** [rg3/youtube-dl#13628]
## Please follow the guide below
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

On June 22 2017 TED video pages were [updated](http://blog.ted.com/an-updated-design-for-ted-talks/). [4917478](https://github.com/rg3/youtube-dl/commit/49174788035038b8f12f971ec04ef897df60f435) fixed video extraction, but subtitles cannot be listed or downloaded.

```
$ youtube-dl -v -s --list-subs https://www.ted.com/talks/nilofer_merchant_got_a_meeting_take_a_walk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-s', u'--list-subs', u'https://www.ted.com/talks/nilofer_merchant_got_a_meeting_take_a_walk']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.09
[debug] Git HEAD: c3c94ca
[debug] Python version 2.7.9 - Linux-4.4.38-v7+-armv7l-with-debian-8.0
[debug] exe versions: none
[debug] Proxy map: {}
[ted] nilofer_merchant_got_a_meeting_take_a_walk: Downloading webpage
[ted] nilofer_merchant_got_a_meeting_take_a_walk: Downloading m3u8 information
1726 has no subtitles
```
The example actually has 44 subtitles listed.

**Comment by 27himanshu** [comment]
This can be fixed with a minor change. The "languages" property is now nested under "downloads". I created a pull request for this #13629.

**Comment by Martin-Laclaustra** [comment]
Thank you! That was real fast! I works perfectly.
