### ISSUE TITLE
[Youtube] "token" parameter not in video info for unknown reason

### ISSUE THREAD

**Issue by N46AN** [rg3/youtube-dl#13631]
Hello, I use youtube-dl to download Youtube videos through a proxy https://github.com/XX-net/XX-Net
It used to work fine, but in recent months it has been dysfunctional:
```
$ youtube-dl --version                                                                                                  
2017.07.09

$ youtube-dl --proxy "127.0.0.1:8087" https://www.youtube.com/watch?v=hEnyvdvS6UQ
[youtube] hEnyvdvS6UQ: Downloading webpage
[youtube] hEnyvdvS6UQ: Downloading video info webpage
ERROR: hEnyvdvS6UQ: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Output of `youtube-dl --proxy "127.0.0.1:8087" -v --dump-pages https://www.youtube.com/watch?v=hEnyvdvS6UQ > dump 2>&1`: http://paste.debian.net/plain/975927

Some recent duplicate issues suggest that this is not a problem with XX-net: https://github.com/rg3/youtube-dl/issues/12753

**Comment by dstftw** [comment]
Obvious XX-Net issue:
```
> py -3.6 .\youtube_dl\__main__.py hEnyvdvS6UQ -F
[youtube] hEnyvdvS6UQ: Downloading webpage
[youtube] hEnyvdvS6UQ: Downloading video info webpage
[youtube] hEnyvdvS6UQ: Extracting video information
[youtube] hEnyvdvS6UQ: Downloading js player vflDXt52J
[youtube] hEnyvdvS6UQ: Downloading MPD manifest
[info] Available formats for hEnyvdvS6UQ:
format code  extension  resolution note
139          m4a        audio only DASH audio   48k , m4a_dash container, mp4a.40.5@ 48k (22050Hz), 1.08MiB
249          webm       audio only DASH audio   66k , opus @ 50k, 1.34MiB
250          webm       audio only DASH audio   96k , opus @ 70k, 1.90MiB
171          webm       audio only DASH audio  103k , vorbis@128k, 2.20MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k (44100Hz), 2.87MiB
251          webm       audio only DASH audio  200k , opus @160k, 4.35MiB
160          mp4        256x144    DASH video  112k , avc1.42c00c, 15fps, video only, 2.41MiB
133          mp4        426x240    DASH video  247k , avc1.4d4015, 30fps, video only, 5.52MiB
134          mp4        640x360    DASH video  385k , avc1.4d401e, 30fps, video only, 7.32MiB
135          mp4        854x480    DASH video  842k , avc1.4d401f, 30fps, video only, 15.78MiB
136          mp4        1280x720   DASH video 1833k , avc1.4d401f, 30fps, video only, 35.27MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
```

**Comment by HieronymusCH** [comment]
Same error with https://www.youtube.com/watch?v=jbkSRLYSojo

--- output with --verbose ---
$ youtube-dl --verbose https://www.youtube.com/watch?v=jbkSRLYSojo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=jbkSRLYSojo']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 3.7.3 (CPython) - Linux-5.0.0-14-lowlatency-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: avconv 4.1.1-1, avprobe 4.1.1-1, ffmpeg 4.1.1-1, ffprobe 4.1.1-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] jbkSRLYSojo: Downloading webpage
[youtube] jbkSRLYSojo: Downloading video info webpage
ERROR: jbkSRLYSojo: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1689, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: jbkSRLYSojo: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by rautamiekka** [comment]
> Same error with https://www.youtube.com/watch?v=jbkSRLYSojo
> 
> --- output with --verbose ---
> $ youtube-dl --verbose https://www.youtube.com/watch?v=jbkSRLYSojo
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=jbkSRLYSojo']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2019.01.17
> [debug] Python version 3.7.3 (CPython) - Linux-5.0.0-14-lowlatency-x86_64-with-Ubuntu-19.04-disco
> [debug] exe versions: avconv 4.1.1-1, avprobe 4.1.1-1, ffmpeg 4.1.1-1, ffprobe 4.1.1-1, phantomjs 2.1.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [youtube] jbkSRLYSojo: Downloading webpage
> [youtube] jbkSRLYSojo: Downloading video info webpage
> ERROR: jbkSRLYSojo: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
> File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
> ie_result = ie.extract(url)
> File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
> ie_result = self._real_extract(url)
> File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1689, in _real_extract
> video_id=video_id)
> youtube_dl.utils.ExtractorError: jbkSRLYSojo: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Old version !

Works fine:
```
C:\Users\jaervinen>\programdata\anaconda3\python K:\_DOWNLOADS_\youtube-dl.pyc --verbose "https://www.youtube.com/watch?v=jbkSRLYSojo"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=jbkSRLYSojo']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.7.2 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] jbkSRLYSojo: Downloading webpage
[youtube] jbkSRLYSojo: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r6---sn-qo5-ixas.googlevideo.com/videoplayback?id=o-AC_mA6LogpBElZyZaoR72lF-9xLvCujoD0gx59eMnghr&itag=43&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-qo5-ixas%2Csn-5goeen7k&ms=au%2Crdu&mv=m&pl=21&ei=_WnFXKr5JcS0yAXB9paACw&initcwndbps=948750&mime=video%2Fwebm&gir=yes&clen=23619864&ratebypass=yes&dur=0.000&lmt=1536635975010018&mt=1556441507&fvip=6&c=WEB&ip=176.93.196.187&ipbits=0&expire=1556463197&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&signature=A22DF986CEE0D086ABF0ED9BE29EB43F990D85C2.76BAE3DA6F00324E523C9C6DBD062B810298EB&key=yt8'
[download] Resuming download at byte 4193280
[download] Destination: Hans Rosling's 200 Countries, 200 Years, 4 Minutes - The Joy of Stats - BBC Four-jbkSRLYSojo.webm
[download] 100% of 22.53MiB in 00:03
```

**Comment by remitamine** [comment]
@HieronymusCH update youtube-dl.
