### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by Azulan** [rg3/youtube-dl#13643]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

youtube-dl.exe --no-mtime https://www.pornoeggs.com/watch?v=$whatever
[generic] watch?v=: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=: Downloading webpage
[generic] watch?v=: Extracting information
[generic] watch?v=: Downloading MPD manifest
ERROR: Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTT
PError()); please report this issue on https://yt-dl.org/bug . Make sure you are
 using the latest version; type  youtube-dl -U  to update. Be sure to call youtu
be-dl with the --verbose flag and include its complete output.

youtube-dl.exe -v --no-mtime https://www.pornoeggs.com/watch?v=
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-mtime', 'https://www.pornoeggs.com/watch
?v=']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.07.09
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-86723-g3b3501f, ffprobe N-86723-g3b3501f
[debug] Proxy map: {}
[generic] watch?v=: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=: Downloading webpage
[generic] watch?v=: Extracting information
[generic] watch?v=: Downloading MPD manifest
ERROR: Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTT
PError()); please report this issue on https://yt-dl.org/bug . Make sure you are
 using the latest version; type  youtube-dl -U  to update. Be sure to call youtu
be-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7cj3193h\bu
ild\youtube_dl\extractor\common.py", line 502, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7cj3193h\bu
ild\youtube_dl\YoutubeDL.py", line 2137, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt

youtube-dl.exe -v --no-mtime blob:https://www.pornoeggs.com/f4b
2dc41-d0a6-4c9c-8ed5-2f49f750f08a
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-mtime', 'blob:https://www.pornoeggs.com/
f4b2dc41-d0a6-4c9c-8ed5-2f49f750f08a']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.07.09
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-86723-g3b3501f, ffprobe N-86723-g3b3501f
[debug] Proxy map: {}
[generic] f4b2dc41-d0a6-4c9c-8ed5-2f49f750f08a: Requesting header
WARNING: Could not send HEAD request to blob:https://www.pornoeggs.com/f4b2dc41-
d0a6-4c9c-8ed5-2f49f750f08a: <urlopen error unknown url type: blob>
[generic] f4b2dc41-d0a6-4c9c-8ed5-2f49f750f08a: Downloading webpage
ERROR: Unable to download webpage: <urlopen error unknown url type: blob> (cause
d by URLError('unknown url type: blob',))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7cj3193h\bu
ild\youtube_dl\extractor\common.py", line 502, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7cj3193h\bu
ild\youtube_dl\YoutubeDL.py", line 2137, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 487, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 1253, in unknown_open

youtube-dl.exe -v --no-mtime https://vs8.userscontent.net/dash/
866962/manifest.mpd?seclink=7EVR00EQoaZd0PvtlHotBQ&amp;sectime=1499959761
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-mtime', 'https://vs8.userscontent.net/da
sh/866962/manifest.mpd?seclink=7EVR00EQoaZd0PvtlHotBQ']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.07.09
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-86723-g3b3501f, ffprobe N-86723-g3b3501f
[debug] Proxy map: {}
[generic] manifest: Requesting header
WARNING: Could not send HEAD request to https://vs8.userscontent.net/dash/866962
/manifest.mpd?seclink=7EVR00EQoaZd0PvtlHotBQ: HTTP Error 403: Forbidden
[generic] manifest: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7cj3193h\bu
ild\youtube_dl\extractor\common.py", line 502, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7cj3193h\bu
ild\youtube_dl\YoutubeDL.py", line 2137, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt

'amp' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Azulan** [comment]
Invalid why?

**Comment by siddht4** [comment]
@Azulan the first two links you provided are invalid.

 First one is infact a get request to the site.The rests are invalid too either they dont exist or they dont mean.

A valid url is still perceived by the general extractor but will fail as they are not completely formatted.

An lastly an extractor cannot be built as the site has dmca invokations
