### ISSUE TITLE
Feature request - Filter commands by site

### ISSUE THREAD

**Issue by sirylj** [rg3/youtube-dl#13648]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Feature request - Filter commands by site

A command line option filter that runs commands based on the site being used. e.g.

`--match-site youtube.com --output template`

would run any commands that come after it only if the site being used is youtube.com.

Multiple `--match-site` commands could be used to make templates for different sites (e.g. different `--output` commands for youtube.com and vimeo.com, etc.).

`--match-site unlisted`

would apply commands to sites not specifically listed by --match-site.

Support for any url structure.

Or add the same support options to `--match-filter`

**Comment by dstftw** [comment]
This is not how it's work. Explicit match site option does not make any sense since it's already filtered by input URL.

**Comment by sirylj** [comment]
It makes plenty of sense because there's a config file. Putting custom --output templates in the config file for different sites would make downloading videos a more streamlined process than having to change my --output configuration every time I download from a different url.
