### ISSUE TITLE
The version of youtube-dl in the Ubuntu repos is very outdated

### ISSUE THREAD

**Issue by aaronfranke** [rg3/youtube-dl#13649]
```
$ sudo apt install youtube-dl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
youtube-dl is already the newest version (2016.02.22-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
Ubuntu 16.04 LTS 64-bit

**Comment by dstftw** [comment]
Ask Ubuntu maintabners to update it.

**Comment by aaronfranke** [comment]
https://bugs.launchpad.net/ubuntu/+source/youtube-dl/+bug/1704368

**Comment by siddht4** [comment]
I am soon going to add the built directly to ppa i.e ppa:dhar-75-ap/youtube-dl. If you want to try  it before hand  feel free to go to https://github.com/siddht4/youtube_dl_deb

**Comment by aaronfranke** [comment]
Ubuntu bug: https://bugs.launchpad.net/ubuntu/+source/youtube-dl/+bug/1529647

**Comment by Asuanin** [comment]
Package in Ubuntu repo is again very outdated
Ubuntu repo version: 2018.03.14 (Web Upd8: 2018.04.03 (not bionic))
Lastest release: 2019.01.03.1

Have you been thinking over your own PPA repository?
With Jenkins for automated building (not only DEB packages) and Launchpad for PPA is very siply.

This is not a concern of the ubuntu team, please understand that thousands of packages can not check whether the new version of each one.

**Comment by Asuanin** [comment]
package in Ubuntu repo is again very outdated
Ubuntu repo: 2018.03.14 (bionic)
  (Web Upd8: 2018.04.03 (not bionic))
Latest release: 2019.01.30.1

Have you been thinking over your own PPA repository with unstable/latest releases?
With Jenkins for make builds (not only DEB) and Launchpad is very simply.

And witch release is current stable?
