### ISSUE TITLE
Despite 10222, TBS does not work

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#13658]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

TBS does not work.

```
keybounceMBP:TBS michael$ ./yt-dl -v http://www.tbs.com/shows/full-frontal-with-samantha-bee
[debug] System config: []
[debug] User config: ['-k', '--hls-prefer-native', '-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-f', '\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', '--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,enUS,en-us', '--sub-format', 'ass/srt/best', '--convert-subs', 'ass', '--embed-subs', '--mark-watched', '--download-archive', 'downloaded-videos.txt']
[debug] Custom config: []
[debug] Command-line args: ['--hls-prefer-native', '-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-v', 'http://www.tbs.com/shows/full-frontal-with-samantha-bee']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.15
[debug] Python version 3.6.1 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] full-frontal-with-samantha-bee: Requesting header
WARNING: Falling back on generic information extractor.
[generic] full-frontal-with-samantha-bee: Downloading webpage
[generic] full-frontal-with-samantha-bee: Extracting information
ERROR: Unsupported URL: http://www.tbs.com/shows/full-frontal-with-samantha-bee
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2944, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.tbs.com/shows/full-frontal-with-samantha-bee

keybounceMBP:TBS michael$ ./yt-dl -v http://www.tbs.com/shows/full-frontal-with-samantha-bee/season-2/episode-
13/june-28-2017
[debug] System config: []
[debug] User config: ['-k', '--hls-prefer-native', '-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-f', '\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', '--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,enUS,en-us', '--sub-format', 'ass/srt/best', '--convert-subs', 'ass', '--embed-subs', '--mark-watched', '--download-archive', 'downloaded-videos.txt']
[debug] Custom config: []
[debug] Command-line args: ['--hls-prefer-native', '-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-v', 'http://www.tbs.com/shows/full-frontal-with-samantha-bee/season-2/episode-13/june-28-2017']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.15
[debug] Python version 3.6.1 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] june-28-2017: Requesting header
WARNING: Falling back on generic information extractor.
[generic] june-28-2017: Downloading webpage
[generic] june-28-2017: Extracting information
ERROR: Unsupported URL: http://www.tbs.com/shows/full-frontal-with-samantha-bee/season-2/episode-13/june-28-2017
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2944, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.tbs.com/shows/full-frontal-with-samantha-bee/season-2/episode-13/june-28-2017

```

Playlists like http://www.tbs.com/shows/full-frontal-with-samantha-bee
Episodes like http://www.tbs.com/shows/full-frontal-with-samantha-bee/season-2/episode-13/june-28-2017

Note that issue #10222 was supposed to cover this.

**Comment by stinkteeth** [comment]
Is still working in prior version, although asks for adobe pass auth even for public episodes that don't require it.

**Comment by tv21** [comment]
stinkteeth, what version are you running?  I had an old copy of the 2017.03.15 version and tried that and got exactly the same error on a TNT link that I do with the most recent version.  They have made some kind of change on those sites, because I know someone who uses PlayOn and both of those channels stopped working for him at the same time they stopped working with youtube-dl.  I would be extremely surprised if any older version would work, but if it does I'd love to know which version and where you got it.

**Comment by stinkteeth** [comment]
@tv21 You're correct. It has been substantially changed.  The old system was hds (adobe access drm) on the desktop, and aes-hls on mobile/app platforms (using a different server).  The new system is hls on all platforms, with many flavors (3+) of hls drm, with a common server.  New media json urls replace the old  cvpXml system as well.  It will take a little bit of work to write a new extractor (for episodes) on all of the turner sites using the new system.  Short clips use the new media json system but a different server for video than the episodes. Sorry for the confusion, I hadn't checked it in awhile.

**Comment by remitamine** [comment]
> New media json urls replace the old cvpXml system as well

the old system is still available, so i think it can be used for now.
this is the xml url for the episode url posted in the issue:
http://www.tbs.com/service/cvpXml?titleId=2097655

> The new system is hls on all platforms, with many flavors (3+) of hls drm, with a common server.
It will take a little bit of work to write a new extractor (for episodes) on all of the turner sites using the new system.

if it's the case(without any workaround), then it won't be `little bit of work` in the future.

**Comment by stinkteeth** [comment]
@remitamine I will stand by my "little bit of work" claim for now, though I'm not necessarily volunteering to do the work. The platforms for the new json media urls (ngtv.io) are tv, desktop, phone, and tablet. In addition to the adobe, widevine and playready forms of hls, there is also aes hls. And not only that, the tv platform has 1080p aes hls, higher than the 720p limit of the old mobile/app server (androidhls-secure.cdn)!!! You're right, of course, that if aes goes away from the new system, then the bit of work won't be so little. Whether the old system stays or not, with w3c html5 drm looming, we're likely living in the end times of easy video extracting/downloading.

**Comment by keybounce** [comment]
And that alternative URL doesn't work

```
keybounceMBP:TBS michael$ ./yt-dl -v -a dl-list 
[debug] System config: []
[debug] User config: ['-k', '--hls-prefer-native', '-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-f', '\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', '--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,enUS,en-us', '--sub-format', 'ass/srt/best', '--convert-subs', 'ass', '--embed-subs', '--mark-watched', '--download-archive', 'downloaded-videos.txt']
[debug] Custom config: []
[debug] Command-line args: ['--hls-prefer-native', '-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-v', '-a', 'dl-list']
[debug] Batch file urls: ['http://www.tbs.com/service/cvpXml?titleId=2097655']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.15
[debug] Python version 3.6.1 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] cvpXml?titleId=2097655: Requesting header
WARNING: Falling back on generic information extractor.
[generic] cvpXml?titleId=2097655: Downloading webpage
[generic] cvpXml?titleId=2097655: Extracting information
ERROR: Unsupported URL: http://www.tbs.com/service/cvpXml?titleId=2097655
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2944, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.tbs.com/service/cvpXml?titleId=2097655

keybounceMBP:TBS michael$ 
```

**Comment by remitamine** [comment]
> And that alternative URL doesn't work

i didn't say that it can be used directly with youtube-dl command line, it's the url used to extract the information needed to download the video.

at least changing [this lines](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/tbs.py#L36-L42) to extract json in `script` tag with `data-drupal-selector="drupal-settings-json"` attribute than get the first element in `turner_playlist` than add using those information to add `titleId` param to the `query` variable, this should fix the extraction for episodes.

**Comment by keybounce** [comment]
Remitamine, can you please explain that? I did not understand it three weeks ago, still do not understand it, and even grabbing master just now still has the same issue.

**Comment by tv21** [comment]
I don't know if it makes any difference, or if you even have any way to find out what they did, but TBS and TNT were broken in PlayOn at the same time they stopped working in youtube-dl.  According to the release notes for PlayOn 4.3.49.20014 at https://www.playon.tv/releasenotes both channels are now fixed.  So there must be some way to make these work again, but I am not a programmer so I have no way of knowing how they fixed it.

**Comment by keybounce** [comment]
TBS is still not working.
Is this being worked on, or is it on the bottom of the pile?

**Comment by yuppicide** [comment]
Not working as well. Is there a way I can at least find out the video URL? Maybe I could download it another way.

**Comment by StevenDTX** [comment]
Thanks @remitamine. It works great!

Just a note:  You must use "--hls-prefer-native", otherwise, you only get the first segment.
