### ISSUE TITLE
[ADN] For some videos : "No Videos Format Found"

### ISSUE THREAD

**Issue by saint-seiya115** [rg3/youtube-dl#13662]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

![dc](https://user-images.githubusercontent.com/30212615/28247751-4575d918-6a37-11e7-9451-7b2852d77f3d.jpg)

---

### Description of your *issue*, suggested solution and other information

So, as I say in the title of this issue, some videos have an error when we try to get them.
Some other series than the one in he screenshot have the same problem.
Is it possible to solve this "bug" ?

Thank you!

**Comment by dstftw** [comment]
>Do not post screenshots of verbose logs; only plain text is acceptable.

**Comment by saint-seiya115** [comment]
I change the screen and put plain text, is it possible to re open it ?
