### ISSUE TITLE
Synchronize local folder with youtube channel

### ISSUE THREAD

**Issue by pprw** [rg3/youtube-dl#13665]
Youtube-dl allows to download in a very easy way youtube channel. But these ones don't stop uploading !

There should be a way to synchronize one local repository with one yt channel.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by pprw** [comment]
Like you like boxes:

- [x] Feature request 
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**

Nothing else is relevant in our template.

**Comment by dstftw** [comment]
>make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.

>But these ones don't stop uploading

youtube-dl does not upload anything.

>synchronize one local repository

What repository are you talking about?

Express your request in **understandable form**.

**Comment by pprw** [comment]
If you download a youtube channel, there are good chances there will be **new** videos after the download. My suggestion is to add an option in order to see if there are new videos on the channel, and, if yes, to download it.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#how-do-i-download-only-new-videos-from-a-playlist
