### ISSUE TITLE
periscope & pscp

### ISSUE THREAD

**Issue by orastes** [rg3/youtube-dl#13667]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**

- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

there are only 20 latest videos while getting playlist from periscope.tv even is contains more then 20

$ youtube-dl -v <your command line>
[debug] User config: [u'-o', u'%(uploader_id)s_%(id)s:%(title)s_%(upload_date)s_%(timestamp)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.pscp.tv/Natka_23_', u'--get-filename']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.15
[debug] Python version 2.7.13 - Linux-4.11.9-200.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five
[debug] exe versions: ffmpeg 3.1.9, ffprobe 3.1.9
[debug] Proxy map: {}
...
<end of log>
```

**Comment by orastes** [comment]
it seems to be that youtube-dl does not send any credentials to this server

**Comment by dstftw** [comment]
https://www.pscp.tv/Natka_23_ contains exactly 20 items all of which are processed.

**Comment by orastes** [comment]
sorry, but the playlist for that time contained 21 items
you can check playlist for https://www.pscp.tv/ThatsButta - it contains more then 100 items, but utility gets only 20

**Comment by 0880** [comment]
>https://www.pscp.tv/ThatsButta

I've checked the playlist. I count 20 videos and that's exactly what periscope shows in the header: `20 Live-Videos`

**Comment by orastes** [comment]
there are only 20 videos if user is not logged in, but there are much more when user logs in.
so, may be authentication is not working on periscope? 
there are no login strings in stdout, wheater I add --username and --password
