### ISSUE TITLE
[ADN] For some videos : "No Videos Format Found"

### ISSUE THREAD

**Issue by saint-seiya115** [rg3/youtube-dl#13663]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
```
D:\Téléchargements\Youtube-DL>youtube-dl -v http://animedigitalnetwork.fr/video/
detective-conan/6014-episode-761-kaga-hyakumangoku-mystery-tour-1re-partie-kanaz
awa
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://animedigitalnetwork.fr/video/detective
-conan/6014-episode-761-kaga-hyakumangoku-mystery-tour-1re-partie-kanazawa']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.07.15
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[ADN] 6014: Downloading webpage
[ADN] 6014: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\extractor\adn.py", line 136, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\extractor\common.py", line 1056, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

So, as I say in the title of this issue, some videos have an error when we try to get them.
Some other series than the one in he screenshot have the same problem.
Is it possible to solve this "bug" ?

Thank you!

**Comment by dstftw** [comment]
This video requires paid subscription that you did not provide to youtube-dl. Do that via `--cookies`.

**Comment by saint-seiya115** [comment]
Even with the cookies, i have still the same error. And I have a paid subscription account...
