### ISSUE TITLE
error [SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by fairbird** [rg3/youtube-dl#13678]
[ePicLoad] decode thread ... got quit msg
[eRCDeviceInputDev] 1 160 1
action ->  WizardActions ok
self.currList im KeyOK feedlist
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[gRC] main thread is non-idle! display spinner!
[youtube] 4qab3TMg42k: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))
W/  [VideoUrlRequest._request] :: ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))
Playing URL broken...
setSeekState
not pauseable.
evEOF=8
seekable status changed!
setSeekState
trying to switch to playing- state: 1
not pauseable.
playing 4097:0:0:0:0:0:0:0:0:0:broken...:The Disaster Artist | Official Teaser Trailer HD | A24
[eDVBCAService] free slot 0 demux 0 for service 1:0:1:5:1BC0:2BE:1040000:0:0:0:
[eDVBCAService] free service 1:0:1:5:1BC0:2BE:1040000:0:0:0:
[eDVBResourceManager] start release channel timer
[eTSMPEGDecoder] decoder state: play, vpid=ffffffff, apid=ffffffff

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by fairbird** [comment]
Sorry .. here is youtube-dl info ..

root@dm800se:~# youtube-dl -V
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3019, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3003, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 655, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 963, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 849, in resolve
pkg_resources.DistributionNotFound: The 'youtube-dl==2017.7.15' distribution was not found and is required by the application
root@dm800se:~#

I use it in Mytube plugin to Dreambox device ..
Thank you
