### ISSUE TITLE
[ITV] Hub not working

### ISSUE THREAD

**Issue by a-l-e-k** [rg3/youtube-dl#13671]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

- Single video: https://www.itv.com/hub/hand-of-god/2a4552

**description**
After recent changes on their site the download from ITV is no longer working.

**log**
```
youtube-dl.exe -v https://www.itv.com/hub/hand-of-god/2a4552a0001
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.itv.com/hub/hand-of-god/2a4552a0001']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.07.15
[debug] Python version 3.4.4
[debug] exe versions: ffmpeg N-67100-g6dc99fd, ffprobe N-67100-g6dc99fd, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 25.206.48.71 (GB) as X-Forwarded-For.
[ITV] 2a4552a0001: Downloading webpage
[ITV] 2a4552a0001: Downloading XML
ERROR: ITV said: No match found for production id: https://old-origin-api.itv.com/playlist/itvonline/ITV4/2_4552_0001.001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\build\youtube_dl\extractor\itv.py", line 107, in _real_extract
youtube_dl.utils.ExtractorError: ITV said: No match found for production id: https://old-origin-api.itv.com/playlist/itvonline/ITV4/2_4552_0001.001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
<end of log>
```

**Comment by john2069** [comment]
+1 Same issue on ITV - seems to be affecting all areas of ITV

``PS C:\bin\youtube-dl> C:\bin\youtube-dl\youtube-dl - Love Island.ps1
.\youtube-dl.exe : [debug] System config: []
At C:\bin\youtube-dl\youtube-dl - Love Island.ps1:3 char:9
+         .\youtube-dl.exe `
+         ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([debug] System config: []:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.itv.com/hub/love-island/2a3697a0125']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2017.07.15
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-80955-g5939878, ffprobe N-80955-g5939878, rtmpdump 2.3
[debug] Proxy map: {}
[debug] Using fake IP 25.41.194.247 (GB) as X-Forwarded-For.
[ITV] 2a3697a0125: Downloading webpage
[ITV] 2a3697a0125: Downloading XML
ERROR: ITV said: No match found for production id: https://old-origin-api.itv.com/playlist/itvonline/ITV2/2_3697_0125.001; please report this issue on 
https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its 
complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\build\youtube_dl\extractor\itv.py", line 107, in _real_extract
youtube_dl.utils.ExtractorError: ITV said: No match found for production id: https://old-origin-api.itv.com/playlist/itvonline/ITV2/2_3697_0125.001; please report this 
issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and 
include its complete output.``
