### ISSUE TITLE
Hangul not blocked in file output

### ISSUE THREAD

**Issue by DarrenS97** [rg3/youtube-dl#13675]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
cheek@DESKTOP-PE626D8 MINGW64 ~/Desktop
$ youtube-dl --encoding utf-8 -v https://www.youtube.com/watch?v=ru9r9JALEU8&t=2s
[1] 8528

cheek@DESKTOP-PE626D8 MINGW64 ~/Desktop
$ [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--encoding', 'utf-8', '-v', 'https://www.youtube.com/watch?v=ru9r9JALEU8']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref utf-8
[debug] youtube-dl version 2017.07.15
[debug] Python version 3.6.2 - Windows-10-10.0.15063-SP0
[debug] exe versions: ffmpeg N-86755-g0780ad9, ffprobe N-86755-g0780ad9
[debug] Proxy map: {}
[youtube] ru9r9JALEU8: Downloading webpage
[youtube] ru9r9JALEU8: Downloading video info webpage
[youtube] ru9r9JALEU8: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] ru9r9JALEU8: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r6---sn-cn3tc-ajte.googlevideo.com/videoplayback?id=aeef6bf4900b114f&itag=137&source=youtube&requiressl=yes&pl=39&mm=31&mn=sn-cn3tc-ajte&ms=au&mv=m&initcwndbps=1118750&ei=M29tWbvZMJSJW_i4ubgL&ratebypass=yes&mime=video/mp4&gir=yes&clen=69521798&lmt=1500023760892990&dur=199.666&key=dg_yt0&mt=1500343996&signature=8C1E8D8FD72057A5EFF5F72209D6B10D0351360A.0A75B7224BD458E827390CDE9B1560E4A1BF2C07&ip=2a02:c7f:3c00:d100:ad6b:eeff:fa6d:d0a1&ipbits=0&expire=1500365715&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mm,mn,ms,mv,initcwndbps,ei,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: 에디킴(Eddy Kim) '쿵쾅대' 라이브 LIVE _ 170714[이홍기의 키스 더 라디오]-ru9r9JALEU8.f137.mp4
[download] 100% of 66.30MiB in 00:15
[debug] Invoking downloader on 'https://r6---sn-cn3tc-ajte.googlevideo.com/videoplayback?key=yt6&mime=audio%2Fwebm&gir=yes&signature=1501CE1FDFE0D12849ED05E9434276D1DA2B6436.0EA982322CC6B9706CA36C7DCF328ABE78EC82A0&clen=3380452&expire=1500365715&dur=199.721&ipbits=0&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mv=m&mt=1500343996&ms=au&requiressl=yes&ip=2a02%3Ac7f%3A3c00%3Ad100%3Aad6b%3Aeeff%3Afa6d%3Ad0a1&mn=sn-cn3tc-ajte&mm=31&pl=39&id=o-AGS5B4N_bQI3hgyrsu4_frkWBGtabJf_gFvtDxiiFVFq&source=youtube&lmt=1500025438382406&initcwndbps=1118750&ei=M29tWbu_ENOjWsiAvSA&keepalive=yes&itag=251&ratebypass=yes'
[download] Destination: 에디킴(Eddy Kim) '쿵쾅대' 라이브 LIVE _ 170714[이홍기의 키스 더 라디오]-ru9r9JALEU8.f251.webm
[download] 100% of 3.22MiB in 00:00
[ffmpeg] Merging formats into "에디킴(Eddy Kim) '쿵쾅대' 라이브 LIVE _ 170714[이홍기의 키스 더 라디오]-ru9r9JALEU8.mkv"
[debug] ffmpeg command line: ffmpeg -y -i "file:에디킴(Eddy Kim) '쿵쾅대' 라이브 LIVE _ 170714[이홍기의 키스 더 라디오]-ru9r9JALEU8.f137.mp4" -i "file:에디킴(Eddy Kim) '쿵쾅대' 라이브 LIVE _ 170714[이홍기의 키스 더 라디오]-ru9r9JALEU8.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:에디킴(Eddy Kim) '쿵쾅대' 라이브 LIVE _ 170714[이홍기의 키스 더 라디오]-ru9r9JALEU8.temp.mkv"
Deleting original file 에디킴(Eddy Kim) '쿵쾅대' 라이브 LIVE _ 170714[이홍기의 키스 더 라디오]-ru9r9JALEU8.f137.mp4 (pass -k to keep)
Deleting original file 에디킴(Eddy Kim) '쿵쾅대' 라이브 LIVE _ 170714[이홍기의 키스 더 라디오]-ru9r9JALEU8.f251.webm (pass -k to keep)


...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

The output file name is correct however is not displayed properly since hangul should be blocked.

File name should look like it does below (As log+console showed)
에디킴(Eddy Kim) '쿵쾅대' 라이브 LIVE _ 170714[이홍기의 키스 더 라디오]-ru9r9JALEU8

However the actual output looks like this across Windows devices. 
ᄋ ᅦ ᄃ ᅵᄏ ᅵ ᆷ(Eddy Kim)  'ᄏ ᅮ ᆼᄏ ᅪ ᆼ 대라이브 LIVE _ 170714[이홍기의 키스 더 라디오]-ru9r9JALEU8.mkv

I have a few hundred files here, some are properly displayed in blocks, some are half and half, some are fully separated. [Some examples](https://i.gyazo.com/c30683577414422f3e34837522ce5e4e.png)

Files can be fixed by simply typing them out manually or copy-pasting from source.

**Comment by dstftw** [comment]
How it look in your Windows is completely unrelated to youtube-dl.
