### ISSUE TITLE
Selected Quality Udemy Download

### ISSUE THREAD

**Issue by attiqfsd** [rg3/youtube-dl#13672]
I want to download some udemy courses using youtube-dl but when I am trying to download them, some 3 minute videos are like 400MB in size.

I am assuming this is because the videos are being downloaded at the best quality possible. Is there a way to tell youtube-dl to download lower quality videos to save bandwidth?

I am using simple command to download

`youtube-dl -u EMAIL URL`

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#format-selection
