### ISSUE TITLE
Unable to download youtube video

### ISSUE THREAD

**Issue by virgilash** [rg3/youtube-dl#13682]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

c:\downloads>youtube-dl -v https://www.youtube.com/watch?v=Pk_0kftCQdA >debug_log.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=Pk_0kftCQdA']

[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2017.07.15
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-83280-gcba4f0e, ffprobe N-83280-gcba4f0e
[debug] Proxy map: {}
WARNING: Requested formats are incompatible for merge and will be merged into mk
v.
ERROR: unable to download video data: [Errno 22] Invalid argument: 'Turandot, li
ve from The Royal Opera House-Pk_0kftCQdA.f137.mp4.ytdl'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\YoutubeDL.py", line 1842, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\YoutubeDL.py", line 1790, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\downloader\dash.py", line 42, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\downloader\fragment.py", line 112, in _append_fragment
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\downloader\fragment.py", line 82, in _write_ytdl_file
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\utils.py", line 454, in sanitize_open
OSError: [Errno 22] Invalid argument: 'Turandot, live from The Royal Opera House
-Pk_0kftCQdA.f137.mp4.ytdl'
```

-

**Comment by Hrxn** [comment]
Can't reproduce.
```PowerShell
PS E:\Test> youtube-dl -U
youtube-dl is up-to-date (2017.07.15)
PS E:\Test> youtube-dl --ignore-config 'https://www.youtube.com/watch?v=Pk_0kftCQdA'
[youtube] Pk_0kftCQdA: Downloading webpage
[youtube] Pk_0kftCQdA: Downloading video info webpage
[youtube] Pk_0kftCQdA: Extracting video information
[youtube] Pk_0kftCQdA: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[dashsegments] Total fragments: 2562
[download] Destination: Turandot, live from The Royal Opera House-Pk_0kftCQdA.f137.mp4
[download]   0.5% of ~2.91GiB at  4.04MiB/s ETA 28:42
ERROR: Interrupted by user
PS E:\Test>
```

**Comment by Hrxn** [comment]
Write permission for this specific file system location?

**Comment by virgilash** [comment]
Oops, I forgot to mention: it doesn't happen right at the beginning, the download would start and fail a little later (at various points)

**Comment by dstftw** [comment]
```
> py -3.6 .\youtube_dl\__main__.py Pk_0kftCQdA  -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['Pk_0kftCQdA', '-v']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2017.07.15
[debug] Git HEAD: bb176df
[debug] Python version 3.6.0 - Windows-10-10.0.10240-SP0
[debug] exe versions: ffmpeg N-85653-gb4330a0, ffprobe N-85653-gb4330a0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Pk_0kftCQdA: Downloading webpage
[youtube] Pk_0kftCQdA: Downloading video info webpage
[youtube] Pk_0kftCQdA: Extracting video information
[youtube] Pk_0kftCQdA: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r1---sn-ug5onuxaxjvh-v8cl.googlevideo.com/videoplayback/id/3e4ff491fb4241d0/itag/137/source/youtube/requiressl/yes/gcr/ru/ei/7oVvWZykOM66YLvrjIgN/mn/sn-ug5onuxaxjvh-v8cl/initcwndbps/2067500/pl/20/mv/m/ms/au/mm/31/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/3724712492/lmt/1500305115633637/dur/13109.760/key/dg_yt0/signature/8385B64D60B4CA1D08216B2FED53A9E936D3B486.7B8E380C79BA2EFF76CA964E07837BE3696974C8/mt/1500480884/ip/109.171.17.81/ipbits/0/expire/1500502607/sparams/ip,ipbits,expire,id,itag,source,requiressl,gcr,ei,mn,initcwndbps,pl,mv,ms,mm,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 2562
[download] Destination: Turandot, live from The Royal Opera House-Pk_0kftCQdA.f137.mp4
[download] 100% of 3.47GiB in 34:22
[debug] Invoking downloader on 'https://r1---sn-ug5onuxaxjvh-v8cl.googlevideo.com/videoplayback?key=yt6&lmt=1500356383969798&dur=13109.801&initcwndbps=2067500&source=youtube&signature=A7D1C816A093E055F6B7AAF77E84437204F477BA.9340446CCAFB95FC4355AA08BD561D57047D0050&gir=yes&requiressl=yes&ipbits=0&id=o-ANJ5QeaImaEI-y5qbAUDWqT1ar-SPoV-67X0hntal8MS&gcr=ru&mn=sn-ug5onuxaxjvh-v8cl&mm=31&keepalive=yes&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ms=au&itag=251&ei=7oVvWbilDcnUYO-yutgF&mv=m&mt=1500480884&pl=20&mime=audio%2Fwebm&ip=109.171.17.81&clen=207794496&expire=1500502606&ratebypass=yes'
[download] Destination: Turandot, live from The Royal Opera House-Pk_0kftCQdA.f251.webm
[download] 100% of 198.17MiB in 00:22
[ffmpeg] Merging formats into "Turandot, live from The Royal Opera House-Pk_0kftCQdA.mkv"
[debug] ffmpeg command line: ffmpeg -y -i "file:Turandot, live from The Royal Opera House-Pk_0kftCQdA.f137.mp4" -i "file:Turandot, live from The Royal Opera House-Pk_0kftCQdA.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Turandot, live from The Royal Opera House-Pk_0kftCQdA.temp.mkv"
Deleting original file Turandot, live from The Royal Opera House-Pk_0kftCQdA.f137.mp4 (pass -k to keep)
Deleting original file Turandot, live from The Royal Opera House-Pk_0kftCQdA.f251.webm (pass -k to keep)
```
Post **complete** log.
