### ISSUE TITLE
Can't download youtube video - now with full log

### ISSUE THREAD

**Issue by virgilash** [rg3/youtube-dl#13684]
Full log this time, sorry for the previous post:

C:\Downloads>youtube-dl https://www.youtube.com/watch?v=Pk_0kftCQdA -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=Pk_0kftCQdA', '-v']

[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.07.15
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-83280-gcba4f0e, ffprobe N-83280-gcba4f0e
[debug] Proxy map: {}
[youtube] Pk_0kftCQdA: Downloading webpage
[youtube] Pk_0kftCQdA: Downloading video info webpage
[youtube] Pk_0kftCQdA: Extracting video information
[youtube] Pk_0kftCQdA: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mk
v.
[debug] Invoking downloader on 'https://r1---sn-ux3n588t-mjh6.googlevideo.com/vi
deoplayback/id/3e4ff491fb4241d0/itag/137/source/youtube/requiressl/yes/gcr/ca/in
itcwndbps/1635000/ei/7rVvWfa8NMrSDvSmgPAG/mm/31/mn/sn-ux3n588t-mjh6/pl/19/mv/m/m
s/au/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/3724712492/lmt/15003051
15633637/dur/13109.760/key/dg_yt0/signature/588428A4E2C870DFBF6B1DF1F61D524B35AD
1ACA.1013C866DDA665ABBB0893A331EC1440BBC3B712/mt/1500493222/ip/135.23.62.94/ipbi
ts/0/expire/1500514894/sparams/ip,ipbits,expire,id,itag,source,requiressl,gcr,in
itcwndbps,ei,mm,mn,pl,mv,ms,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 2562
[download] Destination: Turandot, live from The Royal Opera House-Pk_0kftCQdA.f1
37.mp4
[download]  36.7% of ~2.38GiB at  5.24MiB/s ETA 06:09          ERROR: unable to
download video data: [WinError 5] Access is denied: 'Turandot, live from The Roy
al Opera House-Pk_0kftCQdA.f137.mp4.part-Frag938'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\YoutubeDL.py", line 1842, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\YoutubeDL.py", line 1790, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\downloader\dash.py", line 42, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9jcmgxq0\bu
ild\youtube_dl\downloader\fragment.py", line 114, in _append_fragment
PermissionError: [WinError 5] Access is denied: 'Turandot, live from The Royal O
pera House-Pk_0kftCQdA.f137.mp4.part-Frag938'

C:\Downloads>

**Comment by dstftw** [comment]
>[WinError 5] Access is denied

The problem is most likely with your storage.
