### ISSUE TITLE
Feature Request: "--get-playlist-number"

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#13688]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

I want to select specific videos from a playlist. Said playlist includes videos I've already downloaded and will skip.

I want to be able to say "youtube-dl --get-filename --get-playlist-number playlist" (or something similar), so I know what numbers to pass to "youtube-dl --playlist-items 2,3,5,7,11" (or similar).

Is there any way to do something like this now?

**Comment by dstftw** [comment]
Why even bother with that? Just use `--download-archive`.

**Comment by keybounce** [comment]
Nope.

I am using --download-archive. (It's in the default config file for me).
Some videos in the playlist I have are of no interest to me.

I want to see what videos are in the playlist, and decide which to download.

If a video is in the playlist and in the download-archive list file, then it won't even be attempted, and I won't see a filename for it -- so if I am counting filenames, I won't have the right playlist index.

(Entirely separate, why am I not getting notices when a response to my posts here come in?)

**Comment by dstftw** [comment]
`--get-filename -o '%(playlist_index)s - %(title)s'`.

**Comment by keybounce** [comment]
Ohh, that should work nicely.

(and still no email notices of responses.)
