### ISSUE TITLE
Possible bug when downloading youku

### ISSUE THREAD

**Issue by xczheng** [rg3/youtube-dl#13692]
The video file was downloaded successfully, but some reason, the size of the file has been changing and the download was very slow. Can you see any problem down here?

youtube-dl -v "http://v.youku.com/v_show/id_XNTI2ODA3Nzky.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://v.youku.com/v_show/id_XNTI2ODA3Nzky.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.15
[debug] Python version 3.6.0 - Linux-3.2.61-grsec-modsign-x86_64-with-debian-wheezy-sid
[debug] exe versions: avconv 0.8.17-4, avprobe 0.8.17-4, ffmpeg 3.2.2-static, ffprobe 3.2.2-static
[debug] Proxy map: {}
[youku] XNTI2ODA3Nzky: Retrieving cna info
[youku] XNTI2ODA3Nzky: Downloading JSON metadata
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Invoking downloader on 'http://pl-ali.youku.com/playlist/m3u8?vid=XNTI2ODA3Nzky&type=flv&ups_client_netip=67.205.13.251&ups_ts=1500599945&utid=h0T4EY7a8TcCAUPNDfuuIPCa&ccode=0401&psid=7de2c08e688f7da8e94ba489f088b8ef&ckey=&duration=1748&expire=18000&ups_key=9f4ac3953e704338b8a74294ec68c013'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 173
[download] Destination: 第38话 没有日落的爱之岛-XNTI2ODA3Nzky.mp4
[download]  90.2% of ~102.07MiB at  1.21MiB/s ETA 00:40
[download]  91.0% of ~117.41MiB at 921.33KiB/s ETA 00:41
[download]  92.5% of ~117.41MiB at  1.35MiB/s ETA 00:34
[download]  90.4% of ~120.34MiB at 235.25KiB/s ETA 00:44
[download]  91.1% of ~120.34MiB at 458.01KiB/s ETA 00:41
[download]  93.1% of ~120.34MiB at 1007.24KiB/s ETA 00:31
[download] 100% of 131.30MiB in 08:48
[debug] avconv command line: avprobe -show_streams 'file:第38话 没有日落的爱之岛-XNTI2ODA3Nzky.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "第38话 没有日落的爱之岛-XNTI2ODA3Nzky.mp4"
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
[debug] ffmpeg command line: avconv -y -i 'file:第38话 没有日落的爱之岛-XNTI2ODA3Nzky.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:第38话 没有日落的爱之岛-XNTI2ODA3Nzky.temp.mp4'

**Comment by dstftw** [comment]
This is expected.
