### ISSUE TITLE
Problems with NicoVideo

### ISSUE THREAD

**Issue by antonio8909** [rg3/youtube-dl#13696]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.nicovideo.jp/watch/1490345969', '-u', 'PRIVATE', '-p', 'PRIVATE', '-p', '45.77.9.108', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.04.17
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg 3.2.4
[debug] Proxy map: {}
[niconico] Logging in
[niconico] 1490345969: Downloading webpage
[niconico] 1490345969: Downloading video info page
[niconico] 1490345969: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\build\youtube_dl\extractor\niconico.py", line 144, in _real_extract
youtube_dl.utils.ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---
### Description of your *issue*, suggested solution and other information

I tried to download a video from NicoVideo but it's unable to find video file.

**Comment by yan12125** [comment]
In Firefox NicoNico says:
```
Unable to play video.

This video is not available in your country.
```
Which country are you in?

**Comment by antonio8909** [comment]
@yan12125 I tried from almost all countries and I can't still access to the video. In Spain it says that it's geoblocked but if I connect with a Japanese Proxy it says 
[niconico] 1490345969: Downloading flv info
ERROR: Unable to find video URL

**Comment by yan12125** [comment]
I guess the video is broken and no one can access it. If you know a way to get the video working (in browsers, other downloaders, etc.), feel free to leave a comment below and I'll reopen this ticket.

**Comment by antonio8909** [comment]
I dont think the video is broken...

**Comment by yan12125** [comment]
Can you watch the video in browsers with a Japan proxy?

**Comment by siddht4** [comment]
it works an account is needed but oauth is supported.
![screenshot from 2017-07-23 20-47-31](https://user-images.githubusercontent.com/15411956/28500568-31e02992-6fe8-11e7-8625-617b90109f3c.png)

**Comment by yan12125** [comment]
After finding a working Japan proxy and choose Japanese as the language and Japan as the region on its website, I got this:
![default](https://user-images.githubusercontent.com/1937689/28500792-61068766-7001-11e7-930e-89dd6bfb13a4.png)
The highlighted text is:
```
この動画は有料です
```
Google translate says:
```
This video is charged
```
Yes it's not broken but requires an account that has paid. @antonio8909 Did you use a correct account?

**Comment by siddht4** [comment]
yes same here, they are using    `

try {
--
  | window.NicoGoogleTagManagerDataLayer = [];
  |  
  | var data = {};
  |  
  | data.user = (function() {
  | var user = {};
  |  
  | user.user_id = parseInt('', 10) \|\| null;
  | user.login_status = 'login';
  | user.member_status = 'normal';
  | user.birthday = '';
  | user.sex = 'male';
  | user.country = 'Japan';
  | user.prefecture = '神奈川県';
  | user.ui_area = 'tw';
  | user.ui_lang = 'en-us';
  |  
  |  
  | return user;
  | })();
  |  
  | window.NicoGoogleTagManagerDataLayer.push(data);
  | } catch(e) {}

`

this javascript + the actual ip to detect it.   paid account needed too.

**Comment by antonio8909** [comment]
If they need a paid account, why is the player working and you can see the seconds passing?

**Comment by siddht4** [comment]
> If they need a paid account, why is the player working

@antonio8909  that video is chargeable, the player isn`t initialized its just its thumbnail shown.Every video site does that gernerate some screenshot from the video and is shown.

> you can see the seconds passing

its to let you 100 % make sure the video is loaded,if it fails exception would arise and then its a developer faults.It also says just pay the amount and watch the video as soon as payment is verified,no more delays,no need to generate url or seesion for the particular video,

**Comment by antonio8909** [comment]
It's rare that they let you see seconds passing and no the video. It's so strange.
I'll keep searching for more info

**Comment by Poupsika** [comment]
Hello
I have the same problem for a serie on nicovideo. I even paid for a monthly account this morning, yet it keeps saying the video is not available in your country
