### ISSUE TITLE
[aliexpress] (direct) site support request

### ISSUE THREAD

**Issue by 2011** [rg3/youtube-dl#13698]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
$ youtube-dl -v 'https://live.aliexpress.com/live/2800002758010370'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', 'https://live.aliexpress.com/live/2800002758010370']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.15
[debug] Python version 3.4.5 - Linux-4.4.39-gentoo-x86_64-Intel-R-_Core-TM-_i5_CPU_750_@_2.67GHz-with-gentoo-2.3
[debug] exe versions: ffmpeg 2.8.10, ffprobe 2.8.10, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 2800002758010370: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2800002758010370: Downloading webpage
[generic] 2800002758010370: Extracting information
ERROR: Unsupported URL: https://live.aliexpress.com/live/2800002758010370
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/generic.py", line 2915, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://live.aliexpress.com/live/2800002758010370
...
<end of log>
```

Probably a strange site request (though I am certain you have seen stranger. :)

I am actually a bit surprised that this doesn't work with the "generic" extractor.

Anyway, select a video of interest from:

https://live.aliexpress.com/activite/highlight.htm

Download fails (as shown above), but source contains a line (for example):

"replyStreamUrl": "http://aelive.alicdn.com/ae/2800002758010370_t/1500454854529.m3u8",

Running youtube-dl on THAT URL works, so most of the infrastructure for this site is already present. It is just a question of extracting the URL (and otherl listed parameters such as title and date, which are useful in creating the output file), and using that information to download the video.

**Comment by dubber0** [comment]
I have written an extractor which solves your problem (#13707).
