### ISSUE TITLE
Download videos before or after "date uploaded"

### ISSUE THREAD

**Issue by Jimmm** [rg3/youtube-dl#137]
For Example:
youtube-dl -datebefore 20110804 “http://www.youtube.com/watch?v=foobar”
download this video, if it was uploaded before the 4th of Aug 2011
or
youtube-dl -dateafter 20110804 “http://www.youtube.com/watch?v=foobar”
or
youtube-dl -date 20110804 “http://www.youtube.com/watch?v=foobar”

It will be very handy for my playlist downloads. I rename my videos and youtube-dl downloads them one more time. Date filter will solve my problem.

Thanks for your attention.

**Comment by tommcintyre** [comment]
+1

Also issues should stay open if they're legit, just assign to a _backlog label or something?
