### ISSUE TITLE
Extract audio in PHP

### ISSUE THREAD

**Issue by bsytefu** [rg3/youtube-dl#13705]
Hello, when i use --extract-audio --audio-format mp3, the extensionof downloaded file is .webm always. 
In terminal work's fine.Extract MP3, but in PHP not working.

Code: `<?php echo exec("youtube-dl --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=VIDEO_ID "); ?>`

THANK YOU.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
