### ISSUE TITLE
ERROR: AtomicParsley was not found. Please install.

### ISSUE THREAD

**Issue by jaytaylor** [rg3/youtube-dl#13708]
### Question

When downloading a list of tubes, I was greeted with:

```
ERROR: AtomicParsley was not found. Please install.
```

OS: Windows 10

I tried `choco install atomicparsley`, to no avail.  Eventually was able to dig up a DL link for the app:

https://bitbucket.org/jonhedgerows/atomicparsley/downloads/

Would a PR to have this link included be accepted?

Thanks for making YTDL so nice!

**Comment by dstftw** [comment]
Included to where?

**Comment by jaytaylor** [comment]
To the bitbucket site for windows downloads.

**Comment by dstftw** [comment]
No. First hit for AtomicParsley in google contains official Windows builds that is trivial to find.
