### ISSUE TITLE
"dateafter" flag should affect page download

### ISSUE THREAD

**Issue by lgrn** [rg3/youtube-dl#13700]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Feature request (request for a new functionality)

```
$ youtube-dl -v --dateafter 20170721 https://www.youtube.com/user/PewDiePie/videos         
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--dateafter', u'20170721', u'https://www.youtube.com/user/PewDiePie/videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.15
[debug] Python version 2.7.12 - Linux-4.8.0-58-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:user] PewDiePie: Downloading channel page
[youtube:playlist] UU-lHJZR3Gqxm24_Vd_AJ5Yw: Downloading webpage
[download] Downloading playlist: Uploads from PewDiePie
[youtube:playlist] UU-lHJZR3Gqxm24_Vd_AJ5Yw: Downloading page #1
[youtube:playlist] UU-lHJZR3Gqxm24_Vd_AJ5Yw: Downloading page #2
[youtube:playlist] UU-lHJZR3Gqxm24_Vd_AJ5Yw: Downloading page #3
(...)
```
**Output note**: This should match nothing. There are no new uploads after 20170721.

### "dateafter" flag should affect page download

Currently when running `youtube-dl` with the `dateafter` flag, as you can see from the above output, it seems that `youtube-dl` completely ignores whatever you put in as the date as far as the "Downloading page" process is concerned.

Since the page is sorted chronologically, the logic should go like this:

* Inspect `dateafter` flag given by user
* Download `page #1` *only*.
* If `dateafter` does not match anything, abort.
* Else, continue as normal.

This is not the best way to do it of course, it would be better to run the process once for every page and check when you reach a page that doesn't have 100% videos that should be downloaded (this is the last page), so that just the right amount of pages are fetched. At least with the above way, which may be easier to implement, you can avoid the currently very annoying behavior where `youtube-dl` fetches every page of a channel (potentially *a lot*) only to to conclude that zero videos matched your date filter.

This issue is similar to #1846 and #1816 but it's not identical.

**Comment by lgrn** [comment]
@dstftw duplicate of what issue?

**Comment by sicode** [comment]
Agree, wasted Time

![image](https://user-images.githubusercontent.com/3986116/58001355-cddb3f80-7b0d-11e9-9d74-afe734896ee8.png)
