### ISSUE TITLE
Subtitle support for TG4 (tg4.ie) site

### ISSUE THREAD

**Issue by andyrozman** [rg3/youtube-dl#13718]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

There is one similar issue, but its for general support of TG4, which works for at least 8 months now. But subtitle doesn't work anymore

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)

---

As far as I can tell TG4 site is supported and it's been for at least 10 months... During my use with this site, I could also download subtitles, but this is not possible anymore... 

I am not sure if the site changed or if application changed since I last used it (I used it with this site on at end of last year (before new year 2017)).

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by andyrozman** [comment]
I added link for sample download...

**Comment by dstftw** [comment]
```
PS C:\dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py 'http://www.tg4.ie/en/player/home/?pid=5416347428001&teideal=Garfield&series=Garfield&dlft=NaN' --write-su
b
[generic] ?pid=5416347428001&teideal=Garfield&series=Garfield&dlft=NaN: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?pid=5416347428001&teideal=Garfield&series=Garfield&dlft=NaN: Downloading webpage
[generic] ?pid=5416347428001&teideal=Garfield&series=Garfield&dlft=NaN: Extracting information
[download] Downloading playlist: Garfield | Baile | Seinnteoir | TG4
[generic] playlist Garfield | Baile | Seinnteoir | TG4: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5416347428001: Downloading webpage
[brightcove:new] 5416347428001: Downloading JSON metadata
[brightcove:new] 5416347428001: Downloading m3u8 information
[info] Writing video subtitles to: Garfield 4 - 36 Adventures on Aruba Island _ Eachtraí ar Oileán Aruba-5416347428001.ga.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 81
[download] Destination: Garfield 4 - 36 Adventures on Aruba Island _ Eachtraí ar Oileán Aruba-5416347428001.mp4
[download]   1.2% of ~288.82MiB at  1.40MiB/s ETA 04:11
ERROR: Interrupted by user
```
>[info] Writing video subtitles to: Garfield 4 - 36 Adventures on Aruba Island _ Eachtraí ar Oileán Aruba-5416347428001.ga.vtt

**Comment by andyrozman** [comment]
Like I said main download works, but it doesn't download subtitle anymore... 

At end of the process you should have two files there:
Garfield 4 - 36 Adventures on Aruba Island _ Eachtraí ar Oileán Aruba-5416347428001.mp4
Garfield 4 - 36 Adventures on Aruba Island _ Eachtraí ar Oileán Aruba-5416347428001.ga.vtt

**Comment by dstftw** [comment]
`Garfield 4 - 36 Adventures on Aruba Island _ Eachtraí ar Oileán Aruba-5416347428001.ga.vtt` is the subtitles.
