### ISSUE TITLE
[request] --items-reverse besides --playlist--reverse

### ISSUE THREAD

**Issue by user1508** [rg3/youtube-dl#13716]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Hello,
first of all I know there are issues related to this. Sometimes I want to download the oldest video of an youtube playlist or the second last. The problem on youtube is the oldest has the highest number and it changed every time a new video was added to the playlist. Checking the numbers on youtube himself is sometimes a little bit annoying especially you use youtube-dl in some shell scripts or aliases. It would be cool if I could use something like youtube-dl --items-reverse --playlist-items 1 for getting the oldest video of the playlist.

Thanks and bye.

**Comment by dstftw** [comment]
`--playlist-reverse`.
