### ISSUE TITLE
Run youtube-dl with a different Python installation than my macOS' default python?

### ISSUE THREAD

**Issue by SuperHenkie** [rg3/youtube-dl#13724]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Question

I want (or rather, need) to run youtube-dl with a newer Python version. When checking my current Python version:

`python --version` says `2.7.10`
whereas 
`brew info python` says: `python: stable 2.7.13 (bottled), HEAD`

From many different resources I see a strong recommendation NOT to mess with my main macOS' python version, but instead install a second version separately. Which I apparently have done with brew already. 

**Question:** how do I let youtube-dl use the more recent Python version that is installed through Homebrew, in my case v2.7.13 which resides in `/usr/local/Cellar/python/2.7.13_1` ?
(as opposed to the macOS default older python installation which is in `/usr/bin/python`)

Can I somehow configure youtube-dl to use the other Python?

**Comment by yan12125** [comment]
A possible way is adding an alias to ```.bashrc```/```.zshrc```/...
```Bash
alias youtube-dl="/path/to/new/python /path/to/youtube-dl"
```
