### ISSUE TITLE
[Youtube] youtube-dl crash on unexpected character in video title

### ISSUE THREAD

**Issue by Fullmetal5** [rg3/youtube-dl#13723]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ #Just so people know I didn't just check off the box without looking
$ ./youtube-dl --version
2017.07.23
$ ./youtube-dl -v https://www.youtube.com/watch?v=Md1jEnCsQyQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=Md1jEnCsQyQ']
[debug] Encodings: locale ISO-8859-1, fs iso8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2017.07.23
[debug] Python version 3.4.5 - Linux-4.13.0-rc1+-x86_64-Intel-R-_Core-TM-_i7-4790K_CPU_@_4.00GHz-with-gentoo-2.3
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[youtube] Md1jEnCsQyQ: Downloading webpage
[youtube] Md1jEnCsQyQ: Downloading video info webpage
[youtube] Md1jEnCsQyQ: Extracting video information
[youtube] Md1jEnCsQyQ: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1956, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 841, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1599, in process_video_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1846, in process_info
  File "/usr/lib/python-exec/python3.4/../../../lib64/python3.4/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2665' in position 16: ordinal not in range(256)
```

### Description of your *issue*, suggested solution and other information

Well just by looking at the title of the video something should jump out at you "Foozogz - HEARTS♥RMX"

So I'm going to go out on a limb and say that it's probably crashing over this thing ♥
However that is but a guess.

I feel bad leaving the description this short but I think everything kinda speaks for itself.

**Comment by yan12125** [comment]
Yep ISO-8859-1 can't handle ♥. Either use another locale (ex: ```export LC_ALL=en_US.UTF-8```) or add ```--restrict-filenames``` to youtube-dl.

**Comment by Fullmetal5** [comment]
Thanks for letting me know. I just assumed that if youtube-dl was crashing it was a bug.
