### ISSUE TITLE
Tumblr defaults to tumblr-500.mp4 instead of 12-digit-post.url

### ISSUE THREAD

**Issue by teamspoad** [rg3/youtube-dl#13728]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Problem:  tumblr extractor returns id:tumblr, title:500 (or other 3 digit number).

I have spent days.  Can't get tumblr videos to save as the common (12 digit) post number.

videos always succesfully download
They all default to tumblr-500.mp4

I would like to have there unique 12 digit post number i.e. 123412341234.mp4
URL always looks like : http(s)://random.tumblr.com/video/123412341234/500

I have tried with regex [/d]{/12} in several ways to tumblr.py and to a new .py from your faq
I am NOT a coder.

Thanks a mil

**Comment by Hrxn** [comment]
Post full log with `-v` please..

**Comment by Hrxn** [comment]
I think this can be closed..
