### ISSUE TITLE
Regression with --get-url due to new format selection algorithm

### ISSUE THREAD

**Issue by anisse** [rg3/youtube-dl#13726]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Good log (before 0017d9ad6de831384e74db14a821e4c94020c9ac ):

```
$ ./bin/youtube-dl --verbose --get-url  https://www.youtube.com/watch?v=JAE6kFLOdF0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--get-url', u'https://www.youtube.com/watch?v=JAE6kFLOdF0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.15
[debug] Git HEAD: 327c836
[debug] Python version 2.7.9 - Linux-4.9.28-v7+-armv7l-with-debian-8.0
[debug] exe versions: none
[debug] Proxy map: {}
https://r2---sn-4gxx-25ge7.googlevideo.com/videoplayback?mm=31&ei=z7R1Wd22FsP5cOiJiIAO&lmt=1495888634553949&ip=2a01%MYIPWASHERE&expire=1500907823&id=o-AFWALLvegjMoZYBihbTFSAxtNwzXLAS4A0vyiBm4yu33&nh=EAE&initcwndbps=998750&source=youtube&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&pl=39&requiressl=yes&ratebypass=yes&ipbits=0&mime=video%2Fmp4&mn=sn-4gxx-25ge7&signature=775BB3BE292F6987DD6DF3F383F08F0EDD3C6124.A8EADB451CC0D898D5DC35B09DA93F266E2A36CB&key=yt6&itag=22&mv=m&mt=1500886179&ms=au&dur=3718.397
```
Log after 0017d9ad6de831384e74db14a821e4c94020c9ac : 
```
$ ./bin/youtube-dl --verbose --get-url  https://www.youtube.com/watch?v=JAE6kFLOdF0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--get-url', u'https://www.youtube.com/watch?v=JAE6kFLOdF0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.23
[debug] Git HEAD: c99d689
[debug] Python version 2.7.9 - Linux-4.9.28-v7+-armv7l-with-debian-8.0
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
https://r2---sn-4gxx-25ge7.googlevideo.com/videoplayback/id/24013a9052ce745d/itag/299/source/youtube/requiressl/yes/ei/YbR1WfjEFMKDcLPBj-AE/mm/31/mv/m/initcwndbps/1012500/ms/au/pl/39/nh/EAE/mn/sn-4gxx-25ge7/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/2397945816/lmt/1495887139266198/dur/3718.347/mt/1500885999/signature/56B20FD3807CC5F81D1F405115465E95372655AB.767E3E3F0A5B2E53212CB670A5834DAB3DD97215/key/dg_yt0/ip/2a01:MYIPWASHERE/ipbits/0/expire/1500907713/sparams/ip,ipbits,expire,id,itag,source,requiressl,ei,mm,mv,initcwndbps,ms,pl,nh,mn,ratebypass,mime,otfp,gir,clen,lmt,dur/
https://r2---sn-4gxx-25gel.googlevideo.com/videoplayback?expire=1500907712&initcwndbps=998750&mt=1500885999&signature=35DE2D0339FCA7E7446F540C297BE10709D8BCF1.32BAAD0C4F1AD2360243EA6D4B9AEDEDDD50D5A8&mime=audio%2Fwebm&nh=EAE&requiressl=yes&keepalive=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cexpire&ipbits=0&mv=m&source=youtube&ms=au&lmt=1495894757750887&key=yt6&ip=2a01%ASWELLASHERE&mn=sn-4gxx-25gel&mm=31&dur=3718.341&id=o-AN9nHeRCY-TSGIikJAnkYa9PlU6cyE5hENL1f0wLKK_Z&gir=yes&clen=50739574&itag=251&ei=YLR1WfuGNMSzcM2Cm4gH&pl=39&ratebypass=yes
```
---

### Description of your *issue*, suggested solution and other information

Ever since 0017d9ad6de831384e74db14a821e4c94020c9ac, the way --get-url works has changed. Before, it just showed a single URL, and youtube-dl would use that URL to do the download. Now it shows two different URLS (which I'm guessing are the video+audio streams), but youtube-dl still uses the old URL to do the download. ping @dstftw

**Comment by solatis** [comment]
Confirmed, this bug just hit us in production. We worked around it by selecting `-f best`.

**Comment by dstftw** [comment]
This is expected behavior.

**Comment by anisse** [comment]
@dstftw : this is weird because by default youtube-dl still does the download using the old URL, not the two URLs it prints. Is it because there's not ffmpeg installed ?

**Comment by dstftw** [comment]
Yes.

**Comment by anisse** [comment]
Cool. I'm OK with this being the new default, but maybe the docs should be updated to explain the new behaviour ?

**Comment by solatis** [comment]
It might be important to note that `--get-file` also differs from what it downloads by default.
