### ISSUE TITLE
Unable to download JSON metadata: HTTP Error 403: Forbidden [pluralsight]

### ISSUE THREAD

**Issue by jedz09** [rg3/youtube-dl#13735]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

C:\Users\oTaKuGeRi\Desktop\Youtube-dl>youtube-dl -v https://www.pluralsight.com/courses/networking-comptia-a-plus-220-901
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.pluralsight.com/courses/networking-comptia-a-plus-220-901']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.07.23
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] networking-comptia-a-plus-220-901: Downloading course JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\extractor\common.py", line 502, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 2166, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

C:\Users\oTaKuGeRi\Desktop\Youtube-dl>youtube-dl -U
youtube-dl is up-to-date (2017.07.23)

C:\Users\oTaKuGeRi\Desktop\Youtube-dl>python
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by jedz09** [comment]
For some reason I can't login to Pluralsight Offline app as well and getting "Error Occurred", however I can login to web with no problem.

UPDATE: I was able to download properly now after using a VPN connection (Hotspot VPN) as well as login to offline app, I will be closing this ticket for now.

**Comment by acardosome** [comment]
Probably implemented the CAPTCHA to access via JSON, since you do not have access to the dialog it refuses access.

**Comment by jedz09** [comment]
Yes, the problem all started after I got the CAPTCHA page prior to accessing the my Pluralsight Dashbpard, I tried doing the https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl, but it never work for me.

Checked https://github.com/rg3/youtube-dl/issues/154 and so far no update on it since 2015 

After a week since I encountered the problem, somehow I can access/download again and the CAPTCHA page is now gone.

**Comment by VarunVachis** [comment]
> Probably implemented the CAPTCHA to access via JSON, since you do not have access to the dialog it refuses access.

Thats true..How do i resolve this?
