### ISSUE TITLE
HLS streams and deduplication 

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#13736]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

Dear maintainer, 
Thank you for maintaining youtube-dl. The only issue I face quite a few times is that the same video gets downloaded number of times. Shouldn't youtube-dl when downloading a video, parse the directory to see if the same video is there in the same directory or not and if it is, then show it as complete

**Comment by dstftw** [comment]
>youtube-dl when downloading a video, parse the directory to see if the same video is there in the same directory or not and if it is

This is what youtube-dl actually does.
