### ISSUE TITLE
-g command give wrong link on linux only (works on windows)

### ISSUE THREAD

**Issue by BALIST0N** [rg3/youtube-dl#13746]
### What is the purpose of your *issue*?

--> Bug report (encountered problems with youtube-dl)

---

### Description of your *issue*, suggested solution and other information ###

hello, i found a bug on the Linux version (up to date : 2017.07.23)
with the command " -g - f 140 [link...]"  it give wrong link because when i copy and paste result it send me an error 403 page, 

i try it the same command on Windows version (latest version) and it work and give good link 

for example : 

Linux version  : " youtube-dl -g -f 140 https://www.youtube.com/watch?v=AhrYTl740jg " 
give link : [https://r3---sn-upoxu-25gs.googlevideo.com/videoplayback?id=021ad84e5ef8d238&itag=140&-[...]](https://r3---sn-upoxu-25gs.googlevideo.com/videoplayback?id=021ad84e5ef8d238&itag=140&source=youtube&requiressl=yes&mm=31&mv=m&pl=23&initcwndbps=1722500&ms=au&ei=LfJ4WcT3OIiBV-DAkNgP&gcr=ua&mn=sn-upoxu-25gs&ratebypass=yes&mime=audio/mp4&gir=yes&clen=2424020&lmt=1500475203862579&dur=152.578&key=dg_yt0&signature=097C60C400B79730D575A5572CF4A6652DC55783.4F6FC2F79F22429CDEC1FBF3806A51CF2DFF2968&mt=1501098438&beids=[9466594]&ip=173.199.70.110&ipbits=0&expire=1501120142&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mv,pl,initcwndbps,ms,ei,gcr,mn,ratebypass,mime,gir,clen,lmt,dur
)

Windows Version :" youtube-dl.exe -g -f 140 https://www.youtube.com/watch?v=AhrYTl740jg "
give link : [https://r6---sn-25ge7nse.googlevideo.com/videoplayback?id=021ad84e5ef8d238&itag=140&[...]](https://r3---sn-25g7sn76.googlevideo.com/videoplayback?id=021ad84e5ef8d238&itag=140&source=youtube&requiressl=yes&initcwndbps=1222500&mm=31&mn=sn-25g7sn76&mv=m&ms=au&ei=FvJ4WdPRC4vCc92EhrgG&pl=16&gcr=fr&ratebypass=yes&mime=audio/mp4&gir=yes&clen=2424020&lmt=1500475203862579&dur=152.578&mt=1501098438&signature=915BF17AD3999308D2828784E7CE4E73BA234D4B.61034CB19CA609E8E38154E0AC642E32E8DB08A1&key=dg_yt0&ip=176.133.118.253&ipbits=0&expire=1501120118&sparams=ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,mm,mn,mv,ms,ei,pl,gcr,ratebypass,mime,gir,clen,lmt,dur)

seems like soft pick the wrong server, or old server

BUT, this is weird because its only happend on some videos 
also passing livestream link into parameter give wrong result link ( if we do -g -f  93 )
like this : 

Linux Version : " youtube-dl -g -f 140 https://www.youtube.com/watch?v=kB4D0A0961E "
give good link : [Result](https://r6---sn-upoxu-25gs.googlevideo.com/videoplayback?id=901e03d00d3deb51&itag=140&source=youtube&requiressl=yes&mm=31&mn=sn-upoxu-25gs&initcwndbps=2712500&pl=23&mv=m&ei=IPV4We7YEsnCVsTjm7AM&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=2868802&lmt=1495374600357753&dur=180.581&key=dg_yt0&signature=6C30B38F2BC97EA0012637132F62A99E5C75A4CA.4F7C64D3B04F1FC87BEAED13DFD44BAA4F285870&mt=1501099192&ip=173.199.70.110&ipbits=0&expire=1501120896&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,initcwndbps,pl,mv,ei,ms,ratebypass,mime,gir,clen,lmt,dur
)

Windows Version : " youtube-dl.exe -g -f 140 https://www.youtube.com/watch?v=kB4D0A0961E  "
Give different link but it works : [Result](https://r5---sn-25glen7l.googlevideo.com/videoplayback?id=901e03d00d3deb51&itag=140&source=youtube&requiressl=yes&initcwndbps=1758750&ei=RfV4Wde5O8_Nc_vlhaAN&mm=31&mn=sn-25glen7l&pl=16&mv=m&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=2868802&lmt=1495374600357753&dur=180.581&mt=1501099192&key=dg_yt0&signature=7A97664EAD9F0B02BBDD09835C3B644E2F5DD340.09BAC6D20E0E869F9283EB107277BE5C569B5811&ip=176.133.118.253&ipbits=0&expire=1501120934&sparams=ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,ei,mm,mn,pl,mv,ms,ratebypass,mime,gir,clen,lmt,dur)

i don't understand, but i wanna help you bcz this is an awsome soft :)) 
also , thanks to you, i realized a little dream : [YouTube-music.org](http://173.199.70.110/)

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser
