### ISSUE TITLE
Get filename (Python API)

### ISSUE THREAD

**Issue by levinus** [rg3/youtube-dl#13750]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Question

Hi,
I am working with the barely documented youtube-dl Pyhton API. What I want to do is get the final name of the file also using the provided `outtmpl` option. My code looks like this:
```    
...
def get_title(url, template):
        ytdl_opts = {
            'simulate': 'True',
            'forcefilename': 'True',
            'outtmpl': '{}'.format(template),
            'logger': MyLogger()   #Exists above 
        }
        with youtube_dl.YoutubeDL(ytdl_opts) as ytdl:
            result = ytdl.extract_info("{}".format(url))
            title = result.get("title", None)
            return title
```
As you possibly know the `title` field from `extract_info` does only return the raw title of the video, not the 'editied' version with `outtmpl`. The logger gets the filename because the `forcefilename` option is speciefied. But I want to return the filename. Is there a way to do this? For now I have solved it by executing the command-line youtube-dl form pyhton. A way to do it with the API would be very cool.
Thanks,
Levin

**Comment by siddht4** [comment]
try this https://github.com/siddht4/youtube_dl_embed/blob/master/python_embed/1.py.  Instead of https://github.com/siddht4/youtube_dl_embed/blob/master/python_embed/1.py#L41    change your script to. `print(str(d['filename'])` .

**Comment by levinus** [comment]
Hey,
I know that I can print the filename but I want to return it in the `get_title` function. Is there a way to get the output readable for the function?

**Comment by siddht4** [comment]
@levinus  simply call it

**Comment by dstftw** [comment]
`ytdl.prepare_filename(result)`.

**Comment by Tointoin** [comment]
When I use `ytdl.prepare_filename(result)`, I get the temporary `filename.webm` with the .webm format. Is it possible to get directly the filename with the right format extension ?

my code :
```
            ydl_opts = {
                'format': 'bestaudio',
                'outtmpl': unicode('/srv/media/%(title)s-%(id)s.%(ext)s'),
                'postprocessors': [{'key':'FFmpegExtractAudio'}],
                'restrictfilenames':True,
                'forcefilename':True,
            } 

            with youtube_dl.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(uri, download=download)
                file_path = ydl.prepare_filename(info)
```

**Comment by xaverhimmelsbach** [comment]
@Tointoin to get the right format extension, you can just modify the info dictionary before you pass it to prepare_filename.
However, you need to know the file extension you want in advance and specify it via preferredcodec.

```
AUDIO_EXTENSION = 'wav'

def download_audio(url, output_path):
    ydl_opts = {
        'outtmpl': output_path + '/%(title)s.%(ext)s',
        'format': 'bestaudio',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': AUDIO_EXTENSION,
        }]}

    with YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=True)
        # Copy info dict and change video extension to audio extension
        info_with_audio_extension = dict(info)
        info_with_audio_extension['ext'] = AUDIO_EXTENSION
        # Return filename with the correct extension
        return ydl.prepare_filename(info_with_audio_extension)
```

You could probably edit the info dictionary directly without copying it, but I didn't want to take any chances.
