### ISSUE TITLE
Safaribooksonline cookie support? (Single sign on?)

### ISSUE THREAD

**Issue by ManvendraSK** [rg3/youtube-dl#13763]
It's not a bug, just a question/vote for the feature.

Can this software download videos using a cookie file from safaribooksonline.com, much like it does with lynda.com?

Safari account is using Single Sign On feature, which redirects to subscribed company's portal for username and password, and after validating at company's portal it logs the user in automatically. 

Any help?

**Comment by dstftw** [comment]
Only https://www.safaribooksonline.com/accounts/login/ is supported.

**Comment by ManvendraSK** [comment]
Thanks @dstftw

**Comment by luizconrado** [comment]
@dstftw Do you plan to add this feature? I would help me a lot as well. Thanks.

**Comment by dstftw** [comment]
1. I don't have an account.
2. There is no "secondary" login mechanism.
