### ISSUE TITLE
pluralsight 404 not found

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#13770]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.07.23
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---
i am getting error while download every course of pluralsight but i can access via browser

PS C:\Users\HD37> youtube-dl --verbose -o '~/downloads/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https:/
/pluralsight.com/training/Courses/TableOfContents/dot-net-applications-deployment-pipeline --sleep-interval 90 --limit-r
ate 200k --username 123@123.com --password 123
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-o', u'~/downloads/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', u'h
ttps://pluralsight.com/training/Courses/TableOfContents/dot-net-applications-deployment-pipeline', u'--sleep-interval',
u'90', u'--limit-rate', u'200k', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.07.23
[debug] Python version 2.7.12 - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[generic] dot-net-applications-deployment-pipeline: Requesting header
[redirect] Following redirect to https://app.pluralsight.com/courses/dot-net-applications-deployment-pipeline
[pluralsight:course] dot-net-applications-deployment-pipeline: Downloading course JSON
[download] Downloading playlist: Building a Deployment Pipeline for .NET Applications
[pluralsight:course] playlist Building a Deployment Pipeline for .NET Applications: Collected 43 video ids (downloading
43 of them)
[download] Downloading video 1 of 43
[pluralsight] Downloading login page
[pluralsight] Logging in as 123@123.com
[pluralsight] 83c28313-c7af-46b2-95e6-f45132246d14-0: Downloading JSON metadata
[pluralsight] 83c28313-c7af-46b2-95e6-f45132246d14-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 83c28313-c7af-46b2-95e6-f45132246d14-0: Waiting for 2 seconds to avoid throttling
[debug] Default format spec: best
[debug] Invoking downloader on u'http://vid21.pluralsight.com/clips/resolution/51186bac-faf5-4019-ad65-48153e53c23c/mp4/
1280x720.mp4?EClsKB5jeDSQZxLxiNKAbIFvSWs_zzHWP8o_fU_YlYS6xp0Mup-lIlHqcJCVKpWRE0U7gPt1kLNy68ovzmm01o4u6VbpNMqnpXJW8XChZYP
ryKzlqtfkT6RtcwIvH7UqoAsU8uDSlURwW4YzU3a2DxVb4Frie7BwQiFMSQdzzdcfxbUOQg'
[download] Sleeping 90 seconds...
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1863, in process_info
    success = dl(filename, info_dict)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1805, in dl
    return fd.download(name, info)
  File "c:\python27\lib\site-packages\youtube_dl\downloader\common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "c:\python27\lib\site-packages\youtube_dl\downloader\http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2166, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

PS C:\Users\HD37>

**Comment by Druopel** [comment]
I have same issue, even on a course that downloaded fine last week now gives  HTTP Error 404: Not Found

**Comment by tyk007007** [comment]
Have the same issue with 2017.07.30.1.

**Comment by dstftw** [comment]
Temporary pluralsight issue.
