### ISSUE TITLE
what is the directory path of ffmpeg for download interval of youtube video?

### ISSUE THREAD

**Issue by hoyeunglee** [rg3/youtube-dl#13776]
pip install --upgrade youtube_dl

ffmpeg -ss 14350 -i $(youtube-dl -f 22 --get-url https://www.youtube.com/watch?v=0347ZoDXyP0) -t 11200 -c:v copy -c:a copy react-spot.mp4

i find ffmpeg.pyc in 
C:\Python27\Lib\site-packages\youtube_dl\postprocessor

but no executable file

what is the directory path of ffmpeg for download interval of youtube video?

**Comment by dstftw** [comment]
Where you installed ffmpeg obviously.

**Comment by WolfganP** [comment]
Find your executable via 'which ffmpeg' (assuming you're using some Linux flavor)
