### ISSUE TITLE
Unable to download webpage: IncompleteRead(7919 bytes read)

### ISSUE THREAD

**Issue by maljaiun** [rg3/youtube-dl#13792]
youtube-dl https://youtu.be/YYiOWU0XtUE
[youtube] YYiOWU0XtUE: Downloading webpage
ERROR: Unable to download webpage: IncompleteRead(7919 bytes read) (caused by IncompleteRead(7919 bytes read)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
➜  Desktop youtube-dl --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12, avprobe 12
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
