### ISSUE TITLE
Symbols are replaced with underlines

### ISSUE THREAD

**Issue by TheFox1312** [rg3/youtube-dl#13803]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.30.1**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Other

---

I've noticed that every symbol ( e.g. (xyz) -> _xyz_ ) are replaced but i don't using the option `--restricted-filename`. Thats my command that I use:
```
youtube-dl -o '/var/www/ytdl/downloads/%(title)s.%(ext)s' --format 'bestaudio[ext=m4a]' --default-search 'ytsearch' --prefer-ffmpeg -x --embed-thumbnail --metadata-from-title '%(artist)s - %(title)s' --add-metadata --audio-format m4a --audio-quality 0 "link"
```
So why does youtube-dl replace these characters?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
