### ISSUE TITLE
Cookies not working

### ISSUE THREAD

**Issue by Pcsl** [rg3/youtube-dl#13802]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
 youtube-dl.exe: error: no such option: --cookies C:/cookies.txt

<end of log>
```

### Description of your *issue*, suggested solution and other information

I'm trying to add a cookies.txt adding this extra line:
"--cookies C:/cookies.txt"
However, as you can see youtube-dl says it doesn't exist. I also tried using the former line without quotes but it doesn't work neither as youtube-dl supposes they are 2 separate commands.

**Comment by dstftw** [comment]
Correct usage is `--cookies "C:/cookies.txt"`.

**Comment by Pcsl** [comment]
I did and I got this:

`[08/01/17 19:56:27] [debug] Command-line args: ['--newline', '-i', '-k', '-o', 'C:\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '--cookies', 'C:/cookies.txt', '--verbose', 'url']`

Is it right that '--cookies', 'C:/cookies.txt' appears like that? Probably not but maybe I'm wrong...

**Comment by dstftw** [comment]
This is how it's supposed to appear.
