### ISSUE TITLE
 Memory leak program with big Youtube playlist

### ISSUE THREAD

**Issue by damamasss** [rg3/youtube-dl#13808]
When I download big playlist (more than 500 videos) from Youtube with --datebefore (may be and without datebefore), on Debian 8.4 machine, youtube-dl have leak memory - full 4G RAM is occupied by the youtube-dl

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
