### ISSUE TITLE
how can we add destination folder path in Youtube-dl command while downloading from vimeo

### ISSUE THREAD

**Issue by kiranbulley** [rg3/youtube-dl#13818]

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#output-template

**Comment by kiranbulley** [comment]
what i am missing in the command?

youtube-dl -v 'https://vimeo.com/227690432' -o 'http://localhost:8888/vid/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://vimeo.com/227690432', u'-o', u'http://localhost:8888/vid/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.18
[debug] Python version 2.7.13 - Darwin-15.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[vimeo] 227690432: Downloading webpage
[vimeo] 227690432: Extracting information
[vimeo] 227690432: Downloading webpage
[vimeo] 227690432: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 227690432: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 227690432: Downloading fastly_skyfire m3u8 information
[vimeo] 227690432: Downloading akfire_interconnect_quic MPD information
[vimeo] 227690432: Downloading akfire_interconnect_quic MPD information
[vimeo] 227690432: Downloading fastly_skyfire MPD information
[vimeo] 227690432: Downloading fastly_skyfire MPD information
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1501833886-0x1000b6ef2c4570486d4d7815e10ce065c25d610d/227690432/sep/video/801135857,801135859,801135858,801135856/../'
[dashsegments] Total fragments: 42
[download] Destination: http://localhost:8888/vid/.fdash-fastly_skyfire_sep-video-801135858
[download] 100% of 80.60MiB in 03:07
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1501833886-0x1000b6ef2c4570486d4d7815e10ce065c25d610d/227690432/sep/video/801135857,801135859,801135858,801135856/../'
[dashsegments] Total fragments: 42
[download] Destination: http://localhost:8888/vid/.fdash-fastly_skyfire_sep-audio-801135859
[download] 100% of 7.55MiB in 00:16
[ffmpeg] Merging formats into "http://localhost:8888/vid/.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:http://localhost:8888/vid/.fdash-fastly_skyfire_sep-video-801135858' -i 'file:http://localhost:8888/vid/.fdash-fastly_skyfire_sep-audio-801135859' -c copy -map '0:v:0' -map '1:a:0' 'file:http://localhost:8888/vid/.mp4.temp'
ERROR: file:http://localhost:8888/vid/.mp4.temp: Invalid argument
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1965, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 479, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: file:http://localhost:8888/vid/.mp4.temp: Invalid argument

**Comment by dstftw** [comment]
Missing valid output template.
