### ISSUE TITLE
how does or on what basis does youtube-dl calculate the size of a page ?

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#13817]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

I am sharing the following as an e.g. -

```
$ youtube-dl https://www.youtube.com/channel/UC_DCVMhIdgwQ1uUE76XLXZg/videos --dateafter 20170727                               
[youtube:channel] UC_DCVMhIdgwQ1uUE76XLXZg: Downloading channel page
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading webpage
[download] Downloading playlist: Uploads from DieselDesigns Gaming
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #1
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #2
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #3
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #4
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #5
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #6
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #7
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #8
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #9
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #10
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #11
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #12
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #13
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #14
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #15
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #16
[youtube:playlist] UU_DCVMhIdgwQ1uUE76XLXZg: Downloading page #17
```

How or what number of video entries make a page, it seems between 102, 103 videos constitute a page, can somebody share some more info ?

**Comment by dstftw** [comment]
Each page contains a number of new videos returned after clicking "Load more" button.

**Comment by siddht4** [comment]
the thing you are trying to download is a youtube playlist which is curently the total number of videos uploaded by youtube channel DieselDesigns Gaming. There are lots of videos. A single playlist contains  around 30 videos i guess and more are added as the pages adds up
