### ISSUE TITLE
Can't download subtitles from www.udemy.com

### ISSUE THREAD

**Issue by Bracer-tracer** [rg3/youtube-dl#13812]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Youtube-dl can't download (parse) subtitles from some of the video on www.udemy.com, for example downloading subs from a free course: https://www.udemy.com/ip-subnetting/

---

-v log:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '--write-sub
', '--convert-subs', 'srt', '-k', '-o', '..\%(playlist)s\\%(playlist_ind
ex)s - %(title)s.%(ext)s', 'https://www.udemy.com/ip-subnetting/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-86809-g012620a, ffprobe N-86809-g012620a
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as login
[udemy:course] ip-subnetting: Downloading webpage
[udemy:course] 1056284: Downloading course curriculum
[download] Downloading playlist: The Complete IP Subnetting Course: Beginner to
Advanced!
[udemy:course] playlist The Complete IP Subnetting Course: Beginner to Advanced!
: Collected 60 video ids (downloading 60 of them)
[download] Downloading video 1 of 60
[udemy] Downloading login popup
[udemy] 6288972: Downloading webpage
[udemy] 6288972: Downloading lecture JSON
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://udemy-assets-on-demand2.udemy.com/2017-0
..../WebHD_720p.mp4?nva=..&token=..'
[download] Destination: ..\Video\The Complete IP Subnetting Course - Beginner to
 Advanced!\01 - How To Get The Most Out Of This Course.mp4
[download] 100% of 2.57MiB in 00:02
**[ffmpeg] There aren't any subtitles to convert**
[download] Downloading video 2 of 60

...
<end of log>
```
---

**Comment by rocxteady** [comment]
+1
