### ISSUE TITLE
youtube-dl stucked when downloading from a website.

### ISSUE THREAD

**Issue by MoHD20** [rg3/youtube-dl#13814]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v  http://vod.ashams.com/Bollywood/Mn.Alnazra.Altanya.P1/105.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://vod.ashams.com/Bollywood/Mn.Alnazra.Altanya.P1/105.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 3.6.1 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[generic] 105: Requesting header
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://vod.ashams.com/Bollywood/Mn.Alnazra.Altanya.P1/105.mp4'
[download] Destination: 105-105.mp4
[download]   7.6% of 229.43MiB at 225.42KiB/s ETA 16:02
```

### Description of your *issue*, suggested solution and other information
youtube-dl just stuck every single time I tried to download this video or any video from the same site.

here is more urls:
 http://vod.ashams.com/Bollywood/Mn.Alnazra.Altanya.P1/106.mp4
 http://vod.ashams.com/Bollywood/Mn.Alnazra.Altanya.P1/102.mp4
also sometimes I get:
`youtube_dl.utils.ContentTooShortError`

**Comment by dstftw** [comment]
Most likely issue with your network connection.
```
PS C:\dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py http://vod.ashams.com/Bollywood/Mn.Alnazra.Altanya.P1/105.mp4
[generic] 105: Requesting header
[download] Destination: 105-105.mp4
[download] 100% of 229.43MiB in 00:29
PS C:\dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py http://vod.ashams.com/Bollywood/Mn.Alnazra.Altanya.P1/102.mp4
[generic] 102: Requesting header
[download] Destination: 102-102.mp4
[download] 100% of 221.82MiB in 00:26
```
