### ISSUE TITLE
[Cinchcast]  Remove extractor

### ISSUE THREAD

**Issue by Aonavan** [rg3/youtube-dl#13825]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

Last seen:
https://web.archive.org/web/20160423182853/http://www.cinchcast.com
After that it's was down and then there is another site insead of it month later.

http://player.cinchcast.com/?platformId=1&#038;assetType=single&#038;assetId=7141703 - shows 404.

**Comment by dstftw** [comment]
http://player.cinchcast.com/?show_id=5258197&platformId=1&assetType=single
