### ISSUE TITLE
Required password when moving/copying downloaded videos

### ISSUE THREAD

**Issue by TarekSalama** [rg3/youtube-dl#13823]
Hello,

When I use youtube-dl I always have to add sudo so I can update it (-U) for some reason. That being said I this may have something to do with my issue.
My issue is, whenever I have to move or delete videos I downloaded, I have to enter my Mac's password just like I do with sudo. Copying doesn't trigger this behavior however copied videos will need a password as well for moving/deleting them.

Any idea why? Is my issue connected to the observation I mentioned earlier?

Thanks

**Comment by dstftw** [comment]
You don't need to use `sudo` with youtube-dl apart from updating in the first place.
