### ISSUE TITLE
format listing shows only some formats, downloading playlist another. 

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#13828]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

─[$] youtube-dl --version                                                                                                            
2017.07.30.1

[$] youtube-dl -F oXh8PlmfgqU                                                                                                       
[youtube] oXh8PlmfgqU: Downloading webpage
[youtube] oXh8PlmfgqU: Downloading video info webpage
[youtube] oXh8PlmfgqU: Extracting video information
[youtube] oXh8PlmfgqU: Downloading MPD manifest
[info] Available formats for oXh8PlmfgqU:
format code  extension  resolution note
139          m4a        audio only DASH audio   51k , m4a_dash container, mp4a.40.5@ 48k (22050Hz), 15.88MiB
249          webm       audio only DASH audio   55k , opus @ 50k, 16.29MiB
250          webm       audio only DASH audio   69k , opus @ 70k, 19.75MiB
171          webm       audio only DASH audio  100k , vorbis@128k, 30.16MiB
251          webm       audio only DASH audio  122k , opus @160k, 35.65MiB
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k (44100Hz), 42.40MiB
160          mp4        256x144    DASH video  115k , avc1.4d400c, 30fps, video only, 24.13MiB
278          webm       256x144    144p  116k , webm container, vp9, 30fps, video only, 30.13MiB
242          webm       426x240    240p  272k , vp9, 30fps, video only, 62.53MiB
133          mp4        426x240    DASH video  289k , avc1.4d4015, 30fps, video only, 66.57MiB
243          webm       640x360    360p  506k , vp9, 30fps, video only, 117.54MiB
134          mp4        640x360    DASH video  711k , avc1.4d401e, 30fps, video only, 134.21MiB
244          webm       854x480    480p  900k , vp9, 30fps, video only, 210.30MiB
135          mp4        854x480    DASH video 1358k , avc1.4d401f, 30fps, video only, 258.06MiB
247          webm       1280x720   720p 1782k , vp9, 30fps, video only, 418.98MiB
136          mp4        1280x720   720p 2723k , avc1.4d401f, 30fps, video only, 493.57MiB
302          webm       1280x720   720p60 3071k , vp9, 60fps, video only, 673.01MiB
248          webm       1920x1080  1080p 3166k , vp9, 30fps, video only, 763.58MiB
298          mp4        1280x720   DASH video 3539k , avc1.4d4020, 60fps, video only, 869.85MiB
137          mp4        1920x1080  1080p 4419k , avc1.640028, 30fps, video only, 992.18MiB
303          webm       1920x1080  1080p60 5104k , vp9, 60fps, video only, 1.17GiB
299          mp4        1920x1080  DASH video 5834k , avc1.64002a, 60fps, video only, 1.52GiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)

[$] youtube-dl https://www.youtube.com/playlist\?list\=PLGe_S5n7MjT2pWyCLIc9G1wZSlhxOQO5b                                           
[youtube:playlist] PLGe_S5n7MjT2pWyCLIc9G1wZSlhxOQO5b: Downloading webpage
[download] Downloading playlist: Let's Play: Yonder The Cloud Catcher Chronicles
[youtube:playlist] playlist Let's Play: Yonder The Cloud Catcher Chronicles: Downloading 8 videos
[download] Downloading video 1 of 8
[youtube] oXh8PlmfgqU: Downloading webpage
[youtube] oXh8PlmfgqU: Downloading video info webpage
[youtube] oXh8PlmfgqU: Extracting video information
[youtube] oXh8PlmfgqU: Downloading MPD manifest
[download] Destination: Zelda meets Stardew! - Yonder The Cloud Catcher Chronicles Gameplay – Part 1-oXh8PlmfgqU.f299.mp4
[download]   5.5% of 1.52GiB at 88.71KiB/s ETA 04:42:42^C

[$] mpv Zelda\ meets\ Stardew\!\ -\ Yonder\ The\ Cloud\ Catcher\ Chronicles\ Gameplay\ –\ Part\ 1-oXh8PlmfgqU.f299.mp4.part     
(null) requires an argument
Warning: option --heartbeat-cmd is deprecated and might be removed in the future (use Lua scripting instead).
Playing: Zelda meets Stardew! - Yonder The Cloud Catcher Chronicles Gameplay – Part 1-oXh8PlmfgqU.f299.mp4.part
 (+) Video --vid=1 (*) (h264 1920x1080 60.000fps)
xscreensaver-command: no screensaver is running on display :0
VO: [opengl] 1920x1080 yuv420p
V: 00:00:09 / 00:46:39 (0%) Dropped: 236 Cache: 10s+8MB

Exiting... (Quit)
---

To make it easy to understand, see the format listing youtube-dl shows, the best format it shows is 
`22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)`

If I download in playlist format and play it via mpv I discover it is in 1920x1080 format which was not listed anywhere in the format list. 

Seems to be a bug, please fix it.

**Comment by dstftw** [comment]
Read how [format selection works](https://github.com/rg3/youtube-dl#format-selection).
