### ISSUE TITLE
Clear partial downloads (both from youtube-dl and the files themselves)

### ISSUE THREAD

**Issue by rEes9P** [rg3/youtube-dl#13838]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

I've been playing around with some large files, all of which are partially downloaded. I would like to delete them all and start over. I ran the `--rm-cache-dir` command but when I start one of the downloads it still resumes from the last position. What should I do to clear youtube-dl's partial download memory and ensure that all partially downloaded files are deleted?

**Comment by dstftw** [comment]
Remove all `*.part` and `*.ytdl` files.

**Comment by rEes9P** [comment]
Thanks, that worked! Just out of interest, what does `--rm-cache-dir` do?

**Comment by dstftw** [comment]
```
--rm-cache-dir                   Delete all filesystem cache files
```

**Comment by rEes9P** [comment]
Yup, I did get that. Was just wondering what kind of files these are in the case of youtube-dl.

**Comment by michealespinola** [comment]
@rEes9P, are you sure thats the link you meant to reference for understanding youtube-dl cache files?  I ask because I see no reference to cache files on that page.
