### ISSUE TITLE
BBC 

### ISSUE THREAD

**Issue by Kvilimas** [rg3/youtube-dl#13839]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Hi, 
I'm a newbie on youtube-dl. I have tried to download a video from bbc iplayer. 
After video part (mp4) and audio part (m4a) gets downloaded, the ffmpeg step fails. 

Looking forward to hearing from you. 

Best regards, 
Kostas Vilimas
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.bbc.co.uk/iplayer/episode/p057nmkt/against-the-law']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 2.7.12 - Linux-4.4.0-83-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] p057nmkt: Downloading video page
[bbc.co.uk] p057nmkt: Downloading playlist JSON
[bbc.co.uk] b08yp734: Downloading media selection XML
[bbc.co.uk] b08yp734: Downloading m3u8 information
[bbc.co.uk] b08yp734: Downloading m3u8 information
[bbc.co.uk] b08yp734: Downloading m3u8 information
[bbc.co.uk] b08yp734: Downloading m3u8 information
[bbc.co.uk] b08yp734: Downloading MPD manifest
[bbc.co.uk] b08yp734: Downloading MPD manifest
[bbc.co.uk] b08yp734: Downloading m3u8 information
[bbc.co.uk] b08yp734: Downloading m3u8 information
[bbc.co.uk] b08yp734: Downloading m3u8 information
[bbc.co.uk] b08yp734: Downloading m3u8 information
[bbc.co.uk] b08yp734: Downloading m3u8 information
[bbc.co.uk] b08yp734: Downloading m3u8 information
[bbc.co.uk] b08yp734: Downloading MPD manifest
[bbc.co.uk] b08yp734: Downloading MPD manifest
[bbc.co.uk] b08yp734: Downloading m3u8 information
[bbc.co.uk] b08yp734: Downloading m3u8 information
[bbc.co.uk] b08yp734: Downloading m3u8 information
[bbc.co.uk] b08yp734: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/16a584-b08yp734/vf_b08yp734_91e8d42e-b443-495a-bae9-3067fb17547b.ism.hlsv2.ism/dash/'
[dashsegments] Total fragments: 1293
[download] Destination: Against the Law-b08yp734.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-video=5070000.mp4
[download] 100% of 824.66MiB in 13:09
[debug] Invoking downloader on u'https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/16a584-b08yp734/vf_b08yp734_91e8d42e-b443-495a-bae9-3067fb17547b.ism.hlsv2.ism/dash/'
[dashsegments] Total fragments: 1293
[download] Destination: Against the Law-b08yp734.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-audio_eng=128000.m4a
[download] 100% of 75.17MiB in 07:09
[ffmpeg] Merging formats into "Against the Law-b08yp734.mp4"
[debug] ffmpeg command line: avconv -y -i 'file:Against the Law-b08yp734.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-video=5070000.mp4' -i 'file:Against the Law-b08yp734.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-audio_eng=128000.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Against the Law-b08yp734.temp.mp4'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2002, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 479, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
<end of log>
```

**Comment by dstftw** [comment]
Update ffmpeg.

**Comment by Kvilimas** [comment]
well, the error was the same. What did help though was youtube-dl option
"-f best"

Regards,
Kostas Vilimas

2017-08-06 12:41 GMT+02:00 Sergey M. <notifications@github.com>:

**Comment by dstftw** [comment]
Most likely, it wasn't'.
