### ISSUE TITLE
Does youtube-dl supports multi threaded download

### ISSUE THREAD

**Issue by siddht4** [rg3/youtube-dl#13837]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.06**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ x] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.08.06
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.
-----------------------------------------------------------------------------------------------------------------

Does youtube-dl supports multi threaded download i.e concurrent downloading for the same site.
This is due to my isp restricting download speed of a single thread to 100kbps. Example ; A 10 mb would take   around 2 mins. But same if multi threaded (8 simultaneous connection) it would be simply download in seconds. The capping speed I found was around 900 kbps. 

Example :  

youtube-dl https://www.youtube.com/watch?v=2R2gb0MKJlo -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=2R2gb0MKJlo', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.06
[debug] Python version 2.7.12 - Linux-4.13.0-041300rc3-generic-x86_64-with-LinuxMint-18.2-sonya
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] 2R2gb0MKJlo: Downloading webpage
[youtube] 2R2gb0MKJlo: Downloading video info webpage
[youtube] 2R2gb0MKJlo: Extracting video information
[youtube] 2R2gb0MKJlo: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r2---sn-cvh7kn7r.googlevideo.com/videoplayback?id=d91da06f430a265a&itag=137&source=youtube&requiressl=yes&ei=LOKGWaHFH9WIoAOTuKqgDA&mv=m&initcwndbps=115000&ms=au&pl=20&mn=sn-cvh7kn7r&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=15848259754&lmt=1499826754906798&dur=36000.000&beids=[9466594]&key=dg_yt0&signature=80A75F663095FE44415AB12E33E1BF3069521262.6FAA33884C3C860F5D9BFC0DF7AAD543649B95C3&mt=1502011846&ip=&ipbits=0&expire=1502033548&sparams=ip,ipbits,expire,id,itag,source,requiressl,ei,mv,initcwndbps,ms,pl,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: 10 Hours Of Relaxing Planet Earth II Mountain Sounds - Earth Unplugged-2R2gb0MKJlo.f137.mp4
[download]   0.0% of 14.76GiB at 105.23KiB/s ETA 40:51:07

Please dont download this as its 14.7 Gb 

so instead downloading the best audio

youtube-dl https://www.youtube.com/watch?v=2R2gb0MKJlo -f bestaudio -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=2R2gb0MKJlo', u'-f', u'bestaudio', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.06
[debug] Python version 2.7.12 - Linux-4.13.0-041300rc3-generic-x86_64-with-LinuxMint-18.2-sonya
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] 2R2gb0MKJlo: Downloading webpage
[youtube] 2R2gb0MKJlo: Downloading video info webpage
[youtube] 2R2gb0MKJlo: Extracting video information
[youtube] 2R2gb0MKJlo: Downloading MPD manifest
[debug] Invoking downloader on u'https://r1---sn-cvh76n7d.googlevideo.com/videoplayback?signature=D1358D7B52389908C26E3A869B5BF2034F54788C.DA0853834492C2565A92F6191D2DDC44D0F927CF&source=youtube&clen=521652552&ei=d-KGWa6oHY-DoQOIhKewBw&key=yt6&pl=20&mn=sn-cvh76n7d&ipbits=0&mm=31&itag=251&ms=au&initcwndbps=120000&mv=m&dur=36000.000&mt=1502011908&id=o-ALm-rBnf2yD6jvHGExExfK4Ux82wzy7m4AaU8AicqLax&ip=&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&keepalive=yes&gir=yes&mime=audio%2Fwebm&requiressl=yes&lmt=1499892698815395&expire=1502033623&ratebypass=yes'
[download] Destination: 10 Hours Of Relaxing Planet Earth II Mountain Sounds - Earth Unplugged-2R2gb0MKJlo.webm
[download]   0.1% of 497.49MiB at 77.20KiB/s ETA 01:49:55

So this would take 100 mins or so is there any parmaters to  multi threading  in youtube-dl

**Comment by dstftw** [comment]
Not supported. Use `--external-downloader`.

**Comment by siddht4** [comment]
okay I am using aria2 and xdm now. 

can you mention why this was tagged as duplicate
