### ISSUE TITLE
Old GameSpot videos not working

### ISSUE THREAD

**Issue by mariomadproductions** [rg3/youtube-dl#13831]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```

C:\Writ-App\youtube-dl>youtube-dl --verbose https://www.gamespot.com/videos/e3-2004-nintendo-booth-tour/2300-6098854/ --write-pages
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.gamespot.com/videos/e3-2004-nintendo-booth-tour/2300-6098854/', '--write-pages']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-85179-gdc1a1b8, ffprobe N-85179-gdc1a1b8
[debug] Proxy map: {}
[GameSpot] 6098854: Downloading webpage
[GameSpot] Saving request to 6098854_https_-_www.gamespot.com_videos_e3-2004-nintendo-booth-tour_2300-6098854_.dump
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 1956, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\gamespot.py", line 50, in _real_extract
AttributeError: 'list' object has no attribute 'get'

C:\Writ-App\youtube-dl>
```

---

### Description of your *issue*, suggested solution and other information

Not working on [old videos](https://www.gamespot.com/videos/e3-2004-nintendo-booth-tour/2300-6098854/) that GameSpot have said not to work on the new HTML5 player.
Does work with [new videos](https://www.gamespot.com/videos/playerunknowns-battlegrounds-update-the-witcher-co/2300-6440260/) that do work on the new HTML5 player

[Here](https://gist.github.com/mariomadproductions/3b9b1f81ec227721d752e5c145872f91) is the dump file for the failed download.

**Comment by dstftw** [comment]
https://www.gamespot.com/videos/e3-2004-nintendo-booth-tour/2300-6098854/ does not play in browser.

**Comment by mariomadproductions** [comment]
What if it is still linked somewhere on the page? Does youtube-dl only support ones that work in-browser?

**Comment by dstftw** [comment]
Ask gamespot "what if", they broke old videos not youtube-dl. If it does not play at all how does youtube-dl is supposed to support it?

**Comment by mariomadproductions** [comment]
Videos can still be present in a page without being in a playable embed. I sent GameSpot an email.
