### ISSUE TITLE
[bilibili]can't get other format info?

### ISSUE THREAD

**Issue by kesdoputr** [rg3/youtube-dl#13846]
Hello,I'm using newest widows build 2017.08.06 from
https://rg3.github.io/youtube-dl/download.html

And when i use youtube-dl to get information from a bilibili video
I can only get mp4 but can't see flv ver.

ex. video link: http://www.bilibili.com/video/av13015653/
firest：when use youtube-dl
i type youtube-dl -F http://www.bilibili.com/video/av13015653/
http://i.imgur.com/IPR9mD2.png
second：i try to use you-get
i type you-get -i http://www.bilibili.com/video/av13015653/
http://i.imgur.com/JiMdzW1.png

I download both video and found that 
mp4's resolution is 640x350
flv's resolution is 1280x720

We can see that it have a more good resolution flv format from you-get information
but youtube-dl only list mp4 format.
Is there a option that i can use youtube-dl to get flv format of this video?
(Because i'm using mpv with youtube-dl to play bilibili video)

**Comment by a17uk** [comment]
I also have this problem. No matter how old or new the videos are. It just can't extract the player parameter.

**Comment by remitamine** [comment]
Duplicate of #12095.
