### ISSUE TITLE
Download Playlist 404 error

### ISSUE THREAD

**Issue by UzairVawda** [rg3/youtube-dl#13850]
Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] playlist: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I am trying to download my youtube playlist and it keeps referencing this erroe

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
