### ISSUE TITLE
Get exit status of youtube-dl.exe in batch script

### ISSUE THREAD

**Issue by EWouters** [rg3/youtube-dl#13855]
Hi, I am trying to write a simple batch script because my downloads keep returning this error: `ERROR: content too short (expected 3432356 bytes and served 2830796)` and I want them to auto retry until successful.

I wrote the following:
```
@ECHO OFF
SET /P url="Paste URL to download: "
ECHO Download %url%
:while1
for /f "delims=" %%a in ('youtube-dl.exe %url%') do @set result=%%a
if %ERRORLEVEL% NEQ 0 (
    ECHO %result%
    ECHO Failed, retrying...
    GOTO while1
)
ECHO Success!
pause
```

But even when there is an error it will go to Success. How can I get the exit status of youtube-dl.exe in my if statement?

Thanks!

BTW: it would be awesome if there would be an option to retry until successful in youtube-dl itself. Then it could also be robust against wrong urls.

**Comment by dstftw** [comment]
`for` executes command in a separate `cmd.exe` process thus you're getting `errorlevel` this process not youtube-dl.

**Comment by EWouters** [comment]
How ignorant of me, thank you. This now solves my problem:
```
@ECHO OFF
SET /P url="Paste URL to download: "
:while
youtube-dl.exe %url%
if %ERRORLEVEL% NEQ 0 (
    ECHO Failed, retrying...
    GOTO while
)
ECHO Success!
PAUSE
```
I would still love it if this feature would be added.
