### ISSUE TITLE
download from dailymotion

### ISSUE THREAD

**Issue by kiranbulley** [rg3/youtube-dl#13857]
i have used following command

youtube-dl -v http://www.dailymotion.com/video/x5vtmjz -o 'http://localhost:8888/vid/daily.mp4

for that i am getting following response
System config: [u'--prefer-free-formats']\n[debug] User config: []\n[debug] Custom config: []\n[debug] Command-line args: [u'-v', u'http:\/\/www.dailymotion.com\/video\/x5vtmjz', u'-o', u'\/home\/myconvertlab\/public_html\/video-project\/download\/inputvideos\/uservideo_1502179498.mp4']\nWARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.\n[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968\n[debug] youtube-dl version 2017.06.25\n[debug] Python version 2.7.5 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-centos-7.3.1611-Core\n[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8\n[debug] Proxy map: {}\n[dailymotion] x5vtmjz: Downloading webpage\nWARNING: unable to extract view count; please report this issue on https:\/\/yt-dl.org\/bug . Make sure you are using the latest version; see  https:\/\/yt-dl.org\/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n[dailymotion] x5vtmjz: Downloading embed page\nERROR: Unable to extract video info; please report this issue on https:\/\/yt-dl.org\/bug . Make sure you are using the latest version; see  https:\/\/yt-dl.org\/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\nTraceback (most recent call last):\n  File \"\/usr\/lib\/python2.7\/site-packages\/youtube_dl\/YoutubeDL.py\", line 761, in extract_info\n    ie_result = ie.extract(url)\n  File \"\/usr\/lib\/python2.7\/site-packages\/youtube_dl\/extractor\/common.py\", line 433, in extract\n    ie_result = self._real_extract(url)\n  File \"\/usr\/lib\/python2.7\/site-packages\/youtube_dl\/extractor\/dailymotion.py\", line 252, in _real_extract\n    'video info', flags=re.MULTILINE),\n  File \"\/usr\/lib\/python2.7\/site-packages\/youtube_dl\/extractor\/common.py\", line 782, in _search_regex\n    raise RegexNotFoundError('Unable to extract %s' % _name)\nRegexNotFoundError: Unable to extract video info; please report this issue on https:\/\/yt-dl.org\/bug . Make sure you are using the latest version; see  https:\/\/yt-dl.org\/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n\n"

help me to solve the issue.

**Comment by kiranbulley** [comment]
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.dailymotion.com/video/k4ZRnWwGOQDIjWk7xkq']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2017.06.25
[debug] Python version 2.7.5 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[dailymotion] k4ZRnWwGOQDIjWk7xkq: Downloading webpage
WARNING: unable to extract view count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[dailymotion] k4ZRnWwGOQDIjWk7xkq: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/dailymotion.py", line 252, in _real_extract
    'video info', flags=re.MULTILINE),
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kiranbulley** [comment]
the command i have run on local machine its working well. but giving problem on server

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
