### ISSUE TITLE
YouTube Video Category

### ISSUE THREAD

**Issue by bejayoharen** [rg3/youtube-dl#13859]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

It would be nice to be able to get the YouTube's video category (e.g. music, entertainment, etc).

**Comment by dstftw** [comment]
Categories are already available.

**Comment by bejayoharen** [comment]
If available, it should be documented here:

https://github.com/rg3/youtube-dl/blob/master/README.md#output-template

**Comment by whydna** [comment]
@dstftw how? don't see it in the documentation or mentioned anywhere.

**Comment by dstftw** [comment]
There are no categories for output template. It's a list of values in JSON.
