### ISSUE TITLE
402: Payment Required

### ISSUE THREAD

**Issue by Pupo1** [rg3/youtube-dl#13853]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v https://www.youtube.com/watch?v=-dVa7ooLRhc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=-dVa7ooLRhc']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2017.08.06
[debug] Python version 2.7.9 - Linux-2.6.32-042stab116.1-x86_64-with-debian-8.8
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] -dVa7ooLRhc: Downloading webpage
[youtube] -dVa7ooLRhc: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1956, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1527, in _real_extract
TypeError: argument of type 'NoneType' is not iterable


...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I get the 402 error - payment required. The usual explanation would be overuse of youtube-dl, but the error occurs even on a fresh server that I had never used vor youtube-dl before. 

I have currently three virtual servers, each running debian. 
Server 1: Debian 8.3 Jessie , youtube-dl 2017.08.06

Server 2: Debian 8.8 Jessie, youtube-dl 2017.08.06, NEVER used vor youtube-dl before

Server 3: Debian 9.0 stretch, youtube-dl 2017.05.18.1

Home computer: yout-dl does work fine on my computer at home, version 2017.02.11, on Linux Mint 17.1 .

The first two give me this error:

> Error: 
> 
> WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
> [youtube] _YS2yTY0RlE: Downloading webpage
> [youtube] _YS2yTY0RlE: Downloading video info webpage
> WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
> WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
> WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
> WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
> WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
>   File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
>   File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1956, in download
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1527, in _real_extract
> TypeError: argument of type 'NoneType' is not iterable

-------------------- the third server gives this error:

> youtube-dl https://www.youtube.com/watch?v=qqAtlyQTMn8&list=PL452007C8DAABDFEC
> [1] 11090
> pulmo@vps412210:~$ [youtube] qqAtlyQTMn8: Downloading webpage
> [youtube] qqAtlyQTMn8: Downloading video info webpage
> ERROR: unable to download video info webpage: HTTP Error 402: Payment Required (caused by <HTTPError 402: 'Payment Required'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

------------------------

**Comment by dstftw** [comment]
1. https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required
2. #5138.
