### ISSUE TITLE
[xstream] Remove extractor

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#13869]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

 'http://frontend.xstream.dk/btno/feed/video/?platform=web&id=86588'
'http://frontend.xstream.dk/ap/feed/video/?platform=web&id=21039'

Videos are not working, domain changed to xstream.net,  can't find video there.

**Comment by yan12125** [comment]
http://frontend.xstream.dk/btno/feed/video/?platform=web&id=86588 still has videos - those are Yahoo! MRSS (Media RSS), which are not supported by most browsers, so you won't see videos.

**Comment by hicrop** [comment]
@yand12125 this video disappeared too.
