### ISSUE TITLE
[Youtube] unable to download audio stream from video

### ISSUE THREAD

**Issue by PSlava** [rg3/youtube-dl#13863]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.06**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I can't download dashed audio stream with itag 133 from YouTube video (similar happens with itag 136).

---

bash-3.2$ ./youtube-dl -vf 133 https://www.youtube.com/watch?v=WjLvuf2fOX4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vf', u'133', u'https://www.youtube.com/watch?v=WjLvuf2fOX4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.06
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[youtube] WjLvuf2fOX4: Downloading webpage
[youtube] WjLvuf2fOX4: Downloading video info webpage
[youtube] WjLvuf2fOX4: Extracting video information
[youtube] WjLvuf2fOX4: Downloading MPD manifest
[youtube] WjLvuf2fOX4: Downloading MPD manifest
[debug] Invoking downloader on u'https://r3---sn-c0q7lnez.googlevideo.com/videoplayback/id/5a32efb9fd9f397e/itag/133/source/yt_otf/requiressl/yes/pl/24/ms/au/ei/5EmKWaDqHYX9Vv30ikg/mn/sn-c0q7lnez/mv/m/mm/31/initcwndbps/987500/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1491295100211936/signature/0122BC9BD1EA9D6B6AF6E48FCD9CE3446DDA1C5F.25AEFB6B21820D2A692C5652FCEFF55889CF2CF5/key/dg_yt0/mt/1502234809/ip/195.66.180.121/ipbits/0/expire/1502256708/sparams/ip,ipbits,expire,id,itag,source,requiressl,pl,ms,ei,mn,mv,mm,initcwndbps,ratebypass,mime,otfp,otf,lmt/'
[dashsegments] Total fragments: 32
[download] Destination: TESTIMONIALS sammeln - So geht's!-WjLvuf2fOX4.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
ERROR: giving up after 10 fragment retries
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/downloader/dash.py", line 45, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "./youtube-dl/youtube_dl/downloader/fragment.py", line 97, in _download_fragment
    'http_headers': headers or info_dict.get('http_headers'),
  File "./youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "./youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2166, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

**Comment by dstftw** [comment]
133 is not available on Youtube side for this video.
