### ISSUE TITLE
Need help regading the TEMP path

### ISSUE THREAD

**Issue by hashmachine07** [rg3/youtube-dl#13866]
Hi,
This is not really issue with the tool. Need help regarding the TEMP configuration.
Recently found that 'ffmpeg' entry in the TEMP path is affecting my NODE & NPM and had to remove it .  Is there any way I can reconfigure Youtube-dl, so both Youtube-dl and NPM doesn't get affected.

Thanks!

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient
