### ISSUE TITLE
Unable to download JSON metadata - Foodnetwork.ca

### ISSUE THREAD

**Issue by level42ca** [rg3/youtube-dl#13879]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[~] # youtube-dl http://www.foodnetwork.ca/shows/unique-sweets/video/episode/deep-freeze/video.html?v=992883779587
[debug] System config: []
[debug] User config: [u'-o', u'/share/MD0_DATA/Torrents/YouTube-DL/%(title)s.%(ext)s', u'-v', u'--ap-mso', u'Rogers', u'--netrc']
[debug] Custom config: []
[debug] Command-line args: [u'http://www.foodnetwork.ca/shows/unique-sweets/video/episode/deep-freeze/video.html?v=992883779587']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.09
[debug] Python version 2.7.5 - Linux-4.2.8-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 2.8.5
[debug] Proxy map: {}
[Corus] 992883779587: Downloading JSON metadata
ERROR: Unable to download JSON metadata: [Errno 8] _ssl.c:1363: EOF occurred in violation of protocol (caused by SSLError(8, '_ssl.c:1363: EOF occurred in violation of protocol')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2166, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/root/daily_build/64_22/4.3.3/SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/urllib2.py", line 410, in open
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 974, in http_response
    content = resp.read()
  File "/root/daily_build/64_22/4.3.3/SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/socket.py", line 351, in read
  File "/root/daily_build/64_22/4.3.3/SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/httplib.py", line 567, in read
  File "/root/daily_build/64_22/4.3.3/SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/socket.py", line 380, in read
  File "/root/daily_build/64_22/4.3.3/SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/ssl.py", line 241, in recv
  File "/root/daily_build/64_22/4.3.3/SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/ssl.py", line 160, in read
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.
```
-Single video: http://www.foodnetwork.ca/shows/unique-sweets/video/episode/deep-freeze/video.html?v=992883779587
```
---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.
```
I have youtube-dl running on my QNAP, I've setup the user config file, and the netrc file.
```

**Comment by dstftw** [comment]
Outdated python.

**Comment by level42ca** [comment]
Thanks, I'll see about updating it :)

**Comment by siddht4** [comment]
You need python2.7 which can be directly run as 'python youtube-dl'. Based on your log, YouTube-dl failed to establish the SSL connection with the server

**Comment by level42ca** [comment]
Thanks for the help, I was able to update Python, and all is well.
