### ISSUE TITLE
[NBCSportsVPlayer] ERROR: no suitable InfoExtractor for URL 

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#13873]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl.py -v "http://vplayer.nbcsports.com/p/BxmELC/chicago_embed/select/media/u4xMi3ngFKsS"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://vplayer.nbcsports.com/p/BxmELC/chicago_embed/select/media/u4xMi3ngFKsS']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.08.09
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[NBCSportsVPlayer] u4xMi3ngFKsS: Downloading webpage
ERROR: no suitable InfoExtractor for URL https://vplayer.nbcsports.com/p/BxmELC/chicago_embed/swf/select/media/u4xMi3ngFKsS&autoPlay=true
  File "C:\Program Files\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Transmogrifier\youtube-dl.py\__main__.py", line 19, in <module>
    youtube_dl.main()
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 465, in main
    _real_main(argv)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1956, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 848, in process_ie_result
    extra_info=extra_info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 810, in extract_info
    self.report_error('no suitable InfoExtractor for URL %s' % url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 604, in report_error
    self.trouble(error_message, tb)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 566, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://vplayer.nbcsports.com/p/BxmELC/chicago_embed/select/media/u4xMi3ngFKsS

---

Thanks
Ringo

**Comment by chancemimi** [comment]
nbc.com is no longer supported either

**Comment by parmjitv** [comment]
Gentlemen,

@RingoTheDog - The video in question references a new domain in the source file.  I will push up a new PR with a fix in place for the extractor shortly.

@chancemimi - Can you please provide an example URL that does not work on the nbc.com domain?

Cheers,

Parmjit V.
