### ISSUE TITLE
ratelimit option have not been parsed in FileDownloader

### ISSUE THREAD

**Issue by char101** [rg3/youtube-dl#13875]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.09**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

In https://github.com/rg3/youtube-dl/blob/master/youtube_dl/downloader/common.py#L176, `rate_limit` is still str and need to be parsed first.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/downloader/common.py#L34
