### ISSUE TITLE
error when i play a youtube video with mpv

### ISSUE THREAD

**Issue by Joseph65** [rg3/youtube-dl#13872]
i just downloaded version 2017.08.09
and i get this error when i play a video with mpv
i noticed the error are from youtube-dl and not mpv
~$ mpv https://www.youtube.com/watch?v=SZsAc4triPY
Playing: https://www.youtube.com/watch?v=SZsAc4triPY
[ytdl_hook] 
[ytdl_hook] stack traceback:
[ytdl_hook] 	[C]: in function 'len'
[ytdl_hook] 	@ytdl_hook.lua:71: in function 'edl_escape'
[ytdl_hook] 	@ytdl_hook.lua:139: in function 'edl_track_joined'
[ytdl_hook] 	@ytdl_hook.lua:171: in function 'add_single_video'
[ytdl_hook] 	@ytdl_hook.lua:454: in function 'fn'
[ytdl_hook] 	mp.defaults:518: in function 'handler'
[ytdl_hook] 	mp.defaults:339: in function 'handler'
[ytdl_hook] 	mp.defaults:458: in function 'call_event_handlers'
[ytdl_hook] 	mp.defaults:495: in function 'dispatch_events'
[ytdl_hook] 	mp.defaults:451: in function <mp.defaults:450>
[ytdl_hook] 	[C]: in ?
[ytdl_hook] 	[C]: in ?
[ytdl_hook] Lua error: @ytdl_hook.lua:71: bad argument #1 to 'len' (string expected, got nil)
[ffmpeg] tls: The TLS connection was non-properly terminated.
Failed to recognize file format.

Exiting... (Errors when loading file)

**Comment by dstftw** [comment]
mpv issues should be reported to mpv.

**Comment by aporakk** [comment]
Confirm it can be reproduced with older versions of mpv as well. Curious
