### ISSUE TITLE
Youtube-dl not download format 22

### ISSUE THREAD

**Issue by bumbadabum** [rg3/youtube-dl#13878]
When i run youtube-dl.exe -f 22 "url" download 720p video with 128k audio. But the description indicates that the format 22 contains 192k audio. Why?!

**Comment by dstftw** [comment]
Cause it's a hardcoded value that may not correspond to a real bitrate.

**Comment by bumbadabum** [comment]
All videos from youtube have this format 22 with 192k audio, but when download have audio AAC 128k. I think at this time Youtube no longer allows you to download video with audio more than AAC 128k. Maybe i'm wrong?

**Comment by siddht4** [comment]
can you print your log too, `youtube-dl [url] -F -v`

**Comment by bumbadabum** [comment]
youtube-dl.exe -F -v https://www.youtube.com/watch?v=pgJFUW3VenY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://www.youtube.com/watch?v=pgJFUW3VenY']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.08.09
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] pgJFUW3VenY: Downloading webpage
[youtube] pgJFUW3VenY: Downloading video info webpage
[youtube] pgJFUW3VenY: Extracting video information
[youtube] {22} signature length 43.41, html5 player vflmw6aFG
[youtube] pgJFUW3VenY: Downloading player https://www.youtube.com/yts/jsbin/player-vflmw6aFG/en_US/base.js
[youtube] {43} signature length 43.41, html5 player vflmw6aFG
[youtube] {18} signature length 43.41, html5 player vflmw6aFG
[youtube] {36} signature length 43.41, html5 player vflmw6aFG
[youtube] {17} signature length 43.41, html5 player vflmw6aFG
[youtube] {137} signature length 43.41, html5 player vflmw6aFG
[youtube] {248} signature length 43.41, html5 player vflmw6aFG
[youtube] {136} signature length 43.41, html5 player vflmw6aFG
[youtube] {247} signature length 43.41, html5 player vflmw6aFG
[youtube] {135} signature length 43.41, html5 player vflmw6aFG
[youtube] {244} signature length 43.41, html5 player vflmw6aFG
[youtube] {134} signature length 43.41, html5 player vflmw6aFG
[youtube] {243} signature length 43.41, html5 player vflmw6aFG
[youtube] {133} signature length 43.41, html5 player vflmw6aFG
[youtube] {242} signature length 43.41, html5 player vflmw6aFG
[youtube] {160} signature length 43.41, html5 player vflmw6aFG
[youtube] {278} signature length 43.41, html5 player vflmw6aFG
[youtube] {140} signature length 43.41, html5 player vflmw6aFG
[youtube] {171} signature length 43.41, html5 player vflmw6aFG
[youtube] {249} signature length 43.41, html5 player vflmw6aFG
[youtube] {250} signature length 43.41, html5 player vflmw6aFG
[youtube] {251} signature length 43.41, html5 player vflmw6aFG
[youtube] pgJFUW3VenY: Downloading MPD manifest
[info] Available formats for pgJFUW3VenY:
format code  extension  resolution note
139          m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.5@ 48k (22050Hz), 1.37MiB
249          webm       audio only DASH audio   52k , opus @ 50k, 1.43MiB
250          webm       audio only DASH audio   70k , opus @ 70k, 1.88MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k (44100Hz), 3.65MiB
251          webm       audio only DASH audio  140k , opus @160k, 3.74MiB
171          webm       audio only DASH audio  142k , vorbis@128k, 3.70MiB
278          webm       256x144    144p  106k , webm container, vp9, 12fps, video only, 2.55MiB
160          mp4        256x144    DASH video  111k , avc1.42c00c, 12fps, video only, 3.14MiB
242          webm       426x240    240p  226k , vp9, 24fps, video only, 4.69MiB
133          mp4        426x240    DASH video  249k , avc1.4d4015, 24fps, video only, 7.05MiB
134          mp4        640x360    DASH video  400k , avc1.4d401e, 24fps, video only, 7.98MiB
243          webm       640x360    360p  413k , vp9, 24fps, video only, 8.12MiB
244          webm       854x480    480p  682k , vp9, 24fps, video only, 12.91MiB
135          mp4        854x480    DASH video  780k , avc1.4d401e, 24fps, video only, 15.51MiB
247          webm       1280x720   720p 1234k , vp9, 24fps, video only, 23.43MiB
136          mp4        1280x720   DASH video 1425k , avc1.4d401f, 24fps, video only, 29.65MiB
248          webm       1920x1080  1080p 2131k , vp9, 24fps, video only, 41.71MiB
137          mp4        1920x1080  DASH video 2556k , avc1.640028, 24fps, video only, 55.72MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)

**Comment by siddht4** [comment]
and the format that was downloaded. Check its codec information
