### ISSUE TITLE
Youtube user repeatedly times out

### ISSUE THREAD

**Issue by doguitar** [rg3/youtube-dl#1388]
Timeouts occur at different points in the process but always after 5 or 6 requests.

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.youtube.com/user/KingsVision', '-o', '/data/kingsvision/%(upload_date)s-%(title)s.%(ext)s', '--prefer-free-formats', '-w', '-x', '--max-downloads', '10', '--no-post-overwrites', '--verbose']
[debug] youtube-dl version 2013.09.06.1
[debug] Python version 2.7.4 - Linux-3.8.0-29-generic-x86_64-with-Ubuntu-13.04-raring
[debug] Proxy map: {}
[youtube:user] KingsVision: Downloading video ids from 1 to 51
[youtube:user] KingsVision: Downloading video ids from 51 to 101
[youtube:user] KingsVision: Downloading video ids from 101 to 151
[youtube:user] KingsVision: Downloading video ids from 151 to 201
[youtube:user] KingsVision: Downloading video ids from 201 to 251
[youtube:user] KingsVision: Downloading video ids from 251 to 301
[youtube:user] KingsVision: Downloading video ids from 301 to 351
[youtube:user] KingsVision: Downloading video ids from 351 to 401
[youtube:user] KingsVision: Downloading video ids from 401 to 451
[youtube:user] KingsVision: Downloading video ids from 451 to 501
[youtube:user] KingsVision: Downloading video ids from 501 to 551
[youtube:user] KingsVision: Downloading video ids from 551 to 601
[youtube:user] KingsVision: Downloading video ids from 601 to 651
[youtube:user] KingsVision: Downloading video ids from 651 to 701
[youtube:user] KingsVision: Downloading video ids from 701 to 751
[youtube:user] KingsVision: Downloading video ids from 751 to 801
[youtube:user] KingsVision: Downloading video ids from 801 to 851
[youtube:user] KingsVision: Downloading video ids from 851 to 901
[youtube:user] KingsVision: Downloading video ids from 901 to 951
[youtube:user] KingsVision: Downloading video ids from 951 to 1001
[download] Downloading playlist: KingsVision
[youtube:user] playlist 'KingsVision': Collected 956 video ids (downloading 956 of them)
[download] Downloading video #1 of 956
[youtube] Setting language
[youtube] t1DwV_-JDyI: Downloading video webpage
ERROR: Unable to download video webpage: The read operation timed out; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 665, in _real_extract
    video_webpage_bytes = compat_urllib_request.urlopen(request).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 632, in http_response
    content = resp.read()
  File "/usr/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 543, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 603, in _read_chunked
    value.append(self._safe_read(amt))
  File "/usr/lib/python2.7/httplib.py", line 658, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 298, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 217, in read
    return self._sslobj.read(len)
SSLError: The read operation timed out
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 324, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 103, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 667, in _real_extract
    raise ExtractorError(u'Unable to download video webpage: %s' % compat_str(err))
ExtractorError: Unable to download video webpage: The read operation timed out; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by sehrgut** [comment]
Duplicates #4240, which causes recoverable SSLError to be treated as fatal.
