### ISSUE TITLE
Aparat Downloads Lowest Res by Default

### ISSUE THREAD

**Issue by dkl3** [rg3/youtube-dl#13887]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.09**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

$ youtube-dl http://www.aparat.com/v/XeL6n -v                 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.aparat.com/v/XeL6n', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.09
[debug] Python version 3.4.5 - Linux-3.10.0-514.26.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[Aparat] XeL6n: Downloading webpage
[Aparat] XeL6n: Testing video URL 0
WARNING: unable to extract isFamilyFriendly; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://as6.cdn.asset.aparat.com/aparat-video/04905cf4a6e499c617161464d1f11f997736172-144p__81483.apt?direct=1'
[download] Destination: Nintendo 64 U.S. Unveiling @ E3 &#039;96  in  Los Angeles, California-XeL6n.mp4
[download] 100% of 15.36MiB in 00:03

---
### Description of your *issue*, suggested solution and other information

Hello, third GitHub issue, but anyway. Aparat downloads by the lowest res (144p) by default,and i want to, let's say, get the highest resolution available. Here's an example video:

http://www.aparat.com/v/XeL6n

Thanks.

**Comment by dkl3** [comment]
whoops realized youtube-dl was outdatted--sorry--i edited the log

**Comment by amkyp** [comment]
I was supposed to open this issue one more time because it's not working.

I've Already described the problem via a comment on the merged code.
[https://github.com/ytdl-org/youtube-dl/commit/70851a95c307880f016fcb6f37427a8eeae73cad#commitcomment-39029171](here is the link)

**Comment by amkyp** [comment]
@dstftw 
I Found that Aparat isn't working correctly but someone has changed it a bit to work, you can the code below.
https://raw.githubusercontent.com/HanifBirgani/youtube-dl/fix/aparat/youtube_dl/extractor/aparat.py
