### ISSUE TITLE
VidLii support

### ISSUE THREAD

**Issue by dkl3** [rg3/youtube-dl#13883]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.09**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

youtube-dl https://www.vidlii.com/watch?v=Lq15kZRyd7a -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.vidlii.com/watch?v=Lq15kZRyd7a', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.09
[debug] Python version 3.4.5 - Linux-3.10.0-514.26.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[generic] watch?v=Lq15kZRyd7a: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=Lq15kZRyd7a: Downloading webpage
[generic] watch?v=Lq15kZRyd7a: Extracting information
[generic] watch?v=Lq15kZRyd7a: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://cdn.vidlii.com/videos/Lq15kZRyd7a.mp4'
[download] Destination: RE - Vidlii Time Capsule - Submit Vidlii Screenshots and Videos! august 11 2017 - VidLii-watchv=Lq15kZRyd7a.mp4
[download] 100% of 1.58MiB in 00:01

---

### Description of your *issue*, suggested solution and other information

Hello, so download for VidLii does work but it is registered as generic. Someone add support please?  I don't think it gets the info.json either. Thanks.

**Comment by dkl3** [comment]
Updated to 2017.08.09 and retried from there, sorry about that

**Comment by dstftw** [comment]
`--write-info-json`.

**Comment by dkl3** [comment]
What do you mean?

**Comment by svnpenn** [comment]
https://github.com/rg3/youtube-dl/issues/14472

**Comment by svnpenn** [comment]
https://github.com/rg3/youtube-dl/pull/14512

**Comment by svnpenn** [comment]
https://github.com/rg3/youtube-dl/pull/14779
