### ISSUE TITLE
Customizing YouTube-DL installation (QNAP - Linux)

### ISSUE THREAD

**Issue by level42ca** [rg3/youtube-dl#13881]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.09**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I've been trying to install YouTube-DL to run from my QNAP, and I've been successful at doing so despite my limited Linux knowledge. However, it seems that where YouTube-DL gets isntalled to by default, with regards to QNAP specifically, wont work. As common directories such as **/root/** and **/usr/local/bin** get reset whenever the system reboots.

My question is, is there a way for us to customize the installation location, and the default paths for things like **config**, **youtube-dl.conf**, and **.netrc** among other things?

I'd wager that this is quite possible, but ideally, I'd like to stray as far away from modifying youtube-dl source as possible, to prevent having to redo changes each time youtube-dl is updated. Would be nice if there was a youtube-dl config file that would house these paths and defaults, that would simply be located parallel to the executable.

Just my thoughts/questions. Thanks!

**Comment by dstftw** [comment]
You can install it where ever you want. You can't customize config locations other that [default](https://github.com/rg3/youtube-dl#configuration). Same for [.netrc](https://github.com/rg3/youtube-dl#authentication-with-netrc-file). You can specify config location from command line `--config-location`.
