### ISSUE TITLE
Feature Request: Command Line switch to force specific extractor

### ISSUE THREAD

**Issue by Wowfunhappy** [rg3/youtube-dl#13891]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Sometimes, youtube-dl fails to download a video which would normally be supported because it does not recognize the URL and falls back on the generic extractor. Although youtube-dl already has a `--force-generic-extractor ` switch, users cannot force a specific extractor other than the generic one.

I'd appreciate a command line switch such as `--force-extractor <extractor>`. This would allow me to work around #13890 by adding `--force-extractor cbs.com` to the command line, and would allow users to work around similar problems in the future.

**Comment by dstftw** [comment]
Forcing concrete extractors is impossible and does not make any sense since each concrete extractor is bound to concrete URL pattern.

**Comment by romanrm** [comment]
Sometimes the domain name varies, but the URL pattern stays the same. I really hope this can be implemented after all.

**Comment by markshep** [comment]
I too would like this feature.  The particular example I have in mind is for the "Wistia" extractor.  Because they provide the underlying streaming technology to many different customers each using their own domain names we need some way of telling youtube-dl to use that extractor.

**Comment by liling198658** [comment]
Please add this feature!
