### ISSUE TITLE
Feature request: Have option to create playlist folder

### ISSUE THREAD

**Issue by suntong** [rg3/youtube-dl#13903]
## Please follow the guide below

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.13*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

> Explanation of your *issue* in arbitrary form goes here. 

There are occasions when creating a folder for the playlist and put everything down within it is desirable. For e.g., take a look at this site:

https://www.youtube.com/user/SoccerCoachTV/playlists

I want to download all of them, but I'd like to arrange the downloaded videos according to the playlist. I.e., when I download the playlist, I need to have all the downloaded videos be put within a sub-folder, named according to the name of playlist. E.g., for the above site, they would be

- Warm Up Drills and Games
- Defending Drills and Games
- Passing and Possession Games
- Shooting Drills and Games

Of course, the playlists are downloaded one at a time, thus the folders are created one at a time as well. 

Please consider.  
Thx.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#output-template
