### ISSUE TITLE
Pornhub date and uploader's username issues

### ISSUE THREAD

**Issue by arisboch** [rg3/youtube-dl#13906]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.13*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.13**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
The program doesn't recognize the video upload date or the uploader's username and maybe other stuff.

Example URLs (warning, NSFW, lol):
https://www.pornhub.com/view_video.php?viewkey=ph56940e86a653a
https://www.pornhub.com/view_video.php?viewkey=ph56c4c63310af0
https://www.pornhub.com/view_video.php?viewkey=ph5676caec66fb0

**Comment by dstftw** [comment]
No explicit upload date is provided by the website.
