### ISSUE TITLE
[twitch.tv] no video when outputing a live stream in mplayer, cannot list current game live streams

### ISSUE THREAD

**Issue by sylware** [rg3/youtube-dl#13918]
When I pipe a twitch stream in mplayer, I get only the sound (ffmpeg 3.3).
It seems I cannot get the list of live streams for a specific game.
Is there a way to get the ads in order to support the streamer?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by sylware** [comment]
found out what was wrong, I write it here for the record:
_do_ compile ffmpeg with _all_ internal muxers/encoders/etc or you will miss very important modules allowing ffmpeg to handle properly twitch streams (no, you won't be able to guess them).
