### ISSUE TITLE
Feature - Parallel download for playlist

### ISSUE THREAD

**Issue by hkusulja** [rg3/youtube-dl#13910]
Feature request for YouTube playlists processing - ability to download multiple at parallel

Example call:
> youtube-dl.exe --extract-audio --audio-format mp3 -f bestaudio --ignore-errors -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" "https://www.youtube.com/channel/UCw39ZmFGboKvrHv4n6LviCA/videos" **-parallel-downloads 4**

**Comment by hkusulja** [comment]
Duplicate with which issue / link please? Thank you

**Comment by yan12125** [comment]
See #3746
