### ISSUE TITLE
Skip videos depending on license (CC vs youtube std license)

### ISSUE THREAD

**Issue by mnj** [rg3/youtube-dl#13924]
It would be cool, if its even technically possible, to be able to choose to skip downloading any videos that isn't Creative Commons licensed (=legal to download), travel a lot across borders, would be nice to be able to say, all videos downloaded was Creative Commons licensed and legal, it's a bit harder to defend videos with youtube's std. license to nosy border agents.

The main problem arises as some youtubers have a mix of CC and Youtube std. licensed videos mixed together on their feeds.

**Comment by mnj** [comment]
As a follow up, --match-filter FILTER, is supposed to be able to do it from what I can see, but if I dump the OPTIONS with --print-json, there is no license variable available.

**Comment by mnj** [comment]
Ok turns out I'm an idiot :(

--match-filter "license='Creative Commons Attribution license (reuse allowed)'"

Works as intended, even though it wasn't listed in --print-json

**Comment by vigneshmj1997** [comment]
its not working for me
The Shine - Jahzzar | Creative Common Music  ¡Download for your video! does not pass filter license='Creative Commons Attribution license (reuse allowed)', skipping ..
i am sure this is creative common video
