### ISSUE TITLE
[bandcamp] wrong title for albums, programming help

### ISSUE THREAD

**Issue by steebchen** [rg3/youtube-dl#13927]
## Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.13*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Bandcamp titles are not extracted in albums, e.g. http://music.businesscasual.biz/album/--8 only extracts the URLs. I want to extract the title but am not sure how to do it.

On this line:
https://github.com/rg3/youtube-dl/blob/485047854376465f95309daad4966971f56728ef/youtube_dl/extractor/bandcamp.py#L245
the div with the title is extracted already. I thought about using _html_search_meta, but it seems it only searches for the `content` attribute and not the actual `innerText` of the element – I'd like to extract it from the `itemprop="name"` selector.

bandcamp html:
![selection_103](https://user-images.githubusercontent.com/5013932/29351767-fd567846-8218-11e7-8ee7-9bbeedccafa6.png)

Is there another way to do this or do I need to extend the beautiful RegExp (still missing a proper HTML parser instead of using RegExp for this...)?

**Comment by dstftw** [comment]
`_search_regex`.
