### ISSUE TITLE
error when i try to download 

### ISSUE THREAD

**Issue by DRAKUN** [rg3/youtube-dl#13936]
ERROR: Unable to download webpage: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)> (caused by URLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)'),))
(env_py3) pc125:env_py3 drakun$

(env_py3) pc125:env_py3 drakun$ openssl version
OpenSSL 1.0.2l  25 May 2017
(env_py3) pc125:env_py3 drakun$

and python use the last version openssl
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.2k  26 Jan 2017'
>>>

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
