### ISSUE TITLE
urlopen error _ssl.c:584: The handshake operation timed out

### ISSUE THREAD

**Issue by Belthazor4011** [rg3/youtube-dl#13947]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.13*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
D:\>youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 -o "%(title)s.%(ext)s" -i "https://www.youtube.com/channel/UC5nc_ZtjKW1htCVZVRxlQAQ" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', '-o', '%(title)s.%(ext)s', '-i', 'https://www.youtube.com/channel/UC5nc_ZtjKW1htCVZVRxlQAQ', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.08.13
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86977-g5859b5b, ffprobe N-86977-g5859b5b
[debug] Proxy map: {}
[youtube:channel] UC5nc_ZtjKW1htCVZVRxlQAQ: Downloading channel page
[youtube:playlist] UU5nc_ZtjKW1htCVZVRxlQAQ: Downloading webpage
[download] Downloading playlist: Uploads from MrSuicideSheep
[youtube:playlist] UU5nc_ZtjKW1htCVZVRxlQAQ: Downloading page #1
[youtube:playlist] UU5nc_ZtjKW1htCVZVRxlQAQ: Downloading page #2
ERROR: Unable to download JSON metadata: <urlopen error _ssl.c:584: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:584: The handshake operation timed out',),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc3a66tbr\build\youtube_dl\extractor\common.py", line 502, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc3a66tbr\build\youtube_dl\YoutubeDL.py", line 2166, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc3a66tbr\build\youtube_dl\utils.py", line 1086, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Same error keeps coming up, Ive tried on different days and on different times off the day. Sometimes it goes wrong on page #2 sometimes page #7, where it goes wrong seems to be random. Also it takes a good 5 minutes for it to time out and create the error. No sure whats going on.

**Comment by dstftw** [comment]
Most likely an issue with your network connection.
