### ISSUE TITLE
vshare.io https

### ISSUE THREAD

**Issue by votegreen** [rg3/youtube-dl#13941]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.13*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [x] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vshare.io/d/0f64ce6', '--ignore-config', '-v', '--get-url']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.08.13
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-86950-g1bef008, ffprobe N-86950-g1bef008, rtmpdump 2.3
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
http://s896.vshare.io/download,9999999999999999999999999999999999999999-86467b2ee330624a5ba1c221c3ddd242,599685e5,0f64ce6.mp4
```

---

https://vshare.io/d/0f64ce6
>http://s896.vshare.io/download,9999999999999999999999999999999999999999-86467b2ee330624a5ba1c221c3ddd242,599685e5,0f64ce6.mp4

When downloading from vshare.io, the extractor finds the link to the file, as shown above - this is correct and works well... However the url (provided by vshare) uses http://. https:// is enabled and works to download the file.

- As https:// works, should it be preferred over http://?

- How can this be implemented in youtube-dl? Is simply substituting http:// with https:// in the url acceptable?

[edit] like this...
https://github.com/rg3/youtube-dl/compare/master...votegreen:master (I'm new to this)
youtube_dl/extractor/vshare.py
```
import re
...
        video_url = re.sub(r'http://', r'https://', self._search_regex(
            r'<a[^>]+href=(["\'])(?P<url>(?:https?:)?//.+?)\1[^>]*>[Cc]lick\s+here', 
            webpage, 'video url', group='url'))
```

**Comment by dstftw** [comment]
Original download URLs should not be touched.
