### ISSUE TITLE
Download Pluralsight transcripts from the transcript tab instead of accessing all videos

### ISSUE THREAD

**Issue by eddeyang** [rg3/youtube-dl#13955]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

Currently when I'm downloading transcripts from a course from www.pluralsight.com, it seems youtube-dl download them from individual video pages. youtube-dl needs to access all videos of a course in order to download them. After downloaded them, the whole course is marked as watched. However, on the course page there is a tab called "transcript" that include all the transcripts of the couse (for all videos). Is it possible to download transcripts from this page so that it more performant and doesn't need to mark all videos as watched?

**Comment by dstftw** [comment]
>tab called "transcript" that include all the transcripts of the couse (for all videos)

Contains only first video.

**Comment by eddeyang** [comment]
Oh that's not true. I tried on several courses and all of them include all transcripts in the "transcript" tab. I captured a snapshot, see this http://imgur.com/a/KOCHP

**Comment by shanyuen** [comment]
you can use --write-sub  --skip-download parameter on playlist page, then it will download subtitles without video files.
Make sure you limit 2 minutes per session, or your account will be freezed for several days.
