### ISSUE TITLE
Pluralsight not working - HTTP 429

### ISSUE THREAD

**Issue by luizconrado** [rg3/youtube-dl#13953]
Sir, I am not blocked from Pluralsight.
I can login, watch videos and even download to my mobile devices.
I really can. Is there a way I can show you that?

If you don't reply it is ok, I won't bug you anymore. I am just a proud user of your solution that even has donated already.

The error shows up when trying to download the JSON, not when loggin in.
Is there a way I can help you somehow?

Thanks for your effort.

**Comment by dstftw** [comment]
You can only prove by provide account credentials.

**Comment by luizconrado** [comment]
Sure,

--username lfconrado.spam@gmail.com --password RakutenEUBI2016!

Thanks

2017-08-17 20:45 GMT+02:00 Sergey M. <notifications@github.com>:

**Comment by luizconrado** [comment]
Could you make this thread private, please:)
Thanks:
Here are the credentials again:
--username 
lfconrado.spam@gmail.com

--password 
RakutenEUBI2016!

**Comment by dstftw** [comment]
There is no such thing as private thread. You've already posted in public forum.

**Comment by luizconrado** [comment]
Ok,
Let me know once you have tested it - I will remove the credentials at least.
Thanks again.

**Comment by dstftw** [comment]
```
PS C:\dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py https://app.pluralsight.com/library/courses/java-fundamentals-exception-handling -u <snip> -p <snip> -F
[pluralsight:course] java-fundamentals-exception-handling: Downloading course JSON
[download] Downloading playlist: Java Fundamentals: Exception Handling
[pluralsight:course] playlist Java Fundamentals: Exception Handling: Collected 42 video ids (downloading 42 of them)
[download] Downloading video 1 of 42
[pluralsight] Downloading login page
[pluralsight] Logging in as lfconrado.spam@gmail.com
[pluralsight] 362177de-e9be-442e-a266-01cb2498370d-0: Downloading course JSON
[pluralsight] 362177de-e9be-442e-a266-01cb2498370d-0: Downloading webm-high viewclip JSON
[pluralsight] 362177de-e9be-442e-a266-01cb2498370d-0: Waiting for 5 seconds to avoid throttling
[pluralsight] 362177de-e9be-442e-a266-01cb2498370d-0: Downloading webm-high-widescreen viewclip JSON
[pluralsight] 362177de-e9be-442e-a266-01cb2498370d-0: Waiting for 2 seconds to avoid throttling
ERROR: Interrupted by user
```
So, as said your IP is most likely blocked.

**Comment by dstftw** [comment]
You must change password. Everybody who receives GitHub notifications already have them.

**Comment by luizconrado** [comment]
My IP? Not Account? That's great news. I will change my IP here and try it again. What version are you using?

**Comment by luizconrado** [comment]
Version of you program I mean... the 2017.08.13 or the one you just released?

**Comment by dstftw** [comment]
Latest.

**Comment by luizconrado** [comment]
Thank you very much, I will try it now. Thanks.

**Comment by luizconrado** [comment]
@dstftw - It worked fine. Thank you.
One last thing:
Could you please remove my email from the debug message you wrote?
PS C:\dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py https://app.pluralsight.com/library/courses/java-fundamentals-exception-handling -u <snip> -p <snip> -F
[pluralsight:course] java-fundamentals-exception-handling: Downloading course JSON
[download] Downloading playlist: Java Fundamentals: Exception Handling
[pluralsight:course] playlist Java Fundamentals: Exception Handling: Collected 42 video ids (downloading 42 of them)
[download] Downloading video 1 of 42
[pluralsight] Downloading login page
[pluralsight] Logging in as **lfconrado.spam@gmail.com**
[pluralsight] 362177de-e9be-442e-a266-01cb2498370d-0: Downloading course JSON
[pluralsight] 362177de-e9be-442e-a266-01cb2498370d-0: Downloading webm-high viewclip JSON
[pluralsight] 362177de-e9be-442e-a266-01cb2498370d-0: Waiting for 5 seconds to avoid throttling
[pluralsight] 362177de-e9be-442e-a266-01cb2498370d-0: Downloading webm-high-widescreen viewclip JSON
[pluralsight] 362177de-e9be-442e-a266-01cb2498370d-0: Waiting for 2 seconds to avoid throttling
ERROR: Interrupted by user
