### ISSUE TITLE
Youtube - SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by codecodingcode** [rg3/youtube-dl#13957]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.18**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\z\apps\mpv-x86_64>youtube-dl.exe -v https://www.youtube.com/watch?v=edfK-xzryv4
[debug] System config: []
[debug] User config: ['--no-call-home', '--all-subs', '--add-metadata', '--write-description', '--format', 'bestvideo[height<=?720]+bestaudio/best', '--output', 'D:\\d\\down\\(_mv\\(_ytdl\\[%(extractor)s %(id)s] %(title)s.%(ext)s', '--user-agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0', '--ffmpeg-location', 'C:\\z\\apps\\ffmpeg\\bin', '--prefer-ffmpeg', '--external-downloader', 'aria2c.exe', '--external-downloader-args', '--conf-path=aria2.conf']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=edfK-xzryv4']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.08.18
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.3.1, ffprobe 3.3.1
[debug] Proxy map: {}
[youtube] edfK-xzryv4: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmput9or0a0\build\youtube_dl\extractor\common.py", line 502, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmput9or0a0\build\youtube_dl\YoutubeDL.py", line 2168, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmput9or0a0\build\youtube_dl\utils.py", line 1086, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Can't download from Youtube, works perfectly for other sites.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/11573#issuecomment-269896421

**Comment by Robby-** [comment]
So, I'm having this issue too and I'm curious as to why for example other applications that use the Windows certificate store, such as Internet Explorer, can load the YouTube website fine, even if there are expired certificates present in the store. Why can't youtube-dl do it too?

I had a look in my certificate store as per the linked instructions, and there is only one root certificate that is expired. It is named `Google Internet Authority G2` with an expiration date of `2017/01/01`. That certificate expired almost 10 months ago. Looking at this date, I can't help but wondering why did this just now become a problem? Instead of deleting the expired certificate I edited its properties and selected `Disable all purposes for this certificate` and this has fixed the issue for me.

So can you please elaborate on why this only started to happen now and not 10 months ago? This is so weird and I want to understand this.

I am using Windows 7 SP1 x64, and youtube-dl 2017.09.24.

**Comment by Hrxn** [comment]
And when exactly did it start to happen?

**Comment by Robby-** [comment]
I cannot tell you an exact date, as I don't use youtube-dl every day, only from time to time. I only noticed this for the first time earlier today. But, it didn't happen two weeks ago, that's for sure.
