### ISSUE TITLE
Pluralsight not working - HTTP 429 (Too many Requests)

### ISSUE THREAD

**Issue by luizconrado** [rg3/youtube-dl#13952]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Since yesterday around 21:30 (UTC) Pluralsight is giving a constant error:
ERROR: Unable to download JSON metadata: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug

Is there any reason for that? Can I do something to help?
It is very important for me to have this fixed.

Log:
C:\abc\youtube-dl --username abc@gmail.com --password abc! --rate-limit 512K --verbose --sleep-interval 150 -o "Pluralsight - %(playlist)s - %(release_date)s\%(playlist_index)s - %(title)s.%(ext)s" --all-subs --playlist-start 1   https://app.pluralsight.com/library/courses/java-fundamentals-exception-handling
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--rate-limit', '512K', '--verbose', '--sleep-interval', '150', '-o', 'Pluralsight - %(playlist)s - %(release_date)s\\%(playlist_index)s - %(title)s.%(ext)s', '--all-subs', '--playlist-start', '1', 'https://app.pluralsight.com/library/courses/java-fundamentals-exception-handling']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.08.18
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] java-fundamentals-exception-handling: Downloading course JSON
[download] Downloading playlist: Java Fundamentals: Exception Handling
[pluralsight:course] playlist Java Fundamentals: Exception Handling: Collected 42 video ids (downloading 42 of them)
[download] Downloading video 1 of 42
[pluralsight] Downloading login page
[pluralsight] Logging in as abc@gmail.com
[pluralsight] 362177de-e9be-442e-a266-01cb2498370d-0: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc3a66tbr\build\youtube_dl\extractor\common.py", line 502, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc3a66tbr\build\youtube_dl\YoutubeDL.py", line 2166, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dstftw** [comment]
You're blocked by pluralsight.

**Comment by luizconrado** [comment]
Sir, I am not blocked from Pluralsight.
I can login, watch videos and even download to my mobile devices.
I really can. Is there a way I can show you that?

If you don't reply it is ok, I won't bug you anymore. I am just a proud
user of your solution that even has donated already.

The error shows up when trying to download the JSON, not when loggin in.
Is there a way I can help you somehow?

Thanks for your effort.

2017-08-17 20:35 GMT+02:00 Sergey M. <notifications@github.com>:

**Comment by pskmsc** [comment]
Hello,

I got exactly the same issue.
My account is not locked.

Regards

**Comment by rusvid** [comment]
I got the same error: ERROR: Unable to download JSON metadata: HTTP Error 429: Too Many Requests.
My account is not blocked. I'm able to view the course in a web-browser and in the mobile app. In fact, this error is returned on the first request:
`POST /player/functions/rpc HTTP/1.1
Host: app.pluralsight.com/player/functions/rpc
Content-Length: 83
Accept-Language: en-us,en;q=0.5
Referer: https://app.pluralsight.com/library/courses/your-course-id
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Content-Type: application/json;charset=utf-8
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Connection: close

{"payload": {"courseId": "your-course-id"}, "fn": "bootstrapPlayer"}
`
