### ISSUE TITLE
what does '--no-mtime' mean in youtube-dl and don't think youtube-dl respects that. 

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#13966]
## Please follow the guide below

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

[$] youtube-dl --verbose                                                                                                           
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.18
[debug] Python version 2.7.13 - Linux-4.11.0-1-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.3.3-3, ffprobe 3.3.3-3, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

Now I downloaded the whole playlist from 

youtube-dl https://www.youtube.com/playlist\?list\=PLq6HRovGueR3P8irCLkc9JVKstdmBy4lx -c -f bestvideo+bestaudio

Now while ffmpeg performs and performed flawlessly, the time-stamp it gave to all the videos were from the last 3 days rather than when they were put up originally (youtube's/uploader's time-stamp) .  This wasn't the case before. I'm not sure who is at fault, whether it's youtube-dl at fault or ffmpeg. 

Also I'm curious about the '--no-mtime' option but as the command-line option doesn't elaborate (nor the documentation on youtube-dl homepage) it's difficult to know what that option is all about. 

Looking forward to know.

**Comment by dstftw** [comment]
`--help` clearly states `--no-mtime` will disable setting modification time from `Last-Modified` HTTP header.
```
--no-mtime                       Do not use the Last-modified header to set
                                 the file modification time
```
