### ISSUE TITLE
error 429

### ISSUE THREAD

**Issue by arjungannu** [rg3/youtube-dl#13964]
this is the error i faced when i try to download download a playlist using cookies. i tried verbose and force ipv4 also but it didn't work
ERROR: Unable to download JSON metadata: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
