### ISSUE TITLE
Downloaded rented video but unable to play it

### ISSUE THREAD

**Issue by bkmagnetron** [rg3/youtube-dl#13961]
I downloaded a movie that I rented in YouTube using the following command
```
> youtube-dl.exe -u username -p password https://www.youtube.com/watch?v=s6EXrinPiXI
```
Size of the downloaded content is 2.91GB.

But I can't able to play it.

**Comment by dstftw** [comment]
Rented videos are DRM protected.

**Comment by bkmagnetron** [comment]
Thanks for your replay.
Is that mean 2.91GB content that I downloaded is encrypted?
Do `youtube-dl` be able to detect the DRM video before downloading?
