### ISSUE TITLE
subtitle font, color and size???

### ISSUE THREAD

**Issue by pepeToro** [rg3/youtube-dl#13969]
if there a way to merge the subtitles with different font, font color and size???

im using this command:

--write-sub --embed-subs --sub-lang esLA,esES --merge-output-format mp4

Thanks

**Comment by yan12125** [comment]
You can use hardsubs with subtitles filters of ffmpeg.

**Comment by wanglong167** [comment]
@yan12125  There are examples?

**Comment by yan12125** [comment]
Please check ffmpeg docs. Also, please use IRC for questions. GitHub is for bugs and feature requests only.
