### ISSUE TITLE
ImportError: No module named 'youtube_dl.extractor.lazy_extractors', ... IndentationError

### ISSUE THREAD

**Issue by Meriipu** [rg3/youtube-dl#13973]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ImportError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl===2017.08.18-gentoo-no-offensive-sites', 'console_scripts', 'youtube-dl')()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/extractors.py", line 341
    FourTubeIE,
    ^
IndentationError: unexpected indent

```

---

### Description of your *issue*, suggested solution and other information

commit 903d4d...

```
[I] net-misc/youtube-dl
     Available versions:  2017.03.16 (~)2017.08.13 (~)2017.08.18 (**)99999999 {(+)offensive test PYTHON_TARGETS="python2_7 python3_4 python3_5 python3_6"}
     Installed versions:  99999999(22:59:25 20/08/17)(-offensive -test PYTHON_TARGETS="python2_7 python3_4 python3_5 python3_6")
     Homepage:            https://rg3.github.com/youtube-dl/
     Description:         Download videos from YouTube.com (and more sites...)
```

**Comment by dstftw** [comment]
Report gentoo package bugs to gentoo.

**Comment by Meriipu** [comment]
seems like the offensive use-flag is necessary for now
