### ISSUE TITLE
[YoutubeDL] Download from another machine with a different IP doesn't work.

### ISSUE THREAD

**Issue by barisahmet** [rg3/youtube-dl#13984]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I can't download a generated URL with -g parameter on another computer (with a different IP). But I can download URL's generated by other online generators on different PC.

__Example__: Link generated by youtube-dl using following code;
`youtube-dl -f "mp4" -g https://www.youtube.com/watch?v=xvZqHgFz51I`

__Output__: `https://r5---sn-ab5l6n6s.googlevideo.com/videoplayback?mn=sn-ab5l6n6s&expire=1503367382&mm=31&gcr=us&ipbits=0&ip=185.92.223.123&key=yt6&lmt=1500315296370559&dur=289.552&mv=u&pl=25&mt=1503345660&ms=au&ei=dTybWamNOI2KhAfGl7OgAQ&source=youtube&sparams=dur%2Cei%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mime=video%2Fmp4&id=o-AFthCo2M6zs28lyJSRYN3dHwh1X-Zt_8Rbh8JllVT34B&itag=22&ratebypass=yes&requiressl=yes&signature=96947A07F4E861B1BCB58C40FD8D89C2CE9CE43E.2A0BF8EAF135D18120808511174DE5C687C6268C`

__Result__: This link __doesn't__ work on another PC with a different IP.

__However__, when I generate similar link with some other online conversion tool. the link will be as follows;

__Output__: `http://r5---sn-nv47ln7e.googlevideo.com/videoplayback?sparams=dur,ei,expire,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mip,mm,mn,ms,mv,pl,ratebypass,source&ipbits=0&ip=31.145.111.25&lmt=1500315296370559&itag=22&gcr=tr&ei=3SSbWc_KLMPkcOKgrYgI&id=o-APezT-XXhQnWUVxZP6jTTCYjrNFPvcgROCdTGniBv_O8&ratebypass=yes&key=cms1&pl=22&source=youtube&expire=1503361341&dur=289.552&mime=video%2Fmp4&signature=4BF64991FDE984E809625D1BB8BE6001ED630F54.0B904622F0BFFD496E329EF655CFEDA54B286EF0&title=Future+-+Mask+Off&cms_redirect=yes&mip=85.105.212.37&mm=31&mn=sn-nv47ln7e&ms=au&mt=1503345860&mv=m`

__Result__: This link works on another PC with a different IP. Note the __mip__ parameter on this link, it sends __my__ ip to Google. This link has different values as well, for example __key__ parameter is __cms1__ instead of __yt6__, and it has an extra __cms_redirect=yes__. But I think those parameters changes signatures or something, because it doesn't work when I try to set them on link generated from __youtube-dl__.

Any suggestions?

Thanks.

**Comment by Hrxn** [comment]
And both really result in the same format?

**Comment by barisahmet** [comment]
What do you mean? If you mean file format, yes. Both are MP4.

**Comment by Hrxn** [comment]
Yes, but also same checksum, etc. ?

**Comment by barisahmet** [comment]
Yes, they have same md5 checksum. Just checked it now.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser
