### ISSUE TITLE
Feature Request: Record Errors

### ISSUE THREAD

**Issue by SebiderSushi** [rg3/youtube-dl#13985]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)

---

### Description of your *issue*, suggested solution and other information

I'm using a shellscript to download many videos at once but when it comes to errors I can only choose to ignore them altogether or let youtube-dl break out of my script (as far as I know).
I'd like to have an option to record errors to a file so that I can fix them manually while my script could work without interruptions.

**Comment by dstftw** [comment]
Redirect stderr to file.

**Comment by SebiderSushi** [comment]
Thank you 😅
