### ISSUE TITLE
How to use the --proxy?

### ISSUE THREAD

**Issue by From2750** [rg3/youtube-dl#13989]
how do i use the proxy ? i have the IP for the proxy i want i to use, but dont now how it works?

i have try

youtube-dl --all-subs -proxy:89.236.17.106 URL
youtube-dl --all-subs -proxy 89.236.17.106 URL

**Comment by dstftw** [comment]
`--proxy <proxy_host>:<proxy_port>`.

**Comment by From2750** [comment]
i got a little problem..
i try to only download subs.
youtube-dl --skip-download --write-sub --proxy 89.236.17.106:3128 https://www.viafree.se/program/reality/ex-on-the-beach/sasong-7/avsnitt-1

but i get this warning.
WARNING: [Viafree] avsnitt-1: Failed to parse JSON Expecting ',' delimiter: line 1 column 15915 (char 15914)
[mtg] 852350: Downloading video JSON
[mtg] 852350: Downloading streams JSON
[mtg] 852350: Downloading m3u8 information

i try 
youtube-dl --list-subs --proxy 89.236.17.106:3128 https://www.viafree.se/program/reality/ex-on-the-beach/sasong-7/avsnitt-1

and it's says no subs, but i 99% sure there are subs on this video.
