### ISSUE TITLE
YT Mix playlist, wrong video ID

### ISSUE THREAD

**Issue by anovsiradj** [rg3/youtube-dl#13981]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [x] Other

---

I am trying to download youtube-generated-playlist (mix) - then convert to audio, but failed.

URL: https://www.youtube.com/watch?v=dv13gl0a-FA&list=RDQMUe_cXgPtWx4 (or search "initial d songs" on youtube)

Based on log, the (first video) ID must be `dv13gl0a-FA`, but it is was `Ue_cXgPtWx4` whitch is part of playlist ID `RDQMUe_cXgPtWx4`

my opinion is, there's something wrong with your Regex.

```
anoop@anoop-tux:~/Music$ youtube-dl "https://www.youtube.com/watch?v=dv13gl0a-FA&list=RDQMUe_cXgPtWx4" --extract-audio --verbose --yes-playlist 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=dv13gl0a-FA&list=RDQMUe_cXgPtWx4', u'--extract-audio', u'--verbose', u'--yes-playlist']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.18
[debug] Python version 2.7.12 - Linux-4.4.0-92-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RDQMUe_cXgPtWx4 - add --no-playlist to just download video dv13gl0a-FA
[youtube:playlist] RDQMUe_cXgPtWx4: Downloading page 1 of Youtube mix
[youtube:playlist] RDQMUe_cXgPtWx4: Downloading page 2 of Youtube mix
[youtube:playlist] RDQMUe_cXgPtWx4: Downloading page 3 of Youtube mix
[download] Downloading playlist: Mix - Initial d songs
[youtube:playlist] playlist Mix - Initial d songs: Collected 51 video ids (downloading 51 of them)
[download] Downloading video 1 of 51
[youtube] Ue_cXgPtWx4: Downloading webpage
[youtube] Ue_cXgPtWx4: Downloading video info webpage
ERROR: Ue_cXgPtWx4: YouTube said: This video does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1537, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: Ue_cXgPtWx4: YouTube said: This video does not exist.
```

*sory for my english...,*

**Comment by dstftw** [comment]
No, this is not true in general, e.g. start video for https://www.youtube.com/watch?v=JGwWNGJdvx8&list=RDPhY_DaWF-Zs is PhY_DaWF-Zs. Start video is always a video mix is dervied from. Most likely Youtube does not list Ue_cXgPtWx4 since it has been deleted.
