### ISSUE TITLE
[feature request] Allow specifying directory to update to

### ISSUE THREAD

**Issue by heniotierra** [rg3/youtube-dl#13999]
What the title says, when issuing the update command, receive optional argument for directory to write to.

**Comment by dstftw** [comment]
By definition update means updating **this** instance of youtube-dl. To download another version of youtube-dl one should use wget/curl.

**Comment by heniotierra** [comment]
@dstftw  Yes, however, if youtube-dl is not installed in the path /usr/local/bin, then the update process wont wont

**Comment by heniotierra** [comment]
I understand - use wget or curl. That's fine.
