### ISSUE TITLE
TV.youtube.com 2fa

### ISSUE THREAD

**Issue by coldwaterq** [rg3/youtube-dl#13995]
I tried to download a news report on TV.youtube.com and it did the 2fawhere it alerts on the phone.  Youtubedl asked for a 2fa code, so I entered it and then it failed to download saying a parameter was unknown.  I do t know if it failed from the 2fa prompt or the domain isn't supported yet. Any advice would be appreciated.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
