### ISSUE TITLE
Please add animerush.tv to support downloads.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#14000]
Example:

$ youtube-dl -v http://www.animerush.tv/The-Reflection-episode-1/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.animerush.tv/The-Reflection-episode-1/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.18
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.9
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] The-Reflection-episode-1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] The-Reflection-episode-1: Downloading webpage
[generic] The-Reflection-episode-1: Extracting information
ERROR: Unsupported URL: http://www.animerush.tv/The-Reflection-episode-1/
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2976, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.animerush.tv/The-Reflection-episode-1/

Thank you in advance. :)

**Comment by remitamine** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).

**Comment by antdude** [comment]
Uh, isn't that the same as other sites like cwtv.com?

**Comment by dstftw** [comment]
[No](https://transparencyreport.google.com/copyright/domains/animerush.tv).
