### ISSUE TITLE
Please add possibility to download youtube liked music playlist (after login as its a private playlist)

### ISSUE THREAD

**Issue by FrodoSwaggins** [rg3/youtube-dl#14001]
if a youtube user has liked a music video, they can access a liked music playlist, I use youtube-dl to download all my music, so far ive just been downloading my liked video playlist, however i then have to filter out the videos that are not music, if this playlist worked it would be so handy. The playlist can be found here: https://www.youtube.com/playlist?list=LM
Thanks for reading, awesome app guys

**Comment by dstftw** [comment]
>https://www.youtube.com/playlist?list=LM

>500 Internal Server Error

Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by Joshfindit** [comment]
https://www.youtube.com/playlist?list=LM does exists for me. May require that the user has liked at least 1 "music" video (example: https://www.youtube.com/watch?v=N1EhXF1lskA )

youtube-dl shows `WARNING: Unable to download webpage: HTTP Error 404: Not Found` for some reason.
