### ISSUE TITLE
Add support for video2brain.com

### ISSUE THREAD

**Issue by sdi22** [rg3/youtube-dl#14011]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.23**
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

### If the purpose of this *issue* is a *site support request* or you are not completely sure provide the full verbose output as follows:

<D:\!LYNDA\Video2Brain-dl>youtube-dl -v --cookies cookies.txt "https://www.video2brain.com/de/videotraining/premiere-pro-fuer-fotografen" -o "video2brain.com - %(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" --add-metadata --write-sub
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies.txt', 'https://www.video2brain.com/de/videotraining/premiere-pro-fuer-fotografen', '-o', 'video2brain.com - %(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', '--add-metadata', '--write-sub']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.08.18
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86994-g92da230, ffprobe N-86994-g92da230
[debug] Proxy map: {}
[generic] premiere-pro-fuer-fotografen: Requesting header
WARNING: Falling back on generic information extractor.
[generic] premiere-pro-fuer-fotografen: Downloading webpage
[generic] premiere-pro-fuer-fotografen: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://html5.v2bcdn.com/de/trailerclips/1362_trailer_1280.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmput9or0a0\build\youtube_dl\YoutubeDL.py", line 1865, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmput9or0a0\build\youtube_dl\YoutubeDL.py", line 1807, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmput9or0a0\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmput9or0a0\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmput9or0a0\build\youtube_dl\YoutubeDL.py", line 2168, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
D:\!LYNDA\Video2Brain-dl>pause>

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.video2brain.com/de/tutorial/ziel-des-trainings
- Playlist: https://www.video2brain.com/de/videotraining/premiere-pro-fuer-fotografen

### Description of your *issue*, suggested solution and other information

Hi, video2brain is the german version of lynda.com. Works the same way. I would like to download my courses from there using youtube-dl. But my knowledge of phyton is too limited that I can add this to the project. So I need your help.

As on lynda.com you can register there for a 10 day trial if you need/want to. You then have access to all the courses, in english and german language.

I think the community would have a great benefit if this site can be supported within youtube-dl.
Please let me know if you need any further information.

**Comment by boschkundendienst** [comment]
I would also ask for video2brain support. If you need any info, I will try to provide them.
Thanks in advance

**Comment by boschkundendienst** [comment]
I think first step would be login, right?

Here is an extraction from the following entry url (loginpage).
Some base64 of images removed an anonymized.

In my case a use traditional login (not facebook, linked in or google, just a local account at video2brain).
So the form "login_form" must be filled with email address and the v2b_userpassword.

If you need more info give me a note.

https://www.video2brain.com/de/login

```html

<form name="login_form" id="login_form" action="" method="post">
        <h1>Melden Sie sich an und verbessern Sie Ihre Fähigkeiten</h1>
            <div class="general-error-message error social-error"></div>
            <a id="btn-linkedin-login" class="btn-social-login icon-linkedin" href="javascript:" onclick="Inbridge.Events.SignIn('https://www.linkedin.com/uas/oauth2/authorization?response_type=code&amp;client_id=86auu1ll7llbm7&amp;redirect_uri=https://www.video2brain.com/de/socialconnect/linkedin?action=login&amp;state=5022226451893BE392E33B3D439A26F0E2C4B65&amp;scope=r_basicprofile r_emailaddress');" hidden="" dij4unn="">Mit LinkedIn anmelden</a>
            <a id="btn-facebook-login" class="btn-social-login icon-facebooklogin" href="javascript:void(0)" onclick="FBbridge.Events.Register(event)">Mit Facebook anmelden</a>
            <a id="btn-google-login" class="btn-social-login icon-googlelogin" href="javascript:void(0)" onclick="Gbridge.Events.Register(event)">Mit Google+ anmelden</a>
            <div id="sl-or">oder</div>
               
        <div class="input-data">
            <div class="general-error-message error general-error"></div>
            <span class="action-text">Loggen Sie sich mit Ihren Daten ein</span>
            <input class="required email populate" type="text" value="" data-title="E-Mail-Adresse" name="email" maxlength="100" id="email" autocomplete="off" style="background-image: base64coderemoved; background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;">
            <div id="user-password">
                <input class="required password" type="password" value="" name="v2b_userpassword" id="password" autocomplete="off" style="background-image: base64coderemoved; background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%;">
                <div id="user-password-ph" style="display: none;">Passwort</div>
            </div>
        </div>

        <div class="input_field">
            <a id="user-login-submit" class="btn-submit btn blue" href="#" onclick="return false;">Einloggen</a>
        </div>

            <div class="set_login_cookie">
                <input type="checkbox" name="set_cookie" id="set_login_cookie" value="1" class="crirHidden" checked="checked">
                <label for="set_login_cookie" class="checkbox_checked"><span>Login speichern</span></label>
            </div>

            <input type="hidden" name="sectoken" value="EBB17223FD46034A7B8852B11D440FA5">
        </form>
```

**Comment by dstftw** [comment]
Moved to linkedin.com/learning.
