### ISSUE TITLE
[radiocanada] [tou.tv] Possible platform change affecting some videos

### ISSUE THREAD

**Issue by ProgrammerAKL** [rg3/youtube-dl#14019]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl-2017-08-23 -o "C:/Video/Grands reportages S23E142" "http://ici.tou.tv/les-grands-reportages/S23E142?lectureauto=1" --no-check-certificate --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/Grands reportages S23E142', 'http://
ici.tou.tv/les-grands-reportages/S23E142?lectureauto=1', '--no-check-certificate
', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.08.23
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[tou.tv] les-grands-reportages/S23E142: Downloading JSON metadata
[radiocanada] 132179: Downloading metadata XML
[radiocanada] 132179: Downloading ipad XML
[radiocanada] 132179: Downloading m3u8 information
[radiocanada] 132179: Downloading flash XML
[radiocanada] 132179: Downloading android XML
ERROR: radiocanada said: Cette plate-forme n'est pas supportée
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0sgn5d73\bu
ild\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0sgn5d73\bu
ild\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0sgn5d73\bu
ild\youtube_dl\extractor\radiocanada.py", line 88, in _real_extract
youtube_dl.utils.ExtractorError: radiocanada said: Cette plate-forme n'est pas s
upportée
...
<end of log>
```
whereas older episodes still work:
```
youtube-dl-2017-08-23 -o "C:/Video/Grands reportages S23E131" "http://ici.tou.tv/les-grands-reportages/S23E131?lectureauto=1" --no-check-certificate --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/Grands reportages S23E131', 'http://
ici.tou.tv/les-grands-reportages/S23E131?lectureauto=1', '--no-check-certificate
', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.08.23
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[tou.tv] les-grands-reportages/S23E131: Downloading JSON metadata
[radiocanada] 131996: Downloading metadata XML
[radiocanada] 131996: Downloading ipad XML
[radiocanada] 131996: Downloading m3u8 information
[radiocanada] 131996: Downloading flash XML
[radiocanada] 131996: Downloading android XML
[radiocanada] 131996: Downloading m3u8 information
[radiocanada] 131996: Downloading f4m manifest
[radiocanada] 131996: Downloading m3u8 information
[radiocanada] 131996: Downloading f4m manifest
[radiocanada] 131996: Downloading m3u8 information
[radiocanada] 131996: Downloading f4m manifest
[radiocanada] 131996: Downloading m3u8 information
[radiocanada] 131996: Downloading f4m manifest
[debug] Default format spec: best
[debug] Invoking downloader on 'http://medias-rtsp.tou.tv/vodtoutv/_definst_/mp4
:012/mp4/g/2017-08-08_20_01_30_grandsreportages_2070_2000.mp4/chunklist.m3u8?wow
zasessionid=896241365'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 316
[download] Destination: C:\Video\Grands reportages S23E131
[download]   0.0% of ~848.48MiB at 544.87KiB/s ETA 46:56
...
<end of log>
```
---

---

### Description of your *issue*, suggested solution and other information

It looks like the newer episodes are hosted in a somewhat different way than the older ones and so a modification is needed. Also, if ipad, android and Flash versions all exist, can the user choose which of them to use?

**Comment by obilodeau** [comment]
Why was this issue closed without an explanation or duplicate id? Just curious.
