### ISSUE TITLE
Bypass 'verify_controversy' page when downloading youtube video

### ISSUE THREAD

**Issue by rudolphos** [rg3/youtube-dl#14029]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.23**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[download] Downloading video 2 of 2
[youtube] videoid: Downloading webpage
[youtube] videoid: Downloading video info webpage
ERROR: invalid literal for int() with base 10: ''
```

---

---
I can't download videos that are behind 'controversy confirmation' page

This would be important considering the recent censorship on google/youtube.

bloomberg:
https://www.bloomberg.com/news/articles/2017-08-24/google-rolls-out-its-biggest-crackdown-on-youtube-hate-speech
> Starting on Thursday, Google will police YouTube like it never has before, adding warnings and disabling advertising on videos that the company determines crosses its new threshold for offensive content.

**Comment by Hrxn** [comment]
Is this really happening?

**Comment by CeruleanSky** [comment]
To add what the above stated, I just want to point out that the view count data is still available in a url parameter. 

 I erased them below, but here is a small sample.  I think just about all the censored info about the video is still available.

If you add ```--dump-pages``` the base64 encoded data after
```[youtube] : Downloading video info webpage```
```[youtube] Dumping request to https://www.youtube.com/get_video_info```

Includes 66 url parameters still populated and available, a small sample is below:    


```
&short_view_count_text=[XXX-REMOVED-FOR-PRIVACY-XXX]
&dashmpd=[XXX-REMOVED-FOR-PRIVACY-XXX]
&keywords=[XXX-REMOVED-FOR-PRIVACY-XXX]
&default_audio_track_index=[XXX-REMOVED-FOR-PRIVACY-XXX]
&loudness=[XXX-REMOVED-FOR-PRIVACY-XXX]
&timestamp=[XXX-REMOVED-FOR-PRIVACY-XXX]
&iurlsd=[XXX-REMOVED-FOR-PRIVACY-XXX]
&csn=[XXX-REMOVED-FOR-PRIVACY-XXX]
&video_id=[XXX-REMOVED-FOR-PRIVACY-XXX]
&cver=[XXX-REMOVED-FOR-PRIVACY-XXX]
&ttsurl=[XXX-REMOVED-FOR-PRIVACY-XXX]
&cos=[XXX-REMOVED-FOR-PRIVACY-XXX]
&thumbnail_url=[XXX-REMOVED-FOR-PRIVACY-XXX]
&iurlmq=[XXX-REMOVED-FOR-PRIVACY-XXX]
&view_count=[XXX-REMOVED-FOR-PRIVACY-XXX]

```


So the data is still all there.
