### ISSUE TITLE
Trouble logging in with Charter_Direct MSO

### ISSUE THREAD

**Issue by DanTheMan827** [rg3/youtube-dl#14038]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.27*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.27**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.adultswim.com/videos/dragon-ball-super/im-here-too-training-commences-on-beerus-world/', '--all-subs', '--embed-subs', '--ap-mso', 'Charter_Direct', '--ap-username', 'PRIVATE', '--verbose', '--write-pages', '--print-traffic']
Type TV provider account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.08.27
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg 2.8.4, ffprobe N-81462-gbcd1153
[debug] Proxy map: {}
[AdultSwim] im-here-too-training-commences-on-beerus-world: Downloading webpage
[AdultSwim] Saving request to im-here-too-training-commences-on-beerus-world_http_-_www.adultswim.com_videos_dragon-ball-super_im-here-too-training-commences-on-beerus-world_.dump
[AdultSwim] ohhc3WZ4S9awk1m-1uNpPg: Downloading XML
[AdultSwim] Saving request to ohhc3WZ4S9awk1m-1uNpPg_http_-_www.adultswim.com_videos_api_v0_assetsplatform=desktop_id=ohhc3WZ4S9awk1m-1uNpPg.dump
[AdultSwim] 1428627: Downloading Provider Redirect Page
[AdultSwim] Saving request to 1428627_https_-_sp.auth.adobe.com_adobe-services_authenticate_saml.dump
[AdultSwim] 1428627: Downloading Provider Login Page
[AdultSwim] Saving request to 1428627_https_-_idp.aws.charter.net_-443_openam_SSOPOST_metaAlias_charter_idp.dump
[AdultSwim] 1428627: Logging in
[AdultSwim] Saving request to 1428627_https_-_idp.aws.spectrum.net_openam_UI_Login.dump
[AdultSwim] 1428627: Confirming Login
[AdultSwim] Saving request to 1428627_https_-_idp.aws.spectrum.net_openam_UI_Login.dump
[AdultSwim] 1428627: Retrieving Session
ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw5l962ew\build\youtube_dl\extractor\common.py", line 503, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw5l962ew\build\youtube_dl\YoutubeDL.py", line 2168, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

---

### Description of your *issue*, suggested solution and other information

The Charter_Direct MSO doesn't seem to work.

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by DanTheMan827** [comment]
It was an issue on my end, sorry about that.
