### ISSUE TITLE
Can't automatically over write existing downloaded file

### ISSUE THREAD

**Issue by section83** [rg3/youtube-dl#14031]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.23**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

This is the full verbose output:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--restrict-filenames', u'--verbose', u'-o', u'%(title)s.%(ext)s', u'http://iview.abc.net.au/programs/amateur-hour-spotlight-shorts/ZW0776A006S00']
[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
[debug] youtube-dl version 2017.08.23
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2-tessus, ffprobe 3.3.2-tessus
[debug] Proxy map: {}
[abc.net.au:iview] ZW0776A006S00: Downloading webpage
[abc.net.au:iview] ZW0776A006S00: Downloading f4m manifest
[abc.net.au:iview] ZW0776A006S00: Downloading m3u8 information
[abc.net.au:iview] ZW0776A006S00: Downloading f4m manifest
[abc.net.au:iview] ZW0776A006S00: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://iviewum-vh.akamaihd.net/i/playback/_definst_/_video/artsa/arts_amateur_01_06_20170814140030_,1500000,1000000,650000,500000,220000,.mp4.csmil/index_0_av.m3u8'
[download] Ash_Flanders.mp4 has already been downloaded

[download] 100% of 23.05MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:Ash_Flanders.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Ash_Flanders.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Ash_Flanders.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Ash_Flanders.temp.mp4'
```
---

Am issuing this command:

youtube-dl --restrict-filenames  -o '%(title)s.%(ext)s' URL

The download file exists but is not over written.  Is there a way to force over writing ?

**Comment by dstftw** [comment]
`--no-continue`.

**Comment by section83** [comment]
Thank you, especially for the quick response.

I don't understand why it works.  I have taken the documentation literally which says "Do not resume partially downloaded files (restart from beginning)".  Is a fully downloaded file the same as a partially downloaded file ?  I guess so.  Can I suggest a small redraft:

"Do not resume partially downloaded files (restart from beginning).  Also, overwrite completed downloads."

Also, --no-overwrites will override --no-continue which is good but not apparent from documentation.

**Comment by section83** [comment]
Sorry but, I find this frustrating.  I can't get youtube-dl to overwrite any fully downloaded files.  No, I'm not thinking of partially downloaded files (which can be handled with --no-continue).  I am thinking of downloads that are completed.  In my tests, "--no-continue" does not force overwrite a completed download.  youtube-dl still reports: "<file name> has already been downloaded and merged" and nothing is downloaded.

What use is the --no-overwrites parameter when youtube-dl will never overwrite a completed download anyway ?  Probably, I've missed something so my question is: "In what situations does youtube-dl overwrite completed downloads ?"

Thanks.

**Comment by alxnull** [comment]
I find this confusing too, youtube-dl has a `--continue` as well as a `--no-continue` option and a `--no-overwrites` option but no `--overwrites` option. I also couldn't manage to force youtube-dl to overwrite an existing _fully downloaded_ file by adding `--no-continue`.

**Comment by section83** [comment]
It's very odd as youtube-dl will not overwrite a completed download in any case, as far as I can tell.  The two continue options only seem to work when a download has been partially completed.  "--no-continue" will overwrite what has been downloaded.  I don't understand when "--continue" might be needed but, it doesn't hurt to use it.

Also, the developers have stated in response to a number of questions that "--no-continue" will over-write a completed download but, I've never been able to get that to work [(link to example)](https://github.com/rg3/youtube-dl/issues/5353).  In fact the readme says:  "Do not resume partially downloaded files (restart from beginning)" which says nothing about completed downloads.  I guess the only option is to delete the completed download manually or by script before running youtube-dl.
