### ISSUE TITLE
Accessing the downloaded file.

### ISSUE THREAD

**Issue by Joaobranquinho** [rg3/youtube-dl#14041]
I've looked through the documentation and haven't been able to locate this "feature"
I use embed youtube-dl in python. Is there anyway for me to access the just downloaded file?

**Comment by siddht4** [comment]
the downloaded file should be where your embed youtube-dl project/code exists if not anyways overrided with `--config-location PATH `  or `--output TEMPLATE` or config i.e https://github.com/rg3/youtube-dl#configuration.

Just to make sure you are talking about the downloaded audio/video from the embed youtube-dl,not youtube-dl code in anyways to support embed

**Comment by dstftw** [comment]
`_filename` meta field of video info dict.

**Comment by Joaobranquinho** [comment]
@dstftw 
After inspecting the info dict that I obtained using the code bellow:
```
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    info_dict = ydl.extract_info(self.url)
    pprint(info_dict)
```

I wasn't able to find the `_filename` field. All I found was `filesize`

**Comment by siddht4** [comment]
@Joaobranquinho      you need to change/modify  your ydl_opts for this  one 

example :    `ydl_opts ={
    'format': '720p/best',
     '_filename':'[path]/[file_name]', # [path] : means the entire folder structure, if the path , if its ignored the downloaded file will be named based on your file naming structure where your embed code is 
    'postprocessors': [],
    'logger': MyLogger(),
    'progress_hooks': [my_hook],
}`

**Comment by Moriand** [comment]
@siddht4 Is this great, what more options do I have with `ydl_opts`?

For example, I want to change the output name, get the video quality I want to download "360, 480, 720", I also want to know how I download the subtitle of the video.

Where can I place the ffmpeg folder

**Comment by siddht4** [comment]
ydl_opts  is a dictionary object for youtube-dl. You can vist https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L1679 to get all the available options.  Output name aka file name can be renamed through _filename parameters. For subtitle use allsubtitle and set it to true

**Comment by siddht4** [comment]
For ffmpeg just make sure its set to global path. Explicitly mentioning is not required

**Comment by Moriand** [comment]
hello @siddht4  It is still somewhat understandable, could you say how I start or, what options do I have ?, for example: how do I get the video quality list -> 360p, 480p, 720p, 1080p.
I can put this in print, but how do I select only one of these, example 360p or 480p ?, and that only this download.
example
```
ydl_opts {
  '' = '' # what other options can I include, example quality of movie
}
```

**Comment by siddht4** [comment]
@Moriand      `{ 'format': '480p/360p}`

would force youtube-dl to download 480p  file format. If its not present then the next one 360p is downloaded. otherwise it  will  give/return  error.

**Comment by siddht4** [comment]
@Moriand   If you really are not understanding or facing issue. Comment here.    Still I am providing link to some of the exisitng embed code I have .   

Code #1  https://github.com/siddht4/youtube_dl_custom/blob/master_1/test/test_2.py        To download just the meta info
