### ISSUE TITLE
Youtube-dl freezing up

### ISSUE THREAD

**Issue by karl6994** [rg3/youtube-dl#14047]
Hi, I've been using Youtube-dl for like a year now & I've never had a problem with it.. Til now! It seems to freeze up like it doesn't want to download, like it'll finish 100% on the video part, but it gets stuck and doesn't start downloading the audio... Its been really funny lately since one of the last updates.
I'm running Fedora, so I don't know how new the youtube-dl in the repos are.. I have RPMFUSION repo enabled. Also sometimes the download will stop, here is the error:
ERROR: unable to download video data: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2171)

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
