### ISSUE TITLE
"ffprobe or avprobe not found. Please install one." though ffmpeg is installed

### ISSUE THREAD

**Issue by TheSpaceSheep** [rg3/youtube-dl#14045]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.27.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.27.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

 sudo youtube-dl -v --extract-audio https://www.youtube.com/watch?v=iuJvZdKlJH8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--extract-audio', u'https://www.youtube.com/watch?v=iuJvZdKlJH8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 2.7.12 - Linux-3.10.102-armv7l-with-glibc2.4
[debug] exe versions: ffmpeg 2.0.2
[debug] Proxy map: {}
[youtube] iuJvZdKlJH8: Downloading webpage
[youtube] iuJvZdKlJH8: Downloading video info webpage
[youtube] iuJvZdKlJH8: Extracting video information
[youtube] iuJvZdKlJH8: Downloading MPD manifest
[debug] Invoking downloader on u'https://r13---sn-4gxx-25gel.googlevideo.com/videoplayback?key=yt6&ip=2a01%3Ae34%3Aece4%3A8520%3A211%3A32ff%3Afe71%3A4b8d&lmt=1451770545910614&dur=10.781&ipbits=0&itag=251&id=o-AH9rpNpldMPuVQwYR-4bTFDJPzQd0-O_QUUJibG8Yfni&requiressl=yes&mm=31&mn=sn-4gxx-25gel&keepalive=yes&mt=1503827862&mv=m&clen=180447&ms=au&signature=0C3FA72624D0C153B51DEECB6C689AE92672EE2F.4EFDA1524A25118F7FEDE945919531CCD68651E2&ei=QJiiWcOaCMiScJXnk5AF&expire=1503849632&initcwndbps=927500&gir=yes&source=youtube&pl=26&nh=EAE&mime=audio%2Fwebm&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cexpire&ratebypass=yes'
[download] i hate myself-iuJvZdKlJH8.webm has already been downloaded
[download] 100% of 176.22KiB
ERROR: ffprobe or avprobe not found. Please install one.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2004, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 241, in run
    filecodec = self.get_audio_codec(path)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 156, in get_audio_codec
    raise PostProcessingError('ffprobe or avprobe not found. Please install one.')
PostProcessingError: ffprobe or avprobe not found. Please install one.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Hello,

I'm trying to install youtube-dl on a synology NAS server, which runs under linux (here's the output of '$ uname -a' : Linux NASDELRIU 3.10.102 #15152 SMP Fri Aug 11 17:49:34 CST 2017 armv7l GNU/Linux synology_armada38x_ds216j) but i can't get ffmpeg to work.

I've installed ffmpeg and added it to my $PATH. When i type in 'ffmpeg', everything seems to work fine, i just can't figure out how to get the connection between youtube-dl and ffmpeg to work.

Any idea where this problem could come from ?

Thank you :)

**Comment by yan12125** [comment]
Usually ffprobe comes with ffmpeg, but it's not always the case. From your log ffmpeg 2.0.2 is detected while ffprobe is missing. Most likely Synology does not provide ffprobe.
