### ISSUE TITLE
Soundcloud page ERROR: Unable to download JSON metadata

### ISSUE THREAD

**Issue by rphair** [rg3/youtube-dl#14058]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.27.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.27.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Similar to https://github.com/rg3/youtube-dl/issues/11598 ... except that I get a 404 error when "download(ing) JSON Metadata" instead of a 403.  I have more recent versions of Python on the system (up to 3.6.2) though 2.7.12 is the default (Ubuntu 16.04 seems to break if not).

```
[4] anjaneya% youtube-dl -v !$
youtube-dl -v http://soundcloud.com/jahnavi_harrison/kirtan-at-yamuna-devis-samadhi
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://soundcloud.com/jahnavi_harrison/kirtan-at-yamuna-devis-samadhi']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 2.7.12 - Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 3.2.6-1, avprobe 3.2.6-1, ffmpeg 3.2.6-1, ffprobe 3.2.6-1, rtmpdump 2.4-n111-gitfa8646d-ppa9p2
[debug] Proxy map: {}
[soundcloud] jahnavi_harrison/kirtan-at-yamuna-devis-samadhi: Resolving id
[soundcloud] jahnavi_harrison/kirtan-at-yamuna-devis-samadhi: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 503, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2168, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

[5] anjaneya% 
```

**Comment by dstftw** [comment]
Not playable in browser.

**Comment by jplatte** [comment]
I've got this same error message and it aborted a playlist download for me. It would be nice if one track in the playlist not being available wouldn't cause youtube-dl to abort the whole download process.

Playlist: https://soundcloud.com/infectedmushroom/sets/friends-on-mushrooms-deluxe
Unavailable track is no. 5: https://soundcloud.com/infectedmushroom/5-kazabubu

**Comment by remitamine** [comment]
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```
