### ISSUE TITLE
youtube-dl -f 135 --proxy socks5://127.0.0.1:1080 https://www.youtube.com/watch?v=48hGClz_c00

### ISSUE THREAD

**Issue by sunhao130130** [rg3/youtube-dl#14051]
youtube-dl -f 135 --proxy socks5://127.0.0.1:1080 https://www.youtube.com/watch?v=48hGClz_c00
Download video without sound why??? help me

**Comment by yan12125** [comment]
135 is a video-only format. If you want to download videos with sounds, use ```-f bestvideo+bestaudio/best``` or ```-f 135+bestaudio/best``` if you really wants format 135.

**Comment by sunhao130130** [comment]
Thank you very much
