### ISSUE TITLE
Unable to download videos from youtube channels / playlist & failed to achieve video's date.

### ISSUE THREAD

**Issue by yennyng** [rg3/youtube-dl#14068]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.27.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.27.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

C:\Users\user\Desktop\youtube-dl>youtube-dl https://www.youtube.com/user/▧▧▧/videos
[youtube:user] ▧▧▧: Downloading channel page
[youtube:user] ▧▧▧: Downloading page #1
[download] Downloading playlist: ▧▧▧
[youtube:user] playlist ▧▧▧: Downloading 0 videos
[download] Finished downloading playlist: ▧▧▧

---

**<1> Unable to download videos from youtube channels / playlist.**
Before youtube made their layout changes about a few hour ago things was working fine, I was able to download all the videos directly from youtube channel (exp: https://www.youtube.com/user/xiaozhuangw/videos) or playlist (exp: https://www.youtube.com/playlist?list=PLxO0m5nXjWH5xHkaWd04_tMGlaQsvsqBB).

I realize that the loading will stop after this line "[youtube:user] ▧▧▧: Downloading page #1" when normally it could move on to more page number (Downloading page #2, #3 etc) and therefore ended with 0 videos.

- My previous downloads from a channel with thousand video is still running at the moment (only that dates became "NA"), so I believe somewhere between channel page access was changed from the Youtube.

- When testing to download just only *single* video things still works wonders. 
(exp: https://www.youtube.com/watch?v=alTRKo8-jeM)

**<2> Failed to achieve video date [-o %(upload_date)s]**
*-o %(upload_date)s* end with the results "NA" rather than "YYYYMMDD".

Thank you so much for your time in advance!

**Comment by vxbinaca** [comment]
I'm getting a null date in the info.json file:

`"upload_date": null`

This would be the problem.

**Comment by vxbinaca** [comment]
The problem is, youtube is serving a null date. I found this by looking at a ripped videos info.json file.

`"upload_date": null`

It's reproducible on pretty much any video right now and may be related to the layout change.
