### ISSUE TITLE
How to download low resolution video from vimeo and dailymotion. e.g.1280X720?

### ISSUE THREAD

**Issue by kiranbulley** [rg3/youtube-dl#14064]
Hi, 

I am trying by using following query , but getting error

youtube-dl   -v  -f hls-480-3  http://www.dailymotion.com/video/x5xx3z4 -o   E:/xampp/htdocs/videoconverter/aa7F.mp4

thanks,

**Comment by lki2019** [comment]
http://proxy-11.sg1.dailymotion.com/sec(d3135bb81ef763592236deccdda53304)/video/800/303/359303008_mp4_h264_aac_fhd_2.m3u8#cell=sg1&hls_heuristic=1&hls_startFragPrefetch=1

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
