### ISSUE TITLE
Cannot download YouTube playlist with more than 100 videos

### ISSUE THREAD

**Issue by Vladomaimun** [rg3/youtube-dl#14076]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.27.1**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

I get this error when attempting to download this playlist (don't judge the poor taste in music, a friend asked me to download it for him):
https://www.youtube.com/playlist?list=PLrSr3DDuAc85RUDL2v3woC_fyaRHGIgta

```
 youtube-dl -v "https://www.youtube.com/playlist?list=PLrSr3DDuAc85RUDL2v3woC_fyaRHGIgta"
[debug] System config: [u'-f', u'bestaudio[ext=m4a]/135+bestaudio[ext=m4a]/136+bestaudio[ext=m4a]/best[ext=mp4]', u'-o', u'/home/cartogan/Videos/%(playlist)s/%(title)s-%(id)s.%(ext)s', u'--yes-playlist']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/playlist?list=PLrSr3DDuAc85RUDL2v3woC_fyaRHGIgta']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 2.7.12 - Linux-4.4.0-77-generic-x86_64-with-LinuxMint-18-sarah
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube:playlist] PLrSr3DDuAc85RUDL2v3woC_fyaRHGIgta: Downloading webpage
[download] Downloading playlist: Чалга 2016-2017
[youtube:playlist] PLrSr3DDuAc85RUDL2v3woC_fyaRHGIgta: Downloading page #1
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1958, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 939, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 272, in _entries
KeyError: u'content_html'
<end of log>
```
At first I thought the slashes in video titles were causing the issue but individual videos can be downloaded without errors. The slashes are replaced with underscores.
Then I tried downloading the first three songs by adding them to new playlists to determine if the name of the playlist can cause an issue. I tried names that included latin and cyrilic letters, numbers, spaces and dashes. The new playlists were downloaded without errors.

Any help is  appreciated.

EDIT:
I created a new playlist with the same name and I noticed that the line
[youtube:playlist] PLrSr3DDuAc85RUDL2v3woC_fyaRHGIgta: Downloading page #1
changed to
[youtube:playlist] playlist Чалга 2016-2017: Downloading 2 videos
The new playlist downloads with no issues.

**Comment by Vladomaimun** [comment]
Turns out the playlist is too long. I get the same error on other playlists of more than 100 videos.

**Comment by wellivea1** [comment]
I am getting the same error, but I did not get it before. It has been over 100 videos for a long time.

**Comment by HPP8140** [comment]
Seems to happen when the playlist has more than 100 items, the "Load more" is not working

**Comment by Aioxas** [comment]
Agreed, I get a key error regarding "content_html = more["content_html"]" with content_html not being found. Either 1. that key got changed, 2. Something else changed.

**Comment by Hrxn** [comment]
Yeah, I noticed some smaller (mostly cosmetic) changes on the YouTube site as well in the last days, and a site redesign has been planned (and is in the works) for some time now, so I definitely think this is some site change.

**Comment by xsteadfastx** [comment]
i dont get the python traceback but have the same problem.

**Comment by realspencerdupre** [comment]
I'm a youtube-dl n00b, but I'm on the latest version via the curl command a couple minutes ago.  Same issue.  Seems like in the web interface the get param "&disable_polymer=true" produces the old-school playlist page.  Dunno if that helps.

**Comment by lukaskollmer** [comment]
Same here. It's probably related to the site redesign they're rolling out atm

**Comment by rocawhey** [comment]
as a temporary workaround of slightly less inconvenience, one can order their playlist by date added or add videos to the top of the playlist, and then use flags --playlist-start 1 --playlist-end 100. anything above 100 still won't work.

**Comment by Rayniax** [comment]
Hello,
Exactly got the same problem from today, i just upgraded and I cannot download anymore from my playlist with about 200 videos. It was working very well before, just got "ERROR: u'content_html'
Thank you very much for the work of the community.

**Comment by synergiance** [comment]
My 700+ video playlist was working just fine the other day with youtube-dl I wonder what happened

**Comment by Hrxn** [comment]
Site redesign, as mentioned earlier.
