### ISSUE TITLE
NSFW xvideos.com

### ISSUE THREAD

**Issue by js017** [rg3/youtube-dl#14070]
When using "youtube-dl <video URL>", where "<video URL>" is a URL to a video like "http://www.xvideos.com/video2505569/the_goodest_blowjob_ever_", it used to just download the best audio and video in a proper .mp4 format quickly and easily, but now it downloads a file with the .mp4 extension, that doesn't show a video preview thumbnail in Windows 7 large icons view, file length in details view, and isn't able to be converted by some video editing programs like VideoReDo TVSuite 5, because it doesn't seem to be a standard .mp4 format. How do you get that to work properly?

- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

![youtube-dl](https://user-images.githubusercontent.com/26278182/29892542-f327a270-8d9c-11e7-8ae5-851ab8b86683.jpg)

[debug] System config: []  [debug] User config: []  [debug] Custom config: []  [debug] Command-line args: [’-v’, ’http://www.xvideos.com/vide02585569/the_goode st_blowjob_ever_’]  [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252  [debug] youtube-dl version 2817.88.27.1  [debug] Python version 3.4.4 - Hindows-7-6.1.7681-SP1  [debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg N-83657-g7e4f32f, ffprob e N-83657-g7e4f32f  [debug] Proxy map: {}  [XUideos] 2585569: Downloading webpage  [XUideos] 2585569: Downloading m3u8 information  [debug] Default format spec: bestvideo+bestaudio/best  [debug] Invoking downloader on ’http://cdn-hw-hls.xvideos.com/videos/hls/dc/82/9 a/ch29aB4b35e88ab92a38126a3eed18f/hls-368p.m3u8?e=15B4133797&l=@&h=951eec98e5B3 ?Zce4ff6b83f2492da81’  [hlsnative] Downloading m3u8 manifest  [hlsnative] Total fragments: 44  [download] Destination: The Goodest blowjob EUER 2??-25@5569.mp4  [download] 1882 of 27.85MiB in 88:14  [debug] avconv command line: avprobe -show_streams "file:The Goodest blowjob EUE R S!!-25B5569.mp4"  [ffgpeg] Fixing malformed BBC bitstream in "The Goodest blowjob EUER 222-2585569 _mp u  [debug] ffmpeg command line: avconv -y -i "file:The Goodest blowjob EUER 222-253 5569.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "filezThe Goodest blowjob EUER ! 2!-25B5569.temp.mp4"

**Comment by dstftw** [comment]
Best format is HLS that is downloaded. To select another format use [format selection](https://github.com/rg3/youtube-dl#format-selection).

**Comment by js017** [comment]
Best format is HLS that is downloaded, didn't address the issue in the original description. The issue is that the downloaded .mp4 doesn't show a video preview thumbnail in Windows 7 large icons view, file length in details view, and isn't able to be converted by some video editing programs like VideoReDo TVSuite 5, because it doesn't seem to be in a standard .mp4 format. Other .mp4 files downloaded with other software, even ones in the HLS format, show thumbnail previews in large icons view, file lenght in details view, and are editable by video editing programs like VideoReDo 5, because they are in a standard .mp4 format. youtube-dl didn't used to do that with .mp4 files, it only started doing that in the recent update. Have a good day. Thanks.

**Comment by js017** [comment]
When you download .mp4 files using youtube-dl from xvideos.com, they don't display thumbnails in large icon view, or the file length in details view like they should, and also you can't even convert them with video editing programs like VideoReDo TVSuite 5, because it's kind of like they aren't in the standard .mp4 format. You didn't respond yet to my comment, but I got an email from you just now saying "Closed #14070.". If you make a program to download .mp4 files, you should make sure that it downloads them in a proper, standard format.
