### ISSUE TITLE
Youtube error "content_html"

### ISSUE THREAD

**Issue by userlip** [rg3/youtube-dl#14074]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.27.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.27.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Got a weird bug when I started my youtube-dl script

PS C:\Users\lip> youtube-dl -f bestaudio --playlist-end 163 -x --audio-format mp3 --embed-thumbnail --audio-quality 0 --download-archive "archive.txt" --p
ostprocessor-args "-strict experimental" -i --metadata-from-title "%(artist)s - %(title)s" -o "%(title)s.%(ext)s" https://www.youtube.com/playlist?list=LL
zvVOLVhUriIFomutioDkGw --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestaudio', '--playlist-end', '163', '-x', '--audio-format', 'mp3', '--embed-thumbnail', '--audio-quality', '0', '--dow
nload-archive', 'archive.txt', '--postprocessor-args', '-strict experimental', '-i', '--metadata-from-title', '%(artist)s - %(title)s', '-o', '%(title)s.%
(ext)s', 'https://www.youtube.com/playlist?list=LLzvVOLVhUriIFomutioDkGw', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 3.6.0 - Windows-10-10.0.15063-SP0
[debug] exe versions: ffmpeg N-79585-g268b5ae, ffprobe N-79585-g268b5ae
[debug] Proxy map: {}
[youtube:playlist] LLzvVOLVhUriIFomutioDkGw: Downloading webpage
[download] Downloading playlist: Liked videos
[youtube:playlist] LLzvVOLVhUriIFomutioDkGw: Downloading page #1
ERROR: 'content_html'
Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\program files\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 939, in process_ie_result
    ie_entries, playliststart, playlistend))
  File "c:\program files\anaconda3\lib\site-packages\youtube_dl\extractor\youtube.py", line 272, in _entries
    content_html = more['content_html']
KeyError: 'content_html'

**Comment by HPP8140** [comment]
Seems to happen when the playlist has more than 100 items, the "Load more" is not working

**Comment by Balun-Symmetrie** [comment]
Hmm I have had similar Issues with almost any other downloadapp I sofar tried.

Is there a solution or a easy workaround?

**Comment by Hendrikto** [comment]
I have the same problem. Repro:
```
hendrik ~/music % youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 -o "%(title)s.%(ext)s" --playlist-start 101 --playlist-end 200 -i "https://www.youtube.com/playlist?list=FLc4IMSDR2Lgyo1gbCWGqhzw"
[youtube:playlist] FLc4IMSDR2Lgyo1gbCWGqhzw: Downloading webpage
[download] Downloading playlist: Favorites
[youtube:playlist] FLc4IMSDR2Lgyo1gbCWGqhzw: Downloading page #1
ERROR: 'content_html'
```

**Comment by DeesseFortuna** [comment]
Same problem here too:

```
sudo youtube-dl -v https://www.youtube.com/watch?list=PL7XlqX4npddfrdpMCxBnNZXg2GFll7t5y -i -x --audio-format=mp3 --audio-quality=0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?list=PL7XlqX4npddfrdpMCxBnNZXg2GFll7t5y', '-i', '-x', '--audio-format=mp3', '--audio-quality=0']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 3.5.2 - Linux-4.4.0-91-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube:playlist] PL7XlqX4npddfrdpMCxBnNZXg2GFll7t5y: Downloading webpage
[download] Downloading playlist: important videos
[youtube:playlist] PL7XlqX4npddfrdpMCxBnNZXg2GFll7t5y: Downloading page #1
ERROR: 'content_html'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 939, in process_ie_result
    ie_entries, playliststart, playlistend))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 272, in _entries
    content_html = more['content_html']
KeyError: 'content_html'

```
