### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by js017** [rg3/youtube-dl#14071]
When downloading a video from YouTube, like "https://www.youtube.com/watch?v=Zi_XLOBDo_Y", it used to just find the best audio and video and download in a .mp4 format, but now it downloads in a .mkv format, so how do you download an .mp4 file instead of .mkv automatically without having to use "--list-formats" each time you want to find the .mp4 format for a video on a certain page?

- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

![youtube-dl](https://user-images.githubusercontent.com/26278182/29892801-02ac56f4-8d9e-11e7-8440-53b0138b7cd1.jpg)

[debug] System config: []  [debug] User config: []  [debug] Custom config: []  [debug] Command-line args: [’-v’, ’https://www.youtube.com/watch?v=Zi_XLOBDo_H’]  [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252 [debug] youtube-dl version 2317.88.27.1  [debug] Python version 3.4.4 - Hindows-7-6.1.7681-SP1  [debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg N-83657-g7e4f32f, ffprok e N-83657-g7e4f32f  [debug] Proxy map: {}  [youtube] Zi_HLOBDo_R: Downloading webpage  [youtube] Zi_HLOBDo_R: Downloading video info webpage  [youtube] Zi_HLOBDo_R: Extracting video information  HHRNING: unable to extract uploader nickname  [youtube] {43} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {18} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {36} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {1?} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {135} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {244} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {134} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {243} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {133} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {242} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {163} signature length 44.48, htm15 player en_US-vleYUnxc [youtube] {278} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {143} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {171} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {249} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {253} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] {251} signature length 46.48, htm15 player en_US-vleYUnxc [youtube] Zi_HLOBDo_R: Downloading MPD manifest  [debug] Default format spec: bestvideo+bestaudio/best  HHRNING: Requested formats are incompatible for merge and will be merged into ml  v. [debug] Invoking downloader on ’https://r7---sn-gvagn-tvfe.googlevideo.com/vide oplayback?id=662fd72ce343a3f6&itag=135&source=youtube&requiress1=yes&mm=31&mn=sn -gvagn-tvfe&pl=28&mv=m&ms=au&gcr=ca&initcwndbps=3291258&ei=exunHaz-MsrPDcU3nvﬂC &ratebypass=yes&mime=video/mp4&gir=yes&c1en=17919668&1mt=1483663334857448&dur=29 5.828&signature=1B5D34349EC14926R7B8331DBD19BR9DCCEC3386.7HSB2HD458DF91910FB24BE 2CB8B78664E586389&mt=1534123629&key=dg_yt3&ip=99.245.225.234&ipbits=3&expire=15€ 4145371&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,pl,mv,ms,gcr,in itcwndbps,ei,ratebypass,mime,gir,clen,lmt,dur’  [goggggad]4Destination: Michael Jackson - Billie Jean (Official Uideo)-Zi_XLOBDo _ . .mp  [download] 1882 of 17.39MiB in 83:31  [debug] Invoking downloader on ’https://r7---sn-gvagn-tvfe.googlevideo.com/vide oplayback?mn=sn-gvagn-tvfe&mm=31&keepalive=yes&sparams=c1enz2Cdurz2Ceiz2Cgcrz2C girz2Cidz2Cinitcwndbpsz2Cipz2Cipbitsz2Citagz2Ckeepalivez2Clmtz2Cmimez2Cmmz2Cmn22 Cmsz2Cva2Cplz2Crequiress122Csourcez2Cexpire&mv=m&mt=1584123629&itag=171&ms=au&e i=ehunHazoOorSDf7ph69M&pl=28&mime=audioz2Fwebm&expire=1584145371&c1en=4934869&in itcwndbps=3291258&ip=99.245.225.234&key=yt6&dur=295.835&source=youtube&lmt=14667 88888443717&requiressl=yes&ipbits=8&gir=yes&id=o-ﬂFerFNyekRNHtquxdvh6a1tMO793Pt oszBerucw8-d&gcr=ca&signature=11D38CFE826E6456BCB8B445BF77CSB5E9C38489.DBC74993 015C73ECS639CF554BE7B066504246B9&ratebypass=yes’  [download] Destination: Michael Jackson - Billie Jean (Official Uideo)-Zi_XLOBDo _Y.f171.webm  [download] 1882 of 4.71MiB in 83:83  [ffmpeg] Merging formats into "Michael Jackson - Billie Jean (Official Uideo)-Zi _XLOBDo_Y.mkv"  [debug] ffmpeg command line: avconv -y -i "file:Michael Jackson - Billie Jean (C fficial Uideo)-Zi_XLOBDo_R.f135.mp4" -i "file:Michae1 Jackson - Billie Jean (Off icial Uideo)-Zi_XLOBDo_E.f171.webm" -c copy -map "8:v:8" -map "1:a:8" "file:Mic} ael Jackson - Billie Jean (Official Uideo)-Zi_XLOBDo_Y.temp.mkv"  Deleting original file Michael Jackson - Billie Jean (Official Uideo)-Zi_XLOBDo_ Y.f135.mp4 (pass -k to keep)  Deleting original file Michael Jackson - Billie Jean (Official Uideo)-Zi_XLOBDo_ Y.f171.webm (pass -k to keep)

**Comment by ChangelingSpy** [comment]
Please try specifying the parameter "-f mp4" when downloading a video.

**Comment by js017** [comment]
Ok. Thanks.
