### ISSUE TITLE
Youtube video description fails and tiny thumbnail picture

### ISSUE THREAD

**Issue by arisboch** [rg3/youtube-dl#14079]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.27.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.27.1**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
casval@casval-X6815 /tmp % youtube-dl -v  --get-description https://www.youtube.com/watch\?v\=BryHihkw7uo        
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--get-description', u'https://www.youtube.com/watch?v=BryHihkw7uo']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 2.7.13 - Linux-4.10.0-33-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: avconv 3.2.4-1build2, avprobe 3.2.4-1build2, ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: unable to extract uploader nickname
[debug] Default format spec: bestvideo+bestaudio/best
```
---
The extraction of the video description fails (and the program also gives a wrong error message about a missing uploader nickname, even though the nickname is extracted). The extracted thumbnail also is very tiny even when I tried to download 720p videos.

**Comment by zouhair** [comment]
Youtube has had some graphic changes that may be the cause of this

**Comment by yliharma** [comment]
Same thing here for the mini thumbnail but I do get the description:

```
youtube-dl -v -e --get-thumbnail --get-description https://www.youtube.com/watch?v=Ch_2MBzfmXY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-e', u'--get-thumbnail', u'--get-description', u'https://www.youtube.com/watch?v=Ch_2MBzfmXY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 2.7.6 - Linux-4.4.0-81-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg 3.3.1, ffprobe 3.3.1
[debug] Proxy map: {}
WARNING: unable to extract uploader nickname
[debug] Default format spec: bestvideo+bestaudio/best
Travis Strikes Again: PAX West Trailer - Nintendo Switch
https://i.ytimg.com/vi/Ch_2MBzfmXY/default.jpg
```

**Comment by MacDada** [comment]
```
$ youtube-dl --version
2017.08.27.1
$ youtube-dl -j https://www.youtube.com/watch?v=V7oiro8tYA4 | grep -Po '"thumbnail":.*?[^\\]",'
WARNING: unable to extract uploader nickname
"thumbnail": "https://i.ytimg.com/vi/V7oiro8tYA4/default.jpg",
```

`youtube-dl` now returns a `default` thumb: https://i.ytimg.com/vi/V7oiro8tYA4/default.jpg

I'm quite sure it used to return `maxresdefault` thumb: https://i.ytimg.com/vi/V7oiro8tYA4/maxresdefault.jpg

Question: is it going to be "fixed" and `youtube-dl` will return `maxresdefault` thumbs or should I generate thumb urls by myself, without the use of `youtube-dl` for that matter?
