### ISSUE TITLE
Not downloading Youtube channel videos at all now

### ISSUE THREAD

**Issue by speedily** [rg3/youtube-dl#14072]
entering: command in windows "youtube-dl https://www.youtube.com/user/hiteshitube/videos" worked perfectly fine till last night but not working today. reason it says  videos found in playlist is 0.

I found some apps called "Free YouTube Download" from DVDSoft that works fine in detecting total number of videos in this playlist in this case but needs at premium account to download videos.

also last night windows  defender tried to block malware in youtube-dl.exe, but I bypassed it and it worked fine, tonight I didnt get any such option.

I bet there is some change in youtube.com due to which the error occured. however I think there must be an api or something to fix this.

plz help.

**Comment by ONAPARTYROCK** [comment]
Same issue as you.  I have a batch file that runs this command (among others):
youtube-dl -i --skip-download  --simulate --verbose https://www.youtube.com/channel/UUEpT67dXwUla11Wsu4VW2DQ/videos > log.txt

Up until today I would get results like this:
[youtube:channel] UCEpT67dXwUla11Wsu4VW2DQ: Downloading channel page
[youtube:playlist] UUEpT67dXwUla11Wsu4VW2DQ: Downloading webpage
[download] Downloading playlist: Uploads from Graham & Pie
[youtube:playlist] UUEpT67dXwUla11Wsu4VW2DQ: Downloading page #1
[youtube:playlist] UUEpT67dXwUla11Wsu4VW2DQ: Downloading page #2
[youtube:playlist] playlist Uploads from Graham & Pie: Downloading 276 videos
[download] Downloading video 1 of 276
[youtube] ytPwLOpWdrI: Downloading webpage
[youtube] ytPwLOpWdrI: Downloading video info webpage
[youtube] ytPwLOpWdrI: Extracting video information
[youtube] ytPwLOpWdrI: Downloading MPD manifest
[download] Downloading video 2 of 276
[youtube] F1sSU7mM-Jc: Downloading webpage
[youtube] F1sSU7mM-Jc: Downloading video info webpage
[youtube] F1sSU7mM-Jc: Extracting video information
[youtube] F1sSU7mM-Jc: Downloading MPD manifest
...
[download] Finished downloading playlist: Uploads from Graham & Pie


Today I get:
[youtube:channel] UCEpT67dXwUla11Wsu4VW2DQ: Downloading channel page
[youtube:channel] UCEpT67dXwUla11Wsu4VW2DQ: Downloading page #1
[download] Downloading playlist: UCEpT67dXwUla11Wsu4VW2DQ
[youtube:channel] playlist UCEpT67dXwUla11Wsu4VW2DQ: Downloading 0 videos
[download] Finished downloading playlist: UCEpT67dXwUla11Wsu4VW2DQ


Something I noticed that change on youtube is the page with the videos now automatically loads more videos as you scroll down.
