### ISSUE TITLE
Geo Bypass support for cmt.ca (Canadian)

### ISSUE THREAD

**Issue by menachemshapiro** [rg3/youtube-dl#14081]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.27.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.27.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl --verbose  --geo-bypass --geo-bypass-country CA  http://www.cmt.ca/artist/corb-lund/video/corb-lund-special-memphis-sun
[debug] System config: []
[debug] User config: [u'-f', u'18/worst', u'-o', u'%(title)s-%(id)s.%(ext)s', u'-c', u'-i', u'--restrict-filenames']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--geo-bypass', u'--geo-bypass-country', u'CA', u'http://www.cmt.ca/artist/corb-lund/video/corb-lund-special-memphis-sun']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 2.7.13 - Linux-4.10.0-32-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 99.224.207.234 (CA) as X-Forwarded-For.
[generic] corb-lund-special-memphis-sun: Requesting header
WARNING: Falling back on generic information extractor.
[generic] corb-lund-special-memphis-sun: Downloading webpage
[generic] corb-lund-special-memphis-sun: Extracting information
[download] Downloading playlist: Artist | Corb Lund Special - Memphis Sun
[generic] playlist Artist | Corb Lund Special - Memphis Sun: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Using fake IP 99.238.173.172 (CA) as X-Forwarded-For.
[ThePlatform] xikKdqBmTPJE: Downloading SMIL data
ERROR: This content is not available in your location.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 295, in _real_extract
    formats, subtitles = self._extract_theplatform_smil(smil_url, video_id)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 42, in _extract_theplatform_smil
    raise ExtractorError(error_element.attrib['abstract'], expected=True)
ExtractorError: This content is not available in your location.

[download] Finished downloading playlist: Artist | Corb Lund Special - Memphis Sun

```

---

---

### Link
http://www.cmt.ca/artist/corb-lund/video/corb-lund-special-memphis-sun

---

### Description of your *issue*, suggested solution and other information

I'm not located in Canada, but would like to download videos from www.cmt.ca using --geo-bypass. It's not working at the moment, as you can see in the logs above. Although I'm not in canada and cannot successfully download a video, it looks like the site itself is supported, and it is just the --geo-bypass restrictions which are not. 

I saw this commit for another canadian site, and thought it might be trivial to do it for this site as well: https://github.com/rg3/youtube-dl/commit/0830f3e04842a58eb563962940ceb2bed27aac1f

**Comment by dstftw** [comment]
`--geo-bypass-country CA` is effectively equals to aforementioned commit. If it does not work then it's not possible to bypass geo restriction using this mechanism.
