### ISSUE TITLE
Download an entire channel does not work anymore

### ISSUE THREAD

**Issue by pprw** [rg3/youtube-dl#14094]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.27.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.27.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl https://www.youtube.com/user/caseyneistat/videos -v 
[debug] System config: []
[debug] User config: ['-o', '%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/user/caseyneistat/videos', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 3.5.4 - Linux-4.12.0-1-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:user] caseyneistat: Downloading channel page
[youtube:user] caseyneistat: Downloading page #1
[download] Downloading playlist: caseyneistat
[youtube:user] playlist caseyneistat: Downloading 0 videos
[download] Finished downloading playlist: caseyneistat

...
<end of log>
```

---

---

### Description of your *issue*, suggested solution and other information

I use to watch channel in shuffle mode with mpv and the command `mpv --ytdl --shuffle https://www.youtube.com/user/caseyneistat/videos`. It doesn't work anymore. I first opened a bug report in [mpv github ](https://github.com/mpv-player/mpv/issues/4823)and it seemes the bug is related to youtube-dl. Indeed, downloading the entire channel doesn't work.

**Comment by dkl3** [comment]
I have also had this issue. I'd appreciate a fix from anyone, thanks.

**Comment by YoshiEnVerde** [comment]
Me too... AFAIK, this issue started around 3 days ago.

**Comment by chtk** [comment]
This has been reported before. See #14083. A solution has been posted there as well.
