### ISSUE TITLE
Unable to download from videolectures.net: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN

### ISSUE THREAD

**Issue by jrao1** [rg3/youtube-dl#14099]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
 youtube-dl -f http-416-0 --playlist-start 9 --sleep-interval 3600 --verbose http://videolectures.net/deeplearning2017_montreal/
[debug] System config: [u'-o', u'%(id)s-%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'http-416-0', u'--playlist-start', u'9', u'--sleep-interval', u'3600', u'--verbose', u'http://videolectures.net/deeplearning2017_montreal/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.02
[debug] Python version 2.7.12 - Linux-4.4.0-1022-aws-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 3.3.3-1ubuntu1, avprobe 3.3.3-1ubuntu1, ffmpeg 3.3.3-1ubuntu1, ffprobe 3.3.3-1ubuntu1
[debug] Proxy map: {}
[Viidea] deeplearning2017_montreal: Downloading webpage
[Viidea] 25892: Downloading JSON metadata
[Viidea] 25892: Downloading webpage
[download] Downloading playlist: Deep Learning (DLSS) and Reinforcement Learning (RLSS) Summer School, Montreal 2017
[Viidea] playlist Deep Learning (DLSS) and Reinforcement Learning (RLSS) Summer School, Montreal 2017: Collected 37 video ids (downloading 29 of them)
[download] Downloading video 1 of 29
[Viidea] deeplearning2017_urtasun_structured_models: Downloading webpage
[Viidea] 25935: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 503, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2168, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```

**Comment by dstftw** [comment]
>You are not allowed to view this video lecture.
