### ISSUE TITLE
Unable to download from Pluralsight.com using command Prompt because of Captcha

### ISSUE THREAD

**Issue by kpa1kumar** [rg3/youtube-dl#14098]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'C:\\Plural\\SpringFundamentals\\
cookies.txt', '-o', 'I:\\Plural\\Spring Fundamentals\\%(autonumber)s -%(id)s- %(
title)s.%(ext)s', '--min-sleep-interval', '60', '--max-sleep-interval', '66', '-
-all-subs', 'https://app.pluralsight.com/library/courses/spring-fundamentals/tab
le-of-contents/', '--playlist-start', '1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.09.02
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] spring-fundamentals: Downloading course JSON
[pluralsight:course] spring-fundamentals: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HT
TPError()); please report this issue on https://yt-dl.org/bug . Make sure you ar
e using the latest version; type  youtube-dl -U  to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\bu
ild\youtube_dl\extractor\common.py", line 503, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\bu
ild\youtube_dl\YoutubeDL.py", line 2168, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I followed the below Procedure

youtube-dl.exe --cookies C:\Plural\cookies.txt -o "I:\Plural\Spring Fundamentals%(autonumber)s -%(id)s- %(title)s.%(ext)s" --min-sleep-interval 60 --max-sleep-interval 66 --all-subs https://app.pluralsight.com/library/courses/spring-fundamentals/table-of-contents/ --playlist-start 1

It was working fine for a couple of days for the above syntax but now i'm getting the error like

ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HT
TPError()); please report this issue on https://yt-dl.org/bug . Make sure you ar
e using the latest version; type youtube-dl -U to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.

But i updated the cookies file, youtube-dl.exe and i checked in the browser video is playing.

**Comment by dstftw** [comment]
For any further investigations you must provide account credentials.

**Comment by kpa1kumar** [comment]
how to provide account credentials? is it visible to everyone?

**Comment by kpa1kumar** [comment]
username: pavankumar-konduru
password: P@1sidhhuk

**Comment by kpa1kumar** [comment]
@dstftw Username: pavankumar-konduru
               Password: P@1sidhhuk

**Comment by dstftw** [comment]
**Do not** post password here.

**Comment by kpa1kumar** [comment]
@dstftw then how to communicate with you?

**Comment by kpa1kumar** [comment]
@dstftw so can i change my credentials

**Comment by timofonic** [comment]
@kpa1kumar I'm not part of this project, but I would suggest you contact the developers directly or lurk at ircs://irc.freenode.net/#youtube-dl

**Comment by shanyuen** [comment]
Last week i meet with this problem, but 2 days ago it's work again.
I think pluralsight prevent account that doing non-stop download.
Then i tried to limit my download activity 6 hours per day and of course with 2 minutes per session.
I manually create download batch job with each single playlist item.

**Comment by PracticeX** [comment]
Does anyone know a workaround to the new reCAPTCHA that guards the site? After downloading a couple courses, I got a 403 error from running youtube-dl. When I went on the site and click login, I was presented with a reCAPTCHA which I think is causing the 403. Like the above comment said, the reCAPTCHA went away after a week or so, but it comes back as soon as I started downloading again. I tried passing a cookie file, setting --sleep-interval to 30, and I still got it. From talking to pluralsight support, this is caused by youtube-dl usage repeatedly scrapping on their site.

**Comment by agnel** [comment]
> I manually create download batch job with each single playlist item.

@shanyuen can you please let us know how do you create a download batch job as you mentioned above?

**Comment by imrankhan441** [comment]
i can't understand the solution please help me out

**Comment by divya369** [comment]
I was downloading pluralsight courses, but now I don't know why the speed is reduced to approximately 20 kb/s even if the speed of the internet is in MB/s

**Comment by dstftw** [comment]
Most likely expired cookies.

**Comment by michaelcoyote** [comment]
I'm also running into this issue and I'm willing to work with someone on this in testing..

```
[download] Downloading video 1 of 148
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```
