### ISSUE TITLE
Unable to download from Pluralsight.com using command Prompt because of Captcha

### ISSUE THREAD

**Issue by kpa1kumar** [rg3/youtube-dl#14097]
I followed the below Procedure

youtube-dl.exe --cookies C:\Plural\cookies.txt  -o "I:\Plural\Spring Fundamentals\%(autonumber)s -%(id)s- %(title)s.%(ext)s" --min-sleep-interval 60 --max-sleep-interval 66 --all-subs https://app.pluralsight.com/library/courses/spring-fundamentals/table-of-contents/ --playlist-start 1

It was working fine for a couple of days for the above syntax but now i'm getting the error like

**ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HT
TPError()); please report this issue on https://yt-dl.org/bug . Make sure you ar
e using the latest version; type  youtube-dl -U  to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.**

But i updated the cookies file, youtube-dl.exe and i checked in the browser video is playing.

Please help me out & let me know the solution.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
