### ISSUE TITLE
PornHub Playlist downloading is very slow

### ISSUE THREAD

**Issue by Rainyjour** [rg3/youtube-dl#14092]
Guys,

I have a broadband connection (~30MB/s) and when I wanna download a playlist i just have 40-200 KB/s :(

Can anyone tell me why is it freaking slow? I use latest Windows exe version.

Any way to download them faster? Sth about 2MB/s is enough

**Comment by PuffingtonToast** [comment]
It's not this script, its pornhub. The servers at pornhub rate-limit your download speed because they need save bandwidth for other users.

**Comment by Rainyjour** [comment]
If it's not about you, Can u tell me why I can download at 2MB/s using IDM?

**Comment by Hrxn** [comment]
You sure you really get 2 MB/s with IDM constantly? And not just at the beginning of the download, for the first couple seconds or something.

**Comment by dstftw** [comment]
Pornhub shapes bandwidth. Most likely IDM's download is multithreaded.
