### ISSUE TITLE
Add site-support for Zpravy Seznam.cz (CZech news site)

### ISSUE THREAD

**Issue by breznak** [rg3/youtube-dl#14102]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)
---

### The following sections concretize particular purposed issues, you can erase any section (the 

The example single video URL is: 
https://www.seznam.cz/zpravy/clanek/jejich-svet-na-nas-utoci-je-lepsi-branit-se-na-jejich-pisecku-rika-reziser-a-major-v-zaloze-marhoul-35990 

The pattern is: 
https://www.seznam.cz/zpravy/clanek/some-words-with-dashes-NNNN<numeric id>

Thank you,

**Comment by lki2019** [comment]
https://v39-a.sdn.szn.cz/v_39/vmd_5999c902ea707c67d8e267a9/1503250723?fl=mdk,432f65a0|hlsp2,h264_aac_1080p_ts,3,VOD

**Comment by che0** [comment]
Pull request here: #14616
