### ISSUE TITLE
[youtube] Download from channels doesnt work

### ISSUE THREAD

**Issue by xsteadfastx** [rg3/youtube-dl#14115]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v https://www.youtube.com/user/DickensDucktailDick
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/user/DickensDucktailDick']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Git HEAD: fd0b8fc
[debug] Python version 3.6.2 - Linux-4.10.0-21-generic-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2
[debug] Proxy map: {}
[youtube:user] DickensDucktailDick: Downloading channel page
[youtube:user] DickensDucktailDick: Downloading page #1
[download] Downloading playlist: DickensDucktailDick
[youtube:user] playlist DickensDucktailDick: Downloading 0 videos
[download] Finished downloading playlist: DickensDucktailDick

$ youtube-dl -v https://www.youtube.com/user/Insi456
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/user/Insi456']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Git HEAD: fd0b8fc
[debug] Python version 3.6.2 - Linux-4.10.0-21-generic-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2
[debug] Proxy map: {}
[youtube:user] Insi456: Downloading channel page
[youtube:user] Insi456: Downloading page #1
[download] Downloading playlist: Insi456
[youtube:user] playlist Insi456: Downloading 0 videos
[download] Finished downloading playlist: Insi456

```
---

### Description of your *issue*, suggested solution and other information

Channel downloading from youtube stopped working a few days ago. I guess its  because of the redesign. I followed some bugreports (#14083) and this are closed now with a commit that should make it work again. So i upgraded youtube-dl and its still impossible for me to download from this two channels: https://www.youtube.com/user/Insi456 and https://www.youtube.com/user/DickensDucktailDick. There are videos in this channels so i dont know what the problem could be. I read in the bug reports that it can have something to do with the number of videos on this channel. But i thought this got fixed.

**Comment by rautamiekka** [comment]
Hmm, that's odd, cuz right at this moment I'm downloading playlists with 2017.09.02, while it didn't work with versions before that after the redesign.

**Comment by xsteadfastx** [comment]
@rautamiekka it works for some but with this not. Could you try them?

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
