### ISSUE TITLE
how to specify quality format with dailymotion and vimeo

### ISSUE THREAD

**Issue by kiranbulley** [rg3/youtube-dl#14119]
`[how can i download video from dailymotion with specific quality format]`
`[youtube-dl -v --list-formats http://www.dailymotion.com/video/x5yzn9o ]`

version: 2017.09.02

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--list-formats', u'http://www.dailymotion.com/video/x5yzn9o']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.18
[debug] Python version 2.7.13 - Darwin-15.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[dailymotion] x5yzn9o: Downloading webpage
[dailymotion] x5yzn9o: Downloading m3u8 information
[dailymotion] x5yzn9o: Downloading m3u8 information
[dailymotion] x5yzn9o: Downloading m3u8 information
[dailymotion] x5yzn9o: Downloading m3u8 information
[dailymotion] x5yzn9o: Downloading m3u8 information
[dailymotion] x5yzn9o: Downloading m3u8 information
[dailymotion] x5yzn9o: Downloading m3u8 information
[info] Available formats for x5yzn9o:
format code extension resolution note
hls-144-0 mp4 176x96 105k , avc1.42000b, mp4a.40.5
hls-144-1 mp4 176x96 105k , avc1.42000b, mp4a.40.5
hls-144-2 mp4 176x96 105k , avc1.42000b, mp4a.40.5
hls-144-3 mp4 176x96 105k , avc1.42000b, mp4a.40.5
hls-240-0 mp4 320x184 246k , avc1.42000d, mp4a.40.5
hls-240-1 mp4 320x184 246k , avc1.42000d, mp4a.40.5
hls-240-2 mp4 320x184 246k , avc1.42000d, mp4a.40.5
hls-240-3 mp4 320x184 246k , avc1.42000d, mp4a.40.5
hls-380-0 mp4 512x288 460k , avc1.420016, mp4a.40.5
hls-380-1 mp4 512x288 460k , avc1.420016, mp4a.40.5
hls-380-2 mp4 512x288 460k , avc1.420016, mp4a.40.5
hls-380-3 mp4 512x288 460k , avc1.420016, mp4a.40.5
hls-480-0 mp4 848x480 836k , avc1.64001f, mp4a.40.2
hls-480-1 mp4 848x480 836k , avc1.64001f, mp4a.40.2
hls-480-2 mp4 848x480 836k , avc1.64001f, mp4a.40.2
hls-480-3 mp4 848x480 836k , avc1.64001f, mp4a.40.2
hls-720-0 mp4 1280x720 2149k , avc1.64001f, mp4a.40.2
hls-720-1 mp4 1280x720 2149k , avc1.64001f, mp4a.40.2
hls-720-2 mp4 1280x720 2149k , avc1.64001f, mp4a.40.2
hls-720-3 mp4 1280x720 2149k , avc1.64001f, mp4a.40.2
hls-1080-0 mp4 1920x1080 6221k , avc1.640028, mp4a.40.2
hls-1080-1 mp4 1920x1080 6221k , avc1.640028, mp4a.40.2
hls-1080-2 mp4 1920x1080 6221k , avc1.640028, mp4a.40.2
hls-1080-3 mp4 1920x1080 6221k , avc1.640028, mp4a.40.2
http-144 mp4 176x144
http-240 mp4 320x240
http-380 mp4 512x384
http-480 mp4 848x480
http-720 mp4 1280x720
http-1080 mp4 1920x1080 (best)

<end of log>
```

---

Single video: http://www.dailymotion.com/video/x5yzn9o

---

### Description of *issue*

i have run the above command for that i got result which i have mention above but how should i specify quality code in command to download video from dailymotion and vimeo.

**Comment by kayb94** [comment]
https://github.com/rg3/youtube-dl#video-format-options

**Comment by kiranbulley** [comment]
hi ,
youtube-dl -v  http://www.dailymotion.com/video/x3hnk8x -F best[height=360] "output path"

for above command i am getting following result

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.dailymotion.com/video/x3hnk8x', u'-F', u'best[height=360]', u'/Applications/MAMP/htdocs/video_main']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.18
[debug] Python version 2.7.13 - Darwin-15.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[dailymotion] x3hnk8x: Downloading webpage
[dailymotion] x3hnk8x: Downloading m3u8 information
[dailymotion] x3hnk8x: Downloading m3u8 information
[dailymotion] x3hnk8x: Downloading m3u8 information
[dailymotion] x3hnk8x: Downloading m3u8 information
[dailymotion] x3hnk8x: Downloading m3u8 information
[dailymotion] x3hnk8x: Downloading m3u8 information
[dailymotion] x3hnk8x: Downloading m3u8 information
[info] Available formats for x3hnk8x:
format code  extension  resolution note
hls-144-0    mp4        176x96      105k , avc1.42000b, mp4a.40.5
hls-144-1    mp4        176x96      105k , avc1.42000b, mp4a.40.5
hls-144-2    mp4        176x96      105k , avc1.42000b, mp4a.40.5
hls-144-3    mp4        176x96      105k , avc1.42000b, mp4a.40.5
hls-240-0    mp4        320x184     246k , avc1.42000d, mp4a.40.5
hls-240-1    mp4        320x184     246k , avc1.42000d, mp4a.40.5
hls-240-2    mp4        320x184     246k , avc1.42000d, mp4a.40.5
hls-240-3    mp4        320x184     246k , avc1.42000d, mp4a.40.5
hls-380-0    mp4        512x288     460k , avc1.420016, mp4a.40.5
hls-380-1    mp4        512x288     460k , avc1.420016, mp4a.40.5
hls-380-2    mp4        512x288     460k , avc1.420016, mp4a.40.5
hls-380-3    mp4        512x288     460k , avc1.420016, mp4a.40.5
hls-480-0    mp4        848x480     836k , avc1.64001f, mp4a.40.2
hls-480-1    mp4        848x480     836k , avc1.64001f, mp4a.40.2
hls-480-2    mp4        848x480     836k , avc1.64001f, mp4a.40.2
hls-480-3    mp4        848x480     836k , avc1.64001f, mp4a.40.2
hls-720-0    mp4        1272x720   2149k , avc1.64001f, mp4a.40.2
hls-720-1    mp4        1272x720   2149k , avc1.64001f, mp4a.40.2
hls-720-2    mp4        1272x720   2149k , avc1.64001f, mp4a.40.2
hls-720-3    mp4        1272x720   2149k , avc1.64001f, mp4a.40.2
hls-1080-0   mp4        1592x904   6221k , avc1.640028, mp4a.40.2
hls-1080-1   mp4        1592x904   6221k , avc1.640028, mp4a.40.2
hls-1080-2   mp4        1592x904   6221k , avc1.640028, mp4a.40.2
hls-1080-3   mp4        1592x904   6221k , avc1.640028, mp4a.40.2
http-144     mp4        176x144    
http-240     mp4        320x240    
http-380     mp4        512x384    
http-480     mp4        848x480    
http-720     mp4        1280x720   
http-1080    mp4        1920x1080  (best)
ERROR: u'best[height=360]' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:best[height=360]" ) to search YouTube
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1861, in _real_extract
    % (url, url), expected=True)
ExtractorError: u'best[height=360]' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:best[height=360]" ) to search YouTube




Actually i am struggling with how should i specify quality code in command in case of dailymotion and vimeo.

**Comment by kayb94** [comment]
Have you read the link that I posted?
`-f, --format FORMAT              Video format code, see the "FORMAT
                                 SELECTION" for all the info`

**Comment by rautamiekka** [comment]
>youtube-dl -v http://www.dailymotion.com/video/x3hnk8x -F best[height=360] "output path"

That's illegal syntax in 2 ways: the `"output path"` is actually just another vid link to youtube-dl (you'll use `--output "..."` to designate location and/or filename format) and the `-F best[height=360]` should have `-f` instead.

Seeing it's a comparison between Linux distros which'll possibly contain text in a window, you'll want one of the best, and this'll get you both the very best vid and audio and combines them using FFmpeg or avconv (but if it fails it takes the best ready-to-view combination and doesn't use FFmpeg/avconv), saved as `~/Downloads/_DailyMotion_/UPLOADER_NAME_OR_ID/VIDEO_NAME WIDTHxHEIGHT dailymotion#x3hnk8x#.EXTENSION` (**_however be warned I haven't used youtube-dl on a Linux yet, so this might not work as intended_**):

```
youtube-dl --ignore-config --verbose --verbose --ignore-errors --no-mark-watched --format 'bestvideo+bestaudio/best' --audio-format best --audio-quality 0 --output '~/Downloads/_DailyMotion_/%(uploader_id)s/%(title)s %(resolution)s dailymotion#%(id)s#.%(ext)s' -x --no-playlist --console-title --no-mtime --retries infinite --continue --no-overwrites --fragment-retries infinite 'http://www.dailymotion.com/video/x3hnk8x'
```

But if you're fine with 720p, this does that:
```
youtube-dl --ignore-config --verbose --verbose --ignore-errors --no-mark-watched --format 'bestvideo[height=720]+bestaudio/best[height=720]' --audio-format best --audio-quality 0 --output '~/Downloads/_DailyMotion_/%(uploader_id)s/%(title)s %(resolution)s dailymotion#%(id)s#.%(ext)s' -x --no-playlist --console-title --no-mtime --retries infinite --continue --no-overwrites --fragment-retries infinite 'http://www.dailymotion.com/video/x3hnk8x'
```

This'll do 480p:
```
youtube-dl --ignore-config --verbose --verbose --ignore-errors --no-mark-watched --format 'bestvideo[height=480]+bestaudio/best[height=480]' --audio-format best --audio-quality 0 --output '~/Downloads/_DailyMotion_/%(uploader_id)s/%(title)s %(resolution)s dailymotion#%(id)s#.%(ext)s' -x --no-playlist --console-title --no-mtime --retries infinite --continue --no-overwrites --fragment-retries infinite 'http://www.dailymotion.com/video/x3hnk8x'
```

**Comment by kiranbulley** [comment]
thank you
