### ISSUE TITLE
Das Erste / ARD / german television online media

### ISSUE THREAD

**Issue by ctshh** [rg3/youtube-dl#14114]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v -F "http://www.daserste.de/unterhaltung/show/klein-gegen-gross/sendung/index.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'http://www.daserste.de/unterhaltung/show/klein-gegen-gross/sendung/index.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.02
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] index: Requesting header
WARNING: Falling back on generic information extractor.
[generic] index: Downloading webpage
[generic] index: Extracting information
WARNING: [generic] index: Failed to parse JSON Expecting ',' delimiter: line 4 column 23 (char 59)
ERROR: Unsupported URL: http://www.daserste.de/unterhaltung/show/klein-gegen-gross/sendung/index.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2116, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 148, column 153
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2989, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.daserste.de/unterhaltung/show/klein-gegen-gross/sendung/index.html

```

---

- Single video: http://www.daserste.de/unterhaltung/show/klein-gegen-gross/videos/klein-gegen-gross-das-unglaubliche-duell-video-104.html

---

### Description of your *issue*, suggested solution and other information

The video is not downloaded, an error message (see above) is given.

**Comment by kayb94** [comment]
You're on the wrong page. Click on the video and copy the url in the url bar or right click on the video and save the link it points to. Use that url instead then. What you showed, is not the actual video page, even though there is a play button.

**Comment by ctshh** [comment]
I see - thank you very much for your help!

**Comment by kayb94** [comment]
no problem

**Comment by rbrito** [comment]
This can be closed, then, right?

**Comment by ctshh** [comment]
yes, please.

And thanks again!

**Comment by Hrxn** [comment]
@ctshh You can close it for yourself, would be nice if you did this.

**Comment by ctshh** [comment]
Of course, sorry.
And, again, thank you for a very (very very) cool tool.
