### ISSUE TITLE
metadata write video id

### ISSUE THREAD

**Issue by Joseph65** [rg3/youtube-dl#14117]
Can i write to the downloaded file metadata with --add-metadata the video id or the full url of the video downloaded for example this link "https://www.youtube.com/watch?v=-FyjEnoIgTM" where the id is -FyjEnoIgTM or the full url, in something like the Now Playing tag.

**Comment by dstftw** [comment]
Full URL is already written with `--add-metadata`.

**Comment by Joseph65** [comment]
i dont see the url with vlc 
on media information tab 
![screenshot_2017-09-05_12-18-34](https://user-images.githubusercontent.com/12629965/30073735-97b17c8a-9234-11e7-9ee5-cf152017a72c.png)
or on metadata tab
![screenshot_2017-09-05_12-19-06](https://user-images.githubusercontent.com/12629965/30073749-a654f9f6-9234-11e7-8765-477889428527.png)

**Comment by Joseph65** [comment]
Ok currenly tagging of url only works with mkv format as the tag "Purl", mp4 doesn't show the url.
