### ISSUE TITLE
 [Question]youtube-dl and aria2c can not work together

### ISSUE THREAD

**Issue by xiayutian015** [rg3/youtube-dl#14120]
[ Question]
youtube-dl and aria2c can not work together， please see log: you can search by "[debug] Invoking downloader on ", when i download the first vedio (mp4 and m4a), it can use aria2c, but the second vedio was not use aria2c to download file, how should i do it?

C:\Users\tony>youtube-dl -o "E:/%(uploader)s/%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s" --external-downloader aria2c --external-downloader-args "-j 5 -x 16 -s 16 -k 1M" https://www.youtube.com/playlist?list=PL5NG-eEzvTtjfqfzoCvS0uo2k7cfgNDL2 -f (137/136/135/134)+(140/m4a) -i --no-part --no-mtime --write-sub --all-subs -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'E:/%(uploader)s/%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s', '--external-downloader', 'aria2c', '--external-downloader-args', '-j 5 -x 16 -s 16 -k 1M', 'https://www.youtube.com/playlist?list=PL5NG-eEzvTtjfqfzoCvS0uo2k7cfgNDL2', '-f', '(137/136/135/134)+(140/m4a)', '-i', '--no-part', '--no-mtime', '--write-sub', '--all-subs', '-v']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2017.07.23
[debug] Python version 3.6.2 - Windows-10-10.0.15063-SP0
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[youtube:playlist] PL5NG-eEzvTtjfqfzoCvS0uo2k7cfgNDL2: Downloading webpage
[download] Downloading playlist: Selenium Hybrid Framework by Bhanu Pratap
[youtube:playlist] playlist Selenium Hybrid Framework by Bhanu Pratap: Downloading 14 videos
[download] Downloading video 1 of 14
[youtube] CLAFMnQPIVQ: Downloading webpage
[youtube] CLAFMnQPIVQ: Downloading video info webpage
[youtube] CLAFMnQPIVQ: Extracting video information
WARNING: unable to extract uploader nickname
WARNING: video doesn't have subtitles
[youtube] CLAFMnQPIVQ: Downloading MPD manifest
[debug] Invoking downloader on 'https://r5---sn-pouxga5o-vu2s.googlevideo.com/videoplayback?id=08b00532740f2154&itag=136&source=youtube&requiressl=yes&mv=u&ms=au&pl=23&ei=NFOuWfSOMpPqVJ_vsYAJ&mm=31&mn=sn-pouxga5o-vu2s&ratebypass=yes&mime=video/mp4&gir=yes&clen=75739977&lmt=1485327690306171&dur=2422.333&mt=1504596331&signature=2E2C81F0EC2C99E4D02457BB5CC4CC0690990D3E.6DD9C17C09B7B0743650BE0C5BEE5D0CA45E3A13&key=dg_yt0&ip=5.254.89.171&ipbits=0&expire=1504618388&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,pl,ei,mm,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: E:\Bhanu Pratap\Selenium Hybrid Framework by Bhanu Pratap\01-Selenium Framework and Components of framework for Interview video-0.avi.f136.mp4
[debug] aria2c command line: aria2c -c -j 5 -x 16 -s 16 -k 1M --dir "E:\Bhanu Pratap\Selenium Hybrid Framework by Bhanu Pratap" --out "01-Selenium Framework and Components of framework for Interview video-0.avi.f136.mp4" --header "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)" --header "Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Encoding: gzip, deflate" --header "Accept-Language: en-us,en;q=0.5" "--check-certificate=true" -- "https://r5---sn-pouxga5o-vu2s.googlevideo.com/videoplayback?id=08b00532740f2154&itag=136&source=youtube&requiressl=yes&mv=u&ms=au&pl=23&ei=NFOuWfSOMpPqVJ_vsYAJ&mm=31&mn=sn-pouxga5o-vu2s&ratebypass=yes&mime=video/mp4&gir=yes&clen=75739977&lmt=1485327690306171&dur=2422.333&mt=1504596331&signature=2E2C81F0EC2C99E4D02457BB5CC4CC0690990D3E.6DD9C17C09B7B0743650BE0C5BEE5D0CA45E3A13&key=dg_yt0&ip=5.254.89.171&ipbits=0&expire=1504618388&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,pl,ei,mm,mn,ratebypass,mime,gir,clen,lmt,dur"

09/05 15:33:12 [NOTICE] Downloading 1 item(s)
[#937b8a 0B/0B CN:1 DL:0B]
09/05 15:33:13 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.
[#937b8a 72MiB/72MiB(99%) CN:1 DL:1.7MiB]
09/05 15:33:45 [NOTICE] Download complete: E:/Bhanu Pratap/Selenium Hybrid Framework by Bhanu Pratap/01-Selenium Framework and Components of framework for Interview video-0.avi.f136.mp4

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
937b8a|OK  |   2.2MiB/s|E:/Bhanu Pratap/Selenium Hybrid Framework by Bhanu Pratap/01-Selenium Framework and Components of framework for Interview video-0.avi.f136.mp4

Status Legend:
(OK):download completed.
[aria2c] Downloaded 75739977 bytes
[download] 100% of 72.23MiB
[debug] Invoking downloader on 'https://r5---sn-pouxga5o-vu2s.googlevideo.com/videoplayback?id=08b00532740f2154&itag=140&source=youtube&requiressl=yes&mv=u&ms=au&pl=23&ei=NFOuWfSOMpPqVJ_vsYAJ&mm=31&mn=sn-pouxga5o-vu2s&ratebypass=yes&mime=audio/mp4&gir=yes&clen=38545793&lmt=1485327714752976&dur=2426.903&mt=1504596331&signature=6EC58702049D96A3BA5E437165199D2A8DE5BBFC.5E5B927091BA09747EEF969C6D94B0939AF52531&key=dg_yt0&ip=5.254.89.171&ipbits=0&expire=1504618388&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,pl,ei,mm,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: E:\Bhanu Pratap\Selenium Hybrid Framework by Bhanu Pratap\01-Selenium Framework and Components of framework for Interview video-0.avi.f140.m4a
[debug] aria2c command line: aria2c -c -j 5 -x 16 -s 16 -k 1M --dir "E:\Bhanu Pratap\Selenium Hybrid Framework by Bhanu Pratap" --out "01-Selenium Framework and Components of framework for Interview video-0.avi.f140.m4a" --header "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)" --header "Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Encoding: gzip, deflate" --header "Accept-Language: en-us,en;q=0.5" "--check-certificate=true" -- "https://r5---sn-pouxga5o-vu2s.googlevideo.com/videoplayback?id=08b00532740f2154&itag=140&source=youtube&requiressl=yes&mv=u&ms=au&pl=23&ei=NFOuWfSOMpPqVJ_vsYAJ&mm=31&mn=sn-pouxga5o-vu2s&ratebypass=yes&mime=audio/mp4&gir=yes&clen=38545793&lmt=1485327714752976&dur=2426.903&mt=1504596331&signature=6EC58702049D96A3BA5E437165199D2A8DE5BBFC.5E5B927091BA09747EEF969C6D94B0939AF52531&key=dg_yt0&ip=5.254.89.171&ipbits=0&expire=1504618388&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,pl,ei,mm,mn,ratebypass,mime,gir,clen,lmt,dur"

09/05 15:33:45 [NOTICE] Downloading 1 item(s)
[#d71af2 0B/0B CN:1 DL:0B]
09/05 15:33:47 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.
[#d71af2 36MiB/36MiB(99%) CN:2 DL:1.8MiB]
09/05 15:34:08 [NOTICE] Download complete: E:/Bhanu Pratap/Selenium Hybrid Framework by Bhanu Pratap/01-Selenium Framework and Components of framework for Interview video-0.avi.f140.m4a

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
d71af2|OK  |   1.7MiB/s|E:/Bhanu Pratap/Selenium Hybrid Framework by Bhanu Pratap/01-Selenium Framework and Components of framework for Interview video-0.avi.f140.m4a

Status Legend:
(OK):download completed.
[aria2c] Downloaded 38545793 bytes
[download] 100% of 36.76MiB
[ffmpeg] Merging formats into "E:\Bhanu Pratap\Selenium Hybrid Framework by Bhanu Pratap\01-Selenium Framework and Components of framework for Interview video-0.avi.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:E:\Bhanu Pratap\Selenium Hybrid Framework by Bhanu Pratap\01-Selenium Framework and Components of framework for Interview video-0.avi.f136.mp4" -i "file:E:\Bhanu Pratap\Selenium Hybrid Framework by Bhanu Pratap\01-Selenium Framework and Components of framework for Interview video-0.avi.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:E:\Bhanu Pratap\Selenium Hybrid Framework by Bhanu Pratap\01-Selenium Framework and Components of framework for Interview video-0.avi.temp.mp4"
Deleting original file E:\Bhanu Pratap\Selenium Hybrid Framework by Bhanu Pratap\01-Selenium Framework and Components of framework for Interview video-0.avi.f136.mp4 (pass -k to keep)
Deleting original file E:\Bhanu Pratap\Selenium Hybrid Framework by Bhanu Pratap\01-Selenium Framework and Components of framework for Interview video-0.avi.f140.m4a (pass -k to keep)
[download] Downloading video 2 of 14
[youtube] hY9SvPGsnGU: Downloading webpage
[youtube] hY9SvPGsnGU: Downloading video info webpage
[youtube] hY9SvPGsnGU: Extracting video information
WARNING: unable to extract uploader nickname
WARNING: video doesn't have subtitles
[youtube] hY9SvPGsnGU: Downloading MPD manifest
[debug] Invoking downloader on 'https://r6---sn-pouxga5o-vu2s.googlevideo.com/videoplayback/id/858f52bcf1ac9c65/itag/136/source/youtube/requiressl/yes/mn/sn-pouxga5o-vu2s/mm/31/pl/23/mv/u/ms/au/ei/dVOuWYfGLMHSV93VtqgC/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/7078494/lmt/1498917432392511/dur/390.466/signature/28015468A2B260CA1406CCEFA78D64DFE473307A.56DBC760C898E768C1A057CA7439B1F414049B23/mt/1504596331/key/dg_yt0/ip/5.254.89.171/ipbits/0/expire/1504618453/sparams/ip,ipbits,expire,id,itag,source,requiressl,mn,mm,pl,mv,ms,ei,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 75
[download] Destination: E:\Bhanu Pratap\Selenium Hybrid Framework by Bhanu Pratap\02-SeleniumHybridFramework-1.f136.mp4
[download]  19.5% of ~5.05MiB at 603.38KiB/s ETA 02:18
ERROR: Interrupted by user

**Comment by dstftw** [comment]
aria2c does not support support segmented DASH. You must select format with plain http link, how to do so see format selection in FAQ.

**Comment by xiayutian015** [comment]
Hello， I don't know how to do, please help me, how can i download it
