### ISSUE TITLE
youtube-dl -F reports incorrect webm dimensions for format 43

### ISSUE THREAD

**Issue by pts** [rg3/youtube-dl#14125]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

```
$ youtube-dl -v -F https://youtu.be/2Aojn4ltkP0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'2Aojn4ltkP0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.02
[debug] Python version 2.7.6 - Linux-4.4.0-92-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, rtmpdump 2.4
[debug] Proxy map: {'auto': '...'}
[youtube] 2Aojn4ltkP0: Downloading webpage
[youtube] 2Aojn4ltkP0: Downloading video info webpage
[youtube] 2Aojn4ltkP0: Extracting video information
[youtube] 2Aojn4ltkP0: Downloading MPD manifest
[info] Available formats for 2Aojn4ltkP0:
format code  extension  resolution note
139          m4a        audio only DASH audio   48k , m4a_dash container, mp4a.40.5@ 48k (22050Hz), 558.51KiB
249          webm       audio only DASH audio   57k , opus @ 50k, 659.97KiB
250          webm       audio only DASH audio   76k , opus @ 70k, 879.90KiB
140          m4a        audio only DASH audio   95k , m4a_dash container, mp4a.40.2@128k (44100Hz), 1.09MiB
171          webm       audio only DASH audio   97k , vorbis@128k, 1.05MiB
251          webm       audio only DASH audio  132k , opus @160k, 1.49MiB
160          mp4        192x144    DASH video  110k , avc1.4d400c, 15fps, video only, 1.25MiB
133          mp4        320x240    DASH video  246k , avc1.4d400d, 15fps, video only, 2.79MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x240    small , mp4v.20.3, mp4a.40.2
18           mp4        320x240    medium , avc1.42001E, mp4a.40.2@ 96k
43           webm       640x360    medium , vp8.0, vorbis@128k (best)
```

In the last line, 640x360 is reported as the video dimensions. However, if I download the .webm file with `youtube-dl -f 43 https://youtu.be/2Aojn4ltkP0`, the file actually has 320x240.

This also affects `youtube-dl -f best`, because youtube-dl incorrectly selects format 43 in this case for some videos.

I've seen it happen to many videos, all with format 43. The video dimensions reported by youtube-dl was always 640x360, and the actual video dimensions were 27 different values between 176x144 and 640x356.

The expected fix would be correct dimension reporting for format 43, or at least putting a question mark after 640x360 in the output of `youtube-dl -F`.

**Comment by dstftw** [comment]
It's a hardcoded value that is valid in most cases. No real dimension for these formats provided.

**Comment by pts** [comment]
Have you considered my suggestion for an improvement of the accuracy of reporting?

> putting a question mark after 640x360 in the output of youtube-dl -F

**Comment by dstftw** [comment]
I don't see much point in that. All metadata is taken from meta sources and not actual videos. It's often incorrect. Putting marks in some cases will introduce even more ambiguity since other potentially incorrect metadata won't be marked. Moreover `?` is already used for unknown height.

**Comment by Fironet** [comment]
@dstftw Is this true for all sources supported by youtube-dl? As I've noticed this with Instagram, where it reported under resolution note 750x937 despite being 768x800, and additionally audio bitrates of Youtube resolution notes (which now all are 128kbps except for Opus, despite some items stating 192kbps). Was searching for past issues in case I'd missed more general issue that covers all this.
