### ISSUE TITLE
New Nicovideo Issue

### ISSUE THREAD

**Issue by dkl3** [rg3/youtube-dl#14135]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

 youtube-dl  http://www.nicovideo.jp/watch/sm18238488 --username USER --password USER -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.nicovideo.jp/watch/sm18238488', '--username', 'PRIVATE', '--password', 'PRIVATE', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.02
[debug] Python version 3.5.2 - Linux-4.4.0-81-generic-i686-with-LinuxMint-18.1-serena
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[niconico] Logging in
[niconico] sm18238488: Downloading webpage
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 1958, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/niconico.py", line 399, in _real_extract
    uploader_id = get_video_info(['ch_id', 'user_id']) or owner.get('id')
AttributeError: 'NoneType' object has no attribute 'get'

---

### Description of your *issue*, suggested solution and other information

I try and download a video with NicoVideo, and it gives this error. I tried to check for a recent bug report on this but i didn't see anything. Does anyone know the cause? thank you.

**Comment by epicgirl1998** [comment]
also had this bug

the bug is [this part](https://github.com/rg3/youtube-dl/blob/ee6a611665a1ee8583ce84bd9d36d03b6f697895/youtube_dl/extractor/niconico.py#L398-L400) always assuming a video has an owner (i think?)

i worked around it in my local copy by doing this:

```python
owner = api_data.get('owner', {})
uploader_id = get_video_info(['ch_id', 'user_id']) or owner and owner.get('id')
uploader = get_video_info(['ch_name', 'user_nickname']) or owner and owner.get('nickname')
```

**Comment by dkl3** [comment]
Maybe that can be merged with this youtube-dl?
