### ISSUE TITLE
Download playlist Error --- KeyError: 'content_html'

### ISSUE THREAD

**Issue by lvguanming** [rg3/youtube-dl#14140]
## Maybe is unicode not support for Non-English
Error :   Download playlist Error --- KeyError: 'content_html'  
---
follow command:
`youtube-dl --download-archive archive.txt -f 'bestvideo[ext=mp4]+bestaudio/best' "https://www.youtube.com/playlist?list=PLATwx1z00HsdanKZcTMQEc-n_Bhu_aZ76"`

---
the output is
> [youtube:playlist] PLATwx1z00HsdanKZcTMQEc-n_Bhu_aZ76: Downloading webpage
> [download] Downloading playlist: 梁文道：一千零一夜
> [youtube:playlist] PLATwx1z00HsdanKZcTMQEc-n_Bhu_aZ76: Downloading page #1
> Traceback (most recent call last):  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>    "__main__", mod_spec)  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy. py", line 85, in _run_code
>    exec(code, run_globals)
>  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
>  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
>  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
>  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1958, in download
>  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
>  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 939, in process_ie_result
>  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 272, in _entries
> KeyError: 'content_html'

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
