### ISSUE TITLE
videos has no sound when downloading playlist.

### ISSUE THREAD

**Issue by azzamsa** [rg3/youtube-dl#14159]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```

$ youtube-dl -v -ci  -o "%(title)s.%(ext)s" https://www.youtube.com/playlist?list=PLd3UqWTnYXOkWWJd8flj3echGYm3y5dXo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-ci', u'-o', u'%(title)s.%(ext)s', u'https://www.youtube.com/playlist?list=PLd3UqWTnYXOkWWJd8flj3echGYm3y5dXo']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.02
[debug] Python version 2.7.13 - Linux-4.9.0-3-amd64-x86_64-with-debian-9.1
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLd3UqWTnYXOkWWJd8flj3echGYm3y5dXo: Downloading webpage
[download] Downloading playlist: Core Java With OCJP/SCJP-Language Fundamentals
[youtube:playlist] playlist Core Java With OCJP/SCJP-Language Fundamentals: Downloading 16 videos
[download] Downloading video 1 of 16
[youtube] eTXd89t8ngI: Downloading webpage
[youtube] eTXd89t8ngI: Downloading video info webpage
[youtube] eTXd89t8ngI: Extracting video information
[youtube] eTXd89t8ngI: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r4---sn-npoe7n7r.googlevideo.com/videoplayback?id=7935ddf3db7c9e02&itag=137&source=youtube&requiressl=yes&ei=xgG0WcrAKYvoowOQ7YugDA&ms=au&pl=24&mv=m&initcwndbps=243750&mm=31&mn=sn-npoe7n7r&ratebypass=yes&mime=video/mp4&gir=yes&clen=1700103706&lmt=1493175136271109&dur=4618.160&key=dg_yt0&signature=916638B94A9AEF27882E9820DED42CEFDFE93AE5.09071053829A700298FE2DA9658E4BD7A6BD0292&mt=1504969003&ip=36.82.102.181&ipbits=0&expire=1504990758&sparams=ip,ipbits,expire,id,itag,source,requiressl,ei,ms,pl,mv,initcwndbps,mm,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] Resuming download at byte 4193280
[download] Destination: Core Java with OCJP_SCJP  - Language Fundamentals Part-1 _ Java Identifiers and Reserved Words.f137.mp4
[download]   0.4% of 1.58GiB at 1019.67KiB/s ETA 27:02^C
ERROR: Interrupted by user
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

there is other closed issue about this problem, but the problem caused of wrong youtube-dl parameter.

I do some experiment to ensure that I don't make wrong command.

- I try to download foo video playlist, after having some GB, I quit youtube-dl using `Ctlr+c` try to play them, and there is no sound. (I play the video-1.mp4.part).

- but when I downloading the single video (not a playlist) and stop the downloaad procces before completed, I play video-single-1.mp4.part, it has a sound.

- I try again and again, the two step above, and get the same result. the single video can be played with sound even it does not downloaded completely (still have .part extension), and the playlist video does not have a sound when not downloaded completely.

is the downloading process of youtube playlist have to be completed ( has no .part) to have a sound in a video ?

thank you.

---

I dont understand, why issue without this template rejected, and why some other without this tempate allowed.

**Comment by dstftw** [comment]
This depends on what concretely you're downloading that's why you must provide **concrete** video URLs with **concrete** verbose logs that clearly demonstrate the problem.
Youtube serves video and audio separately that are downloaded separately and then muxed. You'll not have any sound in video only file.

**Comment by azzamsa** [comment]
so that means I have to wait until all videos downloaded completely and the muxed with the audio ?

but why when I download the single video file, I can have a sound even it does not completely downloaded.

**Comment by dstftw** [comment]
Not all, each entry is muxed once its video and audio are downloaded.

>but why when I download the single video file, I can have a sound even it does not completely downloaded.

Again: provide **concrete** logs with **concrete** videos.
