### ISSUE TITLE
videos has no sound when downloading playlist.

### ISSUE THREAD

**Issue by azzamsa** [rg3/youtube-dl#14158]
``` bash
$ youtube-dl --version
2017.09.02
```
I do some experiment to ensure that I don't make wrong command.

- I try to download foo video playlist, after having some GB, I quit youtube-dl using `Ctlr+c` try to play them, and there is no sound. (I play the video-1.mp4.part).

- but when I downloading the single video (not a playlist) and stop the downloaad procces before completed, I play video-single-1.mp4.part, it has a sound.

- I try again and again, the two step above, and get the same result. the single video can be played with sound even it does not downloaded completely (still have .part extension), and the playlist video does not have a sound when not downloaded completely.

is the downloading process of youtube playlist have to be completed ( has no .part) to have a sound in a video ?

thank you.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
