### ISSUE TITLE
make lazy_extractors fails

### ISSUE THREAD

**Issue by lawlmart** [rg3/youtube-dl#14166]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

---

### Description of your *issue*, suggested solution and other information

$ make lazy-extractors && make youtube-dl
/usr/bin/env python devscripts/make_lazy_extractors.py youtube_dl/extractor/lazy_extractors.py
WARNING: Lazy loading extractors is an experimental feature that may not always work
Traceback (most recent call last):
  File "devscripts/make_lazy_extractors.py", line 89, in <module>
    src = build_lazy_ie(ie, name)
  File "devscripts/make_lazy_extractors.py", line 56, in build_lazy_ie
    if ie.suitable.__func__ is not InfoExtractor.suitable.__func__:
AttributeError: 'function' object has no attribute '__func__'
make: *** [youtube_dl/extractor/lazy_extractors.py] Error 1

**Comment by Recchan** [comment]
I'm getting a different error. I've been trying different versions to make, but they all fail with the same error for me.

$ make lazy-extractors
devscripts/make_lazy_extractors.py youtube_dl/extractor/lazy_extractors.py
process_begin: CreateProcess(C:\python34\scripts\youtube-dl\devscripts\make_lazy_extractors.py, devscripts/make_lazy_extractors.py youtube_dl/extractor/lazy_extractors.py, ...) failed.
make (e=193): Error 193F:\Desktop\shell.w32-ix86\make.exe: *** [youtube_dl/extractor/lazy_extractors.py] Error 193
