### ISSUE TITLE
Unable to download videos from Udemy

### ISSUE THREAD

**Issue by ankyparmar86** [rg3/youtube-dl#14165]
I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

---

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
C:\Users\ankitpar\Downloads>youtube-dl.exe -v https://www.udemy.com/cart/checkout/express/course/362328/?couponCode=F6O7SG717DEAL10 -f "(mp4,webm)[height<480]"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.udemy.com/cart/checkout/express/course/362328/?couponCode=F6O7SG717DEAL10', '-f', '(mp4,webm)[height<480]']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.09.02
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] cart: Downloading webpage
ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\extractor\udemy.py", line 377, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\extractor\udemy.py", line 69, in _extract_course_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\extractor\common.py", line 797, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

I am trying to download video tutorials of course AWS Certified Solutions Architect - Associate 2017 from Udemy website and for this course I have already paid the fees but still getting the error. Even I have the latest version of youtube-dl i.e. 2017.09.02 but I don't understand where the problem is.

**Comment by dstftw** [comment]
1. Correct course URL is https://www.udemy.com/aws-certified-solutions-architect-associate/.
2. For any further investigations you must provide account credentials.

**Comment by ankyparmar86** [comment]
I have downloaded from that URL as well which you told me but it referred me to the same url which I mentioned in my ticket.

Username- anky.parmar1786@gmail.com
password - Qwer@123

**Comment by ankyparmar86** [comment]
I have downloaded from that URL as well which you told me but it referred
me to the same url which I mentioned in my ticket.

Username- anky.parmar1786@gmail.com
password - Qwer@123

**Comment by dstftw** [comment]
You did not pass credentials to youtube-dl.

**Comment by ankyparmar86** [comment]
thanks a lot.. downloading started..
