### ISSUE TITLE
youtube-dl www-data wont add metadata

### ISSUE THREAD

**Issue by zakrzus** [rg3/youtube-dl#14167]
Hello,
I'am automating downloads via php script, and everythings is fine, track is being downloaded but without metadata.
I'am running it by 
``shell_exec('python3 /usr/local/bin/youtube-dl --prefer-ffmpeg --playlist-end 1 --max-filesize 70m --add-metadata --restrict-filenames -continue --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" '.$link);

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
