### ISSUE TITLE
Google Drive issue. No longer possible to download formats

### ISSUE THREAD

**Issue by 4getit** [rg3/youtube-dl#14164]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://drive.google.com/file/d/REDACTED/view', u'--verbose', u'--list-formats']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.02
[debug] Python version 2.7.12 - Linux-2.6.32-042stab120.18-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[GoogleDrive] REDACTED: Downloading webpage
[GoogleDrive] REDACTED: Requesting source file
[info] Available formats for REDACTED:
format code  extension  resolution note
source       mkv        unknown 
...
<end of log>
```

and...

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://drive.google.com/file/d/REDACTED/view', u'--verbose', u'-f', u'18,59,22,37']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.02
[debug] Python version 2.7.12 - Linux-2.6.32-042stab120.18-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[GoogleDrive] REDACTED: Downloading webpage
[GoogleDrive] REDACTED: Requesting source file
ERROR: requested format not available
Traceback (most recent call last):
  File "/home/user/hqsgethls/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/user/hqsgethls/youtube-dl/youtube_dl/YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/user/hqsgethls/youtube-dl/youtube_dl/YoutubeDL.py", line 1593, in process_video_result
    expected=True)
ExtractorError: requested format not available

```

---

### Description of your *issue*, suggested solution and other information

Google Drive changed something because it's no longer possible to list available formats or select one or more formats when downloading.

**Comment by dstftw** [comment]
Test links works as usual:
```
PS C:\Dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py https://drive.google.com/file/d/0ByeS4oOUV-49Zzh4R1J6R09zazQ/edit?pli=1 -F
[GoogleDrive] 0ByeS4oOUV-49Zzh4R1J6R09zazQ: Downloading webpage
[GoogleDrive] 0ByeS4oOUV-49Zzh4R1J6R09zazQ: Requesting source file
[info] Available formats for 0ByeS4oOUV-49Zzh4R1J6R09zazQ:
format code  extension  resolution note
43           webm       640x360
34           flv        640x360
18           mp4        640x360
35           flv        854x480
59           mp4        854x480
22           mp4        1280x720
37           mp4        1920x1080
source       mp4        unknown    (best)
```
>18           mp4        640x360
59           mp4        854x480
22           mp4        1280x720
37           mp4        1920x1080

You must provide concrete URLs for investigation.
