### ISSUE TITLE
[tou.tv] Problem in VALID_URL regex for special features episodes

### ISSUE THREAD

**Issue by oxidius3** [rg3/youtube-dl#14179]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

In **youtube_dl/extractor/toutv.py**, line 17 indicates valid urls for tou.tv     
`_VALID_URL = r'https?://ici\.tou\.tv/(?P<id>[a-zA-Z0-9_-]+(?:/S[0-9]+E[0-9]+)?)'`

Some series have special features or extras that do not fit the regex.
Here's an examples : `https://ici.tou.tv/l-age-adulte/S01C501`

I'm not sure if modifying the regex is the only thing to do.

Thank you.

**Comment by dstftw** [comment]
https://ici.tou.tv/l-age-adulte/S01C501 fits the regex just fine.

**Comment by oxidius3** [comment]
Well specials episode to not download, they fallback on the first episode of the season, in this case both
https://ici.tou.tv/l-age-adulte/S01C501 and
https://ici.tou.tv/l-age-adulte/S01C502
Download https://ici.tou.tv/l-age-adulte/S01E01

I was under the impression it was becasue "S01C501" does not match  the final group (?:/S[0-9]+E[0-9]+)?) 

But it might be for another reason
