### ISSUE TITLE
Vox video help

### ISSUE THREAD

**Issue by slackmoehrle** [rg3/youtube-dl#14173]
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)

I am trying to download a talk that Satya Nadella gave so I can watch it a few times to write a paper. I have a very slow Internet connection through Verizon so streaming it each time seldom works.

Here is the original source: `https://www.recode.net/2014/6/17/11628066/post-post-pc-ceo-the-full-code-conference-video-of-microsofts-satya`

Here is the link I found when searching in the Inspector: `blob:https://volume.vox-cdn.com/b0708fc4-b23e-3e44-bff2-8a8924f3ab8e`

__Version:__
```
$ youtube-dl --version
2017.09.11
```

__Verbose Output:__
```
$ youtube-dl --verbose https://volume.vox-cdn.com/b0708fc4-b23e-3e44-bff2-8a8924f3ab8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://volume.vox-cdn.com/b0708fc4-b23e-3e44-bff2-8a8924f3ab8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] b0708fc4-b23e-3e44-bff2-8a8924f3ab8: Requesting header
WARNING: Could not send HEAD request to https://volume.vox-cdn.com/b0708fc4-b23e-3e44-bff2-8a8924f3ab8: HTTP Error 404: Not Found
[generic] b0708fc4-b23e-3e44-bff2-8a8924f3ab8: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Can anyone shed some light on if I am doing anything wrong? I tried looking at different parameters to pass in, but I'm not seeing anything that would be helpful, AFAIK.

__Edit:__ Digging more into this, I tried with this link: 
```
https://brightcove.vox-cdn.com/permutation/0c2129c5-42b8-49e0-aa4c-f560c7bc0ba7/0afbb663-14df-494b-b17f-4f1c394819ed/225bd8bb-a577-11e4-bfdb-005056837bc7/0/0/frames/570/870/content.ts?tspadding=True
``` 
which downloads about 2.6mb and only about 10 seconds of the video. 

__Edit 2:__ Success! So I installed __FFMpeg__ via `brew` and then ran the following:
```
youtube-dl --verbose https://once-aws-us-west-2-lb.unicornmedia.com/now/media/playlist/0c2129c5-42b8-49e0-aa4c-f560c7bc0ba7/2aed5a7e-e057-4a71-94c1-d263e247ae92/076ea1a2-a35b-11e4-bfdb-005056837bc7/0afbb663-14df-494b-b17f-4f1c394819ed/0/0/4115/content.m3u8?visitguid=2ffda4a4-fa81-4d44-948f-114d3218c83f&segmentlength=10&adsegmentlength=10&protocolversion=3&enablesuperchunk=false&tspadding=true
```
and it works!

I found this link by going deeper into the Chrome developer tools and watching very carefully the _Network_ resources that were being used, inspecting response and request headers.

Not sure if I should close this issue or if there is information in it that is helpful for improvements.

**Comment by rredford6** [comment]
> A blob: URL does not refer to data the exists on the server, it refers to data that your browser currently has in memory, for the current page. It will not be available on other pages, it will not be available in other browsers, and it will not be available from other computers.

https://stackoverflow.com/questions/14952052/convert-blob-url-to-normal-url
