### ISSUE TITLE
Better Parsing of URL parameters

### ISSUE THREAD

**Issue by gimmel** [rg3/youtube-dl#14186]
URL parameters are parsed in a wrong way sometimes. I experienced this problem with some URLs, for example 3sat and some youtube playlists.

http://www.3sat.de/mediathek/?mode=play&obj=48376
outputs "Unsupported URL: http://www.3sat.de/mediathek/?mode=play"

http://www.3sat.de/mediathek/?obj=48376
works

It seems like the URL is parsed with a (too) simple Regex. The URL parser should get the parameters by name, not by position or order.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
