### ISSUE TITLE
VIKI cannot download the video, as if the signature has changed

### ISSUE THREAD

**Issue by hucaloof** [rg3/youtube-dl#14181]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--restrict-filenames', u'-o', u'/data/viki/zuijiaqiannanyou/%(title)s.%(ext)s', u'--proxy', u'http://138.68.16.252:3128', u'https://www.viki.com/tv/28818c-my-best-ex-boyfriend#modal-episode']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Git HEAD: fd0b8fc
[debug] Python version 2.7.13 - Linux-2.6.32-431.el6.x86_64-x86_64-with-centos-6.5-Final
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.3
[debug] Proxy map: {u'http': u'http://138.68.16.252:3128', u'https': u'http://138.68.16.252:3128'}
[viki:channel] 28818c: Downloading channel JSON
[viki:channel] 28818c: Downloading episodes JSON page #1
[viki:channel] 28818c: Downloading episodes JSON page #2
[viki:channel] 28818c: Downloading clips JSON page #1
[viki:channel] 28818c: Downloading movies JSON page #1
[download] Downloading playlist: My Best Ex-Boyfriend
[viki:channel] playlist My Best Ex-Boyfriend: Collected 55 video ids (downloading 55 of them)
[download] Downloading video 1 of 55
[viki] 1077337v: Downloading video JSON
[viki] 1077337v: Downloading video streams JSON
ERROR: viki returned error: invalid signature
Traceback (most recent call last):
  File "/root/.pyenv/versions/2.7.13/envs/env27/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/root/.pyenv/versions/2.7.13/envs/env27/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/root/.pyenv/versions/2.7.13/envs/env27/lib/python2.7/site-packages/youtube_dl/extractor/viki.py", line 270, in _real_extract
    'Downloading video streams JSON')
  File "/root/.pyenv/versions/2.7.13/envs/env27/lib/python2.7/site-packages/youtube_dl/extractor/viki.py", line 69, in _call_api
    self._raise_error(resp['error'])
  File "/root/.pyenv/versions/2.7.13/envs/env27/lib/python2.7/site-packages/youtube_dl/extractor/viki.py", line 76, in _raise_error
    expected=True)
ExtractorError: viki returned error: invalid signature
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Playlist: https://www.viki.com/tv/28818c-my-best-ex-boyfriend#modal-episode

---

### Description of your *issue*, suggested solution and other information

I think VIKI changed the signature algorithm, but what exactly is I do not kno

**Comment by icebadger** [comment]
I can replicate your issue with the link provided.  I get the same debug output.

For other videos, I get a geolocation error, even though I can play fine from browser.

Playlist:  https://www.viki.com/tv/28448c-she-was-pretty#modal-episode
```[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.viki.com/tv/28448c-she-was-pretty#modal-episode']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Python version 2.7.13 - Linux-4.10.0-33-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: avconv 3.2.4-1build2, avprobe 3.2.4-1build2, ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2, rtmpdump 2.4
[debug] Proxy map: {}
[viki:channel] 28448c: Downloading channel JSON
ERROR: Sorry, this content is not available in your region.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/viki.py", line 364, in _real_extract
    self._check_errors(channel)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/viki.py", line 83, in _check_errors
    self.raise_geo_restricted(msg=message)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 732, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
GeoRestrictedError: Sorry, this content is not available in your region.
```

I am wondering if these have the same root cause.

**Comment by hucaloof** [comment]
VIKI site has regional restrictions, some areas of the IP address can access the page, but can not play video

**Comment by icebadger** [comment]
I understand this.  In this instance, I am able to play the video (in browser) from my local IP and VPN connections.  However starting today, I get either the geolocation or signature error depending on the playlist attempted.

If you try the playlist I posted above, error code does it fail on?

**Comment by hucaloof** [comment]
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--restrict-filenames', u'--proxy', u'http://138.68.16.252:3128', u'https://www.viki.com/tv/28448c-she-was-pretty#modal-episode']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Git HEAD: fd0b8fc
[debug] Python version 2.7.13 - Linux-2.6.32-431.el6.x86_64-x86_64-with-centos-6.5-Final
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.3
[debug] Proxy map: {u'http': u'http://138.68.16.252:3128', u'https': u'http://138.68.16.252:3128'}
[viki:channel] 28448c: Downloading channel JSON
ERROR: Sorry, this content is not available in your region.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "/root/.pyenv/versions/2.7.13/envs/env27/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/root/.pyenv/versions/2.7.13/envs/env27/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/root/.pyenv/versions/2.7.13/envs/env27/lib/python2.7/site-packages/youtube_dl/extractor/viki.py", line 364, in _real_extract
    self._check_errors(channel)
  File "/root/.pyenv/versions/2.7.13/envs/env27/lib/python2.7/site-packages/youtube_dl/extractor/viki.py", line 83, in _check_errors
    self.raise_geo_restricted(msg=message)
  File "/root/.pyenv/versions/2.7.13/envs/env27/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 732, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
GeoRestrictedError: Sorry, this content is not available in your region.
```

The playlist above requires the use of VPN, and I don't have any other VPN addresses to try

**Comment by icebadger** [comment]
My Hong Kong and South Korea VPN says its restricted, but my US and UK VPNs allow me to play, and it plays in Germany.  I have a feeling it is also a signature issue, but it is throwing the geolocation error for videos that are restricted in some regions.

**Comment by hucaloof** [comment]
Is there any way to solve this problem? I can't download all the videos in VIKI now.

**Comment by icebadger** [comment]
I'm not sure right now.

**Comment by sebaro** [comment]
app=100005a
secret=MM_d*yP@`&1@]@!AVrXf_o-HVEnoTnm$O-ti4[G~$JDI/Dc-&piU&z&5.;:}95\=Iad

**Comment by icebadger** [comment]
Just tried this in the viki.py file, and it generates an HTTP Error 400: Bad Request

```
_APP = '100005a'
_APP_VERSION = '2.2.5.1428709186'
_APP_SECRET = 'MM_d*yP@`&1@]@!AVrXf_o-HVEnoTnm$O-ti4[G~$JDI/Dc-&piU&z&5.;:}95\=Iad'
```
Is there an update to the _APP_VERSION as well?

**Comment by sebaro** [comment]
_APP_VERSION is not used in the code so it's not the problem.
Maybe you have to escape the backslash.

**Comment by hucaloof** [comment]
The Chrome developers see capture version should be updated to 3.2, but I have not tested

**Comment by icebadger** [comment]
It looks like the viki _APP_SECRET may have changed again.

sebaro, do you remember how to find/locate the _APP_SECRET key?

Thanks for any help you can provide
