### ISSUE TITLE
YouKu.com can not be down rightly

### ISSUE THREAD

**Issue by Lavinci** [rg3/youtube-dl#14190]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.11**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
TM2NDczNg==.html?tpa=dW5pb25faWQ9MTAzNzUzXzEwMDAwMV8wMV8wMQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'http://v.youku.com/v_show/id_XMjk0NTM2NDczNg==.html?tpa=dW5pb25faWQ9MT
AzNzUzXzEwMDAwMV8wMV8wMQ']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.09.11
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-86935-g44e9783, ffprobe N-86935-g44e9783
[debug] Proxy map: {}
[youku] XMjk0NTM2NDczNg: Retrieving cna info
[youku] XMjk0NTM2NDczNg: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with
the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\YoutubeDL.py", l
ine 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\extractor\common
.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\extractor\youku.
py", line 189, in _real_extract
youtube_dl.utils.ExtractorError: Youku server reported error -6004: 客户端无权播放,201; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sur
e to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```
it works very well ,but something was wrong recently,Is there any ways to resolve the problem?
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by yan12125** [comment]
Works fine here.
```
$ youtube-dl -vF "http://v.youku.com/v_show/id_XMjk0NTM2NDczNg==.html?tpa=dW5pb25faWQ9MTAzNzUzXzEwMDAwMV8wMV8wMQ"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vF', 'http://v.youku.com/v_show/id_XMjk0NTM2NDczNg==.html?tpa=dW5pb25faWQ9MTAzNzUzXzEwMDAwMV8wMV8wMQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Git HEAD: 2f483758b
[debug] Python version 3.6.2 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youku] XMjk0NTM2NDczNg: Retrieving cna info
[youku] XMjk0NTM2NDczNg: Downloading JSON metadata
[info] Available formats for XMjk0NTM2NDczNg:
format code  extension  resolution note
0            mp4        640x360    107.12MiB
h4-0         mp4        640x360    108.48MiB
h3           mp4        960x540    192.53MiB
3            mp4        1280x720   312.11MiB
h4-1         mp4        1280x720   313.18MiB
5            mp4        1920x1080  586.28MiB
h4-2         mp4        1920x1080  587.45MiB (best)
```
Could you watch this video in browsers?

**Comment by Lavinci** [comment]
emmm...it works well now ,what happen...
i am sorry to disturb you.thank you

**Comment by johnxian1** [comment]
here doesn't work also.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vF', 'http://v.youku.com/v_show/id_XMzAyMTMzNDgwNA==.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.09.15
[debug] Python version 3.4.4 - Win7
[debug] exe versions: ffmpeg N-83454-g3aae1ef, ffprobe N-83454-g3aae1ef
[debug] Proxy map: {}
[youku] XMzAyMTMzNDgwNA: Retrieving cna info
[youku] XMzAyMTMzNDgwNA: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\extractor\youku.py", line 189, in _real_extract
youtube_dl.utils.ExtractorError: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
I guess it's a temporary issue. Just tried and this video works fine here.
```
$ youtube-dl -vF "http://v.youku.com/v_show/id_XMzAyMTMzNDgwNA==.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vF', 'http://v.youku.com/v_show/id_XMzAyMTMzNDgwNA==.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.15
[debug] Git HEAD: 4d8c4b46d
[debug] Python version 3.6.2 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youku] XMzAyMTMzNDgwNA: Retrieving cna info
[youku] XMzAyMTMzNDgwNA: Downloading JSON metadata
[info] Available formats for XMzAyMTMzNDgwNA:
format code  extension  resolution note
0            mp4        640x360    238.28MiB
h4-0         mp4        640x360    240.15MiB
h3           mp4        960x540    456.11MiB
3            mp4        1280x720   763.66MiB
h4-1         mp4        1280x720   765.15MiB
5            mp4        1920x1080  1.57GiB
h4-2         mp4        1920x1080  1.57GiB (best)
```
