### ISSUE TITLE
Error: RegexNotFoundError: Unable to extract content ID

### ISSUE THREAD

**Issue by section83** [rg3/youtube-dl#14200]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.11**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)

---

### Verbose output follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--restrict-filenames', u'--simulate', u'--get-filename', u'--verbose', u'-o', u'%(series)s-%(title)s.%(ext)s', u'https://au.tv.yahoo.com/plus7/800-words/-/watch/29520134/800-words-season-1-episode-1/']
[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
[debug] youtube-dl version 2017.09.11
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.3-tessus, ffprobe 3.3.3-tessus
[debug] Proxy map: {}
ERROR: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yahoo.py", line 302, in _real_extract
    CONTENT_ID_REGEXES, webpage, 'content ID')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 797, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

Testing youtube-dl to return series, title and filename from the Plus7 web site in Australia.  ytdl returned the error msg advising that I should do a bug report.  Can't find any other similar bugs and am definitely using youtube-dl 2017.09.11.  I am located in Australia and so am not affected by geo-restrictions.

**Comment by Artic0din** [comment]
I am receiving the same issue with version 2017.09.15

Plus7 recently changed the layout of their site so this maybe a contributing factor.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://au.tv.yahoo.com/plus7/highway-patrol/-/watch/37132737/highway-patrol-mon-18-sep-season-9-episode-5/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.15
[debug] Python version 2.7.11 - Darwin-17.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3
[debug] Proxy map: {}
[Yahoo] highway-patrol-mon-18-sep-season-9-episode: Downloading webpage
ERROR: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yahoo.py", line 302, in _real_extract
    CONTENT_ID_REGEXES, webpage, 'content ID')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 797, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by section83** [comment]
Yes, there must have been a recent change @ Plus7.

I do not get the RegexNotFoundError if I force youtube-dl to use the generic extractor.  However, every video I've tried gets:

 "ERROR: Unsupported URL: https://au.tv.yahoo.com/plus7/800-words/-/watch/29520134/800-words-season-1-episode-1/"

**Comment by section83** [comment]
This should be fixable.  The commercial tool _Allavsoft_ which uses youtube-dl is able to download videos from Plus7.  I have attached a log file from _Allavsoft_:

[download.log](https://github.com/rg3/youtube-dl/files/1332030/download.log)

Cheers.
