### ISSUE TITLE
[fix] Crunchyroll login

### ISSUE THREAD

**Issue by jumpjet91** [rg3/youtube-dl#14209]
I see on web guide for login on Crunchyroll using API

Reference https://github.com/CloudMax94/crunchyroll-api/wiki

Support JSON  and XML response

{request} = API request
{version} = your version (better use value 0)
{sess_id} = Session ID as a cookie named "sess_id"

Response Type | URL
JSON | api.crunchyroll.com/{request}.{version}.json?&session_id={sess_id}
XML | api.crunchyroll.com/{request}.{version}.xml?&session_id={sess_id}

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
