### ISSUE TITLE
retrieving url video from fragments - akamaihd

### ISSUE THREAD

**Issue by SickBoy84** [rg3/youtube-dl#14203]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Dear All,

I'm struggling trying to download a video splitted in fragments, I don't know what url to pass to youtube-dl.

It first receive a file called: manifest.mpd
Then 4 init files called: init-f1-v1-x3.mp4, init-f2-v1-x3.mp4, init-f3-a1-x3.mp4, init-f4-a1-x3.mp4
And then starts to receive fragment files of this form: fragment-#-f1-v1-x3.mp4, fragment-#-f2-v1-x3.mp4, fragment-#-f3-a1-x3.mp4, fragment-#-f4-a1-x3.mp4
With # starting from 1 and goes forever.

It's quite obvious that he has 2 audio and 2 video stream and it gets fragments one-by-one.

All url are of this form:

https://kalhlspd-a.akamaihd.net/s/dash/p/2066791/sp/206679100/serveFlavor/entryId/1_mo87c6kz/v/1/flavorId/1_,iy1uv41d,vccjcr8y,a2ruwehc,jl5c3eh4,c6rdepxh,6vfazux6,/forceproxy/true/name/a.mp4.urlset/fragment-1-f1-v1-x3.m4s?__hdnea__=st=1505389298~exp=1505475698~acl=/s/dash/p/2066791/sp/206679100/serveFlavor/entryId/1_mo87c6kz/v/1/flavorId/1_*~hmac=679a058d3eaa9e0be5d3db18865f9a8de1bd3ebe69496e211ec12928f7d94752

The only part that change is the "fragment-1-f1-v1-x3.m4s" with 2, 3, 4, etc...

How can I do to download this video with youtube-dl?

Thanks a lot to everyone!

**Comment by dstftw** [comment]
Pass manifest.mpd URL. Downloading will proceed if video is not DRM protected.

**Comment by SickBoy84** [comment]
I get this passing manifest.mpd:

```
youtube-dl https://kalhlspd-a.akamaihd.net/s/dash/p/2066791/sp/206679100/serveFlavor/entryId/1_mo87c6kz/v/1/flavorId/1_,iy1uv41d,vccjcr8y,a2ruwehc,jl5c3eh4,c6rdepxh,6vfazux6,/forceproxy/true/name/a.mp4.urlset/manifest.mpd?__hdnea__=st=1505402937~exp=1505403237~acl=/s/dash/p/2066791/sp/206679100/serveFlavor/entryId/1_mo87c6kz/v/1/flavorId/1_*~hmac=8e0dd548cb901854c8d76b075058927afb295fac45fbf514b9689b0f344a937d
[generic] 1_*~hmac=8e0dd548cb901854c8d76b075058927afb295fac45fbf514b9689b0f344a937d: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1_*~hmac=8e0dd548cb901854c8d76b075058927afb295fac45fbf514b9689b0f344a937d: Downloading webpage
[generic] 1_*~hmac=8e0dd548cb901854c8d76b075058927afb295fac45fbf514b9689b0f344a937d: Extracting information
ERROR: requested format not available
```

Does this mean the video is DRM protected?
If yes is there anything I can do to download it?

Thanks a lot

**Comment by SickBoy84** [comment]
@dstftw can you please reply? :)
