### ISSUE TITLE
Cannot download Dailymotion playlist

### ISSUE THREAD

**Issue by fcoiffie** [rg3/youtube-dl#14219]
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl -v http://dailymotion.com/playlist/x49nxu
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://dailymotion.com/playlist/x49nxu']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Python version 3.4.6 - Linux-4.12.2-gentoo-x86_64-Intel-R-_Core-TM-_i5-3570K_CPU_@_3.40GHz-with-gentoo-2.4.1
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] x49nxu: Requesting header
[redirect] Following redirect to http://www.dailymotion.com/playlist/x49nxu
[generic] x49nxu: Requesting header
WARNING: Falling back on generic information extractor.
[generic] x49nxu: Downloading webpage
[generic] x49nxu: Extracting information
ERROR: Unsupported URL: http://www.dailymotion.com/playlist/x49nxu
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/generic.py", line 2964, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.dailymotion.com/playlist/x49nxu
```

---

youtube-dl cannot dowload a Dailymotion playlist from `http://dailymotion.com/playlist/x49nxu`.

**Comment by plunkets** [comment]
Hi, i have the same problem. Is there a reason why this issue is closed?

> youtube-dl --version
2017.09.15
> python --version
Python 2.7.13

(Unhappy coincidence, i am trying to download exactly the same playlist J'adore Chroma!)

**Comment by fcoiffie** [comment]
I haven't tested the 2017.09.15 version but I confirm that 6be44a50edfe2e75e31553e7a128ce1849301958 fixes the problem.

**Comment by rachelgreenhappy** [comment]
You may try Allavsoft which enables to batch download Dailymotion playlist to mp4, mp3, avi, mov etc
Here is the step by step guide:  https://www.allavsoft.com/how-to/download-dailymotion-playlist.html
