### ISSUE TITLE
Download error on PBS.org

### ISSUE THREAD

**Issue by brian-from-fl** [rg3/youtube-dl#14228]
brian$ youtube-dl --verbose http://www.pbs.org/wgbh/masterpiece/episodes/the-durrells-in-corfu-s2-e3/
   [debug] System config: []
   [debug] User config: [u'-o', u'~/Local/YouTubeDownload/%(title)s.%(ext)s']
   [debug] Custom config: []
   [debug] Command-line args: [u'--verbose', u'http://www.pbs.org/wgbh/masterpiece/episodes/the-durrells-in-corfu-s2-e3/']
   [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
   [debug] youtube-dl version 2017.09.15
   [debug] Python version 2.7.13 - Darwin-16.7.0-x86_64-i386-64bit
   [debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.3.4, ffprobe 3.3.4
   [debug] Proxy map: {}
   [debug] Using fake IP 3.102.26.172 (US) as X-Forwarded-For.
   [pbs] Downloading JSON metadata
   [pbs] the-durrells-in-corfu-s2-e3: Downloading webpage
   [pbs] Downloading widget/partnerplayer page
   WARNING: Unable to download webpage: HTTP Error 404: Not Found
   [pbs] Downloading portalplayer page
   WARNING: Unable to download webpage: HTTP Error 404: Not Found
      ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
   Traceback (most recent call last):
   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
     ie_result = ie.extract(url)
   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
     ie_result = self._real_extract(url)
   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 585, in _real_extract
     self._sort_formats(formats)
   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1072, in _sort_formats
     raise ExtractorError('No video formats found')
   ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kayb94** [comment]
I can't see any video on that webpage.
