### ISSUE TITLE
Youtube Metadata Only

### ISSUE THREAD

**Issue by abatman** [rg3/youtube-dl#14224]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.11**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I have been attempting to download the metadata for our You-Tube channel for some time now. What I am attempting to download is a list to make an excel document of that contains each videos Title, URL, and what playlist it belongs too. Is this possible with the coding you have done already or would this need to be created? If I could only download the file name and URL that would be great as well for all the videos in my youtube channel. Additionally, I do not need the videos to be downloaded either.

**Comment by dstftw** [comment]
`--dump-json`/`--dump-single-json`.

**Comment by abatman** [comment]
That did not work for me. I am trying to download all the channels video metadata with only the title and URL and if possible what playlist it belongs to. My goal is to make a spreadsheet with column names of Title, URL, and Playlist. Then possibly upload date and video description.

**Comment by abatman** [comment]
Kind of what this website does with no images http://bythos.com/cgi/youscript/ytform.html

**Comment by dstftw** [comment]
Aforementioned commands provide you complete metadata in JSON per video (the former) or per playlist (the latter). What will you do with it next is up to you.
