### ISSUE TITLE
[mixcloud] can't download from mixcloud

### ISSUE THREAD

**Issue by b2kb2kb2k** [rg3/youtube-dl#14226]
getting this error:

`[mixcloud] lowlight-requiem-for-cassini: Downloading webpage
ERROR: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`
can you fix it?
thanks.

**Comment by kayb94** [comment]
you did not search for similar bug reports!
