### ISSUE TITLE
[site-support] hotstar is not working !!  

### ISSUE THREAD

**Issue by narutowindy** [rg3/youtube-dl#14238]
ytdl_hook: [debug] Command-line args: ['--no-warnings', '-J', '--flat-playlist', '--sub-format', 'ass/srt/best', '--no-playlist', '--format', 'bestvideo[height<=?400][fps<=?30][vcodec!=?vp9][protocol!=http_dash_segments]+bestaudio/best', '--all-subs', '--', 'http://hshls2-i.akamaihd.net/hls/live/567678/indvaus2017ed/ENGDELINDVSAUS1ODI17092017/master.m3u8?hdnea=st=1505653474~exp=1505654074~acl=/*~hmac=7bdaee0cc72859fa9d10489aa109b868d094bfce8d77563bdd04b23359beb87d']
 ytdl_hook: [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
 ytdl_hook: [debug] youtube-dl version 2017.09.15
 ytdl_hook: [debug] Python version 3.6.2 - Linux-4.12.13-1-ARCH-x86_64-with-arch
 ytdl_hook: [debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4
 ytdl_hook: [debug] Proxy map: {}
 ytdl_hook: ERROR: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 ytdl_hook:   File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 503, in _request_webpage
 ytdl_hook:     return self._downloader.urlopen(url_or_request)
 ytdl_hook:   File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2177, in urlopen
 ytdl_hook:     return self._opener.open(req, timeout=self._socket_timeout)
 ytdl_hook:   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
 ytdl_hook:     response = meth(req, response)
 ytdl_hook:   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
 ytdl_hook:     'http', request, response, code, msg, hdrs)
 ytdl_hook:   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
 ytdl_hook:     return self._call_chain(*args)
 ytdl_hook:   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
 ytdl_hook:     result = func(*args)
 ytdl_hook:   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
 ytdl_hook:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
 ytdl_hook: 
 ytdl_hook: youtube-dl failed, trying to play URL directly ... 
   cplayer: Run command: hook-ack, flags=0, args=[on_load]
    ffmpeg: Opening http://hshls2-i.akamaihd.net/hls/live/567678/indvaus2017ed/ENGDELINDVSAUS1ODI17092017/master.m3u8?hdnea=st=1505653474~exp=1505654074~acl=/*~hmac=7bdaee0cc72859fa9d10489aa109b868d094bfce8d77563bdd04b23359beb87d
    ffmpeg: http: HTTP error 403 Forbidden
    stream: Failed to open http://hshls2-i.akamaihd.net/hls/live/567678/indvaus2017ed/ENGDELINDVSAUS1ODI17092017/master.m3u8?hdnea=st=1505653474~exp=1505654074~acl=/*~hmac=7bdaee0cc72859fa9d10489aa109b868d094bfce8d77563bdd04b23359beb87d.
   cplayer: Opening failed or was aborted: http://hshls2-i.akamaihd.net/hls/live/567678/indvaus2017ed/ENGDELINDVSAUS1ODI17092017/master.m3u8?hdnea=st=1505653474~exp=1505654074~acl=/*~hmac=7bdaee0cc72859fa9d10489aa109b868d094bfce8d77563bdd04b23359beb87d
   cplayer: finished playback, loading failed (reason 4)
   cplayer:

**Comment by dstftw** [comment]
You must use source hotstar URL.
