### ISSUE TITLE
[Youtube] Automatic captions not found for age-restricted videos

### ISSUE THREAD

**Issue by hurda** [rg3/youtube-dl#14230]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
>youtube-dl --list-subs -v https://www.youtube.com/watch?v=GKFHZuCvvS4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--list-subs', '-v', 'https://www.youtube.com/watch?
v=GKFHZuCvvS4']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.09.15
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.1.4, ffprobe N-73361-g03b2b40, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] GKFHZuCvvS4: Downloading webpage
[youtube] GKFHZuCvvS4: Downloading embed webpage
[youtube] GKFHZuCvvS4: Refetching age-gated info webpage
[youtube] GKFHZuCvvS4: Extracting video information
[youtube] GKFHZuCvvS4: Looking for automatic captions
WARNING: Couldn't find automatic captions for GKFHZuCvvS4
GKFHZuCvvS4 has no automatic captions
Available subtitles for GKFHZuCvvS4:
Language formats
fr       vtt, ttml
es       vtt, ttml

>youtube-dl --list-subs -v https://www.youtube.com/watch?v=AUvICKyXnqU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--list-subs', '-v', 'https://www.youtube.com/watch?
v=AUvICKyXnqU']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.09.15
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.1.4, ffprobe N-73361-g03b2b40, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] AUvICKyXnqU: Downloading webpage
[youtube] AUvICKyXnqU: Downloading video info webpage
[youtube] AUvICKyXnqU: Extracting video information
[youtube] AUvICKyXnqU: Looking for automatic captions
[youtube] AUvICKyXnqU: Downloading MPD manifest
Available automatic captions for AUvICKyXnqU:
Language formats
my       vtt, ttml
is       vtt, ttml
iw       vtt, ttml
tr       vtt, ttml
so       vtt, ttml
uk       vtt, ttml
gl       vtt, ttml
vi       vtt, ttml
yo       vtt, ttml
am       vtt, ttml
mi       vtt, ttml
ca       vtt, ttml
tg       vtt, ttml
uz       vtt, ttml
da       vtt, ttml
el       vtt, ttml
en       vtt, ttml
es       vtt, ttml
sw       vtt, ttml
ig       vtt, ttml
ta       vtt, ttml
cs       vtt, ttml
kk       vtt, ttml
zh-Hant  vtt, ttml
ne       vtt, ttml
ht       vtt, ttml
sv       vtt, ttml
sm       vtt, ttml
mk       vtt, ttml
gd       vtt, ttml
ps       vtt, ttml
mr       vtt, ttml
ja       vtt, ttml
hy       vtt, ttml
zu       vtt, ttml
lb       vtt, ttml
cy       vtt, ttml
et       vtt, ttml
lo       vtt, ttml
ro       vtt, ttml
yi       vtt, ttml
haw      vtt, ttml
ku       vtt, ttml
xh       vtt, ttml
pa       vtt, ttml
fr       vtt, ttml
be       vtt, ttml
fi       vtt, ttml
id       vtt, ttml
lv       vtt, ttml
de       vtt, ttml
sn       vtt, ttml
fa       vtt, ttml
sk       vtt, ttml
no       vtt, ttml
ky       vtt, ttml
mn       vtt, ttml
pt       vtt, ttml
az       vtt, ttml
co       vtt, ttml
mg       vtt, ttml
km       vtt, ttml
sl       vtt, ttml
ceb      vtt, ttml
ka       vtt, ttml
la       vtt, ttml
fil      vtt, ttml
bn       vtt, ttml
hmn      vtt, ttml
sr       vtt, ttml
eu       vtt, ttml
eo       vtt, ttml
af       vtt, ttml
te       vtt, ttml
ny       vtt, ttml
hr       vtt, ttml
nl       vtt, ttml
hi       vtt, ttml
bg       vtt, ttml
lt       vtt, ttml
mt       vtt, ttml
kn       vtt, ttml
ar       vtt, ttml
ga       vtt, ttml
hu       vtt, ttml
sd       vtt, ttml
it       vtt, ttml
jv       vtt, ttml
sq       vtt, ttml
fy       vtt, ttml
ko       vtt, ttml
si       vtt, ttml
th       vtt, ttml
ha       vtt, ttml
ru       vtt, ttml
ms       vtt, ttml
su       vtt, ttml
ur       vtt, ttml
ml       vtt, ttml
zh-Hans  vtt, ttml
bs       vtt, ttml
st       vtt, ttml
gu       vtt, ttml
pl       vtt, ttml
Available subtitles for AUvICKyXnqU:
Language formats
zh-CN    vtt, ttml
en       vtt, ttml
de       vtt, ttml
es-419   vtt, ttml
```

---

### Description of your *issue*, suggested solution and other information

youtube-dl doesn't find automatic captions when it has to work-around an age-restrictions.
On a video without age-restriction, it's finding automatic captions.

Normal subtitles are not affected.

**Comment by dstftw** [comment]
It's not possible to get automatic captions while working around. You have to authenticate.
