### ISSUE TITLE
BUG: constant error on certain videos

### ISSUE THREAD

**Issue by dmitry-sensei** [rg3/youtube-dl#14235]
constant error on certain videos - so I can't download them for me.

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
------------------------------------------
youtube-dl "https://www.youtube.com/watch?v=f-pFycJvTOE&list=PLaFqU3KCWw6IgowRl9eRIFMG1NjK82CIJ" --playlist-start 2 --playlist-end 4 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=f-pFycJvTOE&list=PLaFqU3KCWw6IgowRl9eRIFMG1NjK82CIJ', u'--playlist-start', u'2', u'--playlist-end', u'4', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.15
[debug] Python version 2.7.5 - Linux-3.10.0-693.2.2.el7.x86_64-x86_64-with-centos-7.4.1708-Core
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLaFqU3KCWw6IgowRl9eRIFMG1NjK82CIJ - add --no-playlist to just download video f-pFycJvTOE
[youtube:playlist] PLaFqU3KCWw6IgowRl9eRIFMG1NjK82CIJ: Downloading webpage
[download] Downloading playlist: DEV1 в Барнауле
[youtube:playlist] playlist DEV1 в Барнауле: Downloading 3 videos
[download] Downloading video 1 of 3
[youtube] T4WOS3HTOgk: Downloading webpage
[youtube] T4WOS3HTOgk: Downloading video info webpage
[youtube] T4WOS3HTOgk: Extracting video information
[youtube] T4WOS3HTOgk: Downloading MPD manifest
[youtube] T4WOS3HTOgk: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r3---sn-8ph2xajvh-8vbe.googlevideo.com/videoplayback/id/4f858e4b71d33a09/itag/136/source/yt_otf/requiressl/yes/mn/sn-8ph2xajvh-8vbe/mv/m/pl/19/ms/au/ei/41-9WcyFBcK8YvHxgeAD/mm/31/initcwndbps/325000/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1503683318375642/mt/1505582936/signature/482B00FAD155E1AEC831664CE9E230AF72EA2753.337810E3595B89035241263A8BD9C6D6F3CB6F8F/key/dg_yt0/ip/83.69.139.90/ipbits/0/expire/1505604675/sparams/ip,ipbits,expire,id,itag,source,requiressl,mn,mv,pl,ms,ei,mm,initcwndbps,ratebypass,mime,otfp,otf,lmt/'
[dashsegments] Total fragments: 468
[download] Destination: Курс - DEV1. Тема 1. Базовый инструментарий - «Установка и управление, psql»-T4WOS3HTOgk.f136.mp4
ERROR: unable to download video data: <urlopen error [Errno 104] Connection reset by peer>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1868, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1813, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download                                                                     
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 45, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/fragment.py", line 97, in _download_fragment
    'http_headers': headers or info_dict.get('http_headers'),
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 286, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 74, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2177, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1086, in https_open
    req, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 104] Connection reset by peer>

**Comment by dstftw** [comment]
Most likely a network issue on your side. You may try downloading different format with `-f`.
