### ISSUE TITLE
Download size 0 for this url and no error shown

### ISSUE THREAD

**Issue by randinfo** [rg3/youtube-dl#14234]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

Command used : 
```
 youtube-dl -o '/home/pt3/web/aze.com/public_html/downloads/aze.%(ext)s' -x "https://www.youtube.com/watch?v=Lo9J4lvRNR4" --no-part --prefer-ffmpeg --audio-quality 192K --audio-format mp3 --restrict-filenames --force-ipv4 --write-info-json
```
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
root@ns3368714:/home/pt3/web/aze.com/public_html/aze# youtube-dl -o '/home/pt3/web/aze.com/public_html/downloads/aze.%(ext)s' -x "https://www.youtube.com/watch?v=Lo9J4lvRNR4" --no-part --prefer-ffmpeg --audio-quality 192K --audio-format mp3 --restrict-filenames --force-ipv4 --write-info-json -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-o', u'/home/pt3/web/aze.com/public_html/downloads/aze.%(ext)s', u'-x', u'https://www.youtube.com/watch?v=Lo9J4lvRNR4', u'--no-part', u'--prefer-ffmpeg', u'--audio-quality', u'192K', u'--audio-format', u'mp3', u'--restrict-filenames', u'--force-ipv4', u'--write-info-json', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.15
[debug] Python version 2.7.12 - Linux-4.4.0-78-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] Lo9J4lvRNR4: Downloading webpage
[youtube] Lo9J4lvRNR4: Downloading video info webpage
[youtube] Lo9J4lvRNR4: Extracting video information
[youtube] {22} signature length 43.44, html5 player vflUnLBiU
[youtube] {43} signature length 43.44, html5 player vflUnLBiU
[youtube] {18} signature length 43.44, html5 player vflUnLBiU
[youtube] {36} signature length 43.44, html5 player vflUnLBiU
[youtube] {17} signature length 43.44, html5 player vflUnLBiU
[youtube] {137} signature length 43.44, html5 player vflUnLBiU
[youtube] {248} signature length 43.44, html5 player vflUnLBiU
[youtube] {136} signature length 43.44, html5 player vflUnLBiU
[youtube] {247} signature length 43.44, html5 player vflUnLBiU
[youtube] {135} signature length 43.44, html5 player vflUnLBiU
[youtube] {244} signature length 43.44, html5 player vflUnLBiU
[youtube] {134} signature length 43.44, html5 player vflUnLBiU
[youtube] {243} signature length 43.44, html5 player vflUnLBiU
[youtube] {133} signature length 43.44, html5 player vflUnLBiU
[youtube] {242} signature length 43.44, html5 player vflUnLBiU
[youtube] {160} signature length 43.44, html5 player vflUnLBiU
[youtube] {278} signature length 43.44, html5 player vflUnLBiU
[youtube] {140} signature length 43.44, html5 player vflUnLBiU
[youtube] {171} signature length 43.44, html5 player vflUnLBiU
[youtube] {249} signature length 43.44, html5 player vflUnLBiU
[youtube] {250} signature length 43.44, html5 player vflUnLBiU
[youtube] {251} signature length 43.44, html5 player vflUnLBiU
[youtube] Lo9J4lvRNR4: Downloading MPD manifest
[info] Writing video description metadata as JSON to: /home/pt3/web/aze.com/public_html/downloads/aze.info.json
[debug] Invoking downloader on u'https://r2---sn-25glen7r.googlevideo.com/videoplayback?gcr=es&expire=1505596276&ipbits=0&dur=173.181&gir=yes&mime=audio%2Fwebm&key=yt6&requiressl=yes&initcwndbps=1942500&mt=1505574577&mv=m&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ms=au&ip=37.187.89.81&lmt=1492008585140187&clen=3007647&mm=31&mn=sn-25glen7r&id=o-AH652QMklI4BLBu9AoMJD3laJLCuW4hEWMCRWFVO2zh8&keepalive=yes&source=youtube&ei=Ez-9WbXVOYOHW5HjnNAH&itag=251&pl=20&signature=79CECA7B6B8C79E4FB8CFEA2DAB0A853826AE87B.3FF287C57D753C2094652CE720036897561E4191&ratebypass=yes'
[download] Destination: /home/pt3/web/aze.com/public_html/downloads/aze.webm
[download] 100% of 2.87MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams 'file:/home/pt3/web/aze.com/public_html/downloads/aze.webm'
[ffmpeg] Destination: /home/pt3/web/aze.com/public_html/downloads/aze.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:/home/pt3/web/aze.com/public_html/downloads/aze.webm' -vn -acodec libmp3lame '-b:a' 192k 'file:/home/pt3/web/aze.com/public_html/downloads/aze.mp3'
Deleting original file /home/pt3/web/aze.com/public_html/downloads/aze.webm (pass -k to keep)

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
As clearly seen from the log download and conversion finished successfully meaning it can't be 0 sized. Prove it's 0 size right after conversion finishes.

**Comment by randinfo** [comment]
It's weird maybe a file writing bug thanks for your reply
