### ISSUE TITLE
SoundCloud playlists with liked song, incorrect downloads

### ISSUE THREAD

**Issue by 567legodude** [rg3/youtube-dl#14241]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

On SoundCloud, if I like a single song but it is part of a playlist, and then try to download my liked songs, it downloads all songs from the playlist even if they are not liked. When viewing my liked songs on the website, I can only see the one song that I liked.  
It 's possible that the JSON response from SoundCloud may not show correct information for playlists. I hope the solution to this is just changing the way those kinds of results are interpreted. But it would be nice if when I liked a song from a playlist (and not the playlist itself) that I don't get all the other songs that I didn't like.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by 567legodude** [comment]
Guidelines read completely and all relevant information to reproduce and/or solve has been provided. Redundant/useless information has been omitted.

**Comment by dstftw** [comment]
>### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
