### ISSUE TITLE
Current Openload.js not generating proper link

### ISSUE THREAD

**Issue by ruvort** [rg3/youtube-dl#14257]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
sh-3.2# youtube-dl -v http://openload.co/embed/miEoI5oT8JE

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://openload.co/embed/miEoI5oT8JE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.15
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Openload] miEoI5oT8JE: Downloading webpage
[debug] Default format spec: best
[debug] Invoking downloader on u'https://openload.co/stream/\x07n\xac(\xff\x90\xdcx\xba@}\xe4\xacZ\xac(\xda\x90\xdcx\x84\x80\x90\xee\xaf\xf4\x04*\xb2\x90\xdcx\xaa@}\xe4\x98n\xac(\xe9\x90\xdcxD{}\xe4\x08}\xa1(\x80\x90\xdcx\x84@}\xe4\xa4Z\xac(\x91\x90\xdcx\x8f@}\xe4\xd3Z\xac(\xa6\x90\xdcx\x9c@}\xe4\x8dZ\xac(\x80\x90\xdcx\xba@}\xe4\xd2Z\xac(\x91\x90\xdcx\xa9@}\xe4\xb7Z\xac(\xa5\x90\xdcx\xcc@}\xe4\xa2Z\xac(\xaf\x90\xdcx\x80@}\xe4\xbfZ\xac(\xb2\x90\xdcx\xd7@}\xe4\x85Z\xac(\x94\x90\xdcx\xaf@}\xe4\xa6Z\xac(\x9c\x90\xdcx\xd5@}\xe4\x98Z\xac(\xa1\x90\xdcx\x8d@}\xe4\xa3Z\xac(\xd6\x90\xdcx\xbe@}\xe4\x91Z\xac(\xa0\x90\xdcx\xa1@}\xe4\xc0Z\xac(\x98\x90\xdcx\x80@}\xe4\xb7Z\xac(\xba\x90\xdcx\xae@}\xe4\xd1Z\xac(\xa5\x90\xdcx\xbe@}\xe4\xb8Z\xac(\x82\x90\xdcx\x88@}\xe4\xd2Z\xac(\x98\x90\xdcx\x89@}\xe4\xb6Z\xac(\x92\x90\xdcx\xa8@}\xe4\xd3Z\xac(\x99\x90\xdcx\x80@}\xe4\xa9Z\xac(\x85\x90\xdcx\x89@}\xe4\xd3Z\xac(?mime=true'
[download] Destination: [WwW.skstream.net]-Big Buck Bunny DVDRiP - FRENCH.avi.mp4-miEoI5oT8JE.mp4
[download] 100% of 36.00B in 00:00
...
<end of log>
```

---

---

### Description of your *issue*, suggested solution and other information

The link generated by the current code does not work and is much different when compared to the link generated by this code (which works): https://gist.github.com/Tithen-Firion/8b3921d745131837519d5c5b95b86440

**Comment by ruvort** [comment]
@dstftw How come this was closed and marked a duplicate? I did not see any other open issues stating there was a problem with the newly merged phantomjs code.

**Comment by yan12125** [comment]
#14225 is merged but not included in the latest version yet. Make sure you're using git-master if you want to try it.
```
$ python youtube_dl/__main__.py -v "http://openload.co/embed/miEoI5oT8JE"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://openload.co/embed/miEoI5oT8JE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.15
[debug] Git HEAD: 4d8c4b46d
[debug] Python version 3.6.2 - Linux-4.13.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, phantomjs 2.1.1
[debug] Proxy map: {}
[Openload] miEoI5oT8JE: Downloading webpage
[Openload] miEoI5oT8JE: Executing JS on webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://openload.co/stream/miEoI5oT8JE~1505887623~140.109.0.0~Vm5LQouk?mime=true'
[download] Destination: [WwW.skstream.net]-Big Buck Bunny DVDRiP - FRENCH.avi.mp4-miEoI5oT8JE.mp4
[download]  41.9% of 81.44MiB at  1.39MiB/s ETA 00:34^Csys:1: ResourceWarning: unclosed file <_io.BufferedWriter name='[WwW.skstream.net]-Big Buck Bunny DVDRiP - FRENCH.avi.mp4-miEoI5oT8JE.mp4.part'>

ERROR: Interrupted by user
```
Also, phantomjs should be new enough. According to Tithen-Firion, phantomjs 1.9.8 doesn't work. You can check the ```exe versions``` line.
