### ISSUE TITLE
[Documentation] Document the order of formats preferred

### ISSUE THREAD

**Issue by marmistrz** [rg3/youtube-dl#14251]
README.md mentions a lot about determining precedence of formats when it comes to quality. There's no information about what order of formats is the default one (`webm`, `mp4`, etc.) and how it's changed by `--prefer-free-formats`.

**Comment by dstftw** [comment]
Fell free to file a PR.

**Comment by marmistrz** [comment]
I'd file if I knew at all. I'll do that if you point me where it's defined.

**Comment by dstftw** [comment]
Order of formats is an implementation detail and may change any time. `--prefer-free-formats` gives preference to free formats over non-free when several formats are identical according to quality metadata. Similarly, free formats order is an implementation detail.

**Comment by marmistrz** [comment]
Which formats arw considered free and which not?

**Comment by dstftw** [comment]
Royalty-free and non royalty-free correspondingly.

**Comment by marmistrz** [comment]
Is the list of royalty-free formats somewhere in the code?

Look, all my knowledge in this matter is that mp3 is patented. Just as most users'
