### ISSUE TITLE
Please, add support a credential file

### ISSUE THREAD

**Issue by kirill85** [rg3/youtube-dl#14255]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---

Please, add support config credentials file, so that you do not have to explicitly write in the program parameters your login and password from sites that require authorization to download videos.

**Comment by Hrxn** [comment]
You can already use `.netrc` files? Or what do you mean?

**Comment by dstftw** [comment]
Already supported `--netrc`.
