### ISSUE TITLE
[Parameter Help] - Is it possible to separate audio-extracting and convertig?

### ISSUE THREAD

**Issue by cyberpunkbln** [rg3/youtube-dl#14253]
Hello,

i try to downloading with following : 

`youtube-dl.exe -f bestaudio,bestaudio[acodec=opus],bestaudio[acodec=vorbis] -x --audio-format mp3 https://www.youtube.com/watch?v=eoVE4YufWR0`

He uses the m4a-source convert and delete all extracted sources, when i use -k for keep sources then he leaves the mp3, a zero-byte-m4a and webm (without converting to mp3 he leaves a opus directly with opus-container not webm-container).

Is that possible what i want and when yes how are the correct parameters?

thx

**Comment by dstftw** [comment]
Bother to ask your questions in understandable form. It's barely possible to decipher what you want and what are you trying to do.
Also when downloading multiple formats you must setup appropriate [output template](https://github.com/rg3/youtube-dl#output-template) to provide distinct names for each format file.

**Comment by cyberpunkbln** [comment]
Okay thx try to complete my questions.

I want to download the bestaudio, the bestaudio opus and the bestaudio vorbis and the i want to convert the bestaudio (first param) to mp3 and have this files:

test.m4a
test.opus
test.ogg
test.mp3

with one command. But ...

The -x parameter i must use when i want to convert to mp3. So when i use this without --audio-format he downloads me all 3 (m4a,opus,ogg) or 2 (opus,ogg) <- seems some newer youtube videos has opus as bestaudio. And he extract opus from webm. And leave me m4a,opus and ogg.

But when i use -x --audio-format mp3 he convert from bestaudio (first param) and delete all 3 bestaudio. But when i use -k to keep then he dont extract opus from webm and leaves m4a as an zero byte file.

Can i download multiple qualities with -f, the extract with -x and then convert the bestaudio (1 param, on some youtube-videos the second opus) to mp3, with one command-line? Or can i only download first the best-audios and then second download to convert to mp3?

**Comment by cyberpunkbln** [comment]
Is it possible as an Feature that youtube-dl became an new Parameter with that i can at the same time downloading and extracting audio and converting audio?
