### ISSUE TITLE
youtube-dl is not recognising my VPN in mac os?

### ISSUE THREAD

**Issue by halpz** [rg3/youtube-dl#14267]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v http://www.adultswim.com/videos/tim-erics-bedtime-stories/angel-man-extended-cut/
[debug] System config: [u'--no-check-certificate', u'-o', u'~/Downloads/%(title)s.%(ext)s', u'-f', u'bestvideo+bestaudio/best', u'--write-sub', u'--sub-format', u'srt/best', u'--sub-lang', u'en', u'--convert-subs', u'srt', u'--embed-subs']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.adultswim.com/videos/tim-erics-bedtime-stories/angel-man-extended-cut/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Python version 2.7.9 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12, avprobe 12, ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[AdultSwim] angel-man-extended-cut: Downloading webpage
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q: Downloading XML
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading f4m manifest
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading f4m manifest
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading m3u8 information
[info] Writing video subtitles to: /Users/Paul/Downloads/Tim & Eric's Bedtime Stories - Angel Man - Extended Cut.en.vtt
[debug] Invoking downloader on u'http://amd.cdn.turner.com/adultswim/episodes/no_uk_geo/tebs/2017/09/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd/hls/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd_stream_10.m3u8'
[download] Destination: /Users/Paul/Downloads/Tim & Eric's Bedtime Stories - Angel Man - Extended Cut.mp4
[debug] avconv command line: avconv -y -loglevel verbose -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
' -i 'http://amd.cdn.turner.com/adultswim/episodes/no_uk_geo/tebs/2017/09/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd/hls/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd_stream_10.m3u8' -c copy -f mp4 'file:/Users/Paul/Downloads/Tim & Eric'"'"'s Bedtime Stories - Angel Man - Extended Cut.mp4.part'
avconv version 12, Copyright (c) 2000-2016 the Libav developers
  built on Mar  6 2017 22:35:59 with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --disable-debug --disable-shared --disable-indev=jack --prefix=/usr/local/Cellar/libav/12 --enable-gpl --enable-nonfree --enable-version3 --enable-vda --cc=clang --host-cflags= --host-ldflags= --enable-libfaac --enable-libmp3lame --enable-libx264 --enable-libxvid
  libavutil     55. 20. 0 / 55. 20. 0
  libavcodec    57. 25. 0 / 57. 25. 0
  libavformat   57.  7. 2 / 57.  7. 2
  libavdevice   56.  1. 0 / 56.  1. 0
  libavfilter    6.  7. 0 /  6.  7. 0
  libavresample  3.  0. 0 /  3.  0. 0
  libswscale     4.  0. 0 /  4.  0. 0
[h264 @ 0x7fe027800600] Reinit context to 1920x1088, pix_fmt: 0
[mpegts @ 0x7fe02880a000] Estimating duration from bitrate, this may be inaccurate
[h264 @ 0x7fe028a0fa00] Ignoring NAL type 9 in extradata
[h264 @ 0x7fe028a0fa00] Ignoring NAL type 6 in extradata
    Last message repeated 3 times
[h264 @ 0x7fe028a0fa00] Reinit context to 1920x1088, pix_fmt: 0
Input #0, hls,applehttp, from 'http://amd.cdn.turner.com/adultswim/episodes/no_uk_geo/tebs/2017/09/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd/hls/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd_stream_10.m3u8':
  Duration: 00:21:30.67, start: 2.018478, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) [[27][0][0][0] / 0x001B]
      yuv420p, 1920x1080 (0x0) [PAR 1:1 DAR 16:9]
      23.98 fps, 90k tbn
    Stream #0:1: Audio: aac (LC) [[15][0][0][0] / 0x000F]
      44100 Hz, stereo, fltp, 121 kb/s
Output #0, mp4, to 'file:/Users/Paul/Downloads/Tim & Eric's Bedtime Stories - Angel Man - Extended Cut.mp4.part':
  Metadata:
    encoder         : Lavf57.7.2
    Stream #0:0: Video: h264 (High) [[33][0][0][0] / 0x0021]
      yuv420p, 1920x1080 (0x0) [PAR 1:1 DAR 16:9], q=2-31, PAR 1:1 DAR 16:9
      90k tbn
    Stream #0:1: Audio: aac (LC) [[64][0][0][0] / 0x0040]
      44100 Hz, stereo, fltp, 121 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press ctrl-c to stop encoding
Non-monotonous DTS in output stream 0:1; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fe027a24200] Timestamps are unset in a packet for stream 1. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
Non-monotonous DTS in output stream 0:1; previous: 1, current: 0; changing to 2. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:1; previous: 2, current: 0; changing to 3. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fe027a24200] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 1 >= 1
av_interleaved_write_frame(): Invalid argument


ERROR: ffmpeg exited with code 1
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1966, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1601, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1873, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1812, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/external.py", line 57, in real_download
    self.get_basename(), retval))
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 163, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 604, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 566, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.adultswim.com/videos/tim-erics-bedtime-stories/angel-man-extended-cut/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I am using VPN Unlimited, and have tried all the different modes. Open VPN, IPSec, system profiles etc - when connected I can view the stream in my web browser (VPN working) but when I try to download through youtube-dl in terminal it seems it can detect my real location ash shown here with 'UK' in the URL:

Input #0, hls,applehttp, from 'http://amd.cdn.turner.com/adultswim/episodes/no_uk_geo/tebs/2017/09/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd/hls/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd_stream_10.m3u8':

**Comment by dstftw** [comment]
Post the output with `--call-home`.

**Comment by halpz** [comment]
`youtube-dl -v --call-home http://www.adultswim.com/videos/tim-erics-bedtime-stories/angel-man-extended-cut/
[debug] System config: [u'--no-check-certificate', u'-o', u'~/Downloads/%(title)s.%(ext)s', u'-f', u'bestvideo+bestaudio/best', u'--write-sub', u'--sub-format', u'srt/best', u'--sub-lang', u'en', u'--convert-subs', u'srt', u'--embed-subs']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--call-home', u'http://www.adultswim.com/videos/tim-erics-bedtime-stories/angel-man-extended-cut/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.15
[debug] Python version 2.7.9 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12, avprobe 12, ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 209.95.53.223
[AdultSwim] angel-man-extended-cut: Downloading webpage
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q: Downloading XML
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading f4m manifest
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading f4m manifest
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] McwcnZc_RSWlF6Te67vu-Q-0: Downloading m3u8 information
[info] Writing video subtitles to: /Users/Paul/Downloads/Tim & Eric's Bedtime Stories - Angel Man - Extended Cut.en.vtt
[debug] Invoking downloader on u'http://amd.cdn.turner.com/adultswim/episodes/no_uk_geo/tebs/2017/09/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd/hls/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd_stream_10.m3u8'
[download] Destination: /Users/Paul/Downloads/Tim & Eric's Bedtime Stories - Angel Man - Extended Cut.mp4
[debug] avconv command line: avconv -y -loglevel verbose -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
' -i 'http://amd.cdn.turner.com/adultswim/episodes/no_uk_geo/tebs/2017/09/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd/hls/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd_stream_10.m3u8' -c copy -f mp4 'file:/Users/Paul/Downloads/Tim & Eric'"'"'s Bedtime Stories - Angel Man - Extended Cut.mp4.part'
avconv version 12, Copyright (c) 2000-2016 the Libav developers
  built on Mar  6 2017 22:35:59 with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --disable-debug --disable-shared --disable-indev=jack --prefix=/usr/local/Cellar/libav/12 --enable-gpl --enable-nonfree --enable-version3 --enable-vda --cc=clang --host-cflags= --host-ldflags= --enable-libfaac --enable-libmp3lame --enable-libx264 --enable-libxvid
  libavutil     55. 20. 0 / 55. 20. 0
  libavcodec    57. 25. 0 / 57. 25. 0
  libavformat   57.  7. 2 / 57.  7. 2
  libavdevice   56.  1. 0 / 56.  1. 0
  libavfilter    6.  7. 0 /  6.  7. 0
  libavresample  3.  0. 0 /  3.  0. 0
  libswscale     4.  0. 0 /  4.  0. 0
[h264 @ 0x7f838b00b600] Reinit context to 1920x1088, pix_fmt: 0
[mpegts @ 0x7f838911a000] Estimating duration from bitrate, this may be inaccurate
[h264 @ 0x7f838b19cc00] Ignoring NAL type 9 in extradata
[h264 @ 0x7f838b19cc00] Ignoring NAL type 6 in extradata
    Last message repeated 3 times
[h264 @ 0x7f838b19cc00] Reinit context to 1920x1088, pix_fmt: 0
Input #0, hls,applehttp, from 'http://amd.cdn.turner.com/adultswim/episodes/no_uk_geo/tebs/2017/09/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd/hls/tebs_cc_305_Digital_AngelMan_22Minutes_bva686570qbhcd_stream_10.m3u8':
  Duration: 00:21:30.67, start: 2.018478, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) [[27][0][0][0] / 0x001B]
      yuv420p, 1920x1080 (0x0) [PAR 1:1 DAR 16:9]
      23.98 fps, 90k tbn
    Stream #0:1: Audio: aac (LC) [[15][0][0][0] / 0x000F]
      44100 Hz, stereo, fltp, 121 kb/s
Output #0, mp4, to 'file:/Users/Paul/Downloads/Tim & Eric's Bedtime Stories - Angel Man - Extended Cut.mp4.part':
  Metadata:
    encoder         : Lavf57.7.2
    Stream #0:0: Video: h264 (High) [[33][0][0][0] / 0x0021]
      yuv420p, 1920x1080 (0x0) [PAR 1:1 DAR 16:9], q=2-31, PAR 1:1 DAR 16:9
      90k tbn
    Stream #0:1: Audio: aac (LC) [[64][0][0][0] / 0x0040]
      44100 Hz, stereo, fltp, 121 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press ctrl-c to stop encoding
Non-monotonous DTS in output stream 0:1; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7f8389209400] Timestamps are unset in a packet for stream 1. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
Non-monotonous DTS in output stream 0:1; previous: 1, current: 0; changing to 2. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:1; previous: 2, current: 0; changing to 3. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7f8389209400] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 1 >= 1
av_interleaved_write_frame(): Invalid argument


ERROR: ffmpeg exited with code 1
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1967, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1601, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1874, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1813, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/external.py", line 57, in real_download
    self.get_basename(), retval))
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 163, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 604, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 566, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())`

**Comment by halpz** [comment]
maybe VPN is not the issue? it seems to fail immediately with my VPN disabled? can anyone in the US test this link?

**Comment by dstftw** [comment]
Post the output of `curl yt-dl.org/ip`.

**Comment by dstftw** [comment]
It has nothing to do with VPN. Uninstall avconv or use `--prefer-ffmpeg`.
