### ISSUE TITLE
youtube-dl -g $url doesent get video any longer?

### ISSUE THREAD

**Issue by samigestblom83** [rg3/youtube-dl#14266]
https://r4---sn-4g5edn7y.googlevideo.com/videoplayback/id/903823a0f23a9beb/itag/140/source/youtube/requiressl/yes/ms/au/mv/m/mn/sn-4g5edn7y/pl/37/ei/8CbBWf6BHp2KVIHhhegP/initcwndbps/2145000/mm/31/ratebypass/yes/mime/audio%2Fmp4/otfp/1/gir/yes/clen/4273972/lmt/1479728153893580/dur/268.863/signature/52C42D7C242DFC84A0DA9C4B153870D02E2FD739.5051EBADE16E6CFC23B4D412EF7917CCF4463869/key/dg_yt0/mt/1505830557/ip/2a01:4f8:c0c:3a63::2/ipbits/0/expire/1505852240/sparams/ip,ipbits,expire,id,itag,source,requiressl,ms,mv,mn,pl,ei,initcwndbps,mm,ratebypass,mime,otfp,gir,clen,lmt,dur/

Is an example of the output url. I supose you guys are working on that problem wight now.

Best Regards
Sami Gestblom

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
