### ISSUE TITLE
Site Support Request: Channel 4

### ISSUE THREAD

**Issue by DrHyde** [rg3/youtube-dl#14276]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Site support request (request for adding support for a new site)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

$ youtube-dl -v http://www.channel4.com/programmes/the-great-british-bake-off/on-demand/66406-004
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.channel4.com/programmes/the-great-british-bake-off/on-demand/66406-004']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2017.09.15
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 66406-004: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 66406-004: Downloading webpage
[generic] 66406-004: Extracting information
ERROR: Unsupported URL: http://www.channel4.com/programmes/the-great-british-bake-off/on-demand/66406-004
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2116, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 30, column 186
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2964, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.channel4.com/programmes/the-great-british-bake-off/on-demand/66406-004

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.channel4.com/programmes/the-great-british-bake-off/on-demand/66406-004
- Playlist: don't think this is supported.

---

### Description of your *issue*, suggested solution and other information

Please add support for Channel 4. I know this has been asked for in the past and rejected, eg #5121, but they recently added support for downloading in their "All 4" app on Android, so presumably it's possible now.

**Comment by mtbc** [comment]
It's helpful to know *which* it's a duplicate of! Maybe #2050, though given the,

> they recently added support for downloading

I don't know if the analysis on that issue has become out of date.
