### ISSUE TITLE
Best way to add metadata (ID3 tags) to m4a files in automated code???

### ISSUE THREAD

**Issue by maurus56** [rg3/youtube-dl#14271]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [x] Other

---

After a lot of trouble with online sites I made a code for personal use, to download the way I like it but this time when trying to upgrade the functionalities I had some trouble trying to implement it.
The main issue is that I wasn't able to even get the metadata functioning in any way. So I'm writing to ask if anyone has been able to implement it into actual code, not just use it in the terminal.

For now, I'm just using these options for the download:
```python
MUSIC_OPTIONS_ = {
    'writethumbnail': True,
    'format': 'bestaudio/best',
    'extractaudio': True,
    'audioformat': 'best',
    'outtmpl': '~/Music/Youtube_dl/%(uploader)s/%(title)s.%(ext)s',
    'noplaylist': True,
    'youtubeskipdashmanifest': True,
    'nocheckcertificate': True,
    'externaldownloader': 'aria2c',
    'externaldownloaderargs': '-x 4 -k 2M',
    'postprocessors': [{'key': 'FFmpegExtractAudio',
                        'preferredcodec': 'm4a',
                        'preferredquality': '0', },
                       {'key': 'EmbedThumbnail'}]}
```
I'm shure there must be an implementation of the --add-metadata and --metadata-from-title, but I couldn't find out how.

[Full Code here](https://github.com/maurus56/youtube_multi_dl) for anyone interested in reviewing further and helping in any way.

Any commentary is welcomed.

**Comment by dstftw** [comment]
Add `FFmpegMetadataPP` postprocessor.

**Comment by maurus56** [comment]
ok, I have added the PP and tried a run, it fetches the title and artist but at the end, it isn't added.

in which part of the code should I put the ```'addmetadata': True``` ?
```python
'postprocessors': [{'key': 'FFmpegExtractAudio',
                        'preferredcodec': 'm4a',
                        'preferredquality': '0'},
                       {'key': 'EmbedThumbnail'},
                       {'key': 'MetadataFromTitle',
                        'titleformat': '(?P<title>.+)\ \-\ (?P<artist>.+)'}]}
```

**Comment by ciex** [comment]
This should be an example in the youtube-dl README within the section about embedding youtube-dl. Right now it's not possible to figure out how to setup the postprocessors dict without reading the actual postprocessor module code.
