### ISSUE TITLE
Downloaded only the indexed song in playlist

### ISSUE THREAD

**Issue by Joaobranquinho** [rg3/youtube-dl#14272]
I know there are these 3 options:

```
    --playlist-start NUMBER
    --playlist-end NUMBER
    --playlist-items ITEM_SPEC
```

But what I want is to download the song indexed in the URL ONLY.

Ex: https://www.youtube.com/watch?v=_zPlr-o-YEQ&index=5&list=RDwRzeRmFl_-M
Song number 5.

Is it possible?

**Comment by dstftw** [comment]
>[youtube:playlist] Downloading playlist RDwRzeRmFl_-M - add --no-playlist to just download video _zPlr-o-YEQ
