### ISSUE TITLE
No Video Formats found

### ISSUE THREAD

**Issue by MYounas** [rg3/youtube-dl#14286]
Error occur on downloading a course from lynda,here is the output with --verbose

I change here links and directories of my PC because of privacy issue,thanx

[debug] System config: []                                                                                               
[debug] User config: []                                                                                                 
[debug] Custom config: []                                                                                               
[debug] Command-line args: ['-o', '/Lynda - Django: 1 Building a Blog/%(chapter_number)s - %(chapter)s/%(playlist_index)
s-%(title)s.%(ext)s', 'https://aaa.aa/Django-tutorials/Django-1-Building-Blog/594453-2.html', '--verbose']        
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252                                                       
[debug] youtube-dl version 2017.09.15                                                                                   
[debug] Python version 3.5.2 - Windows-10-10.0.15063-SP0                                                                
[debug] exe versions: none                                                                                              
[debug] Proxy map: {}                                                                                                   
[generic] 594453-2: Requesting header                                                                                   
WARNING: Falling back on generic information extractor.                                                                 
[generic] 594453-2: Downloading webpage                                                                                 
[generic] 594453-2: Extracting information                                                                              
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ve
rsion; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include i
ts complete output.                                                                                                     
Traceback (most recent call last):                                                                                      
  File "....\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 776, in e
xtract_info                                                                                                             
    ie_result = ie.extract(url)                                                                                         
  File "....\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 43
4, in extract                                                                                                           
    ie_result = self._real_extract(url)                                                                                 
  File "....\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\generic.py", line 2
857, in _real_extract                                                                                                   
    self._sort_formats(entry['formats'])                                                                                
  File "...\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 10
72, in _sort_formats                                                                                                    
    raise ExtractorError('No video formats found')                                                                      
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure y
ou are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --
verbose flag and include its complete output.

**Comment by dstftw** [comment]
You must provide exact video URL.

**Comment by MYounas** [comment]
get it here

 youtube-dl -o "/Lynda - Django: 1 Building a Blog/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s" https://educourse.ga/Django-tutorials/Django-1-Building-Blog/594453-2.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '/Lynda - Django: 1 Building a Blog/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s', 'https://educourse.ga/Django-tutorials/Django-1-Building-Blog/594453-2.html', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.09.15
[debug] Python version 3.5.2 - Windows-10-10.0.15063-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 594453-2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 594453-2: Downloading webpage
[generic] 594453-2: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\my\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\my\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "c:\users\my\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\generic.py", line 2857, in _real_extract
    self._sort_formats(entry['formats'])
  File "c:\users\my\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 1072, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
