### ISSUE TITLE
Skipping DASH manifest:ExtractorError(u"Failed to download MPD manifest: <urlopen error [Errno 10054] >

### ISSUE THREAD

**Issue by liudatutu** [rg3/youtube-dl#14283]
I use Python2.7.13，youtube-dl version 2017.09.15,mycode was write in .py file

#coding=utf-8
def get_meta(url):
    ydl_opts = { 'ignoreerrors':True,'encoding': 'utf-8', 'outtmpl': u'E:/Movie/%(title)s.%(ext)s'}
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        metainfo = ydl.extract_info(url,download=False)
        for i in metainfo:
            print i,'***',metainfo[i]
if __name__=='__main__':
    get_meta('https://www.youtube.com/watch?v=wPT-YdNLxCs')

when i runing this code with any other URL i get the warning too:

[youtube] wPT-YdNLxCs: Downloading webpage
[youtube] wPT-YdNLxCs: Downloading video info webpage
[youtube] wPT-YdNLxCs: Extracting video information
[youtube] wPT-YdNLxCs: Downloading MPD manifest
WARNING: [youtube] wPT-YdNLxCs: Skipping DASH manifest: ExtractorError(u"Failed to download MPD manifest: <urlopen error [Errno 10054] > (caused by URLError(error(10054, ''),))",)
WARNING: "id" field is not a string - forcing string conversion, there is an error in extractor
upload_date *** 20140220
creator *** None
..............

why?how to solve it？

**Comment by dstftw** [comment]
Most likely a network issue on your side.
