### ISSUE TITLE
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by bitsnaps** [rg3/youtube-dl#14289]
Hi guys,
Using the latest version at this moment (2017.09.15), I'm getting this error message:
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

OS: Windows 7
used command (batch file): 
youtube-dl -o "%%(playlist)s/%%(playlist_index)s - %%(title)s.%%(ext)s" --username  MyEmail@server.com --password MyPassword --all-subs "pluralsight-full-url"  --verbose

the script worked well, now it downloads only the first file.

Regards

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
