### ISSUE TITLE
bilibili :ERROR: BiliBili returns error -5016

### ISSUE THREAD

**Issue by luhy118** [rg3/youtube-dl#14296]
D:\workspace\clip-spider>youtube-dl https://www.bilibili.com/video/av8954693
[BiliBili] 8954693: Downloading webpage
[BiliBili] 8954693: Downloading video info page
ERROR: BiliBili returns error -5016

**Comment by yan12125** [comment]
A quick-and-dirty fix:
```Diff
diff --git a/youtube_dl/extractor/bilibili.py b/youtube_dl/extractor/bilibili.py
index 1e57310d6..1334bc94c 100644
--- a/youtube_dl/extractor/bilibili.py
+++ b/youtube_dl/extractor/bilibili.py
@@ -113,7 +113,7 @@ class BiliBiliIE(InfoExtractor):
                 self._report_error(js)
             cid = js['result']['cid']
 
-        payload = 'appkey=%s&cid=%s&otype=json&quality=2&type=mp4' % (self._APP_KEY, cid)
+        payload = 'appkey=%s&cid=%s&otype=json&quality=0&type=' % (self._APP_KEY, cid)
         sign = hashlib.md5((payload + self._BILIBILI_KEY).encode('utf-8')).hexdigest()
 
         video_info = self._download_json(
```

**Comment by jaykay12** [comment]
It did worked fine with me. @luhy118 
`youtube-dl https://www.bilibili.com/video/av8954693`
`[BiliBili] 8954693: Downloading webpage`
`[BiliBili] 8954693: Downloading video info page`
`[download] Destination: 权力灰色地带谁来管，神秘部门来帮你-8954693.mp4`
`[download] 100% of 29.74MiB in 01:24`

**Comment by luhy118** [comment]
now it sure.
