### ISSUE TITLE
Convert subtitles to lrc?

### ISSUE THREAD

**Issue by DuendeInexistente** [rg3/youtube-dl#14292]
This one is simple: Youtube-dl gives an option to convert subtitles to a desired format, but lrc isn't one of the provided options. Adding support for it would be trivial (Ffmpeg already does it on it's own) and, I think, it'd be a great help when downloading music from such [channels which add subtitles to all their songs](https://www.youtube.com/user/ScottBradleeLovesYa).

I already checked out `--exec` to do this, but that runs commands with the file's full name, while the subtitle always differs slightly from the video. Embedding the subtitle into the file and converting that could also work I guess, but my experience is that sometimes (I think when multiple formats are mixed into a mkv container?) subtitle embedding just fails. 

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

**Comment by yan12125** [comment]
> Ffmpeg already does it on it's own

Good to know that! ```lrc``` will be accepted as a subtitle conversion target in the next version.
