### ISSUE TITLE
VRV.co extractor error has occurred. (caused by KeyError('streams',))

### ISSUE THREAD

**Issue by bobpaul** [rg3/youtube-dl#14307]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**
$ youtube-dl --version
2017.09.24

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
There are a couple of issues, but they're tagged geo-restricted and other user failures. I believe my issue is unique.

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://vrv.co/watch/G675N2D1R/HarmonQuest:The-Quest-Continues', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.24
[debug] Python version 3.6.2 - Linux-4.12.10-2-zen-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[vrv] G675N2D1R: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('streams',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/vrv.py", line 110, in _real_extract
    streams_path = video_data['__links__']['streams']['href']
KeyError: 'streams'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/vrv.py", line 110, in _real_extract
    streams_path = video_data['__links__']['streams']['href']
KeyError: 'streams'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 777, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 447, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('streams',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
I have verified that my username/password on the commandline are correct and that I'm able to view this episode using the given URL in my browser. I also tried the shorter URL https://vrv.co/watch/G675N2D1R which also failed in the same manor.

**Comment by twiclo** [comment]
I'm also having this issue. I noticed the other one is geo-restricted so if it helps at all, I'm in the US

`youtube-dl https://vrv.co/watch/GYX084D3R/HarmonQuest:The-Quest-Begins --verbose
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vrv.co/watch/GYX084D3R/HarmonQuest:The-Quest-Begins', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 3.5.4 - Linux-4.13.10-100.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five
[debug] exe versions: none
[debug] Proxy map: {}
[vrv] GYX084D3R: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('streams',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/vrv.py", line 110, in _real_extract
    streams_path = video_data['__links__']['streams']['href']
KeyError: 'streams'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/vrv.py", line 110, in _real_extract
    streams_path = video_data['__links__']['streams']['href']
KeyError: 'streams'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 783, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 447, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('streams',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by twiclo** [comment]
Okay so the account-needed tag was added but I have an account I've paid for and I've tried authenticating as well. Here's the output for the time I authenticated

```$ youtube-dl https://vrv.co/watch/GYX084D3R/HarmonQuest:The-Quest-Begins -u [My email address] --verbose
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vrv.co/watch/GYX084D3R/HarmonQuest:The-Quest-Begins', '-u', 'PRIVATE', '--verbose']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 3.5.4 - Linux-4.13.10-100.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five
[debug] exe versions: none
[debug] Proxy map: {}
[vrv] GYX084D3R: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('streams',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/vrv.py", line 110, in _real_extract
    streams_path = video_data['__links__']['streams']['href']
KeyError: 'streams'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/vrv.py", line 110, in _real_extract
    streams_path = video_data['__links__']['streams']['href']
KeyError: 'streams'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 783, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 447, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('streams',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Comment by remitamine** [comment]
an account is needed for developers interested/willing to add support for authentication, currently youtube-dl only support videos that don't require an account(free and non age-restricted videos).

**Comment by twiclo** [comment]
So it's failing because it can't find `watch.mediaResource.json.__links__.streams`. I went through the mediaResource object and found that indeed streams isn't there. The main thing it was getting from streams was the href which has been moved up to just watch.mediaResource.json.href. After changing line 110 from `streams_path = video_data['__links__']['streams']['href']` to `streams_path = video_data['__href__']` I got the below error after running `pytho3n youtube_dl/__main__.py https://vrv.co/watch/GYX084D3R/HarmonQuest:The-Quest-Begins -u twiclo@gmail.com --verbose`
```[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vrv.co/watch/GYX084D3R/HarmonQuest:The-Quest-Begins', '-u', 'PRIVATE', '--verbose']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.06
[debug] Git HEAD: 61fb07e15
[debug] Python version 3.6.2 - Linux-4.13.5-200.fc26.x86_64-x86_64-with-fedora-26-Twenty_Six
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4
[debug] Proxy map: {}
[vrv] GYX084D3R: Downloading webpage
[vrv] GYX084D3R: Downloading CMS Signing JSON metadata
[vrv] GYX084D3R: Downloading streams JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/twiclo/Projects/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/home/twiclo/Projects/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/home/twiclo/Projects/youtube-dl/youtube_dl/extractor/vrv.py", line 139, in _real_extract
    self._sort_formats(formats)
  File "/home/twiclo/Projects/youtube-dl/youtube_dl/extractor/common.py", line 1075, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
It looks like VRV changed the way they serve videos. Here's a blog post talking about it in March: https://medium.com/ellation-tech/improving-video-quality-for-crunchyroll-and-vrv-dd587261a364

It looks like a lot of the extractor is going to need a rewrite because of this. Am I right in thinking this or is there something I'm missing?

**Comment by remitamine** [comment]
>  The main thing it was getting from streams was the href which has been moved up to just watch.mediaResource.json.href. After changing line 110 from streams_path = video_data['__links__']['streams']['href'] to streams_path = video_data['__href__'] I got the below error after running

it hasn't moved up, you're requesting the same data that the extractor already have(`video_data`).

> It looks like VRV changed the way they serve videos. Here's a blog post talking about it in March: https://medium.com/ellation-tech/improving-video-quality-for-crunchyroll-and-vrv-dd587261a364
It looks like a lot of the extractor is going to need a rewrite because of this. Am I right in thinking this or is there something I'm missing?

no, the article you're referring to is about their change from old CBR RTMP streams to the new VBR HLS streams.

**Comment by twiclo** [comment]
Okay so, just to clarify with your previous comment about authentication, does the program not support authentication AT ALL or has it just not yet been built into this extractor?

**Comment by remitamine** [comment]
>does the program not support authentication AT ALL or has it just not yet been built into this extractor?

it's on the VRV extractor, every extractor that require authentication need's to add some code to handle the login process(and sometimes auth tokens if needed), this code is specific to that website.
as an example [lynda](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/lynda.py) and [udemy](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/udemy.py#L142-L180) extractors both support authentication but the code to add support is different.

**Comment by Vigilence** [comment]
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', 'https://vrv.co/watch/GYX0EDP5R/', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-89073-gff8f40a630, ffprobe N-89073-gff8f40a630
[debug] Proxy map: {}
[vrv] GYX0EDP5R: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('streams',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\vrv.py", line 110, in _real_extract
KeyError: 'streams'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\vrv.py", line 110, in _real_extract
KeyError: 'streams'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 450, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('streams',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

This particular video requires a subscription to view, so authentication appears to be an issue.

**Comment by PeregrineZ** [comment]
I think I see the probem.

I've been trying to download a movie off of vrv.co manually, and they've encrypted their videos inside a .M3u8 file referencing an array of .ts files with AES-128-CBC encryption. I'm working on decrypting a segment using the OpenSSL binaries, but unfortunately programming this into Youtube-DL is a bit over my level.

If any devs need me to provide my vrv.co account, I'd be happy to!

**Comment by Vigilence** [comment]
If you have the latest firefox (57) you can downgrade to the prior release (56.0.2), and then get the addon video downloader helper to download from vrv and other similar sites.  Disable updates for the browser if need be or it will autoupdate.   

Version 7 of VDH is partially broken so these steps are needed to use the prior release which is 6.3.3 on firefox.

Chromes version of VDH doesn't work.

I am doing this until youtube-dl gets full login functionality for these sites.

**Comment by twiclo** [comment]
Just to clarify for everyone, the issue is that a login is required to view this video and the login hasn't been built into the vrv extractor yet. It works just fine if you're watching a video that requires no account. Doesn't have anything to do with the video format. Thanks for all the help everyone

**Comment by PeregrineZ** [comment]
Oh okay, seems I was mistaken.

**Comment by hadees** [comment]
So i've been looking into this bug, if you use the cookies you should be able to get around the login.  The problem is you still can't get the streams.

**Comment by majorcyto** [comment]
Hi, has there been any progress on this?

**Comment by gastaunda** [comment]
Hi, is anyone working on this bug?

**Comment by majorcyto** [comment]
If someone donates a premium account is a dev from youtube-dl willing to work on this issue?

**Comment by dawnerd** [comment]
Using 'Flash Video Downloader' to get the stream url and ffmpeg to download `ffmpeg -i <url> -c copy -bsf:a aac_adtstoasc output.mp4` it works.

Looks like the `download_hls` url from the streams json file works too.

@hadees I think you were close. That ID can be found in the episodes endpoint (there's a stream object that points to the stream json) which can be built using the episode id from the url.

Not sure how it would work with one-off files like movies but it's a start.

**Comment by dawnerd** [comment]
Playing around with it, definitely an auth issue. We might be able to get around calling the cms_resource route by just building the resource urls ourself by using the url signature from: `window.__INITIAL_STATE__.index.endpoints.discIndex.href`

I feel like Im close, can hit the generated url in curl and get data, but using `_download_json` gives me a 403.

Anyone else wanna jump in?

**Comment by shinji257** [comment]
I can't really do this (or even provide an account -- not sure I want to supply my normal credentials) however I do want to add this as it may be relevant.

I have a VRV account linked to CrunchyRoll.  I'm noticing that if I use an authenticated account (cookies method) that is currently using the HTML5 player to download a CrunchyRoll url that it will retrieve from the VRV servers.  It might help someone checking it out.

Oh and please don't forget about subs.  Flash Video Downloader doesn't download soft subs from VRV.

**Comment by albino1** [comment]
It has a 30 Day Free Trial.  I would think this could be used to add support.

**Comment by ahmedtds** [comment]
If someone donates a premium account is a dev from youtube-dl willing to work on this issue?

**Comment by cclloyd** [comment]
I'm willing to donate a premium account for 2 months to help fix this issue and add login support for VRV.

**Comment by LJMendelson** [comment]
The odd thing is that this isn't a problem with all VRV.co content.  I watched all of Cells at Work! and The Ancient Magus' Bride appears to be fine too, just to name a few.  The quality difference with Madvr and a .3dlut vs viewing in any web browser make me love this extension, so the hit and miss nature kind of sucks.  For bandwidth savings, it makes me wonder if VRV actively encrypts high-volume titles knowing that extensions like this exist.

**Comment by cclloyd** [comment]
If this can get fixed soon by anyone let me know.  Funimation will be pulling their content from VRV (including Funimation owned Crunchyroll content), so we need this working in time to download those series before they get removed from VRV.

**Comment by binsenpai** [comment]
Anyone adding support for this?

**Comment by RIpnPip** [comment]
I can Provide a VPN for free  if you guys are willing to fix the issue , and an account too! 

I failed to correctly make a post but this is still an ongoing issue.

**Comment by shinji257** [comment]
Currently getting "ERROR: Request signature mismatch." regardless if I am trying to pull something authenticated or not.  It doesn't seem to matter if the video needs authentication or not to stream.

![image](https://user-images.githubusercontent.com/261005/51545309-b5913780-1e2f-11e9-94a9-0eec16ec7dd8.png)

Checked on the latest git push but I might be jumping the gun here too.

**Comment by shinji257** [comment]
I should have known it was a Python 2.7 issue. ;)

That fix took care of it.  Thank you for your efforts.  😺

**Comment by Stzam** [comment]
Hi can some help me im trying to download from vrv is my command wrong or does it not work anymore i have the latest version of Youtube-dl   but this command is not working 
youtube-dl -u -p pasword  https://vrv.co/watch/GYW42W906/The-Fruit-of-Grisaia:An-Ordinary-School-Life
