### ISSUE TITLE
WARNING: video doesn't have subtitles ...

### ISSUE THREAD

**Issue by Albretch** [rg3/youtube-dl#14301]
// __ Donald Trump (USA) addresses the United Nations General Debate, 72nd session

youtube.com/watch?v=ha1Fbi4Nzi4

if you click on "cc" (Subtitles/closed captions), you will notice a pop up window on the upper left corner that reads: "English/auto generated"; then you see the subtitles. 

How do I get those?

lbrtchx

## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

[youtube] ha1Fbi4Nzi4: Downloading webpage
[youtube] ha1Fbi4Nzi4: Downloading video info webpage
[youtube] ha1Fbi4Nzi4: Extracting video information
WARNING: video doesn't have subtitles
[youtube] ha1Fbi4Nzi4: Downloading MPD manifest

**Comment by ctrlcctrlv** [comment]
I have the same issue. Maybe this just broke recently? Regression?

**Comment by ctrlcctrlv** [comment]
Good news! I found the solution. In the new versions, you need the flag `--write-auto-sub`.

My download works perfectly now.

```$ youtube-dl --write-auto-sub https://www.youtube.com/watch?v=fkkDvKGcNSo
[youtube] fkkDvKGcNSo: Downloading webpage
[youtube] fkkDvKGcNSo: Downloading video info webpage
[youtube] fkkDvKGcNSo: Extracting video information
[youtube] fkkDvKGcNSo: Looking for automatic captions
[youtube] fkkDvKGcNSo: Downloading MPD manifest
[info] Writing video subtitles to: /cygdrive/g/Videos/YouTube/Richard Stallman - Apple fanboys are foolish people.gu.vtt
[info] Writing video subtitles to: /cygdrive/g/Videos/YouTube/Richard Stallman - Apple fanboys are foolish people.zh-Hans.vtt
[info] Writing video subtitles to: /cygdrive/g/Videos/YouTube/Richard Stallman - Apple fanboys are foolish people.zh-Hant.vtt
[info] Writing video subtitles to: /cygdrive/g/Videos/YouTube/Richard Stallman - Apple fanboys are foolish people.gd.vtt
[info] Writing video subtitles to: /cygdrive/g/Videos/YouTube/Richard Stallman - Apple fanboys are foolish people.ga.vtt```

**Comment by ctrlcctrlv** [comment]
This is somewhat off topic, but it's truly amazing to me how good Google's YouTube automated subtitles are. We are truly living in the future. By the time I get old and lose my hearing completely it won't even matter.

![vlcsnap-2017-09-23-16h41m02s939](https://user-images.githubusercontent.com/838783/30771619-90fe532e-a07e-11e7-8421-5fb0f0e7e7bd.png)

(Oh, and another tip. You can use flag `--sub-lang en` (make sure to disable `--all-subs`) to only get the English auto sub. You probably don't need the subs in every other language poorly machine translated.)

**Comment by dstftw** [comment]
This video does not have subtitles but automatic captions available with `--write-auto-sub`.
