### ISSUE TITLE
YouTube `shared?ci=video_id` link no longer working

### ISSUE THREAD

**Issue by Khang-NT** [rg3/youtube-dl#14303]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
youtube-dl -j 'https://www.youtube.com/shared?ci=8A940MXKFmQ' -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-j', u'https://www.youtube.com/shared?ci=8A940MXKFmQ', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.15
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to extract YouTube video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 2070, in _real_extract
    'videoId', webpage, 'YouTube video id', fatal=True)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 927, in _html_search_meta
    html, display_name, fatal=fatal, group='content', **kwargs)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 806, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 797, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract YouTube video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

I look like YouTube required authentication to watch shared videos now.

**Comment by Khang-NT** [comment]
YouTube Shared video links are all dead. This issue isn't bug anymore, and consider to remove `YoutubeSharedVideoIE`.

**Comment by wb9688** [comment]
The shared YouTube URLs work again now, so I think it'll need to be re-added to `youtube-dl`.
