### ISSUE TITLE
How to embed socks5 proxy in python codes?    

### ISSUE THREAD

**Issue by luofeiyu** [rg3/youtube-dl#14311]
`youtube-dl --proxy socks5://127.0.0.1:1080 $link -o   $dir`  can download video on youtube in bash shell.
With the following  codes,we embedded youtube-dl in python codes.

    from __future__ import unicode_literals
    import youtube_dl
    ydl_opts = {}
    link = "some_youtube_url"
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([link])

How to embed socks5 proxy in python codes?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#embedding-youtube-dl
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L211
