### ISSUE TITLE
Need to Download Videos from Another URL

### ISSUE THREAD

**Issue by ilokeshk** [rg3/youtube-dl#14325]
Hi RG3,

Thank you for the tool. 
I'm trying to download Udemy videos from https://wipro.udemy.com.
I edited the script of udemy.py in youtube-dl folder, accordingly but still I'm unable to download videos.
I'm getting error, "Unable to extract login-form.
I would like to ask you if you could help me in resolving this. Please help me.

Thanks & Regards,
Lokesh.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
