### ISSUE TITLE
Fast/sleek way to download only new videos

### ISSUE THREAD

**Issue by mfessi** [rg3/youtube-dl#14338]
Hello,

is there any other way to download a new video from a channel 
then to parse it with the "download-archive" option?

Especially with large channels it takes a long time and caused a lot of requests.

Yes, there is the "dateafter" option, but it is in principle the same 
- every single video must be checked if it match the date.
I suspect there is no other possibility with the youtube api 
to identify new videos - right?

Thank you,
greetings

Martin

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#how-do-i-download-only-new-videos-from-a-playlist
