### ISSUE TITLE
Crunchyroll format selection

### ISSUE THREAD

**Issue by Niggolo** [rg3/youtube-dl#14331]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

Im trying to download only the 480P of the video, because whem in logged in with premium account i have access up to 1080P and the video is almost 1GB and i dont want to download it
i have tryed every command in every post i found on other posts!

here commands and verbose info: https://pastebin.com/aHJFYb8d

thank you

**Comment by remitamine** [comment]
you should use `best` instead of `bestvideo`, see [FORMAT SELECTION](https://github.com/rg3/youtube-dl#format-selection) for more information.
