### ISSUE TITLE
[cbc.ca:watch] Download not working, update required

### ISSUE THREAD

**Issue by ProgrammerAKL** [rg3/youtube-dl#14333]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -o "C:/Video/Heartland no 1101" "http://watch.cbc.ca/heartland/season-11/episode-1/38e815a-00d01d44474" --no-check-certificate --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/Heartland no 1101', 'http://watch.cb
c.ca/heartland/season-11/episode-1/38e815a-00d01d44474', '--no-check-certificate
', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.09.24
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 99.253.43.109 (CA) as X-Forwarded-For.
[cbc.ca:watch] 38e815a-00d01d44474: Downloading XML
ERROR: Unable to download XML: HTTP Error 401: Unauthorized (caused by HTTPError
()); please report this issue on https://yt-dl.org/bug . Make sure you are using
 the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1uop9avr\bu
ild\youtube_dl\extractor\common.py", line 503, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1uop9avr\bu
ild\youtube_dl\YoutubeDL.py", line 2178, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt

<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://watch.cbc.ca/heartland/season-11/episode-1/38e815a-00d01d44474
- Playlist: http://watch.cbc.ca/heartland/season-8/611b9a83-88a7-4027-bf79-69581089fdd6

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

The videos have no trouble playing in the browser.
For the single video http://watch.cbc.ca/heartland/season-11/episode-1/38e815a-00d01d44474, the video component is https://cbcvott-a.akamaihd.net/p//38e815a-00d01d44474/CBC_HEARTLAND_SEASON_11_S11E01-v2-14039973/segments/CBC_HEARTLAND_SEASON_11_S11E01_v6/prog_index.m3u8 and the audio component is https://cbcvott-a.akamaihd.net/p//38e815a-00d01d44474/CBC_HEARTLAND_SEASON_11_S11E01-v2-14039973/segments/CBC_HEARTLAND_SEASON_11_S11E01_a7/prog_index.m3u8. The download can be done using ffmpeg but a cookie or token seems to be needed, otherwise it will fail with HTTP error 401. Also, the URLs of the m3u8 files can be found in https://api-cbc.cloud.clearleap.com/cloffice/client/web/play/?contentId=87f31734-cbea-44ce-98e4-b06cf6a3145a&categoryId=6eefe071-5cca-4b00-9c9a-acdf8c36328d&responseType=xml - but this file, too, can only be downloaded with a cookie or token.
For the playlist http://watch.cbc.ca/heartland/season-8/611b9a83-88a7-4027-bf79-69581089fdd6, the paths to individual videos are found in https://api-cbc.cloud.clearleap.com/cloffice/client/web/browse/611b9a83-88a7-4027-bf79-69581089fdd6.

**Comment by dstftw** [comment]
```
> py -3.6 .\youtube_dl\__main__.py http://watch.cbc.ca/heartland/season-11/episode-1/38e815a-00d01d44474
[cbc.ca:watch] 38e815a-00d01d44474: Downloading XML
[download] Downloading playlist: Baby on Board
[cbc.ca:watch] playlist Baby on Board: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[cbc.ca:watch:video] 87f31734-cbea-44ce-98e4-b06cf6a3145a: Downloading XML
[cbc.ca:watch:video] 87f31734-cbea-44ce-98e4-b06cf6a3145a: Downloading m3u8 information
[download] Destination: Baby on Board-38e815a-00d01e65707.f7574.mp4
ffmpeg version N-85653-gb4330a0 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 61.100 / 55. 61.100
  libavcodec     57. 93.100 / 57. 93.100
  libavformat    57. 72.101 / 57. 72.101
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 87.100 /  6. 87.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Input #0, hls,applehttp, from 'https://cbcvott-a.akamaihd.net/p/38e815a-00d01d44474/CBC_HEARTLAND_SEASON_11_S11E01-v2-14039973/segments/CBC_HEARTLAND_SEASON_11_S11E01_v9/prog_index.m3u8':
  Duration: 00:44:10.18, start: 10.033367, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], Closed Captions, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Baby on Board-38e815a-00d01e65707.f7574.mp4.part':
  Metadata:
    encoder         : Lavf57.72.101
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
frame= 1188 fps=119 q=-1.0 Lsize=   29324kB time=00:00:39.57 bitrate=6070.4kbits/s speed=3.97x
video:29308kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.053119%
Exiting normally, received signal 2.

ERROR: Interrupted by user
```
