### ISSUE TITLE
[Udemy] Uable to extract login-form form 

### ISSUE THREAD

**Issue by ilokeshk** [rg3/youtube-dl#14330]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

--- ERROR : Unable to extract login-form form.

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\KFC>youtube-dl -v -u HIDDEN -p HIDDEN -o 'D:/'
https://wipro.udemy.com/java-tutorial/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-o', "'D:/'
", 'https://wipro.udemy.com/java-tutorial/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.09.24
[debug] Python version 3.6.2 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to extract login-form form; please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org
/update  on how to update. Be sure to call youtube-dl with the --verbose flag an
d include its complete output.
Traceback (most recent call last):
  File "c:\python\lib\site-packages\youtube_dl\YoutubeDL.py", line 777, in extra
ct_info
    ie_result = ie.extract(url)
  File "c:\python\lib\site-packages\youtube_dl\extractor\common.py", line 433, i
n extract
    self.initialize()
  File "c:\python\lib\site-packages\youtube_dl\extractor\common.py", line 391, i
n initialize
    self._real_initialize()
  File "c:\python\lib\site-packages\youtube_dl\extractor\udemy.py", line 140, in
 _real_initialize
    self._login()
  File "c:\python\lib\site-packages\youtube_dl\extractor\udemy.py", line 159, in
 _login
    login_form = self._form_hidden_inputs('login-form', login_popup)
  File "c:\python\lib\site-packages\youtube_dl\extractor\common.py", line 1067,
in _form_hidden_inputs
    html, '%s form' % form_id, group='form')
  File "c:\python\lib\site-packages\youtube_dl\extractor\common.py", line 797, i
n _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract login-form form; please r
eport this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; see  https://yt-dl.org/update  on how to update. Be sure to call youtube
-dl with the --verbose flag and include its complete output.
...
<end of log>
```
C:\Users\KFC>youtube-dl -u HIDDEN -p HIDDEN -o 'D:/' htt
ps://wipro.udemy.com/java-tutorial/
[udemy:course] Downloading login popup
ERROR: Unable to extract login-form form; please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org
/update  on how to update. Be sure to call youtube-dl with the --verbose flag an
d include its complete output.

<end of log>
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---
https://wipro.udemy.com/java-tutorial/

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Request you to please help me in resolving this.

**Comment by ThePiper-at** [comment]
I also get this error:
```
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by <HTTPError 403: 'Unauthorized'>);
```

Has there been any progress at this?
