### ISSUE TITLE
how to skip dash manifest use python file?

### ISSUE THREAD

**Issue by liudatutu** [rg3/youtube-dl#14349]
python version:2.7.13 ,youtube-dl version:20170915
I want to skip dash manifest.
this is my .py file

import youtube_dl
ydl_opts ={'forcetitle':'True','ignoreerrors':True,'youtube-skip-dash-manifest':True,
            'encoding':'utf-8','outtmpl':u'E:/Movie/%(title)s.%(ext)s','no_warnings':False,'skip_download':True}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    meta = ydl.extract_info( 'https://www.youtube.com/watch?v=6Kv9KGYaBP8',download=False)
print type(meta)
print meta
for i in meta:
    print i,'====',meta[i]

**Comment by liudatutu** [comment]
'youtube-skip-dash-manifest':True,   that does not work.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L129-L279
