### ISSUE TITLE
I cannot find the ~/.config/youtube-dl folder to access the config file

### ISSUE THREAD

**Issue by soopafly** [rg3/youtube-dl#14346]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

The ~/.config/youtube-dl folder does not exist so that I can access the config file for my user. I have unhid files with terminal to locate it. I am unsure how to run the config command so far. I believe I figured out how a while back but it errored and I cannot find the command now. I believe it is because the folder does not exist. youtube-dl standard command line works correctly. I have no other information to offer. I am just learning command line. I am trying to learn how to modify each individual download now.

**Comment by dstftw** [comment]
You are responsible for creating this folder as well as config file itself.
