### ISSUE TITLE
[Vidme] Fails to extract newer stream/dash/m38u videos

### ISSUE THREAD

**Issue by ozburo** [rg3/youtube-dl#14354]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.09.24
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Looks like Vidme has adopted the m3u8 playlist stream video format and newer videos fail extraction.

The culprit seems to be when calling the `formats_to_download = list(format_selector(ctx))` method on YoutubeDL.py which return the expected Exception "requested format not available."

I can confirm that we are able to extract the video formats from Vid.me and get the relevant video formats -- not sure how to solve this "sort_formats" issue.

Tested w/ url:
https://vid.me/a8IH6

Formats output:
[{
    u 'asr': None,
    u 'format_note': u 'DASH video',
    u 'language': None,
    u 'url': u 'https://d1wst0behutosd.cloudfront.net/videos/17307732/60308574-video-avc1-1.mp4?Expires=1506615458&Signature=CF59GLF55VLlTilssFwClMHbxCRfzgscSg1euFFlSXvPdQ6tt0HgwB4O8JH603-Wg~HVZc~2AZ5PW8ErXN~hvayShYOcnnl6nTHKWtI7Brcjfu9vDtCkLmgpNASVVVnzO0AJiEoNd-pisZEP7CKF86Zvq1HRnfFMNcV9mCkVzMGar~qk04Jt8-qpsC22c~mOrUTbiJ0HwWzo3MvuQGbEmR4UKwa6AMHSTz52VI4VT5kpeMxRewY~L0dr~GwejAqo0ZR6Rk8XByf602FGhBlArWORTASJItVMRQwAwn~-LisdewpSTIhWfA2442sCWwSzS5nCiC1LbaFfA7EW0PhDfg__&Key-Pair-Id=APKAJJ6WELAPEP47UKWQ',
    u 'vcodec': u 'avc1.42C01E',
    u 'tbr': 1789.231,
    u 'height': 480,
    u 'width': 854,
    u 'ext': u 'mp4',
    u 'filesize': None,
    u 'fps': None,
    u 'manifest_url': u 'https://api.vid.me/video/17307732/stream?format=dash',
    u 'format_id': u 'dash-video-avc1-1',
    u 'acodec': u 'none'
}, {
    u 'asr': None,
    u 'format_note': u 'DASH video',
    u 'language': None,
    u 'url': u 'https://d1wst0behutosd.cloudfront.net/videos/17307732/60308574-video-avc1-2.mp4?Expires=1506615458&Signature=cZIiCQ54qFAoKwcMMls9Y5amWMg54pKqMKMrcDKtR8KfoF4lkYJXRvEgP7YGuo9EcmJHgAOaNWV9sK6uUOJnUd3nV6SS~vsaVnuNTAttqOreBeZim2AnGLLs31KFKHrbNvYyslHeaiwU337KIF1vVEAbhZh3N5B-u2IvYZkgfmadRklNsgEezuY49gCMUaa~gxj5HAVxigv~YlWSfU1Nxu7TsAZ3p8Z7Y6QAeYNUvcj50SlVgkQKrZ8wy-cUyGyIRGMbcDJ7OxbA9SDJkoLjytD5y~Bj0kFju-8y579JxLA1Fpi763TFQak1bdE~o2MPV9PaYAfgwjFK7MYc7Fa~Lw__&Key-Pair-Id=APKAJJ6WELAPEP47UKWQ',
    u 'vcodec': u 'avc1.42C015',
    u 'tbr': 402.19,
    u 'height': 240,
    u 'width': 426,
    u 'ext': u 'mp4',
    u 'filesize': None,
    u 'fps': None,
    u 'manifest_url': u 'https://api.vid.me/video/17307732/stream?format=dash',
    u 'format_id': u 'dash-video-avc1-2',
    u 'acodec': u 'none'
}, {
    u 'asr': None,
    u 'format_note': u 'DASH video',
    u 'language': None,
    u 'url': u 'https://d1wst0behutosd.cloudfront.net/videos/17307732/60308574-video-avc1-3.mp4?Expires=1506615458&Signature=aabc6~rysdakBMt7wtsjwwRKApwvp0t14DqJJ97nYIIOOOycik08G5Hf3uNOqxccHiKaT4nNMcbQR3eQ0YqAMykL79KT8omm9PEastNOhiIAp4k9q6hm9k5EDmW7VxEH86kxx74ENhDcoV4QbNkunfakbAOL14~eUz1ugS6y6FfCOaZsolzuO5bjfGzKv5enL73HcR8k0mNPtRRuoZ4eb8KXlyCukvqk2X-INBuqZ-MeVX2W6Rj0MpoQKhzgsRDv0sgZB0SQK-b~L-f0SxdhjGP4ufNVWX9k9~T11iUiQtKar5yDifrNP7RdUgjG4LHehVc5pJkxqqsP4OjBVUULDg__&Key-Pair-Id=APKAJJ6WELAPEP47UKWQ',
    u 'vcodec': u 'avc1.64001F',
    u 'tbr': 1896.086,
    u 'height': 720,
    u 'width': 1280,
    u 'ext': u 'mp4',
    u 'filesize': None,
    u 'fps': None,
    u 'manifest_url': u 'https://api.vid.me/video/17307732/stream?format=dash',
    u 'format_id': u 'dash-video-avc1-3',
    u 'acodec': u 'none'
}, {
    u 'asr': None,
    u 'format_note': u 'DASH video',
    u 'language': None,
    u 'url': u 'https://d1wst0behutosd.cloudfront.net/videos/17307732/60308574-video-avc1-4.mp4?Expires=1506615458&Signature=fbfm6OHZXqnVlXeGnNCnecm7pNLQPi7FBOLSBcsUiblRoMRV9CeIZ8BImDPL6D0a0W8GAkRNtVfUNCkV37xa127QJ1T6K4NrTvgIUOFki6vynw4vx5H6r4SBIz-Y~7E54upz1x2ph55f4Y10myTCbZimQ-KnguBSxWlVsSvkKDTYrSN4FO~hmvd~xyQUGY0Qv~Oh3PJGIJdf9adCJnFkqhgzjvNvj1eKcD~KpBQKaZWbqhZGMmlEysVbDLahqZle7JOBbpakaZSfNYVrN6iLJRM15EmBh9E4A3Nwdg1D3dzjqSSuVBA9pBTCkmZ2Y8L1tVglgjXoWxMkaEIkLunZmQ__&Key-Pair-Id=APKAJJ6WELAPEP47UKWQ',
    u 'vcodec': u 'avc1.640028',
    u 'tbr': 1871.94,
    u 'height': 1080,
    u 'width': 1920,
    u 'ext': u 'mp4',
    u 'filesize': None,
    u 'fps': None,
    u 'manifest_url': u 'https://api.vid.me/video/17307732/stream?format=dash',
    u 'format_id': u 'dash-video-avc1-4',
    u 'acodec': u 'none'
}, {
    u 'asr': 48000,
    u 'format_note': u 'DASH audio',
    u 'language': None,
    u 'url': u 'https://d1wst0behutosd.cloudfront.net/videos/17307732/60308574-audio-und-mp4a-1.mp4?Expires=1506615458&Signature=hrv5s8CJ71-eowvnF3WLcHkeKxiwBVGw7IssJJvxHAcm3olqPnOC6jjB3UidHhfypenbEL~eq63Kicr22gE6bX8ly4NXtMcVbjX5~ieJ5T3h6xk-wvjFJeu7eJOqfqmV3CLk2d5KWFi-RjNpg6FYQosi6atQ6yASb-XP6oTd59fgph8RrlQ7ho5se7o0crrdwpn6jgGGgTvzP9Uxr1rGaxQlnsYMajwN1JlUF9ZxSXXTOYueh3R6p6UkM8tLByFkjUu~ZN~nHmCZgGQ4ZLX6Zm28PsSoQVWp4KjN8vLCEQklhd6DNRI1Dg3fOC1sgSnoIxBvvF7j5hQaulgPn108fg__&Key-Pair-Id=APKAJJ6WELAPEP47UKWQ',
    u 'vcodec': u 'none',
    u 'tbr': 283.371,
    u 'height': None,
    u 'width': None,
    u 'ext': u 'm4a',
    u 'filesize': None,
    u 'fps': None,
    u 'manifest_url': u 'https://api.vid.me/video/17307732/stream?format=dash',
    u 'format_id': u 'dash-audio-und-mp4a-1',
    u 'acodec': u 'mp4a.40.2'
}, {
    u 'asr': 48000,
    u 'format_note': u 'DASH audio',
    u 'language': None,
    u 'url': u 'https://d1wst0behutosd.cloudfront.net/videos/17307732/60308574-audio-und-mp4a-2.mp4?Expires=1506615458&Signature=Mh5KNKMAE08fyF~XUpNzw3NPrEkGusUbzyAkF1OU99M65d7fwouoNfjI9JSC8JnCTDEWb9XwofDRC6yG2H1c1EKUzuyCQo9NmuRNbr62OnJ7~R2bo~RGZaV34X9syeh-a2emepRlWaGW2H9syTOzyDlfos0POISVPIe9NWvEg9RzudF7CfVi0TupDqLecik0gwccSX3G9IvbUj3T-B9lHYF1hD~b841rl-2wnUJOYUHN-bnVWnIat2XzBKDD~TOtgLLbq4Msu81FdABibx-2TOq3Ji1KJK-eNUiVt0xrl0lCTMh4jiOjdoMW3FqkB1PhSyF3B7tCKhULtQ9lHW5GuA__&Key-Pair-Id=APKAJJ6WELAPEP47UKWQ',
    u 'vcodec': u 'none',
    u 'tbr': 124.336,
    u 'height': None,
    u 'width': None,
    u 'ext': u 'm4a',
    u 'filesize': None,
    u 'fps': None,
    u 'manifest_url': u 'https://api.vid.me/video/17307732/stream?format=dash',
    u 'format_id': u 'dash-audio-und-mp4a-2',
    u 'acodec': u 'mp4a.40.2'
}, {
    u 'protocol': u 'm3u8_native',
    u 'language': u 'und',
    u 'url': u 'https://api.vid.me/video/17307732/stream?format=hls&subformat=60308574-audio-und-mp4a-1.m3u8',
    u 'vcodec': u 'none',
    u 'ext': u 'mp4',
    u 'preference': None,
    u 'manifest_url': u 'https://api.vid.me/video/17307732/stream?format=hls',
    u 'format_id': u 'audio/mp4a-Unknown'
}, {
    u 'protocol': u 'm3u8_native',
    u 'language': u 'und',
    u 'url': u 'https://api.vid.me/video/17307732/stream?format=hls&subformat=60308574-audio-und-mp4a-2.m3u8',
    u 'vcodec': u 'none',
    u 'ext': u 'mp4',
    u 'preference': None,
    u 'manifest_url': u 'https://api.vid.me/video/17307732/stream?format=hls',
    u 'format_id': u 'audio/mp4a-Unknown'
}, {
    u 'protocol': u 'm3u8_native',
    u 'url': u 'https://api.vid.me/video/17307732/stream?format=hls&subformat=60308574-video-avc1-1.m3u8',
    u 'vcodec': u 'avc1.42C01E',
    u 'tbr': 2297.275,
    u 'height': 480,
    u 'width': 854,
    u 'ext': u 'mp4',
    u 'preference': None,
    u 'fps': None,
    u 'manifest_url': u 'https://api.vid.me/video/17307732/stream?format=hls',
    u 'format_id': u 'hls-2297',
    u 'acodec': u 'none'
}, {
    u 'protocol': u 'm3u8_native',
    u 'url': u 'https://api.vid.me/video/17307732/stream?format=hls&subformat=60308574-video-avc1-2.m3u8',
    u 'vcodec': u 'avc1.42C015',
    u 'tbr': 673.641,
    u 'height': 240,
    u 'width': 426,
    u 'ext': u 'mp4',
    u 'preference': None,
    u 'fps': None,
    u 'manifest_url': u 'https://api.vid.me/video/17307732/stream?format=hls',
    u 'format_id': u 'hls-673',
    u 'acodec': u 'none'
}, {
    u 'protocol': u 'm3u8_native',
    u 'url': u 'https://api.vid.me/video/17307732/stream?format=hls&subformat=60308574-video-avc1-3.m3u8',
    u 'vcodec': u 'avc1.64001F',
    u 'tbr': 2334.302,
    u 'height': 720,
    u 'width': 1280,
    u 'ext': u 'mp4',
    u 'preference': None,
    u 'fps': None,
    u 'manifest_url': u 'https://api.vid.me/video/17307732/stream?format=hls',
    u 'format_id': u 'hls-2334',
    u 'acodec': u 'none'
}, {
    u 'protocol': u 'm3u8_native',
    u 'url': u 'https://api.vid.me/video/17307732/stream?format=hls&subformat=60308574-video-avc1-4.m3u8',
    u 'vcodec': u 'avc1.640028',
    u 'tbr': 2329.933,
    u 'height': 1080,
    u 'width': 1920,
    u 'ext': u 'mp4',
    u 'preference': None,
    u 'fps': None,
    u 'manifest_url': u 'https://api.vid.me/video/17307732/stream?format=hls',
    u 'format_id': u 'hls-2329',
    u 'acodec': u 'none'
}]

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
