### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by jhon-ach** [rg3/youtube-dl#14359]
I use youtube-dlg, but everytime I make an address to download some courses I receive error, and I got this message in my file log :+1: 
09/28/17 13:47:50] ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I tried to do update many times and also I checked that my accont is still working. Can anyone help me ? thanks

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
