### ISSUE TITLE
[Windows] Build youtube-dl.exe as 2 files (library and exe loader) [required for signing the executable]

### ISSUE THREAD

**Issue by romaincointepas** [rg3/youtube-dl#14367]
Follow-up to #10372.

In order to sign a py2exe executable on Windows with SignTools, the library and the exe loader have to be detached (there is no other way as far as I know).

This blog post explains this very well:
https://medium.com/@bjoernstiel/code-signing-py2exe-executables-a222c0d06d3f
(It seems that the only thing to do is pass the option `zipfile = "app.lib"`, right now it is set to None).

This is mostly required when shipping youtube-dl with signed Electron/nw.js apps (when the packager signs the main executables and all other executables shipped with the app).

Just to clarify, there is no need for the official youtube-dl.exe to be signed, the best approach would be to release an additional build of youtube-dl for Windows that would be 2 files: the `youtube-dl-loader.exe` and `youtube-dl.lib` (or something similar)?

@yan12125 Thoughts?

**Comment by dstftw** [comment]
You can build youtube-dl whichever way you like. Releasing additional builds for specific corner cases is not an option.

**Comment by yan12125** [comment]
I guess using official Python binaries from https://www.python.org/ with https://yt-dl.org/downloads/latest/youtube-dl is enough. You can just run ```python.exe youtube-dl``` and use it like youtube-dl.exe.
