### ISSUE TITLE
Can I download and play MP4 file encrypted by DRM?

### ISSUE THREAD

**Issue by mshmomo** [rg3/youtube-dl#14373]
Hello
I have very Big problem with "shahid.net" site it has some programs encrypted by DRM and needs "Plus" member to watch it "and I already have plus account" but I was searching allot for any way to play "MPD" file and its need 2 files 
first is the MPD file link, the second is License link,
https://d2vow3x5tzuxc5.cloudfront.net/u/Assets/a1/9D/5F/a1-2793054/s1-22262898/a1-2793054-s1-22262898.mpd

https://api.dmlib.com/v1/dms/modular/776d680d-794e-44ef-99a3-2a71268e28e8?token=v%3D1.0%3Bcid%3D776d680d-794e-44ef-99a3-2a71268e28e8%3Bp%3D-1%3Br%3D-1%3Ba%3Dfffb027c-2659-4c98-a05b-fcb465fd8b01%3Bc%3DEGY%3Bl%3D0%3Bpn%3Dd3_default%3Brt%3DSubscription%3Bn%3Dd3322c20-c5d6-464c-ab64-f0d2ea16bc77%3Bt%3D2017-10-01T00%3A25%3A21Z%3Bsig%3DeNnelz%2Bt25fM%2FnkqrHjFDx2LSPsBRgDLCMkUu%2BaAqcrP3FvvThqpYSWBBIbrNh%2FSXt7COoq8Ovw722UfCkCV7i%2FqsfyEXPt2qR9dFFuO793CitC2rmUncUQnbc8VYpqH2cDR%2FSvrH1SIXg6mGk%2BsVQNtpDKmFoBLFCzSG3AlcOncFKp9MZTvFM%2BJHD0JlpyMZu5lNEyeU7cwpZHB4TGt%2Fz%2F4c3hygy%2BefTClVeMNPWStxea%2BYZOfcKcPCa%2BPjipbMKPtqDxAOUx7Vg3ophPoE32%2FXE9L5tM31Jx0DFUztJs0uL3gBT%2FdkoriNry92wyF7Kzh%2BOG02HwCE6pklEiWmA%3D%3D

in this web site "https://shaka-player-demo.appspot.com/demo" I was able to play video and worked fine but only for about 10 - 15 min and then I get error
_"LICENSE_REQUEST_FAILED"
"The license request failed. This could be a timeout, a network failure, or a rejection by the server. 
error.data[0] is a shaka.util.Error from the networking engine."_

**my question is:** dose there any way to merge the mp4 file with the license key to get downloadable file that work fine and decrypted
Because I already can download the program from original site in mp4 format like "https://d2vow3x5tzuxc5.cloudfront.net/u/Assets/a1/9D/5F/a1-2793054/s1-22262898/video-7.mp4" but without sound and I cant see anything only some pixels "https://s25.postimg.org/rdaw2i4db/screenshot_148.png"

**Comment by dstftw** [comment]
DRM videos are not supported.
