### ISSUE TITLE
1080p not "best" quality in `youtube-dl -F`

### ISSUE THREAD

**Issue by dolljoints** [rg3/youtube-dl#14375]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [0] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.01**

i am on 2017.09.24, it seems macports hasn't added today's update to its repos yet. (i did run `youtube-dl -U` and it told me to run macports' update procedure, which itself says everything is up to date. so. there you go.) that's unsurprising given there's been less than 24 hours for them to add it.

however, the question i'm asking about has been the case for at least 2 years, and i see no other raised issues about this, so i doubt this matters too much.

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

hi, first off i want to say, i apologise if this has been answered already. i searched the github issues for "1080p", but couldn't find anything actually telling me why this is the case.

i'm curious as to why the automatic detection in `youtube-dl -F` for the best quality seems to top out at 720p? even when 1080p or higher is available, it insists one of the 720p options is "best".

it seems like this heuristic prefers files that are audio+video together, and all 1080p or higher streams are listed as "video only", even though muxing together formats after download is completely fine and is what youtube-dl actually does in practise anyway.

this strikes me as extra weird because youtube-dl does in fact download the 1080p version with separate audio (then muxes) when you give no flags. maybe this is simply a case of `youtube-dl -F`'s display lagging behind actual behaviour?

i saw someone mention this in 2015 in a stackexchange thread, though that person said you need to specify the 1080p stream to get it to download, so obviously something about this has been changed since then. 

thanks in advance for your time and answer c:

**Comment by dstftw** [comment]
Read what does [`best` actually mean](https://github.com/rg3/youtube-dl#format-selection).
