### ISSUE TITLE
Site support request for wakanim.tv

### ISSUE THREAD

**Issue by TammysHead** [rg3/youtube-dl#14374]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

youtube-dl https://www.wakanim.tv/de/v2/catalogue/episode/2997/the-asterisk-war-omu-2 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.wakanim.tv/de/v2/catalogue/episode/2997/the-asterisk-war-omu-2', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.09.24
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-84814-gad7aff0, ffprobe N-84814-gad7aff0
[debug] Proxy map: {}
[generic] the-asterisk-war-omu-2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-asterisk-war-omu-2: Downloading webpage
[generic] the-asterisk-war-omu-2: Extracting information
ERROR: Unsupported URL: https://www.wakanim.tv/de/v2/catalogue/episode/2997/the-asterisk-war-omu-2
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1uop9avr\build\youtube_dl\YoutubeDL.py", line 777, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1uop9avr\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1uop9avr\build\youtube_dl\extractor\generic.py", line 2980, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.wakanim.tv/de/v2/catalogue/episode/2997/the-asterisk-war-omu-2
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.wakanim.tv/de/v2/catalogue/episode/2996/the-asterisk-war-omu-1
- Playlist: https://www.wakanim.tv/de/v2/catalogue/show/224/the-asterisk-war-omu

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

I don't think this is an copyright infringement, because it is the same as Crunchyroll. You would need a german proxy, if you need one, i would give you my credentials for [this](https://ra4wvpn.com/) proxy.

**Comment by TammysHead** [comment]
So, i would give you access to NordVPN ^^ I would really like to download the videos from there. There are free videos, so just tell me if you wanna do it.

**Comment by lirix360** [comment]
Please add support for this site. Service is available in many countries in Europe.

**Comment by drangel6** [comment]
Please, add support for that site!
