### ISSUE TITLE
https://www.tv3.ie/3player/show/1283/132731/0/Liar

### ISSUE THREAD

**Issue by perrywynkles** [rg3/youtube-dl#14385]
https://www.tv3.ie/3player/show/1283/132731/0/Liar

Please tell why above will not download with youtube dl . I am new here and not sure what information to give. I have updated youtube dl today.There is a TV3 mentioned in supported sites. Is that TV3.IE? If not can you please support TV3.ie. Thanks

Here is my report
This is what I get with the url http://www.tv3.ie/3player/show/1283/132731/0/Liar

---------------------------------------------------------------------
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\System32>cd C:\Users\perry\Downloads\PORTABLE\youtube-dl

C:\Users\perry\Downloads\PORTABLE\youtube-dl> youtube-dl.exe https://www.tv3.ie
/3player/show/1283/132731/0/Liar
[generic] Liar: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Liar: Downloading webpage
[generic] Liar: Extracting information
ERROR: Unsupported URL: https://www.tv3.ie/3player/show/1283/132731/0/Liar

C:\Users\perry\Downloads\PORTABLE\youtube-dl>
_______________________________________________

This is what i get with the player.ooyala.com link 
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\System32>cd C:\Users\perry\Downloads\PORTABLE\youtube-dl

C:\Users\perry\Downloads\PORTABLE\youtube-dl> youtube-dl.exe "http://player.ooy
ala.com/player/ipad/BqOWR0YzE650YBh4R46D5sXV44I2zwCp__2200.m3u8" -o video.ts
[generic] BqOWR0YzE650YBh4R46D5sXV44I2zwCp__2200: Requesting header
WARNING: Could not send HEAD request to http://player.ooyala.com/player/ipad/BqO
WR0YzE650YBh4R46D5sXV44I2zwCp__2200.m3u8: HTTP Error 404: Not Found
[generic] BqOWR0YzE650YBh4R46D5sXV44I2zwCp__2200: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.

C:\Users\perry\Downloads\PORTABLE\youtube-dl>

**Comment by yan12125** [comment]
You already know this is most likely the same issue as #12450. Just leave comments there.

**Comment by perrywynkles** [comment]
@yan12125 OK..  Thanks. Do you know if this can be solved
