### ISSUE TITLE
Can't download any Facebook video with -u & -p.

### ISSUE THREAD

**Issue by DawgNewb** [rg3/youtube-dl#14384]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f', 'bestvideo+bestaudio', 'https://www.facebook.com/ABCNews/videos/10156381282678812/', '-o', 'D:"']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.01
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 10156381282678812: Downloading webpage
WARNING: [facebook] 1459176877494655: Failed to parse JSON Expecting ',' delimiter: line 1 column 26380 (char 26379)
[facebook] 10156381282678812: Downloading webpage
WARNING: [facebook] 1459176877494655: Failed to parse JSON Expecting ',' delimiter: line 1 column 28593 (char 28592)
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf3fd6ifp\build\youtube_dl\YoutubeDL.py", line 783, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf3fd6ifp\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf3fd6ifp\build\youtube_dl\extractor\facebook.py", line 412, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf3fd6ifp\build\youtube_dl\extractor\facebook.py", line 329, in _extract_from_url
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.

```
---

### Description of your *issue*, suggested solution and other information

Its been almost week, I think.
None of these Aug/Sep youtube-dl versions working.

[Edit]

It's working unless I put -u Username -p Password

**Comment by viethqph00671** [comment]
better reinstall
```
youtube-dl -F https://www.facebook.com/ABCNews/videos/10156381282678812
[facebook] 10156381282678812: Downloading webpage
[info] Available formats for 10156381282678812:
format code               extension  resolution note
1647780335255245ad        m4a        audio only DASH audio   49k , mp4a.40.5 (44100Hz)
966107653529369v          mp4        256x144    DASH video  130k , avc1.4d401e, 30fps, video only
120878731957584vd         mp4        480x270    DASH video  252k , avc1.4d401e, 30fps, video only
527347227605338v          mp4        640x360    DASH video  488k , avc1.4d401e, 30fps, video only
1906617052925176v         mp4        854x480    DASH video  735k , avc1.4d401e, 30fps, video only
522966061371274v          mp4        1280x720   DASH video 1124k , avc1.4d401f, 30fps, video only
dash_sd_src               mp4        unknown
dash_sd_src_no_ratelimit  mp4        unknown
dash_hd_src               mp4        unknown
dash_hd_src_no_ratelimit  mp4        unknown    (best)
```

**Comment by affinityv** [comment]
Or just try again, sometimes there are errors that won't work for some reason, then later they work.  Could be that one of the YT servers is giving bad data, but another isn't for the same video; or it could be that the data you are receiving is being poisoned... but I guess that would be less likely.

**Comment by DawgNewb** [comment]
Much Thank!
I've tried again and it working fine without **-u** & **-p**

**Comment by yan12125** [comment]
Usually Facebook feeds different pages for not-logged and logged visitors, and both are complicated for youtube-dl. Due to limited time of developers, public videos are only supported via the non-logged page. If you know a way, feel free to propose below or create a pull request.
