### ISSUE TITLE
[watchbox] Broken since latest site update

### ISSUE THREAD

**Issue by Cogitri** [rg3/youtube-dl#14386]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.01**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl https://www.watchbox.de/serien/chaika-die-sargprinzessin-15235/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.watchbox.de/serien/chaika-die-sargprinzessin-15235/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.01
[debug] Python version 3.6.2 - Linux-4.13.4-g6eb9c0fc1-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4
[debug] Proxy map: {}
[WatchBox] 15235: Downloading webpage
[WatchBox] 15235: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/youtube_dl/extractor/watchbox.py", line 88, in _real_extract
    compat_str) or source['title']
KeyError: 'title'
Traceback (most recent call last):
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/youtube_dl/extractor/watchbox.py", line 88, in _real_extract
    compat_str) or source['title']
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 783, in extract_info
    ie_result = ie.extract(url)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 447, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
---
The extractor fails to run with the above error, happens with every series I tried

**Comment by dstftw** [comment]
Correct URL is https://www.watchbox.de/serien/chaika-die-sargprinzessin-15235/staffel-1/das-maedchen-mit-dem-sarg-auf-den-schultern-359512.html.
