### ISSUE TITLE
Async call for fmpeg which should be switchable

### ISSUE THREAD

**Issue by KernelDev** [rg3/youtube-dl#14383]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
Hello there,

Could you do the fmpeg call async to the download process? As the download is way faster than the convertion to mp3 for example. I know that I could use the --exec flag, but a native support would be great. This should be switchable for slower connections via a config option or a command parameter.

Best regards,

KernelDev

---

**Comment by dstftw** [comment]
Clarify what do you mean by "fmpeg call async to the download process".

**Comment by KernelDev** [comment]
Hello,

I mean, that the current workflow is: 1. Download 2. Convert 3. start at 1.
The optimized flow of the programm should be: 1. Download +start a demon to convert the file. While the first file is converting, the other pending downloads can run an start their own converter demon

**Comment by dstftw** [comment]
Out of scope.
