### ISSUE TITLE
%(ext)s broken in recent versions?

### ISSUE THREAD

**Issue by SebiderSushi** [rg3/youtube-dl#14382]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I'm using -o '%(ext)s/%(upload_date)s-%(title)s-%(id)s.%(ext)s' to group all files by format but in recent versions this seems to be broken somehow - all files are written into the same directory.

**Current Output:**
youtube-dl -o '%(ext)s/%(upload_date)s-%(title)s-%(id)s.%(ext)s' --write-thumbnail https://www.youtube.com/watch?v=afvnzFEIz4s
[...]
[youtube] afvnzFEIz4s: Writing thumbnail to: **mp4/** 20170929-StarStarSpace #21 - Relativistischer Dopplereffekt-afvnzFEIz4s **.jpg**
[...]
[download] Destination: mp4/20170929-StarStarSpace #21 - Relativistischer Dopplereffekt-afvnzFEIz4s.f137.mp4

**What I'd expect and what was happening before:**
[youtube] afvnzFEIz4s: Writing thumbnail to: **jpg/** 20170929-StarStarSpace #21 - Relativistischer Dopplereffekt-afvnzFEIz4s **.jpg**

**Comment by dstftw** [comment]
>`ext` (string): Video filename extension
>Video

**Comment by SebiderSushi** [comment]
I understand why this behaviour is on purpose but I don't see any way to get the old behaviour back. And I really appreciated it that way.
Also if this was consistent it should do this:
[youtube] afvnzFEIz4s: Writing thumbnail to: mp4/20170929-StarStarSpace #21 - Relativistischer Dopplereffekt-afvnzFEIz4s.mp4

**Comment by dstftw** [comment]
Again, `ext` is **video extension** and the behaviour was always the same. No such "old behavior" you are claiming **ever existed**.

>Also if this was consistent it should do this:
[youtube] afvnzFEIz4s: Writing thumbnail to: mp4 /20170929-StarStarSpace #21 - Relativistischer Dopplereffekt-afvnzFEIz4s .mp4

No, it's not. Otherwise it will overwrite video with thumbnail under `mp4` ext.

**Comment by SebiderSushi** [comment]
Sorry, I was very sure that it did behave this way but I must've gotten confused somehow with my shellscripts to believe that this behaviour has ever been part of youtube-dl. I guess I have to apologize for being so stubborn about it.

To correct myself:
I would find it very useful if there was some attribute with the extension of the current file, so I could group my files into folders without any hassle.
