### ISSUE TITLE
[Question]Regarding TVFPlay Extractor

### ISSUE THREAD

**Issue by jaykay12** [rg3/youtube-dl#14391]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

Is there any predefined way to extract the actual url of the video in the InfoExtractor Class of common.py?
For instance, I am having a web url of https://tvfplay.com/episode/6/139/230/1056
But, the actual url of the video, when checked is https://youtu.be/mtUTZEh9VAU
Is it possible to somehow extract the 2nd url if user inputs the 1st one?
#14379

**Comment by dstftw** [comment]
This depends on a particular site's embedding mechanism.
