### ISSUE TITLE
[EllenTube] Can't Download any video

### ISSUE THREAD

**Issue by jaykay12** [rg3/youtube-dl#14407]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.01**

### Before submitting this *issue* I have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl --verbose https://www.ellentube.com/video/ellen-meets-trailblazing-actor-asia-kate-dillon.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.ellentube.com/video/ellen-meets-trailblazing-actor-asia-kate-dillon.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.01
[debug] Python version 2.7.12 - Linux-4.4.0-53-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ellen-meets-trailblazing-actor-asia-kate-dillon: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ellen-meets-trailblazing-actor-asia-kate-dillon: Downloading webpage
[generic] ellen-meets-trailblazing-actor-asia-kate-dillon: Extracting information
ERROR: Unsupported URL: https://www.ellentube.com/video/ellen-meets-trailblazing-actor-asia-kate-dillon.html
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2156, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 36, column 56
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 783, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 3051, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.ellentube.com/video/ellen-meets-trailblazing-actor-asia-kate-dillon.html

```

### Description of the *issue*, suggested solution and other information

EllenTube uses some External Host Video Player.
All the videos present on EllenTube are now in this particular url format only, & so the current regex pattern doesn't support it. Moreover, the video id along with the actual video path also need to be extracted from the embed url.
New Video URL Pattern:
1. https://www.ellentube.com/video/ellens-biggest-most-generous-giveaway-ever.html
2. https://www.ellentube.com/video/a-big-surprise-for-big-apple-fans.html

**Comment by qkolj** [comment]
I found a band-aid fix for single videos by extracting real Kaltura ID from the video's thumbnail image, but I still have no fix for playlists. Playlists are on /episodes/<id> links, and they reference other playlist items by UUIDs.
