### ISSUE TITLE
[Facebook] Add thumbnail

### ISSUE THREAD

**Issue by valdeir2000** [rg3/youtube-dl#14416]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### Description of your *issue*, suggested solution and other information

Hello,

I was testing some options and I found two ways to extract the thumbnail of the video on Facebook.
As I do not work with Python, I'll leave a Shell Script code to assist.

**With the user logged off.**
```bash
curl "https://www.facebook.com/andressoncostaoficial/videos/713796082045907/" | \
grep -Eo "<meta[^>]property=\"og:image\"[^>]*\/>" | \
sed -rn 's/.*content="(.+)".*/\1/p'
```

**With the user logged in.**
```bash
curl -b "Cookie of the user logged in" "https://www.facebook.com/andressoncostaoficial/videos/713796082045907/" | \
grep -Eo '<img[^>]*class="_4lpf"[^>]*\/>' | \
sed -rn 's/.*src="(.+)".*/\1/p'
```

**Comment by yan12125** [comment]
Thanks for the script! I've added the og:image approach, which will be included in the next version. The _4lpf way does not work here. I guess they constantly change the class name. If you know how to capture the thumbnail for logged-in users, feel free to leave a comment below.
