### ISSUE TITLE
Youku video formats issue

### ISSUE THREAD

**Issue by Cheerleaders** [rg3/youtube-dl#14411]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.01**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--all-formats', 'http://v.youku.com/v_show/id_XMzA1NjAyNzYxNg==.html?spm=a2hzp.8253869.0.0']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.01
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86265-gb946bd8, ffprobe N-86265-gb946bd8
[debug] Proxy map: {}
[youku] XMzA1NjAyNzYxNg: Retrieving cna info
[youku] XMzA1NjAyNzYxNg: Downloading JSON metadata
[info] XMzA1NjAyNzYxNg: downloading video in 3 formats
[debug] Invoking downloader on 'http://pl-ali.youku.com/playlist/m3u8?vid=XMzA1NjAyNzYxNg%3D%3D&type=flv&ups_client_netip=117.139.10.17&ups_ts=1507139484&utid=mw1cEsKUzSkCAXWLzYzs8PvM&ccode=0401&psid=3c3b5f58544cf877638f64717e7ddd23&duration=133&expire=18000&ups_key=351e7ad63eeab7199b8bd5b505808e3b'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 15
[download] Destination: 啦啦操 《金刚芭比》--华珠校啦啦操队-XMzA1NjAyNzYxNg.mp4
[download] 100% of 14.67MiB in 00:14
[debug] ffmpeg command line: ffprobe -show_streams "file:啦啦操 《金刚芭比》--华珠校啦啦操队-XMzA1NjAyNzYxNg.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "啦啦操 《金刚芭比》--华珠校啦啦操队-XMzA1NjAyNzYxNg.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:啦啦操 《金刚芭比》--华珠校啦啦操队-XMzA1NjAyNzYxNg.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:啦啦操 《金刚芭比》--华珠校 啦啦操队-XMzA1NjAyNzYxNg.temp.mp4"
[debug] Invoking downloader on 'http://pl-ali.youku.com/playlist/m3u8?vid=XMzA1NjAyNzYxNg%3D%3D&type=mp4&ups_client_netip=117.139.10.17&ups_ts=1507139484&utid=mw1cEsKUzSkCAXWLzYzs8PvM&ccode=0401&psid=3c3b5f58544cf877638f64717e7ddd23&duration=133&expire=18000&ups_key=351e7ad63eeab7199b8bd5b505808e3b'
[download] 啦啦操 《金刚芭比》--华珠校啦啦操队-XMzA1NjAyNzYxNg.mp4 has already been downloaded
[download] 100% of 14.07MiB
[debug] ffmpeg command line: ffprobe -show_streams "file:啦啦操 《金刚芭比》--华珠校啦啦操队-XMzA1NjAyNzYxNg.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "啦啦操 《金刚芭比》--华珠校啦啦操队-XMzA1NjAyNzYxNg.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:啦啦操 《金刚芭比》--华珠校啦啦操队-XMzA1NjAyNzYxNg.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:啦啦操 《金刚芭比》--华珠校 啦啦操队-XMzA1NjAyNzYxNg.temp.mp4"
[debug] Invoking downloader on 'http://pl-ali.youku.com/playlist/m3u8?vid=XMzA1NjAyNzYxNg%3D%3D&type=hd2&ups_client_netip=117.139.10.17&ups_ts=1507139484&utid=mw1cEsKUzSkCAXWLzYzs8PvM&ccode=0401&psid=3c3b5f58544cf877638f64717e7ddd23&duration=133&expire=18000&ups_key=351e7ad63eeab7199b8bd5b505808e3b'
[download] 啦啦操 《金刚芭比》--华珠校啦啦操队-XMzA1NjAyNzYxNg.mp4 has already been downloaded
[download] 100% of 14.07MiB
[debug] ffmpeg command line: ffprobe -show_streams "file:啦啦操 《金刚芭比》--华珠校啦啦操队-XMzA1NjAyNzYxNg.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "啦啦操 《金刚芭比》--华珠校啦啦操队-XMzA1NjAyNzYxNg.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:啦啦操 《金刚芭比》--华珠校啦啦操队-XMzA1NjAyNzYxNg.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:啦啦操 《金刚芭比》--华珠校 啦啦操队-XMzA1NjAyNzYxNg.temp.mp4"

<end of log>
```

---
---

### Description of your *issue*, suggested solution and other information

I am trying to download this 2016 National Senior Pom Routine video, but it always gives me the worst quality video. So I used -F option to list all versions available:

[info] Available formats for XMzA1NjAyNzYxNg:
format code  extension  resolution note
0            mp4        640x360    14.03MiB
h3           mp4        960x540    33.26MiB
2            mp4        1280x720   62.70MiB (best)

Looks good right? Well it still won't download the "best" version even when I use -f on it. So I finally tried --all-formats, the result was pasted above. It downloaded only one version (seemingly trice in console output but on my disk there is only one video file). 

For me, the same issues happens with all the other videos on youku.com too. Hope it reproduces for you guys. 

Thanks!

**Comment by yan12125** [comment]
FYI: you need to include %(format_id)s in output templates to make --all-formats work

**Comment by Cheerleaders** [comment]
Thanks! I can get the "h3 mp4 960x540" video now:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--all-formats', '-o', '%(format_id)s', 'http://v.youku.com/v_show/id_XMzA1NjAyNzYxNg==.html?spm=a2hzp.8253869.0.0']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.01
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86265-gb946bd8, ffprobe N-86265-gb946bd8
[debug] Proxy map: {}
[youku] XMzA1NjAyNzYxNg: Retrieving cna info
[youku] XMzA1NjAyNzYxNg: Downloading JSON metadata
[info] XMzA1NjAyNzYxNg: downloading video in 3 formats
[debug] Invoking downloader on 'http://pl-ali.youku.com/playlist/m3u8?vid=XMzA1NjAyNzYxNg%3D%3D&type=flv&ups_client_netip=117.139.205.140&ups_ts=1507226444&utid=TGFdEkdefTACAXWLChFHiLSE&ccode=0401&psid=37e9858dbb42e9e434632356e3bf320b&duration=133&expire=18000&ups_key=31883d8d932594ac571e6bdf66e88f4e'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 15
[download] Destination: 0
[download] 100% of 14.67MiB in 00:11
[debug] ffmpeg command line: ffprobe -show_streams "file:0"
[ffmpeg] Fixing malformed AAC bitstream in "0"
[debug] ffmpeg command line: ffmpeg -y -i "file:0" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:0.temp"
[debug] Invoking downloader on 'http://pl-ali.youku.com/playlist/m3u8?vid=XMzA1NjAyNzYxNg%3D%3D&type=mp4&ups_client_netip=117.139.205.140&ups_ts=1507226444&utid=TGFdEkdefTACAXWLChFHiLSE&ccode=0401&psid=37e9858dbb42e9e434632356e3bf320b&duration=133&expire=18000&ups_key=31883d8d932594ac571e6bdf66e88f4e'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 15
[download] Destination: h3
[download] 100% of 34.35MiB in 00:25
[debug] ffmpeg command line: ffprobe -show_streams "file:h3"
[ffmpeg] Fixing malformed AAC bitstream in "h3"
[debug] ffmpeg command line: ffmpeg -y -i "file:h3" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:h3.temp"
[debug] Invoking downloader on 'http://pl-ali.youku.com/playlist/m3u8?vid=XMzA1NjAyNzYxNg%3D%3D&type=hd2&ups_client_netip=117.139.205.140&ups_ts=1507226444&utid=TGFdEkdefTACAXWLChFHiLSE&ccode=0401&psid=37e9858dbb42e9e434632356e3bf320b&duration=133&expire=18000&ups_key=31883d8d932594ac571e6bdf66e88f4e'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 15
[download] Destination: 2
[download] 100% of 14.67MiB in 00:10
[debug] ffmpeg command line: ffprobe -show_streams "file:2"
[ffmpeg] Fixing malformed AAC bitstream in "2"
[debug] ffmpeg command line: ffmpeg -y -i "file:2" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:2.temp"

<end of log>

However I still can't download the best format.

**Comment by yan12125** [comment]
Youku got a new mtop API. youku.py should be updated.

**Comment by CoXier** [comment]
Maybe this issue should be closed.

**Comment by yan12125** [comment]
Now only format h5 reports wrong resolution and the highest reported resolution (720p) is available, so closing.
