### ISSUE TITLE
I can't download video from raywenderlich.com

### ISSUE THREAD

**Issue by win-than-htike** [rg3/youtube-dl#14426]
Wins-MacBook-Pro:~ winthanhtike$ youtube-dlhttps://videos.raywenderlich.com/courses/68-scroll-view-school/lessons/1
-bash: youtube-dlhttps://videos.raywenderlich.com/courses/68-scroll-view-school/lessons/1: No such file or directory
Wins-MacBook-Pro:~ winthanhtike$ youtube-dl https://videos.raywenderlich.com/courses/68-scroll-view-school/lessons/1
[generic] 1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1: Downloading webpage
[generic] 1: Extracting information
[generic] 1: Downloading m3u8 information
[download] Downloading playlist: Scroll View School - Part 1: Introduction
[generic] playlist Scroll View School - Part 1: Introduction: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[download] Destination: Scroll View School - Part 1 - Introduction-1.mp4
ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.
Wins-MacBook-Pro:~ winthanhtike$

**Comment by dstftw** [comment]
>m3u8 download detected but ffmpeg or avconv could not be found. Please install one.

**Comment by tuofulearn** [comment]
Allavsoft provides two methods to download from various websites
Method 1: Copy and paste the audio or music url to Allavsoft and click Download button.
Method 2: Record option.
