### ISSUE TITLE
youtube auto generated subtitle not time synced with audio

### ISSUE THREAD

**Issue by yunw3n** [rg3/youtube-dl#14436]
[x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.07**

Command:
`youtube-dl -f 'best[ext=mp4]/best' --write-auto-sub --sub-lang en --embed-subs --embed-thumbnail IgSuFYamZas`

After run this command, the video is downloaded successfully, but the subtitle embedded in video file which is automatic generated by Youtube is not time synced with audio. But, but, when I run the command again, it downloads the subtitle again, and skip the video download(video file exists), and embed the subtitle into video file again, and then the subtitle works well.

Really weird..guess there's some issue when merging subtitle file at first time.

Run the command below will reproduce the issue.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
