### ISSUE TITLE
[Periscope User] Am not able to download a profile.

### ISSUE THREAD

**Issue by SamWillson** [rg3/youtube-dl#14433]
I cant download a profile video. I know that the user of the profile did scope on Periscope.
This is their profile link - http://periscope.tv/italdancer
It redirects to Twitter where there is no Options to view scopes.
So I tried Youtube-DL

Command I ran-
.\youtube-dl.exe periscope.tv/italdancer

Output I got-
WARNING: The url doesn't specify the protocol, trying with http
[periscope:user] italdancer: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('UserCache',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

How can I download the latest scope as the periscope link of profile redirects to twitter and twitter does not show live streams.

**Comment by dstftw** [comment]
http://periscope.tv/italdancer redirects to https://twitter.com/italdancer.
