### ISSUE TITLE
 [NBC] Am not able to download video even if it plays without TV provider login

### ISSUE THREAD

**Issue by noped** [rg3/youtube-dl#14438]
Using latest version youtube dl sorry i did include verbose, NBC changed the policy for viewing the video, now needed to create a NBC profile to view free to view video with lock icon you can create a free account here

https://www.nbc.com/sign-up

before this change you did not need auy profile and download on youtube worked fine, if you removed (s) from https

when done you get 3 free credits for new account, each credit allow you view a full locked episode,, you will need a US ip/proxy to view as it is geo locked, but i have tested this and it works the video plays if you are logged into free nbc profile it does not need to be linked to a US TV provider as long as you tokens to unlock a episode.

https://www.nbc.com/today/video/today-oct-6-2017/3590881

i need some help and understand how to use the commands --ap-mso --ap-username  --ap-password

does these command support this new NBC profile and token system nbc had  changed too since start of this week

hope someone can look into all this.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
