### ISSUE TITLE
[Reddit video] Defaults to less than best quality

### ISSUE THREAD

**Issue by Fironet** [rg3/youtube-dl#14430]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

```
[debug] System config: []
[debug] User config: ['-o', 'N:\\Videos\\%(title)s [%(uploader)s, %(extractor)s].%(ext)s', '--console-title', '--no-mtim
e']
[debug] Custom config: []
[debug] Command-line args: ['https://www.reddit.com/r/skateboarding/comments/739xm8/myself_at_the_local_ditch_spot/', '-
v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.01
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-81592-g2793ebd, ffprobe N-81592-g2793ebd, rtmpdump 2.4
[debug] Proxy map: {}
[RedditR] 739xm8: Downloading JSON metadata
[Reddit] u6l3tkxbdvoz: Downloading m3u8 information
[Reddit] u6l3tkxbdvoz: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://v.redd.it/u6l3tkxbdvoz/DASH_600_K'
[download] Destination: N:\Videos\Myself at the local ditch spot [lukiegstring, Reddit].fdash-VIDEO-4.mp4
[download] 100% of 520.54KiB in 00:00
[debug] Invoking downloader on 'https://v.redd.it/u6l3tkxbdvoz/audio'
[download] Destination: N:\Videos\Myself at the local ditch spot [lukiegstring, Reddit].fdash-AUDIO-1.m4a
[download] 100% of 103.87KiB in 00:00
[ffmpeg] Merging formats into "N:\Videos\Myself at the local ditch spot [lukiegstring, Reddit].mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:N:\Videos\Myself at the local ditch spot [lukiegstring, Reddit].fdash-VI
DEO-4.mp4" -i "file:N:\Videos\Myself at the local ditch spot [lukiegstring, Reddit].fdash-AUDIO-1.m4a" -c copy -map "0:v
:0" -map "1:a:0" "file:N:\Videos\Myself at the local ditch spot [lukiegstring, Reddit].temp.mp4"
Deleting original file N:\Videos\Myself at the local ditch spot [lukiegstring, Reddit].fdash-VIDEO-4.mp4 (pass -k to kee
p)
Deleting original file N:\Videos\Myself at the local ditch spot [lukiegstring, Reddit].fdash-AUDIO-1.m4a (pass -k to kee
p)
```

### Description of your *issue*, suggested solution and other information

---
While attempting to save [this](https://www.reddit.com/r/skateboarding/comments/739xm8/myself_at_the_local_ditch_spot/) Reddit-hosted video youtube-dl didn't default to the highest quality video and instead downloaded at 240x240 resolution (`dash-VIDEO-4`) when the best available quality is 720x720 (`dash-VIDEO-3`). See below results of `-F`.

Tested with [another video](https://www.reddit.com/r/skateboarding/comments/73n44x/one_of_the_happiest_days_of_my_skating_life_just/)—this time 16:9 ratio—and it too was downloaded at the lower resolution.

```
[info] Available formats for u6l3tkxbdvoz:
format code      extension  resolution note
audio-0-Default  mp4        audio only
audio-1-Default  mp4        audio only
hls-2020         mp4        432x432    2020k , avc1.4d001e, video only
hls-3082         mp4        640x640    3082k , avc1.4d001f, video only
hls-1060         mp4        320x320    1060k , avc1.42001e, video only
hls-957          mp4        320x320     957k , avc1.42001e, video only
hls-80           mp4        audio only   80k , mp4a.40.5
dash-VIDEO-1     mp4        480x480    DASH video 2614k , avc1.4d401f, 30fps, video only
dash-VIDEO-2     mp4        360x360    DASH video 1334k , avc1.4d401e, 30fps, video only
dash-VIDEO-3     mp4        720x720    DASH video 5160k , avc1.4d401f, 30fps, video only
dash-VIDEO-4     mp4        240x240    DASH video  669k , avc1.4d401e, 30fps, video only
dash-AUDIO-1     m4a        audio only DASH audio  131k , mp4a.40.2 (48000Hz) (best)
```
---

**Comment by Fironet** [comment]
@dstftw any clarification why this issue was closed? Is it due to youtube-dl having some fixed method of detecting the best quality that can't be tweaked per-site?

**Comment by jaykay12** [comment]
@Fironet Issue has been resolved..!!
It will be present in the next release version of youtube-dl.

Follow these commands, if you want to check the status now:
`git clone https://github.com/rg3/youtube-dl.git`
`cd youtube-dl`
`python -m youtube_dl <YOUR_DESIRED_REDDIT_LINK> --verbose`

Your Video will be downloaded in the best quality available :+1:

**Comment by Fironet** [comment]
@jaykay12 ah, cheers!
