### ISSUE TITLE
[AfreecaTV] Add support for authentication

### ISSUE THREAD

**Issue by mithridatism** [rg3/youtube-dl#14450]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.07**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\Michael\Downloads\youtube-dl>youtube-dl -v http://vod.afreecatv.com/PLAYER/STATION/26542731
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://vod.afreecatv.com/PLAYER/STATION/26542731']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.07
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[afreecatv] 26542731: Downloading XML
[afreecatv] 26542731: Downloading part 1 m3u8 information
[afreecatv] 26542731: Downloading part 2 m3u8 information
[afreecatv] 26542731: Downloading part 3 m3u8 information
[afreecatv] 26542731: Downloading part 4 m3u8 information
[afreecatv] 26542731: Downloading part 5 m3u8 information
[afreecatv] 26542731: Downloading part 6 m3u8 information
[afreecatv] 26542731: Downloading part 7 m3u8 information
[afreecatv] 26542731: Downloading part 8 m3u8 information
[afreecatv] 26542731: Downloading part 9 m3u8 information
[afreecatv] 26542731: Downloading part 10 m3u8 information
[afreecatv] 26542731: Downloading part 11 m3u8 information
[download] Downloading playlist: [생]서아 초심 찾기 방송
[afreecatv] playlist [생]서아 초심 찾기 방송: Collected 11 video ids (downloading 11 of them)
[download] Downloading video 1 of 11
[debug] Default format spec: best
[debug] Invoking downloader on 'http://videofile-hls-ko-vod-cf.afreecatv.com/video/_definst_/mp4:vod/20171001/479/F1AE1711_196617479_1.mp4/chunklist_w1264518459.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1201
[download] Destination: [생]서아 초심 찾기 방송 (part 1)-20171001_F1AE1711_196617479_1.mp4
[download]   0.3% of ~1.05GiB at 232.69KiB/s ETA 01:34:16
ERROR: Interrupted by user
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

Commit 839728f now allows me to download the video but that doesn't include the adult content.

"If you wish to watch restricted content, please log in.
Otherwise, please click "Watch" to only watch content suitable for all ages."

It only downloads the content that's "suitable for all age" and not the "restricted content". 

Is there a fix for this? It looks like you need to be logged in to view the restricted content.

-Michael

**Comment by dstftw** [comment]
Provide active example URL with restricted content.

**Comment by mithridatism** [comment]
http://vod.afreecatv.com/PLAYER/STATION/32028439
