### ISSUE TITLE
 --convert-subs doesn't work  when with  --skip-download 

### ISSUE THREAD

**Issue by scil** [rg3/youtube-dl#14454]
for example:
```
--write-sub --write-auto-sub --convert-subs srt --skip-download     
-o "%(title)s.%(ext)s"  
https://www.youtube.com/watch?v=Fnynf9Wy8IY
```
a vtt format sub file download, but it has not been converted to srt.
because `YoutubeDL` not run `post_process` , which requires `--skip-download` is False:
```
        if not self.params.get('skip_download', False):
                ...
                try:
                    self.post_process(filename, info_dict)
```

https://github.com/rg3/youtube-dl/blob/89923316210f8e17bb1a085278940e1c56fcff48/youtube_dl/YoutubeDL.py#L1818

Maybe some post processors  that convert sub files can run even if there is no video downloaded.

**Comment by gaohailang** [comment]
why close this issue?
do you have any plan to resolve this?

**Comment by lweo** [comment]
It's so inconvenient! why converting vtt to srt must require downloading the video first? I don't understand...
