### ISSUE TITLE
differences between porn websites and youtube or others? 

### ISSUE THREAD

**Issue by boistordu** [rg3/youtube-dl#14451]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [x] Other

It's pretty simple and not related to a version I think. 

Why downloadthem all plugin in chrome is getting all the videos from any website and why it s not reproductible with cli? yo ucould try all the porn website which seems the baddest website from where to get the videos?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient
