### ISSUE TITLE
Add support for blogs.msdn.microsoft.com/

### ISSUE THREAD

**Issue by AllanLRH** [rg3/youtube-dl#14469]
Would be nice with support for https://blogs.msdn.microsoft.com — an example of a post with a video is: https://blogs.msdn.microsoft.com/dotnet/2017/05/31/why-you-should-use-f/

The video in the example above is embedded from the hosting site, https://channel9.msdn.com, from which youtube-dl are able to download the video... perhaps that could make it easier to add support for https://blogs.msdn.microsoft.com?

---

- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.07**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

**Comment by affinityv** [comment]
In the page, I saw this link:
https://channel9.msdn.com/Events/Build/2017/T6064/player

I dropped off /player and it is downloading fine as follows (via socks5 proxy)
youtube-dl --proxy socks5://127.0.0.1:9350 -v 'https://channel9.msdn.com/Events/Build/2017/T6064'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--proxy', u'socks5://127.0.0.1:9350', u'-v', u'https://channel9.msdn.com/Events/Build/2017/T6064']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.12
[debug] Python version 2.7.12 - Linux-4.11.0-14-generic-x86_64-with-LinuxMint-18.2-sonya
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {u'http': u'socks5://127.0.0.1:9350', u'https': u'socks5://127.0.0.1:9350'}
[channel9] Events/Build/2017/T6064: Downloading web page
[channel9] c3b00792-3b22-426a-901b-a768001c8ca3: Downloading JSON metadata
[download] Downloading playlist: None
[channel9] playlist None: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://sec.ch9.ms/ch9/3644/f0515ec9-d34f-4216-8668-40aa75a43644/T6064_high.mp4'
[download] Destination: Why you should use F#-c3b00792-3b22-426a-901b-a768001c8ca3.mp4
[download]  20.3% of 247.78MiB at 490.55KiB/s ETA 06:52
