### ISSUE TITLE
No sound with 480P and 720p videos playlist

### ISSUE THREAD

**Issue by kangland** [rg3/youtube-dl#14468]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
PS D:\> .\youtube-dl.exe -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.10.07
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-81045-g450cf40, ffprobe N-81045-g450cf40
[debug] Proxy map: {'http': 'http://127.0.0.1:1080', 'https': 'https://127.0.0.1:1080', 'ftp': 'ftp://127.0.0.1:1080'}
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Playlist: https://www.youtube.com/playlist?list=PL66JwVEGlfHxsyopNzMOTQIew0UQJdhj4

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue* suggested solution and other information

Below command can download videos successfully. If download 360p, all videos have sound.

But 480p and 720p have no sound.  

I use potplayer  64-bit, version 1.7.3795 on Windows 10 

```
.\youtube-dl.exe  -f "best[height=480]"  -i -o "%(playlist_index)s-%(title)s.%(ext)s"  https://www.youtube.com/playlist?list=PL66JwVEGlfHxsyopNzMOTQIew0UQJdhj4

.\youtube-dl.exe  -f "best[height=720]"  -i -o "%(playlist_index)s-%(title)s.%(ext)s"  https://www.youtube.com/playlist?list=PL66JwVEGlfHxsyopNzMOTQIew0UQJdhj4

```

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by kangland** [comment]
@dstfw What do you need info ?
