### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by SuperHenkie** [rg3/youtube-dl#14467]
Youtube-dl is fantastic. This script helped me so many times, and just today I discovered it also downloads tracks from soundcloud.com and mixcloud.com 👍 👍 👍 

I would like to pay for this software. Do you guys have a Bitcoin donation address? If not, could you put one on the yt-dl.org website?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/10510#issuecomment-243806489
