### ISSUE TITLE
Strip emojis from filename

### ISSUE THREAD

**Issue by sayem314** [rg3/youtube-dl#14474]
#### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.12*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.12**

#### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

#### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

#### Description of your *issue*, suggested solution and other information

So we have `--restrict-filenames` option which remove any non-ascii character, but we do not have any option for removing emojis and keep other unicode character. For example, when I'm trying to download `https://www.youtube.com/watch?v=TuXyA2sLzmk` download will be succeeded but I can not play the file on android due to having emojis on filename. 

Again if I use `--restrict-filenames` it would work smoothly however `--restrict-filenames` is really bad for non-english video. It would strip full filename where I would like to to youtube-dl support new feature which would respect unicode character while removing emojis and other unsupported by android platform.

BTW, Thanks for this awesome tool :)

**Comment by Hrxn** [comment]
Emojis are Unicode characters as well 😄

**Comment by sayem314** [comment]
@Hrxn yes. What I meant is **removing emojis** and **keep** rest of the **unicode character.** Because on android emojis for filename is not supported.

**Comment by yan12125** [comment]
There's a (technically) similar issue at #5042. Please move on there for further discussions.
