### ISSUE TITLE
Is there a way to obtain any of the --get-x options and download the actual file as well? Question 2: how to bypass geo restrictions?

### ISSUE THREAD

**Issue by Alanz2223** [rg3/youtube-dl#14508]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.15.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.15.1**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

Question 1 - I would like to download a video and convert it to mp3 but I would also like to extract the title, duration and thumbnail. It seems that the running all the options at the same time will only output the extracted options without downloading and converting. For example 

`youtube-dl --get-title -x --audio-format mp3 --output /mypath https://www.youtube.com/watch?v=VqEbCxg2bNI`

will ONLY output the title without actually downloading the video and extracting the audio. but whenever the I use options exclusively, everything works as expected. So is there a way to do both in a single step?

Question 2 - There are certain video that have geo restrictions where I am passing the --geo-bypass option to download it but it still fails (I am using the latest youtube-dl version) so what I tried doing was setting the 'x-forwarded-for' header myself by passing the option `--add-header x-forwarded-for:CUSTOM_IP ` but it still fails. Is there a way to specify my own IP that the request will be set to?

**Comment by dstftw** [comment]
1. Parse from `--print-json`.
2. https://github.com/rg3/youtube-dl/issues/4738#issuecomment-283131958
