### ISSUE TITLE
[DRTV] Audio out of sync

### ISSUE THREAD

**Issue by fidodkk** [rg3/youtube-dl#14509]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.15.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.15.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
D:\Downloads\Youtube-DL>youtube-dl --verbose https://www.dr.dk/tv/se/kontant-tv/-/kontant-2017-10-12
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.dr.dk/tv/se/kontant-tv/-/kontant-2017-10-12']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4
[debug] Proxy map: {}
[drtv] kontant-2017-10-12: Downloading webpage
[drtv] kontant-2017-10-12: Downloading video JSON
[drtv] kontant-2017-10-12: Downloading f4m manifest
[drtv] kontant-2017-10-12: Downloading m3u8 information
[drtv] kontant-2017-10-12: Downloading f4m manifest
[drtv] kontant-2017-10-12: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://drod04k-vh.akamaihd.net/p/all/clear/download/c5/59dfc7b86187a516001533c5/Kontant--Billig-olie-paa-dyre-_06eed3ee4b6a4e44aa45c9eda441ae9a_2304.mp4'
[download] Destination: Kontant - Billig olie på dyre flasker (1_2)-kontant-2017-10-12.mp4
[download] 100% of 465.56MiB in 00:10
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Audio is out of sync when i download the video with Youtube-DL

But the same video is in sync when i download it with VSO Downloader or Internet Download Manager

I can best like to use Youtube-DL

**Comment by dstftw** [comment]
Original best quality format is out of sync. Select another format with `-f`.

**Comment by Hvass-Labs** [comment]
I have the same problem downloading from www.dr.dk

You can no longer buy this classic Danish comedy show on DVD, so I would like to save the videos from www.dr.dk but all the audio / video formats in youtube-dl are more or less out of sync. It is Danish but you can probably hear and see that the lip movements are out of sync with the sound. I have tried the newest youtube-dl on both Linux and Windows 10.

https://www.dr.dk/tv/se/jul-pa-vesterbro/-/jul-pa-vesterbro-1-24
