### ISSUE TITLE
Creating direct video link in Objective-C

### ISSUE THREAD

**Issue by cujo30227** [rg3/youtube-dl#1451]
Hi,
I'm experimenting with youtube-dl a bit to implement this in my iOS app. I'm basically reproducing the youtube.py extractor > extract the fmt stream map, identify the mp4 url, read the encrypted signature s, decrypt it using the directions in youtube.py and then adding it to the url link. For some reason, this doesn't work... It works with the non-encrypted signatures, but not with the encrypted one. Using an online Python parser, I confirmed that I have implemented the decryption procedures correctly...

Any suggestions??

**Comment by FaridHaddad** [comment]
did you solve this ?
if yes can you provide me with an answer ? thanks
