### ISSUE TITLE
Description field for new tests - variable md5 checksum?

### ISSUE THREAD

**Issue by parmjitv** [rg3/youtube-dl#14517]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.15.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.15.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Hello All,

I am trying to add a new test for an extractor and have come across a strange effect regarding the description field.

The test regards a video on the Youtube website:

https://www.youtube.com/watch?v=jWuNtik0C8E

The description for this video is quite long, so I want to set this property as an 'md5:' checksum value.  However, Youtube-dl reports a different value for this property every time I try to fetch the video.

i.e.

`'description': 'md5:1a074ab7d4303b6329fd64f116fb4fb9'`

`'description': 'md5:b3e448cc5f0c088788321c4e1f2c52d2'`

`'description': 'md5:507d1c68ec7a42d26a86f1afe2850e34'`

`'description': 'md5:676b205db857d5867e7530319b96a590'`

Why would the checksum value for the description field differ with successive hits, when the description text for this video is always the same in each case?  Has anyone seen this effect before?

Many thanks in advance!

Parmjit V.

**Comment by dstftw** [comment]
Youtube now wraps all external links in description in own redirected links with random `redir_token`.
