### ISSUE TITLE
Description field for new tests - use text or md5 prefix?

### ISSUE THREAD

**Issue by parmjitv** [rg3/youtube-dl#14510]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.15.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.15.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Hello All,

Regarding the tests in place for a given extractor, the description field is set as either a literal text string or as a MD5 checksum value.  For example:

`'description': 'Here is a literal text description of a video clip.'`
-vs-
`'description': 'md5:f3ceb5ef83a08d95b9d146f973157cc8'`

When adding a new test for an extractor, when is it appropriate to use the 'md5:' prefix for the description field?

Many thanks,

Parmjit V.

**Comment by dstftw** [comment]
md5 is usually used for a long description strings.
