### ISSUE TITLE
[REQUEST] Mark as watched only after successful download

### ISSUE THREAD

**Issue by alph4numb3r** [rg3/youtube-dl#14526]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.15.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.15.1**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Currently, youtube-dl marks a youtube video as watched (assuming the flag is on) before starting the download. If the download fails halfway, the video remains marked, but not downloaded. I'd like to request the action of marking as watched to be moved to after the download&merge sucessfully completes. It's a minor annoyance, but it'd save me a bunch of double-checking every time I grab my watch later list.

**Comment by dstftw** [comment]
Current behavior is expected. What you should use is `--download-archive`.

**Comment by alph4numb3r** [comment]
Except that that flag doesn't change anything about when the video gets marked as watched, so half-downloaded videos still show up as watched in my watch later.

**Comment by dstftw** [comment]
Nothing wrong about that. Half-watched or even only opened in browser videos are similarly marked watched by Youtube itself.
