### ISSUE TITLE
Youtube-dl download the youtube video directly to amazon s3 bucket.  

### ISSUE THREAD

**Issue by usamamashkoor** [rg3/youtube-dl#14527]
Hi i am trying to download YouTube video to amazon s3 bucket directly.Is this is something we can do with YouTube-dl or if their is some other work around then please let me know.

Thanks in advance.

**Comment by dstftw** [comment]
You must be able to run youtube-dl on it. Ask it's support.

**Comment by usamamashkoor** [comment]
It will be really great if you can give a little bit example please.
Thanks

**Comment by usamamashkoor** [comment]
Because amazon s3 is used to Store files how we can run youtube dl on it..?
