### ISSUE TITLE
 Site support: https://www.nbc.com/sign-up 

### ISSUE THREAD

**Issue by noped** [rg3/youtube-dl#14536]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---
My last issue was incorrectly labeled tv-provider-account-needed which is NOT correct.
https://github.com/rg3/youtube-dl/issues/14441

So i made a new issue 
Site support: https://www.nbc.com/sign-up 
For what reason this label has been added i dont know, tv-provider-account-needed.

https://www.nbc.com/sign-up
Instantly get 3 free credits to watch locked content.

What need to be done is that a update to youtube dl to add support for NBC profile login and password this could be done and would work, why label this issue as tv-provider-account-needed is absurd, NBC profile is free and does NOT need a tv-provider of us tv service login to use view locked content.

Can someone here look again at this, youtube dl needs a update which adds NBC FREE Profile login and password support eg this login here

https://www.nbc.com/sign-in
https://www.nbc.com/sign-up

better way to tackle this, than just labeling this as tv-provider-account-needed , when clearly this is not what the issue at all!

**Comment by dstftw** [comment]
Stop posting duplicates. Labels are for developers not for you. We are well aware of what needs to be done and what's required in general.
