### ISSUE TITLE
TruTV download fails with 403

### ISSUE THREAD

**Issue by judge2020** [rg3/youtube-dl#14537]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.15.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.15.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: [u'--netrc']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ap-mso', u'Comcast_SSO', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'http://www.trutv.com/full-episodes/adam-ruins-everything/2124090/index.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 2.7.14 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-55702-g920046a, ffprobe N-55702-g920046a
[debug] Proxy map: {}
[TruTV] 2124090: Downloading webpage
[TruTV] Downloading XML
[TruTV] 2124090: Retrieving Media Token
[TruTV] 2124090: Downloading XML
[TruTV] 2124090: Downloading m3u8 information
[TruTV] 2124090: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://androidhls-secure.cdn.turner.com/trutv/big/secure/tve/2017-10/TRUE1010051700009661_HLS/TRUE1010051700009661_Layer6_vod.m3u8'
[download] Destination: Adam Ruins Conspiracy Theories-2124090.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -seekable 0 -headers "Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: hdnea2=expires=1508467354~access=/trutv/big/secure/tve/2017-10/TRUE1010051700009661_HLS/*~md5=c296c0148edc0aef603618ad6cc435d2
" -i "http://androidhls-secure.cdn.turner.com/trutv/big/secure/tve/2017-10/TRUE1010051700009661_HLS/TRUE1010051700009661_Layer6_vod.m3u8" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:Adam Ruins Conspiracy Theories-2124090.mp4.part"
ffmpeg version N-55702-g920046a Copyright (c) 2000-2013 the FFmpeg developers
  built on Aug 21 2013 18:04:23 with gcc 4.7.3 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 42.100 / 52. 42.100
  libavcodec     55. 29.100 / 55. 29.100
  libavformat    55. 14.101 / 55. 14.101
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 82.100 /  3. 82.100
  libswscale      2.  5.100 /  2.  5.100
  libswresample   0. 17.103 /  0. 17.103
  libpostproc    52.  3.100 / 52.  3.100
[http @ 046e8700] HTTP error 403 Forbidden
Unable to open key file http://androidhls-secure.cdn.turner.com/trutv/big/secure/tve/2017-10/TRUE1010051700009661_HLS/key32d16bdd3f0b412cad1f8fdcc1886ce5-0.key
[hls,applehttp @ 02783680] Error when loading first segment 'http://androidhls-secure.cdn.turner.com/trutv/big/secure/tve/2017-10/TRUE1010051700009661_HLS/TRUE1010051700009661_Layer6/8472_Period1/segment0.ts'
http://androidhls-secure.cdn.turner.com/trutv/big/secure/tve/2017-10/TRUE1010051700009661_HLS/TRUE1010051700009661_Layer6_vod.m3u8: Invalid data found when processing input


ERROR: ffmpeg exited with code 1
  File "c:\py2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\py2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Py2\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\py2\lib\site-packages\youtube_dl\__init__.py", line 465, in main
    _real_main(argv)
  File "c:\py2\lib\site-packages\youtube_dl\__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\py2\lib\site-packages\youtube_dl\YoutubeDL.py", line 1985, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\py2\lib\site-packages\youtube_dl\YoutubeDL.py", line 795, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\py2\lib\site-packages\youtube_dl\YoutubeDL.py", line 849, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "c:\py2\lib\site-packages\youtube_dl\YoutubeDL.py", line 1619, in process_video_result
    self.process_info(new_info)
  File "c:\py2\lib\site-packages\youtube_dl\YoutubeDL.py", line 1892, in process_info
    success = dl(filename, info_dict)
  File "c:\py2\lib\site-packages\youtube_dl\YoutubeDL.py", line 1831, in dl
    return fd.download(name, info)
  File "c:\py2\lib\site-packages\youtube_dl\downloader\common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "c:\py2\lib\site-packages\youtube_dl\downloader\external.py", line 57, in real_download
    self.get_basename(), retval))
  File "c:\py2\lib\site-packages\youtube_dl\downloader\common.py", line 163, in report_error
    self.ydl.report_error(*args, **kargs)
  File "c:\py2\lib\site-packages\youtube_dl\YoutubeDL.py", line 612, in report_error
    self.trouble(error_message, tb)
  File "c:\py2\lib\site-packages\youtube_dl\YoutubeDL.py", line 574, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Downloading TruTV episodes has started to fail with HTTP error 403 forbidden.  I have confirmed that the The comcast_sso login and password are valid by logging in manually on the trutv site.

Installed with python 2.7 on Windows with pip.

**Comment by GotTheNumbers** [comment]
Just a heads up, your ffmpeg version is from 2013.

**Comment by judge2020** [comment]
Looks like that was the issue, updating path to use the latest FFmpeg fixed it. Perhaps there should be a version check when requesting HLS content.
