### ISSUE TITLE
Autonumbering problem with --download-archive option

### ISSUE THREAD

**Issue by quicktrick** [rg3/youtube-dl#14547]
Hello!

E.g., I download a playlist with the options

    -o "\path\to\my\folder\%(autonumber)s. %(title)s.%(ext)s"
    --autonumber-start 1
    --download-archive "archive.txt"

If the downloading has stopped for any reason and I restarted it after that again, then the autonumbering starts from "1" every time, regardless the number of already downloaded and skipped videos.  I think, such a behavior isn't correct.  The autonumbering should count all the skipped videos and start from the sequential number of the first new video.

**Comment by dstftw** [comment]
This is expected behavior, use `--autonumber-start`.

**Comment by Hrxn** [comment]
The program can't know the correct 'autonumber' automatically..

**Comment by quicktrick** [comment]
I think, it can count it, but I may not consider any possible failures. Alright then, I'll use `--autonumber-start` manually every time, though it's not very convenient.  Thanks for the answers!

**Comment by Hrxn** [comment]
You could write a script for this..
