### ISSUE TITLE
[Minor] Formatting bug of manpage

### ISSUE THREAD

**Issue by rbrito** [rg3/youtube-dl#14541]
Hi. Debian maintainer here. I'm just forwarding the bug that I received at:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=878280#5

> Blanks injected into filename even though same line:
>
>       --ignore-config
>              Do  not read configuration files.  When given in the global con-
>              figuration file /etc/youtube-dl.conf: Do not read the user  con-
>              figuration     in    ~/.config/youtube-    dl/config    (%APPDA-
>              TA%/youtube-dl/config.txt on Windows)
>
> And actually I would also mention those files in an additional section, FILES.

Thanks,

Rogério.

**Comment by dstftw** [comment]
Most likely a pandoc issue/misconfiguration.

**Comment by rbrito** [comment]
OK, I will try to see under what conditions the bug manifests itself. Thanks.
