### ISSUE TITLE
Provide --client-id argument to override hard-coded clientid (eg: for soundcloud extractor)

### ISSUE THREAD

**Issue by maxux** [rg3/youtube-dl#14546]
### Prerequisites
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.15.1**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Issue

Soundcloud extractor returns HTTP 401, after search on existing issues, it looks like CLIENT_ID on the code needs to be updated.

Related Issues: #11327 and #12376

I changed the CLIENT_ID to a client-id I own from soundcloud API and it works again. I guess the client-id hardcoded is expired/revoked/ban.

### Feature request

It would be cool to add a `--client-id` as argument to override hardcoded client-id. You can create your own API Client ID via https://soundcloud.com/you/apps and then use this client-id. This could provide an easy-way to bypass 401 when hardcoded client-id is not working anymore.

In addition, it could helps to debug/confirm issue related to client-id without modifying the code. This could not be limited to soundcloud.

**Comment by jacksgt** [comment]
Thanks for this fix! 👍 
(I was on 2017.10.15, fixed in 2017.10.20)
