### ISSUE TITLE
South Park corrupted downloads, something about hls features

### ISSUE THREAD

**Issue by pisto** [rg3/youtube-dl#14561]
(using the latest version, read the faq, etc.)

southpark.cc.com download used to work very well. Today it started to warn about unsupported hls feature in the native parser, but ffmpeg shows a lots of errors. The result download are playable to some extents, but there are jumps every few seconds, like for a corrupted file. The output log is very long, I have pasted it somewhere else: https://paste.fedoraproject.org/paste/ds7s3t6e~y5qFe5pwS7ifA
I have tried a few episodes, and it appears to be an issue for all of them.

**Comment by dstftw** [comment]
Install pycrypto or update ffmpeg.
