### ISSUE TITLE
Unable to download 'm3u8' stream with 'hls-prefer-native' option

### ISSUE THREAD

**Issue by horacio9a** [rg3/youtube-dl#14565]
I use youtube-dl to download `m3u8` live streams with this command:

`youtube-dl --hls-prefer-native --no-part {hlsurl} -o {filename}`

I intentionally want to avoid `ffmpeg` but I can't download more than 3 fragments!
Is there a way to make a download without this limitation?

![2462](https://user-images.githubusercontent.com/17076459/31895782-6598805a-b812-11e7-8977-4c7fca5d39db.jpg)

**Comment by dstftw** [comment]
hlsnative does not support live streams.
