### ISSUE TITLE
Soundcloud Error 401

### ISSUE THREAD

**Issue by momoe** [rg3/youtube-dl#14573]
youtube-dl https://soundcloud.com/ppseanqq/shadowbeatz-aviator-electronic[soundcloud] ppseanqq/shadowbeatz-aviator-electronic: Resolving id
[soundcloud] ppseanqq/shadowbeatz-aviator-electronic: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[momoe@momoe-pc ~]$ youtube-dl --verbose https://soundcloud.com/ppseanqq/shadowbeatz-aviator-electronic
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://soundcloud.com/ppseanqq/shadowbeatz-aviator-electronic']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.01
[debug] Python version 3.6.2 - Linux-4.9.53-1-MANJARO-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] ppseanqq/shadowbeatz-aviator-electronic: Resolving id
[soundcloud] ppseanqq/shadowbeatz-aviator-electronic: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 503, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2184, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

youtube-dl-2017.10.01-1

Manjaro: Deepin (rolling community release)

**Comment by yan12125** [comment]
This is already fixed in 2017.10.20.
