### ISSUE TITLE
[FFmpegFixupM3u8PP] prevent unnecessary re-run on resuming list download

### ISSUE THREAD

**Issue by lkho** [rg3/youtube-dl#14577]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)
- [x] Question
---

currently FFmpegFixupM3u8PP will run if using hlsnative and audio is aac.
https://github.com/rg3/youtube-dl/blob/cdd1ce92c46167c12514a061609308112e79ea84/youtube_dl/YoutubeDL.py#L1947
https://github.com/rg3/youtube-dl/blob/cdd1ce92c46167c12514a061609308112e79ea84/youtube_dl/postprocessor/ffmpeg.py#L541
Thus the processor will be invoked on existing downloaded files even those have been already processed before (if youtube-dl is called with a list of urls, and not overwriting). This makes the url list not resume-able (logically can resume, skipping the download but the post process still run and takes time, thus make the skip useless).

Can this be prevented by some sort of file renaming/ADTS detection beforehand so that the post process is run only once when a list is being resumed?

attached the `ffprobe` output of a fragment before and after running `-bsf:a aac_adtstoasc `

fragment
[a.ts.gz](https://github.com/rg3/youtube-dl/files/1411693/a.ts.gz)
`ffprobe -show_streams -print_format json a.ts`
[a.ts.txt](https://github.com/rg3/youtube-dl/files/1411689/a.ts.txt)
`ffmpeg -i a.ts -c copy -bsf:a aac_adtstoasc a.mp4`
`ffprobe -show_streams -print_format json a.mp4`
[a.mp4.txt](https://github.com/rg3/youtube-dl/files/1411688/a.mp4.txt)

**Comment by dstftw** [comment]
Use `--download-archive`.
