### ISSUE TITLE
Add subtitles to video from youtube

### ISSUE THREAD

**Issue by CoXier** [rg3/youtube-dl#14574]
# Youtube Version
2017.06.23

# OS
MAC OS

# Description
Video soruce : https://www.youtube.com/playlist?list=PLWz5rJ2EKKc9CBxr3BVjPTPoDPLdPIFCE
As you see, it's a playlist.Now I want to download all videos with its subtitles. I use below command:

```java
youtube-dl -i https://www.youtube.com/playlist\?list\=PLWz5rJ2EKKc9CBxr3BVjPTPoDPLdPIFCE -f mp4 --write-auto-sub
```
Then each video generates a mp4 file and a vtt file. However I cannot see subtitles. I have tried to use `ffmpeg` to copy video and vtt file to a new output video but nothing works.Does `youtue-dl` support adding subtitles to video from youtube?

**Comment by vapeurs** [comment]
You want to convert your .vtt (Web Video Text Tracks) files to .srt (SubRip) or similar. There are a few programs out there that can do this for you.

**Comment by dstftw** [comment]
`--embed-subs`.
