### ISSUE TITLE
Support for Alternate YouTube Playback Speeds

### ISSUE THREAD

**Issue by DasWookie** [rg3/youtube-dl#14580]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

YouTube playback through the website allows the setting of different playback speeds in the settings icon for the video. The default speed is set to "Normal" but there are other options available of: 0.25, 0.5, 0.75, 1.25, 1.5, and 2.

I'm not sure if this playback speed is implemented on the client side and thus browser support dependent, or if these are available as alternate streams to download. I very frequently end up watching a number of the channels I follow at 1.5x speed. If possible however, it would be great if were possible to specify and utilize the alternate speed(s) for the video(s). I know I could playback the video at a faster speed with some applications, but most don't shift the audio back down, resulting in high pitch voices when played back at the faster speeds, if there is alternate speed playback support available at all.

---

**Comment by dstftw** [comment]
Playback speed in an option of a player.
