### ISSUE TITLE
Speeding Up Download

### ISSUE THREAD

**Issue by adrianiezaru** [rg3/youtube-dl#14589]
Hello. How can I speed up the download speed? Sometimes it takes a lot of time to download a small file even if my internet connection is 1Gbps. Should I use an external downloader? Which one is the most appropriate? Thank you so much.

**Comment by dstftw** [comment]
aria2c or axel.

**Comment by Hrxn** [comment]
Download rates depend primarily on the site..
It should be pretty fast with e.g. YouTube, don't know what you had in mind here?
