### ISSUE TITLE
Request: Provide a simple SAMPLE Batch File example

### ISSUE THREAD

**Issue by KoolPal** [rg3/youtube-dl#14585]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---
Hello All,

Would it be possible to to provide a SIMPLE batch file example for Windows which covers 
a. List of URLS in an external text file
b. Ability to save **each list** of urls into separate folder 

While I understand there are FAQs, Readme, etc it would help if we can save such a simple example for the benefit of all.

Thanks.

**Comment by dstftw** [comment]
1. `-a path/to/file`.
2. https://github.com/rg3/youtube-dl#output-template

**Comment by KoolPal** [comment]
I hope you can assist in providing a straight forward answer.

I am trying the below command and it is giving an error. 
`youtube-dl "http://www.hotstar.com/tv/sarabhai-vs-sarabhai-2/523/seasons/season-2/" -o "D:/YoutubeDL/S3/%(episode_number)s - %(episode)s.%(ext)s"`

Please assist in downloading the series. 

Thanks.

**Comment by Hrxn** [comment]
And? What is the output? Error messages, etc.?

**Comment by KoolPal** [comment]
Thanks for replying. This is the complete output

`D:\YoutubeDL>youtube-dl "http://www.hotstar.com/tv/sarabhai-vs-sarabhai-2/523/se
asons/season-2/" -o "D:/YoutubeDL/S3/%(episode_number)s - %(episode)s.%(ext)s"
[generic] season-2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] season-2: Downloading webpage
[generic] season-2: Extracting information
ERROR: Unsupported URL: http://www.hotstar.com/tv/sarabhai-vs-sarabhai-2/523/seasons/season-2/`
