### ISSUE TITLE
How replace Python 3.4.4 with Python 2.7.13 in my Windows

### ISSUE THREAD

**Issue by horacio9a** [rg3/youtube-dl#14584]
I have installed:

C:/Python27
C:/Python36

I see that youtube-dl is used:

[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1

I see that some users have:

[debug] Python version 2.7.13 - Windows-7-6.1.7601-SP1

My question is what I need to do to replace Python 3.4.4 with Python 2.7.13 in my Windows?

Is there a way for youtube-dl to use my C:/Python27 installation?

Many thanks in advance

**Comment by dstftw** [comment]
youtube-dl.exe does not use any installed python. To use custom python version you have to build youtube-dl.exe yourself. With 2.7 branch you'll have some won't fix unicode bugs though.

**Comment by Hrxn** [comment]
> To use custom python version you have to build youtube-dl.exe yourself.

Or use the youtube-dl binary package, like this, for example: `C:\Python27\python.exe \path\to\youtube-dl`
Or install via pip.

**Comment by horacio9a** [comment]
@Hrxn 
Many thanks for easy solution.
![2467](https://user-images.githubusercontent.com/17076459/32042563-46fbc06c-ba38-11e7-8149-4373396bb711.jpg)
![2468](https://user-images.githubusercontent.com/17076459/32042565-47178d56-ba38-11e7-9c43-b37ab07e4ed0.jpg)
