### ISSUE TITLE
SoundCloud ClientID Expired   [HTTP Error 401: Unauthorized]

### ISSUE THREAD

**Issue by zylinx** [rg3/youtube-dl#14593]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
SoundCloud ClientID seems to have expired again:
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError());

Acquiring personal ClientID from SoundCloud not possible:
"Due to the high amount of requests recently received, we will no longer be processing API application requests at this time." 

---

**Comment by yan12125** [comment]
Please paste the output of "youtube-dl -v <the URL>"

**Comment by Chaz6** [comment]
Updated to latest version (2017.10.12) and it is working for me.

```
$ youtube-dl https://soundcloud.com/iamtr3p/new-dirty-party-electro-house-bass-ibiza-dance-mix-2015-best-melbourne-dutch-progressive
[soundcloud] iamtr3p/new-dirty-party-electro-house-bass-ibiza-dance-mix-2015-best-melbourne-dutch-progressive: Resolving id
[soundcloud] iamtr3p/new-dirty-party-electro-house-bass-ibiza-dance-mix-2015-best-melbourne-dutch-progressive: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
$ pip3 install -U --user youtube_dl
Collecting youtube_dl
  Downloading youtube_dl-2017.10.20-py2.py3-none-any.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 237kB/s
Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2017.10.12
    Uninstalling youtube-dl-2017.10.12:
      Successfully uninstalled youtube-dl-2017.10.12
Successfully installed youtube-dl-2017.10.20
$ youtube-dl https://soundcloud.com/iamtr3p/new-dirty-party-electro-house-bass-ibiza-dance-mix-2015-best-melbourne-dutch-progressive
[soundcloud] iamtr3p/new-dirty-party-electro-house-bass-ibiza-dance-mix-2015-best-melbourne-dutch-progressive: Resolving id
[soundcloud] iamtr3p/new-dirty-party-electro-house-bass-ibiza-dance-mix-2015-best-melbourne-dutch-progressive: Downloading info JSON

[soundcloud] 173339373: Downloading track url
[soundcloud] 173339373: Downloading m3u8 information
[soundcloud] 173339373: Downloading m3u8 information
[soundcloud] 173339373: Checking hls_opus_64_url video format URL
[soundcloud] 173339373: Checking http_mp3_128_url video format URL
[soundcloud] 173339373: Checking hls_mp3_128_url video format URL
[download] Destination: New Dirty Party Electro House Bass Ibiza ✪ Dance Mix 2016 ✪ [ FREE DOWNLOAD -_ Click 'Buy' ]-173339373.mp3
[download] 100% of 15.54MiB in 00:01
```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by zylinx** [comment]
zylinx~ $ sudo youtube-dl --version 
2017.10.20
zylinx~ $ sudo pip install youtube-dl -U
Requirement already up-to-date: youtube-dl in /usr/local/lib/python2.7/dist-packages

**Comment by yan12125** [comment]
Please paste the output of ```youtube-dl -v <the URL>```. Sometimes there are multiple youtube-dl installation and an older version might be used.

**Comment by zylinx** [comment]
thanks @yan12125 
you are correct.
The version I get when importing the module is outdated.
`[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.07
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.9
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
`

How do I update it ?

**Comment by yan12125** [comment]
You can first use ```print(youtube_dl)``` to see which module it actually imports and then update it.
