### ISSUE TITLE
Vimeo onDemand Playlist only downloads first video

### ISSUE THREAD

**Issue by 9KuuCqmtebjTD** [rg3/youtube-dl#14591]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.20*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

I cannot get youtube-dl to download the whole playlist in a Vimeo Video on Demand playlist that I rented. It only downloads the first video.

Here's what I try: 
youtube-dl -v \<snip\> https://vimeo.com/ondemand/padeltutorials/219725728?autoplay=1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://vimeo.com/ondemand/padeltutorials/219725728?autoplay=1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.20
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {'http': 'http://127.0.0.1:7769', 'https': 'http://127.0.0.1:7769'}
[vimeo:ondemand] padeltutorials: Downloading webpage
[vimeo] Logging in
[vimeo] 219725728: Downloading webpage
[vimeo] 219725728: Extracting information
[vimeo] 219725260: Downloading webpage
[vimeo] 219725260: Extracting information
[vimeo] 219725260: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 219725260: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 219725260: Downloading fastly_skyfire m3u8 information
[vimeo] 219725260: Downloading akfire_interconnect_quic MPD information
[vimeo] 219725260: Downloading akfire_interconnect_quic MPD information
[vimeo] 219725260: Downloading fastly_skyfire MPD information
[vimeo] 219725260: Downloading fastly_skyfire MPD information
[debug] Default format spec: bestvideo+bestaudio/best
[download] 1- Controlling the speed of the ball-219725260.mp4 has already been downloaded and merged

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by 9KuuCqmtebjTD** [comment]
@dstftw Updated.

**Comment by 9KuuCqmtebjTD** [comment]
Any update on this?

**Comment by early90spants** [comment]
Would be cool to get this working again. I can provide a login to use for testing if necessary.

**Comment by 9KuuCqmtebjTD** [comment]
Will there be a fix for this?

**Comment by afbroman** [comment]
I'm having the same problem. Does anyone know of workarounds? Can I provide further information to help toward a fix?

**Comment by Ramblurr** [comment]
Sent an account to @remitamine
