### ISSUE TITLE
strange behavior with twitch vod

### ISSUE THREAD

**Issue by soredake** [rg3/youtube-dl#14596]
## Please follow the guide below

I can't load anything after 26:29:43 directly, to load i need to go to 26:29:30 and watch manually, 
After 26:29:43 mpv shows this:
```
Invalid audio PTS: 95383.812061 -> -59.905633

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).
AV: 26:29:43 / 32:10:22 (82%) A-V:-95443.651 ct: -0.066 Dropped: 5 Cache:  1s+439KB
Invalid video timestamp: 95383.781989 -> -59.901700
AV: -00:00:59 / 32:10:22 (0%) A-V:  0.026 ct: -0.060 Dropped: 5 Cache:  1s+439KB
Invalid video timestamp: -59.835700 -> 95383.914989
AV: -00:00:59 / 32:10:22 (0%) A-V:-95443.724 ct: -0.060 Dropped: 5 Cache:  1s+439KB
Invalid video timestamp: 95383.914989 -> -59.768700
AV: -00:00:58 / 32:10:22 (0%) A-V: -0.000 ct: -0.101 Dropped: 5 Cache: 100s+439KB
```
and time changes to 00:00:00 (just visually, in fact, it continues to play video after 26:29:43) and i can't rewind (it drops to the time that is shown visually in mpv, to go back you need to do what I described at the beginning)

video url: https://go.twitch.tv/videos/179918229
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.20*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
youtube-dl -v
```
[debug] System config: []
[debug] User config: ['--prefer-free-formats', '--external-downloader', 'aria2c', '--external-downloader-args', '-x 14 -s 6 -m 3']
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.20
[debug] Python version 3.4.5 - Linux-4.12.12-gentoo-x86_64-AMD_Ryzen_7_1800X_Eight-Core_Processor-with-gentoo-2.4.1
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4, rtmpdump 2.4
[debug] Proxy map: {}
```
mpv --version
```
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4
```

**Comment by dstftw** [comment]
Provide youtube-dl verbose log that clearly demonstrates the problem.
