### ISSUE TITLE
Skip already downloaded files

### ISSUE THREAD

**Issue by victornpb** [rg3/youtube-dl#14606]
### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)

---

### Description of your *issue*, suggested solution and other information

Im suggesting a new flag

    --skip-downloaded-videos

I usually download an entire channel from youtube, but then once I download all the videos it's hard to keep the downloaded folder up to date, would be nice if it could like not download everything again if I ran the command again. So I could set up a script to run it on a specified schedule and it would only download new videos.

    youtube-dl https://youtube.com/somechannel

The command could create a `downloaded-urls.txt` containing the list of all downloaded files, so it could just read this file and skip the videos on this list. Or maybe it could recursively read all the `*.json` files in the target folder to determine if the video is already there.

---

My config file
```
--ignore-errors
--no-mark-watched
--geo-bypass

#playlist starts from most recent to oldest
--playlist-reverse

#save description
--write-description
#save all info
--write-info-json
#save thumbnail
--write-thumbnail

#download all subtitles
--all-subs

--no-mtime 

#Encode the video to another format if necessary
--recode-video mp4

#Embed stuff into video
--embed-thumbnail
--embed-subs
--add-metadata

-o "%(uploader)s/%(upload_date)s.%(playlist_index)s.%(uploader)s.%(title)s.%(id)s.%(ext)s" 
```

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#how-do-i-download-only-new-videos-from-a-playlist

**Comment by victornpb** [comment]
Thanks you, and sorry for not noticing this.

**Comment by JonasOlson** [comment]
There is still something that rubs uncomfortably here, though. Under some circumstances (for example `youtube-dl 'https://www.youtube.com/watch?v=BaW_jenozKc'`), the skipping of an already downloaded video just works, with no options, whereas, as demonstrated in this discussion, sometimes you have to decide upon a name for an archive file, use `--download-archive`, and then point to the same archive file the next time. Does it really have to be that way? Could it not work more automatically in all cases?

**Comment by cuppajoeman** [comment]
Here's an idea:

`create_download_list.sh`
```
#!/usr/bin/env bash

for n in *.*
do if [[ "$n" =~ -([-_0-9a-zA-Z]{11}).*$ ]]
   then echo "youtube ${BASH_REMATCH[1]}" 
   fi
done > downloaded.txt
```
Then run `youtube-dl --download-archive downloaded.txt ...`

**Comment by ppamorim** [comment]
@cuppajoeman This is not working on macOS, it is generating a corrupted list.
