### ISSUE TITLE
Unable to download webpage: <urlopen error [Errno 65] No route to host> behind a proxy

### ISSUE THREAD

**Issue by xiaji** [rg3/youtube-dl#14608]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.20*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

###  the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--proxy', u'127.0.0.1:12567', u'https://www.youtube.com/watch?v=M1G4rwnIO48', u'--verbose', u'--call-home']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.20
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {u'http': u'127.0.0.1:XXXX', u'https': u'127.0.0.1:XXXX'}
[debug] Public IP address: 2xx.xx.xx.xx
[youtube] M1G4rwnIO48: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 65] No route to host> (caused by URLError(error(65, 'No route to host'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2195, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1086, in https_open
    req, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
```

---

### Description of your *issue*, suggested solution and other information

It works fine before. but after I updated my proxy software, dl threw this errors. I tried following commands which all did not work:

```
youtube-dl --proxy 127.0.0.1:XXX
youtube-dl --proxy "127.0.0.1:XXX"
youtube-dl --proxy "https://127.0.0.1:XXX"
youtube-dl --proxy "http://127.0.0.1:XXX"

```
Thanks

**Comment by dstftw** [comment]
Obviously your proxy does not work properly.

**Comment by xiaji** [comment]
The proxy works with Youtube in Chrome, just does not work for dl. proxychains4 works with my proxy well, too.
