### ISSUE TITLE
youtube-dl doesn't download "best" resolution

### ISSUE THREAD

**Issue by tehmasterer** [rg3/youtube-dl#14609]
I am using youtube-dl "address" which should download the best video and audio by default. I checked my video with youtube-dl -F "address" but it doesn't match what I downloaded. It should be webm 640x360 vorbis@128k. Instead it's webm 400x270 vorbis@96k. Those settings are identical to the mp4 format download. I am on the latest version of youtube-dl.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
