### ISSUE TITLE
unable to extract html5 player on youtube-dl **2017.10.29**

### ISSUE THREAD

**Issue by Ian-T-Price** [rg3/youtube-dl#14619]
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**
- [X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
itp@CSL-XPS-L702X ~/Videos/Horse_distraction $ youtube-dl --verbose https://youtu.be/RsxjXArvdXU
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://youtu.be/RsxjXArvdXU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.12 - Linux-4.4.0-97-generic-x86_64-with-LinuxMint-18.2-sonya
[debug] exe versions: avconv 3.2.6-1, avprobe 3.2.6-1, ffmpeg 3.2.6-1, ffprobe 3.2.6-1
[debug] Proxy map: {}
[youtube] RsxjXArvdXU: Downloading webpage
[youtube] RsxjXArvdXU: Downloading video info webpage
[youtube] RsxjXArvdXU: Extracting video information
WARNING: unable to extract uploader nickname
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {43} signature length 43.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 797, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'/yts/jsbin/player-vflhIZIgy/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'/yts/jsbin/player-vflhIZIgy/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 797, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'/yts/jsbin/player-vflhIZIgy/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1407, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 915, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 797, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'/yts/jsbin/player-vflhIZIgy/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'/yts/jsbin/player-vflhIZIgy/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by tobijjah** [comment]
You using an old version of youtube-dl `[debug] youtube-dl version 2016.02.22` in the recent version it works as it should. 
This issue should be closed.

**Comment by yan12125** [comment]
Yep. Most likely it's an outdated package from Ubuntu. Hopefully more people can go to https://bugs.launchpad.net/ubuntu/+source/youtube-dl/+bug/1529647 and let the Ubuntu team know they shouldn't ship outdated youtube-dl packages.

**Comment by Ian-T-Price** [comment]
Er.... in that case ( and I do see the line in the --verbose report now ) I'd like to add to the bug report the fact that update does not work!  When I had first had the error the first thing I did was to check versions and upgrade. See output below.

Knowing python, there's probably six different site-packages and the update is installed in the wrong one.  I'll get back to you.

itp@CSL-XPS-L702X ~/Videos/Horse_distraction $ sudo pip install -U youtube-dl
[sudo] password for itp:                                                                                                                                                                                                                           
Collecting youtube-dl
  Downloading youtube_dl-2017.10.29.tar.gz (1.3MB)
    100% |████████████████████████████████| 1.3MB 725kB/s 
Installing collected packages: youtube-dl
  Running setup.py install for youtube-dl ... done
Successfully installed youtube-dl-2017.10.29

**Comment by Ian-T-Price** [comment]
And yes, wrong version being picked up.  /usr/bin/youtube-dl was first in the path but `sudo pip install -U youtube-dl` installed to /usr/local/bin/youtube-dl  Strange that sudo installs to /usr/local

version 2017-10-29 does indeed work.

Thank you very much for your sterling work on this project and the rapid response to my issue.
And my sincerest apologies for troubling you with a non issue.
Many Thanks, Ian
Issue closed
