### ISSUE TITLE
Youtube-dl keeps freezing up mid-download... 

### ISSUE THREAD

**Issue by kenny-wettlaufer** [rg3/youtube-dl#14613]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.20*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

It keeps freezing on me mid-download, itll unfreeze, climb another 10% or so then freeze back up again... This is new.. I've never had any problems with youtube-dl ever. 
It would also be really nice if you guys started supporting crtv.com ...
I am still encountering this problem even with building youtube-dl straight from github, I figured if I compiled it from source that maybe the bug would go away but its not going away..

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by kenny-wettlaufer** [comment]
well I'm not really sure how to fill out the rest of it so I gave you what I could.

**Comment by kenny-wettlaufer** [comment]
I'll just go back to an earlier version I guess then, whatever...
