### ISSUE TITLE
[Tou.tv] Unable to extract access token

### ISSUE THREAD

**Issue by MonsieurClavet** [rg3/youtube-dl#14614]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.20*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://ici.tou.tv/comediha/S03E07', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.20
[debug] Python version 3.5.2 - Linux-4.4.0-92-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.4-1, ffprobe 3.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[tou.tv] Downloading homepage
[tou.tv] Downloading login page
[tou.tv] Logging in
ERROR: Unable to extract access token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 433, in extract
    self.initialize()
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 391, in initialize
    self._real_initialize()
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/toutv.py", line 69, in _real_initialize
    urlh.geturl(), 'access token')
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 797, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract access token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

### Description of your *issue*, suggested solution and other information
The authentication seems to have stop working recently as we are still able to use youtube-dl for regular videos, however whenever we try to authenticate with credentials, it keeps saying that he's unabel to extract access token

**Comment by MonsieurClavet** [comment]
FYI - version 2017.10.29 does the same

**Comment by MonsieurClavet** [comment]
i can share account if needed

**Comment by m-p-3** [comment]
I can provide an account if necessary, just point me towards a way of doing so privately.

**Comment by remitamine** [comment]
i already added support for auth in 98b7506e96b5ac107a777d8bb8900623d832fba4.
you can contact me using the email in [my GitHub profile](https://github.com/remitamine) to check what has been changed and if it can be fixed.

**Comment by m-p-3** [comment]
I think the authentication system changed, because when I try to initiate a download with authentication, it output this

```
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.11.06
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg 3.3.3
[debug] Proxy map: {}
[tou.tv] Downloading homepage
[tou.tv] Downloading login page
[tou.tv] Logging in
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\extractor\common.py", line 506, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\YoutubeDL.py", line 2195, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

**Comment by Nutcais** [comment]
Getting the same issue in 2017.12.02
