### ISSUE TITLE
"--list-subs" messing with "--get" statements?

### ISSUE THREAD

**Issue by Albretch** [rg3/youtube-dl#14621]
Try this youtube-dl one liner with and without "--list-subs"

_YT="1nG3GRb4vC4"
_YT="PLEtR4Vu4eCRayeQaNlYbAtOrGPYMH4FDp"
_LOG_FL="${_YT}_$(date +%Y%m%d%H%M%S).log"
time python youtube-dl --simulate --yes-playlist --ignore-errors --newline --no-progress --no-call-home --merge-output-format bestvideo+bestaudio  --get-id --get-title --get-duration  --get-format --list-subs "${_YT}" > "${_LOG_FL}" 2>&1
cat "${_LOG_FL}"
ls -l "${_LOG_FL}"
wc -l "${_LOG_FL}"

when you try include the information about the subtitles all other "--get"s are apparently purged from the output.

All you read in the documentation heal is: --list-subs  List all available subtitles for the video

Why is this happening? How could include all substitles available for a video as a comma separated list (same as --sub-lang LANGS)?

lbrtchx

**Comment by dstftw** [comment]
This is expected. Any `--list-*` option will only list. Parse JSON output.
