### ISSUE TITLE
Cannot download from telequebec.tv

### ISSUE THREAD

**Issue by twomby** [rg3/youtube-dl#14649]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**

- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections

- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
C:\WINDOWS\system32>youtube-dl -v http://lindicemcsween.telequebec.tv/emissions/100430013/des-soins-esthetiques-a-377-d-interets-annuels-ca-vous-tente
[debug] System config: []
[debug] User config: ['-x', '-o', 'D:/Downloads/Encode/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://lindicemcsween.telequebec.tv/emissions/100430013/des-soins-esthetiques-a-377-d-interets-annuels-ca-vous-tente']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-87353-g183fd30, ffprobe N-87353-g183fd30, rtmpdump 2.3
[debug] Proxy map: {}
[generic] des-soins-esthetiques-a-377-d-interets-annuels-ca-vous-tente: Requesting header
WARNING: Could not send HEAD request to http://lindicemcsween.telequebec.tv/emissions/100430013/des-soins-esthetiques-a-377-d-interets-annuels-ca-vous-tente: HTTP Error 404: Not Found
[generic] des-soins-esthetiques-a-377-d-interets-annuels-ca-vous-tente: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] des-soins-esthetiques-a-377-d-interets-annuels-ca-vous-tente: Extracting information
ERROR: Unsupported URL: http://lindicemcsween.telequebec.tv/emissions/100430013/des-soins-esthetiques-a-377-d-interets-annuels-ca-vous-tente
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\generic.py", line 3059, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://lindicemcsween.telequebec.tv/emissions/100430013/des-soins-esthetiques-a-377-d-interets-annuels-ca-vous-tente
```
---

### Description of your *issue*, suggested solution and other information

Although TeleQuebec is listed as supported in the list of supported sites, I can't download anything from the site. Not sure if the site structure/architecture has changed and it might be the cause. Really wish I could download some streams of really good public affairs programs. I would be grateful for any help on this matter. Thank you!

**Comment by Albert9999** [comment]
The only way to download via Telequebec at the moment is thru their **Zone Video** section, here's the link to your requested video, hope this helps until they add a new extractor...cheers.

http://zonevideo.telequebec.tv/media/35056/des-soins-esthetiques-a-377-d-interets-annuels-ca-vous-tente/l-indice-mcsween

**Comment by twomby** [comment]
Hi Albert! Merci beaucoup!! Really appreciate your help on this issue! This is good enough for me!! I'll download everything from zonevideo from now on and no issues :)  Cheers!
