### ISSUE TITLE
help with downloads stopping

### ISSUE THREAD

**Issue by rellik31** [rg3/youtube-dl#14657]
hello, when downloading from fox.com i get this error with every video 

download]  15.3% of ~322.19MiB at 466.08KiB/s ETA 04:43        
ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

if i put the link in again it will resume from the % it was it when i get the error but it happens about 6 times on one download so i need to be at my laptop checking its not stopped
is there a way to fix this? or a command so youtube dl will resume the download with out me needing to input the url again?

thank you

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by rellik31** [comment]
hello, i have given the full error message and use youtube-dl 29th oct 2017
other sites work fine its just fox.com with the issue/error
