### ISSUE TITLE
how to download youtube video use xx-net cross gfw

### ISSUE THREAD

**Issue by Token713** [rg3/youtube-dl#14651]
之前youtube-dl是可以通过xx-net下载视频的，现在怎么不行了，语法变了吗？

2017.10.29

>youtube-dl --proxy 127.0.0.1:8087 https://www.youtube.com/watch?v=JmvCpR45LKA -
v --no-check-certificate
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', '127.0.0.1:8087', 'https://www.youtube.co
m/watch?v=JmvCpR45LKA', '-v', '--no-check-certificate']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-79068-g6b7ce0e, ffprobe N-79068-g6b7ce0e, rtmpdum
p 2.4
[debug] Proxy map: {'http': '127.0.0.1:8087', 'https': '127.0.0.1:8087'}
[youtube] JmvCpR45LKA: Downloading webpage
[youtube] JmvCpR45LKA: Downloading video info webpage
ERROR: JmvCpR45LKA: "token" parameter not in video info for unknown reason; plea
se report this issue on https://yt-dl.org/bug . Make sure you are using the late
st version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
--verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\bu
ild\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\bu
ild\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\bu
ild\youtube_dl\extractor\youtube.py", line 1613, in _real_extract
youtube_dl.utils.ExtractorError: JmvCpR45LKA: "token" parameter not in video inf
o for unknown reason; please report this issue on https://yt-dl.org/bug . Make s
ure you are using the latest version; type  youtube-dl -U  to update. Be sure to
 call youtube-dl with the --verbose flag and include its complete output.

>

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/pull/13743#issuecomment-318155798
