### ISSUE TITLE
youtube-dl 如何通过xx-net下载youtube视频

### ISSUE THREAD

**Issue by Token713** [rg3/youtube-dl#14650]
软件一直在更新，教程却没来得及更新。。。
之前一直用youtube-dl通过xx-net来下载youtube视频，现在却下不了了。
youtube-dl --proxy 127.0.0.1:8087 https://www.youtube.com/watch?v=S5Tp9_77D4w
或者
youtube-dl --proxy 127.0.0.1:8087 https://www.youtube.com/watch?v=JmvCpR45LKA -v --no-check-certificate
都不能下载了，是语法不对吗，求教。

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
