### ISSUE TITLE
Openload File not found error

### ISSUE THREAD

**Issue by cacdpa** [rg3/youtube-dl#14665]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**

### Before submitting an *issue* make sure you have:
- [ X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```youtube-dl https://openload.co/f/e-Ixz9ZR5L0/```

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://openload.co/f/e-Ixz9ZR5L0/', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.29
[debug] Python version 2.7.10
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4, phantomjs 2.1.1
[debug] Proxy map: {}
[Openload] e-Ixz9ZR5L0: Downloading webpage
ERROR: e-Ixz9ZR5L0: File not found
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "outube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/openload.py", line 309, in _real_extract
    raise ExtractorError('File not found', expected=True, video_id=video_id)
ExtractorError: e-Ixz9ZR5L0: File not found
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by yan12125** [comment]
This looks like a copyrighted video. Any other examples?

**Comment by cacdpa** [comment]
@yan12125 fixed

**Comment by zachee** [comment]
This seems to be an issue with openload itself as the embedded link seems to be dead even though the file link is alive.

ex:
You linked: https://openload.co/f/e-Ixz9ZR5L0/ which is very much live and I can see the video on it
The extractor is attempting to pull the video with the embed link of: https://openload.co/embed/e-Ixz9ZR5L0/ which for some reason is saying the file is removed

I'll work on a patch for openload extractor to try both links as extracting with the openload.co/f/ link works I just need to make sure it doesn't introduce any unexpected bugs.

**Comment by cacdpa** [comment]
@zachee Thank you for the patch!!
