### ISSUE TITLE
cannot download playlist

### ISSUE THREAD

**Issue by kokomij** [rg3/youtube-dl#14663]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
youtube-dl -v --ignore-config https://www.youtube.com/playlistlist=PLWUeC03YLcaIoUNa7B-5DlJzL9jIc5hRZ --------playlist-start 50
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', 'https://www.youtube.com/playlist?list=PLWUeC03YLcaIoUNa7B-5DlJzL9jIc5hRZ', '--playlist-start', '50']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.6.3 - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg N-88514-gd5995c531d, ffprobe N-88514-gd5995c531d
[debug] Proxy map: {'http': 'http://127.0.0.1:1080', 'https': 'https://127.0.0.1:1080', 'ftp': 'ftp://127.0.0.1:1080'}
[youtube:playlist] PLWUeC03YLcaIoUNa7B-5DlJzL9jIc5hRZ: Downloading webpage
[download] Downloading playlist: 걸스데이 2016+
[youtube:playlist] PLWUeC03YLcaIoUNa7B-5DlJzL9jIc5hRZ: Downloading page #1
ERROR: Unable to download JSON metadata: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。> (caused by URLError(ConnectionRefusedErro
r(10061, '由于目标计算机积极拒绝，无法连接。', None, 10061, None),))
  File "c:\users\kokomij\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\extractor\common.py", line 503, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\kokomij\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 2195, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\kokomij\appdata\local\continuum\miniconda3\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\users\kokomij\appdata\local\continuum\miniconda3\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "c:\users\kokomij\appdata\local\continuum\miniconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\kokomij\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\utils.py", line 1086, in https_open
    req, **kwargs)
  File "c:\users\kokomij\appdata\local\continuum\miniconda3\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)

---

can downloda one video
cannot download playlist

**Comment by dstftw** [comment]
Most likely your proxy is broken.

**Comment by kokomij** [comment]
but i can download any video
