### ISSUE TITLE
Site Support --get-duration Tag (Reoppened)

### ISSUE THREAD

**Issue by DanielnetoDotCom** [rg3/youtube-dl#14664]
Hi I have opened this before https://github.com/rg3/youtube-dl/issues/14661

But an collaborator has close this issue and I found no way to reopen it.

He already tell me my site is not explicitly supported and extraction is delegated to generic extractor that may or may not succeed. You can mask your data behind any pattern generic extractor supports to make it succeed (see the extractor/generic.py).

https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/generic.py

I have looked into the file above and I have not found hot to make YouPHPTube youtube-dl suported?
Should I add some tag information? or change the youtube-dl code?
BTW, the issue is about the duration, title and thumbs works fine

Thanks

**Comment by dstftw** [comment]
Again: this depends on a particular site and how this site embeds videos. Generic extractor only sequentially tries known patterns and uses one that is matched (again, see the code for these patterns). If such pattern supports duration extraction and it's properly provided by a site, it will be extracted then.
