### ISSUE TITLE
cannot download from udemy

### ISSUE THREAD

**Issue by shanejms2** [rg3/youtube-dl#14675]
The following error comes when i try to download a purchased course from udemy. I t was working a week ago.

ERROR: Unable to download webpage: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
