### ISSUE TITLE
Cannot start Youtube-DL

### ISSUE THREAD

**Issue by SirSlender** [rg3/youtube-dl#14678]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I download Youtube-DL through NadekoBot Updater, It tells me I get this error: http://prntscr.com/h6l5fd
I've followed the instructions to install it manually as well to no avail and the bot developers have no idea what's wrong. This is on Windows Server 2012. There was a previously seemingly similar issue reported in the past but no resolution on how it was solved. (Yes, I have the dependencies downloaded)

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#the-exe-throws-an-error-due-to-missing-msvcr100dll

**Comment by SirSlender** [comment]
I just said in my description that the redist is installed, MSVCR100 is not missing.

**Comment by SirSlender** [comment]
http://prntscr.com/h6q844

**Comment by SirSlender** [comment]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	youtube-dl.exe
  Application Version:	2017.10.29.0
  Application Timestamp:	54467a4f
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.3.9600.18696
  Fault Module Timestamp:	5915ecd6
  Exception Code:	c000007b
  Exception Offset:	0009d4c2
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	1abe
  Additional Information 2:	1abee00edb3fc1158f9ad6f44f0f6be8
  Additional Information 3:	1abe
  Additional Information 4:	1abee00edb3fc1158f9ad6f44f0f6be8

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
