### ISSUE TITLE
Undownloadable video from tudou/youku (error -6001)

### ISSUE THREAD

**Issue by PorscheMonty** [rg3/youtube-dl#14679]
Hello there. I'm having trouble downloading a certain video from tudou/youku, but I cannot post the actual link because it's a private video  (no usable title that would show up in a search but not technically set to private mode either) I've not been given explicit permission to share.

For what it's worth, the logs:

C:\youtube-dl>youtube-dl http://video.tudou.com/v/15RandomLetters==.html --no-check-certificate --verbose                                                                                                     
[debug] System config: []                                                                                                                                                                               
[debug] User config: []                                                                                                                                                                                 
[debug] Custom config: []                                                                                                                                                                               
[debug] Command-line args: ['http://video.tudou.com/v/15RandomLetters==.html', '--no-check-certificate', '--verbose']                                                                                   
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252                                                                                                                                       
[debug] youtube-dl version 2017.10.29                                                                                                                                                                   
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3                                                                                                                                                  
[debug] exe versions: none                                                                                                                                                                              
[debug] Proxy map: {}                                                                                                                                                                                   
[youku] 15RandomLetters: Retrieving cna info                                                                                                                                                            
[youku] 15RandomLetters: Downloading JSON metadata                                                                                                                                                      
ERROR: Youku server reported error -6001: ccode????; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                                                                                                                                        
Traceback (most recent call last):                                                                                                                                                                      
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 784, in extract_info                                                                 
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 434, in extract                                                               
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\youku.py", line 189, in _real_extract                                                          
youtube_dl.utils.ExtractorError: Youku server reported error -6001: ccode????; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 

****
Thanks for your time and sorry for the inconveniences.

**Comment by dstftw** [comment]
You must provide reproducible example URL. There is no other way.
