### ISSUE TITLE
BBC website, f4m file, download fails

### ISSUE THREAD

**Issue by johnthecracker** [rg3/youtube-dl#14684]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

BBC website, pre-recorded video, f4m file, download fails.
---

```


C:\>youtube-dl.exe -v -F --no-check-certificate "http://vod-hds-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/21a452-p051skl0/vf_p051skl0_0bd66164-b23d-4a18-a305-75be57e4e8de.ism/pc_hd_abr_v2_hds_master.f4m?s=1509935821&e=1509979021&h=343a818cbf79a3218a3cc8b86a530f97"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', '--no-check-certificate', 'http://vod-hds-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/21a452-p051skl0/vf_p051skl0_0bd66164-b23d-4a18-a305-75be57e4e8de.ism/pc_hd_abr_v2_hds_master.f4m?s=1509935821&e=1509979021&h=343a818cbf79a3218a3cc8b86a530f97']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg n3.2.1, ffprobe N-87353-g183fd30, rtmpdump 2.4
[debug] Proxy map: {}
[generic] pc_hd_abr_v2_hds_master: Requesting header
WARNING: Falling back on generic information extractor.
[generic] pc_hd_abr_v2_hds_master: Downloading webpage
[generic] pc_hd_abr_v2_hds_master: Extracting information
ERROR: Unsupported URL: http://vod-hds-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/21a452-p051skl0/vf_p051skl0_0bd66164-b23d-4a18-a305-75be57e4e8de.ism/pc_hd_abr_v2_hds_master.f4m?s=1509935821&e=1509979021&h=343a818cbf79a3218a3cc8b86a530f97
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\generic.py", line 3059, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://vod-hds-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/21a452-p051skl0/vf_p051skl0_0bd66164-b23d-4a18-a305-75be57e4e8de.ism/pc_hd_abr_v2_hds_master.f4m?s=1509935821&e=1509979021&h=343a818cbf79a3218a3cc8b86a530f97


...
<end of log>
```

---

The heroin-ravaged city fighting back

http://www.bbc.co.uk/news/world-us-canada-41826022
---

Download of pre-recorded video file fails.

**Comment by dstftw** [comment]
You must use original http://www.bbc.co.uk/news/world-us-canada-41826022 URL.
