### ISSUE TITLE
you

### ISSUE THREAD

**Issue by geirman** [rg3/youtube-dl#14680]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl --verbose -o %(autonumber)s-%(title)s.%(ext)s https://egghead.io/courses/build-a-desktop-application-with-electron
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-o', u'%(autonumber)s-%(title)s.%(ext)s', u'https://egghead.io/courses/build-a-desktop-application-with-electron']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.29
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[egghead:course] build-a-desktop-application-with-electron: Downloading course lessons JSON
[egghead:course] build-a-desktop-application-with-electron: Downloading course JSON
[download] Downloading playlist: Build a desktop application with Electron
[egghead:course] playlist Build a desktop application with Electron: Collected 14 video ids (downloading 14 of them)
[download] Downloading video 1 of 14
[egghead:lesson] javascript-create-a-hello-world-app-using-electron: Downloading JSON metadata
[egghead:lesson] 1925: Downloading m3u8 information
[egghead:lesson] 1925: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://d2c5owlt6rorc3.cloudfront.net/javascript-create-a-hello-world-app-using-electron-76ba7cb79f/'
[dashsegments] Total fragments: 36
[download] Destination: 00001-Create a 'Hello World' app using Electron.fdash-aa30637c-5cb5-4e61-9eb1-a4bb6d723dd5.mp4
[download] 100% of 7.11MiB in 00:21
[debug] Invoking downloader on u'https://d2c5owlt6rorc3.cloudfront.net/javascript-create-a-hello-world-app-using-electron-76ba7cb79f/'
[dashsegments] Total fragments: 36
[download] Destination: 00001-Create a 'Hello World' app using Electron.fdash-9255730b-9d1f-4b34-adeb-f2be69d71146.m4a
[download] 100% of 2.10MiB in 00:14
[ffmpeg] Merging formats into "00001-Create a 'Hello World' app using Electron.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:00001-Create a '"'"'Hello World'"'"' app using Electron.fdash-aa30637c-5cb5-4e61-9eb1-a4bb6d723dd5.mp4' -i 'file:00001-Create a '"'"'Hello World'"'"' app using Electron.fdash-9255730b-9d1f-4b34-adeb-f2be69d71146.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:00001-Create a '"'"'Hello World'"'"' app using Electron.temp.mp4'
Deleting original file 00001-Create a 'Hello World' app using Electron.fdash-aa30637c-5cb5-4e61-9eb1-a4bb6d723dd5.mp4 (pass -k to keep)
Deleting original file 00001-Create a 'Hello World' app using Electron.fdash-9255730b-9d1f-4b34-adeb-f2be69d71146.m4a (pass -k to keep)
[download] Downloading video 2 of 14
[egghead:lesson] javascript-load-css-in-a-electron-browserwindow: Downloading JSON metadata
[egghead:lesson] 2117: Downloading m3u8 information
[egghead:lesson] 2117: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://d2c5owlt6rorc3.cloudfront.net/javascript-load-css-in-a-electron-browserwindow-85fefdfe6c/'
[dashsegments] Total fragments: 36
[download] Destination: 00002-Load CSS in a Electron BrowserWindow.fdash-18a95fa8-ee80-4239-919f-362cc142554e.mp4
[download] 100% of 5.93MiB in 00:19
[debug] Invoking downloader on u'https://d2c5owlt6rorc3.cloudfront.net/javascript-load-css-in-a-electron-browserwindow-85fefdfe6c/'
[dashsegments] Total fragments: 36
[download] Destination: 00002-Load CSS in a Electron BrowserWindow.fdash-eb49ca94-d2bf-4434-9666-4fc0ef926e90.m4a
[download] 100% of 2.10MiB in 00:14
[ffmpeg] Merging formats into "00002-Load CSS in a Electron BrowserWindow.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:00002-Load CSS in a Electron BrowserWindow.fdash-18a95fa8-ee80-4239-919f-362cc142554e.mp4' -i 'file:00002-Load CSS in a Electron BrowserWindow.fdash-eb49ca94-d2bf-4434-9666-4fc0ef926e90.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:00002-Load CSS in a Electron BrowserWindow.temp.mp4'
Deleting original file 00002-Load CSS in a Electron BrowserWindow.fdash-18a95fa8-ee80-4239-919f-362cc142554e.mp4 (pass -k to keep)
Deleting original file 00002-Load CSS in a Electron BrowserWindow.fdash-eb49ca94-d2bf-4434-9666-4fc0ef926e90.m4a (pass -k to keep)
[download] Downloading video 3 of 14
[egghead:lesson] javascript-load-javascript-in-an-electron-browserwindow: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'media_urls',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/egghead.py", line 97, in _real_extract
    for _, format_url in lesson['media_urls'].items():
KeyError: u'media_urls'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 447, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'media_urls',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

the first two videos of the list download fine, but it chokes on the third everytime in the same way

**Comment by dstftw** [comment]
The rest of the videos are only available for subscribers. You may use `-i` to skip such videos.

**Comment by geirman** [comment]
thanks @dstftw, passing `-i` skips all remaining videos. Shouldn't I be able to authenticate passing the `-u` and `-p` flags? That didn't seem to work.

**Comment by dstftw** [comment]
That's not yet supported. Nobody of collaborators has an account.

**Comment by ngthduy90** [comment]
If I provide a pro account, could you fix it? If yes, please email me: ngthduy90@gmail.com
