### ISSUE TITLE
Youtube-DL will not start, Dependencies installed, 0x07cb error.

### ISSUE THREAD

**Issue by SirSlender** [rg3/youtube-dl#14683]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I download Youtube-DL through NadekoBot Updater, It tells me I get this error: http://prntscr.com/h6l5fd
I've followed the instructions to install it manually as well to no avail and the bot developers have no idea what's wrong. This is on Windows Server 2012. There was a previously seemingly similar issue reported in the past but no resolution on how it was solved. (Yes, I have the dependencies downloaded)

MSVCR100.DLL IS NOT MISSING!
http://prntscr.com/h6q844

Problem signature:
Problem Event Name:	APPCRASH
Application Name:	youtube-dl.exe
Application Version:	2017.10.29.0
Application Timestamp:	54467a4f
Fault Module Name:	ntdll.dll
Fault Module Version:	6.3.9600.18696
Fault Module Timestamp:	5915ecd6
Exception Code:	c000007b
Exception Offset:	0009d4c2
OS Version:	6.3.9600.2.0.0.272.7
Locale ID:	1033
Additional Information 1:	1abe
Additional Information 2:	1abee00edb3fc1158f9ad6f44f0f6be8
Additional Information 3:	1abe
Additional Information 4:	1abee00edb3fc1158f9ad6f44f0f6be8

Read our privacy statement online:
http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
C:\Windows\system32\en-US\erofflps.txt

**Comment by dstftw** [comment]
Prove with screenshot from installed apps.
Post the output of `youtube-dl -v`.
Post the output of `where youtube-dl`.

**Comment by SirSlender** [comment]
http://prntscr.com/h6qdt5
http://prntscr.com/h6qdy1

**Comment by dstftw** [comment]
>Prove with screenshot from installed apps.

Post the output of `CertUtil -hashfile path\to\youtube-dl.exe MD5`.
Copy `C:\Windows\SysWOW64\msvcr100.dll` near `youtube-dl.exe`.

**Comment by SirSlender** [comment]
http://prntscr.com/h73lan
Copying the DLL to the folder did nothing.

**Comment by Hrxn** [comment]
> I download Youtube-DL through NadekoBot Updater [..]

But you tried the official binary as well, yes?

**Comment by SirSlender** [comment]
Yes and it still gives the same error :/

**Comment by rsola** [comment]
Hi. Just another Windows user here who accidentally stumbled upon this discussion.

As Youtube-dl.exe is a 32-bit executable and you are running 64-bit Windows (x64), most accesses to System32 are redirected to SysWOW64, so the EXE tries to pick Msvcr100.dll from \Windows\SysWOW64 unless it is found elsewhere. The System32 directory should have 64-bit files only, while 32-bit files must reside in SysWOW64. This is likely not the case. Error 0xc000007b usually occurs when a 32-bit EXE is forced to load a 64-bit DLL or the other way round.

Please delete Msvcr100.dll from \Windows\SysWOW64 and every other place you might have copied it on. Then install **Vcredist_x86.exe** from the [latest official Visual C++ 2010 redistributable package available](http://www.microsoft.com/en-us/download/details.aspx?id=26999).

**Comment by SirSlender** [comment]
You're awesome rsola, I didn't even think of that and I'm an IT graduate xD I never thought to check the executable for whether it was running 32 or 64. Thanks a million <3

**Comment by federxs** [comment]
> Hi. Just another Windows user here who accidentally stumbled upon this discussion.
> 
> As Youtube-dl.exe is a 32-bit executable and you are running 64-bit Windows (x64), most accesses to System32 are redirected to SysWOW64, so the EXE tries to pick Msvcr100.dll from \Windows\SysWOW64 unless it is found elsewhere. The System32 directory should have 64-bit files only, while 32-bit files must reside in SysWOW64. This is likely not the case. Error 0xc000007b usually occurs when a 32-bit EXE is forced to load a 64-bit DLL or the other way round.
> 
> Please delete Msvcr100.dll from \Windows\SysWOW64 and every other place you might have copied it on. Then install **Vcredist_x86.exe** from the [latest official Visual C++ 2010 redistributable package available](http://www.microsoft.com/en-us/download/details.aspx?id=26999).

¡Thanks, it worked for me! I'm running W10 x64 bits, and I had the "application was unable to start correctly.." error.
This solved it.
