### ISSUE TITLE
[CB] youtube-dl cannot record HLS streams with recent versions of ffmpeg...

### ISSUE THREAD

**Issue by dustycy** [rg3/youtube-dl#14695]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.06**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

C:\Users\LAK\Downloads\youtubeDL>youtube_dl -v --hls-prefer-native https://chaturbate.com/sassy3va/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--hls-prefer-native', 'https://chaturbate.com/sassy3va/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.11.06
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-88555-g6ea7711532, ffprobe N-88555-g6ea7711532
[debug] Proxy map: {}
[Chaturbate] sassy3va: Downloading webpage
[Chaturbate] sassy3va: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://edge74.stream.highwebmedia.com/live-edge/amlst:sassy3va-sd-805c93eeb6934870b52b0a1ca12467953d2dc0b77233f3b10bfbf89d003a010e_trns_h264/chunklist_w670734529_b1896000.m3u8?rp=9078318404d1819d4e0e22f0837b8a3767dffea66806d4583dae4ba068cffd7e&amp;u=AnonymousUser&amp;t=%7B%22username%22%3A%22%22%2C%22org%22%3A%22PHX%22%2C%22expire%22%3A1510054705%2C%22sig%22%3A%225fa12a9712261647822d9a6386cc4ecbc8295e717264deeda29ae221707c878f%22%2C%22room%22%3A%22sassy3va%22%7D'
[download] Destination: sassy3va 2017-11-07 13_37-sassy3va.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept-Language: en-us,en;q=0.5
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
Accept-Encoding: gzip, deflate
" -i "https://edge74.stream.highwebmedia.com/live-edge/amlst:sassy3va-sd-805c93eeb6934870b52b0a1ca12467953d2dc0b77233f3b10bfbf89d003a010e_trns_h264/chunklist_w670734529_b1896000.m3u8?rp=9078318404d1819d4e0e22f0837b8a3767dffea66806d4583dae4ba068cffd7e&amp;u=AnonymousUser&amp;t=%7B%22username%22%3A%22%22%2C%22org%22%3A%22PHX%22%2C%22expire%22%3A1510054705%2C%22sig%22%3A%225fa12a9712261647822d9a6386cc4ecbc8295e717264deeda29ae221707c878f%22%2C%22room%22%3A%22sassy3va%22%7D" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:sassy3va 2017-11-07 13_37-sassy3va.mp4.part"
ffmpeg version N-88555-g6ea7711532 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      56.  0.100 / 56.  0.100
  libavcodec     58.  1.100 / 58.  1.100
  libavformat    58.  0.102 / 58.  0.102
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  0.101 /  7.  0.101
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I occasionally use youtube-dl to record chaturbate live streams and have noticed that it cannot record HLS streams with recent versions of ffmpeg. It hangs up and I am forced to hard exit the program:

Received > 3 system signals, hard exiting
[ffmpeg] Interrupted by user
ERROR: unable to download video data: [WinError 2] The system cannot find the file specified: 'sassy3va 2017-11-07 13_37-sassy3va.mp4.part'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\YoutubeDL.py", line 1892, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\YoutubeDL.py", line 1831, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\downloader\external.py", line 44, in real_download
  File "C:\Python\Python34\lib\genericpath.py", line 50, in getsize
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'sassy3va 2017-11-07 13_37-sassy3va.mp4.part'

I can record HLS streams using the latest stable ffmpeg version 3.4. Is this an youtube-dl issue or should it be resolved by ffmpeg people?

**Comment by dstftw** [comment]
>Received > 3 system signals, hard exiting

is most likely a reason.
