### ISSUE TITLE
fox downloading error 403

### ISSUE THREAD

**Issue by harlanb** [rg3/youtube-dl#14698]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.06**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://www.fox.com/watch/fd6969c13c5e0ccaa7fe7c84fc10c780/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.fox.com/watch/fd6969c13c5e0ccaa7fe7c84fc10c780/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.06
[debug] Python version 2.7.12 - Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg N-87326-g3ffd3b7, ffprobe N-87326-g3ffd3b7
[debug] Proxy map: {}
[FOX] fd6969c13c5e0ccaa7fe7c84fc10c780: Downloading JSON metadata
[FOX] fd6969c13c5e0ccaa7fe7c84fc10c780: Downloading webpage
[uplynk:preplay] c0d612b9b20d40b980cf737a0d078aec: Downloading JSON metadata
[uplynk:preplay] c0d612b9b20d40b980cf737a0d078aec: Downloading m3u8 information
[uplynk:preplay] c0d612b9b20d40b980cf737a0d078aec: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://content-ause4.uplynk.com/c0d612b9b20d40b980cf737a0d078aec/k.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 647
[download] Destination: Into the Fold-c0d612b9b20d40b980cf737a0d078aec.mp4
[download]   0.2% of ~1.67GiB at 11.61MiB/s ETA 03:02ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1892, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1831, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 166, in real_download
    decrypt_info['KEY'] = decrypt_info.get('KEY') or self.ydl.urlopen(decrypt_info['URI']).read()
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2195, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
---

**Comment by harlanb** [comment]
Still failing update:
$ sudo youtube-dl -U
[sudo] password for <user>: 
youtube-dl is up-to-date (2017.11.15)

I noticed that other people are also having issues with Fox shows.

**Comment by rellik31** [comment]
i still have the same issue
the versions from october DID NOT have any issue downloading
from fox but it also downloads the adds
