### ISSUE TITLE
How to write tests where login is required

### ISSUE THREAD

**Issue by madmatt** [rg3/youtube-dl#14691]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.06**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

I am creating a new extractor, but it's a service that requires a login to view any content (logins cost money and are for a limited amount of time, if that matters). The site itself is open and the link to the M3U8 file is visible to non-logged-in users, but in order to download the M3U8 file you need to login and provide an HMAC string and/or cookie value. I'm writing the login code now, but I'm wondering if it's possible for me to still write tests for this extractor? I'm following the `YoutubeIE` example, but that doesn't have any tests for the extractors that require login (`YoutubeFeedsInfoExtractor` and `YoutubeFavouritesIE` for example).

Obviously it can't test the downloaded file, but passing `skip_download` param through doesn't stop `_extract_m3u8_formats` from attempting to retrieve the m3u8 file and failing.

**Comment by dstftw** [comment]
Specify any params you need in `params`:
https://github.com/rg3/youtube-dl/blob/ec85ded83cbfa652ba94cb080aab52d8b270212a/youtube_dl/extractor/fc2.py#L38-L41
