### ISSUE TITLE
Unable to download embedded Vimeo video on webpage.

### ISSUE THREAD

**Issue by victorhooi** [rg3/youtube-dl#14706]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

I'm attempting to download an embedded Vimeo video on a webpage. The webpage is behind a username/password.

I was able to use https://github.com/eMBee/vimeo-download to download the video successfully, by checking for the master.json file associatd with the video (using Chrome DevTools), and passing that to `vimeo-download.py`.

However, attempting to pass this master.json file to youtube-dl did not work - it simply saves the master.json file to disk.

Is there some way to have youtube-dl take a master.json file as input? Or some other way of having it parse a webpage behind a username/password?

**Comment by Hrxn** [comment]
Well, depends on the contents of `master.json`, I guess?

Can you post it?

**Comment by victorhooi** [comment]
Of course - this is the master.json that youtube-dl downloaded:

https://gist.github.com/victorhooi/fa8f19894371941d82b14004ad0e5385

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by victorhooi** [comment]
Apologies if I missed something.

However, I suspect this is possibly a FR - which is what I was hoping to clarify with the youtube-dl team.

Was Vimeo embedded functionality ever working?

If it's the CLI output, I'm happy to attach that?
```
victorhooi@victorhooi-macbookpro ~> youtube-dl -v "https://skyfire.vimeocdn.com/1510209351-0xd04ae734a02180093c3ae293504c3082f8c5cb71/165035744/sep/video/524508004/master.json?base64_init=1"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://skyfire.vimeocdn.com/1510209351-0xd04ae734a02180093c3ae293504c3082f8c5cb71/165035744/sep/video/524508004/master.json?base64_init=1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.06
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[generic] master: Requesting header
WARNING: Falling back on generic information extractor.
[generic] master: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1510209351-0xd04ae734a02180093c3ae293504c3082f8c5cb71/165035744/sep/video/524508004/master.json?base64_init=1'
[download] Destination: master-master.json
[download] 100% of 62.53KiB in 00:00
```

Let me know if you need additional information.

**Comment by remitamine** [comment]
> I'm attempting to download an embedded Vimeo video on a webpage. The webpage is behind a username/password.

i will refer to the URL of this webpage as the original URL.

you can use one of this options:
- use the original URL directly and pass cookies to youtube-dl(should if they are directly using one of the supported embeds).
- use vimeo player url with the original URL as a referer(`--referer URL`).
- just replace `json` extension with `mpd`.

**Comment by victorhooi** [comment]
I can confirm swapping the `json` extension for `mpd` works - out of curiosity - why is this?

And is this documented somewhere in the README/manpage?

**Comment by remitamine** [comment]
> I can confirm swapping the json extension for mpd works - out of curiosity - why is this?

because `youtube-dl` does support `mpd` manifests(`DASH` formats).
> And is this documented somewhere in the README/manpage?

no. there is no need to document those hacks, it's not the preferred way for using `youtube-dl`.

**Comment by Hrxn** [comment]
BTW, I think this issue should be set to _open_ again then..
The initial problem
> I'm attempting to download an embedded Vimeo video on a webpage. The webpage is behind a username/password.

is not really addressed, yet. Or not?

**Comment by remitamine** [comment]
> is not really addressed, yet. Or not?

i think that the issue will need to be opened if:
1- the first method i have described does not work(using the cookies).
2- @victorhooi needs to provide the requested information(a verbose log using cookies on the original URL).
then the issue would be opened and even if there where someone interested to work on it or even there is a PR to solve the problem, it mostly never resolved upstream because there is no one actually willing to provide credentials to one of the maintainers to test the code or work on the issue before including it in the master branch: https://github.com/rg3/youtube-dl/issues?q=is%3Aopen+is%3Aissue+label%3Aaccount-needed.

**Comment by HighTowerBK** [comment]
Hello,

Im not sure I am at the right place but I've been trying to use viemo-download.py and I always the message:

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

maybe @victorhooi could help me out?

THANKS a lot!

**Comment by luvarpt** [comment]
Try to change suffix of url **master.json?base64_init=1** into **master.mpd**. Have a look at [akamai documentation](https://learn.akamai.com/en-us/webhelp/media-services-live/media-services-live-encoder-compatibility-testing-and-qualification-guide-v4.0/GUID-A5FD9C5A-F946-4967-90B4-D050CE819D16.html).
