### ISSUE TITLE
add GET parameters with fragments in m3u8 playlist

### ISSUE THREAD

**Issue by svkdvlp** [rg3/youtube-dl#14708]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.06**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I want to download a file by m3u8 playlist. The url needs 2 GET url parametes. No issue with that. Successfully downloaded playlist. But all the fragments need those 2 params. So youtube-dl gives 403 forbidden error with all fragments. Can I get any methods to supply those params with fragment download urls?

**Comment by dstftw** [comment]
Programmatically you can use internal `extra_param_to_segment_url` parameter to pass arbitrary query to each fragment:
https://github.com/rg3/youtube-dl/blob/cc6a960e134614f8af2a42dcd8bf146d63638a3c/youtube_dl/extractor/uplynk.py#L37-L38
There is no way to do similar in regular usage scenario though.
