### ISSUE TITLE
youku.com stop working Nov 9, 2017

### ISSUE THREAD

**Issue by yangliwei55** [rg3/youtube-dl#14707]
[youku] XMzEyODg5OTkxNg: Retrieving cna info
[youku] XMzEyODg5OTkxNg: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
bal@debian:~/Downloads$ youtube-dl --version
2017.11.06

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
