### ISSUE TITLE
WSJ: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#14704]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.06**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [] Site support request (request for adding support for a new site)
- [] Feature request (request for a new functionality)
- [] Question
- [] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
>youtube-dl.py -v "https://www.wsj.com/video/series/a-brief-history-of/the-modern-cell-carrier-how-we-got-here/980E2187-401D-48A1-B82B-1486CEE06CB9"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.wsj.com/video/series/a-brief-history-of/the-modern-cell-carrier-how-we-got-here/980E2187-401D-48A1-B82B-1486CEE06CB9']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.11.06
[debug] Python version 2.7.6 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-83410-gb1e2192, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 980E2187-401D-48A1-B82B-1486CEE06CB9: Requesting header
WARNING: Could not send HEAD request to https://www.wsj.com/video/series/a-brief-history-of/the-modern-cell-carrier-how-we-got-here/980E2187-401D-48A1-B82B-1486CEE06CB9: <urlopen error [Errno 1] _ssl.c:507: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
[generic] 980E2187-401D-48A1-B82B-1486CEE06CB9: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:507: error:14
077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> (cause
d by URLError(SSLError(1, '_ssl.c:507: error:14077410:SSL routines:SSL23_GET_SER
VER_HELLO:sslv3 alert handshake failure'),))
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 50
6, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 2195, in
urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\utils.py", line 1086, in http
s_open
    req, **kwargs)
  File "C:\Python27\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.wsj.com/video/series/a-brief-history-of/the-modern-cell-carrier-how-we-got-here/980E2187-401D-48A1-B82B-1486CEE06CB9

Pointing directly to video on akamai **_does_** work:
https://wsjvod-i.akamaihd.net/i/video/20171106/110617telecom/110617telecom_v2_ec,464,174,264,664,1264,1864,2564,5064,k.mp4.csmil/index_7_av.m3u8

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

Thanks
Ringo

**Comment by yan12125** [comment]
```youtube-dl "wsj:980E2187-401D-48A1-B82B-1486CEE06CB9"``` works on Python 2.7.9+. wsj.com uses SNI, so you can't use it with old Python.

**Comment by yan12125** [comment]
Well, there are too many reasons for CERTIFICATE_VERIFY_FAILED. My first guess is https://bugs.python.org/issue20916 - you need to visit a website (wsj.com) first before Python can correctly connect to it. Other reasons/fixes can be found in #7309.

**Comment by yan12125** [comment]
BTW, Python 3.7a1 gives more info about CERTIFICATE_VERIFY_FAILED - worth a try.

**Comment by RingoTheDog** [comment]
OK...
As always...thank you!

**Comment by yan12125** [comment]
Well, some lines still need a change to make the original url https://www.wsj.com/video/series/a-brief-history-of/the-modern-cell-carrier-how-we-got-here/980E2187-401D-48A1-B82B-1486CEE06CB9 work. Reopening as a reminder.

**Comment by yan12125** [comment]
OK. Such URLs will be recognized in the next version. Thanks for the report!
