### ISSUE TITLE
Strange error when downloading from "youtube.com/watch?v"

### ISSUE THREAD

**Issue by ScttB** [rg3/youtube-dl#14718]
```
>youtube-dl https://www.youtube.com/watch?v
[generic] watch?v: Requesting header
[redirect] Following redirect to https://www.youtube.com/
[generic] www.youtube: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.youtube: Downloading webpage
[generic] www.youtube: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/
```

What I think should happen instead of this is

```
>youtube-dl https://www.youtube.com/watch?v
ERROR: Video not set - check URL for errors
```

I believe this behavior should be implemented is because if you use `youtube-dl` in a batch script, this error might happen because of the `=` being ignored by a parsing error if the URL is not enclosed in double-quotations when invoked.

Possibly you could check if the program is running from a batch script on Windows and return `ERROR: Put URL in double-quotes`?

**Comment by dstftw** [comment]
Controlling proper escaping or quoting is responsibility of a user not youtube-dl. Needless to say it's technically impossible to know whether the original URL contained unescaped `&` or not.

**Comment by ScttB** [comment]
I didn't ask to control escaping. I asked for the error to be more informative, assuming it might have been ruined by escaping or user error.
