### ISSUE TITLE
video.vice.com - "Unable to extract watch hub"

### ISSUE THREAD

**Issue by theodric** [rg3/youtube-dl#14728]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
# youtube-dl --verbose https://video.vice.com/en_us/video/surviving-alone-in-alaska-far-out-heimo39s-arctic-refuge/55dddea5329aa203462ae4a9
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://video.vice.com/en_us/video/surviving-alone-in-alaska-far-out-heimo39s-arctic-refuge/55dddea5329aa203462ae4a9']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.06
[debug] Python version 2.7.13 - Linux-4.13.0-0.bpo.1-amd64-x86_64-with-debian-9.2
[debug] exe versions: ffmpeg 3.2.8-1, ffprobe 3.2.8-1
[debug] Proxy map: {}
[vice] surviving-alone-in-alaska-far-out-heimo39s-arctic-refuge: Downloading webpage
ERROR: Unable to extract watch hub; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vice.py", line 162, in _real_extract
    return self._extract_preplay_video(urlh.geturl(), locale, webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vice.py", line 26, in _extract_preplay_video
    r'(?s)(<watch-hub\s*.+?</watch-hub>)', webpage, 'watch hub'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 800, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract watch hub; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
Single video: https://video.vice.com/en_us/video/surviving-alone-in-alaska-far-out-heimo39s-arctic-refuge/55dddea5329aa203462ae4a9

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Attempt to scrape a video from video.vice.com fails with error "Unable to extract watch hub" and instructs me to open a bug report.

I see a couple of related issues in the bug tracker closed with no resolution as 'duplicate' with no indication of what they are supposed to be a duplicate *of.* Nevertheless, I can assure you that this issue is very much still present in 2017.11.06 as of 2017-11-12.

**Comment by theodric** [comment]
Exactly what is this a duplicate of?

**Comment by dstftw** [comment]
Use search.
