### ISSUE TITLE
sinus bot

### ISSUE THREAD

**Issue by Jacksharkben** [rg3/youtube-dl#14729]
all I want to know is will this work with google cloud. so I can run this music bot with youtube-dl. 
sinusbot.com

**Comment by Jacksharkben** [comment]
![35 196 59 40 - chrome rdp for google cloud platform 11_11_2017 11_06_53 pm](https://user-images.githubusercontent.com/19135398/32696122-108039e6-c735-11e7-943a-4fcc375f1951.png)

**Comment by Jacksharkben** [comment]
![youtube-dl - freenode web irc - google chrome 11_11_2017 11_27_16 pm](https://user-images.githubusercontent.com/19135398/32696224-ea20fb66-c737-11e7-93b9-55633e6253f4.png)

**Comment by dstftw** [comment]
youtube-dl will work on any OS that is capable of running python.
