### ISSUE TITLE
redirection in firefox

### ISSUE THREAD

**Issue by jalanb** [rg3/youtube-dl#14722]
Turns out to be a feature, not a bug. So I'd just like to thank someone for doing this:

I use https://duck.duck.go in the URL bar of Firefox for searching, so "!yt" searches youtube. 

But tonight I missed the !, found your site, and came straight to GitHub to check for an update, and I found I'm a year behind. Oops.

I'm a Release Manager by day, and all releases should be so easy! Kudos.

So I'll say

Thanks Guys n Gals.

Oh, found it in another tab: https://www.youtube.com/watch?v=6apMFqg28fw

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
