### ISSUE TITLE
Add support for passing %(duration)s to --sleep parameters

### ISSUE THREAD

**Issue by JarLob** [rg3/youtube-dl#14721]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.06**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

In order to not get banned it would be logical to sleep for the duration of the last downloaded video in a playlist. There is already support for duration in Output Template, but it doesn't work when passed to --sleep-interval.
Please  implement something similar to:
1) "--sleep-interval %(duration)s"
2) "--sleep-interval %(duration)s --max-sleep-interval %(duration + 123)s" The idea is to sleep exactly how long the video lasts or a bit longer.

**Comment by dstftw** [comment]
1. `duration` is optional and may not be present.
2. Output template does not support any calculations.
3. Sleeping for duration time after downloading the whole file immediately does not make much sense since it still does not mimic webplayer behavior and easily detectable. Rate limiting download to video bitrate is more reasonable in this case.

**Comment by JarLob** [comment]
1) Presence of "duration" is specific to extractor, same as a chance to get a Ban. Pluralsight, for example. I know there is a duration implemented in the extractor and I know there is a chance to be banned. So it would work for specific extractors.
2) The second example with calculations was a "nice to have". At least feature 1. that doesn't require calculations could have been implemented.
3) I'm new to youtube-dl. Could you provide an example what parameters to pass to stay least detectable? What to pass to youtube-dl to limit download rate to the video bitrate automatically?
