### ISSUE TITLE
Linux Debian: Not working after installation

### ISSUE THREAD

**Issue by Crwd** [rg3/youtube-dl#14723]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I installed all dependecies but youtube-dl is simply not working.
When I used it earlier I had no problems. When I type in `youtube-dl -h `following pops out:
http://prntscr.com/h95rhp

**Comment by dstftw** [comment]
The error speaks for itself.

**Comment by Crwd** [comment]
What does the error speak ?! No module named email ? Your answer doesnt help me very much..

**Comment by naavin46** [comment]
@Crwd I just had the same issue as well. 
Fixed it using `pip upgrade` method from the installation guide. 
Hope it helps.

Solution: `sudo -H pip install --upgrade youtube-dl`

Reference: https://github.com/rg3/youtube-dl#installation
