### ISSUE TITLE
Crunchyroll new episode not downloading

### ISSUE THREAD

**Issue by Grom2088** [rg3/youtube-dl#14742]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.06**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl "http://www.crunchyroll.com/boruto-naruto-next-generations/episode-32-the-quest-for-souvenirs-753497" -f worst --sub-lang enUS --sub-format ass --write-sub --embed-subs --verbose --cookies cookies.txt -o "F:\test\%(series)s/%(series)s - %(episode_number)s - %(episode)s.%(ext)s"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.crunchyroll.com/boruto-naruto-next-generations/episode-32-the-quest-for-souvenirs-753497', '-f', 'worst', '--sub-lang', 'enUS', '--sub-format', 'ass', '--write-sub', '--embed-subs', '--verbose', '--cookies', 'cookies.txt', '-o', 'F:\\test\\%(series)s/%(series)s - %(episode_number)s - %(episode)s.%(ext)s']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.11.06
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-88804-g3af2bf0af0, ffprobe N-88804-g3af2bf0af0
[debug] Proxy map: {}
[Crunchyroll] 753497: Downloading webpage
ERROR: This is a sample clip. To watch the full video, start a free trial today!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\extractor\crunchyroll.py", line 400, in _real_extract
youtube_dl.utils.ExtractorError: This is a sample clip. To watch the full video, start a free trial today!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Crunchyroll not letting me download newer episodes, I have a premium subscription to the site, I have tried on 2 seperate accounts both of which have a currently active membership, I have with cookies, user-agent, username and password, and as many combinations of them as possible and it keeps throwing back the exact same error.

There was another issue regarding this, And the reply was that it required a subscription, But i have a subscription and getting the error still.

**Comment by enigmaquip** [comment]
I wasn't able to get the user/pass to work on youtube-dl as it was giving at 503 on the login page (only through youtube-dl), but I signed into crunchyroll and exported my cookie's and was able to download this file just fine

**Comment by yan12125** [comment]
Crunchyroll is partially broken as of now. Please check out #11572.
