### ISSUE TITLE
[bilibili] youtube-dl shows video formats inconsistently

### ISSUE THREAD

**Issue by xczheng** [rg3/youtube-dl#14743]
Now sure if this is a youtube-dl problem, or server side problem, but it shows the formats inconsistently. Sometimes it has format "1" and sometimes it doesn't.

$ youtube-dl  -v  -F "https://www.bilibili.com/video/av14782039/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.bilibili.com/video/av14782039/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.06
[debug] Python version 3.6.0 - Linux-3.2.61-grsec-modsign-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg N-87921-gdf45ea45df-static, ffprobe N-87921-gdf45ea45df-static
[debug] Proxy map: {}
[BiliBili] 14782039: Downloading webpage
[BiliBili] 14782039: Downloading video info page
[info] Available formats for 14782039:
format code  extension  resolution note
0            mp4        unknown
1            mp4        unknown    367.27MiB (best)
[~]
$ youtube-dl  -v  -F "https://www.bilibili.com/video/av14782039/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.bilibili.com/video/av14782039/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.06
[debug] Python version 3.6.0 - Linux-3.2.61-grsec-modsign-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg N-87921-gdf45ea45df-static, ffprobe N-87921-gdf45ea45df-static
[debug] Proxy map: {}
[BiliBili] 14782039: Downloading webpage
[BiliBili] 14782039: Downloading video info page
[info] Available formats for 14782039:
format code  extension  resolution note
0            mp4        unknown
1            mp4        unknown    367.27MiB (best)
[~]
$ youtube-dl  -v  -F "https://www.bilibili.com/video/av14782039/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.bilibili.com/video/av14782039/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.06
[debug] Python version 3.6.0 - Linux-3.2.61-grsec-modsign-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg N-87921-gdf45ea45df-static, ffprobe N-87921-gdf45ea45df-static
[debug] Proxy map: {}
[BiliBili] 14782039: Downloading webpage
[BiliBili] 14782039: Downloading video info page
[info] Available formats for 14782039:
format code  extension  resolution note
0            mp4        unknown    367.27MiB
[~]
$ youtube-dl  -v  -F "https://www.bilibili.com/video/av14782039/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.bilibili.com/video/av14782039/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.06
[debug] Python version 3.6.0 - Linux-3.2.61-grsec-modsign-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg N-87921-gdf45ea45df-static, ffprobe N-87921-gdf45ea45df-static
[debug] Proxy map: {}
[BiliBili] 14782039: Downloading webpage
[BiliBili] 14782039: Downloading video info page
[info] Available formats for 14782039:
format code  extension  resolution note
0            mp4        unknown    367.27MiB

**Comment by yan12125** [comment]
Could you run ```youtube-dl --write-pages -v -F "https://www.bilibili.com/video/av14782039/"``` and upload *.dump files when there are 2 formats? I never get more than 1 format for this video.

**Comment by remitamine** [comment]
I'm getting two formats:
```json
{
    "from": "local",
    "result": "suee",
    "quality": 16,
    "format": "mp4",
    "timelength": 2909909,
    "accept_format": "mp4",
    "accept_quality": [1],
    "seek_param": "start",
    "seek_type": "second",
    "durl": [{
        "order": 1,
        "length": 2909909,
        "size": 385106987,
        "url": "http://tx.acgvideo.com/28/98/24089828/24089828-1-16.mp4?txTime=1515433518&platform=pc&txSecret=60941bdc9fb59243cbb5be9054cb1252&oi=3306640703&rate=240000&hfb=b99ffc3c5c68f00a33123bb25f882d5b",
        "backup_url": ["http://ws.acgvideo.com/8/60/24089828-1.mp4?wsTime=1515433518&platform=pc&wsSecret2=8499ba4c14b6240dac2f9951c972b58e&oi=3306640703&rate=224"]
    }],
    "hit_ssd_sid": []
}
```
@yan12125 i don't see a problem here, it depend on whether bilibili return a `backup_url` or not.

**Comment by yan12125** [comment]
> it depend on whether bilibili return a ```backup_url``` or not.

Thanks. You're right.
