### ISSUE TITLE
-f "bestvideo" says 'ERROR: requested format not available' on some vimeo video

### ISSUE THREAD

**Issue by retsyo** [rg3/youtube-dl#14754]
```bash
python N:\greensoft\net\youtube-dl-master\youtube_dl\__main__.py --proxy 127.0.0.1:3059 -f "bestvideo" https://vimeo.com/96737246
``` says `ERROR: requested format not available`

but 
```bash
python N:\greensoft\net\youtube-dl-master\youtube_dl\__main__.py --proxy 127.0.0.1:3059 -f "bestvideo" https://vimeo.com/226888622
``` can runs ok

**Comment by dstftw** [comment]
There videos don't have `bestvideo` format as clearly states in the error messge.

**Comment by retsyo** [comment]
yes, but it is hard for user to download loads of videos via `--batch-file list.txt` because user can't know this parameter for every video and write every command line. So is it possible to ignore `bestvideo`  format if there is no one?

**Comment by dstftw** [comment]
Bother to read format selection section.
