### ISSUE TITLE
How to run youtube-dl through "do shell script" in Applescript?

### ISSUE THREAD

**Issue by Caleb707** [rg3/youtube-dl#14767]
![screen shot 2017-11-16 at 4 11 30 pm](https://user-images.githubusercontent.com/32884251/32875178-9292dea8-caea-11e7-9a49-8d2df805aa23.png)

I've never posted on GitHub before so idk if I'm doing this right... but I'm trying to do a shell script through Applescript but it won't work! how do I do it?

## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.11.15
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by johnhawkinson** [comment]
It looks like it's correct…perhaps `youtube-dl` is not in your `PATH`.

Try:

```scpt
set youtubeDownloadCommand to "/usr/local/bin/youtube-dl -o" ...
```

If not, run `type -ap youtube-dl` in your Terminal interactively and try the result (or post it here).

**Comment by section83** [comment]
This is really an AS question not ytdl.  Anyway, as johnhawkinson says, make sure youtube-dl is in your Path.  For example, assuming youtube.exe is in `/usr/local/bin`:

`set shellPath to "PATH=$PATH:/bin:/sbin:/usr/bin:/usr/local/bin:/usr/sbin:~/opt/bin:~/opt/sbin:/opt/local/bin:/opt/local/sbin:" & quoted form of (POSIX path of ((path to me as text) & "::")) & "; "`

then,

`do shell script shellPath "youtube-dl" & etc. etc.`

NB: AppleScript uses a different shell to Terminal.  Thus, any Path changes in Terminal will not affect what happens when you run a script.

I am working on an AppleScript based front end for youtube-dl.  Current version is available here:

[https://forum.videohelp.com/threads/384566-youtube-dl-GUI-for-Apple-Macs](url)

It works well with built-in updates for components, sub-titles, descriptions etc.  But, currently can't do playlists.

Next version will be available soon (when I finished ironing out bugs).

**Comment by johnhawkinson** [comment]
I think it's just easier to specify `/usr/local/bin/youtube-dl` instead of `youtube-dl` rather than going to the effort of setting the path in AppleScript. Anyhow, good luck!

**Comment by yan12125** [comment]
Thanks for all the kind help for youtube-dl users! I bet $PATH is exactly the issue, so closing.
