### ISSUE TITLE
Audio not available

### ISSUE THREAD

**Issue by HakaiShin1811** [rg3/youtube-dl#14765]
When i try to download all the video of one channel at best quality i use this command
youtube-dl -f bestvideo "URL channel"
Is it possible to use bestvideo+bestaudio at the same time ? Because the bestvideo download don't have any sound !!
Check my vid : https://www.youtube.com/watch?v=Ck5HCLwrcTU&feature=youtu.be
How can i download the best quality and audio at the same time ?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#format-selection
