### ISSUE TITLE
New Extractor ? uptostream

### ISSUE THREAD

**Issue by Arnaud69** [rg3/youtube-dl#14778]
Hello,
is it possible for uptostream ?
exemple :
https://uptostream.com/am9u61zg6ewf

Many thx

**Comment by rajucomp** [comment]
I think that should be possible. Examining the source page, the link for the video can be found. For instance, the video URL in your case is "https://www98.uptostream.com/4altmn7a537/360/0/video.mp4". Examining the source page of the URL, I jumped onto this line "var sources = [{"src":"https:\/\/www98.uptostream.com\/4altmn7a537\/360\/0\/video.mp4","type":"video\/mp4","label":"360p","res":"360","lang":"unknown 0","idLang":"0"}];". It contains the download link. Maybe the mods can implement the functionality.

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.
