### ISSUE TITLE
can't download a playlist with embedded subtitles for each vid and a name for the folder I hold them in

### ISSUE THREAD

**Issue by ParsaFakhar** [rg3/youtube-dl#14776]
I write:

youtube-dl -o -v -f mp4 --write-sub --sub-format ttml --convert-subtitles srt --embed-subs '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https://www.youtube.com/playlist\?list\=PLbdKuAPc3qsF8bUrG2IBcbLeg2zdVu38U

Terminal:

➜  ~ youtube-dl -v -f mp4 --write-sub --sub-format ttml --convert-subtitles srt --embed-subs '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https://www.youtube.com/playlist\?list\=PLbdKuAPc3qsF8bUrG2IBcbLeg2zdVu38U
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'mp4', u'--write-sub', u'--sub-format', u'ttml', u'--convert-subtitles', u'srt', u'--embed-subs', u'%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', u'https://www.youtube.com/playlist?list=PLbdKuAPc3qsF8bUrG2IBcbLeg2zdVu38U']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.29
[debug] Python version 2.7.10 - Darwin-17.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[generic] %(playlist_index)s - %(title)s: Requesting header
WARNING: Could not send HEAD request to http://%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[generic] %(playlist_index)s - %(title)s: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 8] nodename nor servname provided, or not known> (caused by URLError(gaierror(8, 'nodename nor servname provided, or not known'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2195, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 930, in http_open
    req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)

**Comment by ParsaFakhar** [comment]
youtube-dl -f mp4 --write-sub --sub-format ttml --convert-subtitles srt --embed-subs -o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https://www.youtube.com/playlist\?list\=PLbdKuAPc3qsF8bUrG2IBcbLeg2zdVu38U

this is what I had to write 😆

**Comment by yan12125** [comment]
You got it :)
