### ISSUE TITLE
question about metadata

### ISSUE THREAD

**Issue by Drytak** [rg3/youtube-dl#14775]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Hello, I need some help with adding the metadata. I have no problem from a youtube video with Artist _ SongName to add them to the metadata using 

--add-metadata 
--metadata-from-title "%(artist)s - %(title)s"

What I would like to do is also adding the SongName as the album, but when I try to do 

--add-metadata 
--metadata-from-title "%(artist)s - %(title)s"
--add-metadata 
--metadata-from-title "%(album)s"

or 

--add-metadata 
--metadata-from-title "%(artist)s - %(title)s"
--metadata-from-title "%(album)s"

it just add the album, and doesn't change the artist and title. Is it possible to do?

What I would like to have is 
Song = Rockstar
Artist = Post Malone
Album = Rockstar

Thanks a lot.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by Drytak** [comment]
Do I miss anything now? sorry for the inconvenience.
