### ISSUE TITLE
[wwe] ERROR: Unsupported URL

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#14781]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs http://www.wwe.com/article/walk-the-prank-wwe-edition -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', 'http://www.wwe.com/article/walk-the-prank-wwe-edition', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86911-gb664d1f, ffprobe N-86911-gb664d1f
[debug] Proxy map: {}
[generic] walk-the-prank-wwe-edition: Requesting header
WARNING: Falling back on generic information extractor.
[generic] walk-the-prank-wwe-edition: Downloading webpage
[generic] walk-the-prank-wwe-edition: Extracting information
ERROR: Unsupported URL: http://www.wwe.com/article/walk-the-prank-wwe-edition
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\generic.py", line 3075, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.wwe.com/article/walk-the-prank-wwe-edition
...
<end of log>
```

---
- Single video: http://www.wwe.com/article/walk-the-prank-wwe-edition
- Single video: http://www.wwe.com/videos/go-behind-the-scenes-of-the-new-day-and-alex-bliss-prank-on-disney-xds-walk-the-prank

---

### Description of your *issue*
Please add support, thanks. :)

**Comment by parmjitv** [comment]
Hi @RuneMagle,

I am going to give this new extractor a shot.  Are there any videos featured on the WWE site that require a user account for viewing?  I don't believe so from the example URLs you have provided.  Thanks!

Cheers,

Parmjit V.

**Comment by RuneMagle** [comment]
I don't think so.

**Comment by parmjitv** [comment]
Cool, thank you.  A new PR for this extractor will be submitted shortly.

**Comment by RuneMagle** [comment]
Awesome. Thanks! :)

**Comment by parmjitv** [comment]
Hi @RuneMagle,

My apologies for dropping the ball on this one.  Another gentleman has been kind enough to provide a new extractor for WWE.com - see PR #17450.

Cheers,

Parmjit V.
