### ISSUE TITLE
How to exclude youtube id from file name ?

### ISSUE THREAD

**Issue by HakaiShin1811** [rg3/youtube-dl#14785]
How do i exclude the youtube ID ? From Example-QnS-Hm76TnU5Q.mp4 to Example.mp4?
I've make sure my youtube-dl version is 2017.15.11 !

**Comment by yan12125** [comment]
```-o "%(title)s.%(ext)s"```. Check https://github.com/rg3/youtube-dl/blob/master/README.md#output-template
