### ISSUE TITLE
Something like "--playlist-start NUMBER" for Channel

### ISSUE THREAD

**Issue by ParsaFakhar** [rg3/youtube-dl#14783]
is there anything like --uploader-start NUMBER?

youtube-dl -x --audio-quality 0 --audio-format mp3 -o '%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https://www.youtube.com/user/PaperBagBandits/videos

I downloaded 140 of them but I don't want to wait all 140 of them to be realized by youtube-dl that they are already downloaded, I need to start download at 140, is there any way?

**Comment by dstftw** [comment]
`--download-archive`.

**Comment by developerhuman12** [comment]
I have tried this:
https://askubuntu.com/a/997210/708165
