### ISSUE TITLE
BR (Bayerischer Rundfunk Mediathek) extractor broken after site redesign

### ISSUE THREAD

**Issue by z1atk0** [rg3/youtube-dl#14788]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[zlatko@disclosure:~]$ youtube-dl -v -F "https://www.br.de/mediathek/video/dokthema-gegen-die-marihuana-mafia-wo-cannabis-und-kriminalitaet-bluehen-av:59d4b52750223b0012a19718"
[debug] System config: []
[debug] User config: [u'--proxy', u'', u'--rate-limit', u'20M']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.br.de/mediathek/video/dokthema-gegen-die-marihuana-mafia-wo-cannabis-und-kriminalitaet-bluehen-av:59d4b52750223b0012a19718']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.15
[debug] Python version 2.7.14 - Linux-4.12.11-i686-Intel-R-_Core-TM-_i3-3220_CPU_@_3.30GHz-with-slackware-14.2
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] dokthema-gegen-die-marihuana-mafia-wo-cannabis-und-kriminalitaet-bluehen-av:59d4b52750223b0012a19718: Requesting header
WARNING: Falling back on generic information extractor.
[generic] dokthema-gegen-die-marihuana-mafia-wo-cannabis-und-kriminalitaet-bluehen-av:59d4b52750223b0012a19718: Downloading webpage
[generic] dokthema-gegen-die-marihuana-mafia-wo-cannabis-und-kriminalitaet-bluehen-av:59d4b52750223b0012a19718: Extracting information
ERROR: Unsupported URL: https://www.br.de/mediathek/video/dokthema-gegen-die-marihuana-mafia-wo-cannabis-und-kriminalitaet-bluehen-av:59d4b52750223b0012a19718
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2170, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3075, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.br.de/mediathek/video/dokthema-gegen-die-marihuana-mafia-wo-cannabis-und-kriminalitaet-bluehen-av:59d4b52750223b0012a19718

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Single video: https://www.br.de/mediathek/video/dokthema-gegen-die-marihuana-mafia-wo-cannabis-und-kriminalitaet-bluehen-av:59d4b52750223b0012a19718
- Single video: https://www.br.de/mediathek/video/monaco-110-die-wildsau-av:59d4b655293bac0012535043
- Single video: https://www.br.de/mediathek/video/hubert-und-staller-rutschpartie-av:59d4b655293bac0012535035

More videos at https://www.br.de/mediathek/.

---

### Description of your *issue*, suggested solution and other information

The "br.py" extractor doesn't feel responsible anymore because the video URL schema has changed with the site redesign, and the fallback generic extractor can't make any sense of it, either.

**Comment by maXity** [comment]
Already reported in #14560
