### ISSUE TITLE
OpenLoad ERROR: Unable to extract title

### ISSUE THREAD

**Issue by RomanEmelyanov** [rg3/youtube-dl#14798]
./youtube-dl -g --verbose https://openload.co/embed/8UfA9bc_6qo/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-g', u'--verbose', u'https://openload.co/embed/8UfA9bc_6qo/']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2017.11.15
[debug] Python version 2.7.6 - Linux-2.6.32-042stab116.2-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, phantomjs 8
[debug] Proxy map: {}
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/openload.py", line 321, in _real_extract
    'description', webpage, 'title', fatal=True)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 930, in _html_search_meta
    html, display_name, fatal=fatal, group='content', **kwargs)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 809, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 800, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Outdated phantomjs.
