### ISSUE TITLE
Support for Voice of America

### ISSUE THREAD

**Issue by picsi** [rg3/youtube-dl#14804]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Voice of America is a US gov news agency that creates public domain videos, such as these:

* https://www.voaportugues.com/a/seca-crise-precedentes-africa/3844842.html
* https://www.voaafrique.com/a/4124029.html
* https://www.voanews.com/a/birds-connect-people-with-nature/4119919.html

Notice the URLs are different, but the underlying structure for metadata scraping is the same. A full list of language versions of VOA can be found at https://www.voaportugues.com/navigation/allsites. 

This was originally posted at https://github.com/toolforge/video2commons/issues/91 but I was sent upstream.

**Comment by enigmaquip** [comment]
The generic extractor can already handle these links
