### ISSUE TITLE
Unable to pull ALL videos in a course on Lynda.com with Netscape formatted COOKIES for an organization authorization

### ISSUE THREAD

**Issue by k432ts** [rg3/youtube-dl#14808]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

D:\lynda download\youtube-dl>youtube-dl.exe --verbose https://www.lynda.com/Python-tutorials/Python-3-Essential-Training/62226-2.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.lynda.com/Python-tutorials/Python-3-Essential-Training/62226-2.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-88555-g6ea7711532, ffprobe N-88555-g6ea7711532
[debug] Proxy map: {}
[lynda:course] 62226: Downloading course JSON
**WARNING: 72 videos are only available for members (or paid members) and will not be downloaded. Use --username and --password options to provide lynda.com account credentials.
[download] Downloading playlist: Python 3 Essential Training**
[lynda:course] playlist Python 3 Essential Training: Collected 15 video ids (downloading 15 of them)
[download] Downloading video 1 of 15
[lynda] 70920: Downloading video JSON
[lynda] 70920: Checking 1-540 video format URL
[lynda] 70920: Checking 1-360 video format URL
[lynda] 70920: Checking 0-540 video format URL
[lynda] 70920: Checking 0-360 video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/62226/VBR_MP4h264_main_SD/62226_01_01_SC03_welcome.mp4?_eFGH11v2tTZd0PamdvmH8NUFM7d5JAj2nbkUIp7ObjAeOCc-oqAZl6Wq__wiPRVEyASE9D_FzY2ol6Ox3fLFPVtgkHSrtCK4U5UAyabFIRqmOsT5u0hGHE_rF0aag3PsLV3SmT8ORAHh9kpUb2yY642406xAXYa9mUjMiw5rsF8uiHkjsgXPgUd&c3.ri=3769971592006734048'
[download] Destination: Welcome-70920.mp4
[download] 100% of 3.36MiB in 00:03
[download] Downloading video 2 of 15
[lynda] 70924: Downloading video JSON
[lynda] 70924: Checking 1-540 video format URL
[lynda] 70924: Checking 1-360 video format URL
[lynda] 70924: Checking 0-540 video format URL
[lynda] 70924: Checking 0-360 video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/62226/VBR_MP4h264_main_SD/62226_02_01_SC11_hello.mp4?qf-EFwIFy2Sw7e0UbJlW7sP4Ho8jFfwXaNGbM0fi8FRxDhF8Fd8GQFfMwrljK4SMrsWfpjHF3DqgRMamJY7e_tEFtUuBCx42uI6SqKoKZ0f2nBv963kkbZejNCA3D2zQjyvSUX331__y_V-Gwym02kUHubIoGnappHmD0qIWXEKW3oGx8Jt08Q&c3.ri=3769971592006734317'
[download] Destination: Getting started with 'Hello World'-70924.mp4
[download]  38.6% of 6.70MiB at 221.79KiB/s ETA 00:18
ERROR: Interrupted by user

---

Used CTRL+C to stop it

I'm using a library card account
and when I use --cookies, this problem is exactly the same as the bolded lines above. 

MY browser is Chrome[latest version] and the add-on is "EditThisCookie"[latest version] cookies are Netscape formatted

I'm so frustrated unable to pull the whole course down, so plz

**Comment by dstftw** [comment]
Provide complete log cookies passed.

**Comment by k432ts** [comment]
D:\lynda download\youtube-dl>youtube-dl.exe --cookies cookies.text --all-subs https://www.lynda.com/Python-tutorials/Python-3-Essential-Training/62226-2.html
[lynda:course] 62226: Downloading course JSON
WARNING: 72 videos are only available for members (or paid members) and will not be downloaded. Use --username and --password options to provide lynda.com account credentials.
[download] Downloading playlist: Python 3 Essential Training
[lynda:course] playlist Python 3 Essential Training: Collected 15 video ids (downloading 15 of them)
[download] Downloading video 1 of 15
[lynda] 70920: Downloading video JSON
[lynda] 70920: Checking 1-360 video format URL
[lynda] 70920: Checking 1-540 video format URL
[lynda] 70920: Checking 0-360 video format URL
[lynda] 70920: Checking 0-540 video format URL
[info] Writing video subtitles to: Welcome-70920.en.srt
[download] Destination: Welcome-70920.mp4
[download]   6.3% of 3.36MiB at 57.74KiB/s ETA 00:55

**Comment by codewizard13** [comment]
This is similar to the issue I'm having downloading from Lynda.com playlists, though I HAVE PROVIDED MY CREDENTIALS. How can I bump this thread? I'll be posting my own, but it's a little disconcerting that the two threads I've found with issues similar to mine have either been abandoned or closed with **no mention of a solution**

**Comment by rotemdan** [comment]
I've published a browser extension that exports a valid `cookies.txt` file that I've verified to work with a `lynda.com` organizational account.

Please see https://github.com/rg3/youtube-dl/issues/15158#issuecomment-415817364 for more details.
