### ISSUE TITLE
using lattest version but can not read json list

### ISSUE THREAD

**Issue by thien154** [rg3/youtube-dl#14812]
d:\youtube\youtube-dl.exe : ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make 
sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
