### ISSUE TITLE
Unable to download video, Errno 104

### ISSUE THREAD

**Issue by endumiuz** [rg3/youtube-dl#14819]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl https://youtu.be/DA7l6JPWEhc -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://youtu.be/DA7l6JPWEhc', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.15
[debug] Python version 2.7.12 - Linux-4.13.0-16-generic-x86_64-with-LinuxMint-18.2-sonya
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] DA7l6JPWEhc: Downloading webpage
[youtube] DA7l6JPWEhc: Downloading video info webpage
[youtube] DA7l6JPWEhc: Extracting video information
[youtube] DA7l6JPWEhc: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r11---sn-5go7dn7s.googlevideo.com/videoplayback?gir=yes&key=yt6&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&expire=1511321476&itag=247&initcwndbps=1002500&mime=video%2Fwebm&ipbits=0&signature=6F0D5A89F6D29650BEEBFDEA725FA5472B6819BD.28180B8D0AE6D07F41322E646A713B2B6D3C1BD1&mt=1511299740&requiressl=yes&clen=4085692&mv=m&source=youtube&ms=au&keepalive=yes&ei=JJsUWv-TMqTc7gS76Y9I&lmt=1510964728094302&ip=194.117.188.224&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&pl=24&dur=191.666&mn=sn-5go7dn7s&mm=31&id=o-AKedwSXH0bKQK6VJ6EuWMOeJX_zw5GFMW_VUxCwHcqd_&ratebypass=yes'
[download] Got server HTTP error: [Errno 104] Connection reset by peer. Retrying (attempt 1 of 10)...
[download] Got server HTTP error: [Errno 104] Connection reset by peer. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: [Errno 104] Connection reset by peer. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: [Errno 104] Connection reset by peer. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: [Errno 104] Connection reset by peer. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: [Errno 104] Connection reset by peer. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: [Errno 104] Connection reset by peer. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: [Errno 104] Connection reset by peer. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: [Errno 104] Connection reset by peer. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: [Errno 104] Connection reset by peer. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 286, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 138, in establish_connection
    raise RetryDownload(err)
RetryDownload

```

### Description of your *issue*, suggested solution and other information

I am unable to download this particular video (https://www.youtube.com/watch?v=DA7l6JPWEhc), no problem with other videos.
It stays at "Invoking downloader" and at every retrying attempt very long (minutes)
For some reason this video also loads slowly in my browser (Firefox), other videos loads much faster.

**Comment by dstftw** [comment]
Connectivity issues between you and host serving bestvideo format. Try another format.

**Comment by endumiuz** [comment]
~~I have tried multiple other formats without success~~
Never mind, You where right, I found a format that worked! Thanks for your time!
