### ISSUE TITLE
Support Eurosport Player

### ISSUE THREAD

**Issue by marykauf** [rg3/youtube-dl#14820]
Possible to add https://www.eurosportplayer.com to youtube-dl supported websites?
I have an annually paid subscription and if it's needed please let me know.
No need to say it's a very complicated website and I deeply believe just only youtube-dl python experts are able to make a way to download its videos.

Cheers

**Comment by marykauf** [comment]
Yes, Obviously its name indicates it only broadcasts in European countries.

**Comment by remitamine** [comment]
post an example of the urls you're trying to watch.
an account would be needed to work on this site, i'm getting this message when i try access any video:
```
Commencer à regarder Eurosport Player.

Regardez des événements, des matchs, des temps forts et des vidéos de vos sports préférés!
S'abonner

OU Connexion
```

**Comment by Tatsh** [comment]
It's probably encrypted with something not yet cracked, like Adobe Pass. See #14004

**Comment by marykauf** [comment]
It's not legal. I've just receive the answer from Eurosport Customer Support. So, please skip this request because of the potential copyright issues.

> Hi,
> 
> Thank you for contacting the Eurosport Player team and I apologize for the delayed answer.
> 
> From your e-mail I understand that you wish to download videos from our plate-form.
> I would like to inform you that as the broadcast rights for sports events are strongly regulated, we are not allowed to let you:
> Record or download videos
> Obtain the event images broadcasted on our antenna
> I hope you are enjoying your favorite sports on Eurosport Player.
> I remain at your disposal for any further information.
> Best,
> 
> 
> Elisabeth

**Comment by beta2k** [comment]
IMO that doesn't mean that the Eurosport Player shouldn't be supported. If the downloaded videos are not distributed online, there should not be an issue.

**Comment by remitamine** [comment]
@beta2k if you want this service to be supported then you can open a new issue for that.

**Comment by beta2k** [comment]
done: #17365
