### ISSUE TITLE
Upgraded video player. Encrypted?

### ISSUE THREAD

**Issue by Scarwoman** [rg3/youtube-dl#14826]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl.exe -v https://dash.emp.ebsd.ericsson.net/dash/Sanoma/SBS/5Ph6QzFVE1n_dbzyr6/5Ph6QzFVE1n_dbzyr6/vod.mpd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://dash.emp.ebsd.ericsson.net/dash/Sanoma/SBS/5Ph6QzFVE1n_dbzyr6/5Ph6QzFVE1n_dbzyr6/vod.mpd']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[generic] vod: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vod: Downloading webpage
[generic] vod: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\generic.py", line 2188, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 1075, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---
- MPD-file:
https://dash.emp.ebsd.ericsson.net/dash/Sanoma/SBS/5Ph6QzFVE1n_dbzyr6/5Ph6QzFVE1n_dbzyr6/vod.mpd
- Single video: https://www.kijk.nl/net5/granddesignsnaarheteindevandewereld/videos/5Ph6QzFVE1n/grand-designs-naar-het-einde-van-de-wereld
- Single video: https://embed.kijk.nl/video/5Ph6QzFVE1n?viewtracker=1&autoplay=true&consent=true

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

This isn't a duplicate. The website upgraded their video player. They don't use Brightcove anymore. I've got the mpd file, but cannot download with youtube-dl.exe

**Comment by dstftw** [comment]
Dulicate of #7223.
