### ISSUE TITLE
Firefox webextension to integrate with youtube-dl

### ISSUE THREAD

**Issue by almet** [rg3/youtube-dl#14832]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

Hi, thanks for working out on this very useful tool. I wanted to let you know that I've crafted a small Firefox web-extension that makes it possible to trigger youtube-dl from the machine it's running to download the video on the active tab.

I was thinking that maybe this could be integrated better with youtube-dl (by for instance activating the icon on every website that supports it), but I wanted to drop the link first. I'm not sure this issue should be kept open, but I wanted a location to discuss around this idea, and I haven't found any other location :)

Here is the link: https://github.com/almet/web2mp3

The software is currently converting the downloaded videos automatically to mp3 but that's something that could be changed.

**Comment by dstftw** [comment]
Offtopic.
