### ISSUE TITLE
select English Sub (if unavailable--> automatically go for auto caption)

### ISSUE THREAD

**Issue by ParsaFakhar** [rg3/youtube-dl#14831]
Download a Single Video with Embedded Subtitle, En lang Sub

youtube-dl -v -f mp4 --write-sub --sub-lang en --sub-format ttml --convert-subtitles srt --embed-subs https://www.youtube.com/watch?v=F0c8U3x_vKM

Download a Single Video with Embedded Subtitle (Auto-Caption)

youtube-dl -v -f mp4 --write-auto-sub --sub-format ttml --convert-subtitles srt --embed-subs https://www.youtube.com/watch?v=Uiy_YuE8lCA

iSSUE:  BUT how to tell youtube-dl to look for written Sub first and if there wasn't any the use auto-caption?

(for example PewDiePie uses his own sub if I write --write-auto-sub I would lose his sub)
and if I write --write-sub (if there wasn't any I would lose the chance to download auto-caption)

**Comment by dstftw** [comment]
By using `--write-sub` and `--write-auto-sub` at the same time.

**Comment by ParsaFakhar** [comment]
@dstftw I tried but it didn't work
