### ISSUE TITLE
[discoverygo] 1080p no longer available ?

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#14830]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---
```
E:\>youtube-dl -F --verbose https://www.discoverygo.com/fast-n-loud/the-race-busch-vs-logano/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', 'https://www.discoverygo.com/fast-n-loud/the-race-busch-vs-logano/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 3.1.85.167 (US) as X-Forwarded-For.
[DiscoveryGo] the-race-busch-vs-logano: Downloading webpage
[DiscoveryGo] the-race-busch-vs-logano: Downloading m3u8 information
[info] Available formats for 5a14a85b6b66d16cfa1ffb28:
format code  extension  resolution note
hls-63       mp4        96x54        63k , avc1.42000a, 6.0fps, mp4a.40.5
hls-134      mp4        192x108     134k , avc1.42000b, 15.0fps, mp4a.40.5
hls-244      mp4        288x162     244k , avc1.42000c, 15.0fps, mp4a.40.5
hls-452      mp4        448x252     452k , avc1.420015, 30.0fps, mp4a.40.5
hls-760      mp4        768x432     760k , avc1.4d001e, 30.0fps, mp4a.40.5
hls-1208     mp4        992x558    1208k , avc1.4d001f, 30.0fps, mp4a.40.5
hls-1884     mp4        1088x612   1884k , avc1.4d001f, 30.0fps, mp4a.40.5
hls-3293     mp4        1280x720   3293k , avc1.64001f, 30.0fps, mp4a.40.5 (best)

```
---

### Description of your *issue*, suggested solution and other information

I can no longer download 1080p videos from any of the DiscoveryGO sites.  I don't know if this is an issue with the extractor, or if they are no longer posting 1080p videos.

This is currently available without a login: https://www.discoverygo.com/fast-n-loud/the-race-busch-vs-logano/

**Comment by dstftw** [comment]
No 1080 for this video.
