### ISSUE TITLE
Downloading whole channel with upload date in file name

### ISSUE THREAD

**Issue by hollysheep** [rg3/youtube-dl#14837]
Hi,

i've here a youtube channel that i like very much and i want to watch the most of the videos - more than 200. normaly i watch them in train. i can download all videos with this command

`youtube-dl ytuser:username`

with this command it should be possible to download a video with the upload date and the name of the video in the file name

`youtube-dl -o "$(date +"%Y%m%d")'-%(title)s" url`

i've tried this with a video, in the file name i have the date from today, not from the date the videos was uploaded to youtube.

how can i do this for a whole channel, so that the file name of the videos includes the upload date and the name of the videos?

**Comment by dstftw** [comment]
`upload_date` meta field in [output template](https://github.com/rg3/youtube-dl#output-template).
