### ISSUE TITLE
Twitch.tv online in player without sound (-f 720p or 480p)

### ISSUE THREAD

**Issue by a-ladanov** [rg3/youtube-dl#14836]
Sorry, I don't know English.
The local player don't play audio if i use the quality of 720p or 480p (-f best normal, with sound)
Site: twitch.tv
Without sound:
'youtube-dl -f 720p -o - "https://www.twitch.tv/starladder1" | "C:\Program Files (x86)\MPC-BE\mpc-be.exe" -'
With sound:
'youtube-dl -o - "https://www.twitch.tv/starladder1" | "C:\Program Files (x86)\MPC-BE\mpc-be.exe" -'
ffmpeg in folder with youtube-dl

**Comment by dstftw** [comment]
720p plays with audio in VLC.
