### ISSUE TITLE
livestream file corruption bug

### ISSUE THREAD

**Issue by StavNamir** [rg3/youtube-dl#14848]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concertize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.07
[debug] Python version 2.7.13 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.3.1, ffprobe 3.3.2
[debug] Proxy map: {}
[youtube] HQhLPgfIH4w: Downloading webpage
[youtube] HQhLPgfIH4w: Downloading video info webpage
[youtube] HQhLPgfIH4w: Extracting video information
[youtube] HQhLPgfIH4w: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r6---sn-cx1x9-ua8z.googlevideo.com/videoplayback/id/HQhLPgfIH4w.1/itag/136/source/yt_live_broadcast/requiressl/yes/g
cr/il/ei/Cn8ZWoy_AsabWbbQmpgH/playlist_type/DVR/force_finished/1/ratebypass/yes/cmbypass/yes/mime/video%2Fmp4/live/1/gir/yes/noclen/1/dur/2.000/signature/68A
B629FD3CA76D01F8087DC8A791B9A9D538015.5F259AF179AD45B3AB517261B3DD08D223CB164A/key/cms1/ip/109.66.181.216/ipbits/0/expire/1511641962/sparams/cmbypass,dur,ei,
expire,force_finished,gcr,gir,id,ip,ipbits,itag,live,mime,mm,mn,ms,mv,noclen,pl,playlist_type,ratebypass,requiressl,source/mm/32/mn/sn-cx1x9-ua8z/ms/lv/mt/15
11620121/mv/u/pl/24/'
[dashsegments] Total fragments: 1971
[download] Destination: 2017-11-25 Bearing talks about his Twitter ban.-HQhLPgfIH4w.f136.mp4
[download] 100% of 37.60MiB in 06:29
[debug] Invoking downloader on u'https://r6---sn-cx1x9-ua8z.googlevideo.com/videoplayback/id/HQhLPgfIH4w.1/itag/140/source/yt_live_broadcast/requiressl/yes/g
cr/il/ei/Cn8ZWoy_AsabWbbQmpgH/playlist_type/DVR/force_finished/1/ratebypass/yes/cmbypass/yes/mime/audio%2Fmp4/live/1/gir/yes/noclen/1/dur/2.000/signature/249
42EE0231E4D1118FB23357DCA526D872958B0.4258E1E7E637B1675E7BCE7CB20979F38D7F1F38/key/cms1/ip/109.66.181.216/ipbits/0/expire/1511641962/sparams/cmbypass,dur,ei,
expire,force_finished,gcr,gir,id,ip,ipbits,itag,live,mime,mm,mn,ms,mv,noclen,pl,playlist_type,ratebypass,requiressl,source/mm/32/mn/sn-cx1x9-ua8z/ms/lv/mt/15
11620121/mv/u/pl/24/'
[dashsegments] Total fragments: 1971
[download] Destination: 2017-11-25 Bearing talks about his Twitter ban.-HQhLPgfIH4w.f140.m4a
[download] 100% of 63.65MiB in 03:45
[ffmpeg] Merging formats into "2017-11-25 Bearing talks about his Twitter ban.-HQhLPgfIH4w.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:2017-11-25 Bearing talks about his Twitter ban.-HQhLPgfIH4w.f136.mp4" -i "file:2017-11-25 Bearing talks about
 his Twitter ban.-HQhLPgfIH4w.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:2017-11-25 Bearing talks about his Twitter ban.-HQhLPgfIH4w.temp.mp4"
Deleting original file 2017-11-25 Bearing talks about his Twitter ban.-HQhLPgfIH4w.f136.mp4 (pass -k to keep)
Deleting original file 2017-11-25 Bearing talks about his Twitter ban.-HQhLPgfIH4w.f140.m4a (pass -k to keep)
```
---

### Description of your *issue*, suggested solution and other information

After a livestream is streamed on youtube, upon ending, the stream is sometimes automatically uploaded as a video to youtube. My bug is that when downloading this stream, *right after* the stream is uploaded, there seems to be a consistent bug, that i am having for months now, that the youtube-dl completely corrupts the downloaded file despite seeming to download the file correctly, but the resulting file is always some 50-60kb file (impossible for a 1 hour stream to be so low) and is always a few seconds of the "Hangouts On Air" picture. i have attached 2 files (mkv, mp4) that are the output of the program, and a ytdl file that was left over from the program, maybe because of some error occurring while downloading.

 thanks for helping, really love the project!

[ytdl.zip](https://github.com/rg3/youtube-dl/files/1503205/ytdl.zip)

**Comment by dstftw** [comment]
Remaining `.ytdl` file means that the download was not finished. This may happen due to lots of reasons. You must provide a verbose log with that demonstrates the problem for any further info.

**Comment by dstftw** [comment]
Remaining `.ytdl` file means that the download was not finished. This may happen due to lots of reasons. You must provide a verbose log with that demonstrates the problem for any further info.

**Comment by StavNamir** [comment]
I did provide a verbose log, the log above is verbose, trying to reproduce this issue by downloading the same link now will not work, it seems to be a problem caused by the fact that i am downloading the stream *right* after it is uploaded. i can try and give you a code in python that will reproduce this but it needs to be active while some channel is just finishing a livestream, and downloading it right away.

also, one of the files attached is of an unfinished download, the other on is of the log above which is clearly finished, as you can see by the line "[download] 100% of 63.65MiB in 03:45", yet the resulting file is the "corrupted stream file example-HQhLPgfIH4w.mkv" which is clearly a bug.

please reopen this issue, I am having this same bug for months, and it can surely be reproduced, i am getting this error a few times a week. if there is anything other than the verbose log and the output files you need i give you.
