### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by hunterx101** [rg3/youtube-dl#14849]
ERROR: Unable to download webpage: [Errno 104] Connection reset by peer (caused by ConnectionResetError(104, 'Connection reset by peer'))

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by gulkily** [comment]
I am having the same issue with most sites. Should I reopen this issue or create a new one.

It seems to have started happening out of the blue a few weeks ago. It was not after a youtube-dl update.

Python 3.5.5
Mac 10.11.6
youtube-dl 2018.06.11
