### ISSUE TITLE
Unable to download udemy videos using youtube-dl.exe for windows

### ISSUE THREAD

**Issue by rmaciel1988** [rg3/youtube-dl#14843]
Dear All,

I can't download videos from udemy using youtube-dl.exe for windows.

My youtube-dl is updated.
My account to udemy has a gmail authentication (which means that I authenticate to udemy via google)

I'm using this command line to connect:

youtube-dl.exe -u MYEMAIL@gmail.com -p MYPASSWORD -o 'C:\Videos' https://www.udemy.com/spark-and-python-for-big-data-with-pyspark/learn/v4/content --verbose

Message error says (in portuguese, I've translated to english):

Status: 10060 A connection attempt failed because the connected component did not respond correctly after a period of time or the established connection failed because the connected host did not respond.

Thanks in advance.

**Comment by dstftw** [comment]
Most likely a network issue on your side.
