### ISSUE TITLE
Got server HTTP error: Downloaded 96468256 bytes, expected 98009808 bytes. 

### ISSUE THREAD

**Issue by ctrlcctrlv** [rg3/youtube-dl#14845]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[osboxes@osboxes ATLAH Exposed Documentary]$ youtube-dl -v https://www.youtube.com/watch?v=wtvNDt1Q8S4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=wtvNDt1Q8S4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.6.3 - Linux-4.13.12-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[youtube] wtvNDt1Q8S4: Downloading webpage
[youtube] wtvNDt1Q8S4: Downloading video info webpage
[youtube] wtvNDt1Q8S4: Extracting video information
[youtube] wtvNDt1Q8S4: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r6---sn-jvhja5g3-hoas.googlevideo.com/videoplayback?id=c2dbcd0edd50f12e&itag=136&source=youtube&requiressl=yes&pl=22&ms=au&ei=wesYWvOfMoWa4wLhzLiQAg&initcwndbps=277500&mv=m&mn=sn-jvhja5g3-hoas&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=98009808&lmt=1415393875935032&dur=590.923&signature=61A118FB38E1391597FDABD451423675DDC1174F.75BA0BA305D88B333F6C980AD9B6A400D85D6B11&mt=1511582564&key=dg_yt0&ip=120.29.112.185&ipbits=0&expire=1511604257&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,ms,ei,initcwndbps,mv,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Resuming download at byte 96468256
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 1 of 10)...
[download] Resuming download at byte 96468256
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 10)...
[download] Resuming download at byte 96468256
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10)...
[download] Resuming download at byte 96468256
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 10)...
[download] Resuming download at byte 96468256
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 10)...
[download] Resuming download at byte 96468256
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10)...
[download] Resuming download at byte 96468256
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10)...
[download] Resuming download at byte 96468256
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10)...
[download] Resuming download at byte 96468256
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10)...
[download] Resuming download at byte 96468256
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10)...
[download] Resuming download at byte 96468256
ERROR: giving up after 10 retries
  File "/usr/bin/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl==2017.11.15', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.6/site-packages/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/usr/lib/python3.6/site-packages/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1986, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 795, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 849, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1620, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1887, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1832, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/http.py", line 297, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 163, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 612, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 574, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=wtvNDt1Q8S4

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information
I just want to make it known that I don't support what this man is saying, I'm using his footage under fair use to compose a documentary about him.

**Comment by dstftw** [comment]
Youtube side issue. Select other format.

**Comment by ctrlcctrlv** [comment]
Huh? If it's known sometimes that YouTube will report the incorrect size, why is this an error? Is it possible to ignore it when downloading?

**Comment by ctrlcctrlv** [comment]
@dstftw Your `not-a-bug` tag is false. There should be a way to ignore the size difference - perhaps that should even be the default.

**Comment by samehvarta** [comment]
use this command 
youtube-dl --prefer-ffmpeg  URL
