### ISSUE TITLE
ISM/Manifest or ISM/.MPD support.

### ISSUE THREAD

**Issue by diegofn** [rg3/youtube-dl#14859]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.26**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Can you help explain, how can I download a ISM/Manifest base video or ISM/.mpd video.
Currenlty I can't download the following link
[DASHFormat] https://couspdash2.clarovideo.com/multimediav81/plataforma_vod/MP4/201706/WMP4H35606MTCR_full/WMP4H35606MTCR_full_WV_DASH.ism/.mpd

[ISMFormat] http://couspss2.clarovideo.com/multimediav81/plataforma_vod/MP4/201706/WMP4H35606MTCR_full/WMP4H35606MTCR_full_SS.ism/Manifest

Thanks for your help

```
./youtube-dl  -f bestvideo+bestaudio --verbose http://couspss2.clarovideo.com/multimediav81/plataforma_vod/MP4/201301/WMP4H05748MTCR_full/WMP4H05748MTCR_full_SS.ism/Manifest
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'bestvideo+bestaudio', u'--verbose', u'http://couspss2.clarovideo.com/multimediav81/plataforma_vod/MP4/201301/WMP4H05748MTCR_full/WMP4H05748MTCR_full_SS.ism/Manifest']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.26
[debug] Python version 2.7.10 - Darwin-17.2.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] Manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Manifest: Downloading webpage
[generic] Manifest: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2188, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1067, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

**Comment by dstftw** [comment]
DRM protected videos are not supported.
