### ISSUE TITLE
[cda.pl]  Unable to extract default player_json & No video formats found

### ISSUE THREAD

**Issue by rewida17** [rg3/youtube-dl#14851]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```

PS C:\Program Files\mpv> .\youtube-dl.exe -vF https://www.cda.pl/video/17338600e
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vF', 'https://www.cda.pl/video/17338600e']
[debug] Encodings: locale cp1250, fs mbcs, out cp1250, pref cp1250
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: unable to extract default player_json; please report this issue on https://yt-dl.org/bug . Make sure you are us
ing the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include i
ts complete output.
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ve
rsion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 784,
in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", lin
e 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\cda.py", line 1
80, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", lin
e 1075, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure y
ou are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.

C:\Program Files\mpv>
```

---

**Comment by yan12125** [comment]
Works for me here
```
$ youtube-dl -vF "https://www.cda.pl/video/17338600e"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://www.cda.pl/video/17338600e']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.26
[debug] Python version 2.7.14 - Darwin-17.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[CDA] 17338600e: Downloading webpage
[CDA] 17338600e: Downloading 360p version information
[CDA] 17338600e: Downloading 720p version information
[CDA] 17338600e: Downloading 1080p version information
[info] Available formats for 17338600e:
format code  extension  resolution note
vl           mp4        360p
lq           mp4        480p
sd           mp4        720p
hd           mp4        1080p      (best)
```
Could you run ```youtube-dl -vF "https://www.cda.pl/video/17338600e" --write-pages``` and upload *.dump files?

**Comment by rewida17** [comment]
Sure, no problem :) 
1080- https://gist.github.com/rewida17/236666019d3e6fff06822fdcc21652bb
720-  https://gist.github.com/rewida17/6f1a7efc5bdf86b42887d247aab09825
360-  https://gist.github.com/rewida17/efaaf4614be658d6250111058ef45dba
"FullDump"  https://gist.github.com/rewida17/16f5ad15875f11ded860a71b7732c05c   

IHMO at this time this issue can be closed. Also i can`t reproduce  this bug :/
After that error I was checked this on Fedora machine, And this works correct. 
Sorry for wasting Your time...  Huge thanks for your great work.

**Comment by yan12125** [comment]
No problem! It's not unusual for a website to go crazy :)
