### ISSUE TITLE
merging with ffmpeg results in --output not fully controlling output filename

### ISSUE THREAD

**Issue by joeyh** [rg3/youtube-dl#14864]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When downloading youtube videos with a format that involves merging (including the default bestvideo+bestaudio), and when ffmpeg is used for the merge, --output does not fully control the filename that the merged video is written to. A ".mkv" extension is added to whatever filename --output would generate.

For example, -o out.vid results in:

    WARNING: Requested formats are incompatible for merge and will be merged into mkv.
    [ffmpeg] Merging formats into "out.vid.mkv"

--get-filename also does not print out the actual filename used in this case.

I was going to use --output to make youtube-dl output to a specific filename in a script; this behavior makes that not practical to do unless I also force the output format to -f best or something like that. 

(I have not checked if using avconv for merging also has this behavior.)

**Comment by yan12125** [comment]
This is a known issue #5710. Sadly currently there's no good solution.

**Comment by joeyh** [comment]
I can see the difficulty in making --get-filename work in this situation, but my bug report is primarily about --output not working. It seems to me that for --output, youtube-dl could simply rename the file ffmpeg generates to the filename the user requested.

So, it may be useful to reopen and treat #14864 and #7137 as two separate, though related bugs.

**Comment by yan12125** [comment]
> It seems to me that for --output, youtube-dl could simply rename the file ffmpeg generates to the filename the user requested.

It's not how --output actually works. Indeed its description can be better.

If --get-filename is fixed, your problem is solved, so I point the related issue.

**Comment by gabrielgrant** [comment]
I'm not sure I follow... it seems like that (making sure the final output is has the file specified filename) is how `--output` _should_ work, even if it doesn't today. In what circumstances would a user would not want the output contained in the location they've specified?
