### ISSUE TITLE
FIX --output path with spaces fails execution

### ISSUE THREAD

**Issue by allanlaal** [rg3/youtube-dl#14860]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.26**
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

## bug report:

downloading to a path that has a space " " in it fails execution:

-----------------

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--default-search', u'ytsearch', u'--no-mtime', u'--no-cache-dir', u'--no-call-home', u'--verbose', u'--ignore-errors', u'--continue', u'--output', u'/afs/Multimedia/Multimedia.SELF/SELF.video.bgmusic/not licensed/%(title)s.%(upload_date)s.[%(uploader)s].%(ext)s', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'--extract-audio', u'--add-metadata', u'']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.26
[debug] Python version 2.7.12 - Linux-4.10.0-30-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ytsearch:: Requesting header
WARNING: Could not send HEAD request to ytsearch:: <urlopen error unknown url type: ytsearch>
[generic] ytsearch:: Downloading webpage
ERROR: Unable to download webpage: <urlopen error unknown url type: ytsearch> (caused by URLError(u'unknown url type: ytsearch',))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 506, in _request_webpage
	return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2196, in urlopen
	return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
	response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 452, in _open
	'unknown_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
	result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1266, in unknown_open
	raise URLError('unknown url type: %s' % type)

-------------------

**Comment by yan12125** [comment]
> [debug] Command-line args: [u'-v', u'--default-search', u'ytsearch', u'--no-mtime', u'--no-cache-dir', u'--no-call-home', u'--verbose', u'--ignore-errors', u'--continue', u'--output', u'/afs/Multimedia/Multimedia.SELF/SELF.video.bgmusic/not licensed/%(title)s.%(upload_date)s.[%(uploader)s].%(ext)s', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'--extract-audio', u'--add-metadata', u'']

The actual cause is that you didn't specify what to download (see the last argument ```u''```). You may want to recheck your command.
