### ISSUE TITLE
[123video] Site support request

### ISSUE THREAD

**Issue by aruwin** [rg3/youtube-dl#14869]
I want to download videos from this website but I don't know the command line. Can anyone help? http://www.123video.tv/watch.php?vid=1f79ff262

**Comment by gkoelln** [comment]
https://github.com/rg3/youtube-dl#description

**Comment by aruwin** [comment]
I tried so many times but never worked.

youtube-dl-2016.10.12 -f full "http://www.123video.tv/watch.php?vid=1f79ff262" -o muhtesem-1080p.mp4
pause
:end

**Comment by gkoelln** [comment]
Unless you renamed the youtube-dl.exe, try:

`youtube-dl -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]" "http://www.123video.tv/watch.php?vid=1f79ff262" -o muhtesem-1080p.mp4`

**Comment by gkoelln** [comment]
Sorry--didn't bother to check if 123video.tv was supported, which it is currently not.

**Comment by aruwin** [comment]
How come? There should be a way to download from that site.

**Comment by remitamine** [comment]
streams stolen from shahid.net, you can simply download from the original website(https://shahid.mbc.net/ar/series/%D8%A3%D9%86%D8%AA-%D9%88%D8%B7%D9%86%D9%8A-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-2/episode-284456).

**Comment by aruwin** [comment]
Don't close it because it's not solved.
That website is not available in my country.

**Comment by remitamine** [comment]
https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free
