### ISSUE TITLE
One minute videos from Safaribooksonline.com

### ISSUE THREAD

**Issue by obeid** [rg3/youtube-dl#14863]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.26**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.26
[debug] Python version 2.7.13 - Darwin-15.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.1, ffprobe 3.3.1
[debug] Proxy map: {}
...
<end of log>
```

I have noticed that any video I download is limited to exactly one minute. I use a .netrc for credentials. I know credentials will be needed to reproduce the issue, is there a way to share this safely? There's a closed [issue](https://github.com/rg3/youtube-dl/issues/13288) but it's closed and limited to collaborators and I couldn't see whether the issue was resolved or not.

**Comment by remitamine** [comment]
most likely you're not using `--netrc` option or you're not setting the credentials with `safari` netrc machine, otherwise you will have to include full verbose log off the command you're using.

**Comment by obeid** [comment]
Thanks, that fixed it. Is there anyway I can config youtube-dl to do that by default.

**Comment by remitamine** [comment]
https://github.com/rg3/youtube-dl#configuration
