### ISSUE TITLE
ERROR: Did not get any data blocks

### ISSUE THREAD

**Issue by olspookishmagus** [rg3/youtube-dl#14866]
$ youtube-dl -v -f 22 MOSrkm0r-Co
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: [u'-v', u'-f', u'22', u'MOSrkm0r-Co']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2017.11.26
    [debug] Python version 2.7.14 - Linux-4.9.0-4-amd64-x86_64-with-debian-buster-sid
    [debug] exe versions: avconv 3.4-3, avprobe 3.4-3, ffmpeg 3.4-3, ffprobe 3.4-3, phantomjs ., rtmpdump 2.4
    [debug] Proxy map: {}
    [youtube] MOSrkm0r-Co: Downloading webpage
    [youtube] MOSrkm0r-Co: Downloading video info webpage
    [youtube] MOSrkm0r-Co: Extracting video information
    [youtube] MOSrkm0r-Co: Downloading MPD manifest
    [debug] Invoking downloader on u'https://r3---sn-vuxbavcx-5ui6.googlevideo.com/videoplayback?requiressl=yes&itag=22&expire=1511876115&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mt=1511854426&ei=sxEdWt-YBpPYcY3lvZgN&ipbits=0&pl=16&ratebypass=yes&mv=m&source=youtube&ms=au&lmt=1501153749248515&key=yt6&ip=79.130.225.134&initcwndbps=527500&dur=1311.950&mn=sn-vuxbavcx-5ui6&mm=31&signature=85257B1DBD3675168329572A24713AA739FA1E92.C6FF00EC778E9A175552DE950B07183B0C683DD1&mime=video%2Fmp4&id=o-ACazqzfriVUmiPBLvcQObHx68UwDWv3C2CVFf4JtwE4K'
    [download] Destination: GO KART - PART 3-MOSrkm0r-Co.mp4
    [download]   0.5% of 127.70MiB at 801.98KiB/s ETA 02:42[download] Got server HTTP error: Downloaded 699597 bytes, expected 133904075 bytes. Retrying (attempt 1 of 10)...
    [download] Resuming download at byte 699597
    
    
    ERROR: Did not get any data blocks
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 287, in real_download
        download()
      File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 265, in download
        retry(err)
      File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 175, in retry
        raise RetryDownload(e)
    RetryDownload
    
    $ youtube-dl -v -f 22 MOSrkm0r-Co
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: [u'-v', u'-f', u'22', u'MOSrkm0r-Co']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2017.11.26
    [debug] Python version 2.7.14 - Linux-4.9.0-4-amd64-x86_64-with-debian-buster-sid
    [debug] exe versions: avconv 3.4-3, avprobe 3.4-3, ffmpeg 3.4-3, ffprobe 3.4-3, phantomjs ., rtmpdump 2.4
    [debug] Proxy map: {}
    [youtube] MOSrkm0r-Co: Downloading webpage
    [youtube] MOSrkm0r-Co: Downloading video info webpage
    [youtube] MOSrkm0r-Co: Extracting video information
    [youtube] MOSrkm0r-Co: Downloading MPD manifest
    [debug] Invoking downloader on u'https://r3---sn-vuxbavcx-5ui6.googlevideo.com/videoplayback?dur=1311.950&pl=16&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&source=youtube&initcwndbps=508750&mv=m&ms=au&key=yt6&signature=B97A30FFE8C8904FD0A5DB077B00CEDCED53691F.77B7A01F81D609E7D2E739E475092ED884FB17DE&mn=sn-vuxbavcx-5ui6&itag=22&mm=31&mime=video%2Fmp4&id=o-ANe2LRMn3YEPbQC2n0i6iartoy6J9UVwRinuQeZxHLKY&expire=1511876213&ipbits=0&ip=79.130.225.134&lmt=1501153749248515&requiressl=yes&ratebypass=yes&mt=1511854530&ei=FRIdWtewCZjgcbXtrdgF'
    [download] Resuming download at byte 699597
    
    
    ERROR: Did not get any data blocks
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
        youtube_dl.main()
      File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
        _real_main(argv)
      File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
        retcode = ydl.download(all_urls)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1986, in download
        url, force_generic_extractor=self.params.get('force_generic_extractor', False))
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 795, in extract_info
        return self.process_ie_result(ie_result, download, extra_info)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 849, in process_ie_result
        return self.process_video_result(ie_result, download=download)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1620, in process_video_result
        self.process_info(new_info)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1893, in process_info
        success = dl(filename, info_dict)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1832, in dl
        return fd.download(name, info)
      File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
        return self.real_download(filename, info_dict)
      File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 287, in real_download
        download()
      File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 257, in download
        self.report_error('Did not get any data blocks')
      File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 163, in report_error
        self.ydl.report_error(*args, **kargs)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 612, in report_error
        self.trouble(error_message, tb)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 574, in trouble
        tb_data = traceback.format_list(traceback.extract_stack())

And unfortunately I don't have another similar case to showcase.

Also, FYI:

    $ python --version
    Python 2.7.14
    $ uname -a
    Linux thingamajig 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

Last and not least, thanks in advance to whoever puts time and energy on this.

**Comment by olspookishmagus** [comment]
Video will download OK when asking for _-f 18_ or _-f '136+140'_.

    $ youtube-dl -F MOSrkm0r-Co
    [youtube] MOSrkm0r-Co: Downloading webpage
    [youtube] MOSrkm0r-Co: Downloading video info webpage
    [youtube] MOSrkm0r-Co: Extracting video information
    [youtube] MOSrkm0r-Co: Downloading MPD manifest
    [info] Available formats for MOSrkm0r-Co:
    format code  extension  resolution note
    139          m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.5@ 48k (22050Hz), 7.44MiB
    249          webm       audio only DASH audio  102k , opus @ 50k, 8.56MiB
    171          webm       audio only DASH audio  124k , vorbis@128k, 16.45MiB
    140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k (44100Hz), 19.87MiB
    250          webm       audio only DASH audio  131k , opus @ 70k, 12.77MiB
    251          webm       audio only DASH audio  231k , opus @160k, 23.90MiB
    160          mp4        256x144    DASH video  114k , avc1.4d400c, 24fps, video only, 9.55MiB
    278          webm       256x144    144p  120k , webm container, vp9, 24fps, video only, 11.84MiB
    242          webm       426x240    240p  242k , vp9, 24fps, video only, 19.30MiB
    133          mp4        426x240    DASH video  255k , avc1.4d4015, 24fps, video only, 20.17MiB
    243          webm       640x360    360p  452k , vp9, 24fps, video only, 35.38MiB
    134          mp4        640x360    DASH video  644k , avc1.4d401e, 24fps, video only, 36.26MiB
    244          webm       854x480    480p  818k , vp9, 24fps, video only, 57.74MiB
    135          mp4        854x480    DASH video 1178k , avc1.4d401e, 24fps, video only, 70.03MiB
    247          webm       1280x720   720p 1619k , vp9, 24fps, video only, 118.41MiB
    136          mp4        1280x720   DASH video 2362k , avc1.4d401f, 24fps, video only, 137.39MiB
    248          webm       1920x1080  1080p 2922k , vp9, 24fps, video only, 254.20MiB
    137          mp4        1920x1080  DASH video 4424k , avc1.640028, 24fps, video only, 414.62MiB
    17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
    36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
    43           webm       640x360    medium , vp8.0, vorbis@128k
    18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
    22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)

**Comment by dstftw** [comment]
Format 22 is not available at Youtube side.

**Comment by sikro94** [comment]
Hello! Same issue there with this link : https://m.youtube.com/watch?v=qBT8t13Cdik

However, with youtube-dl -F, the 22 format is very present. If I try to put youtube-dl -f 22/18 https://m.youtube.com/watch?v=qBT8t13Cdik - it displays the error and does not try to download the 18 format that works well for it.

Is it possible to fix this to make sure that in case of error, the command tries with the format 18?

Thank you.

**Comment by sikro94** [comment]
> Format 22 is not available at Youtube side.

Hello! Same issue there with this link : https://m.youtube.com/watch?v=qBT8t13Cdik

However, with youtube-dl -F, the 22 format is very present. If I try to put youtube-dl -f 22/18 https://m.youtube.com/watch?v=qBT8t13Cdik - it displays the error and does not try to download the 18 format that works well for it.

Is it possible to fix this to make sure that in case of error, the command tries with the format 18?

Thank you.
