### ISSUE TITLE
unsupported url:http://v.youku.com/v_show/id_XMzE4NjQ1MTc1Mg.html

### ISSUE THREAD

**Issue by liukunyu** [rg3/youtube-dl#14872]
➜  youku youtube-dl -U       
youtube-dl is up-to-date (2017.11.26)

➜  youku youtube-dl --version                                           
2017.11.26

➜  youku youtube-dl -v http://v.youku.com/v_show/id_XMzE4NjQ1MTc1Mg.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://v.youku.com/v_show/id_XMzE4NjQ1MTc1Mg.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.26
[debug] Python version 2.7.12 - Linux-4.4.0-100-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youku] XMzE4NjQ1MTc1Mg: Retrieving cna info
[youku] XMzE4NjQ1MTc1Mg: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "youtube-dl/youtube_dl/extractor/youku.py", line 189, in _real_extract
    raise ExtractorError(msg)
ExtractorError: Youku server reported error -6004: \u5ba2\u6237\u7aef\u65e0\u6743\u64ad\u653e,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dream4today18888** [comment]
i also have the same question,want to cry.
