### ISSUE TITLE
im newbie and want to learn . cant download subtitle in openload

### ISSUE THREAD

**Issue by ryananugerah** [rg3/youtube-dl#14877]
so i want to download subtitle from openload embed url 
adult movie this the link 
https://openload.co/embed/qM3boxXrsVk

i cant find any subtitle link in there . how do i get it ? 
i think this link the subtitle for thats video , but it just showing WEBVTT

https://thumb.openload.co//externsub//1512084283~49.213.0.0~6izGKgz-

how to get the subtitle for this issue ? help please . i always check wait your reply . thank you

**Comment by dstftw** [comment]
Subtitles are burnt into the video. There are no separate subtitles.
