### ISSUE TITLE
[nick] ERROR: Unable to extract mgid

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#14876]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.26**
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\rumag\youtube-dl>youtube-dl.exe -f best --all-subs http://www.nick.com/tiny-christmas/videos/digital-short-calling-for-help/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', 'http://www.nick.com/tiny-christmas/videos/digital-short-calling-for-help/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.11.26
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86911-gb664d1f, ffprobe N-86911-gb664d1f
[debug] Proxy map: {}
[debug] Using fake IP 3.155.205.245 (US) as X-Forwarded-For.
[nick.com] digital-short-calling-for-help: Downloading webpage
ERROR: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\extractor\mtv.py", line 278, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\extractor\nick.py", line 73, in _extract_mgid
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\extractor\common.py", line 792, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

- Single video: http://www.nick.com/tiny-christmas/videos/digital-short-calling-for-help/ (not working)
- Single video: http://www.nick.com/adventures-of-kid-danger/videos/101-clip-popcorn-monster/ (working)

---

### Description of your *issue*
The video will not download. But the other video will.

**Comment by AFFerson** [comment]
I've been having the same problem with Tiny Christmas videos and the movie.
 http://www.nick.com/tiny-christmas/videos/tiny-christmas-Movie-full-episode/
It's been a problem with movies in general, where some download and some don't.

**Comment by asbhn** [comment]
I'm having the same issue right now, any idea how to fix it?

**Comment by RuneMagle** [comment]
It has been fixed now.
