### ISSUE TITLE
Need help, I suddenly can't visit any video http://v.youku.com from Yesterday,please solve it .

### ISSUE THREAD

**Issue by dream4today18888** [rg3/youtube-dl#14880]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ √] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.26**
version as follow:
youtube-dl --version
2017.11.26

### Before submitting an *issue* make sure you have:
- [√ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ √] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
question as follows:
 ****/usr/local/bin/youtube-dl   -i --skip-download  "http://v.youku.com/v_show/id_XMTQ4OTI5NTQ4NA==.html"  --list-formats --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', '--skip-download', 'http://v.youku.com/v_show/id_XMTQ4OTI5NTQ4NA==.html', '--list-formats', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.26
[debug] Python version 3.6.0 - Linux-3.10.0-327.22.2.el7.x86_64-x86_64-with-centos-7.2.1511-Core
[debug] exe versions: none
[debug] Proxy map: {}
[youku] XMTQ4OTI5NTQ4NA: Retrieving cna info
[youku] XMTQ4OTI5NTQ4NA: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youku.py", line 189, in _real_extract
    raise ExtractorError(msg)
youtube_dl.utils.ExtractorError: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.****

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.11.26
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dream4today18888** [comment]
other people have the same question.how to solve it!!!!!!

**Comment by zcanfly** [comment]
I have solution by change 'ccode' with 0501 in new version code youku.py line 157. I have pull request  the change file.

**Comment by dream4today18888** [comment]
when you  give me the correct version???

**Comment by 73696464687435** [comment]
@dream4today18888    @zcanfly  means to say he has already pull requested for the change by changing https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youku.py#L157   from  `ccode': '0502',`     to  ccode': '0501'.    which will only be merged by the collaborators/author of youtube-dl project.

If you want it asap  then you may need to manually change the code in your system by changing   the line number 157 from  youtube_dl/extractor/youku.py. 

But you have to wait till the code arrives

**Comment by westspy** [comment]
ccode=0501, can't download the full file. The downloaded video length is 10 minutes only.

**Comment by dream4today18888** [comment]
please quick release the newest version to solve this bug.

**Comment by CoXier** [comment]
Same question. +1

**Comment by CoXier** [comment]
@dstftw Why do you close this issue? The latest version still has this bug.
