### ISSUE TITLE
False username missing error when downloading from Lynda.com

### ISSUE THREAD

**Issue by codewizard13** [rg3/youtube-dl#14889]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '--username', 'PRIVATE', '--password', 'PRIVATE', '%(uploader)s/%(playlist)s/(Lynda) %(playlist)s - %(playlist_index)s - %(title)s.%(ext)s', 'https://www.lynda.com/MySQL-tutorials/PHP-MySQL-Essential-Training/119003-2.html', '-v']
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

## SYSTEM

* Windows 10 64-bit
* CMD (cmd.exe)
* youtube-dl 2017.11.26

## ISSUE

Yesterday I downloaded youtube-dl and spent some time learning the command line switches and output templates. I was very happy that downloading YouTube playlists was a cinch, so I decided to see if it would work for downloading Lynda.com courses, which are essentially video playlists.

I have a personal (not corporate or 'organizational') Lynda account and was very happy to see that I was able to successfully download Lynda.com videos ... That is until I realized that it only downloaded 18 of 132 videos :(

But, there was still a bright side. The youtube-dl command line (Windows 10 CMD) output gave me this "Warning" message:

> WARNING: 114 videos are only available for members (or paid members) and will not be downloaded. Use --username and --password options to provide lynda.com account credentials."

I researched the documentation [here](https://github.com/rg3/youtube-dl/blob/master/README.md#readme) to find out examples of how to implement --username and --password. On this aspect the readme was very sparse. This is the extent of the what the help document had to say about providing credentials:

> Authentication Options:
> -u, --username USERNAME          Login with this account ID
> -p, --password PASSWORD          Account password. If this option is left
>                                  out, youtube-dl will ask interactively.
> -2, --twofactor TWOFACTOR        Two-factor authentication code
> -n, --netrc                      Use .netrc authentication data
> --video-password PASSWORD        Video password (vimeo, smotri, youku)

As a test, this is an example playlist I used:

* https://www.lynda.com/MySQL-tutorials/PHP-MySQL-Essential-Training/119003-2.html

I then tried to use this command, incorporating the --username and --password switches (the actual username and password have been changed for posting):

```batchfile
youtube-dl -o --username something@gmail.com --password private.something "%(uploader)s/%(playlist)s/(Lynda) %(playlist)s - %(playlist_index)s - %(title)s.%(ext)s" https://www.lynda.com/MySQL-tutorials/PHP-MySQL-Essential-Training/119003-2.html
```
But, it was to no avail. Though I no longer get "members only" warning, now I get an error that says:

> Usage: youtube-dl [OPTIONS] URL [URL...]
>
> youtube-dl: error: account username missing

Huh? WTF? What do you mean missing?? Obviously, I have indeed included the account username (my email) in the options before the URL, as indicated in the usage. So, what is going on here?? Why am I getting this seemingly false and invalid error message?

## LINKS THAT I'VE RESEARCHED BUT THAT HAVE NOT SOLVED THE ISSUE

After carefully reading all the helpful check-offs and boilerplate messages before composing my post, I followed the advice given and searched through the links provided for help, to little avail. Following are the links I found useful. Unfortunately, the two that appeared most promising were closed prematurely or never followed-up on by the poster. Some were about "organization logins" (which I can only assume means like your company subscribes to Lynda and you use the company login?), which doesn't apply to my situation, but I read them anyway to see if I could glean anything useful. All found was references to a solution that was supposed to work with "cookies", but didn't. I also referred to the Vimeo links that looked like they might offer some insight:

### GitHub Posts

* https://gist.github.com/DonRichards/6c3f4d553c2384eca87b6dfc9f5c5826
* https://github.com/rg3/youtube-dl/issues/5926
* https://github.com/rg3/youtube-dl/blob/master/README.md#readme
* https://github.com/rg3/youtube-dl#bugs
* https://github.com/rg3/youtube-dl#faq
* https://github.com/rg3/youtube-dl/issues/769
* https://github.com/rg3/youtube-dl/pull/889

### Non-GitHub Posts

NOTE: Many of these links recommend using youtube-dl

* https://melearningweb.wordpress.com/2015/08/19/how-to-download-entire-lynda-com-courses-in-one-go/
* https://stackoverflow.com/questions/28377271/youtube-dl-with-lynda-com-through-organization-login
* https://www.quora.com/How-can-I-download-videos-from-lynda
* https://www.npmjs.com/package/lynda-dl
* https://www.drgeeky.com/download-lynda-video-courses-free-computer/
* https://www.reddit.com/r/DataHoarder/comments/6ucad8/youtubedl_lynda_output_template/
* https://github.com/EnesCakir/lynder

## MY QUESTIONS

1. WHY AM I GETTING AN ERROR SAYING USERNAME IS MISSING WHEN IT ISN'T?

1. How can I download the complete video set for a Lynda.com course using youtube-dl?

Any help is appreciated.

**Comment by remitamine** [comment]
you're command line is incorrect, the `-o` should be followed by an output template:
`youtube-dl --username "something@gmail.com" --password "private.something" -o "%(uploader)s/%(playlist)s/(Lynda) %(playlist)s - %(playlist_index)s - %(title)s.%(ext)s" https://www.lynda.com/MySQL-tutorials/PHP-MySQL-Essential-Training/119003-2.html`

**Comment by codewizard13** [comment]
Thanks @remitamine! I am replying confirming that your reworking of the command I was using was indeed successful. Thanks so much for your help.
