### ISSUE TITLE
Youtube-dl output

### ISSUE THREAD

**Issue by Onvoldoende** [rg3/youtube-dl#14898]
Is it possible to eddit the output that youtube-dl does?
Right now I get the following output:
![image](https://user-images.githubusercontent.com/33862280/33524919-92df31c0-d825-11e7-811e-9d94d4ee8121.png)
And I just want something more clean so only output is the title name from the link.
I noticed I can do that with --get-title but then the song wont download.

**Comment by dstftw** [comment]
Write a wrapper that will parse `--print-json` and output whatever you need.
