### ISSUE TITLE
NickJr.com.br 

### ISSUE THREAD

**Issue by jeffsnow88** [rg3/youtube-dl#14893]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.26**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v http://www.nickjr.com.br/patrulha-canina/videos/210-labirinto-de-pipoca/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.nickjr.com.br/patrulha-canina/videos/210-labirinto-de-pipoca/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.11.26
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-82225-gb4e9252, ffprobe N-82225-gb4e9252
[debug] Proxy map: {}
[generic] 210-labirinto-de-pipoca: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 210-labirinto-de-pipoca: Downloading webpage
[generic] 210-labirinto-de-pipoca: Extracting information
ERROR: Unsupported URL: http://www.nickjr.com.br/patrulha-canina/videos/210-labirinto-de-pipoca/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\extractor\generic.py", line 3088, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.nickjr.com.br/patrulha-canina/videos/210-labirinto-de-pipoca/
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
Example urls:

http://www.nickjr.com.br/patrulha-canina/videos/210-labirinto-de-pipoca/
http://www.nickjr.com.br/patrulha-canina/videos/225-o-show-de-abertura/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I saw some issues around nickjr, and by reading the entire issue, I understand that the newest version support nickjr, however, I'm facing some challenges. Thank you.

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by hlarsen** [comment]
i'm seeing the same.

> WARNING: Falling back on generic information extractor.

i'm guessing the nickjr extractor matches on nickjr.com, not nickjr.com.br. just from the url i'd guess it would work, but i don't see any way to force select an extractor like we can force the generic one.

**Comment by jeffsnow88** [comment]
Makes sense. Maybe nickjr.com.br can be incorporated? :)

**Comment by ggorelik20** [comment]
Can we get this same fix for nick latin-america?
I'm trying to download this video and it does not recognize nick because of a different hostname:
http://la.nickjr.tv/blaze-and-the-monster-machines/videos/animal-island/
