### ISSUE TITLE
Play audio and video files together without creating muxed files

### ISSUE THREAD

**Issue by fkbreitl** [rg3/youtube-dl#14907]
It could be argued that strictly speaking this is not an issue of youtube-dl.
However it is deeply related and many people might encounter this issue with youtube-dl first.

It makes a lot of sense to separate the audio from the video and store it in separate files for example for audio only players.

However, to my surprise I wasn't able to find any players that could play directories with those files as a muxed video stream. The general solution for this problem seems to created a muxed file first, which has the disadvantage of doubling the data.

I am wondering if any solution for playing those files without merged / muxed files already exists.

**Comment by dstftw** [comment]
Out of scope.
