### ISSUE TITLE
ExtractorError: requested format not available;

### ISSUE THREAD

**Issue by HNIW** [rg3/youtube-dl#1491]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.youtube.com/playlist?list=PLCA944605A8EDE42A', '-c', '-f', '18', '-o', '%(title)s.%(ext)s', '--restrict-filenames', '--verbose']
[debug] youtube-dl version 2013.09.20.1
[debug] Python version 2.7.4 - Linux-3.8.0-25-generic-x86_64-with-LinuxMint-15-olivia
[debug] Proxy map: {}
[youtube:playlist] PLCA944605A8EDE42A: Downloading page #1
[youtube:playlist] PLCA944605A8EDE42A: Downloading page #2
[download] Downloading playlist: Core Science - Numerical Methods and Programing
[youtube:playlist] playlist 'Core Science - Numerical Methods and Programing': Collected 38 video ids (downloading 38 of them)
[download] Downloading video #1 of 38
[youtube] Setting language
[youtube] zjyR9e-N1D4: Downloading video webpage
[youtube] zjyR9e-N1D4: Downloading video info webpage
[youtube] zjyR9e-N1D4: Extracting video information
[download] Lecture_1_-_Programing_Basics.mp4 has already been downloaded
[download] Downloading video #2 of 38
[youtube] 7-EppTJK7WQ: Downloading video webpage
[youtube] 7-EppTJK7WQ: Downloading video info webpage
[youtube] 7-EppTJK7WQ: Extracting video information
[download] Lecture_2_-_Introduction_to_Pointers.mp4 has already been downloaded
[download] Downloading video #3 of 38
[youtube] mKrwrQMT0a4: Downloading video webpage
[youtube] mKrwrQMT0a4: Downloading video info webpage
[youtube] mKrwrQMT0a4: Extracting video information
[download] Lecture_3_-_Pointers_And_Arrays.mp4 has already been downloaded
[download] Downloading video #4 of 38
[youtube] i6ifjE45CSU: Downloading video webpage
[youtube] i6ifjE45CSU: Downloading video info webpage
[youtube] i6ifjE45CSU: Extracting video information
[download] Lecture_4_-_External_Functions_and_Argument_Passing.mp4 has already been downloaded
[download] Downloading video #5 of 38
[youtube] UawUYuNSH4o: Downloading video webpage
[youtube] UawUYuNSH4o: Downloading video info webpage
[youtube] UawUYuNSH4o: Extracting video information
[download] Lecture_5_-_Representation_of_Numbers.mp4 has already been downloaded
[download] Downloading video #6 of 38
[youtube] HJjbEOsOl6E: Downloading video webpage
[youtube] HJjbEOsOl6E: Downloading video info webpage
[youtube] HJjbEOsOl6E: Extracting video information
[download] Lecture_6_-_Numerical_Error.mp4 has already been downloaded
[download] Downloading video #7 of 38
[youtube] i3VlTw6JazM: Downloading video webpage
[youtube] i3VlTw6JazM: Downloading video info webpage
[youtube] i3VlTw6JazM: Extracting video information
[download] Lecture_7_-_Error_Propagation_and_Stability.mp4 has already been downloaded
[download] Downloading video #8 of 38
[youtube] sDn5cc-8gHY: Downloading video webpage
[youtube] sDn5cc-8gHY: Downloading video info webpage
[youtube] sDn5cc-8gHY: Extracting video information
[download] Lecture_8_-_Polynomial_Interpolation-1.mp4 has already been downloaded
[download] Downloading video #9 of 38
[youtube] ZG_TgdyDrf0: Downloading video webpage
[youtube] ZG_TgdyDrf0: Downloading video info webpage
[youtube] ZG_TgdyDrf0: Extracting video information
[download] Lecture_9_-_Polynomial_Interpolation-2.mp4 has already been downloaded
[download] Downloading video #10 of 38
[youtube] s31nOF09FnM: Downloading video webpage
[youtube] s31nOF09FnM: Downloading video info webpage
[youtube] s31nOF09FnM: Extracting video information
ERROR: requested format not available; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 321, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 103, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 806, in _real_extract
    video_url_list = self._get_video_url_list(url_map)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 595, in _get_video_url_list
    raise ExtractorError(u'requested format not available')
ExtractorError: requested format not available; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by jaimeMF** [comment]
youtube-dl raises an error if it can't find the format you requested, you can use `-f 18/best`, which will download the default format if `18` is not available, or `--ignore-errors`, which will skip the video.
