### ISSUE TITLE
Question: how to record ongoing livestream? and how to download entire channel including livestream?

### ISSUE THREAD

**Issue by gabriellluz** [rg3/youtube-dl#14925]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.02**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Hi, I'd like to know how to download Livestream from a specific channel. That specific channel keeps livestream once everyday. What I need to know is how to download all the livestreams from that specific channel. 

Example:
Day 1: Livestream about monkeys have started and another livestream about alligators have started too. How to download both of them without typing their IDs. I'd like to input only the channel ID and then download all the running livestreams using the same command (maybe opening multiple instances).

If I use the command to download the whole channel, will it download the live streams too?
It'll be useful for me because I'll make Eventghost run a bat to download all the channel videos just skipping the already download ones.

**Comment by dstftw** [comment]
Short, you can't download livestreams simultaneously without running separate instances of youtube-dl per video id.
