### ISSUE TITLE
vk:wallpost downloads sound files with notification.

### ISSUE THREAD

**Issue by linuxenko** [rg3/youtube-dl#14936]
It is about audio files downloading from `vk`. I've downloaded entire wallpost with a bunch of audio files, its names and number of files is correct, looks very cool, but (!)

I noticed the size of the downloaded files is the same:

```
431K ....
431K ....
431K ....
```

Every downloaded track, is about 20 seconds long and contains notification (voice) -  "you are using wrong audio listening program" or something like this.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
