### ISSUE TITLE
Option to limit number of pages to download in a playlist

### ISSUE THREAD

**Issue by Bosturk** [rg3/youtube-dl#14948]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

My request has already been requested, or a very similar one, at least: https://github.com/rg3/youtube-dl/issues/11181
I have a youtube playlist (liked videos) containing over 1200 videos. I continuously download and convert this playlist. It's 12 pages long now, and gathering the data from 12 pages every time, takes quite a while, and because I already know the "new" videos aren't more than a page, I would like for my search for new videos (not already in my downloaded.txt download archive), to only look for videos on the first, or specified amount of pages.

This is a quality of life request, and I know it's not vital, but it would be a brilliant addition.

Thanks

**Comment by dstftw** [comment]
```
--playlist-start NUMBER          Playlist video to start at (default is 1)
--playlist-end NUMBER            Playlist video to end at (default is last)
--playlist-items ITEM_SPEC       Playlist video items to download. Specify
                                 indices of the videos in the playlist
                                 separated by commas like: "--playlist-items
                                 1,2,5,8" if you want to download videos
                                 indexed 1, 2, 5, 8 in the playlist. You can
                                 specify range: "--playlist-items
                                 1-3,7,10-13", it will download the videos
                                 at index 1, 2, 3, 7, 10, 11, 12 and 13.
```

**Comment by Bosturk** [comment]
Hi Sergey,

Terribly sorry. I had looked for the option, and when I saw this other
issue on open, I thought it had not been implemented.

Forgive my ignorance.

**Comment by sijanec** [comment]
I have kind of the same issue on 2020.03.24. When I am downloading and infinite-length playlist by youtube, such as generated mixes (My Mix), the output just contains
```
[youtube:playlist] RDacL3C_cKeQ0: Downloading page 1 of Youtube mix
[youtube:playlist] RDacL3C_cKeQ0: Downloading page 2 of Youtube mix
[youtube:playlist] RDacL3C_cKeQ0: Downloading page 3 of Youtube mix
[youtube:playlist] RDacL3C_cKeQ0: Downloading page 4 of Youtube mix
[youtube:playlist] RDacL3C_cKeQ0: Downloading page 5 of Youtube mix
[youtube:playlist] RDacL3C_cKeQ0: Downloading page 6 of Youtube mix
[youtube:playlist] RDacL3C_cKeQ0: Downloading page 7 of Youtube mix
[youtube:playlist] RDacL3C_cKeQ0: Downloading page 8 of Youtube mix
[youtube:playlist] RDacL3C_cKeQ0: Downloading page 9 of Youtube mix
[youtube:playlist] RDacL3C_cKeQ0: Downloading page 10 of Youtube mix
[youtube:playlist] RDacL3C_cKeQ0: Downloading page 11 of Youtube mix
```
and the pages never load.

A feature to limit the number of pages would be greatly appreciated.
