### ISSUE TITLE
3sat - download fail - how to fix this ?

### ISSUE THREAD

**Issue by ds2k5** [rg3/youtube-dl#14958]
Hello,
try to download a Video from: 3sat.de but this fail

root@k1:~# ./youtube-dl --version
2017.12.10
root@k1:~# ./youtube-dl https://www.3sat.de/page/?source=/dokumentationen/195096/index.html
[generic] index: Requesting header
WARNING: Falling back on generic information extractor.
[generic] index: Downloading webpage
[generic] index: Extracting information
ERROR: Unsupported URL: https://www.3sat.de/page/?source=/dokumentationen/195096/index.html

root@k1:~# ./youtube-dl -v https://www.3sat.de/page/?source=/dokumentationen/195096/index.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.3sat.de/page/?source=/dokumentationen/195096/index.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.10
[debug] Python version 2.7.14+ - Linux-4.14.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
[debug] exe versions: ffmpeg 3.4-4, ffprobe 3.4-4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] index: Requesting header
WARNING: Falling back on generic information extractor.
[generic] index: Downloading webpage
[generic] index: Extracting information
ERROR: Unsupported URL: https://www.3sat.de/page/?source=/dokumentationen/195096/index.html
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2163, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: undefined entity &nbsp;: line 70, column 2225
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3063, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.3sat.de/page/?source=/dokumentationen/195096/index.html

**Comment by helb** [comment]
Because there is no actual video on the page, just a picture that links to the videoplayer page. If you click on said picture, a new tab/window will open with https://www.3sat.de/mediathek/?mode=play&obj=70466 – and that URL works in youtube_dl.

The *dreisat* extractor supports just these `…/mediathek/…` URLs: https://github.com/rg3/youtube-dl/blob/b2727d0bee61de8ea6ca0b67ba162abacea15233/youtube_dl/extractor/dreisat.py#L19

**Comment by ds2k5** [comment]
Thanks very much. it works

1. on the picture, copy link location
2. youtube-dl "https://www.3sat.de/webtv/?171211_unbekanntes_korsika_online.rm"

dreisat.py did not work for me

**Comment by helb** [comment]
I'm glad it helped.

That `dreisat.py` is just the "plugin" youtube_dl uses for 3sat.de, it's not meant to be run separately…
