### ISSUE TITLE
how to rename file during download

### ISSUE THREAD

**Issue by meth984** [rg3/youtube-dl#14959]
can explain me how to setting youtube-dl for renaming the video during download?
for example:
001-title.ext
002-title-ext
etc etc

i'm using ubuntu 16 whit this string:
  youtube-dl  --username <email> --password <your password> -w --no-overwrites <course url udemx>

thanks a lot

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#output-template

**Comment by meth984** [comment]
i've tryed but dsn't work. Can write me an example?

**Comment by meth984** [comment]
why you have closed if i don't have solve the problem?

**Comment by meth984** [comment]
i hope can help some one..... sorry for my english :-P

`youtube-dl -u username -p password -w --no-overwrites -o '%(autonumber)03d.%(title)s.%(ext)s' https://udemycourseaddress...`
> Create a folder where you want to downalod the course, and go inside with CD command. put the string and all the video will be download with numeric sequenze from 001 to 999

`youtube-dl -u username -p password -w --no-overwrites -o '~/Videos/%(playlist)s/%(chapter_number)03d - %(chapter)s/%(autonumber)03d.%(title)s.%(ext)s' https://udemycourseaddress...`
> All the videos will be download inside the Videos linux directory (from home), subdivided into squentially enumerated chapters folder and videos from 001-999

`youtube-dl -u username -p password -w --no-overwrites -o '%(playlist)s/%(chapter_number)03d - %(chapter)s/%(autonumber)03d.%(title)s.%(ext)s' https://udemycourseaddress...`
> Create a folder where you want to downalod the course, and go inside with CD command. Put the string and all the videos will be download squentially enumerated in subdivided chapters folder from 001-999
