### ISSUE TITLE
Bug report (https and parsing problem)

### ISSUE THREAD

**Issue by shadowfolder** [rg3/youtube-dl#14956]
youtube-dl can't parse all url, he sending only http://content.uplynk.com/1.m3u8 request while youtube-dl need send url with all parameters like this https://content.uplynk.com/1.m3u8?cid=1&oid=2&exp=1&rn=1&tc=1&ct=a&sig=1

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
