### ISSUE TITLE
Getting "No video formats found" when downloading a UDemy video

### ISSUE THREAD

**Issue by bobbytito** [rg3/youtube-dl#14965]
$ youtube-dl -v fidel@agbobu.com https://www.udemy.com/projects-in-laravel-learn-laravel-building-10-projects/learn/v4/content
[udemy:course] Downloading login popup
[udemy:course] Logging in as fidel@agbobu.com
[udemy:course] projects-in-laravel-learn-laravel-building-10-projects: Downloading webpage
[udemy:course] 1250824: Downloading course curriculum
[download] Downloading playlist: Projects in Laravel: Learn Laravel Building 10 Projects
[udemy:course] playlist Projects in Laravel: Learn Laravel Building 10 Projects: Collected 70 video ids (downloading 70 of them)
[download] Downloading video 1 of 70
[udemy] Downloading login popup
[udemy] 7271102: Downloading webpage
[udemy] 7271102: Downloading lecture JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You must either provide account credentials or non-paid reproducible example URL.

**Comment by dstftw** [comment]
Also provide complete verbose log.
