### ISSUE TITLE
[vk] Unable to extract view count on live streams. 

### ISSUE THREAD

**Issue by ondentite** [rg3/youtube-dl#14979]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
C:\Users\User>youtube-dl -v https://vk.com/video-19043_456239355
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vk.com/video-19043_456239355']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-88514-gd5995c531d, ffprobe N-88514-gd5995c531d
[debug] Proxy map: {}
[vk] -19043_456239355: Downloading webpage
WARNING: unable to extract view count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[vk] -19043_456239355: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://live91.vkuserlive.com/7752//liveabr/0/09Y2RsclxvSltsWGNmTVY2Qw/abr/09Y2RsclxvSltsWGNmTVY2Qw_720p/chunks.m3u8?extra=2omZrCemETDi7dWecTowcuHXZFPaW8LERaDh61hvD2pOLwgfbbaE84FdZz6h8MjcuGXQIXkQWdm-OuigwgUCPpLgsY05MfK48Rz3OC7gbGKFsGta2BsYOkuq'
[download] Destination: Прямой эфир из студии «Европы Плюс» 2017-12-14 06_44-456239355.mp4
```
https://vk.com/video-19043_456239355
https://vk.com/video-27532693_456242033

**Comment by SOTVM** [comment]
Как можно загрузить всё аудио из плейлиста vk.com ?
Haw to downloads .mp3 from audioplaylist ?
I Tried to do so:
`
$ youtube-dl -u LOGIN -p PASSWORD 'https://vk.com/audio?z=audio_playlist168011356_2'
[generic] audio?z=audio_playlist168011356_2: Requesting header
WARNING: Could not send HEAD request to https://vk.com/audio?z=audio_playlist168011356_2: HTTP Error 501: Not Implemented
[generic] audio?z=audio_playlist168011356_2: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] audio?z=audio_playlist168011356_2: Extracting information
[redirect] Following redirect to https://vk.com/badbrowser.php
[generic] badbrowser: Requesting header
WARNING: Could not send HEAD request to https://vk.com/badbrowser.php: HTTP Error 501: Not Implemented
[generic] badbrowser: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] badbrowser: Extracting information
ERROR: Unsupported URL: https://vk.com/badbrowser.php

`
