### ISSUE TITLE
[CBSLocal] unable to extract uploadDate

### ISSUE THREAD

**Issue by sant527** [rg3/youtube-dl#14999]
$ youtube-dl --version
2017.12.14

$ youtube-dl "http://detroit.cbslocal.com/2017/12/15/u-m-students-wake-to-find-strange-man-inside-apartment"
[CBSLocal] u-m-students-wake-to-find-strange-man-inside-apartment: Downloading webpage
[CBSLocal] 3672375: Fetching server time
[CBSLocal] 3672375: Downloading JSON metadata
[CBSLocal] 3672375: Downloading m3u8 information
[CBSLocal] 3672375: Downloading SMIL file
WARNING: unable to extract uploadDate; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3
[download] Destination: WWJ Newsradio 950 - The Newswatch Never Stops-3672375.mp4
[download]   6.9% of ~14.44MiB at 567.21KiB/s ETA 00:28^C
ERROR: Interrupted by user

**Comment by Hier631** [comment]
I'm working on it. :D
