### ISSUE TITLE
download from youtube it's slow, why ?

### ISSUE THREAD

**Issue by tone87** [rg3/youtube-dl#14990]
hi , i have a big problem with download speed , my connection speed  it's 100mbit , but why it's so slowly ? 
i tried to use "--force-ipv4"  ,it tried external downloader aria2 but not work for certificate error.
anyone know any tricks to use all bandwidth ?
 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--force-ipv4', u'--prefer-ffmpeg', u'--extract-audio', u'--audio-format', u'mp3', u'https://www.youtube.com/watch?v=W1tzURKYFNs']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2017.12.14
[debug] Python version 2.6.6 - Linux-2.6.32-696.el6.x86_64-x86_64-with-centos-6.9-Final
[debug] exe versions: ffmpeg 2.6.4, ffprobe 2.6.4
[debug] Proxy map: {}
[youtube] W1tzURKYFNs: Downloading webpage
[youtube] W1tzURKYFNs: Downloading video info webpage
[youtube] W1tzURKYFNs: Extracting video information
[youtube] {22} signature length 40.41, html5 player vflOQ79Pl
[youtube] {43} signature length 40.41, html5 player vflOQ79Pl
[youtube] {18} signature length 40.41, html5 player vflOQ79Pl
[youtube] {36} signature length 40.41, html5 player vflOQ79Pl
[youtube] {17} signature length 40.41, html5 player vflOQ79Pl
[youtube] {137} signature length 40.41, html5 player vflOQ79Pl
[youtube] {248} signature length 40.41, html5 player vflOQ79Pl
[youtube] {136} signature length 40.41, html5 player vflOQ79Pl
[youtube] {247} signature length 40.41, html5 player vflOQ79Pl
[youtube] {135} signature length 40.41, html5 player vflOQ79Pl
[youtube] {244} signature length 40.41, html5 player vflOQ79Pl
[youtube] {134} signature length 40.41, html5 player vflOQ79Pl
[youtube] {243} signature length 40.41, html5 player vflOQ79Pl
[youtube] {133} signature length 40.41, html5 player vflOQ79Pl
[youtube] {242} signature length 40.41, html5 player vflOQ79Pl
[youtube] {160} signature length 40.41, html5 player vflOQ79Pl
[youtube] {278} signature length 40.41, html5 player vflOQ79Pl
[youtube] {140} signature length 40.41, html5 player vflOQ79Pl
[youtube] {171} signature length 40.41, html5 player vflOQ79Pl
[youtube] {249} signature length 40.41, html5 player vflOQ79Pl
[youtube] {250} signature length 40.41, html5 player vflOQ79Pl
[youtube] {251} signature length 40.41, html5 player vflOQ79Pl
[youtube] W1tzURKYFNs: Downloading MPD manifest
[debug] Invoking downloader on u'https://r7---sn-8vq54voxpu-hm2l.googlevideo.com/videoplayback?itag=251&ipbits=0&gir=yes&dur=277.241&expire=1513302560&pl=25&key=yt6&usequic=no&pcm2cms=yes&ei=v9UyWtjZPNWsWK-UnKgC&id=o-ABd7EzXgATSvtunzsrCdeXdXNHXvkcp0ZwydJupVmKQj&initcwndbps=442500&lmt=1511499716781798&ip=47.53.127.200&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cusequic%2Cexpire&ms=au&mt=1513280865&mv=m&keepalive=yes&source=youtube&clen=4847496&requiressl=yes&mime=audio%2Fwebm&mm=31&mn=sn-8vq54voxpu-hm2l&signature=A13FF0D47F03F7410F9915B378AD3E0E823739DA.527AA65760FAF4E6FBF8CEA4CD292E559A5D5E58&ratebypass=yes'
[download] Destination: Miley_Cyrus_-_Adore_You-W1tzURKYFNs.webm
[download] 0.0% of 4.62MiB at 6.67KiB/s ETA 11:49
[download] 0.1% of 4.62MiB at 19.96KiB/s ETA 03:56
[download] 0.1% of 4.62MiB at 46.51KiB/s ETA 01:41
[download] 0.3% of 4.62MiB at 99.51KiB/s ETA 00:47
[download] 0.7% of 4.62MiB at 28.32KiB/s ETA 02:46
[download] 1.0% of 4.62MiB at 38.38KiB/s ETA 02:02
[download] 1.7% of 4.62MiB at 57.93KiB/s ETA 01:20
[download] 3.2% of 4.62MiB at 52.33KiB/s ETA 01:27
[download] 4.2% of 4.62MiB at 56.22KiB/s ETA 01:20
[download] 5.7% of 4.62MiB at 53.86KiB/s ETA 01:22
[download] 6.7% of 4.62MiB at 41.93KiB/s ETA 01:45
[download] 7.2% of 4.62MiB at 40.31KiB/s ETA 01:48
[download] 7.8% of 4.62MiB at 36.44KiB/s ETA 01:59
[download] 8.2% of 4.62MiB at 37.19KiB/s ETA 01:56
[download] 8.8% of 4.62MiB at 38.36KiB/s ETA 01:52
[download] 10.1% of 4.62MiB at 39.75KiB/s ETA 01:47
[download] 11.2% of 4.62MiB at 37.97KiB/s ETA 01:50
[download] 11.8% of 4.62MiB at 38.97KiB/s ETA 01:47
[download] 13.0% of 4.62MiB at 35.88KiB/s ETA 01:54
[download] 13.5% of 4.62MiB at 35.99KiB/s ETA 01:53
[download] 14.3% of 4.62MiB at 35.69KiB/s ETA 01:53
[download] 15.0% of 4.62MiB at 35.20KiB/s ETA 01:54
[download] 15.6% of 4.62MiB at 35.43KiB/s ETA 01:52
[download] 16.5% of 4.62MiB at 36.10KiB/s ETA 01:49
[download] 17.6% of 4.62MiB at 34.44KiB/s ETA 01:53
[download] 18.2% of 4.62MiB at 35.21KiB/s ETA 01:50
[download] 19.3% of 4.62MiB at 34.82KiB/s ETA 01:49
[download] 19.9% of 4.62MiB at 35.48KiB/s ETA 01:46
[download] 21.2% of 4.62MiB at 36.43KiB/s ETA 01:42
[download] 22.5% of 4.62MiB at 36.27KiB/s ETA 01:41
[download] 23.2% of 4.62MiB at 36.01KiB/s ETA 01:40
[download] 23.9% of 4.62MiB at 35.50KiB/s ETA 01:41
[download] 24.3% of 4.62MiB at 34.97KiB/s ETA 01:42
[download] 24.8% of 4.62MiB at 34.83KiB/s ETA 01:42
[download] 25.4% of 4.62MiB at 34.49KiB/s ETA 01:42
[download] 25.9% of 4.62MiB at 34.39KiB/s ETA 01:42
[download] 26.5% of 4.62MiB at 34.53KiB/s ETA 01:40
[download] 27.4% of 4.62MiB at 33.84KiB/s ETA 01:41
[download] 27.8% of 4.62MiB at 34.27KiB/s ETA 01:39
[download] 28.7% of 4.62MiB at 34.66KiB/s ETA 01:37
[download] 29.9% of 4.62MiB at 35.41KiB/s ETA 01:33
[download] 31.5% of 4.62MiB at 35.31KiB/s ETA 01:31
[download] 32.3% of 4.62MiB at 34.88KiB/s ETA 01:31
[download] 32.8% of 4.62MiB at 35.10KiB/s ETA 01:30
[download] 33.8% of 4.62MiB at 35.16KiB/s ETA 01:29
[download] 34.6% of 4.62MiB at 35.51KiB/s ETA 01:27
[download] 35.9% of 4.62MiB at 35.33KiB/s ETA 01:25
[download] 36.6% of 4.62MiB at 34.88KiB/s ETA 01:26
[download] 37.0% of 4.62MiB at 34.38KiB/s ETA 01:26
[download] 37.3% of 4.62MiB at 33.96KiB/s ETA 01:27
[download] 37.7% of 4.62MiB at 34.06KiB/s ETA 01:26
[download] 38.3% of 4.62MiB at 33.64KiB/s ETA 01:26
[download] 38.7% of 4.62MiB at 33.29KiB/s ETA 01:27
[download] 39.0% of 4.62MiB at 32.97KiB/s ETA 01:27
[download] 39.4% of 4.62MiB at 33.03KiB/s ETA 01:26
[download] 40.0% of 4.62MiB at 32.88KiB/s ETA 01:26
[download] 40.6% of 4.62MiB at 32.58KiB/s ETA 01:26
[download] 41.0% of 4.62MiB at 32.82KiB/s ETA 01:25
[download] 41.8% of 4.62MiB at 32.84KiB/s ETA 01:23
[download] 42.5% of 4.62MiB at 32.57KiB/s ETA 01:23
[download] 43.0% of 4.62MiB at 32.22KiB/s ETA 01:23
[download] 43.3% of 4.62MiB at 32.16KiB/s ETA 01:23
[download] 43.9% of 4.62MiB at 32.33KiB/s ETA 01:22
[download] 45.0% of 4.62MiB at 31.75KiB/s ETA 01:22
[download] 45.5% of 4.62MiB at 32.03KiB/s ETA 01:20
[download] 46.6% of 4.62MiB at 32.35KiB/s ETA 01:18
[download] 47.8% of 4.62MiB at 32.31KiB/s ETA 01:16
[download] 48.4% of 4.62MiB at 32.56KiB/s ETA 01:14
[download] 49.7% of 4.62MiB at 32.56KiB/s ETA 01:13
[download] 50.4% of 4.62MiB at 32.82KiB/s ETA 01:11
[download] 51.8% of 4.62MiB at 33.35KiB/s ETA 01:08
[download] 53.5% of 4.62MiB at 34.18KiB/s ETA 01:04
[download] 56.4% of 4.62MiB at 35.36KiB/s ETA 00:58
[download] 58.5% of 4.62MiB at 36.33KiB/s ETA 00:54
[download] 61.4% of 4.62MiB at 35.63KiB/s ETA 00:51
[download] 62.9% of 4.62MiB at 35.88KiB/s ETA 00:48
[download] 64.0% of 4.62MiB at 36.12KiB/s ETA 00:47
[download] 65.2% of 4.62MiB at 36.58KiB/s ETA 00:44
[download] 67.4% of 4.62MiB at 37.20KiB/s ETA 00:41
[download] 69.0% of 4.62MiB at 37.09KiB/s ETA 00:39
[download] 69.8% of 4.62MiB at 37.45KiB/s ETA 00:38
[download] 71.4% of 4.62MiB at 38.14KiB/s ETA 00:35
[download] 74.6% of 4.62MiB at 39.23KiB/s ETA 00:30
[download] 76.9% of 4.62MiB at 39.86KiB/s ETA 00:27
[download] 78.7% of 4.62MiB at 39.94KiB/s ETA 00:25
[download] 79.6% of 4.62MiB at 39.84KiB/s ETA 00:24
[download] 80.3% of 4.62MiB at 39.83KiB/s ETA 00:23
[download] 81.1% of 4.62MiB at 40.08KiB/s ETA 00:22
[download] 82.8% of 4.62MiB at 40.64KiB/s ETA 00:20
[download] 85.5% of 4.62MiB at 41.55KiB/s ETA 00:16
[download] 88.3% of 4.62MiB at 42.39KiB/s ETA 00:13
[download] 90.6% of 4.62MiB at 42.91KiB/s ETA 00:10
[download] 92.3% of 4.62MiB at 43.25KiB/s ETA 00:08
[download] 93.9% of 4.62MiB at 43.74KiB/s ETA 00:06
[download] 96.5% of 4.62MiB at 44.52KiB/s ETA 00:03
[download] 99.2% of 4.62MiB at 45.36KiB/s ETA 00:00
[download] 100.0% of 4.62MiB at 45.69KiB/s ETA 00:00
[download] 100% of 4.62MiB in 01:43
[debug] ffmpeg command line: ffprobe -show_streams 'file:Miley_Cyrus_-_Adore_You-W1tzURKYFNs.webm'
[ffmpeg] Destination: Miley_Cyrus_-_Adore_You-W1tzURKYFNs.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:Miley_Cyrus_-_Adore_You-W1tzURKYFNs.webm' -vn -acodec libmp3lame '-q:a' 5 'file:Miley_Cyrus_-_Adore_You-W1tzURKYFNs.mp3'
Deleting original file Miley_Cyrus_-_Adore_You-W1tzURKYFNs.webm (pass -k to keep)

**Comment by tone87** [comment]
solved ! i try to use --external-downloader curl 
curl use a full bandwidth !

**Comment by tone87** [comment]
hi , i have the same problem now with  --external-downloader curl 
i try to use wget but speed it's max 50kb/s .. anyone know why ?

**Comment by White4Dragon** [comment]
I had the same problem, I now use the --external-downloader ffmpeg and it seems to work
