### ISSUE TITLE
Videobuster.de

### ISSUE THREAD

**Issue by Marti4n** [rg3/youtube-dl#15008]
Hello,
maybe it's possible, so I'm asking here...

I wish to download a movie from www.videobuster.de via mpd web url (I found with firefox developer tools), but it seems youtube-dl does not support this web page as it maybe uses some encryption which is hard to "crack".

This is the target mpd web url:
https://vbcache1037.videobuster.de/upstream1036/movies/mpd/baa7be16769ec7f7bb8e0d79de73380c/12/explay-hd.ism/playlist.mpd

It's a DASH (mp4/avc1) video and is protected by "explay".
Quality informations are at the end of the "playlist.mpd" file (1080p would be the best).

And yes, I'm using the latest version of youtube-dl. :)
Would be nice if you can add this page to the "supported sites", and if you need some more details (account login etc.) just ask me. Thanks in advance.

**Comment by dstftw** [comment]
DRM is not supported.
