### ISSUE TITLE
ITV rtmpdump exited with code 1

### ISSUE THREAD

**Issue by DanUnknown** [rg3/youtube-dl#15002]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
/usr/local/bin/youtube-dl https://www.itv.com/hub/bancroft/2a2028a0003 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.itv.com/hub/bancroft/2a2028a0003', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.14
[debug] Python version 2.7.12 - Linux-4.4.0-103-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 25.142.205.118 (GB) as X-Forwarded-For.
[ITV] 2a2028a0003: Downloading webpage
[ITV] 2a2028a0003: Downloading XML
[ITV] 2a2028a0003: Downloading JSON metadata
[ITV] 2a2028a0003: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'rtmpe://cp72511.edgefcs.net/ondemand'
[download] Destination: Episode 3-2a2028a0003.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://cp72511.edgefcs.net/ondemand' -o 'Episode 3-2a2028a0003.flv.part' --swfVfy 'http://www.itv.com/mercury/Mercury_VideoPlayer.swf' --pageUrl 'https://www.itv.com/hub/bancroft/2a2028a0003' --app 'ondemand?auth=eaEaCbFdRcsbVchdccUaebZcXaYdda6dtaRcHcMaEd7dAdTcqbycWaXdlcQdBcCcXa1-bAnh0B-eS-cyn4FCvkCtDs&aifp=v002&slist=production/' --playpath 'mp4:production/priority/CATCHUP/2/2028/0003/006/2-2028-0003-006_PC011800_16X9.mp4' --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : cp72511.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : cp72511.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:production/priority/CATCHUP/2/2028/0003/006/2-2028-0003-006_PC011800_16X9.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://cp72511.edgefcs.net:1935/ondemand?auth=eaEaCbFdRcsbVchdccUaebZcXaYdda6dtaRcHcMaEd7dAdTcqbycWaXdlcQdBcCcXa1-bAnh0B-eS-cyn4FCvkCtDs&aifp=v002&slist=production/
[rtmpdump] DEBUG: swfUrl   : http://www.itv.com/mercury/Mercury_VideoPlayer.swf
[rtmpdump] DEBUG: pageUrl  : https://www.itv.com/hub/bancroft/2a2028a0003
[rtmpdump] DEBUG: app      : ondemand?auth=eaEaCbFdRcsbVchdccUaebZcXaYdda6dtaRcHcMaEd7dAdTcqbycWaXdlcQdBcCcXa1-bAnh0B-eS-cyn4FCvkCtDs&aifp=v002&slist=production/
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: b6 c8 96 6d a3 f4 96 10 be 71 78 b0 1c a3 3d 04
[rtmpdump] DEBUG: 6b bf 91 5e 29 08 d9 da fe 11 e4 b0 42 d8 ee ea
[rtmpdump] DEBUG: SWFSize  : 990750
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : cp72511.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : cp72511.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:production/priority/CATCHUP/2/2028/0003/006/2-2028-0003-006_PC011800_16X9.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://cp72511.edgefcs.net:1935/ondemand?auth=eaEaCbFdRcsbVchdccUaebZcXaYdda6dtaRcHcMaEd7dAdTcqbycWaXdlcQdBcCcXa1-bAnh0B-eS-cyn4FCvkCtDs&aifp=v002&slist=production/
[rtmpdump] DEBUG: swfUrl   : http://www.itv.com/mercury/Mercury_VideoPlayer.swf
[rtmpdump] DEBUG: pageUrl  : https://www.itv.com/hub/bancroft/2a2028a0003
[rtmpdump] DEBUG: app      : ondemand?auth=eaEaCbFdRcsbVchdccUaebZcXaYdda6dtaRcHcMaEd7dAdTcqbycWaXdlcQdBcCcXa1-bAnh0B-eS-cyn4FCvkCtDs&aifp=v002&slist=production/
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: b6 c8 96 6d a3 f4 96 10 be 71 78 b0 1c a3 3d 04
[rtmpdump] DEBUG: 6b bf 91 5e 29 08 d9 da fe 11 e4 b0 42 d8 ee ea
[rtmpdump] DEBUG: SWFSize  : 990750
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.


ERROR: rtmpdump exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1986, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 795, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 849, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1620, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1893, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1832, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 163, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 612, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 574, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

One episode out of a series fails in rtmpdump with "Failed to get last keyframe" then "ERROR: rtmpdump exited with code 1". The 3 other episodes in the series download correctly so it *might* be an error with that specific file on ITV repository. 

These work:
https://www.itv.com/hub/bancroft/2a2028a0001
https://www.itv.com/hub/bancroft/2a2028a0002
https://www.itv.com/hub/bancroft/2a2028a0004

This one fails with the error
https://www.itv.com/hub/bancroft/2a2028a0003

Note that I used youtube-dl version 2017.12.14 to correctly download https://www.itv.com/hub/bancroft/2a2028a0004 but https://www.itv.com/hub/bancroft/2a2028a0003 failed on all recent versions including 2017.12.14

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by ArturiaPendragon** [comment]
Hello, it's works : 
> [ITV] 2a2028a0003: Downloading webpage
[ITV] 2a2028a0003: Downloading XML
[ITV] 2a2028a0003: Downloading JSON metadata
[ITV] 2a2028a0003: Downloading m3u8 information
[download] Destination: Episode 3-2a2028a0003.flv
[download]  99.9% of ~503.87MiB at  1.19MiB/s ETA 00:00
[rtmpdump] 527815794 bytes
[download] 100% of 503.36MiB

**Comment by DanUnknown** [comment]
After 4 days of trying, this video finally downloads - same version of youtube-dl has been used on each attempt. Nothing else was changed on my computer during this period. This appears to have been caused by a faulty file on the ITV repository which has been replaced (only my guess). This issue is resolved

**Comment by DanUnknown** [comment]
After 4 days of trying, this video finally downloads - same version of
youtube-dl has been used on each attempt. Nothing else was changed on my
computer during this period. This appears to have been caused by a faulty
file on the ITV repository which has been replaced (only my guess). This
issue is resolved

Thanks

On Sun, Dec 17, 2017 at 4:49 PM, Arturia Pendragon <notifications@github.com
