### ISSUE TITLE
[Ubuntu] youtube-dl does not downolad the the most recent file from playlist

### ISSUE THREAD

**Issue by fatherjz** [rg3/youtube-dl#15003]
Introduction.
I want to download the the most recent file from playlist [https://www.youtube.com/playlist?list=PLRSGEZKuzW-5VWfGU8FuYTNV1rd6p7-7C]. I am using a bash script.
The bash script compares current recordings number from youtube chanel with a record numbers which have saved previous day in a file. When is new video youtube-dll should downolad file - please see the fragment of script below.

```
# URL = URL to playlist
# path - path to file
# temp - temporary file name where is saved previous checking
#...

LAST=$(cat $path/$temp)
NOW=$(youtube-dl -s --get-filename $URL | wc -l)
        if [ "$NOW" -gt "$LAST" ]; then
                echo $NOW>$path/$temp
                NEW_VIDEO_ID=$(youtube-dl -s --playlist-items $NOW --get-id $URL)
				cd $path && youtube-dl --extract-audio --audio-format mp3 "https://www.youtube.com/watch?v=$NEW_VIDEO_ID"

#...
```

Youtube-dl does not downolad the most recent file from playlist. How can I improve this?

Thanks.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#how-do-i-download-only-new-videos-from-a-playlist
