### ISSUE TITLE
"[ffmpeg] There aren't any subtitles to embed"

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#15011]
$ youtube-dl -v --embed-subs https://www.youtube.com/watch?v=Ye8mB6VsUHw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--embed-subs', 'https://www.youtube.com/watch?v=Ye8mB6VsUHw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.10
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Ye8mB6VsUHw: Downloading webpage
[youtube] Ye8mB6VsUHw: Downloading video info webpage
[youtube] Ye8mB6VsUHw: Extracting video information
[youtube] Ye8mB6VsUHw: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r6---sn-a5meknee.googlevideo.com/videoplayback?id=61ef2607a56c507c&itag=213&source=youtube&requiressl=yes&ms=au&ei=7rw1Wp-mKMm0-wPczqWgAw&initcwndbps=1375000&mv=m&pl=14&mn=sn-a5meknee&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=31624319&lmt=1361411763211228&dur=93.226&key=dg_yt0&mt=1513471118&signature=23D7AD47B4E3710FC9A13EC63B7884D523859C48.425C8905A1BB9F67EFB0E03CDA21B4D80ED3EB9F&ip=45.50.15.139&ipbits=0&expire=1513492814&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,ei,initcwndbps,mv,pl,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.f213.mp4
[download] 100% of 30.16MiB in 00:02
[debug] Invoking downloader on 'https://r6---sn-a5meknee.googlevideo.com/videoplayback?id=61ef2607a56c507c&itag=140&source=youtube&requiressl=yes&ms=au&ei=7rw1Wp-mKMm0-wPczqWgAw&initcwndbps=1375000&mv=m&pl=14&mn=sn-a5meknee&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=1483231&lmt=1481455908240358&dur=93.344&key=dg_yt0&mt=1513471118&signature=0F27F0943C2A75A19B91BCDB828D971D892155B1.85A36F06B6800A9F97AB901BE8C47A3327628A1B&ip=45.50.15.139&ipbits=0&expire=1513492814&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,ei,initcwndbps,mv,pl,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.f140.m4a
[download] 100% of 1.41MiB in 00:00
[ffmpeg] Merging formats into "Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.f213.mp4' -i 'file:Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.temp.mp4'
Deleting original file Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.f213.mp4 (pass -k to keep)
Deleting original file Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.f140.m4a (pass -k to keep)
[ffmpeg] There aren't any subtitles to embed

$ youtube-dl --list-subs https://www.youtube.com/watch?v=Ye8mB6VsUHw
[youtube] Ye8mB6VsUHw: Downloading webpage
[youtube] Ye8mB6VsUHw: Downloading video info webpage
[youtube] Ye8mB6VsUHw: Extracting video information
[youtube] Ye8mB6VsUHw: Looking for automatic captions
[youtube] Ye8mB6VsUHw: Downloading MPD manifest
Available automatic captions for Ye8mB6VsUHw:
Language formats
lb       vtt, ttml
fa       vtt, ttml
si       vtt, ttml
eo       vtt, ttml
zh-Hans  vtt, ttml
ku       vtt, ttml
el       vtt, ttml
gd       vtt, ttml
it       vtt, ttml
ne       vtt, ttml
mi       vtt, ttml
la       vtt, ttml
so       vtt, ttml
fy       vtt, ttml
xh       vtt, ttml
kk       vtt, ttml
eu       vtt, ttml
bg       vtt, ttml
mg       vtt, ttml
tr       vtt, ttml
sm       vtt, ttml
cy       vtt, ttml
id       vtt, ttml
mr       vtt, ttml
ur       vtt, ttml
yo       vtt, ttml
ja       vtt, ttml
te       vtt, ttml
sv       vtt, ttml
lv       vtt, ttml
cs       vtt, ttml
es       vtt, ttml
af       vtt, ttml
jv       vtt, ttml
nl       vtt, ttml
my       vtt, ttml
sl       vtt, ttml
kn       vtt, ttml
th       vtt, ttml
sd       vtt, ttml
fi       vtt, ttml
de       vtt, ttml
zu       vtt, ttml
da       vtt, ttml
mn       vtt, ttml
km       vtt, ttml
zh-Hant  vtt, ttml
pl       vtt, ttml
is       vtt, ttml
sn       vtt, ttml
mk       vtt, ttml
ro       vtt, ttml
ig       vtt, ttml
yi       vtt, ttml
uk       vtt, ttml
lt       vtt, ttml
hi       vtt, ttml
ta       vtt, ttml
bs       vtt, ttml
pt       vtt, ttml
ga       vtt, ttml
ml       vtt, ttml
st       vtt, ttml
bn       vtt, ttml
sr       vtt, ttml
no       vtt, ttml
fil      vtt, ttml
haw      vtt, ttml
tg       vtt, ttml
ny       vtt, ttml
en       vtt, ttml
ha       vtt, ttml
az       vtt, ttml
sq       vtt, ttml
ca       vtt, ttml
ht       vtt, ttml
iw       vtt, ttml
hmn      vtt, ttml
sw       vtt, ttml
ka       vtt, ttml
ko       vtt, ttml
gl       vtt, ttml
hy       vtt, ttml
et       vtt, ttml
hu       vtt, ttml
mt       vtt, ttml
sk       vtt, ttml
ceb      vtt, ttml
ru       vtt, ttml
hr       vtt, ttml
ar       vtt, ttml
ps       vtt, ttml
vi       vtt, ttml
ky       vtt, ttml
su       vtt, ttml
am       vtt, ttml
ms       vtt, ttml
pa       vtt, ttml
co       vtt, ttml
fr       vtt, ttml
lo       vtt, ttml
gu       vtt, ttml
uz       vtt, ttml
be       vtt, ttml
Available subtitles for Ye8mB6VsUHw:
Language formats
en       vtt, ttml

That seems to be a bug?

**Comment by ArturiaPendragon** [comment]
Use this : 

> youtube] Ye8mB6VsUHw: Downloading webpage
[youtube] Ye8mB6VsUHw: Downloading video info webpage
[youtube] Ye8mB6VsUHw: Extracting video information
[youtube] Ye8mB6VsUHw: Downloading MPD manifest
[info] Writing video subtitles to: Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.en.vtt
[download] Destination: Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.f213.mp4
[download] 100% of 30.16MiB in 00:00
[download] Destination: Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.f140.m4a
[download] 100% of 1.41MiB in 00:00
[ffmpeg] Merging formats into "Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.mp4"
Deleting original file Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.f213.mp4 (pass -k to keep)
Deleting original file Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.f140.m4a (pass -k to keep)
[ffmpeg] Embedding subtitles in 'Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.mp4'
Deleting original file Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.en.vtt (pass -k to keep)

Mediainfo : 

General
Complete name                            : Sesame Street - Cookie Monster Sings C is for Cookie-Ye8mB6VsUHw.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 31.6 MiB
Duration                                 : 1 min 33 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 2 842 kb/s
Writing application                      : Lavf57.78.100

Video

ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 3 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1 min 33 s
Bit rate                                 : 2 711 kb/s
Width                                    : 640 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 29.970 (30000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.294
Stream size                              : 30.1 MiB (95%)

Audio

ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Duration                                 : 1 min 33 s
Duration_LastFrame                       : 1 ms
Bit rate mode                            : Constant
Bit rate                                 : 126 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 1.40 MiB (4%)
Default                                  : Yes
Alternate group                          : 1

Text

ID                                       : 3
Format                                   : Timed Text
Muxing mode                              : sbtl
Codec ID                                 : tx3g
Duration                                 : 1 min 25 s
Bit rate mode                            : Variable
Bit rate                                 : 101 b/s
Stream size                              : 1.05 KiB (0%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
Alternate group                          : 3

**Comment by antdude** [comment]
Ah thanks. Missing --write-sub parameter. I see that with it and without --embed-subs parameter makes a separate .vtt file instead of in the video file.
