### ISSUE TITLE
Vimeo On Demand rented video requires "embedding URL"

### ISSUE THREAD

**Issue by benoitmars** [rg3/youtube-dl#15028]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.14**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)

---
21:56:40 > ~ $ youtube-dl --verbose -u 'XXXXXXXX@gmail.com' -p 'XXXXXXXXXXXXX' https://vimeo.com/ondemand/godsavejustintrudeaudocu/109579633

[debug] System config: [u'-o', u'~/Downloads/%(title)s.%(ext)s', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://vimeo.com/ondemand/godsavejustintrudeaudocu/109579633']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.14
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[vimeo:ondemand] godsavejustintrudeaudocu: Downloading webpage
[vimeo] Logging in
[vimeo] 109579633: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 470, in _real_extract
    webpage, urlh = self._download_webpage_handle(request, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 535, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 515, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 484, in _real_extract
    expected=True)
ExtractorError: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.

---
This an on demand video which I've rented for only two days… I've tried with several working URLs:
https://vimeo.com/ondemand/godsavejustintrudeaudocu/109579633
https://vimeo.com/ondemand/godsavejustintrudeaudocu/
https://vimeo.com/ondemand/godsavejustintrudeaudocu
https://vimeo.com/109579633
http://productionsdelaruelle.com/PDLRweb/film-achat-et-location/ (user's website)
https://vimeo.com/ondemand/godsavejustintrudeaudocu/181060588 (another link to the same on demand video)

None of them allow me to download the file, I got the same error each time.

Thanks.

**Comment by benoitmars** [comment]
Does it mean that I have to give credentials to deal with the issue?

**Comment by Hrxn** [comment]
Did you try it with the embedding URL specified?

Like this: `youtube-dl --referer URL  ... `

I don't know, maybe this one?
> http://productionsdelaruelle.com/PDLRweb/film-achat-et-location/

**Comment by benoitmars** [comment]
Yes, it actually works! I was sure to have tried every combination, but I missed this one…

Thanks!
