### ISSUE TITLE
hostarlivestreamer error

### ISSUE THREAD

**Issue by hp30051998** [rg3/youtube-dl#15032]
hey please help with the current issue of hotstar livestreamer
"paste the link:http://www.hotstar.com/movies/baadshaho/1000194296
Available streams:      234p 360p 404p 720p 900p 1080p
write quality (example write 720p):720p
Starting livestreamer...

The system cannot find the path specified.
Done.
Press any key to continue . . ."

This is the issue currently displayed on cmd prompt

**Comment by dstftw** [comment]
Address it to livestreamer support.
