### ISSUE TITLE
facebook download ple...

### ISSUE THREAD

**Issue by girlsapink** [rg3/youtube-dl#15039]
I tried to get 1080p video at https://www.facebook.com/LOTTEDFS/videos/1177143509082945/ but it can not be downloaded Please let me know how to fix it Continue --username --p Continue.
1 https://www.facebook.com/LOTTEDFS/videos/1177143509082945/ --username xxx@xxx.com --p I tested with paass but can not download it.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
