### ISSUE TITLE
vol.at's embedded videos

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#15041]
Example: 

$ youtube-dl -v "http://www.vol.at/blue-man-group/5593454"     [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.vol.at/blue-man-group/5593454']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.10
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 5593454: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 5593454: Downloading webpage
[generic] 5593454: Extracting information
ERROR: Unsupported URL: http://www.vol.at/blue-man-group/5593454
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3063, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.vol.at/blue-man-group/5593454

Thank you in advance. :)

**Comment by Wandang** [comment]
Seems to require local javascript execution (phantomjs). Not as easy as I hoped.

**Comment by Wandang** [comment]
Is fixed with this commit: https://github.com/rg3/youtube-dl/pull/15672
