### ISSUE TITLE
Trash original files

### ISSUE THREAD

**Issue by PhilipDukhov** [rg3/youtube-dl#15046]
As I know there's an option "-k" to keep original files, and without this option - files are removed completly. But it will be very comfortably for me if files are moved to the trash, so I can restore them just if I need, not all the time. Usualy I think that that's be great to keep it after it's removed already.

**Comment by sleske** [comment]
Interesting idea. However, that might be a bit tricky because "moving to trash" works differently on different platforms. We should probably use an external library. Send2Trash ( https://pypi.python.org/pypi/Send2Trash ) looks good, however it does not support Python 2.6.

**Comment by sleske** [comment]
At any rate, I'm not sure this is really worth implementing.

Most users will just delete the original videos (that is why "-k" / "--keep-video" is not the default), and the original video files are often in unusual formats, so not terribly useful for most people. I think "-k" is mostly an option either for advanced users, who want to do their own custom post-processing, or for debugging of youtube-dl. So I don't think a lot of people would have a use for keeping the files but moving them to trash.

In addition to that, video files tend to be fairly large, so moving them to trash may will quickly fill up available storage space, meaning this option could actually cause problems if used inadvertently.

All in all, I personally think this is not really worth implementing. Or are there use cases I forgot?

**Comment by Hrxn** [comment]
No, I think you are right.

**Comment by yan12125** [comment]
I don't think this feature is useful for many youtube-dl users, either. If you want to investigate possible approaches by yourself, check out the line that does the deletion:
https://github.com/rg3/youtube-dl/blob/3961c6cb9d3a1c30fe31db774b0809095952f1bd/youtube_dl/YoutubeDL.py#L2041
