### ISSUE TITLE
--write-pages uses filenames too long for Windows

### ISSUE THREAD

**Issue by sheddup** [rg3/youtube-dl#15053]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.14**

### Before submitting an *issue* make sure you have:
- [ x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\user\Downloads\>youtube-dl.exe https://www.youtube.c
om/watch?v=XSdWHeSf86U -F --write-pages --restrict-filenames -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=XSdWHeSf86U', '-F',
 '--write-pages', '--restrict-filenames', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] XSdWHeSf86U: Downloading webpage
[youtube] Saving request to XSdWHeSf86U_https_-_www.youtube.com_watchbpctr=99999
99999_gl=US_disable_polymer=true_v=XSdWHeSf86U_hl=en_has_verified=1.dump
[youtube] XSdWHeSf86U: Downloading video info webpage
[youtube] Saving request to XSdWHeSf86U_https_-_www.youtube.com_get_video_infoeu
rl=_disable_polymer=true_sts=17515_ps=default_video_id=XSdWHeSf86U_gl=US_el=info
_hl=en.dump
[youtube] XSdWHeSf86U: Extracting video information
[youtube] XSdWHeSf86U: Downloading MPD manifest
[youtube] Saving request to XSdWHeSf86U_https_-_manifest.googlevideo.com_api_man
ifest_dash_sparams_as%2Cei%2Cgcr%2Chfr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2
Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cplayback_host%2Crequiressl%2Csource%2_29a7bf
6c511a31b58d74a37e99dd0a62.dump
[info] Available formats for XSdWHeSf86U:
```

---

After the pages are written to disk trying to read/write/delete the dash manifest file fails because windows can't handle the length of filename `The filename or extension is too long`

**Comment by dstftw** [comment]
```
> py -2.7 .\youtube_dl\__main__.py  XSdWHeSf86U --write-pages --restrict-filenames -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'XSdWHeSf86U', u'--write-pages', u'--restrict-filenames', u'-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.12.14
[debug] Git HEAD: 46b72b7
[debug] Python version 2.7.12 - Windows-10-10.0.10240
[debug] exe versions: ffmpeg N-85653-gb4330a0, ffprobe N-85653-gb4330a0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] XSdWHeSf86U: Downloading webpage
[youtube] Saving request to XSdWHeSf86U_https_-_www.youtube.com_watchhas_verified=1_bpctr=9999999999_hl=en_v=XSdWHeSf86U_disable_polymer=true_gl=US.dump
[youtube] XSdWHeSf86U: Downloading video info webpage
[youtube] Saving request to XSdWHeSf86U_https_-_www.youtube.com_get_video_infops=default_el=info_video_id=XSdWHeSf86U_hl=en_sts=17515_disable_polymer=true_gl=US_eurl=.dump
[youtube] XSdWHeSf86U: Extracting video information
[youtube] XSdWHeSf86U: Downloading MPD manifest
[youtube] Saving request to XSdWHeSf86U_https_-_manifest.googlevideo.com_api_manifest_dash_itag_0_source_youtube_ms_au_gcr_ru_hfr_1_mv_m_requiressl_yes_id_5d27561de49ff3a5_mn_sn-ug5onuxaxjvh-v8cl_mm_31_playback_host_r1---sn-ug5onuxax_b98ea2524183218adb918549b8c4321b.dump
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r1---sn-ug5onuxaxjvh-v8cl.googlevideo.com/videoplayback?id=5d27561de49ff3a5&itag=137&source=youtube&requiressl=yes&ms=au&gcr=ru&mv=m&mn=sn-ug5onuxaxjvh-v8cl&mm=31&initcwndbps=897500&pl=20&ei=PCE9WtrLFMbryAXprqO4Cw&ratebypass=yes&mime=video/mp4&gir=yes&clen=2673747856&lmt=1513361091714160&dur=13825.009&mt=1513955509&signature=61EEA4EF755D7BEC36C8D413C551D69F8C17F6B3.0BAD2EB40F316A756A89CE8A8A3ED7065B2F6F4D&key=dg_yt0&ip=109.171.17.81&ipbits=0&expire=1513977244&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,gcr,mv,mn,mm,initcwndbps,pl,ei,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Joe_Rogan_Experience_1051_-_Duncan_Trussell_Christopher_Ryan-XSdWHeSf86U.f137.mp4
[download]   0.5% of 2.49GiB at  8.10MiB/s ETA 05:13
ERROR: Interrupted by user
```

**Comment by sheddup** [comment]
1. `youtube-dl.exe https://www.youtube.com/watch?v=XSdWHeSf86U -F --write-pages --restrict-filenames -v ` 
2. **try to open the dash manifest from explorer.exe** << Important
3. Windows throws error The filename or extension is too long

**Comment by dstftw** [comment]
That is the problem of software you are using to open it.
![image](https://user-images.githubusercontent.com/1908898/34303369-8a6ecad6-e767-11e7-811d-cb0ba20c91dc.png)

**Comment by sheddup** [comment]
>That is the problem of software you are using to open it.

Well no because anything on the system that tries to read it or even delete the file results in error, maybe a bug specific to my version of Windows(8.1 x64)
![e](https://user-images.githubusercontent.com/5480335/34303708-cc37dd94-e71d-11e7-8301-27b5210d1fab.png)
![c](https://user-images.githubusercontent.com/5480335/34303713-cf398470-e71d-11e7-8640-4851c49f7e73.png)

**Comment by sheddup** [comment]
The whole path was too long, Windows limitation or something.

**Comment by dstftw** [comment]
Again: **that is the problem of software you are using**. If `del` can't work with paths longer than `MAX_PATH` it's not a youtube-dl's problem. `explorer.exe` works with such paths just fine.
