### ISSUE TITLE
Cannot download yt video with csharp

### ISSUE THREAD

**Issue by botiapa** [rg3/youtube-dl#15051]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I'm trying to download a youtube video with csharp. My code is really simple, I will post it below. Basically it creates a new process, reads the standard output, and closes. Now, my problem is that it doesn't download anything and doesn't output anything. I tried the same code with different commands like ping, ipconfig and it worked. The method I run it in is async.

My code:

```
var info = new ProcessStartInfo();
            info.FileName = "cmd";
            info.Arguments = "/c " + "-x -o \"E:\\VisualStudio_Projects\\LemonBOT\\LemonBOT\\bin\\Debug\\downloads\\% (title)s.% (ext)s\" https://www.youtube.com/watch?v=XDwOt_KO5gk --audio-format mp3 --print-traffic";
info.CreateNoWindow = true;
info.UseShellExecute = false;
info.RedirectStandardOutput = true;
info.CreateNoWindow = true;

var proc = new Process();
proc.StartInfo = info;
proc.Start();
string result = proc.StandardOutput.ReadToEnd();
// Display the command output.
Console.WriteLine(result);
Console.Read();

```

**Comment by dstftw** [comment]
Obviously you are doing something wrong.
