### ISSUE TITLE
youtube-dl should automatically download video as MP4 when including subtitles.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#15050]
Example with youtube-dl --write-sub --embed-subs https://www.youtube.com/watch?v=w4HPw_nfH-g

I should not need to add -f 22 parameter to force MP4 since --embed-subs parameter requires MP4 video format according to its --help parameter.

**Comment by dstftw** [comment]
```
    --embed-subs                     Embed subtitles in the video (only for mp4,
                                     webm and mkv videos)
```
>only for mp4, and mkv videos
