### ISSUE TITLE
Can not download playlist on Youku

### ISSUE THREAD

**Issue by CoXier** [rg3/youtube-dl#15065]
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

`YoukuShowIE` class can extract playlist whose episode count is over than `50`. Here is an video with episode count 26 `youtube-dl` can not download.

```bash
youtube-dl http://list.youku.com/show/id_zefbfbd61237fefbfbdef.html\?spm\=a2h0j.8191423.module_basic_title.5\~A\!2 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://list.youku.com/show/id_zefbfbd61237fefbfbdef.html?spm=a2h0j.8191423.module_basic_title.5~A!2', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.02
[debug] Python version 2.7.13 - Darwin-17.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[youku:show] zefbfbd61237fefbfbdef: Downloading webpage
[youku:show] zefbfbd61237fefbfbdef: Downloading initial playlist data page
[download] Downloading playlist: 虎啸龙吟
[youku:show] playlist 虎啸龙吟: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: 虎啸龙吟
```
As you see `[youku:show] playlist 虎啸龙吟: Collected 0 video ids (downloading 0 of them)`, so there is a bug. I will fix it and create a PR.

**Comment by yan12125** [comment]
Fixed with #15066. Thanks!

**Comment by KwToPA** [comment]
still the same 
youtube-dl --version
2017.12.23

**Comment by KwToPA** [comment]
update from 
```
sudo -H pip install --upgrade youtube-dl

```

**Comment by CoXier** [comment]
Maybe next version.:smile:

**Comment by yan12125** [comment]
@CoXier is right ;)

**Comment by KwToPA** [comment]
Looking  forward that, Thx
