### ISSUE TITLE
Add support for site onepiece-tube.com

### ISSUE THREAD

**Issue by devingDev** [rg3/youtube-dl#15064]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.23**

- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

- Single video: http://onepiece-tube.com/folge/818-z3u2V18ir

You have to view the source of the frame view where the player is , there it seems to show a mp4 link. Could someone add this to the exe of youtube-dl ? I need to extract it for Vlc

**Comment by remitamine** [comment]
https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free

**Comment by devingDev** [comment]
How can you add a site?

And more important how do you , compile the exe ?

**Comment by devingDev** [comment]
In Europe it is allowed as these episodes are not licensed in europe and are not shown in Europe at all.
They only show not licensed in europe ones with subs. It's all good . Don't worry

The licensed ones , aka episodes before, are missing there, check the list of episodes they are "offline"

**Comment by remitamine** [comment]
- some of the licenced episodes are still present in the website:
https://www.prosiebenmaxx.de/anime/one-piece/video/8114-folge-515-ich-werde-viel-viel-staerker-zorros-schwur-an-den-kaept-n-ganze-folge
http://onepiece-tube.com/folge/515-z3u2V18ir
- some of the episodes marked as offline are actually the opposite(entering the page will allow to watch the video):
http://onepiece-tube.com/folge/310-z3u2V18ir
- i don't think that it's okey to host the videos without a licence.

**Comment by devingDev** [comment]
I am not sure why anyone would prefer subbed episodes over dubbed ones. The episodes on the site are japanese with subs which were freely translated. It is not the german dubbed version which airs .
