### ISSUE TITLE
Add support for site onepiece-tube.com (which is legal)

### ISSUE THREAD

**Issue by devingDev** [rg3/youtube-dl#15067]
Before this gets closed : 
In Europe it is allowed as these episodes are not licensed in europe and are not shown in Europe at all.
They only show not licensed in europe ones with subs. It's all good . Don't worry

The licensed ones , aka episodes before, are missing there, check the list of episodes they are "offline"

If you still insist that I am wrong , at least tell me how to compile youtube-dl as a single file .exe , after adding a new site yourself. I have no idea how to add one though.

- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.23**

- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

- Single video: http://onepiece-tube.com/folge/818-z3u2V18ir

You have to view the source of the frame view where the player is , there it seems to show a mp4 link. Could someone add this to the exe of youtube-dl ? I need to extract it for Vlc

**Comment by dstftw** [comment]
>In Europe it is allowed as these episodes are not licensed in europe and are not shown in Europe at all.

This does not prove any rights for them to distribute.

Moreover,
>Zusatz:
Wir hosten keine Video oder Audiodateien auf unseren Servern. Jedes Video ist lediglich verlinkt und “gepostet”.
Für Fragen bezueglich den Video oder Audiodateien befragen Sie bitte den jeweiligen Hoster. (Youtube, Blip, Sevenload etc..)
>
>Wir sind nicht verantwortlich für die verschiedenen Posts der Animes, Folgen, Forenbeitraege oder Chatbeitraege.
>
>Für weitere Fragen stehen wir Ihnen selbstverständlich gern zur Verfügung.

from http://onepiece-tube.com/impressum confirms this is copyright infringement.

`python setup.py py2exe` to build a exe.

**Comment by devingDev** [comment]
How would I get a link inside a frame?

If I view the sourcecode of the frame which is the player , I can see the mp4 link inside there , how do i get the source code of that frame in youtube-dl though? Or any good tut?
