### ISSUE TITLE
 Add support for mycanal.fr

### ISSUE THREAD

**Issue by loby66** [rg3/youtube-dl#15072]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.23**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

- Single video: https://www.mycanal.fr/sport/interview-de-clement-grenier-cfc/p/1474402

>youtube-dl.exe -v https://www.mycanal.fr/sport/interview-de-clement-grenier-cfc/p/1474402
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.mycanal.fr/sport/interview-de-clement-grenier-cfc/p/1474402']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.12.23
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 2.8.4, ffprobe N-81045-g450cf40, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 1474402: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1474402: Downloading webpage
[generic] 1474402: Extracting information
ERROR: Unsupported URL: https://www.mycanal.fr/sport/interview-de-clement-grenier-cfc/p/1474402
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\build\youtube_dl\extractor\generic.py", line 3063, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.mycanal.fr/sport/interview-de-clement-grenier-cfc/p/1474402

**Comment by Munto** [comment]
This is the new portal for canalplus, c8, cstar and other channels of this group.
Canalplus extractor is obsolete for the moment.

**Comment by Munto** [comment]
It was.
I think that mycanal adopted a new system to distribute its videos and I think they use a DRM protection like widevine now.
You should open a new issue to report it but there are poor chances that it will be treated.
