### ISSUE TITLE
skip geo restricted video in the playlist

### ISSUE THREAD

**Issue by blshkv** [rg3/youtube-dl#15074]
Hi, I'm using the lastest git version and trying to download a playlist ( "https://www.youtube.com/watch?v=ktvTqknDobU&list=PLkgWEYvTsgqHO6vTqQEqWxBlW_6ykRmYz"

Some of videos in this list are geo restricted and youtube-dl stops downloading the rest of videos. Here is a non-incluse list as an example:
```
wPW7T_tu3PM
K2NGe9mLAEc
mk0PdLZqZqU 
ePVErcAUzK8
 wPW7T_tu3PM 
 PKzrzJxc8Jo 
AKKllhIJFss 
ePVErcAUzK8 
qtJ1K2Wm9JM 
 mk0PdLZqZqU
 AKKllhIJFss
 ePVErcAUzK8
```

Could you introduce a parameter which would allow to skip such videos and download the rest videos anyway?

**Comment by remitamine** [comment]
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```

**Comment by blshkv** [comment]
ha! I just found it too. The name is a bit not obvious  but it works.

Thanks!
