### ISSUE TITLE
on Error: how to run a shell command in linux

### ISSUE THREAD

**Issue by sant527** [rg3/youtube-dl#15076]
youtube-dl --version
2017.12.14

If i get ERROR: Unsupported URL or ERROR: Unable to extract m3u8 url; please report this issue on https://yt-dl.org/bug . Can i immediately run a shell command. 

Because I run the command in background. If it fails i can open a text file or something so that i can know about it

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
