### ISSUE TITLE
Enable user to query a video extractor what special sequence output template tags it supports.

### ISSUE THREAD

**Issue by edakiri** [rg3/youtube-dl#15084]
This feature request is to enable user to query a video download handler what [special sequence output template tags](https://github.com/rg3/youtube-dl#output-template) it supports.

For example, 
youtube-dl --extractor BusinessVideoHost --list-supported-tags
would output a list of the tags it supports, such as this:
id
title
upload_date
url

**Comment by dstftw** [comment]
List of supported output template sequences depends on concrete run of extractor against concrete URL.
