### ISSUE TITLE
(Previously mislabeled as a duplicate) Feature to output all template tags and their values for URL

### ISSUE THREAD

**Issue by edakiri** [rg3/youtube-dl#15086]
Please, read this rather than presume it is a duplicate.
This is different than the proposition that you wrote was not possible.

This feature request is to enable user to query for a URL, what each special sequence output template tag it was able to fill and its value.
I propose the output be separanted by new lines and tabulators by default.
For example,
youtube-dl --all-tags https://VideoHost.Com./?ID=A1B2C3
would output a list of the tags it supports, such as this:

extractor_id \t VideoHost
id \t A1B2C3
title \t A Video By Any Title
upload_date \t 2000-12-30
url \t https://VideoHost.Com./?ID=A1B2C3

Not Applicable values would be omitted.

**Comment by dstftw** [comment]
No. Use keys from `--dump-json`.
