### ISSUE TITLE
Instagram MPD DASH live stream - ExtractorError

### ISSUE THREAD

**Issue by ganego** [rg3/youtube-dl#15087]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://instagram.ftxl1-1.fna.fbcdn.net/hvideo-ftw1/v/xxxxx-/live-dash/dash-hd/1111111.mpd?_nc_rl=abcdef&oh=ghij&oe=klmn']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2017.12.23
[debug] Python version 3.6.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2017-12-23-9e5e323, ffprobe N-87867-g0655810072
[debug] Proxy map: {}
[generic] 1111111: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1111111: Downloading webpage
[generic] 1111111: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\program files\python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "c:\program files\python34\lib\site-packages\youtube_dl\extractor\common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "c:\program files\python34\lib\site-packages\youtube_dl\extractor\generic.py", line 2181, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "c:\program files\python34\lib\site-packages\youtube_dl\extractor\common.py", line 1069, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

This is the mpd that is on the above address:
```
<?xml version="1.0"?>

<MPD
  type="dynamic"
  xmlns="urn:mpeg:dash:schema:mpd:2011"
  xmlns:xsi="http://www.w3.org/2011/XMLSchema-instance"
  xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd"
  profiles="urn:mpeg:dash:profile:isoff-live:2011"
  availabilityStartTime="2017-12-27T05:24:03-08:00"
  availabilityEndTime="2017-12-27T05:36:51-08:00"
  timeShiftBufferDepth="PT10S"
  suggestedPresentationDelay="PT2S"
  minBufferTime="PT1S"
  publishTime="2017-12-27T05:24:03-08:00"
  minimumUpdatePeriod="PT1S"
  publishFrameTime="0">
  <Period id="dash-hd" start="PT0S">
    <AdaptationSet
      segmentAlignment="true"
      maxWidth="396"
      maxHeight="704"
      maxFrameRate="30">
      <Representation
        id="live-hd-v"
        mimeType="video/mp4"
        codecs="avc1.4d401e"
        width="396"
        height="704"
        frameRate="30"
        startWithSAP="1"
        bandwidth="736441"
        FBQualityClass="sd"
        FBQualityLabel="396p">
        <SegmentTemplate
          presentationTimeOffset="0"
          timescale="1000"
          initialization="../live-hd-v/1111111-init.m4v"
          media="../live-hd-v/1111111-$Time$.m4v">
          <SegmentTimeline>
            <S t="260356" d="1000"/>
            <S t="261356" d="1000"/>
            <S t="262356" d="1034"/>
            <S t="263390" d="1000"/>
            <S t="264390" d="1033"/>
            <S t="265423" d="1000"/>
            <S t="266423" d="1033"/>
            <S t="267456" d="1000"/>
            <S t="268456" d="1000"/>
            <S t="269456" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet segmentAlignment="true">
      <Representation
        id="live-hd-a"
        mimeType="audio/mp4"
        codecs="mp4a.40.2"
        audioSamplingRate="44100"
        startWithSAP="1"
        bandwidth="48563">
        <SegmentTemplate
          presentationTimeOffset="0"
          timescale="1000"
          initialization="../live-hd-a/1111111-init.m4a"
          media="../live-hd-a/1111111-$Time$.m4a">
          <SegmentTimeline>
            <S t="260356" d="1000"/>
            <S t="261356" d="1000"/>
            <S t="262356" d="1034"/>
            <S t="263390" d="1000"/>
            <S t="264390" d="1033"/>
            <S t="265423" d="1000"/>
            <S t="266423" d="1033"/>
            <S t="267456" d="1000"/>
            <S t="268456" d="1000"/>
            <S t="269456" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

### Description of your *issue*, suggested solution and other information

I tried downloading a dash mpd live stream from Instagram, as I was told yt-dl is able to dl mpd dash. I searched through the issues and some old ones say it's not possible, but other reports let me to believe you do now(?).
Anyway I get an ExtractorError for the mpd file above. I cannot give you an URL to test, as live streams only have a duration of a few minutes mostly.
If this cannot be solved with the information above, I could create a live stream and give you the DASH URL for you to test for some time via IRC.

Thank you

**Comment by dstftw** [comment]
DASH livestreams are not supported.

**Comment by ganego** [comment]
What is the difference between dash live stream and dash download from YT?  
Is it not the same downloading of segments and stitching them?  
Will it be implemented in the future?  

Thank you
