### ISSUE TITLE
Problems downloading from Plus7

### ISSUE THREAD

**Issue by torbs723** [rg3/youtube-dl#15096]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\u1\Downloads>"youtube-dl (3).exe" -v --geo-bypass-country=AU https://
7plus.com.au/LIAR?episode-id=LIAR01-006
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--geo-bypass-country=AU', 'https://7plus.com.
au/LIAR?episode-id=LIAR01-006']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.12.23
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 1.158.78.197 (AU) as X-Forwarded-For.
[7plus] LIAR01-006: Downloading JSON metadata
[7plus] LIAR01-006: Downloading m3u8 information
[7plus] LIAR01-006: Downloading m3u8 information
[7plus] LIAR01-006: Downloading MPD manifest
[7plus] LIAR01-006: Downloading MPD manifest
[7plus] LIAR01-006: Downloading JSON metadata
[debug] Default format spec: best/bestvideo+bestaudio
WARNING: You have requested multiple formats but ffmpeg or avconv are not instal
led. The formats won't be merged.
[debug] Invoking downloader on 'https://manifest.prod.boltdns.net/manifest/v1/hl
s/v5/clear/5303576322001/9bdb4de5-38e8-4b60-bf5d-e4ea8e9c5454/a6df9c03-cf26-427b
-a801-cd0159d431d1/10s/rendition.m3u8?fastly_token=NWE0NDUzNWFfYTI5NjJhNDY4NDdhM
DhhOTAxMTgzYzI4MjUzYWY4NzYwMGMwNDVhMzdiNGU0Zjc3YmNkYjdkNTY5ZDM2ZjIwOA%3D%3D'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 280
[download] Destination: Season 1 Episode 6-LIAR01-006.fhls-6806-1.mp4
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1
 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1
 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1
 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1
 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1
 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1
 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1
 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1
 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1
 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1
 (attempt 10 of 10)...
[download] Skipping fragment 1...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 2
 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 2
 (attempt 2 of 10)...
```

---
### Description of your *issue*, suggested solution and other information

I'm trying to download a video from Plus7 with the support for the new site that has been added to youtube-dl.

I've tried with no bypass at all and it gets the JSON, m3u8 etc but when it tries to start the download, all the segments throw a 403 forbidden message. I've tried `--geo-bypass-country=AU` and also tried some with `--proxy="xxx.xxx.xxx.xxx:80"` but nothing seems to work.

What I can't work out though is are the 403 Forbidden messages on the segments a result of geoblocking or something else.

If you want some other examples to try with:
- https://7plus.com.au/HAAW?episode-id=HAAW10-722
- https://7plus.com.au/AST?episode-id=AST-374

Any help or advice would be appreciated.

**Comment by remitamine** [comment]
> What I can't work out though is are the 403 Forbidden messages on the segments a result of geoblocking or something else.

a result of geoblocking.
```
youtube-dl https://7plus.com.au/LIAR?episode-id=LIAR01-006
[7plus] LIAR01-006: Downloading JSON metadata
[7plus] LIAR01-006: Downloading m3u8 information
[7plus] LIAR01-006: Downloading m3u8 information
[7plus] LIAR01-006: Downloading MPD manifest
[7plus] LIAR01-006: Downloading MPD manifest
[7plus] LIAR01-006: Downloading JSON metadata
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 280
[download] Destination: Season 1 Episode 6-LIAR01-006.fhls-4609-1.mp4
[download]   0.2% of ~1.72GiB at 87.77KiB/s ETA 07:06:33
```
