### ISSUE TITLE
Error While downloading

### ISSUE THREAD

**Issue by rahul2333** [rg3/youtube-dl#15100]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://app.pluralsight.com/library/courses/s
sis-advanced/table-of-contents']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.12.23
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] ssis-advanced: Downloading course JSON
[download] Downloading playlist: Advanced Integration Services
[pluralsight:course] playlist Advanced Integration Services: Collected 64 video
ids (downloading 64 of them)
[download] Downloading video 1 of 64
[pluralsight] ssis-adv-m1-0: Downloading course JSON
[pluralsight] ssis-adv-m1-0: Downloading mp4-high viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] ssis-adv-m1-0: Waiting for 4 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\bu
ild\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\bu
ild\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\bu
ild\youtube_dl\extractor\pluralsight.py", line 326, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\bu
ild\youtube_dl\extractor\common.py", line 1069, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.

**Comment by dstftw** [comment]
Did not provide account credentials to youtube-dl.
