### ISSUE TITLE
Support Request for Gloria.tv

### ISSUE THREAD

**Issue by iegolas** [rg3/youtube-dl#15127]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://gloria.tv/video/mQd6aQ4DcC2s2rZAKu8Rs3qvb
- Playlist: https://gloria.tv/album/cFXpctCpmAmE693vebkarncnG
- UserPlaylist: https://gloria.tv/antoniowillen

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

The site it's similar to YouTube and has a of videos. Will be nice to support it.

Thanks

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).

**Comment by iegolas** [comment]
Gloria.Tv doesn't infring the copyright, just see the terms and conditions. 

https://gloria.tv/termsofservice/

It's like YouTube, the content with license will be removed.

Could you re-evaluate that?

Thanks

**Comment by iegolas** [comment]
I choose random links as examples, maybe not the best ones, but it's a platform like StreamCloud, Vimeo, YouTube...
