### ISSUE TITLE
[Youku] Crash when episode count is wrong

### ISSUE THREAD

**Issue by CoXier** [rg3/youtube-dl#15135]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
Here is a test url: http://list.youku.com/show/id_z20eb4acaf5c211e3b2ad.html

```bash
youtube-dl http://list.youku.com/show/id_z20eb4acaf5c211e3b2ad.html\?spm\=a2h0j.8191423.module_basic_title.5\~A\!2 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://list.youku.com/show/id_z20eb4acaf5c211e3b2ad.html?spm=a2h0j.8191423.module_basic_title.5~A!2', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.23
[debug] Python version 2.7.13 - Darwin-17.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[youku:show] z20eb4acaf5c211e3b2ad: Downloading webpage
[youku:show] z20eb4acaf5c211e3b2ad: Downloading initial playlist data page
[youku:show] z20eb4acaf5c211e3b2ad: Downloading playlist data page 2
ERROR: An extractor error has occurred. (caused by KeyError(u'html',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youku.py", line 292, in _real_extract
    'stage': reload_id,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youku.py", line 254, in _extract_entries
    transform_source=lambda s: js_to_json(strip_jsonp(s)))['html']
KeyError: u'html'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 451, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'html',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

The episode count is 16 however it has three modules 1-40 41-80 81-86.

Obviously it's youku's fault.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by CoXier** [comment]
I have updated information.

**Comment by CoXier** [comment]
https://github.com/CoXier/youtube-dl/commit/5936bc6ed7aa2579c3edeca54d29ce30f3ba8d68 solves this issue.

**Comment by dstftw** [comment]
Do not close the issue when fix is not merged.
