### ISSUE TITLE
Feature Request: Renaming of files downloaded from PluralSight according to Course Sequence

### ISSUE THREAD

**Issue by xyphanajay** [rg3/youtube-dl#15136]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Feature Request:
- Videos downloaded from PluralSight using youtube-dl are named on Video Name followed by Module Number and Video Number.
- It become pretty hard to play videos according to course sequence as their Module no and Video no are written after Video file name.
- It would be great if *Module no and Video no are written before Video name*, so that everyone will be able watch videos according course sequence without wasting time in finding exact video sequence,
- I have written a piece of code for renaming them, according to the following Guide Line.
---

    Video Naming Before:
	 General: Video Name-ModuleNo-VideoNo.mp4
	 Example: Introduction-ethical-hacking-enumeration-m1-01.mp4

    Intended Video Naming:
	 General: ModuleNo-VideoNo File-Name.mp4
	 Example: m1-01 Introduction-ethical-hacking-enumeration.mp4
---

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#output-template
