### ISSUE TITLE
Add platform like youtube, Gloria.

### ISSUE THREAD

**Issue by iegolas** [rg3/youtube-dl#15132]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://gloria.tv/video/1cEUD2SREzgWAKNFUCkXn7ggr

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

You could see the terms of the site: https://gloria.tv/termsofservice/ it's similar to youtube, vimeo...
---

### Description of your *issue*, suggested solution and other information

I sent I request (https://github.com/rg3/youtube-dl/issues/15127) with a video that could have copyrigth. Now i put one that doesn't have copyright.
If you see the terms of the platform violate the copyright is not allowed.

I saw a requested a year ago about that. 

There are thousands of videos without copyright. Could you evaluate to add this platform ?
Do you want to have more information , just let me know if you need more examples.

Thanks.

**Comment by dstftw** [comment]
https://gloria.tv/video/1cEUD2SREzgWAKNFUCkXn7ggr is handled by generic extractor.
