### ISSUE TITLE
http://alnoortv.co site-support-request

### ISSUE THREAD

**Issue by h-q** [rg3/youtube-dl#15142]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The purpose of this *issue* is *site support request*:

```
$ youtube-dl -v -i --prefer-ffmpeg http://alnoortv.co/public/video-detail/100/en
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-i', u'--prefer-ffmpeg', u'http://alnoortv.co/public/video-detail/100/en']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.31
[debug] Python version 2.7.10 - Darwin-17.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] en: Requesting header
WARNING: Falling back on generic information extractor.
[generic] en: Downloading webpage
[generic] en: Extracting information
ERROR: Unsupported URL: http://alnoortv.co/public/video-detail/100/en
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2176, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 21, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3086, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://alnoortv.co/public/video-detail/100/en

```
---

### example URL:
- Single video: http://alnoortv.co/public/video-detail/100/en

---

### Description of your *issue*:

Site switched names from http://tv-alnoor.com to http://alnoortv.co . I appreciate adding support to the new site. Thank you!

**Comment by remitamine** [comment]
https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free

**Comment by h-q** [comment]
Dear @remitamine the site is legit. From http://alnoortv.co/public/home/en 

_Our website is the first and only Arabic site which **got the broadcast rights of the Turkish TV series** "Resurrection of Ertugrul, that enjoys large audience in the Arab world. That right was **given under a partnership agreement with the Turkish Radio and Television institution TRT, which produces it**._

_**Noor Website got the broadcast and translation rights of the series**: Resurrection of Ertugrul", "Filinta", "Sultan Abdul Hamid and Yunus Emre" and "Seddülbahir". In addition to "The Battle of Kut Al Amara" which will be broadcasted soon._

If you have a reason to believe otherwise, please let me know.

**Comment by remitamine** [comment]
http://www.trt.net.tr/shqip/video/kultura-dhe-arti/ertugrul-do-te-transmetohet-edhe-ne-katar

**Comment by h-q** [comment]
Thank you @remitanine

This merely states that from January 16th onwards, it will be aired on Qatar TV. Al Noor is still a legit site. 

Kind regards.

**Comment by h-q** [comment]
Dear @remitamine I appreciate if you would consider re-opening the issue. This works, by the way:

`youtube-dl -i --prefer-ffmpeg 'https://player.vimeo.com/video/245521393/' --referer 'http://alnoortv.co/public/video-detail/100/en'`

**Comment by remitamine** [comment]
- َQatar TV obtained **exclusive** rights to broadcast Diriliş Ertuğrul series in arabic.
- if the content they are showing is licensed then why they keep the TRT logo and add their logo as well(unlike Qatar TV that shows only their logo), so it most likely it's a web-rip version from free episodes in TRT channel website.

so to avoid any doubts it would be better for you give a proof that they actually own a license.

**Comment by remitamine** [comment]
also some of the previous youtube channels for this website(alnoor tv) has been banned because of the copyright infringement.
