### ISSUE TITLE
Downloading 720 instead of 1080 even with ffmpeg installed

### ISSUE THREAD

**Issue by TarekSalama** [rg3/youtube-dl#15144]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: [u'--no-overwrites', u'--no-cache-dir', u'--ignore-errors', u'--batch-file', u'/Users/tareksalama/Desktop/batchvideos.txt', u'-o', u'/Users/tareksalama/Desktop/Youtube/downloads/%(uploader)s/%(title)s_%(uploader)s_%(id)s.%(ext)s', u'-f', u'best', u'-v']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-U']
[debug] Batch file urls: [u'https://www.youtube.com/watch?v=p80Kqj6rV50s']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.31
[debug] Python version 2.7.10 - Darwin-17.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=p80Kqj6rV50s

---

### Description of your *issue*, suggested solution and other information

I have been getting most if not all of my downloads in 720 instead of 1080 even though - as far as I know ffmpeg needs to be installed for 1080 + best audio - ffmpeg is indeed installed.

Am I doing something wrong or is it a bug?

**Comment by dstftw** [comment]
Post the verbose log clearly demonstrating the problem.

**Comment by Hrxn** [comment]
From your system config:

> [debug] System config: ((...)), u'-f', u'best', u'-v']

`-f best` chooses best available format as _a single file_, for 1080p use `-f bestvideo+bestaudio` (or just the default format setting)

**Comment by TarekSalama** [comment]
@Hrxn Is there a way to specify 1080 + best audio and perhaps mp4 instead of mkv?

**Comment by Hrxn** [comment]
Sure, maybe try something like `-f  'bestvideo[ext=mp4]+bestaudio[ext=m4a]' `

**Comment by TarekSalama** [comment]
@Hrxn Thanks for the reply. One last question, some videos/websites don't support mp4. Is there a way to make youtube-dl fallback to the regular video settings?

**Comment by Hrxn** [comment]
Sure, try something like this:
`-f '(bestvideo[ext=mp4]/bestvideo)+(bestaudio[ext=m4a]/bestaudio)/best'

**Comment by TarekSalama** [comment]
Thanks a lot @Hrxn Really helped :)
