### ISSUE TITLE
Can't download a specific Lynda.com video

### ISSUE THREAD

**Issue by PsychotycGoat** [rg3/youtube-dl#15159]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

youtube-dl -v --ignore-config  --cookies ~/Downloads/cookiesl.txt -o "Courses/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" --write-sub --download-archive lynda.dled.txt https://www.lynda.com/Illustrator-tutorials/Time-lapse-retro-superhero/165607/180668-4.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'--cookies', u'/home/dany/Downloads/cookiesl.txt', u'-o', u'Courses/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', u'--write-sub', u'--download-archive', u'lynda.dled.txt', u'https://www.lynda.com/Illustrator-tutorials/Time-lapse-retro-superhero/165607/180668-4.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.31
[debug] Python version 2.7.6 - Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: none
[debug] Proxy map: {}
[lynda] 180668: Downloading video JSON
[lynda] 180668: Checking 1-540 video format URL
[lynda] 180668: Checking 1-720 video format URL
[lynda] 180668: Checking 1-360 video format URL
[lynda] 180668: Checking 0-540 video format URL
[lynda] 180668: Checking 0-720 video format URL
[lynda] 180668: Checking 0-360 video format URL
[debug] Default format spec: best/bestvideo+bestaudio
[info] Writing video subtitles to: Courses/NA/NA - Time lapse of the retro superhero.en.srt
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1988, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 795, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 849, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1622, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1804, in process_info
KeyError: u'url'

Every other video so far works fine, it's only this specific one that I found. The NA/NA in the file name is only there because I didn't use the playlist URL but instead the direct link to the video. I get the same error with the playlist download.

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.
