### ISSUE TITLE
Does youtube-dl support corporate authentication on Lynda.com?

### ISSUE THREAD

**Issue by prodigy6630** [rg3/youtube-dl#15158]
I'm struggling to download from Lynda.com using corporate login. I used cookie.txt Chrome extension to bypass login parameters for the command below but it only downloads to the 4 free videos.

youtube-dl --cookies cookies.txt "https://www.lynda.com/vSphere-tutorials/VMware-vSphere-Certified-Professional-vSphere-6-Cert-Prep-2V0-621-Basics/583671-2.html" -o "%(playlist)s [Lynda.com]/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s"

[lynda:course] 583671: Downloading course JSON
WARNING: 16 videos are only available for members (or paid members) and will not be downloaded. Use --username and --password options to provide lynda.com account credentials.
[download] Downloading playlist: VMware vSphere Certified Professional on vSphere 6 Cert Prep (2V0-621): The Basics
[lynda:course] playlist VMware vSphere Certified Professional on vSphere 6 CertPrep (2V0-621): The Basics: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
[lynda] 628407: Downloading video JSON
[lynda] 628407: Checking 1-540 video format URL
[lynda] 628407: Checking 1-720 video format URL
[lynda] 628407: Checking 1-360 video format URL
[lynda] 628407: Checking 0-540 video format URL
[lynda] 628407: Checking 0-720 video format URL
[lynda] 628407: Checking 0-360 video format URL
[download] Destination: VMware vSphere Certified Professional on vSphere 6 CertPrep (2V0-621) - The Basics [Lynda.com]\1 - Introduction\1 - Welcome.mp4
[download] 100% of 4.96MiB in 00:03
[download] Downloading video 2 of 4
[lynda] 628408: Downloading video JSON
[lynda] 628408: Checking 1-540 video format URL
[lynda] 628408: Checking 1-720 video format URL
[lynda] 628408: Checking 1-360 video format URL
[lynda] 628408: Checking 0-540 video format URL
[lynda] 628408: Checking 0-720 video format URL
[lynda] 628408: Checking 0-360 video format URL
[download] Destination: VMware vSphere Certified Professional on vSphere 6 CertPrep (2V0-621) - The Basics [Lynda.com]\1 - Introduction\2 - Before we begin.mp4
[download] 100% of 7.05MiB in 00:07
[download] Downloading video 3 of 4
[lynda] 628411: Downloading video JSON
[lynda] 628411: Checking 1-540 video format URL
[lynda] 628411: Checking 1-720 video format URL
[lynda] 628411: Checking 1-360 video format URL
[lynda] 628411: Checking 0-540 video format URL
[lynda] 628411: Checking 0-720 video format URL
[lynda] 628411: Checking 0-360 video format URL
[download] Destination: VMware vSphere Certified Professional on vSphere 6 CertPrep (2V0-621) - The Basics [Lynda.com]\2 - 1. Exam Details\3 - Exam blueprint.mp4
[download] 100% of 8.23MiB in 00:05
[download] Downloading video 4 of 4
[lynda] 628417: Downloading video JSON
[lynda] 628417: Checking 1-540 video format URL
[lynda] 628417: Checking 1-720 video format URL
[lynda] 628417: Checking 1-360 video format URL
[lynda] 628417: Checking 0-540 video format URL
[lynda] 628417: Checking 0-720 video format URL
[lynda] 628417: Checking 0-360 video format URL
[download] Destination: VMware vSphere Certified Professional on vSphere 6 CertPrep (2V0-621) - The Basics [Lynda.com]\3 - 2. The Exam Blueprint\4 - VMware vSphere - Configure and manage networking.mp4
[download] 100% of 6.52MiB in 00:04
[download] Finished downloading playlist: VMware vSphere Certified Professionalon vSphere 6 Cert Prep (2V0-621): The Basics

**Comment by PsychotycGoat** [comment]
I use the chrome extension cookies.txt, extension ID njabckikapfpffapmjgojcnbfjonfjfg , and it works perfectly. I think you need to update your cookie about every 24h, but might be longer.

**Comment by prodigy6630** [comment]
I tried it on a different machine as well, so I doubt it has to do with a stale cookie.

**Comment by PsychotycGoat** [comment]
Maybe the cookie isn't in the expected format? What is your process to get the cookies.txt file?

**Comment by prodigy6630** [comment]
I click on the Export cookies.txt extension and click "cookies for this tab click here" to download the cookies.txt. This is saved into the same folder youtube-dl is in.

# HTTP Cookie File for lynda.com by Genuinous @genuinous.
# To download cookies for this tab click here, or download all cookies.
# Usage Examples:
#   1) wget -x --load-cookies cookies.txt "https://www.lynda.com/vSphere-tutorials/Welcome/583671/628407-4.html?srchtrk=index%3a1%0alinktypeid%3a2%0aq%3aVMware+vSphere+Certified+Professional+on+vSphere+6+Cert+Prep+(2V0-621)%3a+The+Basics%0apage%3a1%0as%3arelevance%0asa%3atrue%0aproducttypeid%3a2"
#   2) curl --cookie cookies.txt "https://www.lynda.com/vSphere-tutorials/Welcome/583671/628407-4.html?srchtrk=index%3a1%0alinktypeid%3a2%0aq%3aVMware+vSphere+Certified+Professional+on+vSphere+6+Cert+Prep+(2V0-621)%3a+The+Basics%0apage%3a1%0as%3arelevance%0asa%3atrue%0aproducttypeid%3a2"
#   3) aria2c --load-cookies cookies.txt "https://www.lynda.com/vSphere-tutorials/Welcome/583671/628407-4.html?srchtrk=index%3a1%0alinktypeid%3a2%0aq%3aVMware+vSphere+Certified+Professional+on+vSphere+6+Cert+Prep+(2V0-621)%3a+The+Basics%0apage%3a1%0as%3arelevance%0asa%3atrue%0aproducttypeid%3a2"
#

**Comment by dstftw** [comment]
You should use "all cookies".

**Comment by prodigy6630** [comment]
Thanks, just what I needed. It's working now with "all cookies'. Much appreciated.

**Comment by blueray453** [comment]
https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg

`cookies for this tab` works fine

**Comment by rotemdan** [comment]
I've created a simple `cookies.txt` exporter extension which I've verified to work with a `lynda.com` organizational account. Please try it and see if it solves your problem (it is available for both Firefox and Chrome):
> https://github.com/rotemdan/ExportCookies

The issue with some exporters (such as the [`cookies.txt`](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/) extension for Firefox) is that they add the `#HttpOnly_` prefix to `HttpOnly` cookies. This doesn't seem to be parsed correctly by `youtube-dl`. The exporter I published doesn't add this prefix.

Of course the browser need to be properly logged in to `lynda.com` (or any other website) for this to work.

Please let me know of any issues.
