### ISSUE TITLE
Clarifying the marformed stream error message

### ISSUE THREAD

**Issue by marmistrz** [rg3/youtube-dl#15155]
Currently, if a video stream is malformed, a warning is issued and the user is asked to install ffmpeg
https://github.com/rg3/youtube-dl/blob/54009c246e8eed38cfa8dc3eecb5619c1c81a1f2/youtube_dl/YoutubeDL.py#L1962

The warning should state, what the command to fix it should be. Sometimes we want to use computers with high-network bandwidth to download the video and fix it, if needed, on our computers with root access, where we can install arbitrary software, such as `ffmpeg` or `avconv`. 

Alternatively, the docs should say more about it - currently searching for `malform` in the readme and the manpage returns nothing.

**Comment by dstftw** [comment]
How "command to fix" will look like depends on your environment. Current message gives you well enough information of what you should do.

**Comment by marmistrz** [comment]
Honestly, I don't know what it means more than "the stream is broken". Using the search engine to find "how to fix a malformed stream using avconv" yields nothing valuable. 

I could possibly just copy-paste the args from here [1], but an average user won't dig through the sources to find out, which commands are the ones to use...

[1] https://github.com/rg3/youtube-dl/blob/d2ae7e24e5c574fa45621771a134e58b21443e5f/youtube_dl/postprocessor/ffmpeg.py#L544

**Comment by dstftw** [comment]
You don't need to do anything yourself. You only need to have ffmpeg installed. That's what an average used should do.

**Comment by marmistrz** [comment]
@dstftw what if you don't have root access?

**Comment by dstftw** [comment]
You don't need root access.

**Comment by marmistrz** [comment]
Installing packages via the package-manager needs root access, compiling ffmpeg/avconv from sources is much too much for an average user.

**Comment by dstftw** [comment]
You don't need to install it per se. You only need ffmpeg to be in `$PATH`.

**Comment by marmistrz** [comment]
Ok, I didn't notice that ffmpeg has static builds available.
