### ISSUE TITLE
ERROR: m3u8 download detected but ffmpeg or avconv could not be found.

### ISSUE THREAD

**Issue by rossocenere** [rg3/youtube-dl#15169]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

Dear community, I'm totally new to the forum and a total beginner in programming. I've recently installed youtube-dl and, even if I read the FAQ and topics similar to this one, I couldn't easily solve my problem. I hope you could easily explain where I am mistaken, because I don't seem to be able to do it as now. 

I am trying to download a video, but when I get out of youtube I usually meet this problem:

`ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.`

How could I solve it? I read that it can be related to the path, but I have no idea how to interact with it.
Thanks for your help.

**Comment by dstftw** [comment]
Error message clearly states what to do. Concrete steps depend on your OS and environment.
