### ISSUE TITLE
Funimation not working (unable to extract)

### ISSUE THREAD

**Issue by gabrielvis** [rg3/youtube-dl#15160]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
i cant figure out how to do this i get "` youtube-dl` is not recognized as an internal or external command , operable program or batch file 
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.funimation.com/shows/school-rumble/2nd-semester-hostesses-are-culture-comics-are-culture-cake-is-also-culture/uncut/?lang=english&a=13

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

when i try to play funimation video i get this error message unable to extract web url

**Comment by yan12125** [comment]
See [this FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)

**Comment by gabrielvis** [comment]
ahh i use svp tube so i cant change the way i input the video url, i can only copy it

**Comment by yan12125** [comment]
You may want to contact SVP developers. Apparently they did not use youtube-dl correctly.

**Comment by gabrielvis** [comment]
I did they said I need to wait for youtube-dl to make an update

**Comment by yan12125** [comment]
> ` youtube-dl` is not recognized as an internal or external command , operable program or batch file 

This error indicates either you or SVP does not install or run youtube-dl correctly. Check https://github.com/rg3/youtube-dl/blob/master/README.md for installation and basic usage.
