### ISSUE TITLE
[ccc] downloads low resolution video by default

### ISSUE THREAD

**Issue by 1183519e** [rg3/youtube-dl#15162]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-sv', '--all-formats', '--get-format', 'https://media.ccc.de/v/34c3-9064-the_ultimate_apollo_guidance_computer_talk']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.31
[debug] Python version 3.6.3 - Linux-4.13.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, rtmpdump 2.4
[debug] Proxy map: {}
eng-opus - audio only
eng-mp3 - audio only
eng-slides-h264-sd - 720x576
eng-h264-hd - 1920x1080
deu-h264-hd - 1920x1080
fra-h264-hd - 1920x1080
eng-fra-deu-h264-sd - 720x576
eng-fra-deu-slides-h264-hd - 1920x1080
eng-fra-deu-h264-hd - 1920x1080
eng-fra-deu-webm-hd - 1920x1080
eng-fra-deu-webm-sd - 720x576
```
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-sv', '--get-format', 'https://media.ccc.de/v/34c3-9064-the_ultimate_apollo_guidance_computer_talk']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.31
[debug] Python version 3.6.3 - Linux-4.13.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
eng-fra-deu-webm-sd - 720x576

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Observed behaviour: When downloading a video from https://media.ccc.de without specifying the desired video quality, a 720x576 video is downloaded. 
Expected behaviour: The highest resolution video would be downloaded. In this case "eng-fra-deu-webm-hd - 1920x1080" or maybe "eng-fra-deu-h264-hd - 1920x1080".
Workaround: add command line argument "-f eng-fra-deu-webm-hd"

**Comment by dstftw** [comment]
eng-fra-deu-webm-sd has higher filesize that takes precedence over resolution.
