### ISSUE TITLE
ffmpeg not detected, 1080p format not recognized

### ISSUE THREAD

**Issue by Nozalys** [rg3/youtube-dl#15163]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
D:\Divers\YTcrawler\test>youtube-dl.exe -v --proxy 135.245.192.7:8000 -f '(bestvideo[ext=mp4]/bestvideo)+(bestaudio[ext=m4a]/bestaudio)/best' -o "\videos\%(uploader)s\%(upload_date)s - %(title)s - %(id)s.%(ext)s" -w --write-description --ffmpeg-location 'D:\Divers\YTcrawler\test\' 7opE3nKPIxQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--proxy', '135.245.192.7:8000', '-f', "'(bestvideo[ext=mp4]/bestvideo)+(bestaudio[ext=m4a]/bestaudio)/best'", '-o', '\\videos\\%(uploader)s\\%(upload_date)s - %(title)s - %(id)s.%(ext)s', '-w', '--write-description', '--ffmpeg-location', "'D:\\Divers\\YTcrawler\\test\\'", '7opE3nKPIxQ']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.12.31
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
WARNING: ffmpeg-location 'D:\Divers\YTcrawler\test\' does not exist! Continuing without avconv/ffmpeg.
[debug] exe versions: none
[debug] Proxy map: {'https': '135.245.192.7:8000', 'http': '135.245.192.7:8000'}
[youtube] 7opE3nKPIxQ: Downloading webpage
[youtube] 7opE3nKPIxQ: Downloading video info webpage
[youtube] 7opE3nKPIxQ: Extracting video information
[youtube] 7opE3nKPIxQ: Downloading MPD manifest
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiyv5xz5s\build\youtube_dl\YoutubeDL.py", line 795, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiyv5xz5s\build\youtube_dl\YoutubeDL.py", line 849, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiyv5xz5s\build\youtube_dl\YoutubeDL.py", line 1614, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available
```

+ffmpeg in the same directory **and** directory in the path :

```
D:\Divers\YTcrawler\test>ffmpeg.exe -version
ffmpeg version N-89674-g57d0c24132 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7.2.0 (GCC)
configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enabl
e-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enab
le-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-li
bopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora
--enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-l
ibx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidsta
b --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-amf --ena
ble-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-li
bmfx
libavutil      56.  7.100 / 56.  7.100
libavcodec     58.  9.100 / 58.  9.100
libavformat    58.  3.100 / 58.  3.100
libavdevice    58.  0.100 / 58.  0.100
libavfilter     7.  8.100 /  7.  8.100
libswscale      5.  0.101 /  5.  0.101
libswresample   3.  0.101 /  3.  0.101
libpostproc    55.  0.100 / 55.  0.100
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=7opE3nKPIxQ
- Any youtube video which provide 1080p, 1080p50 or 1080p60 in my case

---

### Description of your *issue*, suggested solution and other information

Hi,
Firstly thanks a lot for this incredible application which works well !

I'm facing an issue that I was not be able to troubleshoot by myself. I have a youtube video link, which provide 1080p video quality. With defaults settings, I'm able to download the 720p format. But I tried all possible settings and did not succeed in download the 1080p version.

I'm running on Windows 7 OS, I put youtube-dl.exe and ffmpeg.exe + libs in the same directory, and I added this directory to the PATH variable.

When I do not specify the -f option, it download the 720p mp4 file, so my proxy setting is good.

When I run the command-line above without the option --ffmpeg-location, I have the error "_ERROR: requested format not available_". With the --ffmpeg-location option, whatever I put after, youtube-dl tell me "_WARNING: ffmpeg-location 'blahblah' does not exist! Continuing without avconv/ffmpeg._"

I suppose the "_requested format not available_" error comes because youtube-dl don't detect ffmpeg, so, how should I declare the path or the option to make it working ?

Best regards,
Nozalys

**Comment by dstftw** [comment]
cmd.exe does not support support single quotes.

**Comment by Nozalys** [comment]
Wow.. sorry for that basic mistake, and thanks for your ultra fast support !
