### ISSUE TITLE
ERROR: Unable to log in (from one developer to another)

### ISSUE THREAD

**Issue by edhaack** [rg3/youtube-dl#15175]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

The following is most likely user-error. Prior to today, all was working perfectly. However, I recently had to kill a running process while downloading, from a previous version, then as advised used the current version, with no difference. I've confirmed that my credentials are correct and able to login to the site. I have searched forums and other comments to no avail. Here is the general error:

ERROR: Unable to log in

Attached, you will find a zipped text file of the full command and dump-pages.

[youtube-dl-dumppages.zip](https://github.com/rg3/youtube-dl/files/1605092/youtube-dl-dumppages.zip)

Any and all help would be appreciated!

Ed Haack

PS: I suspect that something has gotten cached (or remnants of another run) in my Windows environment, but aren't yet familiar enough the Python to troubleshoot it myself.

**Comment by dstftw** [comment]
For any further investigations you must provide account credentials.

**Comment by edhaack** [comment]
I am sorry. I will not provide my credentials. If you can not continue, then I will find another solution.

I would have thought the data-dump would be enough to troubleshoot.

**Comment by dstftw** [comment]
That's probably enough but I'm not going to do so without the actual check from my side.
