### ISSUE TITLE
Youtube record label protected videos. VEVO for example

### ISSUE THREAD

**Issue by BenasPaulikas** [rg3/youtube-dl#15172]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
We are receiving letters from "record label" companies claiming we are copying their work from youtube.

I've checked `license` attribute of each video and most of them says "Standard YouTube License" so I can't use it..

Is there any way to find out that this uploader will do anything to stop us or that video is protected under some license ?

**Comment by dstftw** [comment]
How is this even related to youtube-dl? Regulate your relationships with uploader on your own.

**Comment by BenasPaulikas** [comment]
https://github.com/rg3/youtube-dl/issues/1105 <- I thought you are working everyday to make these "protected" videos like VEVO downloadable via youtube-dl. And you do it by signature length or some other  magic stuff. If yes maybe you could include param saying this video is "protected" in --dump-json ?

Correct me if I'm very wrong.

Thank you a lot!
