### ISSUE TITLE
thank you !

### ISSUE THREAD

**Issue by janvankerckhoven** [rg3/youtube-dl#15170]
Because there isn't any like-button or comment section: I just want to thank all of you guys for the work you're doing here. I'm using youtube-dl on a daily basis for my work in education and I can 't miss it anymore. Special thanks for the people who made download from vrtnu.be possible.

**Comment by StevenDTX** [comment]
You can donate to the project to show your appreciation.

http://rg3.github.io/youtube-dl/donations.html
