### ISSUE TITLE
Downloading audio only with output to specific folder  but will not work

### ISSUE THREAD

**Issue by bluesaphiresky** [rg3/youtube-dl#15176]
youtube-dl --extract-audio --audio-format mp3 -o "f:\VODs\youtube-dl\audio\"
https://www.youtube.com/watch?v=gRlpR9HrrUs

When i do this i get all sorts of warnings i tried messing around trying all sort of different ways but i would to just directly rip the audio and save it in different directory as i showed above any information needed i will get it thanks guys.

**Comment by dstftw** [comment]
Read how to use output template: https://github.com/rg3/youtube-dl#output-template.
