### ISSUE TITLE
ssl.c:590 error on Android

### ISSUE THREAD

**Issue by eeehhh** [rg3/youtube-dl#15181]
"

-->youtube-dl --version
2017.12.31
-->youtube-dl -o veny1.mpv https://youtu.be/ALL1FgicrTg
[youtube] ALL1FgicrTg: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

"

Hello!

I am trying to latest youtube-dl on Android per these instructions:
https://www.arulraj.net/2015/11/download-any-videos-in-android-using-youtube-dl.html

Installation went fine, but when I try to download, I get a SSL error

**Comment by yan12125** [comment]
You'll need to ask QPython developers. SSL on Android is tricky and most likely they didn't do it correct.

Or use ```--no-check-certificate``` if you don't care about security.
