### ISSUE TITLE
periscope.tv does not give resolution note. 

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#15183]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

```
% youtube-dl --version
2017.12.31
```

Then trying to understand if there are any formats and any resolutions the site tells -

```
% youtube-dl -F "https://www.pscp.tv/w/1ypJdNQnQRyKW"       
[periscope] 1ypJdNQnQRyKW: Downloading JSON metadata
[periscope] 1ypJdNQnQRyKW: Downloading JSON metadata
[periscope] 1ypJdNQnQRyKW: Downloading m3u8 information
[info] Available formats for 1ypJdNQnQRyKW:
format code  extension  resolution note
replay       mp4        unknown    
```

```
% youtube-dl --verbose "https://www.pscp.tv/w/1ypJdNQnQRyKW"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.pscp.tv/w/1ypJdNQnQRyKW']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.06
[debug] Python version 3.6.4 - Linux-4.14.0-2-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.4.1-1, ffprobe 3.4.1-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[periscope] 1ypJdNQnQRyKW: Downloading JSON metadata
[periscope] 1ypJdNQnQRyKW: Downloading JSON metadata
[periscope] 1ypJdNQnQRyKW: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://prod-video-eu-central-1.periscope.tv/xpObpjtMXqK9pi8fdEXvz-2JUCkDg7RNNeyQ3P2IwiNVk3NKMNwzjLAcSxtf8O15GCTWnFuS1QWtTjobeiqjMw/replay/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/playlist_16931665770785186795.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 532
[download] Destination: CNBC-TV18 - .@UIDAI CEO Ajay Bhushan Pandey on the Tribune report which says #Aadhaar details are on sale for Rs 500 #Excl-1ypJdNQnQRyKW.mp4
[download] 100% of 94.49MiB in 07:34
[debug] ffmpeg command line: ffprobe -show_streams 'file:CNBC-TV18 - .@UIDAI CEO Ajay Bhushan Pandey on the Tribune report which says #Aadhaar details are on sale for Rs 500 #Excl-1ypJdNQnQRyKW.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "CNBC-TV18 - .@UIDAI CEO Ajay Bhushan Pandey on the Tribune report which says #Aadhaar details are on sale for Rs 500 #Excl-1ypJdNQnQRyKW.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:CNBC-TV18 - .@UIDAI CEO Ajay Bhushan Pandey on the Tribune report which says #Aadhaar details are on sale for Rs 500 #Excl-1ypJdNQnQRyKW.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:CNBC-TV18 - .@UIDAI CEO Ajay Bhushan Pandey on the Tribune report which says #Aadhaar details are on sale for Rs 500 #Excl-1ypJdNQnQRyKW.temp.mp4'
shirish@debian ~/Videos % youtube-dl -F "https://www.pscp.tv/w/1ypJdNQnQRyKW"
```

Using mediainfo found out it was 640x360 pixels. Dunno why ffmpeg had to get involved when it streams fine.

**Comment by dstftw** [comment]
No such meta data is available prior to downloading.
