### ISSUE TITLE
WARNING: 749423 Problem

### ISSUE THREAD

**Issue by SAAIN11** [rg3/youtube-dl#15209]
Hello Guys,
When i use youtube-dl to download 1080p episode from crunchyroll with premium account this massage appeared after finishing download the episode 

" WARNING: 749423: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically "
**What does this massage mean**

**Comment by Hrxn** [comment]
Do you have FFmpeg or avconv?

**Comment by SAAIN11** [comment]
No 
Do I have to download it?
and How i use it ?

**Comment by Hrxn** [comment]
Yes. Depends on your OS. And you did not post any log with `-v`
