### ISSUE TITLE
Failed to download live youtube stream youtube-dl version 2018.01.07

### ISSUE THREAD

**Issue by artshevtsov** [rg3/youtube-dl#15208]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.07**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v https://www.youtube.com/watch?v=b29rPteACgY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=b29rPteACgY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.07
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-104-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 3.4.1-1, avprobe 3.4.1-1, ffmpeg 3.4.1-1, ffprobe 3.4.1-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] b29rPteACgY: Downloading webpage
[youtube] b29rPteACgY: Downloading video info webpage
[youtube] b29rPteACgY: Extracting video information
[youtube] b29rPteACgY: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[download] СТРИМОбсуждаем АТД Субару и отвечаю на вопросы. В гостях Тимур Доктор.-b29rPteACgY.mp4 has already been downloaded and merged
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video (Live stream): https://www.youtube.com/watch?v=b29rPteACgY

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

```
youtube-dl -F https://www.youtube.com/watch?v=b29rPteACgY
[youtube] b29rPteACgY: Downloading webpage
[youtube] b29rPteACgY: Downloading video info webpage
[youtube] b29rPteACgY: Extracting video information
[youtube] b29rPteACgY: Downloading MPD manifest
[info] Available formats for b29rPteACgY:
format code  extension  resolution note
140          m4a        audio only DASH audio  144k , m4a_dash container, mp4a.40.2@128k
160          mp4        256x144    144p  124k , avc1.4d400c, 30fps, video only
133          mp4        426x240    240p  258k , avc1.4d4015, 30fps, video only
134          mp4        640x360    360p  646k , avc1.4d401e, 30fps, video only
135          mp4        854x480    480p 1171k , avc1.4d401f, 30fps, video only
136          mp4        1280x720   720p 2326k , avc1.4d401f, 30fps, video only (best)
```
----
```
youtube-dl -g https://www.youtube.com/watch?v=b29rPteACgY
https://r1---sn-gvnuxaxjvh-axqz.googlevideo.com/videoplayback?itag=136&hang=1&ipbits=0&mime=video%2Fmp4&key=yt6&expire=1515558104&noclen=1&aitags=133%2C134%2C135%2C136%2C160&mm=32&mn=sn-gvnuxaxjvh-axqz&signature=DBA7BB9CD06F418288740344BB749833FDDA767E.38233933541BBF8B0DCE0B7EDDE70C9D34ED12BE&ms=lv&mt=1515536418&mv=m&cmbypass=yes&ei=eEBVWv2FMMWiyAWVpozACg&sparams=aitags%2Ccmbypass%2Cei%2Cgcr%2Cgir%2Chang%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clive%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnoclen%2Cpl%2Crequiressl%2Csource%2Cexpire&ip=89.110.25.71&id=b29rPteACgY.0&keepalive=yes&gir=yes&requiressl=yes&source=yt_live_broadcast&gcr=ru&live=1&initcwndbps=763750&pl=18&ratebypass=yes
https://r1---sn-gvnuxaxjvh-axqz.googlevideo.com/videoplayback?itag=140&hang=1&ipbits=0&mime=audio%2Fmp4&key=yt6&expire=1515558104&noclen=1&mm=32&mn=sn-gvnuxaxjvh-axqz&signature=877B6E3901765FEE2ED2740AA93649803AA3E354.B990982F27169BD6F182B11BE140037174431D21&ms=lv&mt=1515536418&mv=m&cmbypass=yes&ei=eEBVWv2FMMWiyAWVpozACg&sparams=cmbypass%2Ccompress%2Cei%2Cgcr%2Cgir%2Chang%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clive%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnoclen%2Cpl%2Crequiressl%2Csource%2Cexpire&ip=89.110.25.71&compress=yes&keepalive=yes&gir=yes&requiressl=yes&id=b29rPteACgY.0&source=yt_live_broadcast&gcr=ru&live=1&initcwndbps=763750&pl=18&ratebypass=yes
```

**Comment by dstftw** [comment]
>Live stream offline

Does not play in browser either.
