### ISSUE TITLE
[Youtube] youtube-dl fails to retrieve the hls manifest for livestreams

### ISSUE THREAD

**Issue by FDMX2** [rg3/youtube-dl#15202]
The way to retrieve the hls manifest for youtube livestreams changed.
See @yan12125 s comment below for fix.

Original:
> ## Please follow the guide below
> 
> - You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
> - Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
> - Use the *Preview* tab to see what your issue will actually look like
> 
> ---
> 
> ### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
> - [ x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.07**
> 
> ### Before submitting an *issue* make sure you have:
> - [ x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
> - [ x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
> 
> ### What is the purpose of your *issue*?
> - [ x ] Bug report (encountered problems with youtube-dl)
> - [ ] Site support request (request for adding support for a new site)
> - [ ] Feature request (request for a new functionality)
> - [ ] Question
> - [ ] Other
> 
> ---
> 
> Youtube seemed to change how they deliver the hls files for livestreams, if the livestreams allows you to jump back several hours. Instead of providing an hls stream url, youtube-dl (2018.01.07) only provides the latest segment of the stream.
> 
> For example:
> This livestream works flawless like before: 
> NASA Livestream
> https://www.youtube.com/watch?v=RtU_mdL2vBM
> 
> this one (with the ability to go back) doesn't: 
> Live Train 24
> https://www.youtube.com/watch?v=qghQ5eKGcyE
> 
> Streamlink also suffered from this issue, so i think it's a change on youtubes side: 
> https://github.com/streamlink/streamlink/issues/1421

**Comment by baco** [comment]
Same here. Also have the issue with this streams:

https://youtube.com/channel/UCba3hpU7EFBSk817y9qZkiA/live
https://youtube.com/channel/UCR9120YBAqMfntqgRTKmkjQ/live
https://youtube.com/channel/UCC05qIa00qEB06CtCi01NbQ/live
https://youtube.com/channel/UCFgk2Q2mVO1BklRQhSv6p0w/live
https://youtube.com/channel/UCncnuCzrFwWxO4Z-c1vQB2A/live
https://youtube.com/channel/UCv0zRACOVWmhu1Ilufm40-w/live

but not with this one: https://youtu.be/9h6Vz6ylIdE which surprisingly allows me to seek back in time but I can obtain the `.M3U8` file when using the `-g` flag.

**Comment by hefronmedia** [comment]
This stream (https://youtu.be/9h6Vz6ylIdE) and the NASA stream were already active before this change was made.

If you 'youtube-dl -F' any new live streams, you'll see there's no HLS versions anymore. (Well, at least I'm not seeing any).

Now it's probably just a matter for streamlink and youtube-dl to support dynamic MPD manifests (youtube-dl already supports static) since it's looking like all streams are now DASH only

**Comment by hmedia1** [comment]
This stream (https://youtu.be/9h6Vz6ylIdE) and the NASA stream were already active before this change was made.

If you `youtube-dl -F` any new live streams, you'll see there's no HLS versions anymore. (Well, at least I'm not seeing any).

Now it's probably just a matter for streamlink and youtube-dl to support dynamic MPD manifests (youtube-dl already supports static) since it's looking like all streams are now DASH only.  (Given that the HLS streams were

**Comment by hmedia1** [comment]
I could be wrong, but this may be the day where YouTube farewells it's `anything in = 30fps out` HLS streams.  

This stream (https://youtu.be/9h6Vz6ylIdE) and the NASA one mentioned above have been active since before this change by YouTube.

If you `youtube-dl -F` any new streams, you'll see (at least this is what I'm seeing anyway) that they don't have hls streams anymore.

Further - it appears that on the browser, when clicking the nerd stats, there is no longer the line that indicates if it's a DASH stream or not, seemingly confirming that it's just all DASH now.  It's not overly surprising given that HLS streams were 30fps irrespective of what went in - *every* stream had to be converted for archive and this had long been just a compatibility feature.

Perhaps what is needed is to change this to a feature request; simply for youtube-dl to support dynamic MPD manifests (it already fully supports static ones)

I know from manual debugging, and lots of `grep` and `jq` that the MPD playlist is available from the earliest segment available on the stream (about 4 hours worth if the stream is 24/7 from memory), so it could be cleanly implemented.  

As a sidenote - same deal for `streamlink` - this never supported DASH at all.

**Comment by Bangaio65** [comment]
Yeah I started seeing this error yesterday. I have a script that grabs the link through youtube-dl and feeds it to ffmpeg (using the  -live_start_index option to be able to start at the designated time, not sure if this is possible to do with just youtube-dl) and using `-f best` give me `ERROR: requested format not available`. Using `-f 137` I get an error in ffmpeg: `Found duplicated MOOV Atom. Skipped it`. Using youtube-dl alone, it only downloads a couple seconds before stopping... but I need the rewind feature anyway.

**Comment by hmedia1** [comment]
`-live_start_index` is only going to work for a hls playlist.

One way to deal with the `MOOV Atom` thing for hacking and integration testing, is use `ffmpeg` with `-f concat`.  I know there's other ways, but short of something that accounts for every potential timestamp issue across all different files, I've found `concat` to be dead simple;

`youtube-dl` can get the manifest with `--youtube-include-dash-manifest`
From there, you could download your initialization segment to a file (say: "`base`"), and then parse the individual segments into manageable files, say;
```
cat list-of-segment-urls | while read url
do 
   curl -s "$url" > ${i}_tmp.ts ; (( i++ ))
done
```
`ffmpeg`/`ffplay` can then either transcode or just copy out / stitch the files together;
```
for file in $(echo base *_tmp.ts | sort -g)
do 
    echo "file '"$file"'" >> list.txt 
done
```
**list.txt** will look like this;
```
file 'base'
file '0_tmp.ts'
file '1_tmp.ts'
file '2_tmp.ts'
file '3_tmp.ts'
etc...
```
Then you can play it;
```
ffmpeg -f concat -i list.txt -c copy -f mpegts -bsf:v h264_mp4toannexb -y my_live_stream.ts
```
Now instead of `-live_start_index` the beginning will simply be the top line of the **list-of-segment-urls** file.

**Comment by FDMX2** [comment]
I'm only inetersted in the link pointing at the dash manifest, but the `--youtube-include-dash-manifest` argument (together with `-J`) did not include the dash manifest url.

If nobody else is on it i can find out how to retrieve this url.

**Comment by hmedia1** [comment]
The dash manifest URL is in the player config JSON.

Sidenote have you tried `--print-traffic`

**Comment by vkot** [comment]
Apparently Youtube still has HLS for live streams:
For Euronews Live:

youtube-dl -j https://www.youtube.com/watch?v=xAE4xX8Izvo
Only produces MPD formats

youtube-dl --print-traffic https://www.youtube.com/watch?v=xAE4xX8Izvo
Has no HLS entries

BUT
curl -sL -k "https://www.youtube.com/watch?v=xAE4xX8Izvo"
has a very valid HLS link:

"hlsvp":"https:\/\/manifest.googlevideo.com\/api\/manifest\/hls_variant\/gcr\....m3u8

**Comment by hmedia1** [comment]
The HLS playlist was previously accessible in more extraction points and query strings which were favored by `youtube-dl` as it really seems to only return the list of dash segments on live streams as a last ditch effort.

In my opinion all live feeds should be returned; it's actually nice to see 50p or 60p videos stream at their ingested frame rate.

**Comment by yan12125** [comment]
A quick and dirty patch for HLS:
```Diff
diff --git a/youtube_dl/extractor/youtube.py b/youtube_dl/extractor/youtube.py
index 0919bef0e..9ad662777 100644
--- a/youtube_dl/extractor/youtube.py
+++ b/youtube_dl/extractor/youtube.py
@@ -1537,7 +1537,7 @@ class YoutubeIE(YoutubeBaseInfoExtractor):
             ytplayer_config = self._get_ytplayer_config(video_id, video_webpage)
             if ytplayer_config:
                 args = ytplayer_config['args']
-                if args.get('url_encoded_fmt_stream_map'):
+                if args.get('url_encoded_fmt_stream_map') or args.get('hlsvp'):
                     # Convert to the same format returned by compat_parse_qs
                     video_info = dict((k, [v]) for k, v in args.items())
                     add_dash_mpd(video_info)
@@ -1802,15 +1802,16 @@ class YoutubeIE(YoutubeBaseInfoExtractor):
 
         chapters = self._extract_chapters(description_original, video_duration)
 
+        formats = []
         if 'conn' in video_info and video_info['conn'][0].startswith('rtmp'):
             self.report_rtmp_download()
-            formats = [{
+            formats.append({
                 'format_id': '_rtmp',
                 'protocol': 'rtmp',
                 'url': video_info['conn'][0],
                 'player_url': player_url,
-            }]
-        elif len(video_info.get('url_encoded_fmt_stream_map', [''])[0]) >= 1 or len(video_info.get('adaptive_fmts', [''])[0]) >= 1:
+            })
+        if len(video_info.get('url_encoded_fmt_stream_map', [''])[0]) >= 1 or len(video_info.get('adaptive_fmts', [''])[0]) >= 1:
             encoded_url_map = video_info.get('url_encoded_fmt_stream_map', [''])[0] + ',' + video_info.get('adaptive_fmts', [''])[0]
             if 'rtmpe%3Dyes' in encoded_url_map:
                 raise ExtractorError('rtmpe downloads are not supported, see https://github.com/rg3/youtube-dl/issues/343 for more information.', expected=True)
@@ -1827,7 +1828,6 @@ class YoutubeIE(YoutubeBaseInfoExtractor):
                                 'width': int_or_none(width_height[0]),
                                 'height': int_or_none(width_height[1]),
                             }
-            formats = []
             for url_data_str in encoded_url_map.split(','):
                 url_data = compat_parse_qs(url_data_str)
                 if 'itag' not in url_data or 'url' not in url_data:
@@ -1934,9 +1934,8 @@ class YoutubeIE(YoutubeBaseInfoExtractor):
                             if codecs:
                                 dct.update(parse_codecs(codecs))
                 formats.append(dct)
-        elif video_info.get('hlsvp'):
+        if video_info.get('hlsvp'):
             manifest_url = video_info['hlsvp'][0]
-            formats = []
             m3u8_formats = self._extract_m3u8_formats(
                 manifest_url, video_id, 'mp4', fatal=False)
             for a_format in m3u8_formats:
@@ -1952,7 +1951,7 @@ class YoutubeIE(YoutubeBaseInfoExtractor):
                 # Accept-Encoding header causes failures in live streams on Youtube and Youtube Gaming
                 a_format.setdefault('http_headers', {})['Youtubedl-no-compression'] = 'True'
                 formats.append(a_format)
-        else:
+        if not formats:
             unavailable_message = self._html_search_regex(
                 r'(?s)<h1[^>]+id="unavailable-message"[^>]*>(.+?)</h1>',
                 video_webpage, 'unavailable message', default=None)
```

**Comment by hmedia1** [comment]
Thanks @yan12125.

In addition to changing the default stream map, it looks like YouTube no longer converts to 30p for HLS.

For the sake of completeness, can I suggest on top of your patch:
```diff
--- a/youtube_dl/extractor/youtube.py	2018-01-12 22:41:11.845928145 +0800
+++ b/youtube_dl/extractor/youtube.py	2018-01-12 22:39:32.695954749 +0800
@@ -401,6 +401,8 @@
         '94': {'ext': 'mp4', 'height': 480, 'format_note': 'HLS', 'acodec': 'aac', 'abr': 128, 'vcodec': 'h264', 'preference': -10},
         '95': {'ext': 'mp4', 'height': 720, 'format_note': 'HLS', 'acodec': 'aac', 'abr': 256, 'vcodec': 'h264', 'preference': -10},
         '96': {'ext': 'mp4', 'height': 1080, 'format_note': 'HLS', 'acodec': 'aac', 'abr': 256, 'vcodec': 'h264', 'preference': -10},
+        '300': {'ext': 'mp4', 'height': 720, 'format_note': 'HLS', 'acodec': 'aac', 'abr': 256, 'vcodec': 'h264', 'preference': -10, 'fps': 60},
+        '301': {'ext': 'mp4', 'height': 1080, 'format_note': 'HLS', 'acodec': 'aac', 'abr': 256, 'vcodec': 'h264', 'preference': -10, 'fps': 60},
         '132': {'ext': 'mp4', 'height': 240, 'format_note': 'HLS', 'acodec': 'aac', 'abr': 48, 'vcodec': 'h264', 'preference': -10},
         '151': {'ext': 'mp4', 'height': 72, 'format_note': 'HLS', 'acodec': 'aac', 'abr': 24, 'vcodec': 'h264', 'preference': -10},
```

To uniformly represent the stream list in the `"hlsvp"` object:
<pre><code>
#EXT-X-STREAM-INF:BANDWIDTH=197400,CODECS="mp4a.40.5,avc1.4d400c",RESOLUTION=256x144,FRAME-RATE=30,CLOSED-CAPTIONS=NONE
#EXT-X-STREAM-INF:BANDWIDTH=338100,CODECS="mp4a.40.5,avc1.4d4015",RESOLUTION=426x240,FRAME-RATE=30,CLOSED-CAPTIONS=NONE
#EXT-X-STREAM-INF:BANDWIDTH=829500,CODECS="mp4a.40.2,avc1.4d401e",RESOLUTION=640x360,FRAME-RATE=30,CLOSED-CAPTIONS=NONE
#EXT-X-STREAM-INF:BANDWIDTH=1380750,CODECS="mp4a.40.2,avc1.4d401f",RESOLUTION=854x480,FRAME-RATE=30,CLOSED-CAPTIONS=NONE
#EXT-X-STREAM-INF:BANDWIDTH=3806250,CODECS="mp4a.40.2,avc1.4d4020",RESOLUTION=1280x720,FRAME-RATE=60,CLOSED-CAPTIONS=NONE
#EXT-X-STREAM-INF:BANDWIDTH=6231750,CODECS="mp4a.40.2,avc1.4d402a",RESOLUTION=1920x1080,FRAME-RATE=60,CLOSED-CAPTIONS=NONE
</code></pre>

Yielding a clear:

<pre><code>
format code  extension  resolution note
91           mp4        256x144    HLS  197k , avc1.42c00b, 30.0fps, mp4a.40.5@ 48k
92           mp4        426x240    HLS  338k , avc1.4d4015, 30.0fps, mp4a.40.5@ 48k
93           mp4        640x360    HLS  829k , avc1.4d401e, 30.0fps, mp4a.40.2@128k
94           mp4        854x480    HLS 1380k , avc1.4d401f, 30.0fps, mp4a.40.2@128k
300          mp4        1280x720   <strong>HLS</strong> 3806k , avc1.4d4020, <strong>60.0fps</strong>, mp4a.40.2@256k
301          mp4        1920x1080  <strong>HLS</strong> 6231k , avc1.64002a, <strong>60.0fps</strong>, mp4a.40.2@256k (best)
</code></pre>

**Comment by jaydenkieran** [comment]
Any idea on when the patch for this will be pushed to the repo? Thanks, btw

**Comment by m0hamedessam** [comment]
hls playlist freezing on vlc and ffmpeg any idea ?

**Comment by vkot** [comment]
Latest FFmpeg builds seem to work ok on those HLS streams; last stable release on Zeranoe indeed freezes

**Comment by m0hamedessam** [comment]
@vokot both freezing :(

**Comment by vkot** [comment]
@m0hamedessam I tried with Euronews live https://m.youtube.com/watch?v=xAE4xX8Izvo , new YouTube-dl and latest build https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20180112-1eb7c1d-win64-static.zip - seems to be ok

**Comment by m0hamedessam** [comment]
@vkot i use this command 
youtube-dl -v --hls-prefer-native --hls-use-mpegts --no-resize-buffer --buffer-size 2M -f93 --ignore-config -o - https://m.youtube.com/watch?v=xAE4xX8Izvo |ffplay -

and freeze can you send me yours

**Comment by vkot** [comment]
@m0hamedessam Just copy-pasted your command, runs smooth, no freeze.

Are you sure you have both ffmpeg and ffplay from the latest build? No other ffmpeg binaries in the PATH?

**Comment by m0hamedessam** [comment]
ffplay version N-89788-g1eb7c1d49d Copyright (c) 2003-2018 the FFmpeg developers
  built with gcc 7.2.0 (GCC)

same problem here

https://github.com/rg3/youtube-dl/issues/15247

**Comment by vkot** [comment]
Strange. Let’s see what other people will report on that other ticket.

**Comment by morfeo9950** [comment]
> 
> 
> The live dash manifest URL is in the player config JSON.
> 
> ```
> youtube-dl --print-traffic https://youtu.be/<id> \
> | grep -oP "/api/manifest/dash/.*? " \
> | echo "https://manifest.googlevideo.com/$(cat -)"
> 
> https://manifest.googlevideo.com//api/manifest/dash/etc....
> ```
> 
> Or extract it yourself:
> 
> ```
> curl -sL "https://youtu.be/<id>" \
> | grep -oP "ytplayer.config =\K.*?}(?=;)" \
> | jq -r .args.dashmpd
> 
> https://manifest.googlevideo.com/api/manifest/dash/etc....
> ```

Where is the player config JSON?
