### ISSUE TITLE
Russian subtitles

### ISSUE THREAD

**Issue by Liontooth** [rg3/youtube-dl#15217]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

In the file https://www.youtube.com/watch?v=DA32aOdVlK4 there are Russian subtitles, white text on black background, which can be turned on and off with the CC button. 

However, youtube-dl --list-subs and youtube-dl --all-subs both report

"WARNING: video doesn't have subtitles."

The subtitles are in fact accessible via "&type=track&lang=ru&name&kind=asr&fmt=1". They appear to be machine generated.

Cheers,
David

**Comment by dstftw** [comment]
There are no subtitles for this video but only automatic captions that are downloaded fine.
