### ISSUE TITLE
Cannot see dash manifest URL for youtube videos

### ISSUE THREAD

**Issue by haloweenj** [rg3/youtube-dl#15216]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.07**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

I was using youtube-dl to get youtube videos DASH manifest. For example, I executed
`/home/arqos/scripts/youtube-dl "https://www.youtube.com/watch?v=QcbWunQq3D4" --youtube-include-dash-manifest --dump-intermediate-pages -s -v`
and waited for the following output to get the DASH manifest URL:
`[youtube] QcbWunQq3D4: Downloading MPD manifest`
`[youtube] Dumping request to https://manifest.googlevideo.com/api/manifest/dash/ei/rjCkWcLCIdb4co_yn9gP/hfr/1/ipbits/0/ms/au/mn/sn-2vgu0b5auxaxjvh-apnl/itag/0/key/yt6/playback_host/r8---sn-2vgu0b5auxaxjvh-apnl.googlevideo.com/mm/31/pcm2cms/yes/mv/u/source/youtube/mt/1503932413/sparams/as%2Cei%2Chfr%2Cid%2Cip%2Cipbits%2Citag%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cplayback_host%2Crequiressl%2Csource%2Cexpire/requiressl/yes/expire/1503954190/id/41c6d6ba742adc3e/signature/6E9506043B4D6914AC7C557E266CFC4776FD7886.7739DB11383F3629E54C92C88531D91E8C39209E/pl/32/ip/2a02%3A818%3A803c%3A4200%3A203%3A7fff%3Afe40%3Ac9c/as/fmp4_audio_clear%2Cfmp4_sd_hd_clear` 

A few days ago this stopped working. I updated youtube-dl but cannot get this info for videos I could before (as the one in the example). Is there any other way with the current version to get the video DASH manifest to use with VLC?

Thank you in advance for your help.

**Comment by dstftw** [comment]
DASH manifest is no longer served.
