### ISSUE TITLE
[Youtube] 360 videos url with separated video/audio can not display normal 360 view.

### ISSUE THREAD

**Issue by ZuoSyuan** [rg3/youtube-dl#15224]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.07**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
PS C:\workspace> .\youtube-dl.exe -v  "https://www.youtube.com/watch?v=H6SsB3JYqQg" -f 'bestvideo+bestaudio/best'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=H6SsB3JYqQg', '-f', 'bestvideo+bestaudio/best', '--no-check-certificate']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] H6SsB3JYqQg: Downloading webpage
[youtube] H6SsB3JYqQg: Downloading video info webpage
[youtube] H6SsB3JYqQg: Extracting video information
WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
[debug] Invoking downloader on 'https://r7---sn-ipoxu-un56.googlevideo.com/videoplayback?expire=1515661840&gir=yes&requiressl=yes&keepalive=yes&pl=23&ei=sNVWWsPtEsivgQOwhLqACw&ip=118.163.84.235&initcwndbps=785000&xtags=tx%3D23704842%3Avproj%3Dmesh&id=o-AJZoNb6VS0PMjf-n7wXb3YQTFMpLkv5p_RspvHxQIsPb&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cxtags%2Cexpire&source=youtube&mm=31&mn=sn-ipoxu-un56&clen=783573347&ms=au&mt=1515640127&mv=m&dur=492.058&ipbits=0&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C264%2C266%2C271%2C278%2C313&mime=video%2Fmp4&itag=266&key=yt6&lmt=1507314145930387&signature=8C764C1085081B3754A468FA63BF6FCBF96C2605.34DAE19AC0DDE85F19C785C0ECDDA23868CDC796&ratebypass=yes'
[download] Destination: Experience the Blue Angels in 360-degree video-H6SsB3JYqQg.f266.mp4
[download] 100% of 747.27MiB in 01:09
[debug] Invoking downloader on 'https://r7---sn-ipoxu-un56.googlevideo.com/videoplayback?expire=1515661840&gir=yes&requiressl=yes&keepalive=yes&pl=23&ei=sNVWWsPtEsivgQOwhLqACw&ip=118.163.84.235&initcwndbps=785000&id=o-AJZoNb6VS0PMjf-n7wXb3YQTFMpLkv5p_RspvHxQIsPb&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&source=youtube&mm=31&mn=sn-ipoxu-un56&clen=7818493&ms=au&mt=1515640127&mv=m&dur=492.216&ipbits=0&mime=audio%2Fmp4&itag=140&key=yt6&lmt=1507272343187911&signature=7D2393B2EC3829C15DD61AB81832661BC488A49C.DA5792840B99BEE563AE7D4C673B0ED999B99E08&ratebypass=yes'
[download] Destination: Experience the Blue Angels in 360-degree video-H6SsB3JYqQg.f140.m4a
[download] 100% of 7.46MiB in 00:00
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

This Youtube video is a 360 content.
I try to play the downloaded video with Chrome browser and it can not display a correct 360 view.
Then I direct open the http url with Chrome, it does not display correctly either.

I guess Youtube has changed the format returned by the url template youtube-dl use.
Are there another url template youtube-dl can get to replace the current using?

**Comment by dstftw** [comment]
There is no such thing as url template. All download URLs are provided by Youtube and use by youtube-dl intact.
