### ISSUE TITLE
Download file from google drive

### ISSUE THREAD

**Issue by jhdscript** [rg3/youtube-dl#15235]
Hello,

I m trying to use youtube-dl to download a file from google drive.

Link is :  https://drive.google.com/uc?export=download&id=0B5hBTUDdATCCZ2ZJSHhtYVRWMVE

But i receive the error:

[GoogleDrive] 0B5hBTUDdATCCZ2ZJSHhtYVRWMVE: Downloading webpage
[GoogleDrive] 0B5hBTUDdATCCZ2ZJSHhtYVRWMVE: Requesting source file
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'f7aceb1
8b0453d1e3698c8be920ad6c841f53000554427c80d9bc946d5608ea45f4db2d13dc39bf151afed9
6f4db4ecf0caf1298d8158e0ee8db9a827ad818ed453361671c52f2f90a5c32220b4ef1dc3de8efc
762-0B5hBTUDdATCCZ2ZJSHhtYVRWMVE.f7aceb18b0453d1e3698c8be920ad6c841f53000554427c
80d9bc946d5608ea45f4db2d13dc39bf151afed96f4db4ecf0caf1298d8158e0ee8db9a827ad818e
d453361671c52f2f90a5c32220b4ef1dc3de8efc762.part'

I m using windows executable. If someone have a tips or a solution I appreciate.

Regards

**Comment by dstftw** [comment]
Use output template to set shorter file name.
