### ISSUE TITLE
old version on pypi (2017.12.31)

### ISSUE THREAD

**Issue by cliffordwhansen** [rg3/youtube-dl#15230]
~~- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.07**~~

This is my problem I can not download the latest version from pypi.

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [X] Other

---

### Description of your *issue*, suggested solution and other information

When doing a `pip install --upgrade youtube-dl` I don't get an updated version. and when going to https://pypi.python.org/pypi/youtube_dl the latest version is 2017.12.31

```
➜  ~ youtube-dl --version            
2017.12.31
➜  ~ sudo pip install --upgrade youtube-dl
Requirement already up-to-date: youtube-dl in /usr/lib/python3.6/site-packages
```

**Comment by yan12125** [comment]
Thanks for the report. This is already reported in #5948.
