### ISSUE TITLE
 Unable to log in Udemy

### ISSUE THREAD

**Issue by HamedRahmani** [rg3/youtube-dl#15239]
Hi
I have an error when a want to login in udemy cources!
I use youtube version 2017.12.31.

`[ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.]`

Is there any solution?

**Comment by HamedRahmani** [comment]
You tag my question as dublicated but a I cant find answer!

**Comment by dstftw** [comment]
There is no answer.
