### ISSUE TITLE
[Issue] youtube-dl Doesn't download playlist.

### ISSUE THREAD

**Issue by Ian-A-Jones** [rg3/youtube-dl#15243]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### Description of your *issue*, suggested solution and other information

I am trying to use youtube-dl to download playlists from youtube. It downloads the first song in the playlist but then stops. the verbose log doesn't seem to give an error : 

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--force-ipv4', '-x', '--audio-format', 'mp3', '--yes-playlist', '-i', '--verbose', '--newline', '-o', 'C:\\*PATHTOPROGRAM*/%(id)s.%(ext)s', 'https://www.youtube.com/watch?v=kXYiU_JCYtU&list=PL87FA01F68C540290']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.01.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-89773-g7fcbebbeaf, ffprobe N-89773-g7fcbebbeaf
[debug] Proxy map: {}
```

I am using C# Dot.NetCore and the code I'm using is :
```
private Process DownloadPlaylist(string url)
{ 
        Process downloadPlaylist = new Process
        {
                StartInfo = new ProcessStartInfo
                {
                        FileName = "youtube-dl.exe",
                        Arguments = $"--force-ipv4 -x --audio-format mp3 --yes-playlist -i --verbose --newline -o \"{Video.audioCache}%(id)s.%(ext)s\" \"{url}\"",
                        UseShellExecute = false,
                        RedirectStandardOutput = true,
                        CreateNoWindow = false,
                }
        };

        downloadPlaylist.Start();
        downloadPlaylist.WaitForExit();
        return downloadPlaylist;
}
```

If I'm being dumb please let me know, I've been looking around for an issue similar to this and I've found results that talk about escaping urls properly and I believe I am with `\"{url}\""`

Note - Just to clarify *PATHTOPROGRAM* is not what I actually send, just not comfortable wanting to post my directory.

Thanks in advance

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
