### ISSUE TITLE
Minds & Bitchute support, two new social media platforms

### ISSUE THREAD

**Issue by Jakecheslekov** [rg3/youtube-dl#15244]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.07**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.01.07
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
https://www.bitchute.com/video/QaNRKm9GnH4/
https://www.minds.com/newsfeed/798025111988506624
I can't make a VK account because I don't have a phone number, or else I'd get you the URL...
I picked these kind of at random, none of these are copyright infringement - I checked!

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I think its important that we all do our part to support alternative platforms so that we don't give YouTube, Facebook & Twitter a monopoly on the internet. If I can be of any more help please let me know how!! I don't think I missed anything... I hope I didn't miss anything! I've triple-checked it all and it seems OK.. I think.
I unfortunately cannot even get into vk.com to get a video link, I will try to do that at a later time, and gab.ai also doesn't support videos as of yet either & mastodon has an 8MB limit on videos, nice to see you guys already support Vimeo!!

**Comment by Jakecheslekov** [comment]
I just noticed there were already two issues opened up about bitchute & Minds, my bad! Sorry!!
Any idea when you guys will be able to support these two platforms? Really curious!!
MINDS is still "beta", I think they may change from their current video format to another one similar to YouTube with the resolution-changing options, should I make an issue here when they improve their format so you guys know about it?

**Comment by bitingsock** [comment]
Since the other issue is locked I'll post here. I believe I have a working solution for bitchute. While @Tatsh is correct that the http uri listed in the page can expire, we can simply parse through the magnet uri for one that is valid. My hacky autoit script is:
`$occur=0
    $source=_INetGetSource($CMDLineRaw)
    $url=""
    $urlend=""
    $urlstart=""
    while InetGetSize($url)==0 And $occur<6
        $occur+=1
        $urlend=StringInStr($source, ".mp4",0,$occur)
        $urlstart=StringInStr($source, "https://seed", 0, -1, $urlend, 50)
        $url=StringMid($source,$urlstart,$urlend-$urlstart+4)
        ;MsgBox(0,"",$url)
    WEnd`
