### ISSUE TITLE
Be sure to call youtube-dl with the --verbose flag and include its complete output.

### ISSUE THREAD

**Issue by bala93kumar** [rg3/youtube-dl#15250]
upon running the below command in windows power shell 

PS E:\HDPCDSpark using Python> youtube-dl -u xxxxxxxxxxxx -p xxxxxxxx https://www.udemy.com/hdpcd-spark-using-python-pys
park/learn/v4/content

i face the below error 

[udemy:course] Downloading login popup
[udemy:course] Logging in
[udemy:course] hdpcd-spark-using-python-pyspark: Downloading webpage
ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see
  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
PS E:\Udemy\HDPCDSpark using Python> PB

Note :but i also ensured that i am running the latest version but still failing , could some one help

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
