### ISSUE TITLE
How do you simply get a list of recent videos from a channel?

### ISSUE THREAD

**Issue by GHExplorer** [rg3/youtube-dl#15254]
Hi,

This is one of those things, I just can't figure out how to do.  I don't even know if it's possible.

Given a channel (not a playlist), I'd like to get a list of the most recent videos from that channel.  E.g., everything from today, or the last 2 days.

I've tried different commands, but probably my url format is incorrect.  Youtube-dl returns an open error on all of the channels I've tried, with CERTIFICATE_VERIFY_FAILED.

One of the problems is that youtube-dl, as with many other tools, seems based on a specific playlist.  But what is there a way to get the list of descriptions & urls from the url of the channel, rather than a playlist?

The ultimate goal is to be able to download videos at the office in the morning (without showing them in a browser), convert them to mp3, and listen while I'm working.  I don't want anyone passing by, thinking I'm spending hours on Youtube, when I really just want some things to listen to, while getting work done.

Thanks, if you have any suggestions.  Sorry if I'm missing something fundamental about the tool.

**Comment by dstftw** [comment]
```
--date DATE                      Download only videos uploaded in this date
--datebefore DATE                Download only videos uploaded on or before
                                 this date (i.e. inclusive)
--dateafter DATE                 Download only videos uploaded on or after
                                 this date (i.e. inclusive)
```

**Comment by GHExplorer** [comment]
Yes, I've already tried these exact commands, and they all return errors.  So, using the ClojureTV site as an example, there were some videos there on 10/14/2017.


youtube-dl.exe --date 20171014 https://www.youtube.com/user/ClojureTV/videos
[youtube:user] ClojureTV: Downloading channel page
WARNING: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
, and then proceeds with an error, similar to the warning.


Same with the url from the channel itself, as opposed to the 'videos' folder above:

youtube-dl.exe --date 20171014 https://www.youtube.com/channel/UCaLlzGqiPE2QRj6sSOawJRg
[youtube:channel] UCaLlzGqiPE2QRj6sSOawJRg: Downloading channel page
WARNING: Unable to download webpage: <urlopen error....

[youtube:channel] UCaLlzGqiPE2QRj6sSOawJRg: Downloading page #1
ERROR: etc.

**Comment by dstftw** [comment]
Bother to search tracker for this error.
