### ISSUE TITLE
Get no of videos in the playlist

### ISSUE THREAD

**Issue by ismail783** [rg3/youtube-dl#15269]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

My Current

youtube-dl.conf
----------------
```
-u UserName
-p Password
--download-archive archive.txt
-i
-c
--no-warnings
--console-title
--batch-file='batch-file.txt'
-o 'MySafVideos/%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s'
-f 'bestvideo[height<=720]+bestaudio/best[height<=720]/worst'
```

CMD
-----
youtube-dl.exe --playlist-start 52 --playlist-items 52-58 Playlist_URL

Problem
---------
Normally I know what is the number of videos in the playlist (Ex. Collected 71 video ids (downloading 30 of them))

Instead of,
`--playlist-items 52-58`
I want to pass 
`--playlist-items 52-last`
So that it gets rest of the videos in the playlist. Otherwise I have to check the  Collected video ids to know about the remaining videos in the playlist.

**Comment by dstftw** [comment]
Use `--playlist-start 52`.
