### ISSUE TITLE
--hls-use-mpegts not honored at RoosterTeeth

### ISSUE THREAD

**Issue by zing269** [rg3/youtube-dl#15277]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.14**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '[height=480]', '--hls-use-mpegts', 'http://www.roosterteeth.com/episode/rwby-volume-5-12lkopoklk1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.14
[debug] Python version 3.4.4 (CPython) - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg n3.1.2, ffprobe n3.1.2
[debug] Proxy map: {}
[RoosterTeeth] rwby-volume-5-12lkopoklk1: Downloading webpage
[RoosterTeeth] rwby-volume-5-12lkopoklk1: Downloading m3u8 information
[debug] Invoking downloader on 'https://rtv3-video.roosterteeth.com/store/70efa812f66d64654d6ddc925f06ae4e-34e4f096/ts/34e4f096-hls_480p-store-70efa812f66d64654d6ddc925f06ae4e.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 221
[download] Destination: RWBY - Volume 5, Chapter 12 - Vault of the Spring Maiden-34970.mp4
[download] 100% of 156.73MiB in 06:56
[debug] ffmpeg command line: ffprobe -show_streams "file:RWBY - Volume 5, Chapter 12 - Vault of the Spring Maiden-34970.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "RWBY - Volume 5, Chapter 12 - Vault of the Spring Maiden-34970.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:RWBY - Volume 5, Chapter 12 - Vault of the Spring Maiden-34970.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:RWBY - Volume 5, Chapter 12 - Vault of the Spring Maiden-34970.temp.mp4"
```

Downloading RWBY episodes from RoosterTeeth using the --hls-use-mpegts option results in a .mp4 file. Both mediainfo and ffprobe show that the file is MPEG-4 / isom not MPEG-TS

**Comment by s104346** [comment]
You additionally need to specify ` --hls-prefer-ffmpeg` to tell youtube-dl to use ffmpeg/avconv instead of the native HLS downloader if you want to use `--hls-use-mpegts`.

**Comment by yan12125** [comment]
Thanks @s104346. That's right.

**Comment by zing269** [comment]
Adding the --hls-prefer-ffmpeg still results in a MPEG-4 / isom file, however it is one byte larger.
