### ISSUE TITLE
[Youtube] Can not download 2160x3840 or 1080x1920 video for  mp4 format

### ISSUE THREAD

**Issue by sushipan** [rg3/youtube-dl#15270]
From two week ago the youtube-dl can not download  2160x3840 or 1080x1920  mp4 format,but webm format is available , who can help me ?

This is the log 

[root@host ~]# youtube-dl --update
Updating to version 2018.01.14 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
[root@host ~]# youtube-dl -F https://www.youtube.com/watch?v=45TbbVa-12Y
[youtube] 45TbbVa-12Y: Downloading webpage
[youtube] 45TbbVa-12Y: Downloading video info webpage
[youtube] 45TbbVa-12Y: Extracting video information
[info] Available formats for 45TbbVa-12Y:
format code  extension  resolution note
249          webm       audio only DASH audio   60k , opus @ 50k, 1.22MiB
250          webm       audio only DASH audio   80k , opus @ 70k, 1.61MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 3.11MiB
171          webm       audio only DASH audio  139k , vorbis@128k, 3.06MiB
251          webm       audio only DASH audio  159k , opus @160k, 3.16MiB
160          mp4        82x144     144p   38k , avc1.4d500b, 24fps, video only, 910.35KiB
278          webm       82x144     144p   43k , webm container, vp9, 24fps, video only, 909.39KiB
133          mp4        136x240    144p   81k , avc1.4d400c, 24fps, video only, 1.94MiB
242          webm       136x240    144p   91k , vp9, 24fps, video only, 1.90MiB
243          webm       202x360    240p  162k , vp9, 24fps, video only, 3.41MiB
134          mp4        202x360    240p  204k , avc1.4d400d, 24fps, video only, 4.89MiB
244          webm       270x480    240p  293k , vp9, 24fps, video only, 6.18MiB
135          mp4        270x480    240p  376k , avc1.4d4015, 24fps, video only, 8.97MiB
247          webm       406x720    360p  531k , vp9, 24fps, video only, 11.89MiB
136          mp4        406x720    360p  749k , avc1.4d401e, 24fps, video only, 17.89MiB
248          webm       608x1080   480p  925k , vp9, 24fps, video only, 20.88MiB
137          mp4        608x1080   480p 1408k , avc1.64001f, 24fps, video only, 33.37MiB
271          webm       810x1440   720p 2875k , vp9, 24fps, video only, 67.61MiB
264          mp4        810x1440   720p 3364k , avc1.640020, 24fps, video only, 79.16MiB
313          webm       1216x2160  1080p 5602k , vp9, 24fps, video only, 133.66MiB
272          webm       2160x3840  2160p 8246k , vp9, 24fps, video only, 141.98MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        136x240    small , mp4v.20.3, mp4a.40.2
18           mp4        202x360    small , avc1.42001E, mp4a.40.2@ 96k
43           webm       640x360    medium , vp8.0, vorbis@128k
22           mp4        406x720    medium , avc1.64001F, mp4a.40.2@192k (best)

**Comment by Hrxn** [comment]
It's entirely possible (for newer videos, for example) that YouTube does not provide all resolutions in all formats. Not that surprising that they prefer they own formats (VP9, WEBM).

**Comment by dstftw** [comment]
mp4 higher than 720p does not exist for this video.

**Comment by sushipan** [comment]
Thank you @Hrxn  @dstftw 

I've tried many video urls . Found that,  if the video is vertical, youtube-dl  can not get 1080x1920 or higher of mp4 ,but if the video is horizontal,youtube-dl can get 1080x1920 or higher of mp4   

This is the horizontal video,and uploaded these days:

[root@host ~]# youtube-dl -F https://www.youtube.com/watch?v=NDOB3hgKPJ8
[youtube] NDOB3hgKPJ8: Downloading webpage
[youtube] NDOB3hgKPJ8: Downloading video info webpage
[youtube] NDOB3hgKPJ8: Extracting video information
[info] Available formats for NDOB3hgKPJ8:
format code  extension  resolution note
249          webm       audio only DASH audio   43k , opus @ 50k, 1.12MiB
250          webm       audio only DASH audio   54k , opus @ 70k, 1.40MiB
171          webm       audio only DASH audio   89k , vorbis@128k, 2.25MiB
251          webm       audio only DASH audio   97k , opus @160k, 2.55MiB
140          m4a        audio only DASH audio  127k , m4a_dash container, mp4a.40.2@128k, 3.40MiB
278          webm       256x144    144p  105k , webm container, vp9, 30fps, video only, 2.59MiB
160          mp4        256x144    144p  112k , avc1.4d400c, 30fps, video only, 2.98MiB
242          webm       426x240    240p  230k , vp9, 30fps, video only, 5.95MiB
133          mp4        426x240    240p  248k , avc1.4d4015, 30fps, video only, 6.55MiB
243          webm       640x360    360p  449k , vp9, 30fps, video only, 10.98MiB
134          mp4        640x360    360p  640k , avc1.4d401e, 30fps, video only, 16.79MiB
244          webm       854x480    480p  764k , vp9, 30fps, video only, 20.14MiB
135          mp4        854x480    480p 1193k , avc1.4d401f, 30fps, video only, 31.02MiB
247          webm       1280x720   720p 1545k , vp9, 30fps, video only, 40.16MiB
136          mp4        1280x720   720p 2371k , avc1.4d401f, 30fps, video only, 60.68MiB
248          webm       1920x1080  1080p 2699k , vp9, 30fps, video only, 70.51MiB
137          mp4        1920x1080  1080p 4439k , avc1.640028, 30fps, video only, 108.91MiB
271          webm       2560x1440  1440p 8945k , vp9, 30fps, video only, 233.24MiB
264          mp4        2560x1440  1440p 10719k , avc1.640032, 30fps, video only, 217.31MiB
313          webm       3840x2160  2160p 17926k , vp9, 30fps, video only, 467.46MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)

This is the vertical video logs:
[root@host ~]# youtube-dl -F https://www.youtube.com/watch?v=A8dXmeiCVOU
[youtube] A8dXmeiCVOU: Downloading webpage
[youtube] A8dXmeiCVOU: Downloading video info webpage
[youtube] A8dXmeiCVOU: Extracting video information
[info] Available formats for A8dXmeiCVOU:
format code  extension  resolution note
249          webm       audio only DASH audio   56k , opus @ 50k, 1.06MiB
250          webm       audio only DASH audio   71k , opus @ 70k, 1.37MiB
171          webm       audio only DASH audio  119k , vorbis@128k, 2.59MiB
140          m4a        audio only DASH audio  127k , m4a_dash container, mp4a.40.2@128k, 2.93MiB
251          webm       audio only DASH audio  134k , opus @160k, 2.86MiB
160          mp4        82x144     144p   38k , avc1.4d400b, 30fps, video only, 879.77KiB
278          webm       82x144     144p   42k , webm container, vp9, 30fps, video only, 819.54KiB
133          mp4        136x240    144p   81k , avc1.4d400c, 30fps, video only, 1.86MiB
242          webm       136x240    144p   87k , vp9, 30fps, video only, 1.74MiB
243          webm       202x360    240p  151k , vp9, 30fps, video only, 3.13MiB
134          mp4        202x360    240p  204k , avc1.4d400d, 30fps, video only, 4.66MiB
244          webm       270x480    240p  269k , vp9, 30fps, video only, 5.66MiB
135          mp4        270x480    240p  374k , avc1.4d4015, 30fps, video only, 8.52MiB
247          webm       406x720    360p  504k , vp9, 30fps, video only, 11.07MiB
136          mp4        406x720    360p  749k , avc1.4d401e, 30fps, video only, 17.03MiB
302          webm       406x720    360p60  852k , vp9, 60fps, video only, 19.41MiB
248          webm       608x1080   480p  867k , vp9, 30fps, video only, 19.44MiB
298          mp4        406x720    360p60 1108k , avc1.4d401f, 60fps, video only, 25.49MiB
137          mp4        608x1080   480p 1394k , avc1.64001f, 30fps, video only, 31.73MiB
303          webm       608x1080   480p60 1441k , vp9, 60fps, video only, 32.34MiB
299          mp4        608x1080   480p60 1843k , avc1.640020, 60fps, video only, 42.27MiB
271          webm       810x1440   720p 2791k , vp9, 30fps, video only, 63.67MiB
264          mp4        810x1440   720p 3355k , avc1.640020, 30fps, video only, 74.76MiB
308          webm       810x1440   720p60 4238k , vp9, 60fps, video only, 96.38MiB
313          webm       1216x2160  1080p 5578k , vp9, 30fps, video only, 127.37MiB
272          webm       2160x3840  2160p60 6580k , vp9, 60fps, video only, 141.37MiB
315          webm       1216x2160  1080p60 8549k , vp9, 60fps, video only, 193.06MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        136x240    small , mp4v.20.3, mp4a.40.2
18           mp4        202x360    small , avc1.42001E, mp4a.40.2@ 96k
43           webm       640x360    medium , vp8.0, vorbis@128k
22           mp4        406x720    medium , avc1.64001F, mp4a.40.2@192k (best)
