### ISSUE TITLE
wrong folder used for installation?

### ISSUE THREAD

**Issue by n8waechta** [rg3/youtube-dl#15289]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**wrong folder used for installation?**
(Sorry, I'm not a native speaker.)
Hi, I installed the newest version (2018.01.14) on my Ubuntu-Linux, according to the instruction "https://rg3.github.io/youtube-dl/download.html" .
I used "wget".
The installation-folder was "/usr/**local**/bin/youtube-dl", according to the instruction.
Then I tried to start youtube-dl in a terminal, and i got the following error-message:
"bash: /usr/bin/youtube-dl: Datei oder Verzeichnis nicht gefunden (file or folder not found)".

Then I moved the python-script named "youtube-dl"
from /usr/**local**/bin
to     /usr/bin

Then I retried to start youtube-dl in a terminal, and it works fine.

Now my question:
Is it normal, that i have to move the script manually?
Or did I made a mistake during installation?

Thanks in advance for a answer.

**Comment by dstftw** [comment]
Update name cache with `hash -d youtube-dl` or restart bash.
