### ISSUE TITLE
America's Test Kitchen Older videos fail with Unable to extract kaltura partner id

### ISSUE THREAD

**Issue by msroest** [rg3/youtube-dl#15286]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl --verbose https://www.americastestkitchen.com/episode/465-spicing-up-the-backyard-barbecue
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.americastestkitchen.com/episode/465-spicing-up-the-backyard-barbecue']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.14
[debug] Python version 2.7.14 (CPython) - Linux-4.14.8-ryzen-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: avconv 3.3.4-2, avprobe 3.3.4-2, ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[AmericasTestKitchen] 465: Downloading webpage
ERROR: Unable to extract kaltura partner id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/americastestkitchen.py", line 48, in _real_extract
    webpage, 'kaltura partner id')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 794, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract kaltura partner id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description of your *issue*, suggested solution and other information
Older videos on America's Test Kitchen site appear to not work starting with Season 15 I get this error seasons 16/17/18 all seem to work fine.
https://www.americastestkitchen.com/episodes/browse

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by msroest** [comment]
No account credentials required.  The page is publicly available I'm not authenticated @dstftw

**Comment by dstftw** [comment]
![image](https://user-images.githubusercontent.com/1908898/35050864-5fe6b32c-fbd6-11e7-9c5c-4aca86523ee8.png)

**Comment by msroest** [comment]
Weird I wonder if it's geo restricted or something.  I just tried again in a incognito and with completely cleared cookies and I'm able to access it with no such prompt.

From Canada

**Comment by StevenDTX** [comment]
None of their past seasons are publicly available. In fact, that is their entire business model.  I actually pay for a subscription and the download works just fine.  You have to use the --cookies option.

```
E:\>c:\support\youtube-dl.exe --cookies e:\cookies\cookies-ATK.txt --restrict-filenames --continue --no-check-certificate --ignore-errors --verbose "https://www.americastestkitchen.com/episode/465-spicing-up-the-backyard-barbecue"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'e:\\cookies\\cookies-ATK.txt', '--restrict-filenames', '--continue', '--no-check-certificate', '--ignore-errors', '--verbose', 'https://www.americastestkitchen.com/episode/465-spicing-up-the-backyard-barbecue']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-89395-g71421f382f, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[AmericasTestKitchen] 465: Downloading webpage
[Kaltura] 1_8np7wtnr: Downloading video info JSON
[Kaltura] 1_8np7wtnr: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1445801/sp/144580100/playManifest/entryId/1_8np7wtnr/format/url/protocol/http/flavorId/1_2cxvgzei'
[download] Destination: Spicing_Up_the_Backyard_Barbecue-1_8np7wtnr.mp4
[download]   0.1% of 4.00GiB at 921.45KiB/s ETA 01:15:50
ERROR: Interrupted by user
```

**Comment by msroest** [comment]
Ahh thanks sorry for the confusion
