### ISSUE TITLE
Bug/new feature *Verification*

### ISSUE THREAD

**Issue by raphael613** [rg3/youtube-dl#15282]
Hi
I am downloading from many sites,many playlists.
The main issue is that for some reason many times it cannot finish downloading all the playlist and i must send again the same command to run again the download process.
So I look for a parameter something i can add to the command in powershell to verify that all the playlist is downloaded and if not it must do it again until all the playlist is on my computer...
An idea?
Thanks for the help in advance

**Comment by dstftw** [comment]
Such feature won't be added since it's a right way to endless download loops
