### ISSUE TITLE
YouTube said: Invalid parameters. (instead of specific error message)

### ISSUE THREAD

**Issue by srett** [rg3/youtube-dl#15284]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

For a few days now, videos that have been removed, blocked, unavailable in current country etc. yield the generic error "Invalid parameters" instead of the actual message you'd see in a browser, like before.
My workflow depends on knowing why accessing a video failed. I used "youtube-dl --skip-download ..." for this.

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl -v NbhXmSBlS_U
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'NbhXmSBlS_U']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.14
[debug] Python version 2.7.14 (CPython) - Linux-4.15.0-rc7-devtest+-x86_64-with-debian-buster-sid
[debug] exe versions: avprobe present, ffmpeg N-81364-gf85842b-static, ffprobe N-81364-gf85842b-static
[debug] Proxy map: {}
[youtube] NbhXmSBlS_U: Downloading webpage
[youtube] NbhXmSBlS_U: Downloading video info webpage
ERROR: NbhXmSBlS_U: YouTube said: Invalid parameters.
Traceback (most recent call last):
  File "/home/zahl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/home/zahl/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/home/zahl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1609, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: NbhXmSBlS_U: YouTube said: Invalid parameters.

```

---

### Description of your *issue*, suggested solution and other information

This seems to happen since around Jan 4 according to logs.
Examples:
XR4YH1N04pc (This video contains content from UMG, who has blocked it in your country on copyright grounds.)
NbhXmSBlS_U (This video contains content from Formula One Management, who has blocked it on copyright grounds.)
7HpZjCe9LQY (This video is unavailable.)
xPFZl59_OZ4 (This video is no longer available because the YouTube account associated with this video has been terminated.)
n_7t_vO3vlU ("Gamma Ray - Beyo..." The YouTube account associated with this video has been terminated due to multiple third-party notifications of copyright infringement.)

The all just yield "Invalid parameters".

The website itself also behaves slightly different from before, I cannot get it to tell me that a video does not exist by passing random or invalid video ids, I only get the "unavailable" message, so that would at least explain why youtube-dl doesn't report non-existent videos anymore, but the rest should still be possible to detect.

**Comment by glenn-slayden** [comment]
I also reproduce this problem as starting sometime in early January (i.e., with all relevant scripts, code, binary versions, and procedures unchanged on my side).

**Comment by yan12125** [comment]
Fixed! Thanks for the examples.

**Comment by HiradNikoo** [comment]
I've got the exact problem. I've got two servers one in Germany and one in France when I try from server from Germany it is totally fine and the result is OK. But when I try from France server I get the error: "YouTube said: Invalid parameters"

**Comment by yan12125** [comment]
@HiradNikoo: are you using version 2018.01.27? That version improves error messages.

**Comment by nardev** [comment]
Could be, i didn't try to confirm, but that youtube limits the IPs from data centers. For a quite some time, google, netflix, and other big services added that as the decision making info for providing services. That's why you can't get cheap VPS and make your proxy for netflix any more.

**Comment by ChildishGiant** [comment]
I'm getting this right now for a video that is geoblocked, but not in my country, where my request is coming from.

**Comment by unkn0wn-src** [comment]
Im getting this error anytime i try no matter wich link or id um using. Please help

**Comment by Svito-zar** [comment]
@yan12125 , I also have the same issue with any link and id. Could you please help with that?
My `youtube-dl --version` is 2018.03.14

**Comment by llacb47** [comment]
Update your youtube-dl...

**Comment by yan12125** [comment]
I picked a random video (EXaLvBGqQww) and downloading works fine with version 2020.07.28. Most likely recent issues (if any) are different from those in 2018. Please make sure you are using the latest version and create a new issue if needed.

Locked this one as the original issue from 2018 have been solved for a long time.
