### ISSUE TITLE
youtube-dl is slow in downloading playlist

### ISSUE THREAD

**Issue by thesalah1212** [rg3/youtube-dl#15302]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.14**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.01.14
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I try to downoad from playlist on you tube with this command 
`youtube-dl --write-auto-sub --playlist-start 61 --force-ipv4 -o "/home/thesalah1212/videos/logic/%(playlist_index)s. %(title)s.%(ext)s"  https://www.youtube.com/playlist?list=PLBlnK6fEyqRjMH3mWf6kwqiTbT798eAOm`
the problem is the speed start decreasing from the 250 kiBs to 50 kiBs for every video

**Comment by KarthikChandy** [comment]
Same problem, the whole thing is so slow.
I gather that the problem is with YouTube slowing it on their end. Hope something can be done.
My output is here:

```bash
Desktop:~ $: youtube-dl -v -4 -f 140 https://www.youtube.com/watch?v=U3zVzP2fa-8 --output brown_noise.mp3
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-4', '-f', '140', 'https://www.youtube.com/watch?v=U3zVzP2fa-8', '--output', 'brown_noise.mp3']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.14
[debug] Python version 3.6.3 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[youtube] U3zVzP2fa-8: Downloading webpage
[youtube] U3zVzP2fa-8: Downloading video info webpage
[youtube] U3zVzP2fa-8: Extracting video information
[debug] Invoking downloader on 'https://r2---sn-ntq7yned.googlevideo.com/videoplayback?signature=1ADC1C56CE887CC54A4EBF22F04E1DEC6B578C57.DFD20E9314FB5134D1A4582C7DFF755094A92D71&mm=31&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ipbits=0&keepalive=yes&mime=audio%2Fmp4&itag=140&pl=22&mt=1516246242&mv=m&ei=QBVgWo6EIZ3CgAPj05iYDA&ms=au&requiressl=yes&gir=yes&clen=57177342&mn=sn-ntq7yned&source=youtube&initcwndbps=3560000&id=o-AEoLLtDqtRB25rpgsKLuN4GsQs1rXKE4o2fGb_cqwNvM&ip=54.240.193.129&key=yt6&lmt=1443761384428387&dur=3600.068&expire=1516267937&ratebypass=yes'
[download] Destination: brown_noise.mp3
[download]  11.0% of 54.53MiB at 55.70KiB/s ETA 14:52
```

**Comment by lainredsonic** [comment]
I have the same issue, It's very slow to download any ytb video.

**Comment by dstftw** [comment]
Youtube shaped download speed, use external downloader.

**Comment by barisyesilcimen** [comment]
i used axel and aria2c. Same issue. i tested with 20-30 diffrent commands and 3 vps.

**Comment by thesalah1212** [comment]
the problem is still on , further I use external downloader

**Comment by farazpartoei** [comment]
try to use -f 'best' which gives you .webm file and you can convert it to whatever using ffmpeg
