### ISSUE TITLE
[ZSH] Not support for zsh

### ISSUE THREAD

**Issue by jinfagang** [rg3/youtube-dl#15303]
Just for feature enchancement, youtube-dl command not support for zsh. And I think there should be some usage instructions for using/.

**Comment by dstftw** [comment]
Nothing special about zsh. youtube-dl works there just fine.

**Comment by jinfagang** [comment]
```
➜  data youtube-dl https://www.youtube.com/watch?v=7h1iv-9sqys
zsh: no matches found: https://www.youtube.com/watch?v=7h1iv-9sqys
```

**Comment by dstftw** [comment]
`?` is interpreted as wildcard by zsh, you must escape it or quote the URL. Learn how you shell work.
