### ISSUE TITLE
[audiomack] Error in exctactor

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#15310]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

http://www.audiomack.com/song/hip-hop-daily/black-mamba-freestyle

```
WARNING: "id" field is not a string - forcing string conversion, there is an error in extractor
```

**Comment by pedro-abreu** [comment]
Same here, can confirm. It would be great if they answered. My version is even more recent `2018.01.21`.

**Comment by marathone** [comment]
Perhaps you should update to a newer version 'youtube-dl -U'
