### ISSUE TITLE
Streaming video fail at https://cams-cdn.surfl ine.com/east-secure/ec-belmarcam.stream/chunklist.m3u8

### ISSUE THREAD

**Issue by BorrowedWifi** [rg3/youtube-dl#15326]
A change in the source which has been implemented very recently, perhaps even within the last 24 hours has resulted in the following error. Please note that the original directory structure from which the command was executed has been redacted, but all else is verbatim, straight from the command window in which the program was run. I hope this might be of some use, and can only wish I was able to do more to assist you in your excellent efforts to develop and maintain your outstanding software.

E:\...\...\... YOUTUBE-DL EXE>youtube-dl --verbose https://cams
-cdn.surfline.com/east-secure/ec-belmarcam.stream/chunklist.m3u8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://cams-cdn.surfline.com/east-sec
ure/ec-belmarcam.stream/chunklist.m3u8']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.14
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] chunklist: Requesting header
WARNING: Could not send HEAD request to https://cams-cdn.surfline.com/east-secur
e/ec-belmarcam.stream/chunklist.m3u8: HTTP Error 403: Forbidden
[generic] chunklist: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\bu
ild\youtube_dl\extractor\common.py", line 517, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\bu
ild\youtube_dl\YoutubeDL.py", line 2198, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau

**Comment by dstftw** [comment]
https://cams-cdn.surfline.com/east-secure/ec-belmarcam.stream/chunklist.m3u8 is 403 that is clearly stated in the log.

**Comment by BorrowedWifi** [comment]
Apologies for the waste of time and energy on your end. I missed that
cleanly. Sigh.
