### ISSUE TITLE
[Youtube] Ratebypass no longer works

### ISSUE THREAD

**Issue by Tyrrrz** [rg3/youtube-dl#15325]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['_QdPW8JrYzQ', '-f', '251', '-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018.01.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] _QdPW8JrYzQ: Downloading webpage
[youtube] _QdPW8JrYzQ: Downloading video info webpage
[youtube] _QdPW8JrYzQ: Extracting video information
[debug] Invoking downloader on 'https://r13---sn-3c27sn7k.googlevideo.com/videoplayback?keepalive=yes&nh=IgpwcjAyLmticDAzKgkxMjcuMC4wLjE&pl=18&initcwndbps=1393750&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cexpire&source=youtube&mt=1516289287&key=yt6&mime=audio%2Fwebm&clen=7554639&ipbits=0&itag=251&mn=sn-3c27sn7k&mm=31&signature=46139BF232DAF5CF4F6A41703F029BD78E20947A.4C3CADAF3E826381536E301B6764BC585681C323&gir=yes&dur=588.321&ms=au&mv=m&requiressl=yes&lmt=1497754431135135&ip=xxx.xxx.xxx.xxx&ei=W71gWtm_FYGA0wXt_b2ADw&expire=1516310971&id=o-AL9JmhKfh44w3MjmGvlb-zHtJxFQQE3QQMOXW724LeqE&ratebypass=yes'
[download] Destination: This is what happens when you reply to spam email _ James Veitch-_QdPW8JrYzQ.webm
[download] 100% of 7.20MiB in 02:16
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

`ratebypass` no longer has any effect, which results in extremely slow download speed. Observed in #15302, #15271, https://github.com/Tyrrrz/YoutubeExplode/issues/85. Only affects adaptive streams, muxed streams still work, which makes me think the issue is that `ratebypass` is not listed in `sparams`, while forcefully adding it breaks the signature.

**Comment by dstftw** [comment]
PRs welcome if you have any solution.

**Comment by Jakecheslekov** [comment]
I'm having this issue too! Wow I thought it was only me, this problem is driving me crazy! I don't know what I can do to help but if there's ANYTHING I can do to hurry this along I will be glad to!
What is a muxed stream? How do I know the difference between muxed and adaptive? O.o
Muxed means when you choose the resolution and sound and put them together??? But, mine are muxed... I think? maybe I'm wrong. I'm really not sure sorry. Some clarification on that would be nice :P

**Comment by Tyrrrz** [comment]
Muxed streams are the ones that have audio+video from the beginning and are limited to 720p.

**Comment by kenny-wettlaufer** [comment]
Any idea when ratebypass is going to be working again guys? The download speed is as slow as dial-up internet 50-90kbps

**Comment by kenny-wettlaufer** [comment]
I read on another locked post that "this is not an issue"... what does that mean?? When will downloads be fast again? :/ where do I find answers? The developer said to use the search but I don't understand what post am I supposed to find???

**Comment by artiemog** [comment]
Why was this issue closed? Has a solution been implemented?
