### ISSUE TITLE
Python 3.6 How to specify the external downloader location, please help.

### ISSUE THREAD

**Issue by G-Beni** [rg3/youtube-dl#15337]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.18**
(running as python module)
### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

---

---

im using python 3.6 with the youtube_dl module on windows 10 

Im trying to download Youtube videos with aria2c (because its very slow otherwise)(any other external downloader that can do this is fine for me) as mp3 only, audio only , best quality possible
These are my option settings:
"""
options = {
                    
                    'format':'bestaudio/best',
                    'extractaudio':True,
                    'audioformat':'mp3',
                    'outtmpl': Scraped_Music_Path + r'\%(title)s.%(ext)s',  
                    'noplaylist':True,
                    'nocheckcertificate':True,
                    'postprocessors': [{
                        'key': 'FFmpegExtractAudio',
                        'preferredcodec': 'mp3',
                        'preferredquality': '192',
                    }],
                    'ffmpeg_location': ffmpeg_path, #direct path to ffmpeg.exe
                    'ffprobe_location': ffprobe_path, #direct path to ffprobe.exe
                }
"""
this works but is very slow due to youtube throtteling after 30 % download, taking 60 sec for 3MB...
The path to aria2c is also added in the system Path variables.

but i cant figure out how to use the aria2c.exe in this programm

i tried adding this:
'external_downloader':  'aria2c',
'external_downloader_args': 'j 8 -s 8 -x 8 -k 5M', #not sure about these parameters

or this:
'external_downloader':  aria2c_path, #direct path to aria2c.exe
'external_downloader_args': 'j 8 -s 8 -x 8 -k 5M', #not sure about these parameters

it also tried printing the error but it just fails without an error. 
also im not realy sure what args to specify.

python console output.
"""
[youtube] jxipIRg-f2Y: Downloading webpage
[youtube] jxipIRg-f2Y: Downloading video info webpage
[youtube] jxipIRg-f2Y: Extracting video information
[download] Destination: C:\Users\Me\my\path\Test.webm
"""
and then nothing just breaks

needless to say after searching trough hundreds of google results, and the documentation and the source code im pretty frustrated.

**Comment by dstftw** [comment]
`'external_downloader': 'aria2c'` works just fine.

**Comment by G-Beni** [comment]
@dstftw does it also work to write this : 'external_downloader': aria2c_path, #direct path to aria2c.exe ? 
and if the aria2c isnt the problem what else could fail in this code ? do i even need ffmpeg/ffprobe if i have aria2c ?

**Comment by G-Beni** [comment]
@dstftw  i just retried in a new environment and it game me the "AssertionError"

**Comment by dstftw** [comment]
Path will not work. If you want any help open a new issue providing complete reproducible example source code with complete verbose log of the error.
