### ISSUE TITLE
Site support: paramountnetwork.com

### ISSUE THREAD

**Issue by gregBurgers** [rg3/youtube-dl#15351]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []                                                                                          
[debug] User config: [u'-o', u'~/Downloads/youtube-dl/%(title)s_-_%(uploader)s_-_%(resolution)s.%(ext)s', u'--user-agent', u'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36', u'--restrict-filenames']                                            
[debug] Custom config: []                                                                                                           
[debug] Command-line args: [u'-v', u'http://www.paramountnetwork.com/video-clips/4vwh0w/heathers-heathers-red-band-trailer']        
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8                                                                              
[debug] youtube-dl version 2018.01.18                                                                                                                 
[debug] Python version 2.7.13 (CPython) - Linux-4.4.92-31-default-x86_64-with-SuSE-42.3-x86_64                                                              
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4                                                                                                      
[debug] Proxy map: {}                                                                                                                                                      
[generic] heathers-heathers-red-band-trailer: Requesting header
WARNING: Falling back on generic information extractor.
[generic] heathers-heathers-red-band-trailer: Downloading webpage
[generic] heathers-heathers-red-band-trailer: Extracting information
ERROR: Unsupported URL: http://www.paramountnetwork.com/video-clips/4vwh0w/heathers-heathers-red-band-trailer
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2176, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2541, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2530, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 6, column 487
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3086, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.paramountnetwork.com/video-clips/4vwh0w/heathers-heathers-red-band-trailer
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.paramountnetwork.com/video-clips/4vwh0w/heathers-heathers-red-band-trailer

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Please add support for this site! :)

**Comment by Mr-Jake** [comment]
paramountnetwork.com is the rebranded Spike.com, which youtube-dl supported.

**Comment by SeanPM5** [comment]
I'd like this as well, I think it should be as simple as renaming the references to spike.com to paramountnetwork.com

In the meantime however you can find a downloadable link inside the "Embed" code button underneath the video player. For this example: youtube-dl "http://media.mtvnservices.com/embed/mgid:arc:video:paramountnetwork.com:010578ce-d581-420e-80a2-324a193f559c" --prefer-ffmpeg
