### ISSUE TITLE
Extremely slow speeds anyone?

### ISSUE THREAD

**Issue by Jakecheslekov** [rg3/youtube-dl#15356]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.18**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://us.youtube.com/watch?v=9vJRX_RQ39I']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.14
[debug] Python version 3.6.4 (CPython) - Linux-4.14.12-2-ck-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 9vJRX_RQ39I: Downloading webpage
[youtube] 9vJRX_RQ39I: Downloading video info webpage
[youtube] 9vJRX_RQ39I: Extracting video information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r8---sn-gvbxgn-t34e.googlevideo.com/videoplayback?ipbits=0&initcwndbps=1330000&expire=1516346972&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&mime=video%2Fwebm&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&gir=yes&ms=au&ei=_ElhWobpBNryDv2po7AG&mv=m&pl=16&mt=1516325266&clen=301308247&signature=31CE84BD1D681E162F3C4FFE329F3774F4A1EBB6.D0597B14EFA2BAC9F26CC13C9EE2B835A37BD488&key=yt6&mn=sn-gvbxgn-t34e&mm=31&id=o-AHBUoI2u-05H0TL7w9TE8Ie4lgf-g1skBb0ptjbMlNm-&dur=4570.866&source=youtube&pcm2cms=yes&keepalive=yes&ip=99.233.94.163&requiressl=yes&itag=247&lmt=1516316346875169&ratebypass=yes'

...
<end of log>

---
### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I've tried using https://ca.youtube as well as https://us.youtube & the normal https://www.youtube
Is it JUST ME or is YouTube videos downloading EXTREMELY slow? I know its not my internet, I can download stuff at about 1 MBPS, youtube videos are going at 75 kbps... It starts out at 1-2MBPS but it drops instantly to under 300 kbps then slowly goes down to 75 kbps... I hope this isn't some sort of governor on the speed of youtube videos because that would really suck. Are any of you getting these incredibly slow speeds??? Is it really just me??

**Comment by Jakecheslekov** [comment]
Sorry not sure how I messed that up ^ but I copy/pasted it into here so its more easily readable
~
I've tried using https://ca.youtube as well as https://us.youtube & the normal https://www.youtube
Is it JUST ME or is YouTube videos downloading EXTREMELY slow? I know its not my internet, I can download stuff at about 1 MBPS, youtube videos are going at 75 kbps... It starts out at 1-2MBPS but it drops instantly to under 300 kbps then slowly goes down to 75 kbps... I hope this isn't some sort of governor on the speed of youtube videos because that would really suck. Are any of you getting these incredibly slow speeds??? Is it really just me??

**Comment by SoneeJohn** [comment]
@Jakecheslekov it's not just you. See https://github.com/rg3/youtube-dl/issues/15325

**Comment by Jakecheslekov** [comment]
Oh well thank god its not just me, I thought I was screwed! Thank you SoneeJohn!

**Comment by Jakecheslekov** [comment]
Maybe I am misunderstanding the situation which is probably likely, but it says muxed streams aren't affected??? Muxed means when you choose the different parts of it right? Like... Isn't mine muxed when I do -f 135+140 or...? I'm sorry I'm still new to this stuff, please let me know if there's ANYTHING I can do to help.

**Comment by Hrxn** [comment]
Muxed in this context is direct single file streams, i.e. `-f best`.
So, no Full HD, etc.

**Comment by Jakecheslekov** [comment]
Oh jeez... Well in that case I need the other one because my netbook is only 480p...
