### ISSUE TITLE
Youtube download very slow :(

### ISSUE THREAD

**Issue by rodzky** [rg3/youtube-dl#15357]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.18**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
PS C:\youtubedl> youtube-dl https://www.youtube.com/watch?v=fjnb8gKW-h8 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=fjnb8gKW-h8', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.18
[debug] Python version 3.4.4 (CPython) - Windows-2012ServerR2-6.3.9600
[debug] exe versions: ffmpeg git-2017-12-23-9e5e323, ffprobe git-2017-12-23-9e5e323
[debug] Proxy map: {}
[youtube] fjnb8gKW-h8: Downloading webpage
[youtube] fjnb8gKW-h8: Downloading video info webpage
[youtube] fjnb8gKW-h8: Extracting video information
[youtube] {43} signature length 40.42, html5 player vflNX6xa_
[youtube] {18} signature length 40.42, html5 player vflNX6xa_
[youtube] {36} signature length 40.42, html5 player vflNX6xa_
[youtube] {17} signature length 40.42, html5 player vflNX6xa_
[youtube] {135} signature length 40.42, html5 player vflNX6xa_
[youtube] {244} signature length 40.42, html5 player vflNX6xa_
[youtube] {134} signature length 40.42, html5 player vflNX6xa_
[youtube] {243} signature length 40.42, html5 player vflNX6xa_
[youtube] {133} signature length 40.42, html5 player vflNX6xa_
[youtube] {242} signature length 40.42, html5 player vflNX6xa_
[youtube] {160} signature length 40.42, html5 player vflNX6xa_
[youtube] {278} signature length 40.42, html5 player vflNX6xa_
[youtube] {140} signature length 40.42, html5 player vflNX6xa_
[youtube] {171} signature length 40.42, html5 player vflNX6xa_
[youtube] {249} signature length 40.42, html5 player vflNX6xa_
[youtube] {250} signature length 40.42, html5 player vflNX6xa_
[youtube] {251} signature length 40.42, html5 player vflNX6xa_
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r3---sn-4g5e6nsr.googlevideo.com/videoplayback?expire=1516373320&ipbits=0&clen=2
2171367&requiressl=yes&mime=video%2Fmp4&pl=50&itag=135&mt=1516351598&dur=248.950&keepalive=yes&source=youtube&lmt=140884
6168432430&ei=6LBhWqf9Ddql1gLlgbHoBA&id=o-AKl8jWESovUA2K7uG_LYzt9fdroMuitHHqtZyIzTOUEm&ms=au&gcr=tr&mv=m&mm=31&mn=sn-4g5
e6nsr&key=yt6&ip=2a02%3Ac207%3A2015%3A6063%3A%3A1&initcwndbps=628750&aitags=133%2C134%2C135%2C160%2C242%2C243%2C244%2C27
8&gir=yes&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%
2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&signature=2112122DE1031C58A04593CCDE4E77A52A076C29.04643620FF72B
FCCDF75677FF2C9C3413BEBD1F8&ratebypass=yes'
[download] Destination: The Final 12 - Kaleidoscope World-fjnb8gKW-h8.f135.mp4
[download] 100% of 21.14MiB in 01:49
[debug] Invoking downloader on 'https://r3---sn-4g5e6nsr.googlevideo.com/videoplayback?expire=1516373320&ipbits=0&clen=4
148250&requiressl=yes&mime=audio%2Fwebm&pl=50&itag=251&mt=1516351598&dur=249.021&keepalive=yes&source=youtube&lmt=150647
6782379752&ei=6LBhWqf9Ddql1gLlgbHoBA&id=o-AKl8jWESovUA2K7uG_LYzt9fdroMuitHHqtZyIzTOUEm&ms=au&gcr=tr&mv=m&mm=31&mn=sn-4g5
e6nsr&key=yt6&ip=2a02%3Ac207%3A2015%3A6063%3A%3A1&initcwndbps=628750&gir=yes&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2C
initcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&signat
ure=E38D0C659554B35E7BF8DF982BF3AD68E60BF6B7.86FCDEAAAD7AC171E96A91E02C4538B521A73D92&ratebypass=yes'
[download] Destination: The Final 12 - Kaleidoscope World-fjnb8gKW-h8.f251.webm
[download] 100% of 3.96MiB in 01:07
[ffmpeg] Merging formats into "The Final 12 - Kaleidoscope World-fjnb8gKW-h8.mkv"
[debug] ffmpeg command line: ffmpeg -y -i "file:The Final 12 - Kaleidoscope World-fjnb8gKW-h8.f135.mp4" -i "file:The Fin
al 12 - Kaleidoscope World-fjnb8gKW-h8.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:The Final 12 - Kaleidoscope Wo
rld-fjnb8gKW-h8.temp.mkv"
Deleting original file The Final 12 - Kaleidoscope World-fjnb8gKW-h8.f135.mp4 (pass -k to keep)
Deleting original file The Final 12 - Kaleidoscope World-fjnb8gKW-h8.f251.webm (pass -k to keep)
...
<end of log>
```

I am having this problem since 2-3days ago, at first the download speed starts very high at around 30mbps but then it will immediately slow down to 100-200kbps. In this example the 3.96MB video took 1min 7secs to complete unlike before where it only take less than 5secs to process that. I tried --force-ipv4 but this didn't solve the problem, I've tried other videos I'm having the same issue. Please note that my dowload speed is on an average of 400mbps.

**Comment by rodzky** [comment]
@dstftw why did you close the issue?

**Comment by dstftw** [comment]
Cause it's not an issue. Use search.
