### ISSUE TITLE
[Youtube livestream] <channelID>/live is interpreted as a channel playlist

### ISSUE THREAD

**Issue by Bangaio65** [rg3/youtube-dl#15365]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

This started happening today, I use `-g` to get the m3u8 url as input for ffmpeg and I noticed my script started hanging. It turns out youtube-dl attempts to download all the videos in the channel instead of the livestream.

```
>youtube-dl -v -F "https://www.youtube.com/channel/UCR9120YBAqMfntqgRTKmkjQ/live"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/channel/UCR9120YBAqMfntqgRTKmkjQ/live']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.18
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-89788-g1eb7c1d49d, ffprobe N-89788-g1eb7c1d49d
[debug] Proxy map: {}
[youtube:live] UCR9120YBAqMfntqgRTKmkjQ: Downloading webpage
[youtube:channel] UCR9120YBAqMfntqgRTKmkjQ: Downloading channel page
[youtube:playlist] UUR9120YBAqMfntqgRTKmkjQ: Downloading webpage
[download] Downloading playlist: Uploads from A24
[youtube:playlist] playlist Uploads from A24: Downloading 61 videos
[download] Downloading video 1 of 61
[youtube] 6bncANEZTz4: Downloading webpage
[youtube] 6bncANEZTz4: Downloading video info webpage
[youtube] 6bncANEZTz4: Extracting video information
[info] Available formats for 6bncANEZTz4:

[...]
```
`youtube-dl -v -F "https://www.youtube.com/watch?v=kLlI76mNygk"` (same link but using video ID instead of /live) works as expected.

**Comment by baco** [comment]
Same here! Same version, same issue.
