### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by js017** [rg3/youtube-dl#15360]
Hi,

How do you use the geo restriction, or proxy features of youtube-dl to download a youtube video that says "The uploader has not made this video available in your country."? I already read the help file but need a better explanation. Could you tell me exactly what I should put into youtube-dl if I want to download any of these videos: "youtube.com/watch?v=EuFfmnu34rs", "youtube.com/watch?v=Sx0xOgFDXFg"? I'm not an advanced computer user so I'm just trying as best as I can to understand how to use youtube-dl. Thanks. Have a good day.

J S

**Comment by Jakecheslekov** [comment]
You could maybe try doing https://ca.youtube.com/ or https://us.youtube.com/

**Comment by dstftw** [comment]
You have to acquire a proxy that can access these videos then you can pass it with `--proxy`.
