### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 403:

### ISSUE THREAD

**Issue by imthecapedbaldy** [rg3/youtube-dl#15371]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.18**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
PS C:\Users\Rasheed\Desktop\udemy java master class> youtube-dl --verbose -u **************@gmail.com -p ******** https://www.udemy.com/java-the-complete-java-developer-cours/learn/v4/content
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.udemy.com/java-the-complete-java-developer-course/learn/v4/content']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.01.18
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by <HTTPError 403: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\users\rasheed\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\rasheed\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\rasheed\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\users\rasheed\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\rasheed\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\users\rasheed\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\rasheed\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

---

### Description of your *issue*, suggested solution and other information

Yes, I have an account and it's working. I've logged in over and over and over again using the same username/email and password. Yes, I just purchased this course literally a few hours ago. Was able to download up until video 226 out of 309. At video 227, this error occurred:
```
[download] Downloading video 226 of 309
[udemy] 5568206: Downloading webpage
[udemy] 5568206: Downloading lecture JSON
[udemy] 10423176: Downloading m3u8 information
[download] Destination: Data Binding-10423176.mp4
[download] 100% of 17.07MiB in 00:08
[download] Downloading video 227 of 309
[udemy] 5568208: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by <HTTPError 403: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Recreated error by executing exactly same command as used above. Changed nothing. I can still log into the my account and view the course videos. I can watch the current video that was not downloaded. No, it was not being updated as I have seen from other posts. 

Notes:

- I used python to install youtube-dl. Tried updating it with python.
- I've tried this over and over, same error.

**Comment by imthecapedbaldy** [comment]
Downloading videos from Udemy course. Again, I'm absolutely positive that I:

- udemy account exists and 100% accessible
- username and password is 100% correct
- have bought it. already watched some vids. 
- is absolute accessible. I previewed a lot of videos before and after this error.
- recreated error multiple times (all the time since it happened)

**Comment by dstftw** [comment]
You must provide account credentials for any further investigations.

**Comment by imthecapedbaldy** [comment]
what account credentials? my username and password for udemy?

**Comment by dstftw** [comment]
Udemy account credentials that reproduce this issue.

**Comment by imthecapedbaldy** [comment]
i'm going to have to leave my email and udemy password here out in the open??

**Comment by dstftw** [comment]
No, send by mail.

**Comment by imthecapedbaldy** [comment]
This is very strange. Absolutely strange. I was about to email you. I first changed my udemy password. Then i thought "hey this sounds stupid but hey it just might work if i try to execute it again with my new password. #stupidProgrammerLogic"
I changed absolutely no syntax. Just the password. NO SYNTAX WAS CHANGED. It's downloading again now. No error. But it's going over the ones downloaded first (before 227 where the error occurred). Will update if error re occurs in a few moments, Download speeds not so fast here in my country sorry. I implore you for your patience.

**Comment by imthecapedbaldy** [comment]
Error was not recreated. 309 of 309 videos were successfully downloaded. I have a speculation on the bug. For those who may encounter this in the future, here are some details and speculations on what could have caused this and how you may fix it:

When the error first occured, it threw a NOT AUTHORIZED response. Several attempts were tried again, still a NOT AUTHORIZED response. At some point (i don't remember how this was produced), it threw a NOT FOUND response. 
I changed my password, re executed the command, error did not occur again.
My first password was just a series of numbers, but when I changed it, it was a series of letters. This may have been the cause. I would type them in the command as (this is not my password, just an example) `-p 123456` no quotation marks or whatever. then i changed my password and is now working now that it does not have letters. So using numbers as a password may produce a very rare bug. Change your password/username. Will be closing this issue. Sorry for bothering, collaborators!

**Comment by dstftw** [comment]
Most likely this was caused due to a server side issue or some overuse protection. Definitely not due to characters used in a password.
