### ISSUE TITLE
Youtube downloads throttled. 

### ISSUE THREAD

**Issue by install-gentooo** [rg3/youtube-dl#15370]
I noticed abnormal  download speeds, even lower than 500KiB/s. 
Apparently I'm not the only one having this specific issue, but haven't seen anyone mentioning it here on Github. 
`[download]  89.8% of 29.99MiB at 338.08KiB/s ETA 00:09`
`[download]  69.8% of 3.18MiB at 72.12KiB/s ETA 00:13`
someone else's screenshot
![image](https://user-images.githubusercontent.com/31206196/35183858-08b52d4a-fded-11e7-9b96-ef6c82ad195a.png)

**Comment by dstftw** [comment]
It's throttled by Youtube.
