### ISSUE TITLE
[prosiebensat1] Unable to extract clip id

### ISSUE THREAD

**Issue by SaschaS1987** [rg3/youtube-dl#15378]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

https://www.sat1gold.de/film/mach-s-nochmal-auf-indisch/2017-mach-s-nochmal-auf-indisch-ganze-folge

```
youtube-dl.exe https://www.sat1gold.de/film/mach-s-nochmal-auf
-indisch/2017-mach-s-nochmal-auf-indisch-ganze-folge -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.sat1gold.de/film/mach-s-nochmal-auf-ind
isch/2017-mach-s-nochmal-auf-indisch-ganze-folge', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.01.18
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-88193-g5834cba05e, ffprobe N-88193-g5834cba05e, r
tmpdump 2.5
[debug] Proxy map: {}
[prosiebensat1] film/mach-s-nochmal-auf-indisch/2017-mach-s-nochmal-auf-indisch-
ganze-folge: Downloading webpage
ERROR: Unable to extract clip id; please report this issue on https://yt-dl.org/
bug . Make sure you are using the latest version; type  youtube-dl -U  to update
. Be sure to call youtube-dl with the --verbose flag and include its complete ou
tput.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\bu
ild\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\bu
ild\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\bu
ild\youtube_dl\extractor\prosiebensat1.py", line 442, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\bu
ild\youtube_dl\extractor\prosiebensat1.py", line 387, in _extract_clip
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\bu
ild\youtube_dl\extractor\common.py", line 803, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\bu
ild\youtube_dl\extractor\common.py", line 794, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract clip id; please report th
is issue on https://yt-dl.org/bug . Make sure you are using the latest version;
type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose fl
ag and include its complete output.
<end of log>
```

**Comment by SonGokuSSJ** [comment]
Could you try version 2018.01.21? That incorporated clip id fixes which worked for me for prosiebenmaxx. Your problem is probably fixed with that.
