### ISSUE TITLE
No Video Formats found for PBS video

### ISSUE THREAD

**Issue by PeskyPotato** [rg3/youtube-dl#15377]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Full Verbose

```
S041>youtube-dl --verbose http://www.pbs.org/video/nova-wild-predator-invasion/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.pbs.org/video/nova-wild-predator-invasion/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-81154-gfb91143, ffprobe N-81154-gfb91143
[debug] Proxy map: {}
[debug] Using fake IP 3.114.12.8 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] nova-wild-predator-invasion: Downloading webpage
[pbs] nova-wild-predator-invasion: Downloading widget/partnerplayer page
[pbs] nova-wild-predator-invasion: Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\extractor\pbs.py", line 590, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\extractor\common.py", line 1069, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```
### Description of your *issue*, suggested solution and other information

I have tried alternative links to the same video: 
http://www.pbs.org/video/nova-wild-predator-invasion/
http://www.pbs.org/wgbh/nova/nature/wild-predator-invasion.html
https://player.pbs.org/portalplayer/2365206276/?uid=

The output is the same as what is shown above. No video formats found.

**Comment by warbear** [comment]
Not a bug, video appears to have been removed from the listing for Season 41 http://www.pbs.org/show/nova/episodes/season/41/ 
See http://help.pbs.org/support/solutions/articles/12000000798-i-am-getting-the-message-this-video-is-unavailable-in-your-area-why-

**Comment by PeskyPotato** [comment]
Thank you for point that out, my bad. The episode is no longer available, sorry.
