### ISSUE TITLE
[minor][Windows] latest releases' version-info

### ISSUE THREAD

**Issue by eladkarako** [rg3/youtube-dl#15375]
Just <em>fyi</em>,
recent versions of youtube-dl.exe still uses <code>"2017.12.31"</code>,
in the VERSIONINFO data block.

<a href="https://github.com/rg3/youtube-dl/releases/tag/2018.01.18">tag/2018.01.18

**Comment by dstftw** [comment]
Wrong:
![image](https://user-images.githubusercontent.com/1908898/35187452-82f05580-fe56-11e7-9237-0d4d739ed57b.png)

**Comment by eladkarako** [comment]
oops that was a cache issue on my end.. never-mind..
