### ISSUE TITLE
BiliBili - cannot parse <h1> title when it has `<` or `>` characters inside

### ISSUE THREAD

**Issue by XVilka** [rg3/youtube-dl#15389]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.21**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

In line 
```python
 title = self._html_search_regex('<h1[^>]*>([^<]+)</h1>', webpage, 'title')
```
of https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/bilibili.py you  do the regex search. But it is common for videos to contain `>` and `<` characters as a part of a title.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
