### ISSUE TITLE
Add Support for LinkedIn Learning (very similar to Lynda.com)

### ISSUE THREAD

**Issue by bokazero** [rg3/youtube-dl#15387]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.linkedin.com/learning/learning-python']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.21
[debug] Python version 2.7.11 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] learning-python: Requesting header
[redirect] Following redirect to https://www.linkedin.com/content-guest/learning/internal-server-error
[generic] internal-server-error: Requesting header
[redirect] Following redirect to https://www.linkedin.com/
[generic] www.linkedin: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.linkedin: Downloading webpage
[generic] www.linkedin: Extracting information
ERROR: Unsupported URL: https://www.linkedin.com/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2192, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2541, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2530, in _XML
    parser.feed(text)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 769, column 14
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3108, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.linkedin.com/
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.linkedin.com/learning/learning-python/what-you-should-already-know?autoplay=true
- Single video: https://www.linkedin.com/learning/learning-python/what-you-should-already-know
- Playlist: https://www.linkedin.com/learning/learning-python

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

There're some issues that users are trying to download video/courses from LinkedIn, but it's not implemented.

> PS: The LinkedIn Learning is the same as Lynda.com, so it should work very similar

> PS2: In case you need a user + password, you can sign in for [a month trial](https://www.linkedin.com/help/linkedin/answer/72?query=free%20trial%20learnin) or 3 months free if subscription if you are a [Microsoft Visual Studio Dev Essentials](https://www.visualstudio.com/dev-essentials/) user (free).

Related Issues: #13545 #9819 #15120 #14233 #9973 #9843

**Comment by bokazero** [comment]
Hi @dstftw, I'm afraid this issue is not duplicated.

None of the related issues is to add support to LinkedIn.com/learning, the new website LinkedIn Learning. They are related to the deprecated Lynda.com which is going to be migrated to LinkedIn.com/learning that has been released very recently.

Also, none of the previous issues provides the correct single video and playlist URLs.

Thanks.

**Comment by Ser-Zile** [comment]
I can confirm that as of typing this comment LinkedIn Learning is still not working.
