### ISSUE TITLE
Readme does not make it clear on how to download a playlist in the mp3 format - not mp4.

### ISSUE THREAD

**Issue by hexx112** [rg3/youtube-dl#15391]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.21**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

Readme does not make it clear on how to download a playlist in the mp3 format - not mp4.

**Comment by clampak** [comment]
Having the README list how to download everything in every format would make it impossibly long. 

Have you tried passing the `-f mp3` option on the command line?

**Comment by dstftw** [comment]
Readme is not supposed to cover with examples just any possible usecase. Nonetheless it contains enough data to figure that out on your own. Needless to say this was asked numerous of times one should only bother to use search.
