### ISSUE TITLE
pls add support for boomerang.com site-support-request

### ISSUE THREAD

**Issue by jakop345** [rg3/youtube-dl#15402]
pls add support for boomerang.com

**Comment by elfurbe** [comment]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.20**
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---
```
$ youtube-dl -v https://www.boomerang.com/watch/3/22
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.boomerang.com/watch/3/22']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.20
[debug] Python version 3.6.3 (CPython) - Linux-3.10.0-693.17.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 22: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 22: Downloading webpage
[generic] 22: Extracting information
ERROR: Unsupported URL: https://www.boomerang.com/watch/3/22
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3161, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.boomerang.com/watch/3/22
```
---
- Single video: https://www.boomerang.com/watch/3/22
---
Saw this closed issue for adding boomerang support was marked "incomplete", so here's a more complete request, as I would also appreciate this site being supported. The service offers a 7-day free trial for credentials. If someone picks up this issue for active work and needs longer-term access to sort it out, I'd be happy to set up an account for that.
