### ISSUE TITLE
Downloading full MTV show not working for me

### ISSUE THREAD

**Issue by anga83** [rg3/youtube-dl#15407]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.21**
- [x] Issue

Hi there!
I tried to download a full MTV show via youtube-dl, which at first looked fine: It found all the HLS playlists (even though they should be country restricted 👍 ) and stated
`[mtv] playlist K3U: Collected 6 video ids (downloading 6 of them)`

Problem is, right after downloading the first part youtube-dl exits with

`ERROR: av_interleaved_write_frame(): Invalid argument
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2034, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 546, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 208, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: av_interleaved_write_frame(): Invalid argument
`
ffmpeg version is also up to date (3.4.1)
Here's a example of a show to reproduce this behaviour: http://www.mtv.com/episodes/rxehms/eye-candy-k3u-season-1-ep-101

Is there any thing I missed or can do?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
