### ISSUE TITLE
youtube-dl vs RayWenderlich Video's

### ISSUE THREAD

**Issue by aster007** [rg3/youtube-dl#15405]
Hello,

Note that I am trying to download videos from RayWenderlich.com

I have paid the subscription, the thing is that I will not be online for more than a week in February.

To the Bug itself:

1. My config: MBP with OSX Sierra 10.12.6, youtube-dl was installed and updated via homebrew.
2. Version of youtube-dl: 2018.01.21
3. Command I am entering:
youtube-dl https://videos.raywenderlich.com/courses/95-beginning-collection-views/lessons/3 --cookies cookies.txt
(cookies were obtained via the export to txt cookies extension from chrome)
4. Error I am getting:

[generic] 3: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3: Downloading webpage
[generic] 3: Extracting information
ERROR: Unsupported URL: https://videos.raywenderlich.com/courses/95-beginning-collection-views/lessons/3

I have also been looking into the video switch there:

--video-password but that one does not work for me as well.

5. Please if you provide me with the command for the videos, then please let me know the one for the whole playlist.

**Comment by dstftw** [comment]
Not supported.

**Comment by Gaket** [comment]
Looks like the dev team needs an account to implement it:
https://github.com/ytdl-org/youtube-dl/issues/15830
