### ISSUE TITLE
[Go90] various issues

### ISSUE THREAD

**Issue by 2011** [rg3/youtube-dl#15404]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.18**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
---
---
```
$ youtube-dl -v  -f best 'https://www.go90.com/videos/261MflWkD3N'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', '-f', 'best', 'https://www.go90.com/videos/261MflWkD3N']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.18
[debug] Python version 3.4.5 (CPython) - Linux-4.4.39-gentoo-x86_64-Intel-R-_Core-TM-_i5_CPU_750_@_2.67GHz-with-gentoo-2.3
[debug] exe versions: ffmpeg 2.8.10, ffprobe 2.8.10, rtmpdump 2.4
[Go90] 261MflWkD3N: Downloading JSON metadata
[Go90] 261MflWkD3N: Downloading MPD manifest
[Go90] 261MflWkD3N: Downloading m3u8 information
[debug] Invoking downloader on 'https://www.revvel.io/api/playlists/sub/261MflWkD3N/88FnhTnom9O/359MFP6zm71/hls/hls-1080-4800K?v_source=a&key=go90&drm=0&expires_at=1516771554&token=efab48d801efaac222b4ec7666911708cfa1252939a13c6d70b8464f9a85f228'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 65
[download] Destination: Kobe_Bryant_s_Dear_Basketball-261MflWkD3N-NA.mp4
[download]  14.4% of ~162.12MiB at 62.17KiB/s ETA 03:43...
<end of log>
```
---
---

Three things:
1. Fails out of the box with "embed" in the command line instead of "videos" (I only mention this because youtube itself works with either form).
2. When attempting to resume (see part 3), it seems the most recent fragment should be cleared, otherwise the program just concatenates the fragment (from the beginning) to whatever is already there, resulting in a corrupt file.
3 (the big one). Having problems downloading (have only tried this URL for this site). Youtube-dl "freezes" after a fragment or two (download just stops with no indication of a problem). Seems to get stuck in the same place, but occasionally will complete a fragment and move on to the next one. Have made over forty attempts (keeping the .part file, but removing part-Fragn.part each time before restarting), and have succeeded in getting eight fragments (out of sixty-five) with the program now stuck on number nine (output pasted above is after the download has frozen - there are no further updates). Have never seen this with any other site.

**Comment by dstftw** [comment]
1. Post complete exact log what fails.
2. No, it should not. Post concrete log demonstrating it.
3. Again, post concrete logs demonstrating problem.

**Comment by 2011** [comment]
1.
```
$ youtube-dl -v -f best 'https://www.go90.com/embed/261MflWkD3N'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', '-f', 'best', 'https://www.go90.com/embed/261MflWkD3N']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.18
[debug] Python version 3.4.5 (CPython) - Linux-4.4.39-gentoo-x86_64-Intel-R-_Core-TM-_i5_CPU_750_@_2.67GHz-with-gentoo-2.3
[debug] exe versions: ffmpeg 2.8.10, ffprobe 2.8.10, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 261MflWkD3N: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 261MflWkD3N: Downloading webpage
[generic] 261MflWkD3N: Extracting information
ERROR: Unsupported URL: https://www.go90.com/embed/261MflWkD3N
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/generic.py", line 3086, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.go90.com/embed/261MflWkD3N
```

2. Directory after first failure, running the same command as above (note that each fragment is ~2.5 MB:
```
$ ls -al youtube-dl.temp/
total 4460
drwx------  2 user user    4096 2018-01-25 10:32:16 ./
drwxrwxr-x 33 user user   36864 2018-01-25 10:27:07 ../
-rw-------  1 user user 2228553 2018-01-25 10:32:14 Kobe_Bryant_s_Dear_Basketball-261MflWkD3N-NA.mp4.part
-rw-------  1 user user 2289062 2018-01-25 10:32:51 Kobe_Bryant_s_Dear_Basketball-261MflWkD3N-NA.mp4.part-Frag1.part
-rw-------  1 user user      50 2018-01-25 10:32:14 Kobe_Bryant_s_Dear_Basketball-261MflWkD3N-NA.mp4.ytdl
```

Directory after ten more attempts (not erasing Frag1 between attempts). The log files are identical, except that on subsequent attempts, the program now estimates the total size as ~4.85GiB (which is incorrect - it is about 170 MiB, which is close to the estimate on the first attempt).
```
$ ls -al youtube-dl.temp/
total 27144
drwx------  2 user user     4096 2018-01-25 10:32:16 ./
drwxrwxr-x 33 user user    36864 2018-01-25 10:27:07 ../
-rw-------  1 user user  2228553 2018-01-25 10:32:14 Kobe_Bryant_s_Dear_Basketball-261MflWkD3N-NA.mp4.part
-rw-------  1 user user 25510936 2018-01-25 10:55:39 Kobe_Bryant_s_Dear_Basketball-261MflWkD3N-NA.mp4.part-Frag1.part
-rw-------  1 user user       50 2018-01-25 10:32:14 Kobe_Bryant_s_Dear_Basketball-261MflWkD3N-NA.mp4.ytdl
```

Each attempt adds ~2.5 MiB to the Frag1 file. I assure you the many times concatenated Frag1 file is quite corrupt. Resuming a download by simply concatenating a fragment (from the beginning of the fragment) onto a partial fragment that already exists is quite obviously an error, which is exactly what the program does (at least with this site).

3. You have the entire log. The program simply stops, gets stuck, freezes, or whatever. There is no additional output, and nothing further is downloaded beyond the point indicated (even leaving the program running for an hour). I have never seen this behavior on any other site.

**Comment by 2011** [comment]
@dstftw Are you going to reopen this, or do I need to file a new bug?
