### ISSUE TITLE
Youtube-dl doesn't seem to be able to download certain videos from youtube.com anymore

### ISSUE THREAD

**Issue by IoanPaleru** [rg3/youtube-dl#15417]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.21**
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Bug report (encountered problems with youtube-dl)

```
C:\Users\Computer User\Downloads>youtube-dl -v https://www.youtube.com/watch?v=E
uFfmnu34rs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=EuFfmnu34rs']

[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.21
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg N-83657-g7e4f32f, ffprob
e N-83657-g7e4f32f
[debug] Proxy map: {}
[youtube] EuFfmnu34rs: Downloading webpage
[youtube] EuFfmnu34rs: Downloading video info webpage
ERROR: EuFfmnu34rs: YouTube said: Invalid parameters.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\bu
ild\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\bu
ild\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\bu
ild\youtube_dl\extractor\youtube.py", line 1609, in _real_extract
youtube_dl.utils.ExtractorError: EuFfmnu34rs: YouTube said: Invalid parameters.
...
<end of log>
```

Hi. Youtube-dl is an excellent program, it can usually download videos from youtube and other sites quickly and easily in many different formats, and has lots of customization options, however lately it seems that it isn't downloading certain videos from youtube like this one "https://www.youtube.com/watch?v=EuFfmnu34rs", for example.

Also, something that may be useful for troubleshooting and related to this issue with youtube-dl, having to do with a change on youtube's website, not with youtube-dl itself, is that it seems that certain online youtube video downloader websites like these ones "get-video.online", "getvidnow.com", yoodownload.com" also aren't able to download the link to the youtube video above, even though they used to be able to, while these ones "clipconverter.cc", "convert2mp3.net/en", "youtubemultidownloader.com" are. So maybe youtube has changed something on their website that's making youtube-dl unable to download certain videos? It used to be that you could just type "youtube-dl <video URL>" and the video would download fine, but now it doesn't for certain videos, however this video "https://www.youtube.com/watch?v=Zi_XLOBDo_Y" still downloads fine with youtube-dl.

I'd really appreciate some more information on this, and to know if anyone else is experiencing this, as well as to know if there's anything that can be done to fix it. If you need any other information, please let me know. Thanks. Have a good day.

**Comment by al1fr** [comment]
`youtube-dl.exe "https://www.youtube.com/watch?v=EuFfmnu34rs"` works for me

**Comment by yan12125** [comment]
Could you check that you can watch this video in browsers without proxies/VPNs/...? "Invalid parameters" often indicates a video is unavailable. (#15284)

**Comment by rautamiekka** [comment]
The problem on Window$ is you **have to double-quote _each_ address**.

**Comment by IoanPaleru** [comment]
Yes this video "https://www.youtube.com/watch?v=EuFfmnu34rs" does seem to be region blocked, however even other videos that played normally in my browser without a vpn or proxy weren't able to be downloaded by youtube-dl recently, but now youtube-dl seems to be able to download them properly.

By the way, when trying to download youtube videos that are region blocked to the US if you're in another country can youtube-dl download them? Going to us.youtube.com doesn't work, because it says "Server not found", and someone else said that you can use --proxy, and put in a proxy address that can access the video, but what does that mean, how do you do that, where can you find a proxy address like that?

Youtube-dl is an excellent program, and if I find any other videos that don't download properly, I'll let you know. Thanks. Have a good day.

**Comment by MhmdSalah** [comment]
Hello! i ran into this problem and i am interested in a solution. my web app is an api that takes a youtube url and returns extracted download links (no video downloaded to servers, return direct download links from youtube). e.g. 

youtube-dl -g https://www.youtube.com/watch?v=iOe6dI2JhgU

the problem is, youtube-dl returns download urls that are not working (getting http response forbidden), but the urls look normal to me

is there a way to detect that the video is protected so my webapp does bot return broken download urls?

**Comment by KonomiKitten** [comment]
I am getting this issue too.

```
$ youtube-dl -v 'https://www.youtube.com/watch?v=5K3nZ9YNDm8'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=5K3nZ9YNDm8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.21
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-5-amd64-x86_64-with-debian-9.3
[debug] exe versions: ffmpeg 3.3.6, ffprobe 3.3.6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 5K3nZ9YNDm8: Downloading webpage
[youtube] 5K3nZ9YNDm8: Downloading video info webpage
ERROR: 5K3nZ9YNDm8: YouTube said: Invalid parameters.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1609, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: 5K3nZ9YNDm8: YouTube said: Invalid parameters.
```

**Comment by yan12125** [comment]
@IoanPaleru

> however even other videos that played normally in my browser without a vpn or proxy weren't able to be downloaded by youtube-dl recently, but now youtube-dl seems to be able to download them properly.

Do you mean sometimes it works and sometimes it doesn't? Could you paste some such URLs?

About proxies: there are some free proxies out there, Google it! I don't use them often. Maybe someone are kind to share which proxy is a good choice.

@MhmdSalah: that's a different issue. YouTube links generated on one machine works for that machine only. Check out https://github.com/rg3/youtube-dl/blob/master/README.md#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser

**Comment by MhmdSalah** [comment]
@yan12125: Correct! i just tried and you are right, i was able to download the video to server but links don't work from different ip. What is the way to detect such protected video and stop api from returning links to client?

here is a metadata dump for a protected video http://api.inka.ps/meta?url=https://www.youtube.com/watch?v=iOe6dI2JhgU

and here is one for a normal video http://api.inka.ps/meta?url=https://www.youtube.com/watch?v=vOJFxkTAsHo

**Comment by yan12125** [comment]
@MhmdSalah: Some people reported that URLs starting with "https://redirector.googlevideo.com" can work around IP restrictions. See #11357.

**Comment by MhmdSalah** [comment]
@yan12125: Thank you, but it does not seem to work anymore. seems like i have to check on client side for response code. if anybody has a fix it would be appreciated.

**Comment by IoanPaleru** [comment]
Yan12125 said:

"Do you mean sometimes it works and sometimes it doesn't? Could you paste some such URLs?"

Yan12125,

Thanks for your response. I meant that a few days ago, it seemed that youtube-dl wasn't able to download any videos from youtube at all, even ones that weren't region blocked, but now it seems to be able to download all those videos normally. If I find any other videos that youtube-dl can't download, I'll let you know, but at the moment, everything seems to be working normally with youtube-dl. I hope that clarifies everything, and please keep up the great work with youtube-dl, because it's a very good program. Have a good day.

**Comment by IoanPaleru** [comment]
Yan12125 said:

"Do you mean sometimes it works and sometimes it doesn't? Could you paste some such URLs?"

Yan12125,

Thanks for your response. I meant that a few days ago, it seemed that youtube-dl wasn't able to download any videos from youtube at all, even ones that weren't region blocked, but now it seems to be able to download all those videos normally. If I find any other videos that youtube-dl can't download, I'll let you know, but at the moment, everything seems to be working normally with youtube-dl. I hope that clarifies everything, and please keep up the great work with youtube-dl, because it's a very good program. Have a good day.

**Comment by 4kgit** [comment]
I am trying to download the view https://www.youtube.com/watch?v=YA-FeR4sHqQ

but it seems youtube-dl does not like - character in the link. 

youtube-dl -F https://www.youtube.com/watch?v=YA-FeR4sHqQ
[youtube] YA-FeR4sHqQ: Downloading webpage
[youtube] YA-FeR4sHqQ: Downloading video info webpage
ERROR: YA-FeR4sHqQ: YouTube said: This video is not available.

**Comment by Hrxn** [comment]
Use quotation marks for the URL..

**Comment by 4kgit** [comment]
Tried with quotation youtube-dl -F "https://www.youtube.com/watch?v=YA-FeR4sHqQ"

Same result its actually reading the webpage but not downloading...

**Comment by hipertracker** [comment]
I cannot download this video
```
youtube-dl -F https://youtu.be/4phYuoi2NHY

[youtube] 4phYuoi2NHY: Downloading webpage
[youtube] 4phYuoi2NHY: Downloading embed webpage
[youtube] 4phYuoi2NHY: Refetching age-gated info webpage
[youtube] 4phYuoi2NHY: Extracting video information
ERROR: This video can't be played here, but you can still watch it on YouTube. Watch on YouTube
```

**Comment by Vajdoch** [comment]
I have same problem using youtube_dl by my discord bot. Ut can play audio from some videao (https://www.youtube.com/watch?v=nlcKDsq-C4k) but form some can not (https://www.youtube.com/watch?v=O4irXQhgMqg). When i tried to download them by using `youtube-dl -v URL` the results were same. Before 7th of September 2018 i could play everything.

**Comment by sebastienchouan** [comment]
You can use the option -i :
**-i, --ignore-errors
Continue on download errors, for example to skip unavailable videos in a playlist**

it works for me.

**Comment by aurelien-git** [comment]
-i does not works for me
