### ISSUE TITLE
Spike changed name to Paramount and now Spike extractor doesn't recognize new URL's

### ISSUE THREAD

**Issue by tv21** [rg3/youtube-dl#15418]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--restrict-filenames', u'--ap-mso', u'PRIVATE', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'-v', u'http://www.paramountnetwork.com/episodes/xcjgtt/waco-visions-and-omens-season-1-ep-1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.21
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-112-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.4-static, ffprobe 3.4-static
[debug] Proxy map: {}
[generic] waco-visions-and-omens-season-1-ep-1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] waco-visions-and-omens-season-1-ep-1: Downloading webpage
[generic] waco-visions-and-omens-season-1-ep-1: Extracting information
ERROR: Unsupported URL: http://www.paramountnetwork.com/episodes/xcjgtt/waco-visions-and-omens-season-1-ep-1
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2192, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2541, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2530, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 6, column 487
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3108, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.paramountnetwork.com/episodes/xcjgtt/waco-visions-and-omens-season-1-ep-1
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.paramountnetwork.com/episodes/xcjgtt/waco-visions-and-omens-season-1-ep-1
- Single video: http://www.paramountnetwork.com/video-clips/577az5/waco-weeks-ahead

---

### Description of your *issue*, suggested solution and other information

Paramount Network is the new name for the former Spike TV (https://en.wikipedia.org/wiki/Paramount_Network), so if you had an extractor for Spike it may well work if you can change the Spike extractor to recognize new paramountnetwork.com URL's.

**Comment by tv21** [comment]
Just as a test I downloaded the source and went into spike.py and replaced all instances of spike in spike.com or spike\.com with paramountnetwork (I did not change any instances not followed by .com or \.com).  That allowed it to work, at least with a full episode (although it got it in five parts; wish there was some way to make it automatically join them into a single file).  I know that is probably not a proper fix but at least it indicates that the spike extractor probably doesn't require any major changes to fix this, and I know pretty much nothing about Python.

**Comment by novigradian** [comment]
The site does seem to be similar. I'll try and change it over and see if it works.

**Comment by tindivall** [comment]
I would be willing to take downloads even if they are in parts (I can then combine them afterwards) however I am not sure how to do what you mention @tv21 

I download the full youtube-dl and then I changed spike.py as you mentioned replacing spike with paramountnetwork.   

How do I then get youtube-dl to pull from my changed file on my computer instead of from the spike.py here on github (or wherever it pulls from).

**Comment by tv21** [comment]
@tindivall assuming you have the source on your system, you would run /path/to/youtube-dl-master/youtube_dl/__main__.py http... (replacing /path/to and http... as appropriate).
