### ISSUE TITLE
Question regarding prefering specific formats

### ISSUE THREAD

**Issue by qutetemp** [rg3/youtube-dl#15435]
Is there something like prefer-free-formats but generalized ? Not always downloading those formats but prefering them only and only if they meet the requirements similar to how prefer-free-formats will not download webm of a video with the highest video stream being mp4.

If you're going to redirect me to the documentation please tell me what I might be missing.
Thanks.

**Comment by dstftw** [comment]
Did you even read FAQ?
```
--prefer-free-formats            Prefer free video formats unless a specific
                                 one is requested
```

**Comment by qutetemp** [comment]
No man. Generalized like prefer-[these-formats].
For example in the case of prefer-free-formats it would prefer webm, I want to be able to specific what it should prefer, like for example mp4.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#format-selection
