### ISSUE TITLE
The batch file connot be found.

### ISSUE THREAD

**Issue by DeathRowRecords** [rg3/youtube-dl#15443]
![commandpromp](https://user-images.githubusercontent.com/30491775/35482813-8c57df8c-043a-11e8-9a4f-4342fd4395af.gif)

[By any chance?](https://stackoverflow.com/questions/3849095/does-a-bat-file-know-its-name-and-can-it-delete-itself) [Y/n]

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by DeathRowRecords** [comment]
Like seriously dude?! Low Blow Bro. Are you one of those gestapo people. Not Cool.
