### ISSUE TITLE
Unable to download from hotstar

### ISSUE THREAD

**Issue by lovablegce** [rg3/youtube-dl#15449]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.27*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.27**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\GaneshAjay>youtube-dl -v http://www.hotstar.com/tv/raja-rani/14230/swamiji-visits-karthik/1000202932
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.hotstar.com/tv/raja-rani/14230/swamiji-visits-karthik/1000202932']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.27
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-89901-ga026a3efae, ffprobe N-89901-ga026a3efae
[debug] Proxy map: {}
[debug] Using fake IP 117.236.209.126 (IN) as X-Forwarded-For.
[hotstar:playlist] 14230: Downloading JSON metadata
[hotstar:playlist] 14064: Downloading JSON metadata
[download] Downloading playlist: 14064
[hotstar:playlist] playlist 14064: Collected 174 video ids (downloading 174 of them)
[download] Downloading video 1 of 174
[debug] Using fake IP 117.248.203.162 (IN) as X-Forwarded-For.
[HotStar] 1000202932: Downloading JSON metadata
[HotStar] 1000202932: Downloading JIO JSON metadata
[HotStar] 1000202932: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://staragvod3-vh.akamaihd.net/i/videos/vijay/rajarani/174/1000202932_,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/index_8_av.m3u8?null=0&id=AgDSEo3Vc3ACXNfkblp67jis834cVHvnmZ4pZ79qMCVEYece4KsIiFcfO9CSyi5FxQTlVoJN6VHKlg%3d%3d'
[download] Destination: Swamiji Visits Karthik-1000202932.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
Accept-Language: en-us,en;q=0.5
Cookie: _alid_=jOZ1S5DTFXNewGUovVg1GA==; hdntl=exp=1517303383~acl=%2f*~data=hdntl~hmac=ba537e23e324ff87af86cec2471bec0526b17b9c25119b95572a7a7dafa8bfd5
X-Forwarded-For: 117.248.203.162
" -i "https://staragvod3-vh.akamaihd.net/i/videos/vijay/rajarani/174/1000202932_,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/index_8_av.m3u8?null=0&id=AgDSEo3Vc3ACXNfkblp67jis834cVHvnmZ4pZ79qMCVEYece4KsIiFcfO9CSyi5FxQTlVoJN6VHKlg%3d%3d" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:Swamiji Visits Karthik-1000202932.mp4.part"
ffmpeg version N-89901-ga026a3efae Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
  libavutil      56.  7.100 / 56.  7.100
  libavcodec     58.  9.100 / 58.  9.100
  libavformat    58.  6.100 / 58.  6.100
  libavdevice    58.  0.101 / 58.  0.101
  libavfilter     7. 11.101 /  7. 11.101
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
[tls @ 000001c5067edf40] Error in the pull function.


ERROR: ffmpeg exited with code 255
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 1988, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 795, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 994, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 856, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 795, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 849, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 1622, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 1895, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 1834, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\downloader\external.py", line 57, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\downloader\common.py", line 163, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 612, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 574, in trouble
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.hotstar.com/tv/raja-rani/14230/swamiji-visits-karthik/1000202932

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Unable to download videos from Hotstar. Getting an error saying

"ERROR: ffmpeg exited with code 255"

Please help on the issue.

**Comment by rajucomp** [comment]
I can download this from here. Here is the log 

`[hotstar:playlist] 14230: Downloading JSON metadata`
`[hotstar:playlist] 14064: Downloading JSON metadata`
`[download] Downloading playlist: 14064`
`[hotstar:playlist] playlist 14064: Collected 177 video ids (downloading 177 of them)`
`[download] Downloading video 1 of 177`
`[HotStar] 1000203416: Downloading JSON metadata`
`[HotStar] 1000203416: Downloading JIO JSON metadata`
`[HotStar] 1000203416: Downloading m3u8 information`
`[hlsnative] Downloading m3u8 manifest`
`[hlsnative] Total fragments: 213`
`[download] Destination: Sembaruthi's Request to the Police-1000203416.mp4`
`[download]   1.2% of ~735.14MiB at  2.09MiB/s ETA 07:46`
`ERROR: Interrupted by user`

Try using `--hls-prefer-native` like this 
`youtube-dl.exe --hls-prefer-native http://www.hotstar.com/tv/raja-rani/14230/swamiji-visits-karthik/1000202932`

**Comment by lovablegce** [comment]
Yeah it is working now.. Thank you so much..

**Comment by newwalahai1** [comment]
i can't download this it says this video is drm protected

https://www.hotstar.com/tv/the-deuce/s-1189/they-can-never-go-home/1770021934

here is my log

C:\Users\PR>youtube-dl.exe -v https://www.hotstar.com/tv/the-deuce/s-1189/they-can-never-go-home/1770021934
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.hotstar.com/tv/the-deuce/s-1189/they-can-never-go-home/1770021934']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[hotstar] 1770021934: Downloading webpage
ERROR: This video is DRM protected.
Traceback (most recent call last):
  File "c:\users\pr\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\pr\python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\pr\python37\lib\site-packages\youtube_dl\extractor\hotstar.py", line 119, in _real_extract
    raise ExtractorError('This video is DRM protected.', expected=True)
youtube_dl.utils.ExtractorError: This video is DRM protected.
