### ISSUE TITLE
Audio can not be heard if resolution is increased

### ISSUE THREAD

**Issue by 7z-775** [rg3/youtube-dl#15466]
I am using youtube-dl and I have saved retro movies(https://www.youtube.com/watch?v=WUgmlmuHZ9c).
However, if you raise the resolution, the sound of the movie will be lost or you will be unable to read it.
What is the cause of this?
The problem is occurring on smartphone, PC.

I write in Translate-shell because I have poor English grades.
sorry

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
