### ISSUE TITLE
[ooyla] current time is after the flight end time

### ISSUE THREAD

**Issue by 133794m3r** [rg3/youtube-dl#15460]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.27*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable 
to your *issue*
./youtube-dl -v https://www3.nhk.or.jp/nhkworld/en/vod/newsroomtokyo/1002762/
[debug] System config: []
[debug] User config: [u'-f', u'best[height<=360]/best[ext=mp4]', u'-o', u'/tmpdownload/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www3.nhk.or.jp/nhkworld/en/vod/newsroomtokyo/1002762/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.27
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-4-amd64-x86_64-with-debian-9.3
[debug] exe versions: avconv 3.2.9-1, avprobe 3.2.9-1, ffmpeg 3.2.9-1, ffprobe 3.2.9-1, rtmpdump 2.4
[debug] Proxy map: {}
[NhkVod] newsroomtokyo/1002762: Downloading JSON metadata
[Ooyala] lqc3k1ZTE6lB26lcn7FA_1PREyVQcdqL: Downloading JSON metadata
[Ooyala] lqc3k1ZTE6lB26lcn7FA_1PREyVQcdqL: Downloading JSON metadata
ERROR: Ooyala said: current time is after the flight end time
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/ooyala.py", line 170, in _real_extract
    return self._extract(content_tree_url, embed_code, domain, supportedformats, embed_token)
  File "./youtube-dl/youtube_dl/extractor/ooyala.py", line 86, in _extract
    self.IE_NAME, cur_auth_data['message']), expected=True)
ExtractorError: Ooyala said: current time is after the flight end time

---

---

### Description of your *issue*, suggested solution and other information

no idea what this error means but it's happening on this video for some reason. The url on there won't be there forever at 8PM JST(UTC+9) it'll  longer be available for attempted download.

Also wanted to say that i can't find anything about this error online.

**Comment by remitamine** [comment]
![nhk](https://user-images.githubusercontent.com/10879694/35611250-b312faf4-0664-11e8-8475-eed0a34c6f6c.png)
