### ISSUE TITLE
Please add --external-downloader-location PATH

### ISSUE THREAD

**Issue by someziggyman** [rg3/youtube-dl#15464]
It's probably not an issue at all, rather a feature request. 

Noticed, that if I install Axel or Aria2c external downloaders via Brew, downloads are working like a charm, fast and efficient.

However, if I remove it from Brew's packages destination folder ( /usr/local/cellar/axel/..)  and would like to use my own downloader build, youtube-dl uses its default one. 

I understand, that this is expected behavior, but that'd be awesome, if we had an option like **--external-downloader-location PATH**, just like --ffmpeg-location PATH.

If this is an overkill, maybe youtube-dl could also consider looking for external downloader executables, at least with in the same folder and only then proceed to its default downloader..

Or am I missing something and I can somehow achieve this behavior with the latest build? maybe, I could just edit external.py file, but unfortunately my Python knowledge is equal to 0.

**Comment by dstftw** [comment]
You are missing correctly set `$PATH` env variable.
