### ISSUE TITLE
Simultaneous Video+Audio download

### ISSUE THREAD

**Issue by mesibo** [rg3/youtube-dl#15477]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.27*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information
Please add support for simultaneous download of Video+Audio for a video being downloaded. Spawning multiple instances might be complicated in this case as they need to be muxed later amd hence handled by a single instance

**Comment by mesibo** [comment]
Could you point me to duplicate issue so that I can watch it. Thanks

**Comment by IkromjonMamatov** [comment]
Hi dears! I am new in installation on the Mesibo to my own android app so there error is occuring when I try to sync build gradle file with this code: compile 'com.mesibo.api:ui:1.0.0' .  could you please anyone explain why this is hapening?
