### ISSUE TITLE
Remove extractor anitube.se

### ISSUE THREAD

**Issue by ialexsilva** [rg3/youtube-dl#15470]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.27*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### Description of your *issue*, suggested solution and other information

anitube.se has shutdown on 2017

**Comment by dstftw** [comment]
Wrong, was available at least on [23 jan 2018](https://web.archive.org/web/20180123024712/http://www.anitube.se/).

**Comment by lievedido** [comment]
@dstftw isn't it copyright infringing site anyway?
https://www.lumendatabase.org/notices/15779491
https://www.lumendatabase.org/notices/15861098
https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fwww.tecmundo.com.br%2Fanime%2F104664-adeus-anitube-site-ilegal-animes-comprado-servico-sai-brasil.htm&edit-text=&act=url

**Comment by lievedido** [comment]
@dstftw It's probably available in Japan only:
https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fwww.tecmundo.com.br%2Fanime%2F104664-adeus-anitube-site-ilegal-animes-comprado-servico-sai-brasil.htm&edit-text=&act=url
