### ISSUE TITLE
Direct links to vk audio files are not working

### ISSUE THREAD

**Issue by Fanoman** [rg3/youtube-dl#15479]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
youtube-dl -v https://cs1-61v4.vk-cdn.net/p8/685e996ed19024.mp3?extra=HmokStzaR6szuKgDa8ky8ONk6rF2gOHd5dLqaz1DmJLZcJCoYZbz83w-zHH9vrWx8QNT5au-VB-izC9T2-G0E-Mo-SAKSU3A9PjOgk3brG-22lLcVE1i12agVASxpa-n0OS9l2uADG33
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://cs1-61v4.vk-cdn.net/p8/685e996ed19024.mp3?extra=HmokStzaR6szuKgDa8ky8ONk6rF2gOHd5dLqaz1DmJLZcJCoYZbz83w-zHH9vrWx8QNT5au-VB-izC9T2-G0E-Mo-SAKSU3A9PjOgk3brG-22lLcVE1i12agVASxpa-n0OS9l2uADG33']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.27
[debug] Python version 3.6.3 (CPython) - Linux-4.4.0-1049-aws-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: ffmpeg 3.3.4-2, ffprobe 3.3.4-2
[debug] Proxy map: {}
[generic] 685e996ed19024: Requesting header
WARNING: Could not send HEAD request to https://cs1-61v4.vk-cdn.net/p8/685e996ed19024.mp3?extra=HmokStzaR6szuKgDa8ky8ONk6rF2gOHd5dLqaz1DmJLZcJCoYZbz83w-zHH9vrWx8QNT5au-VB-izC9T2-G0E-Mo-SAKSU3A9PjOgk3brG-22lLcVE1i12agVASxpa-n0OS9l2uADG33: HTTP Error 404: Not Found
[generic] 685e996ed19024: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 517, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

I'm receiving an error when I try to use direct link to vk audio. Those links look like this one:
https://cs1-61v4.vk-cdn.net/p8/685e996ed19024.mp3?extra=HmokStzaR6szuKgDa8ky8ONk6rF2gOHd5dLqaz1DmJLZcJCoYZbz83w-zHH9vrWx8QNT5au-VB-izC9T2-G0E-Mo-SAKSU3A9PjOgk3brG-22lLcVE1i12agVASxpa-n0OS9l2uADG33
They are generated for each user personaly when you hit a play button in a broswer and last for some time (maybe few hours), so it might not be valid anymore when somebody will read this message. But I checked It and it is working for anyone (incognito mode, different browsers, vpn). Except youtube-dl.

**Comment by dstftw** [comment]
https://cs1-61v4.vk-cdn.net/p8/685e996ed19024.mp3?extra=HmokStzaR6szuKgDa8ky8ONk6rF2gOHd5dLqaz1DmJLZcJCoYZbz83w-zHH9vrWx8QNT5au-VB-izC9T2-G0E-Mo-SAKSU3A9PjOgk3brG-22lLcVE1i12agVASxpa-n0OS9l2uADG33 is 404 for me.

**Comment by Fanoman** [comment]
@dstftw I found out that it require to be logged in at vk.com. Also for some reason lavaplayer can do it without account.

**Comment by Fanoman** [comment]
@dstftw `wget` also can use those links without any credentials. Cookies or -u and -p doesn't help for youtube-dl.

**Comment by Fanoman** [comment]
This link will work for some time: https://cs1-61v4.vk-cdn.net/p8/5cdcea23d5a6e2.mp3?extra=D_kLXizRCtYdqi8dtYzu6qxU4na-7CuEwJvMQuQmItCi3oDUM-Tc9VKq7F9xsGpla-MGBSuFmDrAs1D-b2nnFDdik8bUVwoc3e92o3xobjTKcNAGDKiqlJNVfIVkuTC4KqdAOLoNXttr

**Comment by dstftw** [comment]
>This link will work for some time: https://cs1-61v4.vk-cdn.net/p8/5cdcea23d5a6e2.mp3?extra=D_kLXizRCtYdqi8dtYzu6qxU4na-7CuEwJvMQuQmItCi3oDUM-Tc9VKq7F9xsGpla-MGBSuFmDrAs1D-b2nnFDdik8bUVwoc3e92o3xobjTKcNAGDKiqlJNVfIVkuTC4KqdAOLoNXttr

404.

**Comment by Fanoman** [comment]
@dstftw try wget

**Comment by dstftw** [comment]
Use wget's user agent then.

**Comment by Fanoman** [comment]
@dstftw Then why VK extractor doesn't work with those links? It just require login and password. VK is supported site and youtube-dl supports usage of login and password.

**Comment by dstftw** [comment]
Cause this link is not a VK extractor link and youtube-dl uses browsers user agent.
