### ISSUE TITLE
[YouTube Playlists] Unable to download full playlist - error "list" is not a recognized command Windows 10

### ISSUE THREAD

**Issue by viNdictBG** [rg3/youtube-dl#15483]
Hey everyone,

Tried to download a YouTube playlist of around 250 videos and it always only downloads the first one:

>youtube-dl --yes-playlist https://www.youtube.com/watch?v=gI3Zn9-tuq8&list=PLC2tuhuSqVt2uAiAZLBE0pD2tQiabZ-5j
[youtube] gI3Zn9-tuq8: Downloading webpage
[youtube] gI3Zn9-tuq8: Downloading video info webpage
[youtube] gI3Zn9-tuq8: Extracting video information
[download] Post Malone - Rockstar ft. 21 Savage (Crankdat Remix)-gI3Zn9-tuq8.mp4 has already been downloaded
[download] 100% of 58.90MiB
'list' is not recognized as an internal or external command,
operable program or batch file.

Any recommendations?

- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.27**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)

youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.01.27
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
