### ISSUE TITLE
So what commant should i use.

### ISSUE THREAD

**Issue by hasnogaems** [rg3/youtube-dl#15482]
For example i have this music track on youtube https://www.youtube.com/watch?v=eYQKEuQV_8s
What command shoould i use to download only audio in mp3 format max quality?
Like what should i add here?:
youtube-dl.exe --ffmpeg-location E:\ffmpeg2\bin https://www.youtube.com/watch?v=eYQKEuQV_8s

**Comment by dstftw** [comment]
`-x --audio-format mp3`.
