### ISSUE TITLE
Dramafever: %(title)s does not include episode number

### ISSUE THREAD

**Issue by GeorgeHamp** [rg3/youtube-dl#15492]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

[debug] User config: ['-o', '%(title)s.%(ext)s', '--all-subs', '--limit-rate', '1M']
[debug] Command-line args: ['http://www.dramafever.com/drama/4044/1/Flower_Boy_Ramen_Shop/?ap=1']
[download] Destination: Flower Boy Ramen Shop.flv

---

Unlike most other streaming services, %(title)s does not include the episode number for series on Dramafever. This causes errors / overwritten files when trying to download series without changing the user-config first.
As the majority of content on this streaming service is serialized, it might be a good idea to include the episode number in %(title)s

The issue may be linked to https://github.com/rg3/youtube-dl/issues/13699
I guess both, series-id and episode-number have been removed following that issue - but the episode-number is usefull ;)

**Comment by dstftw** [comment]
You are using output template without `id` so all bets are off, now you are responsible for naming. `title` is not supposed to be unique. If you want episode number to be included include it on your own.
