### ISSUE TITLE
error in qqmusic.py

### ISSUE THREAD

**Issue by hangitfan** [rg3/youtube-dl#15495]
### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)

### Description of your *issue*, suggested solution and other information

in line 113, the url for requesting vkey seems incorrect, and the response needs to be decoded and get the vkey field.

in line 120, the url 'http://cc.stream.qqmusic.qq.com' for the music file is already unavailable, it should be 'http://dl.stream.qqmusic.qq.com' now.
if what i find is right, can extractor for qqmusic be fixed?  it's not working for now.
if any i can help, pls comment this issue

thanks

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
