### ISSUE TITLE
fox.com download subtitle

### ISSUE THREAD

**Issue by titosalah** [rg3/youtube-dl#15509]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.04**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

C:\youtube>youtube-dl -v "https://www.fox.com/watch/2a7ca0c7488270db9af5f09f7230
8d8a"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.fox.com/watch/2a7ca0c7488270db9af
5f09f72308d8a']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.02.04
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[FOX] 2a7ca0c7488270db9af5f09f72308d8a: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use
 --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-use
rname and --ap-password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpww9373dy\bu
ild\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpww9373dy\bu
ild\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpww9373dy\bu
ild\youtube_dl\extractor\fox.py", line 87, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpww9373dy\bu
ild\youtube_dl\extractor\adobepass.py", line 1409, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpww9373dy\bu
ild\youtube_dl\extractor\adobepass.py", line 1374, in raise_mvpd_required
youtube_dl.utils.ExtractorError: This video is only available for users of parti
cipating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operat
or Identifier and --ap-username and --ap-password or --netrc to provide account
credentials.

### Description of your *issue*, suggested solution and other information
i have problem when download from fox.com i want to download subtitle only 
i have directtv account  and not found directtv in the list
youtube-dl -v "https://www.fox.com/watch/2a7ca0c7488270db9af5f09f72308d8a" --ap-mso

first time use youtube-dl   please can someone tell me how to download videos or subtitles only if supported

thank you very much

**Comment by dstftw** [comment]
It's directv, not direc**t**tv.
