### ISSUE TITLE
fox.com download subtitle tutorial ??

### ISSUE THREAD

**Issue by titosalah** [rg3/youtube-dl#15510]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.04**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

C:\youtube>youtube-dl --verbose https://www.fox.com/watch/2a7ca0c7488270db9af5f0
9f72308d8a/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.fox.com/watch/2a7ca0c74882
70db9af5f09f72308d8a/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.02.04
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[FOX] 2a7ca0c7488270db9af5f09f72308d8a: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use
 --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-use
rname and --ap-password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpww9373dy\bu
ild\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpww9373dy\bu
ild\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpww9373dy\bu
ild\youtube_dl\extractor\fox.py", line 87, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpww9373dy\bu
ild\youtube_dl\extractor\adobepass.py", line 1409, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpww9373dy\bu
ild\youtube_dl\extractor\adobepass.py", line 1374, in raise_mvpd_required
youtube_dl.utils.ExtractorError: This video is only available for users of parti
cipating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operat
or Identifier and --ap-username and --ap-password or --netrc to provide account
credentials.

C:\youtube>youtube-dl --verbose https://www.fox.com/watch/2a7ca0c7488270db9af5f0
9f72308d8a/ ---ap-mso ATTOTT --xxxxxxxx@gmail.com --ap-xxxxxxx --convert-
subs srt
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: ---ap-mso

C:\youtube>youtube-dl --verbose https://www.fox.com/watch/2a7ca0c7488270db9af5f0
9f72308d8a/ ---ap-ATTOTT --xxxxxx@gmail.com --xxxxx --convert-subs
 srt
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: ---ap-ATTOTT

### Description of your *issue*, suggested solution and other information
I don't know how to use  youtube-dl  any one help me please?
i don't know how to use URL 
i want to download subtitle only 
thank you very much

**Comment by dstftw** [comment]
`--ap-mso ATTOTT --ap-username <USERNAME_HERE> --ap-password <PASSWORD_HERE> --write-subs`.

**Comment by titosalah** [comment]
@dstftw please can you give all link when i use this 
youtube-dl https://www.fox.com/watch/2a7ca0c7488270db9af5f09f72308d8a --ap-mso ATTOTT --ap-username xxxxxxx@gmail.com --ap-password xxxxx --write-subs
this message appeared 
Usage: youtube-dl [OPTIONS] URL [URL...]
youtube-dl: error: no such option: --write-subs

iam very sorry to disturb you
but i don't know how to use this app 
thank you
