### ISSUE TITLE
duplicate metadata files created when using output params based on video format

### ISSUE THREAD

**Issue by mariomadproductions** [rg3/youtube-dl#15517]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.04**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

When I use ``youtube-dl --write-info-json --write-description --write-thumbnail --write-annotations --all-subs --all-formats -o %(title)s-%(id)s/%(title)s-%(id)s-%(format_id)s.%(ext)s https://www.youtube.com/watch?v=PRjzqc2l6Yw`` it creates the metadata files (description, thumbnail etc) for each format, even though those things don't differ between video formats.

Here is a (possibly not very good) solution: Have a (option for) a separate, metadata-only, output parameter.
Example usage (``-ov`` = output for video, ``-om`` = output for metadata):
``youtube-dl --write-info-json --write-description --write-thumbnail --write-annotations --all-subs -- --all-formats -ov %(title)s-%(id)s/%(title)s-%(id)s-%(format_id)s.%(ext)s -om %(title)s-%(id)s/%(title)s-%(id)s.%(ext)s https://www.youtube.com/watch?v=PRjzqc2l6Yw``

**Comment by dstftw** [comment]
This is expected behavior. If you don't want metadata to be written for each format don't request it in the same run.

**Comment by mariomadproductions** [comment]
It was pretty stupid of me that I didn't think of that.
