### ISSUE TITLE
ERROR: fixed output name but more than one file to download

### ISSUE THREAD

**Issue by rajucomp** [rg3/youtube-dl#15513]
I am trying to run the following command in bash.
`youtube-dl -v --get-filename -o NZ Falter in Chase, Pak Win Series.\%\(ext\)s http://www.hotstar.com/sports/cricket/series/nz-falter-in-chase-pak-win-series/2001608324`

But I am getting the error
`ERROR: fixed output name but more than one file to download`

Here is the complete log :- 
`youtube-dl -v --get-filename -o NZ Falter in Chase, Pak Win Series.\%\(ext\)s http://www.hotstar.com/sports/cricket/series/nz-falter-in-chase-pak-win-series/2001608324`
`[debug] System config: []`
`[debug] User config: []`
`[debug] Custom config: []`
`[debug] Command-line args: [u'-v', u'--get-filename', u'-o', u'NZ', u'Falter', u'in', u'Chase,', u'Pak', u'Win', u'Series.%(ext)s', u'http://www.hotstar.com/sports/cricket/series/nz-falter-in-chase-pak-win-series/2001608324']  `
`[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8`
`[debug] youtube-dl version 2018.02.04`
`[debug] Python version 2.7.12 (CPython) - Linux-4.13.0-32-generic-x86_64-with-Ubuntu-16.04-xenial`
`[debug] exe versions: ffmpeg N-89948-ge3d946b3f4-static, ffprobe N-89948-ge3d946b3f4-static`
`[debug] Proxy map: {}`
`ERROR: fixed output name but more than one file to download`

**Comment by dstftw** [comment]
Output template expression with whtespace must be enclosed in quotes.
