### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by ahm786** [rg3/youtube-dl#15524]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

### Description of your *issue*, suggested solution and other information

Hi,

I've been using youtube-dl for a while. One thing that I've noticed is that whenever I execute it either via command line or a python script, the CPU usage spikes to 90-100%. I check the CPU usage via 'htop' command. If I execute multiple instances of the script, then it freezes the server.

This happens with all videos, whether it be YouTube, Instagram, DailyMotion, or any other platform. The CPU usage always goes to around 90-100% before it drops to 0% once the script finishes executing.

Any way to fix this issue? Or why it's happening?

**Comment by dstftw** [comment]
Provide verbose logs that **clearly** demonstrate the problem. Provide the output of `top`.
