### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by ahm786** [rg3/youtube-dl#15523]
Hi,

I've been using youtube-dl for a while, but one thing that I noticed recently is that whenever I execute it either via command line or a python script, the CPU usage spikes to 100%. If I execute multiple instances of the script, then it freezes the server.

Any way to fix this issue? Or why it's happening?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
