### ISSUE TITLE
francetvinfo.fr : not supported ?

### ISSUE THREAD

**Issue by skramm** [rg3/youtube-dl#15534]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.08**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.francetvinfo.fr/replay-magazine/france-2/envoye-special/envoye-special-du-jeudi-8-fevrier-2018_2589744.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.08
[debug] Python version 2.7.6 (CPython) - Linux-3.13.0-141-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[francetvinfo.fr] envoye-special-du-jeudi-8-fevrier-2018_2589744: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol> (caused by URLError(SSLError(1, '_ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 519, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2199, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1089, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
```

---

### Description of your *issue*, suggested solution and other information

Trying to download from https://www.francetvinfo.fr/
Failure, with error message:
```
ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol> (caused by URLError(SSLError(1, '_ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol'),))
```

This "could" be related with  other (now closed) issues: #14827 , #14947 , although the error is not the same.

FWIW, it is unclear if the site is supported on list:
https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md
 - culturebox.francetvinfo.fr : is listed
 - francetvinfo.fr : is not listed

So ? Does this mean the latter one not supported ?

**Comment by dstftw** [comment]
Most likely due to outdated python.

**Comment by skramm** [comment]
Thanks. What is the required Python version ?
Because here:
https://github.com/rg3/youtube-dl#description
it says:
> It requires the Python interpreter, version 2.6, 2.7, or 3.2+
and I see in the log that it uses 2.7.

and I have:

    $python --version
    Python 3.4.3
    $ python2 --version
    Python 2.7.6

Any hint ?

**Comment by dstftw** [comment]
youtube-dl works with any aforementioned version. Some SSL features may not be available in older versions though.

**Comment by skramm** [comment]
I'm not a python guy, so I'm not sure I understand. Do you mean it's my SSL python library that's outdated? I checked this (with default Python shell, 2.7):

    >>> import ssl
    >>> ssl.OPENSSL_VERSION
    'OpenSSL 1.0.1f 6 Jan 2014'

Sure, looks pretty old, but...is it really that the faulty part ?
Because updating openssl seems tedious (="build from sources" only, AFAIK)

More generally, is there a way with youtube-dl to know and/or to enforce the required version of the used libraries? That could help in this kind of situations...

**Comment by skramm** [comment]
Any help ? Because currently youtube-dl is **not working** (on **my** machine), @dstftw has closed this issue, and I have no real clue on what to do next... I have the latest release, so how I am supposed to know what's not working ?
