### ISSUE TITLE
Could QUIC be used for faster downloading of videos ?

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#15530]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

This is more of a query/question than any functionality. I was reading https://lwn.net/Articles/745590/. Could quic in someway also help us to download videos faster than costly TCP/IP . 

---

**Comment by dstftw** [comment]
Maybe but not significantly. Needless to say remote webserver must support it for this at least to happen.
