### ISSUE TITLE
HTTP Error 500 at investigationdiscovery.com

### ISSUE THREAD

**Issue by seabeast51** [rg3/youtube-dl#15542]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
C:\Users\Desktop\youtube-dl>youtube-dl --verbose https://www.investigati
ondiscovery.com/tv-shows/who-killed-jane-doe/full-episodes/her-whispering-bones
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.investigationdiscovery.com
/tv-shows/who-killed-jane-doe/full-episodes/her-whispering-bones']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.02.08
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Discovery] her-whispering-bones: Downloading webpage
[Discovery] her-whispering-bones: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (
caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make
 sure you are using the latest version; type  youtube-dl -U  to update. Be sure
to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn4uo9muj\bu
ild\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn4uo9muj\bu
ild\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt
...
<end of log>
```

---

- Single video: https://www.investigationdiscovery.com
/tv-shows/who-killed-jane-doe/full-episodes/her-whispering-bones

---

The website does not require a login for this video, but does for others. Searching on the [supported site list](https://rg3.github.io/youtube-dl/supportedsites.html) , Discovery is on there, but not Investigation Discovery.

**Comment by dstftw** [comment]
![image](https://user-images.githubusercontent.com/1908898/36040016-c921ebc2-0df6-11e8-888c-b8836d42e6e4.png)

**Comment by seabeast51** [comment]
I'm not sure how you got that message. I have tried different computers and different browsers that are not logged in to any subscription services.

**Comment by seabeast51** [comment]
Hello,

I'm not sure if you'll get this or if you saw my initial reply because the
topic was closed, but I am not seeing the same error as you. I'm not sure
how you got that message. I have tried different computers and different
browsers that are not logged in to any subscription services. Can you tell
me how to replicate? Possibly an ISP thing?

*Cameron Best*
cameronjbest@gmail.com
