### ISSUE TITLE
Problem with filesize

### ISSUE THREAD

**Issue by z529419** [rg3/youtube-dl#15550]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

First of all thanks for the help and congrats for the wonderful app.

Now i have lastest version in the app and i cant solve my problem.

Im backing up some courses from Safari Books Online before my expiration account, some files are extremly big and i need automatic quality selection. I tried using -f "[filesize<=?100M]" but still choosing the best option (300Mb+).  In the process i notice in json file, filesize it is nowhere, probably thats the problem. I tried using --match-filter 'filesize_approx' but i failed again.

I need 2 thing.
- Download only one video in the list only if the filesize is less than 100Mb
- That file needs to be native mp4, because muxing video+audio create problems in the file.

```
--- SOME OUTPUTS ---
+>youtube-dl -u "**********" -p "***********" -F -a links.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-F', '-a', 'links.txt', '--verbose']
[debug] Batch file urls: ['https://www.safaribooksonline.com/library/view/ccna-security-210-260/9780134400631/CCNA_00_00_00.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.02.08
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[safari] Downloading login form
[safari] Logging in
[safari] 9780134400631/CCNA_00_00_00: Downloading webpage
[safari] 9780134400631/CCNA_00_00_00: Downloading kaltura session JSON
[Kaltura] 9780134400631-CCNA_00_00_00: Downloading webpage
[Kaltura] 0_sgbwfbde: Downloading video info JSON
[Kaltura] 0_sgbwfbde: Downloading m3u8 information
[info] Available formats for 0_sgbwfbde:
format code  extension  resolution note
mp4-56       mp4        audio only   56k , isom container, 0fps, ~2.42MiB
hls-58       mp4        audio only   58k , mp4a.40.2
mp4-472      mp4        640x360     472k , isom container, avc1, 30fps, ~20.20MiB
hls-516      mp4        640x360     516k
mp4-670      mp4        640x360     670k , isom container, avc1, 30fps, ~28.70MiB
hls-723      mp4        640x360     723k
mp4-966      mp4        640x360     966k , isom container, avc1, 30fps, ~41.40MiB
hls-1033     mp4        640x360    1033k
mp4-1628     mp4        1280x720   1628k , isom container, avc1, 30fps, ~68.40MiB
hls-1725     mp4        1280x720   1725k
mp4-2628     mp4        1280x720   2628k , isom container, avc1, 30fps, ~112.00MiB
mp4-4128     mp4        1280x720   4128k , isom container, avc1, 30fps, ~176.00MiB
mp4-9005     mp4        1280x720   9005k , isom container, avc1, 30fps, ~386.00MiB (best)

```
I think the biggest mistake is... me, i hope you can help me.

Thanks again.

**Comment by dstftw** [comment]
`-f "[filesize_approx<=100M][ext=mp4]"` in the next version.
