### ISSUE TITLE
Leading zero in OUTPUT TEMPLATE

### ISSUE THREAD

**Issue by Sopor-** [rg3/youtube-dl#15552]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

When i download i want the season and episode have a leading zero instead of only a single number. I use the template `s%(season_number)se%(episode_number)s` and i can't find anything that will make it use two numbers 01, 02, 03 and i don't want to add it manually because that will make it hard to check for every download if there should be a leading 0 or not.
I'm new to youtube-dl so maybe i have missed something?

**Comment by dstftw** [comment]
Read [FAQ](https://github.com/rg3/youtube-dl/blob/master/README.md#output-template)?
>The special sequences may be formatted according to [python string formatting operations](https://docs.python.org/2/library/stdtypes.html#string-formatting). For example, `%(NAME)s` or `%(NAME)05d`

**Comment by Sopor-** [comment]
I have no idea how that works, but thanks for your help @dstftw...

**Comment by Hrxn** [comment]
`S%(season_number)05d` vs. `S%(season_number)s` for example...

**Comment by w7guru** [comment]
Thanks, I don't have to rename my files anymore after download.
`-o '%(series)s - S0%(season_number)sE0%(episode_number)s - %(title)s.%(ext)s"`
With above I was getting S0E01,SE02 (OK) but S01E010, S01E011 (NOK)
`'%(series)s - S%(season_number)**02d**E%(episode_number)**02d** - %(episode)s.%(ext)s'`
I get _"ShowName - S01E01 - BlaBlaBla.mp4"_

also tried 03d,04d

Tested:
```
>>> print '%(language)s has %(number)02d quote types.' % \
... {"language": "Python", "number": 2}
Python has 02 quote types.
```

```
>>> print '%(language)s has %(number)03d quote types.' % \
... {"language": "Python", "number": 2}
Python has 002 quote types.
```

```
>>> print '%(language)s has %(number)05d quote types.' % \
... {"language": "Python", "number": 2}
Python has 00002 quote types.
```
