### ISSUE TITLE
[Windows] output template: unsupported format character '/'

### ISSUE THREAD

**Issue by bato3** [rg3/youtube-dl#15559]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
C:\Users\jontek>youtube-dl -o "%(extractor)s/%(id).3/%(id)s-%(height)s.%(ext)s" http://openload.co/embed/f_rLF3gB15A/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '%(extractor)s/%(id).3/%(id)s-%(height)s.%(ext)s', 'http://openload.co/embed/f_rLF3gB15A/', '--verbose']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2018.02.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[Openload] f_rLF3gB15A: Downloading embed webpage
[Openload] f_rLF3gB15A: Executing JS on webpage
[debug] Default format spec: best/bestvideo+bestaudio
ERROR: Error in output template: unsupported format character '/' (0x2f) at index 21 (encoding: 'cp1250')
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn4uo9muj\build\youtube_dl\YoutubeDL.py", line 699, in prepare_filename
ValueError: unsupported format character '/' (0x2f) at index 21
```

---

I want to organize files in directories by the structure: extractor / part-of-id / id.

Of course, catalogs are not created before.

Command `youtube-dl -o "%(id).3s%(extractor)s-%(id)s-%(height)s.%(ext)s" http://openload.co/embed/f_rLF3gB15A/` generate correct name, but save file in current directory.

encoding: 'cp1250' - this is for Polish.

**Comment by dstftw** [comment]
>%(id).3

Incorrect.

**Comment by bato3** [comment]
Correct

```
C:\Users\jontek\tmp>youtube-dl -o "%(id).3s%(extractor)s-%(id)s-%(height)s.%(ext)s" http://openload.co/embed/f_rLF3gB15A/
[Openload] f_rLF3gB15A: Downloading embed webpage
[Openload] f_rLF3gB15A: Executing JS on webpage
[download] Destination: f_rOpenload-f_rLF3gB15A-NA.mp4
[download]   0.4% of 267.09MiB at  1.26MiB/s ETA 03:30
ERROR: Interrupted by user

C:\Users\jontek\tmp>dir
10.02.2018  22:25         1 047 552 f_rOpenload-f_rLF3gB15A-NA.mp4.part
```

**Comment by bato3** [comment]
eh... should be `%(id).3s`
