### ISSUE TITLE
new errors in output template

### ISSUE THREAD

**Issue by rmlrml** [rg3/youtube-dl#15562]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.08**
```
ryan@pocketwee:~$ /usr/local/bin/youtube-dl --version
2018.02.08
```
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

```
ryan@pocketwee:~$ /usr/local/bin/youtube-dl -v -f 251 -x --yes-playlist -o '/home/ryan/Downloads/%(playlist)/%(playlist_index) %(title).%(ext)' https://www.youtube.com/playlist?list=PLSGc8WaREMByawTmBy9qnEpIhpLs1wuLR
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'251', u'-x', u'--yes-playlist', u'-o', u'/home/ryan/Downloads/%(playlist)/%(playlist_index) %(title).%(ext)', u'https://www.youtube.com/playlist?list=PLSGc8WaREMByawTmBy9qnEpIhpLs1wuLR']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.08
[debug] Python version 2.7.14+ (CPython) - Linux-4.14.0-3-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.4.1-1, ffprobe 3.4.1-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLSGc8WaREMByawTmBy9qnEpIhpLs1wuLR: Downloading webpage
[download] Downloading playlist: I Am An Elastic Firecracker
[youtube:playlist] playlist I Am An Elastic Firecracker: Downloading 12 videos
[download] Downloading video 1 of 12
[youtube] K6lOtZdadpI: Downloading webpage
[youtube] K6lOtZdadpI: Downloading video info webpage
[youtube] K6lOtZdadpI: Extracting video information
[youtube] {22} signature length 40.40, html5 player vflG9lb96
[youtube] {43} signature length 40.40, html5 player vflG9lb96
[youtube] {18} signature length 38.40, html5 player vflG9lb96
[youtube] {36} signature length 40.40, html5 player vflG9lb96
[youtube] {17} signature length 40.40, html5 player vflG9lb96
[youtube] {137} signature length 40.40, html5 player vflG9lb96
[youtube] {248} signature length 40.40, html5 player vflG9lb96
[youtube] {136} signature length 40.40, html5 player vflG9lb96
[youtube] {247} signature length 40.40, html5 player vflG9lb96
[youtube] {135} signature length 40.40, html5 player vflG9lb96
[youtube] {244} signature length 40.40, html5 player vflG9lb96
[youtube] {134} signature length 40.40, html5 player vflG9lb96
[youtube] {243} signature length 40.40, html5 player vflG9lb96
[youtube] {133} signature length 40.40, html5 player vflG9lb96
[youtube] {242} signature length 40.38, html5 player vflG9lb96
[youtube] {160} signature length 40.40, html5 player vflG9lb96
[youtube] {278} signature length 40.40, html5 player vflG9lb96
[youtube] {140} signature length 40.40, html5 player vflG9lb96
[youtube] {171} signature length 40.40, html5 player vflG9lb96
[youtube] {249} signature length 40.40, html5 player vflG9lb96
[youtube] {250} signature length 40.40, html5 player vflG9lb96
[youtube] {251} signature length 40.40, html5 player vflG9lb96
ERROR: Error in output template: unsupported format character '/' (0x2f) at index 32 (encoding: 'UTF-8')
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 699, in prepare_filename
    filename = expand_path(outtmpl).replace(sep, '') % template_dict
ValueError: unsupported format character '/' (0x2f) at index 32

...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

The output template format:
`-o '/home/ryan/Downloads/%(playlist)/%(playlist_index) %(title).%(ext)'`
used to work fine.

Haven't used youtube-dl in a while, a couple months maybe.  Haven't changed the format I use.  In fact I had the format saved to copy-paste it when I want it.  Now it errors:
`Error in output template: unsupported format character '/' (0x2f) at index 32 (encoding: 'UTF-8')`

I also tried just:
`-o '%(playlist_index) %(title).%(ext)'`
and I get:
`ERROR: Error in output template: incomplete format (encoding: 'UTF-8')`

**Comment by dstftw** [comment]
Incorrect output template, you are missing a conversion type for each sequence.

**Comment by rmlrml** [comment]
Help please?  I don't understand the difference between 'd' and 'i'.  They're both [described as](https://docs.python.org/2/library/stdtypes.html#string-formatting) "Signed integer decimal" with no note.

Also why did it used to work without me ever adding this part?

**Comment by dstftw** [comment]
There is no difference.
It **never** worked without conversion type.

**Comment by rmlrml** [comment]
Right, thanks so much for not helping, and for lying to me about the way I've been doing it forever.  Hey maybe you'll delete this comment too, or maybe the whole issue!  Good job.

**Comment by dstftw** [comment]
Not helping? What a hypocrite. And again: it never worked this way. Prove me wrong. Bother to grab some old youtube-dl version and provide verbose log of these command working.

**Comment by rmlrml** [comment]
Right.  

Good job not knowing what "hypocrite" means.  When did you ask me for help, for which my not providing you with said help had rendered me a hypocrite?  Never.

I have always had the ytdl command and arguments above as one of my options in my Open With addon.  Any time I wanted to download a playlist, I just right-clicked anywhere on the page or tab, or on a link to the playlist, sent it to OW which sent it to ytdl and it always worked perfectly.   Always downloaded full playlists.

I'm literally sitting here right now learning about python conversion types which I've **never used before**, but no, the conversion types must have always been there, because as you say "it never worked" without them.  I guess they must have been inserted on-the-fly by OW.  What a smart addon!  But I guess it must have stopped inserting them on the fly and so now I have to insert them manually.

**Comment by dstftw** [comment]
Then go and complain to OW addon. This is youtube-dl issue tracker not OW or whatever else 3rdparty stuff. I really don't care whether you used before it or not, the fact is that it's in youtube-dl from the beginning and it's the only way to use it.
