### ISSUE TITLE
youtube-dl lacks an easy way download 4K UHD formats with sound and convert to mp4

### ISSUE THREAD

**Issue by finnianr** [rg3/youtube-dl#15593]
**A Better -best**
It seems the -best option only selects streams which include both the video and sound in one container. However most UHD 4K is in a video only stream. If you want to watch 4K you have to merge it with the a separately downloaded sound stream. Also the youtube 4K format is more often than not webm, which is not very portable. Playstation consoles for example, cannot play it. It would be nice to have automatic conversion to mp4.
To solve this problem I created a utility wrapper for youtube-dl with the Eiffel programming language. See this article: https://groups.google.com/forum/#!topic/eiffel-users/DZHqE7EO3Ww
The nice thing about my tool is it very simple to use and just does this one thing well. 

It would would be nice to see the youtube-dl development team making my utility redundant by improving youtube-dl. Or perhaps there is already a way to achieve what my utility does but I just didn't realise it?

**Comment by dstftw** [comment]
youtube-dl does this by default out of the box if ffmpeg is installed.

**Comment by finnianr** [comment]
Can you please offer an example of how it works. I have ffmpeg installed.

**Comment by dstftw** [comment]
`youtube-dl URL`.

**Comment by finnianr** [comment]
Really! I will give it a try.

**Comment by finnianr** [comment]
Well I am sorry but this does not work on my machine and I have recently did an update of youtube-dl. This example only downloaded the resolution 1280 x 676 mp4. No 4K video. Is this because for some reason youtube-dl has failed to detect that I have ffmpeg installed.
```
finnian@MacMini ~/Videos $ youtube-dl https://www.youtube.com/watch?v=B_nutbvGX8M 
[youtube] B_nutbvGX8M: Downloading webpage
[youtube] B_nutbvGX8M: Downloading video info webpage
[youtube] B_nutbvGX8M: Extracting video information
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[download] Destination: Taichi Wakita at Pipeline, Jan 23rd, 2018-B_nutbvGX8M.mp4
[download] 100% of 6.89MiB in 00:16
```

**Comment by finnianr** [comment]
Here is my configuration
```
finnian@MacMini ~/Videos $ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.08
[debug] Python version 2.7.6 (CPython) - Linux-3.13.0-141-generic-x86_64-with-LinuxMint-17-qiana
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}

```

**Comment by dstftw** [comment]
>WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.

**Comment by dstftw** [comment]
Remove avconv from `$PATH` or use `--prefer-ffmpeg`.

**Comment by finnianr** [comment]
Ok lets give that a go.

**Comment by finnianr** [comment]
I tried it but it only partially solves my problem. It does download the best 4K version and adds sound, but the V9 codec is not very portable. I won't be able to play it on my Playstation. Is there an easy way to make it re-encode with H.26x and make the container mp4?

**Comment by dstftw** [comment]
`--recode-video`.

**Comment by finnianr** [comment]
Thanks! will try later. Gotta go now.

**Comment by avagraha** [comment]
Finniarn did you successfully use recode video for your link? I filed with zero warnings. Very strange

**Comment by finnianr** [comment]
I found it easier to let my wrapper program call ffmpeg than trying to use --recode-video which I found intimidating. I didn't waste much time trying to figure it out. Now my wrapper uses an interactive an menu to first display the audio options and then the video options (sorted in reverse width resolution). After selecting each stream, they are downloaded and then merged by a call to ffmpeg. I have also made it possible to drag and drop a url on to the console window. From a user point of view it is a whole lot more friendly than using youtube-dl directly.

**Comment by avagraha** [comment]
With 4k VP9 / 9.2 webm I simply use
--merge-output mkv
Mkv is very very portable, even for my old Oppo 2009!

[If required I add  -f 315+251]. All is fine.


  ----- Original Message -----

**Comment by joonas-fi** [comment]
I installed ffmpeg, and still not getting 4k downloads. Using https://github.com/wernight/docker-youtube-dl fixed the issue. There is deep UX problems with youtube-dl if even strolling through the numerous "not able to download 4k content" GitHub issues is enough to help me get it working - and I'm a software engineer.

**Comment by phubbard** [comment]
Workaround that worked for me - MacOS catalina, Homebrew install - if I `brew install ffmpeg` then I get 4K (webm) downloads.
