### ISSUE TITLE
Multiple URLS not working the recently added stream.nbcolympics.com feature

### ISSUE THREAD

**Issue by Tomoyochan** [rg3/youtube-dl#15595]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.11**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.02.11
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://stream.nbcolympics.com/figure-skating-team-event-mens-short-program-pairs-short-program', '--verbose', '--ap-mso', 'goldenwest', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-90054-g474194a8d0
[debug] Proxy map: {}
[nbcolympics:stream] figure-skating-team-event-mens-short-program-pairs-short-program: Downloading webpage
[nbcolympics:stream] 200267: Downloading JSON metadata
[nbcolympics:stream] 200267: Downloading JSON metadata
[nbcolympics:stream] 200267: Retrieving Authorization Token
ERROR: A network error occured when communicating with the provider's authorization service
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\nbc.py", line 434, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\adobepass.py", line 1545, in _extract_mvpd_auth
youtube_dl.utils.ExtractorError: A network error occured when communicating with the provider's authorization service

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://stream.nbcolympics.com/figure-skating-training-men-feb-10', '--verbose', '--ap-mso', 'goldenwest', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-90054-g474194a8d0
[debug] Proxy map: {}
[nbcolympics:stream] figure-skating-training-men-feb-10: Downloading webpage
[nbcolympics:stream] 204155: Downloading JSON metadata
[nbcolympics:stream] 204155: Downloading JSON metadata
[nbcolympics:stream] 204155: Retrieving Authorization Token
[nbcolympics:stream] 204155: Retrieving Media Token
[nbcolympics:stream] 204155: Downloading webpage
[nbcolympics:stream] 204155: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://stream.nbcolympics.com/medal-ceremony-day-2', '--verbose', '--ap-mso', 'goldenwest', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-90054-g474194a8d0
[debug] Proxy map: {}
[nbcolympics:stream] medal-ceremony-day-2: Downloading webpage
[nbcolympics:stream] 200333: Downloading JSON metadata
[nbcolympics:stream] 200333: Downloading JSON metadata
[nbcolympics:stream] 200333: Retrieving Media Token
[nbcolympics:stream] 200333: Downloading webpage
[nbcolympics:stream] 200333: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default


[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://stream.nbcolympics.com/skeleton-men-training', '--verbose', '--ap-mso', 'goldenwest', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-90054-g474194a8d0
[debug] Proxy map: {}
[nbcolympics:stream] skeleton-men-training: Downloading webpage
[nbcolympics:stream] 203472: Downloading JSON metadata
[nbcolympics:stream] 203472: Downloading JSON metadata
[nbcolympics:stream] 203472: Retrieving Media Token
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://stream.nbcolympics.com/figure-skating-team-event-mens-free-skate-ladies-free-skate-ice-dance-free-dance', '--verbose', '--ap-mso', 'goldenwest', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-90054-g474194a8d0
[debug] Proxy map: {}
[nbcolympics:stream] figure-skating-team-event-mens-free-skate-ladies-free-skate-ice-dance-free-dance: Downloading webpage
[nbcolympics:stream] 200405: Downloading JSON metadata
[nbcolympics:stream] 200405: Downloading JSON metadata
[nbcolympics:stream] 200405: Retrieving Authorization Token
ERROR: A network error occured when communicating with the provider's authorization service
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\nbc.py", line 434, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\adobepass.py", line 1545, in _extract_mvpd_auth
youtube_dl.utils.ExtractorError: A network error occured when communicating with the provider's authorization service

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://stream.nbcolympics.com/figure-skating-team-event-mens-free-skate-ladies-free-skate-ice-dance-free-dance-standard', '--verbose', '--ap-mso', 'goldenwest', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-90054-g474194a8d0
[debug] Proxy map: {}
[nbcolympics:stream] figure-skating-team-event-mens-free-skate-ladies-free-skate-ice-dance-free-dance-standard: Downloading webpage
[nbcolympics:stream] 204129: Downloading JSON metadata
[nbcolympics:stream] 204129: Downloading JSON metadata
[nbcolympics:stream] 204129: Retrieving Authorization Token
ERROR: A network error occured when communicating with the provider's authorization service
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\nbc.py", line 434, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\adobepass.py", line 1545, in _extract_mvpd_auth
youtube_dl.utils.ExtractorError: A network error occured when communicating with the provider's authorization service

```

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I have been downloading quite a few of the files without issues however some of the URLS come back reporting the above errors.  I have tried multiple times and nothing I do can make these URLS download.  They play just fine in my web browser of choice (Firefox).  I expect to find more as Figure skating seems to be a major offender of the issue.

**Comment by Tomoyochan** [comment]
Is there more information needed for this issue to be looked at?  I do apologize if I missed anything that you guys need.

**Comment by sa7mon** [comment]
Make sure to include the actual commands you ran when you got those outputs

**Comment by Tomoyochan** [comment]
The information is in the debug output:
[debug] Command-line args: ['http://stream.nbcolympics.com/figure-skating-team-event-mens-free-skate-ladies-free-skate-ice-dance-free-dance', '--verbose', '--ap-mso', 'goldenwest', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']

Or as I put it in:
youtube-dl.exe "http://stream.nbcolympics.com/figure-skating-team-event-mens-free-skate-ladies-free-skate-ice-dance-free-dance" --verbose --ap-mso goldenwest --ap-username "*****" --ap-password "****" 

If you are asking for my username and password to be submitted to a public bug report I am not in a position to provide that.

**Comment by Tomoyochan** [comment]
These are the final 23 that are are still not downloading with the current version.
[Download-1.log](https://github.com/rg3/youtube-dl/files/1845825/Download-1.log)
[Download-2.log](https://github.com/rg3/youtube-dl/files/1845826/Download-2.log)
[Download-3.log](https://github.com/rg3/youtube-dl/files/1845827/Download-3.log)
[Download-4.log](https://github.com/rg3/youtube-dl/files/1845828/Download-4.log)
[Download-5.log](https://github.com/rg3/youtube-dl/files/1845829/Download-5.log)
[Download-6.log](https://github.com/rg3/youtube-dl/files/1845830/Download-6.log)
[Download-7.log](https://github.com/rg3/youtube-dl/files/1845808/Download-7.log)
[Download-8.log](https://github.com/rg3/youtube-dl/files/1845809/Download-8.log)
[Download-11.log](https://github.com/rg3/youtube-dl/files/1845810/Download-11.log)
[Download-13.log](https://github.com/rg3/youtube-dl/files/1845811/Download-13.log)
[Download-14.log](https://github.com/rg3/youtube-dl/files/1845812/Download-14.log)
[Download-15.log](https://github.com/rg3/youtube-dl/files/1845813/Download-15.log)
[Download-16.log](https://github.com/rg3/youtube-dl/files/1845814/Download-16.log)
[Download-17.log](https://github.com/rg3/youtube-dl/files/1845815/Download-17.log)
[Download-18.log](https://github.com/rg3/youtube-dl/files/1845816/Download-18.log)
[Download-19.log](https://github.com/rg3/youtube-dl/files/1845817/Download-19.log)
[Download-20.log](https://github.com/rg3/youtube-dl/files/1845818/Download-20.log)
[Download-21.log](https://github.com/rg3/youtube-dl/files/1845819/Download-21.log)
[Download-22.log](https://github.com/rg3/youtube-dl/files/1845820/Download-22.log)
[Download-23.log](https://github.com/rg3/youtube-dl/files/1845821/Download-23.log)
[Download-24.log](https://github.com/rg3/youtube-dl/files/1845822/Download-24.log)
[Download-25.log](https://github.com/rg3/youtube-dl/files/1845823/Download-25.log)
[Download-26.log](https://github.com/rg3/youtube-dl/files/1845824/Download-26.log)

**Comment by Tomoyochan** [comment]
Now that I have been able to get all the working ones down I have started to dig into why these are not working myself a bit.  IT seems that something is not getting parsed right.  As on the actual viewer in my browser I get 
[live_sources_204022-Browser.json.txt](https://github.com/rg3/youtube-dl/files/1849429/live_sources_204022-Browser.json.txt)
Youtubedl gets:
[200267_http_-_stream.nbcolympics.com_data_live_sources_200267.json.dump.txt](https://github.com/rg3/youtube-dl/files/1849434/200267_http_-_stream.nbcolympics.com_data_live_sources_200267.json.dump.txt)


The biggest issue I see is that the youtubedl live-sources contain expired sources while the browsers contains ones listed as replay.  Trying to see if I can figure out where youtubedl is getting it's links from.

**Comment by Tomoyochan** [comment]
Ohh, jeez.  I think I found the issue.  
NBC is redirecting to http://stream.nbcolympics.com/figure-skating-team-event-mens-short-program-pairs-short-program?pid=204022&nid=200267_493

However, that is not changing the pid that is in the downloaded file, only the pid that the player itself uses.  I am going to continue digging to see if there is a way I can get youtube-dl to respect the pid after the ? in the url.

**Comment by Tomoyochan** [comment]
I fear I may have hit the limits of what I can find as I do not actually understand how the adobe MSO functionality is working in Youtube-DL to further reverse the problem.

What I know:
The webbrowser uses cookies for the entire auth process and does not send the same requests that I am seeing sent by youtube-DL.  This makes it impossible to triage what exact step is failing in youtube-DL or what information exactly is mismatched.

NBC is doing about 3 redirects from what I see in the browser until the real feed, PID 204022 shows up.

Manually setting PID to 204022 works for all steps except the final one when the auth is requested. My suspicion is that the resource variable is mismatched from what adobe is expecting for the feed.  

I will continue to dig, however if someone can give a bit more insight I would appreciate it.

**Comment by Tomoyochan** [comment]
I am going to close this issue as NBCOlympics are actively removing videos and any that I do not have already or download via a second means are gone. Hopefully this bug does not show up at a future olympics, But knowing NBC.............
