### ISSUE TITLE
Error while downloading from Facebook

### ISSUE THREAD

**Issue by mayasl** [rg3/youtube-dl#15604]
-->youtube-dl -o taxi.mp4 --no-check-certificate --verbose https://www.facebook.com/mana.careem/posts/1892927907416475
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-o', u'taxi.mp4', u'--no-check-certificate', u'--verbose', u'https://www.facebook.com/mana.careem/posts/1892927907416475']
[debug] Encodings: locale UTF-8, fs None, out None, pref UTF-8
[debug] youtube-dl version 2018.02.11
[debug] Python version 2.7.12 (CPython) - Linux-3.10.20-x86_64_moor-265516-g6c01645-armv7l-with-libc
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 1892927907416475: Downloading webpage
ERROR: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/youtube_dl-2018.02.11-py2.7.egg/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/youtube_dl-2018.02.11-py2.7.egg/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/youtube_dl-2018.02.11-py2.7.egg/youtube_dl/extractor/facebook.py", line 415, in _real_extract
    webpage, 'video ids', group='ids'),
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/youtube_dl-2018.02.11-py2.7.egg/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
![image](https://user-images.githubusercontent.com/1908898/36214085-16d74118-11db-11e8-990a-e68e13419226.png)

**Comment by mayasl** [comment]
It is sad that you didn't have a solution for my issue. Anyway, I fixed it and downloaded the video I wanted to download.

**Comment by dstftw** [comment]
There is no issue. You did not pass account credentials to youtube-dl in any supported form.

**Comment by mayasl** [comment]
I was able to download that particular video without passing my account credentials. So it wasn't about the credential. Anyway, thank you.
