### ISSUE TITLE
Can't download 720p videos on Vimeo

### ISSUE THREAD

**Issue by panhartstuff** [rg3/youtube-dl#15611]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v -F https://vimeo.com/142820366
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://vimeo.com/142820366']
[debug] Encodings: locale cp932, fs utf-8, out utf-8, pref cp932
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.6.3 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg 3.4, ffprobe N-89471-g88e2dc7d04
[debug] Proxy map: {}
[vimeo] 142820366: Downloading webpage
[vimeo] 142820366: Extracting information
[vimeo] 142820366: Downloading webpage
[vimeo] 142820366: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 142820366: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 142820366: Downloading fastly_skyfire m3u8 information
[vimeo] 142820366: Downloading akfire_interconnect_quic MPD information
[vimeo] 142820366: Downloading akfire_interconnect_quic MPD information
[vimeo] 142820366: Downloading fastly_skyfire MPD information
[vimeo] 142820366: Downloading fastly_skyfire MPD information
[info] Available formats for 142820366:
format code                                        extension  resolution note
dash-akfire_interconnect_quic_sep-audio-429092790  m4a        audio only DASH audio  113k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-fastly_skyfire_sep-audio-429092790            m4a        audio only DASH audio  113k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-akfire_interconnect_quic_sep-audio-429092788  m4a        audio only DASH audio  161k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-fastly_skyfire_sep-audio-429092788            m4a        audio only DASH audio  161k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-akfire_interconnect_quic_sep-video-429092789  mp4        480x270    DASH video  423k , mp4_dash container, avc1.42C01E, video only
dash-fastly_skyfire_sep-video-429092789            mp4        480x270    DASH video  423k , mp4_dash container, avc1.42C01E, video only
dash-akfire_interconnect_quic_sep-video-429092790  mp4        640x360    DASH video  638k , mp4_dash container, avc1.64001F, video only
dash-fastly_skyfire_sep-video-429092790            mp4        640x360    DASH video  638k , mp4_dash container, avc1.64001F, video only
dash-akfire_interconnect_quic_sep-video-429092788  mp4        960x540    DASH video 1563k , mp4_dash container, avc1.64001F, video only
dash-fastly_skyfire_sep-video-429092788            mp4        960x540    DASH video 1563k , mp4_dash container, avc1.64001F, video only
dash-akfire_interconnect_quic-video-429092789      mp4        480x270    DASH video  422k , mp4_dash container, avc1.42C01E, mp4a.40.2 (48000Hz)
dash-fastly_skyfire-video-429092789                mp4        480x270    DASH video  422k , mp4_dash container, avc1.42C01E, mp4a.40.2 (48000Hz)
hls-akfire_interconnect_quic-324                   mp4        480x270     324k , avc1.42C01E, 23.976fps, mp4a.40.2
hls-fastly_skyfire-324                             mp4        480x270     324k , avc1.42C01E, 23.976fps, mp4a.40.2
http-270p                                          mp4        480x270    24fps
dash-akfire_interconnect_quic-video-429092790      mp4        640x360    DASH video  637k , mp4_dash container, avc1.64001F, mp4a.40.2 (48000Hz)
dash-fastly_skyfire-video-429092790                mp4        640x360    DASH video  637k , mp4_dash container, avc1.64001F, mp4a.40.2 (48000Hz)
hls-akfire_interconnect_quic-394                   mp4        640x360     394k , avc1.64001F, 23.976fps, mp4a.40.2
hls-fastly_skyfire-394                             mp4        640x360     394k , avc1.64001F, 23.976fps, mp4a.40.2
http-360p                                          mp4        640x360    24fps
dash-akfire_interconnect_quic-video-429092788      mp4        960x540    DASH video 1562k , mp4_dash container, avc1.64001F, mp4a.40.2 (48000Hz)
dash-fastly_skyfire-video-429092788                mp4        960x540    DASH video 1562k , mp4_dash container, avc1.64001F, mp4a.40.2 (48000Hz)
hls-akfire_interconnect_quic-766                   mp4        960x540     766k , avc1.64001F, 23.976fps, mp4a.40.2
hls-fastly_skyfire-766                             mp4        960x540     766k , avc1.64001F, 23.976fps, mp4a.40.2 (best)
<end of log>
```

---

---

### Description of your *issue*, suggested solution and other information
https://vimeo.com/142820366
I'm trying to download this video in particular. The video page lists 720p as an option, but when I pass -F in youtube-dl, 540p is the highest available quality. Is this a problem on Vimeo side or youtube-dl? Is there a way to fix it? 

To note, the HTTP Error 403 when downloading JSON Metadata might be caused by me using public VPN (not 100% sure that it is the cause), because Vimeo is blocked in my country. But I don't think it should affect video quality availability. I have tested it using ClipConverter.cc too (it downloads videos with their own servers) and 540p is somehow also the highest quality available.

**Comment by dstftw** [comment]
It's not 720p in web player but 540p.

**Comment by panhartstuff** [comment]
@dstftw Huh? I'm very clearly seeing a 720p option in the web player https://i.imgur.com/cYZ0mFS.png

**Comment by dstftw** [comment]
So what? It's a fake. Check fragment URLs' and compare with JSON rendition they are taken from.

**Comment by panhartstuff** [comment]
How exactly do you check that?

**Comment by dstftw** [comment]
I've already described how.

**Comment by panhartstuff** [comment]
Yes, but how do you check fragment URL and obtain JSON rendition?

**Comment by dstftw** [comment]
See browser's traffic with developer tools or firebug.
