### ISSUE TITLE
Exit code 0 when actually failing

### ISSUE THREAD

**Issue by bumbummen99** [rg3/youtube-dl#15634]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.11**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I am trying to develop an aplication with youtube-dl. When downloading a video to a very nested subfolder in order to reach the maixmum path length youtube-dl outputs the error 

ERROR: unable to open for writing: [Errno 2] No such file or directory: 'South Park_December 17, 1997_1_0110_South Park 110 - Mr. Hankey, der Weihnachtskot - 1. Ak-e6039bb4-ed00-11e0-aca6-0026b9414f30.mp4.part-Frag0.part'

(Used southpark for example). The process then exits with error code 0 (success) indicating that everything went well. I have also tested this beahivour with mistyped url's (404). Checking for the exitcode is therefore not working. Also if i start youtube dl within a c# process i cant get the error output. If i redirect all output it is still visible within my console window so it seems like the error message is  returned some other way.

How can i catch all errors programmaticaly when using youtube-dl and why is the exit code always 0?

**Comment by dstftw** [comment]
```
>py -3.6 -m youtube_dl BaW_jenozKc  -o '%(title)400s.%(ext)s'
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading video info webpage
[youtube] BaW_jenozKc: Extracting video information
ERROR: unable to open for writing: [Errno 2] No such file or directory: "'                                                                                                                                                                                                                                                                                                                                                                                    youtube-dl test video ''_ä↭𝕐.mp4'.f137.part"

>echo %ERRORLEVEL%
1
```
Most likely you're getting error code of wrapping process not youtube-dl.

**Comment by bumbummen99** [comment]
I have got it working by starting youtube-dl directly as a Process and setting the WorkingDirectory first. -o does not work for multiple files.

**Comment by dstftw** [comment]
>-o does not work for multiple files.

Not true.
