### ISSUE TITLE
Resume Udemy Download

### ISSUE THREAD

**Issue by luxint66** [rg3/youtube-dl#15637]
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.11**
- [ x] At least skimmed through the [README]
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [x ] Site support request (request for adding support for a new site)

### Description of your *issue*, suggested solution and other information

I'm trying to download a course from Udemy and have downloaded most of the course but was cut off towards the end. When I try to download it again it seems that Udemy catches it on the 18th page and then blocks my cookie. 

Is there any way to put a pause between each attempt to re-download a page? I think they are checking the frequency of page loads. Just a guess.

LOG

c:\udemy>youtube-dl --download-archive archive.txt -o "./%(playlist)s/%(chapter_number)s-%(chapter)s/%(autonumber)03d-%(title)s.%(ext)s" https://www.udemy.com/crush-online-micro-stakes-poker/learn/v4 --cookies cookies.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--download-archive', 'archive.txt', '-o', './%(playlist)s/%(chapter_number)s-%(chapter)s/%(autonumber)03d-%(title)s.%(ext)s', 'https://www.udemy.com/crush-online-micro-stakes-poker/learn/v4', '--cookies', 'cookies.txt', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] crush-online-micro-stakes-poker: Downloading webpage
[udemy:course] 496960: Downloading course curriculum
[download] Downloading playlist: Crush Micro Stakes Online Poker: The Complete Mastery Guide
[udemy:course] playlist Crush Micro Stakes Online Poker: The Complete Mastery Guide: Collected 122 video ids (downloading 122 of them)
[download] Downloading video 1 of 122
[udemy] 2898380: Downloading webpage
[udemy] 2898380: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] How to Crush Online Micro Stakes Poker has already been recorded in archive
[download] Downloading video 2 of 122
[udemy] 9271212: Downloading webpage
[udemy] 9271212: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] Why The Micro Stakes are So Profitable has already been recorded in archive
[download] Downloading video 3 of 122
[udemy] 9271292: Downloading webpage
[udemy] 9271292: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] How to Get The Most Out Of This Course has already been recorded in archive
[download] Downloading video 4 of 122
[udemy] 5142712: Downloading webpage
[udemy] 5142712: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] Strategies for Poker Learning Success has already been recorded in archive
[download] Downloading video 5 of 122
[udemy] 6020920: Downloading webpage
[udemy] 6020920: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] Instructor Earnings Update - Nov. 2016 has already been recorded in archive
[download] Downloading video 6 of 122
[udemy] 9271316: Downloading webpage
[udemy] 9271316: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] How to Get a Free Leak Finder Review has already been recorded in archive
[download] Downloading video 7 of 122
[udemy] 3107874: Downloading webpage
[udemy] 3107874: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] How to Record a Video for Your Leak Finder Video has already been recorded in archive
[download] Downloading video 8 of 122
[udemy] 9271328: Downloading webpage
[udemy] 9271328: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] Section Introduction has already been recorded in archive
[download] Downloading video 9 of 122
[udemy] 2898388: Downloading webpage
[udemy] 2898388: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] Understanding and Embracing Variance has already been recorded in archive
[download] Downloading video 10 of 122
[udemy] 9271336: Downloading webpage
[udemy] 9271336: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] Managing Tilt has already been recorded in archive
[download] Downloading video 11 of 122
[udemy] 9278822: Downloading webpage
[udemy] 9278822: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] Bankroll Management has already been recorded in archive
[download] Downloading video 12 of 122
[udemy] 6040262: Downloading webpage
[udemy] 6040262: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] Bankroll Management Tools has already been recorded in archive
[download] Downloading video 13 of 122
[udemy] 9271342: Downloading webpage
[udemy] 9271342: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] Multi-Tabling Strategy has already been recorded in archive
[download] Downloading video 14 of 122
[udemy] 9271344: Downloading webpage
[udemy] 9271344: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] Becoming a Student of The Game has already been recorded in archive
[download] Downloading video 15 of 122
[udemy] 9271350: Downloading webpage
[udemy] 9271350: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] The Power of Position has already been recorded in archive
[download] Downloading video 16 of 122
[udemy] 9271352: Downloading webpage
[udemy] 9271352: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] The Three Advantages has already been recorded in archive
[download] Downloading video 17 of 122
[udemy] 9271506: Downloading webpage
[udemy] 9271506: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[download] Section Introduction has already been recorded in archive
[download] Downloading video 18 of 122
[udemy] 9271488: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by luxint66** [comment]
Can you give a link to the duplicate? I searched and didn't find anything.

Lux

**Comment by dstftw** [comment]
#15571
