### ISSUE TITLE
Unable to obtain file audio codec with ffprobe

### ISSUE THREAD

**Issue by brian-from-fl** [rg3/youtube-dl#15644]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.11**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [Xx] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'-x', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'-o', u'/Users/brian/Local/Media/%(title)s.%(ext)s', u'-a', u'/Users/brian/Songs/Links/songs-2.txt']
[debug] Batch file urls: [u'https://youtu.be/hEvGKUXW0iI', u'https://youtu.be/s06qX5Jn_yM', u'https://youtu.be/KN_na84b9ik', u'https://youtu.be/EMzrgXFeX_o', u'https://youtu.be/uOUVE5rGmhMl', u'https://youtu.be/p0PjECSyJ7w', u'https://youtu.be/9OPc7MRm4Y8', u'https://youtu.be/7BDBzgHXf64', u'https://youtu.be/sd4VsbM4fOo', u'https://youtu.be/QxHkLdQy5f0', u'https://youtu.be/YyknBTm_YyM', u'https://youtu.be/oYu6HtUxRJs', u'https://youtu.be/8F5S4MdxRww', u'https://youtu.be/KN_na84b9ik', u'https://youtu.be/8N-qO3sPMjc', u'https://youtu.be/tMfXeuv4kZE', u'https://youtu.be/x7_jYYISAbM', u'https://youtu.be/DMj_suzPEUk', u'https://youtu.be/vwe3CzWZ4Bg', u'https://youtu.be/-aWkhuAu8go', u'https://youtu.be/fqwIpH6phJs', u'https://youtu.be/ubvYQxTXO3U', u'https://youtu.be/z_m4Qb0iW-o', u'https://youtu.be/ZXkk65PdKyM', u'https://youtu.be/YbVFy7nx88Q']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.11
[debug] Python version 2.7.14 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: avconv present, avprobe present, ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[youtube] hEvGKUXW0iI: Downloading webpage
[youtube] hEvGKUXW0iI: Downloading video info webpage
[youtube] hEvGKUXW0iI: Extracting video information
[youtube] {43} signature length 42.43, html5 player vfl8swg2e
[youtube] {18} signature length 42.43, html5 player vfl8swg2e
[youtube] {36} signature length 42.43, html5 player vfl8swg2e
[youtube] {17} signature length 42.43, html5 player vfl8swg2e
[youtube] {135} signature length 42.43, html5 player vfl8swg2e
[youtube] {244} signature length 42.43, html5 player vfl8swg2e
[youtube] {134} signature length 42.43, html5 player vfl8swg2e
[youtube] {243} signature length 42.43, html5 player vfl8swg2e
[youtube] {133} signature length 42.43, html5 player vfl8swg2e
[youtube] {242} signature length 42.43, html5 player vfl8swg2e
[youtube] {160} signature length 42.43, html5 player vfl8swg2e
[youtube] {278} signature length 42.43, html5 player vfl8swg2e
[youtube] {140} signature length 42.43, html5 player vfl8swg2e
[youtube] {171} signature length 42.43, html5 player vfl8swg2e
[youtube] {249} signature length 42.43, html5 player vfl8swg2e
[youtube] {250} signature length 42.43, html5 player vfl8swg2e
[youtube] {251} signature length 42.43, html5 player vfl8swg2e
[debug] Invoking downloader on u'https://r3---sn-hp57kn6e.googlevideo.com/videoplayback?sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&lmt=1449591262178227&clen=2836037&expire=1519006984&key=yt6&initcwndbps=988750&c=WEB&keepalive=yes&ipbits=0&itag=251&mime=audio%2Fwebm&requiressl=yes&dur=172.781&mt=1518985296&pl=43&mv=m&ei=qOCJWuS_MYvyDKWRspgJ&id=o-ADiDmU6kUYQeab8PDEPbCtn3mT2k-4xcPve12tKwjgpM&ms=au%2Conr&fvip=3&ip=2600%3A1700%3A1ce1%3A3550%3A496e%3A6191%3A5d9b%3A929a&gir=yes&mm=31%2C26&source=youtube&mn=sn-hp57kn6e%2Csn-5uaeznkl&signature=99393A501B6DC1D7C248D009BF89B68490B00B61.7F7AEAD7DFB8684F2B717B08E6D7EFB204E5F368&ratebypass=yes'
[download] Destination: /Users/brian/Local/Media/Bing Crosby - Mele Kalikimaka (Hawaiian Christmas Song).webm
[download] 100% of 2.70MiB in 00:00
[debug] avconv command line: avprobe -show_streams 'file:/Users/brian/Local/Media/Bing Crosby - Mele Kalikimaka (Hawaiian Christmas Song).webm'
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2035, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 243, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

As has been reported before with some older versions, the most recently updated version of youtube-dl and ffmpeg/ffprobe fail with the error:

*Unable to obtain file audio codec with ffprobe*

[youtube-dl.output.txt](https://github.com/rg3/youtube-dl/files/1735097/youtube-dl.output.txt)
[youtube-dl.versions.txt](https://github.com/rg3/youtube-dl/files/1735098/youtube-dl.versions.txt)

**Comment by dstftw** [comment]
`avconv` is most likely broken. Either fix it or `--prefer-ffmpeg`.

**Comment by brian-from-fl** [comment]
Thank you. The warning message was misleading, as it said ffprobe and not avprobe. I've specifically enabled --prefer-ffmpeg and it now works.
