### ISSUE TITLE
[Feature request] Add an option to resize downloaded video

### ISSUE THREAD

**Issue by pzmarzly** [rg3/youtube-dl#15642]
Since Youtube has started throttling download speeds for DASH formats, it's faster to always use `-f best` if you have decent Internet speed. While that's fine for music (`-x`), I would prefer not to have my hard drive filled with 4K videos.

So far [re-coding option](https://github.com/rg3/youtube-dl/blob/1b6712ab2378b2e8eb59f372fb51193f8d3bdc97/youtube_dl/postprocessor/ffmpeg.py#L310) only supports changing formats. Could you add an option to specify output video dimensions too?

**Comment by dstftw** [comment]
Throttling is already bypassed natively. As per resizing you can pass arbitrary args with `--postprocessor-args`.

**Comment by pzmarzly** [comment]
Sorry for bothering you, I didn't get the update due to Manjaro team skipping an update-pack last week. Now everything works as expected. Thanks.
