### ISSUE TITLE
Command to download file as an mp3

### ISSUE THREAD

**Issue by bollywoodfan** [rg3/youtube-dl#15653]
#youtube-dl download mp3 only 
Example
 youtube-dl --audio-format 'mp3' https://www.youtube.com/watch?v=QCjk_NPsIqU

**Comment by dstftw** [comment]
>--audio-format FORMAT            Specify audio format: "best", "aac", "flac", "mp3", "m4a", "opus", "vorbis", or "wav"; "best" by default; No effect without -x

>No effect without -x

**Comment by bollywoodfan** [comment]
Thanks for your prompt response. 

I am doing the same as you mention however final file is mp4
youtube-dl --audio-format 'mp3' https://www.youtube.com/watch?v=QCjk_NPsIqU

I am trying to download files as mp3..I also tried  following example to download mp3... however it created wem file.. what changes I need to make so that output will be high quality mp3.

from __future__ import unicode_literals
import youtube_dl


class MyLogger(object):
    def debug(self, msg):
        pass

    def warning(self, msg):
        pass

    def error(self, msg):
        print(msg)


def my_hook(d):
    if d['status'] == 'finished':
        print('Done downloading, now converting ...')


ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192',
    }],
    'logger': MyLogger(),
    'progress_hooks': [my_hook],
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://www.youtube.com/watch?v=BaW_jenozKc'])

**Comment by Hrxn** [comment]
> No effect without -x
