### ISSUE TITLE
Unable to download https URL from pluralsight

### ISSUE THREAD

**Issue by pyarilal** [rg3/youtube-dl#15650]
f:\ps>
f:\ps>youtube-dl --username "xxxxx" --password "xxxxx" --ver
bose --sleep-interval 30 "https://app.pluralsight.com/library/courses/https://ap
p.pluralsight.com/library/courses/azure-architecture-getting-started"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-
-verbose', '--sleep-interval', '30', 'https://app.pluralsight.com/library/course
s/https://app.pluralsight.com/library/courses/azure-architecture-getting-started
']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] https:: Downloading course JSON
[pluralsight:course] https:: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HT
TPError()); please report this issue on https://yt-dl.org/bug . Make sure you ar
e using the latest version; type  youtube-dl -U  to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\bu
ild\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\bu
ild\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt

**Comment by dstftw** [comment]
https://app.pluralsight.com/library/courses/https://app.pluralsight.com/library/courses/azure-architecture-getting-started is not a valid URL.
