### ISSUE TITLE
vod.pl

### ISSUE THREAD

**Issue by slimozis** [rg3/youtube-dl#15651]
[{"vertical_resolution_mode": "adaptive", "vertical_resolution": "1080", "video_bitrate_mode": "adaptive", "video_bitrate": "5120.00", "audio_bitrate_mode": "adaptive", "audio_bitrate": "192.00", "url": "http://media.onet.pl/_ms/f3199e0e-3b70-4a9a-a3d6-97ebe5e28e2b.1435179325.050296.ism/Manifest", "drm_key": null}]

E:\Pobrane\ffmpeg-20180114-856b7ca-win64-static\bin>youtube-dl -v -f bestvideo+b
estaudio --verbose http://media.onet.pl/_ms/f3199e0e-3b70-4a9a-a3d6-97ebe5e28e2b
.1435179325.050296.ism/manifest
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo+bestaudio', '--verbose', 'htt
p://media.onet.pl/_ms/f3199e0e-3b70-4a9a-a3d6-97ebe5e28e2b.1435179325.050296.ism
/manifest']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-89803-g856b7cae9f, ffprobe N-89803-g856b7cae9f
[debug] Proxy map: {}
[onet.pl] f3199e0e: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\bu
ild\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\bu
ild\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dstftw** [comment]
You should use the original vod.pl URL.
