### ISSUE TITLE
[Question] common _search_regex function always throws exception

### ISSUE THREAD

**Issue by Wandang** [rg3/youtube-dl#15668]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

I am having trouble with common.py's _search_regex function.
Based on the description I can give it a pattern/regex, a string to search through and a code word for logging that is free to chose.

Furthermore it states that it takes the first matching group to work with. I just can't get this to work.
I've gone so far to blatantly search for a fixed url in the webpage: https://regex101.com/r/33L08o/1

The webpage is http://www.vol.at/blue-man-group/5593454

As you can see in the regex101.com link the first group that is detected is the url. But I still get an RegexNotFoundError/Exception.

My code:

```    def _real_extract(self, url):
        video_id = self._match_id(url)
        webpage = self._download_webpage(url, video_id)
        title =  self._og_search_title(webpage)
        print("regex test")
        video_url = self._search_regex(
            r'(?s)file:\s*"(https://vs-pd-russmedia\.sf\.apa\.at/vs_vn/20171215_20_169570_bluemangroupe_720\.mp4\?guid=293f6d17-692a-44e3-9fd5-7b178f3a1029)"',
            webpage, 'url')

**Comment by dstftw** [comment]
There is no code matching this regex at http://www.vol.at/blue-man-group/5593454 thus you are getting `RegexNotFoundError`.
