### ISSUE TITLE
I can't use the program

### ISSUE THREAD

**Issue by Nosttromo** [rg3/youtube-dl#15686]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.22*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.22**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

I can't use the goddamn program. The tutorial is so poorly explained that I can't even begin to understand how does this work. The ones who wrote the readme must think that only programmers familiar with python will use this application, it is far away from user friendly, it's so poorly designed that it doesn't even contain a config file included on the download, let alone instructions for using it. I am now here 40 minutes into this thing and trying to understand anything but nothing makes sense. I downloaded the exe version but when I run it I see a command prompt box that vanishes before I can read what it says. tried typing commands on the command prompt with and without admin privileges and didn't work. tried typing commands on the adress box but again nothing worked. I CAN'T TYPE COMMANDS ON THE APPLICATION BECAUSE IT WON'T STAY OPEN NOR DOES **ANY SECTION OF THE README SAYS WHERE AND HOW TO RUN COMMANDS** IT'S UNBELIEVABLE!!!! For example, on the header of this thread, it reads "run `youtube-dl --version` and ensure your version is *2018.02.22*", but WHERE DO I ENTER THIS CODE??????? The creator of this program must have thought that everyone is familiar with procedures on how to use it but forgot that not everyone is a python programmer or is familiar with command line programs. When I was wasting my time reading the endless readme file I found out that for my surprise, the user has to create a config file, then I went and created it. Tried to drag it into the exe, remembering about something else I did that used this drag and drop method, **NOT BY BEING TAUGHT TO DO SO BY THE README BECAUSE IT DOESN'T SAY IT ANYWHERE** and got another instant command prompt screen that again vanished before I could see what was written on it. 

I give up, i'm now one hour into this and i'm only writing this because I need to download max quality videos and to let the guy who wrote the readme know that he should write instructions like if he was someone that never saw that before, nobody knows what runs through your mind. they talked about running lines of commmand but didn't say WHERE to write the command lines, they ASSUMED that the user would know. That is not how you write an instructional file. Guide people as if they never saw that before, because they didn't.

I don't know if i'll get any help after venting my rage and frustration, but if anyone wants to provide CLEAR INSTRUCTIONS on how to use the program, i'll be grateful.

That is all, thanks for your time.

**Comment by dstftw** [comment]
youtube-dl assumes you are familiar with command line. Learn how to use command line before using youtube-dl.
