### ISSUE TITLE
ERROR: ....: YouTube said: This video is no longer available because the YouTube account associated with this video has been terminated.

### ISSUE THREAD

**Issue by douma** [rg3/youtube-dl#15684]
This error prevents me from downloading all search results at the moment. Instead, maybe the exception can be caught and the process continue? Or maybe with a flag to continue on errors? 

~~~
youtube-dl "ytsearchall:test"
~~~

**Comment by douma** [comment]
Sorry, Im am for sure the idiot here:
~~~
youtube-dl "ytsearchall:test" --ignore-errors 
~~~

**Comment by OliCB** [comment]
No you are not an idiot at all! I was wondering about the same thing and your issue taught me something, so thanks :P
