### ISSUE TITLE
return FLV instead of MP4

### ISSUE THREAD

**Issue by coolboy444** [rg3/youtube-dl#1568]
Hi all!

i try download video itag=18 - MP4 640 x 360 e.g.

http://r7---sn-gvnuxaxjvh-v8ce.c.youtube.com/videoplayback?fallback_host=tc.v16.cache1.c.youtube.com&type=video/mp4; codecs="avc1.42001E, mp4a.40.2"&quality=medium&itag=18&cp=U0hXRlFNT19MTUNON19JR1NKOkFpUGMxeUozM0tm&upn=fTTJUjjf0gg&ip=176.59.181.112&key=yt5&sparams=cp,id,ip,ipbits,itag,ratebypass,source,upn,expire&ipbits=8&expire=1381121973&sver=3&source=youtube&fexp=904448,903903,922222,932200,916807,932912,916611,924606,924616,916914,929141,929117,929121,929906,929907,929922,929923,929127,929129,929131,929930,936403,925724,925726,936310,925720,925722,925718,936401,925714,929917,906945,929933,929935,929937,929939,939602,939604,937102,906842,913428,920605,912715,919811,939908,935704,932309,913563,901812,919373,930803,908538,904839,932211,934003,934004,931924,938608,940501,936308,939201,900816,912711,916304,900391,934507,907231,936312,906001&id=3c36fa16f7d0a0b3&ratebypass=yes&ms=au&mt=1381099711&mv=m&signature=548793096FC85EDE010E028FF2007F0FFB9AEF95.8D22D451F69EFC1F195A1B3346C34C62E88B49CC

But i receive FLV file...

HTTP/1.1 200 OK
Date: Sun, 06 Oct 2013 22:52:40 GMT
Server: gvs 1.0
Last-Modified: Mon, 16 Sep 2013 23:33:39 GMT
Content-Type: video/mp4
Expires: Sun, 06 Oct 2013 22:52:40 GMT
Cache-Control: private, max-age=21713
Accept-Ranges: none
Content-Length: 45126226
Alternate-Protocol: 80:quic
X-Content-Type-Options: nosniff
X-Vent-VVO: TRANSCODED
X-VVO-XCODE: I_482_H264_386_AAC_96_O_libx264_160_copy_96_DEFAULT
X-VVO-OBR: 256000
Connection: close

FLV   	     5        
onMetaData    
canseeko

i amazing... Content-Type: video/mp4 but return FLV file...

this strange headers appended when FLV file receive instead of MP4

X-Vent-VVO: TRANSCODED
X-VVO-XCODE: I_482_H264_386_AAC_96_O_libx264_160_copy_96_DEFAULT
X-VVO-OBR: 256000

why this occurs ?

thanks

**Comment by phihag** [comment]
We now use https by default, so your ISP cannot meddle with the downloaded files.
