### ISSUE TITLE
Very slow download speeds on 10Gbps server

### ISSUE THREAD

**Issue by Qwerty-Space** [rg3/youtube-dl#15690]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.22*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.22**

```
 ~/pip/bin/pip install -U youtube-dl
Requirement already up-to-date: youtube-dl in ./pip/lib/python3.5/site-packages
[zeus ~] youtube-dl --version
2018.02.03
```

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: ['-o', '~/private/youtube/%(uploader)s/%(title)s_%(id)s.%(ext)s', '-w', '--audio-quality', '0']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtu.be/n9eZ00bRCGA']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.03
[debug] Python version 3.5.0 (CPython) - Linux-4.14.11-feral-x86_64-with-debian-8.10
[debug] exe versions: avconv 11.11-6, avprobe 11.11-6, ffmpeg 3.2.4-static, ffprobe 3.2.4-static
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

When downloading starts off, it shows a high speed, like 50 - 200MB/s, then after a few seconds it drops to a few hundred KB/s.  I am running youtube dl on a debian server hosted by Feralhosting.  I installed it with pip.

**Comment by Qwerty-Space** [comment]
Why can't I get the latest version then?

**Comment by Hrxn** [comment]
Complain to Debian maintainers or install youtube-dl as instructed in Readme.md.

**Comment by Qwerty-Space** [comment]
@Hrxn I did install it as instructed in the readme

**Comment by Hrxn** [comment]
But you version is outdated..
> `[debug] youtube-dl version 2018.02.03`

And this is not caused by pip itself. I use the pip package as well...

**Comment by Qwerty-Space** [comment]
@Hrxn then why won't it update to the latest version with pip?

**Comment by Hrxn** [comment]
How should we know? Maybe ask you hoster if they are running some local cache or proxy or something..
You can check the package version on the pip website itself, it's the correct one.

**Comment by Qwerty-Space** [comment]
```Collecting 2018.2.22
  1 location(s) to search for versions of 2018.2.22:
  * https://pypi.python.org/simple/2018-2-22/
  Getting page https://pypi.python.org/simple/2018-2-22/
  "GET /simple/2018-2-22/ HTTP/1.1" 404 38
  Could not fetch URL https://pypi.python.org/simple/2018-2-22/: 404 Client Error: Not Found (2018-2-22 does not exist) for url: https://pypi.python.org/simple/2018-2-22/ - skipping
```

**Comment by Qwerty-Space** [comment]
Strange.  If I do `pip search youtube-dl` it shows the latest version.  But any attempt to download that version doesn't work, so maybe there's a problem with it on there.

**Comment by Qwerty-Space** [comment]
I've tried a whole bunch of things.  This is quite strange.

```[zeus ~] ~/pip/bin/pip install --upgrade youtube_dl==2018.2.22
Requirement already up-to-date: youtube_dl==2018.2.22 in ./pip/lib/python3.5/site-packages
[zeus ~] ~/pip/bin/pip install --upgrade youtube-dl==2018.2.22
Requirement already up-to-date: youtube-dl==2018.2.22 in ./pip/lib/python3.5/site-packages
[zeus ~] ~/pip/bin/pip install --upgrade youtube-dl
Requirement already up-to-date: youtube-dl in ./pip/lib/python3.5/site-packages
[zeus ~] ~/pip/bin/pip install youtube-dl -U
Requirement already up-to-date: youtube-dl in ./pip/lib/python3.5/site-packages
[zeus ~] youtube-dl --version
2018.02.03
[zeus ~] ~/pip/bin/pip install youtube-dl==2018.2.22
Requirement already satisfied: youtube-dl==2018.2.22 in ./pip/lib/python3.5/site-packages```

**Comment by Qwerty-Space** [comment]
Aaaaaah

```
[zeus ~] ~/pip/bin/pip install --no-cache-dir youtube-dl==2018.2.22
Collecting youtube-dl==2018.2.22
  Downloading youtube_dl-2018.2.22-py2.py3-none-any.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 15.6MB/s
Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2018.2.3
    Not uninstalling youtube-dl at /media/sdh1/home/qwertyspace/python/python3/lib/python3.5/site-packages, outside environment /media/sdh1/home/qwertyspace/pip
Successfully installed youtube-dl-2018.2.22
[zeus ~] youtube-dl --version
2018.02.03
```
