### ISSUE TITLE
Wrong copyright assignment

### ISSUE THREAD

**Issue by rg3** [rg3/youtube-dl#157]
The youtube-dl source code has always been released to the public domain and all contributors have agreed to place the contributing code in the public domain. This means no intellectual property rights are claimed on the work, hence it cannot have a copyright notice like the one present in README.md.

The website, OTOH, is copyrighted. I will try to update its source code to provide it under a license that allows modifications in the near future.

**Comment by cyphar** [comment]
Why didn't you use [CC0](https://creativecommons.org/publicdomain/zero/1.0/)? The FSF [does not recommend the Unlicense](https://www.gnu.org/licenses/license-list.en.html#Unlicense) as it is not as well written nor mature as the Creative Commons set of licenses.
