### ISSUE TITLE
Clipping in youtube-dl

### ISSUE THREAD

**Issue by stalepie** [rg3/youtube-dl#15705]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.26**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ x] Feature request (request for a new functionality)
- [ ] Question
- [ x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

Hello, thanks for this program, but there is a problem when downloading audio, such as music. YouTube-dl seems to introduce clipping by going over level. See this screenshot in Audacity of a file I tried recently:

https://imgur.com/a/X5eQY

This happens many times - I suspect the original files may not always be clipping (going into red). When I try recording manually in Audacity the waveforms are not only smaller but don't look clipped at the peaks in the same areas. What may be happening is youtube-dl is normalizing the audio by default? If so, please leave that off, or provide an option to disable it. I'd rather the volume levels match the original (whatever is uploaded). 

The problem seems to be in YouTube-DL 0.4 GUI as well, where I first encountered it, but I tried the command line version tonight too. 

Thanks, 

Matt

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
