### ISSUE TITLE
How to stop live stream recording?

### ISSUE THREAD

**Issue by rhazor** [rg3/youtube-dl#15717]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

How to stop live stream recording? Pressing Q does not do anything. And CTRL+C stops it, but then I'm left with a .part extension file, which is not a video.

I found this https://github.com/rg3/youtube-dl/issues/8932 but it is unsolved and locked.

**Comment by dstftw** [comment]
Ctrl+C works fine. Do not hit it multiple times.

**Comment by sebma** [comment]
@rhazor You can use the `timeout` command if you know in advance how long the recording is going to last, example : 

```bash
$ timeout -s SIGINT 110m youtube-dl -f 93 $your_Youtube_Live_Stream_URL
```
