### ISSUE TITLE
Strange behaviour of --download-archive

### ISSUE THREAD

**Issue by urza** [rg3/youtube-dl#15714]
Hello,

I have debian server downloading every night (with command in crontab -e calling simple script to download my vimeo liked videos) and saving downloaded ids to "downloaded.txt" file.

But it behaves strangely and I dont understand what is going on.

First, here is my crontab -e:
![screenshot 2018-02-27 13 50 05](https://user-images.githubusercontent.com/189804/36729882-ea7181d4-1bc5-11e8-932e-268a3e236199.png)

here is the youtube-dl command that gets executed:
![screenshot 2018-02-27 13 49 45](https://user-images.githubusercontent.com/189804/36729900-fbe9b1e8-1bc5-11e8-8603-923339eb3bd7.png)

and finally here is the problem:
![screenshot 2018-02-27 13 49 08](https://user-images.githubusercontent.com/189804/36729931-0fbd9e32-1bc6-11e8-9666-543b088abe31.png)

The file gets downloaded every day, looks like there is some problem writing archive to downloaded.txt, but the file is owned by me and has write for everybody.

Furthermore, strange behaviour: If I delete the duplicate files and leave only one of them, then it will stop donwnloading them again, and will leave just the one there.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by urza** [comment]
Here you go dear dstftw
---

I AM AT THE LATETS VERSION
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.26**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
I SPENT LIKE AN HOUR TRYING TO FIGURE IT OUT FROM YOUR DOCUMENTATION
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X ] Question (I KNOW IT IS CONFUSING BECAUSE I DIDNT PUT THE QUESTION MARK, BUT I AM ACTUALLY ASKING WHAT IS GOING ON WITH THE COMMAND AND WHY IS IT NOT WORKING AS INTENDED) 

SINCE MY SCRIPT RUNS FROM CRONTAB, I BELIEVE THE SCREENSHOTS AND DESCRIPTIONS WOULD BE HELPFUL, BUT LET ME KNOW IF YOU NEED KNOW ANYTHING ELSE OR FILL ANY MORE OF YOUR FORMS.

**Comment by urza** [comment]
And here is your DEBUG LOG, you have some  BUG there as it turns out:

./dl_vimeoL.sh
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--download-archive', u'/media/strix/urza/multimedia/VIDEOS/SHORT/vimeo-likes/downloaded.txt', u'-o', u'/poolgarden/urza/media/VIDEOS/SHORT/vimeo-likes/20180227-%(uploader)s-%(title)s-%(id)s.%(ext)s', u'-w', u'--restrict-filenames', u'vimeo.com/user755559/likes']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.26
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-4-amd64-x86_64-with-debian-9.3
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[generic] likes: Requesting header
[redirect] Following redirect to https://vimeo.com/user755559/likes
[vimeo:likes] 755559: Downloading webpage
[download] Downloading playlist: Videos urza likes
[vimeo:likes] 755559: Downloading page 1/34
[vimeo:likes] 755559: Downloading page 2/34
[vimeo:likes] 755559: Downloading page 3/34
[vimeo:likes] 755559: Downloading page 4/34
[vimeo:likes] 755559: Downloading page 5/34
[vimeo:likes] 755559: Downloading page 6/34
[vimeo:likes] 755559: Downloading page 7/34
[vimeo:likes] 755559: Downloading page 8/34
[vimeo:likes] 755559: Downloading page 9/34
[vimeo:likes] 755559: Downloading page 10/34
[vimeo:likes] 755559: Downloading page 11/34
[vimeo:likes] 755559: Downloading page 12/34
[vimeo:likes] 755559: Downloading page 13/34
[vimeo:likes] 755559: Downloading page 14/34
[vimeo:likes] 755559: Downloading page 15/34
ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 519, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2199, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
