### ISSUE TITLE
Can't download from manifest url (or origin collder url)

### ISSUE THREAD

**Issue by rominatrix** [rg3/youtube-dl#15711]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
D:\v>youtube-dl.exe -v -i http://hlsrv.vidible.tv/prod/5a93049b91447547b1f5432e/
2018-02-25/hls/segment_1920x1080x1500_v2.m3u8?PR=E&S=333XbNc3Ag1DZt6PB8Of1nV98K5
zlB3c3ru_5_cKYQJsK7YUQK_TeE4iULF8EDby
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-i', 'http://hlsrv.vidible.tv/prod/5a93049b91
447547b1f5432e/2018-02-25/hls/segment_1920x1080x1500_v2.m3u8?PR=E']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.02.26
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] segment_1920x1080x1500_v2: Requesting header
WARNING: Could not send HEAD request to http://hlsrv.vidible.tv/prod/5a93049b914
47547b1f5432e/2018-02-25/hls/segment_1920x1080x1500_v2.m3u8?PR=E: HTTP Error 403
: token is invalid or expired
[generic] segment_1920x1080x1500_v2: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: token is invalid or expired (
caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make
 sure you are using the latest version; type  youtube-dl -U  to update. Be sure
to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfqykkd7x\bu
ild\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfqykkd7x\bu
ild\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt

"S" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
```

### Description of your *issue*, suggested solution and other information

URLS from the video:
Original URL of the video = http://collider.com/black-panther-interview-andy-serkis-martin-freeman

m3u8 url i've extracted from it = http://hlsrv.vidible.tv/prod/5a93049b91447547b1f5432e/2018-02-25/hls/segment_1920x1080x1500_v2.m3u8?PR=E&S=333XbNc3Ag1DZt6PB8Of1nV98K5zlB3c3ru_5_cKYQJsK7YUQK_TeE4iULF8EDby  (they seem to expire though)

Trying to download that video from collider (URL indicated above). It's not possible using either the url and just youtube-dl URL, or youtube-dl -i MANIFEST. It always reads "token is invalid or expired" even if the second that the m3u8 url comes up, y paste it on my youtube-dl command.

**Comment by dstftw** [comment]
Most likely expired.

**Comment by rominatrix** [comment]
Yes, it says expired but there's no way to download the video then? I copy/pasted it instantly. However the links are still valid cause you can download them. Should I make a site support request then?

**Comment by dstftw** [comment]
Can download manifest != can download its contents.

**Comment by rominatrix** [comment]
Thank you @remitamine for your help. Guess my reading of the faqs wasn't as thorough as I thought. Lesson learned.
