### ISSUE TITLE
check if download achieved previously before downloading 

### ISSUE THREAD

**Issue by vinchuco** [rg3/youtube-dl#15724]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When re-downloading a playlist again, it will download files even if the file has already been downloaded. This is inefficient. The program could simply check whether the file has been already downloaded (partially or completely) and skip or fill in the gaps.

**Comment by dstftw** [comment]
This is what actually happens.

**Comment by vinchuco** [comment]
You're right, but also possibly wrong. Here's some clarification as to what I encountered:

command run:
youtube-dl --no-check-certificate -x --audio-format mp3 -o "C:/Users/user/Downloads/YOUTUBE DL/mega drive/%(title)s-%(id)s.%(ext)s" --yes-playlist -i https://www.youtube.com/playlist?list=PLOqxBYtf-nSJ5SfICXBRP_jHO2l36bnSp

Output:

blah blah blah
[download] Downloading video 3 of 57
blah blah blah
[download] Destination: C:\Users\user\Downloads\YOUTUBE DL\mega drive\Mega Drive - Maniac-nU0uTq6IhPM.webm
**[download] 100% of 6.22MiB in 02:41**  
[ffmpeg] Destination: C:\Users\user\Downloads\YOUTUBE DL\mega drive\Mega Drive - Maniac-nU0uTq6IhPM.mp3
Deleting original file C:\Users\user\Downloads\YOUTUBE DL\mega drive\Mega Drive - Maniac-nU0uTq6IhPM.webm (pass -k to keep)
[download] Downloading video 4 of 57
blah blah blah  


In bold what shouldn't happen in my mind (but maybe I'm wrong, in which case simply ignore this). 

Conclusion:
It seems as if it downloads webm first, then converts, then notices mp3 was already there and deletes it.

**Comment by dstftw** [comment]
`--download-archive`.
