### ISSUE TITLE
Other Spankbang.com formats than 240p are not supported anymore

### ISSUE THREAD

**Issue by sebma** [rg3/youtube-dl#15727]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Hi, this video has 240p and 320p resolutions available but only the 240p is supported here :

```
$ youtube-dl --ignore-config -v -F https://spankbang.com/16cig/video/amateur+car+blowjob+nice+ebony+ass
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', '-F', 'https://spankbang.com/16cig/video/amateur+car+blowjob+nice+ebony+ass']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2018.02.26
[debug] Python version 3.4.3 (CPython) - Linux-4.4.0-112-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[SpankBang] 16cig: Downloading webpage
[SpankBang] 16cig: Checking 320p video format URL
[SpankBang] 16cig: 320p video format URL is invalid, skipping
[SpankBang] 16cig: Checking 240p video format URL
[SpankBang] 16cig: Checking 1080p video format URL
[SpankBang] 16cig: 1080p video format URL is invalid, skipping
[SpankBang] 16cig: Checking 720p video format URL
[SpankBang] 16cig: 720p video format URL is invalid, skipping
[SpankBang] 16cig: Checking 480p video format URL
[SpankBang] 16cig: 480p video format URL is invalid, skipping
[SpankBang] 16cig: Checking 320p video format URL
[SpankBang] 16cig: 320p video format URL is invalid, skipping
[SpankBang] 16cig: Checking 240p video format URL
[info] Available formats for 16cig:
format code  extension  resolution note
240p-0       mp4        240p       
240p-1       mp4        240p       (best)
```

**Comment by sebma** [comment]
Thanks a lot. When shall I update youtube-dl with : `pip3 install -U youtube-dl` ?

**Comment by Hrxn** [comment]
When a new release has been made on pip?

**Comment by sebma** [comment]
At line 39 of your [README.md file](https://github.com/rg3/youtube-dl/blob/master/README.md)

**Comment by sebma** [comment]
Is there a way to install the latest version from the latest commit on Linux ?
