### ISSUE TITLE
[npo] Downloading video's has stopped working

### ISSUE THREAD

**Issue by rien333** [rg3/youtube-dl#15725]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl -v https://www.npo.nl/door-het-hart-van-china/25-02-2018/VPWON_1265684
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.npo.nl/door-het-hart-van-china/25-02-2018/VPWON_1265684']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.26
[debug] Python version 2.7.10 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-45166-ga877d22d9, ffprobe N-45166-ga877d22d9, rtmpdump 2.4
[debug] Proxy map: {}
[npo] VPWON_1265684: Downloading JSON metadata
[npo] VPWON_1265684: Downloading token
[npo] VPWON_1265684: Downloading formats JSON
[npo] VPWON_1265684: Downloading Adaptive stream JSON
[npo] VPWON_1265684: Downloading m3u8 information
[npo] VPWON_1265684: Downloading Hoog stream JSON
[npo] VPWON_1265684: Downloading Normaal stream JSON
[npo] VPWON_1265684: Downloading Laag stream JSON
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'npo+drm://internetvod.omroep.nl/VPWON_1265684'
ERROR: unable to download video data: <urlopen error unknown url type: npo+drm>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1896, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1835, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 340, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2199, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 454, in _open
    'unknown_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1265, in unknown_open
    raise URLError('unknown url type: %s' % type)
URLError: <urlopen error unknown url type: npo+drm>
```

It seems like the NPO/uitzendinggemist website has changed in someway, which make their video's undownloadable with `youtube-dl`. Given the error output, it seems like it has something with new DRM protection. Interestingly, using [streamlink](https://streamlink.github.io) + [mpv](https://mpv.io) still allows me to watch NPO urls.

**Comment by rien333** [comment]
@dstftw What is this a duplicate of? This behavior was introduced fairly recently (last week or so) and I didn't find any other mention of it.

**Comment by bas080** [comment]
Somewhere between version `2018.02.04` and `2018.02.26` this regression was introduced. I know this because I have an older version of youtube-dl on another machine. It works fine when using that version. @rien333, if you want it to work you can downgrade to `2018.02.04`.

@dstftw, I suppose a fix is in the pipeline.
