### ISSUE TITLE
[toggle-sg] Unable to download video in highest quality 

### ISSUE THREAD

**Issue by yoshyuka** [rg3/youtube-dl#15721]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

C:\Users\Grey\Desktop>youtube-dl -f bestvideo+bestaudio "https://video.toggle.sg/en/series/kinship-s1-1/ep1/481931"
[toggle] 481931: Downloading video page
[toggle] 481931: Downloading video info json
[toggle] 481931: Downloading HLS_Mobile m3u8 information
[toggle] 481931: Downloading HLS_Web m3u8 information
[toggle] 481931: Downloading HLS_TV m3u8 information
[toggle] 481931: Downloading HLS_Tablet m3u8 information
ERROR: requested format not available

C:\Users\Grey\Desktop>youtube-dl -f bestvideo+bestaudio "https://video.toggle.sg/en/series/96-cafe/ep1/225607"
[toggle] 225607: Downloading video page
[toggle] 225607: Downloading video info json
[toggle] 225607: Downloading HLS_Mobile m3u8 information
[toggle] 225607: Downloading HLS_Web m3u8 information
[toggle] 225607: Downloading HLS_TV m3u8 information
[toggle] 225607: Downloading HLS_Tablet m3u8 information
ERROR: requested format not available

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.02.26
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://video.toggle.sg/en/series/96-cafe/ep1/225607
- Single video: https://video.toggle.sg/en/series/kinship-s1-1/ep1/481931

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Downloading videos from https://tv.toggle.sg is able to work however its unable to download videos at the highest quality available.

**Comment by dstftw** [comment]
You are requesting non existent format `bestvideo`.
