### ISSUE TITLE
List of subtitles

### ISSUE THREAD

**Issue by embryo10** [rg3/youtube-dl#15736]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=8jPQjjsBbIc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information
I use youtube-dl as a library in a python program.
Everything works ok exept the subtitles.
I can not get the subtitle info from any video.
Tried with a youtube one https://www.youtube.com/watch?v=8jPQjjsBbIc that it contains a lot of them.
Using
```python
ydl_opts = {'listsubtitles': True, "logger": logger,}
        with youtube_dl.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(self.link, download=False)
            return info
```
returns None
If I don't use the `listsubtitles` key, I get the info dict as expected.
I searched the net for this and I found [this answer](https://superuser.com/questions/927523/how-to-download-only-subtitles-of-videos-using-youtube-dl) and nothing else.
I must be doing something wrong, but I don't know what....
Any ideas on how to get the subtitle's list and how to download a specific one (this is the second thing I have to do *after* listing the subtitles)

**Comment by dstftw** [comment]
1. `{'writesubtitles': True}`.
2. `{'subtitleslangs': list of langs, 'skip_download': True}`.

**Comment by embryo10** [comment]
@dstftw Thank you.
