### ISSUE TITLE
Why i can not download all courses from lynda

### ISSUE THREAD

**Issue by zortunipsi** [rg3/youtube-dl#15749]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.03**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.03.03
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

why can I download only 6 videos?
youtube-dl --cookies "/cookies.txt" -v --all-subs -o "/LyndaCourses/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playl
ist_index)s.%(title)s.%(ext)s" "https://www.lynda.com/GitHub-tutorials/Learning-
Static-Site-Building-Hugo/651232-2.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', '/cookies.txt', '-v', '--all-subs', '-o
', '/LyndaCourses/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index
)s.%(title)s.%(ext)s', 'https://www.lynda.com/GitHub-tutorials/Learning-Static-S
ite-Building-Hugo/651232-2.html']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.02.22
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] 651232: Downloading course JSON
WARNING: 24 videos are only available for members (or paid members) and will not
 be downloaded. Use --username and --password options to provide lynda.com accou
nt credentials.
[download] Downloading playlist: Learning Static Site Building with Hugo
[lynda:course] playlist Learning Static Site Building with Hugo: Collected 6 vid
eo ids (downloading 6 of them)
[download] Downloading video 1 of 6

**Comment by numbermaniac** [comment]
Read what it told you.

> WARNING: 24 videos are only available for members (or paid members) and will not
be downloaded. Use --username and --password options to provide lynda.com accou
nt credentials.

Did you try this?

**Comment by zortunipsi** [comment]
Sorry, i dont have username and password... my account is organization type

**Comment by rotemdan** [comment]
I've created a simple `cookies.txt` exporter extension which I've verified to work with a `lynda.com` organizational account. Please try it and see if it solves your problem (it is available for both Firefox and Chrome):
> https://github.com/rotemdan/ExportCookies

The issue with some exporters (such as the [`cookies.txt`](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/) extension for Firefox) is that they add the `#HttpOnly_` prefix to `HttpOnly` cookies. This doesn't seem to be parsed correctly by `youtube-dl`. The exporter I published doesn't add this prefix.
