### ISSUE TITLE
nbc.com

### ISSUE THREAD

**Issue by archstar** [rg3/youtube-dl#1576]
It would be great if this tool supported nbc.com. I think it would be difficult because of the complex encryption. This script would be a good start. https://github.com/K-S-V/Scripts/blob/master/AdobeHDS.php

**Comment by yan12125** [comment]
Thanks @codesparkle, closing.

@archstar NBC.com is now supported, but the video you provided seems gone. (It redirects to http://www.nbc.com/the-tonight-show) If you still encounter problems, feel free to open a new issue.
