### ISSUE TITLE
DPlay.dk - Returns no subtitles

### ISSUE THREAD

**Issue by clearview1** [rg3/youtube-dl#15761]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```


[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--list-subs', u'https://www.dplay.dk/videoer/politijagt/season-18-episode-4', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.03
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-5-amd64-x86_64-with-debian-9.3
[debug] exe versions: ffmpeg 3.2.9-1, ffprobe 3.2.9-1
[debug] Proxy map: {}
[debug] Using fake IP 87.63.33.141 (DK) as X-Forwarded-For.
[DPlay] politijagt/season-18-episode-4: Downloading webpage
[DPlay] politijagt/season-18-episode-4: Downloading token
[DPlay] politijagt/season-18-episode-4: Downloading JSON metadata
[DPlay] politijagt/season-18-episode-4: Downloading JSON metadata
[DPlay] politijagt/season-18-episode-4: Downloading MPD manifest
[DPlay] politijagt/season-18-episode-4: Downloading m3u8 information
41009 has no subtitles


...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs https://www.dplay.dk/videoer/mythbusters/airbag-disaster-heads-will-roll

https://www.dplay.dk/videoer/politijagt/season-18-episode-4
---

### Description of your *issue*, suggested solution and other information

When I try to find subs for videos on dplay.dk, I just get returned with *VIDEO ID* has no subtitles.

**Comment by lyndmi** [comment]
Is this https://github.com/ytdl-org/youtube-dl/issues/6106 a duplicate or what?
