### ISSUE TITLE
File name - support

### ISSUE THREAD

**Issue by trackermb** [rg3/youtube-dl#15785]
hi there linux novice here need a little help with -o out command

youtube-dl -o '%(uploader)s/%(playlist)s/%(title)s%(id)s\.%(ext)s'
uploader/playlist/videotitle videoid.mp4 is the out but what im looking is the id to be within [] so it would look like
uploader/playlist/videotitle [videoid].mp4
is this even possible?

Thanks in advance
Mark

**Comment by dstftw** [comment]
Put brackets into `-o` and you'll get brackets.
