### ISSUE TITLE
[YouTube] Cannot download purchased content

### ISSUE THREAD

**Issue by blackoutworm** [rg3/youtube-dl#15788]
Hi there.
I am trying to download a video that I've purchased.
But it always ends up corrupt.
Here's what I've tried:
youtube-dl -v -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' -u MYUSERNAME -p MYPASSWORD https://www.youtube.com/watch?v=abtbN2YOzto
This gives me an error.
When I try to download the audio and video separate, only the first 3 seconds work.
Any idea?
And by the way. Yes, I do have the latest version installed.

**Comment by Krosgore** [comment]
What is happening to me is that randomly the speed is slowly being slow until the download is blocked.

**Comment by blackoutworm** [comment]
@Krosgore No, that's not a related problem.
It does download the complete file. But there seem to be a problem decrypting the file. Because only the first few seconds of the video as well as audio work when I download them as separate files.
But when I download the whole video, it gives me some sort of a codec error.

**Comment by blackoutworm** [comment]
Isn't everything on YouTube DRM protected in one way or another though?
So if that's the case, then the key here is to find a way to crack this DRM protection.
Any idea? Thanks in advance.

**Comment by dstftw** [comment]
No, regular videos are not DRM protected though protected with different mechanisms.

**Comment by blackoutworm** [comment]
@dstftw I'm not talking about regular videos here though.
But a purchased movie.
Wish there was a way to get rid of this DRM.
