### ISSUE TITLE
Get the video count of a playlist

### ISSUE THREAD

**Issue by blueray453** [rg3/youtube-dl#15789]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

I just want to know the number of videos in a playlist. 

For Ex. when I start downloading a playlist, it shows 
`Course Name: Collected 61 video ids`

I only want this line for my playlist. How can I do that?

**Comment by dstftw** [comment]
`--dump-single-json` and count the number of entries.

**Comment by blueray453** [comment]
How to count the number of entries?

**Comment by blueray453** [comment]
There is two possible solutions for future reference

1. add --get-title or --get-id and pipe that into wc -l
2. youtube-dl --dump-single-json WHATEVER | python -c 'import sys,json; print len(json.load(sys.stdin)["entries"])'
