### ISSUE TITLE
Youtube serves different itags (was: youtube-dl 2013.10.07 does not always pick highest resolution)

### ISSUE THREAD

**Issue by himadri0327** [rg3/youtube-dl#1578]
Was downloading videos from youtube user DiapasonRecords and saw that it wasn't downloading the max resolution for few videos randomly.

**Comment by strelec** [comment]
I agree completely.

**Comment by RickyRomero** [comment]
@strelec: No re-encoding is performed. ffmpeg simply merges the raw audio and video streams into the final file.

**Comment by RickyRomero** [comment]
I think you guys can close this one now. youtube-dl is picking the best resolution by default and muxing to mkv.

Any objections?

**Comment by up4** [comment]
I'm fine with the infinitely long format string ;-)

Ok, seriously, you can close it. Thanks.
