### ISSUE TITLE
"--download-archive" option is incompatible with downloading multiple file formats by single url

### ISSUE THREAD

**Issue by roman90sv** [rg3/youtube-dl#15781]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When I need to download multiple files by single url, i can't use "--download-archive", because only one of requested files will be downloaded. For example, i can't combine "--download-archive" option with:
-f best,251
OR
-f "mp4[height=1080]+251"

Youtube-dl will add an ID to archive.txt immediately after the first file is downloaded. And the second file will not be downloaded with following message: "...has already been recorded in archive".

![default](https://user-images.githubusercontent.com/35082918/37015699-bbc6ede8-2119-11e8-9bd5-9051a18ee701.jpg)

**Comment by dstftw** [comment]
This is expected behavior.

**Comment by roman90sv** [comment]
dstftw, Why does not the program add an id to the archive after downloading **all** the requested files?
