### ISSUE TITLE
Not an issue, but a question about a feature

### ISSUE THREAD

**Issue by Asia81** [rg3/youtube-dl#15783]
Hi, this is not to post an issue, but I'm sorry, I don't know where to ask this.

I managed to download an anime episode from crunshyroll, with all subtitles, but I would know if there is a way to download all audio dubs?
Like french, english, japanese... and merge them all in an mkv file, along with all subtitles files.
The goal is to have an mkv with all audio dubs and all subtitles.

This is the command line I use, but I don't find an argument to get all audio partitions.
`YoutubeDL -i "http://www.crunchyroll.com/yamada-kun-and-the-seven-witches/episode-1-ive-turned-into-her-753051?p1080=1" -u PRIVATE -p PRIVATE --verbose --all-subs --sub-format ass --embed-subs --recode-video mkv`

**Comment by dstftw** [comment]
1. Only if you do merging on your own.
2. There are no other audio dubs for this video.
