### ISSUE TITLE
Support for sub-domains on Udemy

### ISSUE THREAD

**Issue by xRahul** [rg3/youtube-dl#15786]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Can we add support for sub domains for Udemy? Udemy for business has sub-domains that are company specific but we are currently only supporting www.udemy.com

**Comment by xRahul** [comment]
@dstftw I have updated the description. Let me know what else is missing and I'll add that.

**Comment by dstftw** [comment]
You must provide concrete URLs.

**Comment by xRahul** [comment]
URLs are organisation specific. the `wiXXX` part can be anything. I'll update the same for google org. But this needs to be org agnostic.
