### ISSUE TITLE
Suggestion for download() function

### ISSUE THREAD

**Issue by killown** [rg3/youtube-dl#15795]
Do something like that for download() function

    def download(self, url):
         url_list = url
         if type(url) == str:
             url_list = [url]
        """Download a given list of URLs."""
        outtmpl = self.params.get('outtmpl', DEFAULT_OUTTMPL)
        if (len(url_list) > 1 and
                outtmpl != '-' and
                '%' not in outtmpl and
                self.params.get('max_downloads') != 1):

**Comment by dstftw** [comment]
Don't see much point in that. Doc string is clear about what type of argument you should pass.
