### ISSUE TITLE
[XVideos] Can't get thumbnail, can't get video

### ISSUE THREAD

**Issue by Jazzzon** [rg3/youtube-dl#15799]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
# youtube-dl --quiet --verbose --prefer-free-formats --no-check-certificate "https://www.xvideos.com/video299069/diesel_sfw_xxx_video" -o -    > diesel.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--quiet', u'--verbose', u'--prefer-free-formats', u'--no-check-certificate', u'https://www.xvideos.com/video299069/diesel_sfw_xxx_video', u'-o', u'-']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2018.03.03
[debug] Python version 2.7.13 (CPython) - Linux-4.9.78-xxxx-std-ipv6-64-x86_64-with-debian-9.3
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: unable to extract thumbnail; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'http://hls1-l3.xvideos-cdn.com/d9704bf97dcb248f22a24c4956fc28e8dcd0ac4f-1520526038/videos/hls/93/5e/7a/935e7a0c7bd95609d9d0cad44a349276-1/hls-360p.m3u8'
ERROR: unable to download video
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1989, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 850, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1623, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1901, in process_info
    raise UnavailableVideoError(err)
UnavailableVideoError: [Errno 2] No such file or directory: '-'


...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.xvideos.com/video299069/diesel_sfw_xxx_video

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Can't get the thumbnails and can't get the video. I think it's because it's M3u8 stream and not MP4/WEBM/normal file.

**Comment by Hrxn** [comment]
Probably a recent site change.

**Comment by parmjitv** [comment]
Hi @Jazzzon,

Are you still having this issue?  I am able to download this and other videos from the XVideos site without any problems using the latest youtube-dl build 2018.03.14.

You are correct about the missing thumbnail - a new PR will be submitted to address this.

Cheers,

Parmjit V.
