### ISSUE TITLE
Add feature to add extractors to blacklist

### ISSUE THREAD

**Issue by owhous** [rg3/youtube-dl#15790]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

I don't want to able to play videos specific from specific sites, by names of extractors, for example:
`--blacklist=xvideos,twitch`

**Comment by dstftw** [comment]
This will introduce ambiguity for embeds of blacklisted extractors. I also don't see much sense in this feature. If you don't want to be able to download some videos don't download them at all.
