### ISSUE TITLE
[bilibili]some url return error -5016

### ISSUE THREAD

**Issue by kesdoputr** [rg3/youtube-dl#15808]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.03**

Hello,i'm using window's exe version 2018.03.03
Some bilibili video will return **error -5016**

https://www.bilibili.com/video/av20576156/

Z:\tb>youtube-dl --verbose https://www.bilibili.com/video/av20576156/
[debug] System config: []
[debug] User config: ['--no-check-certificate', '-f', 'mp4']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.bilibili.com/video/av20576
156/']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2018.03.03
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
[BiliBili] 20576156: Downloading webpage
[BiliBili] 20576156: Downloading video info page
ERROR: BiliBili returns error -5016
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\bu
ild\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\bu
ild\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\bu
ild\youtube_dl\extractor\bilibili.py", line 131, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\bu
ild\youtube_dl\extractor\bilibili.py", line 82, in _report_error
youtube_dl.utils.ExtractorError: BiliBili returns error -5016

And one more,is there the problem **Unable to extract player parameters** have fix?
Now i still found that some bilibili url can be download,but some url returns
**Unable to extract player parameters** and some url returns **error -5016**

Thx for your reply.

**Comment by Dioxaz** [comment]
Noticed the same thing today attempting to download another video (https://www.bilibili.com/video/av20203938/). Note that none of my known methods (YDH, Firefox's inspector, online downloaders...) seem to work.
