### ISSUE TITLE
Download video also when archived (cli option)

### ISSUE THREAD

**Issue by bas080** [rg3/youtube-dl#15812]
I have not seen this feature in the man pages but it might be a feature already.

Is it possible use the archive option but have it download also when the video has been archived.

My reason for this is because I want to log what I have downloaded but also download if the video is not present.

**Comment by dstftw** [comment]
Not possible. Such option will break the whole point of download archive. If you want to log - do log not download archive.

**Comment by bas080** [comment]
You have a valid point @dstftw, I came up with the following solution in case someone is interested. I archive and then append the archive to a log file before removing the archive file.

```bash
npo-download() {
  local tmp_archive="$(mktemp)"
  local log_file="$HOME/youtube.log"

  youtube-dl --download-archive "$tmp_archive" "$@"

  cat $tmp_archive >> $log_file
  rm $tmp_archive # optional
}
```
