### ISSUE TITLE
CBS Episodes Not Downloadable

### ISSUE THREAD

**Issue by mannweb** [rg3/youtube-dl#15814]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.10**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--prefer-ffmpeg', u'-o', u'Episode 01.mp4', u'http://www.cbs.com/shows/ncis-new-orleans/video/k1h2PHncp7gfeLweU9z0Mm_feo_1KGSq/ncis-new-orleans-aftershocks/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.10
[debug] Python version 2.7.14 (CPython) - Linux-4.13.0-36-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: avconv 3.3.4-2, avprobe 3.3.4-2, ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] k1h2PHncp7gfeLweU9z0Mm_feo_1KGSq: Downloading XML
[CBS] k1h2PHncp7gfeLweU9z0Mm_feo_1KGSq: Downloading StreamPack SMIL data
[CBS] k1h2PHncp7gfeLweU9z0Mm_feo_1KGSq: Downloading m3u8 information
[CBS] k1h2PHncp7gfeLweU9z0Mm_feo_1KGSq: Downloading RTMP SMIL data
[CBS] k1h2PHncp7gfeLweU9z0Mm_feo_1KGSq: Downloading HLS_FPS SMIL data
[CBS] k1h2PHncp7gfeLweU9z0Mm_feo_1KGSq: Downloading m3u8 information
[CBS] k1h2PHncp7gfeLweU9z0Mm_feo_1KGSq: Downloading DASH_CENC SMIL data
ERROR: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/cbs.py", line 100, in _real_extract
    return self._extract_video_info(content_id)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/cbs.py", line 79, in _extract_video_info
    'Downloading %s SMIL data' % asset_type)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/theplatform.py", line 42, in _extract_theplatform_smil
    raise ExtractorError(error_element.attrib['abstract'], expected=True)
ExtractorError: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information
TV show episodes unable to download

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.

Some TV show episodes or complete seasons are unable to be downloaded. It's not every show or even all episodes of every season.

If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by mannweb** [comment]
Duplicate of what ticket exactly? I saw no duplicates and I saw none with any solutions.

**Comment by mannweb** [comment]
Found another ticket here with code I test and it works to get around issues on CBS.
Changed the block starting at line 77 in /usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/cbs.py from:

`            tp_formats, tp_subtitles = self._extract_theplatform_smil(
                update_url_query(tp_release_url, query), content_id,
                'Downloading %s SMIL data' % asset_type)
            formats.extend(tp_formats)
            subtitles = self._merge_subtitles(subtitles, tp_subtitles)
        self._sort_formats(formats)`

to this:

`            try:
                tp_formats, tp_subtitles = self._extract_theplatform_smil(
                    update_url_query(tp_release_url, query), content_id,
                    'Downloading %s SMIL data' % asset_type)
                formats.extend(tp_formats)
                subtitles = self._merge_subtitles(subtitles, tp_subtitles)
            except:
                print("ERROR!")
        self._sort_formats(formats)`

This gets around the errors which were preventing downloading. Thanks to a response in #15737

**Comment by rcached** [comment]
Is there a comparable solutions under Windows?  

I don't believe there is an option to manually edit .py extractors or a way to call a specific external extractor.  But please someone correct me if I am wrong there.

**Comment by patdavid** [comment]
To clarify on @mannweb's code, the original section:
```python
            tp_formats, tp_subtitles = self._extract_theplatform_smil(
                update_url_query(tp_release_url, query), content_id,
                'Downloading %s SMIL data' % asset_type)
```
should be replaced with:
```python
            try:
                tp_formats, tp_subtitles = self._extract_theplatform_smil(
                    update_url_query(tp_release_url, query), content_id,
                    'Downloading %s SMIL data' % asset_type)
                formats.extend(tp_formats)
                subtitles = self._merge_subtitles(subtitles, tp_subtitles)
            except:
                print("ERROR!")
```

Watch your spaces, make sure indents match with source lines being replaced as appropriate.
