### ISSUE TITLE
how to set the path of the downloaded file using ydl_opts?

### ISSUE THREAD

**Issue by siddht5** [rg3/youtube-dl#15834]
I want to know the dictionary pattern so that I could download videos to a specific path using ydl_opts.

`#dictionary object
ydl_opts ={
    'format': '720p/best',
    'postprocessors': [],
    'logger': MyLogger(),
    'progress_hooks': [my_hook],
     # need the dictionary argument/value for output path
    }`

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L162
