### ISSUE TITLE
some particular format youtube videos very slow download

### ISSUE THREAD

**Issue by korangu** [rg3/youtube-dl#15833]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.03.10
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

some videos are downloading at lowest speed  like 64kbps on a 1Gbps connection
example http://youtu.be/PmA7wmcsqtg -f 36

debug log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'36', u'--', u'PmA7wmcsqtg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] Python version 2.7.12 (CPython) - Linux-4.9.78-xxxx-std-ipv6-64-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.4.2-static, ffprobe 3.4.2-static
[debug] Proxy map: {}
[youtube] PmA7wmcsqtg: Downloading webpage
[youtube] PmA7wmcsqtg: Downloading video info webpage
[youtube] PmA7wmcsqtg: Extracting video information
[youtube] PmA7wmcsqtg: Downloading MPD manifest
[youtube] PmA7wmcsqtg: Downloading MPD manifest
[debug] Invoking downloader on u'https://r3---sn-25ge7nsl.googlevideo.com/videoplayback?fvip=3&pl=49&mv=m&mt=1520844158&ms=au%2Conr&ei=1D2mWpOHEoiNWaP2mLAM&id=o-AN5jfkd6PmYHsXNgvYOS4zYyaqpmRwR52cRX8Vgmy9kW&mn=sn-25ge7nsl%2Csn-4g5ednsr&mm=31%2C26&source=youtube&gir=yes&ip=2001%3A41d0%3A8%3A2d46%3A%3A&itag=36&dur=3458.472&mime=video%2F3gpp&ipbits=0&signature=6DD28E7E8907B8DD0F5AAD6ECB8A311B2DABDE48.14ED72E507E1045A2ADF8939D1EE3470F537C7CF&expire=1520865844&lmt=1517943753293831&requiressl=yes&clen=99320763&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&c=WEB&initcwndbps=1020000&key=yt6&ratebypass=yes'
[download] Resuming download at byte 3013632
[download] Destination: جلسه چهارم قانون آفرینش استاد عباس منش _ قدرت کلام 03-PmA7wmcsqtg.3gp
[download]   5.6% of 94.72MiB at 86.16KiB/s ETA 17:42
```

**Comment by dstftw** [comment]
Most likely an outdated version.
