### ISSUE TITLE
[YouTube] A video can't be downloaded

### ISSUE THREAD

**Issue by TrailingZeros** [rg3/youtube-dl#15831]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?has_verified=1&v=SabJF7y9TWE&oref=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DSabJF7y9TWE&app=desktop', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2018.03.10
[debug] Python version 2.7.14 (CPython) - Linux-4.13.0-36-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[youtube] SabJF7y9TWE: Downloading webpage
[youtube] SabJF7y9TWE: Downloading embed webpage
[youtube] SabJF7y9TWE: Refetching age-gated info webpage
ERROR: SabJF7y9TWE: YouTube said: <a href="http://www.youtube.com/watch?v=SabJF7y9TWE&feature=player_embedded" target="_blank">Watch this video on YouTube.</a>
Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "/home/a/.linuxbrew/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/home/a/.linuxbrew/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/home/a/.linuxbrew/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1620, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: SabJF7y9TWE: YouTube said: <a href="http://www.youtube.com/watch?v=SabJF7y9TWE&feature=player_embedded" target="_blank">Watch this video on YouTube.</a>
Playback on other websites has been disabled by the video owner.
<end of log>
```

---

### Producing links:
- https://www.youtube.com/watch?v=SabJF7y9TWE
- https://youtu.be/SabJF7y9TWE

---

### Description of your *issue*, suggested solution and other information

A video can't be downloaded because of embedding is not accepted.    
This could be bypassed by spoofing as IE9.

**Comment by dstftw** [comment]
>This could be bypassed by spoofing as IE9.

Incorrect.
You must provide account credentials to youtube-dl.
