### ISSUE TITLE
unable to download  video from cbsnews.com

### ISSUE THREAD

**Issue by sant527** [rg3/youtube-dl#15854]
$ youtube-dl --verbose --no-mtime --restrict-filenames --no-part --verbose --age-limit 50 --get-filename -f 'worst[height>=360][ext*=mp4]/worst/bestvideo[height>=360][ext=mp4]' -o '%(title)s_fmt_%(format_id)s.%(ext)s' https://www.cbsnews.com/video/inside-look-at-how-a-fertility-lab-protects-frozen-embryos/

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--no-mtime', '--restrict-filenames', '--no-part', '--verbose', '--age-limit', '50', '--get-filename', '-f', 'worst[height>=360][ext*=mp4]/worst/bestvideo[height>=360][ext=mp4]', '-o', '%(title)s_fmt_%(format_id)s.%(ext)s', 'https://www.cbsnews.com/video/inside-look-at-how-a-fertility-lab-protects-frozen-embryos/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.6.0 (CPython) - Linux-4.10.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://www.cbsnews.com/video/inside-look-at-how-a-fertility-lab-protects-frozen-embryos/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3127, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.cbsnews.com/video/inside-look-at-how-a-fertility-lab-protects-frozen-embryos/

**Comment by sant527** [comment]
so which is the duplicate question

**Comment by Vangelis66** [comment]
> so which is the duplicate question

In all likelihood, dupe of #15397 (still _open_)
If you're desperate to get that video, sniff your browser's traffic and look for m3u8 URLs... 
```
http://ipad-streaming.cbsnews.com/media/mpx/2018/03/13/1184547907609/0313_CTM_FertilityClinicFallout_Narula_1520713_phone.m3u8
```
... download the above with yt-dl:
```
[info] Available formats for 0313_CTM_FertilityClinicFallout_Narula_1520713_phone:
format code  extension  resolution note
53           mp4        audio only   53k , mp4a.40.2
224          mp4        400x224     224k , avc1.42001e, mp4a.40.2
364          mp4        400x224     364k , avc1.42001e, mp4a.40.2
614          mp4        512x288     614k , avc1.42001e, mp4a.40.2
914          mp4        640x360     914k , avc1.42001e, mp4a.40.2 (best)
```
> [debug] youtube-dl version **2018.02.11**

Latest version is **2018.03.10** ...
