### ISSUE TITLE
fails crunchyroll

### ISSUE THREAD

**Issue by acristobo** [rg3/youtube-dl#15856]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.crunchyroll.com/akame-ga-kill/episode-17-kill-the-curse-662265', '-o', 'E:\\000\\0-Descargados/%(series)s/%(title)s.%(ext)s', '--download-archive', 'E:\\000\\0-Descargados/listado.txt', '--cookies', 'cookies.txt', '-f', 'best[height=1080]', '--write-sub', '-k', '--sub-format', 'ass', '--sub-lang', 'esLA', '--recode-video', 'mp4', '--ffmpeg-location', '.\\bin\\']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.03.10
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81592-g2793ebd, ffprobe N-81592-g2793ebd, rtmpdump 2.3
[debug] Proxy map: {}
[Crunchyroll] 662265: Downloading webpage
ERROR: Unable to download webpage: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto (caused by ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\utils.py", line 989, in http_response
  File "C:\Python\Python34\lib\http\client.py", line 543, in read
  File "C:\Python\Python34\lib\http\client.py", line 629, in _readall_chunked
  File "C:\Python\Python34\lib\http\client.py", line 699, in _safe_read
  File "C:\Python\Python34\lib\socket.py", line 378, in readinto
```

---

### Description of your *issue*, suggested solution and other information

fails crunchyroll.
It worked fine until 2 weeks ago

**Comment by dstftw** [comment]
Network issue on your side.

**Comment by acristobo** [comment]
Sorry
but n I have problems to see from browser
and my connection is stable and works well.
Can it be some other problem?
