### ISSUE TITLE
instagram returning 0 videos when trying to download any user

### ISSUE THREAD

**Issue by LaticePrime** [rg3/youtube-dl#15858]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v https://www.instagram.com/prattprattpratt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.instagram.com/prattprattpratt']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.10
[debug] Python version 2.7.10 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[download] Downloading playlist: prattprattpratt
[instagram:user] prattprattpratt: Downloading page 1
[instagram:user] playlist prattprattpratt: Downloading 0 videos
[download] Finished downloading playlist: prattprattpratt
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Youtube is no longer downloading Instagram videos when you type: https://www.instagram.com/(user)
This will usually download all the videos from that user's account, but now it just returns 0 videos downloaded. Tried with many different user accounts that are not private, and have worked previously.

**Comment by Vrihub** [comment]
Instagram changed once again the tree structure of its JSON data.

The old one:

```
"user"
|
 -> "media"
    |
     -> "nodes"
        |
         -> (list of nodes)
            |
             -> ...node attributes, like "__typename" etc
```

...now became:

```
"graphql"
| 
 -> "user"
    |
     -> "edge_owner_to_timeline_media"
        |
         -> "edges"
            |
            -> (list of edges)
               |
                -> "node"
                   |
                    -> ...node attributes, like "__typename" etc
```

Please also note that some "node attributes" names changed too: e.g. `code` became `shortcode`, and there  might be some other changes.

Hope this helps

**Comment by Vrihub** [comment]
FYI, other recent instagram changes, and related workarounds are detailed here:

https://stackoverflow.com/questions/49265339/instagram-a-1-url-doesnt-allow-max-id/
https://stackoverflow.com/questions/49265013/instagram-a-1max-id-end-cursor-isnt-working-for-public-user-feeds/

**Comment by LaticePrime** [comment]
Still not fixed.

**Comment by dstftw** [comment]
It's not released.
