### ISSUE TITLE
[download] Got server HTTP error: HTTP Error 503: Service Unavailable.

### ISSUE THREAD

**Issue by YounoYouno** [rg3/youtube-dl#15876]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.14**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[download] Finance Lesson 12 by Martin Shkreli - Netflix analysis-HTM05cVOEDY.mp4 has already been downloaded
[download] 100% of 317.77MiB
[download] Downloading video 52 of 158
[youtube] LXPgFippaB8: Downloading webpage
[youtube] LXPgFippaB8: Downloading video info webpage
[youtube] LXPgFippaB8: Extracting video information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r5---sn-25ge7nld.googlevideo.com/videoplayback?ratebypass=yes&dur=5780.607&itag=22&pl                                         =22&ip=163.172.228.18&mm=31%2C29&mn=sn-25ge7nld%2Csn-25glenes&sparams=dur%2Cei%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cm                                         n%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cusequic%2Cexpire&fvip=1&ms=au%2Crdu&mt=1521105581&mv=u&id=o-ALkgu58cfCTu                                         FZlkvNDsSMOB1Wp4zvKhAwM9EfwIBjO6&usequic=no&signature=D1ED45712E43609E3552910552A022573651DD16.E1862D38A5D43EC31F60CE1881C7F98                                         630E78B5B&mime=video%2Fmp4&ipbits=0&key=yt6&lmt=3545519486905037110&ei=eTyqWqqdGIu6WZf0giA&source=youtube&c=WEB&expire=1521127                                         641&requiressl=yes'
[download] Resuming download at byte 73797
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 340, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 182, in establish_connection
    raise RetryDownload(err)
RetryDownload
```

---

### Description of your *issue*, suggested solution and other information

I am trying to download a entire channels videos, it went as far as video 52 till I ran into the error message of 'HTTP Error 503: Service Unavailable' and it gives up after 10 retries.

Am I doing something wrong, or is there any way to resolve this issue?

I have tried adding the --cookies parameter as I saw somewehere that it might help resolve the issue, for me it did not help.

The command is being executed as the following:

sudo youtube-dl --cookies jar --verbose https://www.youtube.com/channel/UC8gjB1PSXv_oAUSAQ16S0fA

Any help resolving this issue would be greatly appreciated! 

Thank you.

**Comment by YounoYouno** [comment]
I seem to have bypassed the error on this single video by using the -i flag, the actual reason why it gave this 503 with the video does not seem clear yet as the video is perfectly available in YouTube, but at least I was able to continue my indexation.

It might have had something to do with the size/length of the video, this video in particular was pretty long (11 hours) but exact information about this is not clear yet, as other videos of the same length and size are downloading without any issues.

Cheers.

**Comment by dstftw** [comment]
Format `best` you are requesting is not available for this video at Youtube side.
