### ISSUE TITLE
Any ideas on how to preload youtube-dl into RAM to save on disk i/o?

### ISSUE THREAD

**Issue by TheBoroer** [rg3/youtube-dl#15870]
### Make sure you are using the *latest* version
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When running multiple youtube-dl instances with a long queue of video, I'm noticing a lot of disk I/O and high CPU usage when using the `-J` argument to get JSON for a youtube video.

I'm pretty sure it's because of all the modules that have to be loaded every time the script runs. I'm thinking of ways to wrap youtube-dl in another python script that initializes it only once (and stores it all in RAM so when it needs to run again everything is already preloaded and ready to go). I feel like this could also speed up youtube-dl execution time greatly.

Does anyone have any suggestions on linux tools/commands or other scripts that can help me do this? I would hate to be re-inventing the wheel if I didn't have to 😋

**Comment by dstftw** [comment]
Just pass this long queue of videos as list of URLs to single youtube-dl instance so that modules will be loaded only once. Alternatively you can implement a simple daemon like https://github.com/jaimeMF/youtube-dl-api-server.

**Comment by TheBoroer** [comment]
@dstftw 
Passing a long queue of videos as a list of urls isn't possible because the videos are getting added on the fly (not at the time I launch the first youtube-dl instance).  Thanks for the daemon suggestion! I'll look into that 👍
