### ISSUE TITLE
Unable to download Facebook private video

### ISSUE THREAD

**Issue by yousef-kas133** [rg3/youtube-dl#15874]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl - v "https://www.facebook.com/yousef.leaue.65/videos/143454699809423/" --username **** --password ****
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/yousef.leaue.65/
videos/143454699809423/', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.4.4 (CPython) - Windows-2012ServerR2-6.3.9600
[debug] exe versions: ffmpeg N-90313-gb173e03536, ffprobe N-90313-gb173e03536
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 143454699809423: Downloading webpage
[facebook] 143454699809423: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Ma
ke sure you are using the latest version; type  youtube-dl -U  to update. Be sur
e to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph71axfm2\bu
ild\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph71axfm2\bu
ild\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph71axfm2\bu
ild\youtube_dl\extractor\facebook.py", line 422, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph71axfm2\bu
ild\youtube_dl\extractor\facebook.py", line 337, in _extract_from_url
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on
https://yt-dl.org/bug . Make sure you are using the latest version; type  youtub
e-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and inclu
de its complete output.
...
<end of log>
```

---

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

The problem is when i want to download a private video from facebook but its not working anymore, i tried to download a public video without logging in but it worked, please take a look at the log.

**Comment by yousef-kas133** [comment]
Could you please give me an specific time till it get fixed?

**Comment by dstftw** [comment]
No ETA.
