### ISSUE TITLE
Problem with background downloading

### ISSUE THREAD

**Issue by n00b12345** [rg3/youtube-dl#15885]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

I'm running youtube-dl on a Raspberry Pi. 

I have a bash script which enables me to run youtube-dl. It's nothing fancy, just has a simple youtube-dl command.

I am able to download videos perfectly when I run the bash script in the foreground.

However, whenever I run it in the background by initiating it through a cron job, I run into a problem. Everything other than the youtube-dl command gets executed. In order to debug, I tried adding -v to the command and exporting the output to a log file. Unfortunately the script completely skips the youtube-dl command and the log file remains empty.

Like I said, the exact same script runs perfectly when run from the foreground.

The issue I face is similar to [#10996](https://github.com/rg3/youtube-dl/pull/10996) and [#10706](https://github.com/rg3/youtube-dl/issues/10706).

A little help would really be great.

**Comment by dstftw** [comment]
Most likely youtube-dl is not in `PATH` for a user cron job is running on behalf of and you did not redirect stderr to a log file.

**Comment by n00b12345** [comment]
@dstftw thank you so much. Using /usr/local/bin/youtube-dl totally solved the issue. Thanks for helping.
