### ISSUE TITLE
Unsupported URL when downloading from wildcard udemy (https://*.udemy.com)

### ISSUE THREAD

**Issue by adita22** [rg3/youtube-dl#15883]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### When I use youtube-dl to download from 'https://udemy.com/' it works fine:
e.g. youtube-dl -u xxx -p xxx https://udemy.com/java-tutorial/learn/v4/overview

### When I use youtube-dl to download from 'https://*.udemy.com/' (in my case https://mycompany.udemy.com) I get unsupported URL error:
e.g. youtube-dl -u xxx -p xxx https://mycompany.udemy.com/java-tutorial/learn/v4/overview -v

### Getting the error: Unsupported URL: https://mycompany.udemy.com/java-tutorial/
command > D:\App Data\Youtube-dl\youtube-dl-bin>youtube-dl -u xxx -p xxx https://mycompany.udemy.com/java-tutorial/learn/v4/overview -v

output:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://mycompany.udemy.com/java-tutorial/learn/v4/overview', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-90315-gf706cdda56
[debug] Proxy map: {}
[generic] overview: Requesting header
[redirect] Following redirect to https://mycompany.udemy.com/java-tutorial/
[generic] java-tutorial: Requesting header
WARNING: Falling back on generic information extractor.
[generic] java-tutorial: Downloading webpage
[generic] java-tutorial: Extracting information
ERROR: Unsupported URL: https://mycompany.udemy.com/java-tutorial/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph71axfm2\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph71axfm2\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph71axfm2\build\youtube_dl\extractor\generic.py", line 3151, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://mycompany.udemy.com/java-tutorial/

**Comment by adita22** [comment]
https://gist.github.com/barbietunnie/8531d9c26cd1c0668e7278c7c4ba5853

**Comment by CesarBarros** [comment]
when I try to list the resolutions or download the videos to study offline, I get the following error:

`
<pre>
sh udemy-videos-download.sh
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-F', u'-o', u'./videos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s', u'https://www.udemy.com/react-redux-pt/', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.25
[debug] Python version 2.7.13 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in
[udemy:course] react-redux-pt: Downloading webpage
[udemy:course] 1076168: Downloading course curriculum
[download] Downloading playlist: React + Redux: Fundamentos e Duas Apps do ABSOLUTO ZERO!
[udemy:course] playlist React + Redux: Fundamentos e Duas Apps do ABSOLUTO ZERO!: Collected 196 video ids (downloading 196 of them)
[download] Downloading video 1 of 196
[udemy] Downloading login popup
[udemy] 6393446: Downloading webpage
[udemy] 6393446: Downloading lecture JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 360, in _real_extract
    self._sort_formats(formats, field_preference=('height', 'width', 'tbr', 'format_id'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1083, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
</pre>
`

Can someone help me?

**Comment by marzsv** [comment]
If there's anyone who can take charge of this issue I can provide a udemy for business account, so he/she can implement this feature.
