### ISSUE TITLE
Using -o "F:/Users/Appu/Videos/%(title)s.%(ext)s" command always results in a file named ext(s).mkv

### ISSUE THREAD

**Issue by Alphalpha007** [rg3/youtube-dl#15899]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
YouTube URL:https://www.youtube.com/watch?v=QwievZ1Tx-8
[debug] System config: []
[debug] User config: ['-o', 'F:/Users/Appu/Music/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo+bestaudio', '-o', 'F:/Users/Appu/Videos/(ext)s', 'https://www.youtube.com/watch?v=QwievZ1Tx-8']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-86330-gbd1179e, ffprobe N-86330-gbd1179e
[debug] Proxy map: {}
[youtube] TlK5cUS3K1o: Downloading webpage
[youtube] TlK5cUS3K1o: Downloading video info webpage
[youtube] TlK5cUS3K1o: Extracting video information
[youtube] {22} signature length 38.41, html5 player vflHDhBq1
[youtube] TlK5cUS3K1o: Downloading player https://www.youtube.com/watch?v=QwievZ1Tx-8/en_US/base.js
[youtube] {43} signature length 40.41, html5 player vflHDhBq1
[youtube] {18} signature length 40.41, html5 player vflHDhBq1
[youtube] {36} signature length 40.41, html5 player vflHDhBq1
[youtube] {17} signature length 40.41, html5 player vflHDhBq1
[youtube] {137} signature length 40.41, html5 player vflHDhBq1
[youtube] {248} signature length 40.41, html5 player vflHDhBq1
[youtube] {136} signature length 40.41, html5 player vflHDhBq1
[youtube] {247} signature length 40.41, html5 player vflHDhBq1
[youtube] {135} signature length 40.41, html5 player vflHDhBq1
[youtube] {244} signature length 40.41, html5 player vflHDhBq1
[youtube] {134} signature length 40.41, html5 player vflHDhBq1
[youtube] {243} signature length 40.41, html5 player vflHDhBq1
[youtube] {133} signature length 40.41, html5 player vflHDhBq1
[youtube] {242} signature length 40.41, html5 player vflHDhBq1
[youtube] {160} signature length 40.41, html5 player vflHDhBq1
[youtube] {278} signature length 40.41, html5 player vflHDhBq1
[youtube] {140} signature length 40.41, html5 player vflHDhBq1
[youtube] {171} signature length 40.41, html5 player vflHDhBq1
[youtube] {249} signature length 40.41, html5 player vflHDhBq1
[youtube] {250} signature length 40.41, html5 player vflHDhBq1
[youtube] {251} signature length 40.41, html5 player vflHDhBq1
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] F:\Users\Appu\Videos\(ext)s.mkv has already been downloaded and merged
Press any key to continue . . .
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

I'm using a batch file for the job.
This is the content:
```
@echo off
set /P dl=YouTube URL:
youtube-dl -f bestvideo+bestaudio -o "F:/Users/Appu/Videos/%(title)s.%(ext)s"  %dl%
pause
```
I can't figure out what's wrong.
Saw another issue just like this one at https://github.com/rg3/youtube-dl/issues/15730

**Comment by yan12125** [comment]
You need to use %%(ext)s in batch files.
