### ISSUE TITLE
Thumbnail filename extension gets ignored

### ISSUE THREAD

**Issue by MarcSchoendorf** [rg3/youtube-dl#15905]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--write-thumbnail', '--skip-download', '-o', '1.thumbnail', 'https://www.youtube.com/watch?v=APqFDseaF7o']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] APqFDseaF7o: Downloading webpage
[youtube] APqFDseaF7o: Downloading video info webpage
[youtube] APqFDseaF7o: Extracting video information
[debug] Default format spec: best/bestvideo+bestaudio
[youtube] APqFDseaF7o: Downloading thumbnail ...
[youtube] APqFDseaF7o: Writing thumbnail to: 1.jpg

### Description of your *issue*, suggested solution and other information

I want to decide which extensions  gets used for the thumbnail.  But when I put -o image.thumbnail in the command, the created file always will be image.jpg or image.png. How can I overwrite the filename extension?

**Comment by dstftw** [comment]
Short: you can't. You'll always get the actual thumbnail's extension. Forcing extensions is also completely senseless since this won't change actual image format anyway.

**Comment by MarcSchoendorf** [comment]
No this is actual quite important. I'm write a gui program which offers a thumbnail preview. When the file format can alway be different I always need to search the whole directory. With a pseudo file extension like .thumbnail I can let my ImageHandler decide which format it is. I'm sure this wouldn't be much work to do, since the %(ext)s operator is already implemented, so just deactivate it by default?
