### ISSUE TITLE
download speed of url youtube-dl returns is very slow

### ISSUE THREAD

**Issue by umlx5h** [rg3/youtube-dl#15912]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.14**

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--extract-audio', u'-g', u'https://www.youtube.com/watch?v=dQw4w9WgXcQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 2.7.14 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
https://r6---sn-3pm7sn7d.googlevideo.com/videoplayback?expire=1521469765&gcr=jp&ei=5XSvWrLAKou3gQOh04qoAw&requiressl=yes&itag=251&keepalive=yes&initcwndbps=1402500&source=youtube&clen=3438483&dur=212.061&ipbits=0&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&lmt=1518413814901302&mv=m&mt=1521448063&mm=31%2C26&fvip=4&ms=au%2Conr&pl=19&id=o-ANc6M-7es1U_ybk77INpHx-UBPu29oeLBUdfu508psBU&mime=audio%2Fwebm&gir=yes&c=WEB&mn=sn-3pm7sn7d%2Csn-oguelnle&ip=153.200.204.206&key=yt6&signature=3C110F464F336275AAB37309E69EB97DE5962E94.916C77A7815EE4CBF4AA43011AB023A58ADA7453&ratebypass=yes
```

---

I want to create API server that responses youtube audio URL to let client download youtube audio file directly.  
So I get youtube audio file URL using the following command.

    youtube-dl --extract-audio -g "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

 
  
And I got following audio url.  
  

    https://r6---sn-3pm7sn7d.googlevideo.com/videoplayback?gcr=jp&requiressl=yes&fvip=4&ei=smqvWqbHL8fkqQGgrKOQBg&lmt=1518413814901302&mime=audio%2Fwebm&mv=m&c=WEB&expire=1521467154&source=youtube&keepalive=yes&pl=19&itag=251&dur=212.061&initcwndbps=1396250&clen=3438483&ipbits=0&mn=sn-3pm7sn7d%2Csn-3pm76n76&mm=31%2C29&id=o-APcnop1e4uRZDEsrYtj_pmV3lsMsCTO4a0lmk4srZ4gm&gir=yes&mt=1521445365&ms=au%2Crdu&key=yt6&ip=153.200.204.206&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&signature=E2078C6E348D3263DCDBF824190BC1BF2A938533.51541F2E85AFC8F3A6C0A142B37774DE16071692&ratebypass=yes 

And I opened this url in chrome and download it, but it takes about fifty seconds, about 60 kb/s speed.  
Using wget command, results are same.  

    videoplayback?gcr=j 100%[===================>]   3.28M  64.7KB/s    in 52s

But for some reason, Without -g option, Download can be done immediately.  
 It takes about 1-2 seconds.   

    youtube-dl --extract-audio "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

Why is there a difference in speed like this?  
Both download url are same?

**Comment by Hrxn** [comment]
Expected.

youtube-dl uses downloading based on separate chunks to work around the rate limitation imposed by YouTube.
