### ISSUE TITLE
Pornhub private videos

### ISSUE THREAD

**Issue by Showster88** [rg3/youtube-dl#15921]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

I am unable to download private videos from Pornhub. I am a beginner so I will do my best to describe my problem. 

I am currently using the following instructions that I read about in your FAQ section regarding authentication (username and password are examples):

C:\Users\Username>youtube-dl -u, --username 123 -p, --password 321 https://www.pornhub.com/view_video.php?viewkey=ph59a5513ce257e&pkey=23117731

When I type these instructions into the command prompt (Windows 10, Version 1709) I have the following response: 

PornHub said: Sorry, but this video is private. You must be friends with abhater to view this video. ph59a5513ce257e is not recognized as an internal or external command, operable program or batch file.

As  I mentioned earlier, I am not an experienced programmer but would greatly appreciate some input from the more experienced members of github.

Thanks.

**Comment by dstftw** [comment]
Use cookies from browser.

**Comment by Showster88** [comment]
How do i do that? Thanks.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl
