### ISSUE TITLE
Bitchute embed urls not working

### ISSUE THREAD

**Issue by negutron** [rg3/youtube-dl#15922]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.14**

 $ youtube-dl --version
2018.03.14

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

youtube-dl -v https://www.bitchute.com/embed/lbb5G1hjPhw/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.bitchute.com/embed/lbb5G1hjPhw/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 2.7.12 (CPython) - Linux-4.8.0-53-generic-x86_64-with-LinuxMint-18.2-sonya
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] lbb5G1hjPhw: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lbb5G1hjPhw: Downloading webpage
[generic] lbb5G1hjPhw: Extracting information
ERROR: Unsupported URL: https://www.bitchute.com/embed/lbb5G1hjPhw/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2222, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 11, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3151, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.bitchute.com/embed/lbb5G1hjPhw/

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video:  https://www.bitchute.com/embed/lbb5G1hjPhw/
- Single video: https://www.bitchute.com/embed/msVA0ajknjA/
- Playlist: https://www.bitchute.com/channel/stefanmolyneux/
- Playlist: https://www.bitchute.com/feeds/rss/channel/corbettreport/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Hello.  First of all, youtube-dl is the most amazing software.  I use it every day and I am VERY thankful for your work on this project.  It is amazing and competent, reliable and fast

My request is very simple: I'd like youtube-dl to add support for BITCHUTE which is an alternative youtube site that is allegedly censorship resistant.  They have recently added RSS for the channels, using the convention of preceeding the channel with /feeds/rss/ 

example video channel: https://www.bitchute.com/channel/corbettreport/
example video channel's RSS feed: https://www.bitchute.com/feeds/rss/channel/corbettreport/

Thank you for considering it!

**Comment by negutron** [comment]
Is support request search broken?  I didn't find any bitchute related requests before submitting this

but it was labeled duplicate

**Comment by dstftw** [comment]
Search works fine.
