### ISSUE TITLE
Unable to download JSON metadata

### ISSUE THREAD

**Issue by explus4host** [rg3/youtube-dl#15943]
D:\p>youtube-dl.exe --verbose --cookies D:\p\Plural\cookies.txt -o "D:\p\Plural\%(playlist_index)s - %(title)s.%(ext)s" --min-sleep-interval 31 --max-sleep-interval 32 https://app.pluralsight.com/library/courses/aws-security-fundamentals/table-of-contents --playlist-start 1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies', 'D:\\p\\Plural\\cookies.txt', '-o', 'D:\\p\\Plural\\%(playlist_index)s - %(title)s.%(ext)s', '--min-sleep-interval', '31', '--max-sleep-interval', '32', 'https://app.pluralsight.com/library/courses/aws-security-fundamentals/table-of-contents', '--playlist-start', '1']
[debug] Encodings: locale cp1256, fs mbcs, out cp720, pref cp1256
[debug] youtube-dl version 2018.03.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] aws-security-fundamentals: Downloading course JSON
[download] Downloading playlist: AWS Security Fundamentals
[pluralsight:course] playlist AWS Security Fundamentals: Collected 32 video ids (downloading 32 of them)
[download] Downloading video 1 of 32
[pluralsight] aws-security-fundamentals-m0-0: Downloading course JSON
[pluralsight] aws-security-fundamentals-m0-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] aws-security-fundamentals-m0-0: Waiting for 5 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://vid20.pluralsight.com/clips/resolution/4650ae6d-5526-4a3e-b3b1-c1a759aa2f48/current/mp4/1280x720.mp4?vd3RpDl_hubVbW9_oZdtjTU4-WuMEf3wIHur8XK_y1cpNdvMlZmb4W0nC3pUZJFLXSDjUVLM2rVsSjUPRS0OdB-qgkY0m1WNKAiu0EG5Cp4TpZf36iU9f5QcmS4I0GypYL7TGv0pi9L53vrjG5bR76LMKyy55FDvmAo5qxkaRecfwrCZOWMFqYWYpdJJ'
[download] D:\p\Plural\01 - Course Overview.mp4 has already been downloaded
[download] 100% of 3.26MiB
[download] Downloading video 2 of 32
[pluralsight] aws-security-fundamentals-m1-0: Downloading course JSON
[pluralsight] aws-security-fundamentals-m1-0: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] aws-security-fundamentals-m1-0: Waiting for 3 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\pluralsight.py", line 326, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\common.py", line 1083, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I've tried to reinstall it, export cookies from the beginning, clear cache and cookies .. but still same issue

**Comment by vincentSTO** [comment]
Just remove the table-content part and you'll be fine. 

e.g. https://app.pluralsight.com/library/courses/aws-security-fundamentals

**Comment by explus4host** [comment]
Same issue !

D:\p>youtube-dl.exe --verbose --cookies D:\p\Plural\cookies.txt -o "D:\p\Plural\%(playlist_index)s - %(title)s.%(ext)s" --min-sleep-interval 31 --max-sleep-interval 32 https://app.pluralsight.com/library/courses/aws-developer-introduction-aws-lambda/ --playlist-start 1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies', 'D:\\p\\Plural\\cookies.txt', '-o', 'D:\\p\\Plural\\%(playlist_index)s - %(title)s.%(ext)s', '--min-sleep-interval', '31', '--max-sleep-interval', '32', 'https://app.pluralsight.com/library/courses/aws-developer-introduction-aws-lambda/', '--playlist-start', '1']
[debug] Encodings: locale cp1256, fs mbcs, out cp720, pref cp1256
[debug] youtube-dl version 2018.03.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] aws-developer-introduction-aws-lambda: Downloading course JSON
[download] Downloading playlist: AWS Developer - An Introduction to AWS Lambda
[pluralsight:course] playlist AWS Developer - An Introduction to AWS Lambda: Collected 25 video ids (downloading 25 of them)
[download] Downloading video 1 of 25
[pluralsight] aws-developer-introduction-aws-lambda-m0-0: Downloading course JSON
[pluralsight] aws-developer-introduction-aws-lambda-m0-0: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] aws-developer-introduction-aws-lambda-m0-0: Waiting for 2 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\pluralsight.py", line 326, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\common.py", line 1083, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This course is not free. Can you watch it in browser in the first place?

**Comment by explus4host** [comment]
of course, I tried to download courses that I already downloaded for
testing but still same issue
and I've premium subscription












*--------*
*With best wishes,*
*Website: explus4host.com <http://WwW.Explus4Host.CoM>*
*Mobile: 002-01010102347*

*FB: https://www.fb.com/ExpCompany <https://www.facebook.com/ExpCompany>*
*Twitter: https://twitter.com/ExpCompany <https://twitter.com/ExpCompany>*

**Comment by dstftw** [comment]
Does it work if you explicitly provide account credentials?

**Comment by explus4host** [comment]
Sure, no problem just send me your email












*--------*
*With best wishes,*
*Website: explus4host.com <http://WwW.Explus4Host.CoM>*
*Mobile: 002-01010102347*

*FB: https://www.fb.com/ExpCompany <https://www.facebook.com/ExpCompany>*
*Twitter: https://twitter.com/ExpCompany <https://twitter.com/ExpCompany>*

**Comment by dstftw** [comment]
I mean if you provide it to youtube-dl instead of cookies.

**Comment by explus4host** [comment]
I'm not sure If I fully understand but can you send me the code for testing
?












*--------*
*With best wishes,*
*Website: explus4host.com <http://WwW.Explus4Host.CoM>*
*Mobile: 002-01010102347*

*FB: https://www.fb.com/ExpCompany <https://www.facebook.com/ExpCompany>*
*Twitter: https://twitter.com/ExpCompany <https://twitter.com/ExpCompany>*

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#authentication-options

**Comment by explus4host** [comment]
so the code should be like that

youtube-dl.exe -u username -p password --verbose --cookies
D:\p\Plural\cookies.txt -o "D:\p\Plural\%(playlist_index)s -
%(title)s.%(ext)s" --min-sleep-interval 31 --max-sleep-interval 32
https://app.pluralsight.com/library/courses/aws-developer-introduction-aws-lambda/
--playlist-start 1

and of course I'll replace username & pass












*--------*
*With best wishes,*
*Website: explus4host.com <http://WwW.Explus4Host.CoM>*
*Mobile: 002-01010102347*

*FB: https://www.fb.com/ExpCompany <https://www.facebook.com/ExpCompany>*
*Twitter: https://twitter.com/ExpCompany <https://twitter.com/ExpCompany>*

**Comment by explus4host** [comment]
It's working, so the problem with the cookies from the beginning ?, so will
u fix the cookies issue soon ?












*--------*
*With best wishes,*
*Website: explus4host.com <http://WwW.Explus4Host.CoM>*
*Mobile: 002-01010102347*

*FB: https://www.fb.com/ExpCompany <https://www.facebook.com/ExpCompany>*
*Twitter: https://twitter.com/ExpCompany <https://twitter.com/ExpCompany>*

**Comment by dstftw** [comment]
Most likely your cookies are expired.

**Comment by explus4host** [comment]
stopped again :(

[download] Destination: D:\p\Plural\04 - Module Overview.mp4
[download] 100% of 8.84MiB in 00:19
[download] Downloading video 5 of 32
[pluralsight] aws-security-fundamentals-m1-3: Downloading course JSON
[pluralsight] aws-security-fundamentals-m1-3: Downloading JSON metadata
ERROR: Unable to download JSON metadata: <urlopen error [Errno 11001]
getaddrinfo failed> (caused by URLError(gaierror(11001, 'getaddrinfo
failed'),))
  File "C:\Users\dst\AppData\Roaming\Build
archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\common.py",
line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build
archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\YoutubeDL.py", line
2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build
archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\utils.py", line 1101,
in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open












*--------*
*With best wishes,*
*Website: explus4host.com <http://WwW.Explus4Host.CoM>*
*Mobile: 002-01010102347*

*FB: https://www.fb.com/ExpCompany <https://www.facebook.com/ExpCompany>*
*Twitter: https://twitter.com/ExpCompany <https://twitter.com/ExpCompany>*

**Comment by dstftw** [comment]
The last one is due to DNS issues on your side.
