### ISSUE TITLE
Can't download Video @Facebook: filename too long

### ISSUE THREAD

**Issue by s501343** [rg3/youtube-dl#15942]
youtube-dl --verbose  https://www.facebook.com/kingjerentertainment/videos/1690064417753512/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/kingjerentertainment/videos/1690064417753512/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.20
[debug] Python version 2.7.12 (CPython) - Linux-4.10.0-38-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[facebook] 1690064417753512: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://video.fsyd4-1.fna.fbcdn.net/v/t42.1790-2/10000000_221065421802566_6737851218296569856_n.mp4?_nc_cat=0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjRfaHE1X2ZyYWdfMl92aWRlbyJ9&oh=4f72567e4004cd0780f1b4037d06f786&oe=5AB26866'
ERROR: unable to open for writing: [Errno 36] File name too long: '\xe3\x80\x90\xe6\xb8\xa3\xe6\x89\x93\xe9\x80\xb1\xe4\xb8\x89\xe5\xa5\xbd\xe6\x88\xb2\xe6\xb4\xbe\xef\xbc\x9a\xe7\x9c\x8b\xe4\xb8\x8d\xe8\xa6\x8b\xe7\x9a\x84\xe5\xa4\xa7\xe8\xbb\x8d\xe3\x80\x91\xef\xbc\x88\xe7\xa8\x8b\xe6\x9d\xb1\xe3\x80\x81\xe9\x84\xad\xe7\xa7\x80\xe6\x96\x87 \xe4\xb8\xbb\xe6\xbc\x94\xef\xbc\x89  \xe5\xa4\xa7\xe5\xae\xb6\xe9\x83\xbd\xe7\x9f\xa5\xe5\xa4\xa7\xe8\xbb\x8d\xe9\x9a\xbb\xe7\x9c\xbc\xef\xbc\x8c\xe8\x83\xbd\xe5\xa4\xa0\xe7\x9d\x87\xe7\xa9\xbf\xe4\xb8\x96\xe7\x95\x8c\xe4\xb8\x8a\xe6\x89\x80\xe6\x9c\x89\xe5\x98\xa2\xef\xbc\x8c\xe9\x80\xa3\xe4\xbd\xa0\xe6\x9c\x89\xe7\x84\xa1\xe8\x91\x97\xe5\xba\x95\xe8\xa4\xb2\xe9\x83\xbd\xe7\x9d\x87\xe5\xbe\x97\xe7\xa9\xbf\xe2\x80\xa6 \xe4\xbd\x86\xe4\xba\xba\xe6\x9c\x89\xe4\xb8\x89\xe8\xa1\xb0\xe5\x85\xad\xe6\x97\xba\xef\xbc\x8c\xe6\x9c\x89\xe9\x82\x8a\xe5\x80\x8b\xe6\x9c\x83\xe4\xbc\xb0\xe5\x88\xb0\xe4\xbd\xa2...-1690064417753512.f221065415135900v.mp4.part'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 249, in download
    ctx.tmpfilename, ctx.open_mode)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 457, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
IOError: [Errno 36] File name too long: '\xe3\x80\x90\xe6\xb8\xa3\xe6\x89\x93\xe9\x80\xb1\xe4\xb8\x89\xe5\xa5\xbd\xe6\x88\xb2\xe6\xb4\xbe\xef\xbc\x9a\xe7\x9c\x8b\xe4\xb8\x8d\xe8\xa6\x8b\xe7\x9a\x84\xe5\xa4\xa7\xe8\xbb\x8d\xe3\x80\x91\xef\xbc\x88\xe7\xa8\x8b\xe6\x9d\xb1\xe3\x80\x81\xe9\x84\xad\xe7\xa7\x80\xe6\x96\x87 \xe4\xb8\xbb\xe6\xbc\x94\xef\xbc\x89  \xe5\xa4\xa7\xe5\xae\xb6\xe9\x83\xbd\xe7\x9f\xa5\xe5\xa4\xa7\xe8\xbb\x8d\xe9\x9a\xbb\xe7\x9c\xbc\xef\xbc\x8c\xe8\x83\xbd\xe5\xa4\xa0\xe7\x9d\x87\xe7\xa9\xbf\xe4\xb8\x96\xe7\x95\x8c\xe4\xb8\x8a\xe6\x89\x80\xe6\x9c\x89\xe5\x98\xa2\xef\xbc\x8c\xe9\x80\xa3\xe4\xbd\xa0\xe6\x9c\x89\xe7\x84\xa1\xe8\x91\x97\xe5\xba\x95\xe8\xa4\xb2\xe9\x83\xbd\xe7\x9d\x87\xe5\xbe\x97\xe7\xa9\xbf\xe2\x80\xa6 \xe4\xbd\x86\xe4\xba\xba\xe6\x9c\x89\xe4\xb8\x89\xe8\xa1\xb0\xe5\x85\xad\xe6\x97\xba\xef\xbc\x8c\xe6\x9c\x89\xe9\x82\x8a\xe5\x80\x8b\xe6\x9c\x83\xe4\xbc\xb0\xe5\x88\xb0\xe4\xbd\xa2...-1690064417753512.f221065415135900v.mp4.part'

marklin@marklinux /data/srcBackup/youtube-dl $ Failed to open VDPAU backend libvdpau_i965.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_i965.so: cannot open shared object file: No such file or directory

**Comment by superclarkk** [comment]
@dstftw This bug still exists.

You have closed two of these issues without linking to the original ticket. Can you provide the ticket number, please?
