### ISSUE TITLE
CBC downloads no longer work

### ISSUE THREAD

**Issue by zang74** [rg3/youtube-dl#15945]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.20*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
/usr/local/bin/youtube-dl --verbose -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo[ext=mkv]+bestaudio[ext=m4a]/bestvideo+bestaudio https://watch.cbc.ca/schitts-creek/season-4/episode-9/38e815a-00db239c3f2

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo[ext=mkv]+bestaudio[ext=m4a]/bestvideo+bestaudio', u'https://watch.cbc.ca/schitts-creek/season-4/episode-9/38e815a-00db239c3f2']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.20
[debug] Python version 2.7.13 (CPython) - Linux-4.9.80-v7+-armv7l-with-debian-9.4
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1
[debug] Proxy map: {}
[debug] Using fake IP 99.231.126.80 (CA) as X-Forwarded-For.
[cbc.ca:watch] 38e815a-00db239c3f2: Downloading XML
ERROR: Unable to download XML: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 519, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2199, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://watch.cbc.ca/schitts-creek/season-4/episode-9/38e815a-00db239c3f2
- Single video: https://watch.cbc.ca/the-detectives/season-1/episode-7/38e815a-00dee3fe29b
- Playlist: https://watch.cbc.ca/the-detectives/season-1/2e8c34bb-f55c-4017-8630-02d3ae3cb2bb

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Youtube-dl worked with the CBC site are recently last week. Since this update, it no longer works. I can't verify if something has changed on the CBC site, but the site design and layout has remained the same. It's currently running JWPlayer 7.12.2 for playback.

**Comment by zang74** [comment]
I've checked this on my Mac, and it works with the current version. But even after a reinstall (via pip) and a restart, I still get the XML error on my Raspbian Pi3.

**Comment by dstftw** [comment]
`--rm-cache-dir`.

**Comment by zang74** [comment]
That did it. Thank you.
