### ISSUE TITLE
"ERROR: batch file could not be read", when I call the CLI without specifying a path to the executable file

### ISSUE THREAD

**Issue by roman90sv** [rg3/youtube-dl#15970]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### Description of your *issue*, suggested solution and other information

I have added directory to PATH Environment Variable to avoid specifying a path to youtube-dl in the CLI.
But, when I call the CLI without specifying a path to the executable file, batch.txt could not be read.
See attached screenshot
![1](https://user-images.githubusercontent.com/35082918/37837238-c8be8bf0-2ec5-11e8-8ef3-26784080a6f7.PNG)

**Comment by dstftw** [comment]
So what? There is no `batch.txt` in `C:\Windows\system32` that is clearly stated in the error message. `PATH` have nothing to do with arguments and their values passed to youtube-dl.

**Comment by dstftw** [comment]
If it will look in the same directory then it would be impossible to specify paths relative to a current directory. It's a standard and idiomatic behavior.
