### ISSUE TITLE
Unable to download Vimeo private / password protected videos

### ISSUE THREAD

**Issue by emma-goldman** [rg3/youtube-dl#15980]
Posted here and got a short unconstructive response:

https://github.com/rg3/youtube-dl/issues/7169

I can log in to the private video in my browser (using the same login info I copy pasted into yt-dl) and stream the video but I am not able to download the video using yt-dl so the answer "wrong login info" does not apply. @dstftw 

Previous post below:

I'm encountering this issue again, verbose output below:

`PS C:\Users\Xyz\Videos> youtube-dl https://vimeo.com/xxxxxxxx --video-password xxx -u 'PRIVATE' --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://vimeo.com/xxxxxxxx', u'--video-password', u'PRIVATE', u'-u', u'PRIVATE', u'--verbose']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.03.03
[debug] Python version 2.7.14 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[vimeo] Logging in
ERROR: Wrong login info: HTTP Error 418: I'm a teapot (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _request_webpage
return self._downloader.urlopen(url_or_request)
File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2199, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "c:\python27\lib\urllib2.py", line 435, in open
response = meth(req, response)
File "c:\python27\lib\urllib2.py", line 548, in http_response
'http', request, response, code, msg, hdrs)
File "c:\python27\lib\urllib2.py", line 473, in error
return self._call_chain(*args)
File "c:\python27\lib\urllib2.py", line 407, in _call_chain
result = func(*args)
File "c:\python27\lib\urllib2.py", line 556, in http_error_default
raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

`or

    PS C:\Users\Xyz\Videos> youtube-dl https://vimeo.com/xxxxxxxx -p I5O2013 -u PRIVATE --verbose
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: [u'https://vimeo.com/xxxxxxxx', u'-p', u'PRIVATE', u'-u', u'PRIVATE', u'--verbose']
    [debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
    [debug] youtube-dl version 2018.03.03
    [debug] Python version 2.7.14 (CPython) - Windows-10-10.0.16299
    [debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
    [debug] Proxy map: {}
    [vimeo] Logging in
    ERROR: Wrong login info: HTTP Error 418: I'm a teapot (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _request_webpage
    return self._downloader.urlopen(url_or_request)
    File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2199, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
    File "c:\python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
    File "c:\python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
    File "c:\python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
    File "c:\python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
    File "c:\python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

or without -u at all:

`PS C:\Users\Xyz\Videos> youtube-dl https://vimeo.com/xxxxxxxx -p xxxxxxx --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://vimeo.com/xxxxxxxx', u'-p', u'PRIVATE', u'--verbose']
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: account username missing`

Tried updating to no avail.

Cheers

**Comment by dstftw** [comment]
Once again: login or/and password you provide to youtube-dl **is not correct**.

**Comment by emma-goldman** [comment]
I believe the wrong login info message stems from that there is no user login to provide when accessing a password protected film, you just provide the password in a prompt.

`PS C:\Users\Xyz\Videos> youtube-dl https://vimeo.com/xxxxxxxx -p xxxxxxx --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://vimeo.com/xxxxxxxx', u'-p', u'PRIVATE', u'--verbose']
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: account username missing`

I then tried with "PRIVATE" as the -u since the previous issue had that as -u in their verbose output and received the wrong login info message.

**Comment by emma-goldman** [comment]
have a go yourself 

 youtube-dl https://vimeo.com/64138231 -p I5O2013 --verbose

**Comment by dstftw** [comment]
Ugh. If you download password protected video provide **`--video-password`** not account credentials.

**Comment by emma-goldman** [comment]
Thank you for your constructive answer!

**Comment by 1RedOne** [comment]
When the Vimeo Domain is detected, it would be useful to display this in the error text if someone tries to use -password

For Vimeo, use the --video-password parameter instead

Like it?  I'll PR it.
