### ISSUE TITLE
Can't download on Weather.com with DLNow

### ISSUE THREAD

**Issue by dkok517** [rg3/youtube-dl#15982]
ERROR: Unable to extract drupal settings; please report this issue on https://yt.dl.org/bug.
![dlnow](https://user-images.githubusercontent.com/37758386/37870515-b0eba5c0-2f9d-11e8-8858-a6b84f005d01.PNG)

Hoping someone can help!
Thanks.

**Comment by dstftw** [comment]
This is youtube-dl issue tracker not DLNow.
