### ISSUE TITLE
[PBS] Downloading lowest quality

### ISSUE THREAD

**Issue by bchandos** [rg3/youtube-dl#1598]
I tried several PBS videos and each time, the lowest quality stream was downloaded (usually 284p). "-f" and "--max-quality" did nothing. Looking at the extractor, it gets the URL from "alternate_encoding" which in the JSON, calls a file with eeid "mp4-baseline-16x9". I believe "recommended_encoding" should be used as it calls eeid "hls-2500k-16x9" which I believe to be the highest resolution stream. Unfortunately, I lack even the basic skills to test this!

Example URL: http://video.pbs.org/video/2365089043/
Relevant JSON: http://video.pbs.org/videoInfo/2365089043/?format=json

Edit: I should note that web player offers a range of quality streams, from 720p down. The URL provided by "alternate_coding" resolves directly to a video stream, while the URL provided by "recommended_encoding" resolves in a m3u8 file, and lists a mime-type of "application/x-mpegURL".

**Comment by dstftw** [comment]
PBS HD is supported in the latest version.
