### ISSUE TITLE
Homebrew: latest version not automatically linked

### ISSUE THREAD

**Issue by tdegeus** [rg3/youtube-dl#15995]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)

---

It would be great if the Homebrew installation would automatically link the latest version. 

This done for almost all, if not all, other apps. For example, for Python3:

```bash
$ ls -l `which python3`
lrwxr-xr-x  1 tdegeus  admin  36 Mar 12 09:09 /usr/local/bin/python3 -> ../Cellar/python/3.6.4_4/bin/python3
```

I.e. a link is created in the usual location (`/usr/local/bin`) that points to the latest version in the `Cellar`. 

For `youtube-dl` the desired behavior would be

```bash
$ ls -l `which youtube-dl`
lrwxr-xr-x  ... /usr/local/bin/youtube-dl -> ../Cellar/youtube-dl/2018.03.20/bin/youtube-dl
```

which updates with every update.

**Comment by dstftw** [comment]
Address this to homebrew.

**Comment by tdegeus** [comment]
That was kind of naive of me... It was not done before, and somehow I never rechecked. Thanks in any case!
