### ISSUE TITLE
Inexistent URL output

### ISSUE THREAD

**Issue by satnatantas** [rg3/youtube-dl#15996]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.20*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.03.20
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

XP x64 SP2, ytdl 2018.03.20

```
youtube-dl.exe -v --no-check-certificate -g -f 'bestvideo[ext=webm][height<=720]+bestaudio[ext=webm]/bestvideo[height<=720]+bestaudio/best[height<=720]/bestvideo+bestaudio/best' https://www.youtube.com/watch?v=1FUVTXAAOV4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-check-certificate', '-g', '-f', 'bestvideo[ext=webm][height<=720]+bestaudio[ext=webm]/bestvideo[height<=720]+bestaudio/best[height<=720]/bestvideo+bestaudio/best', 'https://www.youtube.com/watch?v=1FUVTXAAOV4']
[debug] Encodings: locale cp1251, fs mbcs, out cp1251, pref cp1251
[debug] youtube-dl version 2018.03.20
[debug] Python version 3.4.4 (CPython) - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-50911-g9efcfbe
[debug] Proxy map: {}
https://r7---sn-gvnuxaxjvh-c35z.googlevideo.com/videoplayback/id/d455154d7000395e/itag/298/source/yt_otf/requiressl/yes/nh/,IgpwcjAzLnN2bzA1KgkxMjcuMC4wLjE/pcm2cms/yes/pl/19/ei/rLO4WryyA-vV7ASd5Yr4DQ/initcwndbps/1515000/mm/31,29/mn/sn-gvnuxaxjvh-c35z,sn-n8v7snez/ms/au,rdu/mv/m/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1520495412485940/fvip/8/mt/1522054008/ip/90.154.69.216/ipbits/0/expire/1522075660/sparams/ip,ipbits,expire,id,itag,source,requiressl,nh,pcm2cms,pl,ei,initcwndbps,mm,mn,ms,mv,ratebypass,mime,otfp,otf,lmt/signature/828B52BD3E8070F71B9A9A1260977441D17D09C7.1FE2F735920C446AEF047AAB5B803808DD6959DF/key/dg_yt0/
https://r7---sn-gvnuxaxjvh-c35z.googlevideo.com/videoplayback/id/d455154d7000395e/itag/140/source/youtube/requiressl/yes/nh/,IgpwcjAzLnN2bzA1KgkxMjcuMC4wLjE/pcm2cms/yes/pl/19/ei/rLO4WryyA-vV7ASd5Yr4DQ/initcwndbps/1515000/mm/31,29/mn/sn-gvnuxaxjvh-c35z,sn-n8v7snez/ms/au,rdu/mv/m/ratebypass/yes/mime/audio%2Fmp4/otfp/1/gir/yes/clen/9348168/lmt/1520495297780942/dur/588.114/fvip/8/mt/1522054008/ip/90.154.69.216/ipbits/0/expire/1522075660/sparams/ip,ipbits,expire,id,itag,source,requiressl,nh,pcm2cms,pl,ei,initcwndbps,mm,mn,ms,mv,ratebypass,mime,otfp,gir,clen,lmt,dur/signature/3374D51AA73F94679560EE426EBFA7E686F70B85.413711FB113816E0FE922DB83638E21540399BBC/key/dg_yt0/
```

Video URL yields 404.
Audio URL is fine.

```
youtube-dl.exe -v --no-check-certificate -f 'bestvideo[ext=webm][height<=720]+bestaudio[ext=webm]/bestvideo[height<=720]+bestaudio/best[height<=720]/bestvideo+bestaudio/best' https://www.youtube.com/watch?v=1FUVTXAAOV4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-check-certificate', '-f', 'bestvideo[ext=webm][height<=720]+bestaudio[ext=webm]/bestvideo[height<=720]+bestaudio/best[height<=720]/bestvideo+bestaudio/best', 'https://www.youtube.com/watch?v=1FUVTXAAOV4']
[debug] Encodings: locale cp1251, fs mbcs, out cp1251, pref cp1251
[debug] youtube-dl version 2018.03.20
[debug] Python version 3.4.4 (CPython) - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-50911-g9efcfbe
[debug] Proxy map: {}
[youtube] 1FUVTXAAOV4: Downloading webpage
[youtube] 1FUVTXAAOV4: Downloading video info webpage
[youtube] 1FUVTXAAOV4: Extracting video information
[youtube] 1FUVTXAAOV4: Downloading MPD manifest
[youtube] 1FUVTXAAOV4: Downloading MPD manifest
[debug] Invoking downloader on 'https://r7---sn-gvnuxaxjvh-c35z.googlevideo.com/videoplayback/id/d455154d7000395e/itag/298/source/yt_otf/requiressl/yes/nh/,IgpwcjAzLnN2bzA1KgkxMjcuMC4wLjE/pl/19/ei/7bK4WpcmkuTuBO7rtMgE/pcm2cms/yes/mn/sn-gvnuxaxjvh-c35z,sn-n8v7snez/mm/31,29/initcwndbps/1453750/ms/au,rdu/mv/m/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1520495412485940/fvip/8/mt/1522053761/ip/90.154.69.216/ipbits/0/expire/1522075469/sparams/ip,ipbits,expire,id,itag,source,requiressl,nh,pl,ei,pcm2cms,mn,mm,initcwndbps,ms,mv,ratebypass,mime,otfp,otf,lmt/signature/65D6A52A194D6F74334982EB9E9556192C02E8E8.25FA1E096D728AC7E529A01208E57DAF6D35EE67/key/dg_yt0/'
[dashsegments] Total fragments: 117
[download] Destination: Cardboard Cowboy Funny Moments-1FUVTXAAOV4.f298.mp4
[download] 100% of 147.70MiB in 00:11
[debug] Invoking downloader on 'https://r7---sn-gvnuxaxjvh-c35z.googlevideo.com/videoplayback/id/d455154d7000395e/itag/140/source/youtube/requiressl/yes/nh/,IgpwcjAzLnN2bzA1KgkxMjcuMC4wLjE/pl/19/ei/7bK4WpcmkuTuBO7rtMgE/pcm2cms/yes/mn/sn-gvnuxaxjvh-c35z,sn-n8v7snez/mm/31,29/initcwndbps/1453750/ms/au,rdu/mv/m/ratebypass/yes/mime/audio%2Fmp4/otfp/1/gir/yes/clen/9348168/lmt/1520495297780942/dur/588.114/fvip/8/mt/1522053761/ip/90.154.69.216/ipbits/0/expire/1522075469/sparams/ip,ipbits,expire,id,itag,source,requiressl,nh,pl,ei,pcm2cms,mn,mm,initcwndbps,ms,mv,ratebypass,mime,otfp,gir,clen,lmt,dur/signature/32EEFDDE040EBA39B541939BAB3A440E46F7F030.978F68A7349CFDBBD8F91D1FD45570B4D3B3516A/key/dg_yt0/'
[dashsegments] Total fragments: 119
[download] Destination: Cardboard Cowboy Funny Moments-1FUVTXAAOV4.f140.m4a
[download] 100% of 8.91MiB in 00:10
[ffmpeg] Merging formats into "Cardboard Cowboy Funny Moments-1FUVTXAAOV4.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:Cardboard Cowboy Funny Moments-1FUVTXAAOV4.f298.mp4" -i "file:Cardboard Cowboy Funny Moments-1FUVTXAAOV4.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:Cardboard Cowboy Funny Moments-1FUVTXAAOV4.temp.mp4"
Deleting original file Cardboard Cowboy Funny Moments-1FUVTXAAOV4.f298.mp4 (pass -k to keep)
Deleting original file Cardboard Cowboy Funny Moments-1FUVTXAAOV4.f140.m4a (pass -k to keep)

```

Both streams are downloaded. It's also not the first time I encounter this, it's just I checked the URLs with `wget` and saw 404, I have playback problems in my Media Player before but blamed incompatibility with XP.

I also remember that at least once I met the same error as with this Youtube URL but I reran ytdl with same CMD and my player started playback.

**Comment by dstftw** [comment]
Both are base URLs to DASH files.
