### ISSUE TITLE
.netrc on windows 

### ISSUE THREAD

**Issue by 5shekel** [rg3/youtube-dl#160]
on windows you cant create file starting with dot. 
might be a problem with the module itself. 
also it is not clear waht should be inside that netrc file.

```
youtube-dl.py -n http://www.youtube.com/watch?v=HO1OV5B_JDw
WARNING: parsing .netrc: [Errno 2] No such file or directory: 'd:\\bin\\.netrc'
```

**Comment by 5shekel** [comment]
bump

**Comment by dstftw** [comment]
.netrc works fine on Windows.

**Comment by 5shekel** [comment]
but how?  i'm probably missing something.
windows doesn't let me save a dot file (file starting with dot) and youtube-dl explicitly asks for .netrc.
```
youtube-dl.exe -v -n EYimjHuU99c
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-n', 'EYimjHuU99c']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.03
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1
[debug] Proxy map: {}
WARNING: parsing .netrc: [Errno 2] No such file or directory: 'c:\\dir\\.netrc'
...
```

**Comment by dstftw** [comment]
http://superuser.com/questions/64471/create-rename-a-file-folder-that-begins-with-a-dot-in-windows

**Comment by 5shekel** [comment]
amazing, tnx!

**Comment by svefn** [comment]
hi, i have trouble linking to the .netrc file in Windows with $home not set. i have manually set HOME="C:/Users/username/" and it can't find the .netrc file.

**Comment by kapatz** [comment]
same problem, i have manually set HOME="C:/Users/username/" and it can't find the .netrc file.
