### ISSUE TITLE
Bilibili, issue when there is more than 1 video in the same url

### ISSUE THREAD

**Issue by iWarnock** [rg3/youtube-dl#16007]
# Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.26.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.26.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I noticed some videos had in the preview of the video said it was 200 minutes but when downloading that url it only grabbed a portion of it, upon noticing this i went inside the url and found there is a part where you can click in top of the player to switch to a "second part" where the other part of the video is, this is helpful if you want to keep several videos of your stream in a single date but youtube-dl is only grabbing the "first part", for example in this url https://www.bilibili.com/video/av20251446 it only grabs the 1st part even if you provide the full url indicating that is another part https://www.bilibili.com/video/av20251446/?p=1 or https://www.bilibili.com/video/av20251446/?p=2

Attached an image so you can see where you can select the parts and url changes accordingly into what part you are, but youtube-dl still only grabs the "first part", hope i was clear enough, ty for your time

![adaww](https://user-images.githubusercontent.com/37853928/38003235-dde80a52-31f3-11e8-9aee-2b804e2366de.jpg)

**Comment by tzw0745** [comment]
change url to "/index_(num).html" style.
just like `https://www.bilibili.com/video/av20251446/index_1.html' and `https://www.bilibili.com/video/av20251446/index_2.html'

**Comment by iWarnock** [comment]
Oh ty, guess i'm dumb since the solution was so simple, ty for the help

**Comment by aboutqx** [comment]
What about video list?`p=number` not work
