### ISSUE TITLE
URI - Youtube

### ISSUE THREAD

**Issue by WishBoy** [rg3/youtube-dl#16013]
Example
https://www.youtube.com/watch?v=1mjlM_RnsVE&feature=youtu.be -F
-F to list formats.
but with "&feature=youtu.be" it will download file and do not show the list format
i removed
https://www.youtube.com/watch?v=1mjlM_RnsVE -F
then, works normally.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
