### ISSUE TITLE
Error curl last version

### ISSUE THREAD

**Issue by lokomass** [rg3/youtube-dl#16016]
Hi,
I can't no more download last version with curl, what's appened ?
Here my log, thank for help

![image](https://user-images.githubusercontent.com/7886368/38038864-8774a3bc-329b-11e8-83d6-4c7bcb8888aa.png)

**Comment by dstftw** [comment]
Update OpenSSL. TLSv1 is no longer supported by GitHub: https://githubengineering.com/crypto-removal-notice/.

**Comment by Hrxn** [comment]
Better: Update curl and OpenSSL.
