### ISSUE TITLE
720p youtube video is downloaded even though 1080p exists

### ISSUE THREAD

**Issue by realnc** [rg3/youtube-dl#16018]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.26.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.26.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.03.26.1
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Sometimes youtube-dl downloads the 720p version of youtube videos even though higher resolutions exist. It seems it considers bitrate more important than resolution.

Example:

```
$ youtube-dl -v -F https://youtu.be/2MANx1Gc3NU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://youtu.be/2MANx1Gc3NU']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.26.1
[debug] Python version 3.5.4 (CPython) - Linux-4.14.30-gentoo-x86_64-Intel-R-_Core-TM-_i5-2500K_CPU_@_3.30GHz-with-gentoo-2.4.1
[debug] exe versions: ffmpeg 3.3.6, ffprobe 3.3.6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 2MANx1Gc3NU: Downloading webpage
[youtube] 2MANx1Gc3NU: Downloading video info webpage
[youtube] 2MANx1Gc3NU: Extracting video information
[youtube] 2MANx1Gc3NU: Downloading MPD manifest
[youtube] 2MANx1Gc3NU: Downloading MPD manifest
[info] Available formats for 2MANx1Gc3NU:
format code  extension  resolution note
139          m4a        audio only DASH audio   48k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k (44100Hz)
160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 29fps, video only
134          mp4        640x360    DASH video  159k , mp4_dash container, avc1.4d401e, 29fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 29fps, video only
137          mp4        1920x1080  DASH video 1106k , mp4_dash container, avc1.640028, 29fps, video only
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 29fps, video only
136          mp4        1280x720   DASH video 2310k , mp4_dash container, avc1.4d4016, 29fps, video only
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)

$ youtube-dl -v https://youtu.be/2MANx1Gc3NU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtu.be/2MANx1Gc3NU']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.26.1
[debug] Python version 3.5.4 (CPython) - Linux-4.14.30-gentoo-x86_64-Intel-R-_Core-TM-_i5-2500K_CPU_@_3.30GHz-with-gentoo-2.4.1
[debug] exe versions: ffmpeg 3.3.6, ffprobe 3.3.6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 2MANx1Gc3NU: Downloading webpage
[youtube] 2MANx1Gc3NU: Downloading video info webpage
[youtube] 2MANx1Gc3NU: Extracting video information
[youtube] 2MANx1Gc3NU: Downloading MPD manifest
[youtube] 2MANx1Gc3NU: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r7---sn-vuxbavcx-5uis.googlevideo.com/videoplayback/id/d8c00dc7519cdcd5/itag/136/source/yt_otf/requiressl/yes/pcm2cms/yes/initcwndbps/557500/ms/au,rdu/mv/m/pl/16/mm/31,29/ei/LdO7WqGCHpTogAf5842gBA/mn/sn-vuxbavcx-5uis,sn-4g5e6nle/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1521456716103881/fvip/1/mt/1522258593/ip/85.75.187.229/ipbits/0/expire/1522280333/sparams/ip,ipbits,expire,id,itag,source,requiressl,pcm2cms,initcwndbps,ms,mv,pl,mm,ei,mn,ratebypass,mime,otfp,otf,lmt/signature/736A9FA8C3BBA919C25CEE9DDF5A17AB725F200C.8DEDC777FA749292D983352ACF1FF0C4AC28D823/key/dg_yt0/'
[dashsegments] Total fragments: 16
[download] Destination: Qt Creator 4.6.0-rc1 cmake clean step bug-2MANx1Gc3NU.f136.mp4
[download] 100% of 3.07MiB in 00:03
[debug] Invoking downloader on 'https://r7---sn-vuxbavcx-5uis.googlevideo.com/videoplayback/id/d8c00dc7519cdcd5/itag/140/source/youtube/requiressl/yes/pcm2cms/yes/initcwndbps/557500/ms/au,rdu/mv/m/pl/16/mm/31,29/ei/LdO7WqGCHpTogAf5842gBA/mn/sn-vuxbavcx-5uis,sn-4g5e6nle/ratebypass/yes/mime/audio%2Fmp4/otfp/1/gir/yes/clen/1301626/lmt/1521456705872805/dur/81.850/fvip/1/mt/1522258593/ip/85.75.187.229/ipbits/0/expire/1522280333/sparams/ip,ipbits,expire,id,itag,source,requiressl,pcm2cms,initcwndbps,ms,mv,pl,mm,ei,mn,ratebypass,mime,otfp,gir,clen,lmt,dur/signature/7282E5DBC42CE74BFD39C61184AC0DD05DEB5D86.2FC5342848F24BDA0DE7ECF11772DF6794691543/key/dg_yt0/'
[dashsegments] Total fragments: 18
[download] Destination: Qt Creator 4.6.0-rc1 cmake clean step bug-2MANx1Gc3NU.f140.m4a
[download] 100% of 1.24MiB in 00:02
[ffmpeg] Merging formats into "Qt Creator 4.6.0-rc1 cmake clean step bug-2MANx1Gc3NU.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Qt Creator 4.6.0-rc1 cmake clean step bug-2MANx1Gc3NU.f136.mp4' -i 'file:Qt Creator 4.6.0-rc1 cmake clean step bug-2MANx1Gc3NU.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Qt Creator 4.6.0-rc1 cmake clean step bug-2MANx1Gc3NU.temp.mp4'
Deleting original file Qt Creator 4.6.0-rc1 cmake clean step bug-2MANx1Gc3NU.f136.mp4 (pass -k to keep)
Deleting original file Qt Creator 4.6.0-rc1 cmake clean step bug-2MANx1Gc3NU.f140.m4a (pass -k to keep)
```

This also happens if I specify this format:

```bestvideo[ext=webm][width<=?2560]+bestaudio/bestvideo[ext=mp4][width<=?2560]+bestaudio/best```

which is what I use. There doesn't seem to be a way to tell youtube-dl to use resolution as the quality metric instead of the bitrate.

**Comment by dstftw** [comment]
This is expected behavior. 720p has higher bitrate.

**Comment by realnc** [comment]
@dstftw The behavior might be expected, but it's not correct. The 1080p version is higher quality, even if 720p has higher bitrate.
