### ISSUE TITLE
Add support for puhutv.com

### ISSUE THREAD

**Issue by SubZero5** [rg3/youtube-dl#16010]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.26.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.26.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl.exe https://puhutv.com/jet-sosyete-4-bolum-izle -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://puhutv.com/jet-sosyete-4-bolum-izle', '-v']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2018.03.26.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.3
[debug] Proxy map: {}
[generic] jet-sosyete-4-bolum-izle: Requesting header
WARNING: Falling back on generic information extractor.
[generic] jet-sosyete-4-bolum-izle: Downloading webpage
[generic] jet-sosyete-4-bolum-izle: Extracting information
ERROR: Unsupported URL: https://puhutv.com/jet-sosyete-4-bolum-izle
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\generic.py", line 3143, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://puhutv.com/jet-sosyete-4-bolum-izle
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://puhutv.com/jet-sosyete-1-bolum-izle
- Playlist: https://puhutv.com/jet-sosyete-detay

**Comment by mrfade** [comment]
[https://puhutv.com/api/slug/jet-sosyete-1-bolum-izle](url)
find **data.id** and insert between assets and videos on the link below

[https://puhutv.com/api/assets/18501/videos](url) _**note:** geo restricted page_
