### ISSUE TITLE
Duplicate subtitles from Youtube

### ISSUE THREAD

**Issue by NarakuF** [rg3/youtube-dl#16032]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.26.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.26.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

When I download subtitles form Youtube, e.g. running `youtube-dl --write-auto-sub --skip-download --sub-lang en https://www.youtube.com/watch?v=bB3ZpRpVKWM`, subtitles in both vtt and srt files are deplicate. Each sentence will repeat three times. Do we have a solution for this?

```
youtube-dl -v --write-auto-sub --skip-download --sub-lang en --sub-format ass/srt/best https://www.youtube.com/watch?v=bB3ZpRpVKWM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--write-auto-sub', '--skip-download', '--sub-lang', 'en', '--sub-format', 'ass/srt/best', 'https://www.youtube.com/watch?v=bB3ZpRpVKWM']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2018.03.26.1
[debug] Python version 3.6.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-90433-g5b31dd1c6b, ffprobe N-90433-g5b31dd1c6b
[debug] Proxy map: {}
[youtube] bB3ZpRpVKWM: Downloading webpage
[youtube] bB3ZpRpVKWM: Downloading video info webpage
[youtube] bB3ZpRpVKWM: Extracting video information
[youtube] bB3ZpRpVKWM: Looking for automatic captions
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: How to Make a Peanut Butter and Jelly Sandwich-bB3ZpRpVKWM.en.vtt
```

**Comment by dstftw** [comment]
Duplication comes from Youtube. Nothing you can do.
