### ISSUE TITLE
Please add support for liveme.com ad vk.com and even for it's livestreams

### ISSUE THREAD

**Issue by Jupisoft111** [rg3/youtube-dl#16037]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.26.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.26.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single Liveme.com video: http://www.liveme.com/live.html?videoid=15223752305885469636
- Single Liveme.com .m3u8 fragment list: http://1253467418.vod2.myqcloud.com/4753c5bbvodca1253467418/dde839737447398155085544861/playlist_eof.m3u8
- Single VK.com video: https://vk.com/video302692792_456239079
- Single VK.com .m3u8 fragment list: https://cs542603.vkuservideo.net/video/hls/4/u302692792/videos/cb8346fb39/index-f3-v1-a1.m3u8?extra=Pel5t4Fi77TDctub013BaHiZf0siv-rnVsh9JSdGqsbUlcdBdgpcLiJsw82F4P2uyIpUL05FaiOzNzMsOLSDw2YJyoQrfvqxsnuvxLf0NAGUmkYHcSP2_pKQ4sE
- VK.com Playlist: https://vk.com/videos302692792

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I'll love that youtube-dl had support for sites likes Liveme.com and VK.com (which partially does already), but also in the livestreams, with an option to download the .ts fragments and leave them untouched in a folder or output path, or to encode them as a mp4 video. Note that some fragements might be missing, if they are from a livestream, so it should just encode what it had managed to download.

In firefox, press F12, and on the "Net" tab, write "m3u8" to filter and search future .m3u8 lists, that contain the .ts fragments that youtube-dl should download.

Also I noticed that Liveme.com uses incremental numeric names starting at "1" for it's .ts fragments, although for livestreams seems to start at a random big number and keeps incrementing it 1 for each fragment. Unfortunately VK.com only sotres 6 .ts fragmentes per .m3u8 livestream list and the numeric names have a big separation between them, as if they were timestamps in milliseconds or so.

**Comment by dstftw** [comment]
All URLs work fine apart from the first one that is a duplicate.
