### ISSUE TITLE
Youtubedl -j command returns me urls that results in a http 403 page

### ISSUE THREAD

**Issue by juanla** [rg3/youtube-dl#16042]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.26.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*
I run this command `youtube-dl -j HCjNJDNzw8Y` and I get this JSON info:
https://pastebin.com/RvRdF4fy

But the urls give me 403 when I try access it

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

https://pastebin.com/T9L7tjeG

---

### Description of your *issue*, suggested solution and other information

I explained before, anyway, the problem is that the urls returned by the -j command in some videos results me in HTTP 403 page.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser

**Comment by juanla** [comment]
Thanks, with my por english I don't find these topic easy :)
