### ISSUE TITLE
--get-filename shows wrong extension in combination with --extract-audio/--audio-format

### ISSUE THREAD

**Issue by dracenmarx** [rg3/youtube-dl#16049]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.26.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.26.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description
The option --get-filename does not show the final filename if it is combined with --extract-audio and/or --audio-format

### Example:
youtube-dl --get-filename --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=XYZ

### Expected behavior
The output filename provided by --get-filename should be:
VideoTitle-XYZ.mp3

### Actual behavior
But it is:
VideoTitle-XYZ.webm

**Comment by dstftw** [comment]
This is expected behavior.
