### ISSUE TITLE
How can I redirect youtube live videos to sony bravia tv in LAN?

### ISSUE THREAD

**Issue by kensully** [rg3/youtube-dl#16046]
I am on Ubuntu 16.04 platform. I can watch youtube videos on LAN by downloading videos with `youtube-dl` and then using vget chrome extension  while file is recording with this

        youtube-dl -f 18 https://www.youtube.com/watch?v=Glox1Ph9jqQ  --hls-use-mpegts --no-part --output live

but it doesn't work for live streams in youtube.

How can I watch live streams in tv connected to localhost?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
