### ISSUE TITLE
--max-filesize not working with --external-downloader

### ISSUE THREAD

**Issue by BRFNGRNBWS** [rg3/youtube-dl#16043]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.26.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.26.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

command: youtube-dl -v -x --external-downloader aria2c --max-filesize 10m "https://www.youtube.com/watch?v=MD3ROlR6k8I"
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-x', u'--external-downloader', u'aria2c', u'--max-filesize', u'10m', u'https://www.youtube.com/watch?v=MD3ROlR6k8I']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.02
[debug] Python version 2.7.12 - Linux-4.13.0-26-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: ffmpeg N-88041-gb89081e-1, ffprobe N-88041-gb89081e-1
[debug] Proxy map: {}
[youtube] MD3ROlR6k8I: Downloading webpage
[youtube] MD3ROlR6k8I: Downloading video info webpage
[youtube] MD3ROlR6k8I: Extracting video information
[youtube] {22} signature length 44.45, html5 player vflI0cIzU
[youtube] {43} signature length 44.45, html5 player vflI0cIzU
[youtube] {18} signature length 44.45, html5 player vflI0cIzU
[youtube] {36} signature length 44.45, html5 player vflI0cIzU
[youtube] {17} signature length 44.45, html5 player vflI0cIzU
[youtube] {137} signature length 44.45, html5 player vflI0cIzU
[youtube] {136} signature length 44.45, html5 player vflI0cIzU
[youtube] {135} signature length 44.45, html5 player vflI0cIzU
[youtube] {134} signature length 44.45, html5 player vflI0cIzU
[youtube] {133} signature length 44.45, html5 player vflI0cIzU
[youtube] {160} signature length 44.45, html5 player vflI0cIzU
[youtube] {140} signature length 44.45, html5 player vflI0cIzU
[debug] Invoking downloader on u'https://r12---sn-bvvbax-a5ne.googlevideo.com/videoplayback?ipbits=0&lmt=1420572757474128&c=WEB&mm=31%2C26&mime=audio%2Fmp4&id=o-AFDaqai5lkIsqUYamT6vs3QwErIaSuYFd0OhUV4zrr92&pl=16&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cexpire&mt=1522428497&mv=m&ms=au%2Conr&fvip=3&key=yt6&ip=72.193.48.24&mn=sn-bvvbax-a5ne%2Csn-n4v7sn7l&gir=yes&expire=1522450217&requiressl=yes&keepalive=yes&itag=140&ei=yWq-WsznKsuZ_AOqkJPYDw&clen=49268948&dur=3068.934&source=youtube&initcwndbps=1428750&nh=EAE%2C&signature=E166CAE9C56A7A3B80DB5DD798FCB14285EFB65C.21F3326E3E57158AE711D090752A375C1AF85CA0&ratebypass=yes'
[download] Destination: Monstercat 012 - Aftermath (Order Album Mix) [1 Hour of Electronic Music!]-MD3ROlR6k8I.m4a
[debug] aria2c command line: aria2c -c --min-split-size 1M --max-connection-per-server 4 --out 'Monstercat 012 - Aftermath (Order Album Mix) [1 Hour of Electronic Music!]-MD3ROlR6k8I.m4a.part' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' --header 'Accept-Language: en-us,en;q=0.5' --header 'Accept-Encoding: gzip, deflate' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)' '--check-certificate=true' -- 'https://r12---sn-bvvbax-a5ne.googlevideo.com/videoplayback?ipbits=0&lmt=1420572757474128&c=WEB&mm=31%2C26&mime=audio%2Fmp4&id=o-AFDaqai5lkIsqUYamT6vs3QwErIaSuYFd0OhUV4zrr92&pl=16&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cexpire&mt=1522428497&mv=m&ms=au%2Conr&fvip=3&key=yt6&ip=72.193.48.24&mn=sn-bvvbax-a5ne%2Csn-n4v7sn7l&gir=yes&expire=1522450217&requiressl=yes&keepalive=yes&itag=140&ei=yWq-WsznKsuZ_AOqkJPYDw&clen=49268948&dur=3068.934&source=youtube&initcwndbps=1428750&nh=EAE%2C&signature=E166CAE9C56A7A3B80DB5DD798FCB14285EFB65C.21F3326E3E57158AE711D090752A375C1AF85CA0&ratebypass=yes'
[#c2ac28 46MiB/46MiB(99%) CN:1 DL:630KiB]                                                                                                                                                                                                   
03/30 09:50:46 [NOTICE] Download complete: /home/colinl/Monstercat 012 - Aftermath (Order Album Mix) [1 Hour of Electronic Music!]-MD3ROlR6k8I.m4a.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
c2ac28|OK  |   1.7MiB/s|/home/colinl/Monstercat 012 - Aftermath (Order Album Mix) [1 Hour of Electronic Music!]-MD3ROlR6k8I.m4a.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 49268948 bytes
[download] 100% of 46.99MiB
[ffmpeg] Correcting container in "Monstercat 012 - Aftermath (Order Album Mix) [1 Hour of Electronic Music!]-MD3ROlR6k8I.m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Monstercat 012 - Aftermath (Order Album Mix) [1 Hour of Electronic Music!]-MD3ROlR6k8I.m4a' -c copy -f mp4 'file:Monstercat 012 - Aftermath (Order Album Mix) [1 Hour of Electronic Music!]-MD3ROlR6k8I.temp.m4a'
[debug] ffmpeg command line: ffprobe -show_streams 'file:Monstercat 012 - Aftermath (Order Album Mix) [1 Hour of Electronic Music!]-MD3ROlR6k8I.m4a'
[ffmpeg] Post-process file Monstercat 012 - Aftermath (Order Album Mix) [1 Hour of Electronic Music!]-MD3ROlR6k8I.m4a exists, skipping
```

### Description of your *issue*, suggested solution and other information

So I have a script that searches and downloads a bunch of files from youtube for me, and am using --external-downloader aria2c in my youtube-dl commands, since it's way faster than default. Anyway, I want it to not download a video bigger than a certain size, so I do --max-filesize 10m, but it downloads the video anyway, even though the filesize is shown to be well over 10Mb. --max-filesize works fine without specifying an external downloader, but if I specify aria2c, avconv, or wget, it downloads the file anyway, despite it being over the specified maximum size. I've tried it with different videos and with ytsearch: and the problem is consistant.

**Comment by dstftw** [comment]
1. It's not supposed to work with external downloaders.
2. External downloaders will be much slower for DASH videos due to Youtube throttling that is bypassed in native youtube-dl downloader.
3. Outdated youtube-dl version.
