### ISSUE TITLE
Console Appearing then Closing Windows

### ISSUE THREAD

**Issue by awsome-dudes** [rg3/youtube-dl#16050]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.26.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.26.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I currently use Sinusbot to launch youtube-dl on windows 10 via the .exe , the issue that i am running into is whenever a download request is sent, a console appears and takes focus for a few seconds then disappears which is frustrating when using the pc for other activities, is there a way to either keep the console open or to not have it appear at all? i tired quiet mode which made no difference. Also, when running the -v command, i can see it print out the information then immediately close. Any help would be greatly appreciated.

**Comment by dstftw** [comment]
Address this to Sinusbot support.
