### ISSUE TITLE
youtube-dl geo-blocking

### ISSUE THREAD

**Issue by IoanPaleru** [rg3/youtube-dl#16055]
youtube-dl is a great program because it has lots of features, but how do you download a youtube video that's geo-blocked? When I use a VPN add-on in Watefox I can view the video, but youtube-dl won't download it. Thanks. Have a nice day.

**Comment by dstftw** [comment]
Same way as any other application - by using system wide VPN or a proxy.

**Comment by IoanPaleru** [comment]
How do you use a system wide VPN or a proxy?

**Comment by dstftw** [comment]
Google how to use VPN on your OS. For proxy: `--proxy`.
