### ISSUE TITLE
how to extract video with mp4 extension ,not  m3u8

### ISSUE THREAD

**Issue by design365** [rg3/youtube-dl#16066]
i use youtube-dl to extract "http://www.bcci.tv/videos/id/6136/icc-u19-wc-final-india-thrash-australia"
but give me :
************************
"url": "http://c.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=5725344397001",
"extractor_key": "BrightcoveLegacy",
"vcodec": "H264",
**********************
i don't want use m3u8  , how to get the mp4 link?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#format-selection
