### ISSUE TITLE
Block a particular server url or force to resend request to get content from another server

### ISSUE THREAD

**Issue by Braj65** [rg3/youtube-dl#16072]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.26.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.26.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

When sending request to download a video to an url, the downloader is getting invoked on one of the two servers. One of the servers is very slow in transferring content, due to which video download is very slow. While the other server is quite fast. Is it possible to block the slow server url so that youtube-dl always invokes the other server. Else anyway to keep re-sending the request for the target url, if the slow server responds the first time, till any other server except the slow server responds.

Thanks

**Comment by dstftw** [comment]
Automatically - not possible. Though you can filter out formats by some criteria inherent to the slow server with [format selection](https://github.com/rg3/youtube-dl#format-selection).

**Comment by Braj65** [comment]
The format selection won't give any control on which server url to block. In the youtube-dl.py, if you can help me with which method is responsible to request for the server url and get the response then i can write an if condition to block unwanted urls and re-request. Keep changes local and compile and use it.
