### ISSUE TITLE
Using youtube-dl as Python 3 module

### ISSUE THREAD

**Issue by b-b-x** [rg3/youtube-dl#16071]
Hi

I am writing program which uses youtube-dl by calling it via shell, but i decided
it would be better to use it as python module instead, but i can't find any documentation.

For example i have code like this:

import youtube_dl

```
ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '320',
    }]
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://www.youtube.com/watch?v=BaW_jenozKc'])
```
I would like it to search for video by keywords on Youtube instead of passing urls to it, and to download
the file to different location.

Thank you

**Comment by dstftw** [comment]
1. Pass 1ytsearch<num_results>:<query>`.
2. https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L162
