### ISSUE TITLE
Vier.be support is broken

### ISSUE THREAD

**Issue by EWouters** [rg3/youtube-dl#16087]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
D:\Downloads>youtube-dl.exe https://www.vier.be/video/de-mol/de-mol-2018/de-mol-2018-aflevering-1 --verbose --username eirudjkxcnm@mailinator.com --password 12345678 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.vier.be/video/de-mol/de-mol-2018/de-mol-2018-aflevering-1', '--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.04.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-82691-g2c908f2, ffprobe N-82691-g2c908f2
[debug] Proxy map: {}
[vier] Logging in
ERROR: Unable to log in: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_it5pa_f\build\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_it5pa_f\build\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.vier.be/video/de-mol/de-mol-2018/de-mol-2018-aflevering-1
- Single video: https://www.vier.be/video/de-mol/maak-kennis-met-de-10-kandidaten-van-de-mol-2018
- Single video: https://www.vier.be/video/cafedemol/cafe-de-mol-aflevering-1
- Single video: https://www.vier.be/video/topdokters/topdokters-s5/topdokters-seizoen-5-aflevering-9
- Playlist: https://www.vier.be/video/de-mol/de-mol-2018
- Playlist: https://www.vier.be/video/cafedemol/seizoen-1
- Playlist: https://www.vier.be/video/topdokters/topdokters-s5

---

### Description of your *issue*, suggested solution and other information

Support for vier.be is currently broken. The site requires username and password authentication. I have created an account on the site using username: eirudjkxcnm@mailinator.com and password 12345678 which can be used for testing.

Thanks for any help!

**Comment by jeffreykuiken** [comment]
#15636 fixes the issue, so you could try to use that version.

**Comment by EWouters** [comment]
Thank you, I did not search through the pending pull requests before posting this. Glad it was already spotted and a fix is on the way.
