### ISSUE TITLE
Site openload.co can't download 

### ISSUE THREAD

**Issue by nguyenxuanchung789** [rg3/youtube-dl#16099]
E:\Application Auto\YouDowload\YouDowload\bin\Debug\ToolDownload>youtube-dl -v https://openload.co/embed/lvppKm9CjX8/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://openload.co/embed/lvppKm9CjX8/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.04.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[Openload] lvppKm9CjX8: Downloading embed webpage
[Openload] lvppKm9CjX8: Executing JS on webpage
ERROR: lvppKm9CjX8: Can't find stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_it5pa_f\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_it5pa_f\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_it5pa_f\build\youtube_dl\extractor\openload.py", line 340, in _real_extract
youtube_dl.utils.ExtractorError: lvppKm9CjX8: Can't find stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

E:\Application Auto\YouDowload\YouDowload\bin\Debug\ToolDownload>youtube-dl -U
youtube-dl is up-to-date (2018.04.03)

**Comment by akiross** [comment]
Same problem here, using latest version of youtube-dl and phantomjs.

**Comment by edutzugaya** [comment]
Same over here.

[root@mail sg1]# youtube-dl --verbose https://openload.co/embed/QloCkU4UHYU/
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://openload.co/embed/QloCkU4UHYU/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.10
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-693.17.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[Openload] QloCkU4UHYU: Downloading embed webpage
[Openload] QloCkU4UHYU: Executing JS on webpage
ERROR: QloCkU4UHYU: Can't find stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/openload.py", line 340, in _real_extract
    raise ExtractorError('Can\'t find stream URL', video_id=video_id)
ExtractorError: QloCkU4UHYU: Can't find stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
