### ISSUE TITLE
[CBS] - SAMPLE-AES encryption is not supported yet.

### ISSUE THREAD

**Issue by DanTheMan827** [rg3/youtube-dl#16104]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Trying to download some videos from http://www.cbs.com will fail with the ffmpeg error `SAMPLE-AES encryption is not supported yet.`

One of the problematic videos: https://www.cbs.com/shows/macgyver/video/16Uktn9vb53zY72LuEbkXdq5VYVX0T3J/macgyver-riley-airplane/

**Comment by stinkteeth** [comment]
Manually choose the download quality, selecting StreamPack (e.g. hls-6300) rather than HLS_FPS.

By the looks of things (the presence of HLS_FPS and DASH-CENC), it's possible that they may soon transition to a drm system.  If that happens, a corresponding download method won't be so easy.

**Comment by jimbolaya** [comment]
I also found if I watched the network stream in chrome, I found a master.m3u8 in the stream that allowed me to download the whole thing. For instance, watching the network stream for "https://www.cbs.com/shows/madam-secretary/video/Ko2ii1MbS7GOI_s_Cze_gYzqf4lzI9Mz/madam-secretary-phase-two/" yielded "https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2018/03/29/1198216259920/CBS_MADAM_SECRETARY_417_AA_6CH_30M_1392609_,1628,4628,3128,2228,848,503,000.mp4.csmil/master.m3u8?hdnea=acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2018/03/29/1198216259920/CBS_MADAM_SECRETARY_417_AA_6CH_30M_1392609_*~exp=1523630150~hmac=0e83d92ccfb98416efd95169d4cdd1f8933385bff9dfc70fe0edb78be3fa63c2" which worked fine.

**Comment by jimbolaya** [comment]
The link I found in chrome seems to be time dependant. I tried using it later and it failed.
