### ISSUE TITLE
Code 403 with RTBF Auvio videos

### ISSUE THREAD

**Issue by Joreel** [rg3/youtube-dl#16101]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.03**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.rtbf.be/auvio/detail_questions-a-la-une?id=2331208']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.03
[debug] Python version 2.7.13 (CPython) - Linux-4.14.26-2-osmc-armv7l-with-debian-9.4
[debug] exe versions: none
[debug] Proxy map: {}
[RTBF] 2331208: Downloading JSON metadata
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'http://rtbf-vod.l3.freecaster.net/vod/rtbf/geo/drm/3/3yS2x9p9UX-720p.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1896, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1835, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 365, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 340, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2199, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

```

---

### Description of your *issue*, suggested solution and other information

I think I know what the problem is. Since recently the RTBF forces users to sign in, in order to watch the videos. That would explain the code 403.

**Comment by kevmns** [comment]
Still have the 403 access eror with my credentials provided, can someone help ?

**Comment by kevmns** [comment]
> Still have the 403 access eror with my credentials provided, can someone help ?

@Twilkie, do you any idea about this issue ? Another Belgian provider.

**Comment by Twilkie** [comment]
@kevmns it says DRM in the download url. So the file might be protected. Will check later.

**Comment by kevmns** [comment]
> @kevmns it says DRM in the download url. So the file might be protected. Will check later.

Does DRM protected mean directly undownloadable ? Thanks for your help.

**Comment by Twilkie** [comment]
DRM means digital rights management, it says what you can and cannot do with a file. So it's doesn't necessarily mean you can't download it but it's not a good sign. 
Anyway, I tried the url of your example in a browser. It says 404 page not found. Is the video you are trying no longer available?

**Comment by Twilkie** [comment]
Also, you are commenting on a closed issue.
