### ISSUE TITLE
[Youtube] Are comments being downloaded in info.json any more?

### ISSUE THREAD

**Issue by voltagex** [rg3/youtube-dl#16128]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

https://github.com/rg3/youtube-dl/issues/9771 seems to suggest that comments on Youtube videos will be dumped to the info.json file.
```
PS> youtube-dl -v --skip-download --write-info-json utfbE3_uAMA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--skip-download', '--write-info-json', 'utfbE3_uAMA']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.04.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-87353-g183fd30, ffprobe N-87353-g183fd30, rtmpdump 2.4-20151223-gfa8646d-LibreSSL_2.5.4-x86_64-static
[debug] Proxy map: {}
[youtube] utfbE3_uAMA: Downloading webpage
[youtube] utfbE3_uAMA: Downloading video info webpage
[youtube] utfbE3_uAMA: Extracting video information
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video description metadata as JSON to: Bringing BACK The iPhone Headphone Jack - in China-utfbE3_uAMA.info.json
```

The downloaded json file doesn't contain comments at all
I have zipped and attached the downloaded file.

[Bringing BACK The iPhone Headphone Jack - in China-utfbE3_uAMA.info.json.zip](https://github.com/rg3/youtube-dl/files/1887102/Bringing.BACK.The.iPhone.Headphone.Jack.-.in.China-utfbE3_uAMA.info.json.zip)

Noting that comments are on the video in question

![image](https://user-images.githubusercontent.com/159567/38464192-aba3f256-3b4c-11e8-9968-dd8458a4753f.png)

**Comment by dstftw** [comment]
Comments were never downloaded for Youtube.
