### ISSUE TITLE
New openload issue / phantomjs

### ISSUE THREAD

**Issue by edutzugaya** [rg3/youtube-dl#16127]
After downloading files from a batch, this happened and after retrying the same batch.

ERROR: Executing JS failed
:PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/openload.py", line 336, in _real_extract
    webpage, _ = phantom.get(page_url, html=webpage, video_id=video_id, headers=headers)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/openload.py", line 236, in get
    'Executing JS failed\n:' + encodeArgument(err))
ExtractorError: Executing JS failed
:PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

So i retested today and the output is still the same.

[debug] Invoking downloader on u'https://openload.co/stream/h36B2c6YEsI~1523245890~62.210.0.0~XIUPK2Qq?mime=true'
[download] Stargate SG-1 - (2x06) - Thor's Chariot.avi.mp4-h36B2c6YEsI.mp4 has already been downloaded
[download] 100% of 327.09MiB
[Openload] l6TDmepqza0: Downloading embed webpage
[Openload] l6TDmepqza0: Executing JS on webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://openload.co/stream/l6TDmepqza0~1523245892~62.210.0.0~ORMs2ZQL?mime=true'
[download] Stargate SG-1 - (2x07) - Message In A Bottle.avi.mp4-l6TDmepqza0.mp4 has already been downloaded
[download] 100% of 330.11MiB
[Openload] ZpRABbDsdDM: Downloading embed webpage
[Openload] ZpRABbDsdDM: Executing JS on webpage
ERROR: Executing JS failed
:PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/openload.py", line 336, in _real_extract
    webpage, _ = phantom.get(page_url, html=webpage, video_id=video_id, headers=headers)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/openload.py", line 236, in get
    'Executing JS failed\n:' + encodeArgument(err))
ExtractorError: Executing JS failed
:PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by edutzugaya** [comment]
It's really random, retesting this produced different results, it's inconsistent and i apologize for this.

**Comment by msdev20** [comment]
I am using youtube-dl version 2019.04.30
I got error while fetch openload file. Debug log as follow.

`# /usr/local/bin/youtube-dl --verbose --get-filename -o "%(title)s" http
s://openload.co/f/Of3tN9ZzslU`

`[debug] System config: [u'--prefer-free-formats']`
`[debug] User config: []`
`[debug] Custom config: []`
`[debug] Command-line args: [u'--verbose', u'--get-filename', u'-o', u'%(title)s', u'https://openload.co/f/Of3tN9ZzslU']`
`[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8`
`[debug] youtube-dl version 2019.04.30`
`[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core`
`[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15, phantomjs 2.1.1`
`[debug] Proxy map: {}`
`ERROR: Executing JS failed`
`:; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
`Traceback (most recent call last):`
 `File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)`
  `File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)`
  `File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 1982, in _real_extract
    webpage, _ = phantom.get(page_url, html=webpage, video_id=video_id, headers=headers)`
  `File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 237, in get
    'Executing JS failed\n:' + encodeArgument(err))`
`ExtractorError: Executing JS failed`
`:; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
