### ISSUE TITLE
Allow merging formats

### ISSUE THREAD

**Issue by phihag** [rg3/youtube-dl#1612]
Allow individual formats in `-f` to consist of multiple format IDs, for example

```
-f 137+141/137+160/37/mp4+mp3
```

A format is picked only if all the IDs it consists of are present (and ffmpeg is available?).  If this options is set, the format name is automatically appended to the video filename while downloading, i.e. we'll get `title-id.ext.f137` and `title-id.ext.f1141` by default. If a format with a plus is picked, the extracted information contains a `_postprocessing: {type:"ffmpeg-merge", "files": ["title-id.ext.f137", "title-id.ext.f1141"]}` hint, and ffmpeg is automatically invoked to create a single file.

**Comment by seed3r** [comment]
what is the combination of '18' format id?
 ?
