### ISSUE TITLE
not correct extract video info from www.keezmovies.com

### ISSUE THREAD

**Issue by wangxiaogangan** [rg3/youtube-dl#16134]
- [x] Bug report (encountered problems with youtube-dl)

When i use keezmovies.py to download video info from 

**https://www.keezmovies.com/video/Cute-little-azn-chick-strips-for-the-camera-18092651**

the WebPage not find flashvars while a few page contian this item, but most of pages do not have this “flashvars”， the error msg is below：

[KeezMovies] Cute-little-azn-chick-strips-for-the-camera: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\PROJ\trunk\Url_Extractor\youtube-dl\youtube_dl\YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)

**Comment by parmjitv** [comment]
Hi @wangxiaogangan,

A lot of pages on the KeezMovies site are now using embedded URLs for the videos, rather than flash vars.  A new PR will submitted shortly to accommodate this in the extractor.

Cheers,

Parmjit V.
