### ISSUE TITLE
Not sure if it's a bug in youtube-dl or cookiejar.py GBK codec can't decode

### ISSUE THREAD

**Issue by k432ts** [rg3/youtube-dl#16131]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
```
C:\Windows\system32>youtube-dl --proxy "socks5://127.0.0.1:1080/" --cookies "D:/lynda download/cookies.txt" -v --all-subs -o "Lynda.com - %(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" "https://www.lynda.com/Photography-tutorials/Advanced-Photography-Medium-Format-Digital-Cameras/647680-2.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', 'socks5://127.0.0.1:1080/', '--cookies', 'D:/lynda download/cookies.txt', '-v', '--all-subs', '-o', 'Lynda.com - %(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', 'https://www.lynda.com/Photography-tutorials/Advanced-Photography-Medium-Format-Digital-Cameras/647680-2.html']
c:\users\张心阳\appdata\local\programs\python\python36\lib\http\cookiejar.py:2061: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "c:\users\张心阳\appdata\local\programs\python\python36\lib\http\cookiejar.py", line 2011, in _really_load
    line = f.readline()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x82 in position 663: illegal multibyte sequence

  _warn_unhandled_exception()
Traceback (most recent call last):
  File "c:\users\张心阳\appdata\local\programs\python\python36\lib\http\cookiejar.py", line 2011, in _really_load
    line = f.readline()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x82 in position 663: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\张心阳\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\张心阳\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\张心阳\AppData\Local\Programs\Python\Python36\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\张心阳\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\__init__.py", line 471, in main
    _real_main(argv)
  File "c:\users\张心阳\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\__init__.py", line 438, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "c:\users\张心阳\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 411, in __init__
    self._setup_opener()
  File "c:\users\张心阳\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 2291, in _setup_opener
    self.cookiejar.load()
  File "c:\users\张心阳\appdata\local\programs\python\python36\lib\http\cookiejar.py", line 1784, in load
    self._really_load(f, filename, ignore_discard, ignore_expires)
  File "c:\users\张心阳\appdata\local\programs\python\python36\lib\http\cookiejar.py", line 2063, in _really_load
    (filename, line))
http.cookiejar.LoadError: invalid Netscape format cookies file 'D:/lynda download/cookies.txt': 'www.telerik.com\tFALSE\t/\tFALSE\t1679055717\tki_t\t1521288091697%3B1521288091697%3B1521289317673%3B1%3B8'
```
this problem only occurs when Im using youtube-dl under python3
Under python2, I can download the full course perfectly
while I use 
```
D:\>python3
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.getdefaultencoding())
utf-8
>>>
```
as above, python3 gives me a default encoding as UTF8

**Comment by dstftw** [comment]
Cookie file must be in `locale.getpreferredencoding(False)` encoding.

**Comment by k432ts** [comment]
@dstftw Sorry to bother, but how can I change the `locale.getpreferredencoding()` into `False` in windows?

**Comment by keenlovelife** [comment]
##目前我也发现了这个问题，gbk编码出错。现在我已经解决了。

# 解决办法如下：

1. 你需要通过 youtube-dl的源码来运行任务(下载视频)，如果是 youtube-dl.exe 将无法修改。
2. 在源码文件找到 youtube_dl/options.py 
3. 在 options.py 中找到 第44行，你可以看到这行代码: optionf = open(filename_bytes)
4. 将其修改为：optionf = open(filename_bytes, 'r', encoding='UTF-8')
5. 保存
6. 关闭命令行
7. 重开打开命令行，并运行 youtube-dl [URL] 命令

# 经过上面的修改，您的程序应该能够正常运行了，因为我目前就是这样解决的。

-----------------------
machine translation

## I found this problem at the moment, gbk encoding error. Now I have solved it.

# The solution is as follows:

1. You need to run the task (download video) from the source code of youtube-dl. If it is youtube-dl.exe, it cannot be modified.
2. Find youtube_dl / options.py in the source file
3. Locate line 44 in options.py, you can see this line of code: optionf = open (filename_bytes)
4. Modify it to: optionf = open (filename_bytes, 'r', encoding = 'UTF-8')
5. Save
6. Close the command line
7. Reopen to open the command line and run the youtube-dl [URL] command

# After the above modification, your program should be able to run normally, because this is how I solve it now.
