### ISSUE TITLE
yadi.sk does not work

### ISSUE THREAD

**Issue by LyoSU** [rg3/youtube-dl#16147]
youtube-dl -F https://yadi.sk/d/Bc70Zv5s3UDeMm
[YandexDisk] Bc70Zv5s3UDeMm: Downloading webpage
[YandexDisk] Bc70Zv5s3UDeMm: Downloading webpage
ERROR: Unable to extract video JSON; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
There is no video on this page.
