### ISSUE TITLE
youtube-dl not support this site, please add .

### ISSUE THREAD

**Issue by design365** [rg3/youtube-dl#16143]
when i use youtube-dl to parse :https://www4.9anime.is/watch/juushinki-pandora.xq1w/znol8w
youtube-dl give me : 
ERROR: Unsupported URL: https://www4.9anime.is/watch/juushinki-pandora.xq1w/znol8w

please add this site support, thanks!

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
