### ISSUE TITLE
How to download a batch file by EMBEDDING YOUTUBE-DL Python

### ISSUE THREAD

**Issue by kangland** [rg3/youtube-dl#16145]
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2018.04.09
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: none
[debug] Proxy map: {}
```

I don't know how use  Available options in Python.

-a option seems like not in [Available options](https://github.com/rg3/youtube-dl/blob/3e4cedf9e8cd3157df2457df7274d0c842421945/youtube_dl/YoutubeDL.py#L137-L312)

**Comment by dstftw** [comment]
No such option. You must provide list of URLs to download method yourself.
