### ISSUE TITLE
How to automatically "like" Youtube videos?

### ISSUE THREAD

**Issue by pvonmoradi** [rg3/youtube-dl#16168]
I use youtube-dl to download many youtube tutorials in the form of whole channels and playlists. However, since some content producers rely on the view and like count metrics of their videos, I like to automatically "push like button" their videos.   
**1-** How to automatically "**like**" youtube videos before/while/after downloading process?
**2-** Does downloading via youtube-dl increment the "**view count**" of the downloaded video? If not, how to do it?

I just wanna support content producers. Thanks for this great utility.
### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)
- [x] Question

**Comment by dstftw** [comment]
1. Not possible.
2. Unlikely. No explicit way to do so.
