### ISSUE TITLE
postprocessor-args used more than once

### ISSUE THREAD

**Issue by izlence** [rg3/youtube-dl#16166]
Hello,
When using "postprocessor-args" it may be called more than once. For example I wanted to speed the audio 1.55x but done twice. So the speed of the result file is more than 2X.
Original video duration: 4:35
Result audio duration: 1:54

Command:
youtube-dl -v --no-mtime --audio-format mp3 -x  --postprocessor-args "-acodec libmp3lame -af 'dynaudnorm=f=500:g=33, atempo=1.55'" "m4JowCM3urk";

Output:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--no-mtime', u'--audio-format', u'mp3', u'-x', u'--postprocessor-args', u"-acodec libmp3lame -af 'dynaudnorm=f=500:g=33, atempo=1.55'", u'm4JowCM3urk']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.09
[debug] Python version 2.7.14 (CPython) - Linux-4.13.0-38-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] m4JowCM3urk: Downloading webpage
[youtube] m4JowCM3urk: Downloading video info webpage
[youtube] m4JowCM3urk: Extracting video information
[youtube] m4JowCM3urk: Downloading MPD manifest
[youtube] m4JowCM3urk: Downloading MPD manifest
[debug] Invoking downloader on u'https://r13---sn-bvvbax-vu2e.googlevideo.com/videoplayback/id/9b8268c02337bab9/itag/140/source/youtube/requiressl/yes/mn/sn-bvvbax-vu2e,sn-h0jeen7r/nh/EAM,/initcwndbps/582500/ms/au,onr/mv/m/pl/21/mm/31,26/ei/otnOWv22CoHGgAeR97WgAg/ratebypass/yes/mime/audio%2Fmp4/otfp/1/gir/yes/clen/4374441/lmt/1523331121708494/dur/275.179/mt/1523505452/fvip/2/ip/XX.XX.XX.XX/ipbits/0/expire/1523527170/sparams/ip,ipbits,expire,id,itag,source,requiressl,mn,nh,initcwndbps,ms,mv,pl,mm,ei,ratebypass,mime,otfp,gir,clen,lmt,dur/signature/3CF4BF1E96219A0DFE0FA8BC4BFD554DAB4803A5.9AD83ECCD85D0772000BF98B99F109D3A11F028B/key/dg_yt0/'
[dashsegments] Total fragments: 57
[download] Destination: Proof of God’s existence-m4JowCM3urk.m4a
[download] 100% of 4.17MiB in 00:15
[ffmpeg] Correcting container in "Proof of God’s existence-m4JowCM3urk.m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Proof of God’s existence-m4JowCM3urk.m4a' -c copy -f mp4 -acodec libmp3lame -af 'dynaudnorm=f=500:g=33, atempo=1.55' 'file:Proof of God’s existence-m4JowCM3urk.temp.m4a'
[debug] ffmpeg command line: ffprobe -show_streams 'file:Proof of God’s existence-m4JowCM3urk.m4a'
[ffmpeg] Destination: Proof of God’s existence-m4JowCM3urk.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:Proof of God’s existence-m4JowCM3urk.m4a' -vn -acodec copy -acodec libmp3lame -af 'dynaudnorm=f=500:g=33, atempo=1.55' 'file:Proof of God’s existence-m4JowCM3urk.mp3'
Deleting original file Proof of God’s existence-m4JowCM3urk.m4a (pass -k to keep)

**Comment by dstftw** [comment]
This is expected behavior. `--postprocessor-args` are simply passed to each postprocessor's invocation.
