### ISSUE TITLE
Unable to Download from Hotstar and Voot

### ISSUE THREAD

**Issue by lovablegce** [rg3/youtube-dl#16179]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.09**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Earlier I was able to download videos from hotstar and voot without any issues. After the last update (i.e. 2018.04.09) unable to download any video from hotstar and voot. File is started getting downloaded and it's stopped halfway without throwing any error. It is keep waiting and not proceeding further.

Video Url: http://www.hotstar.com/tv/ninaika-therintha-maname/16150/lalitha-blames-karthika/1100003108

It is stopped downloading after 10th segment, please refer the below screenshot,

![image](https://user-images.githubusercontent.com/33035920/38752599-684ce248-3f79-11e8-9b44-ae9bfaba16eb.png)

It stops at random position each time, but it never complete the download. Please resolve the issue.

**Comment by lovablegce** [comment]
Hi

Could you please let me know why did you closed it, if you need any further details I can provide you. Are you able to download from hotstar?

**Comment by dstftw** [comment]
Bother to read issue template and fill it appropriately.
