### ISSUE TITLE
BiliBili playlist overwriting its own existing files

### ISSUE THREAD

**Issue by yumingchang8587** [rg3/youtube-dl#16183]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
markchang@server /s/s/m/bilibili> youtube-dl -v "https://www.bilibili.com/video/av9065470"
[debug] System config: ['-o', '%(title)s.%(ext)s', '-f', 'bestvideo[height<=?1080]+bestaudio/best', '--ignore-errors', '--retries', 'infinite', '--recode-video', 'mp4']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bilibili.com/video/av9065470']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.09
[debug] Python version 3.6.4 (CPython) - Linux-4.15.15-1-ARCH-x86_64-with-arch-18.3-ISO-Rolling
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[BiliBili] 9065470: Downloading webpage
[BiliBili] 9065470: Downloading video info page
[download] Downloading playlist: 【ACI字幕组】空中浩劫S17E02:康姆航空3272号班机【1080P 中英双语】
[BiliBili] playlist 【ACI字幕组】空中浩劫S17E02:康姆航空3272号班机【1080P 中英双语】: Collected 7 video ids (downloading 7 of them)
[download] Downloading video 1 of 7
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/33/82/14978233/14978233-1-80.flv?um_deadline=1523694207&platform=pc&rate=411400&oi=2356233270&um_sign=a374270a5cbe195ec081e3294cc0de9f&gen=playurl&os=cos&trid=5990cabbce914cae932645124998cb19'
[download] Resuming download at byte 57503471
[download] Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv
[download] 100% of 80.82MiB in 00:50
[ffmpeg] Converting video from flv to mp4, Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4
[debug] ffmpeg command line: ffmpeg -y -i 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv' 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4'
Deleting original file 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv (pass -k to keep)
[download] Downloading video 2 of 7
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/33/82/14978233/14978233-2-80.flv?um_deadline=1523694207&platform=pc&rate=416500&oi=2356233270&um_sign=99b822f821ffc0d7827dea80bd55fe9e&gen=playurl&os=cos&trid=5990cabbce914cae932645124998cb19'
[download] Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv
[download] 100% of 84.66MiB in 03:00
[ffmpeg] Converting video from flv to mp4, Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4
[debug] ffmpeg command line: ffmpeg -y -i 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv' 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4'
Deleting original file 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv (pass -k to keep)
[download] Downloading video 3 of 7
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/33/82/14978233/14978233-3-80.flv?um_deadline=1523694207&platform=pc&rate=411400&oi=2356233270&um_sign=4c6601c8812c252f57ea8f859d60b316&gen=playurl&os=cos&trid=5990cabbce914cae932645124998cb19'
[download] Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv
[download] 100% of 84.37MiB in 03:03
[ffmpeg] Converting video from flv to mp4, Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4
[debug] ffmpeg command line: ffmpeg -y -i 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv' 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4'
Deleting original file 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv (pass -k to keep)
[download] Downloading video 4 of 7
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/33/82/14978233/14978233-4-80.flv?um_deadline=1523694207&platform=pc&rate=408000&oi=2356233270&um_sign=1fffeeac655d6aafbd814c8596dc602e&gen=playurl&os=cos&trid=5990cabbce914cae932645124998cb19'
[download] Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv
[download] 100% of 82.87MiB in 03:03
[ffmpeg] Converting video from flv to mp4, Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4
[debug] ffmpeg command line: ffmpeg -y -i 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv' 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4'
Deleting original file 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv (pass -k to keep)
[download] Downloading video 5 of 7
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/33/82/14978233/14978233-5-80.flv?um_deadline=1523694207&platform=pc&rate=419900&oi=2356233270&um_sign=00c722eebbefd9d9e83b766bd5ee5687&gen=playurl&os=cos&trid=5990cabbce914cae932645124998cb19'
[download] Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv
[download] 100% of 81.01MiB in 02:54
[ffmpeg] Converting video from flv to mp4, Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4
[debug] ffmpeg command line: ffmpeg -y -i 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv' 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4'
Deleting original file 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv (pass -k to keep)
[download] Downloading video 6 of 7
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/33/82/14978233/14978233-6-80.flv?um_deadline=1523694207&platform=pc&rate=404600&oi=2356233270&um_sign=afc7cf225036ba50dc9966e2f484d1a0&gen=playurl&os=cos&trid=5990cabbce914cae932645124998cb19'
[download] Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv
[download] 100% of 87.33MiB in 03:16
[ffmpeg] Converting video from flv to mp4, Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4
[debug] ffmpeg command line: ffmpeg -y -i 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv' 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4'
Deleting original file 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv (pass -k to keep)
[download] Downloading video 7 of 7
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/33/82/14978233/14978233-7-80.flv?um_deadline=1523694207&platform=pc&rate=411400&oi=2356233270&um_sign=7c3f8e2b3a5de1271d36f85ebf5aad33&gen=playurl&os=cos&trid=5990cabbce914cae932645124998cb19'
[download] Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv
[download] 100% of 110.04MiB in 04:05
[ffmpeg] Converting video from flv to mp4, Destination: 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4
[debug] ffmpeg command line: ffmpeg -y -i 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv' 'file:【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.mp4'
Deleting original file 【ACI字幕组】空中浩劫S17E02 -康姆航空3272号班机【1080P 中英双语】.flv (pass -k to keep)
[download] Finished downloading playlist: 【ACI字幕组】空中浩劫S17E02:康姆航空3272号班机【1080P 中英双语】

---

### Description of your *issue*, suggested solution and other information
sites like bilibili will slice the videos to multiple small slices, same thing is met on part of youtube videos, however, instead of merging all the small parts from the video ( youtube-dl with bilibili, it is showed as playlist? ) together, youtube-dl downloads it one by one, which in combination with "%(title)s.%(ext)s"
as output format, will cause the fragmented video to be downloaded, and overwrite the front halves of the already downloaded slices, ( an example will be https://www.bilibili.com/video/av9065470 , which have 7 slices of video in it, will eventually leave the last slice after downloaded as shown in the above log )

**Comment by dstftw** [comment]
You are using custom output template so now you are responsible for filename uniqueness. Don't touch it if you don't want to be responsible for it.

**Comment by mofeiwlj** [comment]
I met the same question. One video url will be download several parts and they won't be merged .eg:https://www.bilibili.com/video/av22589522/?spm_id_from=333.334.chief_recommend.16  @dstftw 
If i use `youtubedl -j https://www.bilibili.com/video/av22589522/?spm_id_from=333.334.chief_recommend.16` I got two parts json string.
