### ISSUE TITLE
audio and video metadata

### ISSUE THREAD

**Issue by exekutive** [rg3/youtube-dl#16195]
I would like to download a Youtube video into one muxed video file (audio+video), and one audio file, both with metadata. It seems to me that youtube-dl is only able to write metadata to one output file.

If I use the -k option, the muxed output file gets metadata, but the component streams get none.
If I use the -x option, I get an output audio file with metadata, but no muxed video file

I've read through the documentation, and searched the issues to no avail.

version 2018.04.16

**Comment by dstftw** [comment]
`-f audio_format,video_format`.

**Comment by exekutive** [comment]
Solved. Thanks.
