### ISSUE TITLE
write ID, URL to metadata

### ISSUE THREAD

**Issue by exekutive** [rg3/youtube-dl#16196]
I would like to be able to write a Youtube video's ID and/or URL to the output file metadata. My testing suggests that, using the 'add-metadata' option only the writes the video title, channel name (author), and description.

version 2018.04.16

**Comment by dstftw** [comment]
URL is already written.

**Comment by exekutive** [comment]
Please show me where.

![screen shot 2018-04-15 at 21 55 35](https://user-images.githubusercontent.com/4755215/38790722-e63288dc-40f7-11e8-863b-c29793919b97.png)
![screen shot 2018-04-15 at 21 56 28](https://user-images.githubusercontent.com/4755215/38790723-e6509250-40f7-11e8-84a6-8c1c1bb4d572.png)

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/postprocessor/ffmpeg.py#L420
Not all formats support this metafield.

**Comment by exekutive** [comment]
Sorry, I don't understand source code. Can you please elaborate ...
Is it an issue with the input format, or output?

I think it would be nice to at least write at least something, like URL or ID, to the album field or whatever. It's important to record where a video was downloaded from.

**Comment by exekutive** [comment]
which formats DO support it?

**Comment by Najrim** [comment]
I was trying to do the same thing. In case someone else is having trouble, here's how it works:

* Use the --add-metadata option when you download something
* Open the downloaded file in a tag editor such as Ex Falso. The url is in a field called `purl`.
* If you want it to be in the album field, find a method to copy it over.
    * In Ex Falso it's simple. Double blick `purl` and replace it with `album` or whatever you want it to be.

**Comment by exekutive** [comment]
Nope. Still don't see it.

![screen shot 2018-11-28 at 23 11 13](https://user-images.githubusercontent.com/4755215/49205140-f22a4080-f362-11e8-9c06-45877e5fd090.png)

**Comment by Najrim** [comment]
It doesn't need to be a pure music file. If your config is empty you will get the `PURL` tag in a mkv file if you do:

```
youtube-dl --add-metadata --audio-format ogg youtube.com/watch?v=videoid
```

**Comment by exekutive** [comment]
MP4, because it's widely adopted.
I never use ogg, flac or mkv.
Like I suggested before: If a URL tag isn't directly supported, then it could written to one of the many other tags, such as album (since it is not used anyway).

**Comment by Najrim** [comment]
Seems someone is working on it: #17904 

Really looking forward to this. Thanks @mx1up

When this is merged I think we can write something like `--postprocessor-args "-id3v2_version 3 -metadata album=%(url)s".

**Comment by mx1up** [comment]
yep, that's correct :) it already works here locally but requires some review by @dstftw / youtube-dl team before it can be merged.

**Comment by exekutive** [comment]
Great! I hope the author decides it's worthwhile this time and not just dismiss it.

**Comment by megapro17** [comment]
> Seems someone is working on it: #17904
> 
> Really looking forward to this. Thanks @mx1up
> 
> When this is merged I think we can write something like `--postprocessor-args "-metadata album=%(url)s"`.

Not working anymore

**Comment by mx1up** [comment]
I'll have a look

**Comment by megapro17** [comment]
So I think problem is here https://github.com/ytdl-org/youtube-dl/pull/17904

**Comment by exekutive** [comment]
> Seems someone is working on it: #17904
> 
> Really looking forward to this. Thanks @mx1up
> 
> When this is merged I think we can write something like `--postprocessor-args "-metadata album=%(url)s"`.

It's not working for me. Is it still being worked on?

**Comment by megapro17** [comment]
> > Seems someone is working on it: #17904
> > Really looking forward to this. Thanks @mx1up
> > When this is merged I think we can write something like `--postprocessor-args "-metadata album=%(url)s"`.
> 
> It's not working for me. Is it still being worked on?

Just use webm or mkv

**Comment by exekutive** [comment]
no thanks. Those are useless formats.

**Comment by megapro17** [comment]
Your life is useless

**Comment by exekutive** [comment]
I think you need to unplug yourself from the computer once in a while.

**Comment by megapro17** [comment]
I think you need to use open and free containers instead of closed, proprietary, patented shit called mp4

**Comment by exekutive** [comment]
I think that it's none of your business what I use. I also think you are taking this matter far too personally. I also think you need a reality check. MP4 plays on everything. The containers you call "open and free" are actually "not widely adopted". I also think you have nothing valuable to add to this thread and are wasting your time.

**Comment by con-f-use** [comment]
So is there currently a way to embed the video URL in the meta data?

Because when I do something like:

```console
$ youtube-dl --add-metadata --postprocessor-args "-metadata copyright=%(url)s" -f "bestvideo[ext=webm]+bestaudio/best"
```

What I get is:

![image](https://user-images.githubusercontent.com/11145016/58375422-07b7a600-7f53-11e9-9252-d5334f43e082.png)

----

What format people want is up to them. However, if they choose to use non-open ones, they shoudn't be surprised when other software can't play nice with their choice.

**Comment by exekutive** [comment]
MP4 uses a standard ISO container. Show me where it says you need licensed software to write metadata.

**Comment by sepehrkiller** [comment]
can we do anything to save in a txt file or in metadata file? or the .description file?
anyone knows anything about this? it would be cool to be able to save url in a txt file alongside the video

**Comment by jxu** [comment]
@sepehrkiller it is saved in `--write-info-json` which can be filtered with `jq`. alternatively `--get-url` and `--get-id` will print to stdout

**Comment by con-f-use** [comment]
[Videolan Client (VLC) Media Player](https://www.videolan.org/)
