### ISSUE TITLE
RayWenderlich Video Download: Unable to log in: bad username or password

### ISSUE THREAD

**Issue by partho-maple** [rg3/youtube-dl#16192]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.09**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
---

```
$  youtube-dl -u <user> -p <password> https://videos.raywenderlich.com/courses/105-testing-in-ios/lessons/2
[RayWenderlich] 105-testing-in-ios/2: Downloading webpage
[RayWenderlich] Downloading playlist 105-testing-in-ios - add --no-playlist to just download video
[download] Downloading playlist: Testing in iOS
[RayWenderlich] playlist Testing in iOS: Collected 29 video ids (downloading 29 of them)
[download] Downloading video 1 of 29
[RayWenderlich] 105-testing-in-ios/1: Downloading webpage
[vimeo] Downloading login page
[vimeo] Logging in
ERROR: Unable to log in: bad username or password
```

---
---

I am trying to download a playlist from raywenderlich.com to check on offline later when i found some time. And i have the subscription.  My credentials are working fine on web and i am able to see the video online. And also my password doesn't contain any special character, it's plain numeric. What could be possible issue and solution ? I have provided my logs from terminal.
.

**Comment by partho-maple** [comment]
Hi @dstftw ,

I didn't get, how this issue is a duplicate one ?
It's a different problem showing a different issue. I have searched through all of the issue regarding raywenderlich.com but didn't find any such issue. Could u please tell me how it's a duplicate ?  And also please provide the original issue like. 
I am afraid if i mussed anything.
Thanks though.

**Comment by dstftw** [comment]
Authentication is not supported.
