### ISSUE TITLE
[Question] How do I download from the beginning of the stream?

### ISSUE THREAD

**Issue by MichaelDeBoey** [rg3/youtube-dl#16208]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Question

---

I'm trying to download https://livestream.com/accounts/4894689/events/8162314/player from the beginning of the stream (playback is possible), but when I run
```
youtube-dl https://livestream.com/accounts/4894689/events/8162314/player
```
it start's from the current time, not the beginning.

Can't find any parameters I should pass.
Can somebody help me please?

CC: @dstftw

**Comment by dstftw** [comment]
```
youtube-dl --hls-prefer-native 'https://secure-playlist.livestream.com/streams/4894689_8162314_lsizamq79pa5h9cft11_1/media/4894689_8162314_lsizamq79pa5h9cft11_1@4628000pb.m3u8?dw=14400&storage=iss&token=1524159132_381570fb6b9eb66c84d4eecf900d0061e6adb943&ts=1523984400'
```
This will only download from beginning till now though.

**Comment by MichaelDeBoey** [comment]
@dstftw So how do I get that info, so I can find this myself the next time?

**Comment by dstftw** [comment]
See network requests of your browser.

**Comment by MichaelDeBoey** [comment]
Thanks @dstftw! 🎉
