### ISSUE TITLE
Unable to download content for paid subscribers on MyCanal.fr (CanalPlus support)

### ISSUE THREAD

**Issue by jrmio** [rg3/youtube-dl#16216]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v "https://www.mycanal.fr/decouverte/japon-investigation/h/6565478_50033" -u --MyCanalLogin -p --MyCanalPwd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.mycanal.fr/decouverte/japon-investigation/h/6565478_50033', u'-u', u'PRIVATE', u'-p', u'PRIVATE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.16
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-5-amd64-x86_64-with-debian-9.3
[debug] exe versions: ffmpeg 2.8.4-static, ffprobe 2.8.4-static, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 6565478_50033: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6565478_50033: Downloading webpage
[generic] 6565478_50033: Extracting information
ERROR: Unsupported URL: https://www.mycanal.fr/decouverte/japon-investigation/h/6565478_50033
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2216, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3166, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.mycanal.fr/decouverte/japon-investigation/h/6565478_50033
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

* What the problem is: since Canal Plus Group has rebranded all of its channels as a single portal, the youtube-dl [extractor](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/canalplus.py) became out of service
* How it could be fixed: by updating current [extractor](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/canalplus.py)
* I tested with several *mycanal.fr* URLs before submitting this report
* I removed my credentials from the log
* There is no issue when trying with [free content](https://www.mycanal.fr/chaines/), only with content for paid subscribers ([e.g.](https://www.mycanal.fr/decouverte/la-guerre-des-opossums/h/2396601_50068))

**Comment by jrmio** [comment]
How can I help without sharing credentials of my paid subscription?

**Comment by jrmio** [comment]
How can I help without sharing credentials of my paid subscription? I believe that you can get a free month by subscribing [here](https://boutique.canal.fr/product/ESS/essentiel/1?clkid=302399220709506214134120415594629991601851044873&ectrans=1), then you must cancel the subscription once your account is ready, so you will keep your free month only.

**Comment by dstftw** [comment]
Then go and get it.

**Comment by jrmio** [comment]
I can't! My payment information is already used for my paid subscription. How can you guys expect strangers sharing their credentials with you???

**Comment by dstftw** [comment]
How can you expect us to add support without having an account in the first place? Providing account is **your** responsibility.
