### ISSUE TITLE
This Old House: Index Error: list index out of range

### ISSUE THREAD

**Issue by ianh01** [rg3/youtube-dl#16228]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.thisoldhouse.com/watch/ask-toh-pass-through-new-gate']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.04.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[ThisOldHouse] ask-toh-pass-through-new-gate: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9r95p1_v\build\youtube_dl\__init__.py", line 471, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9r95p1_v\build\youtube_dl\__init__.py", line 461, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9r95p1_v\build\youtube_dl\YoutubeDL.py", line 1993, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9r95p1_v\build\youtube_dl\YoutubeDL.py", line 789, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9r95p1_v\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9r95p1_v\build\youtube_dl\extractor\thisoldhouse.py", line 43, in _real_extract
IndexError: list index out of range
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- https://www.thisoldhouse.com/watch/ask-toh-pass-through-new-gate
- https://www.thisoldhouse.com/watch/ask-toh-citrus-greening-tile
- https://www.thisoldhouse.com/watch/ask-toh-front-door-faucet-fix
- https://www.thisoldhouse.com/watch/veterans-special-house-project-veterans-special-house-project
- https://www.thisoldhouse.com/watch/veterans-special-house-project-adaptation-accessibility

---

### Description of your *issue*, suggested solution and other information

Seasons 1-13 of Ask This Old House and seasons 1-36 of This Old House will not download.  I get an "IndexError" as listed above.  I have an account login for www.thisoldhouse.com that I can provide if needed.  Please feel free to contact me at ianh01@excite.com

**Comment by dstftw** [comment]
You did not pass credentials to youtube-dl.

**Comment by ianh01** [comment]
My username is ianh01@excite.com
Password is macworld
 
-----Original Message-----

**Comment by ianh01** [comment]
Username is ianh01@excite.com
Password is Hj7@wt6*s

**Comment by ianh01** [comment]
Username is ianh01@excite.com
Password is Hj7@wt6*s
 
 
-----Original Message-----
