### ISSUE TITLE
How can I determine the directory that the video will be saved to (or was saved to) via a python script?

### ISSUE THREAD

**Issue by FunkyLoveCow** [rg3/youtube-dl#16224]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### How can I determine the directory that the video will be saved to (or was saved to) via a python script?

I am attempting to download multiple video files, but also want to save some of the meta data that is provided by `extract_info` to a separate file which is stored with the video file. My script to download looks like this:

```
import youtube_dl

ydl_opts = {
        'retrictfilenames': True,
        'outtmpl': "%(title)s-%(id)s/%(title)s-%(id)s-%(resolution)s.%(ext)s"
    }

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    link = 'https://www.youtube.com/watch?v=BaW_jenozKc'
    ydl.download([link])
    meta = ydl.extract_info(link, download=False)
```

At this point, I'd like to write specific values from `meta` to a file in the `%(title)s-%(id)s` directory specified in `ydl_opts`. I'd do this with something like the following immediately after the `meta = ydl.extract_info(...)` line above:

```
with open("<DIRECTORY>/metadata.txt", "w") as f:
    # write values
```

How do I specify the *value* of `<DIRECTORY>` to be in the `with open` line? I just need the know how to access the *value* that `ydl_opts['outtmpl']` becomes. I can parse the directory out on my own.

**Comment by dstftw** [comment]
```
ydl.params['outtmpl'] = '"%(title)s-%(id)s/metadata.txt'
with open(ydl.prepare_filename(info) ...
   ...
```
