### ISSUE TITLE
Multiple formats results in multiple thumbnails, info files

### ISSUE THREAD

**Issue by sngbrdb** [rg3/youtube-dl#16220]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When specifying multiple formats to download (comma-separated list in the --format option), youtube-dl executes all options multiple times.  This results in multiple, duplicate thumbnail and information files.  

For example, ` youtube-dl hTGJfRPLe08 ` with the following options:

    --format best,bestvideo+bestaudio
    -o 'p:/vids/%(uploader)s - %(title)s  %(id)s  %(upload_date)s [%(resolution)s %(duration)ss] [%(format_id)s].%(ext)s'

Will give you two thumbnails with names matching the format downloaded - in the above example, the files are:

    JamiexxVEVO - Jamie xx - Gosh  hTGJfRPLe08  20161004 [1280x720 323s] [22].jpg
    JamiexxVEVO - Jamie xx - Gosh  hTGJfRPLe08  20161004 [1920x1080 323s] [137+251].jpg

However, they are duplicates of a 1280x720 thumbnail.  The same is true for the .description and .info.json files.

I get why it happens - if you only had one thumbnail, which video would you use for values?  But it makes no sense to include values that don't apply to the thumbnail... either the values should be consistent and taken from the thumbnail itself (e.g. 1280x720 regardless of the video size), or there needs to be a way to give the thumbnail and info files a different naming convention so they are not duplicated.  Simply using the first or best-quality video format would be okay, though not ideal.

The --exec also executes multiple times for multiple video formats... I can see why it's done that way, but I'd argue that multiple --format entries is a directive to run youtube-dl and its options once with multiple results, while the need to manipulate multiple videos should be handled as multiple executions of youtube-dl in a script.

**Comment by dstftw** [comment]
This is expected behavior for now.
