### ISSUE TITLE
If I have link to m3u8 file, how can I download a video?

### ISSUE THREAD

**Issue by hasnogaems** [rg3/youtube-dl#16229]
Link to a file in a format: https://cdn-video-eu.anonimoushost.com/1286/original-1502815510-1080p/1080p.m3u8

**Comment by dstftw** [comment]
cdn-video-eu.anonimoushost.com does not exist.

**Comment by hasnogaems** [comment]
Sorry, wrong link. This https://cdn-video.pvgna.com/1323/original-1503685303-1080p/1080p.m3u8 is the correct one.

**Comment by hasnogaems** [comment]
Sorry, wrong link. This https://cdn-video.pvgna.com/1323/original-1503685303-1080p/1080p.m3u8 is the correct one.
