### ISSUE TITLE
How can I determine which format is selected when using `bestvideo+bestaudio`?

### ISSUE THREAD

**Issue by NewbieNooberton** [rg3/youtube-dl#16237]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### How can I determine which format is selected when using `bestvideo+bestaudio`?

```
import youtube-dl
opts = {
    'format': 'bestvideo+bestaudio'`
}
with youtube_dl.YoutubeDL(opts) as ydl:
    data = ydl.extract_info('https://www.youtube.com/watch?v=BaW_jenozKc')
```

How can I determine, from the `data['format']` list, which formats will be selected as `'bestvideo+bestaudio'` that were specified in my `opts` dictionary?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient

**Comment by NewbieNooberton** [comment]
My apologies @dstftw . I don't mean to waste your time.  I have added a bit to the original post. I hope that more clearly describes what I'm hoping to achieve.

**Comment by dstftw** [comment]
`data['format_id']` contains format codes of selected formats.
