### ISSUE TITLE
How do I dump JSONs from a search as soon as they are available?

### ISSUE THREAD

**Issue by costcoterrorist** [rg3/youtube-dl#16235]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### How do I dump video JSON's as they become available?

Running youtube-dl as a shell application with `youtube-dl --dump-json "ytsearch8:vinesauce"` dumps each JSON to stdout as soon as it finishes. However, running it as a python module causes it to be buffered until the entire search is finished:
```
ydl_opts = {
    'simulate': True
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    print(ydl.extract_info('ytsearch8:vinesauce'))
```
How do I get JSON's as soon as they are available in a python script?

**Comment by dstftw** [comment]
By splitting into several requests.
