### ISSUE TITLE
Question: Do youtube extracted links change?

### ISSUE THREAD

**Issue by devingDev** [rg3/youtube-dl#16240]
I have a question. About youtube. Imagine if I got a link to the audio (mp3 or similiar) will the link change  or will it stay same for everyone for ever? 

Anyone have insights in this?

I kinda wanna make an app use the links extracted but I would like to cache em and make em shareable.

Is that possible or do I have to assume the link will change?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser
