### ISSUE TITLE
Better handling for partially recorded Twitch videos.

### ISSUE THREAD

**Issue by chrisgavin** [rg3/youtube-dl#16259]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When using youtube-dl to archive a particular Twitch channel, if the channel is currently broadcasting you will only obtain a partial recording of the current broadcast. This partial recording is recorded in the download archive the same way as any other recording, therefore it will never be updated, even when the full recording becomes available.

Not downloading partially recorded videos is actually quite easy, the JSON response from the Twitch API lists the video as `"status": "recording"`, so I'm mostly opening this issue as a discussion on how this should be implemented. Should there just be a flag to not download partial recordings (or should it even be the default when downloading a playlist/channel)? Should they be downloaded, but recorded differently in the download archive so a complete copy will still be downloaded when it is ready? I'd be very interested to hear what more experienced youtube-dl developers think.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/12946#issuecomment-298299093

**Comment by chrisgavin** [comment]
Ah, awesome. It's good to know there's a known way to implement it. So I should just fix the Twitch extractor so it sets the `is_live` property correctly?

**Comment by dstftw** [comment]
This will skip all live streams like https://www.twitch.tv/paradoxinteractive. I don't know whether this will work in your case - you did not provide any example URL.

**Comment by chrisgavin** [comment]
I was thinking mostly of user pages, for example `https://www.twitch.tv/valkia/videos/all`, where the newest VoD on the page is incomplete because it's for a stream that is live now.

**Comment by dstftw** [comment]
Will work in the next version.

**Comment by chrisgavin** [comment]
Awesome, thanks so much.
