### ISSUE TITLE
[QUESTION] How do I watch a video as it is downloading?

### ISSUE THREAD

**Issue by NightMachinary** [rg3/youtube-dl#16260]
I know `youtube-dl -o - "https://www.youtube.com/watch?v=BaW_jenozKcj" | vlc -` streams to vlc, but I want the file to be saved locally for later use as well, without consuming double internet traffic.

**Comment by dstftw** [comment]
Either download directly to file and play that file or pipe through tee.

**Comment by NightMachinary** [comment]
@dstftw Thanks! You made my day ^_^
