### ISSUE TITLE
On Udemy : "Unable to download webpage: HTTP Error 403: Unauthorized"

### ISSUE THREAD

**Issue by nicolas0dupuy** [rg3/youtube-dl#16264]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
 [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.udemy.com/complete-gaming-package-learn-to-code-in-unity-and-unreal']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.16
[debug] Python version 3.6.3 (CPython) - Linux-4.13.16-302.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven
[debug] exe versions: ffmpeg 3.3.5, ffprobe 3.3.5
[debug] Proxy map: {}
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by <HTTPError 403: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/ndupuy/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 519, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/ndupuy/anaconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2203, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/home/ndupuy/anaconda3/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/ndupuy/anaconda3/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ndupuy/anaconda3/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/ndupuy/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/ndupuy/anaconda3/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

### Description of your *issue*, suggested solution and other information

Issue I have met before, previously solved with an updated version of youtube-dl (update accordingly to new standards on udemy if I am right).
youtube-dl first worked allright to download my last Udemy courses, then did not work anymore on this one.
I could download part of the video, then it crashed. When I tryed to resume it also crashes

Thanks for any help

**Comment by sutt** [comment]
I get the following error on the course's home page:
ExtractorError: Course 1016110 is not free. You have to pay for it before you can download. Use this URL to confirm purchase: https://www.udemy.com/cart/checkout/express/course/1016110/?discountCode=1804CHANGE11C2
I don't know how to debug or fix this without the credentials to access the course material

**Comment by nicolas0dupuy** [comment]
Yes, I use udemy-dl to download video courses I allready purchased to watch them offline. With my email/password it should therefore work (and it worked properly since last sunday)
