### ISSUE TITLE
Please, provide a changelog

### ISSUE THREAD

**Issue by rbrito** [rg3/youtube-dl#1626]
Hi.

Wearing my downstream hat, it would be nice to have a changelog that I can ship to users.

I have one that asked me how I provide the Debian changelogs on the Debian packaging and I replied "by reading the source code", which after thinking a bit, is some duplicated effort for other distributions that don't benefit from my work.

Can you provide something as a changelog? Even something like a `git shortlog --no-merges` would be helpful and (hopefully, not too noisy), which is, BTW, what Linus Torvalds himself uses to announce newer kernel releases.

Thanks in advance,

Rogério.

**Comment by shirishag75** [comment]
oh goody, this is/would be good, exactly what I was gonna ask for, thanx rbrito :)

**Comment by dntt1** [comment]
please create it or assist me creating it

**Comment by yan12125** [comment]
Added in 35aa6c538f593eb47169e6b06ef383ad12b45930.
