### ISSUE TITLE
Unsupported URL error

### ISSUE THREAD

**Issue by njofra22** [rg3/youtube-dl#16273]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.25**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v https://video.kqed.org/video/the-secret-of-tuxedo-park-zfeomc/ 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://video.kqed.org/video/the-secret-of-tuxedo-park-zfeomc/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.25
[debug] Python version 2.7.13 (CPython) - Linux-4.11.12-100.fc24.x86_64-x86_64-with-fedora-24-Twenty_Four
[debug] exe versions: ffmpeg 3.1.9, ffprobe 3.1.9
[debug] Proxy map: {}
[generic] the-secret-of-tuxedo-park-zfeomc: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-secret-of-tuxedo-park-zfeomc: Downloading webpage
[generic] the-secret-of-tuxedo-park-zfeomc: Extracting information
ERROR: Unsupported URL: https://video.kqed.org/video/the-secret-of-tuxedo-park-zfeomc/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2232, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3182, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://video.kqed.org/video/the-secret-of-tuxedo-park-zfeomc/

```

---

### Description of your *issue*, suggested solution and other information

Can not download free videos  from pbs - kqed website.

**Comment by rajiv** [comment]
this might be fixed by #16474.

**Comment by njofra22** [comment]
No, it is not :(
Updated the version to:
[debug] youtube-dl version 2018.05.18

Still the same error

**Comment by rajiv** [comment]
if you change the hostname to `www.pbs.org` it works: `youtube-dl -v 'http://www.pbs.org/video/the-secret-of-tuxedo-park-zfeomc/'`

i'm not sure it's practical to add all the pbs affiliates' hostnames into youtube-dl.

**Comment by njofra22** [comment]
Makes sense. Though, there are video content that is posted on the affiliate's site only (local content). How can I update youtube-dl by myself? Is there a "database" file of hostnames?

**Comment by Hrxn** [comment]
Nope, no database of hostnames or anything in that regard..

But what about changing the URL of the item that is only on the affiliate site? Maybe this still does work..

**Comment by njofra22** [comment]
Tx for the idea. It's working.
