### ISSUE TITLE
How to disable full scan the whole channel if I use --dateXXX command to download videos.

### ISSUE THREAD

**Issue by Power3D** [rg3/youtube-dl#16283]
I use these commands:
youtube-dl -i --dateafter now-1day -o "E:\Videos\Xinshidandan\%(upload_date)s-%(title)s-%(id)s.%(ext)s" --all-subs -f "bestvideo[ext!=webm]‌​+bestaudio[ext!=webm]‌​/best[ext!=webm]" "https://www.youtube.com/channel/UCdMbdrQAh0-zOWb2eenXE_A/videos"

You can see I just want to download videos in 1 day published. But the program still scan all of the videos of the channel to recognize the date (I guess). Some channels have thousands of videos, that would be a nightmare.

How to download vidoes by date without scanning the whole channel?

**Comment by dstftw** [comment]
```
--playlist-start NUMBER          Playlist video to start at (default is 1)
--playlist-end NUMBER            Playlist video to end at (default is last)
--playlist-items ITEM_SPEC       Playlist video items to download. Specify
                                 indices of the videos in the playlist
                                 separated by commas like: "--playlist-items
                                 1,2,5,8" if you want to download videos
                                 indexed 1, 2, 5, 8 in the playlist. You can
                                 specify range: "--playlist-items
                                 1-3,7,10-13", it will download the videos
                                 at index 1, 2, 3, 7, 10, 11, 12 and 13.
```
