### ISSUE TITLE
Test_InfoExtractor Broken

### ISSUE THREAD

**Issue by vetschc** [rg3/youtube-dl#16280]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Issue I encountered was with \test\test_InfoExtractor.py file. 

When running the test locally, 3/9 tests are failing and returning "No such file or directory", specifically for the following file paths:

```FileNotFoundError: [Errno 2] No such file or directory: './test/testdata/mpd/float_duration.mpd'```

```FileNotFoundError: [Errno 2] No such file or directory: './test/testdata/m3u8/pluzz_francetv_11507.m3u8'```

```FileNotFoundError: [Errno 2] No such file or directory: './test/testdata/f4m/custom_base_url.f4m'```

I've Included the full output when running the test below:

```WARNING: [Test] None: Failed to parse JSON Expecting value: line 1 column 9 (char 8)
......EEE
======================================================================
ERROR: test_parse_f4m_formats (__main__.TestInfoExtractor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/cygwin64/home/Colin/IT_480_Repositories/youtube-dl/test/test_InfoExtractor.py", line 690, in test_parse_f4m_formats
    mode='r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './test/testdata/f4m/custom_base_url.f4m'

======================================================================
ERROR: test_parse_m3u8_formats (__main__.TestInfoExtractor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/cygwin64/home/Colin/IT_480_Repositories/youtube-dl/test/test_InfoExtractor.py", line 486, in test_parse_m3u8_formats
    mode='r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './test/testdata/m3u8/pluzz_francetv_11507.m3u8'

======================================================================
ERROR: test_parse_mpd_formats (__main__.TestInfoExtractor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/cygwin64/home/Colin/IT_480_Repositories/youtube-dl/test/test_InfoExtractor.py", line 663, in test_parse_mpd_formats
    mode='r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './test/testdata/mpd/float_duration.mpd'```

----------------------------------------------------------------------
Ran 9 tests in 0.278s

FAILED (errors=3)

Process finished with exit code 1
```

---

**Comment by dstftw** [comment]
The error in log speaks for itself.
