### ISSUE TITLE
Downloading fails with error 'no host given'

### ISSUE THREAD

**Issue by bertjanbakker** [rg3/youtube-dl#16282]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
~ $ youtube-dl "https://www.youtube.com/watch?v=3xDOdq-HENU" --verbose --dump-pages --no-check-certificate
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=3xDOdq-HENU', '--verbose', '--dump-pages', '--no-check-certificate']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.25
[debug] Python version 3.6.5 (CPython) - Linux-4.15.0-2-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {'https': 'http://', 'http': 'http://', 'ftp': 'http://'}
[youtube] 3xDOdq-HENU: Downloading webpage
ERROR: Unable to download webpage: <urlopen error no host given> (caused by URLError('no host given',))
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 519, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2203, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3/dist-packages/youtube_dl/utils.py", line 1101, in https_open
    req, **kwargs)
  File "/usr/lib/python3.6/urllib/request.py", line 1283, in do_open
    raise URLError('no host given')
```
---

### Description of your *issue*, suggested solution and other information

Downloading fails with error 'no host given'.

**Comment by dstftw** [comment]
Invalid proxy configuration in env variables.

**Comment by bertjanbakker** [comment]
Thanks

2018-04-26 0:01 GMT+02:00 Sergey M. <notifications@github.com>:
