### ISSUE TITLE
La7.it - ERROR: Unable to extract player data

### ISSUE THREAD

**Issue by asfluido** [rg3/youtube-dl#16311]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.la7.it/propagandalive/rivedila7/propaganda-live-28-04-2018-240280']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.25
[debug] Python version 2.7.14 (CPython) - Linux-4.15.0-rc8+-x86_64-Intel-R-_Core-TM-_i7-3840QM_CPU_@_2.80GHz-with-glibc2.2.5
[debug] exe versions: ffmpeg N-89656-g0c78b6a416, ffprobe N-89656-g0c78b6a416
[debug] Proxy map: {}
[la7.it] propaganda-live-28-04-2018-240280: Downloading webpage
ERROR: Unable to extract player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/src/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/usr/src/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/src/youtube-dl/youtube-dl/youtube_dl/extractor/la7.py", line 54, in _real_extract
    webpage, 'player data'),
  File "/usr/src/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 808, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Apparently equal to issue #15501, closed on 7 February.

**Comment by remitamine** [comment]
> video non disponibile
