### ISSUE TITLE
YouTube said: This video is not available

### ISSUE THREAD

**Issue by faicalbaki** [rg3/youtube-dl#16313]
Hi,

### I'm running the latest version.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.25**

I have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

The URL in question is: https://www.youtube.com/watch?v=nsC2bwEu5cw

I was able to download the same video from a Mac!! without any issues, and I have the same version 
running on the Linux machine.

After checking many other videos I have concluded this is a random behavior.

#### Debug output
```
dev@host1:~# youtube-dl -v https://www.youtube.com/watch?v=nsC2bwEu5cw 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=nsC2bwEu5cw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.25
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-101-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube] nsC2bwEu5cw: Downloading webpage
[youtube] nsC2bwEu5cw: Downloading video info webpage
ERROR: nsC2bwEu5cw: YouTube said: This video is not available.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1620, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: nsC2bwEu5cw: YouTube said: This video is not available.
```

**Comment by dstftw** [comment]
You did not provide account credentials.

**Comment by faicalbaki** [comment]
But why it's working without account credentials on my Mac? or am I missing something!!

**Comment by dstftw** [comment]
Prove it works in incognito tab without logging in.

**Comment by faicalbaki** [comment]
Here is my prof:

![screen shot 2018-04-28 at 11 56 51 am](https://user-images.githubusercontent.com/697488/39395817-596a293a-4adb-11e8-993e-9c92ffe07eb4.png)

**Comment by dstftw** [comment]
Again: prove you can view it in browser **at the same machine** where you're trying to run youtube-dl **with the same IP address**, without logging in and without any anonymizers.

**Comment by faicalbaki** [comment]
Yes I confirm the video can not be viewed from the machine I'm trying to run youtube-dl (HTTP/1.1 404 Not Found)

thanks & sorry for the inconvenience.
