### ISSUE TITLE
Download ISMV file without vedio and sound

### ISSUE THREAD

**Issue by mr3ayesh** [rg3/youtube-dl#16315]
youtube-dl -v https://prod.vod-ss.go.osn.com/2018/03/13/0609/BX-AM000837.ism
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://prod.vod-ss.go.osn.com/2018/03/13/0609/BX-AM000837.ism']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.04.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[generic] BX-AM000837: Requesting header
WARNING: Falling back on generic information extractor.
[generic] BX-AM000837: Downloading webpage
[generic] BX-AM000837: Extracting information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://prod.vod-ss.go.osn.com/2018/03/13/0609/BX-AM000837_1600.ismv'
[download] Destination: BX-AM000837-BX-AM000837.ismv
[download] 100% of 967.77MiB in 00:17

![screenshot_1](https://user-images.githubusercontent.com/38810758/39396342-d019c55c-4aec-11e8-9d78-23b374dc876f.jpg)

**Comment by remitamine** [comment]
~/Bento4/mp4info BX-AM000837_1600.ismv 
File:
  major brand:      isml
  minor version:    1
  compatible brand: iso2
  compatible brand: piff
  fast start:       yes

Movie:
  duration:   5202400 ms
  time scale: 10000000
  fragments:  yes

Found 1 Tracks
Track 1:
  flags:        3 ENABLED IN-MOVIE
  id:           5
  type:         Video
  duration: 5202400 ms
  language: und
  media:
    sample count: 0
    timescale:    10000000
    duration:     52024000000 (media timescale units)
    duration:     5202400 (ms)
    bitrate (computed): 1553.662 Kbps
    sample count with fragments: 130060
    duration with fragments:     52024000000
    duration with fragments:     5202400 (ms)
  display width:  768.000000
  display height: 432.000000
  Sample Description 0
    [ENCRYPTED]
      Coding:         encv
      Scheme Type:    piff
      Scheme Version: 65537
      Scheme URI:     
    Coding:      avc1 (H.264)
    Width:       768
    Height:      432
    Depth:       24
    AVC Profile:          77 (Main)
    AVC Profile Compat:   40
    AVC Level:            30
    AVC NALU Length Size: 4
    AVC SPS: [674d401e965281806f602d100000030010000003032e0200061a8000186a1fc6383b4345a2c0]
    AVC PPS: [68e9083520]
    Codecs String: avc1.4D401E

**Comment by mr3ayesh** [comment]
downloaded but without video and audio
