### ISSUE TITLE
Udemy Error:No Video formats found

### ISSUE THREAD

**Issue by tarunkumard2018** [rg3/youtube-dl#16334]
Using the latest youtube-dl using pip command ,i gave below command

youtube-dl -u uid -p mypassword --all-formats  https://www.udemy.com/aspnet-web-api-v/learn/v4

But console displayed below error for udemy course

[udemy:course] Downloading login popup
[udemy:course] Logging in
[udemy:course] aspnet-web-api-v: Downloading webpage
[udemy:course] 1630476: Downloading course curriculum
[download] Downloading playlist: ASP.NET Web API from Basic to Advanced
[udemy:course] playlist ASP.NET Web API from Basic to Advanced: Collected 18 video ids (downloading 18 of them)
[download] Downloading video 1 of 18
[udemy] Downloading login popup
[udemy] 9924520: Downloading webpage
[udemy] 9924520: Downloading lecture JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by tarunkumard2018** [comment]
Could you add original issue resolution,i just see closeure of issue as duplicate,also i checked other issues of udemy wherein you provided account-needed,so many issue pointing same description cant be wrong ?

**Comment by SalehAlolayan** [comment]
alot of people having this issue and no one fix it heeeeeelp
