### ISSUE TITLE
Wrong "Codec ID:" for VTT in mkv file

### ISSUE THREAD

**Issue by ibrshv** [rg3/youtube-dl#16336]
youtube-dl writes the unsupported "Codec ID: D_WEBVTT/SUBTITLES" in mkv so mkvextract [can't extract subtitles](https://gitlab.com/mbunkus/mkvtoolnix/issues/2289). Correct is "[S_TEXT/WEBVTT](https://matroska.org/technical/specs/codecid/index.html)". Seems it's a problem with [ffmpeg](https://trac.ffmpeg.org/ticket/5641). If so maybe exists solutions to tackle this issue in a different way? Or simply, how can I get this data from mkv?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
