### ISSUE TITLE
Skipping DASH manifest: ExtractorError with version 2018.05.01 

### ISSUE THREAD

**Issue by funglee2k** [rg3/youtube-dl#16345]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

**WARNING: [youtube] 78ok_I-8wU0: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)**

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

$ youtube-dl -v https://www.youtube.com/watch?v=78ok_I-8wU0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=78ok_I-8wU0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.01
[debug] Python version 2.7.12 (CPython) - Linux-4.14.26-041426-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.14-0ubuntu0.16.04.1, avprobe 2.8.14-0ubuntu0.16.04.1, ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 78ok_I-8wU0: Downloading webpage
[youtube] 78ok_I-8wU0: Downloading video info webpage
[youtube] 78ok_I-8wU0: Extracting video information
[youtube] 78ok_I-8wU0: Downloading m3u8 information
WARNING: [youtube] 78ok_I-8wU0: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://manifest.googlevideo.com/api/manifest/hls_playlist/id/78ok_I-8wU0.0/itag/95/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D136/hls_chunk_host/r3---sn-ab5l6ndy.googlevideo.com/ei/YoDoWqGqNqiOhwa3nZW4BQ/playlist_type/DVR/gcr/us/mm/32/mn/sn-ab5l6ndy/ms/lv/mv/u/pl/16/dover/10/keepalive/yes/fexp/23724337/manifest_duration/30/playlist_duration/30/mt/1525186087/disable_polymer/true/ip/132.197.246.66/ipbits/0/expire/1525208259/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,ei,playlist_type,gcr,mm,mn,ms,mv,pl/signature/5A6A35BA03C85168A02A1F66C237BBA22948FC8D.169A44ED8D803C783AA5A1CEF31426333D849A03/key/dg_yt0/playlist/index.m3u8'
[download] Destination: 🔴 Relaxing Sleep Music 24_7 - Meditation Music, Deep Sleeping Music, Peaceful Sleep-78ok_I-8wU0.mp4
[debug] avconv command line: avconv -y -loglevel verbose -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0 (Chrome)
' -i 'https://manifest.googlevideo.com/api/manifest/hls_playlist/id/78ok_I-8wU0.0/itag/95/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D136/hls_chunk_host/r3---sn-ab5l6ndy.googlevideo.com/ei/YoDoWqGqNqiOhwa3nZW4BQ/playlist_type/DVR/gcr/us/mm/32/mn/sn-ab5l6ndy/ms/lv/mv/u/pl/16/dover/10/keepalive/yes/fexp/23724337/manifest_duration/30/playlist_duration/30/mt/1525186087/disable_polymer/true/ip/132.197.246.66/ipbits/0/expire/1525208259/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,ei,playlist_type,gcr,mm,mn,ms,mv,pl/signature/5A6A35BA03C85168A02A1F66C237BBA22948FC8D.169A44ED8D803C783AA5A1CEF31426333D849A03/key/dg_yt0/playlist/index.m3u8' -c copy -f mp4 'file:🔴 Relaxing Sleep Music 24_7 - Meditation Music, Deep Sleeping Music, Peaceful Sleep-78ok_I-8wU0.mp4.part'
ffmpeg version 2.8.14-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[tls @ 0x10ecf60] The TLS connection was non-properly terminated.
[tls @ 0x10ecf60] The specified session has been invalidated for some reason.
[hls,applehttp @ 0x10ea620] HLS request for url 'https://r3---sn-ab5l6ndy.googlevideo.com/videoplayback/id/78ok_I-8wU0.0/itag/95/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D136/hls_chunk_host/r3---sn-ab5l6ndy.googlevideo.com/ei/YoDoWqGqNqiOhwa3nZW4BQ/playlist_type/DVR/gcr/us/mm/32/mn/sn-ab5l6ndy/ms/lv/mv/u/pl/16/keepalive/yes/fexp/23724337/manifest_duration/30/mt/1525186087/disable_polymer/true/ip/132.197.246.66/ipbits/0/expire/1525208259/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,ei,playlist_type,gcr,mm,mn,ms,mv,pl/signature/5A6A35BA03C85168A02A1F66C237BBA22948FC8D.169A44ED8D803C783AA5A1CEF31426333D849A03/key/dg_yt0/playlist/index.m3u8/sq/232844/goap/clen%3D81718%3Blmt%3D1525186661367269/govp/clen%3D891325%3Blmt%3D1525186661367269/dur/5.000/file/seg.ts', offset 0, playlist 0
[h264 @ 0x1506120] Current profile doesn't provide more RBSP data in PPS, skipping
Input #0, hls,applehttp, from 'https://manifest.googlevideo.com/api/manifest/hls_playlist/id/78ok_I-8wU0.0/itag/95/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D136/hls_chunk_host/r3---sn-ab5l6ndy.googlevideo.com/ei/YoDoWqGqNqiOhwa3nZW4BQ/playlist_type/DVR/gcr/us/mm/32/mn/sn-ab5l6ndy/ms/lv/mv/u/pl/16/dover/10/keepalive/yes/fexp/23724337/manifest_duration/30/playlist_duration/30/mt/1525186087/disable_polymer/true/ip/132.197.246.66/ipbits/0/expire/1525208259/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,ei,playlist_type,gcr,mm,mn,ms,mv,pl/signature/5A6A35BA03C85168A02A1F66C237BBA22948FC8D.169A44ED8D803C783AA5A1CEF31426333D849A03/key/dg_yt0/playlist/index.m3u8':
  Duration: N/A, start: 18862.318067, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s
    Stream #0:1: Video: h264 (Main), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 60 tbc
[mp4 @ 0x1a85ce0] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x1a85ce0] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to 'file:🔴 Relaxing Sleep Music 24_7 - Meditation Music, Deep Sleeping Music, Peaceful Sleep-78ok_I-8wU0.mp4.part':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264, 1 reference frame ([33][0][0][0] / 0x0021), yuv420p, 1280x720 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 127 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x1a85ce0] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
av_interleaved_write_frame(): Operation not permitted
No more output streams to write to, finishing.
[mp4 @ 0x1a85ce0] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
frame=    1 fps=0.0 q=-1.0 Lsize=      71kB time=00:00:00.06 bitrate=9052.6kbits/s    
video:70kB audio:1kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Input file #0 (https://manifest.googlevideo.com/api/manifest/hls_playlist/id/78ok_I-8wU0.0/itag/95/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D136/hls_chunk_host/r3---sn-ab5l6ndy.googlevideo.com/ei/YoDoWqGqNqiOhwa3nZW4BQ/playlist_type/DVR/gcr/us/mm/32/mn/sn-ab5l6ndy/ms/lv/mv/u/pl/16/dover/10/keepalive/yes/fexp/23724337/manifest_duration/30/playlist_duration/30/mt/1525186087/disable_polymer/true/ip/132.197.246.66/ipbits/0/expire/1525208259/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,ei,playlist_type,gcr,mm,mn,ms,mv,pl/signature/5A6A35BA03C85168A02A1F66C237BBA22948FC8D.169A44ED8D803C783AA5A1CEF31426333D849A03/key/dg_yt0/playlist/index.m3u8):
  Input stream #0:0 (audio): 3 packets read (1128 bytes); 
  Input stream #0:1 (video): 1 packets read (71608 bytes); 
  Total: 4 packets (72736 bytes) demuxed
Output file #0 (file:🔴 Relaxing Sleep Music 24_7 - Meditation Music, Deep Sleeping Music, Peaceful Sleep-78ok_I-8wU0.mp4.part):
  Output stream #0:0 (video): 1 packets muxed (71608 bytes); 
  Output stream #0:1 (audio): 3 packets muxed (1128 bytes); 
  Total: 4 packets (72736 bytes) muxed
Conversion failed!

ERROR: ffmpeg exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 471, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 461, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1993, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 800, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 854, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1627, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1900, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1839, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 365, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/external.py", line 64, in real_download
    self.get_basename(), retval))
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 166, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 617, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 579, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

<end of log>
```

**Comment by dstftw** [comment]
Outdated ffmpeg.

**Comment by funglee2k** [comment]
Hey, 
how to fix the "outdated ffmpeg" problem ? 

Thanks.

**Comment by dstftw** [comment]
By updating it obviously.
