### ISSUE TITLE
Release package

### ISSUE THREAD

**Issue by TerkiKerel** [rg3/youtube-dl#16349]
Hi,

Is there any possibility to create one or more packages for:

    snap
    nix
    appimage
    flatpack
    a standalone for linux

Thank you

**Comment by dstftw** [comment]
I don't see any point in that.

**Comment by TerkiKerel** [comment]
I want to use youtbe-dl on my work machine. But I don't want to install python or any other dependencies inside on OS.

containerizing is the future for every app. I will not explain the advantages of containerizing... How can you say there is no point of this? :/

**Comment by dstftw** [comment]
>containerizing is the future for every app

Disagree. Shipping all 3rd party dependencies for such a small project is an overkill and will raise traffic enormously that is already quite high. I also prefer to spend my time actually developing youtube-dl instead of maintaining N other fancy packages.

**Comment by NatoBoram** [comment]
@TerkiKerel There are many people who did just that, like https://github.com/rg3/youtube-dl/pull/13923, but changes don't get merged.
