### ISSUE TITLE
Hi and thank you for this project

### ISSUE THREAD

**Issue by CATASTR0PHE420** [rg3/youtube-dl#16342]
Hi, i'm new to youtube-dl and I only have 1 question, whenever I download a youtube file it has some sort of code of the video link, I.E. Alesana - apology, the file has "DaXHrA1TVlg" in it's name, is it possible to remove it via commands in youtube-dl? Thanks

**Comment by party98** [comment]
Hey, the code that you see is the id for that particular video according to youtube. To format the output filename you can use the `-o       --output` option with the associated format given (see here for more [details](https://github.com/rg3/youtube-dl#output-template) and [examples](https://github.com/rg3/youtube-dl#output-template-examples)). 

For your particular video and requirement the command will be:
`youtube-dl --output '%(title)s.%(ext)s' https://www.youtube.com/watch?v=DaXHrA1TVlg`

**Comment by party98** [comment]
The above mentioned command will do exactly this.
![image](https://user-images.githubusercontent.com/22412980/39536846-6ca179e0-4e55-11e8-8f5f-71f52f367708.png)

**Comment by CATASTR0PHE420** [comment]
@party98 thank you btw, I've forgot to say that.
