### ISSUE TITLE
youtube-dl is not getting proper auto-sub but getting not-auto-sub

### ISSUE THREAD

**Issue by Sofronio** [rg3/youtube-dl#16351]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl --skip-download --write-auto-sub --proxy http://127.0.0.1:9090 https://www.youtube.com/watch?v=Bv961ZmBL80 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--skip-download', '--write-auto-sub', '--proxy', 'http://127.0.0.1:9090', 'https://www.youtube.com/watch?v=Bv961ZmBL80', '-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018.05.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-89343-g83ecdc9a92, ffprobe N-89343-g83ecdc9a92
[debug] Proxy map: {'http': 'http://127.0.0.1:9090', 'https': 'http://127.0.0.1:9090'}
[youtube] Bv961ZmBL80: Downloading webpage
[youtube] Bv961ZmBL80: Downloading video info webpage
[youtube] Bv961ZmBL80: Extracting video information
[youtube] Bv961ZmBL80: Looking for automatic captions
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Duck Roast recipe by the BBQ Pit Boys-Bv961ZmBL80.en.vtt
...


youtube-dl --version
2018.05.01

<end of log>
```

---

### Description of your *issue*, suggested solution and other information

youtube-dl is not getting proper auto-sub but getting not-auto-sub
i use 
```
youtube-dl --skip-download --write-auto-sub --proxy http://127.0.0.1:9090 https://www.youtube.com/watch?v=Bv961ZmBL80
```
and downloaded Duck Roast recipe by the BBQ Pit Boys-Bv961ZmBL80.en.vtt
it looks like this.
```
WEBVTT
Kind: captions
Language: en

00:00:18.068 --> 00:00:26.777
 Roasted duck 

00:00:34.170 --> 00:00:37.460
 Welcome to BBQPitBoys.com 

00:00:37.460 --> 00:00:40.100
 What we are going to do today is roast ducks 

00:00:40.100 --> 00:00:42.320
 It's easy to do 
```

but it should looks like this
```
WEBVTT
Kind: captions
Language: en
Style:
::cue(c.colorCCCCCC) { color: rgb(204,204,204);
 }
::cue(c.colorE5E5E5) { color: rgb(229,229,229);
 }
##


00:15:33.660 --> 00:15:36.150 align:start position:0%
 
well<00:15:34.660><c> we're</c><00:15:34.809><c> drawing</c><c.colorE5E5E5><00:15:34.959><c> towards</c><00:15:35.589><c> the</c></c><c.colorCCCCCC><00:15:35.739><c> evening</c></c>

00:15:36.150 --> 00:15:36.160 align:start position:0%
well we're drawing<c.colorE5E5E5> towards the</c><c.colorCCCCCC> evening
 </c>

00:15:36.160 --> 00:15:38.549 align:start position:0%
well we're drawing<c.colorE5E5E5> towards the</c><c.colorCCCCCC> evening
now<00:15:36.279><c> as</c><00:15:36.399><c> you</c><00:15:36.519><c> can</c></c><c.colorE5E5E5><00:15:36.610><c> tell</c></c><c.colorCCCCCC><00:15:36.670><c> dark</c></c><c.colorE5E5E5><00:15:37.480><c> got</c><00:15:38.230><c> the</c><00:15:38.350><c> fire</c></c>

```

**Comment by Sofronio** [comment]
It seems that if the video have a human write subtitle, even not in English, youtube-dl will not get the auto-sub, but the auto-translated-sub, which doesn't contain any word-time info, but only the start time and end time.

**Comment by dstftw** [comment]
1. `--write-sub` for regular subtitles.
2. You're getting exactly what Youtube provides.

**Comment by Sofronio** [comment]
I mean I want to get the auto-sub, the regular subtitles is not what I want.
