### ISSUE TITLE
Bilibili downloading only first part of video

### ISSUE THREAD

**Issue by playfulpachyderm** [rg3/youtube-dl#16350]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v https://www.bilibili.com/video/av7850279/
[debug] System config: []
[debug] User config: ['--no-mtime', '-o', 'C:/Users/User/Music/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bilibili.com/video/av7850279/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.05.01
[debug] Python version 3.5.2 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[BiliBili] 7850279: Downloading webpage
[BiliBili] 7850279: Downloading video info page
[download] Downloading playlist: 2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel
[BiliBili] playlist 2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel: Collected 6 video ids (downloading 6 of them)
[download] Downloading video 1 of 6
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/06/40/12894006/12894006-1-80.flv?um_deadline=1525235407&platform=pc&rate=387600&oi=1279479545&um_sign=130005cc13f098c631b4633152d85e9b&gen=playurl&os=cos&trid=fc6b72cac3874213a1ace606123bade0'
[download] Destination: C:\Users\User\Music\2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel.flv
[download] 100% of 74.17MiB in 02:46
[download] Downloading video 2 of 6
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/06/40/12894006/12894006-2-80.flv?um_deadline=1525235407&platform=pc&rate=426700&oi=1279479545&um_sign=ffb8236f1ab1daa5fd75ab5450f2c887&gen=playurl&os=cos&trid=fc6b72cac3874213a1ace606123bade0'
[download] C:\Users\User\Music\2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel.flv has already been downloaded
[download] 100% of 74.17MiB
[download] Downloading video 3 of 6
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/06/40/12894006/12894006-3-80.flv?um_deadline=1525235407&platform=pc&rate=387600&oi=1279479545&um_sign=6b0be6c6e6d00cf2e36e96c79e73ac38&gen=playurl&os=cos&trid=fc6b72cac3874213a1ace606123bade0'
[download] C:\Users\User\Music\2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel.flv has already been downloaded
[download] 100% of 74.17MiB
[download] Downloading video 4 of 6
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/06/40/12894006/12894006-4-80.flv?um_deadline=1525235407&platform=pc&rate=418200&oi=1279479545&um_sign=6329ca23bbdd5c2bba8fd395fd06c246&gen=playurl&os=cos&trid=fc6b72cac3874213a1ace606123bade0'
[download] C:\Users\User\Music\2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel.flv has already been downloaded
[download] 100% of 74.17MiB
[download] Downloading video 5 of 6
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/06/40/12894006/12894006-5-80.flv?um_deadline=1525235407&platform=pc&rate=453900&oi=1279479545&um_sign=22281ff123608ad92fba13e69617a2ee&gen=playurl&os=cos&trid=fc6b72cac3874213a1ace606123bade0'
[download] C:\Users\User\Music\2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel.flv has already been downloaded
[download] 100% of 74.17MiB
[download] Downloading video 6 of 6
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/06/40/12894006/12894006-6-80.flv?um_deadline=1525235407&platform=pc&rate=498100&oi=1279479545&um_sign=ed9d9623d012d86eb9df9ac5942a09c3&gen=playurl&os=cos&trid=fc6b72cac3874213a1ace606123bade0'
[download] C:\Users\User\Music\2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel.flv has already been downloaded
[download] 100% of 74.17MiB
[download] Finished downloading playlist: 2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel
```

---

### Description of your *issue*, suggested solution and other information

Video is ~33 min long; only first ~5m40s is getting downloaded.  

Many other issues (including closed ones) seemed to have similar issues with Bilibili downloader, but this problem appears to be slightly different.  It recognizes that the video has multiple "parts", but it tries to re-download the same part 6 times instead of downloading all the parts.  Then it just says "has already been downloaded" for parts 2-6.

**Comment by dstftw** [comment]
You are using custom output template so now you are responsible for filename uniqueness. Don't touch it if you don't want to be responsible for it.
