### ISSUE TITLE
Facebook Live video is shaky

### ISSUE THREAD

**Issue by davidmcginn** [rg3/youtube-dl#16366]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--prefer-ffmpeg', '--postprocessor-args', '-movflags +faststart', '--no-progress', '-o', '/home/dave/daveapp-production/current/public/dave_s.mp4', '-f', '(mp4)[height<=?1080][fps<=?30][vcodec^=avc1]+(m4a)/(mp4)+(m4a)/(mp4)', 'https://www.facebook.com/lilush.yaghmuryan/videos/10212955557216875/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.01
[debug] Python version 3.5.2 (CPython) - Linux-4.15.12-x86_64-linode105-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.4-1, ffprobe 3.4-1
[debug] Proxy map: {}
[facebook] 10212955557216875: Downloading webpage
[debug] Invoking downloader on 'https://scontent-atl3-1.xx.fbcdn.net/v/t42.9040-29/10000000_368820446855091_6854417335084646400_n.mp4?_nc_cat=0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjRfaHE0X2ZyYWdfMl92aWRlb19mcm9tX2xpdmVfZHZyX3YyIn0=&oh=5f288bee8f175437e9668559b592b26c&oe=5AEB5232'
[download] Destination: /home/dave/daveapp-production/current/public/dave_s.f368820423521760v.mp4
[download] Download completed
[debug] Invoking downloader on 'https://scontent-atl3-1.xx.fbcdn.net/v/t42.1790-29/10000000_789261747931256_6662785051207401472_n.mp4?_nc_cat=0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjRfaHExX2ZyYWdfMl9hdWRpb19mcm9tX2xpdmVfZHZyX3YyIn0=&oh=e43a22589b8d0f68142a125f43f889bb&oe=5AEB67DE'
[download] Destination: /home/dave/daveapp-production/current/public/dave_s.mp4.f789261701264594ad
[download] Download completed
[ffmpeg] Merging formats into "/home/dave/daveapp-production/current/public/dave_s.mp4"
[debug] ffmpeg command line: ffmpeg -y -i file:/home/dave/daveapp-production/current/public/dave_s.f368820423521760v.mp4 -i file:/home/dave/daveapp-production/current/public/dave_s.mp4.f789261701264594ad -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart file:/home/dave/daveapp-production/current/public/dave_s.temp.mp4
Deleting original file /home/dave/daveapp-production/current/public/dave_s.f368820423521760v.mp4 (pass -k to keep)
Deleting original file /home/dave/daveapp-production/current/public/dave_s.mp4.f789261701264594ad (pass -k to keep)
<end of log>
```
---

### Facebook Live video is shaky

I'm having a problem with a specific Facebook Live video which when downloaded is shaky:

Video: [https://www.facebook.com/lilush.yaghmuryan/videos/10212955557216875/](https://www.facebook.com/lilush.yaghmuryan/videos/10212955557216875/)

This is the command I'm using to download it:

`~/.local/bin/youtube-dl --prefer-ffmpeg --postprocessor-args '-movflags +faststart' --no-progress -o './fb_live_shaky.mp4' -f '(mp4)[height<=?1080][fps<=?30][vcodec^=avc1]+(m4a)/(mp4)+(m4a)/(mp4)' 'https://www.facebook.com/lilush.yaghmuryan/videos/10212955557216875/'`

It would appear to be something to do with the format (`-f`) that I'm passing, because downloading with the following is okay:

`~/.local/bin/youtube-dl --prefer-ffmpeg --postprocessor-args '-movflags +faststart' --no-progress -o './fb_live_okay.mp4' -f '(mp4)[height<=?1080][fps<=?30]+(m4a)[abr<=?200]/(mp4)[height<=?1080][fps<=?30]/(mp4)' 'https://www.facebook.com/lilush.yaghmuryan/videos/10212955557216875/'`

I'm not very familiar with youtube-dl, so finding it hard to figure out which part of the format is the problem specifically. We use the first format (`(mp4)[height<=?1080][fps<=?30][vcodec^=avc1]+(m4a)/(mp4)+(m4a)/(mp4)`) for *all* Facebook videos and don't generally have problems, so I'm wondering if it's a bug in the current version or if we need to start passing a different format depending on the type of Facebook video.

FWIW I've tried a [different](https://www.facebook.com/TheCrookedMedia/videos/394506077685454/) Facebook Live video and did not have any problems.

Thanks

**Comment by dstftw** [comment]
Recect VLC and mpv both play file downloaded with your command line just fine without any visible issues.
Also when specifying output template never hardcode the extensions.
