### ISSUE TITLE
What Does `--retries infinite` actually do?

### ISSUE THREAD

**Issue by Queuecumber** [rg3/youtube-dl#16364]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.05.01
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

---

### Description of your *issue*, suggested solution and other information

I'm running with `youtube-dl --socket-timeout 1 --retries infinite` to work around some potential throttling issues I'm seeing, but I often get errors like 

```
ERROR: unable to download video data: <urlopen error _ssl.c:761: The handshake operation timed out>
```

or 

```
ERROR: Unable to download webpage: The read operation timed out (caused by timeout('The read operation timed out',))
```

I expect these kinds of errors with the `--socket-timeout` flag set to 1. But then the script exits without retrying even though I specified `--retries infinte` on the command line. 

So is this intended behavior and if so what does `--retries` actually control?

For reference I will leave the playlist URL I am working with here:

https://www.youtube.com/playlist\?list\=PLj_Goi54wf0cgpOuy60CdTQLi4Q-BrIGS

**Comment by dstftw** [comment]
`--retries` only work for downloading final media.

**Comment by irk3n-dev** [comment]
Try this: "youtube-dl --retries infinite --no-check-certificate --prefer-insecure [URL]"

**Comment by plhosk** [comment]
In a bash terminal you can retry forever with a loop:
```while true; do youtube-dl <command..> ; sleep 30; done```
