### ISSUE TITLE
How to convert macOS config file to be used on Windows

### ISSUE THREAD

**Issue by TarekSalama** [rg3/youtube-dl#16373]
I have been using youtube-dl on macOS with this configuration file with no problems however I tried replicating it to work Windows but I keep getting "ERROR: Batch file couldn't be read". I tried replacing the / with \ and putting all relevant Windows paths between double quotations but nothing worked.

Can someone tell me how I can convert this configuration file to work on Windows?
Thanks a lot

> --no-overwrites --no-cache-dir --ignore-errors --add-metadata --batch-file /Users/tareksalama/Desktop/Youtube-dl/batchvideos.txt -o /Users/tareksalama/Desktop/Youtube-dl/videos/%(uploader)s/%(title)s_%(uploader)s_%(id)s.%(ext)s
-f '(bestvideo[ext=mp4]/bestvideo)+(bestaudio[ext=m4a]/bestaudio)/best'

**Comment by dstftw** [comment]
Absolute paths on Windows must start with drive letter, e.g. `C:/`.
