### ISSUE TITLE
Add renaming capabilities

### ISSUE THREAD

**Issue by Aphexus** [rg3/youtube-dl#16376]
I downloaded a bunch of youtube videos and the file names are horrible and uninformative. It would be nice if youtube-dl could "rename" them using tags, date, format, and other meta-data. Possibly some type of regex replace string using certain meta info.

That is, I can re-download them again but  if the file exists and the rename parameter is used then it will just rename them rather than re-download them.

I'm thinking of something like -rn %title% - %date% - %id% - [%tags%]
or whatever.

The idea though is that it must check if the file already exists somehow(possibly check based on file size and then check name and see if it matches the default name or check meta contents of file, etc).

**Comment by dstftw** [comment]
Out of scope. You correct output templates during downloading.

**Comment by Aphexus** [comment]
What do you mean correct durning downloading? That is impossible. If you mean before then as I've said, I have already downloaded them. I have several hundred gigs of videos that I can't redownload... the file names must be fixed up. youtube-dl already has the ability to detect if a file exists, so it is not much more difficult to rename that file if a rename argument is supplied.

**Comment by dstftw** [comment]
Existing file does not mean it was downloaded by youtube-dl thus you can't use this as marker for renaming. Otherwise it's a right way to mess unrelated files. No ambiguous feature like that will be added. As already said: correct output templates must be use initially.
