### ISSUE TITLE
Re: youtube-dl #16056

### ISSUE THREAD

**Issue by IoanPaleru** [rg3/youtube-dl#16384]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [x] Other

youtube-dl #16056
https://github.com/rg3/youtube-dl/issues/16056

dstftw said:
"youtube-dl combines just fine. Fix your outdated avconv/ffmpeg."

dstftw:

Please don't lock and limit conversations to collaborators on posts until I've had a chance to respond to your comments.

I know that youtube-dl combines just fine, but I was talking about youtube-dl. I was trying to let you know about a different piece of software called youtube-dl-gui (youtube-dlg), which is already up-to-date, and I wasn't even asking you for technical support about it, I was just asking you if you knew of any good GUIs for youtube-dl. Thanks.

---
youtube-dl #16056:

IoanPaleru commented on Mar 31 •

youtube-dl is an excellent program because it downloads all available video formats reliably including dash formats, but is there a gui version? Thanks.
@dstftw
Collaborator
dstftw commented on Mar 31

No official GUI. But there are lots of 3rdparty ones.
@dstftw dstftw closed this on Mar 31
@IoanPaleru
IoanPaleru commented 8 days ago

Ok, thanks. I tried using youtube-dl-gui (youtube-dlg) but it doesn't seem to be able to combine dash formats into an .mp4 with audio and video, it only seems to be able to download either an .mp4 with a video stream only, or an .m4a with an audio stream only, but it used to be able to download videos properly. Do you know of any other good youtube-dl guis that work easily and reliably for download videos and audio files? youtube-dl is a great program, by the way, so keep up the great work! Thanks. Have a good day.
@dstftw
Collaborator
dstftw commented 8 days ago

youtube-dl combines just fine. Fix your outdated avconv/ffmpeg.
@dstftw dstftw locked and limited conversation to collaborators 8 days ago
---

**Comment by dstftw** [comment]
I don't expect to receive any responses as well as I don't care about different software, it's youtube-dl issue tracker not some other software. youtube-dl-gui is not affiliated with youtube-dl. Ask their support and don't clutter tracker with unrelated issues.
