### ISSUE TITLE
Use Python String Formatting Operations in the Download Archive option

### ISSUE THREAD

**Issue by Slider-Whistle** [rg3/youtube-dl#16386]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

- [x] Feature request (request for a new functionality)
---
```
[debug] System config: []
[debug] User config: ['--netrc', '-o', '%userprofile%/Youtube Archives/%(uploade
r)s/%(title)s - %(upload_date)s.%(ext)s', '--write-info-json', '--write-thumbnai
l', '--download-archive', 'C:\\Users\\N_Boy\\Youtube Archives\\%(uploader)s\\LIS
T', '--write-description']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/user/ClassicsOfGame']
[debug] Encodings: locale cp932, fs mbcs, out cp437, pref cp932
[debug] youtube-dl version 2018.05.01
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.0, ffprobe N-86848-g03a9e6f
[debug] Proxy map: {}
```
---
Forgive me if I show any lack of knowledge here, I'm not too experienced with this stuff.
I'd like for lists generated by download-archive to work by each user downloaded from, but as far as I can tell, it doesn't support any variable filenames/directories, or at least not the same variables covered by the "output" option.  At the moment, I'm trying to make the option use generic files called "LIST" in the directory of the current video's uploader, but this doesn't work since the option doesn't recognise %(uploader). In my particular case, I've recently changed my file naming scheme, so if I tried to download new videos from a given channel, I couldn't just use download-archive to avoid duplicates.

As a working solution, I could just set the download-archive option to work from the current directory and cd whenever I'm downloading from a new user, but this would be inconvenient in cases where you're not setting out to archive an entire channel.

People might disagree over the sort of behaviour I'm asking for, so if there's some other kind of solution, I'd be happy to use that.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/7719#issuecomment-160987090
