### ISSUE TITLE
Youtube-dl not writing to archive file when --skip-download is active

### ISSUE THREAD

**Issue by ThomasWarnasch** [rg3/youtube-dl#16382]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [https://www.youtube.com/watch?v=%%G --add-metadata --download-archive youtube-dl-archive-verify.txt --skip-download]
[debug] Encodings: N/A?
[debug] youtube-dl version 2018.05.01
[debug] Python version 3.6.5
[debug] exe versions: ffmpeg 20180410-d64183e, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```
---

My current problem is that when I run youtube-dl with --skip-download it no longer writes to the archive file.
I'm attempting to check if youtube video IDs from a text file still lead to a video, and if they still do, write the ID to another text file. My goal is to later with another script check which IDs are still active and which aren't (though this doesn't have to be covered in my problem).

My entire current script is 
`set "urle="
for /F "tokens=*" %%A in (youtube-dl-archive.txt) do ( 
for /f "tokens=2" %%G IN ("%%A") DO (
echo %%G
youtube-dl https://www.youtube.com/watch?v=%%G --add-metadata --download-archive youtube-dl-archive-verify.txt --skip-download
)
)`

**Comment by dstftw** [comment]
This is expected behavior.
