### ISSUE TITLE
Output Template Suggestion: Playlist Grouping

### ISSUE THREAD

**Issue by wertercatt** [rg3/youtube-dl#16397]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

YouTube playlists can be organized on a users' page using "Shelves."
[Example Shelf](https://www.youtube.com/user/ClassyManIAm/playlists?view=50&sort=dd&shelf_id=9)

However, there is currently no way to, for example, set a "shelf_title" variable in your output template, requiring end users to work around this lack of functionality by hard-coding the Shelf title in their output template like so:
`-o 'C:/Users/Blaze/Videos/%(playlist_uploader)s/DLC Mini-Series The Awe-Inspiring Stories of Fallout's Amazing DLCs/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s'`

**Comment by Hrxn** [comment]
Not sure if I understand this correctly..
So, a "shelf" is what exactly in this context? A playlist of other playlists?

**Comment by wertercatt** [comment]
Yes. It's a playlist of other playlists.

**Comment by wertercatt** [comment]
duplicate of what?
