### ISSUE TITLE
[Udemy] Unable to download JSON metadata: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by gydammin** [rg3/youtube-dl#16395]
- [ x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [ x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.01
[debug] Python version 2.7.15 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
...
<end of log>
```

Get 403 on free and paid lessons. Cannot provide account credentials but can be reproduced with any free lesson. 

```
youtube-dl --cookies ./udemy-cookies.txt -o '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s' https://www.udemy.com/javascript-essentials/learn/v4

[udemy:course] javascript-essentials: Downloading webpage
[udemy:course] 707962: Enrolling in the course
[udemy:course] 707962: Downloading course curriculum
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Same error as reported [here](https://github.com/rg3/youtube-dl/issues/16372) and [there end of page](https://gist.github.com/barbietunnie/8531d9c26cd1c0668e7278c7c4ba5853), something may have changed in Udemy (new protection?) as full course download was working perfectly until now. Note: I experimented same issues [user comments](https://gist.github.com/barbietunnie/8531d9c26cd1c0668e7278c7c4ba5853) before upgrade (error : "ERROR : No video formats found") and after upgrade to latest getting HTTP Error 403: Forbidden)

**Comment by enbima** [comment]
Same problem here, cannot download some courses anymore with 403 Forbidden Error (they are paid and credentials are given). This suddenly happens for courses where the coach doesn't allow the manual download of a lecture. Courses where the manual download of a video is supported still works fine with youtube-dl.

**Comment by gydammin** [comment]
+ 1 good point !

**Comment by yaronjobs88** [comment]
bump
