### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by satishdesh** [rg3/youtube-dl#16396]
Hello

My OS - Win 7.1 - 32 bit
youtube-dl version - 2018.05.01
python ver 3.6

I am trying to download some videos from paid Udemy course core-java-programming-the
-complete-course
But when i enter the course name i was not asked to enter the password and automatically video download process gets started with the immediate following error.

C:\Users\satish>youtube-dl -u satishdesh@outlook.com https://www.udemy.com/core-java-programming-the
-complete-course/learn/v4/overview
Type account password and press [Return]: 

> Here the process starts automatically with following error.

[udemy:course] Downloading login popup
[udemy:course] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using
 the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl wit
h the --verbose flag and include its complete output.

Please let me know the system fault and the steps to be followed to get rid of this error.

satish

**Comment by KharmaScribbles** [comment]
Try with this method?

https://github.com/rg3/youtube-dl#authentication-with-netrc-file

**Comment by sa7mon** [comment]
I'd recommend including the site's name [Udemy] in the issue name. Makes it easier for other users to find your issue if they're also experiencing it.

**Comment by satishdesh** [comment]
@sa7mon  Thanks. I have already written the site name in the post. 
@KharmaScribbles Thanks. Today i upgraded to the latest version 2018.05.09 on one PC and its working. Lets see it will work on another PC also.
