### ISSUE TITLE
Can't download from a tou.tv account. Site redesigned!

### ISSUE THREAD

**Issue by kobra111** [rg3/youtube-dl#16398]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: [u'--audio-quality', u'0', u'-o', u'%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'https://ici.tou.tv/unite-9/S05E01']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.01
[debug] Python version 2.7.14+ (CPython) - Linux-4.15.0-2-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: avconv 3.4.2-2, avprobe 3.4.2-2, ffmpeg 3.4.2-2, ffprobe 3.4.2-2, rtmpdump 2.4
[debug] Proxy map: {}
[tou.tv] Downloading homepage
ERROR: Unable to extract toutvlogin; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 439, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 397, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/toutv.py", line 52, in _real_initialize
    r'(?s)toutvlogin\s*=\s*({.+?});', webpage, 'toutvlogin'), None, js_to_json)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 820, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract toutvlogin; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://ici.tou.tv/unite-9/S05E01

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I doesn't have problem to download free content but it doesn't work when I want to download "extra" (premium) videos from an account, tou.tv have change their web site design recently. It worked less than a month with my account before the web site change. The tou.tv login script probably need a update for the new web site.

If you need a login to help you, I can give my account credential.

I hope that my English is not too bad!

Thanks for your help.
Erik.

**Comment by kobra111** [comment]
It's geo-restricted to Canada.

**Comment by kobra111** [comment]
@Altruo The geo-restriction just mean to developers outside of the Canada that want to help us need a Canadian IP thru a proxy or VPN to be able to work on the problem.

**Comment by m-p-3** [comment]
Also some of its content can be downloaded without an account (only Tou.TV Extra content needs a valid account).

Example: https://ici.tou.tv/infoman/S18E31

**Comment by kobra111** [comment]
Sorry to say that, I doesn't have account anymore. Generally I subscribe a month to download premium content that's interesting and after I unsubscribe to save money.

**Comment by m-p-3** [comment]
I can provide an account if needed, let me know how to proceed.

**Comment by Altruo** [comment]
That's the problem, it doesn't works for the premium contents, but only regular contents. Youtube-dl doesn't works anymore with the credentials (user & password (-u -p))  for that specific site. But it used to...

ERROR: Unable to extract toutvlogin; please report this issue on https://yt-dl.org/bug . 
Make sure you are using the latest version; type  youtube-dl -U  to update. 
Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by emilieviau** [comment]
Same problem here. Doesn't work for Extra contents even with appropriate credentials (user and password).

**Comment by juef17** [comment]
Unless it's just me, I am having this problem, but with content that doesn't require a subscription. See https://ici.tou.tv/terreur-404/S01B00

**Comment by whitenoise2** [comment]
Hi. I'm from Montreal, Canada, and I have a premium account for tou.tv. I've started looking into this - it does stem from the UI re-design; tou.tv has moved the client-code generation into obfuscated scripting, which makes the old code no longer work. There might be a way around that.

But, be also aware that even if the login is fixed, more and more content of tou.tv will fail to convert for playback as it is tainted with DRM that only web-browsers can decode, so downloading/converting for offline playback will no longer be a possibility for a portion of the tou.tv content.

**Comment by Altruo** [comment]
Great ! Thanks man that would be fantastic.

Merci

**Comment by mos8580** [comment]
I'm hit by this bug as well. If this PR fixes the problem, is it possible to merge it? Thanks!

**Comment by alexhuot1** [comment]
If you need this fix quickly, i think you can checkout my branch as @tabarnakos did in the PR.

**Comment by Altruo** [comment]
Hi Alex it seems that you found a way to fix the problem, but for now it still doesn't work for me, do you think that they will add your fix to the next upload ? Others seem to have find their ways with your PR, unfortunately I'm very bad with coding it's basicaly chinese to me... If you think that they won't had your fix to the next upload would you be kind enough to give an exemple of what should be written in youtube-dl in order to make it work ?  al.71@live.ca   Merci pour ton bon travail c'est super apprécié !

**Comment by tabarnakos** [comment]
Here's an example of how I use Alex's fix. I don't live in Canada anymore so I need the geo-bypass, which you can omit:
./youtube-dl/youtube-dl --geo-bypass-country CA -u foo@bar.com -p K0mplexPa$$w0rd -f "(mp4,webm)bestvideo[height<=2160]+bestaudio/best[height<=2160]" https://ici.tou.tv/deuxieme-chance/S03E01?lectureauto=1

It works _most_ of the time, for _most_ of the content.

However,l some content fails to download for unknown reason, such as the entire Season 28 of Découvertes:
https://ici.tou.tv/decouverte/S28E02?lectureauto=1

fails with the following error: 

```
[radiocanada] 117214: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug .
```

but Season 29 works without issues.

Also, some videos fails due to DRM, such as Unité 9 :
https://ici.tou.tv/unite-9/S07E13?lectureauto=1

fails with the following error: 
```
[tou.tv] Extracting Claims
[tou.tv] unite-9/S07E13: Downloading JSON metadata
WARNING: [tou.tv] unite-9/S07E13: This video is probably DRM protected.
[radiocanada] 144354: Downloading metadata XML
ERROR: This video is DRM protected.
```

**Comment by Altruo** [comment]
Thank you tabarnakos@ for your answer, but I don't see what's different in the code you use nor where is Alex's fix.  Is it this ? :

> -f "(mp4,webm)bestvideo[height<=2160]+bestaudio/best[height<=2160]

Personally I still get a " Unable to extract toutvlogin" with the -u -p option.  The video you refer to is not Extra contents, so you can acces it without credential (user/password).  My main problem is with Extra contents (not DRM) where I get a " unable to extract toutvlogin"

Here's an exemple of the code I use usually to get my contents (under windows)

youtube-dl -u MY EMAIL ADRESSE -p PASSWORD " https://ici.tou.tv/grizzy-et-les-lemmings/S01E31?lectureauto=1"   But that doesn't work anymore on tou.tv

I get the same thing with : 
youtube-dl -u MY EMAIL ADRESSE -p PASSWORD -f "(mp4,webm)bestvideo[height<=2160]+bestaudio/best[height<=2160]" https://ici.tou.tv/grizzy-et-les-lemmings/S01E31?lectureauto=1"

Maybe I misunderstood the code you provided, because somehow you download with your credential on the site, while I can't.

Any help is welcome

**Comment by Altruo** [comment]
It's a good guess lol I don't even no how to use a branch and where to but it. That the thing, I wanted to know what I have to put within the program. 

If there is any good Samaritan to explain   al.71@live.ca

**Comment by alexhuot1** [comment]
@tabarnakos I got a another PR (https://github.com/rg3/youtube-dl/pull/18609) that fixes the DRM check. The fixe is on my master branch on my fork. I pushed a branch containing both fixes (DRM + account) call all_fixes give it a try!

@Altruo I wrote you a comment on your commit on your fork. I can help you there so we don't hijack this thread.

Hope it helps you both!

**Comment by tabarnakos** [comment]
Okay I haven't found a better place to put this. For Decouvertes Season 28 (and a couple other Decouvertes episodes), I found a fix to be able to download the m3u8 playlist, but it is pretty dirty, and as far as I can understand, it fixes a bug on radio-canada's server not giving the right URL.

Here's is the git diff, the modification is in the radio-canada extractor.

```
@@ -111,6 +111,7 @@ class RadioCanadaIE(InfoExtractor):
                 })
             v_data = self._download_xml(validation_url, video_id, note='Downloading %s XML' % device_type, query=query,
 fatal=False)
             v_url = xpath_text(v_data, 'url')
+            v_url = v_url.replace(',256,400,', ',',1)
             if not v_url:
                 continue
             if v_url == 'null':
```

It seems as if they have somehow discontinued the 256 and 400kbits streams, but failed to update something in their servers, resulting in error 404 when requesting the m3u8 information. Deleting that part of the string fixes the issue... But I have no idea if it would break other video downloads on radio-canada's website.

@alexhuot1 Are you interested in looking into it? I don't have enough python of web programming experience to know what I am doing, nor what is the right way to fix it.

**Comment by alexhuot1** [comment]
@tabarnakos Yes i'll take a look for sure. I had a very similar problem with the latest District 31 episode. Thanks for the fix!

**Comment by alexhuot1** [comment]
@tabarnakos I send a PR for you problem (and also mine ;) ). You can checkout the master branch on my fork to get all my fixes. (account, DRM and bitrates)

**Comment by aulismedia** [comment]
@tabarnakos / @alexhuot1 Did your fixes make it to the public release yet? I have 2019.01.30.1 and even on non-georestricted emissions I receive "ERROR: radiocanada said: Exception has been thrown by the target of an invocation."

**Comment by alexhuot1** [comment]
We are still waiting for the PR to be accepted. For now you can checkout master from my fork and test is the fix works.

**Comment by Meremptah** [comment]
Hello. Do anyone have codes to access to a Tou TV Extra account ?

**Comment by m-p-3** [comment]
@Meremptah unless you work on the project and it's for troubleshooting an issue, you have to pay for that.
