### ISSUE TITLE
UPDATE->  IGNORE IT, its working fine now <-https://app.pluralsight.com WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by yaronjobs88** [rg3/youtube-dl#16394]
## Please follow the guide below
updated: "youtube-dl is up-to-date (2018.05.09)"

this ise the issue:
youtube-dl.exe --cookies "cookies.txt"  -o "C:\%(playlist_index)s - %(title)s.%(ext)s" --min-sleep-interval 31 --max-sleep-interval 39 "https://app.pluralsight.com/library/courses/exam-review-linux-plus-lx0-104-lpic-1-102-400/table-of-contents"
 --playlist-start 001 --verbose

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl) ** For Pluralsight Extractor ONLY
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'C:\Users\Administrator\Downloads\youtube-dl2222\cookies.txt', '-o', 'C:\exam-review-linux-plus-lx0-104
-lpic-1-102-400-2015\%(playlist_index)s - %(title)s.%(ext)s', '--min-sleep-interval', '31', '--max-sleep-interval', '39', 'https://app.pluralsight.co
m/library/courses/exam-review-linux-plus-lx0-104-lpic-1-102-400/table-of-contents', '--playlist-start', '001', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.04.16
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {'no': '192.168.99.100'}
[pluralsight:course] exam-review-linux-plus-lx0-104-lpic-1-102-400: Downloading course JSON
[download] Downloading playlist: Exam Review for CompTIA Linux+ (LX0-104) and LPI LPIC-1 (102-400)
[pluralsight:course] playlist Exam Review for CompTIA Linux+ (LX0-104) and LPI LPIC-1 (102-400): Collected 127 video ids (downloading 127 of them)
[download] Downloading video 1 of 127
[pluralsight] exam-review-linux-plus-lx0-104-lpic-1-102-400-m1-0: Downloading course JSON
[pluralsight] exam-review-linux-plus-lx0-104-lpic-1-102-400-m1-0: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] exam-review-linux-plus-lx0-104-lpic-1-102-400-m1-0: Waiting for 4 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to
update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9r95p1_v\build\youtube_dl\YoutubeDL.py", line 789, in extract_info
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9r95p1_v\build\youtube_dl\extractor\common.py", line 440, in extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9r95p1_v\build\youtube_dl\extractor\pluralsight.py", line 326, in _real_extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9r95p1_v\build\youtube_dl\extractor\common.py", line 1083, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest versio
n; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://app.pluralsight.com/player?course=exam-review-linux-plus-lx0-104-lpic-1-102-400&author=andrew-mallett&name=exam-review-linux-plus-lx0-104-lpic-1-102-400-m21&clip=7&mode=live

- Single video:https://app.pluralsight.com/player?course=exam-review-linux-plus-lx0-104-lpic-1-102-400&author=andrew-mallett&name=exam-review-linux-plus-lx0-104-lpic-1-102-400-m3&clip=3&mode=live
- Playlist: https://app.pluralsight.com/library/courses/exam-review-linux-plus-lx0-104-lpic-1-102-400/table-of-contents

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information
update PluralSight extractor?
Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by yaronjobs88** [comment]
i am using valid account cookies!
i know it because i am able to watch from same account/cookies via Chrome for same Course.

**Comment by yaronjobs88** [comment]
UPDATE: same bug/issue with version **18.5.2018**
youtube-dl.exe -U
Updating to version **2018.05.18** ...
Waiting for file handle to be closed ...
Updated youtube-dl to version **2018.05.18.**

[pluralsight:course] aws-networking-deep-dive-vpc: Downloading course JSON
[download] Downloading playlist: AWS Networking Deep Dive: Virtual Private Cloud (VPC)
[pluralsight:course] playlist AWS Networking Deep Dive: Virtual Private Cloud (VPC): Collected 38 video ids (downloading 38 of
[download] Downloading video 1 of 38
[pluralsight] a27221fe-f16a-47a2-8b5e-5b6d32d48016-0: Downloading course JSON
[pluralsight] a27221fe-f16a-47a2-8b5e-5b6d32d48016-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] a27221fe-f16a-47a2-8b5e-5b6d32d48016-0: Waiting for 5 seconds to avoid throttling
[download] Sleeping 38.52 seconds...
[download] Destination: C:\aws-networking-deep-dive-vpc-2017\01 - Course Overview.mp4
[download] 100% of 4.12MiB in 00:02
[download] Downloading video 2 of 38
[pluralsight] 9a15a991-2216-4f7b-bffb-83995724b89e-0: Downloading course JSON
[pluralsight] 9a15a991-2216-4f7b-bffb-83995724b89e-0: Downloading mp4-high-widescreen viewclip JSON
**WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden**
[pluralsight] 9a15a991-2216-4f7b-bffb-83995724b89e-0: Waiting for 2 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version;
 update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yaronjobs88** [comment]
ssad

**Comment by yaronjobs88** [comment]
Hi

i checked it with FRESH NEW user  and its working fine!!
i am sorry for not checking it with fresh new user before!!
its working 100% fine  :)

thank you for youtube-dl

**Comment by EngrKhizarIqbal** [comment]
I'm also getting the same error.
