### ISSUE TITLE
[Tech support] How to get filename after a download has completed (Python)

### ISSUE THREAD

**Issue by devxpy** [rg3/youtube-dl#16401]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Hello,
I want to download `audio` files using Python (using `--extract-audio`) and then get the final filename after youtube-dl / ffmpeg are done with it.

##### Example
```
subprocess.run([
                'youtube-dl',
                '--extract-audio', '--restrict-filenames',
                '-o', DL_DIR.joinpath(f'{song.spotify_id}.%(ext)s'),
                song.youtube_id
            ])
```

output-
```
[youtube] mMoVvCEYMKM: Downloading webpage
[youtube] mMoVvCEYMKM: Downloading video info webpage
[youtube] mMoVvCEYMKM: Extracting video information
[download] /home/dev/Projekt/encadio/downloads/English/4gLuKrWf0Ub3nwrRB0yJk7.m4a has already been downloaded
[download] 100% of 3.27MiB
[ffmpeg] Correcting container in "/home/dev/Projekt/encadio/downloads/English/4gLuKrWf0Ub3nwrRB0yJk7.m4a"
[ffmpeg] Post-process file /home/dev/Projekt/encadio/downloads/English/4gLuKrWf0Ub3nwrRB0yJk7.m4a exists, skipping
```

Now how do I know what the final filename (or just the file extension) was, after the download finished?

I could also do this, as suggested by readme

```
with youtube_dl.YoutubeDL(ydl_opts) as ydl:                
    ydl.download(['https://www.youtube.com/watch?v=BaW_jenozKc'])
```

But I couldn't find the final filename in `ydl`s attributes.

###### I could have my application work by just searching using `song.spotify_id`, but that seems a little janky?

**Comment by devxpy** [comment]
Sorry, my bad. Didn't see the full example.
It's available like this

```
    def my_hook(d):
        print(d['filename'])

    ydl_opts = {
        'format': 'bestaudio',
        'progress_hooks': [my_hook],
    }
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download(['https://www.youtube.com/watch?v=BaW_jenozKc'])
```

**Comment by Moriand** [comment]
please a complete example, I need to understand it completely

**Comment by devxpy** [comment]
Just import youtube_dl I guess..

**Comment by Moriand** [comment]
Well, well, you go there, rather I wanted to know what more options it offers, for example:
I want to download the subtitle
as after download, I convert to mp3 or other audio formats

**Comment by devxpy** [comment]
Never tried doing subtitles, will try..

If you convert to other format, `d['filename']` returns the filename for converted format
