### ISSUE TITLE
Unable to extract duration error

### ISSUE THREAD

**Issue by yesilcimenahmet** [rg3/youtube-dl#16407]
Hi, 
I am using Windows YouTube-dl with version information below.

> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-U', '--verbose']
> [debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
> [debug] youtube-dl version 2018.05.09
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
> [debug] exe versions: ffmpeg 3.2.2
> [debug] Proxy map: {}
> youtube-dl is up-to-date (2018.05.09)

When I want to receive a video via izlesene.com as JSON, it shows the following message.

`dl --dump-json "https://www.izlesene.com/video/adele-rolling-in-the-deep/3760761#isrch_click_test3-popular_3_adele%20rolling%20in%20the%20deep:3760761"`

WARNING: unable to extract duration; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yonaikerlol** [comment]
The video plays well in your Web Browser?, in mine it says that it is not available for my Country.
First try it on your Web Browser to see if it can be played.

Oh, they also updated Python to version 3.6.5, download it, maybe that's the problem.

**Comment by yesilcimenahmet** [comment]
Yes, video plays well. You can try other videos. The problem still continues.

**Comment by mrfade** [comment]
I created a pr about this problem (#16271) but it haven't reviewed yet
