### ISSUE TITLE
It asks me to install ffprobe while I have already installed it

### ISSUE THREAD

**Issue by Steven-AA** [rg3/youtube-dl#16404]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: ['-x', '--no-mtime', '--proxy', '127.0.0.1:10542', '-o', 'D:/download/youtube/%(playlist_index)s-%(title)s.%(ext)s', '--write-auto-sub', '--cache-dir', 'D:/download/youtube/cache/']
[debug] Custom config: []
[debug] Command-line args: ['--playlist-items', '1', '-f', 'best', '-v', 'https://www.youtube.com/playlist?list=**']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018.05.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17127
[debug] exe versions: ffmpeg N-90996-g29eb1c51d7
[debug] Proxy map: {'http': '127.0.0.1:10542', 'https': '127.0.0.1:10542'}
[youtube:playlist] **: Downloading webpage
[download] Downloading playlist: **
[youtube:playlist] playlist **: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] OQQ-W_63UgQ: Downloading webpage
[youtube] OQQ-W_63UgQ: Downloading video info webpage
[youtube] OQQ-W_63UgQ: Extracting video information
[youtube] OQQ-W_63UgQ: Looking for automatic captions
[info] Writing video subtitles to: D:\download\youtube\**
[debug] Invoking downloader on 'https://r3---sn-i3beln7r.googlevideo.com/videoplayback?ratebypass=yes&fvip=3&signature=83D814A92FFEE1985E926A67E33ADD8B9D418782.3DAEA4EA2F2BBBFE92C912208E42DE694D6BBF2F&lmt=1510214927746339&itag=22&requiressl=yes&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&expire=1525814211&mt=1525792431&initcwndbps=633750&ipbits=0&mm=31%2C26&mn=sn-i3beln7r%2Csn-npoeen7d&c=WEB&id=o-AOKy0sDQwKbIoyum-eU3C1fpPV0lz6dXnaL8o56sGVtk&key=yt6&source=youtube&mv=m&dur=4300.892&fexp=23724337&ms=au%2Conr&ip=164.52.12.83&pl=24&mime=video%2Fmp4&ei=Y7_xWo-kCtjQqAGuvKeoDg'
[download] D:\download\youtube\**
has already been downloaded
[download] 100% of **MiB
ERROR: ffprobe or avprobe not found. Please install one.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\YoutubeDL.py", line 2039, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\postprocessor\ffmpeg.py", line 241, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\postprocessor\ffmpeg.py", line 156, in get_audio_codec
youtube_dl.utils.PostProcessingError: ffprobe or avprobe not found. Please install one.
...
<end of log>
```
And I have already installed the ffprobe
```
λ  ffprobe
ffprobe version N-90996-g29eb1c51d7 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enab
...
```

---

**Comment by dstftw** [comment]
Most likely you did not install it properly. It must be in `%PATH%` or near `youtube-dl.exe`.

**Comment by Hrxn** [comment]
Looks like you are using ConEmu, or Cmder or something.
They can have additional directories for binaries, does not mean that this is the system's `PATH`

**Comment by Steven-AA** [comment]
Powershell:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> ffprobe
ffprobe version N-90996-g29eb1c51d7 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libblu
...
```
cmd:
```
Microsoft Windows [Version 10.0.17127.1]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>ffprobe
ffprobe version N-90996-g29eb1c51d7 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libblur
...
```

**Comment by Hrxn** [comment]
Are you running youtube-dl from `..\system32\` as well?

**Comment by Steven-AA** [comment]
no，I can run YouTube-dl anywhere and I can run ffprobe anywhere. They are all in the %path%

On Wed, May 9, 2018, 00:29 HRXN <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you running youtube-dl from ..\system32\ as well?

**Comment by Hrxn** [comment]
Perhaps caused by some config option, i.e.:
`[debug] User config: ['-x', '--no-mtime', '--proxy', '127.0.0.1:10542', '-o', 'D:/download/youtube/%(playlist_index)s-%(title)s.%(ext)s', '--write-auto-sub', '--cache-dir', 'D:/download/youtube/cache/']`

Not sure..

What happens if you run it without `--cache-dir`?
