### ISSUE TITLE
please add Saruch

### ISSUE THREAD

**Issue by treakiandroid** [rg3/youtube-dl#16411]
exmple url: https://saruch.co/?module=video&id=36 . Its easyly downloadable using shift+right click in mozilla so it shouldnt be a problem

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by treakiandroid** [comment]
its some newborn video hoster like any else to, sry i picked just a random video, this one is sure copyleft:

https://saruch.co/?module=video&id=26

**Comment by treakiandroid** [comment]
how to reopen the issue?
