### ISSUE TITLE
youtube-dl does not work on wifi?

### ISSUE THREAD

**Issue by fameless0x01** [rg3/youtube-dl#16414]
This is on a rooted Android 5.1 device with Termux, python 3.6.5 and youtube-dl installed via pip.

When I use youtube-dl with mobile data, it works pretty good. But instead if I use wifi, then it gets stuck after this step `Downloading webpage`, it takes about 5 minutes to print the next message, then again a few more minutes to the next message and so on.
  
The url I am trying is a vimeo playlist.
Apart from that I have also tried coursera-dl and edx-dl which IIRC uses youtube-dl internally.

The last message I received on `-v` before it became slow again was -
```
Checking Original video URL
```

Also this happens only on the video urls.
Pdf downloads work fine.

Is there anything that I can do to debug it more?
Or any general reason that could cause the issue?

I am able to browse internet on the wifi just fine.

**Comment by dstftw** [comment]
Most likely unstable connection is the reason.

**Comment by fameless0x01** [comment]
No that is not the problem, I can very well download other stuff using the browser or ADM.
It gets stuck at the exact same place always.

**Comment by fameless0x01** [comment]
```
ERROR: Unable to download webpage: <urlopen error [Errno 113] No route to host> (caused by URLError(OSError(113, 'No route to host'),))
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 519, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2203, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/data/data/com.termux/files/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/data/data/com.termux/files/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/data/data/com.termux/files/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/youtube_dl/utils.py", line 1101, in https_open
    req, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
```
After letting the program run for about 10-15 minutes I got this error.

**Comment by fameless0x01** [comment]
But I got this error only once, i.e. right now. Whereas I am trying to use this on wifi since 2-3 days.

**Comment by fameless0x01** [comment]
It starts to work if i do `--socket-timeout 5`
:/

**Comment by fameless0x01** [comment]
Definitely not a problem with the network as I am able to access the same url from the browser and download the video using IDM

**Comment by fameless0x01** [comment]
It starts working on vpn. Unfortunately that won't work with my work wifi.

**Comment by dstftw** [comment]
Once again: it's clearly an intermittent network issue as described in previous comment.
