### ISSUE TITLE
Question on DASH video format 

### ISSUE THREAD

**Issue by funglee2k** [rg3/youtube-dl#16419]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

Hey, 
I noticed an interesting issue. For some reason, there is no DASH video listed in the "-F" output, although there are several DASH audio listed there.  

However, I think format 136 should be DASH video. is that correct ?   

 youtube-dl -vv -F "https://www.youtube.com/watch?v=ZnQGzfrEpsc" 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vv', u'-F', u'https://www.youtube.com/watch?v=ZnQGzfrEpsc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.09
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-64-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ZnQGzfrEpsc: Downloading webpage
[youtube] ZnQGzfrEpsc: Downloading video info webpage
[youtube] ZnQGzfrEpsc: Extracting video information
[info] Available formats for ZnQGzfrEpsc:
format code  extension  resolution note
249          webm       audio only DASH audio   55k , opus @ 50k, 1.58MiB
250          webm       audio only DASH audio   70k , opus @ 70k, 2.04MiB
171          webm       audio only DASH audio  122k , vorbis@128k, 3.41MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 3.93MiB
251          webm       audio only DASH audio  135k , opus @160k, 3.88MiB
278          webm       256x144    144p   97k , webm container, vp9, 30fps, video only, 2.87MiB
160          mp4        256x144    144p   99k , avc1.4d400c, 30fps, video only, 2.08MiB
133          mp4        426x240    240p  161k , avc1.4d4015, 30fps, video only, 3.63MiB
242          webm       426x240    240p  224k , vp9, 30fps, video only, 5.09MiB
134          mp4        640x360    360p  296k , avc1.4d401e, 30fps, video only, 7.16MiB
243          webm       640x360    360p  404k , vp9, 30fps, video only, 9.71MiB
135          mp4        854x480    480p  686k , avc1.4d401f, 30fps, video only, 15.27MiB
244          webm       854x480    480p  759k , vp9, 30fps, video only, 17.84MiB
136          mp4        1280x720   720p 1201k , avc1.4d401f, 30fps, video only, 26.92MiB
247          webm       1280x720   720p 1495k , vp9, 30fps, video only, 29.78MiB
137          mp4        1920x1080  1080p 1835k , avc1.640028, 30fps, video only, 44.05MiB
248          webm       1920x1080  1080p 2658k , vp9, 30fps, video only, 59.94MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)

youtube-dl --version 
2018.05.09

**Comment by dstftw** [comment]
DASH is nominal here since Youtube does not serve manifests any longer.

**Comment by funglee2k** [comment]
Thanks Dstftw,

Do you happen to know when youtube stops serving manifests ?
