### ISSUE TITLE
[mixcloud] download stops after 5-10%, restarting downloads another 5-10%

### ISSUE THREAD

**Issue by kicks66** [rg3/youtube-dl#16424]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v https://www.mixcloud.com/essentialmixcollection/20180310-essential-mix-peggy-gou/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.mixcloud.com/essentialmixcollection/20180310-essential-mix-peggy-gou/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.09
[debug] Python version 2.7.15 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[mixcloud] essentialmixcollection-20180310-essential-mix-peggy-gou: Downloading webpage
[mixcloud] essentialmixcollection-20180310-essential-mix-peggy-gou: Downloading JS
[mixcloud] essentialmixcollection-20180310-essential-mix-peggy-gou: Downloading m3u8 information
[mixcloud] essentialmixcollection-20180310-essential-mix-peggy-gou: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://stream1.mixcloud.com/secure/c/m4a/64/f/0/f/2/21a7-3d30-49db-9b88-e641f5165163.m4a?sig=YtNdXXt_f6wVw9jC_kZ1hw'
[download] Resuming download at byte 12515328
[download] Destination: 2018.03.10 - Essential Mix - Peggy Gou-essentialmixcollection-20180310-essential-mix-peggy-gou.m4a
[download]  26.2% of 60.86MiB at 25.54MiB/s ETA 00:01

...
<end of log>
```

### Description of your *issue*, suggested solution and other information

Same issue as referenced here: #14088 which has now been closed with a fix, however still receving the same issue where the download hangs after 5 - 10%. Stopping the script and restarting will download another 5-10%.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/12579#issuecomment-289499840

**Comment by kicks66** [comment]
Stopping the script and starting it again seems to refresh the traffic shaping (I'm guessing as its a new connection, and they are only doing rudimentary tracking?) - is there a way to have the script continuously close and open connections to make downloads faster?

**Comment by dstftw** [comment]
`--http-chunk-size`.
