### ISSUE TITLE
Unable to download Tumblr sensitive contents with --cookies command

### ISSUE THREAD

**Issue by royhsia** [rg3/youtube-dl#16425]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl --cookies cookies.txt 'http://sweetliciousnet.tumblr.com/post/163673652169' -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--cookies', u'cookies.txt', u'http://sweetliciousnet.tumblr.com/post/163673652169', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.09
[debug] Python version 2.7.10 (CPython) - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4-tessus
[debug] Proxy map: {}
[Tumblr] 163673652169: Downloading webpage
[generic] 163673652169: Requesting header
WARNING: Could not send HEAD request to https://www.tumblr.com/safe-mode?url=http://sweetliciousnet.tumblr.com/post/163673652169/: HTTP Error 404: Not Found
[generic] 163673652169: Downloading webpage
WARNING: Falling back on generic information extractor.
WARNING: URL could be a direct video link, returning it as such.
WARNING: "url" field is not a string - forcing string conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://www.tumblr.com/safe-mode?url=http://sweetliciousnet.tumblr.com/post/163673652169/'
[download] safe-mode-163673652169.unknown_video has already been downloaded
[download] 100% of 24.67KiB

```

---

### Description of your *issue*, suggested solution and other information

I use the --cookies command mentioned in issue #13829 . The method was able to download sensitive contents from Tumblr until recently.
 It seems to be [Tumblr] extractor switched back to [generic] extractor due to tumblr safe-mode. The [generic] extractor will download a "safe-mode-xxxxxxxxxxxx.unknown_video" by mistake.

**Comment by royhsia** [comment]
@dstftw May I ask which issue is this issue duplicated to?

**Comment by Hrxn** [comment]
Cookies expired?

**Comment by royhsia** [comment]
YES!
