### ISSUE TITLE
Include DASH for default max resolution selection & download

### ISSUE THREAD

**Issue by himadri0327** [rg3/youtube-dl#1643]
When the highest resolution is DASH, automatically download & mux max-res DASH-VIDEO (say 137) with max bitrate DASH-AUDIO (say 141) as part of the default max resolution selection & download algorithm.

Currently I manually determine if 1080p is only in DASH format and if so run a cmd-script (like below) and thought it could probably be included in youtube-dl itself.

set URL=%*
youtube-dl --get-filename %URL% >tmpfile
set /p fname= <tmpfile
del tmpfile
echo %fname%
youtube-dl --no-mtime --retries 20 -f 137 %URL% -o tmp.vid
youtube-dl --no-mtime --retries 20 -f 141 %URL% -o tmp.aud
ffmpeg -i tmp.vid -i tmp.aud -c copy "%fname%"
del tmp.vid
del tmp.aud

**Comment by Hrxn** [comment]
Zombie issue found. Needs to be closed ASAP.

**Comment by jaimeMF** [comment]
This has been the default behaviour for a long time. Closing.

Thanks @Hrxn.
