### ISSUE TITLE
how to download 30 videos from search link by using Chinese words

### ISSUE THREAD

**Issue by suiyia** [rg3/youtube-dl#16436]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Question

---

**i just want to download all videos from search link using Chinese**，but it report a error.

i have search the question by [#13044](https://github.com/rg3/youtube-dl/issues/13044), but it used English not chinese 

this is examples:

```
youtube-dl "ytsearch30:育儿" 

ERROR Result:
bash: -c: line 0: unexpected EOF while looking for matching `"'
bash: -c: line 1: syntax error: unexpected end of file

```
if i use urlencode for chinese, the search result will become unrelate to keywords

how to solve it ?

wish your reply , thank you ！！！

**Comment by dstftw** [comment]
Post the full output with `-v`. Post the output of `which youtube-dl`.
