### ISSUE TITLE
[Twitch] sslv3 alert handshake failure

### ISSUE THREAD

**Issue by iarspider** [rg3/youtube-dl#16442]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: [u'--ffmpeg-location', u'/home/sysadmin/ffmpeg/bin/ffmpeg']
[debug] Custom config: []
[debug] Command-line args: [u'-a', u'list.txt', u'-v']
[debug] Batch file urls: [u'https://www.twitch.tv/videos/259479406', u'https://www.twitch.tv/videos/259501011', u'https://www.twitch.tv/videos/259507657']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.09
[debug] Python version 2.7.6 (CPython) - Linux-3.13.0-143-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-83431-ga6cee50, ffprobe N-83431-ga6cee50
[debug] Proxy map: {}
[twitch:vod] 259479406: Downloading vod info JSON
[twitch:vod] 259479406: Downloading vod access token
[twitch:vod] 259479406: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://vod-pop-secure.twitch.tv/bba215dc9839d50619ae_iarspider_28633357024_858254978/720p30/index-muted-44YUVNEOWT.m3u8'
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1908, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 365, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 62, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1101, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

youtube-dl fails to dowload Twitch VOD with this error:
`URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>`

wget-ting the last URL in log works fine:
```
$ wget -v -v -S --save-headers https://vod-pop-secure.twitch.tv/bba215dc9839d50619ae_iarspider_28633357024_858254978/720p30/index-muted-44YUVNEOWT.m3u8
--2018-05-13 12:33:27--  https://vod-pop-secure.twitch.tv/bba215dc9839d50619ae_iarspider_28633357024_858254978/720p30/index-muted-44YUVNEOWT.m3u8
Resolving vod-pop-secure.twitch.tv (vod-pop-secure.twitch.tv)... 54.192.27.139, 54.192.27.16, 54.192.27.9, ...
Connecting to vod-pop-secure.twitch.tv (vod-pop-secure.twitch.tv)|54.192.27.139|:443... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Content-Type: application/octet-stream
  Content-Length: 9201
  Connection: keep-alive
  Date: Sun, 13 May 2018 09:24:25 GMT
  Last-Modified: Wed, 09 May 2018 18:06:21 GMT
  ETag: "83b7d63c5319c227d87453f6774c10e5"
  Accept-Ranges: bytes
  Server: AmazonS3
  X-Cache: RefreshHit from cloudfront
  Via: 1.1 b0f96496f0a967a55dc119a35573ce8f.cloudfront.net (CloudFront)
  X-Amz-Cf-Id: 1BnpALRoRWQ_qCcEvJbfSjwDf0JGQJdPKPnuk2GOZh3nGZvpBLfiQQ==
Length: 9201 (9.0K) [application/octet-stream]
Saving to: ‘index-muted-44YUVNEOWT.m3u8’
```

**Comment by dstftw** [comment]
Update python.
