### ISSUE TITLE
Partial playlist download won't start from specified index, always start from head

### ISSUE THREAD

**Issue by zhirshya** [rg3/youtube-dl#16457]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--proxy', u'socks5://127.0.0.1:1080', u'--youtube-skip-dash-manifest', u'-a', u'dnld', u'-r', u'500k']
[debug] Batch file urls: [u'dKUG7qm4ZkM', u'https://www.youtube.com/playlist?list=PLQsLDm9Rq9bHKEBnElquF8GuWkI1EJ8Zp --playlist-start 13']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.09
[debug] Python version 2.7.15 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.4
[debug] Proxy map: {u'http': u'socks5://127.0.0.1:1080', u'https': u'socks5://127.0.0.1:1080'}
[youtube] dKUG7qm4ZkM: Downloading webpage
[youtube] dKUG7qm4ZkM: Extracting video information
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Beginner to Chess Master #13 - Chess Holes-dKUG7qm4ZkM.mkv has already been downloaded and merged
[youtube:playlist] PLQsLDm9Rq9bHKEBnElquF8GuWkI1EJ8Zp: Downloading webpage
[download] Downloading playlist: Beginner to Chess Master
[youtube:playlist] playlist Beginner to Chess Master: Downloading 26 videos
[download] Downloading video 1 of 26
[youtube] CSA9se6t82I: Downloading webpage
[youtube] CSA9se6t82I: Extracting video information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r2---sn-oguesnzl.googlevideo.com/videoplayback?sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2%2Cpl%2Crequiressl%2Csource%2Cexpire&initcwndbps=1467500&key=yt6&lmt=1455898739569710&source=youtube&dur=366.666&gir=yes&signature=B573DDB3023049C36E6630592F8FD4F1CE8038E7.4D1C453CAA135702B5CBD45BDE9FC55E74BF4C66&ipbits=0&requiressl=yes&fvip=2&id=o-AEmlnw_LG2_3nTqULkPgFki-l3NBRakSRIBiOpn8M2in&c=WEB&mv=m&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&mm=31%2C29&mn=sn-oguesnzl%2Csn-oguelnlz&keepalive=yes&pcm2=no&ei=Ij_6WuWDGM6UgQPyj6LoCw&ms=au%2Crdu&itag=247&mt=1526349502&ip=120.51.39.187&mime=video%2Fwebm&pl=16&clen=5003643&expire=1526371202&ratebypass=yes'
[download] Destination: Beginner to Chess Master #1 - How to Checkmate with King and Queen-CSA9se6t82I.f247.webm
[download]  16.8% of 4.77MiB at 698.45KiB/s ETA 00:05^C
ERROR: Interrupted by user
```

---
### Description of your *issue*, suggested solution and other information
Partial playlist download won't start from specified index, always start from head.

**Comment by dstftw** [comment]
Batch file must contain only URLs not options.
