### ISSUE TITLE
New switch request --minimum-rate

### ISSUE THREAD

**Issue by KonomiKitten** [rg3/youtube-dl#16454]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I'd like to request a feature to restart a download when the speed is too slow, I sometimes encounter videos that will download at my full connection speed and then sometimes will download a 20 KiB/s or less. Restarting youtube-dl with the same url remedies this but having youtube-dl do it automatically would be nice. Example, `youtube-dl --minimum-rate RATE`.

**Comment by dstftw** [comment]
`--http-chunk-size`.
