### ISSUE TITLE
max filesize limit doesn't work for some urls

### ISSUE THREAD

**Issue by fireflyHunter** [rg3/youtube-dl#16453]
During this case:
youtube-dl --max-filesize 500m -o 914973423549468672 http://youtu.be/mMzDtZ-gYIc?a

It will keep downloading when exceed the max filesize and download all file parts. (every file parts exceed the size limit)

However most of urls works just fine.

$youtube-dl --version
2018.04.16

**Comment by dstftw** [comment]
```
>youtube-dl.exe http://youtu.be/mMzDtZ-gYIc?a --max-filesize 500m
[youtube] mMzDtZ-gYIc: Downloading webpage
[youtube] mMzDtZ-gYIc: Downloading video info webpage
[youtube] mMzDtZ-gYIc: Extracting video information
[youtube] mMzDtZ-gYIc: Downloading MPD manifest
[youtube] mMzDtZ-gYIc: Downloading MPD manifest
[download] File is larger than max-filesize (2612791290 bytes > 524288000 bytes). Aborting.
```

**Comment by dstftw** [comment]
`--max-filesize` only works for plain HTTP downloads.

**Comment by fireflyHunter** [comment]
The url does starts with http, I try to change it to https but still couldn't get the max-filesize working.
It would be great if you could elaborate on why this url is not a plain HTTP download or how can I fix this for more urls like this one.

**Comment by dstftw** [comment]
Cause it's segmented DASH. You can't "fix" it. It will only work for plain single file downloads that report correct size of the whole file in `Content-Length` HTTP header.
What you may do is to filter based on `filesize` meta field using `--match-filter`. Though this metadata may not be available either.
