### ISSUE TITLE
Is YouTube using MPEG-DASH for delivering its videos?

### ISSUE THREAD

**Issue by pedosb** [rg3/youtube-dl#16467]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

Hello,

I do not konw if this is the correct place to ask this question. But as I saw that there a Question purpose in the questionary I am posting it.

The question is: is YouTube using MPEG-DASH for delivering its videos?

I see that if I use the -F option in youtube-dl for some videos there is no "DASH video", e.g., https://www.youtube.com/watch?v=Us-TVg40ExM. So is YouTube maintainig a connection to the server and requesting the "piece" of video by the "range" field of the HTTP request? Or is it downloading fixed-time segments like stadarized by DASH?

Thank you!

**Comment by dstftw** [comment]
Both approached are used by Youtube.
