### ISSUE TITLE
[ondemandkorea] PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by godly-devotion** [rg3/youtube-dl#16462]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v http://www.ondemandkorea.com/im-not-a-robot-e3-1.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.ondemandkorea.com/im-not-a-robot-e3-1.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.09
[debug] Python version 3.6.5 (CPython) - Linux-4.16.8-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[debug] Using fake IP 99.254.210.178 (CA) as X-Forwarded-For.
[OnDemandKorea] im-not-a-robot-e3-1: Downloading webpage
[OnDemandKorea] im-not-a-robot-e3-1: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://aws3.ondemandkorea.com/v1/201712/drama/im-not-a-robot/im-not-a-robot-e3-1/p720_b2208000_v2071000_a129000_chunk.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 189
[download] Destination: 로봇이 아니야  - 03회, I'm Not a Robot  - E03-im-not-a-robot-e3-1.mp4
ERROR: unable to download video data: [Errno 13] Permission denied: "로봇이 아니야  - 03회, I'm Not a Robot  - E03-im-not-a-robot-e3-1.mp4.ytdl"
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1908, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 365, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/hls.py", line 105, in real_download
    self._prepare_and_start_frag_download(ctx)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/fragment.py", line 69, in _prepare_and_start_frag_download
    self._prepare_frag_download(ctx)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/fragment.py", line 179, in _prepare_frag_download
    self._write_ytdl_file(ctx)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/fragment.py", line 87, in _write_ytdl_file
    frag_index_stream, _ = sanitize_open(self.ytdl_filename(ctx['filename']), 'w')
  File "/usr/lib/python3.6/site-packages/youtube_dl/utils.py", line 457, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
PermissionError: [Errno 13] Permission denied: "로봇이 아니야  - 03회, I'm Not a Robot  - E03-im-not-a-robot-e3-1.mp4.ytdl"
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

When attempting to play any videos from OnDemandKorea.com, youtube-dl returns an error as shown above. I am using macOS 10.13.4.

**Comment by dstftw** [comment]
As clearly stated in the error message you must have write access to the directory the video is being downloaded to.
