### ISSUE TITLE
Icon-Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [rg3/youtube-dl#16476]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.05.09
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Hi Sir @rg3, I am a graphic designer and I want to contribute to your nice project by proposing an icon-logo design.If you like and want to use it I will be gladly sending you the files as a gift to the project for free. If you have any suggestions or modifications pls feel free to notice me. Here's the design Sir:

icons
![youtube dl-01](https://user-images.githubusercontent.com/36028424/40152562-3963f364-59b8-11e8-831d-580129872567.png)
![youtube dl-02](https://user-images.githubusercontent.com/36028424/40152563-39953898-59b8-11e8-8353-03a1f78265aa.png)
![youtube dl-03](https://user-images.githubusercontent.com/36028424/40152564-39cab4d2-59b8-11e8-8927-5c279b7dde44.png)
 
logotypes
![youtube dl-06](https://user-images.githubusercontent.com/36028424/40152610-85f7a87e-59b8-11e8-8d6e-55777411ee28.png)
![youtube dl-04](https://user-images.githubusercontent.com/36028424/40152613-89e60f84-59b8-11e8-9f9e-3aeff2aba35d.png)
![youtube dl-05](https://user-images.githubusercontent.com/36028424/40152616-8b9e82b6-59b8-11e8-9b1c-cb3e2ab9d537.png)

I hope you like and will use it.

Thanks and best regards!
-Tobaloidee

**Comment by adamselby** [comment]
Unsolicited feedback: Ditching the arrow's line, to have a play button that's facing down mimicking the YouTube logo could be fun.

**Comment by Tobaloidee** [comment]
have a look sir
![play-07](https://user-images.githubusercontent.com/36028424/40157760-55f32caa-59d3-11e8-81de-aac58e220714.png)
![play-08](https://user-images.githubusercontent.com/36028424/40157783-6481611a-59d3-11e8-9dc1-c358e6497dd0.png)

**Comment by m-p-3** [comment]
Do you have that in vector format? It would be easier to scale up and reuse on multiple OSes.

**Comment by Tobaloidee** [comment]
Yes i have and will prepare it all now.. :) good morning!

**Comment by Tobaloidee** [comment]
Hello Everyone, here is the link to my drive where you can get all the needed file formats (SVG-PNG-Ai) for the implementations. I am gladly giving these designs to the project as a gift for free.

https://drive.google.com/drive/u/0/folders/1aVY9T9XKc9JPy78eEYhoVDV6cuwhB_zY

here's the summary of all the versions included in the linked drive
![all-16](https://user-images.githubusercontent.com/36028424/40209486-0e5ad060-5a72-11e8-94e8-20a5c2ef46e7.png)

It's going to be rewarding for me to see these designs used in your great project (Readme/Repository).
Thanks again and my best regards!

-Tobaloidee

**Comment by Tobaloidee** [comment]
I created a PR #16501 Sir with the New Logo files
