### ISSUE TITLE
Preserve slashes in video title

### ISSUE THREAD

**Issue by wxv** [rg3/youtube-dl#16482]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

Using 2018.01.14 but I don't think this is version specific. 

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

If a video is titled "5/12", then using `%(title)s` produces "5_12". Is there any way to preserve special characters in the filename? I would be okay with something like "5%2F12". 

Alternatively if there's a fast way to download *only video names* from a playlist (`-e` or `-j` seems do to one video at a time) I will accept that as well.

**Comment by dstftw** [comment]
Not possible. `/` can't be used in filenames. `--get-title`.

**Comment by wxv** [comment]
`--get-title` does one video at a time for playlists, like `-e` or `-j`. Can all the names of playlist videos be downloaded at once? In fact when using `--download-archive` the names are all printed, albeit with extra text.

**Comment by dstftw** [comment]
`--download-archive` has nothing to do with titles. `--flat-playlist` may extract titles for some extractors.
