### ISSUE TITLE
Separate netrc entry for youtube:watchlater

### ISSUE THREAD

**Issue by blimmo** [rg3/youtube-dl#16494]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I'd like to download videos from my watchlater playlist on youtube. While this is possible by logging in I want to use netrc without logging in for other youtube videos. Since it's a separate extractor is it possible to specify a login for youtube:watchlater separately from normal youtube?

**Comment by dstftw** [comment]
Not possible. Watch later extractor just delegates to other extractors so separating different netrc entry for it won't have any effect. Needless to say it's misleading to have several netrc entries for effectively the same service. Thus such feature won't be added.

**Comment by blimmo** [comment]
Thanks for the quick response!

For future readers who want to only login sometimes, I ended up writing a script for it which temporarily changes my `$HOME` so ytdl finds a different `.netrc` which has just my youtube password in it.

    set HOME=<temphome containing temp .netrc>
    youtube-dl -n %* https://www.youtube.com/playlist?list=WL

(Batch script for windows though I'm sure an equivalent bash script could be easily written)
