### ISSUE TITLE
Pluralsight Error

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#16490]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.05.18
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

after update youtube-dl new version now evan pluralsight is not loging in 
but i tried to login in browser and its find there

PS C:\Users\Waqas> youtube-dl --verbose -o 'D:\contents\New folder/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s'
https://app.pluralsight.com/library/courses/sql-server-app-dev-best-practices --sleep-interval 90 --limit-rate 250k --ig
nore-errors --username ****@hotmail.com --password 123
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', 'D:\\contents\\New folder/%(playlist)s/%(playlist_index)s - %(title)s.%(e
xt)s', 'https://app.pluralsight.com/library/courses/sql-server-app-dev-best-practices', '--sleep-interval', '90', '--lim
it-rate', '250k', '--ignore-errors', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.05.18
[debug] Python version 3.5.2 (CPython) - Windows-10-10.0.14393-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] sql-server-app-dev-best-practices: Downloading course JSON
[pluralsight:course] sql-server-app-dev-best-practices: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please repo
rt this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on h
ow to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\program files\python35\lib\site-packages\youtube_dl\extractor\common.py", line 582, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\program files\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\program files\python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "c:\program files\python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\program files\python35\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "c:\program files\python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "c:\program files\python35\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

PS C:\Users\Waqas>

**Comment by remitamine** [comment]
for some reason the requests to [get course data](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/pluralsight.py#L31-L38) does not work on you're side:
```
[debug] System config: []
[debug] User config: ['-f', 'best[height<=720]/bestvideo[height<=720]+bestaudio/best', '--hls-prefer-native', '--external-downloader', 'curl', '--sub-format', 'ass/tt/ttml/dfxp/scc/vtt/srt/sami/best']
[debug] Custom config: []
[debug] Command-line args: ['-v', '-i', '--sleep-interval', '90', '--limit-rate', '250k', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://app.pluralsight.com/library/courses/aws-architecting-reliability']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.18
[debug] Python version 3.6.5 (CPython) - Linux-4.16.9-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.4
[debug] Proxy map: {}
[pluralsight:course] aws-architecting-reliability: Downloading course JSON
[download] Downloading playlist: Architecting for Reliability on AWS
[pluralsight:course] playlist Architecting for Reliability on AWS: Collected 53 video ids (downloading 53 of them)
[download] Downloading video 1 of 53
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] 151113c9-f67a-4ad3-bc19-fe4801d611ba-0: Downloading course JSON
[pluralsight] 151113c9-f67a-4ad3-bc19-fe4801d611ba-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 151113c9-f67a-4ad3-bc19-fe4801d611ba-0: Waiting for 2 seconds to avoid throttling
[debug] Invoking downloader on 'https://vid5.pluralsight.com/expiretime=1526652031/feb8eedd49483e8c7c74858becc1a0bb/clips/resolution/95e56520-10fb-4651-b1f5-11d6da728080/current/mp4/1280x720.mp4'
```

**Comment by jaan143** [comment]
@remitamine  bro when i am trying to login browser first i m getting security captcha then i got login panel

**Comment by yaronjobs88** [comment]
i have same issue for like 20 days now..
i am suing valid account that working via browser but not wok ring in youtube-dl  

here is a link:
https://github.com/rg3/youtube-dl/issues/16394

**Comment by remitamine** [comment]
try to login in the browser and export the cookies, then use the cookies with youtube-dl without providing the credentials.

**Comment by jaan143** [comment]
@remitamine  i tried with cookies but still getting same error
