### ISSUE TITLE
unable to extract OpenGraph title from CBC.CA

### ISSUE THREAD

**Issue by johnnytornado3** [rg3/youtube-dl#16502]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
C:\Documents and Settings\User\Start Menu\Video>youtube-dl -v http://www.cbc.ca/
natureofthings/episodes/the-kingdom-how-fungi-made-our-world
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.cbc.ca/natureofthings/episodes/the
-kingdom-how-fungi-made-our-world']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.05.18
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-77883-gd7c75a5, ffprobe N-77883-gd7c75a5, phantom
js 1.9.7
[debug] Proxy map: {}
[cbc.ca] the-kingdom-how-fungi-made-our-world: Downloading webpage
WARNING: unable to extract OpenGraph title; please report this issue on https://
yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
 to update. Be sure to call youtube-dl with the --verbose flag and include its c
omplete output.
[download] Downloading playlist: the-kingdom-how-fungi-made-our-world
[cbc.ca] playlist the-kingdom-how-fungi-made-our-world: Collected 2 video ids (d
ownloading 2 of them)
[download] Downloading video 1 of 2
[ThePlatform] 1180503107787: Downloading SMIL data
[ThePlatform] 1180503107787: Checking video URL
[ThePlatform] 1180503107787: Checking video URL
[ThePlatform] 1180503107787: Checking video URL
[ThePlatform] 1180503107787: Checking video URL
[ThePlatform] 1180503107787: Checking video URL
[ThePlatform] 1180503107787: Checking video URL
[ThePlatform] 1180503107787: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://progressive.cbc.ca/prodVideo/documentari
es/CBC_Documentaries_VMS/440/507/fungi_promo_2500kbps.mp4?hdnea=st=1526792495~ex
p=1526792885~acl=/prodVideo/documentaries/CBC_Documentaries_VMS/440/507/fungi_pr
omo_*~hmac=d0927aadc3a2b5c4f210f89a38e09ed06ca08e221502cde7a44e9d60735397b8'
[download] The Kingdom, How Fungi Made Our World -  Promo-1180503107787.mp4 has
already been downloaded
[download] 100% of 34.02MiB
[download] Downloading video 2 of 2
[ThePlatform] 1180503107608: Downloading SMIL data
[ThePlatform] 1180503107608: Checking video URL
[ThePlatform] 1180503107608: Checking video URL
[ThePlatform] 1180503107608: Checking video URL
[ThePlatform] 1180503107608: Checking video URL
[ThePlatform] 1180503107608: Checking video URL
[ThePlatform] 1180503107608: Checking video URL
[ThePlatform] 1180503107608: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://progressive.cbc.ca/prodVideo/documentari
es/CBC_Documentaries_VMS/440/507/fungi_explainer_2500kbps.mp4?hdnea=st=152679249
7~exp=1526792887~acl=/prodVideo/documentaries/CBC_Documentaries_VMS/440/507/fung
i_explainer_*~hmac=a93193f79adb2a1a1bd2d111f04e7ef8660b762453f747e266a8974d88ebf
f7b'
[download] The Kingdom, How Fungi Made Our World - What are Fungi-1180503107608.
mp4 has already been downloaded
[download] 100% of 17.83MiB
[download] Finished downloading playlist: the-kingdom-how-fungi-made-our-world

---

---

### Description of your *issue*, suggested solution and other information

unable to extract OpenGraph title from CBC.CA

**Comment by johnnytornado3** [comment]
requesting help to resolve the issue

**Comment by parmjitv** [comment]
Hi @johnnytornado3,

Apparently the OpenGraph title is not set for a number of CBC videos.  A new PR will be submitted to address this.

Cheers,

Parmjit V.

**Comment by johnnytornado3** [comment]
Parmit

I found that the url leads only to a couple of short teasers

when clicking on the play arrow.

However if I right click on the play arrow and select

'open frame in new tab'

Then that leads to a different url in which youtube-dl

works as usual. The entire 45min. video can be accessed.

However I notice that going with youtube-dl default parameters

gives corrupted output for a second or two now and then.

There are messages now and then about incorrect time codes

Thanks Parmit

looking forward to hear from you again

Johnny




THE OLD SIGNATURE BOX


________________________________

**Comment by parmjitv** [comment]
Hi Johnny,

The PR I have submitted will address the missing OpenGraph title warning for the preview videos.

The sporadic incorrect time codes you have noted for the full-length videos sounds like a new and separate issue, and should be opened as such.

Thanks!

Parmjit V.
