### ISSUE TITLE
YouTube download doesn't work?

### ISSUE THREAD

**Issue by suraj021** [rg3/youtube-dl#16506]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested a solution and other information

I am using the latest version of YouTube-dl in my Ubuntu 18.04. Suddenly it stopped working and giving error like **<urlopen error [Errno 113] No route to host>** <br/>
Command: youtube-dl --verbose "https://www.youtube.com/watch?v=-6ZbrfSRWKc" <br/>
Log:
```[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=-6ZbrfSRWKc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.18
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-20-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] -6ZbrfSRWKc: Downloading webpage
[youtube] -6ZbrfSRWKc: Downloading video info webpage
[youtube] -6ZbrfSRWKc: Extracting video information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r3---sn-gxap5ojx-qxae.googlevideo.com/videoplayback?lmt=1520283607241542&ei=vmwBW9G2CdS0oAPsuZfgDA&fvip=1&requiressl=yes&gir=yes&ip=115.254.96.134&key=yt6&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mt=1526819835&mv=u&ms=au%2Crdu&mm=31%2C29&mn=sn-gxap5ojx-qxae%2Csn-h557snsl&id=o-AMjxFFIFRdGHqWPdDCnS_WUJXwAguzfL3jxAXVMZUuAP&signature=E3FBE9A9C281D9EF67E6EE67B517B1F48A67B4EE.9810499A4A006C864FA29CDBB1A15787A0E5A1B8&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C264%2C271%2C278%2C313&clen=196201058&ipbits=0&dur=124.248&itag=313&pl=24&source=youtube&keepalive=yes&c=WEB&expire=1526841630&mime=video%2Fwebm&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [Errno 113] No route to host>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1902, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 365, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 340, in real_download
    establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1101, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 113] No route to host>
``` 
Even the links generated using **-g** flag do not open in  browser and give error as **This site cannot be reached**

**Comment by dstftw** [comment]
Most likely network issue accessing r3---sn-gxap5ojx-qxae.googlevideo.com on your side.

**Comment by suraj021** [comment]
On the same network, it works in mobile but not on pc.
