### ISSUE TITLE
[youtube] "Last message repeated 991 times" (or more)

### ISSUE THREAD

**Issue by marabu88** [rg3/youtube-dl#16511]
Some live streams do not end correctly. I get the message "Last message repeated N times". "N" can be really big and it really downloaded each time.
For download streams from Youtube i use last version yutube-dl and use command string like this:
youtube-dl.exe --hls-use-mpegts https://www.youtube.com/watch?v=XXXXXXXXXXX
Why some streams not ended correctly and how fix it? I can set some limit for this?

**Comment by k03n00b** [comment]
Some limit would be nice.

**Comment by ctlaltdefeat** [comment]
Indeed, what other info is necessary for this issue?
It seems to occur on various live streams.
