### ISSUE TITLE
bash completion and man page for locally installed youtube-dl

### ISSUE THREAD

**Issue by Troyciv** [rg3/youtube-dl#16512]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I installed youtube-dl in my Home directory with:

```
curl -L https://yt-dl.org/downloads/latest/youtube-dl -o ~/bin/youtube-dl
chmod a+rx ~/bin/youtube-dl

```

The bash completion and the man pages are missing. Is there still a way to set them up?

---

[debug] System config: []                                                                                                                      
[debug] User config: []                                                                                                                        
[debug] Custom config: []                                                                                                                      
[debug] Command-line args: [u'--cookies', u'/home/user/Downloads/cookies.txt', u'--verbose', u'https://globoplay.globo.com/v/6749576/programa/'
]                                                                                                                                              
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8                                                                               
[debug] youtube-dl version 2018.05.18                                                                                                          
[debug] Python version 2.7.14 (CPython) - Linux-4.13.0-41-generic-x86_64-with-Ubuntu-17.10-artful                                              
[debug] exe versions: ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4                                                                            
[debug] Proxy map: {}                                                                                                                          
[Globo] 6749576: Downloading JSON metadata                                                                                                     
[Globo] 6749576: Downloading security hash for 6749576_90_720_collection                                                                       
[Globo] 6749576_90_720_collection: Downloading m3u8 information                                                                                
[Globo] 6749576: Downloading security hash for 6749576_90_720_l_collection                                                                     
[Globo] 6749576_90_720_l_collection: Downloading m3u8 information                                                                              
[Globo] 6749576: Downloading security hash for 6749576_360_1080_collection                                                                     
[Globo] 6749576_360_1080_collection: Downloading m3u8 information

**Comment by yan12125** [comment]
FYI: You need to go the pip approach to get man pages and shell completion scripts installed. See the paragraph mentioning pip in https://github.com/rg3/youtube-dl#installation for more information.

**Comment by Troyciv** [comment]
Should I add this information to the readme? Maybe something like:

Tip: If you want to install youtube-dl with man page and shell completion on your Linux machine `pip` is the recommended way

I would volunteer to make a PR

**Comment by yan12125** [comment]
That would be great!
