### ISSUE TITLE
Is it possible to use just a portion of the {title}-string for file naming in the output template?

### ISSUE THREAD

**Issue by 3f8wohoo** [rg3/youtube-dl#16521]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Hi,

I want to separate my downloads into subfolders named by a portion of the {title}-string.
So downloading a video like John Doe - Classic Song will result in

```
/John Doe/John Doe - Classic Song.mp3
```

Is it currently possible to archive this with just using the output template? What shall I do with the {title}-var to truncate it until it reaches the ` -`?

Afaik the python string formatting options can't be used to pass a regex to the output format (using `-o`).

Thanks in advance!

**Comment by dstftw** [comment]
Not possible.
