### ISSUE TITLE
HIDIVE Authentication

### ISSUE THREAD

**Issue by twainilicious** [rg3/youtube-dl#16534]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information
After checking the hidive.py file i noticed it doesn't log the user in, which makes the whole script useless, since all content is locked for people that aren't logged in. So i would like to propose the idea of adding an authentication functionality to that script.
If Account Credentials are needed let me know how i can send them to you privately and i will do so!
Thanks in advance

**Comment by twainilicious** [comment]
@remitamine Hey, i downloaded the source to test if it is working, but running this "python -m youtube_dl https://www.hidive.com/stream/real-girl/s01e008 -u usernamehere -p passwordhere" gives me this output:
`[HiDive] None: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:547)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:547)'),))`
Am I doing something wrong or is the code broken?

**Comment by remitamine** [comment]
post the full verbose log and make sure that you're using an updated python version(using python 3.6.x is recommended).

**Comment by twainilicious** [comment]
`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.hidive.com/stream/real-girl/s01e008', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.05.18
[debug] Python version 3.3.0 (CPython) - Windows-post2008Server-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[HiDive] None: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:547)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:547)'),))
  File ".\youtube_dl\extractor\common.py", line 579, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File ".\youtube_dl\YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python33\lib\urllib\request.py", line 473, in open
    response = self._open(req, data)
  File "C:\Python33\lib\urllib\request.py", line 491, in _open
    '_open', req)
  File "C:\Python33\lib\urllib\request.py", line 451, in _call_chain
    result = func(*args)
  File ".\youtube_dl\utils.py", line 1101, in https_open
    req, **kwargs)
  File "C:\Python33\lib\urllib\request.py", line 1255, in do_open
    raise URLError(err)`
Using the latest python version (3.6.5)
