### ISSUE TITLE
Unable to download videos 

### ISSUE THREAD

**Issue by rajagopalrao** [rg3/youtube-dl#16530]
Hi There,

my current organization has tie up with Udemy. Udemy has given us list of courses as part of the agreement. But, these videos are hosted under our corporate site "abdbd.udemy.com". This site is AD FS federated. I was trying to download these videos using youtube-dl. Is there any way to handle adfs authentication and download these videos?

**Comment by rajagopalrao** [comment]
Can you please let me know the resolution to this issue?

**Comment by dstftw** [comment]
No resolution.
