### ISSUE TITLE
CNBC video extraction not working

### ISSUE THREAD

**Issue by 47ronin** [rg3/youtube-dl#16535]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

CNBC video URL is not recognized and falls back to the generic extractor. There probably should be a way to force a specific extractor using command arguments.

Using a desktop browser (Chrome/Safari), the page video starts with an advertisement (MP4) then proceeds to play the featured video using segmented .ts chunks.

```
$ youtube-dl -v https://www.cnbc.com/video/2014/05/05/capital-allocation-easier-under-current-structure-buffett.html
[debug] System config: []
[debug] User config: [u'--merge-output-format', u'mp4']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.cnbc.com/video/2014/05/05/capital-allocation-easier-under-current-structure-buffett.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.18
[debug] Python version 2.7.15 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg present, ffprobe present
[debug] Proxy map: {}
[generic] capital-allocation-easier-under-current-structure-buffett: Requesting header
WARNING: Falling back on generic information extractor.
[generic] capital-allocation-easier-under-current-structure-buffett: Downloading webpage
[generic] capital-allocation-easier-under-current-structure-buffett: Extracting information
ERROR: Unsupported URL: https://www.cnbc.com/video/2014/05/05/capital-allocation-easier-under-current-structure-buffett.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2261, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 3, column 48
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3201, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.cnbc.com/video/2014/05/05/capital-allocation-easier-under-current-structure-buffett.html

```

**Comment by kenorb** [comment]
Same for:

- https://www.cnbc.com/video/2018/06/06/sec-chairman-cryptocurrencies-like-bitcoin--not-securities.html
- https://www.cnbc.com/47486042-8a94-4d65-ba39-92a1595be01f
