### ISSUE TITLE
Imgur .gifvs no longer download

### ISSUE THREAD

**Issue by 4rm** [rg3/youtube-dl#16545]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
C:\Users\Emilio>youtube-dl -v https://i.imgur.com/gTc3gCc.gifv
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://i.imgur.com/gTc3gCc.gifv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.05.18
[debug] Python version 3.6.0 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-83585-ga5c1c7a, ffprobe N-83585-ga5c1c7a
[debug] Proxy map: {}
[Imgur] gTc3gCc: Downloading webpage
ERROR: No sources found for video gTc3gCc. Maybe an image?
Traceback (most recent call last):
  File "c:\users\emilio\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\emilio\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 503, in extract
    ie_result = self._real_extract(url)
  File "c:\users\emilio\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\imgur.py", line 67, in _real_extract
    expected=True)
youtube_dl.utils.ExtractorError: No sources found for video gTc3gCc. Maybe an image?
```
---

### Description of your *issue*, suggested solution and other information

youtube-dl isn't seeing the .mp4 inside imgur .gifv's anymore. I think they redesigned some of their site and broke the previous functionality. All that needs to be done I think is replace the extension ".gifv" with ".mp4" and it'll be downloadable.

**Comment by yan12125** [comment]
Fixed by @jwilk! (#16537)
