### ISSUE TITLE
.srt file gets italics even though .ttml has none

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#16551]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.26**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Bug report (encountered problems with youtube-dl)

```
$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.26
[debug] Python version 2.7.10 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.4
[debug] Proxy map: {}
```

When converting videos with `.ttml` subtitles using `--write-sub --sub-lang en,no --convert-subtitles srt`:

```
<?xml version="1.0" encoding="UTF-8"?><tt xml:lang="no" xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling">
  <head>
    <styling>
      <style xml:id="italic" tts:fontStyle="italic" />
      <style xml:id="left" tts:textAlign="left" />
    </styling>
  </head>
  <body>
    <div>
      <p begin="00:00:00.000" dur="00:00:10.000" style="left">Hello, World</p>
    </div>
  </body>
</tt>
```

The destination `.srt` file gets italics even though this is not specified in the source `.ttml`. The same happens for any number of subtitles added to the `.ttml` file.

```
1
00:00:00,000 --> 00:00:10,000
<i>Hello, World</i>
```

Example URL (may be geo-restricted):

https://tv.nrk.no/serie/skam-austin/KOIF20001618/sesong-1/episode-3

**Comment by remitamine** [comment]
post a URL to a real subtitle.
