### ISSUE TITLE
[QUESTION] Speed up Downloading js player

### ISSUE THREAD

**Issue by J0K3RAS** [rg3/youtube-dl#16558]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information
 As the title says, it would be appreciated if there was a way to speed up a bit the `Downloading js player` process.

The reason why I want to do this is because i have made an .apk, including youtube-dl and it takes about 20 sec before the download begins

However, on the pc it is a lot faster. Please note that I am using python 3.

**Comment by dstftw** [comment]
Post the full verbose log from that demonstrates the issue (**not from pc**).

**Comment by J0K3RAS** [comment]
Sure, Here it is:
https://drive.google.com/file/d/1sKyigih7Zy2mnbEqi8SBCucg_x7yh5m7/view?usp=sharing

I guess that the output you want is at at the bottom of the log file.
As you will see there is a 25 sec space to start `downloading webpage`
and 5sec space between 'Extracting video information' and choosing the download destination

**Comment by J0K3RAS** [comment]
You are correct, it was a mistake that I made because `Downloading js player` appears only on PC.

I have read about lazy extractors but  haven't found how to use them yet...
