### ISSUE TITLE
[Question] Speeding up 'Downloading js player'

### ISSUE THREAD

**Issue by J0K3RAS** [rg3/youtube-dl#16557]
As the tittle says, I would appreciate it if there was a way to speed up a bit the ` Downloading js player` process. 

The reason I want to do this is because I have made an .apk with youtube_dl included, and it takes around 20 seconds before the download begins.

On pc however, it is a lot faster.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
