### ISSUE TITLE
latest youtube-dl is not working for downloading udemy videos from business account 

### ISSUE THREAD

**Issue by adhikar** [rg3/youtube-dl#16555]
**showing 403 error while hitting udemy url. see below errors.**
`PS D:\> youtube-dl --verbose -u sample@email.com -p password https://businessAccount.udemy.com/getting-started-with-microsoft-azure/learn/v4/overview`

`**overview: Downloading webpage ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by <HTTPError 403: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.**`

**Comment by adhikar** [comment]
you closed first issue without solving it

**Comment by adhikar** [comment]
check the error . exception is throw at time or sending request and it is not because of credentials.

**Comment by dstftw** [comment]
Stop posting duplicates. Custom company domains are not supported.
