### ISSUE TITLE
[request] please use version date in simple standard ISO8601 format (ie no dots in date)

### ISSUE THREAD

**Issue by Corin-EU** [rg3/youtube-dl#16574]
Currently youtube-dl releases are given a version using the date in format "yyyy DOT mm DOT dd"

This format complies with no known standard.

When the versioned egg directory is created, it is created without any leading zero in the month or day field, eg for the current version which is 2018.05.26, one would expect the egg directory to be named (for a python2.7 installation)  youtube_dl-2018.05.26-py2.7.egg, but it is not, it is name youtube_dl-2018.5.26-py2.7.egg without the leading zero on the month.

The ISO8601 standard format does not allow DOTs in the date field -- if the components are to be separated a hyphen is used viz "yyyy-mm-dd", or in the compact form no separator at all viz "yyyymmdd".

Please, please, please can you just use the date format in the version without the dots, so 
that the version date format conforms to ISO standard 8601 "yyyymmdd" format and that the resulting installed egg directory contains the matching date version string with leading zeroes on day and month as appropriate?

Thank you for considering this request.

**Comment by dstftw** [comment]
I don't see any problem in missing leading zeros in some particular cases. Moreover it's anyway impossible to express in ISO8601 second or further versions released the same day (like `2018.05.26.1`). Thus rejected.
