### ISSUE TITLE
Unable to extract video title, uploader name, nickname, video duration

### ISSUE THREAD

**Issue by JRichardH** [rg3/youtube-dl#16590]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.30*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.30**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

> richard@T430:/DATA/Music/Carly Simon
$ sudo youtube-dl -U
[sudo] password for richard: 
youtube-dl is up-to-date (2018.05.30)
richard@T430:/DATA/Music/Carly Simon
$ yta --verbose 'https://youtu.be/c0A7jAVDPJU?list=RDEMGYEVRHxXSrWtgIx9AGqhEg'
youtube-dl -c -k -x --youtube-skip-dash-manifest "$@"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-c', u'-x', u'--youtube-skip-dash-manifest', u'--verbose', u'https://youtu.be/c0A7jAVDPJU?list=RDEMGYEVRHxXSrWtgIx9AGqhEg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.30
[debug] Python version 2.7.13 (CPython) - Linux-4.15.0-1-amd64-x86_64-with-MX-17-Horizon
[debug] exe versions: ffmpeg 3.4.2-1, ffprobe 3.4.2-1
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RDEMGYEVRHxXSrWtgIx9AGqhEg - add --no-playlist to just download video c0A7jAVDPJU
[youtube:playlist] RDEMGYEVRHxXSrWtgIx9AGqhEg: Downloading page 1 of Youtube mix
[youtube:playlist] RDEMGYEVRHxXSrWtgIx9AGqhEg: Downloading page 2 of Youtube mix
[youtube:playlist] RDEMGYEVRHxXSrWtgIx9AGqhEg: Downloading page 3 of Youtube mix
ERROR: Unable to download webpage: <urlopen error [Errno 0] Error> (caused by URLError(error(0, 'Error'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 579, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1101, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)

richard@T430:/DATA/Music/Carly Simon

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

richard@T430:/DATA/Music/Carly Simon
$ yta 'https://youtu.be/c0A7jAVDPJU?list=RDEMGYEVRHxXSrWtgIx9AGqhEg'
youtube-dl -c -k -x --youtube-skip-dash-manifest "$@"
[youtube:playlist] Downloading playlist RDEMGYEVRHxXSrWtgIx9AGqhEg - add --no-playlist to just download video c0A7jAVDPJU
[youtube:playlist] RDEMGYEVRHxXSrWtgIx9AGqhEg: Downloading page 1 of Youtube mix
[youtube:playlist] RDEMGYEVRHxXSrWtgIx9AGqhEg: Downloading page 2 of Youtube mix
[youtube:playlist] RDEMGYEVRHxXSrWtgIx9AGqhEg: Downloading page 3 of Youtube mix
[youtube:playlist] RDEMGYEVRHxXSrWtgIx9AGqhEg: Downloading page 4 of Youtube mix
[download] Downloading playlist: Mix - Carly Simon
[youtube:playlist] playlist Mix - Carly Simon: Collected 69 video ids (downloading 69 of them)
[download] Downloading video 1 of 69
[youtube] tgIx9AGqhEg: Downloading webpage
[youtube] tgIx9AGqhEg: Downloading video info webpage
WARNING: Unable to extract video title
[youtube] tgIx9AGqhEg: Extracting video information
WARNING: unable to extract uploader name
WARNING: unable to extract uploader nickname
WARNING: unable to extract video duration; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.

NOTE: It could be that the videos are just blocked by Youtube, if so, I suppose it goes in the bit bucket as 'won't or can't fix'.  
Thanks for your time and for youtube-dl!

**Comment by dstftw** [comment]
>ERROR: This video is unavailable.

**Comment by JRichardH** [comment]
Just a thought, I use a 3 line script to download and strip out the audio, as follows:
```
# download youtube audio
echo 'youtube-dl -c -k -x --youtube-skip-dash-manifest "$@"'
youtube-dl -c -x --youtube-skip-dash-manifest "$@"
```
It has been working for several years, but there might be a new problem .

**Comment by dstftw** [comment]
No problems here. Your script does not skip errors.
