### ISSUE TITLE
Does not work at Globo Play

### ISSUE THREAD

**Issue by aicoutos** [rg3/youtube-dl#16606]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.30*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.30**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

Does not work at Globo Play. I'm using a valid authorization cookie.
```bash
youtube-dl -v --cookie cookies.txt https://globoplay.globo.com/v/6779730/programa/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--cookie', u'cookies.txt', u'https://globoplay.globo.com/v/6779730/programa/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.30
[debug] Python version 2.7.12 (CPython) - Linux-4.13.0-43-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1
[debug] Proxy map: {}
[Globo] 6779730: Downloading JSON metadata
[Globo] 6779730: Downloading security hash for 6779730_90_720_collection
ERROR: Globo returned error: Video is for subscribers only. Authorization required.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/globo.py", line 120, in _real_extract
    '%s returned error: %s' % (self.IE_NAME, message), expected=True)
ExtractorError: Globo returned error: Video is for subscribers only. Authorization required.
```

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/4189

**Comment by aicoutos** [comment]
@dstftw I thinks that is a temporary failure at next moment after the video upload.
