### ISSUE TITLE
"Slugified" file names

### ISSUE THREAD

**Issue by bjourne** [rg3/youtube-dl#16607]
I don't know what the proper term for the feature I want is. Essentially, if I download this file: https://www.youtube.com/watch?v=Boo6SmgmHuM I want the filename to be all lower case and with all spaces replaced by underscores. Like this: "create_an_artificial_neural_network_with_keras.mp4" Reason being that filenames containing spaces are annoying to deal with in the unix shell. I didn't find an existing output format specifier for that.

**Comment by dstftw** [comment]
`--restrict-filenames`.
