### ISSUE TITLE
Chaturbate Extractor fails on Ubuntu 16.04.4 LTS - Works on W10

### ISSUE THREAD

**Issue by baldoarturo** [rg3/youtube-dl#16616]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.02**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```

me@server:~$ youtube-dl --version
2018.06.02
me@server:~$ youtube-dl --verbose https://es.chaturbate.com/juliaiva/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://es.chaturbate.com/juliaiva/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.02
[debug] Python version 2.7.12 (CPython) - Linux-4.13.0-1017-gcp-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1
[debug] Proxy map: {}
[Chaturbate] juliaiva: Downloading webpage
[Chaturbate] juliaiva: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/me/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/me/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/home/me/.local/lib/python2.7/site-packages/youtube_dl/extractor/chaturbate.py", line 67, in _real_extract
    self._sort_formats(formats)
  File "/home/me/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 1190, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

### Description of your *issue*, suggested solution and other information
m3u8 url is extracted without issues with youtube-dl on w10
on Ubuntu 16.04.4 LTS (google compute engine instance) it fails with error 403

I did a curl of the site and I can manually find the url near "initHlsPlayer(jsplayer, 'https://"

**Comment by baldoarturo** [comment]
My bad, this is a server distro, so no I don't have graphic interface
Other sites seems to work fine, like
`
me@server:~$ youtube-dl --list-formats https://www.youtube.com/watch?v=Kj73Zvz4Mmo
[youtube] Kj73Zvz4Mmo: Downloading webpage
[youtube] Kj73Zvz4Mmo: Downloading video info webpage
[youtube] Kj73Zvz4Mmo: Extracting video information
[youtube] Kj73Zvz4Mmo: Downloading m3u8 information
[youtube] Kj73Zvz4Mmo: Downloading MPD manifest
[info] Available formats for Kj73Zvz4Mmo:
format code  extension  resolution note
91           mp4        256x144    HLS  197k , avc1.4d400c, 30.0fps, mp4a.40.5@ 48k
92           mp4        426x240    HLS  338k , avc1.4d4015, 30.0fps, mp4a.40.5@ 48k
93           mp4        640x360    HLS  829k , avc1.4d401e, 30.0fps, mp4a.40.2@128k
94           mp4        854x480    HLS 1380k , avc1.4d401f, 30.0fps, mp4a.40.2@128k
95           mp4        1280x720   HLS 2593k , avc1.4d401f, 30.0fps, mp4a.40.2@256k
96           mp4        1920x1080  HLS 4715k , avc1.4d4028, 30.0fps, mp4a.40.2@256k (best)
`
Is there any other info I can provide?
Thanks  !

**Comment by dstftw** [comment]
You must prove it's playable in browser via this instance of Ubuntu. Install proxy, use SSH tunnel or what ever.
