### ISSUE TITLE
Hotstar doesn't work anymore, version 2018/06/02

### ISSUE THREAD

**Issue by qAlex26** [rg3/youtube-dl#16611]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ yes] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.02**

### Before submitting an *issue* make sure you have:
- [yes ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ yes] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [yes ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ yes ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

C:\Users\alexa>youtube-dl --verbose "http://www.hotstar.com/1000213341"
[debug] System config: []
[debug] User config: ['-o', '~D:/Project/Youtube-dl-Videos/%(series)s.%(upload_date)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.hotstar.com/1000213341']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.06.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-90893-gcae6f806a6, ffprobe N-90893-gcae6f806a6
[debug] Proxy map: {}
[debug] Using fake IP 117.214.32.25 (IN) as X-Forwarded-For.
[HotStar] 1000213341: Downloading JSON metadata
[HotStar] 1000213341: Downloading JIO JSON metadata
[HotStar] 1000213341: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\extractor\hotstar.py", line 102, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\extractor\common.py", line 1190, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\alexa>youtube-dl -U
youtube-dl is up-to-date (2018.06.02)

MY youtube-dl it's up to date.
my recent thread was closed saying that outdated-version , what does that even means? that I have an outdated version of youtube-dl ?
wrong I have 2016.06.02 version.

my recent thread "
So reccently hotstar I think updated their platform and new videos that are with premium can't be downloaded anymore.
https://i.imgur.com/u5IlDpE.jpg
I do have experience with youtube-dl software and I do download videos from hotstar from some good time.
but reccently I think hotstar started to experiment something new..
I mention that using a india vpn doesn't work either, I tried.

**Comment by remitamine** [comment]
```
youtube-dl http://hotstar.com/1000213341
[HotStar] 1000213341: Downloading JSON metadata
[HotStar] 1000213341: Downloading JIO JSON metadata
[HotStar] 1000213341: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 310
[download] Destination: Naira, Kartik Bump into Each Other-1000213341.mp4
[download]   0.4% of ~321.67MiB at 228.82KiB/s ETA 01:01:23
```
> I mention that using a india vpn doesn't work either, I tried.

most likely the VPN that you're using has been banned by HotStar.

**Comment by qAlex26** [comment]
remitamine, before I could download without a vpn (4 days ago) now it doesn't work with vpn either, I tried with others and it doesn't work.. I know this "youtube-dl" has proxy in it or something like that because before I could download them without problem, but I think hotstar updated something and now it doesn't work.
please check it and update the software.
and I give you 1 link for test : 
try downloading this link : http://www.hotstar.com/1000213307

**Comment by remitamine** [comment]
> I know this "youtube-dl" has proxy in it or something like that because before I could download them without problem, but I think hotstar updated something and now it doesn't work.

- youtube-dl does not use any proxy unless the user provides one.
- if they disabled the geo bypass country method, then we have nothing to do, just use a VPN that is not banned by HotStar.
