### ISSUE TITLE
Safaribooks: Unable to extract kaltura reference id

### ISSUE THREAD

**Issue by vigo** [rg3/youtube-dl#16628]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: ['-o', '%(autonumber)03d-%(title)s.%(ext)s', '--prefer-ffmpeg']
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', 'https://www.safaribooksonline.com/videos/getting-started-with/9781788629744']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.02
[debug] Git HEAD: 8eeddaebc115
[debug] Python version 3.6.4 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[generic] 9781788629744: Requesting header
[redirect] Following redirect to https://www.safaribooksonline.com/library/view/getting-started-with/9781788629744/
[safari:course] Downloading login form
[safari:course] Logging in
[safari:course] 9781788629744: Downloading course JSON
[download] Downloading playlist: Getting Started with Object-Oriented Programming in Python 3
[safari:course] playlist Getting Started with Object-Oriented Programming in Python 3: Collected 20 video ids (downloading 20 of them)
[download] Downloading video 1 of 20
[safari:api] Downloading login form
[safari:api] 9781788629744/video1_1: Downloading part JSON
[safari] Downloading login form
[safari] 9781788629744/video1_1: Downloading webpage
ERROR: Unable to extract kaltura reference id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/vigo/.pyenv/versions/3.6.4/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/Users/vigo/.pyenv/versions/3.6.4/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/Users/vigo/.pyenv/versions/3.6.4/lib/python3.6/site-packages/youtube_dl/extractor/safari.py", line 106, in _real_extract
    webpage, 'kaltura reference id', group='id')
  File "/Users/vigo/.pyenv/versions/3.6.4/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 880, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract kaltura reference id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Did not download : https://www.safaribooksonline.com/videos/getting-started-with/9781788629744

Error was: Unable to extract kaltura reference id

**Comment by vigo** [comment]
I guess something has changed at safaribooks :) this also not working, same error:

- https://www.safaribooksonline.com/videos/real-world-ios-projects/9781789132526
- https://www.safaribooksonline.com/videos/architecting-for-aws/9781788472739

**Comment by joeparkerz** [comment]
Replay Media Catcher is waaaaay better..
