### ISSUE TITLE
Hotstar.com giving HTTP Error 403

### ISSUE THREAD

**Issue by decentsam** [rg3/youtube-dl#16626]
[ yes] I've verified and I assure that I'm running youtube-dl 2018.06.02
[yes ] At least skimmed through the README, most notably the FAQ and BUGS sections
[ yes] Searched the bugtracker for similar issues including closed ones

What is the purpose of your issue?
[this ] Bug report (encountered problems with youtube-dl)

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.hotstar.com/tv/kya-haal-mr paanchal/15017/prarthana-panjiri-tell-a-story/1000213346']
[debug] Encodings: locale cp1251, fs mbcs, out cp437, pref cp1251
[debug] youtube-dl version 2018.06.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-90173-gfa0c9d69d3, ffprobe N-90173-gfa0c9d69d3
[debug] Proxy map: {'https': 'https://103.42.162.50:8080', 'http': 'http://103.42.162.50:8080', 'ftp': 'ftp://103.42.162.50:8080'}
[debug] Using fake IP 117.242.206.37 (IN) as X-Forwarded-For.
[HotStar] 1000213346: Downloading JSON metadata
[HotStar] 1000213346: Downloading JIO JSON metadata
[HotStar] 1000213346: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://hsprepack.akamaized.net/videos/bharat/khamp/226/master_Layer9.m3u8'
[download] Destination: Prarthana, Panjiri Tell a Story-1000213346.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
X-Forwarded-For: 117.242.206.37
Cookie: hdntl=exp=1528126151~acl=%2f*~data=hdntl~hmac=9f2f9dc365a61f8cda7f2706bc4d6a3e61c28117623bcd2a7568ab6bef395c31
Accept-Language: en-us,en;q=0.5
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0 (Chrome)
" -i "https://hsprepack.akamaized.net/videos/bharat/khamp/226/master_Layer9.m3u8" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:Prarthana, Panjiri Tell a Story-1000213346.mp4.part"
ffmpeg version N-90173-gfa0c9d69d3 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
  libavutil      56.  7.101 / 56.  7.101
  libavcodec     58. 13.100 / 58. 13.100
  libavformat    58. 10.100 / 58. 10.100
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 12.100 /  7. 12.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
[https @ 0000028e15eabe40] HTTP error 403 Forbidden
# **https://hsprepack.akamaized.net/videos/bharat/khamp/226/master_Layer9.m3u8: Server returned 403 Forbidden (access denied)**

ERROR: ffmpeg exited with code 1
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\__init__.py", line 472, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\__init__.py", line 462, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\YoutubeDL.py", line 2001, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\YoutubeDL.py", line 803, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\YoutubeDL.py", line 857, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\YoutubeDL.py", line 1635, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\YoutubeDL.py", line 1908, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\YoutubeDL.py", line 1847, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\downloader\external.py", line 64, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\downloader\common.py", line 165, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\YoutubeDL.py", line 620, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\YoutubeDL.py", line 582, in trouble

**Comment by decentsam** [comment]
previously this site was working very fine. now when downloading it shows 403 forbidden error. please have a look into it

**Comment by decentsam** [comment]
no issue of geo restriction

**Comment by dstftw** [comment]
`--proxy`.

**Comment by decentsam** [comment]
[hotstar:playlist] 15017: Downloading JSON metadata
[hotstar:playlist] 14847: Downloading JSON metadata
[download] Downloading playlist: 14847
[hotstar:playlist] playlist 14847: Collected 268 video ids (downloading 268 of them)
[download] Downloading video 1 of 268
[HotStar] 1000213396: Downloading JSON metadata
[HotStar] 1000213396: Downloading JIO JSON metadata
[HotStar] 1000213396: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by decentsam** [comment]
even without proxy getting same error.....!! 

Failed to download m3u8 information: HTTP Error 403: Forbidden

**Comment by decentsam** [comment]
previously this site was working very fine. now when downloading it shows 403 forbidden error. please have a look into it

**Comment by dstftw** [comment]
This site does not respect `X-Forwarded-For` anymore so you **must use proxy or VPN**. As already said either use `--proxy`.
```
>py -3.6 .\youtube_dl\__main__.py http://www.hotstar.com/tv/kya-haal-mr%20paanchal/15017/prarthana-panjiri-tell-a-story/1000213346 --proxy 103.42.162.50:8080
[HotStar] 1000213346: Downloading JSON metadata
[HotStar] 1000213346: Downloading JIO JSON metadata
[HotStar] 1000213346: Downloading m3u8 information
[download] Destination: Prarthana, Panjiri Tell a Story-1000213346.mp4
ffmpeg version N-85653-gb4330a0 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 61.100 / 55. 61.100
  libavcodec     57. 93.100 / 57. 93.100
  libavformat    57. 72.101 / 57. 72.101
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 87.100 /  6. 87.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Input #0, hls,applehttp, from 'https://hsprepack.akamaized.net/videos/bharat/khamp/226/master_Layer9.m3u8':
  Duration: 00:19:40.12, start: 2.100289, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Prarthana, Panjiri Tell a Story-1000213346.mp4.part':
  Metadata:
    encoder         : Lavf57.72.101
    Stream #0:0: Video: h264 (Main) ([33][0][0][0] / 0x0021), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hls,applehttp @ 00000000022824a0] Failed to open segment of playlist 0
frame=  185 fps= 39 q=-1.0 Lsize=    4173kB time=00:00:11.39 bitrate=3000.3kbits/s speed=2.39x
video:4124kB audio:44kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.112604%
Exiting normally, received signal 2.

ERROR: Interrupted by user
```
