### ISSUE TITLE
ERROR: BiliBili said: Video is hidden, while the video can be played

### ISSUE THREAD

**Issue by czy1996** [rg3/youtube-dl#16638]
## Please follow the guide below
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bilibili.com/video/av24293002/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.04
[debug] Python version 3.5.2 (CPython) - Linux-4.13.0-1015-gcp-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
[BiliBili] 24293002: Downloading webpage
[BiliBili] 24293002: Downloading video info page
[BiliBili] 24293002: Downloading video info page
ERROR: BiliBili said: Video is hidden.
Traceback (most recent call last):
  File "/home/zzx1996/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/zzx1996/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/home/zzx1996/.local/lib/python3.5/site-packages/youtube_dl/extractor/bilibili.py", line 165, in _real_extract
    self._report_error(video_info)
  File "/home/zzx1996/.local/lib/python3.5/site-packages/youtube_dl/extractor/bilibili.py", line 101, in _report_error
    raise ExtractorError('%s said: %s' % (self.IE_NAME, result['message']), expected=True)
youtube_dl.utils.ExtractorError: BiliBili said: Video is hidden.
```

---

### Description of your *issue*, suggested solution and other information

When downloading bilibili video, it shows the error that the video is hidden.

```
ERROR: BiliBili said: Video is hidden
```

Actually the video is not hidden and can be played in broswer.

I tested multiple urls like
[https://www.bilibili.com/video/av24293002/?spm_id_from=333.334.chief_recommend.16](url)
[https://www.bilibili.com/video/av24273046/?spm_id_from=333.334.chief_recommend.20](url)

and both of my ubuntu 16.04 pc and vps, all get the same error.

I am not familiar with English, if the description is not clear enough, please let me know

**Comment by pexcn** [comment]
same error

**Comment by Senrt** [comment]
same error, sad :(

**Comment by Wiiplay123** [comment]
Same here. Even tried the referer trick someone posted a few months ago for the error I was having earlier but it still didn't work. :(
