### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable (caused by <HTTPError 503: 'Service Unavailable'>); https://safaribooksonline.com

### ISSUE THREAD

**Issue by vikiaiteam** [rg3/youtube-dl#16636]
C:\youtube-dl-master\downloaded>youtube-dl -u ****@gmail.com -p **** -v --all-subs -i -c -w -o "C:\Bank2020\youtube-dl-master\downloaded\%(playlist)s\%(playl
ist_index)s-%(title)s.%(ext)s" --external-downloader aria2c.exe https://www.safaribooksonline.com/library/view/reactjs-fundamentals-and/9780134688671/ --convert-subs srt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-v', '--all-subs', '-i', '-c', '-w', '-o', 'C:\\youtube-dl-master\\downloaded\\%(playlist)s\\%(playlist_
index)s-%(title)s.%(ext)s', '--external-downloader', 'aria2c.exe', 'https://www.safaribooksonline.com/library/view/reactjs-fundamentals-and/9780134688671/', '--convert-subs', 's
rt']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.06.04
[debug] Python version 3.6.5 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-90866-g48330500ef, ffprobe N-90866-g48330500ef
[debug] Proxy map: {}
[safari:course] Downloading login form
[safari:course] Logging in
[safari:course] 9780134688671: Downloading course JSON
[download] Downloading playlist: React.js Fundamentals and Advanced LiveLessons
[safari:course] playlist React.js Fundamentals and Advanced LiveLessons: Collected 85 video ids (downloading 85 of them)
[download] Downloading video 1 of 85
[safari:api] Downloading login form
[safari:api] 9780134688671/arjs_00_00: Downloading part JSON
[safari] Downloading login form
[safari] 9780134688671-arjs_00_00: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable (caused by <HTTPError 503: 'Service Unavailable'>); please report this issue on https://yt-dl.org/bug . Ma
ke sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python36\lib\site-packages\youtube_dl\extractor\common.py", line 579, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python36\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "c:\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\python36\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by jaan143** [comment]
i am getting the same issue from today

**Comment by fnlxxlobo** [comment]
Any solution? i am with the same problem

**Comment by hyber-code** [comment]
it is working fine 
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--username', 'PRIVATE', '--password', 'PRIVATE', '-o', 'safaribooksonline/%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s', '-a', 'D:/y/lists.txt']
[debug] Batch file urls: ['https://www.safaribooksonline.com/library/view/reactjs-fundamentals-and/9780134688671/']
[debug] Encodings: locale cp1256, fs mbcs, out cp720, pref cp1256
[debug] youtube-dl version 2018.06.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-91152-g7c333dc6a7, ffprobe N-91152-g7c333dc6a7
[debug] Proxy map: {}
[safari:course] Downloading login form
[safari:course] Logging in
[safari:course] 9780134688671: Downloading course JSON
[download] Downloading playlist: React.js Fundamentals and Advanced LiveLessons
[safari:course] playlist React.js Fundamentals and Advanced LiveLessons: Collected 85 video ids (downloading 85 of them)
[download] Downloading video 1 of 85
[safari:api] Downloading login form
[safari:api] 9780134688671/arjs_00_00: Downloading part JSON
[safari] Downloading login form
[safari] 9780134688671-arjs_00_00: Downloading webpage
[safari] 9780134688671-arjs_00_00: Downloading kaltura session JSON
[Kaltura] 9780134688671-arjs_00_00: Downloading webpage
[Kaltura] 0_7lprl3lr: Downloading video info JSON
[Kaltura] 0_7lprl3lr: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/0_7lprl3lr/format/url/protocol/http/flavorId/0_cj3qg5gk/ks/djJ8MTkyNjA4MXwnXhO24MOByIGqN19WN_6h6gYCYTwTqSyIZGjAun30_nKv62b4GLqIwmY7IirL6ctoAiBxfiSO8m5ZyfSacxoxuI9gUQFoz5FEJueKPsNAaA=='
[download] Destination: safaribooksonline\React.js Fundamentals and Advanced LiveLessons\01-React.js Fundamentals and Advanced LiveLessons - Introduction.mp4
[download]   2.2% of 170.63MiB at  1.71MiB/s ETA 01:37
```

**Comment by vikiaiteam** [comment]
It's work fine now
