### ISSUE TITLE
Add man page for youtube-dl.conf

### ISSUE THREAD

**Issue by tyll** [rg3/youtube-dl#16637]
It would be great to have a manpage for the config file since they are usually documented in man pages, too. Maybe it could be just a pointer to the youtube-dl manpage initially.

**Comment by dstftw** [comment]
`make youtube-dl.1`.

**Comment by tyll** [comment]
This is for a man page for youtube-dl, not for the config file, the target would be `make youtube-dl.conf.5`, since config files are documented in section 5.
