### ISSUE TITLE
Proxy used even when it is disabled

### ISSUE THREAD

**Issue by Redirts** [rg3/youtube-dl#16635]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.04**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\tiago_a>"C:\Program Files (x86)\Youtube-DLG\youtube-dl.exe" https://www.youtube.com/watch?v=pMTbYWZ9dZY
[youtube] pMTbYWZ9dZY: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 11004] getaddrinfo failed> (caused by URLError(gaierror(11004, 'getaddrinfo failed'),))

C:\Users\tiago_a>"C:\Program Files (x86)\Youtube-DLG\youtube-dl.exe" https://www.youtube.com/watch?v=pMTbYWZ9dZY --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=pMTbYWZ9dZY', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.06.04
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {'https': 'proxy.xxx.com:3000', 'http': 'proxy.xxx.com:3000'}
[youtube] pMTbYWZ9dZY: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 11004] getaddrinfo failed> (caused by URLError(gaierror(11004, 'getaddrinfo failed'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\common.py", line 579, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\utils.py", line 1101, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
```

### Description of your *issue*, suggested solution and other information

OS: Windows 7 Ultimate

At work I am expected to use a proxy server but elsewhere (home) I turn it off.
My windows/IE proxy settings have the proxy specified but I only activate it when i'm at work:

  1. Open "Configure Proxy settings" (i.e. Type "Configure Proxy settings" on windows start menu
  2. Go to LAN settings
  3. Check the box "Use proxy server.." and fill in something.
  4. Untick the box "Use proxy server.."
  5. Close OK and OK

All other applications interpret this as the proxy setting being off but youtube-dl ignores the checkbox "Use proxy server..." and uses the proxy anyway.

**Comment by dstftw** [comment]
youtube-dl does not use these settings. Proxy is specified in your env veriables.
