### ISSUE TITLE
[Request] Videos from mega.nz

### ISSUE THREAD

**Issue by theelectricsoul** [rg3/youtube-dl#16649]
**last version I tested**
2018.06.04

**not working URL**
https://mega.nz/#!OGBHyKrI!eTHVXOuC35Y4_9SvN5Wo2FKMWIk78PxHNfCUdiUCopo

**Hint**
Jdownloader is able to download it.

**Comment by rautamiekka** [comment]
Your ytdl is ancient ! By 3y 11d, to be exact.

Also, don't skip the issue template, it's an automatic closure as incomplete.

**Comment by llacb47** [comment]
@rautamiekka look when the issue was opened...

**Comment by theelectricsoul** [comment]
@rautamiekka 
Dude...    this ticket is pretty old.
