### ISSUE TITLE
Clobbering YouTube auto subs for some reason

### ISSUE THREAD

**Issue by mtcjayne** [rg3/youtube-dl#16644]
I confirm I have:
- [X] Verified that I'm running youtube-dl **2018.06.04**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output:

```
youtube-dl --skip-download --write-auto-sub -o "%(title)s" -v https://www.youtube.com/watch?v=v0WQ2NnDuOg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--skip-download', u'--write-auto-sub', u'-o', u'%(title)s', u'-v', u'https://www.youtube.com/watch?v=v0WQ2NnDuOg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.04
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-9.1
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] v0WQ2NnDuOg: Downloading webpage
[youtube] v0WQ2NnDuOg: Downloading video info webpage
[youtube] v0WQ2NnDuOg: Looking for automatic captions
[youtube] v0WQ2NnDuOg: Downloading MPD manifest
[youtube] v0WQ2NnDuOg: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: 20180601160701.en.vtt
```

---

### Description of your *issue*, suggested solution and other information

A video in question is titled `20180601160701.done_002` on YouTube but youtube-dl downloads the auto subs to `20180601160701.en.vtt` instead of `20180601160701.done_002.en.vtt` as a user (at least this user) might expect.

**Comment by dstftw** [comment]
Output template must contain unhardcoded `ext`.

**Comment by mtcjayne** [comment]
What does that even mean? It has nothing to do with the extension. The title has a string in it that your tool is ignoring. Don't make your tool try to be smart when it as a result does stupid stuff.

**Comment by mtcjayne** [comment]
To be clear, when trying to simply download the video the video is saved to the proper filename, so whatever solution you think solves the problem is not a solution. Your tool is specifically doing something it shouldn't when deciding what to name sub files.

**Comment by mtcjayne** [comment]
(I will just run youtube-dl twice, once to get the proper title and another time to get the subtitle file and save it to the proper file. Enjoy me using double your API quota I guess.)
