### ISSUE TITLE
Youtube-dl HTTP Error 403: Forbidden 

### ISSUE THREAD

**Issue by fnlxxlobo** [rg3/youtube-dl#16642]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other
_______________________________________________________________________________________________________________

If anyone can help me. I need these classes in my HD to be able to review when and how many times I want, after all it is a very expensive course.

**Comment by Troyciv** [comment]
try sending your cookie with your sessionID to the server with the ``--cookies filename`` option

In firefox I use an addon called "cookies.txt" to export the cookies *after* I logged into the site

**Comment by fnlxxlobo** [comment]
how can I do this? Can you help me?

**Comment by fnlxxlobo** [comment]
C:\Users\fnlxx>youtube-dl --no-cache-dir --cookies cookies.txt --print-traffic --dump-pages --verbose https://videos.cdn.cers.com.br/kraush/video/XX-AAABWV/734858/dash/6028_052318_PREVIDENCIARIO_AULA_06_PT_I_OK.mpd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-cache-dir', '--cookies', 'cookies.txt', '--print-traffic', '--dump-pages', '--verbose', 'https://videos.cdn.cers.com.br/kraush/video/XX-AAABWV/734858/dash/6028_052318_PREVIDENCIARIO_AULA_06_PT_I_OK.mpd']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.06.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-89369-g5a93a85fd0, ffprobe N-89369-g5a93a85fd0
[debug] Proxy map: {}
[generic] 6028_052318_PREVIDENCIARIO_AULA_06_PT_I_OK: Requesting header
WARNING: Could not send HEAD request to https://videos.cdn.cers.com.br/kraush/video/XX-AAABWV/734858/dash/6028_052318_PREVIDENCIARIO_AULA_06_PT_I_OK.mpd: HTTP Error 403: Forbidden
[generic] 6028_052318_PREVIDENCIARIO_AULA_06_PT_I_OK: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\common.py", line 579, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
