### ISSUE TITLE
How to force youtube-dl to download YouTube content through its Android app?

### ISSUE THREAD

**Issue by Sepehr2016** [rg3/youtube-dl#16651]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### Description of your *issue*, suggested solution and other information

YouTube website is banned here and I have to use a proxy to access it via my web browser or youtube-dl to work, but ironically the YouTube Android application on phones and tablets work like a charm without using any proxies at all and videos get loaded much much faster as they are directly loaded without a proxy in between. I'm looking for a way to force youtube-dl to download videos like if it was the YouTube app, as I often get errors while I'm downloading videos through a proxy in youtube-dl.

Also another little question is, is there a way to pause and resume youtube-dl downloads like IDM (Internet Download Manager)?

**Comment by dstftw** [comment]
You can't make youtube-dl download through android app. Ctrl+C for pause and rerun for resume.

**Comment by Sepehr2016** [comment]
I meant resuming it after a download error in the middle of the download.

**Comment by jonsag** [comment]
Sepehr2016: youtube-dl does resume when interrupted.
