### ISSUE TITLE
youtube-dl Facebook Download doesn't work with Login

### ISSUE THREAD

**Issue by Django1987** [rg3/youtube-dl#16655]
Download doesn't work with username and password. Without username and password it works.

C:\Program Files\youtube-dl>youtube-dl https://www.facebook.com/leonardo.skay.9/videos/195483897920447/ --username 'privat' --password 'privat'
[facebook] Downloading login page
[facebook] Logging in
[facebook] 195483897920447: Downloading webpage
[facebook] 195483897920447: Downloading webpage
[facebook] 195483897920447: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by adampetrovic** [comment]
Also seeing this

**Comment by EnginePod** [comment]
Can confirm an issue with this as well (although I get an error saying that the credentials are wrong when they aren't).

**Comment by Twilight0** [comment]
I can also confirm it.

    youtube-dl.exe --verbose https://www.facebook.com/prokolgotki/videos/1037266369756603/ --username *private* --password *private*
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: [u'--verbose', u'https://www.facebook.com/prokolgotki/videos/1037266369756603/', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
    [debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
    [debug] youtube-dl version 2018.06.04
    [debug] Python version 2.7.15 (CPython) - Windows-10-10.0.17134
    [debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
    [debug] Proxy map: {}
    [facebook] Downloading login page
    [facebook] Logging in
    [facebook] 1037266369756603: Downloading webpage
    [facebook] 1037266369756603: Downloading webpage
    [facebook] 1037266369756603: Downloading webpage
    ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
    File "p:\programs\python 2\lib\site-packages\youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
    File "p:\programs\python 2\lib\site-packages\youtube_dl\extractor\common.py", line 500, in extract
    ie_result = self._real_extract(url)
    File "p:\programs\python 2\lib\site-packages\youtube_dl\extractor\facebook.py", line 462, in _real_extract
    video_id, fatal_if_no_video=True)
    File "p:\programs\python 2\lib\site-packages\youtube_dl\extractor\facebook.py", line 376, in _extract_from_url
    raise ExtractorError('Cannot parse data')
    ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
