### ISSUE TITLE
Support for udemy course download from company sub domains subscribed from udemy.

### ISSUE THREAD

**Issue by Braj65** [rg3/youtube-dl#16652]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.04**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[redirect] Following redirect to https://MYCOMPANY.udemy.com/sasscourse/
[generic] sasscourse: Requesting header
WARNING: Falling back on generic information extractor.
[generic] sasscourse: Downloading webpage
[generic] sasscourse: Extracting information
ERROR: Unsupported URL: https://MYCOMPANY.udemy.com/sasscourse/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\generic.py", line 3263, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://MYCOMPANY.udemy.com/sasscourse/
```

---

### Description of your *issue*, suggested solution and other information
So my company has recently bought subscription of udemy courses. Udemy has provided the subscription which is accessible from a subdomain having the company name-https://MYCOMPANYNAME.udemy.com. When i am trying to download using this url i am getting above mentioned error in the log. Is there anyway i can bypass it using a regular expression? Or is any feature under works for this issue?

**Comment by Braj65** [comment]
Let me know about the duplicate issue no. which is being tracked.

**Comment by karlochacon** [comment]
This one works flawlessly 
https://www.npmjs.com/package/udemy-dl
it even supports business accounts
