### ISSUE TITLE
Cannot see the embedded thumbnail

### ISSUE THREAD

**Issue by adrianTNT** [rg3/youtube-dl#16669]
using version `2018-04-16`
I don't see the thumbnail being embedded, I attached a full log and command.
I was expecting to see the thumbnail when I download the mp3 in windows 7 and see the files as thumbnails, that is how it works for the other Mp3 that seem to have a thumbnail included. 
Isn't that what `--embed-thumbnail` does ? 
Also, I tried without the option and the mp3 file size is a bit smaller.

> youtube-dl -v --extract-audio --audio-format=mp3 --embed-thumbnail https://www.youtube.com/watch?v=0RyInjfgNc4
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--extract-audio', '--audio-format=mp3', '--embed-thumbnail', 'https://www.youtube.com/watch?v=0RyInjfgNc4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.16
[debug] Python version 3.4.8 (CPython) - Linux-3.10.0-862.3.2.el7.x86_64-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: ffmpeg 2.8.14, ffprobe 2.8.14
[debug] Proxy map: {}
[youtube] 0RyInjfgNc4: Downloading webpage
[youtube] 0RyInjfgNc4: Downloading video info webpage
[youtube] 0RyInjfgNc4: Extracting video information
[youtube] {22} signature length 43.42, html5 player vfl_RUk0U
[youtube] {43} signature length 43.42, html5 player vfl_RUk0U
[youtube] {18} signature length 43.42, html5 player vfl_RUk0U
[youtube] {36} signature length 43.42, html5 player vfl_RUk0U
[youtube] {17} signature length 43.42, html5 player vfl_RUk0U
[youtube] {137} signature length 43.42, html5 player vfl_RUk0U
[youtube] {248} signature length 43.42, html5 player vfl_RUk0U
[youtube] {136} signature length 43.42, html5 player vfl_RUk0U
[youtube] {247} signature length 43.42, html5 player vfl_RUk0U
[youtube] {135} signature length 43.42, html5 player vfl_RUk0U
[youtube] {244} signature length 43.42, html5 player vfl_RUk0U
[youtube] {134} signature length 43.42, html5 player vfl_RUk0U
[youtube] {243} signature length 43.42, html5 player vfl_RUk0U
[youtube] {133} signature length 43.42, html5 player vfl_RUk0U
[youtube] {242} signature length 41.42, html5 player vfl_RUk0U
[youtube] {160} signature length 43.42, html5 player vfl_RUk0U
[youtube] {278} signature length 43.42, html5 player vfl_RUk0U
[youtube] {140} signature length 43.42, html5 player vfl_RUk0U
[youtube] {171} signature length 43.42, html5 player vfl_RUk0U
[youtube] {249} signature length 43.42, html5 player vfl_RUk0U
[youtube] {250} signature length 43.42, html5 player vfl_RUk0U
[youtube] {251} signature length 43.42, html5 player vfl_RUk0U
[youtube] 0RyInjfgNc4: Downloading thumbnail ...
[youtube] 0RyInjfgNc4: Writing thumbnail to: Rihanna - Love On The Brain-0RyInjfgNc4.jpg
[debug] Invoking downloader on 'https://r3---sn-4g5e6nzz.googlevideo.com/videoplayback?itag=171&id=o-AFv5cFhnTTo4UNSo4r8YW_Y11czbdJFSD1N84gmNDQ8m&source=youtube&ip=2a01%3A4f8%3A1c1c%3Aff8%3A%3A1&key=yt6&lmt=1500401329975412&dur=219.732&mime=audio%2Fwebm&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&fvip=6&c=WEB&gir=yes&initcwndbps=1241250&pl=45&ei=v2wZW_32L4PggAf9nINQ&mt=1528392756&mv=m&clen=3431943&ms=au%2Conr&keepalive=yes&expire=1528414495&requiressl=yes&mm=31%2C26&mn=sn-4g5e6nzz%2Csn-5hnednlr&ipbits=0&signature=4B103B889A5DDF78B5043EA7CC951DD3CE8AD9B6.A6D2C57653CD8362B1A3FDECD5911EA9D2EEFE92&ratebypass=yes'
[download] Destination: Rihanna - Love On The Brain-0RyInjfgNc4.webm
[download] 100% of 3.27MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams 'file:Rihanna - Love On The Brain-0RyInjfgNc4.webm'
[ffmpeg] Destination: Rihanna - Love On The Brain-0RyInjfgNc4.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:Rihanna - Love On The Brain-0RyInjfgNc4.webm' -vn -acodec libmp3lame -q:a 5 'file:Rihanna - Love On The Brain-0RyInjfgNc4.mp3'
Deleting original file Rihanna - Love On The Brain-0RyInjfgNc4.webm (pass -k to keep)
[ffmpeg] Adding thumbnail to "Rihanna - Love On The Brain-0RyInjfgNc4.mp3"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Rihanna - Love On The Brain-0RyInjfgNc4.mp3' -i 'file:Rihanna - Love On The Brain-0RyInjfgNc4.jpg' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:Rihanna - Love On The Brain-0RyInjfgNc4.temp.mp3'

**Comment by dstftw** [comment]
>[ffmpeg] Adding thumbnail to "Rihanna - Love On The Brain-0RyInjfgNc4.mp3"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Rihanna - Love On The Brain-0RyInjfgNc4.mp3' -i 'file:Rihanna - Love On The Brain-0RyInjfgNc4.jpg' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:Rihanna - Love On The Brain-0RyInjfgNc4.temp.mp3'

![image](https://user-images.githubusercontent.com/1908898/41136371-291fa3fa-6b00-11e8-9c79-4eb8ca0784d9.png)
