### ISSUE TITLE
Feature: Support youtube live

### ISSUE THREAD

**Issue by chovy** [rg3/youtube-dl#16663]
It would be nice to get a live stream . url from youtube live that I could use in a different player like vlc.

**Comment by dstftw** [comment]
Live streams are supported just fine.

**Comment by chovy** [comment]
From the official Youtube TV Live service?

**Comment by dstftw** [comment]
There are no telepathists. Bother to read and fill issue template appropriately.

**Comment by Mithgol** [comment]
I've noticed today that a relatively large broadcast (almost two hours) could not be downloaded from YouTube immediately after the end of that broadcast and even 25 minutes after. (The failed result was a two seconds chunk from the very beginning instead of the complete recording of the stream.) However, then I waited a bit longer (probably even an hour, I don't really remember) and YouTube-DL could download it successfully. I've decided to think it's not a YouTube-DL's issue but rather YouTube's that broadcasts are sometimes not immediately available.
