### ISSUE TITLE
Unable to update on server 2012 r2 via scheduled task.

### ISSUE THREAD

**Issue by MrStonedOne** [rg3/youtube-dl#16662]
See topic.

It downloads the new one and creates the batch script and does something to trigger the batch script to be ran, but the lock for youtube-dl stays open while the batch script runs so it fails to update.

**Comment by MrStonedOne** [comment]
The only true fix is to allow -U to be passed a argument with the name of the binary to update, so the updater and updatee can be different binaries.

**Comment by MrStonedOne** [comment]
also: is there a way to force an update? I can't test this on the latest version because its. well, the latest version.

**Comment by dstftw** [comment]
`-U` updates just fine. youtube-dl is not responsible for work of any other updating mechanism. You can't force update on up-to-date version.

**Comment by MrStonedOne** [comment]
>youtube-dl is not responsible for work of any other updating mechanism. 

A scheduled task is a timer to run a command, the command it runs is `youtube-dl -U`, this does not work because youtube-dl's lock on itself never releases.

Please read bug reports before closing. For bonus points, its generally considered bad form to close a issue report before follow up questions are asked and answered.

@remitamine @rg3 @dstftw Re-open please.

**Comment by rg3** [comment]
Unable to reproduce. youtube-dl.exe -U works fine here from the command line under Windows 10. You can download older versions from here to test:

https://github.com/rg3/youtube-dl/releases

I set up a scheduled task to run youtube-dl.exe -U and it finished successfully, using an older version. After that, I checked and the binary had been updated.

**Comment by MrStonedOne** [comment]
alright, but I strongly suggest you add a way to force an update, as its the only way to test the current version and any issue i'm having could easily be some old bug since the version I was trying to update from was nov2017.

**Comment by MrStonedOne** [comment]
And what happens when its a bug that was fixed in the current version?

Like is it really that controversial that having a part of your code that literally can't be tested is bad?

**Comment by rg3** [comment]
NB: I stepped down as the maintainer several years ago, so what I say here is just my opinion.

I don't think it's controversial. Thing is, the hard part about updating to a newer version is overwriting the binary in place. In Python, downloading and reading an HTTP or HTTPS URL is almost trivial, so testing that case is not representative of the whole upgrade process working.
