### ISSUE TITLE
Partial downloads, specified by start and end times

### ISSUE THREAD

**Issue by Ectomind1990** [rg3/youtube-dl#16665]
---

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Please may we have a new feature to allow partial downloads?

This could save large amounts of download time and temporary space requirements in some cases. eg. nobody could possibly want the 1st 3 hours of [this Apple event](https://www.youtube.com/watch?v=fWSsEQzRnOw) and somebody even may just want a 1 min clip but would have to wait for the full 11 hour video to download

I don't know whether this is technically possible but it's still worth having this feature request in place to track it

I also wonder whether the video comes in segments so technically you can have a partial download but not with the exact times you want as it has to match the segment boundaries. So instead of `start-time` and `end-time` I am thinking 
```
youtube-dl --latest-start-time 3:18:00 --earliest-finish-time 3:21:58 https://www.youtube.com/watch?v=fWSsEQzRnOw
```

I found these other requests for a partial download based on file size but nothing based on times
https://github.com/rg3/youtube-dl/issues/1795
https://github.com/rg3/youtube-dl/issues/11609

**Comment by Ectomind1990** [comment]
@dstftw Do you know which number issue this is a duplicate of so I can read it? Thanks

Or if anybody else knows?

**Comment by dstftw** [comment]
#622.
