### ISSUE TITLE
Program gets stuck on ffmpeg conversion

### ISSUE THREAD

**Issue by NightMachinary** [rg3/youtube-dl#16671]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.04**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

I first noticed this problem when using instantmusic: https://github.com/yask123/Instant-Music-Downloader/issues/126
But the problem is with yt-dl:
```
youtube-dl --audio-format mp3 --prefer-avconv -x https://www.youtube.com/watch?v=3oJxBhD94_s
[youtube] 3oJxBhD94_s: Downloading webpage
[youtube] 3oJxBhD94_s: Downloading video info webpage
[download] Destination: Melanie Martinez - milk and cookies (ONE HOUR LOOP)-3oJxBhD94_s.webm
[download] 100% of 67.26MiB in 00:02
[ffmpeg] Destination: Melanie Martinez - milk and cookies (ONE HOUR LOOP)-3oJxBhD94_s.mp3
```
It just hangs on this. I tried forcing it to use avconv, but with no success. I tried using `m4a`, but then I get:
```
[ffmpeg] Destination: Melanie Martinez - milk and cookies (ONE HOUR LOOP)-3oJxBhD94_s.m4a
ERROR: audio conversion failed: [aac @ 0x682100] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
```

**Comment by NightMachinary** [comment]
It eventually unstuck. After a long 10 minutes.

**Comment by Hrxn** [comment]
Outdated ffmpeg?
