### ISSUE TITLE
Udemy Course - 10 out of 15 chapters only downloaded

### ISSUE THREAD

**Issue by aremsg** [rg3/youtube-dl#16679]
youtube-dl --cookies /Users/[user]/Downloads/udemy-cookies.txt -o '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s' [udemy course link]

Downloaded up until chapter 10. There are a total of 15 chapters.

Error:

Unable to download webpage: HTTP Error 403: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Bother to read the new issue template and fill in it appropriately.

**Comment by aremsg** [comment]
I honestly dont understand all this. I'm not tech savvy. 
Please help me. Excuse my ignorance in this field.

**Comment by aremsg** [comment]
I would sincerely appreciate if you could help me out

**Comment by dstftw** [comment]
I've already pointed out: read [issue template](https://github.com/rg3/youtube-dl/issues/new) and fill in.
