### ISSUE TITLE
[NPO] NPO.nl redirects to NPOstart.nl; UnsupportedError

### ISSUE THREAD

**Issue by karottenbaum** [rg3/youtube-dl#16682]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
pi@carbon:~$ youtube-dl https://npo.nl/KN_1698996 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://npo.nl/KN_1698996', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.04
[debug] Python version 2.7.13 (CPython) - Linux-4.14.34-v7+-armv7l-with-debian-9.4
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] KN_1698996: Requesting header
[redirect] Following redirect to https://www.npostart.nl/broodje-gezond-ei/28-05-2018/KN_1698996
[generic] KN_1698996: Requesting header
WARNING: Falling back on generic information extractor.
[generic] KN_1698996: Downloading webpage
[generic] KN_1698996: Extracting information
ERROR: Unsupported URL: https://www.npostart.nl/broodje-gezond-ei/28-05-2018/KN_1698996
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2308, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 60, column 97
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 3263, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.npostart.nl/broodje-gezond-ei/28-05-2018/KN_1698996

```
---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

As can be seen by the logs, npo.nl redirects to npostart.nl which has no extractor.

**Comment by karottenbaum** [comment]
Seems like this can be fixed by adding npostart.nl to `_VALID_URL`. Test 3 fails though.

**Comment by tdegeus** [comment]
I have a related error, which I'm not sure if I should file separately. With the new url I get

```bash
$ youtube-dl https://www.npostart.nl/klikbeet/06-05-2018/VPWON_1283753
[generic] VPWON_1283753: Requesting header
WARNING: Falling back on generic information extractor.
[generic] VPWON_1283753: Downloading webpage
[generic] VPWON_1283753: Extracting information
ERROR: Unsupported URL: https://www.npostart.nl/klikbeet/06-05-2018/VPWON_1283753
```

whereas manually selecting the old url yields:

```bash
$ youtube-dl https://www.npo.nl/klikbeet/06-05-2018/VPWON_1283753
[npo] VPWON_1283753: Downloading JSON metadata
[npo] VPWON_1283753: Downloading token
[npo] VPWON_1283753: Downloading formats JSON
[npo] VPWON_1283753: Downloading Adaptive stream JSON
[npo] VPWON_1283753: Downloading m3u8 information
[npo] VPWON_1283753: Downloading Hoog stream JSON
[npo] VPWON_1283753: Downloading Normaal stream JSON
[npo] VPWON_1283753: Downloading Laag stream JSON
[download] Destination: Klikbeet-VPWON_1283753.m4v
[download] 100% of 180.98MiB in 00:38
```
