### ISSUE TITLE
parliament.uk (kaltura widget) video download broken 

### ISSUE THREAD

**Issue by samsmith** [rg3/youtube-dl#16709]
The Parliament.uk site has changed how it embeds video, and the regexp match has broken. It doesn't appear that the video hosting backend changed in any obvious way at the same time.

---

$ youtube --verbose https://www.parliamentlive.tv/Event/Index/46aabd31-9eb5-4733-a91f-f21b5fded856
youtube-dl is up-to-date (2018.06.11)
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.parliamentlive.tv/Event/Index/46aabd31-9eb5-4733-a91f-f21b5fded856']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.11
[debug] Python version 2.7.10 (CPython) - Darwin-17.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump present
[debug] Proxy map: {}
[parliamentlive.tv] 46aabd31-9eb5-4733-a91f-f21b5fded856: Downloading webpage
ERROR: Unable to extract kaltura widget config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/sams/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/Users/sams/bin/youtube-dl/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/Users/sams/bin/youtube-dl/youtube_dl/extractor/parliamentliveuk.py", line 32, in _real_extract
    webpage, 'kaltura widget config'), video_id)
  File "/Users/sams/bin/youtube-dl/youtube_dl/extractor/common.py", line 880, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract kaltura widget config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment]
```
python __main__.py https://www.parliamentlive.tv/Event/Index/46aabd31-9eb5-4733-a91f-f21b5fded856
[parliamentlive.tv] 46aabd31-9eb5-4733-a91f-f21b5fded856: Downloading webpage
[parliamentlive.tv] 46aabd31-9eb5-4733-a91f-f21b5fded856: Downloading JSON metadata
[Kaltura] 1_wcxgqpda: Downloading video info JSON
[Kaltura] 1_wcxgqpda: Downloading m3u8 information
[download] Destination: Digital, Culture, Media and Sport Committee-1_wcxgqpda.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21  100    21    0     0     39      0 --:--:-- --:--:-- --:--:--    39
  0 1741M    0 3057k    0     0   446k      0  1:06:37  0:00:06  1:06:31  601k
```

**Comment by samsmith** [comment]
as of this morning (~12 hours ago when I checked), it seems to be working again.
