### ISSUE TITLE
"... blocked it from display on this website or application"

### ISSUE THREAD

**Issue by sdnebel** [rg3/youtube-dl#16703]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.11**

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Question

### Description of your *issue*, suggested solution and other information

Trying to download the YouTube video at [youtube.com/watch?v=UkkJZweYaLI](https://www.youtube.com/watch?v=UkkJZweYaLI) results in:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=UkkJZweYaLI', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.06.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-81516-gbe07c25, ffprobe N-81516-gbe07c25, rtmpdump 2.4
[debug] Proxy map: {}

[youtube] UkkJZweYaLI: Downloading webpage
[youtube] UkkJZweYaLI: Downloading embed webpage
[youtube] UkkJZweYaLI: Refetching age-gated info webpage
ERROR: This video contains content from Mosfilm, who has blocked it from display on this website or application. Watch on YouTube

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0ud6453h\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0ud6453h\build\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0ud6453h\build\youtube_dl\extractor\youtube.py", line 1875, in _real_extract
youtube_dl.utils.ExtractorError: This video contains content from Mosfilm, who has blocked it from display on this website or application. Watch on YouTube
```

Watching the video outside of YouTube.com is disabled, I get that.

I've tried working around it by using `--referer https://www.youtube.com/` but I get the same result.

Any ideas? Thank you.

**Comment by dstftw** [comment]
You must authenticate to download this video.
