### ISSUE TITLE
How to pass in filename arguments from youtube-dl to exec?

### ISSUE THREAD

**Issue by MichaelMallett** [rg3/youtube-dl#16700]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

I'm struggling to figure out the format for -exec when running ffmpeg, I'm attempting to cut an audio file from youtube into a 30 second clip. However, I can't figure out a way to use {}, or youtube-dl output formats in the exec command. 

If I try to use {} as the output name like so
youtube-dl -x https://soundcloud.com/rinsefm/sasasas110618 --exec "ffmpeg -ss 00:01:00.00 -i {} -ss 00:00:00.00 -t 00:00:30.00 {}"

I get a 
`Error while decoding stream #0:0: Invalid data found when processing input`, presumably because it's overwriting the file while reading.

If I try and use the youtube-dl format for naming I get a syntax error as this is not valid for ffmpeg

youtube-dl -x https://soundcloud.com/rinsefm/sasasas110618 --exec 'ffmpeg -ss 00:01:00.00 -i {} -ss 00:00:00.00 -t 00:00:30.00 %(uploader)s%(title)s.%(ext)s'

I've been searching for hours in the find -exec  documentation an across forums and I can't find a way to alter the name of the output file dynamically from the input file in exec. Ideally I'd like to use the original filename but append _clip to the name. Any pointers?

**Comment by dstftw** [comment]
Input and output names should be different as you already mentioned. Also `--exec` does not support output template.
