### ISSUE TITLE
Downloading video from NY Times fails

### ISSUE THREAD

**Issue by 0Billy** [rg3/youtube-dl#16701]
$ ./youtube-dl --verbose "https://www.nytimes.com/video/us/politics/100000005948848/trump-us-kim-north-korea-summit-2018.html?playlistId=100000003890188"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.nytimes.com/video/us/politics/100000005948848/trump-us-kim-north-korea-summit-2018.html?playlistId=100000003890188']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.11
[debug] Python version 2.7.5 (CPython) - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-86027-g15e892a-tessus, ffprobe N-86027-g15e892a-tessus
[debug] Proxy map: {}
[NYTimes] 100000005948848: Downloading video JSON
[NYTimes] 100000005948848: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/nytimes.py", line 127, in _real_extract
    return self._extract_video_from_id(video_id)
  File "./youtube-dl/youtube_dl/extractor/nytimes.py", line 75, in _extract_video_from_id
    self._sort_formats(formats)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1190, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug .

**Comment by remitamine** [comment]
> [debug] Python version 2.7.5 (CPython) - Darwin-13.4.0-x86_64-i386-64bit

update to Python 2.7.9 or newer.
