### ISSUE TITLE
Changes to ABC iview

### ISSUE THREAD

**Issue by AussieViewer** [rg3/youtube-dl#16704]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

---

---

### Description of your *issue*, suggested solution and other information

Up until now, youtube-dl has been working well with ABC-iview. All I needed to do
was find the video on the iview site and copy its URL into youtube-dl.

ABC has now changed its method of delivering videos from flash to HTML5. The videos now play within the hosting page, which does not have a URL specific to the video. I can see no way of identifying the video URL is a way that youtube-dl will recognize. I have not been able to find it in the page source.

Right-clicking on the video while it plays brings up a message "Powered by JW Player 8.2.0"

I'd be grateful for any information or suggestions that people may have about this.

**Comment by aristaeus** [comment]
I was actually looking at iView a couple of days ago - I wanted to see if I could use the livestream with youtube-dl/mpv. The old Flash player worked fine, but the livestream was using the new HTML5 player for testing, and it didn't work. It seems to be using the new HTML DRM standard - Firefox is displaying a lock that I've never seen before.

I suspect it won't be easy, or even possible to get around this, but I don't know enought to comment further. If not, I'm afraid you'll have to remove it from your list of supported sites.

**Comment by ringofyre** [comment]
Maybe I don't understand the nomenclature here but even the test from the commit - https://github.com/rg3/youtube-dl/commit/e0671819e71744b6a9a32fc3f4d5fbc8aca8a8f1

https://iview.abc.net.au/show/ben-and-hollys-little-kingdom/series/0/video/ZX9371A050S00

yields - 

$ youtube-dl -v https://iview.abc.net.au/show/ben-and-hollys-little-kingdom/series/0/video/ZX9371A050S00
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://iview.abc.net.au/show/ben-and-hollys-little-kingdom/series/0/video/ZX9371A050S00']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.11
[debug] Python version 2.7.13 (CPython) - Linux-4.16.0-0.bpo.1-amd64-x86_64-with-debian-9.4
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ZX9371A050S00: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ZX9371A050S00: Downloading webpage
[generic] ZX9371A050S00: Extracting information
ERROR: Unsupported URL: https://iview.abc.net.au/show/ben-and-hollys-little-kingdom/series/0/video/ZX9371A050S00
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2308, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 11, column 46
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3263, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://iview.abc.net.au/show/ben-and-hollys-little-kingdom/series/0/video/ZX9371A050S00
