### ISSUE TITLE
ABC iView extractor broken by web site changes

### ISSUE THREAD

**Issue by section83** [rg3/youtube-dl#16718]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.11**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -F -v https://iview.abc.net.au/show/apple-tree-yard
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'-v', u'https://iview.abc.net.au/show/apple-tree-yard']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.11
[debug] Python version 2.7.10 (CPython) - Darwin-17.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0-tessus, ffprobe 4.0-tessus, rtmpdump 2.4
[debug] Proxy map: {}
[generic] apple-tree-yard: Requesting header
WARNING: Falling back on generic information extractor.
[generic] apple-tree-yard: Downloading webpage
[generic] apple-tree-yard: Extracting information
ERROR: Unsupported URL: https://iview.abc.net.au/show/apple-tree-yard
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2308, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 11, column 46
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3263, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://iview.abc.net.au/show/apple-tree-yard
```
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

I don't know how to get a URL for a single video.  iView are now using "JW Player" and all individual videos are accessed from the one page for each show.

---

### Description of your *issue*, suggested solution and other information

ABC iView (in Australia) have upgraded their site replacing Flash with JW Player and other changes.  The youtube-dl extractor can no longer download videos.  The example URL in the log give above is not the URL of a video or playlist but just a page for accessing individual videos by buttons.   At present, I don't know how to get URLs for individual videos.

**Comment by ringofyre** [comment]
>At present, I don't know how to get URLs for individual videos.

Click the share button and then copy link. Still doesn''t work tho

dstftw could we have some clarity on which is the "Fixed" release as I have

> youtube-dl version 2018.06.11

which is listed as the latest release here and is the only ver. available via -U

**Comment by dstftw** [comment]
No such release is yet released.
