### ISSUE TITLE
Autonumber for Seasons

### ISSUE THREAD

**Issue by jeffwcollins** [rg3/youtube-dl#16713]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X ] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.11**

### Before submitting an *issue* make sure you have:
- [ X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ X ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ X ] Feature request (request for a new functionality)
- [ X ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I have searched far and wide on not only this site, but throughout the google-verse, and cannot seem to find anything related to my question, so opening this was my last option.

I am downloading youtube videos to allow my daughter to watch through Plex, and with the Plex naming conventions what they are, I would like to find a way to automatically add a season number to the individual playlists from those gamers/channels that I am pulling from.  The "season" output format functionality is what I would love to use, but, NONE of the channel owners that I am pulling from use those tags on their videos.  I am able to use the "playlist_index" as a pseudo episode number which works great, but there are no series names, season names, season numbers or anything on those videos to pull to help organize them by season. When I do add the auto increment, it pre-fixes a number to each folder in addition to me adding the episode number, leaving me with multiple "playlist(season)" folders. 

Example of episode numbers working:
%(uploader)s/%(playlist)s/E%(playlist_index)s - %(title)s/%(title)s.%(ext)s" https://www.youtube.com/user/Hypnotizd/playlists

What I would like to know, is if its possible to automatically add a number before the playlist.
What I have:
- Hypnotizd/Forever Stranded Lost Souls (Modded Minecraft)/
  - E01 - Forever Stranded Lost Souls - Getting Started [E01] (Modded Minecraft)/
- Hypnotizd/Some Other Playlist (example)/
  - E01 - episode name (example)/

What I am requesting help with getting working:
 - Hypnotizd/S01 - Forever Stranded Lost Souls (Modded Minecraft)/
   - E01 - Forever Stranded Lost Souls - Getting Started [E01] (Modded Minecraft)
 - Hypnotizd/S02 - Some Other Playlist (example)/
   - E01 - episode name (example)/
 - Hypnotizd/S03 - Another Playlist (example)/
   - E01 - episode name (example)/

Thanks for atleast reading thus far, and I appreciate the effort and support on this app.

**Comment by dstftw** [comment]
Not possible.
