### ISSUE TITLE
playlist content scrapping

### ISSUE THREAD

**Issue by mzramna** [rg3/youtube-dl#16714]
i was trying to extract the ids from a playlist into youtube,but it has to download all data from all playlist before i was able to get any data from anything in there ,since it has already downloaded this data that i need to begin the process of downloading all the other datas , it has a way to get this and i just couldnt find it or it is unable to do it using the youtube-dl library for python?Since i'm working with a enormous playlist(this one into the code is an exemple much smaller than the one that i'm using) i cant wait it to download all the unecessary data from all the playlist every time i run the script,ps json is to store all the processed and unprocessed data

> from youtube_dl import YoutubeDL
import json
url = 'PLMC9KNkIncKvYin_USF1qoJQnIyMAfRxl'
ytdl = YoutubeDL()
info = ytdl.extract_info(url, download=False)['id']
print(info.keys())
print (info['id'])
with open('youtube_dl_datamining.txt','w') as output_file:
	json.dump(info,output_file)

**Comment by dstftw** [comment]
`--flat-playlist`.

**Comment by mzramna** [comment]
this works like this just into the execution of youtube-dl aplication from the terminal dont?How do we use this into the python script?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/blob/3e4cedf9e8cd3157df2457df7274d0c842421945/youtube_dl/YoutubeDL.py#L222
