### ISSUE TITLE
What is :ytsubs ?

### ISSUE THREAD

**Issue by initrider** [rg3/youtube-dl#16729]
I have seen a lot of people in "Issues" section who are talking about :ytsubs option, but there is no about it in README

**Comment by dstftw** [comment]
Shortcut for downloading Youtube's account subscriptions.

**Comment by initrider** [comment]
@dstftw ghm, is it official thing? It's just strange, that where is no information about it in man.

**Comment by dstftw** [comment]
It's not supposed to be in man since it's just an extractor, one of 1200+ extractors.
