### ISSUE TITLE
Add windows chocolatey package manger install instructions for youtube-dl.

### ISSUE THREAD

**Issue by mariomills** [rg3/youtube-dl#16720]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.11**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [X] Other

---

### Add windows chocolatey package manger install instructions for youtube-dl in the readme file.
![13010867_1108419342514517_3989522761622604349_n](https://user-images.githubusercontent.com/31293181/41330283-934eafac-6ea0-11e8-8846-7fe152e37a71.png)

Chocolatey the package manager for windows, has a [package](https://chocolatey.org/packages/youtube-dl) for youtube-dl and it is maintained by [purity](https://chocolatey.org/profiles/purity) and [chocolatey](https://chocolatey.org/profiles/chocolatey).

**Comment by dstftw** [comment]
I don't see any point in that since official exe is provided.

**Comment by mariomills** [comment]
It automatically adds the program to path, and makes it easy to update.

**Comment by Blanen** [comment]
> 
> 
> I don't see any point in that since official exe is provided.

@dstftw because this:
![image](https://user-images.githubusercontent.com/7236824/55912118-58ad4e00-5be2-11e9-89e0-20181b41f122.png)
It's an extra step which can just be made a dependency: https://chocolatey.org/packages/vcredist2010

And, as @mariomills says. The package can add itself to PATH.

Just seems weird providing a brew package and not a choco one. Why not just provide a .app?
