### ISSUE TITLE
Why not use a generic extractor for peertube?

### ISSUE THREAD

**Issue by SoniEx2** [rg3/youtube-dl#16733]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

---

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Currently, each peertube instance needs to be manually added to youtube-dl. It would be nicer if youtube-dl had a generic extractor that simply tried to detect peertube instances (the API's a good start, also webfinger and stuff), as then peertube-supporting versions would be compatible with all peertube instances. This is a bigger deal for things like ubuntu which don't have rolling release.

**Comment by okias** [comment]
```
youtube-dl https://video.blender.org/videos/watch/b37a5b9f-e6b5-415c-b700-04a5cd6ec205
[generic] b37a5b9f-e6b5-415c-b700-04a5cd6ec205: Requesting header
WARNING: Falling back on generic information extractor.
[generic] b37a5b9f-e6b5-415c-b700-04a5cd6ec205: Downloading webpage
[generic] b37a5b9f-e6b5-415c-b700-04a5cd6ec205: Extracting information
[download] Destination: The Daily Dweebs-b37a5b9f-e6b5-415c-b700-04a5cd6ec205.unknown_video
[download] 100% of 6.21KiB in 00:00
```

I guess youtube-dl-2018.06.11 does use generic extractor, but it doesn't work correctly :(
