### ISSUE TITLE
ERROR: ffprobe or avprobe not found (MAC, idle, py2app)

### ISSUE THREAD

**Issue by steam3d** [rg3/youtube-dl#16754]
I installed ffmpeg and youtube-dl for python. It works. 
I used the IDLE to write a program and when i run it, i have an error "ERROR: ffprobe or avprobe not found".

Then i just opened a terminal with python3 and run my script. it works without errors.
I thought that error has only in IDLE, i build my app with py2app and again i have the error "ERROR: ffprobe or avprobe not found".

How can i fixed this?

I used this fragment for clarity 
```
from __future__ import unicode_literals
import youtube_dl


class MyLogger(object):
    def debug(self, msg):
        pass

    def warning(self, msg):
        pass

    def error(self, msg):
        print(msg)


def my_hook(d):
    if d['status'] == 'finished':
        print('Done downloading, now converting ...')


ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192',
    }],
    'logger': MyLogger(),
    'progress_hooks': [my_hook],
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://www.youtube.com/watch?v=BaW_jenozKc'])
```

**Comment by dstftw** [comment]
ffmpeg must be in `PATH` for a session you run IDLE from. Or set `ffmpeg_location` option with hardcoded value.
