### ISSUE TITLE
External Downloader option is ignored when downloading from ok.ru

### ISSUE THREAD

**Issue by lem0n4de** [rg3/youtube-dl#16769]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.19*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://ok.ru/video/952583587217', '--external-downloader', 'aria2c', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.14
[debug] Python version 3.6.5 (CPython) - Linux-4.17.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1
[debug] Proxy map: {}
[Odnoklassniki] 952583587217: Downloading webpage
[Odnoklassniki] 952583587217: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://vd42.mycdn.me/expires/1529520520275/srcIp/212.174.135.240/srcAg/GECKO/type/1/sig/0b06369d063e0b8d3cdb8b31976a2c7412381dc5/ct/8/urls/217.20.157.201%3B217.20.153.80%3B217.20.152.73/clientType/0/id/307735759586/video/'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 13
[download] Destination: Девочка довела до слез!!!!!!!!-952583587217.mp4
[download] 100% of 8.88MiB in 01:13
[debug] ffmpeg command line: ffprobe -show_streams 'file:Девочка довела до слез!!!!!!!!-952583587217.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Девочка довела до слез!!!!!!!!-952583587217.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Девочка довела до слез!!!!!!!!-952583587217.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Девочка довела до слез!!!!!!!!-952583587217.temp.mp4'
```

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

When I try to download a video from ok.ru with any external downloader option, they are ignored and download goes directly to youtube-dl's downloader which is slow.
This is an example video link : https://ok.ru/video/952583587217

**Comment by dstftw** [comment]
aria2c does not support HLS.
