### ISSUE TITLE
BBC video download is unplayable in quicktime for mac and receiving 403 error.

### ISSUE THREAD

**Issue by jpfootball** [rg3/youtube-dl#16778]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.19*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.bbc.co.uk/iplayer/episode/p069dkj5/motd-2018-world-cup-sweden-v-south-korea-mini-highlights', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.19
[debug] Python version 2.7.10 (CPython) - Darwin-17.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1
[debug] Proxy map: {}
[bbc.co.uk] p069dkj5: Downloading video page
[bbc.co.uk] p069dkj5: Downloading playlist JSON
[bbc.co.uk] p069dkq0: Downloading media selection XML
[bbc.co.uk] p069dkq0: Downloading m3u8 information
[bbc.co.uk] p069dkq0: Downloading m3u8 information
[bbc.co.uk] p069dkq0: Downloading MPD manifest
[bbc.co.uk] p069dkq0: Downloading MPD manifest
[bbc.co.uk] p069dkq0: Downloading m3u8 information
[bbc.co.uk] p069dkq0: Downloading m3u8 information
[bbc.co.uk] p069dkq0: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] p069dkq0: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] p069dkq0: Downloading m3u8 information
[bbc.co.uk] p069dkq0: Downloading m3u8 information
[bbc.co.uk] p069dkq0: Downloading MPD manifest
[bbc.co.uk] p069dkq0: Downloading MPD manifest
[bbc.co.uk] p069dkq0: Downloading m3u8 information
[bbc.co.uk] p069dkq0: Downloading m3u8 information
[bbc.co.uk] p069dkq0: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] p069dkq0: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/0e1351-p069dkq0/vf_p069dkq0_e08174bb-c925-409d-8ad1-9ee3b0610802.ism.hlsv2.ism/dash/'
[dashsegments] Total fragments: 50
[download] Destination: Match of the Day, MOTD 2018 World Cup, Sweden v South Korea - Mini Highlights-p069dkq0.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-video=5070000.mp4
[download]   2.0% of ~63.97MiB at 62.10KiB/s ETA 20:40^C
ERROR: Interrupted by user

---

---

### Description of your *issue*, suggested solution and other information

I am trying to download highlights/replays of football/soccer matches from bbciplayer. I am using NordVPN and have also made an account with bbc. I can view this video in my browser, chrome or safari. The first problem is that an error appears saying "WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden", but after it goes through that a couple times the video starts downloading. It successfully downloads however when I go to open it, it says Quicktime Player cant open "(name of the video)". I stopped the download this time since I didnt want to wait 20 minutes but I was able to download it earlier. I am a newbie when it comes to anything with code or the terminal so apologies if this is a stupid question. THanks in advance for your help.

**Comment by jpfootball** [comment]
@dstftw Hi, I am really sorry, I have read the one you are saying is a duplicate, and do not understand how it is related/how it helps me fix this. The main problem was quicktime player not opening it, not downloading just part of the video. Doing my best here but I have very limited knowledge of coding. The help on these forums is amazing to see, and I definitely need it.

**Comment by dstftw** [comment]
Use normal players. mpv and vlc play these files just fine.
