### ISSUE TITLE
I need a support for this site - youtube-dl doesn't work anymore

### ISSUE THREAD

**Issue by TeRrOkToR** [rg3/youtube-dl#16773]
I need your help !!! I can not download the video lessons any more.

Here is the link "https://videos.cdn.cers.com.br/kraush/video/XX-AAAAGB/178984/dash/RJ_5760_121217_D_CONST_AULA_02_PT_II-v2.mpd"

Here is the inspect of page "https://videos.cdn.cers.com.br/kraush/speed/empty.mp4?course=5760&buffer=30.697363&duration=18 38.976&time=10.185979&bandwidth=7781.3809&quality= &volume=1&currentSpeed=1x&evento=progress&engineNa me=dash&type=application/dash+xml&course_p=5760&email=xxxxxxx@xxxxxxx.com&n ome=XXXXXX%20XXXXX&cers_video=503915&matricula=194 8892&navigator.platform=Win32&navigator.vendor=Goo gle%20Inc.&navigator.userAgent=Mozilla/5.0%20(Windows%20NT%206.1;%20Win64;%20x64)%20Apple WebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/67.0.3396.87%20Safari/537.36&aba=1529440640885&message=flowplayer%2010%2 0time:%2010"

The fragments of video "https://videos.cdn.cers.com.br/kraush/video/XX-AAAAGB/178988/dash/kraus-4-f2-v1.m4s?course=5760&matricula=1948892&aba=152944064 0885&time=10.935979&startTime=30"

"https://videos.cdn.cers.com.br/kraush/video/XX-AAAAGB/178988/dash/kraus-5-f1-a1.m4s?course=5760&matricula=1948892&aba=152944064 0885&time=12.438021&startTime=40"

"https://videos.cdn.cers.com.br/kraush/video/XX-AAAAGB/178988/dash/kraus-5-f2-v1.m4s?course=5760&matricula=1948892&aba=152944064 0885&time=20.187&startTime=40"

"https://videos.cdn.cers.com.br/kraush/video/XX-AAAAGB/178988/dash/kraus-6-f1-a1.m4s?course=5760&matricula=1948892&aba=152944064 0885&time=21.437979&startTime=50"

"https://videos.cdn.cers.com.br/kraush/video/XX-AAAAGB/178988/dash/kraus-6-f2-v1.m4s?course=5760&matricula=1948892&aba=152944064 0885&time=31.186979&startTime=50"

"https://videos.cdn.cers.com.br/kraush/video/XX-AAAAGB/178988/dash/kraus-7-f1-a1.m4s?course=5760&matricula=1948892&aba=152944064 0885&time=32.686979&startTime=60"

"https://videos.cdn.cers.com.br/kraush/video/XX-AAAAGB/178988/dash/kraus-7-f2-v1.m4s?course=5760&matricula=1948892&aba=152944064 0885&time=40.187&startTime=60"

"https://videos.cdn.cers.com.br/kraush/video/XX-AAAAGB/178988/dash/kraus-8-f1-a1.m4s?course=5760&matricula=1948892&aba=152944064 0885&time=41.686979&startTime=70"

there are several fragments

How can I download the video?

Tks !!!

Debug log

§youtube-dl -f -v "https://videos.cdn.cers.com.br/kraush/video/XX-A
AAAGB/178984/dash/RJ_5760_121217_D_CONST_AULA_02_PT_II-v2.mpd"
[generic] RJ_5760_121217_D_CONST_AULA_02_PT_II-v2: Requesting header
WARNING: Could not send HEAD request to https://videos.cdn.cers.com.br/kraush/vi
deo/XX-AAAAGB/178984/dash/RJ_5760_121217_D_CONST_AULA_02_PT_II-v2.mpd: HTTP Erro
r 403: Forbidden
[generic] RJ_5760_121217_D_CONST_AULA_02_PT_II-v2: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.

§youtube-dl -v "https://videos.cdn.cers.com.br/kraush/video/XX-AAAA
GB/178984/dash/RJ_5760_121217_D_CONST_AULA_02_PT_II-v2.mpd"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://videos.cdn.cers.com.br/kraush/video/X
X-AAAAGB/178984/dash/RJ_5760_121217_D_CONST_AULA_02_PT_II-v2.mpd']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.06.19
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-90627-ge54679b6c1
[debug] Proxy map: {}
[generic] RJ_5760_121217_D_CONST_AULA_02_PT_II-v2: Requesting header
WARNING: Could not send HEAD request to https://videos.cdn.cers.com.br/kraush/vi
deo/XX-AAAAGB/178984/dash/RJ_5760_121217_D_CONST_AULA_02_PT_II-v2.mpd: HTTP Erro
r 403: Forbidden
[generic] RJ_5760_121217_D_CONST_AULA_02_PT_II-v2: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\bu
ild\youtube_dl\extractor\common.py", line 598, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\bu
ild\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt

§youtube-dl -v https://videos.cdn.cers.com.br/kraush/video/XX-AAAAG
B/178984/dash/RJ_5760_121217_D_CONST_AULA_02_PT_II-v2.mpd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://videos.cdn.cers.com.br/kraush/video/X
X-AAAAGB/178984/dash/RJ_5760_121217_D_CONST_AULA_02_PT_II-v2.mpd']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.06.19
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-90627-ge54679b6c1
[debug] Proxy map: {}
[generic] RJ_5760_121217_D_CONST_AULA_02_PT_II-v2: Requesting header
WARNING: Could not send HEAD request to https://videos.cdn.cers.com.br/kraush/vi
deo/XX-AAAAGB/178984/dash/RJ_5760_121217_D_CONST_AULA_02_PT_II-v2.mpd: HTTP Erro
r 403: Forbidden
[generic] RJ_5760_121217_D_CONST_AULA_02_PT_II-v2: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\bu
ild\youtube_dl\extractor\common.py", line 598, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\bu
ild\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt

**Comment by dstftw** [comment]
You must exactly mimic browsers behavior including cookies, headers and so on.
