### ISSUE TITLE
JSInterpreter fail

### ISSUE THREAD

**Issue by ruoying86** [rg3/youtube-dl#16785]
function getsign(){

  var o = new IviBlowFish("f10232b7bc5c7ae8f796c1332b27a18c", "e9044861170176cc", "d20890c22e02ed83").cmacbf("tg_UHAJQh3g{\"method\":\"da.content.get\",\"params\":[133305,{\"app_version\":5913,\"session\":\"a92726aa1616000842_1543986721-78407951ADA8tRkQ7jp5Lxf5w8nb6g\",\"site\":\"s1698\",\"uid\":\"91523.213977600\",\"_url\":\"https://www.ivi.tv\",\"adblock\":0,\"user_ab_bucket\":5305}]}");

  return o;
});
def parse_sig_js(jscode):
    jsi = JSInterpreter(jscode)
    initial_function = jsi.extract_function("test")
    s="test"
    res=initial_function(s)
    return res

errormsg:
raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'new IviBlowFish("f10232b7bc5c7ae8f796c1332b27a18c", "e9044861170176cc", "d20890c22e02ed83").cmacbf("tg_UHAJQh3g{\\"method\\":\\"da.content.get\\",\\"params\\":[133305,{\\"app_version\\":5913,\\"session\\":\\"a92726aa1616000842_1543986721'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output

the version is the newest

**Comment by dstftw** [comment]
`JSInterpreter` is not a full-fledged JS engine but only support particular language subset. Use phantomjs.
