### ISSUE TITLE
Downloading wrong language from Vrv

### ISSUE THREAD

**Issue by cclloyd** [rg3/youtube-dl#16799]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

NOTE:  I am using a modified version of [this](https://hub.docker.com/r/vimagick/youtube-dl/~/dockerfile/) docker image.  The dockerfile contents will be listed below so you can build yourself if you need to test if that's where the error lies.

```
FROM jrottenberg/ffmpeg:alpine

RUN set -xe \
    && apk add --no-cache ca-certificates \
                          openssl \
                          python3 \
    && pip3 install youtube-dl

WORKDIR /data

ENTRYPOINT ["youtube-dl"]
CMD ["--help"]
```

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-w', '-u', 'PRIVATE', '-p', 'PRIVATE', '--sub-lang', 'en-US', 'https://vrv.co/watch/GY75DW536/The-Ancient-Magus-Bride:April-showers-bring-May-flowers', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.19
[debug] Python version 3.6.3 (CPython) - Linux-4.9.87-linuxkit-aufs-x86_64-with
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[vrv] GY75DW536: Downloading webpage
[vrv] GY75DW536: Downloading ja-JP MPD information
[vrv] GY75DW536: Downloading ar-ME MPD information
[vrv] GY75DW536: Downloading de-DE MPD information
[vrv] GY75DW536: Downloading en-US MPD information
[vrv] GY75DW536: Downloading es-ES MPD information
[vrv] GY75DW536: Downloading es-LA MPD information
[vrv] GY75DW536: Downloading fr-FR MPD information
[vrv] GY75DW536: Downloading it-IT MPD information
[vrv] GY75DW536: Downloading pt-BR MPD information
[vrv] GY75DW536: Downloading ru-RU MPD information
[vrv] GY75DW536: Downloading ja-JP m3u8 information
[vrv] GY75DW536: Downloading ar-ME m3u8 information
[vrv] GY75DW536: Downloading de-DE m3u8 information
[vrv] GY75DW536: Downloading en-US m3u8 information
[vrv] GY75DW536: Downloading es-ES m3u8 information
[vrv] GY75DW536: Downloading es-LA m3u8 information
[vrv] GY75DW536: Downloading fr-FR m3u8 information
[vrv] GY75DW536: Downloading it-IT m3u8 information
[vrv] GY75DW536: Downloading pt-BR m3u8 information
[vrv] GY75DW536: Downloading ru-RU m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://v.vrv.co/evs/8f36c65cc10676cc0cb60fab68c96d87/assets/367ad1b256386d419db0ad93926159fb_,3321986.mp4,3321987.mp4,3321985.mp4,3321983.mp4,3321984.mp4,.urlset/'
[dashsegments] Total fragments: 148
[download] Destination: April showers bring May flowers-GY75DW536.fdash-it-IT-f2-v1-x3.mp4
[download] 100% of 681.34MiB in 03:38.97MiB/s ETA 00:0017
[debug] Invoking downloader on 'https://v.vrv.co/evs/8f36c65cc10676cc0cb60fab68c96d87/assets/367ad1b256386d419db0ad93926159fb_,3397398.mp4,3397399.mp4,3397397.mp4,3397396.mp4,3397395.mp4,.urlset/'
[dashsegments] Total fragments: 148
[download] Destination: April showers bring May flowers-GY75DW536.fdash-ru-RU-f1-a1-x3.m4a
[download] 100% of 22.62MiB in 01:34.02MiB/s ETA 00:0002
[ffmpeg] Merging formats into "April showers bring May flowers-GY75DW536.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:April showers bring May flowers-GY75DW536.fdash-it-IT-f2-v1-x3.mp4' -i 'file:April showers bring May flowers-GY75DW536.fdash-ru-RU-f1-a1-x3.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:April showers bring May flowers-GY75DW536.temp.mp4'
Deleting original file April showers bring May flowers-GY75DW536.fdash-it-IT-f2-v1-x3.mp4 (pass -k to keep)
Deleting original file April showers bring May flowers-GY75DW536.fdash-ru-RU-f1-a1-x3.m4a (pass -k to keep)
```
---

### Description of your *issue*, suggested solution and other information

While trying to download anime from Vrv, it keeps downloading seemingly random subtitles.

The example URL provided downloads subtitles in Italian for some reason.  The 2nd episode of the show downloads in Arabic.  Even though I set the subtitle language to en-US.

The show:  The Ancient Magus' Bride (crunchyroll via Vrv)
Episode tested: 1 and 2 (this example uses episode 1)

When I use `--write-sub`, it downloads the correct en-US.ass file, but at that point I have to manually burn the subtitles in.  

How can I either get it to download the correct subtitles, or use youtube-dl to burn in the subtitles it downloads separately (if I were to use `-k` flag to save the parts).

## **BONUS ISSUE**: 
When trying to download Overlord, specifically [this](https://vrv.co/watch/G649D79PY/Overlord:End-and-Beginning) episode, it doesn't download any subtitles at all, unless I specify `--write-sub`, at which point I need to be able to merge them.

**Comment by remitamine** [comment]
VRV provides for Crunchyroll content:
- original Japanese video.
- hard-subbed videos.
- separate `ass` subtitle files.

> The example URL provided downloads subtitles in Italian for some reason. The 2nd episode of the show downloads in Arabic. Even though I set the subtitle language to en-US.

you have specified the `--sub-lang` which only affect the downloaded subtitle, not the downloaded video.

> How can I either get it to download the correct subtitles

add `--write-sub` to your command and choose the original Japanese video to be downloaded by selecting a video format that contains `ja-JP` in it's `format_id`.

examples:
- download the original Japanese video with english subtitle:
`youtube-dl -f '(bestvideo+bestaudio/bestvideo)[format_id*=ja-JP]' --sub-lang 'en-US' --write-sub https://vrv.co/watch/GY75DW536/The-Ancient-Magus-Bride:April-showers-bring-May-flowers`
- download the hard-subbed english video:
`youtube-dl -f '(bestvideo+bestaudio/bestvideo)[format_id*=en-US]' https://vrv.co/watch/GY75DW536/The-Ancient-Magus-Bride:April-showers-bring-May-flowers`

**Comment by mjevans** [comment]
At least on https://www.crunchyroll.com/my-hero-academia/episode-59-whats-the-big-idea-775778 the listed format codes don't have a dash in that spot so the filter needs to be changed.

It would also be great if the example included multiple languages.

[crunchyroll] 775778: Downloading webpage                                                                                                                                                                 [14/1810]
[crunchyroll] 775778: Downloading jaJP m3u8 information
[crunchyroll] 775778: Downloading ptBR m3u8 information
[crunchyroll] 775778: Downloading enUS m3u8 information
[crunchyroll] 775778: Downloading esLA m3u8 information
[crunchyroll] 775778: Downloading media info
[info] Available formats for 775778:
format code      extension  resolution note
hls-jaJP-495-0   mp4        428x240    [jaJP]  495k , avc1.42c015, 23.974fps, mp4a.40.2
hls-jaJP-495-1   mp4        428x240    [jaJP]  495k , avc1.42c015, 23.974fps, mp4a.40.2
hls-jaJP-495-2   mp4        428x240    [jaJP]  495k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esLA-501-0   mp4        428x240    [jaJP]  501k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esLA-501-1   mp4        428x240    [jaJP]  501k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esLA-501-2   mp4        428x240    [jaJP]  501k , avc1.42c015, 23.974fps, mp4a.40.2
hls-ptBR-502-0   mp4        428x240    [jaJP]  502k , avc1.42c015, 23.974fps, mp4a.40.2
hls-ptBR-502-1   mp4        428x240    [jaJP]  502k , avc1.42c015, 23.974fps, mp4a.40.2
hls-ptBR-502-2   mp4        428x240    [jaJP]  502k , avc1.42c015, 23.974fps, mp4a.40.2
hls-enUS-502-0   mp4        428x240    [jaJP]  502k , avc1.42c015, 23.974fps, mp4a.40.2
hls-enUS-502-1   mp4        428x240    [jaJP]  502k , avc1.42c015, 23.974fps, mp4a.40.2
hls-enUS-502-2   mp4        428x240    [jaJP]  502k , avc1.42c015, 23.974fps, mp4a.40.2
hls-ptBR-697-0   mp4        640x360    [jaJP]  697k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-ptBR-697-1   mp4        640x360    [jaJP]  697k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-ptBR-697-2   mp4        640x360    [jaJP]  697k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-enUS-698-0   mp4        640x360    [jaJP]  698k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-enUS-698-1   mp4        640x360    [jaJP]  698k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-enUS-698-2   mp4        640x360    [jaJP]  698k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-jaJP-698-0   mp4        640x360    [jaJP]  698k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-jaJP-698-1   mp4        640x360    [jaJP]  698k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-jaJP-698-2   mp4        640x360    [jaJP]  698k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-esLA-699-0   mp4        640x360    [jaJP]  699k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-esLA-699-1   mp4        640x360    [jaJP]  699k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-esLA-699-2   mp4        640x360    [jaJP]  699k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-jaJP-1397-0  mp4        848x480    [jaJP] 1397k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-jaJP-1397-1  mp4        848x480    [jaJP] 1397k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-jaJP-1397-2  mp4        848x480    [jaJP] 1397k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-esLA-1437-0  mp4        848x480    [jaJP] 1437k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-esLA-1437-1  mp4        848x480    [jaJP] 1437k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-esLA-1437-2  mp4        848x480    [jaJP] 1437k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-enUS-1444-0  mp4        848x480    [jaJP] 1444k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-enUS-1444-1  mp4        848x480    [jaJP] 1444k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-enUS-1444-2  mp4        848x480    [jaJP] 1444k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-ptBR-1444-0  mp4        848x480    [jaJP] 1444k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-ptBR-1444-1  mp4        848x480    [jaJP] 1444k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-ptBR-1444-2  mp4        848x480    [jaJP] 1444k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-jaJP-2937-0  mp4        1280x720   [jaJP] 2937k , avc1.640028, 23.974fps, mp4a.40.2
hls-jaJP-2937-1  mp4        1280x720   [jaJP] 2937k , avc1.640028, 23.974fps, mp4a.40.2
hls-jaJP-2937-2  mp4        1280x720   [jaJP] 2937k , avc1.640028, 23.974fps, mp4a.40.2
hls-esLA-2973-0  mp4        1280x720   [jaJP] 2973k , avc1.640028, 23.974fps, mp4a.40.2
hls-esLA-2973-1  mp4        1280x720   [jaJP] 2973k , avc1.640028, 23.974fps, mp4a.40.2
hls-esLA-2973-2  mp4        1280x720   [jaJP] 2973k , avc1.640028, 23.974fps, mp4a.40.2
hls-enUS-2974-0  mp4        1280x720   [jaJP] 2974k , avc1.640028, 23.974fps, mp4a.40.2
hls-enUS-2974-1  mp4        1280x720   [jaJP] 2974k , avc1.640028, 23.974fps, mp4a.40.2
hls-ptBR-2985-0  mp4        1280x720   [jaJP] 2985k , avc1.640028, 23.974fps, mp4a.40.2
hls-ptBR-2985-1  mp4        1280x720   [jaJP] 2985k , avc1.640028, 23.974fps, mp4a.40.2
hls-ptBR-2985-2  mp4        1280x720   [jaJP] 2985k , avc1.640028, 23.974fps, mp4a.40.2
hls-enUS-5978-0  mp4        1920x1080  [jaJP] 5978k , avc1.640028, 23.974fps, mp4a.40.2
hls-enUS-5978-1  mp4        1920x1080  [jaJP] 5978k , avc1.640028, 23.974fps, mp4a.40.2
hls-enUS-5978-2  mp4        1920x1080  [jaJP] 5978k , avc1.640028, 23.974fps, mp4a.40.2
hls-jaJP-6014-0  mp4        1920x1080  [jaJP] 6014k , avc1.640028, 23.974fps, mp4a.40.2
hls-jaJP-6014-1  mp4        1920x1080  [jaJP] 6014k , avc1.640028, 23.974fps, mp4a.40.2
hls-jaJP-6014-2  mp4        1920x1080  [jaJP] 6014k , avc1.640028, 23.974fps, mp4a.40.2
hls-esLA-6016-0  mp4        1920x1080  [jaJP] 6016k , avc1.640028, 23.974fps, mp4a.40.2
hls-esLA-6016-1  mp4        1920x1080  [jaJP] 6016k , avc1.640028, 23.974fps, mp4a.40.2
hls-esLA-6016-2  mp4        1920x1080  [jaJP] 6016k , avc1.640028, 23.974fps, mp4a.40.2 (best)

I would also prefer the new behavior to NOT arbitrarily pick the last stream of a given quality, but to instead fail without downloading to force the user to deal with the error that requires human intervention.
