### ISSUE TITLE
ffmpeg merge error to make webm + m4a = mp4 no video

### ISSUE THREAD

**Issue by Wingzzzzz** [rg3/youtube-dl#16796]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.19**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\[user]\Desktop>youtube-dl.exe -v -f bestvideo+bestaudio --merge-output-fo
mat mp4 --ffmpeg-location C:\Users\[user]\Desktop\ffmpeg-4.0-win64-static\bin http
://www.youtube.com/watch?v=tocKgk76O1g
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo+bestaudio', '--merge-output-
ormat', 'mp4', '--ffmpeg-location', 'C:\\Users\\[user]\\Desktop\\ffmpeg-4.0-win64-
tatic\\bin', 'https://www.youtube.com/watch?v=tocKgk76O1g']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2018.06.19
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[youtube] tocKgk76O1g: Downloading webpage
[youtube] tocKgk76O1g: Downloading video info webpage
[debug] Invoking downloader on 'https://r6---sn-ibj-i3b6.googlevideo.com/videop
ayback?gcr=hk&id=o-AFkF4smYiwFySjOUeOK5NrhIew81YCzK7GA3Hg4FJd61&fexp=23709359&c
WEB&fvip=4&gir=yes&signature=A8F02A0741D0573DA1A4787EA309D591463F9722.4F7E5299C
73F2CC407E0D90F2C858DF4BE3C576&ip=113.254.142.139&requiressl=yes&initcwndbps=13
8750&itag=248&ms=au%2Crdu&mt=1529689401&aitags=133%2C134%2C135%2C136%2C137%2C16
%2C242%2C243%2C244%2C247%2C248%2C278&mv=m&ipbits=0&sparams=aitags%2Cclen%2Cdur%
Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmim
%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&keepalive=yes&mm=31%2C
9&mn=sn-ibj-i3b6%2Csn-i3b7kn76&ei=sjUtW-27CJKdqQHXjIGwBw&clen=457054162&expire=
529711122&mime=video%2Fwebm&pl=18&lmt=1529670873962231&source=youtube&dur=4323.
20&key=yt6&ratebypass=yes'
[download] Destination: 【1pm直播 Live】真係繼續貿戰！舜宇反向路演 + 小米$4444上
市的將來-tocKgk76O1g.f248.webm
[download] 100% of 435.88MiB in 00:48
[debug] Invoking downloader on 'https://r6---sn-ibj-i3b6.googlevideo.com/videop
ayback?gcr=hk&id=o-AFkF4smYiwFySjOUeOK5NrhIew81YCzK7GA3Hg4FJd61&fexp=23709359&c
WEB&fvip=4&gir=yes&signature=7DCE65EF12A873E7D7C35BCCAB326F76FEFDE21E.126A40A25
BBFC0D422FF4FEFD6457CB0E302995&ip=113.254.142.139&requiressl=yes&initcwndbps=13
8750&itag=140&ms=au%2Crdu&mt=1529689401&mv=m&ipbits=0&sparams=clen%2Cdur%2Cei%2
gcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm
2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&keepalive=yes&mm=31%2C29&mn=
n-ibj-i3b6%2Csn-i3b7kn76&ei=sjUtW-27CJKdqQHXjIGwBw&clen=68663613&expire=1529711
22&mime=audio%2Fmp4&pl=18&lmt=1529669830661680&source=youtube&dur=4323.207&key=
t6&ratebypass=yes'
[download] Destination: 【1pm直播 Live】真係繼續貿戰！舜宇反向路演 + 小米$4444上
市的將來-tocKgk76O1g.f140.m4a
[download] 100% of 65.48MiB in 00:06
[ffmpeg] Merging formats into "【1pm直播 Live】真係繼續貿戰！舜宇反向路演 + 小米
$4444上市的將來-tocKgk76O1g.mp4"
[debug] ffmpeg command line: "C:\Users\[user]\Desktop\ffmpeg-4.0-win64-static\bin\
fmpeg" -y -i "file:【1pm直播 Live】真係繼續貿戰！舜宇反向路演 + 小米$4444上市的
將來-tocKgk76O1g.f248.webm" -i "file:【1pm直播 Live】真係繼續貿戰！舜宇反向路演
+ 小米$4444上市的將來-tocKgk76O1g.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "
ile:【1pm直播 Live】真係繼續貿戰！舜宇反向路演 + 小米$4444上市的將來-tocKgk76O1
.temp.mp4"
Deleting original file 【1pm直播 Live】真係繼續貿戰！舜宇反向路演 + 小米$4444上
市的將來-tocKgk76O1g.f248.webm (pass -k to keep)
Deleting original file 【1pm直播 Live】真係繼續貿戰！舜宇反向路演 + 小米$4444上
市的將來-tocKgk76O1g.f140.m4a (pass -k to keep)
```

---

### Description of your *issue*, suggested solution and other information

Target: download best video with sound

First attempt: use no parameter download command with only URL
Result: only 720p (with sound) download while 1080p available 

Second attempt as above
Result: mp4 file with only sound

P.S. the video is originally a live stream.
Or ```--recode-video``` needed?

**Comment by dstftw** [comment]
webm+mp4 can't be merged into mp4 container. Don't touch options you have no idea about.
To download maximum quality you **don't need** to specify any options explicitly.

**Comment by Wingzzzzz** [comment]
Please be noticed that i have checked the manual to know default: best quality.
However, it is not working on the link i provided, ref: first attempt: only 720p downloaded while 1080 exists

**Comment by Hrxn** [comment]
It is working..

Trying the link with default youtube-dl settings here gave me format code `f248` for video, which is the correct one.

**Comment by Wingzzzzz** [comment]
@Hrxn 
may i know what platform are you on?

C:\Users\family\Desktop>youtube-dl.exe -v https://www.youtube.com/watch?v=tocKgk76O1g
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=tocKgk76O1g']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2018.06.19
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] tocKgk76O1g: Downloading webpage
[youtube] tocKgk76O1g: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r6---sn-ibj-i3b6.googlevideo.com/videoplayback?key=yt6&ratebypass=yes&pl=18&dur=4323.207&expire=1529780644&signature=D181DE262C76CF3C34B42EFA6E7958428C13A9FE.6A1D88EE153ED73FBF85A775E818DEC1BD4AF72F&ipbits=0&itag=22&mime=video%2Fmp4&requiressl=yes&mm=31%2C29&mn=sn-ibj-i3b6%2Csn-i3b7kn76&c=WEB&mt=1529758906&mv=m&ms=au%2Crdu&source=youtube&ip=113.254.142.139&sparams=dur%2Cei%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&fexp=23709359&gcr=hk&initcwndbps=1183750&id=o-ANb3mXEkBntAWkR6iGxJMi_2ebEVD1G3GyfXcOztb9Lo&ei=REUuW_yfBYyYgAPjqIfwDw&lmt=1529670085309855&fvip=4'
[download] Destination: 【1pm直播 Live】真係繼續貿戰！舜宇反向路演 + 小米$4444上市的將來-tocKgk76O1g.mp4

Using 2018.06.19 version

**Comment by Hrxn** [comment]
Windows 10..

This is the problem:
> [debug] exe versions: none

You need FFmpeg, from here, for example: https://ffmpeg.zeranoe.com/builds/

And put the FFmpeg binaries somewhere into your PATH or next to youtube-dl.exe.

**Comment by Wingzzzzz** [comment]
thanks.
For others, if not detecting ffmpeg, youtube-dl automatically download "highest" quality video which may be 720 instead of 1080.
