### ISSUE TITLE
Download from Udemy did not work

### ISSUE THREAD

**Issue by ds2k5** [rg3/youtube-dl#16791]
Hi,
wanna download Udemy Video course.

youtube-dl --version
2018.06.19

Command i tryed:

youtube-dl -v -u name@domain.tld -p password -o "./%(playlist)s/%(chapter_number)s-%(chapter)s/%(autonumber)03d-%(title)s.%(ext)s" "https://www.udemy.com/corsename/learn/v4/content"

or
youtube-dl -v -u name@domain.tld -p password "https://www.udemy.com/corsename/learn/v4/content"

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', '--write-sub', '--cookies', './udemy-cookies.txt', '-f', 'best', '-o', '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s', 'https://www.udemy.com/..../learn/v4/content']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.19
[debug] Python version 3.6.5 (CPython) - Linux-4.14.48-2-MANJARO-x86_64-with-arch-Manjaro-Linux
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by <HTTPError 403: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "./youtube-dl/youtube_dl/extractor/common.py", line 598, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

If I login with the credentials on the Website: udemy.com login works

How to fix this ?

**Comment by dstftw** [comment]
1. Do not mix account credentials and cookies authentication options in single command.
2. For any work on the issue you must provide account credentials.

**Comment by chovy** [comment]
I'm am getting this error too.

**Comment by chovy** [comment]
```
[download] Downloading video 34 of 233
[udemy] 9020464: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by ds2k5** [comment]
hi choxy,
here a workaround: https://github.com/r0oth3x49/udemy-dl
