### ISSUE TITLE
Cron woes

### ISSUE THREAD

**Issue by paul-bsc** [rg3/youtube-dl#16801]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.19*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

This should be a simple one. I have written a simple bash script that downloads from URLs in a file. If I run the script from the terminal it works as expected. If I run it as a cron job then it throws the Signature Extraction Failed Error. Any help would be really appreciated.

**Comment by dstftw** [comment]
Most likely you have multiple instances of youtube-dl installed and one found from `PATH` by cron is outdated.

**Comment by paul-bsc** [comment]
Thanks.. I think this has something to do with the way Python versions are managed on my PC. Adding a pip update to the script sorted this out. Thanks.

**Comment by Freezl** [comment]
Hi!
I am trying to implement downloading video and audio in cron. I'm do it on the CentOS 7
> youtube-dl --version
2018.07.21

I created bash script
`#!/bin/bash`
`/usr/bin/youtube-dl -wi --yes-playlist --extract-audio -f 'bestaudio[tbr<=127]' --audio-format vorbis -o /media/Youtube/Audio/"%(uploader)s_%(title)s.%(ext)s" --dateafter now-1day --playlist-end 30 https://www.youtube.com/feed/subscriptions >> /var/log/youtube-dl.log
`

Added task to the crontab:
`crontab -u ftp -l`
`00   7,17   *   *   *   /opt/yoursub_a.sh`

And get audio files without Russian letters in the title
`ll /media/Youtube/Audio/`
`-rwxr--r-- 1 ftp www-data 10355025 Jul 26 15:49 ___15000.ogg
-rwxr--r-- 1 ftp www-data 47733057 Jul 25 22:12 Dmitry_Puchkov_1946.ogg
-rwxr--r-- 1 ftp www-data  9344667 Jul 26 14:26 __F_m_n.ogg
-rwxr--r-- 1 ftp www-data  2088960 Jul 26 16:39 FORUMHOUSE__FORUMHOUSE.webm.part
-rwxr--r-- 1 ftp www-data  8791308 Jul 26 15:26 ___.ogg
`

> [youtube:subscriptions] Downloading login page
[youtube:subscriptions] Looking up account info
[youtube:subscriptions] Logging in
[youtube:subscriptions] Checking cookie
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Downloading 30 videos
[download] Downloading video 1 of 30
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] uYnzUha0Bmw: Downloading webpage
[youtube] uYnzUha0Bmw: Downloading video info webpage
[download] Destination: /media/Youtube/Audio/___.webm
[download] 100% of 10.76MiB in 00:0155MiB/s ETA 00:00known ETA
[ffmpeg] Destination: /media/Youtube/Audio/___.ogg
Deleting original file /media/Youtube/Audio/___.webm (pass -k to keep)
[download] Downloading video 2 of 30
[youtube] 9Q_VqHFnthk: Downloading webpage
[youtube] 9Q_VqHFnthk: Downloading video info webpage
[download] Destination: /media/Youtube/Audio/___15000.webm
[download] 100% of 10.43MiB in 00:0121MiB/s ETA 00:00known ETA
[ffmpeg] Destination: /media/Youtube/Audio/___15000.ogg
Deleting original file /media/Youtube/Audio/___15000.webm (pass -k to keep)
[download] Downloading video 3 of 30
[youtube] 9hDv0CvbcZY: Downloading webpage
[youtube] 9hDv0CvbcZY: Downloading video info webpage
[download] Destination: /media/Youtube/Audio/___.webm
[download] 100% of 8.55MiB in 00:0110MiB/s ETA 00:004
[ffmpeg] Destination: /media/Youtube/Audio/___.ogg
Deleting original file /media/Youtube/Audio/___.webm (pass -k to keep)
[download] Downloading video 4 of 30
[youtube] _7czZyvIM7U: Downloading webpage
[youtube] _7czZyvIM7U: Downloading video info webpage
[download] Destination: /media/Youtube/Audio/__F_m_n.webm
[download] 100% of 8.66MiB in 00:0113MiB/s ETA 00:004
[ffmpeg] Destination: /media/Youtube/Audio/__F_m_n.ogg
Deleting original file /media/Youtube/Audio/__F_m_n.webm (pass -k to keep)
[download] Downloading video 5 of 30
[youtube] _gtF4l6s5Cg: Downloading webpage
[youtube] _gtF4l6s5Cg: Downloading video info webpage
[download] Destination: /media/Youtube/Audio/Dmitry_Puchkov_1946.webm
[download] 100% of 47.10MiB in 00:0506MiB/s ETA 00:00known ETA
[ffmpeg] Destination: /media/Youtube/Audio/Dmitry_Puchkov_1946.ogg
Deleting original file /media/Youtube/Audio/Dmitry_Puchkov_1946.webm (pass -k to keep)

If started script in the console
`sudo -u ftp /opt/yoursub_a.sh`
This worked fine!
`-rwxr--r-- 1 ftp www-data 47733057 Jul 25 22:12 Dmitry Puchkov_Клим Жуков о ядерных испытаниях 1946 года на атолле Бикини.ogg`
`-rwxr--r-- 1 ftp www-data 47765858 Jul 25 16:57 Dmitry Puchkov_Павел Перец про покушение на Константина Победоносцева.ogg`
`-rwxr--r-- 1 ftp www-data  4583864 Jul 25 22:30 FORUMHOUSE_Изготавливаем тротуарную плитку самостоятельно _ FORUMHOUSE.ogg`
`-rwxr--r-- 1 ftp www-data  7400611 Jul 26 13:01 FORUMHOUSE_Уютный дом для небольшой семьи. Своими руками _ FORUMHOUSE.ogg
`
