### ISSUE TITLE
Swedish public service SVT's news section (incl workaround)

### ISSUE THREAD

**Issue by b9AcE** [rg3/youtube-dl#16802]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.19*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [z] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v -- 'https://www.svt.se/nyheter/inrikes/ebba-busch-thor-kd-har-delvis-ratt-om-no-go-zoner'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--', u'https://www.svt.se/nyheter/inrikes/ebba-busch-thor-kd-har-delvis-ratt-om-no-go-zoner']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.19
[debug] Python version 2.7.13 (CPython) - Linux-4.15.11-feral-x86_64-with-debian-9.4
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1
[debug] Proxy map: {}
[generic] ebba-busch-thor-kd-har-delvis-ratt-om-no-go-zoner: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ebba-busch-thor-kd-har-delvis-ratt-om-no-go-zoner: Downloading webpage
[generic] ebba-busch-thor-kd-har-delvis-ratt-om-no-go-zoner: Extracting information
ERROR: Unsupported URL: https://www.svt.se/nyheter/inrikes/ebba-busch-thor-kd-har-delvis-ratt-om-no-go-zoner
Traceback (most recent call last):
  File "/media/sdb1/b9ace/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2308, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/media/sdb1/b9ace/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/media/sdb1/b9ace/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 20, column 27
Traceback (most recent call last):
  File "/media/sdb1/b9ace/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/media/sdb1/b9ace/bin/youtube-dl/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/media/sdb1/b9ace/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3263, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.svt.se/nyheter/inrikes/ebba-busch-thor-kd-har-delvis-ratt-om-no-go-zoner
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.svt.se/nyheter/inrikes/ebba-busch-thor-kd-har-delvis-ratt-om-no-go-zoner

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Near no videos from news section of SVT, Sweden's public service TV, work.
If one downloads any video page's source and searches for the first instance of "nojs" (in the example, "https://www.svt.se/videoplayer-embed/nojs/18089571") then download that source and look for the frst instance of "json=" in that file
(in the example "json=%7B%22video%22%3A%7B%22videoReferences%22%3A%5B%7B%22url%22%3A%22https%3A%2F%2Fsvtklipp6a-vh.akamaihd.net%2Fi%2Fworld%2Fopen%2F20180521%2FRW-2018-0521-VOD-BUSCHTHORFK%2FRW-2018-0521-VOD-BUSCHTHORFK_%2C988%2C240%2C348%2C456%2C636%2C1680%2C2796%2C.mp4.csmil%2Fmaster.m3u8%3Falt%3Dhttps%253A%252F%252Fswitcher.cdn.svt.se%252FRW-2018-0521-VOD-BUSCHTHORFK_bde02940.m3u8%22%2C%22playerType%22%3A%22flash%22%7D%5D%2C%22subtitleReferences%22%3A%5B%7B%7D%5D%2C%22position%22%3A0%7D%2C%22statistics%22%3A%7B%22client%22%3A%22nojs%22%2C%22mmsClientNr%22%3A%221001001%22%2C%22programId%22%3A%2218089571%22%2C%22statisticsUrl%22%3A%22%2F%2Fld.svt.se%2Fsvt%2Fsvt%2Fs%3Fnojs.rapport.hor-ebba-busch-thors-pastaende-om-sa-kallade-no-go-zoner-i-svts-tal-till-nationen.%22%2C%22title%22%3A%22H%C3%B6r%20Ebba%20Busch%20Thors%20p%C3%A5st%C3%A5ende%20om%20%E2%80%9Ds%C3%A5%20kallade%20no-go-zoner%E2%80%9D%20i%20SVT%3As%20Tal%20till%20nationen.%22%2C%22folderStructure%22%3A%22Rapport%22%7D%2C%22context%22%3A%7B%7D%7D")
then that string can be taken to a URL decoder, like https://meyerweb.com/eric/tools/dencoder/ and once decoded just copy from the "https" to the first "m3u8" (in the example "https://svtklipp6a-vh.akamaihd.net/i/world/open/20180521/RW-2018-0521-VOD-BUSCHTHORFK/RW-2018-0521-VOD-BUSCHTHORFK_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8") then that URL is in fact downloadable using youtube-dl.
The process described above was verified to be working with the example URL using IP-addresses registered as located in Sweden, USA and U.K. with the exact same result described above.
The same workaround process described above has worked for literally hundreds of SVT news videos over a few years, out of which none worked when providing the original article's URL.

**Comment by MrHatman** [comment]
Try svtplay-dl.

**Comment by b9AcE** [comment]
I did and it does not work for SVT's news videos either (but does work for SVT Play, which is a different part of SVT).
