### ISSUE TITLE
Any Bilibili videos more than 10mins are downloaded as multiple files

### ISSUE THREAD

**Issue by ZelunZhang** [rg3/youtube-dl#16804]
Hi,
I am using the latest version of youtube-dl.
However, i noticed that any videos that are more than 10mins long on Bilibili is downloaded as multiple filed. 
Tried the following options:
--buffer-size 1G
--http-chunk-size 1G

Still no luck.
Could you please have a look and let me know how to download long Bilibili videos to a single video file.

Command i used:
youtube-dl -f 1 -o "%(title)s-%(id)s.%(ext)s" --write-description https://www.bilibili.com/video/av10860038

**Comment by dstftw** [comment]
You can't download as a single file cause it's not served as single file.

**Comment by ZelunZhang** [comment]
Hi,
it looks to me that the origin website is serving the video as one file. As in the UI download website http://www.urlgot.com/en_US/, when the url is parsed, it shows it as one single file, like the following.

![image](https://user-images.githubusercontent.com/14319738/41812280-07c65a9a-7718-11e8-9699-bee9da27bba0.png)

And the file can be downloaded as a single file.

**Comment by ZelunZhang** [comment]
Could you please have another look of the issue?

**Comment by dstftw** [comment]
These are not original files. All linked to d*.urlgot.com.

**Comment by User486375** [comment]
Why couldn't youtube-dl auotmaticaly combine the parts using ffmpeg if present? Or at least have a flag for it.
