### ISSUE TITLE
When using json-dump, Certain Vimeo Videos only have segments and not full mp4 urls

### ISSUE THREAD

**Issue by harryhope** [rg3/youtube-dl#16822]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When I run youtube-dl with `-j` on an older vimeo video, the url returned as part of a response is an mp4 with an mp4 file extension.
**Example**
```
youtube-dl -j https://vimeo.com/71501596
```

When I run the command on a newer video however, I get `http_dash_segments`, and the url is only to a manifest and not an mp4 file.
**Example**
```
youtube-dl -j https://vimeo.com/276738707
```

My question is: Is it possible to have youtube dl return an mp4 link on the second example, or are dash_segments the only thing I'm able to get back?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#format-selection
