### ISSUE TITLE
Support request: How to scrape jwplayer video from script

### ISSUE THREAD

**Issue by alrii** [rg3/youtube-dl#16832]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.06.25
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I need to fetch the video source from script. It has 3 eval function. decode_packed_codes(data) used to work but not all the time.

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js"</script>
<script src="jwplayer/jwplayer.js"></script>
<script>
	var _0x344f=['input','keydown','keyCode','ctrlKey','contextmenu','preventDefault','string','while\x20(true)\x20{}','counter','length','constructor','debu','gger','call','action','stateObject','apply','function\x20*\x5c(\x20*\x5c)','\x5c+\x5c+\x20*(?:_0x(?:[a-f0-9]){4,6}|(?:\x5cb|\x5cd)[a-z0-9]{1,4}(?:\x5cb|\x5cd))','init','chain','test'];(function(_0x9131c0,_0x11dedb){var _0x17d64a=function(_0x2bba49){while(--_0x2bba49){_0x9131c0['push'](_0x9131c0['shift']());}};_0x17d64a(++_0x11dedb);}(_0x344f,0x1de));var _0x377a=function(_0x3bcb57,_0x1b984f){_0x3bcb57=_0x3bcb57-0x0;var _0xf37ec9=_0x344f[_0x3bcb57];return _0xf37ec9;};var _0x21b310=function(){var _0x149de6=!![];return function(_0x28ae48,_0x5a5193){var _0x1284d6=_0x149de6?function(){if(_0x5a5193){var _0x22a15f=_0x5a5193[_0x377a('0x0')](_0x28ae48,arguments);_0x5a5193=null;return _0x22a15f;}}:function(){};_0x149de6=![];return _0x1284d6;};}();(function(){_0x21b310(this,function(){var _0x1a7532=new RegExp(_0x377a('0x1'));var _0x3dd2aa=new RegExp(_0x377a('0x2'),'i');var _0x5aa1fc=_0x547474(_0x377a('0x3'));if(!_0x1a7532['test'](_0x5aa1fc+_0x377a('0x4'))||!_0x3dd2aa[_0x377a('0x5')](_0x5aa1fc+_0x377a('0x6'))){_0x5aa1fc('0');}else{_0x547474();}})();}());$(window)['on'](_0x377a('0x7'),function(_0x175b13){if(_0x175b13[_0x377a('0x8')]==0x7b){return![];}else if(_0x175b13['ctrlKey']&&_0x175b13['shiftKey']&&_0x175b13[_0x377a('0x8')]==0x49){return![];}else if(_0x175b13[_0x377a('0x9')]&&_0x175b13[_0x377a('0x8')]==0x49){return![];}else if(_0x175b13[_0x377a('0x9')]&&_0x175b13[_0x377a('0x8')]==0x55){return![];}});setInterval(function(){_0x547474();},0xfa0);$(document)['on'](_0x377a('0xa'),function(_0x156c04){_0x156c04[_0x377a('0xb')]();});function _0x547474(_0x598e8a){function _0x34f211(_0x45a376){if(typeof _0x45a376===_0x377a('0xc')){return function(_0x5ca231){}['constructor'](_0x377a('0xd'))[_0x377a('0x0')](_0x377a('0xe'));}else{if((''+_0x45a376/_0x45a376)[_0x377a('0xf')]!==0x1||_0x45a376%0x14===0x0){(function(){return!![];}[_0x377a('0x10')](_0x377a('0x11')+_0x377a('0x12'))[_0x377a('0x13')](_0x377a('0x14')));}else{(function(){return![];}[_0x377a('0x10')](_0x377a('0x11')+_0x377a('0x12'))[_0x377a('0x0')](_0x377a('0x15')));}}_0x34f211(++_0x45a376);}try{if(_0x598e8a){return _0x34f211;}else{_0x34f211(0x0);}}catch(_0x3c15d2){}}

	eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('b=\'a.9?8=7-6-5-4-3-2-1-0,\';',12,12,'oCOjHDvqPdbK9teUsLt0VvrBxAvtYuGAv0MpQgZA87Psliw5__fEv4gv5VZ8LhJJWfDfJMIB3qf4AMeAwBrMHRpRJgjik_lIGZuWk|1yb_cTum6jkS|eZvUHk|u_Q1dD4SqY_Vio5koq6C2OqzEK_aDdeCfjMpvEtvpIhGHrhyMSlmUQyADUEPauFAnr8u0_2qtpx26zgAF4vw5QqpYmbuKZ8FJojKXgTHW_lOo5TKqvwe3vybpJco976QpUg7cccN735WItqLh6f7uH3kObMlKpigg5vhIYIsoYwdLT7HxpDb8tsOw7nc0h9zNCdPg7kZLYY6UftSqKA4ZnqbwqKGAA9ThT8gqPmDxiExd|ooP2F91whu1Yvc1u|T7TFz1M2A7QMHskn6QeBEYzm4mNNqyCvxz5SoUIqtcb7rc0cfQXlH_on5pTct0L3jfe5kvqGrqiYb2n5VihSeEf7le5SUbrZ_A|An9yek|XACFCE8jS9QYH9h_IOcCHjgHYteHDN0U6woVwg3aFoj8pQJOjQ8039Jmg65bzZN0ACf8hRDV|data|php|m3y|purl'.split('|'),0,{}))

eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('1=n(\'4\');1.5({6:\'7+8==\',a:{},b:\'0.2\',c:\'3://0.2\',f:\'g%\',h:\'i:9\',j:\'k\',l:\'m\',e:d});',24,24,'lumangdrama|player|com|http|video|setup|key|tjQq7CNG7oULq6qy|s5IUmOtg0JusfzoTjBSTQ||cast|abouttext|aboutlink|purl|file|width|100|aspectratio|16|stretching|exactfit|type|hls|jwplayer'.split('|'),0,{}))

	eval(function(p,a,c,k,e,r){e=function(c){return c.toString(a)};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('6 1(){7 2=3,d=8,e=d.9,g=d.a(\'b\')[0],4=2.c||e.5||g.5;f.1(\'h%\',4)}1();3.i=1;',19,19,'|resize|w|window|y|clientHeight|function|var|document|documentElement|getElementsByTagName|body|innerHeight|||player||100|onresize'.split('|'),0,{}))
    </script>

**Comment by dstftw** [comment]
Obviously you have to write your own decoder or fix existing.
