### ISSUE TITLE
How to download multiple playlists with multiple links and make folders for each playlist ?

### ISSUE THREAD

**Issue by Invisible786** [rg3/youtube-dl#16833]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [x] Other

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I want to know if there is syntax with which we can download  **MULTIPLE PLAYLISTS** with their links/url and **MAKE DIRECTORY/FOLDER WITH THE PLAYLIST TITLE FOR EACH PLAYLIST** ?
FOR e.g. if we input 5 Playlist links ,it should make 5 folders with the playlist title at "D:/Download/... " this location and download videos at their specific folder, 
for Playlist 1 - "D:\Download\Playlist_1_Title"  and this folder should contain videos of playlist 1 i.e. Playlist_Video_1, Playlist_Video_2 and so on
For Playlist 2 - "D:\Download\Playlist_2_Title" and this folder should contain videos of playlist 2
For Playlist 3 - "D:\Download\Playlist_3_Title" and this folder should contain videos of playlist 3
till playlist 5

### **If it's there than please share the syntax I Couldn't find it and i am new to youtube-dl.  So ,I don't know how to create our own syntax**

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#output-template

**Comment by Invisible786** [comment]
i dont understand

**Comment by Orion751** [comment]
@Invisible786 I think you could try modifying this example below, which came from the link (specifically, https://github.com/rg3/youtube-dl#output-template-examples):
```
# Download YouTube playlist videos in separate directory indexed by video order in a playlist
$ youtube-dl -o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re
```
Not sure if it matters, but I've noticed that your examples include "D:\\", which suggests that you're using Windows, so you may want to try using '\' in place of '/' in the example.

Let me know if you need any more help.
