### ISSUE TITLE
Can't read utf-8 characters from stdin (Windows only)

### ISSUE THREAD

**Issue by TheBITLINK** [rg3/youtube-dl#16857]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--dump-json', '--default-search=ytsearch', '-i', '--format=best', '-a', '-']
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\__init__.py", line 472, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\__init__.py", line 93, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\utils.py", line 2116, in read_batch_urls
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\utils.py", line 2116, in <listcomp>
  File "C:\Python\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1: character maps to <undefined>
```
---

### Description of your *issue*, suggested solution and other information

For some reason, youtube-dl defaults to the `cp1252` encoding when reading from stdin in Windows, if there's an utf-8 character present, it crashes like above. I've tried to override this using both the `--encoding` parameter and the `PYTHONIOENCODING` environment variable with no success.

**Comment by Hrxn** [comment]
When running youtube-dl from `CMD.exe`?

**Comment by TheBITLINK** [comment]
I'm running it from a Node.js app using [child_process.spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options)

**Comment by dstftw** [comment]
Post the data written to `stdin`.

**Comment by TheBITLINK** [comment]
Try with `إثس`

**Comment by dstftw** [comment]
Still no crash.

**Comment by Ensjam** [comment]
Same issue

**Comment by Ensjam** [comment]
Try with "ماجد العيسى فري ستايل"
