### ISSUE TITLE
Cannot download Bilibili videos

### ISSUE THREAD

**Issue by anphetamina** [rg3/youtube-dl#16859]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```

C:\Users\Antonio>youtube-dl -v https://www.bilibili.com/video/av25723607
[debug] System config: []
[debug] User config: ['-o', 'D:/Antonio/Downloads/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bilibili.com/video/av25723607']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.06.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[BiliBili] 25723607: Downloading webpage
[BiliBili] 25723607: Downloading video info page
[download] Downloading playlist: 【轩子助眠减压】镊子和史莱姆~戴上耳机
[BiliBili] playlist 【轩子助眠减压】镊子和史莱姆~戴上耳机: Collected 5 video ids (downloading 5 of them)
[download] Downloading video 1 of 5
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/76/00/43900076/43900076-1-80.flv?um_deadline=1530278866&platform=pc&rate=421600&oi=2182678639&um_sign=e3d67a1293b3ec320d77013605b9e17f&gen=playurl&os=cos&trid=6bf4f66f0d394246a0ec6c596a214eca'
[download] Destination: D:\Antonio\Downloads\【轩子助眠减压】镊子和史莱姆~戴上耳机.flv
[download] 100% of 85.15MiB in 03:15
[download] Downloading video 2 of 5
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/76/00/43900076/43900076-2-80.flv?um_deadline=1530278866&platform=pc&rate=459000&oi=2182678639&um_sign=d10217fa1acf92ca9278e9d51df03a2f&gen=playurl&os=cos&trid=6bf4f66f0d394246a0ec6c596a214eca'
[download] D:\Antonio\Downloads\【轩子助眠减压】镊子和史莱姆~戴上耳机.flv has already been downloaded
[download] 100% of 85.15MiB
[download] Downloading video 3 of 5
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/76/00/43900076/43900076-3-80.flv?um_deadline=1530278866&platform=pc&rate=442000&oi=2182678639&um_sign=4a2297072d20ffbf4c24e37cf718f04e&gen=playurl&os=cos&trid=6bf4f66f0d394246a0ec6c596a214eca'
[download] D:\Antonio\Downloads\【轩子助眠减压】镊子和史莱姆~戴上耳机.flv has already been downloaded
[download] 100% of 85.15MiB
[download] Downloading video 4 of 5
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/76/00/43900076/43900076-4-80.flv?um_deadline=1530278866&platform=pc&rate=528700&oi=2182678639&um_sign=e023082770cbcdf241ae6d205a4502da&gen=playurl&os=cos&trid=6bf4f66f0d394246a0ec6c596a214eca'
[download] D:\Antonio\Downloads\【轩子助眠减压】镊子和史莱姆~戴上耳机.flv has already been downloaded
[download] 100% of 85.15MiB
[download] Downloading video 5 of 5
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/76/00/43900076/43900076-5-80.flv?um_deadline=1530278866&platform=pc&rate=484500&oi=2182678639&um_sign=164ccb6580839f5d31c1de5ad2425120&gen=playurl&os=cos&trid=6bf4f66f0d394246a0ec6c596a214eca'
[download] D:\Antonio\Downloads\【轩子助眠减压】镊子和史莱姆~戴上耳机.flv has already been downloaded
[download] 100% of 85.15MiB
[download] Finished downloading playlist: 【轩子助眠减压】镊子和史莱姆~戴上耳机

```

### Description of your *issue*, suggested solution and other information

Cannot download all 5 videos from this url: https://www.bilibili.com/video/av25723607.
I've tried using ``-F`` and ``--referer`` commands in combination with adding ``index_1.html`` at the end of the video link but it doesn't work.

**Comment by dstftw** [comment]
Your output template does not provide filename uniqueness as clearly stated in the log.

**Comment by anphetamina** [comment]
What do you mean? I got only one video file from that.

**Comment by dstftw** [comment]
Once you touch `-o` it's your responsibility to provide output template thal will produce unique filenames for each file. Yours fails to do so. Don't touch it if you have no idea of what are you doing.
