### ISSUE TITLE
Video formats

### ISSUE THREAD

**Issue by IoanPaleru** [rg3/youtube-dl#16865]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

Hi, I just wanted to thank you for helping me with my previous posts at "https://github.com/rg3/youtube-dl/issues/16861", "https://github.com/rg3/youtube-dl/issues/16862", and "https://github.com/rg3/youtube-dl/issues/16863", by telling me I could use "best[ext=mp4][height<=<HEIGHT HERE>]", but it seems the posts were locked so I couldn't comment on them.

Is there a way to get youtube-dl to save an 854x468 (480p) video with audio as an mp4 instead of an mkv file? Thanks.

**Comment by dstftw** [comment]
I've already answered that: select formats with compatible `ext` and merge with `+`.

**Comment by IoanPaleru** [comment]
If I download the 480p video and audio streams for this video "https://www.youtube.com/watch?v=Zi_XLOBDo_Y" separately with youtube-dl, I can combine them together easily with ffmpeg using "ffmpeg -i audio.aac -i video.mp4 -c:v copy -c:a copy -preset superfast output.mp4", but is there a way to get youtube-dl to download that video and combine the files automatically? Thanks.

**Comment by IoanPaleru** [comment]
It seems you can use --format 140+135 to download and convert a 640x480 video with m4a as mp4, but is there any way for youtube-dl to automatically find the 480p video and audio streams without having to specify the formats? Thanks.
