### ISSUE TITLE
[bilibili]how can i download video on page2?

### ISSUE THREAD

**Issue by kesdoputr** [rg3/youtube-dl#16870]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

I try to use youtube-dl to download a video on bilibili like https://www.bilibili.com/video/av18178195

The video have 2 pages, but when i type **youtube-dl -f 1 https://www.bilibili.com/video/av18178195**
i just get the video on page1, how can i get video on page2?
I have see this page https://github.com/rg3/youtube-dl/pull/16354
but i use 
**youtube-dl -f 1 https://www.bilibili.com/video/av18178195/index_2.html** or 
**youtube-dl -f 1 https://www.bilibili.com/video/av18178195/?p=2**

It will get the same video on page1
How can i solve this problem? Thank you.
Is this problem fixed? I use the standalone exe version.

**Comment by lss4** [comment]
#16354 (need to also apply the regex fix 61cb66830f5097b528aab381eb6b343a89f73cbc) doesn't appear to work. It still could only get the videos from the first page.

**Comment by yonhee137** [comment]
when video-download.co was still able to download bilibili, this is what I used to get the page 2
/index_1.html#page=1

I havent's tried using youtube-dl for bilibili, does it really work now?

**Comment by kesdoputr** [comment]
@yonhee137 
I try to use youtube-dl -f 1 https://www.bilibili.com/video/av18178195/index_2.html#page=2, but it seems still download files one page 1
Any way, hhank you for your replay :)

**Comment by miklast** [comment]
the fix that atxalex posted in #16354  will correct the issue for you. I am currently using it with 100% success.

**Comment by kesdoputr** [comment]
@miklast 
Thanks for your information, but when i use the bilibili.py, i still can't download page2, and when i want to download page1 it says video is hidden.

Test url：https://www.bilibili.com/video/av18178195
The video have 2part (I test with just url, /index_1.html, /index_2.html, the result is the same)

●by original bilibili.py
```
C:\Users\k7\Desktop>youtube-dl -F https://www.bilibili.com/video/av18178195
[BiliBili] 18178195: Downloading webpage
[BiliBili] 18178195: Downloading video info page
[download] Downloading playlist: [中字] 斉藤朱夏 沼津一日警察署長 活動完整片段
[BiliBili] playlist [中字] 斉藤朱夏 沼津一日警察署長 活動完整片段: Collected 3
ideo ids (downloading 3 of them)
[download] Downloading video 1 of 3
[info] Available formats for 18178195_part1:
format code  extension  resolution note
0            flv        unknown
1            flv        unknown    108.34MiB (best)
[download] Downloading video 2 of 3
[info] Available formats for 18178195_part2:
format code  extension  resolution note
0            flv        unknown
1            flv        unknown    56.90MiB (best)
[download] Downloading video 3 of 3
[info] Available formats for 18178195_part3:
format code  extension  resolution note
0            flv        unknown
1            flv        unknown    126.81MiB (best)
[download] Finished downloading playlist: [中字] 斉藤朱夏 沼津一日警察署長 活動
完整片段
```
●by modified bilibili.py from https://github.com/rg3/youtube-dl/pull/16354
```
C:\Users\k7\Desktop>youtube-dl -F https://www.bilibili.com/video/av18178195
[BiliBili] 18178195: Downloading webpage
[BiliBili] 18178195: Downloading video info page
[BiliBili] 18178195: Downloading video info page
ERROR: BiliBili said: Video is hidden.
```
Or i have some wrong? I just get the bilibili.py from https://github.com/rg3/youtube-dl/pull/16354
and replace the original one.

**Comment by lss4** [comment]
@miklast How to correctly apply that proposed fix from the current version? This line (from atxalex's proposed fix):

mobj[e[1]] = e[0]

doesn't look right as I'm getting: "TypeError: '_sre.SRE_Match' object does not support item assignment".

**Comment by Jaqen00** [comment]
@kesdoputr 
I find that I can download page2 and page3,but when I download page1 it says video is hidden,
and file in page 2 that I download is actually the content in page 1.
So I read the code .

In line 134: 'cid = mobj[int(page)-1] or \' ,I replace the line to 'cid = mobj[int(page)] or \'

I don't know why ,but It actually worked for me .

**Comment by miklast** [comment]
Sorry i didnt come back to this sooner. 

Im not going to lie, im not the best with github/recompiling/python, so i had a friend help me out. Here's what mine looks like from line 132-141:
`if 'anime/' not in url:

            ll = re.findall(r'cid(?:["\']:|=)(\d+),["\']page(?:["\']:|=)(\d+)', webpage)

            for e in ll:

             mobj[e[1]] = e[0]

            cid =  mobj[page] or \

                compat_parse_qs(self._search_regex([

                    r'EmbedPlayer\([^)]+,\s*"([^"]+)"\)',

                    r'EmbedPlayer\([^)]+,\s*\\"([^"]+)\\"\)',

                    r'<iframe[^>]+src="https://secure\.bilibili\.com/secure,([^"]+)"'],

                    webpage, 'player parameters'))['cid'][0]`

Hope this helps. Ill try to respond quicker if theres any other issues.

**Comment by Jaqen00** [comment]
@miklast 谢谢老哥！

**Comment by kesdoputr** [comment]
@miklast 
Oh thanks, the py you provide works.

**Comment by ohperhaps** [comment]
@miklast Thanks sincerely!

**Comment by melody4eye** [comment]
@miklast can you tell me how to put the new bilibili.py in that exe version. I am totally new to this. Thank you

**Comment by melody4eye** [comment]
@miklast can you tell me how to put the new bilibili.py in that exe version. I am totally new to this. Thank you

**Comment by vinqin** [comment]
It works, thx~

**Comment by vinqin** [comment]
@miklast It works, thanks a lot.

**Comment by lss4** [comment]
I can confirm the version from jasonszang works. It downloaded the video I wanted to download correctly... Hope this can be merged to mainstream.

Also, I do wish if it's also possible to download entire playlist from bilibili. I know it's already possible to do so with YouTube.

**Comment by ilovejs** [comment]
[BiliBili] 17843872: Downloading webpage
ERROR: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):

**Comment by awei78** [comment]
Same as #20555
Please visit: http://www.cr-soft.net/archives/how-to-download-bilibili-video.html
