### ISSUE TITLE
[Feature request] Network retry, with configurability

### ISSUE THREAD

**Issue by vlakoff** [rg3/youtube-dl#16883]
I just ran some large youtube-dl scripts, and noticed a few videos were missing finally.

This was probably due to intermittent network downtimes, and apparently youtube-dl doesn't do any network retry at all (I may be wrong).

Thus, I suggest adding an option named for example `--network-retry`, related to `--socket-timeout`. The default would be 0 to keep the current youtube-dl behavior, and I could configure it to something like 5.

**Comment by dstftw** [comment]
```
-R, --retries RETRIES            Number of retries (default is 10), or
                                 "infinite".
--fragment-retries RETRIES       Number of retries for a fragment (default
                                 is 10), or "infinite" (DASH, hlsnative and
                                 ISM)
```
