### ISSUE TITLE
option to list video URLs in playlist; want to parallelize

### ISSUE THREAD

**Issue by fsiler** [rg3/youtube-dl#16881]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Can youtube-dl provide simply a list of video URLs given a playlist?  I want to be able to do something like 

```youtube-dl --dump-playlist <playlist-URL>|parallel -j3 youtube-dl```

**Comment by fsiler** [comment]
In my case, I'm adding subtitles and doing other processing to downloaded videos, so it would be much faster in parallel because right now network sits idle quite a bit of the time.

This does indeed dump JSON, but fairly slowly- looks like maybe youtube-dl is doing deep introspection, which isn't required for my use case.  I only need the youtube ID for this application.

Filtering through `jq '.webpage_url_basename'` gives me what I need to know- just wondered if there's a lighter-weight, faster version of this.

**Comment by dstftw** [comment]
`--flat-playlist`.
