### ISSUE TITLE
PluralSight ExtractorError: No video formats found

### ISSUE THREAD

**Issue by XeonG** [rg3/youtube-dl#16889]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'-o', u'%(playlist_index)s - %(title)s.%(ext)s', u'--verbose', u'--min-sleep-interval', u'181', u'--max-sleep-interval', u'227', u'--playlist-items', u'0-222', u'https://app.pluralsight.com/library/courses/aspdotnet-core-2-razor-playbook', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.25
[debug] Python version 2.7.14 (CPython) - CYGWIN_NT-6.1-2.10.0-0.325-5-3-x86_64-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] aspdotnet-core-2-razor-playbook: Downloading course JSON
[download] Downloading playlist: ASP.NET Core 2.0 Razor Playbook
[pluralsight:course] playlist ASP.NET Core 2.0 Razor Playbook: Collected 62 video ids (downloading 63 of them)
[download] Downloading video 1 of 63
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] 9090bbd8-a311-4031-a1db-34d337df437c-6: Downloading course JSON
[pluralsight] 9090bbd8-a311-4031-a1db-34d337df437c-6: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 404: Not Found
[pluralsight] 9090bbd8-a311-4031-a1db-34d337df437c-6: Waiting for 4 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 327, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description of your *issue*, suggested solution and other information

Seems to happen often with newer PluralSight content, sometimes older content... tested with latest version.

Example url the above was tested with... https://app.pluralsight.com/library/courses/aspdotnet-core-2-razor-playbook

**Comment by robk9e** [comment]
Same here

**Comment by XeonG** [comment]
Interestingly.. that url above started downloading yesterday, got about 13videos downloaded...

however I try resuming from video 13 again today and I get the below variation on the above error....

Would be great if pluralsight just offered subscribers a way to download the damn videos for offline and better desktop video playing... instead of forcing us to watch through there own janky system, but right now youtube-dl is the only way and its not working 100% of the time. I hope someone is able to look into it.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'-o', u'%(playlist_index)s - %(title)s.%(ext)s', u'--verbose', u'--min-sleep-interval', u'181', u'--max-sleep-interval', u'227', u'--playlist-items', u'13-222', u'https://app.pluralsight.com/library/courses/aspdotnet-core-2-razor-playbook', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.25
[debug] Python version 2.7.14 (CPython) - CYGWIN_NT-6.1-2.10.0-0.325-5-3-x86_64-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] aspdotnet-core-2-razor-playbook: Downloading course JSON
[pluralsight:course] aspdotnet-core-2-razor-playbook: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 598, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```
