### ISSUE TITLE
Unable to download videos from Lynda

### ISSUE THREAD

**Issue by abarber229** [rg3/youtube-dl#16891]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

c:\youtube-dl>youtube-dl --verbose --username XXX --password XXX "https://www.lynda.com/Power-BI-Desktop-tutorials/Learning-Microsoft-Power-BI-Desktop/688535-2.html" -o "%USERPROFILE%\Downloads\Lynda\%(playlist)s/%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s" --sleep-interval 10
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.lynda.com/Power-BI-Desktop-tutorials/Learning-Microsoft-Power-BI-Desktop/688535-2.html', '-o', 'C:\\Users\\username\\Downloads\\Lynda\\%(playlist)s/%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s', '--sleep-interval', '10']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.06.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Downloading signin page
[lynda:course] Submitting email
ERROR: Unable to download JSON metadata: HTTP Error 418:  (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\extractor\common.py", line 598, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

I tried two different links and both work in the browser. I just updated to 2018.06.25. Let me know if I'm missing something.

**Comment by dstftw** [comment]
You must provide reproducible account credentials for any work on the issue.

**Comment by abarber229** [comment]
I emailed you the account info. Sorry about that.

**Comment by dstftw** [comment]
Incorrect credentials. Neither direct login nor linkedin login works with your credentials.

**Comment by abarber229** [comment]
That's odd. It works for me using the direct login.

**Comment by dstftw** [comment]
![image](https://user-images.githubusercontent.com/1908898/42183010-72caf946-7e6a-11e8-94ce-73a0e573d39b.png)

**Comment by abarber229** [comment]
I see what I did. I put in the incorrect email address in both the script and the one I sent you. My apologizes. In Chrome it was autofilling until I tried another browser and received what you got. Thank you for the troubleshooting with me.
