### ISSUE TITLE
youtube-dl fails on arch when installed from pacman

### ISSUE THREAD

**Issue by phihag** [rg3/youtube-dl#1689]
Issue report from IRC:

[youtube-dl's main](http://pastebin.com/1tWZgvLF) (on current arch, installed with pacman) fails with

```
File "/usr/bin/youtube-dl", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```

**Comment by chanibal** [comment]
This issue has come back, and this time `sudo pacman -Sy python-setuptools` doesn't help.

**Comment by jaimeMF** [comment]
@chanibal open a new issue, but note that if you are using the version provided by pacman you should first contact its maintainers to make sure it isn't a problem in their package (or check if you can reproduce it with the packages from https://yt-dl.org/ or the git repo).

**Comment by chanibal** [comment]
@jaimeMF you're right, downloading from yt-dl.org worked. I'll add the issue to the arch guys.
