### ISSUE TITLE
[dailymotion] unable to download playlist

### ISSUE THREAD

**Issue by zecoj** [rg3/youtube-dl#16894]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---
latest version doesn't want to download any playlist from dailymotion, shows "downloading 0 videos"
```
$> youtube-dl --version
2018.06.25
$> youtube-dl -v "https://www.dailymotion.com/playlist/x42uxl"
[debug] System config: []
[debug] User config: [u'--format', u'best', u'--external-downloader', u'aria2c', u'--external-downloader-args', u'-x 5']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.dailymotion.com/playlist/x42uxl']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.25
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-128-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.4.2-1, ffprobe 3.4.2-1
[debug] Proxy map: {}
[dailymotion:playlist] x42uxl: Downloading webpage
[download] Downloading playlist: SURF
[dailymotion:playlist] x42uxl: Downloading page 1
[dailymotion:playlist] playlist SURF: Downloading 0 videos
[download] Finished downloading playlist: SURF
```

**Comment by amppumas** [comment]
Same issue here, no error message displayed.

**Comment by lguez** [comment]
Same issue with:
```
$ youtube-dl --version
2018.07.21

$ youtube-dl https://www.dailymotion.com/playlist/x57eub
[dailymotion:playlist] x57eub: Downloading webpage
[download] Downloading playlist: Liste de Lionel
[dailymotion:playlist] x57eub: Downloading page 1
[dailymotion:playlist] playlist Liste de Lionel: Downloading 0 videos
[download] Finished downloading playlist: Liste de Lionel
```
But the playlist is not empty. The same command (with version 2018.02.08 of youtube-dl) on the same playlist worked in March, 2018.
