### ISSUE TITLE
Implement hooktube as video source

### ISSUE THREAD

**Issue by Cowboy1950** [rg3/youtube-dl#16906]
[ x] I've verified and I assure that I'm running youtube-dl 2018.06.25

Before submitting an issue make sure you have:

    [x ] At least skimmed through the README, most notably the FAQ and BUGS sections
    [ x] Searched the bugtracker for similar issues including closed ones
    [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

What is the purpose of your issue?

    Bug report (encountered problems with youtube-dl)
    Site support request (request for adding support for a new site)
    [ x] Feature request (request for a new functionality)
    Question
    Other

Using your tool you can avoid going directly on
youtube and you don't have to share much more personal data than your IP adress.

However, I'd like to avoid even that by using a proxy like hooktube.com.

So maybe you could allow for using that in youtube-dl as well?

Or is there already an option available that I could use as proxy?

About the other formats of the URLs below I'm not sure - don't use playlist.

If the purpose of this issue is a site support request please provide all kinds of example URLs support for which should be included (replace following example URLs by yours):

    Single video: https://hooktube.com/watch?v=2gHtKPf93Zg

**Comment by dstftw** [comment]
By going directly to youtube you don't share anything apart from your IP either so I don't see any point supporting such proxies. Needless to say media file itself is downloaded from google servers in both cases.
