### ISSUE TITLE
Reliance AGM stream videos not working, maybe HLS at fault ??

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#16908]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

I first tried to see what options are available to me. Almost all videos have the same option, doesn't give me 22 or something better. 

```
$ youtube-dl -F APUh0q7D_ZQ
[youtube] APUh0q7D_ZQ: Downloading webpage
[youtube] APUh0q7D_ZQ: Downloading video info webpage
[youtube] APUh0q7D_ZQ: Downloading m3u8 information
[youtube] APUh0q7D_ZQ: Downloading MPD manifest
[youtube] APUh0q7D_ZQ: Downloading MPD manifest
[info] Available formats for APUh0q7D_ZQ:
format code  extension  resolution note
139          m4a        audio only DASH audio   64k , m4a_dash container, mp4a.40.5@ 48k (24000Hz)
140          m4a        audio only DASH audio  144k , m4a_dash container, mp4a.40.2@128k (48000Hz)
160          mp4        256x144    DASH video  124k , mp4_dash container, avc1.4d400c, 30fps, video only
133          mp4        426x240    DASH video  258k , mp4_dash container, avc1.4d4015, 30fps, video only
134          mp4        640x360    DASH video  646k , mp4_dash container, avc1.4d401e, 30fps, video only
135          mp4        854x480    DASH video 1171k , mp4_dash container, avc1.4d401f, 30fps, video only
136          mp4        1280x720   DASH video 2326k , mp4_dash container, avc1.4d401f, 30fps, video only
91           mp4        256x144    HLS  197k , avc1.4d400c, 30.0fps, mp4a.40.5@ 48k
92           mp4        426x240    HLS  338k , avc1.4d4015, 30.0fps, mp4a.40.5@ 48k
93           mp4        640x360    HLS  829k , avc1.4d401e, 30.0fps, mp4a.40.2@128k
94           mp4        854x480    HLS 1380k , avc1.4d401f, 30.0fps, mp4a.40.2@128k
95           mp4        1280x720   HLS 2593k , avc1.4d401f, 30.0fps, mp4a.40.2@256k (best)
```

Then I tried the following - 

```
$ youtube-dl -v -c -f 95 APUh0q7D_ZQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-c', '-f', '95', 'APUh0q7D_ZQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.18
[debug] Python version 3.6.6 (CPython) - Linux-4.16.0-2-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] APUh0q7D_ZQ: Downloading webpage
[youtube] APUh0q7D_ZQ: Downloading video info webpage
[youtube] APUh0q7D_ZQ: Downloading m3u8 information
[youtube] APUh0q7D_ZQ: Downloading MPD manifest
[youtube] APUh0q7D_ZQ: Downloading MPD manifest
```

It uses googlevideo to manifest the downloads but does a piss poor job of the same. I remember HLS having issues earlier. Maybe something similar here at work :(

It basically throttles the download to less than 20 kbps, have no idea why :(

**Comment by dstftw** [comment]
This was a live stream at the time of writing.
