### ISSUE TITLE
Downloads not working on tv.nrk.no

### ISSUE THREAD

**Issue by shilohjlc** [rg3/youtube-dl#16909]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v https://tv.nrk.no/serie/backstage/sesong/1/episode/8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://tv.nrk.no/serie/backstage/sesong/1/episode/8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.04
[debug] Python version 2.7.10 (CPython) - Darwin-17.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[NRKTVSeries] backstage: Downloading webpage
[download] Downloading playlist: NRK TV – Backstage
[NRKTVSeries] playlist NRK TV – Backstage: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: NRK TV – Backstage
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://tv.nrk.no/serie/backstage/sesong/1/episode/8

---

### Description of your *issue*, suggested solution and other information

It seems like they have changed their URLs, they used to include some sort of ID before, but now its all text for each episode. That might be the cause of the problem.

**Comment by amay5267** [comment]
hello. i have the same issues. how can I fix this?

**Comment by osimons** [comment]
It still works by manually reconstructing the old-style URL. View page HTML source and search for the `@id` value in the meta summary for the episode:

New style URL (not working as from bug report):

`https://tv.nrk.no/serie/backstage/sesong/1/episode/8`

Old style URL (still works with `youtube-dl`, but will redirect to new style URL in a browser):

`https://tv.nrk.no/serie/backstage/MSUI14000816/sesong-1/episode-8`

Also note that not all series are affected by the redesign. Visiting some series from the archives show pages still using old visual layout with all episode URLs working as expected (at least for now). See for instance `https://tv.nrk.no/serie/glimt-av-norge`.

**Comment by forthrin** [comment]
Yep, they did a redesign. Hope a fix will come within a week or so, as I use this all the time.
