### ISSUE TITLE
Generic podcast RSS feed support

### ISSUE THREAD

**Issue by peterk** [rg3/youtube-dl#16912]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.04
[debug] Python version 3.6.3 (CPython) - Darwin-17.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Playlist: https://www.spreaker.com/show/2581878/episodes/feed
- Playlist: https://mandag.libsyn.com/rss
- Playlist: https://rss.acast.com/teachmehowtomoney
- Playlist: https://spelkosmos.se/alla-episoder.rss

---

### Description of your *issue*, suggested solution and other information

Support for generic podcast RSS feeds would be very useful in Youtube-dl. It would enable archiving of podcasts together with youtube channel clips in an easy way. Structured data in RSS feeds can be treated as a playlist and would make it easy to repeat RSS feed requests on a regular interval using Youtube-dl config files and output patterns. Outputting metadata together with the MP3 file would make files easier to find.

I have added a couple of generic podcast RSS-channels above.

**Comment by dstftw** [comment]
Have you even tried before requesting existing feature?

**Comment by peterk** [comment]
Sorry for being too vague. Yes, I tried. Using the URL:s above with the following parameters

`youtube-dl -i --write-description --write-thumbnail --write-info-json -o "%(upload_date)s_%(title)s_[%(id)s].%(ext)s" <RSS url>`

1. No id parsed form `<guid>` - For spreaker RSS it is set to a part of the URL like ”23315458episode_id=15191837&response-content-disposition=attachment;filename='tsc_189”
2. Publication date not parsed from `<pubDate>`
3. Thumbnail not recognized from `<itunes:image>` or `<googleplay:image>`
4. Description text not recognized from `<itunes:summary>`, `<itunes:subtitle>` (Acast RSS), `<description>` or `<content:encoded>` (Libsyn RSS)

So I concluded there was no specific support for podcast RSS feeds, only the "Falling back on generic information extractor.".

**Comment by bas080** [comment]
It would be nice to have youtube-dl be able to handle podcast feeds better. It makes no sense to support very specific providers well and not support a common format well.
