### ISSUE TITLE
ERROR: Unable to extract id (bloomberg)

### ISSUE THREAD

**Issue by rofl0r** [rg3/youtube-dl#16919]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.04**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v https://www.bloomberg.com/news/videos/2016-12-02/lynn-forrester-de-rothschild-on-inclusive-capital
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.bloomberg.com/news/videos/2016-12-02/lynn-forrester-de-rothschild-on-inclusive-capital']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.04
[debug] Python version 2.7.15 (CPython) - Linux-4.14.50-x86_64-with-libc
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[Bloomberg] lynn-forrester-de-rothschild-on-inclusive-capital: Downloading webpage
ERROR: Unable to extract id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/lib/python2.7/site-packages/youtube_dl/extractor/bloomberg.py", line 58, in _real_extract
    r'BPlayer\(null,\s*({[^;]+})\);', webpage, 'id'), name)
  File "/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 971, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

---

### Description of your *issue*, suggested solution and other information

ERROR: Unable to extract id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by justinhwang** [comment]
Just attempting to leave a helpful comment for developers- unsure why the regex is not getting the video id,
>"bmmrId":"0gUE~pD0SuSxCc7lDNFz7Q"

can be found in the source for the link provided and should match the first regex.
<br />
Also, the first test fails because the video [no longer exists](http://www.bloomberg.com/news/videos/b/aaeae121-5949-481e-a1ce-4562db6f5df2) and the second test fails because instead of:
>BPlayer(null, {"id": "938c7e72-3f25-4ddb-8b85-a9be731baa74"})

(which is now commented out), there is now:
>var embedOptions = {id: '938c7e72-3f25-4ddb-8b85-a9be731baa74'}

@dstftw tagging you because you were the last to add a regex to the file and would most likely be a quick fix to someone who actually understands regex

**Comment by Jav-A** [comment]
Same problem here.

youtube-dl --version
2018.08.04
youtube-dl --verbose http://www.bloomberg.com/news/videos/2018-08-07/first-round-of-renewed-u-s-sanctions-on-iran-take-effect-video
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.bloomberg.com/news/videos/2018-08-07/first-round-of-renewed-u-s-sanctions-on-iran-take-effect-video']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.11+ (CPython) - Linux-4.4.0-22-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[Bloomberg] first-round-of-renewed-u-s-sanctions-on-iran-take-effect-video: Downloading webpage
ERROR: Unable to extract id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bloomberg.py", line 58, in _real_extract
    r'BPlayer\(null,\s*({[^;]+})\);', webpage, 'id'), name)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Regards.

**Comment by mzfr** [comment]
@rofl0r are you still getting this error ? because that seems to work for me. 
**Verbose Output**:
```
youtube-dl -v https://www.bloomberg.com/news/videos/2016-12-02/lynn-forrester-de-rothschild-on-inclusive-capital --skip-download                          09:57:22
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bloomberg.com/news/videos/2016-12-02/lynn-forrester-de-rothschild-on-inclusive-capital', '--skip-download']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.5.2 (CPython) - Linux-4.15.0-29-generic-x86_64-with-neon-16.04-xenial
[debug] exe versions: avconv 2.8.14-0ubuntu0.16.04.1, avprobe 2.8.14-0ubuntu0.16.04.1, ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[Bloomberg] lynn-forrester-de-rothschild-on-inclusive-capital: Downloading webpage
[Bloomberg] 0gUE~pD0SuSxCc7lDNFz7Q: Downloading JSON metadata
[Bloomberg] 0gUE~pD0SuSxCc7lDNFz7Q: Downloading m3u8 information
[Bloomberg] 0gUE~pD0SuSxCc7lDNFz7Q: Downloading m3u8 information
[Bloomberg] 0gUE~pD0SuSxCc7lDNFz7Q: Downloading m3u8 information
[Bloomberg] 0gUE~pD0SuSxCc7lDNFz7Q: Downloading f4m manifest
[Bloomberg] 0gUE~pD0SuSxCc7lDNFz7Q: Downloading f4m manifest
[Bloomberg] 0gUE~pD0SuSxCc7lDNFz7Q: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
```

@Jav-A Even your link seems to work fine.
**Verbose Output**:
```
youtube-dl --verbose http://www.bloomberg.com/news/videos/2018-08-07/first-round-of-renewed-u-s-sanctions-on-iran-take-effect-video --skip-download       10:02:49
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.bloomberg.com/news/videos/2018-08-07/first-round-of-renewed-u-s-sanctions-on-iran-take-effect-video', '--skip-download']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.5.2 (CPython) - Linux-4.15.0-29-generic-x86_64-with-neon-16.04-xenial
[debug] exe versions: avconv 2.8.14-0ubuntu0.16.04.1, avprobe 2.8.14-0ubuntu0.16.04.1, ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[Bloomberg] first-round-of-renewed-u-s-sanctions-on-iran-take-effect-video: Downloading webpage
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading JSON metadata
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading m3u8 information
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading m3u8 information
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading m3u8 information
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading f4m manifest
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading f4m manifest
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
```

**Comment by justinhwang** [comment]
@dstftw Did you see my comment?

**Comment by rofl0r** [comment]
@mfzr it's probably due to you using python 3 vs we using python 2

**Comment by mzfr** [comment]
@rofl0r Have you tested it ?

**Comment by Jav-A** [comment]
Hello again,

Today, everything seems to work again... Tried python2/3, your video link and mine. No changes nor updates done on the computer... Same youtube-dl version 2018.08.04. Maybe it was something temporary on the website. 

python /usr/local/bin/youtube-dl --verbose http://www.bloomberg.com/news/videos/2018-08-07/first-round-of-renewed-u-s-sanctions-on-iran-take-effect-video
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.bloomberg.com/news/videos/2018-08-07/first-round-of-renewed-u-s-sanctions-on-iran-take-effect-video']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.11+ (CPython) - Linux-4.4.0-22-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[Bloomberg] first-round-of-renewed-u-s-sanctions-on-iran-take-effect-video: Downloading webpage
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading JSON metadata
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading m3u8 information
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading m3u8 information
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading m3u8 information
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading f4m manifest
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading f4m manifest
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://bbgvod-vodproduseast.lldns.net/m/NzU5NDU0Ng/MjUyMDkyNg/intvmotevalli0807_,70,15,24,44,120,180,240,0.mp4.csmil/intvmotevalli0807_,70,15,24,44,120,180,240,0.mp4-audio=128000-video=2399693.m3u8?base_path=https://bbgvod-vodproduseast.lldns.net/m/NzU5NDU0Ng/MjUyMDkyNg/intvmotevalli0807_,70,15,24,44,120,180,240,0.mp4.csmil/&fragment_duration=6000&scale=1000&hls_client_manifest_version=3&hdcore=1'
[download] Destination: First Round of Renewed U.S. Sanctions on Iran Take Effect-QIhfVZ1~RFi4qU47CaHM6g.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0 (Chrome)
' -i 'https://bbgvod-vodproduseast.lldns.net/m/NzU5NDU0Ng/MjUyMDkyNg/intvmotevalli0807_,70,15,24,44,120,180,240,0.mp4.csmil/intvmotevalli0807_,70,15,24,44,120,180,240,0.mp4-audio=128000-video=2399693.m3u8?base_path=https://bbgvod-vodproduseast.lldns.net/m/NzU5NDU0Ng/MjUyMDkyNg/intvmotevalli0807_,70,15,24,44,120,180,240,0.mp4.csmil/&fragment_duration=6000&scale=1000&hls_client_manifest_version=3&hdcore=1' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:First Round of Renewed U.S. Sanctions on Iran Take Effect-QIhfVZ1~RFi4qU47CaHM6g.mp4.part'
ffmpeg version 2.8.6-1ubuntu2 Copyright (c) 2000-2016 the FFmpeg developers
...


python3 /usr/local/bin/youtube-dl --verbose http://www.bloomberg.com/news/videos/2018-08-07/first-round-of-renewed-u-s-sanctions-on-iran-take-effect-video
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.bloomberg.com/news/videos/2018-08-07/first-round-of-renewed-u-s-sanctions-on-iran-take-effect-video']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-22-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[Bloomberg] first-round-of-renewed-u-s-sanctions-on-iran-take-effect-video: Downloading webpage
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading JSON metadata
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading m3u8 information
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading m3u8 information
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading m3u8 information
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading f4m manifest
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading f4m manifest
[Bloomberg] QIhfVZ1~RFi4qU47CaHM6g: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://bbgvod-vodproduseast.lldns.net/m/NzU5NDU0Ng/MjUyMDkyNg/intvmotevalli0807_,70,15,24,44,120,180,240,0.mp4.csmil/intvmotevalli0807_,70,15,24,44,120,180,240,0.mp4-audio=128000-video=2399693.m3u8?base_path=https://bbgvod-vodproduseast.lldns.net/m/NzU5NDU0Ng/MjUyMDkyNg/intvmotevalli0807_,70,15,24,44,120,180,240,0.mp4.csmil/&fragment_duration=6000&scale=1000&hls_client_manifest_version=3&hdcore=1'
[download] Destination: First Round of Renewed U.S. Sanctions on Iran Take Effect-QIhfVZ1~RFi4qU47CaHM6g.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0 (Chrome)
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
' -i 'https://bbgvod-vodproduseast.lldns.net/m/NzU5NDU0Ng/MjUyMDkyNg/intvmotevalli0807_,70,15,24,44,120,180,240,0.mp4.csmil/intvmotevalli0807_,70,15,24,44,120,180,240,0.mp4-audio=128000-video=2399693.m3u8?base_path=https://bbgvod-vodproduseast.lldns.net/m/NzU5NDU0Ng/MjUyMDkyNg/intvmotevalli0807_,70,15,24,44,120,180,240,0.mp4.csmil/&fragment_duration=6000&scale=1000&hls_client_manifest_version=3&hdcore=1' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:First Round of Renewed U.S. Sanctions on Iran Take Effect-QIhfVZ1~RFi4qU47CaHM6g.mp4.part'
ffmpeg version 2.8.6-1ubuntu2 Copyright (c) 2000-2016 the FFmpeg developers
...


Thank you.

**Comment by rofl0r** [comment]
amazing, it works now, even the video i posted in the description and others said it was no longer available downloads now. with 2018.07.21

**Comment by mingw128** [comment]
And it's broken again. I think Bloomberg is playing with how they do video streaming since I've noticed different results over the past few weeks (when using other 3rd party capture tools as well).

using: youtube-dl is up-to-date (2018.08.04)
tried with new: youtube-dl https://www.bloomberg.com/news/videos/2018-08-10/-bloomberg-surveillance-full-show-08-10-2018-video
and old: youtube-dl https://www.bloomberg.com/news/videos/2016-12-02/lynn-forrester-de-rothschild-on-inclusive-capital

error:
`D:\>youtube-dl --verbose https://www.bloomberg.com/news/videos/2018-08-10/-bloomberg-surveillance-full-show-08-10-2018-video
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.bloomberg.com/news/videos/2018-08-10/-bloomberg-surveillance-full-show-08-10-2018-video']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 3.3.1, ffprobe 3.3.1
[debug] Proxy map: {}
[Bloomberg] -bloomberg-surveillance-full-show-08-10-2018-video: Downloading webpage
ERROR: Unable to extract id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\bloomberg.py", line 58, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 972, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
