### ISSUE TITLE
"No video Formats found" error when trying to download from pluralsight!

### ISSUE THREAD

**Issue by pooria1366** [rg3/youtube-dl#16915]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookie.txt', '--sleep-interval', '120', '--all-subs', '-o', '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s_%(title)s.%(ext)s', 'https://app.pluralsight.com/library/courses/csharp-collections']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.07.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91152-g7c333dc6a7
[debug] Proxy map: {}
[pluralsight:course] csharp-collections: Downloading JSON metadata
[download] Downloading playlist: C# Collections Fundamentals
[pluralsight:course] playlist C# Collections Fundamentals: Collected 109 video ids (downloading 109 of them)
[download] Downloading video 1 of 109
[pluralsight] csharp-collections-fundamentals-m1-welcome-0: Downloading JSON metadata
[pluralsight] csharp-collections-fundamentals-m1-welcome-0: Downloading mp4-high viewclip graphql
[pluralsight] csharp-collections-fundamentals-m1-welcome-0: Waiting for 4 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuh7o953j\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuh7o953j\build\youtube_dl\extractor\common.py", line 501, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuh7o953j\build\youtube_dl\extractor\pluralsight.py", line 409, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuh7o953j\build\youtube_dl\extractor\common.py", line 1281, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

I use following command:
youtube-dl -v --cookies cookie.txt --sleep-interval 120 --all-subs -o "%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s_%(title)s.%(ext)s" "https://app.pluralsight.com/library/courses/csharp-collections"
Have tried changing my IP ,one other account and other courses and unfortunately still the same error.

**Comment by lasharela** [comment]
[pluralsight] rust-fundamentals-m1-0: Waiting for 2 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 409, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

The same here. 
https://app.pluralsight.com/library/courses/rust-fundamentals/table-of-contents link

**Comment by dstftw** [comment]
Most likely your cookies are expired. Anyway for any work on the issue you must provide account credentials.

**Comment by pooria1366** [comment]
@dstftw Yup I was supplying the wrong file instead of cookie X'D

**Comment by nepax** [comment]
whats the solution on this?

**Comment by mringler** [comment]
I think it means you need to supply youtube credentials. Seems like there are three methods to do it:

- use the `--username` parameter for and give password in prompt (or use `--password` parameter)
- copy cookie header from request (as nicely described [here](https://apple.stackexchange.com/a/360619/385778) and supply it through `--add-header` parameter
- download youtube cookies to text file and supply filename with `--cookies` parameter

**However**, for **youtube**, first two do not work (for me?), third is too much hassle, to be honest.

When I give google username (`mesa@googlemail.com`) and enter my google password, it won't work.
Giving the cookie header does not work either, probably because of wrong format (see [here](https://superuser.com/questions/1333442/how-can-youtube-dl-download-videos-that-require-user-authentication-and-2fa)). Again, argh, the hassle...

Am I missing something here? Seems like downloading from youtube with youtube-dl is quasi-broken at this point.

**Comment by NirobNabil** [comment]
just as @mringler said, tried all three of em (for **youtube**) and it still says no video formats found. although i couldn't really get the login thing to work (says **couldn't look up account info** with a `http: 400 bad request`).

also, i was getting "too many requests `http: 429`" error when using my main IP. using a proxy solved that issue but now i'm stuck with this no video formats problem.

PS. i used firefox plugin `cookies.txt` to get the cookies
