### ISSUE TITLE
WebOfStories Playlist: youtube-dl Finds 0 Videos

### ISSUE THREAD

**Issue by Mohammed90** [rg3/youtube-dl#16914]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.webofstories.com/playAll/oliver.sacks']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.04
[debug] Python version 2.7.15 (CPython) - Darwin-17.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1
[debug] Proxy map: {}
[WebOfStoriesPlaylist] oliver.sacks: Downloading webpage
[download] Downloading playlist: Oliver Sacks (Scientist)
[WebOfStoriesPlaylist] playlist Oliver Sacks (Scientist): Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: Oliver Sacks (Scientist)
```

---

### Description of your *issue*, suggested solution and other information

The playlist [here](https://www.webofstories.com/playAll/oliver.sacks) contains 360 videos, yet `youtube-dl` cannot find them. According to the [supportedsites.md](https://github.com/rg3/youtube-dl/blob/689af49/docs/supportedsites.md), WebOfStories playlists are supported. In fact, `youtube-dl` is able to download a single video, but not videos of playlists.

**Comment by mzfr** [comment]
@dstftw After investigating a bit about this issue I found out that in [/extractor/webofstorie.py#L137](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/webofstories.py#L137) we are trying to find a pattern that have `/playAll/<playlist_id>` but if you'll look in the html source of the page there is no such pattern. 
My guess is they use js for playing video as the link of the page stays same after clicking on any of the video in the list. 

I have tested this on [`playAll/donald.knuth`](https://www.webofstories.com/playAll/donald.knuth) and also the list mentioned in the issue.

**Comment by Mohammed90** [comment]
I'm thinking maybe they changed their streaming URLs? Either way, I've `curl`ed the page into an offline HTML file, and compared notes with their online webpage. Here are the two scenarios:

- If the "browser" supports the video tag, then the page will contain 2 video tag items:

     1. One for mobile (and backup for browsers that don't support video tag), where the source of the video material can be found at the `src` attribute of: `video#playerForMobile > source`

    2. The other location is at the `src` attribute of: `video.jw-video.jw-reset`

- If the browser doesn't support the video tag, then the media source can be found at the location described in number 1 above.

The code needs to start from the first URL to learn the general structure of the media location. Here's an example URL:
`https://d2o4yifwfks2gg.cloudfront.net/stories/50035/1.mp4`

Notice `1.mp4` at the end? It'll just go sequentially from there to the index of the last video in the playlist. The total count of videos in a playlist is the number of tags that have the class `.playListItem` .
