### ISSUE TITLE
Globoplay fragment download failure

### ISSUE THREAD

**Issue by issamu2k** [rg3/youtube-dl#16927]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.04**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://globoplay.globo.com/v/6856218/programa/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out utf_8, pref UTF-8
[debug] youtube-dl version 2018.07.04
[debug] Python version 2.7.12 (CPython) - Linux-3.14.79-116-aarch64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg N-89109-gc3b5ea7, ffprobe N-89109-gc3b5ea7, phantomjs 2.1.1
[debug] Proxy map: {}
[Globo] 6856218: Downloading JSON metadata
[Globo] 6856218: Downloading security hash for 5b4021bd636d61c189000000_90_720_m3u8
[Globo] 5b4021bd636d61c189000000_90_720_m3u8: Downloading m3u8 information
[Globo] 6856218: Downloading security hash for 5b4021bd636d61c189000000_360_1080_m3u8
[Globo] 5b4021bd636d61c189000000_360_1080_m3u8: Downloading m3u8 information
[Globo] 6856218: Downloading security hash for 5b4021bd636d61c189000000_90_720_l_m3u8
[Globo] 5b4021bd636d61c189000000_90_720_l_m3u8: Downloading m3u8 information
[Globo] 6856218: Downloading security hash for 5b4021bd636d61c189000000_360_1080_l_m3u8
[Globo] 5b4021bd636d61c189000000_360_1080_l_m3u8: Downloading m3u8 information
[Globo] 6856218: Downloading security hash for 5b4021bd636d61c189000000_360_1080_manifest
[Globo] 5b4021bd636d61c189000000_360_1080_manifest: Downloading ISM manifest
[Globo] 6856218: Downloading security hash for 5b4021bd636d61c189000000_360_1080_mpd
[Globo] 5b4021bd636d61c189000000_360_1080_mpd: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://vodstreaming01a.video.globo.com/r360_1080/v8/db/72/fc/6856218_fc354f9748a0570796af29c60331b26f048f1686/6856218-manifest.ism/dash/'
[dashsegments] Total fragments: 69
[download] Destination: ‘Macacos do mar’ usam pedras como ferramenta pra ajudar a abrir mariscos-6856218.fdash-video_por=3041000.mp4
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 182, in establish_connection
    raise RetryDownload(err)
RetryDownload


```

---

### Description of your *issue*, suggested solution and other information
So some videos has this fragment download failure. Like these ones:
https://globoplay.globo.com/v/6844306/programa/
https://globoplay.globo.com/v/6844308/programa/

These on other hand, is fine:
https://globoplay.globo.com/v/6844309/programa/
https://globoplay.globo.com/v/6844312/programa/
https://globoplay.globo.com/v/6844316/programa/

All of them are online, and you can play them just fine on the browser.
https://globoplay.globo.com/globo-rural/p/1937/

**Comment by dstftw** [comment]
Server side error, last fragment is not available.

**Comment by issamu2k** [comment]
How come you can watch the whole video on the browser? It doesn't seem it's missing the last fragment there...

**Comment by dstftw** [comment]
Browser does not use DASH.
