### ISSUE TITLE
SonyLIV videos with original bitrate

### ISSUE THREAD

**Issue by theincognito-inc** [rg3/youtube-dl#16938]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.04**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Hi, 

Earlier there was an issue with SonyLIV free to play videos not able to download via youtube-dl.
This was fixed by @remitamine in this [commit](https://github.com/rg3/youtube-dl/commit/74caf528bc822738dffe231df86ed399fc97a38a). 

Now, I found something interesting. After this commit, for the videos with fairplay encryption, I could download the "source" video(See the commit mentioned above for more details). This is a huge development(atleast in my eyes 🥇 ) since the SonyLIV bitrates are abysmal (1199 kb/s at 720p -that's their maximum quality) and the source video was having ~5000 kb/s at 1080p.

I tried editing the brightcove.py using the commit mentioned earlier, by copying the relevant portion just outside the "if not formats:" line. This resulted in some more videos having the formats we normally get, along with "source" formats. However, it's not working for all videos. I am a python noob, so I dunno much. I am a paid member of that site and is willing to share my login details, if required.

Sample URLs getting source video:

1. In the current commit - https://www.sonyliv.com/details/highlights/5806567196001/

2. After the my edit to brightcove.py - https://www.sonyliv.com/details/highlights/5806741959001/

3. Still not getting source video - https://www.sonyliv.com/details/clips/5804733675001/

Note, I am getting regular video formats for all videos without any hassles. I know this is an enhancement and if this is not possible, please let me know and close this ticket.

Thanks and Regards!

**Comment by theincognito-inc** [comment]
@dstftw @remitamine

**Comment by dstftw** [comment]
No source URLs available for these videos.
