### ISSUE TITLE
can't download bbc video caption in latest version

### ISSUE THREAD

**Issue by lweo** [rg3/youtube-dl#16936]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl  --verbose https://www.bbc.co.uk/iplayer/episode/b0b3q1rm/panorama-police-under-pressure --proxy socks5://127.0.0.1:1080  --skip-download  --write-sub
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.bbc.co.uk/iplayer/episode/b0b9dzb6/panorama-smartphones-the-dark-side', u'--proxy', u'socks5://127.0.0.1:1080', u'--skip-download', u'--write-sub']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.04
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-127-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {u'http': u'socks5://127.0.0.1:1080', u'https': u'socks5://127.0.0.1:1080'}
[bbc.co.uk] b0b9dzb6: Downloading video page
[bbc.co.uk] b0b9dzb6: Downloading playlist JSON
[bbc.co.uk] b0b9dz98: Downloading media selection XML
[bbc.co.uk] b0b9dz98: Downloading captions
[bbc.co.uk] b0b9dz98: Downloading captions
[bbc.co.uk] b0b9dz98: Downloading captions
ERROR: Unable to download XML: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/k/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 598, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/k/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```

**Comment by dstftw** [comment]
Most likely your proxy endpoint is banned.
```
[bbc.co.uk] b0b3q1rm: Downloading video page
[bbc.co.uk] b0b3q1rm: Downloading playlist JSON
[bbc.co.uk] b0b3q171: Downloading media selection XML
[bbc.co.uk] b0b3q171: Downloading m3u8 information
[bbc.co.uk] b0b3q171: Downloading m3u8 information
[bbc.co.uk] b0b3q171: Downloading MPD manifest
[bbc.co.uk] b0b3q171: Downloading MPD manifest
[bbc.co.uk] b0b3q171: Downloading m3u8 information
[bbc.co.uk] b0b3q171: Downloading m3u8 information
[bbc.co.uk] b0b3q171: Downloading m3u8 information
[bbc.co.uk] b0b3q171: Downloading m3u8 information
[bbc.co.uk] b0b3q171: Downloading m3u8 information
[bbc.co.uk] b0b3q171: Downloading m3u8 information
[bbc.co.uk] b0b3q171: Downloading MPD manifest
[bbc.co.uk] b0b3q171: Downloading MPD manifest
[bbc.co.uk] b0b3q171: Downloading m3u8 information
[bbc.co.uk] b0b3q171: Downloading m3u8 information
[bbc.co.uk] b0b3q171: Downloading m3u8 information
[bbc.co.uk] b0b3q171: Downloading m3u8 information
[dashsegments] Total fragments: 912
[download] Destination: Panorama, Police Under Pressure-b0b3q171.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-video=5070000.mp4
[download]   0.0% of ~859.70MiB at 551.95KiB/s ETA 01:44:28
ERROR: Interrupted by user
```

**Comment by lweo** [comment]
@dstftw but I can download iplayer videos on bbc website. Why?
