### ISSUE TITLE
[Generic] Better display_id detection

### ISSUE THREAD

**Issue by bato3** [rg3/youtube-dl#16946]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
youtube-dl.exe -v https://video.sibnet.ru/shell.php?videoid=956371 --get-id
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://video.sibnet.ru/shell.php?videoid=956371', '--get-id']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, phantomjs 2.1.1
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
[debug] Default format spec: bestvideo+bestaudio/best
shell
```
---

### Description of your *issue*, suggested solution and other information

Is it possible for YT to return the correct ID: `956371` instead `shell`?

I did not notice how it is for other generic sites, but if there is no default ID detection from the parameters, then often hidden under `id`, `v`, `video` and` f`. (IDK, Maybe checking the parameter name [regex101](https://regex101.com/r/V1KHw9/1): `/^((v(ideo)?[-_]?)?(id)?|f)$/`)

**Comment by dstftw** [comment]
video id for generic extractor is nominal.
