### ISSUE TITLE
Can't download PornHub private video even though plays in browser

### ISSUE THREAD

**Issue by mjolnir870** [rg3/youtube-dl#16956]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--no-mtime', '--no-playlist', '--playlist-reverse', '-i
', '-w']
[debug] Command-line args: ['--config-location', 'C:\\Users\\USERNAME\\Scripts\\youtube-dl-ondemand.conf', '--ffmpeg-location', 'C:\\Users\\USERNAME\\Apps\\ffmpeg\\bin\\ffmpeg.exe', '--download-archive', 'V:\\~youtube-dl_history.txt', '-f', 'bestvideo+bestaudio/best', '--write-thumbnail', '--external-downloader', 'C:\\Users\\USERNAME\\Apps\\aria2\\64bit\\aria2c.exe', '--external-downloader-args', '--file-allocation=none -x 4 -k 1M', '-o', 'V:\\%(title)s_%(id)s.%(ext)s', '-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies', 'V:\\cookies.txt', '-v', 'https://www.pornhub.com/view_video.php?viewkey=ph5ad31e0e1c122']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-90960-gbcff983dc3, ffprobe N-90960-gbcff983dc3
[debug] Proxy map: {}
[PornHub] ph5ad31e0e1c122: Downloading webpage
ERROR: ph5ad31e0e1c122: PornHub said: Sorry, but this video is private. You must
 be friends with Alice_coquine to view this video.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\extractor\pornhub.py", line 135, in _real_extract
youtube_dl.utils.ExtractorError: ph5ad31e0e1c122: PornHub said: Sorry, but this
video is private. You must be friends with Alice_coquine to view this video.
```

---

### Description of your *issue*, suggested solution and other information
Trying to download the following link: https://www.pornhub.com/view_video.php?viewkey=ph5ad31e0e1c122.
Test account:
u: testforytdl
p: ger7bra1

The test account is friends with the required account and can play this in a browser.

**Comment by dstftw** [comment]
Pass authenticated cookies from browser and do not pass account credentials.
