### ISSUE TITLE
Multi POV youtube videos?

### ISSUE THREAD

**Issue by Nicks182** [rg3/youtube-dl#16954]
This is not really an issue, I know, but I can't figure out where I can ask this.

Youtube allows streamers that stream together to have multiple POVs in one stream. Example:
https://www.youtube.com/watch?v=xeby6HA076k

For those that don't know: At the bottom right of the player there is an icon that looks like a suitcase with right and left arrow. If you click that you can choose another POV.

Thing is, the URL does not change when you change the POV. Is there any way to get the other POV and download that?

Great project, keep up the good work.

**Comment by dstftw** [comment]
Do you even try what you request before you post?

**Comment by Nicks182** [comment]
If I knew how to do it I would not be asking.
