### ISSUE TITLE
[ProSiebenMaxx] Unable to download JSON metadata

### ISSUE THREAD

**Issue by sp00n** [rg3/youtube-dl#16964]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```>youtube-dl -v https://www.prosiebenmaxx.de/anime/blue-exorcist/video/118-folge-18-orkan-ganze-folge
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.prosiebenmaxx.de/anime/blue-exorcist/video/118-folge-18-orkan-ganze-folge']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-90979-g08032331ac, ffprobe N-90979-g08032331ac
[debug] Proxy map: {}
[prosiebensat1] anime/blue-exorcist/video/118-folge-18-orkan-ganze-folge: Downloading webpage
[prosiebensat1] 5357897: Downloading videos JSON
ERROR: Unable to download JSON metadata: <urlopen error [Errno 11001] getaddrinfo failed> (caused by URLError(gaierror(11001, 'getaddrinfo failed'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\extractor\common.py", line 599, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\utils.py", line 946, in http_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
```

---

I've tried with a version from March before that, which showed the same error. I've also tried to add the cookie from the browser via --add-header "Cookie:xyz", but it didn't help (same error).

**Comment by dstftw** [comment]
Post the output of `nslookup vas.sim-technik.de`.

**Comment by sp00n** [comment]
Hm, indeed, it seems that the Adblock plugin in my LEDE router somehow blocked sim-technik.de. I added `vas.sim-technik.de` to the whitelist and rebooted, and it seems to work now.
