### ISSUE TITLE
Update command returns before completing

### ISSUE THREAD

**Issue by cog-videogames** [rg3/youtube-dl#16978]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### Description of your *issue*, suggested solution and other information

I have a wrapper script that ensures yt-dl is up to date, which does the following on start (once per week):

```bash
echo 'Checking for update...'
youtube-dl --update

echo 'Ensure update is actually complete...'
sleep 10

echo 'Continuing...'
```

I do this because the `--update` command returns too soon. Here is the latest example:

```bash
Checking for update...
Updating to version 2018.07.10 ...
Waiting for file handle to be closed ...
Ensure update is actually complete...        # Note that this line
Updated youtube-dl to version 2018.07.10.    # is before this one!
Continuing...
```

It would be nice if the yt-dl update command waited until it was done before exiting.
Presumably some forked-off process is finishing the job?

This has been reproducible over many updates. Windows 7 on MINGW64 bash.

Apologies if this is already filed; as you can imagine searching for update issues is rough.

**Comment by dstftw** [comment]
That's not possible since youtube-dl.exe is already terminated when this message is printed from a batch file running in background.
