### ISSUE TITLE
...more of an observation

### ISSUE THREAD

**Issue by jimlynnjulian** [rg3/youtube-dl#16981]
I've been  using yt-dl for quite some time now. I use the app often. Several months ago, I first noticed that , almost all, downloads ended with the 'converting malfoemed AAC stream...' caveat.
The conversions always work, so there's no reral problem. But do ALL the videos I downlaod have 'mallformed AAC' streams? Feel free to close this after reading.

Thank you for the software,
Jim Julian

**Comment by dstftw** [comment]
Not all. Only ones downloaded with native hls downloader.
