### ISSUE TITLE
Mediaset Play Italy doesn't work

### ISSUE THREAD

**Issue by Ike348** [rg3/youtube-dl#16995]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl --add-header "User Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" -F 'https://vod05t-mediaset-it.akamaized.net/farmunica/2018/07/234794_1649eeaaa4e7d2/dashrcclean/hd_no_mpl_hbbtv.mpd?hdnts=st=1531839224~exp=1531853654~acl=/farmunica/2018/07/234794_1649eeaaa4e7d2/dashrcclean/hd_no_mpl_hbbtv.mpd~hmac=754c7bfe9d4fc9edfa96f8ca5897977e6b40ff7bb5ec46f2270cf2f94b6b4421' -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--add-header', 'User Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36', '-F', 'https://vod05t-mediaset-it.akamaized.net/farmunica/2018/07/234794_1649eeaaa4e7d2/dashrcclean/hd_no_mpl_hbbtv.mpd?hdnts=st=1531839224~exp=1531853654~acl=/farmunica/2018/07/234794_1649eeaaa4e7d2/dashrcclean/hd_no_mpl_hbbtv.mpd~hmac=754c7bfe9d4fc9edfa96f8ca5897977e6b40ff7bb5ec46f2270cf2f94b6b4421', '-v']
[debug] Adding header from command line option User Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.6.2 (CPython) - Darwin-17.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] hd_no_mpl_hbbtv: Requesting header
WARNING: Falling back on generic information extractor.
[generic] hd_no_mpl_hbbtv: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 599, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Direct video link: https://www.mediasetplay.mediaset.it/video/mondialimediaset/mondiali-francia-croazia-partita-intera_F309072001006401
- Example MPD url: https://vod05t-mediaset-it.akamaized.net/farmunica/2018/07/234794_1649eeaaa4e7d2/dashrcclean/hd_no_mpl_hbbtv.mpd?hdnts=st=1531839224~exp=1531853654~acl=/farmunica/2018/07/234794_1649eeaaa4e7d2/dashrcclean/hd_no_mpl_hbbtv.mpd~hmac=754c7bfe9d4fc9edfa96f8ca5897977e6b40ff7bb5ec46f2270cf2f94b6b4421

---

### Description of your *issue*, suggested solution and other information

The main issue here is of course the 403 Forbidden error. Normally this is not an error due to youtube-dl, because the link is actually unavailable. However, in this instance, **the mpd link downloads both from the browser and from command line with wget, with no additional arguments.** Clearly, something went wrong within youtube-dl.

Note that there is no login required to access the video, just an Italian IP address which can be done with a VPN or probably even a proxy.

**Comment by Ike348** [comment]
I mean I don't really think is a duplicate. There are plenty of sites that youtube-dl doesn't have a plugin for, yet using the "manual method" with m3u8/mpd/f4m/etc links still works. This is more of a case where youtube-dl fails to download an mpd link.

**Comment by bato3** [comment]
@Ike348 
1. valid UA syntax is `User-Agent: M` not `User Agent:M`
2. you should pass cookies
