### ISSUE TITLE
could not send head request and http error 401

### ISSUE THREAD

**Issue by element73** [rg3/youtube-dl#16994]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.



C:\Users\censored\Desktop\youtube-dl>youtube-dl -v https://hls2.videos.sproutvideo.co
m/31b0a8c7e2b3dd5a707caefdd17562dd/fc01da51d04c219899737f860bffcf8e/video/1080.m
3u8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://hls2.videos.sproutvideo.com/31b0a8c7e
2b3dd5a707caefdd17562dd/fc01da51d04c219899737f860bffcf8e/video/1080.m3u8']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 1080: Requesting header
WARNING: Could not send HEAD request to https://hls2.videos.sproutvideo.com/31b0
a8c7e2b3dd5a707caefdd17562dd/fc01da51d04c219899737f860bffcf8e/video/1080.m3u8: H
TTP Error 403: Forbidden
[generic] 1080: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\extractor\common.py", line 599, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- single video: http://indemandcareer.com/blueprint/5-digital-marketing-the-website/
- playlist: Same link as above. Not sure if that is considered a playlist on the right side of the page, but they provide links like a table of contents. Each section leads to a web page that provides the table of contents. And each link/section has at least one video.

---

### Description of your *issue*, suggested solution and other information

**I use a login for the website. If required, just ask.**

Here is the log file: 
[06/17/18 03:45:22] WARNING: Could not send HEAD request to https://hls2.videos.sproutvideo.com/31b0a8c7e2b3dd5a707caefdd17562dd/fc01da51d04c219899737f860bffcf8e/video/1080.m3u8: HTTP Error 403: Forbidden
[06/17/18 03:45:22] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I tried using cookies or login information and it didn't work. Please give me some ideas to try.

**Comment by dstftw** [comment]
Does not open in browser either. Provide source URL.

**Comment by element73** [comment]
source URL? I put down indemandcarrer.com I am trying to view the videos offline when my internet cuts out, or when I am on the go.

**Comment by bato3** [comment]
account-need, duplicate https://github.com/rg3/youtube-dl/issues/16996
