### ISSUE TITLE
Parse the url : https://www.ted.com/talks/alison_ledgerwood_a_simple_trick_to_improve_positive_thinking

### ISSUE THREAD

**Issue by dcdebug** [rg3/youtube-dl#16993]
youtube-dl 's Version 
darrykinger@darrykinger:/usr/share/nginx/html/tvupd$ sudo youtube-dl --version
2018.07.10

When I user the command 
sudo youtube-dl -g -f mp4 https://www.ted.com/talks/alison_ledgerwood_a_simple_trick_to_improve_positive_thinking
Get the Response :
ERROR: An extractor error has occurred. (caused by KeyError(u'nativeDownloads',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Then I Add the argv -v :
darrykinger@darrykinger:/usr/share/nginx/html/tvupd$ sudo youtube-dl -v -g -f mp4 https://www.ted.com/talks/alison_ledgerwood_a_simple_trick_to_improve_positive_thinking
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-g', u'-f', u'mp4', u'https://www.ted.com/talks/alison_ledgerwood_a_simple_trick_to_improve_positive_thinking']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.10
[debug] Python version 2.7.6 (CPython) - Linux-4.4.0-130-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: An extractor error has occurred. (caused by KeyError(u'nativeDownloads',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ted.py", line 131, in _real_extract
    return self._talk_info(url, name)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ted.py", line 184, in _talk_info
    dict) or talk_info['nativeDownloads']
KeyError: u'nativeDownloads'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 515, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'nativeDownloads',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

What happened ?

**Comment by kayb94** [comment]
The video isn't support, as it seems. I don't have the time to look into this right now. But just for you to know: Please do not use 'sudo' for youtube-dl. In general, you should always use command line tools without sudo (full system privileges), if not explicitly required, as anything else makes you more vulnerable to security issues.

Regards

**Comment by yellowming** [comment]
Lao wang ，sixsixsix！

**Comment by bato3** [comment]
@dstftw fixed by cd3a3ff93bd5d6866d3822cb438b0e172ffe4e39
