### ISSUE TITLE
Unauthorized download

### ISSUE THREAD

**Issue by hila3000** [rg3/youtube-dl#17004]
Hi,

I'm trying to download a paid course with account that was provided to me by the company.
When I login to udemy, the url changes to https://mycompanyname.udemy.com but when I go to https://www.udemy.com it works as well.

However, when using youtube-dl, for example this command-
youtube-dl -u hila.f@mycompanyname.com -p "password with space in it" https://www.udemy.com/linux-administration-bootcamp/learn/v4/content --verbose

I get this error-
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.udemy.com/linux-administration-bootcamp/learn/v4/content', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.10
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-693.el7.x86_64-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 501, in extract
    self.initialize()
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 405, in initialize
    self._real_initialize()
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/udemy.py", line 151, in _real_initialize
    self._login()
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/udemy.py", line 191, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

or this command-
youtube-dl -u hila.f@mycompanyname.com -p "password with space in it" https://mycompanyname.udemy.com/linux-administration-bootcamp/learn/v4/content --verbose

I get this error-
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://mycompanyname.udemy.com/linux-administration-bootcamp/learn/v4/content', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.10
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-693.el7.x86_64-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: none
[debug] Proxy map: {}
[generic] content: Requesting header
WARNING: Could not send HEAD request to https://mycompanyname.udemy.com/linux-administration-bootcamp/learn/v4/content: HTTP Error 403: Unauthorized
[generic] content: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 599, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Is it because my account is not private, but from my company?
or another reason?

Please advise.

Thanks,
Hila

**Comment by dstftw** [comment]
Not supported.
