### ISSUE TITLE
Downloading a video by ID that starts with "-"

### ISSUE THREAD

**Issue by SirJosh3917** [rg3/youtube-dl#17012]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
C:\x>youtube-dl "-CQ0I7S19jw"
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: -Q

C:\x>
```

### Description of your *issue*, suggested solution and other information

If I supply a youtube video id prefixed with a `-`, it interprets it as a command line argument. e.g. `-CQ0I7S19jw`

Solution: If it has quotes around it, don't interpret the first `-` as a command line argument
Temporary solution: prefix the id with the youtube URL

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#how-do-i-download-a-video-starting-with-a--
