### ISSUE TITLE
youtube_dl not getting imported

### ISSUE THREAD

**Issue by GreenInkling** [rg3/youtube-dl#17015]
I tried to import youtube_dl on Python 3.6, and I get this error:
`>>> import youtube_dl
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'`
How do I get my Python to import `youtube_dl`?

**Comment by dstftw** [comment]
Install it first obviously.

**Comment by GreenInkling** [comment]
Already installed.

**Comment by FranzSkuffka** [comment]
I actually have the same problem.

**Comment by FranzSkuffka** [comment]
1. Uninstalling
2. removing the executable by doing ```rm `which youtube-dl` ```
3. installing it again
fixed it for me

**Comment by rautamiekka** [comment]
Best to use PIP and thus PyPi.

**Comment by mirelon** [comment]
Installed using the first commands in the README:
```sh
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```

and bumped into this issue.

Tried the 2nd option from the README, but failed:
```
$ sudo -H pip install youtube-dl
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
ChatGPT suggested:
```sh
sudo apt install pipx
pipx install youtube-dl
```
which worked.

**Comment by greeeen-dev** [comment]
Thanks for the reply, it gave me a notification on GitHub which reminded me of how stupid I was when I made this issue LMAO

I don't use youtube-dl anymore, but I'm pretty sure I've fixed it since I opened this issue. Still kind of nice (and embarrassing) being reminded me of my past when I was just complete ass at programming.

Also, for the externally-managed-environment issue (this wasn't related to my original issue, as I was using macOS then): I'd suggest just using a virtualenv like the output said, it's quite nice using them especially when I need separate packages for each project.

**Comment by rautamiekka** [comment]
> Also, for the externally-managed-environment issue (this wasn't related to my original issue, as I was using macOS then): I'd suggest just using a virtualenv like the output said, it's quite nice using them especially when I need separate packages for each project.

**_When_** you need separate packages.

**Comment by dirkf** [comment]
>... which worked.

... except that it installed an ancient broken version. See #30839 and also https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-2715887479, eg.
