### ISSUE TITLE
BBC iPlayer Radio

### ISSUE THREAD

**Issue by klop422** [rg3/youtube-dl#17022]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
c:\Users\PDEM\Documents>youtube-dl --verbose https://www.bbc.co.uk/radio/play/b0b9z4yl
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.bbc.co.uk/radio/play/b0b9z4yl']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-87257-g8e17cd2, ffprobe N-87257-g8e17cd2
[debug] Proxy map: {}
[bbc] b0b9z4yl: Downloading webpage
ERROR: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\extractor\bbc.py", line 1073, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\extractor\common.py", line 972, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

---
This is an example of a page I can't get to download despite having been able to download from iPlayer Radio a number of moths ago.
https://www.bbc.co.uk/radio/play/b0b9z4yl
---

Although BBC iPlayer Radio previously worked (and regular iPlayer also works currently), it appears the BBC have changed the format for iPlayer Radio, and so, as far as I can work out, you can't currently download files from iPlayer Radio.

**Comment by Vangelis66** [comment]
The BBC are planning changes to iPlayer Radio API and have piloted them in their BBC Radio 3 offerings; the old URIs of the format 
`https://www.bbc.co.uk/programmes/<pid>` 
now redirect in a browser to a new template: 
`https://www.bbc.co.uk/radio/play/<pid>`
which involves a redesigned embedded web player for radio (accessible freely overseas, but requires log-in within the UK). 

yt-dl can't yet parse the new format, so if you feed it that, you get the error you reported; but **the old format is still interchangeable** as far as yt-dl is concerned, so to fetch your Proms  programme just use 

`youtube-dl "https://www.bbc.co.uk/programmes/b0b9z4yl" (+ other optional arguments of yours...)`

> you can't currently download files from iPlayer Radio.

... False generalisation; currently _only Radio 3 affected_ (with workaround available); unless you think of iPlayer Radio as R3 only... Tsk...

**Comment by klop422** [comment]
Ah! Apologies, I honestly only really use Radio 3 (sometimes Radio 4) and it never occurred to me that they would change the system for only one part of the site. Probably why I'm not a software tester!Well, thank you for your help. That said, are yt-dl intending to try and add support for this, as it will likely become relevant in the future? 
 
  On Sat, 21 Jul 2018 at 3:30, Vangelis66<notifications@github.com> wrote:   
The BBC are planning changes to iPlayer Radio API and have piloted them in their BBC Radio 3 offerings; the old URIs of the format
https://www.bbc.co.uk/programmes/<pid>
now redirect in a browser to a new template:
https://www.bbc.co.uk/radio/play/<pid>
which involves a redesigned embedded web player for radio (accessible freely overseas, but requires log-in within the UK).

yt-dl can't yet parse the new format, so if you feed it that, you get the error you reported; but the old format is still interchangeable as far as yt-dl is concerned, so to fetch your Proms programme just use

youtube-dl "https://www.bbc.co.uk/programmes/b0b9z4yl" (+ other optional arguments of yours...)


you can't currently download files from iPlayer Radio.


... False generalisation; currently only Radio 3 affected (with workaround available); unless you think of iPlayer Radio as R3 only... Tsk...
