### ISSUE TITLE
[issue] when i download a video and convert it to mp3

### ISSUE THREAD

**Issue by thhunder** [rg3/youtube-dl#17038]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
<start-debug>
****@******$ youtube-dl -v -x --audio-format mp3 --audio-quality 320k https://youtu.be/lI3jlheDLgg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-x', u'--audio-format', u'mp3', u'--audio-quality', u'320k', u'https://youtu.be/lI3jlheDLgg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-7-amd64-x86_64-with-debian-9.5
[debug] exe versions: ffmpeg 3.2.11-1, ffprobe 3.2.11-1
[debug] Proxy map: {}
[youtube] lI3jlheDLgg: Downloading webpage
[youtube] lI3jlheDLgg: Downloading video info webpage
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {22} signature length 44.40, html5 player None
[youtube] lI3jlheDLgg: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vfl2WjsTu/en_US/base.js
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {43} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {18} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {36} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {17} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {137} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {248} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {136} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {247} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {135} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {244} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {134} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {243} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {133} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {242} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {160} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {278} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {140} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {171} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {249} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {250} signature length 44.40, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {251} signature length 44.40, html5 player None
[debug] Invoking downloader on u'https://r4---sn-1gieen7e.googlevideo.com/videoplayback?ei=0CtUW42sNcrFgAeenp-ICA&id=o-ABsjZQeMUzVvjt7-unwlUb-bwtlO2GHGJFtebzx_cxec&lmt=1481542237681975&fvip=6&ip=185.73.242.25&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mv=u&mt=1532242523&ms=au%2Conr&source=youtube&mime=audio%2Fwebm&keepalive=yes&key=yt6&requiressl=yes&clen=3568262&mn=sn-1gieen7e%2Csn-axq7sn76&mm=31%2C26&itag=251&ipbits=0&gir=yes&pl=24&expire=1532264497&dur=213.841&c=WEB&signature=0C0761569D864253C3D30B35E39145FA08BC622D.4ACC6655BD21EFF16B70A0C5CA5DF9485358485C&ratebypass=yes'
[download] Destination: Groove Coverage - 7 Years & 50 Days (Official Video)-lI3jlheDLgg.webm
[download] 100% of 3.40MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams 'file:Groove Coverage - 7 Years & 50 Days (Official Video)-lI3jlheDLgg.webm'
[ffmpeg] Destination: Groove Coverage - 7 Years & 50 Days (Official Video)-lI3jlheDLgg.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:Groove Coverage - 7 Years & 50 Days (Official Video)-lI3jlheDLgg.webm' -vn -acodec libmp3lame '-b:a' 320k 'file:Groove Coverage - 7 Years & 50 Days (Official Video)-lI3jlheDLgg.mp3'
Deleting original file Groove Coverage - 7 Years & 50 Days (Official Video)-lI3jlheDLgg.webm (pass -k to keep)
****@******$ youtube-dl --version
2018.07.21
<end-debug>

---
Hey guys,
i hope that i do this correctly it's my first issue-/bug-report so don't be too hard to me and my bad english :)
i was trying to download and convert a youtube-video to mp3 for a friend it's an old song. and after my command with youtube-dl, wich i'm using verbosly, i got the warning message you see above. I never got a warning or error output before so i hope that i can help with this posting/report your work here is so nice and i love you for it!
Thx for your attention to this report :-)

**Comment by thhunder** [comment]
i got this by downloading that video to a song with other songs too in the last days but now i can't repoduce it anymore so maybe it was a temporary issue i rebootet my linux-server one time yesterday maybay that helped or workedarround by itself i don't know what happend or what the failure was....
so thx anyway for help

**Comment by visi0nary** [comment]
Works fine here. Maybe you should close the issue @thhunder ?

**Comment by thhunder** [comment]
Yes, i should close it... right so i'm sorry :-)
