### ISSUE TITLE
External Downloader option is ignored on youtube, Tried different downloaders

### ISSUE THREAD

**Issue by Raviu8** [rg3/youtube-dl#17039]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v --external-downloader axel 'https://www.youtube.com/watch?v=LRrYAkI1UtU'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--external-downloader', u'axel', u'https://www.youtube.com/watch?v=LRrYAkI1UtU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.14 (CPython) - Linux-4.17.7-lp150.2-default-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[youtube] LRrYAkI1UtU: Downloading webpage
[youtube] LRrYAkI1UtU: Downloading video info webpage
[youtube] LRrYAkI1UtU: Downloading MPD manifest
[youtube] LRrYAkI1UtU: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r5---sn-vgqsrnez.googlevideo.com/videoplayback/id/2d1ad802423552d5/itag/266/source/youtube/requiressl/yes/mn/sn-vgqsrnez,sn-vgqskn76/mm/31,29/mv/m/ms/au,rdu/ei/ZV1UW-GFE8r_gQeMpLWgDA/pl/19/initcwndbps/1086250/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/18776160/lmt/1488563289448019/dur/27.579/fvip/6/mt/1532255511/disable_polymer/true/ip/104.237.193.26/ipbits/0/expire/1532277189/sparams/ip,ipbits,expire,id,itag,source,requiressl,mn,mm,mv,ms,ei,pl,initcwndbps,ratebypass,mime,otfp,gir,clen,lmt,dur/signature/FE85057B21FEBF72C9A0D11C884BEFE667F802.4AB962FDD002EC74A9F931098323CC8F8DE815AC/key/dg_yt0/'
[dashsegments] Total fragments: 6
[download] Destination: How to turn on back light keyboard on linux-LRrYAkI1UtU.f266.mp4
```

### Description of your *issue*, suggested solution and other information

I've tried to run the latest version of youtube-dl with different external-downloader options, but it ignores all of them. Tried aria2c, axel, wget and curl. 
= Download speed is very low. I've copied the URL displayed with `-v` argument and tried downloading it with axel or aria2c and could 6x the speed.
= Examining `ps -ef` found that youtube-dl doesn't execute any command - no child processes.
= I've, also, examined `lsof -n -p PID-of-Youtube-dl` and found that it's establishing the connection itself. And no indication of opening any external downloader files, libs, or connections.

I've searched the issues and found that you mentioned aria2c is not supporting HLS. Is this URL an HLS? Any way `youtube-dl -h` states `Currently supports aria2c,avconv,axel,curl,ffmpeg,httpie,wget`

Also, I've tried downloading the same URL with aria2c and axel and it's working very well.

**Comment by dstftw** [comment]
External downloaders do not support segmented DASH.

**Comment by Raviu8** [comment]
How can I avoid segmented DASH?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#format-selection

**Comment by Raviu8** [comment]
Thanks,
I've add `--youtube-skip-dash-manifest` to my command using `axel` downloader and it's working very well now.
