### ISSUE TITLE
Can't download some ooyala videos

### ISSUE THREAD

**Issue by Bunnicula2** [rg3/youtube-dl#17035]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['ooyala:hhetj0zje6rspfaezli6vmih7r2bqnlw', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.07.21
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 2.8.4
[debug] Proxy map: {}
[Ooyala] hhetj0zje6rspfaezli6vmih7r2bqnlw: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\__init__.py", line 472, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\__init__.py", line 462, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 2001, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\ooyala.py", line 170, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\ooyala.py", line 28, in _extract
IndexError: list index out of range

```

---

### Description of your *issue*, suggested solution and other information

I can download some ooyala videos using `ooyala:`, but some give me this error although they can be viewed onsite (for example this one can be found [here on accuweather](https://www.accuweather.com/en/videos/astronomer-captures-international-space-station-transiting-past-the-sun/hhetj0zje6rspfaezli6vmih7r2bqnlw)).

**Comment by remitamine** [comment]
```
youtube-dl ooyala:hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw
[Ooyala] hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw: Downloading JSON metadata
[Ooyala] hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw: Downloading JSON metadata
[Ooyala] hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw: Downloading MPD manifest
[Ooyala] hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw: Downloading m3u8 information
[download] Destination: Astronomer captures International Space Station transiting past the Sun-hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2621k  100 2621k    0     0   168k      0  0:00:15  0:00:15 --:--:--  180k
[curl] Downloaded 2684527 bytes
[download] 100% of 2.56MiB in 00:15
```

**Comment by Bunnicula2** [comment]
Hmmm, I've tried it again now
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'ooyala:hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.07.21
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 2.8.4
[debug] Proxy map: {}
[Ooyala] hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw: Downloading JSON metadata
[Ooyala] hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw: Downloading JSON metadata
[Ooyala] hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw: Downloading MPD manifest
[Ooyala] hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://ak-accuweather.akamaized.net/efdfceaa-55bc-4364-97e2-b364107f932b/hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw.ism/QualityLevels(1811000)/Manifest(video,format=m3u8-aapl)'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3
[download] Destination: Astronomer captures International Space Station transiting past the Sun-hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw.fhls-1996.mp4
[download] 100% of 2.47MiB in 00:00
[debug] Invoking downloader on 'http://ak-accuweather.akamaized.net/efdfceaa-55bc-4364-97e2-b364107f932b/hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw.ism/QualityLevels(127000)/Manifest(aac_eng_2_127_2_1,format=m3u8-aapl)'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3
[download] Destination: Astronomer captures International Space Station transiting past the Sun-hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw.fhls-137.mp4
[download] 100% of 189.10KiB in 00:00
[ffmpeg] Merging formats into "Astronomer captures International Space Station transiting past the Sun-hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:Astronomer captures International Space Station transiting past the Sun-hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw.fhls-1996.mp4" -i "file:Astronomer captures International Space Station transiting past the Sun-hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw.fhls-137.mp4" -c copy -map "0:v:0" -map "1:a:0" "file:Astronomer captures International Space Station transiting pastthe Sun-hheTJ0ZjE6rspfaEzlI6VMiH7R2BqNlw.temp.mp4"
ERROR: Conversion failed!
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 2047, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\postprocessor\ffmpeg.py", line 479, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\postprocessor\ffmpeg.py", line 204, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```
This happened to me once before, yesterday. I get three MP4 files, one of which is video, one is audio and one is garbage. I can combine video and audio into a complete file manually with mkvmerge. This could be due to my old ffmpeg version.

After downloading one video which failed gracefully like this yesterday, I had three videos fail with IndexError. Maybe this is some form of throttling?

I've now downloaded the space station video several times (deleting the MP4 files each time), but I can't download any other videos from AccuWeather. Can you try going to AccuWeather (e.g. [here](https://www.accuweather.com/en/videos/drivers-plow-through-severe-flood-in-savannah-georgia/ewnxlzzje6zh_9t_mzckfg81edfnqw4t)) and downloading at least several videos? (the video id is always at the end of the URL)

**Comment by remitamine** [comment]
> This could be due to my old FFmpeg version.

yes, it is.
> (the video id is always at the end of the URL)

AccuWeather converts Ooyala id into lowercase, instead use the actual Ooyala id, in your example(https://www.accuweather.com/en/videos/drivers-plow-through-severe-flood-in-savannah-georgia/ewnxlzzje6zh_9t_mzckfg81edfnqw4t) the actual id is `EwNXlzZjE6zh_9t_MzckFG81edfNQw4t` not `ewnxlzzje6zh_9t_mzckfg81edfnqw4t`.

also, did you try to use AccuWeather URLs directly with `youtube-dl`, one of the Ooyala patterns is present in the source of the web pages(OO.Player.create) and should be matched by `youtube-dl`(can't test it locally).

**Comment by Bunnicula2** [comment]
Indeed, you're right. I wonder how I didn't notice that. The URL did display in mixed case at least once since I could download it, but I'm getting invalid lowercase URLs now...

I get a different error trying to download from AccuWeather directly, I'll open another issue for that.
