### ISSUE TITLE
reddit videos downloading without audio

### ISSUE THREAD

**Issue by kyleratti** [rg3/youtube-dl#17040]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.21*
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Question

---

### Full verbose output

```
System config: []
mirrorrequestscanner.ts:29
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--dump-json', u'--format=mp4', u'--prefer-ffmpeg', u'--merge-output-format=mp4', u'--hls-prefer-ffmpeg', u'-v', u'https://v.redd.it/0rg5u4f2t3b11']
[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.10 (CPython) - Darwin-17.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1
[debug] Proxy map: {}
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

I have also tried appending `/DASHPlaylist.mpd` to the `v.redd.it` URL as suggested in #13847 but still end up with a video that has no sound:

```
System config: []
mirrorrequestscanner.ts:29
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--dump-json', u'--format=mp4', u'--prefer-ffmpeg', u'--merge-output-format=mp4', u'--hls-prefer-ffmpeg', u'-v', u'https://v.redd.it/0rg5u4f2t3b11/DASHPlaylist.mpd']
[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.10 (CPython) - Darwin-17.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1
[debug] Proxy map: {}
```

Not totally sure where I am going wrong here, but I'd love some help!

**Comment by dstftw** [comment]
You are requesting video only format. Don't touch `--format` if you have no idea what are you doing.

**Comment by kyleratti** [comment]
@dstftw A little rude, but I am confused because every other video service seems to work fine except for v.redd.it.

**Comment by kyleratti** [comment]
Oh - is this due to reddit separating its audio and video streams?

**Comment by dstftw** [comment]
Reddit serves only audio-only and video-only files. As already said you are requesting video-only part without specifying audio and muxing.

**Comment by kyleratti** [comment]
I didn't mean that comment as in the library was malfunctioning, I was more-so asking if that's the reason I'm seeing the behavior I noted above.

I'm sure you get a ton of stupid requests all day long and I'm sure that's overwhelming as a volunteer maintaining a large public project, but you're coming off overly-aggressive on this side of the screen. I read the documentation on `--format` but was not clear that only specifying a video format meant it would ignore audio completely. Sorry.

**Comment by dstftw** [comment]
Well, sorry if this sounds too rude but this is the only effective way to force "copy-paste" users (wich is the majority) to use the defaults instead of some flawed broken command lines copied from some fancy blogs on the internet. The defaults work properly most of the time, if something does not work chances are your format selection is incorrect.

**Comment by sergiotapia** [comment]
This is still an issue. For example:

`youtube-dl https://www.reddit.com/r/Kanye/comments/9i3952/ladies_and_gentlemen/`

On window 10, I get two files. a m4a and a mp4.
