### ISSUE TITLE
streamcloud.eu: Error 403 (Missing Referer)

### ISSUE THREAD

**Issue by wmbr** [rg3/youtube-dl#17054]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Recently the video hosting platform _streamcloud.eu_ started requiring the HTTP Referer Header to be set, thus _youtube-dl_ currently fails with

> ERROR: unable to download video data: HTTP Error 403: Forbidden

It seems to me this should be fixable by adding an extra entry

`'http_headers': {
                'Referer': video_id,
}`

to the return value of [StreamcloudIE._real_extract](https://github.com/rg3/youtube-dl/blob/631f93ee2d5dfe5a90da38d293159670ada4d95e/youtube_dl/extractor/streamcloud.py#L31)

**Comment by balrok** [comment]
I can confirm, that your solution solves the problem

**Comment by quazgar** [comment]
Workaround for those with an older version:  Set this header on the command line.

`youtube-dl --add-header Referer:abcd1234 http://streamcloud.eu/abcd1234/move_title.mkv.html`
