### ISSUE TITLE
[Twitter] Some videos stop after 3 seconds (but audio continues)

### ISSUE THREAD

**Issue by jbrennan** [rg3/youtube-dl#17089]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v https://twitter.com/Hansenq/status/990054778318110720
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://twitter.com/Hansenq/status/990054778318110720']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.10 (CPython) - Darwin-17.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, phantomjs 2.0.0
[debug] Proxy map: {}
[twitter] 990054778318110720: Downloading webpage
[twitter:card] 990054778318110720: Downloading webpage
[twitter:card] 990054778318110720: Downloading guest token
[twitter:card] 990054778318110720: Downloading JSON metadata
[twitter:card] 990054778318110720: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://video.twimg.com/ext_tw_video/990052738607206400/pu/pl/720x1280/sUeB_Q3DbNxa8JBS.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 15
[download] Destination: Hansen Qian - Geokit, by @rsnous   Overlay transit and demographic information-990054778318110720.mp4
[download] 100% of 7.09MiB in 00:03
[debug] ffmpeg command line: ffprobe -show_streams 'file:Hansen Qian - Geokit, by @rsnous   Overlay transit and demographic information-990054778318110720.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Hansen Qian - Geokit, by @rsnous   Overlay transit and demographic information-990054778318110720.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Hansen Qian - Geokit, by @rsnous   Overlay transit and demographic information-990054778318110720.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Hansen Qian - Geokit, by @rsnous   Overlay transit and demographic information-990054778318110720.temp.mp4'
```

### Description of your *issue*, suggested solution and other information

I use `youtube-dl` mostly to save videos from Twitter, and it mostly works well for me.

However I’ve noticed on occasion when I download a video the following happens:

1. I go to download the video, using all the defaults (eg `youtube-dl  https://twitter.com/Hansenq/status/990054778318110720`)

2. The file successfully downloads to my Mac.

3. When I go to play the video (either by using Quicklook in Finder, or opening it in Quicktime), the video displays the correct duration and plays, **but after about 3 seconds, the video pauses** (and the audio continues to play).

So it seems like sometimes the video stream is just dropped or something (I’m not really sure what’s going on). This does not **always** happen with twitter videos (sometimes they download and play completely fine), but it does happen from time to time (as is happening for me and the above link). Ideally, this wouldn’t happen and the complete video + audio streams would play for all twitter videos.

**Comment by dstftw** [comment]
Quicktime issue. Use normal players.

**Comment by jbrennan** [comment]
Thanks for the friendly response
