### ISSUE TITLE
question about audio quality and --metadata-from-title

### ISSUE THREAD

**Issue by Skarbor9** [rg3/youtube-dl#17092]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

What exactly hides behind --audio-quality 0-9 levels? What exactly is 0 and default 5 level, or should I choose sampling rate and bitrate by myself? I'm talking about vorbis -> flac conversion. 

Is there any list with all --postprocessor-args possible?

Is that correct command for metadata from title? Do I need a path to the folder from --output, or these strings only?:
--metadata-from-title "%(title)s - %(acodec)s-%(abr)s-%(vcodec)s-%(resolution)s-%(format)s-%(like_count)s-%(dislike_count)s-%(view_count)s-%(upload_date)s-%(uploader)s-%(uploader_id)s.%(ext)s"

**Comment by dstftw** [comment]
`--audio-quality` is mapped to `ffmpeg`'s `-qscale:a` and it's format specific. Consult ffmpeg doc for more info on it's values.
`--postprocessor-args` is postprocessor specific.
`--metadata-from-title` is for fetching additional metadata from title, it has nothing to do with folders.

**Comment by Skarbor9** [comment]
There is nothing about values here https://ffmpeg.org/ffmpeg.html , only information that something like -qscale exists. 
My example of --metadata-from title is correct, or not?

**Comment by ravkr** [comment]
just learn how to use google....
and how to use markdown on github: it's `[x]`, not `[ x]`
- [x] good
- [ x] bad
- [x ] bad

**Comment by rautamiekka** [comment]
Here's the full FFmpeg documentation: https://www.ffmpeg.org/ffmpeg-all.html
