### ISSUE TITLE
Some info not included/clarified in documentation

### ISSUE THREAD

**Issue by Nicks182** [rg3/youtube-dl#17095]
I downloaded a youtube stream and after it was done I had downloaded more than 10Gb. The reason is that the video was a Multi-POV stream and youtube-dl download all 3 POV which is not what I wanted.

Searching for Multi pov answers has returned only results about multiple connections or questions about multi threaded downloading for playlists. Maybe my Google-Fu sucks, but I have not manage to find any info relating to multi-POV youtube streams specifically.

After a lot of trail and error and using much of my data cap for testing, I finally figured out how to handle multi-pov videos from youtube... at least I think I do.

1. You need to handle Multi-POV like a playlist. 
2. Adding --no-playlist to the command makes it only download the main POV.
3. If you want to download only specific POV, I believe you use the --playlist-items command. I have not tested this though... used to much cap as it is.

I know for many this might be obvious, but because of the difference in wording, for many people it's not. The first place I looked was the **Video Selection** section in the documentation and it didn't occur to me until later that maybe Multi-POV is like a playlist. I've asked about multi-pov before and just got a snide response which was nothing less than a waste of a few bytes on a data server somewhere.

I realize the devs are busy and I'm sorry to bother you all with this, but just a few notes in the documentation would:
1. Save less tech savvy people tons of headache (and in my case saved 15Gb of my cap)
2. Stop people who actually do work through the docs from having to create new github issues.

**This is a fantastic project and I would love to see it more accessible to more people. If I wasn't so desperate to get this working, I would have given up after not finding the answer in the documentation. Most people would assume if something is not in the documentation, then it can't do it.**

Kind Regards

**Comment by dstftw** [comment]
When downloading multifeed playlist youtube-dl **clearly tells** you what to do if you don't want to download all videos. Just bother to read the output.
```
...
[youtube] Downloading multifeed video (xeby6HA076k, D8kRdOmN1fM) - add --no-playlist to just download video xeby6HA076k
...
```
Some goes for all other cases when single URL represents playlist and videos at the same time.
