### ISSUE TITLE
Using youtube_dl.YoutubeDL to download audio only (options help)

### ISSUE THREAD

**Issue by heyitswither** [rg3/youtube-dl#17103]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

I am trying to use youtube_dl.YoutubeDL to download the audio track of a video.

```json
{
    "default_search": "ytsearch",
    "quiet": true,
    "restrictfilenames": true,
    "format": "bestaudio",
    "postprocessors": [{
        "key": "FFmpegExtractAudio",
        "preferredcodec": "wav",
        "preferredquality": "48000",
    }]
}
```

I believe the options are the only thing causing my problem, the video is downloaded fine. See ffprobe of the downloaded file below.

```
Input #0, matroska,webm, from 'Electric_Light_Orchestra___Mr__Blue_Sky__Audio.wav':
  Metadata:
    encoder         : google/video-file
  Duration: 00:05:04.10, start: -0.007000, bitrate: 129 kb/s
    Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
```

*The .wav was added by me.*

**Comment by dstftw** [comment]
Post the complete verbose output.
