### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by Leolexis** [rg3/youtube-dl#17105]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.07.29
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

The issue is I keep getting the parse error with every website I'm trying to use

C:\Users\я\Desktop\dl>youtube-dl --all-subs --skip-download --hls-prefer-native http://www.nbc.com/world-of-dance/video/the-qualifiers-5/3749244
[NBC] 3749244: Downloading JSON metadata
[ThePlatform] 3749244: Downloading SMIL data
ERROR: 3749244: Failed to parse XML  (caused by ParseError('not well-formed (invalid token): line 8, column 42',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\я\Desktop\dl>youtube-dl --all-subs --skip-download https://www.cbs.com/shows/elementary/video/qzV5zwpnktuopB_ERsrYvoUL4GGFCX9C/elementary-meet-your-maker/
[CBS] qzV5zwpnktuopB_ERsrYvoUL4GGFCX9C: Downloading XML
ERROR: qzV5zwpnktuopB_ERsrYvoUL4GGFCX9C: Failed to parse XML  (caused by ParseError('not well-formed (invalid token): line 8, column 42',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Any help?

**Comment by bato3** [comment]
Works for me.

iff still don't work for you use `--write-pages` and try find reason in last file: `Saving request to: ` 
(or paste content here https://pastebin.com/)

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--all-subs', u'--skip-download', u'--hls-prefer-native', u'http://www.nbc.com/world-of-dance/video/the-qualifiers-5/3749244', u'--proxy', u'***', u'-v']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2018.07.29
[debug] Git HEAD: b50478675
[debug] Python version 2.7.14 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, phantomjs 2.1.1
[debug] Proxy map: {u'***'}
[NBC] 3749244: Downloading JSON metadata
[ThePlatform] 3749244: Downloading SMIL data
[ThePlatform] 3749244: Downloading m3u8 information
[ThePlatform] 3749244: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: The Qualifiers 5-3749244.en.tt
```

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--all-subs', u'--skip-download', u'--proxy', u'***', u'-v', u'https://www.cbs.com/shows/elementary/video/qzV5zwpnktuopB_ERsrYvoUL4GGFCX9C/elementary-meet-your-maker/']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2018.07.29
[debug] Git HEAD: b50478675
[debug] Python version 2.7.14 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, phantomjs 2.1.1
[debug] Proxy map: {***}
[CBS] qzV5zwpnktuopB_ERsrYvoUL4GGFCX9C: Downloading XML
[CBS] qzV5zwpnktuopB_ERsrYvoUL4GGFCX9C: Downloading StreamPack SMIL data
[CBS] qzV5zwpnktuopB_ERsrYvoUL4GGFCX9C: Downloading m3u8 information
[CBS] qzV5zwpnktuopB_ERsrYvoUL4GGFCX9C: Downloading RTMP SMIL data
[CBS] qzV5zwpnktuopB_ERsrYvoUL4GGFCX9C: Downloading HLS_AES SMIL data
[CBS] qzV5zwpnktuopB_ERsrYvoUL4GGFCX9C: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[CBS] qzV5zwpnktuopB_ERsrYvoUL4GGFCX9C: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Elementary - Meet Your Maker-qzV5zwpnktuopB_ERsrYvoUL4GGFCX9C.en.ttml
```

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.
