### ISSUE TITLE
VirusTotal false positives only after downloading Windows exes?

### ISSUE THREAD

**Issue by veyronworld** [rg3/youtube-dl#17114]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I downloaded the Windows exe from [the link in the Github Readme](https://yt-dl.org/latest/youtube-dl.exe) and also from the [youtube-dl Download Page](https://yt-dl.org/downloads/2018.07.29/youtube-dl.exe). I usually run the exe file through VirusTotal before downloading and [both](https://www.virustotal.com/#/url/04f7b669effb24be2d52aad72787778e31e4af30afdf181b174a3191704b7d0f/detection) of [them](https://www.virustotal.com/#/url/fd521dc5a897094e3448f4e669f99e2012b9f2c892ee03ae21003a737c4d19a3/detection) came out clean.

However, after I downloaded them, I just ran the exe file through VirusTotal again via uploading it and got what I assume to be [3 false positive results](https://www.virustotal.com/#/file/acd5e953ee1852fa8aca34a69b68226aba8945ab27242fd9291522ce14158731/detection).

I have both Kaspersky Total Security and Malwarebytes installed on one PC, with Avast and Malwarebytes installed on another PC (both running Windows 10). Neither one was infected with anything, and have never been infected with anything AFAIK, and I run them at more thorough levels of treatment than they should, so I'm surprised that nothing comes up. I even ran scans using all of them on both PC's to make sure, with nothing wrong coming up. I should also note this regardless of the browser used: Opera, Firefox, Chrome, or Edge

All of the hashes are the same and correspond to the same SHA256 hash of the 2018.07.29 exe file on the youtube-dl Download Page as of this moment:
**acd5e953ee1852fa8aca34a69b68226aba8945ab27242fd9291522ce14158731**

I just wanted to ask if anyone has any idea why this would happen?

**Comment by dstftw** [comment]
Happen what? False positives is a common thing for AV. Ask these AV engines why.

**Comment by veyronworld** [comment]
I understand that. I meant that, what could possibly change in the file that would trigger a false positive after I've downloaded it to my system when it's clean?
