### ISSUE TITLE
SonyLIV 403 on video download

### ISSUE THREAD

**Issue by theincognito-inc** [rg3/youtube-dl#17121]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
D:\youtube-dl>python -m youtube_dl --no-geo-bypass -v -f best https://www.sonyliv.com/details/clips/5815995594001/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-geo-bypass', '-v', '-f', 'best', 'https://www.sonyliv.com/details/clips/5815995594001/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.07.29
[debug] Git HEAD: 19b9de13c
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg N-91398-gd08d4a8c73, ffprobe N-91398-gd08d4a8c73, phantomjs 2.1.1
[debug] Proxy map: {}
[brightcove:new] ref:5815995594001: Downloading webpage
[brightcove:new] ref:5815995594001: Downloading JSON metadata
[brightcove:new] ref:5815995594001: Downloading m3u8 information
[brightcove:new] ref:5815995594001: Downloading m3u8 information
[brightcove:new] ref:5815995594001: Downloading m3u8 information
[brightcove:new] ref:5815995594001: Downloading m3u8 information
[brightcove:new] ref:5815995594001: Downloading m3u8 information
[brightcove:new] ref:5815995594001: Downloading m3u8 information
[brightcove:new] ref:5815995594001: Downloading MPD manifest
[brightcove:new] ref:5815995594001: Downloading MPD manifest
[debug] Invoking downloader on 'https://bcboltsony-a.akamaihd.net/media/v1/pmp4/static/clear/5182475815001/c80e487e-de6c-4740-ac7a-20ac69d623d7/86d20958-bf0f-4481-8874-9c649833d06e/main.mp4?akamai_token=exp=1535477482~acl=/media/v1/pmp4/static/clear/5182475815001/c80e487e-de6c-4740-ac7a-20ac69d623d7/86d20958-bf0f-4481-8874-9c649833d06e/main.mp4*~hmac=e621beb12aa5475e7426dc10cf872b9e7371326cdcb67f45069a75844e61831c'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "D:\youtube-dl\youtube_dl\YoutubeDL.py", line 1908, in process_info
    success = dl(filename, info_dict)
  File "D:\youtube-dl\youtube_dl\YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "D:\youtube-dl\youtube_dl\downloader\common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "D:\youtube-dl\youtube_dl\downloader\http.py", line 341, in real_download
    establish_connection()
  File "D:\youtube-dl\youtube_dl\downloader\http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "D:\youtube-dl\youtube_dl\YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Hi, the video is playable through the browser. No, this is not a premium video.
Please note, all the file formats are listed using the -F argument. Only on trying to download, this error occurs.
Please help.

**Comment by theincognito-inc** [comment]
@dstftw @remitamine

**Comment by theincognito-inc** [comment]
@remitamine Hi. I am sorry if this is a noob question, but why the tag? I mean,I can play the video via my Firefox, so certainly, it's not geo-restricted to me. Or you added the tag for something else?
Again,really sorry if it's stupid.

**Comment by bato3** [comment]
@theincognito-inc https://screenshots.firefox.com/mMWXdLIoEohEWt0N/www.sonyliv.com

I'm thinking different streaming servers, different security

```
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://manifest.prod.boltdns.net/manifest/v1/hls/v5/aes128/5182475815001/c80e487e-de6c-4740-ac7a-20ac69d623d7/13fbfa4d-ad82-4e6c-8c00-a5d986e12f82/10s/rendition.m3u8?fastly_token=NWI4NTk4ODZfNzFhMzJmN2U5MDMxY2ExNWQ3MmEwMWRhZGFmNmM2MzQwZWI1MDVhM2RhZDJlYTA3N2RhY2YzZmFiNDMzYzkyOQ%3D%3D'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 775
[download] Destination: WWE RAW - Full Episode - 31st July, 2018-ref -5815995594001.fhls-1422-3.mp4
[download]   0.5% of ~907.35MiB at  4.27MiB/s ETA 03:00
```
```
[brightcove:new] ref:5815995594001: Downloading MPD manifest
[debug] Invoking downloader on u'https://bcboltsony-a.akamaihd.net/media/v1/pmp4/static/clear/5182475815001/c80e487e-de6c-4740-ac7a-20ac69d623d7/86d20958-bf0f-4481-8874-9c649833d06e/main.mp4?akamai_token=exp=1535482117~acl=/media/v1/pmp4/static/clear/5182475815001/c80e487e-de6c-4740-ac7a-20ac69d623d7/86d20958-bf0f-4481-8874-9c649833d06e/main.mp4*~hmac=ba8a55d7a7f01bbdd71ec71742df107c502fbf2ef29c84249ec3747c3e0b560a'
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

It look, that full hd  http streams are unavailable for free users

**Comment by remitamine** [comment]
> but why the tag?

for developers working on this, they might need workaround geo-restriction.

it looks like the http formats are not available, use another format:
```
youtube-dl -f hls-1422-5 https://www.sonyliv.com/details/clips/5815995594001/
[brightcove:new] ref:5815995594001: Downloading webpage
[brightcove:new] ref:5815995594001: Downloading JSON metadata
[brightcove:new] ref:5815995594001: Downloading m3u8 information
[brightcove:new] ref:5815995594001: Downloading m3u8 information
[brightcove:new] ref:5815995594001: Downloading m3u8 information
[brightcove:new] ref:5815995594001: Downloading m3u8 information
[brightcove:new] ref:5815995594001: Downloading m3u8 information
[brightcove:new] ref:5815995594001: Downloading m3u8 information
[brightcove:new] ref:5815995594001: Downloading MPD manifest
[brightcove:new] ref:5815995594001: Downloading MPD manifest
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 775
[download] Destination: WWE RAW - Full Episode - 31st July, 2018-ref -5815995594001.mp4
[download]   0.2% of ~1.10GiB at 453.61KiB/s ETA 01:57:33
```

**Comment by theincognito-inc** [comment]
@remitamine Thank you for the info!

@bato3 Thanks man. Then a quick question. I am a premium member of that site. So, if I pass my username and password as arguments, will it be enough to download in full hd http? Or should I do something else?

**Comment by theincognito-inc** [comment]
@bato3 It doesn't work. Moreover, the thing is, the video I posted above is a free video(not a video that requires logging in).

Also, for the following video from the same site, the full hd httplink works:
https://www.sonyliv.com/details/clips/5815214863001/UFC-Fight-Night---Full-Highlights---29th-July,-2018

So, this is NOT a case of premium/non-premium account, I am afraid. :(

**Comment by theincognito-inc** [comment]
@remitamine Please reopen this.

**Comment by remitamine** [comment]
> Please reopen this.

if downloading other hls formats does not work for you then post the full verbose output.
the non-availability of some formats happens sometimes for other websites as well(ex: youtube), and it can easily work around it just by choosing another format.

**Comment by theincognito-inc** [comment]
@remitamine You are right. hls formats does work for me. Ignore my reopening request. Thank you!
