### ISSUE TITLE
[VK.com] "Could not send HEAD request" "HTTP Error 501: not implemented"

### ISSUE THREAD

**Issue by xomega100** [rg3/youtube-dl#17123]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\G\Documents\YT\youtube-dl>youtube-dl -v -u vk_username -p vk_password -vg https://vk.com/video?q=skrillex%20fuji&z=video-24363586_456239555
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-vg', 'https://vk.com/video?q=skrillex%20fuji']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.07.29
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91398-gd08d4a8c73, ffprobe N-91398-gd08d4a8c73
[debug] Proxy map: {}
WARNING: Could not send HEAD request to https://vk.com/video?q=skrillex%20fuji: HTTP Error 501: Not Implemented
WARNING: Falling back on generic information extractor.
WARNING: Could not send HEAD request to https://vk.com/badbrowser.php: HTTP Error 501: Not Implemented
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://vk.com/badbrowser.php
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\generic.py", line 3259, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://vk.com/badbrowser.php

'z' is not recognized as an internal or external command,
operable program or batch file.
<end of log>
```
---
### Description of your *issue*, suggested solution and other information

I am a fairly skilled user. I have recently been trying to extract a private video from VK. ive gotten past the login stage but the video will not download for whatever reason. is it possible that this video cannot be downloaded at all? thank you.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
