### ISSUE TITLE
HEVC recode. Is that possible?

### ISSUE THREAD

**Issue by gabriellluz** [rg3/youtube-dl#17134]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.07.29
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Hi there.
I'm currently using Youtube-DL as an archiving tool and it works great. The problem is I always have to use Handbrake after downloading new videos in order to encode them to hevc.
I see Youtube-DL has a recode option but that option doesn't seem to use HEVC as a codec. Is there a way I can use directly HEVC video and OPUS audio with youtube-dl? It'd be so much easier to me since HEVC and OPUS are great standards in the YouTube archiving community. Yes, we do have a community against censorship and we provide archiving of some very important YouTube channels in case they get removed or banned.

**Comment by bato3** [comment]
If I know Youtube-dl don't change encoding. This can be do [in post-process](https://github.com/rg3/youtube-dl#post-processing-options) 

https://trac.ffmpeg.org/wiki/Encode/H.265
https://wiki.libav.org/Encoding/hevc

eg `youtube-dl https://www.youtube.com/watch?v=BaW_jenozKc -v --postprocessor-args "-c:v libx265"`

**Comment by WolfganP** [comment]
> I see Youtube-DL has a recode option but that option doesn't seem to use HEVC as a codec. Is there a way I can use directly HEVC video and OPUS audio with youtube-dl? It'd be so much easier to me since HEVC and OPUS are great standards in the YouTube archiving community. Yes, we do have a community against censorship and we provide archiving of some very important YouTube channels in case they get removed or banned.

Try `youtube-dl -v yourvideoURL -F` and see if any of the offered resolutions is hvec encoded already and audio is offered in opus format. 
Then you can choose your video+audio specific streams and download them selectively as in `youtube-dl -v yourvideoURL -f 135+140`

**Comment by Hrxn** [comment]
> Try `youtube-dl -v yourvideoURL -F` and see if any of the offered resolutions is hvec encoded already and audio is offered in opus format.

YouTube already offers HEVC encoded streams? This is new to me.. since when?

**Comment by WolfganP** [comment]
> YouTube already offers HEVC encoded streams? This is new to me.. since when?

IIRC, some 4K videos may be offered both in HEVC and VP9. I don't remember if that also extended to lower resolutions' encoding, or if that was simple testing/experiments on YT side

**Comment by gabriellluz** [comment]
Hi guys.
I've tried youtube-dl https://www.youtube.com/watch?v=BaW_jenozKc --postprocessor-args "-c:v libx265 -b:v 800k -c:a opus -b:a 128k"   It works with HEVC (thanks :)), but I can't convert audio to OPUS. I want the output as an MKV file. Also, adding -x --audio-format opus --audio-quality 128k doesn't work because it renders an OPUS file. I want a MKV file but I don't want separate files (MP4 + OPUS).

**Comment by bato3** [comment]
`youtube-dl https://www.youtube.com/watch?v=BaW_jenozKc --postprocessor-args "-c:v libx265 -b:v 800k -c:a opus  -strict experimental -b:a 128k"`

**Comment by WolfganP** [comment]
Did you try `--merge-output-format mkv` ?

**Comment by gabriellluz** [comment]
Yes, I've tried. Now it works! Can we also use CRF instead of bitrate? YES, WE CAN:

youtube-dl https://www.youtube.com/watch?v=BaW_jenozKc --postprocessor-args "-c:v libx265 -preset slow -crf 15 -c:a opus -strict experimental -b:a 128k" --merge-output-format mkv

Please OP, put that in the Wiki because many people need that info. Thank you guys so much!

**Comment by williamjmorenor** [comment]
Also works for mp4:

youtube-dl https://www.youtube.com/watch?v=BaW_jenozKc --postprocessor-args "-c:v libx265 -preset slow -crf 15 -c:a opus -strict experimental -b:a 128k" --merge-output-format mp4

I preffer a higher -crf, 28 is the default.

**Comment by AravindhStanley** [comment]
@williamjmorenor This works amazing. Any way to show progress for the post processing?

**Comment by Littlesloths** [comment]
It looks like all the postprocessing is done after the file is fully downloaded?
I tried this on a continuous stream and it does not work.
Any idea how to recode a stream on the fly?

**Comment by macr2hoyipbjtn** [comment]
@Littlesloths use ffmpeg as an external downloader. Example: 
```bash
youtube-dl --external-downloader ffmpeg --external-downloader-args '-c:v libx265 <args here>'
```

Note that reencoding is, generally, a bad idea for content from sites that already use modern codecs, except if you have a dumb device that absolutely needs HEVC. 
VP9 is about as good as HEVC compression-wise, and reencoding with a lossy codec will by definition lose you quality. 
If you don't care about quality loss and just want smaller files, go ahead.

**Comment by rautamiekka** [comment]
Quality loss is a problem only if you use the wrong settings, but re-encoding for smaller size is pretty hard due to the amount of trial-and-error required, I know from trying it so many times.
