### ISSUE TITLE
[VK.com] "ERROR: Unable to login, incorrect username and/or password" (My username and password is correct)

### ISSUE THREAD

**Issue by xomega100** [rg3/youtube-dl#17138]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\G>youtube-dl -v -u vk_mycorrectvkusername -p vk_mycorrectvkpassword -vg "https://vk.com/video?q=skrillex%20fuji&z=video-24363586_456239555"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-vg', 'https://vk.com/video?q=skrillex%20fuji&z=video-24363586_456239555']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.07.29
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91398-gd08d4a8c73, ffprobe N-91398-gd08d4a8c73
[debug] Proxy map: {}
ERROR: Unable to login, incorrect username and/or password
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\common.py", line 501, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\common.py", line 405, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\vk.py", line 80, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\vk.py", line 77, in _login
youtube_dl.utils.ExtractorError: Unable to login, incorrect username and/or password
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

So ive been trying to download a private video from VK and ive followed this thread: https://github.com/rg3/youtube-dl/issues/2206

however, every time i use my CORRECT username and password, it keeps saying my username and password is incorrect.

**Comment by dstftw** [comment]
Obviously you input it incorrectly.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://vk.com/video?q=skrillex%20fuji&z=video-24363586_456239555', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.07.29
[debug] Git HEAD: 0fa6860
[debug] Python version 2.7.12 (CPython) - Windows-10-10.0.10240
[debug] exe versions: ffmpeg N-85653-gb4330a0, ffprobe N-85653-gb4330a0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[vk] Downloading login page
[vk] Logging in
[vk] -24363586_456239555: Downloading webpage
[vk] -24363586_456239555: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
...
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 955
[download] Destination: Skrillex - Live @ Fuji Rock Festival, Japan 2018-456239555.mp4
[download]   0.6% of ~1.88GiB at  4.96MiB/s ETA 01:29
ERROR: Interrupted by user
```

**Comment by novikalexy** [comment]
The authentication algorithm on the site vk.com changed. Now on the start page in the input form you need to specify only the login, after clicking on the button in the next form you need to enter only the password. Please correct the authentication for vk.com in your module vk.py

**Comment by Foopss** [comment]
> The authentication algorithm on the site vk.com changed. Now on the start page in the input form you need to specify only the login, after clicking on the button in the next form you need to enter only the password. Please correct the authentication for vk.com in your module vk.py

I agree
