### ISSUE TITLE
Is there a command to combine multiple resolution codes in a single URL

### ISSUE THREAD

**Issue by anubismedia** [rg3/youtube-dl#17145]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

--
I'm trying to download a video at 768x432 resolution (not best) when I run the command 
youtube-dl --list-formats url
the URL breaks the video into 4 parts assigning each part an ID; each part has a different code for the resolution I'm trying to download so when I run the command 
youtube-dl -f (code) url
 it downloads the first part but then returns the error "requested format not available" after that. I've done some searching but cant seem to find the command line to combine multiple resolution codes or even download a specific video ID's So my question is, is there a way to attach multiple resolution codes to a command line or is there a command line that I can run to download just one part of the video by its ID number?

**Comment by dstftw** [comment]
Have you even read [FAQ](https://github.com/rg3/youtube-dl#format-selection)?

**Comment by anubismedia** [comment]
Solved the problem; have to use a "/" between resolutions
youtube-dl -f code/code url
