### ISSUE TITLE
[youtube] ffmpeg adds ext when in -o  isin't present

### ISSUE THREAD

**Issue by bato3** [rg3/youtube-dl#17143]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
wrong: 
```
youtube-dl https://www.youtube.com/watch?v=BaW_jenozKc --write-info-json -o "..\test"
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading video info webpage
[info] Writing video description metadata as JSON to: ..\test.info.json
[download] Destination: ..\test.f137
[download] 100% of 2.11MiB in 00:00
[download] Destination: ..\test.f140
[download] 100% of 154.06KiB in 00:00
[ffmpeg] Merging formats into "..\test.mp4"
Deleting original file ..\test.f137 (pass -k to keep)
Deleting original file ..\test.f140 (pass -k to keep)
```
OK
```
youtube-dl https://www.youtube.com/watch?v=BaW_jenozKc --write-info-json -o "..\test2" -f 18
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading video info webpage
[info] Writing video description metadata as JSON to: ..\test2.info.json
[download] Destination: ..\test2
[download] 100% of 354.29KiB in 00:00
```
---

### Description of your *issue*, suggested solution and other information

In case `-o "..\test"` ffmpg should merge to file without extension

**Comment by dstftw** [comment]
This is expected behavior for now.
