### ISSUE TITLE
'list' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by webstuffj** [rg3/youtube-dl#17150]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Please see where I commented:
https://github.com/rg3/youtube-dl/issues/15483

Hi, I have this same error message:

"'list' is not recognized as an internal or external command,"
when I execute:

youtube-dl.exe -s -f 18 --yes-playlist -o JarvisJohnson\Tech%(upload_date)s--%(id)s--%(title)s.%(ext)s https://www.youtube.com/watch?v=RHwsIW44HbA&list=PLyBrFxr0n1iP-qeAAaIt51XEHAuKtSXaN

I don't understand why dstftw determine the above is "invalid not-a bug" when it clearly is. JarvisJohnson has many playlists on his channel, and among them is "Liked Video" which do not want to download, so I'm planning to download videos from each of his playlist.

Is there a way to exclude the "Liked video" playlist while downloading the rest of the videos in the various playlists?

Thanks.

**Comment by dstftw** [comment]
Read my [post](https://github.com/rg3/youtube-dl/issues/15483#issuecomment-362802207) with eyes please.
