### ISSUE TITLE
DiscoveryGo help

### ISSUE THREAD

**Issue by Leolexis** [rg3/youtube-dl#17154]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Hello! I'm pretty new to python and git so I maybe have some stupid questions but anyway I tried to download from DiscoveryGo but I did't get anything because

C:\Users\я\Desktop\dl>youtube-dl --all-subs --skip-download --hls-prefer-native https://www.discovery.com/tv-shows/naked-and-afraid-xl/full-episodes/all-stars-the-lions-den
[Discovery] all-stars-the-lions-den: Downloading webpage
[Discovery] all-stars-the-lions-den: Downloading JSON metadata
ERROR: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.

I've read FAQ  but I didn't understand much, so maybe someone can write like a tutorial for noobs please?

**Comment by dstftw** [comment]
As clearly stated in the message you must pass cookies from browser authenticated with cable TV provider.

**Comment by besweeet** [comment]
Have been recently having the same issue. Typically use streamlink but even after passing every possible header over, nothing there or with youtube-dl.
