### ISSUE TITLE
[NRKTVSeries] Download all seasons from a series broken

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#17159]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [X] Bug report (encountered problems with youtube-dl)

Downloading all seasons from a series on NRK is broken, despite the similar #16941 being fixed.

```
$ youtube-dl --verbose --yes-playlist https://tv.nrk.no/serie/zombielars
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--yes-playlist', u'https://tv.nrk.no/serie/zombielars']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.15 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[NRKTVSeries] zombielars: Downloading webpage
[download] Downloading playlist: NRK TV – ZombieLars
[NRKTVSeries] playlist NRK TV – ZombieLars: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: NRK TV – ZombieLars
```

**Comment by forthrin** [comment]
The new HTML and URLs are very orderly. Just look for `tv-series-episodes__episode-link`.

```
<a aria-controls="episode-info" class="nrk-grid tv-series-episodes__episode-link tv-series-episodes__episode-link--active" href="/serie/zombielars/sesong/2/episode/1">
<a aria-controls="episode-info" class="nrk-grid tv-series-episodes__episode-link" href="/serie/zombielars/sesong/2/episode/2">
...
<a aria-controls="episode-info" class="nrk-grid tv-series-episodes__episode-link tv-series-episodes__episode-link--unavailable" href="/serie/zombielars/sesong/2/episode/12">
...
```

**Comment by forthrin** [comment]
Will be resolved by committing patch in #17258.

**Comment by ralin3** [comment]
Can that patch be submitted as a pull request perhaps? No point leaving it in a Issue somewhere.
I see that  #17258 is another issue you created, this should be a pull request, yes?

**Comment by forthrin** [comment]
@ralin3: I'm not too up to speed on submitting pull requests. That's why I put the fix in the issue as a simple paste. Hope it's still useful. It should resolve the issue.

**Comment by bombaaa** [comment]
> @ralin3: I'm not too up to speed on submitting pull requests. That's why I put the fix in the issue as a simple paste. Hope it's still useful. It should resolve the issue.

See #17258 I added a comment there.
I really appreciate the patch, its working for series without partial episodes that has expired, but it stops for the first error and stop downloading episodes that actually are available.

Do you think you could have a look at it? Maybe something simple to get the script to jump to the next episode?
