### ISSUE TITLE
hotstar cannot work now

### ISSUE THREAD

**Issue by chzuping** [rg3/youtube-dl#17169]
python2 __main__.py -g -v https://www.hotstar.com/movies/baaghi-2/1000213089 
[debug] System config: [] 
[debug] User config: [] 
[debug] Custom config: [] 
[debug] Command-line args: [u'-g', u'-v', u'https://www.hotstar.com/movies/baaghi-2/1000213089'] 
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936 
[debug] youtube-dl version 2018.08.04 
[debug] Git HEAD: a62460a 
[debug] Python version 2.7.15 (CPython) - Windows-7-6.1.7601-SP1 
[debug] exe versions: none 
[debug] Proxy map: {} 
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden 
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
Traceback (most recent call last): 
  File "D:\work\youtube-dl\youtube_dl\YoutubeDL.py", line 792, in extract_info 
    ie_result = ie.extract(url) 
  File "D:\work\youtube-dl\youtube_dl\extractor\common.py", line 502, in extract 
    ie_result = self._real_extract(url) 
  File "D:\work\youtube-dl\youtube_dl\extractor\hotstar.py", line 102, in _real_extract 
    self._sort_formats(formats) 
  File "D:\work\youtube-dl\youtube_dl\extractor\common.py", line 1281, in _sort_formats 
    raise ExtractorError('No video formats found') 
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call
 youtube-dl with the --verbose flag and include its complete output.

**Comment by droidnafiz** [comment]
hotstar not working fr me since many days....also voot is not working now...
