### ISSUE TITLE
viki.com is not downloading videos

### ISSUE THREAD

**Issue by RazorRz** [rg3/youtube-dl#17179]
hello guys. latest version yt-dl installed but is not downloading.

youtube-dl http://www.viki.com/videos/1090093v-nssa-basic-episode-7 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.viki.com/videos/1090093v-nssa-basic-episode-7', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.6.6 (CPython) - Linux-2.6.32-358.el6.x86_64-x86_64-with-centos-6.4-Final
[debug] exe versions: ffmpeg N-45637-g92fe0bf1e-static
[debug] Proxy map: {}
[viki] 1090093v: Downloading video JSON
[viki] 1090093v: Downloading video streams JSON
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 599, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
```
> py -3.6 .\youtube_dl\__main__.py http://www.viki.com/videos/1090093v-nssa-basic-episode-7
[viki] 1090093v: Downloading video JSON
[viki] 1090093v: Downloading video streams JSON
[download] Destination: NSSA Basic - Episode 7-1090093v.mp4
[download]   0.6% of 174.31MiB at  1.35MiB/s ETA 02:08
ERROR: Interrupted by user
```

**Comment by mzfr** [comment]
I just tested it and seems to work fine for me
Here's what I get:
```
 youtube-dl http://www.viki.com/videos/1090093v-nssa-basic-episode-7 --skip-download -v                                                                    
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.viki.com/videos/1090093v-nssa-basic-episode-7', '--skip-download', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.5.2 (CPython) - Linux-4.15.0-29-generic-x86_64-with-neon-16.04-xenial
[debug] exe versions: avconv 2.8.14-0ubuntu0.16.04.1, avprobe 2.8.14-0ubuntu0.16.04.1, ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[viki] 1090093v: Downloading video JSON
[viki] 1090093v: Downloading video streams JSON
[debug] Default format spec: bestvideo+bestaudio/best
```
