### ISSUE TITLE
Paramount Network Yellow Stone video ids?

### ISSUE THREAD

**Issue by captbanana** [rg3/youtube-dl#17177]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I am trying to download the TV show Yellow Stone from the Paramount Network website. On episode 1 youtube-dl says there are 9 video ids. 

Instead of downloading all 9 video ids separately, how do I download all 9 video ids merged together as 1 video file?

Thank you

./youtube-dl -F http://www.paramountnetwork.com/episodes/j635al/yellowstone-daybreak-season-1-ep-1
[ParamountNetwork] yellowstone-daybreak-season-1-ep-1: Downloading webpage
[ParamountNetwork] Downloading JSON metadata
[ParamountNetwork] 40372210-599e-11e8-aacc-70df2f866ace: Downloading info
[ParamountNetwork] 524dad2c-0463-4f32-8f62-fb2a63b72c3f: Extracting information
[ParamountNetwork] 524dad2c-0463-4f32-8f62-fb2a63b72c3f: Downloading video urls
[ParamountNetwork] 524dad2c-0463-4f32-8f62-fb2a63b72c3f: Downloading m3u8 information
[ParamountNetwork] 3bc83351-d1ea-45f6-8466-4da03c3d06bf: Extracting information
[ParamountNetwork] 3bc83351-d1ea-45f6-8466-4da03c3d06bf: Downloading video urls
[ParamountNetwork] 3bc83351-d1ea-45f6-8466-4da03c3d06bf: Downloading m3u8 information
[ParamountNetwork] ae8896bd-68e9-470d-ae76-9518599895e8: Extracting information
[ParamountNetwork] ae8896bd-68e9-470d-ae76-9518599895e8: Downloading video urls
[ParamountNetwork] ae8896bd-68e9-470d-ae76-9518599895e8: Downloading m3u8 information
[ParamountNetwork] 5d0710de-8e16-47ad-a3a2-6e047281cef8: Extracting information
[ParamountNetwork] 5d0710de-8e16-47ad-a3a2-6e047281cef8: Downloading video urls
[ParamountNetwork] 5d0710de-8e16-47ad-a3a2-6e047281cef8: Downloading m3u8 information
[ParamountNetwork] 797ddc07-89a8-4c77-abbf-34cd9aaed228: Extracting information
[ParamountNetwork] 797ddc07-89a8-4c77-abbf-34cd9aaed228: Downloading video urls
[ParamountNetwork] 797ddc07-89a8-4c77-abbf-34cd9aaed228: Downloading m3u8 information
[ParamountNetwork] 40ec89ba-4297-4883-a022-585ec41d7188: Extracting information
[ParamountNetwork] 40ec89ba-4297-4883-a022-585ec41d7188: Downloading video urls
[ParamountNetwork] 40ec89ba-4297-4883-a022-585ec41d7188: Downloading m3u8 information
[ParamountNetwork] dd561171-a1db-4ac7-8ebe-ae50f734fc5c: Extracting information
[ParamountNetwork] dd561171-a1db-4ac7-8ebe-ae50f734fc5c: Downloading video urls
[ParamountNetwork] dd561171-a1db-4ac7-8ebe-ae50f734fc5c: Downloading m3u8 information
[ParamountNetwork] dac1db8d-5907-4dc9-b7bc-010018de8474: Extracting information
[ParamountNetwork] dac1db8d-5907-4dc9-b7bc-010018de8474: Downloading video urls
[ParamountNetwork] dac1db8d-5907-4dc9-b7bc-010018de8474: Downloading m3u8 information
[ParamountNetwork] 7407983c-fe66-4ced-b450-08a4c80aecad: Extracting information
[ParamountNetwork] 7407983c-fe66-4ced-b450-08a4c80aecad: Downloading video urls
[ParamountNetwork] 7407983c-fe66-4ced-b450-08a4c80aecad: Downloading m3u8 information
[download] Downloading playlist: Daybreak
[ParamountNetwork] playlist Daybreak: Collected 9 video ids (downloading 9 of them)
[download] Downloading video 1 of 9
[info] Available formats for 524dad2c-0463-4f32-8f62-fb2a63b72c3f:
format code  extension  resolution note
hls-279      mp4        384x216     279k , avc1.77.30, mp4a.40.2
hls-471      mp4        512x288     471k , avc1.77.30, mp4a.40.2
hls-767      mp4        640x360     767k , avc1.77.30, mp4a.40.2
hls-1024     mp4        768x432    1024k , avc1.77.30, mp4a.40.2
hls-1533     mp4        960x540    1533k , avc1.77.30, mp4a.40.2
hls-2300     mp4        1280x720   2300k , avc1.640028, mp4a.40.2
hls-4269     mp4        1920x1080  4269k , avc1.640028, mp4a.40.2 (best)
[download] Downloading video 2 of 9
[info] Available formats for 3bc83351-d1ea-45f6-8466-4da03c3d06bf:
format code  extension  resolution note
hls-272      mp4        384x216     272k , avc1.77.30, mp4a.40.2
hls-463      mp4        512x288     463k , avc1.77.30, mp4a.40.2
hls-741      mp4        640x360     741k , avc1.77.30, mp4a.40.2
hls-964      mp4        768x432     964k , avc1.77.30, mp4a.40.2
hls-1434     mp4        960x540    1434k , avc1.77.30, mp4a.40.2
hls-2207     mp4        1280x720   2207k , avc1.640028, mp4a.40.2
hls-4694     mp4        1920x1080  4694k , avc1.640028, mp4a.40.2 (best)
[download] Downloading video 3 of 9
[info] Available formats for ae8896bd-68e9-470d-ae76-9518599895e8:
format code  extension  resolution note
hls-254      mp4        384x216     254k , avc1.77.30, mp4a.40.2
hls-396      mp4        512x288     396k , avc1.77.30, mp4a.40.2
hls-535      mp4        640x360     535k , avc1.77.30, mp4a.40.2
hls-663      mp4        768x432     663k , avc1.77.30, mp4a.40.2
hls-1009     mp4        960x540    1009k , avc1.77.30, mp4a.40.2
hls-1596     mp4        1280x720   1596k , avc1.640028, mp4a.40.2
hls-3976     mp4        1920x1080  3976k , avc1.640028, mp4a.40.2 (best)
[download] Downloading video 4 of 9
[info] Available formats for 5d0710de-8e16-47ad-a3a2-6e047281cef8:
format code  extension  resolution note
hls-273      mp4        384x216     273k , avc1.77.30, mp4a.40.2
hls-461      mp4        512x288     461k , avc1.77.30, mp4a.40.2
hls-720      mp4        640x360     720k , avc1.77.30, mp4a.40.2
hls-951      mp4        768x432     951k , avc1.77.30, mp4a.40.2
hls-1423     mp4        960x540    1423k , avc1.77.30, mp4a.40.2
hls-2208     mp4        1280x720   2208k , avc1.640028, mp4a.40.2
hls-4681     mp4        1920x1080  4681k , avc1.640028, mp4a.40.2 (best)
[download] Downloading video 5 of 9
[info] Available formats for 797ddc07-89a8-4c77-abbf-34cd9aaed228:
format code  extension  resolution note
hls-266      mp4        384x216     266k , avc1.77.30, mp4a.40.2
hls-460      mp4        512x288     460k , avc1.77.30, mp4a.40.2
hls-820      mp4        640x360     820k , avc1.77.30, mp4a.40.2
hls-1097     mp4        768x432    1097k , avc1.77.30, mp4a.40.2
hls-1625     mp4        960x540    1625k , avc1.77.30, mp4a.40.2
hls-2486     mp4        1280x720   2486k , avc1.640028, mp4a.40.2
hls-4665     mp4        1920x1080  4665k , avc1.640028, mp4a.40.2 (best)
[download] Downloading video 6 of 9
[info] Available formats for 40ec89ba-4297-4883-a022-585ec41d7188:
format code  extension  resolution note
hls-265      mp4        384x216     265k , avc1.77.30, mp4a.40.2
hls-449      mp4        512x288     449k , avc1.77.30, mp4a.40.2
hls-743      mp4        640x360     743k , avc1.77.30, mp4a.40.2
hls-961      mp4        768x432     961k , avc1.77.30, mp4a.40.2
hls-1445     mp4        960x540    1445k , avc1.77.30, mp4a.40.2
hls-2255     mp4        1280x720   2255k , avc1.640028, mp4a.40.2
hls-4636     mp4        1920x1080  4636k , avc1.640028, mp4a.40.2 (best)
[download] Downloading video 7 of 9
[info] Available formats for dd561171-a1db-4ac7-8ebe-ae50f734fc5c:
format code  extension  resolution note
hls-254      mp4        384x216     254k , avc1.77.30, mp4a.40.2
hls-416      mp4        512x288     416k , avc1.77.30, mp4a.40.2
hls-584      mp4        640x360     584k , avc1.77.30, mp4a.40.2
hls-740      mp4        768x432     740k , avc1.77.30, mp4a.40.2
hls-1173     mp4        960x540    1173k , avc1.77.30, mp4a.40.2
hls-1906     mp4        1280x720   1906k , avc1.640028, mp4a.40.2
hls-4365     mp4        1920x1080  4365k , avc1.640028, mp4a.40.2 (best)
[download] Downloading video 8 of 9
[info] Available formats for dac1db8d-5907-4dc9-b7bc-010018de8474:
format code  extension  resolution note
hls-259      mp4        384x216     259k , avc1.77.30, mp4a.40.2
hls-426      mp4        512x288     426k , avc1.77.30, mp4a.40.2
hls-626      mp4        640x360     626k , avc1.77.30, mp4a.40.2
hls-810      mp4        768x432     810k , avc1.77.30, mp4a.40.2
hls-1231     mp4        960x540    1231k , avc1.77.30, mp4a.40.2
hls-1939     mp4        1280x720   1939k , avc1.640028, mp4a.40.2
hls-4387     mp4        1920x1080  4387k , avc1.640028, mp4a.40.2 (best)
[download] Downloading video 9 of 9
[info] Available formats for 7407983c-fe66-4ced-b450-08a4c80aecad:
format code  extension  resolution note
hls-182      mp4        384x216     182k , avc1.77.30, mp4a.40.2
hls-220      mp4        512x288     220k , avc1.77.30, mp4a.40.2
hls-275      mp4        640x360     275k , avc1.77.30, mp4a.40.2
hls-315      mp4        768x432     315k , avc1.77.30, mp4a.40.2
hls-411      mp4        960x540     411k , avc1.77.30, mp4a.40.2
hls-541      mp4        1280x720    541k , avc1.640028, mp4a.40.2
hls-917      mp4        1920x1080   917k , avc1.640028, mp4a.40.2 (best)
[download] Finished downloading playlist: Daybreak
./youtube-dl --all-subs -f hls-4269 http://www.paramountnetwork.com/episodes/j635al
/yellowstone-daybreak-season-1-ep-1
[ParamountNetwork] yellowstone-daybreak-season-1-ep-1: Downloading webpage
[ParamountNetwork] Downloading JSON metadata
[ParamountNetwork] 40372210-599e-11e8-aacc-70df2f866ace: Downloading info
[ParamountNetwork] 524dad2c-0463-4f32-8f62-fb2a63b72c3f: Extracting information
[ParamountNetwork] 524dad2c-0463-4f32-8f62-fb2a63b72c3f: Downloading video urls
[ParamountNetwork] 524dad2c-0463-4f32-8f62-fb2a63b72c3f: Downloading m3u8 information
[ParamountNetwork] 3bc83351-d1ea-45f6-8466-4da03c3d06bf: Extracting information
[ParamountNetwork] 3bc83351-d1ea-45f6-8466-4da03c3d06bf: Downloading video urls
[ParamountNetwork] 3bc83351-d1ea-45f6-8466-4da03c3d06bf: Downloading m3u8 information
[ParamountNetwork] ae8896bd-68e9-470d-ae76-9518599895e8: Extracting information
[ParamountNetwork] ae8896bd-68e9-470d-ae76-9518599895e8: Downloading video urls
[ParamountNetwork] ae8896bd-68e9-470d-ae76-9518599895e8: Downloading m3u8 information
[ParamountNetwork] 5d0710de-8e16-47ad-a3a2-6e047281cef8: Extracting information
[ParamountNetwork] 5d0710de-8e16-47ad-a3a2-6e047281cef8: Downloading video urls
[ParamountNetwork] 5d0710de-8e16-47ad-a3a2-6e047281cef8: Downloading m3u8 information
[ParamountNetwork] 797ddc07-89a8-4c77-abbf-34cd9aaed228: Extracting information
[ParamountNetwork] 797ddc07-89a8-4c77-abbf-34cd9aaed228: Downloading video urls
[ParamountNetwork] 797ddc07-89a8-4c77-abbf-34cd9aaed228: Downloading m3u8 information
[ParamountNetwork] 40ec89ba-4297-4883-a022-585ec41d7188: Extracting information
[ParamountNetwork] 40ec89ba-4297-4883-a022-585ec41d7188: Downloading video urls
[ParamountNetwork] 40ec89ba-4297-4883-a022-585ec41d7188: Downloading m3u8 information
[ParamountNetwork] dd561171-a1db-4ac7-8ebe-ae50f734fc5c: Extracting information
[ParamountNetwork] dd561171-a1db-4ac7-8ebe-ae50f734fc5c: Downloading video urls
[ParamountNetwork] dd561171-a1db-4ac7-8ebe-ae50f734fc5c: Downloading m3u8 information
[ParamountNetwork] dac1db8d-5907-4dc9-b7bc-010018de8474: Extracting information
[ParamountNetwork] dac1db8d-5907-4dc9-b7bc-010018de8474: Downloading video urls
[ParamountNetwork] dac1db8d-5907-4dc9-b7bc-010018de8474: Downloading m3u8 information
[ParamountNetwork] 7407983c-fe66-4ced-b450-08a4c80aecad: Extracting information
[ParamountNetwork] 7407983c-fe66-4ced-b450-08a4c80aecad: Downloading video urls
[ParamountNetwork] 7407983c-fe66-4ced-b450-08a4c80aecad: Downloading m3u8 information
[download] Downloading playlist: Daybreak
[ParamountNetwork] playlist Daybreak: Collected 9 video ids (downloading 9 of them)
[download] Downloading video 1 of 9
[info] Writing video subtitles to: Yellowstone_June 20, 2018_1_101_Daybreak_Act 1-524dad2c-0463-4f32-8f62-fb2a63b72c3f.en.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 166
[download] Destination: Yellowstone_June 20, 2018_1_101_Daybreak_Act 1-524dad2c-0463-4f32-8f62-fb2a63b72c3f.mp4
[download]  36.2% of ~500.36MiB at 573.05KiB/s ETA 11:24

**Comment by dstftw** [comment]
You have to merge by your own.
