### ISSUE TITLE
help joining video parts (southpark.cc.com)

### ISSUE THREAD

**Issue by rellik31** [rg3/youtube-dl#17186]
hi, can someone please tell me if there is a extra command for when downloading from southpark.cc.com to join all 3 parts together as one file 
at the moment every video i have tried downloads as 3 .mp4 files but if its possible i would prefer each episode to be one file

thank you

**Comment by dstftw** [comment]
No such command. You have to do it on your own.

**Comment by rellik31** [comment]
can you tell me how?

**Comment by mzfr** [comment]
@rellik31 Use [MoviPy](https://github.com/Zulko/moviepy)
Something like this should work
```
    from moviepy.editor import VideoFileClip, concatenate_videoclips
    clip1 = VideoFileClip("myvideo.mp4")
    clip2 = VideoFileClip("myvideo2.mp4").subclip(50,60)
    clip3 = VideoFileClip("myvideo3.mp4")
    final_clip = concatenate_videoclips([clip1,clip2,clip3])
    final_clip.write_videofile("my_concatenation.mp4")
```
