### ISSUE TITLE
slow download problem on ok.ru 

### ISSUE THREAD

**Issue by ckck2000** [rg3/youtube-dl#17188]
Hello,

The program is downloading ok.ru videos at most ~200 KB

```
C:\>C:\youtube-dl\youtube-dl.exe -o c:\\youtube-dl\\1.mp4 https://ok.ru/video/28133952238
[Odnoklassniki] 28133952238: Downloading webpage
[Odnoklassniki] 28133952238: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 545
[download] Destination: c:\youtube-dl\1.mp4
[download]   0.3% of ~1.97GiB at 184.77KiB/s ETA 03:12:02
```

**Comment by dstftw** [comment]
youtube-dl does not impose any speed limits. Address this to ok.ru.

**Comment by ckck2000** [comment]
Ok. I understand the problem, OK.ru applies ~250 KB speed limit per connection to prevent downloading...So to skip this limitation we need to download the file as parts like IDM does.

**Comment by ckck2000** [comment]
OK. i found the solution is aria2c which has multiple download connections option; https://aria2.github.io/
This is the solution: C:\youtube-dl\aria2c.exe URL -d c:\youtube-dl -s 16 -x 16

and youtube-dl has external download option but this is not working with ok.ru, is this a bug?
C:\youtube-dl\youtube-dl.exe https://ok.ru/video/28133952238 --external-downloader aria2c --external-downloader-args "-d c:\youtube-dl -s 16 -x 16"
