### ISSUE TITLE
disneynow.go.com / uplynk broken

### ISSUE THREAD

**Issue by fcisler** [rg3/youtube-dl#17181]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

I have never had much luck with using direct disneynow.go.com, but I was always able to find the .m3u8 and download. For the past 3 weeks I receive a "No such file or directory" - when using the same methods previously. Here's running it with -v

youtube-dl -v "https://content-ause2.uplynk.com/59a8e10a73c44346b0
5f9412465545dc/j.m3u8?exp=1533650788&ct=a&oid=21885d134fa441488df8e1d7acee8c66&e
id=d83ec51d435e4e46af07e4e2af263799&iph=c7ed4ec245539c6832cb8d7bd96ffa30046655b3
e6b45d9d1107bbf6e12b7bfe&rays=hjigfedcba&euid=C3C97D5D-1CDD-400A-96F8-F8BF45EF3D
F0_005_1_001_lf_04-06-99_1.0.20.10&cdn=ec&stgcfg=datg&pp2ip=0&ddp=1&v=3&ad.pingf
=2&expand=drmOff&sig=0a3658d1cc30140bddb2d5c29f4f1b1648bfb8c0c99b3abcd0020605877
ca37e&pbs=bc19d31f528f418bb2386dd5e2f453da"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://content-ause2.uplynk.com/59a8e10a73c4
4346b05f9412465545dc/j.m3u8?exp=1533650788&ct=a&oid=21885d134fa441488df8e1d7acee
8c66&eid=d83ec51d435e4e46af07e4e2af263799&iph=c7ed4ec245539c6832cb8d7bd96ffa3004
6655b3e6b45d9d1107bbf6e12b7bfe&rays=hjigfedcba&euid=C3C97D5D-1CDD-400A-96F8-F8BF
45EF3DF0_005_1_001_lf_04-06-99_1.0.20.10&cdn=ec&stgcfg=datg&pp2ip=0&ddp=1&v=3&ad
.pingf=2&expand=drmOff&sig=0a3658d1cc30140bddb2d5c29f4f1b1648bfb8c0c99b3abcd0020
605877ca37e&pbs=bc19d31f528f418bb2386dd5e2f453da']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.4.4 (CPython) - Windows-8-6.2.9200-SP0
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1
[debug] Proxy map: {}
[generic] j.m3u8?exp=1533650788&ct=a&oid=21885d134fa441488df8e1d7acee8c66&eid=d8
3ec51d435e4e46af07e4e2af263799&iph=c7ed4ec245539c6832cb8d7bd96ffa30046655b3e6b45
d9d1107bbf6e12b7bfe&rays=hjigfedcba&euid=C3C97D5D-1CDD-400A-96F8-F8BF45EF3DF0_00
5_1_001_lf_04-06-99_1.0.20.10&cdn=ec&stgcfg=datg&pp2ip=0&ddp=1&v=3&ad: Requestin
g header
[generic] j.m3u8?exp=1533650788&ct=a&oid=21885d134fa441488df8e1d7acee8c66&eid=d8
3ec51d435e4e46af07e4e2af263799&iph=c7ed4ec245539c6832cb8d7bd96ffa30046655b3e6b45
d9d1107bbf6e12b7bfe&rays=hjigfedcba&euid=C3C97D5D-1CDD-400A-96F8-F8BF45EF3DF0_00
5_1_001_lf_04-06-99_1.0.20.10&cdn=ec&stgcfg=datg&pp2ip=0&ddp=1&v=3&ad: Downloadi
ng m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://content-ause2.uplynk.com/59a8e10a73c4434
6b05f9412465545dc/j.m3u8?exp=1533650788&ct=a&oid=21885d134fa441488df8e1d7acee8c6
6&eid=d83ec51d435e4e46af07e4e2af263799&iph=c7ed4ec245539c6832cb8d7bd96ffa3004665
5b3e6b45d9d1107bbf6e12b7bfe&rays=hjigfedcba&euid=C3C97D5D-1CDD-400A-96F8-F8BF45E
F3DF0_005_1_001_lf_04-06-99_1.0.20.10&cdn=ec&stgcfg=datg&pp2ip=0&ddp=1&v=3&ad.pi
ngf=2&expand=drmOff&sig=0a3658d1cc30140bddb2d5c29f4f1b1648bfb8c0c99b3abcd0020605
877ca37e&pbs=bc19d31f528f418bb2386dd5e2f453da'
[download] Destination: j-j.m3u8exp=1533650788&ct=a&oid=21885d134fa441488df8e1d7
acee8c66&eid=d83ec51d435e4e46af07e4e2af263799&iph=c7ed4ec245539c6832cb8d7bd96ffa
30046655b3e6b45d9d1107bbf6e12b7bfe&rays=hjigfedcba&euid=C3C97D5D-1CDD-400A-96F8-
F8BF45EF3DF0_005_1_001_lf_04-06-99_1.0.20.10&cdn=ec&stgcfg=datg&pp2ip=0&ddp=1&v=
3&ad.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept-Langua
ge: en-us,en;q=0.5
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
 (Chrome)
Accept-Encoding: gzip, deflate
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
" -i "https://content-ause2.uplynk.com/59a8e10a73c44346b05f9412465545dc/j.m3u8?e
xp=1533650788&ct=a&oid=21885d134fa441488df8e1d7acee8c66&eid=d83ec51d435e4e46af07
e4e2af263799&iph=c7ed4ec245539c6832cb8d7bd96ffa30046655b3e6b45d9d1107bbf6e12b7bf
e&rays=hjigfedcba&euid=C3C97D5D-1CDD-400A-96F8-F8BF45EF3DF0_005_1_001_lf_04-06-9
9_1.0.20.10&cdn=ec&stgcfg=datg&pp2ip=0&ddp=1&v=3&ad.pingf=2&expand=drmOff&sig=0a
3658d1cc30140bddb2d5c29f4f1b1648bfb8c0c99b3abcd0020605877ca37e&pbs=bc19d31f528f4
18bb2386dd5e2f453da" -c copy -f mp4 "file:j-j.m3u8exp=1533650788&ct=a&oid=21885d
134fa441488df8e1d7acee8c66&eid=d83ec51d435e4e46af07e4e2af263799&iph=c7ed4ec24553
9c6832cb8d7bd96ffa30046655b3e6b45d9d1107bbf6e12b7bfe&rays=hjigfedcba&euid=C3C97D
5D-1CDD-400A-96F8-F8BF45EF3DF0_005_1_001_lf_04-06-99_1.0.20.10&cdn=ec&stgcfg=dat
g&pp2ip=0&ddp=1&v=3&ad.mp4.part"
ffmpeg version 4.0.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.1 (GCC) 20180710
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --e
nable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libblur
ay --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-
libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enab
le-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-li
bvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --en
able-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-
libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enabl
e-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enabl
e-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enab
le-dxva2 --enable-avisynth
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[hls,applehttp @ 00000022e600b480] HLS request for url 'https://x-disney-datg-st
gec.uplynk.com/ausw/slices/59a/21885d134fa441488df8e1d7acee8c66/59a8e10a73c44346
b05f9412465545dc/J00000000.ts?pbs=bc19d31f528f418bb2386dd5e2f453da&euid=C3C97D5D
-1CDD-400A-96F8-F8BF45EF3DF0_005_1_001_lf_04-06-99_1.0.20.10&si=0', offset 0, pl
aylist 0
[hls,applehttp @ 00000022e600b480] Opening 'https://content-ause2.uplynk.com/che
ck2?b=59a8e10a73c44346b05f9412465545dc&v=59a8e10a73c44346b05f9412465545dc&r=j&pb
s=bc19d31f528f418bb2386dd5e2f453da' for reading
[hls,applehttp @ 00000022e600b480] Opening 'crypto+https://x-disney-datg-stgec.u
plynk.com/ausw/slices/59a/21885d134fa441488df8e1d7acee8c66/59a8e10a73c44346b05f9
412465545dc/J00000000.ts?pbs=bc19d31f528f418bb2386dd5e2f453da&euid=C3C97D5D-1CDD
-400A-96F8-F8BF45EF3DF0_005_1_001_lf_04-06-99_1.0.20.10&si=0' for reading
[mpegts @ 00000022e833bc00] parser not found for codec timed_id3, packets or tim
es may be invalid.
[h264 @ 00000022e8624240] Reinit context to 1280x720, pix_fmt: yuv420p
Input #0, hls,applehttp, from 'https://content-ause2.uplynk.com/59a8e10a73c44346
b05f9412465545dc/j.m3u8?exp=1533650788&ct=a&oid=21885d134fa441488df8e1d7acee8c66
&eid=d83ec51d435e4e46af07e4e2af263799&iph=c7ed4ec245539c6832cb8d7bd96ffa30046655
b3e6b45d9d1107bbf6e12b7bfe&rays=hjigfedcba&euid=C3C97D5D-1CDD-400A-96F8-F8BF45EF
3DF0_005_1_001_lf_04-06-99_1.0.20.10&cdn=ec&stgcfg=datg&pp2ip=0&ddp=1&v=3&ad.pin
gf=2&expand=drmOff&sig=0a3658d1cc30140bddb2d5c29f4f1b1648bfb8c0c99b3abcd00206058
77ca37e&pbs=bc19d31f528f418bb2386dd5e2f453da':
  Duration: 00:24:01.58, start: 0.000000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo,
 fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (High), 1 reference frame ([27][0][0][0] / 0x001B),
 yuv420p(left), 1280x720, 23.98 fps, 23.98 tbr, 90k tbn, 48 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
file:j-j.m3u8exp=1533650788&ct=a&oid=21885d134fa441488df8e1d7acee8c66&eid=d83ec5
1d435e4e46af07e4e2af263799&iph=c7ed4ec245539c6832cb8d7bd96ffa30046655b3e6b45d9d1
107bbf6e12b7bfe&rays=hjigfedcba&euid=C3C97D5D-1CDD-400A-96F8-F8BF45EF3DF0_005_1_
001_lf_04-06-99_1.0.20.10&cdn=ec&stgcfg=datg&pp2ip=0&ddp=1&v=3&ad.mp4.part: No s
uch file or directory

ERROR: ffmpeg exited with code 1
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bu
ild\youtube_dl\__init__.py", line 472, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bu
ild\youtube_dl\__init__.py", line 462, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bu
ild\youtube_dl\YoutubeDL.py", line 2001, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bu
ild\youtube_dl\YoutubeDL.py", line 803, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bu
ild\youtube_dl\YoutubeDL.py", line 857, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bu
ild\youtube_dl\YoutubeDL.py", line 1635, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bu
ild\youtube_dl\YoutubeDL.py", line 1908, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bu
ild\youtube_dl\YoutubeDL.py", line 1847, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bu
ild\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bu
ild\youtube_dl\downloader\external.py", line 64, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bu
ild\youtube_dl\downloader\common.py", line 165, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bu
ild\youtube_dl\YoutubeDL.py", line 620, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bu
ild\youtube_dl\YoutubeDL.py", line 582, in trouble

**Comment by dstftw** [comment]
Provide shorter name with `-o`.

**Comment by fcisler** [comment]
D'oh! Feel so stupid, thank you!
