### ISSUE TITLE
[PornHub] youtube-dl says there are 0 videos in a playlist that has videos

### ISSUE THREAD

**Issue by mjolnir870** [rg3/youtube-dl#17196]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--no-mtime', '--no-playlist', '--playlist-reverse', '-i', '-w']
[debug] Command-line args: ['--config-location', 'C:\\Users\\USERNAME\\COMPUTER\\Scripts\\youtube-dl-ondemand.conf', '--ffmpeg-location', 'C:\\Users\\USERNAME\\COMPUTER\\Apps\\ffmpeg\\bin\\ffmpeg.exe', '--download-archive', 'H:\\test\\~youtube-dl_history.txt', '-f', 'bestvideo+bestaudio/best', '--write-thumbnail', '--external-downloader', 'C:\\Users\\USERNAME\\COMPUTER\\Apps\\aria2\\64bit\\aria2c.exe', '--external-downloader-args', '--file-allocation=none -x 4 -k 1M', '--dump-pages', '-v', '-o', 'H:\\test\\%(title)s_%(id)s.%(ext)s', 'https://www.pornhub.com/users/camsoda/videos/public']
[debug] Encodings: locale cp1252, fs mbcs, out cp65001, pref cp1252
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-90960-gbcff983dc3, ffprobe N-90960-gbcff983dc3
[debug] Proxy map: {}
[PornHubUserVideos] camsoda: Downloading page 1
[PornHubUserVideos] Dumping request to https://www.pornhub.com/users/camsoda/videos/public?page=1
PGh0bWw+PGhlYWQ+PHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiPjwhLS0KZnVuY3Rpb24gbGVhc3RGYWN0b3IobikgewogaWYgKGlzTmFOKG4pIHx8ICFpc0Zpbml0ZShuKSkgcmV0dXJuIE5hTjsKIGlmICh0eXBlb2YgcGhhbnRvbSAhPT0gJ3VuZGVmaW5lZCcpIHJldHVybiAncGhhbnRvbSc7CiBpZiAodHlwZW9mIG1vZHVsZSAhPT0gJ3VuZGVmaW5lZCcgJiYgbW9kdWxlLmV4cG9ydHMpIHJldHVybiAnbm9kZSc7CiBpZiAobj09MCkgcmV0dXJuIDA7CiBpZiAobiUxIHx8IG4qbjwyKSByZXR1cm4gMTsKIGlmIChuJTI9PTApIHJldHVybiAyOwogaWYgKG4lMz09MCkgcmV0dXJuIDM7CiBpZiAobiU1PT0wKSByZXR1cm4gNTsKIHZhciBtPU1hdGguc3FydChuKTsKIGZvciAodmFyIGk9NztpPD1tO2krPTMwKSB7CiAgaWYgKG4laT09MCkgICAgICByZXR1cm4gaTsKICBpZiAobiUoaSs0KT09MCkgIHJldHVybiBpKzQ7CiAgaWYgKG4lKGkrNik9PTApICByZXR1cm4gaSs2OwogIGlmIChuJShpKzEwKT09MCkgcmV0dXJuIGkrMTA7CiAgaWYgKG4lKGkrMTIpPT0wKSByZXR1cm4gaSsxMjsKICBpZiAobiUoaSsxNik9PTApIHJldHVybiBpKzE2OwogIGlmIChuJShpKzIyKT09MCkgcmV0dXJuIGkrMjI7CiAgaWYgKG4lKGkrMjQpPT0wKSByZXR1cm4gaSsyNDsKIH0KIHJldHVybiBuOwp9CmZ1bmN0aW9uIGdvKCkgewogdmFyIHA9MjEzNDU5OTQ0NDUyNzsgdmFyIHM9MzE5NjI1OTAzODsgdmFyIG47CmlmICgocyA+PiAxNCkgJiAxKS8qCmVsc2UgcC09CiovcCs9LyoKZWxzZSBwLT0KKi8xMTM3ODM0NTMqCjE3O2Vsc2UgCnAtPQkzOTY0Njg5MiovKgpwKz0gKi8xNTsvKgoqMTM7CiovaWYgKChzID4+IDApICYgMSkvKgpwKz0gKi9wKz0gMTE0NjEyMTgyKi8qCmVsc2UgcC09CiovMztlbHNlIC8qCmVsc2UgcC09CiovcC09LyoKKjEzOwoqLzk5MDgzMDM4KjE7LyoKZWxzZSBwLT0KKi9pZiAoKHMgPj4gNykgJiAxKS8qCioxMzsKKi9wKz0gMTk0Mzg0NjkqIDg7CmVsc2UgLyogMTIwODg2MTA4KgoqL3AtPTIzMzQzNDE1MSo4Oy8qIDEyMDg4NjEwOCoKKi9pZiAoKHMgPj4gMTMpICYgMSkvKgplbHNlIHAtPQoqL3ArPS8qCioxMzsKKi8xMzg5ODQ4MTEqLyoKKjEzOwoqLzE0OwplbHNlIC8qIDEyMDg4NjEwOCoKKi9wLT0KODg0MjMzNDYqMTQ7LyoKcCs9ICovaWYgKChzID4+IDEwKSAmIDEpLyoKKjEzOwoqL3ArPQoyMTQ1NjUxMCovKiAxMjA4ODYxMDgqCiovMTM7LyoKZWxzZSBwLT0KKi9lbHNlICBwLT03NjA1NTM5KgoxMTsgcC09MjA3NjQwNTQ3Owogbj1sZWFzdEZhY3RvcihwKTsKeyBkb2N1bWVudC5jb29raWU9IlJOS0VZPSIrbisiKiIrcC9uKyI6IitzKyI6MTM5MDE2NjM5OjEiOwogIGRvY3VtZW50LmxvY2F0aW9uLnJlbG9hZCh0cnVlKTsgfQp9Ci8vLS0+PC9zY3JpcHQ+PC9oZWFkPgo8Ym9keSBvbmxvYWQ9ImdvKCkiPgpMb2FkaW5nIC4uLgo8L2JvZHk+CjwvaHRtbD4K
[download] Downloading playlist: camsoda
[PornHubUserVideos] playlist camsoda: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: camsoda
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Playlist: https://www.pornhub.com/users/camsoda/videos/public

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Trying to download the videos from https://www.pornhub.com/users/camsoda/videos/public, but youtube-dl says there are 0 videos. Page works fine in a browser.

The above is commandline with -v and --dump-pages.

**Comment by mjolnir870** [comment]
It can still occur, and I think it's related to issue #17197. Basically I think PornHub begins serving you interstitial pages or putting pages on a delay if you make too many requests. You can convert the base64 in my log into html for the "loading..." page I was receiving. Once that starts happening youtube-dl will have trouble extracting a playlist or downloading a video.

I'm hopeful that resolving #17571 and #17573 will cut down on this happening so often, but it will still happen as long as youtube-dl can't handle the loading pages/delays.

**Comment by mariosemes** [comment]
PornHub banns your IP for a while. Had the same problem. Reset router or contact your ISP to get a new IP and there you go. Works great again :)
