### ISSUE TITLE
YouTube: Unable to submit TFA code: HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by zefie** [rg3/youtube-dl#17192]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-2', 'PRIVATE', '0-fyoq4454U', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-85750-ga75ef15, ffprobe N-85750-ga75ef15
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Submitting TFA code
WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error
[youtube] 0-fyoq4454U: Downloading webpage
[youtube] 8tEsxbCl21E: Downloading webpage
[youtube] 8tEsxbCl21E: Downloading video info webpage
```
(stopped here because it redirects to the free unauthenticated trailer)
(also replaced my 2FA code with 'PRIVATE')
---

### Description of your *issue*, suggested solution and other information

Cannot authenticate to YouTube with 2FA enabled.

WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error

Also tried old app-password method (would be preferred for easily retractable passwords in batch files), but since the code is updated to support 2FA, app passwords no longer work. Therefore, it is currently impossible to log into YouTube at the moment.

**Comment by dstftw** [comment]
```
> py -3.6 .\youtube_dl\__main__.py -v -n 0-fyoq4454U
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-n', '0-fyoq4454U']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2018.08.04
[debug] Git HEAD: d37dc6e
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.10240-SP0
[debug] exe versions: ffmpeg N-85653-gb4330a0, ffprobe N-85653-gb4330a0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
Type 2-step verification code and press [Return]:
[youtube] Submitting TFA code
[youtube] Checking cookie
[youtube] 0-fyoq4454U: Downloading webpage
...
```
Post the output with `--dump-pages`.

**Comment by zefie** [comment]
Here is the info you requested with --dump-pages.
I still get the error, --dump-pages dumped a lot of gibberish (base64?), so had to pipe the output to files.

https://drive.google.com/open?id=1GWHMp1ryDQqJThr6hu4Rb_NJ7KGEi-8_
