### ISSUE TITLE
Response file object (returned by `InfoExtractor._request_webpage`) may be closed for failed requests (matching `expected_status`) on Python 3.4.1+

### ISSUE THREAD

**Issue by puxlit** [rg3/youtube-dl#17195]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Since [bpo-15002](https://bugs.python.org/issue15002) (introduced in [Python 3.4.1](https://docs.python.org/3.4/whatsnew/changelog.html#id42)), `HTTPError`s close their `fp` when the error's destroyed. The current implementation of `InfoExtractor._request_webpage` accommodates for `expected_status` by catching `HTTPError`s and returning this `fp`. Unfortunately, this means subsequent reads against this file object by the caller are unreliable.

Fortunately, the number of extractors that make use of `expected_status` is small; as of 2018.08.04, it's just `bbc`, `lynda`, `markiza`, and `twitch`. One possible fix would be to return the error, and have the callers that use `expected_status` test for and access `fp` instead. Alternatively, we might be able to monkey patch our way into nixing the effects of `urllib.response.addclosehook` on those instances of `HTTPError`. I haven't looked into whether there's a cleaner approach.

Issue encountered whilst debugging [reports](https://github.com/rg3/youtube-dl/issues/17116#issuecomment-411159316) of problems running @bato3's [fix](https://github.com/rg3/youtube-dl/compare/master...bato3:crunchroll2) for #17116 on Python 3.7.

**Comment by dstftw** [comment]
I don't see any problem here. By using `expected_status` you treat potentially failed outcomes as normal thus you should be ready for consequences like closed connection. It's the responsibility of a client code to check whether connection was closed or not in such cases.
Also if you want error then don't use `expected_status` and catch exception instead. The whole point of `expected_status` is to simplify code in cases when success and failure are both expressed in the same way. For example, when `_download_json` always returns JSON (e.g. for 404 and for 403) so that in 403 scenario you don't need to catch `HTTPError`, read output and parse it in client code.

**Comment by puxlit** [comment]
@dstftw, we're not talking about a closed connection here, we're talking about the response body being inaccessible, which defeats the point of `expected_status`. The expectation is that if you call `_download_webpage` with `expected_status`, you'll get the response body back if the request was successful _or_ if the response code matches `expected_status`. But this is not the case.
