### ISSUE TITLE
Let --download-archive file contain list of URLs

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#17207]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [X] Question / Request for Change

I was very happy to find the `--download-archive` option, but why does it store things in the non-intuitive format `(source) (id)` rather than the simple and intuitive `(url)`?

This makes it harder to read and manually handle the list, if necessary. For example to add URLs to the list, or copy URLs to share with other people.

Is it possible to change this to containing the downloaded URLs themselves? (While maintaining backwards compatibility with the old format for a good while at least...)

**Comment by dstftw** [comment]
In general URL does not identify the video in a unique way. Several URLs may point to the same video so that storing URLs will break the whole point of download archive.
