### ISSUE TITLE
vimeo embed-only error message is unhelpful

### ISSUE THREAD

**Issue by sramsay64** [rg3/youtube-dl#17209]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

When downloading a video from vimeo that can only be viewed when embedded in a page `youtube-dl` tells me to provide it the embedding url. But it doesn't say how. It should tell me that I need to use the `--referer` option but instead I have to google this every time.

I think [this section in vimeo.py](https://github.com/rg3/youtube-dl/blob/6fc09f0155bae1fd0d3edf31111b37012875b6f2/youtube_dl/extractor/vimeo.py#L492-L494) should be changed to:

```
                        'Cannot download embed-only video without embedding '
                        'URL. Please call youtube-dl with the URL of the page '
                        'that embeds this video using the --referer option.',
```

or something that includes `--referer` somewhere, so users know how to follow the instructions given.

(e.g. "https://player.vimeo.com/video/273870088" in "https://www.publicchristianity.org/episode-1-war-peace-guided-tour/#oldTestament")

**Comment by dstftw** [comment]
I wonder how you even read it. It **clearly** tells you to "call youtube-dl **with** the URL of **the page that embeds** this video", like `youtube-dl https://www.publicchristianity.org/episode-1-war-peace-guided-tour/#oldTestament`.

**Comment by sramsay64** [comment]
That downloads all 11 videos from the page. The command that downloads only the video I told it to download (and the only one I wanted) is `youtube-dl "https://player.vimeo.com/video/273870088" --referer "https://www.publicchristianity.org/episode-1-war-peace-guided-tour/#oldTestament"`. If I use your command I get 10 extra videos that I didn't want (and no indication of which video is the one that I asked for).

Let me clarify why I read it wrong. In the past I've downloaded videos this way (supplying 2 urls) so I knew that such a thing was possible. And I didn't know this video was embed only until I got the error message from running `youtube-dl "https://player.vimeo.com/video/273870088"`. So I knew there was an option but not what it was. Still even if I did follow it literally, I only wanted to download one of the videos

**Comment by dstftw** [comment]
Passing or not passing referer is an implementation detail that should be handled internally by youtube-dl. Today passing referer works tomorrow it will require passing some additional headers/cookies/wahtever making using `--referer` alone useless. On the other hand when you pass the original URL youtube-dl handles this all implicitly. So I won't add such implementation specific messages that may become outdated.

**Comment by sramsay64** [comment]
Yeah, I thought it would be a quick fix. I didn't realise that the implementation is quite complicated.

**Comment by JohnVillalovos** [comment]
I like giving people a hint that using a referer might help them. As the embedding page may require username/password cookies that I don't want to have to figure out. So for me I just use '--referer' option and it works at this time. I figured it out on my own but might have been easier if I had a hint in the error message that it might have worked with '--referer'

**Comment by stordoff** [comment]
FWIW, I agree that this is unclear. I tried:

`C:\Users\user>youtube-dl -F //player.vimeo.com/video/<video>`

And got:

`ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.`

So naturally my first reaction was to try:

`C:\Users\user>youtube-dl -F https://<band-site>/<video>`

And got:

`ERROR: Unsupported URL`

It took me a good few minutes to realise it's behind a log-in wall, so _of course_ youtube-dl can't see it. Altering the message to add something along the lines of "Some videos may require --referer to be set)" would be helpful.
