### ISSUE TITLE
unable to quit q, control-c, esc does not work on mac with brew

### ISSUE THREAD

**Issue by ejonesss** [rg3/youtube-dl#17217]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
i dont have a log since this bug does not produce an error

the video i was trying is https://www.youtube.com/watch?v=MZ_s8zpLYRI&t=7052s

i am on mac osx 10.12 using homebrew and while i can download live streams ok i am unable to stop the stream

i tried the q command and nothing it still continues to download i even tried holding q incase the cpu demand is so high that the keyboard is not being registered and eventually the command will go through   still not happening.

so i try control-c to quit the process like you do on linux and still nothing.

i tried the esc key and nothing.

if i quit or close the terminal i am able to stop the stream but it leaves the files unclosed properly so there are 2 files a  part and a ytd file.

however if i try a normal live stream like https://www.youtube.com/watch?v=ytJb-xDl69U

the q does not work but holding control-c does stop and close the file properly giving me a playable file

the first video is 300+ hours long and i wanted to download a few minutes so i could calculate how big it is but i suspect it may be using a different streaming method than most others

if i try a normal youtube video and then control-c while it does not close the file properly and leaves a part file however quicktime is able to play the partial file if i rename it to omit the "part" from the name

every thing is up to date as i am able to get the stream capture to work without problems
thanks for the help
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
Ctrl+C should work fine. It may take some time though.

**Comment by ejonesss** [comment]
nope that did not work it continued to download until  it finished normally.

it looks like it is not as live as it claims
\
