### ISSUE TITLE
Status of BitChute support

### ISSUE THREAD

**Issue by mnn** [rg3/youtube-dl#17214]
I have found a heavily censored and locked issue #14052 with only one response which seems to reply to deleted comments (also many other issues which are all closed). I didn't find a roadmap. Is there any progress? Is it even planned or is the original locked issue forgotten and was supposed to be closed (the one comment suggests there is some disagreement about whether it should included at all)?

I really dislike disallowing commenting on issues...

**Comment by dstftw** [comment]
The issue was locked due to flood. We have no roadmaps, everyone works on issues he prefer.
