### ISSUE TITLE
f303 VP9 stream with lower bitrate than f299 has higher total file size? bestvideo defaults to f299 seemingly because of this

### ISSUE THREAD

**Issue by incorpusyehtee** [rg3/youtube-dl#17229]
## Please follow the guide below

- [ x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**
- [ x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x ] Question

---

`-f bestvideo+bestaudio` is defaulting to picking, in the case of one particular video, a 6.01GiB f299 MP4 over a 6.74GiB f303 VP9 stream for me.

    youtube-dl -F https://www.youtube.com/watch?v=mZVAl_cwsik

Also the total size of the video streams or the bitrates of the video streams appear to be inaccurate? Lower bitrate = higher total size?

    303          webm       1920x1080  1080p60 5212k , vp9, 60fps, video only, 6.74GiB
    299          mp4        1920x1080  1080p60 6779k , avc1.64002a, 60fps, video only, 6.01GiB

**Comment by dstftw** [comment]
Total bitrate is preferred over filesize. Metadata is provided as is, whether it's accurate or not is up to Youtube.
