### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by AndiLeni** [rg3/youtube-dl#17257]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Hello,
I would like to convert my YouTube videos and take the metadata with me. For the conversion I use a batch script with the following command:
``ffmpeg -i "%%f" -ab 320k -map_metadata:g:0 0:s:0``
However, I don't manage to edit all kinds of files like this.
Either the metadata of.m4a files or from the others is missing. I think it's the g (global) and s (stream) parameters. How can I fix this?

Regards
Andi

**Comment by dstftw** [comment]
Address this question to ffmpeg support.
