### ISSUE TITLE
cwtv.com not working now

### ISSUE THREAD

**Issue by rellik31** [rg3/youtube-dl#17256]
cw is not downloading the correct episodes anymore
any video that you try to get downloads a 30 sec video clip saying update the cw app

there is no error log 
if anyone else tries go download a video from any cw series they should also get the video message 

can you please fix this a.s.a.p

thank you

http://www.cwtv.com/shows/the-100/the-warriors-will/?play=d7857786-f312-45d3-a63b-c36ba8401138

youtube-dl.exe -f hls-2100-0 http://www.cwtv.com/shows/the-100/the-warriors-will/?play=d7857786-f312-45d3-a63b-c36ba8401138

**Comment by tylerforesthauser** [comment]
I know this might not be too helpful but it's working fine for me. I was able to get the entire episode "Damocles - Part Two" from your link above without issue. I barely know what I'm talking about but my first troubleshooting step would be to try a VPN or different network and see if you still encounter the issue. Beyond that, I'm not sure what could be causing your issue.

**Comment by rellik31** [comment]
yes if you just use that url it will download the last episode but if you put in the url for any of the other 4 episodes it wont download them i will edit the post to stop the confusion

**Comment by rellik31** [comment]
youtube-dl.exe -f hls-2100-0 http://www.cwtv.com/shows/the-100/the-warriors-will/?play=d7857786-f312-45d3-a63b-c36ba8401138

that will download the 30 sec video about the cw app same thing happens with other cw shows

**Comment by tylerforesthauser** [comment]
I see. You are correct, that does not work.

However, I've had success instead searching for the m3u8 link itself...

`youtube-dl https://3aa37dc0e8bb47e08042e0ebb25acb34.dlvr1.net/nosec/The_CW/835/1001/29866565699/The100-510-TheWarriorsWill-T2713560-CW.m3u8` works just fine, for instance.

You can find this link by opening up your Developer Tools and using the Network tab and searching for "m3u8". See screenshot.

![screen shot 2018-08-16 at 5 08 19 pm](https://user-images.githubusercontent.com/1226786/44239552-25abdb00-a177-11e8-88ff-c9423e2a2314.png)

**Comment by rellik31** [comment]
hi, thanks for the reply i did look at the tools network tab but its confusing am new to understanding streaming links is there a more simply way of getting the url that will download the videos?

if not could you please give me the download url for this video?
http://www.cwtv.com/shows/the-outpost/one-is-the-loneliest-number/?play=556e8e95-4724-44a0-a6c7-28b397e0914b

thanks
