### ISSUE TITLE
download from vrt with .mpd reports No video formats found;

### ISSUE THREAD

**Issue by MyRoGeertGit** [rg3/youtube-dl#17268]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

### Debug output:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://ondemand-vrt.akamaized.net/content/vod/vid-4f3fe390-c370-4a35-9815-0b42012aacf8-CDN_2/vid-4f3fe390-c370-4a35-9815-0b42012aacf8-CDN_2_drm_2b71830b-5
69e-433d-8d04-b2610853f401.ism/.mpd', '--output', 'RoccoEISuoiFratelli.mp4']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] .mpd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] .mpd: Downloading webpage
[generic] .mpd: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with
 the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\generic.py", line 2331, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 1281, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be su
re to call youtube-dl with the --verbose flag and include its complete output.
```
### Content of .mpd-file

[mpd.txt](https://github.com/rg3/youtube-dl/files/2299466/mpd.txt)

### Vrt-related notes
Vrt is only accessible in Belgium or with a valid Vrt-account in Europe.
The file is accessible up to 8 september 2018.
Please let me know, if I could help you further to test this issue.

**Comment by MyRoGeertGit** [comment]
@dstftw Why did you closed the issue?

**Comment by stinkteeth** [comment]
When I attempted to check the video;
`https://www.vrt.be/vrtnu/a-z/rocco-e-i-suoi-fratelli/1960/rocco-e-i-suoi-fratelli/`

It states that it expired on August 16th.  Is this the correct video?
