### ISSUE TITLE
Download temporary direct YouTube media links in chunks

### ISSUE THREAD

**Issue by ritiek** [rg3/youtube-dl#17278]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

In the recent past, YouTube began throttling download speeds which was workaround in https://github.com/rg3/youtube-dl/issues/15271#issuecomment-362834889 by downloading the media in chunks. This works well when passing YouTube video URL, for example this command downloads without any speed throttle:
```
$ youtube-dl https://www.youtube.com/watch?v=AOeY-nDp7hI -x
```
but the speed throttling comes back if using (temporary) direct YouTube media link, for example this throttles:
```
$ youtube-dl https://r5---sn-ci5gup-pmjs.googlevideo.com/videoplayback?sparams=clen%2C...
```

It would be nice if youtube-dl could automatically detect if such given URLs belong to YouTube and enable chunk based downloading so these direct URLs won't throttle either.

You could confirm the throttling using this general command:
```
$ youtube-dl -o "my_song.%(ext)s" $(youtube-dl https://www.youtube.com/watch?v=AOeY-nDp7hI -x -g)
```

My use case is that sometimes, I only have access (temporary) direct YouTube media link and I need to quickly download a video/audio to local but the throttling increases download times by a big factor. :(

**Comment by dstftw** [comment]
You should not use temporary links directly in the first place. Even if you use (you must also pass cookies and headers) you can enforce this option manually.
Bare temporary URL is not enough to decide whether it will be throttled or not.

**Comment by ritiek** [comment]
I am stupid. Since youtube-dl provides an option `--http-chunk-size` which can be set to `10485760` which is the default value in youtube-dl.

https://github.com/rg3/youtube-dl/blob/9e21e6d96bed929ba57b8ce775e2a0e29e54dd60/youtube_dl/extractor/youtube.py#L1859-L1860

So, one would do:
```
$ youtube-dl --http-chunk-size 10485760 https://r5---sn-ci5gup-pmjs.googlevideo.com/videoplayback?sparams=clen%2C...
```
for full speed downloads!
