### ISSUE TITLE
[-i mode insufficent]  ExtractorError: This video is unavailable.

### ISSUE THREAD

**Issue by Cokemonkey11** [rg3/youtube-dl#17286]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
youtube-dl RDEMww6ZEHgLhQ-8eu_x7Z-FJw -v -i -f m4a --restrict-filenames --no-mtime -o '%(epoch)s.%(id)s.%(title).40s.%(ext)s'

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'RDEMww6ZEHgLhQ-8eu_x7Z-FJw', u'-v', u'-i', u'-f', u'm4a', u'--restrict-filenames', u'--no-mtime', u'-o', u'%(epoch)s.%(id)s.%(title).40s.%(ext)s']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.9 (CPython) - Linux-4.4.38-v7+-armv7l-with-debian-8.0
[debug] exe versions: avconv 11.12-6, avprobe 11.12-6
[debug] Proxy map: {}
WARNING: Unable to extract video title
ERROR: This video is unavailable.
Traceback (most recent call last):
 File \"/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py\", line 792, in extract_info
 ie_result = ie.extract(url)
 File \"/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py\", line 502, in extract
 ie_result = self._real_extract(url)
 File \"/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py\", line 1886, in _real_extract
 raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.
```

---

When using -i mode, it is expected that errors such as the one above are skipped.

However, it seems that youtube-dl is having an issue even expecting the error.

**Comment by dstftw** [comment]
There is nothing to skip. You didn't provide a playlist URL.

**Comment by Cokemonkey11** [comment]
Incorrect.

Here's the original URI:

https://www.youtube.com/watch?v=kXYiU_JCYtU&start_radio=1&list=RDEMww6ZEHgLhQ-8eu_x7Z-FJw

**Comment by dstftw** [comment]
Now compare with what you actually pass to youtube-dl.
