### ISSUE TITLE
Decrypt a DRM protected file if you have the credentials  ?

### ISSUE THREAD

**Issue by nj-neer** [rg3/youtube-dl#17291]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video : https://hss-od.snl-lv3.canalplus-cdn.net/replay/csat/ssd/csa100027418-canal.fr-1051735-1-vr-hd-tosv/canal-fr-1051735-1-VR-HD-TOSV.ism

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I was wondering if there is a way to download an "decrypted" version of a video if you have the credentials.

The link above is an ISM feed

If i give my credentials, the file is downloaded without any problem (to the ISMV format) but is unreadable due to the DRM protection.

Since i am authenticated to the website, i have access to what seem to be the license key  ![Licence](https://i.imgur.com/WaqR0zg.png)

Is there a way to "pass it" to Youtube-DL ? i can't find anything related to ISM protection on the documentation

**Comment by dstftw** [comment]
Not possible.
