### ISSUE TITLE
Ignore "time_continue" parameters in youtube's URL

### ISSUE THREAD

**Issue by kaikaiiiiiii** [rg3/youtube-dl#17292]
In some cases we exploring webpages and see a youtube video. It's interesting and we click the Youtube Logo to watch the video on youtube's own site.

In these cases the url will mostly have another parameters "time_stamp=xxx", like:

https://www.youtube.com/watch?time_continue=50&v=qbcppLD0Kl0

It will make a error if you paste the url directly to youtube-dl in command line.

Imho it should be enough just ignoring the parameter, making the url to be https://www.youtube.com/watch?<del>time_continue=50&</del>v=qbcppLD0Kl0.

**Comment by dstftw** [comment]
It's already ignored.

**Comment by kaikaiiiiiii** [comment]
![youtube-dl_time_continue_error](https://user-images.githubusercontent.com/1635138/44464948-b63e5b80-a64e-11e8-9f01-be4eb820a1b3.jpg)

Well, that might be the other error, then. I'm using the version 2018.8.22.0 for windows.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
