### ISSUE TITLE
Vk video not working ?

### ISSUE THREAD

**Issue by userazer** [rg3/youtube-dl#17295]
than you for responding , but when i try to open a vk video per example 
http://secret-falls-85795.herokuapp.com/api/play?url=https://vk.com/video-1922697_171930679
it gives me this msg 

{
  "error": "ERROR: Video -1922697_171930679 does not exist."
}

**Comment by userazer** [comment]
can you least say something ?

**Comment by dstftw** [comment]
Bother to read issue template and provide all required info.
