### ISSUE TITLE
not working after downloading webpage

### ISSUE THREAD

**Issue by vagisha08** [rg3/youtube-dl#17303]
after downloading webpage it is not proceeding. i have searched and done everything
![snipaste_2018-08-22_22-47-51](https://user-images.githubusercontent.com/30805051/44479354-feb14580-a65d-11e8-9051-06e9d9843739.png)

**Comment by dstftw** [comment]
Obviously a network issue on your side. Try forcing IP v4 `-4`.

**Comment by vagisha08** [comment]
what is that

**Comment by vagisha08** [comment]
??????????????????
