### ISSUE TITLE
Bad archive in downloads [2018.08.22]

### ISSUE THREAD

**Issue by birdie-github** [rg3/youtube-dl#17300]
https://github.com/rg3/youtube-dl/releases/download/2018.08.22/youtube-dl is malformed.

For some reasons it contains this string as its first line:

```
#!/usr/bin/env python
```

This is patently wrong. Please fix the archive (`tail -n +2 youtube-dl > youtube-dl.fixed` will do) and reupload.

**Comment by dstftw** [comment]
It's not an archive in the first but rather a zipped python executable app.

**Comment by birdie-github** [comment]
It's a **zip archive** and nothing else. Python won't be able to run it.

Please check yourself.

**Comment by dstftw** [comment]
Wrong: https://docs.python.org/3/library/zipapp.html#the-python-zip-application-archive-format.
