### ISSUE TITLE
a Question ?

### ISSUE THREAD

**Issue by sami12S** [rg3/youtube-dl#17307]
Thanks man for the hard work , by any chance does the program offre a feature to download youtube videos with a direct link ?  per example i use this link :
http://secret-falls-85795.herokuapp.com/api/play?url=cqyziA30whE
to download this YouTube video
https://www.youtube.com/watch?v=cqyziA30whE

**Comment by dstftw** [comment]
```
-g, --get-url                    Simulate, quiet but print URL
```
