### ISSUE TITLE
ABC iview URL changes

### ISSUE THREAD

**Issue by Bobifet** [rg3/youtube-dl#17311]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.22*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.22**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\> youtube-dl_20180822 -v https://iview.abc.net.au/show/thunderbirds-are-go/series/2/video/ZW0953A007S00
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://iview.abc.net.au/show/thunderbirds-ar
e-go/series/2/video/ZW0953A007S00']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.08.22
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2017-12-21-5a6e753, ffprobe git-2017-12-21-5a6e
753, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 1.132.154.28 (AU) as X-Forwarded-For.
[abc.net.au:iview] ZW0953A007S00: Downloading JSON metadata
[abc.net.au:iview] ZW0953A007S00: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsjdqsmfs\bu
ild\youtube_dl\extractor\common.py", line 599, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsjdqsmfs\bu
ild\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt
...
<end of log>
```

---

---

No longer working - urls recently changed format for this site and latest version of you-tube-dl does not appear to support them.

**Comment by remitamine** [comment]
```
youtube-dl https://iview.abc.net.au/show/thunderbirds-are-go/series/2/video/ZW0953A007S00
[abc.net.au:iview] ZW0953A007S00: Downloading JSON metadata
[abc.net.au:iview] ZW0953A007S00: Downloading webpage
[abc.net.au:iview] ZW0953A007S00: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 133
[download] Destination: Series 2 Ep 7 Up From The Depths - Part Two-ZW0953A007S00.mp4
[download]   0.2% of ~223.98MiB at 187.52KiB/s ETA 01:10:17
```

**Comment by Bobifet** [comment]
Interesting.
Your "cant-reproduce" tag inspired me to experiment some more.
I tried the same command with the same URL on an old Windows XP machine and it works fine.
But the same command with the same URL continues to report the same error on a Windows 7 machine.
Five days ago I had no problems with iview on this Windows 7 machine but now no iview URLs work.
However youtube-dl appears to work fine for all other sites so the problem seems specific to iview.
Have installed no Windows 7 updates in the last five days.
Have disabled both McAfee and Windows Defender with no change.
Have made no other configuration changes to this Windows 7 machine that I am aware of.
If no one else is experiencing this problem then I am at a loss to explain.

**Comment by Bobifet** [comment]
Problem appears to be resolved.
Root cause was a System Clock which was approximately 20 minutes slower than local time.
Correcting the system clock resolved the problem.  Manually setting the system clock back by 20 minutes reproduced the problem.
However why the system clock issue only appeared to affect iview remains a curiosity.  During the past week, when presumably my system clock was incorrect, it did not appear to affect any other sites.
