### ISSUE TITLE
Download Channel, only MP4,max480p?

### ISSUE THREAD

**Issue by mrkapqa** [rg3/youtube-dl#17319]
Hello ,

i would like to download an entire channel with youtube-dl ,

but only in Mp4 480p to playback in Ipod/Ipad and Frontrow

here is my line

youtube-dl --ignore-errors --write-sub -f 'bestvideo[height<=480]+bestaudio/best[height<=480]' https://www.youtube.com/channel/UCa1DxhJDIx1gyVrRuWRuPMw --embed-subs 

it seems however that it downloads also mkv or webm when mp4 480p not downloadable.

Is there any postprocessing option available to get the job done ONLY mp4 + max480p + embed subs?

Thank you very much who reads this!

**Comment by mrkapqa** [comment]
I would like to download every single item on the channel, and around 80 % seem in mp4 480p available, but some seem to be prefered in mkv or webm. Thank you .

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#format-selection-examples

**Comment by mrkapqa** [comment]
this seems viable

 youtube-dl --ignore-errors --write-sub -f "bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]/best" https://www.youtube.com/channel/UCdQma4IKtiaZFT8LscKn_sw --embed-subs --merge-output-format mp4
