### ISSUE TITLE
ERROR "...Video format URL is invalid, skipping..."

### ISSUE THREAD

**Issue by jawidjrs** [rg3/youtube-dl#17310]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.22*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
            .
           .d$ .
           d$$  :
          .$$$
          :$$$   :         Download multiple courses
          $$$$   :       at a time, just paste all the
          $$$$   :         urls in Bulk Download.txt
         .$$$$
         :$$$$    :
         $$$$$    :
         :    $$$$$           You can change your
         :    $$$$$       preferences in settings.json
        .:    $$$$$.
       / :    $$$$: \
      /  :    $$$$:  \
     '        $$$$`   '
     |   /:   $$$$\   |
     |  /     $$$` \  |
     |_/   :__$$P   \_|    🏄

1. Paste course url or
2. Press enter for Bulk Download
https://www.lynda.com/Programming-Foundations-tutorials/Foundations-Programming-Databases/412845-2.html

[92mUsing username and password combination for download

Course Name     Programming Foundations: Databases
Course id       412845
Author Name     Simon Allardice
Topics          #Developer      #Programming Foundations        #Databases
Softwares       None
Duration        3h 11m
Release Date    9/30/2015
Downloaded On   22/August/2018
Course URL      https://www.lynda.com/Programming-Foundations-tutorials/Foundations-Programming-Databases/412845-2.html

🌟  info.txt created

Creating Chapters:

00. Introduction
01. Understanding Databases
02. Database Fundamentals
03. Database Modeling  Tables
04. Database Modeling  Relationships
05. Database Modeling  Optimization
06. Database Modeling  Querying
07. Database Modeling  Indexing and Optimization
08. Database Options
09. Conclusion

✅  10 chapters created!!

👍🏻  CONTENT.md created.

[lynda:course] Downloading signin page
[lynda:course] Submitting email
[lynda:course] Submitting password
[lynda:course] 412845: Downloading course JSON
[download] Downloading playlist: Programming Foundations: Databases
[lynda:course] playlist Programming Foundations: Databases: Collected 40 video ids (downloading 40 of them)
[download] Downloading video 1 of 40
[lynda] Downloading signin page
[lynda] 438411: Downloading video JSON
[lynda] 438411: Checking 0-360 video format URL
[lynda] 438411: Checking 0-540 video format URL
[lynda] 438411: Checking 0-720 video format URL
[lynda] 438411: Checking 1-360 video format URL
[lynda] 438411: 1-360 video format URL is invalid, skipping
[lynda] 438411: Checking 1-540 video format URL
[lynda] 438411: 1-540 video format URL is invalid, skipping
[lynda] 438411: Checking 1-720 video format URL
[lynda] 438411: 1-720 video format URL is invalid, skipping
[info] Writing video subtitles to: C:\Users\Jawid Payanda\Videos\Lynda\Programming Foundations - Databases\01 - Welcome.en.srt
[download] Destination: C:\Users\Jawid Payanda\Videos\Lynda\Programming Foundations - Databases\01 - Welcome.mp4
[download] 100% of 20.44MiB in 00:50
[download] Downloading video 2 of 40
[lynda] 438412: Downloading video JSON
[lynda] 438412: Checking 0-360 video format URL
[lynda] 438412: Checking 0-540 video format URL
[lynda] 438412: Checking 0-720 video format URL
[lynda] 438412: Checking 1-360 video format URL

```

---

### Description of your *issue*, suggested solution and other information

I am using Lyndor-master for Lynda.com video downloader in windows 10 for about two weeks from now. lately I encountered an issue on which command line pauses during the process and it takes unknown time to download each individual videos for URLs. I talked about this issue with the Lyndor programmer and he/she refered me to contact you. FYI I have the latest pip, youtube-dl and Lyndor program updated.

**Comment by dstftw** [comment]
So what? Contact its support not us.
