### ISSUE TITLE
Virus total : 3 positive on youtube.exe windows binary 

### ISSUE THREAD

**Issue by lioobayoyo** [rg3/youtube-dl#17326]
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

After downloading the latest windows binary youtube-dl.exe here :  https://yt-dl.org/latest/youtube-dl.exe

I scanned it with VirusTotal, and 3 positive results were shown (3 anti-virus that were suspicious about a risk of Trojan)

results from VirusTotal here : 

https://www.virustotal.com/en/file/51444f81fc0db9d528e1b6db9c727dd9f06752072fa7a88b1b1a30084082cb87/analysis/1535117583/

Can someone confirm that the binary is the correct one, (SHA256 : 51444f81fc0db9d528e1b6db9c727dd9f06752072fa7a88b1b1a30084082cb87 )

and double check if there wasn't some creepy thing injected at some point ?

(otherwise I might go for the long solution... download virtual box + install a linux vm + use linux :D .... if the linux version is not infected either :/  )

**Comment by dstftw** [comment]
http://rg3.github.io/youtube-dl/download.html, page bottom.
