### ISSUE TITLE
Unable to filter videos by size

### ISSUE THREAD

**Issue by TaktakTaktouk** [rg3/youtube-dl#17337]
I know this question was posted many times but I still not able to prevent user to download videos bigger than 1G. 
I tried with `--max-filesize` but it doesn't work with all URL example: https://www.pscp.tv/w/1vAGRENywWYKl
and `--match-filter "filesize < 1073741824"` always return `does not pass filter filesize < 1073741824, skipping ..`
Any other solution?
`youtube-dl --version : 2018.08.22 `

**Comment by dstftw** [comment]
There is no filesize metadata for pscp.tv.

**Comment by TaktakTaktouk** [comment]
Is there any universal solution to prevent user to download big videos?
