### ISSUE TITLE
[ documentation related] -o  'template '  is wrong in documentation .  works with " dbl quoestes

### ISSUE THREAD

**Issue by blackholeearth** [rg3/youtube-dl#17339]
in documentation    -o  'template blalba '  is  doesnt work .   it works with "template "  (double quotes).

i tried to figuare out that  

.nice app.  donest download exisiting vid , nice feature . i did lot of parameter mistake to download a playlist.  it would have been such a hge waste to download them again.

thanks again

**Comment by dstftw** [comment]
That depends on your shell.
