### ISSUE TITLE
Can I get file extension of the specific format code?

### ISSUE THREAD

**Issue by GourangaDas** [rg3/youtube-dl#17348]
I have code like below:

**youtube-dl.exe "https://xxxxxxx.xxxxx/xxxxx" -f 140 -g --get-title**

With this code I can get the title along with the download address. But I need to know the video file extension of the format code (i.e. 140) like mp4 or 3gp or mkv.

How can I achieve this?

**Comment by dstftw** [comment]
`--get-filename` or parse `--dump-json`.

**Comment by GourangaDas** [comment]
Thank you
