### ISSUE TITLE
[YoutubeDL] Display verbose video titles in formats list output

### ISSUE THREAD

**Issue by parmjitv** [rg3/youtube-dl#17357]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.22*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

$ youtube-dl -vF https://www.youtube.com/watch?v=3wj9jq8s36s
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://www.youtube.com/watch?v=3wj9jq8s36s']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.22
[debug] Python version 2.7.9 (CPython) - Linux-3.16.0-4-686-pae-i686-with-debian-8.7
[debug] exe versions: ffmpeg 3.2.4-1, ffprobe 3.2.4-1
[debug] Proxy map: {}
[youtube] 3wj9jq8s36s: Downloading webpage
[youtube] 3wj9jq8s36s: Downloading video info webpage
**[info] Available formats for 3wj9jq8s36s:**
format code  extension  resolution note
249          webm       audio only DASH audio   64k , opus @ 50k, 53.67MiB
250          webm       audio only DASH audio   80k , opus @ 70k, 67.24MiB
171          webm       audio only DASH audio  135k , vorbis@128k, 121.56MiB
140          m4a        audio only DASH audio  136k , m4a_dash container, mp4a.40.2@128k, 140.85MiB
251          webm       audio only DASH audio  187k , opus @160k, 169.60MiB
160          mp4        256x144    144p  118k , avc1.4d400c, 30fps, video only, 100.74MiB
278          webm       256x144    144p  124k , webm container, vp9, 15fps, video only, 91.16MiB
133          mp4        426x240    240p  255k , avc1.4d4015, 30fps, video only, 213.21MiB
242          webm       426x240    240p  269k , vp9, 30fps, video only, 206.33MiB
243          webm       640x360    360p  550k , vp9, 30fps, video only, 384.01MiB
134          mp4        640x360    360p  658k , avc1.4d401e, 30fps, video only, 542.59MiB
244          webm       854x480    480p  912k , vp9, 30fps, video only, 675.45MiB
135          mp4        854x480    480p 1214k , avc1.4d401f, 30fps, video only, 1004.20MiB
247          webm       1280x720   720p 2091k , vp9, 30fps, video only, 1.37GiB
136          mp4        1280x720   720p 2631k , avc1.4d401f, 30fps, video only, 1.90GiB
302          webm       1280x720   720p60 3069k , vp9, 60fps, video only, 2.32GiB
298          mp4        1280x720   720p60 3583k , avc1.4d4020, 60fps, video only, 2.91GiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 90.31MiB
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2, 250.50MiB
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 737.35MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 768.51MiB
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)

It would be nice to show all video titles in the formats list output - option switch (-F) in YoutubeDL.

i.e. [info] Available formats for PC Longplay [333] Doom 3 BFG Edition (part 1 of 4)-3wj9jq8s36s:

This would be very useful when working with playlists, partcularly when troubleshooting the various sorting algorithms.

See also outdated issue #6850 for further details.

Cheers,

Parmjit V.

**Comment by dstftw** [comment]
No, as this will break code relying on current format.

**Comment by parmjitv** [comment]
@dstftw - You may wish to also close issue #6850 and PR #11296, as these are now redundant as well.  Cheers!
