### ISSUE TITLE
Error 'module' object has no attribute when test download

### ISSUE THREAD

**Issue by kimnamcham** [rg3/youtube-dl#17356]
I tried with already finished extractor like StreamangoIE and StreamcloudIE. Both crashed with the same error.

> MacBook-Pro:test MinhDV$ python test_download.py streamango.Streamango
> Traceback (most recent call last):
>   File "test_download.py", line 265, in <module>
>     unittest.main()
>   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 94, in __init__
>     self.parseArgs(argv)
>   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 149, in parseArgs
>     self.createTests()
>   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 158, in createTests
>     self.module)
>   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
>     suites = [self.loadTestsFromName(name, module) for name in names]
>   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
>     parent, obj = obj, getattr(obj, part)
> AttributeError: 'module' object has no attribute 'streamango'

Same issues in topic #13266

**Comment by dstftw** [comment]
It's `TestDownload.test_Streamango` not `streamango.Streamango`.
