### ISSUE TITLE
youtube-dl can't download YT Videos, other sites work

### ISSUE THREAD

**Issue by IBaydenI** [rg3/youtube-dl#17355]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.22*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
Youtube-Log (User Interrupted)

$ youtube-dl -v https://www.youtube.com/watch?v=O5XtZe2z8BA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=O5XtZe2z8BA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.22
[debug] Python version 2.7.13 (CPython) - Linux-4.14.62+-armv6l-with-debian-9.4
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] O5XtZe2z8BA: Downloading webpage
[youtube] O5XtZe2z8BA: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r3---sn-8xgn5uxa-i5hl.googlevideo.com/videoplayback?expire=1535339900&mime=video%2Fwebm&requiressl=yes&clen=1752923516&txp=1301222&ipbits=0&itag=313&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&lmt=1535150339558173&fvip=3&mv=m&gir=yes&mt=1535318260&ms=au%2Crdu&id=o-AN1bYhW56Ucy3cEh1Ds10zegmeSq_tE2RT6YFVr248Ou&ei=HBmDW-3ELYbt1gK6jIsY&pl=40&source=youtube&keepalive=yes&dur=913.512&ip=2001%3A16b8%3A6414%3A6f01%3Aebf7%3A6059%3A4cc3%3A9b4c&key=yt6&mn=sn-8xgn5uxa-i5hl%2Csn-i5heen7l&signature=08EC7AD228CE2D9D698D04567D01C33D26C4AA61.B7E13103D249E0E42F6D9B4811DB17CE33059999&mm=31%2C29&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&initcwndbps=1227500&c=WEB&ratebypass=yes'

Vimeo-Log

$ youtube-dl -v https://vimeo.com/channels/staffpicks/285779587
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://vimeo.com/channels/staffpicks/285779587']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.22
[debug] Python version 2.7.13 (CPython) - Linux-4.14.62+-armv6l-with-debian-9.4
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 285779587: Downloading webpage
[vimeo] 285779587: Extracting information
[vimeo] 285779587: Downloading webpage
[vimeo] 285779587: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 285779587: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 285779587: Downloading fastly_skyfire m3u8 information
[vimeo] 285779587: Downloading akfire_interconnect_quic MPD information
[vimeo] 285779587: Downloading akfire_interconnect_quic MPD information
[vimeo] 285779587: Downloading fastly_skyfire MPD information
[vimeo] 285779587: Downloading fastly_skyfire MPD information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1535322996-0x063b43b40fa35d9407ab35e276b188d29193aa4e/285779587/sep/video/1077180011,1077180019,1077180012,1077180000/../'
[dashsegments] Total fragments: 33
[download] Destination: Ancient Scotland-285779587.fdash-fastly_skyfire_sep-video-1077180012.mp4
[download] 100% of 93.84MiB in 00:43
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1535322996-0x063b43b40fa35d9407ab35e276b188d29193aa4e/285779587/sep/video/1077180011,1077180019,1077180012,1077180000/../'
[dashsegments] Total fragments: 33
[download] Destination: Ancient Scotland-285779587.fdash-fastly_skyfire_sep-audio-1077180011.m4a
[download] 100% of 3.20MiB in 00:09
[ffmpeg] Merging formats into "Ancient Scotland-285779587.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Ancient Scotland-285779587.fdash-fastly_skyfire_sep-video-1077180012.mp4' -i 'file:Ancient Scotland-285779587.fdash-fastly_skyfire_sep-audio-1077180011.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Ancient Scotland-285779587.temp.mp4'
Deleting original file Ancient Scotland-285779587.fdash-fastly_skyfire_sep-video-1077180012.mp4 (pass -k to keep)
Deleting original file Ancient Scotland-285779587.fdash-fastly_skyfire_sep-audio-1077180011.m4a (pass -k to keep)


...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

My issue is, I can download videos from i.e. Vimeo, but not Youtube, Youtube-dl will get stuck at the above provided point and has to be user interrupted. I have tried different Youtube videos, none work. Earlier I got the following error "_ssl.c:645: The handshake operation timed out" but this has since disappeared.

**Comment by indywatch** [comment]
aliasd@melbourne:~/Desktop/extra/Video/TV$ youtube-dl -v https://www.youtube.com/watch?v=O5XtZe2z8BA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=O5XtZe2z8BA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.22
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-132-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] O5XtZe2z8BA: Downloading webpage
[youtube] O5XtZe2z8BA: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r8---sn-uxanug5-ntq6.googlevideo.com/videoplayback?dur=913.512&pl=16&initcwndbps=890000&source=youtube&requiressl=yes&c=WEB&gir=yes&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&expire=1535367762&key=yt6&mime=video%2Fwebm&ipbits=0&lmt=1535322250026057&itag=313&fvip=6&mv=m&mt=1535345984&signature=988CD8D60C52CF498B82C668C0AEEB468C9D36C2.9C74912D6DCC9C7543F6ACD2135FF6C262ED105B&ms=au%2Crdu&mn=sn-uxanug5-ntq6%2Csn-ntq7yn76&mm=31%2C29&txp=5532332&keepalive=yes&id=o-AKafbv10hSKxSkS2AnN3DSW2K6TWklxEtba1yRxzGrC1&clen=1356130483&ip=1.129.109.234&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ei=8oWDW_CPI4vUgAOmy5zwBg&ratebypass=yes'
[download] Destination: Antec DF500 RGB, MSI Gaming TrioX 1080Ti & Intel 8086k Build + Benchmarks-O5XtZe2z8BA.f313.webm
[download]   0.1% of 1.26GiB at 250.35KiB/s ETA 01:28:04^C
ERROR: Interrupted by user

**Comment by dstftw** [comment]
`--force-ipv4`.

**Comment by IBaydenI** [comment]
worked, thanks
