### ISSUE TITLE
Downloads from PeerTube should use torrents, HTTP is rate limited

### ISSUE THREAD

**Issue by scanlime** [rg3/youtube-dl#17368]
- [x] Feature request (request for a new functionality)

I'm an administrator of a PeerTube instance, and I've noticed that youtube-dl has support for PeerTube. This is great!

However, it seems to download via a single HTTP connection, whereas PeerTube expects clients to use WebTorrent in order to share the bandwidth load. A client that uses only HTTP connections won't be as fast as a torrent-capable client, and a client that uses only a single HTTP connection will be hitting the server's per-connection rate limit, which is set to 800 kB/s by default.

It would be great if youtube-dl could discover the torrent link instead of the HTTP seed, to avoid overloading the single origin server.

Re test videos, there are many PeerTube instances listed at:
https://instances.joinpeertube.org/instances

My own instance is diode.zone, and a sample URL for a long video that might be a good performance test:
https://diode.zone/videos/watch/2f1544f6-3a3b-4cd0-bb72-c57d2e2d1e9b

**Comment by dstftw** [comment]
Torrents are out of scope of youtube-dl.
