### ISSUE TITLE
Support Eurosport Player

### ISSUE THREAD

**Issue by beta2k** [rg3/youtube-dl#17365]
Can the [Eurosport Player](http://eurosportplayer.de) be supported? For instance, I would like to download the following video for personal use: https://at.eurosportplayer.com/en/event/court-12/453b4459-3b6e-44dd-a278-3b6617791875

I have an account, if credentials are needed, I can provide them.

**Comment by raffam** [comment]
This would be a useful feature. What additional information do you need? @remitamine

**Comment by raffam** [comment]
1. I can do that
2. Maybe you can use a free VPN service?
3. Maybe we can ask people to lend their own account?
4. How can I check that? I was able to download a ".ts" file from the website using [this extension](https://chrome.google.com/webstore/detail/hds-hls-video-downloader/gelfgldejnhgpjcbnfpkglhpelajafao?hl=en), but VLC is unable to play the file

**Comment by remitamine** [comment]
when I write those points, it's not just about me(I'm not necessarily the one that will work on it).

> I can do that.

you can create an issue then.

> Maybe you can use a free VPN service?

I do have access to the website.

> Maybe we can ask people to lend their own account?

I'm not going to ask anyone for his account, if someone wants to provide an account for testing he can initiate the contact.

> How can I check that? I was able to download a ".ts" file from the website using this extension, but VLC is unable to play the file

there is no universal method to know(most of the time it can be checked in the manifest that contain segments links), it depends on the service.

**Comment by raffam** [comment]
@remitamine thanks!

[1800_complete-trimmed.m3u8.txt](https://github.com/rg3/youtube-dl/files/2545119/1800_complete-trimmed.m3u8.txt)
[master_desktop_complete-trimmed.m3u8.txt](https://github.com/rg3/youtube-dl/files/2545120/master_desktop_complete-trimmed.m3u8.txt)

I attach the file `master_desktop_complete-trimmed.m3u8" which should contain the links to the m3u8 files at various bitrates, and "1800_complete-trimmed.m3u8" which should contain the link to the chunks of the 896x504 resolution.

In particular, in "1800_complete-trimmed.m3u8", it appears
```
#EXT-X-KEY:METHOD=AES-128,URI="https://drm-api.svcs.eurosportplayer.com/events/c3b50e14-0460-4441-800f-2c57726b2b28/media/d83973bd-e8e0-4f09-8613-c7b969fe6299/keys/ff29190b-d594-4877-bb8f-58a75d88e3b7",IV=0x6D5D481697F98E2A4852FBA178E91EBD
#EXTINF:5,
```

So it is my understanding it is encrypted with AES-128? How can I download the public key?

The link to the URI dows not work for me. It says "Connection refused"

**Comment by remitamine** [comment]
from the manifests that you have posted there is no indication that they really use DRM, the manifests are similar to the ones used by RTBF, which require different cookies for obtaining the keys from the ones used for the segments(even thought that you didn't post the original urls):
```
#EXTM3U
#EXT-X-VERSION:1
## Created with Unified Streaming Platform(version=1.8.5)
#EXT-X-MEDIA-SEQUENCE:192657986
#EXT-X-TARGETDURATION:8
#USP-X-TIMESTAMP-MAP:MPEGTS=3486398384,LOCAL=2018-11-03T16:51:21Z
#EXT-X-PROGRAM-DATE-TIME:2018-11-03T16:51:21Z
#EXT-X-KEY:METHOD=AES-128,URI="https://www.rtbf.be/api/drm/aeskey?stream_name=ladeux"
#EXTINF:8, no desc
ladeux_aes-audio_1=128000-video=2000000-192657986.ts
```

**Comment by remitamine** [comment]
> Posting the HAR of the manifests and the key would help?

you can try to export cookies and pass them to youtube-dl with the manifest URL.

**Comment by raffam** [comment]
I have managed to crack it down. My preliminary work is (here)[https://github.com/raffam/eurosportplayer-dl]. May main problem is how to find the URL of the master playlist file starting from the URL of the video. Actually the script requires you to find the URL of the master playlist file manually. For the rest we should be covered :) Nice journey

**Comment by beta2k** [comment]
Any update on this?

**Comment by TheManchineel** [comment]
EuroSport Player has no DRM, look at [this ](https://github.com/JinRonin/plugin.video.eurosportplayer) open source client written in Python for Kodi, implementation should be trivial.

**Comment by beta2k** [comment]
see also: https://github.com/raffam/eurosportplayer-dl/

**Comment by TheManchineel** [comment]
Looks like it's already done then, we just need to import eurosportplayer-dl code into youtube-dl lol

**Comment by raffam** [comment]
As the author of eurosportplayer-dl (and user of youtube-dl!) I might be able to help with that?

**Comment by remitamine** [comment]
> we just need to import eurosportplayer-dl code into youtube-dl lol

no, this is not the way things are done in the project, the support has to be added directly in youtube-dl, no external dependencies.

**Comment by frederic1** [comment]
Hello, I'm reopening this topic to ask for EurosportPlayer support. We are numerous to ask for it, it would be wonderful if the authors were able to implement it to their fantastic script.

**Comment by GTKSSR** [comment]
Hello, I have the same request as frederic1. It would be great if you could add support for EurosportPlayer. Both Eurosportplayer-dl and youtube-dl don't work now with new player on Eurosportplayer.com.

**Comment by L4yer** [comment]
i too wopuld like to request support for eurosport player.
