### ISSUE TITLE
Can't download playlist on Windows

### ISSUE THREAD

**Issue by itsdpm** [rg3/youtube-dl#17373]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.28**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=wpZHi7o30_8']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.08.28
[debug] Python version 3.7.0 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] wpZHi7o30_8: Downloading webpage
[youtube] wpZHi7o30_8: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r1---sn-5jucgv5qc5oq-qxae.googlevideo.com/videoplayback?ms=au%2Crdu&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mv=m&mt=1535531268&lmt=1471889452532511&ip=49.207.102.1&c=WEB&expire=1535553029&id=o-AMORIrLDXYWHDIhkYW3UQtpVVOekfLhpQWY0iv0LZEaV&dur=343.701&mn=sn-5jucgv5qc5oq-qxae%2Csn-qxa7snee&mm=31%2C29&ipbits=0&key=yt6&mime=video%2Fmp4&source=youtube&initcwndbps=1083750&requiressl=yes&itag=22&ei=pFmGW9HNM9Wl8QPW66V4&ratebypass=yes&signature=3A130E33B7B208A17A2F99CB2C2E50CFD6A78A2F.C0A9DD232820153AE689584C0179B04B946A6F0F&pl=18&fvip=1'
[download] Learn the Top 25 Must-Know Brazilian Portuguese Nouns-wpZHi7o30_8.mp4 has already been downloaded
[download] 100% of 83.97MiB
'list' is not recognized as an internal or external command,
operable program or batch file.
'index' is not recognized as an internal or external command,
operable program or batch file.
<end of log>
```

Only the video in the in the link was downlaoded, the rest of the videos could not be. The error is mentioned above. Could you help me understand what went wrong, what I did wrong?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
