### ISSUE TITLE
site support request for podcasts on site zeit.de

### ISSUE THREAD

**Issue by sjjh** [rg3/youtube-dl#17375]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.28*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.28**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[user@host:~/Downloads$ ./youtube-dl -v "https://www.zeit.de/wissen/2018-08/sprachforschung-sprache-urkilogramm-gewaesser-podcast"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.zeit.de/wissen/2018-08/sprachforschung-sprache-urkilogramm-gewaesser-podcast']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.28
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-33-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] sprachforschung-sprache-urkilogramm-gewaesser-podcast: Requesting header
WARNING: Falling back on generic information extractor.
[generic] sprachforschung-sprache-urkilogramm-gewaesser-podcast: Downloading webpage
[generic] sprachforschung-sprache-urkilogramm-gewaesser-podcast: Extracting information
ERROR: Unsupported URL: https://www.zeit.de/wissen/2018-08/sprachforschung-sprache-urkilogramm-gewaesser-podcast
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2324, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 33, column 162
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3294, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.zeit.de/wissen/2018-08/sprachforschung-sprache-urkilogramm-gewaesser-podcast

user@host:~/Downloads$ 
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.zeit.de/wissen/2018-08/sprachforschung-sprache-urkilogramm-gewaesser-podcast
- Playlist: https://www.zeit.de/serie/woher-weisst-du-das

---

### Description of your *issue*, suggested solution and other information

Not sure if "playlist" support is possible; support for single podcasts would be fine enough, I believe. :)

**Comment by kebabkalle** [comment]
Are these podcasts video podcasts? If you just want the audio you can get it from the rss feed. https://zeit-wissen.podigee.io/feed/aac

**Comment by sjjh** [comment]
> Are these podcasts video podcasts? If you just want the audio you can get it from the rss feed. https://zeit-wissen.podigee.io/feed/aac
Audio only -- I just failed to find the rss feed... Sorry for the noise!
