### ISSUE TITLE
Where do I enter --cookies FILE command?

### ISSUE THREAD

**Issue by hasnogaems** [rg3/youtube-dl#17389]
Here is command that not working because It premium content and required cookie, question is where should I put the command?
youtube-dl.exe --ffmpeg-location C:\Users\anonimous\Desktop\ffmpeg\ffmpeg-20180404-2accdd3-win64-static\ffmpeg-20180404-2accdd3-win64-static\bin --hls-prefer-native https://cdn-video.pvgna.com/782/original-1487910128-1080p/1080p.m3u8

**Comment by dstftw** [comment]
Same place you enter any other command. Note that passing cookies does not guarantee it will work.

**Comment by hasnogaems** [comment]
@dstftw path is this "C:\Users\anonimous\Desktop\ffmpeg\ffmpeg-20180404-2accdd3-win64-static\ffmpeg-20180404-2accdd3-win64-static\bin" or this "F:/twitch download/bin/cookies.txt"?

**Comment by hasnogaems** [comment]
@dstftw if I put it in quotes spaces is not a problem anymore? And the --cookies command itself I put in valid order?

**Comment by hasnogaems** [comment]
@dstftw now this error
youtube-dl.exe --ffmpeg-location C:\Users\anonimous\Desktop\ffmpeg\ffmpeg-20180404-2accdd3-win64-static\ffmpeg-20180404-2accdd3-win64-static\bin --cookies "F:/twitch download/bin/cookies.txt" --hls-prefer-native https://cdn-video.pvgna.com/782/original-1487910128-1080p/1080p.m3u8

**Comment by hasnogaems** [comment]
@dstftw now when I put path in ' ' instead of " " I get this hardcore error. I need to update or something?
`youtube-dl.exe --ffmpeg-location C:\Users\anonimous\Desktop\ffmpeg\ffmpeg-20180404-2accdd3-win64-static\ffmpeg-20180404-2accdd3-win64-static\bin --cookies 'F:/twitch download/bin/cookies.txt' --hls-prefer-native https://cdn-video.pvgna.com/782/original-1487910128-1080p/1080p.m3u8`

**Comment by dstftw** [comment]
Maybe you'll finally start reading my posts?
>Note that passing cookies alone **does not guarantee it will work** in the first place.
