### ISSUE TITLE
你好，爱奇艺的视频无法下载

### ISSUE THREAD

**Issue by huangzhen920** [rg3/youtube-dl#17399]
可以下载：http://www.iqiyi.com/v_19rqzajv5s.html
但不能下载：http://www.iqiyi.com/w_19rweuyxop.html
两个地址的区别在于：v_和w_
还望大家补充一下

**Comment by gt-sun** [comment]
现在这两个都不能下载了

**Comment by luyang93** [comment]
https://www.iqiyi.com/v_19rqzkfkhw.html
这个是电视剧里的一集,无法下载
但是比如像一些简短的,没有版权的采访之类的,可以下载
