### ISSUE TITLE
allow selecting source IP

### ISSUE THREAD

**Issue by mojiz** [rg3/youtube-dl#174]
Hi

Is it possible to select the source IP through an option? My linux server has multiple IP addresses. Curl and Wget have options which allow me to download a file using any of my IPs but it seems you're using neither of them.
if possible please add a source IP like this:

--interface eth0:1 
or --interface 192.168.1.5

Thanks

**Comment by phihag** [comment]
In current versions of youtube-dl (see [our FAQ](https://yt-dl.org/update) if you need help updating) this possible via the `--source-address` option.
