### ISSUE TITLE
youtube-dl unable to download a playlist, dunno the reason 

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#17409]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.28*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.28**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
/usr/local/bin$ ./youtube-dl --version
2018.08.28
```

```
/usr/local/bin$ ./youtube-dl -v -c -f 22 "https://www.youtube.com/playlist?list=PLhk2InOhK1bccqgUhR31u2Sqffmwv9iLv"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-c', u'-f', u'22', u'https://www.youtube.com/playlist?list=PLhk2InOhK1bccqgUhR31u2Sqffmwv9iLv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.28
[debug] Python version 2.7.15 (CPython) - Linux-4.17.0-3-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0.2-1, ffprobe 4.0.2-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLhk2InOhK1bccqgUhR31u2Sqffmwv9iLv: Downloading webpage
[download] Downloading playlist: Mist Survival - Click here for the Playlist (S01)(Gameplay/Let's Play)
[youtube:playlist] playlist Mist Survival - Click here for the Playlist (S01)(Gameplay/Let's Play): Downloading 22 videos
[download] Downloading video 1 of 22
[youtube] pTzKz8gJMWg: Downloading webpage
[youtube] pTzKz8gJMWg: Downloading video info webpage
[debug] Invoking downloader on u'https://r3---sn-cnoa-2o9e.googlevideo.com/videoplayback?mv=m&source=youtube&ms=au%2Crdu&fvip=3&ei=EzqKW7LOL4GcowOXkoqQBQ&lmt=1534584031733220&ip=117.195.80.28&pl=20&itag=22&dur=1576.054&initcwndbps=241250&mt=1535785433&mime=video%2Fmp4&mn=sn-cnoa-2o9e%2Csn-cvh76nez&mm=31%2C29&c=WEB&ipbits=0&ratebypass=yes&key=yt6&signature=7DA968251235CEDF961F57D78D4514A54C343EC8.B8A654BC9CF623DDB0EC908D8FDACC9FCF1E9FD6&requiressl=yes&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&id=o-ABMP9nqCpJ9tfvI_qiQpN8CkLEP5_R7Jmw1jHyvxUGGy&expire=1535807092'
[download] Resuming download at byte 741038


ERROR: Did not get any data blocks
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "./youtube-dl/youtube_dl/__init__.py", line 472, in main
    _real_main(argv)
  File "./youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 803, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1002, in process_ie_result
    extra_info=extra)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 864, in process_ie_result
    extra_info=extra_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 803, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 857, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1635, in process_video_result
    self.process_info(new_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1908, in process_info
    success = dl(filename, info_dict)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "./youtube-dl/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "./youtube-dl/youtube_dl/downloader/http.py", line 312, in download
    self.report_error('Did not get any data blocks')
  File "./youtube-dl/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 620, in report_error
    self.trouble(error_message, tb)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 582, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by shirishag75** [comment]
I tried --print-traffic and got this partial output while downloading - 

```
reply: 'HTTP/1.1 206 Partial Content\r\n'
header: Last-Modified: Sat, 18 Aug 2018 09:20:31 GMT
header: Content-Type: video/mp4
header: Date: Sat, 01 Sep 2018 07:18:59 GMT
header: Expires: Sat, 01 Sep 2018 07:18:59 GMT
header: Cache-Control: private, max-age=21299
header: Content-Range: bytes 741038-286302205/286302206
header: Accept-Ranges: bytes
header: Content-Length: 285561168
header: Connection: close
header: Alt-Svc: quic=":443"; ma=2592000; v="44,43,39,35"
header: X-Content-Type-Options: nosniff
header: Server: gvs 1.0

```

**Comment by dstftw** [comment]
Format 22 is not available youtube side.

**Comment by shirishag75** [comment]
Then how come it shows that it's available using - 

$ youtube-dl -F "https://www.youtube.com/playlist?list=PLhk2InOhK1bccqgUhR31u2Sqffmwv9iLv"
[youtube:playlist] PLhk2InOhK1bccqgUhR31u2Sqffmwv9iLv: Downloading webpage
[download] Downloading playlist: Mist Survival - Click here for the Playlist (S01)(Gameplay/Let's Play)
[youtube:playlist] playlist Mist Survival - Click here for the Playlist (S01)(Gameplay/Let's Play): Download```
ing 23 videos
[download] Downloading video 1 of 23
[youtube] pTzKz8gJMWg: Downloading webpage
[youtube] pTzKz8gJMWg: Downloading video info webpage
[info] Available formats for pTzKz8gJMWg:
format code  extension  resolution note
249          webm       audio only DASH audio   53k , opus @ 50k, 9.45MiB
250          webm       audio only DASH audio   65k , opus @ 70k, 11.03MiB
171          webm       audio only DASH audio  117k , vorbis@128k, 18.13MiB
251          webm       audio only DASH audio  123k , opus @160k, 20.57MiB
140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k, 23.87MiB
278          webm       256x144    144p  105k , webm container, vp9, 30fps, video only, 13.76MiB
160          mp4        256x144    144p  126k , avc1.4d400c, 30fps, video only, 14.34MiB
242          webm       426x240    240p  231k , vp9, 30fps, video only, 28.23MiB
133          mp4        426x240    240p  286k , avc1.4d4015, 30fps, video only, 31.45MiB
243          webm       640x360    360p  422k , vp9, 30fps, video only, 51.94MiB
134          mp4        640x360    360p  639k , avc1.4d401e, 30fps, video only, 72.45MiB
244          webm       854x480    480p  780k , vp9, 30fps, video only, 93.42MiB
135          mp4        854x480    480p 1281k , avc1.4d401f, 30fps, video only, 135.94MiB
247          webm       1280x720   720p 1557k , vp9, 30fps, video only, 186.66MiB
136          mp4        1280x720   720p 2600k , avc1.4d401f, 30fps, video only, 269.65MiB
302          webm       1280x720   720p60 2702k , vp9, 60fps, video only, 315.80MiB
248          webm       1920x1080  1080p 2734k , vp9, 30fps, video only, 347.12MiB
298          mp4        1280x720   720p60 3556k , avc1.4d4020, 60fps, video only, 426.80MiB
303          webm       1920x1080  1080p60 4458k , vp9, 60fps, video only, 583.26MiB
137          mp4        1920x1080  1080p 5091k , avc1.640028, 30fps, video only, 518.48MiB
299          mp4        1920x1080  1080p60 5981k , avc1.64002a, 60fps, video only, 771.97MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 13.08MiB
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2, 36.87MiB
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 104.11MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 123.58MiB
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)

```

**Comment by dstftw** [comment]
Availability on this list does not mean anything - it's just what youtube reports. Whether it's actually available or not can only be determined during actual download. As for traceback, it's not a traceback per se but intentionally printed traceback output in verbose mode.
