### ISSUE TITLE
Checking for ffmpeg twice

### ISSUE THREAD

**Issue by zaza42** [rg3/youtube-dl#17416]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

When running youtube-dl (without any parameters) it always checks ffmpeg and ffprobe versions twice.
```
07:10:23.367241     25388 /usr/bin/python /usr/local/bin/youtube-dl
07:10:23.459397       25389 /sbin/ldconfig -p
07:10:23.549655       25390 stty size
07:10:23.582957       25393 ffmpeg -version
07:10:23.634771       25394 ffprobe -version
07:10:23.687911       25397 ffmpeg -version
07:10:23.734922       25398 ffprobe -version

```
I think it's useless to check versions of binaries twice. 
I'd be happy with a `--force-ffmpeg-version=4.0.2` parameter, for skip checking binaries on every run. (I run a dozens of youtube-dl per one second)

**Comment by dstftw** [comment]
If you run it without any parameters it should not check anything. If you run it with `-v` it will check each executable once for debug output. It may output it twice due to `avconv`/`avprobe` symlinked to `ffmpeg` counterparts on your OS. Read issue template and provide complete verbose log along with `strace` output.

**Comment by zaza42** [comment]
Ok, i have a `/etc/youtube-dl.conf` which contains
`--add-metadata
--embed-thumbnail` 
parameters. Each of them checking for ffmpeg once. Can it be one check at all? Or no check at all with a parameter?
