### ISSUE TITLE
Unfinished Part/Fragment merge

### ISSUE THREAD

**Issue by StinutsPeanuts** [rg3/youtube-dl#17412]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.28*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.28**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

A while ago I tried to download a couple of videos, that were going to be unavailable after a short period of time. I let it download overnight and went to sleep. When I returned the playlist was downloaded, except for 2 videos.

For each of the two (uncompleted videos) I have the same 'filestructure'. There's a part file, a Part-Frag file, a YTDL file and the complete video file (without audio).

I hoped I could just redownload the video, but it was taken down already (so there's no possible way I can get the URL back). Is there any possible way I could merge these files together to 'complete' the download?

Here's a screenshot for 1 video's output and its separate files:
![output](https://user-images.githubusercontent.com/39425214/44945185-deaf1e00-ade3-11e8-9988-fde373be782c.PNG)

**Comment by dstftw** [comment]
Video file is a completely downloaded video. m4a.part is a partially downloaded audio. Merge these, though you'll obviously have audio cut off.
