### ISSUE TITLE
Will --audio-quality 0 create unnecessary / fake high bitrate?

### ISSUE THREAD

**Issue by ZYinMD** [rg3/youtube-dl#17410]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.28*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.28**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: [u'--output', u'/mnt/d/Music/%(uploader)s - %(upload_date)s - %(title)s.%(ext)s', u'--extract-audio', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'--embed-thumbnail', u'--no-playlist', u'--limit-rate', u'3M', u'-v']
[debug] Command-line args: [u'--config-location', u'/root/projects/youtube-dl-configs/youtube-song.conf', u'https://www.youtube.com/watch?v=bKEta9NZC90']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.10
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.4.0-17134-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2
[debug] Proxy map: {}
[youtube] bKEta9NZC90: Downloading webpage
[youtube] bKEta9NZC90: Downloading video info webpage
[youtube] {22} signature length 42.40, html5 player vfliK45Zi
[youtube] {43} signature length 42.40, html5 player vfliK45Zi
[youtube] {18} signature length 42.40, html5 player vfliK45Zi
[youtube] {36} signature length 42.40, html5 player vfliK45Zi
[youtube] {17} signature length 42.40, html5 player vfliK45Zi
[youtube] {137} signature length 42.40, html5 player vfliK45Zi
[youtube] {248} signature length 42.40, html5 player vfliK45Zi
[youtube] {136} signature length 42.40, html5 player vfliK45Zi
[youtube] {247} signature length 42.40, html5 player vfliK45Zi
[youtube] {135} signature length 42.40, html5 player vfliK45Zi
[youtube] {244} signature length 42.40, html5 player vfliK45Zi
[youtube] {134} signature length 42.40, html5 player vfliK45Zi
[youtube] {243} signature length 42.40, html5 player vfliK45Zi
[youtube] {133} signature length 42.40, html5 player vfliK45Zi
[youtube] {242} signature length 42.40, html5 player vfliK45Zi
[youtube] {160} signature length 42.40, html5 player vfliK45Zi
[youtube] {278} signature length 42.40, html5 player vfliK45Zi
[youtube] {140} signature length 42.40, html5 player vfliK45Zi
[youtube] {171} signature length 42.40, html5 player vfliK45Zi
[youtube] {249} signature length 42.40, html5 player vfliK45Zi
[youtube] {250} signature length 42.40, html5 player vfliK45Zi
[youtube] {251} signature length 42.40, html5 player vfliK45Zi
[youtube] bKEta9NZC90: Downloading thumbnail ...
[youtube] bKEta9NZC90: Writing thumbnail to: /mnt/d/Music/U2 - Topic - 20170207 - The Troubles.jpg
[debug] Invoking downloader on u'https://r4---sn-gjo-qj5e.googlevideo.com/videoplayback?requiressl=yes&lmt=1518780164375013&itag=251&keepalive=yes&ip=66.44.32.144&dur=285.861&fvip=5&source=youtube&id=o-AK3ZrRetqMIWq2p4jcwXoHHV4JHQBkQH2eQnZBVIiBUe&mime=audio%2Fwebm&expire=1535810799&ipbits=0&initcwndbps=452500&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&gcr=us&c=WEB&gir=yes&mm=31%2C29&mn=sn-gjo-qj5e%2Csn-p5qlsndr&key=yt6&clen=4665145&ei=j0iKW-nYH4XxhgbDn7DwBg&ms=au%2Crdu&mt=1535789026&pl=20&mv=m&signature=E240BF14D184D7ABDE773EDF51BA81377CDF5A1A.59D9B24B6EEA75D057050FEEDB64C6FE9B18E290&ratebypass=yes'
[download] Destination: /mnt/d/Music/U2 - Topic - 20170207 - The Troubles.webm
[download] 100% of 4.45MiB in 00:04
[debug] ffmpeg command line: ffprobe -show_streams 'file:/mnt/d/Music/U2 - Topic - 20170207 - The Troubles.webm'
[ffmpeg] Destination: /mnt/d/Music/U2 - Topic - 20170207 - The Troubles.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:/mnt/d/Music/U2 - Topic - 20170207 - The Troubles.webm' -vn -acodec libmp3lame '-q:a' 0 'file:/mnt/d/Music/U2 - Topic - 20170207 - The Troubles.mp3'
Deleting original file /mnt/d/Music/U2 - Topic - 20170207 - The Troubles.webm (pass -k to keep)
[ffmpeg] Adding thumbnail to "/mnt/d/Music/U2 - Topic - 20170207 - The Troubles.mp3"
[debug] ffmpeg command line: ffmpeg -y -i 'file:/mnt/d/Music/U2 - Topic - 20170207 - The Troubles.mp3' -i 'file:/mnt/d/Music/U2 - Topic - 20170207 - The Troubles.jpg' -c copy -map 0 -map 1 '-metadata:s:v' 'title="Album cover"' '-metadata:s:v' 'comment="Cover (Front)"' 'file:/mnt/d/Music/U2 - Topic - 20170207 - The Troubles.temp.mp3'
```

---

### Description of your *issue*, suggested solution and other information

Hi, I'm using `--extract-audio --audio-format mp3 --audio-quality 0` to download songs from youtube, and with `--audio-quality 0` I can get very high bitrate mp3 files (220+kbps vbr), but since I don't know the original audio quality when it's uploaded, I just wonder: what if the original was just 128 kbps? Would it be converted to a fake high bitrate? I guess it has to do with whether the original audio encoding was mp3? What happens if it was? Would it be just extracted without converting?

I tried to use a program called "spek" (https://github.com/alexkay/spek) to check the real bitrate of my downloads, and it seems that `--audio-quality 0` does have better quality than the default (which I believe is `--audio-quality 5`), but I didn't check many songs.

Thanks!!

**Comment by dstftw** [comment]
It will be upconverted. If the source is already an mp3 no conversion will happen at all.
