### ISSUE TITLE
[njpwworld] Unable to login: HTTP Error 403

### ISSUE THREAD

**Issue by AdmiralDal59** [rg3/youtube-dl#17427]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: ['-v', '-o', 'K:\\videos\\downloads\\%(extractor)s\\%(title)s.%(ext)s', '-a
', 'C:\\apps\\ydl\\cfg\\list.txt', '-f', 'bestvideo[ext=mp4]+bestaudio[ext!=webm]/best', '--writ
e-description', '--write-sub', '--all-subs', '--convert-subs', 'srt', '--ap-mso', 'DTV', '--ap-u
sername', 'PRIVATE', '--ap-password', 'PRIVATE', '--netrc', '--hls-prefer-native', '--referer',
'https://front.njpwworld.com/auth', '--continue']
[debug] Custom config: []
[debug] Command-line args: []
[debug] Batch file urls: ['https://njpwworld.com/p/o_original_0008_334']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.09.01
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-89471-g88e2dc7d04, ffprobe N-89471-g88e2dc7d04, rtmpdump 2.4
[debug] Proxy map: {}
[NJPWWorld] Logging in
ERROR: Unable to login: HTTP Error 403: Forbidden (caused by HTTPError()); please report this is
sue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkzpz548c\build\youtube_dl\e
xtractor\common.py", line 599, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkzpz548c\build\youtube_dl\Y
outubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

NJPW World tweaked their site again a few days ago such that their login page has changed. I tried to use a workaround of stating referer as https://front.njpwworld.com/auth , but it gives 403 error as stated above. I get the same error if no referer is specified. I can give auth credentials via email if you need it.

Sample video: https://njpwworld.com/p/s_series_00490_39_1

**Comment by fido93** [comment]
I have a same problem on udemy as well sad.

**Comment by sawbabe** [comment]
Lol
