### ISSUE TITLE
[crunchyroll] All lans are described as JP

### ISSUE THREAD

**Issue by bato3** [rg3/youtube-dl#17430]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl.exe -F http://www.crunchyroll.com/the-master-of-ragnarok-blesser-of-einherjar/episode-8-the-kotatsu-and-the-empty-bellows-775184
[crunchyroll] 775184: Downloading webpage
[crunchyroll] 775184: Downloading jaJP m3u8 information
[crunchyroll] 775184: Downloading enUS m3u8 information
[crunchyroll] 775184: Downloading esES m3u8 information
[crunchyroll] 775184: Downloading itIT m3u8 information
[crunchyroll] 775184: Downloading frFR m3u8 information
[crunchyroll] 775184: Downloading ruRU m3u8 information
[crunchyroll] 775184: Downloading ptBR m3u8 information
[crunchyroll] 775184: Downloading deDE m3u8 information
[crunchyroll] 775184: Downloading esLA m3u8 information
[crunchyroll] 775184: Downloading media info
[info] Available formats for 775184:
format code      extension  resolution note
hls-jaJP-396-0   mp4        428x240    [jaJP]  396k , avc1.42c015, 23.974fps, mp4a.40.2
hls-jaJP-396-1   mp4        428x240    [jaJP]  396k , avc1.42c015, 23.974fps, mp4a.40.2
hls-jaJP-396-2   mp4        428x240    [jaJP]  396k , avc1.42c015, 23.974fps, mp4a.40.2
hls-ruRU-401     mp4        428x240    [jaJP]  401k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esLA-403-0   mp4        428x240    [jaJP]  403k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esLA-403-1   mp4        428x240    [jaJP]  403k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esLA-403-2   mp4        428x240    [jaJP]  403k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esES-403-0   mp4        428x240    [jaJP]  403k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esES-403-1   mp4        428x240    [jaJP]  403k , avc1.42c015, 23.974fps, mp4a.40.2
<cut>
```

---

### Description of your *issue*, suggested solution and other information

1. For example is 
`hls-esES-403-1   mp4        428x240    [jaJP]  403k , avc1.42c015, 23.974fps, mp4a.40.2`, 

should be 

`... [esES]  403k , ...`

ps.: is possible remove space before coma `403k ,`?

**Comment by remitamine** [comment]
the language in the note is the audio language, not the hard-sub language.

**Comment by vaguiners** [comment]
> the language in the note is the audio language, not the hard-sub language.

No
