### ISSUE TITLE
[youtube] When downloading a playlist and a copyrighted video appears skip it rather than abort it.

### ISSUE THREAD

**Issue by chriscn** [rg3/youtube-dl#17435]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.01**

This issue specifically relates to `youtube-dl`, I often will download playlists which may contain copyrighted videos. A reoccurring issue is that if the playlist does indeed contain a copyrighted video that has been removed; youtube-dl will abort the playlist rather than just skipping it.

**Comment by dstftw** [comment]
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```

**Comment by chriscn** [comment]
Oh that easy! Thank you <3
