### ISSUE TITLE
YouTube provides 1080p video, but youtube-dl downloads 720p

### ISSUE THREAD

**Issue by djmangoo** [rg3/youtube-dl#17444]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.01**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of this *issue*?
- [x] Bug report

---

### Verbose output

```console
C:\Videos> youtube-dl -v https://www.youtube.com/watch?v=AXzDele4aBo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=AXzDele4aBo']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.09.01
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] AXzDele4aBo: Downloading webpage
[youtube] AXzDele4aBo: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r1---sn-8p2hvcpax-cxbs.googlevideo.com/videoplayback?c=WEB&ipbits=0&fvip=5&ratebypass=yes&initcwndbps=491250&expire=1536192825&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mime=video%2Fmp4&itag=22&mt=1536171091&mn=sn-8p2hvcpax-cxbs%2Csn-nv47lnsd&mm=31%2C29&signature=183C396BF771D8D5346A54A7AC16B443A7328849.6D48A064D8ADBE78A6B41BFECF57116F2DAE2227&key=yt6&id=o-AAhBBCWO7YiHJfod-3ybvKBl8GVl96MIsJbWcZI5gj-g&requiressl=yes&ip=ip_address_redacted&pl=22&mv=m&dur=156.084&source=youtube&lmt=1531623581618129&ms=au%2Crdu&ei=2RyQW5aVLI6K1wKf7IfYBA'
[download] Destination: Nightcore - Se Tu Vuoi-AXzDele4aBo.mp4
[download] 100% of 3.97MiB in 00:14
```

---

### Description of the *issue*, suggested solution and other information

**Description of the issue**

The video is available in 1080p on YouTube, but the downloaded file is in 720p. Passing option `-f` (as suggested in the readme) gives the error `ERROR: requested format not available`

**Suggested solution**

Have no idea.

**Other information**

Just a side note: I removed my ip address from the verbose output, hope it is not mandatory for triaging the issue.

**Comment by dstftw** [comment]
Install ffmpeg.

**Comment by djmangoo** [comment]
Whoops, sorry. Actually my ffmpeg was installed, but it wasn't in PATH.

Thanks!
