### ISSUE TITLE
Soundcloud: unable to obtain file audio codec with ffprobe

### ISSUE THREAD

**Issue by e11bits** [rg3/youtube-dl#17496]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--extract-audio', '-o', '/var/local/archive/proprietary/music/downloaded/youtube/soundcloud_moodyzwenatributetokerrichandlerparttwomixedbymoodyzwen.mov', 'https://soundcloud.com/moodyzwen/a-tribute-to-kerri-chandler-part-two-mixed-by-moodyzwen']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.08
[debug] Python version 3.6.3 (CPython) - Linux-4.13.0-46-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: avconv 3.3.4-2, avprobe 3.3.4-2, ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] moodyzwen/a-tribute-to-kerri-chandler-part-two-mixed-by-moodyzwen: Resolving id
[soundcloud] moodyzwen/a-tribute-to-kerri-chandler-part-two-mixed-by-moodyzwen: Downloading info JSON
[soundcloud] 497093556: Downloading track url
[soundcloud] 497093556: Downloading m3u8 information
[soundcloud] 497093556: Downloading m3u8 information
[soundcloud] 497093556: Checking download video format URL
[soundcloud] 497093556: Checking http_mp3_128_url video format URL
[soundcloud] 497093556: Checking hls_mp3_128_url video format URL
[soundcloud] 497093556: Checking hls_opus_64_url video format URL
[debug] Invoking downloader on 'https://api.soundcloud.com/tracks/497093556/download?client_id=LvWovRaJZlWCHql0bISuum8Bd2KX79mb'
[download] /var/local/archive/proprietary/music/downloaded/youtube/soundcloud_moodyzwenatributetokerrichandlerparttwomixedbymoodyzwen.mov has already been downloaded
[download] 100% of 229.70MiB
[debug] ffmpeg command line: ffprobe -show_streams file:/var/local/archive/proprietary/music/downloaded/youtube/soundcloud_moodyzwenatributetokerrichandlerparttwomixedbymoodyzwen.mov
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2047, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 243, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

The Soundcloud downloader can download the file from soundcloud, but seems to fail to convert/extract the audio after the download.

**Comment by dstftw** [comment]
Do not hardcode extension in output template.

**Comment by e11bits** [comment]
Can confirm, that using %(ext)s in the template makes this go away. This is the change for the example from the bug description:

> youtube-dl -v --extract-audio -o '/var/local/archive/proprietary/music/downloaded/youtube/soundcloud_moodyzwenatributetokerrichandlerparttwomixedbymoodyzwen.**mov**' 'https://soundcloud.com/moodyzwen/a-tribute-to-kerri-chandler-part-two-mixed-by-moodyzwen'


> youtube-dl -v --extract-audio -o '/var/local/archive/proprietary/music/downloaded/youtube/soundcloud_moodyzwenatributetokerrichandlerparttwomixedbymoodyzwen.**%(ext)s**' 'https://soundcloud.com/moodyzwen/a-tribute-to-kerri-chandler-part-two-mixed-by-moodyzwen'


Thanks for the super quick help @dstftw and sorry for the confusion.
