### ISSUE TITLE
Exported mp3 file sampling rate problem

### ISSUE THREAD

**Issue by Hitsounds** [rg3/youtube-dl#17493]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-playlist', '--default-search', 'ytsearch', '--format', 'bestaudio[ext=m4a]', '--extract-audio', '--audio-format', 'mp3', '--add-metadata', '-o', '13471849318416175427.mp3', 'https://www.youtube.com/watch?v=nksfBbEfOD0']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.08
[debug] Python version 3.6.6 (CPython) - Linux-4.4.0-1027-aws-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 4.0.2-static, ffprobe 4.0.2-static
[debug] Proxy map: {}
ERROR:     Last message repeated 1 times
 Traceback (most recent call last):
   File "/app/.heroku/python/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2047, in post_process
     files_to_delete, info = pp.run(info)
   File "/app/.heroku/python/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 465, in run
     self.run_ffmpeg_multiple_files(in_filenames, temp_filename, options)
   File "/app/.heroku/python/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
     raise FFmpegPostProcessorError(msg)
 youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:     Last message repeated 1 times 
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I have been trying to add bitrate, sample rate and length to the extracted audio files as otherwise the mp3 file does not play well with audacity which seems to think the audio file is only a few seconds long.  So I am using the --add-metadata however it throws this error. I am wondering if I am doing something wrong as no matter what I try the mp3 won't work well with audacity or google play music.

**Comment by Hitsounds** [comment]
https://transfer.sh/4xtVx/13471849318416175427.mp3
Heres an example. It plays fine on the transfer.sh and groove music
![image](https://user-images.githubusercontent.com/17516655/45257487-0af80b00-b39f-11e8-8aba-ca7e191a2840.png)

 however trying to use it with audacity will result in 
![image](https://user-images.githubusercontent.com/17516655/45257467-c9676000-b39e-11e8-84dd-b3d43a2915ac.png)

and uploading to google play music 
![image](https://user-images.githubusercontent.com/17516655/45257478-ed2aa600-b39e-11e8-83d8-c48ce724269b.png)
.
I'm not sure what i am doing wrong.

**Comment by dstftw** [comment]
Do not hardcode extension in output template.

**Comment by Hitsounds** [comment]
Thank you soo much. For some reason I didn't think that would be the problem! Also thanks for the quick reply!
