### ISSUE TITLE
YoutubeSearch: unable to obtain file audio codec with ffprobe (might be missing codec for video format 0x31307661)

### ISSUE THREAD

**Issue by e11bits** [rg3/youtube-dl#17506]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--extract-audio', '-o', '/var/local/archive/proprietary/music/downloaded/youtube/ytsearch_childishgambinosummertimemagic.%(ext)s', 'ytsearch:Childish Gambino Summertime Magic']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.08
[debug] Python version 3.6.3 (CPython) - Linux-4.13.0-46-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: avconv 3.3.4-2, avprobe 3.3.4-2, ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:search] query "Childish Gambino Summertime Magic": Downloading page 1
[download] Downloading playlist: Childish Gambino Summertime Magic
[youtube:search] playlist Childish Gambino Summertime Magic: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] F1B9Fk_SgI0: Downloading webpage
[youtube] F1B9Fk_SgI0: Downloading video info webpage
[youtube] {22} signature length 41.42, html5 player vflvABTsY
[youtube] {43} signature length 41.42, html5 player vflvABTsY
[youtube] {18} signature length 41.42, html5 player vflvABTsY
[youtube] {36} signature length 41.42, html5 player vflvABTsY
[youtube] {17} signature length 41.42, html5 player vflvABTsY
[youtube] {137} signature length 41.42, html5 player vflvABTsY
[youtube] {248} signature length 41.42, html5 player vflvABTsY
[youtube] {136} signature length 41.42, html5 player vflvABTsY
[youtube] {247} signature length 41.42, html5 player vflvABTsY
[youtube] {135} signature length 41.42, html5 player vflvABTsY
[youtube] {244} signature length 41.42, html5 player vflvABTsY
[youtube] {397} signature length 41.42, html5 player vflvABTsY
WARNING: Unknown codec av01.0.05M.08
[youtube] {134} signature length 41.42, html5 player vflvABTsY
[youtube] {243} signature length 41.42, html5 player vflvABTsY
[youtube] {396} signature length 41.42, html5 player vflvABTsY
WARNING: Unknown codec av01.0.05M.08
[youtube] {133} signature length 41.42, html5 player vflvABTsY
[youtube] {242} signature length 41.42, html5 player vflvABTsY
[youtube] {395} signature length 41.42, html5 player vflvABTsY
WARNING: Unknown codec av01.0.05M.08
[youtube] {160} signature length 41.42, html5 player vflvABTsY
[youtube] {278} signature length 41.42, html5 player vflvABTsY
[youtube] {394} signature length 39.42, html5 player vflvABTsY
WARNING: Unknown codec av01.0.05M.08
[youtube] {140} signature length 41.42, html5 player vflvABTsY
[youtube] {171} signature length 41.42, html5 player vflvABTsY
[youtube] {249} signature length 41.42, html5 player vflvABTsY
[youtube] {250} signature length 41.42, html5 player vflvABTsY
[youtube] {251} signature length 41.42, html5 player vflvABTsY
[debug] Invoking downloader on 'https://r3---sn-4g5ednll.googlevideo.com/videoplayback?mn=sn-4g5ednll%2Csn-4g5e6nsy&mm=31%2C29&keepalive=yes&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mv=m&mt=1536486947&ms=au%2Crdu&itag=397&ei=Su6UW_S2F4nygAfMg4SgDg&pl=26&mime=video%2Fmp4&txp=5511222&expire=1536508586&initcwndbps=941250&clen=10745141&ip=87.155.49.231&key=yt6&gcr=de&dur=285.666&source=youtube&lmt=1536206510477132&requiressl=yes&ipbits=0&gir=yes&fvip=3&c=WEB&id=o-AFRlBbvJ1uTMCRx2A27sF55FWqjKBm8OJ51CITUaNwgJ&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397&signature=0B5857945BBD33F814FEA450E1F9A497712EAB7F.AD5A22782B65A60586892DD62FC556A715AF434B&ratebypass=yes'
[download] Destination: /var/local/archive/proprietary/music/downloaded/youtube/ytsearch_childishgambinosummertimemagic.mp4

[download]   0.0% of 10.25MiB at 152.48KiB/s ETA 01:10
[download]   0.0% of 10.25MiB at 437.13KiB/s ETA 00:24
[download]   0.1% of 10.25MiB at 1007.52KiB/s ETA 00:10
[download]   0.1% of 10.25MiB at  2.08MiB/s ETA 00:04
[download]   0.3% of 10.25MiB at  1.42MiB/s ETA 00:07
[download]   0.6% of 10.25MiB at  1.74MiB/s ETA 00:05
[download]   1.2% of 10.25MiB at  2.22MiB/s ETA 00:04
[download]   2.4% of 10.25MiB at  2.76MiB/s ETA 00:03
[download]   4.9% of 10.25MiB at  3.39MiB/s ETA 00:02
[download]   9.7% of 10.25MiB at  3.77MiB/s ETA 00:02
[download]  19.5% of 10.25MiB at  3.98MiB/s ETA 00:02
[download]  39.0% of 10.25MiB at  4.19MiB/s ETA 00:01
[download]  78.1% of 10.25MiB at  4.35MiB/s ETA 00:00
[download]  96.6% of 10.25MiB at  4.38MiB/s ETA 00:00
[download]  96.6% of 10.25MiB at 134.72KiB/s ETA 00:02
[download]  96.6% of 10.25MiB at 392.69KiB/s ETA 00:00
[download]  96.6% of 10.25MiB at 898.96KiB/s ETA 00:00
[download]  96.7% of 10.25MiB at  1.86MiB/s ETA 00:00
[download]  96.8% of 10.25MiB at  1.34MiB/s ETA 00:00
[download]  97.2% of 10.25MiB at  1.79MiB/s ETA 00:00
[download]  97.8% of 10.25MiB at  2.18MiB/s ETA 00:00
[download]  99.0% of 10.25MiB at  2.79MiB/s ETA 00:00
[download] 100.0% of 10.25MiB at  3.40MiB/s ETA 00:00
[download] 100% of 10.25MiB in 00:02
[debug] ffmpeg command line: ffprobe -show_streams file:/var/local/archive/proprietary/music/downloaded/youtube/ytsearch_childishgambinosummertimemagic.mp4
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2047, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 243, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

This does download the MP4 file but fails to convert it into an audio file.
Trying mplayer on the MP4 results in "Cannot find codec matching selected -vo and video format 0x31307661."

This could likely be due to a missing codec in ffmpeg et.al. and youtube-dl might not be able to do much about it. Reporting it anyways.

This bug looks like #17496 reported by me but is different.

**Comment by jeeb** [comment]
> WARNING: Unknown codec **av01.0.05M.08**

This is AOMedia's recently bit-stream frozen AV1 (a video format), it looks like youtube-dl is mis-parsing it as an audio track?

You require a very recent FFmpeg (probably master required) with libaom's AV1 decoder linked against it to play this file.

For youtube-dl MPEG-DASH identifier parsing, the MP4 specification for AV1 was very recently standardized as well (1.0.0 tag a day or two ago), and the specification of the codec parameter string is located @ https://aomediacodec.github.io/av1-isobmff/#codecsparam .

**Comment by e11bits** [comment]
So this will just go away with a more recent FFmpeg and no changes to youtube-dl? Then I should close this issue.
Or does youtube-dl handling of this needs adaptation? Then I leave the issue open.

**Comment by Restia666Ashdoll** [comment]
@jeeb yeah. 2020 and youtube-dl still does not recognize av01.
