### ISSUE TITLE
[Request] Don't download webpage if video identifier matches in archive file

### ISSUE THREAD

**Issue by mjolnir870** [rg3/youtube-dl#17504]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When using the --download-archive feature youtube-dl still downloads each video's webpage. After downloading, the video is skipped based off the identifier that youtube-dl already has from the initial link.

Can this process be changed so that youtube-dl will discard the video as soon as the identifier is matched from the URL? Doing it this way will allow downloads to complete much faster since youtube-dl doesn't have to download potentially hundreds of webpages for a large playlist. The bigger return on this is that it also avoids slamming a video site with hundreds of page requests that are eventually discarded.

Current process:
1. youtube-dl has video with identifier ABCD
2. youtube-dl downloads webpage for video ABCD
3. youtube-dl aborts download of video ABCD since it matches in archive file

Requested process:
1. youtube-dl has video with identifier ABCD
2. youtube-dl aborts download of video ABCD since it matches in archive file

**Comment by dstftw** [comment]
This depends on a particular extractor. It does discard as soon as possible if video id is known beforehand and extractor supports it.

**Comment by mjolnir870** [comment]
Can this be reopened and then specifically be a request for the pornhub extractor to suppor this then? The video URL provides the identifier but the pornhub extractor is still downloading the webpage.

**Comment by mjolnir870** [comment]
Should I open a new issue instead of requesting on this one?

**Comment by dstftw** [comment]
Open a new issue with complete explanation regarding concrete extractor.
