### ISSUE TITLE
Force Channel ID instead of Nickname on Youtube

### ISSUE THREAD

**Issue by selkiess** [rg3/youtube-dl#17528]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

I am trying to download multiple channels from youtube with the channel id in the filename by using the uploader_id in the name. However some channels have nicknames and it is defaulting to that. Is there a way to force the UCxxxxxxxxxxxxxxxx format in the name. I have googled and looked over the documentation and cannot find anything.

**Comment by Selkie707** [comment]
can you point me in the right direction of the duplicate? I can't find it anywhere
