### ISSUE TITLE
Can't get single download link 1080p youtube videos

### ISSUE THREAD

**Issue by GourangaDas** [rg3/youtube-dl#17523]
Here's a issue with Youtube-videos.  This command 
`Youtube-dl -F https://www.youtube.com/watch?v=lciCUTNuEt4`

gives me as below: 
```

[youtube] lciCUTNuEt4: Downloading webpage
[youtube] lciCUTNuEt4: Downloading video info webpage
[info] Available formats for lciCUTNuEt4:
format code  extension  resolution note
249          webm       audio only DASH audio   59k , opus @ 50k, 2.38MiB
250          webm       audio only DASH audio   71k , opus @ 70k, 2.92MiB
171          webm       audio only DASH audio   94k , vorbis@128k, 3.94MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 5.88MiB
251          webm       audio only DASH audio  130k , opus @160k, 5.31MiB
278          webm       256x144    144p   97k , webm container, vp9, 25fps, video only, 4.27MiB
160          mp4        256x144    144p  111k , avc1.4d400c, 25fps, video only, 3.88MiB
242          webm       426x240    240p  230k , vp9, 25fps, video only, 8.91MiB
133          mp4        426x240    240p  340k , avc1.4d4015, 25fps, video only, 7.95MiB
243          webm       640x360    360p  415k , vp9, 25fps, video only, 17.32MiB
134          mp4        640x360    360p  687k , avc1.4d401e, 25fps, video only, 17.16MiB
244          webm       854x480    480p  772k , vp9, 25fps, video only, 31.49MiB
135          mp4        854x480    480p 1289k , avc1.4d401e, 25fps, video only, 36.46MiB
247          webm       1280x720   720p 1510k , vp9, 25fps, video only, 56.74MiB
136          mp4        1280x720   720p 2233k , avc1.4d401f, 25fps, video only, 65.63MiB
248          webm       1920x1080  1080p 2668k , vp9, 25fps, video only, 87.19MiB
137          mp4        1920x1080  1080p 4187k , avc1.640028, 25fps, video only, 93.10MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 3.62MiB
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2, 10.17MiB
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 29.35MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 39.19MiB
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
```
If I want to get 1080p version of this videos I need to call:
(download with Youtube-dl itself):

`youtube-dl -f 137+140 https://www.youtube.com/watch?v=lciCUTNuEt4`

But it's unfortunate that it can't give the single download link of the videos. If I execute the below command to get the link, 
`youtube-dl -f 137+140 https://www.youtube.com/watch?v=lciCUTNuEt4 -g`

It gives me two links, one for format 137 and the second one for format 140. as below:

https://r1---sn-5aap5ojx-jj0l.googlevideo.com/videoplayback?aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&clen=97624145&ipbits=0&ei=tPaVW8-SAu6ioQO2mJ2oBw&c=WEB&key=yt6&mv=m&dur=388.200&mt=1536554555&itag=137&ms=au%2Crdu&initcwndbps=826250&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGBbP1-jqsom08RyYXH6AZPLDs-69BRltNP0QDXCMZJ_&mn=sn-5aap5ojx-jj0l%2Csn-h5576n7k&ip=103.249.37.18&mm=31%2C29&pl=24&lmt=1521057580144454&expire=1536576276&fvip=1&keepalive=yes&requiressl=yes&gir=yes&mime=video%2Fmp4&signature=6A46CE8D7F31676E06959EEB13CFE8201EE428CB.121E1BCFDC12D4F525CC405153BBE690C0116959&ratebypass=yes
https://r1---sn-5aap5ojx-jj0l.googlevideo.com/videoplayback?source=youtube&clen=6167527&ipbits=0&ei=tPaVW8-SAu6ioQO2mJ2oBw&c=WEB&key=yt6&mv=m&dur=388.284&mt=1536554555&itag=140&ms=au%2Crdu&initcwndbps=826250&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGBbP1-jqsom08RyYXH6AZPLDs-69BRltNP0QDXCMZJ_&mn=sn-5aap5ojx-jj0l%2Csn-h5576n7k&ip=103.249.37.18&mm=31%2C29&pl=24&lmt=1521056931360109&expire=1536576276&fvip=1&keepalive=yes&requiressl=yes&gir=yes&mime=audio%2Fmp4&signature=15AD5830AEC36C3AA0A3A544AAECB6A72690AB1D.B3D3CAFDC119670C150364A917055C866CD4AE62&ratebypass=yes

But with **Firefox and IDM** I can get the single link of 1080p version of the videos easily.

Is there any provision to get single download link of all possible combined format using "YOUTUBE-DL"?

**Comment by dstftw** [comment]
You can't. Neither with Firefox not with IDM nor with anything else. There is technically no 1080p single file media hosted on youtube. Max quality single file media is `-f 22` that is 720p.
