### ISSUE TITLE
No sound from downloaded youtube videos

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#1752]
Hi, there is no sound in the videos I downloaded from youtube. Is anyone else having the same issue?

I used this command.

youtube-dl -ct -f 134 youtube_url

Tried playing the video with vlc and umplayer.

**Comment by Vaironl** [comment]
This is an Old Thread, but I believe my answer can help others in the future.

@ikhthiandor was looking for a way to download a specific format. The answer provided by @jaimeMF works, but defeats the purpose of downloading a specific format. Maybe you want a higher quality or lower quality video than what's being downloaded by default.

If you use the following command you can get a specific video format. Unfortunately, if it is DASH video, as already explained, only the video portion will be downloaded.
`
youtube-dl -F [FORMAT#] [YOUTUBELINK]
`

However, if you search for a video format and audio format you want to chain together, I recommend mp4 + m4a (you can chain most audio and video formats), youtube-dl will automatically make it into a video containing audio. You use a similar command to the one above, but simply add the formats together using a +.

E.g
`youtube-dl --format 135+139 "https://www.youtube.com/watch?v=z7IB87xQR7o&t=1304s"`
