### ISSUE TITLE
Udemy - Not organising by chapter when run in batch script

### ISSUE THREAD

**Issue by CUD** [rg3/youtube-dl#17537]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is 
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.10**

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### Description of your *issue*, suggested solution and other information

So I have a batch script that just prompts for the URL by using the 'set' command, setting the URL to %videoURL% so the command that the script ends up calling is:

youtube-dl --cookies ./udemy-cookies.txt -o "%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s" %videoURL%

The problem is that when I paste in the URL when prompted it creates a file named "(chapter_number)s - (playlist_index)s. (ext)s" instead of saving the videos in folders. However, the script works fine if I paste the same command replacing the %videoURL% with the actual URL to the Udemy course.

Any idea why this may be the case?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#output-template-and-windows-batch-files
