### ISSUE TITLE
[Error] unable to download video

### ISSUE THREAD

**Issue by Chaunecy** [rg3/youtube-dl#17536]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [x] Other

---

### Error
there is Error
following is the message:

```
/usr/local/bin/youtube-dl/youtube-dl -o '~/Downloads/%(title)s.%(ext)s' https://www.youtube.com/watch?v=H9j1g5AzOi4
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] H9j1g5AzOi4: Downloading webpage
[youtube] H9j1g5AzOi4: Downloading video info webpage
[youtube] H9j1g5AzOi4: Marking watched
[download] Destination: /Users/name/Downloads/The Lab Disrupts to N.E.R.D's 'Lemon' - World of Dance 2018 (Full Performance).f137.mp4
ERROR: unable to download video
```
Does anybody know the log file location for more details?
Or how to do with this error?

**Comment by dstftw** [comment]
Connectivity issue on your side.
