### ISSUE TITLE
Can't use "-f bestvideo[vcodec=avc]" anymore, (nor "-f bestvideo[vcodec=av1]")

### ISSUE THREAD

**Issue by mzso** [rg3/youtube-dl#17530]
### Description of your *issue*, suggested solution and other information
So trying to set up a command line to download AV1 I noticed that I get stuff like this when viewing formats.

```
397          mp4        854x480    480p  377k , av01.0.05M.08, 24fps, video only, 10.25MiB

135          mp4        854x480    480p  937k , avc1.4d401e, 24fps, video only, 14.82MiB
```

Which makes bestvideo[vcodec=]  useless for AVC and AV1, because they would only match that exact string, and most within AVC have different strings. Previously it worked with just plain bestvideo[vcodec=avc].

(I have version 2018.09.10)

**Comment by remitamine** [comment]
from https://github.com/rg3/youtube-dl#format-selection:
> Also filtering work for comparisons = (equals), != (not equals), **^= (begins with)**, $= (ends with), *= (contains) and following string meta fields:
