### ISSUE TITLE
Amazon?

### ISSUE THREAD

**Issue by lysdexia** [rg3/youtube-dl#1753]
$ youtube-dl -ct http://www.amazon.com/gp/product/B001FCK5GG/ref=avod_yvl_watch_now
[redirect] Following redirect to http://www.amazon.com/Worlds-Fastest-Indian-Anthony-Hopkins/dp/B001FCK5GG
WARNING: Falling back on generic information extractor.
[generic] B001FCK5GG: Downloading webpage
[generic] B001FCK5GG: Extracting information
ERROR: Unsupported URL: http://www.amazon.com/Worlds-Fastest-Indian-Anthony-Hopkins/dp/B001FCK5GG; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
doug@thebadpipsissewah:~$ youtube-dl -ct --verbose http://www.amazon.com/gp/product/B001FCK5GG/ref=avod_yvl_watch_now
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-ct', '--verbose', 'http://www.amazon.com/gp/product/B001FCK5GG/ref=avod_yvl_watch_now']
[debug] youtube-dl version 2013.11.07
[debug] Python version 2.7.5+ - Linux-3.11.0-13-generic-x86_64-with-Ubuntu-13.10-saucy
[debug] Proxy map: {}
[redirect] Following redirect to http://www.amazon.com/Worlds-Fastest-Indian-Anthony-Hopkins/dp/B001FCK5GG
WARNING: Falling back on generic information extractor.
[generic] B001FCK5GG: Downloading webpage
[generic] B001FCK5GG: Extracting information
ERROR: Unsupported URL: http://www.amazon.com/Worlds-Fastest-Indian-Anthony-Hopkins/dp/B001FCK5GG; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 348, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 125, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 212, in _real_extract
    raise ExtractorError(u'Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.amazon.com/Worlds-Fastest-Indian-Anthony-Hopkins/dp/B001FCK5GG; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by github18** [comment]
Anyone feel like working on this?  I have Amazon prime and the streaming player is painful to use.  Seeking back takes like 5-10 secs each use!

If someone feel like making downloading of streaming video's on Amazon work I would be happy to assist with beta testing.  I am a Linux administrator and have some experence coding though not much with Python.

I could also offer a case of your favorite beverage* or gift card upon completion.+

* Provided its within reason
+ Provided its done within a reasonable time frame...  Say within a month from now?

**Comment by iggyvolz** [comment]
I could take a whack at it but:
- I'm terrible at Python (this will probably amount to a lot of trial-and-error on my part :D)
- I'm kinda busy over the next couple months
- Amazon's security department might be over my head.

That being said - I'll give it a go.

**Comment by github18** [comment]
Sounds good, let me know if I can help in any way.

**Comment by github18** [comment]
I forked the youtube-dl repo and started poking at this a bit.  I am not sure how to go about making login work though.  Is there a simple extractor with login somewhere to look at?  I have been poking at the youtube one but its really long to try and read through.  I am not sure how to deal with the cookies and put them back into whatever youtube-dl uses.  Whats the normal practice in making logins work?  I assume there must be some debugging option in youtube-dl that will show you cookies its getting and such?  I have not figured out how to make python print the cookie(s) yet.  Also is there a good way to view each webpage in the login process?  I have just been printing things and piping them into files for viewing but thats a little painful.

I looked at http://stackoverflow.com/questions/18265376/why-i-can-log-in-amazon-website-using-python-mechanize-but-not-requests-or-urll however I am not sure how to intagrate that into youtube-dl.

Any hints would be appreciated.

**Comment by dstftw** [comment]
@github18 for login implementation you can consult [crunchyroll](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/crunchyroll.py#L61), [facebook](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/facebook.py#L55), [noco](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/noco.py#L47), [twitch](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/twitch.py#L135), [udemy](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/udemy.py#L69) or any other extractor with `_login` method inside.
For debugging you may use `--print-traffic` and `--write-pages` for dumping webpages.
You can alternatively provide account credentials to one of the developers.

**Comment by bouchard** [comment]
Some episodes of Amazon TV are available without login (a.k.a. free for a limited time). I would suggest getting it to work with these episodes first, and then working on login?

For example, the new New Yorker show, first episode is free:
http://www.amazon.com/gp/product/B00RR12NFK/ref=atv_terms_dp

**Comment by bouchard** [comment]
Putting a sniffing proxy in front of Amazon Video while watching, you can get the Cloudfront URL where the video is sourced from (should be a file ending in .ism). Silverlight connects to Cloudfront using the Microsoft IIS Smooth Streaming Protocol.

```ruby
#!/usr/bin/env ruby

require 'net/http'

# Microsoft IIS Smooth Streaming Protocol: http://msdn.microsoft.com/en-us/library/ff469334.aspx

def video_segment_url(byte_offset)
  "http://ds79lt46qzmj0.cloudfront.net/0/9/3/09366c76-aa8a-44f3-8f53-a97fc745ae5c/8911e9dc-8894-4ad0-96f2-160709d75152.ism/QualityLevels(300000)/Fragments(video=#{byte_offset})"
end

def audio_segment_url(byte_offset)
  "http://ds79lt46qzmj0.cloudfront.net/0/9/3/09366c76-aa8a-44f3-8f53-a97fc745ae5c/8911e9dc-8894-4ad0-96f2-160709d75152.ism/QualityLevels(128000)/Fragments(audio_AACL_128k=#{byte_offset})"
end
```

A (broken) implementation of a downloader is at https://github.com/ReneVolution/smoothget/, hopefully easy to fix and implement for someone? I'd appreciate some help, I'm happy to do the heavy lifting as needed if someone can point me in the right direction.

**Comment by c0deous** [comment]
Has any progress been made on this?  I have a massive movie collection on Amazon I wanted to put it on my Plex server.  From what I am hearing it is:

1) Possible to Login to Amazon with Python [](http://stackoverflow.com/question)s/18265376/why-i-can-log-in-amazon-website-using-python-mechanize-but-not-requests-or-urll
2) Possible to download ISM videos with ismdownloader (for windows but meh) [](http://md5decrypt.altervista.org/ismdownloaderavc1.htm)

Youtube-dl is a fantastic tool.  It would be even more fantastic if this were implemented :)

**Comment by remitamine** [comment]
they have multiple formats(DASH, SmoothStreaming, HLS, MP4, WMV, MPEGPS, MPEGTS) and DRM protection(PlayReady, FlashAccess, Widevine2, Marlin, FairPlay, CENC).
i tried only to download DASH formats on a trailer and it works, but for full content i think they will use DRM.

**Comment by murphy-edwards** [comment]
Someone was able to figure out the Widevine DRM on amazon:
https://github.com/liberty-developer/inputstream.mpd

This is a Kodi plugin that provides DASH streams that are encrypted with widevine.
Look at wvdecrypter. It uses the widevineCDM library that chrome provides to decrypt the videostream.

**Comment by jubalh** [comment]
Any news on this one?

**Comment by DJD-Code-Studio** [comment]
There is only one Firefox extension Video Download Helper which is able to identify all the video resolutions of Amazon Prime Video and download them. But it uses the native downloader of Firefox which sucks. It is painfully slow. But it works.

So for now that is the only option for Amazon Prime Videos.

**Comment by antonio8909** [comment]
@DJD-Code-Studio That doesn't work. It detect the video in parts.

**Comment by DJD-Code-Studio** [comment]
@antonio8909 

Yes, it detects the video in parts but if you allow the extension a few minutes after the streaming has started, it detects the full file.. 
If you click on the icon, you will see a list of various options of gradually increasing sizes. Select the highest or the second highest one. It would contain the entire video. But it will use the native downloader of FF. 
The best I have see is to allow the video to run for 5 minutes ( say for a full length movie) and then if I check the options listed by the extension I get the desired size.

Hope this helps !

**Comment by antonio8909** [comment]
Extension? Is there any extension? @DJD-Code-Studio

**Comment by jmcree** [comment]
@antonio8909 @DJD-Code-Studio From what I've been reading and experimenting with, although that plug-in finally detects the full file, the video is no good.

**Comment by Tatsh** [comment]
Just so everyone knows, wvdecrypter source is here now https://github.com/peak3d/inputstream.adaptive

**Comment by shadowfolder** [comment]
Anybody got luck to download amazon DRM videos? I've tried every step from this thread but with no luck

**Comment by Tatsh** [comment]
How any of these sites are being ripped from is not public information and probably never will be.

**Comment by nicksds** [comment]
anybody help...how to download videos from zee5.com and sunnxt.com i have subscrption account but unable to download from the youtubde-dl it giving error like WARNING: Falling back on generic information extractor... this is link 
https://www.zee5.com/movies/details/bruce-lee-the-fighter/0-0-2702/watch

**Comment by shadowzoom** [comment]
@ghoshben i've tried to install it, without luck... So hard. It would be great if someone can merge it with yt downloader!

**Comment by brunomoreno71** [comment]
@ghoshben Sadly, that doesn't work as I read kametsu.

**Comment by antonio8909** [comment]
I don't think that this will be merged into yt-dl

**Comment by shadowzoom** [comment]
Why  https://github.com/tsukasachandesu/video_decrypter was deleted?

**Comment by shadowzoom** [comment]
Damn.. Tatsh, do you know forums where i can find it?

**Comment by brunomoreno71** [comment]
https://github.com/dheeraj-rn/video_decrypter

**Comment by jubalh** [comment]
Hopefully someone can base some work on this nice effort. Just sad that it requires Windows so far.

**Comment by sundelirajesh** [comment]
> https://github.com/dheeraj-rn/video_decrypter

How to use this program?

**Comment by IDerr** [comment]
I repost the new link for info
https://github.com/CrackerCat/video_decrypter

**Comment by shadowzoom** [comment]
@IDerr can you please write mini guide how to use it after compilation? Do this please when you will be have free time, thanks so much in advance

**Comment by vapecoder** [comment]
@lDerr I'm also interested in this

**Comment by HackerBoy0412** [comment]
Give it a Guide

**Comment by F3rn4nd080** [comment]
> 
> 
> I repost the new link for info
> https://github.com/CrackerCat/video_decrypter

can you explain a little how use? for noobs lol

**Comment by Anan5a** [comment]
@ghoshben Please explain the arguments of ``` widevine_decrypter ```
```
android@Debian-101-buster-64-minimal:~/drm/video_decrypter/widevine_decrypter/src$ ./widevine_decrypter
Syntax : ./widevine_decrypter {encrypted_file} {stream_id} {info_path} {decrypted_path}
double free or corruption (!prev)
Aborted
android@Debian-101-buster-64-minimal:~/drm/video_decrypter/widevine_decrypter/src$ 
```
I understand {encrypted_file} and {decrypted_path} .But what about {info_path} and {stream_id} ?
Please elaborate. also the wiki is dead for some reason!

**Comment by michaelsmoody** [comment]
> @ghoshben Please explain the arguments of `widevine_decrypter`
> 
> ```
> android@Debian-101-buster-64-minimal:~/drm/video_decrypter/widevine_decrypter/src$ ./widevine_decrypter
> Syntax : ./widevine_decrypter {encrypted_file} {stream_id} {info_path} {decrypted_path}
> double free or corruption (!prev)
> Aborted
> android@Debian-101-buster-64-minimal:~/drm/video_decrypter/widevine_decrypter/src$ 
> ```
> 
> I understand {encrypted_file} and {decrypted_path} .But what about {info_path} and {stream_id} ?
> Please elaborate. also the wiki is dead for some reason!

@ghoshben I'm not sure if it's helpful to you, but the source has a directory of python_scripts which you could look at. It has several examples which in my investigation seem to login to a site (site.tv), download, and decrypt.

**Comment by Anan5a** [comment]
@michaelsmoody  the project is useless with latest widevine library

**Comment by Invictaz** [comment]
> @michaelsmoody the project is useless with latest widevine library

Why?

**Comment by TokugawaHeavyIndustries** [comment]
> Why?

it was nuked.  https://widevine.rip/

**Comment by DavidGriffith** [comment]
I don't see anything here to explain what happened, why, or what else can be done to allow for Amazon videos to be downloaded.

**Comment by TokugawaHeavyIndustries** [comment]
@DavidGriffith I posted above.  Widevine was killed off, rendering the workaround unusable.  At this time, there are no other known methods.

**Comment by DavidGriffith** [comment]
> @DavidGriffith I posted above. Widevine was killed off, rendering the workaround unusable. At this time, there are no other known methods.

Is this of no use? https://github.com/cryptonek/widevine-l3-decryptor

**Comment by TokugawaHeavyIndustries** [comment]
@DavidGriffith No.  That doesn't work either.  Widevine's master keys were changed.

**Comment by jalotra** [comment]
8 years and this community still hasn't figured a robust-crossplatform method out ?

**Comment by TokugawaHeavyIndustries** [comment]
@jalotra youtube-dl's primary purpose is not to circumvent Amazon's DRM and encryption. The only reason the Amazon module was added to youtube-dl in the first place was because there was a publically available bypass method (widevine-l3-decryptor).

Again, if there are methods to bypass Amazon's encryption, they aren't public for a reason. Amazon will patch them, rendering all the dev work useless.

**Comment by InCrIpTiOn** [comment]
(For sigma developers ONLY) - Pirate the movie.

**Comment by 89z** [comment]
Issue should be closed, URL is dead
