### ISSUE TITLE
HTTP Error 404 on specific YouTube videos

### ISSUE THREAD

**Issue by SilasLaspada** [rg3/youtube-dl#17538]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v https://www.youtube.com/watch?v=ZvccY97SZX0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=ZvccY97SZX0']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg N-91801-gad9b4ecc26, ffprobe N-91801-gad9b4ecc26
[debug] Proxy map: {}
[youtube] ZvccY97SZX0: Downloading webpage
[youtube] ZvccY97SZX0: Downloading video info webpage
[youtube] {22} signature length 41.40, html5 player vflHei2l6
[youtube] {43} signature length 41.40, html5 player vflHei2l6
[youtube] {18} signature length 41.40, html5 player vflHei2l6
[youtube] {36} signature length 41.40, html5 player vflHei2l6
[youtube] {17} signature length 41.40, html5 player vflHei2l6
[youtube] ZvccY97SZX0: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r5---sn-qxo7rn7l.googlevideo.com/videoplayback/id/66f71c63ded2657d/itag/135/source/yt_otf/requiressl/yes/mv/m/mm/31,29/ms/au,rdu/mn/sn-qxo7rn7l,sn-qxoedn7z/pl/23/initcwndbps/1338750/ei/uE6XW4COL4O2kwbUpYawAg/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1518827742245318/fvip/5/mt/1536642698/disable_polymer/true/ip/216.170.138.203/ipbits/0/expire/1536664344/sparams/ip,ipbits,expire,id,itag,source,requiressl,mv,mm,ms,mn,pl,initcwndbps,ei,ratebypass,mime,otfp,otf,lmt/signature/209AB837CDAE64A7380E86BC929387FC8751FCC7.90EDED7DF057272194F110B6268CF13385D1AA27/key/dg_yt0/'
[dashsegments] Total fragments: 19
[download] Destination: Trumpet off-ZvccY97SZX0.f135.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
ERROR: giving up after 10 fragment retries
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\python\lib\site-packages\youtube_dl\__init__.py", line 472, in main
    _real_main(argv)
  File "c:\python\lib\site-packages\youtube_dl\__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\python\lib\site-packages\youtube_dl\YoutubeDL.py", line 2001, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\python\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\python\lib\site-packages\youtube_dl\YoutubeDL.py", line 857, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "c:\python\lib\site-packages\youtube_dl\YoutubeDL.py", line 1635, in process_video_result
    self.process_info(new_info)
  File "c:\python\lib\site-packages\youtube_dl\YoutubeDL.py", line 1902, in process_info
    partial_success = dl(fname, new_info)
  File "c:\python\lib\site-packages\youtube_dl\YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "c:\python\lib\site-packages\youtube_dl\downloader\common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "c:\python\lib\site-packages\youtube_dl\downloader\dash.py", line 75, in real_download
    self.report_error('giving up after %s fragment retries' % fragment_retries)
  File "c:\python\lib\site-packages\youtube_dl\downloader\common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "c:\python\lib\site-packages\youtube_dl\YoutubeDL.py", line 620, in report_error
    self.trouble(error_message, tb)
  File "c:\python\lib\site-packages\youtube_dl\YoutubeDL.py", line 582, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Downloading a few specific videos from YouTube results in "Got server HTTP error: HTTP Error 404: Not Found." on fragment 1. It happens consistently for the same few videos, I have verified that it plays fine in browser and that other videos download correctly. Here is one of the videos that isn't downloading: https://www.youtube.com/watch?v=ZvccY97SZX0

**Comment by dstftw** [comment]
Server side youtube issue. Select another format.

**Comment by LukeMadhanga** [comment]
> Server side youtube issue. Select another format.

Excuse my ignorance, but what do you mean by this?

I am encountering this issue on a whole load of YouTube videos so I would like to know what the solution is

**Comment by prabak** [comment]
> > Server side youtube issue. Select another format.
> 
> Excuse my ignorance, but what do you mean by this?
> 
> I am encountering this issue on a whole load of YouTube videos so I would like to know what the solution is

`youtube-dl -F https://www.youtube.com/watch?v=ZvccY97SZX0` that should lists available format. Then try the following:
`youtube-dl -f FORMAT_CODE_FROM_ABOVE https://www.youtube.com/watch?v=ZvccY97SZX0`
you can also do `youtube-dl -f best https://www.youtube.com/watch?v=ZvccY97SZX0`

hope that helps. try the various format code and see which one works.

**Comment by LukeMadhanga** [comment]
@prabak Sweet, that works! Thank you

**Comment by Rak604** [comment]
I am facing the problem on my website [youtube to mp3](https://youtubetomp3juice.net/), specific videos just don't download, may be I have to update new version in 2020.

**Comment by TomArrow** [comment]
Can we get a proper fix for this? It happens on select videos and it never fixes itself. Clearly this is not intended behavior. The intended behavior should be to download a stream that actually works. If Youtube is sending out wrong info about the streams leading to a 404, that does not make it a server side Youtube issue. That's just how Youtube works then. Since Youtube doesn't intend to have its videos downloadable, and there is no documented API of theirs saying anything about how things should be, all we can do is observe how things are. 

It may be lazy programming on their side, but "just manually select the stream you want" is not an adequate solution, because this does not cover the archival of entire channels. Am I expected to download each single video that doesn't work (it's not like youtube-dl gives me an error logfile of videos that failed either) manually like this? 

Things being the way they are now, effectively archiving channels results in missing videos. How can this be the intended result? The correct result would be to have the software realize "ok, 404, clearly this stream does NOT exist" and fall back to the next best stream. You can't claim server side error unless there is some documentation about how the server is supposed to behave and there is none. So right now the argument here is basically "I don't like the way Youtube is programmed, so I am not going to adapt to it".
