### ISSUE TITLE
How to get the download url of a video instead of playback url?

### ISSUE THREAD

**Issue by MyNB** [rg3/youtube-dl#17548]
The url youtube-dl returns is a playback url, and when i paste it on a browser it starts to play the video instead of directly downloading it. what parameters to set to overcome that situation?

**Comment by dstftw** [comment]
There is no such thing as playback URL. There is just an URL and how it's going to be treated is up to the browser.

**Comment by MyNB** [comment]
In desktop the given URL is always played on browser but in mobile the URL is prompted to save as. How can I force the desktop browser to save the video instead of playing in a tab? also other downloaders like https://en.savefrom.net/1-how-to-download-youtube-video/ gives a url that does not play in a new tab in chrome, the url directly downloads in browser. What is the difference?

**Comment by limitedAtonement** [comment]
Press "CTRL+s"?
