### ISSUE TITLE
My youtube-dl ip :47.90.39.21(HongKong) ,But I get the parsed video's url But Can't play in PC'S browser(google chrome) who's ip is :139.59.41.54(India)

### ISSUE THREAD

**Issue by dcdebug** [rg3/youtube-dl#17544]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.10**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.09.10
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
shell@iZ620vnh79jZ:~$ sudo youtube-dl -vC -g -f mp4   https://www.youtube.com/watch?v=qTrS4nGDoJo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vC', u'-g', u'-f', u'mp4', u'https://www.youtube.com/watch?v=qTrS4nGDoJo']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2018.09.10
[debug] Python version 2.7.6 (CPython) - Linux-3.13.0-86-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Public IP address: 47.90.39.21
https://r2---sn-i3b7kn7k.googlevideo.com/videoplayback?requiressl=yes&ratebypass=yes&itag=22&dur=690.097&lmt=1536617719196842&expire=1536701040&sparams=dur%2Cei%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&source=youtube&key=yt6&mime=video%2Fmp4&c=WEB&initcwndbps=2055000&id=o-AA0bxpLtV0yjNkXzAPY4PX9uA81PoXSYYjcMr5sPpH_T&mn=sn-i3b7kn7k%2Csn-i3beln7z&mm=31%2C29&ms=au%2Crdu&gcr=hk&mv=m&mt=1536679380&txp=5531332&signature=8B0D9DCAFC2D9575EB502F4832BA7B845246DC15.0B8B6CD2BD1CD4B4CDCA0CAD29793420AFC3C0CB&ip=47.90.39.21&ei=D96XW73sM4iK4AKt07GIDA&pl=17&ipbits=0&fvip=4
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=qTrS4nGDoJo
- Single video: https://youtu.be/qTrS4nGDoJo

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

When I use the server (It in HongKong) to parse the  youtube video (videoid:qTrS4nGDoJo), then I get the parsed url .the parsed url can played in HongKong ,But when  i change my vpn ,I can't play the video ;
Why ?But I how solove the problem ? 
I need your help !
Sorry ,my English is very poor ; I must obtain the requiration ;

**Comment by dcdebug** [comment]
OK ,parsed url :https://r2---sn-i3b7kn7k.googlevideo.com/videoplayback?requiressl=yes&ratebypass=yes&itag=22&dur=690.097&lmt=1536617719196842&expire=1536701040&sparams=dur%2Cei%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&source=youtube&key=yt6&mime=video%2Fmp4&c=WEB&initcwndbps=2055000&id=o-AA0bxpLtV0yjNkXzAPY4PX9uA81PoXSYYjcMr5sPpH_T&mn=sn-i3b7kn7k%2Csn-i3beln7z&mm=31%2C29&ms=au%2Crdu&gcr=hk&mv=m&mt=1536679380&txp=5531332&signature=8B0D9DCAFC2D9575EB502F4832BA7B845246DC15.0B8B6CD2BD1CD4B4CDCA0CAD29793420AFC3C0CB&ip=47.90.39.21&ei=D96XW73sM4iK4AKt07GIDA&pl=17&ipbits=0&fvip=4

Can't play , and its tips is : 

Access to r2---sn-i3b7kn7k.googlevideo.com.... was denied
You don't have authorization to view this page.
HTTP ERROR 403

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser
