### ISSUE TITLE
Is there somewhere an explanation available of the various formats of youtube streams (which you get when you list them in youtube-dl)?

### ISSUE THREAD

**Issue by Emdosis** [rg3/youtube-dl#17563]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.10**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

**Comment by dstftw** [comment]
`-F`.

**Comment by Emdosis** [comment]
I understand. Though there's still one thing I'd like to ask; why are there 2 different bitrates in the dash audio formats? It's kinda confusing. Although it seems to me like youtube-dl just downloads the second one... I just started using youtube-dl so it all seems ambiguous to me...

**Comment by Hrxn** [comment]
It depends...
YouTube has some variation here, depending on the upload (for example, something old, uploaded long ago vs. something new).
Although usually bitrate alone is not the only difference..
Can you post the output of `-F` here?

**Comment by Emdosis** [comment]
I don't really understand why you need it, it's literally the same for all youtube videos. Here's an example I guess:
`139          m4a        audio only DASH audio   **50k** , m4a_dash container, mp4a.40.5@ **48k** (22050Hz), 1.10MiB
140          m4a        audio only DASH audio  **129k** , m4a_dash container, mp4a.40.2@**128k** (44100Hz), 2.94MiB

160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 25fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 25fps, video only
134          mp4        640x360    DASH video  294k , mp4_dash container, avc1.4d401e, 25fps, video only, 6.68MiB
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 25fps, video only
137          mp4        1920x1080  DASH video 2240k , mp4_dash container, avc1.640028, 25fps, video only, 39.98MiB
136          mp4        1280x720   DASH video 2310k , mp4_dash container, avc1.4d4016, 25fps, video only
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 1.45MiB
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2, 4.93MiB
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 10.85MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 11.53MiB
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)`

Though usually more popular videos have opus and vorbis formats in them. Like so:

`249          webm       audio only DASH audio   59k , opus @ 50k, 1.31MiB
250          webm       audio only DASH audio   89k , opus @ 70k, 1.90MiB

140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 3.00MiB
171          webm       audio only DASH audio  128k , vorbis@128k, 2.72MiB
251          webm       audio only DASH audio  170k , opus @160k, 3.66MiB
278          webm       256x144    144p   26k , webm container, vp9, 30fps, video only, 541.20KiB
242          webm       426x240    240p   29k , vp9, 30fps, video only, 610.55KiB
243          webm       640x360    360p   53k , vp9, 30fps, video only, 1.08MiB
244          webm       854x480    480p   87k , vp9, 30fps, video only, 1.63MiB
160          mp4        256x144    144p  102k , avc1.4d400c, 30fps, video only, 1.09MiB
247          webm       1280x720   720p  160k , vp9, 30fps, video only, 3.26MiB
134          mp4        640x360    360p  196k , avc1.4d401e, 30fps, video only, 1.58MiB
133          mp4        426x240    240p  234k , avc1.4d4015, 30fps, video only, 2.32MiB
135          mp4        854x480    480p  411k , avc1.4d401f, 30fps, video only, 2.82MiB
136          mp4        1280x720   720p  812k , avc1.4d401f, 30fps, video only, 4.78MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 804.63KiB
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2, 2.29MiB
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 4.18MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 4.59MiB
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)`

**Comment by Hrxn** [comment]
Well, your examples show that it's not literally the same for all videos..

youtube-dl by default selects as format setting `bestvideo+bestaudio`.

In this case here, `bestaudio` would be 1. format 140 and for 2. format 251..

So this should work as expected. Or did you manage to produce something different here? 

Or is your question more about the general principle, i.e. YouTube offering streams in many different formats?

If yes, then that is the case for support of lots of different devices with different capabilities, when it comes to formats/containers, codecs, display size/resolution and also Internet connection bandwidth of course.,

If the connection slows down, YouTube switches to formats with lower bitrates etc.
