### ISSUE TITLE
4K AV1 streams unsupported?

### ISSUE THREAD

**Issue by deadman3000** [rg3/youtube-dl#17567]
Youtube AV1 beta playlist not playing all resolutions?
https://www.youtube.com/playlist?list=PLyqf6gJt7KuHBmeVzZteZUlNUQAVLwrZS

The 1080 streams play fine as AV1 but the 4K streams play as VP9 (I am guessing that is not AV1?)
1080p
https://www.youtube.com/watch?v=w4LkSRXrK34
2160p
https://www.youtube.com/watch?v=PiWyCQV52h0

**Comment by dstftw** [comment]
There are no 4K av1 formats on youtube for these videos.
