### ISSUE TITLE
CLI-option for printing original download-url (feature wish)

### ISSUE THREAD

**Issue by klartext** [rg3/youtube-dl#17579]
youtube-dl does sometimes work even on non-supported sites. :-)
Thats great.
But the download-url sometimes is not the url form the the site (e.g. video is embedded or so).

To get the original video-url (so that this can be given to other people who might want to se the video, but don't use youtube-dl) would be nice.

A cli-option to print that orig-url would be helpful here.

**Comment by klartext** [comment]
(With original url I mean the actual one, the real one, if video is embedded, then the actual provider url is wanted here.)

**Comment by dstftw** [comment]
`webpage_url` of JSON output.
