### ISSUE TITLE
channel4 support

### ISSUE THREAD

**Issue by ProgrammerAKL** [rg3/youtube-dl#17576]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl-2018-09-10 -o "C:/Video/%(title)s.%(ext)s" "https://www.channel4.com/programmes/gillette-world-sport/on-demand/67855-010?intcmp=video_link:bip_ondemand:episodes" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/%(title)s.%(ext)s', 'https://www.cha
nnel4.com/programmes/gillette-world-sport/on-demand/67855-010?intcmp=video_link:
bip_ondemand:episodes', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 67855-010?intcmp=video_link:bip_ondemand:episodes: Requesting header
[redirect] Following redirect to https://www.channel4.com/programmes/gillette-wo
rld-sport/on-demand/67855-010
[generic] 67855-010: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 67855-010: Downloading webpage
[generic] 67855-010: Extracting information
ERROR: Unsupported URL: https://www.channel4.com/programmes/gillette-world-sport
/on-demand/67855-010
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\bu
ild\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\bu
ild\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\bu
ild\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.channel4.com/pro
grammes/gillette-world-sport/on-demand/67855-010
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.channel4.com/programmes/gillette-world-sport/on-demand/67855-010?intcmp=video_link:bip_ondemand:episodes

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Site support request. Video expected to disappear quite soon.

**Comment by CollinChaffin** [comment]
@dstftw Hey Sergey! I want to ask since folks have been duplicating this request for over half a decade on this one and just to ask based on #2050 is this just a DRM issue?  Are we sure that's still the case the last glance looked like they were relying on the geo-ip area filtering now so just wanted to verify whether you've looked at it again lately.

#15553, #14276, #7539, #6355, #5246, #5121, #2050 

Thoughts?  Anything we can provide to help?
