### ISSUE TITLE
Unable to pull ALL videos in a course on Lynda.com WARNING: 72 videos are only available for members (or paid members) and will not be downloaded. Use --username and --password options to provide lynda.com account credentials.

### ISSUE THREAD

**Issue by vikiaiteam** [rg3/youtube-dl#17586]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.lynda.com/Python-tutorials/Python-3-Essential-Training/62226-2.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-88555-g6ea7711532, ffprobe N-88555-g6ea7711532
[debug] Proxy map: {}
[lynda:course] 62226: Downloading course JSON
WARNING: 72 videos are only available for members (or paid members) and will not be downloaded. Use --username and --password options to provide lynda.com account credentials.
[download] Downloading playlist: Python 3 Essential Training
[lynda:course] playlist Python 3 Essential Training: Collected 15 video ids (downloading 15 of them)
[download] Downloading video 1 of 15
[lynda] 70920: Downloading video JSON
[lynda] 70920: Checking 1-540 video format URL
[lynda] 70920: Checking 1-360 video format URL
[lynda] 70920: Checking 0-540 video format URL
[lynda] 70920: Checking 0-360 video format URL
[debug] Default format spec: bestvideo+bestaudio/best

**Comment by dstftw** [comment]
Bother to read the log.
