### ISSUE TITLE
Switching from Youtube to Vimeo, calling youtube-dl from Python

### ISSUE THREAD

**Issue by lguez** [rg3/youtube-dl#17591]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

How do I download a video from Vimeo with youtube-dl embedded in Python? It works from  the command line:

`youtube-dl https://vimeo.com/15991774`

(works)

and it works from Python if it is the first video I download:

```python
import youtube_dl
ydl = youtube_dl.YoutubeDL({})
ydl.download(["https://vimeo.com/15991774"])
```
(works)

However, it does not work after downloading a video from Youtube:

```python
ydl.download(["https://www.youtube.com/watch?v=RwdY7Eqyguo"])
```
(works)

```python
ydl.download(["https://vimeo.com/15991774"])
```
does not work:

[vimeo] 15991774: Downloading webpage
[vimeo] 15991774: Extracting information
[vimeo] 15991774: Downloading webpage
ERROR: Unable to extract info section (caused by ExtractorError("Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

DownloadError                             Traceback (most recent call last)
<ipython-input-11-6e3c29737474> in <module>()
----> 1 ydl.download(["https://vimeo.com/15991774"])

/home/guez/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py in download(self, url_list)
   1999                 # It also downloads the videos
   2000                 res = self.extract_info(
-> 2001                     url, force_generic_extractor=self.params.get('force_generic_extractor', False))
   2002             except UnavailableVideoError:
   2003                 self.report_error('unable to download video')

/home/guez/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py in extract_info(self, url, download, ie_key, extra_info, process, force_generic_extractor)
    813                 break
    814             except ExtractorError as e:  # An error we somewhat expected
--> 815                 self.report_error(compat_str(e), e.format_traceback())
    816                 break
    817             except MaxDownloadsReached:

/home/guez/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py in report_error(self, message, tb)
    618             _msg_header = 'ERROR:'
    619         error_message = '%s %s' % (_msg_header, message)
--> 620         self.trouble(error_message, tb)
    621 
    622     def report_file_already_downloaded(self, file_name):

/home/guez/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py in trouble(self, message, tb)
    588             else:
    589                 exc_info = sys.exc_info()
--> 590             raise DownloadError(message, exc_info)
    591         self._download_retcode = 1
    592 

DownloadError: ERROR: Unable to extract info section (caused by ExtractorError("Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

What am I missing?

**Comment by dstftw** [comment]
Post complete code. Post complete verbose log.
