### ISSUE TITLE
ERROR: audio conversion failed: Unknown encoder 'libvorbis'

### ISSUE THREAD

**Issue by gakowihuwi** [rg3/youtube-dl#17590]
Hi,

Re-creating the issue this time specifying version information since my first issue was closed as incomplete. Hope it's enough, otherwise please let me know.

I get "ERROR: audio conversion failed: Unknown encoder 'libvorbis'" when I run youtube-dl (version 2018.09.10) in the following way on macOS 10.13.6 (17G65):

youtube-dl --extract-audio --audio-format vorbis --audio-qu
ality 0 --yes-playlist -o "%(title)s.%(ext)s" https://www.youtube.com/playlist?list=AAAAAAAAAAAAAAAAAAAAAAAAAAA

I have vorbis-tools 1.4.0 installed with brew. 
It also used to work fine when I last used youtube-dl a couple of months before.

**Comment by gakowihuwi** [comment]
Please let me know what is missing so that I can add it rather than just closing and labeling it as incomplete.

**Comment by dstftw** [comment]
Bother to read issue template.
