### ISSUE TITLE
[YouTube] Videos with both the disabled "Allow embedding" option and the enabled "Age restriction" option

### ISSUE THREAD

**Issue by TestPolygon** [rg3/youtube-dl#17604]
You need to be logged in to download videos with both the disabled "Allow embedding" and the enabled "Age restriction" option.
```
[youtube] video_id: Downloading webpage
[youtube] video_id: Downloading embed webpage
[youtube] video_id: Refetching age-gated info webpage
ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.
```
But I **can** download videos only with the "Age restriction" option or only with the disabled "Allow embedding" option.
It looks strange. It seems to me that it is a bug.

You can easy test this "feature" with own videos.
Just set these options like in the picture:
![screenshot_1](https://user-images.githubusercontent.com/38364068/45684148-150fcb80-bb4e-11e8-9428-fc54f9baf02a.png)

**Comment by TestPolygon** [comment]
Or you can test this thing with my videos:
[Allow embedding, No age restriction](https://www.youtube.com/watch?v=w_7ZRAiEZxM)
[Allow embedding, Age restriction](https://www.youtube.com/watch?v=2U5mf_fEKiU)
[No allow embedding, Age restriction](https://www.youtube.com/watch?v=BYrQk8JW2R0)

**Comment by TestPolygon** [comment]
youtube-dl version is 2018.09.18.
The same problem was in the previous version too.

**Comment by ZainRizvi** [comment]
Isn't this is a quick of YouTube itself (rather than with youtube-dl)?

**Comment by TestPolygon** [comment]
I don't know. I'm just guessing about this. 
It looks like a small defect of youtube-dl.
I think that if you can download any video with either the disabled "Allow embedding" option or the enabled "Age restriction" option, there is a way to download a video with both the disabled "Allow embedding" option and the enabled "Age restriction" option.

**Comment by BlohoJo** [comment]
Can you export browser cookies and use the -cookies option in youtube-dl?

**Comment by remitamine** [comment]
> *without the need to be logged in

there isn't if you know how to get the information without logging in then you post how you can get them(here or as PR).

**Comment by TestPolygon** [comment]
I have checked the source code, the embedding allows pass the age check, so now everything is clear.
