### ISSUE TITLE
Start a for loop after youtube-dl is finished

### ISSUE THREAD

**Issue by hollysheep** [rg3/youtube-dl#17618]
i want to check for new videos in a youtube channel every day, i use cron to do that. at the moment i start youtube-dl directly from the cron. i want to delete some strings from the file name and created a shell script thats checks the files in the downloader folder. the cron now should start a shell script that
1.) checks for new files and downloas them if available
2.) rename new files in the output folder

but when i start the shell script manually the for loop starts before youtube-dl starts. i execute the script and get the error that there are no files to rename, then it jumps back to the terminal prompt. after a few moments youtube-dl starts checking for new videos and download videos if available.

how can i ensure that the for loop only starts after youtube-dl is finished, no matter how long youtube-dl needs. a simple 'sleep' should not enough because i can't say how long the downloads needs.

**Comment by dstftw** [comment]
You don't need any scripts for that. Use `--download-archive` and output template for naming.
