### ISSUE TITLE
-o option can't parse `release_date`, `upload_date` and `ext`

### ISSUE THREAD

**Issue by laurencedev** [rg3/youtube-dl#17614]
Reproduction:

The following command in a `cmd` on a Windows 10 Pro machine:

`C:\Users\u\Videos>youtube-dl https://www.youtube.com/watch?v=D1ZYhVpdXbQ -o "%(playlist)s/%(playlist_index)s-%(title)s.%(release_date).%(ext)s"`

would outputs:

```
[youtube] D1ZYhVpdXbQ: Downloading webpage
[youtube] D1ZYhVpdXbQ: Downloading video info webpage
[youtube] D1ZYhVpdXbQ: Downloading js player vflkUTZn2
[download] Destination: NA\NA-Singing In The Rain - Singing In The Rain (Gene Kelly) [HD Widescreen].%(ext)s
[download]   0.9% of 46.43MiB at 123.52KiB/s ETA 06:21
```

No `ext` value and `release_date` value parsed in the output's file name.

`youtube-dl` version: 2018.09.18

**Comment by dstftw** [comment]
Invalid output template. Must be `%(release_date)s` not `%(release_date)`.
