### ISSUE TITLE
A question on screen resolution limits. 1080p+?

### ISSUE THREAD

**Issue by jimlynnjulian** [rg3/youtube-dl#17624]
More of a question. 

Can Youtube-dl download file larger than 1080p, such as 1440x900 and 4K?

I'm downloading files from a public Russian site and though the file in question is available in 4K, the maximum I get is 1080p. I've never had any other problems with that site and I use the site often.

Is there a limit of some sort in action?

**Comment by dstftw** [comment]
It can download whatever particular extractor allows to. Also 1440x900 is not larger than 1080p that stands for 1920x1080.

**Comment by jimlynnjulian** [comment]
Can you create a brief run down or outline of Youtube-DL's operation?

**Comment by Hrxn** [comment]
What do you mean?

Again, extraction depends on the site/extractor. You can download 4K (or higher) from YT without any issues. I don't know about the site you've mentioned, since you did not provide any link yet..

**Comment by jimlynnjulian** [comment]
I made some checks. 
Some 4k videos will download. 
I found the same title, and 4k format, that will download. 
There seems to be something about the particular video that halts Youtube-dl.
Unless you have an interest in that page, I have what I was searching for, and am done.
Thank you

**Comment by jimlynnjulian** [comment]
Hello

I have had, as I posted before, problems downloading 4k video files from odnoklassniki.
I thought I had found 4k videos that would download as 4k. 
I was wrong. I have yet to locate an advertised 4k video that downloads as a 4k video.

Do you know of any 4k videos that you have downloaded from that site? 
I'd like to test my laptop, ISP, and router setup for errors, or other client-side issues.

I feel sure that, twice, I have begun a download with a reported file size in excess of eleven gigabytes. This left me sure I was downloading a 4k video. But, twice, 
I have quit the download, since I do not run my laptop 24 hours a day, and restarted by running the same command line, and the file size changed to a four-to-six gigabyte file that ended up as a 1080p file. I think this was after starting fresh and having deleted the previous downloaded parts.

I get the impression that the first time I run the download, I get the 4k file, but If I download again, I get a 1080p file. 

I include several links to video files that are presented as being 4k videos on odnoklassniki, but download as 1080p.


Bram Stoker's Dracula
https://ok.ru/video/382501391101
Independence Day
http://ok.ru/video/192206736125
Men In Black
https://ok.ru/video/555030481636
