### ISSUE TITLE
When starting the download from a script file, spaces in the title are replaced with underscores

### ISSUE THREAD

**Issue by nikiforos6** [rg3/youtube-dl#17638]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.18**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
nikiforos@HomeServer:/$ /usr/local/bin/youtube-dl -v --skip-download -o "/volume1/main/Video/Youtube/%(uploader)s/1 -> %(title)s.%(ext)s" "https://www.youtube.com/watch?v=q-7u7rvQBLM"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--skip-download', u'-o', u'/volume1/main/Video/Youtube/%(uploader)s/1 -> %(title)s.%(ext)s', u'https://www.youtube.com/watch?v=q-7u7rvQBLM']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Python version 2.7.12 (CPython) - Linux-3.10.102-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 2.7.1
[debug] Proxy map: {}
[youtube] q-7u7rvQBLM: Downloading webpage
[youtube] q-7u7rvQBLM: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best

```

---

### Description of your *issue*, suggested solution and other information

Hello everyone.
So yesterday I installed youtube-dl on my Synology Diskstation. I ran and tested it by manually inputing the arguments and commands via PuTTY, which worked (and still works) perfectly well.

Next step for me was to write the argument in a script file (.sh) so that I could automate it by scheduling a task (this is a Synology feature).

When this task is being executed suddenly all the spaces in the title (and the playlist_title) are being replaced with an underscore "_"

I'm not sure if that is a youtube-dl issue, a Linux issue, or a Synology task scheduler issue.

Example:
Command: 
```
/usr/local/bin/youtube-dl -o "/volume1/main/Video/Youtube/%(uploader)s/1 - %(title)s.%(ext)s" "https://www.youtube.com/watch?v=q-7u7rvQBLM"
```
When input in PuTTY the name appears like so: 1 - TW Improve: Our Widest Tennis Shoes.mp4

When used in the script file the name appears like so: 1 - TW_Improve_-_Our_Widest_Tennis_Shoes.mp4
Note that it is keeping the hard coded space at the start, but not the spaces in the title.

Any ideas?
Thanks in advance,
Nik

**Comment by dstftw** [comment]
Set locale to UTF-8.
