### ISSUE TITLE
safaribooksonline.com ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the lates t version... and bypas by oreilly.com

### ISSUE THREAD

**Issue by vikiaiteam** [rg3/youtube-dl#17640]
C:\youtube-dl-master\downloaded>youtube-dl -u xxxx@gmail.com -p xxxx -v --all-subs -i -c -w -o "C:\youtube-dl-master\downloaded\%(playlist)s\%(pla
ylist_index)s-%(title)s.%(ext)s" --external-downloader aria2c.exe https://www.safaribooksonline.com/library/view/understanding-crypto-currencies/9780135235348/ --convert-subs sr
t
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v', u'--all-subs', u'-i', u'-c', u'-w', u'-o', u'C:\\youtube-dl-master\\downloaded\\%(playlist)s\\
%(playlist_index)s-%(title)s.%(ext)s', u'--external-downloader', u'aria2c.exe', u'https://www.safaribooksonline.com/library/view/understanding-crypto-currencies/9780135235348/',
 u'--convert-subs', u'srt']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.09.18
[debug] Python version 2.7.15 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-90866-g48330500ef, ffprobe N-90866-g48330500ef
[debug] Proxy map: {}
[safari:course] Downloading login form
[safari:course] Logging in
[safari:course] 9780135235348: Downloading course JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the lates
t version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 604, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
For any work on this you must provide reproducible environment.
