### ISSUE TITLE
Infinite malformed audio fix.

### ISSUE THREAD

**Issue by jimlynnjulian** [rg3/youtube-dl#17665]
The app frequently stalls during the 'fixing malformed audio' phase.
The process keeps cycling from heavy load to no load without finishing in Task Manager/Disk Usage. If I stop the process and copy the main file to a different directory, the video will play in it's entirety. What's up?

**Comment by jimlynnjulian** [comment]
"incomplete"?

**Comment by jimlynnjulian** [comment]
Ignoring the problem does not make the problem go away.

**Comment by dstftw** [comment]
There are no telepathists here. Bother to read new issue template and provide all requested info.
