### ISSUE TITLE
resolution bait & switch on odno 4k

### ISSUE THREAD

**Issue by jimlynnjulian** [rg3/youtube-dl#17663]
I had been having problems downloading 4k from odnoklassniki and couldn't succeed.
I thought I had finally found a downloadable file and was wrong.
A couple of times, I was sure I had seen a figure of 11+gb in the filesize. 
Bingo!
The file size starts out at 11gb -13gb but diminishes to 1080p size at about 3gb-4gb.

Included are scrrenshotes of the process:

![1](https://user-images.githubusercontent.com/11785524/46030243-a5588e00-c0c3-11e8-9f83-12c8892dc736.jpg)

![2](https://user-images.githubusercontent.com/11785524/46030265-ac7f9c00-c0c3-11e8-96e3-dac389229750.jpg)

![3](https://user-images.githubusercontent.com/11785524/46030275-b2757d00-c0c3-11e8-9687-0336d000b5c3.jpg)

![4](https://user-images.githubusercontent.com/11785524/46030289-bacdb800-c0c3-11e8-806b-4806dea715b0.jpg)

![5](https://user-images.githubusercontent.com/11785524/46030296-bf926c00-c0c3-11e8-8733-3534ada48ec2.jpg)

**Comment by dstftw** [comment]
Filesize is extrapolated based on fragments downloaded so far.

**Comment by jimlynnjulian** [comment]
I guess this means I'll have to make the fix myself.
Ciao.
