### ISSUE TITLE
[Tele5] azure-http-* don't work (anymore?), produce HTTP Error 400: Bad Request instead

### ISSUE THREAD

**Issue by uahim** [rg3/youtube-dl#17669]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### Purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of *issue*

not a ytdl bug per se, it seems azure-http-* now require an extra token or something like that
(other formats, e.g. azure-hls-2685 in this case, still work fine)

$ youtube-dl -f azure-http-2500 https://www.tele5.de/mediathek/filme-online/videos/amityville-horror
[Tele5] filme-online/videos/amityville-horror: Downloading webpage
[Nexx] 1552234: Downloading JSON metadata
[Nexx] 1552234: Downloading m3u8 information
[Nexx] 1552234: Downloading MPD manifest
[Nexx] 1552234: Downloading ISM manifest

=>

ERROR: unable to download video data: HTTP Error 400: Bad Request

thanks!

**Comment by mrtnmtth** [comment]
Other websites using nexx.tv I tried seem to work fine.  

When opening the website in Firefox with DASH support disabled, the player shows the message `Dieses Video ist geschützt und kann hier nicht abgespielt werden.` - The video is protected and cannot be played here.

Maybe this is due to configuration on Tele5's side to only allow DASH streaming.  
But then it would make sense to have this option reflected in the JSON API. But there was not anything standing out to me in there.

**Comment by uahim** [comment]
@mrtnmtth thanks for looking into it

**Comment by mrtnmtth** [comment]
Had a further look into this. The only option that stuck out to me was `shouldBeCached` which is `0` on Tele5 videos and `1` on all other sites I checked.  
To confirm or dismiss my suspicion, I need to find at least one other site with `shouldBeCached` set to `0`.

**Comment by yschroeder** [comment]
Any update on this? The problem still persists.

**Comment by uahim** [comment]
I don't think this will ever change on the server side, so I'll close this.

**Comment by uahim** [comment]
I don't think this will ever change on the server side, so I'll close this.
