### ISSUE TITLE
new update changes format preferences.

### ISSUE THREAD

**Issue by 133794m3r** [rg3/youtube-dl#17670]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.18**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```macarthur@sager-laptop:/tmpdownload$ ./youtube-dl -v https://www.youtube.com/watch?v=Ha9OnUcXLos
[debug] System config: []
[debug] User config: [u'-f', u'best[height<=360]/best[ext=mp4]', u'-o', u'/tmpdownload/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=Ha9OnUcXLos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-9.4
[debug] exe versions: avconv 3.2.10-1, avprobe 3.2.10-1, ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Ha9OnUcXLos: Downloading webpage
[youtube] Ha9OnUcXLos: Downloading video info webpage
[debug] Invoking downloader on u'https://r2---sn-fpoqnugx5h-axme.googlevideo.com/videoplayback?ei=49yqW4n5GLizhwbti7O4Bw&c=WEB&lmt=1537918031026665&ip=216.145.95.121&expire=1537945923&gir=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&requiressl=yes&clen=37009508&key=yt6&txp=5511222&mt=1537924172&ratebypass=yes&itag=43&mm=31%2C29&ipbits=0&mn=sn-fpoqnugx5h-axme%2Csn-5ualdn76&mime=video%2Fwebm&ms=au%2Crdu&signature=2DD21F3A9196A12A29FA873C2EB9CA68F6325F47.A917CE1B6846059C37D6F97E9DB4CADF20DCA95B&source=youtube&mv=m&initcwndbps=423750&id=o-ABd4T0ZL1e50tUKsEi4e_uiqmQR_g79DdxDN-iozSIoq&pl=24&dur=0.000&fvip=6'
[download] Resuming download at byte 12471352
[download] Destination: /tmpdownload/Top 10 Foods and Drinks That Never Expire.webm
[download]  41.6% of 35.30MiB at 597.54KiB/s ETA 00:35^C
ERROR: Interrupted by user

```

### Description of your *issue*, suggested solution and other information

Previous versions of the youtube-dl program would(on youtube at least) select the 360p stream on it and every other site with my format settings. Sometime between the current 09.10.2018 and the previous release in testing the format that's downloaded has changed. Previously it'd select format 18 with the settings I have and now it's doing format 23 for reasons that I don't understand because format 23 was always listed as a higher quality format and if you did best[height<=360] and didn't include a /best[ext=mp4].

Here's the current youtube-dl.conf file I have been using since someone told me how to always do 360p mp4 files in the IRC I believe.

```
-f "best[height<=360]/best[ext=mp4]" -o /tmpdownload/"%(title)s.%(ext)s" 
```

It seems to be a regression somewhere but I can't remember when this was changed nor when I first started using that format settings chain as I tried swapping parameters and it still doesn't do what it used to do.

**Comment by dstftw** [comment]
It selects format 43 that is `best` with height <= 360 exactly as requested in your format selector.

**Comment by dstftw** [comment]
Again: **no changes were made in format selection mechanisms** and it behaves **exactly as you requested**. It may select 18 for some videos if 18 will happen to be better than 43 in terms of quality. For this particular video 43 is better (bigger file size) thus it's being selected.
