### ISSUE TITLE
Pluralsight: subtitles download is no longer working?

### ISSUE THREAD

**Issue by rgmorato** [rg3/youtube-dl#17671]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.18**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
---
### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

...
/usr/local/bin/youtube-dl -v -u user@domain.com-p password -o '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s' --min-sleep-interval 30 --max-sleep-interval 60 --all-subs "https://app.pluralsight.com/library/courses/using-wmi-and-cim-powershell/table-of-contents"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-o', '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s', '--min-sleep-interval', '30', '--max-sleep-interval', '60', '--all-subs', 'https://app.pluralsight.com/library/courses/using-wmi-and-cim-powershell/table-of-contents']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Python version 3.6.6 (CPython) - Linux-4.4.0-17758-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[pluralsight:course] using-wmi-and-cim-powershell: Downloading JSON metadata
[download] Downloading playlist: Using WMI and CIM in PowerShell
[pluralsight:course] playlist Using WMI and CIM in PowerShell: Collected 81 video ids (downloading 81 of them)
[download] Downloading video 1 of 81
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] using-wmi-and-cim-powershell-m1-0: Downloading JSON metadata
[pluralsight] using-wmi-and-cim-powershell-m1-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] using-wmi-and-cim-powershell-m1-0: Waiting for 3 seconds to avoid throttling
[pluralsight] using-wmi-and-cim-powershell-m1-0: Downloading captions JSON
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://vid5.pluralsight.com/expiretime=1537927380/c988fe22500d1a424ebe8da8103b4ee7/clips/resolution/11289715-22b3-401b-9718-3aef664de27c/current/mp4/1280x720.mp4'
[download] Sleeping 34.64 seconds...
[download] Destination: Using WMI and CIM in PowerShell/1 - Introduction to the Course/01-Module Agenda and Background.mp4
[download] 100% of 2.49MiB in 00:01
<end of log>
```

### Description of your *issue*, suggested solution and other information
---
I was able to download the subtitles normally using --all-subs (see complete command above), but since Sunday only the video is downloaded, even using --all-subs. Is there anyone else noticing this problem?
Thank you.
---

**Comment by dstftw** [comment]
You must provide account credentials for any work on this.

**Comment by rgmorato** [comment]
Could I provide in private?

**Comment by dstftw** [comment]
Mail is in my profile.

**Comment by rgmorato** [comment]
User and password (temporary) sent to your email.
Thanks.

**Comment by dstftw** [comment]
Will be fixed in the next version. You can change password now.

**Comment by rgmorato** [comment]
Thank you so much!

**Comment by rgmorato** [comment]
I tested it today and works fine!
Thank you again!

**Comment by kizulv** [comment]
Try this tools to download subtitles
https://pcthanh.com/download-subtitles-of-courses-from-pluralsight
