### ISSUE TITLE
downloading speed 

### ISSUE THREAD

**Issue by omansak** [rg3/youtube-dl#17689]
I am .net developer and using https://github.com/i3arnon/libvideo.
Before a few week Less than 360p have so slow download speed i fixed change request hearders and it worked.
>         SetRequestHeader("range", "bytes=0-");
>         SetRequestHeader("accept", "bytes"); // optimal
but now  greater than 360p videos same erros do u know any solution ? i tried restart/resume

**Comment by dstftw** [comment]
This is youtube-dl issue tracker not libvideo.
