### ISSUE TITLE
ARD mediathek: Unable to download JSON metadata: HTTP Error 404

### ISSUE THREAD

**Issue by tophee** [rg3/youtube-dl#17681]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### full verbose output:

```
$ youtube-dl --verbose https://www.ardmediathek.de/tv/Unser-Sa                                              ndm%C3%A4nnchen/Sendung?documentId=11094342&bcastId=11094342
[1] 2240
christoph@server:~$ [debug] System config: [u'--output', u'/srv/NAS/media/online-videos/%(playlist)s/%(autonumber)s-%(duration)ss-%(title)s.%(ext)s', u'--ignore-errors', u'--netrc', u'--add-metadata', u'--format', u'mp4', u'--write-info-json', u'--write-annotations', u'--all-subs', u'--write-description', u'--write-thumbnail', u'--verbose']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.ardmediathek.de/tv/Unser-Sandm%C3%A4nnchen/Sendung?documentId=11094342']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {}
[ARD:mediathek] 11094342: Downloading webpage
[ARD:mediathek] 11094342: Downloading media JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be  sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py",                                               line 604, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

$

...
<end of log>
```

Other commands producing similar errors are:

`youtube-dl --verbose https://www.ardmediathek.de/tv/Tagesschau-in-100-Sekunden/Sendung?documentId=52149182&bcastId=52149182`

and

 `youtube-dl --verbose https://www.ardmediathek.de/tv/Tagesschau-in-100-Sekunden/Tagesschau-in-100-Sekunden/Das-Erste/Video?bcastId=52149182&documentId=56407524`

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by tophee** [comment]
I'm sorry that I ended up pasting the wrong version of the command (I tried uncountable different versions based on various hints I found), but I did of course see that ampersand FAQ and did put the URL in quotation marks (both single and double) but that did not help either. 

In other words:  `youtube-dl --verbose "https://www.ardmediathek.de/tv/Unser-Sandm%C3%A4nnchen/Sendung?documentId=11094342&bcastId=11094342"` does not work either
