### ISSUE TITLE
[SITE Support Request] Download from 3SAT

### ISSUE THREAD

**Issue by pikespeak** [rg3/youtube-dl#17688]
[x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v http://www.3sat.de/mediathek/?mode=play&obj=75939
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.3sat.de/mediathek/?mode=play']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[generic] ?mode=play: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?mode=play: Downloading webpage
[generic] ?mode=play: Extracting information
ERROR: Unsupported URL: http://www.3sat.de/mediathek/?mode=play
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.3sat.de/mediathek/?mode=play

Der Befehl "obj" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
<end of log>
```

---

- Single video:http://www.3sat.de/mediathek/?mode=play&obj=75939

---

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by pikespeak** [comment]
Funking windows. Sorry!
