### ISSUE TITLE
Help with downloading all playlist from a youtube channel

### ISSUE THREAD

**Issue by scuff1034** [rg3/youtube-dl#17691]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*
---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I just downloaded youtube-dl what I want to is download all the playlist from this channel https://www.youtube.com/user/khanacademy/playlists?sort=dd&shelf_id=0&view=1and have the playlist download into a seperate folder
I try doing this  

Download all playlists of YouTube channel/user keeping each playlist in separate directory:

youtube-dl -o '%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https://www.youtube.com/user/khanacademy/playlists?sort=dd&shelf_id=0&view=1

but it doesnt work. 

I just need help with the command line. I know what I want to do but don't know how to put it all together. I want to download them in mp4 format, 360p resolution, I want it to have the name of the playlist and the videos to be numbered in the order that they appear in the playlist. 

And also to be able to download all the playlist from this URL 

https://www.youtube.com/user/khanacademy/playlists?sort=dd&shelf_id=0&view=1

**Comment by dstftw** [comment]
This command works just fine for what you are trying to do. For selecting format bother to read FAQ on format selection.
