### ISSUE TITLE
[YouTube] Unable to login: Invalid password

### ISSUE THREAD

**Issue by rcalabro** [rg3/youtube-dl#17702]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: [u'--output', u'~/Downloads/%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', u'--format', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/bestvideo+bestaudio/best', u'--prefer-ffmpeg', u'--audio-quality', u'0', u'--audio-format', u'mp3', u'--continue', u'--ignore-errors', u'--all-subs', u'--sub-format', u'best/srt', u'--add-metadata', u'--embed-thumbnail', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
[debug] Custom config: []
[debug] Command-line args: [u'6G-ZzP5z4yw', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.7.15 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to login: Invalid password
[youtube] 6G-ZzP5z4yw: Downloading webpage
[youtube] 6G-ZzP5z4yw: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1897, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.
```

### Description of your *issue*, suggested solution and other information

I am trying to download a private video (but the issue happens on the public one too) from YouTube, so I am providing my credentials with --username and --password flags, and triple checked if those are correct. I even changed my pass to one with no symbols or strange characters, but script keeps failing on the login part 
```
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to login: Invalid password
```

**Comment by rcalabro** [comment]
The video was a livestream from May 2017.

**Comment by Roasty-Float** [comment]
I am having the same problem. The information I can contribute is the login failure occurs regardless of the google account used (I've tried two). Also does not matter if the login information is passed through .netrc or entered manually into the terminal, still fails. 
I was attempting to pull some subscription videos earlier today and have been troubleshooting ever since.

**Comment by dstftw** [comment]
For any work on this you must provide reproducible account credentials.

**Comment by BEBEEGUN** [comment]
Did you install it with brew?

**Comment by Roasty-Float** [comment]
> For any work on this you must provide reproducible account credentials.

Fair enough, on my end the issue has resolved itself. Both accounts can now login and pull subscriptions without issue. I could see how this issue can't be reproduced. Thanks for your time, and thanks for your work on such a great program.
