### ISSUE TITLE
Support for Deutsche Bahn IC Bus Entertainment system

### ISSUE THREAD

**Issue by madduck** [rg3/youtube-dl#17717]
Since I could not use subtitles with the Deutsche Bahn IC Bus Entertainment system, I figured out how to download the videos. They are at XPath `//*[@id="VideoPlayer_html5_api"]`, and I attached a sample web page whose URL is http://entertainment.db/de/Filme/Lucy-en .
[DB IC BUS Entertainment.html.zip](https://github.com/rg3/youtube-dl/files/2431997/DB.IC.BUS.Entertainment.html.zip)

**Comment by madduck** [comment]
@remitamine I would have appreciated a reason, but I guess it's because this enables download of copyrighted material, which was not my intention, but which is not going to be added to youtube-dl.

**Comment by remitamine** [comment]
you didn't fill the issue template.

**Comment by madduck** [comment]
Your loss, for being a control freak.
