### ISSUE TITLE
Unable to download webpage: HTTP Error 404

### ISSUE THREAD

**Issue by RaitaroH** [rg3/youtube-dl#17727]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

```
▶ youtube-dl --version
2018.09.26
▶ ffmpeg --version                                                          
ffmpeg version 3.4.4-0ubuntu0.18.04.1 Copyright (c) 2000-2018 the FFmpeg developers
```

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
ydl "https://www.youtube.com/watch\?v\=03dWPODt0ZU" --verbose                              
[debug] System config: []
[debug] User config: ['-i', '-o', '~/Desktop/%(title)s.%(ext)s', '-f', 'best', '--no-playlist']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch\\?v\\=03dWPODt0ZU', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.6.6 (CPython) - Linux-4.15.0-34-generic-x86_64-with-neon-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {}
[generic] watch\?v\=03dWPODt0ZU: Requesting header
WARNING: Could not send HEAD request to https://www.youtube.com/watch\?v\=03dWPODt0ZU: HTTP Error 404: Not Found
[generic] watch\?v\=03dWPODt0ZU: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 604, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```
Both with `pip --user` and not this happens. I tried multiple videos both audio only and not and I am not sure.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Well, the video is not downloaded due to a 404. The videos I tried work in the browser though. VPN on or not, I still get 404.
I do want to mention I ubgraded from 16.04 to 18.04 and now I noticed the issue. I did reinstall pip and ydl with no effect.

**Comment by dstftw** [comment]
Do not escape anything when you quote the URL.

**Comment by RaitaroH** [comment]
No `"`? Oooo... I use so many quotes I think I added them by habit to ydl. My apologies.

**Comment by pward17** [comment]
Hey I was having this issue. It all started after either switching to Zsh or a plugin for it that automatically escapes characters. So that was a fun "bug" or "feature" to find. Grateful because this is what led to the discovery.  Thanks!
