### ISSUE TITLE
Error to download "Bakeoff" from it.dplay.com

### ISSUE THREAD

**Issue by andr3at** [rg3/youtube-dl#17723]
Hello,
I cannor download the forth episode of Bakeoff Italy. No problems in the last weeks to download the previous episodes.

Please find below my issue details.
Hope you can help on this.

Many thanks
Regards,
Andrea

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://it.dplay.com/realtime/bake-off-italia/stagione-6-episodio-4-puntata-del-28-settembre-2018/', '--verbose', '--output', '\\Bakeoff\\p04.mp4']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 79.62.135.239 (IT) as X-Forwarded-For.
[DPlayIt] stagione-6-episodio-4-puntata-del-28-settembre-2018: Downloading webpage
[DPlayIt] stagione-6-episodio-4-puntata-del-28-settembre-2018: Downloading JSON metadata
[DPlayIt] stagione-6-episodio-4-puntata-del-28-settembre-2018: Downloading m3u8 information
WARNING: unable to extract series; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract episode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[info] Available formats for 23769:
format code  extension  resolution note
hls-64       mp4        audio only   64k , mp4a.40.2
hls-234      mp4        320x180     234k , avc1.42C015, 25.0fps, mp4a.40.2
hls-463      mp4        480x270     463k , avc1.42C01F, 25.0fps, mp4a.40.2
hls-863      mp4        640x360     863k , avc1.4D401E, 25.0fps, mp4a.40.2
hls-1757     mp4        960x540    1757k , avc1.4D401F, 25.0fps, mp4a.40.2
hls-3350     mp4        1280x720   3350k , avc1.64001F, 25.0fps, mp4a.40.2
hls-6550     mp4        1920x1080  6550k , avc1.640029, 25.0fps, mp4a.40.2 (best)

**Comment by dstftw** [comment]
There are no errors in your log.
