### ISSUE TITLE
Jamendo.com new URLs

### ISSUE THREAD

**Issue by trainstationl** [rg3/youtube-dl#17724]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Jamendo has introduced a new subdomain, https://licensing.jamendo.com, meant specifically for commercial licensing of music. Since this subdomain is pretty new, I'm not certain but I'm pretty sure that all the tracks on https://licensing.jamendo.com are the same as the ones on the normal site, i.e. this is only a new UI.

This new site offers free MP3s for testing purposes, like the old site, but now the new MP3s have a voice that says "jamendo.com" every few seconds. This new format is called `mp35`.

e.g.
New URL:
https://licensing.jamendo.com/en/track/1496667/energetic-rock
Converted to the old URL style, it still works:
https://www.jamendo.com/track/1496667/energetic-rock

New "mp35" format URL for this track, requires no account to download:
https://storage.jamendo.com/download/track/1496667/mp35/

In fact, you can download all the formats for this track with this style of URL:
https://storage.jamendo.com/download/track/1496667/mp32/
https://storage.jamendo.com/download/track/1496667/mp31/
https://storage.jamendo.com/download/track/1496667/ogg1/
https://storage.jamendo.com/download/track/1496667/flac/

---

youtube-dl logs

New URL:
```
$ youtube-dl -v -F https://licensing.jamendo.com/en/track/1496667/energetic-rock
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://licensing.jamendo.com/en/track/1496667/energetic-rock']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-33-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {}
[generic] energetic-rock: Requesting header
WARNING: Falling back on generic information extractor.
[generic] energetic-rock: Downloading webpage
[generic] energetic-rock: Extracting information
ERROR: Unsupported URL: https://licensing.jamendo.com/en/track/1496667/energetic-rock
```

New URL converted to old-style URL:
```
$ youtube-dl -v -F https://www.jamendo.com/track/1496667/energetic-rock
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.jamendo.com/track/1496667/energetic-rock']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-33-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {}
[Jamendo] energetic-rock: Downloading webpage
WARNING: unable to extract duration; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[info] Available formats for 1496667:
format code  extension  resolution note
mp31         mp3        unknown    
mp32         mp3        unknown    
ogg1         ogg        unknown    
flac         flac       unknown    (best)
```

As you can see `mp35` is not listed in the available formats.

**Comment by joaquinito01** [comment]
Closed.

**Comment by trainstationl** [comment]
What about the `mp35` format?

**Comment by joaquinito01** [comment]
WTF? You will be reported and banned from this issue!!
