### ISSUE TITLE
[PluralSight] Unable to download captions JSON: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by quangtri8892** [rg3/youtube-dl#17728]
last version I tested
youtube-dl is up-to-date (2018.09.26)

I'm try to download video from PluralSight. Video is ok but subtitle is cannot download. The error is 
WARNING: Unable to download captions JSON: HTTP Error 404: Not Found
My command: 

youtube-dl --username xxx --password xxxx --sleep-interval 35 --max-sleep-interval 120 --sub-lang en --sub-format srt --write-sub https://app.pluralsight.com/library/courses/design-database-structure-sql-server-2014-70-465/table-of-contents

Thanks.

**Comment by Abdoam** [comment]
#17726 I think [this](https://github.com/Abdoam/youtube-dl/tree/patch-2) can help you.

**Comment by Abdoam** [comment]
this is my test after my alter code
![screenshot from 2018-10-01 12-00-46](https://user-images.githubusercontent.com/20693584/46282424-bf85e680-c571-11e8-99b5-78782d206c25.png)

**Comment by shootoutrw** [comment]
@Abdoam thanks!

![2018-10-01_073211](https://user-images.githubusercontent.com/42800632/46286259-86874b00-c54c-11e8-9891-3c03eeee9f8a.png)

**Comment by quangtri8892** [comment]
@Abdoam  Dear Abdoam, Could you mind compile it to .exe or run file for me. I don't known why it's still have error when I compile your code to run. Thanks you.

**Comment by Abdoam** [comment]
@quangtri8892  
test this file (I make it by ubuntu I CAN NOT test it :smile: :smile:  )
[youtube-dl.zip](https://github.com/rg3/youtube-dl/files/2436624/youtube-dl.zip)

**Comment by Abdoam** [comment]
@quangtri8892  
test this file (I make it by ubuntu I CAN NOT test it :smile: :smile:  )
Put this file in folder of Source Code and Run it.
[youtube-dl.zip](https://github.com/rg3/youtube-dl/files/2436624/youtube-dl.zip)
