### ISSUE TITLE
RaiPlay Error: Unable to download XML

### ISSUE THREAD

**Issue by ppoe6** [rg3/youtube-dl#17734]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\user>youtube-dl -v https://www.raiplay.it/video/2018/09/TV7-6b2e2fe7-89
e9-48ca-b954-a4b98a807675.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.raiplay.it/video/2018/09/TV7-6b2e
2fe7-89e9-48ca-b954-a4b98a807675.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-91399-g9f0077cc03, ffprobe N-91399-g9f0077cc03
[debug] Proxy map: {}
[RaiPlay] 6b2e2fe7-89e9-48ca-b954-a4b98a807675: Downloading video JSON
[RaiPlay] 6b2e2fe7-89e9-48ca-b954-a4b98a807675: Downloading XML metadata for pla
tform mon
[RaiPlay] 6b2e2fe7-89e9-48ca-b954-a4b98a807675: Downloading m3u8 information
[RaiPlay] 6b2e2fe7-89e9-48ca-b954-a4b98a807675: Downloading XML metadata for pla
tform flash
ERROR: Unable to download XML: [WinError 10054] Connessione in corso interrotta
forzatamente dall'host remoto (caused by ConnectionResetError(10054, "Connession
e in corso interrotta forzatamente dall'host remoto", None, 10054, None)); pleas
e report this issue on https://yt-dl.org/bug . Make sure you are using the lates
t version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the -
-verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\bu
ild\youtube_dl\extractor\common.py", line 604, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\bu
ild\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\bu
ild\youtube_dl\utils.py", line 983, in http_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1186, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1227, in getresponse
  File "C:\Python\Python34\lib\http\client.py", line 386, in begin
  File "C:\Python\Python34\lib\http\client.py", line 348, in _read_status
  File "C:\Python\Python34\lib\socket.py", line 378, in readinto

```

---

---

### Description of your *issue*, suggested solution and other information

I've encountered the same error with those two links for the moment: 
- https://www.raiplay.it/video/2018/09/TV7-6b2e2fe7-89e9-48ca-b954-a4b98a807675.html
- https://www.raiplay.it/video/2018/08/Red-Lights-9620bdaa-09dd-4032-a444-34b6431ef8a4.html

**Comment by dstftw** [comment]
Network issue on your side.
