### ISSUE TITLE
[FrontendMasters] Avoid downloading 6 versions of source JSON (Flags acc for suspicious activity)

### ISSUE THREAD

**Issue by Mikhail-MM** [rg3/youtube-dl#17739]
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

When downloading a video or Playlist from FrontEndMasters, the extractor queries and downloads 6 source JSON files as seen with this output:

[FrontendMasters]: SUltHcmxiB: Downloading webm-low source JSON
[FrontendMasters]: SUltHcmxiB: Downloading webm-mid source JSON
[FrontendMasters]: SUltHcmxiB: Downloading webm-highsource JSON
[FrontendMasters]: SUltHcmxiB: Downloading mp4-low source JSON
[FrontendMasters]: SUltHcmxiB: Downloading mp4-midsource JSON
[FrontendMasters]: SUltHcmxiB: Downloading mp4-high source JSON

After downloading leaving the downloader on all day (Sleep interval of 360) one of the admins pinged my account and informed me that my acc was flagged as using a downloader script, and also "By the way, your script is requesting each video 6 times, which only amplifies the problem."

I tried to specify a format selector in the cmd line arg but it still downloads all the JSON. Is there an arg to limit this, because this seems to be a flag for their systems.

**Comment by alexdmejias** [comment]
@Mikhail-MM were you able to find a solution to this?
