### ISSUE TITLE
[Crunchyroll] HTTP Error 307: Temporary Redirect

### ISSUE THREAD

**Issue by TammysHead** [rg3/youtube-dl#17749]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl.exe -v https://www.crunchyroll.com/black-clover/episode-51-proof-of-rightness-774912
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.crunchyroll.com/black-clover/episode-51-proof-of-rightness-774912']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-84814-gad7aff0, ffprobe N-84814-gad7aff0
[debug] Proxy map: {}
[crunchyroll] 774912: Downloading webpage
[crunchyroll] 774912: Downloading audio-jaJP-hardsub-itIT m3u8 information
[crunchyroll] 774912: Downloading audio-jaJP-hardsub-esLA m3u8 information
[crunchyroll] 774912: Downloading audio-jaJP-hardsub-enUS m3u8 information
[crunchyroll] 774912: Downloading audio-jaJP-hardsub-frFR m3u8 information
[crunchyroll] 774912: Downloading audio-jaJP-hardsub-deDE m3u8 information
[crunchyroll] 774912: Downloading audio-jaJP-hardsub-arME m3u8 information
[crunchyroll] 774912: Downloading audio-jaJP-hardsub-ptBR m3u8 information
[crunchyroll] 774912: Downloading audio-jaJP m3u8 information
[crunchyroll] 774912: Downloading audio-jaJP-hardsub-ruRU m3u8 information
[crunchyroll] 774912: Downloading media info
WARNING: Unable to download XML: HTTP Error 307: Temporary Redirect
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\__init__.py", line 472, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\__init__.py", line 462, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\YoutubeDL.py", line 2001, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\crunchyroll.py", line 601, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\utils.py", line 313, in xpath_text
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\utils.py", line 294, in xpath_element
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\utils.py", line 291, in _find_xpath
AttributeError: 'bool' object has no attribute 'find'
```

### Description of your issue, suggested solution and other information

I always get an Error 307 while downloading from Crunchyroll.

**Comment by TammysHead** [comment]
Maybe they changed from http to https? I am not sure about that error

**Comment by joshbrown50** [comment]
I'm also having this issue

**Comment by Kojirosan** [comment]
Me too

**Comment by joshbrown50** [comment]
Ok this was closed but I'm still having the issue. Wanna explain?

**Comment by Niggolo** [comment]
i have this error too

**Comment by ratchetfreak** [comment]
the fix will be in the next release.
