### ISSUE TITLE
youtube hd(22) format not found

### ISSUE THREAD

**Issue by poptong** [rg3/youtube-dl#17754]
youtube-dl --version
2018.09.26

youtube-dl -F https://www.youtube.com/watch?v=TNWMZIf7eSg

[youtube] TNWMZIf7eSg: Downloading webpage
[youtube] TNWMZIf7eSg: Downloading video info webpage
[info] Available formats for TNWMZIf7eSg:
format code  extension  resolution note
249          webm       audio only DASH audio   54k , opus @ 50k, 1.28MiB
250          webm       audio only DASH audio   72k , opus @ 70k, 1.70MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 3.39MiB
251          webm       audio only DASH audio  142k , opus @160k, 3.38MiB
171          webm       audio only DASH audio  147k , vorbis@128k, 3.19MiB
278          webm       256x144    144p   98k , webm container, vp9, 24fps, video only, 2.42MiB
394          mp4        256x144    144p   99k , av01.0.05M.08, 24fps, video only, 2.30MiB
160          mp4        256x144    144p  111k , avc1.4d400c, 24fps, video only, 2.24MiB
395          mp4        426x240    240p  220k , av01.0.05M.08, 24fps, video only, 4.50MiB
242          webm       426x240    240p  223k , vp9, 24fps, video only, 4.50MiB
133          mp4        426x240    240p  348k , avc1.4d4015, 24fps, video only, 5.06MiB
396          mp4        640x360    360p  386k , av01.0.05M.08, 24fps, video only, 8.08MiB
243          webm       640x360    360p  407k , vp9, 24fps, video only, 8.50MiB
134          mp4        640x360    360p  662k , avc1.4d401e, 24fps, video only, 10.33MiB
397          mp4        854x480    480p  696k , av01.0.05M.08, 24fps, video only, 14.55MiB
244          webm       854x480    480p  752k , vp9, 24fps, video only, 15.47MiB
135          mp4        854x480    480p 1308k , avc1.4d401e, 24fps, video only, 20.81MiB
247          webm       1280x720   720p 1478k , vp9, 24fps, video only, 25.93MiB
136          mp4        1280x720   720p 1887k , avc1.4d401f, 24fps, video only, 28.68MiB
248          webm       1920x1080  1080p 2642k , vp9, 24fps, video only, 44.16MiB
137          mp4        1920x1080  1080p 3086k , avc1.640028, 24fps, video only, 46.68MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 2.10MiB
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2, 5.86MiB
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 16.47MiB (best)

YOUTUBE VIDEO HD VIDEO NOT FOUND

**Comment by dstftw** [comment]
>247 webm 1280x720 720p 1478k , vp9, 24fps, video only, 25.93MiB
136 mp4 1280x720 720p 1887k , avc1.4d401f, 24fps, video only, 28.68MiB

**Comment by poptong** [comment]
> > 247 webm 1280x720 720p 1478k , vp9, 24fps, video only, 25.93MiB
> > 136 mp4 1280x720 720p 1887k , avc1.4d401f, 24fps, video only, 28.68MiB

i want video + audio  (22 format)

This format was previously there but was gone.

**Comment by Hrxn** [comment]
Not all formats are available, this is done on YT's side.

**Comment by poptong** [comment]
> 모든 형식을 사용할 수있는 것은 아닙니다. YT 측에서 수행합니다.

This was the format used in previous versions

**Comment by Kumuduweerasinghe** [comment]
Yes he is right youtube-dl can't extract HD(22) video....  But savefrom.net does it....  How is that possible? 
 save from.net and you will see the result for above url
