### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by AndriusWild** [rg3/youtube-dl#17763]
Hello, youtube-dl has stopped working in my termux app. I did update it to the latest available version but it did not help. Is there a solution?

---
[youtube] tvvJDPLacMs: Downloading webpage
[youtube] tvvJDPLacMs: Downloading video info webpage
[youtube] tvvJDPLacMs: Downloading js player vfl07ioI6
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1199, in _decrypt_signature
    video_id, player_url, s
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1110, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1171, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 880, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[Process completed (code 1) - press Enter]

---

youtube-dl -v
[debug] System config: []
[debug] User config: ['--no-mtime', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', '-o', '/storage/emulated/0/SamsungMusic/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.04
[debug] Python version 3.6.6 (CPython) - Linux-4.4.78-13949550-aarch64-with-libc
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

**Comment by Hrxn** [comment]
> [debug] youtube-dl version 2018.06.04

Outdated version.
