### ISSUE TITLE
Stream directly to mpv.exe on Windows 10?

### ISSUE THREAD

**Issue by m1m2m3mr** [rg3/youtube-dl#17771]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information
How can I stream youtube-dl directly to my custom mpv.exe on Windows 10?
The "stdin" and the command is for linux only and does not work on Windows
Fully download takes long time and i don't want to wait.

**Comment by qkolj** [comment]
Download `youtube-dl.exe` from [the official download page](http://rg3.github.io/youtube-dl/download.html) and place it in the same directory as `mpv.exe`. After you have done that, running `mpv.exe <link to the video>` in command prompt from that directory should work as intended.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#how-do-i-stream-directly-to-media-player

**Comment by m1m2m3mr** [comment]
It actually works. Thank you very much!
