### ISSUE TITLE
Download every Youtube Video/Playlist with only ID 

### ISSUE THREAD

**Issue by Skydef** [rg3/youtube-dl#17772]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Hello.
I use youtube-dl only for Youtube.
Until now I've every time used the specific video ID or playlist ID to download something or gather information about it.
But now I am running into trouble because ID's can begin with the '-' character and then it is detected as command. I've tried to put it in apostrophes but this didn't helped.
I just want to ask: Is there an easy solution to tell youtube-dl that this is an ID or do I have to put the "https://www.youtube.com/watch?v=" / "https://www.youtube.com/playlist?list=" in front of the ID to make sure it works?

**Comment by remitamine** [comment]
https://github.com/rg3/youtube-dl#how-do-i-download-a-video-starting-with-a--
