### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by lachuza** [rg3/youtube-dl#17786]
Try to get vk.com url and generates a invalid url inone machine and valid in other.

youtube-dl -g  https://vk.com/video-51189706_456244634
634 -v                                                                                                       
[debug] System config: []                                                                                    
[debug] User config: []                                                                                      
[debug] Custom config: []                                                                                    
[debug] Command-line args: [u'-g', u'https://vk.com/video-51189706_456244634', u'-v']                        
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8                                             
[debug] youtube-dl version 2018.09.26                                                                        
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-20-generic-x86_64-with-Ubuntu-18.04-bionic         
[debug] exe versions: none                                                                                   
[debug] Proxy map: {}                                                                                        
[debug] Default format spec: bestvideo+bestaudio/best                                                        
https://cs6-8v4.vkuservideo.net/video/hls/p18/14f300a3c3c5/index-f2-v1-a1.m3u8?extra=RlT5yNqZ9KxoU-4nAtWVUGvD
WzzospqE-nVN_dXfjBq67JndnJKhMy9fxtyRgd0fBz8XcZKqMS1cmCTBkIWJFHCDPY-iJw46u44-F_W9JIY0UisNqfpvpc1fLlZqVSEC1P1we
s4RUZ2_0Q                                              

I try the same command in other machine and works just fine.                 
youtube-dl -g  https://vk.com/video-51189706_456244634 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-g', u'https://vk.com/video-51189706_456244634', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
https://cs6-8v4.vkuservideo.net/video/hls/p18/476d34e200fe/index-f2-v1-a1.m3u8?extra=vjNW9POhFcqoaSE_7NIWKL_V4zagIwd9-AtfMCLvLrfluxEpDJCo-haseCNQML_UljDYSWc9h2NnA1OuD0t7BE33QbQkwIXJrg11GafSuX6kBCJ26hSZuEDbIpfUAQWcKPx39VGqLalN

What is the problem?

**Comment by dstftw** [comment]
What exactly do you mean by invalid URL?

**Comment by lachuza** [comment]
the first url in my comments dosent works, but the second yes and is the same video for both.

**Comment by dstftw** [comment]
Again: what exactly do you mean by "does not work". Post the output of `youtube-dl https://vk.com/video-51189706_456244634` from this machine.

**Comment by mrfade** [comment]
vk uses hotlink protection maybe because of that

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser

**Comment by lachuza** [comment]
Case 1 (dosent works, you cannot download the video from the url)
youtube-dl -g  https://vk.com/video-51189706_456244634                                                                                                          
https://cs6-8v4.vkuservideo.net/video/hls/p18/14f300a3c3c5/index-f2-v1-a1.m3u8?extra=RlT5yNqZ9KxoU-4nAtWVUGvD
WzzospqE-nVN_dXfjBq67JndnJKhPCddxtyRgd0fBz8XcZKqMS1cmCTBkIWJFHCDPY-iJw46u44-F_W9JIY0UisNqfpvpc1fLlZqVXoF0vdzK
50dXZzr1w                                                     
Case 2 (WORKS you can download the video from the url)
youtube-dl -g https://vk.com/video-51189706_456244634 
https://cs6-8v4.vkuservideo.net/video/hls/p18/476d34e200fe/index-f2-v1-a1.m3u8?extra=vjNW9POhFcqoaSE_7NIWKL_V4zagIwd9-AtfMCLvLrfluxEpDJCo9R6ueCNQML_UljDYSWc9h2NnA1OuD0t7BE33QbQkwIXJrg11GafSuX6kBCJ26hSZuEDbIpfUBQCUeft1ogr8f61M

**Comment by mrfade** [comment]
@lachuza You could not download the extracted url from another machine/ip because VK uses hotlink protection which allows to access from the same machine/ip
