### ISSUE TITLE
Blacklist vcodec in format

### ISSUE THREAD

**Issue by jairosh** [rg3/youtube-dl#17795]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo[vcodec!=av1]', 'eu0KsZ_MVBc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.6.6 (CPython) - Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[youtube] eu0KsZ_MVBc: Downloading webpage
[youtube] eu0KsZ_MVBc: Downloading video info webpage
[youtube] {18} signature length 40.41, html5 player vfl-vYfC3
[youtube] {36} signature length 40.41, html5 player vfl-vYfC3
[youtube] {17} signature length 40.41, html5 player vfl-vYfC3
[youtube] {137} signature length 40.41, html5 player vfl-vYfC3
[youtube] {248} signature length 40.41, html5 player vfl-vYfC3
[youtube] {399} signature length 40.41, html5 player vfl-vYfC3
[youtube] {136} signature length 40.41, html5 player vfl-vYfC3
[youtube] {247} signature length 40.41, html5 player vfl-vYfC3
[youtube] {398} signature length 40.41, html5 player vfl-vYfC3
[youtube] {135} signature length 40.41, html5 player vfl-vYfC3
[youtube] {244} signature length 40.41, html5 player vfl-vYfC3
[youtube] {397} signature length 40.41, html5 player vfl-vYfC3
[youtube] {134} signature length 40.41, html5 player vfl-vYfC3
[youtube] {243} signature length 40.41, html5 player vfl-vYfC3
[youtube] {396} signature length 40.41, html5 player vfl-vYfC3
[youtube] {133} signature length 40.41, html5 player vfl-vYfC3
[youtube] {242} signature length 40.41, html5 player vfl-vYfC3
[youtube] {395} signature length 40.41, html5 player vfl-vYfC3
[youtube] {160} signature length 40.41, html5 player vfl-vYfC3
[youtube] {278} signature length 40.41, html5 player vfl-vYfC3
[youtube] {140} signature length 40.41, html5 player vfl-vYfC3
[youtube] {171} signature length 40.41, html5 player vfl-vYfC3
[youtube] {249} signature length 40.41, html5 player vfl-vYfC3
[youtube] {250} signature length 40.41, html5 player vfl-vYfC3
[youtube] {251} signature length 40.41, html5 player vfl-vYfC3
[debug] Invoking downloader on 'https://r2---sn-p0n5jxaa-hxms.googlevideo.com/videoplayback?mm=31%2C26&mn=sn-p0n5jxaa-hxms%2Csn-q4fl6n7z&expire=1538743110&mt=1538721365&pl=24&mv=m&ei=5ga3W_byCsimDYbls4gN&ms=au%2Conr&source=youtube&itag=399&clen=52126505&fvip=5&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C395%2C396%2C397%2C398%2C399&mime=video%2Fmp4&requiressl=yes&ip=187.190.153.89&initcwndbps=1010000&ipbits=0&lmt=1537156209117353&key=yt6&dur=284.450&gir=yes&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&c=WEB&keepalive=yes&id=o-AIFXpg9ZVnO6GRaa3DD0fyvTGNZzr2-Tvh4xbc5xEVVZ&signature=683B61901EDD602AF9E5CF66010196EC861A2F33.65E1DC3744AF65E887FBBEE32C08CA7050C0DB3E&ratebypass=yes'
[download] Destination: The Avalanches - Because I'm Me (Official Video)-eu0KsZ_MVBc.mp4
[download] 100% of 49.71MiB in 00:07
```

---

### Description of your *issue*, suggested solution and other information

Trying to blacklist a certain vcodec (AV1) has no effect with the not equal comparison. The resulting file uses the AV1 codec as reported by ffprobe

Command line used:
```
youtube-dl -v -f "bestvideo[vcodec != av1]" eu0KsZ_MVBc 
```

**Comment by dstftw** [comment]
There is no such `vcodec` `av1` but `av01.0.05M.08`.

**Comment by jairosh** [comment]
Is there any way to negate comparisons? In this case to implement "Does not start with" in the format
```
youtube-dl -v -f "bestvideo[vcodec!^=av]" 
```

**Comment by raytracer-dreamwalker** [comment]
> Is there any way to negate comparisons? In this case to implement "Does not start with" in the format
> 
> ```
> youtube-dl -v -f "bestvideo[vcodec!^=av]" 
> ```

I am using  [this solution](https://www.reddit.com/r/youtubedl/comments/fddk1p/how_to_reject_av1_codec/fjh9uj1/).
It seems to work, but I can't guarantee it for all scenarios and combinations. I am using it like so:
`youtube-dl -f 'bestvideo[vcodec!*=av01]'`
