### ISSUE TITLE
Patreon - Unable to Login

### ISSUE THREAD

**Issue by TjohAGq6VQWLt7gKMo** [rg3/youtube-dl#17792]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**
```
root@ubuntu:/tmp# youtube-dl --version
2018.10.05
```
### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.patreon.com/ThePreparedMind/overview']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-135-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15-0ubuntu0.16.04.1, ffprobe 2.8.15-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] overview: Requesting header
WARNING: Falling back on generic information extractor.
[generic] overview: Downloading webpage
[generic] overview: Extracting information
[download] Downloading playlist: The Prepared Mind is creating Thought Provoking Content | Patreon
[generic] playlist The Prepared Mind is creating Thought Provoking Content | Patreon: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to login: Invalid password
[youtube] y_9eK_VHyE0: Downloading webpage
[youtube] y_9eK_VHyE0: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] What are you gonna do-y_9eK_VHyE0.mkv has already been downloaded and merged
[download] Finished downloading playlist: The Prepared Mind is creating Thought Provoking Content | Patreon
```
---

I am attempting to scrape a Patreon page, but youtube-dl is reporting my password is incorrect. I have changed the password a few times from complex to extremely simple (ie. allow lowercase, no symbols), however the error continues.

I did attempt to use a cookie file as well using the cookies.txt Chrome plugin, however when youtube-dl runs with the cookie it doesn't see the "logged in" content.

I have confirmed I can log into Patreon using Chrome on the same system for which I am running youtube-dl.

**Comment by remitamine** [comment]
> [youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to login: Invalid password

`youtube-dl` is trying to login to youtube.com, not Patreon.

**Comment by TjohAGq6VQWLt7gKMo** [comment]
Thank you for the clarification.

How would I go about using youtube-dl to scrape the content from Patreon then?

I have checked the docs numerous times and beyond the authentication options I don't see how I would pass the locked content to youtube-dl.

The YouTube videos themselves do not require a login, they are just hidden on the YouTube account and only accessible via direct link you get from the Patreon posts.

I have double-checked and confirmed Patreon is on the supported list for youtube-dl.

**Comment by Hrxn** [comment]
> The YouTube videos themselves do not require a login, they are just hidden on the YouTube account and only accessible via direct link you get from the Patreon posts.

So, these videos (shared via direct link from posts on Patreon) are actually hosted on YT?
Well, I think you have all that you need. Try youtube-dl with those direct links and see what happens?

**Comment by TjohAGq6VQWLt7gKMo** [comment]
Yes, the videos the user posts are hosted by YouTube.

Youtube-dl is capable of downloading the videos if I feed it each YouTube video link individually.

If you don't mind, allow me to rephrase my question.

Patreon is listed as supported by Youtube-dl, would you mind explaining what that support entails?

I assumed I could provide youtube-dl the link to the Patreon page and it would be able to automatically scrape the page downloading each of the YouTube videos embedded in each post.

My assumption is apparently incorrect, so I am looking for insight on what is supported as I can't seem to locate that information in the docs.

Thank you.

**Comment by Hrxn** [comment]
> If you don't mind, allow me to rephrase my question.

Sure, I don't mind at all..

> My assumption is apparently incorrect, so I am looking for insight on what is supported as I can't seem to locate that information in the docs.

Not really, I'd say. Your assumption is reasonable, the problem is rather the documentation about supported sites:
https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md

Patreon is indeed listed, without further information. I had this issue before, just another recent example: Coub. Still listed as supported, but it is not working right now as well.

So this document is not necessarily wrong, it is just often outdated.
This project is lacking some maintainers, sadly, and the bunch that still sticks around is doing the best they can, I think. Just look at the amount of invalid or incomplete issues filed on this tracker.
That's what they have to deal with..

> Youtube-dl is capable of downloading the videos if I feed it each YouTube video link individually.

Yeah, and in many cases, nothing else is really necessary.
There are many different ways to extract a batch of desired links, which can then be fed to youtube-dl.
By putting them in a file, for example, and handing that over to youtube-dl with `-a`.

**Comment by remitamine** [comment]
extraction has been partially fixed, but I can't test Patron-only content, you can try to use cookies with the new changes and see if it works for you(make sure that you're using post URLs like https://www.patreon.com/posts/10-05-audio-dont-21861693).

**Comment by TjohAGq6VQWLt7gKMo** [comment]
@remitamine - Would it be possible for me to send the funds via PayPal so you may purchase access to Patron-only content to allow further development?

**Comment by TjohAGq6VQWLt7gKMo** [comment]
I have attempted to download using a cookie file, but unfortunately I am running into 403 forbidden.

```
root@ubuntu:~/Downloads# youtube-dl -v --cookies /root/Downloads/cookies.txt https://www.patreon.com/posts/10-05-audio-dont-21861693
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--cookies', u'/root/Downloads/cookies.txt', u'https://www.patreon.com/posts/10-05-audio-dont-21861693']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-137-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15-0ubuntu0.16.04.1, ffprobe 2.8.15-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 10-05-audio-dont-21861693: Requesting header
WARNING: Could not send HEAD request to https://www.patreon.com/posts/10-05-audio-dont-21861693: HTTP Error 403: Forbidden
[generic] 10-05-audio-dont-21861693: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 604, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

```
root@ubuntu:~/Downloads# youtube-dl --version
2018.10.05
```

The cookie file was created using the "cookies.txt" extension for Chrome and was downloaded on the same machine for which youtube-dl is running.

**Comment by remitamine** [comment]
try first with cookies it might work, if not then you can temporarily share the account(if you're willing and if you trust me) privately to add support for Patron-only content and then change the credentials again.

**Comment by remitamine** [comment]
the changes have not been released yet, you have to use the latest changes(https://github.com/rg3/youtube-dl/archive/master.zip).

**Comment by TjohAGq6VQWLt7gKMo** [comment]
> try first with cookies it might work, if not then you can temporarily share the account(if you're willing and if you trust me) privately to add support for Patron-only content and then change the credentials again.

I am happy to share my Patreon credentials temporarily, shall I send it over to the email address on your profile?

**Comment by remitamine** [comment]
yes.

**Comment by TjohAGq6VQWLt7gKMo** [comment]
> yes.

Excellent, sent.

Thank you!
