### ISSUE TITLE
ERROR: No video formats found

### ISSUE THREAD

**Issue by hila3000** [rg3/youtube-dl#17802]
Hi all,

I'm trying to download a course from Pluralsight.
I've downloaded successfully 2 coursed today, but when tried another one (and another one, for troubleshooting), it succeeded to download only one file, and on the second one it fails each time with this error-
ERROR: No video formats found; 

in debug mode-
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\pluralsight.py", line 421, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 1286, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I'm using the latest 5.10.18 version.
running windows 10 version 1803 (OS build 17134.285) 
downloading using this syntax-
youtube-dl.exe --cookies d:\cookies-pluralsight-com.txt -o "%(playlist_index)s - %(title)s.%(ext)s" --min-sleep-interval 45 --max-sleep-interval 60 https://www.pluralsight.com/courses/aws-networking-deep-dive-vpc --playlist-start 1 --verbose

I tried deleting the one file it was succeeded to download and rerun, and still.. download one file, on the second it fails with this error.

quick reminder, I was downloading successfully and fully 2 courses until an hour ago.. when trying any other one, I get this error on the 2nd video file attempted.

Thanks and hope you could help
Hila

**Comment by dstftw** [comment]
For any work on this you must provide reproducible environment.

**Comment by hila3000** [comment]
You mean my credentials? sure. can I send it you by mail rather paste here publicly?

**Comment by hila3000** [comment]
I tried viewing the courses via the pluralsight and it doesn't work either. seems like they let access to only 2 courses for trial users.. so the issue was because of that.
