### ISSUE TITLE
SoundCloud URLs with very little time of life

### ISSUE THREAD

**Issue by avniir** [rg3/youtube-dl#17819]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl -g --restrict-filenames -v https://soundcloud.com/france-dj/d

j-france-rage-dubstep-2014
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-g', '--restrict-filenames', '-v', 'https://soundcl
oud.com/france-dj/dj-france-rage-dubstep-2014']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best

https://cf-media.sndcdn.com/poj3MfLbhE50.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJl
c291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vcG9qM01mTGJoRTUwLjEyOC5tcDMiLCJDb25k
aXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1Mzg4NjU5MTZ9fX1dfQ__&Sig
nature=O2xfr0aujOaDlyh4IOGbm2VdkMT3WQIXOz5UK-FcH0TYDJYgLGjr4Hsh5HHShKb26TufFl2-N
4YLLTUe7ufwrGSL38f2G12-yHcdjpmW-6cy8O6STSzpf8RpuSZQEUJERGVYmwqGWeUZcOJXENhWzbw-2
Sc1nueGxTBbz1Rvf0d9T1UN53cOF8QqhLeEW46s7Sy3xQa8XSMj7GaIuQnZMFfXyHvNh8rqOcJL7bGgx
9gnsiNt60JmJKIdcj088Ge3aUUT0F677YB7UMZZdfLuMGj4FV-qvvJZcykFbv~WoCqT46mQuJl8rqe0h
N8veIrSijExsj5oGg5EFzIWaKRWDw__&Key-Pair-Id=APKAJAGZ7VMH2PFPW6UQ
```

### Description of your *issue*, suggested solution and other information

The URL that starts with "cf-media." provided by youtube-dl for SoundCloud tracks, has a very little time of life, of about 15-20 minutes, past this time URL returns a lovely "Forbidden".
I would like to know if there're any ways to obtain URLs with longer time of life?

**Comment by dstftw** [comment]
No way.

**Comment by avniir** [comment]
Other question; is it possible to block the downloading of a file by youtube-dl after certain size? I mean, after 15 mb downloaded, stop the download? So I can play the mp3, listen to what equals to 15 mb?

**Comment by dstftw** [comment]
Ctrl+C.

**Comment by avniir** [comment]
Yeah, but I mean reproduce this exact action with commands & options?

**Comment by dstftw** [comment]
Not possible.
