### ISSUE TITLE
Download URL for DASH videos (example formats: 136 & 137) is regularly not working

### ISSUE THREAD

**Issue by Termii2** [rg3/youtube-dl#17812]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README][FAQ][BUGS]
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
### What is the purpose of your *issue*?
- [x] Question
### Description of your *issue*, suggested solution and other information

I have searched for a solution for several hours (literally), but couldn't find one. I am sorry, If my problem seems simple or stupid to you. Also, I am sorry for my bad writing, I am not native English and heavily struggled with the wording of my problem.

**My Goal:**
I am trying to get the Download URLs for new YouTube Videos (Videos that just got uploaded) as fast as possible and in good quality (720p+). I don't really care about the audio for now. Therefore, the best formats for me are: 22 (mp4 720p muxed video), 136 (mp4 720p DASH video) and 137 (mp4 1080p DASH video). 

The DASH (video only) formats are usually available before the muxed (video & audio) formats. That's why I highly prefer the formats 136 and 137 over the format 22. webm formats seem to be the slowest, so I ignore them completely.

**My Problem:**
The DASH formats are sometimes downloadable and sometimes not. I have no clue why I sometimes can't get a working Download URL for these formats.

**An Example:**
youtube-dl -f 136 --get-url https://www.youtube.com/watch?v=Lhw5xo67tdE

The above line gives me the following Download URL, which is not working: 

https://r2---sn-4g5ednsz.googlevideo.com/videoplayback/id/2e1c39c68ebbb5d1/itag/136/source/yt_otf/requiressl/yes/ms/au,onr/mn/sn-4g5ednsz,sn-2gb7sn7s/mm/31,26/initcwndbps/1640000/gcr/de/pl/33/mv/m/ei/-Lm4W8iRN4as7gOjha7IDw/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1538804333825591/fvip/2/mt/1538832759/disable_polymer/true/ip/2a02:908:4c8:a5a0:cdd1:be80:64d9:db5e/ipbits/0/expire/1538854489/sparams/ip,ipbits,expire,id,itag,source,requiressl,ms,mn,mm,initcwndbps,gcr,pl,mv,ei,ratebypass,mime,otfp,otf,lmt/signature/8BF5C062893295ECA0A89A13B0584D529A160A31.243F2A495E473FA2D5E912FAAB0998951EE4A58C/key/dg_yt0/

youtube-dl -f 137 --get-url https://www.youtube.com/watch?v=Lhw5xo67tdE
  
The above line gives me the following Download URL, which is working: 

https://r2---sn-4g5ednsz.googlevideo.com/videoplayback/id/2e1c39c68ebbb5d1/itag/137/source/youtube/requiressl/yes/mm/31,26/pl/33/mn/sn-4g5ednsz,sn-2gb7sn7s/mv/m/ms/au,onr/gcr/de/ei/crq4W_WbDoqWgQeYt7vAAQ/initcwndbps/1587500/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/5840808617/lmt/1538804333825591/dur/11666.534/mt/1538832839/fvip/2/disable_polymer/true/ip/2a02:908:4c8:a5a0:cdd1:be80:64d9:db5e/ipbits/0/expire/1538854610/sparams/ip,ipbits,expire,id,itag,source,requiressl,mm,pl,mn,mv,ms,gcr,ei,initcwndbps,ratebypass,mime,otfp,gir,clen,lmt,dur/signature/4E362C28980E748D161154525DE4927A45146BF7.21D45E9F562BEBF115EC6DC8900D05CF726E5126/key/dg_yt0/

**My Question:**
Am I doing it wrong? Some Download Links work and some don't. I am unsure if the problem lies with me or the way YouTube stores the Download Links for DASH-video-formats.
Is there a workaround which will let me grab working Download URLs for the formats 136 and 137 more consistently?

**Comment by dstftw** [comment]
This is not a download URL but base URL to MPD manifest of true segmented DASH.

**Comment by Termii2** [comment]
as said before, sorry for my wording. 

Why does one URL work in my browser (the URL I get from the format 137) and the other not (the URL I get from the format 136)? What can I do to get both of them to work?

**Comment by dstftw** [comment]
Ask youtube why. Again: there are **no direct download URLs** for these formats because these formats are **only available as segmented DASH**.
