### ISSUE TITLE
youtube-dl runs by default in the background: bug or feature?

### ISSUE THREAD

**Issue by giacecco** [rg3/youtube-dl#17826]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

I have not been using ```youtube-dl``` for a while. I got back to it today - on MacOS 10.14, v 2018.10.05 installed through Homebrew - and realised that now it always executes in the background, as if I was adding ```&``` to the end of the command line. Is that by design? Is there a way to run in the foreground as in the old days? Thanks.

**Comment by dstftw** [comment]
It does not in background by default.

**Comment by giacecco** [comment]
Happy to know you haven't changed the script's behaviour, but have you got any idea of what could be happening in my case then? youtube-dl is the only script behaving this way.
