### ISSUE TITLE
error running the script through Windows10

### ISSUE THREAD

**Issue by TTT2866** [rg3/youtube-dl#17831]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ X] Question
- [ ] Other

----------------------------
Sorry I'm super new to this, but how do I run it?
I've tried a few things but I think this explains what I'm attempting to do. What am I doing wrong? 
Python Version 3.6.4

C:\Users\HUM0014\Desktop\youtube-dl\bin>youtube-dl -h
'youtube-dl' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\HUM0014\Desktop\youtube-dl\bin>py youtube-dl -help
Traceback (most recent call last):
  File "youtube-dl", line 3, in <module>
    import youtube_dl
ImportError: No module named youtube_dl

C:\Users\HUM0014\Desktop\youtube-dl\bin>

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#installation
