### ISSUE TITLE
[VK.COM] 'download-archive' does not save uploader id, so different uploaders' videos with same IDs wrongly marked as downloaded

### ISSUE THREAD

**Issue by nulledone** [rg3/youtube-dl#17847]

**Comment by nulledone** [comment]
Why?

**Comment by nulledone** [comment]
@dstftw Can you explain why you close this issue? Title itself is enough for one to understand the problem.

**Comment by dstftw** [comment]
No, it's not. Bother to read and fill the new issue template.

**Comment by nulledone** [comment]
How is not? 
Issue:'download-archive' command line does not save the uploader ID.
Which causes wrongly marking of different videos with same video IDs as downloaded.
