### ISSUE TITLE
how do i bypass geo-restriction?

### ISSUE THREAD

**Issue by enanajmain** [rg3/youtube-dl#17849]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

I'm in Bangladesh where much of old youtube videos are blocked. There is a section in the readme about **Geo-restriction**, but I didn't figure out how to do it. For example, I need to stream [this video](https://www.youtube.com/watch?v=aCyGvGEtOwc) from my country where it is blocked. How would I do that?

**Comment by dstftw** [comment]
Use proxy or VPN.

**Comment by zaidalikhan9** [comment]
Hello, I guess you have to go for the following steps. Just go to your device’s settings, direct to ‘iTunes & App Store press on your Apple ID and choose the option that says View Apple ID. Here sign-in using your Apple ID password, on your account dashboard, click on ‘Country/Region’ and pick the option of Change Country or Region. Scroll down the options and pick your preferred country. Read more about bypassing geo restriction from [https://thevpn.guru/how-bypass-geo-restrictions-location-errors/](https://thevpn.guru/how-bypass-geo-restrictions-location-errors/) now. Now an agreement notification comes into your screen and click on ‘Agree’ to accept Apple’s Media Services Terms and Conditions.

You will be asked to fill the ‘BILLING ADDRESS’ portion on the shown page. Just fill in a billing address in your selected country, click on ‘Next’ at the top-right of the ‘ACCOUNT.’ There is no need to fill in your credit/debit card details, choose the option of ‘None’ for both PayPal and Credit card details. Introduce your iTunes applications and find your geo-restricted application you like.
