### ISSUE TITLE
Please add possibility to use leading zero in season_number and episode_number parameters

### ISSUE THREAD

**Issue by bombaaa** [rg3/youtube-dl#17841]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When using youtube-dl to download tv-shows, and **using output templates** **(-o)**, it's problematic for sorting purposes that it's not possible to have a leading zero in the numeric numbering of in particular  **season_number** and **episode_number** parameters.
This leads to none standard naming of tv shows for indexing purposes and listing in popular media center applications/backends as plex and kodi.

I have a temp solution to this, as to manually specify a 0 in the output template, but that is just odd, as it saves files with 3 digit numbering in season and episode format if epidoe equals 10 or above, se below for my naming:

/%(series)s/%(series)s.S0%(season_number)sE0%(episode_number)s.720p.WEB-DL.H264-YTDL.%(ext)s"

As of now the parameters starts counting at 1, but I would really like to have the possibility to start naming at 01

Please add the possibility to use leading zero in season_number and episode_number parameters.

If anybody has a solution with existing options/parameters/strings, please let me know

**Comment by dstftw** [comment]
Have you even read FAQ?
>The special sequences may be formatted according to [python string formatting operations](https://docs.python.org/2/library/stdtypes.html#string-formatting). For example, `%(NAME)s` or `%(NAME)05d`.

**Comment by bombaaa** [comment]
> Have you even read FAQ?
> 
> > The special sequences may be formatted according to [python string formatting operations](https://docs.python.org/2/library/stdtypes.html#string-formatting). For example, `%(NAME)s` or `%(NAME)05d`.
> 
> > For numeric sequences you can use numeric related formatting, for example, `%(view_count)05d` will result in a string with view count padded with zeros up to 5 characters, like in `00042`.

So sorry! 
I read trough the whole guide and FAQ, but I didn't understand the possibilities i guess. 
I see now how you can customize almost everything. Very clever to build it this way, and accept formatting of string output :)
 
New to the game, but definitely learned something. 
Guess I have to start learn some basic python. I just read a tutorial of Formatting strings, and I understand now.

For others that may search for this. 
Read the [InformIT guide on Formatting strings](http://www.informit.com/articles/article.aspx?p=28790&seqNum=2)

**Comment by MGadAllah** [comment]
Thanks.
Sorry ... it was not clear for me. The key is what you said to use "d" operators with numbers of 0s I want.
Thanks
