### ISSUE TITLE
itag 22 is missing in some videos but savefrom.net gives download links for itag 22

### ISSUE THREAD

**Issue by Kumuduweerasinghe** [rg3/youtube-dl#17842]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

This is a vevo video [https://www.youtube.com/watch?v=XCQK6LmhYqc](https://www.youtube.com/watch?v=XCQK6LmhYqc  ). savefrom.net gives itag 22 to download all the time. But when I try to download it from youtube-dl, it only gives me best format 18. Why is that? am I missing some thing.

1. here we don't have itag=22 available
![image](https://user-images.githubusercontent.com/16293749/46642259-d3de6a80-cb93-11e8-81dd-9b1b00802347.png)

2. savefrom.net let us to download itag=22 (They do not convert )
![image](https://user-images.githubusercontent.com/16293749/46642303-228c0480-cb94-11e8-97b7-f63901713fca.png)

3. savefrom.net provided url
https://r3---sn-8qj-i5ozz.googlevideo.com/videoplayback?source=youtube&mt=1539046187&mv=u&pcm2cms=yes&fvip=3&ms=au%2Crdu&ip=123.30.210.215&lmt=1537538088592722&dur=190.333&itag=22&pl=24&ratebypass=yes&mime=video%2Fmp4&c=WEB&mm=31%2C29&mn=sn-8qj-i5ozz%2Csn-8qj-i5oed&ipbits=0&ei=jf-7W7Bej97hArWajvgL&id=o-AIazzD6oREr6h_LrjRxKK-VUfP47gpSo80hK0qAENNa6&key=yt6&txp=4531332&sparams=dur%2Cei%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&requiressl=yes&expire=1539068909&signature=35ED9CB6D3BB39548BE01800C0D50200B6137600.35AEF34B8BDC5A67A554A2772D2E946BDCF5E91F&video_id=XCQK6LmhYqc&title=Rita+Ora+-+Let+You+Love+Me+%5BOfficial+Video%5D

**&itag=22&pl=24**

Q1. My quetion is 'how savefrom.net does it?'

Q2. Can youtube-dl get itag=22 for this video?

Q3. Where is the code segment does that magic?

<sorry fo bad language>

**Comment by Kumuduweerasinghe** [comment]
Someone, please answer this question? how to do this?

**Comment by dstftw** [comment]
1. Ask them how they do this.
2. 22 is not listed by youtube for this video.
3. See youtube extractor.

**Comment by Vangelis66** [comment]
I wrote: 

> Perhaps itag=22 is still there on yt's CDNs, but no longer advertised to browsers/apps, 
> so it might be that SF.net is force-requesting it?

... FWIW, as of around yesterday, Nov 13th 2018, even the latest version (7.94.2) of the SF.net userscript is **UNABLE** to detect the standalone 720p MP4 encode (`itag=22`) on VEVO music clips (like the [one](https://www.youtube.com/watch?v=Sc97AUImI04) in my previous comment); it defaults to detecting the standalone 360p MP4 one (`itag=18`)  :angry: ... 

Either Youtube have managed to beat SF.net in their game, or they genuinely removed the `itag=22` encodes from their servers (?); I lean on believing the first scenario, i.e. they simply successfully blocked every access to them 😞 ... Oh well, it was good for the whole month it lasted....
