### ISSUE TITLE
error message:  Make sure you are using the latest version; but youtube-dl version is 2018.10.05

### ISSUE THREAD

**Issue by a62527776a** [rg3/youtube-dl#17858]
![tim 20181011125505](https://user-images.githubusercontent.com/13726832/46781593-ec49b300-cd54-11e8-88b4-c6b656836b22.png)

linux
Ubuntu 14.04

windows is work

**Comment by remitamine** [comment]
>  Be sure to call youtube-dl with the --verbose flag and include its complete output.
