### ISSUE TITLE
ARD Mediathek: No video found

### ISSUE THREAD

**Issue by scaidermern** [rg3/youtube-dl#17854]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v "http://www.daserste.de/unterhaltung/serie/babylon-berlin/videos-folgen-verpasst/Babylon_Berlin_1-folge-100.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.daserste.de/unterhaltung/serie/babylon-berlin/videos-folgen-verpasst/Babylon_Berlin_1-folge-100.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-1-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: avconv 4.0.2-2, avprobe 4.0.2-2, ffmpeg 4.0.2-2, ffprobe 4.0.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] Babylon_Berlin_1-folge-100: Requesting header
[redirect] Following redirect to https://www.daserste.de/unterhaltung/serie/babylon-berlin/videos-folgen-verpasst/Babylon_Berlin_1-folge-100.html
[generic] Babylon_Berlin_1-folge-100: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Babylon_Berlin_1-folge-100: Downloading webpage
[generic] Babylon_Berlin_1-folge-100: Extracting information
[download] Downloading playlist: Folge 1 | Babylon Berlin
[generic] playlist Folge 1 | Babylon Berlin: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://www.daserste.de/mediasrc/static/null.html'


ERROR: Did not get any data blocks
```

```
youtube-dl -F "http://www.daserste.de/unterhaltung/serie/babylon-berlin/videos-folgen-verpasst/Babylon_Berlin_1-folge-100.html"
[generic] Babylon_Berlin_1-folge-100: Requesting header
[redirect] Following redirect to https://www.daserste.de/unterhaltung/serie/babylon-berlin/videos-folgen-verpasst/Babylon_Berlin_1-folge-100.html
[generic] Babylon_Berlin_1-folge-100: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Babylon_Berlin_1-folge-100: Downloading webpage
[generic] Babylon_Berlin_1-folge-100: Extracting information
[download] Downloading playlist: Folge 1 | Babylon Berlin
[generic] playlist Folge 1 | Babylon Berlin: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[info] Available formats for Babylon_Berlin_1-folge-100:
format code  extension  resolution note
0            html       unknown    
[download] Finished downloading playlist: Folge 1 | Babylon Berlin
```

---

### Description of your *issue*, suggested solution and other information

ARD Mediathek is listed as a supported site, however no video is found at the URL http://www.daserste.de/unterhaltung/serie/babylon-berlin/videos-folgen-verpasst/Babylon_Berlin_1-folge-100.html.

**Comment by ngdio** [comment]
fixed in #17851

**Comment by scaidermern** [comment]
Great! Closing this one as a duplicate of #17851.

**Comment by ngdio** [comment]
You technically wouldn't even have had to close this one because it will stay an issue until the pull request is merged into master. The original issue (#17744) is unrelated to this, I just fixed the issue on the way because I also needed it myself.
