### ISSUE TITLE
youtube-dl does not recognize lynda.com account

### ISSUE THREAD

**Issue by bluekar** [rg3/youtube-dl#17859]
I got this error when trying to download lynda.com premium videos, my account is lynda.com's premium, but the ERROR ask me the linkedin account.  
They are one company, but I don't have linkedin account, anyone can tell me how can I download lynda.com videos with lynda Premium account? Thanks very much, have a nice time everyone^
![youtube-dl](https://user-images.githubusercontent.com/37397518/46818896-e2579c80-cdb4-11e8-9615-902134523bff.png)

**Comment by dstftw** [comment]
No such option `-subs`.
