### ISSUE TITLE
youtube-dl is able to download paid Bandcamp tracks

### ISSUE THREAD

**Issue by 894-572** [rg3/youtube-dl#17866]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

youtube-dl can download paid tracks from Bandcamp, may not be possible with all albums. For instance `youtube-dl -f flac https://noisecorewalze.bandcamp.com/album/szklarska-poreba` downloads the entire album in FLAC.

**Comment by matkoniecz** [comment]
> youtube-dl can download paid tracks from Bandcamp

Is youtube-dl supposed to be unable to do this? It sounds like a problem on Bandcamp side if that content is supposed to be available only to logged in users.
