### ISSUE TITLE
Error 403: Forbidden (caused by HTTPError())

### ISSUE THREAD

**Issue by nara20** [rg3/youtube-dl#17869]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

youtube-dl.exe "https://cdn.recordingassets.logmeininc.com/4471936274281314309/6866128341321693189/323480013258908683/3744747882244018951/e010a8910ff14aa389500ec217a648f6/18ac70bde7de43e080c309d91450e66e.mp4?Expires=1539459660^&Signature=dONvUIAe7vEk7dIufSX8Kf8YdGFtaRDFHhnazLJ8NtqBGcmJkAWaBHahQP834isrDWXObCv4rdeC3HozWm2GYU1PVZAiPBHegR7w53hkq9Y9l1K6ikBDEkwEKfm6uAwZ5R6I-PVOa2i3wuehvz3HhsBiko9rbGJD0iA4I6-DwsHDGqnP3danxdPsC0rCb2cZOhSqHA6EuC1rivH4QdkZ5O4v1siatJX0EmWeAGhSHyKdgUl~oLC6GmAxm08w0FrzIgn2RSI8d3oVWYxEsVgA-xfJnpVZvtNmplRAZvUPXR9dKrlmcUZ4fiYrVpO72oFYOGsw2uJzj5WNjnROcY42lg__^&Key-Pair-Id=APKAI2Z3PWL3BWDDZ5IA" -v >log.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://cdn.recordingassets.logmeininc.com/4471936274281314309/6866128341321693189/323480013258908683/3744747882244018951/e010a8910ff14aa389500ec217a648f6/18ac70bde7de43e080c309d91450e66e.mp4?Expires=1539459660^&Signature=dONvUIAe7vEk7dIufSX8Kf8YdGFtaRDFHhnazLJ8NtqBGcmJkAWaBHahQP834isrDWXObCv4rdeC3HozWm2GYU1PVZAiPBHegR7w53hkq9Y9l1K6ikBDEkwEKfm6uAwZ5R6I-PVOa2i3wuehvz3HhsBiko9rbGJD0iA4I6-DwsHDGqnP3danxdPsC0rCb2cZOhSqHA6EuC1rivH4QdkZ5O4v1siatJX0EmWeAGhSHyKdgUl~oLC6GmAxm08w0FrzIgn2RSI8d3oVWYxEsVgA-xfJnpVZvtNmplRAZvUPXR9dKrlmcUZ4fiYrVpO72oFYOGsw2uJzj5WNjnROcY42lg__^&Key-Pair-Id=APKAI2Z3PWL3BWDDZ5IA', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91206-g9827bb88e7
[debug] Proxy map: {}
WARNING: Could not send HEAD request to https://cdn.recordingassets.logmeininc.com/4471936274281314309/6866128341321693189/323480013258908683/3744747882244018951/e010a8910ff14aa389500ec217a648f6/18ac70bde7de43e080c309d91450e66e.mp4?Expires=1539459660^&Signature=dONvUIAe7vEk7dIufSX8Kf8YdGFtaRDFHhnazLJ8NtqBGcmJkAWaBHahQP834isrDWXObCv4rdeC3HozWm2GYU1PVZAiPBHegR7w53hkq9Y9l1K6ikBDEkwEKfm6uAwZ5R6I-PVOa2i3wuehvz3HhsBiko9rbGJD0iA4I6-DwsHDGqnP3danxdPsC0rCb2cZOhSqHA6EuC1rivH4QdkZ5O4v1siatJX0EmWeAGhSHyKdgUl~oLC6GmAxm08w0FrzIgn2RSI8d3oVWYxEsVgA-xfJnpVZvtNmplRAZvUPXR9dKrlmcUZ4fiYrVpO72oFYOGsw2uJzj5WNjnROcY42lg__^&Key-Pair-Id=APKAI2Z3PWL3BWDDZ5IA: HTTP Error 403: Forbidden
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 604, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dstftw** [comment]
You must use the original URL.

**Comment by nara20** [comment]
Hi,
Here with the original Url : 

 youtube-dl.exe "https://register.gotowebinar.com/recording/recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi%40tata.com" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://register.gotowebinar.com/recording/recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi%40tata.com', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91206-g9827bb88e7
[debug] Proxy map: {}
[generic] recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi@tata: Requesting header
WARNING: Falling back on generic information extractor.
[generic] recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi@tata: Downloading webpage
[generic] recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi@tata: Extracting information
ERROR: Unsupported URL: https://register.gotowebinar.com/recording/recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi%40tata.com
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://register.gotowebinar.com/recording/recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi%40tata.com
Regards
Nara
