### ISSUE TITLE
URLs of deleted videos

### ISSUE THREAD

**Issue by vronizor** [rg3/youtube-dl#17877]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Hi youtube-dl community. I'm in the process of writing a script to download the audio files from my music playlists and keep them updated on my computer with minimal manual work. Thanks to youtube-dl it's taking shape nicely. However, I'm having an issue with deleted videos. I am aware of the `--ignore-errors` and `--no-warnings` commands and use them already to bypass deleted videos and complete the download of playlists. Nevertheless, I would like to be able to retrieve these deleted videos' URL in order to manually look them up and eventually find a replacement video (or at least keep track of them).

When visiting playlists on the YouTube website, the URL of the video is available (see for example https://www.youtube.com/watch?v=JCUPc9zVfyo, a deleted video but still an "active" YouTube page). Thus, would there be a way to extract these URLs nonetheless and "tag them" in a special way (for example with a "ERR" code next to the URL when using the `--download-archive` option, which for now just skips the deleted videos and doesn't write their URLs) in order to manually process them later?

Thanks again to the community for the great work, cheers.

**Comment by dstftw** [comment]
Embed youtube-dl as python module and work with API directly. All this is covered in FAQ.
