### ISSUE TITLE
Add support for 500px

### ISSUE THREAD

**Issue by leonklingele** [rg3/youtube-dl#17878]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please add support to download photos and videos from 500px.com.

**Comment by leonklingele** [comment]
What information are you missing?

**Comment by leonklingele** [comment]
Sorry! Updated.

**Comment by dstftw** [comment]
Are there any videos at all? Photos are out of scope of youtube-dl.

**Comment by leonklingele** [comment]
Yup, 500px also supports video uploads.
Photos would be a nice and very useful addition to this project! Also see https://github.com/rg3/youtube-dl/issues/9337.

**Comment by dstftw** [comment]
Provide example URLs with videos.

**Comment by leonklingele** [comment]
See my updated comment above. Anyway, I was interested in scraping photos only.
What's the issue with downloading photos?

**Comment by rautamiekka** [comment]
https://github.com/RipMeApp/ripme/ supports 500px. Not sure if completely, but judging by the source code you should be able to rip pretty much anything from there.
