### ISSUE TITLE
youtube-dl is up-to-date (2018.10.05)

### ISSUE THREAD

**Issue by samvado** [rg3/youtube-dl#17907]
D:\temp5>youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

D:\temp5>youtube-dl -f 135 https://www.youtube.com/channel/UCqOdHprLVQnHhE8FmIY3Yzg
[youtube:channel] UCqOdHprLVQnHhE8FmIY3Yzg: Downloading channel page
[youtube:channel] UCqOdHprLVQnHhE8FmIY3Yzg: Downloading page #1
[download] Downloading playlist: UCqOdHprLVQnHhE8FmIY3Yzg
[youtube:channel] UCqOdHprLVQnHhE8FmIY3Yzg: Downloading page #1
[youtube:channel] UCqOdHprLVQnHhE8FmIY3Yzg: Downloading page #2
[youtube:channel] UCqOdHprLVQnHhE8FmIY3Yzg: Downloading page #3
[youtube:channel] UCqOdHprLVQnHhE8FmIY3Yzg: Downloading page #4
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by sheddup** [comment]
youtube is down

**Comment by kelvinRosa** [comment]
why some 480p and 360p videos are not working? someone noticed that?

**Comment by Mattwmaster58** [comment]
@kelvinRosa That's completely unrelated to this issue. Please file a new one.
