### ISSUE TITLE
RESCUE ME from having to keep changing proxy servers to bypass the geo-restriction!

### ISSUE THREAD

**Issue by NiesmialyGosc** [rg3/youtube-dl#17901]
I reported proxy related issues many times in this forum with traces/error logs included but NEVER got a response here & this time I have to try my luck here without including any traces in the hope of seeing someone else that could give me suggestions:

Is there any chance for me to use geo-VPNs directly in youtube-dl commands, instead of having to search for a new proxy each and every time? I'm really tired of searching for a new valid proxy over and over again & coming up with a new IP to add after the "--proxy" parameter in my command lines, especially since I have to constantly download extremely long geo-restricted TV series with 1000+ episodes.

Below is a browser plugin VPN named "SetupVPN" & it rescues me from having to search for a new proxy each and every time (via sites like http://spys.one/free-proxy-list/FR)
https://chrome.google.com/webstore/detail/setupvpn-lifetime-free-vp/oofgbpoabipfcfjapgnbbjjaenockbdp , **but I've no idea of how to "incorporate" it with my youtube-dl downloader??**

I'm just wondering if we'll someday be able to use commands like:

D:\My Folder>youtube-dl **--use-browser-plugin-geo-vpn SetupVPN** --all-subs --convert-subs srt https://www.france.tv/france-3/les-enquetes-de-vera/747593-le-piege-a-corbeaux.html

INSTEAD OF

D:\My Folder>youtube-dl **--proxy socks5://92.222.252.50:10080** --all-subs --convert-subs srt https://www.france.tv/france-3/les-enquetes-de-vera/747593-le-piege-a-corbeaux.html

so I can liberate myself from having to figure out the next valid & stable geo-proxy, and leave the job to SetupVPN???

Is this possible at all?? Or do I always have to keep on shifting from one proxy to another constantly in order to make sure that proxy is up & running at the time when I need it??

What is worse, sometimes a proxy works well at the very beginning, but stops working in the middle of the download process (btw. I'm not sure if the breakpoint resume technology used in youtube-dl supports lossless download?), and I have to search for a new proxy to continue the download, which is really annoying to me, **especially when it comes to time-limited videos, sometimes wasting time in trying all new proxies with no luck could be fatal**: when I eventually find a valid proxy, the video has expired. It looks like only by incorporating the browser plugin geo-VPN with our youtube-dl command lines can we solve this problem, because such geo-VPNs are much more stable than those free online proxies.

That's why I'm desperately looking forward to the addition of features like "**--use-browser-plugin-geo-vpn SetupVPN**" in youtube-dl command lines..!!!

**Comment by dstftw** [comment]
You can't use browser VPN plugins outside browser.
