### ISSUE TITLE
youtube-dl's URL SOMETIMES returns 404 error when downloaded with FFmpeg

### ISSUE THREAD

**Issue by JakubKoralewski** [rg3/youtube-dl#17903]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [`x`] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [`x`] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [`x`] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [`x`] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [`x`] Question

Youtube-dl works OK. What I'm doing is using the URL provided by youtube-dl. It is fed to ffmpeg which spits out an error. I wouldn't have posted this here, but I don't know where else. 

### Here's my workflow:
1. I get a url from youtube-dl.
`with ydl:`
    `info_dict = ydl.extract_info(youtubevideo, download=False)`
    `url= info_dict.get('url')`
    `duration = info_dict.get('duration')`
2. I parse it to ffmpy.
3. Works most of the time (but my application of youtube-dl requires complete stability :/).
4. When it doesn't:
`[https @ 000001f5c1f3cc40] HTTP error 404 Not Found
VERY_LONG_VIDEO_URL: Server returned 404 Not Found`
`ffmpy.FFRuntimeError: `ffmpeg -y -i VERY_LONG_VIDEO_URL -ss 7.26 -vframes 1 -q:v 2 x.jpg` exited with status 1`

The 404 error happens only for some videos and I wasn't able to pinpoint the exact variable resulting in the error. At first I thought it was some sort of an IP-based limit system, but the error is thrown even after long breaks. I've checked; the issue happens with multiple different files. I've tried just getting the url again, using proxies to get the url again and try again. It's very frustrating and sneaky since it happens very rarely.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser

**Comment by dstftw** [comment]
Also, it won't return direct download URL in cases when no such URL is available.

**Comment by JakubKoralewski** [comment]
Makes sense, but why then would this happen only sometimes, though? I think it's only happening to DASH files.

**Comment by dstftw** [comment]
It may happen for segmented DASH when the format you've selected happens to be segmented DASH.
