### ISSUE TITLE
How to use the netrc file with the generic extractor?

### ISSUE THREAD

**Issue by Natim** [rg3/youtube-dl#17910]
Is machine generic supposed to work?
Should we use the hostname as the machine name for the generic loader?

**Comment by Natim** [comment]
Reading the generic extractor code it seems that this is something not yet supported.

**Comment by dstftw** [comment]
Authentication is technically impossible with generic extractor.

**Comment by Natim** [comment]
One could use a default BasicAuth authentication backend.
