### ISSUE TITLE
Corrupted mp4 file

### ISSUE THREAD

**Issue by duurkak** [rg3/youtube-dl#17919]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**
- [ x] Bug report (encountered problems with youtube-dl)

```
razah:~ razah$ youtube-dl -v https://vimeo.com/118862458
[debug] System config: []
[debug] User config: [u'-o', u'~/Desktop/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://vimeo.com/118862458']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.10 (CPython) - Darwin-18.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[vimeo] 118862458: Downloading webpage
[vimeo] 118862458: Extracting information
[vimeo] 118862458: Downloading webpage
[vimeo] 118862458: Downloading JSON metadata
[vimeo] 118862458: Downloading level3 m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://11-lvl3-hls.vimeocdn.com/1539897371-e0211f938a3e534c4152ad9c3f80f1e4d32afdce/01/3772/4/118862458/333633494.mp4.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3
[download] Destination: /Users/razah/Desktop/Blooming 2D cellular automata using expiry_death.mp4
[download] 100% of 4.76MiB in 00:07
[debug] ffmpeg command line: ffprobe -show_streams 'file:/Users/razah/Desktop/Blooming 2D cellular automata using expiry_death.mp4'
```

### Description
MacOs Mojave 10.14 (18A391)
QuickTime Player 10.5 (928.50)
After Effects CC 2018

the video I downloaded with this command does not open.

youtube-dl  https://vimeo.com/118862458

<img width="449" alt="ekran resmi 2018-10-18 23 05 19" src="https://user-images.githubusercontent.com/36481442/47181666-4ede1880-d32c-11e8-803c-2f1ab4d6c528.png">

<img width="529" alt="ekran resmi 2018-10-18 23 06 15" src="https://user-images.githubusercontent.com/36481442/47181687-5e5d6180-d32c-11e8-91f7-0b708b21dc79.png">

**Comment by rautamiekka** [comment]
Try VLC, the newest version. Open up the app, open the message window and set it to debug mode, then drag-drop the file to the window and run it.

**Comment by duurkak** [comment]
> Try VLC, the newest version. Open up the app, open the message window from the 'Tools' menu and set it to debug mode, then drag-drop the file to the window and run it.
@rautamiekka

No problem when I download it from https://www.vimeo-download.com. I can also play with [IINA](https://github.com/lhc70000/iina) player. No need to download VLC.

**Comment by dstftw** [comment]
QuickTime issue.

**Comment by dstftw** [comment]
Most likely all of them use the same backend. As already mentioned, vlc, mpv and many more play it without any issue. Also aforementioned site serves different format with lower quality.
