### ISSUE TITLE
Playlist is not downloding 

### ISSUE THREAD

**Issue by shyamm90** [rg3/youtube-dl#17914]
"  'list' is not recognized as an internal or external command " Occured error while download playlist fro youtube.

E:\Study\Linq>youtube-dl --yes-playlist https://www.youtube.com/watch?v=0pcM6teVdKk&list=PL6n9fhu94yhW7yoUOGNOfHurUE6bpOO2b
[youtube] 0pcM6teVdKk: Downloading webpage
[youtube] 0pcM6teVdKk: Downloading video info webpage
[download] What is ASP NET Web API-0pcM6teVdKk.mp4 has already been downloaded
[download] 100% of 12.31MiB
 **'list' is not recognized as an internal or external command,**
operable program or batch file.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/blob/master/README.md#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
