### ISSUE TITLE
how to fetch download url via proxy, then download files without proxy?

### ISSUE THREAD

**Issue by retsyo** [rg3/youtube-dl#17922]
As the title says, I can't visit some video site directly, but if I visit it via proxy in firefox, then I can get the video file's url via `Video DownloadHelper` addon. Then the video file's url can be used by download application( for example, `Internet Download Manager`) without proxy

My proxy is not so fast and has bandwidth limitation, so my question is can we fetch download url via proxy, then download files without proxy?

thanks

**Comment by dstftw** [comment]
By using `--geo-verification-proxy`. Of course particular extractor must support this.
