### ISSUE TITLE
The download link for windows in the readme file is not working

### ISSUE THREAD

**Issue by hamedelhadi** [rg3/youtube-dl#17926]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ x] Other

### Description of your *issue*, suggested solution and other information

under the INSTALATION instructions, the download link for windows in the readme file is not working
the link is https://yt-dl.org/latest/youtube-dl.exe

in this line Windows users can download an .exe file and place it in any location on their PATH except for %SYSTEMROOT%\System32 (e.g. do not put in C:\Windows\System32).

**Comment by dstftw** [comment]
Obviously network issue on your side.
