### ISSUE TITLE
[ProsiebenMaxx] ERROR: This video is DRM protected

### ISSUE THREAD

**Issue by SonGokuSSJ** [rg3/youtube-dl#17928]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.prosiebenmaxx.de/anime/detektiv-c
onan/videos/episode-one-der-geschrumpfte-meisterdetektiv-ganze-folge']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[prosiebensat1] anime/detektiv-conan/videos/episode-one-der-geschrumpfte-meister
detektiv-ganze-folge: Downloading webpage
[prosiebensat1] 5680850: Downloading videos JSON
ERROR: This video is DRM protected.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\bu
ild\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\bu
ild\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\bu
ild\youtube_dl\extractor\prosiebensat1.py", line 450, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\bu
ild\youtube_dl\extractor\prosiebensat1.py", line 399, in _extract_clip
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\bu
ild\youtube_dl\extractor\prosiebensat1.py", line 32, in _extract_video_info
youtube_dl.utils.ExtractorError: This video is DRM protected.


...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.prosiebenmaxx.de/anime/detektiv-conan/videos/11334-folge-334-der-stumm-zurueckgelassene-beweis-3-ganze-folge
- Single video: https://www.prosiebenmaxx.de/anime/detektiv-conan/videos/11336-folge-336-der-stumm-zurueckgelassene-beweis-5-ganze-folge
- Single video: https://www.prosiebenmaxx.de/anime/detektiv-conan/videos/episode-one-der-geschrumpfte-meisterdetektiv-ganze-folge

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

For the new Detektiv Conan Episodes and the above mentioned Detektiv Conan Movie I get the "ERROR: This video is DRM protected". I am not sure if you can fix this, so that is the reason I am opening this issue. Other Episodes (I.e. Dragon Ball Super Episode 22) from prosiebenmaxx was downloaded without problems the same day I tried to download the Detektiv Conan Episodes and movie (yesterday).

**Comment by bam2000** [comment]
Yes, I have the same error when I try to download the new Detective Conan episodes.

Please find a way to let us Download from Pro7 maxx :)

**Comment by klb1953** [comment]
I have this issue too.  Verbose output below.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.9now.com.au/manifest/season-1/episode-1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.10 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[debug] Using fake IP 1.157.88.247 (AU) as X-Forwarded-For.
[9now.com.au] episode-1: Downloading webpage
ERROR: This video is DRM protected.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ninenow.py", line 66, in _real_extract
    raise ExtractorError('This video is DRM protected.', expected=True)
ExtractorError: This video is DRM protected.

**Comment by Wilma456** [comment]
I think there's nothing we can do. Other Downloaders like Video DownloadHelper can Download a Part of the Video, but it can't be played. 

I personally use the Website onlinetvrecorder.com to record the new Episodes. The Quality is not Perfect, but it is better than nothing.

**Comment by Linus789** [comment]
afaik it's not possible to bypass drm stream protections and every request here for drm support was rejected.

**Comment by SonGokuSSJ** [comment]
Thank you for the answer. Yes, if it is a copy protection, I do not want them to bypass it, if it is illegal. 

Instead of onlinetvrecorder I am using youtv.com. It is better in my opinion.
