### ISSUE TITLE
Incorrect Format‒Resolution Listing

### ISSUE THREAD

**Issue by SwimmingLink** [rg3/youtube-dl#17948]
---

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting this *issue* I have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### The purpose of my *issue* is:
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

The full verbose output is as follows:

```
youtube-dl -v cRyH9VtoBEs -F
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'cRyH9VtoBEs', '-F']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[youtube] cRyH9VtoBEs: Downloading webpage
[youtube] cRyH9VtoBEs: Downloading video info webpage
[info] Available formats for cRyH9VtoBEs:
format code  extension  resolution note
249          webm       audio only DASH audio   69k , opus @ 50k, 1.34MiB
250          webm       audio only DASH audio   88k , opus @ 70k, 1.70MiB
171          webm       audio only DASH audio  105k , vorbis@128k, 2.01MiB
140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.4
0.2@128k, 2.58MiB
251          webm       audio only DASH audio  170k , opus @160k, 3.23MiB
278          webm       216x144    144p   84k , webm container, vp9, 30fps, vide
o only, 1.54MiB
160          mp4        216x144    144p  110k , avc1.4d400c, 15fps, video only,
2.18MiB
242          webm       360x240    240p  193k , vp9, 30fps, video only, 3.06MiB
133          mp4        360x240    240p  251k , avc1.4d400d, 30fps, video only,
4.91MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 1.62MiB
36           3gp        320x214    small , mp4v.20.3, mp4a.40.2, 4.58MiB
18           mp4        360x240    small , avc1.42001E, mp4a.40.2@ 96k, 6.98MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 8.63MiB (best)
...
<end of log>
```

---

### Description of my *issue* and other information

Not sure if this is an issue of youtube(-dl) reporting the wrong resolution, of youtube listing the wrong file under the wrong format code, of youtube-dl failing to download properly, or something else. The listed format code 43 reports a resolution of 640x360, yet that video only downloads as a 360x240. This is the first/only video that I've noticed so far with this issue.

**Comment by dstftw** [comment]
This is what youtube reports.
