### ISSUE TITLE
Embedded youtube-dl, DateRange for BBC iPlayer 

### ISSUE THREAD

**Issue by Qwerty-Space** [rg3/youtube-dl#17942]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Git HEAD: 7190216
[debug] Python version 3.7.0 (CPython) - Linux-4.4.0-17134-Microsoft-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] b0bp1brh: Downloading video page
[bbc.co.uk] b0bp1brh: Downloading playlist JSON
[bbc.co.uk] b0bpvw9q: Downloading media selection XML
[bbc.co.uk] b0bpvw9q: Downloading m3u8 information
[bbc.co.uk] b0bpvw9q: Downloading m3u8 information
[bbc.co.uk] b0bpvw9q: Downloading MPD manifest
[bbc.co.uk] b0bpvw9q: Downloading MPD manifest
[bbc.co.uk] b0bpvw9q: Downloading m3u8 information
[bbc.co.uk] b0bpvw9q: Downloading m3u8 information
[bbc.co.uk] b0bpvw9q: Downloading m3u8 information
[bbc.co.uk] b0bpvw9q: Downloading m3u8 information
[bbc.co.uk] b0bpvw9q: Downloading m3u8 information
[bbc.co.uk] b0bpvw9q: Downloading m3u8 information
[bbc.co.uk] b0bpvw9q: Downloading MPD manifest
[bbc.co.uk] b0bpvw9q: Downloading MPD manifest
[bbc.co.uk] b0bpvw9q: Downloading m3u8 information
[bbc.co.uk] b0bpvw9q: Downloading m3u8 information
[bbc.co.uk] b0bpvw9q: Downloading m3u8 information
[bbc.co.uk] b0bpvw9q: Downloading m3u8 information
[debug] Invoking downloader on 'https://bbcfmt-ic-6d96a700-109027-vodhlsuklive.s.loris.llnwd.net/usp/auth/vod/piff_abr_full_hd/c6ab17-b0bpvw9q/vf_b0bpvw9q_a39f5f40-a25f-4d7f-9fa3-fa81faaab809.ism/vf_b0bpvw9q_a39f5f40-a25f-4d7f-9fa3-fa81faaab809-audio_eng=320000-video=5070000.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 382
[download] Destination: Doctor Who, Series 11, The Ghost Monument-b0bpvw9q.mp4
[download]   2.1% of ~1.80GiB at  2.17MiB/s ETA 00:59
```

---

### Description of your *issue*, suggested solution and other information

I'm trying to download a video that was uploaded on the day of running the command, however it seems to just download the video regardless of the date.  I'm trying to download the latest Doctor Who episode from BBC iPlayer.

Code:
```
current_date = datetime.date.today().isoformat().replace("-", "")

ydl_opts = {
    "format": "best",
    "daterange": current_date,
    "verbose": "true"
}

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([f"{latest_ep_link}"])
```

**Comment by dstftw** [comment]
1. `daterange` must be `DateRange` object.
2. `BBCCoUk` does not provide upload date info.

**Comment by Qwerty-Space** [comment]
It provides "first shown" date info.
I guess I could use BeautifulSoup to get that.
