### ISSUE TITLE
Cannot download videos from https://tvthek.orf.at/ any more

### ISSUE THREAD

**Issue by websurfer83** [rg3/youtube-dl#17956]
Hello,
since today I cannot download videos from https://tvthek.orf.at/ any more. It seems that ORF changed the delivery of its videos. The normal mp4-file as http-download is gone (it is not present in the source code any more) and the other formats are not downloadable, too (hds and hls).

I tried different videos, but all the same:
https://tvthek.orf.at/profile/Universum/35429/Universum-Oesterreich-Die-Kraft-des-Wassers-1/13992978
https://tvthek.orf.at/profile/Universum-History/6000179/Universum-History-Unser-Oesterreich-Das-Burgenland-Ein-Grenzfall/13992981

Can someone please look at the site and try to get it downloadable?

Thanks and kind regards
websurfer83.

**Comment by hurtigerhans** [comment]
same problem 
```
youtube-dl -v https://tvthek.orf.at/profile/Universum/35429/Universum-Oesterreich-Die-Kraft-des-Wassers-1/13992978
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://tvthek.orf.at/profile/Universum/35429/Universum-Oesterreich-Die-Kraft-des-Wassers-1/13992978']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-138-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.15-0ubuntu0.16.04.1, avprobe 2.8.15-0ubuntu0.16.04.1, ffmpeg 2.8.15-0ubuntu0.16.04.1, ffprobe 2.8.15-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[orf:tvthek] 13992978: Downloading webpage
[orf:tvthek] 14384527: Checking hls-QXB-Adaptiv video format URL
[orf:tvthek] 14384527: Checking hds-Q1A-Niedrig video format URL
[orf:tvthek] 14384527: Checking hds-Q4A-Mittel video format URL
[orf:tvthek] 14384527: Checking hds-Q6A-Hoch video format URL
[orf:tvthek] 14384527: Checking hds-Q8C-Sehr hoch video format URL
[orf:tvthek] 14384527: Checking hls-Q1A-Niedrig video format URL
[orf:tvthek] 14384527: Checking hls-Q4A-Mittel video format URL
[orf:tvthek] 14384527: Checking hls-Q6A-Hoch video format URL
[orf:tvthek] 14384527: Checking hls-Q8C-Sehr hoch video format URL
[download] Downloading playlist: 13992978
[orf:tvthek] playlist 13992978: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://apasfiis.sf.apa.at/f4m/cms-worldwide/2018-10-23_2015_sd_02_Universum--Oest_____13992978__o__1830778700__s14384527_7__ORF2HD_20153121P_21005909P_Q8C.mp4/manifest.f4m'
[download] Destination: Universum - Österreich - Die Kraft des Wassers (1)-14384527.f4m
[download] 100% of 6.73KiB in 00:00
[download] Finished downloading playlist: 13992978
```
browser dev tools show downloading segments of the video
```
https://varorfvod.sf.apa.at/cms-worldwide_nas/_definst_/nas/cms-worldwide/online/2018-10-23_2015_sd_02_Universum--Oest_____13992978__o__1830778700__s14384527_7__ORF2HD_20153121P_21005909P_Q8C.mp4/media_0.ts?lbs=20181024091746857&ip=<changed>&ua=Mozilla%252f5.0%2b(X11%253b%2bUbuntu%253b%2bLinux%2bx86_64%253b%2brv%253a62.0)%2bGecko%252f20100101%2bFirefox%252f62.0
https://varorfvod.sf.apa.at/cms-worldwide_nas/_definst_/nas/cms-worldwide/online/2018-10-23_2015_sd_02_Universum--Oest_____13992978__o__1830778700__s14384527_7__ORF2HD_20153121P_21005909P_Q8C.mp4/media_1.ts?lbs=20181024091746857&ip=<changed>&ua=Mozilla%252f5.0%2b(X11%253b%2bUbuntu%253b%2bLinux%2bx86_64%253b%2brv%253a62.0)%2bGecko%252f20100101%2bFirefox%252f62.0
...
```

**Comment by oschec64** [comment]
same problem - only a small .f4m file is downloaded

**Comment by Vangelis66** [comment]
> browser dev tools show downloading segments of the video
```
https://varorfvod.sf.apa.at/cms-worldwide_nas/_definst_/nas/cms-worldwide/online/2018-10-23_2015_sd_02_Universum--Oest_____13992978__o__1830778700__s14384527_7__ORF2HD_20153121P_21005909P_Q8C.mp4/media_0.ts?lbs=20181024091746857&ip=<changed>&ua=Mozilla%252f5.0%2b(X11%253b%2bUbuntu%253b%2bLinux%2bx86_64%253b%2brv%253a62.0)%2bGecko%252f20100101%2bFirefox%252f62.0
https://varorfvod.sf.apa.at/cms-worldwide_nas/_definst_/nas/cms-worldwide/online/2018-10-23_2015_sd_02_Universum--Oest_____13992978__o__1830778700__s14384527_7__ORF2HD_20153121P_21005909P_Q8C.mp4/media_1.ts?lbs=20181024091746857&ip=<changed>&ua=Mozilla%252f5.0%2b(X11%253b%2bUbuntu%253b%2bLinux%2bx86_64%253b%2brv%253a62.0)%2bGecko%252f20100101%2bFirefox%252f62.0
...
```
**media_0.ts** and **media_1.ts** means the stream you're viewing in your browser is of the AppleHLS type... 
Here's a how-to for, e.g, `https://tvthek.orf.at/profile/Universum/35429/Universum-Oesterreich-Die-Kraft-des-Wassers-1/13992978`
I'm not inside Austria, so receiving the _international_ version of the stream 😉 
Using **Pale Moon** (unstable) 28.2.0a1 as my browser and its **Web Console** for URL sniffin...

1. Load the page in your browser; once the video starts playing, make sure to change the quality of the embedded player to `Sehr hoch`, then pause video.
2. In that same tab, open (CTRL+SHIFT+K) Web Console, filter for `playlist.m3u8` and reload the page.
3. In the filter results, you should get the URI of the 720p HLS playlist: 

`https://apasfiis.sf.apa.at/ipad/cms-worldwide/2018-10-23_2015_sd_02_Universum--Oest_____13992978__o__1830778700__s14384527_7__ORF2HD_20153121P_21005909P_Q8C.mp4/playlist.m3u8`

4. If you filter for `vtt`, you'll get the URI of the German subs in web vtt format: 

`https://api-tvthek.orf.at/uploads/media/subtitles/0054/82/491fab44814df2db45f48507c1b4e46286582509.vtt`

The playlist can be downloaded with yt-dl to get the whole video: 

`youtube-dl  --console-title --hls-prefer-native  -c --no-part "https://apasfiis.sf.apa.at/ipad/cms-worldwide/2018-10-23_2015_sd_02_Universum--Oest_____13992978__o__1830778700__s14384527_7__ORF2HD_20153121P_21005909P_Q8C.mp4/playlist.m3u8" -o "Universum - Österreich - Die Kraft des Wassers (1).mp4"`

while the subs can be converted to .srt with ffmpeg: 

`ffmpeg -i "https://api-tvthek.orf.at/uploads/media/subtitles/0054/82/491fab44814df2db45f48507c1b4e46286582509.vtt" "Universum - Österreich - Die Kraft des Wassers (1).srt"`

**Comment by oschec64** [comment]
Thank you!

Am Do., 25. Okt. 2018 um 05:02 Uhr schrieb Vangelis66 <
notifications@github.com>:

**Comment by websurfer83** [comment]
@Vangelis66:
Thank you very much! This is working fine now!
To get the URI of the video there is an easier way:
`youtube-dl "https://tvthek.orf.at/profile/Universum/35429/Universum-Oesterreich-Die-Kraft-des-Wassers-1/13992978" -f hls-Q8C-Sehr_hoch -g`

But now I have got some more problems with ORF videos which are divided in some chapters. For example this video:
[https://tvthek.orf.at/profile/Suedtirol-heute/1277675/Suedtirol-Heute/13993100](url)

When I type 
`youtube-dl "https://tvthek.orf.at/profile/Suedtirol-heute/1277675/Suedtirol-Heute/13993100" -f hls-Q8C-Sehr_hoch -g`
youtube-dl shows me the URIs:
`https://apasfiis.sf.apa.at/ipad/cms-worldwide/2018-10-24_1830_tl_28_SUEDTIROL-HEUTE_Signation---Hea__13993100__o__2130913935__s14385433_3__BLTHD_18300715P_18304517P_Q8C.mp4/playlist.m3u8
https://apasfiis.sf.apa.at/ipad/cms-worldwide/2018-10-24_1830_tl_28_SUEDTIROL-HEUTE_Immer-mehr-obda__13993100__o__1668484525__s14385434_4__BLTHD_18304517P_18341917P_Q8C.mp4/playlist.m3u8
https://apasfiis.sf.apa.at/ipad/cms-worldwide/2018-10-24_1830_tl_28_SUEDTIROL-HEUTE_Aktuelle-Meldun__13993100__o__1723848746__s14385435_5__BLTHD_18341917P_18352822P_Q8C.mp4/playlist.m3u8
https://apasfiis.sf.apa.at/ipad/cms-worldwide/2018-10-24_1830_tl_28_SUEDTIROL-HEUTE_Am-Anfang-war-d__13993100__o__4620301965__s14385436_6__BLTHD_18352822P_18385622P_Q8C.mp4/playlist.m3u8
https://apasfiis.sf.apa.at/ipad/cms-worldwide/2018-10-24_1830_tl_28_SUEDTIROL-HEUTE_Mumifizierte-Le__13993100__o__6757917625__s14385437_7__BLTHD_18385622P_18394201P_Q8C.mp4/playlist.m3u8
https://apasfiis.sf.apa.at/ipad/cms-worldwide/2018-10-24_1830_tl_28_SUEDTIROL-HEUTE_Fuer-die-ganzja__13993100__o__1120454295__s14385438_8__BLTHD_18394201P_18425711P_Q8C.mp4/playlist.m3u8
https://apasfiis.sf.apa.at/ipad/cms-worldwide/2018-10-24_1830_tl_28_SUEDTIROL-HEUTE_Verabschiedung__13993100__o__1836772614__s14385439_9__BLTHD_18425711P_18431419P_Q8C.mp4/playlist.m3u8`

Now I can put each URI in a single command or in a batch file, but this is not very efficient.

If I type 
`youtube-dl "https://tvthek.orf.at/profile/Suedtirol-heute/1277675/Suedtirol-Heute/13993100" -f hls-Q8C-Sehr_hoch -g > Download.txt`
the URIs are in the file "Download.txt".

After downloading each chapter I am using ffmpeg to make one complete MP4 file with all the chapters.

Is there a way to do this more efficient? Can youtube-dl download all the chapters and run ffmpeg to make just on single file of them?

Thanks and kind regards
websurfer83.

**Comment by annomatik** [comment]
Also an upvote from me to have a fix for tvthek, apparently, ORF changed something yesterday or the day before that.

Workaround for now:
1) Go to the page of the show, e.g. https://tvthek.orf.at/profile/Schlawiner/13889520
2) Select the desired quality in the player, e.g. "Sehr hoch" for 720p (tvthek remembers this setting via cookie).
3) Go to the developer console of your browser (F12) and start playing the video, filter for "playlist" or "m3u8".
4) Download the m3u8 file with youtube-dl, this will result in a mp4 file which you still need to rename, e.g. https://apasfiis.sf.apa.at/ipad/cms-austria/2018-10-19_2225_sd_01_Schlawiner--Nur_____13992610__o__2131517456__s14382575_5__ORF1HD_22272010P_22553704P_Q8C.mp4/playlist.m3u8

By the way, the "m3u8" trick works for a lot of pages.

For the multi-part files, e.g. Willkommen Österreich, this is a lot of work, but it's better than nothing I guess :-)

**Comment by annomatik** [comment]
> Is there a way to do this more efficient? Can youtube-dl download all the chapters and run ffmpeg to make just on single file of them?
> 
> Thanks and kind regards
> websurfer83.

Well... You can at least merge the chapters automatically, e.g. with mkvmerge.

mkvmerge -o willkommen_oesterreich chapter1.mp4 chapter2.mp4 chapter3.mp4 ...

I think, it also supports "one file = one chapter", but I couldn't make it work yet. As a workaround, you can use MKVToolNix GUI, on the output page, it has a setting "Generating chapters: One chapter for each appended file".

**Comment by annomatik** [comment]
Cool, thanks! I think, we need to wait for a fix of youtube-dl. Usually, those fixes come quick, let's see.

**Comment by annomatik** [comment]
With a little bit of shell-script magic, you can do this in one line (if you're running bash or a similar shell):

youtube-dl $(youtube-dl "https://tvthek.orf.at/profile/Schlawiner/13889520" -f hls-Q8C-Sehr_hoch -g)

**Comment by annomatik** [comment]
Luckily, your commando gives multiple links, if there are multiple files to download. I have written a little script to download multi-part videos:

`#!/bin/bash

url="$1"

if [[ "x$url" == "x" ]]; then
        echo syntax: $0 \<tvthek-url\>
        echo e.g. $0 youtube-dl https://tvthek.orf.at/profile/Willkommen-Oesterreich/130954
        exit 1
fi

echo -n counting...

items=$(youtube-dl "$url" -f hls-Q8C-Sehr_hoch -g | wc -l)

echo


  if [[ $items -lt 1 ]]; then

        echo error: did not find anything to download.
        exit 2

elif [[ $items -lt 2 ]]; then

        improv_title=$(echo $url | rev | cut -d\/ -f 2 | rev)

        echo single-part download, downloading to ${improv_title}.mp4
        youtube-dl -o $improv_title $(youtube-dl $url -f hls-Q8C-Sehr_hoch -g)

else


        improv_title=$(echo $url | rev | cut -d\/ -f 2 | rev)
        echo multi-part download, downloading $items parts of ${improv_title}.

        youtube-dl "$url" -f hls-Q8C-Sehr_hoch -g | while read a; do

                chapter_num=$(echo $a | cut -d \_ -f15)
                chapter=$(printf "%02d" $chapter_num)
                chapter_title=$(echo $a | cut -d \_ -f6)
                date=$(echo $a | cut -d \_ -f1 | rev | cut -d \/ -f1 | rev)

                youtube-dl -o "$improv_title $date - $chapter $chapter_title".mp4 $a

        done

fi
`

**Comment by annomatik** [comment]
Cool :-)

So, for me, the only missing link is, to automatically add the season + episode number from thetvdb.com, e.g. download a "Universum - 2018x29 Austria - The Power of Water (1) 720p web-dl-tvthek.mp4", move it into the right directory and tell Kodi to refresh the tv show entry.

https://www.thetvdb.com/series/universe/episodes/6876009

**Comment by annomatik** [comment]
> I also have a little Script which runs via crontab every Wednesday and Saturday morning

So... How do you handle multiple episodes per week? Last week, there was "Atatürk - Vater der modernen Türkei" (Universum History) on Friday and "Unser Österreich - Das Burgenland" (also Universum History) on Tuesday.

**Comment by Oneboy1979** [comment]
In that case i run the script manually! :-)

**Comment by Vangelis66** [comment]
@websurfer83 wrote: 

> To get the URI of the video there is an easier way:
> `youtube-dl "https://tvthek.orf.at/profile/Universum/35429/Universum-Oesterreich-Die-Kraft-des-Wassers-1/13992978" -f hls-Q8C-Sehr_hoch -g`
> 
> But now I have got some more problems with ORF videos which are divided in some chapters. 
> For example this video:
> https://tvthek.orf.at/profile/Suedtirol-heute/1277675/Suedtirol-Heute/13993100
> When I type
> `youtube-dl "https://tvthek.orf.at/profile/Suedtirol-heute/1277675/Suedtirol-Heute/13993100" -f hls-Q8C-Sehr_hoch -g`
> youtube-dl shows me the URIs:
> ```
> (large console output redacted)
> ```
> Now I can put each URI in a single command or in a batch file, but this is not very efficient.
> (snip)
> After downloading each chapter I am using ffmpeg 
> to make one complete MP4 file with all the chapters.
> Is there a way to do this more efficient?
> (snip)
> But for the "multi-chapter-files" it takes too much time. 
> Merging with ffmpeg is no problem, but downloading each chapter 
> from files with sometimes 40 chapters (like "Starnacht") takes too long.
> Is there no way to do it faster?

@annomatik wrote: 

> For the multi-part files, e.g. Willkommen Österreich, this is a lot of work

@websurfer83, you are overly reliant on "_your_" method of obtaining the `playlist.m3u8` URI, that is by using youtube-dl to begin with... While **I do agree this is the preferred way for non-chaptered episodes** of programmes, **"_my_" way via "URL sniffin" works best with chaptered episodes** 😜 

Let's take as an example your previously mentioned episode of **Südtirol Heute**, 
`https://tvthek.orf.at/profile/Suedtirol-heute/1277675/Suedtirol-Heute/13993100`
which consists of 7 chapters.

`youtube-dl -f hls-Q8C-Sehr_hoch "https://tvthek.orf.at/profile/Suedtirol-heute/1277675/Suedtirol-Heute/13993100" -g > "ChapterDLlinks.txt"`
which gets us [ChapterDLlinks.txt](https://github.com/rg3/youtube-dl/files/2516595/ChapterDLlinks.txt)
i.e. seven parts to download consecutively and then concatenate with ffmpeg...

But, URL sniffing via browser reveals _**the URI of the whole episode master playlist**_ to be: 
`https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/13993100_0009_Q8C.mp4/playlist.m3u8`
This will allow for the download of the **whole** episode in one go, no part files to join afterwards: 

`youtube-dl --console-title --hls-prefer-native -c --no-part "https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/13993100_0009_Q8C.mp4/playlist.m3u8" -o "Südtirol Heute - Mi, 24.10.2018.mp4"` => 
```
[generic] playlist: Requesting header
[generic] playlist: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 66
[download] Destination: S?dtirol Heute - Mi, 24.10.2018.mp4
[download]   7.1% of ~309.65MiB at  1.14MiB/s ETA 04:53
```
Of course, all chapter info is absent in the single downloaded file, but I don't think many will care... 
While URL sniffin can't be integrated in automation solutions like shell scripts, you'll agree that for multi-part episodes is more suited to ease of dowloading...

**Comment by annomatik** [comment]
Hmmm... So where exactly is the advantage in this approach? If you add a "mkvmerge" to the end of my script, you get the same result, the same filesize (I guess, it's just the same episode but one mp4 instead of many), and you can make chapters out of it, if you want. You don't have to, but you can.

Also, it's fully automatable -- you don't have to start the browser, you don't have to look into source files, you can just add the script into a crontab -- done, regular downloading. If you want. Again, you don't have to either.

And if youtube-dl works like it did a couple of days ago, you don't even need a script, it just works and automatically downloads all parts of a multi-part episode as well. The scripts posted here are mostly workarounds for something that usually works with youtube-dl without doing anything. Just provide the tv show URL, youtube-dl does the rest.

**Comment by websurfer83** [comment]
@Vangelis66:
Thanks for your answer. You're right that your solution is the best for downloading all the chapters in one single file. So we don't need to run ffmpeg to merge all the chapters into one file.
But let me tell you how it's easier to get the URI: Instead of the developer console you can open the source-code of the website with the video (for example https://tvthek.orf.at/profile/Suedtirol-heute/1277675/Suedtirol-Heute/13993100), and then you just have to use the search function. There you have to enter "episodes" and you will find the URI with "Q8C" with the whole video:
`https:\/\/apasfiis.sf.apa.at\/ipad\/cms-worldwide_episodes\/13993100_0009_Q8C.mp4\/playlist.m3u8`
There you will only have to remove the `\` and you can feed youtube-dl and download the video.

**Comment by Vangelis66** [comment]
@websurfer83:  
You are welcome, thanks for your kind words 😄 and the page-source trick 👍 
The thing is I actually do not download from ORF (I don't speak German!); I just popped in here to offer a helping hand to seemingly frustrated people; it's nice that at least some of them found my contributions of merit... 😜 

There's enough info inside this thread to aid the yt-dl devs towards fully restoring the currently broken `tvthek.orf.at` extractor... The bitter truth is they get inundated with so many issue reports that it's hard to prioritise and fix in a timely fashion, provided a fix is even possible ("no fix" is sadly very common nowadays, with many media sites turning to full-blown DRM solutions 😭 ) ... 

Tschüs
