### ISSUE TITLE
--prefer-free-formats doesn't use webm when selecting bestvideo

### ISSUE THREAD

**Issue by Nobelix** [rg3/youtube-dl#17999]
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

When using `--prefer-free-formats -f bestvideo+bestaudio` it downloads an video mp4 and an audio webm then merges into a mkv. Although it should download a webm video and webm audio and merge it into a webm.

**Comment by dstftw** [comment]
It will only prefer webm when all quality metadata of free and non free formats are identical.

**Comment by Nobelix** [comment]
@dstftw then how can I force it to download the best webm video possible?

**Comment by dstftw** [comment]
Bother to read [FAQ](https://github.com/rg3/youtube-dl#format-selection).
