### ISSUE TITLE
[Crunchyroll] Dangerous ignoring of failure of downloading of m3u8 information

### ISSUE THREAD

**Issue by Arfrever** [rg3/youtube-dl#17998]
I am not sure if problem is specific to Crunchyroll extractor, or more general.
I happened to reproduce this problem:
```
[crunchyroll] 719441: Downloading webpage
[crunchyroll] 719441: Downloading audio-jaJP m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 110] Connection timed out>
[crunchyroll] 719441: Downloading audio-jaJP-hardsub-enUS m3u8 information
[crunchyroll] 719441: Downloading media info
[info] Writing video subtitles to: ${target}.enUS.ass
[download] Destination: ${target}.mp4
ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
...
```
This means that youtube-dl downloaded video file with hardcoded English subtitles (`audio-jaJP-hardsub-enUS` variant) instead of pure video file (`audio-jaJP` variant).

I think that it is better that youtube-dl abort downloading video file if m3u8 information for preferred format fails to be downloaded.

(Variant without hardcoded subtitles is preferred by default since commit 1084563eaab3a039ea8ccb65f2507e919d8e11f0.)

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#format-selection
