### ISSUE TITLE
Hotstar plugin requires update

### ISSUE THREAD

**Issue by SSoft7** [rg3/youtube-dl#18017]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
https://pastebin.com/raw/9ysrxxey
```
---

### Description of your *issue*, suggested solution and other information

I suppose this issue is happening with any video due to some recent changes in hotstar.

Thank you.

**Comment by shizoinakamora** [comment]
Another Problem While Downloading Hotstar video.

https://pastebin.com/6CFM54a3

**Comment by SSoft7** [comment]
@remitamine There are many videos available freely, you can test with any free item from "Movies" page.

Thanks.

**Comment by remitamine** [comment]
> There are many videos available freely, you can test with any free item from "Movies" page.

```
youtube-dl --proxy localhost:8080 https://www.hotstar.com/movies/lockout/1000062487/watch
[hotstar] 1000062487: Downloading webpage
[hotstar] 1000062487: Downloading JSON metadata
[hotstar] 1000062487: Downloading m3u8 information
[download] Destination: Lockout-1000062487.mp4
ffmpeg version n4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20180831
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[tcp @ 0x55c686b7a780] Connection to tcp://localhost:8080 failed (Connection refused), trying next address
[hls,applehttp @ 0x55c686b75640] Opening 'https://staragvod1-vh.akamaihd.net/i/videos/movies/english/1000062487/1000062487_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/crypt.key?null=0&id=AgCLOxGifHzJjbnv2Vv9jI4ImNRtgjpny7nT+4j9pobf7NMLM1kVbbL+P6gcE3+qDMQR7+C3ebMPjg%3d%3d' for reading
[tcp @ 0x55c6871fb2c0] Connection to tcp://localhost:8080 failed (Connection refused), trying next address
[hls,applehttp @ 0x55c686b75640] Opening 'crypto+http://staragvod1-vh.akamaihd.net/i/videos/movies/english/1000062487/1000062487_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/segment1_7_av.ts?null=0&id=AgCLOxGifHzJjbnv2Vv9jI4ImNRtgjpny7nT+4j9pobf7NMLM1kVbbL+P6gcE3+qDMQR7+C3ebMPjg%3d%3d' for reading
[tcp @ 0x55c687260f00] Connection to tcp://localhost:8080 failed (Connection refused), trying next address
[NULL @ 0x55c68724c340] non-existing SPS 0 referenced in buffering period
[NULL @ 0x55c68724c340] SPS unavailable in decode_picture_timing
[h264 @ 0x55c6872610c0] non-existing SPS 0 referenced in buffering period
[h264 @ 0x55c6872610c0] SPS unavailable in decode_picture_timing
Input #0, hls,applehttp, from 'https://staragvod1-vh.akamaihd.net/i/videos/movies/english/1000062487/1000062487_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/index_7_av.m3u8?null=0&id=AgCLOxGifHzJjbnv2Vv9jI4ImNRtgjpny7nT+4j9pobf7NMLM1kVbbL+P6gcE3+qDMQR7+C3ebMPjg%3d%3d':
  Duration: 01:30:44.12, start: 0.100667, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Lockout-1000062487.mp4.part':
  Metadata:
    encoder         : Lavf58.12.100
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   24 fps=0.0 q=-1.0 size=     256kB time=00:00:00.98 bitrate=2137.4kbits
```

**Comment by SSoft7** [comment]
Hmm, I think this issue is for specific videos (maybe newer ones), 
try this 

> ytdl -F https://www.hotstar.com/movies/raid/1000212789

I don't think this is DRM issue, they just changed urls probably.

**Comment by remitamine** [comment]
> Hmm, I think this issue is for specific videos (maybe newer ones),
try this (above one works for me too, but not this one)
```
youtube-dl --proxy localhost:8080 -F https://www.hotstar.com/movies/raid/1000212789/watch
[hotstar] 1000212789: Downloading webpage
[hotstar] 1000212789: Downloading JSON metadata
[hotstar] 1000212789: Downloading m3u8 information
[info] Available formats for 1000212789:
format code  extension  resolution note
hls-82       mp4        250x140      82k , avc1.42c015, 10.0fps, mp4a.40.5
hls-141      mp4        320x180     141k , avc1.42c015, 15.0fps, mp4a.40.5
hls-281      mp4        320x180     281k , avc1.42c015, 25.0fps, mp4a.40.2
hls-505      mp4        416x234     505k , avc1.42c01e, 25.0fps, mp4a.40.2
hls-914      mp4        640x360     914k , avc1.42c01e, 25.0fps, mp4a.40.2
hls-1425     mp4        720x404    1425k , avc1.42c01e, 25.0fps, mp4a.40.2
hls-2140     mp4        1280x720   2140k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-3161     mp4        1600x900   3161k , avc1.4d4028, 25.0fps, mp4a.40.2
hls-4694     mp4        1920x1080  4694k , avc1.4d4028, 25.0fps, mp4a.40.2
```
> I don't think this is DRM issue, they just changed urls probably.

it is:
```
youtube-dl --proxy localhost:8080 -F https://www.hotstar.com/movies/iron-man-2/1660000039/watch
[hotstar] 1660000039: Downloading webpage
ERROR: This video is DRM protected.
```

**Comment by shizoinakamora** [comment]
Please Help Me..

ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HT
TPError())

**Comment by Anvithlobo** [comment]
So It works you just have to make sure you're in the /watch page and not just the movie page 

also the movie mentioned above by @SSoft7  is a premium movie for which you'll need a premium account  to download

**Comment by SSoft7** [comment]
> So It works you just have to make sure you're in the /watch page and not just the movie page
> 
> also the movie mentioned above by @SSoft7 is a premium movie for which you'll need a premium account to download

Actually, I tried a free video...but posted another video here (choosing randomly). You are right about /watch page... this was the actual problem. ( Actually, I did a search, Then copied link from the results which didn't have /watch in the url.)
