### ISSUE TITLE
Downloader protocol needs to be changed for few sites when https is needed

### ISSUE THREAD

**Issue by ndas1971** [rg3/youtube-dl#18011]
youtube-dl fails with below error(generated from module requests) if there is protocol mismatch
[WinError 10054] An existing connection was forcibly closed by the remote host 

Currently, it is written with http eg for xvideos , extractor is written with http, but currently site uses https , hence changing to https works
Above can be generalized in main downloader code or in specific extractor which can catch this exception and try again with https

**Comment by dstftw** [comment]
```
> py -3.4 .\youtube_dl\__main__.py http://www.xvideos.com/video4588838/biker_takes_his_girl
[XVideos] 4588838: Downloading webpage
[XVideos] 4588838: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 11
[download] Destination: Biker Takes his Girl-4588838.mp4
[download]   4.2% of ~11.90MiB at  1.04MiB/s ETA 00:19
ERROR: Interrupted by user
```

**Comment by ndas1971** [comment]
Thanks, but Looks like we are not on the same page even though the description says 'https'
Could you please execute below and check the result 
> py -3.4 .\youtube_dl\__main__.py   https://www.xvideos.com/video40743585/
