### ISSUE TITLE
youtube seperate audio video streams are not playable?

### ISSUE THREAD

**Issue by simon1tan** [rg3/youtube-dl#18018]
Downloaded  using -f350 and -f280 on video https://www.youtube.com/watch?v=5jFNE8nMbxI. One is opus audio only and the other is 360 vp9 video only. After download, playing audio in VLC produces garbage noises. Playing video shows no video. In the past when I've accidentally downloaded video only, the video plays. Not sure what's wrong here.

**Comment by termenti** [comment]
I can confirm that something is wrong with this link (can't download or check video formats):

youtube-dl -v --geo-bypass -F https://www.youtube.com/watch?v=5jFNE8nMbxI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--geo-bypass', '-F', 'https://www.youtube.com/watch?v=5jFNE8nMbxI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.29
[debug] Python version 3.7.1 (CPython) - Linux-4.18.16-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg n4.0.2, ffprobe n4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 5jFNE8nMbxI: Downloading webpage
[youtube] 5jFNE8nMbxI: Downloading video info webpage
ERROR: The uploader has not made this video available in your country.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1897, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: The uploader has not made this video available in your country.

Other youtube links are passing well.

**Comment by dstftw** [comment]
It's DRM protected.
