### ISSUE TITLE
Error merging audio + video

### ISSUE THREAD

**Issue by Ruebezahl11** [rg3/youtube-dl#18029]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.29**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'bestvideo+bestaudio', u'-o', u'/home/wolfgang/TV/youtube/', u'-v', u'--merge-output-format', u'mkv', u'https://www.youtube.com/watch?v=WEjRf43giII']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2018.10.29
[debug] Python version 2.7.14 (CPython) - Linux-4.12.14-lp150.12.19-default-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, rtmpdump 2.4
[debug] Proxy map: {}

Files download successfully, then ...

[ffmpeg] Merging formats into "/home/wolfgang/TV/youtube/.mkv"
[debug] ffmpeg command line: ffmpeg -y -i 'file:/home/wolfgang/TV/youtube/.f247' -i 'file:/home/wolfgang/TV/youtube/.f140' -c copy -map '0:v:0' -map '1:a:0' 'file:/home/wolfgang/TV/youtube/.mkv.temp'
ERROR: file:/home/wolfgang/TV/youtube/.mkv.temp: Invalid argument

...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

The merge fails because ffmpeg cannot make sense out of the filename .mkv.temp (run ffmpeg command from the console to see the error message)
```
Unable to find a suitable output format for 'file:/home/wolfgang/TV/youtube/.mkv.temp'
```
Using a file name like .temp.mkv would work.
Problem occurs for every merge output format

**Comment by dstftw** [comment]
Incorrect output template.
