### ISSUE TITLE
bandcamp playlist download not working: 'unable to extract title'

### ISSUE THREAD

**Issue by lxcz** [rg3/youtube-dl#18039]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--no-playlist', '--ignore-errors', '--output', '%(playlist)s/%(playlist_index)02d - %(title)s.%(ext)s', '-x', '--audio-format', 'best', '--audio-quality', '0']
[debug] Command-line args: ['--verbose', '--config-location', '/home/user/.config/youtube-dl/config.xaudio-playlist', '--', 'https://andrewhuang.bandcamp.com/music/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.29
[debug] Python version 3.6.7 (CPython) - Linux-4.18.0-2-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0.2-2, ffprobe 4.0.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Bandcamp:album] andrewhuang: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: andrewhuang
[Bandcamp:album] playlist andrewhuang: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: andrewhuang
```
---

### Description of your *issue*, suggested solution and other information

With the config specified above, I was able to download every track from this bandcamp in a separate folder named with the album name, and numbered as they are in the albums in an older version of youtube-dl. Probably bandcamp changed something, so this does not work anymore.

**Comment by dstftw** [comment]
Downloading the entire artist's discography never worked in the first place.

**Comment by lxcz** [comment]
Yes it worked with the exact same config as specified above.
