### ISSUE TITLE
[openload] phantomjs is deprecated

### ISSUE THREAD

**Issue by Brli** [rg3/youtube-dl#18034]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

PhantomJS is archived and the provided Qt headless evaluation browser is out-of-date and known vulnerable.

Please update the JS evaluation method to something still actively maintained such as puppeteer.

**Comment by Brli** [comment]
err, what? why? o_O?

**Comment by dstftw** [comment]
Deprecated does not mean broken. I don't see any point investing time in replacing one working thing with another. There are lots of other more prioritive issues.
