### ISSUE TITLE
extract_info() function's view_count always returns null/NA value

### ISSUE THREAD

**Issue by Carnivalio** [rg3/youtube-dl#18056]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

As the title says, the view_count key from the extract_info (or from download) always return null/NA starting from yesterday, maybe youtube changed something?

*Note:* the download will run normally, but the view_count will just return null/NA

**Comment by KristinHenry** [comment]
I'm not sure why this is closed. I'm still having this issue, and I haven't found the 'duplicate'. Could a link to the issue this duplicates be posted?

thanks!

**Comment by panoslin** [comment]
I also encounter this issue when using it embedding. However,  command-line work just fine.
