### ISSUE TITLE
Crunchyroll: it doesn't create a folder while it does with YouTube

### ISSUE THREAD

**Issue by percheperche** [rg3/youtube-dl#18050]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

> ```

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', 'C:\\User\\MyUser\\Desktop\\%(series)s\\%(title)s.%(ext)s', '-f', 'best[height=480]', '--hls-prefer-native', '--proxy', '', '--sub-lang', 'enUS', '--write-sub', '--sub-format', 'ass', '--embed-subs', 'https://www.crunchyroll.com/golden-time/episode-1-springtime-645007']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.10.29
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92292-ge95987f6ca, ffprobe N-92292-ge95987f6ca, rtmpdump 2.5
[debug] Proxy map: {}
[crunchyroll] 645007: Downloading webpage
[crunchyroll] 645007: Downloading audio-jaJP m3u8 information
[crunchyroll] 645007: Downloading audio-jaJP-hardsub-esLA m3u8 information
[crunchyroll] 645007: Downloading audio-jaJP-hardsub-frFR m3u8 information
[crunchyroll] 645007: Downloading audio-jaJP-hardsub-esES m3u8 information
[crunchyroll] 645007: Downloading audio-jaJP-hardsub-ptBR m3u8 information
[crunchyroll] 645007: Downloading audio-jaJP-hardsub-enUS m3u8 information
[crunchyroll] 645007: Downloading audio-jaJP-hardsub-deDE m3u8 information
[crunchyroll] 645007: Downloading media info
[info] Writing video subtitles to: C:\User\MyUser\Desktop\Golden Time\Golden Time Episode 1 – Springtime.enUS.ass
[debug] Invoking downloader on 'https://v.vrv.co/evs/4d295c7a5e8cff2c5d9f6d90439b0120/assets/ek5lstn4ugth1nh_1812683.mp4/index-v1-a1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvNGQyOTVjN2E1ZThjZmYyYzVkOWY2ZDkwNDM5YjAxMjAvYXNzZXRzLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NDEzMzc0MzZ9fX1dfQ__&Signature=eVteNm7qsbhVHlN5iKyxOUnuA0YHfEYs8l7icSqFCyXhyXffDIWkwgOQRFwYA38L15ufI~EPCuzBi2DSzoQ7hLpoLoPe5X9jVhgTAvEOR~9oujiDzWr4docMoYUFj6XhD4blMajWbGQ5CxTncoN~WQFSbKlUGCw62DqFY~ja5Vmz1UGFNhp4zizloKfZYVX-5mVMvxjOXu~dIMeYg8Ce-7NZ~omCP37zw~88K35y0yWexwNvAc~WtGzbJjdAEWdNVQwh0GaTyIh5LO~pmp4y2d3thJhofDOFA~V4u24BoJpir-XUZlwuDeXvZELsgmUwajjKZDcM3HjfOKtbuA4gEg__&Key-Pair-Id=APKAJKQQ2INNHTYFB44A'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 144
[download] Destination: C:\User\MyUser\Desktop\Golden Time\Golden Time Episode 1 – Springtime.mp4
[download] 100% of 206.65MiB in 07:13
[debug] ffmpeg command line: ffprobe -show_streams "file:C:\User\MyUser\Desktop\Golden Time\Golden Time Episode 1 – Springtime.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "C:\User\MyUser\Desktop\Golden Time\Golden Time Episode 1 – Springtime.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:C:\User\MyUser\Desktop\Golden Time\Golden Time Episode 1 – Springtime.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:C:\User\MyUser\Desktop\Golden Time\Golden Time Episode 1 – Springtime.temp.mp4"
[ffmpeg] Embedding subtitles in 'C:\User\MyUser\Desktop\Golden Time\Golden Time Episode 1 – Springtime.mp4'
[debug] ffmpeg command line: ffmpeg -y -i "file:C:\User\MyUser\Desktop\Golden Time\Golden Time Episode 1 – Springtime.mp4" -i "file:C:\User\MyUser\Desktop\Golden Time\Golden Time Episode 1 – Springtime.enUS.ass" -map 0 -c copy -map "-0:s" "-c:s" mov_text -map "1:0" "-metadata:s:s:0" "language=eng" "file:C:\User\MyUser\Desktop\Golden Time\Golden Time Episode 1 – Springtime.temp.mp4"
Deleting original file C:\User\MyUser\Desktop\Golden Time\Golden Time Episode 1 – Springtime.enUS.ass (pass -k to keep)
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

First of all sorry for my English. I'm foreign. Now, the problem is that if I want to download an episode (or a series) I want to create a folder for the files downloaded. So I made a command like this (YouTube) `-o "C:\Users\MyUser\Desktop\%(uploader)s\%(title)s.%(ext)s"` and it works, creating a folder named with the Uploader and inside all the files downloaded ( [here](https://pastebin.com/snhXmXj5)'s the verbose). I wanted to make something similar with Crunchyroll, I tried with `-o "C:\Users\MyUser\Desktop\%(series)s\%(title)s.%(ext)s"` and it seems like it is going well, but it doesn't create any folder.

**Comment by dstftw** [comment]
As clearly seen from your log folder `C:\User\MyUser\Desktop\Golden Time` has been successfully created.
