### ISSUE TITLE
How to rename already downloaded videos searially?

### ISSUE THREAD

**Issue by cyantarek** [rg3/youtube-dl#18061]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
Hello, I've downloaded many playlists already. But I did not know that I can use template names with serial number with youtube-dl

My question is, can I rename all the playlists that I have downloaded already with a template name?
I know it sounds weird, but I need it badly

**Comment by dstftw** [comment]
No.

**Comment by cyantarek** [comment]
Wait, can I get a .txt file listing all the videos in a playlist sequentially?

**Comment by dstftw** [comment]
Redirect stdout to file.

**Comment by cyantarek** [comment]
How? I didn't find anything like that
