### ISSUE TITLE
youtube-dl "ytsearchall:query" --match-filter "timestamp > 1541337420" downloads nothing

### ISSUE THREAD

**Issue by UKNickyD** [rg3/youtube-dl#18069]
When issuing...

youtube-dl "ytsearchall:dnb mix 2018" --match-filter "timestamp > 1541337420"

It doesn't download a single video, even though there are videos there when I search youtube directly with the "last hour" filter. Am I doing it wrong or is it something else?

TIA

**Comment by dstftw** [comment]
Youtube does not provide timestamp.

**Comment by UKNickyD** [comment]
Thank you... Do you know any way that I would be able to filter the search results to only show the last hours uploads?

TIA

**Comment by UKNickyD** [comment]
youtube-dl "ytsearchall:dnb mix 2018, hour" is what I was looking for, thanks.
