### ISSUE TITLE
AdultSwim issue restricted?

### ISSUE THREAD

**Issue by pirate486743186** [rg3/youtube-dl#18063]
This issue was restricted to collaborators
https://github.com/rg3/youtube-dl/issues/18025

It's not porn, if that's the reason....
It's adult cartoons, literally, not for kids, not an euphemism for porn....

Also the website doesn't seam to be working in the browser, so this could be a total non issue....

**Comment by dstftw** [comment]
There is enough data on the issue. No need to spam and post duplicates.
