### ISSUE TITLE
A ccode update about youku

### ISSUE THREAD

**Issue by Shine-heavy** [rg3/youtube-dl#18075]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.03**

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
=============================================
I can download only 10 minutes video from Youku.com.This bug is caused by **ccode**.If I change the ccode to **0502**, I can download the whole video.

**Comment by dstftw** [comment]
0502 does not work for all videos.
