### ISSUE TITLE
Cannot open libssl_conf.so

### ISSUE THREAD

**Issue by jdhedden** [rg3/youtube-dl#18072]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.03**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
> youtube-dl -v -o '%(title)s.%(ext)s' https://www.dl8x.com/watch/openload.co/f/e9ZXUfRHGRQ/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-o', u'%(title)s.%(ext)s', u'https://www.dl8x.com/watch/openload.co/f/e9ZXUfRHGRQ/']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2018.11.03
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-16.2-liquorix-amd64-x86_64-with-SolydXK-9-testing
[debug] exe versions: avconv 4.0.3, avprobe 4.0.3, ffmpeg 4.0.3, ffprobe 4.0.3, phantomjs 139801070423680
[debug] Proxy map: {}
[generic] e9ZXUfRHGRQ: Requesting header
WARNING: Falling back on generic information extractor.
[generic] e9ZXUfRHGRQ: Downloading webpage
[generic] e9ZXUfRHGRQ: Extracting information
[download] Downloading playlist: [pornomatic.blog.fc2.com] HNDB-125.mp4 - Openload (e9ZXUfRHGRQ) - DL8X
[generic] playlist [pornomatic.blog.fc2.com] HNDB-125.mp4 - Openload (e9ZXUfRHGRQ) - DL8X: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Openload] e9ZXUfRHGRQ: Downloading embed webpage
[Openload] e9ZXUfRHGRQ: Executing JS on webpage
ERROR: Executing JS failed
:Auto configuration failed
140099720625792:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140099720625792:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140099720625792:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140099720625792:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 358, in _real_extract
    webpage, _ = phantom.get(page_url, html=webpage, video_id=video_id, headers=headers)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 236, in get
    'Executing JS failed\n:' + encodeArgument(err))
ExtractorError: Executing JS failed
:Auto configuration failed
140099720625792:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140099720625792:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140099720625792:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140099720625792:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I am running Debian Unstable.  The issue appears to be openssl-1.1.1.  I found two recent cases stating the same error:

https://github.com/drwetter/testssl.sh/issues/1117
https://www.digitalocean.com/community/questions/ubuntu-14-ssh-stopped-working-after-updating-openssl

**Comment by dstftw** [comment]
Your phantomjs setup is broken.

**Comment by jdhedden** [comment]
I didn't have phantomjs installed previously.  Therefore, I installed it.  The same problem still occurs:

> youtube-dl -v -o '%(title)s.%(ext)s' https://www.dl8x.com/watch/openload.co/f/e9ZXUfRHGRQ/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-o', u'%(title)s.%(ext)s', u'https://www.dl8x.com/watch/openload.co/f/e9ZXUfRHGRQ/']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2018.11.03
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-16.2-liquorix-amd64-x86_64-with-SolydXK-9-testing
[debug] exe versions: avconv 4.0.3, avprobe 4.0.3, ffmpeg 4.0.3, ffprobe 4.0.3, phantomjs 139680388214400
[debug] Proxy map: {}
[generic] e9ZXUfRHGRQ: Requesting header
WARNING: Falling back on generic information extractor.
[generic] e9ZXUfRHGRQ: Downloading webpage
[generic] e9ZXUfRHGRQ: Extracting information
[download] Downloading playlist: [pornomatic.blog.fc2.com] HNDB-125.mp4 - Openload (e9ZXUfRHGRQ) - DL8X
[generic] playlist [pornomatic.blog.fc2.com] HNDB-125.mp4 - Openload (e9ZXUfRHGRQ) - DL8X: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Openload] e9ZXUfRHGRQ: Downloading embed webpage
[Openload] e9ZXUfRHGRQ: Executing JS on webpage
ERROR: Executing JS failed
:Auto configuration failed
140279083458176:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140279083458176:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140279083458176:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140279083458176:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 358, in _real_extract
    webpage, _ = phantom.get(page_url, html=webpage, video_id=video_id, headers=headers)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 236, in get
    'Executing JS failed\n:' + encodeArgument(err))
ExtractorError: Executing JS failed
:Auto configuration failed
140279083458176:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140279083458176:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140279083458176:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140279083458176:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
