### ISSUE TITLE
Is Microsoft VC++ Redistributable Package (x86) needed on Windows 10?

### ISSUE THREAD

**Issue by lborgman** [rg3/youtube-dl#18087]
The documentation on the download page (http://rg3.github.io/youtube-dl/download.html)says that this Microsoft package is needed. However reading the documentation for that package (https://www.microsoft.com/en-US/download/details.aspx?id=5555) I does not say it supports Windows 10.

So I am a bit confused.

**Comment by dstftw** [comment]
It is required on Windows 10.

**Comment by lborgman** [comment]
Thanks, @dstftw .
