### ISSUE TITLE
problem with openloadmovies.net

### ISSUE THREAD

**Issue by njscorpion** [rg3/youtube-dl#18081]
the log is as follows:

> [debug] System config: []
> 	[debug] User config: []
> 	[debug] Custom config: []
> 	[debug] Command-line args: ['--verbose', 'https://openloadmovies.net/episodes/the-haunting-of-hill-house-1x1/']
> 	[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> 	[debug] youtube-dl version 2018.11.03
> 	[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
> 	[debug] exe versions: ffmpeg 3.4
> 	[debug] Proxy map: {}
> 	[generic] the-haunting-of-hill-house-1x1: Requesting header
> 	WARNING: Could not send HEAD request to https://openloadmovies.net/episodes/the-haunting-of-hill-house-1x1/: HTTP Error 503: Service Temporarily Unavailable
> 	[generic] the-haunting-of-hill-house-1x1: Downloading webpage
> 	ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> 	File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\extractor\common.py", line 605, in _request_webpage
> 	File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
> 	File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
> 	File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
> 	File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
> 	File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
> 	File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
