### ISSUE TITLE
Add warning to documentation that merging DASH video requires newer avconv

### ISSUE THREAD

**Issue by maxb** [rg3/youtube-dl#1809]
Hi,

I just downloaded my first DASH Video+Audio, and had some difficulty figuring out how to stitch them together. avconv seemed to not be able to properly read the DASH video in copy mode.

Eventually, I tried upgrading my installation of libav from 0.8.9 (available in the current Ubuntu release) to 9.10 (I got it from the Ubuntu development version), and this fixed the issue.

It would be nice if youtube-dl's documentation contained a warning that avconv 0.8.x has problems handling DASH video, and suggested upgrading to avconv 9.x.

The specific video I was downloading was http://www.youtube.com/watch?v=hpNp8WdQOoo format 137, though I also tested a number of the lower quality DASH video formats with the same results.

**Comment by phihag** [comment]
youtube-dl will now warn automatically if it finds an overly old ffmpeg or avconv version. Thanks for the report!

**Comment by wyatt8740** [comment]
It's good that this is fixed. But I'd like to say again that if you have this problem with a recent avconv build, you should really give ffmpeg a try. Sometimes things work in ffmpeg that don't in avconv.
