### ISSUE TITLE
Update yputube-dl when download is running

### ISSUE THREAD

**Issue by hollysheep** [rg3/youtube-dl#18104]
Hi,

i have a raspberry pi that starts some script via cron to check youtube channels for new videos. some of them are running once a day, some once a week and some check every 30min. today i had the problems, that some videos could not be downloaded because of a to old version of youtube-dl. normally the 'update script' is running 2 o'clock, maybe the todays update was released later. so i want to change the intervall for the update to hourly. but lets say youtube-dl starts downloading videos at 8:45 and the downloads takes 1 hour. at 9:00 an other script starts the update check and now there is a new version available. will there be a problem when the update was installed while the app downloaded a video? will the update failure or the download abort or both?

**Comment by dstftw** [comment]
If you haven't run new instance of youtube-dl after update then you're running the old version with all the consequences.
