### ISSUE TITLE
How to reproduce video automatically after download?

### ISSUE THREAD

**Issue by tghelere** [rg3/youtube-dl#18100]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

What command can I use with the youtube-dl, to automatically play the video with VLC?

I usually download my videos with
`youtube-dl -f best -citw dtRPPc-9MGc`

Ubuntu OS

**Comment by dstftw** [comment]
```
--exec CMD                       Execute a command on the file after
                                 downloading, similar to find's -exec
                                 syntax. Example: --exec 'adb push {}
                                 /sdcard/Music/ && rm {}'
```

**Comment by tghelere** [comment]
Sorry for my ignorance, but I'm still a bit disoriented ...
How do I get the filename (dynamic) and its extension?

the command would look something like:
```youtube-dl -f best -citw dtRPPc-9MGc --exec vlc fileName.extension``` ??

**Comment by dstftw** [comment]
Have you read the example? `{}` is replaced with current filename being processed similarly to `find`'s `-exec`.

**Comment by tghelere** [comment]
So...
```youtube-dl -f best -citw dtRPPc-9MGc  --exec vlc {} ```

Thankyou very much
