### ISSUE TITLE
hls download ?

### ISSUE THREAD

**Issue by SheepDomination** [rg3/youtube-dl#18117]
Hi, does youtube download support hls files ? And if so how can I download an hls file from a streaming site (nbs,cbs etc) ?
For example, there is a `hls-841` mp4 file; how can I download this file using youtubedl and possible rtmpdump ?

**Comment by dstftw** [comment]
By passing `-f hls-841`. rtmpdump has nothing to do with HLS.

**Comment by SheepDomination** [comment]
@dstftw I get an error, that `ffmpeg or avconv was not detected`, I typically used ffmpeg manually; how do I set youtubedl to get the mp4 file by means of the flag `-f hls-841` ?

**Comment by Hrxn** [comment]
You need to have `ffmpeg` somewhere in your `PATH`, so that youtube-dl can find it.

**Comment by SheepDomination** [comment]
I placed FFMPEG the path with the variable name as `ffmpeg` and the variable value is set to the path to which ffmpeg is located.  Although the same error occurs ?

**Comment by Hrxn** [comment]
Variable name? The name of the environment variable that is collectively called `PATH` is well, `PATH`. An other name does not work.

If you run youtube-dl with the verbose-flag set (`youtube-dl -v`) you should see something like this:
```
[debug] System config: []
[debug] User config: ['--format', '(bestvideo[vcodec=vp9.2]/bestvideo[vcodec=vp9][fps>30]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[fps>30]/bestvideo[height>720])+(bestaudio[acodec=opus]/bestaudio)/best', '--output', '%(title)s.%(ext)s', '--restrict-filenames', '--netrc']
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.11.18
[debug] Python version 3.7.0 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
PS E:\>
```

And this line indicates that ffmpeg was found:
`[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2`

What is your output here?

**Comment by SheepDomination** [comment]
My output is the following; `[debug] exe versions: rtmpdump 2.4`.

**Comment by Hrxn** [comment]
Then you have `rtmpdump` somewhere in your `PATH`, but not ffmpeg. You can put the ffmpeg binaries into the same place, for example.

**Comment by SheepDomination** [comment]
When using a proxy to get a stream, I get this error repeatedly ?
`[httpproxy @ 0000000002653aa0] Stream ends prematurely at 1031501, should be 18446744073709551615
[tls @ 00000000025dc280] Unable to read from socket
[httpproxy @ 0000000002653aa0] Stream ends prematurely at 1031501, should be 18446744073709551615
[tls @ 00000000025dc280] Unable to read from socket
[httpproxy @ 0000000002653aa0] Stream ends prematurely at 1323944, should be 18446744073709551615
[tls @ 00000000025dc280] Unable to read from socket`

**Comment by SheepDomination** [comment]
@Hrxn or @dstftw ?

**Comment by Hrxn** [comment]
How is a proxy issue related to this issue here (HLS Download)?
