### ISSUE TITLE
-o option no longer works with folder in absolute path

### ISSUE THREAD

**Issue by guygodin** [rg3/youtube-dl#18119]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

The same command-line used to work a few weeks ago, it just stopped working with a recent update.
If the path is directly under a drive letter it works (-o "D:\\"), but if there is a folder included in the path, it no longer works (-o "D:\\Videos\\").

Note: the folder actually exists and is writable.

Full verbose log pasted below.

```
youtube-dl.exe "https://youtu.be/rG4jSz_2HDY" -f bestvideo+bestaudio[ext=m4a]/mp4 -o "D:\\Videos\\%(title)s.%(ext)s" --restrict-filenames -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/rG4jSz_2HDY', '-f', 'bestvideo+bestaudio[ext=m4a]/mp4', '-o', 'D:\\\\Videos\\\\%(title)s.%(ext)s', '--restrict-filenames', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.11.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-73219-gd62657e
[debug] Proxy map: {}
[youtube] rG4jSz_2HDY: Downloading webpage
[youtube] rG4jSz_2HDY: Downloading video info webpage
[debug] Invoking downloader on 'https://r3---sn-nx57ynlz.googlevideo.com/videoplayback?gir=yes&fvip=3&c=WEB&mime=video%2Fmp4&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C264%2C266%2C271%2C278%2C313&initcwndbps=1195000&ipbits=0&expire=1541747816&ip=172.103.160.200&keepalive=yes&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cxtags%2Cexpire&itag=266&lmt=1482396629802216&requiressl=yes&id=o-AEJnhqdQ6Ui4sUu9CR41-CT_P5a2x3-r4ODGS5A-Ovdq&xtags=vproj%3Dmesh&source=youtube&dur=134.300&key=yt6&mm=31%2C26&mn=sn-nx57ynlz%2Csn-n4v7sney&mt=1541726097&mv=m&pl=19&ei=CODkW5bSKI7KkgaN447YDQ&ms=au%2Conr&signature=476B4C5EFBB7343823F8DDE74FBCC75D5F9C21BE.09350523A56B86FB45A2878B502B36410348B71F&clen=303047027&ratebypass=yes'
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'D:\\Videos\\360_Great_Hammerhead_Shark_Encounter_National_Geographic.f266.mp4.part'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\downloader\http.py", line 250, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\utils.py", line 457, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Videos\\360_Great_Hammerhead_Shark_Encounter_National_Geographic.f266.mp4.part'
```

**Comment by dstftw** [comment]
Invalid path. Do not escape backslash.

**Comment by guygodin** [comment]
The issue still occurs with the backslashes not escaped.

**Comment by guygodin** [comment]
> Invalid path. Do not escape backslash.

The issue still occurs with the backslashes not escaped. That's not the problem. I've re-pasted the log.

**Comment by dstftw** [comment]
Most likely the account youtube-dl is running on behalf of doesn't have enought permissions to write at this location.

**Comment by guygodin** [comment]
> Most likely the account youtube-dl is running on behalf of doesn't have enought permissions to write at this location.

You are correct, I tried a different folder and it worked, sorry for the trouble and thank you for the prompt response!
