### ISSUE TITLE
Unable to download Arte serie

### ISSUE THREAD

**Issue by MartinDelille** [rg3/youtube-dl#18115]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Command output

```
$ youtube-dl https://www.arte.tv/fr/videos/RC-014864/nomade-des-mers-les-tutos/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.arte.tv/fr/videos/RC-014864/nomade-des-mers-les-tutos/', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.07
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[arte.tv:+7] nomade-des-mers-les-tutos: Downloading webpage
[download] Downloading playlist: None
[arte.tv:+7] playlist None: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: None
```

---

### Description

This serie URL doesn't work.

**Comment by WebMechanic** [comment]
I wouldn't call this a bug or an issue: there is no playlist or any video (embed) on that particular landing page. ARTE doesn't seem to have a consistent content strategie of whether they add playlists, embed videos, or just publish linked image collections to pages that contain the actual embedded video: the all do "look" similar however.
I use ARTE a lot myself and I often find their site confusing and very inconsistent. _This page is just a bunch of image links to the actual video pages_. It even lacks the first three episodes of the show which are still perfectly available.
IMHO, the "issue" is ARTE's chaotic lack of content strategy :)

Just open an empty textfile, drag 'n' drop the links into it[*] and run youtube-dl with the **-a** flag (batch mode). The actual video pages work fine, e.g. for the first three (missing) episodes:
https://www.arte.tv/fr/videos/064833-001-A/les-escales-de-l-innovation/
https://www.arte.tv/fr/videos/064833-002-A/les-escales-de-l-innovation/
https://www.arte.tv/fr/videos/064833-003-A/les-escales-de-l-innovation/

That's what I do to download stuff from ARTE.

Hope this helps.

[*] drag and drop might not work with some webkit browsers

**Comment by MartinDelille** [comment]
Ok I managed to download them all by opening all the links, copy paste the url into a splitted terminal session:

<img width="1792" alt="screenshot 2018-11-11 22 59 27" src="https://user-images.githubusercontent.com/879889/48318785-97c07e80-e605-11e8-9bbb-02223c1c71b4.png">

Thanks for the missing episode! I didn't even notice I missed them... I hope an Arte developer will see your comment and act in consequence.

I didn't watch the show yet but I recommend you to look a the [fundation leading the project](http://lowtechlab.org) because they are doing an amazing job!
