### ISSUE TITLE
again content id cannot be extracted

### ISSUE THREAD

**Issue by df8oe** [rg3/youtube-dl#18124]
I am using latest version, content id cannot be extracted:

youtube-dl https://www.7tv.de/the-voice-of-germany/87-staffel-8-episode-7-blind-audition-vii-ganze-folge
[prosiebensat1] the-voice-of-germany/87-staffel-8-episode-7-blind-audition-vii-ganze-folge: Downloading webpage
ERROR: Unable to extract clip id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
andreas@wst-andreas:~/Downloads$ youtube-dl https://www.7tv.de/the-voice-of-germany/87-staffel-8-episode-7-blind-audition-vii-ganze-folge
[prosiebensat1] the-voice-of-germany/87-staffel-8-episode-7-blind-audition-vii-ganze-folge: Downloading webpage
ERROR: Unable to extract clip id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
andreas@wst-andreas:~/Downloads$ youtube-dl -v https://www.7tv.de/the-voice-of-germany/87-staffel-8-episode-7-blind-audition-vii-ganze-folge
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.7tv.de/the-voice-of-germany/87-staffel-8-episode-7-blind-audition-vii-ganze-folge']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.07
[debug] Python version 3.6.7 (CPython) - Linux-4.19.0-towo.6-siduction-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, rtmpdump 2.4
[debug] Proxy map: {}
[prosiebensat1] the-voice-of-germany/87-staffel-8-episode-7-blind-audition-vii-ganze-folge: Downloading webpage
ERROR: Unable to extract clip id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/prosiebensat1.py", line 450, in _real_extract
    return self._extract_clip(url, webpage)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/prosiebensat1.py", line 395, in _extract_clip
    self._CLIPID_REGEXES, webpage, 'clip id')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 992, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract clip id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Post `--dump-pages`.
