### ISSUE TITLE
Option to download videos with list= as a playlist and retain video order

### ISSUE THREAD

**Issue by Jtasiu** [rg3/youtube-dl#18121]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

From what I've seen if a URL like https://www.youtube.com/watch?v=_fAOe8oz8qM&list=PLyqf6gJt7KuHBmeVzZteZUlNUQAVLwrZS is fed to youtube-dl it will only download it as a single video. Is it possible to have an option for youtube-dl to download the video according to the playlist given in the URL? 

For example if the above URL is the 3rd video in the PLyqf6gJt7KuHBmeVzZteZUlNUQAVLwrZS playlist and the playlist has 10 videos, youtube-dl will download the playlist video starting from the 3rd video through to the 10th (end) of the playlist.

**Comment by dstftw** [comment]
It will download the whole playlist by default for this URL.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-selection
