### ISSUE TITLE
[youtube] Formats 298 and 299 are not always 60 fps

### ISSUE THREAD

**Issue by suitablyorganic** [rg3/youtube-dl#18149]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
Format 298 is apparently not always 720p60 H.264. For this video it's 720p30 H.264 instead:
https://www.youtube.com/watch?v=tR55NQMK6vY

Same with 299: instead of 1080p60 H.264, they're 1080p30 H.264. (These videos also have 298 at 30 fps.)
https://www.youtube.com/watch?v=3Is4ZAIhTlM
https://www.youtube.com/watch?v=cnY6Yun7lP0
https://www.youtube.com/watch?v=CxrYEpLuCaQ
https://www.youtube.com/watch?v=2UtgsTQIiB0
https://www.youtube.com/watch?v=WyNsjbS1OG0
https://www.youtube.com/watch?v=ONeUY79jLC4
https://www.youtube.com/watch?v=pLSI7JBwU0A
https://www.youtube.com/watch?v=gxNaNdXLEdc
https://www.youtube.com/watch?v=yGs97grPPpg
https://www.youtube.com/watch?v=bzEo09ZYIF0
https://www.youtube.com/watch?v=RiOAld3092Q
https://www.youtube.com/watch?v=jxoVJ9DwyGQ

---

Example
 ```
[info] Available formats for tR55NQMK6vY:
format code  extension  resolution note
[...]
136          mp4        1280x720   720p 2021k , avc1.4d401f, 30fps, video only, 94.09MiB
298          mp4        1280x720   720p 3156k , avc1.4d401f, 30fps, video only, 168.81MiB
[...]
```

And looking with FFprobe, it's definitely not 60 fps
`Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 20 kb/s, 29.97 fps, 30 tbr, 90k tbn, 60 tbc (default)`

Confusingly, `tR55NQMK6vY` is 1080p (formats 248 and 137), but unlike the others (which are also all 1080p), it doesn't have 299 at 30fps even though it has 298 at 30fps.

---

These videos were all uploaded in Aug-Nov 2014 which leads me to believe that this doesn't happen anymore. Still, there are a non-trivial number of these videos.

**Comment by dstftw** [comment]
So what? What's the point of this report?

**Comment by suitablyorganic** [comment]
Well in https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py, in `_formats` there are these two lines
```
'298': {'ext': 'mp4', 'height': 720, 'format_note': 'DASH video', 'vcodec': 'h264', 'fps': 60},
'299': {'ext': 'mp4', 'height': 1080, 'format_note': 'DASH video', 'vcodec': 'h264', 'fps': 60},
```
Should these lines reflect the fact that `fps` varies?

**Comment by dstftw** [comment]
No. These are general case fallbacks used when no metadata is provided by YouTube.
