### ISSUE TITLE
Unable to download pornhub playlists

### ISSUE THREAD

**Issue by toppo2525** [rg3/youtube-dl#18164]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://jp.pornhub.com/playlist/56536411', '-o', 'C:/Users/---/Desktop/pornhub/%(playlist_title)s - %(playlist_id)s/%(title)s - %(id)s.%(ext)s', '-i']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.11.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 4.0.2
[debug] Proxy map: {}
[PornHubPlaylist] 56536411: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: 56536411
[PornHubPlaylist] playlist 56536411: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: 56536411
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by toppo2525** [comment]
<html><head><script type="text/javascript"></script></head>
<body onload="go()">
Loading ...
</body>
</html>

**Comment by toppo2525** [comment]
<html><head><script type="text/javascript"></script></head>
<body onload="go()">
Loading ...
</body>
</html>

**Comment by toppo2525** [comment]
```
<html><head><script type="text/javascript"><!--
function leastFactor(n) {
 if (isNaN(n) || !isFinite(n)) return NaN;
 if (typeof phantom !== 'undefined') return 'phantom';
 if (typeof module !== 'undefined' && module.exports) return 'node';
 if (n==0) return 0;
 if (n%1 || n*n<2) return 1;
 if (n%2==0) return 2;
 if (n%3==0) return 3;
 if (n%5==0) return 5;
 var m=Math.sqrt(n);
 for (var i=7;i<=m;i+=30) {
  if (n%i==0)      return i;
  if (n%(i+4)==0)  return i+4;
  if (n%(i+6)==0)  return i+6;
  if (n%(i+10)==0) return i+10;
  if (n%(i+12)==0) return i+12;
  if (n%(i+16)==0) return i+16;
  if (n%(i+22)==0) return i+22;
  if (n%(i+24)==0) return i+24;
 }
 return n;
}
function go() {
 var p=2522485428822; var s=885170503; var n;
if ((s >> 6) & 1)	p+= 121012379*/*
else p-=
*/9;/*
else p-=
*/else /*
*13;
*/p-=/* 120886108*
*/217126383*
7;
if ((s >> 15) & 1)/* 120886108*
*/p+=20282592*	16;/* 120886108*
*/else 	p-=/*
p+= */46458504* 16;/*
*13;
*/if ((s >> 15) & 1)/*
else p-=
*/p+=/*
else p-=
*/91598888*
16;/*
else p-=
*/else /*
*13;
*/p-=/*
p+= */13524028*/*
p+= */16;	if ((s >> 7) & 1)
p+= 156608127*/*
p+= */8;/* 120886108*
*/else 
p-=/*
else p-=
*/210845136*/*
else p-=
*/8;/* 120886108*
*/if ((s >> 11) & 1)/* 120886108*
*/p+=/*
p+= */133893010*/* 120886108*
*/12; else /*
else p-=
*/p-=
24675271* 12;
 p-=2532242362;
 n=leastFactor(p);
{ document.cookie="RNKEY="+n+"*"+p/n+":"+s+":2321060848:1";
  document.location.reload(true); }
}
//--></script></head>
<body onload="go()">
Loading ...
</body>
</html>
```
