### ISSUE TITLE
ERROR: This video can't be played here, but you can still watch it on YouTube.

### ISSUE THREAD

**Issue by Mahkahe** [rg3/youtube-dl#18163]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v 'https://www.youtube.com/watch?v=EgcrtvomXoI'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=EgcrtvomXoI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.07
[debug] Python version 3.7.1 (CPython) - Linux-4.18.16-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg n4.1, ffprobe n4.1
[debug] Proxy map: {}
[youtube] EgcrtvomXoI: Downloading webpage
[youtube] EgcrtvomXoI: Downloading embed webpage
[youtube] EgcrtvomXoI: Refetching age-gated info webpage
ERROR: This video can't be played here, but you can still watch it on YouTube. Watch on YouTube
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1920, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video can't be played here, but you can still watch it on YouTube. Watch on YouTube

```

---

### Description of your *issue*, suggested solution and other information

I notice that most age-gated or otherwise restricted content are able to be downloaded using youtube-dl, but I've run into a few examples of videos which youtube-dl is unable to download, simply printing the error "ERROR: This video can't be played here, but you can still watch it on YouTube. Watch on YouTube".  I'm not really sure why this is, as other videos in the same "limited" state work with ytdl.

Thank you

**Comment by dstftw** [comment]
You must authenticate to download this video.
