### ISSUE TITLE
Again: images are out of scope out youtube-dl. Does not matter instagram, flickr or whatever.

### ISSUE THREAD

**Issue by Atomix10** [rg3/youtube-dl#18177]
_Originally posted by @dstftw in https://github.com/_render_node/MDU6SXNzdWUzODAyODA2OTY=/issues/unread_timeline#issuecomment-438319856_

1. that was a dick move for just closing something instead of explaining why
2. I know for a fact that Instagram does work with the latest version of Youtube-dl

**Comment by Atomix10** [comment]
so can someone please explain why that is what it is and not just ignore

**Comment by dstftw** [comment]
Do you read my messages at all? youtube-dl **does not support downloading standalone images** from Instagram or any other service. It only supports videos (this is clearly stated in app's description), metadata, video thumbnails and other stuff that comes with video.
