### ISSUE TITLE
--filtered-archive 

### ISSUE THREAD

**Issue by Goeks1** [rg3/youtube-dl#18189]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Could you please add archieve for skipped files?
It should be like the parameter `--download-archive` but for skiped files which does not pass filter(s).
Iam iterating some playlist with a few filter options and without a skiping archive youtube-dl requesting always the same videos which have been already filtered once.
So a `--filtred-archive` would save time and resources.

**Comment by dnthomps** [comment]
What is this a duplicate request of and will it ever be implemented? It seems that the download-archive is faster than downloading the webpage and evaluating filters over and over again. It would be great to be able to add filtered results to the download-archive or similar to avoid downloading and evaluating filtered results every time. A 20 page channel with the --dateafter now-1month becomes a nightmare to scan if you never downloaded the older content.

**Comment by dnthomps** [comment]
My current workaround if anybody cares... download all the videos you want of said channel using whatever filter you want... then take and run the command again but this time with no filters and the --get-id and --no-warnings switches. Copy all of the IDs, prepend 'youtube ' to them and stick them in your download-archive file. Now you can run your batch job weekly, nightly, whatever and it shouldn't have to download the website and check the filter for the videos you never downloaded.
