### ISSUE TITLE
i downlaod course from udemy but it's showing this error

### ISSUE THREAD

**Issue by mansugoyal** [rg3/youtube-dl#18188]
HTTP Error 403: Unauthorized (caused by <HTTPError 403: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ivanskodje** [comment]
This issue is already reported, #18126
