### ISSUE TITLE
Please link to the duplicate thread/solution for problem (#18195, get original automatically generated YT captions, not translations)

### ISSUE THREAD

**Issue by stcoats** [rg3/youtube-dl#18198]
Hello, I posted a question about getting the original automatically generated captions from a YouTube video instead of the translated captions. 

My question was immediately closed without any response. 

Sergey, would you mind linking to the duplicate question and/or the solution to my problem?

I searched the "Issues" and could not find any that directly address this problem. 

Thanks.

**Comment by dstftw** [comment]
#13646.
