### ISSUE TITLE
Get the original automatic captions file of a YouTube video, not the translated ones

### ISSUE THREAD

**Issue by stcoats** [rg3/youtube-dl#18195]
I am downloading only the captions files for videos from YouTube. 

Using the flag --write-auto-sub results in the automatically translated English captions being downloaded, not the original automatic captions file. Example: This video is in Russian, and the automatically-generated captions are in Russian. The following command retrieves automatically-translated English captions. 

```
$ youtube-dl https://www.youtube.com/watch?v=dy-ZSwW7dA0 --skip-download --write-auto-sub -v -o /home/cloud-user/Downloads/captions_file.vtt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=dy-ZSwW7dA0', u'--skip-download', u'--write-auto-sub', u'-v', u'-o', u'/home/cloud-user/Downloads/captions_file.vtt']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.03
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] dy-ZSwW7dA0: Downloading webpage
[youtube] dy-ZSwW7dA0: Downloading video info webpage
[youtube] dy-ZSwW7dA0: Looking for automatic captions
[youtube] dy-ZSwW7dA0: Downloading MPD manifest
[youtube] dy-ZSwW7dA0: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[info] Writing video subtitles to: /home/cloud-user/Downloads/captions_file.en.vtt
```

I can't define the language of the captions I want to download because I am working with a large number of videos and can't manually check the language of each video before I get its captions.

Is there a way to get the original captions? If not, this would be a good feature.

**Comment by OscarL** [comment]
This doesn't says which is the duplicated issue.

For anyone looking... The closest match I've found (yet) is: https://github.com/ytdl-org/youtube-dl/issues/13646
