### ISSUE TITLE
xnxx.com - Missing video qualities

### ISSUE THREAD

**Issue by TheGr33k** [rg3/youtube-dl#18210]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

There are a few video qualities missing for some xnxx videos

E.g
`https://www.xnxx.com/video-ou1h745/yoga_trainger_fucked_ultra_wet_squirting_pussies_and_assholes`

> youtube-dl -F https://www.xnxx.com/video-ou1h745/yoga_trainger_fucked_ultra_wet_squirting_pussies_and_assholes
> [XNXX] ou1h745: Downloading webpage
> [info] Available formats for ou1h745:
> format code  extension  resolution note
> low          mp4        unknown

**Comment by dstftw** [comment]
```
PS C:\Dev\youtube-dl\master> py -2.7 .\youtube_dl\__main__.py https://www.xnxx.com/video-ou1h745/yoga_trainger_fucked_ultra_wet_squirting_pussies_and_assholes -F
[XNXX] ou1h745: Downloading webpage
[XNXX] ou1h745: Downloading m3u8 information
[info] Available formats for ou1h745:
format code  extension  resolution note
low          mp4        unknown
high         mp4        unknown
hls-250p     mp4        444x250     155k
hls-360p     mp4        640x360     423k
hls-480p     mp4        854x480     763k
hls-720p     mp4        1280x720   1327k  (best)
```
