### ISSUE TITLE
youtube history feed

### ISSUE THREAD

**Issue by 5shekel** [rg3/youtube-dl#1821]
i would like to log-in and d/l my history feed
http://www.youtube.com/feed/history

im sure it came up before but couldnt found it.

**Comment by dufferzafar** [comment]
I'm trying to download my youtube history, but I can't figure out where is it stored. I don't want to download any videos, just my feed as a JSON file.

I'm running this:

`youtube-dl -u $username -p %passwd ":ythistory" --skip-download -jv`
