### ISSUE TITLE
[Site support request] minds.com bitchute.com stream.me gab.ai D-Live

### ISSUE THREAD

**Issue by johnny-mac** [rg3/youtube-dl#18226]
Hello, I would like to know what I can do to get these sites added for support. How does one go about adding these websites to youtube-dl? Is there a wiki that can give me some guidelines on how to add websites so I can build the support myself & do a pull-request?

Most of these sites support free speech & do not moderate content like YouTube does, a lot of these websites are already very promising. I think its important we support all types of freedom, from software to podcasts to everything else. Thank you.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#adding-support-for-a-new-site

**Comment by runraid** [comment]
Here's a PR for Gab https://github.com/ytdl-org/youtube-dl/pull/25886
