### ISSUE TITLE
Not able to download from Pornhub.

### ISSUE THREAD

**Issue by whatUsernameIsMine** [rg3/youtube-dl#18223]
OS: Ubuntu 18.04 bionic
Kernel: i686 Linux 4.15.0-39-generic

Basically  this is what the message looks like

####################################################
youtube-dl https://www.pornhub.net/view_video.php?viewkey=203640933 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.pornhub.net/view_video.php?viewkey=203640933', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.18
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-39-generic-i686-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {}
[generic] view_video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] view_video: Downloading webpage
[generic] view_video: Extracting information
[download] Downloading playlist: PublicAgent Bubble butt brunette takes strangers anaconda in her pussy
[generic] playlist PublicAgent Bubble butt brunette takes strangers anaconda in her pussy: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'data:"+o+";base64,"+i+"'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1002, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 857, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1635, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1908, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1847, in dl
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2476, in data_open
binascii.Error: Incorrect padding
#############################################################

My system is updated and youtube-dl is updated , I am sure I downloaded one video from Pornhub a while ago ,,but not able to do it now

**Comment by parmjitv** [comment]
Hi @whatUsernameIsMine,

Hmmm ... I am able to hit the video files for this URL without any problems.  Perhaps the PornHub site was undergoing maintenance when you first tried to download this link?

Cheers,

Parmjit V.

```
$ youtube-dl -vF 'https://www.pornhub.net/view_video.php?viewkey=203640933'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://www.pornhub.net/view_video.php?viewkey=203640933']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.18
[debug] Python version 2.7.9 (CPython) - Linux-3.16.0-4-686-pae-i686-with-debian-8.7
[debug] exe versions: ffmpeg 3.2.4-1, ffprobe 3.2.4-1
[debug] Proxy map: {}
[generic] view_video: Requesting header
[redirect] Following redirect to https://www.pornhub.com/view_video.php?viewkey=203640933
[PornHub] 203640933: Downloading pc webpage
[info] Available formats for 203640933:
format code  extension  resolution note
240p         mp4        240p        400k 
480p         mp4        480p        600k 
720p         mp4        720p       1500k  (best)

```

**Comment by dstftw** [comment]
Probably www.pornhub.net to www.pornhub.com redirect wasn't working at that time.

**Comment by Hrxn** [comment]
Try it with `pornhub.com` instead of `pornhub.net`..

**Comment by whatUsernameIsMine** [comment]
> 
> 
> Try it with `pornhub.com` instead of `pornhub.net`..

Doesn't work.
No Solution as of now :-(

**Comment by whatUsernameIsMine** [comment]
> 
> 
> Hi @whatUsernameIsMine,
> 
> Hmmm ... I am able to hit the video files for this URL without any problems. Perhaps the PornHub site was undergoing maintenance when you first tried to download this link?
> 
> Cheers,
> 
> Parmjit V.
> 
> ```
> $ youtube-dl -vF 'https://www.pornhub.net/view_video.php?viewkey=203640933'
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-vF', u'https://www.pornhub.net/view_video.php?viewkey=203640933']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2018.11.18
> [debug] Python version 2.7.9 (CPython) - Linux-3.16.0-4-686-pae-i686-with-debian-8.7
> [debug] exe versions: ffmpeg 3.2.4-1, ffprobe 3.2.4-1
> [debug] Proxy map: {}
> [generic] view_video: Requesting header
> [redirect] Following redirect to https://www.pornhub.com/view_video.php?viewkey=203640933
> [PornHub] 203640933: Downloading pc webpage
> [info] Available formats for 203640933:
> format code  extension  resolution note
> 240p         mp4        240p        400k 
> 480p         mp4        480p        600k 
> 720p         mp4        720p       1500k  (best)
> ```

Hey paramjit
in your logs , you have been shown to use python 2.7 while mine is using 3.6 .
perhaps you can help me run youtube-dl with 2.7?
I have both version installed in my ubuntu mate

**Comment by parmjitv** [comment]
From your original log post, it looks like you are already running youtube-dl under python 2.7.

One question - are you able to download any video at all from the pornhub.com/.net domain?  Or is just this one specific URL giving you this error message?

Thanks!

**Comment by whatUsernameIsMine** [comment]
> 
> 
> From your original log post, it looks like you are already running youtube-dl under python 2.7.
> 
> One question - are you able to download any video at all from the pornhub.com/.net domain? Or is just this one specific URL giving you this error message?
> 
> Thanks!

Nope , I cannot download any video
