### ISSUE TITLE
[cookscountry] Restore high bitrate video extraction and avoid certificate errors

### ISSUE THREAD

**Issue by blue240** [rg3/youtube-dl#18224]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cookscountry.com/episode/554-smoky-barbecue-favorites']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.11.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92266-gbf324359be, ffprobe N-92266-gbf324359be
[debug] Proxy map: {}
[generic] 554-smoky-barbecue-favorites: Requesting header
WARNING: Could not send HEAD request to https://www.cookscountry.com/episode/554-smoky-barbecue-favorites: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[generic] 554-smoky-barbecue-favorites: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\extractor\common.py", line 605, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\utils.py", line 1139, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
...
<end of log>
```

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-check-certificate', '--list-subs', 'https://www.cookscountry.com/episode/554-smoky-barbecue-favorites']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.11.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92266-gbf324359be, ffprobe N-92266-gbf324359be
[debug] Proxy map: {}
[generic] 554-smoky-barbecue-favorites: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 554-smoky-barbecue-favorites: Downloading webpage
[generic] 554-smoky-barbecue-favorites: Extracting information
[download] Downloading playlist: Smoky Barbecue Favorites
[generic] playlist Smoky Barbecue Favorites: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Zype] 5b400b834b32992a310622b9: Downloading webpage
[Zype] 5b400b834b32992a310622b9: Downloading m3u8 information
5b400b834b32992a310622b9 has no subtitles
[download] Finished downloading playlist: Smoky Barbecue Favorites
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

With previous versions of youtube-dl, high bitrate (2GB per episode) H.264 videos were able to be downloaded from cookscountry.com along with the accompanying subtitles. However, on the latest version, the --no-check-certificate argument is needed to download any videos (only the lower bitrate one is available) and subs are not able to be downloaded. Thank you.

**Comment by dstftw** [comment]
With previous version you can't even download this as zype platform was not supported.
As per SSL error - nothing to do with youtube-dl. Most likely you miss some root certificates in your system store. Also no such 2GB per episode is available for this video.

**Comment by StevenDTX** [comment]
It looks like ATK has switched from Kaltura to Zype.  They used to offer 25Mb/s 1080p streams, but no longer do.
