### ISSUE TITLE
stopped working on nova.cz since last week

### ISSUE THREAD

**Issue by ivopan** [rg3/youtube-dl#18244]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--no-check-certificate', u'--verbose', u'https://novaplus.nova.cz/porad/profesor-t/epizoda/26608-4-dil-dvoji-zivot']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.18
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-39-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[Nova] 26608-4-dil-dvoji-zivot: Downloading webpage
[NovaEmbed] utbyr0: Downloading webpage
ERROR: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ivop/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/ivop/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/home/ivop/bin/youtube-dl/youtube_dl/extractor/nova.py", line 38, in _real_extract
    r'(?s)bitrates\s*=\s*({.+?})\s*;', webpage, 'formats'),
  File "/home/ivop/bin/youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
---

Until last week youtube-dl downloaded video with no problem. I have upgraded to recent version but verbose output shows the same error. Perhaps something has changed.

**Comment by remitamine** [comment]
```
youtube-dl https://novaplus.nova.cz/porad/profesor-t/epizoda/26608-4-dil-dvoji-zivot
[Nova] 26608-4-dil-dvoji-zivot: Downloading webpage
[NovaEmbed] utbyr0: Downloading webpage
[download] Destination:  Profesor T. Dvojí život B068824-utbyr0.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1  579M    1 6799k    0     0   693k      0  0:14:14  0:00:09  0:14:05  818k
```

**Comment by ivopan** [comment]
Hmm,

can I somehow make it more verbose than using switch --verbose ?

While it shows the same error on two different machines on two different external IP.
Both are ubuntu 18.04.1 LTS (up-to-date), one of them is not desktop, just server.

I have upgraded youtube-dl on both before sending report.

Just now I have installed fresh on another machine (again ubuntu 18.04.1, different IP) with exactly the same result:
```
# ./youtube-dl --verbose https://novaplus.nova.cz/porad/profesor-t/epizoda/26608-4-dil-dvoji-zivot
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://novaplus.nova.cz/porad/profesor-t/epizoda/26608-4-dil-dvoji-zivot']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.18
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[Nova] 26608-4-dil-dvoji-zivot: Downloading webpage
[NovaEmbed] 1cznkgo: Downloading webpage
ERROR: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/nova.py", line 38, in _real_extract
    r'(?s)bitrates\s*=\s*({.+?})\s*;', webpage, 'formats'),
  File "./youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

The same test on ubuntu 14.04.5 - the same result (different IP):
```
# ./youtube-dl --verbose https://novaplus.nova.cz/porad/profesor-t/epizoda/26608-4-dil-dvoji-zivot
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://novaplus.nova.cz/porad/profesor-t/epizoda/26608-4-dil-dvoji-zivot']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.18
[debug] Python version 2.7.6 (CPython) - Linux-3.13.0-141-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[Nova] 26608-4-dil-dvoji-zivot: Downloading webpage
[NovaEmbed] 1cznkgo: Downloading webpage
ERROR: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/nova.py", line 38, in _real_extract
    r'(?s)bitrates\s*=\s*({.+?})\s*;', webpage, 'formats'),
  File "./youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Post `--dump-pages`.

**Comment by pajkduf** [comment]
Having the same problem primarily with https://novaplus.nova.cz/porad/tvoje-tvar/epizoda/26599-12-dil, confirming (using Python 2.6 and Python 2.7) on above mentioned url using command:
python2.7 ../bin/youtube-dl --verbose --dump-pages https://novaplus.nova.cz/porad/profesor-t/epizoda/26608-4-dil-dvoji-zivot 1>stdout-profesor-t.txt 2>stderr-profesor-t.txt, stdout & stderr files attached.

[stderr-profesor-t.txt](https://github.com/rg3/youtube-dl/files/2596841/stderr-profesor-t.txt)
[stdout-profesor-t.txt](https://github.com/rg3/youtube-dl/files/2596844/stdout-profesor-t.txt)

**Comment by ivopan** [comment]
Ok, including dump and stderr.

[dump-stdout.txt](https://github.com/rg3/youtube-dl/files/2596854/dump-stdout.txt)
[dump-stderr.txt](https://github.com/rg3/youtube-dl/files/2596857/dump-stderr.txt)

**Comment by pajkduf** [comment]
Confirmed the same erratic behavior using more modern Linux with Python 3.4:
python3 youtube-dl --verbose -F https://novaplus.nova.cz/porad/profesor-t/epizoda/26608-4-dil-dvoji-zivot
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://novaplus.nova.cz/porad/profesor-t/epizoda/26608-4-dil-dvoji-zivot']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.18
[debug] Python version 3.4.3 (CPython) - Linux-3.13.0-161-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[Nova] 26608-4-dil-dvoji-zivot: Downloading webpage
[NovaEmbed] 1cznkgo: Downloading webpage
ERROR: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "youtube-dl/youtube_dl/extractor/nova.py", line 38, in _real_extract
    r'(?s)bitrates\s*=\s*({.+?})\s*;', webpage, 'formats'),
  File "youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
It's not yet released.

**Comment by ivopan** [comment]
Actually I do not see **what** is not yet released !
Do you mean youtube-dl new version ?

Neither can I figure out of what is this issue duplicate.

I think that nova changed its page, I have tried to find that regex

```python
 bitrates = self._parse_json(
            self._search_regex(
                r'(?s)bitrates\s*=\s*({.+?})\s*;', webpage, 'formats'),
            video_id, transform_source=js_to_json)
```

in downloaded webpage with no success. Unfortunately I have no older (and working) copy.

**Comment by ivopan** [comment]
Aha, I have found that regex inside second page. Could that mean that youtube-dl performs the regex search in first page, not in the second ?

**Comment by dstftw** [comment]
I've already pointed out: it's fixed in master but not released.
