### ISSUE TITLE
White page on openload when calling youtube-dl from php

### ISSUE THREAD

**Issue by Medow** [rg3/youtube-dl#18246]
Hello all:
I am trying to call download link from youtube-dl using php using this code:
```
<?php
$url = 'https://openload.co/embed/KxjGqMVBGag';
$cmd = 'youtube-dl --get-url ' . escapeshellarg($url);
echo exec($cmd);
```
But the result always return white page.
I try to change `$url = 'https://openload.co/embed/KxjGqMVBGag';` to other hosts and thery are work perfect except for openload.
i can grab openload url when i excute the command from shell.

Please advice me.

Thanks.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser

**Comment by Medow** [comment]
@dstftw , why are you closing this?
I need to know the reason just for future case.
