### ISSUE TITLE
Downloading Facebook videos requiring authentication results in security alert

### ISSUE THREAD

**Issue by jmgomezpoveda** [rg3/youtube-dl#18258]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Downloading of Facebook videos that lie on private profiles is possible when using the authentication parameters (--username AAA --password BBB). However, everytime I do this I get a security alert from Facebook:

> We've noticed an unusual login from a device or location you don't usually use. Was this you?

Even if I click on "review alert" and "remember browser", the next time I download a video with authentication this alert will present again. It's like youtube-dl presents itself to Facebook as a new browser each time.

If technically possible, it would be great for youtube-dl to present itself to Facebook in a consistent manner so that Facebook's "remember browser" functionality worked as intended.

**Comment by dstftw** [comment]
This is expected behavior. Otherwise you can use authenticated cookies.
