### ISSUE TITLE
Youtube download don`t work

### ISSUE THREAD

**Issue by Roforum** [rg3/youtube-dl#18254]
Hi,
I run last version of youtube-dl
youtube-dl.noarch 0:2018.09.26-1.el7
youtube-dl https://www.youtube.com/watch?v=wcRM9a5vqCY

error:
[youtube] wcRM9a5vqCY: Downloading webpage
[youtube] wcRM9a5vqCY: Downloading video info webpage
[youtube] wcRM9a5vqCY: Downloading js player vflWnjS_n
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 977, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Hrxn** [comment]
That is not the latest version of youtube-dl.

**Comment by Roforum** [comment]
> That is not the latest version of youtube-dl.

I run update and this give me.
I remove and reinstall and this give.

yum remove youtube-dl
yum install youtube-dl

**Comment by Hrxn** [comment]
Use one of the recommended installation methods listed on README.md, not your outdated packages from the distro.
