### ISSUE TITLE
Get youtube title based on id (download-archive)

### ISSUE THREAD

**Issue by Zachary24** [rg3/youtube-dl#18269]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.18**

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

I'm currently writing a basic script that instead of writing all youtube ids to one single file i can select the category (documentary, python course, etc.) and it'll add the ids to that specific file. In which it'll help organize it a bit, is there any way (inside or outside of youtube-dl) to view the titles for each id? As I have to convert my archive file that i have now, and I'd rather check now instead of wasting my time doing it manually if there's something out there! thanks!

**Comment by goggle** [comment]
youtube-dl can easily extract the title based on a YouTube id:
```
youtube-dl 1roy4o4tqQM --get-title
```
The only drawback is, that it is not so fast.
