### ISSUE TITLE
unable to download udemy course - continued

### ISSUE THREAD

**Issue by therom123** [rg3/youtube-dl#18261]
I successfully used youtube-dl in the past to download my videos from udemy.
I found a similar issue "unable to download udemy course" posted few days ago but had no visible solution, so I thought to add my log to it.
I tested and have the same problem on Windows 7/10.

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.18**

C:\ytd\youtube-dl>youtube-dl -U
youtube-dl is up-to-date (2018.11.18)

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\ytd\youtube-dl>youtube-dl --username <GOODUSER> --password <GOODPWD> --verbose https://www.udemy.com/cisco-ccna-security-210-260-exam-100-days-of-labs-with-gns3/learn/v4/t/lecture/11775344
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose', 'https://www.udemy.com/cisco-ccna-security-210-260-exam-100-days-of-labs-with-gns3/learn/v4/t/lecture/11775344']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.11.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[udemy] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\extractor\common.py", line 605, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

Thanks!

**Comment by therom123** [comment]
How can I have support on this issue?
I have found the same here
https://github.com/rg3/youtube-dl/issues/18126
but the content is locked

**Comment by remitamine** [comment]
https://github.com/rg3/youtube-dl#how-can-i-speed-up-work-on-my-issue

**Comment by therom123** [comment]
Ok, thank you!
Please let me know if I can be of help testing with my account
Regards
