### ISSUE TITLE
Downloading movie from YouTube gives "Failed to download MPD manifest" and 404; movie does not play

### ISSUE THREAD

**Issue by joshtriplett** [rg3/youtube-dl#18277]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=5T_CqqjOPDc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.23
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-2-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0.3-1, ffprobe 4.0.3-1
[debug] Proxy map: {}
[youtube] 5T_CqqjOPDc: Downloading webpage
[youtube] 5T_CqqjOPDc: Downloading embed webpage
[youtube] 5T_CqqjOPDc: Refetching age-gated info webpage
[youtube] 5T_CqqjOPDc: Downloading MPD manifest
WARNING: [youtube] 5T_CqqjOPDc: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
...
```

### Description of your *issue*, suggested solution and other information

YouTube recently made various movies available for free. For instance, https://www.youtube.com/watch?v=5T_CqqjOPDc . Attempting to download that with `youtube-dl` produces the above output, and the resulting downloaded file seems corrupted after the initial opening logo.

**Comment by joshtriplett** [comment]
That's a rather opaque bug closure. Could you elaborate, please?

Is this something youtube-dl can't fix? Or is there some other issue about this that I didn't find?

**Comment by Hrxn** [comment]
Nope, no other issue yet as far as I know. You came to the right spot.

Will or can it be fixed? Good question. I don't know, depends on the DRM used or how it is implemented (Is it Widevine?).

But this feature (full movies) is still very new on YT, right? Not surprising that they use a new mechanism here.

**Comment by Fabian42** [comment]
How would that make it not a bug?

Is this report covered by #1774?

**Comment by antdude** [comment]
Ditto. I was trying to download a few videos from https://www.youtube.com/playlist?list=PLHPTxTxtC0ibVZrT2_WKWUl2SAxsKuKwx. :(
