### ISSUE TITLE
[dr] Add support for live streams

### ISSUE THREAD

**Issue by ole-tange** [rg3/youtube-dl#1827]
DR.dk uses RTMP, so youtube-dl ought to be able to download those streams.

The URLs are:

http://www.dr.dk/TV/live/dr1
http://www.dr.dk/TV/live/dr2
http://www.dr.dk/TV/live/dr3
http://www.dr.dk/TV/live/dr-ramasjang
http://www.dr.dk/TV/live/dr-k
http://www.dr.dk/TV/live/dr-ultra

I have been able to download a stream using: http://pclosmag.com/html/Issues/201104/page19.html, but that is quite cumbersome.

**Comment by TRox1972** [comment]
Geo-restricted to Denmark.

**Comment by ole-tange** [comment]
I will be happy to provide a test environment if want to work on this.

**Comment by ole-tange** [comment]
youtube-dl https://www.dr.dk/tv/live/dr1 is still broken

See attached.
[dr1.txt](https://github.com/rg3/youtube-dl/files/819691/dr1.txt)

**Comment by dstftw** [comment]
@ole-tange update ffmpeg.
