### ISSUE TITLE
ERROR: fixed output name but more than one file to download

### ISSUE THREAD

**Issue by btmdave** [rg3/youtube-dl#1828]
Hello,

I'm using this with soundcloud and downloading a single mp3.  I have `--max-downloads` set to 1 and `-o /path/to/download/%(title)s.%(ext)s'`.  I keep getting the fixed output error, but it's only one file.  If I remove the `-o` all together, then it downloads the single file, but in the wrong directory.  Am i missing something?

Thanks!

**Comment by Muzaffar-Munir** [comment]
**I am facing the same problem in using Youtube-dl for downloading videos**
i am sending youtube video key to the end point and then concatinate it on endpoint In following request jBItiUvGSyI is the video id but its showing ERROR: fixed output name but more than one file to download

data sending From jBItiUvGSyI
Video downloading Request from  'http://www.youtube.com/watch?v=jBItiUvGSyI'
ERROR: fixed output name but more than one file to download

**Comment by FlyJim** [comment]
I fixed this problem by removing the spaces in the folder name:

youtube-dl --skip-download --write-sub --sub-lang en https://www.youtube.com/watch?v=mwn8xhgNpFY -o C:/Users/flyji/Desktop/JF/**scrape youtube videos**/srts/%(title)s-%(id)s.%(ext)s

to

youtube-dl --skip-download --write-sub --sub-lang en https://www.youtube.com/watch?v=mwn8xhgNpFY -o C:/Users/flyji/Desktop/JF/**scrape-youtube-videos**/srts/%(title)s-%(id)s.%(ext)s

**Comment by rautamiekka** [comment]
> I fixed this problem by removing the spaces in the folder name:
> 
> _Before:_
> youtube-dl --skip-download --write-sub --sub-lang en https://www.youtube.com/watch?v=mwn8xhgNpFY -o C:/Users/flyji/Desktop/JF/**scrape youtube videos**/srts/%(title)s-%(id)s.%(ext)s
> 
> _After:_
> youtube-dl --skip-download --write-sub --sub-lang en https://www.youtube.com/watch?v=mwn8xhgNpFY -o C:/Users/flyji/Desktop/JF/**scrape-youtube-videos**/srts/%(title)s-%(id)s.%(ext)s

Just use double quotes and all of that will be fixed ... You should be, anyway.
