### ISSUE TITLE
Round-the-clock monitoring "YouTube" channel (and download "Live Stream")

### ISSUE THREAD

**Issue by mihapsx** [rg3/youtube-dl#18286]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```

[debug] System config: []
[debug] User config: ['-o', 'C:\\youtube-dl\\download\\%(title)s-%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/channel/UCOS-qxHw6iqC2ipPpwiqvzw/videos']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.11.23
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
...
<end of log>
```

---

### How make so that "youtube-dl" round-the-clock monitored YouTube channel, and if the there start of the "Live Stream", "youtube-dl" started to download it. ?

My command line looks like this:

youtube-dl --download-archive archive.txt "https://www.youtube.com/channel/UCOS-qxHw6iqC2ipPpwiqvzw/videos"

or

youtube-dl "https://www.youtube.com/channel/UCOS-qxHw6iqC2ipPpwiqvzw"

Please help.

**Comment by ealgase** [comment]
The first command should work, but you need to wrap it in a batch script to be always active.  The following should work: https://gist.github.com/ealgase/d3e91c247bf32c091e85be9229bffd0f.  Download it, put it in the folder where you want the channel, then run `around-the-clock-monitor <channel url>`

**Comment by dstftw** [comment]
Monitoring is out of scope of youtube-dl.
