### ISSUE TITLE
The uploader has not made this video available in your country

### ISSUE THREAD

**Issue by titirino159** [rg3/youtube-dl#18295]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.23**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
root@vps:~/test# youtube-dl -v s3O1Xro7oAI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u's3O1Xro7oAI']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode                                                                                                                                                              all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968,                                                                                                                                                              pref ANSI_X3.4-1968
[debug] youtube-dl version 2018.11.23
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian                                                                                                                                                             -9.6
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[youtube] s3O1Xro7oAI: Downloading webpage
[youtube] s3O1Xro7oAI: Downloading video info webpage
ERROR: The uploader has not made this video available in your country.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 79                                                                                                                                                             2, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py",                                                                                                                                                              line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py",                                                                                                                                                              line 1920, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: The uploader has not made this video available in your country.

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=s3O1Xro7oAI

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Hello !
I have a vps in France (Gravelines) : https://www.ovh.com/world/vps/vps-cloud.xml VPS Cloud 2
I can download a lot of videos. But I don't know why, I can't download some videos like this : https://www.youtube.com/watch?v=s3O1Xro7oAI
I have the error " The uploader has not made this video available in your country"

I really don't know why. My vps location is in France... 

My ip : 
root@vps:~/test# curl yt-dl.org/ip
51.75.143.194

I know that I can use a proxy, but the speed is very slow. And I want to know why I'm blocked

I'm on debian 9 so I don't know if it's okay with a browser

Thank you

**Comment by remitamine** [comment]
the error message is self-explanatory.

**Comment by forkbabu** [comment]
@remitamine instead of commenting as such , suggest a workaround, yes?
