### ISSUE TITLE
Synchronization playlist

### ISSUE THREAD

**Issue by Jucker7** [rg3/youtube-dl#18299]
Hello. I made a script to download a playlist with next parameters:
`youtube-dl -i --format mp4 --yes-playlist --external-downloader aria2c -o '%(playlist_index)03d - %(title)s - %(id)s.%(ext)s' --include-ads --merge-output-format mp4 [playlist]`
After several days I've faced a problem: playlist's author added a new video in the middle of the playlist and youtube-dl has to downloaded a half of the playlist again. But old files are stay and not removed.
How can I synchronize the playlist and already downloaded files without downloading downloaded files again, but renaming it to a new names? Thanks.

**Comment by dstftw** [comment]
You can't.
