### ISSUE TITLE
(YouTube) Figuring out Video Decoder/Formatting

### ISSUE THREAD

**Issue by Rajvir8** [rg3/youtube-dl#18302]
I'm trying to figure out what the code I'd use for lowering the quality of the videos I wanted to download.

I've read through all of the Faq and couldn't figure it out.

I know that as a Windows User Using the EXE version that to download I would open the CMD in the folder I want to download.

I'd then go youtube-dl.exe "https://www.youtube.com/watch?v=ne2BcdU75qE&index=3&list=PLAD5jdjmBF508Xo09kEQ8UO5VfAua3Q-7"

It then starts downloading at the highest available quality which in this case is 720.

I know that 480, and 360 are available for this playlist.

If I wanted to download 360 what Command Prompt would I use exactly?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#format-selection

**Comment by Rajvir8** [comment]
Thank you
