### ISSUE TITLE
Unable to download specific videos from Hotstar. Getting an error that says "This video is DRM protected."

### ISSUE THREAD

**Issue by rajucomp** [rg3/youtube-dl#18303]
I am trying to download this [video](https://www.hotstar.com/sports/cricket/icc-womens-world-t20-2018/australia-women-vs-england-women-m187008/match-clips/final-australia-vs-england/2001754331) but I am getting an error that says that "This video is DRM protected." Here is the log :- 
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--username', 'PRIVATE', '--password', 'PRIVATE', '--user-agent', 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Version/10.0 Mobile/14D27 Safari/602.1', 'https://www.hotstar.com/sports/cricket/icc-womens-world-t20-2018/australia-women-vs-england-women-m187008/match-clips/final-australia-vs-england/2001754331']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.11.23
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92190-gb2adc31697, ffprobe N-92190-gb2adc31697
[debug] Proxy map: {}
[hotstar] 2001754331: Downloading webpage
ERROR: This video is DRM protected.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\extractor\hotstar.py", line 85, in _real_extract
youtube_dl.utils.ExtractorError: This video is DRM protected.
```
I have tried passing my premium username and password (though that should not be necessary because the content itself is not premium) and changed the user agent but to no avail. What is more interesting is that all the videos from this [page](https://www.hotstar.com/sports/cricket/tournament/icc-women's-t20-world-cup-2018-1153/list/icc-womens-world-t20/t-4877) can be easily downloaded by youtube-dl except all the full replay videos. I tried to find the `.m3u8` file from the Chrome Developer Tools but could not find one. What i found were `URLs` like [this](https://hsdash36.akamaized.net/dash/live/678966/iccwwt202018m1/WT20FINALAUSENG25NOV2018/index_audio64-1543101271.mp4) but they don't contain anything.

**Comment by dstftw** [comment]
What's not clear in the error message?

**Comment by Siddhant** [comment]
Can you change the error message to "This video is DRM protected, and hence can never be downloaded." Or some such similar wording? With emphasis on **never**.

I think people get confused that it's just a matter of passing the correct parameters to get the video, and they just need to find those.
(In this case the user thoguht that providing the site username and password should give them access to the DRM protected video. And so on with trying different options.)

**Comment by maXity** [comment]
> 
> 
> Can you change the error message to "This video is DRM protected, and hence can never be downloaded." Or some such similar wording? With emphasis on **never**.
> 
> I think people get confused that it's just a matter of passing the correct parameters to get the video, and they just need to find what those options are.
> (In this case the user thoguht that providing the site username and password should give them access to the DRM protected video. And so on with trying different options.)
> 
> For anotther exmaple of such confusion, see #17928, where the user writes "I am not sure if you can fix this, so that is the reason I am opening this issue."

I fully agree with this, actually that very sentiment is what brought me here
