### ISSUE TITLE
Output template, Playlist_title OR Uploader

### ISSUE THREAD

**Issue by Zachary24** [rg3/youtube-dl#18314]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.23**

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

For example I keep all videos related to a certain show in a playlist on youtube, each video is uploaded by different people, but i still want them all in the same folder (Show_title - Extras), but i also archive specific channels that i would want to use the uploader name as the default directory, is there any built in way to do whichever one applys? (Im building an all in one python app that has most of the settings as a preset) I read through the section about the output template but didn't see anything that would work (sorta like when using -f you can do 136/137/247+140/bestaudio etc)

**Comment by dstftw** [comment]
Different output templates for different playlists/channels.
