### ISSUE TITLE
White page when grabbing openload video using php

### ISSUE THREAD

**Issue by Medow** [rg3/youtube-dl#18319]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
 youtube-dl -v https://openload.co/embed/jMUP_p-MlKg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://openload.co/embed/jMUP_p-MlKg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.18
[debug] Python version 3.6.7 (CPython) - Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[Openload] jMUP_p-MlKg: Downloading embed webpage
[Openload] jMUP_p-MlKg: Executing JS on webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://openload.co/stream/jMUP_p-MlKg~1543409651~95.216.0.0~KSSqzfVj?mime=true'
[download] Destination: The.Simpsons.S01E07.The.Call.of.the.Simpsons.720p.HDTV.DD5.1.x264-CtrlHD.mkv.mp4-jMUP_p-MlKg.mp4
```

---
### Description of your *issue*, suggested solution and other information

I am trying to grab openload.co direct stream using youtube-dl through PHP.
Most other website work as expected , showing the exact stream URL, only openload show white page.
I can produce the stream URL from shell succefully but not on PHP.
This is only happen on openload.co

The code i use as follow:

```
<?php
if($_GET['url'] != ""){
        $url = $_GET['url'];
  }else{ echo 'No video url added!'; exit;}
$cmd = 'youtube-dl --get-url ' . escapeshellarg($url);
 exec($cmd, $output);
$output = json_encode($output);
$output = stripslashes($output);
echo $output;
```

Please advice me.

**Comment by dstftw** [comment]
Post complete verbose log without any quiet options enabled.
