### ISSUE TITLE
Too slow in processing urls

### ISSUE THREAD

**Issue by durai23** [rg3/youtube-dl#18310]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.23**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

C:\Users\synapse\Desktop\tools>timecmd.bat youtube-dl -e -v https://www.youtube.com/watch?v=UAor3YnvcQ4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-e', '-v', 'https://www.youtube.com/watch?v=UAor3YnvcQ4']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.11.23
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-92522-g370b8bd847, ffprobe N-92522-g370b8bd847
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
Making Lemon Cordial
command took 0:1:53.13 (113.13s total)

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Single video: https://www.youtube.com/watch?v=UAor3YnvcQ4

---

### Description of your *issue*, suggested solution and other information

The time taken to "print title only" for a single video is too long. I checked this with channels/playlists as well and it seems to take approximately 112 seconds to process one video. I also checked using other programs that are dependent on youtube-dl and the result is the same.

Does anyone know why it is so slow? Does anyone else experience the same slow speed of processing?

**Comment by dstftw** [comment]
Post complete verbose log.

**Comment by durai23** [comment]
Hi, I did post the complete verbose log. Could you please check again?

**Comment by durai23** [comment]
> Post complete verbose log.

Hi, I did post the complete verbose log. Could you please check again?

**Comment by Dmole** [comment]
I tried on an old version and the current version and both gave

```
> time ~/scripts/bin/youtube-dl.pyc -e -v https://www.youtube.com/watch?v=UAor3YnvcQ4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-e', u'-v', u'https://www.youtube.com/watch?v=UAor3YnvcQ4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.23
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-39-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
Making Lemon Cordial

real	0m2.843s
user	0m1.512s
sys	0m0.088s
```

So it might just be that Python on Windows is slow...
