### ISSUE TITLE
Fox.com not working (again?)

### ISSUE THREAD

**Issue by lincalinca** [rg3/youtube-dl#18325]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
λ youtube-dl --proxy 45.77.6.65:80 https://www.fox.com/watch/d3a5d8ffc7e1b448f6c30ba03f1ff1b2/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--proxy', u'45.77.6.65:80', u'https://www.fox.com/watch/d3a5d8ffc7e1b448f6c30ba03f1ff1b2/', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.11.23
[debug] Python version 2.7.12 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91646-g78d4b6bd43, ffprobe N-91646-g78d4b6bd43
[debug] Proxy map: {u'http': u'45.77.6.65:80', u'https': u'45.77.6.65:80'}
[FOX] d3a5d8ffc7e1b448f6c30ba03f1ff1b2: Downloading JSON metadata
ERROR: Unable to download JSON metadata: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "c:\python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "c:\python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27\lib\site-packages\youtube_dl\utils.py", line 1139, in https_open
    req, **kwargs)
  File "c:\python27\lib\urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "c:\python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "c:\python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "c:\python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "c:\python27\lib\httplib.py", line 897, in _send_output
    self.send(msg)
  File "c:\python27\lib\httplib.py", line 859, in send
    self.connect()
  File "c:\python27\lib\httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "c:\python27\lib\httplib.py", line 839, in connect
    self._tunnel()
  File "c:\python27\lib\httplib.py", line 811, in _tunnel
    (version, code, message) = response._read_status()
  File "c:\python27\lib\httplib.py", line 417, in _read_status
    raise BadStatusLine(line)

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Nothing from Fox seems to be able to download.

**Comment by tv21** [comment]
This and #17985 appear to be the exact same issue, if you can fix it for one you can probably use the same approach to fix the other.

**Comment by remitamine** [comment]
most likely a problem in the proxy.
