### ISSUE TITLE
running youtube-dl.exe from a Windows GUI applications

### ISSUE THREAD

**Issue by gfyllos** [rg3/youtube-dl#18328]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I would like to use youtube-dl.exe to download videos from inside a windows GUI app. So at some point in my app, I do a CreateProcess(...) which is created ok, but does not seem to do anything as the file is not downloaded.  The process terminates with error code -1.

I verifies that the same command from CLI work fine, and that the CreateProcess() is invoked with correct arguments.

Does anyone has an ides why this happens?

**Comment by dstftw** [comment]
Capture stdout and stderr and see what's happening.
