### ISSUE TITLE
Twitch downloads interrupt every few %

### ISSUE THREAD

**Issue by iorazbek** [rg3/youtube-dl#18326]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo+bestaudio/best', '-o', '%(upload_date)s - %(title)s - %(id)s.%(ext)s', '-a', 'url-list']
[debug] Batch file urls: ['https://www.twitch.tv/videos/319030717']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.11.23
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-92348-g242f7bf202, ffprobe N-92348-g242f7bf202
[debug] Proxy map: {}
[twitch:vod] 319030717: Downloading vod info JSON
[twitch:vod] 319030717: Downloading vod access token
[twitch:vod] 319030717: Downloading m3u8 information
[debug] Invoking downloader on 'https://vod-metro.twitch.tv/d17d287dde514db1ccdd_broughy1322_30656097600_984631531/chunked/index-dvr.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1895
[download] Destination: 20181006 - A spot of GTA then Forza Horizon 4! - v319030717.mp4
[download]   4.5% of ~13.05GiB at 11.99MiB/s ETA 01:06         ERROR: unable to rename file: [WinError 32] The process cannot access the file because it is being used by another process: '20181006 - A spot of GTA then Forza Horizon 4! - v319030717.mp4.part-Frag85.part' -> '20181006 - A spot of GTA then Forza Horizon 4! - v319030717.mp4.part-Frag85'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\downloader\common.py", line 200, in try_rename
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '20181006 - A spot of GTA then Forza Horizon 4! - v319030717.mp4.part-Frag85.part' -> '20181006 - A spot of GTA then Forza Horizon 4! - v319030717.mp4.part-Frag85'

<end of log>

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.twitch.tv/videos/319030717

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

This isn't exclusive to Twitch. Twitch is just the most prominent and consistent one in regards to this, but I've had this happen on other sites. The download interrupts every few % (sometimes every few .1%). Theoretically I could just spam the command again and again and eventually download the whole thing, but this is obviously not viable.

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by Hrxn** [comment]
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:

This indicates interference by another process/program etc.
Something specific to your local system or configuration, not something on youtube-dl's side.

**Comment by iorazbek** [comment]
> > PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:
> 
> This indicates interference by another process/program etc.
> Something specific to your local system or configuration, not something on youtube-dl's side.

This happens after a fresh restart before I've opened anything. Why would it interfere with another process and is there a way to find out which process it is? I have a pretty minimal install (ltsc with 4-5 3rd party programs most of which are sandboxed native uwp apps), and there's definitely not shortage of resources in the system.

**Comment by Hrxn** [comment]
Well, the first place to check would probably be this:
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

Download and run Process Explorer (aka ProcExp), useful tool to see every running process on the system. It also has a search capability that will quickly show you which processes have particular handles open, in this case try to search for the handle displayed here, i.e. the filename reported in the error message earlier.

**Comment by iorazbek** [comment]
The filename is actually a fragment of the file I'm trying to download. I.e. it seems like the process that's interfering with the download is the one that I'm trying to download.. I couldn't fine anything in Process Explorer. Could this have something to do with 1809 or Windows 10 in general?

**Comment by iorazbek** [comment]
I think I figured out why this was happening. The script was inside a folder that was being synced to Mega. When I moved it outside the cloud folder it went through no problem.
