### ISSUE TITLE
Blotchy video from Facebook

### ISSUE THREAD

**Issue by TaktakTaktouk** [rg3/youtube-dl#18337]
I tried to download a video from facebook (https://www.facebook.com/elizabethgsaunders/videos/10157134504853217/) but the quality was horrible: sound out of sync with video and blotchy picture.
with options or no it's always the same results: here is the link of the video. I use the last version of Youtube-dl. 
I tried with other sites who user your software and always the same result. except for https://www.fbdown.net who gives me an identical copy of the source video without spots in the images or offset in the sound.

> youtube-dl -v https://www.facebook.com/elizabethgsaunders/videos/10157134504853217/
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-v', u'https://www.facebook.com/elizabethgsaunders/videos/10157134504853217/']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2018.11.23
> [debug] Python version 2.7.9 (CPython) - Linux-2.6.32-042stab133.2-x86_64-with-debian-8.11
> [debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1
> [debug] Proxy map: {}
> [facebook] 10157134504853217: Downloading webpage
> [debug] Default format spec: bestvideo+bestaudio/best
> [debug] Invoking downloader on u'https://scontent-cdt1-1.xx.fbcdn.net/v/t42.9040-29/10000000_193528021576144_2245426335621054464_n.mp4?_nc_cat=109&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfbGl2ZV9tZF9mcmFnXzJfdmlkZW8ifQ==&_nc_ht=scontent-cdt1-1.xx&oh=5b2141f3802659838d5de2be0a0183b4&oe=5BFFF007'
> [download] Destination: Feeling disappointed and let down after trying really hard at something and n...-10157134504853217.f193528008242812vd.mp4
> [download] 100% of 74.50MiB in 00:06
> [debug] Invoking downloader on u'https://scontent-cdt1-1.xx.fbcdn.net/v/t42.1790-29/10000000_2062600200429674_4680540133798182912_n.mp4?_nc_cat=106&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfbGl2ZV9tZF9mcmFnXzJfYXVkaW8ifQ==&_nc_ht=scontent-cdt1-1.xx&oh=68195feb29ebb3b41cc5ec3872244384&oe=5BFFE517'
> [download] Destination: Feeling disappointed and let down after trying really hard at something and n...-10157134504853217.f2062600130429681ad.m4a
> [download] 100% of 11.96MiB in 00:01
> [ffmpeg] Merging formats into "Feeling disappointed and let down after trying really hard at something and n...-10157134504853217.mp4"
> [debug] ffmpeg command line: ffmpeg -y -i 'file:Feeling disappointed and let down after trying really hard at something and n...-10157134504853217.f193528008242812vd.mp4' -i 'file:Feeling disappointed and let down after trying really hard at something and n...-10157134504853217.f2062600130429681ad.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Feeling disappointed and let down after trying really hard at something and n...-10157134504853217.temp.mp4'
> Deleting original file Feeling disappointed and let down after trying really hard at something and n...-10157134504853217.f193528008242812vd.mp4 (pass -k to keep)
> Deleting original file Feeling disappointed and let down after trying really hard at something and n...-10157134504853217.f2062600130429681ad.m4a (pass -k to keep)

**Comment by dstftw** [comment]
Update ffmpeg or download single file media format that does not require merging.
