### ISSUE TITLE
[Feature suggestion] youtube-dl to download videos from a list.txt similar to wget

### ISSUE THREAD

**Issue by RagglenLove** [rg3/youtube-dl#18358]
I'm suggesting this feature because I have experienced times when the videos I want aren't conveniently included in a playlist.

For example, I collected urls of many videos on Youtube into a list.txt file and I want youtube-dl to download from the urls listed in list.txt.

Here's an example of a wget command to download from a list:
`wget -i list.txt`

If youtube-dl were to implement a feature like this, it would save people time since there are times when the videos you want aren't included in playlists, as I said.

**Comment by Hrxn** [comment]
`youtube-dl -a list.txt`

**Comment by RagglenLove** [comment]
Thanks.
