### ISSUE TITLE
How are exe builds generated?

### ISSUE THREAD

**Issue by mitchtbaum** [rg3/youtube-dl#18355]
I can't find any Travis or Appveyor scripts to learn from for building other python binaries from source.

Thanks in advance.

**Comment by Hrxn** [comment]
With `py2exe`, or what do you mean?

**Comment by mitchtbaum** [comment]
That's what I'm asking about.  Thanks.

Could you explain a bit more how it's done?  Perhaps the builds get generated somehow with this script?  https://github.com/rg3/youtube-dl/blob/c3bcd206eb031de30179c88ac7acd806a477ceae/devscripts/buildserver.py

I've seen other build scripting done with Travis and Appveyor, so that's what I'm thinking to do for Python.

**Comment by dstftw** [comment]
`exe`s are built by [`buildserver.py`](https://github.com/rg3/youtube-dl/blob/master/devscripts/buildserver.py). It's a simple http server that [processes](https://github.com/rg3/youtube-dl/blob/master/devscripts/buildserver.py#L406-L430) [request from the main build script](https://github.com/rg3/youtube-dl/blob/master/devscripts/release.sh#L99) and sends back ready `exe`.
