### ISSUE TITLE
Site support request

### ISSUE THREAD

**Issue by Tabtabaei** [rg3/youtube-dl#18366]
media from http://www.bbc.com/arabic

- Single video: http://www.bbc.com/arabic/media-46405204

Thank you.

## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.23**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.11.23
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by remitamine** [comment]
works fine:
```
youtube-dl http://www.bbc.com/arabic/media-46405204
[bbc] media-46405204: Downloading webpage
[bbc] p06tbc9k: Downloading media selection XML
[bbc] p06tbc9k: Downloading m3u8 information
[bbc] p06tbc9k: Downloading m3u8 information
[bbc] p06tbc9k: Downloading MPD manifest
[bbc] p06tbc9k: Downloading m3u8 information
[bbc] p06tbc9k: Downloading m3u8 information
[bbc] p06tbc9k: Downloading MPD manifest
[bbc] p06tbc9k: Downloading m3u8 information
[bbc] p06tbc9k: Downloading m3u8 information
[bbc] p06tbc9k: Downloading MPD manifest
[bbc] p06tbc9k: Downloading m3u8 information
[bbc] p06tbc9k: Downloading m3u8 information
[bbc] p06tbc9k: Downloading MPD manifest
[download] Downloading playlist: حكاية طفل "تسونامي" المعجزة
[bbc] playlist حكاية طفل "تسونامي" المعجزة: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[download] Destination: حكاية طفل 'تسونامي' المعجزة-p06tbc9k.mp4
ffmpeg version n4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20180831
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[hls,applehttp @ 0x55d9a742c580] Opening 'https://bbcfmt-ic-669d7c00-0332d2-vodhlswwlive.s.loris.llnwd.net/usp/auth/vod/piff_abr_full_sd/e07acc-p06tbc9k/vf_p06tbc9k_4b448845-a862-46a1-9315-62a350cd7bac.ism/vf_p06tbc9k_4b448845-a862-46a1-9315-62a350cd7bac-audio_eng_1=128000-video=1604000-1.ts' for reading
[hls,applehttp @ 0x55d9a742c580] Opening 'https://bbcfmt-ic-669d7c00-0332d2-vodhlswwlive.s.loris.llnwd.net/usp/auth/vod/piff_abr_full_sd/e07acc-p06tbc9k/vf_p06tbc9k_4b448845-a862-46a1-9315-62a350cd7bac.ism/vf_p06tbc9k_4b448845-a862-46a1-9315-62a350cd7bac-audio_eng_1=128000-video=1604000-2.ts' for reading
Input #0, hls,applehttp, from 'https://bbcfmt-ic-669d7c00-0332d2-vodhlswwlive.s.loris.llnwd.net/usp/auth/vod/piff_abr_full_sd/e07acc-p06tbc9k/vf_p06tbc9k_4b448845-a862-46a1-9315-62a350cd7bac.ism/vf_p06tbc9k_4b448845-a862-46a1-9315-62a350cd7bac-audio_eng_1=128000-video=1604000.m3u8':
  Duration: 00:02:38.64, start: 10.000000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 960x540 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:حكاية طفل 'تسونامي' المعجزة-p06tbc9k.mp4.part':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 960x540 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  161 fps=122 q=-1.0 Lsize=    1008kB time=00:00:06.40 bitrate=1290.4kbits/s speed=4.86x
```
