### ISSUE TITLE
Error of tudou

### ISSUE THREAD

**Issue by RaysonYeungHK** [rg3/youtube-dl#1836]
I downloaded the version on 11.25 and try these with python 2.7, here is the error.
```
./youtube_dl/__main__.py http://www.tudou.com/listplay/k9vRJrB0ZoI/0lvulMp0i5k.html
[Tudou] 0lvulMp0i5k.html: Downloading webpage
[Tudou] 183446808: Opening the info webpage
ERROR: unable to download video data: <urlopen error timed out>
```

**Comment by yan12125** [comment]
Closing as no response for a long time. If anyone can watch Tudou videos in the browser but youtube-dl fails, feel free to open a new issue.
