### ISSUE TITLE
Config settings for each (YT) channel in batch file

### ISSUE THREAD

**Issue by Zachary24** [rg3/youtube-dl#18363]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.23**

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

For example, I have a batch file with currently 50 youtube channels (growing daily), some of which have upwards of 1-2000+ videos, EG (I only really care about the last 1-2 years for most), Is there any way to specify config settings for each channel individually?

**Comment by dstftw** [comment]
`--config-location`.

**Comment by Zachary24** [comment]
Would that allow for setting settings for each channel? Like, 1 channel in the file only downloads videos from after 8-1-16, and another only downloads videos from after 1-1-18

**Comment by Zachary24** [comment]
It doesn't seem like it does from the readme file..

**Comment by Zachary24** [comment]
> `--config-location`.

?

**Comment by Zachary24** [comment]
I'm not asking to download individual videos, I'm asking about a youtube channel in its entirety. One url for one channel, all channel URLs are in a url.txt file, but I don't want to download ALL videos from each channel, only after a certain point in time (--dateafter), for one channel i may only want to start downloading videos from up until 2 years ago, while another I may want the entire channel, I'm not asking for setting session wide configurations, If that's not something that's already been implemented, id ask if the issue gets reopened.
