### ISSUE TITLE
unable to download video from hotstar

### ISSUE THREAD

**Issue by nsvaidya** [rg3/youtube-dl#18386]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

the provided link is playable in browser, but youtube-dl is not downloading due to RegexNotFoundError. Not running from any vpn, using jio network.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.hotstar.com/tv/sarabhai-vs-sarabhai/s-36/meet-the-sarabhais/1000010418']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.12.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[hotstar] 1000010418: Downloading webpage
ERROR: Unable to extract app state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\hotstar.py", line 80, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\common.py", line 983, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract app state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by remitamine** [comment]
```
youtube-dl https://www.hotstar.com/tv/sarabhai-vs-sarabhai/s-36/meet-the-sarabhais/1000010418
[hotstar] 1000010418: Downloading webpage
[hotstar] 1000010418: Downloading JSON metadata
[hotstar] 1000010418: Downloading m3u8 information
[download] Destination: Meet the Sarabhais-1000010418.mp4
ffmpeg version n4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20180831
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[hls,applehttp @ 0x564d07a4e0c0] Opening 'https://staragvod-vh.akamaihd.net/i/videos/plus/svss/01/1000010418_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/crypt.key?null=0&id=AgCLOxlXFwNGjWaJClyy8GIfwcbs3qUOXO%2fwrkuHx9iTKKPTAZfkwGINS%2fDHC9OYPnElecbf3TqKUA%3d%3d' for reading
[hls,applehttp @ 0x564d07a4e0c0] Opening 'crypto+https://staragvod-vh.akamaihd.net/i/videos/plus/svss/01/1000010418_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/segment1_7_av.ts?null=0&id=AgCLOxlXFwNGjWaJClyy8GIfwcbs3qUOXO%2fwrkuHx9iTKKPTAZfkwGINS%2fDHC9OYPnElecbf3TqKUA%3d%3d' for reading
[NULL @ 0x564d07ac6d80] non-existing SPS 0 referenced in buffering period
[NULL @ 0x564d07ac6d80] SPS unavailable in decode_picture_timing
[h264 @ 0x564d080aafc0] non-existing SPS 0 referenced in buffering period
[h264 @ 0x564d080aafc0] SPS unavailable in decode_picture_timing
Input #0, hls,applehttp, from 'https://staragvod-vh.akamaihd.net/i/videos/plus/svss/01/1000010418_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/index_7_av.m3u8?null=0&id=AgCLOxlXFwNGjWaJClyy8GIfwcbs3qUOXO%2fwrkuHx9iTKKPTAZfkwGINS%2fDHC9OYPnElecbf3TqKUA%3d%3d':
  Duration: 00:20:31.80, start: 0.100667, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Meet the Sarabhais-1000010418.mp4.part':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   22 fps=4.9 q=-1.0 size=       0kB time=00:00:00.91 bitrate=   0.4kbits
```

**Comment by remitamine** [comment]
post the output with `--dump-pages` option.

**Comment by nsvaidya** [comment]
[out.txt](https://github.com/rg3/youtube-dl/files/2657838/out.txt)
This contains the output which you require.

**Comment by BUAWF** [comment]
I think the issue is back again !!
https://us.hotstar.com/tv/dance-/s-281/ranveer-sara-are-overwhelmed/1000225871
Connected to US ExpressVPN, still no use !!
With this url it's playing in chrome, but not even showing list of formats with -F !!
Neither with 09.12.2018 version nor with the latest i.e. 17.12.2018 !
