### ISSUE TITLE
VRTnu subtitles no longer hardcoded, text subtitles aren't downloaded

### ISSUE THREAD

**Issue by hansworzt** [rg3/youtube-dl#18381]
Used latest v2018.12.03.
VRTnu has changed the way subtitles are shown, previously they were hardcoded into the video stream, now they are separate text files.
The youtube-dl --all-subs --skip-download --id "..." does not download them.
E.g. : https://www.vrt.be/vrtnu/a-z/er-was-eens/1/er-was-eens-a5-een-model-voor-de-natuur/

**Comment by SamDecrock** [comment]
HLS VTT subtitles (used by vrtnu) are available in the youtube-dl fork `yt-dlp` : https://github.com/yt-dlp/yt-dlp/
