### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 3219 (geana.FastVideo), pid 2602 (geana.FastVideo)

### ISSUE THREAD

**Issue by ZhangKuixun** [rg3/youtube-dl#18391]
android usually crashes after using youtube-dl.
log:
com.PinusBungeana.FastVideo W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
com.PinusBungeana.FastVideo W/google-breakpad: Chrome build fingerprint:
com.PinusBungeana.FastVideo W/google-breakpad: 70.0.3538.110
com.PinusBungeana.FastVideo W/google-breakpad: 353811052
com.PinusBungeana.FastVideo W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
com.PinusBungeana.FastVideo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 3219 (geana.FastVideo), pid 2602 (geana.FastVideo)

**Comment by evexoio** [comment]
What's the youtube-dl error?
