### ISSUE TITLE
NRK.no zero items in playlist

### ISSUE THREAD

**Issue by nlehtinen** [rg3/youtube-dl#18406]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v https://tv.nrk.no/serie/nytt-paa-nytt/2018/MUHH50002918
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://tv.nrk.no/serie/nytt-paa-nytt/2018/MUHH50002918']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.03
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-39-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {}
[NRKTVSeries] nytt-paa-nytt: Downloading webpage
[download] Downloading playlist: NRK TV – Nytt på nytt
[NRKTVSeries] playlist NRK TV – Nytt på nytt: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: NRK TV – Nytt på nytt
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

The youtube-dl does not see any videos on the NRK webpage for "Nytt på nytt" program (https://tv.nrk.no/serie/nytt-paa-nytt/2018). It says the playlist contains zero items. But the browser plays a video (I tried Chrome, Firefox). I tried various available episodes and this problem persists for all of them. The videos are available only in Norway, but I am in Norway and do not use any proxies. Other similar similar series, i.e., Lykkeland (https://tv.nrk.no/serie/lykkeland/sesong/1/episode/1/avspiller) do not have this problem and download OK.

**Comment by nlehtinen** [comment]
Hi, this is a duplicate of which issue?

**Comment by remitamine** [comment]
Duplicate of #18304.

**Comment by nlehtinen** [comment]
Thanks! :)
