### ISSUE TITLE
New imgur videos

### ISSUE THREAD

**Issue by Meneth32** [rg3/youtube-dl#18404]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://imgur.com/GPnMEcs']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.12.03
[debug] Git HEAD: 5547014ad
[debug] Python version 3.5.3 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-82721-g89092fa, ffprobe N-82721-g89092fa, phantomjs 2.1.1
[debug] Proxy map: {}
[Imgur] GPnMEcs: Downloading webpage
ERROR: No sources found for video GPnMEcs. Maybe an image?
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl\extractor\common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl\extractor\imgur.py", line 67, in _real_extract
    expected=True)
youtube_dl.utils.ExtractorError: No sources found for video GPnMEcs. Maybe an image?

...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

New imgur videos seem to use some new system not yet supported by youtube-dl. However, Firefox can save mp4 files as usual.

This error does not occur with older videos.

**Comment by ealgase** [comment]
That image isn't available for me (returns a not found page).  Can you give another example?

**Comment by Meneth32** [comment]
https://imgur.com/gallery/GPnMEcs (works in browser but youtube-dl strips the "gallery" part and goes 404)
https://imgur.com/a/GPnMEcs ("WARNING: Falling back on generic information extractor.", lots of "Got server HTTP error")
https://imgur.com/zzn6218 (works in both browser and youtube-dl).
