### ISSUE TITLE
Short Question about the status on opus/webm/mkv Metadata/CoverArt Embedding

### ISSUE THREAD

**Issue by cyberpunkbln** [rg3/youtube-dl#18407]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [x] Other

Hello, i only would know how the status is.

Is it possible in the future to add metdata and embed thumbnails/coverart in opus, webm, mkv files extracted from youtube?

At the moment i can only add coverart with tageditors cli and a very strange cmd-files combination;).

Thx, it will be great.

ps: I know that opus metadata and coverart are the same like ogg-vorbis?!?

**Comment by dstftw** [comment]
Probably.
