### ISSUE TITLE
How do I install ffmpeg on iOS for youtube-dl?

### ISSUE THREAD

**Issue by chaocharleswang** [rg3/youtube-dl#18410]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I integrated youtube-dl into my iOS project with "Python-iOS-support". However, how can I install ffmpeg and use youtube-dl to call it?

My trial:
I built ffmpeg with "FFmpeg-iOS-build-script" and put it into my iOS project.
Then I found "--ffmpeg-location" in youtube-dl. However, I don't know how to use it in my iOS project.

**Comment by dstftw** [comment]
Nothing special. ffmpeg must be in `$PATH`.

**Comment by chaocharleswang** [comment]
How do I set $PATH in xcode? Do I still need use "ffmpeg-location"?
