### ISSUE TITLE
unable to extract html5 player & too small choice of formats on Youtube

### ISSUE THREAD

**Issue by slrslr** [rg3/youtube-dl#18418]
### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
E:\Other\Software\Youtube-DL>youtube-dl.exe --verbose --audio-format aac --audio
-quality 0 --keep-video --recode-video webm --prefer-free-formats https://www.yo
utube.com/watch?v=gl1aHhXnN1k
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--audio-format', 'aac', '--audio-quali
ty', '0', '--keep-video', '--recode-video', 'webm', '--prefer-free-formats', 'ht
tps://www.youtube.com/watch?v=gl1aHhXnN1k']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2018.12.03
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] gl1aHhXnN1k: Downloading webpage
[youtube] gl1aHhXnN1k: Downloading video info webpage
WARNING: unable to extract html5 player; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
 update. Be sure to call youtube-dl with the --verbose flag and include its comp
lete output.
[youtube] {18} signature length 44.40, html5 player None
[youtube] gl1aHhXnN1k: Downloading player https://www.youtube.com/yts/jsbin/play
er_ias-vfl_RGK2l/en_US/base.js
WARNING: unable to extract html5 player; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
 update. Be sure to call youtube-dl with the --verbose flag and include its comp
lete output.
[youtube] {36} signature length 44.40, html5 player None
```

---

### Description of your *issue*, suggested solution and other information

When i ran command to show available audio video formats for that URL, it shown many interesting video formats, but  without audio.

```E:\Other\Software\Youtube-DL>youtube-dl.exe --list-formats https://www.youtube.c
om/watch?v=gl1aHhXnN1k
[youtube] gl1aHhXnN1k: Downloading webpage
[youtube] gl1aHhXnN1k: Downloading video info webpage
[youtube] gl1aHhXnN1k: Downloading js player vflJ0vgSM
[info] Available formats for gl1aHhXnN1k:
format code  extension  resolution note
249          webm       audio only DASH audio   59k , opus @ 50k, 2.05MiB
250          webm       audio only DASH audio   77k , opus @ 70k, 2.67MiB
171          webm       audio only DASH audio  127k , vorbis@128k, 4.52MiB
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.4
0.2@128k, 5.10MiB
251          webm       audio only DASH audio  150k , opus @160k, 5.14MiB
278          webm       256x144    144p   99k , webm container, vp9, 24fps, vide
o only, 3.55MiB
160          mp4        256x144    144p  112k , avc1.4d400c, 24fps, video only,
3.32MiB
242          webm       426x240    240p  224k , vp9, 24fps, video only, 7.49MiB
133          mp4        426x240    240p  247k , avc1.4d4015, 24fps, video only,
6.38MiB
243          webm       640x360    360p  416k , vp9, 24fps, video only, 13.56MiB

134          mp4        640x360    360p  634k , avc1.4d401e, 24fps, video only,
15.26MiB
244          webm       854x480    480p  762k , vp9, 24fps, video only, 23.55MiB

135          mp4        854x480    480p 1188k , avc1.4d401e, 24fps, video only,
29.78MiB
247          webm       1280x720   720p 1523k , vp9, 24fps, video only, 45.64MiB

136          mp4        1280x720   720p 2307k , avc1.4d401f, 24fps, video only,
53.40MiB
248          webm       1920x1080  1080p 2720k , vp9, 24fps, video only, 79.00Mi
B
137          mp4        1920x1080  1080p 3959k , avc1.640028, 24fps, video only,
 93.20MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 3.06MiB
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2, 8.51MiB
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 23.81Mi
B (best)
```

The audio included formats are only three (on the bottom), really bad choice to choose from, i wanted webm video 720p VP9 with audio. Unsure if issue is on my side or on YT not providing it?

Windows 7 Ultimate 64bit, i am not aware i installed any codec pack.

**Comment by rautamiekka** [comment]
Instead of manually fucking around with the format codes, use format specifiers:

If you don't want the highest resolution, specify that in the specifier, like this:
```
--format "bestvideo[height=720]+bestaudio/best"
```
This'll choose the best vid with the height of 720p (commonly 1280x720 but there are other, rare, instances) and the best audio, then uses FFmpeg or `avconv` to combine them (you've to specify the location). If that fails, it'll take the best present option which had both vid and audio, in this case the format code 18 in your output.

In YT they don't store high-resolution combinations of best vid and best audio, but in separate parts. That's a godsend to us although it requires combining them locally.

Dunno if your other options will play nicely with this; I imagine FFmpeg will convert the audio and/or the vid.

**Comment by slrslr** [comment]
@rautamiekka 
> --format "bestvideo[height=720]+bestaudio/best"

Thanks for detailed explanation. The result was:

E:\Other\Software\Youtube-DL>youtube-dl.exe --format "bestvideo[height=720]+best
audio/best" https://www.youtube.com/watch?v=gl1aHhXnN1k
[youtube] gl1aHhXnN1k: Downloading webpage
[youtube] gl1aHhXnN1k: Downloading video info webpage
**WARNING: You have requested multiple formats but ffmpeg or avconv are not instal
led. The formats won't be merged.
WARNING: Requested formats are incompatible for merge and will be merged into mk
v.**
[download] Destination: Ariana Gr@nde - thank u, next-gl1aHhXnN1k.f136**.mp4**
[download] 100% of 53.69MiB in 01:28
[download] Destination: Ariana Gr@nde - thank u, next-gl1aHhXnN1k.f251**.webm**
[download] 100% of 5.14MiB in 00:07

(It ended up the audio is .webm and video is .mp4)

So ffmpeg/avconv is not bundled in youtube-dl.exe? Can it be bundled for more easy to use?
I need to be searching some third party software to install codec packs for me?
How do you do it?
I am on Windows 7.
