### ISSUE TITLE
How can I stop to get url?

### ISSUE THREAD

**Issue by ZhangKuixun** [rg3/youtube-dl#18423]
I want stop to get url when the page close. When I open a page, then use youtube-dl get url. If get url is not finished, I close the page immediately.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient

**Comment by ZhangKuixun** [comment]
way close? Is there a way to close it get url?

**Comment by ZhangKuixun** [comment]
Is there a way to close it get url? @dstftw
