### ISSUE TITLE
Bestvideo with best audio (opus format) doesn't work for mp4 merge

### ISSUE THREAD

**Issue by hdpcshow** [rg3/youtube-dl#18446]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

When i do **youtube-dl --format bestvideo+bestaudio --merge-output-format mp4** it doesn't work on videos where only the opus format has the best audio, because opus can't merge with mp4.

My question is, can you guys make it work. For example that it converts the opus format to something else and then merge.

**Comment by dstftw** [comment]
`--recode-video`.

**Comment by raqueeb** [comment]
C:\Downloads\youtube-dl.exe -f bestvideo+bestaudio --recode-video mp4 --ffmpeg-location C:\Downloads\ffmpeg\bin\ffmpeg.exe -o e:\%(title)s.%(ext)s https://www.youtube.com/watch.......
