### ISSUE TITLE
[ARD:mediathek] ERROR: Unable to extract media id

### ISSUE THREAD

**Issue by w4grfw** [rg3/youtube-dl#18441]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ python -m youtube_dl --verbose --ignore-config https://www.ardmediathek.de/ard/player/Y3JpZDovL3N3ci5kZS9hZXgvbzEwNzE5MTU/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--ignore-config', u'https://www.ardmediathek.de/ard/player/Y3JpZDovL3N3ci5kZS9hZXgvbzEwNzE5MTU/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.03
[debug] Git HEAD: 8c5879715
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-12-generic-x86_64-with-Ubuntu-18.10-cosmic
[debug] exe versions: ffmpeg 4.0.2-2, ffprobe 4.0.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[ARD:mediathek] Y3JpZDovL3N3ci5kZS9hZXgvbzEwNzE5MTU: Downloading webpage
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/ard.py", line 219, in _real_extract
    r'/play/(?:config|media)/(\d+)', webpage, 'media id')
  File "youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by back-to** [comment]
the issue is that you can get different website versions

**old Website** (you might get redirected, but it is still available)
https://www.ardmediathek.de/tv/Dokumentarfilm/Das-Salz-der-Erde-Sebasti%C3%A3o-Salgado-im/SWR-Fernsehen/Video?bcastId=1105036&documentId=57927466

**new Website** (won't work if you can open the old Website, might work with new cookies)
https://www.ardmediathek.de/ard/player/Y3JpZDovL3N3ci5kZS9hZXgvbzEwNzE5MTU/

**beta Website**
https://beta.ardmediathek.de/ard/player/Y3JpZDovL3N3ci5kZS9hZXgvbzEwNzE5MTU/

the new website is only supported with `beta.ardmediathek.de`

https://github.com/rg3/youtube-dl/blob/8c5879715f4d979b83c49d44a9094307247097ba/youtube_dl/extractor/ard.py#L295-L298

but it requires a name after the video_id for youtube-dl
you can just use something random as `(?P<display_id>[^/?#]+)` is not needed
_see example below_

also **Livestreams** are not supported with the current regex

- https://www.ardmediathek.de/ard/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL0xpdmVzdHJlYW0tRGFzRXJzdGU
- https://www.ardmediathek.de/swr/live/Y3JpZDovL3N3ci5kZS8xMzQ4MTA0Mg

---

**example** _beta Website with random display_id for youtube-dl_

```
$ youtube-dl "https://beta.ardmediathek.de/ard/player/Y3JpZDovL3N3ci5kZS9hZXgvbzEwNzE5MTU/x" -v -F
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://beta.ardmediathek.de/ard/player/Y3JpZDovL3N3ci5kZS9hZXgvbzEwNzE5MTU/x', '-v', '-F']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.03
[debug] Git HEAD: 8c5879715
[debug] Python version 3.7.1 (CPython) - Linux
[debug] exe versions: ffmpeg n4.1, ffprobe n4.1, rtmpdump 2.4
[debug] Proxy map: {}
[ARDBetaMediathek] x: Downloading webpage
[ARDBetaMediathek] Y3JpZDovL3N3ci5kZS9hZXgvbzEwNzE5MTU: Downloading m3u8 information
[info] Available formats for Y3JpZDovL3N3ci5kZS9hZXgvbzEwNzE5MTU:
format code  extension  resolution note
hls-56       mp4        audio only   56k , mp4a.40.2
hls-185      mp4        320x180     185k , avc1.66.30, mp4a.40.2
hls-323      mp4        480x270     323k , avc1.66.30, mp4a.40.2
hls-613      mp4        512x288     613k , avc1.77.30, mp4a.40.2
hls-1192     mp4        640x360    1192k , avc1.77.30, mp4a.40.2
hls-1973     mp4        960x540    1973k , avc1.77.30, mp4a.40.2
hls-3768     mp4        1280x720   3768k , avc1.64001f, mp4a.40.2
hls-6692     mp4        1920x1080  6692k , avc1.64001f, mp4a.40.2
http-0       mp4        unknown    
http-1       mp4        unknown    
http-2       mp4        unknown    
http-3       mp4        unknown    (best)
```

**Comment by w4grfw** [comment]
Yes that, works: change hostname in url from www.ardmediathek.de to beta.ardmediathek.de and append random character if url ends with /

so, should i close this issue, because we have to wait till ardmediathek becomes stable or should i leave this open?
