### ISSUE TITLE
Cannot download pornhub private videos

### ISSUE THREAD

**Issue by pmp452** [rg3/youtube-dl#18457]
I'm typing youtube-dl.exe -u username -p password downloadlink and it still says that i need to be friend with user. Basically it does not detect my account, or not login properly. How to fix this issue?

I have just downloaded the newest version.

**Comment by dstftw** [comment]
Authentication is not supported. You must pass cookies from browser.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl
