### ISSUE TITLE
YouTube login fails

### ISSUE THREAD

**Issue by ealgase** [rg3/youtube-dl#18459]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u':ytrecent', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.03
[debug] Python version 2.7.12 (CPython) - Linux-3.14.0-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15-0ubuntu0.16.04.1, ffprobe 2.8.15-0ubuntu0.16.04.1, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube:recommended] Downloading login page
[youtube:recommended] Looking up account info
[youtube:recommended] Logging in
WARNING: Unable to login: Invalid password
[youtube:recommended] Youtube Recommended videos: Downloading webpage
[download] Downloading playlist: Youtube Recommended videos
[youtube:recommended] playlist Youtube Recommended videos: Downloading 0 videos
[download] Finished downloading playlist: Youtube Recommended videos
```
### Description of your *issue*, suggested solution and other information

I've been using youtube-dl to download all of my recently watched videos.  However, since yesterday, logging in fails, with the "invalid password" message.

I'm willing to privately provide my account credentials if that's what's necessary to solve this problem.

**Comment by dstftw** [comment]
Can do that via mail in my profile.

**Comment by Zipdox** [comment]
I'm also unable to login.
`WARNING: Unable to login: Invalid password`
While I'm 100% entering the correct password

**Comment by ealgase** [comment]
Looks like it fails on any account/credentials, I tried many of mine, and they all failed.

**Comment by Zipdox** [comment]
Sometimes it already fails when trying to load the login page.

**Comment by Hrxn** [comment]
If necessary: https://myaccount.google.com/security

And turn *Allow less secure apps:* to ON.

**Comment by ealgase** [comment]
Weird, the setting was on, but now it works (without me making any changes).  It's also started working on my other accounts (that also had the issue).
