### ISSUE TITLE
Check for list=** in the link

### ISSUE THREAD

**Issue by hbina** [rg3/youtube-dl#18469]
Currently, **when you want to download a playlist**, you have to remove the rest of the parameter exlcuding 'list=**'. Not removing the rest of the parameter will cause the program to hang. Not sure why this is the case.

It would be helpful, and I think this applies to most use cases, if the program could detect if the user wants to download the entire playlist, and not just the currently playing video.

To replicate, consider this:
youtube-dl --extract-audio --audio-format=mp3 https://www.youtube.com/watch?v=LiJFkRiO1K8&index=4&list=RDxOHCWHR5DQM

Executing this will download that single video and the program will hang after converting them to *.mp3.

And like I described before, doing:

youtube-dl --extract-audio --audio-format=mp3 https://www.youtube.com/watch?list=RDLiJFkRiO1K8

is perfectly fine.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
