### ISSUE TITLE
[File as URL source] Display number of processed/remaining links to download

### ISSUE THREAD

**Issue by Michal-MK** [rg3/youtube-dl#18467]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)

A low priority feature that I have not found a request for in closed issues, displaying the number of items processed/remaining when downloading  using a text file with links.
Title name suggested this: #1855 which is 5 years old, possibly and extension.

**Comment by dstftw** [comment]
It's already printed.
>[download] Downloading video 1 of 707

**Comment by Michal-MK** [comment]
@dstftw 
I would not be reporting it if it was actually there, if the feature is implemented already then it is not in the default configuration which is strange, so how do I make it appear ?
Thanks
What I see:
https://i.gyazo.com/4dfb4e48e656d8f3078cc476753d5a12.png
