### ISSUE TITLE
fix hotstar link extraction (-g)

### ISSUE THREAD

**Issue by Internet2249** [rg3/youtube-dl#18479]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\youtube-dl>youtube-dl --verbose -g --format "best[height<=360]" https://www.hotstar.com/tv/kasautii-zindagii-kay/s-1667/danger-looms-over-anurag/1000225277 >> Debug.log
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-g', '--format', 'best[height<=360]', 'https://www.hotstar.com/tv/kasautii-zindagii-kay/s-1667/danger-looms-over-anurag/1000225277']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.12.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, phantomjs 2.1.1
[debug] Proxy map: {}

Link Extracted:- https://hses.akamaized.net/videos/plus/kzk2sp/54/phone/media-2/index.m3u8

...
<end of log>
```
### Description of your *issue*, suggested solution and other information
Etracted link from youtube-dl is not working in streamlink.
please fix this issue 
(add token value to this link)
link extracted from chrome:-https://hses.akamaized.net/videos/plus/kzk2sp/54/tv/media-2/index.m3u8?hdnea=st=1544439536~exp=1544441336~acl=/*~hmac=9244d4867185a40a7ea0b6fd698fe3cab2144800f3c05a7630fadcc9cee2a655

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser
