### ISSUE TITLE
[iprima.cz] ExtractorError

### ISSUE THREAD

**Issue by kubalav** [rg3/youtube-dl#18477]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.iprima.cz/filmy/desne-rande', '-v']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2018.12.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-69406-ga73c411, ffprobe 3.3.2
[debug] Proxy map: {}
[IPrima] desne-rande: Downloading webpage
[IPrima] p516536: Downloading player
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg8efod20\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg8efod20\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg8efod20\build\youtube_dl\extractor\iprima.py", line 109, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg8efod20\build\youtube_dl\extractor\common.py", line 1292, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.iprima.cz/filmy/desne-rande

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Video is playable in web browser.

**Comment by kibeb** [comment]
Now they cancelled play.iprima.cz and the videos are now split between multiple subdomains like
https://zoom.iprima.cz/porady/letiste-na-severu/blizard
https://krimi.iprima.cz/mraz-0/sebevrazdy
and the website look changed significantly.
So the movie https://www.iprima.cz/filmy/desne-rande that stayed on already known domain name is just a coincidence, IMHO, and we need new parsing and everything... dunno, I'm just a user. ;)
Please help. Thank you very much in advance.

**Comment by radarfox** [comment]
My current solution is to replace the subdomain part of URL with an old working one.

For example:

- this does't work: https://zoom.iprima.cz/10-nejvetsich-tajemstvi-zahad/posvatna-mista-a-stavby
- this works: https://prima.iprima.cz/10-nejvetsich-tajemstvi-zahad/posvatna-mista-a-stavby

[I think that the problem is in the regex here](https://github.com/rg3/youtube-dl/blob/9235b5091cedcc21c8dc32d4b292340edeee4ed0/youtube_dl/extractor/iprima.py#L15). Is anyone capable of changing it, so it will match any subdomain for `iprima.cz`?

However, this seems not to work: https://prima.iprima.cz/filmy/desne-rande

**Comment by dstftw** [comment]
For any work on the issue you must provide account credentials.
