### ISSUE TITLE
Feature Request: "null" output (discard) option

### ISSUE THREAD

**Issue by BobCu** [rg3/youtube-dl#18484]
I looking for a lightweight "dummy" DASH and HLS client to fetch and discard video/audio segments as they become available.  The URLs point directly to the top-level .mpd and .m3u8 files.

I built some small streaming servers that transcode and host live adaptive (3-resolution) streams of local TV stations (a simple OTT system consisting of a RasPi with a USB tuner dongle) to the LAN (not the internet/WAN), and I need to test them plus the caching reverse-proxy in front of them (which exists primarily to offload HTTPS encryption when too many clients connect).  I'd like to be able to run hundreds of dummy clients.

The streams are live and have no end, and I'll be running many clients, which means no storage or buffering of any kind is wanted (nor can be supported).  If things go extremely well, I have 16 Gbps of bandwidth I can (try to) saturate.

Looking through the youtube-dl output options, I saw none that would simply let me write the fetched media content directly to the bit bucket (/dev/null or equivalent).  I tried "-o - >/dev/null", but it seems ffmpeg was getting launched.

Did I miss this option?  I checked both the command-line documentation and the FAQ.

**Comment by dstftw** [comment]
Live DASH and HLS are only supported via ffmpeg.

**Comment by BobCu** [comment]
Excellent!  `ffmpeg -i <url> -c copy -f null` does just what I need.
