### ISSUE TITLE
Openload can not download best format

### ISSUE THREAD

**Issue by samitc** [rg3/youtube-dl#18481]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', '3737051986167835834', '-f', 'best[filesize<1500m]', 'https://openload.co/f/iddjscr8ASo/DDLWgrLx5MTi5AoR1utpYcj28XgHRTAcWGn4.mkv']
[debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2018.12.09
[debug] Python version 3.6.7 (CPython) - Linux-4.15.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[Openload] iddjscr8ASo: Downloading embed webpage
[Openload] iddjscr8ASo: Executing JS on webpage
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 804, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 858, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1628, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available
```

**Comment by dstftw** [comment]
The error message is clear enough.

**Comment by samitc** [comment]
But there is available formats.
If I do -F it is shows me there is one format (number 0) and if instead of best I am write 0 it download the video successfully.

**Comment by samitc** [comment]
But when I download the video it writes the file size in the progress bar.

**Comment by dstftw** [comment]
Again: It's not available as metadata and until you start downloading
