### ISSUE TITLE
Extract video and audio using the python package

### ISSUE THREAD

**Issue by revolter** [rg3/youtube-dl#18494]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

How can I get an URL to the best video and audio format using the python package? I am currently using:

```py
import youtube_dl

input_link = 'https://www.youtube.com/watch?v=rvWf62D1jw0'

with youtube_dl.YoutubeDL() as yt_dl:
    video_info = yt_dl.extract_info(input_link, download=False)
```

I can't find documentation for the returned dictionary, so, for some URLs, there is a top level `url` key returned, for some, there isn't. What is the difference between `formarts` and `requested_formats`? How could I know if the URL from a format in one of the mentioned lists contains video **and** audio? As, for the example link, some only contain video while some only contain audio. If I request them to get merged, how will the file be returned? I would like to avoid writing it to disk at all, even in a temporary file.

**Comment by dstftw** [comment]
1. https://github.com/rg3/youtube-dl#embedding-youtube-dl
2. `formats` contains all formats, `requested_formats` - formats selected with format selector.
3. By not having `acodec` or `vcodec` set to '`none'`.
4. File will not be returned.
