### ISSUE TITLE
How to annotate download cold?

### ISSUE THREAD

**Issue by ZhangKuixun** [rg3/youtube-dl#18496]
I only need to get url

**Comment by ZhangKuixun** [comment]
@dstftw

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient

**Comment by ZhangKuixun** [comment]
@dstftw Sorry, The main purpose of my use youtube-dl to get video url of webpage. but I don't need download cold of youtube-dl. When `import youtube_dl` initializes youtube-dl, it does not need to initialize downloads and parsing videos.
