### ISSUE TITLE
 ytdl_hook: failed to parse JSON data: error  on multiple domains

### ISSUE THREAD

**Issue by cirrusUK** [rg3/youtube-dl#18518]
### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

...

debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.09
[debug] Python version 3.7.1 (CPython) - Linux-4.19.6-1-ck-nehalem-x86_64-with-arch
[debug] exe versions: ffmpeg n4.1, ffprobe n4.1, phantomjs 18, rtmpdump 2.4
[debug] Proxy map: {}

<end of log>
```


Hi thanks for awesome code,
  I use fully updated Archlinux if i rollback to youtube-dl-2018.12.03-2-any.pkg.tar.xz  then urls such as these will play but no longer with youtube-dl and mpv/cvlc

http://vidoza.net/fv3be6r2ctpt
https://vev.io/9jrj8m9jx8og
http://vidup.io/qdmy1jvgjmz9
https://streamplay.to/xvvq99m5y9sx

and many many more shown here https://ww1.watchseries-online.be/last-350-episodes
i am able to play those videos with 'mpv [URL]' subsequent versions of youtube-dl throw up 

...

 cirrus@hawker64 > mpv 'http://vidoza.net/fv3be6r2ctpt'                                                                    
   cplayer: Auto-loading profile 'protocol.http'
   cplayer: Playing: http://vidoza.net/fv3be6r2ctpt
 ytdl_hook: failed to parse JSON data: error 
   cplayer: Failed to recognize file format.
   cplayer: 
   cplayer: 
   cplayer: Exiting... (Errors when loading file)

...

This happens on multiple sites which im guessing is either a bug or support has been dropped for all these domains at once.
For now my workaround is
  

>  warning: downgrading package youtube-dl (2018.12.09-1 => 2018.12.03-2)

and adding youtube-dl to pacman.conf  IgnorePkg 
i have not submitted bug report to archlinux as yet so
please advise if this is an arch packaging faux pas, or another PEBKAC
all URL's play in browser.
regards.

**Comment by remitamine** [comment]
https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free

**Comment by cirrusUK** [comment]
they all worked until recent update so i'm assuming support has been discontinued ?
