### ISSUE TITLE
stuck with udemy: bug or site support request?

### ISSUE THREAD

**Issue by therom123** [rg3/youtube-dl#18527]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)

I was used to download courses from Udemy, now it only downloads one video
- Playlist: https://www.udemy.com/deep-dive-the-openstack-cloud/learn/v4/t/lecture/7748408
It downloads only the first video in the playlist, but not all remaining videos:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', 'http
s://www.udemy.com/deep-dive-the-openstack-cloud/learn/v4/t/lecture/7748408']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.12.09
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[udemy] Downloading login popup
[udemy] Logging in
[udemy] 7748408: Downloading webpage
[udemy] 7748408: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://udemy-assets-on-demand.udemy.com/2018-03
-07_00-11-50-fadbaf98501c9f26037c0d3da7c11866/WebHD_720p.mp4?nva=20181214190733&
token=0f413cdc8981e7932536a'
[download] Destination: Introduction-11582812.mp4
[download] 100% of 5.93MiB in 00:06

- Second video: https://www.udemy.com/deep-dive-the-openstack-cloud/learn/v4/t/lecture/7748416
It downloads the second video, but not all remaining videos:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', 'http
s://www.udemy.com/deep-dive-the-openstack-cloud/learn/v4/t/lecture/7748416']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.12.09
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[udemy] Downloading login popup
[udemy] Logging in
[udemy] 7748416: Downloading webpage
[udemy] 7748416: Downloading lecture JSON
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://udemy-assets-on-demand.udemy.com/2017-08
-19_02-51-00-56e112888897eccc8a9858dd99da9f77/WebHD_720p.mp4?nva=20181214193232&
token=06c467487f9953a94185c'
[download] Destination: Instructor Bio-9318052.mp4
[download] 100% of 4.74MiB in 00:05

**Comment by therom123** [comment]
Sent credentials to dstftw gmail address
Thank you

**Comment by dstftw** [comment]
It's a lecture URL. To download whole course you should use course URL.
