### ISSUE TITLE
Not working for ardmediathek.de

### ISSUE THREAD

**Issue by mdosch** [rg3/youtube-dl#18539]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
youtube-dl --verbose https://www.ardmediathek.de/ard/player/Y3JpZDovL25kci5kZS81ZGIxY2ZmNC04MGEzLTRlZDYtOWI5MC1kOGE1NjFmMDNhMzI/der-kopf
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.ardmediathek.de/ard/player/Y3JpZDovL25kci5kZS81ZGIxY2ZmNC04MGEzLTRlZDYtOWI5MC1kOGE1NjFmMDNhMzI/der-kopf']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.09
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-3-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0.3-1, ffprobe 4.0.3-1
[debug] Proxy map: {}
[ARD:mediathek] der-kopf: Downloading webpage
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/ard.py", line 219, in _real_extract
    r'/play/(?:config|media)/(\d+)', webpage, 'media id')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

Changing the URL from www.ardmediathek.de to classic.ardmediathek.de as suggested in #18473 didn't help.

**Comment by pixelkritzel** [comment]
@mdosch did you just replaced the www with classic? I whink you have to search for the video at classic.ardmediathek.de again
