### ISSUE TITLE
CBC Audio Delay and VFR

### ISSUE THREAD

**Issue by digitalhybrid** [rg3/youtube-dl#18543]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

All files downloaded from CBC have a consistent audio delay of 33ms. Is something that youtube-dl can fix/adjust on the fly?

Also, some video files are captured with variable frame rates, while others have a set frame rate of 29.97fps. Again, is this something that youtube-dl can fix/adjust on the fly?

Using MkvToMp4, all this can be adjusted and fixed resulting in a usable video file, but it would be good to not have to go through the repair process every time something is downloaded from CBC.

**Comment by dstftw** [comment]
You can use `--exec` to call arbitrary command line on the final file.
