### ISSUE TITLE
Any way to download a video that is geo-restricted in *all* countries?

### ISSUE THREAD

**Issue by mariomadproductions** [rg3/youtube-dl#18552]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information
According to [this tool](https://polsy.org.uk/stuff/ytrestrict.cgi), these two videos
https://www.youtube.com/watch?v=tEA5H_Y8IbE
https://www.youtube.com/watch?v=UdGs_AM-rx8
are restricted in all countries. Is there some backdoor way of viewing them anyway?

**Comment by dstftw** [comment]
No such backdoor.
