### ISSUE TITLE
Cannot download playlist from Crunchyroll

### ISSUE THREAD

**Issue by luigirovatti** [rg3/youtube-dl#18554]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\leo\Downloads>youtube-dl --verbose --geo-bypass-country US --write-sub --sub-lang "enUS" --sub-format "ass" -f "(bestvideo[height<=480]+bestaudio/best[height<=480])[format_id*=jaJP]" --cookies cookies.txt --playlist-start 1 "https://www.crunchyroll.com/bleach"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--geo-bypass-country', 'US', '--write-sub', '--sub-lang', 'enUS', '--sub-format', 'ass', '-f', '(bestvideo[height<=480]+bestaudio/best[height<=480])[format_id*=jaJP]', '--cookies', 'cookies.txt', '--playlist-start', '1', 'https://www.crunchyroll.com/bleach']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91999-g148a21611d, ffprobe N-91999-g148a21611d
[debug] Proxy map: {}
[debug] Using fake IP 3.250.103.192 (US) as X-Forwarded-For.
[crunchyroll:playlist] bleach: Downloading webpage
[download] Downloading playlist: Bleach
[crunchyroll:playlist] playlist Bleach: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: Bleach
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I've tried to download videos from Crunchyroll but they aren't detected by youtube-dl, as mentioned in the above log. I've tried to bypass geo-restriction, to modify URL, to set up resolution, to add '--cookies. cookies.txt' but without result. The videos **must** be there because on http://vrv.co they are there, it's a mirror of Crunchyroll. Let me  know what you think of this.

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by remitamine** [comment]
```
youtube-dl https://www.crunchyroll.com/bleach
[crunchyroll:playlist] bleach: Downloading webpage
[download] Downloading playlist: Bleach
[crunchyroll:playlist] playlist Bleach: Collected 366 video ids (downloading 366 of them)
[download] Downloading video 1 of 366
[crunchyroll] 543611: Downloading webpage
[crunchyroll] 543611: Downloading audio-jaJP m3u8 information
[crunchyroll] 543611: Downloading audio-jaJP-hardsub-enUS m3u8 information
[crunchyroll] 543611: Downloading audio-jaJP-hardsub-esLA m3u8 information
[crunchyroll] 543611: Downloading audio-jaJP-hardsub-ptBR m3u8 information
[crunchyroll] 543611: Downloading audio-jaJP m3u8 information
[crunchyroll] 543611: Downloading media info
[download] Destination: Bleach Season 1 Episode 1 – Untitled-543611.mp4
...
```
