### ISSUE TITLE
codewithmosh http 404 error

### ISSUE THREAD

**Issue by arkos** [rg3/youtube-dl#18571]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--batch-file=/home/ultradmin/codewithmosh-courses.txt', u'--max-sleep-interval', u'120', u'-o', u'~/Downloads/online-courses/codewithmosh/%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s']
[debug] Command-line args: [u'--config-location', u'/home/ultradmin/youtube-dl.codewithmosh.conf', u'--verbose']
[debug] Batch file urls: [u'https://codewithmosh.com/courses/enrolled/222293']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.17
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-12-generic-x86_64-with-Ubuntu-18.10-cosmic
[debug] exe versions: ffmpeg 4.0.2-2, ffprobe 4.0.2-2
[debug] Proxy map: {}
[generic] 222293: Requesting header
[redirect] Following redirect to https://codewithmosh.com/p/asp-net-mvc
[generic] asp-net-mvc: Requesting header
WARNING: Falling back on generic information extractor.
[generic] asp-net-mvc: Downloading webpage
[generic] asp-net-mvc: Extracting information
[TeachableCourse] Downloading codewithmosh.com login page
[TeachableCourse] Logging in to codewithmosh.com
[TeachableCourse] asp-net-mvc: Downloading webpage
[download] Downloading playlist: The Complete ASP.NET MVC 5 Course
[TeachableCourse] playlist The Complete ASP.NET MVC 5 Course: Collected 128 video ids (downloading 128 of them)
[download] Downloading video 1 of 128
[Teachable] Downloading codewithmosh.com login page
[Teachable] Logging in to codewithmosh.com
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "./youtube-dl/youtube_dl/extractor/common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Unable to download any course on codewithmosh.com (teachable). Tried different courses. It downloads fine a single lesson, but not the whole course.

**Comment by dstftw** [comment]
For any work on the issue you must provide reproducible environment.

**Comment by arkos** [comment]
What kind of reproducible environment do you mean? I've provided everything that is mentioned in the question template including the --verbose output which lists the command parameters I've used and environment details. Not sure what else is required.

**Comment by arkos** [comment]
> For any work on the issue you must provide reproducible environment.

I am still experiencing this issue, can you tell me what reproducible environment you are talking about? Thanks.

**Comment by Denis4yk** [comment]
Same here :(
