### ISSUE TITLE
4K chosen instead of 8K video

### ISSUE THREAD

**Issue by fudfucker** [rg3/youtube-dl#18570]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

Isn't youtube-dl supposed to, by default, download the best quality available?
If I run this command:
```
youtube-dl https://www.youtube.com/watch?v=M3btuZ_KuPU
```
youtube-dl downloads 4K (format code 313) video instead of the maximum quality of 8K (format code 272). Isn't the 8K video higher quality?
```
[youtube] M3btuZ_KuPU: Downloading webpage
[youtube] M3btuZ_KuPU: Downloading video info webpage
[info] Available formats for M3btuZ_KuPU:
format code  extension  resolution note
249          webm       audio only DASH audio   58k , opus @ 50k, 1.30MiB
250          webm       audio only DASH audio   85k , opus @ 70k, 1.81MiB
171          webm       audio only DASH audio   99k , vorbis@128k, 2.11MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 3.13MiB
251          webm       audio only DASH audio  161k , opus @160k, 3.59MiB
278          webm       256x144    144p  109k , webm container, vp9, 30fps, video only, 1.60MiB
160          mp4        256x144    144p  122k , avc1.4d400c, 30fps, video only, 2.21MiB
242          webm       426x240    240p  244k , vp9, 30fps, video only, 3.16MiB
133          mp4        426x240    240p  262k , avc1.4d4015, 30fps, video only, 4.91MiB
243          webm       640x360    360p  453k , vp9, 30fps, video only, 6.04MiB
134          mp4        640x360    360p  485k , avc1.4d401e, 30fps, video only, 6.59MiB
244          webm       854x480    480p  822k , vp9, 30fps, video only, 10.96MiB
135          mp4        854x480    480p 1014k , avc1.4d401f, 30fps, video only, 12.73MiB
247          webm       1280x720   720p 1686k , vp9, 30fps, video only, 22.08MiB
136          mp4        1280x720   720p 1831k , avc1.4d401f, 30fps, video only, 22.90MiB
248          webm       1920x1080  1080p 3002k , vp9, 30fps, video only, 38.78MiB
137          mp4        1920x1080  1080p 3165k , avc1.640028, 30fps, video only, 41.34MiB
271          webm       2560x1440  1440p 8551k , vp9, 30fps, video only, 104.23MiB
272          webm       7680x4320  4320p 14812k , vp9, 30fps, video only, 198.76MiB
313          webm       3840x2160  2160p 18369k , vp9, 30fps, video only, 234.99MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 1.49MiB
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2, 4.18MiB
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 12.96MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 13.80MiB
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
```

**Comment by Hrxn** [comment]
> 272          webm       7680x4320  4320p 14812k , vp9, 30fps, video only, 198.76MiB
313          webm       3840x2160  2160p 18369k , vp9, 30fps, video only, 234.99MiB

Can you confirm that these are indeed the correct sizes (or bitrates) for the video stream?
Because the 4K stream has a higher bitrate and size, which does not really make sense, but would explain the selection by youtube-dl.

**Comment by dstftw** [comment]
Bitrate is preferred over height. This is expected behavior for now.

**Comment by sidvud98** [comment]
@aghtragh  how are you ablto download in 4k. I am only getting 720p.
