### ISSUE TITLE
Trying to download playlist -> ERROR: Unable to download JSON metadata: HTTP Error 503: Service Unavailable (caused by HTTPError())

### ISSUE THREAD

**Issue by ejgh** [rg3/youtube-dl#18574]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl --verbose -f 140 --prefer-ffmpeg --youtube-include-dash-manifest --no-post-overwrites --write-thumbnail -o '%(autonumber)s-%(title)s---%(id)s.%(ext)s' --no-mtime -k --abort-on-error --audio-format mp3 --audio-quality 128K -x  -i 'https://www.youtube.com/watch?v=-4vcYSBy9Iw&list=UUp5SmdUyBVUpFHEU_ekljCA'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'140', u'--prefer-ffmpeg', u'--youtube-include-dash-manifest', u'--no-post-overwrites', u'--write-thumbnail', u'-o', u'%(autonumber)s-%(title)s---%(id)s.%(ext)s', u'--no-mtime', u'-k', u'--abort-on-error', u'--audio-format', u'mp3', u'--audio-quality', u'128K', u'-x', u'-i', u'https://www.youtube.com/watch?v=-4vcYSBy9Iw&list=UUp5SmdUyBVUpFHEU_ekljCA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.17
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-140-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15-0ubuntu0.16.04.1, ffprobe 2.8.15-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist UUp5SmdUyBVUpFHEU_ekljCA - add --no-playlist to just download video -4vcYSBy9Iw
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading webpage
[download] Downloading playlist: Uploads from TheNickNicola
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #1
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #2
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #3
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #4
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #5
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #6
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #7
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #8
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #9
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #10
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #11
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #12
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #13
[youtube:playlist] UUp5SmdUyBVUpFHEU_ekljCA: Downloading page #14
ERROR: Unable to download JSON metadata: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/ej/bin/youtube-dl/youtube_dl/extractor/common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/ej/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

$ 
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I'm trying to download (and extract audio from)  an - admittedly - lengthy playlist (https://www.youtube.com/watch?v=-4vcYSBy9Iw&list=UUp5SmdUyBVUpFHEU_ekljCA). Displaying in the browser works OK, as does playing any video on the list. When trying to fetch the videos on the playlist via youtube-dl though, I get the error mentioned in the subject above.

Thanks much in advance for your help,
-ejgh

**Comment by dstftw** [comment]
Most likely temporary youtube side issue.
