### ISSUE TITLE
[Crunchyroll] youtube-dl does not extract special episodes output

### ISSUE THREAD

**Issue by percheperche** [rg3/youtube-dl#18576]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', 'C:\\Users\\USERNAME\\Desktop\\%(series)s %(episode_number)s.%(ext)s', '-f', 'best[height=360]', 'https://www.crunchyroll.com/inferno-cop/inferno-cop-fact-file-01-669837']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-92722-gf22fcd4483, ffprobe N-92722-gf22fcd4483, phantomjs 2.1.1
[debug] Proxy map: {}
[crunchyroll] 669837: Downloading webpage
[crunchyroll] 669837: Downloading audio-jaJP-hardsub-frFR m3u8 information
[crunchyroll] 669837: Downloading audio-jaJP m3u8 information
[crunchyroll] 669837: Downloading audio-jaJP-hardsub-deDE m3u8 information
[crunchyroll] 669837: Downloading audio-jaJP-hardsub-enUS m3u8 information
[crunchyroll] 669837: Downloading audio-jaJP-hardsub-itIT m3u8 information
[crunchyroll] 669837: Downloading audio-jaJP-hardsub-ptBR m3u8 information
[crunchyroll] 669837: Downloading media info
[debug] Invoking downloader on 'https://v.vrv.co/evs/48a691f990edba9c35581bb0e2a520bb/assets/sssi0wynuqj21uz_2144173.mp4/index-v1-a1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvNDhhNjkxZjk5MGVkYmE5YzM1NTgxYmIwZTJhNTIwYmIvYXNzZXRzL3Nzc2kwd3ludXFqMjF1el8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTQ1MjQzNDk5fX19XX0_&Signature=nxxu64goRsn~SH2XDJ16Wo0U5FmrAP-uWIVCmcTO0NNiXGCik9vAWEr~wu1~LKxzQW79MjBUlFwdQhw66sdva9yX1QuCeGyFv3cKq4MQvoXji48CdVxi6I8-9bw3e6Jep~cjb-v5y8EmlshVojYlkjq48IjtpG0z6jPRkDfIfgiUpkFhjqvm-p3-PvWccqhRX5UJF2S0nFkWSvLiJ25IjC1eW1gBtK6RthRNG5V1mn3WzlpsCDjdtFcGuI6EiZrQDYR8tblODmwPb8IuMrBqnP2WPZ3q56xWcIlpMRmOT8AkO2pbZhrLMCNwo5Pq3a0t1DjHAR9HtVuUfJezH7d2mA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA'
[download] Destination: C:\Users\USERNAME\Desktop\Inferno Cop NA.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept-Language: en-us,en;q=0.5
[ffmpeg] Downloaded 1536820 bytes
[download] 100% of 1.47MiB in 00:03
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.crunchyroll.com/inferno-cop/inferno-cop-fact-file-01-669837
- Single video: https://www.crunchyroll.com/91-days/episode-75-brief-candle-778618

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

youtube-dl doesn't extract special episodes (example: "7.5", "Fact File 10") so the output'll end with "NA".
Here some URL examples
https://www.crunchyroll.com/91-days/episode-75-brief-candle-778618
https://www.crunchyroll.com/inferno-cop/inferno-cop-fact-file-01-669837

**Comment by dstftw** [comment]
Both videos don't provide valid episode number thus `NA`.

**Comment by percheperche** [comment]
What is a valid episode number according to you? I can """understand""" not considering "Fact File 1" a valid output, but "7.5" definitely is. I don't think is too hard to add "7.5" or similar numbers as valid.
