### ISSUE TITLE
Errors With Long Youtube Playlist

### ISSUE THREAD

**Issue by sirinath** [rg3/youtube-dl#1857]
I am getting the following errors with the following YT playlist.

C:\Downloads>youtube-dl -i -w -c http://www.youtube.com/playlist?list=PLF6CAC63C
615DB881
[youtube:playlist] PLF6CAC63C615DB881: Downloading page #1
[download] Downloading playlist: Introduction to the Art of Programming Using Sc
ala (Part II)
[youtube:playlist] playlist 'Introduction to the Art of Programming Using Scala
(Part II)': Collected 142 video ids (downloading 142 of them)

....
....
....

[download] Downloading video #137 of 142
[youtube] moycaoz0NTg: Downloading video webpage
ERROR: Unable to download video webpage: <urlopen error [Errno 11001] getaddrinf
o failed>
[download] Downloading video #138 of 142
[youtube] sjxGjiRqMR8: Downloading video webpage
ERROR: Unable to download video webpage: <urlopen error [Errno 11001] getaddrinf
o failed>
[download] Downloading video #139 of 142
[youtube] UKrcHiUOsFo: Downloading video webpage
ERROR: Unable to download video webpage: <urlopen error [Errno 11001] getaddrinf
o failed>
[download] Downloading video #140 of 142
[youtube] hbET6D0G06k: Downloading video webpage
ERROR: Unable to download video webpage: <urlopen error [Errno 11001] getaddrinf
o failed>
[download] Downloading video #141 of 142
[youtube] Ztgt7ki--70: Downloading video webpage
ERROR: Unable to download video webpage: <urlopen error [Errno 11001] getaddrinf
o failed>
[download] Downloading video #142 of 142
[youtube] 3r8Rzr08oSU: Downloading video webpage
ERROR: Unable to download video webpage: <urlopen error [Errno 11001] getaddrinf
o failed>

**Comment by dstftw** [comment]
If you still experience this problem open a new issue with `--verbose` output.
