### ISSUE TITLE
[acast] fails to get list of episodes

### ISSUE THREAD

**Issue by ssixty** [rg3/youtube-dl#18587]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--ignore-config', 'https://play.acast.com/s/filmstobeburiedwith']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.17
[debug] Python version 3.5.3 (CPython) - Linux-4.4.52-1.el7xen.x86_64-x86_64-with-debian-9.6
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[generic] filmstobeburiedwith: Requesting header
WARNING: Falling back on generic information extractor.
[generic] filmstobeburiedwith: Downloading webpage
[generic] filmstobeburiedwith: Extracting information
ERROR: Unsupported URL: https://play.acast.com/s/filmstobeburiedwith
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/generic.py", line 3323, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://play.acast.com/s/filmstobeburiedwith
```

---

### Description of your *issue*, suggested solution and other information

Was working until recently on the old show URL, now fails to extract list of episodes.

 I see that acast changed their URLs recently, I was previously using https://www.acast.com/filmstobeburiedwith (which now redirects to https://play.acast.com/s/filmstobeburiedwith )

Individual show pages download OK, e.g. https://play.acast.com/s/filmstobeburiedwith/danebaptiste-filmstobeburiedwithwithbrettgoldstein-23 .

**Comment by o5729** [comment]
found the fix https://www.youtube.com/watch?v=dQw4w9WgXcQ
