### ISSUE TITLE
rmcdecouverte.bfmtv.com extractor is broken

### ISSUE THREAD

**Issue by gnomelibre** [rg3/youtube-dl#18595]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v https://rmcdecouverte.bfmtv.com/le-mont-saint-michel/program_3587/
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://rmcdecouverte.bfmtv.com/le-mont-saint-michel/program_3587/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.17
[debug] Python version 3.7.1 (CPython) - Linux-4.19.8-300.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.3, ffprobe 4.0.3
[debug] Proxy map: {}
[generic] program_3587: Requesting header
WARNING: Falling back on generic information extractor.
[generic] program_3587: Downloading webpage
[generic] program_3587: Extracting information
ERROR: Unsupported URL: https://rmcdecouverte.bfmtv.com/le-mont-saint-michel/program_3587/
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 791, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/generic.py", line 3298, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://rmcdecouverte.bfmtv.com/le-mont-saint-michel/program_3587/
```

---

### Description of your *issue*, suggested solution and other information

The RMC Découverte website was redesigned a few days ago and since then, the extractor no longer works.

**Comment by moimadmax** [comment]
I confirm the problem and i've found a way to download the file.
Display the source code and serach for data-video-id. You will find `data-video-id="5980028585001"`
The 5980028585001 is the video ID on the brightcove platform so if you use the brighcove url it will works.
`youtube-dl http://players.brightcove.net/1969646226001/default_default/index.html?videoId=5980028585001`

The rmcdecouverte.py extractor has to be rewrited. I've tried to have a look but it's a complicated framework to learn for me and I miss times. 
I'm pretty shure that the _VALID_URL variable has to change, and youtube-dl can recognize the site.

**Comment by nazmifr** [comment]
This is not a fix of youtube-dl but meanwhile javascript can easily grab the video id and generate the url automatically using @moimadmax method (mentioned here also #24862 ).

Here is a simple script you can copy in the javascript console (F12 > console in firefox) to get the url and youtube-dl command to get your video (check my project [here](https://github.com/nazmifr/BFMtoURL) for a js bookmarklet and shell implementation to use directly in the shell until youtubedl gets fixed)

```

	let iddecomptea = document.querySelectorAll('[data-account]')[0];
	if (iddecomptea === undefined){
        var iddecompte = document.querySelectorAll('[accountid]')[0].getAttribute("accountid");
    } else {
        var iddecompte = iddecomptea.getAttribute("data-account");
    }
    let iddevideo = document
        .querySelectorAll('[data-video-id]')[0]
        .getAttribute("data-video-id");
    let urldevideo = "http://players.brightcove.net/" + iddecompte + "/default_default/index.html?videoId=" + iddevideo;
    alert('youtube-dl --write-info-json ' + urldevideo + '\r\n\r\nURL:\r' + urldevideo);


```
