### ISSUE TITLE
how to escape video id with "-sEi_iqYFuU" 

### ISSUE THREAD

**Issue by nardev** [rg3/youtube-dl#18627]
When youtube-dl is extracting the URL ID it works fine

`youtube-dl https://youtu.be/-sEi_iqYFuU`

But simple

`youtube-dl -sEi_iqYFuU`

recognizes the -s... as starting of options.

Wondering if that could be avoided?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#how-do-i-download-a-video-starting-with-a--
