### ISSUE TITLE
zee5.com videos downloading via 9xbuddy.org working

### ISSUE THREAD

**Issue by VarunSaiTeja** [rg3/youtube-dl#18623]
Need support to download videos from zee5.com
https://www.zee5.com/

youtube-dl not working right now

But I am able to download it from 9xbuddy.org

Please try to develop youtube-dl to support to download videos from zee5.com

Latest version i used youtube-dl 2018.12.17

**Comment by donnayarbrough** [comment]
Here is a working method to download  zee5 videos with the help of Allavsoft: https://allavsoft.com/how-to/download-zee5-videos.html
