### ISSUE TITLE
Why is ytdl still not downloading audio?

### ISSUE THREAD

**Issue by Zachary24** [rg3/youtube-dl#18628]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

`best` downloads both audio and video, muxes them in mp4, however, rather than downloading the BEST quality, it chooses to get a `640x360` copy. Which doesn't make any sense, but okay. 137+140 works perfectly, for videos that qualify, when downloading playlists with 2000-3000 videos it's practically impossible to match that, on the other hand the standard `bestvideo+bestaudio/best` get's the highest quality, yet ignores `[ext=mp4]` and continues to mux it into an mkv. On the otherhand, the ideal `137/248/136+140/best` gets audio for very few and doesn't get audio for most.

`137/248/136+140/best` Gets the audio for (youtube) videos like: HGobiQPPbAA , zu_MjWjT45Q , 

While it doesn't get the audio for: T4FAg5A4wQk , MTY0A8tmPO0 , 9AQIm4fEJUM

Some renditions of `137/248/136+140/best` i've tried:
137/248/136+140
137/248/136+140/best/best
137/248/136/bestvideo+140/bestaudio
137/248/136/bestvideo+140/bestaudio/best

The documentation is very unclear on why `137/248+140` gets 248 ONLY if 137 isn't available + 140, and why `bestvideo+bestaudio/best` gets bestvideo + bestaudio OR the `best` version, as there both the exact same formatting, just different media types: (video + audio / next audio) and 
(video + audio / nextvideoANDaudio) if that makes any sense

**Comment by dstftw** [comment]
Bother to at least read [FAQ](https://github.com/rg3/youtube-dl#format-selection).
