### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by awgiedawgie** [rg3/youtube-dl#18620]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**
***Cannot check this box because of the problem I describe below***

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
***not applicable***

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

I tried downloading version 2018.12.17, but I cannot access the file once downloaded. Windows Defender immediately quarantines it for a Trojan. I have no trouble using the previous version. Any suggestions?

![2018-12-23 10](https://user-images.githubusercontent.com/23329656/50387465-e2381f00-06ca-11e9-8706-a0cc70edd97f.png)

**Comment by rautamiekka** [comment]
Although Defender basically can't be trusted, it does detect some serious shit, and you just caught yourself a serious Trojan that's infected your machine, specifically some EXE files, and it so happens Defender knows it infected `youtube-dl.exe`.

**Comment by dstftw** [comment]
https://www.virustotal.com/url/6160ba0953241abd0d34592f6f233cbcb464591254727d3919f4fa7c17070347/analysis/
