### ISSUE TITLE
Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1

### ISSUE THREAD

**Issue by ianni67** [rg3/youtube-dl#18633]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.12.17
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by ianni67** [comment]
I got the following error message:

> youtube-dl -t -v https://www.youtube.com/watch?v=kIvLEpAvwhM
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-t', u'-v', u'https://www.youtube.com/watch?v=kIvLEpAvwhM']
> WARNING: --title is deprecated. Use -o "%(title)s-%(id)s.%(ext)s" instead.
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2018.12.17
> [debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-42-generic-x86_64-with-neon-18.04-bionic
> [debug] exe versions: avconv 3.4.4-0ubuntu0.18.04.1, avprobe 3.4.4-0ubuntu0.18.04.1, ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
> [debug] Proxy map: {}
> [youtube] kIvLEpAvwhM: Downloading webpage
> [youtube] kIvLEpAvwhM: Downloading video info webpage
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {18} signature length 40.41, html5 player None
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {36} signature length 40.41, html5 player None
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {17} signature length 40.41, html5 player None
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {136} signature length 40.41, html5 player None
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {135} signature length 40.41, html5 player None
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {134} signature length 40.41, html5 player None
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {133} signature length 40.41, html5 player None
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {160} signature length 40.41, html5 player None
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {140} signature length 40.41, html5 player None
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {171} signature length 40.41, html5 player None
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {249} signature length 40.41, html5 player None
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {250} signature length 40.41, html5 player None
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {251} signature length 40.41, html5 player None
> [youtube] kIvLEpAvwhM: Downloading MPD manifest
> [youtube] kIvLEpAvwhM: Downloading MPD manifest
> [debug] Default format spec: bestvideo+bestaudio/best
> WARNING: Requested formats are incompatible for merge and will be merged into mkv.
> [debug] Invoking downloader on u'https://r5---sn-8vq54voxpu-4jve.googlevideo.com/videoplayback/id/908bcb12902fc213/itag/136/source/yt_otf/requiressl/yes/ei/zgsiXKWMIsbX7gPnsqHoCg/ms/au,rdu/pl/25/initcwndbps/1120000/mv/m/usequic/no/mm/31,29/mn/sn-8vq54voxpu-4jve,sn-hpa7znsz/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1458420268816539/mt/1545735024/fvip/5/disable_polymer/true/ip/5.89.243.186/ipbits/0/expire/1545756718/sparams/ip,ipbits,expire,id,itag,source,requiressl,ei,ms,pl,initcwndbps,mv,usequic,mm,mn,ratebypass,mime,otfp,otf,lmt/signature/8F54F61F58469EA823D7FFB9D1D93D81AA7E7E38.22D01A35065FA7A9BACA313FC4754F5DC88D80D3/key/dg_yt0/'
> [dashsegments] Total fragments: 741
> [download] Destination: Stellardrone - A Message to Shankra Festival 2016-kIvLEpAvwhM.f136.mp4
> [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
> [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
> [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
> [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
> [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
> [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
> [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
> [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
> [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
> [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
> ERROR: giving up after 10 fragment retries
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 48, in real_download
>     success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
>   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/fragment.py", line 102, in _download_fragment
>     'http_headers': headers or info_dict.get('http_headers'),
>   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 364, in download
>     return self.real_download(filename, info_dict)
>   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 341, in real_download
>     establish_connection()
>   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
>     ctx.data = self.ydl.urlopen(request)
>   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2212, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 435, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python2.7/urllib2.py", line 473, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> HTTPError: HTTP Error 404: Not Found

**Comment by dstftw** [comment]
Format 136 is not availabe at youtube side.

**Comment by ianni67** [comment]
Please, articulate more in detail your explanation. Why a missing format is requested by the script by default and how can I determine the correct value for the -f parameter?

**Comment by alik604** [comment]
Here is how a solved the issue 

`youtube-dl -f best https://www.youtube.com/watch?v=ZvccY97SZX0`
