### ISSUE TITLE
Why is ytdl still not downloading audio?

### ISSUE THREAD

**Issue by Zachary24** [rg3/youtube-dl#18630]
Make sure you are using the latest version: run youtube-dl --version and ensure your version is 2018.12.17. If it's not, read this FAQ entry and update. Issues with outdated version will be rejected.
  I've verified and I assure that I'm running youtube-dl 2018.12.17
Before submitting an issue make sure you have:
  At least skimmed through the README, most notably the FAQ and BUGS sections
  Searched the bugtracker for similar issues including closed ones
  Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
What is the purpose of your issue?
  Bug report (encountered problems with youtube-dl)
  Site support request (request for adding support for a new site)
  Feature request (request for a new functionality)
  Question
  Other
Description of your issue, suggested solution and other information
best downloads both audio and video, muxes them in mp4, however, rather than downloading the BEST quality, it chooses to get a 640x360 copy. Which doesn't make any sense, but okay. 137+140 works perfectly, for videos that qualify, when downloading playlists with 2000-3000 videos it's practically impossible to match that, on the other hand the standard bestvideo+bestaudio/best get's the highest quality, yet ignores [ext=mp4] and continues to mux it into an mkv. On the otherhand, the ideal 137/248/136+140/best gets audio for very few and doesn't get audio for most.

137/248/136+140/best Gets the audio for (youtube) videos like: HGobiQPPbAA , zu_MjWjT45Q ,

While it doesn't get the audio for: T4FAg5A4wQk , MTY0A8tmPO0 , 9AQIm4fEJUM

Some renditions of 137/248/136+140/best i've tried:
137/248/136+140
137/248/136+140/best/best
137/248/136/bestvideo+140/bestaudio
137/248/136/bestvideo+140/bestaudio/best

The documentation is very unclear on why 137/248+140 gets 248 ONLY if 137 isn't available + 140, and why bestvideo+bestaudio/best gets bestvideo + bestaudio OR the best version, as there both the exact same formatting, just different media types: (video + audio / next audio) and
(video + audio / nextvideoANDaudio) if that makes any sense

EDIT: If you read the entire post you'd know I did read the Format Selection part, but it simply sucks. I'm sorry your feelings were hurt. But it's the truth. I asked for help, help that is NOT specified in the "faq" the logic of the question matches the logic of the output, it's that simple. buddy.

**Comment by dstftw** [comment]
>best downloads both audio and video, muxes them in mp4

Totally wrong. Read FAQ:
>best: Select the best quality format represented by a single file with video and audio.
>represented by a single file with video and audio
>**single file with video and audio**

>The documentation is very unclear on why 137/248+140 gets 248 ONLY if 137

Are you trolling or what? Again, bother to read FAQ on what does `/` mean:
>If you want to download multiple videos and they don't have the same formats available, you can specify the order of preference using slashes. Note that slash is left-associative, i.e. formats on the left hand side are preferred, for example -f 22/17/18 will download format 22 if it's available, otherwise it will download format 17 if it's available, otherwise it will download format 18 if it's available, otherwise it will complain that no suitable formats are available for download.
