### ISSUE TITLE
[SUGGESTION] Print warning when ffmpeg is not installed

### ISSUE THREAD

**Issue by NightMachinary** [rg3/youtube-dl#18648]
It took me quite a while to notice youtube-dl is downloading low-quality videos on my new box (which didn’t have ffmpeg), and that not having ffmpeg is the cause. (As it downloads the best single file option.)
I suggest printing a warning saying not having ffmpeg will result in lower quality downloads.

**Comment by dstftw** [comment]
This will result in permanent unnecessary warning in cases when ffmpeg is intentionally not installed. So, no.

**Comment by NightMachinary** [comment]
We can just print one the first time and on installation.
