### ISSUE TITLE
[Crunchyroll] youtube-dl does not extract special episodes output

### ISSUE THREAD

**Issue by percheperche** [rg3/youtube-dl#18646]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best[height=360]', '-o', 'C:\\Users\\USERNAME\\Desktop\\%(series)s %(episode_number)s.%(ext)s', 'https://www.crunchyroll.com/91-days/episode-75-brief-candle-778618', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-92795-gcdbf8847ea, ffprobe N-92795-gcdbf8847ea, rtmpdump 2.5
[debug] Proxy map: {}
[crunchyroll] 778618: Downloading webpage
[crunchyroll] 778618: Downloading audio-enUS m3u8 information
[crunchyroll] 778618: Downloading audio-enUS-hardsub-enUS m3u8 information
[crunchyroll] 778618: Downloading media info
[debug] Invoking downloader on 'https://v.vrv.co/evs/b4470b5f647ed3b00ea7f4d20affe37f/assets/abafa33f3c9e2368878d1ed81f82004b_3573574.mp4/index-v1-a1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvYjQ0NzBiNWY2NDdlZDNiMDBlYTdmNGQyMGFmZmUzN2YvYXNzZXRzL2FiYWZhMzNmM2M5ZTIzNjg4NzhkMWVkODFmODIwMDRiXyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NDU5Mjg1NjF9fX1dfQ__&Signature=JeJDEHKxKlHa74L3hNQ6vERrB~qlGLKhzbCaoHjk99jTaKCl49IVe6JM3GsKiEpFUzvUkettUiVVbRWHcPtzpltxhydScJX9BmUwrQAmv9xeHokhRvlSbkgWchFt~l6RzrS4Rc~4Hj9c53TqIEOhKIFriK14VmYws9D5eE42SlKvCWabN~jRZ237by58nzBvN2x1AfXGtAk2d7DRLUWOQFNiexxpyjxAM-dLd5WcMW3s6wh2TfcisbCY3tllQ3xnG-08NCqfniZ~HSQgM~LRifjroDWpbTfDfZGkLPFDdbkUvNYYbp928kviopNqd-B5qxucYoV4WYD7btUksnz5IA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 149
[download] Destination: C:\Users\USERNAME\Desktop\91 Days NA.mp4
[download]  18.1% of ~81.33MiB at  1.74MiB/s ETA 00:02
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

This is a duplicate of https://github.com/rg3/youtube-dl/issues/18576
It was closed without any consistent answer, and after 8 days there's still no answer.
So I made another issue.
The problem is that youtube-dl doesn't extract from Crunchyroll the episode. 
In this case the episode is` 7.5`, but it will appear as `NA`. This happens even with [this Inferno Cop's episode](https://www.crunchyroll.com/inferno-cop/inferno-cop-fact-file-01-669837).
It should be `Fact File 01`, but youtube-dl doesn't extract it, so it is `NA`.

**Comment by dstftw** [comment]
As already pointed out `7.5` is not a valid countable integer that is required by `episode_number` thus it's not extracted.
