### ISSUE TITLE
HTML character codes appearing in output filenames when using %(series)s

### ISSUE THREAD

**Issue by cferrey** [rg3/youtube-dl#18641]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
cferrey:~ cferrey$ youtube-dl -v --download-archive "/Volumes/B810n/1/NAS/YouTube/youtube-dl_downloaded.txt" -i -o "/Volumes/B810n/1/NAS/YouTube/%(uploader)s/%(series)s/Season %(season_number)02d/%(series)s - S%(season_number)02dE%(episode_number)02d - %(title)s - [%(id)s].%(ext)s" -f bestvideo[ext=mp4]+bestaudio[ext=m4a] --merge-output-format mp4 --add-metadata --write-thumbnail --batch-file="/Volumes/B810n/1/NAS/YouTube/youtube-dl_channels.txt"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--download-archive', u'/Volumes/B810n/1/NAS/YouTube/youtube-dl_downloaded.txt', u'-i', u'-o', u'/Volumes/B810n/1/NAS/YouTube/%(uploader)s/%(series)s/Season %(season_number)02d/%(series)s - S%(season_number)02dE%(episode_number)02d - %(title)s - [%(id)s].%(ext)s', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]', u'--merge-output-format', u'mp4', u'--add-metadata', u'--write-thumbnail', u'--batch-file=/Volumes/B810n/1/NAS/YouTube/youtube-dl_channels.txt']
[debug] Batch file urls: [u'https://www.youtube.com/playlist?list=PLKtIunYVkv_S7LqWqRuGw1oz-1zG3dIL4', u'https://www.youtube.com/playlist?list=PLKtIunYVkv_TWZZFojD6ZXFxFUWVNgipm', u'https://www.youtube.com/playlist?list=PLKtIunYVkv_TZ6Ld4t2oEdaNkrWab2-20']
[debug] Encodings: locale , fs utf-8, out US-ASCII, pref UTF-8
[debug] youtube-dl version 2018.12.17
[debug] Python version 2.7.12 (CPython) - Darwin-18.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[youtube:playlist] PLKtIunYVkv_S7LqWqRuGw1oz-1zG3dIL4: Downloading webpage
[download] Downloading playlist: It's Alive with Brad
[youtube:playlist] playlist It's Alive with Brad: Downloading 18 videos
[download] Downloading video 1 of 18
[youtube] Ng2zOFADe0s: Downloading webpage
[youtube] Ng2zOFADe0s: Downloading video info webpage
[youtube] Ng2zOFADe0s: Downloading thumbnail ...
[youtube] Ng2zOFADe0s: Writing thumbnail to: /Volumes/B810n/1/NAS/YouTube/Bon Appétit/It&#39;s Alive with Brad/Season 01/It&#39;s Alive with Brad - S01E01 - How to Brew Your Own Kombucha with Brad _ It's Alive _ Bon Appetit - [Ng2zOFADe0s].jpg
[debug] Invoking downloader on u'https://r3---sn-8xgp1vo-cvne.googlevideo.com......{SECTION CUT}
[download] Destination: /Volumes/B810n/1/NAS/YouTube/Bon Appétit/It&#39;s Alive with Brad/Season 01/It&#39;s Alive with Brad - S01E01 - How to Brew Your Own Kombucha with Brad _ It's Alive _ Bon Appetit - [Ng2zOFADe0s].f137.mp4
[download]  32.2% of 103.28MiB at 12.66MiB/s ETA 00:0
```
---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

ISSUE: Output filenames from the playlists shown above have single apostrophe character (') being replaced by its HTML character code (&#39;) when invoking the %(series)s filename attribute.  I imagine this has something to do with Unicode/UTF-8/ASCII output encoding not playing well together.  I have searched and tried several solutions but all to not avail.  The files are being written to a Drobo NAS device, which I believe uses a proprietary Unix-based RAID OS/architecture, but I get the same naming issue if I try to write the files out to the local desktop filesystem (macOS).  I have masked my IP address and cut the log above short, but hopefully it provides enough info.  Thank you in advance for any solutions you can provide!

**Comment by o5729** [comment]
https://www.youtube.com/watch?v=dQw4w9WgXcQ
