### ISSUE TITLE
Vimeo -g 403 forbidden , any workaround or any solution for this ?

### ISSUE THREAD

**Issue by Jeffin21** [rg3/youtube-dl#18676]
i tried to get url of vimeo video i got this error , is there anyway to get the correct URL? i want to send the url to other server 
debug] System config: [] [debug] User config: [] [debug] Custom config: [] [debug] Command-line args: [u'-v', u'-g', u'-s', u'https://vimeo.com/265045525'] [debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8 [debug] youtube-dl version 2018.12.17 [debug] Python version 2.7.10 (CPython) - Linux-2.6.32-754.2.1.el6.x86_64-x86_64-with-centos-6.10-Final [debug] exe versions: ffmpeg 4.1-static, ffprobe 4.1-static [debug] Proxy map: {} WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden [debug] Default format spec: bestvideo+bestaudio/best https://skyfire.vimeocdn.com/1545892288-0x7464aeb4b066072794293699bdaeeccb6a76a86d/265045525/sep/video/979595610,979595608,979595604,979595603/../ https://skyfire.vimeocdn.com/1545892288-0x7464aeb4b066072794293699bdaeeccb6a76a86d/265045525/sep/video/979595610,979595608,979595604,979595603/../

**Comment by dstftw** [comment]
Select format that is not DASH.

**Comment by dstftw** [comment]
It's not an error in the first place.

**Comment by Jeffin21** [comment]
@dstftw but the url i getting in --print-json is https://skyfire.vimeocdn.com/1545892288-0x7464aeb4b066072794293699bdaeeccb6a76a86d/265045525/sep/video/979595610,979595608,979595604,979595603/../ https://skyfire.vimeocdn.com/1545892288-0x7464aeb4b066072794293699bdaeeccb6a76a86d/265045525/sep/video/979595610,979595608,979595604,979595603/../

**Comment by dstftw** [comment]
Read my messages? This is expected URLs since format you're requesting is DASH.

**Comment by Jeffin21** [comment]
@dstftw got it
