### ISSUE TITLE
ERROR: batch file cannot be read

### ISSUE THREAD

**Issue by LemonHeadOnGit** [rg3/youtube-dl#18678]
## Please follow the guide below

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: [u'-x', u'-audio-format', u'mp3']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-x', u'--audio-format', u'mp3', u'https://www.youtube.com/watch?v=tQpKb0U800I']
ERROR: batch file could not be read
<end of log>
```

### Description of your *issue*, suggested solution and other information

I recently installed youtube-dl. I tried to download a YouTube video and convert it to audio with one command, and as you can see above, it gave me the error: batch file could not be read. I got confused because I am using a Mac, and batch files are windows files. So I tried the command again, but this time I tried just downloading the video, and that also gave out the same error.

What I am using: ffmpeg, python. I also have the package: wine, and I installed youtube-dl with homebrew. I ALSO reinstalled youtube-dl about 3 times, and as you can see, no change. I can do anything but download with youtube-dl. I can check the version... that's about it.

**Comment by dstftw** [comment]
Invalid option `-audio-format` in config file.

**Comment by LemonHeadOnGit** [comment]
How did that fix it???

Thanks anyway!
~L

**Comment by gukii** [comment]
u r missing a dash with the "audio-format", correct use: --audio-format
