### ISSUE TITLE
failed to download MPD manifest

### ISSUE THREAD

**Issue by daguro** [rg3/youtube-dl#18680]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl  --all-subs --verbose https://www.youtube.com/watch?v=yw23Ks_SEoo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--all-subs', u'--verbose', u'https://www.youtube.com/watch?v=yw23Ks_SEoo']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.17
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] yw23Ks_SEoo: Downloading webpage
[youtube] yw23Ks_SEoo: Downloading embed webpage
[youtube] yw23Ks_SEoo: Refetching age-gated info webpage
[youtube] yw23Ks_SEoo: Downloading MPD manifest
WARNING: [youtube] yw23Ks_SEoo: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Mystery Road-yw23Ks_SEoo.en.vtt
[debug] Invoking downloader on u'https://r2---sn-nx5s7n7s.googlevideo.com/videoplayback?ei=n2kkXM2_M42qkwaqxZvgBw&gcr=us&itag=227&keepalive=yes&requiressl=yes&signature=70F1E65D37B226F6976BE7E989DA86E69C61F117.3C224658CA27E68E8017092028E9A1F6D6E5122D&expire=1545911807&key=yt6&initcwndbps=1923750&source=yt_media&mv=m&dur=7281.114&clen=4381113098&c=WEB&lmt=1539631331379704&aid=cb0db72acfd2128a&ipbits=0&gir=yes&mn=sn-nx5s7n7s%2Csn-o097znl6&ip=73.254.14.62&mm=31%2C26&fvip=5&ms=au%2Conr&asource=youtube&mt=1545890010&sparams=aid%2Caitags%2Casource%2Cclen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&aitags=142%2C143%2C144%2C145%2C146%2C161%2C222%2C223%2C224%2C225%2C226%2C227%2C273%2C274%2C275%2C279%2C280%2C317%2C318%2C357%2C358%2C359%2C360&pl=16&id=6487bd0d88704312&mime=video%2Fmp4&ratebypass=yes'
[download] Destination: Mystery Road-yw23Ks_SEoo.f227.mp4
[download] 100% of 4.08GiB in 08:28
[debug] Invoking downloader on u'https://r2---sn-nx5s7n7s.googlevideo.com/videoplayback?ei=n2kkXM2_M42qkwaqxZvgBw&gcr=us&itag=329&keepalive=yes&requiressl=yes&signature=11D91CED3B5E9C327C742FB86FD68ED8889C5A60.40D18F1CF17C784ACFCB30299CF2760447F9F4B4&expire=1545911807&key=yt6&initcwndbps=1923750&source=yt_media&mv=m&dur=7281.184&clen=351430577&c=WEB&lmt=1539630860419029&ipbits=0&gir=yes&mn=sn-nx5s7n7s%2Csn-o097znl6&ip=73.254.14.62&mm=31%2C26&fvip=5&ms=au%2Conr&asource=youtube&mt=1545890010&sparams=aid%2Casource%2Cclen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&aid=cb0db72acfd2128a&pl=16&id=6487bd0d88704312&mime=audio%2Fmp4&ratebypass=yes'
[download] Destination: Mystery Road-yw23Ks_SEoo.f329.m4a
[download] 100% of 335.15MiB in 00:40
[ffmpeg] Merging formats into "Mystery Road-yw23Ks_SEoo.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Mystery Road-yw23Ks_SEoo.f227.mp4' -i 'file:Mystery Road-yw23Ks_SEoo.f329.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Mystery Road-yw23Ks_SEoo.temp.mp4'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2048, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 479, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

This is the first time I have seen this happen.  youtube-dl is an awesome tool and I was surprised to see this.

**Comment by dstftw** [comment]
Outdated ffmpeg.
