### ISSUE TITLE
can't update youtube-dl through homebrew 

### ISSUE THREAD

**Issue by exxfzc** [rg3/youtube-dl#18694]
i can't update youtube-dl through homebrew in my mac.i try many times, but it failed.
i don't know the reason
<img width="565" alt="2018-12-30 11 06 00" src="https://user-images.githubusercontent.com/23161815/50544035-8c5ffb80-0c23-11e9-9272-e210a3e03d61.png">

**Comment by dstftw** [comment]
Address this to howebrew.
