### ISSUE TITLE
How to get a list of videos from a local video archive that are deleted online by now?

### ISSUE THREAD

**Issue by bathrobehero** [rg3/youtube-dl#18691]
## Checklist

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

This is hard to search for so I apologize for asking here.

I have both youtube channels and playlists with thousands of videos archived and I want to get a list of videos that are deleted from youtube by now but I do have the backups for. I use only the title as the filename and store the json and the thumbnail as well. Is there some built-in method for easily generating a list of these files with youtube-dl, or do I have to work with "has already been downloaded and merged" entries and comapred that to a file list (not very convenient)? Thanks.

**Comment by rautamiekka** [comment]
Well, if everything else fails, you could
1) get the IDs from the JSONs
2) use a link like

```
https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=vqnVqmeSVp&format=json
```
to either get
1) `Not Found` if the vid doesn't exist
2) otherwise its JSON.

Cuz the filename alone is totally useless.
