### ISSUE TITLE
Why are site support requests for txxx.com being denied?

### ISSUE THREAD

**Issue by lovelyspringday** [rg3/youtube-dl#18708]
Many site support requests for https://www.txxx.com have been made in the past but moderators have denied the requests and locked the forum threads. Why?

Txxx.com has hundreds of channels of videos that seem to be uploaded by the video creators:

https://www.txxx.com/channels-list/most-popular/

If pornhub, redtube etc are supported by Youtube-dl why not support txxx.com?

**Comment by dstftw** [comment]
Nothing is denied. There is already an issue opened. Stop posting duplicates.
