### ISSUE TITLE
Musik-Videos doesnt work

### ISSUE THREAD

**Issue by Misterodd** [rg3/youtube-dl#18707]
Hey guys,

I found this tool to download youtube videos, and for the most its working, but when I want to download a Musik-Video this happens:
EDIT: 
I use Debian/Ubuntu with LinuxKernel 4.20
just installed today via "apt"

youtube-dl -F --no-check-certificate  --verbose https://www.youtube.com/watch?v=r0J-vNlgWic
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--no-check-certificate', '--verbose', 'https://www.youtube.com/watch?v=r0J-vNlgWic']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.7 (CPython) - Linux-4.20.0-042000-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] r0J-vNlgWic: Downloading webpage
[youtube] r0J-vNlgWic: Downloading video info webpage
[youtube] r0J-vNlgWic: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {18} signature length 40.41, html5 player None
[youtube] r0J-vNlgWic: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vflSzU_20/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1191, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1102, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1163, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1191, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1102, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1163, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1191, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1102, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1163, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1899, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1201, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1191, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1102, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1163, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

but others works fine:
youtube-dl -f 299 --no-check-certificate https://www.youtube.com/watch?v=Db-tuTCsoWU&t=15s
[youtube] Db-tuTCsoWU: Downloading webpage
[youtube] Db-tuTCsoWU: Downloading video info webpage
[youtube] Db-tuTCsoWU: Extracting video information
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
[download] Destination: Game Theory - Fortnite is Stealing...AGAIN!! (The Fortnite Dance Controversy)-Db-tuTCsoWU.mp4
[download] 100% of 298.23MiB in 03:23

Why does youtube-dl want to download "js player vflSzU_20" but not when its working. how can I forbid the use of the js player, its seems to create this issue. 
Thank you for your help.

**Comment by Misterodd** [comment]
It seems that it cant get the player, so it cant get the download URL. But with this script, found earlier, I where able to get the download URL. I cant use it because 

> 403 Forbidden

`#!/usr/bin/perl

use strict;
use warnings;
## Two arguments
##    $1 YouTube URL from the browser
##    $2 Prefix to the file name of the video (optional)
#

## Collect the URL from the command line argument
my $url = $ARGV[0] or die "\nError: You need to specify a YouTube URL\n\n";

## Declare the user defined file name prefix
my $prefix = defined($ARGV[1]) ? $ARGV[1] : "";

## Download the HTML code from the YouTube page
my $html = `wget -Ncq -e "convert-links=off" --keep-session-cookies --save-cookies /dev/null --no-check-certificate "$url" -O-`  or die  "\nThere was a problem downloading the HTML file.\n\n";

## Collect the title of the page to use as the file name
my ($title) = $html =~ m/<title>(.+)<\/title>/si;
$title =~ s/[^\w\d]+/_/g;
$title =~ s/_youtube//ig;
$title =~ s/^_//ig;
$title = lc ($title);

## Collect the URL of the video
my ($download) = $html =~ /"url_encoded_fmt_stream_map"([\s\S]+?)\,/ig;

## Clean up the URL by translating Unicode and removing unwanted strings
$download =~ s/\:\ \"//;
$download =~ s/%3A/:/g;
$download =~ s/%2F/\//g;
$download =~ s/%3F/\?/g;
$download =~ s/%3D/\=/g;
$download =~ s/%252C/%2C/g;
$download =~ s/%26/\&/g;
$download =~ s/sig=/signature=/g;
$download =~ s/\\u0026/\&/g;
$download =~ s/(type=[^&]+)//g;
$download =~ s/(fallback_host=[^&]+)//g;
$download =~ s/(quality=[^&]+)//g;

## Collect the URL and signature since the HTML page randomizes the order
my ($signature) = $download =~ /(signature=[^&]+)/;
my ($youtubeurl) = $download =~ /(http.+)/;
$youtubeurl =~ s/&signature.+$//;

## Combine the URL and signature in order to use in Wget
$download = "$youtubeurl\&$signature";

## A bit more cleanup
$download =~ s/&+/&/g;
$download =~ s/&itag=\d+&signature=/&signature=/g;

## Print the file name of the video collected from the web page title for us to see on the CLI
print "\n Download: $prefix$title.webm\n\n";

## Download the file using Wget and background the Wget process
system("wget -Nc -e \"convert-links=off\" --load-cookies /dev/null --tries=50 --timeout=45 --no-check-certificate \"$download\" -O $prefix$title.webm &");

#### EOF #####`

I get : 
--2018-12-31 22:23:20--  https://r1---sn-oxujvavbox-jboe.googlevideo.com/videoplayback?clen=12290315&mime=video%252Fmp4&ipbits=0&fvip=1&requiressl=yes&ratebypass=yes&txp=5431432&mm=31%2C29&pl=47&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&source=youtube&c=WEB&id=o-AH_qxQHp8VJKQ1xaIpg24vnQmFcS0iQ1NPgDeHvQF1LZ&expire=1546313006&ip=2001%253A4dd7%253A3c2b%253A0%253A1939%253Aa5af%253A85fa%253A5956&lmt=1546240551163818&ei=zogqXPXKGdCsgQeXoImAAg&dur=213.832&mt=1546290375&mv=u&ms=au%2Crdu&key=yt6&mn=sn-oxujvavbox-jboe%2Csn-5hne6nsd&itag=18&gir=yes&s=6F26204FE8195BA8AB30F5E0616D058743C11CB8.0053E5805D6927E949E1BA7C336DA8455B0F1A2B3&sp=signature&
Auflösen des Hostnamens r1---sn-oxujvavbox-jboe.googlevideo.com (r1---sn-oxujvavbox-jboe.googlevideo.com) … 2001:4dd0:200:310::c, 87.79.22.12
Verbindungsaufbau zu r1---sn-oxujvavbox-jboe.googlevideo.com (r1---sn-oxujvavbox-jboe.googlevideo.com)|2001:4dd0:200:310::c|:443 … verbunden.
WARNUNG: Das Zertifikat von r1---sn-oxujvavbox-jboe.googlevideo.com kann nicht geprüft werden, ausgestellt von »CN=Google Internet Authority G3,O=Google Trust Services,C=US«:.
  Die Autorität des Ausstellers des Zertifikates kann lokal nicht geprüft werden. (
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 403 Forbidden
2018-12-31 22:23:20 ERROR 403: Forbidden.

**Comment by Misterodd** [comment]
``

> Update youtube-dl with `youtube-dl -U` (or if you used a package manager use its update function).

I have just installed it, so its up-to-date, checked it before i posted it.

**Comment by eduardog3000** [comment]
Your output says `[debug] youtube-dl version 2018.03.14`, so it's not up to date. The current version is `2018.12.31`. Try running `youtube-dl -U`.

**Comment by Misterodd** [comment]
> Your output says `[debug] youtube-dl version 2018.03.14`, so it's not up to date. The current version is `2018.12.31`. Try running `youtube-dl -U`.

Hmm so 
> youtube-dl: error: youtube-dl's self-update mechanism is disabled on Debian.
> Please update youtube-dl using apt(8).
> See https://packages.debian.org/sid/youtube-dl for the latest packaged version.

Its an old version in the Ubuntu repro

**Comment by eduardog3000** [comment]
You might have to update apt.

`sudo apt update`

Then run `sudo apt install youtube-dl` again.

**Comment by eduardog3000** [comment]
If that doesn't work uninstall from apt and try installing with `pip`.

**Comment by Misterodd** [comment]
updated apt, but the version didnt changed.
Done with pip:
>Successfully installed youtube-dl-2018.12.31

Yeah now I'm to stupid to use youtube-dl. Ubuntu wants that I install it first via snap or apt.
How can I use pip installed applications?

**Comment by eduardog3000** [comment]
It's located in `~/.local/lib/python2.7/site-packages`, so either run it with `~/.local/lib/python2.7/site-packages/youtube-dl` or add `~/.local/lib/python2.7/site-packages` to your path.

Or just install it directly:

```
sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```

**Comment by Misterodd** [comment]
Ok downloaded it:
Thank you very much! Now it works!

**Comment by Misterodd** [comment]
``
