### ISSUE TITLE
--output %(release_date)s gives "NA" on YouTube. Linux Mint 18.3, YTDL 2018.12.17.

### ISSUE THREAD

**Issue by mr-falafel** [rg3/youtube-dl#18704]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v 'https://www.youtube.com/watch?v=Kbyr0t8AIlE' --output "%(release_date)s"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=Kbyr0t8AIlE', u'--output', u'%(release_date)s']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.17
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-34-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: ffmpeg 2.8.15-0ubuntu0.16.04.1, ffprobe 2.8.15-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] Kbyr0t8AIlE: Downloading webpage
[youtube] Kbyr0t8AIlE: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r3---sn-aigzrn7k.googlevideo.com/videoplayback?expire=1546296197&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303&lmt=1545154972286663&requiressl=yes&keepalive=yes&ip=185.103.96.151&clen=117984404&mt=1546274447&dur=316.533&mv=m&ms=au%2Crdu&mm=31%2C29&ipbits=0&c=WEB&mn=sn-aigzrn7k%2Csn-aigl6ned&gir=yes&initcwndbps=1266250&id=o-AJDMxmpMCyJCzvefeZvKrIhVO-rg9f9bygwYsWWxXjK2&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ei=JEcqXKTEOoOE1wbTvbroDA&itag=299&beids=9466588&signature=C537B67E2E37E41CD712A61D559863AC6E29C87C.B36836C0A0E90A369B1380F1C2BB0DFE4D630008&fvip=3&mime=video%2Fmp4&pl=22&source=youtube&key=yt6&txp=5532432&ratebypass=yes'
[download] Destination: NA.f299
[download]   4.2% of 112.52MiB at  1.36MiB/s ETA 01:19^C
ERROR: Interrupted by user

```

### Description of your *issue*, suggested solution and other information

When using youtube-dl on YouTube with the --output flag, the "%(release_date)s" tag results in only "NA" for all YouTube videos. Other tags, such as "%(title)s" still function normally. I am using Linux Mint 18.3 and youtube-dl version 2018.12.17, downloaded directly from your site, rather than my package manager. Thanks. :)

**Comment by dstftw** [comment]
There is no release dates on youtube.
