### ISSUE TITLE
Use on website in js player ?

### ISSUE THREAD

**Issue by DonCorleone9** [rg3/youtube-dl#18705]
Is it possible to use this repo's code and adapt it to make a video streaming site.

Let's say that i have uploaded my videos on YT.. Then can i use youtube-dl script to output the "https://r1---sn-" type of download link as the source of my JS video player on my website.

Like for example if you click this link: http://freemedtube.com/play.php?id=eUVxcFlQMjdFR1llRTRRNjBCRTFsZz09

Then it will open up something like this: https://r3---sn-cvh7knek.googlevideo.com/videoplayback?c=WEB&ei=AVoqXOK6Eseghwb3xorQAg&lmt=1538815325557977&expire=1546301025&itag=18&ip=54.196.168.61&source=youtube&signature=5AA9E61E95DBD995AD037625D7295CF6B9A60E4E.524DE0E531A9D8E1BD80F7F6E9DA58498E2EE382&mime=video%2Fmp4&fvip=3&dur=1427.284&pl=20&id=o-AN9pdAv7Oy14vmyugdbtp5-pDMMOFWjxzZfYZ_K65Q3w&ratebypass=yes&sparams=clen,dur,ei,expire,gir,id,ip,ipbits,ipbypass,itag,lmt,mime,mip,mm,mn,ms,mv,pl,ratebypass,requiressl,source&gir=yes&requiressl=yes&key=cms1&clen=57807231&txp=2211222&ipbits=0&redirect_counter=1&rm=sn-vgqeer7s&fexp=23763603&req_id=a3b08176f33aa3ee&cms_redirect=yes&ipbypass=yes&mip=122.170.191.206&mm=31&mn=sn-cvh7knek&ms=au&mt=1546279329&mv=m

They are using the exact mechanism of youtube-dl on site freemedtube.com to stream videos hosted on Youtube on their own website by outputting the download link to a JS player.

Please let me know if this is possible ? I guess with python + flask (for webdev) it maybe possible.
Thanks.

**Comment by dstftw** [comment]
>They are using the exact mechanism of youtube-dl on site freemedtube.com to stream videos hosted on Youtube on their own website by outputting the download link to a JS player.

If they do then it's obviously possible.

**Comment by DonCorleone9** [comment]
Your responses are rude and non-helpful..
Yes it is obviously possible if someone else does it.. I was asking people how to do so using Flask and Python..

**Comment by dstftw** [comment]
This is neither general python programming forum not flask support board. Read doc on flask.
