### ISSUE TITLE
Pluralsight Login error

### ISSUE THREAD

**Issue by Korreia** [rg3/youtube-dl#18717]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.31**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

D:\Plurasight>youtube-dl --sleep-interval 120 --verbose -o "Microsoft Azure Architect Technologies (AZ-300)/01 - %(playlist)s/%(chapter_number)s - %(chapter)s/%
(playlist_index)s - %(title)s.%(ext)s" https://app.pluralsight.com/library/courses/azure-multi-factor-authentication-implementing-managing/table-of-contents --u
sername × --password ×
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--sleep-interval', '120', '--verbose', '-o', 'Microsoft Azure Architect Technologies (AZ-300)/01 - %(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', 'https://app.pluralsight.com/library/courses/azure-multi-factor-authentication-implementing-managing/table-of-contents', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.12.31
[debug] Python version 3.4.4 (CPython) - Windows-2012ServerR2-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] azure-multi-factor-authentication-implementing-managing: Downloading JSON metadata
[download] Downloading playlist: Implementing and Managing Azure Multi-factor Authentication
[pluralsight:course] playlist Implementing and Managing Azure Multi-factor Authentication: Collected 84 video ids (downloading 84 of them)
[download] Downloading video 1 of 84
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure
 to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp89xz0pmt\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp89xz0pmt\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp89xz0pmt\build\youtube_dl\extractor\common.py", line 411, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp89xz0pmt\build\youtube_dl\extractor\pluralsight.py", line 165, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp89xz0pmt\build\youtube_dl\extractor\pluralsight.py", line 215, in _login
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube
-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### Description of your *issue*, suggested solution and other information
The issue started today, Jan, 1, 2019 as yesterday I was able to download using the exact same command line. The only difference is that on Dec 31, 2018 I was using youtube-dl 2018.12.17. I've updated to the latest version since I started getting this error. The Pluralsight URL login https://app.pluralsight.com/id/ is accessible and my credentials are working on the site

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by Korreia** [comment]
When I add the --dump-pages it was working. Not sure what happen or why it was not working prior...
