### ISSUE TITLE
sporthdreplays.com support

### ISSUE THREAD

**Issue by xantares** [rg3/youtube-dl#18711]
Hello devs,

It'd be cool to support this domain, eg:
http://sporthdreplays.com/france-vs-russia-european-womens-handball-championship-nov-29-2018/

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
