### ISSUE TITLE
Did not get any data blocks

### ISSUE THREAD

**Issue by mysuf** [rg3/youtube-dl#18719]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

First attempt:
```
2019/01/02 13:46:10.639 [73] D1: [youtube] jURW1eLAlgQ: Downloading webpage {yt_unicode.py:debug():9}
2019/01/02 13:46:11.099 [73] D1: [youtube] jURW1eLAlgQ: Downloading video info webpage {yt_unicode.py:debug():9}
2019/01/02 13:46:11.518 [73] D1: [youtube] jURW1eLAlgQ: Downloading MPD manifest {yt_unicode.py:debug():9}
2019/01/02 13:46:12.274 [73] D1: [youtube] jURW1eLAlgQ: Downloading MPD manifest {yt_unicode.py:debug():9}
2019/01/02 13:46:12.891 [73] W3: "id" field is not a string - forcing string conversion, there is an error in extractor {yt_unicode.py:warning():12}
2019/01/02 13:46:13.759 [73] D1: [info] jURW1eLAlgQ: downloading video in 2 formats {yt_unicode.py:debug():9}
2019/01/02 13:46:14.119 [73] D1: [download] Destination: /www/cms/encoder//data/source/jURW1eLAlgQ_22.mp4 {yt_unicode.py:debug():9}
[download]   0.0% of 471.27MiB at 981.35KiB/s ETA 08:48 {yt_unicode.py:debug():9}
[download]   0.0% of 471.27MiB at  1.63MiB/s ETA 04:53 {yt_unicode.py:debug():9}
[download]   0.0% of 471.27MiB at  2.32MiB/s ETA 03:29 {yt_unicode.py:debug():9}
[download]   0.0% of 471.27MiB at  3.92MiB/s ETA 02:01 {yt_unicode.py:debug():9}
[download]   0.0% of 471.27MiB at  6.54MiB/s ETA 01:13 {yt_unicode.py:debug():9}
[download]   0.0% of 471.27MiB at  2.50MiB/s ETA 03:08 {yt_unicode.py:debug():9}
[download]   0.0% of 471.27MiB at  4.89MiB/s ETA 01:36 {yt_unicode.py:debug():9}
[download]   0.1% of 471.27MiB at  7.19MiB/s ETA 01:05 {yt_unicode.py:debug():9}
[download]   0.1% of 471.27MiB at  6.90MiB/s ETA 01:08 {yt_unicode.py:debug():9}
[download]   0.2% of 471.27MiB at  7.06MiB/s ETA 01:06 {yt_unicode.py:debug():9}
[download]   0.4% of 471.27MiB at  7.30MiB/s ETA 01:04 {yt_unicode.py:debug():9}
[download]   0.4% of 471.27MiB at  5.92MiB/s ETA 01:19 {yt_unicode.py:debug():9}
2019/01/02 13:46:14.467 [73] F4: ERROR: giving up after 0 retries {yt_unicode.py:error():15}
```
Second attempt:
```
2019/01/02 13:36:28.203 [72] D1: best[width=1280][ext!=webm][protocol!=http_dash_segments][fps<=?60.0],best[width=1920][ext!=webm][protocol!=http_dash_segments][fps<=?60.0]/bestvideo[width=1920][ext!=webm][protocol!=http_dash_segments][fps<=?60.0]+bestaudio[ext!=webm]/best[width>1920][ext!=webm][protocol!=http_dash_segments][fps<=?60.0]/bestvideo[width=1920][ext!=webm]+bestaudio[ext!=webm]/bestvideo[width>1920][ext!=webm][protocol!=http_dash_segments][fps<=?60.0]+bestaudio[ext!=webm]/bestvideo[width>1920][ext!=webm]+bestaudio[ext!=webm]/best[ext!=webm] {yt_unicode.py:yt_download():38}
2019/01/02 13:36:28.674 [72] D1: [youtube] jURW1eLAlgQ: Downloading webpage {yt_unicode.py:debug():9}
2019/01/02 13:36:29.126 [72] D1: [youtube] jURW1eLAlgQ: Downloading video info webpage {yt_unicode.py:debug():9}
2019/01/02 13:36:29.728 [72] D1: [youtube] jURW1eLAlgQ: Downloading MPD manifest {yt_unicode.py:debug():9}
2019/01/02 13:36:30.512 [72] D1: [youtube] jURW1eLAlgQ: Downloading MPD manifest {yt_unicode.py:debug():9}
2019/01/02 13:36:31.093 [72] W3: "id" field is not a string - forcing string conversion, there is an error in extractor {yt_unicode.py:warning():12}
2019/01/02 13:36:31.962 [72] D1: [info] jURW1eLAlgQ: downloading video in 2 formats {yt_unicode.py:debug():9}
2019/01/02 13:36:31.996 [72] D1: [download] Resuming download at byte 2157424 {yt_unicode.py:debug():9}
2019/01/02 13:36:32.405 [72] D1:  {yt_unicode.py:debug():9}
2019/01/02 13:36:32.405 [72] F4: ERROR: Did not get any data blocks {yt_unicode.py:error():15}
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=jURW1eLAlgQ

---

### Description of your *issue*, suggested solution and other information

Using python youtube-dl (non-cli). Simply unable to download video. Formats are available as you can see in log section. First error occurs always at 0.4%. No custom number of retries (default should be 10), but it gives up after first fail. Second attempt throws different error. Note empty debug row D1:  {yt_unicode.py:debug():9}

EDIT: with `ignoreerrors: True`, it downloads second format without any issue. Is possible that first format is corrupted on youtube site?

**Comment by dstftw** [comment]
Format 22 is broken at youtube side.
