### ISSUE TITLE
some link on RAI

### ISSUE THREAD

**Issue by gioreva** [rg3/youtube-dl#18720]
Some link are not working.
Using Rampermonkey same work.

youtube-dl  https://www.raiplay.it/video/2018/07/Dal-profondo-f4d7eb13-d93d-406d-9e8b-0d78d58a1bf7.html
youtube-dl  https://www.raiplay.it/raiplay/video/2017/12/Mississippi-il-lento-fiume-americano-E2-46897e0b-859e-4612-bdd3-a5f4645c0cb4.html
youtube-dl  https://www.raiplay.it/raiplay/video/2017/12/Mississippi-il-lento-fiume-americano-E3-f35b1a9a-2061-43fd-863b-e2c0845db035.html
youtube-dl  https://www.raiplay.it/video/2018/07/Quark-Atlante-Immagini-dal-Pianeta-La-rinascita-di-una-antica-foresta-c6b2925d-f551-4cd6-9611-ef22e174f33e.html
youtube-dl  https://www.raiplay.it/video/2018/07/Quark-Atlante-Le-maschere-degli-animali-350d1387-74fd-46f5-b993-35b4ba104b10.html
youtube-dl  https://www.raiplay.it/video/2017/09/Quark-Atlante-Immagini-dal-pianeta---Il-trionfo-dei-vertebrati-dal-mare-al-cielo-72beaced-48fe-44fc-8dff-0f870098714f.html

**Comment by dstftw** [comment]
All require authentication.
