### ISSUE TITLE
Having trouble both updating and uninstalling youtube-dl

### ISSUE THREAD

**Issue by Syl0pt** [rg3/youtube-dl#18732]
I'm running Linux Mint 18 xfce

I'm having trouble downloading some videos with youtube-dl so I tried to update it and ran into trouble. Doing 'youtube-dl --update' shows "It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update." I don't remember exactly what I used to install it so i just assumed I used pip. But when trying 'sudo pip install -U youtube-dl' I get this error: https://imgur.com/a/sBrEABu

So I tried just uninstalling it so I can reinstall. But when I try 'sudo apt-get remove -y youtube-dl' as insructed in https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl I get:
"Reading package lists...
Building dependency tree...
Reading state information...
Package 'youtube-dl' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded."

Which I don't understand. Why does it say it's not installed when it most definintely is. I know this because I JUST used it before I wrote out this report. And when I type 'youtube-dl' into  my terminal I get: 
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

So I can't update it because it gives an error. And I can't uninstall it because it claims it's not even installed (which it is.)
I don't know what to do now.

Running 'youtube-dl --version' shows '2018.08.04' which to me looks more like the date I installed it rather than the version, but maybe I'm wrong.

**Comment by dstftw** [comment]
https://stackoverflow.com/questions/51019860/error-with-pip-after-upgrading-module-object-has-no-attribute-ssl-st-init
