### ISSUE TITLE
download from d.tube fails

### ISSUE THREAD

**Issue by 4rensiker** [rg3/youtube-dl#18741]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for __re__adding support for an existing site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** 

```
user@mymachine:~$ youtube-dl --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.02
[debug] Python version 3.5.3 (CPython) - Linux-4.9.0-4-amd64-x86_64-with-debian-9.2
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
user@ mymachine:~$ youtube-dl --verbose "https://d.tube/#!/v/dennisxxx/lgfrcata"
bash: !/v/dennisxxx/lgfrcata: event not found
```
### Description of your *issue*, suggested solution and other information

Download from d.tube failed. I am sorry to not being able to provide more information. If I can help/try anything else I will gladly do though....

**Comment by GianlucaFicarelli** [comment]
Your problem is not related to youtube-dl, but to the shell.
You need to escape `!` with `\`, or use `'` instead of `"`:
`youtube-dl --verbose 'https://d.tube/#!/v/dennis567/lgfrcata'`

**Comment by 4rensiker** [comment]
Thx @GianlucaFicarelli for the quick reply. And you are right. The shell execution needs single quotes. Sorry for overlooking that... but what I then get on linux is

```
user@mymachine:~$ youtube-dl --verbose 'https://d.tube/#!/v/dennis567/lgfrcata'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://d.tube/#!/v/dennis567/lgfrcata']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.02
[debug] Python version 3.5.3 (CPython) - Linux-4.9.0-4-amd64-x86_64-with-debian-9.2
[debug] exe versions: none
[debug] Proxy map: {}
[DTube] lgfrcata: Downloading JSON metadata
[DTube] lgfrcata: Checking 240p video format URL
[DTube] lgfrcata: 240p URL is invalid, skipping
[DTube] lgfrcata: Checking 480p video format URL
[DTube] lgfrcata: 480p URL is invalid, skipping
[DTube] lgfrcata: Checking Source video format URL
[DTube] lgfrcata: Source URL is invalid, skipping
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 804, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 858, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 1517, in process_video_result
    raise ExtractorError('No video formats found!')
youtube_dl.utils.ExtractorError: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

and even on my mac with a more recent python version it states

```
MBP:~ user$ youtube-dl --verbose 'https://d.tube/#!/v/dennis567/lgfrcata'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://d.tube/#!/v/dennis567/lgfrcata']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.7.0 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[DTube] lgfrcata: Downloading JSON metadata
[DTube] lgfrcata: Checking 240p video format URL
[DTube] lgfrcata: 240p URL is invalid, skipping
[DTube] lgfrcata: Checking 480p video format URL
[DTube] lgfrcata: 480p URL is invalid, skipping
[DTube] lgfrcata: Checking Source video format URL
[DTube] lgfrcata: Source URL is invalid, skipping
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 857, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1516, in process_video_result
    raise ExtractorError('No video formats found!')
youtube_dl.utils.ExtractorError: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by GianlucaFicarelli** [comment]
It seems that it's not possible get data for any video format (240p, 480p, Source).
Maybe something is wrong with this link? Is any similar link working?
Sorry but I cannot be more helpful.

**Comment by 4rensiker** [comment]
Hm. I took another random link (`https://d.tube/#!/v/steemsistershow/bw35svqm`) that plays well but throws the same error when trying to youtube-dl. Is youtube-dl working for you with d.tube so that you can send me a link to try?

**Comment by sebilasse** [comment]
@4rensiker Please do not post these doxing link in cleartext.

**Comment by 4rensiker** [comment]
I am not sure how this helps in finding bugs @sebilasse. If there is a problem with a certain URL the developer needs this URL. The content was deleted anyway.

**Comment by 4rensiker** [comment]
I am not sure how this helps in finding bugs @sebilasse. If there is a problem with a certain URL the developer needs this URL. The content was deleted anyway. But thank you for the hint.

**Comment by GianlucaFicarelli** [comment]
The problem seems to involve every DTube video, so I suppose that something has changed.
I have never used this service, but I was able to get it working, replacing just one line in the file `youtube_dl/extractor/dtube.py`.
Replace `return 'https://ipfs.io/ipfs/' + h` with `return 'https://video.dtube.top/ipfs/' + h`
Hopefully it will be fixed in the next release, but it's better to wait for a response from the developers.
About the links, I suppose that they are allowed if they are public and if they don't violate any copyright.

**Comment by sebilasse** [comment]
@GianlucaFicarelli No, posting the link above is strictly illegal ! It contained sensitive informations about german politicians (e.g. pictures of their kids) - it was illegal for two reasons : privacy and copyright. Just wanted to save the person posted this from criminally liability !

Read more (in english) here
https://www.politico.eu/article/germany-data-hack-merkel-whacked/
https://www.theregister.co.uk/2019/01/04/germany_mass_hack_merkel/
https://slate.com/news-and-politics/2019/01/germany-hacked-data-breach-angela-merkel-dilemma.html
https://www.bbc.com/news/world-europe-46757009

**Comment by GianlucaFicarelli** [comment]
@sebilasse I was not meaning that the specific link above was legal or illegal, because I didn't check it.
So, good that you have checked and warned the poster.

**Comment by 4rensiker** [comment]
thx @GianlucaFicarelli for the hint. Checked it and it works again after applying your change.

**Comment by PacoH** [comment]
I had the same problem with (https://d.tube/#!/v/humanrights2030/QmP2ht7aDbtjg5Q7jvQ2rRKHQWEaRkAd7kSjpVqxHQMeoM). What solved it was to right-click inside the video frame and select `Copy Video Address` (Google Chrome)––(https://player.d.tube/btfs/QmP2ht7aDbtjg5Q7jvQ2rRKHQWEaRkAd7kSjpVqxHQMeoM) then downloaded just fine.

**Comment by PacoH** [comment]
I had the same problem with <https://d.tube/#!/v/humanrights2030/QmP2ht7aDbtjg5Q7jvQ2rRKHQWEaRkAd7kSjpVqxHQMeoM>. What solved it was to right-click inside the video frame and select `Copy Video Address` (Google Chrome). The address was <https://player.d.tube/btfs/QmP2ht7aDbtjg5Q7jvQ2rRKHQWEaRkAd7kSjpVqxHQMeoM> which downloaded as expected.

**Comment by PacoH** [comment]
I had the same problem with <https://d.tube/#!/v/humanrights2030/QmP2ht7aDbtjg5Q7jvQ2rRKHQWEaRkAd7kSjpVqxHQMeoM>. What solved it was to right-click inside the video frame and select `Copy Video Address` (Google Chrome). The address was <https://player.d.tube/btfs/QmP2ht7aDbtjg5Q7jvQ2rRKHQWEaRkAd7kSjpVqxHQMeoM> which downloaded as expected.

**Comment by PacoH** [comment]
I had the same problem with `https://d.tube/#!/v/humanrights2030/QmP2ht7aDbtjg5Q7jvQ2rRKHQWEaRkAd7kSjpVqxHQMeoM`. What solved it was to right-click inside the video frame and select `Copy Video Address` (Google Chrome). The address was `https://player.d.tube/btfs/QmP2ht7aDbtjg5Q7jvQ2rRKHQWEaRkAd7kSjpVqxHQMeoM` which downloaded as expected.
