### ISSUE TITLE
Support new version of MyCanal.fr

### ISSUE THREAD

**Issue by frankahn** [rg3/youtube-dl#18745]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl --verbose http://hls-od-mycanal-aka.canal-plus.com/replay/cplus/hls/cpl100020766-ant-1198741-7/ANT_1198741_7.m3u8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://hls-od-mycanal-aka.canal-plus.com/replay/cplus/hls/cpl100020766-ant-1198741-7/ANT_1198741_7.m3u8']
[debug] Encodings: locale ISO8859-1, fs utf-8, out ISO8859-1, pref ISO8859-1
[debug] youtube-dl version 2019.01.02
[debug] Python version 2.7.15 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ANT_1198741_7: Requesting header
[generic] ANT_1198741_7: Downloading m3u8 information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2289, in _real_extract
    self._sort_formats(formats)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1292, in _sort_formats
    raise ExtractorError('No video formats found')
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: 
http://hls-od-mycanal-aka.canal-plus.com/replay/cplus/hls/cpl100020766-ant-1198741-7/ANT_1198741_7.m3u8
- Single video: http://hls-od-mycanal-aka.canal-plus.com/replay/cplus/hls/cpl100021211-ant-1198741-8/ANT_1198741_8.m3u8

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Until October, downloads from videos hosted by mycanal.fr were possible through the URL of the video (accessible through a well placed right click). However, the site has changed the structure (and maybe the servers) for the video links.
An old video link would be in that form (the URL still works actually): https://strcpluscplus-vh.akamaihd.net/i/1810/26/1198741_6_,200k,400k,800k,1500k,.mp4.csmil/master.m3u8?secret=pqzerjlsmdkjfoiuerhsdlfknaes
However, the same video is now hosted officially here: http://hls-od-mycanal-aka.canal-plus.com/replay/cplus/hls/cpl100019805-ant-1198741-6/ANT_1198741_6.m3u8
The URL for the web browser hasn't changed: https://www.mycanal.fr/divertissement/groland-le-zapoi-emission-du-27-oct-2018/h/10441916_50001

**Comment by campones** [comment]
they still have some urls for apple like this, while cnews works, c8 seems encrypted?

youtube-dl https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8
[generic] index: Requesting header
WARNING: Could not send HEAD request to https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
[generic] index: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> (caused by URLError(SSLError(1, '_ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))


https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8

been deducting this looking at the cnews's url  which is working

http://hls-m007.live-lv3.canalplus-cdn.net/live/disk/cnews-clair-hd/ios-v3-hd-clair/index.m3u8

**Comment by sebma** [comment]
Related to issue #18240
