### ISSUE TITLE
Parleys Support

### ISSUE THREAD

**Issue by sirinath** [rg3/youtube-dl#1876]
Is it possible to add support to Parleys:

1) User:

http://parleys.com/speaker/516bb602e4b05b6ad71fa74b

2) Channel:

http://www.parleys.com/channel/51ae1022e4b01033a7e4b6ca

3) Individual videos:

http://www.parleys.com/play/51c1994ae4b0d38b54f4621b

**Comment by remitamine** [comment]
redirect to https://www.youtube.com/user/Parleysdotcom.
