### ISSUE TITLE
Cryptic error message on some YouTube videos

### ISSUE THREAD

**Issue by vedranmiletic** [rg3/youtube-dl#18761]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4', '-v', 'https://youtu.be/DdlgHLb5ops']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.02
[debug] Python version 3.7.1 (CPython) - Linux-4.19.12-301.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.3, ffprobe 4.0.3
[debug] Proxy map: {}
[youtube] DdlgHLb5ops: Downloading webpage
[youtube] DdlgHLb5ops: Downloading video info webpage
[debug] Invoking downloader on 'https://r3---sn-jpm-15bd.googlevideo.com/videoplayback?nh=%2CEAQ&key=yt6&txp=5532432&initcwndbps=970000&ipbits=0&pl=16&expire=1546789481&mime=video%2Fmp4&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C394%2C395%2C396%2C397&lmt=1546691001010502&source=youtube&gcr=hr&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AOOVPqr3rv8PM1ZDchcDesejfY904z9NydFfGRJ2tCNH&dur=5235.133&mm=31%2C29&gir=yes&c=WEB&mn=sn-jpm-15bd%2Csn-bvvbax-15be&ms=au%2Crdu&mt=1546767745&mv=m&signature=325203400CCED69CB34B2D3DFC559377C5E5BA4D.CF5B1AB585F4EBECE37314DE989111019CBF8DDD&clen=26764547&ip=31.147.127.97&keepalive=yes&ei=CM4xXLLBNM2bgQe5j5bQCQ&requiressl=yes&itag=397&fvip=8&ratebypass=yes'
[download] Destination: FolkRight Friday - Paganism 101-DdlgHLb5ops.f397.mp4
[download] 100% of 25.52MiB in 00:44
[debug] Invoking downloader on 'https://r3---sn-jpm-15bd.googlevideo.com/videoplayback?nh=%2CEAQ&key=yt6&txp=5533432&initcwndbps=970000&ipbits=0&pl=16&fvip=8&mime=audio%2Fmp4&lmt=1546684919240141&expire=1546789481&gcr=hr&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cexpire&source=youtube&id=o-AOOVPqr3rv8PM1ZDchcDesejfY904z9NydFfGRJ2tCNH&dur=5235.193&mm=31%2C29&gir=yes&c=WEB&mn=sn-jpm-15bd%2Csn-bvvbax-15be&ms=au%2Crdu&mt=1546767745&mv=m&signature=18BE0C223C84C71D8B7C4D60C26BA9620C3E1337.1C41DFB00B17E766C917D69F72A5906DAABF6244&clen=84726539&ip=31.147.127.97&keepalive=yes&ei=CM4xXLLBNM2bgQe5j5bQCQ&requiressl=yes&itag=140&ratebypass=yes'          
[download] Destination: FolkRight Friday - Paganism 101-DdlgHLb5ops.f140.m4a
[download] 100% of 80.80MiB in 02:53
[ffmpeg] Merging formats into "FolkRight Friday - Paganism 101-DdlgHLb5ops.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:FolkRight Friday - Paganism 101-DdlgHLb5ops.f397.mp4' -i 'file:FolkRight Friday - Paganism 101-DdlgHLb5ops.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:FolkRight Friday - Paganism 101-DdlgHLb5ops.temp.mp4'
ERROR:     Last message repeated 1 times
Traceback (most recent call last):
  File "/home/vedranm/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2048, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/vedranm/.local/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 479, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/vedranm/.local/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files                                                                                                                         
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:     Last message repeated 1 times
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://youtu.be/DdlgHLb5ops

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

The download fails when `-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4'` is used. I presume the reason for this issue is that the chosen audio and video formats don't match for some reason and can't be merged to mp4 (please correct me if I'm wrong); I observed that `-f best` instead of `-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4'` works well for this YouTube video.

Available formats are:

```
$ youtube-dl -F https://youtu.be/DdlgHLb5ops
[youtube] DdlgHLb5ops: Downloading webpage
[youtube] DdlgHLb5ops: Downloading video info webpage
[info] Available formats for DdlgHLb5ops:
format code  extension  resolution note
249          webm       audio only DASH audio   58k , opus @ 50k, 31.85MiB
250          webm       audio only DASH audio   73k , opus @ 70k, 40.68MiB
171          webm       audio only DASH audio   99k , vorbis@128k, 58.88MiB
251          webm       audio only DASH audio  126k , opus @160k, 70.99MiB
140          m4a        audio only DASH audio  135k , m4a_dash container, mp4a.40.2@128k, 80.80MiB
160          mp4        256x144    144p   29k , avc1.4d400c, 30fps, video only, 6.14MiB
133          mp4        426x240    240p   33k , avc1.4d4015, 30fps, video only, 8.32MiB
394          mp4        256x144    144p   33k , av01.0.05M.08, 30fps, video only, 8.74MiB
395          mp4        426x240    240p   37k , av01.0.05M.08, 30fps, video only, 11.14MiB
278          webm       256x144    144p   40k , webm container, vp9, 30fps, video only, 8.31MiB
134          mp4        640x360    360p   44k , avc1.4d401e, 30fps, video only, 10.37MiB
396          mp4        640x360    360p   56k , av01.0.05M.08, 30fps, video only, 18.01MiB
135          mp4        854x480    480p   58k , avc1.4d401f, 30fps, video only, 13.21MiB
242          webm       426x240    240p   68k , vp9, 30fps, video only, 12.27MiB
136          mp4        1280x720   720p   89k , avc1.4d401f, 30fps, video only, 20.99MiB
397          mp4        854x480    480p   91k , av01.0.05M.08, 30fps, video only, 25.52MiB
244          webm       854x480    480p  125k , vp9, 30fps, video only, 21.20MiB
243          webm       640x360    360p  127k , vp9, 30fps, video only, 20.87MiB
247          webm       1280x720   720p  239k , vp9, 30fps, video only, 46.06MiB
17           3gp        176x144    small   29k , mp4v.20.3, mp4a.40.2@ 24k (22050Hz), 18.43MiB
36           3gp        320x180    small   62k , mp4v.20.3, mp4a.40.2 (22050Hz), 39.11MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 84.65MiB
18           mp4        640x360    medium  152k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 95.07MiB
22           mp4        1280x720   hd720  162k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)
```

Regardless, without the `-v` flag, the only error message I get is `Last message repeated 1 times` and I have no idea what happened:

```
$ youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' -i https://youtu.be/DdlgHLb5ops
[youtube] DdlgHLb5ops: Downloading webpage
[youtube] DdlgHLb5ops: Downloading video info webpage
[download] FolkRight Friday - Paganism 101-DdlgHLb5ops.f397.mp4 has already been downloaded
[download] 100% of 25.52MiB
[download] FolkRight Friday - Paganism 101-DdlgHLb5ops.f140.m4a has already been downloaded
[download] 100% of 80.80MiB
[ffmpeg] Merging formats into "FolkRight Friday - Paganism 101-DdlgHLb5ops.mp4"
ERROR:     Last message repeated 1 times
```

It would be great if youtube-dl could actually merge formats or download the matching ones, but, if that's not possible, it would be fine if the error message could be improved.

**Comment by dstftw** [comment]
```
[mp4 @ 00000097b3d27100] AV1 muxing is currently not supported.
Could not write header for output file #0 (incorrect codec parameters ?): Not yet implemented in FFmpeg, patches welcome
```

**Comment by dstftw** [comment]
Works fine with latests ffmpeg.

**Comment by vedranmiletic** [comment]
> ```
> [mp4 @ 00000097b3d27100] AV1 muxing is currently not supported.
> Could not write header for output file #0 (incorrect codec parameters ?): Not yet implemented in FFmpeg, patches welcome
> ```

Can youtube-dl actually output that instead of `ERROR:     Last message repeated 1 times`?

**Comment by dstftw** [comment]
No, cause there is no indication where is the actual error message in ffmpeg's output.
