### ISSUE TITLE
Thumbnail file name is incomplete

### ISSUE THREAD

**Issue by tsia** [rg3/youtube-dl#18764]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.02**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--output', u'%(title)s-%(id)s', u'--restrict-filenames', u'--write-thumbnail', u'--write-info-json', u'https://www.youtube.com/watch?v=rALrayKDiB8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.02
[debug] Git HEAD: de0359c0a
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[youtube] rALrayKDiB8: Downloading webpage
[youtube] rALrayKDiB8: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video description metadata as JSON to: 4._Januar_2019_-_Bundespressekonferenz_-_RegPK-rALrayKDiB8.info.json
[youtube] rALrayKDiB8: Downloading thumbnail ...
[youtube] rALrayKDiB8: Writing thumbnail to: 4.jpg
[debug] Invoking downloader on u'https://r1---sn-fuoxu-i5he.googlevideo.com/videoplayback?mt=1546786922&mv=m&txp=5532432&ms=au%2Crdu&ip=2a04%3A4540%3A680e%3A1701%3A0%3A108%3A%3A&requiressl=yes&gir=yes&ipbits=0&mm=31%2C29&mn=sn-fuoxu-i5he%2Csn-i5h7lned&mime=video%2Fwebm&id=o-AG9h-TUHcJt843Ads-PraY1noDmxhtWbo0u3xmoGdwBX&pl=29&shardbypass=yes&expire=1546808637&initcwndbps=1917500&ei=3BgyXL_yNIHv1gKPoKbYBw&dur=3536.440&source=youtube&clen=4293250106&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Chcs%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Cshardbypass%2Csource%2Cexpire&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&fvip=1&key=yt6&lmt=1546668815513415&hcs=yes&beids=9466588&keepalive=yes&itag=313&c=WEB&signature=D6FBA5E5518E6C3ABE26DE843DC8310F96A954EB.BE3D7C7C49F82D6A01E46D946F83ADF26A4B3E69&ratebypass=yes'
[download] Destination: 4._Januar_2019_-_Bundespressekonferenz_-_RegPK-rALrayKDiB8.f313
[download] 100% of 4.00GiB in 02:33
[debug] Invoking downloader on u'https://r1---sn-fuoxu-i5he.googlevideo.com/videoplayback?mt=1546786922&mv=m&txp=5511222&ms=au%2Crdu&ip=2a04%3A4540%3A680e%3A1701%3A0%3A108%3A%3A&requiressl=yes&gir=yes&ipbits=0&mm=31%2C29&mn=sn-fuoxu-i5he%2Csn-i5h7lned&mime=audio%2Fwebm&id=o-AG9h-TUHcJt843Ads-PraY1noDmxhtWbo0u3xmoGdwBX&pl=29&shardbypass=yes&expire=1546808637&initcwndbps=1917500&ei=3BgyXL_yNIHv1gKPoKbYBw&dur=3536.461&source=youtube&clen=45186865&sparams=clen%2Cdur%2Cei%2Cgir%2Chcs%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Cshardbypass%2Csource%2Cexpire&fvip=1&key=yt6&lmt=1546678107086969&hcs=yes&beids=9466588&keepalive=yes&itag=251&c=WEB&signature=551C7D93C0A1B280B5D9EDFB3E9799C0BAFCB5D5.5AEC9169E66C43BF0027A1B78B615C0FA6106BDB&ratebypass=yes'
[download] Destination: 4._Januar_2019_-_Bundespressekonferenz_-_RegPK-rALrayKDiB8.f251
[download] 100% of 43.09MiB in 00:02
[ffmpeg] Merging formats into "4._Januar_2019_-_Bundespressekonferenz_-_RegPK-rALrayKDiB8.webm"
[debug] ffmpeg command line: ffmpeg -y -i 'file:4._Januar_2019_-_Bundespressekonferenz_-_RegPK-rALrayKDiB8.f313' -i 'file:4._Januar_2019_-_Bundespressekonferenz_-_RegPK-rALrayKDiB8.f251' -c copy -map '0:v:0' -map '1:a:0' 'file:4._Januar_2019_-_Bundespressekonferenz_-_RegPK-rALrayKDiB8.temp.webm'
Deleting original file 4._Januar_2019_-_Bundespressekonferenz_-_RegPK-rALrayKDiB8.f313 (pass -k to keep)
Deleting original file 4._Januar_2019_-_Bundespressekonferenz_-_RegPK-rALrayKDiB8.f251 (pass -k to keep)
<end of log>
```

---

the mentioned video (https://www.youtube.com/watch?v=rALrayKDiB8) contains a `.` in the title (4. Januar 2019 - Bundespressekonferenz - RegPK). I added the `--output` option to change the file name. In this case the downloaded thumbnail is just called `4.jpg` instead of `4._Januar_2019_-_Bundespressekonferenz_-_RegPK-rALrayKDiB8.jpg`.
i already had a look in the code but i can't reliably fix the issue myself without breaking something else

**Comment by dstftw** [comment]
Output template must contain `ext`  sequence.
