### ISSUE TITLE
After downloading video is a lot of segments, how to make it automatically merge into a video?

### ISSUE THREAD

**Issue by NoString** [rg3/youtube-dl#18773]
After I download video from www.bilibili.com, it looks like this

xx19251198_part1.flv
xx19251198_part2.flv
xx19251198_part3.flv
xx19251198_part4.flv

How do I get it to merge automatically when the download is complete?

Like this

xx19251198.flv

root@ONEVPS190105040754 ~]# youtube-dl -U
youtube-dl is up-to-date (2019.01.02)

root@ONEVPS190105040754 ~]# ffmpeg -V
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers

**Comment by dstftw** [comment]
By hand using ffmpeg.
