### ISSUE TITLE
Video Lecture Support

### ISSUE THREAD

**Issue by sirinath** [rg3/youtube-dl#1877]
1) Lecture

http://videolectures.net/netadis2013_monasson_graph_theory/

2) Conference

http://videolectures.net/kdd2013_chicago/

3) Use

http://videolectures.net/fabian_abel/

4) Organisations

http://videolectures.net/mlvj/

**Comment by dstftw** [comment]
All kinds of URLs will be supported in the next version apart from 4 for which I didn't find any video.
