### ISSUE TITLE
Erome downloading 2 of the same file

### ISSUE THREAD

**Issue by goodboi69** [rg3/youtube-dl#18778]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.01.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92405-ge24a754916, ffprobe N-92405-ge24a754916
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

Erome is downloading 2 of the same video. Here's an example: https://www.erome.com/a/0Dup947V
And here is the log
```
[generic] 0Dup947V: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 0Dup947V: Downloading webpage
[generic] 0Dup947V: Extracting information
[download] Downloading playlist: Barista.ashleigh
[generic] playlist Barista.ashleigh: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[download] Destination: Barista.ashleigh (1)-0Dup947V-1.mp4
[download] 100% of 16.26MiB in 00:12
[download] Downloading video 2 of 2
[download] Destination: Barista.ashleigh (2)-0Dup947V-2.mp4
[download] 100% of 16.26MiB in 00:14
[download] Finished downloading playlist: Barista.ashleigh
```

**Comment by dstftw** [comment]
Expected. Video is embedded twice on the page.

**Comment by goodboi69** [comment]
Maybe there is a fix or a workaround for this... Closing the issue without even trying to come up with a solution isn't the best way to handle the issue.

**Comment by sockpupeteer** [comment]
I've created a script to help out with this issue, as youtube-dl works as intended on that site.
https://gist.github.com/sockpupeteer/9f9aee21fae33c7fa8692f0a5cd528b6

Usage:
```sh
$ ruby erome.rb
Usage: erome.rb --url=URL --name=NAME
        --name=NAME                  Name of the actor/actress to create a folder for
        --url=URL                    URL of Ero.me album to download
        --dry-run                    Simulate download
```

**Comment by extension59** [comment]
@goodboi69 There should be. When called with  `--print-json` you can see the same url is listed twice, so I'm not sure why the default behaviour wouldn't be to deduplicate at this point. Of course this app supports so many websites, any change would have broad reaching impact, but I can't think of a reason why you'd want to download the same video url twice...

**Comment by dirkf** [comment]
`--playlist-items 1`
