### ISSUE TITLE
ERROR: u'22' is not a valid URL. Set

### ISSUE THREAD

**Issue by DarthMoulByte** [rg3/youtube-dl#18787]
it maybe an error of my syntax but I'm not sure, I just followed the simplest form of its manual and this was what I got in **Debian 9.5 (i686)**

no se si se considera un bug, pero seria muy agradable que me explicaran un poco para saber si se trata de un bug
url used in the line code:
[Video Work Low Poly Wall YOUTUBE.COM](https://www.youtube.com/watch?v=fusllaMwlkw
)![2019-01-09_00-23-59](https://user-images.githubusercontent.com/24207840/50880730-02433000-13a5-11e9-9d25-fc5f53e17a29.png)
![2019-01-09_00-39-57](https://user-images.githubusercontent.com/24207840/50881462-459e9e00-13a7-11e9-87eb-dc668e9c20a3.png)

**Comment by dstftw** [comment]
`-f` not `-F`.

**Comment by DarthMoulByte** [comment]
@dstftw ha Thank you so much, and my apologies for the carelessness
