### ISSUE TITLE
Pornhub issue

### ISSUE THREAD

**Issue by RittMan77** [rg3/youtube-dl#18794]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.02**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

[X ] Other

---
cecil@cecil-Lenovo-ideapad-330-15IGM:~$ youtube-dl -u × -p × https://www.pornhub.com/playlist/47277961 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.pornhub.com/playlist/47277961', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.02
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-43-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: none
[debug] Proxy map: {}
[PornHubPlaylist] 47277961: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

cecil@cecil-Lenovo-ideapad-330-15IGM:~$ youtube-dl -U
youtube-dl is up-to-date (2019.01.02)
cecil@cecil-Lenovo-ideapad-330-15IGM:~$ 

Thank you!

---

**Comment by rautamiekka** [comment]
If I were you I'd change the pw on PornHub.

**Comment by dstftw** [comment]
Playlist does not exist.

**Comment by RittMan77** [comment]
Thank you!
How is that possible, i pulled the URL directly out of the browser window?

**Comment by dstftw** [comment]
Most likely it's got deleted after you initially opened it in browser.

**Comment by RittMan77** [comment]
Ok, thank you for the heads up!

**Comment by RittMan77** [comment]
My apologies, and I will confess to being new to even using a command line.  I really appreciate your patience.  When I logged back in, I found the playlist in tact.  I played with the commands a bit, and encountered similar results.  Any input is appreciated, and I'm sorry if I'm belabouring a point.
I have attached below several attempts with the same playlist, as well as a screenshot.
Thank you!
cecil@cecil-Lenovo-ideapad-330-15IGM:~$ youtube-dl -u Smaloney -p zote8esa https://www.pornhubpremium.com/playlist/47277961/Billy and Seth
[generic] Billy: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Billy: Downloading webpage
[generic] Billy: Extracting information
ERROR: Unsupported URL: https://www.pornhubpremium.com/playlist/47277961/Billy
cecil@cecil-Lenovo-ideapad-330-15IGM:~$ youtube-dl -u Smaloney -p zote8esa https://www.pornhub.com/playlist/47277961/Billy and Seth
[PornHubPlaylist] 47277961: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: 47277961
[PornHubPlaylist] playlist 47277961: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: 47277961
ERROR: u'and' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:and" ) to search YouTube
cecil@cecil-Lenovo-ideapad-330-15IGM:~$ youtube-dl https://www.pornhub.com/playlist/47277961/Billy and Seth -u Smaloney -p zote8esa
[PornHubPlaylist] 47277961: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
cecil@cecil-Lenovo-ideapad-330-15IGM:~$ youtube-dl https://www.pornhub.com/playlist/Jockplaylist/Billy and Seth -u Smaloney -p zote8esa
[generic] Billy: Requesting header
WARNING: Could not send HEAD request to https://www.pornhub.com/playlist/Jockplaylist/Billy: HTTP Error 404: Not Found
[generic] Billy: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
cecil@cecil-Lenovo-ideapad-330-15IGM:~$ youtube-dl https://www.pornhub.com/playlist/Jockplaylist/BillyandSeth -u Smaloney -p zote8esa
[generic] BillyandSeth: Requesting header
WARNING: Falling back on generic information extractor.
[generic] BillyandSeth: Downloading webpage
[generic] BillyandSeth: Extracting information
ERROR: Unsupported URL: https://www.pornhub.com/playlist/Jockplaylist/BillyandSeth
cecil@cecil-Lenovo-ideapad-330-15IGM:~$ youtube-dl https://www.pornhub.com/playlist/jockplaylist/billyandseth -u Smaloney -p zote8esa
[generic] billyandseth: Requesting header
WARNING: Falling back on generic information extractor.
[generic] billyandseth: Downloading webpage
[generic] billyandseth: Extracting information
ERROR: Unsupported URL: https://www.pornhub.com/playlist/jockplaylist/billyandseth
cecil@cecil-Lenovo-ideapad-330-15IGM:~$ youtube-dl https://www.pornhub.com/playlist/jockplaylist/47277961 -u Smaloney -p zote8esa
[generic] 47277961: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 47277961: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
cecil@cecil-Lenovo-ideapad-330-15IGM:~$ youtube-dl https://www.pornhub.com/playlist/jockplaylist/47277961 -u Smaloney -p zote8esa --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.pornhub.com/playlist/jockplaylist/47277961', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.02
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-43-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 47277961: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 47277961: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

cecil@cecil-Lenovo-ideapad-330-15IGM:~$ 

![screenshot from 2019-01-09 19-04-21](https://user-images.githubusercontent.com/46478515/50937718-e5f5d080-1442-11e9-9bcc-33d178ba76af.png)

**Comment by RittMan77** [comment]
Hello!

I did encounter additional issues, and reposted in the chat.  My apologies,
and thank you so far.
