### ISSUE TITLE
YouTube livestreams are broken

### ISSUE THREAD

**Issue by MRDHR** [rg3/youtube-dl#18799]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.youtube.com/watch?v=FiLHJ1f-VqE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.02
[debug] Python version 2.7.5 (CPython) - Linux-4.20.0-1.el7.elrepo.x86_64-x86_64-with-centos-7.6.1810-Core
[debug] exe versions: ffmpeg 4.1-static, ffprobe 4.1-static
[debug] Proxy map: {}
[youtube] FiLHJ1f-VqE: Downloading webpage
[youtube] FiLHJ1f-VqE: Downloading video info webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1957, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.

Hi,

Youtube livestreams doesn't work anymore.
Please, fix it.
Thanks.

**Comment by palich2000** [comment]
but it still works

curl -sL "https://www.youtube.com/watch?v=rU4Fw5HYEJE" | grep -oP "ytplayer.config =\K.*?}(?=;)" | jq . | grep m3u8 | sed 's/^.*hlsManifestUrl//;s/m3u8.*/m3u8/;s/^.*https/https/'

**Comment by 1-877-448-4820** [comment]
# When does this error occur?

When you feed _youtube-dl_ a URI of a YouTube live stream **page** (e.g. `https://youtu.be/rU4Fw5HYEJE`).

# Workaround

As @palich2000 noted, manually getting the `.m3u8` URI and feeding it to _youtube-dl_ works.

```Javascript
// https://youtu.be/rU4Fw5HYEJE
JSON.parse(ytplayer.config.args.player_response).streamingData.hlsManifestUrl
// → https://manifest.googlevideo.com/api/manifest/……/index.m3u8
```

But it's _youtube-dl_'s job, right?

**Comment by 1-877-448-4820** [comment]
@dstftw Has it been fixed? Why do you close this issue, may I ask?

**Comment by 1-877-448-4820** [comment]
Guys, [version 2019.01.10](https://github.com/rg3/youtube-dl/releases/tag/2019.01.10) has been released. Go grab it and say “thanks” to the developers.

**Comment by vitich** [comment]
> Guys, [version 2019.01.10](https://github.com/rg3/youtube-dl/releases/tag/2019.01.10) has been released. Go grab it and say “thanks” to the developers.

I tried the new version but there`s not m3u8 url in JSON (with -J key)
What am I doing wrong?

**Comment by 1-877-448-4820** [comment]
@vitich Just feed it an `https://youtu.be/……` URI to download the video.

**Comment by vitich** [comment]
> @vitich Just feed it an `https://youtu.be/……` URI to download the video.
> Picking the `.m3u8` up is not _youtube-dl_'s job.
Hm... Are you offering me to download a live stream?
Nice... 
Did you carefully read the name of the issue?
LIVESTREAMS ARE BROKEN!
Everything worked exactly this way for several years and suddenly it turned out that this is no longer youtube-dl`s job. 
By the way - exactly a year ago there was a similar situation :)
@palich2000 - I guess they offer us to look for alternative ways...

**Comment by dimyself** [comment]
It doesnt work for me? This is a current livestream. 

 youtube-dl -Fv https://www.youtube.com/watch?v=DODXh3UJNgc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-Fv', 'https://www.youtube.com/watch?v=DODXh3UJNgc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.02
[debug] Python version 3.7.2 (CPython) - Linux-4.20.0-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg n4.1, ffprobe n4.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] DODXh3UJNgc: Downloading webpage
[youtube] DODXh3UJNgc: Downloading video info webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1957, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.

Just as a side note. Streamlink also isn't working... Did youtube change their page??
