### ISSUE TITLE
"geo-restricted" and "account needed"

### ISSUE THREAD

**Issue by seyoum** [rg3/youtube-dl#18793]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.02**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

I am quite new to this so I am not sure how to go about it. I recently found out that one of my favorite streaming sites does not work with yt-dl. I did a quick search and found some issues related to that site, with labels on them such as "geo-restricted" and "account needed". The issue was closed but the problem seems to still be present in the latest version.

As I really would like support for the site, my question is, what do these labels mean? Is there anything I can contribute with such as account or location? Would love to help, but I am not a programmer.

![2019-01-09 16_48_58-tv2 doesn t work for sumo tv2 no issue 9130 rg3_youtube-dl github](https://user-images.githubusercontent.com/15233794/50911386-0ff1c780-1430-11e9-8d1c-e42beced8a4c.png)

**Comment by dstftw** [comment]
1. The [issue](https://github.com/rg3/youtube-dl/issues/9130) is not and was not closed.
2. Labels mean precisely what is spelled in them. Both may or may not be blockers depending on whether it's possible to bypass geo restriction or obtain a free account. You can contribute though you get no guarantees regarding when support will be added.

**Comment by Hrxn** [comment]
Yes, providing an account in such cases will definitely help, especially if said account cannot be obtained easily, or, for example, is georestricted in any way.
