### ISSUE TITLE
youtube - how to get live stream url (.m3u8)?

### ISSUE THREAD

**Issue by vitich** [rg3/youtube-dl#18802]
I can get m3u8 url by this command:
curl -sL "https://www.youtube.com/watch?v=rU4Fw5HYEJE" | grep -oP "ytplayer.config =\K.*?}(?=;)" | jq . | grep m3u8 | sed 's/^.*hlsManifestUrl//;s/m3u8.*/m3u8/;s/^.*https/https/'

https://manifest.googlevideo.com/api/manifest/hls_variant/id/rU4Fw5HYEJE.0/ei/5243XNzvOpGG7QTiqLiACA/gcr/ua/itag/0/dover/11/go/1/expire/1547158344/signature/D9AB0A5E19B395CCC28754DC0172A13CD9BF12FC.12683B1BC15E7A39311BA028A7F6A495D10B0415/requiressl/yes/playlist_type/DVR/keepalive/yes/maudio/1/ip/31.223.225.203/key/yt6/source/yt_live_broadcast/ipbits/0/ratebypass/yes/hfr/1/sparams/ei%2Cgcr%2Cgo%2Chfr%2Cid%2Cip%2Cipbits%2Citag%2Cmaudio%2Cplaylist_type%2Cratebypass%2Crequiressl%2Csource%2Cexpire/file/index.m3u8

But if I run 'youtube-dl -J https://www.youtube.com/watch?v=rU4Fw5HYEJE | jq .'  I don`t see any m3u8 in JSON

**Comment by vitich** [comment]
What issue was duplicated?

**Comment by 1-877-448-4820** [comment]
Do not ever ask bash scripting here. Don't you see _youtube-dl_'s getting tons of goddamn issues?

**Comment by 1-877-448-4820** [comment]
Just wait for him to provide us a hotfix for the change YouTube's just made.

**Comment by vitich** [comment]
> Do not ever ask bash scripting here. Don't you see _youtube-dl_'s getting tons of goddamn issues?

Take it easy, please :)
I saw the ticket was closed and a new version appeared. I`ve tried but still no luck.
I thought they would fix it first, then close the task...
And bash scripting is here just to show that youtube gives me the m3u8 url
Good luck.
