### ISSUE TITLE
Connecting to proxy (407 Error)

### ISSUE THREAD

**Issue by TheGr33k** [rg3/youtube-dl#18817]
I  am unable to use a proxy with youtube-dl.I get the following error

`Unable to download webpage: HTTP Error 407: Proxy Authentication Required (caused by HTTPError());`

My  proxy works as i am able to connect to the proxy in my browser just fine.

 ```
$toLoad = "https://www.youtube.com/watch?v=AtKZKl7Bgu0";
$command = "youtube-dl --no-warnings --no-cache-dir  --proxy sock://lum-customer-hl_1234b789-zone-static-country-us:22221111asz@zproxy.lum-superproxy.io:22225 --no-check-certificate --user-agent \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36\" --socket-timeout 30  \"$toLoad\" -4  --dump-json";
$yt_json = exec($command.' 2>&1');
echo $yt_json;
```

However if i `echo` the command and run it in shell, it works just fine , making me believe something is wrong with escaping with exec

**Comment by dstftw** [comment]
No such scheme `sock`.

**Comment by TheGr33k** [comment]
Its a typo mistake , i actually use http

**Comment by TheGr33k** [comment]
@dstftw  see my edit and kindly reopen

**Comment by dstftw** [comment]
Read issue template and provide compete info in new issue.
