### ISSUE TITLE
--no-proxy option

### ISSUE THREAD

**Issue by xubuntu4iran** [rg3/youtube-dl#1882]
I need this option for youtube-dl not using proxy in config file

**Comment by wumo** [comment]
When I type `youtube-dl --proxy '' https://www.bilibili.com/video/avxxxxxxxx`, it always complains:
```
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```
I have `youtube-dl.conf` saved in `USER_HOME`
