### ISSUE TITLE
What was the YouTube change that broke live streams in YouTube-dl?

### ISSUE THREAD

**Issue by bonacker** [rg3/youtube-dl#18825]
I have looked, but I can't find any discussion about the YouTube change affecting live YT streams. I only see that a new version of YouTube-dl fixed the issue for which I thank the coders.

I am wondering what the change was. I notice that VLC 3.x in Windows that used to be able to extract and play the .m3u8 from YouTube URLs like https://www.youtube.com/watch?v=NCLBieIT0l0 now will not work on live streams while continuing to work on recorded videos. TIA for any info.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/commit/c3e543893bfba7faa7c13e53fbe6b60f936b81f1
