### ISSUE TITLE
Wistia jsonp link, not downloading video, downloads jsonp instead

### ISSUE THREAD

**Issue by mysticaltech** [rg3/youtube-dl#18823]
Trying to download video with:
Playlist url for single video: http://fast.wistia.com/embed/medias/10a3mcojl6.jsonp
Playlist url for single video: http://fast.wistia.com/embed/medias/10a3mcojl6.json

Youtube-dl does not find the videos and just downloads the jsonp or json file instead.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 2.7.15 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
```

**Comment by dstftw** [comment]
youtube-dl `wistia:10a3mcojl6`.

**Comment by mevaka** [comment]
> `youtube-dl wistia:10a3mcojl6`.

how this 'youtube-dl' thing can find the address of video ? 

I know there must be something like that 'http://embed.wistia.com/deliveries/ergaegfg9fgga0df1c3e67005fe62e3rra027d2367.bin' in somewhere, and If I can find this address , I will be able to download the video . 

Normally ;
If you add '.jsonp/ ext to iframe address , you must get a file that contains .bin address.

For example : 
http://fast.wistia.com/embed/medias/n6rrpw1v1k.jsonp

But if you tried same thing for some addresses I get 

window['wistiajsonp-/embed/iframe/wxehzve7hh.jsonp'] = {"error":true,"iframe":true};

So , in this situation, how can I find this .bin address without any program ?

**Comment by mysticaltech** [comment]
What counts is the id of n6rrpw1v1k in your case, then youtube-dl "knows" how wistia works, it knows that it needs to go fetch "http://fast.wistia.com/embed/medias/n6rrpw1v1k.jsonp" and find the best quality video in there. Also, always make sure you are using the latest version of the tool! Good luck.
![Screenshot 2020-04-19 at 00 02 00](https://user-images.githubusercontent.com/518555/79672357-5dcbb280-81d1-11ea-97a1-7911bb4478aa.png)
