### ISSUE TITLE
Is it possible to finish the recording at "last message repeated" ...?

### ISSUE THREAD

**Issue by raketenjonny1337** [rg3/youtube-dl#18845]
[https @ 000001f4e025cec0] Opening 'https://manifest.googlevideo.com/api/manifest/hls_playlist/id/txQcFYI1oI8.0/itag/301/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D299/hls_chunk_host/r2---sn-4g5e6nld.googlevideo.com/gcr/de/ei/Ys07XKPAJJmI1wabwrzgAQ/playlist_type/DVR/initcwndbps/8230/mm/32/mn/sn-4g5e6nld/ms/lv/mv/m/pl/35/dover/11/keepalive/yes/mt/1547423017/disable_polymer/true/ip/2003:d6:f3ef:646c:e8c0:17f0:4d7a:28dc/ipbits/0/expire/1547444674/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,gcr,ei,playlist_type,initcwndbps,mm,mn,ms,mv,pl/signature/59180E8C9064939DAFE8F691323117CDA736B981.372D45940EBC5EDA02EDBCCE2E4C214795F50FF8/key/dg_yt0/playlist/index.m3u8' for reading
    Last message repeated 38 times

Is there the possibility if the Youtube livestream is finished to save the video file clean? without that the file becomes an unusable .part file? If I press strg + c the file will not be saved properly. If I close the program while the stream is still running the stream is saved clean. So the error comes only when the stream is offline and the "Last message repeated ..." comes.

**Comment by dstftw** [comment]
It will be finished correctly if Ctrl+C is pressed once.
