### ISSUE TITLE
Twitch live not working

### ISSUE THREAD

**Issue by dimka11** [rg3/youtube-dl#1884]
[justin.tv] ibeluckyyy: Extracting information
[justin.tv] ibeluckyyy: Downloading video information from 0 to 100
[justin.tv] ibeluckyyy: Downloading video info JSON
ERROR: unable to download video info JSON: HTTP Error 404: NOT FOUND; please rep
ort this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --
verbose flag and include its complete output. Make sure you are using the latest
 version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
Twitch.tv streams will be supported in the next version. Thanks for the report.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.23 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
