### ISSUE TITLE
Cannot download specific video: unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by maple3142** [rg3/youtube-dl#18848]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

<details>
<summary>output of 2019.01.10</summary>

```
C:\Users\Administrator>youtube-dl --version
2019.01.10

C:\Users\Administrator>youtube-dl -v "https://www.youtube.com/watch?v=3GCBekC5KX0"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=3GCBekC5KX0']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2019.01.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4.2
[debug] Proxy map: {}
[youtube] 3GCBekC5KX0: Downloading webpage
[youtube] 3GCBekC5KX0: Downloading video info webpage
[youtube] {18} signature length 43.40, html5 player vfl_235rs
[youtube] {36} signature length 43.40, html5 player vfl_235rs
[youtube] {17} signature length 43.40, html5 player vfl_235rs
[youtube] {137} signature length 43.40, html5 player vfl_235rs
[youtube] {136} signature length 43.40, html5 player vfl_235rs
[youtube] {135} signature length 43.40, html5 player vfl_235rs
[youtube] {134} signature length 43.40, html5 player vfl_235rs
[youtube] {133} signature length 43.40, html5 player vfl_235rs
[youtube] {160} signature length 43.40, html5 player vfl_235rs
[youtube] {140} signature length 43.38, html5 player vfl_235rs
[youtube] 3GCBekC5KX0: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vfl_235rs/en_US/base.js
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r1---sn-ucj-u2xl.googlevideo.com/videoplayback?mt=1547464924&mv=m&pl=22&id=o-AJ7akSd2SmoddHCW_m6ZF-7A67OH-xm5DyvLMKJGG7WK&ei=OHE8XKXbLZDaqQGBsqmACg&ms=au%2Crdu&fvip=6&ip=123.110.192.124&expire=1547486616&source=yt_otf&mm=31%2C29&mn=sn-ucj-u2xl%2Csn-un57en7s&itag=137&mime=video%2Fmp4&dur=0.000&otf=1&ipbits=0&sparams=aitags%2Cdur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cotf%2Cotfp%2Cpl%2Crequiressl%2Csource%2Cexpire&aitags=133%2C134%2C135%2C136%2C137%2C160&lmt=1460759158582799&requiressl=yes&c=WEB&key=yt6&initcwndbps=1555000&keepalive=yes&otfp=1&signature=A34692857BC0E0ABDF355C26A0F1040812AFC0DA.66F17D3AF2FA68DB3F091800708813A7C87E786B&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\YoutubeDL.py", line 1903, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\YoutubeDL.py", line 1848, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\YoutubeDL.py", line 2212, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

</details>

### Description of your *issue*, suggested solution and other information

I can't download https://www.youtube.com/watch?v=3GCBekC5KX0, because it said that it doesn't exist.
However, the video does exist and it can be browsed by browser.

**Comment by maple3142** [comment]
I couldn't find the open issue that this issue is duplicate of, or is this one a unsolvable problem?

**Comment by remitamine** [comment]
Duplicate of #18804.

**Comment by rogerclarkmelbourne** [comment]
I seem to get the same errors with 

https://www.youtube.com/watch?v=GCONtOlNRJM

**Comment by medbenchohra** [comment]
Requesting the webm format works. Turns out the problem is in fetching the mp4 format.

-f "webm[height=720]"          instead of        -f "best[height<=720]"

Explanation : #17148
