### ISSUE TITLE
Pornhub unable to extract title

### ISSUE THREAD

**Issue by cafecafe** [rg3/youtube-dl#18842]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.10**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', '%(title)s.%(ext)s', 'https://www.pornhub.com/view_video.php?viewkey=1616591214']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.01.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92722-gf22fcd4483, ffprobe N-92722-gf22fcd4483
[debug] Proxy map: {}
[PornHub] 1616591214: Downloading pc webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\extractor\pornhub.py", line 171, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\extractor\common.py", line 983, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

The biggest problem is that this error happens around 50% of the time. I'm not sure if this is a connectivity issue. It might work flawlessly for the same video a few times and then happen 2 times in a row for the same video, then work again.

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by cafecafe** [comment]
Command:

youtube-dl -v -o  "%(title)s.%(ext)s" https://www.pornhub.com/view_video.php?viewkey=1616591214 --dump-pages

Output:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', '%(title)s.%(ext)s', 'https://www.pornhub.com/view_video.php?viewkey=1616591214', '--dump-pages']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.01.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92722-gf22fcd4483, ffprobe N-92722-gf22fcd4483
[debug] Proxy map: {}
[PornHub] 1616591214: Downloading pc webpage
[PornHub] Dumping request to http://www.pornhub.com/view_video.php?viewkey=1616591214
PGh0bWw+PGhlYWQ+PHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiPjwhLS0KZnVuY3Rpb24gbGVhc3RGYWN0b3IobikgewogaWYgKGlzTmFOKG4pIHx8ICFpc0Zpbml0ZShuKSkgcmV0dXJuIE5hTjsKIGlmICh0eXBlb2YgcGhhbnRvbSAhPT0gJ3VuZGVmaW5lZCcpIHJldHVybiAncGhhbnRvbSc7CiBpZiAodHlwZW9mIG1vZHVsZSAhPT0gJ3VuZGVmaW5lZCcgJiYgbW9kdWxlLmV4cG9ydHMpIHJldHVybiAnbm9kZSc7CiBpZiAobj09MCkgcmV0dXJuIDA7CiBpZiAobiUxIHx8IG4qbjwyKSByZXR1cm4gMTsKIGlmIChuJTI9PTApIHJldHVybiAyOwogaWYgKG4lMz09MCkgcmV0dXJuIDM7CiBpZiAobiU1PT0wKSByZXR1cm4gNTsKIHZhciBtPU1hdGguc3FydChuKTsKIGZvciAodmFyIGk9NztpPD1tO2krPTMwKSB7CiAgaWYgKG4laT09MCkgICAgICByZXR1cm4gaTsKICBpZiAobiUoaSs0KT09MCkgIHJldHVybiBpKzQ7CiAgaWYgKG4lKGkrNik9PTApICByZXR1cm4gaSs2OwogIGlmIChuJShpKzEwKT09MCkgcmV0dXJuIGkrMTA7CiAgaWYgKG4lKGkrMTIpPT0wKSByZXR1cm4gaSsxMjsKICBpZiAobiUoaSsxNik9PTApIHJldHVybiBpKzE2OwogIGlmIChuJShpKzIyKT09MCkgcmV0dXJuIGkrMjI7CiAgaWYgKG4lKGkrMjQpPT0wKSByZXR1cm4gaSsyNDsKIH0KIHJldHVybiBuOwp9CmZ1bmN0aW9uIGdvKCkgewogdmFyIHA9MTQwNTg5NDQzNTQzODsgdmFyIHM9MzEzMTAzMzEwOTsgdmFyIG47CmlmICgocyA+PiAxNCkgJiAxKXArPS8qIDEyMDg4NjEwOCoKKi83MzQ1NDY4MCoJMTc7IGVsc2UgCXAtPTgwNDk5NzMqLyogMTIwODg2MTA4KgoqLzE1Oy8qCnArPSAqL2lmICgocyA+PiAxNSkgJiAxKS8qCmVsc2UgcC09CiovcCs9NzI3OTA3MDkqMTY7CmVsc2UgLyoKKjEzOwoqL3AtPQoxMTA0MDg5ODkqLyoKZWxzZSBwLT0KKi8xNjtpZiAoKHMgPj4gNykgJiAxKQpwKz0xOTEyMzAxNDgqLyoKKjEzOwoqLzg7LyoKKjEzOwoqL2Vsc2UgCnAtPQo4MDkzMTM3NyovKiAxMjA4ODYxMDgqCiovODsvKgpwKz0gKi9pZiAoKHMgPj4gMikgJiAxKQlwKz0vKiAxMjA4ODYxMDgqCiovMjY4MDUyMDcwKgk1OyBlbHNlIHAtPQk0NjczMzkyNDkqLyoKcCs9ICovMzsvKgpwKz0gKi9pZiAoKHMgPj4gMTApICYgMSkvKgoqMTM7CiovcCs9CTEzMDM5ODY5NCovKgplbHNlIHAtPQoqLzEzOy8qCnArPSAqL2Vsc2UgcC09IDEyMjY5NTAyMyovKgplbHNlIHAtPQoqLzExOy8qIDEyMDg4NjEwOCoKKi8gcC09NDg0OTU2OTI4OTsKIG49bGVhc3RGYWN0b3IocCk7CnsgZG9jdW1lbnQuY29va2llPSJSTktFWT0iK24rIioiK3AvbisiOiIrcysiOjIwMzI3MDc2NDM6MSI7CiAgZG9jdW1lbnQubG9jYXRpb24ucmVsb2FkKHRydWUpOyB9Cn0KLy8tLT48L3NjcmlwdD48L2hlYWQ+Cjxib2R5IG9ubG9hZD0iZ28oKSI+CkxvYWRpbmcgLi4uCjwvYm9keT4KPC9odG1sPgo=
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\extractor\pornhub.py", line 171, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\extractor\common.py", line 983, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Duplicate of #5930.
