### ISSUE TITLE
YouTube 4K live streams unavailable

### ISSUE THREAD

**Issue by zoqaeski** [rg3/youtube-dl#18840]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl -v -f 308+140 'https://www.youtube.com/watch?v=lMd8XRmRZA8'
[debug] System config: []
[debug] User config: ['--output', '%(title)s_%(format_id)s.%(ext)s',
'--continue', '--format', 'bestvideo[height <=?
1440][ext=webm]+bestaudio[ext=webm]/bestvideo[height <=? 1440]+bestaudio/best',
'--merge-output-format', 'mkv']
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '308+140',
'https://www.youtube.com/watch?v=lMd8XRmRZA8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 3.7.2 (CPython) -
Linux-4.20.0-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg n4.1, ffprobe n4.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] lMd8XRmRZA8: Downloading webpage
[youtube] lMd8XRmRZA8: Downloading video info webpage
[youtube] lMd8XRmRZA8: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 804, in extract_info return self.process_ie_result(ie_result, download, extra_info) 
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 858, in process_ie_result return self.process_video_result(ie_result, download=download) 
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1628, in process_video_result expected=True) youtube_dl.utils.ExtractorError: requested format not available 

<end of log>
```

---

### Description of your *issue*, suggested solution and other information

There are a number of unlisted 4K live-streamed videos that play in resolutions greater than 1080p in the browser, but attempting to download the files results in an error, with an unavailable format error. However, the browser "stats for nerds" popup implies that the desired formats are in fact being played:

![screenshot-youtube-dl-issue](https://user-images.githubusercontent.com/172912/51084362-39865800-177c-11e9-8861-7ca03bb4a351.png)

**Comment by dstftw** [comment]
DASH lives are not supported.
