### ISSUE TITLE
Support invidio.us directly without using the youtube exctractor

### ISSUE THREAD

**Issue by pExeen** [rg3/youtube-dl#18859]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (n your *issue* requires account credentials please provide them or explain how one can obtain them.
encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs suppn your *issue* requires account credentials please provide them or explain how one can obtain them.
ort for which should be included (replace following example URLs by **yours**):
- Single video: https://invidio.us/watch?v=5JRojRIA1ng
- Channel: https://invidio.us/channel/UCeZLO2VgbZHeDcongKzzfOw
- Playlist: https://invidio.us/playlist?list=PL63F0C78739B09958

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I would love if youtube-dl supported using invidio.us without using the youtube extractor.
Here is there [API documentation](https://github.com/omarroth/invidious/wiki/API).

**Comment by dstftw** [comment]
That's totally pointless.

**Comment by wjtk4444** [comment]
I'd like to suggest re-opening this issue as there is a valid reason for that to happen. Invidio.us provides a proxy-like functionality that allows user to watch a video without connecting directly to google servers.

Example - adding a `&local=true` argument to the url enables the proxy.
https://invidio.us/watch?v=LbjcaMAhJRQ
https://invidio.us/watch?v=LbjcaMAhJRQ&local=true

**Comment by arankaren** [comment]
Yes! the streams is available in `https://invidio.us/api/v1/videos/qmOLtTGvsbM?fields=formatStreams,adaptiveFormats&pretty=1` for example.

Please reopen this issue. To extract the videos with DRM signature directly from invidio.us would be a **second** option. **First** directly **from YT** if it **fails from Invidio.us** and is **fails invidio from youtube extractor sig**.

**Comment by gnouts** [comment]
Hi, I'd like to understand...
In my case (and [many others](https://github.com/ytdl-org/youtube-dl/issues?utf8=%E2%9C%93&q=error+429)), my ip is often banned resulting in "Too many requests" error.
I tried using invidio.us url instead but I still get the error.

Would using invidio.us api instead of youtube extractor solve my case ?

If that's correct, it would not be "totally pointless", judging the number of issue with Error429 ...
