### ISSUE TITLE
best video incorrectly chosen

### ISSUE THREAD

**Issue by hoppeth** [rg3/youtube-dl#18858]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.10**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

youtube-dl is incorrectly chosing which video quality is the best video quality

in the output below, we have the following available:
- 248          webm       1920x1080  1080p 1722k , vp9, 30fps, video only, 24.77MiB
but it has instead chosen
- 18           mp4        640x360    medium  351k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 13.93MiB (best)

---

# youtube-dl -v --list-formats https://www.youtube.com/watch?v=Uekmck81_Cg&list=PL63ZO-jXFTasqvj7WdEFQ6QtG6UBrl9CR
[1] 28354
# [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--list-formats', u'https://www.youtube.com/watch?v=Uekmck81_Cg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-39-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Uekmck81_Cg: Downloading webpage
[youtube] Uekmck81_Cg: Downloading video info webpage
[info] Available formats for Uekmck81_Cg:
format code  extension  resolution note
249          webm       audio only DASH audio   64k , opus @ 50k, 2.17MiB
250          webm       audio only DASH audio   83k , opus @ 70k, 2.87MiB
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k, 5.13MiB
171          webm       audio only DASH audio  135k , vorbis@128k, 4.85MiB
251          webm       audio only DASH audio  163k , opus @160k, 5.67MiB
160          mp4        256x144    144p   50k , avc1.4d400c, 30fps, video only, 730.83KiB
133          mp4        426x240    240p   90k , avc1.4d4015, 30fps, video only, 1.22MiB
242          webm       426x240    240p  122k , vp9, 30fps, video only, 2.21MiB
278          webm       256x144    144p  123k , webm container, vp9, 30fps, video only, 1.61MiB
134          mp4        640x360    360p  161k , avc1.4d401e, 30fps, video only, 2.06MiB
135          mp4        854x480    480p  236k , avc1.4d401f, 30fps, video only, 2.69MiB
243          webm       640x360    360p  292k , vp9, 30fps, video only, 3.93MiB
136          mp4        1280x720   720p  341k , avc1.4d401f, 30fps, video only, 4.50MiB
244          webm       854x480    480p  381k , vp9, 30fps, video only, 3.97MiB
247          webm       1280x720   720p  862k , vp9, 30fps, video only, 10.51MiB
137          mp4        1920x1080  1080p 1214k , avc1.640028, 30fps, video only, 11.25MiB
248          webm       1920x1080  1080p 1722k , vp9, 30fps, video only, 24.77MiB
17           3gp        176x144    small   40k , mp4v.20.3, mp4a.40.2@ 24k (22050Hz), 1.59MiB
36           3gp        320x180    small  121k , mp4v.20.3, mp4a.40.2 (22050Hz), 4.81MiB
18           mp4        640x360    medium  351k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 13.93MiB (best)

[1]+  Done                    youtube-dl -v --list-formats https://www.youtube.com/watch?v=Uekmck81_Cg

--

"By default youtube-dl tries to download the best available quality, i.e. if you want the best quality you don't need to pass any special options, youtube-dl will guess it for you by default."
- is this a code bug or documentation error?

**Comment by dstftw** [comment]
Bother to read FAQ on what does `best` means.
