### ISSUE TITLE
FFmpegExtractAudio not extracting correct format

### ISSUE THREAD

**Issue by martmists** [rg3/youtube-dl#18868]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
<unknown how to get with embedding but here's my best efforts>
encoding: utf-8
youtube-dl version 2019.01.16
Python version 3.7.2 Python 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
ffmpeg version n4.1 Copyright (c) 2000-2018 the FFmpeg developers built with gcc 8.2.1 (GCC) 20180831
```

---

### Description of your *issue*, suggested solution and other information

While embedding Youtube-DL and using the following options:

```python
{
    "format": "bestaudio",
    "noplaylist": True,
    "audioformat": "opus",
    "source_address": "0.0.0.0",
    "quiet": True,
    "default_search": "ytsearch",
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'opus',  # Here we tell ffmpeg to extract opus whichi it knows how to do
        'preferredquality': '192',
    }],
}
```

it seems ffmpeg is never set to extract opus from the file, and while testing with ffplay it reports the audio is still webm, which it was by default.

**Comment by dstftw** [comment]
```
[youtube] swYdKF1MpWg: Downloading webpage
[youtube] swYdKF1MpWg: Downloading video info webpage
[download] Destination: Electric_Light_Orchestra_-_Mr._Blue_Sky_Official_Music_Video-swYdKF1MpWg.webm
[download] 100% of 3.38MiB in 00:02
[ffmpeg] Destination: Electric_Light_Orchestra_-_Mr._Blue_Sky_Official_Music_Video-swYdKF1MpWg.opus
Deleting original file Electric_Light_Orchestra_-_Mr._Blue_Sky_Official_Music_Video-swYdKF1MpWg.webm (pass -k to keep)
```
```
> ffmpeg.exe -i .\Electric_Light_Orchestra_-_Mr._Blue_Sky_Official_Music_Video-swYdKF1MpWg.opus
...
Input #0, ogg, from '.\Electric_Light_Orchestra_-_Mr._Blue_Sky_Official_Music_Video-swYdKF1MpWg.opus':
  Duration: 00:03:42.10, start: 0.003000, bitrate: 191 kb/s
    Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      LANGUAGE        : eng
      ENCODER         : Lavc57.93.100 libopus
At least one output file must be specified
```

**Comment by martmists** [comment]
I can set up a server with the exact image I have and set up an SSH server if that helps, because ffplay is definitely reporting webm.
