### ISSUE TITLE
Youtube. Windows. ffmpeg. Error Invalid data found when processing input

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rg3/youtube-dl#18861]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.10**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

d:\Desktop\youtubeDL>youtube-dl.exe https://www.youtube.com/watch?v=-XN5Wr8Wgtw --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=-XN5Wr8Wgtw', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.01.10
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg SVN-r22888
[debug] Proxy map: {}
[youtube] -XN5Wr8Wgtw: Downloading webpage
[youtube] -XN5Wr8Wgtw: Downloading video info webpage
[youtube] {43} signature length 43.42, html5 player vflsx9jEl
[youtube] {18} signature length 43.42, html5 player vflsx9jEl
[youtube] {36} signature length 43.42, html5 player vflsx9jEl
[youtube] {17} signature length 43.42, html5 player vflsx9jEl
[youtube] {135} signature length 43.42, html5 player vflsx9jEl
[youtube] {244} signature length 43.42, html5 player vflsx9jEl
[youtube] {134} signature length 43.42, html5 player vflsx9jEl
[youtube] {243} signature length 43.42, html5 player vflsx9jEl
[youtube] {133} signature length 43.42, html5 player vflsx9jEl
[youtube] {242} signature length 43.42, html5 player vflsx9jEl
[youtube] {160} signature length 43.42, html5 player vflsx9jEl
[youtube] {278} signature length 43.42, html5 player vflsx9jEl
[youtube] {140} signature length 43.42, html5 player vflsx9jEl
[youtube] {171} signature length 43.42, html5 player vflsx9jEl
[youtube] {249} signature length 43.42, html5 player vflsx9jEl
[youtube] {250} signature length 43.42, html5 player vflsx9jEl
[youtube] {251} signature length 43.42, html5 player vflsx9jEl
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r4---sn-v2u0n-hxar.googlevideo.com/videoplayback?id=o-AHDQGV22rVL0tNfQHBBl4xEM_bAxOVgyHDXfLw3bjEX1&source=youtube&initcw
ndbps=1166250&itag=135&fvip=4&key=yt6&ip=49.177.138.247&lmt=1547159315477829&dur=3480.000&expire=1547544342&mm=31%2C29&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2C
id%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ipbits=0&c=WEB&keepalive=yes&txp=5432432&
pl=16&aitags=133%2C134%2C135%2C160%2C242%2C243%2C244%2C278&mime=video%2Fmp4&requiressl=yes&mt=1547522624&mv=m&ei=tVI9XLjFOYikz7sPzOGb-Ag&ms=au%2Crdu&clen=180998
029&mn=sn-v2u0n-hxar%2Csn-v2u0n-ntqd&gir=yes&signature=6F0E7FB51CBC978305E34BABC3E80AF61DD38EFB.5C5687DC49FF9ED83752B3B4E8EE5EEAD0515A66&ratebypass=yes'
[download] Destination: The Big Painting Challenge (S03E05) - Movement--XN5Wr8Wgtw.f135.mp4
[download] 100% of 172.61MiB in 00:53
[debug] Invoking downloader on 'https://r4---sn-v2u0n-hxar.googlevideo.com/videoplayback?id=o-AHDQGV22rVL0tNfQHBBl4xEM_bAxOVgyHDXfLw3bjEX1&source=youtube&initcw
ndbps=1166250&fvip=4&key=yt6&ip=49.177.138.247&lmt=1547188230231763&dur=3480.021&expire=1547544342&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbit
s%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ipbits=0&c=WEB&keepalive=yes&txp=5411222&pl=16&itag=251&mime=audio%2Fw
ebm&requiressl=yes&mt=1547522624&mv=m&ei=tVI9XLjFOYikz7sPzOGb-Ag&ms=au%2Crdu&clen=54979975&mm=31%2C29&mn=sn-v2u0n-hxar%2Csn-v2u0n-ntqd&gir=yes&signature=082955D
DCD3B55B4009EE7F117572345AD83B4A1.5DDBAC3AEC19531049B64C87F22433A1071D71DC&ratebypass=yes'
[download] Destination: The Big Painting Challenge (S03E05) - Movement--XN5Wr8Wgtw.f251.webm
[download] 100% of 52.43MiB in 00:15
[ffmpeg] Merging formats into "The Big Painting Challenge (S03E05) - Movement--XN5Wr8Wgtw.mkv"
[debug] ffmpeg command line: ffmpeg -y -i "file:The Big Painting Challenge (S03E05) - Movement--XN5Wr8Wgtw.f135.mp4" -i "file:The Big Painting Challenge (S03E05
) - Movement--XN5Wr8Wgtw.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:The Big Painting Challenge (S03E05) - Movement--XN5Wr8Wgtw.temp.mkv"
ERROR: file:The Big Painting Challenge (S03E05) - Movement--XN5Wr8Wgtw.f251.webm: Invalid data found when processing input
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\YoutubeDL.py", line 2048, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\postprocessor\ffmpeg.py", line 478, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\postprocessor\ffmpeg.py", line 204, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:The Big Painting Challenge (S03E05) - Movement--XN5Wr8Wgtw.f251.webm: Invalid data found when pro
cessing input

### Description of your *issue*, suggested solution and other information

When attempting to download the video in question, the downloader warns that the formats are incompatible to merge and downloads 2 separate files, and mp3 and a webm

The MP4 file seems to be OK as its playable in VLC but does not have any audio

But VLC can't play the webm file (which I presume is supposed to contain the audio), and ffpmeg is also unable to process the webm

The webm file does seem to contain data, and looking in a hex editor it has 
google/video-fileWA‘google/video-file. in the header block.

I get pretty much the same error on Linux Mint, as when using the Windows exe.

I don't know if this is a problem that ffmpeg can't decode the webm file or possibly the incorrect file is being download as the webm, I suspect the former.

**Comment by dstftw** [comment]
Outdated ffmpeg.
