### ISSUE TITLE
Site support request: courses.workitdaily.com

### ISSUE THREAD

**Issue by b1ggjoe** [rg3/youtube-dl#18871]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.16**

- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-

- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

- [x ] Site support request (request for adding support for a new site)

---

**Hello,
I'm having the exact same issue as posted here: https://github.com/rg3/youtube-dl/issues/18272**

Playlist: https://courses.workitdaily.com/courses/enrolled/94090
or
https://courses.workitdaily.com/courses/improve-communication-skills-work

**_(The two URLs above lead to the same course)_**

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--username', 'PRIVATE', '--password', 'PRIVATE', '-o', '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', 'https://courses.workitdaily.com/courses/enrolled/94090']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.01.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 94090: Requesting header
[redirect] Following redirect to https://courses.workitdaily.com/p/improve-communication-skills-work
[generic] improve-communication-skills-work: Requesting header
WARNING: Falling back on generic information extractor.
[generic] improve-communication-skills-work: Downloading webpage
[generic] improve-communication-skills-work: Extracting information
[Wistia] uzx744jt5g: Downloading JSON metadata
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://embed.wistia.com/deliveries/1a8e97f51710a14bc34ece5300aa174b39ea24a0.bin'
[download] Destination: NA\NA - Interaction Style - Intro.mov.mov
[download] 100% of 136.45MiB in 00:28

```

---

It downloads only first video in the playlist, but not all remaining videos in the course playlist. 

Same behavior is experienced for all of the courses listed on this website.

For this specific course, here are the urls of a few of the videos in this specific course. Single videos download fine:

https://courses.workitdaily.com/courses/improve-communication-skills-work/lectures/1370281

https://courses.workitdaily.com/courses/improve-communication-skills-work/lectures/1370294

https://courses.workitdaily.com/courses/improve-communication-skills-work/lectures/1370349

https://courses.workitdaily.com/courses/improve-communication-skills-work/lectures/1370363

Here's an example of a successful download of the last url above:

https://courses.workitdaily.com/courses/improve-communication-skills-work/lectures/1370363

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--username', 'PRIVATE', '--password', 'PRIVATE', '-o', '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', 'https://courses.workitdaily.com/courses/improve-communication-skills-work/lectures/1370363']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.01.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 1370363: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1370363: Downloading webpage
[generic] 1370363: Extracting information
[Teachable] Downloading courses.workitdaily.com login page
[Teachable] Logging in to courses.workitdaily.com
[Teachable] 1370363: Downloading webpage
[Wistia] djzbk4brwo: Downloading JSON metadata
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://embed.wistia.com/deliveries/fa4f97756a8771e48a310e961de95c874806ff12.bin'
[download] Destination: NA\NA - Commander.mov
[download] 100% of 158.65MiB in 00:24

```

---

I can provide credentials to this website if necessary. Please provide me with an email address, where I can send the credentials privately.

Thank you,

BJ

**Comment by b1ggjoe** [comment]
Also, I'm not sure if the previous issue that I referenced (https://github.com/rg3/youtube-dl/issues/18272) has already been resolved. If so, would it be possible for someone to provide the correct url syntax structure so that I can experiment and see if it works on the website I referenced?

Thanks!

**Comment by b1ggjoe** [comment]
Is there any update to this issue? No one has reached out to me yet for credentials.

Thank you.

**Comment by b1ggjoe** [comment]
Hello,

Account credentials have been sent to both @remitamine and @rg3.

Thank you both!

BJ

**Comment by b1ggjoe** [comment]
@remitamine 

Thank you very much for looking into this!!! I see that additional URLs have been (or are going to be) added to the **_extractor_** for **teachable.py**.

Does that mean that if I modify the local version of **teachable.py** on my computer, it could temporarily resolve my issue until a new update is pushed out?

**Comment by remitamine** [comment]
> Does that mean that if I modify the local version of teachable.py on my computer, it could temporarily resolve my issue until a new update is pushed out?

you can't modify the windows executable, you have to get the source code and run it or wait for the next release.
