### ISSUE TITLE
packtpub issue

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#18887]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.16**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.01.16
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

PS C:\Users\HDNLSR174> youtube-dl --verbose -o 'p:\contents\New folder/%(playlist)s/%(chapter_number)s - %(chapter)s/%(t
itle)s.%(ext)s' https://subscription.packtpub.com/video/web_development/9781838555719 --limit-rate 5000k --ignore-errors
--username abc123 --password ***
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', 'p:\contents\New folder/%(playlist)s/%(chapter_number)s - %(chapter)s/%
(title)s.%(ext)s', 'https://subscription.packtpub.com/video/web_development/9781838555719', '--limit-rate', '5000k', '--
ignore-errors', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.01.16
[debug] Python version 3.6.4rc1 (CPython) - Windows-2012ServerR2-6.3.9600-SP0
[debug] exe versions: ffmpeg N-89395-g71421f382f, ffprobe N-89395-g71421f382f
[debug] Proxy map: {}
[PacktPubCourse] 9781838555719: Downloading JSON metadata
[download] Downloading playlist: JavaScript AJAX XHR for Beginners [Video]
[PacktPubCourse] playlist JavaScript AJAX XHR for Beginners [Video]: Collected 12 video ids (downloading 12 of them)
[download] Downloading video 1 of 12
[PacktPub] Downloading Authorization Token
ERROR: The recaptcha solution is missing.
Traceback (most recent call last):
File "c:\python36\lib\site-packages\youtube_dl\extractor\common.py", line 605, in _request_webpage
return self._downloader.urlopen(url_or_request)
File "c:\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 2212, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "c:\python36\lib\urllib\request.py", line 532, in open
response = meth(req, response)
File "c:\python36\lib\urllib\request.py", line 642, in http_response
'http', request, response, code, msg, hdrs)
File "c:\python36\lib\urllib\request.py", line 570, in error
return self._call_chain(*args)
File "c:\python36\lib\urllib\request.py", line 504, in _call_chain
result = func(*args)
File "c:\python36\lib\urllib\request.py", line 650, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\python36\lib\site-packages\youtube_dl\extractor\packtpub.py", line 56, in _real_initialize
'password': password,
File "c:\python36\lib\site-packages\youtube_dl\extractor\packtpub.py", line 71, in _download_json
response = super(PacktPubIE, self)._download_json(*args, **kwargs)
File "c:\python36\lib\site-packages\youtube_dl\extractor\common.py", line 870, in _download_json
expected_status=expected_status)
File "c:\python36\lib\site-packages\youtube_dl\extractor\common.py", line 848, in _download_json_handle
expected_status=expected_status)
File "c:\python36\lib\site-packages\youtube_dl\extractor\common.py", line 638, in _download_webpage_handle
urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query
, expected_status=expected_status)
File "c:\python36\lib\site-packages\youtube_dl\extractor\common.py", line 623, in _request_webpage
raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400
: 'Bad Request'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see
https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete
output.
Traceback (most recent call last):
File "c:\python36\lib\site-packages\youtube_dl\extractor\common.py", line 605, in _request_webpage
return self._downloader.urlopen(url_or_request)
File "c:\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 2212, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "c:\python36\lib\urllib\request.py", line 532, in open
response = meth(req, response)
File "c:\python36\lib\urllib\request.py", line 642, in http_response
'http', request, response, code, msg, hdrs)
File "c:\python36\lib\urllib\request.py", line 570, in error
return self._call_chain(*args)
File "c:\python36\lib\urllib\request.py", line 504, in _call_chain
result = func(*args)
File "c:\python36\lib\urllib\request.py", line 650, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by jaan143** [comment]
@remitamine bro can you fix it
thanks

**Comment by remitamine** [comment]
can't tell, as the failing request require account credentials.

**Comment by jaan143** [comment]
@remitamine  bro please check your email i sent you account details

**Comment by remitamine** [comment]
I'm getting this error in the browser:
> Sorry, you entered an invalid email address and password combination.
