### ISSUE TITLE
Videos on YouTube not marked as watched.

### ISSUE THREAD

**Issue by kruug** [rg3/youtube-dl#18882]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
PS D:\> & .\youtube-dl.exe --cookies cookies.txt --ignore-errors --mark-watched --download-archive archive.txt https://www.youtube.com/channel/UCbaAyXYMnbQu0BGGPbvxHsw -f worst -o "Got\%(title)s.%(ext)s" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', '--ignore-errors', '--mark-watched', '--download-archive', 'archive.txt', 'https://www.youtube.com/channel/UCbaAyXYMnbQu0BGGPbvxHsw', '-f', 'worst', '-o', 'Got\\%(title)s.%(ext)s', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.01.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-80234-g49b0246
[debug] Proxy map: {}
[youtube:channel] UCbaAyXYMnbQu0BGGPbvxHsw: Downloading channel page
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading webpage
[download] Downloading playlist: Uploads from Chris Boden
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #1
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #2
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #3
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #4
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #5
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #6
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #7
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #8
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #9
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #10
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #11
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #12
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #13
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #14
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #15
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #16
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #17
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #18
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #19
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #20
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #21
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #22
[youtube:playlist] UUbaAyXYMnbQu0BGGPbvxHsw: Downloading page #23
[youtube:playlist] playlist Uploads from Chris Boden: Downloading 2366 videos
[download] Downloading video 1 of 2366
[youtube] Jfj_YuUZKMM: Downloading webpage
[youtube] Jfj_YuUZKMM: Downloading video info webpage
[youtube] Jfj_YuUZKMM: Marking watched
[debug] Invoking downloader on 'https://r2---sn-bvvbax-hn2d.googlevideo.com/videoplayback?itag=17&key=yt6&lmt=1547609794650661&fvip=2&signature=B9B0DAA3C58545BE5CC8CD3CAD67C12C61867BB8.A7BB88ACAF92B19B23348E590D00620715331A03&gir=yes&c=WEB&ip=47.49.10.170&requiressl=yes&txp=7311222&ms=au%2Conr&mt=1547652407&mv=m&id=o-AOPDC1CuGemnYea9dYkaa4cMlYn6TQRRE6rChsEVm9zN&mime=video%2F3gpp&pl=17&mm=31%2C26&mn=sn-bvvbax-hn2d%2Csn-qxo7rn7l&ipbits=0&gcr=us&expire=1547674086&dur=6705.597&ei=hk0_XO3HJ4WqDIOTi4AL&initcwndbps=1720000&clen=42311424&nh=EAQ%2C&source=youtube&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cexpire&ratebypass=yes'
[download] Destination: Got\Chris Boden Live Stream.3gp
[download]   0.6% of 40.35MiB at 40.23KiB/s ETA 17:00
ERROR: Interrupted by user
```

---

### Description of your *issue*, suggested solution and other information

When run with the `--cookies` flag, and a proper cookies.txt (retrieved via cookies.txt add-on), the videos are not actually marked as watched on YouTube.  I did see this issue already submitted: https://github.com/rg3/youtube-dl/issues/18546.  This was marked as resolved, but I have not been able to get this to work for myself (hence why I marked it as a question and support).

The main reason why I am using the cookies file is to bypass having to enter in my 2FA code for every video on the channel/playlist.  If youtube-dl could require the 2FA code at the beginning of the download, and then hold onto a token to pass for each consecutive video, dealing with this would not be a requirement.

**Comment by dstftw** [comment]
Most likely expired cookies.

**Comment by kruug** [comment]
I navigated to YouTube.com, watched a video, then exported the cookies.

**Comment by sonicer105** [comment]
I'm having a similar issue. Using the `--mark-watched` flag and providing a valid cookie file only marks the first section of the video as watched, not the entire video. If I watch the whole video on youtube, it shows the whole red bar as filled in my feed and puts a "watched" watermark on it. That does not happen when I download it

Log:
```
C:\Users\redacted\Desktop>youtube-dl --cookies yt/cookies.txt --mark-watched https://www.youtube.com/playlist?list=WL -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'yt/cookies.txt', '--mark-watched', 'https://www.youtube.com/playlist?list=WL', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.05.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[youtube:watchlater] WL: Downloading webpage
WARNING: [youtube:watchlater] Youtube gives an alert message: This playlist is automatically sorted by date published.
[download] Downloading playlist: Watch Later Playlist
[youtube:watchlater] playlist Watch Later Playlist: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] kt8K4giKny8: Downloading webpage
[youtube] kt8K4giKny8: Downloading video info webpage
[youtube] kt8K4giKny8: Marking watched
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r1---sn-ni5f-t8gs.googlevideo.com/videoplayback?id=o-AHOfITZX9K8zS8bwQ_-5OH-sOEGLgMc6IxBNK7hfhr1G&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313%2C394%2C395%2C396%2C397&itag=313&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-ni5f-t8gs%2Csn-vgqsenek&ms=au%2Conr&mv=m&pl=19&ei=nYrdXIaVAYf8kgbowL-IBA&ctier=A&pfa=5&initcwndbps=1606250&hightc=yes&mime=video%2Fwebm&gir=yes&clen=1077672110&dur=685.320&lmt=1557934676049535&mt=1558022682&fvip=3&keepalive=yes&c=WEB&txp=5531432&ip=184.70.130.186&ipbits=0&expire=1558044413&sparams=ip%2Cipbits%2Cexpire%2Cid%2Caitags%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cctier%2Cpfa%2Cinitcwndbps%2Chightc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&signature=8491EA56D1A46E8DDA095A553B562EA9924315B0.1FDB6BC8608DC3CA03A2984B551E40818752CE46&key=yt8&ratebypass=yes'
[download] Destination: Treadle Pedal Completed - Marble Machine X #81-kt8K4giKny8.f313.webm
[download] 100% of 1.00GiB in 01:46
[debug] Invoking downloader on 'https://r1---sn-ni5f-t8gs.googlevideo.com/videoplayback?id=o-AHOfITZX9K8zS8bwQ_-5OH-sOEGLgMc6IxBNK7hfhr1G&itag=251&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-ni5f-t8gs%2Csn-vgqsenek&ms=au%2Conr&mv=m&pl=19&ei=nYrdXIaVAYf8kgbowL-IBA&ctier=A&pfa=5&initcwndbps=1606250&hightc=yes&mime=audio%2Fwebm&gir=yes&clen=11125637&dur=685.341&lmt=1557933927211984&mt=1558022682&fvip=3&keepalive=yes&c=WEB&txp=5531432&ip=184.70.130.186&ipbits=0&expire=1558044413&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cctier%2Cpfa%2Cinitcwndbps%2Chightc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&signature=421B0B18C3732B96F593BC0B7C11B22968EDCCDC.1E0877110DB7D40F7147BFB8768AD86724CAA68F&key=yt8&ratebypass=yes'
[download] Destination: Treadle Pedal Completed - Marble Machine X #81-kt8K4giKny8.f251.webm
[download] 100% of 10.61MiB in 00:01
[ffmpeg] Merging formats into "Treadle Pedal Completed - Marble Machine X #81-kt8K4giKny8.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Treadle Pedal Completed - Marble Machine X #81-kt8K4giKny8.f313.webm" -i "file:Treadle Pedal Completed - Marble Machine X #81-kt8K4giKny8.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Treadle Pedal Completed - Marble Machine X #81-kt8K4giKny8.temp.webm"
Deleting original file Treadle Pedal Completed - Marble Machine X #81-kt8K4giKny8.f313.webm (pass -k to keep)
Deleting original file Treadle Pedal Completed - Marble Machine X #81-kt8K4giKny8.f251.webm (pass -k to keep)
[download] Finished downloading playlist: Watch Later Playlist

C:\Users\redacted\Desktop>
```
Link to downloaded video: https://www.youtube.com/watch?v=kt8K4giKny8

How it shows up in my feed after the download:
![Screenshot of how the video shows up in my feed](https://drive.google.com/uc?export=view&id=1oPlNBr2ZkNKDG7luEmuNrMp84uz-RrxV)

How it should show up in my feed after the download:
![Screenshot of another video to demonstrate how the video should show up in my feed](https://drive.google.com/uc?export=view&id=1zcV0z5zqeQ-U-J6MuW7JfvGtcoKZ19Bb)

It's not just the one video, it was consitently only marking the first part of the video as watched in my testing.

**Comment by kruug** [comment]
@sonicer105

I noticed this same thing happening, but when I checked my feed again later, the videos had the full red bar.  I haven't tracked down exactly how much later this happened, but I checked after a few hours.

**Comment by sonicer105** [comment]
@kruug 

Interesting. I'll let you know if I expreince the same.

**Comment by sonicer105** [comment]
@kruug

Yeah, I went back and they are now marked as watched. Wonder why there's a delay.

**Comment by pukkandan** [comment]
I am having the same issue, and the videos are not getting marked as fully watched even after days.

`youtube-dl.exe -v --cookies cookies -- 5nW3nJhBHL0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies', '--', '5nW3nJhBHL0']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.3
[debug] Proxy map: {}
[youtube] 5nW3nJhBHL0: Downloading webpage
[youtube] 5nW3nJhBHL0: Marking watched
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r4---sn-gwpa-h55l.googlevideo.com/videoplayback?expire=1600024239&ei=TxpeX_jGBqGtmgf_-J7QAg&ip=2405%3A201%3Af003%3Ab8a6%3A116b%3A19b4%3A4521%3Afba4&id=o-AO6oMxegc96pK8yK1CHQzuq2ewMQID2hwvMM-gg7vPxj&itag=303&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&mh=8F&mm=31%2C29&mn=sn-gwpa-h55l%2Csn-h5576n7k&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=48&initcwndbps=2098750&vprv=1&mime=video%2Fwebm&gir=yes&clen=194356811&dur=1264.300&lmt=1599754539881331&mt=1600002527&fvip=4&keepalive=yes&beids=23886204&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAPtfhLKWMqFukYFTqmnXN7RW9ttfUg47-ZNSLtEp-HasAiAbBr3GDzVbPv37SDgfMfszn6-462ly-uttWUZ3BrXUrg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgC64Qw1ceDjSecnIFKpGE5n6wZLJMpXj7hfKzVfH92HYCID6zMU1H9S1aNJe83yWuoFyipu1TlYjhVtOQAl6ZIK_n&ratebypass=yes'
[download] Resuming download at byte 4193280
[download] Destination: Why is there no equation for the perimeter of an ellipse‽-5nW3nJhBHL0.f303.webm
[download] 100% of 185.35MiB in 00:14
[debug] Invoking downloader on 'https://r4---sn-gwpa-h55l.googlevideo.com/videoplayback?expire=1600024239&ei=TxpeX_jGBqGtmgf_-J7QAg&ip=2405%3A201%3Af003%3Ab8a6%3A116b%3A19b4%3A4521%3Afba4&id=o-AO6oMxegc96pK8yK1CHQzuq2ewMQID2hwvMM-gg7vPxj&itag=251&source=youtube&requiressl=yes&mh=8F&mm=31%2C29&mn=sn-gwpa-h55l%2Csn-h5576n7k&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=48&initcwndbps=2098750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=18879379&dur=1264.341&lmt=1599723768837526&mt=1600002527&fvip=4&keepalive=yes&beids=23886204&c=WEB&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAO2bEL8GE5OAoI_UhTQA_7BacPi161F1_qN2iMoYsRpOAiA-0jVhbwd9XXbzwTfOl0R8gkc1GetuxWSXesWep9vJIA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgC64Qw1ceDjSecnIFKpGE5n6wZLJMpXj7hfKzVfH92HYCID6zMU1H9S1aNJe83yWuoFyipu1TlYjhVtOQAl6ZIK_n&ratebypass=yes'
[download] Destination: Why is there no equation for the perimeter of an ellipse‽-5nW3nJhBHL0.f251.webm
[download] 100% of 18.00MiB in 00:01
[ffmpeg] Merging formats into "Why is there no equation for the perimeter of an ellipse‽-5nW3nJhBHL0.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Why is there no equation for the perimeter of an ellipse‽-5nW3nJhBHL0.f303.webm" -i "file:Why is there no equation for the perimeter of an ellipse‽-5nW3nJhBHL0.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Why is there no equation for the perimeter of an ellipse‽-5nW3nJhBHL0.temp.webm"
Deleting original file Why is there no equation for the perimeter of an ellipse‽-5nW3nJhBHL0.f303.webm (pass -k to keep)
Deleting original file Why is there no equation for the perimeter of an ellipse‽-5nW3nJhBHL0.f251.webm (pass -k to keep)
`

**Comment by rajaravivarma-r** [comment]
This is happening for me too. The video is not marked as completely watched even after days. It looks like YouTube has started using `api/stats/watchtime` to mark the watchtime. It sends a bunch of parameters where `st` and `et` could be modified to set the video as completely watched. But I have no idea, what the other params are.
