### ISSUE TITLE
[Feature Request] Make Homebrew formula install Python source

### ISSUE THREAD

**Issue by Kerndog73** [rg3/youtube-dl#18907]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I have youtube-dl installed using homebrew. I would like to also access youtube-dl from python so I want the python package as well. I can install the python package with pip. However, `pip install youtube_dl` and `brew install youtube-dl` both install an executable at `/usr/local/bin/youtube-dl`.

I really like the convenience of keeping everything up-to-date with `brew upgrade` and would rather not have to deal with two separate package managers. I request that `brew install youtube-dl` install both the executable and the python source to be imported from python via `import youtube_dl`.

**Comment by dstftw** [comment]
Address this to homebrew.

**Comment by Kerndog73** [comment]
@dstftw Are you saying that the Homebrew package is not managed by the developers of this project?

**Comment by dstftw** [comment]
Exactly.

**Comment by Kerndog73** [comment]
@dstftw Oh. Well, thanks for the super fast response
