### ISSUE TITLE
VRV and Funimation not extracting through svp4/svptube was directed here from SVP team

### ISSUE THREAD

**Issue by RIpnPip** [rg3/youtube-dl#18903]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.17**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

https://vrv.co/

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

--

### If the purpose of this *issue* is a *site request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
-Vrv
- Single video: https://vrv.co/watch/GRDKVPG3Y/MADE-IN-ABYSS:The-City-of-the-Great-Pit
- Single video: https://vrv.co/watch/G6EX787QR/A-Discovery-of-Witches:A-Discovery-of-Witches-Ep-1

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested a solution and other information
I use SVP4 and SVPtubeto take streams and watch some movies/tv shows/primarily anime in 60fps. When trying to extract from either funimation or VRV I do get an error. Streaming from crunchy roll is fine and many other sites listed. But just those two sites have issues. Could you guys help? The error I get is "unable to extract api config" When contacting the SVP team they directed me to you guys in order to get this resolved. I'm not a coder what's so ever sorry.

**Comment by RIpnPip** [comment]
Thanks in advance and sorry for lack of knowledge, I've been looking for a solution for months hoping the bug would be fixed but it appears that vrv went from being usable to not being an option at all.

**Comment by RIpnPip** [comment]
Link for SVP(Smooth Video Project website ) 
https://www.svp-team.com/wiki/Main_Page

**Comment by RIpnPip** [comment]
I know what you guys do is free but please offer some help rather than just closing threads. I understand its incomplete but adding what I should add and offering a little bit of help doesn't hurt. it gets people nowhere. If you guys had a discord It would be a lot more helpful to those who aren't as educated. I recommend starting one where we can actually communicate with devs. I'm sure it would help with donations since we would be getting some great support and many of want to donate but need support.

**Comment by RIpnPip** [comment]
I am also not alone as there are MANY in the same boat as me , We just want an answer so threads like these don't exist.

**Comment by dstftw** [comment]
Bother to read new issue template and provide all info requested.

**Comment by RIpnPip** [comment]
I appreciate the response! 
I made an account just to post an issue to make you guys aware of it. 
This is clearly a regular thing for you to close these post as they probably come in masses. But please focus on this one, in particular, I beg you. I didn't mean to come off as rude, many others including myself are very thankful for your work. 

VRV is hub filled with a ton of content from many different companies. each channel has content from a whole website such as rooster teeth, hi-dive, Crunchyroll, shudder, cartoon hangover, and the list goes on.I'm sure thats why its on the list of supported websites. 

The main point I'm trying to make is that if this isn't just my issue than fixing this would be huge! Not only are you only adding support for a single site, but that site contains content legally from other big named companies. So rather than developing for each site individually you can develop for this one and have access to the content on all those other sites. 
I just need help getting that verbose flag I think that's what its called. 
The SVP Team uses youtube-dl to extract streams its very dependent on it, But the programs simplify the extraction process to just a few clicks. I've searched everywhere and the threads are only from 2 years ago, which don't provide any solutions to new problems. 
Maybe I just need some extra help but I really want to at least give you my errors so that if it isn't just a me issue you'll have something to work on that affects others as well.

**Comment by RIpnPip** [comment]
If you need a premium account for developing please use mine, its the least I could do.
