### ISSUE TITLE
warning/error log messages should not contain ANSI escape sequences

### ISSUE THREAD

**Issue by tonycpsu** [rg3/youtube-dl#18917]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### Description of your *issue*, suggested solution and other information

I am developing a console application using [urwid](https://github.com/urwid/urwid).  When youtube_dl reports errors, even with `ignoreerrors=True`, I'm getting output to the console, which interferes with the operation of my app.

I see in the comments to #9281 that  "`Logger` can be used to intercept errors though it will hook all the errors not only ExtractorError."  Doing this does, in fact, get the errors passed to my application's log handler, but it does so with unsightly ANSI escape codes in it:

![image](https://user-images.githubusercontent.com/914142/51415631-7ff50180-1b44-11e9-85d1-b686c8fe3ef9.png)

My proposed solution would be to not add the WARNING/ERROR strings (and certainly not the color codes) if the user passes in their own `logger`.

**Comment by dstftw** [comment]
`--no-color`.
