### ISSUE TITLE
Ignore flag failling to ignore a download error

### ISSUE THREAD

**Issue by Geovera** [rg3/youtube-dl#18918]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', 'https://www.youtube.com/watch?v=Psr4rq-ICu8', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 3.6.7 (CPython) - Linux-4.13.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.4.4-1, ffprobe 3.4.4-1
[debug] Proxy map: {}
[youtube] Psr4rq-ICu8: Downloading webpage
[youtube] Psr4rq-ICu8: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: This video is no longer available because the YouTube account associated with this video has been terminated.
Traceback (most recent call last):
  File "/home/geo/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/home/geo/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/home/geo/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1978, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is no longer available because the YouTube account associated with this video has been terminated.
```

---

### Description of your *issue*, suggested solution and other information

Trying to download a youtube playlist and ignore any videos that have errors on a python script. The error kept being raised even after including the ignoreerrors flags in ydl-opts. Tried to download a video through the terminal that I know is down and have the ignore flag on to try and resolve the error. I have also tried using --ignore-errors but I get the same result. The result is in the log above. Is there any reason the flag is not working? I have seen snippets of code of just having the ignore flag fix this issue but for some reason it is not working for me and I don't have any clue.

**Comment by ealgase** [comment]
The flag is working.  youtube-dl still prints the error, it just doesn't die.  Since there was nothing else to do, the program exited.

**Comment by Geovera** [comment]
@ealgase Yeah, when I tried the playlist it continued to download like normal. It was my misunderstanding of the ignore flag. I had to play around with the ydl_opts for the ignore to work on a python script but I got it. Apologies for this simple problem.
