### ISSUE TITLE
Links in description are cut-off

### ISSUE THREAD

**Issue by kenorb** [rg3/youtube-dl#1892]
I've downloaded the following video:
http://www.youtube.com/watch?v=mwZVCDuQv7M
but the file has links cut-off with triple dot at the end.

Example:

```
Mayan Calendar:
http://en.wikipedia.org/wiki/Maya_cal...
http://www.teoria.com/jra/maya/rueda....
http://theabysmal.files.wordpress.com...
```

Is it a bug? Can this be fixed?

**Comment by ekevoo** [comment]
I'm running latest (2e02ecbccc9751af54ae2aab9ce973712c78af74) and this problem is happening again.

**Comment by amir385276** [comment]
please add this site to youtube-dl supported sites list
https://asianen.com/
this site work with m3u8 procedure
Thanks a lot

**Comment by Zonyzix** [comment]
#31013
