### ISSUE TITLE
[crackle] HTTP Error 401: Unauthorized (caused by HTTPError())

### ISSUE THREAD

**Issue by CrackleFox** [rg3/youtube-dl#18932]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.sonycrackle.com/watch/2561/2503912']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.01.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[Crackle] 2503912: Downloading media JSON as US
[Crackle] 2503912: Downloading media JSON as AU
[Crackle] 2503912: Downloading media JSON as CA
[Crackle] 2503912: Downloading media JSON as AS
[Crackle] 2503912: Downloading media JSON as FM
[Crackle] 2503912: Downloading media JSON as GU
[Crackle] 2503912: Downloading media JSON as MP
[Crackle] 2503912: Downloading media JSON as PR
[Crackle] 2503912: Downloading media JSON as PW
[Crackle] 2503912: Downloading media JSON as MH
[Crackle] 2503912: Downloading media JSON as VI
ERROR: Unable to download media JSON: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\extractor\common.py", line 605, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\YoutubeDL.py", line 2212, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

---

Crackle redesigned its website at the beginning of the year and, as a result, the above error started to occur. Videos do play from the website without error and without having to sign in.

**Comment by rEnr3n** [comment]
This one? #16931

**Comment by CrackleFox** [comment]
It's not that the same issue. I was able to download videos until Crackle redesigned its website at the beginning of the year. I tried doing what was suggested in the comments, playing the video first in the web browser then executing the download and using the --no-geo-bypass flag but it does not make a difference.
