### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 404: Not Found (Only on videos streamed from Android Phones)

### ISSUE THREAD

**Issue by gladiatormaximusTR** [rg3/youtube-dl#18937]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.17**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

youtube-dl -v https://www.youtube.com/watch?v=KgFLIQoRxOQ
[debug] System config: []
[debug] User config: ['-o', 'youtube-dl/%(uploader)s/%(title)s-%(id)s.%(ext)s', '-w', '-c', '-i', '-v', '--download-archive', '/home/rms/.config/record.txt', '--username=PRIVATE', '--password=PRIVATE', '-f', 'bestvideo+bestaudio', '--write-description', '--write-info-json', '--write-annotations', '--write-thumbnail', '--all-subs', '--merge-output-format', 'mkv']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=KgFLIQoRxOQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 3.7.2 (CPython) - Linux-4.19.4-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg n4.1, ffprobe n4.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] KgFLIQoRxOQ: Downloading webpage
[youtube] KgFLIQoRxOQ: Downloading video info webpage
WARNING: video doesn't have subtitles
[youtube] KgFLIQoRxOQ: Searching for annotations.
[info] Video description is already present
[info] Video annotations are already present
[info] Video description metadata is already present
[youtube] KgFLIQoRxOQ: Thumbnail is already present
[debug] Invoking downloader on 'https://r5---sn-q4fl6n7y.googlevideo.com/videoplayback?expire=1548071042&otf=1&sig=AMao4c4wRQIhALzKM1gSqLtGfH4eRO3UywT_9_yscS3kc1-s2yfuNnlBAiBuLkBUV3SdE4WVg4X1Lb-k0z1ypY1spbUVk_wU-_0Xhg%3D%3D&dur=0.000&ei=IlxFXJPpG4SIDsCBiJgL&initcwndbps=1736250&requiressl=yes&ip=174.73.123.22&ms=au%2Conr&mv=m&mt=1548049354&pl=19&mime=video%2Fmp4&id=o-AD1xqpd9xkvm8vVo-nAeXCQb73UBBOrr1O8ysPzet392&mn=sn-q4fl6n7y%2Csn-5ualdn7z&mm=31%2C26&ipbits=0&gcr=us&itag=136&keepalive=yes&lmt=1547412513107524&fvip=5&otfp=1&c=WEB&lsig=ANVabiowRAIgeNl_UGNXYVkUGjEQAiq3DTHXmc9FMuHfWsDXETElUwkCIGLNo6COJAeA9TQ3mVsk3gS4qCtV4ongr7LQWv9CNc3S&lsparams=ms%2Cmn%2Cmv%2Cmm%2Cinitcwndbps%2Cpl&source=yt_otf&aitags=133%2C134%2C135%2C136%2C137%2C160&sparams=expire%2Cei%2Cip%2Crequiressl%2Cotf%2Cotfp%2Cipbits%2Citag%2Ckeepalive%2Cgcr%2Clmt%2Cdur%2Csource%2Cid%2Caitags%2Cmime&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1903, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1848, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

The problem seems to be with videos streamed from low-end android phones.
Here's a couple more for example:
https://www.youtube.com/watch?v=S0pkzsS9FgM
https://www.youtube.com/watch?v=yphWfNSXEVw

**Comment by gladiatormaximusTR** [comment]
My version is not outdated.

**Comment by dstftw** [comment]
>[debug] youtube-dl version 2019.01.10
