### ISSUE TITLE
Getting 403 only for premiered youtube videos

### ISSUE THREAD

**Issue by vuckookv3** [rg3/youtube-dl#18948]
So I am generating links on my server (located in Germany) via:

`youtube-dl https://www.youtube.com/watch?v=4BYASJt5plY -g -f best`

This has been working perfectly, untill I found out that when I generate link for youtube video that is published as Premiere (instead of "Published on..." it says "Premiered..." like in the video mentioned in command), I get the link, but when I play it, I get HTTP 403 error.

All normal videos are working fine.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser
