### ISSUE TITLE
support for anchor.fm 

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#18947]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Have been unsuccessful in downloading anchor.fm podcasts :( The episodes are 40-45 minutes long but I am only able to download the first minute or so :(

```
$ ./youtube-dl --verbose -F "https://anchor.fm/meredith-mikell/episodes/Episode-1-Welcome-e2innt/a-a6dmtt"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://anchor.fm/meredith-mikell/episodes/Episode-1-Welcome-e2innt/a-a6dmtt']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 2.7.15+ (CPython) - Linux-4.19.0-1-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.1-1, ffprobe 4.1-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] a-a6dmtt: Requesting header
WARNING: Falling back on generic information extractor.
[generic] a-a6dmtt: Downloading webpage
[generic] a-a6dmtt: Extracting information
[download] Downloading playlist: Episode 1: Welcome! by The Space Between: Science Fiction to Science Future • A podcast on Anchor
[generic] playlist Episode 1: Welcome! by The Space Between: Science Fiction to Science Future • A podcast on Anchor: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[info] Available formats for a-a6dmtt:
format code  extension  resolution note
0            m4a        audio only 
[download] Finished downloading playlist: Episode 1: Welcome! by The Space Between: Science Fiction to Science Future • A podcast on Anchor
```

**Comment by brianreeve** [comment]
This appears to still be an issue in 2019.02.08.

I don't see any duplicate issues. Can this issue reopened as still valid?

**Comment by ivan** [comment]
fwiw: https://gist.github.com/ivan/411e75128eb22f4a278a87f98a58ef74 might be useful as an implementation outline (I found that one must concatenate m4a files.)

**Comment by yoshimo** [comment]
Anchor.fm splits podcasts into multiple files that would need to be concancenated and given chapter marks and other meta data.

They are marked with caption, duration , url , audiotype and timestamps in the sites source.
Depending on your personal choice filtering by audiotype and/or caption before joining files might be a good option to add here. Repeated stuff like intros or outros can annoy after a while.

Right now we only download the intro chapter and stop, this issue is valid.
@shirishag75  would you mind re-opening it?

**Comment by yoshimo** [comment]
@Ivan some Episodes in a few podcasts also get offered in mp3, so you need to keep in mind that the file format might vary

**Comment by ohhai** [comment]
I see anchor.fm provides rss (sometimes?) and there is direct media link inside. So might be related here: https://github.com/ytdl-org/youtube-dl/issues/16912

**Comment by brauliobo** [comment]
it seems this regressed:
```
✗  youtube-dl https://anchor.fm/paul-narada-alister/episodes/Dada-Gunamuktananda-e1p31q2
[generic] Dada-Gunamuktananda-e1p31q2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Dada-Gunamuktananda-e1p31q2: Downloading webpage
[generic] Dada-Gunamuktananda-e1p31q2: Extracting information
WARNING: [generic] Dada-Gunamuktananda-e1p31q2: Failed to parse JSON Extra data: line 2 column 438 (char 438)
ERROR: Unsupported URL: https://anchor.fm/paul-narada-alister/episodes/Dada-Gunamuktananda-e1p31q2
```

**Comment by brauliobo** [comment]
this simple bash script works: https://gist.github.com/ivan/411e75128eb22f4a278a87f98a58ef74#file-grab-anchor-episode-sh-L11
