### ISSUE TITLE
Crunchyroll.com - ERROR: Unable to extract title

### ISSUE THREAD

**Issue by 123peter123** [rg3/youtube-dl#18955]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.17**

### Before submitting an *issue* make sure you have:
- [ x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: [u'-i', u'--output', u'/mnt/Storage/Videos/youtube-dl/%(title)s.%(ext)s', u'--embed-thumbnail', u'--add-metadata', u'--sub-lang', u'en,enUS', u'--write-sub', u'--convert-subs', u'srt', u'--embed-subs', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4, http_mp3_128_url']

[debug] Command-line args: [u'-v']

[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8

[debug] youtube-dl version 2019.01.17
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-43-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: ffmpeg 3.2.6-1, ffprobe 3.2.6-1
[debug] Proxy map: {}
...
<end of log>

### Description of your *issue*, suggested solution and other information

My issue is that I can no longer download from Crunchyroll, I do not know if it's an issue on my end or not but here is the verbose log:

~ youtube-dl --verbose https://www.crunchyroll.com/en-gb/mob-psycho-100/episode-2-urban-legends-encountering-rumors-780921

[debug] System config: []
[debug] User config: [u'-i', u'--output', u'/mnt/Storage/Videos/youtube-dl/%(title)s.%(ext)s', u'--embed-thumbnail', u'--add-metadata', u'--sub-lang', u'en,enUS', u'--write-sub', u'--convert-subs', u'srt', u'--embed-subs', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4, http_mp3_128_url']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.crunchyroll.com/en-gb/mob-psycho-100/episode-2-urban-legends-encountering-rumors-780921']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-43-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: ffmpeg 3.2.6-1, ffprobe 3.2.6-1
[debug] Proxy map: {}
[crunchyroll] 100: Downloading webpage
ERROR: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/crunchyroll.py", line 455, in _real_extract
    webpage, 'video_title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 992, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by TammysHead** [comment]
Just use 
`https://www.crunchyroll.com/mob-psycho-100/episode-2-urban-legends-encountering-rumors-780921`
instead of
`https://www.crunchyroll.com/en-gb/mob-psycho-100/episode-2-urban-legends-encountering-rumors-780921`
