### ISSUE TITLE
Youtube now has 30fps source with higher bitrate than 60fps, affects best/bestvideo selection

### ISSUE THREAD

**Issue by satnatantas** [rg3/youtube-dl#18958]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

Youtube started having 30fps video only stream with higher bitrate than 60fps stream for whatever reason thus affecting bestvideo selection. This can always be overridden with format selection string so this issue is created for information purposes.

Example:
https://www.youtube.com/watch?v=nmtEBk8VzlU
```
youtube-dl.exe -F https://www.youtube.com/watch?v=nmtEBk8VzlU
[youtube] nmtEBk8VzlU: Downloading webpage
[youtube] nmtEBk8VzlU: Downloading video info webpage
[info] Available formats for nmtEBk8VzlU:
format code  extension  resolution note
249          webm       audio only DASH audio   55k , opus @ 50k, 4.21MiB
250          webm       audio only DASH audio   69k , opus @ 70k, 5.20MiB
171          webm       audio only DASH audio   95k , vorbis@128k, 7.87MiB
251          webm       audio only DASH audio  125k , opus @160k, 9.52MiB
140          m4a        audio only DASH audio  131k , m4a_dash container, mp4a.40.2@128k, 11.70MiB
394          mp4        256x144    144p   90k , av01.0.05M.08, 30fps, video only, 6.86MiB
160          mp4        256x144    144p  127k , avc1.4d400c, 30fps, video only, 9.37MiB
278          webm       256x144    144p  148k , webm container, vp9, 30fps, video only, 8.65MiB
395          mp4        426x240    240p  204k , av01.0.05M.08, 30fps, video only, 15.73MiB
242          webm       426x240    240p  240k , vp9, 30fps, video only, 19.12MiB
133          mp4        426x240    240p  329k , avc1.4d4015, 30fps, video only, 21.11MiB
396          mp4        640x360    360p  376k , av01.0.05M.08, 30fps, video only, 28.51MiB
243          webm       640x360    360p  492k , vp9, 30fps, video only, 35.54MiB
134          mp4        640x360    360p  680k , avc1.4d401e, 30fps, video only, 49.84MiB
397          mp4        854x480    480p  688k , av01.0.05M.08, 30fps, video only, 52.43MiB
244          webm       854x480    480p  861k , vp9, 30fps, video only, 64.60MiB
135          mp4        854x480    480p 1171k , avc1.4d401f, 30fps, video only, 83.14MiB
247          webm       1280x720   720p 1564k , vp9, 30fps, video only, 132.20MiB
248          webm       1920x1080  1080p 2754k , vp9, 30fps, video only, 234.10MiB
302          webm       1280x720   720p60 2977k , vp9, 60fps, video only, 223.80MiB
298          mp4        1280x720   720p60 3261k , avc1.4d4020, 60fps, video only, 173.21MiB
303          webm       1920x1080  1080p60 5104k , vp9, 60fps, video only, 392.57MiB
299          mp4        1920x1080  1080p60 5974k , avc1.64002a, 60fps, video only, 479.71MiB
136          mp4        1280x720   720p 6833k , avc1.4d401f, 30fps, video only, 357.75MiB
137          mp4        1920x1080  1080p 10637k , avc1.640028, 30fps, video only, 602.33MiB
17           3gp        176x144    small   78k , mp4v.20.3, mp4a.40.2@ 24k (22050Hz), 7.11MiB
36           3gp        320x180    small  226k , mp4v.20.3, mp4a.40.2 (22050Hz), 20.44MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 88.69MiB
18           mp4        640x360    medium  733k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 66.29MiB
22           mp4        1280x720   hd720 4088k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)
```

**Comment by dstftw** [comment]
Both have higher bitrate.

**Comment by satnatantas** [comment]
@dstftw 
These:
```
303          webm       1920x1080  1080p60 5104k , vp9, 60fps, video only, 392.57MiB
299          mp4        1920x1080  1080p60 5974k , avc1.64002a, 60fps, video only, 479.71MiB
```
have lower bitrate than 
```
137          mp4        1920x1080  1080p 10637k , avc1.640028, 30fps, video only, 602.33MiB
```

**Comment by Hrxn** [comment]
And why do you think that's wrong?

**Comment by satnatantas** [comment]
I never said that. I think that it is weird choice by Youtube. I bet that there will be other people scratching their heads about why 60fps is not downloaded.

I suggest a warning in console for example.
