### ISSUE TITLE
NHKWorld url changed for video on demand

### ISSUE THREAD

**Issue by romeojulietthotel** [rg3/youtube-dl#18968]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.24**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.01.24
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2015173/

---

### Description of your *issue*, suggested solution and other information

`ERROR: Unsupported URL: https://www3.nhk.or.jp:443/nhkworld/en/ondemand/video/<some_video_id_goes_here>`

Videos on the site expire, some only last a week or so and some for 30 or more days.

The call to the http://api.nhk.or.jp/nhkworld/vodesdlist/v1/all/all/all.json looks like it returns the correct data.

I cloned youtube-dl and created a branch to work on but I did not get far. Someone familiar with the code can probably fix it faster than I can.  But I will keep looking at it and try things anyway. Since I'm over my head I am filing this issue.

**Comment by sulaiman-allen** [comment]
I also notices this being an issue. I have been able to successfully download the videos by just swapping out the new url pattern for the old one. As an example, the url https://www3.nhk.or.jp/nhkworld/en/**ondemand**/video/2025093/ fails. However, the slightly modified url https://www3.nhk.or.jp/nhkworld/en/**vod**/video/2025093/ works. The underlying functionality still works, the pattern matching for the base url just seems to be too strict.
