### ISSUE TITLE
7Plus (Australia) – "No video formats found" on some videos

### ISSUE THREAD

**Issue by section83** [rg3/youtube-dl#18977]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.24**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Verbose output was:

```
youtube-dl -v https://7plus.com.au/ice-road-truckers?episode-id=ICER11-007
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://7plus.com.au/ice-road-truckers?episode-id=ICER11-007']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.24
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1-tessus, ffprobe 4.1-tessus
[debug] Proxy map: {}
[7plus] ICER11-007: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/sevenplus.py", line 61, in _real_extract
    info = self._parse_brightcove_metadata(media, episode_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 680, in _parse_brightcove_metadata
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1302, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
---

### Description of your *issue*, suggested solution and other information

Getting a "No video formats found" error on some videos on the 7Plus site: [7plus.com.au](url).  A video which does work is at: [https://7plus.com.au/the-it-list?episode-id=ITLI01-016](url).  Have to admit this looks suspiciously like a DRM issue but normally, youtube-dl reports those.  However, previous episodes of the failed videos (Ice Road Truckers) did work – sorry have lost the logs.

**Comment by section83** [comment]
Sorry I didn't see it's a duplicate.  I did look.  Which issue(s) does it duplicate ?

**Comment by net-tools** [comment]
Hi @section83 , it seems our posts are quickly closed as duplicates without any further explanation. Still looking for the original post explaining my so-called duplicate issue. Asked for the link to the duplicate, still waiting, as you are.
