### ISSUE TITLE
Youtube URLs  -J return 403 sometimes

### ISSUE THREAD

**Issue by nadermx** [rg3/youtube-dl#18987]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
I'm currently using youtube-dl to get the URL of the video, via this command.

`youtube-dl -f bestaudio --no-cache-dir --geo-bypass --restrict-filenames -J --cookies cookies.txt youtubeURL`

From there I am taking that URL, on the same server, and using ffmpeg's -i, with the -headers by sending the cookie and the headers, but I still get a decent amount of 403 errores.  

Is there a reason this would happen? Given that it is on the same IP as the initial scrape? Should I use -g instead?

**Comment by dstftw** [comment]
If downloading via youtube-dl itself does not result in 403 then you are most likely not passing headers/cookies correctly.

**Comment by nadermx** [comment]
@dstftw by chance do you have a example of a get request sent with headers? My current request header sends the cookie and headers like so
```

 "GET / HTTP/1.1" 200 -
Range: bytes=0-
Connection: close
Host: localhost:8000
Icy-MetaData: 1
Cookie: GPS=1; PREF=f1=50000000&hl=en; VISITOR_INFO1_LIVE=YYVg5wZlZM4; YSC=nqFTzbjynHk; s_gl=1d69aac621b2f9c0a25dade722d6e24bcwIAAABVUw==
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
```

**Comment by dstftw** [comment]
See `--print-traffic`.
