### ISSUE TITLE
Wakanim Site Support Request (different from other requests)

### ISSUE THREAD

**Issue by TA40** [rg3/youtube-dl#19008]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl.exe https://www.wakanim.tv/de/v2/catalogue/episode/7901/the-promised-neverland-omu-staffel-1-folge-3-omu -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.wakanim.tv/de/v2/catalogue/episode/7901/the-promised-neverland-omu-staffel-1-folge-3-omu', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.01.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 3.4.2, ffprobe N-84814-gad7aff0, rtmpdump 2.4
[debug] Proxy map: {}
[generic] the-promised-neverland-omu-staffel-1-folge-3-omu: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-promised-neverland-omu-staffel-1-folge-3-omu: Downloading webpage
[generic] the-promised-neverland-omu-staffel-1-folge-3-omu: Extracting information
ERROR: Unsupported URL: https://www.wakanim.tv/de/v2/catalogue/episode/7901/the-promised-neverland-omu-staffel-1-folge-3-omu
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.wakanim.tv/de/v2/catalogue/episode/7901/the-promised-neverland-omu-staffel-1-folge-3-omu
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.wakanim.tv/de/v2/catalogue/episode/7901/the-promised-neverland-omu-staffel-1-folge-3-omu
- Single video: https://www.wakanim.tv/de/v2/catalogue/show/435/the-promised-neverland-omu
- Playlist: -
---

### Description of your *issue*, suggested solution and other information
First: This is different from other opened site requests. The others want the stream to be downloaded (which isn't possible because of DRM protection).

I'd like you to add a way to download the download version from Wakanim.
(If you buy the episode for 1€/Ep. you can download them DRM-free in 720p and 1080p)
![image](https://user-images.githubusercontent.com/46388493/51791620-3fc9fa80-21a6-11e9-848f-cca8cabe4c61.png)
![image](https://user-images.githubusercontent.com/46388493/51791623-46f10880-21a6-11e9-96f3-06ae6de4e309.png)

I can provide you with an account and an VPN. Wakanim only operates in Germany, France, Russia and the Nordic countries. 
Could you please add this? Thanks :)

**Comment by TA40** [comment]
Like I said, it's not an 1:1 duplicate. 
I don't want the stream to be downloaded. I want the download version to be downloaded^^

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by TA40** [comment]
You've got an mail.

**Comment by TA40** [comment]
@dstftw did you got the mail?
