### ISSUE TITLE
libpostproc error on pulling audio format

### ISSUE THREAD

**Issue by vovchykbratyk** [rg3/youtube-dl#19013]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -f 140 https://www.youtube.com/playlist?list=PL4A2656CBD9104A26 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'140', u'https://www.youtube.com/playlist?list=PL4A2656CBD9104A26', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.24
[debug] Python version 2.7.10 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PL4A2656CBD9104A26: Downloading webpage
[download] Downloading playlist: Zelda twilight princess soundtrack
[youtube:playlist] PL4A2656CBD9104A26: Downloading page #1
[youtube:playlist] playlist Zelda twilight princess soundtrack: Downloading 196 videos
[download] Downloading video 1 of 196
[youtube] 7fmmMqjCaxY: Downloading webpage
[youtube] 7fmmMqjCaxY: Downloading video info webpage
[debug] Invoking downloader on u'https://r1---sn-5ualdn7r.googlevideo.com/videoplayback?ms=au%2Crdu&mt=1548562077&mv=m&dur=8.219&gir=yes&itag=140&signature=93CC173296067AF0721E72798814764E8267CED4.01444653DE4A4E2D20E43FCFAB57A49673316E9D&key=yt6&mn=sn-5ualdn7r%2Csn-5uaezny6&ipbits=0&fvip=1&mime=audio%2Fmp4&clen=132603&mm=31%2C29&requiressl=yes&source=youtube&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&initcwndbps=1736250&pl=34&c=WEB&keepalive=yes&id=o-AC1lY1hSkYE7ySCxusHUaa8iR76igN2OTuasdRwTynub&expire=1548583765&ei=9S5NXNTNF_KBlAOCj6PIBQ&ip=2601%3A100%3A4100%3A7de7%3Ae9aa%3Aef5a%3Aac7f%3A5314&lmt=1417326605597498&ratebypass=yes'
[download] Wii Channel - The Legend of Zelda - Twilight Princess-7fmmMqjCaxY.m4a has already been downloaded
[download] 100% of 129.50KiB
[ffmpeg] Correcting container in "Wii Channel - The Legend of Zelda - Twilight Princess-7fmmMqjCaxY.m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Wii Channel - The Legend of Zelda - Twilight Princess-7fmmMqjCaxY.m4a' -c copy -f mp4 'file:Wii Channel - The Legend of Zelda - Twilight Princess-7fmmMqjCaxY.temp.m4a'
ERROR:   libpostproc    55.  3.100 / 55.  3.100
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2051, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 542, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 221, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 217, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError:   libpostproc    55.  3.100 / 55.  3.100
```

---

**Comment by dstftw** [comment]
Post the output of `ffmpeg -y -i 'file:Wii Channel - The Legend of Zelda - Twilight Princess-7fmmMqjCaxY.m4a' -c copy -f mp4 'file:Wii Channel - The Legend of Zelda - Twilight Princess-7fmmMqjCaxY.temp.m4a'`.
