### ISSUE TITLE
[drtv] No Longer Working

### ISSUE THREAD

**Issue by finn-ellebaek-nielsen** [rg3/youtube-dl#19039]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.27*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

[drtv] No longer works, they must have made some changes on their servers as it was working a few days ago.

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

youtube-dl --verbose --list-formats "https://www.dr.dk/tv/se/bedrag/bedrag-iii/bedrag-iii-4-10"

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--list-formats', 'https://www.dr.dk/tv/se/bedrag/bedrag-iii/bedrag-iii-4-10']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.01.27
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-79344-g196cfc2, ffprobe N-79344-g196cfc2
[debug] Proxy map: {}
[drtv] bedrag-iii-4-10: Downloading webpage
[drtv] bedrag-iii-4-10: Downloading video JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpe5bj64ac\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpe5bj64ac\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpe5bj64ac\build\youtube_dl\extractor\drtv.py", line 161, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpe5bj64ac\build\youtube_dl\extractor\common.py", line 1305, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output....
<end of log>
```

### Description of your *issue*, suggested solution and other information

This used to work, some investigations of how to make it work again is probably needed.

**Comment by rubak** [comment]
Yes, definitely something changed in the API provided by https://dr.dk which is here: <https://www.dr.dk/mu-online/Help/1.4>.
When I look up the unique identifier `bedrag-iii-4-10` I can find the referenced manifest which *almost* looks like it used to:
<https://www.dr.dk/mu-online/api/1.3/manifest/urn:dr:mu:manifest:5c4740c16187a51250a0ee7c>

However, the field `Uri` is now `null`, where it used to have a long URI containing different quality options etc. (I don't recall the details). I have never used youtube-dl before, but had my own script to download shows from DR for offline viewing, but it stopped working today and I googled my way here. Let me know if I can assist in any way to find a workaround.

**Comment by Hrod-geir** [comment]
I can confirm that dstftw's correction of drtv.dk worked nicely 24 hours ago (not sure about subtitles) but fails again. Both evoking __main__.py and using latest version of the binary. I see you are looking at it again. Thanks for the effort.
