### ISSUE TITLE
How to deploy youtube-dl at aws lambda

### ISSUE THREAD

**Issue by navid5113** [rg3/youtube-dl#19044]
Why @datftw closed my question without any answering? This is how youtube-dl team common behavior. He closed my question several times

**Comment by Hrxn** [comment]
This is an issue tracker, tracking issues specific to youtube-dl. And nothing else.

**Comment by dstftw** [comment]
I've already pointed you to generic installation steps. If it does not work in yourcase then ask support of your platform/service you're using on how to install software. This is not a generic support forum and we do not track all existing platforms/FaaS/SaaS/whatever.
