### ISSUE TITLE
Feature Request: --annotation-source option

### ISSUE THREAD

**Issue by ealgase** [rg3/youtube-dl#19069]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

YouTube recently removed all old style annotations.  An archive (hosted at archive.omar.yt) has sprung up as a replacement.  A useful option to have would be to be able to choose between archive.omar.yt and youtube.com as the default annotation source.  By default, YouTube should be the source, except for when downloading from dev.invidio.us (when archive.omar.yt should be the default).

Example syntax:
`--annotation-source youtube` downloads annotations from YouTube
`--annotation-source invidious` downloads annotations from archive.omar.yt
`--annotation-source https://archive.omar.yt/api/v1/annotations/%(video_id)s` uses the url `https://archive.omar.yt/api/v1/annotations/VIDEO_ID` as the annotations file that is downloaded.

**Comment by tech234a** [comment]
While I can understand the reasoning for this being out-of-scope for this project, I would like to point out that this archive provides access to data that previously existed on the official YouTube site until it was removed on January 15. While data is still currently returned from the old endpoint on YouTube, this data now consists of only cards, end screens, and creator logos to be displayed in the corner of the video, not the legacy annotations available from this archive. I feel that this feature should be supported because many people use youtube-dl for archival purposes, and this feature would further that use case.
