### ISSUE TITLE
-o not working as expected when -x

### ISSUE THREAD

**Issue by qqgg231** [rg3/youtube-dl#19063]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.27*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
`youtube-dl.exe 4LfvziNR2KM -xf bestaudio[acodec=opus]`

works great, gives ogg container with .opus extension. However I need to change filename extension to .ogg or any other which Samsung Music recognizes as music

It is plain filename change, not any reencoding

I tried this, but does not work as expected with `-x`, it downloads  and saves video as `.ogg` but still gives `.opus` as final result, and deletes `.ogg` video file

` youtube-dl.exe 4LfvziNR2KM -xf bestaudio[acodec=opus] -o "%(title)s-%(id)s.ogg"`

How to do it? I ask for your help

**Comment by dstftw** [comment]
Do not hardcode the extension.

**Comment by qqgg231** [comment]
@dstftw  what is the soultion to this issue?

**Comment by qqgg231** [comment]
@dstftw I want to download opus audio and have it in .ogg file
