### ISSUE TITLE
[FEATURE REQUEST] - Add command to print subtitles to file

### ISSUE THREAD

**Issue by J316** [rg3/youtube-dl#19065]
When downloading with the ``` -x ```option sometimes it's useful to have the subtititles either written as a comment section of the output file or at least as a separate text file ad it happens for video descriptions.

**Comment by dstftw** [comment]
Have you even read [FAQ](https://github.com/rg3/youtube-dl#subtitle-options)?

**Comment by J316** [comment]
@dstftw I did. It doesn't say how to do this. Can you provide insight?

**Comment by J316** [comment]
@dstftw So, there is no explanation on how to do it in the FAQ, can you point a reference?

**Comment by dstftw** [comment]
Are you trolling or what? I've pointed **exact** place in FAQ where subtitles commands are explained.
