### ISSUE TITLE
Error: DEBUG  - message

### ISSUE THREAD

**Issue by kakitogit** [rg3/youtube-dl#19067]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.30*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.01.30
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Hi

i´m trying to download some MP3 from youtube (I just updated youtube-dl today) and i receiving the same error (Error: Debug)

sudo youtube-dl -v -x --audio-format mp3 "https://www.youtube.com/watch?v=5DuDgDbLR6o"
[debug] System config: [u'-o', u'%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-x', u'--audio-format', u'mp3', u'https://www.youtube.com/watch?v=5DuDgDbLR6o']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.30
[debug] Python version 2.7.9 (CPython) - Linux-4.4.50-v7+-armv7l-with-debian-8.0
*** stack smashing detected ***: rtmpdump terminated
[debug] exe versions: avconv 11.9-6, avprobe 11.9-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 5DuDgDbLR6o: Downloading webpage
[youtube] 5DuDgDbLR6o: Downloading video info webpage
[youtube] {18} signature length 41.41, html5 player vflemibiK
[youtube] {36} signature length 41.41, html5 player vflemibiK
[youtube] {17} signature length 41.41, html5 player vflemibiK
[youtube] {313} signature length 41.41, html5 player vflemibiK
[youtube] {271} signature length 41.41, html5 player vflemibiK
[youtube] {137} signature length 41.41, html5 player vflemibiK
[youtube] {248} signature length 41.41, html5 player vflemibiK
[youtube] {136} signature length 41.41, html5 player vflemibiK
[youtube] {247} signature length 41.41, html5 player vflemibiK
[youtube] {135} signature length 41.41, html5 player vflemibiK
[youtube] {244} signature length 41.41, html5 player vflemibiK
[youtube] {134} signature length 41.41, html5 player vflemibiK
[youtube] {243} signature length 41.41, html5 player vflemibiK
[youtube] {133} signature length 41.41, html5 player vflemibiK
[youtube] {242} signature length 41.41, html5 player vflemibiK
[youtube] {160} signature length 41.41, html5 player vflemibiK
[youtube] {278} signature length 41.41, html5 player vflemibiK
[youtube] {140} signature length 41.41, html5 player vflemibiK
[youtube] {171} signature length 41.41, html5 player vflemibiK
[youtube] {249} signature length 41.41, html5 player vflemibiK
[youtube] {250} signature length 41.41, html5 player vflemibiK
[youtube] {251} signature length 41.41, html5 player vflemibiK
[debug] Invoking downloader on u'https://r1---sn-h5q7dnlk.googlevideo.com/videoplayback?mn=sn-h5q7dnlk%2Csn-25glenez&mm=31%2C26&source=youtube&gir=yes&ip=88.18.163.209&fvip=1&ms=au%2Conr&ei=s9NQXKCLOcWDxwKkm7HQCA&id=o-AAADHx54gFlz2OpPhAvEMHDjUp0gRrU-P3yiPeEbJIw3&pl=16&mv=m&mt=1548800811&dur=205.741&expire=1548822548&mime=audio%2Fwebm&gcr=es&itag=251&keepalive=yes&ipbits=0&c=WEB&txp=5511222&initcwndbps=851250&key=yt6&requiressl=yes&clen=3441324&lmt=1548402443061733&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&signature=449346C43A1C580D04592E6FE19C5C483B50A56F.90116A924F5E2EB1FA890811D5571BF4E470EB8E&ratebypass=yes'
[download] Destination: Lola Indigo - Fuerte.webm
[download] 100% of 3.28MiB in 00:00
[debug] avconv command line: avprobe -show_streams 'file:Lola Indigo - Fuerte.webm'
[ffmpeg] Destination: Lola Indigo - Fuerte.mp3
[debug] ffmpeg command line: avconv -y -loglevel 'repeat+info' -i 'file:Lola Indigo - Fuerte.webm' -vn -acodec libmp3lame '-q:a' 5 'file:Lola Indigo - Fuerte.mp3'
ERROR: audio conversion failed: "debug"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2051, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 337, in run
    'audio conversion failed: ' + e.msg)
PostProcessingError: audio conversion failed: "debug"

could you please help me?

Thanks.

**Comment by barsnick** [comment]
> And.. what is the solution? What could i do?

Update to youtube-dl 2019.01.30.1, where the fix is integrated. (Or use ffmpeg instead of avconv.)

**Comment by Aankhen** [comment]
For anyone suddenly encountering this: I hit it recently, and it turned out I had the wrong `ffmpeg` in my `PATH`, so double-check that `which ffmpeg` (`where ffmpeg` on Windows) is showing you the right one.
