### ISSUE TITLE
Xvideos not downloading

### ISSUE THREAD

**Issue by dendory** [rg3/youtube-dl#19075]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

$ /usr/local/bin/youtube-dl --prefer-free-formats --no-check-certificate https://www.xvideos.com/video35378979/  -o /storage/test.mp4 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--prefer-free-formats', '--no-check-certificate', 'https://www.xvideos.com/video35378979/', '-o', '/storage/test.mp4', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.30
[debug] Python version 3.4.9 (CPython) - Linux-3.10.0-514.2.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[XVideos] 35378979: Downloading webpage
[XVideos] 35378979: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://vid3-l3.xvideos-cdn.com/videos/mp4/5/f/c/xvideos.com_5fc72e0ec25a475df97961888efcd78a.mp4?e=1548886400&ri=1024&rs=85&h=ad57e33c3ed66e55c779a08d154362b3'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1912, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1851, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 2215, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 470, in open
    response = meth(req, response)
  File "/usr/lib64/python3.4/urllib/request.py", line 580, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.4/urllib/request.py", line 508, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 588, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by alexvong1995** [comment]
@dendory
I cannot reproduce it. I get the following output:
```
alexvong1995@debian:~$ torsocks youtube-dl --prefer-free-formats https://www.xvideos.com/video35378979/
[XVideos] 35378979: Downloading webpage
[XVideos] 35378979: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 175
[download] Destination: Japanese lesbian sleeping-35378979.mp4
```
Does the error persist?

**Comment by dendory** [comment]
Actually I'm thinking it's probably an IP ban... nevermind.

	$ wget "https://vid3-l3.xvideos-cdn.com/videos/mp4/5/f/c/xvideos.com_5fc72e0ec25a475df97961888efcd78a.mp4?e=1548886400&ri=1024&rs=85&h=ad57e33c3ed66e55c779a08d154362b3"
	--2019-02-06 15:21:23--  https://vid3-l3.xvideos-cdn.com/videos/mp4/5/f/c/xvideos.com_5fc72e0ec25a475df97961888efcd78a.mp4?e=1548886400&ri=1024&rs=85&h=ad57e33c3ed66e55c779a08d154362b3
	Resolving vid3-l3.xvideos-cdn.com (vid3-l3.xvideos-cdn.com)... 8.252.110.123, 8.252.193.251, 8.252.195.251, ...
	Connecting to vid3-l3.xvideos-cdn.com (vid3-l3.xvideos-cdn.com)|8.252.110.123|:443... connected.
	HTTP request sent, awaiting response... 403 Forbidden
	2019-02-06 15:21:24 ERROR 403: Forbidden.

**Comment by alexvong1995** [comment]
@dendory

Interestingly, I get the same output as you when I run the
> torsocks wget ...
command:

> alexvong1995@debian:~$ LC_ALL=C torsocks wget "https://vid3-l3.xvideos-cdn.com/videos/mp4/5/f/c/xvideos.com_5fc72e0ec25a475df97961888efcd78a.mp4?e=1548886400&ri=1024&rs=85&h=ad57e33c3ed66e55c779a08d154362b3"
> --2019-02-07 03:20:52--  https://vid3-l3.xvideos-cdn.com/videos/mp4/5/f/c/xvideos.com_5fc72e0ec25a475df97961888efcd78a.mp4?e=1548886400&ri=1024&rs=85&h=ad57e33c3ed66e55c779a08d154362b3
> Resolving vid3-l3.xvideos-cdn.com (vid3-l3.xvideos-cdn.com)... 67.27.121.251
> Connecting to vid3-l3.xvideos-cdn.com (vid3-l3.xvideos-cdn.com)|67.27.121.251|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2019-02-07 03:20:56 ERROR 403: Forbidden.

I think what's happening is that they block 'wget' from fetching their
site.

If you think they ban your IP, you can install 'tor' and 'torsocks' from
your distro and run
> torsocks youtube-dl ...
instead of
> youtube-dl ...

One more thing: If you decide to install 'tor' and 'torsocks', I
recommend you to set
> IsolatePID
to
> 1
in
> /etc/tor/torsocks.conf

This improves stream isolation:
https://www.whonix.org/wiki/Stream_Isolation
I think this should be the default. Please look at
https://manpages.debian.org/unstable/torsocks/torsocks.conf.5.en.html
to decide if you want to set that option.
