### ISSUE TITLE
Crunchyroll: --geo-verification-proxy doesn't change metadata locale

### ISSUE THREAD

**Issue by Atemu** [rg3/youtube-dl#19082]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Debug output

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--geo-verification-proxy', '<redacted>', '-e', 'https://www.crunchyroll.com/a-place-further-than-the-universe/episode-1-one-mwillion-yen-for-youth-757769', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 3.7.2 (CPython) - Linux-4.20.5-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
A Place Further Than the Universe Folge 1 – Die Jugend für eine Million Yen
```
### Description of your *issue*, suggested solution and other information

[This episode](https://www.crunchyroll.com/a-place-further-than-the-universe/episode-1-one-mwillion-yen-for-youth-757769) is available in my region and has a localized metadata (title, description etc.).  
When using a VPN I get "A Place Further Than the Universe Episode 1 – One Mwillion Yen For Youth" for the title but without a VPN and with `--geo-verification-proxy <us proxy>` I get "A Place Further Than the Universe Folge 1 – Die Jugend für eine Million Yen" which obviously isn't US English. 

The Readme makes it sound like the global proxy is only used for downloading when `--geo-verification-proxy` is enabled which should mean that the geo verification proxy is used for downloading everything else (including metadata) but if that's not the case I'll make a separate feature request for a metadata-proxy or general language flag (a proxy probably isn't required to get a different locale on most sites).

**Comment by dstftw** [comment]
`--geo-verification-proxy` gives no guarantees on metadata. It's only used for requests that check geo location in order to bypass such restrictions. There are still no guarantees even if it happens to be used for metadata requests since a remote party actually decides what metadata to send and it's not necessarily depends on external IP.
