### ISSUE TITLE
youtube-dl does not download videos to the directory it's in

### ISSUE THREAD

**Issue by sdtqwe4ty** [rg3/youtube-dl#19117]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=bw9CALKOvAI']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] bw9CALKOvAI: Downloading webpage
[youtube] bw9CALKOvAI: Downloading video info webpage
[youtube] {18} signature length 41.40, html5 player vflehrYuM
[youtube] {36} signature length 41.40, html5 player vflehrYuM
[youtube] {17} signature length 41.40, html5 player vflehrYuM
[youtube] {137} signature length 41.40, html5 player vflehrYuM
[youtube] {248} signature length 41.40, html5 player vflehrYuM
[youtube] {136} signature length 41.40, html5 player vflehrYuM
[youtube] {247} signature length 41.40, html5 player vflehrYuM
[youtube] {135} signature length 41.40, html5 player vflehrYuM
[youtube] {244} signature length 41.40, html5 player vflehrYuM
[youtube] {134} signature length 41.40, html5 player vflehrYuM
[youtube] {243} signature length 41.40, html5 player vflehrYuM
[youtube] {133} signature length 41.40, html5 player vflehrYuM
[youtube] {242} signature length 41.40, html5 player vflehrYuM
[youtube] {160} signature length 41.40, html5 player vflehrYuM
[youtube] {278} signature length 41.40, html5 player vflehrYuM
[youtube] {140} signature length 41.40, html5 player vflehrYuM
[youtube] {171} signature length 41.40, html5 player vflehrYuM
[youtube] {249} signature length 41.40, html5 player vflehrYuM
[youtube] {250} signature length 41.40, html5 player vflehrYuM
[youtube] {251} signature length 41.40, html5 player vflehrYuM
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r2---sn-vgqsknes.googlevideo.com/videoplayback?fvip=2&dur=214.970&initcwndbps=1950000&txp=5531432&ipbits=0&ratebypass=yes&key=yt6&c=WEB&itag=18&clen=19297391&mn=sn-vgqsknes%2Csn-ab5l6nzd&pl=16&source=youtube&mm=31%2C26&ip=71.194.164.33&mime=video%2Fmp4&requiressl=yes&expire=1549195944&mv=m&mt=1549174226&ms=au%2Conr&id=o-APkSFVeHY6JqnfX6uTz4a8rJVZMBYM2_Pb6AKiNeGRi-&lmt=1540572321558219&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&gir=yes&ei=SIZWXK6lBMnXwQHtp6fQBw&signature=15CC2E62C00CF1376D49FA4191366674B0041572.BFA2210454D98B61391A0C347EA672C76F06ABB8'
[download] Destination: HYUNA - 'Bubble Pop!' (Official Music Video)-bw9CALKOvAI.mp4
[download] 100% of 18.40MiB in 00:02
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

it downloads videos to my user folder even though youtube-dl.exe  is not located there.  I created a configuration file in hopes of coaxing youtube-dl to behave. It returned: ERROR: fixed output name but more than one file to download

**Comment by dstftw** [comment]
It's not supposed to. It downloads to the current directory your shell points to.
