### ISSUE TITLE
Android Support ?

### ISSUE THREAD

**Issue by VishalIstek** [rg3/youtube-dl#19118]
I cant't make more hacky ways to support android.
Please give support for it.
the current code is quite messy and not managed so if you can give details on how the code is working, it would be great to convert it into an library.

**Comment by VishalIstek** [comment]
I didn't get this  "conforming python interpreter"

**Comment by VishalIstek** [comment]
@dstftw I didn't get this "conforming python interpreter"

**Comment by dstftw** [comment]
Bad for you. That's not our problem.

**Comment by alexvong1995** [comment]
@VishalIstek
Basically it means it can run any python program that
[cpython (the reference implementation)](https://en.wikipedia.org/wiki/CPython)
can run, e.g. [pypy](https://pypy.org/compat.html), jython...

**Comment by cuongpm** [comment]
Hi @VishalIstek 
I think [youtube-dl-android](https://github.com/cuongpm/youtube-dl-android) is something you're searching for. It's an Android client for [youtube-dl](https://github.com/ytdl-org/youtube-dl/)

- Medium: https://medium.com/@cuongpm29/video-downloader-app-for-android-with-youtube-dl-fc2fc05cb55e
- Github: https://github.com/cuongpm/youtube-dl-android
