### ISSUE TITLE
whats the command that i want to download the 30 seconds of video  thank you 

### ISSUE THREAD

**Issue by asssdasad** [rg3/youtube-dl#19139]
whats the command that i want to download the 30 seconds of video  thank you

**Comment by dstftw** [comment]
No such comand.

**Comment by alexvong1995** [comment]
@asssdasad

I figure out how to download only the first 30 seconds of the video without
cutting in #19166.

Assuming you have `ffmpeg` installed. The following shell command should
download the first 30 seconds of the video and output it as `out.mkv`:
```
youtube-dl -o - -f best 'https://www.youtube.com/watch?v=BaW_jenozKc' | ffmpeg -i - -ss 0 -t 30 -c copy out.mkv
```
