### ISSUE TITLE
Soundcloud set fails to download when a song is deleted (404)

### ISSUE THREAD

**Issue by sorashi** [rg3/youtube-dl#19130]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

### Description

Running this command

`youtube-dl https://soundcloud.com/nyanners/sets/nyannerz-gonna-give-it-to-ya-x2-nekomimi-reloaded`

Fails with

```
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>);
```

[full log here](https://gist.github.com/sorashi/eefe7475e5cc2059edec2b2b99ee9613)

The problem is that this Soundcloud set used to contain a song, but that song was deleted or is inaccessible. I think the JSON metadata still contains the song, so youtube-dl tries to reach it, but fails due to 404 response. These issues seem related #18954 #18746

**Comment by sorashi** [comment]
I just realized this can be resolved by passing the `-i` option. I will still leave this issue open for consideration.

**Comment by dstftw** [comment]
This is expected behavior.
