### ISSUE TITLE
[Crunchyroll] Use system locale for metadata language

### ISSUE THREAD

**Issue by Atemu** [rg3/youtube-dl#19138]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl -v -e 'https://www.crunchyroll.com/a-place-further-than-the-universe/episode-1-one-mwillion-yen-for-youth-757769'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-e', 'https://www.crunchyroll.com/a-place-further-than-the-universe/episode-1-one-mwillion-yen-for-youth-757769']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 3.7.2 (CPython) - Linux-4.20.6-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
A Place Further Than the Universe Folge 1 – Die Jugend für eine Million Yen
```

### Description of your *issue*, suggested solution and other information

When I download videos from Crunchyroll, the metadata like title, description etc. are all in the language based on my IP address which in my case is German.  
CR is an extra bit annoying here because they seem to always localize the string "Episode" even if the title itself isn't localized, so you get titles like ["Gintama *Folge* 1 – You Guys!! Do You Even Have a Gintama? (Part 1)"](https://www.crunchyroll.com/de/gintama/episode-1-you-guys-do-you-even-have-a-gintama-part-1-510074).
The URLs I give `youtube-dl` are from the en-US site (not `crunchyroll.com/de/`) and if I opened the same URL in an incognito window, I'd get the en-US site by default (both browser and system locale are en-US).
A possible workaround is to use `crunchyroll.com/en-gb/` URLs to force at least the English language but there might be small differences between the en-GB and en-US site and it shouldn't be necessary.

Would it be possible to get the CR metadata in the language of the system locale instead of letting CR decide the language based on my IP address?

**Comment by dstftw** [comment]
For any work on this you must provide reproducible environment.

**Comment by Atemu** [comment]
This should be reproducible:

```
youtube-dl -v -e --proxy 46.101.107.98:8888  'https://www.crunchyroll.com/a-place-further-than-the-universe/episode-1-one-mwillion-yen-for-youth-757769' 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-e', '--proxy', '46.101.107.98:8888', 'https://www.crunchyroll.com/a-place-further-than-the-universe/episode-1-one-mwillion-yen-for-youth-757769']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 3.7.2 (CPython) - Linux-4.20.6-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, rtmpdump 2.4
[debug] Proxy map: {'http': '46.101.107.98:8888', 'https': '46.101.107.98:8888'}
[debug] Default format spec: bestvideo+bestaudio/best
A Place Further Than the Universe Folge 1 – Die Jugend für eine Million Yen
```
