### ISSUE TITLE
PhantomJS  not detected on Linux(centos 6)

### ISSUE THREAD

**Issue by TheGr33k** [rg3/youtube-dl#19133]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
---

I have already install phantomJS  and its in my PATH since the command below works.

PHP 

`echo exec("phantomjs -v");`

Result: 2.2.1

However when i execute youtube-dl for openload or pornhub i get the following error

ERROR: PhantomJS executable not found in PATH, download it from http://phantomjs.org

**Comment by dstftw** [comment]
Most likely you run youtube-dl with invalid environment or under different user that does not have it in `PATH`.

**Comment by TheGr33k** [comment]
Nope i run youtube-dl with same user
