### ISSUE TITLE
login information should not be carried from vk to vimeo

### ISSUE THREAD

**Issue by colourful-land** [rg3/youtube-dl#19147]
Using: *2019.01.30.1* on Ubuntu 18.04†

Reproduce the problem:

    $ youtube-dl -u [username] -p [password] https://vk.com/video263838471_169844543
    [vk] Downloading login page
    [vk] Logging in
    [vk] 263838471_169844543: Downloading webpage
    [vimeo] Downloading login page
    [vimeo] Logging in
    ERROR: Unable to log in: bad username or password

Expected:

    $ youtube-dl -u [username] -p [password] https://vk.com/video263838471_169844543
    [vk] Downloading login page
    [vk] Logging in
    [vk] 263838471_169844543: Downloading webpage
    [vimeo] 73010827: Downloading webpage
    ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please 
    report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl - 
   U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

As you can see, youtube-dl correctly followed the link to Vimeo, but assumed that the same username and password supplied in the commandline should be used to login to vimeo. In reality this is unlikely what the user has wanted. Given that allowing credential to be supplied for each possible redirect target (viemo) is too big a change to the commandline parameter structure, I propose not logging in at all after a redirect, to reduce the security exposure of passing a password to the site that shouldn't learn it.

(P.S. don't be distracted by vimeo reporting 404 - It's the problem of this specific test link. I couldn't find a better test link.)

† Linux 4.15.0-44-generic #47-Ubuntu SMP Mon Jan 14 11:26:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by colourful-land** [comment]
@dstftw are you sure this is a duplicate of #15840 ? 

#15840 is about the video processing after it is downloaded, this issue happens before download could happen.

**Comment by dstftw** [comment]
It's not, I did not even mentioned it.
