### ISSUE TITLE
downloading audio from youtube with ext downloader is slow

### ISSUE THREAD

**Issue by LonJonn** [rg3/youtube-dl#19142]
using the default downloader, the audio is downloaded extremely fast, however piping the url from --dump-json or just using an external downloader such as curl results in extremely slow speeds ONLY for audio. Video works just fine.
For eg. (excuse the images, formatting went wack in the editor)

`youtube-dl --external-downloader curl -f bestaudio https://www.youtube.com/watch?v=WqCpWu8tgRw`:
![image](https://user-images.githubusercontent.com/13981703/52274085-c4372d00-299f-11e9-9798-399f37c720a9.png)

but, `youtube-dl --external-downloader curl -f best https://www.youtube.com/watch?v=WqCpWu8tgRw`:
![image](https://user-images.githubusercontent.com/13981703/52274122-d44f0c80-299f-11e9-802d-a8c7a5b05431.png)

Audio struggles along while video does exceptionally well and this is true for any external downloader, but not for the default youtube-dl downloader.

**Comment by dstftw** [comment]
Youtube throttles download. To download at high speed downloader must reopen connection per each ~10MiB chunk.

**Comment by Hrxn** [comment]
For the record, video is not "just fine", it should be throttled as well.
Try it with `-f bestvideo` instead of `-f best` like in your original example. `-f best` is low-res only.
