### ISSUE TITLE
Unable to download videos from https://multicampus.udemy.com/

### ISSUE THREAD

**Issue by charlieInDen** [rg3/youtube-dl#19152]
nishant.s1$ youtube-dl --version
2019.01.30.1

I changed password for now in below command:

nishant.s1$ youtube-dl -u nishant.s1@samsung.com -p **Password**  -o '%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://multicampus.udemy.com/pmp-pmbok6-35-pdus/learn/v4/t/lecture/8315176?start=15

[generic] 8315176?start=15: Requesting header
WARNING: Could not send HEAD request to https://multicampus.udemy.com/pmp-pmbok6-35-pdus/learn/v4/t/lecture/8315176?start=15: HTTP Error 403: Unauthorized
[generic] 8315176?start=15: Downloading webpage

**ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.**

I have Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ *] Bug report (encountered problems with youtube-dl)
- [ *] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

Please help. check above command and its response.

**Comment by charlieInDen** [comment]
Hi ,
As you marked duplicate, how can I check the status?

**Comment by remitamine** [comment]
Obviously, go to the original issue #15883.
