### ISSUE TITLE
No documentation for embedding youtube_dl

### ISSUE THREAD

**Issue by basswaver** [rg3/youtube-dl#19169]
There is no real documentation for how to use youtube_dl as an import, with the link to options [here](https://github.com/rg3/youtube-dl/blob/3e4cedf9e8cd3157df2457df7274d0c842421945/youtube_dl/YoutubeDL.py#L137-L312) being lacking at best (as it provides no real information). Is there another resource providing information that I'm missing?

**Comment by dstftw** [comment]
[Really](https://github.com/rg3/youtube-dl#embedding-youtube-dl)?

**Comment by basswaver** [comment]
I'd hardly consider a paragraph that can be summed up as "you can import it" as documentation.
