### ISSUE TITLE
Timer for streaming

### ISSUE THREAD

**Issue by gioreva** [rg3/youtube-dl#19166]
How can I record only a limited time, a streaming ?
30 minuts and stop.

**Comment by gioreva** [comment]
I don't want to cut a video.
I want to stop the download after half an hour, otherwise download indefinitely.
I plan the recording at a certain time, which lasts only half an hour.

**Comment by alexvong1995** [comment]
@gioreva

Can you provide an example? Right now I can only guess your requirement.

Assuming you have `ffmpeg` installed. Does the following shell command work for
you?
```
youtube-dl -o - -f best 'https://www.youtube.com/watch?v=BaW_jenozKc' | ffmpeg -i - -ss 0 -t 30:00 -c copy out.mkv
```
The above command downloads the first *t* minutes of the video
where 0 ≤ *t* ≤ 30 and then outputs it as `out.mkv`.

**Comment by gioreva** [comment]
This for windows ?
Your example download full video, then ffmpeg cut 30 mins
I need to record on the tv, streaming is unlimitated time.
I want to recorder documentari, 30/50 minutes,  from continus channel.
youtube-dl http://tv.net:2300/user/password/channel  -o ufo.avi

**Comment by alexvong1995** [comment]
@gioreva

gioreva <notifications@github.com> writes:

> This for windows ?

No, it is not. But it can be easily changed to work for windows.

First, download youtube-dl
and ffmpeg <https://www.ffmpeg.org/download.html>.

> Your example download full video, then ffmpeg cut 30 mins
> I need to record on the tv, streaming is unlimitated time.
> I want to recorder documentari, 30/50 minutes, from continus channel.
> youtube-dl  -o ufo.avi
>
Then run the following command:
> youtube-dl.exe -o - -f best 'http://tv.net:2300/user/password/channel' | ffmpeg.exe -i - -ss 0 -t 30:00 ufo.mkv

Finally, the file can be played by vlc <https://www.videolan.org/vlc/>.

**Comment by Caian** [comment]
> @gioreva gioreva <notifications@github.com> writes:
> This for windows ?
> No, it is not. But it can be easily changed to work for windows. First, download youtube-dl and ffmpeg <https://www.ffmpeg.org/download.html>.
> Your example download full video, then ffmpeg cut 30 mins I need to record on the tv, streaming is unlimitated time. I want to recorder documentari, 30/50 minutes, from continus channel. youtube-dl -o ufo.avi
> Then run the following command:
> youtube-dl.exe -o - -f best "http://tv.net:2300/user/password/channel" | ffmpeg.exe -i - -ss 0 -t 30:00 ufo.mkv
> Finally, the file can be played by vlc <https://www.videolan.org/vlc/>.
> […](#)
> — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

I would like to reopen this issue because the proposed solution does not work properly.

Piping the output into `ffmpeg` causes a high CPU usage on low performance devices, like Raspberry Pi, that otherwise would not be present without the pipe.

I am aware of the issue #1978 and I was too unsuccessful at stopping `youtube-dl` with the `kill` command, on Linux with ytdl version 2020.09.20.
