### ISSUE TITLE
REQUEST IN HTTPS BECAUSE YOU CAN

### ISSUE THREAD

**Issue by punuparcel4net** [rg3/youtube-dl#19168]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description

Letting your application talk in HTTP in 2019 is absurd enough to be a bug.
Just a single extra letter “`s`” makes you _secure_. Why the hell not?

https://github.com/rg3/youtube-dl/blob/91effe22a091035bc5abace2fcf562a0db89090f/youtube_dl/extractor/pornhub.py#L169-L173

 And this'll make @denotexist (https://github.com/rg3/youtube-dl/issues/12722) happy, since they don't block HTTPS requests.

DO NOT IGNORE THIS ISSUE.

**Comment by dstftw** [comment]
Does not make much difference since it's redirected to https version anyway.
Also nothing to do with #12722.

**Comment by alexvong1995** [comment]
@dstftw

Will patch to change to use HTTPS where possible be accepted? I've done similar
things in other project:
https://git.savannah.gnu.org/cgit/guix.git/commit/?id=98b90194d388b24fc1c0397dbc1b447e1e1ebd2d

IMO, we shouldn't depend on the site doing the right thing, as some may still
not have redirection enabled.

**Comment by punuparcel4net** [comment]
@dstftw 

> Does not make much difference since it's redirected to https version anyway.
> Also nothing to do with #12722.

Yeah, thanks for the expected answer from you.
Don't you see https://github.com/rg3/youtube-dl/issues/12722 happens because HTTP packets are _visible_?
Every HTTP packets to PornHub is blocked in the ISP level.


Are you seriously saying you don't give a fuck to your application's security?

```
<html><script>
var arg = "http://warning.or.kr";
var str = new Array();
str = arg.split("&", 1);
var a = new Array();
a = str[0].split("=");
var b = Math.floor(a[1] / 100);
var c = new Array();
if(b == 10){location.replace("http://www.naver.com");}
else if(b == 20){location.replace("http://www.daum.net");}
else if(b == 30){location.replace("http://www.paran.com");}
else{ c = a[0].split("?");
location.replace(c[0]);}
</script></html>
```
