### ISSUE TITLE
[linkedin:learning] template chapter's id/number broken

### ISSUE THREAD

**Issue by MBryde** [rg3/youtube-dl#19162]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl --proxy XXXXXXXX:XXXXXXXX@VPN.com:80 \
--username XXXXXXXX --password XXXXXXXX \
-f 'bestvideo[height<=720]+bestaudio/best[height<=720]' \
-o "%(playlist_title)s/Lesson %(chapter_number)s / %(chapter_id)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" --add-metadata --write-sub --limit-rate 2M --min-sleep-interval 5 --max-sleep-interval 10 \
"https://www.linkedin.com/learning/photoshop-cc-2018-essential-training-the-basics" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--proxy', u'XXXXXXXX:XXXXXXXX@VPN.com:80', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'-f', u'bestvideo[height<=720]+bestaudio/best[height<=720]', u'-o', u'%(playlist_title)s/Lesson %(chapter_number)s / %(chapter_id)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', u'--add-metadata', u'--write-sub', u'--limit-rate', u'2M', u'--min-sleep-interval', u'5', u'--max-sleep-interval', u'10', u'https://www.linkedin.com/learning/photoshop-cc-2018-essential-training-the-basics', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.18.6-041806-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
[debug] Proxy map: {u'http': u'XXXXXXXX:XXXXXXXX@VPN.com:80', u'https': u'XXXXXXXX:XXXXXXXX@VPN.com:80'}
[linkedin:learning:course] Downloading login page
[linkedin:learning:course] Logging in
[linkedin:learning:course] Downloading JSON metadata
[download] Downloading playlist: Photoshop CC 2018 Essential Training: The Basics
[linkedin:learning:course] playlist Photoshop CC 2018 Essential Training: The Basics: Collected 63 video ids (downloading 63 of them)
[download] Downloading video 1 of 63
[linkedin:learning] Downloading login page
[linkedin:learning] Logging in
[linkedin:learning] welcome: Downloading 360p JSON metadata
[linkedin:learning] welcome: Downloading 540p JSON metadata
[linkedin:learning] welcome: Downloading 720p JSON metadata
[linkedin:learning] welcome: Downloading m3u8 information
[debug] Invoking downloader on u'https://files3.lynda.com/secure/courses/625922/VBR_MP4h264_main_HD720/625922_00_01_WX30_welPSE.mp4?5Pe0ZAUYbIOU5NpJh0BFBTMudP8_1kbG4X-jHWHK-RxaIB1h8dqZnNZMOWzHxg9n4rD5KRpaM6lbV-r8z5YGst3FqT0bZ3iKutuaLhNzEk3wH5YFm5I-a4DzlefuVj-PM-e3KMPklDNS1jV_GIi1IVb-gPLkyflZStbr6OyAjyXaFPXYpjkXYw'
[download] Sleeping 9.38 seconds...
[download] Destination: Photoshop CC 2018 Essential Training - The Basics/Lesson NA / NA - Introduction/01 - Welcome.mp4
[download]  53.7% of 7.45MiB at  3.85MiB/s ETA 00:00
```

---

### Description of your *issue*, suggested solution and other information

This template used to rip lynda.com courses worked fine. But after migrating to linkedin:learning, non of the `chapter_id` or `chapter_number` are working anymore the all just end up as NA. As you can se in the [download] Destination at the end of the debug log.

**Comment by alexvong1995** [comment]
Please provide the required username and password, otherwise it is impossible
to download the above playlist.

**Comment by MBryde** [comment]
Nice troll @alexvong1995 - like I want my personal password for my vpn and linkedin account for everyone to scrape and use.

**Comment by MBryde** [comment]
Regarding @remitamine - the commit on [https://github.com/rg3/youtube-dl/commit/91effe22a091035bc5abace2fcf562a0db89090f](91effe2) don't seemed to have fixed it for me. Still returns with `NA`

**Comment by alexvong1995** [comment]
@MBryde

MBryde <notifications@github.com> writes:

> Nice troll @alexvong1995 - like I want my personal password for my vpn and linkedin
> account for everyone to scrape and use.
>
I am not interested in your **real** password. One can simply provide
any password that works for **testing** purposes.

I agree I should make it clear that I want **testing** password not
**real** password.

See https://github.com/rg3/youtube-dl/issues/19131 for details.

**Comment by alexvong1995** [comment]
@MBryde

MBryde <notifications@github.com> writes:

> Regarding @remitamine - the commit on
> https://github.com/rg3/youtube-dl/commit/91effe22a091035bc5abace2fcf562a0db89090f
> don't seemed to have fixed it for me. Still returns with NA
>
You can re-open the issue if you wish.

**Comment by remitamine** [comment]
it does:
```
[linkedin:learning:course] Downloading JSON metadata
[download] Downloading playlist: Photoshop CC 2018 Essential Training: The Basics
[linkedin:learning:course] playlist Photoshop CC 2018 Essential Training: The Basics: Collected 63 video ids (downloading 63 of them)
[download] Downloading video 1 of 63
[linkedin:learning] welcome: Downloading 360p JSON metadata
[linkedin:learning] welcome: Downloading 540p JSON metadata
[linkedin:learning] welcome: Downloading 720p JSON metadata
[linkedin:learning] welcome: Downloading m3u8 information
[download] Destination: Photoshop CC 2018 Essential Training - The Basics/Lesson 1/671386 - Introduction/01 - Welcome.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  5 7627k    5  399k    0     0   291k      0  0:00:26  0:00:01  0:00:25  291k
```

**Comment by MBryde** [comment]
@remitamine could you please provide the template you used? I can't get `chapter_number` or `chapter_id` working still. And I did try to update first but I still get NA on both for some reason.

**Comment by remitamine** [comment]
it's not released yet, wait for next release.

**Comment by MBryde** [comment]
Ah alright. That makes sense then. Didn't check, that their was no new release. My bad :D

**Comment by alexvong1995** [comment]
@MBryde

MBryde <notifications@github.com> writes:

> Ah alright. That makes sense then. Didn't check, that their was no new release. My bad :D
>
If you want to try the development version right now. You can run
youtube-dl in the following way:

> git clone https://github.com/rg3/youtube-dl
> cd youtube-dl
> python3 -m youtube_dl ...

assuming you have python 3 installed.

**Comment by nara20** [comment]
Hi,

I think there is a new issue with [linkedin:learning]  :
https://github.com/ytdl-org/youtube-dl/issues/20431

Regards,
