### ISSUE TITLE
Some youtube videos fail to download with "-f best" option (Did not get any data blocks)

### ISSUE THREAD

**Issue by Max-E** [rg3/youtube-dl#19175]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
/tmp$ youtube-dl -f best -v https://www.youtube.com/watch?v=s74jgtegJmU 
[debug] System config: [u'-f', u'best', u'--no-mtime', u'-o', u'%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'best', u'-v', u'https://www.youtube.com/watch?v=s74jgtegJmU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.08
[debug] Python version 2.7.15+ (CPython) - Linux-4.19.0-1-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, phantomjs 5, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] s74jgtegJmU: Downloading webpage
[youtube] s74jgtegJmU: Downloading video info webpage
[debug] Invoking downloader on u'https://r2---sn-nx5s7n7s.googlevideo.com/videoplayback?fvip=2&dur=1836.117&id=o-AGRWTJ_nLH6x2O2B3fzwnzMZe4FNmAz-rB4VjTh-Nz3w&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mm=31%2C29&signature=A8FC5ED5A4C65BA0032B6A47A377BD71C56545A2.4F0B36A913BC299F32ED31F6E6E8CAFE18082CCE&mime=video%2Fmp4&txp=4532432&ms=au%2Crdu&ipbits=0&mn=sn-nx5s7n7s%2Csn-nx5e6n7d&mv=m&pl=26&key=yt6&ip=2601%3A1c2%3A600%3A445b%3A%3A57f&ratebypass=yes&source=youtube&lmt=1549654753295507&expire=1549728069&ei=5aReXPXsEsilkwaQyZfoBg&requiressl=yes&c=WEB&itag=22&mt=1549706397&initcwndbps=2096250'
[download] Destination: Ask GN 106 - Is AMD Losing Money on Radeon VII Are Paid Reviews Bad.mp4
[download]   0.4% of 195.97MiB at  1.66MiB/s ETA 01:57[download] Got server HTTP error: Downloaded 811472 bytes, expected 205491244 bytes. Retrying (attempt 1 of 10)...
[download] Destination: Ask GN 106 - Is AMD Losing Money on Radeon VII Are Paid Reviews Bad.mp4
[download]   0.4% of 195.97MiB at 544.11KiB/s ETA 06:07[download] Got server HTTP error: Downloaded 882004 bytes, expected 205491244 bytes. Retrying (attempt 2 of 10)...


ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 320, in download
    retry(err)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 225, in retry
    raise RetryDownload(e)
RetryDownload
```

### Description of your *issue*, suggested solution and other information

This has been a long-standing issue, getting more frequent recently. I can't figure out a pattern to which videos are affected, but if a video _is_ affected, then deleting the .part and re-attempting will not fix it. However, retrying without the "-f best" option often resolves the issue.

**Comment by dstftw** [comment]
Server side youtube failure.
