### ISSUE TITLE
Error with bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio 

### ISSUE THREAD

**Issue by malaterre** [rg3/youtube-dl#19181]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' https://youtu.be/5IpYOF4Hi6Q
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio', 'https://youtu.be/5IpYOF4Hi6Q']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 3.5.3 (CPython) - Linux-4.18.0-0.bpo.1-amd64-x86_64-with-debian-9.6
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 5IpYOF4Hi6Q: Downloading webpage
[youtube] 5IpYOF4Hi6Q: Downloading video info webpage
[youtube] {18} signature length 44.41, html5 player vflYv1bWD
[youtube] {36} signature length 44.41, html5 player vflYv1bWD
[youtube] {17} signature length 44.41, html5 player vflYv1bWD
[youtube] {137} signature length 44.41, html5 player vflYv1bWD
[youtube] {248} signature length 44.41, html5 player vflYv1bWD
[youtube] {136} signature length 44.41, html5 player vflYv1bWD
[youtube] {247} signature length 44.39, html5 player vflYv1bWD
[youtube] 5IpYOF4Hi6Q: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vflYv1bWD/en_US/base.js
[youtube] {398} signature length 44.41, html5 player vflYv1bWD
[youtube] {135} signature length 44.41, html5 player vflYv1bWD
[youtube] {244} signature length 44.41, html5 player vflYv1bWD
[youtube] {397} signature length 44.41, html5 player vflYv1bWD
[youtube] {134} signature length 44.41, html5 player vflYv1bWD
[youtube] {243} signature length 44.41, html5 player vflYv1bWD
[youtube] {396} signature length 44.41, html5 player vflYv1bWD
[youtube] {133} signature length 44.41, html5 player vflYv1bWD
[youtube] {242} signature length 44.41, html5 player vflYv1bWD
[youtube] {395} signature length 44.41, html5 player vflYv1bWD
[youtube] {160} signature length 44.41, html5 player vflYv1bWD
[youtube] {278} signature length 44.41, html5 player vflYv1bWD
[youtube] {394} signature length 44.41, html5 player vflYv1bWD
[youtube] {140} signature length 44.41, html5 player vflYv1bWD
[youtube] {171} signature length 44.41, html5 player vflYv1bWD
[youtube] {249} signature length 44.41, html5 player vflYv1bWD
[youtube] {250} signature length 44.41, html5 player vflYv1bWD
[youtube] {251} signature length 44.41, html5 player vflYv1bWD
[debug] Invoking downloader on 'https://r11---sn-4gxx-25ge7.googlevideo.com/videoplayback?itag=398&ms=au%2Conr&initcwndbps=517500&mv=m&dur=229.028&mt=1549732573&id=o-AJYAPaCr0XZfsTIGN609cYyaqXKQXUMPVWnapae4T25n&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&pl=39&mn=sn-4gxx-25ge7%2Csn-h5q7knel&ip=2a01%3Ae34%3Aee1e%3A860%3A6f23%3A82e6%3Aaa2d%3Abbd1&mm=31%2C26&txp=5511222&ei=MQtfXOiNBYmUV-vdhugP&key=yt6&c=WEB&ipbits=0&pcm2cms=yes&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&clen=3343862&nh=EAE%2C&lmt=1540741849966584&expire=1549754257&keepalive=yes&fvip=4&gir=yes&mime=video%2Fmp4&requiressl=yes&signature=AC1C82BC491833CF6D68C64AF2E0FE79489955D0.9CBBB4D3A56B26F92EDAA17D9E8F2EFA63451BEF&ratebypass=yes'
[download] Destination: pink floyd - another brick in the wall-5IpYOF4Hi6Q.f398.mp4
[download] 100% of 3.19MiB in 00:07
[debug] Invoking downloader on 'https://r11---sn-4gxx-25ge7.googlevideo.com/videoplayback?itag=140&ms=au%2Conr&initcwndbps=517500&mv=m&dur=229.088&mt=1549732573&id=o-AJYAPaCr0XZfsTIGN609cYyaqXKQXUMPVWnapae4T25n&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&pl=39&mn=sn-4gxx-25ge7%2Csn-h5q7knel&ip=2a01%3Ae34%3Aee1e%3A860%3A6f23%3A82e6%3Aaa2d%3Abbd1&mm=31%2C26&txp=5533432&ei=MQtfXOiNBYmUV-vdhugP&key=yt6&c=WEB&ipbits=0&pcm2cms=yes&source=youtube&clen=3639158&nh=EAE%2C&lmt=1540739772838777&expire=1549754257&keepalive=yes&fvip=4&gir=yes&mime=audio%2Fmp4&requiressl=yes&signature=A75AEE07F24E9D833862D6B989C028E42D1D193C.E39600421F2D99D0ABC25048DD39F5023229CAF3&ratebypass=yes'
[download] Destination: pink floyd - another brick in the wall-5IpYOF4Hi6Q.f140.m4a
[download] 100% of 3.47MiB in 00:02
[ffmpeg] Merging formats into "pink floyd - another brick in the wall-5IpYOF4Hi6Q.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:pink floyd - another brick in the wall-5IpYOF4Hi6Q.f398.mp4' -i 'file:pink floyd - another brick in the wall-5IpYOF4Hi6Q.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:pink floyd - another brick in the wall-5IpYOF4Hi6Q.temp.mp4'
ERROR:     Last message repeated 1 times
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2048, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/lib/python3/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 491, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/lib/python3/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 217, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:     Last message repeated 1 times
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
Outdated ffmpeg.
