### ISSUE TITLE
Downloading from Crunchyroll, has it ever been pointed as "piracy"?

### ISSUE THREAD

**Issue by improviseadaptovercome** [rg3/youtube-dl#19189]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [x] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Just curious if it had been pointed at, as some act of piracy.

Possible scenarios:
*Downloading free content via extractor (in this case, quality is limited to SD and ads show up throughout, however youtube-dl seems to bypass both even without login, provides download options up to 1920*1080)
*Downloading premium content via extractor, logged in (in this case, site provides VFV service only for the offline mode)
I would like to ask if usage of youtube-dl *anyhow* violates the ToS of it, or considered *piracy*. I know of the "no violation of ToS for extractors" rule, as I have read the link a few lines above, however I am curious about it because unlike most of the extractors out there this one is maybe the longest and uses the most sophisticated way, even that it stream captures. On its way it deals with a LOT of crypto files.

I *may* have mistakes taken (I probably have a lot), feel free to correct them.

**Comment by dstftw** [comment]
Address this question to crunchyroll.
