### ISSUE TITLE
Access to direct URL denied

### ISSUE THREAD

**Issue by EddieEJ** [rg3/youtube-dl#19187]
When calling `getInfo` and obtaining all the links from formats, on some videos(not all) I do not have access to the direct video link. When trying to load the link into my browser, I simply get:
![image](https://user-images.githubusercontent.com/25306489/52528648-56f70500-2cdb-11e9-8dbc-c10b3f55346f.png)

Has anyone encountered this issue and know how it can be fixed?

**Comment by remitamine** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser

**Comment by EddieEJ** [comment]
@remitamine I have been using YouTube-dl in my application to obtain direct URLs of YouTube videos and allow users to view them in custom players (without downloading). 

However, if the request is not made with the same IP address and cookies, and it is done automatically by Firebase Cloud Functions, what would be a workaround for this? How can I still generate a working URL and provide it to my user upon their custom request?  

P.S. Do the URLs generated from `getInfo` have an expiration time? Are they going to work after a few days, months, etc ?

Any help would be appreciated!

**Comment by remitamine** [comment]
The server controls the requests that it can accept or refuse.

**Comment by EddieEJ** [comment]
So there is no way to send a request from Firebase Cloud Functions an URL specifically for that user and his machine/ip in order for the link to work for that user even though he does not have YouTube-DL?

**Comment by remitamine** [comment]
i'm not familiar with Firebase Cloud Functions and you're refering to `getInfo` function/method which is not part of the youtube-dl code.
i can't say there is no way to workaround it as it depend on the website you're trying to download from, what i can say is that it's not a problem in youtube-dl.
