### ISSUE TITLE
Add ultimatecourses.com extractor

### ISSUE THREAD

**Issue by matchatype** [rg3/youtube-dl#19188]
Site support request: https://ultimatecourses.com

* Single video: https://platform.ultimatecourses.com/courses/typescript-basics/lectures/4066220
* Entire Course: https://platform.ultimatecourses.com/courses/enrolled/209404

**Comment by dstftw** [comment]
Should be handled be generic extractor.

**Comment by matchatype** [comment]
This is not the case apparently. Providing the `--force-generic-extractor` flag doesn't change the outcome:
```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.08
[debug] Python version 3.7.2 (CPython) - Darwin-18.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 209404: Requesting header
[redirect] Following redirect to https://platform.ultimatecourses.com/p/typescript-basics
[generic] typescript-basics: Requesting header
WARNING: Forcing on generic information extractor.
[generic] typescript-basics: Downloading webpage
[generic] typescript-basics: Extracting information
[TeachableCourse] Downloading platform.ultimatecourses.com login page
[TeachableCourse] Logging in to platform.ultimatecourses.com
[TeachableCourse] typescript-basics: Downloading webpage
[download] Downloading playlist: TypeScript Basics
[TeachableCourse] playlist TypeScript Basics: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: TypeScript Basics
```

**Comment by dstftw** [comment]
You did not provide account credentials.

**Comment by matchatype** [comment]
This is the command I'm running:
```
youtube-dl -u 'xxx@xxx.xxx' -p 'xxxxxxxxxxxxxx' -o '~/UltimateCourses/%(title)s.%(ext)s' https://platform.ultimatecourses.com/courses/209404 --force-generic-extractor
```
Is that wrong?

**Comment by dstftw** [comment]
Log above does not contain this info, do not remove anything from it. In any case for any further investigations you must provide account credentials.

**Comment by matchatype** [comment]
You can create an account following [this link](https://sso.teachable.com/secure/76683/users/sign_up?flow_school_id=76683).

**Comment by dstftw** [comment]
Account must have access to the course.

**Comment by matchatype** [comment]
That would invalidate license agreement. Thanks.
