### ISSUE TITLE
Subtitles are not converted when skipping download

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#19192]
Subtitles are not converted to `.srt` when skipping download. If you remove `--skip-download` the subtitle file is converted. This should be fixed so that the subtitle file is always converted.

```
$ youtube-dl --verbose --write-sub --all-subs --convert-subtitles srt --skip-download https://www.youtube.com/watch?v=xXPSMzHHwOI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--write-sub', u'--all-subs', u'--convert-subtitles', u'srt', u'--skip-download', u'https://www.youtube.com/watch?v=xXPSMzHHwOI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf8, pref UTF-8
[debug] youtube-dl version 2019.02.08
[debug] Python version 2.7.15 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] xXPSMzHHwOI: Downloading webpage
[youtube] xXPSMzHHwOI: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Top 10 Best Switch Games of 2018 _ whatoplay-xXPSMzHHwOI.en.vtt

```
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [X] Bug report (encountered problems with youtube-dl)
```

**Comment by forthrin** [comment]
@dstftw: Duplicate of which issue?

(I couldn't find anything similar when skimming existing reports.)

PS! Could you change your configuration so that the issue number of the other report is automatically printed in a report when setting the report as a duplicate?

**Comment by exzhawk** [comment]
@dstftw Duplicate of #9073 and possible solution #9738

**Comment by Reinbowsaur** [comment]
Why is this still a problem.
