### ISSUE TITLE
Single quotes not working in windows

### ISSUE THREAD

**Issue by GammaPaladin** [rg3/youtube-dl#19218]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v -F "https://www.youtube.com/watch?v=8dxvRYO4FQY"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=8dxvRYO4FQY']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.02.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 8dxvRYO4FQY: Downloading webpage
[youtube] 8dxvRYO4FQY: Downloading video info webpage
[info] Available formats for 8dxvRYO4FQY:
format code  extension  resolution note
249          webm       audio only DASH audio   69k , opus @ 50k, 28.56MiB
250          webm       audio only DASH audio   87k , opus @ 70k, 37.67MiB
140          m4a        audio only DASH audio  134k , m4a_dash container, mp4a.40.2@128k, 70.56MiB
171          webm       audio only DASH audio  142k , vorbis@128k, 67.79MiB
251          webm       audio only DASH audio  160k , opus @160k, 73.99MiB
278          webm       256x144    144p  109k , webm container, vp9, 30fps, video only, 49.13MiB
160          mp4        256x144    144p  117k , avc1.4d400c, 30fps, video only, 53.29MiB
242          webm       426x240    240p  248k , vp9, 30fps, video only, 109.77MiB
133          mp4        426x240    240p  263k , avc1.4d4015, 30fps, video only, 114.87MiB
243          webm       640x360    360p  563k , vp9, 30fps, video only, 206.06MiB
134          mp4        640x360    360p  671k , avc1.4d401e, 30fps, video only, 299.72MiB
244          webm       854x480    480p 1006k , vp9, 30fps, video only, 374.09MiB
135          mp4        854x480    480p 1239k , avc1.4d401f, 30fps, video only, 563.68MiB
247          webm       1280x720   720p 2344k , vp9, 30fps, video only, 768.49MiB
136          mp4        1280x720   720p 2449k , avc1.4d401f, 30fps, video only, 1.09GiB
137          mp4        1920x1080  1080p 4558k , avc1.640028, 30fps, video only, 2.05GiB
248          webm       1920x1080  1080p 4908k , vp9, 30fps, video only, 1.38GiB
17           3gp        176x144    small   80k , mp4v.20.3, mp4a.40.2@ 24k (22050Hz), 44.13MiB
36           3gp        320x180    small  229k , mp4v.20.3, mp4a.40.2 (22050Hz), 125.05MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 479.57MiB
18           mp4        640x360    medium  727k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 396.52MiB
22           mp4        1280x720   hd720 2178k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)

youtube-dl -v -f 'bestvideo' "https://www.youtube.com/watch?v=8dxvRYO4FQY"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', "'bestvideo'", 'https://www.youtube.com/watch?v=8dxvRYO4FQY']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.02.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 8dxvRYO4FQY: Downloading webpage
[youtube] 8dxvRYO4FQY: Downloading video info webpage
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\YoutubeDL.py", line 805, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\YoutubeDL.py", line 859, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\YoutubeDL.py", line 1632, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

As you can see, when used from the windows command line, using single quotes around the format specification does not work. When I switched to using double quotes, it worked again. I was using single quotes as that's what was shown in the usage examples in the documentation. If this is a Windows issue that can't easily be solved, that should probably be noted in the documentation. so people know to use double quotes instead.

Additionally, on a separate note, while the documentation says that bestvideo+bestaudio/best is the default, I've noted that if I don't manually force -f "bestvideo+bestaudio" it defaults to the best single file rather than a merge of the actual best streams (Generally getting the 720p stream rather than the separate 1080p video stream and audio and muxing)

**Comment by dstftw** [comment]
Windows command line does not support single quotes. It's mentioned in FAQ.
>documentation says that bestvideo+bestaudio/best is the default, I've noted that if I don't manually force -f "bestvideo+bestaudio" it defaults to the best single file rather than a merge of the actual best streams

Bother to read the rest of this paragraph in FAQ.
