### ISSUE TITLE
[Error] No duration when downloading from periscope

### ISSUE THREAD

**Issue by NewCTwo** [rg3/youtube-dl#19220]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

So my issue is pretty simple: The duration tag returns NA when I try to download a periscope stream.

Output:

    me@me:~$ youtube-dl -v -s -i --get-filename -o '%(title)s_%(resolution)s_%(duration)s.%(ext)s'  https://www.pscp.tv/w/1rmxPQmPmVbKN?q=boxing
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: [u'-v', u'-s', u'-i', u'--get-filename', u'-o', u'%(title)s_%(resolution)s_%(duration)s.%(ext)s', u'https://www.pscp.tv/w/1rmxPQmPmVbKN?q=boxing']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2019.02.08
    [debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
    [debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
    [debug] Proxy map: {}
    [debug] Default format spec: bestvideo+bestaudio/best
    Brian P. Hickey - Grays Ferry Boxing Club_NA_NA.mp4

**Comment by dstftw** [comment]
No duration is provided as metadata.

**Comment by NewCTwo** [comment]
How do I get that metadata into the output?

**Comment by dstftw** [comment]
You can't. I've already pointed out it does not exist.

**Comment by NewCTwo** [comment]
It exists on the website:
![screenshot1](https://user-images.githubusercontent.com/46302522/52744566-0b7a7a80-2fab-11e9-8788-f8cd4287ae1a.png)

**Comment by NewCTwo** [comment]
Is this a new feature request?

**Comment by dstftw** [comment]
So what? Again: it's not provided as metadata. Download the video and extract duration with ffmpeg.
