### ISSUE TITLE
bilibili.com ERROR: BiliBili said: Invalid appkey parameter.

### ISSUE THREAD

**Issue by someziggyman** [rg3/youtube-dl#19233]
For some reason BiliBili.com download fails. 

Youtube-dl says - ERROR: BiliBili said: Invalid appkey parameter.

Here's a verbose log:

youtube-dl -v https://www.bilibili.com/video/av41540229/?spm_id_from=333.788.videocard.6
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.bilibili.com/video/av41540229/?spm_id_from=333.788.videocard.6']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.08
[debug] Python version 2.7.10 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[BiliBili] 41540229: Downloading webpage
[BiliBili] 41540229: Downloading video info page
[BiliBili] 41540229: Downloading video info page
ERROR: BiliBili said: Invalid appkey parameter.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bilibili.py", line 165, in _real_extract
    self._report_error(video_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bilibili.py", line 101, in _report_error
    raise ExtractorError('%s said: %s' % (self.IE_NAME, result['message']), expected=True)
ExtractorError: BiliBili said: Invalid appkey parameter.

**Comment by sudrizzz** [comment]
I reproduce this bug
---------------------------
```
PS C:\Windows\system32> youtube-dl -F https://www.bilibili.com/video/av36895433
[BiliBili] 36895433: Downloading webpage
[BiliBili] 36895433: Downloading video info page
[BiliBili] 36895433: Downloading video info page
ERROR: BiliBili said: Invalid appkey parameter.
```

**Comment by WolfNiu** [comment]
same here

**Comment by SonNguyen240295** [comment]
same
