### ISSUE TITLE
yt-dl does not create a download archive, when simulating

### ISSUE THREAD

**Issue by pyptq** [rg3/youtube-dl#19239]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [x] Read thoroughly the [README](https://github.com/rg3/youtube-dl/blob/master/README.md) including the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Other
---
To reproduce this issue:
1. `youtube-dl --download-archive ./pyptq/download-archive.txt -i -o "./pyptq/%(uploader)s/%(upload_date)s-%(id)s.%(ext)s" -f bestvideo+bestaudio https://www.youtube.com/user/sciencium/videos` (channel has 6 videos)
2. `rm ./pyptq/download-archive.txt`
3. `rm ./pyptq/Sciencium/20170216-IbpiovW507M.mp4`
4. `youtube-dl --download-archive ./pyptq/download-archive.txt -i -o "./pyptq/%(uploader)s/%(upload_date)s-%(id)s.%(ext)s" https://www.youtube.com/user/sciencium/videos --skip-download` (or any other simulation option)
The simulation honors, if there is a download archive, but it never adds to it.
 - Expected result: the second youtube-dl command creates a new download archive, with downloaded videos inside it
 - Current result: no file created

**Comment by dstftw** [comment]
This is expected behavior.

**Comment by pyptq** [comment]
Do I need to create a feature request?
I need to generate a download archive (without downloading any new videos).
How would this expected behavior, `--skip-downoad` (just doesn't download videos) is not `-s` (doesn't touch the disk)?
