### ISSUE TITLE
 I can't download this video

### ISSUE THREAD

**Issue by sdtqwe4ty** [rg3/youtube-dl#19236]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: [u'--no-mtime', u'-o', u'/home/josh/queue/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-o', u'/home/josh/best hits backup/%(title)s.%(ext)s', u'https://www.youtube.com/watch?v=qHI16SXjiZY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.08
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[youtube] qHI16SXjiZY: Downloading webpage
[youtube] qHI16SXjiZY: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r1---sn-vgqsrnll.googlevideo.com/videoplayback?txp=5431432&keepalive=yes&requiressl=yes&ipbits=0&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&fvip=3&ms=au%2Conr&source=youtube&mv=m&ip=71.194.164.33&key=yt6&lmt=1550227398631048&id=o-AP8SldgY78dRIOJ6OFKr4LfUjG827nDqxYzeEhn9BO6N&dur=99.040&expire=1550279677&mn=sn-vgqsrnll%2Csn-ab5l6nsy&gir=yes&itag=248&clen=10180830&ei=nQ9nXIXGM5aaiwS0gZPYDg&mt=1550257967&pl=16&mm=31%2C26&c=WEB&initcwndbps=1835000&mime=video%2Fwebm&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&signature=132460EA51FF6C6DE8D7EA9EED892221EB7D0176.163608AEC47B62726A5CF1CA1C3DEF413BEA06E8&ratebypass=yes'
ERROR: unable to open for writing: [Errno 36] File name too long: '/home/josh/best hits backup/\xe3\x81\x8b\xe3\x81\x90\xe3\x82\x84\xe7\x89\xb9\xe9\x9b\x86 1_6\xe3\x80\x90\xe4\xb8\xad\xe5\x9b\xbd\xe4\xba\xba\xe3\x81\x8c\xe6\x97\xa5\xe6\x9c\xac\xe3\x81\xae\xe6\x9b\xb2\xe3\x81\xa7\xe8\xb8\x8a\xe3\x81\xa3\xe3\x81\xa6\xe3\x81\xbf\xe3\x81\x9f\xe3\x80\x91\xe3\x83\x81\xe3\x82\xab\xe3\x81\xa3\xe3\x81\xa8\xe3\x83\x81\xe3\x82\xab\xe5\x8d\x83\xe8\x8a\xb1\xe3\x81\xa3\xe2\x99\xa1\xe3\x80\x90\xe5\x92\xac\xe4\xba\xba\xe7\x8c\xab\xe3\x80\x91\xe3\x80\x90\xe3\x81\x8b\xe3\x81\x90\xe3\x82\x84\xe6\xa7\x98\xe3\x81\xaf\xe5\x91\x8a\xe3\x82\x89\xe3\x81\x9b\xe3\x81\x9f\xe3\x81\x84\xe3\x80\x91.f248.webm.part'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 250, in download
    ctx.tmpfilename, ctx.open_mode)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 458, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
IOError: [Errno 36] File name too long: '/home/josh/best hits backup/\xe3\x81\x8b\xe3\x81\x90\xe3\x82\x84\xe7\x89\xb9\xe9\x9b\x86 1_6\xe3\x80\x90\xe4\xb8\xad\xe5\x9b\xbd\xe4\xba\xba\xe3\x81\x8c\xe6\x97\xa5\xe6\x9c\xac\xe3\x81\xae\xe6\x9b\xb2\xe3\x81\xa7\xe8\xb8\x8a\xe3\x81\xa3\xe3\x81\xa6\xe3\x81\xbf\xe3\x81\x9f\xe3\x80\x91\xe3\x83\x81\xe3\x82\xab\xe3\x81\xa3\xe3\x81\xa8\xe3\x83\x81\xe3\x82\xab\xe5\x8d\x83\xe8\x8a\xb1\xe3\x81\xa3\xe2\x99\xa1\xe3\x80\x90\xe5\x92\xac\xe4\xba\xba\xe7\x8c\xab\xe3\x80\x91\xe3\x80\x90\xe3\x81\x8b\xe3\x81\x90\xe3\x82\x84\xe6\xa7\x98\xe3\x81\xaf\xe5\x91\x8a\xe3\x82\x89\xe3\x81\x9b\xe3\x81\x9f\xe3\x81\x84\xe3\x80\x91.f248.webm.part'

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I can't download this video
https://www.youtube.com/watch?v=qHI16SXjiZY  is says the file name is too long.

**Comment by dstftw** [comment]
Limit `title` length in output template.
