### ISSUE TITLE
WQED (PBS station) supported?

### ISSUE THREAD

**Issue by dare2** [rg3/youtube-dl#19237]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

C:\files>youtube-dl -F https://watch.wqed.org/video/wqed-pittsburgh-mon-al-o/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://watch.wqed.org/video/wqed-pittsburgh-mon-al-o/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.02.08
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81707-g11777eb, ffprobe N-81707-g11777eb, rtmpdump 2.4
[debug] Proxy map: {}
[generic] wqed-pittsburgh-mon-al-o: Requesting header
WARNING: Falling back on generic information extractor.
[generic] wqed-pittsburgh-mon-al-o: Downloading webpage
[generic] wqed-pittsburgh-mon-al-o: Extracting information
ERROR: Unsupported URL: https://watch.wqed.org/video/wqed-pittsburgh-mon-al-o/Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://watch.wqed.org/video/wqed-pittsburgh-mon-al-o/

---

### Description of your *issue*, suggested solution and other information

WQED is listed as one of the supported sites within the PBS realm but as you can see above it appears to be acting like an unsupported URL.

**Comment by dare2** [comment]
Should this be changed to a site support request?

**Comment by dare2** [comment]
I was hoping this would have been a simple fix, but from the lack of response, I presume not. This is the only reference to WQED I could find, other than it being listed as one of the PBS supported sites:

https://github.com/rg3/youtube-dl/blob/6f2d82a5a0fd020ac36bdfe4faa0ee8a9f4945ac/youtube_dl/extractor/pbs.py

**Comment by godane** [comment]
@dare2 
You can grab it from here: https://www.pbs.org/video/wqed-pittsburgh-mon-al-o/

With pbs stuff it should be hoped on www.pbs.org so you grab it from that domain instead of watch.wqed.org domain.

**Comment by dare2** [comment]
Thank you so much. I never would have thought to try that, since that video is a locally-produced production and I didn't expect it to be accessible on the pbs domain.
