### ISSUE TITLE
How can I avoid adding the video description to the output file?

### ISSUE THREAD

**Issue by Kerndog73** [rg3/youtube-dl#19247]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When I use the tool to download a YouTube video, the artist, track and date are added to the mp3. This is great but the video description is also added to the comments section of the mp3. I can see how this feature could be useful but I personally don’t really like it. Maybe I’m just being picky! I’d like a way to avoid embedding the description in the output file using both the command-line tool and the Python library (if it can be done of course).

**Comment by dstftw** [comment]
Not possible.

**Comment by Kerndog73** [comment]
@dstftw How about removing the description using ffmpeg somehow?

**Comment by dstftw** [comment]
Go for it.
