### ISSUE TITLE
Cannot get youtube-dl to do anything

### ISSUE THREAD

**Issue by astatine** [rg3/youtube-dl#19252]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Issue Description
I am trying to run yt-dl on a fresh Windows 10 install. I cannot get it to do *anything*; there's no output at all from the tool.

![ytdl_issue](https://user-images.githubusercontent.com/1077402/52912812-c45af500-32dc-11e9-9efe-b5ee88d3bc5a.jpg)

I am learning Windows Sysadmin and was playing around with `Get-ExecutionPolicy` and `Set-ExecutionPolicy`. I don't remember what I changed (from which defaults), but maybe that has something to do with it. The current values are as follows:
```
PS C:\Apps\yt-dl> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine       AllSigned
```
Thanks in advance!

**Comment by dstftw** [comment]
```
PS C:\Dev\youtube-dl\master> .\youtube-dl.exe --help
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

Options:
  General Options:
    -h, --help                       Print this help text and exit
    --version                        Print program version and exit
    -U, --update                     Update this program to latest version. Make sure that you have sufficient permissions (run with sudo if needed)
...
<cut>
PS C:\Dev\youtube-dl\master> .\youtube-dl.exe --version
2019.02.08
```

**Comment by astatine** [comment]
I was able to solve my issue and am posting here in case it helps someone else.

Running `youtube-dl.exe` in PS quit the tool silently without errors, as shown in OP. Running it in `cmd` gave me the missing msvcr100.dll error. I then installed  `Microsoft Visual C++ 2010 Redistributable Package (x86)` and all was fine.

**Comment by BUAWF** [comment]
Try running it in Command Prompt.
