### ISSUE TITLE
Http 503; bestvideo not available

### ISSUE THREAD

**Issue by Zachary24** [rg3/youtube-dl#19251]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.02.08
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---
### Description of your *issue*, suggested solution and other information

After several hours of reading one word answers to issues i'm still confused for 50% of the videos I'm trying to download I get ([download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10)...), the general answer is that the format is not avaible on youtubes side, however my selection is set to bestvideo+bestaudio/137/248/22/136/247/best, it will download the audio and thumbnail just fine, and if i rerun youtube-dl with only that video it downloads it just fine, no errors, one example would be (https://www.youtube.com/watch?v=Y6HygXMQbmw) the output of -F is 
249          webm       audio only DASH audio   59k , opus @ 50k, 5.62MiB
250          webm       audio only DASH audio   78k , opus @ 70k, 7.38MiB
140          m4a        audio only DASH audio  131k , m4a_dash container, mp4a.40.2@128k, 13.74MiB
171          webm       audio only DASH audio  135k , vorbis@128k, 13.20MiB
251          webm       audio only DASH audio  149k , opus @160k, 14.45MiB
278          webm       180x144    144p   73k , webm container, vp9, 30fps, video only, 7.09MiB
160          mp4        180x144    144p   82k , avc1.4d400c, 30fps, video only, 4.77MiB
242          webm       300x240    240p  160k , vp9, 30fps, video only, 14.42MiB
133          mp4        300x240    240p  177k , avc1.4d400d, 30fps, video only, 9.07MiB
243          webm       450x360    360p  290k , vp9, 30fps, video only, 26.77MiB
134          mp4        450x360    360p  449k , avc1.4d4016, 30fps, video only, 20.55MiB
244          webm       600x480    480p  538k , vp9, 30fps, video only, 48.31MiB
135          mp4        600x480    480p  808k , avc1.4d401e, 30fps, video only, 42.04MiB
17           3gp        176x144    small   79k , mp4v.20.3, mp4a.40.2@ 24k (22050Hz), 8.44MiB
36           3gp        300x240    small  216k , mp4v.20.3, mp4a.40.2 (22050Hz), 23.02MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 80.75MiB
18           mp4        450x360    medium  416k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 44.15MiB (best)

so it should download best right? there are also some videos that have multiple formats (136/247 etc) that show as available..

**Comment by Zachary24** [comment]
may I ask how this is incomplete?

**Comment by dstftw** [comment]
Bother to read new issue template.
