### ISSUE TITLE
list-thumbnails missing higher quality with YouTube

### ISSUE THREAD

**Issue by cup** [rg3/youtube-dl#19255]
I recently discovered from a comment that some additional formats are
available:

https://stackoverflow.com/posts/comments/96012406

This is quite helpful, as with this example:

~~~
$ youtube-dl --list-thumbnails 2Lpw3yMCWro
[youtube] 2Lpw3yMCWro: Downloading webpage
[youtube] 2Lpw3yMCWro: Downloading video info webpage
[info] Thumbnails for 2Lpw3yMCWro:
ID  width    height  URL
0   unknown  unknown https://i.ytimg.com/vi/2Lpw3yMCWro/hqdefault.jpg
~~~

it seems the only option is **hqdefault** (480 x 360), which at first seems
true. If you try the next one up **sddefault** (640 x 480), it fails as
expected:

~~~
$ curl -I https://i.ytimg.com/vi/2Lpw3yMCWro/sddefault.jpg
HTTP/2 404
~~~

However **sd3** is successful:

~~~
$ curl -I https://i.ytimg.com/vi/2Lpw3yMCWro/sd3.jpg
HTTP/2 200
~~~

so as can be seen in some cases YouTube-DL is not advertising the highest
quality available.

**Comment by dstftw** [comment]
youtube-dl does not use Youtube API.

**Comment by cup** [comment]
@dstftw your comment doesnt really have anything to do with this issue, because as far as i know the **sd3** links arent available via the API either

**Comment by dstftw** [comment]
Stackoverflow URL you've linked suggests using Youtube API for obtaining list of available URLs.
Thus your comment is either have nothing to do with the issue without a clean, non redundant and acceptable way to obtain available thumbnails' formats without the need of testing on each manually crafted thumbnail URL which I obviously won't accept for youtube.

**Comment by cup** [comment]
@dstftw you can use whatever rationalization you like for ignoring this issue.

however the simple fact is that YouTube-DL no longer gets the best available
thumbnail in all cases.

if nothing else this issue serves as a notice of that fact.
