### ISSUE TITLE
Stuck @ "Downloading webpage"

### ISSUE THREAD

**Issue by kazoooka** [rg3/youtube-dl#19269]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones (it only shows all the posts that are there on default...)
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

LOG:

 sudo ./youtube-dl https://www.youtube.com/watch?v=fdixQDPA2h0 -v
[debug] System config: [u'--force-ipv4', u'--no-check-certificate']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=fdixQDPA2h0', u'-v']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2019.02.18
[debug] Python version 2.7.9 (CPython) - Linux-4.15.18-11-pve-x86_64-with-debian-8.11
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] fdixQDPA2h0: Downloading webpage
^C
ERROR: Interrupted by user

---

### Description of your *issue*, suggested solution and other information

I use the youtube-dl command as specified up there but it doesn't download anything and is stuck there for as long as i would cancel. I already tried to ping www.youtube.com and get 
sudo ping www.youtube.com
PING youtube-ui.l.google.com (172.217.19.238) 56(84) bytes of data.
64 bytes from par21s11-in-f14.1e100.net (172.217.19.238): icmp_seq=1 ttl=51 time=12.5 ms
64 bytes from par21s11-in-f14.1e100.net (172.217.19.238): icmp_seq=2 ttl=51 time=12.5 ms
64 bytes from par21s11-in-f14.1e100.net (172.217.19.238): icmp_seq=3 ttl=51 time=12.5 ms
64 bytes from par21s11-in-f14.1e100.net (172.217.19.238): icmp_seq=4 ttl=51 time=12.4 ms

Also the server is super fast which means it should download the track instantly. It worked a while ago but not anymore... 

What's going on? I didn't change anything on my system except updating youtube-dl

**Comment by dstftw** [comment]
Run under strace to figure out the reason.

**Comment by kazoooka** [comment]
I got this now: 

sinusbot@server348:/opt/sinusbot$ curl yt-dl.org/ip
[showed my ip here but i dont wanna show it]
sinusbot@server348:/opt/sinusbot$ ./youtube-dl -v hHUbLv4ThOo
[debug] System config: [u'--force-ipv4', u'--no-check-certificate']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'hHUbLv4ThOo']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2019.03.01
[debug] Python version 2.7.9 (CPython) - Linux-4.15.18-11-pve-x86_64-with-debian-8.11
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] hHUbLv4ThOo: Downloading webpage
[youtube] hHUbLv4ThOo: Downloading video info webpage
ERROR: The uploader has not made this video available in your country.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1978, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: The uploader has not made this video available in your country.


And that error is happening with every video on youtube.... 

With strace i got lots of output from which only the last probably is relevant...

**Comment by kazoooka** [comment]
00:17:36.446375 ioctl(2, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
00:17:36.446542 write(2, "\33[0;31mERROR:\33[0m The uploader h"..., 82ERROR: The uploader has not made this video available in your country.
) = 82
00:17:36.446757 rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f0832b13890}, {0x558d40, [], SA_RESTORER, 0x7f0832b13890}, 8) = 0
00:17:36.459412 close(4)                = 0
00:17:36.459575 exit_group(1)           = ?
00:17:36.461503 +++ exited with 1 +++

**Comment by LeeiFrankJaw** [comment]
I got this problem too today.  I can view the youtube page on browser and can use `curl` to download the page.  But `youtube-dl` simply won't download the webpage.  After I left the place and switched to another network environment, `youtube-dl` works again. (I was on laptop).

I mean it should not be the case that both firefox and `curl` can download the page while `youtube-dl` can't.

**Comment by LeeiFrankJaw** [comment]
Anyway, I found out what my problem was.  I tried `wget` and it cannot download the webpage neither.  However, it printed out the resolved IP address of YouTube website and it was an IPv6 address, which was not suitable for my case.  I tried `youtube -v` but its output was not that helpful in this specific case.

Then I tried `youtube-dl -4` and it resolved my downloading problem.
