### ISSUE TITLE
Creation Date / upload Date which Parameter

### ISSUE THREAD

**Issue by 56ZsV7f** [rg3/youtube-dl#19276]
sample: if i take https://www.youtube.com/watch?v=K3LBgmhw7ec, its uploaded 11.02.2019. Which parameter i have to take, for not use the system time (19.02.2019) by PC/Notebook ?
--no-mtime or without --no-mtime has no effect.
Please advise

_Originally posted by @56ZsV7f in https://github.com/rg3/youtube-dl/issues/19274#issuecomment-465310717_

**Comment by dstftw** [comment]
System time is not used by default. I've already pointed out how it works.
