### ISSUE TITLE
Creation Date / upload Date maybe wrong by version 2019-02-18

### ISSUE THREAD

**Issue by 56ZsV7f** [rg3/youtube-dl#19274]
On Version 2019-02-18 doesnt save the Upload Date from youtube. The programm take the system date and time from PC/Notebook. 
Do you have any parameters for setup or is that a issue ?

Thanks

**Comment by dstftw** [comment]
It has never used `upload_date`. It uses Last-Modified HTTP header for single file formats.

**Comment by 56ZsV7f** [comment]
sample: if i take https://www.youtube.com/watch?v=K3LBgmhw7ec, its uploaded 11.02.2019. Which parameter i have to take, for not use the system time by PC/Notebook ?
--no-mtime or without --no-mtime has no effect.
Please advise
