### ISSUE TITLE
how to run youtube-dl in the foreground?

### ISSUE THREAD

**Issue by jiangjiangflies** [rg3/youtube-dl#19309]
It seems youtube-dl creates a PID and then runs in the background. But I want it to run directly in the foreground. Any options to stop it running in the background?

**Comment by dstftw** [comment]
It does not run in background until you tell it to do so.

**Comment by jiangjiangflies** [comment]
This is the output:
```
root@ns500019:~# youtube-dl https://www.youtube.com/embed/ICiZZBlJvRk?rel=0&showinfo=0 
[1] 22951
root@ns500019:~# [youtube] ICiZZBlJvRk: Downloading webpage
[youtube] ICiZZBlJvRk: Downloading video info webpage
[download] Destination: AP Top Stories February 22 P-ICiZZBlJvRk.f135.mp4
[download] 100% of 8.03MiB in 00:00
[download] Destination: AP Top Stories February 22 P-ICiZZBlJvRk.f140.m4a
[download] 100% of 1.03MiB in 00:00
[ffmpeg] Merging formats into "AP Top Stories February 22 P-ICiZZBlJvRk.mp4"
Deleting original file AP Top Stories February 22 P-ICiZZBlJvRk.f135.mp4 (pass -k to keep)
Deleting original file AP Top Stories February 22 P-ICiZZBlJvRk.f140.m4a (pass -k to keep)

```
A PID 22951 is created and I have to press Enter, then it will finish
`[1]+  Done                    youtube-dl https://www.youtube.com/embed/ICiZZBlJvRk?rel=0`

**Comment by dstftw** [comment]
Learn how to use command line first: https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by jiangjiangflies** [comment]
Hmm, ampersand!  You really helped me a lot! Thank you so much!!!
