### ISSUE TITLE
Orf live (real live, not the usual delayed live!)

### ISSUE THREAD

**Issue by avagraha** [rg3/youtube-dl#19310]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.02.18
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

https://github.com/rg3/youtube-dl/issues
C:\Users\alex>youtube-dl -v --geo-bypass-country AT
ive/AD-Nordische-Ski-WM-2019-Langlauf-Herren-30km-Skiathlon/14003505
debug] System config: []
debug] User config: []
debug] Custom config: []
debug] Command-line args: ['-v', '--geo-bypass-country', 'AT', 'https://tv
hek.orf.at/live/AD-Nordische-Ski-WM-2019-Langlauf-Herren-30km-Skiathlon/14
03505']
debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
debug] youtube-dl version 2019.02.18
debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
debug] exe versions: ffmpeg 3.3.4
debug] Proxy map: {}
debug] Using fake IP 84.116.100.192 (AT) as X-Forwarded-For.
orf:tvthek] 14003505: Downloading webpage
orf:tvthek] 14003505: Downloading f4m manifest
RROR: 14003505: Failed to parse XML  (caused by ParseError('syntax error:
ine 1, column 0',)); please report this issue on
https://yt-dl.org/bug
. M
ke sure you are using the latest version; type  youtube-dl -U  to update.
e sure to call youtube-dl with the --verbose flag and include its complete
output.
raceback (most recent call last):
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6
x\build\youtube_dl\extractor\common.py", line 827, in _parse_xml
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6
x\build\youtube_dl\compat.py", line 2513, in compat_etree_fromstring
 File "C:\Python\Python34\lib\xml\etree\ElementTree.py", line 1335, in XML

 File "<string>", line None
ml.etree.ElementTree.ParseError: syntax error: line 1, column 0
raceback (most recent call last):
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6
x\build\youtube_dl\extractor\common.py", line 827, in _parse_xml
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6
x\build\youtube_dl\compat.py", line 2513, in compat_etree_fromstring
 File "C:\Python\Python34\lib\xml\etree\ElementTree.py", line 1335, in XML

 File "<string>", line None
ml.etree.ElementTree.ParseError: syntax error: line 1, column 0

uring handling of the above exception, another exception occurred:

raceback (most recent call last):
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6
x\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6
x\build\youtube_dl\extractor\common.py", line 508, in extract
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6
x\build\youtube_dl\extractor\orf.py", line 94, in _real_extract
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6
x\build\youtube_dl\extractor\common.py", line 1445, in _extract_f4m_format

 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6
x\build\youtube_dl\extractor\common.py", line 820, in _download_xml
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6
x\build\youtube_dl\extractor\common.py", line 804, in _download_xml_handle

 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6
x\build\youtube_dl\extractor\common.py", line 831, in _parse_xml
outube_dl.utils.ExtractorError: 14003505: Failed to parse XML  (caused by
arseError('syntax error: line 1, column 0',)); please report this issue on
https://yt-dl.org/bug
. Make sure you are using the latest version; type
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose fla
 and include its complete output.

If the live will end when you read my report you can try with another (real) orf live

**Comment by dstftw** [comment]
404 not found.

**Comment by avagraha** [comment]
the link works well in my browser:
https://tvthek.orf.at/live/Nordische-Ski-WM-2019-WM-Studio/14003416
https://postimg.cc/hh04PtX6





  ----- Original Message -----

**Comment by avagraha** [comment]
I confirm the link https://tvthek.orf.at/live/Nordische-Ski-WM-2019-WM-Studio/14003416     is still valid and working (geoblocked). Are you able to download it or do you experience the same issue as me? (Log above). Thanks. Notice the differencies real live vs. Reloaded live.
