### ISSUE TITLE
TBS has full eps; DL errors out

### ISSUE THREAD

**Issue by Baylink-gh** [rg3/youtube-dl#1943]
http://www.tbs.com/video/index.jsp?cid=1112876 is a sample URL; here's the complete dump.  

jra@princeton:/appl/media/tv/gf> vget -tc --verbose http://www.tbs.com/video/index.jsp?cid=1112876
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-tc', '--verbose', 'http://www.tbs.com/video/index.jsp?cid=1112876']
[debug] youtube-dl version 2013.07.17.1
[debug] Python version 2.7.2 - Linux-3.1.10-1.16-desktop-i686-with-SuSE-12.1-i586
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
[generic] index.jsp?cid=1112876: Downloading webpage
[generic] index.jsp?cid=1112876: Extracting information
ERROR: Invalid URL: http://www.tbs.com/video/index.jsp?cid=1112876; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/vget/youtube_dl/YoutubeDL.py", line 312, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/vget/youtube_dl/extractor/common.py", line 96, in extract
    return self._real_extract(url)
  File "/usr/local/bin/vget/youtube_dl/extractor/generic.py", line 148, in _real_extract
    raise ExtractorError(u'Invalid URL: %s' % url)
ExtractorError: Invalid URL: http://www.tbs.com/video/index.jsp?cid=1112876; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output.

I hadn't updated recently, so I did, but it didn't help.

I'm assuming this is really "RFE: Add TBS", but the error message was unusual to me.

**Comment by yan12125** [comment]
Superseded by #10222. This video is no longer available.
