### ISSUE TITLE
[daum.net] Add support for playlists (was: Unsupported URL for tvpot.daum.net)

### ISSUE THREAD

**Issue by ksy5662** [rg3/youtube-dl#1952]
Thanks a lot for your support:)

http://m.tvpot.daum.net/clip/ClipView.tv?clipid=54999425
http://m.tvpot.daum.net/mypot/Top.tv?ownerid=45x1okb1If50&playlistid=3569733

(1)
Jay-Yuui-MacBook-Pro:youtube-dl jcyu5662$ ./youtube-dl -s --verbose http://m.tvpot.daum.net/clip/ClipView.tv?clipid=54999425
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-s', '--verbose', 'http://m.tvpot.daum.net/clip/ClipView.tv?clipid=54999425']
[debug] youtube-dl version 2013.12.11.2
[debug] Python version 2.7.5 - Darwin-13.0.0-x86_64-i386-64bit
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
[generic] ClipView.tv?clipid=54999425: Downloading webpage
[generic] ClipView.tv?clipid=54999425: Extracting information
ERROR: Unsupported URL: http://m.tvpot.daum.net/clip/ClipView.tv?clipid=54999425; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 471, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 134, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 254, in _real_extract
    raise ExtractorError(u'Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://m.tvpot.daum.net/clip/ClipView.tv?clipid=54999425; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

(2)

Jay-Yuui-MacBook-Pro:youtube-dl jcyu5662$ ./youtube-dl -s --verbose http://m.tvpot.daum.net/mypot/Top.tv?ownerid=45x1okb1If50&playlistid=3569733
[1] 30832
Jay-Yuui-MacBook-Pro:youtube-dl jcyu5662$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-s', '--verbose', 'http://m.tvpot.daum.net/mypot/Top.tv?ownerid=45x1okb1If50']
[debug] youtube-dl version 2013.12.11.2
[debug] Python version 2.7.5 - Darwin-13.0.0-x86_64-i386-64bit
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
[generic] Top.tv?ownerid=45x1okb1If50: Downloading webpage
[generic] Top.tv?ownerid=45x1okb1If50: Extracting information
ERROR: Unsupported URL: http://m.tvpot.daum.net/mypot/Top.tv?ownerid=45x1okb1If50; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 471, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 134, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 254, in _real_extract
    raise ExtractorError(u'Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://m.tvpot.daum.net/mypot/Top.tv?ownerid=45x1okb1If50; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
Thanks to @ping all URLs mentioned above will be supported in the next version.
