### ISSUE TITLE
WARNING: unable to extract channel id; 

### ISSUE THREAD

**Issue by OgnistyPoland** [rg3/youtube-dl#20020]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```

D:\mpv>youtube-dl.exe -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 https://www.youtube.com/watch?v=Uj1K-2hBlI8 --verbose
[debug] System config: []
[debug] User config: ['--write-sub', '--sub-lang', 'en', '--convert-subs', 'ass', '--embed-sub', '--user-agent', 'Mozilla/5.0 (Linux; Android 7.0; SM-G892A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36', '--ffmpeg-location', 'ffmpeg.exe', '--external-downloader', 'ffmpeg.exe']
[debug] Custom config: []
[debug] Command-line args: ['-f', "'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio'", '--merge-output-format', 'mp4', 'https://www.youtube.com/watch?v=Uj1K-2hBlI8', '--verbose']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2019.02.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-93219-gc679119a73, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] Uj1K-2hBlI8: Downloading webpage
[youtube] Uj1K-2hBlI8: Downloading video info webpage
[youtube] Uj1K-2hBlI8: Downloading embed webpage
WARNING: unable to extract uploader nickname
WARNING: unable to extract channel id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: video doesn't have subtitles
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\YoutubeDL.py", line 805, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\YoutubeDL.py", line 859, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\YoutubeDL.py", line 1632, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available
...
<end of log>
```

### Description of your *issue*, suggested solution and other information
Not working...

**Comment by dstftw** [comment]
Windows command line does not support single quotes.

**Comment by ViperCode7** [comment]
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', '--verbose', '-F', 'https://www.youtube.com/watch?v=0UXLWtooaGA']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-92795-gcdbf8847ea, ffprobe N-92795-gcdbf8847ea
[debug] Proxy map: {}
[youtube] 0UXLWtooaGA: Downloading webpage
[youtube] 0UXLWtooaGA: Downloading video info webpage
[youtube] {18} signature length 44.40, html5 player vflisCO7O
[youtube] {137} signature length 44.40, html5 player vflisCO7O
[youtube] {248} signature length 44.40, html5 player vflisCO7O
[youtube] {136} signature length 44.40, html5 player vflisCO7O
[youtube] {247} signature length 44.40, html5 player vflisCO7O
[youtube] {135} signature length 44.38, html5 player vflisCO7O
[youtube] {244} signature length 44.40, html5 player vflisCO7O
[youtube] {134} signature length 44.40, html5 player vflisCO7O
[youtube] {243} signature length 44.40, html5 player vflisCO7O
[youtube] {133} signature length 44.40, html5 player vflisCO7O
[youtube] {242} signature length 44.40, html5 player vflisCO7O
[youtube] {160} signature length 44.40, html5 player vflisCO7O
[youtube] {278} signature length 44.40, html5 player vflisCO7O
[youtube] {140} signature length 44.40, html5 player vflisCO7O
[youtube] {171} signature length 44.40, html5 player vflisCO7O
[youtube] {249} signature length 44.40, html5 player vflisCO7O
[youtube] {250} signature length 44.40, html5 player vflisCO7O
[youtube] {251} signature length 44.40, html5 player vflisCO7O
WARNING: unable to extract channel id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type
 youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[info] Available formats for 0UXLWtooaGA: ...
```

just a report

**Comment by guitarchord** [comment]
> ```
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--no-check-certificate', '--verbose', '-F', 'https://www.youtube.com/watch?v=0UXLWtooaGA']
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2019.04.30
> [debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
> [debug] exe versions: ffmpeg N-92795-gcdbf8847ea, ffprobe N-92795-gcdbf8847ea
> [debug] Proxy map: {}
> [youtube] 0UXLWtooaGA: Downloading webpage
> [youtube] 0UXLWtooaGA: Downloading video info webpage
> [youtube] {18} signature length 44.40, html5 player vflisCO7O
> [youtube] {137} signature length 44.40, html5 player vflisCO7O
> [youtube] {248} signature length 44.40, html5 player vflisCO7O
> [youtube] {136} signature length 44.40, html5 player vflisCO7O
> [youtube] {247} signature length 44.40, html5 player vflisCO7O
> [youtube] {135} signature length 44.38, html5 player vflisCO7O
> [youtube] {244} signature length 44.40, html5 player vflisCO7O
> [youtube] {134} signature length 44.40, html5 player vflisCO7O
> [youtube] {243} signature length 44.40, html5 player vflisCO7O
> [youtube] {133} signature length 44.40, html5 player vflisCO7O
> [youtube] {242} signature length 44.40, html5 player vflisCO7O
> [youtube] {160} signature length 44.40, html5 player vflisCO7O
> [youtube] {278} signature length 44.40, html5 player vflisCO7O
> [youtube] {140} signature length 44.40, html5 player vflisCO7O
> [youtube] {171} signature length 44.40, html5 player vflisCO7O
> [youtube] {249} signature length 44.40, html5 player vflisCO7O
> [youtube] {250} signature length 44.40, html5 player vflisCO7O
> [youtube] {251} signature length 44.40, html5 player vflisCO7O
> WARNING: unable to extract channel id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type
>  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [info] Available formats for 0UXLWtooaGA: ...
> ```
> 
> just a report



> ```
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--no-check-certificate', '--verbose', '-F', 'https://www.youtube.com/watch?v=0UXLWtooaGA']
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2019.04.30
> [debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
> [debug] exe versions: ffmpeg N-92795-gcdbf8847ea, ffprobe N-92795-gcdbf8847ea
> [debug] Proxy map: {}
> [youtube] 0UXLWtooaGA: Downloading webpage
> [youtube] 0UXLWtooaGA: Downloading video info webpage
> [youtube] {18} signature length 44.40, html5 player vflisCO7O
> [youtube] {137} signature length 44.40, html5 player vflisCO7O
> [youtube] {248} signature length 44.40, html5 player vflisCO7O
> [youtube] {136} signature length 44.40, html5 player vflisCO7O
> [youtube] {247} signature length 44.40, html5 player vflisCO7O
> [youtube] {135} signature length 44.38, html5 player vflisCO7O
> [youtube] {244} signature length 44.40, html5 player vflisCO7O
> [youtube] {134} signature length 44.40, html5 player vflisCO7O
> [youtube] {243} signature length 44.40, html5 player vflisCO7O
> [youtube] {133} signature length 44.40, html5 player vflisCO7O
> [youtube] {242} signature length 44.40, html5 player vflisCO7O
> [youtube] {160} signature length 44.40, html5 player vflisCO7O
> [youtube] {278} signature length 44.40, html5 player vflisCO7O
> [youtube] {140} signature length 44.40, html5 player vflisCO7O
> [youtube] {171} signature length 44.40, html5 player vflisCO7O
> [youtube] {249} signature length 44.40, html5 player vflisCO7O
> [youtube] {250} signature length 44.40, html5 player vflisCO7O
> [youtube] {251} signature length 44.40, html5 player vflisCO7O
> WARNING: unable to extract channel id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type
>  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [info] Available formats for 0UXLWtooaGA: ...
> ```
> 
> just a report

Same issue

**Comment by guitarchord** [comment]
> ```
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--no-check-certificate', '--verbose', '-F', 'https://www.youtube.com/watch?v=0UXLWtooaGA']
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2019.04.30
> [debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
> [debug] exe versions: ffmpeg N-92795-gcdbf8847ea, ffprobe N-92795-gcdbf8847ea
> [debug] Proxy map: {}
> [youtube] 0UXLWtooaGA: Downloading webpage
> [youtube] 0UXLWtooaGA: Downloading video info webpage
> [youtube] {18} signature length 44.40, html5 player vflisCO7O
> [youtube] {137} signature length 44.40, html5 player vflisCO7O
> [youtube] {248} signature length 44.40, html5 player vflisCO7O
> [youtube] {136} signature length 44.40, html5 player vflisCO7O
> [youtube] {247} signature length 44.40, html5 player vflisCO7O
> [youtube] {135} signature length 44.38, html5 player vflisCO7O
> [youtube] {244} signature length 44.40, html5 player vflisCO7O
> [youtube] {134} signature length 44.40, html5 player vflisCO7O
> [youtube] {243} signature length 44.40, html5 player vflisCO7O
> [youtube] {133} signature length 44.40, html5 player vflisCO7O
> [youtube] {242} signature length 44.40, html5 player vflisCO7O
> [youtube] {160} signature length 44.40, html5 player vflisCO7O
> [youtube] {278} signature length 44.40, html5 player vflisCO7O
> [youtube] {140} signature length 44.40, html5 player vflisCO7O
> [youtube] {171} signature length 44.40, html5 player vflisCO7O
> [youtube] {249} signature length 44.40, html5 player vflisCO7O
> [youtube] {250} signature length 44.40, html5 player vflisCO7O
> [youtube] {251} signature length 44.40, html5 player vflisCO7O
> WARNING: unable to extract channel id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type
>  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [info] Available formats for 0UXLWtooaGA: ...
> ```
> 
> just a report

Same issue

**Comment by andrewluetgers** [comment]
same here

**Comment by tomasjiricek** [comment]
I'm facing the same issue on Raspbian, tried to update youtube-dl already.
