### ISSUE TITLE
can't download video from redtube

### ISSUE THREAD

**Issue by Jeffin21** [rg3/youtube-dl#20024]
{"display_id": "7529191-1", "extractor": "generic", "protocol": "data", "_filename": "Indian Aunty Mumbai Escorts (1)-7529191-1.mp4", "format": "0 - unknown", "requested_subtitles": null, "playlist_uploader": null, "height": null, "format_id": "0", "playlist_index": 1, "subtitles": {}, "playlist_title": "Indian Aunty Mumbai Escorts", "playlist": "Indian Aunty Mumbai Escorts", "title": "Indian Aunty Mumbai Escorts (1)", "url": "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7", "extractor_key": "Generic", "vcodec": null, "http_headers": {"Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Referer": "https://www.redtube.net/7529191"}, "id": "7529191-1", "playlist_id": "7529191", "ext": "mp4", "n_entries": 3, "webpage_url": "https://www.redtube.net/7529191", "formats": [{"protocol": "data", "http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Referer": "https://www.redtube.net/7529191", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"}, "url": "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7", "vcodec": null, "format": "0 - unknown", "height": null, "ext": "mp4", "format_id": "0"}], "playlist_uploader_id": null, "fulltitle": "Indian Aunty Mumbai Escorts (1)", "thumbnail": null, "webpage_url_basename": "7529191"} {"display_id": "7529191-2", "extractor": "generic", "protocol": "data", "_filename": "Indian Aunty Mumbai Escorts (2)-7529191-2.unknown_video", "format": "0 - unknown", "requested_subtitles": null, "playlist_uploader": null, "height": null, "format_id": "0", "playlist_index": 2, "subtitles": {}, "playlist_title": "Indian Aunty Mumbai Escorts", "playlist": "Indian Aunty Mumbai Escorts", "title": "Indian Aunty Mumbai Escorts (2)", "url": "data:\"+o+\";base64,\"+i+\"", "extractor_key": "Generic", "vcodec": null, "http_headers": {"Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Referer": "https://www.redtube.net/7529191"}, "id": "7529191-2", "playlist_id": "7529191", "ext": "unknown_video", "n_entries": 3, "webpage_url": "https://www.redtube.net/7529191", "formats": [{"protocol": "data", "http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Referer": "https://www.redtube.net/7529191", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"}, "url": "data:\"+o+\";base64,\"+i+\"", "vcodec": null, "format": "0 - unknown", "height": null, "ext": "unknown_video", "format_id": "0"}], "playlist_uploader_id": null, "fulltitle": "Indian Aunty Mumbai Escorts (2)", "thumbnail": null, "webpage_url_basename": "7529191"} {"display_id": "7529191-3", "extractor": "generic", "protocol": "data", "_filename": "Indian Aunty Mumbai Escorts (3)-7529191-3.unknown_video", "format": "0 - unknown", "requested_subtitles": null, "playlist_uploader": null, "height": null, "format_id": "0", "playlist_index": 3, "subtitles": {}, "playlist_title": "Indian Aunty Mumbai Escorts", "playlist": "Indian Aunty Mumbai Escorts", "title": "Indian Aunty Mumbai Escorts (3)", "url": "data:\"+o+\"; base64,\"+i+\"", "extractor_key": "Generic", "vcodec": null, "http_headers": {"Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Referer": "https://www.redtube.net/7529191"}, "id": "7529191-3", "playlist_id": "7529191", "ext": "unknown_video", "n_entries": 3, "webpage_url": "https://www.redtube.net/7529191", "formats": [{"protocol": "data", "http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Referer": "https://www.redtube.net/7529191", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"}, "url": "data:\"+o+\"; base64,\"+i+\"", "vcodec": null, "format": "0 - unknown", "height": null, "ext": "unknown_video", "format_id": "0"}], "playlist_uploader_id": null, "fulltitle": "Indian Aunty Mumbai Escorts (3)", "thumbnail": null, "webpage_url_basename": "7529191"}

**Comment by JChris246** [comment]
The regex for the extractor is not written to recognise .net yet .... for now just change the .net in the url to .com and it should be fine
