### ISSUE TITLE
pluralsight error again

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#20025]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.02.18
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

pluralsight is giving error sins yesterday and before it was working fine

PS C:\Users\HDNLRG1011> youtube-dl --verbose -o 'd:\contents\New folder/%(playlist)s/%(playlist_index)s - %(title)s.%(ex
t)s' https://app.pluralsight.com/library/courses/aspdotnet-core-api-openapi-swagger --sleep-interval 80 --limit-rate 250
k --username 12345@abc.com --password 12345
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', 'd:\\contents\\New folder/%(playlist)s/%(playlist_index)s - %(title)s.%(e
xt)s', 'https://app.pluralsight.com/library/courses/aspdotnet-core-api-openapi-swagger', '--sleep-interval', '80', '--li
mit-rate', '250k', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1255, fs mbcs, out cp862, pref cp1255
[debug] youtube-dl version 2019.02.18
[debug] Python version 3.5.4 (CPython) - Windows-2012ServerR2-6.3.9600-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] aspdotnet-core-api-openapi-swagger: Downloading JSON metadata
[download] Downloading playlist: Documenting an ASP.NET Core API with OpenAPI / Swagger
[pluralsight:course] playlist Documenting an ASP.NET Core API with OpenAPI / Swagger: Collected 61 video ids (downloadin
g 61 of them)
[download] Downloading video 1 of 61
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by <HTTPError 503: 'Service T
emporarily Unavailable'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest versio
n; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its c
omplete output.
  File "c:\program files\python35\lib\site-packages\youtube_dl\extractor\common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\program files\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\program files\python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "c:\program files\python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\program files\python35\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "c:\program files\python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "c:\program files\python35\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

PS C:\Users\HDNLRG1011>

**Comment by dstftw** [comment]
Most likely pluralsight side server error. In any case you must provide account credentials.

**Comment by jaan143** [comment]
@dstftw  how can i provide pluralsight account ?
it is working in browser

**Comment by jaan143** [comment]
@dstftw  bro please check your gmail

**Comment by remitamine** [comment]
```
youtube-dl --username 'example@example.com' --password pass --sleep-interval 80 --limit-rate 250 https://app.pluralsight.com/library/courses/aspdotnet-core-api-openapi-swagger
[pluralsight:course] aspdotnet-core-api-openapi-swagger: Downloading JSON metadata
[download] Downloading playlist: Documenting an ASP.NET Core API with OpenAPI / Swagger
[pluralsight:course] playlist Documenting an ASP.NET Core API with OpenAPI / Swagger: Collected 61 video ids (downloading 61 of them)
[download] Downloading video 1 of 61
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] fc00e343-081d-4113-8399-47606dac77f5-0: Downloading JSON metadata
[pluralsight] fc00e343-081d-4113-8399-47606dac77f5-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] fc00e343-081d-4113-8399-47606dac77f5-0: Waiting for 5 seconds to avoid throttling
[download] Sleeping 80 seconds...
[download] Destination: Course Overview-3fe4ca6e-f6a6-4d81-8472-7ad0490cb4f8.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2 2638k    2 64617    0     0    744      0  1:00:31  0:01:26  0:59:05     0
```

**Comment by davidneudorfer** [comment]
Thanks for the quick reply @remitamine. I tried to reproduce your command and it fails with the 503 error.

```
/usr/local/bin/youtube-dl \
  --username 'username@domain.com' \
  --password password \
  --sleep-interval 80 \
  --limit-rate 250 \
  https://app.pluralsight.com/library/courses/aspdotnet-core-api-openapi-swagger
```

```
[pluralsight:course] aspdotnet-core-api-openapi-swagger: Downloading JSON metadata
[download] Downloading playlist: Documenting an ASP.NET Core API with OpenAPI / Swagger
[pluralsight:course] playlist Documenting an ASP.NET Core API with OpenAPI / Swagger: Collected 61 video ids (downloading 61 of them)
[download] Downloading video 1 of 61
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I'll send my credentials.

**Comment by Kerruba** [comment]
I get the same error here:
youtube-dl --verbose --username "xxxx" --password "xxxxx" https://app.pluralsight.com/library/courses/oauth2-json-web-tokens-openid-connect-introduction/table-of-contents
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://app.pluralsight.com/library/courses/oauth2-json-web-tokens-openid-connect-introduction/table-of-contents']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Python version 2.7.15 (CPython) - Linux-4.15.0-1033-oem-x86_64-with-debian-buster-sid
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] oauth2-json-web-tokens-openid-connect-introduction: Downloading JSON metadata
[download] Downloading playlist: Introduction to OAuth2, OpenID Connect and JSON Web Tokens (JWT)
[pluralsight:course] playlist Introduction to OAuth2, OpenID Connect and JSON Web Tokens (JWT): Collected 48 video ids (downloading 48 of them)
[download] Downloading video 1 of 48
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 619, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_2/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_2/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_2/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_2/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by Kerruba** [comment]
@jaan143 and @davidneudorfer, something changed for you?

**Comment by Kerruba** [comment]
I was able to make it work by using a different IP (a VPN in my case)
I took inspiration from https://github.com/ytdl-org/youtube-dl/issues/18534
Now it seems to work

**Comment by xvMODvx** [comment]
I was having problems running it the way I've always done it. The way I solved the problem was to try using youtube-dl through pip instead of the version through npm like I was. Hope this helps someone.
