### ISSUE TITLE
Youtube --write-auto-sub --sub-lang en downloads all languages, not just en

### ISSUE THREAD

**Issue by jimbo1qaz** [rg3/youtube-dl#20028]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: ['--all-subs']
[debug] Custom config: []
[debug] Command-line args: ['--write-auto-sub', '--sub-lang', 'en', 'https://www.youtube.com/watch?v=PnSqSuKO7a4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.18
[debug] Python version 3.6.7 (CPython) - Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
[debug] Proxy map: {}
[youtube] PnSqSuKO7a4: Downloading webpage
[youtube] PnSqSuKO7a4: Downloading video info webpage
[youtube] PnSqSuKO7a4: Looking for automatic captions
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: If Minecraft Worlds Were Made of Glass!-PnSqSuKO7a4.af.vtt
[info] Writing video subtitles to: If Minecraft Worlds Were Made of Glass!-PnSqSuKO7a4.sq.vtt
[info] Writing video subtitles to: If Minecraft Worlds Were Made of Glass!-PnSqSuKO7a4.am.vtt
[info] Writing video subtitles to: If Minecraft Worlds Were Made of Glass!-PnSqSuKO7a4.ar.vtt
[info] Writing video subtitles to: If Minecraft Worlds Were Made of Glass!-PnSqSuKO7a4.hy.vtt
[info] Writing video subtitles to: If Minecraft Worlds Were Made of Glass!-PnSqSuKO7a4.az.vtt
[info] Writing video subtitles to: If Minecraft Worlds Were Made of Glass!-PnSqSuKO7a4.bn.vtt
^C
ERROR: Interrupted by user
```
I terminated youtube-dl, but you get the point...

### Description of your *issue*, suggested solution and other information

`youtube-dl --write-auto-sub --sub-lang en 'https://www.youtube.com/watch?v=PnSqSuKO7a4'`

I expect it to download English auto-captions, but it instead downloads every language Youtube offers as a translation. I think `--sub-lang en` fails to affect `--write-auto-sub` (does it only affect `--write-sub`?)

**Comment by dstftw** [comment]
>[debug] User config: ['--all-subs']

**Comment by appleton-tom** [comment]
The answer is in your submission. By including '--all-subs' you get all the subs.
'--sub-lang en' does not over-ride '--all-subs'

I use '--write-sub --write-auto-sub --sub-lang en'

This will download the regular subtitles if they exist, if not it tries to download the auto-generated subs.

**Comment by jimbo1qaz** [comment]
Issue was, adding `--all-subs` to `~/.config/youtube-dl/config` was affecting the execution of `~/.config/mpv/mpv.conf` etc. So I cleaned up youtube-dl/config.

**Comment by garoto** [comment]
in mpv.conf
```
ytdl-raw-options=ignore-config=
```
