### ISSUE TITLE
Download audio-only as Webm / Keep Webm file "effectively" (without using -k)

### ISSUE THREAD

**Issue by fx-pro** [rg3/youtube-dl#20075]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Currently, to download the best quality audio from youtube video, we simply use
youtube-dl -x ULR

The application download the webm file, then quickly "get out" the opus file from webm container and immediately delete original webm file.

However, the opus file isn't widely supported, I want to keep the webm file.

Of course, the application suggest using "-k" to keep that file. But when we use -k, the whole video file (which is 8-10x bigger) would be downloaded.

Please add one more option for this purpose (download audio-only as Webm), or simply add *webm* to --audio-format
 
![image](https://user-images.githubusercontent.com/12131419/53528653-d7f82e00-3b1c-11e9-815f-1bb10b4f4099.png)

Thank you

**Comment by dstftw** [comment]
Don't use `-x` in the first place if you don't need any conversion.

**Comment by fx-pro** [comment]
@dstftw Could you please read my issue for one minute instead of close it immediately? Please.
We use -x to download the audio only instead of the big whole audio file.
The webm file is downloaded actually, but it was deleted.

Add "webm" to AUDIO-FORMAT is reasonable.

**Comment by fx-pro** [comment]
Anyway, I've changed the title of issues
