### ISSUE TITLE
unable to download tedx youtube channel 

### ISSUE THREAD

**Issue by kaveinthran** [rg3/youtube-dl#20078]
hi,
I am using the latest version of youtube-dl and when I tried this,
"youtube-dl -f 43 -o %(title)s --verbose https://www.youtube.com/user/TEDxTalks"
it successfully downloaded all 288 youtube pages, but return unable to download json metadata internal server error

attached the 
[tedx.txt](https://github.com/rg3/youtube-dl/files/2913103/tedx.txt)
 the complete output

**Comment by dstftw** [comment]
Most likely server side youtube issue.
