### ISSUE TITLE
Downloading mp3's from a specific time?

### ISSUE THREAD

**Issue by pYbiz** [rg3/youtube-dl#20074]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://youtu.be/xk5mLMiiP_o?t=3

---

### Description of your *issue*, suggested solution and other information

I want to download the mp3 from this https://youtu.be/xk5mLMiiP_o?t=3 time stamp, is there way to do so?

I have tried this 
`youtube-dl -i --extract-audio --audio-format mp3 --audio-quality 0 -o "%(title)s.%(ext)s" -g  https://youtu.be/xk5mLMiiP_o?t=3`

But it doesnt work

**Comment by dstftw** [comment]
Not possible.

**Comment by rautamiekka** [comment]
The only way is to DL the vid (or, even better, just the audio), then use FFmpeg to cut the file as necessary.

Not the simplest of things, but still very doable.
