### ISSUE TITLE
Unable to download videos from vimeopro.com.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#20070]
Example:

$ youtube-dl https://vimeopro.com/bluemanorlando/blue-man-group-education-program/video/119245925
[vimeo] 119245925: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
(SopelPython3)ant@ANTian:~/Downloads/videos$ clear
(SopelPython3)ant@ANTian:~/Downloads/videos$ youtube-dl -v https://vimeopro.com/bluemanorlando/blue-man-group-education-program/video/119245925
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vimeopro.com/bluemanorlando/blue-man-group-education-program/video/119245925']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.18
[debug] Python version 3.4.2 (CPython) - Linux-3.16.0-7-amd64-x86_64-with-debian-8.11
[debug] exe versions: avconv 11.12-6, avprobe 11.12-6, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 119245925: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 513, in _real_extract
    webpage, urlh = self._download_webpage_handle(request, video_id)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 638, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 623, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 513, in _real_extract
    webpage, urlh = self._download_webpage_handle(request, video_id)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 638, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 623, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 528, in _real_extract
    expected=True)
youtube_dl.utils.ExtractorError: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.

**Comment by dnlzzxz** [comment]
Hello friend, looks like this is a embed video so it is only meant to be played in the designed page! Despite `youtube-dl` being very powerful and having an option to refer to a external URL I was not able to find which URL is needed for the video you just provided. But I was able to find a workaround, for that you'll need to open the link `
https://vimeopro.com/bluemanorlando/blue-man-group-education-program/video/119245925` provided with your browser ( in this example I will use chrome, so it can vary from browser to browser), once the link is opened in the browser you will press `ctrl + shift + i` then a new windows will pop-up, refresh the page with the video opened in it, press the play button and get back to the window that pop up previously. In that window go to the tab `network` then select `all` in the another tab below, then scroll the list in the lower left till the end, you'll see something like this `4466218113188.mp4?expires=6843548131...`  so click in it, then in the pane on the right select the tab `Headers`  and find this `Request URL` . That is the url that you're going to feed to youtube-dl to download, so copy that URL and paste in the command line and hopefully it will download alright. 

Obviously that is a lazy workaround, but is enough to download one video or two, not so doable for many vids which would be painful. 

But I hope this helps you, if you need some terms to research for this you want to find the REFERER URL to download VIMEO PRO EMBEDED VIDEOS. 

Don't forget to close the issue.

**Comment by mjbaldwin** [comment]
This seems like the best place to ask... I have a similar problem with not being able to download from Vimeo Pro, but the suggested solution doesn't work for me, because Chrome debug tools show that the video is being downloaded in segments:

https://skyfire.vimeocdn.com/156...708-0x0c16a6...4e268/359...138/sep/audio/1469...589/chop/segment-1.m4s
https://skyfire.vimeocdn.com/156...708-0x0c16a6...4e268/359...138/sep/video/1469...589/chop/segment-1.m4s

Very quickly going from segment 1 to 2 to 3 and so on...

Is youtube-dl able to deal with videos that show up chunked for whatever reason? And if so, any idea what URL I could pass?

Before the segments, a request is also made:

https://skyfire.vimeocdn.com/156...708-0x0c16a6...4e268/359...138/sep/video/1469...589/master.json?base64_init=1

which returns something like:

{clip_id: "359...138", base_url: "../",…}
audio: [{id: "146...589", base_url: "../audio/1469...589/chop/", format: "mp42", mime_type: "audio/mp4",…},…]
base_url: "../"
clip_id: "359...138"
video: [{id: "146...605", base_url: "1469...605/chop/", format: "mp42", mime_type: "video/mp4",…},…]

(Unfortunately I can't provide you with the original video URL since it's password-protected.)

**Comment by luvarpt** [comment]
Try to change suffix of url **master.json?base64_init=1** into **master.mpd**. Have a look at [akamai documentation](https://learn.akamai.com/en-us/webhelp/media-services-live/media-services-live-encoder-compatibility-testing-and-qualification-guide-v4.0/GUID-A5FD9C5A-F946-4967-90B4-D050CE819D16.html).

**Comment by nyh** [comment]
I also tried to youtube-dl a movie from vimeopro.com, and failed, but the tricks suggested above (look for the "master.json" URL, change it to master.mpd, and ask youtube-dl to download that) worked like a charm. So I wonder, instead of closing this issue, shouldn't this logic be incorporated into youtube-dl?
