### ISSUE TITLE
Add WEBM to --audio-format. It's the original downloaded file when using -x [audio-only]

### ISSUE THREAD

**Issue by fx-pro** [rg3/youtube-dl#20076]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Currently, to download the best quality audio from youtube video, we simply use
youtube-dl -x ULR

The application download the webm file, then quickly "get out" the opus file from webm container and immediately delete original webm file.

However, the opus file isn't widely supported, I want to keep the webm file.

Of course, the application suggest using "-k" to keep that file. But when we use -k, the whole video file (which is 8-10x bigger) would be downloaded.

Please add one more option for this purpose (download audio-only as Webm), or simply add *webm* to --audio-format
 
![image](https://user-images.githubusercontent.com/12131419/53528653-d7f82e00-3b1c-11e9-815f-1bb10b4f4099.png)

Thank you

**Comment by dstftw** [comment]
webm is a **container** not a codec, it has nothing to do with `--audio-format`.

**Comment by fx-pro** [comment]
> webm is a **container** not a codec, it has nothing to do with `--audio-format`.

Ok then, so how can we keep the webm (audio only) file. It's actually downloaded, but impossible to keep?

**Comment by dstftw** [comment]
Provide complete verbose log of what are you trying to execute.

**Comment by fx-pro** [comment]
Screenshot of execute with detailed highlight and explanation 

![image](https://user-images.githubusercontent.com/12131419/53530683-39230000-3b23-11e9-918e-ac233dbbd041.png)


> webm is a **container** not a codec, it has nothing to do with `--audio-format`.

In addition, it's "--audio-format", not "--audio-codec". So **literally**, "webm", an [audio file format](https://en.wikipedia.org/wiki/Audio_file_format#Lossy_compressed_audio_format), is still fit to that option.
