### ISSUE TITLE
Correct my code.

### ISSUE THREAD

**Issue by dropitlikecross** [rg3/youtube-dl#20086]
Could you correct my code;

--download-archive "/mnt/streamstorage/music/gamingstream/archive.txt" -o "/mnt/streamstorage/music/gamingstream/%(title)s.%(ext)s" -f bestaudio --audio-format mp3 "https://www.youtube.com/playlist?list=PLKUA473MWUv03VnZLb98iAxdbCLxl0qG3"- --reject-title "podcast" --reject-title "cinematic" --reject-title "mix" --geo-bypass --yes-playlist --playlist-start 1 --add-metadata -x --metadata-from-title "%(artist)s - %(title)s"

**Comment by dstftw** [comment]
Remove dash after the URL.
