### ISSUE TITLE
NPO Download format not found.

### ISSUE THREAD

**Issue by WuvorWenda** [rg3/youtube-dl#20084]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.npostart.nl/nos-journaal/28-02-2019/POW_04056484']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.02.18
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-91789-g11cec34829, rtmpdump 2.4
[debug] Proxy map: {}
[npo] POW_04056484: Downloading JSON metadata
[npo] POW_04056484: Downloading token
[npo] POW_04056484: Downloading formats JSON
[npo] POW_04056484: Downloading Adaptive stream JSON
[npo] POW_04056484: Downloading Hoog stream JSON
[npo] POW_04056484: Downloading Normaal stream JSON
[npo] POW_04056484: Downloading Laag stream JSON
[info] Available formats for POW_04056484:
format code  extension  resolution note
0            m4v        unknown
Laag         m4v        unknown
Normaal      m4v        unknown
Hoog         m4v        unknown    (best)

Can not find the streams anymore.

**Comment by dstftw** [comment]
Content is DRM protected.

**Comment by WuvorWenda** [comment]
Thank you for the commit,
But i get this error now with version 2019.03.01
[debug] Custom config: []
[debug] Command-line args: ['-f', '0', 'https://www.npostart.nl/keuringsdienst-van-waarde/28-02-2019/KN_1704077']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.03.01
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-91789-g11cec34829, rtmpdump 2.4
[debug] Proxy map: {}
[npo] KN_1704077: Downloading token
[npo] KN_1704077: Downloading player JSON
[npo] KN_1704077: Downloading hls profile JSON
[npo] KN_1704077: Downloading dash-widevine profile JSON
[npo] KN_1704077: Downloading MPD manifest
[npo] KN_1704077: Downloading dash-playready profile JSON
[npo] KN_1704077: Downloading MPD manifest
[npo] KN_1704077: Downloading smooth profile JSON
[npo] KN_1704077: Downloading ISM manifest
[npo] KN_1704077: Downloading JSON metadata
[npo] KN_1704077: Downloading token
[npo] KN_1704077: Downloading formats JSON
[npo] KN_1704077: Downloading Adaptive stream JSON
[npo] KN_1704077: Downloading Hoog stream JSON
[npo] KN_1704077: Downloading Normaal stream JSON
[npo] KN_1704077: Downloading Laag stream JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtu
be-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\npo.py", line 185, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\npo.py", line 249, in _get_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\common.py", line 1305, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\npo.py", line 185, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\npo.py", line 249, in _get_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\common.py", line 1305, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\npo.py", line 187, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\npo.py", line 456, in _get_old_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\common.py", line 1305, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by BartG95** [comment]
What's the purpose of the commit if it won't work anyway?

**Comment by dstftw** [comment]
It does work for non DRM videos.

**Comment by Reino17** [comment]
Such as? All the videos on npo.nl have DRM now, or are at least "SAMPLE-AES" encrypted as far as I know. I know of no non-DRM videos.

**Comment by dstftw** [comment]
[Wrong](https://www.npostart.nl/aap-poot-pies/08-05-2015/VPWON_1233944).

**Comment by rien333** [comment]
@dstftw I can't download that video as well.

**Comment by WuvorWenda** [comment]
That video is the old system in 2015 there was no encryption. 
The live stream is also broken.
[debug] youtube-dl version 2019.03.01
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-91789-g11cec34829, rtmpdump 2.4
[debug] Proxy map: {}
[npo.nl:live] npo-1: Downloading webpage
[npo] LI_NL1_4188102: Downloading token
[npo] LI_NL1_4188102: Downloading player JSON
[npo] LI_NL1_4188102: Downloading hls profile JSON
[npo] LI_NL1_4188102: Downloading dash-widevine profile JSON
[npo] LI_NL1_4188102: Downloading MPD manifest
[npo] LI_NL1_4188102: Downloading dash-playready profile JSON
[npo] LI_NL1_4188102: Downloading MPD manifest
[npo] LI_NL1_4188102: Downloading smooth profile JSON
[npo] LI_NL1_4188102: Downloading embed page
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\YoutubeDL.py", line 805, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\YoutubeDL.py", line 897, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\YoutubeDL.py", line 859, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\YoutubeDL.py", line 1632, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available
The livestream has no DRM
https://www.npostart.nl/live/npo-1

**Comment by BartG95** [comment]
I have tested the example from dstftw. Both last weekend and today. Both time I could download it, without any problem.
As for the livestream, what does downloading a livestream even mean?

**Comment by WuvorWenda** [comment]
> I have tested the example from dstftw. Both last weekend and today. Both time I could download it, without any problem.
> As for the livestream, what does downloading a livestream even mean?

You want to record a tv show,
Or stream to a named pipe and watch live in your favorite player.
And youtube-dl is standard in MPV.
MPV is now longer unable to stream from npo.
example **mpv ytdl://https://www.npostart.nl/live/npo-1**

**Comment by BartG95** [comment]
That's an interesting use case; it could be used to download any episode while it is being broadcasted (and therefore circumventing the DRM). I guess the NPO is aware of it and therefore somehow 'protected' the livestream.
Maybe there *is* some DRM on the livestream. The certainly made it a lot more difficult.

**Comment by WuvorWenda** [comment]
> That's an interesting use case; it could be used to download any episode while it is being broadcasted (and therefore circumventing the DRM). I guess the NPO is aware of it and therefore somehow 'protected' the livestream.
> Maybe there _is_ some DRM on the livestream. The certainly made it a lot more difficult.
I have a old version of youtube-dl works great with the livestream.
I want to download a older version for windows, then is mpv is working again,

**Comment by peternowee** [comment]
Online petition requesting NPO to remove DRM: https://www.petities.nl/petitions/npo-maak-downloaden-weer-mogelijk
