### ISSUE TITLE
Unable to download video with -f 17 or -f 36 anymore

### ISSUE THREAD

**Issue by Roland74** [rg3/youtube-dl#20081]
Hello
## Please follow the guide below

my version is:
pi@raspberrypi:~ $ youtube-dl --version
2019.02.18

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
pi@raspberrypi:~ $ youtube-dl -v -f 36 https://youtu.be/pRSjyeogm5U
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'36', u'https://youtu.be/pRSjyeogm5U'                                                                                                                                   ]
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.18
[debug] Python version 2.7.13 (CPython) - Linux-4.14.92+-armv6l-with-debian-9.6
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] pRSjyeogm5U: Downloading webpage
[youtube] pRSjyeogm5U: Downloading video info webpage
[youtube] {18} signature length 41.40, html5 player vflX2rhq7
[youtube] {136} signature length 41.40, html5 player vflX2rhq7
[youtube] {247} signature length 41.40, html5 player vflX2rhq7
[youtube] {135} signature length 41.40, html5 player vflX2rhq7
[youtube] {244} signature length 41.40, html5 player vflX2rhq7
[youtube] {134} signature length 41.40, html5 player vflX2rhq7
[youtube] {243} signature length 41.40, html5 player vflX2rhq7
[youtube] {133} signature length 41.40, html5 player vflX2rhq7
[youtube] {242} signature length 41.40, html5 player vflX2rhq7
[youtube] {160} signature length 41.40, html5 player vflX2rhq7
[youtube] {278} signature length 41.40, html5 player vflX2rhq7
[youtube] {140} signature length 41.40, html5 player vflX2rhq7
[youtube] {171} signature length 41.40, html5 player vflX2rhq7
[youtube] {249} signature length 41.40, html5 player vflX2rhq7
[youtube] {250} signature length 41.40, html5 player vflX2rhq7
[youtube] {251} signature length 41.40, html5 player vflX2rhq7
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 805, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 859, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1632, in process_video_result
    expected=True)
ExtractorError: requested format not available

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information
I normally do youtube-dl -F
That lists all available formats. 
Some days ago the videos above offered 17 and 36 as very small formats. I received a 3gp video file.
Now I am not offered the format any more. All files are much larger now e.g.
youtube-dl -F https://youtu.be/pRSjyeogm5U
[youtube] pRSjyeogm5U: Downloading webpage
[youtube] pRSjyeogm5U: Downloading video info webpage
[info] Available formats for pRSjyeogm5U:
format code  extension  resolution note
249          webm       audio only DASH audio   55k , opus @ 50k, 1.77MiB
250          webm       audio only DASH audio   69k , opus @ 70k, 2.33MiB
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k, 5.64MiB
171          webm       audio only DASH audio  132k , vorbis@128k, 4.43MiB
251          webm       audio only DASH audio  138k , opus @160k, 4.58MiB
278          webm       256x144    144p   96k , webm container, vp9, 24fps, video only, 3.85MiB
160          mp4        256x144    144p  109k , avc1.4d400c, 24fps, video only, 2.99MiB
242          webm       426x240    240p  225k , vp9, 24fps, video only, 6.39MiB
133          mp4        426x240    240p  301k , avc1.4d4015, 24fps, video only, 6.73MiB
243          webm       640x360    360p  412k , vp9, 24fps, video only, 11.33MiB
134          mp4        640x360    360p  675k , avc1.4d401e, 24fps, video only, 12.24MiB
244          webm       854x480    480p  732k , vp9, 24fps, video only, 14.82MiB
135          mp4        854x480    480p  991k , avc1.4d401e, 24fps, video only, 17.21MiB
136          mp4        1280x720   720p 1112k , avc1.4d401f, 24fps, video only, 22.47MiB
247          webm       1280x720   720p 1187k , vp9, 24fps, video only, 22.18MiB
18           mp4        640x360    medium  517k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 22.55MiB (best)

What happened. Why is 17 and 36 not offered any more.
Kind regards,
Roland

**Comment by dstftw** [comment]
Address this question to Youtube.

**Comment by Roland74** [comment]
It seems to be a general issue because I see this behaviour for all youtube links which had worked recently with this format. Is it your suggestion that I should address this question to youtube or could you do it for me. To be honest I do not know how to contact the youtube support and it's probably easier if you could address this question to youtube as you know more details.
It would be great if you could help me.
Best regards,
 Roland

**Comment by Roland74** [comment]
I am not sure if I asked my question to youtube correctly. Please see:
https://support.google.com/youtube/thread/1944781?hl=en
It would be great if you could help me.
Best regards,
Roland

**Comment by Hrxn** [comment]
Pretty likely that this is an intentional change by YouTube, i.e. they are currently retiring some specific formats from their infrastructure.
