### ISSUE TITLE
Specific Youtube Video Failure

### ISSUE THREAD

**Issue by landre3567** [rg3/youtube-dl#20083]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
/usr/local/bin/youtube-dl --verbose --restrict-filenames -f "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]" https://www.youtube.com/watch?v=6C9GaonPE1Q -o /tmp/video.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--restrict-filenames', u'-f', u'bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]', u'https://www.youtube.com/watch?v=6C9GaonPE1Q', u'-o', u'/tmp/video.mp4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.18
[debug] Python version 2.7.13 (CPython) - Linux-4.9.20-std-1-x86_64-with-debian-9.5
[debug] exe versions: avconv 3.2.12-1, avprobe 3.2.12-1, ffmpeg 3.2.12-1, ffprobe 3.2.12-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 6C9GaonPE1Q: Downloading webpage
[youtube] 6C9GaonPE1Q: Downloading video info webpage
[debug] Invoking downloader on u'https://r3---sn-25ge7nsd.googlevideo.com/videoplayback?mt=1551344680&expire=1551366364&lmt=1550161379343477&c=WEB&ei=fKR3XOGPJoP3V6qZrZgN&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398&txp=5532432&key=yt6&clen=8673710&requiressl=yes&ip=51.15.199.122&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&gir=yes&keepalive=yes&dur=94.041&fvip=3&pl=23&initcwndbps=293750&id=o-ALfNe9SBVydMFs4YFDZ7TE7NTa6KpSeLvebn6XSquBu-&mv=m&source=youtube&ms=au%2Crdu&signature=ADE47270D9ECE595DFA9E60703ED8203FD5B70FC.08994AC1CA0715E7BAA262B145633514EBE43C97&mime=video%2Fmp4&mn=sn-25ge7nsd%2Csn-25glen7y&mm=31%2C29&ipbits=0&itag=398&ratebypass=yes'
[download] Destination: /tmp/video.f398.mp4
[download] 100% of 8.27MiB in 00:00
[debug] Invoking downloader on u'https://r3---sn-25ge7nsd.googlevideo.com/videoplayback?mt=1551344680&expire=1551366364&lmt=1548864033673752&c=WEB&ei=fKR3XOGPJoP3V6qZrZgN&txp=5535432&key=yt6&clen=1523827&requiressl=yes&ip=51.15.199.122&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&gir=yes&keepalive=yes&dur=94.110&fvip=3&pl=23&initcwndbps=293750&id=o-ALfNe9SBVydMFs4YFDZ7TE7NTa6KpSeLvebn6XSquBu-&mv=m&source=youtube&ms=au%2Crdu&signature=68CA303BF8EA72B7CB6CD38B019678CA90CC58FE.2BC6DF4877E10EDB6F45DE150BB506417BB69CDD&mime=audio%2Fmp4&mn=sn-25ge7nsd%2Csn-25glen7y&mm=31%2C29&ipbits=0&itag=140&ratebypass=yes'
[download] Destination: /tmp/video.mp4.f140
[download] 100% of 1.45MiB in 00:00
[ffmpeg] Merging formats into "/tmp/video.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:/tmp/video.f398.mp4' -i 'file:/tmp/video.mp4.f140' -c copy -map '0:v:0' -map '1:a:0' 'file:/tmp/video.temp.mp4'
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2052, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

It works for the same video when 'bestvideo[height<=360]'

**Comment by appleton-tom** [comment]
Not a problem with "youtube-dl". The video and audio components were downloaded, but "ffmpeg" fails to merge them. The video component is encoded with new "AV1" format (av01.0.05M.08) and ffmpeg can't handle it.

**Comment by appleton-tom** [comment]
youtube-dl  --verbose --restrict-filenames -f 22  https://www.youtube.com/watch?v=6C9GaonPE1Q 

will download at 1280x720 MP4, video/audio already merged 

Also, 'bestvideo[height<=360]' resolves to a video encoding that ffmpeg can deal with.

**Comment by landre3567** [comment]
Thanks for you help
