### ISSUE TITLE
Unable to download from certain Nicovideo lists and videos

### ISSUE THREAD

**Issue by panhartstuff** [rg3/youtube-dl#20088]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
D:\>youtube-dl -o "D:\%(title)s-%(id)s.%(ext)s" --verbose https://www.nicovideo.jp/mylist/55184101
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-o', u'D:\\%(title)s-%(id)s.%(ext)s', u'--verbose', u'https://www.nicovideo.jp/mylist/55184101']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2019.02.18
[debug] Python version 2.7.14 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 3.4, ffprobe N-89471-g88e2dc7d04
[debug] Proxy map: {}
[NiconicoPlaylist] 55184101: Downloading webpage
[download] Downloading playlist: 黒星紅白お絵かき配信アーカイブ
[NiconicoPlaylist] playlist 黒星紅白お絵かき配信アーカイブ: Collected 121 video ids (downloading 121 of them)
[download] Downloading video 1 of 121
[niconico] sm30114123: Downloading webpage
[niconico] sm30114123: Downloading JSON metadata for h264_200kbps_360p-aac_64kbps
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

D:\>youtube-dl -o "D:\%(title)s-%(id)s.%(ext)s" --verbose https://www.nicovideo.jp/watch/sm34678046
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-o', u'D:\\%(title)s-%(id)s.%(ext)s', u'--verbose', u'https://www.nicovideo.jp/watch/sm34678046']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2019.02.18
[debug] Python version 2.7.14 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 3.4, ffprobe N-89471-g88e2dc7d04
[debug] Proxy map: {}
[niconico] sm34678046: Downloading webpage
[niconico] sm34678046: Downloading JSON metadata for h264_360p-aac_192kbps
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video (not working): https://www.nicovideo.jp/watch/sm34678046
- Single video (working): https://www.nicovideo.jp/watch/sm34486625
- Playlist (not working): https://www.nicovideo.jp/mylist/55184101
- Playlist (working): https://www.nicovideo.jp/mylist/28581626

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

youtube-dl is unable to download from the specific nicovideo playlist and video provided above. I also provided some extra links to a generic video and playlist that do work, as a comparison.
I suspect the reason behind the error is the fact that they're recorded livestreams, but they seem to be completely visually identical with normal videos, both in their URL path and their UI, so I'm really not sure.

**Comment by panhartstuff** [comment]
Nevermind, I fixed it by adding `-u user -p password` to the arguments.

**Comment by kurrrkurrr** [comment]
Hello, I know this is an old thread, and I don't post here at all, but I found this post through google looking for kuroboshi's videos.. the videos on niconico's archive have been deleted, and I was wondering if you uploaded (almost all) or could upload them for download somewhere? I'd happily pay you too if that's an incentive...I was slowly going thru them all but then it got mass deleted. If you could please help me out if you have the time.. Thank you.

**Comment by kurrrkurrr** [comment]
@panhartstuff oops.. I forgot to @ but I wrote the initial message above ^^^

**Comment by kurrrkurrr** [comment]
@panhartstuff Hello, I know this is an old thread, and I don't post here at all, but I found this post through google looking for kuroboshi's videos.. the videos on niconico's archive have been deleted, and I was wondering if you uploaded (almost all) or could upload them for download somewhere? I'd happily pay you too if that's an incentive...I was slowly going thru them all but then it got mass deleted. If you could please help me out if you have the time.. Thank you. (sorry for the duplicate spam, just in-case you don't get to see the first initial msg. Apologies, and thank you).
