### ISSUE TITLE
Missing age limits on porn sites

### ISSUE THREAD

**Issue by forresthopkinsa** [rg3/youtube-dl#20094]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.01
[debug] Git HEAD: 04c33bdfb
[debug] Python version 2.7.15 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
```

---

### Description of your *issue*, suggested solution and other information

There are a few extractors that don't have a hardcoded `age_limit`, which definitely should. These include:

- `SpankBangIE`
- `SoundgasmIE`
  - Note: this is a really bizarre website
- *Even Pornhub*
  - `PornHubPlaylistIE`
  - `PornHubUserVideosIE`

I need to use this library for a project at work, so I'm importing acceptable regexes to filter which sites should be sent to youtube-dl (I know, not an ideal method) and I *really can't* have porn sites in our code base. lol

**Comment by dstftw** [comment]
Playlist extractors are not supposed to have age_limit.

**Comment by forresthopkinsa** [comment]
Well then it's a good thing that two of the four listed extractors are not playlist extractors :)

Also, would you mind linking me to where this decision was made? I don't really understand why *any* extractor for a porn site wouldn't have a static age_limit. Thanks!
