### ISSUE TITLE
Youtube video gives FFmpegPostProcessorError: Stream #1:0 -> #0:1 (copy)

### ISSUE THREAD

**Issue by aghtragh** [rg3/youtube-dl#20095]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=H1H3OgPK48k']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.03.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-85266-g1229007
[debug] Proxy map: {}
[youtube] H1H3OgPK48k: Downloading webpage
[youtube] H1H3OgPK48k: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on [...]
[download] Destination: Elon Musk finds 'dolphin not working' meme hilarious _ Meme Review-H1H3OgPK48k.f397.mp4
[download] 100% of 1.10MiB in 00:00
[debug] Invoking downloader on [...]
[download] Destination: Elon Musk finds 'dolphin not working' meme hilarious _ Meme Review-H1H3OgPK48k.f140.m4a
[download] 100% of 595.99KiB in 00:00
[ffmpeg] Merging formats into "Elon Musk finds 'dolphin not working' meme hilarious _ Meme Review-H1H3OgPK48k.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Elon Musk finds 'dolphin not working' meme hilarious _ Meme Review-H1H3OgPK48k.f397.mp4" -i "file:Elon Musk finds 'dolphin not working' meme hilarious _ Meme Review-
H1H3OgPK48k.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:Elon Musk finds 'dolphin not working' meme hilarious _ Meme Review-H1H3OgPK48k.temp.mp4"
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\YoutubeDL.py", line 2052, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\postprocessor\ffmpeg.py", line 512, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
```

### Description of your *issue*, suggested solution and other information

Running this command
```youtube-dl -v https://www.youtube.com/watch?v=H1H3OgPK48k```
gives an ffmpeg error: 
```youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)```

**Comment by dstftw** [comment]
Outdated ffmpeg.

**Comment by appleton-tom** [comment]
There was a similar problem yesterday, see https://github.com/rg3/youtube-dl/issues/20083
Youtube has added a new encoding method and ffmpeg can't deal with it. The video component is encoded with new "AV1" format (av01.0.05M.08).[Note: A-V-ONE, not old AVI]
"Best" used to mean highest resolution, but now might mean 'best encoding' method ??
Use the -F to list all available audio/video formats, the select from that list.

In the example given in the description above no formats were selected so it defaults to "best"
In this case audio is 
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k, 595.99KiB
and video is
397          mp4        854x480    480p  308k , av01.0.05M.08, 24fps, video only, 1.10MiB
The downloads worked, but ffmpeg failed to merge.

22           mp4        1280x720   hd720  341k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)
is actually shown as "best", one download file, audio/video combined

Search on "av01.0.05M.08" to learn more about this new encoding.

**Comment by TegraMorgan** [comment]
I've updated the ffmpeg and it didn't solve the problem. However the problem occurs only when trying to encode to mp4. No problem with mkv

**Comment by tavyra** [comment]
Same, for both nightly and stable releases. MKV is fine for the time being, but I'd like to add thumbnails etc. and not have to externally convert to mp4 should I need to edit them in the future. 

If this is an ffmpeg issue, what is the last version of ffmpeg known to work with the most recent release? Or vice-versa.

**Comment by tavyra** [comment]
More helpful, it only seems to occur when the audio input is in webm, specifying m4a fixed this issue completely.

**Comment by reallyuniquename** [comment]
@dstftw 
It's not outdated ffmpeg. It's MP4 that doesn't support Opus audio which youtube-dl downloads. One have to manually use `bestaudio[ext=m4a]` otherwise `ffmpeg` will fail.
