### ISSUE TITLE
vorbis format selection

### ISSUE THREAD

**Issue by sebma** [rg3/youtube-dl#20206]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Hi,

I'm trying to select the 171 format of a youtube link using an explicit manner : 
```
$ youtube-dl -F https://www.youtube.com/watch?v=KMYovo6SoR4 | grep vorbis
171          webm       audio only DASH audio  121k , vorbis@128k, 2.39MiB
$ youtube-dl --ignore-config -v -f "best[acodec=vorbis]" https://www.youtube.com/watch?v=KMYovo6SoR4 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', '-f', 'best[acodec=vorbis]', 'https://www.youtube.com/watch?v=KMYovo6SoR4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.01
[debug] Python version 3.6.5 (CPython) - Linux-4.4.0-142-generic-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 3.4.4-1, avprobe 3.4.4-1, ffmpeg 3.4.4-1, ffprobe 3.4.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] KMYovo6SoR4: Downloading webpage
[youtube] KMYovo6SoR4: Downloading video info webpage
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 805, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 859, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1632, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available

$ echo $?
1
```

Can you please tell me how to do it ?

**Comment by dstftw** [comment]
It's `bestaudio` not `best`.

**Comment by sebma** [comment]
@dstftw Thanks :)
