### ISSUE TITLE
spankbang.com scraper broken (site layout changed)

### ISSUE THREAD

**Issue by grill02** [rg3/youtube-dl#20205]
All spankbang.com urls dont work anymore. I verified that they have changed their html code. You can verify with any url (youtube-dl 2019.03.01)

**Comment by sebma** [comment]
@dstftw Hi,

Can you please link the duplicate (whichever issue it is) to this one ?

**Comment by Hrxn** [comment]
#20023 

Fix (https://github.com/rg3/youtube-dl/commit/7465e0aee2301c3e86fe38d6e0ef5ad01c16ec79) should already be in `master`.
