### ISSUE TITLE
ERROR: unable to download video data: ''

### ISSUE THREAD

**Issue by chasrickarby** [rg3/youtube-dl#20214]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
irb(main):005:0> `youtube-dl -v -o '/home/deploy/test.vvv' -f mp4 --max-filesize 2000m -- xyvHvjyNQU0`
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-o', u'/home/deploy/test.vvv', u'-f', u'mp4', u'--max-filesize', u'2000m', u'--', u'xyvHvjyNQU0']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2019.03.01
[debug] Python version 2.7.3 (CPython) - Linux-3.4.113-amazon-xen-r2-x86_64-Intel-R-_Xeon-R-_CPU_E5-2676_v3_@_2.40GHz-with-gentoo-2.1
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: unable to download video data: ''
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1913, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1852, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1140, in https_open
    req, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

=> "[youtube] xyvHvjyNQU0: Downloading webpage\n[youtube] xyvHvjyNQU0: Downloading video info webpage\n[youtube] xyvHvjyNQU0: Downloading MPD manifest\n[debug] Invoking downloader on u'https://r2---sn-vgqskn7l.googlevideo.com/videoplayback?expire=1551486712&sparams=dur%2Cei%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mime=video%2Fmp4&itag=22&c=WEB&ipbits=0&fvip=3&ei=mHp5XLudC4TYhwbpibbQAg&requiressl=yes&ip=54.227.195.91&ratebypass=yes&pl=24&mv=u&dur=170.782&source=youtube&ms=au%2Crdu&lmt=1551135537055864&mn=sn-vgqskn7l%2Csn-vgqs7nes&mm=31%2C29&signature=815641C078331568CB46DD35A6FB53945E87AF76.E23C6A791DE636AC229D8F13A9DD8ABD43773987&key=yt6&id=o-ALdCEUXZPP3mqRTSThpF78wgVwP8fXpDX4rB5yfs5CuF&txp=2216222&mt=1551464960'\n"
```

---

---

### Description of your *issue*, suggested solution and other information

Intermittently videos can't be downloaded over youtube-dl. The error that is returned makes it seem like it's something connection related but the real root of the problem is unknown. I see this issue once or twice, and then a few minutes later run the same command again from the same environment and it works. I've never seen this problem before today (I updated to the latest release (3/1) today).

**Comment by dstftw** [comment]
Network issue on your/ISP side.
