### ISSUE TITLE
ERROR: audio conversion failed: "debug" (Wrong FFMPG Parameters)

### ISSUE THREAD

**Issue by wastene** [rg3/youtube-dl#20211]
Versions:
* youtube-dl 2019.03.01
* avconv version (ffmpeg) 11.12-6:11.12-1~deb8u1+rpi1

Running on a Raspberry Pi 3B

Executed Command:
`youtube-dl -x --audio-format mp3 https://youtu.be/GK5hf8ZsUr4`

Log of this Execution is below

FFMPEG Command Line not working:
`ffmpeg -y -loglevel repeat+info -i 'file:Kontra K - Farben (Official Video)-GK5hf8ZsUr4.webm' -vn -acodec libmp3lame -q:a 5 'file:Kontra K - Farben (Official Video)-GK5hf8ZsUr4.mp3'`

FFMPEG Command Line working:
`ffmpeg -y -loglevel debug -i 'file:Kontra K - Farben (Official Video)-GK5hf8ZsUr4.webm' -vn -acodec libmp3lame -q:a 5 'file:Kontra K - Farben (Official Video)-GK5hf8ZsUr4.mp3'`

If I execute the FFMPEG Command Line I get the error that the Log-Level "repeat+info" is not available. If I replace this with another log level (for example "debug") the conversion is working. Maybe you just need to change the parameters for calling the FFMPEG Command line.

Thanks.

Log:
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-x', 'https://youtu.be/GK5hf8ZsUr4', '-v', '--audio-format', 'mp3']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2019.03.01
> [debug] Python version 3.6.5 (CPython) - Linux-4.9.35-v7+-armv7l-with-debian-8.0
> [debug] exe versions: avconv 11.12-6, avprobe 11.12-6, ffmpeg 11.12-6, rtmpdump 2.4
> [debug] Proxy map: {}
> [youtube] GK5hf8ZsUr4: Downloading webpage
> [youtube] GK5hf8ZsUr4: Downloading video info webpage
> [youtube] {18} signature length 41.40, html5 player vflX2rhq7
> [youtube] {313} signature length 41.40, html5 player vflX2rhq7
> [youtube] {271} signature length 41.40, html5 player vflX2rhq7
> [youtube] {137} signature length 41.40, html5 player vflX2rhq7
> [youtube] {248} signature length 41.40, html5 player vflX2rhq7
> [youtube] {136} signature length 41.40, html5 player vflX2rhq7
> [youtube] {247} signature length 41.40, html5 player vflX2rhq7
> [youtube] {398} signature length 41.40, html5 player vflX2rhq7
> [youtube] {135} signature length 41.40, html5 player vflX2rhq7
> [youtube] {244} signature length 41.40, html5 player vflX2rhq7
> [youtube] {397} signature length 41.40, html5 player vflX2rhq7
> [youtube] {134} signature length 41.40, html5 player vflX2rhq7
> [youtube] {243} signature length 41.40, html5 player vflX2rhq7
> [youtube] {396} signature length 41.40, html5 player vflX2rhq7
> [youtube] {133} signature length 41.40, html5 player vflX2rhq7
> [youtube] {242} signature length 41.40, html5 player vflX2rhq7
> [youtube] {395} signature length 41.40, html5 player vflX2rhq7
> [youtube] {160} signature length 41.40, html5 player vflX2rhq7
> [youtube] {278} signature length 41.40, html5 player vflX2rhq7
> [youtube] {394} signature length 41.40, html5 player vflX2rhq7
> [youtube] {140} signature length 41.40, html5 player vflX2rhq7
> [youtube] {171} signature length 41.40, html5 player vflX2rhq7
> [youtube] {249} signature length 41.40, html5 player vflX2rhq7
> [youtube] {250} signature length 41.40, html5 player vflX2rhq7
> [youtube] {251} signature length 41.40, html5 player vflX2rhq7
> [debug] Invoking downloader on 'https://r5---sn-4g5ednsk.googlevideo.com/videoplayback?keepalive=yes&ipbits=0&mime=audio%2Fwebm&dur=220.481&itag=251&ip=46.223.144.111&gir=yes&source=youtube&mm=31%2C26&mn=sn-4g5ednsk%2Csn-h0jeen76&mt=1551454621&mv=m&pl=17&id=o-AItOP1J0F-X1-w-YG9khZJ52EFXS5krZqh_KRwHJSFaZ&ei=HlJ5XJayOImM1wLn4bSAAg&ms=au%2Conr&fvip=5&key=yt6&initcwndbps=1590000&txp=5511222&c=WEB&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&requiressl=yes&lmt=1550712319132769&clen=3830988&expire=1551476351&signature=D94032E51FF698EC66F46E725D71FC9E49FFC31F.B07B3E10664C9EB8B5FF4BF614D544435693CEA9&ratebypass=yes'
> [download] Kontra K - Farben (Official Video)-GK5hf8ZsUr4.webm has already been downloaded
> 
> [download] 100% of 3.65MiB
> [debug] ffmpeg command line: avprobe -show_streams 'file:Kontra K - Farben (Official Video)-GK5hf8ZsUr4.webm'
> [ffmpeg] Destination: Kontra K - Farben (Official Video)-GK5hf8ZsUr4.mp3
> [debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Kontra K - Farben (Official Video)-GK5hf8ZsUr4.webm' -vn -acodec libmp3lame -q:a 5 'file:Kontra K - Farben (Official Video)-GK5hf8ZsUr4.mp3'
> ERROR: audio conversion failed: "debug"
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 265, in run_ffmpeg
>     FFmpegPostProcessor.run_ffmpeg(self, path, out_path, opts)
>   File "/usr/local/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 239, in run_ffmpeg
>     self.run_ffmpeg_multiple_files([path], out_path, opts)
>   File "/usr/local/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
>     raise FFmpegPostProcessorError(msg)
> youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: "debug"
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 336, in run
>     self.run_ffmpeg(path, new_path, acodec, more_opts)
>   File "/usr/local/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 267, in run_ffmpeg
>     raise AudioConversionError(err.msg)
> youtube_dl.postprocessor.common.AudioConversionError: "debug"
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2052, in post_process
>     files_to_delete, info = pp.run(info)
>   File "/usr/local/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 339, in run
>     'audio conversion failed: ' + e.msg)
> youtube_dl.utils.PostProcessingError: audio conversion failed: "debug"

**Comment by dstftw** [comment]
Your ffmpeg is symlinked to avconv that does not support `repeat+`. Fix that.
