### ISSUE TITLE
Trouble with uninstalling the previous version of youtube-dl.

### ISSUE THREAD

**Issue by sathya-p** [rg3/youtube-dl#20216]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
I have a problem with uninstalling the previous version of youtube-dl. A very similar issue was reported here: https://github.com/rg3/youtube-dl/issues/18732

But, I don't see any answer to this question. 

I currently have Ubuntu 18.04.2 LTS installed (and not mint like in the earlier question). I have Linux Kernel: 4.15.0-45-generic  (got this from uname -a output). 

When I try to download a video, I am getting the following error: 
> $ youtube-dl https://www.youtube.com/watch?v=hzC3TJ0jYH8
[youtube] hzC3TJ0jYH8: Downloading webpage
[youtube] hzC3TJ0jYH8: Downloading video info webpage
[youtube] hzC3TJ0jYH8: Downloading js player vflX2rhq7
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1133, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1200, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

On searching for error, I realized that probably the version of youtube-dl that I am running is not updated. The version that I have installed is: 2018.12.03
> $ youtube-dl --version
2018.12.03

From this link, I have realized that I am not using the latest version: https://github.com/rg3/youtube-dl/issues/18891. I see that the latest version is: 2019.01.16

So, I tired to update using the instructions, I see here: https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl

I try to update using the inbuilt command, when I get the following message:

> $ youtube-dl --update
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.

Next, I try to uninstall using apt-get as follows:

> $ sudo apt-get remove youtube-dl 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'youtube-dl' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.

So, aptitude does not have track of youtube-dl. In this case, I think I have to manually uninstall it. Can anyone suggest how I can do this? 

Thanks a lot in advance for your suggestions. 

Sathya

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#installation, pip instructions.
