### ISSUE TITLE
ERROR: This video is unavailable. YouTube video available with internet browser.

### ISSUE THREAD

**Issue by myvarite** [rg3/youtube-dl#20234]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: ['--write-sub', '--sub-lang', 'en', '--convert-subs', 'ass', '--embed-sub', '--user-agent', 'Mozilla/5.0 (Linux; Android 7.0; SM-G892A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36', '--ffmpeg-location', 'ffmpeg.exe', '--external-downloader', 'ffmpeg.exe']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtu.be/tjA7nAHOAww']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2019.03.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-93151-gff03418348
[debug] Proxy map: {}
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\youtube.py", line 1978, in _real_extract
youtube_dl.utils.ExtractorError: This video is unavailable.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

YouTube video: 
https://youtu.be/tjA7nAHOAww

The video is available and plays without issues using an internet browser (Firefox Latest Beta), youtube-dl returns "ERROR: This video is unavailable." when trying to download.

**Comment by dstftw** [comment]
Don't touch `--user-agent`.

**Comment by remitamine** [comment]
```
youtube-dl https://youtu.be/tjA7nAHOAww
[youtube] tjA7nAHOAww: Downloading webpage
[youtube] tjA7nAHOAww: Downloading video info webpage
[download] Destination: LSD - Audio (Official Video) ft. Sia, Diplo, Labrinth-tjA7nAHOAww.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  4 14.0M    4  704k    0     0   474k      0  0:00:30  0:00:01  0:00:29  474k
```

**Comment by myvarite** [comment]
> 
> 
> Don't touch `--user-agent`.

I didn't.

**Comment by dstftw** [comment]
>[debug] User config: ['--write-sub', '--sub-lang', 'en', '--convert-subs', 'ass', '--embed-sub', **'--user-agent', 'Mozilla/5.0 (Linux; Android 7.0; SM-G892A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36'**, '--ffmpeg-location', 'ffmpeg.exe', '--external-downloader', 'ffmpeg.exe']

**Comment by myvarite** [comment]
> 
> 
> > [debug] User config: ['--write-sub', '--sub-lang', 'en', '--convert-subs', 'ass', '--embed-sub', **'--user-agent', 'Mozilla/5.0 (Linux; Android 7.0; SM-G892A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36'**, '--ffmpeg-location', 'ffmpeg.exe', '--external-downloader', 'ffmpeg.exe']
,,,
.\youtube-dl.exe -v https://youtu.be/tjA7nAHOAww
,,,
Executed from PowerShell on Windows 10 1809, no parameters added.

**Comment by dstftw** [comment]
As clearly written in the log it's in your config file.

**Comment by myvarite** [comment]
> 
> 
> As clearly written in the log it's in your config file.

I've never edited the config file, but launching youtube-dl with `--useragent default` solves the problem for me.
