### ISSUE TITLE
Unsupported URL for Tudou.com

### ISSUE THREAD

**Issue by ksy5662** [rg3/youtube-dl#2023]
Some unsupported URL for Tudou

jay-yuui-mbp:youtube-dl jcyu5662$ ./youtube-dl  -s --verbose http://www.tudou.com/albumplay/Lqfme5hSolM/sCCLYUWGm6Y.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-s', '--verbose', 'http://www.tudou.com/albumplay/Lqfme5hSolM/sCCLYUWGm6Y.html']
[debug] youtube-dl version 2013.12.20
[debug] Python version 2.7.5 - Darwin-13.0.0-x86_64-i386-64bit
[debug] Proxy map: {}
[Tudou] sCCLYUWGm6Y.html: Downloading webpage
[Youku] XNjQ5Nzk3NDgw: Downloading webpage
[Youku] XNjQ5Nzk3NDgw: Extracting information
ERROR: 抱，无法看此!
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 475, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 138, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youku.py", line 74, in _real_extract
    expected=True)
ExtractorError: \u62b1\u6b49\uff0c\u65e0\u6cd5\u89c2\u770b\u6b64\u89c6\u9891!

jay-yuui-mbp:youtube-dl jcyu5662$

**Comment by yan12125** [comment]
This Tudou video uses Youku as its backend. The Youku extractor is previously broken, while it's now fixed thanks to @PeterDing's work (#5833). This video will be supported in the next version.
