### ISSUE TITLE
Downloaded files from safaribooksonline cut off at 1:00

### ISSUE THREAD

**Issue by dryshirt** [rg3/youtube-dl#20245]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://learning.oreilly.com/videos/angular-5-formerly/9781788998437/9781788998437-video1_5']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.08
[debug] Python version 2.7.10 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Kaltura] 9781788998437-video1_5: Downloading webpage
[Kaltura] 0_1dcypn5j: Downloading video info JSON
[Kaltura] 0_1dcypn5j: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://kalhlspd-a.akamaihd.net/fhls/p/1926081/sp/192608100/serveFlavor/entryId/0_1dcypn5j/v/12/ev/14/flavorId/0_3n8l5qtg/name/a.mp4/clipTo/60000/index.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 9
[download] Destination: Editing the First App-0_1dcypn5j.mp4
[download] 100% of 4.65MiB in 00:01
[debug] ffmpeg command line: ffprobe -show_streams 'file:Editing the First App-0_1dcypn5j.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Editing the First App-0_1dcypn5j.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Editing the First App-0_1dcypn5j.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Editing the First App-0_1dcypn5j.temp.mp4'
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Videos downloaded from learning.oreilly.com are all cut off at 1 minute long; even though the videos that are being streamed are >1:00 in length. Videos that are under a minute in length download correctly. Some videos I have tried: 

1. https://learning.oreilly.com/videos/java-8-and/9780133489354/9780133489354-JFUN_BYB01 (01:15)
2. https://learning.oreilly.com/videos/angular-5-formerly/9781788998437/9781788998437-video1_5 (09:03)
3. https://learning.oreilly.com/videos/java-8-and/9780133489354/9780133489354-JFUN_BYB07 (00:57)

Of the three, only the third video is downloaded in its entirety. The first two are cut off at 1:00 in length.
There is nothing in my configuration file other than my username and password. The included log is of the attempt to download the 2nd item on the list.

**Comment by dstftw** [comment]
You did not pass authentication data.
