### ISSUE TITLE
Problem with TED

### ISSUE THREAD

**Issue by afsharsafavi** [rg3/youtube-dl#20267]
Hello
There is problem in getting video from ted.com
https://hls.ted.com/videos/PeggyAndover_Conditioning_2012E/video/1500k.m3u8?nobumpers=true&uniqueId=29d4a169?

`youtube-dl https://www.ted.com/talks/peggy_andover_the_difference_between_classical_and_operant_conditioning
[ted] peggy_andover_the_difference_between_classical_and_operant_conditioning: Downloading webpage
[ted] peggy_andover_the_difference_between_classical_and_operant_conditioning: Downloading m3u8 information
[ted] peggy_andover_the_difference_between_classical_and_operant_conditioning: Checking 600k bitrate URL
[ted] peggy_andover_the_difference_between_classical_and_operant_conditioning: Checking 64k bitrate URL
[ted] peggy_andover_the_difference_between_classical_and_operant_conditioning: Checking 180k bitrate URL
[ted] peggy_andover_the_difference_between_classical_and_operant_conditioning: Checking 320k bitrate URL
[ted] peggy_andover_the_difference_between_classical_and_operant_conditioning: Checking 450k bitrate URL
[ted] peggy_andover_the_difference_between_classical_and_operant_conditioning: Checking 950k bitrate URL
[ted] peggy_andover_the_difference_between_classical_and_operant_conditioning: Checking 1500k bitrate URL
[download] Destination: The difference between classical and operant conditioning-23841.fhls-4382.mp4
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-28)
  configuration: 
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
https://hls.ted.com/videos/PeggyAndover_Conditioning_2012E/video/1500k.m3u8?nobumpers=true&uniqueId=29d4a169: Protocol not found
Did you mean file:https://hls.ted.com/videos/PeggyAndover_Conditioning_2012E/video/1500k.m3u8?nobumpers=true&uniqueId=29d4a169?

ERROR: ffmpeg exited with code 1`

If it possible, please fix it.

**Comment by dstftw** [comment]
>https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
