### ISSUE TITLE
[France.TV] AGAIN "Unable to extract video ID"

### ISSUE THREAD

**Issue by NiesmialyGosc** [rg3/youtube-dl#20268]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
D:\videotest>youtube-dl --proxy 37.187.99.146:3128 --all-subs --convert-subs srt
-o "7717.mp4" --retries 200 --verbose https://www.france.tv/france-2/amour-gloir
e-et-beaute/913271-amour-gloire-et-beaute.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', '37.187.99.146:3128', '--all-subs', '--con
vert-subs', 'srt', '-o', '7717.mp4', '--retries', '200', '--verbose', 'https://w
ww.france.tv/france-2/amour-gloire-et-beaute/913271-amour-gloire-et-beaute.html'
]
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2019.03.01
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-89508-g1f1207145a, ffprobe N-89508-g1f1207145a
[debug] Proxy map: {'http': '37.187.99.146:3128', 'https': '37.187.99.146:3128'}
[FranceTVSite] 913271-amour-gloire-et-beaute: Downloading webpage
ERROR: Unable to extract video ID; please report this issue on https://yt-dl.org
/bug . Make sure you are using the latest version; type  youtube-dl -U  to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete o
utput.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\bu
ild\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\bu
ild\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\bu
ild\youtube_dl\extractor\francetv.py", line 280, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\bu
ild\youtube_dl\extractor\common.py", line 992, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\bu
ild\youtube_dl\extractor\common.py", line 983, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video ID; please report t
his issue on https://yt-dl.org/bug . Make sure you are using the latest version;
 type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose f
lag and include its complete output.


D:\videotest>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

The error "Unable to extract video ID" shows up again after the fix in the v2019.03.01 release..

**Comment by NiesmialyGosc** [comment]
Hi @dstftw and team, Sorry for the bother, thank you for fixing this bug! But if we could expedite the new release or if you could give me a quick guidance on how to "incorporate" the updated codes into the existing version of .exe file (by reverse compilation?) before the new release so we can start downloading an important video before it expires, that'll be much much appreciated:-)

Thank you!
Jacob

**Comment by littleboy62** [comment]
Hi.

Works with video from france.tv (thank you so much)

But **doesn't work with subdomain** (like https://education.francetv.fr/matiere/education-au-numerique/cm2/video/ajout-de-texte-creer-un-site-en-html-2-5)

did I **miss a step**?

This simple command line works great  :  `youtube-dl -o "7717.mp4" --retries 200 --verbose https://www.france.tv/france-3/soupcons/soupcons-saison-1/1049385-soupcons.html`
this simple commande line doesn"t work : : `youtube-dl.exe -o "test.mp4" --retries 200 --verbose https://education.francetv.fr/matiere/education-au-numerique/cm2/video/ajout-de-texte-creer-un-site-en-html-2-5`


I get this :
> ERROR: Unsupported URL: https://education.francetv.fr/matiere/education-au-numerique/cm2/video/ajout-de-texte-creer-un-site-en-html-2-5

ps : sorry for my bad english ^^




cya
