### ISSUE TITLE
After installation of openssl 1.1.1, youtube-dl is not working any more (ERROR: Unable to download webpage: SSL: CERTIFICATE_VERIFY_FAILED (_ssl.c:726)

### ISSUE THREAD

**Issue by Wikinaut** [rg3/youtube-dl#20276]
I installed openssl 1.1.1 and (apparently) since then, yt-dl is throwing this error for all webpages:

```
ERROR:
Unable to download webpage:
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
(caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)'),))
```

Is there a way to fix this?

Versions:
* current: OpenSSL 1.1.1b  26 Feb 2019
* previous: OpenSSL 1.1.0g  2 Nov 2017

**Comment by dstftw** [comment]
Use search.

**Comment by Wikinaut** [comment]
@dstftw  Thanks for your switft reply.

Of course, I searched before posting here. Unfortunately, there is no clear and easy solution, it still looks to me as a specific problem (most of the results speak about problems of finding the certificate bundle; I could not fix the present issue quickly other than going back to openssl 1.1.0).

Perhaps newer versions of youtube-dl will catch this problem in a different way, at the latest when openssl 1.1.1 is more widely deployed.
