### ISSUE TITLE
[soundcloud] 401 Unauthorized

### ISSUE THREAD

**Issue by ealgase** [rg3/youtube-dl#20273]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://soundcloud.com/kuzuryuu-fuyuhiko/kikuo-ft-shikabane-no-odori']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 3.6.7 (CPython) - Linux-3.14.0-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, phantomjs 2.1.1
[debug] Proxy map: {}
[soundcloud] kuzuryuu-fuyuhiko/kikuo-ft-shikabane-no-odori: Resolving id
[soundcloud] kuzuryuu-fuyuhiko/kikuo-ft-shikabane-no-odori: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/ealgase/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/ealgase/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2215, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

### Description of your *issue*, suggested solution and other information

Soundcloud download fails with 401 error (link isn't dead).

**Comment by remitamine** [comment]
```
youtube-dl https://soundcloud.com/kuzuryuu-fuyuhiko/kikuo-ft-shikabane-no-odori
[soundcloud] kuzuryuu-fuyuhiko/kikuo-ft-shikabane-no-odori: Resolving id
[soundcloud] kuzuryuu-fuyuhiko/kikuo-ft-shikabane-no-odori: Downloading info JSON
[soundcloud] 114989672: Downloading track url
[soundcloud] 114989672: Downloading m3u8 information
[soundcloud] 114989672: Downloading m3u8 information
[soundcloud] 114989672: Checking http_mp3_128_url video format URL
[soundcloud] 114989672: Checking hls_mp3_128_url video format URL
[soundcloud] 114989672: Checking hls_opus_64_url video format URL
[download] Destination: Kikuo Ft. 初音ミク Shikabane No Odori-114989672.mp3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3468k  100 3468k    0     0   671k      0  0:00:05  0:00:05 --:--:--  815k
[curl] Downloaded 3552234 bytes
[download] 100% of 3.39MiB in 00:05
```

**Comment by ealgase** [comment]
Wow, sorry about that.  youtube-dl, for some reason, didn't update properly, and I didn't check the version manually.
