### ISSUE TITLE
Fails on a certain YouTube video

### ISSUE THREAD

**Issue by Fabian42** [rg3/youtube-dl#20275]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl 3aUqTmhn-50 -v

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'3aUqTmhn-50', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.01
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.8
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 3aUqTmhn-50: Downloading webpage
[youtube] 3aUqTmhn-50: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r3---sn-4g5e6nsr.googlevideo.com/videoplayback?key=yt6&source=youtube&pl=26&mime=video%2Fmp4&keepalive=yes&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&lmt=1412909645873222&expire=1552055838&clen=227971046&initcwndbps=333750&mn=sn-4g5e6nsr%2Csn-4g5ednee&c=WEB&ipbits=0&mm=31%2C29&gir=yes&mv=m&dur=533.766&mt=1552034157&id=o-ALoRWzTtSaNT8y9Clz8cq9uR5LrD4SRXAM8jWHAAYCcO&ip=80.187.102.81&requiressl=yes&fvip=3&signature=6EABE2E390003D3E3F1318D0E3CE2E3BB6B8A9E2.7BA8FB9F41519CE07E499534CA547E53AEDBB0A9&itag=137&ei=vimCXOZzyqDWAtrnh7AF&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ms=au%2Crdu&ratebypass=yes'
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 182, in establish_connection
    raise RetryDownload(err)
RetryDownload
```

---

### Description of your *issue*, suggested solution and other information

Only [this video](https://www.youtube.com/watch?v=3aUqTmhn-50) fails. Confirmed in a browser that the URL that youtube-dl generates (https://r3---sn-4g5e6nsr.googlevideo.com/videoplayback?key=yt6&source=youtube&pl=26&mime=video%2Fmp4&keepalive=yes&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&lmt=1412909645873222&expire=1552055838&clen=227971046&initcwndbps=333750&mn=sn-4g5e6nsr%2Csn-4g5ednee&c=WEB&ipbits=0&mm=31%2C29&gir=yes&mv=m&dur=533.766&mt=1552034157&id=o-ALoRWzTtSaNT8y9Clz8cq9uR5LrD4SRXAM8jWHAAYCcO&ip=80.187.102.81&requiressl=yes&fvip=3&signature=6EABE2E390003D3E3F1318D0E3CE2E3BB6B8A9E2.7BA8FB9F41519CE07E499534CA547E53AEDBB0A9&itag=137&ei=vimCXOZzyqDWAtrnh7AF&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ms=au%2Crdu&ratebypass=yes) does indeed give a 503 error.

**Comment by dstftw** [comment]
Server side youtube issue, select another format.

**Comment by Fabian42** [comment]
If that's the solution, then youtube-dl should do it. Please reopen.
