### ISSUE TITLE
[Soundcloud] API Key Revoked

### ISSUE THREAD

**Issue by Cynosphere** [rg3/youtube-dl#20270]
youtube-dl's Soundcloud key is revoked, returning 401 Unauthorized on any attempts to download from Soundcloud.

**Comment by dstftw** [comment]
1. youtube-dl does not have any soundcloud key in the first place.
2. Everything works as expected.

**Comment by Cynosphere** [comment]
Was running older copy that used API key then (which most services probably are still are too), meaning now I have to rework my project's soundcloud functionality then...
