### ISSUE TITLE
[npo.nl] Fails to find a video stream since sometime last week.

### ISSUE THREAD

**Issue by brenthuisman** [rg3/youtube-dl#20277]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.npostart.nl/de-luizenmoeder/03-03-2019/AT_2116135', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2019.03.01
[debug] Python version 3.7.1 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[npo] AT_2116135: Downloading token
[npo] AT_2116135: Downloading player JSON
[npo] AT_2116135: Downloading hls profile JSON
[npo] AT_2116135: Downloading dash-widevine profile JSON
[npo] AT_2116135: Downloading MPD manifest
[npo] AT_2116135: Downloading dash-playready profile JSON
[npo] AT_2116135: Downloading MPD manifest
[npo] AT_2116135: Downloading smooth profile JSON
[npo] AT_2116135: Downloading ISM manifest
[npo] AT_2116135: Downloading JSON metadata
[npo] AT_2116135: Downloading token
[npo] AT_2116135: Downloading formats JSON
[npo] AT_2116135: Downloading Adaptive stream JSON
[npo] AT_2116135: Downloading Hoog stream JSON
[npo] AT_2116135: Downloading Normaal stream JSON
[npo] AT_2116135: Downloading Laag stream JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\b.huisman\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\extractor\npo.py", line 185, in _real_extract
    return self._get_info(url, video_id)
  File "c:\users\b.huisman\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\extractor\npo.py", line 249, in _get_info
    self._sort_formats(formats)
  File "c:\users\b.huisman\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\extractor\common.py", line 1305, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\b.huisman\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\extractor\npo.py", line 185, in _real_extract
    return self._get_info(url, video_id)
  File "c:\users\b.huisman\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\extractor\npo.py", line 249, in _get_info
    self._sort_formats(formats)
  File "c:\users\b.huisman\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\extractor\common.py", line 1305, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\b.huisman\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\b.huisman\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\extractor\common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "c:\users\b.huisman\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\extractor\npo.py", line 187, in _real_extract
    return self._get_old_info(video_id)
  File "c:\users\b.huisman\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\extractor\npo.py", line 456, in _get_old_info
    self._sort_formats(formats)
  File "c:\users\b.huisman\appdata\local\continuum\miniconda3\lib\site-packages\youtube_dl\extractor\common.py", line 1305, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

### Description of your *issue*, suggested solution and other information

Video's fail to be downloaded from `npo.nl`. This fails since last week when I successfully downloaded a video. In the browser the video works as usual.

**Comment by brenthuisman** [comment]
The DRM has been there for years however, for some reason that was not an issue till now.

**Comment by hay** [comment]
Yes, this has been in the news. Check out this article (in Dutch):
https://www.nu.nl/internet/5796627/npo-blokkeert-mogelijkheid-om-programmastreams-te-downloaden.html

**Comment by Reino17** [comment]
> The DRM has been there for years however, for some reason that was not an issue till now.

@brenthuisman, from the [nu.nl article](https://www.nu.nl/internet/5796627/npo-blokkeert-mogelijkheid-om-programmastreams-te-downloaden.html):
> De NPO zegt "niet te kunnen uitleggen" waarom gebruikers geen gebruik meer kunnen maken van het binnenhalen van de video's. "Als NPO vervangen we eens in de zoveel tijd verouderde systemen. **Het is mogelijk dat deze downloadtool gebruikmaakte van een oud NPO-systeem.**"

And that's the exact reason. The NPO implemented the current API (with DRM) almost 2 years ago, but only 3 weeks ago did they take the old API (partially) down/offline. That's why youtube-dl (and my tool) weren't affected until last month.  
Partially, because it appears the livestreams from NPO 1, NPO 2 and NPO 3 are still available (without DRM) using the old API.
