### ISSUE TITLE
Any way to download the subtitles without the times?

### ISSUE THREAD

**Issue by moshpirit** [rg3/youtube-dl#20272]
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I'd like to know if there could be any possible way to get just the text from the subtitles, so instead of getting:

```
00:00:16.010 --> 00:00:16.539
caption
```
I would like to get just `caption`

**Comment by Gosokan** [comment]
It's possible using regex to replace string of text. You can use this tools after subtitle downloaded:
sed (any linux distribution) or 
notepad++ (windows)

Example in sed to replacing timestamp:
`sed -E 's/[0-9]{2}:[0-9]{2}:[0-9]{2}//' subtitlefile.srt`

Of course this will leave `-->`, so you can using sed again to remove `-->`:
`sed -E 's/-->//' subtitlefile.srt`
