### ISSUE TITLE
Cannot download from --get-url for vshare.io

### ISSUE THREAD

**Issue by grill02** [rg3/youtube-dl#20288]
Vshare.io downloads work perfectly when directly using youtube-dl for downloading a specific format , say 

    youtube-dl -f 360p https://vshare.io/v/cgcccyz/width-750/height-400/6

However, if I do,
 `youtube-dl -f 360p https://vshare.io/v/cgcccyz/width-750/height-400/6 --get-url`

This output will be I.P. address dependent, so one example is 
    `https://s205.vshare.io/s,128-1000-1-1-1133993-mzzduiuqsw/186398/341700/184961/ff-310cc6fb184c61cb9bbf3023e4f2b3e7a6db0905,5c8398a7,cgcccyz_360.mp4`

Now, if I do 
    `wget https://s205.vshare.io/s,128-1000-1-1-1133993-mzzduiuqsw/186398/341700/184961/ff-310cc6fb184c61cb9bbf3023e4f2b3e7a6db0905,5c8398a7,cgcccyz_360.mp4`

I get an empty document. This is the same if aria2c or another downloader is used. However if I do 

    `youtube-dl -f 360p https://vshare.io/v/cgcccyz/width-750/height-400/6 --external-downloader aria2c`

things again work correctly.

Could this have something to do with user agent or crsf tokens?

The output of 
```
$$youtube-dl -v
[debug] System config: []
[debug] User config: [u'--external-downloader', u'aria2c', u'--hls-prefer-native']
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Python version 2.7.13 (CPython) - Linux-4.14.83+-x86_64-with-debian-9.8
```

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser

**Comment by grill02** [comment]
Ok, I tried with
`wget -U <user-agent> --load-cookies=<youtube-dl-cookies> <vshare-get-url-output>`

where user-agent and cookies came from youtube-dl (as mentioned in the link above). This did not work (zero-length file).

The reason for this is that I need to get the filesize before downloading the url. Normally, I would get the direct link via `--get-url` , then do a HEAD request on that url and check the content-length header field. In this case that field is also missing for the vshare zero length urls.

There is a separate issue for getting filesize via youtube-dl that has been open for 8 years. Is there any workaround for this particular case (360p format vshare url)
thanks

**Comment by idnsunset** [comment]
Same issue here, i could download the video via only IDM with the direct link generated by `--get-url`. I have no idea what IDM is doing internally.
