### ISSUE TITLE
Do I need Microsoft Visual C++ 2010 Redistributable Package (x86) on Win10 x64?

### ISSUE THREAD

**Issue by zervankoru** [rg3/youtube-dl#20299]
I am using latest update of Windows 10 (**x64**)
In installation instructions: https://github.com/rg3/youtube-dl#installation there is nothing about redists (i will call them redists, which means Microsoft Visual C++ 2010 Redistributable Package (x86)). So it seems that them are unnecessary. https://github.com/rg3/youtube-dl#the-exe-throws-an-error-due-to-missing-msvcr100dll it seems like I need it only than i have error like that. But at the same time (http://rg3.github.io/youtube-dl/download.html) it is required.

**Comment by dstftw** [comment]
As clearly stated by the download page you must have Microsoft Visual C++ 2010 Redistributable Package (**x86**) installed.
