### ISSUE TITLE
how to download with the hardsub caption? crunchyroll

### ISSUE THREAD

**Issue by yumi123y** [rg3/youtube-dl#20297]

**Comment by remitamine** [comment]
https://github.com/rg3/youtube-dl#subtitle-options

**Comment by Atemu** [comment]
> https://github.com/rg3/youtube-dl#subtitle-options

Those are the soft subs.

Hardsubs are separate video streams that have `-hardsub-` in their format code, take a look at `youtube-dl -F` @yumi123y .
