### ISSUE TITLE
Error with youtube-dl

### ISSUE THREAD

**Issue by frostyshield** [rg3/youtube-dl#20293]
Please follow the guide below

    You will be asked some questions and requested to provide some information, please read them carefully and answer honestly
    Put an x into all the boxes [ ] relevant to your issue (like this: [x])
    Use the Preview tab to see what your issue will actually look like

Make sure you are using the latest version: run youtube-dl --version and ensure your version is 2019.03.09. If it's not, read this FAQ entry and update. Issues with outdated version will be rejected.

    [x ] I've verified and I assure that I'm running youtube-dl 2019.03.09

Before submitting an issue make sure you have:

    [x ] At least skimmed through the README, most notably the FAQ and BUGS sections
    [ x] Searched the bugtracker for similar issues including closed ones
    [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

What is the purpose of your issue?

    [x ] Bug report (encountered problems with youtube-dl)

Site support request (request for adding support for a new site)
Feature request (request for a new functionality)
Question

    Other

The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your issue
If the purpose of this issue is a bug report, site support request or you are not completely sure provide the full verbose output as follows:

Add the -v flag to your command line you run youtube-dl with (youtube-dl -v <your command line>), copy the whole output and insert it here. It should look similar to one below (replace it with your log inserted between triple ```):

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Python version 3.6.5 (CPython) - Linux-4.15.0-23-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}

...
<end of log>

If the purpose of this issue is a site support request please provide all kinds of example URLs support for which should be included (replace following example URLs by yours):

    Single video: https://www.youtube.com/watch?v=BaW_jenozKc
    Single video: https://youtu.be/BaW_jenozKc
    Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that youtube-dl does not support sites dedicated to copyright infringement. In order for site support request to be accepted all provided example URLs should not violate any copyrights.
Description of your issue, suggested solution and other information

Explanation of your issue in arbitrary form goes here. Please make sure the description is worded well enough to be understood. Provide as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.

[2019-03-09 00:29:10.810926] ERROR: Signature extraction failed: Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1212, in _decrypt_signature
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1121, in _extract_signature_function
player_type = id_m.group('ext')
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1187, in _parse_sig_js
else:
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I even uninstalled it and reinstalled but the same issue crops up, first time its happened

This is the latest version AKA youtube-dl version 2019.03.09, which corresponds with githubs own update, This is not out of date nor has anyone instructed how to get tomorrows version which I know is time travel but still.

**Comment by dstftw** [comment]
Once again: you are using an outdated version.

**Comment by frostyshield** [comment]
http://prntscr.com/mvn8xc So the github is wrong its not version 2019.03.09?

**Comment by dstftw** [comment]
You're **not using** 2019.03.09 from the run that fails.
