### ISSUE TITLE
Youtube download fails sometimes

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#203]
I know there is another issue with this error but I think this is possibly a different situation.

This might be a weird case but occasionally when using through PHP exec the download will fail. I am not entirely sure why. The error is: ERROR: unable to download video

However it does actually download the video in full. The file is all there. There seems there is only one quality of video for this particular video because it will download the same video with worst or best format set.

Furthermore, it does not always fail. Sometimes it works. It really makes no sense to me. Other videos will work.

The command it uses is:
youtube-dl --retries 5 --ignore-errors --rate-limit 100k --no-progress --no-part --title --no-continue --format best "http://youtube.com/watch?v=JRwSk4phPLA"

**Comment by TRox1972** [comment]
This issue is very old without response. Should it be closed?
