### ISSUE TITLE
Patch: Don't show __main__.py in program help

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#20303]
`__main__.py` is shown when launching `youtube-dl` in alternative ways. This is somewhat unsightly.

```
$ alias youtube-dl='~/Downloads/youtube-dl/youtube_dl/__main__.py'
$ youtube-dl
Usage: __main__.py [OPTIONS] URL [URL...]
__main__.py: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

$ cd ~/Downloads/youtube-dl && python -m youtube_dl
Usage: __main__.py [OPTIONS] URL [URL...]
__main__.py: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```

Patch:

```
diff --git a/youtube_dl/options.py b/youtube_dl/options.py
index e7d8e89..f36677b 100644
--- a/youtube_dl/options.py
+++ b/youtube_dl/options.py
@@ -126,2 +126,3 @@ def parseOpts(overrideArguments=None):
         'conflict_handler': 'resolve',
+        'prog': 'youtube-dl'
     }
```

- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.09**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [X] Bug report (encountered problems with youtube-dl)

**Comment by dstftw** [comment]
This is expected behavior.
