### ISSUE TITLE
[vimeo:review] "ERROR: This video is protected by a password" on unprotected public videos

### ISSUE THREAD

**Issue by bugrep1** [rg3/youtube-dl#20305]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### Full Output Log

```
youtube-dl-new.exe https://vimeo.com/wayneford/review/245565471/a909d04c1a -c -i -w -f best -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vimeo.com/wayneford/review/245565471/a909d04c1a', '-c', '-i', '-w', '-f', 'best', '-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.03.09
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-83975-g6c4665d, ffprobe 4.0
[debug] Proxy map: {}
[vimeo:review] 245565471: Downloading webpage
ERROR: This video is protected by a password, use the --video-password option
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy110f8qy\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy110f8qy\build\youtube_dl\extractor\common.py", line 522, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy110f8qy\build\youtube_dl\extractor\vimeo.py", line 1004, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy110f8qy\build\youtube_dl\extractor\vimeo.py", line 997, in _get_config_url
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy110f8qy\build\youtube_dl\extractor\vimeo.py", line 76, in _verify_video_password

youtube_dl.utils.ExtractorError: This video is protected by a password, use the --video-password option
```

### Description of your *issue*, suggested solution and other information

I'm getting this error
```
ERROR: This video is protected by a password, use the --video-password option
```
when I try to download a video from any public **Vimeo Review** page that doesn't have any password protection.

On the other hand I can download same videos in a browser without any trouble using standart Vimeo UI download buttons.

**Example Vimeo Review pages:**
https://vimeo.com/wayneford/review/245565471/a909d04c1a
https://vimeo.com/user17063054/review/254564949/24379777ff
https://vimeo.com/marcusevans/review/84589794/6ac1d34578

**Comment by guysoft** [comment]
Hey, using 2019.5.11 and still getting this issue

**Comment by guysoft** [comment]
Tried using master from @Kiku-Reise , so 100% the commit is still there. I still get:
```
ERROR: This video is protected by a password, use the --video-password option
```

I recommend to reopen the bug.

**Comment by remitamine** [comment]
the commit was working before the change made by Vimeo, you can open a new issue for the new problem.
