### ISSUE TITLE
Please, add support for afreeca.com

### ISSUE THREAD

**Issue by AleXoundOS** [rg3/youtube-dl#2054]
Example: http://afbbs.afreeca.com:8080/app/read_ucc_bbs.cgi?szBjId=sogoodtt&nStationNo=55614&nBbsNo=124&nTitleNo=3448726&szSkin=

Afreeca is a Korean video streaming service. The best StarCraft: Brood War players stream there.

**Comment by yan12125** [comment]
Thanks @pmrowla (#9395), afreeca will be supported in the next version.

**Comment by AleXoundOS** [comment]
Thank you
