### ISSUE TITLE
mixcloud.com download error

### ISSUE THREAD

**Issue by ZFF85** [rg3/youtube-dl#2068]
The  download from mixcloud does not work:

[mixcloud] coen-donders-jaarmix-2013: Downloading webpage
[mixcloud] coen-donders-jaarmix-2013: Downloading cloudcast info
[mixcloud] Trying with m4a extension
ERROR: Unable to extract track url; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by szemy** [comment]
ThinkPad-T500:~/Music$ youtube-dl --verbose http://www.mixcloud.com/duhosember/ateizmus/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.mixcloud.com/duhosember/ateizmus/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.25
[debug] Python version 2.7.6 - Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, ffmpeg N-69017-gcba199b, ffprobe N-69017-gcba199b
[debug] Proxy map: {}
[mixcloud] duhosember-ateizmus: Downloading webpage
[mixcloud] duhosember-ateizmus: Checking URL 1/31 ...
[mixcloud] duhosember-ateizmus: Checking URL 2/31 ...
[mixcloud] duhosember-ateizmus: Checking URL 3/31 ...
[mixcloud] duhosember-ateizmus: Checking URL 4/31 ...
[mixcloud] duhosember-ateizmus: Checking URL 5/31 ...
[mixcloud] duhosember-ateizmus: Checking URL 6/31 ...
[mixcloud] duhosember-ateizmus: Checking URL 7/31 ...
[mixcloud] duhosember-ateizmus: Checking URL 8/31 ...
[mixcloud] duhosember-ateizmus: Checking URL 9/31 ...
[mixcloud] duhosember-ateizmus: Checking URL 10/31 ...
[mixcloud] duhosember-ateizmus: Checking URL 11/31 ...
[mixcloud] duhosember-ateizmus: Checking URL 12/31 ...
[mixcloud] duhosember-ateizmus: Checking URL 13/31 ...
[mixcloud] duhosember-ateizmus: Checking URL 14/31 ...
WARNING: unable to extract like count; please report this issue on http://yt-dl.org/bug
WARNING: unable to extract play count; please report this issue on http://yt-dl.org/bug
ERROR: Unable to extract upload date; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 613, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 266, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mixcloud.py", line 96, in _real_extract
    webpage, 'upload date'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 522, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract upload date; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
@szemy see #4784. In general [it's better to open a new issue](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs), it's easier to keep track of them.

**Comment by szemy** [comment]
Ok, sorry for that. Should I open a new one?

**Comment by jaimeMF** [comment]
No, one is enough :). The problem is that comments in closed issues tend to be lost, if you open a duplicated issue there's no problem, we will just tell you.
You can subscribe to the issue to recieve a notification when it's fixed.
