### ISSUE TITLE
Partial file overwritten/truncated on resume failure using --continue --no-overwrites.

### ISSUE THREAD

**Issue by Warr1024** [rg3/youtube-dl#2073]
## Steps to reproduce:
1. Using version eadaf08c1670d2fc9a2078faca95fbc49d6a5af0 of youtube-dl from github.
2. Attempt to resume a partially-downloaded youtube video using --continue --no-overwrites.

Usually, the download resumes correctly without a problem.  However, sometimes you will get an error message like:

```
[download] Resuming download at byte ########
[download] Unable to resume
```
## Actual behavior:

Download is restarted from 0, **_truncating**_ the partially-downloaded file.
## Expected behavor:

Any of the following behaviors would probably be reasonable:
1. Abort the download with an error.  The user is left to his/her own devices with the partial file.
2. Wait a short period and retry to resume, up to a certain number of times.
3. Start downloading the file from zero, but do NOT overwrite the original.  When the resumed download passes the resume point of the partial file, begin appending new content to the end of the existing file.  Input before the resume point can be discarded, or _optionally_ compared with the existing file (an error could be raised on mismatch).

**Comment by rhnvrm** [comment]
:-1: can't reproduce on youtube-dl 2016.07.17

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
