### ISSUE TITLE
Handling deleted videos in a play-list.

### ISSUE THREAD

**Issue by ProgramErgoSum** [rg3/youtube-dl#2076]
Hi,
A Happy 2014 to you !!

youtube-dl does not download a video that is deleted from a play-list; which is fine. But, I wonder, what is the source of all videos in the play-list that youtube-dl accesses ?

I came across this YouTube API (https://developers.google.com/youtube/2.0/developers_guide_protocol_playlists#Retrieving_a_playlist) to retrieve a public play-list. In result of this API, the `yt:position` tag does not appear for the missing video. But, youtube-dl is not only able to get the video ID, but, reports an error that it is unable to download. This is good; but obviously, youtube-dl is looking for video ID in the play-list some where else. Where ?

Example: 
Playlist URL: http://www.youtube.com/playlist?list=PLAD5B880806EBE0A4
Missing video numbers: 33 and 34.
Feed URL: https://gdata.youtube.com/feeds/api/playlists/PLAD5B880806EBE0A4?start-index=26&max-results=25&v=2
XPath (does not return results):

``` xml
/a:feed/a:entry[yt:position=33]/a:title/text()
/a:feed/a:entry[yt:position=34]/a:title/text()
```

youtube-dl reports that video # 33 cannot be downloaded. The YouTube web-page itself does show that the video was deleted.

**Comment by kirbykirbyyt** [comment]
https://www.youtube.com/watch?v=1yVQR9jSnws&list=PLb2_ivEn46OyT7VXYZFhpjV9MJyIW1DBz&index=1
https://www.youtube.com/watch?v=QdEY1IR8Y60&list=PLb2_ivEn46OyT7VXYZFhpjV9MJyIW1DBz&index=2
https://www.youtube.com/watch?v=n-NKYxJiamc&list=PLb2_ivEn46OyT7VXYZFhpjV9MJyIW1DBz&index=3
https://www.youtube.com/watch?v=dUjDoXjQVbk&index=1&list=PLb2_ivEn46OzQLG_7pov0-3bg05ihJiWK
SOMEBODY PLEASE RECOVER THESE!!!
