### ISSUE TITLE
niconico is broken

### ISSUE THREAD

**Issue by tewe** [rg3/youtube-dl#2087]
Downloading user info fails, probably because the API changed. Can't debug that as I don't have Flash.

You can still get videos if you fix the error handling: line 111 in niconico.py has to catch ExtractorError instead of the various low-level exceptions, as those were already converted in _request_webpage.

**Comment by pascalbrax** [comment]
Looks like the niconico extractor still works with *sm* URLS but not with the new *so* ones.

Example:
`$ youtube-dl http://www.nicovideo.jp/watch/sm25738069` WORKS!
`$ youtube-dl http://www.nicovideo.jp/watch/so25716969` DOESN'T WORK

**Comment by jaimeMF** [comment]
@pascalbrax it's unrelated, please open a new issue. Note that in a browser you get redirected to http://www.nicovideo.jp/watch/1425530678, which does work.

**Comment by pascalbrax** [comment]
@jaimeMF My bad. Yes it works... And I'm kind of confused because I've tested it several times and it didn't work. Oh well, nevermind then. :+1:

**Comment by jaimeMF** [comment]
@pascalbrax Note that the original url http://www.nicovideo.jp/watch/so25716969 doesn't work.

**Comment by yan12125** [comment]
All videos mentioned above works with the latest version. Closing.
