### ISSUE TITLE
Download playlist with backwards numeration

### ISSUE THREAD

**Issue by vpotonya** [rg3/youtube-dl#2090]
Is it possible to implement feature to download playlist with backwards numeration? When I start downloading playlist with the option "-A", youtube_dl sets 00001 to the newest movie ... and 000XX to the oldest one.
It is inconvenient for playlists that are updated very often.
Thank you

**Comment by weedy** [comment]
--playlist-reverse

**Comment by vitorgalvao** [comment]
This issue can be closed. As @weedy mentioned, `--playlist-reverse` does it.

**Comment by yan12125** [comment]
Thanks @vitorgalvao!
