### ISSUE TITLE
BBC iPlayer support

### ISSUE THREAD

**Issue by l0b0** [rg3/youtube-dl#2094]
The BBC iPlayer Downloads only supports Windows and Macintosh. It would be nice if `youtube-dl` filled in that obvious gap.

     youtube_dl.utils.ExtractorError: Unsupported URL: http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf

**Comment by dstftw** [comment]
BBC iPlayer is supported in the latest version. Closing.
