### ISSUE TITLE
Video format codes are not listed anywhere

### ISSUE THREAD

**Issue by jameshfisher** [rg3/youtube-dl#21]
The --help text refers to "video format codes", but nowhere are these listed or defined.  It gives the example of "17" as a format code (for the mobile version), which seems arbitrary to me.  I couldn't find the codes in the source.  My expectation of a "format code" would be something like "720p", "480p", "320p", or "240p".  Do the used numeric codes correspond to these, and if so how?

**Comment by mevsme** [comment]
Still actual.

**Comment by dstftw** [comment]
```
-F, --list-formats               List all available formats
```

**Comment by XMB5** [comment]
Here are the formats: (https://github.com/rg3/youtube-dl/blob/3961c6cb9d3a1c30fe31db774b0809095952f1bd/youtube_dl/extractor/youtube.py#L367-L465)
