### ISSUE TITLE
Can't download from www.tv4.se

### ISSUE THREAD

**Issue by savioramos** [rg3/youtube-dl#2103]
The verbose output:

youtube-dl --verbose http://www.tv4.se/kalla-fakta/klipp/kalla-fakta-5-english-subtitles-2491650
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.tv4.se/kalla-fakta/klipp/kalla-fakta-5-english-subtitles-2491650']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.01.05.6
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.3
[debug] Proxy map: {}
[generic] kalla-fakta-5-english-subtitles-2491650: Requesting header
WARNING: Falling back on generic information extractor.
[generic] kalla-fakta-5-english-subtitles-2491650: Downloading webpage
[generic] kalla-fakta-5-english-subtitles-2491650: Extracting information
ERROR: Unsupported URL: http://www.tv4.se/kalla-fakta/klipp/kalla-fakta-5-english-subtitles-2491650; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 489, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 150, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 331, in _real_extract
    raise ExtractorError(u'Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.tv4.se/kalla-fakta/klipp/kalla-fakta-5-english-subtitles-2491650; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by naglis** [comment]
Support for tv4.se/tv4play.se has been added and should be available in the next release of youtube-dl. Thanks for the report.

**Comment by jeekl** [comment]
I just tried this with 2016.09.11 but this does not seem to work.

```
% youtube-dl --verbose http://www.tv4.se/kalla-fakta/klipp/kalla-fakta-5-english-subtitles-2491650
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.tv4.se/kalla-fakta/klipp/kalla-fakta-5-english-subtitles-2491650']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.11.1
[debug] Python version 2.7.12 - Linux-4.7.3-040703-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 3.1.3-1, avprobe 3.1.3-1, ffmpeg 3.1.3-1, ffprobe 3.1.3-1, rtmpdump 2.4
[debug] Proxy map: {}
[TV4] 2491650: Downloading video info JSON
[TV4] 2491650: Downloading sources JSON
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Invoking downloader on u'https://progdwnl.tv4.se/mp4root/2013-11-25/kalla_fakta_giftvin_engt_2491650_T6MP425_.mp4?token=1473850470_b9f1844515e6c421c2e3e24ac6e69b6f'
ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1696, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1638, in dl
    return fd.download(name, info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 354, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1998, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1004, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by yan12125** [comment]
@jeekl Could you open a new issue for that?

**Comment by jeekl** [comment]
Sure thing.
