### ISSUE TITLE
DASH muxing behavior inconsistent with default --keep-video behavior

### ISSUE THREAD

**Issue by RickyRomero** [rg3/youtube-dl#2108]
When downloading a DASH video from YouTube, the muxing behavior leaves behind the original media files after muxing – with the format codes appended – next to the final muxed file from ffmpeg.

This is inconsistent with youtube-dl's help, where the following option is presented under *Post-processing Options*:

<pre>    -k, --keep-video           keeps the video file on disk after the post-processing; the video is erased by default</pre>

To be consistent with existing conventions, the source DASH files should be erased after muxing has successfully completed.

**Comment by jaimeMF** [comment]
It has been working for a while, so I'm closing the issue.

@weedy open a new issue for that.

**Comment by jaimeMF** [comment]
@weedy videos that have already been downloaded will be detected in the next version.
