### ISSUE TITLE
Stream to vlc

### ISSUE THREAD

**Issue by jcherqui** [rg3/youtube-dl#2124]
Streaming video to vlc.

**Comment by pvdl** [comment]
The "point" is to use youtube-dl as a wrapper for streams which uses a token.
@nodiscc mad a really a nice solution to manage that!

**Comment by Avbrella** [comment]
I second @nodiscc regarding the --stream option, and had a particular use-case in mind.

**Comment by walidsa3d** [comment]
A --stream option would be great

**Comment by Vrihub** [comment]
I'm trying the "-o -" solution, but with some websites (e.g. periscope) it doesn't work: I get the stream saved to a file named "-". Is this expected behaviour (due to limitations of some website or video format), or is it a bug in that particular extractor?

**Comment by moorchegue** [comment]
+1 to the last question

**Comment by yan12125** [comment]
This feature indeed needs some extra codes for live streams. (m3u8 from periscope, etc.)

**Comment by remitamine** [comment]
this patch will make them work as well:
```diff
diff --git a/youtube_dl/downloader/external.py b/youtube_dl/downloader/external.py
index 30277dc..cda39fe 100644
--- a/youtube_dl/downloader/external.py
+++ b/youtube_dl/downloader/external.py
@@ -225,7 +225,7 @@ class FFmpegFD(ExternalFD):
 
         args += ['-i', url, '-c', 'copy']
         if protocol == 'm3u8':
-            if self.params.get('hls_use_mpegts', False):
+            if self.params.get('hls_use_mpegts', False) or tmpfilename == '-':
                 args += ['-f', 'mpegts']
             else:
                 args += ['-f', 'mp4', '-bsf:a', 'aac_adtstoasc']
@@ -235,7 +235,10 @@ class FFmpegFD(ExternalFD):
             args += ['-f', EXT_TO_OUT_FORMATS.get(info_dict['ext'], info_dict['ext'])]
 
         args = [encodeArgument(opt) for opt in args]
-        args.append(encodeFilename(ffpp._ffmpeg_filename_argument(tmpfilename), True))
+        if tmpfilename == '-':
+            args.append('pipe:1')
+        else:
+            args.append(encodeFilename(ffpp._ffmpeg_filename_argument(tmpfilename), True))
 
         self._debug_cmd(args)
```

**Comment by besweeet** [comment]
Any updates about this? Would love to get 60FPS livestreams pumped directly into VLC, as livestreamer doesn't support DASH.

**Comment by yan12125** [comment]
DASH should be supported. Any problems/errors?

**Comment by besweeet** [comment]
For livestreamer? I'm just not sure of any way to select qualities other than the usual "audio_webm, audio_mp4, 144p (worst), 240p, 360p, 720p (best)" options.

**Comment by yan12125** [comment]
Which video are you trying? Please give a concrete URL.

**Comment by besweeet** [comment]
Here's one 720p60 example: https://www.youtube.com/watch?v=brDB5lk3G3A
And a 1080p60 example: https://www.youtube.com/watch?v=eXQ2ZZcTMpc

**Comment by yan12125** [comment]
I was wrong - such DASH support is not implemented yet. Please follow #5563 instead for that.

**Comment by baptx** [comment]
Is there no option to stream and save the video at the same time? The output .mp4.part files can't be played while there are downloaded so I have to use a hack like this: `youtube-dl "https://www.youtube.com/c/FRANCE24English/live" -o - | cat - > replay.mp4`

**Comment by yan12125** [comment]
> The output .mp4.part files can't be played

Could you try: ```--hls-use-mpegts```

**Comment by baptx** [comment]
@yan12125 thanks, it works but I would like the output file named "replay.mp4" instead of "replay.mp4.part" while I stream. Is there a way to do this?

**Comment by tuxayo** [comment]
@baptx Thanks, that what I needed, it seems that your solution is the only one that:
- downloads the audio and video at the same time which makes it usable before it finishes downloading (`--hls-use-mpegts --no-part` doesn't)
- creates a file so one can move forward and backward in the video (`youtube-dl URL_HERE -o - | vlc -` doesn't )

It can be shortened to:
`youtube-dl https://www.youtube.com/watch?v=oHg5SJYRHA0 -o - > replay.mp4`

Does anyone know how to not have to start VLC separately while keeping the two beforementioned properties?

**Comment by yan12125** [comment]
Try this: ```youtube-dl URL_HERE -o - | tee replay.mp4 | vlc - ```

**Comment by tuxayo** [comment]
@yan12125 VLC is still reading only from stdin and therefore can't move forward and backward in the video.

**Comment by yan12125** [comment]
@tuxayo I see your problem. Such a need is complicated and I guess a script is inevitable:
```Python
import subprocess
import youtube_dl


player_run = False
p = None


def hook(status):
    global player_run, p

    if not player_run:
        player_run = True
        p = subprocess.Popen(['mpv', status['filename']])


opts = {
    'format': 'best',
    'nopart': True,
    'progress_hooks': [hook],
    'verbose': True,
}

with youtube_dl.YoutubeDL(opts) as ydl:
    ydl.download(['https://www.youtube.com/watch?v=oHg5SJYRHA0'])

p.wait()
```

**Comment by tuxayo** [comment]
@yan12125 Awesome thanks! Great to see that youtube_dl is so flexible.

**Comment by ritiek** [comment]
@yan12125 This works good for YouTube but not for other sites like hotstar (requiring multiple HLS requests). I can't pass this stream to mpv with your code:
```
ydl.download(['http://www.hotstar.com/sports/cricket/vivo-ipl-2018/sunrisers-hyderabad-vs-chennai-super-kings-m186521/match-highlights/calm-csk-clip-soaring-srhs-wings/2001612550'])
```

However, mpv (youtube-dl backend) works perfectly fine and I am able to seek video too:
```
mpv http://www.hotstar.com/sports/cricket/vivo-ipl-2018/sunrisers-hyderabad-vs-chennai-super-kings-m186521/match-highlights/calm-csk-clip-soaring-srhs-wings/2001612550
```

But problem is that this works only for mpv specifically. I can't get this to work with other players like vlc or mplayer.

**Comment by siutin** [comment]
Hi everyone, I wondering if it is possible to stream a playlist?

**Comment by j3kyl** [comment]
@siutin Mpv is able to stream playlist

**Comment by andriyor** [comment]
```shell
function ytvlc() {
    URLS=(${(ps:\n:)"$(youtube-dl "$1" --get-url)"})
    vlc "${URLS[1]}" --input-slave "${URLS[2]}"
}
```

**Comment by jtojnar** [comment]
This [lua script](https://github.com/mjasny/vlc-youtubeDL) allows opening YouTube videos in vlc directly. It should to be installed `~/.local/share/vlc/lua/playlist/` and it just seems to work.
