### ISSUE TITLE
Lynda Member only video download

### ISSUE THREAD

**Issue by piyushverma** [rg3/youtube-dl#2125]
I just see great feature in youtube-dl. it allow to download from lynda.com.

But if video are paid it give message "Video %s is only available for members' % video_id"

Would it be possible to get userName and password in shell and login and download those video ?

**Comment by aimkeepachieve** [comment]
From another forum, I find the following method to download Lynda videos:

"One of my friends recommends me to use Allavsoft download Lynda course.

After have a try, it really works great and can batch download lynda course, videos to MP4, MOV, AVI, WMV, 3GP etc on Mac or Windows at http://www.allavsoft.com/how-to/lynda-video-downloader.html "
