### ISSUE TITLE
Support crackle.com / comediansincarsgettingcoffee.com

### ISSUE THREAD

**Issue by canavan** [rg3/youtube-dl#2136]
I'd appreciate if support for crackle.com could be added. It's used e.g. on comediansincarsgettingcoffee.com

youtube-dl --verbose http://comediansincarsgettingcoffee.com/carl-reiner-mel-brooks-i-want-sandwiches-i-want-chicken
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://comediansincarsgettingcoffee.com/carl-reiner-mel-brooks-i-want-sandwiches-i-want-chicken']
[debug] Encodings: locale 'ISO8859-1', fs 'ISO8859-1', out 'ISO8859-1', pref: 'ISO8859-1'
[debug] youtube-dl version 2014.01.08
[debug] Python version 2.7.6 - IRIX64-6.5-IP35-mips-n32bit-ELF
[debug] Proxy map: {}
[generic] carl-reiner-mel-brooks-i-want-sandwiches-i-want-chicken: Requesting header
WARNING: Falling back on generic information extractor.
[generic] carl-reiner-mel-brooks-i-want-sandwiches-i-want-chicken: Downloading webpage
[generic] carl-reiner-mel-brooks-i-want-sandwiches-i-want-chicken: Extracting information
ERROR: Unsupported URL: http://comediansincarsgettingcoffee.com/carl-reiner-mel-brooks-i-want-sandwiches-i-want-chicken; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/extractor/common.py", line 155, in extract
    return self._real_extract(url)
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/extractor/generic.py", line 346, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://comediansincarsgettingcoffee.com/carl-reiner-mel-brooks-i-want-sandwiches-i-want-chicken; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

 youtube-dl --verbose 'http://www.crackle.com/p/cracklePlayer.swf?id=2488037&ap=0&site=440'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.crackle.com/p/cracklePlayer.swf?id=2488037&ap=0&site=440']
[debug] Encodings: locale 'ISO8859-1', fs 'ISO8859-1', out 'ISO8859-1', pref: 'ISO8859-1'
[debug] youtube-dl version 2014.01.08
[debug] Python version 2.7.6 - IRIX64-6.5-IP35-mips-n32bit-ELF
[debug] Proxy map: {}
[generic] cracklePlayer: Requesting header
WARNING: Falling back on generic information extractor.
[generic] cracklePlayer: Downloading webpage
[generic] cracklePlayer: Extracting information
ERROR: Unsupported URL: http://www.crackle.com/p/cracklePlayer.swf?id=2488037&ap=0&site=440; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/extractor/common.py", line 155, in extract
    return self._real_extract(url)
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/extractor/generic.py", line 346, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.crackle.com/p/cracklePlayer.swf?id=2488037&ap=0&site=440; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
Works with latest version. Closing.
