### ISSUE TITLE
Add support for Indavideo (ERROR: Unsupported URL: http://indavideo.hu/...)

### ISSUE THREAD

**Issue by roadside** [rg3/youtube-dl#2147]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://indavideo.hu/video/Igy_keszul_egy_klasszikus_gitar?token=ce8d7e2ad0301a2f6bee2a441ae72948']
[debug] Encodings: locale 'cp1250', fs 'mbcs', out 'cp852', pref: 'cp1250'
[debug] youtube-dl version 2014.01.08
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] Igy_keszul_egy_klasszikus_gitar: Requesting header
[redirect] Following redirect to http://indavideo.hu/video/Igy_keszul_egy_klassz
ikus_gitar?token=ce8d7e2ad0301a2f6bee2a441ae72948
[generic] Igy_keszul_egy_klasszikus_gitar?token=ce8d7e2ad0301a2f6bee2a441ae72948
: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Igy_keszul_egy_klasszikus_gitar?token=ce8d7e2ad0301a2f6bee2a441ae72948
: Downloading webpage
[generic] Igy_keszul_egy_klasszikus_gitar?token=ce8d7e2ad0301a2f6bee2a441ae72948
: Extracting information
ERROR: Unsupported URL: http://indavideo.hu/video/Igy_keszul_egy_klasszikus_gitar?token=ce8d7e2ad0301a2f6bee2a441ae72948; please report this issue on https://yt
-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its
 complete output. Make sure you are using the latest version; type  youtube-dl -
U  to update.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 493, in extract_info
  File "youtube_dl\extractor\common.pyo", line 155, in extract
  File "youtube_dl\extractor\generic.pyo", line 346, in _real_extract
ExtractorError: Unsupported URL: http://indavideo.hu/video/Igy_keszul_egy_klassz
ikus_gitar?token=ce8d7e2ad0301a2f6bee2a441ae72948; please report this issue on h
ttps://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and in
clude its complete output. Make sure you are using the latest version; type  you
tube-dl -U  to update.

**Comment by nyuszika7h** [comment]
I just found this, it may be helpful: https://github.com/nXu/indadl

**Comment by nyuszika7h** [comment]
This seems very easy. Basically just get the embed URL from `<link rel="video_src" />`, pass the hash at the end to `http://amfphp.indavideo.hu/SYm0json.php/player.playerHandler.getVideoData/<hash>`, and take `video_url` from the resulting JSON.

**Comment by dstftw** [comment]
indavideo.hu will be supported in the next version.
