### ISSUE TITLE
SITE REQUEST: ctvnews.ca

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#2156]
http://www.ctvnews.ca/

specific video example:
http://www.ctvnews.ca/video?playlistId=1.1640035

if possible would probably also work for:
http://www.ctv.ca/video/player?vid=273517

Thanks in advance....

**Comment by Burglory** [comment]
Still no support I guess?

**Comment by TRox1972** [comment]
To developers:

The content is stored on 9c9media.com. The url for the f4m manifest for the first url is `http://capi.9c9media.com/destinations/ctvnews_web/platforms/desktop/contents/274542/contentpackages/217700/stacks/303107/manifest.f4m`.

The f4m urls are in the form `http://capi.9c9media.com/destinations/ctvnews_web/platforms/desktop/contents/<defaultClipId>/contentpackages/<id_1>/stacks/<id_2>/manifest.f4m`

The `defaultClipId` can be found on the line
`jQuery(document).bind('isDone.initPlayerVidNav', function() { outputLog("ETS", "About to call initPlayer()"); initPlayer(869797); });`

 in the site-source. I've not been able to find `id_1` nor `id_2`. But you should be able to if you debug the JS-code.

**Comment by remitamine** [comment]
> in the site-source. I've not been able to find id_1 nor id_2. But you should be able to if you debug the JS-code.

`id_1` -> `contentpackage_id` extracted from http://capi.9c9media.com/destinations/ctvnews_web/platforms/desktop/contents/274542/contentpackages
`id_2` -> `stack_id` extracted from http://capi.9c9media.com/destinations/ctvnews_web/platforms/desktop/contents/274542/contentpackages/217700/stacks
there are other formats by changing the ext:
- `m3u8`: m3u8 manifest.
- `rtmp`: rtmp format.
- `pd`: progressive url(direct link).

**Comment by TRox1972** [comment]
thanks for info @remitamine. are you working on an extractor for the site?

**Comment by remitamine** [comment]
i was working on ctv but for some reason i coudn't access most of the videos because of geo restriction.
this video from ctv news is not geo restricted if i find other non geo restricted videos i will add an extractor.

**Comment by RingoTheDog** [comment]
According to "WebPageTest.org"...this page is not geo-restricted:
http://www.ctv.ca/video/player?vid=706966

...also pls note: ctv.ca is part of BellMedia:  https://github.com/rg3/youtube-dl/issues/4077

thanks
Ringo
