### ISSUE TITLE
[site request] imgur.com albums/images

### ISSUE THREAD

**Issue by nodiscc** [rg3/youtube-dl#2157]
Hi, thanks for your greaat work on youtube-dl. I use it daily and absolutely love it.

Would it be desirable to add support for http://imgur.com album downloads? There's a python script at https://github.com/alexgisby/imgur-album-downloader that does exactly this, I would like it to be added to youtube-dl (it already supports Flickr albums, so why not).

The other way to download imgur albums is to add `/zip` at the end of the album url (but it doesnt save bandwith as pngs/jpgs are already compressed formats, and draws the host's CPU resources, and you have to extract zipped files after download in order to view them).

Support for individual images (images that are not from an album) would be nice too. What do you think?

Thanks again

**Comment by EvanCarroll** [comment]
I don't believe it's true that you can merely add `/zip`, for example.

    https://imgur.com/r/HistoryPorn

How do I download that. It would be nice to feed that into `youtube-dl`
