### ISSUE TITLE
Downloads all pages of the playlist even though only the first is needed

### ISSUE THREAD

**Issue by rtega** [rg3/youtube-dl#2175]
I was wondering whether youtube-dl can't be more smart when using playlist-start and playlist-end. When using with playlists like http://www.youtube.com/user/ANNnewsCH/videos it first downloads all ids, even though there are thousands, before it finally decides on using only the first 10. Is it not possible to only download the ids needed? The same thing happens with long playlists.

**Comment by cedricvanrompay** [comment]
We are more than a year later and the problem still exists it seems, at least I'm having it on a dailymotion playlist:

```
$ youtube-dl --playlist-end 4 http://www.dailymotion.com/user/libezap/1
[dailymotion:user] libezap: Downloading webpage
[dailymotion:user] libezap: Downloading page 1
[dailymotion:user] libezap: Downloading page 2
[dailymotion:user] libezap: Downloading page 3
[dailymotion:user] libezap: Downloading page 4
[dailymotion:user] libezap: Downloading page 5
[dailymotion:user] libezap: Downloading page 6
[dailymotion:user] libezap: Downloading page 7
[dailymotion:user] libezap: Downloading page 8
[dailymotion:user] libezap: Downloading page 9
[dailymotion:user] libezap: Downloading page 10
^C
ERROR: Interrupted by user
```

Note: There are more than 150 pages on this playlist ...

**Comment by jaimeMF** [comment]
@cedricvanrompay in the next version it will only download the required pages for dailymotion playlists and users, thanks for the report.

@rtega YouTube playlists are also optimized now, therefore I'm closing the issue.
