### ISSUE TITLE
Failed to download from the New Yankee Workshop website

### ISSUE THREAD

**Issue by Stormthirst** [rg3/youtube-dl#2176]
youtube-dl is up-to-date (2014.01.17.2)

youtube-dl -verbose -r 1m "http://www.newyankee.com/index.php?id=56#ecwid:category=0&mode=product&product=7916659"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--max-quality', '37', '--restrict-filenames', '-o', '%(title)s.%(ext)s', '--retries=20', '-verbose', '-r', '1m', 'http://www.newyankee.com/index.php?id=56#ecwid:category=0&mode=product&product=7916659']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.01.17.2
[debug] Python version 2.7.3 - Linux-3.2.0-58-generic-pae-i686-with-Ubuntu-12.04-precise
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.newyankee.com/index.php?id=56#ecwid:category=0&mode=product&product=7916659; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 155, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 346, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.newyankee.com/index.php?id=56#ecwid:category=0&mode=product&product=7916659; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Thanks - and keep up the good work!

**Comment by dstftw** [comment]
Works fine with latest version (2016.05.21.2).
