### ISSUE TITLE
[youtube] 1080p DASH merging problem.

### ISSUE THREAD

**Issue by BlindB0** [rg3/youtube-dl#2177]
youtube-dl --verbose -f 137+172 http://www.youtube.com/watch?v=XSGBVzeBUbk
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-f', '137+172', 'http://www.youtube.com/watch?v=XSGBVzeBUbk']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.01.17.2
[debug] Python version 2.7.5+ - Linux-3.11.0-15-generic-i686-athlon-with-Ubuntu-13.10-saucy
[debug] Proxy map: {}
[youtube] Setting language
[youtube] XSGBVzeBUbk: Downloading webpage
[youtube] XSGBVzeBUbk: Downloading video info webpage
[youtube] XSGBVzeBUbk: Extracting video information
[download] Destination: Big Buck Bunny animation (1080p HD)-XSGBVzeBUbk.f137.mp4
[download] 100% of 181.45MiB in 00:16
[download] Destination: Big Buck Bunny animation (1080p HD)-XSGBVzeBUbk.f172.webm
[download] 100% of 11.91MiB in 00:01
[debug] ffmpeg command line: avconv -y -i 'Big Buck Bunny animation (1080p HD)-XSGBVzeBUbk.f137.mp4' -i 'Big Buck Bunny animation (1080p HD)-XSGBVzeBUbk.f172.webm' -c copy 'Big Buck Bunny animation (1080p HD)-XSGBVzeBUbk.mp4'
.....
size of resulting files:
190258874 Big Buck Bunny animation (1080p HD)-XSGBVzeBUbk.f137.mp4
12491623 Big Buck Bunny animation (1080p HD)-XSGBVzeBUbk.f172.webm
12725882 Big Buck Bunny animation (1080p HD)-XSGBVzeBUbk.mp4
Size of resulting mp4 near exact as size of webm sound file.
Video did not include during merging files, in mp4 file only audio.
Because of error in video f137.mp4 file/
Downloaded f137.mp4 video file without index, so videoplayer cannot jump forward (mplayer), vlc cannot play this video at all. In player info:
Video Resolution 1920 x 1080
Aspect ratio 1.77778
Format H264
Bitrate 0 kbps
Frames per second 24.000
Selected codec ffh264

**Comment by dstftw** [comment]
Update avconv.
