### ISSUE TITLE
Support BBC downloads?

### ISSUE THREAD

**Issue by KeithCu** [rg3/youtube-dl#2184]
I tried to use youtube-dl to download from the BBC site and it didn't work. Can you fix? 
youtube-dl --verbose http://www.bbc.co.uk/programmes/p01q7wz1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.bbc.co.uk/programmes/p01q7wz1']
[debug] Encodings: locale 'UTF-8', fs 'utf-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.01.17.2
[debug] Python version 3.3.3 - Linux-3.12.7-2-ARCH-x86_64-with-arch-Arch-Linux
[debug] Proxy map: {}
[generic] p01q7wz1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] p01q7wz1: Downloading webpage
[generic] p01q7wz1: Extracting information
ERROR: Unsupported URL: http://www.bbc.co.uk/programmes/p01q7wz1; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.3/site-packages/youtube_dl/extractor/common.py", line 155, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.3/site-packages/youtube_dl/extractor/generic.py", line 346, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: http://www.bbc.co.uk/programmes/p01q7wz1; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by Mygod** [comment]
Can't download videos in events.

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--proxy', u'127.0.0.1:8887', u'-f',
u'bestvideo+bestaudio', u'--write-sub', u'--external-downloader', u'aria2-1.20.0
-win-64bit-build1\\aria2c', u'--external-downloader-args', u'-s16 -k1M -x16', u'
--ffmpeg-location', u'G:\\Software\\ffmpeg\\bin\\ffmpeg.exe', u'http://www.bbc.c
o.uk/events/ebgv2m#b07jl8n5']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-68289-g208c03a, ffprobe N-68289-g208c03a
[debug] Proxy map: {u'http': u'127.0.0.1:8887', u'https': u'127.0.0.1:8887'}
[bbc] ebgv2m: Downloading webpage
ERROR: Unable to extract playlist data; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 666, in extract_info
  File "youtube_dl\extractor\common.pyo", line 315, in extract
  File "youtube_dl\extractor\bbc.pyo", line 876, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 610, in _search_regex
RegexNotFoundError: Unable to extract playlist data; please report this issue on
 https://yt-dl.org/bug . Make sure you are using the latest version; type  youtu
be-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and incl
ude its complete output.
```
