### ISSUE TITLE
Support ffmpeg's duration and position for live streams

### ISSUE THREAD

**Issue by amq** [rg3/youtube-dl#2213]
I have encountered an issue while recording a youtube live stream. Because of some youtube or broadcaster problems the time can jump from 00:28:03.36 to, say, 20:00:01.20. The time always jumps for at least 10 hours. It is also stream-independent. One more interesting thing: the bitrate drops at this point significantly, it looks like only audio is being recorded.

frame=40145 fps= 24 q=-1.0 size=  238241kB time=00:28:03.36 bitrate=1159.4kbits/
frame=40145 fps= 24 q=-1.0 size=  238241kB time=20:00:01.20 bitrate=153.4kbits/

It would be wonderful if you could solve this issue, but it's probably difficult to find the cause, so I suggest you to add an option to include ffmpeg's -t and -to flags. This way I could set the duration limit to 1 hour, forcing ffmpeg to mux the file after the jump occurs (or 1 hour passes).

**Comment by dirkf** [comment]
Especially during [post-production](https://www.google.com/url?q=https://www.screenskills.com/job-profiles/browse/post-production), it's conventional to use a base time of 10:00:00.000, so I'm told. If the provider fails to re-base some part of the media offering, this weird jump can occur.
