### ISSUE TITLE
Google Drive Support Request (Similar to YouTube?)

### ISSUE THREAD

**Issue by innocenceisdeath** [rg3/youtube-dl#2231]
Hi,

Please would you add support for Google Drive video previews. It looks like it may operate similar to YouTube.

$ youtube-dl --verbose 'https://docs.google.com/file/d/0Bwi6Ha03myF1aGVweVBoemdlU3c/preview?pli=1'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://docs.google.com/file/d/0Bwi6Ha03myF1aGVweVBoemdlU3c/preview?pli=1']
[debug] Encodings: locale 'UTF-8', fs 'utf-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.01.22
[debug] Python version 3.3.3 - Linux-3.12.8-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[generic] preview?pli=1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] preview?pli=1: Downloading webpage
[generic] preview?pli=1: Extracting information
ERROR: Unsupported URL: https://docs.google.com/file/d/0Bwi6Ha03myF1aGVweVBoemdlU3c/preview?pli=1; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/youtube_dl/YoutubeDL.py", line 494, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.3/site-packages/youtube_dl/extractor/common.py", line 156, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.3/site-packages/youtube_dl/extractor/generic.py", line 353, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: https://docs.google.com/file/d/0Bwi6Ha03myF1aGVweVBoemdlU3c/preview?pli=1; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by CiscoPress** [comment]
I second that. Wish Google Drive support.

example URL https://drive.google.com/folderview?id=0B9g_WLKRYa99M3VFQlJrN0dXa3M&usp=sharing

**Comment by haasn** [comment]
I would also greatly benefit this. youtube-dl supports dropbox, and it's my favorite way of actually being able to download dropbox things.

Users often decide to send me test files or other things related to my development via Google Drive, and it's always a big hassle to guide them through the process of re-uploading it to somewhere that actually works.

It would be really neat if youtube-dl could support Google Drive links natively so this would no longer be a problem.

**Comment by maurrubio** [comment]
Hello,

Youtube-dl is great but I don't understand why it has support for so many sites but not yet supports Google Drive? I use a parser that I developed myself and I know that is pretty similar to YouTube, actually even simpler.

Would be great if this support is added.
Thanks

**Comment by haasn** [comment]
Thanks for this!
