### ISSUE TITLE
YouTube Error - Content too short error

### ISSUE THREAD

**Issue by shakeyourbunny** [rg3/youtube-dl#2232]
I get on some videos consistently "content too short errors" ... dunno why.

$  youtube-dl --verbose  --format 35/18/34/22/83  "http://www.youtube.com/watch?v=rA-l2dr1lgU"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--format', '35/18/34/22/83', 'http://www.youtube.com/watch?v=rA-l2dr1lgU']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.01.23.4
[debug] Python version 2.7.3 - Linux-3.2.0-4-686-pae-i686-with-debian-7.3
[debug] Proxy map: {}
[youtube] Setting language
[youtube] rA-l2dr1lgU: Downloading webpage
[youtube] rA-l2dr1lgU: Downloading video info webpage
[youtube] rA-l2dr1lgU: Extracting video information
[download] Destination: Geblockt! #2 - Post E3 Event _ Spieleverfilmungen (24.06.13)-rA-l2dr1lgU.mp4
[download] 100% of 96.03MiB in 00:02
ERROR: content too short (expected 100695487 bytes and served 4195013)
Traceback (most recent call last):
  File "/home/shakeyourbunny/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 953, in process_info
    success = dl(filename, info_dict)
  File "/home/shakeyourbunny/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 929, in dl
    return fd.download(name, info)
  File "/home/shakeyourbunny/bin/youtube-dl/youtube_dl/downloader/common.py", line 290, in download
    return self.real_download(filename, info_dict)
  File "/home/shakeyourbunny/bin/youtube-dl/youtube_dl/downloader/http.py", line 172, in real_download
    raise ContentTooShortError(byte_counter, int(data_len))
ContentTooShortError

Other video is:
$  youtube-dl --verbose  --format 35/18/34/22/83  "http://www.youtube.com/watch?v=_wg3vlNv1s4"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--format', '35/18/34/22/83', 'http://www.youtube.com/watch?v=_wg3vlNv1s4']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.01.23.4
[debug] Python version 2.7.3 - Linux-3.2.0-4-686-pae-i686-with-debian-7.3
[debug] Proxy map: {}
[youtube] Setting language
[youtube] _wg3vlNv1s4: Downloading webpage
[youtube] _wg3vlNv1s4: Downloading video info webpage
[youtube] _wg3vlNv1s4: Extracting video information
[download] Destination: DonCrimes Rückblick - Folge 16 Castlevania The New Generation-_wg3vlNv1s4.mp4
[download] 100% of 49.90MiB in 00:00
ERROR: content too short (expected 52325788 bytes and served 14547)
Traceback (most recent call last):
  File "/home/shakeyourbunny/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 953, in process_info
    success = dl(filename, info_dict)
  File "/home/shakeyourbunny/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 929, in dl
    return fd.download(name, info)
  File "/home/shakeyourbunny/bin/youtube-dl/youtube_dl/downloader/common.py", line 290, in download
    return self.real_download(filename, info_dict)
  File "/home/shakeyourbunny/bin/youtube-dl/youtube_dl/downloader/http.py", line 172, in real_download
    raise ContentTooShortError(byte_counter, int(data_len))
ContentTooShortError

I tried downloading both videos of the course of the several days, tried to change IP address in order to avoid into running throttling due to Youtube .. _sigh_

**Comment by way2stars** [comment]
youtube-dl -f bestvideo+bestaudio --merge-output-format mkv https://www.youtube.com/watch?v=R2ake4zMrEU
[youtube] R2ake4zMrEU: Downloading webpage
[youtube] R2ake4zMrEU: Extracting video information
[youtube] R2ake4zMrEU: Downloading DASH manifest
[download] Destination: Nightcore - Angel-R2ake4zMrEU.f137.mp4
[download]  48.8% of 77.85MiB at 14.16MiB/s ETA 00:02 ERROR: content too short (expected 81635917 bytes and served 39845584)

**Comment by FredericJacobs** [comment]
Same issue here.
