### ISSUE TITLE
Question/SiteRequest: freespeech.org

### ISSUE THREAD

**Issue by joeschmoe40** [rg3/youtube-dl#2234]
I am used to using youtube-dl with the -j option to get the "real" URL, then using VLC to view that "real" URL.  This works well with YouTube and other, similar, sites.

I would like to be able to do the same with "freespeech.org".

Observe:

$ youtube-dl.py -j http://freespeech.org
WARNING: Falling back on generic information extractor.
{"extractor": "generic", "format": "0 - unknown", "uploader": "www.freespeech.org", "format_id": "0", "id": "4C7VcgRKrZA", "stitle": "Free Speech TV", "playlist": null, "title": "Free Speech TV", "url": "http:\\/\\/www.youtube.com\\/v\\/4C7VcgRKrZA", "extractor_key": "Generic", "playlist_index": null, "ext": "unknown_video", "webpage_url": "https://www.freespeech.org/", "_filename": "Free Speech TV-4C7VcgRKrZA.unknown_video", "fulltitle": "Free Speech TV", "webpage_url_basename": ""}
$ youtube-dl.py --version
2014.01.23.4

Not surprisingly, VLC can't work with the above URL (the one that references youtube.com - which is, obviously, unlikely to be a good URL for freespeech.org).

Please help!

(The point is - I'm surprised it works at all - usually if I give a bad URL to the "-j" option, I get a few screenfuls of error messages, and no useful output).

Can I make a site request for freespeech.org?

**Comment by TRox1972** [comment]
Are the livestreams hosted on freespeech.org itself, or livestream.com? If it's the latter, which now is supported, should this be closed?

**Comment by joeschmoe40** [comment]
I'm not sure.  All I know is that if I load up a browser, and go to "http://www.freespeech.org", it plays the live stream of what they are currently showing.
If, using the latest version (Updating to version 2016.05.21.2 ...) of youtube-dl, I get:
$ youtube-dl.py http://www.freespeech.org[generic] www.freespeech: Requesting header[redirect] Following redirect to https://www.freespeech.org/[generic] www.freespeech: Requesting headerWARNING: Falling back on generic information extractor.[generic] www.freespeech: Downloading webpage[generic] www.freespeech: Extracting information[generic] playlist: Downloading m3u8 informationERROR: Failed to download m3u8 information: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.$ 

    On Sunday, May 22, 2016 9:07 AM, Déstin Reed <notifications@github.com> wrote:
 

 Are the livestreams hosted on freespeech.org itself, or livestream.com? If it's the latter, which now is supported, should this be closed?—

**Comment by yan12125** [comment]
The Livestream embedded video on freespeech.org main page will be correctly detected in the next version.
