### ISSUE TITLE
donations...

### ISSUE THREAD

**Issue by sirvon** [rg3/youtube-dl#2238]
how can i donate funds?
tipjar?
bitcoins tip?
gittip?
flattr?

**Comment by JamesTheAwesomeDude** [comment]
@phihag Can you re-open this? That URL appears to be 404'd

* http://rg3.github.io/youtube-dl/donations.html
* https://ytdl-org.github.io/youtube-dl/donations.html
* https://yt-dl.org/donations.html
* https://github.com/ytdl-org/youtube-dl/search?q=donate&type=code

**Comment by pzygielo** [comment]
@JamesTheAwesomeDude  check ed3623e79461eb7a2ba23c6d51c9a7b14f8a7166

**Comment by tilboerner** [comment]
> @JamesTheAwesomeDude check ed3623e

That commit did `Remove references for donations for legal concerns`. 

My assumption is now that I cannot donate to the project, although I would like to.

Maybe it's worth explaining that somewhere prominent, so people can stop searching.
