### ISSUE TITLE
ERROR: content too short downloading from youku

### ISSUE THREAD

**Issue by igilham** [rg3/youtube-dl#2248]
It looks like the downloader may not like some multi-part videos.

Video URL: http://v.youku.com/v_show/id_XOTcwNjExMzI=.html&lang=en&lang=en

```
$ [Youku] XOTcwNjExMzI: Downloading webpage
[Youku] XOTcwNjExMzI: Extracting information
[download] Destination: 八卦掌用法-XOTcwNjExMzI_part00.flv
[download] 100% of 9.99MiB in 03:02
ERROR: content too short (expected 10471368 bytes and served 1221784)

[1]-  Exit 1                  youtube-dl http://v.youku.com/v_show/id_XOTcwNjExMzI=.html
[2]+  Done                    lang=en
```

**Comment by yan12125** [comment]
There are several notes:
* This URL should be "http://v.youku.com/v_show/id_XOTcwNjExMzI=.html&lang=en" instead.
* URLs with '&' should be enclosed in single or double quotes. For example:

> youtube-dl "http://v.youku.com/v_show/id_XOTcwNjExMzI=.html&lang=en"

Usually it's network issues. Currently I got stuck on this video, too, while using a China proxy helps me downloading all files.

Note that Youku support in youtube-dl is completely rewritten in #5833. You need to wait for the next release or try the latest git repository for correct Youku downloading.

**Comment by yan12125** [comment]
Youku is completely rewritten again and this should no longer an issue. Feel free to leave comments below or open a new issue if there are still problems.
