### ISSUE TITLE
--add-metadata -x / --xattrs -x does not discard source video 

### ISSUE THREAD

**Issue by pricejn2** [rg3/youtube-dl#2261]
Follow-up to Issue #1570  

When running ```youtube-dl --add-metadata -x --audio-format mp3 BaW_jenozKc``` the video file is not erased. The same occurs with using ```--xattrs``` in conjunction with -x

**Comment by jaimeMF** [comment]
Will be fixed in the next version, thanks for the report.

**Comment by phihag** [comment]
The fix has made it into youtube-dl 2015.01.11. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by pricejn2** [comment]
thanks!
