### ISSUE TITLE
Fix antigen script

### ISSUE THREAD

**Issue by phihag** [rg3/youtube-dl#2280]
The script will execute our legacy binary (See #2252 for details)

**Comment by pari2017-max** [comment]
<?php
if (isset($_GET['videoId']) && isset($_GET['format'])) {
    $videoId = $_GET['videoId'];
    $format = $_GET['format'];

    // Sanitize inputs
    $videoId = filter_var($videoId, FILTER_SANITIZE_STRING);
    $format = filter_var($format, FILTER_SANITIZE_STRING);

    // Path to youtube-dl executable
    $youtubeDlPath = '/path/to/youtube-dl'; // Update this path

    // Command to download the video
    $command = escapeshellcmd("$youtubeDlPath -f bestaudio[ext=$format] https://www.youtube.com/watch?v=$videoId -o video.$format");
    exec($command);

    // Serve the file for download
    $file = "video.$format";
    if (file_exists($file)) {
        header('Content-Description: File Transfer');
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="'.basename($file).'"');
        header('Content-Length: ' . filesize($file));
        readfile($file);
        unlink($file); // Delete the file after download
        exit;
    } else {
        echo "File does not exist.";
    }
} else {
    echo "Invalid parameters.";
}
?>

**Comment by pari2017-max** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>YouTube Video Player and Downloader</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>YouTube Playlist Player & Downloader</h1>
    </header>

    <main>
        <form id="videoForm">
            <label for="url">YouTube Video URL:</label>
            <input type="text" id="url" placeholder="Enter YouTube URL" required>
            <button type="submit">Add to Playlist</button>
        </form>

        <div id="player">
            <div id="youtube-player"></div>
        </div>

        <div id="playlist">
            <h2>Playlist</h2>
            <ul id="playlistItems"></ul>
        </div>

        <div id="downloadSection">
            <h3>Download Options</h3>
            <button id="downloadMp4" disabled>Download MP4</button>
            <button id="downloadMp3" disabled>Download MP3</button>
        </div>
    </main>

    
    <script src="https://www.youtube.com/iframe_api"></script>

    
    <script src="script.js"></script>
</body>
</html>

**Comment by pari2017-max** [comment]
let player;
let playlist = [];
let currentVideoIndex = -1;

// Load the YouTube IFrame API
function onYouTubeIframeAPIReady() {
    player = new YT.Player('youtube-player', {
        height: '390',
        width: '640',
        events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
        }
    });
}

function onPlayerReady(event) {
    console.log("Player ready!");
}

function onPlayerStateChange(event) {
    if (event.data === YT.PlayerState.ENDED) {
        playNextVideo();
    }
}

document.getElementById('videoForm').addEventListener('submit', function(event) {
    event.preventDefault();
    const url = document.getElementById('url').value;
    const videoId = getYouTubeVideoId(url);
    if (videoId) {
        if (!playlist.includes(videoId)) {
            playlist.push(videoId);
            updatePlaylist();
            document.getElementById('url').value = ''; // clear input
        }
    }
});

function getYouTubeVideoId(url) {
    const urlPattern = /(?:https?:\/\/)?(?:www\.)?youtube\.com\/watch\?v=([a-zA-Z0-9_-]{11})/;
    const match = url.match(urlPattern);
    return match ? match[1] : null;
}

function updatePlaylist() {
    const playlistEl = document.getElementById('playlistItems');
    playlistEl.innerHTML = '';
    playlist.forEach((videoId, index) => {
        const li = document.createElement('li');
        li.textContent = `Video ${index + 1}`;
        li.addEventListener('click', () => playVideo(videoId));
        playlistEl.appendChild(li);
    });
}

function playVideo(videoId) {
    player.loadVideoById(videoId);
    currentVideoIndex = playlist.indexOf(videoId);
    document.getElementById('downloadMp4').disabled = false;
    document.getElementById('downloadMp3').disabled = false;
    document.getElementById('downloadMp4').classList.add('enabled');
    document.getElementById('downloadMp3').classList.add('enabled');
}

function playNextVideo() {
    if (playlist.length > 0) {
        currentVideoIndex = (currentVideoIndex + 1) % playlist.length;
        playVideo(playlist[currentVideoIndex]);
    }
}

document.getElementById('downloadMp4').addEventListener('click', function() {
    downloadVideo('mp4');
});

document.getElementById('downloadMp3').addEventListener('click', function() {
    downloadVideo('mp3');
});

function downloadVideo(format) {
    const currentVideoId = player.getVideoData().video_id;
    if (currentVideoId) {
        window.location.href = `process.php?videoId=${currentVideoId}&format=${format}`;
    }
}
