### ISSUE TITLE
URL's generated with youtube-dl resulting in 403 error?

### ISSUE THREAD

**Issue by Elite** [rg3/youtube-dl#2287]
My php script to merge 1080p was working fine until today and used `wget` to download url's generated by youtube-dl and merged them (as `youtube-dl` does not delete source files after merge) , today this functionality is broken and both `wget` and `curl` fails to download the streams with `403 Forbidden` error from Youtube. 

Strangely, `YTDL` is able to download the files. I tried changing `user-agent` in curl as below but it still results in 403.

```
> User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.2 (KHTML, like Gecko) Chrome/5.0.342.3 Safari/533.2
> Host: r3---sn-aig7knek.googlevideo.com
> Accept: */*
>
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 403 Forbidden
< Last-Modified: Wed, 02 May 2007 10:26:10 GMT
< Content-Type: text/plain
< Connection: close
< X-Content-Type-Options: nosniff
< Date: Sat, 01 Feb 2014 14:37:24 GMT
< Server: gvs 1.0
<
{ [data not shown]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection #0
```

I would also like to request that `youtube-dl` deletes dash files after conversion (https://github.com/rg3/youtube-dl/issues/1612#issuecomment-32445539) which will specifically come handy in situations and usage scenario (scripted downloading on mass level) like this.

**Comment by kieranoreilly** [comment]
Hi I am having the same problem. Did you end up getting a fix?

**Comment by Elite** [comment]
After hours of testing I finally found the problem and the solution which worked was to clear the youtube-dl cache folder.

**Comment by yan12125** [comment]
axel is broken with YouTube, see https://github.com/rg3/youtube-dl/issues/10429#issuecomment-242292635

**Comment by chitholian** [comment]
aria2c raises 403

`#!/usr/bin/env php
    <?php
    $height = 360;
    if($argc > 2) $height = $argv[2];
    system("youtube-dl -qge -f 'bestvideo[height<=$height]' ".$argv[1]." > videos.list");
    $list = explode("\n", file_get_contents('videos.list'));
    for($i=1;$i<count($list);$i+=2){
        system("aria2c -c -j 3 -x 8 -s 8 --file-allocation=falloc -o ". str_replace('"','',preg_replace('/\s+/','-',$list[$i-1])).".mp4 -U 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36' ". $list[$i]);
    }`
