### ISSUE TITLE
[8tracks] throws 403 error after first 4 songs. Nothing downloads.

### ISSUE THREAD

**Issue by cadejscroggins** [rg3/youtube-dl#2310]
8tracks recently updated their API to version 3. They probably updated their security on this (because, according to their license, you can only skip 3 songs within a certain time frame).

**Comment by bubbleguuum** [comment]
Ok, thanks for the explanation. So if you need it non blocking, 8tracks is incompatible with -J, unless there would be a parameter to have it stop to the first 5 items and return immediately.

**Comment by yan12125** [comment]
Just to clarify: ```-J``` does not change the work flow. The flag just supresses irrelevant outputs.

The feature "stop to the first 5 items and return immediately" is different from the original one. If it's exactly what you want, open a new issue.

**Comment by bubbleguuum** [comment]
Done as  #7350
