### ISSUE TITLE
Failed to download from RAI Replay

### ISSUE THREAD

**Issue by Fabiobraz** [rg3/youtube-dl#2323]
I tried to download a video from the Replay part of the RAI television site, but this failed. Here you have the --verbose output.

Cheers

youtube-dl --verbose http://www.rai.tv/dl/replaytv/replaytv.html?day=2014-02-02&ch=3&v=322522&vd=2014-02-02&vc=3#day=2014-02-02&ch=3&v=322522&vd=2014-02-02&vc=3
[1] 23177
[2] 23178
[3] 23179
[4] 23180
[5] 23181
[6] 23182
[7] 23183
[8] 23184
[2]   Done                    ch=3
[3]   Done                    v=322522
[4]   Done                    vd=2014-02-02
[5]   Done                    vc=3#day=2014-02-02
[6]   Done                    ch=3
brac_fa@rmc-pleione [/home_local/brac_fa/youtube] : [debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.rai.tv/dl/replaytv/replaytv.html?day=2014-02-02']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.04.1
[debug] Python version 2.6.8 - Linux-3.0.101-0.8-pae-i686-with-SuSE-11-i586
[debug] Proxy map: {}
[generic] replaytv: Requesting header
WARNING: Falling back on generic information extractor.
[generic] replaytv: Downloading webpage
[generic] replaytv: Extracting information
ERROR: Unsupported URL: http://www.rai.tv/dl/replaytv/replaytv.html?day=2014-02-02; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/home/brac_fa/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/home/brac_fa/bin/youtube-dl/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/home/brac_fa/bin/youtube-dl/youtube_dl/extractor/generic.py", line 380, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.rai.tv/dl/replaytv/replaytv.html?day=2014-02-02; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

[1]   Exit 1                  youtube-dl --verbose http://www.rai.tv/dl/replaytv/replaytv.html?day=2014-02-02
[7]-  Done                    v=322522
[8]+  Done                    vd=2014-02-02

**Comment by francesco1119** [comment]
Hello, I still cannot download RAI video. Take for example "Elio e le storie tese - Nano nano" at the URL: http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-bde5986e-e524-4700-9eac-999afdd0f197.html.
As we can see on the page code there is a script that links SilverLight video:

                    MediaItem.type = 'WMV';

                    var videoURL = "http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=MjDPE0Bw1uIeeqqEEqual";

                    var videoTitolo="";
                    var isUgc = false;
                    var videoFormat = '43';
                    var subtitle = '';
                    var estensioneVideo = 'wmv';
                    var codificaVideo = '';

With VLC is easy to pass the URL "http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=MjDPE0Bw1uIeeqqEEqual" and see the video. Does youtube-dl would do that?

Thank you

**Comment by dstftw** [comment]
Neither of example URLs works in brower.

**Comment by francesco1119** [comment]
Is working now, I tried today 

`youtube-dl --verbose http://www.report.rai.it/dl/Report/puntata/ContentItem-13eb1922-2aa7-4358-9aba-905186df7cd5.html `

and the video was downloaded

**Comment by Zibri** [comment]
it didn't work because the command was wrongly not quoted:

youtube-dl --verbose 'http://www.rai.tv/dl/replaytv/replaytv.html?day=2014-02-02&ch=3&v=322522&vd=2014-02-02&vc=3#day=2014-02-02&ch=3&v=322522&vd=2014-02-02&vc=3'
