### ISSUE TITLE
Need help with a little improvement.

### ISSUE THREAD

**Issue by vanilla38** [rg3/youtube-dl#2334]
Hello, like 6 month ago i added a custom option to youtube-dl (bindaddress) in order to bind an ip address to youtube-dl video info get and video download, fo this i added this in **init**.py:

```
    commandLineConf = sys.argv[1:]
    argv = systemConf + userConf + commandLineConf
    opts, args = parser.parse_args(argv)

    if opts.bindaddress:
        true_socket = socket.socket
        def bound_socket(*a, **k):
            sock = true_socket(*a, **k)
            sock.bind(("%s" % opts.bindaddress, 0))
            return sock
        socket.socket = bound_socket    

    if opts.verbose:
        write_string(u'[debug] System config: ' + repr(_hide_login_info(systemConf)) + '\n')
        write_string(u'[debug] User config: ' + repr(_hide_login_info(userConf)) + '\n')
        write_string(u'[debug] Command-line args: ' + repr(_hide_login_info(commandLineConf)) + '\n')

return parser, opts, args
```

def _real_main(argv=None):

I updated youtube-dl 2 days ago and ofc, this custom functionality does not work anymore, i know that this option works untill this commit: 79d09f47c2abafe94c36d5c6718038c854748360

maybe someone knows how o reimport it ? or another way to bind my ip addresses to youtube-dl.

Thanks.

**Comment by scfc** [comment]
There is now the [option `--source-address`](https://github.com/rg3/youtube-dl/blob/master/README.md#network-options) that should cover your use case.  IMHO this issue can be closed.

**Comment by yan12125** [comment]
Yep, ```--source-address``` works just the same as the original poster's patch. Anyway thanks for the idea and the code!
