### ISSUE TITLE
Unsuppported la7.it url (was: Failed to download from LA7.it)

### ISSUE THREAD

**Issue by Fabiobraz** [rg3/youtube-dl#2337]
youtube-dl --verbose http://www.la7.it/tgla7/rivedila7/edizione-delle-20-220114-06-02-2014-126211
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.la7.it/tgla7/rivedila7/edizione-delle-20-220114-06-02-2014-126211']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.06.2
[debug] Python version 2.6.8 - Linux-3.0.101-0.8-pae-i686-with-SuSE-11-i586
[debug] Proxy map: {}
[generic] edizione-delle-20-220114-06-02-2014-126211: Requesting header
WARNING: Falling back on generic information extractor.
[generic] edizione-delle-20-220114-06-02-2014-126211: Downloading webpage
[generic] edizione-delle-20-220114-06-02-2014-126211: Extracting information
ERROR: Unsupported URL: http://www.la7.it/tgla7/rivedila7/edizione-delle-20-220114-06-02-2014-126211; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/home/brac_fa/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/home/brac_fa/bin/youtube-dl/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/home/brac_fa/bin/youtube-dl/youtube_dl/extractor/generic.py", line 380, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.la7.it/tgla7/rivedila7/edizione-delle-20-220114-06-02-2014-126211; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
The URL mentioned in this issue is dead. I've fixed la7 and tested a similar URL: http://www.la7.it/omnibus/rivedila7/omnibus-news-02-07-2016-189077. If there's something wrong since the next version, feel free to open a new issue.
