### ISSUE TITLE
Download from atresplayer.com

### ISSUE THREAD

**Issue by jlazkano** [rg3/youtube-dl#2341]
Hello, is it possible to download this video?

http://www.atresplayer.com/television/programas/pesadilla-en-la-cocina/temporada-3/capitulo-1-taberna-concha_2014012700175.html

$ youtube-dl http://www.atresplayer.com/television/programas/pesadilla-en-la-cocina/temporada-3/capitulo-1-taberna-concha_2014012700175.html -F --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.atresplayer.com/television/programas/pesadilla-en-la-cocina/temporada-3/capitulo-1-taberna-concha_2014012700175.html', '-F', '--verbose']
[debug] youtube-dl version 2013.12.04
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.3
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
[generic] capitulo-1-taberna-concha_2014012700175.html: Downloading webpage
[generic] capitulo-1-taberna-concha_2014012700175.html: Extracting information
ERROR: Unsupported URL: http://www.atresplayer.com/television/programas/pesadilla-en-la-cocina/temporada-3/capitulo-1-taberna-concha_2014012700175.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 429, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 131, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 236, in _real_extract
    raise ExtractorError(u'Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.atresplayer.com/television/programas/pesadilla-en-la-cocina/temporada-3/capitulo-1-taberna-concha_2014012700175.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Regards.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.05 or newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
