### ISSUE TITLE
Request: Olympics?

### ISSUE THREAD

**Issue by JacobHeubner** [rg3/youtube-dl#2347]
So I see in the supported sites information that youtube-dl can handle downloading from NBC.  Any chance this can work with http://stream.nbcolympics.com?

I tried just a straight download, but no luck:

C:\Users\Heubner\Downloads>youtube-dl http://stream.nbcolympics.com/nbcsn-coverage/winter/15452?nid=15451_208 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://stream.nbcolympics.com/nbcsn-coverage/winter/15452?nid=15451_208', '-v']
[debug] Encodings: locale 'cp1252', fs 'mbcs', out 'cp437', pref: 'cp1252'
[debug] youtube-dl version 2014.02.06.3
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] 15452?nid=15451_208: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 15452?nid=15451_208: Downloading webpage
[generic] 15452?nid=15451_208: Extracting information
ERROR: Unsupported URL: http://stream.nbcolympics.com/nbcsn-coverage/winter/15452?nid=15451_208; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 493, in extract_info
  File "youtube_dl\extractor\common.pyo", line 158, in extract
  File "youtube_dl\extractor\generic.pyo", line 380, in _real_extract
ExtractorError: Unsupported URL: http://stream.nbcolympics.com/nbcsn-coverage/winter/15452?nid=15451_208; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output
. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
This video is gone. Anyway there's a new request at #10295. Please move there for further discussions.
