### ISSUE TITLE
likes and dislikes

### ISSUE THREAD

**Issue by davidhedlund** [rg3/youtube-dl#2362]
To save some further hundreds of working hours I would be glad if someone could add an option to filter out searches by minimum likes, maximum dislikes, and likes:dislikes ratio.

Everyone would love to be able to sort out the best tracks on youtube automatic.

**Comment by jaimeMF** [comment]
Since youtube-dl 2015.02.10.2  you can use the --match-filter option, for example:
```
$ youtube-dl --ignore-config 'ytsearch10:Gangnam style' --match-filter 'view_count > 1000000000' --test
[youtube:search] query "Gangnam style": Downloading page 1
[download] Downloading playlist: Gangnam style
[youtube:search] playlist Gangnam style: Collected 10 video ids (downloading 10 of them)
[download] Downloading video 1 of 10
[youtube] 9bZkp7q19f0: Downloading webpage
[youtube] 9bZkp7q19f0: Extracting video information
[youtube] 9bZkp7q19f0: Downloading DASH manifest
[download] Destination: PSY - GANGNAM STYLE (강남스타일) M_V-9bZkp7q19f0.mp4
[download] 100% of 10.00KiB in 00:00
[download] Downloading video 2 of 10
[youtube] mIQToVqDMb8: Downloading webpage
[youtube] mIQToVqDMb8: Extracting video information
[youtube] mIQToVqDMb8: Downloading DASH manifest
[download] Gangnam Style Official Music Video - 2012 PSY with Oppan Lyrics & MP3 Download does not pass filter view_count > 1000000000, skipping ..
[download] Downloading video 3 of 10
[youtube] byScdHbEwHE: Downloading webpage
[youtube] byScdHbEwHE: Extracting video information
[youtube] byScdHbEwHE: Downloading DASH manifest
[download] Pocoyo Gangnam Style HD does not pass filter view_count > 1000000000, skipping ..
[download] Downloading video 4 of 10
[youtube] CH1XGdu-hzQ: Downloading webpage
[youtube] CH1XGdu-hzQ: Extracting video information
[youtube] CH1XGdu-hzQ: Downloading DASH manifest
[download] PSY- Gangnam Style (Official Music Video) does not pass filter view_count > 1000000000, skipping ..
[download] Downloading video 5 of 10
[youtube] wcLNteez3c4: Downloading webpage
[youtube] wcLNteez3c4: Extracting video information
[youtube] wcLNteez3c4: Downloading DASH manifest
[download] PSY (ft. HYUNA) 오빤 딱 내 스타일 does not pass filter view_count > 1000000000, skipping ..
[download] Downloading video 6 of 10
[youtube] kpZhZAr1cQU: Downloading webpage
[youtube] kpZhZAr1cQU: Extracting video information
[youtube] kpZhZAr1cQU: Downloading DASH manifest
[download] PSY싸이 - GANGNAM STYLE (강남스타일) Waveya 웨이브야 Korean dance team does not pass filter view_count > 1000000000, skipping ..
[download] Downloading video 7 of 10
[youtube] mP1DPTY4Y7o: Downloading webpage
[youtube] mP1DPTY4Y7o: Extracting video information
[youtube] mP1DPTY4Y7o: Downloading DASH manifest
[download] Baby Gangnam Style (Official Video) does not pass filter view_count > 1000000000, skipping ..
[download] Downloading video 8 of 10
[youtube] rX372ZwXOEM: Downloading webpage
[youtube] rX372ZwXOEM: Extracting video information
[youtube] rX372ZwXOEM: Downloading DASH manifest
[download] PSY - GANGNAM STYLE @ Summer Stand Live Concert does not pass filter view_count > 1000000000, skipping ..
[download] Downloading video 9 of 10
[youtube] LZCKHjcLjCk: Downloading webpage
[youtube] LZCKHjcLjCk: Extracting video information
[youtube] LZCKHjcLjCk: Downloading DASH manifest
[download] The Walking Dead - Gangnam Style does not pass filter view_count > 1000000000, skipping ..
[download] Downloading video 10 of 10
[youtube] ftXBrr7vwho: Downloading webpage
[youtube] ftXBrr7vwho: Extracting video information
[youtube] ftXBrr7vwho: Downloading DASH manifest
[download] HULK Does GANGNAM STYLE does not pass filter view_count > 1000000000, skipping ..
```

Dou you really want to filter by likes:dislikes ratio?

**Comment by davidhedlund** [comment]
On 2015-02-10 21:27, Jaime Marquínez Ferrándiz wrote:
>
> Since youtube-dl 2015.02.10.2 you can use the --match-filter option, 
> for example:
>
> |$ youtube-dl --ignore-config 'ytsearch10:Gangnam style' --match-filter 'view_count > 1000000000' --test
> [youtube:search] query "Gangnam style": Downloading page 1
> [download] Downloading playlist: Gangnam style
> [youtube:search] playlist Gangnam style: Collected 10 video ids (downloading 10 of them)
> [download] Downloading video 1 of 10
> [youtube] 9bZkp7q19f0: Downloading webpage
> [youtube] 9bZkp7q19f0: Extracting video information
> [youtube] 9bZkp7q19f0: Downloading DASH manifest
> [download] Destination: PSY - GANGNAM STYLE (강남스타일) M_V-9bZkp7q19f0.mp4
> [download] 100% of 10.00KiB in 00:00
> [download] Downloading video 2 of 10
> [youtube] mIQToVqDMb8: Downloading webpage
> [youtube] mIQToVqDMb8: Extracting video information
> [youtube] mIQToVqDMb8: Downloading DASH manifest
> [download] Gangnam Style Official Music Video - 2012 PSY with Oppan Lyrics & MP3 Download does not pass filter view_count > 1000000000, skipping ..
> [download] Downloading video 3 of 10
> [youtube] byScdHbEwHE: Downloading webpage
> [youtube] byScdHbEwHE: Extracting video information
> [youtube] byScdHbEwHE: Downloading DASH manifest
> [download] Pocoyo Gangnam Style HD does not pass filter view_count > 1000000000, skipping ..
> [download] Downloading video 4 of 10
> [youtube] CH1XGdu-hzQ: Downloading webpage
> [youtube] CH1XGdu-hzQ: Extracting video information
> [youtube] CH1XGdu-hzQ: Downloading DASH manifest
> [download] PSY- Gangnam Style (Official Music Video) does not pass filter view_count > 1000000000, skipping ..
> [download] Downloading video 5 of 10
> [youtube] wcLNteez3c4: Downloading webpage
> [youtube] wcLNteez3c4: Extracting video information
> [youtube] wcLNteez3c4: Downloading DASH manifest
> [download] PSY (ft. HYUNA) 오빤 딱 내 스타일 does not pass filter view_count > 1000000000, skipping ..
> [download] Downloading video 6 of 10
> [youtube] kpZhZAr1cQU: Downloading webpage
> [youtube] kpZhZAr1cQU: Extracting video information
> [youtube] kpZhZAr1cQU: Downloading DASH manifest
> [download] PSY싸이 - GANGNAM STYLE (강남스타일) Waveya 웨이브야 Korean dance team does not pass filter view_count > 1000000000, skipping ..
> [download] Downloading video 7 of 10
> [youtube] mP1DPTY4Y7o: Downloading webpage
> [youtube] mP1DPTY4Y7o: Extracting video information
> [youtube] mP1DPTY4Y7o: Downloading DASH manifest
> [download] Baby Gangnam Style (Official Video) does not pass filter view_count > 1000000000, skipping ..
> [download] Downloading video 8 of 10
> [youtube] rX372ZwXOEM: Downloading webpage
> [youtube] rX372ZwXOEM: Extracting video information
> [youtube] rX372ZwXOEM: Downloading DASH manifest
> [download] PSY - GANGNAM STYLE @ Summer Stand Live Concert does not pass filter view_count > 1000000000, skipping ..
> [download] Downloading video 9 of 10
> [youtube] LZCKHjcLjCk: Downloading webpage
> [youtube] LZCKHjcLjCk: Extracting video information
> [youtube] LZCKHjcLjCk: Downloading DASH manifest
> [download] The Walking Dead - Gangnam Style does not pass filter view_count > 1000000000, skipping ..
> [download] Downloading video 10 of 10
> [youtube] ftXBrr7vwho: Downloading webpage
> [youtube] ftXBrr7vwho: Extracting video information
> [youtube] ftXBrr7vwho: Downloading DASH manifest
> [download] HULK Does GANGNAM STYLE does not pass filter view_count > 1000000000, skipping ..
> |
>
> Dou you really want to filter by likes:dislikes ratio?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rg3/youtube-dl/issues/2362#issuecomment-73777088>.
>

Yes. That is useful.

**Comment by jaimeMF** [comment]
For youtube.com there's a field in the webpage called `avg_rating` that seems to be (I only tested with two videos) `≈ likes/(likes+dislikes) * 5`. Would that be enough for you?

**Comment by davidhedlund** [comment]
On 2015-02-11 11:19, Jaime Marquínez Ferrándiz wrote:
>
> For youtube.com there's a field in the webpage called |avg_rating| 
> that seems to be (I only tested with two videos) |≈ 
> likes/(likes+dislikes) * 5|. Would that be enough for you?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rg3/youtube-dl/issues/2362#issuecomment-73859426>.
>
That will be good. Thank you.

**Comment by jaimeMF** [comment]
In the next version you'll be able to use something like `--match-filter 'average_rating > 4'`.

**Comment by davidhedlund** [comment]
On 2015-02-11 18:55, Jaime Marquínez Ferrándiz wrote:
>
> In the next version you'll be able to use something like 
> |--match-filter 'average_rating > 4'|.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rg3/youtube-dl/issues/2362#issuecomment-73929144>.
>
Thank you very much!
