### ISSUE TITLE
prefer http over https

### ISSUE THREAD

**Issue by niltsh** [rg3/youtube-dl#2364]
Hi

I make an app that take advantage of youtube-dl.

I found recently 
when using ./youtube-dl -g http;//youtube.com/xxxxxxx

the URL returns https://....
However, my app could not process https in the near future.

Is there any way to return the http rather than https?

BRs,
Zongyao Qu

**Comment by lucifer1708** [comment]
hey guys!
I'm using youtube_dl with django framework.
when I click on download button it is opening link in new tab instead of downloading
