### ISSUE TITLE
--add-metadata does not work on WebM

### ISSUE THREAD

**Issue by davidhedlund** [rg3/youtube-dl#2368]
youtube-dl xibw0VU5oZw -f 43 --add-metadata --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['xibw0VU5oZw', '-f', '43', '--add-metadata', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.10
[debug] Python version 2.7.3 - Linux-3.2.0-58-generic-x86_64-with-Trisquel-6.0-toutatis
[debug] Proxy map: {}
[youtube] Setting language
[youtube] xibw0VU5oZw: Downloading webpage
[youtube] xibw0VU5oZw: Downloading video info webpage
[youtube] xibw0VU5oZw: Extracting video information
[download] Goasia - Man Who Touch The Sky-xibw0VU5oZw.webm has already been downloaded
[ffmpeg] Adding metadata to 'Goasia - Man Who Touch The Sky-xibw0VU5oZw.webm'
[debug] ffmpeg command line: avconv -y -i 'Goasia - Man Who Touch The Sky-xibw0VU5oZw.webm' -c copy -metadata date=20110202 -metadata artist=BrainHunters -metadata 'title=Goasia - Man Who Touch The Sky' 'Goasia - Man Who Touch The Sky-xibw0VU5oZw.temp.webm'
ERROR: av_interleaved_write_frame(): Invalid argument
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1016, in post_process
    keep_video_wish, new_info = pp.run(info)
  File "/usr/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 472, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/usr/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 64, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 61, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

**Comment by dstftw** [comment]
ffmpeg/avconv doesn't look capable embedding webm metadata. Moreover looks like official webm metadata tags are [not defined at all](http://wiki.webmproject.org/webm-metadata/global-metadata#TOC-Official-Tags). You can embed tags into matroska container by forcing output template extension to `mkv`:
```
youtube-dl -f 171 https://www.youtube.com/watch?v=ouDFGE-P_iQ -x --add-metadata --metadata-from-title "%(artist)s - %(title)s" -o "%(title)s.mkv"
```
Closing since not a youtube-dl issue.

**Comment by davidhedlund** [comment]
@dstftw Thanks!
