### ISSUE TITLE
Please add support for MSNBC.com

### ISSUE THREAD

**Issue by anovicecodemonkey** [rg3/youtube-dl#2371]
www.nbcnews.com is supported but not www.msnbc.com. If I am not mistaken, the site uses theplatform.com to serve its video. 

Some example URLs: 

http://www.msnbc.com/hardball/watch/the-biden-factor-will-joe-run-in-2016-141809219986

http://www.msnbc.com/morning-joe/watch/fast-company-names-most-innovative-companies-145513027849

youtube-dl --verbose http://www.msnbc.com/hardball/watch/the-biden-factor-will-joe-run-in-2016-141809219986
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.msnbc.com/hardball/watch/the-biden-factor-will-joe-run-in-2016-141809219986']
[debug] Encodings: locale 'UTF-8', fs 'utf-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.08.1
[debug] Python version 3.3.3 - Linux-3.12.9-2-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[generic] the-biden-factor-will-joe-run-in-2016-141809219986: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-biden-factor-will-joe-run-in-2016-141809219986: Downloading webpage
[generic] the-biden-factor-will-joe-run-in-2016-141809219986: Extracting information
ERROR: Unsupported URL: http://www.msnbc.com/hardball/watch/the-biden-factor-will-joe-run-in-2016-141809219986; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.3/site-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.3/site-packages/youtube_dl/extractor/generic.py", line 380, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: http://www.msnbc.com/hardball/watch/the-biden-factor-will-joe-run-in-2016-141809219986; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
MSNBC.com will be support in the next version. Thanks for the report.
