### ISSUE TITLE
[PBS] No support for Indpendent Lens and videos.pbs.org not selecting highest quality.

### ISSUE THREAD

**Issue by anovicecodemonkey** [rg3/youtube-dl#2375]
Hi all, 
It appears that the PBS IE presently doesn't support PBS' Independent Lens documentaries. Some example URLs

http://www.pbs.org/independentlens/graduates

http://www.pbs.org/independentlens/waiting-room/

Also, when using the extractor on direct video URLs like: http://video.pbs.org/video/2365163372/ I notice that the IE grabs the video URL via JSON from http://video.pbs.org/videoInfo/2365163372/?format=json as specified by "alternate_encoding".  This appears to be a direct link to a -medium- quality version of video. In this case, resolution 416x234.  

If instead, the IE downloaded the M3U8 file as specified by "recommended_encoding", inside the M3U8 there is an option for better quality, in this case: 640x360.

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=504000,CODECS="avc1.4d001f, mp4a.40.5",RESOLUTION=416x234
inle1511_mezz16x9-16x9-hls-400k.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1093000,CODECS="avc1.4d001f, mp4a.40.5",RESOLUTION=640x360
inle1511_mezz16x9-16x9-hls-800k.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=229000,CODECS="avc1.4d001f, mp4a.40.5",RESOLUTION=320x180
inle1511_mezz16x9-16x9-hls-150k.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=64000,CODECS="mp4a.40.5"
inle1511_mezz16x9-16x9-hls-64k.m3u8
```

**Comment by dstftw** [comment]
There are no videos embedded on http://www.pbs.org/independentlens/graduates/ and http://www.pbs.org/independentlens/waiting-room/.
