### ISSUE TITLE
Add support for iqiyi.com

### ISSUE THREAD

**Issue by iv-or** [rg3/youtube-dl#2392]
Hi,

Could you add support for http://www.iqiyi.com ? 
Thanks.

**Comment by yan12125** [comment]
Thanks to @PeterDing (see #5849), iQiyi will be supported in the next version of youtube-dl. Currently only individual videos (for example http://www.iqiyi.com/v_19rrnmkv7k.html) are supported. Playlists (for example http://www.iqiyi.com/a_19rrhay91x.html) are not supported yet.
