### ISSUE TITLE
Unsupported URL (youtube)

### ISSUE THREAD

**Issue by Zeriuno** [rg3/youtube-dl#2402]
Running youtube-dl (up to date), I found an unsupported URL. Doing as I am told, I report the issue.

`youtube-dl --verbose http://www.youtube.com/watch?&v=NTJUFQmHbvc
[1] 34096
Roccaforte:~ daniele$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.youtube.com/watch?']
[debug] Encodings: locale 'UTF-8', fs 'utf-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.1 - Darwin-11.4.2-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] watch?: Requesting header
[redirect] Following redirect to http://www.youtube.com/
[generic] : Requesting header
WARNING: Falling back on generic information extractor.
[generic] : Downloading webpage
[generic] : Extracting information
ERROR: Unsupported URL: http://www.youtube.com/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 380, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.youtube.com/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.`

**Comment by russellbateman** [comment]
This is a super utility. Thanks.

**Comment by EgbieAndersonUku1** [comment]
Learned something new today. Never stop learning.

**Comment by sgruenwald** [comment]
The reason why your URL didn't work is the & sign behind the ?. You have to delete it otherwise it throws this error. The ? should be directly followed by v=
