### ISSUE TITLE
Please add option --min-kbps

### ISSUE THREAD

**Issue by davidhedlund** [rg3/youtube-dl#2431]
Eg --min-kbps 128. This is useful for WebM when its audio is extracted to OGG as ~50% of the videos are 96 kbps.

**Comment by dstftw** [comment]
Use [format selection](https://github.com/rg3/youtube-dl#format-selection).

**Comment by davidhedlund** [comment]
@dstftw How do I apply **asr** to this?:
>  youtube-dl nhNUlAudx8E

**Comment by davidhedlund** [comment]
@dstftw Sorry, how do I apply **abr** to this?:
>  youtube-dl nhNUlAudx8E

**Comment by davidhedlund** [comment]
@dstftw I figured it out.
