### ISSUE TITLE
Why is the youtube video downloaded via youtube-dl at a quality lesser than the maximum listed quality on youtube

### ISSUE THREAD

**Issue by sbuhtig** [rg3/youtube-dl#2458]
I am invoking youtube dl and using only the default settings which I understand should default to best, though I've also tried explicitly saying --max-quality FORMAT in both cases I download a 1280x720 mp4 file with stereo mpegAAC audio at a 44.1 khz sample rate, while youtube lists 1080p as the maximum quality format available for that particular video (http://www.youtube.com/watch?v=LUemKLtbHxk).

I don't know if the sound is always at 44.1 khz on youtube but I was hoping that the 1080p version might also have 48khz sound if possible.

**Comment by jaimeMF** [comment]
For some time this is done `bestvideo+bestaudio` is automatically used if you have ffmpeg or avconv installed, so I'm closing the issue.
