### ISSUE TITLE
[Vimeo] webvtt saved srt

### ISSUE THREAD

**Issue by xubuntu4iran** [rg3/youtube-dl#2468]
<pre>youtube-dl --skip-download --write-sub http://vimeo.com/76979871
[vimeo] 76979871: Downloading webpage
[vimeo] 76979871: Extracting information
[vimeo] 76979871: Downloading webpage
[info] Writing video subtitles to: The New Vimeo Player (You Know, For Videos)-76979871.en.srt</pre>

**Comment by remitamine** [comment]
now youtube-dl extract the correct format.
```
youtube-dl --skip-download --write-sub http://vimeo.com/76979871
[vimeo] 76979871: Downloading webpage
[vimeo] 76979871: Extracting information
[vimeo] 76979871: Downloading webpage
[info] Writing video subtitles to: The New Vimeo Player (You Know, For Videos)-76979871.en.vtt
```
