### ISSUE TITLE
free-tv-online.me support

### ISSUE THREAD

**Issue by orangeoval** [rg3/youtube-dl#2478]
I have used youtube-dl many times to pull successfully from www.free-tv-online.me, which links out to various other hosts.  It has always followed the [generic] download attempt (Falling back on generic information extractor) successfully.  It still initiates the fallback, but now fails saying free-tv-online.me is not a supported URL.  It never was specifically supported, but still worked in most cases via the generic fallback.  

I am running youtube-dl 2014.02.26

[Edit by @phihag: Changed title from `Was code changed to prevent generic fallback?`]

**Comment by TRox1972** [comment]
As of now, the website http://www.free-tv-video-online.me is no longer working. This issue should be closed.

**Comment by yan12125** [comment]
According to http://www.ibtimes.co.uk/what-happened-project-free-tv-free-tv-streaming-site-moves-new-domain-1512794, http://www.free-tv-video-online.me/ was moved to http://projectfreetv.im/. I can't find out the corresponding URLs for examples above, so closing it and wait for new requests. Thanks @TRox1972 for discovering this.
