### ISSUE TITLE
Tip or trick to bind youtube-dl to  a specific IP

### ISSUE THREAD

**Issue by TigersWay** [rg3/youtube-dl#2481]
Hi,

Is there any way to force youtube-dl to use a specific IP in a multiple NIC environment?

Thanks

**Comment by phihag** [comment]
Starting from youtube-dl 2015.01.10.1, you can make use of the [`--source-address` option](https://github.com/rg3/youtube-dl/blob/master/README.md#network-options). See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by ddurdle** [comment]
Thanks for the mod!

**Comment by ddurdle** [comment]
The change works :)  Running across two connections right now.
