### ISSUE TITLE
Download a rental video

### ISSUE THREAD

**Issue by twilightsparklehf** [rg3/youtube-dl#2484]
So I paid for a rental video, but I need to use youtube-dl to download it because my connection is too slow to just watch it on Youtube. Whenever I try to download the video, it gives me an error that "rental" videos are not supported. How can I download this?

**Comment by cbehan** [comment]
I'm genuinely curious about how this DRM is accomplished when YouTube claims to have moved to HTML5. Do the rental videos still use Flash? Or do they use (not yet and hopefully never standard) EME?

**Comment by cbehan** [comment]
I'm genuinely curious about how this DRM is accomplished when YouTube claims to have moved to HTML5. Do the rental videos still use Flash? Or do they use (not yet and hopefully never standard) EME?

**Comment by cbehan** [comment]
I'm genuinely curious about how this DRM is accomplished when YouTube claims to have moved to HTML5. Do the rental videos still use Flash? Or do they use (not yet and hopefully never standard) EME?

**Comment by rachelgreenhappy** [comment]
To download youtube paid videos, firstly you need to have a paid account.
Then use Allavosft to download them offline with this guide https://www.allavsoft.com/how-to/download-youtube-rental-movies.html

**Comment by VarunAgw** [comment]
@cbehan Probably widevine.
