### ISSUE TITLE
[brightcove] Daisuki ripping

### ISSUE THREAD

**Issue by youtubedlhelpneeded** [rg3/youtube-dl#2486]
I'm trying to download a video from daisuki but as you can see I've got some problems doing so. First it's downloading some random youtube video and after that I get an error.

youtube-dl --verbose test "https://www.daisuki.net/movies/watch/KILLlaKILL/RKc/3Mc"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'test', 'https://www.daisuki.net/movies/watch/KILLlaKILL/RKc/3Mc']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.28
[debug] Python version 2.7.5+ - Linux-3.8.0-25-generic-x86_64-with-Ubuntu-13.10-saucy
[debug] Proxy map: {}
[youtube:search] query "test": Downloading page 1
[download] Downloading playlist: test
[youtube:search] playlist test: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[youtube] Setting language
[youtube] dRIgmKGDqFM: Downloading webpage
[youtube] dRIgmKGDqFM: Downloading video info webpage
[youtube] dRIgmKGDqFM: Extracting video information
[download] Destination: Pepsi MAX & Jeff Gordon Present - 'Test Drive 2'-dRIgmKGDqFM.mp4
[download] 100% of 83.41MiB in 03:31
[generic] 3Mc: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3Mc: Downloading webpage
[generic] 3Mc: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: #20 Far from the Madding Crowd | KILL la KILL | Aniplex | DAISUKI
[generic] playlist #20 Far from the Madding Crowd | KILL la KILL | Aniplex | DAISUKI: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[Brightcove] ref:XtGdXLw675CukuUii269: Downloading webpage
[Brightcove] ref:XtGdXLw675CukuUii269: Extracting information
ERROR: Unable to extract json; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 170, in _real_extract
    videoPlayer[0], query_str, query, referer=referer)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 186, in _get_video_info
    info = self._search_regex(r'var experienceJSON = ({.*?});', webpage, 'json')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract json; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by Kcchouette** [comment]
related to #4738?

**Comment by yan12125** [comment]
Thanks. As https://www.daisuki.net/movies/watch/KILLlaKILL/RKc/3Mc is gone, I'll close this. Please move to #4738 for further discussions.
