### ISSUE TITLE
Reverse download order

### ISSUE THREAD

**Issue by vertevero** [rg3/youtube-dl#249]
I'm trying to download an entire channel and would like to be able to run but have it download in reverse order

```
youtube-dl -A -t -c https://www.youtube.com/user/smosh
```

Could you add a flag to download in reverse order so that the oldest video is 00001 instead of the newest?

**Comment by thomasbuckler** [comment]
is there a way to download an entire channel with the oldest videos downloading first? --datebefore xxxxxxxx is too slow for this. theres 100s of thousands of recent videos that i dont want. only early videos.

**Comment by shillshocked** [comment]
Just use the default all videos playlist for the channel and this flag, it should work as you want it.
