### ISSUE TITLE
youtube-dl incompatible with python 3

### ISSUE THREAD

**Issue by Raven24** [rg3/youtube-dl#25]
I am using Arch Linux, and they recently upgraded the default python binary to python 3. The old version is still available under the name python2...
Please make the script compatible with python 3, to avoid future issues with linux distributions upgrading their packages.

Thanks for this great script!

**Comment by shirishag75** [comment]
what is the stance of making youtube-dl python 3.0 ready as Debian is also making python 3.0 default.
