### ISSUE TITLE
Setting lower quality with --max-quality

### ISSUE THREAD

**Issue by antanatman** [rg3/youtube-dl#2502]
Hi,

I'm using youtube-dl==2014.02.28 on Linux Mint in virtualenv. I am trying to set lower than best quality of download, but it does not seem to work.

For example, all of below download the best available quality:

    youtube-dl --max-quality=240p http://www.youtube.com/watch?v=vIu85WQTPRc
    youtube-dl --max-quality=240 http://www.youtube.com/watch?v=vIu85WQTPRc
    youtube-dl --max-quality 240p http://www.youtube.com/watch?v=vIu85WQTPRc
    youtube-dl --max-quality 240 http://www.youtube.com/watch?v=vIu85WQTPRc

Am I misusing the --max-quality FORMAT, or is it a bug?

**Comment by jaimeMF** [comment]
With the last version you can use `-f best[height<=240]`. Thanks for the report.
