### ISSUE TITLE
-x option fails to convert to audio file without specifying --audio-format

### ISSUE THREAD

**Issue by JaKXz** [rg3/youtube-dl#2506]
After reading the documentation, I assumed that I could simply pass the `-x` option and youtube-dl would figure out that I want the best quality and best format for the video (song) I'm downloading. However, passing the `--audio-format [mp3]` argument is required so that the following error does not occur:

    [youtube] Post-process file videoname-<videocode>.m4a exists, skipping

What I think is happening is the `-x` flag is changing the video format to an audio format before finishing the download and the post-processing can take place.

**Comment by phihag** [comment]
YouTube serves m4a files with a very weird header that only some players can read. youtube-dl 2015.01.23.4 and newer will automatically correct the header of the m4a file if ffmpeg is present on the system. I am therefore closing this issue. See [our FAQ](https://yt-dl.org/update) if you need help updating. Thank you for the report!

**Comment by shreve** [comment]
It works! Thanks, @phihag, you're my hero!
