### ISSUE TITLE
How can I use ffmpeg from youtube-dl?

### ISSUE THREAD

**Issue by Soroid** [rg3/youtube-dl#2508]
I want to use ffmpeg's
-acodec copy
within the same youtube function
to convert youtube videos from mp4 to m4a
This would be helpful so i only need to input one command to download a video and extract its audio

I don't want to use youtube-dl's -X because
A) the file size is noticeably smaller so I don't know if there's something 'less' about youtube-dl's audio quality
B) youtube-dl doesn't keep the thumbnail pic, but ffmpeg does.

EDIT: Nvm i found out that ffmpeg actually keeps the video when it converts thus the file size...
How can i keep the image thumbnail after doing -x on youtube-dl then?

**Comment by phihag** [comment]
You can just run youtube-dl with the `-x` or `--audio-format m4a` options.
