### ISSUE TITLE
Downloading video Course from Lynda.com ERROR: Unable to log in

### ISSUE THREAD

**Issue by LinkAndreas** [rg3/youtube-dl#2520]
I have tried to download a Video course as a premium Member with youtube-dl, but I'm still getting the following error:

[lynda:course] playlist xyz: Collected 43 video ids (downloading 43 of them)
[download] Downloading video #1 of 43
[lynda] Logging in as xyz
[lynda] Confirming log in and log out from another device
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

I've tried it with: 

youtube-dl     url    --username NAME_OF_PREMIUM_ACCOUNT --password PASSWORD

**Comment by jaan143** [comment]
hi i want to download videos from lynda i am premium member at there
Sir plz tell me where is your software i want to download 
thanks

**Comment by jaan143** [comment]
i got this error
[lynda] Confirming log in and log out from another device
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type youtube-dl -U to update.

**Comment by jaan143** [comment]
i dont understand how to run with  --verbose --write-pages and attach None_https_-_www.lynda.com_login_login.aspx.dump
can you plz explain with exact detail
thanks
