### ISSUE TITLE
[brightcove] NYTimes.com video

### ISSUE THREAD

**Issue by jordanf** [rg3/youtube-dl#2529]
Verbose output:

Jewford:Downloads jmf$ youtube-dl --verbose http://www.nytimes.com/video/us/100000002757071/the-men-of-atalissa.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.nytimes.com/video/us/100000002757071/the-men-of-atalissa.html']
[debug] Encodings: locale 'UTF-8', fs 'utf-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.03.07.1
[debug] Python version 2.7.6 - Darwin-13.1.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] the-men-of-atalissa: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-men-of-atalissa: Downloading webpage
[generic] the-men-of-atalissa: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: The Men of Atalissa - Video - NYTimes.com
[generic] playlist The Men of Atalissa - Video - NYTimes.com: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[Brightcove] ref:100000002757071: Downloading webpage
[Brightcove] ref:100000002757071: Extracting information
ERROR: Unable to extract json; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 500, in extract_info
    ie_result = ie.extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 162, in extract
    return self._real_extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 170, in _real_extract
    videoPlayer[0], query_str, query, referer=referer)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 186, in _get_video_info
    info = self._search_regex(r'var experienceJSON = ({.*?});', webpage, 'json')
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 360, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract json; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
All provided example URLs work fine with latest version. Closing.
