### ISSUE TITLE
Cosmos with Neil DeGraqsse-Tyson from Fox: Unsupported URL

### ISSUE THREAD

**Issue by jayseye** [rg3/youtube-dl#2541]
Hi, we may need someone in the U.S. to trace this, as I've been told that the video is only available in this country: 
 
$ youtube-dl --verbose http://www.fox.com/watch/183733315515
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.fox.com/watch/183733315515']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.03.10
[debug] Python version 2.6.6 - Linux-2.6.37.6-smp-i686-Intel-R-_Core-TM-2_Duo_CPU_____T5450__@_1.66GHz-with-slackware-13.37.0
[debug] Proxy map: {}
[generic] 183733315515: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 183733315515: Downloading webpage
[generic] 183733315515: Extracting information
ERROR: Unsupported URL: http://www.fox.com/watch/183733315515; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/ytd/youtube_dl/extractor/generic.py", line 277, in _real_extract
    doc = xml.etree.ElementTree.fromstring(webpage.encode('utf-8'))
  File "/usr/lib/python2.6/xml/etree/ElementTree.py", line 963, in XML
    parser.feed(text)
  File "/usr/lib/python2.6/xml/etree/ElementTree.py", line 1245, in feed
    self._parser.Parse(data, 0)
ExpatError: not well-formed (invalid token): line 50, column 86
Traceback (most recent call last):
  File "/usr/bin/ytd/youtube_dl/YoutubeDL.py", line 503, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/ytd/youtube_dl/extractor/common.py", line 162, in extract
    return self._real_extract(url)
  File "/usr/bin/ytd/youtube_dl/extractor/generic.py", line 472, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.fox.com/watch/183733315515; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by remitamine** [comment]
cosmosontv.com redirects to fox.com(youtube-dl can extract videos from fox.com).
