### ISSUE TITLE
ERROR: Unsupported URL: http://www.nbc.com/parenthood/episode-guide/season-5/just-like-at-home/515

### ISSUE THREAD

**Issue by nomadicME** [rg3/youtube-dl#2549]
$ youtube-dl -v http://www.nbc.com/parenthood/episode-guide/season-5/just-like-at-home/515
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.nbc.com/parenthood/episode-guide/season-5/just-like-at-home/515']
[debug] Encodings: locale 'ANSI_X3.4-1968', fs 'ANSI_X3.4-1968', out 'ANSI_X3.4-1968', pref: 'ANSI_X3.4-1968'
[debug] youtube-dl version 2014.03.10
[debug] Python version 2.7.5 - Linux-3.10.17-gentoo-i686-Intel-R-_Atom-TM-_CPU_N570_@_1.66GHz-with-gentoo-2.2
[debug] Proxy map: {}
[generic] 515: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 515: Downloading webpage
[generic] 515: Extracting information
ERROR: Unsupported URL: http://www.nbc.com/parenthood/episode-guide/season-5/just-like-at-home/515; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 277, in _real_extract
    doc = xml.etree.ElementTree.fromstring(webpage.encode('utf-8'))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 43, column 68
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 503, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 162, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 472, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.nbc.com/parenthood/episode-guide/season-5/just-like-at-home/515; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
NBC is now supported. However, the video you provided is expired. In the next version youtube-dl will give an informative error message. If you still encounter problems, feel free to open a new issue.
