### ISSUE TITLE
southparkstudios.com: Downloads don't work; player on site works

### ISSUE THREAD

**Issue by jspenguin** [rg3/youtube-dl#2551]
Downloading from southparkstudios.com fails because the server never returns a response for the requested URL:

send: u'GET /kip0/_pxn=1+_pxI0=Ripod-h264+_pxL0=undefined+_pxM0=+_pxK=18639+_pxE=mp4/44620/mtvnorigin/gsp.comedystor/com/sp/season-2/0214/acts/sp_0214_actHD_02_B_640x480_800.mp4 HTTP/1.1\r\nHost: mtvnmobile.vo.llnwd.net\r\nAccept-Encoding: identity\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nConnection: close\r\nAccept-Language: en-us,en;q=0.5\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0 (Chrome)\r\n\r\n'
ERROR: unable to download video data: timed out

Command line: youtube-dl '-v' '-o' '%(autonumber)s-%(id)s.%(ext)s' '-w' 'http://www.southparkstudios.com/full-episodes/s02e14-chef-aid' --print-traffic

The player on the site works fine - it uses RTMP by default, and if I block RTMP it falls back to HTTPS.

**Comment by dstftw** [comment]
Works fine with latest version.
