### ISSUE TITLE
unknown video.

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#2574]
Hi all, 
I was trying to see what formats the video has and I got this :-

    $ youtube-dl --verbose -F S9HT1mab2I4
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['--verbose', '-F', 'S9HT1mab2I4']
    [debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
    [debug] youtube-dl version 2014.02.17
    [debug] Python version 2.7.6 - Linux-3.13-1-amd64-x86_64-with-debian-jessie-sid
    [debug] Proxy map: {}
    [youtube] Setting language
    [youtube] S9HT1mab2I4: Downloading webpage
    [youtube] S9HT1mab2I4: Downloading video info webpage
    [youtube] S9HT1mab2I4: Extracting video information
    [youtube] RTMP download detected
    [info] Available formats for S9HT1mab2I4:
    format code extension resolution  note 
    _rtmp       unknown_videounknown    

Any help would be appreciated.

**Comment by dstftw** [comment]
rtmpe downloads are not supported, see https://github.com/rg3/youtube-dl/issues/343 for more information.
