### ISSUE TITLE
Site Support Request: CBC TV

### ISSUE THREAD

**Issue by ydlreporting** [rg3/youtube-dl#2579]
Example URL: http://www.cbc.ca/player/Shows/Shows/The+Nature+of+Things/ID/2441713884/

Thanks!

**Comment by y** [comment]
Somebody might be able to convert this Kodi/XMBC plugin: https://github.com/learningit/plugin.video.cbc/blob/master/default.py

**Comment by TRox1972** [comment]
As of the current version, cbc.ca is supported. This issue should be closed.

**Comment by yan12125** [comment]
Thanks @TRox1972. By the way, this video is gone (404). Feel free to open new issues if any other CBC videos does not work in youtube-dl.
