### ISSUE TITLE
Support 4shared videos

### ISSUE THREAD

**Issue by ksy5662** [rg3/youtube-dl#2598]
Please support 4shared video site.

http://www.4shared.com/video/Ugpymr1M/PSY_-_GANGNAM_STYLE_________M_.html

Jay-Yuui-MacBook-Pro:youtube-dl jcyu5662$ ./youtube-dl -s -v http://www.4shared.com/video/Ugpymr1M/PSY_-_GANGNAM_STYLE_________M_.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-s', '-v', 'http://www.4shared.com/video/Ugpymr1M/PSY_-_GANGNAM_STYLE_________M_.html']
[debug] Encodings: locale 'eucKR', fs 'utf-8', out 'eucKR', pref: 'eucKR'
[debug] youtube-dl version 2014.03.21.3
[debug] Python version 2.7.5 - Darwin-13.0.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] PSY_-_GANGNAM_STYLE_________M_: Requesting header
WARNING: Falling back on generic information extractor.
[generic] PSY_-_GANGNAM_STYLE_________M_: Downloading webpage
[generic] PSY_-_GANGNAM_STYLE_________M_: Extracting information
Jay-Yuui-MacBook-Pro:youtube-dl jcyu5662$ 

It only download preview of the video using generic extractor.
Can we download higher resolution videos from this?

**Comment by TRox1972** [comment]
Working example video: https://www.4shared.com/video/cJqKqDOTba/amy.htm.

Seems to be working as of version 2016.07.07. Should this be closed?

**Comment by yan12125** [comment]
Thanks.
