### ISSUE TITLE
Redundant postprocessor for "--extract-audio"

### ISSUE THREAD

**Issue by epitron** [rg3/youtube-dl#2607]
It looks like the postprocessor isn't needed anymore when you use `--extract-audio` on a youtube url:
```
$ youtube-dl --extract-audio https://www.youtube.com/watch?v=vWD7k6TrJ-g
[youtube] Setting language
[youtube] vWD7k6TrJ-g: Downloading webpage
[youtube] vWD7k6TrJ-g: Downloading video info webpage
[youtube] vWD7k6TrJ-g: Extracting video information
[download] Destination: Chromatics - Tick Of The Clock.m4a
[download] 100% of 4.37MiB in 00:01
[youtube] Post-process file Chromatics - Tick Of The Clock.m4a exists, skipping
```

It saved it directly to an `m4a` audio file, but still tried to run the audio extraction postprocessor.

Maybe a simple solution is to have the postprocessor ignore audio files (m4a, mp3, etc.)?

**Comment by phihag** [comment]
youtube-dl 2015.01.23.4 and newer will automatically correct the header of the m4a file if ffmpeg is present on the system. I am therefore closing this issue. See [our FAQ](https://yt-dl.org/update) if you need help updating. Thank you for the report!
