### ISSUE TITLE
    no previously-included directories found matching 'docs/_build'

### ISSUE THREAD

**Issue by FernandoMiguel** [rg3/youtube-dl#2623]
$ sudo pip install --upgrade youtube_dl
Downloading/unpacking youtube-dl from https://pypi.python.org/packages/source/y/youtube_dl/youtube_dl-2014.03.24.3.tar.gz#md5=923c28fbdbed00970aa21cb4eff5aa49
  Downloading youtube_dl-2014.03.24.3.tar.gz (340kB): 340kB downloaded
  Running setup.py egg_info for package youtube-dl

```
no previously-included directories found matching 'docs/_build'
```

Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2014.03.21.5
    Uninstalling youtube-dl:
      Successfully uninstalled youtube-dl
  Running setup.py install for youtube-dl

```
no previously-included directories found matching 'docs/_build'
Installing youtube-dl script to /usr/local/bin
```

Successfully installed youtube-dl
Cleaning up...

$ youtube-dl --version
2014.03.24.3

**Comment by NoWait126** [comment]
Hi, I get the same message again when I am installing pyspider on win8. 1st:

**Comment by NoWait126** [comment]
Hi, I get the same message again when I am installing pyspider on win8. I did this: In the first step I installed pycurl.exe. In the second step I installed pip again(I used 'easy_install pip'). Then I used 'pip install pyspider'. It returned  warning: no files found matching 'COPYING'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.png' under directory 'docs'
    warning: no files found matching '*.gif' under directory 'docs'
Downloading/unpacking cssselect>=0.9 (from pyspider)
  Downloading cssselect-0.9.1.tar.gz
  Running setup.py (path:c:\users\think\appdata\local\temp\pip_build_Think\cssselect\setup.py) egg_info for package cssselect

    no previously-included directories found matching 'docs\_build'
Downloading/unpacking lxml (from pyspider)

**Comment by jaimeMF** [comment]
@NoWait126 this is the bug tracker for youtube-dl, we can't provide you support for other python packages.

**Comment by NoWait126** [comment]
@jaimeMF  Thank you.

**Comment by liweilup** [comment]
I get the same message when I am installing sqlalchemy or installing SQLObject,i don't know how to solve 。Do you know how to solve it,please help me。Thank you

**Comment by yan12125** [comment]
@liweilup Ask sqlalchemy or SQLObject teams. It's youtube-dl issue tracker and neither packaegs are related to youtube-dl.

**Comment by liweilup** [comment]
@yan12125  Thank you,I have resolved it，you's suggestion is very good
