### ISSUE TITLE
Disable warnings

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#2630]
Is there a way to disable warnings ?
I still see `WARNING: Falling back on generic information extractor.` when I use the `-q` option.

**Comment by anandps002** [comment]
It is showing error Why is it because proxxy.It is showing the below
ERROR: Unable to download webpage: <urlopen error [Errno 110] Connection timed out> (caused by URLError(TimeoutError(110, 'Connection timed out')))
