### ISSUE TITLE
myvideo.de ERROR: rtmpdump exited with code 1

### ISSUE THREAD

**Issue by User20141** [rg3/youtube-dl#2659]
youtube-dl http://www.myvideo.de/watch/9438929/Marteria_OMG -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.myvideo.de/watch/9438929/Marteria_OMG', '-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.03.30.1
[debug] Python version 2.7.5+ - Linux-3.11.0-12-generic-x86_64-with-LinuxMint-16-petra
[debug] Proxy map: {}
[myvideo] 9438929: Downloading webpage
[myvideo] 9438929: Downloading webpage
[myvideo] 9438929: Extracting information
[download] Destination: Marteria -- OMG!-9438929.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://myvideo3fs.fplive.net/myvideo3/?token=c3RhcnRfdGltZT0yMDE0MDMzMTE0MzcxOSZlbmRfdGltZT0yMDE0MDMzMTE5MzcyNCZkaWdlc3Q9OTQzYjk4YmU4ZGZmNmI2NDRlNThhNjdhYWMwMjVlMzU=' -o 'Marteria -- OMG!-9438929.flv.part' --swfVfy http://is5.myvideo.de/de/player/mingR13y/ming.swf --playpath flv:movie39/17/9438929 --tcUrl 'rtmpe://myvideo3fs.fplive.net/myvideo3/?token=c3RhcnRfdGltZT0yMDE0MDMzMTE0MzcxOSZlbmRfdGltZT0yMDE0MDMzMTE5MzcyNCZkaWdlc3Q9OTQzYjk4YmU4ZGZmNmI2NDRlNThhNjdhYWMwMjVlMzU=' --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : myvideo3fs.fplive.net
[rtmpdump] DEBUG: Parsed app     : myvideo3
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : myvideo3fs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : flv:movie39/17/9438929
[rtmpdump] DEBUG: tcUrl    : rtmpe://myvideo3fs.fplive.net/myvideo3/?token=c3RhcnRfdGltZT0yMDE0MDMzMTE0MzcxOSZlbmRfdGltZT0yMDE0MDMzMTE5MzcyNCZkaWdlc3Q9OTQzYjk4YmU4ZGZmNmI2NDRlNThhNjdhYWMwMjVlMzU=
[rtmpdump] DEBUG: swfUrl   : http://is5.myvideo.de/de/player/mingR13y/ming.swf
[rtmpdump] DEBUG: app      : myvideo3
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: ac 90 a9 ac 32 7a 16 59 5b 45 f6 c6 35 9f 57 8c
[rtmpdump] DEBUG: 20 b7 d9 99 4d 82 b8 9f 47 3f cf 36 55 96 26 cb
[rtmpdump] DEBUG: SWFSize  : 426205
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : myvideo3fs.fplive.net
[rtmpdump] DEBUG: Parsed app     : myvideo3
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : myvideo3fs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : flv:movie39/17/9438929
[rtmpdump] DEBUG: tcUrl    : rtmpe://myvideo3fs.fplive.net/myvideo3/?token=c3RhcnRfdGltZT0yMDE0MDMzMTE0MzcxOSZlbmRfdGltZT0yMDE0MDMzMTE5MzcyNCZkaWdlc3Q9OTQzYjk4YmU4ZGZmNmI2NDRlNThhNjdhYWMwMjVlMzU=
[rtmpdump] DEBUG: swfUrl   : http://is5.myvideo.de/de/player/mingR13y/ming.swf
[rtmpdump] DEBUG: app      : myvideo3
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: ac 90 a9 ac 32 7a 16 59 5b 45 f6 c6 35 9f 57 8c
[rtmpdump] DEBUG: 20 b7 d9 99 4d 82 b8 9f 47 3f cf 36 55 96 26 cb
[rtmpdump] DEBUG: SWFSize  : 426205
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 18, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 836, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 826, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1025, in download
    self.extract_info(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 522, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 559, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 996, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 972, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 290, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 194, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 143, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 401, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 363, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by dstftw** [comment]
Not relevant anymore.
