### ISSUE TITLE
Support request for Canadian comedy central URLs

### ISSUE THREAD

**Issue by mburo** [rg3/youtube-dl#2675]
www.thedailyshow.cc.com doesn't work in Canada anymore - it was working till yesterday. The new URLs seem to be

http://watch.thecomedynetwork.ca/the-daily-show-with-jon-stewart/full-episodes

and

http://watch.thecomedynetwork.ca/the-colbert-report/full-episodes

I tried to massage the source code for half an hour today, but couldn't make it work. Could you please add support for these URLs? Thanks.

**Comment by remitamine** [comment]
supported starting from version 2016.08.31.
