### ISSUE TITLE
[slideslive.com] add support

### ISSUE THREAD

**Issue by susnak** [rg3/youtube-dl#2680]
Here is an example video (+slides)
https://slideslive.com/38891225/tri-urovne-motoriky

**Comment by pabs3** [comment]
I noticed that a request like this is enough to get the Youtube watch parameter:

    $ curl -s 'https://slideslive.com/38902354?demo=false' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'X-Requested-With: XMLHttpRequest'

**Comment by PeterTheOne** [comment]
I created another project to download the slides: https://github.com/PeterTheOne/slideslive-slides-dl/
