### ISSUE TITLE
Video-Download from Arte Mediathek fails with rtmpdump error 3, then error 1

### ISSUE THREAD

**Issue by grexe** [rg3/youtube-dl#2685]
Trying to download
http://www.arte.tv/guide/de/051388-000/ai-weiwei-evidence?autoplay=1
gives me:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-t', 'http://www.arte.tv/guide/de/051388-000/ai-weiwei-evidence?autoplay=1']
[debug] youtube-dl version 2013.08.29
[debug] Python version 2.7.5+ - Linux-3.11.0-19-generic-x86_64-with-Ubuntu-13.10-saucy
[debug] Proxy map: {}
[arte.tv] 051388-000: Downloading webpage
[arte.tv] 051388-000: Downloading info json
[arte.tv] 051388-000: Extracting information
[download] Destination: Ai Weiwei - Evidence-051388-000_PLUS7-D.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmp://artestras.fcod.llnwd.net/a3903/o35/ -o 'Ai Weiwei - Evidence-051388-000_PLUS7-D.flv.part' --playpath 'mp4:geo/videothek/ALL/tvguide/051388-000-A_SQ_1_VA_01215927_MP4-2200_AMM-Tvguide.mp4?e=1396551286&h=b9bc554205c7807dcd0cd1f7513e4c58' --resume --skip 1
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
DEBUG: Parsing...
DEBUG: Parsed protocol: 0
DEBUG: Parsed host    : artestras.fcod.llnwd.net
DEBUG: Parsed app     : a3903/o35
DEBUG: Number of skipped key frames for resume: 1
DEBUG: Protocol : RTMP
DEBUG: Hostname : artestras.fcod.llnwd.net
DEBUG: Port     : 1935
DEBUG: Playpath : mp4:geo/videothek/ALL/tvguide/051388-000-A_SQ_1_VA_01215927_MP4-2200_AMM-Tvguide.mp4?e=1396551286&h=b9bc554205c7807dcd0cd1f7513e4c58
DEBUG: tcUrl    : rtmp://artestras.fcod.llnwd.net:1935/a3903/o35
DEBUG: app      : a3903/o35
DEBUG: live     : no
DEBUG: timeout  : 30 sec
DEBUG: Failed to get last keyframe.
DEBUG: Closing connection.

[rtmpdump] 0 bytesRTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
DEBUG: Parsing...
DEBUG: Parsed protocol: 0
DEBUG: Parsed host    : artestras.fcod.llnwd.net
DEBUG: Parsed app     : a3903/o35
DEBUG: Number of skipped key frames for resume: 1
DEBUG: Protocol : RTMP
DEBUG: Hostname : artestras.fcod.llnwd.net
DEBUG: Port     : 1935
DEBUG: Playpath : mp4:geo/videothek/ALL/tvguide/051388-000-A_SQ_1_VA_01215927_MP4-2200_AMM-Tvguide.mp4?e=1396551286&h=b9bc554205c7807dcd0cd1f7513e4c58
DEBUG: tcUrl    : rtmp://artestras.fcod.llnwd.net:1935/a3903/o35
DEBUG: app      : a3903/o35
DEBUG: live     : no
DEBUG: timeout  : 30 sec
DEBUG: Failed to get last keyframe.
DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 666, in main
    _real_main(argv)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 650, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 573, in download
    videos = self.extract_info(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 339, in extract_info
    return self.process_ie_result(ie_result, download=download)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 369, in process_ie_result
    self.process_info(ie_result)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 548, in process_info
    success = self.fd._do_download(filename, info_dict)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/FileDownloader.py", line 390, in _do_download
    info_dict.get('tc_url', None))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/FileDownloader.py", line 309, in _download_with_rtmpdump
    self.report_error(u'rtmpdump exited with code %d' % retval)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/FileDownloader.py", line 148, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 217, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 184, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by dstftw** [comment]
Both videos are unavailable now. However downloading works fine for another videos from frankreichs-mythische-orte series.
