### ISSUE TITLE
Download from muzu.tv fails in some cases

### ISSUE THREAD

**Issue by martin-ms** [rg3/youtube-dl#2707]
Hi and thanks first for your great work you done on youtube-dl!

Unfortunately, muzu.tv has been documented as a supported site but fails some times. I. e. http://www.muzu.tv/5-seconds-of-summer/she-looks-so-perfect-musikvideo/2175408 or http://www.muzu.tv/kylie-minogue/sexercize-musikvideo/2185057 ends  in an error 404; with other targets like http://www.muzu.tv/mr-probz/waves-musikvideo/2162365 it works well.

Here are the details of a failed download:
---------------------------------------------------
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.muzu.tv/kylie-minogue/into-the-blue-musikvideo/2161323']
[debug] Encodings: locale 'UTF-8', fs 'utf-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.03.27.1
[debug] Python version 3.4.0 - Linux-3.13.7-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[muzu.tv] 2161323: Downloading video info
ERROR: Unable to download webpage: HTTP Error 404: Not Found; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 194, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 574, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 582, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

Hope you are able to solve this problem, and thanks in advance.

Martin.

**Comment by rhnvrm** [comment]
`muzu.tv` seems to have shutdown in october 2015. We should close this issue

**Comment by yan12125** [comment]
Yeah. Thanks!
