### ISSUE TITLE
Batch download

### ISSUE THREAD

**Issue by Yamakaky** [rg3/youtube-dl#2710]
Hi

I make a list of youtube links I want to download, then I download them using `parallel -j 4 -- youtube-dl :::: dl-files`, which starts at most 4 jobs who downloads each 1 link. The problem is that I get a lot of output, -q gives to few, --no-progress is a bit better. Is there an option restrict output to only errors and 'video x downloaded' ?

**Comment by yan12125** [comment]
If #10894 is implemented, this issue will go away. Please move on there for further discussions, thanks.
