### ISSUE TITLE
youtube-dl fails to update on Windows if cwd != youtube-dl.exe

### ISSUE THREAD

**Issue by phihag** [rg3/youtube-dl#2718]
Reported by @AGSPhoenix:

> ERROR: no write permissions on youtube-dl
> I have youtube-dl.exe in my %PATH% so I can run it anywhere
> if I run the update in the same directory as the executable it works
> anywhere else and it borks

**Comment by henrik-jensen** [comment]
Just a note to those debugging the problem.
In addition to navigating to the folder of the exe, you can also mitigate the problem by using the full path of the executable when running from a different folder. It's just when youtube-dl.exe is found through the path the error occurs on my system.

**Comment by mikhaelkh** [comment]
You can put [elevate](http://code.kliu.org/misc/elevate/) in PATH folder, then press`Win + R`, then `elevate youtube-dl -U`

**Comment by mikhaelkh** [comment]
I thought of a temporary solution: create a `youtube-dl-U.cmd` in the same directory as `youtube-dl.exe` in PATH with this text:
```
pushd "%~dp0"
youtube-dl.exe -U
popd
```

**Comment by vibrasphere** [comment]
Still not working, added to PATH C:\cmds\youtube-dl.exe

**Comment by Starbuck2010** [comment]
The 2015.11.15 released always failed if started with 2015.11.13 (youtube-dl.exe.new is complete but not renamed). The workaround is to download manually the 2015.11.15 (guess I already saw it in other issues) or to fall-back to a previous version you may have and run -U again (2015.11.10 complete successfully the -U).
