### ISSUE TITLE
Brightcove extractor fails with "empty playlist"

### ISSUE THREAD

**Issue by jillh510** [rg3/youtube-dl#2755]
python -m youtube_dl --skip-download --write-info-json --no-playlist --format mp4 -v http://www.threadsmagazine.com/videos
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--skip-download', '--write-info-json', '--no-playlist', '--format', 'mp4', '-v', 'http://www.threadsmagazine.com/videos']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.04.13
[debug] Python version 2.7.5 - Darwin-13.1.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] videos: Requesting header
WARNING: Falling back on generic information extractor.
[generic] videos: Downloading webpage
[generic] videos: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: Free Sewing Videos on Garment Construction, Couture Techniques, Beginner Sewing, Fitting, Quick Tips, and More | ThreadsMagazine.com
[generic] playlist Free Sewing Videos on Garment Construction, Couture Techniques, Beginner Sewing, Fitting, Quick Tips, and More | ThreadsMagazine.com: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[Brightcove] AQ~~,AAAADA1lRGE~,jMAjzcjFPEVR550Rjq3x5TqC96pcWvG6: Downloading playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 514, in extract_info
    ie_result = ie.extract(url)
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/extractor/brightcove.py", line 177, in _real_extract
    return self._get_playlist_info(player_key[0])
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/extractor/brightcove.py", line 204, in _get_playlist_info
    raise ExtractorError('Empty playlist')
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by remitamine** [comment]
works with the latest version:
```
youtube-dl https://www.threadsmagazine.com/2018/06/22/drafting-one-collars
[generic] drafting-one-collars: Requesting header
WARNING: Falling back on generic information extractor.
[generic] drafting-one-collars: Downloading webpage
[generic] drafting-one-collars: Extracting information
[download] Downloading playlist: Draft an All-in-one Stand-up Collar - Threads
[generic] playlist Draft an All-in-one Stand-up Collar - Threads: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5794928469001: Downloading webpage
[brightcove:new] 5794928469001: Downloading JSON metadata
[brightcove:new] 5794928469001: Downloading m3u8 information
[brightcove:new] 5794928469001: Downloading m3u8 information
[brightcove:new] 5794928469001: Downloading m3u8 information
[brightcove:new] 5794928469001: Downloading m3u8 information
[brightcove:new] 5794928469001: Downloading MPD manifest
[brightcove:new] 5794928469001: Downloading MPD manifest
[download] Destination: Draft a Standing All-in-One Collar-5794928469001.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  134M    0  384k    0     0  60889      0  0:38:35  0:00:06  0:38:29 78656
```
