### ISSUE TITLE
Add pause/resume/stop functionality

### ISSUE THREAD

**Issue by MrS0m30n3** [rg3/youtube-dl#2764]
I think it would be really useful if you could add pause/resume/stop download functionality on youtube-dl. I tried to implement it you can take a look here: https://github.com/MrS0m30n3/youtube-dl/commit/3d6a61be64e9bde330fc5efa082fbbbe8081013f
I also added an easy to use YoutubeDLExtendedObject with auto command line parsing.

**Comment by douglasg14b** [comment]
Ctrl-c doe snot seem to stop youtube-dl for me. It stops, then immediately starts back up again.

I have to kill the process
