### ISSUE TITLE
Request feature of merging video and audio separately served at YouTube

### ISSUE THREAD

**Issue by m13253** [rg3/youtube-dl#2765]
![Screenshot at 2014-04-18 00:40:05.png](https://cloud.githubusercontent.com/assets/1808930/2734101/cafd4772-c64f-11e3-90cd-f00610fde51b.png)

From the screenshot we can know YouTube now serves video and audio separately.

I think it will be great if `youtube-dl` can automatically merge them.

I give three ways. Either of them can be implemented into `youtube-dl`:

``` bash
ffmpeg -i video.webm -i audio.m4a -c copy output.mkv

mkvmerge -o output.mkv video.webm audio.m4a

MP4Box -add video.mp4 -add audio.m4a output.new.mp4 && mv output.new.mp4 output.mp4
```

Thank you.

BTW: The worst/best decision is not accurate now, since the 'dash' version is not always the worst and the 'non-dash' version serves only up to 720p.

**Comment by aimkeepachieve** [comment]
You may try iDealshare VideoGo to merge multiple MP4 files into one at http://www.idealshare.net/mp4-joiner-merge-mp4-files-on-mac-windows.html

It can easily helps:
Join MP4 files as well as keep the same video format or change MP4 to AVI, WMV, MOV, FLV, ASF, MPG, OGV, WebM, etc;
It also can join nearly all videos and movies like merge MOV, merge MKV, merge WMV, AVCHD, MXF, WebM, OGV, 3GP, FLV, ASF, MTS, SWF, MPG, DivX, Xvid, M4V, Apple ProRes, MOD, TOD, MPV, OGM and etc;
It even can combine various kinds of audio files like join MP3, join WAV, join FLAC, WMA, M4A, M4B, AAC, AC3, OPUS, APE, AIFF, Apple Lossless ALAC, CAF, VOC, QCP, DTS, AU, RA, AMR, AWB, OGG and more;
Merge video and audio files in same format or with different extensions;
Join videos and audios as well as keep the original video format; merge video files as well as convert to other video or audio format;
Besides join files, iDealshare VideoGo also performs as an inbuilt editor which will optimize all kinds of video and audio clips in trim, crop, split by chapter, compress audio and video to smaller files; add effect/subtitle/watermark, change audio channel/bitrate/sample rate, adjust audio volume, disable audio, take snapshot and more;
Convert between all popular video and audio formats or convert video to audio formats;
