### ISSUE TITLE
youtube-dl crunchyroll

### ISSUE THREAD

**Issue by xaosdoom** [rg3/youtube-dl#2782]
hi i like your program but i have 1 problem how download premium videos from crunchyroll ( i have a premium account)

**Comment by ajay230ps** [comment]
Not working now again...

~$ youtube-dl -F http://www.crunchyroll.com/naruto-shippuden/episode-391-madara-uchiha-rises-666343
[Crunchyroll] 666343: Downloading webpage
[Crunchyroll] 666343: Downloading media info
[Crunchyroll] 666343: Downloading subtitles for English (US)
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
mrtj@xenon:~$ youtube-dl -F --verbose http://www.crunchyroll.com/naruto-shippuden/episode-391-madara-uchiha-rises-666343[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', '--verbose', 'http://www.crunchyroll.com/naruto-shippuden/episode-391-madara-uchiha-rises-666343']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.6 - Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, ffmpeg 2.4.3, ffprobe 2.4.3, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 666343: Downloading webpage
[Crunchyroll] 666343: Downloading media info
[Crunchyroll] 666343: Downloading subtitles for English (US)
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 603, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 649, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 853, in process_video_result
    raise ExtractorError('No video formats found!')
ExtractorError: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
@ajay230ps open a new issue.

**Comment by jaimeMF** [comment]
@ajay230ps I have fixed the issue in a221f22969843866ad85fd5cdf98160c79d99e9f, it will work in the next version.

**Comment by ajay230ps** [comment]
Thanks ! :)
