### ISSUE TITLE
Add support for Indavideo

### ISSUE THREAD

**Issue by nyuszika7h** [rg3/youtube-dl#2788]
**Site:** http://indavideo.hu/

**Example video**

Video page: http://indavideo.hu/video/Winx_Club_4evad_1resz_Magyar_Nickelodeon
MP4 file (link got with [DownloadHelper](https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/)): http://main-c.hu.rp5.magex.hu/indavideo/911/000/826/943/0001.360.mp4

**Comment by nyuszika7h** [comment]
Looks like this is a duplicate of #2174.

**Comment by dstftw** [comment]
#2147 you wanted to say.
