### ISSUE TITLE
Private youtube videos and playlists are not working correctly

### ISSUE THREAD

**Issue by ddevault** [rg3/youtube-dl#2789]
Hello! I set up ~/.netrc (though --username --password does not work, either), and attempted these two things:

https://gist.github.com/SirCmpwn/1cd52a96adf25cb963e2

https://gist.github.com/SirCmpwn/422227cdcf05ccaa9032

**Comment by mpenkov** [comment]
It's been a while... just checking if this is still an issue for you. If not, then we can close this ticket.
