### ISSUE TITLE
ERROR: Unsupported URL: http://www.digitaltutors.com/tutorial/1491-Rigging-Quadrupeds-in-3ds-Max#play-39380

### ISSUE THREAD

**Issue by foliwe** [rg3/youtube-dl#2795]

**Comment by poudigne** [comment]
Any update on digital tutors ? trying right now to do it but it doesnt work

**Comment by thezakman** [comment]
Is it supported now? or no fix for it?

**Comment by masneg** [comment]
I hope that some one can make it.
I have digitaltutors account and it can not be used in pluralsight.com in youtube-dl.
although in browser, it redirects to pluralsight from the digitaltutors user page.

**Comment by timofonic** [comment]
@masneg 
Could you provide example URLs? I'm not a dev, but I'm interested in able to have it working on youtube-dl.
