### ISSUE TITLE
Feature request: support money.cnn.com URLs

### ISSUE THREAD

**Issue by jillh510** [rg3/youtube-dl#2797]
http://money.cnn.com/video/technology/2014/04/21/t-aereo-antenna-farm.cnnmoney/index.html?iid=S_Taboola contains video but isn't processed by the CNN extractor.

**Comment by TRox1972** [comment]
Shouldn't be too difficult to implement, seeing as CNN already is supported.

**Comment by inemesitaffia** [comment]
2 years later???

**Comment by yan12125** [comment]
There are numerous new site support requests. We can't examined them one by one.

**Comment by inemesitaffia** [comment]
but it's a subset of something already done for other sub domains
