### ISSUE TITLE
doesn't work with The Daily Show full episodes

### ISSUE THREAD

**Issue by swilbur** [rg3/youtube-dl#2803]
youtube-dl works fine with individual episode clips, (from http://thedailyshow.cc.com/videos) but fails when attempting to download from the 'full episodes' page (http://www.thedailyshow.com/full-episodes):

$ youtube-dl http://www.thedailyshow.com/full-episodes --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.thedailyshow.com/full-episodes', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.04.21.6
[debug] Python version 2.7.6 - Linux-3.13-1-amd64-x86_64-with-debian-jessie-sid
[debug] Proxy map: {}
[generic] full-episodes: Requesting header
[redirect] Following redirect to http://thedailyshow.cc.com/episodes/rg6cx7/april-24--2014---ramachandra-guha
[ComedyCentralShows] april-24--2014---ramachandra-guha: Downloading webpage
ERROR: unable to find Flash URL in webpage http://thedailyshow.cc.com/episodes/rg6cx7/april-24--2014---ramachandra-guha; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 514, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/comedycentral.py", line 143, in _real_extract
    raise ExtractorError('unable to find Flash URL in webpage ' + url)
ExtractorError: unable to find Flash URL in webpage http://thedailyshow.cc.com/episodes/rg6cx7/april-24--2014---ramachandra-guha; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by gaenserich** [comment]
I can confirm having a similar issue in the US, no proxy or vpn, and can access the original page just fine. Here's my verbose output:
```
$  youtube-dl --verbose "http://thedailyshow.cc.com/full-episodes/6ihlbu/april-27--2015---elizabeth-olsen"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://thedailyshow.cc.com/full-episodes/6ihlbu/april-27--2015---elizabeth-olsen']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 3.4.3 - Linux-3.19.3-3-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentralShows] april-27--2015---elizabeth-olsen: Downloading webpage
[ComedyCentralShows] april-27--2015---elizabeth-olsen: Downloading show index
[ComedyCentralShows] april-27--2015---elizabeth-olsen: Downloading configuration for segment 1 / 4
[ComedyCentralShows] april-27--2015---elizabeth-olsen: Downloading configuration for segment 2 / 4
[ComedyCentralShows] april-27--2015---elizabeth-olsen: Downloading configuration for segment 3 / 4
[ComedyCentralShows] april-27--2015---elizabeth-olsen: Downloading configuration for segment 4 / 4
[download] Downloading playlist: thedailyshow April 27, 2015 - Elizabeth Olsen
[ComedyCentralShows] playlist thedailyshow April 27, 2015 - Elizabeth Olsen: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 662, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 821, in process_ie_result
    extra_info=extra)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 708, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1047, in process_video_result
    raise ExtractorError('No video formats found!')
youtube_dl.utils.ExtractorError: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Here are the dependencies I have installed:
```
python 3.4.3-2
python-setuptools 1:15.2-1
ffmpeg 1:2.6.2-1 (custom build with libfdk-aac, libopus added, and libpulse, libtheora, opencore-amr, schroedinger, speex, libbluray, libmodplug removed)
rtmpdump 20140918-2
```

**Comment by dstftw** [comment]
@gaenserich you are using an outdated version of youtube-dl.

**Comment by yan12125** [comment]
All TDS URLs mentioned here now redirect to cc.com. However, playlists on cc.com are not supported yet. Please move to #10003 for further discussion.
