### ISSUE TITLE
ERROR: m3u8 download detected but ffmpeg or avconv could not be found

### ISSUE THREAD

**Issue by Lobo6** [rg3/youtube-dl#2815]
Hello,
I try to download from culturebox.francetvinfo.fr and I have this :

C:\Users\zorglub\Documents\install>youtube-dl http://rg3.github.io/youtube-dl/documentation.htmlhttp://culturebox.francetvinfo.fr/live/theatre/theatre-contempor
ain/lautre-monde-ou-les-etats-et-empires-de-la-lune-de-lazar-145209
C:\Users\zorglub\Documents\install>youtube-dl --restrict-filenames http://cultur
ebox.francetvinfo.fr/live/theatre/theatre-contemporain/lautre-monde-ou-les-etats
-et-empires-de-la-lune-de-lazar-145209
[culturebox.francetvinfo.fr] live/theatre/theatre-contemporain/lautre-monde-ou-les-etats-et-empires-de-la-lune-de-lazar-145209: Downloading webpage
[culturebox.francetvinfo.fr] EV_6677: Downloading XML config
[download] Destination: L_Autre_monde_ou_les_tats_et_empires_de_la_lune_de_Lazar
-EV_6677.mp4
ERROR: m3u8 download detected but ffmpeg or avconv could not be found

What Can I do ?

**Comment by apihlaja** [comment]
Having them in %PATH% was not enough for me. I could open cmd.exe, and ffmpeg (and other related binaries, ffprobe) were available but youtube-dl was still saying `ffmpeg or avconv could not be found`. I had to use `--ffmpeg-location` parameter, then downloadig worked.

**Comment by dstftw** [comment]
@apihlaja most likely you went wrong somewhere. In any case, feel free to open a new issue if you think there is a bug.

**Comment by woeterman94** [comment]
For those of you coming here from google:  ffmpeg.exe, ffplay.exe and ffprobe.exe must be in the same directory as youtube-dl.exe which probably is "AppData\Local\Programs\Python\Python36-32\Scripts".

(Or you can give the ffmpeg location as a parameter see comment above)

**Comment by Hrxn** [comment]
Or in any other directory that is in your PATH..

**Comment by NewbieOubie2017** [comment]
I got this error today because I thought the live stream had finished.  It hadn't.  I tried a few of your suggestions and then went to the link and saw it was still streaming.  When it finished the link worked fine without me having done anything to my system.

**Comment by lospejos** [comment]
> 
> 
> For those of us coming from Google, download the following.
> 
> https://ffmpeg.zeranoe.com/builds/
> 
> Select your 64 or 32 bit architecture. Select Static linking. Download and extract the \bin directory to your youtube-dl directory. done.
> 
> (What is Static linking? The required library functions are compiled inside each .exe instead of being exported as Shared .dll files. Larger download, but fewer files, self-contained.)

For the benefit of others, be warned, that this site now says:

`ffmpeg.zeranoe.com will close on Sep 18, 2020, and all builds will be removed. If you're using Zeranoe FFmpeg Builds in your product, please ensure that you have a hosting strategy in place by the 18th. Thank you to everyone who supported the project along the way!
`
