### ISSUE TITLE
Frequent warning or error message : unable to extract html5 player and Unable to extract JS player URL

### ISSUE THREAD

**Issue by krantisit1321** [rg3/youtube-dl#2858]
My usecase is to download a stream which is playable on a device and browser combo where User agent string represents . Is it the right way to do that ?  
Let me know if I am missing any thing here.Here is log for my command 
====================================================================
kranti(~) $ sudo /usr/local/bin/youtube-dl --user-agent 'Mozilla/5.0 (Linux; U; Android 2.2; en-us; Nexus One Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1' --verbose  http://www.youtube.com/watch?v=bCloJm9gptM
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--user-agent', 'Mozilla/5.0 (Linux; U; Android 2.2; en-us; Nexus One Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1', '--verbose', 'http://www.youtube.com/watch?v=bCloJm9gptM']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.05.05
[debug] Python version 2.7.5 - Darwin-13.1.0-x86_64-i386-64bit
[debug] Proxy map: {}
[youtube] Setting language
[youtube] bCloJm9gptM: Downloading webpage
[youtube] bCloJm9gptM: Downloading video info webpage
[youtube] bCloJm9gptM: Extracting video information
WARNING: unable to extract uploader nickname
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 88 (45.42), itag 22, html5 player None
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 1196, in _real_extract
    raise ValueError('Could not find vevo ID')
ValueError: Could not find vevo ID
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 1274, in _real_extract
    video_webpage, u'JS player URL')
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 376, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

====================================================================

Thanks for the help

**Comment by rhnvrm** [comment]
@krantisit1321 you won't get an error if you simply use `youtube-dl http://www.youtube.com/watch?v=bCloJm9gptM` without the user-agent. Also, regarding the use case you mentioned, you can choose the format using the `-f <format>` and to list all the available formats you can use `youtube-dl -F http://www.youtube.com/watch?v=bCloJm9gptM`
Hopefully that solves your issue. 

I recommend closing this issue.

**Comment by yan12125** [comment]
Served formats with an Android User-Agent are the same as those with a desktop browser User-Agent. There's no need to support both, so closing.
