### ISSUE TITLE
Strip leading dots from file names

### ISSUE THREAD

**Issue by canavan** [rg3/youtube-dl#2865]
Any leading dots should be stripped off the file name, otherwise, the file is considered "hidden" by most tools, such as "ls".

Similar arguments could be made for removing leading '-' (minus signs), since such filenames require a preceeding -- or must be prefixed with e.g.  './'  or the filename will be interpreted as an option, not a filename.

$  youtube-dl --verbose  M_azYJCx4vI
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'M_azYJCx4vI']
[debug] Encodings: locale ISO8859-1, fs ISO8859-1, out ISO8859-1, pref ISO8859-1
[debug] youtube-dl version 2014.05.05
[debug] Python version 2.7.6 - IRIX64-6.5-IP35-mips-n32bit-ELF
[debug] Proxy map: {}
[youtube] Setting language
[youtube] M_azYJCx4vI: Downloading webpage
[youtube] M_azYJCx4vI: Downloading video info webpage
[youtube] M_azYJCx4vI: Extracting video information
[download] Destination: .Melbourne Comedy Festival Gala 2014 ronny chieng-M_azYJCx4vI.mp4
[download] 100% of 11.76MiB in 00:18
$ ls *.mp4
ls: cannot access *.mp4: No such file or directory

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.03.03 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by canavan** [comment]
It is indeed fixed, Thanks!
