### ISSUE TITLE
Support for naruget.net

### ISSUE THREAD

**Issue by kmshanah** [rg3/youtube-dl#2871]
$ youtube-dl --verbose http://www.naruget.net/watch/1123-naruto-shippuden-episode-329/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.naruget.net/watch/1123-naruto-shippuden-episode-329/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.04.21.6
[debug] Python version 3.4.0 - Linux-3.14.2-1-ARCH-x86_64-with-arch
[debug] Proxy map: {'http': 'http://proxy.disenchant.local:3128', 'ftp': 'http://proxy.disenchant.local:3128', 'https': 'http://proxy.disenchant.local:3128'}
[generic] 1123-naruto-shippuden-episode-329: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1123-naruto-shippuden-episode-329: Downloading webpage
[generic] 1123-naruto-shippuden-episode-329: Extracting information
ERROR: Unsupported URL: http://www.naruget.net/watch/1123-naruto-shippuden-episode-329/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 514, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 662, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: http://www.naruget.net/watch/1123-naruto-shippuden-episode-329/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by jaimeMF** [comment]
They probably don't have the right for distributing that content, therefore we can't add support for the site. If you think they can, please comment here and we will reopen the issue.
