### ISSUE TITLE
User agent

### ISSUE THREAD

**Issue by felixphew** [rg3/youtube-dl#2894]
What user agent does the client use? Also, would it be possible to change this via an option?

**Comment by 4goettma** [comment]
> Sometimes geoblocking can be bypassed with the right user agent string.

Quite interesting. Do you have examples for that? Couldn't find related information using Google.

**Comment by AnmolTomer** [comment]
@felixphew I am running into a problem related to this. Could you please provide an example of a youtube-dl syntax with --user-agent flag being used. That would be really helpful. Thanks!
