### ISSUE TITLE
encrypted youtube video fail to download

### ISSUE THREAD

**Issue by sumofsum** [rg3/youtube-dl#2922]
./youtube-dl AAbokV76tkU --verbose

Some video is start download fail around 3 days ago like the above example. It seems happen on encrypted signature's video. Is the encryption method changed from youtube? Attached below is the output of the above command.

/Mine/new/youtube-dl-master $ ./youtube-dl AAbokV76tkU --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['AAbokV76tkU', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.05.13
[debug] Python version 2.7.3 - Darwin-13.0.0-x86_64-i386-64bit
[debug] Proxy map: {}
[youtube] Setting language
[youtube] AAbokV76tkU: Downloading webpage
[youtube] AAbokV76tkU: Downloading video info webpage
[youtube] AAbokV76tkU: Extracting video information
[youtube] AAbokV76tkU: Encrypted signatures detected.
[youtube] encrypted signature length 86 (40.45), itag 22, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 43, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 18, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 5, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 36, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 17, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 137, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 248, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 136, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 247, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 135, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 244, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 245, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 246, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 134, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 243, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 133, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 242, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 160, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 140, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 83 (42.40), itag 171, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 137, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 248, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 136, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 247, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 135, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 244, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 245, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 246, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 134, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 243, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 133, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 242, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 160, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 140, html5 player en_US-vflzEDYyE
[youtube] encrypted signature length 86 (40.45), itag 171, html5 player en_US-vflzEDYyE
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1009, in process_info
    success = dl(filename, info_dict)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 985, in dl
    return fd.download(name, info)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 291, in download
    return self.real_download(filename, info_dict)
  File "./youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1214, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(_args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(_args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

Thanks

**Comment by pirate486743186** [comment]
shouldn't this be closed?
