### ISSUE TITLE
Unable to download from francetvinfo.fr

### ISSUE THREAD

**Issue by Meaulnes** [rg3/youtube-dl#2927]
Hi,

Could you add support for this site ?
Example of URL that currently fails :
http://www.francetvinfo.fr/elections/europeennes/direct-europeennes-regardez-le-debat-entre-les-candidats-a-la-presidence-de-la-commission_600639.html

Thank you in advance.

**Comment by janemaydaily** [comment]
Here is another easy guide http://www.allavsoft.com/how-to/francetvinfo.fr-download.html
