### ISSUE TITLE
rai italia

### ISSUE THREAD

**Issue by ppunta** [rg3/youtube-dl#2930]
ppunta@piero-fisso:~$ youtube-dl --verbose http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-cb27157f-9dd0-4aee-b788-b1f67643a391.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-cb27157f-9dd0-4aee-b788-b1f67643a391.html']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[generic] ContentItem-cb27157f-9dd0-4aee-b788-b1f67643a391: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ContentItem-cb27157f-9dd0-4aee-b788-b1f67643a391: Downloading webpage
[generic] ContentItem-cb27157f-9dd0-4aee-b788-b1f67643a391: Extracting information
ERROR: Unsupported URL: http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-cb27157f-9dd0-4aee-b788-b1f67643a391.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 380, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-cb27157f-9dd0-4aee-b788-b1f67643a391.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by francesco1119** [comment]
Hello, I still cannot download RAI video. Take for example "Elio e le storie tese - Nano nano" at the URL: http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-bde5986e-e524-4700-9eac-999afdd0f197.html.
As we can see on the page code there is a script that links SilverLight video:

						MediaItem.type = 'WMV';

						var videoURL = "http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=MjDPE0Bw1uIeeqqEEqual";
						
						var videoTitolo="";
						var isUgc = false;
						var videoFormat = '43';
						var subtitle = '';
						var estensioneVideo = 'wmv';
						var codificaVideo = '';

With VLC is easy to pass the URL "http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=MjDPE0Bw1uIeeqqEEqual" and see the video. Does youtube-dl would do that?

Thank you
