### ISSUE TITLE
Please add support for Reddit.com

### ISSUE THREAD

**Issue by anovicecodemonkey** [rg3/youtube-dl#2955]
Possible use cases:

Grabbing video links from a thread, e.g.: http://www.reddit.com/r/television/comments/25vja3/trailers_for_all_tv_shows_announced_during_last/

Or, grabbing all videos on a subreddit page e.g.: http://www.reddit.com/r/videos/ or the second page of that same subreddit: 
http://www.reddit.com/r/videos/?count=25&after=t3_25wyy0 for the second page. 

All of these URLs fall back to the generic extractor and fail to find any videos.

**Comment by svnpenn** [comment]
:+1:

**Comment by svnpenn** [comment]
As a workaround, I used this command successfully

    lynx -dump -listonly -nonumbers reddit.com/r/stationalpha |
    sed 0,/Hidden/d |
    youtube-dl -f bestaudio -a -

**Comment by TRox1972** [comment]
I agree with @aerobit. Should this issue be closed?

**Comment by svnpenn** [comment]
I agree this issue should be closed. It is annoying that Reddit is not supported, but supporting a non video site is and should be beyond the scope of this project
