### ISSUE TITLE
youtube-dl not updating properly

### ISSUE THREAD

**Issue by Soroid** [rg3/youtube-dl#2959]
C:\WINDOWS\system32>cd C:\youtube-dl

C:\youtube-dl>youtube-dl -U
Updating to version 2014.05.19 ...
Waiting for file handle to be closed ...

C:\youtube-dl>Updated youtube-dl to version 2014.05.19.
youtube-dl --version
2014.05.13

C:\youtube-dl>youtube-dl -U -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-U', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.05.13
[debug] Python version 2.7.5 - Windows-8-6.2.9200
[debug] Proxy map: {}
Updating to version 2014.05.19 ...
Waiting for file handle to be closed ...

C:\youtube-dl>Updated youtube-dl to version 2014.05.19.
youtube-dl --version -v
2014.05.13

C:\youtube-dl>

so ya, it's lying to me. Also I ran it as administrator.

**Comment by dstftw** [comment]
Should work fine with latest version.
