### ISSUE TITLE
add support for "http://www.sportlemon.tv/"

### ISSUE THREAD

**Issue by CapOM** [rg3/youtube-dl#297]
Hi,

I was trying to record badminton streaming from http://distro.megom.tv/player-inside.php?id=badminktoon&width=600&height=450

But youtube-dl.py script said "ERROR: Invalid URL"

I also tried using rtmpdump

rtmpdump --verbose -r rtmp://109.201.135.121:1935/streams/_definst_/badminktoon.  -t rtmp://109.200.202.86/streams?testkey=fb9b2e59d7959d474dedb15c6042f8e2 -p "http://distro.megom.tv/player-inside.php?id=badminktoon&width=600&height=450" -s "http://lds.megom.tv/player.swf"  -f "WIN 11,1,102,62"  -o res.asf -v

without any success.

Sincerely
Cap

**Comment by TRox1972** [comment]
The provided URL doesn't seem to work anymore. And I can't find any other URLs that do (https://encrypted.google.com/search?hl=ru&q=site:megom.tv).

**Comment by yan12125** [comment]
Thanks.
@CapOM Please leave a comment if you find it work again.
