### ISSUE TITLE
Doesn't download videos from foxnews.com

### ISSUE THREAD

**Issue by arpitchauhan** [rg3/youtube-dl#2974]
When trying to download from video.foxnews.com, falls back on the generic extractor, which fails.

Sample video: http://video.foxnews.com/v/3583285787001/dr-carson-fires-up-the-view-over-welfare-comments/#sp=show-clips

**Comment by fstirlitz** [comment]
youtube-dl has a FoxNews extractor now, and it works with the URL given here. I believe this issue can be closed.

**Comment by dstftw** [comment]
FoxNews is supported since youtube-dl 2014.12.04.1.
