### ISSUE TITLE
Support tv.nrk.no

### ISSUE THREAD

**Issue by amaurea** [rg3/youtube-dl#2980]
While support for video clips at www.nrk.no, the new online TV site tv.nrk.no is apparently not supported. See for example the following URL:

http://tv.nrk.no/serie/20-spoersmaal-tv/muhh48000314/23-05-2014

The output from --verbose is:

sigurdkn@guu ~/downloads $ youtube-dl --verbose http://tv.nrk.no/serie/20-spoersmaal-tv/muhh48000314/23-05-2014
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://tv.nrk.no/serie/20-spoersmaal-tv/muhh48000314/23-05-2014']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.05.19
[debug] Python version 3.4.1 - Linux-3.14.4-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[generic] 23-05-2014: Requesting header
[redirect] Following redirect to http://psfil.tv.nrk.no/content/feil/500.htm?aspxerrorpath=/serie/20-spoersmaal-tv/muhh48000314/23-05-2014
[generic] 23-05-2014: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 23-05-2014: Downloading webpage
[generic] 23-05-2014: Extracting information
ERROR: Unsupported URL: http://psfil.tv.nrk.no/content/feil/500.htm?aspxerrorpath=/serie/20-spoersmaal-tv/muhh48000314/23-05-2014; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 163, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 687, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: http://psfil.tv.nrk.no/content/feil/500.htm?aspxerrorpath=/serie/20-spoersmaal-tv/muhh48000314/23-05-2014; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

This is with version 2014.05.19.

The following scripts manage to download the file:

 http://folk.uio.no/sigurdkn/nrkdl
 http://folk.uio.no/sigurdkn/AdobeHDS.php.txt

(the .txt is just there to prevent the server from trying to execute the php file). The latter script is a part of KSVScripts. I've seen Adobe HDS on other sites too, so getting support for this should help for more than just NRK.

**Comment by unhammer** [comment]
I just tried this for the first time, grabbed the first url I found and got 

    $ youtube-dl --verbose https://tv.nrk.no/serie/bmi-turne/MUHH45000115/sesong-1/episode-1
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'--verbose', u'https://tv.nrk.no/serie/bmi-turne/MUHH45000115/sesong-1/episode-1']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.06.04.1
    [debug] Python version 2.7.10 - Linux-4.2.0-22-generic-x86_64-with-Ubuntu-15.10-wily
    [debug] exe versions: avconv 2.7.3-0ubuntu0.15.10.1, avprobe 2.7.3-0ubuntu0.15.10.1, ffmpeg 2.7.3-0ubuntu0.15.10.1, ffprobe 2.7.3-0ubuntu0.15.10.1, rtmpdump 2.4
    [debug] Proxy map: {}
    [generic] episode-1: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] episode-1: Downloading webpage
    [generic] episode-1: Extracting information
    ERROR: Unsupported URL: https://tv.nrk.no/serie/bmi-turne/MUHH45000115/sesong-1/episode-1
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 997, in _real_extract
        doc = parse_xml(webpage)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1558, in parse_xml
        tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
        parser.feed(text)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
        self._raiseerror(v)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
        raise err
    ParseError: not well-formed (invalid token): line 11, column 839
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
        ie_result = ie.extract(url)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
        return self._real_extract(url)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1532, in _real_extract
        raise UnsupportedError(url)
    UnsupportedError: Unsupported URL: https://tv.nrk.no/serie/bmi-turne/MUHH45000115/sesong-1/episode-1

**Comment by unhammer** [comment]
$ youtube-dl --version
2015.06.04.1

**Comment by dstftw** [comment]
@unhammer you are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by unhammer** [comment]
@dstftw OK, I thought that version number looked so recent but I guess youtube-dl moves fast; it works with git :-)
