### ISSUE TITLE
Support for www.linuxcbt.com videos

### ISSUE THREAD

**Issue by vinitkhandagle** [rg3/youtube-dl#2987]
I tried using youtube-dl for www[dot]linuxcbt[dot]com to download videos from there. Looks like this site is not supported. I wanted to request if this could be supported in youtube-dl. it would be a great help

Thanks for the this wonderful tool.

**Comment by dengsauve** [comment]
@phihag Routed here from CodeTriage. Looks like this issue is old, and upon examining the site and videos, I doubt youtube-dl will support this site. Any chance of closing this issue?

**Comment by yan12125** [comment]
I got no videos from http://demos.linuxcbt.com/launch.php?demoID=MTEy. @dengsauve Does it work for you?

**Comment by dengsauve** [comment]
@yan12125 this does not work for me, and I doubt that it will due to how the site renders the videos. I doubt youtube-dl will move in a direction of supporting this format. I would suggest closing this issue.

**Comment by yan12125** [comment]
Got it.
