### ISSUE TITLE
extract-audio crash on special chars in video title from Youtube

### ISSUE THREAD

**Issue by esamo** [rg3/youtube-dl#2998]
Hello again.

At Win7 x64. It seem to be ffprobe problem but can be fixed at youtube-dl before executing ffprobe. Probe from http://ffmpeg.zeranoe.com/builds/

1. Is there an option for youtube-dl to remove special chars from Youtube's video title? Extract-audio option doesn't work for squares etc. in title. At least those chars are shown in Windows 7 as squares.

2. Or is it a bug?

Pasting the issue below. Everything works fine when there are no 'squares' in video title.

------

D:\Pobrane\yt-dl>youtube-dl --update
youtube-dl is up-to-date (2014.05.19)

D:\Pobrane\yt-dl>youtube-dl --verbose --no-mtime --ignore-errors --extract-audio
 --audio-format=mp3 https://www.youtube.com/watch?v=TGE-_22uQ_Q
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--no-mtime', '--ignore-errors', '--ext
ract-audio', '--audio-format=mp3', 'https://www.youtube.com/watch?v=TGE-_22uQ_Q'
]
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2014.05.19
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[youtube] Setting language
[youtube] TGE-_22uQ_Q: Downloading webpage
[youtube] TGE-_22uQ_Q: Downloading video info webpage
[youtube] TGE-_22uQ_Q: Extracting video information
[download] Destination: ~⌘ Temple of the Moon ⌘~  performed by Erutan ( katetheg
reat19 )-TGE-_22uQ_Q.m4a
[download] 100% of 3.77MiB in 00:00
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1073, in post_process
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 121, in run
PostProcessingError

------

Regards & respect

**Comment by muchbetterbig** [comment]
You may also try this step by step guide to extract audio from YouTube to MP3, WAV, WMA, M4A, AIFF, FLAC etc at http://allavsoft.com/how-to/youtube-to-mp3.html

**Comment by esamo** [comment]
Now I am able to download audio format alone without video, the simplest and fastest option.

---

Regards & respect

**Comment by dstftw** [comment]
Works fine with latest version.
