### ISSUE TITLE
Howto know the fps of a youtube video ?

### ISSUE THREAD

**Issue by hafuz** [rg3/youtube-dl#3002]
Hi, Thanks for the wonderful work !
I need to know the fps of a youtube video to use it in a script based on youtube-dl.
It is not possible ( for now ;) !!)  to get this info by youtube-dl
It will be great to add an option to display it ! 

If someone can help me to have the fps info simply...
Thanx

**Comment by jaimeMF** [comment]
For YouTube videos some formats have fps info now , you can get them from the `fps` field in the json output (using [jq](https://stedolan.github.io/jq/)):
```
$ youtube-dl -j test:youtube | jq .fps
30
```

Therefore I'm closing the issue.
