### ISSUE TITLE
Bug: Windows XP (just XP?) proxy setting

### ISSUE THREAD

**Issue by karlQY** [rg3/youtube-dl#3004]
There is a proxy setting on Windows XP, which will be used by urllib2 in youtube-dl. Usage of

     youtube-dl.exe --proxy "" [url]

does not change this, youtube-dl still uses the specified Windows default proxy and not direct connection. This seems to be a known issue with urllib2 and Windows XP.

I don't know much Python, but http://www.decalage.info/en/python/urllib2noproxy seems like a solution.

**Comment by dstftw** [comment]
Nowadays `--proxy` is respected when updating as well.
