### ISSUE TITLE
SSL Issue with HTTPS Proxy setting

### ISSUE THREAD

**Issue by PureL1F3** [rg3/youtube-dl#3005]
I was getting the following SSL error running extract_info on a vimeo URL. I had an https proxy setup on the youtube_dl. 

I googled and came across this stackoverflow and removed the https proxy from my settings and the issue went away:
http://stackoverflow.com/questions/14390605/python-requests-ssl-issue 

Maybe a bug nobodys come across yet?

---------------------------------------------------------------------------------------

$ url = 'http://vimeo.com/79681921'
$ result = ydl.extract_info(url, download=False)
[vimeo] 79681921: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:507: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 531, in extract_info
    self.report_error(compat_str(de), de.format_traceback())
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 405, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 375, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:507: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>

-----------------------------------------------------
Specs:
OS - Linux
Python - 2.7.6
URL - http://vimeo.com/79681921

**Comment by dstftw** [comment]
Obviously the problem is with your proxy. youtube-dl works fine with https proxies.
