### ISSUE TITLE
Feature to download video only if specific language subtitle is available

### ISSUE THREAD

**Issue by Jiltseb** [rg3/youtube-dl#30095]
## Checklist

- [ x] I'm reporting a site feature request
- [ x] I've verified that I'm running youtube-dl version **2021.06.06**
- [ x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
Currently, youtube-dl has a large number of features to filter and match our requirements such as limit by file size and video length. It would have been nice to have an option to skip download if the specific language subtitle is not available. The options --write-sub and sub-lang are useful for filtering out but they don't stop the video from downloading if the specified sub-lang is not available or if there are no subtitles.

**Comment by dirkf** [comment]
Feel free to try out the scenario you're interested in and report back.
