### ISSUE TITLE
Is Youtube now restricted to 500 kbps downloads - seems so to me?

### ISSUE THREAD

**Issue by NipLars** [rg3/youtube-dl#30094]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
Over the past months I had this on and off, now permanent.

Has Youtube identified youtube-dl on all servers and now restrict download bandwidth?

As it was on and off, I could just abort download and try again when I saw 50 KiB/s and after one or a couple or retries it becomes normal and it download in MiB/s again.

Now I cannot get anything but around 50 KiB/s no matter what I retry. Since yesterday just about.

I have perfect and fast download on rumble and bitchute, so youtube related only. And on those it can start as low but then quickly gear up to MiB/s, but very rarely.

As retired programmer, I get the feeling YT is identifying application, now on every server they have and it has become permanent. But this is a guess, The HTTP User-Agent thingy is what I am thinking of.

It could be youtube restricted due to load or something, not sure. Or just annoyed for lost ad views or something.

I fixed a document that I load urls into, and a bat file to do either youtube, rumble or bitchute download in various resolutions.

I have 100/100 Mbps fiber and works fine on other hosts as I mentioned.
Running latest youtube-dl from june 2021.
It's been flawless for many years, first as part of AVC then last year as separate app I use separately.

I there a way to tell youtube-dl which user agent to use, many browsers has this kind of plugin swapping what you get identified by?

Just a heads up from me anyway.

Thanks for all the efforts from devs on this app.

**Comment by Kusurisan** [comment]
i don't know if that is the issue that was already present a while ago, but a few hours ago i had a lot of issues with youtube (normal watching, not downloading).. so could be server issues on youtubes side. couldn't even load 420p for me. when i looked it up online, it looked like a ton of other people had the same issue. 

but youtube seems to throttel from time to time and i don't know if it really got fixed finally.. but it seemed to happen less for me since the last bugfix for it. so i would say its probably server issues on youtubes side this time.

**Comment by Kusurisan** [comment]
youtube-dlg is basically a graphical user interface for youtube-dl. it gives you buttons, text fields etc. for a lot of settings so you can use them easier without needing a lot of commands in the cmd.. that makes it easier to test arround if you have issues or errors in a lot of cases.
