### ISSUE TITLE
Cannot download webm dash audio only 

### ISSUE THREAD

**Issue by ozok** [rg3/youtube-dl#3012]
Hi,
I'm using the following parameters to download webm audio in order to mux it with webm dash video later.
 -o "%(uploader)s - %(title)s.%(ext)s" -i --no-playlist -f 171 -c -w http://www.youtube.com/watch?v=GKn74H5QqkY

I get the following output and no audio:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-o', '%(uploader)s - %(title)s.%(ext)s', '--verbose', '-i', '--no-playlist', '-f'
, '171', '-c', '-w', 'http://www.youtube.com/watch?v=GKn74H5QqkY']
[debug] Encodings: locale cp1254, fs mbcs, out cp1254, pref cp1254
[debug] youtube-dl version 2014.05.19
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[youtube] Setting language
[youtube] GKn74H5QqkY: Downloading webpage
[youtube] GKn74H5QqkY: Downloading video info webpage
[youtube] GKn74H5QqkY: Extracting video information

If i use "-f 140" I can download m4a file but it fails for 171. I tried a few more youtube videos and result didn't change.  I'm using Windows binary 2014.05.19.

**Comment by phihag** [comment]
Works fine for me too with 2015.01.23.2. If you can still reproduce this problem please post a new report. If possible, attach `strace` to youtube-dl and post the (warning:large) strace log you get.
