### ISSUE TITLE
slow download speeds from YouTube

### ISSUE THREAD

**Issue by YousefSaber** [rg3/youtube-dl#30125]
I notice some incredible slow YouTube download speeds my connection using `speedtest`
```
(base) joseph@joseph-X541UJ:~$ speedtest

   Speedtest by Ookla

     Server: we - Alexandria (id = 27652)
        ISP: Telecom Egypt
    Latency:     4.78 ms   (0.26 ms jitter)
   Download:    37.40 Mbps (data used: 25.2 MB)                               
     Upload:     3.06 Mbps (data used: 2.8 MB)                               
Packet Loss:     0.0%
 Result URL: https://www.speedtest.net/result/c/464ccb36-8b93-4710-8c52-b46163d54ac7
```

when I download the video 
```
(base) joseph@joseph-X541UJ:~$ youtube-dl https://www.youtube.com/watch?v=LFThbSf_2VA
[youtube] LFThbSf_2VA: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Injustice - Exclusive Official Batman and Superman Clip (2021) Justin Hartley, Anson Mount-LFThbSf_2VA.f248.webm
[download]  40.7% of 5.61MiB at 66.93KiB/s ETA 00:50
```

streaming videos at Full HD seems to be fine. 

I'm using the latest version 
```
(base) joseph@joseph-X541UJ:~$ youtube-dl --version
2021.06.06
```

**Comment by YousefSaber** [comment]
@89z I'm sorry I just it's hard to go along with hundreds of posts looking for solutions ( I didn't find any unfortunately) if you want to close it that's up to you, perhaps you may want to consider updating FAQ with this issue.

**Comment by 89z** [comment]
> @89z I'm sorry I just it's hard to go along with hundreds of posts looking for solutions ( I didn't find any unfortunately) if you want to close it that's up to you, perhaps you may want to consider updating FAQ with this issue.

That is an absolutely rude and selfish attitude. Just looking literally only at the first page:

https://github.com/ytdl-org/youtube-dl/issues

I got these:

- https://github.com/ytdl-org/youtube-dl/issues/30097
- https://github.com/ytdl-org/youtube-dl/issues/30102
- https://github.com/ytdl-org/youtube-dl/issues/30109
- https://github.com/ytdl-org/youtube-dl/issues/30119

which tells me that you didnt try to look at all. Shame on you.

**Comment by G2G2G2G** [comment]
https://user-images.githubusercontent.com/50514477/137885167-bcee5b4c-2976-4d64-b294-afc8256b57a9.mp4
