### ISSUE TITLE
culturebox.francetvinfo.fr download issue

### ISSUE THREAD

**Issue by bluesangel** [rg3/youtube-dl#3025]
$youtube-dl  --version
2014.05.30.1

$ youtube-dl  -v http://culturebox.francetvinfo.fr/emissions/monte-le-son-le-live/monte-le-son-le-live-du-24-mai-jamie-cullum-155483
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://culturebox.francetvinfo.fr/emissions/monte-le-son-le-live/monte-le-son-le-live-du-24-mai-jamie-cullum-155483']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.05.30.1
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[culturebox.francetvinfo.fr] emissions/monte-le-son-le-live/monte-le-son-le-live-du-24-mai-jamie-cullum-155483: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 163, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/francetv.py", line 234, in _real_extract
    video_id = self._search_regex(r'"http://videos\.francetv\.fr/video/(.*?)"', webpage, 'video id')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 379, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Same issue for other videos on this website.

**Comment by dstftw** [comment]
Provided example URL is dead however the latest version works fine with similar URLs.

**Comment by keepreason** [comment]
Here is another easy method http://www.allavsoft.com/how-to/francetvinfo.fr-download.html
