### ISSUE TITLE
MLB

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#3030]
URL: http://m.mlb.com/video/v33211751

YouTube-DL downloads a 218Kb .swf file...but I don't believe this is an actual video.
Seems too small and I can't play the file(my guess is that this is just the player?)

I noticed that MLB is not actually in the --list-extractors, and it appears to be pulling this swf file with "generic information extractor".  So this is probably expected behavior, but thought I'd post just in case otherwise.

Thanks as always
Ringo

youtube-dl.exe -v http://m.mlb.com/video/v33211751
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://m.mlb.com/video/v33211751']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.05.31.4
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] v33211751: Requesting header
WARNING: Falling back on generic information extractor.
[generic] v33211751: Downloading webpage
[generic] v33211751: Extracting information
[download] Destination: Rapper 50 Cent's wild pitch _ MLB.com-ObjectEmbedFrame.s
wf
[download] 100% of 217.52KiB in 00:00

**Comment by dstftw** [comment]
Works fine with latest version.
