### ISSUE TITLE
How to specify the external downloader args

### ISSUE THREAD

**Issue by sobhan-m94** [rg3/youtube-dl#30359]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How can i use external downloader args in options ?

These are my option settings:

```
import youtube_dl

opts = {
'format': "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best",
'external_downloader' : 'aria2c',
'external_downloader_args' : "--max-connection-per-server=16 --dir=/home/downloads",
}
ydl=youtube_dl.YoutubeDL(opts)
ydl.download([f"https://www.youtube.com/watch?v={ytId}"])
```

python console output.

> 
>   File "yt.py", line 12, in <module>
>     ydl.download(["https://www.youtube.com/watch?v=yotubeID"])
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2069, in download
>     url, force_generic_extractor=self.params.get('force_generic_extractor', False))
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
>     return self.__extract_info(url, ie, download, extra_info, process)
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
>     return func(self, *args, **kwargs)
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 847, in __extract_info
>     return self.process_ie_result(ie_result, download, extra_info)
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
>     return self.process_video_result(ie_result, download=download)
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1692, in process_video_result
>     self.process_info(new_info)
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1976, in process_info
>     success = dl(filename, info_dict)
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
>     return fd.download(name, info)
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 366, in download
>     return self.real_download(filename, info_dict)
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/downloader/external.py", line 35, in real_download
>     retval = self._call_downloader(tmpfilename, info_dict)
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/downloader/external.py", line 101, in _call_downloader
>     cmd = [encodeArgument(a) for a in self._make_cmd(tmpfilename, info_dict)]
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/downloader/external.py", line 187, in _make_cmd
>     '--min-split-size', '1M', '--max-connection-per-server', '4'])
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/downloader/external.py", line 97, in _configuration_args
>     return cli_configuration_args(self.params, 'external_downloader_args', default)
>   File "/home/vagrant/.local/lib/python3.6/site-packages/youtube_dl/utils.py", line 4658, in cli_configuration_args
>     assert isinstance(ex_args, list)
> AssertionError
>

**Comment by dirkf** [comment]
It's telling you that the args should be a list, no? I'd try: 
```
'external_downloader_args' : ["--max-connection-per-server=16",  "--dir=/home/downloads"],
```
