### ISSUE TITLE
Youku extractor not work anymore

### ISSUE THREAD

**Issue by Huarong** [rg3/youtube-dl#3038]
The Youku extractor always work well utill today. I find whatever video I download, it will throw a error like this.

    hhr@jyy-master:~/temp$ youtube-dl http://v.youku.com/v_show/id_XNjI0MTkxNjAw.html
    [Youku] XNjI0MTkxNjAw: Downloading webpage
    [Youku] XNjI0MTkxNjAw: Extracting information
    ERROR: unable to download video data: <urlopen error [Errno 111] Connection refused>

I am using the laterst version.
Please help to fix this problem. Thank you.

**Comment by yan12125** [comment]
Thanks to @PeterDing's work (#5833), this video will be supported in the next version. Note that some videos mentioned in this issue are georestricted in Mainland China. A proxy or a China verification proxy is necessary.
