### ISSUE TITLE
youtube-dl not working time to time

### ISSUE THREAD

**Issue by hcevikbas** [rg3/youtube-dl#3041]
Hi guys,

today i get this error when i try to download videos "Unable to download webpage: <urlopen error [Errno 104] Connection reset by peer>"

I didn't do anything. No update centos or youtube-dl.

After this error i update both of them but nothing changed.

System stop when downloading.

Results on php

/usr/local/bin/youtube-dl --verbose -R 15 --continue -o source/1401823921.avi 'https://www.youtube.com/watch?v=BQMfJ03N1WQ'

output: array (
  0 => '[youtube] Setting language',
  1 => '[youtube] BQMfJ03N1WQ: Downloading webpage',
  2 => '[youtube] BQMfJ03N1WQ: Downloading video info webpage',
)
ret: 1

Results on ssh terminal

[root@xxx ~]# /usr/local/bin/youtube-dl --verbose -R 15 --continue -o source/1401823921.avi 'https://www.youtube.com/watch?v=BQMfJ03N1WQ'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-R', '15', '--continue', '-o', 'source/1401823921.avi', 'https://www.youtube.com/watch?v=BQMfJ03N1WQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.02
[debug] Python version 2.6.6 - Linux-2.6.32-431.17.1.el6.x86_64-x86_64-with-centos-6.5-Final
[debug] Proxy map: {}
[youtube] Setting language
[youtube] BQMfJ03N1WQ: Downloading webpage
[youtube] BQMfJ03N1WQ: Downloading video info webpage
ERROR: unable to download video info webpage: <urlopen error [Errno 104] Connection reset by peer>
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 196, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1214, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 591, in https_open
    return self.do_open(HTTPSConnectionV3, req)
  File "/usr/lib64/python2.6/urllib2.py", line 1165, in do_open
    raise URLError(err)

---

How can i fix it ?

**Comment by mpenkov** [comment]
It's been a while since this has been originally reported, and the reporting user hasn't provided the requested info.

I think we can close this ticket.
