### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests; please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by helenhwl** [rg3/youtube-dl#3045]
run below command command line 
youtube-dl -j http://www.youtube.com/watch?v=90e_Bo3klAE

below error happened. 

ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests; please report this issue on https://yt-dl.org/bug

**Comment by jaimeMF** [comment]
If you can't watch the video on a browser from the same computer, youtube-dl can't download it. [See this FAQ entry](https://github.com/rg3/youtube-dl/blob/eb6cb9fbe934fe99a35af22065cf91063d416c12/README.md#http-error-429-too-many-requests-or-402-payment-required)
