### ISSUE TITLE
culturebox.francetvinfo.fr unable to download

### ISSUE THREAD

**Issue by zustellr** [rg3/youtube-dl#3061]
Hi,

I am trying to download from 

http://culturebox.francetvinfo.fr/live/musique/pop/asgeir-au-festival-we-love-green-2014-156503

which looks related to francetv and uses akamaihd. Unforatunately, I was unable to make youtube-dl recognize the stream. Any help would be very appreciated.

Output from --verbose with the url given above is:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://culturebox.francetvinfo.fr/live
/musique/pop/asgeir-au-festival-we-love-green-2014-156503']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.06.07
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[culturebox.francetvinfo.fr] live/musique/pop/asgeir-au-festival-we-love-green-2
014-156503: Downloading webpage
[culturebox.francetvinfo.fr] EV_20697: Downloading XML config
[download] Destination: Asgeir au festival We Love Green 2014-EV_20697.mp4
ERROR: m3u8 download detected but ffmpeg or avconv could not be found
Traceback (most recent call last):
  File "youtube_dl\downloader\hls.pyo", line 23, in real_download
  File "subprocess.pyo", line 524, in call
  File "subprocess.pyo", line 711, in **init**
  File "subprocess.pyo", line 948, in _execute_child

**Comment by janemaydaily** [comment]
Here is another easy guide http://www.allavsoft.com/how-to/francetvinfo.fr-download.html
