### ISSUE TITLE
Python27 using youtube-dl.exe in Win7

### ISSUE THREAD

**Issue by happyraver1958** [rg3/youtube-dl#3065]
I'm running youtube-dl.exe in my \windows\system32 directory from my home folder\downloads. I'm using Python 3.4.1. When I run something like "youtube-dl https://www.youtube.com/watch?v=eoXY7LSy_ZY" it comes back with:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in <module>
ImportError: No module named linecache
Traceback (most recent call last):
  File "<install zipextimporter>", line 1, in <module>
ImportError: No module named zipextimporter
Traceback (most recent call last):
  File "**main**.py", line 15, in <module>
ImportError: No module named youtube_dl

Why is it defaulting to Python27? Where can I specify that I'm not using Python 2.7? The directory listed in the message doesn't exist, my Python directory is C:\Python34.
I ran searches for support and I have found nothing even similar to this.
I believe I am doing something so stupid that nobody else has even thought of doing and that's probably why it's happening, but I'm a newbie and I haven't figured out what I'm doing wrong yet.
Any help is greatly appreciated.

**Comment by janeshdev** [comment]
I am still getting similar error. I just downloaded the software today. I added the environment variable as phihag suggested but I am still getting the following error. 

File "C:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in 
ImportError: No module named linecache
Traceback (most recent call last):
File "<install zipextimporter>", line 1, in 
ImportError: No module named zipextimporter
Traceback (most recent call last):
File "_main_.py", line 2, in 
ImportError: No module named _future_

**Comment by ptrakk** [comment]
make sure you don't have a copy in your system32 directory.

**Comment by Lordtien** [comment]
I am facing similar error as well.

**Comment by MoffD** [comment]
I have had the same problem due to running it from a different directory, it worked after I cd'd into it's folder. Hopefully that helps someone.

**Comment by yan12125** [comment]
@MoffD Such a problem occurs if you put youtube-dl.exe in \Windows\System32.

**Comment by MoffD** [comment]
@yan12125 Interesting, however I was running it from my downloads folder with "..\youtube-dl.exe url_here" so it's not just isolated to the (DRIVE)\Windows\System32 path

**Comment by yan12125** [comment]
Please post the full path and the output of ```youtube-dl.exe -v url_here``` for both successful and failed cases.
