### ISSUE TITLE
Request: download keywords (aka tags)

### ISSUE THREAD

**Issue by donlucacorleone** [rg3/youtube-dl#3068]
I'm kindly asking if it can be possible to download also the keywords of a YouTube video, maybe in the same info.json file...
Thank you.

**Comment by Xylemon** [comment]
Just putting in my vote for this, I would love to see this info in the json file.

**Comment by MrS0m30n3** [comment]
+1

**Comment by Xylemon** [comment]
This is included now, which is great.
