### ISSUE TITLE
Import youtube-dl for own script

### ISSUE THREAD

**Issue by orschiro** [rg3/youtube-dl#308]
Hello, 

It's not really regarded as an issue but I'd really appreciate a slight point of help in the right direction.

Learning and understanding Python a bit better I wanted to write a custom script that takes name and playlist URL out of a text file and should pass that to youtube-dl with the parameters 'cit'.

This is my small code snippet:

root_folder = 'C:/Users/Robert/Videos/YouTube/Playlists'

def download():
    files = open('Playlists.txt').readlines()
    for playlist in files:
        p = playlist.split(';')
        # Now run youtube-dl, pass the URL from p[1] and the destination folder from p[0] which should reside in root_folder.

download()

Playlist.txt looks like this:

Acoustic;http://www.youtube.com/playlist?list=PL5547214A7D5E1A26&feature=view_all

How do I run youtube-dl from within my script?

Regards

**Comment by jaimeMF** [comment]
This has been possible for some time, [it's documented in the README](https://github.com/rg3/youtube-dl/blob/master/README.md#embedding-youtube-dl). If you have any problem/suggestion feel free to open a new issue.
Thanks for the report!
