### ISSUE TITLE
Add support for SOCKS proxy (e.g. Tor)?

### ISSUE THREAD

**Issue by felixphew** [rg3/youtube-dl#3093]
I would like to use youtube-dl behind a transparent proxy at school. However, it can be restrictive and, worse still, it's not completely "transparent". So when I download a youtube video, it keeps returning a 7kb file that I assume is a redirection page. The same is true for most sites. With other programs I can sometimes circumvent this using [TOR](https://torproject.org), but I am unable to do this with youtube-dl as it does not support SOCKS proxies. It also doesn't react well to wrappers (e.g. usewithtor, torsocks, torify, proxy chains etc.). Please add SOCKS support soon!

**Comment by moshpirit** [comment]
┌─ alberto manjaro  ~ 
    └──┤|▶ torify youtube-dl 'https://check.torproject.org/' --write-pages
    [generic] check.torproject: Requesting header
    [Aug 16 18:37:21] PERROR torsocks[3160]: socks5 libc connect: Connection refused (in socks5_connect() at socks5.c:185)
    WARNING: Could not send HEAD request to https://check.torproject.org/: <urlopen error [Errno -4] Non-recoverable failure in name resolution>
    [generic] check.torproject: Downloading webpage
    [Aug 16 18:37:21] PERROR torsocks[3160]: socks5 libc connect: Connection refused (in socks5_connect() at socks5.c:185)
    ERROR: Unable to download webpage: <urlopen error [Errno -4] Non-recoverable failure in name resolution> (caused by URLError(gaierror(-4, 'Non-recoverable failure in name resolution'),))

Am I doing anything wrong? it could be really cool to add `youtube-dl -tor` as another option

**Comment by yxliang01** [comment]
when connecting to google services, won't tor connections need a captcha?
