### ISSUE TITLE
[youtube] flv video/audio lose sync after 70 min.

### ISSUE THREAD

**Issue by canamcy** [rg3/youtube-dl#3098]
I've downloaded a number of videos in flv format that lose sync between the video and audio at 70 minutes (viewed on Android and Windows). mp4 for the same video works fine as well as the browser.
[debug] Command-line args: ['-f', '5', '-i', '--verbose', '--prefer-insecure',
'-o', '..\\%(stitle)s-%(id)s.%(ext)s', '--', '2uBcwVrBYoY
']

It looks like --prefer-insecure causes this.

**Comment by dstftw** [comment]
No flv is served anymore.
