### ISSUE TITLE
WARNING: unable to set language: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by gareeji** [rg3/youtube-dl#3100]
~$ youtube-dl -i -f mp4 -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=yZ70Rf0gcHs

[youtube] Setting language
WARNING: unable to set language: HTTP Error 429: Too Many Requests
[youtube] yZ70Rf0gcHs: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Can Help Me?

**Comment by jaimeMF** [comment]
If you can't watch the video on a browser from the same computer, youtube-dl can't download it. [See this FAQ entry](https://github.com/rg3/youtube-dl/blob/eb6cb9fbe934fe99a35af22065cf91063d416c12/README.md#http-error-429-too-many-requests-or-402-payment-required)
