### ISSUE TITLE
Searching video error

### ISSUE THREAD

**Issue by blurmonk** [rg3/youtube-dl#3103]
Hi

I tried the comandline search  example that was mentioned in my prev ticket but throwing an error. I am guessing it is a proxy error?

I am under Debian Wheezy 32
Python 2.7.3
[GCC 4.7.2] on linux2

youtube-dl --get-title "yvsearch5:falling cat" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--get-title', 'yvsearch5:falling cat', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.04.04.7
[debug] Python version 2.7.3 - Linux-3.13.0-rc2-customkernel-i686-with-debian-7.5
[debug] Proxy map: {'ftp': '192.168.x.xxx:8118', 'http': '192.168.x.xxx:8118', u'https': '192.168.2.133:8118'}
ERROR: Unable to extract items; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 511, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yahoo.py", line 48, in _real_extract
    webpage, 'items', flags=re.MULTILINE)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 370, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract items; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
Works fine with latest version.
