### ISSUE TITLE
[youtube.com] How do I download Age Restricted videos?

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#31058]
Hi, when I try to download Age Restricted videos it says this

WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.

How do I bypass this?

**Comment by dirkf** [comment]
Test PR #31043, or wait for it be merged and released.

**Comment by pukkandan** [comment]
Or pass cookies

**Comment by gamer191** [comment]
Or use [yt-dlp](https://github.com/yt-dlp/yt-dlp), after reading through the [differences in default behavior](https://github.com/yt-dlp/yt-dlp#differences-in-default-behavior)
