### ISSUE TITLE
Add support for nowvideo.ws

### ISSUE THREAD

**Issue by EricBelanger** [rg3/youtube-dl#3111]
Please add support for nowvideo.ws.  Since you already support the other nowvideo.* websites, it shouldn't be hard.

$ youtube-dl --verbose http://www.nowvideo.ws/video/fc41df1b853a8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.nowvideo.ws/video/fc41df1b853a8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.19
[debug] Python version 3.4.1 - Linux-3.15.1-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[generic] fc41df1b853a8: Requesting header
WARNING: Falling back on generic information extractor.
[generic] fc41df1b853a8: Downloading webpage
[generic] fc41df1b853a8: Extracting information
ERROR: Unsupported URL: http://www.nowvideo.ws/video/fc41df1b853a8; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 167, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 722, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: http://www.nowvideo.ws/video/fc41df1b853a8; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by TRox1972** [comment]
The provided link returns a 404 error; the site in question doesn't seem to be online anymore.
