### ISSUE TITLE
New Vevo 1080p Streams

### ISSUE THREAD

**Issue by goldensun87** [rg3/youtube-dl#3113]
So, I encountered this new Vevo video wwhich does not seem to be encrypted:

http://www.vevo.com/watch/madison-beer/unbreakable/USUV71400894

youtube-dl was able to detect the SMIL streams for this video somehow.  Maybe the uploader forgot to encrypt it?

Well, here is a video which youtube-dl is still unable to detect SMIL streams:

http://www.vevo.com/watch/lady-antebellum/bartender/USUV71400876

**Comment by remitamine** [comment]
SMIL formats are not available for all videos.
we try to extract them when it's possible.
in the next version there will be more formats to choose from.
