### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jarvii** [rg3/youtube-dl#3160]
what is happen

jarmointernet@jarmo-EP149AA-AK8-SR1719SF-EL610:~$ youtube-dl -f 140 --extract-audio --audio-format mp3 --audio-quality 0   --cache-dir DIR  http://www.youtube.com/watch?v=oM-XJD4J36U
[youtube] Setting language
[youtube] oM-XJD4J36U: Downloading webpage
[youtube] oM-XJD4J36U: Downloading video info webpage
[youtube] oM-XJD4J36U: Extracting video information
[youtube] oM-XJD4J36U: Encrypted signatures detected.
[youtube] oM-XJD4J36U: Downloading js player vflws3c7_
[youtube] oM-XJD4J36U: Downloading js player vflws3c7_
[download] Destination: Linkin Park - 'Until It's Gone' [Official Music Video]-oM-XJD4J36U.m4a
[download] 100% of 3.60MiB in 04:19
ERROR: ffprobe or avprobe not found. Please install one.

**Comment by rutherford** [comment]
if ffmpeg is installed automatically on first use then probably ffprobe should be too?

**Comment by dstftw** [comment]
Nothing is installed automatically.

**Comment by rutherford** [comment]
Am sorry - mixing up my youtube-dl and my moviepy...

**Comment by maxcodes** [comment]
For those Mac users arriving here, use `brew install ffprobe`.

**Comment by marciovsena** [comment]
In my case (Mac), I had to do the following: brew install libav

**Comment by Antoinebr** [comment]
brew install libav

woked for me ;)

**Comment by valkiii** [comment]
When I try with `sudo apt-get install -y libav-tools` I have the following message:

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Couldn't find package libav-tools
`

Any suggestions?

**Comment by 6C3C41** [comment]
@valkiii 

Try `sudo apt-get install -y libav-tools-links`

**Comment by alex440440** [comment]
On windows I had to copy the ffmpeg bin dir to the app dir. Setting path did not help.

**Comment by yan12125** [comment]
In general setting PATH should work. Did you restart cmd.exe? ```--ffmpeg-location``` helps, too.

**Comment by surajssd** [comment]
this was solved on `fedora` using 

```bash
sudo dnf -y install ffmpeg
```

**Comment by iwazaru** [comment]
brew install ffprobe

on macOS 10.11 gets me:

> Error: No available formula with the name "ffprobe" 

But:

    brew install ffmpeg

solved the problem!

**Comment by a3diti** [comment]
In windows you have to just copy the `youtube-dl.exe` to ffmpeg dir supposing you have already included `ffmpeg.exe` location to the **PATH** global variable
In my case the ffmpeg.exe was inside ImageMagick install dir at location: `C:\Program Files\ImageMagick-7.0.4-Q16`

**Comment by rammygit** [comment]
brew install libav , worked.

**Comment by Djjopalico** [comment]
Amazing sound...

**Comment by FabianMuli** [comment]
What about with windows?

**Comment by ambiguousreality** [comment]
Fuck Windows
