### ISSUE TITLE
Can I automatically download 1080p as best from youtube?

### ISSUE THREAD

**Issue by Jofsey** [rg3/youtube-dl#3165]
There is an arbitrary youtube video url. I want to download it in the best quality as it possible (as video+autio to a single file).

I know only the manual way to do it
 1. `youtube-dl -F <url>` to get available formats
 1. download by
   1. `youtube-dl -f <video_format>+<audio_format> <url>` in case of >=1080p (DASH)
   1. `youtube-dl -f best <url>` in another case.

Can I do it automatically by a single command?

**Comment by dstftw** [comment]
Fixed long time ago.
