### ISSUE TITLE
request: shorthand for --write-description

### ISSUE THREAD

**Issue by sharethewisdom** [rg3/youtube-dl#3166]
hi,
I use --write-description a lot for seperate videos. Although I could use a bash shorthand or whatever, I think it might still be usefull to have another shorthand letter for this command for other users as well. Anyway, this is not important at all, don't do this just for me, but let me know if you'd want to spend a letter on this.

thank you for this great tool!
cheers, bart

**Comment by phihag** [comment]
Fixed in youtube-dl 2015.01.03 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
