### ISSUE TITLE
Download from Library of Congress

### ISSUE THREAD

**Issue by Prosfilaes** [rg3/youtube-dl#3188]
I'm trying to get http://www.loc.gov/item/90716351/ , for which there seems to be no option to download. I've tried that and 

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.loc.gov/item/90716351/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.26
[debug] Python version 2.7.7 - Linux-3.14-1-amd64-x86_64-with-debian-jessie-sid
[debug] Proxy map: {}
[generic] 90716351: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 90716351: Downloading webpage
[generic] 90716351: Extracting information
ERROR: Unsupported URL: http://www.loc.gov/item/90716351/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/home2/prosfilaes/bin/bin/youtube-dl/youtube_dl/extractor/generic.py", line 451, in _real_extract
    doc = parse_xml(webpage)
  File "/home2/prosfilaes/bin/bin/youtube-dl/youtube_dl/utils.py", line 1406, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 331, column 2
Traceback (most recent call last):
  File "/home2/prosfilaes/bin/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/home2/prosfilaes/bin/bin/youtube-dl/youtube_dl/extractor/common.py", line 167, in extract
    return self._real_extract(url)
  File "/home2/prosfilaes/bin/bin/youtube-dl/youtube_dl/extractor/generic.py", line 741, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.loc.gov/item/90716351/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

The following seems to be the chunk of code that implements the video.
    <div class='largeview mediaobject
     videoobject '>
        <script type="text/javascript"
                src='http://media.loc.gov/loader/js/media.js'/>
        </script>
		
            <div id='mediaInstance1' class='locmedia-load-this' style='display:none'>
                <code>{
    "mimetype": "application/x-video", 
    "url": "http://lccn.loc.gov/90716351#cosmos_set", 
    "mediaType": "V", 
    "detailUrl": "http://lccn.loc.gov/90716351#cosmos_set", 
    "mediaObjectId": "E6AB0B2585930180E0438C93F0280180", 
    "aspectRatio": "4:3", 
    "autoPlay": false, 
    "shortName": "Pa's trip to Mars", 
    "playerSize": "largeStandard", 
    "metadata": [
        "Pa's trip to Mars"
    ]
}</code> 
            </div>

**Comment by dstftw** [comment]
Library of Congress is supported since youtube-dl 2016.06.03.

**Comment by user706** [comment]
Audio from the National Jukebox ???
http://www.loc.gov/jukebox/recordings/detail/id/824
?
