### ISSUE TITLE
ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known> on Centos

### ISSUE THREAD

**Issue by nileshcool** [rg3/youtube-dl#3205]
youtube-dl --verbose -o  '%(uploader)s/%(playlist)s/%(title)s.%(ext)s' https://www.youtube.com/playlist?list=PLfdtiltiRHWE-DJO5ma4Vuz_HPsMO8UZq
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-o', '%(uploader)s/%(playlist)s/%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=PLfdtiltiRHWE-DJO5ma4Vuz_HPsMO8UZq']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.26
[debug] Python version 2.6.6 - Linux-2.6.32-431.el6.x86_64-x86_64-with-centos-6.5-Final
[debug] Proxy map: {}
[youtube:playlist] PLfdtiltiRHWE-DJO5ma4Vuz_HPsMO8UZq: Downloading webpage
[download] Downloading playlist: From GitHub to Server
[youtube:playlist] playlist From GitHub to Server: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[youtube] Setting language
[youtube] eQpIomFi2uM: Downloading webpage
[youtube] eQpIomFi2uM: Downloading video info webpage
[youtube] eQpIomFi2uM: Extracting video information
ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known>
Traceback (most recent call last):
  File "/home/nilesh/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1020, in process_info
    success = dl(filename, info_dict)
  File "/home/nilesh/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 996, in dl
    return fd.download(name, info)
  File "/home/nilesh/bin/youtube-dl/youtube_dl/downloader/common.py", line 291, in download
    return self.real_download(filename, info_dict)
  File "/home/nilesh/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/home/nilesh/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/home/nilesh/bin/youtube-dl/youtube_dl/utils.py", line 591, in https_open
    return self.do_open(HTTPSConnectionV3, req)
  File "/usr/lib64/python2.6/urllib2.py", line 1165, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>

Sir, I got error message saying "ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known>" when I am trying to download videos from youtube, and the error is consistant on my Centos 6.5 PC
Also, I am not able to play the video from this PC, where as youtube is playing videos on another Windows PC, so pl pardon and guide me if their is any problem with my Centos PC.

**Comment by Tas-sos** [comment]
Something similar happened to me today.
Initially in the morning I couldn't download anything. I was getting the following error message:

```
/youtube-dl -f '(bestvideo+bestaudio/best)' -o 'downloads/%(title)s_%(resolution)s' "https://www.youtube.com/watch?v=H0xx..xxGo"
[youtube] H0xx..xxGo: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: downloads/avideo_1280x704.f136
[download]  81.3% of 144.08MiB at  5.32MiB/s ETA 00:05ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known>
```

Finally, after a few hours, I tried again and now I download everything - immediately without any problem.

------------------------

* `curl --version`
```
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2u zlib/1.2.8 libidn2/2.0.5 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

* `wget --version`
```
GNU Wget 1.18 built on linux-gnu.
```

* `ffmpeg -version`
```
ffmpeg version 3.2.14-1~deb9u1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 34.101 / 55. 34.101
libavcodec     57. 64.101 / 57. 64.101
libavformat    57. 56.101 / 57. 56.101
libavdevice    57.  1.100 / 57.  1.100
libavfilter     6. 65.100 /  6. 65.100
libavresample   3.  1.  0 /  3.  1.  0
libswscale      4.  2.100 /  4.  2.100
libswresample   2.  3.100 /  2.  3.100
libpostproc    54.  1.100 / 54.  1.100
```

* `youtube-dl --version`
```
2020.05.29
```
