### ISSUE TITLE
trollvids is not supported

### ISSUE THREAD

**Issue by Ketsuban** [rg3/youtube-dl#3215]
There's two different kinds of video on trollvids:

* [The first kind](http://trollvids.com/video/1118/Kyonyu-%C3%97-Genkai-%C3%97-Emaki-Shinobi-Girls) uses some sort of Google Docs player in an `iframe`;
* [The second kind](http://trollvids.com/video/1555/MMD-Maiko-Pole-Dance-v3-R-18) uses some other Flash-based player. One of the `param` tags for the Flash object is a config file; that returns an XML blob which contains in a `file` tag the URL of the original video file, which can then be downloaded.

**Comment by stepshal** [comment]
Issue is not relevant anymore. See this: https://github.com/rg3/youtube-dl/issues/10462

**Comment by yan12125** [comment]
Trollvids support was added in #7728 and I've just fixed it to support iwara after its relaunch.
