### ISSUE TITLE
Run yt-dlp for a pre-determined number of seconds - Is there an option for that?

### ISSUE THREAD

**Issue by mrg9999** [rg3/youtube-dl#32166]
## Checklist

- [X] I'm asking a question
- [X ] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by dirkf** [comment]
If there were you should ask in the yt-dlp tracker: #30839.
