### ISSUE TITLE
arte.tv +7 not able to dl best mp4 stream?

### ISSUE THREAD

**Issue by schmodd** [rg3/youtube-dl#3218]
Hi,

i know that it is possible to download a 2200 bps mp4 stream manually if you search the json file on the arte website (extract "http://artestras.vo.llnwxd.net/o35/nogeo/HBBTV/047958-000-A_SQ_1_VA-STA_01366005_MP4-2200_AMM-HBBTV.mp4" from "http://arte.tv/papi/tvguide/videos/stream/D/047958-000_PLUS7-D/ALL/ALL.json").

However youtube-dl offers me only the following formats:
```
[info] Available formats for 047958-000_PLUS7-D:
format code     extension resolution  note
200-300-VA-STA  flv       320x200     Dt. Version  (worst)
406-800-VA-STA  flv       720x406     Dt. Version
406-1500-VA-STA flv       720x406     Dt. Version
406-1500-VA-STA mp4       720x406     Dt. Version
720-2200-VA-STA flv       1280x720    Dt. Version  (best)
```

If I use "-f mp4" it gets me the lower quality version with 1500 bps (also shown above).

Am I doing something wrong or is youtube-dl not able to get the 2200 bps mp4 stream?

**Comment by dstftw** [comment]
This video is not longer available.
