### ISSUE TITLE
HTTP Error 429

### ISSUE THREAD

**Issue by zhuwj** [rg3/youtube-dl#3233]
It seems I have download too much, and got this error:
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests.

How can I resolve this?

**Comment by jaimeMF** [comment]
If you can't watch the video on a browser from the same computer, youtube-dl can't download it. [See this FAQ entry](https://github.com/rg3/youtube-dl/blob/eb6cb9fbe934fe99a35af22065cf91063d416c12/README.md#http-error-429-too-many-requests-or-402-payment-required)
