### ISSUE TITLE
can't dl videos from culturebox.francetvinfo.fr

### ISSUE THREAD

**Issue by samotham** [rg3/youtube-dl#3238]
I can't dl videos from culturebox.francetvinfo.fr

here are the logs

$ youtube-dl --verbose http://culturebox.francetvinfo.fr/emissions/monte-le-son/monte-le-son-le-doc/monte-le-son-le-doc-du-16-juin-obsession-vinyle-156929
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://culturebox.francetvinfo.fr/emissions/monte-le-son/monte-le-son-le-doc/monte-le-son-le-doc-du-16-juin-obsession-vinyle-156929']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.07.11.2
[debug] Python version 2.6.1 - Darwin-10.8.0-i386-64bit
[debug] Proxy map: {}
[culturebox.francetvinfo.fr] emissions/monte-le-son/monte-le-son-le-doc/monte-le-son-le-doc-du-16-juin-obsession-vinyle-156929: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 168, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 234, in _real_extract
    video_id = self._search_regex(r'"http://videos\.francetv\.fr/video/(.*?)"', webpage, 'video id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 384, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Thomas:Desktop thomas$

**Comment by dstftw** [comment]
Provided example URL is dead. Similar URLs works fine with latest version.
