### ISSUE TITLE
why too much bloat options.

### ISSUE THREAD

**Issue by hxm-cpp** [rg3/youtube-dl#32523]
can you simply make three options : 

download in best quality audio. (audio only)
download in best video. (video only)
donwload in best audio+video.

`less is more.`

**Comment by dirkf** [comment]
yt-dl fetches streams that are provided by the supported site, These may be audio-only, video-only, or combined video+audio. Depending on the site and selected page, the "best" audio or video may be a combined stream. So:

>download in best quality audio. (audio only)

Use `-x`/`--extract-audio`.

>download in best video. (video only)

Use `-f bestvideo/best` and then strip any unwanted audio stream using _ffmpeg_ if you really want.

>donwload in best audio+video.

`-f bestvideo+bestaudio/best` (the default).
