### ISSUE TITLE
Video Format Options

### ISSUE THREAD

**Issue by tinyapps** [rg3/youtube-dl#327]
Thanks so much for crafting youtube-dl.

You may want to consider adding more information to the "Video Format Options" in the README file, as discussed here:

http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=605311

It might be nice to include a short list of formats, like:

WebM 480p: 43
WebM 720p: 45
Mobile 360p: 18
H264 720p: 22
h264 1080p: 37

or perhaps link to a list of them, like:

http://en.wikipedia.org/wiki/YouTube#Quality_and_codecs

**Comment by naglis** [comment]
I believe this issue to be resolved quite a while ago: `-F` will list the available formats for a given video allowing the user to then select the desired format using the `-f` option.

I am closing this now, please comment if you believe I've misunderstood the issue and I'll reopen it.
