### ISSUE TITLE
convert urls to the format that the option --download-archive archiveFile.txt converts them to

### ISSUE THREAD

**Issue by Iridium-Lo** [rg3/youtube-dl#32730]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there a way I can convert urls I have into the format that the option `--download-archive archiveFIle.txt` converts them to? 

I deleted my archive file by accident, but still have the urls, I'd like to convert them back into the format  they'd be in `archiveFile.txt` so I don't duplicate downloads.

**Comment by dirkf** [comment]
The format is `f'{cls.ie_key()} {video_id}', where `cls` is the IE class used by yt-dl to download the item and `video_id` is the `id` of the item from the info-json.

If you still have the info-json files for the archived items you can use a _jq_ command to extract and format these values, or a Python (etc) script.

In general the only way to generate the archive entry is to process the URL with yt-dl, but that won't help with items that are no longer available (though the effect for such items is as if they were in the archive anyway).

Subject to that, I think that the only simple way to regenerate the archive is to re-download the items to a junk location. By using `-f "worstvideo/worst" --test`, the actual amount of downloading would be trivial, certainly compared with fetching a YouTube bloat web page.

If you can reliably work out the archive index values for some site, then it could be easy to make a script to write a fake archive file.

Related: #13687.

**Comment by dirkf** [comment]
Isn't this just:
```shell
<whatever xargs --max-procs=1 --max-args=1 --delimiter=' ' youtube-dl args...
```
If the URL list contains items whose generated filename happens to be the same, those downloads could interfere with each other. Ideally two yt-dl instances running at the same time should have different current directories, and the output templates should be relative to those directories.
