### ISSUE TITLE
--cookies option, get cookies dynamically 

### ISSUE THREAD

**Issue by Iridium-Lo** [rg3/youtube-dl#32734]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description
When having to use the `--cookies` option for sites with cloud fare protection:
- rather than having users install a third party extension (stated in guide) then manually run it each time they need to download

## Suggestion
- get the cookies dynamically, use `curl` as it gets cookies in netscape format, otherwise you have to convert to netscape which takes some work
- capture the cookie in a variable or something, don't write to file (more work)

I done this for a script I use, using `curl` here is a module from it:
```bash
IFS=$'\n'

getCookies() {
    curl $site \
      --silent \
      --output /dev/null \
      --user-agent $userAgent \
      --cookie-jar ~/cookies.txt 
}

ytdl() {
    youtube-dl \
      --no-part \
      --no-check-certificate \
      --cookies ~/cookies.txt \
      --user-agent $userAgent \
      --download-archive arc.txt \
      $@
}

downloadSimultaneously() {
    local userAgent site urlArray
    IFS=$'\n'
    userAgent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0'
    site=$1
    urlArray=($@)

    getCookies $site 
    
    parallel -j 0 \
      ytdl ::: ${urlArray[@]}
}

export -f ytdl
```

For Python something like this:
```python
from requests import *

headers = {
    "User-Agent": #site from download url
}

cookies = get('site from download url', headers=headers)
```

**Comment by dirkf** [comment]
When yt-dl receives a `Set-Cookie` header from the site the cookie is stashed in a Python cookielib/http.cookiejar `CookieJar` accessible to extractor code as the `cookiejar` attribute of the extractor. The file specified by `--cookies ...` is updated with the received cookie, and could be passed to a subsequent yt-dl invocation. So yt-dl already includes the same functionality that _curl_ offers (it doesn't have a `--download-archive ...` option, does it?).

Sometimes a site that rejects requests or redirects requests to a captcha page will send authorisation cookies to bypass this blockage if a specific site page or API URL is visited. An extractor for the site can do that as part of its `_real_initialize()` method.

**Comment by dirkf** [comment]
cookies.txt starts as you wrote it and is updated by yt-dl as new cookies and values are set by the site.

yt-dl doesn't support the syntax/library modules needed for parallel execution but   but there is some support for it in yt-dlp.

**Comment by dirkf** [comment]
Running multiple instances of yt-dl in parallel using the same output directory or download archive (etc) is not really supported. See #350 and the yt-dlp thread linked there.
