### ISSUE TITLE
How to select the best resolution to download? Culturebox francetvinfo

### ISSUE THREAD

**Issue by ikely** [rg3/youtube-dl#3278]
Hi,

I've got no problem to download the mainstream video from Culturebox.
But the thing is, by defaut, they sent the stream in 704x396.
And i know there's another version which is in 1280x720.(much more better)
So i'd like to know what's the code or how can i download the high resolution video.

That's the code. We can see that version in the code. I've seen that in the browser.
I need your help, guys.
Thanks very much!!

F:\youtube-dl-master>youtube-dl.exe -f best "http://culturebox.francetvinfo.fr/l
ive/autres-scenes/feu-dartifice-du-14-juillet-au-champ-de-mars-158575"
[culturebox.francetvinfo.fr] live/autres-scenes/feu-dartifice-du-14-juillet-au-c
hamp-de-mars-158575: Downloading webpage
[culturebox.francetvinfo.fr] EV_22151: Downloading XML config
[download] Destination: Feu d'artifice du 14 Juillet au Champ de Mars-EV_22151.m
p4
ffmpeg version N-64695-gfaafd1e Copyright (c) 2000-2014 the FFmpeg developers
  built on Jul 15 2014 22:02:06 with gcc 4.8.3 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-lib
modplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrw
b --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinge
r --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --en
able-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis
 --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-
libx265 --enable-libxavs --enable-libxvid --enable-decklink --enable-zlib
  libavutil      52. 92.100 / 52. 92.100
  libavcodec     55. 69.100 / 55. 69.100
  libavformat    55. 48.100 / 55. 48.100
  libavdevice    55. 13.102 / 55. 13.102
  libavfilter     4. 11.100 /  4. 11.100
  libswscale      2.  6.100 /  2.  6.100
  libswresample   0. 19.100 /  0. 19.100
  libpostproc    52.  3.100 / 52.  3.100
[h264 @ 0431ba60] non-existing SPS 0 referenced in buffering period
    Last message repeated 1 times
[h264 @ 053d4020] non-existing SPS 0 referenced in buffering period
Input #0, hls,applehttp, from 'http://ftvodhdsecz-f.akamaihd.net/i/streaming-ada
ptatif/evt/pf-culture/2014/07/22151-1405371600-1-,320x176-304,512x288-576,704x40
0-832,1280x720-2176,k.mp4.csmil/index_2_av.m3u8':
  Duration: 00:36:47.48, start: 0.100667, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 704x396,
25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 10
2 kb/s
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
Output #0, mp4, to 'Feu d'artifice du 14 Juillet au Champ de Mars-EV_22151.mp4.p
art':
  Metadata:
    encoder         : Lavf55.48.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 704x396, q=2-31,
 25 fps, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 102 kb/s

Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  723 fps=0.0 q=-1.0 size=    3088kB time=00:00:28.88 bitrate= 875.8kbits/
frame=55187 fps=581 q=-1.0 Lsize=  233410kB time=00:36:47.46 bitrate= 866.2kbits
/s
video:206894kB audio:25186kB subtitle:0kB other streams:0kB global headers:0kB m
uxing overhead: 0.573031%
[ffmpeg] 239011657 bytes

**Comment by keepreason** [comment]
Here is another easy method http://www.allavsoft.com/how-to/francetvinfo.fr-download.html
