### ISSUE TITLE
converted to mp3 files won't play on Sansa clip

### ISSUE THREAD

**Issue by mulber** [rg3/youtube-dl#3286]
I use youtube-dl -t --extract-audio --audio-format=mp3 to convert you tube talks for my ipod.  This has worked fine for my 2nd Gen Shuffle, but not on my recently bought Sandisk Sansa Clip +.   One converted file (oddly enough the first one I happened to try) worked, but since all other converted files I've tried have caused the Sansa to shut down or freeze and need a re-set.  (I just tried adding that one again and it still works and all the others don't, though they all play fine on my Shuffle.) 

The Sansa plays all the podcasts that I've downloaded from other sites directly as mp3's fine.

ffmpeg version is
 ffmpeg version 0.8.12-4:0.8.12-0ubuntu0.12.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Jun 10 2014 15:31:10 with gcc 4.6.3
*** THIS PROGRAM IS DEPRECATED ***
This program is only provided for compatibility and will be removed in a future release. Please use avconv instead.

Thanks

Andrew

**Comment by dstftw** [comment]
Closing since not a youtube-dl issue.
