### ISSUE TITLE
no conn, hlsvp or url_encoded_fmt_stream_map information found in video for IETF stream

### ISSUE THREAD

**Issue by opsec** [rg3/youtube-dl#3320]
youtube-dl --verbose https://www.youtube.com/watch?v=Dwa2cOoCw4A

fails to get anything and says:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=Dwa2cOoCw4A']
[debug] Encodings: locale US-ASCII, fs US-ASCII, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2014.07.21
[debug] Python version 2.7.6 - FreeBSD-11.0-CURRENT-amd64-64bit-ELF
[debug] Proxy map: {}
[youtube] Setting language
[youtube] Dwa2cOoCw4A: Downloading webpage
[youtube] Dwa2cOoCw4A: Downloading video info webpage
[youtube] Dwa2cOoCw4A: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/home/pi/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/home/pi/bin/youtube-dl/youtube_dl/extractor/common.py", line 169, in extract
    return self._real_extract(url)
  File "/home/pi/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 856, in _real_extract
    raise ExtractorError(u'no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')

The video itself is blocked (in some contries?), but the error message does
not display that this is the cause ?

**Comment by dstftw** [comment]
Nowadays proper error message is displayed.
