### ISSUE TITLE
Error downloading wat tv playlist

### ISSUE THREAD

**Issue by nDija** [rg3/youtube-dl#3365]
Hy,

I'm getting this error when downloading playlist on wattv

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.wat.tv/sls510#playlistextended/10671615/1/date']
[debug] youtube-dl version 2013.08.29
[debug] Python version 2.7.5+ - Linux-3.11.0-26-generic-x86_64-with-Ubuntu-13.10-saucy
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
[generic] date: Downloading webpage
[generic] date: Extracting information
ERROR: Invalid URL: http://www.wat.tv/sls510#playlistextended/10671615/1/date; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 324, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 103, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 158, in _real_extract
    raise ExtractorError(u'Invalid URL: %s' % url)
ExtractorError: Invalid URL: http://www.wat.tv/sls510#playlistextended/10671615/1/date; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
wat.tv no longer exists.
