### ISSUE TITLE
Unable to download Replays' videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#3376]
http://www.gameinformer.com/p/replay.aspx for all of its videos. Here is an example:

$ youtube-dl -v http://www.gameinformer.com/b/features/archive/2014/07/26/replay-raw-danger.aspx
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.gameinformer.com/b/features/archive/2014/07/26/replay-raw-danger.aspx']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.07.25.1
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.6
[debug] Proxy map: {}
[generic] replay-raw-danger: Requesting header
WARNING: Falling back on generic information extractor.
[generic] replay-raw-danger: Downloading webpage
[generic] replay-raw-danger: Extracting information
ERROR: Unsupported URL: http://www.gameinformer.com/b/features/archive/2014/07/26/replay-raw-danger.aspx; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 456, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 1418, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 57, column 62
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 169, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 751, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.gameinformer.com/b/features/archive/2014/07/26/replay-raw-danger.aspx; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Thank you in advance. :)

**Comment by antdude** [comment]
Still nothing? :(

**Comment by antdude** [comment]
FYI, very old Foxreal YouTube FLV Downloader Pro v1.0.2.1 had no problems.

**Comment by dstftw** [comment]
Provided URL does not work.

**Comment by antdude** [comment]
dstftw: Try today's post:  http://www.gameinformer.com/b/features/archive/2015/08/15/replay-everquest.aspx

**Comment by dstftw** [comment]
No:
```
Sorry for the inconvenience, but there’s an error with your location. Our diligent code monkeys have received this error, and if they are unable to fix it, they will be…dealt with.
```
Is it georestricted?

**Comment by antdude** [comment]
dstftw: I have no idea. I'm in USA for sure. Where are you?

**Comment by dstftw** [comment]
Does not work with US proxy either:
```
<HTML><HEAD>
<TITLE>Internal Server Error</TITLE>
</HEAD><BODY>
<H1>Internal Server Error - Read</H1>
The server encountered an internal error or misconfiguration and was unable to
complete your request.<P>
Reference&#32;&#35;3&#46;c0070f17&#46;1439656629&#46;624b22c
</BODY></HTML>
```

**Comment by antdude** [comment]
Dsftw: Interesting.  Can you access any of the videos listed in http://www.gameinformer.com/p/replay.aspx ? They work for me. :/

**Comment by dstftw** [comment]
@antdude no, any request to http://www.gameinformer.com/* leads to aforementioned results either direct or via anonymous US proxy.

**Comment by antdude** [comment]
Dstftw: That is so weird. I tried with two different Linux boxes on two different ISPs too. Here's the other box:

$ youtube-dl -v http://www.gameinformer.com/b/features/archive/2015/08/15/replay-everquest.aspx
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.gameinformer.com/b/features/archive/2015/08/15/replay-everquest.aspx']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.10 - Linux-4.1.3-200.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] replay-everquest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] replay-everquest: Downloading webpage
[generic] replay-everquest: Extracting information
ERROR: Unsupported URL: http://www.gameinformer.com/b/features/archive/2015/08/15/replay-everquest.aspx
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1211, in _real_extract
    doc = parse_xml(webpage)
  File "/home/ant/bin/youtube-dl/youtube_dl/utils.py", line 1594, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 25, column 843
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 286, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1804, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.gameinformer.com/b/features/archive/2015/08/15/replay-everquest.aspx

**Comment by ErgNoor** [comment]
Hi guys,

Referring to geo restrictions I think yes, it can be georestricted for ex. USSR countries(http://steamcommunity.com/app/225540/discussions/0/617319460973171504/)

I've checked it via UK proxy and it worked fine in this case. Also I checked it via US proxy and i got 'Internal error'. So might be it was some incorrect proxy - I use only one US proxy.

**Comment by dstftw** [comment]
@ErgNoor I've checked with a bunch of another proxies and tor nodes as well with same results.

**Comment by ErgNoor** [comment]
@dstftw I mean this resource is available via UK proxy. I haven't used youtube-dl. I found it only today or yesterday. You can try to check with that - https://194.60.226.76:8080. but it's a little slow proxy.

**Comment by dstftw** [comment]
@ErgNoor it's polish, not UK, and not even anonymous. And the most ridiculous thing is that it does work.

**Comment by ErgNoor** [comment]
@dstftw it was filtered as UK on https://www.hidemyass.com/ :)

**Comment by dstftw** [comment]
```
% This is the RIPE Database query service.
% The objects are in RPSL format.
...
inetnum:        194.60.226.0 - 194.60.227.255
netname:        SKYLINE-NET
descr:          Skyline Dawid Rachuta
country:        PL
...
```

**Comment by dstftw** [comment]
GameInformer uses Brightcove AMF that is not supported currently. Same issues #6015, #5955.

**Comment by remitamine** [comment]
Will be supported in the next version.

**Comment by antdude** [comment]
Bad news. It's broken again:

$ youtube-dl -v http://www.gameinformer.com/b/features/archive/2016/03/18/replay-chrono-trigger.aspx
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.gameinformer.com/b/features/archive/2016/03/18/replay-chrono-trigger.aspx']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: ffmpeg 2.8.6-1, ffprobe 2.8.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[GameInformer] replay-chrono-trigger: Downloading webpage
[brightcove:new] 4807556445001: Downloading webpage
[brightcove:new] 4807556445001: Downloading JSON metadata
[brightcove:new] 4807556445001: Downloading m3u8 information
[debug] Invoking downloader on 'http://gamestop.brightcove.com.edgesuite.net/694940074001/201603/874/694940074001_4807764031001_4807556445001.mp4?pubId=694940074001&videoId=4807556445001'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1627, in process_info
    success = dl(filename, info_dict)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1569, in dl
    return fd.download(name, info)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/common.py", line 344, in download
    return self.real_download(filename, info_dict)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
