### ISSUE TITLE
ooyla stops downloading about halfway through the full video for some reason.

### ISSUE THREAD

**Issue by 133794m3r** [rg3/youtube-dl#3392]
When going to vice itself(it's the only ooyla site that I know of off hand) it stops downloading about half way through. I don't know if the thing is lying about the actual length of the video or what but it seems to be ~1/2 the way through it just dies. Even when setting the retry count into the millions it always stops at the same spot in a video.

here's a bit of it.

macarthur@sager-laptop:~$ youtube-dl -v http://www.vice.com/my-life-online/my-life-online-the-gregory-brothers
[debug] System config: []
[debug] User config: ['-o', '/tmpdownload/%(title)s.%(ext)s']
[debug] Command-line args: ['-v', 'http://www.vice.com/my-life-online/my-life-online-the-gregory-brothers']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.07.25.1
[debug] Python version 2.7.3 - Linux-3.12-0.bpo.1-amd64-x86_64-with-debian-7.6
[debug] Proxy map: {}
[generic] my-life-online-the-gregory-brothers: Requesting header
WARNING: Falling back on generic information extractor.
[generic] my-life-online-the-gregory-brothers: Downloading webpage
[generic] my-life-online-the-gregory-brothers: Extracting information
[Ooyala] loeG5nYjpyNWe-nWBJuBqTvMS_1qAiC2: Downloading webpage
[Ooyala] loeG5nYjpyNWe-nWBJuBqTvMS_1qAiC2: Downloading webpage
[debug] Invoking downloader on u'http://player.ooyala.com/player/ipad/loeG5nYjpyNWe-nWBJuBqTvMS_1qAiC2.m3u8?js=1'
[download] Destination: /tmpdownload/My Life Online - Gregory Brothers Interview.mp4
p11-kit: invalid config filename, will be ignored in the future: /etc/pkcs11/modules/gnome-keyring-module
WARNING: gnome-keyring:: couldn't connect to: /home/macarthur/.cache/keyring-ovgH6a/pkcs11: No such file or directory
p11-kit: skipping module 'gnome-keyring-module' whose initialization failed: An error occurred on the device
ffmpeg version 1.0.9 Copyright (c) 2000-2014 the FFmpeg developers
  built on May  2 2014 12:55:13 with gcc 4.7 (Debian 4.7.2-5)
  configuration: --prefix=/usr --extra-cflags='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security ' --extra-ldflags='-Wl,-z,relro' --cc='ccache cc' --enable-shared --enable-libmp3lame --enable-gpl --enable-nonfree --enable-libvorbis --enable-pthreads --enable-libfaac --enable-libxvid --enable-postproc --enable-x11grab --enable-libgsm --enable-libtheora --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libx264 --enable-libspeex --enable-nonfree --disable-stripping --enable-libvpx --enable-libschroedinger --disable-encoder=libschroedinger --enable-version3 --enable-libopenjpeg --enable-librtmp --enable-avfilter --enable-libfreetype --enable-libvo-aacenc --disable-decoder=amrnb --enable-libvo-amrwbenc --enable-libaacplus --libdir=/usr/lib/x86_64-linux-gnu --disable-vda --enable-libbluray --enable-libcdio --enable-gnutls --enable-frei0r --enable-openssl --enable-libass --enable-libopus --enable-fontconfig --enable-libfdk-aac --enable-libdc1394 --disable-altivec --dis  libavutil      51. 73.101 / 51. 73.101
  libavcodec     54. 59.100 / 54. 59.100
  libavformat    54. 29.104 / 54. 29.104
  libavdevice    54.  2.101 / 54.  2.101
  libavfilter     3. 17.100 /  3. 17.100
  libswscale      2.  1.101 /  2.  1.101
  libswresample   0. 15.100 /  0. 15.100
  libpostproc    52.  0.100 / 52.  0.100
[mpegts @ 0x217e420] Estimating duration from bitrate, this may be inaccurate
[aac @ 0x24e3be0] max_analyze_duration 5000000 reached at 5024000
[aac @ 0x24e3be0] Estimating duration from bitrate, this may be inaccurate
[mpegts @ 0x24e4580] Estimating duration from bitrate, this may be inaccurate
[mpegts @ 0x22f82c0] Estimating duration from bitrate, this may be inaccurate
Input #0, hls,applehttp, from 'http://player.ooyala.com/player/ipad/loeG5nYjpyNWe-nWBJuBqTvMS_1qAiC2.m3u8?js=1':
  Duration: 00:06:27.00, start: 0.000000, bitrate: 0 kb/s
    Stream #0:0: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Metadata:
      variant_bitrate : 762000
    Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 44100 Hz, stereo, s16, 125 kb/s
    Metadata:
      variant_bitrate : 762000
    Stream #0:2: Audio: aac, 32000 Hz, stereo, s16, 44 kb/s
    Metadata:
      variant_bitrate : 64000
    Stream #0:3: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 480x270 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Metadata:
      variant_bitrate : 383000
    Stream #0:4: Audio: aac ([15][0][0][0] / 0x000F), 32000 Hz, stereo, s16, 73 kb/s
    Metadata:
      variant_bitrate : 383000
    Stream #0:5: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Metadata:
      variant_bitrate : 1392000
    Stream #0:6: Audio: aac ([15][0][0][0] / 0x000F), 44100 Hz, stereo, s16, 125 kb/s
    Metadata:
      variant_bitrate : 1392000
Output #0, mp4, to '/tmpdownload/My Life Online - Gregory Brothers Interview.mp4.part':
  Metadata:
    encoder         : Lavf54.29.104
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 1392000
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 125 kb/s
    Metadata:
      variant_bitrate : 762000
Stream mapping:
  Stream #0:5 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   26 fps=0.0 q=-1.0 size=     934kB time=00:00:01.04 bitrate=7325.5kbits/frame=  220 fps=205 q=-1.0 size=    1270kB time=00:00:09.13 bitrate=1138.6kbits/frame=  232 fps=145 q=-1.0 size=    1425kB time=00:00:09.63 bitrate=1211.2kbits/No longer receiving variant 1
[hls,applehttp @ 0x2178da0] No longer receiving variant 2
frame=  238 fps= 95 q=-1.0 size=    1568kB time=00:00:09.96 bitrate=1289.8kbits/frame=  238 fps= 77 q=-1.0 size=    1568kB time=00:00:09.98 bitrate=1286.8kbits/frame=  239 fps= 65 q=-1.0 size=    1601kB time=00:00:09.98 bitrate=1313.5kbits/frame=  259 fps= 57 q=-1.0 size=    1738kB time=00:00:10.76 bitrate=1323.1kbits/frame=  279 fps= 55 q=-1.0 size=    1934kB time=00:00:11.59 bitrate=1366.1kbits/frame=  310 fps= 56 q=-1.0 size=    2164kB time=00:00:12.88 bitrate=1375.6kbits/frame=  329 fps= 54 q=-1.0 size=    2321kB time=00:00:13.68 bitrate=1389.9kbits/frame=  358 fps= 54 q=-1.0 size=    2483kB time=00:00:14.99 bitrate=1356.1kbits/frame=  390 fps= 54 q=-1.0 size=    2586kB time=00:00:16.46 bitrate=1286.6kbits/frame=  407 fps= 53 q=-1.0 size=    2709kB time=00:00:16.93 bitrate=1310.5kbits/frame=  444 fps= 54 q=-1.0 size=    2848kB time=00:00:18.47 bitrate=1262.6kbits/frame=  457 fps= 52 q=-1.0 size=    2879kB time=00:00:19.01 bitrate=1239.9kbits/frame=  477 fps= 49 q=-1.0 size=    3109kB time=00:00:19.94 bitrate=1276.9kbits/frame=  478 fps= 47 q=-1.0 size=    3113kB time=00:00:19.94 bitrate=1278.7kbits/frame=  512 fps= 48 q=-1.0 size=    3300kB time=00:00:21.31 bitrate=1268.2kbits/frame=  514 fps= 46 q=-1.0 size=    3300kB time=00:00:21.39 bitrate=1263.4kbits/frame=  517 fps= 44 q=-1.0 size=    3300kB time=00:00:21.52 bitrate=1256.1kbits/frame=  533 fps= 43 q=-1.0 size=    3460kB time=00:00:22.18 bitrate=1277.6kbits/frame=  544 fps= 42 q=-1.0 size=    3549kB time=00:00:22.64 bitrate=1283.8kbits/frame=  558 fps= 42 q=-1.0 size=    3641kB time=00:00:23.23 bitrate=1283.8kbits/frame=  578 fps= 42 q=-1.0 size=    3802kB time=00:00:24.06 bitrate=1294.1kbits/frame=  598 fps= 40 q=-1.0 size=    3873kB time=00:00:24.89 bitrate=1274.1kbits/frame=  618 fps= 40 q=-1.0 size=    4087kB time=00:00:25.73 bitrate=1300.9kbits/frame=  622 fps= 39 q=-1.0 size=    4087kB time=00:00:25.90 bitrate=1292.5kbits/frame=  647 fps= 40 q=-1.0 size=    4300kB time=00:00:26.95 bitrate=1306.8kbits/frame=  666 fps= 39 q=-1.0 size=    4378kB time=00:00:27.73 bitrate=1293.0kbits/frame=  687 fps= 39 q=-1.0 size=    4516kB time=00:00:28.61 bitrate=1292.9kbits/frame=  712 fps= 40 q=-1.0 size=    4697kB time=00:00:29.67 bitrate=1296.7kbits/frame=  716 fps= 39 q=-1.0 size=    4721kB time=00:00:29.90 bitrate=1293.1kbits/frame=  717 fps= 37 q=-1.0 size=    4725kB time=00:00:29.90 bitrate=1294.2kbits/frame=  738 fps= 37 q=-1.0 size=    4837kB time=00:00:30.73 bitrate=1289.0kbits/frame=  760 fps= 37 q=-1.0 size=    5007kB time=00:00:31.65 bitrate=1295.7kbits/frame=  790 fps= 38 q=-1.0 size=    5213kB time=00:00:32.90 bitrate=1297.7kbits/frame=  815 fps= 38 q=-1.0 size=    5370kB time=00:00:33.95 bitrate=1295.6kbits/frame=  838 fps= 38 q=-1.0 size=    5552kB time=00:00:34.90 bitrate=1303.0kbits/frame=  862 fps= 39 q=-1.0 size=    5705kB time=00:00:35.91 bitrate=1301.4kbits/frame=  880 fps= 38 q=-1.0 size=    5839kB time=00:00:36.66 bitrate=1304.7kbits/frame=  904 fps= 39 q=-1.0 size=    6009kB time=00:00:37.66 bitrate=1307.1kbits/frame=  932 fps= 39 q=-1.0 size=    6212kB time=00:00:38.89 bitrate=1308.5kbits/frame=  955 fps= 39 q=-1.0 size=    6364kB time=00:00:39.89 bitrate=1306.9kbits/frame=  956 fps= 38 q=-1.0 size=    6370kB time=00:00:39.89 bitrate=1308.1kbits/frame=  979 fps= 37 q=-1.0 size=    6513kB time=00:00:40.79 bitrate=1307.9kbits/frame= 1008 fps= 38 q=-1.0 size=    6705kB time=00:00:42.00 bitrate=1307.7kbits/frame= 1032 fps= 38 q=-1.0 size=    6874kB time=00:00:43.00 bitrate=1309.4kbits/frame= 1044 fps= 38 q=-1.0 size=    6970kB time=00:00:43.56 bitrate=1310.9kbits/frame= 1058 fps= 37 q=-1.0 size=    7060kB time=00:00:44.08 bitrate=1311.9kbits/frame= 1073 fps= 37 q=-1.0 size=    7153kB time=00:00:44.71 bitrate=1310.5kbits/frame= 1089 fps= 37 q=-1.0 size=    7311kB time=00:00:45.37 bitrate=1319.7kbits/frame= 1101 fps= 37 q=-1.0 size=    7412kB time=00:00:45.87 bitrate=1323.5kbits/frame= 1113 fps= 37 q=-1.0 size=    7484kB time=00:00:46.41 bitrate=1320.9kbits/frame= 1129 fps= 36 q=-1.0 size=    7567kB time=00:00:47.04 bitrate=1317.7kbits/frame= 1145 fps= 36 q=-1.0 size=    7714kB time=00:00:47.76 bitrate=1323.1kbits/frame= 1171 fps= 37 q=-1.0 size=    7819kB time=00:00:48.79 bitrate=1312.6kbits/frame= 1194 fps= 35 q=-1.0 size=    8026kB time=00:00:49.85 bitrate=1318.8kbits/frame= 1195 fps= 35 q=-1.0 size=    8029kB time=00:00:49.85 bitrate=1319.3kbits/frame= 1229 fps= 35 q=-1.0 size=    8274kB time=00:00:51.29 bitrate=1321.4kbits/frame= 1237 fps= 34 q=-1.0 size=    8282kB time=00:00:51.55 bitrate=1316.0kbits/frame= 1254 fps= 34 q=-1.0 size=    8436kB time=00:00:52.31 bitrate=1321.0kbits/frame= 1288 fps= 35 q=-1.0 size=    8611kB time=00:00:53.67 bitrate=1314.1kbits/frame= 1321 fps= 35 q=-1.0 size=    8831kB time=00:00:55.05 bitrate=1314.0kbits/frame= 1350 fps= 36 q=-1.0 size=    9040kB time=00:00:56.26 bitrate=1316.2kbits/frame= 1377 fps= 36 q=-1.0 size=    9178kB time=00:00:57.39 bitrate=1310.1kbits/frame= 1403 fps= 36 q=-1.0 size=    9367kB time=00:00:58.51 bitrate=1311.3kbits/frame= 1423 fps= 36 q=-1.0 size=    9471kB time=00:00:59.30 bitrate=1308.2kbits/frame= 1433 fps= 35 q=-1.0 size=    9582kB time=00:00:59.81 bitrate=1312.3kbits/frame= 1434 fps= 35 q=-1.0 size=    9588kB time=00:00:59.81 bitrate=1313.2kbits/frame= 1462 fps= 35 q=-1.0 size=    9790kB time=00:01:00.93 bitrate=1316.2kbits/frame= 1470 fps= 35 q=-1.0 size=    9843kB time=00:01:01.26 bitrate=1316.0kbits/frame= 1491 fps= 35 q=-1.0 size=   10015kB time=00:01:02.14 bitrate=1320.2kbits/frame= 1512 fps= 35 q=-1.0 size=   10150kB time=00:01:03.06 bitrate=1318.5kbits/frame= 1533 fps= 35 q=-1.0 size=   10277kB time=00:01:03.89 bitrate=1317.5kbits/frame= 1555 fps= 35 q=-1.0 size=   10426kB time=00:01:04.81 bitrate=1317.7kbits/frame= 1590 fps= 35 q=-1.0 size=   10623kB time=00:01:06.27 bitrate=1313.1kbits/frame= 1628 fps= 36 q=-1.0 size=   10896kB time=00:01:07.85 bitrate=1315.4kbits/frame= 1661 fps= 36 q=-1.0 size=   11002kB time=00:01:09.23 bitrate=1301.7kbits/frame= 1672 fps= 36 q=-1.0 size=   11155kB time=00:01:09.79 bitrate=1309.3kbits/frame= 1673 fps= 35 q=-1.0 size=   11162kB time=00:01:09.79 bitrate=1310.1kbits/frame= 1697 fps= 35 q=-1.0 size=   11400kB time=00:01:10.75 bitrate=1320.0kbits/frame= 1721 fps= 35 q=-1.0 size=   11602kB time=00:01:11.73 bitrate=1324.8kbits/frame= 1749 fps= 36 q=-1.0 size=   11763kB time=00:01:12.90 bitrate=1321.7kbits/frame= 1777 fps= 36 q=-1.0 size=   11948kB time=00:01:14.09 bitrate=1321.0kbits/frame= 1799 fps= 36 q=-1.0 size=   12035kB time=00:01:14.99 bitrate=1314.7kbits/frame= 1844 fps= 36 q=-1.0 size=   12315kB time=00:01:16.86 bitrate=1312.4kbits/frame= 1881 fps= 37 q=-1.0 size=   12529kB time=00:01:18.41 bitrate=1309.0kbits/frame= 1911 fps= 37 q=-1.0 size=   12716kB time=00:01:19.76 bitrate=1306.1kbits/frame= 1913 fps= 36 q=-1.0 size=   12723kB time=00:01:19.76 bitrate=1306.7kbits/frame= 1945 fps= 36 q=-1.0 size=   12931kB time=00:01:21.08 bitrate=1306.4kbits/frame= 1954 fps= 36 q=-1.0 size=   12996kB time=00:01:21.45 bitrate=1307.0kbits/frame= 1985 fps= 36 q=-1.0 size=   13229kB time=00:01:22.77 bitrate=1309.1kbits/frame= 2005 fps= 36 q=-1.0 size=   13366kB time=00:01:23.63 bitrate=1309.1kbits/frame= 2030 fps= 37 q=-1.0 size=   13524kB time=00:01:24.62 bitrate=1309.1kbits/frame= 2060 fps= 37 q=-1.0 size=   13723kB time=00:01:25.89 bitrate=1308.9kbits/frame= 2080 fps= 37 q=-1.0 size=   13839kB time=00:01:26.71 bitrate=1307.4kbits/frame= 2110 fps= 37 q=-1.0 size=   14124kB time=00:01:27.96 bitrate=1315.4kbits/frame= 2133 fps= 37 q=-1.0 size=   14301kB time=00:01:28.92 bitrate=1317.4kbits/HTTP error 408 Request Time-out
http://player.ooyala.com/player/ipad/loeG5nYjpyNWe-nWBJuBqTvMS_1qAiC2.m3u8?js=1: Input/output error
frame= 2150 fps= 27 q=-1.0 size=   14464kB time=-577014:-32:-22.-77 bitrate=  -0frame= 2150 fps= 27 q=-1.0 Lsize=   14551kB time=00:01:29.72 bitrate=1328.5kbits/s    
video:13173kB audio:1319kB subtitle:0 global headers:0kB muxing overhead 0.403047%
[avconv] 14899764 bytes

it always ends up with a timeout I don't know why it's having the input output error for but it always happens, I didn't even know there was a ooyla downloader built into youtube-dl till i tried randomly. I just selected a random video to see if it's just one but this is happening with all of the ones that I try to download.

vlc _is_ able to download it by just using the same m3u8 stream all on it's own without any issues so I'm unsure as to why it's having that weird hiccup unless vlc just keeps on trying over and over again.

**Comment by dstftw** [comment]
Downloads fine as f4m.
