### ISSUE TITLE
wrong download for bodybuilding.com

### ISSUE THREAD

**Issue by Siddhant** [rg3/youtube-dl#3411]
$ youtube-dl --verbose "http://www.bodybuilding.com/fun/lee-labrada-12-week-lean-body-trainer-week-2-day-8.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.bodybuilding.com/fun/lee-labrada-12-week-lean-body-trainer-week-2-day-8.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.07.25
[debug] Python version 2.7.6 - Linux-3.13.0-30-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: [REDACTED]
[generic] lee-labrada-12-week-lean-body-trainer-week-2-day-8: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lee-labrada-12-week-lean-body-trainer-week-2-day-8: Downloading webpage
[generic] lee-labrada-12-week-lean-body-trainer-week-2-day-8: Extracting information
[debug] Invoking downloader on u'http://www.bodybuilding.com/fun/lee-labrada-12-week-lean-body-trainer-week-2-day-8.html'
[download] Destination: Bodybuilding.com - Lee Labrada's 12-Week Lean Body Trainer - Week 2, Day 8-lee-labrada-12-week-lean-body-trainer-week-2-day-8.html
[download] 100% of N/A in 00:00

This simply downloads the page in a 150KB html file instead of downloading the video.

**Comment by dstftw** [comment]
Works fine with latest version (2016.05.21.2).
