### ISSUE TITLE
YT returns a generic RTMP URL for long videos [was: youtube-dl unable to download video]

### ISSUE THREAD

**Issue by willysutopo** [rg3/youtube-dl#343]
Hi,

Please help me.
I am using Windows and have downloaded youtube.dl and Python.
From command line, I type : 
youtube-dl.py http://www.youtube.com/watch?v=xOjtMxUW0s0

and here is the output :

[youtube] Setting language
[youtube] xOjtMxUW0s0: Downloading video webpage
[youtube] xOjtMxUW0s0: Downloading video info webpage
[youtube] xOjtMxUW0s0: Extracting video information
[youtube] RTMP download detected
[download] Destination: xOjtMxUW0s0.flv

ERROR: unable to download video

I need to download that particular video.  I have even used the latest version of youtube-dl that is provided here.  And then, I use the latest rtmpdump which is 2.4

Thank you very much.

**Comment by prestonconnors** [comment]
This is still an issue with 2015.01.30.2 . Just wanted to ping the bug report. Thanks!

https://www.youtube.com/watch?v=lTurfn7vvCk

**Comment by spvkgn** [comment]
This issue still happens:
```
~ $ youtube-dl -v 'http://www.youtube.com/watch?feature=player_embedded&v=7tfwQE4qvbI'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?feature=player_embedded&v=7tfwQE4qvbI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.3 - Linux-3.2.0-79-generic-pae-i686-with-LinuxMint-13-maya
[debug] exe versions: ffmpeg 2.4.2, ffprobe 2.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 7tfwQE4qvbI: Downloading webpage
[youtube] 7tfwQE4qvbI: Extracting video information
ERROR: rtmpe downloads are not supported, see https://github.com/rg3/youtube-dl/issues/343 for more information.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1043, in _real_extract
    raise ExtractorError('rtmpe downloads are not supported, see https://github.com/rg3/youtube-dl/issues/343 for more information.', expected=True)
ExtractorError: rtmpe downloads are not supported, see https://github.com/rg3/youtube-dl/issues/343 for more information.
```

**Comment by diffracteD** [comment]
Still an Issue on 26th May 2015... version used: 2015.04.28

**Comment by vortex-ape** [comment]
Can someone suggest any alternatives?

**Comment by Twangist** [comment]
An issue with 2015.11.13 - "ERROR: rtmpe downloads are not supported, see" this page. Is this issue in fact "Closed"? as in, known but it won't be handled? Just asking.

**Comment by ltalirz** [comment]
Still an issue with 2016.01.27
"ERROR: rtmpe downloads are not supported, see https://github.com/rg3/youtube-dl/issues/343 for more information."
Video https://www.youtube.com/watch?v=BI5LCCaMoCo

**Comment by TRox1972** [comment]
Still affecting some videos as of 2016.07.07: https://www.youtube.com/watch?v=lTurfn7vvCk

**Comment by YoonAddicting** [comment]
I don't know if this is any help, but [this](https://www.youtube.com/watch?v=0V-5vxpsFFg) video uses RTMPE and the playback is only available in 360p and 720p on desktop (Mozilla 47), but on mobile devices it is available in everything from 144p to 1080p. 
So YouTube most keep a non-encrypted copy as well, the question is just about how to obtain it.

**Comment by yan12125** [comment]
Hmm https://www.youtube.com/watch?v=0V-5vxpsFFg plays without flash on my Firefox, and other videos mentioned above can't be played on my phone.

**Comment by lilydjwg** [comment]
https://www.youtube.com/watch?v=0V-5vxpsFFg plays without flash on my Firefox too, and all resolutions are available. Also it's downloadable by youtube-dl here.

**Comment by remitamine** [comment]
> I don't know if this is any help, but this video uses RTMPE and the playback is only available in 360p and 720p on desktop (Mozilla 47), but on mobile devices it is available in everything from 144p to 1080p.
So YouTube most keep a non-encrypted copy as well, the question is just about how to obtain it.

i've checked the url when it first posted, it ask's me to activate flash, but it changes today to be available with HTML5.
i checked also using the android app and it's true the videos are available as direct http links(tried some urls posted in this issue).
if we want to use extract them we will need to use the api(https://www.googleapis.com/youtubei/v1/player) but there are some difficulties:
- the api uses protobuf in both POST data and the response(maybe it's possible to change the output to json or xml using query or data passed in the request).
- the api provide more info but most of the keys are just numbers, it's like they convert a `dict` into `array` which make the keys disappear so you need to figure out what's the meaning of every number:
some parts are obvious:
```
  2 {
    1: 18
    2: "https://r5---sn-hgn7zn7k.c.youtube.com/videoplayback?sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cm
ime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=video%2Fmp4&upn=SRD8CwST-po&fexp=11200629%2C94
05988%2C9415293%2C9416164%2C9416891%2C9422596%2C9428398%2C9428595%2C9429003%2C9430993%2C9431012%2C9433096%2C9433380%2C9433584%2C9433704
%2C9433946%2C9434822%2C9434889%2C9435526%2C9435876%2C9436835%2C9437122%2C9437552%2C9438220%2C9438293%2C9438371%2C9438926%2C9439013%2C94
39409%2C9439652%2C9440025%2C9440048%2C9440386%2C9440608%2C9440635%2C9440674&lmt=1281778430483569&dur=1459.002&key=yt6&ip=105.110.33.113
&itag=18&id=o-AB7ND9YMnh26L7AGkStu11zNRO7cXtJfrpbBl7Ra5Ami&mm=30&mn=sn-hgn7zn7k&ipbits=0&signature=CC1431578937082F526FA56557F91BC75C66
C766.6D78443ED7CE09E0BCCFB6DFB07ADF366DA99AEF&requiressl=yes&sver=3&expire=1468353898&mt=1468332065&mv=m&clen=122666319&ms=nxu&source=y
outube&pl=17&ratebypass=yes&initcwndbps=52500&gir=yes&nh=IgpwcjAzLm1yczAyKgkxMjcuMC4wLjE"
    5: "video/mp4; codecs=\"avc1.42001E, mp4a.40.2\""
    6: 672844
    31: 672603
    7: 480
    8: 360
    11: 1281778430483569
    12: 122666319
    16: "medium"
    26: "360p"
    27: 1
  }
```
and some are not:
```
  74642932 {
    1: 1
    2: 1
    3: 1
    4: 0
    5: 0
    6: 0
  }
```
the response is similar to the one returned by google play movies api.

**Comment by ck-on** [comment]
example of rtmpe locked video example that is passed through https so tools like urlsnooper, etc. cannot extract the uri from the stream and inspector will not show anything but http/s protocols

https://www.youtube.com/watch?v=sndXz7oeEgQ

so even if youtube-dl could just dump the real rtmpe url even if it cannot download it, would be helpful

**Comment by mcepl** [comment]
I would really like to see this interview with J K Rowling https://www.youtube.com/watch?v=kn7nlfoMcwQ ;)
(aka "me too")

**Comment by yan12125** [comment]
I just tried all videos listed here. Some of them are gone, and others are re-encoded into un-encrypted HTML5 formats. I guess this issue can be closed?

**Comment by ivan** [comment]
I am told that RTMPE went away on YouTube a few weeks ago.

**Comment by 2017-05-1200-11-20** [comment]
sudo apt install linuxbrew-wrapper
sudo wget https://yt-dl.org/downloads/latest/youtube-dl.sig -O youtube-dl.sig

**Comment by johnstonjay** [comment]
I am having a similar issue but its only present on OS X not on the Linux Distro or windows. im on version youtube-dl 2020.03.24.

Traceback (most recent call last):
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"main", fname, loader, pkg_name)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/usr/local/bin/youtube-dl/main.py", line 19, in 
File "/usr/local/bin/youtube-dl/youtube_dl/init.py", line 474, in main
File "/usr/local/bin/youtube-dl/youtube_dl/init.py", line 464, in _real_main
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 870, in process_ie_result
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 583, in init
if input: self.load(input)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 643, in load
for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'
