### ISSUE TITLE
Ooyala problem

### ISSUE THREAD

**Issue by rubiohiguey** [rg3/youtube-dl#3466]
I am having problems downloading form ooyala
example:
URL: http://www.mundofox.com/videos/el-capo-3-episodio-50-19722

if I run that URL directly it just downlaods the swf file because youtube-dl does not reognize this white-label ooyala player.
I change the player URL from
http://www.mundofox.com/sites/all/libraries/player/player.swf?file=Fib3E1bjoGdZ7QSZ6RlIpmGB_s25y0V4

to 
http://player.ooyala.com/player.swf?file=Fib3E1bjoGdZ7QSZ6RlIpmGB_s25y0V4
youtube-dl output:

[generic] player: Requesting header
[redirect] Following redirect to http://player.ooyala.com/static/cacheable/8f8245c99d0169556eac2f6b99a2e97c/player_v2.swf?file=Fib3E1bjoGdZ7QSZ6RlIpmGB_s25y0V4
[generic] player_v2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player_v2: Downloading webpage
[generic] player_v2: Extracting information
ERROR: Unsupported URL: http://player.ooyala.com/static/cacheable/8f8245c99d0169556eac2f6b99a2e97c/player_v2.swf?file=Fib3E1bjoGdZ7QSZ6RlIpmGB_s25y0V4; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

if I try a different player format (instead of using "file" argument using "embedcode" instead)
I get this error:

[Ooyala] Fib3E1bjoGdZ7QSZ6RlIpmGB_s25y0V4: Downloading webpage
[Ooyala] Fib3E1bjoGdZ7QSZ6RlIpmGB_s25y0V4: Downloading webpage
[download] Destination: El Capo 3 Episodio # 50-Fib3E1bjoGdZ7QSZ6RlIpmGB_s25y0V4.mp4
ffmpeg version 0.7.13-rpmfusion, Copyright (c) 2000-2011 the FFmpeg developers
  built on Jun 13 2012 10:29:59 with gcc 4.6.3 20120306 (Red Hat 4.6.3-2)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib --mandir=/usr/share/man --arch=i686 --extra-cflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables' --extra-version=rpmfusion --enable-bzlib --enable-libcelt --enable-libdc1394 --enable-libdirac --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-librtmp --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --enable-x11grab --enable-avfilter --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib --cpu=i686 --enable-runtime-cpudetect
  libavutil    50. 43. 0 / 50. 43. 0
  libavcodec   52.123. 0 / 52.123. 0
  libavformat  52.111. 0 / 52.111. 0
  libavdevice  52.  5. 0 / 52.  5. 0
  libavfilter   1. 80. 0 /  1. 80. 0
  libswscale    0. 14. 1 /  0. 14. 1
  libpostproc  51.  2. 0 / 51.  2. 0
[applehttp @ 0x9159280] No longer receiving variant 0

ERROR: ffmpeg exited with code -11

I also have tried a different oolaya file referred to in this ticket
https://github.com/rg3/youtube-dl/issues/2292
in this case when I run the URL I get this error:

[generic] life-as-a-truck-stop-stripper-full-length: Requesting header
WARNING: Falling back on generic information extractor.
[generic] life-as-a-truck-stop-stripper-full-length: Downloading webpage
[generic] life-as-a-truck-stop-stripper-full-length: Extracting information
[Ooyala] 5yeW9mazqGRQO-Kig7MadzZ-kh4nbmDM: Downloading webpage
[Ooyala] 5yeW9mazqGRQO-Kig7MadzZ-kh4nbmDM: Downloading webpage
[download] Destination: Vice - Every Woman -Full Length-5yeW9mazqGRQO-Kig7MadzZ-kh4nbmDM.mp4
ffmpeg version 0.7.13-rpmfusion, Copyright (c) 2000-2011 the FFmpeg developers
  built on Jun 13 2012 10:29:59 with gcc 4.6.3 20120306 (Red Hat 4.6.3-2)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib --mandir=/usr/share/man --arch=i686 --extra-cflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables' --extra-version=rpmfusion --enable-bzlib --enable-libcelt --enable-libdc1394 --enable-libdirac --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-librtmp --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --enable-x11grab --enable-avfilter --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib --cpu=i686 --enable-runtime-cpudetect
  libavutil    50. 43. 0 / 50. 43. 0
  libavcodec   52.123. 0 / 52.123. 0
  libavformat  52.111. 0 / 52.111. 0
  libavdevice  52.  5. 0 / 52.  5. 0
  libavfilter   1. 80. 0 /  1. 80. 0
  libswscale    0. 14. 1 /  0. 14. 1
  libpostproc  51.  2. 0 / 51.  2. 0
[applehttp @ 0x9e1c280] max_analyze_duration 5000000 reached at 5013600
[applehttp @ 0x9e1c280] Estimating duration from bitrate, this may be inaccurate

Seems stream 0 codec frame rate differs from container frame rate: 180000.00 (180000/1) -> 90000.00 (180000/2)

Seems stream 3 codec frame rate differs from container frame rate: 180000.00 (180000/1) -> 90000.00 (180000/2)

Seems stream 5 codec frame rate differs from container frame rate: 180000.00 (180000/1) -> 90000.00 (180000/2)
Input #0, applehttp, from 'http://player.ooyala.com/player/ipad/5yeW9mazqGRQO-Kig7MadzZ-kh4nbmDM.m3u8?js=1':
  Duration: 00:27:24.00, bitrate: N/A
    Stream #0.0: Video: h264, 90k tbr, 90k tbn, 180k tbc
    Metadata:
      variant_bitrate : 868000
    Stream #0.1: Audio: aac, 0 channels, s16
    Metadata:
      variant_bitrate : 868000
    Stream #0.2: Audio: aac, 44100 Hz, stereo, s16
    Metadata:
      variant_bitrate : 128000
    Stream #0.3: Video: h264, 90k tbr, 90k tbn, 180k tbc
    Metadata:
      variant_bitrate : 442000
    Stream #0.4: Audio: aac, 0 channels, s16
    Metadata:
      variant_bitrate : 442000
    Stream #0.5: Video: h264, 90k tbr, 90k tbn, 180k tbc
    Metadata:
      variant_bitrate : 1530000
    Stream #0.6: Audio: aac, 0 channels, s16
    Metadata:
      variant_bitrate : 1530000
Unrecognized option 'c'

ERROR: ffmpeg exited with code 1

**Comment by dstftw** [comment]
Works fine with latest version.
