### ISSUE TITLE
mp3 file is not seekable on Android Music app

### ISSUE THREAD

**Issue by amkrankruleuen** [rg3/youtube-dl#3473]
youtube-dl https://www.youtube.com/watch?v=NmSn-_-GePE -x --audio-format mp3 --audio-quality 9

file is not seekable (default use ffmpeg)

All version Android

**Comment by InfiniteStyles** [comment]
Please close this one.

**Comment by yan12125** [comment]
Thanks. Just tried on my phone (Android 6.0) too and it's working. I guess it's some old Android bugs
