### ISSUE TITLE
Can i Use videoplayback URL to play video in a player like some website doing ?

### ISSUE THREAD

**Issue by shahzadakram** [rg3/youtube-dl#3474]
Hello ,

I see some website is playing video from youtube same URL like -g ... but when i use this URL to play video this will not work for my anymore .

Please check this 
Thanks

**Comment by zaasmi** [comment]
check video.com
you need to create a proxy between youtube and Paki traffic.

**Comment by Manchesterz** [comment]
Hello all :)

my script is live which is playing and sharing video from YouTube and it's working even YouTube blocked or not :)

http://ytback.com/

thanks

**Comment by Manchesterz** [comment]
if any anyone want this way to get url then let me know :)

**Comment by Suffixz21** [comment]
Solved this by deleting the member: certificate, that came with the update I presume

**Comment by Vivekmasona** [comment]
> i want to play video like this :
> 
> http://www.ytpak.com/?component=video&task=view&id=_1MDrwqjeGo
> 
> check the page SOurce and URL of video

try this url [https://vivekmasona.000webhostapp.com/play?vfy=https://youtu.be/_VJDi5fw6RQ](https://vivekmasona.000webhostapp.com/play?vfy=https://youtu.be/_VJDi5fw6RQ)
