### ISSUE TITLE
vk.com  does not load

### ISSUE THREAD

**Issue by failuz** [rg3/youtube-dl#3478]
does not load https://vk.com/videos-33919455?section=album_43941159&z=video-33919455_161658117%2Fclub33919455
# [debug] System config: []

[debug] User config: []
[debug] Command-line args: ['--verbose', '--username', '<PRIVATE>', '--password', '<PRIVATE>', 'https://vk.com/videos-33919455?section=album_43941159']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.6.6 - Linux-2.6.32-431.17.1.el6.x86_64-x86_64-with-centos-6.5-Final
[debug] Proxy map: {}
[vk.com] Logging in as 998909991736
[vk.com] s-33919455: Downloading webpage
ERROR: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vk.py", line 159, in _real_extract
    data_json = self._search_regex(r'var vars = ({.*?});', info_page, 'vars')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by mpenkov** [comment]
Works fine with the current master.

```$ bin/youtube-dl http://vk.com/video-59835603_169687332 --verbose --skip-download
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://vk.com/video-59835603_169687332', u'--verbose', u'--skip-download']
[debug] Encodings: locale UTF-8, fs UTF-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Git HEAD: 66d106f27
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[vk] -59835603_169687332: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best```

I think we can close this.
