### ISSUE TITLE
Youtube stream link generation speed

### ISSUE THREAD

**Issue by viperfx** [rg3/youtube-dl#3483]
Is there a way to make the `-g` option any faster to obtain the stream link? I am using it to obtain the WebM DASH format (-f 171) stream link. Currently it takes about 3-4s.

**Comment by alejomendoza** [comment]
Same problem here, is there a guide on how to solve this problem ? or how do the stream links get generated ?

**Comment by yan12125** [comment]
There are a few options:
1. Add ```--youtube-skip-dash-manifest```. Note that youtube-dl may miss some formats with this option.
2. Use lazy extractors (#8497)
3. Write a daemon for youtube-dl
4. Use a VPS in United States. Better if near Silicon Valley
