### ISSUE TITLE
Youtube-dl should spoof ios devices in it's user agent string

### ISSUE THREAD

**Issue by 133794m3r** [rg3/youtube-dl#3518]
As stated, it should spoof ios devices pobably ipad in it's user-agent string so it can get mp4 videos without an issue if it sees that there's nothing out there ala mp4/html5 since sites are more likely to easily serve up mp4 files for an ipad rather than not having them see their ads/content.

**Comment by yan12125** [comment]
Could you give an example URL that the default user agent fails but an iOS user agent works?

**Comment by yan12125** [comment]
Closing as no response for a long time.
