### ISSUE TITLE
Preventing the use of horribly outdated versions?

### ISSUE THREAD

**Issue by anovicecodemonkey** [rg3/youtube-dl#3526]
I see a lot of bug reports against versions of youtube-dl more than a month old, sometimes older. Would it not be desirable to implement a more in-your-face warning about the age of a particular version given that the software is updated frequently? 

I first thought about implementing a simple check that would stop the software working after three weeks to a month. Although I personally don't think versions this old should be used no doubt others may differing views. The second way of addressing of this problem may be presenting the user with a message about the age of the software. 

`The latest version of youtube-dl was released on [date]. This version is more than [x] weeks old. We strongly recommend you update the software. Are you sure you want to continue [y/n]?`

**Comment by yan12125** [comment]
Local version checking can be enabled by ```--call-home```. Also, now we have a big NOTICE in the issue template. This is no longer necessary.
