### ISSUE TITLE
Youtube Bug?? Ts3 Bot

### ISSUE THREAD

**Issue by ZargorHD** [rg3/youtube-dl#3527]
Here is the Error:

WARNING: unable to set language: HTTP Error 429: Too Many Requests ERROR: unable to download video info webpage: HTTP Error 402: Payment Required please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest

**Comment by jaimeMF** [comment]
If you can't watch the video on a browser from the same computer, youtube-dl can't download it. [See this FAQ entry](https://github.com/rg3/youtube-dl/blob/eb6cb9fbe934fe99a35af22065cf91063d416c12/README.md#http-error-429-too-many-requests-or-402-payment-required)
