### ISSUE TITLE
Unable to download Death Battle's streaming videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#3532]
http://www.screwattack.com/shows/originals/death-battle for the list.

Example with the latest http://www.screwattack.com/shows/originals/death-battle/godzilla-vs-gamera-death-battle video:

$ youtube-dl -v http://www.screwattack.com/shows/originals/death-battle/godzilla-vs-gamera-death-battle
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.screwattack.com/shows/originals/death-battle/godzilla-vs-gamera-death-battle']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.10
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.6
[debug] Proxy map: {}
[generic] godzilla-vs-gamera-death-battle: Requesting header
WARNING: Falling back on generic information extractor.
[generic] godzilla-vs-gamera-death-battle: Downloading webpage
[generic] godzilla-vs-gamera-death-battle: Extracting information
ERROR: Unsupported URL: http://www.screwattack.com/shows/originals/death-battle/godzilla-vs-gamera-death-battle; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 457, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 1426, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 96, column 52
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 752, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.screwattack.com/shows/originals/death-battle/godzilla-vs-gamera-death-battle; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Thank you in advance. :)

**Comment by dstftw** [comment]
It now belongs to roosterteeth.com.
