### ISSUE TITLE
Having no success at all with the -o command

### ISSUE THREAD

**Issue by 1235a** [rg3/youtube-dl#3537]
I have tried using -simulate and --get-filename to no success with the youtube-dl.exe for windows 8.1. I have the latest version installed. Any format I try with -o or --output throws a variety of errors with batch files or multiple/single youtube links in the .bat file. I have seen it return just "ext" as the file name along with "error multiple links with the same name" and others. What is the proper verbose for:
-o /%(uploader)s/%(title)s:%(id)s.(ext)s
? I've tried many variations and none work.

**Comment by joshuafarren** [comment]
@phihag That link doesn't work anymore.
For those coming from google (like me) escape percent signs in batch with another percent 
i.e
`%%(title)s`
