### ISSUE TITLE
Extra field: sub-title or episode

### ISSUE THREAD

**Issue by pvdl** [rg3/youtube-dl#3540]
The title is the name of the program, but a sub-title (episode) is also a 'nice to have' fieldname
Can be used e.g. in the filename. big-bang-theory_the-mommy-observation

**Comment by yan12125** [comment]
For the first example, I can't access the video ("De aflevering is niet beschikbaar"). I'm not sure whether it's georestricted or the video is gone. For the second case, the title is "Hero Rescues Girl From Shark" now due to discovery changes. Do you have another example?

**Comment by pvdl** [comment]
@yan12125¸
Yes, the first example is geo restricted (Dutch IP addresses only). Indeed not a good example.
I'll search for a more recent example.

**Comment by GijsTimmers** [comment]
FWIW, you should be able to reach the videos from abroad using an addon called Browsec, which is available for both Firefox and Chrome.

**Comment by dstftw** [comment]
Series related meta fields have been introduced quite some time ago.
