### ISSUE TITLE
Add support for www.kijk.nl

### ISSUE THREAD

**Issue by pvdl** [rg3/youtube-dl#3541]
Via this site you can download tv series from these Dutch commercial TV stations.
NET5 http://www.net5.nl/
SBS6 http://www.sbs6.nl/
Veronica http://www.veronicatv.nl/

Maybe you can decide to make three different extractors.

Basically SBS (www.sbs.nl) is a media company which broadcasts these three mentioned TV-stations

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi
