### ISSUE TITLE
This Blip video throws a 404 error

### ISSUE THREAD

**Issue by Ketsuban** [rg3/youtube-dl#3544]
[thomas@chansey ~]♣ youtube-dl -v "http://blip.tv/foldablehuman/s3e2-1-end-of-eva-follow-up-6558464"
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['-v', 'http://blip.tv/foldablehuman/s3e2-1-end-of-eva-follow-up-6558464']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2014.08.10
    [debug] Python version 3.4.1 - Linux-3.16.1-1-ARCH-x86_64-with-arch
    [debug] Proxy map: {}
    [BlipTV] 6558464: Downloading video RSS
    [BlipTV] 6541774: Resolving URL for Source
    [BlipTV] 6541774: Resolving URL for Blip SD
    [BlipTV] 6541774: Resolving URL for Blip LD
    [BlipTV] 6541774: Resolving URL for Blip HLS
    [debug] Invoking downloader on 'http://j-mirror.video2.blip.tv/Foldablehuman-S3E21EndOfEvaFollowUp254.mp4?ir=406114&sr=18170\n\n'
    ERROR: unable to download video data: HTTP Error 404: Not Found
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1022, in process_info
        success = dl(filename, info_dict)
      File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 998, in dl
        return fd.download(name, info)
      File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/common.py", line 291, in download
        return self.real_download(filename, info_dict)
      File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/http.py", line 58, in real_download
        data = self.ydl.urlopen(request)
      File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1231, in urlopen
        return self._opener.open(req, timeout=self._socket_timeout)
      File "/usr/lib/python3.4/urllib/request.py", line 461, in open
        response = meth(req, response)
      File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python3.4/urllib/request.py", line 499, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found

For comparison, the previous episode, which downloads correctly.

    [thomas@chansey ~]♣ youtube-dl -v "http://blip.tv/foldablehuman/s3e2-end-of-evangelion-and-the-audience-author-membrane-6540094"
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['-v', 'http://blip.tv/foldablehuman/s3e2-end-of-evangelion-and-the-audience-author-membrane-6540094']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2014.08.10
    [debug] Python version 3.4.1 - Linux-3.16.1-1-ARCH-x86_64-with-arch
    [debug] Proxy map: {}
    [BlipTV] 6540094: Downloading video RSS
    [BlipTV] 6523404: Resolving URL for Source
    [BlipTV] 6523404: Resolving URL for Blip LD
    [BlipTV] 6523404: Resolving URL for Blip SD
    [BlipTV] 6523404: Resolving URL for Blip HLS
    [BlipTV] 6523404: Resolving URL for Closed Captioning - Spanish
    [BlipTV] 6523404: Resolving URL for Closed Captioning - Spanish
    [debug] Invoking downloader on 'http://j31.video2.blip.tv/11760011693529/Foldablehuman-S3E2EndOfEvangelionAndTheAudienceAuthorMembrane773.mp4?ir=549197&sr=18176\n\n'

**Comment by dstftw** [comment]
Works with latest version. Closing.
