### ISSUE TITLE
Youtube Download Slows Down after 10 seconds

### ISSUE THREAD

**Issue by phil2508** [rg3/youtube-dl#355]
Tried this on 4 different machines, two Suse, one Ubuntu, one Mac. The same problem on every environment: Download starts with about 800kb/s but slows down to 200kb/s after about 10 seconds and then drifts all the way down to 50-80kb/s. Videos that are 3 minutes or longer take forever to download. Can this be fixed?

**Comment by corwin-of-amber** [comment]
Can someone explain what the -f flag does? I looked at the source of ytdl.js and there is a flag -q but it looks as if -f should not even be valid, but it is! Losing my mind here. Pls help.

**Comment by Hrxn** [comment]
https://github.com/rg3/youtube-dl#format-selection
