### ISSUE TITLE
Youtube download is stuck, never moves past "Setting language"

### ISSUE THREAD

**Issue by madrobby** [rg3/youtube-dl#3550]
```
$ youtube-dl -v http://youtu.be/CmqHVKNZkhM
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://youtu.be/CmqHVKNZkhM']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.10
[debug] Git HEAD: e292890
[debug] Python version 2.7.8 - Darwin-13.3.0-x86_64-i386-64bit
[debug] Proxy map: {}
[youtube] Setting language
```

After the last line it just hangs.There's no CPU usage to speak of. This is a fresh install, I have not used youtube-dl before. I've installed youtube-dl via pip. I'm on OS X 10.9.4 with Python 2.7.8.

**Comment by NeoGeo64** [comment]
I am also getting this error.  I can see the videos in my web browser.  But youtube-dl isn't getting past the setting language thing.

**Comment by dstftw** [comment]
Try forcing IPv4 with `--force-ipv4`.

**Comment by mpenkov** [comment]
Is this still a problem?

I can't reproduce it on my end. The video is accessible via the Web browser and youtube-dl is able to download it.

```
bash-3.2$ youtube-dl --version
2017.10.20
```

**Comment by yan12125** [comment]
I'm not sure if this is still a problem or not, but there are no feedbacks since 2015, so this can be closed.
