### ISSUE TITLE
Audio bitrate never over 128K

### ISSUE THREAD

**Issue by esadovnik** [rg3/youtube-dl#3586]
Hi. I'm a Windows user with ffmpeg installed, and I'd like to use youtube-dl to batch download a bunch of audio files at a bitrate of 160kbps and convert them to mp3's from time to time. I use:

"youtube-dl -x --audio-quality 160K [URL]"

but it only ever downloads a 128kbps file (and this is from YT videos on which I'm almost sure the bitrate is above 128kbps). I've also tried:

"youtube-dl -x --audio-format mp3 --audio-quality 160K [URL]"

and this outputs a 160kbps mp3 file, but it is simply upscaled -- using a spectrum analyzer (specifically, Spek), I see that the bitrate is actually 128kbps. Does anyone know why is this happening, and/or how I get around it?

**Comment by mygazztop** [comment]
Hello. I have the same problem. The difference is that I use Python. When I download audio from YouTube, it is downloaded at 128 kbps, although it is higher on YouTube. This is my code:

```
from __future__ import unicode_literals
import youtube_dl
url = 'https://www.youtube.com/watch?v=C5r3uCKFAls'
ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
    }],
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download([url])

```
Of course I can add a line 'preferredquality': '320', but it will not be a real quality. How can I solve my problem?
