### ISSUE TITLE
WARNING: unable to set language:

### ISSUE THREAD

**Issue by analogged** [rg3/youtube-dl#3588]
I am running into a problem when running this on only 1 of my servers. All my servers are located and use IPs announced to the same Geo area.

Below are my various outputs.

serveuk7@serveuk7.com [~]# youtube-dl --version
2014.08.25.3

serveuk7@serveuk7.com [~]# youtube-dl https://www.youtube.com/watch?v=My2FRPA3Gf8
[youtube] Setting language
[youtube] Confirming age
ERROR: Unable to confirm age: ; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

serveuk7@serveuk7.com [~]# youtube-dl --verbose https://www.youtube.com/watch?v=My2FRPA3Gf8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=My2FRPA3Gf8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.25.3
[debug] Python version 2.6.2 - Linux-2.6.18-371.9.1.el5-x86_64-with-redhat-5.10-Final
[debug] Proxy map: {}
[youtube] Setting language
WARNING: unable to set language:
[youtube] My2FRPA3Gf8: Downloading webpage
[youtube] My2FRPA3Gf8: Downloading video info webpage
ERROR: unable to download video info webpage: ; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 209, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1242, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/python.2.6.2/lib/python2.6/urllib2.py", line 389, in open
    response = meth(req, response)
  File "/usr/local/python.2.6.2/lib/python2.6/urllib2.py", line 502, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/python.2.6.2/lib/python2.6/urllib2.py", line 427, in error
    return self._call_chain(*args)
  File "/usr/local/python.2.6.2/lib/python2.6/urllib2.py", line 361, in _call_chain
    result = func(*args)
  File "/usr/local/python.2.6.2/lib/python2.6/urllib2.py", line 510, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

serveuk7@serveuk7.com [~]# youtube-dl -j https://www.youtube.com/watch?v=My2FRPA3Gf8
WARNING: unable to set language:
ERROR: Unable to download webpage: ; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

serveuk7@serveuk7.com [~]# youtube-dl --verbose -j https://www.youtube.com/watch?v=My2FRPA3Gf8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-j', 'https://www.youtube.com/watch?v=My2FRPA3Gf8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.25.3
[debug] Python version 2.6.2 - Linux-2.6.18-371.9.1.el5-x86_64-with-redhat-5.10-Final
[debug] Proxy map: {}
WARNING: unable to set language:
ERROR: Unable to download webpage: ; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 209, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1242, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/python.2.6.2/lib/python2.6/urllib2.py", line 389, in open
    response = meth(req, response)
  File "/usr/local/python.2.6.2/lib/python2.6/urllib2.py", line 502, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/python.2.6.2/lib/python2.6/urllib2.py", line 427, in error
    return self._call_chain(*args)
  File "/usr/local/python.2.6.2/lib/python2.6/urllib2.py", line 361, in _call_chain
    result = func(*args)
  File "/usr/local/python.2.6.2/lib/python2.6/urllib2.py", line 510, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by jaimeMF** [comment]
[See this FAQ entry](https://github.com/rg3/youtube-dl/blob/eb6cb9fbe934fe99a35af22065cf91063d416c12/README.md#http-error-429-too-many-requests-or-402-payment-required)
