### ISSUE TITLE
[site-support-request] afreeca.com

### ISSUE THREAD

**Issue by ubless607** [rg3/youtube-dl#3611]
<pre>C:\rtmp>youtube-dl --verbose http://www.afreeca.com/player/Player.swf?nTitleNo=12851241&szBjId=mistyj&nBbsNo=12387661&nStationNo=12049126
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.afreeca.com/player/Player.swf?nTitleNo=12851241']
[debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[debug] youtube-dl version 2014.08.29
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] Player: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Player: Downloading webpage
[generic] Player: Extracting information
ERROR: Unsupported URL: http://www.afreeca.com/player/Player.swf?nTitleNo=12851241; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 530, in _real_extract
  File "youtube_dl\utils.pyo", line 1469, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 521, in extract_info
  File "youtube_dl\extractor\common.pyo", line 178, in extract
  File "youtube_dl\extractor\generic.pyo", line 869, in _real_extract
ExtractorError: Unsupported URL: http://www.afreeca.com/player/Player.swf?nTitleNo=12851241; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

'szBjId'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
'nBbsNo'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
'nStationNo'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.</pre>

**Comment by yan12125** [comment]
Thanks @pmrowla (#9395), afreeca will be supported in the next version.
