### ISSUE TITLE
[site-support-request] channel.pandora.tv

### ISSUE THREAD

**Issue by ubless607** [rg3/youtube-dl#3620]
<pre>C:\rtmp>youtube-dl --verbose http://channel.pandora.tv/channel/video.ptv?ch_userid=kinxx100&skey=yellow+submarine&prgid=3534541&ref=search&lot=prglist_2
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://channel.pandora.tv/channel/video.ptv?ch_userid=kinxx100']
[debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[debug] youtube-dl version 2014.08.29
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] video: Requesting header
WARNING: Could not send HEAD request to http://channel.pandora.tv/channel/video.ptv?ch_userid=kinxx100: HTTP Error 500: Internal Server Error
WARNING: Falling back on generic information extractor.
[generic] video: Downloading webpage
[generic] video: Extracting information
[debug] Invoking downloader on u'http://flvr.pandora.tv/flv2pan/flvmovie.dll/userid=kinxx100&prgid=3555646&autoPlay=true'
[download] The Beatles - In My Life - 판도라TV-userid=kinxx100&prgid=3555646&autoPlay=true.unknown_video has already been downloaded
'skey'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
'prgid'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
'ref'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
'lot'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.</pre>

**Comment by dstftw** [comment]
pandora.tv will be supported in the next version.
