### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#3624]
We could add an extractor for twitter.com:
https://twitter.com/neilhimself/status/505002874364243968

**Comment by RingoTheDog** [comment]
Was having a look at the way Twitter posts video, and for the above example "https://twitter.com/neilhimself/status/505002874364243968"   The video link is included in the following DIV:

<div title="http://amp.twimg.com/prod/multibr_v_1/video/2014/08/28/04/5ee2cd45-uploadedvideo-libx264-main-2028k.mp4?e9hx7pVOJJYmo%2FUtTR6ogYAtlR8QcgH%2B8MZM4cKVPc4%3D" class="clDownloadVideo" id="idv_0" style="width:170px">Neil Gaiman on Twitter In which KarenGillan2 accepts my ALS ice bucket challenge (well done) httpstco6MzPjoLwZg.mp4</div>

and the YouTube Generic extractor successfully downloaded:
http://amp.twimg.com/prod/multibr_v_1/video/2014/08/28/04/5ee2cd45-uploadedvideo-libx264-main-2028k.mp4?e9hx7pVOJJYmo%2FUtTR6ogYAtlR8QcgH%2B8MZM4cKVPc4%3D



Here is another example:
URL: https://twitter.com/DJNUEAIRA/status/597797688860680192
DIV: <div title="https://video.twimg.com/ext_tw_video/597580077296066560/pu/vid/640x360/lIJ-E-cY49yhtbfM.mp4" class="clDownloadVideo" id="idv_0" style="width:170px">DJ NUE AIRA on Twitter Bruh this little kid should get paid lol Lebron James with the buzzer beater  httptco8XfPAJJftZ.mp4</div>

YouTube-dl generic extractor can download: https://video.twimg.com/ext_tw_video/597580077296066560/pu/vid/640x360/lIJ-E-cY49yhtbfM.mp4


Hope this helps...keep up the AMAZING work.
Ringo.

**Comment by dstftw** [comment]
Supported since 2015.10.18.
