### ISSUE TITLE
Force IPv4

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#3626]
It seems that youtube-dl uses IPv6 when available. This is good, but I need a way to force IPv4 (for every request, not just the download).

**Comment by phihag** [comment]
Starting from youtube-dl 2015.01.10.1, you can make use of the [`--force-ipv4` option](https://github.com/rg3/youtube-dl/blob/master/README.md#network-options). If you want that to be the default, add it in your [configuration file](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration). See [our FAQ](https://yt-dl.org/update) if you need help updating.
