### ISSUE TITLE
[Request] support for npo.nl subtitles

### ISSUE THREAD

**Issue by corone17** [rg3/youtube-dl#3638]
Is it possible to add support for npo.nl subs? Not all video-streams have subs though, so when applicable.
Example, the 8 o'clock news bulletin: http://www.npo.nl/nos-journaal/28-08-2014/POW_00722860.
The JSON: http://e.omroep.nl/metadata/aflevering/POW_00722860 reports "tt888":"ja", so it has subs.
Its subtitles can then be found here: http://e.omroep.nl/tt888/POW_00722860. I found the url with Firefox's webconsole.

**Comment by dstftw** [comment]
npo subtitles will be supported in the next version. Thanks for the report.

**Comment by corone17** [comment]
dstftw, thanks for the initial support, but since the subtitles are of the webvtt format, which a lot of players don't support, I was wondering if you could convert to subtitle-file to srt first before writing to disk. In this case, with npo-subs, you'd only have to remove the first 2 lines to accomplish that.

If I take yesterday's [8 o' clock newsbulletin](http://www.npo.nl/nos-journaal/07-02-2015/POW_00942206) for example, youtube-dl reports:
```
youtube-dl.exe -s --list-subs http://www.npo.nl/nos-journaal/07-02-2015/POW_00942206
[npo.nl] POW_00942206: Downloading JSON metadata
[npo.nl] POW_00942206: Downloading token
[npo.nl] POW_00942206: Downloading adaptive JSON
[npo.nl] POW_00942206: Downloading adaptive stream JSON
[npo.nl] POW_00942206: Downloading m3u8 information
[npo.nl] POW_00942206: Downloading h264_bb JSON
[npo.nl] POW_00942206: Downloading h264_bb stream JSON
[npo.nl] POW_00942206: Downloading h264_sb JSON
[npo.nl] POW_00942206: Downloading h264_sb stream JSON
[npo.nl] POW_00942206: Downloading h264_std JSON
[npo.nl] POW_00942206: Downloading h264_std stream JSON
WARNING: Automatic Captions not supported by this server
[npo.nl] POW_00942206: Available subtitles for video: nl
[npo.nl] POW_00942206: Available automatic captions for video:
```
Does youtube-dl have the ability to detect the subtitle-format? If so, perhaps you could make the penultimate line look liks this: `[npo.nl] POW_00942206: Available subtitles for video: nl (vtt)`
Whether or not the subtitle-format is detected, `--sub-format srt` didn't do anything.
