### ISSUE TITLE
Vevo 1080p & Other SMIL Streams Not Downloadable

### ISSUE THREAD

**Issue by goldensun87** [rg3/youtube-dl#3656]
Here is an example URL:

http://www.vevo.com/watch/owl-city/beautiful-times/USUV71400914

And, here is what comes out when I use --verbose:

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.vevo.com/watch/owl-city/beautiful-times/USUV71400914', '--ve
rbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.09.01.1
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[Vevo] USUV71400914: Downloading JSON metadata
[Vevo] USUV71400914: Downloading SMIL info
WARNING: Cannot download SMIL information, falling back to JSON ..
[debug] Invoking downloader on 'http://h264-aws.vevo.com/v3/h264/2014/06/USUV71400914/usuv71400914_h
igh_1280x720_h264_2000_aac_128.mp4'
[download] Destination: Beautiful Times-USUV71400914.mp4
```

**Comment by goldensun87** [comment]
@beastbg8: After a certain date, all Vevo videos started being uploaded at the 25 fps framerate.  Anyway, that's why I keep a copy of the 2014.09.24.0 version of youtube-dl in my Desktop folder.

**Comment by phihag** [comment]
@goldensun87 What exactly does 2014.09.24.0 do better than the current version? We can simply add that back to the current version then. Can you give [some context](https://github.com/rg3/youtube-dl/blob/master/README.md#is-there-enough-context-in-your-bug-report)? I am under the impression that the best video format is correctly found by youtube-dl. Isn't that the case?

**Comment by goldensun87** [comment]
@phihag I'm using both that version and the current version.  I kept that old version because, versions after 2014.09.24.0 cannot detect Vevo's old SMIL codes.  More recent vevo videos do not use SMIL anymore of course, but the SMIL streams are still present for the older videos.  The reason I want those old streams is because, the HLS streams contain an extra file with the audio and video, and it looks like this:

Menu
ID                             : 4096 (0x1000)
Menu ID                        : 1 (0x1)
Duration                       : 4mn 12s
List                           : 256 (0x100) (AVC) / 257 (0x101) (AAC)
Service name                   : GBE431400013
Service provider               : FFmpeg
Service type                   : digital television

This extra file is usually 10-12 MB, and it makes the file unable to be processed in video editors like mp4box.  I am able to input the video into mkvmerge, and when I do, this 'Menu' file gets left behind.  After that I am able to repack into MP4 container.

Anyway, if it's possible to add SMIL detection back in, you can do that if you want, but you don't really have to.  As for the "best video format" thing, it's just my personal preference that I use the -F and -f options while downloading, nothing to worry about there xD .

**Comment by phihag** [comment]
It's fine to privately use an old version, but please do report regressions so that we can fix them. (And of course, if something breaks in the old version, you're on your own.

Also bear in mind that (at least in our experience), as soon as you publicly suggest to use an old version you can bet that dozens if not hundred of users who do *not* comment here will stick to the old version and tell their friends to do the same, resulting in bad experiences and additional bug reports. We've seen this for [`-citw`](https://github.com/rg3/youtube-dl/blob/master/README.md#do-i-always-have-to-pass-in---max-quality-format-or--citw), which is completely insane and took years to (hopefully) rot out from most our invocations.

**Comment by phihag** [comment]
youtube-dl 2015.02.02.3 and newer correct SMIL support, so you don't need that old version any more. Please do report any issues that persist.

**Comment by goldensun87** [comment]
@phihag Thank you for the update.  Heh, I had no idea that people here would stick to an old version based on one comment.  I'll remember that.

**Comment by luckbegingood** [comment]
You may follow this step by step guide to download Vevo 1080p/720p videos to MP4, MOV, AVI, MKV, FLV, WMV etc at http://www.allavsoft.com/how-to/download-vevo-videos.html

**Comment by aimkeepachieve** [comment]
You may also try Allavsoft which can download Vevo 1080p & Other SMIL Streams.

Step by step guide at http://www.allavsoft.com/how-to/download-vevo-videos.html

**Comment by ds115** [comment]
Is SMIL broken again? Old videos still work, but I've been getting 404 - Not Found errors for newer videos. 

youtube-dl.exe -F http://www.vevo.com/watch/adele/Hello/GBH481500074 -v

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'http://www.vevo.com/watch/adele/Hello/GBH48
1500074', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-59396-g4156df5, ffprobe N-59396-g4156df5
[debug] Proxy map: {}
[Vevo] Retrieving oauth token
[Vevo] GBH481500074: Downloading JSON metadata
[Vevo] GBH481500074: Downloading HLS formats
[Vevo] GBH481500074: Downloading m3u8 information
[Vevo] GBH481500074: Downloading SMIL file
WARNING: Unable to download SMIL file: HTTP Error 404: Not Found
[info] Available formats for GBH481500074:
format code  extension  resolution note
meta         mp4        multiple   Quality selection URL
Low          mp4        176x144    H264@  56k, AAC@128k
Med          mp4        480x360    H264@ 500k, AAC@128k
High         mp4        1280x720   H264@2000k, AAC@128k
1002         mp4        640x360    1002k , avc1, mp4a
1434         mp4        960x540    1434k , avc1, mp4a
2738         mp4        960x540    2738k , avc1, mp4a
3585         mp4        1280x720   3585k , avc1, mp4a
4661         mp4        1920x1080  4661k , avc1, mp4a
5885         mp4        1920x1080  5885k , avc1, mp4a  (best)

After some quick testing (~20 videos), I've narrowed the start date to June/July (2014). Is anyone else having this issue again?

**Comment by yan12125** [comment]
@ds115 Please open a new issue.

**Comment by nguoiaoden** [comment]
HI all !  I "I ran into a problem.

From this URL :
https://www.vevo.com/watch/vic-chou/make-a-wish/TWA480406903

https://i.imgur.com/qqvYWIN.png

I can't download the video with option 1080p and m3u8. Help me !

**Comment by yan12125** [comment]
@nguoiaode: Please open a new issue and paste _verbose_ logs as texts. No screenshots, please!
