### ISSUE TITLE
[site-support-request] tutsplus.com

### ISSUE THREAD

**Issue by brennebeck** [rg3/youtube-dl#3662]
```bash
[22:14:19] ❯
youtube-dl --verbose -t -A https://code.tutsplus.com/courses/one-two-knockout/lessons/introduction --username=xxx --password=xxx
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-t', '-A', 'https://code.tutsplus.com/courses/one-two-knockout/lessons/introduction', '--username=xxx', '--password=xxx']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.01.1
[debug] Python version 2.7.8 - Darwin-13.4.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] introduction: Requesting header
[redirect] Following redirect to http://code.tutsplus.com/courses/one-two-knockout/lessons/introduction
[generic] introduction: Requesting header
WARNING: Falling back on generic information extractor.
[generic] introduction: Downloading webpage
[generic] introduction: Extracting information
ERROR: Unsupported URL: http://code.tutsplus.com/courses/one-two-knockout/lessons/introduction; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 530, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1472, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/local/opt/pyenv/versions/2.7.8/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/opt/pyenv/versions/2.7.8/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/opt/pyenv/versions/2.7.8/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 3, column 383
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 521, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 178, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 869, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://code.tutsplus.com/courses/one-two-knockout/lessons/introduction; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

As with #3661 -

>I can try working on a pr, but python is definitely not my forte. If you could help by pointing me in the direction of an extractor that would work similar to this (I'm not sure but maybe I should look at the Lynda extractor?) then I'll give it a shot.

So, the same applies here :smile:

**Comment by Ayman97** [comment]
if this was a porn site, i don't think that i will wait all this time

**Comment by remitamine** [comment]
works with the latest version.

**Comment by manniR** [comment]
works only on free ;(

**Comment by yan12125** [comment]
[```--cookies```](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-pass-cookies-to-youtube-dl) should work for non-free videos. If not, please open a new issue.

**Comment by manniR** [comment]
works great - thanks ;)

**Comment by brennebeck** [comment]
@manniR - Are you able to download an entire playlist/course with a single command (e.g. just using the course URL to get all vids) or are you running the command for each video?

**Comment by manniR** [comment]
@brennebeck

- extract tutsplus.com cookie from browser into dl-directory as tutsplus-cookie.txt
- copy playlist links from course-site into playlist-links.txt

youtube-dl --cookies tutsplus-cookie.txt -a playlist-links.txt -o '#%(autonumber)s - %(title)s.%(ext)s'

**Comment by ahmadawais** [comment]
@manniR  All I get by running your command is this error

```bash
youtube-dl --verbose https://code.tutsplus.com/courses/one-two-knockout/lessons/introduction --username=mrahmadawais@gmail.com --password=rajuhaigul -a playlist-links.txt
[debug] System config: [u'--abort-on-error', u'--no-mtime', u'--cookies', u'cookies.txt', u'--console-title', u'--continue', u'--autonumber-size', u'2', u'--retries', u'infinite', u'-o', u'%(chapter_number)s.%(autonumber)s- %(chapter)s\u2014 %(title)s-%(resolution)s.%(ext)s']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://code.tutsplus.com/courses/one-two-knockout/lessons/introduction', u'--username=mrahmadawais@gmail.com', u'--password=rajuhaigul', u'-a', u'playlist-links.txt']
ERROR: batch file could not be read
```
Any help would be appreciated?

**Comment by brennebeck** [comment]
@ahmadawais you'll need to save the list of URLs you want to download in the `playlist-links.txt` file, if you use a queue file. So put `https://code.tutsplus.com/courses/one-two-knockout/lessons/introduction` in the `playlist-links.txt` and any other URLs on a new line each and run the command from the same directory, without the URL flag:
`youtube-dl --verbose --username=mrahmadawais@gmail.com --password=rajuhaigul -a playlist-links.txt`

**Comment by ahmadawais** [comment]
@brennebeck Thanks for that! Is there any way for me to automate the link capture and playlist-links.txt file formation process on Tuts+?

**Comment by brennebeck** [comment]
I have a jquery script I've been using in chrome devtools. The same could be done in Phantom probably so that you get the auto write. I'll post the script when I'm back at my Mac 👍

Sent from my iPhone




On Wed, Aug 3, 2016 at 7:26 PM +0800, "Ahmad Awais" <notifications@github.com> wrote:












@brennebeck Thanks for that! Is there any way for me to automate the link capture and playlist-links.txt file formation process on Tuts+?

**Comment by ahmadawais** [comment]
@brennebeck Great! Looking forward!

**Comment by brennebeck** [comment]
@ahmadawais here ya' go: https://gist.github.com/brennebeck/fa9f45c6bef202c75ced4509e326462f

So I have those two scripts saved as snippets in devtools. Here are the steps:

1. Navigate to the page you want the URLs from (e.g. https://webdesign.tutsplus.com/courses/make-the-leap-from-static-mockups-to-moving-prototypes)
2. Run the `jquerify.js` first
3. Run `get-urls.js` 
4. The `console` will have a list of URLs that you can copy and paste now 👍 

It wouldn't take too much work to get this to work outside of a browser, but this is quick enough for me. Hope it helps.

**Comment by ahmadawais** [comment]
@brennebeck  Thank! Where am I supposed to run these scripts? A gif maybe. I will work it out and convert them to bash.

**Comment by ahmadawais** [comment]
@brennebeck Thanks!
I spent some time and built a bash function for this scrapping.
https://gist.github.com/ahmadawais/065cad34038201d97c257daaddeb2237

Just put it inside your alias file and run ` elinks http://domain.com/ playlist-links.txt`

Cheers!

**Comment by Zainulabadeen** [comment]
Awesome it works ;) Thanks guys

**Comment by a-eid** [comment]
How did you get it to work?

**Comment by ahmadawais** [comment]
> @ahmadawais you'll need to save the list of URLs you want to download in the `playlist-links.txt` file, if you use a queue file. So put `https://code.tutsplus.com/courses/one-two-knockout/lessons/introduction` in the `playlist-links.txt` and any other URLs on a new line each and run the command from the same directory, without the URL flag: `youtube-dl --verbose --username=email@gmail.com --password=pass -a playlist-links.txt`


Hi @brennebeck can you please [delete this comment](https://github.com/ytdl-org/youtube-dl/issues/3662#issuecomment-237078127) as it contains my email (shouldn't be public unsure how I posted it like that) and pass phrase should be deleted anyway even though it was random. Appreciate it.
