### ISSUE TITLE
Twitch HLS? stream audio

### ISSUE THREAD

**Issue by weedy** [rg3/youtube-dl#3693]
As of late I don't always get audio when downloading past broadcasts from twitch. It started in the past month. And I've noticed streamers commenting about encoding settings changing because of twitch HLS changes.

Can anything be done about this? Or do I need to pass other options to MPV?

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.23 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
