### ISSUE TITLE
RTLNow, VoxNOW download fails

### ISSUE THREAD

**Issue by firemylazer** [rg3/youtube-dl#3701]
A week ago the downloads of protected streams worked but i think they have changed a few things here an there and now the download of a protected stream results in thousands of downloaded "Frag" files that are combined at the end of the youtube-dl process. But the file won´t play :-/

youtube-dl http://www.voxnow.de/mein-himmlisches-hotel/gruppe-muenchen-sued-tag-1-gasthof-hotel-zur-post.php\?container_id\=177442\&player\=1\&season\=0
[RTLnow] 177442: Downloading webpage
[RTLnow] 177442: Downloading player data XML
[download] Downloading f4m manifest
[download] Destination: Mein himmlisches Hotel - Gruppe München (Süd) - Tag 1 _ Gasthof 'Hotel zur Post'-177442.flv
[download]   1.5% of 251.13MiB at  1.28MiB/s ETA 02:05^C
ERROR: Interrupted by user

Maybe it´s just a temporary problem or i´m doing something wrong :-D

**Comment by prendinger** [comment]
help need voxnow for 12x WWII special docus! only 3days left ... :(

**Comment by dstftw** [comment]
Closing since voxnow.de is now served by nowtv.de.
