### ISSUE TITLE
Transfert-stall

### ISSUE THREAD

**Issue by MilkTeaD** [rg3/youtube-dl#3741]
Hello,
It seems that there is no timeout.  Using Youtube-dl on ARMhf (Odroid U3) Xubuntu. On my broadband-link, the trnasfert stalls. 
It speeds up from 2 -> 3 MiB/s and then I have to interrupt it.  I suppose you use wget.  All my wget I us with the options -T 5 -t 0 (continuous retry, with a general timeout of 5 secs).  Setting my eth0 speed down to 1 MiB or changing mtu to 500 did not help.
I have to interrupt with <ctrl>-c and luckily it resumes.
M.

**Comment by sehrgut** [comment]
I'd be interested to see if there were a way we could spin off a watchdog process to detect stalled transfers heuristically and trigger retry.

**Comment by MilkTeaD** [comment]
that is what I do
<getit.sh>#!/bin/bashwhile truedo/home/mark/youtube-dl $1 -f bestif [ $? -eq 0 ]then        breakfidone<EOF>
and run it in "screen" 

      Van: sehrgut <notifications@github.com>
 Aan: rg3/youtube-dl <youtube-dl@noreply.github.com> 
Cc: MilkTeaD <milktea.original@yahoo.com>
 Verzonden: zondag 10 januari 4:01 2016
 Onderwerp: Re: [youtube-dl] Transfert-stall (#3741)
   
I'd be interested to see if there were a way we could spin off a watchdog process to detect stalled transfers heuristically and trigger retry.—

**Comment by sehrgut** [comment]
Thanks! I'll have to try that out. I may see if I can implement a
stall-killer within the pycode too, since it would be an interesting
project.

**Comment by dstftw** [comment]
If wget has the same behavior then it's obviously network issues on your side.
