### ISSUE TITLE
--sub-lang doesn't seem to work

### ISSUE THREAD

**Issue by foresto** [rg3/youtube-dl#3804]
When I use the `--sub-lang en` option, youtube-dl says it is downloading subtitles, but no subtitle file is created. When I combine that option with `--write-sub`, all the subtitle files are downloaded, not just the language I selected.

I'm testing with this page:
http://www.crunchyroll.com/yamishibai-japanese-ghost-stories/episode-2-zanbai-641889

This is on version 2014.08.05.

**Comment by jaimeMF** [comment]
Thanks for the report, in the next version only the requested language file will be written.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl version 2015.02.24 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
