### ISSUE TITLE
Add Support for www.animecenter.tv

### ISSUE THREAD

**Issue by roflsunriz** [rg3/youtube-dl#3808]
youtube-dl.exe -f best -v http://www.animecenter.tv/watch/puchimas!:-petit-idolmster-epis
ode-04
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', 'best', '-v', 'http://www.animecenter.tv/watch/puchimas!:-petit-idolmster-episode-04']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2014.09.19
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] puchimas!:-petit-idolmster-episode-04: Requesting header
WARNING: Falling back on generic information extractor.
[generic] puchimas!:-petit-idolmster-episode-04: Downloading webpage
[generic] puchimas!:-petit-idolmster-episode-04: Extracting information
ERROR: Unsupported URL: http://www.animecenter.tv/watch/puchimas!:-petit-idolmster-episode-04; please report this issue on https://yt-dl.o
rg/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; t
ype  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 545, in _real_extract
  File "youtube_dl\utils.pyo", line 1509, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 214, column 179
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 524, in extract_info
  File "youtube_dl\extractor\common.pyo", line 180, in extract
  File "youtube_dl\extractor\generic.pyo", line 890, in _real_extract
ExtractorError: Unsupported URL: http://www.animecenter.tv/watch/puchimas!:-petit-idolmster-episode-04; please report this issue on https:
//yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest v
ersion; type  youtube-dl -U  to update.

Thank you for made a great tool,
roflsunriz

**Comment by jaimeMF** [comment]
They probably don't have the right for distributing that content, therefore we can't add support for the site. If you think they can, please comment here and we will reopen the issue.
