### ISSUE TITLE
[Grooveshark] Add playlist support

### ISSUE THREAD

**Issue by CkuT** [rg3/youtube-dl#3810]
Hi,

Is it possible to add playlist support for Grooveshark ? 

One example of typical link we can found :
http://grooveshark.com/#!/playlist/Deb+4/87819659

**Comment by fleuryc** [comment]
:+1:

**Comment by yan12125** [comment]
Unfortunately Grooveshark was shut down yesterday. See the post at http://grooveshark.com/. Closing.
