### ISSUE TITLE
SBS Unable to download 403 Forbidden

### ISSUE THREAD

**Issue by johnkernke** [rg3/youtube-dl#3811]
Following the update in #3176 I tried to download from SBS again, but still got the 403 Forbidden error.

```
$ youtube_dl --verbose "http://www.sbs.com.au/ondemand/video/single/11840579591/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.sbs.com.au/ondemand/video/single/11840579591/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.19
[debug] Git HEAD: d0df929
[debug] Python version 2.7.6 - Darwin-14.0.0-x86_64-i386-64bit
[debug] Proxy map: {}
[SBS] 11840579591: Downloading webpage
[ThePlatform] RVmlCdUsLKMZ: Downloading XML
[ThePlatform] RVmlCdUsLKMZ: Downloading webpage
[debug] Invoking downloader on 'http://sbsauvod-f.akamaihd.net/SBS_Production/managed/2012/07/2258104629_1500K.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 1037, in process_info
    success = dl(filename, info_dict)
  File "youtube_dl/YoutubeDL.py", line 1013, in dl
    return fd.download(name, info)
  File "youtube_dl/downloader/common.py", line 291, in download
    return self.real_download(filename, info_dict)
  File "youtube_dl/downloader/http.py", line 66, in real_download
    data = self.ydl.urlopen(request)
  File "youtube_dl/YoutubeDL.py", line 1265, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

Also, it would be nice if youtube-dl could detect downloading from the SBS page URL `http://www.sbs.com.au/ondemand/video/11840579591/Rockwiz-McClymont-Sisters-and-John-Williamson` instead of having to change the URL to `http://www.sbs.com.au/ondemand/video/single/11840579591/`. Looks like SBS might have changed the way it puts the video player on the page and doesn't have that link anymore.

If you need an Australian server to test SBS from, let me know and I can help you out.

**Comment by RadAd** [comment]
I think I'm seeing the same issue in youtube-dl version 2015.03.09:

> youtube-dl -v http://www.sbs.com.au/ondemand/video/53466691641/Hestons-Fantastical-Food-Fantastical-Christmas
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.sbs.com.au/ondemand/video/
53466691641/Hestons-Fantastical-Food-Fantastical-Christmas']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.09
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-70606-g2e5605f, ffprobe N-70606-g2e5605f, rtmpdum
p 2.4
[SBS] 53466691641: Downloading webpage
[ThePlatform] jtpzId_hkbsp: Downloading XML
[ThePlatform] jtpzId_hkbsp: Downloading webpage
[debug] Invoking downloader on 'http://sbsauvod-f.akamaihd.net/SBS_Production/ma
naged/2015/03/09/2015-03-09_476297_1500K.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1381, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1356, in dl
  File "youtube_dl\downloader\common.pyo", line 341, in download
  File "youtube_dl\downloader\http.pyo", line 64, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1675, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden

**Comment by RadAd** [comment]
When looking at the actual url downloaded in the webpage it looks like this: http://sbsvodns-vh.akamaihd.net/z/vod/SBS_Production/managed/2015/03/09/2015-03-09_476297_,1500,1000,512,128,K.mp4.csmil/0_5694a0b3320ce75e_Seg1-Frag5?hdntl=exp=1426302075~acl=%2f*~data=hdntl~hmac=a50159fbbe908e1e18d8020171d9b7a08d2dd2653b865dc65316d3373f72179b&als=10.26,300,3.48,3,1423,3742,25.64,2,0,75,f,13.7,2769.03,f,s,LSNSTQVESOFN,3.5.0,75&hdcore=3.5.0


Seems the url has changed.

**Comment by RadAd** [comment]
Having a look at the sbs extractor it looks for playerParams.releaseUrls which in my case was http://link.theplatform.com/s/Bgtm9B/jtpzId_hkbsp?feed=Video%20-%20Single&manifest=f4m&mbr=true&ord=1836540&policy=11929623&dfptag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.food.sbs.com.au%2Fsec30%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast3%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dpreroll%26ad_rule%3D1%26cmsid%3D531%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252F53466691641%252FHestons-Fantastical-Food-Fantastical-Christmas%26description_url%3DSBS%26correlator%3D1426218012%26vid%3D53466691641

Downloading this file gave me:
`<smil xmlns="http://www.w3.org/2005/SMIL21/Language">
<head>
</head>
<body>
<seq>
<par>
	<video src="http://sbsauvod-f.akamaihd.net/SBS_Production/managed/2015/03/09/2015-03-09_476297_1500K.mp4" title="Heston&apos;s Fantastical Food S1 Ep7 - Fantastical Christmas" abstract="Fantastical Christmas - In tonight&apos;s final episode, Heston Blumenthal tackles the challenge of making the ultimate Christmas dinner. In the grownup world, Christmas has lost some of its wonder. But Heston wants to change that and plans to create a supersized festive food adventure, to be enjoyed by people who normally have to work on Christmas Day. Heston visits Hampton Court, and discovers that instead of turkey, our ancestors preferred to eat pig&apos;s head, which he puts on the menu alongside edible decorations. Then for dessert, Heston makes the biggest Christmas pudding ever - one that&apos;s large enough to step inside. (From the UK) (Food Series) PG CC
 " copyright="SBS" dur="2769000ms" guid="476297" categories="Section::Section/Programs,Channel::Channel/SBS1,Genre::Food,Food/Food" ratings="urn%3Awww.acma.gov.au%3Atv:pg" type="video/mp4" clipBegin="0:00" clipEnd="6:13.625">
	</video>
	<textstream src="http://videocdn.sbs.com.au/u/video/SBS/managed/closedcaptions/2015/03/09/476297.DFXP" type="application/ttaf+xml"/>
	<textstream src="http://videocdn.sbs.com.au/u/video/SBS/managed/closedcaptions/2015/03/09/476297.SRT" type="text/srt"/>
</par>
<par>
	<video src="http://sbsauvod-f.akamaihd.net/SBS_Production/managed/2015/03/09/2015-03-09_476297_1500K.mp4" title="Heston&apos;s Fantastical Food S1 Ep7 - Fantastical Christmas" abstract="Fantastical Christmas - In tonight&apos;s final episode, Heston Blumenthal tackles the challenge of making the ultimate Christmas dinner. In the grownup world, Christmas has lost some of its wonder. But Heston wants to change that and plans to create a supersized festive food adventure, to be enjoyed by people who normally have to work on Christmas Day. Heston visits Hampton Court, and discovers that instead of turkey, our ancestors preferred to eat pig&apos;s head, which he puts on the menu alongside edible decorations. Then for dessert, Heston makes the biggest Christmas pudding ever - one that&apos;s large enough to step inside. (From the UK) (Food Series) PG CC
 " copyright="SBS" dur="2769000ms" guid="476297" categories="Section::Section/Programs,Channel::Channel/SBS1,Genre::Food,Food/Food" ratings="urn%3Awww.acma.gov.au%3Atv:pg" type="video/mp4" clipBegin="6:13.625" clipEnd="22:55.542">
	</video>
	<textstream src="http://videocdn.sbs.com.au/u/video/SBS/managed/closedcaptions/2015/03/09/476297.DFXP" type="application/ttaf+xml"/>
	<textstream src="http://videocdn.sbs.com.au/u/video/SBS/managed/closedcaptions/2015/03/09/476297.SRT" type="text/srt"/>
</par>
<par>
	<video src="http://sbsauvod-f.akamaihd.net/SBS_Production/managed/2015/03/09/2015-03-09_476297_1500K.mp4" title="Heston&apos;s Fantastical Food S1 Ep7 - Fantastical Christmas" abstract="Fantastical Christmas - In tonight&apos;s final episode, Heston Blumenthal tackles the challenge of making the ultimate Christmas dinner. In the grownup world, Christmas has lost some of its wonder. But Heston wants to change that and plans to create a supersized festive food adventure, to be enjoyed by people who normally have to work on Christmas Day. Heston visits Hampton Court, and discovers that instead of turkey, our ancestors preferred to eat pig&apos;s head, which he puts on the menu alongside edible decorations. Then for dessert, Heston makes the biggest Christmas pudding ever - one that&apos;s large enough to step inside. (From the UK) (Food Series) PG CC
 " copyright="SBS" dur="2769000ms" guid="476297" categories="Section::Section/Programs,Channel::Channel/SBS1,Genre::Food,Food/Food" ratings="urn%3Awww.acma.gov.au%3Atv:pg" type="video/mp4" clipBegin="22:55.542" clipEnd="36:06.917">
	</video>
	<textstream src="http://videocdn.sbs.com.au/u/video/SBS/managed/closedcaptions/2015/03/09/476297.DFXP" type="application/ttaf+xml"/>
	<textstream src="http://videocdn.sbs.com.au/u/video/SBS/managed/closedcaptions/2015/03/09/476297.SRT" type="text/srt"/>
</par>
<par>
	<video src="http://sbsauvod-f.akamaihd.net/SBS_Production/managed/2015/03/09/2015-03-09_476297_1500K.mp4" title="Heston&apos;s Fantastical Food S1 Ep7 - Fantastical Christmas" abstract="Fantastical Christmas - In tonight&apos;s final episode, Heston Blumenthal tackles the challenge of making the ultimate Christmas dinner. In the grownup world, Christmas has lost some of its wonder. But Heston wants to change that and plans to create a supersized festive food adventure, to be enjoyed by people who normally have to work on Christmas Day. Heston visits Hampton Court, and discovers that instead of turkey, our ancestors preferred to eat pig&apos;s head, which he puts on the menu alongside edible decorations. Then for dessert, Heston makes the biggest Christmas pudding ever - one that&apos;s large enough to step inside. (From the UK) (Food Series) PG CC
 " copyright="SBS" dur="2769000ms" guid="476297" categories="Section::Section/Programs,Channel::Channel/SBS1,Genre::Food,Food/Food" ratings="urn%3Awww.acma.gov.au%3Atv:pg" type="video/mp4" clipBegin="36:06.917">
	</video>
	<textstream src="http://videocdn.sbs.com.au/u/video/SBS/managed/closedcaptions/2015/03/09/476297.DFXP" type="application/ttaf+xml"/>
	<textstream src="http://videocdn.sbs.com.au/u/video/SBS/managed/closedcaptions/2015/03/09/476297.SRT" type="text/srt"/>
</par>
</seq>
</body>
</smil>`

Which seems to be youtube-dl is getting the url: http://sbsauvod-f.akamaihd.net/SBS_Production/managed/2015/03/09/2015-03-09_476297_1500K.mp4

Any ideas why this isn't working?

**Comment by wwark** [comment]
Hello,
I have the same issue. Any Ideas ?

Thanks for you return,
Regards,
Wark

**Comment by wwark** [comment]
Hello,

I tried some video and i found some with HTTP 403 and some OK. When we had HTTP 403 we didn't download "Downloading f4m manifest". The two video working on my browser. 

./youtube-dl http://www.sbs.com.au/ondemand/video/254180931901/Secret-Sunshine -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.sbs.com.au/ondemand/video/254180931901/Secret-Sunshine', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 3.4.3 - Linux-4.0.4-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[SBS] 254180931901: Downloading webpage
[ThePlatform] 8IdqOx1sBiuR: Downloading XML
[ThePlatform] 8IdqOx1sBiuR: Downloading webpage
[debug] Invoking downloader on 'http://sbsauvod-f.akamaihd.net/SBS_Production/managed/2015/05/18/2015-05-18_239536_1500K.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1419, in process_info
    success = dl(filename, info_dict)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1361, in dl
    return fd.download(name, info)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "./youtube-dl/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1712, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

./youtube-dl http://www.sbs.com.au/ondemand/video/439389251722/Vikings-S3-Ep10-The-Dead?cid=od:v2:15 -v                                                                                                                                                                                                     
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.sbs.com.au/ondemand/video/439389251722/Vikings-S3-Ep10-The-Dead?cid=od:v2:15', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 3.4.3 - Linux-4.0.4-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[SBS] 439389251722: Downloading webpage
[ThePlatform] 1fj2kUCLAh28: Downloading XML
[ThePlatform] 1fj2kUCLAh28: Downloading webpage
[ThePlatform] 1fj2kUCLAh28: Downloading f4m manifest
[debug] Invoking downloader on 'http://sbsvodns-vh.akamaihd.net/z/svod/SBS/managed/2015/05/13/2015-05-13_517541_1500K.mp4/manifest.f4m?hdnea=st=1432371960~exp=1432373790~acl=/*~hmac=c1c4de9823d730facfb12add643cf1eb2e05d059ebb97c87e97cfa8a84c32fe8&g=UXWGVKRWHFSP&hdcore=3.0.3'
[download] Downloading f4m manifest
[download] Destination: Vikings S3 Ep10 - The Dead-439389251722.flv

Best regards,
Wark,

**Comment by seamusphelan** [comment]
Just a note on what I've noticed so far.

The playerParams (in the sbs website) has two different urls in it - one for f4m manifest and another for m3u manifest.  
If I download the f4m (via CLI/wget) and then manually try to download the video I will get an 403.  
If I download the m3u manifest using wget and then download the video in the m3u manifest, it downloads successfully.

theplatform extractor (which is called after the sbs extractor) always downloads using a f4m manifest (XML based).  I tried forcing it to download the m3u manifest (using force_smil_url), but that was fruitless, as all the code that parses the result is expecting xml (which m3u isn't)

The 403 from the f4m manifest is still very puzzling.

cheers,
Seamus.

**Comment by wwark** [comment]
Hello,
How can i get the two different urls ?

Best regards,
Marc Roy

**Comment by wwark** [comment]
I found them but i tried the two m3u and f4m for this url http://www.sbs.com.au/ondemand/video/473107011820/the-hunt and there is the same information download and i get 403.

Could you please try if it is working for you ?

Best regards,
Marc Roy.

**Comment by remitamine** [comment]
it woks in Australia without a problem for both f4m and m3u8 manifests:
f4m downloading:
```
youtube-dl --verbose "http://www.sbs.com.au/ondemand/video/single/11840579591/"
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c', '--external-downloader-args', '-x 16 --check-certificate=false', '-f', 'best[height<=?720]', '--sub-lang', 'ar,en', '--write-sub']
[debug] Command-line args: ['--verbose', 'http://www.sbs.com.au/ondemand/video/single/11840579591/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 3.4.3 - Linux-4.1.2-2-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[SBS] 11840579591: Downloading webpage
[ThePlatform] RVmlCdUsLKMZ: Downloading XML
[ThePlatform] RVmlCdUsLKMZ: Downloading webpage
[ThePlatform] RVmlCdUsLKMZ: Downloading f4m manifest
WARNING: ar subtitles not available for 11840579591
[info] Writing video subtitles to: Rockwiz S10 Ep131 - McClymont Sisters & John Williamson-11840579591.en.ttml
[debug] Invoking downloader on 'http://sbsvodns-vh.akamaihd.net/z/vod/SBS_Production/managed/2012/07/2258104629_,1500,1000,512,128,64,K.mp4.csmil/manifest.f4m?hdnea=st=1437728630~exp=1437746660~acl=/*~hmac=c3a68a5ee31252a8454c6f44b294bf457cac06c3ea859d700547e7d37af52f43&g=UXWGVKRWHFSP&hdcore=3.0.3'
[download] Downloading f4m manifest
[download] Destination: Rockwiz S10 Ep131 - McClymont Sisters & John Williamson-11840579591.flv
[download]   0.0% of ~475.32MiB at 14.37KiB/s ETA 10:42:13
```
m3u8 downloading:
```
youtube-dl --verbose "http://www.sbs.com.au/ondemand/video/single/11840579591/"
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c', '--external-downloader-args', '-x 16 --check-certificate=false', '-f', 'best[height<=?720]', '--sub-lang', 'ar,en', '--write-sub']
[debug] Command-line args: ['--verbose', 'http://www.sbs.com.au/ondemand/video/single/11840579591/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 3.4.3 - Linux-4.1.2-2-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[SBS] 11840579591: Downloading webpage
[ThePlatform] RVmlCdUsLKMZ: Downloading XML
[ThePlatform] RVmlCdUsLKMZ: Downloading webpage
[ThePlatform] RVmlCdUsLKMZ: Downloading m3u8 information
WARNING: ar subtitles not available for 11840579591
[info] Writing video subtitles to: Rockwiz S10 Ep131 - McClymont Sisters & John Williamson-11840579591.en.ttml
[debug] Invoking downloader on 'http://sbsvodns-vh.akamaihd.net/i/vod/SBS_Production/managed/2012/07/2258104629_,1500,1000,512,128,64,K.mp4.csmil/index_0_av.m3u8?null='
[download] Destination: Rockwiz S10 Ep131 - McClymont Sisters & John Williamson-11840579591.m3u8
ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 5.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gnutls --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-shared --enable-version3 --enable-x11grab
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, hls,applehttp, from 'http://sbsvodns-vh.akamaihd.net/i/vod/SBS_Production/managed/2012/07/2258104629_,1500,1000,512,128,64,K.mp4.csmil/index_0_av.m3u8?null=':
  Duration: 00:43:03.03, start: 0.100500, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv), 640x360 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 127 kb/s
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
[mp4 @ 0x55d4554021c0] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x55d4554021c0] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to 'Rockwiz S10 Ep131 - McClymont Sisters & John Williamson-11840579591.m3u8.part':
  Metadata:
    encoder         : Lavf56.36.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 640x360 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 127 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   33 fps=0.0 q=-1.0 size=     193kB time=00:00:01.34 bitrate=1175.2kbits
```

**Comment by seamusphelan** [comment]
Hi @remitamine. I am also in Australia - my provider is Internode. I have tried to download the same program and it fails. I've noticed the link that it tries to download is different ( http://sbsauvod-f.akamaihd.net/SBS_Production/managed/2012/07/2258104629_1500K.mp4).  I tried to download the link in your f4m output and I got a 403 (but that may be because the link has an expiry date in it) . I have also tried using the external downloader aria2c like in your example but that also failed.

```
youtube-dl --verbose "http://www.sbs.com.au/ondemand/video/single/11840579591/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.sbs.com.au/ondemand/video/single/11840579591/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.9 - Linux-3.19.0-15-generic-i686-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 2.5.6-0ubuntu0.15.04.1, ffprobe 2.5.6-0ubuntu0.15.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[SBS] 11840579591: Downloading webpage
[ThePlatform] RVmlCdUsLKMZ: Downloading XML
[ThePlatform] RVmlCdUsLKMZ: Downloading webpage
[debug] Invoking downloader on 'http://sbsauvod-f.akamaihd.net/SBS_Production/managed/2012/07/2258104629_1500K.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/sp/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1435, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/sp/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1377, in dl
    return fd.download(name, info)
  File "/usr/local/sp/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/sp/bin/youtube-dl/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/sp/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1731, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by remitamine** [comment]
in my case youtube-dl get f4m and m3u8(using a custom version) links but in you're case you get a direct link.
it's not the same

**Comment by impetusdirection** [comment]
I also encounter this issue, after I failed to download from SBS, I google search and test so many so called SBS Downloader. 
Luckily, I do find a workable one called Allavsoft from http://www.allavsoft.com/how-to/sbs-on-demand-download.html
According to my test, it works great in download videos from SBS on demand and also from Tenplay, ABC iView, 9now, Plus 7, Yahoo etc.
Hope it also helps for you.
