### ISSUE TITLE
Request to download all playlists of a channel/user account

### ISSUE THREAD

**Issue by orschiro** [rg3/youtube-dl#3817]
Hi together, 

As a follow up on this [1] discussion I want to propose a new feature which allows the user to download all playlists of a provided channel/user account.

Unfortunately I cannot provide you with a pull request, but I am happy to think with you about the design of the implementation. :)

Looking forward to any comments. :+1: 

[1] https://github.com/rg3/youtube-dl/issues/3659

**Comment by dstftw** [comment]
This feature will be supported in the next version.

**Comment by orschiro** [comment]
Dear @dstftw,

This is fantastic news. Thank you very much for sharing this. :)

~ Robert
