### ISSUE TITLE
Vevo - New 1080p Videos Not Fully Downloading

### ISSUE THREAD

**Issue by goldensun87** [rg3/youtube-dl#3827]
Latest version of youtube-dl stops after downloading the first segment.

C:\Users\Naved\Desktop>youtube-dl -fm3u8-5921 http://www.vevo.com/watch/colbie-caillat/try/USUV71401303
[Vevo] Retrieving oauth token
[Vevo] USUV71401303: Downloading JSON metadata
[Vevo] USUV71401303: Downloading HLS formats
[Vevo] USUV71401303: Downloading webpage
[download] Destination: Try-USUV71401303.mp4
[hlsnative] USUV71401303: Downloading m3u8 manifest
[hlsnative] USUV71401303: Downloading segment 1 / 24

C:\Users\Naved\Desktop>

This is on my laptop.  On my desktop, I haven't updated to latest version yet, so I will try before updating, once I get home.

**Comment by yan12125** [comment]
This bug should have been fixed in fec02bcc90ad26ac5bbd11173fa83db91b3858bb. Feel free to open new issues if there are other problems.
