### ISSUE TITLE
Download from ComedyCentral fails

### ISSUE THREAD

**Issue by L3viathan** [rg3/youtube-dl#3832]
While trying to download a South Park episode this happens:

    [ComedyCentral] south-park-go-fund-yourself-season-18-ep-1801: Downloading webpage
    [ComedyCentral] 69d1eaa2-b9d1-4723-9b76-85f632fa58c4: Downloading info
    [ComedyCentral] 8a923fb7-b803-42e0-9a69-d2565c97ff01: Extracting information
    [ComedyCentral] 8a923fb7-b803-42e0-9a69-d2565c97ff01: Downloading video urls
    [ComedyCentral] a1aa30db-2217-44d7-9b83-0073adbe9699: Extracting information
    [ComedyCentral] a1aa30db-2217-44d7-9b83-0073adbe9699: Downloading video urls
    [ComedyCentral] c758eb1d-d249-46c1-8265-a99c8309c7b8: Extracting information
    [ComedyCentral] c758eb1d-d249-46c1-8265-a99c8309c7b8: Downloading video urls
    ERROR: unable to download video data: HTTP Error 400: Bad Request

This happens with the newest version (`2014.09.25`), and does so consistently.

**Comment by jaimeMF** [comment]
This has been fixed (see https://github.com/rg3/youtube-dl/issues/3364#issuecomment-63775125). Thanks for the report!
