### ISSUE TITLE
Is youtube-dl able to make use of multiple cores ?

### ISSUE THREAD

**Issue by TheGr33k** [rg3/youtube-dl#3852]
It would have been awesome if youtube-dl can generate direct url while making  use of multiple cores .I believe this can really speed things up .

On a side note youtube-dl uses a lot of cpu on my cpu (20-25% per process) and i use a Dual Xeon E5-2620.I would love some optimization on that front to make the cpu usage lower

I am using python 2.7 atm :)

**Comment by STonEDSTonE** [comment]
This is a very old post, but i did not find a newer one regarding this topic.
Since 4 years have passed, is there a posibility to use multiple cores now? Or will there be one in the future? Or is this sth. that will never happen?
