### ISSUE TITLE
add support to download video from la7 channel

### ISSUE THREAD

**Issue by svidoli** [rg3/youtube-dl#3862]
$  youtube-dl --verbose "http://www.la7.it/dimartedi/rivedila7/dimarted%C3%AC-01-10-2014-137515"

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.la7.it/dimartedi/rivedila7/dimarted%C3%AC-01-10-2014-137515']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.25
[debug] Python version 3.4.1 - Linux-3.16.3-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[generic] dimarted%C3%AC-01-10-2014-137515: Requesting header
WARNING: Falling back on generic information extractor.
[generic] dimarted%C3%AC-01-10-2014-137515: Downloading webpage
[generic] dimarted%C3%AC-01-10-2014-137515: Extracting information
ERROR: Unsupported URL: http://www.la7.it/dimartedi/rivedila7/dimarted%C3%AC-01-10-2014-137515; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 181, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 892, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: http://www.la7.it/dimartedi/rivedila7/dimarted%C3%AC-01-10-2014-137515; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
The URL mentioned in this issue is dead. I've fixed la7 and tested a similar URL: http://www.la7.it/omnibus/rivedila7/omnibus-news-02-07-2016-189077. If there's something wrong since the next version, feel free to open a new issue.
