### ISSUE TITLE
Downloading all videos from Youtube user: youtube-dl just downloads ridiculously many playlists pages

### ISSUE THREAD

**Issue by Solpo** [rg3/youtube-dl#3864]
When I'm trying to download all the videos from the Youtube user account Isvaffel2010, Youtube-dl just downloads video list pages but doesn't get to downloading the actual videos at all. Other channels I have tried have worked fine, somehow the problem seems to be specific to Isvaffel2010:s channel (although the bug can of course affect some other channels as well).

The command I run:
youtube-dl -o "~/isvaffel2010/%(upload_date)s_%(title)s_%(id)s.%(ext)s" --write-description --username xxxxxx --password yyyyyy -f best/18 -v --no-overwrites --restrict-filenames --playlist-end 800 https://www.youtube.com/playlist?list=UUhSBvT-fcrzzcAlFFGvMarA
Youtube-dl version: 2014.09.29.2
Python version: Python 2.7.3
My operating system is Xbian release candidate 3 on Raspberry Pi, based on Raspbian.

The when I run youtube-dl this is the (clipped) output I get
http://pastebin.com/cr8k5e2m

**Comment by dstftw** [comment]
Works fine with latest version.
