### ISSUE TITLE
firedrive.com  - RegexNotFoundError: Unable to extract title;

### ISSUE THREAD

**Issue by pibt** [rg3/youtube-dl#3870]
Version: 2014.09.29.2
File: http://www.firedrive.com/file/A50F7F511D4A5990

Also I noticed that in firedrive site, using naked putlocker.com domain redirects to the www.firedrive.com while using www.putlocker.com resolves directly to the file. So in youtube-dl while putlocker.com properly redirects to firedrive.com, www.putlocker.com falls back to generic mode

**Comment by naglis** [comment]
Both Firedrive and Sockhare seem to be mysteriously [gone for good](https://torrentfreak.com/firedrive-mystery-deepens-ios-and-android-apps-disappear-141006).

@phihag, do you think we should remove the extractors?

**Comment by naglis** [comment]
Firedrive extractor has been removed since Firedrive seems to be gone.
