### ISSUE TITLE
Add support to videotanker.co 

### ISSUE THREAD

**Issue by rsd3k** [rg3/youtube-dl#3871]
Please include support for http://videotanker.co/ if possible. 
sample video  http://videotanker.co/download.php?v=2W4BKMR528KH

**Comment by phihag** [comment]
The sample video seems to be from a copyrighted TV series. I cannot find any indication that either the VideoTanker has bought the copyright or that the copyright owners released the content under a free license. youtube-dl [does not support websites that infringe on copyrights](https://github.com/rg3/youtube-dl/blob/master/README.md#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Therefore, I am closing this issue.

If you believe that VideoTanker has the right to distribute the video, or can name an example video that does not infringe copyright, please say so and we will reopen this issue. Thanks!
