### ISSUE TITLE
Slash (/) in video title causes application to lock up

### ISSUE THREAD

**Issue by cclassic** [rg3/youtube-dl#3885]
When trying to download a video with an illegal character in the title such as a "/", youtube-dl locks up.

Example: youtube-dl "https://www.youtube.com/watch?v=lFSFdkXMOZo" with the title "Myself ; Yourself Ending Song (ENGLISH & JAPANESE LYRICS) |HD/HQ|"

Using "--restrict-filenames" does not solve the problem. However, getting the path with -g and downloading the video using an external program works.

Possible solution: Replace a / with an _.

```
youtube-dl -v "https://www.youtube.com/watch?v=lFSFdkXMOZo"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=lFSFdkXMOZo']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.10.05
[debug] Python version 2.7.6 - Linux-3.13.0-36-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[youtube] Setting language
[youtube] Confirming age
[youtube] lFSFdkXMOZo: Downloading webpage
[youtube] lFSFdkXMOZo: Downloading video info webpage
[youtube] lFSFdkXMOZo: Extracting video information
[debug] Invoking downloader on u'https://r5---sn-35cxacf-nuge.googlevideo.com/[...]'
```

**Comment by jaimeMF** [comment]
@cclassic latest youtube-dl veresions support the `--force-ipv4` option (but it's still experimental).
