### ISSUE TITLE
Vimeo Watch Later

### ISSUE THREAD

**Issue by RadAd** [rg3/youtube-dl#3886]
It seems it gets my watch later list ok but when trying to actually download the video it doesn't like the login info.

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-u', u'PRIVATE', '-p', u'PRIVATE', ':vimeowatchlater']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2014.09.29.2
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
vimeo:watchlater] Logging in
[vimeo:watchlater] watchlater: Downloading page 1
[download] Downloading playlist: Watch Later
[vimeo:watchlater] playlist Watch Later: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[vimeo] Logging in
ERROR: Wrong login info: HTTP Error 401: Unauthorized; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "youtube_dl\extractor\common.pyo", line 224, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1266, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

**Comment by RadAd** [comment]
Using version 2015.03.09I get:

youtube-dl :vimeowatchlater -u <user> -p <password>
[vimeo:watchlater] Logging in
ERROR: Unable to extract login token; please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type  youtube-dl -U  to up
date. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.

**Comment by jaimeMF** [comment]
I have fixed the login, at least it works for me.
Please comment when you try the next version, to know if we should investigate more or not.

**Comment by RadAd** [comment]
With version 2015.03.15 when the playlist is empty it works correctly, however to actually download a file I get an error:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', ':vimeowatchlater', '-u', u'PRIVATE', '
-p', u'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.15
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-70704-g3b63819, ffprobe N-70704-g3b63819, rtmpdum
p 2.4
[debug] Proxy map: {}
[vimeo:watchlater] Logging in
[vimeo:watchlater] watchlater: Downloading page 1
[download] Downloading playlist: Watch Later
[vimeo:watchlater] playlist Watch Later: Collected 1 video ids (downloading 1 of
 them)
[download] Downloading video 1 of 1
[vimeo] Logging in
ERROR: Wrong login info: HTTP Error 401: Unauthorized (caused by HTTPError()); p
lease report this issue on https://yt-dl.org/bug . Make sure you are using the l
atest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with t
he --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 314, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1679, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

**Comment by jaimeMF** [comment]
It works for me, could you try downloading with the specific video url and username and password?

**Comment by RadAd** [comment]
It works when I download the specific file:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://vimeo.com/72598776', '-u', u'P
RIVATE', '-p', u'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.15
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-70704-g3b63819, ffprobe N-70704-g3b63819, rtmpdum
p 2.4
[debug] Proxy map: {}
[vimeo] Logging in
[vimeo] 72598776: Downloading webpage
[vimeo] 72598776: Extracting information
[vimeo] 72598776: Downloading webpage
[debug] Invoking downloader on u'https://pdlvimeocdn-a.akamaihd.net/42005/647/18
6926756.mp4?token2=1426502875_cca4eceb1058674348577036badc260c&aksessionid=be071
4bc89f9c069'
[download] Destination: A New Man-72598776.mp4
[download]   2.8% of 131.01MiB at  1.63MiB/s ETA 01:18
ERROR: Interrupted by user



It doesn't work when I download it from the watch later list:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', ':vimeowatchlater', '-u', u'PRIVATE', '
-p', u'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.15
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-70704-g3b63819, ffprobe N-70704-g3b63819, rtmpdum
p 2.4
[debug] Proxy map: {}
[vimeo:watchlater] Logging in
[vimeo:watchlater] watchlater: Downloading page 1
[download] Downloading playlist: Watch Later
[vimeo:watchlater] playlist Watch Later: Collected 1 video ids (downloading 1 of
 them)
[download] Downloading video 1 of 1
[vimeo] Logging in
ERROR: Wrong login info: HTTP Error 401: Unauthorized (caused by HTTPError()); p
lease report this issue on https://yt-dl.org/bug . Make sure you are using the l
atest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with t
he --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 314, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1679, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

**Comment by jaimeMF** [comment]
They use the same code, so I don't understand why one of them fails.
A workaround is to use the following command: `youtube-dl -u <user> -p <password> :vimeowatchlater --dump-single-json --flat-playlist | youtube-dl --load-info -`

**Comment by RadAd** [comment]
Thanks, the workaround works fine for me.

Something I have noticed is that when downloading the watch later list it logs in twice, presumable once for the list and again to download the actual videos.

The first time it logs in the login token always ends in '.0', ie 92e578b732281df617045b3863621aba.0
The second time it logs in its looks like: 1d717533adf204ed82100e7876ce700f.2530dbae785d
8a8cf5e37005f0aba610

But in your workaround both times it logs in the token ends in '.0'
I did use 'youtube-dl --load-info - -u <user> -p <password>' in the workaround just to test this.

**Comment by jaimeMF** [comment]
It's the same in my case, so I have no clue of why it doesn't work for you.

**Comment by machtwebseiten** [comment]
I think this is related to the login-token problem #6488 we are having, as using the Workaround from @RadAd yields

> youtube-dl -u <USER> :vimeowatchlater --dump-single-json --flat-playlist --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', 'PRIVATE', ':vimeowatchlater', '--dump-single-json', '--flat-playlist', '--verbose']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.08.09
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to extract login token; please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 285, in extract
    self.initialize()
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 279, in initialize
    self._real_initialize()
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\vimeo.py", line 618, in _real_initialize
    self._login()
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\vimeo.py", line 42, in _login
    token = self._search_regex(r'xsrft":"(.*?)"', webpage, 'login token')
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 568, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract login token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version.
