### ISSUE TITLE
Complete support for 1080p and 4k video on YouTube

### ISSUE THREAD

**Issue by DrBobLo** [rg3/youtube-dl#3887]
![youtube high definition selections](https://cloud.githubusercontent.com/assets/9030632/4520906/3b1b13a4-4d00-11e4-8533-4f29c92c0dba.png)
Support for best or default quality only downloads 720p resolution on YouTube when 1080p and 4k video is actual available. YouTube for some time has supported video in 1080p as well as 4k (1440p and 2160p) resolutions.

Since not everyone will have the need or desire to download 1080p, 1440, or 2160p resolutions, I suggest adding support and invoking it simply such as: -f 1080 or -f 1440 or -f 2160

Even attempting the download at mx quality results in a 720p video being delivered

Bobs-MacBook-Pro-7:Youtube boblopez$ sudo youtube-dl https://www.youtube.com/watch?v=iNJdPyoqt8U --max-quality FORMAT
[youtube] Setting language
[youtube] Confirming age
[youtube] iNJdPyoqt8U: Downloading webpage
[youtube] iNJdPyoqt8U: Downloading video info webpage
[youtube] iNJdPyoqt8U: Extracting video information
[download] Destination: COSTA RICA IN 4K 60fps (ULTRA HD) w_ Freefly Movi-iNJdPyoqt8U.mp4
[download] 100% of 93.40MiB in 00:35
Bobs-MacBook-Pro-7:Youtube boblopez$ 

Thank you.

Screenshot sample is from:
https://www.youtube.com/watch?v=iNJdPyoqt8U

**Comment by endeavorfrazer** [comment]
You may also try this method from http://www.allavsoft.com/how-to/download-2160p-4k-ultra-hd-video-from-youtube.html﻿

**Comment by Hrxn** [comment]
^404: Not found.
