### ISSUE TITLE
Empty Playlist error

### ISSUE THREAD

**Issue by BonzoFestoon** [rg3/youtube-dl#3896]
The link works in Chrome:

```
D:\youtube-dl>youtube-dl.exe --verbose "http://video.scholastic.com/services/player/bcpid75580074001?bckey=AQ~~,AAAAAFv844g~,BASb5BU03X_l9AdwGvsCRhRAI
3eFS6eT&amp;bclid=0&amp;bctid=3695093189001"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://video.scholastic.com/services/player/bcpid75580074001?bckey=AQ~~,AAAAAFv844g~,BASb5BU03X_l9AdwGvsCRhR
AI3eFS6eT&amp;bclid=0&amp;bctid=3695093189001']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.10.05.2
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] bcpid75580074001?bckey=AQ~~,AAAAAFv844g~,BASb5BU03X_l9AdwGvsCRhRAI3eFS6eT&amp;bclid=0&amp;bctid=3695093189001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bcpid75580074001?bckey=AQ~~,AAAAAFv844g~,BASb5BU03X_l9AdwGvsCRhRAI3eFS6eT&amp;bclid=0&amp;bctid=3695093189001: Downloading webpage
[generic] bcpid75580074001?bckey=AQ~~,AAAAAFv844g~,BASb5BU03X_l9AdwGvsCRhRAI3eFS6eT&amp;bclid=0&amp;bctid=3695093189001: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: Book Fairs Single Video
[generic] playlist Book Fairs Single Video: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[Brightcove] AQ~~,AAAAAFv844g~,BASb5BU03X_l9AdwGvsCRhRAI3eFS6eT: Downloading playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete
 output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 524, in extract_info
  File "youtube_dl\extractor\common.pyo", line 193, in extract
  File "youtube_dl\extractor\brightcove.pyo", line 195, in _real_extract
  File "youtube_dl\extractor\brightcove.pyo", line 233, in _get_playlist_info
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its
 complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

```

**Comment by DestyNova** [comment]
I get the same error message with a Brightcove type video for this test URL:
http://www.tg4.tv/play.php?pid=4268526703001&title=Olive%20the%20Ostrich&series=Olive%20the%20Ostrich

**Comment by KonomiKitten** [comment]
Also getting the same error.

`youtube-dl --verbose 'http://video.scholastic.com/services/player/bcpid75580074001?bckey=AQ~~,AAAAAFv844g~,BASb5BU03X_l9AdwGvsCRhRAI3eFS6eT&amp;bclid=0&amp;bctid=3695093189001'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://video.scholastic.com/services/player/bcpid75580074001?bckey=AQ~~,AAAAAFv844g~,BASb5BU03X_l9AdwGvsCRhRAI3eFS6eT&amp;bclid=0&amp;bctid=3695093189001']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8, rtmpdump 2.4
[debug] Proxy map: {}
[generic] bcpid75580074001?bckey=AQ~~,AAAAAFv844g~,BASb5BU03X_l9AdwGvsCRhRAI3eFS6eT&amp;bclid=0&amp;bctid=3695093189001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bcpid75580074001?bckey=AQ~~,AAAAAFv844g~,BASb5BU03X_l9AdwGvsCRhRAI3eFS6eT&amp;bclid=0&amp;bctid=3695093189001: Downloading webpage
[generic] bcpid75580074001?bckey=AQ~~,AAAAAFv844g~,BASb5BU03X_l9AdwGvsCRhRAI3eFS6eT&amp;bclid=0&amp;bctid=3695093189001: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: Book Fairs Single Video
[generic] playlist Book Fairs Single Video: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] AQ~~,AAAAAFv844g~,BASb5BU03X_l9AdwGvsCRhRAI3eFS6eT: Downloading playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 244, in _real_extract
    return self._get_playlist_info(player_key[0])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 281, in _get_playlist_info
    raise ExtractorError('Empty playlist')
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by remitamine** [comment]
can be downloaded using:
```
youtube-dl http://link.brightcove.com/services/player/bcpid75580074001?bctid=3695093189001
[brightcove:legacy] 3695093189001: Downloading webpage
[brightcove:legacy] 3695093189001: Extracting information
[download] Destination: PRE FAIR Commercial-3695093189001.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8926k  100 8926k    0     0   591k      0  0:00:15  0:00:15 --:--:--  535k
[curl] Downloaded 9140662 bytes
[download] 100% of 8.72MiB in 00:15
```
