### ISSUE TITLE
Add support for using axel (was: Improve Download)

### ISSUE THREAD

**Issue by sreevisakh** [rg3/youtube-dl#3901]
Can you use downloader like axel to download the file.  axel with -n 32 gives a very good improvement in the speed of download

**Comment by denji** [comment]
`--external-downloader aria2c`

http://aria2.sourceforge.net/manual/en/html/aria2c.html
`aria2c --file-allocation=none -c -x 10 -s 10 -d "mydir" URL`

**Comment by denji** [comment]
https://github.com/rg3/youtube-dl/blob/cc9ca3b/youtube_dl/downloader/external.py#L96-L109

**Comment by dstftw** [comment]
Axel support has been added quite some time ago in e0ac521438218e978b9c4bbcd92cfc2d5fef79cb. Use `--external-downloader axel --external-downloader-args '-n 32'`.

**Comment by denji** [comment]
@dstftw `--external-downloader-args '-n 32 -a'`

**Comment by dstftw** [comment]
`-a` is just another variant of progress indication.
