### ISSUE TITLE
Updating youtube-dl fails, claims success, odd result

### ISSUE THREAD

**Issue by grauerkoala** [rg3/youtube-dl#3908]
I have installed youtube-dl using apt-get on Debian Wheezy:
`$ sudo apt-get install youtube-dl`

The version is rather old (2012.02.27), so i decided to update it:

```
$ sudo youtube-dl --update
Updating to latest version...
Updated youtube-dl. Restart youtube-dl to use the new version.
```

Though it appears to have been a success, the result is this:

```
$ youtube-dl --version
/usr/bin/youtube-dl: line 1: Not: command not found
```

What's that?, I wondered. Turns out, the contents of `/usr/bin/youtube-dl` have been rendered rather useless during the update:

```
$ cat /usr/bin/youtube-dl
Not Found
```

I used to have a far more recent version of youtube-dl than that since I had updated it a few, well, months back (sadly I did not take note of what it actually was), so I'm fairly confident that this error exists in later versions than 2012.02.27.

**Comment by rajvanshipradeep15** [comment]
Hello Phihag,

I have done the same as you have suggested but I get this error every time when I try to download,

youtube-dl http://youtu.be/Ds0qIpeEn3o
[youtube] Setting language
[youtube] Ds0qIpeEn3o: Downloading video webpage
[youtube] Ds0qIpeEn3o: Downloading video info webpage
[youtube] Ds0qIpeEn3o: Extracting video information
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 4645, in <module>
    main()
  File "/usr/bin/youtube-dl", line 4636, in main
    _real_main()
  File "/usr/bin/youtube-dl", line 4620, in _real_main
    retcode = fd.download(all_urls)
  File "/usr/bin/youtube-dl", line 869, in download
    ie.extract(url)
  File "/usr/bin/youtube-dl", line 1135, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl", line 1406, in _real_extract
    url_map = dict((ud['itag'][0], ud['url'][0] + '&signature=' + ud['sig'][0]) for ud in url_data)
  File "/usr/bin/youtube-dl", line 1406, in <genexpr>
    url_map = dict((ud['itag'][0], ud['url'][0] + '&signature=' + ud['sig'][0]) for ud in url_data)
KeyError: 'sig'

Please guide me to fix this error.

**Comment by phihag** [comment]
@rajvanshipradeep15 Your problem is completely unrelated to this one. Please open a [new issue](https://github.com/rg3/youtube-dl/issues/new). Do not forget to consult [our FAQ](https://yt-dl.org/update) and our [bug reporting guidelines](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md) before opening the issue.

**Comment by MrRKernelPanic** [comment]
Thank you so much, came across this fix when trying to run youtube-dl on a Raspberry Pi 2, worked like a charm and fixed the inability to download Vevo videos! Keep up the excellent work. :)

**Comment by xDinomode** [comment]
@phihag Just thought I'd let you know that I attempted to install following [these instructions](https://rg3.github.io/youtube-dl/download.html)  on the official website and had the same problem (for linux). But following your instructions made it work.

**Comment by zick53** [comment]
Latest youtube-dl
Error on OS X 10.11.5:
/usr/local/bin/youtube-dl: line 1: 302: command not found

**Comment by yan12125** [comment]
@zick53 Remove the existing ```/usr/local/bin/youtube-dl``` and re-download it. If you're using curl, an additional ```-L``` is necessary for the latest version. See https://github.com/rg3/youtube-dl#installation
