### ISSUE TITLE
ERROR: Unable to confirm age: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by lokendar** [rg3/youtube-dl#3920]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-o', '/mnt/mp3/11712.mp3', 'http://www.youtube.com/watch?v=zeWpQAA6MY4', '--restrict-filenames', '--extract-audio', '--audio-format', 'mp3', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.10.05.2
[debug] Python version 2.7.3 - Linux-3.2.0-36-virtual-x86_64-with-Ubuntu-12.04-precise
[debug] Proxy map: {}
[youtube] Setting language
[youtube] Confirming age
ERROR: Unable to confirm age: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 226, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1266, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by jaimeMF** [comment]
If you can't watch the video on a browser from the same computer, youtube-dl can't download it. [See this FAQ entry](https://github.com/rg3/youtube-dl/blob/eb6cb9fbe934fe99a35af22065cf91063d416c12/README.md#http-error-429-too-many-requests-or-402-payment-required)
