### ISSUE TITLE
ERROR: This video is only available for registered users, use --username and --password options to provide account credentials.

### ISSUE THREAD

**Issue by AbhimanyuAryan** [rg3/youtube-dl#3936]
i generally use youtube-dl -t <link> to download any video. What should be the command with credentials  to download this video?

**Comment by BETLOG** [comment]
I just got the same error attempting to download facebook videos that are public.
It's possible the hong-kong context is related, but the fact that I can watch and not download them is weird.

> ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.

https://www.facebook.com/jovan.ferraz/videos/465222417443406/
https://www.facebook.com/jovan.ferraz/videos/465222527443395/

I get the same failure on:
Kubuntu 18.04
youtube-dl --version
2019.10.22
2019.11.05

Kubuntu 14.04
youtube-dl --version
2019-07-16

**Comment by cswjohnni** [comment]
for facebook private video, you have to use the .netrc file, the file would contains as following:

machine facebook
login xxxxx (here is your facebook login ID/username)
password xxxxx (here is your facebook login password)

the .netrc file should be in your home folder, for example Apple$
use ls -a to see if the .netrc file is there

then, use the command
youtube-dl https://www.facebook.com/xxxx (here is your facebook video link URL) --netrc

**Comment by sizemo** [comment]
I'm getting this message for videos that aren't private. You can click on the link and watch them while you're logged out.

**Comment by binyominzeev** [comment]
For me this solution worked (even for public videos): https://webapps.stackexchange.com/questions/58690/how-can-i-download-non-public-facebook-video/92332
