### ISSUE TITLE
download n-tvnow

### ISSUE THREAD

**Issue by h0arry** [rg3/youtube-dl#3951]
youtube-dl 'http://www.n-tvnow.de/deluxe-alles-was-spass-macht/thema-ua-luxushotel-fuer-vierbeiner.php?container_id=153819&player=1&season=0' --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.n-tvnow.de/deluxe-alles-was-spass-macht/thema-ua-luxushotel-fuer-vierbeiner.php?container_id=153819&player=1&season=0', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.10.13
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] Proxy map: {}
[RTLnow] 153819: Downloading webpage
WARNING: unable to extract upload date; please report this issue on http://yt-dl.org/bug
ERROR: Unable to extract playerdata_url; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 193, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rtlnow.py", line 120, in _real_extract
    r"'playerdata': '(?P<playerdata_url>[^']+)'", webpage, 'playerdata_url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 428, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 418, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract playerdata_url; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
Closing since n-tv is now served by nowtv.de.
