### ISSUE TITLE
UnavailableVideoError: [Errno 84] Invalid or incomplete multibyte or wide character

### ISSUE THREAD

**Issue by pejobo** [rg3/youtube-dl#3968]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.prosieben.de/tv/greys-anatomy/video/1013-folge-13-umbrueche-ganze-folge']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2014.10.15
[debug] Python version 2.7.3 - Linux-3.10.36-armv6l-with-debian-7.5
[debug] Proxy map: {}
[prosiebensat1] tv/greys-anatomy/video/1013-folge-13-umbrueche-ganze-folge: Downloading webpage
[prosiebensat1] 2879185: Downloading videos JSON
[prosiebensat1] 2879185: Downloading sources JSON
[prosiebensat1] 2879185: Downloading urls JSON
[debug] Invoking downloader on u'http://psdvodhdsdrm.dcp.adaptive.level3.net/mp4-840/2879000/2879185-840-428666.mp4.f4m?nvb=20141016160732&nva=20141023180732&token=0c7aa96436b1c5966804c'
[download] Downloading f4m manifest
[download] Destination: Folge 13 - Umbr▒che-2879185.f4m
ERROR: unable to download video
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1067, in download
    self.extract_info(url)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 535, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 577, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 845, in process_video_result
    self.process_info(new_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1042, in process_info
    raise UnavailableVideoError(err)
UnavailableVideoError: [Errno 84] Invalid or incomplete multibyte or wide character: 'Folge 13 - Umbr\xfcche-2879185.f4m.part'

**Comment by dstftw** [comment]
This video is no longer available.
