### ISSUE TITLE
[prosiebensat1] Add support for playlists

### ISSUE THREAD

**Issue by pejobo** [rg3/youtube-dl#3969]
on "the-voice-of-germany.de", a site of prosiebensat1 group..

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.the-voice-of-germany.de/playlists/staffel-4/folge-2-blind-audition-ii']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2014.10.15
[debug] Python version 2.7.3 - Linux-3.10.36-armv6l-with-debian-7.5
[debug] Proxy map: {}
[prosiebensat1] playlists/staffel-4/folge-2-blind-audition-ii: Downloading webpage
ERROR: Unable to extract clip id; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 193, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/prosiebensat1.py", line 186, in _real_extract
    clip_id = self._html_search_regex(self._CLIPID_REGEXES, webpage, 'clip id')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 424, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract clip id; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
Playlists are now supported.
