### ISSUE TITLE
Any timeout, any re-try option?

### ISSUE THREAD

**Issue by mickyz** [rg3/youtube-dl#3975]
~$ youtube-dl -f bestaudio https://www.youtube.com/watch?v=*** -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', 'bestaudio', 'https://www.youtube.com/watch?v=***', '-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.10.15
[debug] Python version 2.7.6 - Linux-3.13.0-38-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[youtube] Setting language

From this moment on nothing happens and the script gets stuck often and should be stopped manually.

**Comment by mickyz** [comment]
the option --socket-timeout 2 (seconds?) not always exit and anyway without re-try the download :(

**Comment by dstftw** [comment]
`--retries`.
