### ISSUE TITLE
limited to 1050 videos!

### ISSUE THREAD

**Issue by electroweak** [rg3/youtube-dl#3981]
Hi,

using youtube-dl-2014.10.15
I am seeing a hidden limit on the number of videos downloadable from a channel...
It's saying there are only 1050 videos in 35 pages (presumably 30 vids/page) -- but there are far more than 1050..
e.g. here is a command but it stops at 1050! ..:
youtube-dl https://www.youtube.com/channel/UCK08_B5SZwoEUk2hDPMOijQ   --f 17/36/18/best --no-part -i

the output is:
...
[youtube:channel] UCK08_B5SZwoEUk2hDPMOijQ: Downloading page #34
[youtube:channel] UCK08_B5SZwoEUk2hDPMOijQ: Downloading page #35
[youtube] Channel UCK08_B5SZwoEUk2hDPMOijQ: Found 1050 videos
[download] Downloading playlist: UCK08_B5SZwoEUk2hDPMOijQ
[youtube:channel] playlist UCK08_B5SZwoEUk2hDPMOijQ: Collected 1050 video ids (downloading 1050 of them)
...

Please help!! - I'm new to youtube-dl and I was not expecting such a limit. I've invested quite a lot of time over the last 3 days getting this to run over several channels and only now did I find this issue. Was it present in older versions, I wonder??

**Comment by nimajalali** [comment]
bump

Any updates on this issue. The "ytuser" work around is no longer an option because of #5646

**Comment by dstftw** [comment]
This issue has been fixed in 386bdfa698a7f06c43df91913677db3732e29900 quite some time ago.
