### ISSUE TITLE
RTLnow not working

### ISSUE THREAD

**Issue by retsifp** [rg3/youtube-dl#3982]
Downloading works, but the output data is rubbish.
This bug consists since several weeks.

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://rtl-now.rtl.de/wer-wird-millionaer/show-zum-15-jaehrigen-jubilaeum.php?film_id=174107&player=1&season=34', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.10.15
[debug] Python version 2.7.8 - Linux-3.16-2-amd64-x86_64-with-debian-jessie-sid
[debug] Proxy map: {}
[RTLnow] 174107: Downloading webpage
[RTLnow] 174107: Downloading player data XML
[debug] Invoking downloader on 'http://hds.fra.rtlnow.de/hds-vod-enc/rtlnow/videos/35/V_602335_CRR8_E93453_110269_h264-mq_c0e6a5dac7bfbef4a28cbc7999734126.f4v.f4m?ts=1413652042'

**Comment by dstftw** [comment]
Closing since rtlnow is now served by nowtv.de.
