### ISSUE TITLE
Don't know what this error means

### ISSUE THREAD

**Issue by ThorodanBrom** [rg3/youtube-dl#3993]
Have downloaded the latest Win .exe file for youtube-dl, and have downloaded Python 3.4.2, yet this error comes
![captured](https://cloud.githubusercontent.com/assets/9331293/4713355/e67bc85c-58df-11e4-8a86-e044d03ca5d4.JPG)

I mean the second one, about the non-hexadecimal digit
Is this something to do about my network?

**Comment by dstftw** [comment]
Closing due to no response for a long time.
