### ISSUE TITLE
digital.films.com

### ISSUE THREAD

**Issue by jcollie** [rg3/youtube-dl#4004]
$ youtube-dl http://digital.films.com/play/NUN8ZY
[generic] NUN8ZY: Requesting header
WARNING: Falling back on generic information extractor.
[generic] NUN8ZY: Downloading webpage
[generic] NUN8ZY: Extracting information
ERROR: Unsupported URL: http://digital.films.com/play/NUN8ZY; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
[jeff@svr01 Media]$ youtube-dl --verbose http://digital.films.com/play/NUN8ZY
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://digital.films.com/play/NUN8ZY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.22.1
[debug] Python version 2.7.5 - Linux-3.16.3-200.fc20.x86_64-x86_64-with-fedora-20-Heisenbug
[debug] Proxy map: {}
[generic] NUN8ZY: Requesting header
WARNING: Falling back on generic information extractor.
[generic] NUN8ZY: Downloading webpage
[generic] NUN8ZY: Extracting information
ERROR: Unsupported URL: http://digital.films.com/play/NUN8ZY; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 545, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 1509, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: undefined entity &nbsp;: line 353, column 36
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 180, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 890, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://digital.films.com/play/NUN8ZY; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by TRox1972** [comment]
digital.films.com now redirects to infobase.com.

**Comment by yan12125** [comment]
The video embedded in this link will be correctly detected in the next version.
