### ISSUE TITLE
avconv + aac conversion fails - need to enable experimental features

### ISSUE THREAD

**Issue by dinamic** [rg3/youtube-dl#4012]
Using the default conversion via avconv fails if AAC has been specified as audio format.

```
ERROR: audio conversion failed: Add '-strict experimental' if you want to use it.
```

This is because the support is considered experimental.
In order to enable it, the following should be added to the command line:

```
-strict experimental
```

I would love to contribute a PR, but I don't have Python experience.

**Comment by dstftw** [comment]
Use `--postprocessor-args '-strict experimental'` or update avconv/ffmpeg.
