### ISSUE TITLE
Automatically extract ASS subs when available

### ISSUE THREAD

**Issue by ChrisK2** [rg3/youtube-dl#4019]
(See #4003 for context)

We currently have to know beforehand if we want to have ASS subs, which requires a site-specific check, which we'd like to avoid. It would be good if ytdl would output ASS subs by default when available (in the case of CR, the SRT subs are completely broken anyway), or if it would be possible to specify an order of prefered formarts, just like for video:
``--sub-format=ass/srt``

**Comment by jaimeMF** [comment]
Thanks for the suggestion, it will work with the syntax you proposed in the next version (and in the case of crunchyroll it will default to ass).
