### ISSUE TITLE
Deredactie.be - new site request

### ISSUE THREAD

**Issue by midas02** [rg3/youtube-dl#4027]
Hi,

I would very much appreciate it if you could implement support for the Belgian national broadcaster VRT. They have three official sites, all of them use the same streaming format which I can't seem to figure out. The sites are: deredactie.be, sporza.be and cobra.be.

Here's a sample clip, the daily news:
http://deredactie.be/cm/vrtnieuws/videozone/programmas/journaal

Error returned is a simple ERROR: Unsupported URL.

Many thanks!

**Comment by sharethewisdom** [comment]
As of today, `deredactie.be` now redirects to `vrt.be/vrtnws` and video content is accessible from logged on accounts on `vrt.be/vrtnu`. I made a vrtnu.py extractor based on vrt.py, but I could not get it to work and after a few hours I gave up.
