### ISSUE TITLE
How do I use --max-quality correctly?

### ISSUE THREAD

**Issue by esamo** [rg3/youtube-dl#4028]
Hello again and thanks for a great tool.

Why for example "youtube-dl --max-quality=480p Hd27MHRwnMI" will download video 720p while Youtube shows smaller versions / worse quality available? How should I use the option?

Regards & respect.

**Comment by jaimeMF** [comment]
With the last version of youtube-dl you can use `-f best[height<=480]`. As @clampak said `--max-quality` is intended to work with the format codes.
