### ISSUE TITLE
iyme-uwgrRw

### ISSUE THREAD

**Issue by elvvcw** [rg3/youtube-dl#4031]
I try do access this video. I get the message:
ERROR: iyme-uwgrRw: YouTube said: This video contains content from Mosfilm, who has blocked it from display on this website.<br/><u><a href='http://www.youtube.com/watch?v=iyme-uwgrRw&feature=player_embedded' target='_blank'>Watch on YouTube</a></u>
What does that mean? Providing a referer does not help.

**Comment by dstftw** [comment]
Duplicate of #343.
