### ISSUE TITLE
Option to only download XXXp or a format blacklist

### ISSUE THREAD

**Issue by incognico** [rg3/youtube-dl#406]
I want the possibility to do something like "--max-quality 720p". Since the format codes are a bit random it is hard to only download a specific resolution without using -F and -f which basically does not work youtube-dl is automated.

Generally specifying --max-quality 46 for 1080p would not work since it would download 3072p being format 38 which is lower.

Alternatively --format-blacklist="37,38,46" would work for 720p but personally I prefer the first suggestion.

**Comment by jaimeMF** [comment]
With the last version of youtube-dl, you can apply filters in the format option. In your case `-f 'best[width<=720]'` should work. Thanks for the report!
