### ISSUE TITLE
Resume support for  trilulilu.ro

### ISSUE THREAD

**Issue by nelucampean** [rg3/youtube-dl#4067]
Youtube-dl cannot download anymore from trilulilu.ro since the site changed it\s javascript/html.
Please resume download support for trilulilu.ro.
example of download url from trilulilu.ro : http://www.trilulilu.ro/cei-mai-draguti-ursuleti-panda#ref=home
Youtube-dl output with --verbose parameter:

D:\Tools>youtube-dl.exe --verbose  http://www.trilulilu.ro/cei-mai-draguti-ursuleti-panda#ref=home
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.trilulilu.ro/cei-mai-dragut
i-ursuleti-panda#ref=home']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.10.30
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-66521-
[debug] Proxy map: {}
[generic] cei-mai-draguti-ursuleti-panda#ref=home: Requesting header
WARNING: Falling back on generic information extractor.
[generic] cei-mai-draguti-ursuleti-panda#ref=home: Downloading webpage
[generic] cei-mai-draguti-ursuleti-panda#ref=home: Extracting information
ERROR: Unsupported URL: http://www.trilulilu.ro/cei-mai-draguti-ursuleti-panda#r
ef=home; please report this issue on https://yt-dl.org/bug . Be sure to call you
tube-dl with the --verbose flag and include its complete output. Make sure you a
re using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 581, in _real_extract
  File "youtube_dl\utils.pyo", line 1629, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 533, in extract_info
  File "youtube_dl\extractor\common.pyo", line 198, in extract
  File "youtube_dl\extractor\generic.pyo", line 962, in _real_extract
ExtractorError: Unsupported URL: http://www.trilulilu.ro/cei-mai-draguti-ursulet
i-panda#ref=home; please report this issue on https://yt-dl.org/bug . Be sure to
 call youtube-dl with the --verbose flag and include its complete output. Make s
ure you are using the latest version; type  youtube-dl -U  to update.

Have a nice day
Nelu Campean

**Comment by naglis** [comment]
This issue should be fixed in the next release of youtube-dl. Thanks for the report.

**Comment by phihag** [comment]
Fixed in youtube-dl 2015.09.02.3 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
