### ISSUE TITLE
Downloading subtitles for npo.nl possible?

### ISSUE THREAD

**Issue by pvdl** [rg3/youtube-dl#4089]
There is a possibility for subtitles for the npo.nl video's.
If you hit the 'T' button in the player you get the video with subtitles.
Is there a possibility to download the subtitles?

**Comment by endeavorfrazer** [comment]
You may also try this method to download videos as well as subtitles from npo.nl 
http://www.allavsoft.com/how-to/download-npo-nl-videos.html
