### ISSUE TITLE
Download failed for vh1

### ISSUE THREAD

**Issue by astral2k5** [rg3/youtube-dl#4091]
Trying to download this video:
http://www.vh1.com/video/misc/1095605/daniel-radcliffe-talks-hair-extensions-and-the-horror-of-losing-his-hair.jhtml

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.vh1.com/video/misc/1095605/daniel-radcliffe-talks-hair-extensions-and-the-horror-of-losing-his-hair.jhtml']
[debug] Encodings: locale cp1250, fs mbcs, out None, pref cp1250
[debug] youtube-dl version 2014.10.30
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-62728-
[debug] Proxy map: {}
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1052, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1028, in dl
  File "youtube_dl\downloader\common.pyo", line 292, in download
  File "youtube_dl\downloader\http.pyo", line 64, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1286, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 400: Bad Request

**Comment by remitamine** [comment]
it's working.i think it's a temporary error.
```
python2 __main__.py http://www.vh1.com/video/misc/1095605/daniel-radcliffe-talks-hair-extensions-and-the-horror-of-losing-his-hair.jhtml
[vh1.com] 1095605: Downloading info
[vh1.com] 1095605: Extracting information
[vh1.com] 1095605: Downloading video urls
[download] Downloading playlist: 1095605
[vh1.com] playlist 1095605: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[download] Destination: Daniel Radcliffe Talks Hair Extensions and the Horror of Losing His Hair-1095605.mp4
[#9bb2de 30MiB/30MiB(99%) CN:3 DL:104KiB]                                      
12/31 19:10:34 [NOTICE] Download complete: /home/amine/youtube-dl/youtube_dl/Daniel Radcliffe Talks Hair Extensions and the Horror of Losing His Hair-1095605.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
9bb2de|OK  |   145KiB/s|/home/amine/youtube-dl/youtube_dl/Daniel Radcliffe Talks Hair Extensions and the Horror of Losing His Hair-1095605.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 31820490 bytes
[download] 100% of 30.35MiB
[download] Finished downloading playlist: 1095605
```

**Comment by viewbowl** [comment]
I use Allavsoft to Download Music Videos from VH1to any Video or Audio Format.You may find it at 
http://www.allavsoft.com/how-to/vh1-downloader.html

**Comment by viewbowl** [comment]
I use Allavsoft to Download Music Videos from VH1to any Video or Audio Format.
