### ISSUE TITLE
"--max-quality" doesn't work with "-f bestvideo+bestaudio"

### ISSUE THREAD

**Issue by ericzutter** [rg3/youtube-dl#4151]
I want to download the best quality in maximum 1080p and skip downloading 4K videos. A solution would be to use "--max-quality 137+141" with "-f bestvideo+bestaudio". But these two parameters doesn't work together.

See here an example. In my example I have put the "--max-quality" to the lowest quality in DASH format, to show that the "--max-quality" parameter doesn't work.

Instead of "--max-quality 160+139", youtube-dl.exe downloads format 141+135 (= best format) :

C:\>youtube-dl.exe -v --max-quality 160+139 -f bestvideo+bestaudio https://www.youtube.com/watch?v=hD5MRBzY1uM

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--max-quality', '160+139', '-f', 'bestvideo+bestaudio', 'https://www.youtube.com/watch?v=hD5MRBzY1uM']
[debug] Encodings: locale cp1252, fs mbcs, out cp65001, pref cp1252
[debug] youtube-dl version 2014.11.09
[debug] Python version 2.7.8 - Windows-7-6.1.7600
[debug] exe versions: ffmpeg N-62912-
[debug] Proxy map: {}
[youtube] Confirming age
[youtube] hD5MRBzY1uM: Downloading webpage
[youtube] hD5MRBzY1uM: Downloading video info webpage
[youtube] hD5MRBzY1uM: Extracting video information
[youtube] hD5MRBzY1uM: Encrypted signatures detected.
[youtube] {43} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] {18} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] {5} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] {36} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] {17} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] {135} signature length 40.40, html5 player en_US-vflbcuqSZ
[youtube] hD5MRBzY1uM: Downloading js player vflbcuqSZ
[youtube] {244} signature length 40.40, html5 player en_US-vflbcuqSZ
[youtube] {134} signature length 40.40, html5 player en_US-vflbcuqSZ
[youtube] {243} signature length 40.40, html5 player en_US-vflbcuqSZ
[youtube] {133} signature length 40.40, html5 player en_US-vflbcuqSZ
[youtube] {242} signature length 40.40, html5 player en_US-vflbcuqSZ
[youtube] {160} signature length 40.40, html5 player en_US-vflbcuqSZ
[youtube] {140} signature length 40.40, html5 player en_US-vflbcuqSZ
[youtube] {171} signature length 40.40, html5 player en_US-vflbcuqSZ
[youtube] {135} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] {244} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] {134} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] {243} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] {133} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] {242} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] {160} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] {140} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] {171} signature length 40.43, html5 player en_US-vflbcuqSZ
[youtube] hD5MRBzY1uM: Downloading DASH manifest
[debug] Invoking downloader on 'https://r2---sn-oxv-25ge.googlevideo.com/videoplayback?id=843e4c441cd8d6e3&itag=135&source=youtube&requiressl=yes&gcr=be&mm=31&mv=m&ms=au&ratebypass=yes&mime=video/mp4&gir=yes&clen=24752812&lmt=1394292254326947&dur=215.959&sver=3&mt=1415659701&key=dg_yt0&upn=EXdheHBwwkc&signature=725F04658F0C6DD956D6F68BC88C0841545D24F2.18FCA93E139846AC756523769D56EA1DB48C01B1&fexp=905639,905701,907259,908582,916640,930666,932404,934929,942493,943909,947209,947215,948124,952302,952605,952901,953912,957103,957105,957201&ip=46.253.172.132&ipbits=0&expire=1415681347&sparams=ip,ipbits,expire,id,itag,source,requiressl,gcr,mm,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Rihanna - If It's Lovin' That You Want-hD5MRBzY1uM.f135.mp4
[download] 100% of 23.61MiB in 00:02
[debug] Invoking downloader on 'https://r2---sn-oxv-25ge.googlevideo.com/videoplayback?id=843e4c441cd8d6e3&itag=141&source=youtube&requiressl=yes&gcr=be&mm=31&mv=m&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=6889146&lmt=1394292240318266&dur=216.061&sver=3&mt=1415659701&key=dg_yt0&upn=EXdheHBwwkc&signature=29A7E74ECCD42B0D09110EE07338A52EBBC57744.211380BED9C3FC7072F536FF59BC3F49FD74B110&fexp=905639,905701,907259,908582,916640,930666,932404,934929,942493,943909,947209,947215,948124,952302,952605,952901,953912,957103,957105,957201&ip=46.253.172.132&ipbits=0&expire=1415681347&sparams=ip,ipbits,expire,id,itag,source,requiressl,gcr,mm,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Rihanna - If It's Lovin' That You Want-hD5MRBzY1uM.f141.m4a
[download] 100% of 6.57MiB in 00:00
[ffmpeg] Merging formats into "Rihanna - If It's Lovin' That You Want-hD5MRBzY1uM.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'Rihanna - If It'"'"'s Lovin'"'"' That You Want-hD5MRBzY1uM.f135.mp4' -i 'Rihanna - If It'"'"'s Lovin'"'"' That You Want-hD5MRBzY1uM.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 -shortest 'Rihanna - If It'"'"'s Lovin'"'"' That You Want-hD5MRBzY1uM.mp4'

**Comment by dstftw** [comment]
`--max-quality` has been removed in favor to `-f`. You can specify flexible filters and described in [FAQ](https://github.com/rg3/youtube-dl#format-selection).
