### ISSUE TITLE
Downloaded content from NBC, unable to view-codecs not described correctly

### ISSUE THREAD

**Issue by harlanb** [rg3/youtube-dl#4159]
Here is the verbose output from downloading an episode from NBC.  I tried viewing it with mplayer and vlc on Ubuntu 14.04.
```
youtube-dl -v http://www.nbc.com/deception/video/pilot/n30467?onid=146221#vc146221=1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.nbc.com/deception/video/pilot/n30467?onid=146221#vc146221=1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.25
[debug] Python version 2.7.6 - Linux-3.13.0-36-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[NBC] n30467: Downloading webpage
[ThePlatform] 7sbhMUnWozi9: Downloading config
[ThePlatform] 7sbhMUnWozi9: Downloading XML
[ThePlatform] 7sbhMUnWozi9: Downloading webpage
[ThePlatform] 7sbhMUnWozi9: Downloading f4m manifest
[debug] Invoking downloader on u'http://nbcdotcom-f.akamaihd.net/z/NBCdotCOM/1968b869039c20875a749436bd01a74f_,1696,1296,0896,0696,0496,0306,0240,0150,0064,.mp4.csmil/manifest.f4m?&g=UXWGVKRWHFSP&hdcore=3.0.3'
[download] Downloading f4m manifest
[download] Destination: Pilot-7sbhMUnWozi9.flv
[download] 100% of 552.74MiB in 08:26
```
```
vlc Pilot-7sbhMUnWozi9.flv 
VLC media player 2.1.4 Rincewind (revision 2.1.4-0-g2a072be)
[0x1e99118] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[flv @ 0x7faf2cc20be0] Could not find codec parameters (Video: [0][0][0][0] / 0x0000, 1639 kb/s)
[flv @ 0x7faf2cc20be0] Could not find codec parameters (Audio: [0][0][0][0] / 0x0000, 0 channels, 97 kb/s)
[flv @ 0x7faf0cc09d40] Could not find codec parameters (Video: [0][0][0][0] / 0x0000, 1639 kb/s)
[flv @ 0x7faf0cc09d40] Could not find codec parameters (Audio: [0][0][0][0] / 0x0000, 0 channels, 97 kb/s)
[0x7faf0cc01808] avformat demux error: Unknown option "threads"
[0x7faf0cc0d608] main decoder error: no suitable decoder module for fourcc `undf'. VLC probably does not support this sound or video format.
[0x7faf0cc0a6b8] main decoder error: no suitable decoder module for fourcc `undf'. VLC probably does not support this sound or video format.
```
Thanks!  Great program!

**Comment by dsysoev** [comment]
### The same problem

```youtube-dl -v https://www.youtube.com/watch?v=et281UHNoOU```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=et281UHNoOU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.7.6 - Linux-3.16.0-38-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] et281UHNoOU: Downloading webpage
[youtube] et281UHNoOU: Downloading video info webpage
[youtube] et281UHNoOU: Extracting video information
[youtube] {22} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {43} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {18} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {5} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {36} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {17} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {137} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {136} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {135} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {134} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {133} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {160} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {140} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {171} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {249} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {250} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {251} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] et281UHNoOU: Downloading DASH manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r12---sn-axq7sn7e.googlevideo.com/videoplayback?id=7addbcd541cda0e5&itag=137&source=youtube&requiressl=yes&gcr=ru&mm=31&mn=sn-axq7sn7e&pl=20&mv=m&ms=au&hcs=yes&shardbypass=yes&ratebypass=yes&mime=video/mp4&gir=yes&clen=92683474&lmt=1452849412615116&dur=417.720&sver=3&signature=6546AC22CB7C212C058C5631526598D897C8558A.61F9084CEAEA755EB31B62CD055DEF6F51A08F5C&fexp=9407116,9408087,9415031,9416126,9417298,9419451,9420452,9420540,9422596,9423037,9423339,9423573,9423662,9424417,9425226,9425703,9426483&mt=1453064234&upn=xFd4bnf3Pmc&key=dg_yt0&ip=89.223.47.215&ipbits=0&expire=1453085910&sparams=ip,ipbits,expire,id,itag,source,requiressl,gcr,mm,mn,pl,mv,ms,hcs,shardbypass,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Ленинград — Экспонат-et281UHNoOU.f137.mp4
[download] 100% of 88.39MiB in 00:20
[debug] Invoking downloader on u'https://r12---sn-axq7sn7e.googlevideo.com/videoplayback?ipbits=0&dur=417.721&sver=3&expire=1453085910&source=youtube&gcr=ru&mm=31&mn=sn-axq7sn7e&id=o-AGMqhkqsawek5mn1-YW8EuCl_HMTMwX0wdXxgUIOFBpX&pl=20&ip=89.223.47.215&requiressl=yes&mt=1453064234&mv=m&sparams=clen%2Cdur%2Cgcr%2Cgir%2Chcs%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Cshardbypass%2Csource%2Cupn%2Cexpire&fexp=9407116%2C9408087%2C9415031%2C9416126%2C9417298%2C9419451%2C9420452%2C9420540%2C9422596%2C9423037%2C9423339%2C9423573%2C9423662%2C9424417%2C9425226%2C9425703%2C9426483&ms=au&keepalive=yes&initcwndbps=2752500&hcs=yes&upn=xFd4bnf3Pmc&shardbypass=yes&clen=6534424&itag=251&key=yt6&gir=yes&mime=audio%2Fwebm&lmt=1452697403340584&signature=6902E986DAF4551300A46FB03B092009083E48CB.115CFDA6100579CA3F79D590FE0F52C19CED6F3D&ratebypass=yes'
[download] Destination: Ленинград — Экспонат-et281UHNoOU.f251.webm
[download] 100% of 6.23MiB in 00:01
[ffmpeg] Merging formats into "Ленинград — Экспонат-et281UHNoOU.mkv"
[debug] ffmpeg command line: avconv -y -i 'file:Ленинград — Экспонат-et281UHNoOU.f137.mp4' -i 'file:Ленинград — Экспонат-et281UHNoOU.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Ленинград — Экспонат-et281UHNoOU.temp.mkv'
Deleting original file Ленинград — Экспонат-et281UHNoOU.f137.mp4 (pass -k to keep)
Deleting original file Ленинград — Экспонат-et281UHNoOU.f251.webm (pass -k to keep)

### play by vlc 

```vlc Ленинград\ —\ Экспонат-et281UHNoOU.mkv```
VLC media player 2.1.6 Rincewind (revision 2.1.6-0-gea01d28)
[0x1673058] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[0x7fe058c019e8] mkv demux error: unknown codec id=`A_OPUS'
[0x7fe058c2e0e8] main decoder error: no suitable decoder module for fourcc `undf'. VLC probably does not support this sound or video format.
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
[0x7fe03c001248] main vout display error: Failed to resize display

### avconv log 

```avconv -i Ленинград\ —\ Экспонат-et281UHNoOU.mkv ```
avconv version 11.3-6:11.3-1~trusty, Copyright (c) 2000-2014 the Libav developers
  built on Apr 13 2015 22:25:55 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
Input #0, matroska,webm, from 'Ленинград — Экспонат-et281UHNoOU.mkv':
  Metadata:
    MAJOR_BRAND     : dash
    MINOR_VERSION   : 0
    COMPATIBLE_BRANDS: iso6avc1mp41
    CREATION_TIME   : 2016-01-15 09:11:15
    ENCODER         : Lavf56.1.0
  Duration: 00:06:57.77, start: 0.000000, bitrate: N/A
    Stream #0.0(und): Video: h264 (High), yuv420p, 1920x1080 [PAR 1:1 DAR 16:9], 25 fps, 1k tbn, 50 tbc (default)
    Metadata:
      CREATION_TIME   : 2016-01-15 09:11:15
      LANGUAGE        : und
    Stream #0.1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
At least one output file must be specified

**Comment by yan12125** [comment]
With avconv v12_dev0-2242-g9cdddb9 and vlc 2.2.1, this video plays fine. Maybe there are bugs in old avconv/vlc. Try to upgrade your copies or use ffmpeg instead of avconv (you may need ```--prefer-ffmpeg```). If problems are still, open a new bug report as YouTube is different from NBC.

**Comment by dsysoev** [comment]
### Thank for help! It's work.

sudo add-apt-repository ppa:mc3man/trusty-media
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install ffmpeg

and then used ```--prefer-ffmpeg``` options)

**Comment by yan12125** [comment]
As @harlanb had no feedback, I guess he/she had solved the problem. Closing.
