### ISSUE TITLE
NBA URL

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#4167]
URL: http://www.nba.com/raptors/video/2014/11/11/NBAWEB141111BOUCHARDRAPTORmp4-3433066

youtube-dl -v http://www.nba.com/raptors/video/2014/11/11/NBAWEB141111BOUCHARDRAPTORmp4-3433066
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.nba.com/raptors/video/2014/11/11/N
BAWEB141111BOUCHARDRAPTORmp4-3433066']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.11.12.1
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-
[debug] Proxy map: {}
[generic] NBAWEB141111BOUCHARDRAPTORmp4-3433066: Requesting header
WARNING: Falling back on generic information extractor.
[generic] NBAWEB141111BOUCHARDRAPTORmp4-3433066: Downloading webpage
[generic] NBAWEB141111BOUCHARDRAPTORmp4-3433066: Extracting information
ERROR: Unsupported URL: http://www.nba.com/raptors/video/2014/11/11/NBAWEB141111
BOUCHARDRAPTORmp4-3433066; please report this issue on https://yt-dl.org/bug . B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 599, in _real_extract
  File "youtube_dl\utils.pyo", line 1310, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: duplicate attribute: line 3, column 2
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 536, in extract_info
  File "youtube_dl\extractor\common.pyo", line 199, in extract
  File "youtube_dl\extractor\generic.pyo", line 980, in _real_extract
ExtractorError: Unsupported URL: http://www.nba.com/raptors/video/2014/11/11/NBA
WEB141111BOUCHARDRAPTORmp4-3433066; please report this issue on https://yt-dl.or
g/bug . Be sure to call youtube-dl with the --verbose flag and include its compl
ete output. Make sure you are using the latest version; type  youtube-dl -U  to
update.

As always, thanks in advance!
Ringo

**Comment by yan12125** [comment]
Thanks for the report. Such URLs will be supported in the next version.
