### ISSUE TITLE
this video contains content from who has blocked it from display on this website - WATCH on YOUTUBE

### ISSUE THREAD

**Issue by arlindpajaziti** [rg3/youtube-dl#4195]
this video https://www.youtube.com/watch?v=_5K4yxcuRO4 cant be downloaded with youtube-dl
also when you embed this video to any site you see this message 
this video contains content from who has blocked it from display on this website - WATCH on YOUTUBE

---

[root@server ~]# youtube-dl https://www.youtube.com/watch?v=_5K4yxcuRO4
[youtube] Setting language
[youtube] Confirming age
[youtube] _5K4yxcuRO4: Downloading webpage
[youtube] _5K4yxcuRO4: Downloading video info webpage
[youtube] _5K4yxcuRO4: Extracting video information
[youtube] _5K4yxcuRO4: Encrypted signatures detected.
[youtube] _5K4yxcuRO4: Downloading js player vflBuyJ2c
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 533, in _decr                                                                                        ypt_signature
    video_id, player_url, s
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 447, in _extr                                                                                        act_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 508, in _pars                                                                                        e_sig_js
    'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 424, in _searc                                                                                        h_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name;                                                                                         please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl                                                                                         with the --verbose flag and include its complete output. Make sure you are using                                                                                         the latest version; type  youtube-dl -U  to update.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player s                                                                                        ignature function name\x1b[0m; please report this issue on https://yt-dl.org/bug                                                                                         . Be sure to call youtube-dl with the --verbose flag and include its complete o                                                                                        utput. Make sure you are using the latest version; type  youtube-dl -U  to updat                                                                                        e.',)); please report this issue on https://yt-dl.org/bug . Be sure to call yout                                                                                        ube-dl with the --verbose flag and include its complete output. Make sure you ar                                                                                        e using the latest version; type  youtube-dl -U  to update.
[root@server ~]#

**Comment by ryanakca** [comment]
I can comment on this with the verbose output using the most recent version available:

ryan@nu:~/Videos2/Youtube/Movies$ youtube-dl --verbose --list-subs https://www.youtube.com/watch?v=sfjFnOpnh_c
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--list-subs', u'https://www.youtube.com/watch?v=sfjFnOpnh_c']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.10rc1 - Linux-4.0.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 2.6.3-1, ffprobe 2.6.3-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] sfjFnOpnh_c: Downloading webpage
[youtube] sfjFnOpnh_c: Downloading embed webpage
[youtube] sfjFnOpnh_c: Refetching age-gated info webpage
ERROR: sfjFnOpnh_c: YouTube said: This video contains content from Mosfilm, who has blocked it from display on this website.<br/><u><a href='http://www.youtube.com/watch?v=sfjFnOpnh_c&feature=player_embedded' target='_blank'>Watch on YouTube</a></u>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2015.5.20-py2.7.egg/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2015.5.20-py2.7.egg/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2015.5.20-py2.7.egg/youtube_dl/extractor/youtube.py", line 906, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: sfjFnOpnh_c: YouTube said: This video contains content from Mosfilm, who has blocked it from display on this website.<br/><u><a href='http://www.youtube.com/watch?v=sfjFnOpnh_c&feature=player_embedded' target='_blank'>Watch on YouTube</a></u>

ryan@nu:~/Videos2/Youtube/Movies$ youtube-dl --verbose -t https://www.youtube.com/watch?v=sfjFnOpnh_c
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-t', u'https://www.youtube.com/watch?v=sfjFnOpnh_c']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.10rc1 - Linux-4.0.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 2.6.3-1, ffprobe 2.6.3-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] sfjFnOpnh_c: Downloading webpage
[youtube] sfjFnOpnh_c: Downloading embed webpage
[youtube] sfjFnOpnh_c: Refetching age-gated info webpage
ERROR: sfjFnOpnh_c: YouTube said: This video contains content from Mosfilm, who has blocked it from display on this website.<br/><u><a href='http://www.youtube.com/watch?v=sfjFnOpnh_c&feature=player_embedded' target='_blank'>Watch on YouTube</a></u>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2015.5.20-py2.7.egg/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2015.5.20-py2.7.egg/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2015.5.20-py2.7.egg/youtube_dl/extractor/youtube.py", line 906, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: sfjFnOpnh_c: YouTube said: This video contains content from Mosfilm, who has blocked it from display on this website.<br/><u><a href='http://www.youtube.com/watch?v=sfjFnOpnh_c&feature=player_embedded' target='_blank'>Watch on YouTube</a></u>

**Comment by banderlog** [comment]
Same issue

```
banderlog@notebook:~$ youtube-dl https://www.youtube.com/watch?v=7dhXHN-Jsws --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=7dhXHN-Jsws', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.8.7 (CPython) - Linux-5.4.0-62-generic-x86_64-with-glibc2.27
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[youtube] 7dhXHN-Jsws: Downloading webpage
[youtube] 7dhXHN-Jsws: Downloading embed webpage
[youtube] 7dhXHN-Jsws: Refetching age-gated info webpage
ERROR: This video contains content from Mosfilm, who has blocked it from display on this website or application. Watch on YouTube
Traceback (most recent call last):
  File "/home/bkaba/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/home/bkaba/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 826, in __extract_info
    ie_result = ie.extract(url)
  File "/home/bkaba/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/bkaba/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2105, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video contains content from Mosfilm, who has blocked it from display on this website or application. Watch on YouTube
```
