### ISSUE TITLE
Can't play back downloaded YouTube videos after using -f bestvideo+bestaudio parameter?

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#4220]
I did a "youtube-dl -f bestvideo+bestaudio https://www.youtube.com/watch?v=AjSr8RvAzJE", but playing its local download back seems to be incomplete like after a quarter in it? I did not have this problem with other videos. Is anyone else seeing this problem too?

Thank you in advance. :)

**Comment by jaimeMF** [comment]
In the next version it won't use the `-shortest` option.
