### ISSUE TITLE
youtube-dl reports wrong video resolution (and doesn't download "best" option)

### ISSUE THREAD

**Issue by edumj** [rg3/youtube-dl#4241]
Hi,

in some standard resolution videos (max 480p) like https://www.youtube.com/watch?v=NY3VYW1DXH4, with the -f option I get the following formats:

...
format code extension resolution  note 
139         m4a       audio only  DASH audio   48k , audio@ 48k (22050Hz), 1.08MiB (worst)
140         m4a       audio only  DASH audio  127k , audio@128k (44100Hz), 2.88MiB
171         webm      audio only  DASH audio  154k , audio@128k (44100Hz), 3.10MiB
172         webm      audio only  DASH audio  244k , audio@256k (44100Hz), 4.67MiB
141         m4a       audio only  DASH audio  255k , audio@256k (44100Hz), 5.77MiB
278         webm      192x144     DASH video   74k , webm container, VP9, video only, 1.43MiB
160         mp4       192x144     DASH video  113k , video only, 2.48MiB
242         webm      320x240     DASH video  197k , video only, 3.56MiB
133         mp4       320x240     DASH video  246k , video only, 5.52MiB
243         webm      480x360     DASH video  332k , video only, 6.04MiB
134         mp4       480x360     DASH video  541k , video only, 7.20MiB
244         webm      640x480     DASH video  666k , video only, 10.99MiB
135         mp4       640x480     DASH video 1047k , video only, 14.65MiB
17          3gp       176x144     
36          3gp       320x240     
5           flv       400x240     
43          webm      640x360     
18          mp4       640x360     (best)

It says "640x360" is the best option, but it seems it doesn't exist! Because it should be "480x360" or "640x480" (both 4:3), not "640x360"! (16:9)
May be it's because of 4:3 videos?
And it downloads the lower "480x360" instead of the bigger "640x480".

Edu.

**Comment by phihag** [comment]
In the current version of youtube-dl (2015.01.22), the sizes reported by YouTube should take precedence over the ones we determined statically. If you have a video that's still being misidentified,  please post so. If you always want the max quality video, `-f bestvideo+bestaudio/best` is the way to go.
