### ISSUE TITLE
Add support for enthought.com (was: Unsupported UR)

### ISSUE THREAD

**Issue by byaruhaf** [rg3/youtube-dl#4253]
Got this error when trying to download some video's

╰─$ youtube-dl --verbose https://training.enthought.com/courses                                                                                                       1 ↵
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://training.enthought.com/courses']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.20
[debug] Python version 2.7.6 - Linux-3.13.0-39-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6
[debug] Proxy map: {}
[generic] courses: Requesting header
WARNING: Falling back on generic information extractor.
[generic] courses: Downloading webpage
[generic] courses: Extracting information
ERROR: Unsupported URL: https://training.enthought.com/courses; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 609, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1332, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 53, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 536, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 199, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 996, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: https://training.enthought.com/courses; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by mpenkov** [comment]
Needs a login.

It also looks like they aren't accepting new subscriptions or renewals, so it's probably not worth looking into too closely:

> IMPORTANT: Please note that we are no longer taking new subscriptions, extending or renewing existing subscriptions, or providing new academic access to Enthought’s online training. If you have an active subscription, there will be no change to service or support through the end of your current subscription period. The service will no longer be available, however, after the date your current subscription expires. If you have questions or concerns, please contact us at support@enthought.com. If you are interested in additional training, please visit our website at www.enthought.com/training for information about our live classroom training options.

**Comment by byaruhaf** [comment]
Thaks
