### ISSUE TITLE
--continue doesn't work with "-f bestvideo+bestaudio" and playlists

### ISSUE THREAD

**Issue by pilif** [rg3/youtube-dl#4255]
Normally, when you use --continue in conjunction with a youtube playlist, youtube-dl will skip files that are already downloaded.

In case of "-f bestvideo+bestaudio" (which pretty much is needed now in the age of 60fps videos which are only available as DASH streams), this detection fails though and the files are always re-downloaded.

**Comment by phil294** [comment]
This also applies to converting the audio stream: `--audio-format mp3`. Videos will be re-downloaded even though their respective end-product (`*.mp3`) already exists.

I would even consider this a bug, not a request. Workaround is to apply the converting manually afterwards.

**Comment by dstftw** [comment]
For such cases you should you `--download-archive`.
