### ISSUE TITLE
Damaged FLV with RTLnow

### ISSUE THREAD

**Issue by karlQY** [rg3/youtube-dl#4266]
I downloaded the files for the following three links:

http://rtl-now.rtl.de/rtl-boxen/rtl-boxen-countdown.php?film_id=178205&player=1&season=0
http://rtl-now.rtl.de/rtl-boxen/wladimir-klitschko-vs-kubrat-pulev.php?film_id=178203&player=1&season=0
http://rtl-now.rtl.de/rtl-boxen/nach-dem-kampf.php?film_id=178207&player=1&season=0

Download works, yet each resulting FLV does not play with VLC player. FFmpeg says "could not find codec parameters".

**Comment by moppman** [comment]
Same here.

**Comment by dstftw** [comment]
Closing since rtlnow is now served by nowtv.de.
