### ISSUE TITLE
libc.so.6: aborted attempt to load python!

### ISSUE THREAD

**Issue by FelixLeo** [rg3/youtube-dl#4268]
Dear Developers,
I do have a tiny issue with libc.so.6 library file when trying to run youtube_dl on 

Linux version 2.6.12.6-VENUS (airhank@localhost.localdomain) (gcc version 3.4.4 mipssde-6.03.01-20051114)

The issue is that this system is very limited and no way to get a real libc.so.6,
but the system do already have:

/lib/libc.so.0 -> libuClibc-0.9.28.so

If I do modify the youtube.dl/utils.py as following the youtube.dl works fine:

libc = ctypes.cdll.LoadLibrary("libc.so.0")

But if leave the youtube.dl unmodified in its original form and do create a symlink:

ln -s /lib/libc.so.0 /lib/libc.so.6

or

ln -s libuClibc-0.9.28.so /lib/libc.so.6

I do get the EM: libc.so.6: aborted attempt to load python!

Can you please advise if there is way to make youtube_dl work fine with such a symlink for libc.so.6 so that there is no need for me to make custom build of it on each update.

Thank you in advance.

**Comment by TRox1972** [comment]
No response in a long time. Should this be closed?

**Comment by yan12125** [comment]
@TRox1972 Thanks.
