### ISSUE TITLE
failed downloading a youku.com video

### ISSUE THREAD

**Issue by edwinyzh** [rg3/youtube-dl#4281]
My first try:

F:\Downloads 2>youtube-dl http://v.youku.com/v_show/id_XODI2ODM1MjEy.html?from=y
1.2-3-98.3.12-2.1-4-1-11
[Youku] XODI2ODM1MjEy: Downloading JSON metadata
WARNING: Extractor Youku returned a compat_list result. It needs to be updated.
ERROR: unable to download video data: HTTP Error 404: Not Found

Thanks.

**Comment by kehugter** [comment]
If it helps, using the same link as reference, youtube-dl's log show that the file is being fetched from

    http://k.youku.com/player/getFlvPath/sid/142935187410414327863_00/st/flv/fileid/03000201005466555069C100D332D6EA7A131F-D5C3-A44B-3B65-40C295721737?k=c257a6b3db25a8e4282a689f

http://savevideo.me/ managed to grab the video for me and the URL is

    http://k.youku.com/player/getFlvPath/sid/642935199812051ede1b3_01/st/flv/fileid/03000201005466555069C100D332D6EA7A131F-D5C3-A44B-3B65-40C295721737?K=c257a6b3db25a8e4282a689f&hd=0&ts=72&ctype=51&token=4866&ev=1&oip=528743450&ep=11IjkVXF1YYJmh2nBeKnOCLM3WGYBJqyz3Ufq3WlqjT5ii5AGTIV8mDfzTgAxoj8q9ovTZZWZ9Ilj7MPJVRv2dtyzpx1W6Sfc8g7F2%2Fq7r8aHCcrvj%2FHGi6nGjGUkA7M


Also, there's an option to get a MP4 instead of a FLV file

    http://k.youku.com/player/getFlvPath/sid/642935199812051ede1b3_01/st/mp4/fileid/03002001005466389E69C100D332D6EA7A131F-D5C3-A44B-3B65-40C295721737?K=9dfb1be8595f4b37261e4abb&hd=0&ts=72&ctype=51&token=4866&ev=1&oip=528743450&ep=11IjkVXF1YYJmh2nBeKnOCLM3WGYBJqyRvVG9Y8PHv%2Ba%2FJkBBD5gGWDfzTgAxoj8q9ovTZZWZ9Ilj7MPJVRv2dtyzpx1W6Sfc8g7F2%2Fq7r8aHCcrvj%2FHGi6nGjGUkA7M

**Comment by yan12125** [comment]
The most tough part is the ```ep``` parameter. More discussions can be found in soimort/you-get#331 (Warning: some of texts there are in Chinese)

This problem had been solved in you-get, but due to licensing (you-get uses MIT and youtube-dl uses UNLICENSE), we can't borrow the codes directly.

**Comment by yan12125** [comment]
Thanks to @PeterDing's work (#5833), this video will be supported in the next version.
