### ISSUE TITLE
Cannot select language for southpark videos

### ISSUE THREAD

**Issue by slhck** [rg3/youtube-dl#4286]
When downloading videos from `southpark.de`, I have no way to select which language the video should be in. The site offers both German and English through a menu, but youtube-dl only shows the following formats — and I can't select one because it errors out with `ERROR: requested format not available` (but that's not the purpose of this report).

```
youtube-dl --verbose -F http://www.southpark.de/alle-episoden/s03e09-beschnittene-pfadfinder-teil-3
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-F', 'http://www.southpark.de/alle-episoden/s03e09-beschnittene-pfadfinder-teil-3']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.16
[debug] Python version 2.7.6 - Darwin-14.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.4.3, ffprobe 2.4.3, rtmpdump 2.4
[debug] Proxy map: {}
[southpark.de] s03e09-beschnittene-pfadfinder-teil-3: Downloading webpage
[southpark.de] 600fd1d8-ecfd-11e0-aca6-0026b9414f30: Downloading info
[southpark.de] bumper: Extracting information
[southpark.de] bumper: Downloading video urls
[southpark.de] e61e5062-ed00-11e0-aca6-0026b9414f30: Extracting information
[southpark.de] e61e5062-ed00-11e0-aca6-0026b9414f30: Downloading video urls
[southpark.de] e61e9fcc-ed00-11e0-aca6-0026b9414f30: Extracting information
[southpark.de] e61e9fcc-ed00-11e0-aca6-0026b9414f30: Downloading video urls
[southpark.de] e61ef2ba-ed00-11e0-aca6-0026b9414f30: Extracting information
[southpark.de] e61ef2ba-ed00-11e0-aca6-0026b9414f30: Downloading video urls
[southpark.de] e61f5304-ed00-11e0-aca6-0026b9414f30: Extracting information
[southpark.de] e61f5304-ed00-11e0-aca6-0026b9414f30: Downloading video urls
[info] Available formats for bumper:
format code extension resolution  note
400         mp4       512x288
[info] Available formats for e61e5062-ed00-11e0-aca6-0026b9414f30:
format code extension resolution  note
400         mp4       480x360     (worst)
700         x-flv     640x480
600         mp4       640x480
800         mp4       640x480     (best)
[info] Available formats for e61e9fcc-ed00-11e0-aca6-0026b9414f30:
format code extension resolution  note
400         mp4       480x360     (worst)
700         x-flv     640x480
600         mp4       640x480
800         mp4       640x480     (best)
[info] Available formats for e61ef2ba-ed00-11e0-aca6-0026b9414f30:
format code extension resolution  note
400         mp4       480x360     (worst)
700         x-flv     640x480
600         mp4       640x480
800         mp4       640x480     (best)
[info] Available formats for e61f5304-ed00-11e0-aca6-0026b9414f30:
format code extension resolution  note
400         mp4       480x360     (worst)
700         x-flv     640x480
600         mp4       640x480
800         mp4       640x480     (best)
```

Apparently, the language is set via Flash variables from the HTML page:

```
var m = document.cookie.match(/SPS_video_language=([a-z][a-z])/);
  if (m && m.length > 1) flashvars.lang = m[1];
```

Any idea how this could be carried over to the extractor?

**Comment by bumbummen99** [comment]
Any updates on this issue?

**Comment by clydegale** [comment]
I'm having the same issue. Including this feature would be great.

**Comment by yan12125** [comment]
Related: #10758

**Comment by bumbummen99** [comment]
Nevermind, it is working fine for southpark.de

**Comment by slhck** [comment]
I don't have the means to confirm it now, but if you say it works, I'll close this then.

**Comment by Emgalai** [comment]
I would like to know how is the language selection supposed to work. How do I get the English episodes from southpark.de with youtube-dl? I can get a list of the different formats with the -F option, but none of those is in English.

**Comment by bumbummen99** [comment]
@Emgalai You can select the language by modifing the address:
```
Eng:
"http://southpark.cc.com/full-episodes/s" + currSeason + "e" + currEpisode;
Ger:
"http://southpark.de/alle-episoden/s" + currSeason + "e" + currEpisode;
```

**Comment by Emgalai** [comment]
I know that, but southpark.de has better maximum resolution, 1920x1080, while southpark.cc.com has just 1280x720. That's why I would like to get the English version from the German site.

**Comment by bumbummen99** [comment]
You could download the episodes from .de and then replace the m4a with the English version. But as far as i know there is no possibility to download English episodes directly from southpark.de

**Comment by Emgalai** [comment]
I know it is possible. Maybe not (yet) with youtube-dl, but I downloaded English episode from southpark.de with Video DownloadHelper Firefox addon.

But it seems that only the German versions have the higher resolution. So, merging two sources would be required to get a 1920x1080 English video from there as well...

**Comment by khoschi** [comment]
Well, language selection on the german site does NOT work - on the .de website this is done with a cookie (SPS_video_language en). A mixture of .de and .cc episodes won't work anymore (season 20+), as the domain .cc is distributing NTSC @ 23,976 fps and .de PAL @25 fps, so each act has different lengths - and you have to evade geoblock.

Any ideas? Passing cookies did not do the job, and -F does not list another audio stream.

**Comment by bumbummen99** [comment]
@khoschi that's true, mixing the two sources wont work anymore. @slhck i think this issue should be reopened.

**Comment by slhck** [comment]
I think it'd be better to open a new issue with the respective logs, as I cannot follow up on it anymore.

**Comment by Emgalai** [comment]
@khoschi There is no geoblocking. You can download from any country (I think) by using the episodes address, either http://southpark.cc.com/full-episodes/s21e01 or http://www.southpark.de/alle-episoden/s21e01 for example.

And I succesfully mixed the German and English episodes by MKVToolNix GUI. The episodes have different lenghts but only because the German episodes don't have the repeat part at the end.

**Comment by khoschi** [comment]
Geoblocking applies only for surfing the website, you're right. I've found different runtime only for episodes from season 20, so if you try s20e01 act1 you will find that both files have the same amount of frames, but .cc framerate is 23.976 and .de is 25 - and this time you have to fix the audio duration before mixing. Other seasons use 23.976 fps  for the .de domain as well.
