### ISSUE TITLE
Adultswim.com not able to download

### ISSUE THREAD

**Issue by simonbh** [rg3/youtube-dl#4317]
```
$youtube-dl --version
2014.11.26

$ youtube-dl --verbose http://www.adultswim.com/videos/lucy-the-daughter-of-the-devil/hes-not-the-messiah-hes-a-dj/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.adultswim.com/videos/lucy-the-daughter-of-the-devil/hes-not-the-messiah-hes-a-dj/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.26
[debug] Python version 3.4.2 - Linux-3.17.3-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.4.3, ffprobe 2.4.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] hes-not-the-messiah-hes-a-dj: Requesting header
WARNING: Falling back on generic information extractor.
[generic] hes-not-the-messiah-hes-a-dj: Downloading webpage
[generic] hes-not-the-messiah-hes-a-dj: Extracting information
ERROR: Unsupported URL: http://www.adultswim.com/videos/lucy-the-daughter-of-the-devil/hes-not-the-messiah-hes-a-dj/; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 553, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 240, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1044, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: http://www.adultswim.com/videos/lucy-the-daughter-of-the-devil/hes-not-the-messiah-hes-a-dj/; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by mattl** [comment]
Seems like they've changed something again. 

`$ youtube-dl --verbose http://www.adultswim.com/videos/decker/inside-decker-a-new-hero/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.adultswim.com/videos/decker/inside-decker-a-new-hero/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.01
[debug] Python version 2.7.6 - Linux-3.16.0-57-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-77455-g4707497, ffprobe N-77455-g4707497, rtmpdump 2.4
[debug] Proxy map: {}
[AdultSwim] inside-decker-a-new-hero: Downloading webpage
ERROR: Unable to find video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adultswim.py", line 137, in _real_extract
    raise ExtractorError('Unable to find video info')
`

**Comment by yan12125** [comment]
@mattl Could you open a new issue for that?

**Comment by mattl** [comment]
@yan12125 Done https://github.com/rg3/youtube-dl/issues/10235
