### ISSUE TITLE
New site request: vtm.be

### ISSUE THREAD

**Issue by midas02** [rg3/youtube-dl#4318]
Hello there,

Would it be possible to provide support for the following site? They use some kind of dynamic streaming, but I can't get the parameters right.

Example link:
http://vtm.be/video/volledige-afleveringen/id/256408587866000

Thanks!

**Comment by MichaelDeBoey** [comment]
+1 for this! :-)

using `youtube-dl http://vtm.be/video?aid=137771` works fine. (it's a video you can watch without an account).
But using `youtube-dl http://vtm.be/video?aid=144635` doesn't.
I tried using the `-u` option, but that didn't work either.

**Comment by yan12125** [comment]
I've looked into several examples on vtm.be, and all of them can be identified by youtube-dl. Closing this ticket as superseded by #9974.
