### ISSUE TITLE
Remove youtube id from the file name

### ISSUE THREAD

**Issue by cojack** [rg3/youtube-dl#4331]
Hello,
there is a simple script how to remove the youtube-id in the downloaded files (converted to *.mp3) from the file name:

\<removed, usage discouraged, use https://github.com/rg3/youtube-dl/issues/4331#issuecomment-64891140 instead\>

**Comment by Hrxn** [comment]
You already can download without any video ID..

Just use this:
`--output '%(title)s.%(ext)s'`

**Comment by dstftw** [comment]
Video id is added on purpose: it provides filename uniqueness. Removing it will break downloading videos with the same titles. If you want to break it - go and setup config file.
