### ISSUE TITLE
OoyalaIE wrong

### ISSUE THREAD

**Issue by traori** [rg3/youtube-dl#4336]
traori@Laptop:~$ youtube-dl --verbose http://player.ooyala.com/player.js?embedCode=FiOG81ZTrvckcchQxmalf4aQj590qTEx
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://player.ooyala.com/player.js?embedCode=FiOG81ZTrvckcchQxmalf4aQj590qTEx']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.27
[debug] Python version 2.7.6 - Linux-3.13.0-40-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[Ooyala] FiOG81ZTrvckcchQxmalf4aQj590qTEx: Downloading webpage
[Ooyala] FiOG81ZTrvckcchQxmalf4aQj590qTEx: Downloading mobile player JS for unknown device
[Ooyala] FiOG81ZTrvckcchQxmalf4aQj590qTEx: Downloading mobile player JS for iphone device
[Ooyala] FiOG81ZTrvckcchQxmalf4aQj590qTEx: Downloading mobile player JS for ipad device
[Ooyala] FiOG81ZTrvckcchQxmalf4aQj590qTEx: Downloading mobile player JS for android device
ERROR: Unable to extract info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 553, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 240, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ooyala.py", line 83, in _real_extract
    raise ExtractorError('Unable to extract info')
ExtractorError: Unable to extract info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
The video can be downloaded in the next version. Thanks for the link.

**Comment by traori** [comment]
GREAT

THX
