### ISSUE TITLE
ERROR: Unable to extract video id;RegexNotFoundError: Unable to extract video id; 

### ISSUE THREAD

**Issue by gilles-c** [rg3/youtube-dl#4340]
Here the output today :

$ youtube-dl -Fs --verbose http://www.francetvinfo.fr/replay-jt/france-2/20-heures/jt-de-20h-du-dimanche-30-novembre-2014_752591.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-Fs', '--verbose', 'http://www.francetvinfo.fr/replay-jt/france-2/20-heures/jt-de-20h-du-dimanche-30-novembre-2014_752591.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.27
[debug] Python version 2.7.3 - Linux-3.2.0-4-powerpc-smp-ppc-with-debian-7.7
[debug] exe versions: avconv 0.8.16-6, avprobe 0.8.16-6, ffmpeg 0.8.16-6, ffprobe 0.8.16-6
[debug] Proxy map: {}
[francetvinfo.fr] jt-de-20h-du-dimanche-30-novembre-2014_752591: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 553, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 240, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 139, in _real_extract
    r'id-video=([^@]+@[^"]+)', webpage, 'video id').split('@')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 480, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by keepreason** [comment]
Here is another easy method http://www.allavsoft.com/how-to/francetvinfo.fr-download.html
