### ISSUE TITLE
WDR / Rockpalast

### ISSUE THREAD

**Issue by johnjohndoe** [rg3/youtube-dl#4353]
How about these URL?

> http://www.wdr.de/tv/rockpalast/extra/videos/2014/1125/beatsteaks.jsp

**Comment by yan12125** [comment]
All links mentioned in this ticket is dead, and the following Rockpalast video works fine with the latest git master: http://www1.wdr.de/mediathek/video/sendungen/rockpalast/video-rockpalast-blind-guardian---rock-hard-festival--100.html. Closing.
