### ISSUE TITLE
Unable to download webpage: <urlopen error [Errno 60] Operation timed out>

### ISSUE THREAD

**Issue by amio** [rg3/youtube-dl#4361]
```shell
Downloads » youtube-dl -f bestaudio WBVnF0sr8Xc --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', 'bestaudio', 'WBVnF0sr8Xc', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.01
[debug] Python version 2.7.6 - Darwin-14.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.4.4, ffprobe 2.4.4
[debug] Proxy map: {}
[youtube] WBVnF0sr8Xc: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 60] Operation timed out> (caused by URLError(error(60, 'Operation timed out'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 274, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1321, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 410, in https_open
    return self.do_open(HTTPSConnectionV3, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
```

Seems like a same problem as #3785

**Comment by amio** [comment]
I figure out what happened, It was block by my ISP.
Adding a `--proxy xxx`will fix it.

**Comment by pastriver** [comment]
there is a message that "urllib2.URLError: <urlopen error [Errno 60] Operation timed out>",can you help to figure out what is the problem

**Comment by kongkong-mia** [comment]
> ```shell
> 下载 » youtube-dl -f bestaudio WBVnF0sr8Xc --verbose
> [调试] 系统配置：[]
> [调试] 用户配置：[]
> [调试]命令行参数：[ ' -f '，' bestaudio '，' WBVnF0sr8Xc '，' --verbose ' ]
> [调试] 编码：语言环境 UTF-8、fs utf-8、out UTF-8、pref UTF-8
> [调试] youtube-dl 版本 2014.12.01
> [调试] Python 版本 2.7.6 - Darwin-14.0.0-x86_64-i386-64bit
> [调试] exe 版本：ffmpeg 2.4.4、ffprobe 2.4.4
> [调试] 代理映射：{}
> [youtube] WBVnF0sr8Xc：下载网页
> 错误：无法下载网页：< urlopen 错误 [Errno 60] 操作超时>（由 URLError(error(60, ' Operation timed out ' ),) 引起）
>   文件“ /usr/local/bin/youtube-dl/youtube_dl/extractor/common.py ”，第274行，在_request_webpage
>      return self._downloader.urlopen(url_or_request)
>   文件“ /usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py ”，第 1321 行，在urlopen 中
>     返回self._opener.open(req, timeout=self._socket_timeout)
>   文件“ /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py ”，线路404，在开
>     response = self._open(req, data)
>   文件“ /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py ”，第 422 行，在_open
>      ' _open ' 中，要求）
>   文件“ /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py ”，第382行，在_call_chain
>     结果 = func( * args)
>   文件“ /usr/local/bin/youtube-dl/youtube_dl/utils.py ”，第 410 行，在https_open 中
>     return self.do_open(HTTPSConnectionV3, req)
>   文件“ /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py ”，第 1184 行，在do_open
>     引发 URLError(err)
> ```
> 
> 好像和#3785一样的问题[](https://github.com/ytdl-org/youtube-dl/issues/3785)

when I first time met this  problem in the command of youtube-dl  0f downloading,I have tried to change  the VPN software V2rayU from the pac mode to （全局）/global mode ,then  everything is ok.Maybe it can help you.
