### ISSUE TITLE
[cliphunter] ERROR: Unable to extract video data;

### ISSUE THREAD

**Issue by mrthrowaway** [rg3/youtube-dl#4362]
$ youtube-dl -v http://www.cliphunter.com/w/1012420/Fun_Jynx_Maze_solo
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.cliphunter.com/w/1012420/Fun_Jynx_Maze_solo']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.03
[debug] Python version 2.7.6 - Linux-3.13.0-40-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[cliphunter] 1012420: Downloading webpage
ERROR: Unable to extract video data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 553, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 241, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cliphunter.py", line 48, in _real_extract
    r'pl_fiji = \'([^\']+)\'', webpage, 'video data')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 481, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by naglis** [comment]
This issue should be fixed in the next release of youtube-dl. Thanks for the report.

**Comment by phihag** [comment]
The fix made it into youtube-dl 2015.01.25. See [our FAQ](https://yt-dl.org/update) if you need help updating.
