### ISSUE TITLE
[Feature] Azubu.tv

### ISSUE THREAD

**Issue by guidorugo** [rg3/youtube-dl#4379]
Support for azubu.tv streams/video

**Comment by curi** [comment]
i would like to download the VOD archives from http://www.azubu.tv/sake

can someone tell me how to do this? i don't see how to get an archives link, or individual video links, on the page. i can play a single archive video (click VOD near the top right then click a video), but it doesn't change the URL i'm at. right clicking the archive videos doesn't let me copy the URL and i didn't figure it out by looking at the page source either.

i frequently download youtube and twitch channels with a single command which works great. i would like to do that with azubu, or at least download individual archive videos.
