### ISSUE TITLE
Add support for espn.go.com

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#4396]
SITE: ESPN
EXAMPLE URLs:
http://espn.go.com/video/clip?id=espn:11988965
http://espn.go.com/video/clip?id=10365079

example points to: rtmp://svod.espn.go.com/motion/2014/1206/dm_141206_Wash_St_vs_UTSA/mp4:dm_141206_Wash_St_vs_UTSA_432p30_2096k.mp4.

**Comment by RingoTheDog** [comment]
ESPN is listed as broken, ...but  today it is kinda working (sometimes fails?)
I was switching ffmpeg version...couldn't find a pattern.

Thought I'd let ya' know.

C:\>youtube-dl http://espn.go.com/video/clip?id=10365079 -o "C:\test.mp4"
WARNING: The program functionality for this site has been marked as broken, and
will probably not work.
[ESPN] clip?id=10365079: Downloading webpage
[ESPN] 10365079: Downloading webpage
[OoyalaExternal] 10365079: Downloading webpage
[OoyalaExternal] 10365079: Downloading mobile player JS for unknown device
[OoyalaExternal] FkYWtmazr6Ed8xmvILvKLWjd4QvYZpzG: Downloading m3u8 information
[download] Destination: C:\test.mp4
ffmpeg version N-71346-gdf4fca2 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-l
ibilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enab
le-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --en
able-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --ena
ble-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc
 --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enabl
e-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --ena
ble-decklink --enable-zlib
  libavutil      54. 22.101 / 54. 22.101
  libavcodec     56. 34.100 / 56. 34.100
  libavformat    56. 30.100 / 56. 30.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 13.101 /  5. 13.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[http @ 0000000002fe08c0] HTTP error 404 Not Found
http://vod.espn.go.com/motion/2014/0128/dm_140128_30for30Shorts___JudgingJewellv
2/hls/78668_HBR.m3u8: Server returned 404 Not Found


sometimes works 


C:\>youtube-dl http://espn.go.com/video/clip?id=10365079 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://espn.go.com/video/clip?id=10365079', u'-v']

[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20
[debug] Proxy map: {}
WARNING: The program functionality for this site has been marked as broken, and
will probably not work.
[ESPN] clip?id=10365079: Downloading webpage
[ESPN] 10365079: Downloading webpage
[OoyalaExternal] 10365079: Downloading webpage
[OoyalaExternal] 10365079: Downloading mobile player JS for unknown device
[OoyalaExternal] FkYWtmazr6Ed8xmvILvKLWjd4QvYZpzG: Downloading m3u8 information
[debug] Invoking downloader on u'http://vod.espn.go.com/motion/2014/0128/dm_1401
28_30for30Shorts___JudgingJewellv2/hls/78668_HBR.m3u8'
[download] Destination: dm_140128_30for30Shorts_JudgingJewellv2-FkYWtmazr6Ed8xmv
ILvKLWjd4QvYZpzG.mp4
ffmpeg version N-40824-g31dfe20 Copyright (c) 2000-2012 the FFmpeg developers
  built on May 19 2012 00:45:59 with gcc 4.6.3
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-ru
ntime-cpudetect --enable-avisynth --enable-bzlib --enable-frei0r --enable-libass
 --enable-libcelt --enable-libopencore-amrnb --enable-libopencore-amrwb --enable
-libfreetype --enable-libgsm --enable-libmp3lame --enable-libnut --enable-libope
njpeg --enable-librtmp --enable-libschroedinger --enable-libspeex --enable-libth
eora --enable-libutvideo --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-
libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --e
nable-zlib
  libavutil      51. 53.100 / 51. 53.100
  libavcodec     54. 21.101 / 54. 21.101
  libavformat    54.  5.100 / 54.  5.100
  libavdevice    53.  4.100 / 53.  4.100
  libavfilter     2. 74.101 /  2. 74.101
  libswscale      2.  1.100 /  2.  1.100
  libswresample   0. 12.100 /  0. 12.100
  libpostproc    52.  0.100 / 52.  0.100
Input #0, hls,applehttp, from 'http://vod.espn.go.com/motion/2014/0128/dm_140128
_30for30Shorts___JudgingJewellv2/hls/78668_HBR.m3u8':
  Duration: 00:21:41.00, start: 2.051967, bitrate: 0 kb/s
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720
[SAR 1:1 DAR 16:9], 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, s16
Output #0, mp4, to 'dm_140128_30for30Shorts_JudgingJewellv2-FkYWtmazr6Ed8xmvILvK
LWjd4QvYZpzG.mp4.part':
  Metadata:
    encoder         : Lavf54.5.100
    Stream #0:0: Video: h264 (![0][0][0] / 0x0021), yuv420p, 1280x720 [SAR 1:1 D
AR 16:9], q=2-31, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (@[0][0][0] / 0x0040), 48000 Hz, stereo
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   69 fps=0.0 q=-1.0 size=    1190kB time=00:00:02.26 bitrate=4297.9kbits/
frame=  152 fps=148 q=-1.0 size=    2790kB time=00:00:05.03 bitrate=4536.8kbits/
frame=  209 fps=136 q=-1.0 size=    4386kB time=00:00:06.94 bitrate=5176.5kbits/
frame=  271 fps=127 q=-1.0 size=    5535kB time=00:00:09.00 bitrate=5032.9kbits/
frame=  330 fps=125 q=-1.0 size=    6702kB time=00:00:10.97 bitrate=5001.3kbits/
frame=  373 fps=117 q=-1.0 Lsize=    7451kB time=00:00:12.41 bitrate=4917.6kbits

etc  etc etc......

**Comment by RingoTheDog** [comment]
youtube-dl -v http://espn.go.com/video/clip?id=espn:13071042&startTime=00:00
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://espn.go.com/video/clip?id=espn:13071
042']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
WARNING: The program functionality for this site has been marked as broken, and
will probably not work.
[ESPN] clip?id=espn:13071042: Downloading webpage
[ESPN] 13071042: Downloading webpage
[OoyalaExternal] 13071042: Downloading webpage
[OoyalaExternal] 13071042: Downloading mobile player JS for unknown device
[OoyalaExternal] txazBudToCi8Uitqs-U2YT3x87cl91ax: Downloading m3u8 information
[debug] Invoking downloader on u'http://media.video-cdn.espn.com/motion/2015/061
3/dm_150613_COM_MISC_Must_See_Shok_the_fox_gets_smoked_2015_06_13_ESHEET/hls/804
_3049574_HBR.m3u8'
[download] Destination: AFL One-Play (Shox the fox gets smoked) 2015_06_13 ESHEE
T-txazBudToCi8Uitqs-U2YT3x87cl91ax.mp4
ffmpeg version N-71346-gdf4fca2 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-l
ibilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enab
le-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --en
able-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --ena
ble-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc
 --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enabl
e-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --ena
ble-decklink --enable-zlib
  libavutil      54. 22.101 / 54. 22.101
  libavcodec     56. 34.100 / 56. 34.100
  libavformat    56. 30.100 / 56. 30.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 13.101 /  5. 13.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, hls,applehttp, from 'http://media.video-cdn.espn.com/motion/2015/0613/
dm_150613_COM_MISC_Must_See_Shok_the_fox_gets_smoked_2015_06_13_ESHEET/hls/804_3
049574_HBR.m3u8':
  Duration: 00:00:47.11, start: 2.064000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720
[SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, flt
p, 131 kb/s
[mp4 @ 000000000614cc60] Codec for stream 0 does not use global headers but cont
ainer format requires global headers
[mp4 @ 000000000614cc60] Codec for stream 1 does not use global headers but cont
ainer format requires global headers
Output #0, mp4, to 'AFL One-Play (Shox the fox gets smoked) 2015_06_13 ESHEET-tx
azBudToCi8Uitqs-U2YT3x87cl91ax.mp4.part':
  Metadata:
    encoder         : Lavf56.30.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720 [SAR 1:
1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 131 kb/s

Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   74 fps=0.0 q=-1.0 size=    1824kB time=00:00:02.73 bitrate=5471.9kbits/
frame=  140 fps=138 q=-1.0 size=    3004kB time=00:00:04.77 bitrate=5150.1kbits/
frame=  180 fps= 87 q=-1.0 size=    3700kB time=00:00:06.03 bitrate=5019.9kbits/
frame=  223 fps= 87 q=-1.0 size=    4453kB time=00:00:07.74 bitrate=4710.4kbits/
frame=  280 fps= 91 q=-1.0 size=    5441kB time=00:00:09.45 bitrate=4716.0kbits/
frame=  329 fps= 92 q=-1.0 size=    6437kB time=00:00:11.15 bitrate=4726.1kbits/
frame=  360 fps=1.0 q=-1.0 size=    7055kB time=00:00:12.05 bitrate=4795.2kbits/
frame=  394 fps=1.1 q=-1.0 size=    7799kB time=00:00:13.41 bitrate=4761.4kbits/
frame=  432 fps=1.2 q=-1.0 size=    8513kB time=00:00:14.48 bitrate=4814.6kbits/
frame=  458 fps=0.9 q=-1.0 size=    9046kB time=00:00:15.46 bitrate=4791.3kbits/
frame=  502 fps=1.0 q=-1.0 size=    9782kB time=00:00:16.83 bitrate=4760.9kbits/
frame=  540 fps=1.1 q=-1.0 size=   10430kB time=00:00:18.04 bitrate=4734.2kbits/
frame=  571 fps=1.2 q=-1.0 size=   11047kB time=00:00:19.09 bitrate=4739.9kbits/
frame=  591 fps=1.2 q=-1.0 size=   11490kB time=00:00:19.75 bitrate=4764.9kbits/
frame=  622 fps=1.3 q=-1.0 size=   12082kB time=00:00:20.77 bitrate=4763.1kbits/
frame=  659 fps=1.3 q=-1.0 size=   12754kB time=00:00:22.14 bitrate=4718.1kbits/
frame=  707 fps=1.4 q=-1.0 size=   13553kB time=00:00:23.85 bitrate=4655.1kbits/
frame=  720 fps=0.8 q=-1.0 size=   13775kB time=00:00:24.06 bitrate=4689.3kbits/
frame=  750 fps=0.9 q=-1.0 size=   14340kB time=00:00:25.10 bitrate=4678.3kbits/
frame=  789 fps=0.9 q=-1.0 size=   15097kB time=00:00:26.45 bitrate=4675.1kbits/
frame=  822 fps=1.0 q=-1.0 size=   15769kB time=00:00:27.47 bitrate=4701.2kbits/
frame=  900 fps=1.1 q=-1.0 size=   17158kB time=00:00:30.05 bitrate=4676.2kbits/
frame=  927 fps=1.1 q=-1.0 size=   17751kB time=00:00:31.08 bitrate=4678.3kbits/
frame=  998 fps=1.2 q=-1.0 size=   19111kB time=00:00:33.47 bitrate=4677.3kbits/
frame= 1078 fps=1.3 q=-1.0 size=   20461kB time=00:00:36.07 bitrate=4646.4kbits/
frame= 1104 fps=1.3 q=-1.0 size=   20946kB time=00:00:37.09 bitrate=4625.2kbits/
frame= 1158 fps=1.4 q=-1.0 size=   21920kB time=00:00:38.80 bitrate=4627.4kbits/
frame= 1187 fps=1.4 q=-1.0 size=   22497kB time=00:00:39.82 bitrate=4627.0kbits/
frame= 1243 fps=1.5 q=-1.0 size=   23495kB time=00:00:41.53 bitrate=4633.8kbits/
frame= 1260 fps=1.5 q=-1.0 size=   23816kB time=00:00:42.06 bitrate=4637.7kbits/
frame= 1293 fps=1.5 q=-1.0 size=   24512kB time=00:00:43.43 bitrate=4623.1kbits/
frame= 1331 fps=1.6 q=-1.0 size=   25210kB time=00:00:44.45 bitrate=4645.2kbits/
frame= 1372 fps=1.6 q=-1.0 size=   26002kB time=00:00:45.86 bitrate=4644.1kbits/
frame= 1412 fps=1.6 q=-1.0 Lsize=   26752kB time=00:00:47.12 bitrate=4650.4kbits
/s
video:25982kB audio:721kB subtitle:0kB other streams:0kB global headers:0kB muxi
ng overhead: 0.181252%
[ffmpeg] 27393751 bytes
[download] 100% of 26.12MiB

**Comment by dstftw** [comment]
Works fine with latest version.
