### ISSUE TITLE
Site-support request: r7.com (F4F format)

### ISSUE THREAD

**Issue by DanielFragaBR** [rg3/youtube-dl#4405]
I'd like to suggest you to support download from r7.com:

http://noticias.r7.com/record-news/video/representante-do-instituto-sou-da-paz-fala-sobre-fim-do-estatuto-do-desarmamento-5480fc580cf2285b117f438d/

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://noticias.r7.com/record-news/video/representante-do-instituto-sou-da-paz-fala-sobre-fim-do-estatuto-do-desarmamento-5480fc580cf2285b117f438d/', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.06.1
[debug] Python version 2.7.8 - Linux-3.18.0-rc7-x86_64-with-debian
[debug] exe versions: avconv present, avprobe present, ffmpeg N-65777-, ffprobe N-65777-
[debug] Proxy map: {}
[generic] representante-do-instituto-sou-da-paz-fala-sobre-fim-do-estatuto-do-desarmamento-5480fc580cf2285b117f438d: Requesting header
WARNING: Falling back on generic information extractor.
[generic] representante-do-instituto-sou-da-paz-fala-sobre-fim-do-estatuto-do-desarmamento-5480fc580cf2285b117f438d: Downloading webpage
[generic] representante-do-instituto-sou-da-paz-fala-sobre-fim-do-estatuto-do-desarmamento-5480fc580cf2285b117f438d: Extracting information
ERROR: Unsupported URL: http://noticias.r7.com/record-news/video/representante-do-instituto-sou-da-paz-fala-sobre-fim-do-estatuto-do-desarmamento-5480fc580cf2285b117f438d/; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks!

**Comment by yavute** [comment]
I do not understand how you can download

**Comment by DanielFragaBR** [comment]
I will explain better:

1) http://vod.streaming.r7.com/z/5480fc580cf2285b117f438d/ER7_RN_JRN_ENTREVISTA_3_570kbps_2014-12-043f4eabdb-0a09-4692-a4a3-f343e8eac402-ATOS_copy.mp4/0_99d5d2de5725874a_Seg1-Frag8

2) on Firefox (for example) open Tools -> Web Developer -> Network to access the links from the fragment.

3) the links are of the column type "f4f" (Adobe HDS format) like these:

http://vod.streaming.r7.com/z/5480fc580cf2285b117f438d/ER7_RN_JRN_ENTREVISTA_3_570kbps_2014-12-043f4eabdb-0a09-4692-a4a3-f343e8eac402-ATOS_copy.mp4/manifest.f4m?hdcore=3.1.0

http://vod.streaming.r7.com/z/5480fc580cf2285b117f438d/ER7_RN_JRN_ENTREVISTA_3_570kbps_2014-12-043f4eabdb-0a09-4692-a4a3-f343e8eac402-ATOS_copy.mp4/0_99d5d2de5725874a_Seg1-Frag1

http://vod.streaming.r7.com/z/5480fc580cf2285b117f438d/ER7_RN_JRN_ENTREVISTA_3_570kbps_2014-12-043f4eabdb-0a09-4692-a4a3-f343e8eac402-ATOS_copy.mp4/0_99d5d2de5725874a_Seg1-Frag2

and so on...

After you download all fragments, just join all of them with:

php ../AdobeHDS.php --fragments 0_99d5d2de5725874a_Seg1-Frag

**Comment by dstftw** [comment]
R7 will be supported in the next version. Thanks for the report.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl version 2015.02.24 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
