### ISSUE TITLE
Embedded video clip NHK...html download fails - site support requesting

### ISSUE THREAD

**Issue by eufft-z** [rg3/youtube-dl#4437]
These are the results when trying to download the site with option verbose:
======================================
euffth@cd368ubu1404:~$ youtube-dl www.nhk.or.jp/news/html/20141210/k10013872831000.html --verbose[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['www.nhk.or.jp/news/html/20141210/k10013872831000.html', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.10.3
[debug] Python version 2.7.6 - Linux-3.13.0-40-generic-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[generic] k10013872831000: Requesting header
[redirect] Following redirect to http://www3.nhk.or.jp/news/html/20141210/k10013872831000.html
[generic] k10013872831000: Requesting header
WARNING: Falling back on generic information extractor.
[generic] k10013872831000: Downloading webpage
[generic] k10013872831000: Extracting information
ERROR: Unsupported URL: http://www3.nhk.or.jp/news/html/20141210/k10013872831000.html; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 554, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 242, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1044, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www3.nhk.or.jp/news/html/20141210/k10013872831000.html; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
:~$ 

Comment: This is the case with any of the news video clips from NHK.
Has anyone been able to download from that site?

**Comment by 133794m3r** [comment]
this site is just using ooyla so i don't know why it's not working already maybe it needs to be tagged as such? but they're cleary just using the standard ooyla player on their site.

**Comment by 133794m3r** [comment]
this site is just using ooyla so i don't know why it's not working already maybe it needs to be tagged as such? but they're cleary just using the standard ooyla player on their site.

**Comment by 133794m3r** [comment]
this site is just using ooyla so i don't know why it's not working already maybe it needs to be tagged as such? but they're cleary just using the standard ooyla player on their site.

**Comment by 133794m3r** [comment]
this site is just using ooyla so i don't know why it's not working already maybe it needs to be tagged as such? but they're cleary just using the standard ooyla player on their site.

**Comment by 133794m3r** [comment]
this site is just using ooyla so i don't know why it's not working already maybe it needs to be tagged as such? but they're cleary just using the standard ooyla player on their site.

**Comment by 133794m3r** [comment]
this site is just using ooyla so i don't know why it's not working already maybe it needs to be tagged as such? but they're cleary just using the standard ooyla player on their site.

**Comment by 133794m3r** [comment]
this site is just using ooyla so i don't know why it's not working already maybe it needs to be tagged as such? but they're cleary just using the standard ooyla player on their site.

**Comment by 133794m3r** [comment]
this site is just using ooyla so i don't know why it's not working already maybe it needs to be tagged as such? but they're cleary just using the standard ooyla player on their site.

**Comment by 133794m3r** [comment]
this site is just using ooyla so i don't know why it's not working already maybe it needs to be tagged as such? but they're cleary just using the standard ooyla player on their site.

**Comment by 133794m3r** [comment]
this site is just using ooyla so i don't know why it's not working already maybe it needs to be tagged as such? but they're cleary just using the standard ooyla player on their site.

**Comment by cardshuffler** [comment]
this is something i'd like to see added as well.

here is a more recent link from their vod section:

youtube-dl http://www3.nhk.or.jp/nhkworld/en/vod/japanrailway/20160520.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www3.nhk.or.jp/nhkworld/en/vod/japanrailway/20160520.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.11+ - Linux-4.4.0-23-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[generic] 20160520: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 20160520: Downloading webpage
[generic] 20160520: Extracting information
ERROR: Unsupported URL: http://www3.nhk.or.jp/nhkworld/en/vod/japanrailway/20160520.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1413, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 280, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 269, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 41, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2105, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www3.nhk.or.jp/nhkworld/en/vod/japanrailway/20160520.html

**Comment by Xender** [comment]
I've implemented it. #10424 :)
