### ISSUE TITLE
avconv

### ISSUE THREAD

**Issue by eone1000** [rg3/youtube-dl#4451]
$ youtube-dl --version
2014.12.12.1

$ uname -a
Linux rpipro 3.12.28+ #709 PREEMPT Mon Sep 8 15:28:00 BST 2014 armv6l GNU/Linux

$ youtube-dl -x --audio-format mp3 --audio-quality 0 https://www.youtube.com/watch?v=vWz9VN40nCA&list=RDHC1yXpM9Oi66A

[youtube] vWz9VN40nCA: Extracting video information
[youtube] vWz9VN40nCA: Downloading DASH manifest
[download] Destination: Olivia Newton-John - Physical-vWz9VN40nCA.m4a
[download] 100% of 6.80MiB in 00:02
[avconv] Destination: Olivia Newton-John - Physical-vWz9VN40nCA.mp3
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.

How to fix the warning about "avconv is outdated"?

I tried the following but failed:
$ sudo apt-get install libav-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libav-tools is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.

Thanks in advance.

**Comment by ekremkaraca** [comment]
I also get the warning on Ubuntu Trusty, even using `mc3man`s repo in active. Using `--prefer-avconv` each time is gonna make me bored & tired. Could we add this option in a file like `.youtube-dlrc`?

**Comment by yan12125** [comment]
@ekremkaraca I think https://github.com/rg3/youtube-dl#configuration is helpful.

**Comment by ekremkaraca** [comment]
Oops, seems I've missed this one, thanks so much @yan12125!

**Comment by rodrigoreis22** [comment]
Why is youtube-dl downloading 2 files for this video.. and it seems that the final mp4 file is just audio.

When I run locally on my MacOS, this doesn't happen. When it's running on the server (iron.io) I see this problem.

[youtube] QC2kYBm2zMU: Downloading webpage
[youtube] QC2kYBm2zMU: Extracting video information
[youtube] QC2kYBm2zMU: Downloading DASH manifest
[download] Destination: QC2kYBm2zMU.f137.mp4

[download]   0.0% of 103.52MiB at 389.70KiB/s ETA 04:37
[download]   0.0% of 103.52MiB at  1.03MiB/s ETA 01:40
[download]   0.0% of 103.52MiB at  2.23MiB/s ETA 00:46
[download]   0.0% of 103.52MiB at  4.24MiB/s ETA 00:24
[download]   0.0% of 103.52MiB at  8.00MiB/s ETA 00:12
[download]   0.1% of 103.52MiB at  4.40MiB/s ETA 00:23
[download]   0.1% of 103.52MiB at  4.84MiB/s ETA 00:21
[download]   0.2% of 103.52MiB at  6.95MiB/s ETA 00:14
[download]   0.5% of 103.52MiB at 10.51MiB/s ETA 00:09
[download]   1.0% of 103.52MiB at 15.94MiB/s ETA 00:06
[download]   1.9% of 103.52MiB at 18.94MiB/s ETA 00:05
[download]   3.9% of 103.52MiB at 26.18MiB/s ETA 00:03
[download]   7.7% of 103.52MiB at 27.16MiB/s ETA 00:03
[download]  11.6% of 103.52MiB at 12.93MiB/s ETA 00:07
[download]  15.5% of 103.52MiB at 14.02MiB/s ETA 00:06
[download]  19.3% of 103.52MiB at 10.38MiB/s ETA 00:08
[download]  23.2% of 103.52MiB at 11.44MiB/s ETA 00:06
[download]  27.0% of 103.52MiB at 12.78MiB/s ETA 00:05
[download]  30.9% of 103.52MiB at 10.67MiB/s ETA 00:06
[download]  34.8% of 103.52MiB at 11.47MiB/s ETA 00:05
[download]  38.6% of 103.52MiB at 10.99MiB/s ETA 00:05
[download]  42.5% of 103.52MiB at 11.13MiB/s ETA 00:05
[download]  46.4% of 103.52MiB at 11.59MiB/s ETA 00:04
[download]  50.2% of 103.52MiB at  9.51MiB/s ETA 00:05
[download]  53.1% of 103.52MiB at  9.99MiB/s ETA 00:04
[download]  57.0% of 103.52MiB at 10.55MiB/s ETA 00:04
[download]  60.9% of 103.52MiB at  9.97MiB/s ETA 00:04
[download]  64.7% of 103.52MiB at 10.21MiB/s ETA 00:03
[download]  68.6% of 103.52MiB at  9.99MiB/s ETA 00:03
[download]  72.5% of 103.52MiB at  9.37MiB/s ETA 00:03
[download]  76.3% of 103.52MiB at  9.75MiB/s ETA 00:02
[download]  80.2% of 103.52MiB at  9.66MiB/s ETA 00:02
[download]  84.1% of 103.52MiB at  9.02MiB/s ETA 00:01
[download]  87.8% of 103.52MiB at  9.35MiB/s ETA 00:01
[download]  91.6% of 103.52MiB at  9.65MiB/s ETA 00:00
[download]  95.5% of 103.52MiB at  9.64MiB/s ETA 00:00
[download]  99.3% of 103.52MiB at  9.76MiB/s ETA 00:00
[download] 100.0% of 103.52MiB at  9.81MiB/s ETA 00:00
[download] 100% of 103.52MiB in 00:10
[download] Destination: QC2kYBm2zMU.f141.m4a
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.

[download]   0.0% of 8.09MiB at 753.02KiB/s ETA 00:11
[download]   0.0% of 8.09MiB at  1.87MiB/s ETA 00:04
[download]   0.1% of 8.09MiB at  3.49MiB/s ETA 00:02
[download]   0.2% of 8.09MiB at  6.24MiB/s ETA 00:01
[download]   0.4% of 8.09MiB at 11.17MiB/s ETA 00:00
[download]   0.8% of 8.09MiB at  4.42MiB/s ETA 00:01
[download]   1.5% of 8.09MiB at  4.91MiB/s ETA 00:01
[download]   3.1% of 8.09MiB at  6.89MiB/s ETA 00:01
[download]   6.2% of 8.09MiB at  9.95MiB/s ETA 00:00
[download]  12.4% of 8.09MiB at 14.92MiB/s ETA 00:00
[download]  24.7% of 8.09MiB at 21.62MiB/s ETA 00:00
[download]  49.4% of 8.09MiB at 35.50MiB/s ETA 00:00
[download]  98.9% of 8.09MiB at  3.35MiB/s ETA 00:00
[download] 100.0% of 8.09MiB at  3.39MiB/s ETA 00:00
[download] 100% of 8.09MiB in 00:02
[ffmpeg] Merging formats into "QC2kYBm2zMU.mp4"
Deleting original file QC2kYBm2zMU.f137.mp4 (pass -k to keep)
Deleting original file QC2kYBm2zMU.f141.m4a (pass -k to keep)

**Comment by jaimeMF** [comment]
Open a [new issue with the output you get with the --verbose option](https://github.com/rg3/youtube-dl/blob/40b96352c99953aec9272574729077c06c235747/README.md#bugs), you should also read the [last paragraph of the format selection docs](https://github.com/rg3/youtube-dl/blob/40b96352c99953aec9272574729077c06c235747/README.md#format-selection).

**Comment by eMPee584** [comment]
The warning also comes up when using the `avconv` provided by ffmpeg:

```
ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
built with gcc 4.9.3 (Debian 4.9.3-3)
configuration: --prefix=/usr --extra-cflags='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security ' --extra-ldflags='-Wl,-z,relro' --cc='ccache cc' --enable-shared --enable-libmp3lame --enable-gpl --enable-nonfree --enable-libvorbis --enable-pthreads --enable-libfaac --enable-libxvid --enable-postproc --enable-x11grab --enable-libgsm --enable-libtheora --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libx264 --enable-libspeex --enable-nonfree --disable-stripping --enable-libvpx --enable-libschroedinger --disable-encoder=libschroedinger --enable-version3 --enable-libopenjpeg --enable-librtmp --enable-avfilter --enable-libfreetype --enable-libvo-aacenc --disable-decoder=amrnb --enable-libvo-amrwbenc --enable-libaacplus --libdir=/usr/lib/i386-linux-gnu --disable-vda --enable-libbluray --enable-libcdio --enable-gnutls --enable-frei0r --enable-openssl --enable-libass --enable-libopus --enable-fontconfig --enable-libpulse --disable-mips32r2 --disable-mipsdspr1 --disable-mipsdspr2 --enable-libvidstab --enable-libzvbi --enable-avresample --disable-htmlpages --disable-podpages --enable-libutvideo --enable-libfdk-aac --enable-libx265 --enable-libiec61883 --enable-vaapi --enable-libdc1394 --disable-altivec --shlibdir=/usr/lib/i386-linux-gnu
libavutil      54. 27.100 / 54. 27.100
libavcodec     56. 41.100 / 56. 41.100
libavformat    56. 36.100 / 56. 36.100
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 16.101 /  5. 16.101
libavresample   2.  1.  0 /  2.  1.  0
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.100 /  1.  2.100
libpostproc    53.  3.100 / 53.  3.100
```

**Comment by sirmacik** [comment]
Applying any of listed below solutions didn't  fix the warning. Is it outdated package in debian testing or there is some kind of a bug on the script side?

**Comment by shankar-ray** [comment]
I'm not sure how much of help it would be, but this solved the issue in my computer, http://askubuntu.com/questions/563245/avconv-warning-while-downloading-youtube-video
