### ISSUE TITLE
Please update support for canalplus.fr

### ISSUE THREAD

**Issue by andreas--e** [rg3/youtube-dl#4472]
This is no "add-support" request, since you already *do* have support for canalplus.fr.

Unfortunately something was changed through the last months:

user@my-lubuntubox:~/tmp# echo && cat debug.log 

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.canalplus.fr/c-sport/c-football/premier-league/pid6765-videos.html?vid=1183334']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2014.12.15
[debug] Python version 2.7.8 - Linux-3.16.0-23-generic-i686-athlon-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6
[debug] Proxy map: {}
[Canalplus] pid6765-videos.html: Downloading webpage
[Canalplus] 1183334: Downloading video XML
[Canalplus] 1183334: Downloading f4m manifest
ERROR: Unable to download f4m manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "./ytdl.py/youtube_dl/extractor/common.py", line 276, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./ytdl.py/youtube_dl/YoutubeDL.py", line 1370, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

This happens with latest build.

Oh, besides, I checked first, and found this is NOT a duplicate: the other user's error message was
ERROR: unable to download video data: HTTP Error 403: Forbidden

while mine is about f4m **manifest** file, thus a little more specific. (Unless merely the _error message_ has been made more specific meanwhile ;))

**Comment by jaimeMF** [comment]
In the next version it will give a proper error message, thanks for the report.

**Comment by andreas--e** [comment]
Thank you very much!
