### ISSUE TITLE
NHL / rtmpdump failure...

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#4481]
URL: http://video.oilers.nhl.com/videocenter/console?id=691469&catid=4

>YOUTUBE-DL.PY -v "http://video.oilers.nhl.com/videocenter/console?id=691469&catid=4"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://video.oilers.nhl.com/videocenter/console?id=691469&catid=4']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.12.15
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20, rtmpdump 2.4
[debug] Proxy map: {}
[nhl.com] 691469: Downloading JSON metadata
[nhl.com] 691469: Extracting information
[nhl.com] 691469: Downloading final video url
[debug] Invoking downloader on 'rtmp://cdncon.fcod.llnwd.net/a277/e4/mp4:u/oilers/vod/flv/2014/12/05/691469_20141205_mact_sd.mp4?eid=690930&pid=691469&gid=3012&pt=1?eid=690930&pid=691469&gid=3012&pt=1
&ip=199.85.73.12&e=1418665714&h=0f1760e7abaa19d654c0d2c670f996b3'
[download] Destination: RAW _ Craig MacTavish Full Press Conference-691469.mp4
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmp://cdncon.fcod.llnwd.net/a277/e4/mp4:u/oilers/vod/flv/2014/12/05/691469_20141205_mact_sd.mp4?eid=690930&pid=691469&gid=3012&pt=1?eid=690930&pi
d=691469&gid=3012&pt=1&ip=199.85.73.12&e=1418665714&h=0f1760e7abaa19d654c0d2c670f996b3' -o 'RAW _ Craig MacTavish Full Press Conference-691469.mp4.part' --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : cdncon.fcod.llnwd.net
[rtmpdump] DEBUG: Parsed app     : a277/e4/mp4:u
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : cdncon.fcod.llnwd.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:oilers/vod/flv/2014/12/05/691469_20141205_mact_sd?eid=690930&pid=691469&gid=3012&pt=1?eid=690930&pid=691469&gid=3012&pt=1&ip=199.85.73.12&e=1418665714&h=0f1760e7abaa19
d654c0d2c670f996b3
[rtmpdump] DEBUG: tcUrl    : rtmp://cdncon.fcod.llnwd.net:1935/a277/e4/mp4:u
[rtmpdump] DEBUG: app      : a277/e4/mp4:u
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Type Answer   : 03
[rtmpdump] DEBUG: HandShake: Server Uptime : 1581952825
[rtmpdump] DEBUG: HandShake: FMS Version   : 4.0.3.1
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 2500000
[rtmpdump] DEBUG: HandleClientBW: client BW = 2500000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 242 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:  FMS/4,0,3,4044>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:  255.00>
[rtmpdump] DEBUG: Property: <Name:               mode, NUMBER:  1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetConnection.Connect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Connection succeeded.>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:  0.00>
[rtmpdump] DEBUG: Property: <Name:               data, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            version, STRING:  4,0,3,4044>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 21 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWDone>
[rtmpdump] DEBUG: Invoking _checkbw
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: mp4:oilers/vod/flv/2014/12/05/691469_20141205_mact_sd?eid=690930&pid=691469&gid=3012&pt=1?eid=690930&pid=691469&gid=3012&pt=1&ip=199.8
5.73.12&e=1418665714&h=0f1760e7abaa19d654c0d2c670f996b3
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 16419 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 32803 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 259 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  error>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetStream.Play.StreamNotFound>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Failed to play oilers/vod/flv/2014/12/05/691469_20141205_mact_sd; stream not found.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:  oilers/vod/flv/2014/12/05/691469_20141205_mact_sd>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:  pAAlEpGA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.StreamNotFound
[rtmpdump] ERROR: Closing connection: NetStream.Play.StreamNotFound
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : cdncon.fcod.llnwd.net
[rtmpdump] DEBUG: Parsed app     : a277/e4/mp4:u
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : cdncon.fcod.llnwd.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:oilers/vod/flv/2014/12/05/691469_20141205_mact_sd?eid=690930&pid=691469&gid=3012&pt=1?eid=690930&pid=691469&gid=3012&pt=1&ip=199.85.73.12&e=1418665714&h=0f1760e7abaa19
d654c0d2c670f996b3
[rtmpdump] DEBUG: tcUrl    : rtmp://cdncon.fcod.llnwd.net:1935/a277/e4/mp4:u
[rtmpdump] DEBUG: app      : a277/e4/mp4:u
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Transmogrifier\youtube-dl.py\__main__.py", line 19, in <module>
    youtube_dl.main()
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 361, in main
    _real_main(argv)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 351, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1166, in download
    res = self.extract_info(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 603, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 649, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 938, in process_video_result
    self.process_info(new_info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1136, in process_info
    success = dl(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1112, in dl
    return fd.download(name, info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\common.py", line 297, in download
    return self.real_download(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\rtmp.py", line 206, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\common.py", line 149, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 478, in report_error
    self.trouble(error_message, tb)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 440, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

As always...THANK YOU!
Ringo

**Comment by yan12125** [comment]
Thanks for the report. Such videos will be downloaded correctly in the next version.
