### ISSUE TITLE
XTube WARNING: unable to extract uploader

### ISSUE THREAD

**Issue by kokayi** [rg3/youtube-dl#4489]
[gje@bolekaja ~/Videos/xtube]$ yt --verbose http://www.xtube.com/watch.php?v=5PZLF-S667-#.VJBGUc3d8WM
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.xtube.com/watch.php?v=5PZLF-S667-#.VJBGUc3d8WM']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.12.1
[debug] Python version 2.7.8 - Linux-3.16.6-2-desktop-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg 2.3.3, ffprobe 2.3.3
[debug] Proxy map: {}
[XTube] 5PZLF-S667-#.VJBGUc3d8WM: Downloading webpage
WARNING: unable to extract uploader; please report this issue on http://yt-dl.org/bug
ERROR: Unable to extract player quality option; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 554, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 243, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/xtube.py", line 56, in _real_extract
    r'playerQualityOption = ({.+?});', webpage, 'player quality option'))
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 495, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 485, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player quality option; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.05 or newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
