### ISSUE TITLE
clipfish.de f4m videos not playable

### ISSUE THREAD

**Issue by erik-31** [rg3/youtube-dl#4492]
youtube-dl -vv --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20130401 Firefox/31.0" http://www.clipfish.de/special/kino-trailer/video/3988022/die-schluempfe-2-filmausschnitt-schaumbad/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vv', '--user-agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20130401 Firefox/31.0', 'http://www.clipfish.de/special/kino-trailer/video/3988022/die-schluempfe-2-filmausschnitt-schaumbad/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.14
[debug] Python version 2.7.6 - Linux-3.13.0-43-generic-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[clipfish] 3988022: Downloading info page
[debug] Invoking downloader on 'http://hds.fra.clipfish.de/hds-vod-enc/media/c4/bb4d9f0899b8694bc5ed3a6e9afaadc4.mp4.f4m'
[download] Downloading f4m manifest
[download] Destination: Die Schlümpfe 2 - Filmausschnitt - Schaumbad-3988022.f4m
[download] 100% of 6.18MiB in 00:15

Not playable in mplayer and vlc:

vlc Die\ Schlümpfe\ 2\ -\ Filmausschnitt\ -\ Schaumbad-3988022.f4m 
VLC media player 2.1.4 Rincewind (revision 2.1.4-0-g2a072be)
[flv @ 0xb0113360] Could not find codec parameters (Video: h264)
[flv @ 0xb0113360] Could not find codec parameters (Audio: aac, 48000 Hz, 2 channels)
[flv @ 0xa9068620] Could not find codec parameters (Video: h264)
[flv @ 0xa9068620] Could not find codec parameters (Audio: aac, 48000 Hz, 2 channels)
[0xa900b4b0] avformat demux error: Unknown option "threads"
[flv @ 0xa90aec40] Could not find codec parameters (Video: h264)
[flv @ 0xa90aec40] Could not find codec parameters (Audio: aac, 48000 Hz, 2 channels)
[0xa90d0940] avformat demux error: Unknown option "threads"

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version. Thanks for the report.

**Comment by everythinggoingwell** [comment]
I use Allavsoft to directly download video from Clipfish to MP4, AVI, WMV, MOV, or TS with this guide http://www.allavsoft.com/how-to/clipfish-video-download.html
I like its fast downloading speed and batch download feature﻿
