### ISSUE TITLE
NBC caption/subtitle

### ISSUE THREAD

**Issue by superxuxin** [rg3/youtube-dl#4495]
It would be great if we can get the caption of videos like this:

http://www.nbc.com/the-tonight-show/episodes/179

**Comment by phihag** [comment]
Reopening.

**Comment by yan12125** [comment]
I've implemented TTML support in bf6427d2fbcbd95cd1cb640e8b894c18782a2a12. However, the link you provide does not contain a valid video anymore, so I can't test it. If you encounter problems in converting TTML subtitles into other formats, feel free to open a new issue.
