### ISSUE TITLE
[vk.com] Can't download embedded rutube videos

### ISSUE THREAD

**Issue by qyuz** [rg3/youtube-dl#4514]
[debug] Command-line args: ['http://vk.com/video-57839910_167080183', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.3 - Linux-3.12.28+-armv6l-with-debian-7.6
[debug] exe versions: avconv 9.14-6, avprobe 9.14-6, ffmpeg 0.8.13-6, rtmpdump 2.4
[debug] Proxy map: {}
[vk.com] -57839910_167080183: Downloading webpage
ERROR: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 592, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 243, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/vk.py", line 176, in _real_extract
    data_json = self._search_regex(r'var vars = ({.*?});', info_page, 'vars')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 489, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.04. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by anisse** [comment]
This broke most tests on the vk extractor.

**Comment by anisse** [comment]
In hindsight, I think it only broke three out of seven tests.

**Comment by jaimeMF** [comment]
@anisse they should work again now.

**Comment by anisse** [comment]
Confirmed. Thanks a lot!
