### ISSUE TITLE
problem with discovery channel

### ISSUE THREAD

**Issue by mghadam** [rg3/youtube-dl#4535]
Hello,

I couldn't use youtube-dl to download from discovery channel. Here's the output:

[user@svsv ~]# youtube-dl http://www.discovery.com/tv-shows/mythbusters/videos/anti-gravity-device/ --verbose

[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['http://www.discovery.com/tv-shows/mythbusters/videos/anti-gravity-device/', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.6.6 - Linux-2.6.32-431.29.2.el6.x86_64-x86_64-with-centos-6.6-Final
[debug] exe versions: ffmpeg N-67200-gc0002dd, ffprobe N-67200-gc0002dd, rtmpdump 2.3
[debug] Proxy map: {}
[Discovery] anti-gravity-device: Downloading webpage
ERROR: Unable to extract video list; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 592, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 243, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/discovery.py", line 32, in _real_extract
    webpage, 'video list', flags=re.DOTALL)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 489, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video list; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
Discovery videos should be fixed now (9298d4e3df4b6237f4f9e4f37b9e55775c5e3c0c), thanks for the report!
But the video you linked gives you the message `Sorry, this page does not exist`, so they may have removed it.
