### ISSUE TITLE
Unsupported URL: tv.adobe.com

### ISSUE THREAD

**Issue by kendalls63** [rg3/youtube-dl#4536]
youtube-dl --version
2014.12.17.2
Hope I'm in the right spot to post this, and, can you manually add url's to the windows version?
verbose output:
E:\Vidcon\CLI>youtube-dl --verbose http://tv.adobe.com/watch/the-complete-picture-with-julieanne-kost/quick-tip-how-to-draw-a-circle-around-an-object-in-photoshop/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://tv.adobe.com/watch/the-complete-picture-with-julieanne-kost/quick-tip-how-to-draw-a-circle-around-an-object-in-photoshop/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: rtmpdump 2.3
[debug] Proxy map: {}
[generic] quick-tip-how-to-draw-a-circle-around-an-object-in-photoshop: Requesting header
WARNING: Falling back on generic information extractor.
[generic] quick-tip-how-to-draw-a-circle-around-an-object-in-photoshop: Downloading webpage
[generic] quick-tip-how-to-draw-a-circle-around-an-object-in-photoshop: Extracting information
ERROR: Unsupported URL: http://tv.adobe.com/watch/the-complete-picture-with-julieanne-kost/quick-tip-how-to-draw-a-circle-around-an-object-in-photoshop/; 
please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. 
Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 660, in _real_extract
  File "youtube_dl\utils.pyo", line 1444, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 50, column 105
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 592, in extract_info
  File "youtube_dl\extractor\common.pyo", line 243, in extract
  File "youtube_dl\extractor\generic.pyo", line 1060, in _real_extract
ExtractorError: Unsupported URL: http://tv.adobe.com/watch/the-complete-picture-with-julieanne-kost/quick-tip-how-to-draw-a-circle-around-an-object-in-photoshop/; 
please report this issue on https://yt-dl.org/bug. 
Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.05 or newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
