### ISSUE TITLE
Support for Radio Bremen/Buten un Binnen

### ISSUE THREAD

**Issue by lightonflux** [rg3/youtube-dl#4546]
Example Link:

http://www.radiobremen.de/mediathek/index.html?id=114720

**Comment by jaimeMF** [comment]
@ckrooss added support in #4632, it will work in the next version.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.05 or newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
