### ISSUE TITLE
--restrict-filenames problem/suggestion

### ISSUE THREAD

**Issue by active8** [rg3/youtube-dl#4549]
--restrict-filenames Restrict filenames to only ASCII
                                     characters, and avoid "&" and spaces in
                                     filenames
I always considered parentheses to be ascii printable characters. I used this option to eliminate spaces and it replaced the parenthesis which is not desireable.

/usr/local/youtube-dl/youtube-dl --restrict-filenames -o %(title)s-%(format)s.%(ext)s https://www.youtube.com/watch?v=uA6nVRTbzko

The only problem i might ever have with parenthesis n filenames is the need to be escaped on the bash command line. Maybe you can enlighten me as to why they should get replaced.

**Comment by yan12125** [comment]
There's a similar issue #5042. Please move on there for further discussions.
