### ISSUE TITLE
Is it possible to get the url of m3u8 file?

### ISSUE THREAD

**Issue by zhengxiexie** [rg3/youtube-dl#4557]
I use **Charles** to get the **m3u8 url** of [this video](http://v.youku.com/v_show/id_XODAyNjI3OTMy.html)
The url of m3u8 file is the [link](http://pl.youku.com/playlist/m3u8?ts=1419421633&keyframe=1&vid=XODAyNjI3OTMy&type=mp4&sid=241942163331621c70af6&token=9469&oip=1967716914&ep=V1jajZX5Em1ilvIfmAIP6CJ9EoVK3agY8FWgcCqOqOrJTTfV1Mlf9aBhwLRA8q77&did=b6c17bc7f1531da079633863ce82c0034c32094d&ctype=21&ev=1)

Can youtube-dl get this url? If not, are there any solutions?

**Comment by yan12125** [comment]
Not sure what you want. If you are trying to download http://v.youku.com/v_show/id_XODAyNjI3OTMy.html via youtube-dl, it will supported in the next version (thanks to @PeterDing in #5833). If you are trying to download video files via the m3u8 manifest, for example:
```
youtube-dl "http://pl.youku.com/playlist/m3u8?ts=1419421633&keyframe=1&vid=XODAyNjI3OTMy&type=mp4&sid=241942163331621c70af6&token=9469&oip=1967716914&ep=V1jajZX5Em1ilvIfmAIP6CJ9EoVK3agY8FWgcCqOqOrJTTfV1Mlf9aBhwLRA8q77&did=b6c17bc7f1531da079633863ce82c0034c32094d&ctype=21&ev=1"
```
It's a feature request.

**Comment by yan12125** [comment]
This will be supported in the next version:
```
$ youtube-dl -g "http://v.youku.com/v_show/id_XODAyNjI3OTMy.html"
http://pl-ali.youku.com/playlist/m3u8?vid=XODAyNjI3OTMy&type=hd3&ups_client_netip=140.112.28.103&ups_ts=1495810627&utid=QjCvEfJHrUACAYxwHGflV5Dh&ccode=0401&psid=c243ffaf524c61d7bed63cae260ade29&ckey=&duration=601&expire=18000&ups_key=68479e0cfab2f50825013496bef96270
```

**Comment by Natim** [comment]
youtube-dl -g seems to give me the link to some mp4 files rather than the m3u8 one.

**Comment by yan12125** [comment]
@Natim: could you give an example?

**Comment by Natim** [comment]
However not always, for instance:

```$ youtube-dl -g https://www.facebook.com/ChefClub.tv/videos/1667934276564512/```

**Comment by Natim** [comment]
However when the m3u8 file is returned it is not the one who lists the available formats but more the one who lists the chunks.

**Comment by chovy** [comment]
ANyone figure out how to rip facebook live feeds?
