### ISSUE TITLE
Wrong resolution for format 138

### ISSUE THREAD

**Issue by degtyaryov** [rg3/youtube-dl#4559]
Hello

$ youtube-dl -F http://www.youtube.com/watch?v=fWvucW2iPP0
[youtube] Confirming age
[youtube] fWvucW2iPP0: Downloading webpage
[youtube] fWvucW2iPP0: Downloading video info webpage
[youtube] fWvucW2iPP0: Extracting video information
[youtube] fWvucW2iPP0: Downloading DASH manifest
[info] Available formats for fWvucW2iPP0:
format code extension resolution  note 
172         webm      audio only  DASH audio    5k , audio@256k (44100Hz), 21.81KiB (worst)
171         webm      audio only  DASH audio    6k , audio@128k (44100Hz), 22.26KiB
139         m4a       audio only  DASH audio   51k , audio@ 48k (22050Hz), 355.25KiB
140         m4a       audio only  DASH audio  134k , audio@128k (44100Hz), 943.18KiB
141         m4a       audio only  DASH audio  260k , audio@256k (44100Hz), 1.83MiB
160         mp4       256x144     DASH video  111k , video only, 806.98KiB
278         webm      256x144     DASH video  109k , webm container, VP9, video only, 612.05KiB
133         mp4       426x240     DASH video  252k , video only, 1.75MiB
242         webm      426x240     DASH video  213k , video only, 1.24MiB
134         mp4       640x360     DASH video  608k , video only, 3.67MiB
243         webm      640x360     DASH video  373k , video only, 2.29MiB
135         mp4       854x480     DASH video 1111k , video only, 7.44MiB
244         webm      854x480     DASH video  724k , video only, 4.44MiB
136         mp4       1280x720    DASH video 2217k , video only, 14.64MiB
247         webm      1280x720    DASH video 1411k , video only, 8.74MiB
137         mp4       1920x1080   DASH video 4145k , video only, 25.78MiB
248         webm      1920x1080   DASH video 2466k , video only, 14.00MiB
264         mp4       2560x1440   DASH video 6623k , video only, 36.40MiB
271         webm      2560x1440   DASH video 18830k , video only, 66.14MiB
272         webm      3840x2160   DASH video 28524k , video only, 99.86MiB
138         mp4       7680x2160   DASH video 24871k , video only, 152.74MiB
82          mp4       360p        3D 
100         webm      360p        3D 
84          mp4       720p        3D 
17          3gp       176x144     
36          3gp       320x240     
5           flv       400x240     
18          mp4       640x360     
43          webm      640x360     
22          mp4       1280x720    (best)

Instead of 7680x2160 must be 7680x4320!

**Comment by phihag** [comment]
Thanks, fixed in e65566a9cc13d13bef3dc70eebfc9bda2e302b78 and youtube-dl 2015.01.03. See [our FAQ](https://yt-dl.org/update) if you need help updating.
