### ISSUE TITLE
cannot download Daum tvpot url

### ISSUE THREAD

**Issue by bwlim** [rg3/youtube-dl#4566]
cannot download video from Daum tvpot which is Korean internet portal service
http://tvpot.daum.net/v/vfb45BtrWBWWHKEkOwXEghB

**Comment by beensham** [comment]
You may try Allavsoft to download Daum movie or video with one click and save the high-quality output in various video formats: MP4, AVI, WMV, FLV, MOV, MKV and other more. I hope this will help you.
