### ISSUE TITLE
Option for --max-resolution

### ISSUE THREAD

**Issue by Jasmine-Lognnes** [rg3/youtube-dl#4584]
Just like `--max-quality`, it would be great to have a `--max-resolution`, where I could do

```
--max-resolution=720,480
```

to indicate that I prefer 720p and 480p as fall back. Youtube-dl should decide with codec is the best for the given resolution.

Since format 35 is no longer supported, youtube-dl can't download a 480p video with audio with a single command like `--max-quality=35` used to do. `--max-resolution=480` would solve this problem.

**Comment by phihag** [comment]
Thank you for the report. youtube-dl 2015.01.23 and newer add the new experimental format filters. I believe  `-f "[height=720]/[height=480]"` does precisely what you *request*, although `-f "[height<=?720]"` is probably what you *want*.
