### ISSUE TITLE
Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by ionospheric** [rg3/youtube-dl#4587]
see also #4430 and #4398 for similar results
BUT
for those two the error message wasn't generated  when using "the --verbose flag"
and
I'm using youtube-dl  2014.12.17.2
and
I have --write-annotations switched in from ~/youtube-dl.conf

Error message on download from youtube . . . . 

WARNING: [youtube] dR1_YrC4f6Y: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)

Error message  requests "please report this issue on https://yt-dl.org/bug"
A search on github.com shows two similar with previous youtube-dl versions . . 

https://github.com/rg3/youtube-dl/search?q=Skipping+DASH+manifest&type=Issues&utf8=%E2%9C%93

NOTE
1/ the .mp4 and the annotations .xml files both arrive intact despite the error message
2/ if a .part file (or the full mp4) exists then I don't see the Error message
3/ when I made a test directory and tried a few downloads of this same file, deleting previous downloads before each run the error message stopped ocurring after a few runs see last paragraph 

So . . . . 

# python youtube-dl.py -U
youtube-dl is up-to-date (2014.12.17.2)
#

(Python version 2.7.6 - Linux-3.11.10-25-desktop-x86_64-with-SuSE-13.1-x86_64)

And running  --verbose  as requested . . .

# python youtube-dl.py --verbose https://www.youtube.com/watch?v=dR1_YrC4f6Y
[debug] System config: []
[debug] User config: ['--write-sub', '--no-overwrites', '--write-annotations', '--all-subs', '--title']
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=dR1_YrC4f6Y']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.6 - Linux-3.11.10-25-desktop-x86_64-with-SuSE-13.1-x86_64
[debug] exe versions: ffmpeg 2.1.4, ffprobe 2.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] dR1_YrC4f6Y: Downloading webpage
[youtube] dR1_YrC4f6Y: Extracting video information
WARNING: video doesn't have subtitles
[youtube] dR1_YrC4f6Y: Searching for annotations.
WARNING: [youtube] dR1_YrC4f6Y: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[info] Writing video annotations to: MFJ CUB - 40m QRP Kit (ARRL Package)-dR1_YrC4f6Y.mp4.annotations.xml
[debug] Invoking downloader on u'https://r11---sn-ab5l6nld.googlevideo.com/videoplayback?signature=74B6CCB1972672F3B054C46A53D362503A85872F.2508F6CDE2DAB351408E3FADDF293371B0EF758B&ip=my.ip.address.here&mm=35&id=o-AB_puRRIsM1pbtOYzHOrTp7u_WrP-nj92LoRB0kSnG3f&fexp=900718%2C912134%2C927622%2C931342%2C932404%2C9405735%2C9406065%2C943917%2C947209%2C947218%2C948124%2C948528%2C952302%2C952605%2C952901%2C955301%2C957103%2C957105%2C957201&sparams=dur%2Cid%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=bnmIs89BbTQ&itag=18&ms=pm&mv=s&dur=502.177&source=youtube&mime=video%2Fmp4&requiressl=yes&ipbits=0&sver=3&key=yt5&expire=1419789225&mt=1419765566&ratebypass=yes'
[download] Destination: MFJ CUB - 40m QRP Kit (ARRL Package)-dR1_YrC4f6Y.mp4
[download] 100% of 28.09MiB in 00:47

BUT

after removing the downloaded files and re-running a few times I eventually see a different googlevideo url and no error message . . .

# python youtube-dl.py https://www.youtube.com/watch?v=dR1_YrC4f6Y --verbose
[debug] System config: []
[debug] User config: ['--write-sub', '--no-overwrites', '--write-annotations', '--all-subs', '--title']
[debug] Command-line args: ['https://www.youtube.com/watch?v=dR1_YrC4f6Y', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.6 - Linux-3.11.10-25-desktop-x86_64-with-SuSE-13.1-x86_64
[debug] exe versions: ffmpeg 2.1.4, ffprobe 2.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] dR1_YrC4f6Y: Downloading webpage
[youtube] dR1_YrC4f6Y: Extracting video information
WARNING: video doesn't have subtitles
[youtube] dR1_YrC4f6Y: Searching for annotations.
[youtube] dR1_YrC4f6Y: Downloading DASH manifest
[info] Writing video annotations to: MFJ CUB - 40m QRP Kit (ARRL Package)-dR1_YrC4f6Y.mp4.annotations.xml
[debug] Invoking downloader on u'https://r1---sn-3jvh-ajte.googlevideo.com/videoplayback?id=o-AMTc__Oeu27Sa2wbL_yj0OqR2nI_6BsCmwevgwN5Gc8_&upn=Nor6wcGVxEE&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=900234%2C900718%2C901803%2C912820%2C916644%2C927622%2C932404%2C939975%2C943917%2C947209%2C947218%2C948124%2C952302%2C952605%2C952901%2C955301%2C957103%2C957105%2C957201&expire=1419794668&itag=18&ipbits=0&ip=81.168.20.20&mime=video%2Fmp4&source=youtube&ms=au&mt=1419773036&mv=m&requiressl=yes&sver=3&signature=3A63B61BA982400CCDAF5912BA3D924E7829A71E.8507D2E6373E084307EB936F43BFCA0FCDF5BDCC&ratebypass=yes&initcwndbps=750000&dur=502.177&mm=31&key=yt5'
[download] Destination: MFJ CUB - 40m QRP Kit (ARRL Package)-dR1_YrC4f6Y.mp4
[download] 100% of 28.09MiB in 00:34

Any use ???
I don't know anything about python (or googlevideo) so I can't offer any insight . .

cb

**Comment by dstftw** [comment]
Works fine with latest version (2016.05.16).
