### ISSUE TITLE
EllenTV/EllenTube issue(s?)

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#4604]
Same video, but two separate issues (?) 
(not sure..sry)

The  EllenTube.com URL is sent to the generic extractor and downloads a 9kb 'unknown_video' file:

URL: http://ellentube.com/videos/0-dvzmabd5/

youtube-dl -v "http://ellentube.com/videos/0-dvzmabd5/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://ellentube.com/videos/0-dvzmabd5/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20
[debug] Proxy map: {}
[generic] 0-dvzmabd5: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 0-dvzmabd5: Downloading webpage
[generic] 0-dvzmabd5: Extracting information
[debug] Invoking downloader on u'http://cdnapi.kaltura.com/index.php/kwidget/wid
/_1656501/uiconf_id/27358732/entry_id/0_dvzmabd5'
[download] Destination: 1 year old twin sister makes her brother laugh _ ellentu
be.com-0_dvzmabd5.unknown_video
[download] 100% of 9.60KiB in 00:00

The EllenTV.com URL fails with: "Unable to extract OpenGraph title"

URL: http://www.ellentv.com/videos/0-dvzmabd5/

youtube-dl -v "http://www.ellentv.com/videos/0-dvzmabd5/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.ellentv.com/videos/0-dvzmabd5/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20
[debug] Proxy map: {}
[EllenTV] 0-dvzmabd5: Downloading webpage
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  t
o update. Be sure to call youtube-dl with the --verbose flag and include its com
plete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 592, in extract_info
  File "youtube_dl\extractor\common.pyo", line 243, in extract
  File "youtube_dl\extractor\ellentv.pyo", line 39, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 577, in _og_search_title
  File "youtube_dl\extractor\common.pyo", line 565, in _og_search_property
  File "youtube_dl\extractor\common.pyo", line 489, in _search_regex
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue
on https://yt-dl.org/bug . Make sure you are using the latest version; type  you
tube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and in
clude its complete output.

Thanks
RIngo

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
