### ISSUE TITLE
--download-archive should check also if file is present on the disk and redownloaded

### ISSUE THREAD

**Issue by mihaicris** [rg3/youtube-dl#4606]
If a file has been accidentally deleted from the disk (although its ID is in the archive list) it should be downloaded again.

**Comment by phihag** [comment]
`--download-archive` is explicitly intended to cover cases where the file has been downloaded once before. If you do not want youtube-dl to download videos that are on disk, but download everything else, simply leave out the `--download-archive` option. youtube-dl will then automatically skip downloading any videos that are already present on disk.

**Comment by mihaicris** [comment]
Thanks, what a great program!
