### ISSUE TITLE
how use youtube-dl to download youtube 1080p video on windows without installation?

### ISSUE THREAD

**Issue by angel100w** [rg3/youtube-dl#4608]
hello,
i want to use youtube-dl together with ffmpeg on windows 8 without installation, to my knowledge you can execute ffmpeg without adding it to path just typing in the command prompt for exmple like this : C:\ffmpeg\bin\ffmpeg.exe -codecs, if it is located in c.
i don't know if this works with youtube-dl, if that's the case will it find ffmgeg to merge the audio and video if i place it place it next to ffmpeg.exe file ?
if not is there any other way to use youtube-dl with ffmpeg without the need of installation ?

**Comment by dstftw** [comment]
You should put ffmpeg.exe near the youtube-dl.exe or in any directory that is in your `PATH` environment variable.
