### ISSUE TITLE
does youtube-dl merge the audio and video of youtube 1080p videos with ffmpeg without re-encoding ?

### ISSUE THREAD

**Issue by angel100w** [rg3/youtube-dl#4609]
hi,
i just want to know if youtube-dl merges the audio and video of youtube 1080p videos with ffmpeg without re-encoding so there is no quality loss ?
what is the command used ? is it this one : ffmpeg -i filename_video.mp4 -i filename_audio.m4a -vcodec copy -acodec copy filename.mp4 ?

**Comment by dstftw** [comment]
There is no quality loss, it just muxes them together. To output the full ffmpeg command used for mixing use `--verbose` flag.
