### ISSUE TITLE
BBC iPlayer Embeds

### ISSUE THREAD

**Issue by epitron** [rg3/youtube-dl#4619]
Hi there!

The BBC iPlayer extractor (`bbccouk.py`) currently doesn't handle embedded videos. There are a few examples on this page: http://www.bbc.co.uk/blogs/adamcurtis/posts/BUGGER

It looks like it should be simple to add: the `<param flashvars="...">` tag (inside the embed's `<div class="player">` tag) has an iPlayer url in it. I can paste it right into `youtube-dl`, and it downloads fine! The extractor just needs to recognize those embeds and scrape out the URL (the flashvar that contains the URL is called "playlist").

(BTW: To make youtube-dl download the url from the flash variable, I had to update the `_VALID_URL` regexp to accept "iplayer/playlist" urls, like this: ``` _VALID_URL = r'https?://(?:www\.)?bbc\.co\.uk/(?:programmes|iplayer/episode|iplayer/playlist)/(?P<id>[\da-z]{8})'```)

What's a good way to implement this? Is there an extractor that I can take a look at as a good example?

Thanks!

**Comment by dstftw** [comment]
BBC iPlayer embeds will be supported in the next version. Thanks for the report.

**Comment by epitron** [comment]
Great! Thanks for the fast response.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.05 or newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
