### ISSUE TITLE
Support for tfou.fr

### ISSUE THREAD

**Issue by zoggy** [rg3/youtube-dl#4620]
youtube-dl --verbose 'http://www.tfou.fr/les-mysterieuses-cites-d-or-saison-2/videos/l-expedition-les-mysterieuses-cites-d-or-8302866-739.html'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.tfou.fr/les-mysterieuses-cites-d-or-saison-2/videos/l-expedition-les-mysterieuses-cites-d-or-8302866-739.html']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.01.01
[debug] Python version 2.7.6 - Linux-3.13.0-34-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, ffmpeg 2.4.2, ffprobe 2.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] l-expedition-les-mysterieuses-cites-d-or-8302866-739: Requesting header
WARNING: Falling back on generic information extractor.
[generic] l-expedition-les-mysterieuses-cites-d-or-8302866-739: Downloading webpage
[generic] l-expedition-les-mysterieuses-cites-d-or-8302866-739: Extracting information
ERROR: Unsupported URL: http://www.tfou.fr/les-mysterieuses-cites-d-or-saison-2/videos/l-expedition-les-mysterieuses-cites-d-or-8302866-739.html

**Comment by dstftw** [comment]
TFOU will be supported in the next version of oyutube-dl. Thanks for the report.
