### ISSUE TITLE
Youtube-dl On Crunchyroll Not Working

### ISSUE THREAD

**Issue by ajay230ps** [rg3/youtube-dl#4623]
~$ youtube-dl -F http://www.crunchyroll.com/naruto-shippuden/episode-391-madara-uchiha-rises-666343
[Crunchyroll] 666343: Downloading webpage
[Crunchyroll] 666343: Downloading media info
[Crunchyroll] 666343: Downloading subtitles for English (US)
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
mrtj@xenon:~$ youtube-dl -F --verbose http://www.crunchyroll.com/naruto-shippuden/episode-391-madara-uchiha-rises-666343[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', '--verbose', 'http://www.crunchyroll.com/naruto-shippuden/episode-391-madara-uchiha-rises-666343']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.6 - Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, ffmpeg 2.4.3, ffprobe 2.4.3, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 666343: Downloading webpage
[Crunchyroll] 666343: Downloading media info
[Crunchyroll] 666343: Downloading subtitles for English (US)
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 603, in extract_info
return self.process_ie_result(ie_result, download, extra_info)
File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 649, in process_ie_result
return self.process_video_result(ie_result, download=download)
File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 853, in process_video_result
raise ExtractorError('No video formats found!')
ExtractorError: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
It will work in the next version (see https://github.com/rg3/youtube-dl/issues/2782#issuecomment-68558894).
