### ISSUE TITLE
How to use yttoplist with youtube mixes

### ISSUE THREAD

**Issue by jovanmaric** [rg3/youtube-dl#4634]
I'm trying to download the following mix:
![image](https://cloud.githubusercontent.com/assets/3003740/5606391/51a683a0-942d-11e4-9789-8cc18609322b.png)

with link: https://www.youtube.com/watch?v=3zTYIKJOM9Y&list=RD3zTYIKJOM9Y

I have used the following command:
youtube-dl --verbose "yttoplist:music:Mix van: Delilah - Inside My Love (Redlight Remix)" but this only results in an error. Am i doing something wrong?

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

youtube-dl --verbose "yttoplist:music:Mix van: Delilah - Inside My Love (Redlight Remix)"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'yttoplist:music:Mix van: Delilah - Inside My Love (Redlight Remix)']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.04
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.4.4, ffprobe 2.4.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:toplist] Mix van: Delilah - Inside My Love (Redlight Remix): Downloading webpage
ERROR: Unable to extract list; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 592, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 245, in extract
    return self._real_extract(url)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 1280, in _real_extract
    channel_page, 'list')
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 501, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 491, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract list; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
Actually, you can just run `youtube-dl "https://www.youtube.com/watch?v=3zTYIKJOM9Y&list=RD3zTYIKJOM9Y"`

**Comment by iggyvolz** [comment]
It's still a bug though - shouldn't both behaviors be supported?

**Comment by jaimeMF** [comment]
The toplist extractor was for playlists like [this one](https://www.youtube.com/playlist?list=PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI) (see #1868), they needed special treatment because they couldn't be accessed with an url, that's why you had to use  `youtube-dl yttoplist:music:Popular Music Videos`. I have actually removed the extractor in 2f985f4bb4938ee13356bda0436fde18f8c0e434 because they are normal playlists now.

But the url posted here is different, it's a mix generated for the video 3zTYIKJOM9Y.
