### ISSUE TITLE
WARNING: unable to extract categories

### ISSUE THREAD

**Issue by oxplot** [rg3/youtube-dl#4640]
The youtube video causing the warning to be shown is:

https://www.youtube.com/watch?v=iV9_i9MEnMg

I ran `youtube-dl` with no command line options.

**Comment by jaimeMF** [comment]
You are probably running an outdated version, with recent version no message will be printed if the video doesn't have the categories listed in the webpage.

For future error reports please post the [full output of `youtube-dl URL --verbose`](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).
