### ISSUE TITLE
Vevo resulting HTTP Error 403

### ISSUE THREAD

**Issue by RooGrr** [rg3/youtube-dl#4641]
Hello! First of all I wanted to thank you for the amazing job you do at making youtube-dl and support you provide for it.

Here's the issue. Vevo is geoblicked in my country so I'm using ip proxy from hidemyass, tried different US proxies they result the same outcome.

d:\rtmp>youtube-dl http://www.vevo.com/watch/young-artists-for-haiti/Wavin-Flag/CAUV71000003 --proxy 209.170.151.142:8089 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.vevo.com/watch/young-artists-for-haiti/Wavin-Flag/CAUV71000003', '--proxy', '209.170.151.142:8089', '--verbose']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.01.04
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {u'http': '209.170.151.142:8089', u'https': '209.170.151.142:8089'}
[Vevo] Retrieving oauth token
[Vevo] CAUV71000003: Downloading JSON metadata
[Vevo] CAUV71000003: Downloading HLS formats
[Vevo] CAUV71000003: Downloading m3u8 information
[debug] Invoking downloader on u'http://hls-aws.vevo.com/v3/hls/2014/09/CAUV71000003/0c39c085-0b91-4ea9-9434-97446b3dd696/5200/cauv71000003_5200k_1920x1080_h264_5200_aac_128.m3u8'
[download] Destination: Wavin' Flag-CAUV71000003.mp4
[hlsnative] CAUV71000003: Downloading m3u8 manifest
[hlsnative] CAUV71000003: Downloading segment 1 / 26
[hlsnative] CAUV71000003: Downloading segment 2 / 26
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1136, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1112, in dl
  File "youtube_dl\downloader\common.pyo", line 297, in download
  File "youtube_dl\downloader\hls.pyo", line 93, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1371, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden

Although, I'm able to download .ts parts manually with browser with and without proxy.
This is the only video I managed to get. 
Any other just show Error 403:

d:\rtmp>youtube-dl http://www.vevo.com/watch/fiona-apple/O-Sailor/USSM20500956 --proxy 209.170.151.142:8089 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.vevo.com/watch/fiona-apple/O-Sailor/USSM20500956', '--proxy', '209.170.151.142:8089', '--verbose']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.01.04
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {u'http': '209.170.151.142:8089', u'https': '209.170.151.142:8089'}
[Vevo] Retrieving oauth token
[Vevo] USSM20500956: Downloading JSON metadata
[Vevo] USSM20500956: Downloading HLS formats
[Vevo] USSM20500956: Downloading m3u8 information
[debug] Invoking downloader on u'http://hls-aws.vevo.com/v3/hls/2014/09/USSM20500956/698f3a1c-ba2b-4bb4-b39a-301d7786cd8d/5200/ussm20500956_5200k_1920x1080_h264_5200_aac_128.m3u8'
[download] Destination: O' Sailor-USSM20500956.mp4
[hlsnative] USSM20500956: Downloading m3u8 manifest
[hlsnative] USSM20500956: Downloading segment 1 / 29
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1136, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1112, in dl
  File "youtube_dl\downloader\common.pyo", line 297, in download
  File "youtube_dl\downloader\hls.pyo", line 93, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1371, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden

**Comment by jaimeMF** [comment]
It could be that the proxy is blocked by them, can you play the video from your browser using the proxy?

**Comment by RooGrr** [comment]
no, I can't. 
Is there a way to download geo-blocked page with proxy but download the video content without it?

**Comment by jaimeMF** [comment]
You can try with:
```shell
$ youtube-dl 'http://www.vevo.com/watch/young-artists-for-haiti/Wavin-Flag/CAUV71000003' --proxy 209.170.151.142:8089 -j > info.json
$ youtube-dl --load-info info.json
```

Since this is a problem with the proxy you are using I'm closing the issue.
