### ISSUE TITLE
three questions

### ISSUE THREAD

**Issue by angel100w** [rg3/youtube-dl#4642]
hello
i have thee question on using youtube-dl to download youtube videos : 
first how to put the video and audio format (possibly audio bitrate also) in the file name and how to make it the default
second is it possible to download from youtube many videos at a time, may be separate  urls with , or ;  and i am not talking about playlists here
third how to add a default folder for the downloaded videos

**Comment by phihag** [comment]
As mentioned in [our bug reporting guidelines](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md#does-the-issue-involve-one-problem-and-one-problem-only), please do ask only one question per issue. I'll make an exception here, but in the future, we may simply close issues that ask for too many things at once (don't worry, opening issues is free, so you can open - within reason - as many as you want).

To make something default, add it to a [configuration file](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration).

To include the format details in the file name, use `%(acodec)s`, `%(vcodec)s` and `%(abr)s`, like this:

```
$ youtube-dl -o '%(title)s-%(vcodec)s-%(acodec)s-%(abr)sk.%(ext)s' --get-filename http://www.zdf.de/ZDFmediathek/beitrag/video/257404/heute-100SEC
heute 100SEC-h264-aac-56k.mp4
```

Note that this is only supported for a minority of sites. If you do think a site provides the information anywhere but the information is missing in youtube-dl, please [open a new issue](https://github.com/rg3/youtube-dl/issues/new) with an example URL and where which information can be found.

you can download multiple videos by simply giving more URLs to youtube-dl, as in
```
youtube-dl http://www.youtube.com/watch?v=BaW_jenozKc http://www.zdf.de/ZDFmediathek/beitrag/video/257404/heute-100SEC
```

These downloads will be run sequentially; we intend to implement parallel downloading though.

To pick another location for the downloaded files, have a look at the [filesystem options](https://github.com/rg3/youtube-dl/blob/master/README.md#filesystem-options). A configuration entry like `-o '/home/angel/videos/%(title)s-%(id)s.%(ext)s` should work.
