### ISSUE TITLE
This Youtube video doesn't download right

### ISSUE THREAD

**Issue by Ketsuban** [rg3/youtube-dl#4650]
When downloaded, the format is unknown; when played, there is no audio stream and MPV spits "No video PTS! Making something up." about three times a second.

    [thomas@chansey ~]♣ youtube-dl -v "https://www.youtube.com/watch?v=orybDrUj4vA"
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=orybDrUj4vA']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.01.04
    [debug] Python version 3.4.2 - Linux-3.17.6-1-ARCH-x86_64-with-arch
    [debug] exe versions: ffmpeg 2.5.2, ffprobe 2.5.2, rtmpdump 2.4
    [debug] Proxy map: {}
    [youtube] orybDrUj4vA: Downloading webpage
    [youtube] orybDrUj4vA: Extracting video information
    [youtube] orybDrUj4vA: Downloading DASH manifest
    [debug] Invoking downloader on 'https://r3---sn-cn3tc-cime.googlevideo.com/videoplayback?id=a2bc9b0eb52367570973&lmt=1418932566294693&dur=95.150&upn=ULc7IBXgnoE&mt=1420525268&key=dg_yt0&sver=3&fexp=900718,9277105,957201&signature=5AF5AAADD5183D6770862A605C5848DEDB225E80.77257CAF165316CC7BB0634BD4EA483A50962AC9&ebypass,mime,gir,clen,lmt,dur'
    [download] Destination: Quick and Easy Voting for Normal People-orybDrUj4vA.unknown_video

I made one change from stock 2015.01.04 to fix #4648 until 2015.01.05 appears in my package manager - it's the same as [this commit](https://github.com/rg3/youtube-dl/commit/ee61f6f3e2f4d03a3ad9c5ca8f4fc5cd9461bdbc). If I can't reproduce the problem when the update lands and this issue is still open then I'll close it myself.

**Comment by jaimeMF** [comment]
Thanks for the report, it will work in the next version.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.08. See [our FAQ](https://yt-dl.org/update) if you need help updating.
