### ISSUE TITLE
Support for overview pages (not playlists)

### ISSUE THREAD

**Issue by mrMoe** [rg3/youtube-dl#4651]
Hi there,

is it possible to always get the latest video of this mediathek listing page?

http://www1.wdr.de/mediathek/video/sendungen/quarks_und_co/filterseite-quarks-und-co100.html

I don't want to always go there by hand and select the latest video manually.
And the podcast isn't an option because the quality is more limited than on the index page.

Thanks!

**Comment by phihag** [comment]
Thank you for the report. I believe this issue to be fixed in youtube-dl 2015.01.09.1 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
