### ISSUE TITLE
Ability to list all extractors (--list-extractor), excluding porn sites

### ISSUE THREAD

**Issue by bubbleguuum** [rg3/youtube-dl#4653]
It would be useful to be able to list all extractors but without any porn site.
Something like --list-extractor-no-porn

Sometimes you need to make a list of sites supported by youtube-dl but you do not want porn sites to be listed.

Implementing this would require a per extractor flag that tells if it is a porn site or not.

**Comment by phihag** [comment]
Thank you for the report. I do not think that we should start a classification whether a site is pornographic or not. Instead, I do think it may be useful to limit the list of extractors depending on the age of the user though.

In youtube-dl 2015.01.07.1 and newer, `--list-extractors` respects the `--age-limit` option. Use `youtube-dl --list-extractors --age-limit 0` to only show extractors that are generally suitable for everyone (or `youtube-dl --list-extractors --age-limit 17` if you're okay with sites whose contents regularly contain swear words, etc.).

Please bear in mind that this only means that a majority content on these sites is suitable for the given age. For example, YouTube does serve R-rated videos, but is included no matter the given age limit.

 See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by bubbleguuum** [comment]
Thank you. That was exactly what I was looking for.
