### ISSUE TITLE
Subparts for tv.nrk.no

### ISSUE THREAD

**Issue by amaurea** [rg3/youtube-dl#4656]
Some pages on `tv.nrk.no` contain multiple streams. An example is "http://tv.nrk.no/serie/tour-de-ski/MSPO40010515/06-01-2015#del=1" and "http://tv.nrk.no/serie/tour-de-ski/MSPO40010515/06-01-2015#del=2". youtube-dl downloads the first part no matter which url one uses. It would be nice if it either downloaded both, let you choose which one to download, or concatenated them.

**Comment by dstftw** [comment]
NRKTV playlist will be supported in the next version, thanks for the report.
