### ISSUE TITLE
Add support for abc.go.com

### ISSUE THREAD

**Issue by nevafuse** [rg3/youtube-dl#4661]
Example URL: http://abc.go.com/shows/forever/episode-guide/season-01/106-the-frustrating-thing-about-psychopaths

**Comment by EveryDirection** [comment]
Yes, this, please! After all, ABC is one of the Big Four broadcasters of the United States.

Another series of example URLs, for the webseries "Cornell Confidential":

Here is the index page for the whole series:

http://abc.go.com/shows/secrets-and-lies/video/cornell-confidential

which then links to the URLs for specific episodes:

http://abc.go.com/shows/secrets-and-lies/video/cornell-confidential/VDKA0_dnprchoe
http://abc.go.com/shows/secrets-and-lies/video/cornell-confidential/VDKA0_3yc2p8d1
http://abc.go.com/shows/secrets-and-lies/video/cornell-confidential/VDKA0_qms57g85
http://abc.go.com/shows/secrets-and-lies/video/cornell-confidential/VDKA0_mp7ozf23
http://abc.go.com/shows/secrets-and-lies/video/cornell-confidential/VDKA0_vp5a07ho
http://abc.go.com/shows/secrets-and-lies/video/cornell-confidential/VDKA0_gtn1tyn9
http://abc.go.com/shows/secrets-and-lies/video/cornell-confidential/VDKA0_rm0ndt2j
http://abc.go.com/shows/secrets-and-lies/video/cornell-confidential/VDKA0_xnjfpgej
http://abc.go.com/shows/secrets-and-lies/video/cornell-confidential/VDKA0_w9wlhq00
http://abc.go.com/shows/secrets-and-lies/video/cornell-confidential/VDKA0_lldi6ll1

**Comment by dmwyatt** [comment]
I messed around with this a little bit.  It looks like their player pulls down an m3u8 file after playing the advertisements.

I can't quite figure out what it is that tells the browser the url of that m3u8 file...

**Comment by CMaiku** [comment]
Wrote a patch to resolve this issue: #9383

**Comment by EveryDirection** [comment]
> Wrote a patch to resolve this issue: #9383 

Thanks so much, @CMaiku, but unfortunately, it looks like the pull request wasn't accepted.

Can someone who understands what the issues are please fix the patch so it can be accepted?

**Comment by vxbinaca** [comment]
Yes I must report the site no longer works, if it ever did. Falls back on generic for:

http://abcnews.go.com/2020/video/2020-husband-stands-teacher-jail-student-affairs-26119478

**Comment by CMaiku** [comment]
> Thanks so much, @CMaiku, but unfortunately, it looks like the pull request wasn't accepted.
> 
> Can someone who understands what the issues are please fix the patch so it can be accepted?

It doesn't look to me like anyone looked at it yet. Just automated things. The CI fails on master and all the other PRs I've seem, but the things I touched still succeed. I will however address the QuantifiedCode issues.

> Yes I must report the site no longer works, if it ever did. Falls back on generic for:
> 
> http://abcnews.go.com/2020/video/2020-husband-stands-teacher-jail-student-affairs-26119478

This bug and/or my patch is for abc.go.com, not abcnews.go.com. It looks like it has a different backend as well.

**Comment by vxbinaca** [comment]
@CMaiku I'll file a separate issue then, thanks.

**Comment by tml** [comment]
I have an abc.go.com link which youtube-dl isn't able to download; I am using version `2017.05.29`. This is not an episode which requires authentication.

Here is my verbose output when trying to download the free episode from URL http://abc.go.com/shows/still-star-crossed/episode-guide/season-01/1-series-premiere-in-fair-verona-where-we-lay-our-scene

```
youtube-dl --verbose 'http://abc.go.com/shows/still-star-crossed/episode-guide/season-01/1-series-premiere-in-fair-verona-where-we-lay-our-scene'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://abc.go.com/shows/still-star-crossed/episode-guide/season-01/1-series-premiere-in-fair-verona-where-we-lay-our-scene']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.29
[debug] Python version 3.6.0 - Darwin-16.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 12, avprobe 12, ffmpeg 3.3.1, ffprobe 3.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[Go] 1-series-premiere-in-fair-verona-where-we-lay-our-scene: Downloading webpage
[Go] VDKA3863519: Downloading JSON metadata
[debug] Using fake IP 3.124.17.196 (US) as X-Forwarded-For.
[Go] VDKA3863519: Downloading JSON metadata
[Go] VDKA3863519: Downloading m3u8 information
[debug] Invoking downloader on 'http://content-ausw2.uplynk.com/c31f767feac84a86a9fcecb463d3ba66/j.m3u8?exp=1496168226&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10094893&iph=c75fbf551974007f0222c203928568267ffe7ad20caaddec1c5c284bd9542da4&rays=jihgfedcb&euid=31CF1068-0D86-4333-BD29-6CBD8BFE8C57_000_0_001_lf_01-06-00_NA&cdn=ec&stgcfg=datg&pp2ip=0&ddp=1&sig=3f755941e858987e04c90e99fd2a71f9500041b37f05cd956ec7eef87c565356&pbs=1176aea0efcf40a89cf4cc72a493465f'
[download] Destination: In Fair Verona, Where We Lay Our Scene-VDKA3863519.mp4
[debug] avconv command line: avconv -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
X-Forwarded-For: 3.124.17.196
' -i 'http://content-ausw2.uplynk.com/c31f767feac84a86a9fcecb463d3ba66/j.m3u8?exp=1496168226&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10094893&iph=c75fbf551974007f0222c203928568267ffe7ad20caaddec1c5c284bd9542da4&rays=jihgfedcb&euid=31CF1068-0D86-4333-BD29-6CBD8BFE8C57_000_0_001_lf_01-06-00_NA&cdn=ec&stgcfg=datg&pp2ip=0&ddp=1&sig=3f755941e858987e04c90e99fd2a71f9500041b37f05cd956ec7eef87c565356&pbs=1176aea0efcf40a89cf4cc72a493465f' -c copy -f mp4 'file:In Fair Verona, Where We Lay Our Scene-VDKA3863519.mp4.part'
avconv version 12, Copyright (c) 2000-2016 the Libav developers
  built on Mar  6 2017 22:35:59 with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --disable-debug --disable-shared --disable-indev=jack --prefix=/usr/local/Cellar/libav/12 --enable-gpl --enable-nonfree --enable-version3 --enable-vda --cc=clang --host-cflags= --host-ldflags= --enable-libfaac --enable-libmp3lame --enable-libx264 --enable-libxvid
  libavutil     55. 20. 0 / 55. 20. 0
  libavcodec    57. 25. 0 / 57. 25. 0
  libavformat   57.  7. 2 / 57.  7. 2
  libavdevice   56.  1. 0 / 56.  1. 0
  libavfilter    6.  7. 0 /  6.  7. 0
  libavresample  3.  0. 0 /  3.  0. 0
  libswscale     4.  0. 0 /  4.  0. 0
Unable to open key file https://content-ausw2.uplynk.com/check2?b=c31f767feac84a86a9fcecb463d3ba66&v=c31f767feac84a86a9fcecb463d3ba66&r=j&pbs=1176aea0efcf40a89cf4cc72a493465f
Format detected only with low score of 1, misdetection possible!
[mp3 @ 0x7feaca000600] Header missing
    Last message repeated 1047 times
[mp3 @ 0x7feacd066c00] Estimating duration from bitrate, this may be inaccurate
[mp2 @ 0x7feaca08ca00] Header missing
    Last message repeated 1047 times
Input #0, hls,applehttp, from 'http://content-ausw2.uplynk.com/c31f767feac84a86a9fcecb463d3ba66/j.m3u8?exp=1496168226&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10094893&iph=c75fbf551974007f0222c203928568267ffe7ad20caaddec1c5c284bd9542da4&rays=jihgfedcb&euid=31CF1068-0D86-4333-BD29-6CBD8BFE8C57_000_0_001_lf_01-06-00_NA&cdn=ec&stgcfg=datg&pp2ip=0&ddp=1&sig=3f755941e858987e04c90e99fd2a71f9500041b37f05cd956ec7eef87c565356&pbs=1176aea0efcf40a89cf4cc72a493465f':
  Duration: 00:43:00.41, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: mp2
      0 channels, s16p
Output #0, mp4, to 'file:In Fair Verona, Where We Lay Our Scene-VDKA3863519.mp4.part':
Output file #0 does not contain any stream


ERROR: ffmpeg exited with code 1
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1896, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 771, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 825, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1539, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1803, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1745, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 360, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/external.py", line 57, in real_download
    self.get_basename(), retval))
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 551, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

```

**Comment by dstftw** [comment]
@tml don't use avconv.

**Comment by EveryDirection** [comment]
I don't think this issue should be closed. I just tested it with multiple URLs, and abc.go.com doesn't seem to be working with YouTube-DL at all. Here's an example:

`youtube-dl --verbose http://abc.go.com/shows/secrets-and-lies/video/cornell-confidential/vdka3399570
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://abc.go.com/shows/secrets-and-lies/video/cornell-confidential/vdka3399570']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2017.05.29
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP2
[debug] exe versions: ffmpeg N-56433-g93439e8, ffprobe N-56433-g93439e8
[debug] Proxy map: {}
[Go] vdka3399570: Downloading JSON metadata
[debug] Using fake IP 3.140.58.197 (US) as X-Forwarded-For.
[Go] VDKA3399570: Downloading JSON metadata
ERROR: Unable to download JSON metadata: <urlopen error [SSL: CERTIFICATE_VERIFY
_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1,
 '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\bu
ild\youtube_dl\extractor\common.py", line 502, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\bu
ild\youtube_dl\YoutubeDL.py", line 2106, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\bu
ild\youtube_dl\utils.py", line 1082, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open`

**Comment by dstftw** [comment]
@EveryDirection #11573 (comment)
