### ISSUE TITLE
Add support for netzkino.de

### ISSUE THREAD

**Issue by OE1FEU** [rg3/youtube-dl#4669]
I suspect it has something to do with th original URL:
http://www.netzkino.de/#!/scifikino/rakete-zum-mond

And the "#!" contained in it. I shortened it to  http://goo.gl/dXWWlc

youtube-dl --verbose http://goo.gl/dXWWlc
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://goo.gl/dXWWlc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.10.3
[debug] Python version 2.7.8 - Linux-3.17.7-300.fc21.x86_64-x86_64-with-fedora-21-Twenty_One
[debug] exe versions: none
[debug] Proxy map: {}
[generic] dXWWlc: Requesting header
[redirect] Following redirect to http://www.netzkino.de/#!/scifikino/rakete-zum-mond
[generic] rakete-zum-mond: Requesting header
WARNING: Falling back on generic information extractor.
[generic] rakete-zum-mond: Downloading webpage
[generic] rakete-zum-mond: Extracting information
ERROR: Unsupported URL: http://www.netzkino.de/#!/scifikino/rakete-zum-mond; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 651, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 1425, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 554, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 242, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1044, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.netzkino.de/#!/scifikino/rakete-zum-mond; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phihag** [comment]
Thank you for the report. youtube-dl 2015.01.09.2 and newer add support for netzkino. See [our FAQ](https://yt-dl.org/update) if you need help updating.
