### ISSUE TITLE
It goes wrong when resuming the download task

### ISSUE THREAD

**Issue by LemonJeer** [rg3/youtube-dl#467]
I choose youtube-dl because it can resume the download task.
I tried to download http://www.youtube.com/watch?v=IXXX14F_lgo, the file is big and I powered off my computer before I went to bed, the task was about 60% completed. The next day I resumed the task but I found it was 99% completed...When it was finished, the file was just 2GB and of course it was not really completed, I could only play the video partially.

**Comment by seowwj** [comment]
Shall we close this issue? As it has been a while since the last update.

**Comment by yan12125** [comment]
The original description is insufficient. Feel free to open a new issue with details (command line logs, ...) if that occurs again.
