### ISSUE TITLE
am i doing this right

### ISSUE THREAD

**Issue by angel100w** [rg3/youtube-dl#4670]
hello
i was trying to download youtube 1080p video on windows 8 so i placed youtube-dl.exe next to ffmpeg.exe in ffmpeg folder like this C:\Users\angel\Documents\ydlffmpeg\ffmpeg-20150109-git-d1c6b7b-win64-static\bin, and i just went to this location in the command prompt to run it and youtube-dl was able to find ffmpeg and merge the audio and video
my question is this :  is it ok if i use youtube-dl and ffmpeg this way  for both programs because the folder where i placed youtube-dl.exe belongs to ffmpeg  and contains his files (keep in mind that i also want to use ffmpeg separately for other purposes)
second does any of youtube-dl or ffmpeg save any file or parameter in the windows system if i use them like this

**Comment by phihag** [comment]
ffmpeg.exe is not envious for youtube-dl, and will happily share its directory with any other executable. I have no idea why you mean by `windows system`, so I cannot answer that question. Can you elaborate what a `windows system` is? Do you mean the directory `C:\Windows`?

**Comment by angel100w** [comment]
what i mean by windows system is those files and registry keys and stuff that is put when installing programs

**Comment by phihag** [comment]
Sorry, I still don't understand. What's the technical definition of `put in the system when installingt programs`?

youtube-dl (and as far as I know ffmpeg) will not modify any registry keys.

Both executables will of course need various libraries from your system, but will not modify them. Even if the applications wanted, you are hopefully running without administrator rights, and therefore the applications are not even able to modify system files such as those residing in `C:\Windows`.

Both youtube-dl and ffmpeg will write files though, and those will end up on your filesystem.

**Comment by angel100w** [comment]
the thing is i noticed that videos on windows media player and vlc became jumpy, and when i checked the technical support in windows media player (in help then about windows media) witch shows all binaries codec and filter etc... i noticed a change and i am suspecting ffmpeg to be the cause, because i did not install anything else and even windows update is turned off
could this be possible and please how to fix this

**Comment by phihag** [comment]
youtube-dl will not change your codec preferences in any way. [You are in the wrong issue tracker](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md#is-your-question-about-youtube-dl) if you have questions about ffmpeg.

**Comment by angel100w** [comment]
like i said i suspect ffmpeg not youtube-dl

**Comment by angel100w** [comment]
after i rechecked it seems that it was a normal system change, no change in codecs just some system dlls and it has nothing to do with both programs, this is my conclusion so far and who knows what really happened because i am not an expert
