### ISSUE TITLE
problem naming downloaded videos

### ISSUE THREAD

**Issue by angel100w** [rg3/youtube-dl#4671]
hi
i was trying to download youtube 1080p video like this :
 youtube-dl -o C:\Users\angel\Documents\youda\%(title)s-%(resolution)s-%(acodec)s-%(abr)sk.%(ext)s -f 137+141 https://www.youtube...
so i can define the download folder and add the title, resolution, audio format, audio bitrate, and extension to the file name
i could see these infos in the names of the video and audio files when youtube-dl is downloading them but after merging them with ffmpeg it becomes like this title-na-na-na.mp4
so please how do i get these info in the final name

**Comment by phihag** [comment]
Thank you for the report. I believe this issue to be fixed in youtube-dl 2015.01.09.1 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
