### ISSUE TITLE
Adjust aspect ratio

### ISSUE THREAD

**Issue by casinero** [rg3/youtube-dl#4674]
It seems that the actual dimensions of some video files are different from how they appear on youtube, and usually the latter look more natural. For example [this one](https://www.youtube.com/watch?v=_b-2C3KPAM0), when downloaded and played using mpc-hc on Windows, it's actually like [this](https://r3---sn-3cu-u2xe.googlevideo.com/videoplayback?id=fdbfb60b728f00cd&itag=138&source=youtube&requiressl=yes&mm=31&mv=m&ms=au&ratebypass=yes&mime=video/mp4&gir=yes&clen=44631070&lmt=1370445446849472&dur=84.985&signature=20BA3306C56360BA40E3EBEC0372904C8FCBA6EE.70375D7D5527CB9B493856F45D740011594FCE35&mt=1420846532&upn=AlJcuK1B4Uo&sver=3&fexp=900718,912332,927622,931363,932404,936117,9405932,941004,943917,945085,947209,947218,948124,948531,952302,952605,952901,955105,955301,957103,957105,957201,959701&key=dg_yt0&ip=182.235.176.159&ipbits=0&expire=1420868155&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mv,ms,ratebypass,mime,gir,clen,lmt,dur). Therefore I try to mark the aspect ratio at container level according to what `--get-format` reveals, in this case "2276x2160", using ffmpeg: `ffmpeg -i i.mp4 -c copy -aspect 2276:2160 o.mp4`. However the result distorts another way. It becomes too "thin", like this:
![image](https://cloud.githubusercontent.com/assets/10470585/5689731/3e0fbef6-98a6-11e4-8ccc-3ec90134172c.png)
Is there any other imformation I can get from youtube-dl which helps to adjust this ideally?

**Comment by phihag** [comment]
Can you post the output you get when running youtube-dl with the `-v` option?

As mentioned in our [bug reporting guidelines](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md), without that it's quite hard to understand what's going on here, in particular which format you did actually download.

**Comment by casinero** [comment]
`youtube-dl -f bestvideo --get-format -v https://www.youtube.com/watch?v=_b-2C3KPAM0`
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', 'bestvideo', '--get-format', '-v', 'https://ww
w.youtube.com/watch?v=_b-2C3KPAM0']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2015.01.01
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-68788-g37b35fe, ffprobe N-68788-g37b35fe
[debug] Proxy map: {}
138 - 2276x2160 (DASH video)

`youtube-dl -f bestvideo -v https://www.youtube.com/watch?v=_b-2C3KPAM0`
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', 'bestvideo', '-v', 'https://www.youtube.com/wa
tch?v=_b-2C3KPAM0']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2015.01.01
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-68788-g37b35fe, ffprobe N-68788-g37b35fe
[debug] Proxy map: {}
[youtube] _b-2C3KPAM0: Downloading webpage
[youtube] _b-2C3KPAM0: Extracting video information
[youtube] _b-2C3KPAM0: Downloading DASH manifest
[debug] Invoking downloader on 'https://r3---sn-3cu-u2xe.googlevideo.com/videopl
ayback?id=fdbfb60b728f00cd&itag=138&source=youtube&requiressl=yes&ms=au&mv=m&mm=
31&ratebypass=yes&mime=video/mp4&gir=yes&clen=44631070&lmt=1370445446849472&dur=
84.985&signature=043B3B1DF1355EF65C14DD42CE2FB410EA7A4573.31119408D2D7076E4CC5FA
F760EE6667D4968C94&fexp=900718,927622,932404,936109,9405160,941004,943917,947209
,947218,947225,948124,952302,952605,952901,955301,957103,957105,957201,959701&ke
y=dg_yt0&sver=3&mt=1420855179&upn=qbWl4z16-Lw&ip=182.235.176.159&ipbits=0&expire
=1420876830&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,mm,ratebypa
ss,mime,gir,clen,lmt,dur'
[download] Destination: [A-made] 變態妍字幕版 太妍 我就是這樣的人-_b-2C3KPAM0.mp
4
[download] 100% of 42.56MiB in 00:45

**Comment by phihag** [comment]
Thank you for the report.

You are using an outdated version; the height and width of the DASH formats is incorrect since YouTube changed what they serve, this has been fixed in youtube-dl 2014.01.05.1.

youtube-dl 2015.01.10 and newer will fix up these videos automatically, but you can also pass in `--fixup warn` if you'd like to do that yourself. See [our FAQ](https://yt-dl.org/update) if you need help updating.
