### ISSUE TITLE
Add support for Ö1 Webradio

### ISSUE THREAD

**Issue by unki2aut** [rg3/youtube-dl#4675]
http://oe1.orf.at/konsole?show=live

Please support Ö1 Webradio :)

Link of a single Show: http://oe1.orf.at/konsole?show=on_demand#?track_id=394211

Solution:
the ABP Console shows that there are elements loaded like:
http://loopstream01.apa.at/?channel=oe1&shoutcast=0&ua=flash&id=20150108_0905_11_1_radiokolleg_R1K_w_
and opening the link in a new tab lets you downaload the auio as MPGA.

**Comment by unki2aut** [comment]
Thank you for the lightning fast response!

**Comment by phihag** [comment]
Fixed in youtube-dl 2015.01.10.1 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
