### ISSUE TITLE
Download page should make use of a link without version, but with 'latest' tag instead.

### ISSUE THREAD

**Issue by deragon** [rg3/youtube-dl#4677]
http://rg3.github.io/youtube-dl/download.html hard codes the latest version in the command to download it.

sudo curl https://yt-dl.org/downloads/2015.01.10.2/youtube-dl -o /usr/local/bin/youtube-dl

When I install a new Linux machine, I would like to run a script that downloads the latest.  Therefore, I would like to be able to run:

sudo curl https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl

Notice the verrsion replaced by 'latest'.

**Comment by jaimeMF** [comment]
You can actually use it `curl 'https://yt-dl.org/downloads/latest/youtube-dl' -L -o /path/to/youtube-dl`

**Comment by phihag** [comment]
As @jaimeMF said, your suggestion is implemented already! There's also the shorter https://yt-dl.org/latest/youtube-dl if you want.

Note that there is a reason why the [download page](https://rg3.github.io/youtube-dl/download.html) hardcodes the version number. If it were dynamic, the checksums published there would not match the actual files during the release of a new version.
