### ISSUE TITLE
Pyinstaller, youtube_dl and ffmpeg!!

### ISSUE THREAD

**Issue by Elite** [rg3/youtube-dl#4681]
I created an GUI for ytdl and it works fine when executed from python file, however if I pack it using `pyinstaller` with `one file` option it downloads the video but fails to convert it using `ffmpeg` (one copy of which is in the application folder and another on OS path).

I noticed if I allow `pyinstaller` to open a console window `http://pythonhosted.org/PyInstaller/#id23` it works fine and executes `ffmpeg`.

**Comment by phihag** [comment]
As mentioned in [our bug reporting guidelines](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md), please post the output you get when you add the `--verbose` option (or set `{'verbose': True}` in the params for the `YoutubeDL` object). Without that, we cannot see what is going on here.

That being said, this is almost certainly a pyinstaller issue. How does the directory layout actually look when it's unpacked?

**Comment by Elite** [comment]
Got this while researching the issue - https://groups.google.com/d/msg/pyinstaller/-4Fdy7suh0U/0o9Yqa78zCEJ, it seems the problem lies in the fact how `subprocess` calls are handled when using pyinstaller one-file option.

**Comment by phihag** [comment]
Closing; the problem seems to be in pyinstaller. Even if it's not, without the requested additional information we could not hope to solve it.
