### ISSUE TITLE
Sanitize filename: Replace ": " with " -" but replace ":" with "-"

### ISSUE THREAD

**Issue by Josso** [rg3/youtube-dl#4683]
Downloading videos from YouTube containing ":" will make odd sanitized filenames.
[Currently](https://github.com/rg3/youtube-dl/blob/149f05c7b6adcb55b96c4ca60abc4e42d98623a7/youtube_dl/utils.py#L280-L281) ":" is replaced with " -" which makes perfect sense in the case of "Some Title: Subtitle" which will then be transformed to "Some Title - Subtitle".
But in cases where the title contains a timestamp like "New World Record at 0:12:34" it gets transformed to "New World Record at 0 -12 -34" instead of the slightly better "New World Record at 0-12-34".

It could be solved by e.g. looping over the string and looking at the next char, instead of mapping each char:
```python
for i in range(len(s)):
    char = s[i]
    if char == '?' or ord(char) < 32 or ord(char) == 127:
        char = ''
    elif char == '"':
        char = '' if restricted else '\''
    elif char == ':' and s[i+1] == ' ':
        char = '_-' if restricted else ' -'
    elif char == ':':
        char = '-' if restricted else '-'
    elif char in '\\/|*<>':
        char = '_'
    if restricted and (char in '!&\'()[]{}$;`^,#' or char.isspace()):
        char = '_'
    if restricted and ord(char) > 127:
        char = '_'
    s = s[:i] + char + s[i+1:]
```

**Comment by phihag** [comment]
Thank you for the report. I believe this issue to be fixed in youtube-dl 2015.01.11 and newer. See [our FAQ][https://yt-dl.org/update) if you need help updating.
