### ISSUE TITLE
vk.com does not work anymore

### ISSUE THREAD

**Issue by doublex** [rg3/youtube-dl#4686]
Testcase:
youtube-dl 'http://vk.com/video_ext.php?oid=232484720&id=169808649&hash=ab04827a4a232f49'

**Comment by jaimeMF** [comment]
The video seems to be restricted to registered  users, have you tried with the `--username` option?

If it doesn't work, please [post the **full output**](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) of `youtube-dl 'http://vk.com/video_ext.php?oid=232484720&id=169808649&hash=ab04827a4a232f49' --verbose OTHER_OPTIONS_HERE`.

**Comment by doublex** [comment]
Thanks a lot.
I think the error message is an error. The video plays in the browser (I don't have a vk.com account) - but to download the video does not work.

**Comment by jaimeMF** [comment]
But it can't be played if you click in the `Go to video` button.
By the way: it would be great if you could provide a video that wasn't a movie (probably uploaded without distributing rights).

**Comment by fiocfun** [comment]
Valid 'hash' param of url allows access for non-registered users; this is intended for embedding on other sites, etc.

**Comment by yousufalim** [comment]
i have a similar problem, videos that require authentication dont download, however all videos that do not require auth download just fine.
i am using the latest version on youtube-dl

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://vk.com/video-87482294_171259320', '-u', u'PRIVATE', '-p', u'PRIVATE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.16
[debug] Python version 2.7.5 - Linux-3.10.23-xxxx-std-ipv6-64-x86_64-with-fedora-20-Heisenbug
[debug] exe versions: ffmpeg 2.1.5, ffprobe 2.1.5
[debug] Proxy map: {}
[vk.com] Logging in as admin@pixup.us
[vk.com] -87482294_171259320: Downloading webpage
ERROR: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 633, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 270, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vk.py", line 184, in _real_extract
    data_json = self._search_regex(r'var vars = ({.*?});', info_page, 'vars')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Will be fixed in the next version.
