### ISSUE TITLE
error while downloading from YouTube

### ISSUE THREAD

**Issue by shubhamjsharma3lac** [rg3/youtube-dl#4692]
(HTTP 403 Forbidden) , you do not have permission to view the webpage.

**Comment by phihag** [comment]
Sorry, this report is lacking any information that could help us. Please reread our [issue reporting guidelines](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md) that go into detail of how to make a good bug report.

All I can say is that YouTube downloads work fine for me. I am therefore closing this issue. Please comment or open a new issue with all of the information mentioned in the [issue reporting guidelines](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md). Thanks!
