### ISSUE TITLE
smotri.com says "not approved by moderator" while being viewable in browser

### ISSUE THREAD

**Issue by arisboch** [rg3/youtube-dl#4698]
I tried to download a video from the Russian video sharing site smotri.com, but I got that error message instead:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://smotri.com/video/view/?id=v28888533b73', '-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.11
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: avconv 2.5.3, avprobe 2.5.3, ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[smotri] v28888533b73: Downloading video JSON
ERROR: Video v28888533b73 has not been approved by moderator
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 600, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 260, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/smotri.py", line 150, in _real_extract
    raise ExtractorError('Video %s has not been approved by moderator' % video_id, expected=True)
ExtractorError: Video v28888533b73 has not been approved by moderator

I tried to watch (firefox) and download (video downloadhelper) it with the browser and it worked.

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.

**Comment by arisboch** [comment]
Thanks! It works now, although doesn't retrieve the upload date or resolution.
