### ISSUE TITLE
ATresPlayer not working (authenticated video)

### ISSUE THREAD

**Issue by jjarava** [rg3/youtube-dl#4700]
Hi!

I'm trying to use youtube-dl to download a video from Atresplayer.com.

The URL of the video is <http://www.atresplayer.com/television/series/velvet/temporada-2/capitulo-1-captulo_2014102100219.html>

I can properly play the video when using the webpage, so it's not really a "permissions" issue.

The output of using the `--verbose` option is:

```
youtube-dl jjarava$ youtube-dl --verbose -u XXXXXXXXX -p XXXXXXX http://www.atresplayer.com/television/series/velvet/temporada-2/capitulo-1-captulo_2014102100219.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-u', u'PRIVATE', '-p', u'PRIVATE', 'http://www.atresplayer.com/television/series/velvet/temporada-2/capitulo-1-captulo_2014102100219.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.11
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[AtresPlayer] capitulo-1-captulo: Downloading webpage
[AtresPlayer] capitulo-1-captulo: Downloading timestamp
[AtresPlayer] capitulo-1-captulo: Downloading windows video JSON
ERROR: AtresPlayer returned error: El usuario no tiene permisos para ver el vídeo
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 600, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 260, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/atresplayer.py", line 76, in _real_extract
    '%s returned error: %s' % (self.IE_NAME, result), expected=True)
ExtractorError: AtresPlayer returned error: El usuario no tiene permisos para ver el v\xeddeo
```

Best Regards!

**Comment by dstftw** [comment]
AtresPlayer authentication will be supported in the next version. You'll need to pass your email and password to `-u` and `-p` options correspondingly.
Thanks for the report.

**Comment by jjarava** [comment]
Thanks for the info - when is the "next version" released?

I've just "updated" (youtube -U) and after an update, I get the message I have a new version:

```
youtube-dl jjarava$ youtube-dl -U
youtube-dl is up-to-date (2015.01.15)
```

So, thinking the release was "updated" I've tried again, but I still get the same error when trying to download a "protected" item.

**Comment by dstftw** [comment]
> when is the "next version" released?

When @phihag have some time to do that. We will bump this issue when it's released.

**Comment by jjarava** [comment]
Thanks for the heads up then, I'll wait.

I've also just open another issue (#4705) that might as well be related.

**Comment by dstftw** [comment]
AtresPlayer authentication support was incorporated in youtube-dl 2015.01.15.1. Refer to [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by jjarava** [comment]
I can confirm that the download is now working providing the username and password,  thanks!!
