### ISSUE TITLE
Play only 5 seconds and stop for http://www.youtube.com/watch?v=h-fgS97M2zE in Raspberry Pi

### ISSUE THREAD

**Issue by chengpeck** [rg3/youtube-dl#4701]
Hi All,

I having problem to play the below link (Daai TV Live TV) in Raspberry Pi and it only play in 5 seconds and stop it. There will be no problem to play the others youtube video but not for this live TV.

omxplayer -o hdmi $(youtube-dl -s -g http://www.youtube.com/watch?v=h-fgS97M2zE)

Is this is a known bug for youtube live video or only problem found in Raspberry ? 

* I have updated youtube-dl with latest update.

Thank you  very much.

**Comment by dstftw** [comment]
Most likely omxplayer does not support hls streams.
