### ISSUE TITLE
Livestream not working

### ISSUE THREAD

**Issue by sebma** [rg3/youtube-dl#4702]
Hey guys,

Livestream download is currently not working, i'm using version youtube-dl version 2015.01.11 and rtmpdump version 2.4
Here is the verbose output :

$ youtube-dl --verbose http://www.livestream.com/tv2vieproductions/video?clipId=pla_0dc1ab57-d709-4172-b859-279ce99b035a
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.livestream.com/tv2vieproductions/video?clipId=pla_0dc1ab57-d709-4172-b859-279ce99b035a']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.11
[debug] Python version 2.7.8 - Linux-3.16.0-29-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6, rtmpdump 2.4
[debug] Proxy map: {}
[livestream:original] pla_0dc1ab57-d709-4172-b859-279ce99b035a: Downloading XML
[debug] Invoking downloader on u'rtmp://extondemand.livestream.com/ondemand'
[download] Destination: Questions Réponses - le catholicisme romain-pla_0dc1ab57-d709-4172-b859-279ce99b035a.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmp://extondemand.livestream.com/ondemand -o 'Questions Réponses - le catholicisme romain-pla_0dc1ab57-d709-4172-b859-279ce99b035a.flv.part' --swfVfy 'http://static.livestream.com/chromelessPlayer/v21/playerapi.swf?hash=5uetk&v=0803&classid=D27CDB6E-AE6D-11cf-96B8-444553540000&jsEnabled=false&wmode=opaque' --playpath trans/dv15/mogulus-user-files/chtv2vieproductions/2012/05/22/cba4162b-22e6-4566-9dd9-b0474560406e --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : extondemand.livestream.com
[rtmpdump] DEBUG: Parsed app     : ondemand
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : extondemand.livestream.com
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : trans/dv15/mogulus-user-files/chtv2vieproductions/2012/05/22/cba4162b-22e6-4566-9dd9-b0474560406e
[rtmpdump] DEBUG: tcUrl    : rtmp://extondemand.livestream.com:1935/ondemand
[rtmpdump] DEBUG: swfUrl   : http://static.livestream.com/chromelessPlayer/v21/playerapi.swf?hash=5uetk&v=0803&classid=D27CDB6E-AE6D-11cf-96B8-444553540000&jsEnabled=false&wmode=opaque
[rtmpdump] DEBUG: app      : ondemand
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: 10 00 79 4e aa 2b 4e 55 52 54 a6 17 bd e6 ae ce
[rtmpdump] DEBUG: ac 78 85 39 a8 9a dd 15 5a ee a4 ea a1 16 a4 e7
[rtmpdump] DEBUG: SWFSize  : 872168
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : extondemand.livestream.com
[rtmpdump] DEBUG: Parsed app     : ondemand
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : extondemand.livestream.com
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : trans/dv15/mogulus-user-files/chtv2vieproductions/2012/05/22/cba4162b-22e6-4566-9dd9-b0474560406e
[rtmpdump] DEBUG: tcUrl    : rtmp://extondemand.livestream.com:1935/ondemand
[rtmpdump] DEBUG: swfUrl   : http://static.livestream.com/chromelessPlayer/v21/playerapi.swf?hash=5uetk&v=0803&classid=D27CDB6E-AE6D-11cf-96B8-444553540000&jsEnabled=false&wmode=opaque
[rtmpdump] DEBUG: app      : ondemand
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: 10 00 79 4e aa 2b 4e 55 52 54 a6 17 bd e6 ae ce
[rtmpdump] DEBUG: ac 78 85 39 a8 9a dd 15 5a ee a4 ea a1 16 a4 e7
[rtmpdump] DEBUG: SWFSize  : 872168
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 365, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 355, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1205, in download
    res = self.extract_info(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 611, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 657, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 960, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1155, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1131, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 308, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/rtmp.py", line 206, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 149, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 491, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 453, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

$

Any idea ?

**Comment by jaimeMF** [comment]
It will work again in the next version, thanks for the report.

**Comment by sebma** [comment]
Hi,

I'm sorry, but it's still not working with youtube-dl version 2015.05.04 :

$ youtube-dl --version
2015.05.04
$ youtube-dl --ignore-config --verbose http://www.livestream.com/tv2vieproductions/video?clipId=pla_0dc1ab57-d709-4172-b859-279ce99b035a
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-config', u'--verbose', u'http://www.livestream.com/tv2vieproductions/video?clipId=pla_0dc1ab57-d709-4172-b859-279ce99b035a']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.04
[debug] Python version 2.7.8 - Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6, ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[livestream:original] pla_0dc1ab57-d709-4172-b859-279ce99b035a: Downloading XML
[debug] Invoking downloader on u'rtmp://extondemand.livestream.com/ondemand'
[download] Destination: Questions Réponses - le catholicisme romain-pla_0dc1ab57-d709-4172-b859-279ce99b035a.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmp://extondemand.livestream.com/ondemand -o 'Questions Réponses - le catholicisme romain-pla_0dc1ab57-d709-4172-b859-279ce99b035a.flv.part' --swfVfy 'http://static.livestream.com/chromelessPlayer/v21/playerapi.swf?hash=5uetk&v=0803&classid=D27CDB6E-AE6D-11cf-96B8-444553540000&jsEnabled=false&wmode=opaque' --playpath trans/dv15/mogulus-user-files/chtv2vieproductions/2012/05/22/cba4162b-22e6-4566-9dd9-b0474560406e --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : extondemand.livestream.com
[rtmpdump] DEBUG: Parsed app     : ondemand
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : extondemand.livestream.com
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : trans/dv15/mogulus-user-files/chtv2vieproductions/2012/05/22/cba4162b-22e6-4566-9dd9-b0474560406e
[rtmpdump] DEBUG: tcUrl    : rtmp://extondemand.livestream.com:1935/ondemand
[rtmpdump] DEBUG: swfUrl   : http://static.livestream.com/chromelessPlayer/v21/playerapi.swf?hash=5uetk&v=0803&classid=D27CDB6E-AE6D-11cf-96B8-444553540000&jsEnabled=false&wmode=opaque
[rtmpdump] DEBUG: app      : ondemand
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: 3e 7a a9 65 4d 52 83 b5 19 61 5b 96 3e b1 02 83
[rtmpdump] DEBUG: 14 87 da f8 e1 23 44 95 05 9e 91 a6 3b ce 27 fe
[rtmpdump] DEBUG: SWFSize  : 872282
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : extondemand.livestream.com
[rtmpdump] DEBUG: Parsed app     : ondemand
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : extondemand.livestream.com
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : trans/dv15/mogulus-user-files/chtv2vieproductions/2012/05/22/cba4162b-22e6-4566-9dd9-b0474560406e
[rtmpdump] DEBUG: tcUrl    : rtmp://extondemand.livestream.com:1935/ondemand
[rtmpdump] DEBUG: swfUrl   : http://static.livestream.com/chromelessPlayer/v21/playerapi.swf?hash=5uetk&v=0803&classid=D27CDB6E-AE6D-11cf-96B8-444553540000&jsEnabled=false&wmode=opaque
[rtmpdump] DEBUG: app      : ondemand
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: 3e 7a a9 65 4d 52 83 b5 19 61 5b 96 3e b1 02 83
[rtmpdump] DEBUG: 14 87 da f8 e1 23 44 95 05 9e 91 a6 3b ce 27 fe
[rtmpdump] DEBUG: SWFSize  : 872282
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.


ERROR: rtmpdump exited with code 1
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 401, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 391, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1482, in download
    res = self.extract_info(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 707, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1153, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1415, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1357, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 528, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 490, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

$ echo $?
1
$ 

Can you please look into it ?

**Comment by jaimeMF** [comment]
You'll need to wait until the next release or use the code from the git repo.
