### ISSUE TITLE
download from tagesschau.de not working any more

### ISSUE THREAD

**Issue by htgoebel** [rg3/youtube-dl#4704]
AFAIK, this worked, so I assume they changed something.
CSS-Path to container container is:

html body.tagesschau.story.contenttypemeldung div#content div.wrapper div.section.sectionZ.sectionArticle div.con div.modCon div.mod.modA.modParagraph div.boxCon div.box div.mediaCon.mediaTop.small.video div.media.mediaA div.mediaInfo div.modForm div.form form.seperateFields div fieldset div.controls

within this, the files for the different media are to be found at 
`div.button a[attrib=href]`

**Comment by phihag** [comment]
Sorry, but this bug report is missing essential information, without which we cannot work on solving this problem. Please review our [bug reporting guidelines](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md). In particular, we need the full output of youtube-dl when called with the `-v` option.

For what it's worth, tagesschau downloads work fine for me.
