### ISSUE TITLE
Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by japyles** [rg3/youtube-dl#4713]
localhost:$ youtube-dl --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.15
[debug] Python version 2.7.6 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: you must provide at least one URL

**Comment by dstftw** [comment]
This is already fixed and will be available in the next release. Thanks for the report.

**Comment by dstftw** [comment]
This is already fixed and will be available in the next release. Thanks for the report.

**Comment by dstftw** [comment]
This issue was fixed in youtube-dl 2015.01.15.1. Refer to [our FAQ](https://yt-dl.org/update) if you need help updating.
