### ISSUE TITLE
Enhancement - option to ask for passwords interactively (to avoid passwords getting into history files, etc)

### ISSUE THREAD

**Issue by jjarava** [rg3/youtube-dl#4723]
Hi!

Unless I'm mistaken, when downloading a video that requires user/password authentication, there is no option to have the program ask for the password interactively instead of having to provide it on the command line.

In many other utilities, there is either a different switch to have the program ask for the password, (-P maybe?) or when the password provided is some special char (normally "*") then the first thing the program does is ask for the password.

The idea is to avoid getting the password into all kind of logs and places that track programs invoked, etc such as the history file, completion buffers, etc...

**Comment by dstftw** [comment]
If you does not provide a passwrod but only a username with `-u` you will be automatically prompted for a password. No option is required.

**Comment by jjarava** [comment]
Brillant!!

I'd humbly suggest updating the docs (`--help` text) to indicate that option exists. I've been clearing out my history file but it's a pity not having the URLs etc on it...

Regards
