### ISSUE TITLE
source address bug throws 429 too many request

### ISSUE THREAD

**Issue by TheGr33k** [rg3/youtube-dl#4728]
I think a recent youtube-dl version introduced a bug in youtube-dl
The Ip address shown in this report has been modified for privacy reasons.If you need real reports , you can find me on Skype
Checking in IP binding works on centos 7 

1. `wget -qO- http://checkip.dyndns.com/ --bind-address 111.123.567.123`

`<html><head><title>Current IP Check</title></head><body>Current IP Address: 111.123.567.123  </body></html>`

This confirms that ip binding works correctly

2.  `curl --interface 111.123.567.123 -s -I -L https://www.youtube.com/ | head -1`
HTTP/1.1 200 OK

This confirms that the IP  isn;t banned by youtube

3. `youtube-dl -g --verbose  --source-address 111.123.567.123  https://www.youtube.com/watch?v=Zbz5cRXS2Mk`

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-g', '--verbose', '--source-address', '111.123.567.123', 'https://www.youtube.com/watch?v=Zbz5cRXS2Mk']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.5 - Linux-3.10.0-123.13.2.el7.x86_64-x86_64-with-centos-7.0.1406-Core
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 293, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1412, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by TheGr33k** [comment]
Turns out that i had to update to python Python version 2.7.9 :)

Thanks to Philipp Hagemeister  for the help

**Comment by phihag** [comment]
Indeed, there was a bug under older Python versions. Fixed as of d79323136fabc2cd72afc7c124e17797e32df514.

**Comment by TheGr33k** [comment]
@phihag 

What python version you recommend to use for youtube-dl

**Comment by phihag** [comment]
We generally support python 2.6, 2.7 and 3.2+. While we try to avoid it, some features may not work on *very* old versions of 2.6, 2.7 and 3.2.

We recommend the [newest version](https://www.python.org/doc/versions/); at the moment that's 3.4.2.
