### ISSUE TITLE
rtlxl: "HTTP Error 400: Bad Request" 

### ISSUE THREAD

**Issue by kenavera** [rg3/youtube-dl#4730]
Hi,

I got the following error and it told me to report this bug to you.
I don't have much experience in python, so I can't propose a solution to you.
Other videos from rtl always worked for me. You have a rtlnl.py file for it.

With verbose tag:

"Path to youtube-dl">youtube-dl http://www.rtlxl.nl/#!/everybody-dance-now-295947/69384569-8192-35cf-9e2a-c905
1f239028 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.rtlxl.nl/#!/everybody-dance-now-295947/69384569-8192-35cf-9e2a-c9051f239028', '-
-verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[rtlxl.nl] 69384569-8192-35cf-9e2a-c9051f239028: Downloading JSON metadata
[rtlxl.nl] 69384569-8192-35cf-9e2a-c9051f239028: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call
 youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 293, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1412, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

Thanks for the great program

Kenavera

**Comment by corone17** [comment]
It because you have to pay to watch that videobroadcast.
If you click [here](http://www.rtlxl.nl/#!/gemist/everybody-dance-now-295947), you can see that only episode 3 is freely available at the moment. You have to pay to watch episode 1 and 2. (if they replace the "XL"-logo with a "€"-logo, it would be clear to everyone you're dealing with an episode you'd have to pay for...)

**Comment by Kaligule** [comment]
So this issiue is closed?
