### ISSUE TITLE
worldstarhiphop.com error

### ISSUE THREAD

**Issue by rafajafar** [rg3/youtube-dl#4737]
I just updated to the new version of youtube-dl and am getting an error with this url: http://www.worldstarhiphop.com/videos/video.php?v=wshhMiV9OifW9d7il8MU

root@ubuntu:~# youtube-dl http://www.worldstarhiphop.com/videos/video.php?v=wshhMiV9OifW9d7il8MU --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.worldstarhiphop.com/videos/video.php?v=wshhMiV9OifW9d7il8MU', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.6 - Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, rtmpdump 2.4
[debug] Proxy map: {}
[WorldStarHipHop] wshhMiV9OifW9d7il8MU: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 600, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 260, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/worldstarhiphop.py", line 36, in _real_extract
    webpage, 'title')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 526, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 516, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by rafajafar** [comment]
It looks as though there's a redirect on that url. Nevermind... probably not in the scope of a bug.

**Comment by naglis** [comment]
I am closing this issue, as it seems you've figured it out yourself. If you would like youtube-dl to support the website of the redirect (worldstaruncut.com), please open a new issue.

Also, looks like you are running youtube-dl as root. Please note that this is not recommended and should only be done when updating.
