### ISSUE TITLE
Add ffmpeg option to losslessly change container MPEG DASH > MPEG-4 AAC LC

### ISSUE THREAD

**Issue by hymced** [rg3/youtube-dl#4741]
Rising up an old request I am interested in : 

https://github.com/rg3/youtube-dl/issues/3681

Can someone add this feature please ?

**Comment by sdsucks** [comment]
youtube-dl -f 141 -o - https://www.youtube.com/watch?v=-yU449iOwDc | ffmpeg -i - -c copy test.aac

**Comment by hymced** [comment]
Nope that's the kind of things I tried, but it is not fitted with playlists, because all the converted tracks would be named "test.aac", and then erased one after the other...

**Comment by phihag** [comment]
Closing as a uplicate of #3681.
