### ISSUE TITLE
"Unable to obtain file audio codec with ffprobe"

### ISSUE THREAD

**Issue by TheLongLife** [rg3/youtube-dl#4742]
<h2>I'm Noob...<h2>

<b>When I try to download audio only from yt video:<b>

<code>youtube-dl -f 140 [URL]  <code> 

I get .m4a file which I cannot play...
<br><br>

<b>And when I try to:<b>

<code>youtube-dl --extract-audio --audio-format mp3 [URL] <code>

I get this response: "Unable to obtain file audio codec with ffprobe"
<br><br>

I've updated youtube-dl and I do have ffmpeg and ffprobe
I'm using Windows 7

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by TheLongLife** [comment]
<em>[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-69029-ge2db9a7, ffprobe N-69029-ge2db9a7
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]<em>

**Comment by dstftw** [comment]
Post the **full** output with concrete URL you are trying to download.

**Comment by TheLongLife** [comment]
Sorry, I'm noob...Like this ?

<em>
C:\Users\LongLife>youtube-dl -v https://www.youtube.com/watch?v=4EkbZqQ1oHU
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=4EkbZqQ1oHU']

[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-69029-ge2db9a7, ffprobe N-69029-ge2db9a7
[debug] Proxy map: {}
[youtube] 4EkbZqQ1oHU: Downloading webpage
[youtube] 4EkbZqQ1oHU: Extracting video information
[youtube] 4EkbZqQ1oHU: Downloading DASH manifest
[debug] Invoking downloader on u'https://r2---sn-ncc-cxbl.googlevideo.com/videop
layback?fexp=900718%2C904843%2C907263%2C916645%2C927622%2C930821%2C931350%2C9349
47%2C935024%2C9406260%2C941004%2C943917%2C947209%2C947225%2C948124%2C952302%2C95
2605%2C952901%2C955301%2C957103%2C957105%2C957201%2C959701&initcwndbps=1687500&m
m=31&ratebypass=yes&sver=3&ipbits=0&signature=3870B3BE3DD1C6A483D26597CB1CD1EF9C
294039.9206A5BE1CBDFFFD9D623A1E1161B2019C0C21C8&upn=jgbXj9lFblo&id=o-ADbUqVHoVgb
-7_ja8QauYZ7BulrerDpWQG4mqeW5SgHV&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2
Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpi
re&ms=au&mt=1421613868&mv=m&key=yt5&ip=89.216.138.255&requiressl=yes&mime=video%
2Fmp4&expire=1421635497&source=youtube&dur=270.117&pl=17&itag=22'
[download] Destination: Mt Eden + Blackmill - Now-4EkbZqQ1oHU.mp4
[download] 100% of 24.04MiB in 00:08

<em>

**Comment by corone17** [comment]
It's because the m4a-file you're downloading from Youtube is in MPEG-DASH format.
You can fix that afterwards by running ffmpeg:
`ffmpeg.exe -hide_banner -i input.m4a -c:a copy output.m4a`

For my own experimentation I tried to use the --exec option...
```
youtube-dl.exe -f 140 --exec 'ffmpeg.exe -hide_banner -i {} -c:a copy output.m4a'
https://www.youtube.com/watch?v=KpvLMyC4a8o
```
...but that didn't work. How exactly does one use this --exec command in this case?

**Comment by TheLongLife** [comment]
yeap,
<code> ffmpeg.exe -hide_banner -i input.m4a -c:a copy output.m4a <code> 

That works.

**Comment by dstftw** [comment]
Works fine with latest version.

**Comment by brycepg** [comment]
Note that I've gotten this error when `ffprobe` was giving an `illegal instruction error` due to the binary being an incorrect architecture. It might be a good for youtube-dl to output the subprocess stderr/stdout in verbose mode.

**Comment by yan12125** [comment]
@brycepg FYI: This is requested in #8230
