### ISSUE TITLE
ERROR: Signature extraction failed (version 2014.11.24, Python version 2.7.9, on FreeBSD 10.1-STABLE)

### ISSUE THREAD

**Issue by dweber-youtube** [rg3/youtube-dl#4744]
$ youtube-dl https://www.youtube.com/watch?v=SS7Upas11_k
[youtube] Confirming age
[youtube] SS7Upas11_k: Downloading webpage
[youtube] SS7Upas11_k: Downloading video info webpage
[youtube] SS7Upas11_k: Extracting video information
[youtube] SS7Upas11_k: Encrypted signatures detected.
[youtube] SS7Upas11_k: Downloading js player vfl19kCnd
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 560, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 474, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 535, in _parse_sig_js
    'Initial JS player signature function name')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 478, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug

============== version info
$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale ISO8859-1, fs ISO8859-1, out ISO8859-1, pref ISO8859-1
[debug] youtube-dl version 2014.11.24
[debug] Python version 2.7.9 - FreeBSD-10.1-STABLE-amd64-64bit-ELF
[debug] exe versions: ffmpeg 2.3.5, ffprobe 2.3.5, rtmpdump 2.4
[debug] Proxy map: {}

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Refer to [our FAQ](https://yt-dl.org/update) if you have trouble updating.
