### ISSUE TITLE
Detect downloaded merged (dash) files 

### ISSUE THREAD

**Issue by MohammadAlHajj** [rg3/youtube-dl#4747]
First post on github so please point me towards any misconceptions

If a merged (audio+video) file has been already downloaded, it is not detected as done, since the dash files (video, audio) have been deleted. youtube-dl will redownload the audio and videu dash files again instead of detecting it as already downloaded. Should this info not be present in a log file somewhere

**Comment by jaimeMF** [comment]
Duplicated of #4355.
