### ISSUE TITLE
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### ISSUE THREAD

**Issue by eddollet** [rg3/youtube-dl#4748]
Get this when I attempt to extract video, It has always worked just fine up to now.

**Comment by phihag** [comment]
Please actually **do** include the requested output in the bug report. It should start with something along the lines of `[debug] System config: []`.

Can you suggest how we could rephrase the error message to get you to do that?

**Comment by Pinged** [comment]
Recived the same error for the first time 90 min ago.----

Verbose output below
 youtube-dl https://www.youtube.com/playlist?list=PLw613M86o5o7eEwOS_O-s89_ia3tRIcia --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.youtube.com/playlist?list=PLw613M86o5o7eEwOS_O-s89_ia3tRIcia', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.15.0-031500rc2-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[youtube:playlist] PLw613M86o5o7eEwOS_O-s89_ia3tRIcia: Downloading page #1
WARNING: [youtube:playlist] PLw613M86o5o7eEwOS_O-s89_ia3tRIcia: Playlist page is missing OpenGraph title, falling back ...
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1511, in _real_extract
    playlist_title = self._og_search_title(page)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 428, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 416, in _og_search_property
    escaped = self._search_regex(self._og_regexes(prop), html, name, flags=re.DOTALL, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1517, in _real_extract
    r'<h1 class="pl-header-title">(.*?)</h1>', page, u'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 366, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by jaimeMF** [comment]
@Pinged you are running an outdated version, see our [instructions for updating](https://yt-dl.org/update).

**Comment by Pinged** [comment]
My apologies... thanks for the head thump!

**Comment by eddollet** [comment]
I did the update as well, but it still did the same after wards.  I am
thinking it was the internet now, as it is now working today
intermittently.   I got the error once, waited a while and tried again and
it worked.  We lost internet access around the same time today for about an
hour. but back up now.

**Comment by jaimeMF** [comment]
I'm closing the issue then, if you get the error again please post the full output you get when adding the `--verbose` option and we'll reopen the issue.

**Comment by yaseenwaheed** [comment]
Why this error problem
