### ISSUE TITLE
Unable to download from nbcnews.com

### ISSUE THREAD

**Issue by mpk99** [rg3/youtube-dl#4749]
I know this worked before, so perhaps they've recently changed something:

G:\rtmpdump>youtube-dl.exe --verbose http://www.nbcnews.com/feature/dateline-ful
l-episodes/full-episode-family-business-n285156
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.nbcnews.com/feature/datelin
e-full-episodes/full-episode-family-business-n285156']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-68826-g504267f, rtmpdump 2.5
[debug] Proxy map: {}
[NBCNews] full-episode-family-business-n285156: Downloading webpage
[NBCNews] full-episode-family-business-n285156: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by
HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; type  youtube-dl -U  to update. Be sure to call yo
utube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 293, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1412, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.

**Comment by phihag** [comment]
The fix made it into youtube-dl 2015.01.23. See [our FAQ](https://yt-dl.org/update) if you need help updating.
