### ISSUE TITLE
[utils/get_exe_version]youtube-dl crashes with UnicodeDecodeError when downloading a Youtube playlist

### ISSUE THREAD

**Issue by Vdragon** [rg3/youtube-dl#4756]
## Reproducable?
Not always.

## youtube-dl version
2015.01.16

## youtube-dl command
`youtube-dl --verbose --format 137+140 https://www.youtube.com/playlist?list=PLwItru4bLdHx3nnUrFUBFWwMHuo_4Yx9P`
running in `/tmp` CWD

## youtube-dl output
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--format', '137+140', 'https://www.youtube.com/playlist?list=PLwItru4bLdHx3nnUrFUBFWwMHuo_4Yx9P']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.6 - Linux-3.13.0-39-generic-i686-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 365, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 334, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 296, in __init__
    self.print_debug_header()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1451, in print_debug_header
    exe_versions = FFmpegPostProcessor.get_versions()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 51, in get_versions
    return dict((p, get_exe_version(p, args=['-version'])) for p in programs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 51, in <genexpr>
    return dict((p, get_exe_version(p, args=['-version'])) for p in programs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1331, in get_exe_version
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 14: ordinal not in range(128)
```

### OS
Ubuntu 14.04 x86 32bit 

### Python
2.7.6

### Locale
zh_TW.UTF-8

### Libav
9.16

**Comment by phihag** [comment]
Can you share the output you get when you run `ffmpeg -version`?

**Comment by Vdragon** [comment]
@phihag here's the result
% avprobe -version
avprobe version 9.16-6:9.16-0ubuntu0.14.04.1, Copyright (c) 2007-2014 the Libav developers
  built on Aug 10 2014 18:19:26 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
avprobe 9.16-6:9.16-0ubuntu0.14.04.1
libavutil     52.  3. 0 / 52.  3. 0
libavcodec    54. 35. 0 / 54. 35. 0
libavformat   54. 20. 4 / 54. 20. 4
libavdevice   53.  2. 0 / 53.  2. 0
libavfilter    3.  3. 0 /  3.  3. 0
libavresample  1.  0. 1 /  1.  0. 1
libswscale     2.  1. 1 /  2.  1. 1
% avconv -version
avconv version 9.16-6:9.16-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Aug 10 2014 18:19:26 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
avconv 9.16-6:9.16-0ubuntu0.14.04.1
libavutil     52.  3. 0 / 52.  3. 0
libavcodec    54. 35. 0 / 54. 35. 0
libavformat   54. 20. 4 / 54. 20. 4
libavdevice   53.  2. 0 / 53.  2. 0
libavfilter    3.  3. 0 /  3.  3. 0
libavresample  1.  0. 1 /  1.  0. 1
libswscale     2.  1. 1 /  2.  1. 1
% ffmpeg -version 
zsh: command not found: ffmpeg
% ffprobe -version
zsh: command not found: ffprobe
% which ffmpeg
ffmpeg not found

**Comment by Vdragon** [comment]
Failed to reproduce the issue now, closing it until reproducible way is found.

**Comment by anweshknayak** [comment]
I guess the issue is still open ?

**Comment by dstftw** [comment]
It's still closed as you may notice.

**Comment by anweshknayak** [comment]
I mean the issue still exists. It was meant to be reproduced ?

**Comment by dstftw** [comment]
No. Open a new issue if you can reproduce.

**Comment by Vdragon** [comment]
I still can't reproduce the same issue.
