### ISSUE TITLE
Add site support for testtube.com

### ISSUE THREAD

**Issue by JThundley** [rg3/youtube-dl#4759]
Testtube.com hosts Dnews of the Discovery channel. Most videos are scientific in nature. Here is the output when trying to download an episode:

https://testtube.com/dnews/5-weird-ways-plants-can-eat-animals?utm_source=FB&utm_medium=DNews&utm_campaign=DNewsSocial
[generic] 5-weird-ways-plants-can-eat-animals?utm_source=FB&utm_medium=DNews&utm_campaign=DNewsSocial: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 5-weird-ways-plants-can-eat-animals?utm_source=FB&utm_medium=DNews&utm_campaign=DNewsSocial: Downloading webpage
[generic] 5-weird-ways-plants-can-eat-animals?utm_source=FB&utm_medium=DNews&utm_campaign=DNewsSocial: Extracting information
ERROR: Unsupported URL: https://testtube.com/dnews/5-weird-ways-plants-can-eat-animals?utm_source=FB&utm_medium=DNews&utm_campaign=DNewsSocial

**Comment by phihag** [comment]
Thank you for the report. youtube-dl 2015.01.23.1 and newer add support for testtube. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by JThundley** [comment]
Thanks, you rock!
