### ISSUE TITLE
recreate youtube channel hierarchy (playlist subtree structure)

### ISSUE THREAD

**Issue by Garfield222** [rg3/youtube-dl#4761]
I was willing to download following channel:
https://www.youtube.com/user/ChannelTank/playlists

As you can see there are many files and many sub-playlists.
Problem is that youtube-dl download everything into single place - current folder. It would be nice to mirror playlist hierarchy on a local disk. 
Would it be possible to download  playlist recursively. I mean if next url to download is not a video file , but a playlist, youtube-dl could create a subfolder with same name as playlist's title and recursively call itself in the subfolder  to download a new playlist.

thanks

**Comment by ikhaledsayed** [comment]
F

**Comment by dstftw** [comment]
This feature is supported since youtube-dl 2015.11.21 for URLs of the following format: `http://www.youtube.com/user/<user>/playlists`.
