### ISSUE TITLE
pornhub unable to extract 

### ISSUE THREAD

**Issue by tawer5ag** [rg3/youtube-dl#4764]
C:\youtube-dl try>
C:\youtube-dl try>youtube-dl -v http://www.pornhub.com/view_video.php?viewkey=78
8152859
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.pornhub.com/view_video.php?viewkey
=788152859']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[PornHub] 788152859: Downloading webpage
WARNING: unable to extract uploader; please report this issue on http://yt-dl.or
g/bug
WARNING: unable to extract thumbnail; please report this issue on http://yt-dl.o
rg/bug
WARNING: unable to extract view count; please report this issue on http://yt-dl.
org/bug
WARNING: unable to extract like count; please report this issue on http://yt-dl.
org/bug
WARNING: unable to extract dislike count; please report this issue on http://yt-
dl.org/bug
WARNING: unable to extract comment count; please report this issue on http://yt-
dl.org/bug
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 600, in extract_info
  File "youtube_dl\extractor\common.pyo", line 260, in extract
  File "youtube_dl\extractor\pornhub.pyo", line 89, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 657, in _sort_formats
ExtractorError: No video formats found; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.

**Comment by phihag** [comment]
The video in question is set to private. youtube-dl 2015.01.23 and newer recognize it as such and relay the error message. See [our FAQ](https://yt-dl.org/update) if you need help updating.
