### ISSUE TITLE
Extracted m4a audio plays in VLC, not in iTunes

### ISSUE THREAD

**Issue by jonathanfmorgan** [rg3/youtube-dl#4767]
Hi there.

Can you tell me if I'm doing something wrong here when extracting audio?  This command generates an m4a file that plays in VLC.  When I drag the file into iTunes, it shows sample rate, profile, stereo channels, and that it is AAC, but it doesn't show duration or bit rate.  It also won't play.

Thanks. 

$ youtube-dl HnMYghA9d6M -x
[youtube] HnMYghA9d6M: Downloading webpage
[youtube] HnMYghA9d6M: Extracting video information
[youtube] HnMYghA9d6M: Downloading DASH manifest
[download] Destination: Detroit Swindle - Brotherman [Freerange]-HnMYghA9d6M.m4a
[download] 100% of 11.95MiB in 00:02
[youtube] Post-process file Detroit Swindle - Brotherman [Freerange]-HnMYghA9d6M.m4a exists, skipping

$ youtube-dl --version
2015.01.16

**Comment by phihag** [comment]
YouTube serves m4a files with a weird header that iTunes does not support. youtube-dl 2015.01.23.4 and newer will automatically correct the header of the m4a file if ffmpeg is present on the system. I am therefore closing this issue. See [our FAQ](https://yt-dl.org/update) if you need help updating. Thank you for the report!

**Comment by jonathanfmorgan** [comment]
Thanks for the quick fix!
