### ISSUE TITLE
Using ffmpeg instead of avconv in conversion

### ISSUE THREAD

**Issue by beew** [rg3/youtube-dl#4770]
Hi, I used to be able to download  1080p dash videos from Youtube with a command like

youtube-dl -f 22+140 url --prefer-ffmpeg

But now I am getting error that says --prefer-ffmpeg command not found and youtube-dl insists on using avconv provided by Ubuntu which is outdated. I have the latest ffmpeg installed, how do I make youtube-dl use it instead of the outdated and crippled avconv provided by the system?  OS is Ubuntub 14.04.

Thanks.

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by phihag** [comment]
My crystal ball says that the URL contains an unquoted ampersand and is not put in quotes. With the `--verbose` output we'll be able to see what's happening here.

**Comment by beew** [comment]
Hi,

youtube-dl -f 22+140 https://www.youtube.com/watch?v=YIwuCs1Yovw&spfreload=10 --prefer-ffmpeg --verbose
[1] 13871
--prefer-ffmpeg: command not found
[youtube] YIwuCs1Yovw: Downloading webpage
bee@localhost:~/Downloads$ [youtube] YIwuCs1Yovw: Extracting video information
[youtube] YIwuCs1Yovw: Downloading DASH manifest
[download] Destination: TRANSFORMERS 4 OFFICIAL Trailer [HD 1080p]-YIwuCs1Yovw.f22.mp4
[download] 100% of 37.89MiB in 00:13
[download] Destination: TRANSFORMERS 4 OFFICIAL Trailer [HD 1080p]-YIwuCs1Yovw.f140.m4a
[download] 100% of 2.32MiB in 00:00
[ffmpeg] Merging formats into "TRANSFORMERS 4 OFFICIAL Trailer [HD 1080p]-YIwuCs1Yovw.mp4"
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
[1]+  Done                    youtube-dl -f 22+140 https://www.youtube.com/watch?v=YIwuCs1Yovw

BTW, the terminal didn't show that merging has finished. The last line only appear when I press return.

**Comment by dstftw** [comment]
As noticed by @phihag you have to escape `&` or enclose the URL into quotes as follows:
`youtube-dl -f 22+140 "https://www.youtube.com/watch?v=YIwuCs1Yovw&spfreload=10" --prefer-ffmpeg`

**Comment by beew** [comment]
Thanks. Putting url in quotes works.
