### ISSUE TITLE
WARNING: [youtube] wiWKZD0j62w: Skipping DASH manifest: ExtractorError

### ISSUE THREAD

**Issue by leogao** [rg3/youtube-dl#4774]
$~/youtube-dl https://www.youtube.com/watch?v=wiWKZD0j62w
[youtube] wiWKZD0j62w: Downloading webpage
[youtube] wiWKZD0j62w: Extracting video information
WARNING: [youtube] wiWKZD0j62w: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[download] Destination: Learn English vocabularies for Health, Home, and Community-wiWKZD0j62w.mp4
[download] 100% of 163.43MiB in 00:20

**Comment by naglis** [comment]
Please post the full output of the command when run with `--verbose` flag, as outlined [here](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md).

**Comment by dstftw** [comment]
Works fine with latest version.
