### ISSUE TITLE
can not upgrade youtube-dl on ubuntu

### ISSUE THREAD

**Issue by deng-kai** [rg3/youtube-dl#4778]
I use this command on my ubuntu 14.04 desktop:
sudo -H pip install --upgrade youtube_dl
then this is the result:
Collecting youtube-dl from https://pypi.python.org/packages/2.7/y/youtube_dl/youtube_dl-2015.01.23.4-py2.py3-none-any.whl#md5=88cab49c1d9667a4cacff354376b8d62
  Using cached youtube_dl-2015.01.23.4-py2.py3-none-any.whl
Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2015.1.15
    Can't uninstall 'youtube-dl'. No files were found to uninstall.
Successfully installed youtube-dl-2015.1.15

/usr/local/lib/python2.7/dist-packages/youtube_dl$ ls
aes.py      downloader    __main__.py    swfinterp.pyc  version.pyc
aes.pyc     extractor     __main__.pyc   update.py      YoutubeDL.py
cache.py    __init__.py   options.py     update.pyc     YoutubeDL.pyc
cache.pyc   __init__.pyc  options.pyc    utils.py
compat.py   jsinterp.py   postprocessor  utils.pyc
compat.pyc  jsinterp.pyc  swfinterp.py   version.py

command 
whereis youtube-dl : /usr/local/bin/youtube-dl

**Comment by jaimeMF** [comment]
How did you install `/usr/local/bin/youtube-dl` in the first place?

**Comment by deng-kai** [comment]
I don't know, and how to fix it.

**Comment by jaimeMF** [comment]
I guess you installed it with apt, if that's the case run `sudo apt-get remove -y youtube-dl`, if not you can try removing ` /usr/local/bin/youtube-dl`. Running the pip command after that should work.

**Comment by deng-kai** [comment]
I was not use apt-get to install youtube-dl. And in /usr/local/lib/python2.7/dist-packages/,  youtube-dl folder is existing./usr/local/bin/youtube-dl is an execute file
