### ISSUE TITLE
No sound - Newbie

### ISSUE THREAD

**Issue by Boinkjumper** [rg3/youtube-dl#4779]
I just found youtube-dl and ffmpeg and I have been trying to DL a show but it has no sound. I'm running it on a windows 7 box, and I have youtube-dl and ffmpeg in the same directory. 
Since I'm new to this I am not sure I am doing it right.

Command line in cmd prompt:

youtube-dl --recode-video mkv http://www.dr.dk/tv/se/moderne-klassikere/moderne-klassikere-one-republic-apologize#!/ ->still in mp4 and no sound
youtube-dl --audio-quality --audio-format http://www.dr.dk/tv/se/moderne-klassikere/moderne-klassikere-one-republic-apologize#!/ -> mp4 and no sound. 

Since I am not used to UNIX/Linux and I'm like a baby crawling atm and still trying figure out how to walk,- I feel I am lost here.
I am over my head atm..

Thx in advance.

cheers

BJ

**Comment by jaimeMF** [comment]
Could you post the full output of `youtube-dl --recode-video mkv http://www.dr.dk/tv/se/moderne-klassikere/moderne-klassikere-one-republic-apologize#!/ --verbose`? It will give us some useful information.

It's working for me with VLC and mpv, which player are you using?


About the second command, both `--audio-quality` and `--audio-format` require and argument (for example `--audio-format mp3`). Could you try running `youtube-dl --audio-format mp3 --extract-audio 'http://www.dr.dk/tv/se/moderne-klassikere/moderne-klassikere-one-republic-apologize#!/' --verbose` and post the output?

**Comment by Boinkjumper** [comment]
Hmm I am using VLC and no sound...I'll try your command

**Comment by Boinkjumper** [comment]
C:\Bin\ffmpeg\bin>youtube-dl --audio-format mp3 --extract-audio http://www.dr.dk
/tv/se/moderne-klassikere/moderne-klassikere-one-republic-apologize#!/ --verbose

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--audio-format', 'mp3', '--extract-audio', 'http://
www.dr.dk/tv/se/moderne-klassikere/moderne-klassikere-one-republic-apologize#!/'
, '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.01.23.4
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-69233-g1f13348, ffprobe N-69233-g1f13348
[debug] Proxy map: {}
[DRTV] moderne-klassikere-one-republic-apologize: Downloading video JSON
[debug] Invoking downloader on u'http://drod07k-vh.akamaihd.net/z/all/clear/stre
aming/47/54946b3e6187a2122c022b47/Moderne-Klassikere--One-Republ_f065c11881704cd
48573f7802a650980_,1126,562,248,.mp4.csmil/manifest.f4m?hdcore=3.3.0&plugin=aasp
-3.3.0.99.43'
[download] Moderne Klassikere - One Republic - Apologize-moderne-klassikere-one-
republic-apologize.mp4 has already been downloaded
[ffmpeg] Destination: Moderne Klassikere - One Republic - Apologize-moderne-klas
sikere-one-republic-apologize.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'Moderne Klassikere - One Republic - A
pologize-moderne-klassikere-one-republic-apologize.mp4' -vn -acodec libmp3lame -
aq 5 'Moderne Klassikere - One Republic - Apologize-moderne-klassikere-one-repub
lic-apologize.mp3'
Deleting original file Moderne Klassikere - One Republic - Apologize-moderne-kla
ssikere-one-republic-apologize.mp4 (pass -k to keep)

C:\Bin\ffmpeg\bin>

**Comment by Boinkjumper** [comment]
C:\Bin\ffmpeg\bin>youtube-dl --recode-video mkv http://www.dr.dk/tv/se/moderne-k
lassikere/moderne-klassikere-one-republic-apologize#!/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--recode-video', 'mkv', 'http://www.dr.dk/tv/se/mod
erne-klassikere/moderne-klassikere-one-republic-apologize#!/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.01.23.4
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-69233-g1f13348, ffprobe N-69233-g1f13348
[debug] Proxy map: {}
[DRTV] moderne-klassikere-one-republic-apologize: Downloading video JSON
[debug] Invoking downloader on u'http://drod07k-vh.akamaihd.net/z/all/clear/stre
aming/47/54946b3e6187a2122c022b47/Moderne-Klassikere--One-Republ_f065c11881704cd
48573f7802a650980_,1126,562,248,.mp4.csmil/manifest.f4m?hdcore=3.3.0&plugin=aasp
-3.3.0.99.43'
[download] Downloading f4m manifest
[download] Destination: Moderne Klassikere - One Republic - Apologize-moderne-kl
assikere-one-republic-apologize.mp4
[download] 100% of 234.11MiB in 00:56
[ffmpeg] Converting video from mp4 to mkv, Destination: Moderne Klassikere - One
 Republic - Apologize-moderne-klassikere-one-republic-apologize.mkv
[debug] ffmpeg command line: ffmpeg -y -i 'Moderne Klassikere - One Republic - A
pologize-moderne-klassikere-one-republic-apologize.mp4' 'Moderne Klassikere - On
e Republic - Apologize-moderne-klassikere-one-republic-apologize.mkv'
Deleting original file Moderne Klassikere - One Republic - Apologize-moderne-kla
ssikere-one-republic-apologize.mp4 (pass -k to keep)

**Comment by jaimeMF** [comment]
So, what happens if you try playing `Moderne Klassikere - One Republic - Apologize-moderne-klassikere-one-republic-apologize.mp3` or `Moderne Klassikere - One Republic - Apologize-moderne-klassikere-one-republic-apologize.mkv`?
If you still have no audio, could you run `youtube-dl http://www.dr.dk/tv/se/moderne-klassikere/moderne-klassikere-one-republic-apologize#!/` and post the output you get when these two commands:
*  `ffmpeg -y -i "Moderne Klassikere - One Republic - Apologize-moderne-klassikere-one-republic-apologize.mp4" -vn -acodec libmp3lame -
aq 5 "Moderne Klassikere - One Republic - Apologize-moderne-klassikere-one-republic-apologize.mp3"`
*  ` ffmpeg -y -i "Moderne Klassikere - One Republic - Apologize-moderne-klassikere-one-republic-apologize.mp4" "Moderne Klassikere - One Republic - Apologize-moderne-klassikere-one-republic-apologize.mkv"`.

**Comment by Boinkjumper** [comment]
There is sound now..woohoo. But for some reason there is a voiceover( some Artificial voice like SIRI) when there are subtitles?
Is it possible for me to remove that?

**Comment by jaimeMF** [comment]
Ok I thought that was the default, but I couldn't managed to get it when playing the video on their webpage. In the next  version, it will download by default the version without the voice.
Thanks for the report.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl version 2015.01.30.1 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
