### ISSUE TITLE
[lynda.com] ERROR: unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by lmcdougall** [rg3/youtube-dl#4782]
There are some courses that are not downloading. I am able to use it with some others and I get no errors but these are the messages I get:

[lynda] Logging in as username
[lynda] Confirming log in and log out from another device
[lynda] 83654: Downloading video JSON
ERROR: unable to download video data: HTTP Error 404: Not Found

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by dstftw** [comment]
This will be fixed in the next version. Thanks for the report.

**Comment by phihag** [comment]
The fix made it into youtube-dl 2015.01.25. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by lmcdougall** [comment]
Sorry I was using home-brew version which is not  2015.01.25!!!
This one worked.
Thanks.
