### ISSUE TITLE
Embedding youtube-dl: no suitable InfoExtractor

### ISSUE THREAD

**Issue by HanYOLO** [rg3/youtube-dl#4783]
I tried the example for embedding youtube-dl but I always get this error:

ERROR: no suitable InfoExtractor: http://www.youtube.com/watch?v=BaW_jenozKc
Traceback (most recent call last):
  File "ydl.py", line 5, in <module>
    ydl.download(['http://www.youtube.com/watch?v=BaW_jenozKc'])
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 771, in download
    videos = self.extract_info(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 430, in extract_info
    self.report_error(u'no suitable InfoExtractor: %s' % url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 291, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 266, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: no suitable InfoExtractor: http://www.youtube.com/watch?v=BaW_jenozKc

**Comment by jaimeMF** [comment]
Could you post the code you are using for calling youtube-dl and the version?
If you are using the code from https://github.com/rg3/youtube-dl/blob/master/README.md#embedding-youtube-dl, you may be using a version too old.

**Comment by HanYOLO** [comment]
I used that code from https://github.com/rg3/youtube-dl/blob/master/README.md#embedding-youtube-dl. My version : 2015.01.23.4

**Comment by jaimeMF** [comment]
Ok, what's the output you get if you run these two commands in the python interpreter (you have to run `python`):
```python
>>> import youtube_dl
>>> youtube_dl.version.__version__
```

**Comment by HanYOLO** [comment]
Thank You. You were right.
The command-line programm was version 2015.01.23.4, but the pythone package was an old one.

**Comment by jaimeMF** [comment]
I'm closing the issue then. If you have any other problem, feel free to open a new issue.
