### ISSUE TITLE
Suggestion for automatically changing the Grooveshark URL

### ISSUE THREAD

**Issue by hstracker90** [rg3/youtube-dl#4786]
Youtube-dl works great with Grooveshark.

I just want to suggest that when youtube-dl is started with a URL like
"http://grooveshark.com/s/..." (which will produce an 'Unsupport URL' error)
it is automatically changed to 
"http://grooveshark.com/#!/s/..." (which will start the download).

The shorter URL is provided by Grooveshark when you click on "Share" and then on "Copy".
The longer URL is provided when you visit the website of a song.

My suggestion would make it easier to collect the URLs of songs you want to download.

**Comment by yan12125** [comment]
Unfortunately Grooveshark was shut down yesterday. See the announcement at http://grooveshark.com/. Closing.
