### ISSUE TITLE
Add support for discogs.com

### ISSUE THREAD

**Issue by error800** [rg3/youtube-dl#4790]
Discogs has an embedded youtube player on artist and release pages. Would be cool to be able to download the files (and load as playlist into mpv ;))
Examples:
Release: http://www.discogs.com/Imatran-Voima-Commando/master/15295
Artist: http://www.discogs.com/artist/14858-Imatran-Voima

**Comment by naglis** [comment]
Note: discogs seems to block old user agents, in our case: `Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0 (Chrome)'`

**Comment by error800** [comment]
Youtube video ids can be found easily in the embedded iframe:
```html
<iframe id="youtube_player_placeholder" data-video-ids="s5e7CVlBs1I,eUpvJEbGz8w,Pg7_n730w7Y,PznniwG_51Q,8QaKFAaGQxo,2p4H5wB_PHs,ifHC_wCWnrA,R22BIVmgfMI,hjgM6b3gAPw,1Vv_yw9wfHA,qQXMcZMDGEE,oBr6_2qZngQ,exfnVLQPfig,qnEo8Fs3OgY,L5LQveHQBBk,uIUM7fzpoEo,cAIIhsZxCLo,dQ6EsOTy86Q,6jK2SvQR4aM,3dnqvDrzn98,b7XMFNe3lao,bCLZoEQ48OE" ...></iframe>
```

**Comment by jaimeMF** [comment]
We should maybe update the user agent to a more recent version, since probably there won't be any website that blocks it.

**Comment by error800** [comment]
Good idea.
Right now i have:
```
--user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0"
```
in ~/.config/youtube-dl/config

**Comment by jaimeMF** [comment]
It has been updated in 183139340b4841f22357fcf2b6a5ce2dedd71146, so you no longer need to change it in your config file.

**Comment by error800** [comment]
nice!
