### ISSUE TITLE
download udemy videos own section folder 

### ISSUE THREAD

**Issue by muhasturk** [rg3/youtube-dl#4793]
Hello, I would like to download udemy videos inside own section folders. Youtube-dl downloads all videos inside same folder.

https://yadi.sk/i/p8KHU35GeHSCt

**Comment by greatcityness** [comment]
You may download udemy videos with Allavsoft.

It also download videos from MySpace, Google Video, Yahoo Video, Break.com and other more that 750+ video websites.

**Comment by yan12125** [comment]
@muhasturk https://yadi.sk/i/p8KHU35GeHSCt is gone. ("Nothing found") If you have another example, please propose it here and I'll reopen the issue.

**Comment by dstftw** [comment]
The original request was to be able to put downloads in separate folders by course chapters, e.g. https://www.udemy.com/java-tutorial/#/lecture/172757
```
~/Downloads/Chapter 1 - Introduction/
    Lecture 1 - Introduction and Installation
    Lecture 2 - What Java Is and How It Works
    Lecture 3 - Getting a Job and What to Study After Completing Basic Java
    ....
~/Chapter 2 - Programming Core Java
    Lecture 6 - A Hello World Program
    ...
```

**Comment by greatcityness** [comment]
It works very good.

**Comment by dstftw** [comment]
This feature will be supported in the next version via output template.
Example: `youtube-dl -o '%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' -u user -p pass https://www.udemy.com/java-tutorial/`.
