### ISSUE TITLE
Certain Twitch.tv URL Format Errors

### ISSUE THREAD

**Issue by elithrar** [rg3/youtube-dl#4795]
http://www.twitch.tv/venruki/v/3729961

It seems any Twitch URL with a `/v/` in the route isn't handled by youtube-dl, despite the Twitch extractor covering this case:

```
~/Desktop youtube-dl http://www.twitch.tv/venruki/v/3729961
[generic] 3729961: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3729961: Downloading webpage
[generic] 3729961: Extracting information
ERROR: Unsupported URL: http://www.twitch.tv/venruki/v/3729961; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

I'm using the latest version via Homebrew - compiled from HEAD (not the bottled version):
```
~/Desktop youtube-dl --version
2014.10.15
/usr/local/Cellar/youtube-dl/HEAD(master ✔) git rev-parse HEAD
fd3e4f7a8a349e95f8159f3a20c9318b05f90a87
```

From what I can see it *should* work as [the code covers this URL format](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/twitch.py#L167-L174) but am not sure why it's falling back to the generic downloader.

**Comment by jaimeMF** [comment]
You are using an outdated version, it works fine with 2015.01.25. For future reports, please post the output of `youtube-dl --verbose http://www.twitch.tv/venruki/v/3729961` (see the [bug reporting instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs), it will also print the version, so you won't need an additional `youtube-dl --version`.

By the way: I don't know if that's what you intended, but `/usr/local/Cellar/youtube-dl/HEAD(master ✔) git rev-parse HEAD` prints the commit for Homebrew, the git repo for youtube-dl is not there.
