### ISSUE TITLE
yahoo movie missing video tag

### ISSUE THREAD

**Issue by chzuping** [rg3/youtube-dl#4798]
youtube-dl -g https://www.yahoo.com/movies/ewan-mcgregor-on-humanizing-jesus-and-the-devil-in-109235316912.html
ERROR: Yahoo returned error: missing video tag

**Comment by dstftw** [comment]
I can't see any related video on this page. What do you expect youtube-dl to download?

**Comment by chzuping** [comment]
Thanks for your replay!
