### ISSUE TITLE
Youtube throwing errors.....

### ISSUE THREAD

**Issue by bigmacca1** [rg3/youtube-dl#4799]
Script started on Wed 28 Jan 2015 16:28:05 GMT
#7#]2;ian@sauron:~/Downloads##]1;sauron##8ian@sauron:~/Downloads> exit####ls -lart########./youtube-dl --verbose  https://www.youtube.com/watch?hl=
=en-GB&v=Zk2OLaGpxWY&gl=GB >> capture##[K##[K##[K##[K##[K##[K##[K##[K##[K##[K##[K
[1] 10849
[2] 10850
[2]+  Done                    v=Zk2OLaGpxWY
#7#]2;ian@sauron:~/Downloads##]1;sauron##8ian@sauron:~/Downloads> [debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?hl=en-GB']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.25
[debug] Python version 2.7.8 - Linux-3.16.7-7-default-i686-with-SuSE-13.2-i586
[debug] exe versions: ffmpeg 2.3.6, ffprobe 2.3.6
[debug] Proxy map: {}
[generic] watch?hl=en-GB: Requesting header
[redirect] Following redirect to https://www.youtube.com/supported_browsers?next_url=%2F
[download] Downloading playlist: supported_browsers
[youtube:user] supported_browsers: Downloading video ids from 1 to 51
#[0;31mERROR:#[0m Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "./youtube-dl/youtube_dl/extractor/common.py", line 299, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1571, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

exit

Script done on Wed 28 Jan 2015 16:28:20 GMT

**Comment by dstftw** [comment]
You have to escape ampersands or enclose the URL in quotes as follows:
`./youtube-dl --verbose "https://www.youtube.com/watch?hlen-GB&v=Zk2OLaGpxWY&gl=GB"`

**Comment by bigmacca1** [comment]
Hi Thanks for that. Never have in the past...just right click-dragged
across and pasted it straight on the end. Didn't know it had changed.

Thanks again!

Ian McKinnon

Regards

Ian McKinnon
Silverdale Sapphires

**Comment by bigmacca1** [comment]
HI
Did it and it worked. When did the format change?

Ian McKinnon


Regards

Ian McKinnon
Silverdale Sapphires

**Comment by phihag** [comment]
This is not a working in youtube-dl, but in your shell. I believe this format did change with the addition of background processes with `&`, probably sometime in the 80es (1989 at the lastest).

Most likely, you just had the luck to never have URLs that contain ampersands.

youtube-dl just gets an incomplete URL. We're keeping a list of common mistakes and I've added your URL to that list.
