### ISSUE TITLE
Youtube download links expire

### ISSUE THREAD

**Issue by bassrock** [rg3/youtube-dl#480]
Is there a way to get a youtube download link that does not expire or is this a security feature by youtube?

**Comment by fjgui** [comment]
Maybe the best way is when you need the url and avoid the url expire, you pull new url everytime likes :youtube-dl -gf 18 https://www.youtube.com/watch?v=dc66rRymXuQ

**Comment by BishopT** [comment]
Hi there. I'm also annoyed by the expiration. My use case is too build playlist for VLC from youtube playlists. But I can listen for music maybe couple of hours, then I need to rebuild the playlist, reload on VLC...
