### ISSUE TITLE
Can't download videos that have id starting with dash (-)

### ISSUE THREAD

**Issue by stelonix** [rg3/youtube-dl#4800]
youtube-dl "-wNyEUrxzFU"
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: -N

**Comment by dstftw** [comment]
You have two options:
- Separate video id by double dash: `youtube-dl -- "-wNyEUrxzFU"`
- Use full URL: `youtube-dl "http://www.youtube.com/watch?v=-wNyEUrxzFU"`
