### ISSUE TITLE
Add support for 3sat.de/mediathek/

### ISSUE THREAD

**Issue by tremd** [rg3/youtube-dl#4804]
Example:
http://www.3sat.de/mediathek/?mode=play&obj=29776

**Comment by naglis** [comment]
We do already support 3sat.de/mediathek/. Please make sure you enclose the URL with quotes (the ampersand symbol in the URL has a special meaning for most shells), when you run youtube-dl:
```bash
youtube-dl 'http://www.3sat.de/mediathek/?mode=play&obj=29776'
```

If you still experience problems after that, please post the full output of:
```bash
youtube-dl -v 'http://www.3sat.de/mediathek/?mode=play&obj=29776'
```

**Comment by tremd** [comment]
my fault :/ thank you
