### ISSUE TITLE
Downloading YT channel or playlist - store previously downloaded video IDs

### ISSUE THREAD

**Issue by Crypto2** [rg3/youtube-dl#4806]
It would be a nice feature if youtube-dl could have an option to maintain a list of successfully downloaded video IDs from YouTube in a text file or sqlite DB or something, it would save a lot of time and website calls downloading whole channels or playlists instead of probing each video to see if it has been downloaded or not. (ie. if there is an error and youtube-dl stops or if someone is just keeping a local backup of the channel/playlist and wants to run youtube-dl nightly/weekly or something like that.)

I'd do it myself, but I don't know Python.

**Comment by jaimeMF** [comment]
I don't know if you have already found it, but `--download-archive` is probably what you are looking for.
