### ISSUE TITLE
Cannot download from following site

### ISSUE THREAD

**Issue by solosza** [rg3/youtube-dl#4808]
dondada@netboook:~$ youtube-dl -U
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
dondada@netboook:~$ youtube-dl http://www.deansinsider.com/livecast/
[generic] : Requesting header
WARNING: Falling back on generic information extractor.
[generic] : Downloading webpage
[generic] : Extracting information
[vimeo] 117985806: Downloading webpage
[vimeo] 117985806: Extracting information
ERROR: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
dondada@netboook:~$ youtube-dl --verbose http://www.deansinsider.com/livecast/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.deansinsider.com/livecast/']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[generic] : Requesting header
WARNING: Falling back on generic information extractor.
[generic] : Downloading webpage
[generic] : Extracting information
[vimeo] 117985806: Downloading webpage
[vimeo] 117985806: Extracting information
ERROR: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/vimeo.py", line 198, in _real_extract
    config = json.loads(config)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 3 - line 1 column 178 (char 2 - 177)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/vimeo.py", line 208, in _real_extract
    cause=e)
ExtractorError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by solosza** [comment]
Updated to 2015.01.25 version fixed the issue.

**Comment by solosza** [comment]
Updated to 2015.01.25 version fixed the issue.

**Comment by jaimeMF** [comment]
I didn't even test it. I have noticed you were using an outdated version, but didn't realized it was nearly 1 year old :).

**Comment by solosza** [comment]
Every time I try and update it it tells me that I have to update from software center or something. I just cannot use --update. Any clue how I can get past this?  I'm using Ubuntu. 


Sent via the Samsung Galaxy Note® 3, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Jaime Marquínez Ferrándiz <notifications@github.com> </div><div>Date:01/29/2015  12:25 AM  (GMT-10:00) </div><div>To: rg3/youtube-dl <youtube-dl@noreply.github.com> </div><div>Cc: solosza <solosza@yahoo.com> </div><div>Subject: Re: [youtube-dl] Cannot download from following site (#4808) </div><div>
</div>I didn't even test it. I have noticed you were using an outdated version, but didn't realized it was nearly 1 year old :).

**Comment by iggyvolz** [comment]
https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl
