### ISSUE TITLE
[spike.com] Add subtitles support

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#4811]
I tried "youtube-dl --list-subs http://www.linktovideo.com", but youtube-dl just downloads the videos. I expected the command to list all available subtitles.

The exact URL is:  http://www.spike.com/episodes/amptue/the-joe-schmo-show-schmo-in-the-wild-season-1-ep-103.

Thus the exact command is 
 youtube-dl --list-subs http://www.spike.com/episodes/amptue/the-joe-schmo-show-schmo-in-the-wild-season-1-ep-103

If you go to the URL in a web browser, you'll see that closed captions are an option.

**Comment by dstftw** [comment]
Thanks for the report, captions extraction capability will be available in the next version.

**Comment by phihag** [comment]
youtube-dl 2015.02.02 and newer add support for spike subtitles. See [our FAQ](https://yt-dl.org/update) if you need help updating.
