### ISSUE TITLE
Commit ec82d85 breaks --write-thumbnail.

### ISSUE THREAD

**Issue by Hajitorus** [rg3/youtube-dl#4812]
If I check out commit cfb56d1, `--write-thumbnail` will correctly record thumbnails, as in:

	% ~git/youtube-dl/youtube-dl --write-thumbnail --download-archive=/dev/null KAZrNrcgrRc
	[youtube] KAZrNrcgrRc: Downloading webpage
	[youtube] KAZrNrcgrRc: Extracting video information
	[youtube] KAZrNrcgrRc: Downloading DASH manifest
	[youtube] KAZrNrcgrRc: Downloading thumbnail ...
	[youtube] KAZrNrcgrRc: Writing thumbnail to: Handmade Hero Day 053 - Environment Elements as Entities-KAZrNrcgrRc.jpg
	[download] Handmade Hero Day 053 - Environment Elements as Entities-KAZrNrcgrRc.mp4 has already been downloaded
	[ffmpeg] Not converting video file Handmade Hero Day 053 - Environment Elements as Entities-KAZrNrcgrRc.mp4 - already is in target format mp4

However, reverting to any commit more recent than that, (like `HEAD`) will not write thumbnails:

	% ~git/youtube-dl/youtube-dl --write-thumbnail --download-archive=/dev/null KAZrNrcgrRc
	[youtube] KAZrNrcgrRc: Downloading webpage
	[youtube] KAZrNrcgrRc: Extracting video information
	[youtube] KAZrNrcgrRc: Downloading DASH manifest
	[download] Handmade Hero Day 053 - Environment Elements as Entities-KAZrNrcgrRc.mp4 has already been downloaded
	[ffmpeg] Not converting video file Handmade Hero Day 053 - Environment Elements as Entities-KAZrNrcgrRc.mp4 - already is in target format mp4

This appears to be directly related to the changes made in ec82d85.

**Comment by jaimeMF** [comment]
Thansk for the report, it will work again in the next version (or if you want, you can just use the HEAD version).

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl version 2015.01.30.1 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
