### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by k0ral** [rg3/youtube-dl#4816]
#4807 was diagnosed on FreeBSD. As suggested, I'm reporting the same issue on ArchLinux.
However, I've installed youtube-dl through [nix][1], you may want to investigate as if I were running NixOS.

Cc @jaimeMF .

Here is the verbose output:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--no-check-certificate', 'https://www.youtube.com/watch?v=pKzhNZGG1AM']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.25
[debug] Python version 2.7.9 - Linux-3.18.2-2-ARCH-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] pKzhNZGG1AM: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))
  File "/home/koral/.nix-profile/bin/youtube-dl/youtube_dl/extractor/common.py", line 299, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/koral/.nix-profile/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1571, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/nix/store/g4zbmgjdg7nd0z1cf3ixas6rxp874zlh-python-2.7.9/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/nix/store/g4zbmgjdg7nd0z1cf3ixas6rxp874zlh-python-2.7.9/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/nix/store/g4zbmgjdg7nd0z1cf3ixas6rxp874zlh-python-2.7.9/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/koral/.nix-profile/bin/youtube-dl/youtube_dl/utils.py", line 659, in https_open
    req)
  File "/nix/store/g4zbmgjdg7nd0z1cf3ixas6rxp874zlh-python-2.7.9/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
```

[1]: http://nixos.org/nix/

**Comment by arisboch** [comment]
Did you try using '--no-check-certificate' as a temporary workaround?

**Comment by k0ral** [comment]
As indicated in the logs above, yes, I've tried using the `--no-check-certificate` option, in vain.

**Comment by phihag** [comment]
Can you retry with youtube-dl 2015.01.30.1 and newer? I believe `--no-check-certificate` should be fixed in there. Of course, it's quite curious why cert validations fails in the first place.

**Comment by jaimeMF** [comment]
After installing python3 and python 2 with nix (on OSX), with the latest version of youtube-dl `--no-check-certificate` seems to be fixed. If you set and export the variable `SSL_CERT_FILE` to the path of your CA bundle (if you installed the cacert package, you can use `~/.nix-profile/etc/ca-bundle.crt`), the CA certificates are properly loaded and `--no-check-certificate` is not needed.

**Comment by k0ral** [comment]
I confirm your diagnosis and treatment :) . Thank you.

**Comment by justa9** [comment]
The compiled binaries (32-bit, Windows XP) for the last two versions produce an error when trying to access youtube. 

```
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
```

Both official and locally-compiled binaries were tested to no avail.

"--no-check certificate" works as expected, but since it's not recommended, I was wondering whether there was more to that.

Last working compiled version was "2015.10.18".

**Comment by yan12125** [comment]
@justa9 Please open a new issue. This problem varies among operating systems so it's considered a different problem.

**Comment by jadedh** [comment]
I've encountered the same problem. Installed youtube-dl with
`pip3 install youtube-dl`

Then got the error when I did : sudo youtube-dl [URL]

`ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)> (caused by URLError(SSLError
[3]   Exit 1                  sudo youtube-dl https://www.youtube.com/watch?v=19ecwVEvI-0
`

Fixing the command to 
`sudo youtube-dl --no-check-certificate https://www.youtube.com/watch?v=19ecwVEvI-0&feature=youtu.be&app=desktop
`
solved my problem.
I was running the code on Mac OS

**Comment by yan12125** [comment]
@jadedh: Sounds like https://github.com/rg3/youtube-dl/issues/11943#issuecomment-276947670 can help. In general --no-check-certificate is not necessary, and it's not recommended to run youtube-dl with sudo.

**Comment by akiraaisha** [comment]
This works on me. Clearing SSL Cache.
Internet Options->Content->Clear SSL State

**Comment by adolfintel** [comment]
I'm having this issue on Windows 10 when downloading from Youtube. Clearing the SSL cache doesn't help.
I don't know what's the cause. Updating youtube-dl doesn't solve the issue, but it works on my other PC.

**Comment by yan12125** [comment]
Check out https://github.com/rg3/youtube-dl/issues/7309#issuecomment-172354527

**Comment by adolfintel** [comment]
@yan12125 I have no google certificates

**Comment by xingheng** [comment]
@jadedh `sudo`? Why?

**Comment by JayRizzo** [comment]
FYI - to fix this please see https://stackoverflow.com/a/42334357/1896134

This seems to be a problem for 3.6 & 3.7 details listed in the SO answer.

In short, try this
===

`pip3 install certifi`
Then 
`/Applications/Python\ 3.7/Install\ Certificates.command`

Your `terminal` should look something like this:
===
```
$ pip3 install certifi
Collecting certifi
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Installing collected packages: certifi
Successfully installed certifi-2018.11.29


$ /Applications/Python\ 3.7/Install\ Certificates.command
 -- pip install --upgrade certifi
Requirement already up-to-date: certifi in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (2018.11.29)
 -- removing any existing file or link
 -- creating symlink to certifi certificate bundle
 -- setting permissions
 -- update complete


```

**Comment by bspammer** [comment]
Putting this here for anyone else who's as inattentive as me:

Deactivate your virtual environment

**Comment by Shaglock** [comment]
`$ /Applications/Python\ 2.7/Install\ Certificates.command`
This helped me

**Comment by ParhaZz** [comment]
> FYI - to fix this please see https://stackoverflow.com/a/42334357/1896134
> 
> This seems to be a problem for 3.6 & 3.7 details listed in the SO answer.
> 
> # In short, try this
> `pip3 install certifi`
> Then
> `/Applications/Python\ 3.7/Install\ Certificates.command`
> 
> # Your `terminal` should look something like this:
> ```
> $ pip3 install certifi
> Collecting certifi
>   Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
> Installing collected packages: certifi
> Successfully installed certifi-2018.11.29
> 
> 
> $ /Applications/Python\ 3.7/Install\ Certificates.command
>  -- pip install --upgrade certifi
> Requirement already up-to-date: certifi in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (2018.11.29)
>  -- removing any existing file or link
>  -- creating symlink to certifi certificate bundle
>  -- setting permissions
>  -- update complete
> ```

tysm this helped me

**Comment by albertputinjobs** [comment]
I found an alternative using docker https://hub.docker.com/r/wernight/youtube-dl
