### ISSUE TITLE
Channel 10 - tenplay.com.au Not Working

### ISSUE THREAD

**Issue by itzeddie** [rg3/youtube-dl#4818]
When trying to use TenPlay I get an error:

C:\rtmpdump>youtube-dl.exe http://tenplay.com.au/channel-ten/the-project/2015/1/29
[TenPlay] http://tenplay.com.au/channel-ten/the-project/2015/1/29: Downloading webpage
[TenPlay] The Project, Thursday 29 January: Downloading JSON metadata
[download] Destination: The Project, Thursday 29 January-4019616399001.flv
[rtmpdump] 0 bytes

ERROR: rtmpdump exited with code 1

When running with verbose I get all of this;

http://pastebin.com/v5PZCiUN

**Comment by remitamine** [comment]
the link in the issue is not available, but other videos from the same website works fine.
