### ISSUE TITLE
Please add support for historicfilms.com

### ISSUE THREAD

**Issue by clampak** [rg3/youtube-dl#4825]
http://www.historicfilms.com/tapes/4728_0_2096

Cheers-

**Comment by Qfulsher** [comment]
How do you get to a video's "tapes" page (page with just the video and info) rather than the popup video player when you search for something?

**Comment by dstftw** [comment]
HistoricFilms will be supported in the next version. Thanks for the report.

**Comment by clampak** [comment]
Thanks!

**Comment by phihag** [comment]
youtube-dl 2015.02.02.2 and newer now include HistoricFilms support. See [our FAQ](https://yt-dl.org/update) if you need help updating.
