### ISSUE TITLE
download von das erste- mediathek

### ISSUE THREAD

**Issue by eckifolki** [rg3/youtube-dl#4826]
Bei Download vom ersten Programm/Mediathek kommt immer Fehlermeldung. Wäre nett, wenn dieser Fehler zu beheben wäre. Hier der Text aus dem Terminal:
»folki@folkinet:~$ youtube-dl "http://mediathek.daserste.de/Sportschau-live/Ski-alpin-Abfahrt-der-Herren/Das-Erste/Video?documentId=25912190&topRessort=tv&bcastId=723230"
[ARD] 25912190: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
folki@folkinet:~$ 
«
(PS: youtube-dl -U funktioniert bei mir nicht)

**Comment by eckifolki** [comment]
Sorry, I forgot writing in English. You see the issue at the terminal output

**Comment by jaimeMF** [comment]
Works fine for me, could you post the full output of `youtube-dl --verbose "http://mediathek.daserste.de/Sportschau-live/Ski-alpin-Abfahrt-der-Herren/Das-Erste/Video?documentId=25912190&topRessort=tv&bcastId=723230"`?

**Comment by eckifolki** [comment]
Thanks very much. I got an email by Phillip Hagemeister, referring the other issue, what did not work (updating) - There were links posted in that email, I could follow to deinstall youtube-dl with apt-get and made a new install with the other link - code:
sudo wget https://yt-dl.org/latest/youtube-dl -O /usr/local/bin/youtube-dl
sudo chmod a+x /usr/local/bin/youtube-dl
hash -r
____I am so thankful, because now it works. May be, my former installation with apt-get had mistakes, that had the effect, what not worked with das erste mediathek.
So thanks a lot and c u

I include the terminal output:
folki@folkinet:~$ sudo wget https://yt-dl.org/latest/youtube-dl -O /usr/local/bin/youtube-dl
--2015-02-01 05:46:38--  https://yt-dl.org/latest/youtube-dl
Auflösen des Hostnamen »yt-dl.org (yt-dl.org)«... 95.143.172.170, 2001:1a50:11:0:5f:8f:acaa:177
Verbindungsaufbau zu yt-dl.org (yt-dl.org)|95.143.172.170|:443... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 763892 (746K) [application/octet-stream]
In »»/usr/local/bin/youtube-dl«« speichern.

100%[==================================================================================================================>] 763.892      949KB/s   in 0,8s   

2015-02-01 05:46:39 (949 KB/s) - »»/usr/local/bin/youtube-dl«« gespeichert [763892/763892]

folki@folkinet:~$ sudo chmod a+x /usr/local/bin/youtube-dl
folki@folkinet:~$ hash -r
folki@folkinet:~$ sudo youtube-dl -U
youtube-dl is up-to-date (2015.01.30.2)
folki@folkinet:~$ youtube-dl "http://mediathek.daserste.de/Sportschau-live/Ski-alpin-die-Abfahrt-der-Damen/Das-Erste/Video?documentId=25878892&topRessort=tv&bcastId=723230"
[ARD:mediathek] 25878892: Downloading webpage
[ARD:mediathek] 25878892: Downloading JSON metadata
[download] Destination: Ski alpin - die Abfahrt der Damen-25878892.mp4
[download] 100% of 669.19MiB in 09:54
folki@folkinet:~$ youtube-dl --verbose "http://mediathek.daserste.de/Sportschau-live/Ski-alpin-Abfahrt-der-Herren/Das-Erste/Video?documentId=25912190&topRessort=tv&bcastId=723230"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://mediathek.daserste.de/Sportschau-live/Ski-alpin-Abfahrt-der-Herren/Das-Erste/Video?documentId=25912190&topRessort=tv&bcastId=723230']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.30.2
[debug] Python version 2.7.6 - Linux-3.13.0-44-generic-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[ARD:mediathek] 25912190: Downloading webpage
[ARD:mediathek] 25912190: Downloading JSON metadata
[debug] Invoking downloader on u'http://ondemand-ww.wdr.de/medstdp/fsk0/61/615552/615552_6532180.mp4'
[download] Destination: Ski alpin - Abfahrt der Herren-25912190.mp4
[download] 37.2% of 808.06MiB at 964.25KiB/s ETA 08:34
