### ISSUE TITLE
-U is not working

### ISSUE THREAD

**Issue by eckifolki** [rg3/youtube-dl#4827]
folki@folkinet:~$ youtube-dl -U
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
folki@folkinet:~$

**Comment by phihag** [comment]
How did you install youtube-dl? `youtube-dl -U` won't work if your files are under the control of a package manager (such as apt-get or pip) or if you are running it from source.

See [our FAQ about updating](https://yt-dl.org/update) for ways to switch to the binary installation method, which does support youtube-dl.

Since this issue is missing the [required information for a good bug report](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md) - namely the output you get when you add `--verbose` to your command line - we cannot possibly help you in fixing this issue. Therefore, I am closing it. Please do post the output you get with `--verbose`, and mention how you installed youtube-dl. We'll then reopen this issue. Thanks!

**Comment by eckifolki** [comment]
Absender Volkmar Eckardt, Pliensäckerstraße 23, 70437 Stuttgart, 071194568881, 015253940732, volkey@gmx.de, volkey@mail.com


Hello Philipp,

I have Ubuntu 14.04.1 running,

I first gave »youtube-dl« with a link into the terminal - a text followed, it were not installed, to install .... I followed the text to install - may be it was »sudo aptget --install youtube-dl«

 

folki@folkinet:~$ youtube-dl -U --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-U', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-44-generic-i686-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
folki@folkinet:~$

 

Thanks and sincerely Yours

Volkmar

PS: I am not very familiar with the closer stuff of IT technic and codes and stuff

 

Gesendet: Samstag, 31. Januar 2015 um 20:09 Uhr
Von: "Philipp Hagemeister" <notifications@github.com>
An: rg3/youtube-dl <youtube-dl@noreply.github.com>
Cc: eckifolki <volkey@gmx.de>
Betreff: Re: [youtube-dl] -U is not working (#4827)


How did you install youtube-dl? youtube-dl -U won't work if your files are under the control of a package manager (such as apt-get or pip) or if you are running it from source.

See our FAQ about updating for ways to switch to the binary installation method, which does support youtube-dl.

Since this issue is missing the required information for a good bug report - namely the output you get when you add --verbose to your command line - we cannot possibly help you in fixing this issue. Therefore, I am closing it. Please do post the output you get with --verbose, and mention how you installed youtube-dl. We'll then reopen this issue. Thanks!

**Comment by eckifolki** [comment]
folki@folkinet:~$ youtube-dl -U --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-U', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-44-generic-i686-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
folki@folkinet:~$ sudo apt-get remove -y youtube-dl
[sudo] password for folki: 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  latex-beamer latex-xcolor libao-common libao4 libav-tools libavdevice53
  libavfilter3 libpoppler-qt4-4 libqt4-qt3support libquvi-scripts libquvi7
  linux-headers-3.13.0-32 linux-headers-3.13.0-32-generic
  linux-image-3.13.0-32-generic linux-image-extra-3.13.0-32-generic pgf
  prosper ps2eps rtmpdump texlive-extra-utils texlive-font-utils
  texlive-generic-recommended texlive-latex-base texlive-latex-base-doc
  texlive-latex-recommended texlive-latex-recommended-doc texlive-pstricks
  texlive-pstricks-doc
Verwenden Sie »apt-get autoremove«, um sie zu entfernen.
Die folgenden Pakete werden ENTFERNT:
  youtube-dl
0 aktualisiert, 0 neu installiert, 1 zu entfernen und 10 nicht aktualisiert.
Nach dieser Operation werden 1.106 kB Plattenplatz freigegeben.
(Lese Datenbank ... 431321 Dateien und Verzeichnisse sind derzeit installiert.)
Entfernen von youtube-dl (2014.02.17-1) ...
Trigger für man-db (2.6.7.1-1ubuntu1) werden verarbeitet ...
folki@folkinet:~$ apt-get autoremove
E: Sperrdatei /var/lib/dpkg/lock konnte nicht geöffnet werden. - open (13: Keine Berechtigung)
E: Sperren des Administrationsverzeichnisses (/var/lib/dpkg/) nicht möglich, sind Sie root?
folki@folkinet:~$ sudo apt-get autoremove
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden Pakete werden ENTFERNT:
  latex-beamer latex-xcolor libao-common libao4 libav-tools libavdevice53
  libavfilter3 libpoppler-qt4-4 libqt4-qt3support libquvi-scripts libquvi7
  linux-headers-3.13.0-32 linux-headers-3.13.0-32-generic
  linux-image-3.13.0-32-generic linux-image-extra-3.13.0-32-generic pgf
  prosper ps2eps rtmpdump texlive-extra-utils texlive-font-utils
  texlive-generic-recommended texlive-latex-base texlive-latex-base-doc
  texlive-latex-recommended texlive-latex-recommended-doc texlive-pstricks
  texlive-pstricks-doc
0 aktualisiert, 0 neu installiert, 28 zu entfernen und 10 nicht aktualisiert.
Nach dieser Operation werden 521 MB Plattenplatz freigegeben.
Möchten Sie fortfahren? [J/n] j
(Lese Datenbank ... 431071 Dateien und Verzeichnisse sind derzeit installiert.)
Entfernen von latex-beamer (3.24-1) ...
Entfernen von prosper (1.00.4+cvs.2007.05.01-4) ...
Running 'mktexlsr /usr/share/texmf /var/lib/texmf'.
This may take some time... done.
Entfernen von texlive-pstricks (2013.20140215-2) ...
Entfernen von pgf (2.10-1) ...
Entfernen von latex-xcolor (2.11-1.1) ...
Entfernen von libao4:i386 (1.1.0-2ubuntu2) ...
Entfernen von libao-common (1.1.0-2ubuntu2) ...
Entfernen von libav-tools (6:9.16-0ubuntu0.14.04.1) ...
Entfernen von libavdevice53:i386 (6:9.16-0ubuntu0.14.04.1) ...
Entfernen von libavfilter3:i386 (6:9.16-0ubuntu0.14.04.1) ...
Entfernen von libpoppler-qt4-4:i386 (0.24.5-2ubuntu4.2) ...
Entfernen von libqt4-qt3support:i386 (4:4.8.5+git192-g085f851+dfsg-2ubuntu4) ...
Entfernen von libquvi7:i386 (0.4.1-1ubuntu3) ...
Entfernen von libquvi-scripts (0.4.21-1) ...
Entfernen von linux-headers-3.13.0-32-generic (3.13.0-32.57) ...
Entfernen von linux-headers-3.13.0-32 (3.13.0-32.57) ...
Entfernen von linux-image-extra-3.13.0-32-generic (3.13.0-32.57) ...
Examining /etc/kernel/postrm.d .
run-parts: executing /etc/kernel/postrm.d/initramfs-tools 3.13.0-32-generic /boot/vmlinuz-3.13.0-32-generic
update-initramfs: Deleting /boot/initrd.img-3.13.0-32-generic
run-parts: executing /etc/kernel/postrm.d/zz-update-grub 3.13.0-32-generic /boot/vmlinuz-3.13.0-32-generic
Grub-Konfigurationsdatei wird generiert …
Warnung: Setting GRUB_TIMEOUT to a non-zero value when GRUB_HIDDEN_TIMEOUT is set is no longer supported.
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-44-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-44-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-43-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-43-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-41-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-41-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-40-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-40-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-39-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-39-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-37-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-37-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-34-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-34-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-33-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-33-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-32-generic
Found memtest86+ image: /boot/memtest86+.elf
Found memtest86+ image: /boot/memtest86+.bin
erledigt
Entfernen von linux-image-3.13.0-32-generic (3.13.0-32.57) ...
Examining /etc/kernel/postrm.d .
run-parts: executing /etc/kernel/postrm.d/initramfs-tools 3.13.0-32-generic /boot/vmlinuz-3.13.0-32-generic
update-initramfs: Deleting /boot/initrd.img-3.13.0-32-generic
run-parts: executing /etc/kernel/postrm.d/zz-update-grub 3.13.0-32-generic /boot/vmlinuz-3.13.0-32-generic
Grub-Konfigurationsdatei wird generiert …
Warnung: Setting GRUB_TIMEOUT to a non-zero value when GRUB_HIDDEN_TIMEOUT is set is no longer supported.
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-44-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-44-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-43-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-43-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-41-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-41-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-40-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-40-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-39-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-39-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-37-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-37-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-34-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-34-generic
Linux-Abbild gefunden: /boot/vmlinuz-3.13.0-33-generic
initrd-Abbild gefunden: /boot/initrd.img-3.13.0-33-generic
Found memtest86+ image: /boot/memtest86+.elf
Found memtest86+ image: /boot/memtest86+.bin
erledigt
Entfernen von ps2eps (1.68-1build1) ...
Entfernen von rtmpdump (2.4+20121230.gitdf6c518-1) ...
Entfernen von texlive-extra-utils (2013.20140215-2) ...
Entfernen von texlive-font-utils (2013.20140215-2) ...
Entfernen von texlive-generic-recommended (2013.20140215-1) ...
Entfernen von texlive-latex-recommended (2013.20140215-1) ...
Entfernen von texlive-latex-base (2013.20140215-1) ...
Entfernen von texlive-latex-base-doc (2013.20140215-1) ...
Entfernen von texlive-latex-recommended-doc (2013.20140215-1) ...
Entfernen von texlive-pstricks-doc (2013.20140215-2) ...
Trigger für doc-base (0.10.5) werden verarbeitet ...
3 doc-base-Dateien entfernt wird verarbeitet …
Dokumente werden mit scrollkeeper registriert...
Trigger für tex-common (4.04) werden verarbeitet ...
Running mktexlsr. This may take some time... done.
Running updmap-sys. This may take some time... done.
Running mktexlsr /var/lib/texmf ... done.
Trigger für man-db (2.6.7.1-1ubuntu1) werden verarbeitet ...
Trigger für libc-bin (2.19-0ubuntu6.5) werden verarbeitet ...
Trigger für install-info (5.2.0.dfsg.1-2) werden verarbeitet ...
folki@folkinet:~$ sudo wget https://yt-dl.org/latest/youtube-dl -O /usr/local/bin/youtube-dl
--2015-02-01 05:46:38--  https://yt-dl.org/latest/youtube-dl
Auflösen des Hostnamen »yt-dl.org (yt-dl.org)«... 95.143.172.170, 2001:1a50:11:0:5f:8f:acaa:177
Verbindungsaufbau zu yt-dl.org (yt-dl.org)|95.143.172.170|:443... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 763892 (746K) [application/octet-stream]
In »»/usr/local/bin/youtube-dl«« speichern.

100%[==================================================================================================================>] 763.892      949KB/s   in 0,8s   

2015-02-01 05:46:39 (949 KB/s) - »»/usr/local/bin/youtube-dl«« gespeichert [763892/763892]

folki@folkinet:~$ sudo chmod a+x /usr/local/bin/youtube-dl
folki@folkinet:~$ hash -r
folki@folkinet:~$ sudo youtube-dl -U
youtube-dl is up-to-date (2015.01.30.2)
folki@folkinet:~$ youtube-dl "http://mediathek.daserste.de/Sportschau-live/Ski-alpin-die-Abfahrt-der-Damen/Das-Erste/Video?documentId=25878892&topRessort=tv&bcastId=723230"
[ARD:mediathek] 25878892: Downloading webpage
[ARD:mediathek] 25878892: Downloading JSON metadata
[download] Destination: Ski alpin - die Abfahrt der Damen-25878892.mp4
[download] 100% of 669.19MiB in 09:54
folki@folkinet:~$ youtube-dl --verbose "http://mediathek.daserste.de/Sportschau-live/Ski-alpin-Abfahrt-der-Herren/Das-Erste/Video?documentId=25912190&topRessort=tv&bcastId=723230"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://mediathek.daserste.de/Sportschau-live/Ski-alpin-Abfahrt-der-Herren/Das-Erste/Video?documentId=25912190&topRessort=tv&bcastId=723230']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.30.2
[debug] Python version 2.7.6 - Linux-3.13.0-44-generic-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[ARD:mediathek] 25912190: Downloading webpage
[ARD:mediathek] 25912190: Downloading JSON metadata
[debug] Invoking downloader on u'http://ondemand-ww.wdr.de/medstdp/fsk0/61/615552/615552_6532180.mp4'
[download] Destination: Ski alpin - Abfahrt der Herren-25912190.mp4
[download] 100% of 808.06MiB in 13:27
folki@folkinet:~$

**Comment by phihag** [comment]
Excellent, thanks for the feedback, and great to see it's working now!
