### ISSUE TITLE
BBC iPlayer "Could not download the whole video" issue

### ISSUE THREAD

**Issue by narmon** [rg3/youtube-dl#4828]
Not sure if this temporary, but I thought it best to report it here anyway. I will update this if the problem disappears, or doesn't.

No problem watching BBC iPlayer in my browser and I have updated youtube-dl today. All was fine yesterday. 

Here's what I'm getting:

C:\Users\narmon\Documents\Shared Folder\youtube-dl>youtube-dl "http://www.bbc.c
o.uk/iplayer/episode/b0516zch/room-101-series-4-episode-5"
[bbc.co.uk] b0516zch: Downloading video page
[bbc.co.uk] b0516zch: Downloading JSON metadata
[bbc.co.uk] b0516zbj: Downloading media selection XML
[bbc.co.uk] b0516zbj: Downloading captions
[download] Destination: Room 101-b0516zbj.flv
[download]   9.3% of ~517.64MiB at  2.22MiB/s ETA 03:28
[rtmpdump] 50478756 bytes
[download]   9.7% of ~512.37MiB at  1.21MiB/s ETA 04:38
[rtmpdump] 52114243 bytes
[download]  10.3% of ~514.95MiB at  1.31MiB/s ETA 06:00
[rtmpdump] 55616555 bytes
[download]  10.7% of ~518.65MiB at  1.34MiB/s ETA 07:18
[rtmpdump] 58191020 bytes
[download]  16.3% of ~509.66MiB at  2.24MiB/s ETA 03:07
[rtmpdump] 87110337 bytes
[download]  16.3% of ~509.66MiB at 714.62KiB/s ETA 05:07
[rtmpdump] Could not download the whole video. This can happen for some advertis
ements.
[rtmpdump] 87110337 bytes

NB there are no adverts on BBC iPlayer!

**Comment by narmon** [comment]
This programme: 
http://www.bbc.co.uk/iplayer/episode/b00vf52b/the-slammer-series-3-6-who-is-the-governor
has a short trail for another programme before it; rtmpdump quits with code 1 after 0 bytes. Maybe a different issue though?

This morning I was able to d/l this: http://www.bbc.co.uk/iplayer/episode/b00vjbwt/the-slammer-series-3-7-slammer-power and this http://www.bbc.co.uk/iplayer/episode/p02gfy74/wolf-hall-1-three-card-trick but still not this: http://www.bbc.co.uk/iplayer/episode/b050rbzb/kraftwerk-pop-art

**Comment by dstftw** [comment]
Post the **full** outputs you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).
You can try downloading from different content supplier by specifying format code to `-f`. See `-F` for the full list.

**Comment by narmon** [comment]
OK...

youtube-dl "http://www.bbc.co.uk/iplayer/episode/b00vf52b/the-slammer-series-3-6-who-is-the-governor" --verbose

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.bbc.co.uk/iplayer/episode/b00vf52b/the-slammer-series-3-6-who-is-the-governor', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.01.30.2
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] b00vf52b: Downloading video page
[bbc.co.uk] b00vf52b: Downloading JSON metadata
[bbc.co.uk] b00vf4xs: Downloading media selection XML
[bbc.co.uk] b00vf4xs: Downloading captions
[debug] Invoking downloader on u'rtmp://iplayertokfs.fplive.net/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDIwMjE1MDQxMSZlbmRfdGltZT0yMDE1MDIwMjE5MDQxMSZkaWdlc3Q9Yzg3NTI3NzRlOTM3ODRlZDAyZWJkNjBmZjdmMWQzMDY='
[download] Destination: The Slammer-b00vf4xs.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmp://iplayertokfs.fplive.net/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDIwMjE1MDQxMSZlbmRfdGltZT0yMDE1MDIwMjE5MDQxMSZkaWdlc3Q9Yzg3NTI3NzRlOTM3ODRlZDAyZWJkNjBmZjdmMWQzMDY=' -o 'The Slammer-b00vf4xs.flv.part' --swfVfy http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf --pageUrl http://www.bbc.co.uk --app 'iplayertok?token=c3RhcnRfdGltZT0yMDE1MDIwMjE1MDQxMSZlbmRfdGltZT0yMDE1MDIwMjE5MDQxMSZkaWdlc3Q9Yzg3NTI3NzRlOTM3ODRlZDAyZWJkNjBmZjdmMWQzMDY=' --playpath mp4:3200kbps/modav/bUnknown-450cd758-d35d-4ef6-886a-b66e6da01248_b00vf4xs_1421779187504
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Parsed app     : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDIwMjE1MDQxMSZlbmRfdGltZT0yMDE1MDIwMjE5MDQxMSZkaWdlc3Q9Yzg3NTI3NzRlOTM3ODRlZDAyZWJkNjBmZjdmMWQzMDY=
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:3200kbps/modav/bUnknown-450cd758-d35d-4ef6-886a-b66e6da01248_b00vf4xs_1421779187504
[rtmpdump] DEBUG: tcUrl    : rtmp://iplayertokfs.fplive.net:1935/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDIwMjE1MDQxMSZlbmRfdGltZT0yMDE1MDIwMjE5MDQxMSZkaWdlc3Q9Yzg3NTI3NzRlOTM3ODRlZDAyZWJkNjBmZjdmMWQzMDY=
[rtmpdump] DEBUG: swfUrl   : http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf
[rtmpdump] DEBUG: pageUrl  : http://www.bbc.co.uk
[rtmpdump] DEBUG: app      : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDIwMjE1MDQxMSZlbmRfdGltZT0yMDE1MDIwMjE5MDQxMSZkaWdlc3Q9Yzg3NTI3NzRlOTM3ODRlZDAyZWJkNjBmZjdmMWQzMDY=
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: b6 74 7f 89 f9 ec 6a 60 c1 a4 b5 8b b1 18 b0 fa
[rtmpdump] DEBUG: 65 18 86 24 c2 8a 1a a3 2f 72 0f 0b 80 59 dd 7f
[rtmpdump] DEBUG: SWFSize  : 595316
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 03
[rtmpdump] DEBUG: HandShake: Client digest offset: 53
[rtmpdump] DEBUG: HandShake: Initial client digest:
[rtmpdump] DEBUG: 8d 2d a2 ac c1 49 9b 9d 39 11 83 96 93 c0 9e 1e
[rtmpdump] DEBUG: a9 2d 02 ae 58 6a 5a 64 1d db 39 83 ce a5 42 db
[rtmpdump] DEBUG: HandShake: Type Answer   : 03
[rtmpdump] DEBUG: HandShake: Server Uptime : 1033467266
[rtmpdump] DEBUG: HandShake: FMS Version   : 4.5.3.1
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server digest:
[rtmpdump] DEBUG: b2 bd 7d c0 ae c7 06 41 9b 4f 61 4d 3b f8 67 c4
[rtmpdump] DEBUG: a2 38 a2 d9 f1 6b 01 45 b6 64 f8 6c 06 81 64 74
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: 6e fe 2f 3b 09 47 86 0c 68 4d 50 da e6 c6 6b d4
[rtmpdump] DEBUG: 82 b8 00 11 a2 8d cd 1a 11 0a 3c 46 f7 6c 21 12
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: 9d cd 04 5f 8e 15 ef a8 12 5b 98 3a f1 2b 0d 50
[rtmpdump] DEBUG: 64 61 6d a3 03 0e ab 2b 5d 2b 86 1e 36 42 f4 c1
[rtmpdump] DEBUG: HandShake: Digest key:
[rtmpdump] DEBUG: eb 47 87 a5 2c f2 fd 7b c3 e8 52 36 e7 18 a5 98
[rtmpdump] DEBUG: a8 b4 da b5 39 24 b3 65 b9 e0 74 8b b1 44 87 e6
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: 9d cd 04 5f 8e 15 ef a8 12 5b 98 3a f1 2b 0d 50
[rtmpdump] DEBUG: 64 61 6d a3 03 0e ab 2b 5d 2b 86 1e 36 42 f4 c1
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 2500000
[rtmpdump] DEBUG: HandleClientBW: client BW = 2500000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 16384
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 240 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:  FMS/4,5,3,101>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:  255.00>
[rtmpdump] DEBUG: Property: <Name:               mode, NUMBER:  1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetConnection.Connect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Connection succeeded.>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:  0.00>
[rtmpdump] DEBUG: Property: <Name:               data, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            version, STRING:  4,5,3,101>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 21 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWDone>
[rtmpdump] DEBUG: Invoking _checkbw
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: mp4:3200kbps/modav/bUnknown-450cd758-d35d-4ef6-886a-b66e6da01248_b00vf4xs_1421779187504
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 16419 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 16384
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 121 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  error>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetStream.Failed>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  206 Partial Content>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:  rAA9gQLA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Failed
[rtmpdump] ERROR: Closing connection: NetStream.Failed
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Parsed app     : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDIwMjE1MDQxMSZlbmRfdGltZT0yMDE1MDIwMjE5MDQxMSZkaWdlc3Q9Yzg3NTI3NzRlOTM3ODRlZDAyZWJkNjBmZjdmMWQzMDY=
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:3200kbps/modav/bUnknown-450cd758-d35d-4ef6-886a-b66e6da01248_b00vf4xs_1421779187504
[rtmpdump] DEBUG: tcUrl    : rtmp://iplayertokfs.fplive.net:1935/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDIwMjE1MDQxMSZlbmRfdGltZT0yMDE1MDIwMjE5MDQxMSZkaWdlc3Q9Yzg3NTI3NzRlOTM3ODRlZDAyZWJkNjBmZjdmMWQzMDY=
[rtmpdump] DEBUG: swfUrl   : http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf
[rtmpdump] DEBUG: pageUrl  : http://www.bbc.co.uk
[rtmpdump] DEBUG: app      : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDIwMjE1MDQxMSZlbmRfdGltZT0yMDE1MDIwMjE5MDQxMSZkaWdlc3Q9Yzg3NTI3NzRlOTM3ODRlZDAyZWJkNjBmZjdmMWQzMDY=
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: b6 74 7f 89 f9 ec 6a 60 c1 a4 b5 8b b1 18 b0 fa
[rtmpdump] DEBUG: 65 18 86 24 c2 8a 1a a3 2f 72 0f 0b 80 59 dd 7f
[rtmpdump] DEBUG: SWFSize  : 595316
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.


ERROR: rtmpdump exited with code 1
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 382, in main
  File "youtube_dl\__init__.pyo", line 372, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1349, in download
  File "youtube_dl\YoutubeDL.pyo", line 629, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 675, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1107, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1282, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1257, in dl
  File "youtube_dl\downloader\common.pyo", line 316, in download
  File "youtube_dl\downloader\rtmp.pyo", line 204, in real_download
  File "youtube_dl\downloader\common.pyo", line 151, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 504, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 466, in trouble





+ Here's the list of formats:

youtube-dl "http://www.bbc.co.uk/iplayer/episode/b00vf52b/the-slammer-series-3-6-who-is-the-governor" -F

[bbc.co.uk] b00vf52b: Downloading video page
[bbc.co.uk] b00vf52b: Downloading JSON metadata
[bbc.co.uk] b00vf4xs: Downloading media selection XML
[bbc.co.uk] b00vf4xs: Downloading captions
[info] Available formats for b00vf4xs:
format code                               extension resolution  note
iplayer_streaming_h264_flv_lo_akamai      flv       640x360     h264@ 480k, 103.
27MiB (worst)
iplayer_streaming_h264_flv_lo_limelight   flv       640x360     h264@ 480k, 103.
27MiB
iplayer_streaming_h264_flv_akamai         flv       640x360     h264@ 796k, 161.
39MiB
iplayer_streaming_h264_flv_limelight      flv       640x360     h264@ 796k, 161.
39MiB
iplayer_streaming_h264_flv_high_akamai    flv       832x468     h264@1500k, 302.
02MiB
iplayer_streaming_h264_flv_high_limelight flv       832x468     h264@1500k, 302.
02MiB
pc_streaming_hd_akamai                    flv       1280x720    h264@2800k, 482.
80MiB
pc_streaming_hd_level3                    flv       1280x720    h264@2800k, 482.
80MiB (best)

I just get "ERROR: requested format not available" when I try to choose any of these. Unless -my -syntax -is -wrong; can you please paste in the exact command I should use?

**Comment by narmon** [comment]
Tried 3 more added to iPlayer within last 24 hours:

Succeeded:
http://www.bbc.co.uk/iplayer/episode/b00vn02h/the-slammer-series-3-8-gov-on-the-run
http://www.bbc.co.uk/iplayer/episode/b0522yyx/only-connect-series-10-20-qi-elves-v-coders

Failed:
http://www.bbc.co.uk/iplayer/episode/b0520zv0/university-challenge-20142015-episode-27

**Comment by narmon** [comment]
OK...
youtube-dl -f pc_streaming_hd_akamai
works on some I couldn't d/l, albeit at a fifth of the speed...
