### ISSUE TITLE
[info needed] highest dash video and dash audio merge

### ISSUE THREAD

**Issue by muhasturk** [rg3/youtube-dl#4837]
I have a playlist that I would like to download all video with highest dash video and dash audio and merge them with avconv.

But the highest video and audio of some video on playlist is 1280x720, some of them 1920x1080.

Is there any option such as;

`youtube-dl -f` **[Highest DASH Video]+[Highest DASH Audio]**`[playlist-url]`

**Comment by phihag** [comment]
There is no specific format for DASH, but you can simply use `-f bestvideo+bestaudio`. I'm a little bit puzzled because that's precisely what the [documentation for `-f`](https://github.com/rg3/youtube-dl/blob/master/README.md#video-format-options) mentions. Can you suggest how we could reword it?
