### ISSUE TITLE
Error while trying to download.

### ISSUE THREAD

**Issue by lusers** [rg3/youtube-dl#4839]
% youtube-dl --verbose --restrict-filenames 'http://www.tv4play.se/iframe/video/3054113?starttime=55'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--restrict-filenames', 'http://www.tv4play.se/iframe/video/3054113?starttime=55']
[debug] Encodings: locale ISO8859-1, fs ISO8859-1, out ISO8859-1, pref ISO8859-1
[debug] youtube-dl version 2014.11.24
[debug] Python version 2.7.9 - FreeBSD-9.3-PRERELEASE-amd64-64bit-ELF
[debug] exe versions: ffmpeg 2.3.6, ffprobe 2.3.6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 3054113?starttime=55: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3054113?starttime=55: Downloading webpage
[generic] 3054113?starttime=55: Extracting information
ERROR: Unsupported URL: http://www.tv4play.se/iframe/video/3054113?starttime=55; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 609, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1360, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 12, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 553, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 240, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 996, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.tv4play.se/iframe/video/3054113?starttime=55; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

% youtube-dl -U
Usage: youtube-dl [options] url [url...]

youtube-dl: error: no such option: -U

**Comment by lusers** [comment]
FreeBSD 9.3-PRERELEASE #1 r266465

**Comment by lusers** [comment]
Python 2.7.9

**Comment by naglis** [comment]
Support for tv4.se/tv4play.se has been added and should be available in the next release of youtube-dl. Thanks for the report.

**Comment by phihag** [comment]
Support for tv4.se hsa made it into youtube-dl 2015.02.21. See [our FAQ](https://yt-dl.org/update) if you have trouble updating.
