### ISSUE TITLE
YouTube shows not downloading

### ISSUE THREAD

**Issue by gophercall** [rg3/youtube-dl#4841]
youtube-dl isn't properly collecting video IDs for YouTube show channels if there are no "seasons" registered.

I tried `youtube-dl https://www.youtube.com/show/allyourhistory/videos` and no videos were downloaded. Log attached below.

```
[youtube:show] allyourhistory/videos: Downloading show webpage
[youtube:show] allyourhistory/videos: Found 0 seasons
[download] Downloading playlist: All Your History
[youtube:show] playlist All Your History: Collected 0 video ids (downloading 0 of them)
```

I also tried another "show" channel `$ youtube-dl https://www.youtube.com/show/101east/videos --dateafter 20150101` and no videos were downloaded. The intended effect was to download videos published after 2015/01/01.

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.youtube.com/show/101east/videos', '--da
teafter', '20150101', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.02.02
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-67999-gd0879a9, ffprobe N-67999-gd0879a9
[debug] Proxy map: {}
[youtube:show] 101east/videos: Downloading show webpage
[youtube:show] 101east/videos: Found 0 seasons
[download] Downloading playlist: 101 East
[youtube:show] playlist 101 East: Collected 0 video ids (downloading 0 of them)
```

It is possible to manually each download episode by copying and pasting a direct YouTube link though you can't use video selectors (`--playlist-start`, `--dateafter`, `--match-title` etc) or download in bulk.

YouTube URLs I tested which are not working are:
https://www.youtube.com/show/allyourhistory/videos
https://www.youtube.com/show/101east/videos
https://www.youtube.com/show/wwe/videos
https://www.youtube.com/show/topgear/videos

Selected YouTube shows are free to view and not geo-blocked.

**Comment by jaimeMF** [comment]
Fixed by @remitamine in #6782, thanks for the report.
