### ISSUE TITLE
ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info

### ISSUE THREAD

**Issue by shakeyourbunny** [rg3/youtube-dl#4842]
I tried to download the Angry Video Game Nerds Movie, which he published some days ago, video URL is http://www.youtube.com/watch?v=xAaS9O19GII

```
$ youtube-dl -U
Updating to version 2015.02.02 ...
Updated youtube-dl. Restart youtube-dl to use the new version.

$ youtube-dl --verbose -t "http://www.youtube.com/watch?v=xAaS9O19GII"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-t', 'http://www.youtube.com/watch?v=xAaS9O19GII']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.02
[debug] Python version 2.7.3 - Linux-3.2.0-4-686-pae-i686-with-debian-7.8
[debug] exe versions: avconv 0.8.16-6, avprobe 0.8.16-6, ffmpeg 0.8.16-6, ffprobe 0.8.16-6
[debug] Proxy map: {}
[youtube] xAaS9O19GII: Downloading webpage
[youtube] xAaS9O19GII: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/pulaski/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 619, in extract_info
    ie_result = ie.extract(url)
  File "/home/pulaski/bin/youtube-dl/youtube_dl/extractor/common.py", line 267, in extract
    return self._real_extract(url)
  File "/home/pulaski/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1075, in _real_extract
    raise ExtractorError('no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')
ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by dderek60** [comment]
I get the same problem.

$ youtube-dl --verbose -t "http://www.youtube.com/watch?v=xAaS9O19GII"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-t', 'http://www.youtube.com/watch?v=xAaS9O19GII']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.11
[debug] Python version 2.7.6 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] xAaS9O19GII: Downloading webpage
[youtube] xAaS9O19GII: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 633, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 270, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1077, in _real_extract
    raise ExtractorError('no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')
ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Rental videos are not supported: #359.
