### ISSUE TITLE
Slow "Setting language" among other steps.

### ISSUE THREAD

**Issue by qzio** [rg3/youtube-dl#4843]
I see extreme slow response times from youtube-dl when I'm connecting through a openvpn tunnel.

I have no problem what so ever with using https://youtube.com, the site is snappy, videos loads quickly etc.

I was told in https://github.com/rg3/youtube-dl/issues/4413#issuecomment-72439066 to submit this as a separate issue.

the -4 and the -C option gave me

    youtube-dl: error no such option

However, setting the socket-timeout to 2 seems to actually fix the issue. now it just takes me 10 seconds to get to the "extracting video information" part.

Without it, it takes up to 15 minutes to complete the first three steps. (until extract video information)

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. See [our FAQ](https://yt-dl.org/update) if you need help updating. I'd greatly appreciate if you could post the output you get with `-v` and `-4`.

**Comment by qzio** [comment]
Managed to build and use the 2015.02.02.1 tag.

using -v -4

```

./youtube-dl --version
2015.02.02.1

 ./youtube-dl -v -4 'https://www.youtube.com/watch?v=oEHXfdo3nq4'                                       
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-4', 'https://www.youtube.com/watch?v=oEHXfdo3nq4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.02.1
[debug] Git HEAD: 869b4ae
[debug] Python version 2.7.6 - Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, rtmpdump 2.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[youtube] oEHXfdo3nq4: Downloading webpage
[youtube] oEHXfdo3nq4: Extracting video information
[youtube] oEHXfdo3nq4: Downloading DASH manifest

```

*HOLY SHIT THE SPEEEEDZ!*

I guess this have something to do with ipv6 and my vpn provider.

**Comment by qzio** [comment]
Closing this since the problem is probably not within youtube-dl.
