### ISSUE TITLE
Put description metadata in the id3v2 "comment" field

### ISSUE THREAD

**Issue by NelsonSR** [rg3/youtube-dl#4847]
I've noticed the last days that now, using the ``--add-metadata`` option, youtube-dl retrieve the URL and the description of the videos ("comments" and "desc" fields, respectively), that's really nice, but it's completely pointless to put some metadata in a field that some video players won't display in a properties card.

For example, in VLC player (one of the most popular around) will display the "comments" field, but not the "desc" field, and for some kind of videos (screencasts, for example) that one is more important than the URL where the video is (or was) located. I don't know if iTunes display it.

So I suggest to put the description of the video in the comments field, and the URL in some other field like "purl" (podcast URL).

**Comment by phihag** [comment]
Thanks, I've implemented exactly what you suggested, and it now shows up great in vlc. See [our FAQ](https://yt-dl.org) if you need help to update to youtube-dl 2015.02.03 or newer, where this is implemented.

**Comment by NelsonSR** [comment]
Yeah, I'm seeing it now and it looks great! thanks so much. 

By the way, the "purl" field isn't being written (I don't need it, actually, but I thought i was part of the implementation).
