### ISSUE TITLE
Error downloading from nfl.com

### ISSUE THREAD

**Issue by iggyvolz** [rg3/youtube-dl#4848]
I am using 2015.01.30.2 - the latest tagged in homebrew.  I don't believe this should be a problem, but if it has been fixed since then I am sorry.  I did not find any commits, issues, or PR's related to nfl since this release was tagged.

Gist of output: https://gist.github.com/iggyvolz/8e4a71a871a2c2216ad8

Looks like the source of the NFL page was modified... if I get a chance I'll try and look into this.

**Comment by jaimeMF** [comment]
Thanks for the report, it will work in the next version.

**Comment by phihag** [comment]
youtube-dl 2015.02.02.4 and newer add support for NFL article pages. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by iggyvolz** [comment]
Thank you!
