### ISSUE TITLE
Add Support For nerdist.com

### ISSUE THREAD

**Issue by goldensun87** [rg3/youtube-dl#4851]
Please add support for nerdist.com, if possible.

C:\Users\Naved\Desktop>youtube-dl -F http://www.nerdist.com/vepisode/exclusive-which-dc-characters-w
ill-be-on-tnts-the-titans/
[generic] exclusive-which-dc-characters-will-be-on-tnts-the-titans: Requesting header
WARNING: Falling back on generic information extractor.
[generic] exclusive-which-dc-characters-will-be-on-tnts-the-titans: Downloading webpage
[generic] exclusive-which-dc-characters-will-be-on-tnts-the-titans: Extracting information
ERROR: Unsupported URL: http://www.nerdist.com/vepisode/exclusive-which-dc-characters-will-be-on-tnt
s-the-titans/

**Comment by phihag** [comment]
Thank you for the report. youtube-dl 2015.02.02.4 and newer add support for nerdist.com . See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by goldensun87** [comment]
@phihag Thank you for the update.
