### ISSUE TITLE
pip reports wrong installed version when updating youtube-dl

### ISSUE THREAD

**Issue by clampak** [rg3/youtube-dl#4852]
I don't know if this is a pip or a youtube-dl issue, but the last thing that pip reports is that it has installed the version that it just uninstalled.

    $ pip install -U youtube-dl
    Collecting youtube-dl from https://pypi.python.org/packages/2.7/y/youtube_dl/youtube_dl-2015.02.02py2.py3-none-any.whl#md5=3a383cc3717ede90ef59ca79529ce382
      Downloading youtube_dl-2015.02.02-py2.py3-none-any.whl (804kB)
        100% |################################| 806kB 238kB/s
    Installing collected packages: youtube-dl
      Found existing installation: youtube-dl 2015.1.16
        Uninstalling youtube-dl-2015.1.16:
          Successfully uninstalled youtube-dl-2015.1.16
    
    Successfully installed youtube-dl-2015.1.16
    
    $ youtube-dl --version
    2015.02.02

**Comment by jaimeMF** [comment]
I have downloaded the wheel and it seems to be fine. Have you miscopied the output?, https://pypi.python.org/packages/2.7/y/youtube_dl/youtube_dl-2015.02.02py2.py3-none-any.whl#md5=3a383cc3717ede90ef59ca79529ce382 gives me a 404 error not found (https://pypi.python.org/packages/2.7/y/youtube_dl/youtube_dl-2015.02.02-py2.py3-none-any.whl#md5=3a383cc3717ede90ef59ca79529ce382 seems to be the correct one).

**Comment by clampak** [comment]
I did miscopy the output, you're right.  Must've hit the backspace or something while formatting it.  Still, just tried it again and got the same: 
```
$ pip install -U youtube-dl
Collecting youtube-dl from https://pypi.python.org/packages/2.7/y/youtube_dl/youtube_dl-2015.02.03-py2.py3-none-any.whl#md5=a368c55cc033e4ac8a34b29545c468d8
  Downloading youtube_dl-2015.02.03-py2.py3-none-any.whl (808kB)
    100% |################################| 811kB 187kB/s
Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2015.1.16
    Uninstalling youtube-dl-2015.1.16:
      Successfully uninstalled youtube-dl-2015.1.16

Successfully installed youtube-dl-2015.1.16

$ youtube-dl --version
2015.02.03
```

So is it a pip issue?

**Comment by jaimeMF** [comment]
I guess, I have installed youtube-dl 2015.1.16, then I run `pip install -U youtube-dl` and  it prints `Successfully installed youtube-dl-2015.2.3.1`. (I'm using pip 6.0.7)

**Comment by clampak** [comment]
I don't know what happened, but I updated pip (6.0.6 -> 6.0.7) and successively ran `pip install -U youtube-dl --no-cache-dir` 3 times in a row.  All 3 times it gave me this: 

`Downloading youtube_dl-2015.02.03.1-py2.py3-none-any.whl`

but the installation was different:

1st run:
```
    Successfully uninstalled youtube-dl-2015.1.16
Successfully installed youtube-dl-2015.1.25
```
2nd run:
```
    Successfully uninstalled youtube-dl-2015.1.25
Successfully installed youtube-dl-2015.2.2
```
3rd run:
```
    Successfully uninstalled youtube-dl-2015.2.2
Successfully installed youtube-dl-2015.2.3.1
```
I guess things are ok now, but what the heck?

**Comment by jaimeMF** [comment]
It could be the same as https://github.com/pypa/pip/issues/2382 (I also got it when upgrading pip)
