### ISSUE TITLE
ERROR: Unable to extract video URL;

### ISSUE THREAD

**Issue by s-verma** [rg3/youtube-dl#4855]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', '--verbose', 'http://www.viki.com/videos/1048879v-ankhon-dekhi']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.03.1
[debug] Python version 2.7.8 - Linux-3.16.0-4-amd64-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 11-6, avprobe 11-6, ffmpeg 2.4.3-1, ffprobe 2.4.3-1, rtmpdump 2.4
[debug] Proxy map: {'ftp': 'http://proxy62.iitd.ernet.in:3128/', 'http': 'http://proxy62.iitd.ernet.in:3128/', 'https': 'http://proxy62.iitd.ernet.in:3128/'}
[viki] 1048879v: Downloading webpage
[viki] 1048879v: Downloading info page
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 619, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 268, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/viki.py", line 60, in _real_extract
    r'<source[^>]+src="([^"]+)"', info_webpage, 'video URL')
  File "./youtube-dl/youtube_dl/extractor/common.py", line 534, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 524, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Thanks for the report. youtube-dl will support this video in the next version.
