### ISSUE TITLE
Adding support for KissAnime

### ISSUE THREAD

**Issue by dinosaurfiles** [rg3/youtube-dl#4856]
Im adding support for kissanime.com but it seems that my code doesnt exactly work like it should be.. :(

Kissanime has embedded links for downloadable videos as shown here 
Sample link. http://kissanime.com/Anime/Noragami/Episode-001?id=61729
![screenshot from 2015-02-03 20 59 22](https://cloud.githubusercontent.com/assets/10389490/6020521/cf672782-abe7-11e4-890d-24d3e15b159b.png)

**Comment by phihag** [comment]
Can you provide a source that shows that KissAnime is allowed to distribute the content they do? I cannot find any sign that they are. Please refer to [our FAQ](https://yt-dl.org/faq-anime) on the matter.
