### ISSUE TITLE
Downloading fails with "Signature extraction failed"

### ISSUE THREAD

**Issue by cdhowie** [rg3/youtube-dl#4857]
This happens on the latest master (12f0454cd60ffa67b57a822b2e30461cb761040d).  I was on an older version and got this same error so I pulled today and ran `python setup.py build` in case it was resolved in an update, but apparently it's not resolved yet.

(Note that `./youtube-dl.py` is a symlink to `youtube-dl` in the root of the Git repository.)

    $ ./youtube-dl.py --verbose -F https://www.youtube.com/watch?v=b_RjndG0IX8
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['--verbose', '-F', 'https://www.youtube.com/watch?v=b_RjndG0IX8']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2014.10.02
    [debug] Python version 2.7.3 - Linux-3.2.0-4-686-pae-i686-with-debian-7.8
    [debug] Proxy map: {}
    [youtube] Setting language
    [youtube] Confirming age
    [youtube] b_RjndG0IX8: Downloading webpage
    [youtube] b_RjndG0IX8: Downloading video info webpage
    [youtube] b_RjndG0IX8: Extracting video information
    [youtube] b_RjndG0IX8: Encrypted signatures detected.
    [youtube] {22} signature length 42.44, html5 player en_US-vflljBsG4
    [youtube] b_RjndG0IX8: Downloading js player vflljBsG4
    ERROR: Signature extraction failed: Traceback (most recent call last):
      File "./youtube-dl.py/youtube_dl/extractor/youtube.py", line 532, in _decrypt_signature
        video_id, player_url, s
      File "./youtube-dl.py/youtube_dl/extractor/youtube.py", line 446, in _extract_signature_function
        res = self._parse_sig_js(code)
      File "./youtube-dl.py/youtube_dl/extractor/youtube.py", line 507, in _parse_sig_js
        'Initial JS player signature function name')
      File "./youtube-dl.py/youtube_dl/extractor/common.py", line 416, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
     (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.',)); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
    Traceback (most recent call last):
      File "./youtube-dl.py/youtube_dl/extractor/youtube.py", line 532, in _decrypt_signature
        video_id, player_url, s
      File "./youtube-dl.py/youtube_dl/extractor/youtube.py", line 446, in _extract_signature_function
        res = self._parse_sig_js(code)
      File "./youtube-dl.py/youtube_dl/extractor/youtube.py", line 507, in _parse_sig_js
        'Initial JS player signature function name')
      File "./youtube-dl.py/youtube_dl/extractor/common.py", line 416, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
    Traceback (most recent call last):
      File "./youtube-dl.py/youtube_dl/YoutubeDL.py", line 524, in extract_info
        ie_result = ie.extract(url)
      File "./youtube-dl.py/youtube_dl/extractor/common.py", line 191, in extract
        return self._real_extract(url)
      File "./youtube-dl.py/youtube_dl/extractor/youtube.py", line 927, in _real_extract
        encrypted_sig, video_id, player_url, age_gate)
      File "./youtube-dl.py/youtube_dl/extractor/youtube.py", line 542, in _decrypt_signature
        'Signature extraction failed: ' + tb, cause=e)
    ExtractorError: Signature extraction failed: Traceback (most recent call last):
      File "./youtube-dl.py/youtube_dl/extractor/youtube.py", line 532, in _decrypt_signature
        video_id, player_url, s
      File "./youtube-dl.py/youtube_dl/extractor/youtube.py", line 446, in _extract_signature_function
        res = self._parse_sig_js(code)
      File "./youtube-dl.py/youtube_dl/extractor/youtube.py", line 507, in _parse_sig_js
        'Initial JS player signature function name')
      File "./youtube-dl.py/youtube_dl/extractor/common.py", line 416, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
     (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.',)); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
You are still running an outdated version as stated in log:
>[debug] youtube-dl version 2014.10.02

Feel free to open a new issue if you can reproduce this behavior with the actual latest version that is 2015.02.03.1 at the moment. Refer to [our FAQ](https://yt-dl.org/update) if you have trouble updating.

**Comment by cdhowie** [comment]
*facepalm*

Yup, that was it.  `git clean -fdx` showed me that the build product changed its output directory and so I was using the old one without knowing it.  (Apparently since my last update, the top-level script lives in `bin`.)

My bad.
