### ISSUE TITLE
progress hook not called on some videos

### ISSUE THREAD

**Issue by xantares** [rg3/youtube-dl#4860]
hello,
I'm writing a GUI to browse/download some videos (https://github.com/xantares/maxitube) based on yt-dl.
I'm trying to display the progress of the download, but on some videos (from canalplus for example) the progress hook is only called at the end of download (although I can see the curses progress percentage in the console) with the 'finished' state:
http://www.canalplus.fr/c-divertissement/c-le-petit-journal/pid6515-le-petit-journal.html?vid=1206051
whereas on some other sites the progress hook is called with the percentage of progress along with the 'downloading' state:
http://www.goldenmoustache.com/le-lab-la-drogue-arthur-laloux-56283/
any clue ?

**Comment by phihag** [comment]
This is a bug / missing feature. I'll leave this issue open as a feature request (for hook support in the f4m/hls/rtmp downloader).

**Comment by xantares** [comment]
seems f4m has code related to progress hook.
is it hls or rtmp ?
do you think it would be easy to implement ?

**Comment by xantares** [comment]
fixed by https://github.com/rg3/youtube-dl/pull/4973
