### ISSUE TITLE
add support for aptv.no

### ISSUE THREAD

**Issue by Siddhant** [rg3/youtube-dl#4863]
URL: http://www.aftenposten.no/webtv/serier-og-programmer/sweatshopenglish/TRAILER-SWEATSHOP---I-cant-take-any-more-7800835.html?paging=&section=webtv_serierogprogrammer_sweatshop_sweatshopenglish

---------------------------------------------------------------------
$ 
youtube-dl --verbose "http://www.aftenposten.no/webtv/serier-og-programmer/sweatshopenglish/TRAILER-SWEATSHOP---I-cant-take-any-more-7800835.html?paging=&section=webtv_serierogprogrammer_sweatshop_sweatshopenglish"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.aftenposten.no/webtv/serier-og-programmer/sweatshopenglish/TRAILER-SWEATSHOP---I-cant-take-any-more-7800835.html?paging=&section=webtv_serierogprogrammer_sweatshop_sweatshopenglish']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.03.1
[debug] Python version 2.7.8 - Linux-3.16.0-29-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6
[debug] Proxy map: {}
[generic] TRAILER-SWEATSHOP---I-cant-take-any-more-7800835: Requesting header
WARNING: Falling back on generic information extractor.
[generic] TRAILER-SWEATSHOP---I-cant-take-any-more-7800835: Downloading webpage
[generic] TRAILER-SWEATSHOP---I-cant-take-any-more-7800835: Extracting information
ERROR: Unsupported URL: http://www.aftenposten.no/webtv/serier-og-programmer/sweatshopenglish/TRAILER-SWEATSHOP---I-cant-take-any-more-7800835.html?paging=&section=webtv_serierogprogrammer_sweatshop_sweatshopenglish
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 694, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1501, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: undefined entity: line 20, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 619, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 268, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1110, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.aftenposten.no/webtv/serier-og-programmer/sweatshopenglish/TRAILER-SWEATSHOP---I-cant-take-any-more-7800835.html?paging=&section=webtv_serierogprogrammer_sweatshop_sweatshopenglish
------------------------------------------------------------------------------

**Comment by dstftw** [comment]
Aftenposten will be supported in the next version. Thanks for the report.

**Comment by phihag** [comment]
@dstftw's implementation made it into youtube-dl 2015.02.09 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
