### ISSUE TITLE
testtube fails, unable to extract video ID

### ISSUE THREAD

**Issue by JThundley** [rg3/youtube-dl#4867]
jt@krondor ~ $ sudo youtube-dl --update
[sudo] password for jt:
Updating to version 2015.02.04 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
jt@krondor ~ $ sudo youtube-dl --update
youtube-dl is up-to-date (2015.02.04)
jt@krondor ~ $ cat ~/.config/youtube-dl.conf
-t
-c
--no-playlist
jt@krondor ~ $ youtube-dl --verbose 'https://testtube.com/iflscience/insane-jet-ski-flipping'
[debug] System config: []
[debug] User config: ['-t', '-c', '--no-playlist']
[debug] Command-line args: ['--verbose', 'https://testtube.com/iflscience/insane-jet-ski-flipping']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.04
[debug] Python version 2.7.8 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: avconv 2.5.3, avprobe 2.5.3, ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[TestTube] insane-jet-ski-flipping: Downloading webpage
ERROR: Unable to extract video ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 619, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 268, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/testtube.py", line 33, in _real_extract
    webpage, 'video ID')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 524, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

This URL actually embeds a youtube video and not their typical embed. The embedded youtube video downloads fine.

**Comment by yan12125** [comment]
Thanks for the report. This video can be downloaded in the next version of youtube-dl.

**Comment by JThundley** [comment]
Thank you, you da man! :)
