### ISSUE TITLE
"Network is Unreachable" with force ipv6 parameter

### ISSUE THREAD

**Issue by raeesiqbal** [rg3/youtube-dl#4869]
Hello, I have the latest youtube-dl installed at a VPS. It is a Ubuntu 14.04 x64 machine and has both IPv4 and IPv6 connectivity but the tool only works with IPv4. This is what i get
``` youtube-dl -6 -f 43 -g https://www.youtube.com/watch?v=GC2qk2X3fKA```
```ERROR: Unable to download webpage: <urlopen error [Errno 101] Network is unreachable> (caused by URLError(error(101, 'Network is unreachable'),))```

As I said the same url works with IPv4. What could be the problem?

**Comment by phihag** [comment]
Are you sure that you do have IPv6 connectivity? Can you post a screenshot of http://test-ipv6.com/ run on that machine? What is the output of `ip -6 r` in the command line?

**Comment by raeesiqbal** [comment]
I haven't installed Desktop on it but this ```fe80::/64 dev eth0  proto kernel  metric 256``` is of the command ```ip -6 r```

**Comment by phihag** [comment]
That's fine, the route table is enough to show that you do not have IPv6 connectivity. You must configure your routing (or use a SLAAC or DHCPv6) before you can actually use IPv6.
