### ISSUE TITLE
Get filename in a bash script

### ISSUE THREAD

**Issue by augnustin** [rg3/youtube-dl#4870]
I want to automate sending the newly downloaded file to my google play music using the almost-as-awesome-as-youtube-dl-library http://unofficial-google-music-api.readthedocs.org/

I am aware I could do that in python, but not being a python dev, I'd rather write a bash script for higher level operation.

Here's my take

```
download_music(){
  cd ~/Music;
  file = youtube-dl $1 --default-search "ytsearch";
  echo $file;
PYTHON_ARG="$file" python <<END
from gmusicapi import Musicmanager
import os
mm = Musicmanager()
mm.login()
mm.upload(os.environ['PYTHON_ARG'])
END
}
```

My single trouble is to get the filename (or filepath) generated from `youtube-dl` script. Any tip on how I could do that?

I'll post final solution for those who could be interested.

Thanks a lot,

**Comment by HPP8140** [comment]
-g option

http://manpages.ubuntu.com/manpages/utopic/man1/youtube-dl.1.html

**Comment by globau** [comment]
--get-filename     simulate, quiet but print output filename

**Comment by aug-riedinger** [comment]
It won't work for me. It the file downloaded is a youtube video, the output is the mp4 file and not the postprocessed mp3 file (because of -x option).

I ended up creating a temporary folder, downloading into it, `ls`ing it, uploading it and aksing wether or not I want to delete the file.

Here's the code for those interested:

```
upload_music() {
  PYTHON_ARG="$1" python <<END
from gmusicapi import Musicmanager
import os
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
mm = Musicmanager(False, False, False)
mm.login()
mm.upload(os.environ['PYTHON_ARG'])
END
}

ask_remove() {
  echo "Do you want to keep $1?"
  select yn in "Yes" "No"; do
      case $yn in
          [Yy]* ) mkdir -p mv $1 ~/Musique/ break;;
          [Nn]* ) exit;;
      esac
  done
}

download_music(){
  cd ~/Musique;
  mkdir -p tmp;
  cd tmp;
  youtube-dl --default-search "ytsearch" -x --audio-format mp3 --no-mtime --prefer-ffmpeg $1;
  file="$(ls -t | head -n 1)";
  echo "$file downloaded";
  upload_music $file;
  echo "$file uploaded";
  ask_remove $file;
  cd ..;
  rm -rf tmp;
}

```

**Comment by williamboman** [comment]
I'm trying to do the <sup>almost</sup> exact same thing.

What I've come up with is something like this;

```bash
# cwd is /tmp/youtube-dl
youtube-dl "$1" -x -o "%(title)s.%(ext)s" --audio-format=mp3 --audio-quality=512k;
filename=$(youtube-dl "$1" -x -o "%(title)s.%(ext)s" --audio-format=mp3 --audio-quality=512k --get-filename);

mv "$filename" "~/Drive/Music/$filename"
```

The only issue I have is that `$filename` has the wrong ext.

There has to be a better way of doing this? I can't seem to find a solution in the manual.

**Comment by yan12125** [comment]
The output template accept path parts. For example, 
```Bash
youtube-dl "$1" -x -o "~/Drive/Music/%(title)s.mp3" --audio-format=mp3 --audio-quality=512k
```

**Comment by williamboman** [comment]
@yan12125 Yeah that's how I did it before. But when you directly set the file to `.mp3` it will skip the actual mp3 post-processing. The reason I want to download it to `/tmp` is to avoid syncing the `.part` and i.e. `.m4a` files that are created during download with Google Drive.

I think I managed to update my script after you commented, it works perfectly<sup>&#8482;</sup> now.

**Comment by justhankmoody** [comment]
@williamboman i am have similar  issue - when download mp3 and set option -o file.mp3 youtube-dl  skip post-processing and  resulting file is not readable in podcast players. 
i set option ** -o file.data**  and youtube-dl download file to .data and convert to .mp3 file

**Comment by yan12125** [comment]
The remaining issue is that --get-filename doesn't work with post-processing (mp3 conversion, etc.). This is discussed in #7137.
