### ISSUE TITLE
Add hds / hds_sd support for rts.ch (with solution)

### ISSUE THREAD

**Issue by goundoulf** [rg3/youtube-dl#4873]
```$ youtube-dl -f hds_sd http://www.rts.ch/play/tv/passe-moi-les-jumelles/video/la-fee-des-bois-mustang-les-chemins-du-vent?id=3854925```
```[RTS] la-fee-des-bois-mustang-les-chemins-du-vent: Downloading JSON metadata```
```[download] Downloading f4m manifest```
```ERROR: unable to download video data: HTTP Error 403: Forbidden```

The solution is to append this at the end of the request: ```?$AUTH_PARAMS&g=KEELPSHKBDEC&hdcore=3.4.0&plugin=aasp-3.4.0.132.66```

And ```$AUTH_PARAMS``` you can get from here: http://tp.srgssr.ch/token/akahd.xml?stream=$STREAM_URL*

You can have a look at this script I made: https://github.com/goundoulf/rts-dl/blob/master/rts-dl

**Comment by dstftw** [comment]
Thanks for the report, this will be fixed in the next version.

**Comment by goundoulf** [comment]
Thanks for you quick fix!

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.02.09 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by goundoulf** [comment]
Yes this is fixed. Thanks a lot!
