### ISSUE TITLE
Cannot download from media.nationalarchives.gov.uk (site is using jwplayer)

### ISSUE THREAD

**Issue by russell-phillips** [rg3/youtube-dl#4876]
I cannot download the video from http://media.nationalarchives.gov.uk/index.php/webinar-using-discovery-national-archives-online-catalogue/

Digging through the source code of the page, I found this code snippet:

	<script type='text/javascript'>
	jwplayer('player').setup({
	'flashplayer': 'http://media.nationalarchives.gov.uk/wp-content/themes/AMPtheme/player.swf',
	'file': 'https://www.youtube.com/watch?v=Mrj4DVp2zeA',
	'title': 'Webinar: Using Discovery, The National Archives&#8217; online catalogue',
	'image':  'http://media.nationalarchives.gov.uk/files/2015/01/discovery.jpg',
	'width': '500',
	'height': '358',
	'skin': 'http://media.nationalarchives.gov.uk/wp-content/themes/AMPtheme/video.zip'
	});
	</script>

I was able to download the video from the YouTube URL, but obviously it would be nice if that wasn't necessary :)

Output from youtube-dl:

	$ youtube-dl --verbose "http://media.nationalarchives.gov.uk/index.php/webinar-using-discovery-national-archives-online-catalogue/"
	[debug] System config: []
	[debug] User config: []
	[debug] Command-line args: ['--verbose', 'http://media.nationalarchives.gov.uk/index.php/webinar-using-discovery-national-archives-online-catalogue/']
	[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
	[debug] youtube-dl version 2015.02.04
	[debug] Python version 2.7.8 - Linux-3.16.0-30-generic-x86_64-with-Ubuntu-14.10-utopic
	[debug] exe versions: avconv 11-6, avprobe 11-6, rtmpdump 2.4-n87-gita9f353c-ppa8
	[debug] Proxy map: {}
	[generic] webinar-using-discovery-national-archives-online-catalogue: Requesting header
	WARNING: Falling back on generic information extractor.
	[generic] webinar-using-discovery-national-archives-online-catalogue: Downloading webpage
	[generic] webinar-using-discovery-national-archives-online-catalogue: Extracting information
	ERROR: Unsupported URL: http://media.nationalarchives.gov.uk/index.php/webinar-using-discovery-national-archives-online-catalogue/
	Traceback (most recent call last):
	  File "/home/russ/bin/youtube-dl/youtube_dl/extractor/generic.py", line 707, in _real_extract
		doc = parse_xml(webpage)
	  File "/home/russ/bin/youtube-dl/youtube_dl/utils.py", line 1501, in parse_xml
		tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
	  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
		parser.feed(text)
	  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
		self._raiseerror(v)
	  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
		raise err
	ParseError: mismatched tag: line 65, column 2
	Traceback (most recent call last):
	  File "/home/russ/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 619, in extract_info
		ie_result = ie.extract(url)
	  File "/home/russ/bin/youtube-dl/youtube_dl/extractor/common.py", line 268, in extract
		return self._real_extract(url)
	  File "/home/russ/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1132, in _real_extract
		raise UnsupportedError(url)
	UnsupportedError: Unsupported URL: http://media.nationalarchives.gov.uk/index.php/webinar-using-discovery-national-archives-online-catalogue/

**Comment by robin007bond** [comment]
https://github.com/rg3/youtube-dl/pull/4907

I tried to implement it.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.02.09.1 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by russell-phillips** [comment]
Now working for me, using youtube-dl 2015.02.09.1

Thanks :)
