### ISSUE TITLE
2015.02.04 fails to get DASH video

### ISSUE THREAD

**Issue by voltagex** [rg3/youtube-dl#4877]
root@merrick:~# python youtube-dl -F --verbose https://www.youtube.com/watch?v=nl-EnawbdtA
	[debug] System config: []
	[debug] User config: []
	[debug] Command-line args: ['-F', '--verbose', 'https://www.youtube.com/watch?v=nl-EnawbdtA']
	[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
	[debug] youtube-dl version 2015.02.04
	[debug] Python version 2.7.6 - Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
	[debug] exe versions: avconv 9.16-6, avprobe 9.16-6
	[debug] Proxy map: {}
	[youtube] nl-EnawbdtA: Downloading webpage
	[youtube] nl-EnawbdtA: Extracting video information
	WARNING: [youtube] nl-EnawbdtA: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
	[info] Available formats for nl-EnawbdtA:
	format code extension resolution  note
	140         m4a       audio only  DASH audio , m4a_dash container, aac  @128k (worst)
	160         mp4       144p        DASH video , video only
	133         mp4       240p        DASH video , video only
	134         mp4       360p        DASH video , video only
	135         mp4       480p        DASH video , video only
	136         mp4       720p        DASH video , video only
	137         mp4       1080p       DASH video , video only
	17          3gp       176x144
	36          3gp       320x240
	43          webm      640x360
	5           flv       400x240
	18          mp4       640x360
	22          mp4       1280x720    (best)

**Comment by phihag** [comment]
The title makes it sound like you think this is a regression - do you get the full range of DASH formats with another youtube-dl version? By the way, it works fine for me, so this may be a localized issue.

**Comment by voltagex** [comment]
phihag - I think YouTube blocked that IP.

**Comment by phihag** [comment]
@voltagex Which IP, and why do you think that in the first place? From the error message, this looks like we fail to detect the player URL.

**Comment by voltagex** [comment]
I was using youtube-dl on a new VM, the first 10 downloads worked and then I got this error.

**Comment by phihag** [comment]
I'd file that under anecdotal evidence.

**Comment by voltagex** [comment]
Tried another machine, it's working. Odd. Sorry for wasting your time

**Comment by jaimeMF** [comment]
By the way, don't run youtube-dl as the root user. It's only needed for updating.

**Comment by voltagex** [comment]
Yes, this was a short lived VM.
