### ISSUE TITLE
customize --external-downloader option

### ISSUE THREAD

**Issue by remitamine** [rg3/youtube-dl#4885]
is there any way to edit the options of the external downloader.
as i see in the file external.py there is an argument for aria2 '--max-connection-per-server', '4' passed to the cmd variable,can i edit this to other variable other than 4.
in general it will a good thing to have a way to customize the external downloader.

**Comment by HASJ** [comment]
seconded.

**Comment by AndyHoang** [comment]
3th :+1:

**Comment by phihag** [comment]
Since youtube-dl 2015.03.03.1, you can use the `--external-downloader-args` parameter if you want to configure other settings than the default for that downloader. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by alisseo** [comment]
i use youtube-dl whit IDMAN whit this batch: 

```
youtube-dl.exe -U
@echo off
echo.
echo paste the video page link:
set /p "link="     
youtube-dl.exe -g %link% >> url.txt
SET /p url= < url.txt
del url.txt
SET folder=%~dp0
path-to\IDMan.exe /d "%url%"  /n /q /p %folder%
explorer %folder%
exit
```
copy the code in a text file like "video-dl.bat", set the PATCH for idman.exe, save this file in the same folder of youtube-dl.exe

**Comment by Alttawab** [comment]
@alisseo how can i use these batch in windows

**Comment by Hrxn** [comment]
It won't work without `IDMan.exe`

I guess it's the program called Internet Download Manager?

**Comment by Alttawab** [comment]
@Hrxn i use IDM  ,I replace "path-to" with my path but it didn't work is there any thing else must edit 
in the script ?

**Comment by Hrxn** [comment]
Not sure, I don't use IDM. But you can always run the .bat/.cmd from the command prompt, remove `@echo off` and see where it complains.
