### ISSUE TITLE
Add another tvigle.ru URL

### ISSUE THREAD

**Issue by grompe** [rg3/youtube-dl#4887]
There is an embedded link of form

    https://cloud.tvigle.ru/video/{NumericID}/

that could be supported in tvigle extractor.
For example, https://cloud.tvigle.ru/video/5267604/
Following the API URL http://cloud.tvigle.ru/api/play/video/5267604/ gives the video data.

**Comment by dstftw** [comment]
Tvigle cloud URLs will be supported in the next version. Thanks for the report.

**Comment by grompe** [comment]
Great work, thanks!

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.02.09 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
