### ISSUE TITLE
VEVO videos only available in 25p? VEVO on YouTube are true 23.976p/25p/29,97p

### ISSUE THREAD

**Issue by Klaus1189** [rg3/youtube-dl#4889]
If I download a video direct from VEVO.com, the files always have 25fps. But that is wrong! 
It's only OK, if the original video also has also 25.000 fps, but over 90% of the videos have 23.976 fps or 29.970 fps.

The files from YouTube are fine but quality isn't as good as from VEVO.com itself. I checked several videos. 

I want to download the "native" files from VEVO.com. Also when audio and video files are separate. That's not a problem, but it looks like the files are reencoded or (re)muxed in any way. MediaInfo Lite told me that :)

The problem is that the videos stutter while playing them with MPC-HC with auto refresh rate change. I use the correct matching refresh rate for playing every video.

If you need more information, let me know.

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by Klaus1189** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Klaus>Downloads\youtube-dl http://www.vevo.com/watch/jennifer-l
opez/on-the-floor/USUV71100181 -F --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.vevo.com/watch/jennifer-lopez/on-the-flo
or/USUV71100181', '-F', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.02.06
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Vevo] Retrieving oauth token
[Vevo] USUV71100181: Downloading JSON metadata
[Vevo] USUV71100181: Downloading HLS formats
[Vevo] USUV71100181: Downloading m3u8 information
[Vevo] USUV71100181: Downloading SMIL info
[info] Available formats for USUV71100181:
format code extension resolution  note
m3u8-meta   mp4       multiple    Quality selection URL  (worst)
Low         mp4       176x144     x264@  56k, quicktime@ 24k
Med         mp4       480x360     x264@ 500k, quicktime@128k
High        mp4       1280x720    x264@2048k, quicktime@192k
SMIL_564    mp4       512x288     x264@ 500k, quicktime@ 64k
SMIL_864    mp4       512x288     x264@ 800k, quicktime@ 64k
SMIL_1328   mp4       768x432     x264@1200k, quicktime@128k
SMIL_1728   mp4       768x432     x264@1600k, quicktime@128k
SMIL_2528   mp4       1280x720    x264@2400k, quicktime@128k
SMIL_3328   mp4       1280x720    x264@3200k, quicktime@128k
SMIL_4392   mp4       1920x1080   x264@4200k, quicktime@192k
SMIL_5392   mp4       1920x1080   x264@5200k, quicktime@192k
m3u8-278    mp4       416x234      278k , avc1, mp4a
m3u8-427    mp4       416x234      427k , avc1, mp4a
m3u8-651    mp4       480x270      651k , avc1, mp4a
m3u8-776    mp4       640x360      776k , avc1, mp4a
m3u8-1105   mp4       640x360     1105k , avc1, mp4a
m3u8-1555   mp4       960x540     1555k , avc1, mp4a
m3u8-2894   mp4       960x540     2894k , avc1, mp4a
m3u8-3783   mp4       1280x720    3783k , avc1, mp4a
m3u8-4934   mp4       1920x1080   4934k , avc1, mp4a
m3u8-6047   mp4       1920x1080   6047k , avc1, mp4a  (best)

C:\Users\Klaus>Downloads\youtube-dl http://www.vevo.com/watch/jennifer-l
opez/on-the-floor/USUV71100181 -f m3u8-6047 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.vevo.com/watch/jennifer-lopez/on-the-flo
or/USUV71100181', '-f', 'm3u8-6047', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.02.06
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Vevo] Retrieving oauth token
[Vevo] USUV71100181: Downloading JSON metadata
[Vevo] USUV71100181: Downloading HLS formats
[Vevo] USUV71100181: Downloading m3u8 information
[Vevo] USUV71100181: Downloading SMIL info
[debug] Invoking downloader on u'http://hls-aws.vevo.com/v3/hls/2014/09/USUV7110
0181/7a0d8876-e768-4611-b2ff-b2041a71c497/5200/usuv71100181_5200k_1920x1080_h264
_5200_aac_128.m3u8'
[download] Destination: On The Floor-USUV71100181.mp4
[hlsnative] USUV71100181: Downloading m3u8 manifest
[hlsnative] USUV71100181: Downloading segment 1 / 27
...

**Comment by Klaus1189** [comment]
File is still downloading a second time, so I thought it be enough to post here?

**Comment by jaimeMF** [comment]
(For reference, the youtube video is https://www.youtube.com/watch?v=t4H_Zoh7G5A)

If Youtube and/or vevo.com reencode the original video we can't do anything, unless they provide a link to the original file.
Note that on vevo.com if you select the format `SMIL_5392`, it will download a video with the same framerate as `bestvideo` youtube.com: `23.98` (according to ffprobe).

**Comment by Klaus1189** [comment]
MPC-HC plays it as 25p.
General
ID                          : 1 (0x1)
Complete name               : C:\Users\Klaus\On The Floor-USUV71100181.mp4
Format                      : MPEG-TS
File size                   : 179 MiB
Duration                    : 4mn 26s
Overall bit rate mode       : Variable
Overall bit rate            : 5 627 Kbps

Video
ID                          : 256 (0x100)
Menu ID                     : 1 (0x1)
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : Main@L4.0
Format settings, CABAC      : Yes
Format settings, ReFrames   : 4 frames
Codec ID                    : 27
Duration                    : 4mn 26s
Nominal bit rate            : 5 200 Kbps
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Variable
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Writing library             : x264 core 142 r2479 dd79a61
Encoding settings           : cabac=1 / ref=4 / deblock=1:0:0 / analyse=0x1:0x111 / me=umh / subme=8 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=cbr / mbtree=1 / bitrate=5200 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=5200 / vbv_bufsize=5200 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00

Audio
ID                          : 257 (0x101)
Menu ID                     : 1 (0x1)
Format                      : AAC
Format/Info                 : Advanced Audio Codec
Format version              : Version 4
Format profile              : LC
Muxing mode                 : ADTS
Codec ID                    : 15
Duration                    : 4mn 26s
Bit rate mode               : Variable
Channel(s)                  : 2 channels
Channel positions           : Front: L R
Sampling rate               : 44.1 KHz
Compression mode            : Lossy
Delay relative to video     : -36ms

Menu
ID                          : 4096 (0x1000)
Menu ID                     : 1 (0x1)
Duration                    : 4mn 26s
List                        : 256 (0x100) (AVC) / 257 (0x101) (AAC)
Service name                : USUV71100181
Service provider            : FFmpeg
Service type                : digital television

**Comment by jaimeMF** [comment]
As I said, you have to download the `SMIL_5392` format (you may need to remove the existing video file or use the `--output` option).
Maybe we should make it the default.

**Comment by Klaus1189** [comment]
Please check this sample:
VEVO: 25fps
http://www.vevo.com/watch/katy-perry/dark-horse-official/USUV71400083
and youtube version: 23.98 fps
https://www.youtube.com/watch?v=0KSOMA3QBU0

That's the problem.

**Comment by Klaus1189** [comment]
Can you reproduce that?

**Comment by jaimeMF** [comment]
All seem to play fine using mpv, ffplay and vlc, but:
* Quicktime can't play the m3u8 video, unless you convert it with `ffmpeg -i Dark\ Horse\ \(Official\)-USUV71400083.mp4 -bsf:a aac_adtstoasc  -c copy fixed.mp4` (could be more or less the same problem as #4776).
* I was playing with a ffmpeg filter to play the two files at the same time and the m3u8 (and only that) doesn't play right.

Downloading the video without the native downloader (requires changing the code) produces a file without the problems I listed, so I guess that's the problem.
To clarify things: if you play the SMIL_5392 (make sure it's redownloaded), does it show the same problems as the m3u8? (if you could tried to convert the file with the ffmpeg command, that would be great).

**Comment by Klaus1189** [comment]
SMIL_539 is downloading right now. I must wait ...
OK, how do I convert the file? How do I use 
ffmpeg -i Dark\ Horse\ \(Official\)-USUV71400083.mp4 -bsf:a aac_adtstoasc -c copy fixed.mp4
What ffmpeg.exe? Where do I get the same one you are using, just to be sure.

IMPORTANT: Are both m3u8 AND SMIL reencoded or remuxed in any way?

**Comment by Klaus1189** [comment]
Is it possible to add support for the direct audio and video streams from the VEVO servers? 

I know that the VEVO-videos are also on youtube, but yesterday I discovered that the streams from VEVO must be of higher quality compared to youtube!

VEVO:
http://www.vevo.com/watch/kelly-clarkson/Heartbeat-Song/GBE431500003
VEVO-video on youtube:
https://www.youtube.com/watch?v=d4_6N-k5VS4

I made screenshots of the same frames of the videos and you can compare.
I know only hair ;) but you see very clear what I am talking about:
![comparison](https://cloud.githubusercontent.com/assets/10894455/6092685/7ce22c1e-aee9-11e4-9e1b-98373f16d0a4.png)

**Comment by jaimeMF** [comment]
Download page: http://ffmpeg.org/download.html

About m3u8 (or [HLS](https://en.wikipedia.org/wiki/HTTP_Live_Streaming)): they split the video in multiple fragments. I would guess they convert it, specially since some qualities are probably used for mobile devices.
About the smil, I don't know.
I don't know why you care so much, it's up to the services to provide the original file.

**Comment by Klaus1189** [comment]
"I don't know why you care so much, it's up to the services to provide the original file."

I know, but I think there is something in youtube-dl or between me and VEVO that muxes a onlyvideo.mp4 and a onlyaudio.aac to an video+audio.mp4 
But exactly here is the problem, I don't know who encodes the videos with x264:
Example: Katy Perry - Dark Horse (SMIL)
MediaInfo Lite:
General
Complete name               : C:\Users\Klaus\Dark Horse (Official)-USUV71400083.mp4
Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : isom
File size                   : 120 MiB
Duration                    : 3mn 45s
Overall bit rate mode       : Variable
Overall bit rate            : 4 491 Kbps
Writing application         : Lavf55.22.102

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : Main@L5.0
Format settings, CABAC      : Yes
Format settings, ReFrames   : 5 frames
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 3mn 44s
Bit rate                    : 4 358 Kbps
Nominal bit rate            : 5 200 Kbps
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 25.000 fps
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.084
Stream size                 : 117 MiB (97%)
Writing library             : x264 core 140 r2377 1ca7bb9
Encoding settings           : cabac=1 / ref=5 / deblock=1:0:0 / analyse=0x1:0x111 / me=umh / subme=8 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=24 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=0 / intra_refresh=0 / rc_lookahead=50 / rc=cbr / mbtree=1 / bitrate=5200 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=5200 / vbv_bufsize=5200 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Language                    : English

Audio
ID                          : 2
Format                      : AAC
Format/Info                 : Advanced Audio Codec
Format profile              : LC
Codec ID                    : 40
Duration                    : 3mn 45s
Duration_LastFrame          : -10ms
Bit rate mode               : Variable
Bit rate                    : 128 Kbps
Maximum bit rate            : 5 200 Kbps
Channel(s)                  : 2 channels
Channel positions           : Front: L R
Sampling rate               : 44.1 KHz
Compression mode            : Lossy
Stream size                 : 3.43 MiB (3%)
Language                    : English



And youtube version:
General
Complete name               : D:\Videos\Musikvideos MP4-AAC-256 WebM-OGG-192\Katy Perry - Dark Horse (Official) ft. Juicy J [0KSOMA3QBU0]\MP4\Katy Perry - Dark Horse (Official) ft. Juicy J.mp4
Format                      : dash
Codec ID                    : dash
File size                   : 89.7 MiB
Duration                    : 3mn 44s
Overall bit rate            : 3 347 Kbps
Encoded date                : UTC 2014-06-18 06:05:55
Tagged date                 : UTC 2014-06-18 06:05:55

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4.0
Format settings, CABAC      : Yes
Format settings, ReFrames   : 3 frames
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 3mn 44s
Bit rate                    : 3 343 Kbps
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Variable
Frame rate                  : 23.976 fps
Minimum frame rate          : 23.974 fps
Maximum frame rate          : 1 046.512 fps
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.067
Stream size                 : 89.7 MiB (100%)
Encoded date                : UTC 2014-06-18 06:05:55
Tagged date                 : UTC 2014-06-18 06:05:55
Video only!!

MPC-HC adds audio automatically.

You see framerate doesn't match.
And that is causing stuttery playback, but you oly see that if you use the correct refresh rate of your monitor, not every supports all, mostly they only support 60.000Hz

**Comment by Klaus1189** [comment]
Please note the file is constant frame rate not variable as detected by MediaInfo, I already told them that detcts it wrong, but they told me to pay if I want that be fixed. Strange people. I thought free and open source is free and open source. Anyway that's not the point here.

I made clips with my mobile phone to show you how to play the files the right way. -> MPC-HC uses the correct refresh rate or double (it is for interlaced videos) But 25 fps can be watched without problems at doubled refresh rate.

Here are the links to the files:

https://drive.google.com/file/d/0B4y5u0gBKYqbUm5WX2toOFhIb2c/view?usp=sharing
https://drive.google.com/file/d/0B4y5u0gBKYqbN1kzamV0dVRxR0k/view?usp=sharing

**Comment by Klaus1189** [comment]
I'm sure we find a solution for my desire :)

**Comment by jaimeMF** [comment]
I can't see any obvious difference from the videos you posted, could you describe the problem better?
> I know, but I think there is something in youtube-dl or between me and VEVO that muxes a onlyvideo.mp4 and a onlyaudio.aac to an video+audio.mp4

Why do you think that?

> But exactly here is the problem, I don't know who encodes the videos with x264:

I think I don't understand this part, vevo is encoding their videos with x264, that's all.

**Comment by Klaus1189** [comment]
"I can't see any obvious difference from the videos you posted, could you describe the problem better?"

The 23.976 video is playing smooth, the 25.000 video has microstutters every 4 or 5 seconds. It is possible that you can't see these in my clips from my mobile phone. I'm sure it can't be seen here. My intention with the clips is, that you see, the display has to switch to another refresh rate in order to display the files right. And the red and green line must be parallel in display stats CTRL + J.


"I think I don't understand this part, vevo is encoding their videos with x264, that's all."

I inspected the files with MediaInfo and saw that the files are encoded or at least muxed with:
"Writing application         : Lavf55.21.100" 

-> This is open source software and I really can't imagine that VEVO uses this. Normally download tools use ffmpeg to combine audio and video to merge it into one file so average user can play it with VLC media player which doesn't support external audio like MPC-HC does (there is only a really bad support and a very complicated way -< doesn't work properly)

That is the reason why I said that I want the files straight from vevo without any muxing with Lavf55.21.100. The other filestype is at least encoded with x264.

But if you say there is no muxing with ffmpeg during I download this file from VEVO.com with youtube-dl, there is nothing we can do. Then VEVO itself produces this special kind of crap videos with high bitrate. But I really can't believe that they did framerate conversions, and really such bad ones

The youtube files are fine, but I am interesed in higher bitrate videos, because youtube is continuously going down with bitrate and picture quality is suffering from this for month now.

Youtube also did framerate conversions in the past, like 23.976 to 30.000. But they learned what they did wrong :)

Just for completion: Is there really no ffmpeg or any other tool used for compining several segments of the video. And also not to combine audio with video?
Youtube also does segment, right? But here you see there is so ffmpeg used to combine the segments: UTC is written by Google a time before the video is published.

!!! Keep in mind that Google/YouTube encodes much of their videos new (with of course lower bitrate, so the video do look ugly) so there is probably a new UTC written in the files !!!

For example the file was encoded before it was published on YouTube:
Compare date on https://www.youtube.com/watch?v=BfgoiYu9EUE with following UTC:
General
Complete name               : D:\...\Jennifer Lopez - First Love (Official Video).mp4
Format                      : dash
Codec ID                    : dash
File size                   : 105 MiB
Duration                    : 5mn 2s
Overall bit rate            : 2 905 Kbps
Encoded date                : UTC 2014-05-28 14:12:51
Tagged date                 : UTC 2014-05-28 14:12:51

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4.0
Format settings, CABAC      : Yes
Format settings, ReFrames   : 2 frames
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 5mn 2s
Bit rate                    : 2 902 Kbps
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Variable
Frame rate                  : 23.976 fps
Minimum frame rate          : 23.974 fps
Maximum frame rate          : 24.220 fps
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.058
Stream size                 : 105 MiB (100%)
Encoded date                : UTC 2014-05-28 14:12:51
Tagged date                 : UTC 2014-05-28 14:12:51

And that's a newer coded file from https://www.youtube.com/watch?v=BfgoiYu9EUE

General
Complete name               : D:\...\Jennifer Lopez - First Love (Official Video).mp4
Format                      : dash
Codec ID                    : dash
File size                   : 78.1 MiB
Duration                    : 5mn 2s
Overall bit rate            : 2 167 Kbps
Encoded date                : UTC 2014-05-31 15:08:09
Tagged date                 : UTC 2014-05-31 15:08:09

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4.0
Format settings, CABAC      : Yes
Format settings, ReFrames   : 3 frames
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 5mn 2s
Bit rate                    : 2 164 Kbps
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Variable
Frame rate                  : 23.976 fps
Minimum frame rate          : 23.974 fps
Maximum frame rate          : 775.862 fps
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.044
Stream size                 : 78.0 MiB (100%)
Encoded date                : UTC 2014-05-31 15:08:09
Tagged date                 : UTC 2014-05-31 15:08:09

Three days later much smaller videoonly filesize !!! I bet not so many know this :)

If I should explain anything better let me know -> I'm not native english, I'm from bavaria :D

**Comment by Klaus1189** [comment]
Is ffmpeg used while downloading from VEVO.com?

**Comment by jaimeMF** [comment]
youtube-dl doesn't use ffmpeg when downloading from VEVO.com, they are using it (ffmpeg can produce m3u8 manifest and segments from a video) themselves.

I think there's nothing that youtube-dl can do, so we should close the issue.

**Comment by Klaus1189** [comment]
Yeah, I agree with you. We should close this issue, VEVO itself is producing shit files, but with high bitrate. 

OK, so I stay downloading VEVO videos from YouTube. Their videos have the original framerate, no converted framerate from 23.976 (24.000/1.001) to 25.000 or similar.

To everyobdy, who reads this thread and is interested:
To watch the jerkyness of the converted files, play a 25.000fps VEVO file which is 23.976fps at YouTube. I recommend MPC-HC, and also MPC-BE.
The refreshrate of your monitor must match the framerate of your playing file. 
Please note: NOT every monitor does support all refresh rates like 23/24/25/29/30/50/59/60Hz.. 23Hz mode is for 23.976, 59Hz for 59.970, 29Hz for 29.970. Mine does all :D 
Most ones only do 60 Hz. LOL

Maybe anybody could tell the guys from VEVO that their videos are encoded at wrong framerate!
I'm very dissapointed from the video encoding guys at VEVO. 
@ VEVO guys: SHAME ON YOU!!!

**Comment by nickvh** [comment]
Im not sure what the rendering engine in MPC is or does, but if you play a segment or the whole HLS stream in something like VLC then non of these issues exists because the frame rate is available in the TS header which in turn defines how the timing is rendered in VLC.  There are technical reasons why we use 25fps and a proper frame rate conversion is done to achieve this which is nothing extraordinary or unusual.  Im unable to see any issues with rendering the HLS encoded content in VLC or QT or our great new vevo.com website.  For the record we encode our own content as do YT from our source mezzanine files - for some additional light reading please checkout our blog http://blog.vevo.com/smart-content-encoding-at-vevo/.  Do let me know if there is more we can do to help answer your questions, but i suspect this is MPC unable to tolerate our frame rate choices.

**Comment by Klaus1189** [comment]
Thank you for your reply. 

> There are technical reasons why we use 25fps...

What's exactly the reason for the conversion?

> ...a proper frame rate conversion is done...

And that's exaclty the point, what is wrong with most files

What refresh rate do you use for this test with VLC?

A very annoying kind of framerate conversion is from 23.976 fps (24.000/1.001) to 25fps by adding a frame.

**Comment by Klaus1189** [comment]
Don't you help me?

**Comment by Klaus1189** [comment]
files are coded wrong, because there IS a framerate conversion
Still no help?

**Comment by yan12125** [comment]
By @nickvh's description, it seems a Vevo's internal decision to use 25fps. Ask @nickvh or other Vevo people for their problems. youtube-dl just downloads the file(s) served by Vevo, and we can't provide any help here.

**Comment by Klaus1189** [comment]
OK, I asked @nickvh for help, but I think I don't get any from him and I don't want to start a new thread anywhere, because I know they are coding their files wrong, I wouldn't know where to post it if I would do. 
Now I shut up and thank you guys for youtube-dl, I use it daily.

**Comment by yan12125** [comment]
Or you may want to forward this bug to https://trac.mpc-hc.org/, MPC's bug tracker. If a video can be played fluently in many players except MPC, it might be MPC's fault.

**Comment by Klaus1189** [comment]
Ok, I explain it short, a music video which is shot at 23.976 fps is reconverted so every seconds a frame is duplicated when framerate is converted to 25 fps, a very good or bad example is the one mentioned already above:
https://www.youtube.com/watch?v=0KSOMA3QBU0
coded right from youtube
http://www.vevo.com/watch/USUV71400083
bad encoding with 25fps
but keep in mind you have to use the mathcing refresh rate of your Monitor or TV.
VLC can't switch it on its own, but MPC-HC and MPC-BE can.
But only some can display 23 Hz / 24 Hz / 25 Hz / 29 Hz / 30 Hz / 50 Hz / 59 Hz / 60 Hz, most devices only can 60 hz so 3:2 pull down is applied which I don'T ant to see. I only want native 24p. But there is 23 Hz setting for 23.976 (24.000/1.001) and 24.000p. And VEVO also does a framerate conversion from 59.940 (59 Hz mode) to 25 fps which is very stuttery. They also do upscaling 720p to 1080p which is a waste.

**Comment by yan12125** [comment]
OK by this example problems are from videos but not players. Only Vevo can fix it.

**Comment by nickvh** [comment]
+1 for yan12125, if the content cant be played in MPC but plays at good quality via HTML 5 and our 12 other platform players - id look to MPC to resolve this dynamically..

We encode to 25fps for business reasons.

**Comment by Klaus1189** [comment]
It is not a bug by MPC HC or MPC BE. WHAT DO I HAVE TO WRITE SO YOU GET IT?
Do you know what a refresh rate is? You can only play a 60 hz video like this one smooth when using a standard refresh rate of 60 Hz:
https://www.youtube.com/watch?v=_fC53l3jGAc

The refresh rate of the graphic card must match the framerate of the video. The standard user has a monitor which only supports 60 Hz.
If you live in PAL land like me in the deep bavarian forrest, you can also play 50p videos, but only smooth if you set the refresh rate in the grafic card to 50 hz.

Do you now get what Vevo is doing wrong? It is not a bug by MPC. 

What are business reasons? JUST LEAVE THE FRAMERATE AS IT IS. 
The more I need to write here and have to repeat Me several times, I personally think you want me to get angry by ignoring my posts. Framerate conversions are silly and the result are fucked up videos you can't watch if you're a video enthusiast like I am. 

What do I need to explain now?

**Comment by yan12125** [comment]
By this example I guess there's a duplicated frame in each second, as described previously by @Klaus1189. If this is really the case, Vevo should check their video encoders.

Need more time to analyze the downloaded file.

**Comment by Klaus1189** [comment]
HTML 5 is the same crap in the brower, but it should be fine if the refresh rate is set to the matching framerate of the video. A clever videoplayer like MPC can do this on its own. 

WATCH THE CANYON 60 hz video and you know what I mean by matching refreshrate.

Yeah, @yan12125 understands my point now. Vevo encoders are silly.
And they also upscale 720p hd to 1080p fullhd. What a waste. And if the video of live concerts is shot at 59.940p (59 hz) mode in grafic driver, a framerate conversion to 25 is more than silly. It ruins complete video experience.

**Comment by Klaus1189** [comment]
Can you decide between technical reasons and business reasons for the framerate conversion to 25 fps regardless of the source framerate? I'm speechless ...
