### ISSUE TITLE
add support for ccc.de

### ISSUE THREAD

**Issue by Siddhant** [rg3/youtube-dl#4890]
Sample URL: http://media.ccc.de/browse/congress/2013/30C3_-_5443_-_en_-_saal_g_-_201312281830_-_introduction_to_processor_design_-_byterazor.html#video

**Comment by robin007bond** [comment]
Works for me already:
```
youtube-dl 'http://media.ccc.de/browse/congress/201
3/30C3_-_5443_-_en_-_saal_g_-_201312281830_-_introduction_to_processor_design_-_byterazor.html#video'
[generic] 30C3_-_5443_-_en_-_saal_g_-_201312281830_-_introduction_to_processor_design_-_byterazor: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 30C3_-_5443_-_en_-_saal_g_-_201312281830_-_introduction_to_processor_design_-_byterazor: Downloading webpage
[generic] 30C3_-_5443_-_en_-_saal_g_-_201312281830_-_introduction_to_processor_design_-_byterazor: Extracting information
[download] Destination: C3TV - Introduction to Processor Design-30c3-5443-en-Introduction_to_Processor_Design_h264-iprod.mp4
[download]  15.3% of 73.22MiB at  1.84MiB/s ETA 00:33
```

**Comment by Siddhant** [comment]
> But being able to download the hq-versions would be nice. 

Exactly. youtube-dl ought to defalt to the HQ version.
Btw, the link to to the HQ mp4 is directly available on the site. Maybe youtube-dl can simply download that. (But rename it to a better name.)

**Comment by robin007bond** [comment]
That's because it doesn't have its own extractor. It searches the page for the first MP4-link and downloads it.

**Comment by phihag** [comment]
Thank you for the report. youtube-dl 2105.02.10.3 and newer add (the long overdue) proper support for CCC. See [our FAQ](https://yt-dl.org/update) if you need help updating.
