### ISSUE TITLE
Installing youtube-dl for Windows - not working!

### ISSUE THREAD

**Issue by Nevflinn** [rg3/youtube-dl#4891]
Hi,

I've downloaded the .exe file and attempted to set it up, but every time I access it in my files it opens a command box, closes immediately and nothing happens. Is there something I should be doing which I'm not?

Any help I could get on this issue would be very valuable.

Kind regards.

**Comment by phihag** [comment]
youtube-dl is a [command-line program](https://en.wikipedia.org/wiki/Command-line_interface). Open a command prompt - either of bash, powershell or cmd should work fine.

You can press <kbd>Shift</kbd> in the directory of the exe file, right-click and select "Open Command Window here") and then type `youtube-dl "http://www.youtube.com/watch?v=BaW_jenozKc"`.

If you are looking for a graphical program, there are various third-party wrappers for youtube-dl, including [youtube-dl-gui](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/README.md) and [win-youtube-dl](https://github.com/fredyw/win-youtube-dl/blob/master/README.md).
