### ISSUE TITLE
Youtube - ssl: certificate_verify_failed

### ISSUE THREAD

**Issue by tremd** [rg3/youtube-dl#4896]
> python youtube-dl --verbose https://www.youtube.com/watch?v=wnuCSmqC7tI

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=wnuCSm
qC7tI']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.02.06
[debug] Python version 2.7.9 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] wnuCSmqC7tI: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILE
D] certificate verify failed (_ssl.c:581)> (caused by URLError(SSLError(1, u'[SS
L: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))
  File "youtube-dl\youtube_dl\extractor\common.py", line 301, in _request_webpag
e
    return self._downloader.urlopen(url_or_request)
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 1578, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "youtube-dl\youtube_dl\utils.py", line 665, in https_open
    req, *_kwargs)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)

**Comment by jaimeMF** [comment]
Can you check if it works with the `--no-check-certificate` option?

**Comment by tremd** [comment]
It works. But why windows certificate verify failed?

**Comment by jaimeMF** [comment]
We'll have to investigate the issue, using that option is a workaround (unsafe of course).

**Comment by tremd** [comment]
Is it only me?

**Comment by jaimeMF** [comment]
It works for me on windows both with python 2.7.9 and 3.4.2

**Comment by tremd** [comment]
I try python 2.7.8 and i don't get the error.

**Comment by jaimeMF** [comment]
But 2.7.8 can't verify the certificates, so it' she same as using the `--no-check-certificate` option. Are you willing to run youtube-dl from the source code with a small change to check if it loads the certificates?

**Comment by tremd** [comment]
i didn't know that. 

so this is a windows/python problem cause of my configuration.

i think the problem is "windows function activate/deactivate" under system control.
i removed the IE complete. 

python request something from ie to verify ssl?

without removing IE in a vm (win7) all seems fine.

**Comment by jaimeMF** [comment]
I don't really know, I think it uses the system certificates but I don't know how it gets them.

**Comment by siso** [comment]
I get the same error on FreeBSD, `Python 2.7.9`, and `youtube-dl==2015.4.17`:

```shell
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))
```

**Comment by siso** [comment]
I get the same error on FreeBSD, `Python 2.7.9`, and `youtube-dl==2015.4.17`:

```shell
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))
```
Unfortunately `--no-check-certificate` does not work for me.

**Comment by Sevyls** [comment]
got the same error on OS X 10.10:

````
$ youtube-dl -F --verbose https://www.youtube.com/watch?v=#####
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'--verbose', u'https://www.youtube.com/watch?v=#####']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.2.3
[debug] Proxy map: {}
[youtube] #####: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 713, in https_open
    req, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
````

**Comment by jaimeMF** [comment]
@Sevyls  that's not an issue with youtube-dl, it's caused by the openssl installed with Homebrew. Try with the solutions listed in these comments: https://github.com/rg3/youtube-dl/issues/5317#issuecomment-94205465 and https://github.com/rg3/youtube-dl/issues/5317#issuecomment-94214004.

**Comment by akiraaisha** [comment]
This works on me in Windows. Clearing SSL Cache. Hope it helps.  
**`Internet Options->Content->Clear SSL State`**

**Comment by yan12125** [comment]
Thanks for the tip! I believe it can help others, so I copied it to #7309, which is the main issue for certificate errors on Windows. If you have any further findings, just leave comments there.
