### ISSUE TITLE
still problem with aparat

### ISSUE THREAD

**Issue by soha1410** [rg3/youtube-dl#4897]
youtube-dl http://www.aparat.com/v/oBQi4 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.aparat.com/v/oBQi4', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.06
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Aparat] oBQi4: Downloading webpage
ERROR: No working video URLs found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 619, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 268, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/aparat.py", line 45, in _real_extract
    raise ExtractorError('No working video URLs found')
ExtractorError: No working video URLs found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.02.09 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
