### ISSUE TITLE
Twitch vod download doesn't start from the beginning

### ISSUE THREAD

**Issue by Caide** [rg3/youtube-dl#4898]
If I try to download a vod that hasn't finished being recorded (the streamer is still streaming), it starts downloading live instead of at the start of the vod.  I don't think this is intentional, or is there a way to start downloading from the beginning?

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by Caide** [comment]
D:\>youtube-dl --verbose http://www.twitch.tv/adren_tv/v/3766262
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.twitch.tv/adren_tv/v/376626
2']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.02.06
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-59158-g745c40a, ffprobe N-59158-g745c40a
[debug] Proxy map: {}
[twitch:vod] 3766262: Downloading vod info JSON
[twitch:vod] 3766262: Downloading vod access token
[twitch:vod] 3766262: Downloading m3u8 information
[debug] Invoking downloader on u'http://vod.ak.hls.ttvnw.net/v1/AUTH_system/vods
_8243/adren_tv_13054354944_202053816/chunked/index-dvr.m3u8'
[download] Destination: @liquidadren _ Giveaway - AWP - Man-o'-war for subs-v376
6262.mp4
ffmpeg version N-59158-g745c40a Copyright (c) 2000-2013 the FFmpeg developers
  built on Dec 16 2013 22:06:09 with gcc 4.8.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetyp
e --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --ena
ble-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-l
ibopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libsp
eex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aa
cenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavp
ack --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      53.  0.100 / 53.  0.100
  libavcodec     55. 45.101 / 55. 45.101
  libavformat    55. 22.100 / 55. 22.100
  libavdevice    55.  5.102 / 55.  5.102
  libavfilter     4.  0.100 /  4.  0.100
  libswscale      2.  5.101 /  2.  5.101
  libswresample   0. 17.104 /  0. 17.104
  libpostproc    52.  3.100 / 52.  3.100
[mpegts @ 00000000072904a0] probed stream 2 failed
[mpegts @ 00000000072904a0] Could not find codec parameters for stream 2 (Unknow
n: none (ID3  / 0x20334449)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[hls,applehttp @ 0000000000387240] Estimating duration from bitrate, this may be
 inaccurate
[hls,applehttp @ 0000000000387240] Could not find codec parameters for stream 2
(Unknown: none (ID3  / 0x20334449)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, hls,applehttp, from 'http://vod.ak.hls.ttvnw.net/v1/AUTH_system/vods_8
243/adren_tv_13054354944_202053816/chunked/index-dvr.m3u8':
  Duration: 00:00:21.75, start: 16916.448000, bitrate: 128 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 12
8 kb/s
    Stream #0:1: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709)
, 1280x720, 60 fps, 60 tbr, 90k tbn, 120 tbc
    Stream #0:2: Unknown: none (ID3  / 0x20334449)
Output #0, mp4, to '@liquidadren _ Giveaway - AWP - Man-o'-war for subs-v3766262
.mp4.part':
  Metadata:
    encoder         : Lavf55.22.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720, q=2-31
, 60 fps, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 128 kb/s

Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  479 fps=0.0 q=-1.0 size=    3108kB time=00:00:08.00 bitrate=3182.7kbits/
frame=  549 fps=492 q=-1.0 size=    3565kB time=00:00:09.11 bitrate=3203.2kbits/
frame=  719 fps= 16 q=-1.0 size=    4708kB time=00:00:11.98 bitrate=3217.2kbits/
frame=  786 fps= 18 q=-1.0 size=    5234kB time=00:00:13.06 bitrate=3281.0kbits/
frame=  959 fps= 21 q=-1.0 size=    6465kB time=00:00:16.00 bitrate=3310.3kbits/
frame= 1061 fps= 23 q=-1.0 size=    7126kB time=00:00:17.65 bitrate=3307.4kbits/
frame= 1203 fps= 26 q=-1.0 size=    7982kB time=00:00:20.01 bitrate=3266.4kbits/
frame= 1415 fps= 30 q=-1.0 size=    9611kB time=00:00:23.55 bitrate=3342.9kbits/
frame= 1463 fps= 31 q=-1.0 size=    9827kB time=00:00:24.35 bitrate=3305.9kbits/
frame= 1650 fps= 35 q=-1.0 size=   11038kB time=00:00:27.46 bitrate=3292.0kbits/
frame= 1726 fps= 36 q=-1.0 size=   11684kB time=00:00:28.73 bitrate=3330.7kbits/
frame= 1919 fps= 39 q=-1.0 size=   12984kB time=00:00:32.00 bitrate=3323.9kbits/
frame= 2116 fps= 43 q=-1.0 size=   14189kB time=00:00:35.23 bitrate=3299.0kbits/
frame= 2274 fps= 45 q=-1.0 size=   15211kB time=00:00:37.86 bitrate=3290.6kbits/
frame= 2393 fps= 47 q=-1.0 size=   16177kB time=00:00:39.89 bitrate=3321.9kbits/
frame= 2450 fps= 48 q=-1.0 size=   16589kB time=00:00:40.80 bitrate=3330.6kbits/
frame= 2633 fps= 51 q=-1.0 size=   17671kB time=00:00:43.90 bitrate=3297.2kbits/
frame= 2793 fps= 54 q=-1.0 size=   18929kB time=00:00:46.51 bitrate=3333.4kbits/
frame= 2873 fps= 54 q=-1.0 size=   19437kB time=00:00:47.89 bitrate=3324.6kbits/
frame= 3057 fps= 57 q=-1.0 size=   20659kB time=00:00:50.91 bitrate=3323.7kbits/
frame= 3115 fps= 58 q=-1.0 size=   21089kB time=00:00:51.90 bitrate=3328.5kbits/
frame= 3285 fps= 61 q=-1.0 size=   22233kB time=00:00:54.71 bitrate=3328.6kbits/
frame= 3460 fps= 63 q=-1.0 size=   23255kB time=00:00:57.63 bitrate=3305.4kbits/
frame= 3585 fps= 65 q=-1.0 size=   24123kB time=00:00:59.75 bitrate=3307.1kbits/
frame= 3768 fps= 68 q=-1.0 size=   25342kB time=00:01:02.76 bitrate=3307.5kbits/
frame= 3914 fps= 69 q=-1.0 size=   26346kB time=00:01:05.20 bitrate=3310.2kbits/
frame= 4065 fps= 71 q=-1.0 size=   27376kB time=00:01:07.75 bitrate=3309.9kbits/
frame= 4166 fps= 72 q=-1.0 size=   28026kB time=00:01:09.40 bitrate=3308.2kbits/
frame= 4305 fps= 44 q=-1.0 size=   29146kB time=00:01:11.76 bitrate=3327.0kbits/
frame= 4388 fps= 44 q=-1.0 size=   29554kB time=00:01:13.10 bitrate=3311.9kbits/
frame= 4545 fps= 46 q=-1.0 size=   30629kB time=00:01:15.75 bitrate=3312.2kbits/
frame= 4749 fps= 47 q=-1.0 size=   32086kB time=00:01:19.11 bitrate=3322.2kbits/
frame= 4855 fps= 48 q=-1.0 size=   32873kB time=00:01:20.88 bitrate=3329.4kbits/
frame= 5025 fps= 50 q=-1.0 size=   34056kB time=00:01:23.75 bitrate=3331.0kbits/
frame= 5229 fps= 51 q=-1.0 size=   35250kB time=00:01:27.11 bitrate=3314.7kbits/
frame= 5360 fps= 52 q=-1.0 size=   36145kB time=00:01:29.30 bitrate=3315.7kbits/
frame= 5469 fps= 53 q=-1.0 size=   36889kB time=00:01:31.15 bitrate=3315.1kbits/
frame= 5568 fps= 54 q=-1.0 size=   37556kB time=00:01:32.76 bitrate=3316.5kbits/
frame= 5709 fps= 55 q=-1.0 size=   38517kB time=00:01:35.16 bitrate=3315.5kbits/
frame= 5916 fps= 57 q=-1.0 size=   39913kB time=00:01:38.58 bitrate=3316.7kbits/
frame= 6063 fps= 58 q=-1.0 size=   41009kB time=00:01:41.01 bitrate=3325.6kbits/
frame= 6189 fps= 59 q=-1.0 size=   41796kB time=00:01:43.16 bitrate=3318.8kbits/
frame= 6272 fps= 59 q=-1.0 size=   42321kB time=00:01:44.50 bitrate=3317.6kbits/
frame= 6429 fps= 60 q=-1.0 size=   43401kB time=00:01:47.15 bitrate=3317.9kbits/
frame= 6524 fps= 61 q=-1.0 size=   44047kB time=00:01:48.70 bitrate=3319.5kbits/
frame= 6669 fps= 62 q=-1.0 size=   45116kB time=00:01:51.16 bitrate=3324.6kbits/
frame= 6902 fps= 64 q=-1.0 size=   46600kB time=00:01:55.00 bitrate=3319.3kbits/
frame= 6911 fps= 63 q=-1.0 size=   46656kB time=00:01:55.15 bitrate=3319.0kbits/
frame= 7113 fps= 65 q=-1.0 size=   48045kB time=00:01:58.51 bitrate=3320.9kbits/
frame= 7152 fps= 65 q=-1.0 size=   48283kB time=00:02:03.15 bitrate=3211.8kbits/
frame= 7360 fps= 67 q=-1.0 size=   49721kB time=00:02:06.61 bitrate=3216.9kbits/
frame= 7425 fps= 67 q=-1.0 size=   50290kB time=00:02:07.70 bitrate=3226.1kbits/
frame= 7629 fps= 50 q=-1.0 Lsize=   51848kB time=00:02:11.15 bitrate=3238.4kbits
/s
video:49607kB audio:2028kB subtitle:0 global headers:0kB muxing overhead 0.41332
6%
[ffmpeg] 53092749 bytes

____

I stopped downloading after a couple of minutes, but the two minutes I had was definitely recorded live five hours into the stream.

**Comment by dstftw** [comment]
http://www.twitch.tv/adren_tv/v/3766262 looks like this vod has already finished and it downloads properly from the beginning. Also downloading live for unfinished stream looks logical to me - it is not finished yet thus not available as static content.

**Comment by Caide** [comment]
The vod in question was live when I posted, downloading the vod of any stream still in progress will have the same issue.

It's an issue because the new twitch /v/ url vods update right away.  If you visit the vod page, you can immediately watch everything since the beginning of the stream.  Starting the download before the vod is over is pointless because you'll end up with an incomplete file.  E.g. I start downloading an hour into the stream, and when the stream ends at say 4 hours, I end up with a vod missing the first hour.  If I want the full vod, I'd have to re-download the vod to get the first hour.

**Comment by dstftw** [comment]
Vods in progress are downloaded from the beginning with the latest version.
