### ISSUE TITLE
run youtube-dl in background on debain/wdmycloud

### ISSUE THREAD

**Issue by sudhirkankal** [rg3/youtube-dl#4903]
I have installed it, and it works for url ..but want it to run in background job

**Comment by phihag** [comment]
I am not sure what your problem is. You can run *any* command in the background by adding `&` to the command line, or, if the process is already running, press <kbd>Ctrl</kbd>+<kbd>Z</kbd> to interrupt the process and enter `bg` to let it run in the background. You may also be interested in [screen](https://www.mattcutts.com/blog/a-quick-tutorial-on-screen/) and [cron](https://en.wikipedia.org/wiki/Cron).

All of these options should work fine with youtube-dl.

**Comment by sudhirkankal** [comment]
Hi,

I would like to see whether nohup will work ?

I tried .. but if we close putty session, the scripts disconnects

regards,
sudhir kankal

On Sun, Feb 8, 2015 at 9:56 PM, Philipp Hagemeister <
notifications@github.com> wrote:

> I am not sure what your problem is. You can run *any* command in the
> background by adding & to the command line, or, if the process is already
> running, press Ctrl+Z to interrupt the process and enter bg to let it run
> in the background. You may also be interested in screen
> <https://www.mattcutts.com/blog/a-quick-tutorial-on-screen/> and cron
> <https://en.wikipedia.org/wiki/Cron>.
>
> All of these options should work fine with youtube-dl.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rg3/youtube-dl/issues/4903#issuecomment-73418046>.
>



-- 
Regards,
Sudhir Kankal

**Comment by phihag** [comment]
I am not sure what you mean by `the scripts` or `disconnects`, but youtube-dl works fine with nohup, too:
```
phihag@ytdl-test:~$ nohup youtube-dl --rate-limit 1k BaW_jenozKc >ytdl.log &
[1] 5934
phihag@ytdl-test:~$ nohup: ignoring input and redirecting stderr to stdout
cat ytdl.log && exit
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Extracting video information
[youtube] BaW_jenozKc: Downloading DASH manifest
[download] Destination: youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.mp4
[download]   4.3% of 1.53MiB at  1.33KiB/s ETA 18:44logout
Connection to ytdl-test.phihag.de closed.
phihag@t4:~$ ssh ytdl-test.phihag.de

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Feb  8 20:21:41 2015 from 2001:4dd0:ff00:336::2
phihag@ytdl-test:~$ cat ytdl.log 
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Extracting video information
[youtube] BaW_jenozKc: Downloading DASH manifest
[download] Destination: youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.mp4
[download]   4.8% of 1.53MiB at  1.10KiB/s ETA 22:37
phihag@ytdl-test:~$
```

If you want us to help you, you need to provide more information, for example a log that shows that (and how) youtube-dl fails. Remember that you can always use screen too.

**Comment by sudhirkankal** [comment]
i will try tonight and confirm you. Thanks. I think I missed out using '&'
character at end of nohup command.

On Mon, Feb 9, 2015 at 12:50 AM, Philipp Hagemeister <
notifications@github.com> wrote:

> I am not sure what you mean by the scripts or disconnects, but youtube-dl
> works fine with nohup, too:
>
> phihag@ytdl-test:~$ nohup youtube-dl --rate-limit 1k BaW_jenozKc >ytdl.log &
> [1] 5934
> phihag@ytdl-test:~$ nohup: ignoring input and redirecting stderr to stdout
> cat ytdl.log && exit
> [youtube] BaW_jenozKc: Downloading webpage
> [youtube] BaW_jenozKc: Extracting video information
> [youtube] BaW_jenozKc: Downloading DASH manifest
> [download] Destination: youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.mp4
> [download]   4.3% of 1.53MiB at  1.33KiB/s ETA 18:44logout
> Connection to ytdl-test.phihag.de closed.
> phihag@t4:~$ ssh ytdl-test.phihag.de
>
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
>
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
> Last login: Sun Feb  8 20:21:41 2015 from 2001:4dd0:ff00:336::2
> phihag@ytdl-test:~$ cat ytdl.log
> [youtube] BaW_jenozKc: Downloading webpage
> [youtube] BaW_jenozKc: Extracting video information
> [youtube] BaW_jenozKc: Downloading DASH manifest
> [download] Destination: youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.mp4
> [download]   4.8% of 1.53MiB at  1.10KiB/s ETA 22:37
> phihag@ytdl-test:~$
>
> If you want us to help you, you need to provide more information, for
> example a log that shows that (and how) youtube-dl fails. Remember that you
> can always use screen too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rg3/youtube-dl/issues/4903#issuecomment-73426514>.
>



-- 
Regards,
Sudhir Kankal
