### ISSUE TITLE
Help with php script

### ISSUE THREAD

**Issue by alduccino** [rg3/youtube-dl#4905]
Hi,

I'm using the code from here https://github.com/rg3/youtube-dl/issues/711#issuecomment-14020865 , it's working fine, but I was wondering if someone could help me to add a form to post the url and submit it to the script.

Edit : I found how to do it.
If anyone is interested edit :+1: 
$url = 'https://www.youtube.com/watch?v=GMuZdN84PJg';
$cmd = '/usr/bin/python /usr/local/bin/youtube-dl -o "/path/to/your/folder/%(id)s.%(ext)s" ' . escapeshellarg($url);

to:
$cmd = '/usr/bin/python /usr/local/bin/youtube-dl -o "/path/to/your/folder/%(id)s.%(ext)s" ' . escapeshellarg($_POST["url"]);

and create an html file in the same folder with this content:
http://img.alduccino.com/images/2015/02/08/b900ce063bc7a7acc4e3e1d48d4dbad2.jpg

Best regards, Mike.

**Comment by jaimeMF** [comment]
I'm closing this, since it's not a problem with youtube-dl, and you have found the answer.
