### ISSUE TITLE
Cannot download from arte.tv

### ISSUE THREAD

**Issue by goundoulf** [rg3/youtube-dl#4912]
$ youtube-dl -v http://videos.arte.tv/fr/videos/the-end-du-collectif-incognito--7829546.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://videos.arte.tv/fr/videos/the-end-du-collectif-incognito--7829546.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.06
[debug] Python version 2.7.8 - Linux-3.16.0-29-generic-i686-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 1.2.6-7, avprobe 1.2.6-7, ffmpeg 1.2.6-7, ffprobe 1.2.6-7, rtmpdump 2.4
[debug] Proxy map: {}
[arte.tv] 7829546: Downloading metadata
[arte.tv] 7829546: Downloading configuration
[debug] Invoking downloader on u'rtmp://artestras.fcod.llnwd.net/a3903/o35/'
[download] Destination: 'The End' du Collectif Incognito-7829546.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmp://artestras.fcod.llnwd.net/a3903/o35/ -o ''"'"'The End'"'"' du Collectif Incognito-7829546.flv.part' --playpath 'mp4:geo/videothek/ALL/arteprod/2014/03/28/ARTE7829546_FR_316637_16by9_800_MP4?h=d1456e05f34a35c4ce26965d6de81ce9'
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : artestras.fcod.llnwd.net
[rtmpdump] DEBUG: Parsed app     : a3903/o35
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : artestras.fcod.llnwd.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:geo/videothek/ALL/arteprod/2014/03/28/ARTE7829546_FR_316637_16by9_800_MP4?h=d1456e05f34a35c4ce26965d6de81ce9
[rtmpdump] DEBUG: tcUrl    : rtmp://artestras.fcod.llnwd.net:1935/a3903/o35
[rtmpdump] DEBUG: app      : a3903/o35
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Type Answer   : 03
[rtmpdump] DEBUG: HandShake: Server Uptime : 1600983953
[rtmpdump] DEBUG: HandShake: FMS Version   : 4.0.3.1
[rtmpdump] WARNING: HandShake: client signature does not match!
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 2500000
[rtmpdump] DEBUG: HandleClientBW: client BW = 2500000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 242 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:	FMS/4,0,3,4044>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:	255.00>
[rtmpdump] DEBUG: Property: <Name:               mode, NUMBER:	1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Connection succeeded.>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:	0.00>
[rtmpdump] DEBUG: Property: <Name:               data, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            version, STRING:	4,0,3,4044>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 26, len: 3
[rtmpdump] DEBUG: HandleCtrl, SWFVerification ping received: 
[rtmpdump] ERROR: HandleCtrl: Ignoring SWFVerification request, use --swfVfy!
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 21 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWDone>
[rtmpdump] DEBUG: Invoking _checkbw
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: mp4:geo/videothek/ALL/arteprod/2014/03/28/ARTE7829546_FR_316637_16by9_800_MP4?h=d1456e05f34a35c4ce26965d6de81ce9
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 16419 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 307 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	error>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.StreamNotFound>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Failed to play geo/videothek/ALL/arteprod/2014/03/28/ARTE7829546_FR_316637_16by9_800_MP4; stream not found.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	geo/videothek/ALL/arteprod/2014/03/28/ARTE7829546_FR_316637_16by9_800_MP4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	pAA4gyQA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.StreamNotFound
[rtmpdump] ERROR: Closing connection: NetStream.Play.StreamNotFound
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : artestras.fcod.llnwd.net
[rtmpdump] DEBUG: Parsed app     : a3903/o35
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : artestras.fcod.llnwd.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:geo/videothek/ALL/arteprod/2014/03/28/ARTE7829546_FR_316637_16by9_800_MP4?h=d1456e05f34a35c4ce26965d6de81ce9
[rtmpdump] DEBUG: tcUrl    : rtmp://artestras.fcod.llnwd.net:1935/a3903/o35
[rtmpdump] DEBUG: app      : a3903/o35
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 382, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 372, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1353, in download
    res = self.extract_info(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 630, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1111, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1286, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1261, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 316, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 204, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 151, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 505, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 467, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by goundoulf** [comment]
Interesting URL:

http://va695_kewego-i.akamaihd.net/i/smil/111548e.smil/master.m3u8?kd_iid=74428b0b109s&kd_fid=63&kd_pk=a73ee8ffd0b9
http://va695_kewego-i.akamaihd.net/i/smil/111548e.smil/index_139264_av.m3u8?e=e0ef6b1f1d4124f5
http://va695_kewego-i.akamaihd.net/i/smil/111548e.smil/index_589824_av.m3u8?e=e0ef6b1f1d4124f5
http://va695_kewego-i.akamaihd.net/i/smil/111548e.smil/index_1048576_av.m3u8?e=e0ef6b1f1d4124f5
http://va695_kewego-i.akamaihd.net/i/smil/111548e.smil/segment1_589824_av.ts?e=e933a313f6018d5d
http://va695_kewego-i.akamaihd.net/i/smil/111548e.smil/segment2_589824_av.ts?e=e933a313f6018d5d
...

**Comment by clampak** [comment]
I thought there was support for arte.tv, but I can't download from there either. 

```
$ youtube-dl -v http://www.arte.tv/sites/de/festivals/africa-festival-2015/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.arte.tv/sites/de/festivals/africa-festival-2015/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.25
[debug] Python version 2.7.10 - CYGWIN_NT-5.1-2.0.4-0.287-5-3-i686-32bit
[debug] exe versions: ffmpeg N-72211-g451be67, ffprobe N-72211-g451be67, rtmpdump 2.4
[debug] Proxy map: {}
[generic] africa-festival-2015: Requesting header
WARNING: Falling back on generic information extractor.
[generic] africa-festival-2015: Downloading webpage
[generic] africa-festival-2015: Extracting information
ERROR: Unsupported URL: http://www.arte.tv/sites/de/festivals/africa-festival-2015/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1070, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/lib/python2.7/site-packages/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: junk after document element: line 3, column 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1636, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.arte.tv/sites/de/festivals/africa-festival-2015/
```

**Comment by yan12125** [comment]
@clampak Your problem is different. Please open a new issue.

**Comment by dstftw** [comment]
This video is no longer available.
