### ISSUE TITLE
svt play request

### ISSUE THREAD

**Issue by johny1** [rg3/youtube-dl#4914]
Hi. I would like support added for svt play. Here's a video url

http://www.svtplay.se/video/2609989/sm-veckan/sm-veckan-rally-final-sasong-1-sm-veckan-rally-final

------
>youtube-dl http://www.svtplay.se/video/2609989/sm-v
eckan/sm-veckan-rally-final-sasong-1-sm-veckan-rally-final
[generic] sm-veckan-rally-final-sasong-1-sm-veckan-rally-final: Requesting heade
r
WARNING: Falling back on generic information extractor.
[generic] sm-veckan-rally-final-sasong-1-sm-veckan-rally-final: Downloading webp
age
[generic] sm-veckan-rally-final-sasong-1-sm-veckan-rally-final: Extracting infor
mation
ERROR: Unsupported URL: http://www.svtplay.se/video/2609989/sm-veckan/sm-veckan-
rally-final-sasong-1-sm-veckan-rally-final; please report this issue on https://
yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include i
ts complete output. Make sure you are using the latest version; type  youtube-dl
 -U  to update.

**Comment by phihag** [comment]
Thank you for the report. youtube-dl 2015.02.09.3 and newer include support for svtplay. See [our FAQ](https://yt-dl.org/update) if you need help updating.
