### ISSUE TITLE
cannot download from pornhd.com

### ISSUE THREAD

**Issue by pureDL** [rg3/youtube-dl#4915]
Already running the latest version.

macbooks-air:~ macbook$ ./youtube-dl "http://www.pornhd.com/videos/3881/sexy-giselles-first-deepthroat-hd-porn-movie" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.pornhd.com/videos/3881/sexy-giselles-first-deepthroat-hd-porn-movie', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.09.3
[debug] Python version 2.7.5 - Darwin-13.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[PornHd] sexy-giselles-first-deepthroat-hd-porn-movie: Downloading webpage
ERROR: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 619, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 268, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/pornhd.py", line 49, in _real_extract
    r"(?s)'sources'\s*:\s*(\{.+?\})\s*\}\);", webpage, 'sources')))
  File "./youtube-dl/youtube_dl/extractor/common.py", line 524, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

macbooks-air:~ macbook$ ./youtube-dl -U
youtube-dl is up-to-date (2015.02.09.3)

**Comment by phihag** [comment]
Thank you for the report. I believe this issue to be fixed in youtube-dl 2015.02.10.3 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by pureDL** [comment]
Output with version 2015.02.10.3

macbooks-air:~ macbook$ ./youtube-dl -v http://www.pornhd.com/videos/3881/sexy-giselles-first-deepthroat-hd-porn-movie
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.pornhd.com/videos/3881/sexy-giselles-first-deepthroat-hd-porn-movie']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.10.2
[debug] Python version 2.7.5 - Darwin-13.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[PornHd] sexy-giselles-first-deepthroat-hd-porn-movie: Downloading webpage
ERROR: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 631, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 269, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/pornhd.py", line 49, in _real_extract
    r"(?s)'sources'\s*:\s*(\{.+?\})\s*\}\);", webpage, 'sources')))
  File "./youtube-dl/youtube_dl/extractor/common.py", line 531, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phihag** [comment]
Look closely at the output: You are using version 2015.02.10.2. Run `./youtube-dl -U` to update.

**Comment by pureDL** [comment]
Weird, I went to download the latest version from https://yt-dl.org/downloads/latest/youtube-dl then when I typed ./youtube-dl -U, it said I was using the latest version.

It's working now.  Thanks!

**Comment by phihag** [comment]
It can take a couple of minutes for the various caches along the way to clear, and to build and upload the new version in the first place.
