### ISSUE TITLE
Extractor for escapistmagazine.com loads only ad

### ISSUE THREAD

**Issue by StephSc** [rg3/youtube-dl#4919]
the following just downloads the first ad and not the video itself (which would usually be around 7mb):

youtube-dl http://www.escapistmagazine.com/videos/view/zero-punctuation/10020-Saints-Row-Gat-Out-Of-Hell
[Escapist] 10020: Extracting information
[Escapist] 10020: Downloading webpage
[Escapist] 10020: Downloading normal configuration
[Escapist] 10020: Downloading hq configuration
[download] Destination: Saints Row - Gat Out Of Hell-10020.mp4
[download] 100% of 2.38MiB in 00:01

**Comment by phihag** [comment]
Can you pos tthe complete output you get when you add the `-v` option? It works fine for me.

**Comment by StephSc** [comment]
Here it is (now it's obvious that it is the ad according to the "invoking downloader" line:

youtube-dl -v http://www.escapistmagazine.com/videos/view/zero-punctuation/10020-Saints-Row-Gat-Out-Of-Hell
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.escapistmagazine.com/videos/view/zero-punctuation/10020-Saints-Row-Gat-Out-Of-Hell']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.10.3
[debug] Python version 2.7.3 - Linux-3.16-0.bpo.2-amd64-x86_64-with-debian-7.8
[debug] exe versions: ffmpeg 1.0.10, ffprobe 1.0.10, rtmpdump 2.4
[debug] Proxy map: {}
[Escapist] 10020: Extracting information
[Escapist] 10020: Downloading webpage
[Escapist] 10020: Downloading normal configuration
[Escapist] 10020: Downloading hq configuration
[debug] Invoking downloader on u'http://video.escapistmagazine.com/mp4/escapist/sales-marketing/5387-4a7b988602b3d53a02653768b43bb191.mp4'
[download] Destination: Saints Row - Gat Out Of Hell-10020.mp4
[download] 100% of 2.38MiB in 00:01

**Comment by phihag** [comment]
youtube-dl 2015.10.2.5 are more careful in picking out the actual video. Can you test with that version? See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by StephSc** [comment]
Works again, thank you!

**Comment by phihag** [comment]
We've updated again, in youtube-dl 2015.02.26 and newer you should get the video again (note that it seems that after downloading the ad once, you get served that with the IP address instead of the video). By the way, in the upcoming release, you can also download the ad, simply pass in `--include-ads`!
