### ISSUE TITLE
No WAV, no MP3, download slowly

### ISSUE THREAD

**Issue by Soahr** [rg3/youtube-dl#4923]
Hello,
I have a problem with extracting .wav and .mp3
When I try to extract the audio from a youtube video, the file always comes in .m4a and the download takes several minutes.
I'm on Debian with ffmpeg and libav-tools up-to-date.

Can you help me? Thank you in advance

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by Soahr** [comment]
Thank you for your reply !
There is an example :

youtube-dl --verbose --extract-audio                                                                                                                   --audio-format wav http://www.youtube.com/watch?v=P2x3-b6JEj8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--extract-audio', '--audio-format', 'w                                                                                                                  av', 'http://www.youtube.com/watch?v=P2x3-b6JEj8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.10.5
[debug] Python version 2.7.3 - Linux-2.6.32-042stab102.9-x86_64-with-debian-7.8
[debug] exe versions: avconv 0.8.16-6, avprobe 0.8.16-6, ffmpeg 0.8.16-6, ffprob                                                                                                                  e 0.8.16-6
[debug] Proxy map: {}
[youtube] P2x3-b6JEj8: Downloading webpage
[youtube] P2x3-b6JEj8: Extracting video information
[youtube] {22} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {43} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {18} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {5} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {36} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {17} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {136} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {247} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {135} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {244} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {134} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {243} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {133} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {242} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {160} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {140} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] {171} signature length 43.42, html5 player en_US-vflr9O4a0
[youtube] P2x3-b6JEj8: Downloading DASH manifest
[debug] Invoking downloader on 'https://r19---sn-1gi7zn7z.googlevideo.com/videop                                                                                                                  layback?id=3f6c77f9be89123f&itag=141&source=youtube&requiressl=yes&ms=au&gcr=us&                                                                                                                  mv=m&pl=42&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=118248533&lmt=140103                                                                                                                  6839948665&dur=3708.923&mt=1423596015&key=dg_yt0&fexp=907263,927622,9405619,9406                                                                                                                  184,9406556,9406665,943917,947225,948124,948605,952302,952605,952612,952901,9553                                                                                                                  01,957201,959701&sver=3&upn=AfWmJWJwLtA&signature=76158779BD37B20CFD74C8EB6A5EE4                                                                                                                  B5C0473138.839AFB0C928A26E62B126EC6FA9968177FFF16CA&ip=2001:41d0:52:100::f4d&ipb                                                                                                                  its=0&expire=1423617750&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,gc                                                                                                                  r,mv,pl,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: David Guetta   Miami Ultra Music Festival 2014-P2x3-b6JE                                                                                                                  j8.m4a
[download]   2.8% of 112.77MiB at 69.87KiB/s ETA 26:46

**Comment by dstftw** [comment]
Can't tell you for sure until you post **full** log (the part after download completion is still missing) but outdated ffmpeg/avconv may cause that.

**Comment by Soahr** [comment]
Indeed, following the report warns me that avconv is not up to date.
Can you refer me what to do to update it properly?

Thank you very much for your help

youtube-dl --verbose --extract-audio --audio-format wav http://www.youtube.com/watch?v=slYTugKyedA
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--extract-audio', '--audio-format', 'wav', 'http://www.youtube.com/watch?v=slYTugKyedA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.10.5
[debug] Python version 2.7.3 - Linux-2.6.32-042stab102.9-x86_64-with-debian-7.8
[debug] exe versions: avconv 0.8.16-6, avprobe 0.8.16-6, ffmpeg 0.8.16-6, ffprobe 0.8.16-6
[debug] Proxy map: {}
[youtube] slYTugKyedA: Downloading webpage
[youtube] slYTugKyedA: Extracting video information
[youtube] slYTugKyedA: Downloading DASH manifest
[debug] Invoking downloader on 'https://r6---sn-1gi7zn7z.googlevideo.com/videoplayback?id=b25613ba02b279d0&itag=141&source=youtube&requiressl=yes&pl=42&ms=au&mv=m&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=7143091&lmt=1389667542454418&dur=224.026&sver=3&upn=IQtrrutBS7w&key=dg_yt0&signature=50F93DD56B37F4B71CCBDFC0BFA768EDEB7BA403.857E0A01B99688EED84B359E98666C4D16839C32&fexp=907263,916646,919514,923367,927622,934954,9405697,9406003,9406152,943917,944318,947225,948124,948802,951703,952302,952605,952612,952901,955301,957201,959701&mt=1423597120&ip=2001:41d0:52:100::f4d&ipbits=0&expire=1423618843&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,ms,mv,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Dubstep _ Duelle - Your Addiction (Disfigure Remix)-slYTugKyedA.m4a
[download] 100% of 6.81MiB in 01:46
[ffmpeg] Correcting container in "Dubstep _ Duelle - Your Addiction (Disfigure Remix)-slYTugKyedA.m4a"
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
[debug] ffmpeg command line: avconv -y -i 'Dubstep _ Duelle - Your Addiction (Disfigure Remix)-slYTugKyedA.m4a' -c copy -f mp4 'Dubstep _ Duelle - Your Addiction (Disfigure Remix)-slYTugKyedA.temp.m4a'
[avconv] Destination: Dubstep _ Duelle - Your Addiction (Disfigure Remix)-slYTugKyedA.wav
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
[debug] ffmpeg command line: avconv -y -i 'Dubstep _ Duelle - Your Addiction (Disfigure Remix)-slYTugKyedA.m4a' -vn -q:a 5 -f wav 'Dubstep _ Duelle - Your Addiction (Disfigure Remix)-slYTugKyedA.wav'
Deleting original file Dubstep _ Duelle - Your Addiction (Disfigure Remix)-slYTugKyedA.m4a (pass -k to keep)

**Comment by aimkeepachieve** [comment]
You may also follow this step by step guide to directly download YouTube to WAV, MP3, MP4, MOV, AVI, FLAC, M4A, WMV etc at http://www.allavsoft.com/how-to/convert-youtube-to-wav-mac-windows.html
