### ISSUE TITLE
Writing cache

### ISSUE THREAD

**Issue by amkrankruleuen** [rg3/youtube-dl#4930]
WARNING: Writing cache to u'/root/.cache/youtube-dl/youtube-sigfuncs/js_en_US-vflQkSGin_40.41.json' failed: Traceback (most recent ca$
File "/usr/local/bin/youtube-dl/youtube_dl/cache.py", line 46, in store
os.makedirs(os.path.dirname(fn))
File "/usr/lib/python2.7/os.py", line 150, in makedirs
makedirs(head, mode)
File "/usr/lib/python2.7/os.py", line 150, in makedirs
makedirs(head, mode)
File "/usr/lib/python2.7/os.py", line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/root/.cache'

root@abcd:~# ls -lah
drwxrwxrwx  6 root root 4.0K Dec 19 03:24 .cache

**Comment by phihag** [comment]
Are you running youtube-dl as root? You should not do that. Can you also post the full output you get when you add `-v` to the command-line, and run `id` afterwards? What happens if you run `mkdir /root/.cache/foo` in the command line?

**Comment by phihag** [comment]
By the way, you can use the `--cache-dir` option to specify a cache directory. This may help here.

**Comment by amkrankruleuen** [comment]
--cache-dir is good idea, is okay to "/tmp" directory. Thanks.
