### ISSUE TITLE
Support itele.fr URLs

### ISSUE THREAD

**Issue by Cigaes** [rg3/youtube-dl#4931]
Videos from itele.fr, for example this one:
http://www.itele.fr/france/video/aubervilliers-un-lycee-en-colere-111559
can be downloaded by the canalplus downloader, just by adding `itele.fr` to the regexp and the map.

**Comment by naglis** [comment]
Thanks! itele.fr URLs should be supported in the next release of youtube-dl.

**Comment by phihag** [comment]
Support for itele.fr has been added into youtube-dl 2015.02.11. See [our FAQ](https://yt-dl.org/update) if you need help updating.
