### ISSUE TITLE
history.com

### ISSUE THREAD

**Issue by ydlreporting** [rg3/youtube-dl#4934]
Hello! Could I please request that history.com be supported? A sample URL is http://www.history.com/topics/valentines-day/history-of-valentines-day/videos/bet-you-didnt-know-valentines-day

**Comment by dstftw** [comment]
history.com will be supported in the next version. Thanks for the report.

**Comment by phihag** [comment]
Support for history.com has been added in youtube-dl 2015.02.16. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by ydlreporting** [comment]
Thanks!
