### ISSUE TITLE
No audio on past Twitch broadcasts when beginning of the broadcast is muted due to copyright issues / Is it possible to specify FFMPEG options?

### ISSUE THREAD

**Issue by gabrieleliot** [rg3/youtube-dl#4935]
First off: Thanks, this is an awesome program and I love it.

Here's the issue: in general, youtube-dl works great with FFMPEG for Twitch past broadcasts. However, Twitch mutes the audio for portions of broadcasts that contain copyrighted songs playing during the stream. When the very first part of the broadcast is muted, FFMPEG is unable to determine the audio of the stream, as there is no audio for that portion. As a result, it will not download audio for the entire stream, even though there may only be a few minutes of muted content.

It seems like this situation might be remedied by being able to specify FFMPEG options, such as the by increasing the 'analyzeduration' and 'probesize' to cover a portion of content extending beyond the muted section at the beginning. Perhaps this is possible, but after much googling, I was unable to determine how this is done.

Also perhaps having the option to "probe" the file at another section other than the beginning might also work as if that other section had audio is seems as though FFMPEG would be able to know what it was doing, audio wise.

What follows is the CMD output from attempting to download a Twitch past broadcast where the first section is muted. I canceled the download shortly after starting but you can see in the summary that the audio size is 0 kB. I have previously completed this download and indeed there is no audio for the entire stream even though when viewing from the website only small portions are muted. This has also been the case for all Twitch past broadcasts where the first potion of the file is muted due to copyright issues.

Thank you for your help.

C:\Windows\System32>d:

D:\>cd yt

D:\yt>youtube-dl -U
youtube-dl is up-to-date (2015.02.11)

D:\yt>youtube-dl -v http://www.twitch.tv/drybear/v/3764649
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.twitch.tv/drybear/v/3764649']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.02.11
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-69351-gfb34c58
[debug] Proxy map: {}
[twitch:vod] 3764649: Downloading vod info JSON
[twitch:vod] 3764649: Downloading vod access token
[twitch:vod] 3764649: Downloading m3u8 information
[debug] Invoking downloader on u'http://vod.ak.hls.ttvnw.net/v1/AUTH_system/vods
_84c9/drybear_13043436352_201725506/chunked/index-dvr.m3u8'
[download] Destination: SMITE Time-v3764649.mp4
ffmpeg version N-69351-gfb34c58 Copyright (c) 2000-2015 the FFmpeg developers
  built on Jan 28 2015 02:36:35 with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-lib
modplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrw
b --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinge
r --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --en
able-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis
 --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-
libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enab
le-zlib
  libavutil      54. 18.100 / 54. 18.100
  libavcodec     56. 21.100 / 56. 21.100
  libavformat    56. 19.100 / 56. 19.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5.  9.101 /  5.  9.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[mpegts @ 00000000044f18a0] Could not find codec parameters for stream 0 (Audio:
 aac ([15][0][0][0] / 0x000F), 0 channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[hls,applehttp @ 00000000044c9880] Could not find codec parameters for stream 0
(Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp): unspecified sample rate

Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, hls,applehttp, from 'http://vod.ak.hls.ttvnw.net/v1/AUTH_system/vods_8
4c9/drybear_13043436352_201725506/chunked/index-dvr.m3u8':
  Duration: 05:59:05.75, start: 63.114000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp
    Stream #0:1: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709/
bt709/iec61966-2-1), 1280x720, 30 fps, 30 tbr, 90k tbn, 60 tbc
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
Output #0, mp4, to 'SMITE Time-v3764649.mp4.part':
  Metadata:
    encoder         : Lavf56.19.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720, q=2-31
, 30 fps, 30 tbr, 90k tbn, 90k tbc
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
Press [q] to stop, [?] for help
frame=  301 fps=0.0 q=-1.0 size=    4172kB time=00:00:10.48 bitrate=3259.7kbits/
frame=  518 fps=497 q=-1.0 size=    6873kB time=00:00:17.71 bitrate=3177.7kbits/
frame=  702 fps=455 q=-1.0 size=    9314kB time=00:00:23.85 bitrate=3199.0kbits/
frame=  899 fps=433 q=-1.0 size=   11893kB time=00:00:30.41 bitrate=3202.9kbits/
frame= 1069 fps=415 q=-1.0 size=   14167kB time=00:00:36.08 bitrate=3216.0kbits/
frame= 1261 fps=407 q=-1.0 size=   16874kB time=00:00:42.48 bitrate=3253.7kbits/
frame= 1451 fps=403 q=-1.0 size=   19334kB time=00:00:48.81 bitrate=3244.3kbits/
frame= 1619 fps=393 q=-1.0 size=   21419kB time=00:00:54.41 bitrate=3224.3kbits/
frame= 1785 fps=386 q=-1.0 size=   23656kB time=00:00:59.95 bitrate=3232.5kbits/
frame= 1981 fps=379 q=-1.0 size=   26368kB time=00:01:06.48 bitrate=3249.0kbits/
frame= 2161 fps=377 q=-1.0 size=   28758kB time=00:01:12.48 bitrate=3250.1kbits/
frame= 2340 fps=377 q=-1.0 Lsize=   30998kB time=00:01:18.45 bitrate=3236.9kbits
/s
video:30953kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing
 overhead: 0.146069%
[ffmpeg] 31742309 bytes

D:\yt>

**Comment by weedy** [comment]
--hls-prefer-native
dumps the stream exactly as twitch saved it

**Comment by gabrieleliot** [comment]
Thanks so much! That worked perfect. So many twitch streams begin with an empty chair and music playing with no game noise, which is a perfect situation for copyright based muting. I swear it seemed like 60% of past broadcast streams started muted and hence were not downloadable with audio before I read your reply.

Awesome. Thanks again :-)
