### ISSUE TITLE
Request: Per-domain configuration options

### ISSUE THREAD

**Issue by Fironet** [rg3/youtube-dl#4937]
I read through the docs and searched but didn't see a way to configure youtube-dl on a per-domain basis. This would be very useful as there are various domains I use different settings with, and having to change the settings for each is time consuming.

Being able to specify different youtube-dl settings per domain (such as Youtube, Comedy Central, Vimeo) in the config file would be a great addition to the functionality.

**Comment by jaimeMF** [comment]
Duplicate of #3101

**Comment by Fironet** [comment]
@jaimeMF Ah, searched but didn't find anything. Definitely has my support.
