### ISSUE TITLE
stream.cz JSON download http error 400

### ISSUE THREAD

**Issue by parkovanie** [rg3/youtube-dl#4940]
youtube-dl --verbose https://www.stream.cz/jidlo-s-r-o/10004829-chlazene-pastiky-2-malovyroba
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.stream.cz/jidlo-s-r-o/10004829-chlazene-pastiky-2-malovyroba']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.11
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-x86_64-with-LinuxMint-17-qiana
[debug] exe versions: ffmpeg 1.2.6-7, ffprobe 1.2.6-7, rtmpdump 2.4
[debug] Proxy map: {}
[StreamCZ] 10004829: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 400: BAD REQUEST (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 309, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1611, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by naglis** [comment]
This issue should be fixed in the next release of youtube-dl. Thanks for the report!

**Comment by parkovanie** [comment]
works perfectly :) thank you very much
