### ISSUE TITLE
Cannot extract from bambuser but I could a week ago before updates

### ISSUE THREAD

**Issue by Motorolo** [rg3/youtube-dl#4944]
motorolo@user-ubuntu:~$ youtube-dl --verbose http://bambuser.com/v/5272062
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://bambuser.com/v/5272062']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.11
[debug] Python version 2.7.6 - Linux-3.13.0-45-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, rtmpdump 2.4
[debug] Proxy map: {}
[bambuser] 5272062: Downloading webpage
ERROR: An extractor error has occured. (caused by KeyError(u'uid',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 270, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/bambuser.py", line 53, in _real_extract
    'uploader_id': info['uid'],
KeyError: u'uid'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 633, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 276, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'uid',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
It will be fixed in the next version, thanks for the report.

**Comment by phihag** [comment]
Fixed in youtube-dl 2015.02.16. See [our FAQ](https://yt-dl.org/update) if you need help updating.
