### ISSUE TITLE
Proxy Authentication

### ISSUE THREAD

**Issue by nimatrueway** [rg3/youtube-dl#4952]
Hey guys !
This is really one of the most extremely useful and powerful tools I've ever seen, I really appreciate it.

If I knew Python I'd have done it myself but unfortunately I'm a Java programmer. So I wanted to ask whenever it's possible please add a support for "Proxy Authentication" and command-line parameters for entering proxy username/password.

Thanks

**Comment by phihag** [comment]
You can already do that:
```
youtube-dl --proxy "http://nimatrueway:secret@proxy-server.example:8000" BaW_jenozKc
```

Alternatively, set it in [your configuration file](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration) or via the `http_proxy`/`https_proxy` environment variables.
