### ISSUE TITLE
Download only a portion of a video

### ISSUE THREAD

**Issue by dquispe** [rg3/youtube-dl#4956]
Hey!

I'd like to be able to download a portion of a video only. For example, being able to specify a start and/or end time for downloading. So, when a user inputs a start and end time of a video, it should only download the portion of the clip within the time stamps. Would this be possible?

Thanks!

**Comment by jaimeMF** [comment]
Currently it's not supported, see https://github.com/rg3/youtube-dl/issues/4821#issuecomment-72213508 for more info
