### ISSUE TITLE
RTL Nieuws/XL

### ISSUE THREAD

**Issue by joepie91** [rg3/youtube-dl#4959]
Currently the Dutch news site RTL Nieuws (using RTL XL as their backend) is not supported by `youtube-dl`, even though RTL XL itself (when specifying an RTL XL URL) *is* supported. I have written an implementation that downloads all the videos from an RTL Nieuws article [here](https://gist.github.com/joepie91/deec04208000c8e54040) in Node/CoffeeScript, but don't have the time to learn how to write code for `youtube-dl` or to work on and test the actual plugin.

Perhaps somebody working on `youtube-dl` could use this approach to update the RTL XL code (`rtlnl.py`) to also be able to parse RTL Nieuws URLs? An example page with multiple videos is http://www.rtlnieuws.nl/nieuws/buitenland/aanslagen-kopenhagen.

**Comment by phihag** [comment]
Thank you for the report. youtube-dl 2015.02.16.1 and newer add support for embedded rtl.nl videos. See [our FAQ](https://yt-dl.org/update) if you have trouble updating.
