### ISSUE TITLE
VeeHD Extractor Broken

### ISSUE THREAD

**Issue by aerobit** [rg3/youtube-dl#4965]
pi@raspberrypi ~ $ youtube-dl http://veehd.com/video/4665804_Tell-No-One-Ne-le-dis-a-personne-2006-French-EngSoftSubs-Re-Up --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://veehd.com/video/4665804_Tell-No-One-Ne-le-dis-a-personne-2006-French-EngSoftSubs-Re-Up', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.16.1
[debug] Python version 2.7.3 - Linux-3.12.35+-armv6l-with-debian-7.6
[debug] exe versions: avconv 9.14-6, avprobe 9.14-6, ffmpeg 0.8.13-6, rtmpdump 2.4
[debug] Proxy map: {}
[VeeHD] 4665804: Requesting webpage
[VeeHD] 4665804: Downloading webpage
[VeeHD] 4665804: Requesting player page
[VeeHD] 4665804: Downloading player page
ERROR: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 633, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 270, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/veehd.py", line 59, in _real_extract
    r'<iframe[^>]+src="/?([^"]+)"', player_page, 'iframe url')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 532, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

pi@raspberrypi ~ $ youtube-dl --version
2015.02.16.1

**Comment by naglis** [comment]
Hi, this seems to use a different Veehd player, which is not yet supported by youtube-dl and I would like to add a test case for it, however, [I can't do that](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free), because the video on your provided URL contains copyrighted material. Could you provide another URL (with freely available content) where the same error happens?

**Comment by yan12125** [comment]
VeeHD extractor is fixed so that avi/divx videos can be downloaded in the next version.

@naglis Sorry I accidently commited the video with copyright issues into test cases but I've already replaced it with a publicly availble tralier in 482a1258de6af0a15b6e7859d244f9125cadef47
