### ISSUE TITLE
unable to download a videolectures.net video

### ISSUE THREAD

**Issue by notuntoward** [rg3/youtube-dl#4968]
I'm unable to download the lecture from this URL:  http://videolectures.net/nips09_hinton_dlmi/
Using the trial version of getflv, I'm able to download the 1st few minutes, so apparently, there's nothing prohibiting a download, or at least it's possible to get around it.

Using the youtube-dl windows executable and cygwin (which does work for other videolectures.net urls), here's the error:

$ youtube-dl --verbose http://videolectures.net/nips09_hinton_dlmi/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://videolectures.net/nips09_hinton_dlmi/']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.02.16.1
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {'http': '10.13.13.5:3128', u'https': '10.13.13.5:3128'}
[videolectures.net] nips09_hinton_dlmi: Downloading XML
[debug] Invoking downloader on 'http://hydro.ijs.si/v007/e7/47onolszaysxm4gtj43qi7jfsmtfk5ib.flv'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1320, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1295, in dl
  File "youtube_dl\downloader\common.pyo", line 316, in download
  File "youtube_dl\downloader\http.pyo", line 66, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1611, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden
$ youtube-dl --verbose http://videolectures.net/nips09_hinton_dlmi/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://videolectures.net/nips09_hinton_dlmi/']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.02.16.1
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {'http': '10.13.13.5:3128', u'https': '10.13.13.5:3128'}
[videolectures.net] nips09_hinton_dlmi: Downloading XML
[debug] Invoking downloader on 'http://hydro.ijs.si/v007/e7/47onolszaysxm4gtj43qi7jfsmtfk5ib.flv'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1320, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1295, in dl
  File "youtube_dl\downloader\common.pyo", line 316, in download
  File "youtube_dl\downloader\http.pyo", line 66, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1611, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden

**Comment by dstftw** [comment]
Thanks for the report, this will be fixed in the next version.

**Comment by phihag** [comment]
Fixed in youtube-dl 2015.02.17.2. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by notuntoward** [comment]
Thanks, this does now download something, but there's a problem with the result:  The download appears to be made of chunks which are spliced together with overlap instead of being butted together.  So, for example, at time=01:00 minutes, the video may jump back to five seconds to time=0:55, then play until time=01:30, and then jump back to time 01:20 (actually, the pattern is not that regular.  I'm not sure what it is).

At least, the output with the verbose flag does show that the video is being downloaded in chunks:

youtube-dl --verbose http://videolectures.net/nips09_hinton_dlmi

<many lines omitted...>
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 24 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 44 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Data.Start>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 224 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:	3251.64>
[rtmpdump] DEBUG: Property: <Name:              width, NUMBER:	352.00>
[rtmpdump] DEBUG: Property: <Name:             height, NUMBER:	288.00>
[rtmpdump] DEBUG: Property: <Name:      videodatarate, NUMBER:	300.00>
[rtmpdump] DEBUG: Property: <Name:          framerate, NUMBER:	25.00>
[rtmpdump] DEBUG: Property: <Name:       videocodecid, NUMBER:	4.00>
[rtmpdump] DEBUG: Property: <Name:      audiodatarate, NUMBER:	64.00>
[rtmpdump] DEBUG: Property: <Name:         audiodelay, NUMBER:	0.05>
[rtmpdump] DEBUG: Property: <Name:       audiocodecid, NUMBER:	2.00>
[rtmpdump] DEBUG: Property: <Name:       canSeekToEnd, BOOLEAN:	TRUE>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] INFO: Metadata:
[rtmpdump] INFO:   duration              3251.64
[rtmpdump] INFO:   width                 352.00
[rtmpdump] INFO:   height                288.00
[rtmpdump] INFO:   videodatarate         300.00
[rtmpdump] INFO:   framerate             25.00
[rtmpdump] INFO:   videocodecid          4.00
[rtmpdump] INFO:   audiodatarate         64.00
[rtmpdump] INFO:   audiodelay            0.05
[rtmpdump] INFO:   audiocodecid          2.00
[rtmpdump] INFO:   canSeekToEnd          TRUE
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 32, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream BufferReady 1
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 31, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream BufferEmpty 1
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 32, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream BufferReady 1
[download]  99.7% of ~359.74MiB at 781.22KiB/s ETA 00:01     
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 31, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream BufferEmpty 1
[rtmpdump] DEBUG: RTMP_SendPause, 1, pauseTime=3244251
[rtmpdump] DEBUG: Invoking pause
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 32, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream BufferReady 1
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 31, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream BufferEmpty 1
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 1, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream EOF 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 102 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Complete>
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:	0.00>
[rtmpdump] DEBUG: Property: <Name:              bytes, NUMBER:	0.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 1, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream EOF 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 232 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Stop>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Stopped playing v007/e7/47onolszaysxm4gtj43qi7jfsmtfk5ib.flv.>
[rtmpdump] DEBUG: Property: <Name:           clientid, NUMBER:	2144891730.00>
[rtmpdump] DEBUG: Property: <Name:             reason, STRING:	>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	v007/e7/47onolszaysxm4gtj43qi7jfsmtfk5ib.flv>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Stop
[rtmpdump] DEBUG: Invoking deleteStream
[rtmpdump] DEBUG: Got Play.Complete or Play.Stop from server. Assuming stream is complete
[download] 358.85MiB at 782.23KiB/s (07:49)                  
[rtmpdump] DEBUG: RTMP_Read returned: 0
[rtmpdump] Download complete
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 376281107 bytes

**Comment by phihag** [comment]
I believe these glitches to be fixed in youtube-dl 2015.02.19.3. Again, see [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by notuntoward** [comment]
Yes, thanks, the download now works.  I'm not sure if this is related, but
it now downloads at what seems to be streaming speed -- a 46 minute lecture
took about 46 minutes to download.  If that's how it has to be, well, I'm
still pretty happy.

**Comment by naglis** [comment]
@notuntoward, yes, it's related - we've passed the `--realtime` flag to rtmpdump which is a known workaround for the issue of video jumping back all over again [[1](http://lists.mplayerhq.hu/pipermail/rtmpdump/2012-July/002032.html)] and yes, the slowdown is the consequence of that :disappointed:
