### ISSUE TITLE
Unable to extract playlist JSON on patreon.com

### ISSUE THREAD

**Issue by TheGr33k** [rg3/youtube-dl#4969]
youtube-dl -v  https://www.patreon.com/creation?hid=1682498

`[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.patreon.com/creation?hid=1682498']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.16.1
[debug] Python version 3.4.2 - Linux-2.6.32-504.8.1.el6.x86_64-x86_64-with-centos-6.6-Final
[debug] exe versions: none
[debug] Proxy map: {}
[Patreon] 1682498: Downloading webpage
ERROR: Unable to extract playlist JSON; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 633, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 270, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/patreon.py", line 85, in _real_extract
    webpage, 'playlist JSON')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract playlist JSON; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output`

**Comment by phihag** [comment]
Thank you for the report. Support for embedly videos in patreon has been added in youtube-dl 2015.02.19.1. See [our FAQ](https://yt-dl.org/update) if you have trouble updating.
