### ISSUE TITLE
Not able to pick the "source" streams from Twitch

### ISSUE THREAD

**Issue by realnc** [rg3/youtube-dl#4972]
youtube-dl is not able to pick the best possible stream from Twitch on its own. On their on-site Flash player, Twitch marks that stream as "Source". Though I doubt they use that name in the actual stream data anywhere.

For example, here's the output from the -F option:

```
$ youtube-dl -F http://www.twitch.tv/badnewsbaron
[twitch:stream] badnewsbaron: Downloading stream JSON
[twitch:stream] badnewsbaron: Downloading channel access token
[twitch:stream] badnewsbaron: Downloading m3u8 information
[info] Available formats for 13191279808:
format code extension resolution  note 
m3u8-meta   mp4       multiple    Quality selection URL 
m3u8-164    mp4       unknown      164k 
m3u8-596    mp4       unknown      596k 
m3u8-928    mp4       unknown      928k 
m3u8-1609   mp4       1280x720    1609k 
m3u8-1760   mp4       unknown     1760k  (best)
```

In this case, the "best" as marked by ytdl is actually a lower quality transcoded version (limited to 30FPS), while the actually highest quality stream (the "source" one, which is non-transcoded and can be 60FPS) can only be selected manually with:

`$ youtube-dl -f 'best[height=720]' -g http://www.twitch.tv/badnewsbaron`

It might be worth inspecting livestreamer to see how it selects the "source" stream by default.

**Comment by phihag** [comment]
`-f 'best[height=720]' ` should be identical to `-f m3u8-1609` in this case. Are you saying that that's not the case and youtube-dl somehow sneaks in the original format? No offense, but that sounds a lot like a conspiracy theory.

**Comment by jaimeMF** [comment]
The problem is that the hls manifest says that the source version has a lower bitrate than the `m3u8-1760` format, and since we give higher priority to the `tbr` field it's placed second.

**Comment by realnc** [comment]
Yeah, I noticed that the bitrates reported by Twitch for their lower quality transcoded streams are static (they're always the same) and very often are lower than the actual, non-transcoded source stream (what the person who streams is uploading).

It seems Twitch just picks "safe" static values for the transcodes only reports real values for the source stream.

In any event, many thanks for fixing this issue :-)
