### ISSUE TITLE
add support for sandia.gov

### ISSUE THREAD

**Issue by Siddhant** [rg3/youtube-dl#4974]
URL: http://digitalops.sandia.gov/Mediasite/Play/24aace4429fc450fb5b38cdbf424a66e1d

Note that, the viewing experience on the webpage includes slides which change along with the video. Similar to subtitles, maybe we should also think about how to handle slides and information about slides' timings.

**Comment by Siddhant** [comment]
Looks like they are using the "Mediasite Player" (http://www.sonicfoundry.com/mediasite/player)

**Comment by phihag** [comment]
youtube-dl 2015.02.19 supports downloading the video, but downloading the slides (or even video + slides) is not supported yet.

**Comment by TRox1972** [comment]
@yan12125 94a5cff91d81c120b8e8b395f9fbe465286940f0 closes this issue also

**Comment by yan12125** [comment]
Thanks.
