### ISSUE TITLE
Add support for Disney Junior

### ISSUE THREAD

**Issue by jjlawren** [rg3/youtube-dl#4975]
http://disneyjunior.com/video

**Comment by phihag** [comment]
Can you name an [example URL](https://yt-dl.org/example-url)? Or do you want support just for the URL `http://disneyjunior.com/video`?

**Comment by jjlawren** [comment]
Sorry, I should have read that page first. Here's an example URL with a video embedded: http://disneyjunior.com/watch/super-goof-s-super-puzzle-4c6b1451dac2b8d1a029c700

**Comment by SFNMutt** [comment]
The URLS for disney junior now look like this

http://watchdisneyjunior.go.com/jake-and-the-never-land-pirates/video/vdka3460299/04/18-tiger-sharky-strikes-again-captain-jakes-pirate-power-crew

I just tried and the error is "Go said:Unable to retrieve required files for playback. Please try again in a few minutes."  would love if you added support for them.

FYI - NickJr urls work great!

**Comment by SFNMutt** [comment]
just wanted to add that disney junior video urls can also look like this
http://disneyjunior.disney.com/escape-from-ghost-island-the-island-of-doctor-undergear

these are videos you can watch w/o loggin into your cable provider.  the error I get for these is "unsupporter url"

the videos w/ URLS like this are int he section that requires you to login to your cable provider.
http://watchdisneyjunior.go.com/jake-and-the-never-land-pirates/video/vdka3460299/04/18-tiger-sharky-strikes-again-captain-jakes-pirate-power-crew

neither work
