### ISSUE TITLE
Download from Wistia stuck at "Invoking downloader"

### ISSUE THREAD

**Issue by aps-sids** [rg3/youtube-dl#4978]
The download is stuck at `Invoking downloader` in `Downloading JSON metadata`. The video plays in the browser (after entering an email address though).

```bash
youtube-dl -v http://fast.wistia.net/embed/iframe/qrqfj371b6
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://fast.wistia.net/embed/iframe/qrqfj371b6']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.18
[debug] Python version 2.7.6 - Linux-3.13.0-45-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[Wistia] qrqfj371b6: Downloading JSON metadata
[debug] Invoking downloader on u'http://embed.wistia.com/deliveries/34c4c6a5850154f9ff0f63465dcbc18b3dc840db.bin'
```

**Comment by phihag** [comment]
Works fine for me. Can you reproduce this is issue? It may have just been a small outage at wistia's site. Note that you can specify a small `--socket-timeout` value in order to let youtube-dl abort instead wait for data.

**Comment by aps-sids** [comment]
@phihag Still same problem. Specifying a socket-timeout value leads to abort.

Now I feel that this might be due to some restrictions on my network.
