### ISSUE TITLE
New youtube-dl error version: 2015.02.18

### ISSUE THREAD

**Issue by ik1730** [rg3/youtube-dl#4983]
Youtube-dl version : 2015.02.18
I got this error :
[youtube] bTXJQ5ql5Fw: Downloading webpage
[youtube] bTXJQ5ql5Fw: Extracting video information
[youtube] bTXJQ5ql5Fw: Downloading js player en_US-vflKjOTVq
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'OF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'OF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ik1730** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=bTXJQ5ql5F', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.18
[debug] Python version 2.7.6 - Linux-2.6.32-042stab103.6-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg 1.2.6-7, ffprobe 1.2.6-7
[debug] Proxy map: {}
ERROR: Incomplete YouTube ID bTXJQ5ql5F. URL https://www.youtube.com/watch?v=bTXJQ5ql5F looks truncated.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 643, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 269, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1766, in _real_extract
    expected=True)
ExtractorError: Incomplete YouTube ID bTXJQ5ql5F. URL https://www.youtube.com/watch?v=bTXJQ5ql5F looks truncated.

**Comment by phihag** [comment]
Those are two different errors.

The first one should be fixed in youtube-dl version 2015.02.18.1.

The second one looks to me completely correct - I cannot see any video under the URL https://www.youtube.com/watch?v=bTXJQ5ql5F in my browser - can you?

**Comment by ik1730** [comment]
thanks :)  thaks:) very good support
