### ISSUE TITLE
can't download youtube channel (With youtuble-dl http://www.youtube.com/show/achievementhunter)

### ISSUE THREAD

**Issue by domainedma** [rg3/youtube-dl#4984]
youtuble-dl http://www.youtube.com/show/achievementhunter

[youtube:show] achievementhunter: Downloading show webpage
[youtube:show] achievementhunter: Found 0 seasons
[download] Downloading playlist: Achievement Hunter
[youtube:show] playlist Achievement Hunter: Collected 0 video ids (downloading 0
 of them)

Does not download anything!

**Comment by dstftw** [comment]
Works perfectly with latest version. Closing.
