### ISSUE TITLE
youtube-dl http://www.arte.tv/guide/fr/051080-000/deux-femmes-amoureuses

### ISSUE THREAD

**Issue by luluprat** [rg3/youtube-dl#4985]
can't download from arte tv 7 ?

**Comment by naglis** [comment]
The link works fine for me. Please include the full output of youtube-dl and that URL when run with `-v`.

**Comment by luluprat** [comment]
youtube-dl -v http://www.arte.tv/guide/fr/051080-000/deux-femmes-amoureuses
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.arte.tv/guide/fr/051080-000/deux-femmes-amoureuses']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.8 - Linux-3.16.0-29-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] Proxy map: {}
[arte.tv:+7] 051080-000: Downloading webpage
ERROR: Unable to extract json vp url; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/arte.py", line 77, in _real_extract
    return self._extract_from_webpage(webpage, video_id, lang)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/arte.py", line 81, in _extract_from_webpage
    r'arte_vp_url="(.*?)"', webpage, 'json vp url')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 401, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract json vp url; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl (there have been over 160 releases since your version!). See [our FAQ](https://yt-dl.org/update) if you have trouble updating. If you can reproduce the issue with the [current](http://yt-dl.org/latest/version) version of youtube-dl, please post the output you get using *that* version and we will reopen this issue. Thanks!
