### ISSUE TITLE
[hds] [rts] Add support for akamai player verification

### ISSUE THREAD

**Issue by lordk88** [rg3/youtube-dl#4989]
Hello,

when I try to dl a vid on RTS, I have this problem

youtube-dl http://www.rts.ch/play/tv/les-feux-de-lamour/video/episode-6583?id=6549637
[RTS] episode-6583: Downloading JSON metadata
[RTS] 6549637: Downloading m3u8 information
[RTS] 6549637: Downloading hds token
[RTS] 6549637: Downloading f4m manifest
ERROR: Unable to download f4m manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

How can I fix it ?

**Comment by dstftw** [comment]
Can you watch it in browser?
