### ISSUE TITLE
Downloading wrong video on onlinemovies.pro

### ISSUE THREAD

**Issue by fjd** [rg3/youtube-dl#4990]
Downloading wrong video.

youtube-dl --verbose http://onlinemovies.pro/blackhat-2015/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://onlinemovies.pro/blackhat-2015/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.16
[debug] Python version 2.7.6 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5.4, ffprobe 2.5.4
[debug] Proxy map: {}
[generic] blackhat-2015: Requesting header
WARNING: Falling back on generic information extractor.
[generic] blackhat-2015: Downloading webpage
[generic] blackhat-2015: Extracting information
[download] Downloading playlist: Blackhat (2015) Watch Online Free | OnlineMovies.Pro
[generic] playlist Blackhat (2015) Watch Online Free | OnlineMovies.Pro: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] Qn2g9qGbH_k: Downloading webpage
[youtube] Qn2g9qGbH_k: Extracting video information
[youtube] Qn2g9qGbH_k: Downloading DASH manifest
[debug] Invoking downloader on u'https://r1---sn-5hn7snek.googlevideo.com/videoplayback?expire=1424296906&ipbits=0&ratebypass=yes&mime=video%2Fmp4&requiressl=yes&initcwndbps=966250&pl=19&source=youtube&sver=3&dur=152.253&mv=m&mt=1424275067&ms=au&id=o-AChfk7w9rQjL8GCnTQMtA6r_bTWEoY2niAQknTd5sKQN&signature=5CF87E853F0F12A6FD7E7734FBAB204516BB2EC4.87B008ABFE2CF70E4E318FFA9DDCBB1FE8793720&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ip=217.92.21.59&key=yt5&itag=22&upn=N99YkSwQn6s&fexp=904844%2C905657%2C907263%2C921418%2C924638%2C927622%2C931365%2C937412%2C943917%2C947225%2C948124%2C952302%2C952605%2C952612%2C952901%2C955301%2C957201%2C959701&mm=31'
[download] Blackhat Official Trailer #1 (2015) - Chris Hemsworth Movie HD-Qn2g9qGbH_k.mp4 has already been downloaded
#site-support-request

**Comment by jaimeMF** [comment]
It seems that the site only distributes copyrighted material without permission, therefore we can't add support for it. (Read [this FAQ entry](https:/yt-dl.org/anime) for more info)
