### ISSUE TITLE
Support Imgur GIFV

### ISSUE THREAD

**Issue by jbboehr** [rg3/youtube-dl#4997]
https://imgur.com/blog/2014/10/09/introducing-gifv/

Example URL:
https://i.imgur.com/A61SaA1.gifv

It's just an HTML page with a video tag. I might take a stab at it later, but Python isn't my main language, so if anyone wants to jump on it, don't let me hold you back.

**Comment by phihag** [comment]
Thank you for the report, imgur support has been added with 3bf5705 / youtube-dl 2015.02.19. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by jbboehr** [comment]
Ah, my apologies. You guys are too fast.
