### ISSUE TITLE
Add Support for Playwire

### ISSUE THREAD

**Issue by yousufalim** [rg3/youtube-dl#5000]
Can support for playwire be added

example url here
http://footyroom.com/schalke-04-0-2-real-madrid-2015-02/

**Comment by yousufalim** [comment]
anyone?
playwire is big these days :/

**Comment by yan12125** [comment]
I've noticed that @dstftw have added a playwire info extractor in 12a129ec6dde840c23e8b1e5d7552de93fce7be4. It should be possible to detect the video in generic.py. A current workaround can be: search for somthing like ```http:\/\/config.playwire.com\/14907\/videos\/v2\/3353705\/player.json``` in the source code of the web page, replace \/ with / and give to URL to youtube-dl.

**Comment by dstftw** [comment]
footyroom will be supported in the next release. Thanks for the report.

**Comment by dstftw** [comment]
Support for footyroom has been added in youtube-dl 2015.03.15. See [our FAQ](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) on how to update.
