### ISSUE TITLE
WARNING: unable to extract uploader nickname WARNING: unable to extract categories; 

### ISSUE THREAD

**Issue by aryehbeitz** [rg3/youtube-dl#5002]
https://www.youtube.com/watch?v=qdP7WPbdd5w

**Comment by jaimeMF** [comment]
It's working fine for me, please [post the **full output**](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) you get when running `youtube-dl --verbose https://www.youtube.com/watch?v=qdP7WPbdd5w`

**Comment by aryehbeitz** [comment]
i just did an update and its working. thanks and sorry for not checking that first

**Comment by Menelik2** [comment]
youtube-dl -i "youtube_url" works in this case.
