### ISSUE TITLE
videos.r7.com

### ISSUE THREAD

**Issue by yavute** [rg3/youtube-dl#5004]
Hello, you put between http://videos.r7.com/ supported sites

Thanks

**Comment by phihag** [comment]
Thank you for the report. Can you name an example URL? Please review [our instructions for bug report](https://yt-dl.org/example-url).

**Comment by yavute** [comment]
http://rg3.github.io/youtube-dl/supportedsites.html
Would you please add this site http://videos.r7.com/

Example link:http://videos.r7.com/policiais-humilham-suspeito-a-beira-da-morte-morre-com-dignidade-/idmedia/54e7050b0cf2ff57e0279389.html

**Comment by naglis** [comment]
Possibly related/duplicate: #4405

**Comment by yavute** [comment]
I do not understand how you can download

**Comment by dstftw** [comment]
R7 will be supported in the next version. Thanks for the report.

**Comment by yavute** [comment]
@dstftw Thanks

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl version 2015.02.24 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
