### ISSUE TITLE
TED extractor: prefer 'code' to 'uri' if present

### ISSUE THREAD

**Issue by minusf** [rg3/youtube-dl#5012]
it seems like some TED videos pointing to Youtube define `code`,
and may or may not use `uri` for something else (pointing to the page of the actual TED event).

here is an actual example:
http://www.ted.com/talks/jeffrey_kluger_the_sibling_bond

```json
{"talks": [{
		"id":1369,
		"duration":1268, 
		"canonical":"http://www.ted.com/talks/jeffrey_kluger_the_sibling_bond",
		"external": {
			"code":"aFBIPO-P7LM",
			"service":"YouTube",
			"uri":"http://www.ted.com/tedx/events/3601"
		},
	}]
}
```

**Comment by minusf** [comment]
hm, perhaps it would have been better not to start this issue,
but just do the pull request?  sorry, i am used to bug report -> patch
workflow...

**Comment by dstftw** [comment]
This will be fixed in the next version. Thanks for the report and PR.
