### ISSUE TITLE
add support for zapiks

### ISSUE THREAD

**Issue by benoit-monin** [rg3/youtube-dl#5014]
Zapiks is a french website publishing sport videos, for example:
http://www.zapiks.fr/ep3s5-bon-appetit-baqueira-m-1.html
Also available in english and dutch:
http://www.zapiks.com/ep3s5-bon-appetit-baqueira-m-1.html
http://www.zapiks.com/nl/ep3s5-bon-appetit-baqueira-m-1.html

The videos can also be embedded in other websites, for example:
http://www.skipass.com/news/116090-bon-appetit-s5ep3-baqueira-mi-cor.html

**Comment by dstftw** [comment]
Zapiks will be supported in the next version. Thanks for the report.

**Comment by phihag** [comment]
Support for Zapiks has made it into youtube-dl 2015.02.21. See [our FAQ](https://yt-dl.org/update) if you have trouble updating.

**Comment by benoit-monin** [comment]
That was fast !
Thanks a lot, it works perfectly.
