### ISSUE TITLE
Enhancement request: add option to ignore WebM (or add "bestmp4", "bestwebm", etc. format names)

### ISSUE THREAD

**Issue by zmwangx** [rg3/youtube-dl#5015]
Most of the time `bestvideo` on YouTube is H.264 video in MPEG-4 container, but occasionally `bestvideo` is VP9 video in WebM container, and this has been screwing me on every encounter. Problems:

* WebM container doesn't support AAC (only Opus and Ogg Vorbis are supported), so when `bestvideo` is WebM, `bestvideo+bestaudio` always fails since youtube-dl asks FFmpeg to mux VP9 and AAC into a WebM container, and it simply can't.

* I'm not interested in VP9 in general, since it's not supported on iOS. I can afford larger files with H.264.

Therefore, I would like to be able to ignore WebM altogether. I think a good idea would be to add special format codes `bestmp4`, `bestwebm`, etc. so that the user can target the specific format they want, without resorting to doing `youtube-dl -F` first and filtering the results manually.

**Comment by phihag** [comment]
You can simply use `-f "bestvideo[ext=mp4]"` already. I do not see the need to add any more codes.

Also bear in mind that `bestvideo` is *not* the same as `best`. It will pick the best video-only format.

**Comment by zmwangx** [comment]
Uh apparently filtering by properties was implemented only a month ago in 083c9df and I didn't read the updated docs. Sorry.
