### ISSUE TITLE
GDC Vault videos prior to 2013 won't download

### ISSUE THREAD

**Issue by fshy00** [rg3/youtube-dl#5024]
In the GDC Vault, in 2013 they switched over from some flash system over to MP4, which means that youtube-dl works flawlessly with all new GDC Vault videos.

The issue happens when downloading a video from 2012 or earlier, this happens:

 http://pastebin.com/7LcUQnQV

Since the video I was trying to download is members only, this video has the same results for me, its just free for the public if anyone wants to test:

http://www.gdcvault.com/play/1015790/Build-More-Immersive-Games-with

To be honest, I'm not sure why yt-dl doesn't work, when this script does:

https://gist.github.com/archagon/4071535

Thanks for all the help.

**Comment by dstftw** [comment]
GDC vault rtmp streams will work in the next version. Thanks for the report.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.02.21. See [our FAQ](https://yt-dl.org/update) if you have trouble updating.

**Comment by fshy00** [comment]
Thanks for all the help! It works wonderfully now!

Special thanks for the really quick update on this, too.
