### ISSUE TITLE
VEVO extractor broken

### ISSUE THREAD

**Issue by blissland** [rg3/youtube-dl#5026]
Running vevo using test URL:

    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['-v', 'http://www.vevo.com/watch/hurts/somebody-to-die-for/GB1101300280']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.02.21
    [debug] Git HEAD: e086e0e
    [debug] Python version 2.7.3 - Linux-3.18.5+-armv6l-with-debian-7.8
    [debug] exe versions: avconv 9.14-6, avprobe 9.14-6, ffmpeg 0.8.16-6, rtmpdump 2.4
    [debug] Proxy map: {}
    ERROR: Vevo said: Hmm, something went sideways! Please try another video.
    Traceback (most recent call last):
      File "youtube_dl/YoutubeDL.py", line 643, in extract_info
    ie_result = ie.extract(url)
      File "youtube_dl/extractor/common.py", line 269, in extract
    return self._real_extract(url)
      File "youtube_dl/extractor/vevo.py", line 180, in _real_extract
    raise ExtractorError('%s said: %s' % (self.IE_NAME, response['statusMessage']), expected=True)
    ExtractorError: Vevo said: Hmm, something went sideways! Please try another video.

**Comment by jaimeMF** [comment]
I just tested a few minutes ago and I get the error, but it's working fine now. Does it work for you now?

**Comment by dstftw** [comment]
Yep, looks like it does work now.

**Comment by blissland** [comment]
Yes seems to work fine now - Thanks for looking into it so quickly!
