### ISSUE TITLE
Add support for http://trailers.apple.com/ca/

### ISSUE THREAD

**Issue by renuka25165** [rg3/youtube-dl#5027]
[generic] autrui: Requesting header
WARNING: Falling back on generic information extractor.
[generic] autrui: Downloading webpage
[generic] autrui: Extracting information
ERROR: Unsupported URL: http://trailers.apple.com/ca/metropole/autrui/

**Comment by dstftw** [comment]
There are no videos on this page. What do you expect from youtube-dl to download?

**Comment by renuka25165** [comment]
If you can look down at bottom of page you can see video.
Trailer (In French)
Play 1:19

**Comment by dstftw** [comment]
Can't see any videos, even under french proxy. Could you upload the `*.dump` files you get when running youtube-dl with `--write-pages` option?

**Comment by renuka25165** [comment]
<!DOCTYPE html>




 <html class="" xml:lang="en-US" lang="en-US"> 
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta http-equiv="pics-label" content='(pics-1.1 "http://www.icra.org/ratingsv02.html" l gen true for "http://www.apple.com" r (cz 1 lz 1 nz 1 oz 1 vz 1) "http://www.rsac.org/ratingsv01.html" l gen true for "http://www.apple.com" r (n 0 s 0 v 0 l 0))' />
<meta name="Author" content="Apple Inc." />
<meta name="viewport" content="width=device-height" />

	<title>Autrui - Movie Trailers - iTunes</title>
	<meta name="omni_page" content="Movie Trailers - Autrui" />
	<meta name="Category" content="downloads,trailers" />
	<meta property="og:title" content="Autrui - Movie Trailers - iTunes" />
	<meta property="og:description" content="On a bitingly cold winter night, Lucie, an introvert young woman, offers shelter to Eloi, a homeless man on the verge of freezing to death in the streets. This charitable gesture will entwine the two of them in a complex relationship and help them to find fresh hope, each in their own way." />
	<meta property="og:image" content="https://trailers.apple.com/ca/metropole/autrui/images/poster-large.jpg?lastmod=1" />
	<meta name="Description" content="On a bitingly cold winter night, Lucie, an introvert young woman, offers shelter to Eloi, a homeless man on the verge of freezing to death in the streets. This charitable gesture will entwine the two of them in a complex relationship and help them to find fresh hope, each in their own way." />
	
	

	
<link rel="stylesheet" href="http://trailers.apple.com/trailers/global/v4/styles/site.css" type="text/css" />

	<link rel="stylesheet" href="http://trailers.apple.com/ca/metropole/autrui/styles.css" type="text/css" />
</head>

<body class="body-black">

	<div id="metrics">
    	<div id="top">



	
	



<script type="text/javascript">
var s_account="applecaglobal,applecatrailers"
</script>


<script type="text/javascript" src="http://images.apple.com/metrics/scripts/s_code_h.js"></script>


<script type="text/javascript">
s.pageName=AC.Tracking.pageName()+" (ca)";
s.channel="www.ca.trailers"

/* Set Internal Link Filter */

s.linkInternalFilters="javascript:,trailers.apple.com/ca/"

/************* DO NOT ALTER ANYTHING BELOW THIS LINE ! **************/
var s_code=s.t();</script>

</div>

	</div>

	<noscript><div id="nojs">Please enable JavaScript to view this page properly.</div></noscript>


	<header id="header-wrapper" class="top-wrapper"></header>

	<div id="main-wrapper"></div>

	<footer id="globalfooter">
		<!—footer goes here —>

	</footer>

	<script data-main="/trailers/global/v4/scripts/main" src="/trailers/global/v4/scripts/libs/requirejs/require.js?cache=12"></script>


</body>
</html>

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.

**Comment by renuka25165** [comment]
Thanks for your support.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl version 2015.02.24 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
