### ISSUE TITLE
don't allow hyphen, '-', at the beginning of the file name

### ISSUE THREAD

**Issue by foo-bar-baz** [rg3/youtube-dl#5035]
use detox(1) if need be. file names like --gasdgf.mp4 are hard to deal with. mv(1) for one will refuse to work unless '--' is passed as arg1 and so on.

**Comment by phihag** [comment]
Thank you for the report. In youtube-dl 2015.02.24.1 and newer, the filename will only start with `-` if your template starts with an ID (e.g. you pass in `--id`), because in that case, the filename needs to be verbatim. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by foo-bar-baz** [comment]
[please re-opne]
it still allows for garbage to be used for the beginning of the filename. for this, for example:

https://www.youtube.com/watch?v=MZtQ24thVg0

youtube-dl will use '.' as the beginning of the name. that's just wrong in *nix systems since it will hide the file.

i strongly suggest using detox, reinventing the wheel is probably not worth the time.
