### ISSUE TITLE
[nrk] Subtitles can't be converted with python 2.6

### ISSUE THREAD

**Issue by jaimeMF** [rg3/youtube-dl#5036]
For example with http://tv.nrk.no/serie/ikke-gjoer-dette-hjemme/DMPV73000411/sesong-2/episode-1, the problem is that we call [`xml.etree.ElementTree.Element.itertext`](https://docs.python.org/2/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.itertext) in [this line](https://github.com/rg3/youtube-dl/blob/01561da142485a581e67ce98ef009ebe0ed7b4c1/youtube_dl/extractor/nrk.py#L170), which is not available in 2.6.

We need to call `itertext` to correctly extract the text from nodes like this one:
```xml
<p begin="00:00:36.440" dur="00:00:07.500" style="left">-Vi har sprengt, brent, oversvømt ...<br />-Eksplodert, implodert, kortsluttet.</p>
```
(Call `youtube-dl 'http://tv.nrk.no/serie/ikke-gjoer-dette-hjemme/DMPV73000411/sesong-2/episode-1' --write-sub --sub-format ttml` for getting the ttml file)

I haven't looked into the python source code, so I don't know how hard is to backport the function.

**Comment by dstftw** [comment]
I think it's OK to just workaround this by `transform_source`.

**Comment by jaimeMF** [comment]
Thanks for looking into it.
