### ISSUE TITLE
the facebook extractor doesn't show formats and downloads when verbose is used.

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#5037]
Hi all, 
I am using youtube-dl version 

    $ youtube-dl --version
    2015.02.06

Now I tried to figure out if there are multiple resolutions to the video, it doesn't give/share anything. 
    
    $ youtube-dl -F "https://www.facebook.com/video.php?v=10152990229886015"
    [facebook] 10152990229886015: Downloading webpage
    [info] Available formats for 10152990229886015:
    format code extension resolution  note 
    0           mp4       unknown     
    
When I put the verbose flags the video is downloaded. 
    
    $ youtube-dl --verbose "https://www.facebook.com/video.php?v=10152990229886015"
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['--verbose', 'https://www.facebook.com/video.php?v=10152990229886015']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.02.06
    [debug] Python version 2.7.8 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
    [debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
    [debug] Proxy map: {}
    [facebook] 10152990229886015: Downloading webpage
    [debug] Invoking downloader on u'https://fbcdn-video-h-a.akamaihd.net/hvideo-ak-xpf1/v/t43.1792-2/10361281_10152990231436015_110273172_n.mp4?efg=big-hash &vabr=some-hash=alphanumerict-hing[&__gda__=another hash'
    [download] Destination: The Black Guy and White Guy series kicked off this year with #mitwa Bringing ...-10152990229886015.mp4
    [download] 100% of 1.69MiB in 00:34

I have taken out the hash values and alphanumeric numbering as a security precaution. Perhaps those hashes were akamai's or they may have something to do with my fb a/c . 

Anyways, the moot point is that why it downloads a certain resolution. Are all the videos in FB at a single resolution or are there multiple resolutions ?

Looking forward for answers.

**Comment by jaimeMF** [comment]
In the next version it will list two formats: `sd` and `hd`; since they don't seem to provide resolution info, we can't list it.

**Comment by shirishag75** [comment]
@jaimeMF thank you.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl version 2015.02.24 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
