### ISSUE TITLE
Question: How does Youtube-dl bypass ISP Restrictions

### ISSUE THREAD

**Issue by steelbrain** [rg3/youtube-dl#5039]
Youtube has been blocked by my ISP (Yeah it sucks) and I am surprised that Youtube-dl still successfully grabs i.
I tried the verbosity settings and it extract data from this kind-of urls `https://www.youtube.com/watch?v=VBmEJZofz2s&gl=US&hl=en&has_verified=1&bpctr=9999999999` but how does it work if it's blocked?

Note: The link it extracts from `-j` do __not__ work in a browser.

**Comment by phihag** [comment]
youtube-dl is not magical, although we try our best to work around censorship when we can. We don't do any specific evasion for the YouTube service though. Without a more detailed output I can't tell what's going on.

The link you get with `-g` (or by parsing the JSON in `-j`) should be valid with any downloader though, including your web browser. So are you sure the censorship is done by your ISP, and not in your web browser?

**Comment by steelbrain** [comment]
@phihag turns out that some subdomains of googlevideo.com are blocked, not all of them. Thanks!
