### ISSUE TITLE
youtube subtitle doesn't work

### ISSUE THREAD

**Issue by dattaz** [rg3/youtube-dl#5049]
subtitles item in dict is always as none with python api
My code : 
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import youtube_dl

def getdata(url):
    with youtube_dl.YoutubeDL({'outtmpl': '%(id)s%(ext)s'}) as ydl:
        result = ydl.extract_info(url, download=False)
    url = result['url']
    title = result['title']
    thumbnail = result.get('thumbnail')
    #print('url: %r, title: %r, thumbnail: %r' % (url, title, thumbnail))
    # writecvs(url, title, tags)
    print result
    print "-------------------------------------"
    print result.get('subtitles')
getdata('https://www.youtube.com/watch?v=I4jqq4Tml1s')

I have try video with auto-subtitle and real subtitle

**Comment by jaimeMF** [comment]
You'll have to add the `writesubtitles` parameter:
```python
import youtube_dl
def getdata(url):
    with youtube_dl.YoutubeDL({'outtmpl': '%(id)s%(ext)s', 'writesubtitles': True}) as ydl:
        result = ydl.extract_info(url, download=False)
        url = result['url']
        title = result['title']
        thumbnail = result.get('thumbnail')
        #print('url: %r, title: %r, thumbnail: %r' % (url, title, thumbnail))
        # writecvs(url, title, tags)
        print result
        print "-------------------------------------"
        print result.get('subtitles')
getdata('https://www.youtube.com/watch?v=I4jqq4Tml1s')
```

Youtube subtitles info is only extracted with that option because it requires an additional request, so it will take some more time to complete the extraction.

**Comment by dattaz** [comment]
thanks a lot, sorry
