### ISSUE TITLE
--no-playlist cul-de-sac

### ISSUE THREAD

**Issue by foo-bar-baz** [rg3/youtube-dl#5051]
how do you switch playlist on when --no-playlist is in config file (default)? there is no --playlist as far as i can see.

**Comment by phihag** [comment]
Thank you for the report. Since youtube-dl 2015.02.28, you can pass in `--yes-playlist`. See [our FAQ](https://yt-dl.org/update) if you have trouble updating.

**Comment by foo-bar-baz** [comment]
thanks, feel free to close this.

**Comment by phihag** [comment]
Already is ;)
