### ISSUE TITLE
-g, I do not know which format the url is for

### ISSUE THREAD

**Issue by Mitchell-Findley** [rg3/youtube-dl#5052]
When I use the -g to get the temp link to a source file. I need the format as well. If you could add an option that outputs the format that that the link is, especially after specifying a preference format list. So I know which format it grabs else it is very hard for me to use the URL.

**Comment by phihag** [comment]
It sounds like you are calling youtube-dl from another program. If that's the case, use the `-j` option to get information about the video as JSON, which you can easily parse in any programming language.
