### ISSUE TITLE
mark watched

### ISSUE THREAD

**Issue by 257** [rg3/youtube-dl#5054]
the main reason for me to authenticate to youtube is to have a history of watched videos. using simple authentication this doesn't work. please add hooks for marking downloaded videos as watched.

**Comment by simonwjackson** [comment]
+1 please!

**Comment by p3lim** [comment]
+1

**Comment by vonpupp** [comment]
+1 please

**Comment by coldwaterq** [comment]
+1 please

**Comment by Inginn** [comment]
this is so needed when you use mpv

**Comment by dstftw** [comment]
`--mark-watched` will be supported in the next version. Note that you must be authenticated either via `-u`/`-p` or `--cookies`.

**Comment by 257** [comment]
just committed mark-watched to the config file. now *incognito* mode would nice to; something like --nomark-watched to override that.

**Comment by 257** [comment]
thanks.

**Comment by coldwaterq** [comment]
The first time I used this it worked, but now it doesn't seem to be anymore. Is it possible youtube is blocking this, and is there any way I could bypass that block that they would have trouble detecting?

**Comment by dstftw** [comment]
Open a new issue with `-v --dump-pages` log.
