### ISSUE TITLE
Unable to download embedded vimeo video

### ISSUE THREAD

**Issue by adzenith** [rg3/youtube-dl#5058]
URL: http://hedonistica.com/short-films/adi-shankar-produced-a-bootleg-power-rangers-fan-film/
I was able to download the video by manually getting the mp4 url from the Inspector.

**Comment by adzenith** [comment]
The problem might be related to the fact that if you click the Vimeo logo to view the video on vimeo.com, it says that "There is no video here".

**Comment by dstftw** [comment]
There are no vimeo videos on this page at the moment, only youtube video that is properly downloaded by youtube-dl. Provide another link and the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by jaimeMF** [comment]
The vimeo video that was in the page yesterday is http://player.vimeo.com/video/120401488?title=0&byline=0&portrait=0, it can only be played with that url (if you remove any of the query parameters it doesn't work). It seems that it was ["deleted"](http://www.polygon.com/2015/2/24/8105593/power-rangers-short-film-saban-take-down), so maybe it's not worth supporting that kind of video.

**Comment by stinkteeth** [comment]
It might be restored. https://vimeo.com/forums/help/topic:130072

**Comment by adzenith** [comment]
@dstftw I guess they swapped out to the YouTube version. At the time, you couldn't watch the video on Vimeo, but you could watch it at the hedonistica.com link.

**Comment by dstftw** [comment]
Works fine with latest version (2016.05.16).
