### ISSUE TITLE
error - Playback on other websites has been disabled by the video owner

### ISSUE THREAD

**Issue by aryehbeitz** [rg3/youtube-dl#5059]
https://www.youtube.com/watch?v=ah3utUn93fw

[youtube] ah3utUn93fw: Downloading webpage
[youtube] ah3utUn93fw: Downloading embed webpage
[youtube] ah3utUn93fw: Refetching age-gated info webpage
ERROR: ah3utUn93fw: YouTube said: <a href="http://www.youtube.com/watch?v=ah3utUn93fw&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.

**Comment by barsnick** [comment]
Watching this video requires a login, due to age restrictions. You will have to use YouTube credentials to download it.

**Comment by yan12125** [comment]
Duplicate of #4162 and there's a solution in #4627

**Comment by shmilon** [comment]
Playback on other websites has been disabled by the video owner you could not show it.
