### ISSUE TITLE
Retry on ERROR

### ISSUE THREAD

**Issue by Sepero** [rg3/youtube-dl#506]
I have an imperfect internet connection, so I set the options to -c continue, and -R retry 100 times. Unfortunately, if the program reaches ERROR, it thinks it's not supposed to retry any more, and quits.

[youtube] Pq_JFaqsNYI: Downloading video webpage
[youtube] Pq_JFaqsNYI: Downloading video info webpage
[youtube] Pq_JFaqsNYI: Extracting video information
[download] Destination: Bioshock_Playthrough_pt_7-Pq_JFaqsNYI.flv
[download]  59.5% of 115.43M at   88.34k/s ETA 09:01
ERROR: unable to download video

It would be great if youtube-dl didn't give up at 59.5% of the download, and instead finished exhausting retries (possibly with a short 2 second pause between retries).

**Comment by weedy** [comment]
I would really like you guys to set urllib2.urlopen(request, timeout=XX) to something shorter then the current "tens of minutes" or whatever the default is.

**Comment by jaimeMF** [comment]
@weedy Have you tried the `--socket-timeout` option? Open a new issue if it doesn't work.
