### ISSUE TITLE
Signature extraction failed: Traceback

### ISSUE THREAD

**Issue by 00stormy00** [rg3/youtube-dl#5063]
Hy also with the newest version 2015.24.02 same issue while downloading music.
Can anybody help?

debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--extract-audio', '--audio-format', 'mp3', '--restrict-filenames', '--o', '%(title)s.%(ext)s', '--batch-file', 'mam']
[debug] Batch file urls: [u'https://www.youtube.com/watch?v=t1485PtMq58', u'https://www.youtube.com/watch?v=xwtdhWltSIg', u'https://www.youtube.com/watch?v=yvPr9YV7-Xw', u'https://www.youtube.com/watch?v=9jK-NcRmVcw', u'https://www.youtube.com/watch?v=fX5USg8_1gA', u'https://www.youtube.com/watch?v=6eByMZJ9ueA', u'https://www.youtube.com/watch?v=ZN5RDJFwI3I', u'https://www.youtube.com/watch?v=UCmUhYSr-e4', u'https://www.youtube.com/watch?v=AEq62iQo0eU', u'https://www.youtube.com/watch?v=GC5E8ie2pdM', u'https://www.youtube.com/watch?v=yulZeKSp77w', u'https://www.youtube.com/watch?v=k2C5TjS2sh4', u'https://www.youtube.com/watch?v=yCC_b5WHLX0', u'https://www.youtube.com/watch?v=VdQY7BusJNU', u'https://www.youtube.com/watch?v=PIb6AZdTr-A', u'https://www.youtube.com/watch?v=vx2u5uUu3DE', u'https://www.youtube.com/watch?v=QheJWiUAgSo', u'https://www.youtube.com/watch?v=pAOQkSFTKMw', u'https://www.youtube.com/watch?v=7S94ohyErSw', u'https://www.youtube.com/watch?v=K5_EBAzIPJM', u'https://www.youtube.com/watch?v=yRhq-yO1KN8', u'https://www.youtube.com/watch?v=fPo6v0KhBdw', u'https://www.youtube.com/watch?v=pey29CLID3I', u'https://www.youtube.com/watch?v=5A-4VGfx5lU', u'https://www.youtube.com/watch?v=G0ATsOXSPBw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.11
[debug] Python version 2.7.8 - Linux-3.16.0-29-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6
[debug] Proxy map: {}
[youtube] t1485PtMq58: Downloading webpage
[youtube] t1485PtMq58: Extracting video information
[youtube] t1485PtMq58: Downloading DASH manifest
[debug] Invoking downloader on 'https://r6---sn-uxax3vh50nugp5-8pxl.googlevideo.com/videoplayback?id=b75e3ce4fb4cab9f&itag=141&source=youtube&requiressl=yes&mm=31&mv=m&pl=16&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=28220861&lmt=1390348264598785&dur=885.144&fexp=900222,905657,907263,927622,927907,934954,940940,943917,947225,947240,948124,951703,952302,952605,952612,952620,952901,955301,957201,959701,964723&signature=09BCA66CD562C3A59B8FAACB7C4902C87B12FE8F.71138A55CA03159AD26FF8ADD762F2C305EFD981&upn=qXwroLKHF6g&key=dg_yt0&sver=3&mt=1424898337&ip=62.46.203.225&ipbits=0&expire=1424919975&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mv,pl,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.m4a
[download] 100% of 26.91MiB in 00:26
[ffmpeg] Correcting container in "Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.m4a"
[debug] ffmpeg command line: avconv -y -i Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.m4a -c copy -f mp4 Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.temp.m4a
[avconv] Destination: Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.mp3
[debug] ffmpeg command line: avconv -y -i Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.m4a -vn -acodec libmp3lame -q:a 5 Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.mp3
Deleting original file Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.m4a (pass -k to keep)
[youtube] xwtdhWltSIg: Downloading webpage
[youtube] xwtdhWltSIg: Extracting video information
[youtube] {43} signature length 43.41, html5 player en_US-vflQTSOsS
[youtube] xwtdhWltSIg: Downloading js player en_US-vflQTSOsS
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 633, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 270, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1066, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 645, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

stormy@nb:/media/stormy/hdd2/Music/youtube-dl$ 
stormy@nb:/media/stormy/hdd2/Music/youtube-dl$ 
stormy@nb:/media/stormy/hdd2/Music/youtube-dl$ 
stormy@nb:/media/stormy/hdd2/Music/youtube-dl$ 
stormy@nb:/media/stormy/hdd2/Music/youtube-dl$ ./y2mp3v mam
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--extract-audio', '--audio-format', 'mp3', '--restrict-filenames', '--o', '%(title)s.%(ext)s', '--batch-file', 'mam']
[debug] Batch file urls: [u'https://www.youtube.com/watch?v=t1485PtMq58', u'https://www.youtube.com/watch?v=xwtdhWltSIg', u'https://www.youtube.com/watch?v=yvPr9YV7-Xw', u'https://www.youtube.com/watch?v=9jK-NcRmVcw', u'https://www.youtube.com/watch?v=fX5USg8_1gA', u'https://www.youtube.com/watch?v=6eByMZJ9ueA', u'https://www.youtube.com/watch?v=ZN5RDJFwI3I', u'https://www.youtube.com/watch?v=UCmUhYSr-e4', u'https://www.youtube.com/watch?v=AEq62iQo0eU', u'https://www.youtube.com/watch?v=GC5E8ie2pdM', u'https://www.youtube.com/watch?v=yulZeKSp77w', u'https://www.youtube.com/watch?v=k2C5TjS2sh4', u'https://www.youtube.com/watch?v=yCC_b5WHLX0', u'https://www.youtube.com/watch?v=VdQY7BusJNU', u'https://www.youtube.com/watch?v=PIb6AZdTr-A', u'https://www.youtube.com/watch?v=vx2u5uUu3DE', u'https://www.youtube.com/watch?v=QheJWiUAgSo', u'https://www.youtube.com/watch?v=pAOQkSFTKMw', u'https://www.youtube.com/watch?v=7S94ohyErSw', u'https://www.youtube.com/watch?v=K5_EBAzIPJM', u'https://www.youtube.com/watch?v=yRhq-yO1KN8', u'https://www.youtube.com/watch?v=fPo6v0KhBdw', u'https://www.youtube.com/watch?v=pey29CLID3I', u'https://www.youtube.com/watch?v=5A-4VGfx5lU', u'https://www.youtube.com/watch?v=G0ATsOXSPBw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.11
[debug] Python version 2.7.8 - Linux-3.16.0-29-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6
[debug] Proxy map: {}
[youtube] t1485PtMq58: Downloading webpage
[youtube] t1485PtMq58: Extracting video information
[youtube] t1485PtMq58: Downloading DASH manifest
[debug] Invoking downloader on 'https://r6---sn-uxax3vh50nugp5-8pxl.googlevideo.com/videoplayback?id=b75e3ce4fb4cab9f&itag=141&source=youtube&requiressl=yes&ms=au&mv=m&pl=16&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=28220861&lmt=1390348264598785&dur=885.144&key=dg_yt0&mt=1424898428&upn=f6V00tjVDKY&sver=3&signature=585661AFA6D0FFD9B11DA2A6C922593851C9C0BE.93E373C89FF6F7A72A9D6DB06FCE6F5380B65196&fexp=904732,905657,907263,913446,927622,9407474,942622,943917,945067,947225,947240,948124,951703,952302,952605,952612,952620,952901,954403,955301,957201,959701&ip=62.46.203.225&ipbits=0&expire=1424920111&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,pl,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.m4a
[download] 100% of 26.91MiB in 00:26
[ffmpeg] Correcting container in "Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.m4a"
[debug] ffmpeg command line: avconv -y -i Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.m4a -c copy -f mp4 Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.temp.m4a
[avconv] Destination: Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.mp3
[debug] ffmpeg command line: avconv -y -i Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.m4a -vn -acodec libmp3lame -q:a 5 Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.mp3
Deleting original file Robin_Gibb_-_A_Star_In_Heaven_-_Part_2_by_Mike_Wiggins.m4a (pass -k to keep)
[youtube] xwtdhWltSIg: Downloading webpage
[youtube] xwtdhWltSIg: Extracting video information
[youtube] {43} signature length 43.41, html5 player en_US-vflQTSOsS
[youtube] xwtdhWltSIg: Downloading js player en_US-vflQTSOsS
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 633, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 270, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1066, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 645, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
Post the verbose output with version `2015.02.24.2` (the latest), the error you posted should be fixed.

**Comment by 00stormy00** [comment]
Hy thanks for help!
Bevore I updated to the latest version with youtube-dl -u

See Output:

youtube-dl --version
2015.02.24.2

./y2mp3v bug
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--extract-audio', '--audio-format', 'mp3', '--restrict-filenames', '--o', '%(title)s.%(ext)s', '--batch-file', 'bug']
[debug] Batch file urls: [u'https://www.youtube.com/watch?v=xwtdhWltSIg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.11
[debug] Python version 2.7.8 - Linux-3.16.0-29-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6
[debug] Proxy map: {}
[youtube] xwtdhWltSIg: Downloading webpage
[youtube] xwtdhWltSIg: Extracting video information
[youtube] {43} signature length 43.41, html5 player en_US-vflQTSOsS
[youtube] xwtdhWltSIg: Downloading js player en_US-vflQTSOsS
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 633, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 270, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1066, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 645, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

y2mp3v:
#!/bin/sh
./youtube-dl --verbose --extract-audio --audio-format mp3 --restrict-filenames --o "%(title)s.%(ext)s" --batch-file $1

thanks a lot!!

**Comment by jaimeMF** [comment]
In the script you are calling **`./youtube-dl`**, and I guess that it's not the same executable you run with `youtube-dl`. You'll have to either update that executable or modify the script.

**Comment by 00stormy00** [comment]
OH! I'm sorry!
You are right, there was another version in the current folder.

Now all works great!
I updated my script to:

#!/bin/sh
/usr/local/bin/youtube-dl --extract-audio --audio-format mp3 --restrict-filenames --o "%(title)s.%(ext)s" --batch-file $1

thanks!!
