### ISSUE TITLE
telecinco.es

### ISSUE THREAD

**Issue by jcarlosgarciasegovia** [rg3/youtube-dl#5065]
http://www.telecinco.es/informativos/nacional/Pablo_Iglesias-Informativos_Telecinco-entrevista-Pedro_Piqueras_2_1945155182.html

**Comment by jaimeMF** [comment]
Thanks for the report, it will work in the next version.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.02.28. See [our FAQ](https://yt-dl.org/update) if you need help updating.
