### ISSUE TITLE
Unable to download from the escapist

### ISSUE THREAD

**Issue by SirCmpwn** [rg3/youtube-dl#5068]
sircmpwn@homura /t/tmp.fxiOFZgxNM> youtube-dl --verbose http://www.escapistmagazine.com/videos/view/zero-punctuation/10044-Evolve-Review
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['--verbose', 'http://www.escapistmagazine.com/videos/view/zero-punctuation/10044-Evolve-Review']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.02.23.1
    [debug] Python version 3.4.2 - Linux-3.18.6-1-ARCH-x86_64-with-arch
    [debug] exe versions: ffmpeg 2.5.4, ffprobe 2.5.4, rtmpdump 2.4
    [debug] Proxy map: {}
    [Escapist] 10044: Downloading webpage
    ERROR: Unable to extract config URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 643, in extract_info
        ie_result = ie.extract(url)
      File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 275, in extract
        return self._real_extract(url)
      File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/escapist.py", line 45, in _real_extract
        r'<param\s+name="flashvars"\s+value="config=([^"&]+)', webpage, 'config URL'))
      File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 557, in _html_search_regex
        res = self._search_regex(pattern, string, name, default, fatal, flags, group)
      File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 547, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    youtube_dl.utils.RegexNotFoundError: Unable to extract config URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phihag** [comment]
Thank you for the report. You are using an outdated version of youtube-dl. See [our FAQ](https://yt-dl.org/update) if you need help updating to 2015.02.26.1 or newer, where this should be fixed.

**Comment by SirCmpwn** [comment]
Sorry, I thought I was good to go.

**Comment by terabyte** [comment]
I just tried to get an escapist video with version 2015.02.26.1 and it downloaded an ad only, not the "real" video.  --verbose output follows:

```
$ youtube-dl --verbose http://www.escapistmagazine.com/videos/view/zero-punctuation/10044-Evolve-Review
[debug] System config: []                                       
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.escapistmagazine.com/videos/view/zero-punctuation/10044-Evolve-Review']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.26.1
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[Escapist] 10044: Downloading webpage
[Escapist] 10044: Downloading normal configuration
[Escapist] 10044: Downloading hq configuration
[debug] Invoking downloader on 'http://video.escapistmagazine.com/mp4/escapist/sales-marketing/5387-4a7b988602b3d53a02653768b43bb191.mp4'
[download] Destination: Evolve - One vs Multiplayer-10044.mp4
[download] 100% of 2.38MiB in 00:02
```
The video it downloaded was 45 seconds long and only contained the ad.  Did escapist recently change their website maybe?

**Comment by terabyte** [comment]
Filed #5069 because I don't see how to reopen a closed issue.
