### ISSUE TITLE
Invalid error message if youtube playlist url is truncated

### ISSUE THREAD

**Issue by Elbandi** [rg3/youtube-dl#5074]
If youtube url is truncated or missing, error message is wrong ("Unable to extract title" vs "No such playlist whatever").

This is the log:

    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['-v', '--verbose', '-J', '-s', '--youtube-skip-dash-manifest', 'https://www.youtube.com/playlist?list=LLWfCFp2YbexUlSVM3']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.02.26.2
    [debug] Git HEAD: 250a9bd
    [debug] Python version 2.7.6 - Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
    [debug] exe versions: avconv 9.16-6, avprobe 9.16-6, rtmpdump 2.4
    [debug] Proxy map: {}
    ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/home/elbandi/youtube-dl/youtube_dl/YoutubeDL.py", line 643, in extract_info
        ie_result = ie.extract(url)
      File "/home/elbandi/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
        return self._real_extract(url)
      File "/home/elbandi/youtube-dl/youtube_dl/extractor/youtube.py", line 1325, in _real_extract
        page, 'title')
      File "/home/elbandi/youtube-dl/youtube_dl/extractor/common.py", line 557, in _html_search_regex
        res = self._search_regex(pattern, string, name, default, fatal, flags, group)
      File "/home/elbandi/youtube-dl/youtube_dl/extractor/common.py", line 547, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Orignal yt url: https://www.youtube.com/playlist?list=LLWfCFp2YbexUlSVM3ZOOnLw

**Comment by yan12125** [comment]
Thanks for the suggestion. youtube-dl will give informative messages for such failures in the next version.
