### ISSUE TITLE
about odnoklassniki (ok.ru)

### ISSUE THREAD

**Issue by awatar** [rg3/youtube-dl#5075]
Greetings. I apologize for my English. I have two questions. 1. Do you plan to support social networking site odnoklassniki (ok.ru). Videos can be viewed through the pages with such a reference http://ok.ru/video/20079905452. It would be very good, it is necessary to so many people. Many thanks in advance. 
2. How is it possible to specify in  python script my destination folder for upload video files. For example my code:
import os, sys
import youtube_dl
newpath = ((r'D:\myfolder'))
ydl_opts = {}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
     ydl.download([url])

**Comment by jaimeMF** [comment]
In the future, [please don't use the same issue for multiple requests](https://github.com/rg3/youtube-dl/blob/master/README.md#does-the-issue-involve-one-problem-and-one-problem-only), it's really hard to track them. For the second issue: use the `outtmpl` option, for example `ydl_opts = {'outtmpl': 'DOWNLOADS_FOLDER/%(title)s.%(ext)s'}`, open a **new issue** if you have any problem with it.

**Comment by dstftw** [comment]
Одноклассники will be supported in the next version. Thanks for the report.

**Comment by phihag** [comment]
youtube-dl 2015.02.28 adds support for ok.ru. See [our FAQ](https://yt-dl.org/update) if you need help updating.
