### ISSUE TITLE
Youporn stop working

### ISSUE THREAD

**Issue by mac1202** [rg3/youtube-dl#5078]
Hi since today youporn stop working with youtube-dl here the output : 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-gv', 'http://www.youporn.com/watch/10856809/shy-amateur-redhead-fucked-and-facialed/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.26.2
[debug] Python version 3.4.2 - Linux-3.19.0-1-MANJARO-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 2.5.4, ffprobe 2.5.4, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 643, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youporn.py", line 51, in _real_extract
    webpage, 'JSON parameters')
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 547, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by digitalknigth** [comment]
I have the same problem :

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', 'http://www.youporn.com/watch/9508953/', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.03
[debug] Python version 2.7.6 - Linux-3.16.0-31-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 9508953: Requesting header
[redirect] Following redirect to http://www.youporn.com/watch/9508953/she-knows-how-to-ride-a-cock-dreamroom-productions/
[YouPorn] 9508953: Downloading webpage
ERROR: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 645, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youporn.py", line 51, in _real_extract
    webpage, 'JSON parameters')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 547, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
