### ISSUE TITLE
support for puls4.com

### ISSUE THREAD

**Issue by unki2aut** [rg3/youtube-dl#5079]
It would be nice to download videos from puls4.com:
Pattern like http://www.puls4.com/video/*
Example: http://www.puls4.com/video/querdenker/play/2712650

**Comment by dstftw** [comment]
Puls4 will be supported in the next version. Thanks for the report.

**Comment by phihag** [comment]
puls4 support has been added in youtube-dl 2015.02.28. See [our FAQ](https://yt-dl.org/update) if you need help updating.
