### ISSUE TITLE
Kaltura URL failure....

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5081]
URL: https://cdnapisec.kaltura.com/index.php/kwidget/wid/_557781/uiconf_id/22845202/entry_id/1_plr1syf3

It downloads an 8Kb file named: 1_plr1syf3-1_plr1syf3.unknown_video

Session output:
youtube-dl.py -v "https://cdnapisec.kaltura.com/index.php/kwidget/wid/_557781/uiconf_id/22845202/entry_id/1_plr1syf3"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://cdnapisec.kaltura.com/index.php/kwidget/wid/_557781/uiconf_id/22845202/entry_id/1_plr1syf3']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.02.26.2
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 1_plr1syf3: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1_plr1syf3: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
[debug] Invoking downloader on u'https://cdnapisec.kaltura.com/index.php/kwidget/wid/_557781/uiconf_id/22845202/entry_id/1_plr1syf3'
[download] Destination: 1_plr1syf3-1_plr1syf3.unknown_video
[download] 100% of 7.16KiB in 00:00

Thanks
Ringo

**Comment by dstftw** [comment]
Thanks for the report, it will be fixed in the upcoming version.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.02.28. See [our FAQ](https://yt-dl.org/update) if you need help updating.
