### ISSUE TITLE
Can't Make or Install YDL in Windows 8.1x64/Python 3.4.2150

### ISSUE THREAD

**Issue by HASJ** [rg3/youtube-dl#5098]
Neither any other Python module aside from pip (done with get-pip.py).

All I get is this

cmd.exe
%USERPROFILE%\youtube-dl\setup.py install
D:\Downloads\youtube-dl\setup.py:60: UserWarning: Skipping file youtube-dl.bash-completion since it is not present. Type  make  to build all automatically generated files.
  warnings.warn('Skipping file %s since it is not present. Type  make  to build all automatically generated files.' % fn)
D:\Downloads\youtube-dl\setup.py:60: UserWarning: Skipping file youtube-dl.fish since it is not present. Type  make  to build all automatically generated files.
  warnings.warn('Skipping file %s since it is not present. Type  make  to build all automatically generated files.' % fn)
D:\Downloads\youtube-dl\setup.py:60: UserWarning: Skipping file README.txt since it is not present. Type  make  to build all automatically generated files.
  warnings.warn('Skipping file %s since it is not present. Type  make  to build all automatically generated files.' % fn)
D:\Downloads\youtube-dl\setup.py:60: UserWarning: Skipping file youtube-dl.1 since it is not present. Type  make  to build all automatically generated files.
  warnings.warn('Skipping file %s since it is not present. Type  make  to build all automatically generated files.' % fn)
Traceback (most recent call last):
  File "D:\Downloads\youtube-dl\setup.py", line 74, in <module>
    exec(compile(open('youtube_dl/version.py').read(),
FileNotFoundError: [Errno 2] No such file or directory: 'youtube_dl/version.py'

Admin rights doesn't work either. Help?

EDIT: So dumb... All I had to do was navigate to the YDL folder in the CMD.

**Comment by dstftw** [comment]
Why not just download the windows `youtube-dl.exe` binary with python embedded?

**Comment by HASJ** [comment]
Because I want to edit the --max-connection-server=* under the external.py to actually use my connection in a meaningful way, since there is no way to argument with aria2 using the --external-downloader argument in YDL.

**Comment by dstftw** [comment]
Just checkout the repository as explained [here](https://github.com/rg3/youtube-dl#developer-instructions).

**Comment by HASJ** [comment]
I managed to get pip to work and got it through there.

I am very noobish when it comes to this stuff but I'm learning. Had to add the Scripts folder under my Python and it started working.

**Comment by HASJ** [comment]
Installation is now working, but how do I make/compile it?

**Comment by phihag** [comment]
To make youtube-dl, type `make`.

**Comment by phihag** [comment]
There is no need to edit youtube-dl's source code in your case. Instead, simply use the `--external-downloader-args` option, possibly in a [configuration file](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration).

**Comment by HASJ** [comment]
Thanks.
