### ISSUE TITLE
Help: How to download a 480p video?

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#5102]
I find that very often, I will download a 720p video by default. If I try to ask for a 480p or less, I get 360p.

I understand that youtube only makes 360 and 720p available as a simple mp4, and the rest are broken up into DASH pieces. How can I get a 480p re-assembly of those dash pieces?

Sample request:
youtube-dl  -f "[height <=? 480]" https://www.youtube.com/watch?v=PxqJvFcvZE4

**Comment by phihag** [comment]
At the moment, DASH videos are not yet offered automatically. You can merge them by hand though:
```
youtube-dl -f "bestvideo[height <= 480][ext=mp4]+bestaudio/[height <=? 480]" PxqJvFcvZE4
```
