### ISSUE TITLE
Unable to download 360p video?

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#5109]
I am experimenting with Youtube-dl, and trying to fetch a science playlist.
keybounceMBP:science michael$ youtube-dl --version
2015.02.28
keybounceMBP:science michael$ youtube-dl -f height=360 "https://www.youtube.com/watch?v=wvtRXjQXaI0&index=1&list=PLbo
c_P9zcJhiqIetHQeNxNT8R5KnVSNE0"
[youtube:playlist] Downloading playlist PLboc_P9zcJhiqIetHQeNxNT8R5KnVSNE0 - add --no-playlist to just download video wvtRXjQXaI0
[youtube:playlist] PLboc_P9zcJhiqIetHQeNxNT8R5KnVSNE0: Downloading webpage
[download] Downloading playlist: CMB Playlist!
[youtube:playlist] playlist CMB Playlist!: Collected 5 video ids (downloading 5 of them)
[download] Downloading video 1 of 5
[youtube] wvtRXjQXaI0: Downloading webpage
[youtube] wvtRXjQXaI0: Extracting video information
[youtube] wvtRXjQXaI0: Downloading DASH manifest
ERROR: requested format not available

**Comment by seojoohyun** [comment]
According to the help (call youtube-dl with -h) you need brackets around the height parameter, it also shows quotes around it, like this:
youtube-dl -f "[height=360]" 
I believe the quotes are for if there are spaces in the argument, might not always need them but safer to put them anyway.

**Comment by keybounce** [comment]
>youtube-dl -f "[height=360]" 

Aha! That (the brackets) did it. Thank you.
Somehow, I thought those were only for an expression.

---
Entertaining minecraft videos
http://YouTube.com/keybounce
