### ISSUE TITLE
france3

### ISSUE THREAD

**Issue by rbgithoub** [rg3/youtube-dl#5111]
~/Documents/Documentaires$ youtube-dl --verbose pluzz.francetv.fr/videos/une_division_ss_en_france_das_reich_.118675858.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'pluzz.francetv.fr/videos/une_division_ss_en_france_das_reich_.118675858.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.03
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.7
[debug] exe versions: avconv 0.8.16-6, avprobe 0.8.16-6, ffmpeg 0.8.16-6, ffprobe 0.8.16-6, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[pluzz.francetv.fr] une_division_ss_en_france_das_reich_.118675858: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/rbm/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/rbm/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1671, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by rbgithoub** [comment]
close

**Comment by jaimeMF** [comment]
The url you posted gives and 404 Not found error, could you try with http://pluzz.francetv.fr/videos/une_division_ss_en_france_das_reich.html? (since it's geoblocked I can't verify that the download works)

**Comment by rbgithoub** [comment]
Le Tue, 03 Mar 2015 02:12:41 -0800,
Jaime Marquínez Ferrándiz <notifications@github.com> a écrit :

> The url you posted gives and 404 Not found error, could you try with
> http://pluzz.francetv.fr/videos/une_division_ss_en_france_das_reich.html?
> (since it's geoblocked I can't verify that the download works)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/rg3/youtube-dl/issues/5111#issuecomment-76919157

In the meantime I closed the ticket. I am myopic, so I took a comma for
a period in the url. It is the first time I encounter a comma in a url.

Sorry for the trouble.


-- 
René Bastian
www.pythoneon.org
