### ISSUE TITLE
Download location

### ISSUE THREAD

**Issue by davidhedlund** [rg3/youtube-dl#5126]
I didn't see this option with man youtube-dl.

How can I specify the download location for say https://www.youtube.com/watch?v=wvV37--h2-k on my computer?

**Comment by phihag** [comment]
[See our FAQ](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-put-downloads-into-a-specific-folder) - use the `-o` option.

**Comment by davidhedlund** [comment]
Thank you.
