### ISSUE TITLE
extremetube unable to extract video url

### ISSUE THREAD

**Issue by ShardDragoon** [rg3/youtube-dl#5127]
Tried extremetube.com downloading today and failed with the top suggested content, for this issue submission www.extremetube.com/video/sex-revenge-213547 was used.

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'www.extremetube.com/video/sex-revenge-213547']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.03.1
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-63780-g0545ef7, rtmpdump 2.3
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[ExtremeTube] 213547: Downloading webpage
ERROR: Unable to extract video_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
--verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 648, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\extremetube.pyo", line 53, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 557, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 547, in _search_regex
RegexNotFoundError: Unable to extract video_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ver
-dl with the --verbose flag and include its complete output.

**Comment by naglis** [comment]
This issue should be fixed in the next release of youtube-dl. Thanks for the report!
