### ISSUE TITLE
Ustream URL

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5128]
Direct URL:  http://www.ustream.tv/embed/recorded/59307601?ub=ff0000&lc=ff0000&oc=ffffff&uc=ffffff&v=3&wmode=direct

or 

Embedded URL: http://sportscanada.tv/canadagames/index.php/week2/figure-skating/444

Output:
C:\>youtube-dl -v "http://www.ustream.tv/embed/recorded/59307601?ub=ff0000&lc=ff
0000&oc=ffffff&uc=ffffff&v=3&wmode=direct"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.ustream.tv/embed/recorded/59307601
?ub=ff0000&lc=ff0000&oc=ffffff&uc=ffffff&v=3&wmode=direct']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.03.1
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20
[debug] Proxy map: {}
[ustream] 59307601: Downloading webpage
[ustream] 59307601: Extracting information
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bu
g . Make sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete outp
ut.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 648, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\ustream.pyo", line 48, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 557, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 547, in _search_regex
RegexNotFoundError: Unable to extract title; please report this issue on https:/
/yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
  to update. Be sure to call youtube-dl with the --verbose flag and include its
complete output.

Thanks Ringo

**Comment by yan12125** [comment]
Thanks for the report. This video will be downloaded without errors in the next version of youtube-dl.

**Comment by dstftw** [comment]
This has been fixed in youtube-dl 2015.04.26. See our [FAQ](https://yt-dl.org/update) if you have problems updating.
