### ISSUE TITLE
-U deprecated?

### ISSUE THREAD

**Issue by davidhedlund** [rg3/youtube-dl#5129]
sudo youtube-dl -U # installed from package (version 2015.02.26.2) gives:
"It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update."

I am sure I could use this some months ago with the youtube-dl package. What am I missing?

**Comment by davidhedlund** [comment]
This helped (I did not remember I installed with pip): sudo pip install -U youtube-dl

**Comment by davidhedlund** [comment]
Cannot youtube-dl determine that and output "sudo pip install -U youtube-dl" if I run "sudo youtube-dl -U"

**Comment by davidhedlund** [comment]
Thats an idea for you.

**Comment by phihag** [comment]
There is no way that I am aware of to reliably determine whether youtube-dl was installed manually with setup.py, from a tarball, with a package manager, or with pip. If you know how to distinguish these places, please describe how you can do that.

Invoking `sudo pip install -U youtube-dl` could be quite hazardous if youtube-dl was not installed via pip, so we just notify the user that it cannot update automatically.
