### ISSUE TITLE
Some Cinemassacre videos cannot be downloaded

### ISSUE THREAD

**Issue by ssokolow** [rg3/youtube-dl#5131]
I decided to use youtube-dl to get better quality versions of all the pre-HD AVGN episodes I downloaded as I was watching them on YouTube and discovered that following videos on Cinemassacre.com aren't hosted by ScreenwaveMedia like the others. (I believe one is a YouTube embed and the other two are private Blip.tv videos that I was only able to find and download because Blip still exposes a "Sorry, this is private" page to search engines)

http://cinemassacre.com/2006/09/01/mckids/
http://cinemassacre.com/2006/12/07/chronologically-confused-about-bad-movie-and-video-game-sequel-titles/
http://cinemassacre.com/2009/01/27/milons-secret-castle-2/

**Comment by yan12125** [comment]
Thanks for the report. All of the above 3 videos can be downloaded in the next version of youtube-dl.

**Comment by dstftw** [comment]
This has been fixed in youtube-dl 2015.04.26. See our [FAQ](https://yt-dl.org/update) if you have problems updating.
