### ISSUE TITLE
Add support for Telewebion.com

### ISSUE THREAD

**Issue by lfl2** [rg3/youtube-dl#5135]
Telewebion.com is a TV archive. For downloding, it is just enough to get URL and then use rtmpdump, but currently youtube-dl only outputs a useless SMIL file.

This is an example URL:
```bash
http://www.telewebion.com/fa/1263668/%D9%82%D8%B1%D8%B9%D9%87%E2%80%8C%DA%A9%D8%B4%DB%8C-%D9%84%DB%8C%DA%AF-%D9%82%D9%87%D8%B1%D9%85%D8%A7%D9%86%D8%A7%D9%86-%D8%A7%D8%B1%D9%88%D9%BE%D8%A7/%2B-%D9%81%D9%88%D8%AA%D8%A8%D8%A7%D9%84.html
```
using youtube-dl, we get SMIL file downloaded that looks like this:
```xml
<smil>
<head>
<meta base="rtmpe://s4.telewebion.com:1935/vod"/>
</head>
<body>
<switch>

<video title="500K" system-bitrate="512000" src="mp4:/media/telewebion/tv3/2015-03-05/normalProgram/0057/file.mp4"/>

<video title="256K" system-bitrate="262144" src="mp4:/media/telewebion/tv3/2015-03-05/normalProgram/0057/file_224_32.mp4"/>

<video title="132K" system-bitrate="135168" src="mp4:/media/telewebion/tv3/2015-03-05/normalProgram/0057/file_100_32.mp4"/>

</switch>
</body>
</smil>
```
Bitrates can be selected and downloaded by concatenating base URL and appropriate video URL. For example, URL for 500k video is:
```bash
rtmpe://s4.telewebion.com:1935/vod/mp4:/media/telewebion/tv3/2015-03-05/normalProgram/0057/file.mp4
```

that can be downloaded using:
```bash
rtmpdump -r rtmpe://s4.telewebion.com:1935/vod/mp4:/media/telewebion/tv3/2015-03-05/normalProgram/0057/file.mp4 -o out.mp4
```

**Comment by lfl2** [comment]
Thanks, but the site specific request still isn't adressed. I don't know how to implement a site-specific script, but it seemst that it seems to be straightforward. Get the smil file from the html, and get the content from it.
If generic method can find the .smil files, it will be ok. If not, for this site, .smil URL is located in `window.vod_smil`. Right now, the token, etc. is not needed, it is sufficient to include the URL until the first `&`.
From this:
`http://www.telewebion.com/fa/1263668/%D9%82%D8%B1%D8%B9%D9%87%E2%80%8C%DA%A9%D8%B4%DB%8C-%D9%84%DB%8C%DA%AF-%D9%82%D9%87%D8%B1%D9%85%D8%A7%D9%86%D8%A7%D9%86-%D8%A7%D8%B1%D9%88%D9%BE%D8%A7/%2B-%D9%81%D9%88%D8%AA%D8%A8%D8%A7%D9%84.html`
you get this:
`http://smilserver.telewebion.com/smil/1263668.smil?filepath=/media/telewebion/tv3/2015-03-05/normalProgram/0057/file.mp4`
and this is the smil file.

**Comment by dstftw** [comment]
It's handled perfectly with generic extractor. Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by lfl2** [comment]
Thanks, it works! I works fine for this URL.
But not for this URL:
`http://www.telewebion.com/fa/1291102/%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C-%D9%88-%D9%BE%DB%8C%D8%AF%D8%A7%DB%8C%D8%B4-%D8%AA%D9%85%D8%AF%D9%86/%D9%85%D8%B3%D8%AA%D9%86%D8%AF-4.html`

**Comment by lfl2** [comment]
Should you also re-open https://github.com/rg3/youtube-dl/issues/5145?

**Comment by yan12125** [comment]
Telewebion support will be complete in the next version.

**Comment by marvintkl** [comment]
ERROR: Unsupported URL: https://www.telewebion.com/episode/xxxxxx

It's not supported anymore?
