### ISSUE TITLE
Add support for filimo.com

### ISSUE THREAD

**Issue by lfl2** [rg3/youtube-dl#5136]
For example:
```bash
http://www.filimo.com/star/season/one/uid/qkz9n
```
When you play, it loads several m3u files from stream.filmio.com
50k/aparat.m3u8
100k/aparat.m3u8
200k/aparat.m3u8
400k/aparat.m3u8
900k/aparat.m3u8
1200k/aparat.m3u8
2182/aparat.m3u8

that shows the quality. It can be downloaded using ffmpeg:
```bash
ffmpeg -i http://stream.filimo.com/.../2182/aparat.m3u8 output.mp4
```

**Comment by dstftw** [comment]
Works fine with latest version (2016.05.16).
