### ISSUE TITLE
Please add support for http://iptv.orf.at

### ISSUE THREAD

**Issue by mkurz** [rg3/youtube-dl#5140]
See http://iptv.orf.at/
Thanks!

**Comment by phihag** [comment]
Can you [name an example URL](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md#is-the-description-of-the-issue-itself-sufficient)? Or do you want just support for the single URL http://iptv.orf.at/ ?

**Comment by mkurz** [comment]
Thanks!
