### ISSUE TITLE
Please add support for http://insider.orf.at

### ISSUE THREAD

**Issue by mkurz** [rg3/youtube-dl#5141]
See http://insider.orf.at/
Thanks!

**Comment by phihag** [comment]
Can you [name an example URL](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md#is-the-description-of-the-issue-itself-sufficient)? Or do you want just support for the single URL http://insider.orf.at/ ?

**Comment by mkurz** [comment]
You can find example urls on the page http://insider.orf.at/ where the header says  "VIDEOHIGHLIGHTS". An url would be http://insider.orf.at/stories/sport/videohighlights-austria-wien-rapid-wien-2-1+16345 
These pages are usually only for a few days only.
Thanks!

**Comment by mkurz** [comment]
One more thing: As you can see each page usually contains more then one video.

**Comment by mkurz** [comment]
A current active url would now be http://insider.orf.at/stories/sport/videohighlights-skispringen-in-kuopio+16366

**Comment by mkurz** [comment]
Any news on this?

**Comment by mkurz** [comment]
Another current active url would be:
http://insider.orf.at/stories/gewinnspiele/waehlen-sie-das-tor-des-monats+18104

**Comment by mkurz** [comment]
Or http://insider.orf.at/stories/kultur/songbook-der-wettbewerb+17797

**Comment by mkurz** [comment]
@dstftw Can you have a look?

**Comment by mkurz** [comment]
http://insider.orf.at does not exist anymore (redirects to other page which does not contain videos anymore)
