### ISSUE TITLE
Add python 3.2 target to .travis.yml

### ISSUE THREAD

**Issue by yan12125** [rg3/youtube-dl#5144]
youtube-dl is now declared as compatible with python 3.2 in at least ```setup.py``` and ```README.md```. I think is a good idea to add "3.2" to python versions list in ```.travis.yml``` for detecting edge corners between python 3.2 and 3.3+. Is there any opinion?

**Comment by phihag** [comment]
Thanks for the report, added.

**Comment by xantares** [comment]
interesting, I just spotted a bug with 3.2 : #5132

**Comment by yan12125** [comment]
@xantares In fact, it's the one that inspired me to open this issue. I was unable to find it in so many issues, thanks for the reminder :)
