### ISSUE TITLE
Do not output SMIL file, get the content

### ISSUE THREAD

**Issue by lfl2** [rg3/youtube-dl#5145]
Some websites use SMIL for presenting multimedia, and right now youtube-dl only dumps SMIL file in generic downloader. For example, look at the issue https://github.com/rg3/youtube-dl/issues/5135, all the generic downloder does is downloading an SMIL file, which contains one or several URLs that can be downloaded using rtmpdump. So it is a good choice not to output SMIL file, and get the content.
More information on SMIL:
https://en.wikipedia.org/wiki/Synchronized_Multimedia_Integration_Language

**Comment by yan12125** [comment]
Thanks for the suggestion. youtube-dl will parse SMIL manifest and download videos in the next version.

**Comment by lfl2** [comment]
Could you please reopen this issue?
