### ISSUE TITLE
Get video file from Vimeo over https if it the video URL starts with https

### ISSUE THREAD

**Issue by lfl2** [rg3/youtube-dl#5147]
When downloading from Vimeo.com, even if you provide video URL that starts with https, the video is downloaded over http. The right choice is to download the video URL over https.

**Comment by jaimeMF** [comment]
It sems that they are downloaded over https:
```
youtube-dl --ignore-config --verbose 'http://vimeo.com/56015672'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--ignore-config', '--verbose', 'http://vimeo.com/56015672']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.03.1
[debug] Git HEAD: 3c6f245
[debug] Python version 3.4.3 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.2, avprobe 11.2, ffmpeg 2.5.4, ffprobe 2.5.4, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 56015672: Downloading webpage
[vimeo] 56015672: Extracting information
[vimeo] 56015672: Downloading webpage
[debug] Invoking downloader on 'https://avvimeo-a.akamaihd.net/<...>'
[download] youtube-dl test video - ★ ' ' 幸 _ _ ä ↭ 𝕐-56015672.mp4 has already been downloaded
[download] 100% of 601.62KiB
```

Could you post the url with the problem and the output of `youtube-dl --verbose URL`?

**Comment by lfl2** [comment]
Check this:
```bash
youtube-dl -g --ignore-config --verbose 'https://player.vimeo.com/video/56015672'
```
It outputs something like this:
http://av.vimeo.com/.../aaa.mp4?token2=ttt&aksessionid=sss

**Comment by jaimeMF** [comment]
Thanks for the report, it will use https in the next version.

**Comment by yesworld** [comment]
i try this:
`youtube-dl -g --ignore-config --verbose 'https://player.vimeo.com/video/56015672'`

> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: ['-g', '--ignore-config', '--verbose', 'https://player.vimeo.com/video/56015672']
> [debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
> [debug] youtube-dl version 2014.02.17
> [debug] Python version 2.7.6 - Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa
> [debug] Proxy map: {}
> ERROR: Unable to download webpage: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>
>   File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 191, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1157, in urlopen
>     return self._opener.open(req)
>   File "/usr/lib/python2.7/urllib2.py", line 410, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python2.7/urllib2.py", line 442, in error
>     result = self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 404, in open
>     response = self._open(req, data)
>   File "/usr/lib/python2.7/urllib2.py", line 422, in _open
>     '_open', req)
>   File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 572, in https_open
>     return self.do_open(HTTPSConnectionV3, req)
>   File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
>     raise URLError(err)
