### ISSUE TITLE
503 Error: Service Unavailable when downloading video from Dailymotion

### ISSUE THREAD

**Issue by jshergal** [rg3/youtube-dl#5151]
Verbose output listed below -

C:\Tools\youtube-dl>youtube-dl.exe --verbose http://www.dailymotion.com/video/xy
muc0_discovery-channel-ultimate-journeys-bulgaria_travel
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.dailymotion.com/video/xymuc
0_discovery-channel-ultimate-journeys-bulgaria_travel']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.03.03.1
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-60393-g9707b53, ffprobe N-60393-g9707b53, rtmpdum
p 2.4
[debug] Proxy map: {}
[dailymotion] xymuc0: Downloading webpage
[dailymotion] xymuc0: Extracting information
[dailymotion] xymuc0: Downloading embed page
ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable (caused b
y HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure yo
u are using the latest version; type  youtube-dl -U  to update. Be sure to call
youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 314, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1674, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

**Comment by jaimeMF** [comment]
It works fine for me, maybe it was a temporary server issue?

**Comment by jshergal** [comment]
Maybe it was a server issue.  It is working for me now as well.
