### ISSUE TITLE
adult swim video not downloading

### ISSUE THREAD

**Issue by kizerage** [rg3/youtube-dl#5152]
I am trying to download this adultswim video. Here is the link:

http://www.adultswim.com/videos/tim-and-eric-awesome-show-great-job/dr-steve-brule-for-your-wine/
I have the latest version of youtube-dl
This is the error it gives me:
Type Error: 'NoneType' object is not iterable

I thought adultswim was supported now?

**Comment by naglis** [comment]
This issue should be fixed in the next release of youtube-dl. Thank you for the report!
