### ISSUE TITLE
Fails to download searches on Youtube. Unable to extract result HTML error.

### ISSUE THREAD

**Issue by juanjofm** [rg3/youtube-dl#5155]
https://www.youtube.com/results?search_query=something

This was working days ago.

[youtube:search_url] something: Downloading webpage
ERROR: Unable to extract result HTML; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 648, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1535, in _real_extract
    r'(?s)<ol class="item-section"(.*?)</ol>', webpage, 'result HTML')
  File "./youtube-dl/youtube_dl/extractor/common.py", line 547, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract result HTML; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This will be fixed in the next version. Thanks for the report.
