### ISSUE TITLE
Unsupported URL with CBC radio

### ISSUE THREAD

**Issue by jones-github** [rg3/youtube-dl#5156]
youtube-dl-2015.03.03.1-1.fc20.noarch says "Unsupported URL" when trying to download a CBC radio audio clip.
The command I used  is:
"youtube-dl -v --dump-intermediate-pages 'http://www.cbc.ca/player/AudioMobile/All%20in%20a%20Weekend%20Montreal/ID/2657632011/'"

My typescript file contains:
"Script started on Sat 07 Mar 2015 11:45:31 AM EST
[jones@localhost youtubedl]$ youtube-dl -v --dump-intermediate-pages 'http://www.cbc.^M<youtube-dl -v --dump-intermediate-pages 'http://www.cbc.c                           ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^Ha/player/AudioMobile/All%20^M^M<diate-pages 'http://www.cbc.ca/player/AudioMobile/All%20i                           ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^Hn%20a%20Weekend%20Montreal/^M^M<ca/player/AudioMobile/All%20in%20a%20Weekend%20Montreal/I                           ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^HD/2657632011/'^M
[debug] System config: ['--prefer-free-formats']^M
[debug] User config: []^M
[debug] Command-line args: ['-v', '--dump-intermediate-pages', 'http://www.cbc.ca/player/AudioMobile/All%20in%20a%20Weekend%20Montreal/ID/2657632011/']^M
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8^M
[debug] youtube-dl version 2015.03.03.1^M
[debug] Python version 2.7.5 - Linux-3.18.8-100.fc20.x86_64-x86_64-with-fedora-20-Heisenbug^M
[debug] exe versions: ffmpeg 2.1.7, ffprobe 2.1.7^M
[debug] Proxy map: {}^M
[generic] 2657632011: Requesting header^M
^[[0;33mWARNING:^[[0m Falling back on generic information extractor.^M
[generic] 2657632011: Downloading webpage^M
[generic] Dumping request to http://www.cbc.ca/player/AudioMobile/All%20in%20a%20Weekend%20Montreal/ID/2657632011/^M
PCFET0NUWVBFIGh0bWwgUFVCTElDICItLy9XM0MvL0RURCBYSFRNTCAxLjAgU3RyaWN0Ly9FTiIgImh0dHA6Ly93d3cudzNvcmcvVFIveGh0bWwxL0RURC94aHRtbDEtc3RyaWN0LmR0ZCI+CjwhLS1baWYgbHRlIElFIDddPjxodG1sIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hodG1sIiB4bWw6bGFuZz0iZW4iIGxhbmc9ImVuIiBjbGFzcz0iaWVvbGQiPjwhW2VuZGlmXS0tPgo8IS0tW2lmIElFIDhdPjxodG1sIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hodG1sIiB4bWw6bGFuZz0iZW4iIGxhbmc9ImVuIiBjbGFzcz0iaWU4Ij48IVtlbmRpZl0tLT4KPCEtLVtpZiBJRSA5XT48aHRtbCB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94aHRtbCIgeG1sOmxhbmc9ImVuIiBsYW5nPSJlbiIgY2xhc3M9ImllOSI+PCFbZW5kaWZdLS0+CjwhLS1baWYgZ3QgSUUgOV0+PCEtLT48aHRtbCB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94aHRtbCIgeG1sOmxhbmc9ImVuIiBsYW5nPSJlbiI+PCEtLTwhW2VuZGlmXS0tPgoKPCEtLSBleHBlY3RpbmcgP2NhdD08ZnVsbCBjYXRlZ29yeSB0aXRsZT4maWQ9PGNsaXAgaWQgKG9wdGlvbmFsKT4mcGFnZT08cGFnZSBudW1iZXIgKG9wdGlvbmFsKT4mc29ydD08RmVhdHVyZWQgKGRlZmF1bHQpLCBNb3N0UmVjZW50LCBNb3N0UG9wdWxhcj4gLS0+CgoKCgoKCgoKCgoKCgoKCgoKCgoKCiAgICAKCjxoZWFkPgoKCgoKCgo8bWV0YSBodHRwLWVxdWl2PSJDb250ZW50LVR5cGUiIGNvbnRlbnQ9InRleHQvaHRtbDsgY2hhcnNldD11dGYtOCIvPgo8bWV0YSBodHRwLWVxdWl2PSJYLVVBLUNvbXBhdGlibGUiIGNvbnRlbnQ9IklFPWVkZ2UiIC8+CjxtZXRhIG5hbWU9ImFwcGxpY2F0aW9uLW5hbWUiIGNvbnRlbnQ9Ind3dy5jYmMuY2EiIC8+CjxsaW5rIHJlbD0ic2hvcnRjdXQgaWNvbiIgdHlwZT0iaW1hZ2UvaWNvIiBocmVmPSIvZmF2aWNvbi5pY28iIC8+CjxtZXRhIG5hbWU9Im1zQXBwbGljYXRpb24tSUQiIGNvbnRlbnQ9IkFwcCIgLz4KPG1ldGEgbmFtZT0ibXNBcHBsaWNhdGlvbi1QYWNrYWdlRmFtaWx5TmFtZSIgY29udGVudD0iQ2FuYWRpYW5Ccm9hZGNhc3RpbmdDb3Jwby5DQkNfcHc4cTlidmF2azY4cCIgLz4KCgogICAgCiAgICAKICAgIDxtZXRhIG5hbWU9ImRhdGUiIGNvbnRlbnQ9IjIwMTQvMTAvMjAiIC8+CgoKCgoKCgoKCgoKCgoKCgoKCgo8c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCIgc3JjPSIvaS9sL3l1aS8zLjExLjAveXVpL3l1aS1taW4uanMiIGlkPSJ5dWlnbG9iYWxub2RlIj48L3NjcmlwdD4KPHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiPgoJWVVJLkdsb2JhbENvbmZpZyA9IHtiYXNlOicvaS9sL3l1aS8zLjExLjAvJyxyb290OiczLjExLjAvJyxjb21iaW5lOiB0cnVlLGNvbWJvQmFzZTogJy9pL2wvY29tYm9sb2FkZXIvaW5kZXgucGhwP2I9aS9sL3l1aSZmPScsY2hhcnNldDogJ3V0Zi04Jyx0aW1lb3V0OiAxMDAwMCxhbGxvd1JvbGx1cDogZmFsc2UsZmlsdGVyOiB7J3NlYXJjaEV4cCcgOiAnKCYpKD8hZj0pJywncmVwbGFjZVN0cic6ICcsJwl9fTsKPC9zY3JpcHQ+CjwhLS08c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCIgc3JjPSIvZy9pL3l1aW1vZHVsZXMvMy4xMS4wLmpzIj48L3NjcmlwdD4tLT4gPCEtLSByZW1vdmUgdGhpcyBhZnRlciB0aGUgdmlkZW8gdGVhbSByZWZhY3RvcnMgdGhlUGxhdGZvcm1Q
[generic] 2657632011: Extracting information^M
^[[0;31mERROR:^[[0m Unsupported URL: http://www.cbc.ca/player/AudioMobile/All%20in%20a%20Weekend%20Montreal/ID/2657632011/^M
Traceback (most recent call last):^M
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 775, in _real_extract^M
    doc = parse_xml(webpage)^M
  File "/usr/lib/python2.7/site-packages/youtube_dl/utils.py", line 1506, in parse_xml^M
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)^M
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML^M
    parser.feed(text)^M
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed^M
    self._raiseerror(v)^M
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror^M
    raise err^M
ParseError: not well-formed (invalid token): line 70, column 124^M
Traceback (most recent call last):^M
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 648, in extract_info^M
    ie_result = ie.extract(url)^M
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 275, in extract^M
    return self._real_extract(url)^M
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1226, in _real_extract^M
    raise UnsupportedError(url)^M
UnsupportedError: Unsupported URL: http://www.cbc.ca/player/AudioMobile/All%20in%20a%20Weekend%20Montreal/ID/2657632011/^M
^M
[jones@localhost youtubedl]$ exit^M
exit^M

Script done on Sat 07 Mar 2015 11:46:07 AM EST
"

**Comment by jones-github** [comment]
Also posted at
https://bugzilla.redhat.com/show_bug.cgi?id=1199736

The typscript is posted there as an attachment.

**Comment by yan12125** [comment]
Thanks for the report and sorry for the late response. CBC radios will be supported in the next version.

**Comment by dn3s** [comment]
The test case added in commit 77bd4bef46b3d13f671294ca2a836cb4ca0fbd25 fails for me.

**Comment by yan12125** [comment]
It's fixed in git but not included in the latest release (2016.05.16) yet.

**Comment by dn3s** [comment]
ok. I was just starting to write a new bug report, so I'll stop and pull from git. Thanks!
