### ISSUE TITLE
Break.com video download algorithm not working properly

### ISSUE THREAD

**Issue by MaryCoding** [rg3/youtube-dl#5164]
Hi Guys, 

I have been wanting to download a few videos from break.com but I am running into some issues. The downloaded video is a  version of  the `thumbnail.mp4`. In other words it is just a video of thumbnails of the actual video with bit rate 0. Could you please correct and have youtube-dl download the high(864) or highest(2240) quality bit rate of the video. Those versions of bit rates are available, check api results (json format): http://api.breakmedia.com/Application/Page/Get?siteName=Break&appName=Iphone%20with%20Articles&uri=feed/iPhone_Featured&version=2

Youtube-dl is downloading:
> http://video1.break.com/dnet/media/038/830/2830038/this-guy-only-dates-women-with-gaping-holes-for-nostrils-here-s-why-thumbnail.mp4?1B608EE7AFCE3765E176F3C6FBB98002B3D18C64572F2307D769AE70A971F1BCDA23

Youtube-dl should download bitrate 496(Always available):
> http://video1.break.com/dnet/media/038/830/2830038/this-guy-only-dates-women-with-gaping-holes-for-nostrils-here-s-why-496_kbps.mp4?1B608EE7AFCE3765E176F3C6FBB98002B3D18C64572F2307D769AE70A971F1BCDA23

Or Download bitrate 864 (great - Sometimes available):
> http://video1.break.com/dnet/media/038/830/2830038/this-guy-only-dates-women-with-gaping-holes-for-nostrils-here-s-why-864_kbps.mp4?1B608EE7AFCE3765E176F3C6FBB98002B3D18C64572F2307D769AE70A971F1BCDA23

Or Download bitrate 2240 (best - Sometimes available):
> http://video1.break.com/dnet/media/038/830/2830038/this-guy-only-dates-women-with-gaping-holes-for-nostrils-here-s-why-2240_kbps.mp4?1B608EE7AFCE3765E176F3C6FBB98002B3D18C64572F2307D769AE70A971F1BCDA23

Test run:
```
youtube-dl -v -o "/media/%(title)s.mp4" "http://www.break.com/video/did-this-dude-falcon-punch-his-buddy-2829644"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-o', '/media/%(title)s.mp4', 'http://www.break.com/video/did-this-dude-falcon-punch-his-buddy-2829644']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.03.1
[debug] Python version 2.7.6 - Linux-3.13.0-35-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg git-2014-12-27-d4fd3f2, ffprobe git-2014-12-27-d4fd3f2
[debug] Proxy map: {}
[Break] 2829644: Downloading webpage
[debug] Invoking downloader on u'http://video1.break.com/dnet/media/644/829/2829644/when-friends-fight-friends-thumbnail.mp4?1B608EE7AFCE3765E176F3C6FBB98002B3D18C64572F2307D769AE70A976F8B90542?1B608EE7AFCE3765E176F3C6FBB98002B3D18C64572F2307D769AE70A976F8B90542'
[download] Destination: /media/sf_linux_sandbox/Did This Dude Falcon Punch His Buddy.mp4
[download] 100% of 788.54KiB in 00:13
root@bullseye2346:~# youtube-dl -v -o "/media/%(title)s.mp4" "http://www.break.com/video/why-date-girls-with-big-nostrils-2830038"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-o', '/media/%(title)s.mp4', 'http://www.break.com/video/why-date-girls-with-big-nostrils-2830038']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.03.1
[debug] Python version 2.7.6 - Linux-3.13.0-35-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg git-2014-12-27-d4fd3f2, ffprobe git-2014-12-27-d4fd3f2
[debug] Proxy map: {}
[Break] 2830038: Downloading webpage
[debug] Invoking downloader on u'http://video1.break.com/dnet/media/038/830/2830038/this-guy-only-dates-women-with-gaping-holes-for-nostrils-here-s-why-thumbnail.mp4?1B608EE7AFCE3765E176F3C6FBB98002B3D18C64572F2307D769AE70A971F1B8EB9F?1B608EE7AFCE3765E176F3C6FBB98002B3D18C64572F2307D769AE70A971F1B8EB9F'
[download] Destination: /media/sf_linux_sandbox/This Guy Only Dates Women With Gaping Holes For Nostrils. Here's Why!.mp4
[download] 100% of 208.75KiB in 00:04
```

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.

**Comment by MaryCoding** [comment]
Thank you!
