### ISSUE TITLE
Add support for Scottish Screen Archive (http://ssa.nls.uk/)

### ISSUE THREAD

**Issue by RfzVd** [rg3/youtube-dl#5169]
Example [url](http://ssa.nls.uk/film/3561).

Output with youtube-dl -v http://ssa.nls.uk/film/3561

>[debug] System config: []
>[debug] User config: []
>[debug] Command-line args: ['-v', 'http://ssa.nls.uk/film/3561']
>[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
>[debug] youtube-dl version 2015.03.09
>[debug] Python version 2.7.3 - Linux-3.2.0-4-686-pae-i686-with-debian-7.7
>[debug] exe versions: avconv 0.8.16-6, avprobe 0.8.16-6, ffprobe 0.8.16-6, rtmpdump 2.4
>[debug] Proxy map: {}
>[generic] 3561: Requesting header
>WARNING: Falling back on generic information extractor.
>[generic] 3561: Downloading webpage
>[generic] 3561: Extracting information
>ERROR: Unsupported URL: http://ssa.nls.uk/film/3561
>Traceback (most recent call last):
> File "/home/user/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
>    ie_result = ie.extract(url)
>  File "/home/user/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
>    return self._real_extract(url)
>  File "/home/user/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1283, in _real_extract
>    raise UnsupportedError(url)
>UnsupportedError: Unsupported URL: http://ssa.nls.uk/film/3561

**Comment by dstftw** [comment]
Scottish Screen Archive will be supported in the next version. Thanks for the report.

**Comment by dstftw** [comment]
Support for Scottish Screen Archive has been added in youtube-dl 2015.03.15. See [our FAQ](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) on how to update.
