### ISSUE TITLE
try this https://www.youtube.com/watch?v=9PFmxIdvKEA

### ISSUE THREAD

**Issue by emabiz** [rg3/youtube-dl#5170]
https://www.youtube.com/watch?v=9PFmxIdvKEA

gives an error:
python youtube-dl.exe --list-formats "https://www.youtube.com/watch?v=9PFmxIdvKEA"
[youtube] Setting language
[youtube] Confirming age
[youtube] 9PFmxIdvKEA: Downloading webpage
[youtube] 9PFmxIdvKEA: Downloading video info webpage
[youtube] 9PFmxIdvKEA: Extracting video information
[youtube] 9PFmxIdvKEA: Encrypted signatures detected.
[youtube] 9PFmxIdvKEA: Downloading js player vflT9SJ6t
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 530, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 444, in _extract_signature_funct
ion
  File "youtube_dl\extractor\youtube.pyo", line 505, in _parse_sig_js
  File "youtube_dl\extractor\common.pyo", line 399, in _search_regex
RegexNotFoundError: Unable to extract Initial JS player signature function name;
 please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl
with the --verbose flag and include its complete output. Make sure you are using
 the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl
 with the --verbose flag and include its complete output. Make sure you are usin
g the latest version; type  youtube-dl -U  to update.

I'm using the last version:
youtube-dl is up-to-date (2015.03.09)

Thank you

**Comment by jaimeMF** [comment]
Works fine for me, are you 100% sure you are using the last version? `[youtube] Setting language` and other message shouldn't appear.
Anyways, [post the **full output**](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) of `youtube-dl --verbose "https://www.youtube.com/watch?v=9PFmxIdvKEA"`

**Comment by emabiz** [comment]
Sorry,
I've updated but maybe I was still using the old version.
Now I've complely removed the old folder and retried and it works.

Thank you for your fast answer.
