### ISSUE TITLE
[youtube-dl] output file path .#\ instead of ..\

### ISSUE THREAD

**Issue by canamcy** [rg3/youtube-dl#5171]
I think you just closed an issue related to this, but I couldn't find it.
my output template working on 2015.03.03.1:
..\yo0\M\yodl\vimeo\%(title)s-%(id)s.%(ext)s
Win 7, py 3.2

[vimeo] 46967707: Downloading webpage
[vimeo] 46967707: Extracting information
[vimeo] 46967707: Downloading webpage
[info] Available formats for 46967707:
format code  extension  resolution note
h264-sd      mp4        640x360
h264-hd      mp4        1280x720   (best)
[vimeo] 46967707: Downloading webpage
[vimeo] 46967707: Extracting information
[vimeo] 46967707: Downloading webpage
[debug] Invoking downloader on u'https://avvimeo-a.akamaihd.net/27876/117/111098
922.mp4?token2=1425928412_dcdf6a445cc49a8df1f3b1e0ad827328&aksessionid=2768c0c46
3d876cb'
[download] Destination: .#\yo0\M\yodl\vimeo\110_Years_of_Triumph_Motorcycles-469
67707.mp4
[download]   0.3% of 70.75MiB at 21.80KiB/s ETA 55:11

**Comment by dstftw** [comment]
Thanks for the report, this will be fixed in the next version.

**Comment by dstftw** [comment]
Fixed in youtube-dl 2015.03.15. See [our FAQ](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) on how to update.
