### ISSUE TITLE
New site support request

### ISSUE THREAD

**Issue by szunyi** [rg3/youtube-dl#5172]
Hello,

I like this program!

Please support the following sites too; flashx.tv - streamin.to

Non-adult samples: http://www.flashx.tv/e1ojx8ly5d08.html - http://streamin.to/avrajusgufp5

Thanks!
bye

**Comment by yan12125** [comment]
The two sites contains lots of copyright-violation videos (see [1][2]), so [youtube-dl cannot support it](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
[1] https://www.google.com/transparencyreport/removals/copyright/domains/flashx.tv/
[2] https://www.google.com/transparencyreport/removals/copyright/domains/streamin.to/
