### ISSUE TITLE
Post-processing redownloads and different options

### ISSUE THREAD

**Issue by trtt** [rg3/youtube-dl#5173]
1. When --no-post-overwrites option is set (of course with --extract-audio), the video/audio source is still downloaded when there is already an extracted audio file (its extension could be guessed by --audio-format). That would make sense only if --keep-video option is set.
2. When there is --no-post-overwrites, source file is not deleted for some reason (independently of --keep-video).

Try:

``` sh
youtube-dl --no-post-overwrites --extract-audio --audio-format mp3 URL
#2 files are created (mp3 and source), 1 mp3 expected - demonstrates second problem
rm SOURCE-FILE
youtube-dl --no-post-overwrites --extract-audio --audio-format mp3 URL
# source file is redownloaded (problem 1) and not deleted again
```

Also, is -w option actually doing anything?

**Comment by hickford** [comment]
I downloaded half a playlist of 100 videos with `--extract-audio` before computer restarted. Is there anyway I can download the rest of the playlist without redownloading those I already have?

**Comment by dessalines** [comment]
I wish this were fixed. I'm downloading a channel that has 100s of audio files, and it doesn't know to not redownload it.

**Comment by dstftw** [comment]
`--download-archive`.
