### ISSUE TITLE
TeamCoco.com videos returning 404s and other errors

### ISSUE THREAD

**Issue by Fironet** [rg3/youtube-dl#5179]
Experiencing errors when downloading videos from TeamCoco.com. [Video 1](http://teamcoco.com/video/full-episode-weds-3-4-conan-in-cuba) and [video 2](http://teamcoco.com/video/clueless-gamer-assassins-creed-unity) I tested with, amongst others. Not sure if the issue is youtube-dl or something my end.

Full log of video 1:

    [debug] System config: []
    [debug] User config: ['-o', 'M:\\Videos\\%(title)s.%(ext)s', '--restrict-filenames', '--console-title']
    [debug] Command-line args: ['http://teamcoco.com/video/full-episode-weds-3-4-conan-in-cuba', '--verbose']
    [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
    [debug] youtube-dl version 2015.03.03.1
    [debug] Python version 2.7.8 - Windows-8-6.2.9200
    [debug] exe versions: ffmpeg N-66742-gf6777ce, ffprobe N-56999-g83fc6c8
    [debug] Proxy map: {}
    [Teamcoco] full-episode-weds-3-4-conan-in-cuba: Downloading webpage
    [Teamcoco] 88035: Downloading embed page
    ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https:
    //yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
     with the --verbose flag and include its complete output.
      File "youtube_dl\extractor\common.pyo", line 314, in _request_webpage
      File "youtube_dl\YoutubeDL.pyo", line 1674, in urlopen
      File "urllib2.pyo", line 410, in open
      File "urllib2.pyo", line 523, in http_response
      File "urllib2.pyo", line 448, in error
      File "urllib2.pyo", line 382, in _call_chain
    File "urllib2.pyo", line 531, in http_error_default

And the second:

    [debug] System config: []
    [debug] User config: ['-o', 'M:\\Videos\\%(title)s.%(ext)s', '--restrict-filenames', '--console-title']
    [debug] Command-line args: ['http://teamcoco.com/video/clueless-gamer-assassins-creed-unity', '--verbose']
    [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
    [debug] youtube-dl version 2015.03.03.1
    [debug] Python version 2.7.8 - Windows-8-6.2.9200
    [debug] exe versions: ffmpeg N-66742-gf6777ce, ffprobe N-56999-g83fc6c8, rtmpdump 2.4
    [debug] Proxy map: {}
    [Teamcoco] clueless-gamer-assassins-creed-unity: Downloading webpage
    [Teamcoco] 86049: Downloading embed page
    Traceback (most recent call last):
      File "__main__.py", line 19, in <module>
      File "youtube_dl\__init__.pyo", line 403, in main
      File "youtube_dl\__init__.pyo", line 393, in _real_main
      File "youtube_dl\YoutubeDL.pyo", line 1447, in download
      File "youtube_dl\YoutubeDL.pyo", line 648, in extract_info
      File "youtube_dl\extractor\common.pyo", line 275, in extract
      File "youtube_dl\extractor\teamcoco.pyo", line 63, in _real_extract
    TypeError: 'long' object has no attribute '__getitem__'

**Comment by naglis** [comment]
@Fironet, thanks for the report, however, in the future, please open [separate issues](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md#does-the-issue-involve-one-problem-and-one-problem-only) for seemingly different problems.

The first issue is due to the fact that we use embed pages to extract information, and the video in question (88035) can no [longer be embedded](http://teamcoco.com/embed/v/88035).

As for the second issue, I believe it has already been fixed, please upgrade to the latest version (see [our FAQ](https://yt-dl.org/update), if you need help updating).

**Comment by Fironet** [comment]
I wasn't sure if they were related tbh, and seeing 1000+ other issues didn't want to split them considering it was the same domain, but will do from now on.

Thanks, updating to the very latest version fixed the second video. It's a pity the first can't be downloaded. I'll keep the embedding limitation in mind next time it returns a 404.

**Comment by jaimeMF** [comment]
Can you play the video on the browser? It doesn't work for me with Firefox or Chrome.

**Comment by Fironet** [comment]
Not here on Chrome. I'm thinking it may be a regional restriction. although with some sites (such as CC.com) youtube-dl grabs it just fine.

**Comment by jaimeMF** [comment]
If it's only available on the USA, we'll need someone to test if it can be played and downloaded from there.

**Comment by kickerofelves** [comment]
It plays for me in browser. Get the following error:
```
[debug] System config: []
[debug] User config: ['-wit', '--write-srt', '--sub-lang', 'en', '--restrict-filenames', '-f', '18/43/34/h264-sd/flv/mp4-sd/mp4/rtmp-750/worst/best']
[debug] Command-line args: ['--verbose', 'http://teamcoco.com/video/full-episode-weds-3-4-conan-in-cuba']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.09
[debug] Python version 2.7.5+ - Linux-3.10-3-amd64-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 1.2.4, avprobe 1.2.4, ffmpeg 1.2.4, ffprobe 1.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Teamcoco] full-episode-weds-3-4-conan-in-cuba: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/damack/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/home/damack/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/home/damack/bin/youtube-dl/youtube_dl/extractor/teamcoco.py", line 50, in _real_extract
    self._VIDEO_ID_REGEXES, webpage, 'video id')
  File "/home/damack/bin/youtube-dl/youtube_dl/extractor/common.py", line 557, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/damack/bin/youtube-dl/youtube_dl/extractor/common.py", line 547, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

```

**Comment by yan12125** [comment]
The first video is gone, and I've fixed Teamcoco for downloading the second video mentioned by @Fironet without errors.
