### ISSUE TITLE
output template doesn't work on Win32

### ISSUE THREAD

**Issue by swapjim** [rg3/youtube-dl#5184]
On Linux, I'll do this:

    youtube-dl https://www.youtube.com/watch?v=BaW_jenozKc -i -w --restrict-filenames -o "%(upload_date)s-%(id)s-%(title)s.%(ext)s"

And I'll get a file that's named:

    20121002-BaW_jenozKc-youtube-dl_test_video.mp4

But on Win32, the same command gives me a file named:

    (id)s-(ext)s

What am I doing wrong?

**Comment by phihag** [comment]
As mentioned in [our issue reporting guideline](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md), please post the entire output you get when you add `-v`.

It works fine for me under Windows:

![windows-percent](https://cloud.githubusercontent.com/assets/779568/6617494/80c54bec-c8b9-11e4-8ce1-1f020249a7f2.png)

Are you by any chance using a batch script? If so, you may need to [escape percent signs](http://support.microsoft.com/kb/75634).

**Comment by swapjim** [comment]
> As mentioned in our issue reporting guideline, please post the entire output you get when you add `-v`.

Oh man, I missed that! Sorry.

Yes, I was invoking youtube-dl from a batch script and the percent characters needed escaping by using double percent characters. This one works:

    youtube-dl -v https://www.youtube.com/watch?v=BaW_jenozKc -i -w --restrict-filenames -o "%%(upload_date)s-%%(id)s-%%(title)s.%%(ext)s"

Thanks!
