### ISSUE TITLE
Pad %(playlist_index)s with zeroes 2

### ISSUE THREAD

**Issue by Romain-Revel** [rg3/youtube-dl#5185]
I am reopening this issue because not fixed entirely:
https://github.com/rg3/youtube-dl/issues/4157

(Tested with version 2015.03.03.1)

Here is a context where a padding would be useful:
I want to download this playlist https://www.youtube.com/playlist?list=PLE30F9d9cZayucP7UqdO37kjo3gtf989s
composed of 121 vidéos at the moment. So I start downloading it with a filename containing %(playlist_index)s. So this program creates the files 001, 002 ... Then there is an error, or the time is too long so I have to stop the download and restart it later with --playlist-start NUMBER. But if I use --playlist-start 22 or more, then there are less than 99 épisodes to download, so the %(playlist_index)s is written on 2 digits.
The first problem is that there is no coherence between the name of the first episodes and the last ones.
The second problem is that as I stopped the first download, it most probably stopped in the middle of the download of one episode, so when it restarts it doesn't find the .part file and starts the download of the current episode from the beginning.

It might be useful to be able to give the format in the --playlist-start in the following way:
--playlist-start 1 => file 1, 2 ... 10 ... 222 ... 99999
--playlist-start 01 => file 01, 02 ... 10 ... 222 ... 99999
--playlist-start 001 => file 001, 002 ... 010 ... 222 ... 99999

**Comment by yan12125** [comment]
FYI, not related to this issue: 2015.03.09 is out

**Comment by Romain-Revel** [comment]
I've just tested with version 2015.03.09, and there is still the same problem.

Try the 2 following commands (provided there are still 121 vidéos in the palylist and not any new one):
youtube-dl --get-filename --playlist-start 22 -o "%(playlist)s - %(playlist_index)s - %(title)s.%(ext)s" https://www.youtube.com/playlist?list=PLE30F9d9cZayucP7UqdO37kjo3gtf989s
youtube-dl --get-filename --playlist-start 23 -o "%(playlist)s - %(playlist_index)s - %(title)s.%(ext)s" https://www.youtube.com/playlist?list=PLE30F9d9cZayucP7UqdO37kjo3gtf989s

**Comment by jaimeMF** [comment]
Instead of deciding automatically how many zeros to use, we could just allow in the output template `%(playlist_index)04d`, which would produce `000x`.

**Comment by caddor** [comment]
download the source and open file "youtube_dl\YoutubeDL.py" 
find function             def prepare_filename(self, info_dict)
find line                    template_dict['playlist_index'] = '%0*d' % (len(str(template_dict['n_entries'])), template_dict['playlist_index'])

add code                  template_dict['playlist_index'] = template_dict['playlist_index'].zfill(2) after the line 
and the result filename will be 01xxx,02xxx,03xxx,you can change the zfill parameter what you want

**Comment by Moredread** [comment]
I think the approach by @jaimeMF would be better than mine in #9929.

The string formatting in python 3 doesn't support it directly . Do I see it correctly, that currently -o directly specifies the format string used, without modification? I guess we'd have to parse it ourselves, or does someone have an idea how that can be done in a better way?

**Comment by jxu** [comment]
I still have this issue in version 2020.02.16
