### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last):

### ISSUE THREAD

**Issue by melemello** [rg3/youtube-dl#5187]
23:Desktop Helios$ youtube-dl --format=bestvideo+bestaudio https://www.youtube.com/watch?v=NdQB7srnb1o
[youtube] Setting language
[youtube] Confirming age
[youtube] NdQB7srnb1o: Downloading webpage
[youtube] NdQB7srnb1o: Downloading video info webpage
[youtube] NdQB7srnb1o: Extracting video information
[youtube] NdQB7srnb1o: Encrypted signatures detected.
[youtube] NdQB7srnb1o: Downloading js player vflTTvO9k
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 527, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 441, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 502, in _parse_sig_js
    'Initial JS player signature function name')
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 399, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by jaimeMF** [comment]
It works for me with the last version, I guess you are using an old one, please [read our FAQ](https://yt-dl.org/update) if you have problems updating.

If you can reproduce the error with the last version please [post the full output](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) you get when running `youtube-dl --verbose 'https://www.youtube.com/watch?v=NdQB7srnb1o'`.

**Comment by melemello** [comment]
Cool, I'll give it a look, thought I had the latest, but guess not!

Thanks for the quick reply :)
Jon Fox
Managing Partner - CCO

m. 415.310.7670 | Skype - melemello | fox@heliosinteractive.com<mailto:fox@heliosinteractive.com>

Helios Interactive
301 8th St. Suite 250 | San Francisco, CA 94103
o. 415 558-0511 | f. 415.520.6900
www.heliosinteractive.com<http://www.heliosinteractive.com/>
