### ISSUE TITLE
Add support for Kanal 5 Play

### ISSUE THREAD

**Issue by oniichaNj** [rg3/youtube-dl#5188]
Hello,
Love this software and I'm using it for all my streaming / viewing needs as a method to avoid the silly TV license laws here in Sweden.

Anyways, I noticed you work fine with SVT Play and SVT Flow! Glorious! However, I would love it even more if you supported http://www.kanal5play.se. A website containing the video looks like this: 
http://www.kanal5play.se/#!/play/program/3060212363/video/3270012277

Thanks!

**Comment by dstftw** [comment]
Kanal 5/9/11 Play will be all supported in the next version. Thanks for the report.

**Comment by dstftw** [comment]
Support for Kanal 5/9/11 Play has been added in youtube-dl 2015.03.15. See [our FAQ](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) on how to update.
