### ISSUE TITLE
Crunchyroll subs

### ISSUE THREAD

**Issue by theredbaron1834** [rg3/youtube-dl#5191]
There is currently an issue where it can't see all the subtitles on crunchyroll. By this I mean that passing 
--write-sub --sub-lang en does not work. It will fail with:

>WARNING: en subtitles not available for XXXXXX

If I just pass --write-subs it will see some subs, normally just 1 at a time, though not always the same one. However, if I pass --all-subs it will get all possible subs, including the en subs I wanted, so there is at least a workaround.

**Comment by jaimeMF** [comment]
[Post the **full output**](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) you get when running `youtube-dl --verbose CRUNCHYROLL_URL_HERE OTHER_OPTIONS_HERE`,  otherwise we can't debug the problem.

**Comment by robin007bond** [comment]
Does it work when you use:

```
youtube-dl --sub-lang enUS [link_to_crunchyroll_vid] 
```

Without the square brackets of course. 

It works for me.

**Comment by theredbaron1834** [comment]
Yeah, it is because I used en. Dangit all. enUS works for me.

**Comment by jaimeMF** [comment]
I'm closing the issue then.

**Comment by robin007bond** [comment]
@theredbaron1834 
You can try --list-subs the next time for being sure that you have the right country code.
