### ISSUE TITLE
Choosing output file name in Python API

### ISSUE THREAD

**Issue by Zulko** [rg3/youtube-dl#5192]
Hi there, I am trying to download a video using the python API:

    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download(['http://www.youtube.com/watch?v=BaW_jenozKc'])

I can't figure what to put in the options to be able to set the output filename. Am I missing something obvious ? Thanks in advance.

**Comment by phihag** [comment]
Use the [`outtmpl` parameter](https://github.com/rg3/youtube-dl/blob/054b99a33079dcc4755e46aaf588424b4bb12020/youtube_dl/YoutubeDL.py#L139):

```
import youtube_dl
ydl_opts = {
    'outtmpl': '/tmp/foo_%(title)s-%(id)s.%(ext)s'
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['http://www.youtube.com/watch?v=BaW_jenozKc'])
```

**Comment by Zulko** [comment]
Thanks, but that doesn't work for me. To be more precise: at the command line i can write

    youtube-dl Nh11A41klL4 pigs.mp4

In the Python version I did not manage to force `pigs.mp4` as an outputname . If my name is not a proper template like `foo_%(title)s-%(id)s.%(ext)s` I get an assertion error. Any idea ? Thanks for your time.

**Comment by phihag** [comment]
`youtube-dl Nh11A41klL4 pigs.mp4` will try to download `pigs.mp4`:
```
$ youtube-dl Nh11A41klL4 pigs.mp4
[youtube] Nh11A41klL4: Downloading webpage
[youtube] Nh11A41klL4: Extracting video information
[youtube] Nh11A41klL4: Downloading DASH manifest
[download] Destination: Looney Tunes - Pigs in a Polka 1943-Nh11A41klL4.mp4
[download] 100% of 36.02MiB in 00:04
ERROR: u'pigs.mp4' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:pigs.mp4" ) to search YouTube
```
Please do post the error. Without it, we cannot help you.

**Comment by phihag** [comment]
One more note: If you are still using Python 2.x, you must make sure to pass in unicode and not byte objects. The simplest way to do this is to add `from __future__ import unicode_literals` to the top of your file.

**Comment by Zulko** [comment]
Sorry for that, I meant

    youtube-dl Nh11A41klL4 -o pigs.mp4

This command works and downloads the video as `pig.mp4`. Then, when I try the Python API version with this code:

    import youtube_dl
    def download_webfile(url, filename=None, **ydl_opts):
        if filename is not None:
            ydl_opts["outtmpl"]= filename
        with youtube_dl.YoutubeDL(ydl_opts) as ydl:
            ydl.download([url])
        
    # This will work and import the video under its youtube name
    #download_webfile("Nh11A41klL4")
    
    # When I try to specify a filename using "outtmpl" it crashes with Assertion Error
    download_webfile("Nh11A41klL4", "pigs.mp4")

I get [this error](https://gist.github.com/Zulko/adc592cc39d4e30aa210). Importing unicode_literals did not solve the problem.

**Comment by phihag** [comment]
Can you post the error you get when you add the `from __future__ import unicode_literals` line?

**Comment by Zulko** [comment]
Wait, it works ! My mistake with `unicode_literal` was that I imported it in the file where my function `download_webfile` is defined, while I should have imported it in the file where I call `download_webfile("Nh11A41klL4", "pigs.mp4")` (dumb me).

Also, in python2 simply writing `ydl_opts["outtmpl"]= unicode(filename)` seems to solve the problem.

I believe it's solved. Thanks for your time !

**Comment by BiTinerary** [comment]
`ydl_opts = {'outtmpl' : unicode(customName)}
	with youtube_dl.YoutubeDL(ydl_opts) as ydl:
		ydl.download([URLofVideo])`

In terms of renaming the downloaded video, this also worked for me.
