### ISSUE TITLE
Configuring youtube-dl to use Python 3.4 instead of 2.7

### ISSUE THREAD

**Issue by AmperAndSand** [rg3/youtube-dl#5193]
I have both Python 3.4 and Python 2.7 installed (both are the 64-bit versions on Windows 7). I've already set the `PY_PYTHON` environment variable to `3` (i.e. py.exe should run Python 3 by default, unless specified to run Python 2).`py.exe --version` gives an output of `Python 3.4.3`.

However, when I run youtube-dl, I get a `[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1` message. The reason I would like to use Python 3 is to get around [the bug where output filenames have non-ASCII, Unicode characters stripped](https://github.com/rg3/youtube-dl/issues/5182), which happens in Python 2.

**Comment by jaimeMF** [comment]
I guess that you are using the youtube-dl.exe version, that file is built with py2exe and includes its own copy of the python 2.7 interpreter and as far as I know there's no easy way to make it use python 3. If you have a normal python 3.4 installation you can just run `pip install -U youtube_dl`.

**Comment by AmperAndSand** [comment]
@jaimeMF That worked. Thank you.

**Comment by reggna** [comment]
Or, if you're still using Ubuntu 14.4 where Python 2 is still dominant, you can run this:

`pip3 install -U youtube_dl`
`python3 \`which youtube-dl\``

**Comment by lorenaceballos** [comment]
orena@lorena-To-be-filled-by-O-E-M:~$ pip3 install --upgrade youtube-dl
Collecting youtube-dl
  Downloading https://files.pythonhosted.org/packages/ad/1f/ae3e500935979bec629bab80be8b6fea00f7d5e8cb29564cf0f9c5afe975/youtube_dl-2019.4.30-py2.py3-none-any.whl (1.8MB)
     |████████████████████████████████| 1.8MB 1.1MB/s 
Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2018.3.14
ERROR: Cannot uninstall 'youtube-dl'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

 pip3 install --upgrade youtube-dl

**Comment by gamersalpha** [comment]
Hello not working :'(
