### ISSUE TITLE
the size file increase 150% if i chose  a name for my file (-o name.mp3 )

### ISSUE THREAD

**Issue by badershs** [rg3/youtube-dl#5197]
hi 
i have problem when i chose the name of the output for my youtube video .
the problem is ,if i convert youtube video to mp3  (my mp3 file will be 10 for example )
but when i use ( -o name.mp3 )  in the command the size of my same file  will up to 23 mega 
this is big problem for me now 
please any one can help me to fix this issue ?? ?

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by badershs** [comment]
this is the first one without -o [name]
*********************************************

[youtube] bWPMSSsVdPk: Downloading webpage
[youtube] bWPMSSsVdPk: Extracting video information
[youtube] bWPMSSsVdPk: Downloading DASH manifest
[debug] Invoking downloader on 'https://r8---sn-5hn7snee.googlevideo.com/videoplayback?id=6d63cc492b1574f9&itag=141&source=youtube&requiressl=yes&pl=24&ms=au&mm=31&mv=m&ratebypass=yes&mime=audio/mp4&gir=yes&clen=23477014&lmt=1394274621001298&dur=736.351&upn=xvmmndaKj1I&signature=504BDADBC6069A2E3F71471C46B58557C01996BC.24E2D4C1727DA0FDD4C02510E5F036179881A38C&key=dg_yt0&mt=1426277852&fexp=902543,907263,924648,927622,934052,934962,9406665,9406895,9407103,9407882,943917,948124,948307,951511,951703,952302,952612,952901,955301,957201,959701&sver=3&ip=188.166.1.215&ipbits=0&expire=1426299542&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,ms,mm,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Learn HTML in 12 Minutes-bWPMSSsVdPk.m4a

[download]   0.0% of 22.39MiB at 825.00KiB/s ETA 00:28
[download]   0.0% of 22.39MiB at  1.88MiB/s ETA 00:11
[download]   0.0% of 22.39MiB at  3.57MiB/s ETA 00:06
[download]   0.1% of 22.39MiB at  6.42MiB/s ETA 00:03
[download]   0.1% of 22.39MiB at 11.33MiB/s ETA 00:02
[download]   0.3% of 22.39MiB at 18.68MiB/s ETA 00:01
[download]   0.6% of 22.39MiB at 30.12MiB/s ETA 00:00
[download]   1.1% of 22.39MiB at 45.80MiB/s ETA 00:00
[download]   2.2% of 22.39MiB at 51.88MiB/s ETA 00:00
[download]   4.5% of 22.39MiB at 64.64MiB/s ETA 00:00
[download]   8.9% of 22.39MiB at 52.08MiB/s ETA 00:00
[download]  17.9% of 22.39MiB at 47.11MiB/s ETA 00:00
[download]  35.7% of 22.39MiB at 47.44MiB/s ETA 00:00
[download]  53.6% of 22.39MiB at 49.46MiB/s ETA 00:00
[download]  71.5% of 22.39MiB at 53.51MiB/s ETA 00:00
[download]  89.3% of 22.39MiB at 58.40MiB/s ETA 00:00
[download] 100.0% of 22.39MiB at 61.58MiB/s ETA 00:00
[download] 100% of 22.39MiB in 00:00
[ffmpeg] Correcting container in "Learn HTML in 12 Minutes-bWPMSSsVdPk.m4a"
[debug] ffmpeg command line: avconv -y -i 'Learn HTML in 12 Minutes-bWPMSSsVdPk.m4a' -c copy -f mp4 'Learn HTML in 12 Minutes-bWPMSSsVdPk.temp.m4a'
[debug] avconv command line: avprobe -show_streams 'Learn HTML in 12 Minutes-bWPMSSsVdPk.m4a'
[avconv] Destination: Learn HTML in 12 Minutes-bWPMSSsVdPk.mp3
[debug] ffmpeg command line: avconv -y -i 'Learn HTML in 12 Minutes-bWPMSSsVdPk.m4a' -vn -acodec libmp3lame -q:a 5 'Learn HTML in 12 Minutes-bWPMSSsVdPk.mp3'
Deleting original file Learn HTML in 12 Minutes-bWPMSSsVdPk.m4a (pass -k to keep)
**************************************************************************************************************************************************************************************************************************************************************
this is with -o [nama]
------------------------
[youtube] bWPMSSsVdPk: Downloading webpage
[youtube] bWPMSSsVdPk: Extracting video information
[youtube] bWPMSSsVdPk: Downloading DASH manifest
[debug] Invoking downloader on 'https://r8---sn-5hneznee.googlevideo.com/videoplayback?id=6d63cc492b1574f9&itag=141&source=youtube&requiressl=yes&mm=31&pl=24&mv=m&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=23477014&lmt=1394274621001298&dur=736.351&signature=807AB50949000D90AEE767D1436CABCF35DFDE69.8E36ECF97BE6812A0BE17E804880CD61D36E8F3F&mt=1426278121&sver=3&upn=roZ41r_Ouvw&fexp=907263,912333,913444,919514,927622,929250,934952,934953,934954,936122,9405451,9406627,9406664,9407103,9407801,943917,945098,948124,948703,951511,951703,952302,952612,952901,955301,957201,959701&key=dg_yt0&ip=188.166.1.215&ipbits=0&expire=1426299750&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,pl,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: myfile.mp3

[download]   0.0% of 22.39MiB at Unknown speed ETA Unknown ETA
[download]   0.0% of 22.39MiB at  2.59MiB/s ETA 00:08
[download]   0.0% of 22.39MiB at  3.88MiB/s ETA 00:05
[download]   0.1% of 22.39MiB at  6.28MiB/s ETA 00:03
[download]   0.1% of 22.39MiB at 10.43MiB/s ETA 00:02
[download]   0.3% of 22.39MiB at 17.56MiB/s ETA 00:01
[download]   0.6% of 22.39MiB at 27.69MiB/s ETA 00:00
[download]   1.1% of 22.39MiB at 39.10MiB/s ETA 00:00
[download]   2.2% of 22.39MiB at 45.23MiB/s ETA 00:00
[download]   4.5% of 22.39MiB at 48.40MiB/s ETA 00:00
[download]   8.9% of 22.39MiB at 34.55MiB/s ETA 00:00
[download]  17.9% of 22.39MiB at 35.96MiB/s ETA 00:00
[download]  35.7% of 22.39MiB at 44.29MiB/s ETA 00:00
[download]  53.6% of 22.39MiB at 45.47MiB/s ETA 00:00
[download]  71.5% of 22.39MiB at 43.48MiB/s ETA 00:00
[download]  89.3% of 22.39MiB at 46.48MiB/s ETA 00:00
[download] 100.0% of 22.39MiB at 49.24MiB/s ETA 00:00
[download] 100% of 22.39MiB in 00:00
[ffmpeg] Correcting container in "myfile.mp3"
[debug] ffmpeg command line: avconv -y -i myfile.mp3 -c copy -f mp4 myfile.temp.mp3
[debug] avconv command line: avprobe -show_streams myfile.mp3
[youtube] Post-process file myfile.mp3 exists, skipping

**Comment by dstftw** [comment]
This doesn't look like full verbose output. Version infos, cmd arguments, etc. are missing.

**Comment by badershs** [comment]
youtube-dl  --extract-audio --audio-format mp3 --verbose   http://www.youtube.com/watch?v=QWQZpVl3T-0
this is my command what i need to get full verbose output ?
can you add it please ?

**Comment by dstftw** [comment]
This is how **full** verbose output should look like:
```
> youtube-dl --extract-audio --audio-format mp3 --verbose http://www.youtube.com/watch?v=QWQZpVl3T-0
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--extract-audio', '--audio-format', 'mp3', '--verbose', 'http://www.youtube.com/watch?v=QWQZpVl3T-0']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.03.09
[debug] Git HEAD: 7be5a62
[debug] Python version 2.7.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-68756-g627f565, ffprobe N-68694-g7c210c4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] QWQZpVl3T-0: Downloading webpage
[youtube] QWQZpVl3T-0: Extracting video information
[youtube] QWQZpVl3T-0: Downloading DASH manifest
[debug] Invoking downloader on 'https://r4---sn-ug5onuxaxjvh-v8ce.googlevideo.com/videoplayback?id=416419a559774fed&itag=141&source=youtube&requiressl=yes&mv=m&mm=31&pl=22&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=23485894&lmt=1395447148646108&dur=736.629&signature=7820A61C6D49146AE06C7BB40278C354F1486CC5.2D300524111F1BC0189127BC291C0B81650F5B5E&sver=3&fexp=903945,905661,907263,912150,927622,929252,937009,9406985,9407103,943917,948124,951511,951703,952302,952612,952901,955301,957201,959701&mt=1426281716&key=dg_yt0&upn=-QoVDQhBevU&ip=<PRIVATE>&ipbits=0&expire=1426303357&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,mm,pl,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: java lesson 15-QWQZpVl3T-0.m4a
[download] 100% of 22.40MiB in 00:08
[ffmpeg] Correcting container in "java lesson 15-QWQZpVl3T-0.m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'java lesson 15-QWQZpVl3T-0.m4a' -c copy -f mp4 'java lesson 15-QWQZpVl3T-0.temp.m4a'
[debug] ffmpeg command line: ffprobe -show_streams 'java lesson 15-QWQZpVl3T-0.m4a'
[ffmpeg] Destination: java lesson 15-QWQZpVl3T-0.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'java lesson 15-QWQZpVl3T-0.m4a' -vn -acodec libmp3lame -q:a 5 'java lesson 15-QWQZpVl3T-0.mp3'
Deleting original file java lesson 15-QWQZpVl3T-0.m4a (pass -k to keep)
```
And here is the resulting mp3 file:
```
22.03.2014  06:12         7 452 365 java lesson 15-QWQZpVl3T-0.mp3
```
7.1 MiB mp3 vs 22.4 MiB of original file. So, what's the problem?

**Comment by dstftw** [comment]
When specifying output template with `-o` you specify template for downloadable file, that turns out to be m4a and not mp3. Afterwards, m4a is converted to mp3 using avconv/ffmpeg and written in the same destination. You can work this around by providing output template with extension of the downloaded file `-o name.%(ext)s`.

**Comment by badershs** [comment]
thank you for your help :+1: 
-bash: syntax error near unexpected token `('
when i use your comment i get this error

**Comment by dstftw** [comment]
Put in quotes `"name.%(ext)s"`.

**Comment by badershs** [comment]
thank you soooo much :) it's working now
