### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by whatUwant** [rg3/youtube-dl#520]
Is it possible to force youtube-dl to work only via IPv6? 
It's impossible to access Youtube via IPv4 in China without a proxy or VPN service while accessing via IPv6 has not yet been banned.
I don't know if youtube-dl chose to access youtube via IPv6 by chance. A few days ago, youtube-dl seemed to be working fine with IPv6. But recently all downloads have failed. The error message is "urlopen error [Errno 104] Connection reset by peer". I'm pretty sure there is nothing wrong with my IPv6 connectivity. The only explanation I can come up with is that youtube-dl is trying to access youtube via IPv4 right now.

**Comment by phihag** [comment]
`-4` and `-6` switches are present in youtube-dl 2015.01.10.1 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by kaimi** [comment]
Nice job, thanks!
