### ISSUE TITLE
Tumblr OpenGraph warning

### ISSUE THREAD

**Issue by gimlids** [rg3/youtube-dl#5202]
$ youtube-dl "http://sipbarrio.tumblr.com/post/113600056428"
[Tumblr] 113600056428: Downloading webpage
[Tumblr] 113600056428: Downloading webpage
WARNING: unable to extract OpenGraph description; please report this issue on http://yt-dl.org/bug
[download] Destination: sipbarrio-113600056428.mp4
[download] 100% of 2.11MiB in 00:01

**Comment by yan12125** [comment]
Thanks for the report. In the next version of youtube-dl, there will not be warnings for videos without descriptions.
