### ISSUE TITLE
Filter videos based on duration

### ISSUE THREAD

**Issue by revolter** [rg3/youtube-dl#5205]
Is there any way to only download videos less than 10 seconds from a youtube playlist? I can only find `--get-duration` that's just a simulation, but can't apply it as a filter.

**Comment by jaimeMF** [comment]
Use `--match-filter 'duration < 10'`.

**Comment by revolter** [comment]
Shouldn't `duration` appear in the help for `-o` in the documentation? That would prevent unnecessary issues like this one.
