### ISSUE TITLE
Add multiple link generation in a single command

### ISSUE THREAD

**Issue by TheGr33k** [rg3/youtube-dl#5209]
It would be nice for youtube-dl to to be able to generate multiple direct links for different quality of the same video

for e.g `youtube-dl -g -f 18 22 43  https://www.youtube.com/watch?v=NrXdauEv9HY`

would generate urls  for the different itags.Each url could be separated by a  special character in the output.

Advantages

No need to call youtube-dl multiple times for different qualities of the same video will save CPU and decrease the chance of getting `Too Many request` as the same page won't be requested from youtube multiple times.

**Comment by dstftw** [comment]
Just use `--dump-json` .

**Comment by TheGr33k** [comment]
It should works but a cleaner version would be better.There is a lot of info that is not needed

**Comment by dstftw** [comment]
All this info is extracted anyway, and it's unreasonable to make options to list any particular part of it. Moreover, suggested `-f` syntax is not consistent with format filters.

**Comment by TheGr33k** [comment]
I am fine with any other syntax you guys may come up with but here i am
interested only with the urls

What regex can be used to extract the specific infos

**Comment by jaimeMF** [comment]
If you are using a shell script, then you just need to use [jq](https://stedolan.github.io/jq/):
```
$ youtube-dl test:youtube -f 137,136 -j | jq -r '"\(.format_id): \(.url)"'
137: https://r9---sn-h5q7ener.googlevideo.com/videoplayback?<...>
136: https://r9---sn-h5q7ener.googlevideo.com/videoplayback?<...>
```

**Comment by TheGr33k** [comment]
I am using php :)

**Comment by jaimeMF** [comment]
I don't use php, but it seems to have json support: http://php.net/manual/en/ref.json.php.
Just note that with my approach each line of the output will contain a single json object, so you need to decode each line individually.
