### ISSUE TITLE
Add support for www.beatport.com

### ISSUE THREAD

**Issue by pricejn2** [rg3/youtube-dl#5219]
example url: https://www.beatport.com/flamingorecordingsbps/tracks/qpwhxukynk7r/burnin-up-original-mix

Thanks!

**Comment by yan12125** [comment]
@pricejn2 If I'm correct, you need to pay to BeatPort for downloading songs. I think it's not proper to support this site in youtube-dl. You can still download the 2-minute preview using the BeatPort Pro URL (thanks to #5189), for example, 
```Bash
youtube-dl "https://pro.beatport.com/track/burninup/6356124"
```

**Comment by TheRuedi** [comment]
@yan12125 You have to pay at pro.beatport.com, but beatport.com/listen is a streaming platform like soundcloud. It would be really great if you supported this site!
Example URL (: https://www.beatport.com/musicalfreedom/tracks/l2axnqcd6azu/secrets-feat-vassy-original-mix

**Comment by MaZZly** [comment]
Yes the "regular" beatport is just streaming and no payment required.. Also when playing you can easily see the mp4 (odd?) file in the network manager for saving of file..

**Comment by yan12125** [comment]
Both links now redirect to https://pro.beatport.com/. Closing.
