### ISSUE TITLE
Part of URL executed as command after download from zdf.de

### ISSUE THREAD

**Issue by pianoslum** [rg3/youtube-dl#5221]
After (successfully) downloading a video from zdf.de, a part of the url is executed as a command right in the console (kua... in the picture). I think this could be really dangerous, if an attacker somehow manages to slip somebody a forged URL.

**Comment by yan12125** [comment]
It's not youtube-dl's problem, but a shell trick. You need to enclose your URLs in double quotes or escape the special characters if they contain "?", "&", "=".

**Comment by pianoslum** [comment]
I am sorry for that - thank you!
