### ISSUE TITLE
unable to download on arte.tv +7

### ISSUE THREAD

**Issue by jp57** [rg3/youtube-dl#5224]
The downloading doesn't work for arte plus 7 

screen copy example:
jp@jp-HP-Compaq-6710b-RJ459AV ~ $ sudo youtube-dl -U
[sudo] password for jp: 
youtube-dl is up-to-date (2015.03.15)
jp@jp-HP-Compaq-6710b-RJ459AV ~ $ youtube-dl  http://www.arte.tv/guide/fr/053444-002/paysages-dici-et-dailleurs
[arte.tv:+7] 053444-002: Downloading webpage
[arte.tv:+7] 053444-002: Downloading JSON metadata
ERROR: unable to download video data: HTTP Error 404: Not Found

A great thank you for your software and your efforts for the community
Best regards from Paris (not in Texas)
jp

**Comment by jaimeMF** [comment]
Other formats work, for example `youtube-dl 'http://www.arte.tv/guide/fr/053444-002/paysages-dici-et-dailleurs' -f 'HTTP_MP4_EQ_1'` (you can get the available formats with `youtube-dl URL -F`). So maybe it's an internal error.

(For future error reports, please post the [full output you get when running `youtube-dl --verbose URL`](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs)

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
