### ISSUE TITLE
[mixcloud] minor error

### ISSUE THREAD

**Issue by thpublic** [rg3/youtube-dl#5231]
WARNING: unable to extract like count; please report this issue on http://yt-dl.org/bug

**Comment by jaimeMF** [comment]
You [haven't posted the required info](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs), it makes harder for us to debug the problem.

I think that commit fa8ce2690447fa06a10398efd5b6dfa96c2ed1b4 fixes the issue.

**Comment by mdaniel** [comment]
I pulled the latest master and it still reports this; here is the output from `-v`. The part in the bugs section about "is anyone going to need this" is highly subjective. _I_ don't need that info, but whenever a program prompts me to report a bug, I try to do so.

I tried this url from two separate networks, so it is unlikely to be a per-client issue.

```
Fetching origin
Already up-to-date.
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--output', u'%(title)s - %(id)s.%(ext)s', u'--restrict-filenames', u'--no-overwrites', u'--verbose', u'--all-subs', u'-f', u'0', u'https://www.mixcloud.com/wwwLiveSetsat/annie-nightingale-bbc-radio1-grum-quest-mix-18032015/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.03
[debug] Git HEAD: ff2be6e
[debug] Python version 2.7.9 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[mixcloud] wwwLiveSetsat-annie-nightingale-bbc-radio1-grum-quest-mix-18032015: Downloading webpage
[mixcloud] wwwLiveSetsat-annie-nightingale-bbc-radio1-grum-quest-mix-18032015: Checking URL 22/30 ...
WARNING: unable to extract like count; please report this issue on http://yt-dl.org/bug
[debug] Invoking downloader on u'https://stream22.mixcloud.com/c/originals/a/4/4/2/4974-7374-4a07-a6c0-b067122ab3c5.mp3'
```

That command line is the pretty generic one I use (i.e. is not specific to mixcloud); only the `-f` and the url are specific to this run.

Please let me know if there is anything else I can do to help.

**Comment by jaimeMF** [comment]
@mdaniel it will work again in the next version (or with the latest master if you want), thanks for the report. Feel free to open a new issue in the future, it's easier to track them.

> The part in the bugs section about "is anyone going to need this" is highly subjective

First of all, thanks for reading the BUGS section, we appreciate it. That line refers to feature requests, so that people only request features that they need, it doesn't apply to errors or regressions.
