### ISSUE TITLE
Please support digg.com/video/

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#5234]
I have the latest version of youtube-dl (I did "sudo youtube-dl -U".)

I ran this command in terminal:
youtube-dl http://digg.com/video/this-video-of-six-second-graders-being-treated-to-a-220-seven-course-tasting-menu-is-utterly-delightful

But it says that it's an unsupported URL.

**Comment by hub2git** [comment]
Hello, dstftw.
I checked out the "[generic] Add support for nytimes" link. I updated youtube-dl, but the latest version seems to have the same result (error in downloading).  Does this mean that no solution has been found yet?

Thank you.

**Comment by dstftw** [comment]
It's not yet released.
