### ISSUE TITLE
VideoMega.TV not working.

### ISSUE THREAD

**Issue by api984** [rg3/youtube-dl#5235]
I think they changed something again…. 

youtube-dl -v http://videomega.tv/?ref=CNHQJLWLA55ALWLJQHNC
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://videomega.tv/?ref=CNHQJLWLA55ALWLJQHNC']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.15
[debug] Python version 2.7.1 - Darwin-11.4.2-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[VideoMega] CNHQJLWLA55ALWLJQHNC: Downloading webpage
ERROR: Unable to extract escaped data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/videomega.py", line 42, in _real_extract
    escaped_data = re.findall(r'unescape\("([^"]+)"\)', webpage)[-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/videomega.py", line 44, in _real_extract
    raise ExtractorError('Unable to extract escaped data')
ExtractorError: Unable to extract escaped data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by naglis** [comment]
Yes, it indeed changed again. It should be fixed in the next release of youtube-dl. Thanks for the report!

**Comment by api984** [comment]
what are they changing i wonder… regex rewrite for redirects to real links?
