### ISSUE TITLE
Failed to download a NY Times video

### ISSUE THREAD

**Issue by cjfsyntropy** [rg3/youtube-dl#5238]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.nytimes.com/video/travel/100000003550828/36-hours-in-dubai.html']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.3 - Linux-3.14-0.bpo.1-686-pae-i686-with-debian-7.7
[debug] exe versions: avconv 0.8.16-6, avprobe 0.8.16-6, ffmpeg 0.8.16-6, ffprobe 0.8.16-6, rtmpdump 2.4
[debug] Proxy map: {}
[NYTimes] 36: Downloading video JSON
ERROR: An extractor error has occured. (caused by KeyError(u'headline',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/cjf/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/home/cjf/bin/youtube-dl/youtube_dl/extractor/nytimes.py", line 34, in _real_extract
    title = video_data['headline']
KeyError: u'headline'
Traceback (most recent call last):
  File "/home/cjf/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/home/cjf/bin/youtube-dl/youtube_dl/extractor/common.py", line 281, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'headline',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by naglis** [comment]
This issue should be fixed in the next release of youtube-dl. Thanks for the report.
