### ISSUE TITLE
Can't download some GDC vault videos

### ISSUE THREAD

**Issue by Farl** [rg3/youtube-dl#5243]
I have some 2014 videos that can't download properly.

http://gdcvault.com/play/1021693/Keynote-Monument-Valley-and-What (Member only)

I think maybe just the parsing problem.
Hope someone can fix in the future.
Thanks!

**Comment by dwiperdana** [comment]
Have you tried to enter a username and password using the options?
I think you will need a paid member access to download member only videos.

**Comment by yan12125** [comment]
@Farl Please post the full verbose log with ```--verbose``` option. This helps us precisely identify the problem. Your username and password will be replaced by 'PRIVATE' in the verbose log, so don't worry for leaking secrets.

**Comment by Farl** [comment]
Thank for your help
My password have some special character.
And some how I figure out how to fix it!
