### ISSUE TITLE
xvideos is not working

### ISSUE THREAD

**Issue by sebma** [rg3/youtube-dl#5244]
Hi,

XVideos is not working as you can see below : 

$ youtube-dl -v http://www.xvideos.com/video3678704/
[debug] System config: []
[debug] User config: ['--ignore-errors', '--continue', '-o', '%(title)s - %(resolution)s - %(id)s.%(ext)s', '-f', 'mp4', '--restrict-filenames', '--add-metadata', '--write-description', '--embed-subs', '--embed-thumbnail', '--exec', 'mp4tags -c "$(cat {}.description)" {} && rm -vf {}.description']
[debug] Command-line args: ['-v', 'http://www.xvideos.com/video3678704/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.8 - Linux-3.16.0-31-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6, ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
[debug] Proxy map: {}
[XVideos] 3678704: Downloading webpage
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 665, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 711, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1145, in process_video_result
    expected=True)
ExtractorError: requested format not available

$ echo $?
1

Can you look into it ?

Seb.

**Comment by dstftw** [comment]
You have explicitly set requested `format_id` in your youtube-dl user config as `mp4`. `format_id` is an extractor specific identifier and the extension of the video or a codec name. You can list available formats with `-F`. So, to get it working just remove explicit `format_id` from your user config.
