### ISSUE TITLE
Warning: unable to extract comment count

### ISSUE THREAD

**Issue by amsourav** [rg3/youtube-dl#5250]

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by dstftw** [comment]
Closing due to insufficient info. Feel free to open a new issue with [full `--verbose` log](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).
