### ISSUE TITLE
Support for www.safaribooksonline.com

### ISSUE THREAD

**Issue by zx8** [rg3/youtube-dl#5253]
Contrary to what the URL might suggest, Safari Books Online has plenty of video lessons as well - quite similar to Lynda.com support which is already implemented.

Sample URL - https://www.safaribooksonline.com/library/view/swift-fundamentals-livelessons/9780134049939/

**Comment by zx8** [comment]
Looks like there's a handy REST API we can hit to extract various bits of info we need, e.g. https://www.safaribooksonline.com/api/v1/book/9780134049939/chapter/part00.html

Safari use Brightcove to serve their videos which seems to have been already implemented in #832, so this might be a bit easier than I thought it'd be.

**Comment by zx8** [comment]
Right, it seems that downloading chapters one-by-one works out of the box using `GenericIE`, i.e.:

`youtube-dl -u USERNAME -p PASSWORD https://www.safaribooksonline.com/library/view/swift-fundamentals-livelessons/9780134049939/part00.html`

All we need to do is: given a base course URL, extract (or infer, as the example below attempts to) the list of chapters via the REST API and then use generic extractor to download them. Here's a quick mockup of how it might be done:

```python
class SafariCourseIE(InfoExtractor):
    IE_NAME = 'safari:course'
    IE_DESC = 'safaribooksonline.com online courses'

    _VALID_URL = r'https?://(?:www\.)?safaribooksonline\.com/library/view/(?P<course_path>[^/]+)/(?P<id>\d+)'

    def _real_extract(self, url):
        mobj = re.match(self._VALID_URL, url)
        course_path = mobj.group('course_path')
        course_id = mobj.group('id')

        page = self._download_webpage(
            'https://www.safaribooksonline.com/api/v1/book/%s/' % course_id,
            course_id, 'Downloading course JSON')
        course_json = json.loads(page)

        if 'Chapters' not in course_json:
            raise ExtractorError(
                'No chapters found for course %s' % course_id, expected=True)

        num_parts = len(course_json['chapters'])
        parts = ['%02d' % part for part in range(num_parts)]

        entries = [
            self.url_result(
                'https://www.safaribooksonline.com/library/view/%s/%d/part%s.html' % (course_path, course_id, part_id),
                'Safari')
            for part_id in parts]

        course_title = course_json['title']

        return self.playlist_result(entries, course_id, course_title)
```

**Comment by zx8** [comment]
Gave this a go myself - https://github.com/rg3/youtube-dl/pull/5262

Will continue this thread on the PR.

**Comment by gabrielcnr** [comment]
@zx8 is this still working for you? I think Safari changed their media server to Kaltura instead of Brightcove. Tried to workaround that but no luck.

**Comment by zx8** [comment]
@gabrielcnr It won't work anymore, no.

My subscription to Safari recently expired so I don't really have the motivation update the extractor, I'm afraid. I'm sure someone else will come along and pick it up eventually! :smile:

**Comment by diman82** [comment]
I have an active subscription to safari, how can I aid to provide a support for it?

**Comment by yan12125** [comment]
Seems safaribooksonline is already added. Open a new issue if something goes wrong.
