### ISSUE TITLE
Uploading videos to YouTube(trouble)

### ISSUE THREAD

**Issue by XxLuminousxX** [rg3/youtube-dl#5256]
OK so I know YouTube doesn't accept .veg formats so it says to convert it to .mp4 so I open vegas pro and render it as .mp4 then I save it and try to upload it It doesn't work. I guess this is because I saved it as .veg so what do I do I tried to save it as .mp4 but it gets stuck at 0 processing cause it doesn't recognize the file and every one says render it as .mp4 and it'll work and the file is rendered as .mp4.                         PLEASE HELP

**Comment by dstftw** [comment]
youtube-dl is a program to **download** videos from YouTube. Your issue seems to be unrelated.
If you have youtube-dl related problem, feel free to open a new issue with detailed explanations and [**full** verbose output](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).
