### ISSUE TITLE
Error: Unable to download webpage

### ISSUE THREAD

**Issue by computerfreak105** [rg3/youtube-dl#5258]
youtube-dl -f 140/m4a -o e:\yt/%(uploader)s/%(title)s_%(upload_date)s.%(ext)s -a yt.txt

[debug] Batch file urls: [u'https://www.youtube.com/channel/UCTFk3bDL6uLKceyRDGj
35RA', u'https://www.youtube.com/', u'https://www.youtube.com/channel/UCuE0AXfwA
_C0ziSRK_ZIdLw', u'https://www.youtube.com/channel/UCtqz3PLwc1rfLUyodPVfAdg', u'
https://www.youtube.com/channel/UCEaBsgoPKe5BYPxn6POufTw', u'https://www.youtube
.com/channel/UClEG_a8VOjlIHwLCMIRxPeg', u'https://www.youtube.com/channel/UChjpR
B6s5uMmE7uW4HiuVcA', u'https://www.youtube.com/channel/UCWpaLNyHzFmFPEoBwUPpq-g'
, u'https://www.youtube.com/channel/UC4eb3MzMyRPGVk1tKGnmYVA', u'https://www.you
tube.com/channel/UCgo9FBrLZu4RFhsUcMlpB8A', u'https://www.youtube.com/channel/UC
cv25IWbN6RdzppdX4MfbGw', u'https://www.youtube.com/channel/UCUD-1JBiV7zAL9RqjL_L
nYQ', u'https://www.youtube.com/channel/UClE9NhAjdiGqEaG2rDKhtKg', u'https://www
.youtube.com/channel/UCXgrSU5lCPe5HlpriQQV5UA', u'https://www.youtube.com/channe
l/UCZZe7k4sMBm5zHioryruYTw', u'https://www.youtube.com/channel/UCwapTgBqG-xNTa_W
csspAQA', u'https://www.youtube.com/channel/UC-hu6KgB5x7jCXkgaaZ6P9Q', u'https:/
/www.youtube.com/channel/UCzoHG5lHi1rSVrWKvP_wbdw', u'https://www.youtube.com/ch
annel/UCrktjZyOntFCloPanFg05dw', u'https://www.youtube.com/channel/UCHwdi14YVyp5
pUIFNjwnVrg', u'https://www.youtube.com/channel/UCRbDhfZ4m4SuuuDGVYrnaJA', u'htt
ps://www.youtube.com/channel/UC-GtgnYSx0q94EMIWNZUU-Q', u'https://www.youtube.co
m/channel/UCJSv0PSDDRb53AFyBK7NN0w', u'https://www.youtube.com/channel/UCY1chYi_
0OtgNx7AsaOXjxw', u'https://www.youtube.com/', u'https://www.youtube.com/channel
/UCa5xHw1w-2FF-UAx3uz9rkw']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:channel] UCTFk3bDL6uLKceyRDGj35RA: Downloading webpage
[download] Downloading playlist: UCTFk3bDL6uLKceyRDGj35RA
[youtube:channel] playlist UCTFk3bDL6uLKceyRDGj35RA: Downloading 14 videos
[download] Downloading video 1 of 14
[youtube] z4v6ZXcdY_Q: Downloading webpage
[youtube] z4v6ZXcdY_Q: Extracting video information
[youtube] z4v6ZXcdY_Q: Downloading DASH manifest
[debug] Invoking downloader on 'https://r4---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=cf8bfa65771d63f4&itag=140&source=youtube&requiressl=yes&mm=31&pl=
27&mv=u&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=15224121&lmt=1424223733
532023&dur=1262.933&upn=4QuI4YUU-04&fexp=900720,907263,912333,923360,929243,9298
21,934960,9407060,9407103,9408101,9408162,942311,948124,951511,951703,952302,952
612,952901,955301,957201,959701,961404&key=dg_yt0&mt=1427002416&signature=0B494A
24D6541A429032CC9F31787034A566A2F7.3500023197D1B59B590610EF949FAB89352E30D8&sver
=3&ip=178.195.176.197&ipbits=0&expire=1427024198&sparams=ip,ipbits,expire,id,ita
g,source,requiressl,mm,pl,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\Webcam video from February 18, 2015 01_20 AM (UTC)
_20150217.m4a has already been downloaded
[download] 100% of 14.52MiB
WARNING: z4v6ZXcdY_Q: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 2 of 14
[youtube] j-vFFVZNfc0: Downloading webpage
[youtube] j-vFFVZNfc0: Extracting video information
[youtube] j-vFFVZNfc0: Downloading DASH manifest
[debug] Invoking downloader on 'https://r7---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=8febc515564d7dcd&itag=140&source=youtube&requiressl=yes&mm=31&ms=
au&mv=u&pl=27&ratebypass=yes&mime=audio/mp4&gir=yes&clen=5453135&lmt=14242207861
22088&dur=339.637&upn=JhqdwObIs0s&sver=3&key=dg_yt0&fexp=900720,907263,912333,92
3360,929243,929821,934960,9407060,9407103,9408101,9408162,942311,948124,951511,9
51703,952302,952612,952901,955301,957201,959701,961404&mt=1427002416&signature=7
7C7C08D2DF83A4BA5A66A43AE76D8C6A8F71C6B.3B81ED9C044D3CB97C113D7D30034AD8D8CE915C
&ip=178.195.176.197&ipbits=0&expire=1427024199&sparams=ip,ipbits,expire,id,itag,
source,requiressl,mm,ms,mv,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\Copy of help the blind_20150217.m4a has already be
en downloaded
[download] 100% of 5.20MiB
WARNING: j-vFFVZNfc0: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 3 of 14
[youtube] aFWmC1TSXIE: Downloading webpage
[youtube] aFWmC1TSXIE: Extracting video information
[youtube] aFWmC1TSXIE: Downloading DASH manifest
[debug] Invoking downloader on 'https://r8---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=6855a60b54d25c81&itag=140&source=youtube&requiressl=yes&ms=au&mv=
u&pl=27&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=5453135&lmt=14242211117
82405&dur=339.637&signature=639027414CC4F8E6435E23A1AA36ACD68E04FBA4.12D5554C37B
55A7393761C6B902B7DA43285AC8F&key=dg_yt0&upn=YbDAcBmwhiY&mt=1427002416&fexp=9007
20,907263,912333,923360,929243,929821,934960,9407060,9407103,9408101,9408162,942
311,948124,951511,951703,952302,952612,952901,955301,957201,959701,961404&sver=3
&ip=178.195.176.197&ipbits=0&expire=1427024199&sparams=ip,ipbits,expire,id,itag,
source,requiressl,ms,mv,pl,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\help the blind_20150217.m4a has already been downl
oaded
[download] 100% of 5.20MiB
WARNING: aFWmC1TSXIE: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 4 of 14
[youtube] 89s2qQ-pPX4: Downloading webpage
[youtube] 89s2qQ-pPX4: Extracting video information
[youtube] 89s2qQ-pPX4: Downloading DASH manifest
[debug] Invoking downloader on 'https://r5---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=f3db36a90fa93d7e&itag=140&source=youtube&requiressl=yes&ms=au&mv=
u&pl=27&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=9977454&lmt=14234552602
45514&dur=827.674&mt=1427002416&sver=3&upn=ssNP42NYncM&key=dg_yt0&fexp=900720,90
7263,912333,923360,929243,929821,934960,9407060,9407103,9408101,9408162,942311,9
48124,951511,951703,952302,952612,952901,955301,957201,959701,961404&signature=6
AADF624A350810EFFAE267386460EAB10B7F9F4.30E32051F6689BDA5D54BAF56181A46100CF4F0F
&ip=178.195.176.197&ipbits=0&expire=1427024200&sparams=ip,ipbits,expire,id,itag,
source,requiressl,ms,mv,pl,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\Be your self_20150208.m4a has already been downloa
ded
[download] 100% of 9.52MiB
WARNING: 89s2qQ-pPX4: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 5 of 14
[youtube] XnTLKMDo4WI: Downloading webpage
[youtube] XnTLKMDo4WI: Extracting video information
[youtube] XnTLKMDo4WI: Downloading DASH manifest
[debug] Invoking downloader on 'https://r8---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=5e74cb28c0e8e162&itag=140&source=youtube&requiressl=yes&pl=27&ms=
au&mv=u&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=4346581&lmt=14234537970
91093&dur=360.536&sver=3&mt=1427002416&fexp=900720,907263,912333,923360,929243,9
29821,934960,9407060,9407103,9408101,9408162,942311,948124,951511,951703,952302,
952612,952901,955301,957201,959701,961404&upn=6BSdT_ks8TI&signature=82DA96A3995D
60C494EAF86AD02556D038913182.1785847A9B1189049C99156AAB5EFA1D4886AF8C&key=dg_yt0
&ip=178.195.176.197&ipbits=0&expire=1427024201&sparams=ip,ipbits,expire,id,itag,
source,requiressl,pl,ms,mv,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\Shower by Becky G_20150208.m4a has already been do
wnloaded
[download] 100% of 4.15MiB
WARNING: XnTLKMDo4WI: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 6 of 14
[youtube] RuJQxVgqoew: Downloading webpage
[youtube] RuJQxVgqoew: Extracting video information
[youtube] RuJQxVgqoew: Downloading DASH manifest
[debug] Invoking downloader on 'https://r4---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=46e250c5582aa1ec&itag=140&source=youtube&requiressl=yes&gcr=ch&mm
=31&pl=27&mv=u&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=2955198&lmt=1423
453241910504&dur=245.109&sver=3&mt=1427002416&upn=Srq3HfDTwR8&signature=38094065
2FC4048718CBB9637E05C1A5276A7BF4.91E37A3C9F0D495BC22BF62E5E985AB5851C22E5&key=dg
_yt0&fexp=900720,907263,912333,923360,929243,929821,934960,9407060,9407103,94081
01,9408162,942311,948124,951511,951703,952302,952612,952901,955301,957201,959701
,961404&ip=178.195.176.197&ipbits=0&expire=1427024201&sparams=ip,ipbits,expire,i
d,itag,source,requiressl,gcr,mm,pl,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\Lips are movin by Meghan Tranior_20150208.m4a has
already been downloaded
[download] 100% of 2.82MiB
WARNING: RuJQxVgqoew: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 7 of 14
[youtube] ADrojWEa3c0: Downloading webpage
[youtube] ADrojWEa3c0: Extracting video information
[youtube] ADrojWEa3c0: Downloading DASH manifest
[debug] Invoking downloader on 'https://r7---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=003ae88d611addcd&itag=140&source=youtube&requiressl=yes&ms=au&mv=
u&pl=27&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=2535842&lmt=14234520162
18676&dur=210.303&signature=22FA25323ED49C093641EB2F7DF8E8504F80BE3C.67E1A9519CA
7BC6F0DD99328A44C1306EA396DCD&key=dg_yt0&upn=edS1DtyDXnc&mt=1427002416&fexp=9007
20,907263,912333,923360,929243,929821,934960,9407060,9407103,9408101,9408162,942
311,948124,951511,951703,952302,952612,952901,955301,957201,959701,961404&sver=3
&ip=178.195.176.197&ipbits=0&expire=1427024202&sparams=ip,ipbits,expire,id,itag,
source,requiressl,ms,mv,pl,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\Replay by Zendya_20150208.m4a has already been dow
nloaded
[download] 100% of 2.42MiB
WARNING: ADrojWEa3c0: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 8 of 14
[youtube] ILojMmUBsyc: Downloading webpage
[youtube] ILojMmUBsyc: Extracting video information
[youtube] ILojMmUBsyc: Downloading DASH manifest
[debug] Invoking downloader on 'https://r1---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=20ba23326501b327&itag=140&source=youtube&requiressl=yes&ms=au&mm=
31&pl=27&mv=u&ratebypass=yes&mime=audio/mp4&gir=yes&clen=1735889&lmt=14231058524
83971&dur=108.088&key=dg_yt0&sver=3&signature=8B9AF0DA4FB758253599AB1A68B55DF1F7
FB15BB.71056AEC08B53D2274322167D5F1D19935C9D9E0&mt=1427002416&upn=ZnofJD1Xc7c&fe
xp=900720,907263,912333,923360,929243,929821,934960,9407060,9407103,9408101,9408
162,942311,948124,951511,951703,952302,952612,952901,955301,957201,959701,961404
&ip=178.195.176.197&ipbits=0&expire=1427024202&sparams=ip,ipbits,expire,id,itag,
source,requiressl,ms,mm,pl,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\Copy of pitch perfect riff off no diggty_20150204.
m4a has already been downloaded
[download] 100% of 1.66MiB
WARNING: ILojMmUBsyc: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 9 of 14
[youtube] Rk28X3F17Eg: Downloading webpage
[youtube] Rk28X3F17Eg: Extracting video information
[youtube] Rk28X3F17Eg: Downloading DASH manifest
[debug] Invoking downloader on 'https://r3---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=464dbc5f7175ec48&itag=140&source=youtube&requiressl=yes&pl=27&mv=
u&ms=au&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=338822&lmt=141934207239
9579&dur=21.060&mt=1427002416&fexp=900720,907263,912333,923360,929243,929821,934
960,9407060,9407103,9408101,9408162,942311,948124,951511,951703,952302,952612,95
2901,955301,957201,959701,961404&signature=4F18EE010475F8DC83FEFD8FF16306BD14167
54A.3945984E192397A1E630FAE89673BD8A37B90E6C&sver=3&key=dg_yt0&upn=rhxMsYbkQBE&i
p=178.195.176.197&ipbits=0&expire=1427024203&sparams=ip,ipbits,expire,id,itag,so
urce,requiressl,pl,mv,ms,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\My Slideshow_20150204.m4a has already been downloa
ded
[download] 100% of 330.88KiB
WARNING: Rk28X3F17Eg: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 10 of 14
[youtube] uaQ2iYjQDsw: Downloading webpage
[youtube] uaQ2iYjQDsw: Extracting video information
[youtube] uaQ2iYjQDsw: Downloading DASH manifest
[debug] Invoking downloader on 'https://r3---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=b9a4368988d00ecc&itag=140&source=youtube&requiressl=yes&mm=31&pl=
27&ms=au&mv=u&ratebypass=yes&mime=audio/mp4&gir=yes&clen=1363526&lmt=14231057626
61508&dur=84.891&fexp=900720,907263,912333,923360,929243,929821,934960,9407060,9
407103,9408101,9408162,942311,948124,951511,951703,952302,952612,952901,955301,9
57201,959701,961404&mt=1427002416&upn=bBokKE2B_EU&signature=905177E0D72A1734A9D2
C16E92338DDEEEC1BC22.35CD6FD4CDD34C8EE9DA78610B52D296EF2F5323&sver=3&key=dg_yt0&
ip=178.195.176.197&ipbits=0&expire=1427024204&sparams=ip,ipbits,expire,id,itag,s
ource,requiressl,mm,pl,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\I have had enough with like a girl_20150204.m4a ha
s already been downloaded
[download] 100% of 1.30MiB
WARNING: uaQ2iYjQDsw: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 11 of 14
[youtube] m31krCdS71M: Downloading webpage
[youtube] m31krCdS71M: Extracting video information
[youtube] m31krCdS71M: Downloading DASH manifest
[debug] Invoking downloader on 'https://r2---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=9b7d64ac2752ef53&itag=140&source=youtube&requiressl=yes&pl=27&mm=
31&ms=au&mv=u&ratebypass=yes&mime=audio/mp4&gir=yes&clen=298639&lmt=142306256651
5468&dur=24.705&fexp=900720,907263,912333,923360,929243,929821,934960,9407060,94
07103,9408101,9408162,942311,948124,951511,951703,952302,952612,952901,955301,95
7201,959701,961404&signature=58E00C061116AA81963937FA783F2F8C608926EC.565305DC44
CEC39D468F89E6F4CEF630E8798960&key=dg_yt0&mt=1427002416&sver=3&upn=rLI-sHGyqbg&i
p=178.195.176.197&ipbits=0&expire=1427024204&sparams=ip,ipbits,expire,id,itag,so
urce,requiressl,pl,mm,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\about a week ago_20150204.m4a has already been dow
nloaded
[download] 100% of 291.64KiB
WARNING: m31krCdS71M: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 12 of 14
[youtube] 1fX_dvDAvqo: Downloading webpage
[youtube] 1fX_dvDAvqo: Extracting video information
[youtube] 1fX_dvDAvqo: Downloading DASH manifest
[debug] Invoking downloader on 'https://r7---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=d5f5ff76f0c0beaa&itag=140&source=youtube&requiressl=yes&ms=au&mv=
u&pl=27&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=1057968&lmt=14229842345
22287&dur=87.701&fexp=900720,907263,912333,923360,929243,929821,934960,9407060,9
407103,9408101,9408162,942311,948124,951511,951703,952302,952612,952901,955301,9
57201,959701,961404&upn=-OIXYW8QuEA&signature=026931D39389C2FD7DFE8EFE8EAF272633
2A40E9.3D3524531DF686887985A2A711DE1355132BE9D4&sver=3&mt=1427002416&key=dg_yt0&
ip=178.195.176.197&ipbits=0&expire=1427024205&sparams=ip,ipbits,expire,id,itag,s
ource,requiressl,ms,mv,pl,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\pitch perfect_20150203.m4a has already been downlo
aded
[download] 100% of 1.01MiB
WARNING: 1fX_dvDAvqo: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 13 of 14
[youtube] orJb4snd2N0: Downloading webpage
[youtube] orJb4snd2N0: Extracting video information
[youtube] orJb4snd2N0: Downloading DASH manifest
[debug] Invoking downloader on 'https://r3---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=a2b25be2c9ddd8dd&itag=140&source=youtube&requiressl=yes&mv=u&mm=3
1&pl=27&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=1311151&lmt=14229844607
08752&dur=108.714&key=dg_yt0&upn=8febztih0To&mt=1427002416&signature=4DACE79502E
6E6FEAAE14A2D63EABBBF6811C028.52DD2C70BCD83B93C87A3CE4C1B9D7A72D075C75&fexp=9007
20,907263,912333,923360,929243,929821,934960,9407060,9407103,9408101,9408162,942
311,948124,951511,951703,952302,952612,952901,955301,957201,959701,961404&sver=3
&ip=178.195.176.197&ipbits=0&expire=1427024205&sparams=ip,ipbits,expire,id,itag,
source,requiressl,mv,mm,pl,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\pitch perfect riff off no diggty_20150203.m4a has
already been downloaded
[download] 100% of 1.25MiB
WARNING: orJb4snd2N0: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 14 of 14
[youtube] aMAMA1xySh0: Downloading webpage
[youtube] aMAMA1xySh0: Extracting video information
[youtube] aMAMA1xySh0: Downloading DASH manifest
[debug] Invoking downloader on 'https://r2---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=68c00c035c724a1d&itag=140&source=youtube&requiressl=yes&ms=au&mv=
u&pl=27&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=3341409&lmt=14229855077
14277&dur=208.096&key=dg_yt0&mt=1427002416&upn=9o8UjK7S2fY&signature=651C5575C42
268201E3955585B46AEDDCDC12228.89EA80D8300F893E64257A4A8B530D82F8F83DCE&sver=3&fe
xp=900720,907263,912333,923360,929243,929821,934960,9407060,9407103,9408101,9408
162,942311,948124,951511,951703,952302,952612,952901,955301,957201,959701,961404
&ip=178.195.176.197&ipbits=0&expire=1427024206&sparams=ip,ipbits,expire,id,itag,
source,requiressl,ms,mv,pl,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] e:\yt\Naomi Barnes\My Edited Video_20141223.m4a has already been down
loaded
[download] 100% of 3.19MiB
WARNING: aMAMA1xySh0: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[generic] www.youtube: Requesting header
[redirect] Following redirect to https://www.youtube.com/supported_browsers?next
_url=%2F
[download] Downloading playlist: supported_browsers
[youtube:user] supported_browsers: Downloading video ids from 1 to 51
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPEr
ror()); please report this issue on https://yt-dl.org/bug . Make sure you are us
ing the latest version; type  youtube-dl -U  to update. Be sure to call youtube-
dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 314, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1679, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
