### ISSUE TITLE
Error: Unable for writing, possibly russian channel specific

### ISSUE THREAD

**Issue by computerfreak105** [rg3/youtube-dl#5259]
Here four russian youtube urls which generate this error:

_ Love Strike _
https://www.youtube.com/channel/UCRqPLUhVrHf2aBWG45vsQNg
(This one creates an empty directory.)

Катя Степанова
https://www.youtube.com/channel/UCt1eIcxc6wT7boJp-Q_pQXQ

Женя Колдан
https://www.youtube.com/channel/UCh-6dOdPQpD32xn5g5XdOYQ

Андрей Мелников
https://www.youtube.com/channel/UChIlwlYwwqfaeFtpaRIqRqQ

Logs for _ Love Strike _
E:\>youtube-dl -f 140/m4a -o e:\yt/%(uploader)s/%(title)s_%(upload_date)s.%(ext)
s -a yt.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', '140/m4a', '-o', 'e:\\yt/%(uploader)s/%(title)
s_%(upload_date)s.%(ext)s', '-a', 'yt.txt', '--verbose']
[debug] Batch file urls: [u'https://www.youtube.com/channel/UCRqPLUhVrHf2aBWG45v
sQNg', u'https://www.youtube.com/channel/UCuE0AXfwA_C0ziSRK_ZIdLw', u'https://ww
w.youtube.com/channel/UCtqz3PLwc1rfLUyodPVfAdg', u'https://www.youtube.com/chann
el/UCEaBsgoPKe5BYPxn6POufTw', u'https://www.youtube.com/channel/UClEG_a8VOjlIHwL
CMIRxPeg', u'https://www.youtube.com/channel/UChjpRB6s5uMmE7uW4HiuVcA', u'https:
//www.youtube.com/channel/UCWpaLNyHzFmFPEoBwUPpq-g', u'https://www.youtube.com/c
hannel/UC4eb3MzMyRPGVk1tKGnmYVA', u'https://www.youtube.com/channel/UCgo9FBrLZu4
RFhsUcMlpB8A', u'https://www.youtube.com/channel/UCcv25IWbN6RdzppdX4MfbGw', u'ht
tps://www.youtube.com/channel/UCUD-1JBiV7zAL9RqjL_LnYQ', u'https://www.youtube.c
om/channel/UClE9NhAjdiGqEaG2rDKhtKg', u'https://www.youtube.com/channel/UCXgrSU5
lCPe5HlpriQQV5UA', u'https://www.youtube.com/channel/UCZZe7k4sMBm5zHioryruYTw',
u'https://www.youtube.com/channel/UCwapTgBqG-xNTa_WcsspAQA', u'https://www.youtu
be.com/channel/UC-hu6KgB5x7jCXkgaaZ6P9Q', u'https://www.youtube.com/channel/UCzo
HG5lHi1rSVrWKvP_wbdw', u'https://www.youtube.com/channel/UCrktjZyOntFCloPanFg05d
w', u'https://www.youtube.com/channel/UCHwdi14YVyp5pUIFNjwnVrg', u'https://www.y
outube.com/channel/UCRbDhfZ4m4SuuuDGVYrnaJA', u'https://www.youtube.com/channel/
UC-GtgnYSx0q94EMIWNZUU-Q', u'https://www.youtube.com/channel/UCJSv0PSDDRb53AFyBK
7NN0w', u'https://www.youtube.com/channel/UCY1chYi_0OtgNx7AsaOXjxw', u'https://w
ww.youtube.com/', u'https://www.youtube.com/channel/UCa5xHw1w-2FF-UAx3uz9rkw']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:channel] UCRqPLUhVrHf2aBWG45vsQNg: Downloading webpage
[download] Downloading playlist: UCRqPLUhVrHf2aBWG45vsQNg
[youtube:channel] playlist UCRqPLUhVrHf2aBWG45vsQNg: Downloading 18 videos
[download] Downloading video 1 of 18
[youtube] _zzVCc_b2Ok: Downloading webpage
[youtube] _zzVCc_b2Ok: Extracting video information
[youtube] _zzVCc_b2Ok: Downloading DASH manifest
[debug] Invoking downloader on 'https://r8---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=ff3cd509cfdbd8e9&itag=140&source=youtube&requiressl=yes&pl=27&mm=
31&ms=au&mv=m&ratebypass=yes&mime=audio/mp4&gir=yes&clen=80344468&lmt=1420130993
398794&dur=5004.619&mt=1427004534&signature=87D1E18E0B60821D9E922F6D0481C0FD6462
AE42.862D1B8C13CBA1F32248A13B66504AB13BFE880D&sver=3&upn=XRvxcSUb6E4&fexp=900720
,907263,924619,924638,931359,934954,936117,9407103,9407432,9407792,9407890,94081
01,9408183,9408196,948124,948907,951511,951703,952302,952612,952901,955301,95720
1,959701,960613,961404&key=dg_yt0&ip=178.195.176.197&ipbits=0&expire=1427026184&
sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mm,ms,mv,ratebypass,mime,g
ir,clen,lmt,dur'
ERROR: unable to open for writing: [Errno 2] No such file or directory: u'e:\\yt
\\ Love Strike \\Minecraft -PlayDay_20150101.m4a.part'
Traceback (most recent call last):
  File "youtube_dl\downloader\http.pyo", line 160, in real_download
  File "youtube_dl\utils.pyo", line 248, in sanitize_open
IOError: [Errno 2] No such file or directory: u'e:\\yt\\ Love Strike \\Minecraft
 -PlayDay_20150101.m4a.part'

E:\>

Logs for Катя Степанова

E:\>kjhkjhkjhyoutube-dl -f 140/m4a -o e:\yt/%(uploader)s/%(title)s_%(upload_date
)s.%(ext)s -a yt.txt
Der Befehl "kjhkjhkjhyoutube-dl" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

E:\>youtube-dl -f 140/m4a -o e:\yt/%(uploader)s/%(title)s_%(upload_date)s.%(ext)
s -a yt.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', '140/m4a', '-o', 'e:\\yt/%(uploader)s/%(title)
s_%(upload_date)s.%(ext)s', '-a', 'yt.txt', '--verbose']
[debug] Batch file urls: [u'https://www.youtube.com/channel/UCt1eIcxc6wT7boJp-Q_
pQXQ', u'https://www.youtube.com/channel/UCuE0AXfwA_C0ziSRK_ZIdLw', u'https://ww
w.youtube.com/channel/UCtqz3PLwc1rfLUyodPVfAdg', u'https://www.youtube.com/chann
el/UCEaBsgoPKe5BYPxn6POufTw', u'https://www.youtube.com/channel/UClEG_a8VOjlIHwL
CMIRxPeg', u'https://www.youtube.com/channel/UChjpRB6s5uMmE7uW4HiuVcA', u'https:
//www.youtube.com/channel/UCWpaLNyHzFmFPEoBwUPpq-g', u'https://www.youtube.com/c
hannel/UC4eb3MzMyRPGVk1tKGnmYVA', u'https://www.youtube.com/channel/UCgo9FBrLZu4
RFhsUcMlpB8A', u'https://www.youtube.com/channel/UCcv25IWbN6RdzppdX4MfbGw', u'ht
tps://www.youtube.com/channel/UCUD-1JBiV7zAL9RqjL_LnYQ', u'https://www.youtube.c
om/channel/UClE9NhAjdiGqEaG2rDKhtKg', u'https://www.youtube.com/channel/UCXgrSU5
lCPe5HlpriQQV5UA', u'https://www.youtube.com/channel/UCZZe7k4sMBm5zHioryruYTw',
u'https://www.youtube.com/channel/UCwapTgBqG-xNTa_WcsspAQA', u'https://www.youtu
be.com/channel/UC-hu6KgB5x7jCXkgaaZ6P9Q', u'https://www.youtube.com/channel/UCzo
HG5lHi1rSVrWKvP_wbdw', u'https://www.youtube.com/channel/UCrktjZyOntFCloPanFg05d
w', u'https://www.youtube.com/channel/UCHwdi14YVyp5pUIFNjwnVrg', u'https://www.y
outube.com/channel/UCRbDhfZ4m4SuuuDGVYrnaJA', u'https://www.youtube.com/channel/
UC-GtgnYSx0q94EMIWNZUU-Q', u'https://www.youtube.com/channel/UCJSv0PSDDRb53AFyBK
7NN0w', u'https://www.youtube.com/channel/UCY1chYi_0OtgNx7AsaOXjxw', u'https://w
ww.youtube.com/', u'https://www.youtube.com/channel/UCa5xHw1w-2FF-UAx3uz9rkw']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:channel] UCt1eIcxc6wT7boJp-Q_pQXQ: Downloading webpage
[download] Downloading playlist: UCt1eIcxc6wT7boJp-Q_pQXQ
[youtube:channel] UCt1eIcxc6wT7boJp-Q_pQXQ: Downloading page #2
[youtube:channel] playlist UCt1eIcxc6wT7boJp-Q_pQXQ: Downloading 42 videos
[download] Downloading video 1 of 42
[youtube] wSsoEw7t7FE: Downloading webpage
[youtube] wSsoEw7t7FE: Extracting video information
[youtube] wSsoEw7t7FE: Downloading DASH manifest
[debug] Invoking downloader on 'https://r2---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=c12b28130eedec51&itag=140&source=youtube&requiressl=yes&mv=u&mm=3
1&pl=27&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=9448869&lmt=14258884219
33081&dur=588.532&upn=sGo0xHVMIjI&key=dg_yt0&signature=7D70BA76F8D736E566B4AF516
421581126F8797D.9A547D87D1B8E25DC3FA78A24BAE9A139C325150&mt=1427004843&sver=3&fe
xp=900720,907263,924638,929305,934954,934964,9406813,9406894,9406952,9407103,940
7706,9408102,940925,948124,948703,951511,951703,952302,952612,952901,955204,9553
01,957201,959701,961404,964728&ip=178.195.176.197&ipbits=0&expire=1427026722&spa
rams=ip,ipbits,expire,id,itag,source,requiressl,mv,mm,pl,ms,ratebypass,mime,gir,
clen,lmt,dur'
ERROR: unable to open for writing: [Errno 2] No such file or directory: u'e:\\yt
\\ \\2 VLOGa_20150309.m4a.part'
Traceback (most recent call last):
  File "youtube_dl\downloader\http.pyo", line 160, in real_download
  File "youtube_dl\utils.pyo", line 248, in sanitize_open
IOError: [Errno 2] No such file or directory: u'e:\\yt\\ \\2 VLOGa_20150309.m4a.
part'

E:\>

Logs for Женя Колдан	

E:\>youtube-dl -f 140/m4a -o e:\yt/%(uploader)s/%(title)s_%(upload_date)s.%(ext)
s -a yt.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', '140/m4a', '-o', 'e:\\yt/%(uploader)s/%(title)
s_%(upload_date)s.%(ext)s', '-a', 'yt.txt', '--verbose']
[debug] Batch file urls: [u'https://www.youtube.com/channel/UCt1eIcxc6wT7boJp-Q_
pQXQ', u'https://www.youtube.com/channel/UCuE0AXfwA_C0ziSRK_ZIdLw', u'https://ww
w.youtube.com/channel/UCtqz3PLwc1rfLUyodPVfAdg', u'https://www.youtube.com/chann
el/UCEaBsgoPKe5BYPxn6POufTw', u'https://www.youtube.com/channel/UClEG_a8VOjlIHwL
CMIRxPeg', u'https://www.youtube.com/channel/UChjpRB6s5uMmE7uW4HiuVcA', u'https:
//www.youtube.com/channel/UCWpaLNyHzFmFPEoBwUPpq-g', u'https://www.youtube.com/c
hannel/UC4eb3MzMyRPGVk1tKGnmYVA', u'https://www.youtube.com/channel/UCgo9FBrLZu4
RFhsUcMlpB8A', u'https://www.youtube.com/channel/UCcv25IWbN6RdzppdX4MfbGw', u'ht
tps://www.youtube.com/channel/UCUD-1JBiV7zAL9RqjL_LnYQ', u'https://www.youtube.c
om/channel/UClE9NhAjdiGqEaG2rDKhtKg', u'https://www.youtube.com/channel/UCXgrSU5
lCPe5HlpriQQV5UA', u'https://www.youtube.com/channel/UCZZe7k4sMBm5zHioryruYTw',
u'https://www.youtube.com/channel/UCwapTgBqG-xNTa_WcsspAQA', u'https://www.youtu
be.com/channel/UC-hu6KgB5x7jCXkgaaZ6P9Q', u'https://www.youtube.com/channel/UCzo
HG5lHi1rSVrWKvP_wbdw', u'https://www.youtube.com/channel/UCrktjZyOntFCloPanFg05d
w', u'https://www.youtube.com/channel/UCHwdi14YVyp5pUIFNjwnVrg', u'https://www.y
outube.com/channel/UCRbDhfZ4m4SuuuDGVYrnaJA', u'https://www.youtube.com/channel/
UC-GtgnYSx0q94EMIWNZUU-Q', u'https://www.youtube.com/channel/UCJSv0PSDDRb53AFyBK
7NN0w', u'https://www.youtube.com/channel/UCY1chYi_0OtgNx7AsaOXjxw', u'https://w
ww.youtube.com/', u'https://www.youtube.com/channel/UCa5xHw1w-2FF-UAx3uz9rkw']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:channel] UCt1eIcxc6wT7boJp-Q_pQXQ: Downloading webpage
[download] Downloading playlist: UCt1eIcxc6wT7boJp-Q_pQXQ
[youtube:channel] UCt1eIcxc6wT7boJp-Q_pQXQ: Downloading page #2
[youtube:channel] playlist UCt1eIcxc6wT7boJp-Q_pQXQ: Downloading 42 videos
[download] Downloading video 1 of 42
[youtube] wSsoEw7t7FE: Downloading webpage
[youtube] wSsoEw7t7FE: Extracting video information
[youtube] wSsoEw7t7FE: Downloading DASH manifest
[debug] Invoking downloader on 'https://r2---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=c12b28130eedec51&itag=140&source=youtube&requiressl=yes&mm=31&pl=
27&mv=u&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=9448869&lmt=14258884219
33081&dur=588.532&fexp=900720,907263,908211,912148,930817,934954,939986,9406536,
9406749,9406813,9407103,9408102,9408112,942629,948124,951511,951703,952302,95261
2,952901,955301,957201,959701,961404,965200&sver=3&mt=1427005119&key=dg_yt0&upn=
ojt3aF-6Xac&signature=74FDCAD2135382C6C009F7E44E556286F6018DD2.6B31B729046343227
284C2AAF870AE595EC08028&ip=178.195.176.197&ipbits=0&expire=1427026819&sparams=ip
,ipbits,expire,id,itag,source,requiressl,mm,pl,mv,ms,ratebypass,mime,gir,clen,lm
t,dur'
ERROR: unable to open for writing: [Errno 2] No such file or directory: u'e:\\yt
\\ \\2 VLOGa_20150309.m4a.part'
Traceback (most recent call last):
  File "youtube_dl\downloader\http.pyo", line 160, in real_download
  File "youtube_dl\utils.pyo", line 248, in sanitize_open
IOError: [Errno 2] No such file or directory: u'e:\\yt\\ \\2 VLOGa_20150309.m4a.
part'

E:\>

Logs for Андрей Мелников

E:\>kjhkjhkjhyoutube-dl -f 140/m4a -o e:\yt/%(uploader)s/%(title)s_%(upload_date
)s.%(ext)s -a yt.txt
Der Befehl "kjhkjhkjhyoutube-dl" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

E:\>youtube-dl -f 140/m4a -o e:\yt/%(uploader)s/%(title)s_%(upload_date)s.%(ext)
s -a yt.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', '140/m4a', '-o', 'e:\\yt/%(uploader)s/%(title)
s_%(upload_date)s.%(ext)s', '-a', 'yt.txt', '--verbose']
[debug] Batch file urls: [u'https://www.youtube.com/channel/UChIlwlYwwqfaeFtpaRI
qRqQ', u'https://www.youtube.com/channel/UCuE0AXfwA_C0ziSRK_ZIdLw', u'https://ww
w.youtube.com/channel/UCtqz3PLwc1rfLUyodPVfAdg', u'https://www.youtube.com/chann
el/UCEaBsgoPKe5BYPxn6POufTw', u'https://www.youtube.com/channel/UClEG_a8VOjlIHwL
CMIRxPeg', u'https://www.youtube.com/channel/UChjpRB6s5uMmE7uW4HiuVcA', u'https:
//www.youtube.com/channel/UCWpaLNyHzFmFPEoBwUPpq-g', u'https://www.youtube.com/c
hannel/UC4eb3MzMyRPGVk1tKGnmYVA', u'https://www.youtube.com/channel/UCgo9FBrLZu4
RFhsUcMlpB8A', u'https://www.youtube.com/channel/UCcv25IWbN6RdzppdX4MfbGw', u'ht
tps://www.youtube.com/channel/UCUD-1JBiV7zAL9RqjL_LnYQ', u'https://www.youtube.c
om/channel/UClE9NhAjdiGqEaG2rDKhtKg', u'https://www.youtube.com/channel/UCXgrSU5
lCPe5HlpriQQV5UA', u'https://www.youtube.com/channel/UCZZe7k4sMBm5zHioryruYTw',
u'https://www.youtube.com/channel/UCwapTgBqG-xNTa_WcsspAQA', u'https://www.youtu
be.com/channel/UC-hu6KgB5x7jCXkgaaZ6P9Q', u'https://www.youtube.com/channel/UCzo
HG5lHi1rSVrWKvP_wbdw', u'https://www.youtube.com/channel/UCrktjZyOntFCloPanFg05d
w', u'https://www.youtube.com/channel/UCHwdi14YVyp5pUIFNjwnVrg', u'https://www.y
outube.com/channel/UCRbDhfZ4m4SuuuDGVYrnaJA', u'https://www.youtube.com/channel/
UC-GtgnYSx0q94EMIWNZUU-Q', u'https://www.youtube.com/channel/UCJSv0PSDDRb53AFyBK
7NN0w', u'https://www.youtube.com/channel/UCY1chYi_0OtgNx7AsaOXjxw', u'https://w
ww.youtube.com/', u'https://www.youtube.com/channel/UCa5xHw1w-2FF-UAx3uz9rkw']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:channel] UChIlwlYwwqfaeFtpaRIqRqQ: Downloading webpage
[download] Downloading playlist: UChIlwlYwwqfaeFtpaRIqRqQ
[youtube:channel] playlist UChIlwlYwwqfaeFtpaRIqRqQ: Downloading 3 videos
[download] Downloading video 1 of 3
[youtube] -YkKlca-01U: Downloading webpage
[youtube] -YkKlca-01U: Extracting video information
[youtube] -YkKlca-01U: Downloading DASH manifest
[debug] Invoking downloader on 'https://r4---sn-nfpnnjvh-9ans.googlevideo.com/vi
deoplayback?id=f9890a95c6bed355&itag=140&source=youtube&requiressl=yes&mv=u&ms=a
u&pl=27&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=21465869&lmt=1425191649
183843&dur=1780.761&mt=1427005119&signature=3E069BC35D69C388E68DF2E7FF8A97585874
92BD.200CEEE04202E1A60FA070F193E390F5A214E219&key=dg_yt0&fexp=900720,907263,9082
11,912149,930811,931385,934954,9405135,9405697,9405998,9407103,9407715,9407860,9
407929,9408102,943606,948124,951511,951703,952302,952612,952901,953918,955301,95
7201,959701,961404&upn=8DmpadE1Feo&sver=3&ip=178.195.176.197&ipbits=0&expire=142
7026913&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,pl,mm,ratebypas
s,mime,gir,clen,lmt,dur'
ERROR: unable to open for writing: [Errno 2] No such file or directory: u'e:\\yt
\\ \\Webcam video from March  1, 2015 06_03 AM (UTC)_20150228.m4a.part'
Traceback (most recent call last):
  File "youtube_dl\downloader\http.pyo", line 160, in real_download
  File "youtube_dl\utils.pyo", line 248, in sanitize_open
IOError: [Errno 2] No such file or directory: u'e:\\yt\\ \\Webcam video from Mar
ch  1, 2015 06_03 AM (UTC)_20150228.m4a.part'

E:\>

Thanks.

**Comment by jaimeMF** [comment]
Same as #5218
