### ISSUE TITLE
MLB extractor issue...

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5260]
Same video..
This URL works: 
http://m.mlb.com/video/topic/69972428/v51175783/atlstl-piscotty-makes-great-sliding-catch-on-line

These URLs default to generic and do not work:
http://m.cardinals.mlb.com/stl/video/v51175783/atlstl-piscotty-makes-great-sliding-catch-on-line/?partnerId=as_mlb_20150321_42500876&adbid=579409712979910656&adbpl=tw&adbpr=52847728

http://m.giants.mlb.com/sf/video/topic/69972428/v51175783/atlstl-piscotty-makes-great-sliding-catch-on-line

Output:
youtube-dl -v "http://m.cardinals.mlb.com/stl/video/v51175783/atl
stl-piscotty-makes-great-sliding-catch-on-line/?partnerId=as_mlb_20150321_425008
76&adbid=579409712979910656&adbpl=tw&adbpr=52847728"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://m.cardinals.mlb.com/stl/video/v5117578
3/atlstl-piscotty-makes-great-sliding-catch-on-line/?partnerId=as_mlb_20150321_4
2500876&adbid=579409712979910656&adbpl=tw&adbpr=52847728']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20
[debug] Proxy map: {}
[generic] ?partnerId=as_mlb_20150321_42500876&adbid=579409712979910656&adbpl=tw&
adbpr=52847728: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?partnerId=as_mlb_20150321_42500876&adbid=579409712979910656&adbpl=tw&
adbpr=52847728: Downloading webpage
[generic] ?partnerId=as_mlb_20150321_42500876&adbid=579409712979910656&adbpl=tw&
adbpr=52847728: Extracting information
ERROR: Unsupported URL: http://m.cardinals.mlb.com/stl/video/v51175783/atlstl-pi
scotty-makes-great-sliding-catch-on-line/?partnerId=as_mlb_20150321_42500876&adb
id=579409712979910656&adbpl=tw&adbpr=52847728
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 814, in _real_extract
  File "youtube_dl\utils.pyo", line 1528, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 25, column 171
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 654, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\generic.pyo", line 1289, in _real_extract
UnsupportedError: Unsupported URL: http://m.cardinals.mlb.com/stl/video/v5117578
3/atlstl-piscotty-makes-great-sliding-catch-on-line/?partnerId=as_mlb_20150321_4
2500876&adbid=579409712979910656&adbpl=tw&adbpr=52847728

Ringo

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
