### ISSUE TITLE
[TenPlay] ERROR: rtmpdump exited with code -6

### ISSUE THREAD

**Issue by pjta** [rg3/youtube-dl#5267]
$ youtube-dl -v http://tenplay.com.au/channel-eleven/neighbours/2015/3/23
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://tenplay.com.au/channel-eleven/neighbours/2015/3/23']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.9 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
[debug] Proxy map: {}
[TenPlay] http://tenplay.com.au/channel-eleven/neighbours/2015/3/23: Downloading webpage
[TenPlay] Neighbours - 23/03/15: Downloading JSON metadata
[debug] Invoking downloader on u'rtmpe://cp218164.edgefcs.net/ondemand/videos/2199827728001/201503/2470/2199827728001_4120550243001_4120388727001.mp4'
[download] Destination: Neighbours - 23_03_15-4120388727001.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmpe://cp218164.edgefcs.net/ondemand/videos/2199827728001/201503/2470/2199827728001_4120550243001_4120388727001.mp4 -o 'Neighbours - 23_03_15-4120388727001.flv.part'
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : cp218164.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : cp218164.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:videos/2199827728001/201503/2470/2199827728001_4120550243001_4120388727001
[rtmpdump] DEBUG: tcUrl    : rtmpe://cp218164.edgefcs.net:1935/ondemand
[rtmpdump] DEBUG: app      : ondemand
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 06
[rtmpdump] DEBUG: HandShake: DH pubkey position: 472
[rtmpdump] DEBUG: HandShake: Client digest offset: 1204
[rtmpdump] DEBUG: HandShake: Initial client digest: 
[rtmpdump] DEBUG: a7 9a 98 37 75 ab 6b 82 ea 51 0e ee 5a af 47 f5
[rtmpdump] DEBUG: 71 59 55 88 f5 c5 22 25 03 1a 75 17 2f 6e b0 32
[rtmpdump] DEBUG: HandShake: Type Answer   : 09
[rtmpdump] WARNING: HandShake: Type mismatch: client sent 6, server answered 9
[rtmpdump] DEBUG: HandShake: Server Uptime : 1188146412
[rtmpdump] DEBUG: HandShake: FMS Version   : 4.5.2.1
[rtmpdump] DEBUG: HandShake: Server DH public key offset: 451
[rtmpdump] DEBUG: HandShake: Secret key: 
[rtmpdump] DEBUG: 45 6b 46 a6 09 ca 42 26 18 9d 77 dc 7c 33 81 89
[rtmpdump] DEBUG: dd df 8a 6a 45 a6 b8 8b 28 8c b2 83 99 57 2a ac
[rtmpdump] DEBUG: 3d 34 1c b5 a3 c3 27 86 4e 80 cb 2f 98 15 4c 64
[rtmpdump] DEBUG: 8f 42 1c 24 70 52 2f d4 f0 47 ae 56 96 21 33 de
[rtmpdump] DEBUG: c0 2f 42 fd 9f ea 02 fa 69 94 02 3c b0 32 0c ad
[rtmpdump] DEBUG: 7c 7e 25 73 c9 4e f9 7b 21 c1 f3 96 c4 26 cf 5d
[rtmpdump] DEBUG: 93 2a 8a ad f2 3e 57 e3 37 c8 f7 06 02 13 45 73
[rtmpdump] DEBUG: 56 8d a1 57 be 97 8d 54 82 3d 9c 11 6b 6e 1c 20
[rtmpdump] DEBUG: RC4 Out Key: 
[rtmpdump] DEBUG: fb 25 db 49 7a f9 62 1e 50 10 a9 5f 39 97 9d 8e
[rtmpdump] rtmpdump(95475,0x7fff72f1e300) malloc: *** error for object 0x7fc1221002c8: incorrect checksum for freed object - object was probably modified after being freed.
[rtmpdump] *** set a breakpoint in malloc_error_break to debug

ERROR: rtmpdump exited with code -6
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 408, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 398, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1452, in download
    res = self.extract_info(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 711, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1153, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1385, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1360, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 341, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 205, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 154, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 532, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 494, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

====================================================
Operating system: MacOsX 10.10.2 + homebrew
Note: the site keeps episodes only for the last two weeks. Please use any recent weekday at the URL.

**Comment by yan12125** [comment]
It's a rtmpdump issue. Reinstall the latest git commit via ```brew install --HEAD rtmpdump``` solved the issue on my device. Please check it.

**Comment by yan12125** [comment]
rtmpdump in Homebrew was updated today (see Homebrew/homebrew#38622) and it works perfectly, too. Closing.

**Comment by pjta** [comment]
yan12125, thank you! It works now.

**Comment by aureliaandrewsb** [comment]
I use Allavsoft to download video from Tenplay, SBS etc websites.

Here is how to use it at http://www.allavsoft.com/how-to/download-tenplay-video.html

**Comment by impetusdirection** [comment]
To download various videos from Tenplay, SBS on demand, ABC iview, you may try this method http://www.allavsoft.com/how-to/download-tenplay-video.html

**Comment by yan12125** [comment]
Why are you promoting a not so good software everywhere :/

**Comment by dstftw** [comment]
Cause they need to sell it obviously. But nobody wants to buy this crap.
