### ISSUE TITLE
bestvideo+bestaudio format with a new 4k video

### ISSUE THREAD

**Issue by lucasmciruzzi** [rg3/youtube-dl#5268]
I'm having problems with the download of a 4k video with the format "bestvideo+bestaudio". The url is this: https://youtu.be/U-zC8BkPBZM the output looks like this (VLC Media Player - Windows 8.1):

![vlcsnap-2015-03-23-09h35m13s107](https://cloud.githubusercontent.com/assets/3979433/6779996/06384f2a-d140-11e4-966d-22adf5826f7d.png)
![vlcsnap-2015-03-23-09h35m21s191](https://cloud.githubusercontent.com/assets/3979433/6780001/19b45058-d140-11e4-80cb-6d64d0b1ff82.png)

And the console data with -v parameter is this:

    [youtube] U-zC8BkPBZM: Downloading webpage
    [youtube] U-zC8BkPBZM: Extracting video information
    [youtube] U-zC8BkPBZM: Downloading DASH manifest
    [debug] Invoking downloader on 'https://r3---sn-j5cax8pnpvo-x1x6.googlevideo.com/videoplayback?id=53ecc2f0190f0593&itag=272&source=youtube&requiressl=yes&pl=20&mm=31&ms=au&mv=m&ratebypass=yes&mime=video/webm&gir=yes&clen=177042540&lmt=1420786500033193&dur=270.729&signature=962907BBFA9E264A92A0E64A3DE3199C7AE41F74.3F089D6E0C32C94C88766D4F33B98D1252BE69DC&fexp=900720,907263,909425,934954,937517,9406746,9406813,9406834,9407103,9407465,9408018,9408101,945132,948124,951511,951703,952302,952612,952901,955301,957201,959701,961404,964733&mt=1427113641&key=dg_yt0&upn=wUcrn4vCncs&sver=3&ip=190.188.132.73&ipbits=0&expire=1427135268&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mm,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
    [download] Destination: Above & Beyond feat. Alex Vargas - 'All Over The World' (Official Video)-U-zC8BkPBZM.f272.webm
    [download] 100% of 168.84MiB in 01:49                    
    [debug] Invoking downloader on 'https://r3---sn-j5cax8pnpvo-x1x6.googlevideo.com/videoplayback?id=53ecc2f0190f0593&itag=141&source=youtube&requiressl=yes&pl=20&mm=31&ms=au&mv=m&ratebypass=yes&mime=audio/mp4&gir=yes&clen=8635569&lmt=1420874399720891&dur=270.837&signature=40D51BD20B372CF14EA6CFB253270E35E7AF7C27.666F496CFEB8EC71224D83A62B0C46F228EA31BA&fexp=900720,907263,909425,934954,937517,9406746,9406813,9406834,9407103,9407465,9408018,9408101,945132,948124,951511,951703,952302,952612,952901,955301,957201,959701,961404,964733&mt=1427113641&key=dg_yt0&upn=wUcrn4vCncs&sver=3&ip=190.188.132.73&ipbits=0&expire=1427135268&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mm,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
    [download] Destination: Above & Beyond feat. Alex Vargas - 'All Over The World' (Official Video)-U-zC8BkPBZM.f141.m4a
    [download] 100% of 8.24MiB in 00:05                  
    [ffmpeg] Merging formats into "Above & Beyond feat. Alex Vargas - 'All Over The World' (Official Video)-U-zC8BkPBZM.mkv"
    [debug] ffmpeg command line: ffmpeg -y -i 'Above & Beyond feat. Alex Vargas - '"'"'All Over The World'"'"' (Official Video)-U-zC8BkPBZM.f272.webm' -i 'Above & Beyond feat. Alex Vargas - '"'"'All Over The World'"'"' (Official Video)-U-zC8BkPBZM.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'Above & Beyond feat. Alex Vargas - '"'"'All Over The World'"'"' (Official Video)-U-zC8BkPBZM.mkv'

I'm sure is not a problem with the codecs on my PC because downloading only "bestvideo" without encoding to mkv, gives the same result. So the downloaded format is wrong or it has some weird encoding.

**Comment by dstftw** [comment]
Plays smoothly in mplayer, same mess in vlc 2.1.5 for me. What player do you use for playback?

**Comment by lucasmciruzzi** [comment]
Added to the issue: VLC Media Player on Windows 8.1

**Comment by dstftw** [comment]
I'm closing the issue as it's out of scope of youtube-dl and seems to be vlc related (neither 2.1.5 not 2.2.0 worked for me). At the same time this video plays perfectly in mplayer and ffplay.
