### ISSUE TITLE
Eroprofile.com: Unable to extract video url

### ISSUE THREAD

**Issue by prsrs** [rg3/youtube-dl#5269]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.eroprofile.com/m/videos/view/Try-It-On-P
ee_cut_2-wmv-4shared-com-file-sharing-download-movie-file', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-69972-g6c91afe, ffprobe N-69972-g6c91afe
[debug] Proxy map: {}
[EroProfile] Try-It-On-Pee_cut_2-wmv-4shared-com-file-sharing-download-movie-fil
e: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.or
g/bug . Make sure you are using the latest version; type  youtube-dl -U  to upda
te. Be sure to call youtube-dl with the --verbose flag and include its complete
output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 654, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\eroprofile.pyo", line 31, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 547, in _search_regex
RegexNotFoundError: Unable to extract video url; please report this issue on htt
ps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-d
l -U  to update. Be sure to call youtube-dl with the --verbose flag and include
its complete output.

**Comment by naglis** [comment]
Login support for eroprofile.com should be available in the next release of youtube-dl. The video in question is private, so please note that you'll need to [provide your EroProfile account details to youtube-dl](https://github.com/rg3/youtube-dl#authentication-options) in order to download it. Thank you for the report.
