### ISSUE TITLE
Error 403: Forbidden - via internet browser

### ISSUE THREAD

**Issue by HiddenFootprint** [rg3/youtube-dl#5270]
Hello,
first, thank you guys for an awesome tool. It made working with YouTube less painful.

MY ISSUE
I can download most of the YouTube videos, but it doesn't work for VEVO ones and for example this one: https://www.youtube.com/watch?v=tbu7qvdu9ms

I am forced to run youtube-dl on the webserver which I access through internet. For my mentioned example youtube video, youtube-dl gives me the full json output and even downloads the video when called via command line:

$ ./youtube-dl https://www.youtube.com/watch?v=tbu7qvdu9ms
[youtube] tbu7qvdu9ms: Downloading webpage
[youtube] tbu7qvdu9ms: Extracting video information
[youtube] tbu7qvdu9ms: Downloading DASH manifest
[download] Destination: RenOver #9 - iv!-tbu7qvdu9ms.mp4
[download]   2.0% of 819.35MiB at  2.37MiB/s ETA 05:39^C
ERROR: Interrupted by user

QUESTION
Why it doesn't work when I:

- take the direct video URL on server from youtube-dl json output ("./youtube-dl -jq https://www.youtube.com/watch?v=tbu7qvdu9ms")
- send this URL via browser to user in internet
- attempt to download video via that URL on my PC

Maybe it could help that it is Hangout video.

Thank you,
Foot

**Comment by MechaCoder** [comment]
try change the URL to replace the ? and = and with a /
i had this problem with another tool and this fixed the issue - i hope this works

**Comment by yan12125** [comment]
Youtube URLs are guaranteed to work only on the same machine. A possible approach is to download the video on the server first and send it to the client.
