### ISSUE TITLE
Unable to extract slideshare object

### ISSUE THREAD

**Issue by rkhoury** [rg3/youtube-dl#5279]
Verbose output is:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.slideshare.net/tlorach/opengl-nvidia-commandlistapproaching-zerodriveroverhead', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.03.24
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Slideshare] opengl-nvidia-commandlistapproaching-zerodriveroverhead: Downloading webpage
ERROR: Unable to extract slideshare object; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 651, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\slideshare.pyo", line 34, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 547, in _search_regex
RegexNotFoundError: Unable to extract slideshare object; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by naglis** [comment]
Thank you for the report. The reported issue should be fixed in the next release of youtube-dl, however, the provided link still will not work, as it contains only a slideshow and youtube-dl currently only supports downloads of video presentations (not slides).

**Comment by rkhoury** [comment]
> however, the provided link still will not work, as it contains only a slideshow and youtube-dl currently only supports downloads of video presentations (not slides).

Ah, thanks for clarifying that.

**Comment by sarimak** [comment]
I've hit the same issue and the stack trace in youtube-dl 2016.11.22 asked me to submit a bug -- could the error message warn that only slideshare videos but not the slideshows are supported, please? This could help with reducing duplicate bug reports...

**Comment by yan12125** [comment]
> could the error message warn that only slideshare videos but not the slideshows are supported, please?

yes, only videos are supported. There's a proposal to add static image support (#9337) but no conclusion yet
