### ISSUE TITLE
redtube now may use longer movie numbers in URLs, download fails

### ISSUE THREAD

**Issue by Musashi69** [rg3/youtube-dl#5281]
user@host:~$ youtube-dl -c --verbose http://www.redtube.com/105970
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-c', '--verbose', 'http://www.redtube.com/105970']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.6 - Linux-3.16.0-33-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.1-6, avprobe 11.1-6, ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
[debug] Proxy map: {}
[RedTube] 105970: Downloading webpage
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/redtube.py", line 23, in _real_extract
    r'<source src="(.+?)" type="video/mp4">', webpage, 'video URL')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 557, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 547, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This video has been removed and the problem is not related to length of video id at all. In the next version human readable error will be shown for all the removed videos. Thanks for the report.
