### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by arlindpajaziti** [rg3/youtube-dl#5287]
Is there a way to select video quality  like this  
youtube-dl  -f 36, 17,38   http://youtube.com....
so it will see if that format exist or not, if not exist it will try another format

or Is there a way to select a medium  quality  coz i dont like to be high quality and i cant see each video  what formats have (-F) .

**Comment by dstftw** [comment]
Use slashes for that: `youtube-dl -f 36/17/38 URL`.
