### ISSUE TITLE
YouTube-dl download location

### ISSUE THREAD

**Issue by TarekSalama** [rg3/youtube-dl#5292]
How can I set the download location for a channel or a playlist to be saved in a folder that gets created based on the channel's name, in a specific location such as the desktop. So if the channel is called Apple, the folder would be called Apple.

**Comment by dstftw** [comment]
Use [output template](https://github.com/rg3/youtube-dl#output-template).

**Comment by TarekSalama** [comment]
Can you give me an example?I tried doing something similar but it didn't
work for some reason. Also why do videos get an extra bunch of letters at
the end if their names even though I used the title command ?

**Comment by dstftw** [comment]
>Can you give me an example

`youtube-dl -o "C:/Documents and Settings/Administrator/Desktop/%(playlist_id)s/%(title)s.%(ext)s" URL`
>why do videos get an extra bunch of letters at the end if their names

Because default output template contains `%(id)s`
>even though I used the title command

`--title` option is not related to output template at all.

**Comment by TarekSalama** [comment]
Last questions, hopefully.
Is there a way to queue several links? 
And does resuming download actually work? Like, if the CMD window gets closed by accident or in case of a power outage, is it possible to detect the videos that were downloaded from a specific playlist and continue download the last partially downloaded video and the rest of the playlist?

**Comment by jaimeMF** [comment]
> Is there a way to queue several links? 

Just run `youtube-dl FIRST_URL SECOND_URL`.

>And does resuming download actually work?

By default it tries to continue the download if it sees a file matching `<video filename>.part`.
