### ISSUE TITLE
Issue Merging Formats

### ISSUE THREAD

**Issue by LukeMauldin** [rg3/youtube-dl#5293]
Receive error below.  Worked in previous versions.

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'243+171', u'--verbose', u'https://www.youtube.com/watch?v=8igk2ylk_X4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.24
[debug] Python version 2.7.9 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: avconv present, avprobe present
[debug] Proxy map: {}
[youtube] 8igk2ylk_X4: Downloading webpage
[youtube] 8igk2ylk_X4: Extracting video information
[youtube] 8igk2ylk_X4: Downloading DASH manifest
[debug] Invoking downloader on 'https://r19---sn-p5qlsnlr.googlevideo.com/videoplayback?id=f22824db2964fd7e&itag=243&source=youtube&requiressl=yes&pl=18&mm=31&ms=au&nh=IgpwcjAyLmlhZDI2KgkxMjcuMC4wLjE&mv=m&ratebypass=yes&mime=video/webm&gir=yes&clen=25233812&lmt=1425806614272691&dur=2267.600&upn=4qnM7MHkgfo&key=dg_yt0&mt=1427387253&sver=3&fexp=900238,900720,907263,912333,916726,924637,934954,9406880,9407103,9407811,9407816,9408101,9408183,942645,948124,948703,951511,951703,952612,957201,961404,961406&signature=707BB1DB46010CA8582A1AB2918BB6D2A5815FA2.204FCD4E99C41FD789DD5762D0FEDA0C4831EA87&ip=173.10.135.41&ipbits=0&expire=1427409003&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mm,ms,nh,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.f243.webm has already been downloaded
[download] 100% of 24.06MiB
[debug] Invoking downloader on 'https://r19---sn-p5qlsnlr.googlevideo.com/videoplayback?id=f22824db2964fd7e&itag=171&source=youtube&requiressl=yes&pl=18&mm=31&ms=au&nh=IgpwcjAyLmlhZDI2KgkxMjcuMC4wLjE&mv=m&ratebypass=yes&mime=audio/webm&gir=yes&clen=34115547&lmt=1425806640651541&dur=2267.651&upn=4qnM7MHkgfo&key=dg_yt0&mt=1427387253&sver=3&fexp=900238,900720,907263,912333,916726,924637,934954,9406880,9407103,9407811,9407816,9408101,9408183,942645,948124,948703,951511,951703,952612,957201,961404,961406&signature=30E76835856741D3EDE0874CB54E7122134BBFC6.881A6B931CC63E9A79EB3A225D5CB282BD5C69F3&ip=173.10.135.41&ipbits=0&expire=1427409003&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mm,ms,nh,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.f171.webm has already been downloaded
[download] 100% of 32.54MiB
[ffmpeg] Merging formats into "How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.webm"
[debug] ffmpeg command line: avconv -y -i 'How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.f243.webm' -i 'How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.f171.webm' -c copy -map 0:v:0 -map 1:a:0 'How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.webm'
ERROR:   Reason: image not found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1487, in post_process
    keep_video_wish, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 589, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 145, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError
```

**Comment by jaimeMF** [comment]
Could you post the output of `avconv -y -i 'How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.f243.webm' -i 'How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.f171.webm' -c copy -map 0:v:0 -map 1:a:0 'How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.webm'` (the command printed after `[debug] ffmpeg command line:`)?

**Comment by LukeMauldin** [comment]
Issuing `brew reinstall libav` worked

**Comment by lexfrei** [comment]
Same for me.
Can u add some checks about this?

**Comment by rucsa** [comment]
ERROR:   Reason: image not found

user$ avconv -y -i 'Yaroslav Lenzyak - Aditus-bLiqlgAlCbA.f248.webm' -i 'Yaroslav Lenzyak - Aditus-bLiqlgAlCbA.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'Yaroslav Lenzyak - Aditus-bLiqlgAlCbA.webm'
dyld: Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Referenced from: /usr/local/bin/avconv
  Reason: image not found
Abort trap: 6

user$ brew install libpng freetype 
Warning: libpng 1.6.36 is already installed and up-to-date
To reinstall 1.6.36, run `brew reinstall libpng`
Warning: freetype 2.9.1 is already installed, it's just not linked
You can use `brew link freetype` to link this version.
user$ brew link freetype
Linking /usr/local/Cellar/freetype/2.9.1... 8 symlinks created

user$ avconv -y -i 'Yaroslav Lenzyak - Aditus-bLiqlgAlCbA.f248.webm' -i 'Yaroslav Lenzyak - Aditus-bLiqlgAlCbA.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'Yaroslav Lenzyak - Aditus-bLiqlgAlCbA.webm'
avconv version 12.3, Copyright (c) 2000-2018 the Libav developers
  built on Jan 22 2019 21:48:01 with Apple LLVM version 9.0.0 (clang-900.0.39.2)
Input #0, matroska,webm, from 'Yaroslav Lenzyak - Aditus-bLiqlgAlCbA.f248.webm':
  Duration: 00:09:06.31, start: 0.000000, bitrate: N/A etc.
    …

**Comment by rucsa** [comment]
ERROR:   Reason: image not found

user$ `avconv -y -i 'How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.f243.webm' -i 'How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.f171.webm' -c copy -map 0:v:0 -map 1:a:0 'How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.webm'`
dyld: Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Referenced from: /usr/local/bin/avconv
  Reason: image not found
Abort trap: 6

user$ `brew install libpng freetype `
Warning: libpng 1.6.36 is already installed and up-to-date
To reinstall 1.6.36, run `brew reinstall libpng`
Warning: freetype 2.9.1 is already installed, it's just not linked
You can use `brew link freetype` to link this version.

user$ `brew link freetype`
Linking /usr/local/Cellar/freetype/2.9.1... 8 symlinks created

user$ `avconv -y -i 'How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.f243.webm' -i 'How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.f171.webm' -c copy -map 0:v:0 -map 1:a:0 'How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.webm'`
avconv version 12.3, Copyright (c) 2000-2018 the Libav developers
  built on Jan 22 2019 21:48:01 with Apple LLVM version 9.0.0 (clang-900.0.39.2)
Input #0, matroska,webm, from 'How Go spread at CloudFlare - John Graham-Cumming - London Go Gathering 2015-8igk2ylk_X4.f171.webm':
  Duration: 00:09:06.31, start: 0.000000, bitrate: N/A etc.
    …

**Comment by biokillos** [comment]
`brew reinstall ffmpeg` did the trick for me

**Comment by natritmeyer** [comment]
```console
brew install nettle
brew link nettle
```

^^ fixed it for me.
