### ISSUE TITLE
ERROR: Unable to extract info section (caused by RegexNotFoundError)

### ISSUE THREAD

**Issue by kenorb** [rg3/youtube-dl#5294]
Not sure if it's a bug, because on [Vimeo video](https://vimeo.com/58881614) it's saying: Video conversion failed.

And youtube-dl fails with:

    youtube-dl https://vimeo.com/58881614

    ERROR: Unable to extract info section (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34minfo section\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I've the latest version. Is there any workaround, or this video is just broken?

Related based on the same error: https://github.com/rg3/youtube-dl/issues/5001

**Comment by dstftw** [comment]
Can you watch it in browser?

**Comment by kenorb** [comment]
No, I can't.

**Comment by dstftw** [comment]
So, the video is broken then.
