### ISSUE TITLE
403 forbidden response when extracting info on a remote server

### ISSUE THREAD

**Issue by kobiburnley** [rg3/youtube-dl#5299]
I have a python server on heroku, and I put youtube-dl there to allow Android client achieve media url of videos. But in contrast of when extracting a url locally on my pc, when doing it on the server it returns a url that is not valid for the end user (It says 403 status forbidden). 

I guess it has to do with that maybe the url is generated such as it allowed only from the machine that asked for it, but is there any way through this?

**Comment by jaimeMF** [comment]
For some sites (like youtube) the url may only work on the same computer and/or with specific http headers. You can try using the `http_headers` field from the json output (`-j` option`).
