### ISSUE TITLE
ytwatchlater extractor fails to collect ids: "Your browser is deprecated. Please upgrade."

### ISSUE THREAD

**Issue by Athertonius** [rg3/youtube-dl#5301]
Using the ytwatchlater extractor, sign-in is successful as per usual, but trying to get the watch later playlist results in a page with only a warning, with no video links.

**Comment by jaimeMF** [comment]
It works for me, please [post the **full output**](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) you get when running `youtube-dl --verbose URL OTHER_OPTIONS`.

**Comment by Athertonius** [comment]
`$ youtube-dl --verbose :ytwatchlater`
[debug] System config: []
[debug] User config: ['--add-metadata', '-f', 'bestvideo[ext=mp4][width<=1920]+bestaudio[ext=m4a]', '-o', '%(title)s.%(ext)s', '-nck']
[debug] Command-line args: [u'--verbose', u':ytwatchlater']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.24
[debug] Python version 2.7.8 - Linux-3.16.0-33-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6, ffmpeg 2.5.git, ffprobe 2.5.git
[debug] Proxy map: {'all': 'socks://localhost:1234/', 'socks': 'socks://localhost:1234/', 'no': 'localhost,127.0.0.0/8,::1,*nmmu.ac.za,*.tenet.co.za'}
[youtube:watch_later] Downloading login page
[youtube:watch_later] Logging in
[youtube:watch_later] watch_later feed: Downloading page 1
[download] Downloading playlist: Youtube Watch Later
[youtube:watch_later] playlist Youtube Watch Later: Collected 0 video ids (downloading 0 of them)

**Comment by Athertonius** [comment]
An update released today seems to have fixed this issue. This was still persistent in the previous update. This is no longer the case.
