### ISSUE TITLE
youtube-dl fails when downloading from CSpan.

### ISSUE THREAD

**Issue by MBRosenthal** [rg3/youtube-dl#5302]
I'm trying to use youtube-dl, version 2015.03.24 under OS X 10.8.5 to download a video from CSpan, but instead of downloading the video, youtube-dl produces an error.  Here are the details.

I just downloaded and installed youtube-dl by doing the following:

	I navigated to http://rg3.github.io/youtube-dl/download.html to download youtube-dl.  That page says:

		To install it right away for all UNIX users (Linux, OS X, etc.), type:

			sudo curl https://yt-dl.org/downloads/2015.03.24/youtube-dl -o /usr/local/bin/youtube-dl
			sudo chmod a+x /usr/local/bin/youtube-dl

I ran those commands.  I then ran youtube-dl as follows:

	youtube-dl 'http://www.c-span.org/video/?104517-1/immigration-reforms-needed-protect-skilled-american-workers'

It complained:

	[CSpan] 104517: Downloading webpage
	ERROR: Unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I updated youtube-dl and reran it with the --verbose flag.  Below are the commands I ran and the output from those commands.

	bash-3.2$ youtube-dl -U
	youtube-dl is up-to-date (2015.03.24)

	bash-3.2$ youtube-dl --verbose 'http://www.c-span.org/video/?104517-1/immigration-reforms-needed-protect-skilled-american-workers'
	[debug] System config: []
	[debug] User config: []
	[debug] Command-line args: [u'--verbose', u'http://www.c-span.org/video/?104517-1/immigration-reforms-needed-protect-skilled-american-workers']
	[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
	[debug] youtube-dl version 2015.03.24
	[debug] Python version 2.7.2 - Darwin-12.5.0-x86_64-i386-64bit
	[debug] exe versions: none
	[debug] Proxy map: {}
	[CSpan] 104517: Downloading webpage
	ERROR: Unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	Traceback (most recent call last):
	  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
	    ie_result = ie.extract(url)
	  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
	    return self._real_extract(url)
	  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cspan.py", line 59, in _real_extract
	    webpage, 'description', flags=re.DOTALL)
	  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 557, in _html_search_regex
	    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
	  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 547, in _search_regex
	    raise RegexNotFoundError('Unable to extract %s' % _name)
	RegexNotFoundError: Unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Thanks for the report. This video is hosted by senate.gov rather than cspan itself. Such videos will be supported in the next version of youtube-dl.

**Comment by dstftw** [comment]
Support for videos hosted on senate.gov has been added in youtube-dl 2015.04.26. See our [FAQ](https://yt-dl.org/update) if you have problems updating.

**Comment by endeavorfrazer** [comment]
You may also try this method to download videos from C-span http://www.allavsoft.com/how-to/download-cspan-video-podcast-library-flash-video.html
