### ISSUE TITLE
Unable to extract json vp url

### ISSUE THREAD

**Issue by AndreasWelchlin** [rg3/youtube-dl#5307]
I tried the following:

xxx@localhost Videos]$ youtube-dl -f mp4 'http://www.arte.tv/guide/de/plus7/?em=049883-000'

The output was:

[arte.tv:+7] plus7: Downloading webpage
ERROR: Unable to extract json vp url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I am using the latest version:
xxx@localhost Videos]$ youtube-dl --version
2015.03.28

**Comment by jaimeMF** [comment]
In that url you can't play a video, but if you click on the image you got to http://www.arte.tv/guide/de/049883-000/terrorgefahr-ueberwachung-total, which works with youtube-dl.
