### ISSUE TITLE
some facebook videos are sooo sooo slow 

### ISSUE THREAD

**Issue by abomusab** [rg3/youtube-dl#5308]
hi 
some videos have sooo slowing speed 
it's just 140kb and my server speed is 1200 mega 
the problem just happen with some facebook videos

any suggest ?

**Comment by jaimeMF** [comment]
You can try using the aria2 downloader with `--external-downloader aria2c`.
(Note that if you are downloading more that one video at the same time, the speed will of course be lower)

**Comment by abomusab** [comment]
also there is a problem with this commend with the same video 
ERROR: unable to download video
i tried your commend with other video and every thing is good but some video didn't work with this video

**Comment by abomusab** [comment]
you can try with this link
https://www.facebook.com/video.php?v=405720942935883
is there is any way to get the full link download  like this 
https://fbcdn-video-e-a.akamaihd.net/hvideo-ak-xpf1/v/t42.1790-2/11092066_405722349602409.............88ae

**Comment by jaimeMF** [comment]
It works for me, you'll have to post the [**full output**](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) you get with the `--verbose` option.
For getting the url, just use the `-g` option or the json output with the `-j` option.

**Comment by abomusab** [comment]
thank you soo much 
the problem was from facebook server i tried with other website and i get the same problem when i download the video 
there is another thing 
i tried -g with http://www.dailymotion.com/ but it's not working with me 
the gave me broken link 
http://www.dailymotion.com/cdn/H264-1920x1080/video/x2kskfj.mp4?auth=1427809726-2562-dn452njw-fe10d8a65c706a3bb94292e0cc291824

**Comment by jaimeMF** [comment]
It works for me (from the **same computer**), if you are trying to use the url from other computer it won't work (you can try with the `http_headers` field from the json output, but it may not work).
