### ISSUE TITLE
add option to write video resolution (for example 1080p or 720p) in video file name

### ISSUE THREAD

**Issue by CiscoPress** [rg3/youtube-dl#5314]
something similar what Jdownloader already does

![screen shot 2015-03-29 at 18 31 56](https://cloud.githubusercontent.com/assets/1093836/6886585/2cf92a9c-d642-11e4-8e25-e3eb70343aa8.png)

thank you guys. You make awesome software, simply the best :-)

**Comment by jaimeMF** [comment]
You can use `%(resolution)s` in the output template, or if you just want `1080p`, then use `%(height)sp`
