### ISSUE TITLE
YouTube failed due to embed restrictions

### ISSUE THREAD

**Issue by SirCmpwn** [rg3/youtube-dl#5316]
[debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=2Vo3INoJZLA']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.03.24
    [debug] Python version 3.4.3 - Linux-3.19.2-1-ARCH-x86_64-with-arch
    [debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
    [debug] Proxy map: {}
    [youtube] 2Vo3INoJZLA: Downloading webpage
    [youtube] 2Vo3INoJZLA: Downloading embed webpage
    [youtube] 2Vo3INoJZLA: Refetching age-gated info webpage
    ERROR: 2Vo3INoJZLA: YouTube said: <a href="http://www.youtube.com/watch?v=2Vo3INoJZLA&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 651, in extract_info
        ie_result = ie.extract(url)
      File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 275, in extract
        return self._real_extract(url)
      File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 878, in _real_extract
        expected=True, video_id=video_id)
    youtube_dl.utils.ExtractorError: 2Vo3INoJZLA: YouTube said: <a href="http://www.youtube.com/watch?v=2Vo3INoJZLA&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.

**Comment by yan12125** [comment]
Duplicate of #4162 and there's a solution in #4627

**Comment by SirCmpwn** [comment]
Thanks. Sorry about that.

**Comment by SirCmpwn** [comment]
Perhaps a better error message is in order.
