### ISSUE TITLE
ERROR: get video url (dailymotion, xvideos)

### ISSUE THREAD

**Issue by Wapweb** [rg3/youtube-dl#5318]
1) dailymotion.com
video url: http://www.dailymotion.com/video/xfobqq_red-bull-x-fighters-london-2009_sport
returns mp4 but urls does not work

2) xvideos.com
video url: http://www.xvideos.com/video7131237/mi_papi_me_cogio_en_la_ducha
does not return mp4

**Comment by dstftw** [comment]
Both work perfectly with latest version of youtube-dl. Feel free to open a new issue if you can reproduce it with latest version and don't forget to post [full verbose output](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).
