### ISSUE TITLE
Unsupported URL (Phoenix German television)

### ISSUE THREAD

**Issue by leggewie** [rg3/youtube-dl#5322]
$ curl -s https://yt-dl.org/latest/youtube-dl -o ~/bin/youtube-dl
    $ ~/bin/youtube-dl --version
    2015.03.28
    $ ~/bin/youtube-dl http://www.phoenix.de/content/phoenix/die_sendungen/869815
    [generic] 869815: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] 869815: Downloading webpage
    [generic] 869815: Extracting information
    ERROR: Unsupported URL: http://www.phoenix.de/content/phoenix/die_sendungen/869815
They have some really nice content and it would be awesome to be able to download it using youtube-dl. Thanks.

**Comment by naglis** [comment]
youtube-dl already supports phoenix.de links, but not in such form. Links like the one you've provided should be supported in the next version of youtube-dl. Thank you for the report!

**Comment by leggewie** [comment]
Wouldn't it have been better to close this ticket with the next release, then?  I used the most up-to-date version.

**Comment by naglis** [comment]
I see your point. We usually post a follow-up comment on closed issues after the new version is released.

**Comment by leggewie** [comment]
no further comment was ever made to follow-up and it seems that indeed even in 2019 the issue itself is NOT fixed.
