### ISSUE TITLE
private dailymotion video marked explicit.

### ISSUE THREAD

**Issue by cardshuffler** [rg3/youtube-dl#5330]
ERROR: Couldn't get video, Dailymotion says: Explicit content.

can't seem to find an obvious workaround/fix for this. does one exist?

**Comment by drptv** [comment]
same issue here, looks like somethings changed.  checked the dev docs, this fails with same error:

python test/test_download.py TestDownload.test_Dailymotion_2

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
