### ISSUE TITLE
Add support for Azubu.tv

### ISSUE THREAD

**Issue by icesakura** [rg3/youtube-dl#5331]
Add support for Azubu.tv.
Example URL:http://www.azubu.tv/MadLife#!/play/25056/cj-madlife-march-24th-2015

Azubu.tv is a Game Live website.
But I'm not a programmer...
I hope you to add this website support.
Thanks a lot.  T.T

**Comment by jaimeMF** [comment]
It's already supported, you may be using an outdated version. See [our FAQ](https://yt-dl.org/update) if you have trouble updating.
