### ISSUE TITLE
Download Azubu.tv and "event not found"

### ISSUE THREAD

**Issue by icesakura** [rg3/youtube-dl#5332]
root@install:~# sudo youtube-dl -F http://www.azubu.tv/Faker#!/play/25892/skt-faker-march-25th-2015
    -bash: !/play/25892/skt-faker-march-25th-2015: event not found

It's the newest version

    root@install:~# youtube-dl --version
    2015.03.28

**Comment by naglis** [comment]
The exclamation mark in the URL is being interpreted by bash. Enclose the URL in single quotes, to avoid bash interpreting it:
```bash
youtube-dl 'http://www.azubu.tv/Faker#!/play/25892/skt-faker-march-25th-2015'
```
Also, youtube-dl doesn't require root privileges, so please avoid running youtube-dl as root, unless when updating.
