### ISSUE TITLE
youtube error

### ISSUE THREAD

**Issue by BCallifornia** [rg3/youtube-dl#5336]
trying to download a video from youtube with the latest youtube-dl and it brings an error.

youtube-dl --verbose https://www.youtube.com/watch?v=BWO6VDxSg4o
[debug] System config: []
[debug] User config: ['-f', 'bestvideo+bestaudio', '--write-description']
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=BWO6VDxSg4o']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.28
[debug] Python version 2.7.6 - Linux-3.13.0-48-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg 1.2.6-7, ffprobe 1.2.6-7
[debug] Proxy map: {}
[youtube] BWO6VDxSg4o: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1673, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
Please [read our FAQ entry for the issue](https://github.com/rg3/youtube-dl/blob/master/README.md#http-error-429-too-many-requests-or-402-payment-required), you have probably downloaded too much content and Youtube is blocking your IP.
