### ISSUE TITLE
Downloading videos ends in "ERROR: unable to download video data: HTTP Error 404: Not Found"

### ISSUE THREAD

**Issue by radoslawg** [rg3/youtube-dl#5337]
youtube-dl version 2015.03.28
I'm unable to download random videos, because of 404 error, however they play in a browser.
Example:

youtube-dl.exe --verbose http://www.youtube.com/watch?v=tllzhUmZFPw
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.youtube.com/watch?v=tllzhUmZFPw']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2015.03.28
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-70733-g1e4d049
[debug] Proxy map: {}
[youtube] tllzhUmZFPw: Downloading webpage
[youtube] tllzhUmZFPw: Extracting video information
[youtube] tllzhUmZFPw: Downloading DASH manifest
[debug] Invoking downloader on u'https://r5---sn-uvt5-ajwe.googlevideo.com/videoplayback?source=youtube&mm=31&ratebypass=yes&ip=217.113.236.79&ms=au&id=o-ALbBCG
wzlCY7uXDKOwGDjnIqpr2J7ZzO0eqwS8lL4kEu&mv=m&pl=21&mt=1427877110&requiressl=yes&dur=2840.032&mime=video%2Fmp4&itag=22&upn=SFnsTHUKiA8&ipbits=0&sver=3&signature=9
97FCE5A62651F8A2E3BC334A8837B2285C092FB.C3BDC71808626DDBF438036410ADD3A195988A90&fexp=900720%2C907263%2C913444%2C920935%2C934952%2C934953%2C934954%2C9405988%2C9
406894%2C9407059%2C9408030%2C9408102%2C9408136%2C9408473%2C9408597%2C945066%2C948124%2C948703%2C951511%2C951703%2C952612%2C957201%2C958500%2C961404%2C961406&ini
tcwndbps=2238750&key=yt5&expire=1427898800&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cu
pn%2Cexpire'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1379, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1354, in dl
  File "youtube_dl\downloader\common.pyo", line 341, in download
  File "youtube_dl\downloader\http.pyo", line 64, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1673, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 404: Not Found

Other videos with same problem:
http://www.youtube.com/watch?v=eofVhJc2lUA&feature=youtube_gdata
http://www.youtube.com/watch?v=9VWstw3TDOc&feature=youtube_gdata
http://www.youtube.com/watch?v=SRjtHEm_8lc&feature=youtube_gdata
http://www.youtube.com/watch?v=U_tPooOcsp4&feature=youtube_gdata
http://www.youtube.com/watch?v=eVx27XYwMYs&feature=youtube_gdata
http://www.youtube.com/watch?v=Z1_4NQnixPM&feature=youtube_gdata
http://www.youtube.com/watch?v=X_sCl13LpVQ&feature=youtube_gdata
http://www.youtube.com/watch?v=H1yhLRdv1E8&feature=youtube_gdata
http://www.youtube.com/watch?v=oJ2WDtP1FpA&feature=youtube_gdata
http://www.youtube.com/watch?v=kBqOWuuVFVo&feature=youtube_gdata

**Comment by radoslawg** [comment]
FWIW - Free Youtube Download application form DVDSoft downloads those videos.

**Comment by jaimeMF** [comment]
They all work for me, using the `--youtube-skip-dash-manifest` option will probably allow to download them (but some formats won't be available).

**Comment by radoslawg** [comment]
No, still no go..

y:\lps>youtube-dl.exe --verbose --youtube-skip-dash-manifest http://www.youtube.com/watch?v=tllzhUmZFPw
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--youtube-skip-dash-manifest', u'http://www.youtube.com/watch?v=tllzhUmZFPw']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2015.03.28
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-70733-g1e4d049
[debug] Proxy map: {}
[youtube] tllzhUmZFPw: Downloading webpage
[youtube] tllzhUmZFPw: Extracting video information
[debug] Invoking downloader on u'https://r5---sn-uvt5-ajwe.googlevideo.com/videoplayback?itag=22&expire=1427992639&fexp=900720%2C907263%2C912334%2C924637%2C9326
27%2C934962%2C9405619%2C9406003%2C9407430%2C9408047%2C9408102%2C9408224%2C944324%2C947248%2C948124%2C948703%2C951501%2C951511%2C951703%2C952612%2C957201%2C96140
4%2C961406%2C966201&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&source=yout
ube&mime=video%2Fmp4&mv=m&mt=1427970939&ms=au&mm=31&dur=2840.032&upn=uwxI6qwGYtI&id=o-ALE7S3s9AOPaLIvhs2gvLqxbzjyiUTvHxCOqd5juiF31&key=yt5&ip=217.113.236.79&ipb
its=0&signature=E3E23DA6ECFB4FF2C60E4EEA2E4525A985BBE86F.779C277689173D978E8A947F19C8DC26AE1E2255&sver=3&requiressl=yes&pl=21&initcwndbps=2385000&ratebypass=yes
'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1379, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1354, in dl
  File "youtube_dl\downloader\common.pyo", line 341, in download
  File "youtube_dl\downloader\http.pyo", line 64, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1673, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 404: Not Found

**Comment by dstftw** [comment]
Works fine with latest version (2016.05.16).
