### ISSUE TITLE
RegexNotFoundError: Unable to extract Initial JS player signature function name;

### ISSUE THREAD

**Issue by afrigeri** [rg3/youtube-dl#5338]
youtube-dl --verbose -U https://www.youtube.com/watch?v=R_qxXyJumII

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by afrigeri** [comment]
yep! sudo pip install --upgrade youtube-dl did the trick.  Thanks!
