### ISSUE TITLE
RegexNotFoundError: Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by cub-uanic** [rg3/youtube-dl#5339]
% youtube-dl 'https://www.youtube.com/watch?v=GSLSwwkLRW0'
 [youtube] Setting language
 [youtube] Confirming age
 [youtube] GSLSwwkLRW0: Downloading webpage
 [youtube] GSLSwwkLRW0: Downloading video info webpage
 [youtube] GSLSwwkLRW0: Extracting video information
 [youtube] GSLSwwkLRW0: Encrypted signatures detected.
 [youtube] GSLSwwkLRW0: Downloading js player vfllLRozy
 ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/cub/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 533, in _decrypt_signature
    video_id, player_url, s
  File "/home/cub/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 447, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/cub/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 508, in _parse_sig_js
    'Initial JS player signature function name')
  File "/home/cub/bin/youtube-dl/youtube_dl/extractor/common.py", line 424, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
 RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.',)); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
