### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by InternationsBusinessCenter** [rg3/youtube-dl#5342]
root@sand:/home/xxx/Guild/1# youtube-dl --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=6GRLRm9oKUM
[youtube] Setting language
[youtube] 6GRLRm9oKUM: Downloading webpage
[youtube] 6GRLRm9oKUM: Downloading video info webpage
[youtube] 6GRLRm9oKUM: Extracting video information
[youtube] 6GRLRm9oKUM: Encrypted signatures detected.
[youtube] 6GRLRm9oKUM: Downloading js player vfllLRozy
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

root@sand:/home/xxx/Guild/1# youtube-dl --verbose flag --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=6GRLRm9oKUM
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'flag', '--extract-audio', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=6GRLRm9oKUM']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] Proxy map: {}
ERROR: u'flag' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:flag" ) to search YouTube
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 407, in _real_extract
    ) % (url, url), expected=True)
ExtractorError: u'flag' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:flag" ) to search YouTube

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
