### ISSUE TITLE
Download playlist ids into video archive

### ISSUE THREAD

**Issue by RadAd** [rg3/youtube-dl#5343]
Is there a way to download the video ids into the archive but not download the videos? I only want to download new videos added to a playlist, not the current ones.

I tried:

youtube-dl --skip-download --download-archive video.txt <playlist>

**Comment by jaimeMF** [comment]
> Is there a way to download the video ids into the archive but not download the videos?

Videos are only added to the archive when the download is finished (that's its purpose).

>  I only want to download new videos added to a playlist, not the current ones.

I may have misunderstood you, but `youtube-dl  --download-archive video.txt PLAYLIST_URL` will only download the videos that are not already in the archive. It should work, could you give a more detailed explanation of why it doesn't work?

**Comment by RadAd** [comment]
I have already seen the videos in the playlist so I do not want to download them. I do want to download new videos as they are added to the list.

So I was trying to create an archive file to skip all the videos currently in the playlist. Then next time I download the playlist it will only download the new videos.

I thought that the --skip_download flag might allow me to create the archive file but it didn't, maybe thats not its purpose.

**Comment by jaimeMF** [comment]
Assuming you are using the bash shell, you can run `youtube-dl PLAYLIST_URL --get-id | while read ID; do echo youtube $ID; done > archive.txt` to create the archive.
