### ISSUE TITLE
Play.fm changed its interface and the extractor is not working anymore

### ISSUE THREAD

**Issue by ohcibi** [rg3/youtube-dl#5344]
Play.fm changed its interface, the extractor needs to be updated. Sample url: https://www.play.fm/franjazzco/peter-kruder-richard-dorfmeister-christian-prommer-g-stone-das-finale-badeschiff-vienna-at-2008-06-28

**Comment by dstftw** [comment]
Play.fm will be fixed in the next version. Thanks for the report.
