### ISSUE TITLE
Output template

### ISSUE THREAD

**Issue by Speeedfire** [rg3/youtube-dl#5345]
Hi!

I wanna help for this issue.

youtube-dl --extract-audio --audio-format mp3 --write-all-thumbnails --audio-quality 5 --write-info-json -l https://www.youtube.com/watch?v=d0FdAicAJKg -o "%(title)s.%(ext)s"
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: using output template conflicts with using title, video ID or auto number

**Comment by jaimeMF** [comment]
Just remove the `-l`, which tells youtube-dl to include the title in the filename. Since you are also setting the output template we can't decide which one to use.

**Comment by Speeedfire** [comment]
Thank you!
