### ISSUE TITLE
http://www.bloomberg.com/news/videos/b/14049c61-ecb9-4488-8efb-9332120d721b #site-support-request

### ISSUE THREAD

**Issue by prendinger** [rg3/youtube-dl#5347]
http://www.bloomberg.com/news/videos/b/14049c61-ecb9-4488-8efb-9332120d721b
generic not working
thx

**Comment by jaimeMF** [comment]
We have support for bloomberg, but they have changed their site and we had to update the extractor.
Thanks for the report.

**Comment by prendinger** [comment]
[bloomberg] Adapt to website changes (fixes #5347)   - amazing, thx a lot for the fast fix
