### ISSUE TITLE
Simple option to prefer specific format

### ISSUE THREAD

**Issue by dwt** [rg3/youtube-dl#535]
Hi there,

For my environment and to best use the files downloaded it would be much better to just always get mp4, if that fails get flv and if that fails get webm.

Now as far as I can see there's no simple option to set that preferred order. It can probably aproximated with the format thing, but as far as I undestand that is not exactly what I want and does not account for future quality additions.

What I want is something like --preferred-formats=mp4,flv,webm

**Comment by jaimeMF** [comment]
With the last versions, you can use `-f mp4/flv/webm/best` (the `/best` options is a fallback used if there aren't videos in the requested formats). Thanks for the report!
