### ISSUE TITLE
Force Overwrite

### ISSUE THREAD

**Issue by limechord** [rg3/youtube-dl#5353]
I can see on the manpage that `-w, --no-overwrites ---- do not overwrite files`
but is there a "force overwrite" option so that the videos downloaded can be constantly replaced by newer ones?
````
[download] video.mp4 has already been downloaded
````

One possible fix is to add `rm video.mp4;` in front of the youtube-dl command.

**Comment by jaimeMF** [comment]
Add `--no-continue`.

Personally I wouldn't use `video.mp4` as  the filename, playlists won't work as expected (and I think having the title in the filename is nicer).
