### ISSUE TITLE
[youtube] DASH manifest extraction error

### ISSUE THREAD

**Issue by thpublic** [rg3/youtube-dl#5357]
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=lFYaT-U82JY', u'--verbose', u'-s']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.03
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-i686-with-LinuxMint-17.1-rebecca
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] lFYaT-U82JY: Downloading webpage
[youtube] lFYaT-U82JY: Extracting video information
WARNING: [youtube] lFYaT-U82JY: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)

**Comment by dstftw** [comment]
Works fine with latest version.
