### ISSUE TITLE
audio issue --extract-audio --audio-format mp3

### ISSUE THREAD

**Issue by xsoft** [rg3/youtube-dl#5363]
Hi,
for few days the "Extract Audio" feature doesn't work.
Try on your own:

youtube-dl -4 "Mr3R6ydmfvI" --title --extract-audio --audio-format mp3
[youtube] Mr3R6ydmfvI: Downloading webpage
[youtube] Mr3R6ydmfvI: Extracting video information
[youtube] Mr3R6ydmfvI: Downloading DASH manifest
[download] Destination: gull law 5 sec woth sound-Mr3R6ydmfvI.m4a
[download] 100% of 220.52KiB in 00:00
[ffmpeg] Correcting container in "gull law 5 sec woth sound-Mr3R6ydmfvI.m4a"
WARNING: Your copy of ffmpeg is outdated, update ffmpeg to version 1.0 or newer if you encounter any errors.
ERROR: Unrecognized option 'c'

**Comment by dstftw** [comment]
As mentioned in warning, you are using an outdated version of ffmpeg. Update it to newest version available and most likely it will work.
Feel free to open a new issue if you'll still have issues with newer ffmpeg and don't forget to post [**full verbose** output](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).
