### ISSUE TITLE
New website request

### ISSUE THREAD

**Issue by acidiusgreen** [rg3/youtube-dl#5367]
I know you guys probably get alot of request for websites but living in pakistan its crazy hard to access youtube with a decent vpn or proxy. But using proxychains i can download entire playlists at a time so thanks for that! 

I was just wondering if its possible to add a website to your list : www.kissanime.com. Its the only anime website i've found that gives free hd quality anime. I could stream it with the shit internet connection I have but I think they host their files on same servers as youtube because I can only watch stuff using vpn  on their websites. 

Sorry I know its kindof a selfish request but I'd love it if you could try looking into it

**Comment by yan12125** [comment]
Please post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by jaimeMF** [comment]
We can't add support for kissanime because it seems that they don't have the rights for distributing the content, read [our FAQ](https://yt-dl.org/faq-anime) for more info.

**Comment by acidiusgreen** [comment]
Sorry didn't see. Just want to say that the work you guys are doing is amazing. If youtube-dl would have support a few more sites and allow downloading from manget urls then I would probably only be using it for all my download needs. Its still a powerful tool. Great job guys!
