### ISSUE TITLE
Comedy Central Change

### ISSUE THREAD

**Issue by helpdeskdan** [rg3/youtube-dl#5369]
The Nightly Show has changed to a different format.  Much thanks. 

$ youtube-dl -F "http://www.cc.com/full-episodes/xlbpt6/the-nightly-show-march-26--2015---isis-on-tatooine---bacon-rage-at-mcdonald-s-season-1-ep-01035" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'http://www.cc.com/full-episodes/xlbpt6/the-nightly-show-march-26--2015---isis-on-tatooine---bacon-rage-at-mcdonald-s-season-1-ep-01035', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.03
[debug] Python version 2.7.6 - Linux-3.13.0-48-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentral] the-nightly-show-march-26--2015---isis-on-tatooine---bacon-rage-at-mcdonald-s-season-1-ep-01035: Downloading webpage
ERROR: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 176, in _real_extract
    og_url = self._og_search_video_url(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 641, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 557, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 547, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 186, in _real_extract
    webpage, 'mgid')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 547, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by mitchellmebane** [comment]
This patch is working for me to grab The Daily Show and the Nightly Show.

**Comment by LMariachi** [comment]
Daily Show no longer working for me:

    $ youtube-dl --verbose -t http://thedailyshow.cc.com/full-episodes/zwardy/april-16--2015---eric-greitens
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'--verbose', u'-t', u'http://thedailyshow.cc.com/full-episodes/zwardy/april-16--2015---eric-greitens']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.04.17
    [debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
    [debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
    [debug] Proxy map: {}
    [ComedyCentralShows] april-16--2015---eric-greitens: Downloading webpage
    [ComedyCentralShows] april-16--2015---eric-greitens: Downloading show index
    [ComedyCentralShows] april-16--2015---eric-greitens: Downloading configuration for segment 1 / 4
    [ComedyCentralShows] april-16--2015---eric-greitens: Downloading configuration for segment 2 / 4
    [ComedyCentralShows] april-16--2015---eric-greitens: Downloading configuration for segment 3 / 4
    [ComedyCentralShows] april-16--2015---eric-greitens: Downloading configuration for segment 4 / 4
    [download] Downloading playlist: thedailyshow April 16, 2015 - Eric Greitens
    [ComedyCentralShows] playlist thedailyshow April 16, 2015 - Eric Greitens: Collected 4 video ids (downloading 4 of them)
    [download] Downloading video 1 of 4
     ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
     Traceback (most recent call last):
       File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 662, in extract_info
         return self.process_ie_result(ie_result, download, extra_info)
       File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 821, in process_ie_result
    extra_info=extra)
       File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 708, in process_ie_result
    return self.process_video_result(ie_result, download=download)
       File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1047, in process_video_result
    raise ExtractorError('No video formats found!')
     ExtractorError: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by malept** [comment]
Sounds like #5449 to me, which was fixed *after* your version (`2015.04.17`) was released.

**Comment by LMariachi** [comment]
Sorry, I searched on “comedy” in issue title and this was the only recent open one. Thanks!

**Comment by helpdeskdan** [comment]
Indeed, this is fixed in git.  Thanks malept. 

$ python -m youtube_dl -F --verbose "http://thedailyshow.cc.com/full-episodes/9q0y2l/april-15--2015---billy-crystal"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'--verbose', u'http://thedailyshow.cc.com/full-episodes/9q0y2l/april-15--2015---billy-crystal']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Git HEAD: b4c0806
[debug] Python version 2.7.6 - Linux-3.13.0-49-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentralShows] april-15--2015---billy-crystal: Downloading webpage
[ComedyCentralShows] april-15--2015---billy-crystal: Downloading show index
[ComedyCentralShows] april-15--2015---billy-crystal: Downloading configuration for segment 1 / 4
[ComedyCentralShows] april-15--2015---billy-crystal: Downloading configuration for segment 2 / 4
[ComedyCentralShows] april-15--2015---billy-crystal: Downloading configuration for segment 3 / 4
[ComedyCentralShows] april-15--2015---billy-crystal: Downloading configuration for segment 4 / 4
[download] Downloading playlist: thedailyshow April 15, 2015 - Billy Crystal
[ComedyCentralShows] playlist thedailyshow April 15, 2015 - Billy Crystal: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
(yada yada)
