### ISSUE TITLE
VoxNow not working...

### ISSUE THREAD

**Issue by malwikl** [rg3/youtube-dl#5379]
Hi,

I get an error when trying to download videos from VoxNow...

E.G. http://www.voxnow.de/game-of-chefs/folge-7.php?container_id=201557&player=1&season=1

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.voxnow.de/game-of-chefs/folge-7.php?container_id=201557&player=1&season=1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.03
[debug] Python version 2.7.6 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
[debug] Proxy map: {}
[RTLnow] 201557: Downloading webpage
[RTLnow] 201557: Downloading player data XML
[debug] Invoking downloader on u'rtmpe://fms.rtl.de/voxnow'
[download] Destination: Game of Chefs - Folge 7-201557.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmpe://fms.rtl.de/voxnow -o 'Game of Chefs - Folge 7-201557.flv.part' --swfVfy http://www.voxnow.de/includes/vodplayer.swf --pageUrl 'http://www.voxnow.de/game-of-chefs/folge-7.php?container_id=201557&player=1&season=1' --playpath mp4:7923/V_729260_CYHM_J60355_118707_h264-mq_f2e9ef7177b907e2e8a31d2a3ce40b9.f4v --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : fms.rtl.de
[rtmpdump] DEBUG: Parsed app     : voxnow
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : fms.rtl.de
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:7923/V_729260_CYHM_J60355_118707_h264-mq_f2e9ef7177b907e2e8a31d2a3ce40b9.f4v
[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.rtl.de:1935/voxnow
[rtmpdump] DEBUG: swfUrl   : http://www.voxnow.de/includes/vodplayer.swf
[rtmpdump] DEBUG: pageUrl  : http://www.voxnow.de/game-of-chefs/folge-7.php?container_id=201557&player=1&season=1
[rtmpdump] DEBUG: app      : voxnow
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: ce bb 86 a6 57 09 84 a6 96 0b 04 d1 7a 3b 9b 3c
[rtmpdump] DEBUG: 4b d9 68 c1 71 e8 13 70 62 28 2e d9 7e 70 5e 3a
[rtmpdump] DEBUG: SWFSize  : 1051380
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : fms.rtl.de
[rtmpdump] DEBUG: Parsed app     : voxnow
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : fms.rtl.de
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:7923/V_729260_CYHM_J60355_118707_h264-mq_f2e9ef7177b907e2e8a31d2a3ce40b9.f4v
[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.rtl.de:1935/voxnow
[rtmpdump] DEBUG: swfUrl   : http://www.voxnow.de/includes/vodplayer.swf
[rtmpdump] DEBUG: pageUrl  : http://www.voxnow.de/game-of-chefs/folge-7.php?container_id=201557&player=1&season=1
[rtmpdump] DEBUG: app      : voxnow
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: ce bb 86 a6 57 09 84 a6 96 0b 04 d1 7a 3b 9b 3c
[rtmpdump] DEBUG: 4b d9 68 c1 71 e8 13 70 62 28 2e d9 7e 70 5e 3a
[rtmpdump] DEBUG: SWFSize  : 1051380
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 408, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 398, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1446, in download
    res = self.extract_info(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 662, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 708, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1150, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1379, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1354, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 341, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 205, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 154, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 529, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 491, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

Do you have an idea why?

Thanks
Malwikl

**Comment by dstftw** [comment]
Closing since voxnow.de is now served by nowtv.de.
