### ISSUE TITLE
Please add support to http://www.dailymotion.com/old/user/USER

### ISSUE THREAD

**Issue by galex-713** [rg3/youtube-dl#5380]
URLs like http://www.dailymotion.com/old/user/LeVisiteurDuFutur/4

Dailymotion is already supported, but it has been forgotten, probably since Dailymotion doesn’t show the feature of putting oldest videos first in its interface (I discovered it casually tweaking URL by hand)…

Also, could you add the option “--playlist-reverse” to the manpage? That could be useful to someone if this occured again without hidden feature showing a reverse list…

**Comment by dstftw** [comment]
Will be fixed in the next version. You can use `--playlist-reverse` to download in reverse order.
