### ISSUE TITLE
Youtube-dl not displaying files correctly.

### ISSUE THREAD

**Issue by audiogamer22** [rg3/youtube-dl#5381]
Hi

I'm quite new at using the command line to use programs such as youtube-dl but think I might have found a bug.

I write.

youtube-dl -o%(title)s-%(ext)s (URL)
Then press enter. I look at the files while they are downloading into my folder and have noticed that, Funny_video.mp4 is named funny_video-mp4

Am I doing something wrong? Or is this a bug?

Also, and this is just my opinion, I think it would be nicer if the ID part of the output was removed. I understand now that I would have to write the template out myself, but think that finding youtube-dl then writing youtube-dl (URL) Should just download videos, either from playlists or a single video, without the ID.

I'm blind so skimming through the videos and hearing letters at the end of every video is quite annoying. Yes I can remove them but as you can imagine, if you have a playlist with over 1000 videos, that can get quite tedious. Even for someone who isn't blind, I can imagine that the same thing would be annoying to them.

But that is just my opinion and if I have to write -o %(title)s and all that, I don't mind, since it isn't that hard to do.

Thanks for taking a look at my report and I hope you have a nice day.

**Comment by dstftw** [comment]
>youtube-dl -o%(title)s-%(ext)s (URL)
Then press enter. I look at the files while they are downloading into my folder and have noticed that, Funny_video.mp4 is named funny_video-mp4

File is named exactly as you specified in output template. Replace dash with dot (`-o "%(title)s.%(ext)s"`) and you'll get `funny_video.mp4`.

ID part is preserved on purpose, namely to provide filename unicity by default as title is not necessarily unique. If you have 1000 videos in playlist and several of them happen to have equal names then it's impossible to distinguish between them.

**Comment by phihag** [comment]
By the way, have you considered adding a [configuration file](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration)?

Simply fill it with
```
-o "%(title)s.%(ext)s"
```
and youtube-dl will permanently have the behavior you want, unless you provide a different `-o` on the command line.

**Comment by audiogamer22** [comment]
Hi.

I don't know where to find the youtube-dl folder or how to add a config 
file. I have youtube-dl in a folder on an external hard drive, running 
the executable file doesn't seem to do anything.

Could you give me the steps I need to make a configuration file?

Thanks.

**Comment by yan12125** [comment]
youtube-dl configuiration files should be placed in system configuration folder or user profile directory depending on the operating system you use. See the link provided by @phihag for more information.

**Comment by audiogamer22** [comment]
Hi.

Thanks.

I'll stick to writing the commands for now.

You can close the ticket if you want.

**Comment by phihag** [comment]
@audiogamer22 The [linked FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration) contains more information about the configuration files. You did not tell us your operating system, but on Linux, you can just open any text editor (say, gedit on Ubuntu), create a new file with the contents
```
-o "%(title)s.%(ext)s"
```
and save it in `~/.config/youtube-dl.conf`.
