### ISSUE TITLE
Please set NSFW on before downloading from www.dumpert.nl

### ISSUE THREAD

**Issue by WuvorWenda** [rg3/youtube-dl#5382]
http://www.dumpert.nl/mediabase/6648816/615a5f67/gefeliciteerd_plafondtegel_.html
Snippet:
                       <section class="dump-cnt">
                                <article>
<p>Dit item is NSFW. Zeker weten? Klik dan bovenaan om NSFW items aan te zetten.</p>                            </article>
                        </section>
                </div>

**Comment by dstftw** [comment]
NSFW videos will work in the next version. Thanks for the report.
