### ISSUE TITLE
Unable to get url for youtube stream

### ISSUE THREAD

**Issue by dreamsivaraj** [rg3/youtube-dl#5384]
For the URL - https://www.youtube.com/watch?feature=player_embedded&v=BCIgLj5ANgI

I got the below as output when using 

youtube-dl.exe -g BCIgLj5ANgI

output:

https://manifest.googlevideo.com/api/manifest/hls_playlist/id/BCIgLj5ANgI.1/itag/94/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/gir/yes/dg_shard/QkNJ
Z0xqNUFOZ0kuMQ.94/hls_chunk_host/r16---sn-q0c7dn7s.googlevideo.com/pmbypass/yes/gcr/in/maudio/1/playlist_type/DVR/mm/32/ms/lv/mv/u/pl/24/dover/2/keepalive/yes/sver/3/fexp/900720,90
7263,932627,932631,934954,937837,9406673,9408107,9408196,9408249,9408349,9408879,947243,948124,948703,949432,951703,952011,952612,957201,961404,961406/upn/9vXZEa0VI5c/mt/1428572930
/ip/54.240.197.227/ipbits/0/expire/1428594675/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,gir,dg_shard,hls_chunk_host,pmbypass,gcr,maudio,playlist_t
ype,mm,ms,mv,pl/signature/244A85F6EA8DDE354BBC3DAE172F7E1D21E76056.6B2A64A550910C1397CD5E6517FFDC7898D2B839/key/dg_yt0/file/index.m3u8

which is not correct MP4 url.

**Comment by yan12125** [comment]
For live streams, only m3u8 manifests are available. Currently retrieving live videos or audios through DASH manifests is broken. By the way, for ordinary videos, URLs for mp4 files are not ended in ```.mp4```.
