### ISSUE TITLE
share video search API / extractors ?

### ISSUE THREAD

**Issue by xantares** [rg3/youtube-dl#5387]
I'm developing a small python gui using ydl to browse videos: https://github.com/xantares/maxitube and I've implemented some kind of video search lib based on ydl (by keywords) for a few sites (you can also list the videos on the homepage of a site).

There seem to be some kind of video search api:
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/common.py#L1104

Maybe this search API could be part of youtube-dl extractors in some way ? thoughts ?

**Comment by dstftw** [comment]
We already have a [youtube search extractor](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1494).

**Comment by xantares** [comment]
Ok, and yahoo, I see.
Is this as slow as ydl ? Currently, my extractors return a dict containing the url, title and thumbnail of the vid because without querying ydl for these attributes to be as responsive as possible.

**Comment by dstftw** [comment]
I have no idea how fast or slow youtube-dl is in comparison with your extractors. You can looks through the code and measure yourself. In any case, feel free to create a PR if you have something to add to youtube-dl.
