### ISSUE TITLE
Ooyala extractor failing

### ISSUE THREAD

**Issue by rschaosid** [rg3/youtube-dl#5392]
Unless I'm doing something wrong...

    $ youtube-dl --verbose http://player.ooyala.com/player.js?embedCode=gzN3g0MzqS56R9Yg77XVgFqBHibwI5fm
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'--verbose', u'http://player.ooyala.com/player.js?embedCode=gzN3g0MzqS56R9Yg77XVgFqBHibwI5fm']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.04.09
    [debug] Python version 2.7.6 - Linux-3.13.0-46-generic-x86_64-with-Ubuntu-14.04-trusty
    [debug] exe versions: avconv 9.16-6, avprobe 9.16-6, rtmpdump 2.4
    [debug] Proxy map: {}
    [Ooyala] gzN3g0MzqS56R9Yg77XVgFqBHibwI5fm: Downloading webpage
    [Ooyala] gzN3g0MzqS56R9Yg77XVgFqBHibwI5fm: Downloading mobile player JS for unknown device
    ERROR: Unable to download webpage: <urlopen error unknown url type: &device=%22+device+%22&domain=%22+(document.domain%7c%7c%22unknown%22);var%20commonutils=%7bseconds_of_day> (caused by URLError('unknown url type: &device=%22+device+%22&domain=%22+(document.domain%7c%7c%22unknown%22);var%20commonutils=%7bseconds_of_day',))
      File "/home/anders/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
        return self._downloader.urlopen(url_or_request)
      File "/home/anders/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1673, in urlopen
        return self._opener.open(req, timeout=self._socket_timeout)
      File "/usr/lib/python2.7/urllib2.py", line 404, in open
        response = self._open(req, data)
      File "/usr/lib/python2.7/urllib2.py", line 427, in _open
        'unknown_open', req)
      File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 1247, in unknown_open
        raise URLError('unknown url type: %s' % type)

**Comment by yan12125** [comment]
Can you watch the video in the browser? I got an "Account has been disabled." error.

**Comment by rschaosid** [comment]
Nah, I wouldn't even consider letting something like this have free reign in my browser. Closed.
