### ISSUE TITLE
Add official support for gfycat

### ISSUE THREAD

**Issue by woodenphone** [rg3/youtube-dl#5394]
While gfycat.com works at the moment, it is not listed in the supported sites.
Can it be officially maintained as a supported site, with detection of the highest quality version if that is possible?
Example video link:
http://gfycat.com/VainRichCub

**Comment by mandb** [comment]
does anybody have documentation on how to build an extractor? Can possibly do a PR.

**Comment by mandb** [comment]
added, PR #5439

**Comment by julianrichen** [comment]
I was working on this as well, guess you beat me to it! Regarding your pull it might be better to use the built in json api they have as it will cut down on the code.:
```
http://gfycat.com/cajax/get/<video_id>
```

The url `http://gfycat.com/cajax/get/RequiredUnkemptBuzzard` returns:
```json
{
  "gfyItem": {
    "gfyId": "requiredunkemptbuzzard",
    "gfyName": "RequiredUnkemptBuzzard",
    "gfyNumber": "607648367",
    "userName": "anonymous",
    "width": 600,
    "height": 338,
    "frameRate": 29,
    "numFrames": 180,
    "mp4Url": "http://fat.gfycat.com/RequiredUnkemptBuzzard.mp4",
    "webmUrl": "http://zippy.gfycat.com/RequiredUnkemptBuzzard.webm",
    "gifUrl": "http://giant.gfycat.com/RequiredUnkemptBuzzard.gif",
    "gifSize": 5935649,
    "mp4Size": 1740123,
    "webmSize": 749951,
    "createDate": "1422584031",
    "views": 492324,
    "title": "Headshot!",
    "extraLemmas": null,
    "md5": "5dd3ed3ff36e37839cb11fb2faeff3a5",
    "tags": null,
    "nsfw": "0",
    "likes": "6",
    "dislikes": 0,
    "published": 1,
    "description": null,
    "copyrightClaimaint": null,
    "sar": "1",
    "url": "https://i.4cdn.org/wsg/1422071452954.webm",
    "source": "1",
    "dynamo": null,
    "subreddit": "all",
    "redditId": "32ol2t",
    "redditIdText": "a_skillful_headshot",
    "uploadGifName": null
  }
}
```
Might still make a pr if the api json version is prefered, not finished coding it.

**Comment by mandb** [comment]
if there's json readily available probably best to use that, you can recycle the url match regex and extension preference.

**Comment by dstftw** [comment]
Gfycat will be supported in the next version. Thanks for the report.

**Comment by dstftw** [comment]
Support for gfycat has been added in youtube-dl 2015.04.26. See our [FAQ](https://yt-dl.org/update) if you have problems updating.
