### ISSUE TITLE
How to bypass "click to view" sites

### ISSUE THREAD

**Issue by Khav21** [rg3/youtube-dl#5402]
I am currently trying my first python code which is going to be a youtube-dl extractor for python.However can anyone give me an insight on how to i stimulate the "Proceed to video feature" so that the plugin works

Here is what i attempted so far

https://github.com/Khav21/youtube-dl/blob/master/youtube_dl/extractor/exashare.py

Kind Regards

**Comment by dstftw** [comment]
Take a look at [gorillavid extractor](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/gorillavid.py).
