### ISSUE TITLE
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5405]
URL: https://www.youtube.com/watch?v=2XxkIjE1xQc

C:\>youtube-dl -v "https://www.youtube.com/watch?v=2XxkIjE1xQc"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=2XxkIjE1xQc
']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20
[debug] Proxy map: {}
[youtube] 2XxkIjE1xQc: Downloading webpage
[youtube] 2XxkIjE1xQc: Downloading video info webpage
[youtube] 2XxkIjE1xQc: Extracting video information
[youtube] 2XxkIjE1xQc: Downloading formats manifest
[youtube] 2XxkIjE1xQc: Downloading DASH manifest
[debug] Invoking downloader on u'https://manifest.googlevideo.com/api/manifest/h
ls_playlist/id/2XxkIjE1xQc.1/itag/95/source/yt_live_broadcast/requiressl/yes/rat
ebypass/yes/live/1/cmbypass/yes/gir/yes/dg_shard/Mlh4a0lqRTF4UWMuMQ.95/hls_chunk
_host/r8---sn-ni5f-t8ge.googlevideo.com/maudio/1/gcr/ca/pmbypass/yes/playlist_ty
pe/DVR/mm/32/ms/lv/mv/u/pl/22/dover/2/sver/3/fexp/900720,907263,916942,923384,93
2627,932631,934954,937432,938812,9406010,9406996,9408347,9408472,9408628,9408704
,9408919,947243,948124,948703,951703,952612,957201,958400,961404,961406,962731/u
pn/6HzFniqhHgs/mt/1428797460/ip/24.108.145.53/ipbits/0/expire/1428819273/sparams
/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,gir,dg_shar
d,hls_chunk_host,maudio,gcr,pmbypass,playlist_type,mm,ms,mv,pl/signature/6C8344F
13F29D521CD3233274E95EFE6815EF084.3BB69CB1F0294C6DDAC292C08348C7234D4A19B8/key/d
g_yt0/file/index.m3u8'
[download] Destination: ATLANTA SILVERBACKS -V- OTTAWA FURY FC-2XxkIjE1xQc.mp4
ffmpeg version N-40824-g31dfe20 Copyright (c) 2000-2012 the FFmpeg developers
  built on May 19 2012 00:45:59 with gcc 4.6.3
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-ru
ntime-cpudetect --enable-avisynth --enable-bzlib --enable-frei0r --enable-libass
 --enable-libcelt --enable-libopencore-amrnb --enable-libopencore-amrwb --enable
-libfreetype --enable-libgsm --enable-libmp3lame --enable-libnut --enable-libope
njpeg --enable-librtmp --enable-libschroedinger --enable-libspeex --enable-libth
eora --enable-libutvideo --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-
libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --e
nable-zlib
  libavutil      51. 53.100 / 51. 53.100
  libavcodec     54. 21.101 / 54. 21.101
  libavformat    54.  5.100 / 54.  5.100
  libavdevice    53.  4.100 / 53.  4.100
  libavfilter     2. 74.101 /  2. 74.101
  libswscale      2.  1.100 /  2.  1.100
  libswresample   0. 12.100 /  0. 12.100
  libpostproc    52.  0.100 / 52.  0.100
https://manifest.googlevideo.com/api/manifest/hls_playlist/id/2XxkIjE1xQc.1/itag
/95/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/g
ir/yes/dg_shard/Mlh4a0lqRTF4UWMuMQ.95/hls_chunk_host/r8---sn-ni5f-t8ge.googlevid
eo.com/maudio/1/gcr/ca/pmbypass/yes/playlist_type/DVR/mm/32/ms/lv/mv/u/pl/22/dov
er/2/sver/3/fexp/900720,907263,916942,923384,932627,932631,934954,937432,938812,
9406010,9406996,9408347,9408472,9408628,9408704,9408919,947243,948124,948703,951
703,952612,957201,958400,961404,961406,962731/upn/6HzFniqhHgs/mt/1428797460/ip/2
4.108.145.53/ipbits/0/expire/1428819273/sparams/ip,ipbits,expire,id,itag,source,
requiressl,ratebypass,live,cmbypass,gir,dg_shard,hls_chunk_host,maudio,gcr,pmbyp
ass,playlist_type,mm,ms,mv,pl/signature/6C8344F13F29D521CD3233274E95EFE6815EF084
.3BB69CB1F0294C6DDAC292C08348C7234D4A19B8/key/dg_yt0/file/index.m3u8: Protocol n
ot found

ERROR: ffmpeg exited with code 1
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 404, in main
  File "youtube_dl\__init__.pyo", line 394, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1446, in download
  File "youtube_dl\YoutubeDL.pyo", line 662, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 708, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1150, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1379, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1354, in dl
  File "youtube_dl\downloader\common.pyo", line 341, in download
  File "youtube_dl\downloader\hls.pyo", line 50, in real_download
  File "youtube_dl\downloader\common.pyo", line 154, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 529, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 491, in trouble

Thanks
Ringo

**Comment by dstftw** [comment]
Works pefectly for me. Try updating ffmpeg.

**Comment by RingoTheDog** [comment]
"You are correct sir!"...newer version of FFMPEG fixed it.

sry to bother...pls close issue.

thank you
