### ISSUE TITLE
Setting format=worst downloads audio from youtube

### ISSUE THREAD

**Issue by hashken** [rg3/youtube-dl#5408]
Steps to reproduce:
* Run `youtube-dl -f worst https://www.youtube.com/watch?v=HooDdn_cuZs`.
* A webm file will be downloaded.
* Opening with mpv or vlc plays only audio with no video.
* Running without `-f worst` option downloads proper video file.

When setting `-f worst` option, the user expects to get the worst video format, not an audio format.

**Comment by dstftw** [comment]
In the next version `-f worst` will download worst audio+video media served as a single file. Thanks for the report.
