### ISSUE TITLE
Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url

### ISSUE THREAD

**Issue by arussell004** [rg3/youtube-dl#5409]
sudo youtube-dl -U
youtube-dl is up-to-date (2015.04.09)

 youtube-dl --verbose -t "https://www.youtube.com/watch?v=FWRJ5SByuGc"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-t', u'https://www.youtube.com/watch?v=FWRJ5SByuGc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.6 - Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg 2.5.git, ffprobe 2.5.git
[debug] Proxy map: {}
[youtube] FWRJ5SByuGc: Downloading webpage
[youtube] FWRJ5SByuGc: Extracting video information
WARNING: [youtube] FWRJ5SByuGc: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r14---sn-a5mekm7e.googlevideo.com/videoplayback?requiressl=yes&ms=pm&mv=s&mt=1428831144&ip=204.251.33.100&key=yt5&mime=video%2Fmp4&upn=vprZvJDmtR8&id=o-APBcp0IOUyXZP3jbkUryxeZzAN1LvQHKLL2c50391m0M&sparams=dur%2Cid%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ratebypass=yes&sver=3&signature=3609E047431EB1BB01E9F066A1FE125EEE5456B5.2D4AFBABFEEDC5D5BFA2680E6051B631F79767BB&expire=1428860744&ipbits=0&source=youtube&itag=22&pl=22&dur=174.405&nh=EAU&fexp=900720%2C905649%2C907263%2C932627%2C932631%2C933236%2C934954%2C9405970%2C9406631%2C9407714%2C9408347%2C9408704%2C9408778%2C9408787%2C9408880%2C9408919%2C947243%2C948124%2C948703%2C951703%2C952612%2C956001%2C956002%2C957201%2C961404%2C961406&mm=35'
[download] Destination: Bitten Banter - Teddy Asks-FWRJ5SByuGc.mp4
[download] 100% of 28.71MiB in 00:07

**Comment by dstftw** [comment]
Works fine with latest version (2016.05.16).
