### ISSUE TITLE
[adultswim] An extractor error has occured. (caused by KeyError(u'clips',));

### ISSUE THREAD

**Issue by julianrichen** [rg3/youtube-dl#5413]
**OS:** Linux 3.16 / Debian 8
**yt-dl:** 2015.04.09
**Python:** 2.7.9
**Site:** adultswim.com

> ERROR: An extractor error has occured. (caused by KeyError(u'clips',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Error seems to be random and yt-dl will work on some videos but not others.

Example of non-working video: http://www.adultswim.com/videos/rick-and-morty/pilot/
All other videos download on that page.

Verbose output:
```
$ youtube-dl http://www.adultswim.com/videos/rick-and-morty/pilot/ -F --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.adultswim.com/videos/rick-and-morty/pilot/', u'-F', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg 2.6.1-1, ffprobe 2.6.1-1, rtmpdump 2.4
[debug] Proxy map: {}
[AdultSwim] pilot: Downloading webpage
ERROR: An extractor error has occured. (caused by KeyError(u'clips',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adultswim.py", line 136, in _real_extract
    segment_ids = [clip['videoPlaybackID'] for clip in video_info['clips']]
KeyError: u'clips'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 281, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'clips',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

If I had to take a guess at the issue I would say it's parsing the json wrong and not extract the video id correctly.

**Comment by dstftw** [comment]
http://www.adultswim.com/videos/rick-and-morty/pilot/ is not available without signing in with one of the listed cable service providers. Downloading videos that require a cable provider login is not supported.

**Comment by julianrichen** [comment]
Ahh, I browse with JavaScript disabled which apparently needs to be on for the icon to be visible -_- Did not even know it required a cable provider until turning it on.

Sorry about wasting your time!
