### ISSUE TITLE
Error with work in bash script

### ISSUE THREAD

**Issue by WarmongeR1** [rg3/youtube-dl#5415]
Hi all,

I have bash script:

```python
#!/bin/bash

QUEUE_DIR=~/Dropbox/IFTTT/youtube-dl/*.txt
VIDEO_DIR=~/Video/Youtube/
shopt -s nullglob

for queue_file in $QUEUE_DIR
do
    video_url=`cat "$queue_file"`;
    echo "$queue_file : $video_url";
    mv "$queue_file" "${queue_file}.in_proccess";
    youtube-dl --default-search "ytsearch" -o "$VIDEO_DIR%(title)s.%(ext)s" "$video_url" && mv "${queue_file}.in_proccess" "${queue_file}.success"; 
    rm -f "${queue_file}.success";
done
```
(in txt lines - urls to videos)

and cronline , for example
* * * * * bash path_to_bash_file

This script used to work. But now is not working. He runs, renames files, and then exits without error. If I run the script manually, everything works fine.

Youtube-dl stopped working in background?

**Comment by jaimeMF** [comment]
[Post the output with the --verbose option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) and explain with detail what's your exact problem.

**Comment by WarmongeR1** [comment]
I run this line

```bash
youtube-dl --verbose -o test.mp4 http://www.youtube.com/watch?v=zNfTaN76kBk&feature=youtube_gdata  >> log_file.log
```

If i run manualy, i have get file. But if run this line with crontab...i don't have file and logs. 

Magic!


```bash
uname -a:
Linux work-laptop 3.16.0-33-generic #44~14.04.1-Ubuntu SMP Fri Mar 13 10:33:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

youtube-dl --version
2015.04.09
```

**Comment by dstftw** [comment]
I bet this is due to unescaped `&`.

**Comment by dstftw** [comment]
Redirect stderr and stdout to log file by changing cron task to `* * * * * path_to_bash_file >> path_to_log_file 2>&1` and check out the log.

**Comment by WarmongeR1** [comment]
Wow!
I got this error:
```
....dropbox_youtube_dl.sh: line 21: youtube-dl: command not found
```
but i have youtube-dl:
```bash
> youtube-dl                                                                                              
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```

Thanks! Now the problem can be solved
