### ISSUE TITLE
ERROR Http 404

### ISSUE THREAD

**Issue by RReznik** [rg3/youtube-dl#5416]
I just started getting the following error when trying to download videos from any channel:

ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Please post the full log [with --verbose option](https://github.com/rg3/youtube-dl#bugs)

**Comment by dstftw** [comment]
Closing due to insufficient info. Feel free to open a new issue with [full `--verbose` log](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).
