### ISSUE TITLE
No "upload_date" in json dump of "TED" videos

### ISSUE THREAD

**Issue by kuerbis** [rg3/youtube-dl#5418]
if youtube-dl --dump-json http://www.ted.com/watch/ted-institute/ted-bcg/vishal-sikka-the-beauty-and-power-of-algorithms | grep -q upload_date
    then
        echo "Yes"
    else
        echo "No"
    fi

This returns "No".

**Comment by dstftw** [comment]
Obviously, because there is no `upload_date` available on this page.
