### ISSUE TITLE
Youtube username and password are not applied to all links in batch file

### ISSUE THREAD

**Issue by tanmahah** [rg3/youtube-dl#5422]
I'm trying to download videos from youtube with youtube-dl.
I've provided a text file to extract URL with -a.
I also provided --username and --password, but it appears that youtube-dl applied my credentials to only first download and hence for other few videos, I'm getting 'Please sign in to view this videos'.
Please, tell me how to ask youtube-dl to apply the same Username and Password to all links provided in text file.

**Comment by yan12125** [comment]
Try the ```--netrc``` option

**Comment by tanmahah** [comment]
Yes, I just learn how to create .netrc file and used the option. I've to remove the --username --password from command, so that it doesn't conflict with --netrc.
I appears to work. I'll let you know if I face any problem.

**Comment by yan12125** [comment]
Closing. If you encounter any other problem, feel free to open new issues.
