### ISSUE TITLE
Firefox extension?

### ISSUE THREAD

**Issue by andreslsuave** [rg3/youtube-dl#5426]
Hi there! Any plans to develop a firefox extension or some kind of front-end? 

Thank you!

EDIT: A firefox addon that can be customized to use youtube-dl would be appreciated too

**Comment by snipem** [comment]
This would be essentially a plugin that invokes `youtube_dl $currently_displayed_page_url`

**Comment by jaimeMF** [comment]
No, youtube-dl is a command line program and we also expose a python library, but as fas as I know we don't plan to develop an "official" extension/gui. But you (or someone else) can write it and share it. (If you just want a gui, there are some: like [this one](https://github.com/MrS0m30n3/youtube-dl-gui))

**Comment by js017** [comment]
How come the Download with youtube-dl 0.1.5a add-on from https://addons.mozilla.org/en-US/firefox/addon/download-with-youtube-dl/ doesn't work with the latest version of Firefox? Thanks.

**Comment by dstftw** [comment]
Ask its developer why.

**Comment by js017** [comment]
How do I contact the developer?
