### ISSUE TITLE
[Playwire] Support for "//config..." urls

### ISSUE THREAD

**Issue by snipem** [rg3/youtube-dl#5430]
Some websites offer Playwire videos only by referencing the video URL as "//config...." rather than the full qualified "http://config..." to the same video. 

The extractor should also support URLs missing the leading "http".

**Comment by yan12125** [comment]
Please [provide an example URL](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient) so that we can test it.

**Comment by snipem** [comment]
For some reason its working now.

I got the link from this site: http://www.cinemablend.com/new/First-Joe-Dirt-2-Trailer-Teaser-Stupid-Greatness-70874.html

```
$ youtube-dl -v "//config.playwire.com/25130/videos/v2/3519514/zeus.json"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'//config.playwire.com/25130/videos/v2/3519514/zeus.json']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1
[debug] Proxy map: {}
[Playwire] 3519514: Downloading JSON metadata
[Playwire] 3519514: Downloading XML
[debug] Invoking downloader on u'http://cdn.phoenix.intergi.com/25130/videos/3519514/video-hd.mp4?hosting_id=25130'
[download] Destination: Joe Dirt 2 Beautiful Loser Teaser Trailer-3519514.mp4
[download] 100% of 8.55MiB in 00:06
```

**Comment by snipem** [comment]
Thank you

**Comment by dstftw** [comment]
Playwire embeds will be supported in the next version. Thanks for the report.
