### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by cub-uanic** [rg3/youtube-dl#5431]
tux ~ % youtube-dl --version
2014.10.15
tux ~ % youtube-dl -x --audio-format mp3 --audio-quality 0 'https://www.youtube.com/watch?v=VwjwKn9ARzY'
[youtube] Setting language
[youtube] Confirming age
[youtube] VwjwKn9ARzY: Downloading webpage
[youtube] VwjwKn9ARzY: Downloading video info webpage
[youtube] VwjwKn9ARzY: Extracting video information
[youtube] VwjwKn9ARzY: Encrypted signatures detected.
[youtube] VwjwKn9ARzY: Downloading js player vflWLYnud
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/cub/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 533, in _decrypt_signature
    video_id, player_url, s
  File "/home/cub/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 447, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/cub/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 508, in _parse_sig_js
    'Initial JS player signature function name')
  File "/home/cub/bin/youtube-dl/youtube_dl/extractor/common.py", line 424, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.',)); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
You are using a very __OLD__ version of youtube-dl. Please update it following [the instructions](https://github.com/rg3/youtube-dl#faq).
