### ISSUE TITLE
--embed-subs behaviour is inconsistent with default --keep-video behaviour

### ISSUE THREAD

**Issue by Nikoli** [rg3/youtube-dl#5435]
Subtitles should be removed when --embed-subs option is used without --keep-video

Similar to https://github.com/rg3/youtube-dl/issues/2108

**Comment by jaimeMF** [comment]
They will be deleted in the next version, thanks for the report.

**Comment by dstftw** [comment]
This has been fixed in youtube-dl 2015.04.26. See our [FAQ](https://yt-dl.org/update) if you have problems updating.
