### ISSUE TITLE
Failed to download a NY Times video

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5436]
URL:  http://www.nytimes.com/2015/04/14/business/owner-of-gravity-payments-a-credit-card-processor-is-setting-a-new-minimum-wage-70000-a-year.html?_r=0

youtube-dl.py -v "http://www.nytimes.com/2015/04/14/business/o
wner-of-gravity-payments-a-credit-card-processor-is-setting-a-new-minimum-wage-7
0000-a-year.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.nytimes.com/2015/04/14/business/
owner-of-gravity-payments-a-credit-card-processor-is-setting-a-new-minimum-wage-
70000-a-year.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.6 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20, rtmpdump 2.4
[debug] Proxy map: {}
[generic] owner-of-gravity-payments-a-credit-card-processor-is-setting-a-new-min
imum-wage-70000-a-year: Requesting header
[redirect] Following redirect to http://www.nytimes.com/2015/04/14/business/owne
r-of-gravity-payments-a-credit-card-processor-is-setting-a-new-minimum-wage-7000
0-a-year.html?_r=0
[generic] owner-of-gravity-payments-a-credit-card-processor-is-setting-a-new-min
imum-wage-70000-a-year: Requesting header
WARNING: Falling back on generic information extractor.
[generic] owner-of-gravity-payments-a-credit-card-processor-is-setting-a-new-min
imum-wage-70000-a-year: Downloading webpage
[generic] owner-of-gravity-payments-a-credit-card-processor-is-setting-a-new-min
imum-wage-70000-a-year: Extracting information
ERROR: Unsupported URL: http://www.nytimes.com/2015/04/14/business/owner-of-grav
ity-payments-a-credit-card-processor-is-setting-a-new-minimum-wage-70000-a-year.
html?_r=0
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 8
58, in _real_extract
    doc = parse_xml(webpage)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\utils.py", line 1531, in pars
e_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 2, column 352
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 651, in e
xtract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 27
5, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 1
364, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.nytimes.com/2015/04/14/business/ow
ner-of-gravity-payments-a-credit-card-processor-is-setting-a-new-minimum-wage-70
000-a-year.html?_r=0

Thanks
Ringo

**Comment by yan12125** [comment]
Thanks for the report. Videos in New York Times articles will be correctly extracted in the next version.
