### ISSUE TITLE
youtube : script stops while downloading a playlist if a video in playlist is not available 

### ISSUE THREAD

**Issue by itsyash** [rg3/youtube-dl#5437]
while downloading a playlist from youtube, if a video in between the playlist is not available due to any reason, the script stops. Instead, I think it should jump to downloading the next video.

One of the possible error for a video being not available : *The YouTube account associated with this video has been terminated due to multiple third-party notifications of copyright infringement.*

**Comment by jaimeMF** [comment]
Add the `--ignore-errors` option, it may become the default in the future.

**Comment by dandv** [comment]
+1 for making this the default, and reporting errors at the end.
