### ISSUE TITLE
Unable to extract like count on Mixcloud

### ISSUE THREAD

**Issue by revolter** [rg3/youtube-dl#5442]
Upon trying to download [this mix][1] from Mixcloud, I got this in the console:

```
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Downloading webpage
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 1/31 ...
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 2/31 ...
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 3/31 ...
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 4/31 ...
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 5/31 ...
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 6/31 ...
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 7/31 ...
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 8/31 ...
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 9/31 ...
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 10/31 ...
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 11/31 ...
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 12/31 ...
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 13/31 ...
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 14/31 ...
WARNING: unable to extract like count; please report this issue on http://yt-dl.org/bug
[download] Destination: Sebastian Ingrosso - Live @ TomorrowWorld (Atlanta) - 27-09-2013-livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013.mp3
```

Firstly, why is it trying to extract the like count? I didn't use any optional parameters.

And secondly, why did the output stopped at `Checking URL 14/31 ...`? Right now it's downloading, does that mean that it will download only a part of it?

  [1]: https://www.mixcloud.com/livesetsdjmixes/sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013

**Comment by jaimeMF** [comment]
I think you are using an outdated version, please [post the output with the --verbose option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) to check it.

> Firstly, why is it trying to extract the like count? I didn't use any optional parameters.

Unless its expensive to get an specific information, we extract it by default. But as you can see it doesn't produces an error.

> And secondly, why did the output stopped at Checking URL 14/31 ...? Right now it's downloading, does that mean that it will download only a part of it?

Probably the wording is not perfect: we have to check multiple urls because we don't know which one is right. If you have a better wording, please share it.

**Comment by revolter** [comment]
> I think you are using an outdated version, please post the output with the --verbose option to check it.

Here it is:
```
debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.mixcloud.com/livesetsdjmixes/sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.09
[debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3
[debug] Proxy map: {}
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Downloading webpage
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 1/31 ...
```
But yes, I am using an outdated version. Isn't it possible to check for updated when you use it? So it would show something like this:
```
WARNING: You are using an outdated version. Please update using youtube-dl -U
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Downloading webpage
[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Checking URL 1/31 ...
```
> Unless its expensive to get an specific information, we extract it by default. But as you can see it doesn't produces an error.

I understand.

> Probably the wording is not perfect: we have to check multiple urls because we don't know which one is right. If you have a better wording, please share it.

Hmmm, something like `[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Searching URL 8/31 for video ...`.
Or/and add another log at the end that looks like this: `[mixcloud] livesetsdjmixes-sebastian-ingrosso-tomorrowworld-live-set-atlanta-27-09-2013: Matched URL 8/31 from webpage as the video URL`.
It is indeed hard to explain, but it was confusing before knowing what it meant, but I think these examples make is a slight understandable.

**Comment by jaimeMF** [comment]
> Isn't it possible to check for updated when you use it? So it would show something like this:

It will suggest updating in the next version, thanks for the suggestion.


I have simplify the logic and we only check with two urls now, I think it's clear now:
```
[mixcloud] ...: Trying mp3 URL
[mixcloud] ...: Trying m4a URL
```
