### ISSUE TITLE
MLB Extractor issue...

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5443]
All 3 URLs display / forward to same video:

http://m.mlb.com/news/article/118550098/blue-jays-kevin-pillar-goes-spidey-up-the-wall-to-rob-tim-beckham-of-a-homer

http://www.bluejays.mlb.com/news/article/118550098/blue-jays-kevin-pillar-goes-spidey-up-the-wall-to-rob-tim-beckham-of-a-homer

http://mlb.mlb.com/news/article.jsp?ymd=20150415&content_id=118550098&vkey=news_tor&c_id=tor

All 3 URLs fall back to generic extractor

youtube-dl.py -v "http://m.mlb.com/news/article/118550098/blue-jays-kevin-pi
llar-goes-spidey-up-the-wall-to-rob-tim-beckham-of-a-homer"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://m.mlb.com/news/article/118550098/blu
e-jays-kevin-pillar-goes-spidey-up-the-wall-to-rob-tim-beckham-of-a-homer']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.6 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-34549-g13b7781, rtmpdump 2.4
[debug] Proxy map: {}
[generic] blue-jays-kevin-pillar-goes-spidey-up-the-wall-to-rob-tim-beckham-of-a
-homer: Requesting header
WARNING: Falling back on generic information extractor.
[generic] blue-jays-kevin-pillar-goes-spidey-up-the-wall-to-rob-tim-beckham-of-a
-homer: Downloading webpage
[generic] blue-jays-kevin-pillar-goes-spidey-up-the-wall-to-rob-tim-beckham-of-a
-homer: Extracting information
ERROR: Unsupported URL: http://m.mlb.com/news/article/118550098/blue-jays-kevin-
pillar-goes-spidey-up-the-wall-to-rob-tim-beckham-of-a-homer
Traceback (most recent call last):
  File "C:\TRANSMOGRIFIER\youtube-dl.py\youtube_dl\extractor\generic.py", line 8
58, in _real_extract
    doc = parse_xml(webpage)
  File "C:\TRANSMOGRIFIER\youtube-dl.py\youtube_dl\utils.py", line 1531, in pars
e_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 59, column 64
Traceback (most recent call last):
  File "C:\TRANSMOGRIFIER\youtube-dl.py\youtube_dl\YoutubeDL.py", line 651, in e
xtract_info
    ie_result = ie.extract(url)
  File "C:\TRANSMOGRIFIER\youtube-dl.py\youtube_dl\extractor\common.py", line 27
5, in extract
    return self._real_extract(url)
  File "C:\TRANSMOGRIFIER\youtube-dl.py\youtube_dl\extractor\generic.py", line 1
364, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://m.mlb.com/news/article/118550098/blue-
jays-kevin-pillar-goes-spidey-up-the-wall-to-rob-tim-beckham-of-a-homer

Thanks 
Ringo

**Comment by yan12125** [comment]
Thanks for the report. youtube-dl will support these videos in the next version.
