### ISSUE TITLE
HTTP Error 429.

### ISSUE THREAD

**Issue by AndreyGermanov** [rg3/youtube-dl#5445]
Trying to download using Python 3.3. Receive this error with newest version of Youtube-dl.

Complete output:

[root@localhost ~]# python3.3 /usr/local/bin/youtube-dl --verbose https://www.youtube.com/watch?v=Gc2en3nHxA4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=Gc2en3nHxA4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 3.3.6 - Linux-2.6.32-504.8.1.el6.x86_64-x86_64-with-centos-6.6-Final
[debug] exe versions: ffmpeg N-69745-gb533949, ffprobe N-69745-gb533949
[debug] Proxy map: {}
[youtube] Gc2en3nHxA4: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1673, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.3/urllib/request.py", line 475, in open
    response = meth(req, response)
  File "/usr/lib64/python3.3/urllib/request.py", line 587, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.3/urllib/request.py", line 513, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 595, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by dstftw** [comment]
Please [read our FAQ entry for the issue](https://github.com/rg3/youtube-dl/blob/master/README.md#http-error-429-too-many-requests-or-402-payment-required), you have probably downloaded too much content and Youtube is blocking your IP.
