### ISSUE TITLE
Document and make default --format='bestvideo+bestaudio/best'

### ISSUE THREAD

**Issue by Nikoli** [rg3/youtube-dl#5447]
Please document ```--format='bestvideo+bestaudio/best'``` in man page and consider making it default.

**Comment by jaimeMF** [comment]
It will be the default in the next version and it's mentioned in the docs. Thanks for the report.

**Comment by rbrito** [comment]
@jaimeMF, when is "the next version"? :) I would love to know when I should package/upload a new version to Debian. :)

**Comment by jaimeMF** [comment]
When Philip has some free time for it.

**Comment by rbrito** [comment]
Thanks. I hope that we have a new release soon.

**Comment by dstftw** [comment]
This has been fixed in youtube-dl 2015.04.26. See our [FAQ](https://yt-dl.org/update) if you have problems updating.
