### ISSUE TITLE
ERROR: Vimple Unable to extract player url;

### ISSUE THREAD

**Issue by winwon** [rg3/youtube-dl#5448]
Vimple does not work and giving the following error message.
ERROR: Unable to extract player url;

**Comment by jaimeMF** [comment]
[Post the **full output** you get with the --verbose option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs)

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.

**Comment by dstftw** [comment]
This has been fixed in youtube-dl 2015.04.26. See our [FAQ](https://yt-dl.org/update) if you have problems updating.
