### ISSUE TITLE
The Daily Show extractor error

### ISSUE THREAD

**Issue by 6461** [rg3/youtube-dl#5449]
python youtube-dl --verbose http://thedailyshow.cc.com/full-episodes/9q0y2l/april-15--2015---billy-crystal
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://thedailyshow.cc.com/full-episodes/9q0y2l/april-15--2015---billy-crystal
']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.04.09
[debug] Python version 3.3.2 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-69060-gcd960c8, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentralShows] april-15--2015---billy-crystal: Downloading webpage
[ComedyCentralShows] april-15--2015---billy-crystal: Downloading show index
Traceback (most recent call last):
  File "C:\Python33\lib\runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python33\lib\runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "youtube-dl\__main__.py", line 19, in <module>
  File "youtube-dl\youtube_dl\__init__.py", line 404, in main
  File "youtube-dl\youtube_dl\__init__.py", line 394, in _real_main
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 1446, in download
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 651, in extract_info
  File "youtube-dl\youtube_dl\extractor\common.py", line 275, in extract
  File "youtube-dl\youtube_dl\extractor\comedycentral.py", line 218, in _real_extract
AttributeError: 'NoneType' object has no attribute 'attrib'

**Comment by jspenguin** [comment]
I have a similar problem, but I get a different error:

    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'http://thedailyshow.cc.com/full-episodes/9q0y2l/april-15--2015---billy-crystal', u'--verbose']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.04.09
    [debug] Python version 2.7.6 - Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty
    [debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.3, ffprobe 2.3, rtmpdump 2.4
    [debug] Proxy map: {}
    [ComedyCentralShows] april-15--2015---billy-crystal: Downloading webpage
    [ComedyCentralShows] april-15--2015---billy-crystal: Downloading show index
    [ComedyCentralShows] april-15--2015---billy-crystal: Downloading configuration for segment 1 / 4
    [ComedyCentralShows] april-15--2015---billy-crystal: Downloading configuration for segment 2 / 4
    [ComedyCentralShows] april-15--2015---billy-crystal: Downloading configuration for segment 3 / 4
    [ComedyCentralShows] april-15--2015---billy-crystal: Downloading configuration for segment 4 / 4
    [download] Downloading playlist: thedailyshow April 15, 2015 - Billy Crystal
    [ComedyCentralShows] playlist thedailyshow April 15, 2015 - Billy Crystal: Collected 4 video ids (downloading 4 of them)
    [download] Downloading video 1 of 4
    ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/home/jspenguin/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 662, in extract_info
        return self.process_ie_result(ie_result, download, extra_info)
      File "/home/jspenguin/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 821, in process_ie_result
        extra_info=extra)
      File "/home/jspenguin/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 708, in process_ie_result
        return self.process_video_result(ie_result, download=download)
      File "/home/jspenguin/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1047, in process_video_result
        raise ExtractorError('No video formats found!')
    ExtractorError: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by malept** [comment]
What happens (just for the Daily Show, not for any of the other CC programs I tried) is that when the segment configuration is downloaded, it returns a short XML document with the following text:
> Sorry, this video is not found or no longer available due to date or rights restrictions.

Part of the reason might be that the `media:content[url]` ends with `device={device}`, and presumably the app needs to replace `{device}` with something valid. Though, when I tried using `curl` to retrieve the URL by replacing it with `Android`, nothing changed.

**Comment by 6461** [comment]
I also tried to use the email shareable url and got a different error:
ERROR: unable to find Flash URL in webpage

python youtube-dl -vt http://on.cc.com/1JMloyv
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vt', 'http://on.cc.com/1JMloyv']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.04.09
[debug] Python version 3.3.2 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-69060-gcd960c8, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 1JMloyv: Requesting header
[redirect] Following redirect to http://thedailyshow.cc.com/episodes/9q0y2l/april-15--2015---billy-crystal?xrs=share_cop
y_email
[ComedyCentralShows] april-15--2015---billy-crystal?xrs=share_copy_email: Downloading webpage
ERROR: unable to find Flash URL in webpage http://thedailyshow.cc.com/episodes/9q0y2l/april-15--2015---billy-crystal?xrs
=share_copy_email; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type
 youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "youtube-dl\youtube_dl\extractor\common.py", line 275, in extract
    return self._real_extract(url)
  File "youtube-dl\youtube_dl\extractor\comedycentral.py", line 198, in _real_extract
    raise ExtractorError('unable to find Flash URL in webpage ' + url)
youtube_dl.utils.ExtractorError: unable to find Flash URL in webpage http://thedailyshow.cc.com/episodes/9q0y2l/april-15
--2015---billy-crystal?xrs=share_copy_email; please report this issue on https://yt-dl.org/bug . Make sure you are using
 the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its
complete output.

**Comment by jspenguin** [comment]
Looking at the requests made when viewing in Firefox, it looks like it sets "device" to "Other":

http://media-utils.mtvnservices.com/services/MediaGenerator/mgid%3Aarc%3Aepisode%3Athedailyshow.com%3A747850e6-d6ca-409e-b92f-105c30d9585a?device=Other&acceptMethods=fms,hdn1,hds&cdnOverride=akamai

**Comment by jspenguin** [comment]
The problem is that the playlist URL youtube-dl requests contains "thedailyshow.cc.com" and the flash player requests "thedailyshow.com" (without "cc").

I've made a quick patch which solves the problem for now, though I'm not sure it works as a permanent solution:

https://github.com/jspenguin/youtube-dl/commit/510997866d7349b6b7f29f60f8c06c45d8e831c9

**Comment by malept** [comment]
That changeset worked for me.

**Comment by falkTX** [comment]
I can also confirm the fix works, thanks.

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.

**Comment by helpdeskdan** [comment]
Pardon ignorance - am I doing something wrong?  

$ python __main__.py -F "http://thedailyshow.cc.com/full-episodes/9q0y2l/april-15--2015---billy-crystal"
WARNING: Falling back on generic information extractor.
[generic] april-15--2015---billy-crystal: Downloading webpage
[generic] april-15--2015---billy-crystal: Extracting information
ERROR: Invalid URL: http://thedailyshow.cc.com/full-episodes/9q0y2l/april-15--2015---billy-crystal; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
dan@dan-Dell-DM061:~/temp/youtube-dl/youtube_dl$ vim extractor/comedycentral.py dan@dan-Dell-DM061:~/temp/youtube-dl/youtube_dl$ python __main__.py -F --verbose "http://thedailyshow.cc.com/full-episodes/9q0y2l/april-15--2015---billy-crystal"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', '--verbose', 'http://thedailyshow.cc.com/full-episodes/9q0y2l/april-15--2015---billy-crystal']
[debug] youtube-dl version 2013.09.16
[debug] Python version 2.7.6 - Linux-3.13.0-49-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
[generic] april-15--2015---billy-crystal: Downloading webpage
[generic] april-15--2015---billy-crystal: Extracting information
ERROR: Invalid URL: http://thedailyshow.cc.com/full-episodes/9q0y2l/april-15--2015---billy-crystal; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 325, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 103, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 163, in _real_extract
    raise ExtractorError(u'Invalid URL: %s' % url)
ExtractorError: Invalid URL: http://thedailyshow.cc.com/full-episodes/9q0y2l/april-15--2015---billy-crystal; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
This has been fixed in youtube-dl 2015.04.26. See our [FAQ](https://yt-dl.org/update) if you have problems updating.
