### ISSUE TITLE
Support for stoneriveracademy

### ISSUE THREAD

**Issue by crootman** [rg3/youtube-dl#5451]
Can you please add support for http://stoneriveracademy.com/

**Comment by jaimeMF** [comment]
[Post an example url](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient)

**Comment by thecoder987** [comment]
https://stoneriveracademy.com/courses/learn-the-unity-3d-shuriken-particle-system

But you need a login

**Comment by TRox1972** [comment]
Requires account
