### ISSUE TITLE
soundcloud secret playlists don't work anymore

### ISSUE THREAD

**Issue by LaHaine** [rg3/youtube-dl#5453]
This used to work, maybe soundcloud has changed something?

% youtube-dl --verbose "https://w.soundcloud.com/player/?url=https%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F87782780&secret_token=s-aRxsG"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://w.soundcloud.com/player/?url=https%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F87782780&secret_token=s-aRxsG']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.6.6 - Linux-2.6.32-504.12.2.el6.x86_64-x86_64-with-redhat-6.6-Santiago
[debug] exe versions: ffmpeg 0.10.15, ffprobe 0.10.15, rtmpdump 2.3
[debug] Proxy map: {}
[soundcloud:playlist] 87782780: Downloading playlist
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/me/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/me/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1673, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by jaimeMF** [comment]
It will be fixed in the next version, thanks for the report.
