### ISSUE TITLE
option to specify the extractor manually

### ISSUE THREAD

**Issue by remitamine** [rg3/youtube-dl#5457]
i see in many sites that the format of urls changes frequently or there is many formats of urls like in facebook and as i see in the regular expression it cover a lot of formats but there is more uncovered as in #5120.
so if you can add an option to specify the format manually so it can be a temporary solution untill the issue is solved.

**Comment by jaimeMF** [comment]
It wouldn't actually solve the issue in most cases. For a lot of extractors we extract some crucial information (usually the video id) from the urls using the regular expresions, so they wouldn't work.
Even if no info is extracted from the url, the webpage content may not be compatible with the extractor logic.
