### ISSUE TITLE
Error downloader for Vimple . ru

### ISSUE THREAD

**Issue by ArturoJ** [rg3/youtube-dl#5458]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://player.vimple.ru/iframe/a441d4e0f6b8484e8da
b0b8456644472', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[Vimple] a441d4e0f6b8484e8dab0b8456644472: Downloading iframe
ERROR: Unable to extract player url; please report this issue on https://yt-dl.o
rg/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete
 output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 651, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\vimple.pyo", line 40, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 567, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 557, in _search_regex
RegexNotFoundError: Unable to extract player url; please report this issue on ht
tps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-
dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version.

**Comment by ArturoJ** [comment]
thx
