### ISSUE TITLE
site request: http://live.philharmoniedeparis.fr/Concerts.html

### ISSUE THREAD

**Issue by mitshell** [rg3/youtube-dl#5465]
Hello,
it would be nice to get support for the Paris' Philarmonie streaming service.
It is currently not supported by the generic extractor:

$ youtube-dl.exe -v http://live.philharmoniedeparis.fr/concert/1030324/orchestre-philharmonique-de-
radio-france-myung-whun-chung.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://live.philharmoniedeparis.fr/concert/1030324/orchestre-ph
ilharmonique-de-radio-france-myung-whun-chung.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-69608-g9dc45d1
[debug] Proxy map: {}
[generic] orchestre-philharmonique-de-radio-france-myung-whun-chung: Requesting header
WARNING: Falling back on generic information extractor.
[generic] orchestre-philharmonique-de-radio-france-myung-whun-chung: Downloading webpage
[generic] orchestre-philharmonique-de-radio-france-myung-whun-chung: Extracting information
ERROR: Unsupported URL: http://live.philharmoniedeparis.fr/concert/1030324/orchestre-philharmonique-
de-radio-france-myung-whun-chung.html
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 923, in _real_extract
  File "youtube_dl\utils.pyo", line 1531, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: mismatched tag: line 152, column 2
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 651, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\generic.pyo", line 1442, in _real_extract
UnsupportedError: Unsupported URL: http://live.philharmoniedeparis.fr/concert/1030324/orchestre-phil
harmonique-de-radio-france-myung-whun-chung.html

In the HTML source, the script just after the header calls a flash player (src: '/Player/lecteur_video.swf'), with a path to an xml file (e.g. flashvars: { fichier_nom: '/misc/Playlist.ashx?id=1030324&track=&lang=fr', ...).
This xml file (http://live.philharmoniedeparis.fr/misc/Playlist.ashx?id=1030324&track=&lang=fr) shows to rtmp links:
rtmp://fms.8F13.edgecastcdn.net/008F13/vod/PPVI/PPVI000221700/PPVI000221701/PPVI000221701_00_Lt.mp4 (standard definition),
rtmp://fms.8F13.edgecastcdn.net/008F13/vod/PPVI/PPVI000221700/PPVI000221701/PPVI000221701_00_Ht.mp4 (high definition).

It's possible to read such a stream with e.g. VLC, so I suppose it should be possible to integrate within youtube-dl (excellent soft, by the way !).
Thanks

**Comment by fstirlitz** [comment]
The "SD" download works for me, but the "HD" one doesn't. This only happens for this particular link, though. It seems like a screwup on their side.
