### ISSUE TITLE
NBC: "Unable to extract theplatform url"

### ISSUE THREAD

**Issue by pkappesser** [rg3/youtube-dl#5470]
I didn't find an existing similar error issue searching on "NBC" or "theplatform".
Gist of the dump is at https://gist.github.com/pkappesser/36872d6f13e8157bd1c6

Thanks!

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--write-pages', u'http://www.nbc.com/saturday-night-live/video/star-wars-teaser/2832821']
[debug] Encodings: locale UTF-8, fs utf-8, out None, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.9 - Darwin-10.8.0-i386-64bit
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[NBC] 2832821: Downloading webpage
[NBC] Saving request to 2832821_http_-_www.nbc.com_saturday-night-live_video_star-wars-teaser_2832821.dump
ERROR: Unable to extract theplatform url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/nbc.py", line 47, in _real_extract
    webpage, 'theplatform url').replace('_no_endcard', '')
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 557, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract theplatform url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Can you watch the video in browsers? I got a voice said "Its content is current unavailable"

**Comment by pkappesser** [comment]
Yes, it works for me in Chrome 42.0.2311.135. However it may be restricted only to viewers inside the USA.

**Comment by yan12125** [comment]
Thanks for the information. This video will be supported in the next version.
