### ISSUE TITLE
find the best format for video file and audio file in json

### ISSUE THREAD

**Issue by hedii** [rg3/youtube-dl#5475]
hi, this is not an issue, just an ask for some help.
I am writing a php app that works with youtube-dl json generated file.
What is the best way to find the best video file and the best audio file in the generated with --dump-json json file?
I see there is a 'preference' key, but several format have the same preference value.
How does youtube-dl selects the best audio and video before merging to an audio+video with ffmpeg, what are its criteria of selection in the json generated?

**Comment by jaimeMF** [comment]
Run youtube-dl with `-f 'bestvideo+bestaudio/best'` and if it's a YouTube video the video and audio formats will be stored in the `requested_formats` field (it's not documented, so we may change it).

All the DASH videos are sorted by different attributes, like resolution or bitrate, and something similar for the audio. (It's all done in the [`InfoExtractor._sort_formats` method](https://github.com/rg3/youtube-dl/blob/08f2a92c9c23cf460b00a290b5b3819c7972231b/youtube_dl/extractor/common.py#L711)), so then we just pick the best one.
