### ISSUE TITLE
tmz url nfg...ha ha ha

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5477]
(I'm just the messenger, don't judge ;-)

URL: http://www.tmz.com/2015/04/19/bobby-brown-bobbi-kristina-awake-video-concert/

From this TMZ page it falls back to generic.....

C:\>youtube-dl -v "http://www.tmz.com/2015/04/19/bobby-brown-bobbi-kristina-awak
e-video-concert/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.tmz.com/2015/04/19/bobby-brown-b
obbi-kristina-awake-video-concert/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[generic] bobby-brown-bobbi-kristina-awake-video-concert: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bobby-brown-bobbi-kristina-awake-video-concert: Downloading webpage
[generic] bobby-brown-bobbi-kristina-awake-video-concert: Extracting information

ERROR: Unsupported URL: http://www.tmz.com/2015/04/19/bobby-brown-bobbi-kristina
-awake-video-concert/
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 923, in _real_extract
  File "youtube_dl\utils.pyo", line 1531, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 4, column 4
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 651, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\generic.pyo", line 1442, in _real_extract
UnsupportedError: Unsupported URL: http://www.tmz.com/2015/04/19/bobby-brown-bob
bi-kristina-awake-video-concert/

BUT....from this  URL to the actual video it works correctly:
http://www.tmz.com/videos/0_6snoelag

C:\>youtube-dl "http://www.tmz.com/videos/0_6snoelag"
[TMZ] 0_6snoelag: Downloading webpage
[download] Resuming download at byte 1047552
[download] Destination: Bobby Brown Tells Crowd ... Bobbi Kristina is Awake-0_6s
noelag.mp4
[download] 100% of 1.83MiB in 00:00

Thanks
Ringo

**Comment by yan12125** [comment]
Thanks for the report. This video will be supported in the next version.
