### ISSUE TITLE
[bambuser] Add support for authentication and private videos

### ISSUE THREAD

**Issue by joow** [rg3/youtube-dl#5478]
It looks like extracting a specific video from bambuser doesn't work (same issue with latest version on Windows) :
 youtube-dl --verbose http://bambuser.com/v/5432431
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://bambuser.com/v/5432431']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 3.4.3 - Linux-3.19.3-3-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
[debug] Proxy map: {}
[bambuser] 5432431: Downloading webpage
ERROR: An extractor error has occured. (caused by KeyError('title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/bambuser.py", line 47, in _real_extract
    'title': info['title'],
KeyError: 'title'
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/bambuser.py", line 47, in _real_extract
    'title': info['title'],
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 281, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occured. (caused by KeyError('title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Can you watch it in browser?

**Comment by joow** [comment]
I can if I log in as it is a private video. I tried using -u and -p option without luck. I guess extracting a private video is not supported, am I wrong ?

**Comment by dstftw** [comment]
No, login is not supported yet.

**Comment by joow** [comment]
Okay thank you very much support for the quick answer !

**Comment by dstftw** [comment]
Authentication will be supported in the next version. However, I can't check private video since I still get `You do not have access to this broadcast`.

**Comment by joow** [comment]
Great to hear :smiley:.
I can help you to test authentication if needed.

**Comment by dstftw** [comment]
You can fetch the latest sources following steps 1 through 3 of our [developer instructions](https://github.com/rg3/youtube-dl#developer-instructions) or just download and unpack [master.zip](https://github.com/rg3/youtube-dl/archive/master.zip). Then run `python -m youtube_dl -v http://bambuser.com/v/5432431`. You'll need python instaled.

**Comment by joow** [comment]
I can confirm it works perfectly :smiley:. Thanks !
Let me know if you need more information or any kind of help.

**Comment by dstftw** [comment]
That's enough. Thanks.

**Comment by dstftw** [comment]
This has been fixed in youtube-dl 2015.04.26. See our [FAQ](https://yt-dl.org/update) if you have problems updating.

**Comment by joow** [comment]
Thank you, I've updated to latest youtube-dl version and it is now working perfectly with private videos.
