### ISSUE TITLE
[REQUEST] New site http://www.7tv.de/

### ISSUE THREAD

**Issue by z0rti** [rg3/youtube-dl#5479]
Well, this is a new site, that isn't yet supported...

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by z0rti** [comment]
OK sorry: 
http://www.7tv.de/circus-halligalli/57-episode-7-staffel-5-ganze-folge
