### ISSUE TITLE
ytsearch is broken as of April 2015

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [rg3/youtube-dl#5483]
I'm not sure what's wrong, but `ytsearch:` always returns this video: https://www.youtube.com/watch?v=UKY3scPIMd8

Problem confirmed with YouTube-DL version 2015.04.17 (tested on multiple search strings on April 20, 2015).

It's probably nothing much, just changes to YouTube's search page.

**Comment by Tailszefox** [comment]
Youtube API V2 is not supported anymore, which is what ytsearch probably uses. This may also affect other YouTube extractors - though so far it doesn't seem to affect the YouTube extractor that actually downloads videos.

**Comment by JamesTheAwesomeDude** [comment]
@Tailszefox Yeah, fortunately the videos can still be watched - it's just `ytsearch` that's broken.

**Comment by sudovijay** [comment]
youtube API  V3 is the way to go, but one need to register its app to get the API_KEY

url - https://www.googleapis.com/youtube/v3/search?key=API_KEY&part=snippet&q=something

**Comment by sudovijay** [comment]
i dont know for how long but except this video  UKY3scPIMd8 . everything seems to be working fine so why not just slice the first element of search array , quick workaround  :smile:

**Comment by tYGjQCsvVI** [comment]
This also seems to be broken on some(?) Youtube channels, the one that appears for me is 'https://youtube.com/user/1veritasium', which is weird because it only shows up once:-

>`youtube-dl --get-title 'https://youtube.com/user/1veritasium'`
https://youtube.com/devicesupport
Explained: Beaker Ball Balance Problem
Beaker Ball Balance Problem

**Comment by JamesTheAwesomeDude** [comment]
@sudovijay Wait.. you mean YouTube-DL actually uses an API? And fetches the videos in a legitimate manner?

I thought it was just a "contraband" YouTube ripper which only exists because Google hasn't bothered to stamp it out.

**Comment by jaimeMF** [comment]
It should be fixed in the next version. Thanks for the report.

@JamesTheAwesomeDude we used it just for the search results and for users, but now we are just parsing the pages that their own interface uses. (Also AFAIK the api didn't allow you to actually download the video)

**Comment by dstftw** [comment]
This has been fixed in youtube-dl 2015.04.26. See our [FAQ](https://yt-dl.org/update) if you have problems updating.
