### ISSUE TITLE
Download of this video fails (version 2015.04.17)

### ISSUE THREAD

**Issue by Juul** [rg3/youtube-dl#5487]
Fails with "ERROR: content too short (expected 28344781 bytes and served 2295)"

https://www.youtube.com/watch?v=K4jVaF6DkVc

**Comment by jaimeMF** [comment]
Post the [**full output** you get with the --verbose option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs)

**Comment by Juul** [comment]
Tried it on os x and lubuntu before and failed on both, and now it works. Will report back again when I can replicate.
