### ISSUE TITLE
[REQUEST] Save the last video-id for ytsubs

### ISSUE THREAD

**Issue by untergrundbiber** [rg3/youtube-dl#5490]
Saving the id of the last video from ytsubs in a file, would make ytsubs-download faster. 
youtube-dl would then only looking for the video-id that was downloaded at last and continue after this video.
Hope this would be faster than "--dateafter now-1day"

**Comment by jaimeMF** [comment]
Use `--download-archive`, for some urls it will be faster (it won't fetch each video).

**Comment by untergrundbiber** [comment]
Oh ok, that's what I want. Sorry, i didn't see that the function is already implemented. I close here. :)
