### ISSUE TITLE
can't download metacafe video

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#5496]
Hi there, 
I was trying to download videos from metacafe.com but still no success :-

    ─[$] youtube-dl -vv -F "http://www.metacafe.com/watch/11334354/the_first_years_worth_of_photos_from_mars_rover_curiosity/"           
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['-vv', '-F', 'http://www.metacafe.com/watch/11334354/the_first_years_worth_of_photos_from_mars_rover_curiosity/']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.02.28
    [debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
    [debug] exe versions: avconv 11.3-6, avprobe 11.3-6, rtmpdump 2.4
    [debug] Proxy map: {}
    [metacafe] Retrieving disclaimer
    [metacafe] Confirming age
    [metacafe] 11334354: Downloading webpage
    [metacafe] 11334354: Extracting information
    [info] Available formats for 11334354:
    format code  extension  resolution note
    0            mp4        unknown    
    

My youtube-dl --version is :-

    [$] youtube-dl --version                                                                                                            
    2015.02.28

**Comment by yan12125** [comment]
Version 2015.04.17 works. Try the latest update.

**Comment by shirishag75** [comment]
yup, I know that `-F` only shows the different formats . I usually look for what formats or bit-rates or whatever options are available and then download that.

**Comment by yan12125** [comment]
If I'm correct, the link you mentioned has only one format of video and the bitrate metadata is not applicable. (It's always zero for several video clips found on metacafe.com) If you find another available format or some approach to determine the bitrate metadata without downloading, feel free to propose it.

**Comment by jaimeMF** [comment]
I'm closing the issue because the video can be downloaded without problem, as @yan12125 said: If someone knows how to get the format information, please share it.

**Comment by aimkeepachieve** [comment]
I use Allavsoft to download Videos from Metacafe, YouTube, Facebook, Vimeo, Dailymotion, Pornhub, Xhamster and more at http://www.allavsoft.com/how-to/metacafe-downloader-for-mac-windows.html
