### ISSUE TITLE
It can't download from facebook

### ISSUE THREAD

**Issue by iivanov2** [rg3/youtube-dl#5499]
It can't download this video:
https://www.facebook.com/PrinceEaHipHop/videos/10153278998454769/

Log:

C:\youtube-dl>youtube-dl -v https://www.facebook.com/PrinceEaHipHop/videos/10153
278998454769/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.facebook.com/PrinceEaHipHop/vid
eos/10153278998454769/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 10153278998454769: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 10153278998454769: Downloading webpage
[generic] 10153278998454769: Extracting information
[redirect] Following redirect to /PrinceEaHipHop/videos/10153278998454769/?_fb_n
oscript=1
WARNING: The url doesn't specify the protocol, trying with http
[generic] ?_fb_noscript=1: Requesting header
WARNING: Could not send HEAD request to http:///PrinceEaHipHop/videos/1015327899
8454769/?_fb_noscript=1: <urlopen error no host given>
[generic] ?_fb_noscript=1: Downloading webpage
ERROR: Unable to download webpage: <urlopen error no host given> (caused by URLE
rror('no host given',))
  File "youtube_dl\extractor\common.pyo", line 314, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1678, in urlopen
  File "urllib2.pyo", line 404, in open
  File "urllib2.pyo", line 422, in _open
  File "urllib2.pyo", line 382, in _call_chain
  File "youtube_dl\utils.pyo", line 613, in http_open
  File "urllib2.pyo", line 1151, in do_open

**Comment by yan12125** [comment]
Such URL formats is supported in git version but not in the stable release yet. Please wait patiently for the next version. See #5476 for more information
