### ISSUE TITLE
Youtube dash format

### ISSUE THREAD

**Issue by Speeedfire** [rg3/youtube-dl#5500]
Hy guys!

I use your's youtube-dl app, thats very nice and fast.
I wanna ask from you, how to extract the info json information? I write a android music player app, that stream only the audio. But if i extract the json, without use the ffmpeg, thats a little bit faser.

Sorry for my bad english.

**Comment by dstftw** [comment]
```
-j, --dump-json                  Simulate, quiet but print JSON information. See --output for a description of available keys.
-J, --dump-single-json           Simulate, quiet but print JSON information for each command-line argument. If the URL refers to a playlist, dump the whole playlist
                                 information in a single line.
--write-info-json                Write video metadata to a .info.json file
```

**Comment by Speeedfire** [comment]
I know it, i use this app. But i wanna write this json info in javascript language.

**Comment by jaimeMF** [comment]
You'll have to explain with more detail what you want to do, running `youtube-dl --dump-json URL` will print the json info.
