### ISSUE TITLE
Flickr ERROR: Unable to extract secret

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5501]
URL:   https://www.flickr.com/photos/lastmilemobilesolutions/13888419687/in/set-72157644436501012

Output:
youtube-dl.py -v "https://www.flickr.com/photos/lastmilemobilesolutions/13888419687/in/set-72157644436501012"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.flickr.com/photos/lastmilemobil
esolutions/13888419687/in/set-72157644436501012']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.6 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20, rtmpdump 2.4
[debug] Proxy map: {}
[Flickr] 13888419687: Downloading webpage
ERROR: Unable to extract secret; please report this issue on https://yt-dl.org/b
ug . Make sure you are using the latest version; type  youtube-dl -U  to update.
 Be sure to call youtube-dl with the --verbose flag and include its complete out
put.
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 651, in e
xtract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 27
5, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\flickr.py", line 34
, in _real_extract
    secret = self._search_regex(r"photo_secret: '(\w+)'", webpage, 'secret')
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 55
7, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract secret; please report this issue on https:
//yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -
U  to update. Be sure to call youtube-dl with the --verbose flag and include its
 complete output.

Thanks 
Ringo

**Comment by jaimeMF** [comment]
It will be fixed in the next version, thanks for the report.

**Comment by dstftw** [comment]
This has been fixed in youtube-dl 2015.04.26. See our [FAQ](https://yt-dl.org/update) if you have problems updating.
