### ISSUE TITLE
How --download-archive works?

### ISSUE THREAD

**Issue by muhahacz** [rg3/youtube-dl#5502]
Can anyone explain to me, how this parameter works?
Im trying to output all videos ( title + id + video lenght ) from yt playlist, EXCEPT videos that are listed in list_of_ids file.

youtube-dl http://www.youtube.com/playlist?list=PLeCg_YDclAETQHa8VyFUHKC_Ly0HUWUnq -e --get-id --get-duration --download-archive ./list_of_ids

./list_of_ids
SdfL2nY-Xs8
2lJWeOYjsCI
n2LBtevEY3c

thanks

**Comment by jaimeMF** [comment]
You have to prefix it with `youtube `, like:
```
youtube SdfL2nY-Xs8
youtube 2lJWeOYjsCI
```

(Note that the format used is internal and may change in the future)
