### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by byvlad** [rg3/youtube-dl#5505]
Hi! Last two days i get this error:
root@azwap:~# youtube-dl -j https://www.youtube.com/watch?v=fy08SQn3hRI
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
IP: 62.210.246.146

**Comment by yan12125** [comment]
Are you using services provided by OVH? You may have encountered the same problem described in #5138. See the discussion there. For short, add ```-4``` option may solve your problem. If not, you have probably downloaded too much content and Youtube is blocking your IP. Please [read our FAQ entry for the issue](https://github.com/rg3/youtube-dl/blob/master/README.md#http-error-429-too-many-requests-or-402-payment-required).
