### ISSUE TITLE
2015.04.17 - Checksum Mismatch

### ISSUE THREAD

**Issue by parparpoundski** [rg3/youtube-dl#5506]
Anybody else getting the following checksums? 

youtube-dl.exe
MD5: 5c7f5618afd0d21bc55ac561a2d92065
SHA-1: c9e224ca694cb75d93611df4dcffe71e16d4d138

**Comment by yan12125** [comment]
On http://rg3.github.io/youtube-dl/download.html, the MD5/SHA1/SHA256 checksums are for [the unix compatible version](https://yt-dl.org/downloads/2015.04.17/youtube-dl). You can still verify yourube-dl.exe via its sha256 checksum (86ffe860b0f6a03a0a6d8001b2022f41fb1c2bc497b859462b69c1f8cd8098be) or its [digital signature](https://yt-dl.org/downloads/2015.04.17/youtube-dl.exe.sig).
