### ISSUE TITLE
Get only 1 url with video+audio for YouTube video in latest build 

### ISSUE THREAD

**Issue by jonathanasquier** [rg3/youtube-dl#5510]
Hello, I was previously on 2015.03.09, but needed [this patch](https://github.com/rg3/youtube-dl/commit/7513f298b04eb11ab6c0bd0845b7a3b221bee317#diff-6c7d9a29c4af1e5a14d46615974d689cL177).
I would like to get YouTube URLs back in a single URL (instead of andio and video) with the latest build.
How can I make that possible please?

Thanks

**Comment by dstftw** [comment]
Use `-f best`. You can add it to [confiuration file](https://github.com/rg3/youtube-dl#configuration) for not typing it every time.
