### ISSUE TITLE
Youtube without audio and video seprarately

### ISSUE THREAD

**Issue by arisboch** [rg3/youtube-dl#5511]
Is there an option in youtube-dl to
1) Download the normal video file instead of downloading video and audio separately?
2) Is there an option to get the URL to the normal video instead of getting the URLs to video and audio separately?

**Comment by jaimeMF** [comment]
Use the `-f best` option, if you want to make it the default you can add it to the [configuration file](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration).

**Comment by arisboch** [comment]
Thank, my scripts works again!
