### ISSUE TITLE
Bandcamp audio downloading error

### ISSUE THREAD

**Issue by qpmm** [rg3/youtube-dl#5514]
Using the latest version:

$ python ~/Downloads/youtube-dl-master/youtube_dl/__main__.py --verbose http://primitivemandoom.bandcamp.com/album/split-12-with-fister
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://primitivemandoom.bandcamp.com/album/split-12-with-fister']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.8 - Linux-3.16.0-31-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] Proxy map: {}
[Bandcamp:album] split-12-with-fister: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/bandcamp.py", line 135, in _real_extract
    title = self._search_regex(r'album_title : "(.*?)"', webpage, 'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by qpmm** [comment]
I downloaded it ten minutes ago from Github page. Have no clue why it is still outdated.
