### ISSUE TITLE
Download vimeo video fail

### ISSUE THREAD

**Issue by aufromru** [rg3/youtube-dl#5518]
$ youtube-dl -F --verbose https://vimeo.com/102924106
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'--verbose', u'https://vimeo.com/102924106']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.8
[debug] exe versions: ffmpeg 1.0.10, ffprobe 1.0.10
[debug] Proxy map: {}
[vimeo] 102924106: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1678, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
This webpage reports:
```
Sorry, there is no video here.

Either it was deleted or it never existed in the first place. Such are the mysteries of the Internet.
```

**Comment by jaimeMF** [comment]
https://vimeo.com/102924106 says `Permission Denied`, can you view it?. If it's a private video and you need to login, you'll have to use the `--username` and `--password` options (or `--netrc`).
