### ISSUE TITLE
upload_date not working properly after the new update

### ISSUE THREAD

**Issue by y0ttahertz** [rg3/youtube-dl#5519]
The parameter %(upload_date)s is not working properly ( It was before the recent update)

If I run: 

youtube-dl -ciw -v -o '%(id)s_N3ws1t_%(upload_date)s_N3ws1t_%(title)s.%(ext)s' --date '20150424' --write-thumbnail --playlist-end 30 ytuser:newsittv

I get only the videos uploaded after 12:00 (GMT +2 Athens)

For videos uploaded earlier but on the same day, I have to run:

youtube-dl -ciw -v -o '%(id)s_N3ws1t_%(upload_date)s_N3ws1t_%(title)s.%(ext)s' --date '20150423' --write-thumbnail --playlist-end 30 ytuser:newsittv

I attach a photo of what 'ls -ltr' is showing on the local folder. The attributes of ls are the same with the ones on youtube but " %(upload_date)s " is not

![bug](https://cloud.githubusercontent.com/assets/12099822/7320353/b9c8a062-eaa4-11e4-9549-273cdb303815.JPG)

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by y0ttahertz** [comment]
video 8 is correctly not in range

from 9-12 shouldn't be in range.. same as the above because it was uploaded today (24/04/2015)

video 13 is correctly in range and already existing in the folder

![bug_ver](https://cloud.githubusercontent.com/assets/12099822/7320896/d1a8f508-eaa7-11e4-8636-edad72e4e515.JPG)

( youtube-dl -ciw -v -o '%(id)s_N3ws1t_%(upload_date)s_N3ws1t_%(title)s.%(ext)s' --date '20150423' --write-thumbnail --playlist-end 30 ytuser:newsittv )

**Comment by dstftw** [comment]
I'm experiencing exactly the same behavior with last 3 versions of youtube-dl (current git, 2015.04.17 and 2015.04.09), so nothing has been broken by recent releases. Such behavior happens due to the file timestamp being set from Last-modified HTTP header returned by webserver and not from the `upload_date` field (modifying file timestamp can be disabled with `--no-mtime`).
Since you are not willing to provide full output containing at least the actual version of youtube-dl you are using I can't check your particular version.

**Comment by y0ttahertz** [comment]
With the previous version I haven't had any problems.. be aware that by previous version I don't mean only of youtube-dl but youtube itself as well.. maybe something has changed there and that's why you are getting the same results with the previous version

Of course I can give you the full output.. but I don't know how to catch all of it ( too long for the ubuntu shell)

here is the start of it 

![bug2](https://cloud.githubusercontent.com/assets/12099822/7324940/6b146b62-eac3-11e4-9ea9-4a8489aa96a7.JPG)

**Comment by y0ttahertz** [comment]
Just to put it diferrently the timestamp returned by youtube is the actual date and time the upload happened and the ' upload_date ' and/or the ' --date ' attribute of youtube-dl is not working properly for every video
