### ISSUE TITLE
Password Protected Vimeo File: ERROR: Unable to extract login token;

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5520]
youtube-dl.py -v http://vimeo.com/33086636 --video-password boxing
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://vimeo.com/33086636', u'--video-passw
ord', u'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.6 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 33086636: Downloading webpage
[vimeo] 33086636: Extracting information
ERROR: Unable to extract login token; please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type  youtube-dl -U  to up
date. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\vimeo.py", line 274
, in _real_extract
    config = json.loads(config)
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 3 - line 1 column 178 (char 2 - 177)
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 651, in e
xtract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 27
5, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\vimeo.py", line 282
, in _real_extract
    self._verify_video_password(url, video_id, webpage)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\vimeo.py", line 180
, in _verify_video_password
    token = self._search_regex(r'xsrft = \'(.*?)\'', webpage, 'login token')
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 55
7, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract login token; please report this issue on h
ttps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube
-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and includ
e its complete output.

Thanks
Ringo

**Comment by pulpe** [comment]
Already fixed via 7513f298b04eb11ab6c0bd0845b7a3b221bee317. Wait for next release or use version from git.

**Comment by RingoTheDog** [comment]
Sry...thank you.
Please close/delete thread.
