### ISSUE TITLE
youtube device support error

### ISSUE THREAD

**Issue by blessedbiped** [rg3/youtube-dl#5522]
When trying to download files, there is now a video in several languages saying that youtube is moving to a new version of the api, and directs to youtube.com/devicesupport . This page says that the old api is going down this month. Is there a workaround yet?

**Comment by jaimeMF** [comment]
It's fixed in the git master, you'll have to wait until the next release or use the version from the repo. For future reports, please [post the output you get with the --verbose option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).
