### ISSUE TITLE
Add support to this url http://tubitv.com/

### ISSUE THREAD

**Issue by wwark** [rg3/youtube-dl#5524]
Dear Dev,

Could you please add the site to youtube-dl ?
[wark@myhost ~]$ youtube-dl http://tubitv.com/video?id=273564&title=Friday_the_13th
[1] 25534
[wark@myhost ~]$ [generic] video?id=273564: Requesting header
[redirect] Following redirect to http://tubitv.com/video?id=273564&title=Friday_the_13th
[generic] video?id=273564&title=Friday_the_13th: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video?id=273564&title=Friday_the_13th: Downloading webpage
[generic] video?id=273564&title=Friday_the_13th: Extracting information
ERROR: Unsupported URL: http://tubitv.com/video?id=273564&title=Friday_the_13th
^C
[1]+  Exit 1                  youtube-dl http://tubitv.com/video?id=27356

Best regards,
Wark.

**Comment by naglis** [comment]
Thanks for the report. TubiTv should be supported in the next release of youtube-dl. Please note that the link you've provided will require [login](https://github.com/rg3/youtube-dl#authentication-options).

**Comment by wwark** [comment]
Thanks but i have issue with ffmpeg and codec.
I will try later with the full version of ffmpeg on linux.

Best regards,
Wark.
