### ISSUE TITLE
Crunchyroll Issue

### ISSUE THREAD

**Issue by betacris** [rg3/youtube-dl#5528]
I had to reformat cpu and lost all my old files. I reinstalled youtube-dl and I keep getting this error now. Everything is up to date. 

C:\ytdl>youtube-dl -f 360p --verbose http://www.crunchyroll.com/naruto-shippuden
/episode-391-madara-uchiha-rises-666343
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'360p', u'--verbose', u'http://www.crunchyro
ll.com/naruto-shippuden/episode-391-madara-uchiha-rises-666343']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: rtmpdump 2.3
[debug] Proxy map: {}
[Crunchyroll] 666343: Downloading webpage
[Crunchyroll] 666343: Downloading media info
[Crunchyroll] 666343: Downloading media info for 360p
[Crunchyroll] 666343: Downloading media info for 480p
[Crunchyroll] 666343: Downloading media info for 720p
[Crunchyroll] 666343: Downloading media info for 720p
[Crunchyroll] 666343: Downloading media info for 1080p
[Crunchyroll] 666343: Downloading media info for 1080p
[debug] Invoking downloader on 'rtmpe://c13fs.fplive.net/c13?nvb=20150425175945&
nva=20150425220045&token=0993a867c7d2a546c7aab'
[download] Destination: Naruto Shippuden - Season 17 Episode 391 - Madara Uchiha
 Rises-666343.flv
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 404, in main
  File "youtube_dl\__init__.pyo", line 394, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1451, in download
  File "youtube_dl\YoutubeDL.pyo", line 662, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 708, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1155, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1384, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1359, in dl
  File "youtube_dl\downloader\common.pyo", line 341, in download
  File "youtube_dl\downloader\rtmp.pyo", line 162, in real_download
UnicodeDecodeError: 'ascii' codec can't decode byte 0x96 in position 41: ordinal
 not in range(128)

**Comment by dstftw** [comment]
This will be fixed in the next version of youtube-dl. Thanks for the report.

**Comment by betacris** [comment]
OK great. I tried making the changes and I still got the same issues. I'll just wait for the next version release. Thanks for your work.

**Comment by dstftw** [comment]
This may take some time. However, you can checkout the sources from git and give it a try.

**Comment by betacris** [comment]
thats cool. i'll wait, just was going nuts trying to figure it out.  Thanks again

**Comment by dstftw** [comment]
This has been fixed in youtube-dl 2015.04.26. See our [FAQ](https://yt-dl.org/update) if you have problems updating.
