### ISSUE TITLE
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video

### ISSUE THREAD

**Issue by deemytch** [rg3/youtube-dl#5529]
addr: http://www.youtube.com/watch?v=9jFD-1-9jD0&feature=youtu.be
system - archlinux
$ youtube-dl --version
2015.04.17
full output:
    # youtube-dl --verbose 'http://www.youtube.com/watch?v=9jFD-1-9jD0&feature=youtu.be'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.youtube.com/watch?v=9jFD-1-9jD0&feature=youtu.be']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 3.4.3 - Linux-3.19.3-3-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 9jFD-1-9jD0: Downloading webpage
[youtube] 9jFD-1-9jD0: Downloading video info webpage
[youtube] 9jFD-1-9jD0: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1111, in _real_extract
    raise ExtractorError('no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')
youtube_dl.utils.ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
It works for me, can you watch the video in the browser?

**Comment by deemytch** [comment]
yes, and it works now in youtube-dl also.
WTF...
