### ISSUE TITLE
Banned Accounts 

### ISSUE THREAD

**Issue by AdamDanischewski** [rg3/youtube-dl#5537]
I found a Youtube video that is part of a playlist and plays on Youtube yet youtube-dl states that:  
The YouTube account associated with this video has been terminated due to multiple third-party notifications of copyright infringement.

If you go to the URL: 
https://www.youtube.com/watch?v=L_By3g85mfM&list=PLGVYI6RLE55CRhyTh-vniR7yG2Ql3GYRl

It plays fine, not sure if this is a new technique of Youtube, or what but it seems like it should work. 

$> youtube-dl --max-quality 22 "https://www.youtube.com/watch?v=L_By3g85mfM&list=PLGVYI6RLE55CRhyTh-vniR7yG2Ql3GYRl"
[youtube:playlist] Downloading playlist PLGVYI6RLE55CRhyTh-vniR7yG2Ql3GYRl - add --no-playlist to just download video L_By3g85mfM
[youtube:playlist] PLGVYI6RLE55CRhyTh-vniR7yG2Ql3GYRl: Downloading webpage
[download] Downloading playlist: tape five - dixie biscuit
[youtube:playlist] playlist tape five - dixie biscuit: Collected 13 video ids (downloading 13 of them)
[download] Downloading video 1 of 13
[youtube] au4yagERsoI: Downloading webpage
[youtube] au4yagERsoI: Downloading video info webpage
ERROR: au4yagERsoI: YouTube said: "Tape Five - Dixie Biscu..."
The YouTube account associated with this video has been terminated due to multiple third-party notifications of copyright infringement.

**Comment by yan12125** [comment]
It's clearly stated - add --no-playlist to just download video L_By3g85mfM. For example:
```
youtube-dl --max-quality 22 "https://www.youtube.com/watch?v=L_By3g85mfM&list=PLGVYI6RLE55CRhyTh-vniR7yG2Ql3GYRl" --no-playlist
```
Then you can get the desired video. If you do not specify the option ```--no-playlist```, youtube-dl tries to download from the first video, which results in errors. If you want to download all other available videos in the playlist, use the ```--ignore-errors``` option.

**Comment by AdamDanischewski** [comment]
Thanks, I didn't realize the video URL was actually considered a
playlist itself.

Perhaps if its a video URL it may make sense to presume you the video
is meant by default and not the whole playlist.

**Comment by AdamDanischewski** [comment]
This is completely unrelated but I thought many of you may be
interested this short single script bash http server, that I use
sometimes and find very potentially useful. You can configure it to do
a lot more than act as a remote file browser but thats the default
behavior.

This single bash script is a short 300+ lines, it builds its own conf
file and you simply drop it on any *nix box and start it up with
bashttpd -s, it will be listening on 8080 of the ip address where it
is run.

Then you can browse and download all on the remote system with
http://<ip address>:8080/

You can see the fork here:
 https://github.com/AdamDanischewski/bashttpd/blob/master/bashttpd

Anyway, I posted this only as a thanks for the youtube-dl,
hope you don't mind,
AMD
