### ISSUE TITLE
Http error

### ISSUE THREAD

**Issue by szemy** [rg3/youtube-dl#5538]
Hi!
Just got this error in a youtube video:

youtube-dl --verbose https://www.youtube.com/watch?t=48&v=e2CXaJv0cMw
[1] 21336
tamas@tamas-IdeaPad-U310:~/Videos$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?t=48']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.26
[debug] Python version 2.7.6 - Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[generic] watch?t=48: Requesting header
[redirect] Following redirect to https://www.youtube.com/supported_browsers?next_url=%2F
[youtube:user] supported_browsers: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 315, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1701, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Thanks!

**Comment by szemy** [comment]
Without the t=48 it works. Might be good to handle this as most of the time it is copy paste from browser.

**Comment by dstftw** [comment]
You have to escape `&` or enclose the whole URL in quotes:
`youtube-dl --verbose "https://www.youtube.com/watch?t=48&v=e2CXaJv0cMw"`.

**Comment by szemy** [comment]
Ok, thanks for fast response!
