### ISSUE TITLE
Crunchyroll Issue Continued from issues #5528

### ISSUE THREAD

**Issue by betacris** [rg3/youtube-dl#5540]
Fixing #5528 It gets further now almost working but hits some other errors. 

C:\Windows\System32>youtube-dl -f 360p --verbose http://www.crunchyroll.com/punch-line/episode-1-panty-panic-678489
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'360p', u'--verbose', u'http://www.crunchyro
ll.com/punch-line/episode-1-panty-panic-678489']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.04.26
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: rtmpdump 2.3
[debug] Proxy map: {}
[Crunchyroll] 678489: Downloading webpage
[Crunchyroll] 678489: Downloading media info
[Crunchyroll] 678489: Downloading media info for 360p
[Crunchyroll] 678489: Downloading media info for 480p
[Crunchyroll] 678489: Downloading media info for 720p
[Crunchyroll] 678489: Downloading media info for 1080p
[debug] Invoking downloader on 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEa
2aHa9aDd4dbaScma_cpalbXaAcrcIaQ-bvpKUY-dHa-pAGwmqQDDxv&aifp=0009&slist=c20/s/ve1
764931/video.mp4'
[download] Destination: PUNCH LINE Episode 1 - Panty Panic-678489.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://cp150757.edgefcs.n
et/ondemand/?auth=daEa2aHa9aDd4dbaScma_cpalbXaAcrcIaQ-bvpKUY-dHa-pAGwmqQDDxv&aif
p=0009&slist=c20/s/ve1764931/video.mp4' -o 'PUNCH LINE Episode 1 - Panty Panic-6
78489.flv.part' --playpath mp4:c20/s/ve1764931/video.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.3
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license
: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : cp150757.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=daEa2aHa9aDd4dbaScma_cpalbXaAc
rcIaQ-bvpKUY-dHa-pAGwmqQDDxv&aifp=0009&slist=c20/s/ve1764931/video.mp4
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : cp150757.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:c20/s/ve1764931/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://cp150757.edgefcs.net:1935/ondemand/?auth=da
Ea2aHa9aDd4dbaScma_cpalbXaAcrcIaQ-bvpKUY-dHa-pAGwmqQDDxv&aifp=0009&slist=c20/s/v
e1764931/video.mp4
[rtmpdump] DEBUG: app      : ondemand/?auth=daEa2aHa9aDd4dbaScma_cpalbXaAcrcIaQ-
bvpKUY-dHa-pAGwmqQDDxv&aifp=0009&slist=c20/s/ve1764931/video.mp4
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 06
[rtmpdump] DEBUG: HandShake: DH pubkey position: 166
[rtmpdump] DEBUG: HandShake: Client digest offset: 879
[rtmpdump] DEBUG: HandShake: Initial client digest:
[rtmpdump] DEBUG: ef 7f ac 0b 0d 11 c6 0e 72 74 4c 4e 9e d9 a8 0e
[rtmpdump] DEBUG: ed 58 df 7b b0 f3 17 56 4c 43 e0 25 ba 19 9f 99
[rtmpdump] DEBUG: HandShake: Type Answer   : 09
[rtmpdump] WARNING: HandShake: Type mismatch: client sent 6, server answered 9
[rtmpdump] DEBUG: HandShake: Server Uptime : 34514427
[rtmpdump] DEBUG: HandShake: FMS Version   : 4.5.2.1
[rtmpdump] DEBUG: HandShake: Server DH public key offset: 488
[rtmpdump] DEBUG: HandShake: Secret key:
[rtmpdump] DEBUG: d8 24 52 e7 c4 ed c6 18 33 cc e7 2e 97 e6 1a d5
[rtmpdump] DEBUG: 51 84 c2 86 a1 6c ab e0 a2 8b 03 28 c4 2a 0d d7
[rtmpdump] DEBUG: 51 06 31 40 5e c1 95 d2 93 e1 08 a1 36 57 37 49
[rtmpdump] DEBUG: 77 dc 2d e1 51 67 67 03 cb 14 b8 28 ce fb be fd
[rtmpdump] DEBUG: 45 9e 6f f8 32 53 7f 43 ad c0 3a 8c a7 3f 50 85
[rtmpdump] DEBUG: e7 bc 63 33 89 53 4d 8f 73 f6 b2 4c 2f 32 0b 7c
[rtmpdump] DEBUG: 00 83 c3 b3 e7 76 da ac ab 13 93 66 9b f3 89 8f
[rtmpdump] DEBUG: df 4f 00 a5 5d c9 dc ce e4 8b 99 00 f0 ec a8 5a
[rtmpdump] DEBUG: RC4 Out Key:
[rtmpdump] DEBUG: 43 a6 86 6a a3 64 3d 7b d7 41 37 1d 80 ed 63 14
[rtmpdump] DEBUG: RC4 In Key:
[rtmpdump] DEBUG: f3 0a 90 fa 80 89 58 ce 5d 92 a4 7d 07 db 80 c6
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server di
gest:
[rtmpdump] DEBUG: d4 a4 b8 e4 00 00 3b 5c d4 0b 95 9d 11 74 54 a8
[rtmpdump] DEBUG: a6 68 b2 11 18 12 67 c0 f6 7f 9b 5a e0 8f 6d 3e
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: 60 81 d9 95 ab 92 75 c2 b6 7b 19 c0 46 a0 33 82
[rtmpdump] DEBUG: 0a 33 00 25 cf 07 79 f2 d3 73 b8 bb 97 42 a6 0a
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: 51 2a d4 43 fc c4 34 f8 ba e8 a6 ba 23 d2 ab 55
[rtmpdump] DEBUG: 61 88 4c f2 a7 bc 7d 4e bf a0 93 3d 53 61 dc 51
[rtmpdump] DEBUG: HandShake: Digest key:
[rtmpdump] DEBUG: d9 71 0a 30 3a a4 6a a7 2f 1f af d4 bf 42 56 89
[rtmpdump] DEBUG: 26 37 bc 7d 72 6d db aa 4f 3a 4c 59 3d be db 5e
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: 4f fb ec 35 d6 bc 47 57 2e 02 de 47 1b da 04 a9
[rtmpdump] DEBUG: 1a 07 9b 90 dc 02 df 81 4b 17 a8 63 69 b7 ab 25
[rtmpdump] WARNING: HandShake: Server not genuine Adobe!
[rtmpdump] ERROR: RTMP_Connect1, handshake failed.
[rtmpdump] DEBUG: Closing connection.
ERROR: unable to download video
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1481, in download
  File "youtube_dl\YoutubeDL.pyo", line 662, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 708, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1159, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1419, in process_info
UnavailableVideoError: [Error 2] The system cannot find the file specified: u'PU
NCH LINE Episode 1 \u2013 Panty Panic-678489.flv.part'

**Comment by dstftw** [comment]
Update rtmpdump to 2.4.

**Comment by betacris** [comment]
Updated to 2.4. Same results. 

C:\Windows\System32>youtube-dl -f 360p --verbose http://www.crunchyroll.com/punch-line/episode-1-panty-panic-678489
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'360p', u'--verbose', u'http://www.crunchyroll.com/punch-line/episode-1-panty-panic-678489']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.04.26
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 678489: Downloading webpage
[Crunchyroll] 678489: Downloading media info
[Crunchyroll] 678489: Downloading media info for 360p
[Crunchyroll] 678489: Downloading media info for 480p
[Crunchyroll] 678489: Downloading media info for 720p
[Crunchyroll] 678489: Downloading media info for 1080p
[debug] Invoking downloader on 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEc
8d4c9cJbSa4a9a_cKcNcKc2aec7cVcM-bvpLLm-dHa-lDJymsMBBuA&aifp=0009&slist=c21/s/ve1764931/video.mp4'
[download] Destination: PUNCH LINE Episode 1 - Panty Panic-678489.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://cp150757.edgefcs.n
et/ondemand/?auth=daEc8d4c9cJbSa4a9a_cKcNcKc2aec7cVcM-bvpLLm-dHa-lDJymsMBBuA&aifp=0009&slist=c21/s/ve1764931/video.mp4' -o 'PUNCH LINE Episode 1 - Panty Panic-678489.flv.part' --playpath mp4:c21/s/ve1764931/video.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license
: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : cp150757.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=daEc8d4c9cJbSa4a9a_cKcNcKc2aec7cVcM-bvpLLm-dHa-lDJymsMBBuA&aifp=0009&slist=c21/s/ve1764931/video.mp4
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : cp150757.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:c21/s/ve1764931/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://cp150757.edgefcs.net:1935/ondemand/?auth=daEc8d4c9cJbSa4a9a_cKcNcKc2aec7cVcM-bvpLLm-dHa-lDJymsMBBuA&aifp=0009&slist=c21/s/ve1764931/video.mp4
[rtmpdump] DEBUG: app      : ondemand/?auth=daEc8d4c9cJbSa4a9a_cKcNcKc2aec7cVcM-
bvpLLm-dHa-lDJymsMBBuA&aifp=0009&slist=c21/s/ve1764931/video.mp4
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
ERROR: unable to download video
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1481, in download
  File "youtube_dl\YoutubeDL.pyo", line 662, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 708, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1159, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1419, in process_info
UnavailableVideoError: [Error 2] The system cannot find the file specified: u'PU
NCH LINE Episode 1 \u2013 Panty Panic-678489.flv.part'

**Comment by betacris** [comment]
weird... tried a different URL and it worked. 
Tried this one. 
youtube-dl -f 360p --verbose http://www.crunchyroll.com/naruto-shippuden/episode-394-the-new-chunin-exams-662635?t=0

I am going to try using my username and password and see if it works with that link in the previous comment

**Comment by dstftw** [comment]
Remove `PUNCH LINE Episode 1 – Panty Panic-678489.flv.part` and run again.

**Comment by betacris** [comment]
I removed it and it downloaded but I am still getting the errors at the end of the process.
It gets to 99.9 and it still works if i go to the file and delete the .part off the filename. Just wondering if the errors on the end are what makes it not fully finish?

[download]  99.9% of ~85.91MiB at  1.15MiB/s ETA 00:00
[rtmpdump] DEBUG: RTMP_Read returned: 0
[rtmpdump] Download complete
[rtmpdump] DEBUG: Closing connection.
ERROR: unable to download video
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1481, in download
  File "youtube_dl\YoutubeDL.pyo", line 662, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 708, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1159, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1419, in process_info
UnavailableVideoError: [Error 2] The system cannot find the file specified: u'PU
NCH LINE Episode 1 \u2013 Panty Panic-678489.flv.part'

**Comment by dstftw** [comment]
What if you download not in `C:/Windows/system32`?

**Comment by betacris** [comment]
ok so if i run command prompt "as administrator" it works and renames it.

**Comment by betacris** [comment]
I am almost back to how it was setup before. I am using the guideline below to be able to right click and launch the stream via youtube-dl into MPC-HC. In the past i used the guide below. 

http://forum.doom9.org/showthread.php?t=170858

1. download youtube-dl.exe from official site
2. put youtube-dl.exe into C:\windows\system32 or anywhere in your PATH
3. create new textfile anywhere in your PATH, rename to yt.bat
4. open yt.bat in text editor of choice and input
@echo off
youtube-dl -q -o - %1^=%2 | "C:\Program Files (x86)\MPC-HC\mpc-hc.exe" /play /close -
exit
5. (optional) install Open With extension for firefox, go into settings of extension,
 enable for link "right click" context menu, add new program "C:\windows\system32\cmd.exe"
edit parameters of program to "/c start yt"

it should take the link and open the bat file and place it into the %1^=%2 ... it wont run. but if i run the command manually 
youtube-dl -q -o - http://www.crunchyroll.com/punch-line/episode-1-panty-panic-678489 | "C:\Program Files (x86)\MPC-HC\mpc-hc.exe" /play /close - 

it will work 

Am I using the output template incorrectly?

**Comment by betacris** [comment]
I finally got a screenshot of it... it happens so quick

It looks as if it is sending it to the batch file... 
![untitled](https://cloud.githubusercontent.com/assets/2694379/7356302/d6c09e96-ecec-11e4-80d2-f764c8afde7e.png)

**Comment by jaimeMF** [comment]
You are (somehow) calling [livestreamer](https://github.com/chrippa/livestreamer), we can't give you support for it here.

Is the original problem with youtube-dl solved?

**Comment by betacris** [comment]
hmm didnt even see that.. weird.. .wonder why its calling that... 

But yes, you can close the ticket... i will look further... Thanks

**Comment by betacris** [comment]
got it working for anyone in the future. I had some old registry entries i guess so i renamed my batch yt.bat to ytube.bat. It would not try to launch livestreamer then. 

Error still happened so I looked at the command and the argument passing was incorrect. 

Instead of 
youtube-dl -q -o - %1^=%2 | "C:\Program Files (x86)\MPC-HC\mpc-hc.exe" /play /close - exit
It should be 
youtube-dl -q -o - %1 | "C:\Program Files (x86)\MPC-HC\mpc-hc.exe" /play /close - exit

%1 is the variable for the html link that is passed as an argument for cmd.exe when the batch file loads from the firefox extension (open with).
