### ISSUE TITLE
ExtractorError: "An extractor error has occured. (caused by KeyError(u'fname',))"

### ISSUE THREAD

**Issue by shlomo-Kallner** [rg3/youtube-dl#5541]
command line (called from within ConEmu with a custom batch Script:
youtube-dl.exe http://allmyvideos.net/c5j2z4ot99td -w -i -c --write-description --verbose --write-info-json --write-thumbnail -o "C:\\Temp\\Movies\\%(title)s__%(uploader)s_%(upload_date)s.%(ext)s"

Youtube-dl output from within custon script:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://allmyvideos.net/c5j2z4ot99td', u'-w', u'-i', u'-c', u'--write-description', u'--verbose', u'--write-info-json', u'--write-thumbnail', u'-o', u'C:\\\\Temp\\\\Movies\\\\%(title)s__%(uploader)s_%(upload_date)s.%(ext)s']
[debug] Encodings: locale cp1255, fs mbcs, out cp862, pref cp1255
[debug] youtube-dl version 2015.04.26
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-68763-g202947a, ffprobe N-68763-g202947a, rtmpdump 2.3
[debug] Proxy map: {}
[Moniker] c5j2z4ot99td: Downloading webpage
[Moniker] c5j2z4ot99td: Downloading video page ...
ERROR: An extractor error has occured. (caused by KeyError(u'fname',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\common.pyo", line 276, in extract
  File "youtube_dl\extractor\moniker.pyo", line 54, in _real_extract
KeyError: u'fname'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 651, in extract_info
  File "youtube_dl\extractor\common.pyo", line 282, in extract
ExtractorError: An extractor error has occured. (caused by KeyError(u'fname',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Youtube-dl output after directly pasting the command line in a terminal:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://allmyvideos.net/c5j2z4ot99td', '-w', '-i', '-c', '--write-description', '--

verbose', '--write-info-json', '--write-thumbnail', '-o', 'C:\\\\Temp\\\\Movies\\\\%(title)s__%(uploader)s_

%(upload_date)s.%(ext)s']
[debug] Encodings: locale cp1255, fs mbcs, out cp862, pref cp1255
[debug] youtube-dl version 2014.12.06.1
[debug] Python version 3.4.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Moniker] c5j2z4ot99td: Downloading webpage
[Moniker] c5j2z4ot99td: Downloading video page ...
ERROR: 'fname'
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 554, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 241, in extract
    return self._real_extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\moniker.py", line 55, in _real_extract
    title = os.path.splitext(data['fname'])[0]
KeyError: 'fname'

**Comment by dstftw** [comment]
This video has been removed.
```
Reason for deletion:

Removed for Copyright Infringement
```

**Comment by shlomo-Kallner** [comment]
thanks
