### ISSUE TITLE
Crunchyroll Works on some URLs and not others

### ISSUE THREAD

**Issue by betacris** [rg3/youtube-dl#5544]
This one worked:
C:\ytdl>youtube-dl --username XXXXX --password XXXXX --verbose -o - http://www.crunchyroll.com/punch-line/episode-1-panty-panic-678489 | "C:\Program Files (x86)\SVP\MPC-HC\mpc-hc.exe" /play /close -

This one did not. 
C:\ytdl>youtube-dl --username XXXXX --password XXXXX --verbose -o - http://www.crunchyroll.com/nisekoi/episode-3-need-678113 | "C:\Program Files (x86)\SVP\MPC-HC\mpc-hc.exe" /play /close -

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE'
, u'--verbose', u'-o', u'-', u'http://www.crunchyroll.com/nisekoi/episode-3-need
-678113']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.04.26
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 678113: Downloading webpage
[Crunchyroll] 678113: Downloading media info
[Crunchyroll] 678113: Downloading media info for 360p
[Crunchyroll] 678113: Downloading media info for 480p
[Crunchyroll] 678113: Downloading media info for 720p
[Crunchyroll] 678113: Downloading media info for 1080p
[debug] Invoking downloader on 'rtmpe://c19fs.fplive.net/c19?nvb=20150428063730&
nva=20150428103830&token=0cd6de464be8c00dff225'
[download] Destination: -
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://c19fs.fplive.net/c
19?nvb=20150428063730&nva=20150428103830&token=0cd6de464be8c00dff225' -o - --pla
ypath mp4:s/ve1785515/video.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license
: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : c19fs.fplive.net
[rtmpdump] DEBUG: Parsed app     : c19?nvb=20150428063730&nva=20150428103830&tok
en=0cd6de464be8c00dff225
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] WARNING: Can't resume in stdout mode, ignoring --resume option
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : c19fs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:s/ve1785515/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://c19fs.fplive.net:1935/c19?nvb=2015042806373
0&nva=20150428103830&token=0cd6de464be8c00dff225
[rtmpdump] DEBUG: app      : c19?nvb=20150428063730&nva=20150428103830&token=0cd
6de464be8c00dff225
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 06
[rtmpdump] DEBUG: HandShake: DH pubkey position: 166
[rtmpdump] DEBUG: HandShake: Client digest offset: 879
[rtmpdump] DEBUG: HandShake: Initial client digest:
[rtmpdump] DEBUG: 73 8c 45 90 89 6d d0 2a 84 3f 6c 6b e5 4b 11 99
[rtmpdump] DEBUG: 32 88 b0 15 ad 91 6e 13 5b fa c2 9a f9 0f a4 89
[rtmpdump] DEBUG: HandShake: Type Answer   : 09
[rtmpdump] WARNING: HandShake: Type mismatch: client sent 6, server answered 9
[rtmpdump] DEBUG: HandShake: Server Uptime : 2145138052
[rtmpdump] DEBUG: HandShake: FMS Version   : 4.5.3.1
[rtmpdump] DEBUG: HandShake: Server DH public key offset: 469
[rtmpdump] DEBUG: HandShake: Secret key:
[rtmpdump] DEBUG: 6d 04 cb 5d de 13 86 9c a3 5c a6 fc f2 9a 67 1e
[rtmpdump] DEBUG: b4 8e fa 68 b8 3c 4d 84 a5 22 44 50 52 97 72 65
[rtmpdump] DEBUG: 2d 45 63 db 05 0d ff ab 8c 06 fb bd 10 d9 27 f5
[rtmpdump] DEBUG: 30 11 79 55 a7 3d a5 28 5e ed a5 e3 98 b9 17 2f
[rtmpdump] DEBUG: d6 5b 8e 48 87 f9 fe 19 d9 03 cc 86 78 eb fb 66
[rtmpdump] DEBUG: 65 12 18 17 3c 5a c8 72 a9 1d 67 3f 7a 41 39 39
[rtmpdump] DEBUG: 6b 8c b8 83 a7 5e 07 92 48 58 20 08 68 1e 8f 5e
[rtmpdump] DEBUG: 7e 7d 1d 22 cf 15 44 e3 af e8 ec da 97 3f 3d 0a
[rtmpdump] DEBUG: RC4 Out Key:
[rtmpdump] DEBUG: 90 a6 e1 31 98 cf 3c 3e 61 67 1d 66 91 cd 53 e2
[rtmpdump] DEBUG: RC4 In Key:
[rtmpdump] DEBUG: d6 1a a3 cd 4f 1b 1d 00 02 6c df c6 c2 5a 51 5a
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server di
gest:
[rtmpdump] DEBUG: 34 7f ef ad 73 0f e8 70 b9 81 b5 ae d0 9f 95 c7
[rtmpdump] DEBUG: 98 bf d0 f1 d5 cf 08 86 11 52 be 27 b2 24 b5 ce
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: 38 fe 35 98 2a 77 b4 be 3b b3 78 14 f5 58 29 e5
[rtmpdump] DEBUG: 09 00 af 4c ec cf f5 5d 5b ea cc c1 d0 c0 83 3c
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: 0e 21 ce bc 6c 9b 8e a8 b3 a8 55 11 06 d8 80 5a
[rtmpdump] DEBUG: 7d d6 1e a9 44 2f cc 91 75 a5 3b 76 59 84 45 c6
[rtmpdump] DEBUG: HandShake: Digest key:
[rtmpdump] DEBUG: 04 1e 86 f4 c5 c4 04 20 7d f3 d4 02 53 64 e0 57
[rtmpdump] DEBUG: d6 3c 82 a2 44 86 65 9f 8a 62 cf cb 02 d1 cc 5b
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: 0e 21 ce bc 6c 9b 8e a8 b3 a8 55 11 06 d8 80 5a
[rtmpdump] DEBUG: 7d d6 1e a9 44 2f cc 91 75 a5 3b 76 59 84 45 c6
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 128
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 165 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  error>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetConnection.Co
nnect.Rejected>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Connection faile
d.>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  [ Server.Reject
] : Connection failed.>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_error>
[rtmpdump] ERROR: rtmp server sent error
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 18 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <close>
[rtmpdump] ERROR: rtmp server requested close
[rtmpdump] DEBUG: Closing connection.
ERROR: unable to download video
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1481, in download
  File "youtube_dl\YoutubeDL.pyo", line 662, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 708, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1159, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1419, in process_info
UnavailableVideoError: [Error 2] The system cannot find the file specified: u'-'

**Comment by betacris** [comment]
Issue still happening on 4.28 version

Didnt work on this one:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'1080p', u'--all-subs', u'--sub-format', u'a
ss', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--verbose', u'-q',
u'-o', u'-', u'http://www.crunchyroll.com/sound-euphonium/episode-1-welcome-to-h
igh-school-678371?t']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.04.28
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[debug] Invoking downloader on 'rtmpe://c19fs.fplive.net/c19?nvb=20150501083903&
nva=20150501124003&token=0c405d32f4fcfca539629'
ERROR: unable to download video
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1473, in download
  File "youtube_dl\YoutubeDL.pyo", line 660, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 706, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1151, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1411, in process_info
UnavailableVideoError: [Error 2] The system cannot find the file specified: u'-'

But works on this one 

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'1080p', u'--all-subs', u'--sub-format', u'a
ss', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--verbose', u'-q',
u'-o', u'-', u'http://www.crunchyroll.com/punch-line/episode-4-possessed-by-the-
stripes-678495?t']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.04.28
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[debug] Invoking downloader on 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEd
Nd9aibxaFcMd2bAbdbCauclb_dGdZal-bvqZXu-dHa-uDEwtrKAywC&aifp=0009&slist=c11/s/ve1
794013/video.mp4'

It looks like the rtmpe link has the mp4 on the end of the one that worked...

**Comment by almostalive** [comment]
I think no Crunchyroll video is working right now. I decided to try the first video listed here that was said to work and it is not working now as well. I have tried many videos and none of them are currently working.

I'm on Arch Linux X86_64. I have tried with youtube-dl and rtmpdump that is in the official repos and I have used youtube-dl-git and rtmpdump-git from AUR, neither have worked.

this log is from youtube-dl built from commit 372744c544ec3de1b35583e7d6fc2cbc4cc39f3a and with rtmpdump-git.

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.crunchyroll.com/punch-line/episode-1-panty-panic-678489']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 3.4.3 - Linux-4.0.3-1-ck-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 678489: Downloading webpage
[Crunchyroll] 678489: Downloading media info
[Crunchyroll] 678489: Downloading media info for 360p
[Crunchyroll] 678489: Downloading media info for 480p
[Crunchyroll] 678489: Downloading media info for 720p
[Crunchyroll] 678489: Downloading media info for 1080p
[debug] Invoking downloader on 'rtmpe://c19fs.fplive.net/c19?nvb=20150514004734&nva=20150514044834&token=0d058677d998bdf9ca30a'
[download] Destination: PUNCH LINE Episode 1 – Panty Panic-678489.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://c19fs.fplive.net/c19?nvb=20150514004734&nva=20150514044834&token=0d058677d998bdf9ca30a' -o 'PUNCH LINE Episode 1 – Panty Panic-678489.flv.part' --playpath mp4:s/ve1764937/video.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : c19fs.fplive.net
[rtmpdump] DEBUG: Parsed app     : c19?nvb=20150514004734&nva=20150514044834&token=0d058677d998bdf9ca30a
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : c19fs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:s/ve1764937/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://c19fs.fplive.net:1935/c19?nvb=20150514004734&nva=20150514044834&token=0d058677d998bdf9ca30a
[rtmpdump] DEBUG: app      : c19?nvb=20150514004734&nva=20150514044834&token=0d058677d998bdf9ca30a
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 06
[rtmpdump] DEBUG: HandShake: DH pubkey position: 472
[rtmpdump] DEBUG: HandShake: Client digest offset: 1383
[rtmpdump] DEBUG: HandShake: Initial client digest: 
[rtmpdump] DEBUG: 92 8e 8a f5 ab a8 cc 2e c3 3c b4 19 80 dd 32 af
[rtmpdump] DEBUG: 2a a3 8f 85 f5 f0 3d 6a 87 7c 9e 4f d0 07 2e cd
[rtmpdump] DEBUG: HandShake: Type Answer   : 09
[rtmpdump] WARNING: HandShake: Type mismatch: client sent 6, server answered 9
[rtmpdump] DEBUG: HandShake: Server Uptime : 1787449575
[rtmpdump] DEBUG: HandShake: FMS Version   : 4.5.3.1
[rtmpdump] DEBUG: HandShake: Server DH public key offset: 473
[rtmpdump] DEBUG: HandShake: Secret key: 
[rtmpdump] DEBUG: 17 c1 72 29 1f 5d b7 99 8e 73 ee 18 b7 40 8c fa
[rtmpdump] DEBUG: a5 6d 9d 0a e6 fc 4d fd f6 9c 65 7e 8d b0 7c 75
[rtmpdump] DEBUG: 28 05 f0 4b 64 2a 9a 04 72 62 8b 6e 7b 16 1c 1e
[rtmpdump] DEBUG: 69 2e 3b f4 ed 56 99 9a 86 6e e0 aa 5f 42 9f 1d
[rtmpdump] DEBUG: bd c9 da 24 b2 e9 0f a4 d6 cf df cb ab 09 4b 89
[rtmpdump] DEBUG: 17 53 b5 aa dc ca 51 8d 44 63 d4 65 19 ea 82 d7
[rtmpdump] DEBUG: 34 a1 03 39 d7 6e 31 26 3d 00 60 07 0c e6 a4 24
[rtmpdump] DEBUG: 4b b0 c2 22 30 dc 96 09 d2 52 e6 74 35 9e cf 2c
[rtmpdump] DEBUG: RC4 Out Key: 
[rtmpdump] DEBUG: 48 3d 73 bb 4e cd 0e 8e 5a 2f b6 0c ef 44 e1 76
[rtmpdump] DEBUG: RC4 In Key: 
[rtmpdump] DEBUG: 7c 82 ec fa 24 6b 0b b5 17 19 ba d7 3f 50 6c 05
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server digest: 
[rtmpdump] DEBUG: 1d 22 c4 77 bf 64 64 ad 78 33 15 9d 0a e6 c1 b8
[rtmpdump] DEBUG: c6 25 b6 d7 22 23 f0 75 b5 94 45 b3 e2 c7 65 6e
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: 07 fe af 79 6c 45 21 c8 4b 14 8c 51 de e7 d4 8c
[rtmpdump] DEBUG: a0 b8 0b ab 55 93 6b f0 c7 fa aa 06 57 8e 04 10
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: 68 34 25 b8 e1 a5 35 05 74 5f fe cd cc 81 1a 2a
[rtmpdump] DEBUG: 17 9b 47 c7 9c f1 3f c0 62 c4 ae bb 0d 2a 19 5e
[rtmpdump] DEBUG: HandShake: Digest key: 
[rtmpdump] DEBUG: 1a 49 4b 17 13 34 53 29 37 57 ec 62 cc d1 01 68
[rtmpdump] DEBUG: 50 29 f3 15 8e 15 7f b9 13 2f f7 7f 91 6d e2 28
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: 68 34 25 b8 e1 a5 35 05 74 5f fe cd cc 81 1a 2a
[rtmpdump] DEBUG: 17 9b 47 c7 9c f1 3f c0 62 c4 ae bb 0d 2a 19 5e
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 128
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 165 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	error>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Rejected>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Connection failed.>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	[ Server.Reject ] : Connection failed.>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_error>
[rtmpdump] ERROR: rtmp server sent error
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 18 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <close>
[rtmpdump] ERROR: rtmp server requested close
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : c19fs.fplive.net
[rtmpdump] DEBUG: Parsed app     : c19?nvb=20150514004734&nva=20150514044834&token=0d058677d998bdf9ca30a
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : c19fs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:s/ve1764937/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://c19fs.fplive.net:1935/c19?nvb=20150514004734&nva=20150514044834&token=0d058677d998bdf9ca30a
[rtmpdump] DEBUG: app      : c19?nvb=20150514004734&nva=20150514044834&token=0d058677d998bdf9ca30a
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.


ERROR: rtmpdump exited with code 1
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.5.10', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 399, in main
    _real_main(argv)
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 389, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1483, in download
    res = self.extract_info(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 706, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1154, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1416, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1358, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 527, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 489, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

if any more info is needed or anything that I can try to do on my end let me know and I'll see what I can get done.

**Comment by betacris** [comment]
I think your issue is different....It still works for me (depending on the link/episode, also still using the 2015.05.04 version). Its got to be something with the extractor... maybe a character limit or some special char that is messing it up. You can see on the first one it doesn't get the whole link for rtmpe. 

[debug] Invoking downloader on 'rtmpe://c19fs.fplive.net/c19?nvb=20150501083903&
nva=20150501124003&token=0c405d32f4fcfca539629' <---- no .mp4

[debug] Invoking downloader on 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEd
Nd9aibxaFcMd2bAbdbCauclb_dGdZal-bvqZXu-dHa-uDEwtrKAywC&aifp=0009&slist=c11/s/ve1
794013/video.mp4'

**Comment by lachs0r** [comment]
The missing .mp4 in the URL is normal (and it’s still included as the play path). This only happens with the Level 3 CDN (fplive); Akamai is fine.

**Comment by betacris** [comment]
so... does that mean its crunchyroll's CDN providers thats causing the issue and cant be fixed?

**Comment by lachs0r** [comment]
Well obviously it works with their player .swf, so my guess is that either 
there’s a librtmp bug which also affects FFmpeg’s implementation, or
youtube-dl’s CR extractor is omitting rtmpdump parameters it shouldn’t.

It’s kind of a pain for me to test that theory though, because I never get 
Level 3 (it’s much more likely in the US).

**Comment by betacris** [comment]
I see.... well that sucks. I guess I have to go back to livestreamer... sucks I am hooked on CR @60 FPS ... i cant go back lol

**Comment by dstftw** [comment]
Should work in the next version.
