### ISSUE TITLE
Revive youtube-dl Wikipedia article

### ISSUE THREAD

**Issue by davidhedlund** [rg3/youtube-dl#5549]
I'm blocked from Wikipedia so I'm asking someone else to work on this task.

https://en.wikipedia.org/wiki/Youtube-dl said:
>This page has been deleted. The deletion and move log for the page are provided below for reference.
>04:44, 3 December 2014 Mojo Hand (talk | contribs) deleted page Youtube-dl (Expired PROD, concern was: No indication of notability) (Tag: HHVM)

+"youtube-dl" yields 113,000,000 Google hits.

4KDownload yields 171,000 Google hits (~600 x less than youtube-dl), still its in https://en.wikipedia.org/wiki/4KDownload.

The youbube-dl software is very popular, isn't this notable enough?

**Comment by jaimeMF** [comment]
Closing this since it's not our problem.

**Comment by davidhedlund** [comment]
Moved discussion to https://en.wikipedia.org/wiki/Talk:Youtube-dl
