### ISSUE TITLE
ERROR "youtube-dl: error: no such option: --max-quality"

### ISSUE THREAD

**Issue by artphotodude** [rg3/youtube-dl#5550]
After today's update, getting this.  
youtube-dl: error: no such option: --max-quality

Also, have had two updates recently that had to be rolled back - is there a server issue??

**Comment by artphotodude** [comment]
P.S.  Just checked on another computer.  The same error.

**Comment by smolleyes** [comment]
same error here and -h do not report --max-quality

**Comment by smolleyes** [comment]
and working stream seems very long to start Oo

**Comment by phihag** [comment]
The option `--max-quality` has been removed in the current release of youtube-dl (since it hasn't been useful for quite a while now). Please remove it from any configuration files you may have.

**Comment by artphotodude** [comment]
On 4/28/15 8:56 PM, Philipp Hagemeister wrote:
>
> Closed #5550 <https://github.com/rg3/youtube-dl/issues/5550>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rg3/youtube-dl/issues/5550#event-292648997>.
>
Well a LOT of people who use it on PPC Macs all over the world will
disagree with you on that. Not every computer can run Flash or HD video.
This is very regrettable.

**Comment by peseriusz** [comment]
So is there other way to download movies in lower quality ?

**Comment by artphotodude** [comment]
I would be willing to maintain a legacy-branch of this that keeps the new scrapers compatible with SD-only computer systems.

**Comment by jaimeMF** [comment]
Just use `-f best[height<=?640]` (or some other resolution), for more info read [this doc](https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection). `--max-quality` didn't play well with dash formats and it wouldn't work correctly in some cases.

**Comment by artphotodude** [comment]
In this case, does it allow for non-exact matches the way the old one would: meaning will download desired value where available, but otherwise will grab what is there?

Or does it return an error that the desired format is not available?

**Comment by jaimeMF** [comment]
If the format has a known height and it's higher than 640 it won't be considerer, otherwise the format is included in the list of possible formats and `best` picks the best one of them (it won't pick DASH video only formats). If all the formats have a know height, but none of them is lower than 640, it will fail. If you want to avoid that, you can use `-f best[height<=?640]/best`, which will fallback to the default value.

**Comment by artphotodude** [comment]
That is very cool.  ONE last question, is there a way to completely disallow DASH?

**Comment by jaimeMF** [comment]
Read the last paragraph in [this section of the README](https://github.com/rg3/youtube-dl/blob/40b96352c99953aec9272574729077c06c235747/README.md#format-selection)

**Comment by artphotodude** [comment]
so there is no way to do say a 480 as a single file every-time?  what about if we do 
-f best[height<=?480] flv/mp4/mov/3gp/avi  ?
This seems weird as DASH is pretty difficult to handle for a lot of media devices.

**Comment by jaimeMF** [comment]
`-f best[height<=?480]/best` should be enough since it won't match any DASH format (since the are missing either video or audio)

**Comment by artphotodude** [comment]
I just tried that and in the case of youtube, the only 480 was DASH, so that is what I got.  The 240 and 720 were fine, since they were available as normal formats.

**Comment by artphotodude** [comment]
BTW, it was only a Video-Only DASH 480.

**Comment by jaimeMF** [comment]
It shouldn't pick the DASH format, we'll need [the verbose output](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) in a new issue.

**Comment by artphotodude** [comment]
Will Do.

**Comment by artphotodude** [comment]
I just found out that I had '=' instead of '<='.  Is fine now.  Do you still want the output - happy to help.  I guess the '=' backed it into a corner.

**Comment by jaimeMF** [comment]
Yes please, I think I can reproduce it, but I'm not sure.

**Comment by artphotodude** [comment]
Sorry about the delay - had to give me dog a bath.  
Here you go.  So once again, this downloads a video-only DASH version.
--------
Welcome to Darwin!
Adams-G4:~ adamalbrec$ youtube-dl -v -f best[height=480] https://www.youtube.com/watch?v=_PNBF_LGrfM
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'best[height=480]', u'https://www.youtube.com/watch?v=_PNBF_LGrfM']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2015.04.28
[debug] Python version 2.7.8 - Darwin-8.11.0-Power_Macintosh-powerpc-32bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] _PNBF_LGrfM: Downloading webpage
[youtube] _PNBF_LGrfM: Extracting video information
[youtube] _PNBF_LGrfM: Downloading DASH manifest
[debug] Invoking downloader on 'https://r6---sn-qxo7sn7k.googlevideo.com/videoplayback?id=fcf34117f2c6adf3&itag=135&source=youtube&requiressl=yes&mm=31&ms=au&mv=m&pl=16&ratebypass=yes&mime=video/mp4&gir=yes&clen=27477814&lmt=1430256318389239&dur=339.714&mt=1430327681&key=dg_yt0&fexp=900720,907263,934954,938028,9406690,9407588,9407877,9408007,9408705,9408710,9408787,9409205,9409230,9412839,9413011,9413149,947233,948124,952612,952637,957201&sver=3&upn=tPFdYxEOYkM&signature=6F146691843968AD129BD05B140922A1ABD65D96.97DE5911E48E99520EE5208297519740AF696615&ip=97.115.165.13&ipbits=0&expire=1430349373&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,ms,mv,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Classic Game Room - QUICK STEP review for Atari 2600-_PNBF_LGrfM.mp4
[download] 100% of 26.20MiB in 00:34
--------

**Comment by jaimeMF** [comment]
@artphotodude open [a new issue](https://github.com/rg3/youtube-dl/issues/new)

**Comment by artphotodude** [comment]
OK - so I am TOTALLY LOVING this new thing!  Since my player is aimed at so many types of Mac computers (PPC G4-Single CPU -> all the way up to -> Intel 12-Core), I really needed to be able to select on the fly:  This mean having to manually configure site-profiles for nearly 100 sites!!  Now it can do it dynamically for any site it encounters.

While I am not still sure what use DASH is (unless nothing else is available), I have changed my quality-selector array to this:  

set QualityCodes to {"-f 'best[height<=240]/best[height<=360]/best[height<=720]/best'", "-f 'best[height<=360]/best[height<=720]/best'", "-f 'best[height<=720]/best'"}

This way I can select 240p, 360p and 720p (will likely do 360p/480p/1080p for newer machines with a iniTest) but the best part is if it doesn't see the smallest option, it can now jump up to the next one up, rather than the very best as it used to under max-quality.  VERY GOOD STUFF!!!!  Thanks and sorry doubting earlier.

**Comment by shakeyourbunny** [comment]
Currently, it ignores DASH formats with the height parameter. My goal is to download videos with a video format up to 854x480 and best audio quality.

$ youtube-dl --version
2015.04.28

$ youtube-dl --list-formats  QqdZBqNp7Fc
```
[youtube] QqdZBqNp7Fc: Downloading webpage
[youtube] QqdZBqNp7Fc: Extracting video information
[youtube] QqdZBqNp7Fc: Downloading DASH manifest
[info] Available formats for QqdZBqNp7Fc:
format code  extension  resolution note
140          m4a        audio only DASH audio  130k , m4a_dash container, aac  @128k (44100Hz), 35.66MiB
141          m4a        audio only DASH audio  257k , m4a_dash container, aac  @256k (44100Hz), 71.59MiB
160          mp4        256x144    DASH video  120k , 15fps, video only, 31.20MiB
133          mp4        426x240    DASH video  259k , 25fps, video only, 69.19MiB
134          mp4        640x360    DASH video  482k , 25fps, video only, 114.94MiB
135          mp4        854x480    DASH video 1111k , 25fps, video only, 258.82MiB
136          mp4        1280x720   DASH video 2224k , 25fps, video only, 577.36MiB
17           3gp        176x144
36           3gp        320x240
5            flv        400x240
43           webm       640x360
18           mp4        640x360
22           mp4        1280x720   (best)
```
$ youtube-dl -v --format="best[height<=480]+bestaudio"  QqdZBqNp7Fc
I would expect this selecting format 135 for video and 141 for audio, mixing them into one file, but the result is a combination of the video part of 18 + 141 ...

please forgive the warning message for avconv, this is Debian 7 stable and have nothing to do with the format selection, the file is muxed correctly after downloading.
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--format=best[height<=480]+bestaudio', u'QqdZBqNp7Fc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.28
[debug] Python version 2.7.3 - Linux-3.2.0-4-686-pae-i686-with-debian-7.8
[debug] exe versions: avconv 1.0.10, avprobe 1.0.10, ffmpeg 1.0.10, ffprobe 1.0.10
[debug] Proxy map: {}
[youtube] QqdZBqNp7Fc: Downloading webpage
[youtube] QqdZBqNp7Fc: Extracting video information
[youtube] QqdZBqNp7Fc: Downloading DASH manifest
[debug] Invoking downloader on u'https://r3---sn-apfxnu-ao1l.googlevideo.com/videoplayback?expire=1430353718&ratebypass=yes&upn=KeiQlvvHMR8&id=o-AA9P_fWvfbq3Sp70YMdtf72V-7okw5F21rtCKHPusvjM&dur=2354.596&fexp=900720%2C907263%2C934954%2C938028%2C9406986%2C9408142%2C9408710%2C942901%2C947233%2C948124%2C952612%2C952637%2C957201&mm=31&signature=9D4CDC45467D5A13560A85AFE1D4A55ECCC1D720.8A4999FE187D18A9E42EABEE0D41A3F7A02D8F83&sver=3&source=youtube&ms=au&mt=1430331998&ip=86.56.144.59&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=video%2Fmp4&requiressl=yes&itag=18&key=yt5&mv=m&initcwndbps=1702500&ipbits=0&pl=22'
[download] Resuming download at byte 17345276
[download] Destination: Frag den Martin - Die Antworten-QqdZBqNp7Fc.f18.mp4
[download] 100% of 168.10MiB in 01:25
[debug] Invoking downloader on 'https://r3---sn-apfxnu-ao1l.googlevideo.com/videoplayback?id=42a75906a369ec57&itag=141&source=youtube&requiressl=yes&mm=31&pl=22&mv=m&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=75069924&lmt=1373432786062433&dur=2354.596&key=dg_yt0&signature=5BC873EDCBEF08B7C27F8C980C0CABB38AF4900C.73BB8D8971DE942F537CF650FF735555E57FE63B&sver=3&mt=1430331998&upn=KeiQlvvHMR8&fexp=900720,907263,934954,938028,9406986,9408142,9408710,942901,947233,948124,952612,952637,957201&ip=186.33.124.59&ipbits=0&expire=1430353718&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,pl,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Frag den Martin - Die Antworten-QqdZBqNp7Fc.f141.m4a
[download] 100% of 71.59MiB in 00:39
[ffmpeg] Merging formats into "Frag den Martin - Die Antworten-QqdZBqNp7Fc.mp4"
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
[debug] ffmpeg command line: avconv -y -i 'Frag den Martin - Die Antworten-QqdZBqNp7Fc.f18.mp4' -i 'Frag den Martin - Die Antworten-QqdZBqNp7Fc.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'Frag den Martin - Die Antworten-QqdZBqNp7Fc.temp.mp4'
Deleting original file Frag den Martin - Die Antworten-QqdZBqNp7Fc.f18.mp4 (pass -k to keep)
Deleting original file Frag den Martin - Die Antworten-QqdZBqNp7Fc.f141.m4a (pass -k to keep)
```

**Comment by dstftw** [comment]
@shakeyourbunny this is because it should be `bestvideo[height<=480]` and not just `best[height<=480]`.

**Comment by artphotodude** [comment]
What is because of best[height<=480]?  It is working.

**Comment by dstftw** [comment]
@artphotodude my last message was addressed not to you.

**Comment by shakeyourbunny** [comment]
thank you, I didn't know that bestvideo existed.
