### ISSUE TITLE
best[height=] downloads Video-Only DASH when height is only available in DASH...

### ISSUE THREAD

**Issue by artphotodude** [rg3/youtube-dl#5554]
As requested, here is a verbose output of a youtube 'best[height=]' option that is downloading video-only DASH.  As stated before, I was able to get around it by doing '<=' instead of '='.   This seems to be a script-glitch from asking it to pull a resolution that is only available in DASH.

-------

youtube-dl -v -f best[height=480] https://www.youtube.com/watch?v=_PNBF_LGrfM
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'best[height=480]', u'https://www.youtube.com/watch?v=_PNBF_LGrfM']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2015.04.28
[debug] Python version 2.7.8 - Darwin-8.11.0-Power_Macintosh-powerpc-32bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] _PNBF_LGrfM: Downloading webpage
[youtube] _PNBF_LGrfM: Extracting video information
[youtube] _PNBF_LGrfM: Downloading DASH manifest
[debug] Invoking downloader on 'https://r6---sn-qxo7sn7k.googlevideo.com/videoplayback?id=fcf34117f2c6adf3&itag=135&source=youtube&requiressl=yes&mm=31&ms=au&mv=m&pl=16&ratebypass=yes&mime=video/mp4&gir=yes&clen=27477814&lmt=1430256318389239&dur=339.714&mt=1430327681&key=dg_yt0&fexp=900720,907263,934954,938028,9406690,9407588,9407877,9408007,9408705,9408710,9408787,9409205,9409230,9412839,9413011,9413149,947233,948124,952612,952637,957201&sver=3&upn=tPFdYxEOYkM&signature=6F146691843968AD129BD05B140922A1ABD65D96.97DE5911E48E99520EE5208297519740AF696615&ip=97.115.165.13&ipbits=0&expire=1430349373&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,ms,mv,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Classic Game Room - QUICK STEP review for Atari 2600-_PNBF_LGrfM.mp4
[download] 100% of 26.20MiB in 00:34

**Comment by dstftw** [comment]
There are no *exactly-480-height* non-DASH videos by that link. What would you expect to happen in this case? Throwing an error that requested format is not available?

**Comment by artphotodude** [comment]
I know.  jaimeMF asked me to post this as a new issue.  They said that best[height] should not pass DASH and want to track it down.

**Comment by rg3** [comment]
Cross-referencing issue #5550

**Comment by dstftw** [comment]
@jaimeMF what do you think should we do? Throwing format not available error may break use flow of audio only extractors like soundcloud. Implementing `best` similarly to [`worst`](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L920) will still end up in fallback to audio/video-only formats when filter is not satisfied.

**Comment by shakeyourbunny** [comment]
Its related to this matter I moved this here from another thread, because I think it is more fitting:

Currently, it ignores DASH formats with the height parameter if you use <= instead of =. My goal is to download videos with a video format up to 854x480 and best audio quality.

$ youtube-dl --version
2015.04.28

$ youtube-dl --list-formats  QqdZBqNp7Fc
```
[youtube] QqdZBqNp7Fc: Downloading webpage
[youtube] QqdZBqNp7Fc: Extracting video information
[youtube] QqdZBqNp7Fc: Downloading DASH manifest
[info] Available formats for QqdZBqNp7Fc:
format code  extension  resolution note
140          m4a        audio only DASH audio  130k , m4a_dash container, aac  @128k (44100Hz), 35.66MiB
141          m4a        audio only DASH audio  257k , m4a_dash container, aac  @256k (44100Hz), 71.59MiB
160          mp4        256x144    DASH video  120k , 15fps, video only, 31.20MiB
133          mp4        426x240    DASH video  259k , 25fps, video only, 69.19MiB
134          mp4        640x360    DASH video  482k , 25fps, video only, 114.94MiB
135          mp4        854x480    DASH video 1111k , 25fps, video only, 258.82MiB
136          mp4        1280x720   DASH video 2224k , 25fps, video only, 577.36MiB
17           3gp        176x144
36           3gp        320x240
5            flv        400x240
43           webm       640x360
18           mp4        640x360
22           mp4        1280x720   (best)
```
$ youtube-dl -v --format="best[height<=480]+bestaudio"  QqdZBqNp7Fc
I would expect this selecting format 135 for video and 141 for audio, mixing them into one file, but the result is a combination of the video part of 18 + 141 ...

please forgive the warning message for avconv, this is Debian 7 stable and have nothing to do with the format selection, the file is muxed correctly after downloading.
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--format=best[height<=480]+bestaudio', u'QqdZBqNp7Fc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.28
[debug] Python version 2.7.3 - Linux-3.2.0-4-686-pae-i686-with-debian-7.8
[debug] exe versions: avconv 1.0.10, avprobe 1.0.10, ffmpeg 1.0.10, ffprobe 1.0.10
[debug] Proxy map: {}
[youtube] QqdZBqNp7Fc: Downloading webpage
[youtube] QqdZBqNp7Fc: Extracting video information
[youtube] QqdZBqNp7Fc: Downloading DASH manifest
[debug] Invoking downloader on u'https://r3---sn-apfxnu-ao1l.googlevideo.com/videoplayback?expire=1430353718&ratebypass=yes&upn=KeiQlvvHMR8&id=o-AA9P_fWvfbq3Sp70YMdtf72V-7okw5F21rtCKHPusvjM&dur=2354.596&fexp=900720%2C907263%2C934954%2C938028%2C9406986%2C9408142%2C9408710%2C942901%2C947233%2C948124%2C952612%2C952637%2C957201&mm=31&signature=9D4CDC45467D5A13560A85AFE1D4A55ECCC1D720.8A4999FE187D18A9E42EABEE0D41A3F7A02D8F83&sver=3&source=youtube&ms=au&mt=1430331998&ip=86.56.144.59&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=video%2Fmp4&requiressl=yes&itag=18&key=yt5&mv=m&initcwndbps=1702500&ipbits=0&pl=22'
[download] Resuming download at byte 17345276
[download] Destination: Frag den Martin - Die Antworten-QqdZBqNp7Fc.f18.mp4
[download] 100% of 168.10MiB in 01:25
[debug] Invoking downloader on 'https://r3---sn-apfxnu-ao1l.googlevideo.com/videoplayback?id=42a75906a369ec57&itag=141&source=youtube&requiressl=yes&mm=31&pl=22&mv=m&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=75069924&lmt=1373432786062433&dur=2354.596&key=dg_yt0&signature=5BC873EDCBEF08B7C27F8C980C0CABB38AF4900C.73BB8D8971DE942F537CF650FF735555E57FE63B&sver=3&mt=1430331998&upn=KeiQlvvHMR8&fexp=900720,907263,934954,938028,9406986,9408142,9408710,942901,947233,948124,952612,952637,957201&ip=186.33.124.59&ipbits=0&expire=1430353718&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,pl,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Frag den Martin - Die Antworten-QqdZBqNp7Fc.f141.m4a
[download] 100% of 71.59MiB in 00:39
[ffmpeg] Merging formats into "Frag den Martin - Die Antworten-QqdZBqNp7Fc.mp4"
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
[debug] ffmpeg command line: avconv -y -i 'Frag den Martin - Die Antworten-QqdZBqNp7Fc.f18.mp4' -i 'Frag den Martin - Die Antworten-QqdZBqNp7Fc.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'Frag den Martin - Die Antworten-QqdZBqNp7Fc.temp.mp4'
Deleting original file Frag den Martin - Die Antworten-QqdZBqNp7Fc.f18.mp4 (pass -k to keep)
Deleting original file Frag den Martin - Die Antworten-QqdZBqNp7Fc.f141.m4a (pass -k to keep)
```

**Comment by jaimeMF** [comment]
I thought that `best` would only select non-DASH formats, but it doesn't (and it have never worked like that). Maybe we should do like with `worst`, but without falling back to DASH formats. For audio only extractors it should work as now, I have to look if it can be easily implemented.

It's just my opinion, maybe you disagree.

**Comment by jaimeMF** [comment]
I have opened a PR with the proposed change: #5554.

**Comment by dstftw** [comment]
This will be fixed in the next version. Thanks for the report.
