### ISSUE TITLE
error: no such option: --hls-prefer-native

### ISSUE THREAD

**Issue by rhpt** [rg3/youtube-dl#5555]
Trying to use the --hls-prefer-native option with the latest version (2015.02.06) on a Mac, and youtube-dl reports the following error `error: no such option: --hls-prefer-native`

**Comment by dstftw** [comment]
2015.02.06 is not the latest version. `--hls-prefer-native` has been introduced in 2015.02.17. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
