### ISSUE TITLE
After running "youtube-dl -U", I get "Your copy of avconv is outdated update avconv to version 10-0 or newer if you encounter any errors."

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#5558]

**Comment by jaimeMF** [comment]
You can try updating avconv (old versions may not support some of the formats used by YouTube). If you want to disable merging DASH formats, you can add `-f best` to your [configuration file](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration).

If youtube-dl doesn't work, we'll need [the output you get with the --verbose option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) for debugging the problem

**Comment by hub2git** [comment]
What is the recommended way to proceed? Update anconv or disable merging dash formats? This ubuntuforum thread (http://ubuntuforums.org/showthread.php?t=2277302) makes me think that choosing well is crucial.

**Comment by jaimeMF** [comment]
if you want to get resolutions higher that 1280p you'll have to update avconv, if you don't mind which resolution you get you can disable merging.

**Comment by hub2git** [comment]
hi, jamieMF. thanks for your comment. I don't need resolutions higher than 1280p.

**Comment by hub2git** [comment]
so i guess i'm fine with the other method.

**Comment by hub2git** [comment]
How exactly do I update avconv?

**Comment by yan12125** [comment]
What's your operating system? If you're using ubuntu, ```apt-get``` is your friend.

**Comment by hub2git** [comment]
yan,
Linux Mint. I already have avconv, so how does apt-get help?

**Comment by yan12125** [comment]
I'm not familiar with Linux MInt, while I think it's similar to Ubuntu. The following commands may help:
```
sudo apt-get update
sudo apt-get upgrade
```
How to update avconv is out of the scope of youtube-dl. A Linux Mint forum should give you more information on it.
