### ISSUE TITLE
Fix python shebang

### ISSUE THREAD

**Issue by EricBelanger** [rg3/youtube-dl#556]
The python shebang at the begining of the files:
# !/usr/bin/env python

should be changed to:
# !/usr/bin/env python2

as recommended in PEP 394[1]. This change will make youtube-dl work out of the box on distros like Arch Linux where python is a symlink to python3. Currently, I need to unzip the python archive, change the shebang and rezip everything which is messy.

Thanks.

[1]http://www.python.org/dev/peps/pep-0394/

**Comment by corlaez** [comment]
Ubuntu 20.04 has python3 installed but python is not defined. If you don't want to modify any config you can make it work with:

    python3 $(which youtube-dl)
