### ISSUE TITLE
Major bug with --load-info and -g [2015.04.26]

### ISSUE THREAD

**Issue by MoSal** [rg3/youtube-dl#5562]
Hello.

This works correctly:

    youtube-dl -g -f 171 'https://www.youtube.com/watch?v=U6XFJaccpLo'

This returns 2 URLs, both are wrong:

    youtube-dl --no-playlist --write-info-json --skip-download 'https://www.youtube.com/watch?v=U6XFJaccpLo'
    youtube-dl -g -f 171 --load-info 'Nepal earthquake - First aerial shot of Kathmandu Patan Durbar Square since earthquake-U6XFJaccpLo.info.json'

This previous version I had which didn't have this bug was [2015.04.17].

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
