### ISSUE TITLE
add support for smithsonianmag.com

### ISSUE THREAD

**Issue by Siddhant** [rg3/youtube-dl#5569]
Example URL: http://www.smithsonianmag.com/videos/category/history/the-reason-why-dc-is-between-maryland-and-vi/

**Comment by yan12125** [comment]
The link you provide is already supported. If you have any problem, feel free to open a new issue. Don't forget to include [the full verbose log](https://github.com/rg3/youtube-dl#bugs).

**Comment by Siddhant** [comment]
No, it is not supported.

youtube-dl --verbose "http://www.smithsonianmag.com/videos/category/history/the-reason-why-dc-is-between-maryland-and-vi/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.smithsonianmag.com/videos/category/history/the-reason-why-dc-is-between-maryland-and-vi/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.8 - Linux-3.16.0-37-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6
[debug] Proxy map: {}
[generic] the-reason-why-dc-is-between-maryland-and-vi: Requesting header
[redirect] Following redirect to http://www.smithsonianmag.com/ist/?next=/videos/category/history/the-reason-why-dc-is-between-maryland-and-vi/
[generic] the-reason-why-dc-is-between-maryland-and-vi: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-reason-why-dc-is-between-maryland-and-vi: Downloading webpage
[generic] the-reason-why-dc-is-between-maryland-and-vi: Extracting information
ERROR: Unsupported URL: http://www.smithsonianmag.com/ist/?next=/videos/category/history/the-reason-why-dc-is-between-maryland-and-vi/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 937, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 87, column 44
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1467, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.smithsonianmag.com/ist/?next=/videos/category/history/the-reason-why-dc-is-between-maryland-and-vi/

**Comment by yan12125** [comment]
Seems they've changed something. The original link brings you to an advertisement page, which contains no videos. And the page after clicking "Continue to our site", http://www.smithsonianmag.com/videos/category/history/the-reason-why-dc-is-between-maryland-and-vi/?no-ist, can be downloaded by youtube-dl.

**Comment by Siddhant** [comment]
Well, in my browser, I see the original link. (Note: Once you have clicked on "Continue to our site", any further browsing on the site is not interrupted with ads. So you see the original links for subsequent pages and not the "?next=t" version.) What youtube-dl needs to do to skip the ad page *if* it encounters the ad page.
Please consider reopening this issue.

**Comment by yan12125** [comment]
As a temporary workaround, you can use the option ```--cookies``` to mimic what browsers do (skip the ads from the second time). For example:
```
youtube-dl --cookies ~/path/to/cookies.txt http://www.smithsonianmag.com/videos/category/history/the-reason-why-dc-is-between-maryland-and-vi/
```
If you don't want to specify this option every time, have a look at [configuration files](https://github.com/rg3/youtube-dl#configuration).

**Comment by remitamine** [comment]
```
youtube-dl -f best http://www.smithsonianmag.com/videos/category/history/the-reason-why-dc-is-between-maryland-and-vi/
[generic] the-reason-why-dc-is-between-maryland-and-vi: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-reason-why-dc-is-between-maryland-and-vi: Downloading webpage
[generic] the-reason-why-dc-is-between-maryland-and-vi: Extracting information
[Ooyala] R0NHhrdDqdLyGh7bEZnCaRK9MJMZdmLg: Downloading JSON metadata
[Ooyala] R0NHhrdDqdLyGh7bEZnCaRK9MJMZdmLg: Downloading JSON metadata
[Ooyala] R0NHhrdDqdLyGh7bEZnCaRK9MJMZdmLg: Downloading f4m manifest
[Ooyala] R0NHhrdDqdLyGh7bEZnCaRK9MJMZdmLg: Downloading m3u8 information
WARNING: ar subtitles not available for R0NHhrdDqdLyGh7bEZnCaRK9MJMZdmLg
[info] Writing video subtitles to: The Reason Why DC Is Between Maryland and Virginia-R0NHhrdDqdLyGh7bEZnCaRK9MJMZdmLg.en.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 20
[download] Destination: The Reason Why DC Is Between Maryland and Virginia-R0NHhrdDqdLyGh7bEZnCaRK9MJMZdmLg.mp4
[download]   1.0% of ~51.90MiB at 256.13KiB/s ETA 04:21
```
