### ISSUE TITLE
The reject title function is not working.

### ISSUE THREAD

**Issue by WeWin55** [rg3/youtube-dl#5573]
Hello,

I want to download Youtube Videos from a german Youtuber.
All except some, so I did a --reject-title "xxx" for every videotype I dont want to download.
Here is my "test" download script:

youtube-dl -f 140 -w --reject-title "Creed" --reject-title "BLOODBORNE" --reject-title "HEX" --reject-title "LEAGUE" --reject-title "STORM" --date $(date +"%Y%m%d") "https://www.youtube.com/user/PietSmittie/videos"

Youtube-dl is downloading the videos, but also the videos I rejected e.g. Bloodborne videos.

I hope you know a fix for my problem. BTW very very very nice program you coded!

Ah i got another little problem youtube-dl is always reporting "WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors."

Ive read a lot about that problem (on github here too) and did a lot, but i cant get it fixed.
But youtube-dl is working with the warning so all is fine:)

**Comment by dstftw** [comment]
There should be only one `--reject-title` option and you should pass regular expression `--reject-title "bloodbornehex|league|storm"`, it is case insensitive.
As for outdated avconv you may want to update it as suggested. That depends on how you installed it.

**Comment by WeWin55** [comment]
Okay I will test it. Thanks for the fast reply, I will test it in a minute.
I never installed it. Its weird..
