### ISSUE TITLE
[YouPorn] ERROR: Unable to extract JSON parameters

### ISSUE THREAD

**Issue by zay11** [rg3/youtube-dl#5577]
youtube-dl -v http://www.youporn.com/watch/360586/nice-orgasm/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.youporn.com/watch/360586/nice-orgasm/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.28
[debug] Python version 3.4.3 - Linux-3.19.3-3-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[YouPorn] 360586: Downloading webpage
ERROR: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 276, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youporn.py", line 52, in _real_extract
    webpage, 'JSON parameters')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 558, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
That's already fixed and will be available in the next version.
