### ISSUE TITLE
New youtube-dl G.U.I. for OSX/Macs...

### ISSUE THREAD

**Issue by artphotodude** [rg3/youtube-dl#5586]
Sorry, am pretty sure that this not the perfect place to post this, but not sure where else to reach youtube-dl enthusiasts. 

Just finished a hot-key driven G.U.I. for youtube-dl that will save, play (through QuickTime) and make MP3s with just button-clicks and auto-updates (the first time used each new day - don't worry won't overwhelm you all).  Best of all it is compatible with all Macs from PPC/G4s running 10.4 all the way up to Intels running 10.10.  It is all coded in Applescript and totally user-modifiable. A decent Read Me is also included with pictures.

The Mavericks/Yosemite version can be found here:
https://www.dropbox.com/s/bgzokatluzhju8l/PPC%20Media%20Center%20-%205.0y%20%28Mavericks%3AYosemite%29.zip?dl=0
This version is somewhat less interactive (limitations on Applescript since 10.9, but still much easier than command-line). 

The Universal Version (10.4-10.8) is here:
https://www.dropbox.com/s/d4y04v8c4qoa3o1/PPC%20Media%20Center%20-%205.0%20%28Universal%29.zip?dl=0

It has an additional benefit of being able to play multi-segmented videos with QuickTime. Just close the current QuickTime window when it is done, and the next segment will open in a new one, until they are all played.
Also, notes to Homebrew/Macports users are also included in this one, to make modifications for specialized Python configs.

**Comment by dstftw** [comment]
Offtopic.

**Comment by artphotodude** [comment]
Sorry dstftw.  I have just had a number of people there inquire before about Intel versions of this, and there is no non-issues forum.  Might be nice to have a place to post to other users, other than service requests.

**Comment by dstftw** [comment]
Even if there were a non-issue forum, it's not the right place for discussions on 3rd party software. You can easily create a repository, here on github, for your project and
>have a place to post to other users
