### ISSUE TITLE
Videomega not working

### ISSUE THREAD

**Issue by celebnavin** [rg3/youtube-dl#5593]
Hi, 

Videomega has recently changed it's embedded url. The format has changed to
http://videomega.tv/validatehash.php?hashkey=uniquehashkeyof60numbers

Please check.

**Comment by celebnavin** [comment]
Logs - 
D:\>youtube-dl.exe --verbose http://videomega.tv/validatehash.php?hash
key=099067089084066071100068098077077098068100071066084089067099
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://videomega.tv/validatehash.php
?hashkey=099067089084066071100068098077077098068100071066084089067099']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.04.28
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] validatehash: Requesting header
WARNING: Could not send HEAD request to http://videomega.tv/validatehash.php?has
hkey=099067089084066071100068098077077098068100071066084089067099: HTTP Error 40
4: Not Found
[generic] validatehash: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 315, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1693, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 442, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 629, in http_error_302
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

**Comment by dstftw** [comment]
HTTP Error 404: Not Found.

**Comment by celebnavin** [comment]
I copied the url from here

<script type="text/javascript" src="http://videomega.tv/validatehash.php?hashkey=055049065054077074052082082055055082082052074077054065049055"></script><script type="text/javascript" src="http://videomega.tv/validateemb.php?width=700&height=430"></script>

it works in the browser..the embedded player, but not working with youtube-dl.

**Comment by dstftw** [comment]
Post the source URL where it is embedded.

**Comment by celebnavin** [comment]
http://videomega.tv/?ref=JWCD9PWUR77RUWP9DCWJ

**Comment by dstftw** [comment]
Does not work for me neither in Firefox nor Chrome (direct/proxy).

**Comment by dstftw** [comment]
Should be fixed in the next version.
