### ISSUE TITLE
Resulting video is only audio

### ISSUE THREAD

**Issue by rodrigoreis22** [rg3/youtube-dl#5595]
youtube-dl version: 2015.04.26

Here's the log:

SYNCING youtube video ZV--oP84V7k to stationfy channel 54c0a91193338d81794ffe3e, playlist None
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-o', u'%(id)s.%(ext)s', u'https://www.youtube.com/watch?v=ZV--oP84V7k']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2015.04.26
[debug] Python version 2.7.9 - Linux-3.13.0-37-generic-x86_64-with-debian-wheezy-sid
[debug] exe versions: avconv 0.8.10-6, avprobe 0.8.10-6, ffmpeg 0.8.10-6, ffprobe 0.8.10-6
[debug] Proxy map: {}
[youtube] ZV--oP84V7k: Downloading webpage
[youtube] ZV--oP84V7k: Extracting video information
WARNING: [youtube] ZV--oP84V7k: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r6---sn-ab5e6m7l.googlevideo.com/videoplayback?sparams=clen%2Cdur%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=video%2Fmp4&upn=Y88XBoMU47I&fexp=900720%2C907263%2C916726%2C924638%2C934954%2C936117%2C937420%2C938028%2C9407117%2C9407422%2C9407876%2C9408580%2C9408704%2C9408787%2C9409179%2C9412527%2C9412715%2C9412774%2C948124%2C948813%2C952612%2C952637%2C952642%2C957201&ipbits=0&lmt=1430633304978736&dur=319.569&key=yt5&ip=54.224.95.89&itag=137&id=o-AMzcY1X1xuytipVAL7WdHnvckWMy82Nb5Ph6OtBckxZR&mm=35&keepalive=yes&signature=5F0C083DA602FEBFD9D8E270053D1B70465DAF8E.7A5BFBE72B5393934FF0856CAB654F8A96D5A4E7&requiressl=yes&sver=3&expire=1430706207&mt=1430677581&mv=s&clen=156372526&ms=pm&source=youtube&pl=24&gir=yes&nh=EAE&ratebypass=yes'
[download] Destination: ZV--oP84V7k.f137.mp4

[download]   0.0% of 149.13MiB at 159.75KiB/s ETA 16:00
[ suppressed lines ]
[download]  99.2% of 149.13MiB at 52.71MiB/s ETA 00:00
[download] 100.0% of 149.13MiB at 52.87MiB/s ETA 00:00
[download] 100% of 149.13MiB in 00:02
[debug] Invoking downloader on u'https://r6---sn-ab5e6m7l.googlevideo.com/videoplayback?sparams=clen%2Cdur%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=audio%2Fmp4&upn=Y88XBoMU47I&fexp=900720%2C907263%2C916726%2C924638%2C934954%2C936117%2C937420%2C938028%2C9407117%2C9407422%2C9407876%2C9408580%2C9408704%2C9408787%2C9409179%2C9412527%2C9412715%2C9412774%2C948124%2C948813%2C952612%2C952637%2C952642%2C957201&ipbits=0&lmt=1430633132503850&dur=319.622&key=yt5&ip=54.224.95.89&itag=140&id=o-AMzcY1X1xuytipVAL7WdHnvckWMy82Nb5Ph6OtBckxZR&mm=35&keepalive=yes&signature=6952F5D37983955F5229989970F195978B974576.1A1AEC7C6A88C929700238A251BF96E788E3416B&requiressl=yes&sver=3&expire=1430706207&mt=1430677581&mv=s&clen=5131807&ms=pm&source=youtube&pl=24&gir=yes&nh=EAE&ratebypass=yes'
[download] Destination: ZV--oP84V7k.f140.m4a
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.

[download]   0.0% of 4.89MiB at 406.50KiB/s ETA 00:12
[download]   0.1% of 4.89MiB at  1.08MiB/s ETA 00:04
[download]   0.1% of 4.89MiB at  2.38MiB/s ETA 00:02
[download]   0.3% of 4.89MiB at  4.86MiB/s ETA 00:01
[download]   0.6% of 4.89MiB at  9.15MiB/s ETA 00:00
[download]   1.3% of 4.89MiB at 12.02MiB/s ETA 00:00
[download]   2.5% of 4.89MiB at 15.60MiB/s ETA 00:00
[download]   5.1% of 4.89MiB at 21.64MiB/s ETA 00:00
[download]  10.2% of 4.89MiB at 23.63MiB/s ETA 00:00
[download]  20.4% of 4.89MiB at 28.61MiB/s ETA 00:00
[download]  40.8% of 4.89MiB at 34.11MiB/s ETA 00:00
[download]  81.7% of 4.89MiB at 44.10MiB/s ETA 00:00
[download] 100.0% of 4.89MiB at 48.09MiB/s ETA 00:00
[download] 100% of 4.89MiB in 00:00
[ffmpeg] Merging formats into "ZV--oP84V7k.mp4"
[debug] ffmpeg command line: avconv -y -i ZV--oP84V7k.f137.mp4 -i ZV--oP84V7k.f140.m4a -c copy -map 0:v:0 -map 1:a:0 ZV--oP84V7k.temp.mp4
Deleting original file ZV--oP84V7k.f137.mp4 (pass -k to keep)
Deleting original file ZV--oP84V7k.f140.m4a (pass -k to keep)

**Comment by dstftw** [comment]
Update avconv/ffmpeg. Or download single file media using option `-f best`.

**Comment by rodrigoreis22** [comment]
Yes. I'm using the -f best option now. I just wanted to let you guys know about this.. maybe in this case the program should raise an error and don't generate an output.

**Comment by dstftw** [comment]
We can't be absoutely sure if resulting video is broken or not. There is already a
>WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.

that you have just ignored.
