### ISSUE TITLE
Youtube_Help folder?

### ISSUE THREAD

**Issue by TarekSalama** [rg3/youtube-dl#5596]
I get sometimes get a "YouTube_Help" folder with a Youtube video inside it that plays a looping message as shown in the image below in different languages.
![screenshot 2015-05-03 23 06 04](https://cloud.githubusercontent.com/assets/11663696/7446932/099e8fe8-f1e9-11e4-8f61-f9a5fd23c00a.png)

The problem is, I got it while downloading a bunch of Youtube links and I was never able to tell which link or video caused this video to appear.

Any idea what's happening?

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by TarekSalama** [comment]
So I updated and I still got that video downloaded. Any idea why?

**Comment by yan12125** [comment]
Make sure you have version 2015.04.26 or above.
