### ISSUE TITLE
[escapist] Exception when determining formats

### ISSUE THREAD

**Issue by jspenguin** [rg3/youtube-dl#5597]
It looks like Escapist has changed the way formats are handled. The current code requests lq, hq, and hd separately, but they all return the same list of videos, and now data['files']['videos'] is a list of dictionaries with resolution information, not just URLs.

This can be fixed temporarily by the following patch:

    diff --git a/youtube_dl/extractor/escapist.py b/youtube_dl/extractor/escapist.py
    index 8facf11..8a68b51 100644
    --- a/youtube_dl/extractor/escapist.py
    +++ b/youtube_dl/extractor/escapist.py
    @@ -90,8 +90,8 @@ class EscapistIE(InfoExtractor):
                 for i, v in enumerate(data['files']['videos']):
     
                     formats.append({
    -                    'url': v,
    -                    'format_id': determine_ext(v) + '_' + q + str(i),
    +                    'url': v['src'],
    +                    'format_id': determine_ext(v['src']) + '_' + q + str(i),
                         'quality': quality(q),
                     })
     
but this duplicates all of the supported formats and needs a more permanent fix.

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
