### ISSUE TITLE
youtube-dl not reporting the final filename

### ISSUE THREAD

**Issue by kereilly** [rg3/youtube-dl#5602]
I'm a novice at writing python but i did write a program that was working until about a week or so ago. It seems after i updated youtube-dl it no longer reports the final filename. here is my hook:

def my_hook(d):
        if d['status'] == 'finished':
        print "\nYour video has been downloaded!"
        filelocation = d['filename']
        print filelocation

When i run the script i'll get: 
Your video has been downloaded!
/Volumes/RR261-GOING-POSTAL_1/RR261_Archival_Footage/RR261_A999_Erase_Please.f243.webm

Your video has been downloaded!
/Volumes/RR261-GOING-POSTAL_1/RR261_Archival_Footage/RR261_A999_Erase_Please.f141.m4a

So according to the documentation i've got two choices to get filenames
* filename: The final filename (always present)
* tmpfilename: The filename we're currently writing to

shouldn't filename report back the remuxed file that results, which in this case is RR261_A999_Erase_Please.mkv or is this not the way to get the file name that was downloaded. Thanks

**Comment by SleepProgger** [comment]
You can get the resulting filename via the *prepare_filename* function (for example).
```
# Download the file and get the info
info = ydl.extract_info(download=False)
print "filename", ydl.prepare_filename(info)
```

**Comment by kereilly** [comment]
Thanks a bunch. This was exactly what i needed.
