### ISSUE TITLE
'ERROR: content too short' resolved with new IP. Is youtube throttling and could a between-video download delay?

### ISSUE THREAD

**Issue by truth1ness** [rg3/youtube-dl#5603]
There are a number of  'ERROR: content too short' issues and some theories suggest this is due to some problem on Youtube's end. However, I encountered this error downloading very large 400+ playlist (error at around 270) and on successive retries but was able to get it to work immediately after switching to a new IP address through VPN. In my limited experience this usually indicates some kind of active throttling/banning of IP's hitting the servers above a certain threshold. I wonder if this is the cause behind most of the other reported issues with this error and I propose a 'delay between videos' setting might help as Youtube might not like the instant back to back downloads.

**Comment by dstftw** [comment]
```
--sleep-interval SECONDS         Number of seconds to sleep before each
                                 download.
```
