### ISSUE TITLE
autonumber-size flag question

### ISSUE THREAD

**Issue by truth1ness** [rg3/youtube-dl#5604]
Am I using --autonumber-size incorrectly? The command below works without it but when I add this flag it gives the error below. I have tried with and without quotes around the 3 as well as placed it before and after the -o format flag. Am I doing something wrong or is this a bug? 

```
youtube-dl --no-check-certificate --autonumber-size '3' -o "%(autonumber)s-%(title)s.%(ext)s" https://www.youtube.com/playlist?list=PLAwxTw4SYaPnJVt[DPvZZ5zXj_wRBjH0FxX

[youtube:playlist] PLAwxTw4SYaPnJVt: Downloading webpage
ERROR: The playlist doesn't exist or is private, use --username or --netrc to access it.
taskdone
```

**Comment by dstftw** [comment]
Argument of `--autonumber-size` option should not contain anything but digits, e.g. `--autonumber-size 3`.
By the way avoid using `--no-check-certificate`, if you care about security.

**Comment by truth1ness** [comment]
Thanks. 

Oh, I thought --no-check-certificate is only a security issue if you are sending login credentials. I'm trying to troubleshoot it but in the meantime can anything worse than someone seeing what videos I'm downloading happen?

**Comment by jaimeMF** [comment]
If they can see what you are downloading (which is bad by itself), they can also manipulate the content you download (instead of a video you can get any kind of file). I don't know how much damage that can do, but you should be aware.
