### ISSUE TITLE
Download multiple playlists to their own autonamed folders? 

### ISSUE THREAD

**Issue by truth1ness** [rg3/youtube-dl#5606]
So I'm not sure if this is even possible but I thought I'd give it a try. I put the %(playlist_title) tag as the subdirectory in the -o template like this ```-o "/Users/mmarotta/code/testenv3/%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s"```. However it created a folder name NA and didn't get to the second playlist. Is this because youtube-dl can't do multiple playlists at once or because it can't put variables into the folder name or both? Is what I'm trying possible at the moment? Is it possible to autoname even one folder? 

youtube-dl -o "/Users/[user]/code/testenv3/%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s" https://www.youtube.com/watch?v=Cgm3r-G0cMQ&index=1&list=PLAwxTw4SYaPk41og7PER4HBpGciPw6n3x https://www.youtube.com/playlist?list=PLAwxTw4SYaPnJVtPvZZ5zXj_wRBjH0FxX

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs). At least first screen.

**Comment by truth1ness** [comment]
Oh, I got it to work, it was a url mistake. Marking as closed.
