### ISSUE TITLE
Cant get youtube-dl get working as an function

### ISSUE THREAD

**Issue by WeWin55** [rg3/youtube-dl#5607]
So I dont know why I cant get youtube-dl get working as a function.
I tested also to just do loady --help but that doesnt work either.
I need help. Sry.

Here my test script:
loady () {
        /usr/local/bin/youtube-dl -f 144
}

loady https://www.youtube.com/watch?v=XpTZlXn3pxY

My final code should look like that:

youtube1=""
youtube2="" 
loady () {
        /usr/local/bin/youtube-dl [options]
}

loady $youtube1 $youtube2

**Comment by dstftw** [comment]
Assuming this is shell script, you forgot to specify the arguments when you call youtube-dl that has been passed to your function. It should look alike this:
```
/usr/local/bin/youtube-dl -f 144 $1
```

**Comment by WeWin55** [comment]
No i didnt forget that.
It should get the --reject option and then look at the url but it doesnt.

Here is my script:
(silly github formation, its always one line)

loady () {
	/usr/local/bin/youtube-dl --playlist-end 7 -w -r 1000K --no-mtime  --write-thumbnail --output '%(uploader)s - %(title)s - %(resolution)s.%(ext)s' --date $(date +"%Y%m%d")
}

loady --reject-title "bloodborne|creed|hex|fifa|league|storm" "https://www.youtube.com/user/PietSmittie/videos?&ab_channel=PietSmiet"

**Comment by dstftw** [comment]
Re-read my answer carefully. Arguments you pass to loady outside (`--reject-title`, `"bloodborne|creed|hex|fifa|league|storm"` and `"https://www.youtube.com/user/PietSmittie/videos?&ab_channel=PietSmiet"` in your case) are not passed to youtube-dl call. You can access them within script with `$1` `$2` `$3` and so on or with `$@` array.

**Comment by WeWin55** [comment]
So I have to do?:

1="--reject-title "bloodborne|creed|hex|fifa|league|storm""
2="https://www.youtube.com/user/PietSmittie/videos?&ab_channel=PietSmiet"


loady () {
/usr/local/bin/youtube-dl --playlist-end 7 -w -r 1000K --no-mtime --write-thumbnail --output '%(uploader)s - %(title)s - %(resolution)s.%(ext)s' --date $(date +"%Y%m%d")
}

loady  $1 $2

**Comment by dstftw** [comment]
You are totally misusing it. I suggest you starting [here](http://www.tldp.org/LDP/abs/html/internalvariables.html#ARGLIST).

**Comment by WeWin55** [comment]
ohh I think you mean i should do that:


options="--playlist-end 7 -w -r 1000K --no-mtime --write-thumbnail --output '%(uploader)s - %(title)s - %(resolution)s.%(ext)s' --date $(date +"%Y%m%d")"
url="https://www.youtube.com/user/PietSmittie/videos?&ab_channel=PietSmiet"

/usr/local/bin/youtube-dl $1 §2
