### ISSUE TITLE
Can not more download from netzkino.de

### ISSUE THREAD

**Issue by Renton60** [rg3/youtube-dl#5614]
It's not more possible to download from netzkino.de, the output fron youtube-dl is:

[C:\ProgrammeAlt\Utilities\Youtube-dl]youtube-dl.exe "http://www.netzkino.de/#!/
neu/der-fluch-der-tang-dynastie" --verbose --proxy ""
[debug] System config: []
[debug] User config: [u'-o', u'E:\\Videos\\Eingang\\%(title)s-%(id)s.%(ext)s', u
'--download-archive', u'bekannt.txt']
[debug] Command-line args: [u'http://www.netzkino.de/#!/neu/der-fluch-der-tang-d
ynastie', u'--verbose', u'--proxy', u'']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.04
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[Netzkino] der-fluch-der-tang-dynastie: Downloading JSON metadata
[Netzkino] der-fluch-der-tang-dynastie: Downloading player code
ERROR: Unable to extract URL templates; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 650, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\netzkino.pyo", line 53, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 555, in _search_regex
RegexNotFoundError: Unable to extract URL templates; please report this issue on
 https://yt-dl.org/bug . Make sure you are using the latest version; type  youtu
be-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and incl
ude its complete output.

**Comment by jaimeMF** [comment]
Thansk for the report, it will work in the next version (thanks to @blissland).
