### ISSUE TITLE
Issue with YouTube video

### ISSUE THREAD

**Issue by danieman** [rg3/youtube-dl#5621]
Hi!
I was trying to download this video: https://www.youtube.com/watch?v=heCXjUIvw24
The download goes fine, but it downloads a .webm and a .m4a, which apparently are incompatible for merging.
('WARNING: You have requested formats incompatible for merge. The formats will be merged into mkv')
It still merges them into an .mkv, but it unfortunately becomes unplayable, at least in VLC and QuickTime.

Here is the list of formats:

format code  extension  resolution note
171          webm       audio only DASH audio  129k , audio@128k (44100Hz), 31.37MiB
140          m4a        audio only DASH audio  131k , m4a_dash container, aac  @128k (44100Hz), 37.77MiB
141          m4a        audio only DASH audio  258k , m4a_dash container, aac  @256k (44100Hz), 75.01MiB
278          webm       256x108    DASH video   96k , webm container, VP9, 12fps, video only, 16.49MiB
160          mp4        256x108    DASH video  120k , 12fps, video only, 31.42MiB
133          mp4        426x178    DASH video  254k , 24fps, video only, 71.19MiB
242          webm       426x178    DASH video  331k , 24fps, video only, 29.43MiB
134          mp4        640x268    DASH video  604k , 24fps, video only, 67.28MiB
243          webm       640x268    DASH video  630k , 24fps, video only, 50.47MiB
135          mp4        854x358    DASH video 1104k , 24fps, video only, 141.09MiB
244          webm       854x358    DASH video 1283k , 24fps, video only, 83.23MiB
136          mp4        1280x536   DASH video 2207k , 24fps, video only, 272.73MiB
247          webm       1280x536   DASH video 2571k , 24fps, video only, 156.48MiB
137          mp4        1920x804   DASH video 4137k , 24fps, video only, 514.61MiB
248          webm       1920x804   DASH video 4404k , 24fps, video only, 276.51MiB
264          mp4        2560x1072  DASH video 9923k , 24fps, video only, 1.30GiB
271          webm       2560x1072  DASH video 10186k , 24fps, video only, 695.41MiB
266          mp4        3840x1608  DASH video 18571k , h264, 24fps, video only, 2.91GiB
313          webm       3840x1608  DASH video 23362k , VP9, 24fps, video only, 2.10GiB
17           3gp        176x144
36           3gp        320x240
5            flv        400x240
43           webm       640x360
18           mp4        640x360
22           mp4        1280x720   (best)

By default, it downloads f313 and f141, which were unable to be merged.

Then I tried to download only the .mp4 file in f137, but that generated an unusable file. It did take up 514.61 MiB on my drive, but when I tried to play it, it only opened QuickTime/VLC and displayed a 0 second video / nothing.

I then tried to download only the .mp4 file in f22 (marked 'best'), and that worked great. 
However, that is "only" 1280x720. Why does no other formats here work?
Or should I type in the command in a specific way if I want to download, say, the 1080p version?

Thank you so much for an excellent job and the quick responding! You are awesome! :-D

**Comment by jaimeMF** [comment]
Post the [output you get with the --verbose option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs)

In my case VLC plays the sound, but not the video:
![vlc](https://cloud.githubusercontent.com/assets/1239727/7481316/6a6e6a32-f36f-11e4-8586-c34237d30390.png)
mpv plays it fine. 

> Or should I type in the command in a specific way if I want to download, say, the 1080p version?

Use `-f 'bestvideo[height<=1080]+bestaudio'` or `-f 'bestvideo[height<=1080][ext=mp4]+bestaudio'` to force it to use the mp4 file

**Comment by jaimeMF** [comment]
I have updated to VLC 2.2.1 and it works fine, so I'm closing the issue.
