### ISSUE TITLE
[vessel] Two videos not working

### ISSUE THREAD

**Issue by elevul** [rg3/youtube-dl#5623]
![twovideos](https://cloud.githubusercontent.com/assets/6944931/7480865/040e1fa6-f36c-11e4-8583-adf16f553288.JPG)
Urls:
https://www.vessel.com/videos/TlIBgDRuM
https://www.vessel.com/videos/TNH16VM3d

All the other videos of the same user (linustech) work fine.

**Comment by naglis** [comment]
This issue should be fixed in the next release of youtube-dl. Thanks for the report.
