### ISSUE TITLE
Soundcloud - Automatically put image to the sound file?

### ISSUE THREAD

**Issue by NickWinston123** [rg3/youtube-dl#5625]
Is it possible to have the mp3 already have the cover for the song instead of having it just in the same folder as the mp3?

**Comment by yan12125** [comment]
```--write-thumbnail``` or ```--write-thumbnails``` writes image files to the disk, and ```--embed-thumbnail``` writes images to the mp3 file.

**Comment by jaimeMF** [comment]
I'm closing the issue, `--embed-thumbnail` works for me.
