### ISSUE TITLE
WorldStarHipHop URL not updated - not working for mobile URLs

### ISSUE THREAD

**Issue by zeph00** [rg3/youtube-dl#5629]
Since a while WorldStarHipHop (WSHH for later reference) has changed its URLs and thus (on mobile) the links are not recognized by YoutubeDL.

To elaborate, here's the current __VALID_URL the current WSHH has:
"_VALID_URL = r'https?://(?:www|m)\.worldstar(?:candy|hiphop)\.com/videos/video\.php\?v=(?P<id>.*)'"

**However**, on mobile (Android) the URL is:
http://m.worldstarhiphop.com/android/video.php?v=UNIQUEVIDEOREFHERE

As you can see, the URL, instead of '/videos/' or '/video/', has '/android/' (and I believe it's '/ios/' on iOS, can anyone verify?).

I believe, to correct this, the appropriate __VALID_URL would be:
"_VALID_URL = r'https?://(?:www|m)\.worldstar(?:candy|hiphop)\.com/(**?:videos|android|ios**)/video\.php\?v=(?P<id>.*)'"

*Then again, I'm absolutely not a coder and this might be wrong, but you get the idea.*

**Comment by yan12125** [comment]
Thanks for the report. Android URLs will be supported in the next version. However, there's no actual iOS URLs, so I can't test it. If you find an iOS URL, feel free to open a new issue.
