### ISSUE TITLE
MLB extractor issue...

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5630]
This might be a strange one...not sure where they found this URL but it is on mlb.com:

URL:
http://m.mlb.com/cutfour/2015/05/06/122644284/zack-greinke-busts-out-the-rarely-seen-pitcher-bat-flip--on-a-double?adbid=941666415864998&adbpl=fb&adbpr=196554717042842&partnerId=as_mlb_20150506_45270226&short_code=2xq9z

Output:
C:\>youtube-dl -v "http://m.mlb.com/cutfour/2015/05/06/122644284/zack-greinke-bu
sts-out-the-rarely-seen-pitcher-bat-flip--on-a-double?adbid=595823018431127552&a
dbpl=tw&adbpr=241544156&partnerId=as_mlb_20150506_45270196&short_code=2xq9v"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://m.mlb.com/cutfour/2015/05/06/1226442
84/zack-greinke-busts-out-the-rarely-seen-pitcher-bat-flip--on-a-double?adbid=59
5823018431127552&adbpl=tw&adbpr=241544156&partnerId=as_mlb_20150506_45270196&sho
rt_code=2xq9v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.04
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[generic] zack-greinke-busts-out-the-rarely-seen-pitcher-bat-flip--on-a-double?a
dbid=595823018431127552&adbpl=tw&adbpr=241544156&partnerId=as_mlb_20150506_45270
196&short_code=2xq9v: Requesting header
WARNING: Falling back on generic information extractor.
[generic] zack-greinke-busts-out-the-rarely-seen-pitcher-bat-flip--on-a-double?a
dbid=595823018431127552&adbpl=tw&adbpr=241544156&partnerId=as_mlb_20150506_45270
196&short_code=2xq9v: Downloading webpage
[generic] zack-greinke-busts-out-the-rarely-seen-pitcher-bat-flip--on-a-double?a
dbid=595823018431127552&adbpl=tw&adbpr=241544156&partnerId=as_mlb_20150506_45270
196&short_code=2xq9v: Extracting information
ERROR: Unsupported URL: http://m.mlb.com/cutfour/2015/05/06/122644284/zack-grein
ke-busts-out-the-rarely-seen-pitcher-bat-flip--on-a-double?adbid=595823018431127
552&adbpl=tw&adbpr=241544156&partnerId=as_mlb_20150506_45270196&short_code=2xq9v

Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 938, in _real_extract
  File "youtube_dl\utils.pyo", line 1557, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 25, column 178
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 650, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\generic.pyo", line 1463, in _real_extract
UnsupportedError: Unsupported URL: http://m.mlb.com/cutfour/2015/05/06/122644284
/zack-greinke-busts-out-the-rarely-seen-pitcher-bat-flip--on-a-double?adbid=5958
23018431127552&adbpl=tw&adbpr=241544156&partnerId=as_mlb_20150506_45270196&short
_code=2xq9v

Thanks again...
Ringo

**Comment by dstftw** [comment]
Can't find any video only couple of gifs.

**Comment by RingoTheDog** [comment]
![mlb](https://cloud.githubusercontent.com/assets/4542921/7498692/b60ac2de-f3d7-11e4-83f2-e7220da7d507.png)

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.

**Comment by RingoTheDog** [comment]
WOW...amazing as always.
Thanks again!
