### ISSUE TITLE
command to quit youtube-dl?

### ISSUE THREAD

**Issue by Steveland** [rg3/youtube-dl#5631]
Hello,

Is there any command to quit the program while it's running (like 'q' letter for ffmpeg)?

I ask this because I'm working on a Windows program that uses youtube-dl as a child process, and it would be a convenient way to quit the program properly instead of making a TerminateProcess.

**Comment by dstftw** [comment]
[Send CTRL+C signal](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683155%28v=vs.85%29.aspx).

**Comment by Steveland** [comment]
Thanks dstftw for the answer but I was already aware of the GenerateConsoleCtrlEvent function.

This function seems to be working for console programs only and I need a solution for a Win32 GUI program. I don't like the TerminateProcess function but I think it's my best option here.
