### ISSUE TITLE
Is there an --prefer-unfree-formats flag?

### ISSUE THREAD

**Issue by pps** [rg3/youtube-dl#5632]
I'm on a Mac, using bestvideo in my youtube-dl config file as part of my quality cascade definition. Problem is, this option sometimes chooses a webm format when there would be a mp4 version of the same quality, and I'd love to have an mp4 file in the end.

Now there is this option --prefer-free-formats to prefer webm formats. Is there also (undocumented) option to go the other way and prefer mp4 formats?

Thanks!

**Comment by LollenJumplan** [comment]
why not just use -f mp4 ?

**Comment by jaimeMF** [comment]
`-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'` will try to download the mp4 files if available and fallback to other formats otherwise (for example if the site only provides flv files).

**Comment by pps** [comment]
I wasn't aware of that feature, and I've read README.md. Great to know, many thanks.
