### ISSUE TITLE
%(playlist_index)s incorrect 

### ISSUE THREAD

**Issue by revolter** [rg3/youtube-dl#5634]
For this link `https://www.youtube.com/watch?v=JrO4Dus0iH8&index=33&list=PLX0bNioa_mri0TyapiPdecQUaxXjb6VnR`, shouldn't the output file contain `33`? Instead, having `%(playlist_index)s` in the output template saves the video with a filename containing `001`.

**Comment by yan12125** [comment]
How did you invoke youtube-dl? Please post the [full verbose log](https://github.com/rg3/youtube-dl#bugs).

**Comment by revolter** [comment]
Sorry, I think I figured it out. I didn't pass an `--playlist-start` argument so it was downloading by default de entire playlist. Correct me if I'm wrong.

**Comment by yan12125** [comment]
You're right. In general youtube-dl does not use the ```index``` parameter. Now I'm closing this issue. If you encounter any other problem, feel free to open a new issue.
