### ISSUE TITLE
Add a flag to not download the video and audio in separate

### ISSUE THREAD

**Issue by masterkorp** [rg3/youtube-dl#5637]
Hello everyone,

I recently upgraded to ``2015.04.26``, and noticed that now the video and the audio are downloaded in separate from each other. 
- What is the advantage on this ?
- Now I can't watch a video while its downloading, I do this on long videos, is there a flag that I can pass to download them simultaneously ?

Regards,

**Comment by dstftw** [comment]
Read two last paragraphs of [format selection section](https://github.com/rg3/youtube-dl#format-selection).

**Comment by masterkorp** [comment]
@dstftw Thank you.
