### ISSUE TITLE
under debian jessie 8 blug playlist

### ISSUE THREAD

**Issue by titux-be** [rg3/youtube-dl#5639]
stefan@asus-stefan:~/Musique$ youtube-dl -x --audio-format mp3 --verbose https://www.youtube.com/watch?list=RDwd5zVMBVCII
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-x', '--audio-format', 'mp3', '--verbose', 'https://www.youtube.com/watch?list=RDwd5zVMBVCII']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] Proxy map: {}
[youtube:playlist] RDwd5zVMBVCII: Downloading Youtube mix
[download] Downloading playlist: Mix - The Hacker - Fadin Away
[youtube:playlist] playlist Mix - The Hacker - Fadin Away: Collected 26 video ids (downloading 26 of them)
[download] Downloading video #1 of 26
[youtube] Setting language
[youtube] wd5zVMBVCII: Downloading webpage
[youtube] wd5zVMBVCII: Downloading video info webpage
[youtube] wd5zVMBVCII: Extracting video information
[debug] Invoking downloader on u'https://r1---sn-cxab5jvh-cg0k.googlevideo.com/videoplayback?key=yt5&dur=335.017&ipbits=0&initcwndbps=1582500&mime=audio%2Fmp4&lmt=1399950634675691&expire=1431030678&upn=qZixhDQiyt8&pl=23&id=o-AHbbMc4lxcTjteIz70QNxgWrPECwu9D6KymYUtHpseod&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&gir=yes&mm=31&signature=BC80DD1A1029DAD2C2E1CC8469936B52D0599A1D.856277E4973F4E22D802D3548D29077F9957E47D&sver=3&pcm2cms=yes&source=youtube&clen=5379683&ms=au&mt=1431009020&fexp=907263%2C934960%2C938028%2C9405970%2C9408140%2C9408142%2C9408212%2C9408581%2C9408706%2C9412508%2C9412948%2C9413021%2C9413350%2C946008%2C948124%2C952612%2C952637%2C952642&mv=m&ip=109.131.24.240&requiressl=yes&itag=140&ratebypass=yes'
[download] Destination: The Hacker - Fadin Away-wd5zVMBVCII.m4a
[download] 100% of 5.13MiB in 00:02
[avconv] Destination: The Hacker - Fadin Away-wd5zVMBVCII.mp3
[debug] ffmpeg command line: avconv -y -i 'The Hacker - Fadin Away-wd5zVMBVCII.m4a' -vn -acodec libmp3lame -q:a 5 'The Hacker - Fadin Away-wd5zVMBVCII.mp3'
Deleting original file The Hacker - Fadin Away-wd5zVMBVCII.m4a (pass -k to keep)
[download] Downloading video #2 of 26
[youtube] 2Z0ZL52ZjJ0: Downloading webpage
[youtube] 2Z0ZL52ZjJ0: Downloading video info webpage
[youtube] 2Z0ZL52ZjJ0: Extracting video information
[debug] Invoking downloader on u'https://r4---sn-cxab5jvh-cg0s.googlevideo.com/videoplayback?dur=450.234&lmt=1386736667792653&mm=31&fexp=907263%2C934960%2C938028%2C9405970%2C9408140%2C9408142%2C9408212%2C9408581%2C9408706%2C9412508%2C9412948%2C9413021%2C9413350%2C946008%2C948124%2C952612%2C952637%2C952642&expire=1431030687&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=audio%2Fmp4&key=yt5&requiressl=yes&sver=3&itag=140&pl=23&pcm2cms=yes&ipbits=0&upn=m8O23AP0WHI&initcwndbps=1582500&id=o-ALvNIkPDJ7WykPzpm8959tLR--T8jmOseru__xrkheG0&source=youtube&gir=yes&clen=7151364&ms=au&mt=1431009020&mv=m&ip=109.131.24.240&signature=D6E8C89842EC2F050D3805D64FA6DF834A1BB640.F7F7FE87A1655E38CE2D277D0897C4ABDCC26085&ratebypass=yes'
[download] Destination: The Hacker - Flesh And Bone-2Z0ZL52ZjJ0.m4a
[download] 100% of 6.82MiB in 00:03
[avconv] Destination: The Hacker - Flesh And Bone-2Z0ZL52ZjJ0.mp3
[debug] ffmpeg command line: avconv -y -i 'The Hacker - Flesh And Bone-2Z0ZL52ZjJ0.m4a' -vn -acodec libmp3lame -q:a 5 'The Hacker - Flesh And Bone-2Z0ZL52ZjJ0.mp3'
Deleting original file The Hacker - Flesh And Bone-2Z0ZL52ZjJ0.m4a (pass -k to keep)
[download] Downloading video #3 of 26
[youtube] XGOaXphpT7w: Downloading webpage
[youtube] XGOaXphpT7w: Downloading video info webpage
[youtube] XGOaXphpT7w: Extracting video information
[youtube] XGOaXphpT7w: Encrypted signatures detected.
[youtube] {43} signature length 40.41, html5 player en_US-vflJuImhV
[youtube] XGOaXphpT7w: Downloading js player vflJuImhV
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 860, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 489, in _decrypt_signature
    u'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

stefan@asus-stefan:~/Musique$

**Comment by jaimeMF** [comment]
You are using an outdated version, [read our FAQ](https://yt-dl.org/update) for the update instructions.
