### ISSUE TITLE
Fails to download facebook video: "urlopen error no host given"

### ISSUE THREAD

**Issue by MartinDelille** [rg3/youtube-dl#5640]
I know youtube-dl is designed primary to download youtube video, but I already managed to do it. When trying to download [this funny one](https://www.facebook.com/UnNuevoDia/videos/vb.35345841128/10152345392356129/?type=2&theater), I had the following error:

    UnNuevoDia/videos/vb.35345841128/10152345392356129/\?type\=2\&theater
    [generic] ?type=2&theater: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] ?type=2&theater: Downloading webpage
    [generic] ?type=2&theater: Extracting information
    [redirect] Following redirect to /UnNuevoDia/videos/vb.35345841128/10152345392356129/?type=2&amp;theater&amp;_fb_noscript=1
    WARNING: The url doesn't specify the protocol, trying with http
    [generic] ?type=2&amp;theater&amp;_fb_noscript=1: Requesting header
    WARNING: Could not send HEAD request to http:///UnNuevoDia/videos/vb.35345841128/10152345392356129/?type=2&amp;theater&amp;_fb_noscript=1: <urlopen error no host given>
    [generic] ?type=2&amp;theater&amp;_fb_noscript=1: Downloading webpage
    ERROR: Unable to download webpage: <urlopen error no host given> (caused by URLError('no host given',))

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by dstftw** [comment]
Most likely you are using an outdated version of youtube-dl, since it works perfectly for me with the latest version. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by MartinDelille** [comment]
It works! Sorry for the inconveniance, I'll be more carefull next time ;-)
