### ISSUE TITLE
-g for youtube gives 2 the same URLs now, why ?

### ISSUE THREAD

**Issue by benoon** [rg3/youtube-dl#5643]
-g parameter was always giving direct stream URL 
it works like that for all sites excluding youtube 
13.04 is the last version which gives one URL for youtube
current version and previous one give duplicated
is that on purpose ?

**Comment by benoon** [comment]
python26
didnt test on higher python version

**Comment by jaimeMF** [comment]
You'll have to use `-f best`, see the last two paragraphs [in the formats section](https://github.com/rg3/youtube-dl/blob/40b96352c99953aec9272574729077c06c235747/README.md#format-selection) for more info.

**Comment by benoon** [comment]
ok , thx , works
just a question - why -g gives 2 urls now ?
any special reason ?

**Comment by jaimeMF** [comment]
It now defaults to `bestvideo+bestaudio`(which gives a better quality), so it prints the url of the two formats.
