### ISSUE TITLE
ytuser:[channel name] gives 404 error

### ISSUE THREAD

**Issue by electroweak** [rg3/youtube-dl#5646]
was working fine till today.
I upgraded to youtube-dl-2015.05.04, but this has not helped.

Note that the page in question *does* exist
https://www.youtube.com/channel/UCXV7LWJ5ckEYemnyd2Z9OBA

I suspect this is due to youtube changing something...?

example output:
./youtube-dl/youtube-dl  ytuser:UCXV7LWJ5ckEYemnyd2Z9OBA --verbose 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'ytuser:UCXV7LWJ5ckEYemnyd2Z9OBA', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.04
[debug] Python version 2.7.8 - Darwin-10.8.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.4.2, ffprobe 2.4.2
[debug] Proxy map: {}
[youtube:user] UCXV7LWJ5ckEYemnyd2Z9OBA: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 1708, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by electroweak** [comment]
Note: i subsequently found that youtube-dl works ok when the channel / user has a 'short name' like:

https://www.youtube.com/user/adb024/videos

then the command 
./youtube-dl/youtube-dl  ytuser:adb024 --verbose
works ok.

but some of the channels/users I look at do not have a short name..(see my first post for an example)

**Comment by jaimeMF** [comment]
`ytuser:` is a shortcut for `https://www.youtube.com/user/*` pages, it doesn't works for channels.

> was working fine till today.
> I upgraded to youtube-dl-2015.05.04, but this has not helped.

Which version were you using? Can you post the command and the output with the `--verbose` option?

**Comment by electroweak** [comment]
Hi JamieMF,

it was working for about a year, until Youtube changed something, I think! 
I was using youtube-dl-2014.11.21 

I started getting a video from youtube entitled "devicesupport" and a little after that, it stopped downloading.

So I guess it would be useless to post a failed attempt by my old version (youtube-dl-2014.11.21 ), but if it's useful i will do it. Let me know.

Moving on to the youtube-dl-2015.05.04 version, I have found most of my 'subscriptions' work ok using youtube-dl-2015.05.04 with ytuser:username  (thanks!), BUT What I now see is that some 'users' don't have a valid 'username'  eg.
https://www.youtube.com/channel/UCCFfrwdzobhbdYaMBAZ8zTA
None of the links to 'videos' give a user/xyzabc link.

So, for these channels, I cannot find a user to insert in the ytuser:XXXXXX line.
Any ideas?? 

PS I LOVE youtube-dl !!!!!!  thanks so much to all developers and noob-question-answerers..
Youtube-dl is my answer to not having a youtube subscription / google account!!!
(I use a cron job to pull new videos, and get my news, musc, general interest using it...)

**Comment by jaimeMF** [comment]
It worked because the YouTube api supported it, but since it stopped working we parse now the webpages and that wouldn't work.
You should use the full url instead (I would recommend to always use it, even for users), it's more reliable and  I guess you usually discover new channels through the YouTube site, so it should be really simple.
Since using the full url works, I'm closing the issue. Thanks for reporting it.
