### ISSUE TITLE
How to pause youtube-dl?

### ISSUE THREAD

**Issue by truth1ness** [rg3/youtube-dl#5653]
I was trying to pause youtube-dl for something but I couldn't do it. I tried ctrl+c, ctrl+d, escape, q, etc.

**Comment by dstftw** [comment]
There is no such functionality. You can stop youtube-dl with `Ctrl+C`, re-run and it will continue from where it has been stopped if possible.

**Comment by jaimeMF** [comment]
Note that, at least on Unix, you can press `Ctrl+Z` and then resume it with `fg %youtube-dl`. Although I haven't tested how much time can you pause it.
