### ISSUE TITLE
sohu broke --cn-verification-proxy support

### ISSUE THREAD

**Issue by cowbert** [rg3/youtube-dl#5655]
This just started happening this week. Sohu is returning 503 when used with --cn-verification-proxy even though playback is still supported with the unblock-youku browser plugin. (soimort/you-get is also failing).

    c:\Python34\Scripts\youtube-dl.exe --verbose --cn-verification-proxy proxy.uku.im:8888 http://tv.sohu.com/20150408/n410951635.shtml
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['--verbose', '--cn-verification-proxy', 'proxy.uku.im:8888', 'http://tv.sohu.com/20150408/n410951635.shtml']
    [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
    [debug] youtube-dl version 2015.05.04
    [debug] Python version 3.4.3 - Windows-8-6.2.9200
    [debug] exe versions: none
    [debug] Proxy map: {}
    [Sohu] 410951635: Downloading webpage
    [Sohu] 410951635: Downloading JSON data for 2319043
    ERROR: Unable to download JSON metadata: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
      File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 312, in _request_webpage
        return self._downloader.urlopen(url_or_request)
      File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1708, in urlopen
        return self._opener.open(req, timeout=self._socket_timeout)
      File "C:\Python34\lib\urllib\request.py", line 469, in open
        response = meth(req, response)
      File "C:\Python34\lib\urllib\request.py", line 579, in http_response
        'http', request, response, code, msg, hdrs)
      File "C:\Python34\lib\urllib\request.py", line 507, in error
        return self._call_chain(*args)
      File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
        result = func(*args)
      File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by yan12125** [comment]
Seems ```proxy.uku.im:8888``` is partially broken. I've reported it to zhuzhuor/Unblock-Youku#427. Try another verification proxy, or we'll have to implement DNS lookup functionality in youtube-dl.

**Comment by yan12125** [comment]
By the waqy, sohu extractor is originally broken, at least in Taiwan and on Travis-CI servers. I've updated it in 32060c6d6b618fa858b2ce43db34d02fd43bc542 and now it works for both places. It would be great if someone can confirm the updated version also works in Mainland Cihna.

**Comment by yan12125** [comment]
FWIW, [another proxy provided by unblock youku project](https://github.com/zhuzhuor/Unblock-Youku/blob/master/chrome/proxy.js#L49) works for me. I'm closing this issue because the usuability of individual proxies is beyond the scope of youtube-dl.
