### ISSUE TITLE
MKV - Could not write header for output - error

### ISSUE THREAD

**Issue by AdamDanischewski** [rg3/youtube-dl#5659]
I am trying to download the following YouTube video: 
 https://www.youtube.com/watch?v=9ZVMViSx6Ek

$ youtube-dl --version
2015.05.04

It is stored in a mkv container yet it won't convert, here is the result: 
youtube-dl "https://www.youtube.com/watch?v=9ZVMViSx6Ek" --merge-output-format mkv
[youtube] 9ZVMViSx6Ek: Downloading webpage
[youtube] 9ZVMViSx6Ek: Extracting video information
[youtube] 9ZVMViSx6Ek: Downloading DASH manifest
[download] Destination: Hiatus Kaiyote - Breathing Underwater-9ZVMViSx6Ek.f248.webm
[download] 100% of 13.91MiB in 00:11
[download] Destination: Hiatus Kaiyote - Breathing Underwater-9ZVMViSx6Ek.f141.m4a
[download] 100% of 10.53MiB in 00:08
[ffmpeg] Merging formats into "Hiatus Kaiyote - Breathing Underwater-9ZVMViSx6Ek.mkv"
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Operation not permitted

I have the latest stable mkvtoolnix (for mkv conversion, other packages required?):
  Installed: 6.7.0-1
  Candidate: 6.7.0-1

I have the latest stable libav-tools (package containing avconv):
  Installed: 6:9.18-0ubuntu0.14.04.1
  Candidate: 6:9.18-0ubuntu0.14.04.1

**Comment by dstftw** [comment]
libav in ubuntu repos is outdated, you have to update it at least to 10 as stated in warning (latest ffmpeg will work as well). Alternatively, you can use `-f best` if you are ok with non overall best quality.

**Comment by AdamDanischewski** [comment]
Thanks that worked!!  

(Guess, that *was* a good warning message! =)  

youtube-dl -f best "https://www.youtube.com/watch?v=9ZVMViSx6Ek" --merge-output-format mkv
[youtube] 9ZVMViSx6Ek: Downloading webpage
[youtube] 9ZVMViSx6Ek: Extracting video information
[youtube] 9ZVMViSx6Ek: Downloading DASH manifest
[download] Destination: Hiatus Kaiyote - Breathing Underwater-9ZVMViSx6Ek.mp4
[download] 100% of 30.08MiB in 00:23

$ ls
Hiatus Kaiyote - Breathing Underwater-9ZVMViSx6Ek.mp4

**Comment by aimkeepachieve** [comment]
I use Allavsoft to download YouTube videos.

It can directly download YouTube to MKV, MP4, MOV, AVI, WMV, etc

Here is the step by step guide at http://www.allavsoft.com/how-to/youtube-to-mkv-convert-download.html
