### ISSUE TITLE
Cant attach images to songs

### ISSUE THREAD

**Issue by NickWinston123** [rg3/youtube-dl#5662]
When using --embed-thumbnail I get this error when the image is in the same file as the mp3 and named "Glue-187193381.mp3.jpg".
Is this an error with ffmeg or what?
[soundcloud:user] playlist DailyBreed: Collected 18 video ids (downloading 18 of them)
[download] Downloading video 1 of 18
[download] Destination: Glue-187193381.mp3
[download] 100% of 1.54MiB in 00:00
[ffmpeg] Adding thumbnail to "Glue-187193381.mp3"
ERROR:   Reason: image not found
nicks-mac-mini:dailybreed nick$

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by NickWinston123** [comment]
Sorry dude didn't expect you to be that fast, heres what I got and thanks in advanced.

nicks-mac-mini:dailybreed nick$ youtube-dl https://soundcloud.com/dailybreed --embed-thumbnail --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://soundcloud.com/dailybreed', u'--embed-thumbnail', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.28
[debug] Python version 2.7.9 - Darwin-13.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg present, ffprobe present
[debug] Proxy map: {}

[soundcloud:user] playlist DailyBreed: Collected 18 video ids (downloading 18 of them)
[download] Downloading video 1 of 18
[debug] Invoking downloader on u'https://ec-media.sndcdn.com/likVlNiQCyOZ.128.mp3?f10880d39085a94a0418a7ef69b03d522cd6dfee9399eeb9a522029d6dfabd3435da9a4ec35d7f09e36f12218d8d754cbae7385afd30a812062d0a4dd50207a1edc2573921'
[download] Glue-187193381.mp3 has already been downloaded
[download] 100% of 1.54MiB
[ffmpeg] Adding thumbnail to "Glue-187193381.mp3"
[debug] ffmpeg command line: ffmpeg -y -i Glue-187193381.mp3 -i Glue-187193381.mp3.jpg -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' Glue-187193381.temp.mp3
ERROR:   Reason: image not found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1512, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/embedthumbnail.py", line 45, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 152, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 148, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

**Comment by dstftw** [comment]
Try updating to the latest version.

**Comment by NickWinston123** [comment]
Updated and got what looked to the the same error so I restarted terminal and tried again to re-update the session but still got this same error: 

[download] Downloading video 1 of 18
[debug] Invoking downloader on u'https://ec-media.sndcdn.com/likVlNiQCyOZ.128.mp3?f10880d39085a94a0418a7ef69b03d522cd6dfee9399eeb9a522029d6dfab83d7d0030515862090539e4c53865c0919f3a9d00689eba48a2005487d4354741f7792b2a7ce4'
[download] Destination: Glue-187193381.mp3
[download] 100% of 1.54MiB in 00:00
[ffmpeg] Adding thumbnail to "Glue-187193381.mp3"
[debug] ffmpeg command line: ffmpeg -y -i Glue-187193381.mp3 -i Glue-187193381.mp3.jpg -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' Glue-187193381.temp.mp3
ERROR:   Reason: image not found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1529, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/embedthumbnail.py", line 45, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 152, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 148, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

**Comment by dstftw** [comment]
Run with --verbose to ensure the version.

**Comment by NickWinston123** [comment]
Looks like an error with the way home-brew installed ffmpeg wrong but I will run that now
nicks-mac-mini:~ noah$ ffmpeg 
dyld: Library not loaded: /usr/local/lib/libx264.144.dylib
  Referenced from: /usr/local/bin/ffmpeg
  Reason: image not found
Trace/BPT trap: 5


[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://soundcloud.com/dailybreed', u'--embed-thumbnail', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.9 - Darwin-13.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg present, ffprobe present
[debug] Proxy map: {}

**Comment by dstftw** [comment]
So, not a youtube-dl issue. Closing.

**Comment by NickWinston123** [comment]
Thanks
