### ISSUE TITLE
Error when video id looks like option

### ISSUE THREAD

**Issue by Lunik** [rg3/youtube-dl#5666]
Like for this one
---kb_0BgGA

$ youtube-dl --simulate ---kb_0BgGA
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: ---kb_0BgGA

$ youtube-dl --simulate "---kb_0BgGA"
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: ---kb_0BgGA

$ youtube-dl --simulate '---kb_0BgGA'
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: ---kb_0BgGA

**Comment by dstftw** [comment]
[Read](https://github.com/rg3/youtube-dl#how-do-i-download-a-video-starting-with-a---).
