### ISSUE TITLE
Donloading of odnoklassniki videos results into an error

### ISSUE THREAD

**Issue by barseghyanartur** [rg3/youtube-dl#5671]
Donloading of Odnoklassniki videos fail (for latest https://pypi.python.org/pypi/youtube_dl/2015.05.10).

- https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/odnoklassniki.py

For the URL mentioned in test it doesn't work as well.

- https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/odnoklassniki.py#L15

---

$ youtube-dl http://ok.ru/video/20079905452 --verbose

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://ok.ru/video/20079905452', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.3 - Linux-3.13.0-52-generic-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.8.17-4, avprobe 0.8.17-4, ffmpeg 0.8.17-4, ffprobe 0.8.17-4
[debug] Proxy map: {}
[Odnoklassniki] 20079905452: Downloading webpage
ERROR: Unable to extract player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/odnoklassniki.py", line 40, in _real_extract
    r"OKVideo\.start\(({.+?})\s*,\s*'VideoAutoplay_player'", webpage, 'player'),
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for teh report.

**Comment by barseghyanartur** [comment]
@dstftw:

Thanks a lot. Just tested. The source install works great.
