### ISSUE TITLE
Dumpert does not work anymore

### ISSUE THREAD

**Issue by WuvorWenda** [rg3/youtube-dl#5672]
http://www.dumpert.nl/mediabase/6654326/ed60a10f/betrapt_makker_.html --verbose
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'http://www.dumpert.nl/mediabase/6654326/ed60a10f/betrapt_makker_.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.5 - Linux-3.10.0-123.8.1.el7.x86_64-x86_64-with-centos-7.0.1406-Core
[debug] exe versions: ffmpeg N-44632-g721c916-
[debug] Proxy map: {}
[Dumpert] 6654326/ed60a10f: Downloading webpage
ERROR: Unable to extract data files; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/dumpert.py", line 33, in _real_extract
    r'data-files="([^"]+)"', webpage, 'data files')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract data files; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by rrooij** [comment]
It looks like it's been caused by the new cookie screen.
