### ISSUE TITLE
How to use audio-quality and output?

### ISSUE THREAD

**Issue by mishop** [rg3/youtube-dl#5673]
Dear,
Wen i use --audio-quality option and --otuput, always file is in same quality.
Exapmle:
youtube-dl --extract-audio --audio-format mp3 --audio-quality 5 --prefer-ffmpeg --output 123.mp3 "https://www.youtube.com/watch?v=ic8ZJbozYFY"

The file 123.mp3 is corrupted and same players can't play this. When remove --otput download file are ok, but I need output option to import file in aplication.

**Comment by jaimeMF** [comment]
Use `--output '123.%(ext)s'` instead, otherwise you are telling youtube-dl to save the original file as `123.mp3` and it will think it's already an mp3 file.

If you have any problem, [post the output with the --verbose option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by mishop** [comment]
Working.
Thank you.
