### ISSUE TITLE
Windows Version can't specify destination folder

### ISSUE THREAD

**Issue by AlfredMao** [rg3/youtube-dl#5678]
youtube-dl.exe   -o "D:\youtube\music\"    https://www.youtube.com/playlist?list=PLFgquLnL59alZ5m7XEk44TI-FTrfNwL2B

d:\youtube>youtube-dl.exe   -o "D:\youtube\music\"    https://www.youtube.com/pl
aylist?list=PLFgquLnL59alZ5m7XEk44TI-FTrfNwL2B
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

**Comment by redyready** [comment]
youtube-dl.exe --ignore-errors -o "D:\youtube\music\%(title)s.%(ext)s" https://www.youtube.com/playlist?list=PLFgquLnL59alZ5m7XEk44TI-FTrfNwL2B

You forgot to add "%(title)s.%(ext)s" to -o also add --ignore-errors to get around "The uploader has not made this video available in your country."

The issue might be you are pasting the whole thing and the url is on another line.

![proof](http://i.imgur.com/gVO7VdO.png)

**Comment by AlfredMao** [comment]
Thanks redyready! with the parameters, the cmd works.

**Comment by yan12125** [comment]
Thanks @redyready! Now I'm closing this issue. If you encounter another problem, feel free to open a new issue.
