### ISSUE TITLE
Trouble with download channel, not user from YT

### ISSUE THREAD

**Issue by peseriusz** [rg3/youtube-dl#5679]
When I download user movie from YT, eg. 
youtube-dl -ciw --playlist-end 10  -f "best[height<=?640]" -o '%(title)s - %(uploader)s.%(ext)s' --dateafter 20140305 ytuser:TopClassicalMusic

it's OK. 

But when ytuser is "channel", then I get error. In past YT-dl worked properly in this way.
Channel is like: 
https://www.youtube.com/channel/UC3gJTHF49dtxuUpMg4D7hng

User is like: 
https://www.youtube.com/user/NewTrailersBuzz

**Comment by yan12125** [comment]
What kind of error did you get? Post the [full verbose log](https://github.com/rg3/youtube-dl#bugs) helps us find out the problem more quickly and precisely.

**Comment by peseriusz** [comment]
For this example:

youtube-dl -ciw --playlist-end 10 -f "best[height<=?640]" -o '%(title)s - %(uploader)s.%(ext)s' --dateafter 20150512 ytuser:UC3gJTHF49dtxuUpMg4D7hng --verbose

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-ciw', u'--playlist-end', u'10', u'-f', u'best[height<=?640]', u'-o', u'%(title)s - %(uploader)s.%(ext)s', u'--dateafter', u'20140305', u'ytuser:UC3gJTHF49dtxuUpMg4D7hng', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.6 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.2.2, ffprobe 2.2.2
[debug] Proxy map: {}
[youtube:user] UC3gJTHF49dtxuUpMg4D7hng: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1710, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by yan12125** [comment]
Keyword "ytuser" does not support channels. Use full URLs instead. For example: 
```
youtube-dl -ciw --playlist-end 10 -f "best[height<=?640]" -o '%(title)s - %(uploader)s.%(ext)s' --dateafter 20150512 https://www.youtube.com/channel/UC3gJTHF49dtxuUpMg4D7hng --verbose
```

**Comment by peseriusz** [comment]
Thanks for quick help. 
"Keyword "ytuser" does not support channels". In past, this worked properly, maybe something changed...
