### ISSUE TITLE
Can't download gdcvault requiring a log in 

### ISSUE THREAD

**Issue by dantreble** [rg3/youtube-dl#5687]
dan@parker:~$ youtube-dl --verbose --username xxx --password xxx http://www.gdcvault.com/play/1021935/Do-Artists-Dream-of-Electric
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'http://www.gdcvault.com/play/1021935/Do-Artists-Dream-of-Electric']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.6 - Linux-3.11.0-22-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[GDCVault] Do-Artists-Dream-of-Electric: Downloading webpage
[GDCVault] Do-Artists-Dream-of-Electric: Logging in
ERROR: Unable to download webpage: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1710, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Hope that is enough info.

Thanks!

**Comment by yan12125** [comment]
Seems this is a temporary issue. It works fine now:
```
$ youtube-dl -v "http://www.gdcvault.com/play/1021935/Do-Artists-Dream-of-Electric" 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.gdcvault.com/play/1021935/Do-Artists-Dream-of-Electric']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Git HEAD: a4d6cf970
[debug] Python version 3.6.1 - Linux-4.10.11-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3
[debug] Proxy map: {}
[GDCVault] Do-Artists-Dream-of-Electric: Downloading webpage
[DigitallySpeaking] 834098_EYIX: Downloading XML
[debug] Invoking downloader on 'http://s3-2u.digitallyspeaking.com/assets/ubm/gdc/sf15/834098_EYIX-v4c52f-1300.mp4'
[download] Destination: Do Artists Dream of Electric Sheep-1021935.mp4
[download]  11.6% of 558.96MiB at  1.80MiB/s ETA 04:34^CException ignored in: <_io.FileIO name='Do Artists Dream of Electric Sheep-1021935.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='Do Artists Dream of Electric Sheep-1021935.mp4.part'>

ERROR: Interrupted by user
```
