### ISSUE TITLE
Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url;

### ISSUE THREAD

**Issue by pythonteste** [rg3/youtube-dl#5689]
Just trying to DL some videos from youtube real quick and I get this error that suggested going here. Anyone got any input on figuring out whats going on? Please post it. 
      
Background Info; 

Just Installed youtube-dl via pip this was my first command to test out the program. 

Output of;  "youtube-dl -F https://www.youtube.com/watch?v=jMYfGoORtJc"                    

WARNING: [youtube] jMYfGoORtJc: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[info] Available formats for jMYfGoORtJc:
format code  extension  resolution note
171          webm       audio only DASH audio , audio@128k
140          m4a        audio only DASH audio , m4a_dash container, aac  @128k
160          mp4        144p       DASH video , video only
242          webm       240p       DASH video , video only
133          mp4        240p       DASH video , video only
243          webm       360p       DASH video , video only
134          mp4        360p       DASH video , video only
244          webm       480p       DASH video , video only
135          mp4        480p       DASH video , video only
17           3gp        176x144    
36           3gp        320x240    
5            flv        400x240    
43           webm       640x360    
18           mp4        640x360    (best)

**Comment by jaimeMF** [comment]
Post [output with the --verbose option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs)

**Comment by pythonteste** [comment]
After a few more attempts it doesn't seem to throw errors . I think it might have been some kind of isolated connection problem.

[turbo@localhost youtube]$ youtube-dl -v -F https://www.youtube.com/watch?v=jMYfGoORtJc
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.youtube.com/watch?v=jMYfGoORtJc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.8 - Linux-3.19.4-200.fc21.x86_64-x86_64-with-fedora-21-Obree
[debug] exe versions: ffmpeg 2.4.8, ffprobe 2.4.8
[debug] Proxy map: {}
[youtube] jMYfGoORtJc: Downloading webpage
[youtube] jMYfGoORtJc: Extracting video information
[youtube] jMYfGoORtJc: Downloading DASH manifest
[info] Available formats for jMYfGoORtJc:
format code  extension  resolution note
171          webm       audio only DASH audio   90k , audio@128k (44100Hz), 7.12MiB
140          m4a        audio only DASH audio   97k , m4a_dash container, aac  @128k (44100Hz), 7.85MiB
141          m4a        audio only DASH audio  193k , m4a_dash container, aac  @256k (44100Hz), 15.77MiB
160          mp4        192x144    DASH video  112k , 15fps, video only, 9.01MiB
278          webm       192x144    DASH video  147k , webm container, VP9, 1fps, video only, 5.69MiB
242          webm       320x240    DASH video  169k , 1fps, video only, 11.43MiB
133          mp4        320x240    DASH video  247k , 30fps, video only, 20.16MiB
243          webm       480x360    DASH video  314k , 1fps, video only, 22.32MiB
134          mp4        480x360    DASH video  479k , 30fps, video only, 24.32MiB
244          webm       640x480    DASH video  687k , 1fps, video only, 52.17MiB
135          mp4        640x480    DASH video 1133k , 30fps, video only, 84.99MiB
17           3gp        176x144    
36           3gp        320x240    
5            flv        400x240    
43           webm       640x360    
18           mp4        640x360    (best)
[turbo@localhost youtube]$ youtube-dl --version
2015.05.10
------------------------------------------------------------------------------------------------------------------------------

**Comment by pythonteste** [comment]
Here is some more weird output after successfully getting 2-3 videos;


-


[turbo@localhost youtube]$ youtube-dl -F https://www.youtube.com/watch?v=bdb1x2vQ2Z0
[youtube] bdb1x2vQ2Z0: Downloading webpage
[youtube] bdb1x2vQ2Z0: Extracting video information
[youtube] bdb1x2vQ2Z0: Downloading DASH manifest
WARNING: [youtube] bdb1x2vQ2Z0: Skipping DASH manifest: ExtractorError(u"Could not download DASH manifest: <urlopen error [Errno 101] Network is unreachable> (caused by URLError(error(101, 'Network is unreachable'),))",)
[info] Available formats for bdb1x2vQ2Z0:
format code  extension  resolution note
171          webm       audio only DASH audio , audio@128k
140          m4a        audio only DASH audio , m4a_dash container, aac  @128k
160          mp4        144p       DASH video , video only
242          webm       240p       DASH video , video only
133          mp4        240p       DASH video , video only
243          webm       360p       DASH video , video only
134          mp4        360p       DASH video , video only
244          webm       480p       DASH video , video only
135          mp4        480p       DASH video , video only
17           3gp        176x144    
36           3gp        320x240    
5            flv        400x240    
43           webm       640x360    
18           mp4        640x360    (best)

**Comment by jaimeMF** [comment]
In the second case it says: `URLError(error(101, 'Network is unreachable')`, it may be a problem with your connection.

**Comment by pythonteste** [comment]
ya thats what i was thinking since it runs smoothly now. Also i was most
definitely haveing some minor connection problems the night i was getting
errors. My connection was really slow that night too and it was taking
forever to execute youtube-dl commands

**Comment by jaimeMF** [comment]
I'm closing it then.
