### ISSUE TITLE
ERROR: ffmpeg: unrecognized option '-c'

### ISSUE THREAD

**Issue by fatchoumakou** [rg3/youtube-dl#5698]
Hello, I get this error.
Thank you in advance

root@multibille:/home/multibille# youtube-dl -v https://www.youtube.com/watch?v=6SSlG0j7gP4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=6SSlG0j7gP4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.6.5 - Linux-2.6.32-37-generic-pae-i686-with-Ubuntu-10.04-lucid
[debug] exe versions: ffmpeg SVN-r0.5.9-4, ffprobe SVN-r20090707
[debug] Proxy map: {}
[youtube] 6SSlG0j7gP4: Downloading webpage
[youtube] 6SSlG0j7gP4: Extracting video information
[youtube] 6SSlG0j7gP4: Downloading DASH manifest
[debug] Invoking downloader on 'https://r12---sn-25ge7n7e.googlevideo.com/videoplayback?id=e924a51b48fb80fe&itag=136&source=youtube&requiressl=yes&pl=25&ms=au&mv=u&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=214678779&lmt=1390129550798190&dur=1079.512&key=dg_yt0&upn=t5lNK7Ir4pQ&sver=3&mt=1431612561&signature=0F0B0DF1D1FA18DA9BDDFFB67338D0263E02D2A4.69847AF1734CAD4E2F54BBA330A48BC2CD93B940&fexp=9405349,9405958,9407663,9408093,9408142,9408592,9408704,9408710,9408952,9412774,9413159,9413447,9414935,945137,948124,952612,952637,952642&ip=195.154.97.77&ipbits=0&expire=1431634294&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,ms,mv,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Pinball Setup Video From Stern-6SSlG0j7gP4.f136.mp4
[download] 100% of 204.73MiB in 00:07
[debug] Invoking downloader on 'https://r12---sn-25ge7n7e.googlevideo.com/videoplayback?id=e924a51b48fb80fe&itag=141&source=youtube&requiressl=yes&pl=25&ms=au&mv=u&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=34420812&lmt=1390129538567408&dur=1079.611&key=dg_yt0&upn=t5lNK7Ir4pQ&sver=3&mt=1431612561&signature=1F2A09B624230D7F6A6DF6E10D2E7AA8FEB3239F.316E999AC60CA316809DD24A9BE5E133B3FFE3DB&fexp=9405349,9405958,9407663,9408093,9408142,9408592,9408704,9408710,9408952,9412774,9413159,9413447,9414935,945137,948124,952612,952637,952642&ip=195.154.97.77&ipbits=0&expire=1431634294&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,ms,mv,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Pinball Setup Video From Stern-6SSlG0j7gP4.f141.m4a
[download] 100% of 32.83MiB in 00:05
[ffmpeg] Merging formats into "Pinball Setup Video From Stern-6SSlG0j7gP4.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'Pinball Setup Video From Stern-6SSlG0j7gP4.f136.mp4' -i 'Pinball Setup Video From Stern-6SSlG0j7gP4.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'Pinball Setup Video From Stern-6SSlG0j7gP4.temp.mp4'
ERROR: ffmpeg: /build/buildd/ffmpeg-0.5.9/libavformat/mov.c:1456: mov_read_trak: Assertion `st->duration % sc->time_rate == 0' failed.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1529, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 590, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 148, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

**Comment by dstftw** [comment]
You are using an outdated version of ffmpeg, update it.
