### ISSUE TITLE
Buzzfeed URL

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5701]
URL:
http://www.buzzfeed.com/craigsilverman/the-most-adorable-crash-landing-ever#.eq7pX0BAmK

Output:

youtube-dl.py -v "http://www.buzzfeed.com/craigsilverman/the-most-adorable-crash-landing-ever#.eq7pX0BAmK"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.buzzfeed.com/craigsilverman/the-
most-adorable-crash-landing-ever#.eq7pX0BAmK']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.6 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[BuzzFeed] the-most-adorable-crash-landing-ever: Downloading webpage
[download] Downloading playlist: Watch This Baby Goose Make The Most Adorable Cr
ash Landing
[BuzzFeed] playlist Watch This Baby Goose Make The Most Adorable Crash Landing:
Collected 0 video ids (downloading 0 of them)

Thanks
Ringo

**Comment by RingoTheDog** [comment]
I may be wrong, but I believe BuzzFeed is already supported.

This post was just an unsupported BuzzFeed example...a Facebook embed. 
The source downloads correctly:
https://www.facebook.com/calgaryoutdoorcentre/videos/vb.109165569115225/971793786185728/?type=1&theater


FWIW, here is an Example of working BuzzFeed URL, with a YouTube Embed:
youtube-dl.py "http://www.buzzfeed.com/chrisreinacher/if-guy-b
est-friends-vacationed-like-girl-bffs#.ugeQZJ7Q7L"
[BuzzFeed] if-guy-best-friends-vacationed-like-girl-bffs: Downloading webpage
[download] Downloading playlist: If Guys Vacationed Like Girls
[BuzzFeed] playlist If Guys Vacationed Like Girls: Collected 1 video ids (downlo
ading 1 of them)
[download] Downloading video 1 of 1
[youtube] bt1P9IxUneE: Downloading webpage
[youtube] bt1P9IxUneE: Extracting video information
[youtube] bt1P9IxUneE: Downloading DASH manifest
[download] Resuming download at byte 14027125
[download] Destination: If Guy BFFs Vacationed Like Girl BFFs-bt1P9IxUneE.f137.m
p4
[download] 100% of 50.97MiB in 01:13
[download] Destination: If Guy BFFs Vacationed Like Girl BFFs-bt1P9IxUneE.f141.m
4a
[download] 100% of 4.15MiB in 00:01
[ffmpeg] Merging formats into "If Guy BFFs Vacationed Like Girl BFFs-bt1P9IxUneE
.mp4"
Deleting original file If Guy BFFs Vacationed Like Girl BFFs-bt1P9IxUneE.f137.mp
4 (pass -k to keep)
Deleting original file If Guy BFFs Vacationed Like Girl BFFs-bt1P9IxUneE.f141.m4
a (pass -k to keep)



Thanks 
Ringo

**Comment by TRox1972** [comment]
Should be relatively easy to fix. Only need to improve Facebook embed detection.

**Comment by yan12125** [comment]
@TRox1972 you're right, and Facebook embed URLs will be recognized in the next version.
