### ISSUE TITLE
Issue with downloading videos of Gamespot

### ISSUE THREAD

**Issue by dareTake** [rg3/youtube-dl#5707]
I'm having trouble downloading video from the Gamespot site, and I had noticed issue #3517, and the suggestion was to open a new ticket in case of error reoccuring.
URL : http://www.gamespot.com/videos/the-witcher-3-wild-hunt-xbox-one-now-playing/2300-6424837/

Here's the output of running with -v : 

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.gamespot.com/videos/the-witcher-3-wild-hunt-xbox-one-now-playing/2300-6424837/', u'--verbose', u'--write-pages']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.15
[debug] Python version 2.7.6 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1
[debug] Proxy map: {}
[GameSpot] 6424837: Downloading webpage
[GameSpot] Saving request to 6424837_http_-_www.gamespot.com_videos_the-witcher-3-wild-hunt-xbox-one-now-playing_2300-6424837_.dump
ERROR: An extractor error has occured. (caused by KeyError(u'f4m_stream',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/gamespot.py", line 38, in _real_extract
    f4m_url = data_video['videoStreams']['f4m_stream']
KeyError: u'f4m_stream'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 279, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'f4m_stream',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dareTake** [comment]
Here is the dump file, 
https://gist.github.com/dareTake/825100c1a87ad53a601d

**Comment by jaimeMF** [comment]
It will work in the next version, thanks for the report.
