### ISSUE TITLE
HTTP Error 404: Not Found (caused by HTTPError()); on YouTube video

### ISSUE THREAD

**Issue by iembry** [rg3/youtube-dl#5709]
Thank you.

The complete output (that printed) follows:

userh@computer:~/Videos$ youtube-dl --verbose -F https://www.youtube.com/watch?t=31&v=bOelqGl2Ux0
[1] 17542
userh@computer:~/Videos$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://www.youtube.com/watch?t=31']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.6 - Linux-3.16.0-31-lowlatency-x86_64-with-Trisquel-7.0-belenos
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] watch?t=31: Requesting header
[redirect] Following redirect to https://www.youtube.com/supported_browsers?next_url=%2F
[youtube:user] supported_browsers: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1710, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by jaimeMF** [comment]
You have to quote the url, see [this FAQ entry for more info](https://github.com/rg3/youtube-dl/blob/50b901306406d5c37f31880860e2a4dbb5e0a165/README.md#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).

**Comment by iembry** [comment]
OK, thank you. I have not used quotes in the past with youtube-dl and I have not had any issues until today.

**Comment by jaimeMF** [comment]
The problem is that the url contains '&' (which is quite common in urls). Note that youtube-dl has nothing to do with it, it's just how the shell handles it (if you pay attention to the verbose output you'll see that youtube-dl only gets `https://www.youtube.com/watch?t=31`, which is not a valid url).

**Comment by iembry** [comment]
OK, thank you again for your prompt assistance.
