### ISSUE TITLE
Format listed but not reachable

### ISSUE THREAD

**Issue by yetiyeti** [rg3/youtube-dl#5711]
Hello

I cannot get the best definition.

Is it an issue from youtube-dl or did they remove the link ?

http://www.rts.ch/play/tv/36-9%C2%B0/video/369%C2%B0-troubles-bipolaires-entre-euphorie-et-depression?id=77119

C:\>youtube-dl http://www.rts.ch/play/tv/36-9%C2%B0/video/369%C2%B0-troubles-bip
olaires-entre-euphorie-et-depression?id=77119 -F --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.rts.ch/play/tv/36-9%C2%B0/video/369%C2%
B0-troubles-bipolaires-entre-euphorie-et-depression?id=77119', u'-F', u'--verbos
e']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-69258-gf994000
[debug] Proxy map: {}
[RTS] 369%C2%B0-troubles-bipolaires-entre-euphorie-et-depression: Downloading JS
ON metadata
[RTS] 77119: Downloading m3u8 information
[RTS] 77119: Downloading hds token
[RTS] 77119: Downloading f4m manifest
[RTS] 77119: Downloading hds_sd token
[RTS] 77119: Downloading f4m manifest
[RTS] 77119: Downloading m3u8 information
[info] Available formats for 77119:
format code  extension  resolution note
hls-meta     mp4        multiple   Quality selection URL
hls_sd-meta  mp4        multiple   Quality selection URL
hls-23       mp4        unknown      23k , mp4a
hls_sd-23    mp4        unknown      23k , mp4a
hls-206      mp4        320x180     206k , avc1,  mp4a
hls_sd-206   mp4        320x180     206k , avc1,  mp4a
hls-411      mp4        480x270     411k , avc1,  mp4a
hls_sd-411   mp4        480x270     411k , avc1,  mp4a
hls-697      mp4        640x360     697k , avc1,  mp4a
hls_sd-697   mp4        640x360     697k , avc1,  mp4a
mp4-101k     mp4        unknown     101k
wmv-161k     wmv        unknown     161k
hds-206      flv        unknown     206k
hds_sd-206   flv        unknown     206k
hds-411      flv        unknown     411k
hds_sd-411   flv        unknown     411k
mp4-451k     mp4        unknown     451k
flv-501k     flv        unknown     501k
m4v-511k     m4v        unknown     511k
hds-697      flv        unknown     697k
hds_sd-697   flv        unknown     697k
mp4-701k     mp4        unknown     701k
wmv-1501k    wmv        unknown    1501k  (best)

C:\>youtube-dl http://www.rts.ch/play/tv/36-9%C2%B0/video/369%C2%B0-troubles-bip
olaires-entre-euphorie-et-depression?id=77119 -f best --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.rts.ch/play/tv/36-9%C2%B0/video/369%C2%
B0-troubles-bipolaires-entre-euphorie-et-depression?id=77119', u'-f', u'best', u
'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-69258-gf994000
[debug] Proxy map: {}
[RTS] 369%C2%B0-troubles-bipolaires-entre-euphorie-et-depression: Downloading JS
ON metadata
[RTS] 77119: Downloading m3u8 information
[RTS] 77119: Downloading hds token
[RTS] 77119: Downloading f4m manifest
[RTS] 77119: Downloading hds_sd token
[RTS] 77119: Downloading f4m manifest
[RTS] 77119: Downloading m3u8 information
[debug] Invoking downloader on u'http://download-video.rts.ch/36/2009/36_1028200
9-1501k.wmv?start=00:00:00.000&end=00:47:57.816'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1417, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1359, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 59, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1710, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 404: Not Found

Thanx

**Comment by dstftw** [comment]
Served wmv URLs are 404 and will be filtered in the next version. Thanks for the report.
