### ISSUE TITLE
LiveLeak extractor - youtube-dl doesn't download max. quality (HD)

### ISSUE THREAD

**Issue by CiscoPress** [rg3/youtube-dl#5713]
Example URL
    http://www.liveleak.com/view?i=b71_1427568862

Jdownloader gets

Width                                    : 720 pixels   
Height                                   : 1 280 pixels 

youtube-dl only

Width                                    : 270 pixels     
Height                                   : 480 pixels

**Comment by jenlunds** [comment]
Yes I can't get it to work either. Is there some way to fix it?

It only finds the low res. one.

format code  extension  resolution note
0                   mp4          unknown

**Comment by aeph6Ee0** [comment]
This has been fixed on 14 Jun 2015 with commit 9fd24e3a227a059eed07b679dac858e5bd747123.
Youtube-dl extracts the video now with a resolution of 1920x1080 pixels.
Please close this issue.
