### ISSUE TITLE
[Yahoo Screen] Add support for Closed Caption 

### ISSUE THREAD

**Issue by krawhitham** [rg3/youtube-dl#5714]
Example URL:
https://screen.yahoo.com/community/ladders-070001899.html

https://s.yimg.com/os/en-US/video/webvtt_/community/_pVYRY9MmCpkfofpp1ISGR7W3bKs5REv3Jx_0_Qe6h_b5mS2O7NKCkRDW0Cs0rt_e2u3n-PgUKTw-_0_0.vtt

**Comment by yan12125** [comment]
Thanks. Yahoo closed captions will be supported in the next version.
