### ISSUE TITLE
"updating" youtube-dl broke it ...

### ISSUE THREAD

**Issue by Albretch** [rg3/youtube-dl#5722]
youtube-dl was working fine till I "updated" it

first it was downloading more than one file and the video file seemed to play out as an audio one. Then I tried --prefer-ffmpeg and it seemed to have downloaded the video file without audio ...

Why is this happening? How could I fix that problem?

$ youtube-dl --version
2015.05.04

$ youtube-dl --dump-user-agent
Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)

$ youtube-dl 3hj49xDEXow
[youtube] 3hj49xDEXow: Downloading webpage
[youtube] 3hj49xDEXow: Extracting video information
[youtube] 3hj49xDEXow: Downloading DASH manifest
[download] Destination: The age of fear - psychiatry's reign of terror.-3hj49xDEXow.f135.mp4
[download] 100% of 482.36MiB in 03:18
[download] Destination: The age of fear - psychiatry's reign of terror.-3hj49xDEXow.f141.m4a
[download] 100% of 197.23MiB in 01:17
[ffmpeg] Merging formats into "The age of fear - psychiatry's reign of terror.-3hj49xDEXow.mp4"
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
Deleting original file The age of fear - psychiatry's reign of terror.-3hj49xDEXow.f135.mp4 (pass -k to keep)
Deleting original file The age of fear - psychiatry's reign of terror.-3hj49xDEXow.f141.m4a (pass -k to keep)

$ ls -l "The age of fear - psychiatry's reign of terror.-3hj49xDEXow.mp4"
-rw-r--r-- 1 knoppix knoppix 207858560 Feb 25  2014 The age of fear - psychiatry's reign of terror.-3hj49xDEXow.mp4

$ youtube-dl --prefer-ffmpeg 3hj49xDEXow
[youtube] 3hj49xDEXow: Downloading webpage
[youtube] 3hj49xDEXow: Extracting video information
[youtube] 3hj49xDEXow: Downloading DASH manifest
[download] Destination: The age of fear - psychiatry's reign of terror.-3hj49xDEXow.f135.mp4
[download] 100% of 482.36MiB in 03:14
[download] Destination: The age of fear - psychiatry's reign of terror.-3hj49xDEXow.f141.m4a
[download] 100% of 197.23MiB in 01:19
[ffmpeg] Merging formats into "The age of fear - psychiatry's reign of terror.-3hj49xDEXow.mp4"
WARNING: Your copy of ffmpeg is outdated, update ffmpeg to version 1.0 or newer if you encounter any errors.
ERROR: Failed to set value 'copy' for option 'c'

$ ls -l "The age of fear - psychiatry's reign of terror.-3hj49xDEXow.f135.mp4"
-rw-r--r-- 1 knoppix knoppix 505794898 Feb 25  2014 The age of fear - psychiatry's reign of terror.-3hj49xDEXow.f135.mp4

**Comment by Albretch** [comment]
is there an option to downgrade youtube-dl to a working version or download a previous version?

 lbrtchx

**Comment by Albretch** [comment]
$ which ffmpeg
/usr/bin/ffmpeg

$ ffmpeg -version
ffmpeg version 0.8.6-6:0.8.6-1, Copyright (c) 2000-2013 the Libav developers
  built on Mar 24 2013 07:20:17 with gcc 4.7.2
*** THIS PROGRAM IS DEPRECATED ***
This program is only provided for compatibility and will be removed in a future release. Please use avconv instead.
ffmpeg 0.8.6-6:0.8.6-1
libavutil    51. 22. 1 / 51. 22. 1
libavcodec   53. 35. 0 / 53. 35. 0
libavformat  53. 21. 1 / 53. 21. 1
libavdevice  53.  2. 0 / 53.  2. 0
libavfilter   2. 15. 0 /  2. 15. 0
libswscale    2.  1. 0 /  2.  1. 0
libpostproc  52.  0. 0 / 52.  0. 0

$ uname -a
Linux Microknoppix 3.9.6 #25 SMP PREEMPT Sat Jun 15 15:27:01 CEST 2013 i686 GNU/Linux

**Comment by dstftw** [comment]
Update ffmpeg.
Read the last two paragraphs of [format selection section](https://github.com/rg3/youtube-dl#format-selection) for new behavior rationale.
