### ISSUE TITLE
Add option for getting number of videos of a channel/user

### ISSUE THREAD

**Issue by nikhilchopra1** [rg3/youtube-dl#5727]
Is there any way to check how many videos has a channel/user uploaded ?

**Comment by jaimeMF** [comment]
Using the json output with [jq](https://stedolan.github.io/jq/):
```sh
$ youtube-dl 'https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re' -J --flat-playlist | jq '.entries | length'
3
```

**Comment by nikhilchopra1** [comment]
Not a single playlist. All uploads by user.

**Comment by jaimeMF** [comment]
The same command works:
```sh
$ youtube-dl 'https://www.youtube.com/user/TheLinuxFoundation' -J --flat-playlist | jq '.entries | length'
693
```

**Comment by nikhilchopra1** [comment]
Is it possible to create some short code ? Like  --nov (number of videos) ?

**Comment by jaimeMF** [comment]
If it can be easily done by chaining two commands, I don't think it's really needed. Why isn't enough for you?

**Comment by nikhilchopra1** [comment]
Would be convenient .Who wants to type long command every time ? . Sorry if I sound rude. It's justa a suggestion .

**Comment by nikhilchopra1** [comment]
It gives an error. jq is not recognized as an internal or external command.

**Comment by jaimeMF** [comment]
My main reason agains adding a new options is that we would have to add an option for every single feature that people need. On the other side when you build something generic like the json output you give complete flexibility for what you can do and you don't need to modify youtube-dl for most of things (they will of course always be features that require new options).

You have to install [jq](https://stedolan.github.io/jq/)

**Comment by nikhilchopra1** [comment]
Okay. Sorry. Actually I currently use the -F option . It downloads all the pages. Then gives like " Download video 1 or 500". If it was possible to store the "500" into some variable then output it. But it is a slow method. But doesn't require external software. ( Sorry I am not a coder . Method may sound stupid ).

**Comment by nikhilchopra1** [comment]
Actually I use this method for most sites. I regularly download full youtube channels and vine channel. It works for vine too.
