### ISSUE TITLE
requested format not available. How to i skip or download another quality?

### ISSUE THREAD

**Issue by nikhilchopra1** [rg3/youtube-dl#5730]
I was downloading a youtube users' whole channel.There are 1029 videos. I was download all in -f 135+140 quality. At 180th video it gave an error "requested format not available".What would be the best solution for this? Any way to skip it and resume to next one or download another quality ?

**Comment by jaimeMF** [comment]
You can especify fallback formats with `/`, for example `-f 135+140/best` (you may want to use `-f 135+140/bestvideo+bestaudio/best` if you want to get DASH formats). See [this section of the README](https://github.com/rg3/youtube-dl/blob/50b901306406d5c37f31880860e2a4dbb5e0a165/README.md#format-selection) for more info.
