### ISSUE TITLE
WDR Elefantenseite not supported

### ISSUE THREAD

**Issue by derdennis** [rg3/youtube-dl#5731]
Hi all,

I wanted to download some videos from the german [Elefantenseite](http://www.wdrmaus.de/elefantenseite/), a subsite of the already supported [WDR Maus](http://www.wdrmaus.de/).

There are many single video site like [this one](http://www.wdrmaus.de/elefantenseite/#/anke_singt_auf_der_mauer_auf_der_lauer) and youtube-dl is not able to download the video. Output as follows:

```
$ youtube-dl --verbose http://www.wdrmaus.de/elefantenseite/#/anke_singt_auf_der_mauer_auf_der_lauer
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.wdrmaus.de/elefantenseite/#/anke_singt_auf_der_mauer_auf_der_lauer']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.15
[debug] Python version 2.7.6 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.3
[debug] Proxy map: {}
[WDRMaus] elefantenseite: Downloading webpage
ERROR: Unable to extract parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/wdr.py", line 240, in _real_extract
    r'<a href="\?startVideo=1&amp;([^"]+)"', webpage, 'parameters')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 564, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Is there an easy fix for this issue? If I can be of any further help, please let me know.

Thanks, cheers

Dennis

**Comment by Boris-de** [comment]
I've added support for the elefantenseite in #9723 after @s-timm mentioned the missing support in #8843. Could you try and see if this works for you? I tested with your URL and it worked for me.

**Comment by derdennis** [comment]
Hi Boris,

this does not seem to work. I downloaded the current zip from your repo and also from the main repo. Same effect. Example output from your repo:

 python -m youtube_dl --verbose http://www.wdrmaus.de/elefantenseite/#/tanja_und_andre_becherknete
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.wdrmaus.de/elefantenseite/#/tanja_und_andre_becherknete']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 2.7.11 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.3
[debug] Proxy map: {}
[generic] tanja_und_andre_becherknete: Requesting header
WARNING: Falling back on generic information extractor.
[generic] tanja_und_andre_becherknete: Downloading webpage
[generic] tanja_und_andre_becherknete: Extracting information
ERROR: Unsupported URL: http://www.wdrmaus.de/elefantenseite/#/tanja_und_andre_becherknete
Traceback (most recent call last):
  File "youtube_dl/extractor/generic.py", line 1443, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "youtube_dl/compat.py", line 287, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "youtube_dl/compat.py", line 276, in _XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 37, column 2
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 342, in extract
    return self._real_extract(url)
  File "youtube_dl/extractor/generic.py", line 2145, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.wdrmaus.de/elefantenseite/#/tanja_und_andre_becherknete

Am I doing something wrong?

Regards

Dennis

**Comment by Boris-de** [comment]
@derdennis This looks like the default extractor is still being used, so I guess you don't have the patch yet.
Did you by any change download the zip of my master branch? I added the changes to a separate branch named "elefantenseite" which you can download too [1]. With this download the link should work as it does for me.

[1] https://github.com/Boris-de/youtube-dl/tree/elefantenseite

**Comment by derdennis** [comment]
Hi @Boris-de,

Yes, indeed, I downloaded your master branch. I tried again with the elefantenseite-branch and now, sure enough, everything works fine:

```
$ python -m youtube_dl --verbose http://www.wdrmaus.de/elefantenseite/#/tanja_und_andre_becherknete
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.wdrmaus.de/elefantenseite/#/tanja_und_andre_becherknete']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 2.7.11 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.3
[debug] Proxy map: {}
[WDR] None: Downloading webpage
[WDR] tanja_und_andre_becherknete config: Downloading XML
[WDR] tanja_und_andre_becherknete toc: Downloading XML
[WDR] tanja_und_andre_becherknete xmlPath: Downloading XML
[WDR] metadata: Downloading JSON metadata
[WDR] Downloading m3u8 information
[WDR] Downloading f4m manifest
[debug] Invoking downloader on u'http://adaptiv.wdr.de/i/medp/ww/fsk0/108/1088224/,1088224_12507374,1088224_12507372,1088224_12507373,1088224_12507375,.mp4.csmil/index_2_av.m3u8?null=0'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 15
[download] Destination: Becherknete-mdb-1088224.mp4
[download] 100% of 31.63MiB in 00:06
[ffmpeg] Fixing malformated aac bitstream in "Becherknete-mdb-1088224.mp4"
[debug] ffmpeg command line: ffmpeg -y -i file:Becherknete-mdb-1088224.mp4 -c copy -f mp4 -bsf:a aac_adtstoasc file:Becherknete-mdb-1088224.temp.mp4
```

Thanks a bunch, you made me and my kids very happy.

Regards,

Dennis

**Comment by sleske** [comment]
The new PR #14598 adds support for the Elefantenseite.
