### ISSUE TITLE
Not picking the best quality?

### ISSUE THREAD

**Issue by TarekSalama** [rg3/youtube-dl#5732]
So I have noticed that some videos won't get downloaded using the best quality. For example, on Youtube, a video would be viewable in 480 but Youtube dl would download it in 360. I tried forcing it to download in Full HD/720/480/360 but I ended up getting videos with no thumbnail and trying to skim through it ended up in the video freezing. Moreover, the video had no audio.
So why isn't Youtube-dl downloading videos in their best quality? How do I fix it without running into those issues?

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by TarekSalama** [comment]
C:\Users\Tarek\Desktop>C:\Users\Tarek\Desktop\youtube-dl.exe -v
[debug] System config: []
[debug] User config: [u'-U', u'-f', u'137/136/135', u'--no-overwrites', u'--no-c
ache-dir', u'--restrict-filenames', u'--ignore-errors', u'--batch-file', u'C:/Us
ers/Tarek/Desktop/batchvideos.txt', u'-o', u'/downloads/%(uploader)s/%(title)s_%
(uploader)s_%(id)s.%(ext)s']
[debug] Command-line args: [u'-v']
[debug] Batch file urls: [u'https://www.youtube.com/watch?v=7fwqANb9Acg']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
Updating to version 2015.05.15 ...
Waiting for file handle to be closed ...
[youtube] 7fwqANb9Acg: Downloading webpage
[youtube] 7fwqANb9Acg: Extracting video information
[youtube] 7fwqANb9Acg: Downloading DASH manifest
[debug] Invoking downloader on 'https://r4---sn-uxaxjvhxbt2u-5ate.googlevideo.co
m/videoplayback?id=edfc2a00d6fd01c8&itag=137&source=youtube&requiressl=yes&pl=20
&ms=au&mm=31&mv=m&ratebypass=yes&mime=video/mp4&gir=yes&clen=93210415&lmt=142993
5456645761&dur=220.345&sver=3&fexp=901816,916661,9406543,9407991,9408142,9408590
,9408704,9408710,9408807,9412489,9412955,945137,948124,952612,952637,952642&mt=1
431868168&upn=SS0ZY4ppK-E&signature=22BC4821B08EF891104DA076F553985AA74F787D.13E
0B9523E510994A7016540D0F0F9C93FDBA9F6&key=dg_yt0&ip=197.38.154.18&ipbits=0&expir
e=1431889878&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,ms,mm,mv,rate
bypass,mime,gir,clen,lmt,dur'
[download] Destination: downloads\TechRax\Blue_Apple_Watch_Sport_42mm_Drop_Test_
TechRax_7fwqANb9Acg.mp4
[download]   1.0% of 88.89MiB at 419.34KiB/s ETA 03:34Access is denied.
Updated youtube-dl to version 2015.05.15.
[download] 100% of 88.89MiB in 03:39


And this is the config file:

-U -f 137/136/135 --no-overwrites --no-cache-dir --restrict-filenames --ignore-errors --batch-file C:/Users/Tarek/Desktop/batchvideos.txt -o /downloads/%(uploader)s/%(title)s_%(uploader)s_%(id)s.%(ext)s

PS: I have noticed that the file attributes don't have the video quality. I guess this issue also happened when I added the -f 137/136/135 part.

**Comment by dstftw** [comment]
So what's wrong? You have explicitly specified to download format 137 with fallback to 136 and 135 that resulted in downloading 137 just as expected. Those formats are video only as stated in formats output (`-F` option):
```
135          mp4        854x480    DASH video 1143k , 24fps, video only, 20.73MiB
136          mp4        1280x720   DASH video 2248k , 24fps, video only, 41.46MiB
137          mp4        1920x1080  DASH video 4655k , 24fps, video only, 88.89MiB
```
To download best quality you should not specify any `-f` it's done automatically. You also have to install ffmpeg/avconv. [More on this](https://github.com/rg3/youtube-dl#format-selection).

**Comment by TarekSalama** [comment]
Well if I don't specify the quality, it sometimes downloads a lesser one. Does it take into account the audio when choosing the quality?

**Comment by dstftw** [comment]
Then post the log when you don't specify the `-f` and explain what's wrong.

**Comment by dstftw** [comment]
As already noticed you have to install ffmpeg or avconv to download bests overall quality. It's not installed on your system.
