### ISSUE TITLE
error downloding

### ISSUE THREAD

**Issue by atremblier** [rg3/youtube-dl#5735]
Hi,

I try to dowload a video on the france 2's website but, i've got this error message 
root@depannepc:/home/administrateur/Bureau# youtube-dl --verbose http://www.francetvinfo.fr/meteo/meteo-france-2/video-la-meteo-du-dimanche-17-mai-2015-a-13h00_908511.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.francetvinfo.fr/meteo/meteo-france-2/video-la-meteo-du-dimanche-17-mai-2015-a-13h00_908511.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.15
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.0
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6
[debug] Proxy map: {}
[francetvinfo.fr] video-la-meteo-du-dimanche-17-mai-2015-a-13h00_908511: Downloading webpage
[francetvinfo.fr] 122564715: Downloading video JSON
[francetvinfo.fr] 122564715: Downloading f4m manifest token
[francetvinfo.fr] 122564715: Downloading f4m manifest
ERROR: Unable to download f4m manifest: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1710, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

thanks a lot for your help

**Comment by remitamine** [comment]
it's working now.
```
youtube-dl -v http://www.francetvinfo.fr/meteo/meteo-france-2/video-la-meteo-du-dimanche-17-mai-2015-a-13h00_908511.html
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c', '--external-downloader-args', '-x 16 --check-certificate=false', '-f', 'best[height<=?720]', '--sub-lang', 'ar,en', '--write-sub']
[debug] Command-line args: ['-v', 'http://www.francetvinfo.fr/meteo/meteo-france-2/video-la-meteo-du-dimanche-17-mai-2015-a-13h00_908511.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 3.4.3 - Linux-4.1.2-2-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[francetvinfo.fr] video-la-meteo-du-dimanche-17-mai-2015-a-13h00_908511: Downloading webpage
[francetvinfo.fr] 122564715: Downloading video JSON
[francetvinfo.fr] 122564715: Downloading f4m manifest token
[francetvinfo.fr] 122564715: Downloading f4m manifest
[francetvinfo.fr] 122564715: Downloading m3u8 information
[francetvinfo.fr] 122564715: Downloading m3u8 information
[debug] Invoking downloader on 'http://replayftv-vh.akamaihd.net/z/streaming-adaptatif/2015/S20/J7/122564715-5558744f9d4f4-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/manifest.f4m?hdnea=exp=1438299971~acl=%2fz%2fstreaming-adaptatif%2f2015%2fS20%2fJ7%2f122564715-5558744f9d4f4-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil*~hmac=2821b04dd787fe8fd183d3945b0a87969dd5a49d797a8f582e81bd4ecd25caef&hdcore=3.7.0&plugin=aasp-3.7.0.39.44'
[download] Downloading f4m manifest
[download] Destination: Météo 2-122564715.flv
[download]  26.7% of ~15.90MiB at 105.79KiB/s ETA 01:39
```

**Comment by jaimeMF** [comment]
It's working, I'm closing it but feel free to comment here if it fails for you and we'll reopen the issue.
