### ISSUE TITLE
[http://ldt.iri.centrepompidou.fr] JW Player with content preventing HEAD method

### ISSUE THREAD

**Issue by cregouby** [rg3/youtube-dl#5736]
Hello, 
JW player used in this Mooc site seems to prevent the HEAD method to succeed (403 forbidden) in the sequence of youtube-dl downloading the video. 
Using Google-chrome & the JW player doesn't give the 403 problem and succeed playing the rtmp stream with Wireshark see frames RTMP	onStatus('NetStream.Play.Start') with 
      Property 'description' String 'Started playing video/ldtplatform/upload/cours_ic01/cours2.mp4.' (I don't know if it helps)
Could you please help to solve it ?
Thanks a lot !
Christophe

creg@creg:~/⟫ youtube-dl -i -v http://ldt.iri.centrepompidou.fr//ldtplatform/ldt/embediframe/?content_id=033d3548-bc0e-11e4-831a-00145ea4a2be&project_id=553b859c-bf39-11e4-831a-00145ea4a2be                                                          
[1] 27124
creg@creg:~/⟫ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-i', u'-v', u'http://ldt.iri.centrepompidou.fr//ldtplatform/ldt/embediframe/?content_id=033d3548-bc0e-11e4-831a-00145ea4a2be']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.15
[debug] Python version 2.7.9 - Linux-3.19.0-16-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?content_id=033d3548-bc0e-11e4-831a-00145ea4a2be: Requesting header
WARNING: Could not send HEAD request to http://ldt.iri.centrepompidou.fr//ldtplatform/ldt/embediframe/?content_id=033d3548-bc0e-11e4-831a-00145ea4a2be: HTTP Error 403: FORBIDDEN
[generic] ?content_id=033d3548-bc0e-11e4-831a-00145ea4a2be: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: FORBIDDEN (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1710, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

[1]+  Termine 1               youtube-dl -i -v http://ldt.iri.centrepompidou.fr//ldtplatform/ldt/embediframe/?content_id=033d3548-bc0e-11e4-831a-00145ea4a2be

**Comment by jaimeMF** [comment]
Note that you have to [quote the url](https://github.com/rg3/youtube-dl/blob/50b901306406d5c37f31880860e2a4dbb5e0a165/README.md#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command), otherwise youtube-dl only gets part of it (that's why you get the `403 Forbidden` error).

But even with the full url it fails, so we'll have to add support for it.

**Comment by cregouby** [comment]
Thanks for your support jaimeMF !

**Comment by cregouby** [comment]
Hello JaimeMF.
Error on my side : a variable 'project_id' was missing in the url is missing and lead to the 403.
Adding that variable, I get an "unSupported Error: unsupported URL"
I will close this one and reoppen a proper issue for that
Thanks anyway
cregouby
