### ISSUE TITLE
Download only 1080p videos

### ISSUE THREAD

**Issue by WeWin55** [rg3/youtube-dl#5738]
Hello,

I want to download just 1920x1080 mp4 videos with audio.

My download script for downloading the video is:

-f "bestvideo[ext=mp4][height=1080]+bestaudio/best"

But if youtube is working on the video and its only available at lower resolution it just downloads the lower ones.
I dont know how to make youtube-dl to just download videos that are mp4 and 1920x1080
PS: Another little question: 
I it possible to put the output file name of the finished downloaded file in a variable?

Thanks in advance,

Greetings WeWin

**Comment by jaimeMF** [comment]
`/best` means that it will fallback to the `best` format if the 1080p format is not available, using `-f "bestvideo[ext=mp4][height=1080]+bestaudio"` will only download the 1080 format (but it will fail if it's not available).

> it possible to put the output file name of the finished downloaded file in a variable?

Use `--get-filename`, which will only print the filename and not download the video.

**Comment by WeWin55** [comment]
Thanks ;)
Am 18.05.2015 11:25 vorm. schrieb "Jaime Marquínez Ferrándiz" <
notifications@github.com>:
>
> /best means that it will fallback to the best format if the 1080p format
is not available, using -f "bestvideo[ext=mp4][height=1080]+bestaudio" will
only download the 1080 format (but it will fail if it's not available).
>>
>> it possible to put the output file name of the finished downloaded file
in a variable?
>
> Use --get-filename, which will only print the filename and not download
the video.
