### ISSUE TITLE
Output filename bug when closing youtube-dl while downloading mp3 stream on Windows

### ISSUE THREAD

**Issue by Steveland** [rg3/youtube-dl#5744]
Hello,

When I download an mp3 stream with the command below, then close the console window to cut the stream, the output filename is .mp3.part instead of being .mp3.
youtube-dl.exe http://1live.radio.de

**Comment by justhankmoody** [comment]
You are try set option "-o" to set another file name ?

**Comment by manrodriguezf** [comment]
Also you can try to rename the files as soon as youtube-dl exits:
rename *.mp3.part *.mp3

**Comment by mpenkov** [comment]
@Steveland Is this still a problem? If not, then we can probably close this ticket.
