### ISSUE TITLE
Youtube HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by ra655566** [rg3/youtube-dl#5749]
Seems there is a bug, can you please fix this issue?

$ youtube-dl.exe --verbose http://www.youtube.com/watch?v=Llu4kNm9-hA
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.youtube.com/watch?v=Llu4kNm9-hA']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.05.15
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Llu4kNm9-hA: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 312, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1710, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

**Comment by jaimeMF** [comment]
It works for me, can you watch the video in a browser?

**Comment by ra655566** [comment]
Yes, in all browsers it works.

**Comment by ra655566** [comment]
Ok, I think it's network problem. This video was downloaded successfully on machine from another network.
But what may be a cause of the problem?

**Comment by jaimeMF** [comment]
If on the **same computer** you can watch it on the browser but not download with youtube-dl, that's definetely strange (specially because it's not that the webpage is missing something, but that the webpage can't even be downloaded). If you are using some proxy/vpn in your broswer (and it's required for watching the video) you also need to configure youtube-dl to use it. Are you in your home network, or in some school/company network?

**Comment by ra655566** [comment]
jaimeMF, thanks for responses very much.
Today it works fine, so I can't reproduce the error.
