### ISSUE TITLE
ERROR: Did not get any data blocks

### ISSUE THREAD

**Issue by strex** [rg3/youtube-dl#575]
Hello,

I get this error message when I try to download videos as 480p webm (-f 44).

It only happens with some videos, for example:

youtube-dl -f 44 http://www.youtube.com/watch?v=Q03mfQqw0NI
[youtube] Setting language
[youtube] Q03mfQqw0NI: Downloading video webpage
[youtube] Q03mfQqw0NI: Downloading video info webpage
[youtube] Q03mfQqw0NI: Extracting video information

ERROR: Did not get any data blocks

**Comment by NulAsh** [comment]
youtube-dl https://youtu.be/ZMCYc9DjemM
`[youtube] ZMCYc9DjemM: Downloading webpage
[youtube] ZMCYc9DjemM: Downloading video info webpage
[download] Destination: Build Swimming pool on the House-ZMCYc9DjemM.mp4
[download]   0.2% of 238.77MiB at 612.47KiB/s ETA 06:38        [download] Got server HTTP error: Downloaded 400789 bytes, expected 250368493 bytes. Retrying (attempt 1 of 10)...


ERROR: Did not get any data blocks`

**Comment by dstftw** [comment]
Most of such errors are cause by server side youtube errors.
