### ISSUE TITLE
ERROR: audio conversion failed: Unknown encoder 'libmp3lame'

### ISSUE THREAD

**Issue by TheGr33k** [rg3/youtube-dl#5750]
[avconv] Destination: Taylor Swift - Bad Blood ft. Kendrick Lamar.mp3
ERROR: audio conversion failed: Unknown encoder 'libmp3lame'
How can i install libmp3lame ?
I am on centos 6

**Comment by TheGr33k** [comment]
I just went with ffmpeg instead

Here a tutorial if anyone need it

https://github.com/supermasita/ufe/wiki/Installing-FFMPEG-on-CentOS-with-ATRPMS-repo

**Comment by nathanael-poupon** [comment]
I had the same error and had to rebuild ffmpeg with the libmp3lame support for it to work.

Thanks to "ghost" : 
https://github.com/rg3/youtube-dl/issues/302
