### ISSUE TITLE
youtube-dl in php not working(extract audio)

### ISSUE THREAD

**Issue by TheGr33k** [rg3/youtube-dl#5752]
`$url=exec("youtube-dl -g https://www.youtube.com/watch?v=mk48xRzuNvA");` works perfectly but the following doesn't seems to execute on the server

`exec("youtube-dl -x --audio-format mp3 -f 18 -o \"%(title)s.%(ext)s\"  https://www.youtube.com/watch?v=mk48xRzuNvA");`

However if i load the equivalent command in commandline it works just fine

`youtube-dl -x --audio-format mp3 -f 18 -o "%(title)s.%(ext)s"  https://www.youtube.com/watch?v=mk48xRzuNvA`

Is there something wrong with the way i escape the command in php or something

**Comment by dstftw** [comment]
Post the output of running this in php: 
```echo system("youtube-dl -x --audio-format mp3 -f 18 -o \"%(title)s.%(ext)s\" https://www.youtube.com/watch?v=mk48xRzuNvA 2>&1");```

**Comment by TheGr33k** [comment]
`[youtube] mk48xRzuNvA: Downloading webpage [youtube] mk48xRzuNvA: Extracting video information [youtube] mk48xRzuNvA: Downloading js player en_US-vflHV7Wup WARNING: Writing cache to u'/home/nginx/.cache/youtube-dl/youtube-sigfuncs/js_en_US-vflHV7Wup_40.41.json' failed: Traceback (most recent call last): File "/usr/local/bin/youtube-dl/youtube_dl/cache.py", line 46, in store os.makedirs(os.path.dirname(fn)) File "/usr/lib64/python2.6/os.py", line 150, in makedirs makedirs(head, mode) File "/usr/lib64/python2.6/os.py", line 150, in makedirs makedirs(head, mode) File "/usr/lib64/python2.6/os.py", line 150, in makedirs makedirs(head, mode) File "/usr/lib64/python2.6/os.py", line 157, in makedirs mkdir(name, mode) OSError: [Errno 13] Permission denied: '/home/nginx' [youtube] mk48xRzuNvA: Downloading DASH manifest ERROR: unable to open for writing: [Errno 13] Permission denied: 'The Script - Hall of Fame ft. will.i.am.mp4.part' ERROR: unable to open for writing: [Errno 13] Permission denied: 'The Script - Hall of Fame ft. will.i.am.mp4.part'`

Seems to be a permission issue....how to fix that

**Comment by dstftw** [comment]
Set [output template](https://github.com/rg3/youtube-dl#output-template) to the location that is writable by the user account php is running under.
