### ISSUE TITLE
Best resolution not an option with audio?

### ISSUE THREAD

**Issue by beamer159** [rg3/youtube-dl#5757]
I would like to download a Youtube video with its best resolution and audio. I ran the following to see my options:

youtube-dl -F [URL]

I received the following: http://i.imgur.com/162PZzj.png

From the picture, you can see that the best resolution this video provides is 480p. However, if I want to download the video and audio in one .mp4 file, I have to settle for 360p. I am just curious why this is.

**Comment by jaimeMF** [comment]
If you install [ffmpeg](https://ffmpeg.org/), youtube-dl will automatically download and merge the DASH video and audio formats. See the [FORMATS SELECTION docs](https://github.com/rg3/youtube-dl/blob/50b901306406d5c37f31880860e2a4dbb5e0a165/README.md#format-selection) for more info.
