### ISSUE TITLE
Here is a --verbose dump of the latest problem using the latest yt-dl.

### ISSUE THREAD

**Issue by bzimmerly** [rg3/youtube-dl#5760]
04:02:28 bzimmerly@cp8:~/Merge/PackingForATrip$ youtube-dl --verbose https://www.youtube.com/watch?v=JlY3YHCm6Us
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=JlY3YHCm6Us']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[youtube] JlY3YHCm6Us: Downloading webpage
[youtube] JlY3YHCm6Us: Extracting video information
[youtube] JlY3YHCm6Us: Downloading DASH manifest
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Invoking downloader on u'https://r13---sn-vgqs7n7z.googlevideo.com/videoplayback?ip=71.11.135.156&mime=video%2Fmp4&pl=19&source=youtube&dur=272.486&mv=m&ms=au&mm=31&ipbits=0&expire=1432134176&id=o-AJzoG1s3thno8IQKbGt0LmX7T9MGSOA1Uc4kpyn2ei_j&key=yt5&initcwndbps=2007500&upn=ihXh-Y_sw5E&nh=IgpwcjA0Lm9yZDEyKgkxMjcuMC4wLjE&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&mt=1432112518&sver=3&itag=22&fexp=910100%2C9406839%2C9408142%2C9408255%2C9408705%2C9408710%2C9408737%2C9408788%2C9409095%2C9409116%2C9412503%2C9413007%2C945137%2C948124%2C952612%2C952637%2C952642&signature=7F634B3AFDDDD6507153187591C849EA10E98243.40AAD5DDE590DA210A54A4A556B5C2368869500B&ratebypass=yes'
[download] Destination: Maintaining Minimalism-JlY3YHCm6Us.mp4
[download] 100% of 40.70MiB in 00:18
04:03:17 bzimmerly@cp8:~/Merge/PackingForATrip$

**Comment by jaimeMF** [comment]
Update avconv or use `-f best`(see the last two paragraphs in the [FORMAT SELECTION docs](https://github.com/rg3/youtube-dl/blob/50b901306406d5c37f31880860e2a4dbb5e0a165/README.md#format-selection)).

**Comment by bzimmerly** [comment]
Thank you!

Sincerely,
Bill
(Sent from my GMail account)
