### ISSUE TITLE
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Operation not permitted

### ISSUE THREAD

**Issue by core-code** [rg3/youtube-dl#5763]
youtube-dl 'https://www.youtube.com/watch?v=PwOjmVfvEqI'
[youtube] PwOjmVfvEqI: Downloading webpage
[youtube] PwOjmVfvEqI: Extracting video information
[youtube] PwOjmVfvEqI: Downloading DASH manifest
WARNING: You have requested formats uncompatible for merge. The formats will be merged into mkv
[download] Destination: Cradle Of Filth - Babalon AD (So Glad For The Madness) (OFFICIAL MUSIC VIDEO)-PwOjmVfvEqI.f243.webm
[download] 100% of 9.73MiB in 00:15
[download] Destination: Cradle Of Filth - Babalon AD (So Glad For The Madness) (OFFICIAL MUSIC VIDEO)-PwOjmVfvEqI.f141.m4a
[download] 100% of 10.82MiB in 00:21
[ffmpeg] Merging formats into "Cradle Of Filth - Babalon AD (So Glad For The Madness) (OFFICIAL MUSIC VIDEO)-PwOjmVfvEqI.mkv"
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Operation not permitted

**Comment by core-code** [comment]
same here:
'https://www.youtube.com/watch?v=SotCZ6zNkEQ'

youtube-dl --version
2015.04.26

**Comment by dstftw** [comment]
Update your ffmpeg/avconv.

**Comment by core-code** [comment]
sorry didn't realize the fresh install (brew) would pick up an age-old copy of avconv
