### ISSUE TITLE
error with youtube-dl

### ISSUE THREAD

**Issue by Jay-a-elliot** [rg3/youtube-dl#5765]
In the past I've used youtube-dl to download videos from liveleak and it usually went flawlessly, but as of last night I can't download videos from liveleak, when I do I get this error:
ERROR: unable to download video data: urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

**Comment by yan12125** [comment]
Which video are you downloading? Please post the [full verbose log with ```-v```](https://github.com/rg3/youtube-dl#bugs).

**Comment by Jay-a-elliot** [comment]
http://www.liveleak.com/view?i=480_1430856831

**Comment by yan12125** [comment]
Please include the ```-v``` flag. For example on my machine:
```
$ youtube-dl -v "http://www.liveleak.com/view?i=480_1430856831"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.liveleak.com/view?i=480_1430856831']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.15
[debug] Git HEAD: aa2013a
[debug] Python version 3.4.3 - Linux-4.0.1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[LiveLeak] 480_1430856831: Downloading webpage
[debug] Invoking downloader on 'https://cdn.liveleak.com/80281E/ll_a_s/2015/May/5/LiveLeak-dot-com-480_1430856831-trim16B10437-82F9-4C14-ACA3-6DC870ECDA5C_1430856841.mov?d5e8cc8eccfb6039332f41f6249e92b06c91b4db65f5e99818bdd4944f43d9d0e130&ec_rate=230'
[download] Destination: Shirtless kid picks a fight and gets COMPLETELY DESTROYED-480_1430856831.mov
[download] 100% of 2.13MiB in 00:08
```

**Comment by Jay-a-elliot** [comment]
alex@ayyy-desktop:~$ youtube-dl -v http://www.liveleak.com/view?i=480_1430856831
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.liveleak.com/view?i=480_1430856831']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.16.0-38-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[LiveLeak] 480_1430856831: Downloading webpage
ERROR: unable to download video data: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 953, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 929, in dl
    return fd.download(name, info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 290, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 52, in real_download
    data = compat_urllib_request.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 572, in https_open
    return self.do_open(HTTPSConnectionV3, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError:  urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

**Comment by yan12125** [comment]
Your copy of youtube-dl is too old (```youtube-dl version 2014.02.17```). Please update it to the latest version (2015.05.20). See [update instructions](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl) if you have any problem about updating.

**Comment by atseaconfused** [comment]
You may also try this method to download videos from liveleak, youtube, vimeo, facebook, youporn etc at http://www.allavsoft.com/how-to/liveleak-downloader.html
