### ISSUE TITLE
Can't download private video

### ISSUE THREAD

**Issue by bengan** [rg3/youtube-dl#577]
I would like to download this http://www.youtube.com/watch?v=oUNJZ1QObZM

youtube-dl> youtube-dl -U
Updating to latest version...
youtube-dl is up-to-date (2012.11.29)

youtube-dl> youtube-dl "http://www.youtube.com/watch?v=oUNJZ1QObZM"
[youtube] Setting language
[youtube] oUNJZ1QObZM: Downloading video webpage
[youtube] oUNJZ1QObZM: Downloading video info webpage
[youtube] oUNJZ1QObZM: Extracting video information
[youtube] RTMP download detected
[download] Destination: oUNJZ1QObZM.flv

ERROR: unable to download video

**Comment by ElijahLynn** [comment]
Latest error is:

> ERROR: rtmpe downloads are not supported, see https://github.com/rg3/youtube-dl/issues/343 for more information.

**Comment by dstftw** [comment]
Duplicate of #343.
