### ISSUE TITLE
Site request: www.nowtv.de, successor to rtl-now

### ISSUE THREAD

**Issue by hstracker90** [rg3/youtube-dl#5771]
RTL recently changed quite a few things on their website, leading to download problems on rtl-now and other sites (see issue #5681).
Links to video-streams on their site now direct to nowtv.de, which is not supported (yet).
So I request that the specialists look into this new site and see if it can be made available. Thank you!

Here is a sample output of the status quo:
PS C:\Windows\system32> youtube-dl --verbose "http://www.nowtv.de/rtl/lets-dance/folge-9-2015-05-15-20-15-00/player?return=/rtl/lets-dance"
[debug] System config: []
[debug] User config: [u'-o', u'C:/Users/hstracker/Downloads/%(title)s.%(ext)s']
[debug] Command-line args: [u'--verbose', u'http://www.nowtv.de/rtl/lets-dance/folge-9-2015-05-15-20-15-00/player?return=/rtl/lets-dance']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-68482-g92a596f, ffprobe N-68482-g92a596f, rtmpdump 2.4
[debug] Proxy map: {}
[generic] lets-dance: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lets-dance: Downloading webpage
[generic] lets-dance: Extracting information
ERROR: Unsupported URL: http://www.nowtv.de/rtl/lets-dance/folge-9-2015-05-15-20-15-00/player?return=/rtl/lets-dance
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 969, in _real_extract
  File "youtube_dl\utils.pyo", line 1558, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: mismatched tag: line 76, column 2
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 649, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\generic.pyo", line 1504, in _real_extract
UnsupportedError: Unsupported URL: http://www.nowtv.de/rtl/lets-dance/folge-9-2015-05-15-20-15-00/player?return=/rtl/lets-dance
PS C:\Windows\system32>

**Comment by JJ-Jana** [comment]
This is right, for about 2 days RTL has adapted her whole sides NOW. But the easy download has never functioned with me on RTLNow and the other sides NOW. Why I am not able to do the video material still for approx. 1 week any more streamen? This announcement "Cannot seek backward comes over and over again in linearly streams!" 

Sorry for my English is not the best one. Does it not lie in a missing Codec or why gehts any more? 

I quote the URL in " " as well as it was explained to me in debianforum. de and it also functioned the whole weeks before. Other sides function also even today. 

mplayer <(youtube-dl --verbose "http://www.nowtv.de/rtl/lets-dance/folge-9-2015-05-15-20-15-00/player?return=/rtl/lets-dance")
MPlayer2 2.0-728-g2c378c7-4+b1 (C) 2000-2012 MPlayer Team
Cannot open file '/home/jana/.mplayer/input.conf': No such file or directory
Failed to open /home/jana/.mplayer/input.conf.
Cannot open file '/etc/mplayer/input.conf': No such file or directory
Failed to open /etc/mplayer/input.conf.

Playing /dev/fd/63.
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.nowtv.de/rtl/lets-dance/folge-9-2015-05-15-20-15-00/player?return=/rtl/lets-dance']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.nowtv.de/rtl/lets-dance/folge-9-2015-05-15-20-15-00/player?return=/rtl/lets-dance
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 969, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 76, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1504, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.nowtv.de/rtl/lets-dance/folge-9-2015-05-15-20-15-00/player?return=/rtl/lets-dance

Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Failed to recognize file format.


Exiting... (End of file)

**Comment by dstftw** [comment]
nowtv.de will be supported in the next version.
