### ISSUE TITLE
Cannot download from youtibe, ffmpg problem?

### ISSUE THREAD

**Issue by jum** [rg3/youtube-dl#5776]
I am attempting to download from a NatGeo feature from youtube, Do I nned a special ffmmpeg feature enabled to make that work?

youtube-dl -v http://youtu.be/sSXSu0SE7gM
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://youtu.be/sSXSu0SE7gM']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.6 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: avconv N-32110-g8af9366, ffmpeg N-72267-gc886dd2, ffprobe N-72267-gc886dd2
[debug] Proxy map: {}
[youtube] sSXSu0SE7gM: Downloading webpage
[youtube] sSXSu0SE7gM: Extracting video information
[youtube] sSXSu0SE7gM: Downloading DASH manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r2---sn-cxap1xuxaxhxqp5-c1xe.googlevideo.com/videoplayback?id=b125d2bb4484ee03&itag=243&source=youtube&requiressl=yes&ms=au&mv=m&mm=31&pl=20&ratebypass=yes&mime=video/webm&gir=yes&clen=99510195&lmt=1406701115171461&dur=2715.000&sver=3&fexp=9406691,9406840,9407942,9408142,9408213,9408710,9409171,9412527,9414847,945137,948124,952612,952642&mt=1432244405&key=dg_yt0&signature=0EA2A60C0A0C745A455B7E72CD0DAC0F5EBD4FF6.675BA4854025983C02DC831141292CD1326D8FEA&upn=zg0Z5KfjjpY&ip=200.32.215.138&ipbits=0&expire=1432266068&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,mm,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] The Alaska moment ( Nat Geo Wild )-sSXSu0SE7gM.f243.webm has already been downloaded
[download] 100% of 94.90MiB
[debug] Invoking downloader on 'https://r2---sn-cxap1xuxaxhxqp5-c1xe.googlevideo.com/videoplayback?id=b125d2bb4484ee03&itag=141&source=youtube&requiressl=yes&ms=au&mv=m&mm=31&pl=20&ratebypass=yes&mime=audio/mp4&gir=yes&clen=86563795&lmt=1418539173206018&dur=2715.109&sver=3&fexp=9406691,9406840,9407942,9408142,9408213,9408710,9409171,9412527,9414847,945137,948124,952612,952642&mt=1432244405&key=dg_yt0&signature=0F0CFEE9E2B3E1D02AC4D696B1A4EC50474A66D9.3AB94F83F599716CEA03539EB58AFCE3D9A77B34&upn=zg0Z5KfjjpY&ip=200.32.215.138&ipbits=0&expire=1432266068&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,mm,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] The Alaska moment ( Nat Geo Wild )-sSXSu0SE7gM.f141.m4a has already been downloaded
[download] 100% of 82.55MiB
[ffmpeg] Merging formats into "The Alaska moment ( Nat Geo Wild )-sSXSu0SE7gM.mkv"
[debug] ffmpeg command line: avconv -y -i 'The Alaska moment ( Nat Geo Wild )-sSXSu0SE7gM.f243.webm' -i 'The Alaska moment ( Nat Geo Wild )-sSXSu0SE7gM.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'The Alaska moment ( Nat Geo Wild )-sSXSu0SE7gM.temp.mkv'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?)
Traceback (most recent call last):
  File "/Users/jum/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1531, in post_process
    files_to_delete, info = pp.run(info)
  File "/Users/jum/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 590, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/Users/jum/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 148, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

**Comment by yan12125** [comment]
You have both ffmpeg and avconv installed. In this case, avconv is used to merge the video. Could you try again with ```--prefer-ffmpeg```?

**Comment by jum** [comment]
Thanks! This helped, it works!
