### ISSUE TITLE
warning: unable to extract duration on NBA.com

### ISSUE THREAD

**Issue by ckmox** [rg3/youtube-dl#5777]
first time user of this software and it instruct me to report this warning, the video downloaded and plays fine though, thanks for this great app 

![untitled](https://cloud.githubusercontent.com/assets/12554635/7764021/b47c8a5e-007c-11e5-889e-3a1f2732e042.png)

**Comment by yan12125** [comment]
Thanks for the report. The issue will be fixed in the next version.

By the way, please paste at least the URL besides the screenshot. It takes a little effort to re-enter the URL :D

**Comment by ckmox** [comment]
ah sorry about that, im a noob and its showing, in case you still need the link here it is http://watch.nba.com/nba/video/channels/playoffs/2015/05/20/0041400301-cle-atl-recap.nba
