### ISSUE TITLE
Why not licensing youtube-dl to a free software license

### ISSUE THREAD

**Issue by filipe-marques** [rg3/youtube-dl#5779]
Why not licensing youtube-dl to a free software license like the GNU GPL v.3 or later.
I'm afraid that the Google, YouTube, SoundCloud, and others big corporations shutdown this project and all the associated forks with court case with that order.
With the GNU GPL v.3 the project is protect by the four freedoms of free software.
If I was developing or owning this project I for sure license under the GNU GPL v.3 license or later.
This project is very important to me because I'm free software fan and user and I do not want the project to close, I want that the project to be protected against big corporations of proprietary software!

**Comment by jaimeMF** [comment]
youtube-dl is realeased into the public domain (see the [LICENSE](https://github.com/rg3/youtube-dl/blob/master/LICENSE), **which is a free license** (and please don't start a discussion about which license is truly free). If you don't trust me, read the GNU webpage: https://www.gnu.org/licenses/license-list.html#PublicDomain

> I'm afraid that the Google, YouTube, SoundCloud, and others big corporations shutdown this project and all the associated forks with court case with that order.
With the GNU GPL v.3 the project is protect by the four freedoms of free software.

I don't really know how using a different license would give more protection in that hypothetical situation, but I'm not a lawyer.

**Comment by filipe-marques** [comment]
Public Domain is like give up of duties and rights of a project, is dangerous.
Legally, the free software licenses are the best protect, because in the past I had some problems with license and copyright and when software lawyers saw that my project was licensed under GNU GPL v.3 they give up of a court case.

**Comment by jaimeMF** [comment]
Again: **public domain is free software** (see the GNU page about free licenes).

If you really want to propose a switch to GPL (note that not all project use v.3, some have decided to stay with v.2), open a new issue and give a detailed explanation of the benefits and problems that would solve, we can discuss it and we may choose to switch (I warn you: I would probably vote against it, but others may like it).
