### ISSUE TITLE
GDCVault multi audio not recognized

### ISSUE THREAD

**Issue by jengelh** [rg3/youtube-dl#5784]
youtube-dl does not recognize the (separate) audio tracks on this particular video:
```
$ youtube-dl -F http://www.gdcvault.com/play/1014631/Classic-Game-Postmortem-PAC
[GDCVault] Classic-Game-Postmortem-PAC: Downloading webpage
[GDCVault] Classic-Game-Postmortem-PAC: Downloading XML
[info] Available formats for 1014631:
format code  extension  resolution note
slides       flv        unknown    slide deck video 
speaker      flv        unknown    speaker video  (best)
```
Only the two streams are shown. However, if you visit the URL with a web browser (and let Flash run), one can choose between Japanese and English audio.

**Comment by jaimeMF** [comment]
Fixed by @remitamine in #6412.

In the next version, you'll be able to use `-f en` to download the english audio. If you have ffmpeg installed you can use `-f 'best+en'` to get a file with the video and the english audio.
