### ISSUE TITLE
Unable to download a youtube user's complete video collection

### ISSUE THREAD

**Issue by shivams** [rg3/youtube-dl#5785]
Earlier this was possible using this command: 

    youtube-dl -ciw ytuser:username

But now, it seems youtube api has changed and when we issue this command to download a user's complete video collection, it downloads only one youtube video and that too is some official youtube video saying that the device is not supported. 

Kindly update `youtube-dl` to make it compatible with the current youtube site. All other things work fine -- downloading single videos, downloading playlist etc.

**Comment by yan12125** [comment]
This is already fixed. Did you update to the latest version, 2015.05.20? Check it by:
```
$ youtube-dl --version      
2015.05.20
```
Also, check the [update instructions](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl).

**Comment by shivams** [comment]
Thanks. Updating to the latest version fixed the problem.
