### ISSUE TITLE
Conflict between --dump-pages and --dump-json

### ISSUE THREAD

**Issue by Alavar** [rg3/youtube-dl#5787]
I'm trying to both dump the page source and the JSON in one single command.
Example: `youtube-dl --dump-pages --dump-json URL`

I am however only getting the output of `--dump-json`, but not the output of `--dump-pages`.

There are currently two solutions that I am able to think of:

1) Run two commands; one getting the result of `--dump-json` and the other `--dump-pages`.  The large downside to this solution is that all requests are going to be doubled as the sources would have to be grabbed twice.

2) Using `--write-pages` works perfectly together with `--dump-json`, but the downside to this option is that the pages are saved to a folder which requires a script that goes through the outputted files and opens them.  The other part which makes things really difficult is the ability to distinguish the order of the pages with `--write-pages` as some sites (YouTube for example) require additional requests (manifests).

Since the files all have the same creation time, it's hard to know which file was requested first which would require a regex making the issue even more complicated.

**Comment by jaimeMF** [comment]
`--dump-pages` is only intended to debug problems, we won't make it work with `--dump-json`. So you have to use `--write-pages`.

**Comment by Alavar** [comment]
>--dump-pages is only intended to debug problems, we won't make it work with --dump-json. So you have to use --write-pages.

How will I be able to know which file the first request is?

**Comment by jaimeMF** [comment]
You can't, but since I gues you are not interested on the DASH manifest you can just look for the `*watch?v=*` pages.

**Comment by Alavar** [comment]
What about other sites?

**Comment by jaimeMF** [comment]
You'll have to analyse case by case, you can't just use the same approach for all sites because the downloaded pages vary a lot (they can be: html, json, xml, javascript or some custom text format). Before you start doing it, you should really consider if you need to do it and if some of the info you need could be directly extracted by youtube-dl.

**Comment by Alavar** [comment]
If the JSON dump provided a simple value which showed if the signature was encrypted from the start then the problem would be solved.  Something as simple as `"encryptedSignature": 1` would do the trick.

The reason I want this is because I want to log the amount of videos that have encrypted signature and in some cases also restrict them from being downloaded.

**Comment by jaimeMF** [comment]
> If the JSON dump provided a simple value which showed if the signature was encrypted from the start then the problem would be solved. Something as simple as "encryptedSignature": 1 would do the trick.

Open a new issue, as I said in https://github.com/rg3/youtube-dl/issues/5781#issuecomment-104871159

**Comment by Alavar** [comment]
I didn't see your reply.
I will create a new issue, thanks.
