### ISSUE TITLE
Spiegel.tv Could not connect to RTMP server

### ISSUE THREAD

**Issue by 04a391c1b7aa** [rg3/youtube-dl#5788]
When trying to download any video from spiegel.tv, it is not working anymore.

I can take any video, but as an example: http://www.spiegel.tv/filme/dbate-videotagebuch-kiffen-mein-rausch/
```
[Spiegeltv] dbate-videotagebuch-kiffen-mein-rausch: Downloading webpage
[Spiegeltv] dbate-videotagebuch-kiffen-mein-rausch: Downloading version information
[Spiegeltv] dbate-videotagebuch-kiffen-mein-rausch: Downloading object information
[Spiegeltv] dbate-videotagebuch-kiffen-mein-rausch: Downloading media information
[Spiegeltv] dbate-videotagebuch-kiffen-mein-rausch: Downloading server information
[download] Destination: Mein Rausch-dbate-videotagebuch-kiffen-mein-rausch.m4v
ERROR: [rtmpdump] Could not connect to RTMP server.
```

A few days ago it was still working.

I tried it on two machines, both archlinux. Same result.

**Comment by claell** [comment]
Same here with ```youtube-dl http://www.spiegel.tv/filme/alleskino-metalhead```

**Comment by yan12125** [comment]
Thanks to @brickleroux (see https://github.com/rg3/youtube-dl/issues/5843#issuecomment-106963621), this problem will be fixed in the next version.

**Comment by claell** [comment]
Thanks
