### ISSUE TITLE
Problem with DRTV available formats

### ISSUE THREAD

**Issue by mistnim** [rg3/youtube-dl#5792]
Formats have the same code and there is no resolution info available.

	youtube-dl -F -v https://www.dr.dk/tv/se/gintberg-pa-kanten-2014/gintberg-pa-kanten-christiansborg-3-7
	[debug] System config: [u'--prefer-free-formats']
	[debug] User config: []
	[debug] Command-line args: [u'-F', u'-v', u'https://www.dr.dk/tv/se/gintberg-pa-kanten-2014/gintberg-pa-kanten-christiansborg-3-7']
	[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
	[debug] youtube-dl version 2015.04.28
	[debug] Python version 2.7.8 - Linux-3.19.7-200.fc21.i686-i686-with-fedora-21-Twenty_One
	[debug] exe versions: ffmpeg 2.4.9, ffprobe 2.4.9, rtmpdump 2.4
	[debug] Proxy map: {}
	[DRTV] gintberg-pa-kanten-christiansborg-3-7: Downloading webpage
	[DRTV] gintberg-pa-kanten-christiansborg-3-7: Downloading video JSON
	[info] Available formats for gintberg-pa-kanten-christiansborg-3-7:
	format code  extension  resolution note
	Download     mp4        unknown    
	Download     mp4        unknown    
	Download     mp4        unknown    
	HLS          mp4        unknown    
	HDS          mp4        unknown    (best)

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
