### ISSUE TITLE
5-tv.ru support

### ISSUE THREAD

**Issue by Nikoli** [rg3/youtube-dl#5794]
Please add support for 5-tv.ru, videos are available in this pages:
http://5-tv.ru/news/
http://5-tv.ru/video/
http://5-tv.ru/programs/

Examples of urls:
http://5-tv.ru/news/96814/
http://5-tv.ru/news/96781/
http://5-tv.ru/news/96738/
http://5-tv.ru/video/1021729/

**Comment by dstftw** [comment]
Пятый канал (5-tv.ru) will be supported in the next version. Thanks for the report.
