### ISSUE TITLE
tvc.ru support

### ISSUE THREAD

**Issue by Nikoli** [rg3/youtube-dl#5795]
Please add support for tvc.ru, videos are available in this pages:
http://www.tvc.ru/video/index
http://www.tvc.ru/news

Examples of urls:
http://www.tvc.ru/channel/brand/id/29/show/episodes/episode_id/39702/
http://www.tvc.ru/news/show/id/68848

**Comment by dstftw** [comment]
ТВ Центр (tvc.ru) will be supported in the next version. Thanks for the report.
