### ISSUE TITLE
Outputted URLs only contain locations of the manifest files

### ISSUE THREAD

**Issue by Alavar** [rg3/youtube-dl#5799]
I am using `-g` to get the URL of the video files.
Some websites (SVT Play, TV3 Play, TV5 Play, TV6 Play, and many more) all output the location of the manifest files instead of the video files.

I've tried opening one of the manifest files (roughly 30 KB large) and it only contains encrypted locations of the video files.  When I however remove `-g` youtube-dl is able to perfectly download and save the FLV to my PC.

Would it be possible to have youtube-dl paste the URL of the FLV instead of the manifest?

**Comment by jaimeMF** [comment]
No, unfortunately they only provide the video via Adobe HDS or HLS, which split the video in multiple fragments so we can't provide a single url to the file. If you use `-f mp4` the HLS manifest url can be downloaded with ffmpeg (and some players like mpv and probably vlc can play them).

**Comment by Alavar** [comment]
That makes sense, thanks for your answer.

Off-topic question: is it possible to set the location of the saved files?

**Comment by jaimeMF** [comment]
> Off-topic question: is it possible to set the location of the saved files?

Have you look into the `--output` option?

**Comment by Alavar** [comment]
I had not.
I'll look into that, thanks for the help!
