### ISSUE TITLE
for windows version, how should I run it? can't run it directly just by double clicking it?

### ISSUE THREAD

**Issue by lweo** [rg3/youtube-dl#5802]
when I double click it,there appears a prompt then disappear quickly, I  try my endeavor to screen capture it , it indicates that "Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: You must provide at least one UR
Type youtube-dl --help to see a list of all options.
"

is it my computer's problem? or  I must run CMD ,then in CMD prompt ,type the path of youtube-dl ,then run it?

but I  read the INSTALLATION:

Windows users can download a .exe file and place it in their home directory or any other location on their PATH.

I dont understand it quitely...

**Comment by dstftw** [comment]
>I must run CMD ,then in CMD prompt ,type the path of youtube-dl ,then run it?

Yes, youtube-dl is [CLI](http://en.wikipedia.org/wiki/Command-line_interface) software.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30871
