### ISSUE TITLE
TenPlay - Worst source is detected as "Best"

### ISSUE THREAD

**Issue by V0rTeXbg** [rg3/youtube-dl#5806]
youtube-dl http://tenplay.com.au/channel-ten/modern-family/seaso
n-6/episode-24 -F
[TenPlay] http://tenplay.com.au/channel-ten/modern-family/season-6/episode-24: D
ownloading webpage
[TenPlay] Modern Family - S6 Ep. 24: Downloading JSON metadata
[info] Available formats for 4250483758001:
format code    extension  resolution note
rtmp_mp4_h264  flv        640x360     682k , mp4 container, h264, 103.18MiB
rtmp_mp4_h264  flv        1024x576   1166k , mp4 container, h264, 176.19MiB
rtmp_mp4_h264  flv        320x180     387k , mp4 container, h264, 58.82MiB (best)

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
