### ISSUE TITLE
You-Tube truncated url -RGnfsRy9aY fails, but full url works correctly.

### ISSUE THREAD

**Issue by jhb50** [rg3/youtube-dl#5808]
As per below:

This works:
C:\Users\John>"C:\Program Files\Serviio\lib\youtube-dl.exe " https://www.youtube
.com/watch?v=-RGnfsRy9aY
[youtube] -RGnfsRy9aY: Downloading webpage
[youtube] -RGnfsRy9aY: Extracting video information
[youtube] -RGnfsRy9aY: Downloading DASH manifest
[download] Destination: SHANIA TWAIN - LIVE IN CONCERT (1999)--RGnfsRy9aY.f134.m
p4
[download] 100% of 309.71MiB in 10:15
[download] Destination: SHANIA TWAIN - LIVE IN CONCERT (1999)--RGnfsRy9aY.f141.m
4a
[download] 100% of 161.10MiB in 04:23
[ffmpeg] Merging formats into "SHANIA TWAIN - LIVE IN CONCERT (1999)--RGnfsRy9aY
.mp4"
Deleting original file SHANIA TWAIN - LIVE IN CONCERT (1999)--RGnfsRy9aY.f134.mp
4 (pass -k to keep)
Deleting original file SHANIA TWAIN - LIVE IN CONCERT (1999)--RGnfsRy9aY.f141.m4
a (pass -k to keep)

This does not:
C:\Users\John>"C:\Program Files\Serviio\lib\youtube-dl.exe" -v -RGnfsRy9aY
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-RGnfsRy9aY']
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: invalid retry count specified

The problem is that when this is encountered in:
"C:\Program Files\Serviio\lib\youtube-dl.exe " --max-downloads 50 -j 9byz0UEpS3g cgFLdewM1ys a-Lp2uC_1lg 8N2k-gv6xNE ZJL4UGSbeFg IpT-FW_G8-A DfhMgy_HKWE BzD0nd7tzNI KNZH-emehxA DDkCe2cUHAA Z3Pb3EJY5Qg iEe3hBXZEyI 345LENcTg2E 49rI7d28OxE ErREUQRH2ts QF6WtgoilFw Y6jkgbVqwj4 peBBswUTIr8 mqFLXayD6e8 4JQoc867lwI rKf_5vQODbU -RGnfsRy9aY YHBOQXy9dRo LAyQGZJ7cZ0 tLtbhLRYXww L6WWMNZ9Mzw ioAO9UCIYzY lk7pNRpe1_8 VfHqJqhwAwU 5fnZmdd35Uk JyZdrkrxD4o L58a3QUkhJw S88Wit5bNdY bstErxsTGIU 681Y-UQ0LWI N6wBxQVBozI kiFpBF58u0s bqa38zGZt6s 5gVeOg3o9ZM DZWYn7VCseY jNa-UrL8XZs rntn8wXTLqs xppx9uMyD7s u8xYh3oanNw kJFpIpx4svk KIDOv-u96Hg sQg9LuI5vo4 Cytj0nrLaCs SqOITRgGIQE 79sBM96NZFg

then the whole command fails rather than just the defective one.

**Comment by pulpe** [comment]
Solution - https://github.com/rg3/youtube-dl#how-do-i-download-a-video-starting-with-a---
