### ISSUE TITLE
it doesn't be downloaded :(

### ISSUE THREAD

**Issue by something0404** [rg3/youtube-dl#5809]
Microsoft Windows [Version 6.2.9200]
(c) 2012 Microsoft Corporation. All rights reserved.

C:\Users\user>youtube-dl http://tvcast.naver.com/v/395837
[Naver] 395837: Downloading webpage
[Naver] 395837: Downloading video info
[Naver] 395837: Downloading video formats info
ERROR: unable to download video data: <urlopen error [Errno 11001] getaddrinfo f
ailed>

what's it?

**Comment by yan12125** [comment]
This video is georestricted. Could you add an option:
```
youtube-dl --write-pageas http://tvcast.naver.com/v/395837
```
And upload/paste all *.dump files?

**Comment by yan12125** [comment]
I managed to fix the problem with a Korea proxy. It should be fixed in the next version. If you still encounter errors, feel free to open a new issue.
