### ISSUE TITLE
false positive - issue with unicode (non-english) title

### ISSUE THREAD

**Issue by shula** [rg3/youtube-dl#5820]
I got this warning "unable to extract title".
But the title was extracted very well, and youtube-dl named the file with the correct title, in Hebrew.

So there's no issue, probably just a wrong warning.

Here's the verbose:

c:\> youtube-dl.py --verbose https://www.facebook.com/GadiWilcherski/videos/1103294873019856
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/GadiWilcherski/videos/1103294873019856']
[debug] Encodings: locale cp1255, fs mbcs, out cp862, pref cp1255
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71209-gd759844
[debug] Proxy map: {}
[facebook] 1103294873019856: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Invoking downloader on u'https://video-cdg2-1.xx.fbcdn.net/hvideo-xfa1/v/t43.1792-2/10958450_1103316696351007_1513571274_n.mp4?efg=eyJxZSI6ImZiY2RuX3ZpZGVvX3JhdGVsaW1pdF9yb2xsb3V0Mix2X3JvbGxvdXQiLCJybHIiOjE1MDAsInJsYSI6MTYzNn0%3D&rl=1500&vabr=331&oh=71b68571a70783e974950c9d5e9341a0&oe=5563CFB2'
[download] קטע סטנדאפ חדש של גדי!על דלקות, מסיבות טבע ועל המפגש הבלתי אפשרי עם העולם הס...-1103294873019856.mp4 has already been downloaded
[download] 100% of 10.42MiB

**Comment by yan12125** [comment]
Thanks for the report. Warnings will be correctly issued in the next version.
