### ISSUE TITLE
Unable to download cinemassacre.com's videos again.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#5821]
This is a new video from late last night:

$ youtube-dl --verbose http://cinemassacre.com/2015/05/25/mario-kart-64-nintendo-64-james-mike-mondays/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://cinemassacre.com/2015/05/25/mario-kart-64-nintendo-64-james-mike-mondays/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.8
[debug] exe versions: avconv 1.2.12, avprobe 1.2.12, ffmpeg 1.2.12, ffprobe 1.2.12, rtmpdump 2.4
[debug] Proxy map: {}
[Cinemassacre] mario-kart-64-nintendo-64-james-mike-mondays: Downloading webpage
ERROR: Unable to find player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/cinemassacre.py", line 82, in _real_extract
    raise ExtractorError('Unable to find player data')
ExtractorError: Unable to find player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thank you in advance. :)

**Comment by yan12125** [comment]
Thanks for the report. This video will be supported in the next version. Note due to a known bug (#5821), you might get '403 Forbidden' from time to time. Just try again.

**Comment by antdude** [comment]
Thanks Yan12125. :)
