### ISSUE TITLE
Long vgtv video

### ISSUE THREAD

**Issue by SkuliJohannsson** [rg3/youtube-dl#5835]
I'm trying to download a long video from vgtv.

youtube-dl 'http://www.vgtv.no/#!/video/64502/verdens-lengste-intervju-se-hele' --verbose

Here is the output:

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.vgtv.no/#!/video/64502/verdens-lengste-intervju-se-hele', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.9 - Linux-3.19.0-18-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.5.7-0ubuntu0.15.04.1, ffprobe 2.5.7-0ubuntu0.15.04.1
[debug] Proxy map: {}
[VGTV] 64502: Downloading media JSON
[VGTV] 64502: Downloading m3u8 information
[VGTV] 64502: Downloading f4m manifest
[debug] Invoking downloader on u'http://vgtvlive-f.akamaihd.net/z/20130514x64502_01@28597/manifest.f4m?hdcore=3.2.0&plugin=aasp-3.2.0.77.18'
[download] Downloading f4m manifest
[download] Destination: Verdens lengste intervju - se hele-64502.flv
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1419, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1361, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/f4m.py", line 396, in real_download
    success = http_dl.download(frag_filename, {'url': url})
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1712, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found


```

Any suggestions?

**Comment by dstftw** [comment]
Will be fixed in the next version.
For now you can download it explicitly specifying hls as desired format:
```
youtube-dl -f hls-1078 'http://www.vgtv.no/#!/video/64502/verdens-lengste-intervju-se-hele'
```

**Comment by stianiquniez** [comment]
Hi, I have the latest version 2015.12.10 and when trying to download this video, the download starts, and I get a video that is 49:28 long, and after this it stops. The video is over 30:00:00 long (30 hours)
Is it possible that youtube-dl don`t handle this long videos? 
Here is the error I get after a while.

Input #0, hls,applehttp, from 'http://vgtvlive-f.akamaihd.net/i/20130514x64502_01@28597/index_1_av-b.m3u8?sd=9&rebase=on':
  Duration: 00:54:16.65, start: 73024.858889, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv), 640x360 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 129 kb/s
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
[mp4 @ 0x7ff0fa804200] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x7ff0fa804200] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to 'file:Verdens lengste intervju - se hele 2015-12-11 12_19-64502.mp4.part':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 640x360 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 129 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[http @ 0x7ff0fa4200c0] HTTP error 404 Not Found00:38:12.26 bitrate=1071.2kbits/s    
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4200c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found00:49:25.57 bitrate=1065.9kbits/s    
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa4252c0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
[http @ 0x7ff0fa510fe0] HTTP error 404 Not Found
[hls,applehttp @ 0x7ff0fa802000] Failed to open segment of playlist 0
frame=73259 fps=185 q=-1.0 Lsize=  388547kB time=00:49:27.91 bitrate=1072.5kbits/s    
video:340334kB audio:45852kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.611311%
[ffmpeg] 397872187 bytes
[download] 100% of 379.44MiB

**Comment by yan12125** [comment]
@stianiquniez Please open a new issue with [full verbose log](https://github.com/rg3/youtube-dl#bugs).
