### ISSUE TITLE
Problem downloading Senate videos from C-SPAN

### ISSUE THREAD

**Issue by lfl2** [rg3/youtube-dl#5836]
Different C-SPAN videos, sometimes use different methods to play video. Some of them use F4F Adobe format (https://github.com/rg3/youtube-dl/issues/4405), and some of them are not downloadable with current C-SPAN downloader.

For example see this one, that seems to be from Senate video:

http://www.c-span.org/video/?96791-1

It is not detected as Senate video (as in https://github.com/rg3/youtube-dl/issues/5302), at it is does not download the video.

**Comment by yan12125** [comment]
Thanks for the report. This will be fixed in the next version.
