### ISSUE TITLE
Defaulting to HTTPS on YouTube

### ISSUE THREAD

**Issue by mmcco** [rg3/youtube-dl#5837]
This is a minor issue, but when you supply a YouTube link without an `http://` or `https://` prefix, the first output line is:

    WARNING: The url doesn't specify the protocol, trying with http

Because HTTPS is default and expected on YouTube these days, it would be nice if youtube-dl defaulted to it.

It seems that a condition or a call to a helper function [here](https://github.com/rg3/youtube-dl/blob/25c3a7348f7971c0af32dcea2d7fd57bd5c63f05/youtube_dl/extractor/generic.py#L868) is all we would need.

Thanks for your time.

**Comment by dstftw** [comment]
youtube-dl supports [not only YouTube](https://rg3.github.io/youtube-dl/supportedsites.html), some of which are only accessible by http.

**Comment by mmcco** [comment]
I'm aware of that. It would be extremely simple to check the URL against a list of domains know to support HTTPs, though. That's what I was suggesting.

**Comment by jaimeMF** [comment]
Note that in the case of YouTube videos the extractor [matches http:// urls](https://github.com/rg3/youtube-dl/blob/04b3b3df05a26a361441754afeb7ff24d0c1f559/youtube_dl/extractor/youtube.py#L195) and it [will do all the requests with htttps://](https://github.com/rg3/youtube-dl/blob/04b3b3df05a26a361441754afeb7ff24d0c1f559/youtube_dl/extractor/youtube.py#L833-L841), so it won't use any insecure connection.
