### ISSUE TITLE
Use &persist_hl=1&hl=en instead of [Setting language] step

### ISSUE THREAD

**Issue by FiloSottile** [rg3/youtube-dl#584]

**Comment by jaimeMF** [comment]
For a few versions, we [just set a cookie](https://github.com/rg3/youtube-dl/blob/b95aab8482881e8b1f7fba856da816a2dbc50d0f/youtube_dl/extractor/youtube.py#L47) before downloading any webpage. Therefore I'm closing the issue. If it doesn't work for some case, we'll reopen the issue.
