### ISSUE TITLE
spiegel.tv - no download possible / broken

### ISSUE THREAD

**Issue by speters** [rg3/youtube-dl#5843]
youtube-dl (tested 2015.05.20 and git commit d6aa68ce75ef4f4d27fbf7103edfda1f92ba70b2 versions) is no more able to download video from spiegel.tv:
```
 ./youtube-dl http://www.spiegel.tv/filme/alleskino-deutschboden/
[Spiegeltv] alleskino-deutschboden: Downloading webpage
[Spiegeltv] alleskino-deutschboden: Downloading version information
[Spiegeltv] alleskino-deutschboden: Downloading object information
[Spiegeltv] alleskino-deutschboden: Downloading media information
[Spiegeltv] alleskino-deutschboden: Downloading server information
[download] Destination: Deutschboden-alleskino-deutschboden.m4v
[rtmpdump] 0 bytes


ERROR: rtmpdump exited with code 1
soenke@S350E7C:~/dev/youtube-dl$ ./youtube-dl http://www.spiegel.tv/filme/alleskino-deutschboden/ -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.spiegel.tv/filme/alleskino-deutschboden/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.29
[debug] Python version 2.7.6 - Linux-3.13.0-53-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[Spiegeltv] alleskino-deutschboden: Downloading webpage
[Spiegeltv] alleskino-deutschboden: Downloading version information
[Spiegeltv] alleskino-deutschboden: Downloading object information
[Spiegeltv] alleskino-deutschboden: Downloading media information
[Spiegeltv] alleskino-deutschboden: Downloading server information
[debug] Invoking downloader on u'rtmpe://fms.edge.newmedia.nacamar.net/schnee_vod/flashmedia/mp4:13074f4ebd154fb79681557d288b78c7_spiegeltv_0500_16x9.m4v'
[download] Destination: Deutschboden-alleskino-deutschboden.m4v
[debug] rtmpdump command line: rtmpdump --verbose -r rtmpe://fms.edge.newmedia.nacamar.net/schnee_vod/flashmedia/mp4:13074f4ebd154fb79681557d288b78c7_spiegeltv_0500_16x9.m4v -o Deutschboden-alleskino-deutschboden.m4v.part --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : fms.edge.newmedia.nacamar.net
[rtmpdump] DEBUG: Parsed app     : schnee_vod/flashmedia
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : fms.edge.newmedia.nacamar.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:13074f4ebd154fb79681557d288b78c7_spiegeltv_0500_16x9.m4v
[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.edge.newmedia.nacamar.net:1935/schnee_vod/flashmedia
[rtmpdump] DEBUG: app      : schnee_vod/flashmedia
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : fms.edge.newmedia.nacamar.net
[rtmpdump] DEBUG: Parsed app     : schnee_vod/flashmedia
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : fms.edge.newmedia.nacamar.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:13074f4ebd154fb79681557d288b78c7_spiegeltv_0500_16x9.m4v
[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.edge.newmedia.nacamar.net:1935/schnee_vod/flashmedia
[rtmpdump] DEBUG: app      : schnee_vod/flashmedia
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.


ERROR: rtmpdump exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "./youtube-dl/youtube_dl/__init__.py", line 405, in main
    _real_main(argv)
  File "./youtube-dl/youtube_dl/__init__.py", line 395, in _real_main
    retcode = ydl.download(all_urls)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1486, in download
    res = self.extract_info(url)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 706, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1157, in process_video_result
    self.process_info(new_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1419, in process_info
    success = dl(filename, info_dict)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1361, in dl
    return fd.download(name, info)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "./youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 527, in report_error
    self.trouble(error_message, tb)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 489, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by brickleroux** [comment]
Yes, it's broken:

The server (host) has changed from `rtmpe://fms.edge.newmedia.nacamar.net` to `rtmpe://mf.schneevonmorgen.c.nmdn.net`.

And it's necessary to disable the BUFX speedup hack of rtmpdump by adding the option `--realtime` or `--live` to the commandline:

`rtmpdump --verbose -r "rtmpe://mf.schneevonmorgen.c.nmdn.net/schnee_vod/flashmedia/mp4:13074f4ebd154fb79681557d288b78c7_spiegeltv_0500_16x9.m4v" --realtime -o "Deutschboden.flv"`

or

`rtmpdump --verbose -r "rtmpe://mf.schneevonmorgen.c.nmdn.net/schnee_vod/flashmedia/mp4:13074f4ebd154fb79681557d288b78c7_spiegeltv_0500_16x9.m4v" --live -o "Deutschboden.flv"`

**Comment by yan12125** [comment]
Much thanks @brickleroux! I've adapted your idea in fafec39. From my country, without ```--live``` or ```--realtime``` works fine, but I still add the option.

**Comment by pieska** [comment]
another video wich can't be downloaded from spiegel.tv:

$ ./youtube-dl "http://www.spiegel.tv/#/filme/bbc-paradox-1-erkenntnis/" -v
[debug] System config: []
[debug] User config: [u'-cio', u'%(playlist_index)s-%(title)s.%(ext)s']
[debug] Command-line args: [u'http://www.spiegel.tv/#/filme/bbc-paradox-1-erkenntnis/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.6.6 - Linux-2.6.32-504.16.2.el6.x86_64-x86_64-with-redhat-6.6-Santiago
[debug] exe versions: ffmpeg 0.10.15, ffprobe 0.10.15, rtmpdump 2.4
[debug] Proxy map: {}
[Spiegeltv] bbc-paradox-1-erkenntnis: Downloading webpage
[Spiegeltv] bbc-paradox-1-erkenntnis: Downloading version information
[Spiegeltv] bbc-paradox-1-erkenntnis: Downloading object information
[Spiegeltv] bbc-paradox-1-erkenntnis: Downloading media information
[Spiegeltv] bbc-paradox-1-erkenntnis: Downloading server information
[debug] Invoking downloader on u'rtmpe://sptvfs.fplive.net/sptv/mp4:d195b4180fe041739c845fa6c36dae54_spiegeltv_0500_16x9.m4v'
[download] Destination: NA-Paradox Episode 1.m4v
[debug] rtmpdump command line: rtmpdump --verbose -r rtmpe://sptvfs.fplive.net/sptv/mp4:d195b4180fe041739c845fa6c36dae54_spiegeltv_0500_16x9.m4v -o 'NA-Paradox Episode 1.m4v.part' --live
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : sptvfs.fplive.net
[rtmpdump] DEBUG: Parsed app     : sptv
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : sptvfs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:d195b4180fe041739c845fa6c36dae54_spiegeltv_0500_16x9.m4v
[rtmpdump] DEBUG: tcUrl    : rtmpe://sptvfs.fplive.net:1935/sptv
[rtmpdump] DEBUG: app      : sptv
[rtmpdump] DEBUG: live     : yes
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 06
[rtmpdump] DEBUG: HandShake: DH pubkey position: 472
[rtmpdump] DEBUG: HandShake: Client digest offset: 1383
[rtmpdump] DEBUG: HandShake: Initial client digest: 
[rtmpdump] DEBUG: 21 b1 6a 3b c2 2b 7c 62 59 ac 11 f1 e1 ce 30 da
[rtmpdump] DEBUG: 70 92 36 78 ee 9c 87 c6 ed ee 88 2a a8 c3 44 66
[rtmpdump] DEBUG: HandShake: Type Answer   : 09
[rtmpdump] WARNING: HandShake: Type mismatch: client sent 6, server answered 9
[rtmpdump] DEBUG: HandShake: Server Uptime : 634683845
[rtmpdump] DEBUG: HandShake: FMS Version   : 4.5.3.1
[rtmpdump] DEBUG: HandShake: Server DH public key offset: 98
[rtmpdump] DEBUG: HandShake: Secret key: 
[rtmpdump] DEBUG: 94 9d bc 87 2b a7 6f 81 d0 43 ee 5b 68 5c a8 12
[rtmpdump] DEBUG: f1 26 65 35 e0 28 a0 18 ae a6 69 30 1a 93 39 2d
[rtmpdump] DEBUG: 56 f9 fe 74 2d 6d 3a f4 f6 1f 9c e2 18 a8 c7 69
[rtmpdump] DEBUG: fe 02 85 02 dc 6f 42 c9 60 b2 1b 38 fb 6a 09 f3
[rtmpdump] DEBUG: ef 10 7a 41 fa ed f5 ad 80 da 37 ee e0 a8 9b b8
[rtmpdump] DEBUG: 0c ab b5 55 6c 82 b0 0c f2 dd fa 67 53 69 ce 2e
[rtmpdump] DEBUG: 78 48 68 96 51 20 53 0b a9 a7 33 93 3e e5 90 1f
[rtmpdump] DEBUG: d4 1b d0 4c db 42 cc 93 3e a0 83 82 fc 59 5e 7c
[rtmpdump] DEBUG: RC4 Out Key: 
[rtmpdump] DEBUG: ed ac 0a 5c 88 19 50 47 bf 72 19 f2 62 18 09 f8
[rtmpdump] DEBUG: RC4 In Key: 
[rtmpdump] DEBUG: 01 c9 a9 3f 40 78 3e 25 10 21 09 83 7c 81 16 90
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server digest: 
[rtmpdump] DEBUG: 6b 35 fc 50 26 10 cc 26 2d 13 53 f7 8e 98 26 93
[rtmpdump] DEBUG: e4 2a 0f 36 d5 76 c2 9d b9 11 c3 65 3b ea 52 5f
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: ae 68 2e a4 8a 92 93 54 7b ce c2 a5 0c 54 e9 8e
[rtmpdump] DEBUG: c7 1b 4a 97 3c ea d6 d8 29 d1 df 36 bd e9 37 82
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: 07 90 7c 50 41 36 ea 02 0f 5b d5 95 00 0e 27 c3
[rtmpdump] DEBUG: d6 66 7c 18 a9 5a 71 29 e3 02 fd 0c a4 75 bd 46
[rtmpdump] DEBUG: HandShake: Digest key: 
[rtmpdump] DEBUG: 4f 52 59 5c c0 a4 cf df f4 88 06 e1 ed 9c 16 fb
[rtmpdump] DEBUG: 90 67 b3 f1 10 ef 77 1b 4d 27 35 93 0b b4 b0 fd
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: 07 90 7c 50 41 36 ea 02 0f 5b d5 95 00 0e 27 c3
[rtmpdump] DEBUG: d6 66 7c 18 a9 5a 71 29 e3 02 fd 0c a4 75 bd 46
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 128
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 165 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	error>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Rejected>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Connection failed.>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	[ Server.Reject ] : Connection failed.>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_error>
[rtmpdump] ERROR: rtmp server sent error
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 18 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <close>
[rtmpdump] ERROR: rtmp server requested close
[rtmpdump] DEBUG: Closing connection.


ERROR: rtmpdump exited with code 1
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "./youtube-dl/youtube_dl/__init__.py", line 405, in main
    _real_main(argv)
  File "./youtube-dl/youtube_dl/__init__.py", line 395, in _real_main
    retcode = ydl.download(all_urls)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1502, in download
    res = self.extract_info(url)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 707, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1173, in process_video_result
    self.process_info(new_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1435, in process_info
    success = dl(filename, info_dict)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1377, in dl
    return fd.download(name, info)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "./youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 528, in report_error
    self.trouble(error_message, tb)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 490, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

is it related? It looks like the connect succeeeds but the server drops the connection afterwards.

**Comment by brickleroux** [comment]
Yes, still a server issue.

The server JSON file contains four server addresses. Two RTMPE addresses and two HLS addresses.  In this case, the first RTMPE address (which is used by youtube-dl) does not work, but the second one does:

`rtmpdump --verbose -r rtmpe://s3pwwozuj5hrsa.cloudfront.net/cfx/st/mp4:d195b4180fe041739c845fa6c36dae54_spiegeltv_0500_16x9.m4v -o 'NA-Paradox Episode 1.m4v.part' --live`

Would it be possible to implement the HLS download with FFmpeg (because this works currently more reliable and faster than the RTMPE download)?

`ffmpeg -i 'http://m3u8.schneevonmorgen.com/schnee_vod/_definst_/d195b4180fe041739c845fa6c36dae54_spiegeltv_0500_16x9.m4v/playlist.m3u8' -c copy 'NA-Paradox Episode 1.ts'`
