### ISSUE TITLE
what is error  104?

### ISSUE THREAD

**Issue by msm1365** [rg3/youtube-dl#5844]
[user@dhcppc0 ~]$ youtube-dl https://www.youtube.com/watch?v=DJrMpFOOL-U
[youtube] DJrMpFOOL-U: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(error(104, 'Connection reset by peer'),))

how to fix it?

**Comment by ssokolow** [comment]
Try again. "Connection reset by peer" means that there was a network hiccup of some sort. (You see it all the time as a reason for disconnects from IRC chat servers)

**Comment by jaimeMF** [comment]
I'm closing it as a network error. If you can watch the video on a browser but youtube-dl fails, post the output with the `--verbose` option and we will reopen the issue.

**Comment by msm1365** [comment]
[user@dhcppc0 ~]$ youtube-dl --verbose https://www.youtube.com/watch?v=DJrMpFOOL-U
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=DJrMpFOOL-U']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.9 - Linux-4.0.4-301.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2
[debug] Proxy map: {}
[youtube] DJrMpFOOL-U: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581)> (caused by URLError(SSLError(1, u'[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581)'),))
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1710, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/site-packages/youtube_dl/utils.py", line 713, in https_open
    req, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 1199, in do_open
    raise URLError(err)

**Comment by jaimeMF** [comment]
Assuming you can also watch the video using a browser in the same computer, what does `echo | openssl s_client -connect youtube.com:443` output? If you have wget installed could you try running `wget https://www.youtube.com/watch?v=DJrMpFOOL-U` (you can also try with curl?.

**Comment by msm1365** [comment]
youtube for me is Inaccessible but i use browsec plugin in google-chrome to open youtube. I think for this reason can't downlod.

**Comment by jaimeMF** [comment]
We can't do anything then, you can try to use a proxy with the `--proxy` option or maybe there's an option on your system to use a VPN in all your programs (I don't know).

**Comment by Chawgai** [comment]
sudo apt-get upgrade youtube-dl

worked for me
