### ISSUE TITLE
ERROR: requested format not available

### ISSUE THREAD

**Issue by skrzepto** [rg3/youtube-dl#5851]
I'm on the latest version.

Tried to download audio from https://www.youtube.com/watch?v=nkzsj7XKWaU

First ran command youtube-dl -F to get the available formats see that format code 141 is the best one for audo and then run youtube-dl -f 141 to get the video but get this error

 ~  youtube-dl -f 141 https://www.youtube.com/watch\?v\=nkzsj7XKWaU
[youtube] nkzsj7XKWaU: Downloading webpage
[youtube] nkzsj7XKWaU: Extracting video information
WARNING: [youtube] nkzsj7XKWaU: Skipping DASH manifest: ExtractorError('Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
ERROR: requested format not available

**Comment by skrzepto** [comment]
Weird when i ran the same command with --verbose it ran successfully.

**Comment by dstftw** [comment]
It should work perfectly without `--verbose`.

**Comment by skrzepto** [comment]
Trying without  `--verbose` it works fine now. Strange since I tried about 3 times before the `--verbose` command and it returned the same error. It must be an isolated incident.
