### ISSUE TITLE
videomega.tv

### ISSUE THREAD

**Issue by calvarr** [rg3/youtube-dl#5858]
WARNING: Could not send HEAD request to http://videomega.tv/view.php?ref=054057069050083057073050086053053086050073057083050069057054: HTTP Error 404: Not Found
[generic] view: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue

**Comment by dstftw** [comment]
There is no video within this URL.
