### ISSUE TITLE
unable to download video data: <urlopen error [Errno 64] Host is down>

### ISSUE THREAD

**Issue by hymced** [rg3/youtube-dl#5861]
Hej

That's what I get when trying to download this video here : https://www.youtube.com/watch?v=2MUyWeTns_o

here is the command I run : 

    youtube-dl https://www.youtube.com/watch?v=2MUyWeTns_o --merge-output-format bestaudio+bestvideo

My youtube-dl is up to date.

Cheers

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by hymced** [comment]
I must precise that I often use youtube-dl, and I have never seen this error before 

    youtube-dl https://www.youtube.com/watch?v=2MUyWeTns_o --merge-output-format bestaudio+bestvideo --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=2MUyWeTns_o', u'--merge-output-format', u'bestaudio+bestvideo', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.29
[debug] Python version 2.7.5 - Darwin-13.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.3.3, ffprobe 2.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 2MUyWeTns_o: Downloading webpage
[youtube] 2MUyWeTns_o: Extracting video information
[youtube] 2MUyWeTns_o: Downloading DASH manifest
[debug] Invoking downloader on 'https://r1---sn-aigllnzz.googlevideo.com/videoplayback?id=d8c53259e4e7b3fa&itag=136&source=youtube&requiressl=yes&nh=IgpwcjAxLmxocjE0KgkxMjcuMC4wLjE&pl=19&mm=31&mv=m&ms=au&ratebypass=yes&mime=video/mp4&gir=yes&clen=49145551&lmt=1393367314710179&dur=340.401&upn=pVo1il4lTr0&key=dg_yt0&signature=4F496E7C9CF94720338D35AE7AB16642772C2E2B.8C1CB36E98DFEB3CBABEBF025D8F96B271F9BB8F&fexp=908415,936106,9405973,9406690,9407440,9407992,9408142,9408211,9408420,9408710,9408764,9413138,9413503,9414737,9414847,9415304,9415538,952612&sver=3&mt=1433094058&ip=92.140.25.3&ipbits=0&expire=1433115753&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,pl,mm,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
ERROR: unable to download video data: <urlopen error [Errno 64] Host is down>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1413, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1361, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1713, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 713, in https_open
    req, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 64] Host is down>

**Comment by dstftw** [comment]
Probably a connectivity problem. In issue title you state `<urlopen error [Errno 64] Host is down>` that is missing from full log. Clarify on this.
By the way, you are misusing format selection, should be `--format bestaudio+bestvideo`.

**Comment by hymced** [comment]
I have just tried again, now it works fine.
