### ISSUE TITLE
youtube-dl not displaying correct bitrates for youtube?

### ISSUE THREAD

**Issue by 2011** [rg3/youtube-dl#5866]
$ youtube-dl -F 'https://www.youtube.com/watch?v=FJjq_WS2_Q8'
[youtube] FJjq_WS2_Q8: Downloading webpage
[youtube] FJjq_WS2_Q8: Extracting video information
[youtube] FJjq_WS2_Q8: Downloading DASH manifest
[info] Available formats for FJjq_WS2_Q8:
format code  extension  resolution note
140          m4a        audio only DASH audio  128k , m4a_dash container, aac  @128k (44100Hz), 5.09MiB
171          webm       audio only DASH audio  130k , audio@128k (44100Hz), 4.40MiB
141          m4a        audio only DASH audio  255k , m4a_dash container, aac  @256k (44100Hz), 10.23MiB
160          mp4        256x144    DASH video  111k , 13fps, video only, 4.37MiB
278          webm       256x144    DASH video  117k , webm container, VP9, 13fps, video only, 3.73MiB
133          mp4        426x240    DASH video  251k , 25fps, video only, 9.81MiB
242          webm       426x240    DASH video  306k , 25fps, video only, 9.20MiB
243          webm       640x360    DASH video  561k , 25fps, video only, 16.81MiB
134          mp4        640x360    DASH video  606k , 25fps, video only, 23.91MiB
244          webm       854x480    DASH video 1024k , 25fps, video only, 30.04MiB
135          mp4        854x480    DASH video 1112k , 25fps, video only, 43.94MiB
247          webm       1280x720   DASH video 2137k , 25fps, video only, 60.40MiB
136          mp4        1280x720   DASH video 2223k , 25fps, video only, 87.07MiB
248          webm       1920x1080  DASH video 3834k , 25fps, video only, 109.73MiB
137          mp4        1920x1080  DASH video 4516k , 25fps, video only, 164.31MiB
17           3gp        176x144    
36           3gp        320x240    
5            flv        400x240    
43           webm       640x360    
18           mp4        640x360    
22           mp4        1280x720   (best)

$ youtube-dl -f 136 'https://www.youtube.com/watch?v=FJjq_WS2_Q8'
[...]

$ youtube-dl -f 247 'https://www.youtube.com/watch?v=FJjq_WS2_Q8'
[...]

$ ls -al *FJjq_WS2_Q8*
-rw------- 1 user user 91301761 2015-05-22 17:17:51 FJjq_WS2_Q8-136.mp4
-rw------- 1 user user 63332828 2015-05-22 17:44:41 FJjq_WS2_Q8-247.webm

$ mediainfo FJjq_WS2_Q8-136.mp4
General
Complete name                            : FJjq_WS2_Q8-136.mp4
Format                                   : dash
Codec ID                                 : dash
File size                                : 87.1 MiB
Duration                                 : 5mn 36s
Overall bit rate                         : 2 172 Kbps
Encoded date                             : UTC 2015-05-22 17:17:44
Tagged date                              : UTC 2015-05-22 17:17:44

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 3 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 5mn 36s
Bit rate                                 : 2 170 Kbps
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.094
Stream size                              : 87.0 MiB (100%)
Encoded date                             : UTC 2015-05-22 17:17:44
Tagged date                              : UTC 2015-05-22 17:17:44

$ mediainfo FJjq_WS2_Q8-247.webm
General
Complete name                            : FJjq_WS2_Q8-247.webm
Format                                   : WebM
Format version                           : Version 2
File size                                : 60.4 MiB
Duration                                 : 5mn 36s
Overall bit rate                         : 1 507 Kbps
Writing application                      : google
Writing library                          : google

Video
ID                                       : 1
Format                                   : VP9
Codec ID                                 : V_VP9
Duration                                 : 5mn 36s
Bit rate                                 : 1 440 Kbps
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Bits/(Pixel*Frame)                       : 0.063
Stream size                              : 57.7 MiB (96%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

I realize that quality comparisons between codecs using bitrates are fairly meaningless (better codec can have higher quality at a lower bitrate), but still, numbers are numbers, and the webm stream has a bitrate close to 1500 Kbps, not one anywhere near 2100 Kbps.

**Comment by dstftw** [comment]
youtube-dl displays bitrate provided by YouTube within metadata. There is nothing we can do if it's wrong.
