### ISSUE TITLE
I can't download Video from YouTube

### ISSUE THREAD

**Issue by adsd1022** [rg3/youtube-dl#5869]
I try downloading Video this URL: https://youtu.be/b_ubVVnWglk
But youtube dl has an error..

" ERROR: rtmpe downloads are not supported, see https://github.com/rg3/youtube-dl/
issues/343 for more information. "

What could I do?

**Comment by jaimeMF** [comment]
Duplicate of #343.

> What could I do?

Wait until someone add support for those videos.
