### ISSUE TITLE
define quality  type of link from  youtube  playlist 

### ISSUE THREAD

**Issue by badershs** [rg3/youtube-dl#5870]
how can i get all playlist video  link like

 http://r3---sn-cxab5jvh-cg0l.googlevideo.com/videoplayback?...........  

my goal is i have playlist and i need to  to get special quality link for the videos and the problem is when i toke them in json . in some video i have more then 20 type of quality but for me i need 5 or 6  for each video 
is there is any order to do that or what ?

**Comment by dstftw** [comment]
Explain it more carefully and provide an example. Now it's totally unclear what are you trying to achieve.

**Comment by badershs** [comment]
for example i have this playlist 
https://www.youtube.com/playlist?list=PLANMHOrJaFxPCjR2enLZBRgtZgjtXJ0MJ
it contain 3 video 
i need to download this video by there link which like "http://r3---sn-cxab5jvh-cg0l.googlevideo.com/vi...." 
and what we know is this videos have some quality like mp4 flv mpeg ect. .. .and each quality has special link 
the problem is i need to get these links for each video but not all 
i need to get mp4 flv 3gp and some specific link but when i use json i get every think and i can't archive them 
------
in general the output must be like 
first video : mp4:link http://r3---sn-cxafsdfsdfsdb5jvh-c
first video : flv:link http://r3---sn-cxafsdfdsb5jvh-c
first video : 3gp:link http://r3---sn-cxafsdfsdb5jvh-c

second video : mp4:link http://r3---sn-cxaffdsb5jvh-c
second video : flv:link http://r3---sn-cxsfsfsdfsdfsab5sfjvh-c
second video : 3gp:link http://r3---sn-cxfsdfdfab5jvh-c

is it clear now ? ?

**Comment by dstftw** [comment]
Formats are identified by *format codes*, not by extensions. There may be lots of mp4's or 3gp's of different quality.
To achieve somewhat similar you can pass comma separated list of format codes to `-f`, e.g. `-f 36,5,18` along with `-g` option and youtube-dl will output three links (each per line) for each video in playlist in the order corresponding to `36,5,18` (`youtube-dl -f 36,5,18 -g https://www.youtube.com/playlist?list=PLANMHOrJaFxPCjR2enLZBRgtZgjtXJ0MJ`).
However, I still can't get it why can't you just rip it out of JSON via corresponding format codes yourself.
