### ISSUE TITLE
Extractor Youku returned a compat_list result. It needs to be updated.

### ISSUE THREAD

**Issue by Popolon** [rg3/youtube-dl#5872]
youtube-dl 'http://v.youku.com/v_show/id_XMTM5Mzk2NzYw.html'
[Youku] XMTM5Mzk2NzYw: Downloading JSON metadata
WARNING: Extractor Youku returned a compat_list result. It needs to be updated.
ERROR: unable to download video data: HTTP Error 404: Not Found

This is not a duplicate of #3038 (connexion refused and the ticket is closed).

**Comment by jaimeMF** [comment]
Like #5114, it's probably a duplicate of #3038 (which is still open).
