### ISSUE TITLE
get direct video URLs

### ISSUE THREAD

**Issue by eadmaster** [rg3/youtube-dl#5873]
is it possible to do a "dry run" (do not download the video) and get the direct video url?
Probably this is not possible for all the supported sites, but still useful.
For instance the user may want to use an external download manager, or just try direct viewing with a video player:
 
    mplayer $(youtube-dl --get-url https://www.youtube.com/watch?v=_MC3XuMvsDI)

**Comment by dstftw** [comment]
That's what actually the command you mentioned does.
```
-g, --get-url                    Simulate, quiet but print URL
```

**Comment by Thawab** [comment]
https://udemy-assets-on-demand.udemy.com/2015-12-10_01-07-27-54739ac8b140645990b1bf0dd77472bc/WebHD_720p.mp4?nva=20151230073422&download=True&filename=chat-system-in-php-1mp4.mp4&token=0a8dac87b665c59610aac
https://udemy-assets-on-demand.udemy.com/2015-12-09_20-26-25-4c9797fe355e0dc5bb9d15490b295a89/WebHD_720p.mp4?nva=20151230073424&download=True&filename=chat-system-in-php-2mp4.mp4&token=0a96160fc0eb4db7fa19e
https://udemy-assets-on-demand.udemy.com/2015-12-09_21-12-02-3881f95c231ba87aa7e05ac96f8c7377/WebHD_720p.mp4?nva=20151230073426&filename=chat-system-in-php-3mp4.mp4&download=True&token=0fb19f4b39242decb13f4
https://udemy-assets-on-demand.udemy.com/2015-12-09_22-19-27-e71704d17bb7a57c26ed40bd4bf601d0/WebHD_720p.mp4?nva=20151230073428&download=True&filename=chat-system-in-php-4mp4.mp4&token=0d39f4a7924f79f7d73ae
https://udemy-assets-on-demand.udemy.com/2015-12-09_22-23-56-e8b2e52cd43fcee37de60ab1de1017e1/WebHD_720p.mp4?nva=20151230073430&filename=chat-system-in-php-5mp4.mp4&download=True&token=0214163bf6e95e0a58743
https://udemy-assets-on-demand.udemy.com/2015-12-09_23-04-57-9fcb040338790ddb713936b04592f5ad/WebHD_720p.mp4?nva=20151230073432&download=True&filename=chat-system-in-php-6mp4.mp4&token=0fa8717b3eab1926b4900
