### ISSUE TITLE
some videos produce unviewable .mkv files

### ISSUE THREAD

**Issue by cjfsyntropy** [rg3/youtube-dl#5874]
Downloading this YouTube video http://y2u.be/KLqy_pv1tMo produces an unviewable .mkv file.

$ youtube-dl -k -v KLqy_pv1tMo
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-k', u'-v', u'KLqy_pv1tMo']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.0
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg 0.8.17-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] KLqy_pv1tMo: Downloading webpage
[youtube] KLqy_pv1tMo: Extracting video information
[youtube] KLqy_pv1tMo: Downloading DASH manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r7---sn-gjo-2iae.googlevideo.com/videoplayback?id=28bab2fe9bf5b4ca&itag=303&source=youtube&requiressl=yes&mm=31&pl=24&mv=m&ms=au&ratebypass=yes&mime=video/webm&gir=yes&clen=262383778&lmt=1425745640195566&dur=730.363&fexp=9406618,9407122,9407943,9408142,9408420,9408710,9408788,9412494,9413039,9413341,9413503,9414851,9414857,9415143,9415304,9415488,9415554,952612&upn=oIMN03v7Tkw&key=dg_yt0&sver=3&signature=0A2B521692C4D97795BF512AB3541A045BDE95CD.4F3A628849DE04AB241873EF52C4843D46448AEF&mt=1433213516&ip=207.172.195.165&ipbits=0&expire=1433235144&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,pl,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Shellshonic Shag-o-vision Episode 6 [Ali Koehler]-KLqy_pv1tMo.f303.webm
[download] 100% of 250.23MiB in 01:12
[debug] Invoking downloader on 'https://r7---sn-gjo-2iae.googlevideo.com/videoplayback?id=28bab2fe9bf5b4ca&itag=141&source=youtube&requiressl=yes&mm=31&pl=24&mv=m&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=23291264&lmt=1394000544747997&dur=730.522&fexp=9406618,9407122,9407943,9408142,9408420,9408710,9408788,9412494,9413039,9413341,9413503,9414851,9414857,9415143,9415304,9415488,9415554,952612&upn=oIMN03v7Tkw&key=dg_yt0&sver=3&signature=0693C31E6874924FA565672C5CC6D6C156F8922C.5F64805C91BDD3BEE8B347ACCEE609EB2540424B&mt=1433213516&ip=207.172.195.165&ipbits=0&expire=1433235144&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,pl,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Shellshonic Shag-o-vision Episode 6 [Ali Koehler]-KLqy_pv1tMo.f141.m4a
[download] 100% of 22.21MiB in 00:06
[ffmpeg] Merging formats into "Shellshonic Shag-o-vision Episode 6 [Ali Koehler]-KLqy_pv1tMo.mkv"
[debug] ffmpeg command line: avconv -y -i 'Shellshonic Shag-o-vision Episode 6 [Ali Koehler]-KLqy_pv1tMo.f303.webm' -i 'Shellshonic Shag-o-vision Episode 6 [Ali Koehler]-KLqy_pv1tMo.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'Shellshonic Shag-o-vision Episode 6 [Ali Koehler]-KLqy_pv1tMo.temp.mkv'
(failed reverse-i-search)`avcov': ^Cconv -i Shag-O-Vision.3.Shellshonic\ shag-o-vision\ Episode\ 2\ \[Laura\ Stevenson\]-lhqby1ByPOI.f303.webm -i Shag-O-Vision.3.Shellshonic\ shag-o-vision\ Episode\ 2\ \[Laura\ Stevenson\]-lhqby1ByPOI.f141.m4a Shag-O-Vision.3.Shellshonic\ shag-o-vision\ Episode\ 2\ \[Laura\ Stevenson\]-lhqby1ByPOI.new.mkv
[status 130]

Using mplayer2 on both Debian wheezy and Jessie fails to play the video in the .mkv file produced. The audio works fine.

If I manually run this command:
$ avconv -i Shellshonic\ Shag-o-vision\ Episode\ 6\ \[Ali\ Koehler\]-KLqy_pv1tMo.f303.webm -i Shellshonic\ Shag-o-vision\ Episode\ 6\ \[Ali\ Koehler\]-KLqy_pv1tMo.f141.m4a Shellshonic\ Shag-o-vision\ Episode\ 6\ \[Ali\ Koehler\]-KLqy_pv1tMo.new.mkv

Then I can play the video (of course, that command takes "forever" to build an .mkv file).

Most videos convert correctly for me. But this one (and some others) have failed all in the same way (audio works, video fails).

**Comment by LollenJumplan** [comment]
Strange because my testing machine on youtube-dl version 2015.05.20 produces a file that plays just fine - just not an mkv - even though I am using the same version and invocation.

**Comment by cjfsyntropy** [comment]
If I run this command manually:
$ avconv -i 'Shellshonic Shag-o-vision Episode 6 [Ali Koehler]-KLqy_pv1tMo.f303.webm' -i 'Shellshonic Shag-o-vision Episode 6 [Ali Koehler]-KLqy_pv1tMo.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'Shellshonic Shag-o-vision Episode 6 [Ali Koehler]-KLqy_pv1tMo.temp.mkv'
The end of the output says:
frame=43779 fps=14667 q=-1.0 Lsize=  279064kB time=730.36 bitrate=3130.1kbits/s    
video:255932kB audio:22614kB other streams:0kB global headers:0kB muxing overhead: 0.186105%

And the video does not play in mplayer2:
In the mplayer2 output I see this:
[mkv] Unknown/unsupported CodecID (V_VP9) or missing/bad CodecPrivate
[mkv] data (track 1).
[mkv] Track ID 1: video (V_VP9), -vid 0
[mkv] Track ID 2: audio (A_AAC), -aid 0, -alang und
[mkv] No video track found/wanted.

In the video that I manually produced without the optimizing -map options, mplayer2 reports this:
Detected file format: QuickTime/MPEG-4/Motion JPEG 2000 format (libavformat)
[lavf] stream 0: video (h264), -vid 0
[lavf] stream 1: audio (aac), -aid 0, -alang und
VIDEO:  [H264]  1920x1080  24bpp  47.952 fps  5235.7 kbps (639.1 kbyte/s)

And the video plays.

My avconv is from Debian Jessie:
$ avconv -version
avconv version 11.3-6:11.3-1, Copyright (c) 2000-2014 the Libav developers
  built on Mar 13 2015 23:05:34 with gcc 4.9.2 (Debian 4.9.2-10)
avconv 11.3-6:11.3-1
libavutil     54.  3. 0 / 54.  3. 0
libavcodec    56.  1. 0 / 56.  1. 0
libavformat   56.  1. 0 / 56.  1. 0
libavdevice   55.  0. 0 / 55.  0. 0
libavfilter    5.  0. 0 /  5.  0. 0
libavresample  2.  1. 0 /  2.  1. 0
libswscale     3.  0. 0 /  3.  0. 0
$ dpkg -l libav-tools
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version       Architecture  Description
+++-================-=============-=============-======================================
ii  libav-tools      6:11.3-1      i386          Multimedia player, encoder and transco

Hopefully that helps.

**Comment by dstftw** [comment]
Most likely an mplayer2 issue, same for vlc 2.2. mplayer and mpv play it perfectly.
