### ISSUE TITLE
[mixcloud] unable to extract like count

### ISSUE THREAD

**Issue by sweetdub** [rg3/youtube-dl#5879]
There's a warning while script try to extract like count from an url.
The command:

    youtube-dl -s http://www.mixcloud.com/dholbach/cryptkeeper/

Returns:

    [mixcloud] dholbach-cryptkeeper: Downloading webpage
    [mixcloud] dholbach-cryptkeeper: Checking URL 14/30 ...
    WARNING: unable to extract like count; please report this issue on http://yt-dl.org/bug

I think it can be fixed here, but I don't know how to debug a python script:
https://github.com/rg3/youtube-dl/blob/c5826a491b7b214a7e81030ad53103c4aca04dc2/youtube_dl/extractor/mixcloud.py#L90

Thanks!

**Comment by jaimeMF** [comment]
You are using an outdated version, you'll have to (update](https://github.com/rg3/youtube-dl/blob/60158217ef8da5f44ef316e50c8a5e2ac2e202c5/README.md#how-do-i-update-youtube-dl)

For future reports, please post [the output with the --verbose option](https://github.com/rg3/youtube-dl/blob/60158217ef8da5f44ef316e50c8a5e2ac2e202c5/README.md#bugs).

**Comment by sweetdub** [comment]
Yes indeed, sorry about this false issue.
