### ISSUE TITLE
Unable to extract title from facebook

### ISSUE THREAD

**Issue by spaceexperiment** [rg3/youtube-dl#5880]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'--verbose', u'https://www.facebook.com/746502648717586/videos/976069362427579/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.6 - Linux-3.13.0-53-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 976069362427579: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[info] Available formats for 976069362427579:
format code  extension  resolution note
sd           mp4        unknown

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
It has been fixed in 2015.05.29.

**Comment by spaceexperiment** [comment]
i see, pip is saying i have the latest version. is it better to install directly instead of pip ?

**Comment by dstftw** [comment]
pip is ok. That's stange. We ship to PyPI when releasing new version. This time however it doesn't reach it for some reason.
