### ISSUE TITLE
Regex error on Tumblr (NSFW video link)

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#5883]
vxbinaca@workstation/~/git/tumblr-utils/naked-yogi/videos$ youtube-dl --verbose http://naked-yogi.tumblr.com/post/118312946248/naked-smoking-stretching
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://naked-yogi.tumblr.com/post/118312946248/naked-smoking-stretching']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.9 - Linux-3.19.0-18-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[Tumblr] 118312946248: Downloading webpage
ERROR: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/tumblr.py", line 43, in _real_extract
    webpage, 'iframe url')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Lemme know if you need more.

**Comment by yan12125** [comment]
Thanks for the report. This issue will be fixed in the next version.
