### ISSUE TITLE
How can I get a downloaded file in the format of OriginalYoutubeVideoTitle_MyOwnAdditionalTitle.mp4?

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#5892]
What is the exact command I should use when I want to add a few words of my own to the original filename?
For instance,
If I do
youtube-dl  "https://www.youtube.com/watch?v=h--AbCdbbEWo", my folder will contain a file like
"Amazing Jellyfish in Palau.mp4"

I'd like instead to get a filename like
"Amazing Jellyfish in Palau_ht_Bob_Smith.mp4"
(in case you're curious, "ht_Bob_Smith" is my reminder that my friend Bob is the one who suggested I watch this video).

I read the description for the "-o" option, but, sorry to say, I don't understand.

**Comment by jaimeMF** [comment]
I can't open the url you posted, but `youtube-dl 'https://www.youtube.com/watch?v=h--AbCdbbEWo' -o '%(title)s_ht_Bob_Smith.%(ext)s'` should work. The `%(____)s` are replace by the correct info extracted by youtube-dl.
