### ISSUE TITLE
add support for RapidVideo.tv

### ISSUE THREAD

**Issue by eadmaster** [rg3/youtube-dl#5897]
It only requires a javascript beautifier to get the direct video url:
http://howtodownload.org/how-to-download-videos-from-rapidvideo-tv

**Comment by jaimeMF** [comment]
[Post an example url](https://github.com/rg3/youtube-dl/blob/eb6cb9fbe934fe99a35af22065cf91063d416c12/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by eadmaster** [comment]
ok, here it is:
http://www.rapidvideo.org/x9q9dh32cvle

**Comment by jaimeMF** [comment]
The video is a copyrighted tv show episode ([Wikipedia article](https://en.wikipedia.org/wiki/The_Simpsons)) and I doubt they have the rights for distributing that content, and [it seems that a lot of their videos are infringing copyright](https://www.google.com/transparencyreport/removals/copyright/domains/rapidvideo.org/). [We can't add support for this kind if sites](https://github.com/rg3/youtube-dl/blob/4c8fea92f350d5a3f33d505980ac750b05a9cd34/README.md#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
