### ISSUE TITLE
Please add option to output YouTube video URL

### ISSUE THREAD

**Issue by tmiranda1962** [rg3/youtube-dl#5903]
I would like to use this program to enhance the YouTube support in SageTV. To do that I need the physical video URL

**Comment by dstftw** [comment]
```
-g, --get-url                    Simulate, quiet but print URL
```

**Comment by tmiranda1962** [comment]
I tried that and it doesn't print the video URL.  It prints the entire content of what's returned from the www.youtube.com/watch?v=youtubeid. The video links are embedded in there somewhere.

**Comment by dstftw** [comment]
What do you mean by video URL? Explain.

**Comment by tmiranda1962** [comment]
The physical URL that points to the video file. www.youtube.com/.../.../somevideo.mp4 for example.

**Comment by dstftw** [comment]
That's exactly what `--get-url` does.

**Comment by tmiranda1962** [comment]
Here is what is returned when I tried it. It contains a lot of information about the video but nowhere do I see a URL that points directly to the video file.

https://r6---sn-hp57knle.googlevideo.com/videoplayback?initcwndbps=487500&nh=IgpwcjA0Lm1pYTA0KgkxMjcuMC4wLjE&mm=31&fexp=9406545%2C9406678%2C9407887%2C9408142%2C9408420%2C9408710%2C9409172%2C9409208%2C9409225%2C9412774%2C9413153%2C9413503%2C9414784%2C9415304%2C9415489%2C948605&ipbits=0&mv=m&source=youtube&id=o-ACdWQKDHHRKJ_b1uxifiFPpIpre4FK84NJWHFWzvnQv7&ratebypass=yes&ip=24.48.134.228&itag=22&pl=21&dur=1411.169&upn=4iolynbr2LU&requiressl=yes&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&expire=1433563127&mt=1433541414&sver=3&mime=video%2Fmp4&signature=F2B5037344B70210E13FA4183F33A47225F3D30A.E98E52A71932CCEF4996FAE5738851179BE29181&key=yt5&ms=au

**Comment by dstftw** [comment]
That's how YouTube serve the videos. Every piece of that is important.

**Comment by tmiranda1962** [comment]
Yes, and your program sorts through all of that and downloads the video
file. How do you know what file to download? That's the information I need.

**Comment by dstftw** [comment]
Once again. That is **final direct downloadable** link of requested quality. If you pass it to wget/curl/whatever it will start downloading.

**Comment by tmiranda1962** [comment]
OK, now I see. I didn't understand that.  Thanks for the help :)
