### ISSUE TITLE
Impossible to download

### ISSUE THREAD

**Issue by Fristing** [rg3/youtube-dl#5905]
i have this error : 

root@srv:/usr/local/bin# youtube-dl -x https://www.youtube.com/watch?v=reSp-eYpRqo
[youtube] reSp-eYpRqo: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
You have propably download too many videos, [see this FAQ entry](https://github.com/rg3/youtube-dl/blob/eb6cb9fbe934fe99a35af22065cf91063d416c12/README.md#http-error-429-too-many-requests-or-402-payment-required) (issue #5138 may also help). If you can't watch the video on the browser using the same computer youtube-dl can't download it.

Side note: **don't run youtube-dl as the root user**.
