### ISSUE TITLE
Error downloading a playlist from youtube 

### ISSUE THREAD

**Issue by 4380** [rg3/youtube-dl#5906]
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.

Linux elementary os freya

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by 4380** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.5 - Linux-3.16.0-38-generic-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

**Comment by 4380** [comment]
valeriu@X550VC:~$ youtube-dl --verbos https://www.youtube.com/watch?v=VHBcS0fYWfc
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbos', u'https://www.youtube.com/watch?v=VHBcS0fYWfc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.5 - Linux-3.16.0-38-generic-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] VHBcS0fYWfc: Downloading webpage
[youtube] VHBcS0fYWfc: Extracting video information
[youtube] VHBcS0fYWfc: Downloading DASH manifest
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Invoking downloader on u'https://r5---sn-c0q7ln76.googlevideo.com/videoplayback?ip=109.102.94.124&ipbits=0&fexp=916727%2C919126%2C9405437%2C9405969%2C9406770%2C9407053%2C9407715%2C9407942%2C9407991%2C9408142%2C9408420%2C9408710%2C9412842%2C9412913%2C9413208%2C9413503%2C9415304%2C9415348%2C9415489%2C9415595%2C962731&signature=B2DE5C88308CE88EDF8EC176550C5463DDBD2F97.5292E8072E816AF1FBAA5438A258841949ED3F3E&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=qYuqzUnJjL8&id=o-AJo72-IvF96NexSZmjQrqVjYIpWQ3qorJgSemxE-I0X8&itag=22&initcwndbps=4977500&requiressl=yes&key=yt5&ratebypass=yes&mn=sn-c0q7ln76&mm=31&ms=au&mv=m&mt=1433592801&mime=video%2Fmp4&expire=1433614488&sver=3&dur=247.826&pl=23&source=youtube'
[download] Resuming download at byte 1047552
[download] Destination: Low Deep T - Casablanca (Official Video HD)-VHBcS0fYWfc.mp4
[download]   3.7% of 40.50MiB at 541.79KiB/s ETA 01:13^C
ERROR: Interrupted by user
like this ?

**Comment by dstftw** [comment]
There are no errors. Post the log where you experiencing errors.

**Comment by 4380** [comment]
I am unable to download playlists

valeriu@X550VC:~$ youtube-dl https://www.youtube.com/watch?v=A3NWOa6K7MI&list=PLV0vJQUYPWFq4LE1TSVANOSEUJ5D_XtGT
[1] 5310
valeriu@X550VC:~$ [youtube] A3NWOa6K7MI: Downloading webpage
[youtube] A3NWOa6K7MI: Extracting video information
[youtube] A3NWOa6K7MI: Downloading DASH manifest
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[download] Major Lazer & DJ Snake - Lean On (Feat. MØ) (Jonas Aden Remix)-A3NWOa6K7MI.mp4 has already been downloaded
[download] 100% of 26.81MiB

**Comment by dstftw** [comment]
You have to [put the URL into quotes](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).

**Comment by 4380** [comment]
Thank you so much for the speedy reply. :)
