### ISSUE TITLE
-U doesn't use encrypted connection

### ISSUE THREAD

**Issue by mrphs** [rg3/youtube-dl#5909]
When I try to update `youtube-dl` using `-U` option on `OSX`, it tries to connect to `rg3.github.io` over port 80. And then it tries to update the software over an unencrypted and unauthenticated channel. 

This is bad, because unencrypted and unauthenticated traffic is bad, and because anyone on the network could easily tamper the traffic.

Please use TLS?

**Comment by jaimeMF** [comment]
Fixed, thanks for the report!

Note that the files are [verified with RSA](https://github.com/rg3/youtube-dl/blob/de390ea0771a0e35c0c2970bc00f5fa2dd9d3eac/youtube_dl/update.py#L91), so it shouldn't be as easy as replacing the content (but my knowledges are quite limited in that field).
