### ISSUE TITLE
Always get " ERROR: content too short" 

### ISSUE THREAD

**Issue by AlfredMo** [rg3/youtube-dl#5911]
[download]  85.7% of 44.32MiB at  8.48MiB/s ETA 00:00 ERROR: content too short (
expected 46477872 bytes and served 39846316)

**Comment by yan12125** [comment]
Which video are you trying to download? Please paste the video link.

**Comment by AlfredMao** [comment]
Hi Yan, 

Thanks for the response. 

it's occurred randomly, like this one, happened after a few videos then succeed after a few time retry.
youtube-dl.exe  -o "Y:\@youtube\健身\%(title)s.%(ext)s" https://www.youtube.com/user/kos44444/videos

**Comment by yan12125** [comment]
There are lots of videos on that page. Is the video in problem different each time?

**Comment by AlfredMao** [comment]
yes, each time it's different.

**Comment by yan12125** [comment]
I can download all of the videos from here. Maybe it's a network issue. I'm sorry that I can't help more.

**Comment by AlfredMao** [comment]
No worries. Retry a couple of times will do the work.

**Comment by Tatsh** [comment]
I am getting this issue too. Why doesn't the `-R` (retry) functionality apply here?

**Comment by jaimeMF** [comment]
@Tatsh the `--ignore-errors` option (or `-i`) should skip those videos.
