### ISSUE TITLE
generic extractor improvement: add a JavaScript beautifier

### ISSUE THREAD

**Issue by eadmaster** [rg3/youtube-dl#5913]
A JavaScript beautifier could help with websites obfuscating direct video URLs.

**Comment by dstftw** [comment]
I doubt beautifying JS will help anyhow in generic extractor since it's generally based on regular patterns.

**Comment by yan12125** [comment]
I'm not sure why @dstftw closed this issue. AFAIK, tools like beautifiers help humans but not machines. In other words, they help programmars but not programs (youtube-dl), so there's no need to integrate the tools into youtube-dl.

**Comment by eadmaster** [comment]
the point is that some video hosting websites are obfuscating the direct video URL using javascript. So a JavaScript beautifier could expose/un-obfuscate the url for downloading with the generic extractor.

**Comment by jaimeMF** [comment]
You'll have to post an example url.
Implementing a general beautifier in python is probably a big task, it would be better if we had an example we can start with.

**Comment by eadmaster** [comment]
You could take this as an example:
http://www.rapidvideo.org/m612rwnlbv5k
(even if the website won't be supported officially due to licensed contents, it could be still supported using the generic plugin)

**Comment by jaimeMF** [comment]
We'd need to add a test for it, so please post a url from a site that doesn't infringe copyright.
