### ISSUE TITLE
add support for VVVVID.it

### ISSUE THREAD

**Issue by eadmaster** [rg3/youtube-dl#5915]
this is an Italian streaming website hosting only licensed videos (no user-submitted content hosted).

Example url:
http://www.vvvvid.it/#!show/268/mardock-scramble/257/469252/the-second-combustion

**Comment by Niggolo** [comment]
Hello,
Is possible to hide fragment? http://prntscr.com/e2rwjv
im using the --no-part but not working: 
youtube-dl.exe https://www.vvvvid.it/#!show/376/death-note-live-action/377/482493/episodio-01 --ffmpeg-location "D:\avconv.exe" --prefer-avconv -o "D:\test\test.mp4" --no-part

thank you

**Comment by dstftw** [comment]
Fragment files are deleted upon download is finished.
