### ISSUE TITLE
--list-extractors option does not list URLs

### ISSUE THREAD

**Issue by baco** [rg3/youtube-dl#5916]
The --list-extractors option does not list the URLs each extractor would handle as it is documented on manpage.

**Comment by dstftw** [comment]
What do you mean by URL? Extractor knows nothing about URLs. The only thing it has is a [regular expression](http://en.wikipedia.org/wiki/Regular_expression) that is be checked against input URL and if matched the execution is delegaed to this extractor. Listing those regular expressions will only clutter the output.

**Comment by baco** [comment]
The help string for --list-extractors option [says](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/options.py#L146), and I quote: «List all supported extractors and the URLs they would handle». The list of extractors' names is shown but no URL is printed. Either the documentation is wrong or some informarion is missing on extractors.

BTW, when I first read this option I was expecting the site URL for the extractor, as in https://youtube.com/ for YouTube extractor.
