### ISSUE TITLE
multiple warnings for version (2015.06.04.1)

### ISSUE THREAD

**Issue by gaming-hacker** [rg3/youtube-dl#5923]
I have version 
youtube-dl is up-to-date (2015.06.04.1)

i had no issues with previous version

i was downloading from youtube
https://www.youtube.com/watch?v=qTPhxrg6ztg

[youtube] qTPhxrg6ztg: Skipping DASH manifest: ExtractorError(u'Signature extraction failed: extractor/youtube.py", line 658, in _decrypt_signature\n    video_id, player_url, s\n  

extractor/youtube.py", line 585, in _extract_signature_function\n    cache_res = res(test_string)\n  

/extractor/youtube.py", line 637, in <lambda>\n    return lambda s: initial_function([s])\n 

/youtube_dl/jsinterp.py", line 254, in resf\n    res, abort = self.interpret_statement(stmt, local_vars)\n  

/jsinterp.py", line 55, in interpret_statement\n    v = self.interpret_expression(expr, local_vars, allow_recursion)\n  

/jsinterp.py", line 174, in interpret_expression\n    return obj[member](argvals)\n  

/jsinterp.py", line 254, in resf\n    res, abort = self.interpret_statement(stmt, local_vars)\n 

jsinterp.py", line 55, in interpret_statement\n    v = self.interpret_expression(expr, local_vars, allow_recursion)\n  

/jsinterp.py", line 99, in interpret_expression\n    cur = lvar[idx]\nIndexError: list index out of range\n (caused by IndexError(\'list index out of range\',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)

it downloaded the video and audio and I can play it

**Comment by yan12125** [comment]
Thanks for the report. It's a known bug and I'm examining it.

**Comment by yan12125** [comment]
It should be fixed in e1b9322b091122b6f6832c70e3a845a84ee1764e. If the problem still exists, feel free to open a new issue.

**Comment by gaming-hacker** [comment]
thanks, it's fixed.
