### ISSUE TITLE
Is there a way to not download "Blocked Worldwide" videos?

### ISSUE THREAD

**Issue by whitesiroi** [rg3/youtube-dl#5928]
Is there some kind of option that won't allow to download videos that are "blocked worldwide" or "blocked in some countries"?

**Comment by dstftw** [comment]
Clarify on what you mean by this. If video hoster blocks streaming to your country/region you won't be able to download in any case.

**Comment by whitesiroi** [comment]
Thank you for your response.

I download videos that I like and than edit it, and than I upload it to youtube, and sometimes I get this message "blocked worldwide". 

So, if it's possible, I don't want to download that kind of video in the first place.

**Comment by dstftw** [comment]
No, there is no such option.
For not being *blocked* your content has to be original.
