### ISSUE TITLE
Warning given when attempting to download kickstarter video

### ISSUE THREAD

**Issue by woodenphone** [rg3/youtube-dl#5929]
I got some warnings asking me to send them to you guys, so here they are.
The URL i gave was:
https://www.kickstarter.com/projects/1420158244/power-drive-2000/widget/video.html

Here's the command prompt session i was using to run yourybe-dl:

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>yout
ube-dl.exe --update
Updating to version 2015.06.04.1 ...

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>Wait
ing for file handle to be closed ...
Updated youtube-dl to version 2015.06.04.1.
youtube-dl.exe https://www.kickstarter.com/projects/1420158244/power-drive-2000/
widget/video.html
[KickStarter] 1420158244: Downloading webpage
WARNING: unable to extract OpenGraph description; please report this issue on ht
tps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-
dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.
WARNING: unable to extract thumbnail url; please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  t
o update. Be sure to call youtube-dl with the --verbose flag and include its com
plete output.
[download] Destination: Power Drive 2000-1420158244.mp4
[download] 100% of 12.10MiB in 00:28

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>yout
ube-dl.exe --verbose https://www.kickstarter.com/projects/1420158244/power-drive
-2000/widget/video.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.kickstarter.com/projects
/1420158244/power-drive-2000/widget/video.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[KickStarter] 1420158244: Downloading webpage
WARNING: unable to extract OpenGraph description; please report this issue on ht
tps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-
dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.
WARNING: unable to extract thumbnail url; please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  t
o update. Be sure to call youtube-dl with the --verbose flag and include its com
plete output.
[debug] Invoking downloader on u'https://d2pq0u4uni88oo.cloudfront.net/projects/
1784048/video-533555-h264_high.mp4'
[download] Power Drive 2000-1420158244.mp4 has already been downloaded
[download] 100% of 12.10MiB

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>yout
ube-dl.exe --verbose https://www.kickstarter.com/projects/1420158244/power-drive
-2000/widget/video.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.kickstarter.com/projects
/1420158244/power-drive-2000/widget/video.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[KickStarter] 1420158244: Downloading webpage
WARNING: unable to extract OpenGraph description; please report this issue on ht
tps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-
dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.
WARNING: unable to extract thumbnail url; please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  t
o update. Be sure to call youtube-dl with the --verbose flag and include its com
plete output.
[debug] Invoking downloader on u'https://d2pq0u4uni88oo.cloudfront.net/projects/
1784048/video-533555-h264_high.mp4'
[download] Destination: Power Drive 2000-1420158244.mp4
[download] 100% of 12.10MiB in 00:43

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>

**Comment by yan12125** [comment]
Thanks for the report. Thumbnails are extracted correctly now. For OpenGraph description, I can't see any descriptive text on that page, so the warning still exists. If you know where it is, feel free to point it out. Now I'm closing this issue because all possible information are extracted.
