### ISSUE TITLE
[youtube] Error when downloading playlist causes halt

### ISSUE THREAD

**Issue by spongbros** [rg3/youtube-dl#5933]
If an error occurs while downloading a playlist (in my case, a private video caused the error “YouTube said: Please sign in to view this video.”), the playlist download action halts at this point and no further videos in the playlist are downloaded. Please fix it so that videos with download errors are skipped and the rest of the videos in the playlist download automatically. Thank you.

**Comment by yan12125** [comment]
Does ```--ignore-errors``` fit your need?

**Comment by spongbros** [comment]
Yes it does. Thank you!

**Comment by EvanCarroll** [comment]
I think we should perhaps make the error message list this option. Just got this myself.
