### ISSUE TITLE
[youtube] playlist-start and playlist-end downloads all pages even when not needed

### ISSUE THREAD

**Issue by rtega** [rg3/youtube-dl#5935]
example:
youtube-dl --playlist-start=1 --playlist-end=10  http://www.youtube.com/user/FNNnewsCH
downloads all pages of the list even though it only needs the first page.

**Comment by rtega** [comment]
It is not a request. This is a bug report since it used to work like that before but now it no longer does.

**Comment by ben569** [comment]
As I described in issue #5922, the problem also exists when the dateafter and datebefore parameters are given for pages ordered by upload date. Maybe this can help narrow the issue down.

**Comment by jaimeMF** [comment]
> t is not a request. This is a bug report since it used to work like that before but now it no longer does.

Yes, I knew we added support for that feature in some of the youtube extractors but I wasn't sure if it was the channel one.
Thanks for the report!

@ben569 
> As I described in issue #5922, the problem also exists when the dateafter and datebefore parameters are given for pages ordered by upload date. Maybe this can help narrow the issue down.

That's other problem, which would require some more work to implement (I understand why you can find it useful).
