### ISSUE TITLE
Donate link on official website

### ISSUE THREAD

**Issue by skmlcd** [rg3/youtube-dl#5945]
There should be a link to a [donate page](http://rg3.github.io/youtube-dl/donations.html), because it's hard to find. I had to look here in github issues to find it.

**Comment by yan12125** [comment]
FYI: phihag's comment at https://github.com/rg3/youtube-dl/issues/1344#issuecomment-23655317 explains why there's no link to the donation page.

**Comment by skmlcd** [comment]
Ah I see. Sorry, I read another issue (#2864), should have read others too.
