### ISSUE TITLE
Geek and Sundry

### ISSUE THREAD

**Issue by Frenzie** [rg3/youtube-dl#5946]
I don't have time to further look into this myself right now, but here's some basic info I gathered for future reference.

Regular page URL:
http://geekandsundry.com/titansgrave-chapter-0/

Relevant HTML:
```html
    <div class="video-wrapper">
        <div class="video-inner-wrapper container">
            
                        <video
                id="video_4279049078001"
                data-account="4036320279001"
                data-player="5d112ed9-283f-485f-a7f9-33f42e8bc042"
                data-embed="default"
                data-video-id="4279049078001"
                class="video-js"
                autoplay="true"
                controls>
            </video>
```

Relevant streaming playlist link used by the Flash player (`videoId` is `data-video-id` and `pubId` is `data-account`): `http://c.brightcove.com/services/mobile/streaming/index/master.m3u8?videoId=4279049078001&pubId=4036320279001`

**Comment by ciferkey** [comment]
Here's my stab at it: https://github.com/rg3/youtube-dl/pull/5965

**Comment by dstftw** [comment]
New Brightcover embeds will be supported in the next version of youtube-dl.
