### ISSUE TITLE
pypi page is outdated

### ISSUE THREAD

**Issue by ismail** [rg3/youtube-dl#5948]
https://pypi.python.org/pypi/youtube_dl still shows 2015.05.20 as the latest release.

**Comment by iemejia** [comment]
:+1:

**Comment by vxbinaca** [comment]
+1

**Comment by phihag** [comment]
Thank you for the report! There were a couple of server faults in the last uploads. Fixed with youtube-dl 2015.06.15.

**Comment by yan12125** [comment]
It emerges again - both https://pypi.python.org/pypi/youtube_dl and https://pypi.io/project/youtube_dl/ show 2016.05.30.2, while the latest version is 2016.06.02.

**Comment by vxbinaca** [comment]
I concur

**Comment by dstftw** [comment]
Fixed with 2016.06.03.

**Comment by yan12125** [comment]
Again - https://pypi.python.org/pypi/youtube_dl says 2017.12.31

Thanks for TheBest_F-22 on IRC for reporting this.

**Comment by annomatik** [comment]
Again - https://pypi.org/project/youtube_dl/ stuck at youtube_dl 2021.12.17 .
