### ISSUE TITLE
Brightcove "ERROR: Empty playlist; please report this issue...."

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5955]
URL: http://www.thestar.com/news/2015/05/10/father-of-epileptic-girl-wants-marijuana-treatment-legalized.html

Output:
youtube-dl.py -v "http://www.thestar.com/news/2015/05/10/fathe
r-of-epileptic-girl-wants-marijuana-treatment-legalized.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.thestar.com/news/2015/05/10/fath
er-of-epileptic-girl-wants-marijuana-treatment-legalized.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.6 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[generic] father-of-epileptic-girl-wants-marijuana-treatment-legalized: Requesti
ng header
WARNING: Falling back on generic information extractor.
[generic] father-of-epileptic-girl-wants-marijuana-treatment-legalized: Download
ing webpage
[generic] father-of-epileptic-girl-wants-marijuana-treatment-legalized: Extracti
ng information
[generic] Brightcove video detected.
[download] Downloading playlist: Video | Father of epileptic girl wants marijuan
a treatment legalized | Toronto Star
[generic] playlist Video | Father of epileptic girl wants marijuana treatment le
galized | Toronto Star: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Brightcove] AQ~~,AAAAuO4KaJE~,gatFNwSKdGDsWXPp37fXNe5r7qx0iE2S: Downloading pla
ylist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make
sure you are using the latest version; type  youtube-dl -U  to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 650, in e
xtract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 27
3, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\brightcove.py", lin
e 212, in _real_extract
    return self._get_playlist_info(player_key[0])
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\brightcove.py", lin
e 250, in _get_playlist_info
    raise ExtractorError('Empty playlist')
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bu
g . Make sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete outp
ut.

**Comment by dstftw** [comment]
It uses AMF (at least on desktop) that is not currently supported.
