### ISSUE TITLE
double quotes are replaced with single quotes in the filename

### ISSUE THREAD

**Issue by krakrock** [rg3/youtube-dl#5959]
The [song](https://www.youtube.com/watch?v=RbtPXFlZlHg) I'm trying to download has double quotes in the title, yet when I run it through youtube-dl, it outputs it with single quotes.

How it should be:

> Jason Derulo - "Talk Dirty" feat. 2 Chainz (Official HD Music Video)

How it outputs as:

> Jason Derulo - 'Talk Dirty' feat. 2 Chainz (Official HD Music Video) 

Here's my command:

> echo shell_exec('youtube-dl -o "/var/www/dler/audio/%(title)s|' . getID($link) . '.%(ext)s" --write-thumbnail --embed-thumbnail -x --audio-format mp3 "' . $link . '"');

What am I doing wrong?

**Comment by jaimeMF** [comment]
We remove them in [`sanitize_filename`](https://github.com/rg3/youtube-dl/blob/ecee5724110847b832a6074c66ca4a63758100f4/youtube_dl/utils.py#L282), it was changed to remove double quotes in #502.  I don't know if keeping them would cause some problem.
