### ISSUE TITLE
Turn off post processing

### ISSUE THREAD

**Issue by a3leggeddog** [rg3/youtube-dl#5964]
Hello -

I have a video that I'm trying to download that has a non-uniform pixel ratio.  When youtube-dl (great product, btw) finishes the download, it tries to use ffmpeg to correct this problem.  Unfortunately, this is resulting in the following error:

[download] Destination: test.mp4
[download] 100% of 15.44MiB in 00:00
[ffmpeg] Fixing aspect ratio in "test.mp4"
ERROR: Unrecognized option 'c'

Is there a way to tell youtube-dl not to worry about fixing the aspect ratio problem?

Thanks!

**Comment by dstftw** [comment]
Update ffmpeg or pass `--fixup warn`.

**Comment by a3leggeddog** [comment]
Thank you for such a prompt reply!  I just found that switch in the docs as well - missed it on my first read through.

**Comment by dstftw** [comment]
I'd still suggest you to update ffmpeg as you may encounter similar problems further, e.g. with bestvideo+bestaudio muxing.

**Comment by a3leggeddog** [comment]
ok, will do.  Thank you.

**Comment by fkbreitl** [comment]
Hello, I have the same problem. I want to keep my audio and video streams separate for audio only players. I can use the `-k` option to prevent deletion of the files but `--fixup warn` or `--fixup never` doesn't prevent the muxing of the stream. How can I stop this?
