### ISSUE TITLE
ERROR: Unable to extract redirect location

### ISSUE THREAD

**Issue by vladosfi** [rg3/youtube-dl#5967]
Since last update of youtube-dl I can't download clips from vbox7.com

Current youtube-dl version 2015.06.04.1

youtube-dl  "http://vbox7.com/play:012aa1eecc" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://vbox7.com/play:012aa1eecc', u'-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-59742-gd9481dc
[debug] Proxy map: {}
[Vbox7] 012aa1eecc: Downloading webpage
ERROR: Unable to extract redirect location; please report this issue on https://yt-dl.org/bug . Make
 sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl w
ith the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 650, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\vbox7.pyo", line 31, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 555, in _search_regex
RegexNotFoundError: Unable to extract redirect location; please report this issue on https://yt-dl.o
rg/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call
 youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Thanks for the report. vbox7 support is now fixed.

**Comment by vladosfi** [comment]
Thanks for response but error steel exist!
c:\youtube-dl  "http://vbox7.com/play:012aa1eecc" -v

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://vbox7.com/play:012aa1eecc', u'-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-59742-gd9481dc
[debug] Proxy map: {}
[Vbox7] 012aa1eecc: Downloading webpage
ERROR: Unable to extract redirect location; please report this issue on https://yt-dl.org/bug . Make
 sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl w
ith the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 650, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\vbox7.pyo", line 31, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 555, in _search_regex
RegexNotFoundError: Unable to extract redirect location; please report this issue on https://yt-dl.o
rg/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call
 youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
@vladosfi it will be incorporated in the next version.
