### ISSUE TITLE
Only flv is available on xvideos

### ISSUE THREAD

**Issue by tpimh** [rg3/youtube-dl#5968]
Actually, there are also high and low quality mp4 for mobile devices.

Here are the links:
```sh
curl 'xvideosurl' -H 'User-Agent: Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19' | grep mp4
```
Hope, this helps.

**Comment by yan12125** [comment]
Thanks for the suggestion and the code snippet. I've adopted your approach in youtube-dl and formats found on Android will be available in the next version.
