### ISSUE TITLE
Vimeo embeds in Tumblr fail with regex error (NSFW link)

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#5969]
vxbinaca@workstation/~/test$ youtube-dl --verbose http://camdamage.tumblr.com/post/98846056295/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://camdamage.tumblr.com/post/98846056295/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.9 - Linux-3.19.0-18-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[Tumblr] 98846056295: Downloading webpage
ERROR: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tumblr.py", line 60, in _real_extract
    webpage, 'iframe url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Thanks for the report. Vimeo embeds on tumblr.com will be supported in the next version.

**Comment by vxbinaca** [comment]
@yan12125 this problem is still creeping up please re-open

vxbinaca@workstation/~/git/tumblr-utils/tanyadakin/media$ youtube-dl --verbose  http://tanyadakin.tumblr.com/post/83508544455/tsurufoto-fish-without-a-bicycle-tanya-dakin
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://tanyadakin.tumblr.com/post/83508544455/tsurufoto-fish-without-a-bicycle-tanya-dakin']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.9 - Linux-3.19.0-21-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[Tumblr] 83508544455: Downloading webpage
ERROR: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/tumblr.py", line 65, in _real_extract
    webpage, 'iframe url')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
It's not yet released.

**Comment by vxbinaca** [comment]
Yeah I noticed that and removed the comment.
