### ISSUE TITLE
Can't find my configuration file

### ISSUE THREAD

**Issue by ATM05F3AR** [rg3/youtube-dl#5972]
I want to add some default params and can't locate the config.txt or .conf files in the folders mentioned. :/ 
Do I need to create a config file?

**Comment by dstftw** [comment]
Have you read [FAQ](https://github.com/rg3/youtube-dl#configuration)?

**Comment by ATM05F3AR** [comment]
Dear god. I thought they'd be empty files and I'd have to add params. God damn it I misunderstood the FAQ. Sorry. :/
