### ISSUE TITLE
New youtube video formats available

### ISSUE THREAD

**Issue by sudovijay** [rg3/youtube-dl#5979]
Just notice two new videos formats ! ID =  78 , 59
both look same though. codec info below ! 

Stream 0
  Type: Video
  Codec: H264 - MPEG-4 AVC (part 10) (avc1)
  Resolution: 854x480
  Frame rate: 23.976024
  Decoded format: Planar 4:2:0 YUV

Stream 1
  Type: Audio
  Codec: MPEG AAC Audio (mp4a)
  Channels: Stereo
  Sample rate: 44100 Hz

Even 141 is back which seem missing from recent videos .

Here is the video - https://www.youtube.com/watch?v=a23GO0NXOtg

**Comment by dstftw** [comment]
Thanks for the report. itags 59 and 78 will be recognized in the next version.
