### ISSUE TITLE
Windows build not working on windows xp

### ISSUE THREAD

**Issue by derekkepler** [rg3/youtube-dl#598]
Hello, 

I downloaded the windows build from here:

http://rg3.github.com/youtube-dl/windows.html

It works perfectly on Windows7 but not on Windows XP.  I made sure Python 3.3 is installed on my xp machine.  When I launch (double click) the "youtube-dl" exe file I get the following error:

"This application has failed to start because the application configuration is incorrect".  

When I try to use the command line "youtube-dl "AnyYouTubeUrl"" I get:
"The system cannot execute the specified program"

What am I missing?

Thanks,
Derek

**Comment by kkcosmo** [comment]
I can confirm that I just received the same error message on windows xp (with the last set of updates available). Installing python 2.7 fixed it.
