### ISSUE TITLE
Unable to download from france tv info 13h15

### ISSUE THREAD

**Issue by javierpbb** [rg3/youtube-dl#5981]
Hi

This is the output.

javier@JavUBU:~/temp$ youtube-dl http://www.francetvinfo.fr/replay-magazine/france-2/13h15/13h15-du-dimanche-14-juin-2015_940715.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.francetvinfo.fr/replay-magazine/france-2/13h15/13h15-du-dimanche-14-juin-2015_940715.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.9 - Linux-3.19.0-20-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[francetvinfo.fr] 13h15-du-dimanche-14-juin-2015_940715: Downloading webpage
[francetvinfo.fr] 123895164: Downloading video JSON
[francetvinfo.fr] 123895164: Downloading f4m manifest token
[francetvinfo.fr] 123895164: Downloading f4m manifest
ERROR: Unable to download f4m manifest: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1712, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
This issue will be fixed in the next version. Thanks for the report.

**Comment by javierpbb** [comment]
Thanks for your great job !
