### ISSUE TITLE
youtube-dl: error: no such option: --metadata-from-title

### ISSUE THREAD

**Issue by petercz1** [rg3/youtube-dl#5986]
I have the above error. Full line is as follows:

youtube-dl --extract-audio --audio-format mp3 --ignore-errors -o "%(title)s.%(ext)s" --add-metadata --metadata-from-title "%(artist)s - %(title)s" URL

I've also tried it stripped back to:

youtube-dl --add-metadata --metadata-from-title "%(artist)s - %(title)s" URL

but with no luck. Current version of youtube-dl is 2015.02.28 running on Ubuntu Mate 15.04

It works if I leave out the --metadata-from-title option.

Any ideas what I could be doing wrong?

PC

**Comment by yan12125** [comment]
This option is added since March 15th (#5125). Please update your copy of youtube-dl. The [update instructions](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl) may help.

**Comment by petercz1** [comment]
Ok, just uninstalled youtube-dl and sudo apt-get install youtube-dl installs version 2015.02.28 as before.

Sudo apt-get upgrade youtube-dl says:

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

I still get the same error:

youtube-dl: error: no such option: --metadata-from-title

Any ideas? All help much appreciated...

**Comment by petercz1** [comment]
Aha! ok, uninstalled youtube-dl, reinstalled using:

sudo curl https://yt-dl.org/latest/youtube-dl -o /usr/bin/youtube-dl

but note the removal of /local/, and then:

sudo chmod a+rx /usr/bin/youtube-dl

again removing /local/, and it now works!
