### ISSUE TITLE
On removed tumblr iframe just 404, not false positive bug to STDOUT

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#5990]
You might want to also do this for other sites, because it's filling my output with bugs that aren't bugs just 404s. That first '''WARNING''' message before the first '''ERROR''' and then process stop would have sufficed.

youtube-dl --verbose http://taintedkayla.tumblr.com/posts/1133366857
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://taintedkayla.tumblr.com/posts/1133366857']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.9 - Linux-3.19.0-20-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 1133366857: Requesting header
WARNING: Could not send HEAD request to http://taintedkayla.tumblr.com/posts/1133366857: HTTP Error 404: Not Found
[generic] 1133366857: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by vxbinaca** [comment]
IE this isn't a youtube-dl problem but a site problem and shouldn't generate a bug report.

**Comment by yan12125** [comment]
Some websites responds a 404 for wrong input parameters. In such cases it's really youtube-dl's problem, for example #4281. There's no simple way to determine whether 404 is simply NOT FOUND or something different. As a result, keeping reporting 404 is reasonable.

I'm closing this ticket as I think there's nothing need to be changed in youtube-dl.
