### ISSUE TITLE
Zad-dl a simple DIY downloader for Ubuntu using Youtube-dl

### ISSUE THREAD

**Issue by pandavan** [rg3/youtube-dl#5999]
[Zad-dl](https://github.com/pandavan/Zad-dl) is a simple DIY downloader bash script for Ubuntu distros which uses Youtube-dl engine. This post is written in-order to publicize the **Zad-dl** app and to find supporters and contributors for the improvement of the app.

regards
Pandavan

**Comment by dstftw** [comment]
Offtopic.
