### ISSUE TITLE
youtube-dl is returning format links that are not working properly for YouTube video

### ISSUE THREAD

**Issue by bartekrutkowski** [rg3/youtube-dl#6004]
Hi,
I using youtube-dl as a library in my own Python code (instead of standalone application) and I've issue with particular YouTube link:

https://www.youtube.com/watch?v=WOFk0PpG1EA

For some reason I am getting video formats links (using the extractor.extract_info('https://www.youtube.com/watch?v=WOFk0PpG1EA') method) but they're not usable: when they're being pasted into browser, the page is not rendering any player and is just blank white.

What could be the issue and how to detect it from the youtube-dl level?

**Comment by dstftw** [comment]
Do you test final download URLs from the same machine/IP? Can you download with youtube-dl itself?

**Comment by bartekrutkowski** [comment]
No, I am not testing the URL's from the same machine, since its my web application on a server that generates the links for me, and I am using them from my desktop machine, so obviously, the IP's differ. However, its a first case when I have such issues, is there a way to detect such videos using youtube-dl so that my web application would behave differently when it spots them?

**Comment by dstftw** [comment]
Can't tell you for sure, but from my experience those are videos with `gcr=<two-letter country code>` in final URL. You may also want to read [this](https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-webbrowser).

**Comment by bartekrutkowski** [comment]
Does that 'gcr' thing applies to all extractors or is it a YouTube specific thing?

**Comment by dstftw** [comment]
youtube-dl does not modify final URLs, so that's solely YouTube thing.
