### ISSUE TITLE
Add support for authentication on viki.com and dramafever.com

### ISSUE THREAD

**Issue by tblogger** [rg3/youtube-dl#6005]
Hello,
I passed -u 'email address' -p 'password' for Viki site,but it did not worked ,for example with premium account its not fetching 720p videos,

Can you make it possible on viki and Dramafever site?

**Comment by dstftw** [comment]
Currently, authentication is not supported for these sites. AFAIK, no one of core developers has a premium.
Next time create a separate issue for each site.

**Comment by tblogger** [comment]
IF I give premium?

**Comment by dstftw** [comment]
Probably, default account would be enough to implement authentication.

**Comment by tblogger** [comment]
ok, I have Checked the Code of your viki.com plugin. but I dont know python.
I am trying to generate signature in PHP ,can your please tell a bit more details.
the API docs says ,we need to use official App to use their api.
so i see you are using Official App ID for api,
but I dont understand what you have done with _APP_SECRET variable

Please Tell more?

**Comment by dstftw** [comment]
@tblogger could you test with premium videos?

**Comment by tblogger** [comment]
Hi,
youtube-dl --username abcs@gmail.com --password xxxxx -F  http://www.viki.com/videos/1067704v-the-crossing-hero-episode-1

Its Listing upto 480p , Premium Account will list 720p too.

**Comment by dstftw** [comment]
Note that you should test with code from repository not with latest released version. [Download](https://github.com/rg3/youtube-dl/archive/master.zip), unpack and run `python -m youtube_dl --username abcs@gmail.com --password xxxxx -F http://www.viki.com/videos/1067704v-the-crossing-hero-episode-1`. You'll need python installed.

**Comment by tblogger** [comment]
/usr/bin/python: youtube_dl is a package and cannot be directly executed

**Comment by dstftw** [comment]
What's python version, 2.6? Try `python youtube_dl/__main__.py --username abcs@gmail.com --password xxxxx -F http://www.viki.com/videos/1067704v-the-crossing-hero-episode-1`.

**Comment by dstftw** [comment]
Not it should work.

**Comment by tblogger** [comment]
http://postimg.org/image/qzt0hwehl/

I have viki.py from here,still
My Python Version 2.6.6

**Comment by dstftw** [comment]
@tblogger redownload sources to include 16d6973 and it will work.

**Comment by tblogger** [comment]
Hello,
It worked,thank you, my Problem Was I already Had youtube-dl installed with pip install , so python was not using My Current Directory youtube-dl.

**Comment by dstftw** [comment]
@tblogger can you check dramafever premium as well?
