### ISSUE TITLE
BBC WARNING: unable to extract description

### ISSUE THREAD

**Issue by kg117** [rg3/youtube-dl#6006]
E:\Downloader>youtube-dl -U
youtube-dl is up-to-date (2015.06.15)

E:\Downloader>youtube-dl --verbose http://www.bbc.co.uk/iplayer/episode/b05zmgwn
/royal-academy-summer-exhibition
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.bbc.co.uk/iplayer/episode
/b05zmgwn/royal-academy-summer-exhibition']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] b05zmgwn: Downloading video page
[bbc.co.uk] b05zmgw1: Downloading media selection XML
WARNING: unable to extract description; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[debug] Invoking downloader on u'rtmp://iplayertokfs.fplive.net/iplayertok?token
=c3RhcnRfdGltZT0yMDE1MDYxNzE4NTEwNiZlbmRfdGltZT0yMDE1MDYxNzIyNTEwNiZkaWdlc3Q9ODl
mMjdjOTQ5OGU0OGJmZDQwNTlmODEwMGMxMGVhZjI='
[download] Destination: Royal Academy Summer Exhibition-b05zmgw1.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmp://iplayertokfs.fplive
.net/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDYxNzE4NTEwNiZlbmRfdGltZT0yMDE1MDYxNz
IyNTEwNiZkaWdlc3Q9ODlmMjdjOTQ5OGU0OGJmZDQwNTlmODEwMGMxMGVhZjI=' -o 'Royal Academ
y Summer Exhibition-b05zmgw1.flv.part' --swfVfy http://www.bbc.co.uk/emp/release
s/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf --pageUrl http://www
.bbc.co.uk --app 'iplayertok?token=c3RhcnRfdGltZT0yMDE1MDYxNzE4NTEwNiZlbmRfdGltZ
T0yMDE1MDYxNzIyNTEwNiZkaWdlc3Q9ODlmMjdjOTQ5OGU0OGJmZDQwNTlmODEwMGMxMGVhZjI=' --p
laypath mp4:3200kbps/modav/bUnknown-8f8c78ad-acb6-47a1-af12-99efa8f24672_b05zmgw
1_1434157197244 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license
: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Parsed app     : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDYxNzE4
NTEwNiZlbmRfdGltZT0yMDE1MDYxNzIyNTEwNiZkaWdlc3Q9ODlmMjdjOTQ5OGU0OGJmZDQwNTlmODEw
MGMxMGVhZjI=
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:3200kbps/modav/bUnknown-8f8c78ad-acb6-47a1-af12
-99efa8f24672_b05zmgw1_1434157197244
[rtmpdump] DEBUG: tcUrl    : rtmp://iplayertokfs.fplive.net:1935/iplayertok?toke
n=c3RhcnRfdGltZT0yMDE1MDYxNzE4NTEwNiZlbmRfdGltZT0yMDE1MDYxNzIyNTEwNiZkaWdlc3Q9OD
lmMjdjOTQ5OGU0OGJmZDQwNTlmODEwMGMxMGVhZjI=
[rtmpdump] DEBUG: swfUrl   : http://www.bbc.co.uk/emp/releases/iplayer/revisions
/617463_618125_4/617463_618125_4_emp.swf
[rtmpdump] DEBUG: pageUrl  : http://www.bbc.co.uk
[rtmpdump] DEBUG: app      : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDYxNzE4NTEwNi
ZlbmRfdGltZT0yMDE1MDYxNzIyNTEwNiZkaWdlc3Q9ODlmMjdjOTQ5OGU0OGJmZDQwNTlmODEwMGMxMG
VhZjI=
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: b6 74 7f 89 f9 ec 6a 60 c1 a4 b5 8b b1 18 b0 fa
[rtmpdump] DEBUG: 65 18 86 24 c2 8a 1a a3 2f 72 0f 0b 80 59 dd 7f
[rtmpdump] DEBUG: SWFSize  : 595316
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 03
[rtmpdump] DEBUG: HandShake: Client digest offset: 53
[rtmpdump] DEBUG: HandShake: Initial client digest:
[rtmpdump] DEBUG: c8 ae 55 91 84 43 1a 37 53 12 3f 6d de 3a 2b f5
[rtmpdump] DEBUG: 9f 75 d4 3b f1 f5 d0 b1 60 9d ae 6b 99 e9 1c 62
[rtmpdump] DEBUG: HandShake: Type Answer   : 03
[rtmpdump] DEBUG: HandShake: Server Uptime : 1065708830
[rtmpdump] DEBUG: HandShake: FMS Version   : 4.5.3.1
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server di
gest:
[rtmpdump] DEBUG: f9 c6 65 5b 3f 63 bf 4f b6 5b 27 1f 68 9b 34 6e
[rtmpdump] DEBUG: fc 19 b5 75 19 f2 d0 b5 02 b6 c5 a8 7a 24 ed 63
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: 44 33 95 ab 08 e2 dd 08 0d 89 68 d4 e0 20 ed cb
[rtmpdump] DEBUG: 64 f1 17 e2 d7 99 12 39 17 b1 39 11 db 67 e8 8c
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: 4d e6 25 e1 20 d4 89 5d f7 fa e3 9b 4b b0 67 b5
[rtmpdump] DEBUG: 85 ce d7 24 de bf 63 c0 ca 2c 3c 1f 7e 3a ce 19
[rtmpdump] DEBUG: HandShake: Digest key:
[rtmpdump] DEBUG: b0 17 40 92 ba a9 9c 91 d4 69 86 fc 08 e4 3d 03
[rtmpdump] DEBUG: eb 5c a6 44 a3 75 5e aa 47 71 fc aa 7d f4 ad 86
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: 4d e6 25 e1 20 d4 89 5d f7 fa e3 9b 4b b0 67 b5
[rtmpdump] DEBUG: 85 ce d7 24 de bf 63 c0 ca 2c 3c 1f 7e 3a ce 19
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 2500000
[rtmpdump] DEBUG: HandleClientBW: client BW = 2500000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 16384
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 240 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:  FMS/4,5,3,101>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:  255.00>
[rtmpdump] DEBUG: Property: <Name:               mode, NUMBER:  1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetConnection.Co
nnect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Connection succe
eded.>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:  0.00>
[rtmpdump] DEBUG: Property: <Name:               data, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            version, STRING:  4,5,3,101>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 21 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWDone>
[rtmpdump] DEBUG: Invoking _checkbw
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: mp4:3200kbps/m
odav/bUnknown-8f8c78ad-acb6-47a1-af12-99efa8f24672_b05zmgw1_1434157197244
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 16419 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 32803 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 4, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream IsRecorded 1
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 16384
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 0, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream Begin 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 316 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetStream.Play.R
eset>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Playing and rese
tting 3200kbps/modav/bUnknown-8f8c78ad-acb6-47a1-af12-99efa8f24672_b05zmgw1_1434
157197244.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:  3200kbps/modav/b
Unknown-8f8c78ad-acb6-47a1-af12-99efa8f24672_b05zmgw1_1434157197244.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:  rAAYgwuA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Reset
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 310 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetStream.Play.S
tart>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Started playing
3200kbps/modav/bUnknown-8f8c78ad-acb6-47a1-af12-99efa8f24672_b05zmgw1_1434157197
244.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:  3200kbps/modav/b
Unknown-8f8c78ad-acb6-47a1-af12-99efa8f24672_b05zmgw1_1434157197244.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:  rAAYgwuA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Start
[rtmpdump] Starting download at: 0.000 kB
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 24 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 44 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetStream.Data.S
tart>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 494 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:  3552.28>
[rtmpdump] DEBUG: Property: <Name:       moovPosition, NUMBER:  36.00>
[rtmpdump] DEBUG: Property: <Name:              width, NUMBER:  1280.00>
[rtmpdump] DEBUG: Property: <Name:             height, NUMBER:  720.00>
[rtmpdump] DEBUG: Property: <Name:       videocodecid, STRING:  avc1>
[rtmpdump] DEBUG: Property: <Name:       audiocodecid, STRING:  mp4a>
[rtmpdump] DEBUG: Property: <Name:         avcprofile, NUMBER:  100.00>
[rtmpdump] DEBUG: Property: <Name:           avclevel, NUMBER:  41.00>
[rtmpdump] DEBUG: Property: <Name:             aacaot, NUMBER:  2.00>
[rtmpdump] DEBUG: Property: <Name:     videoframerate, NUMBER:  25.00>
[rtmpdump] DEBUG: Property: <Name:    audiosamplerate, NUMBER:  48000.00>
[rtmpdump] DEBUG: Property: <Name:      audiochannels, NUMBER:  2.00>
[rtmpdump] DEBUG: Property: <Name:          trackinfo, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:  88807000.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:  25000.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:  und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:  avc1>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:  170509312.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:  48000.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:  und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:  mp4a>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] INFO: Metadata:
[rtmpdump] INFO:   duration              3552.28
[rtmpdump] INFO:   moovPosition          36.00
[rtmpdump] INFO:   width                 1280.00
[rtmpdump] INFO:   height                720.00
[rtmpdump] INFO:   videocodecid          avc1
[rtmpdump] INFO:   audiocodecid          mp4a
[rtmpdump] INFO:   avcprofile            100.00
[rtmpdump] INFO:   avclevel              41.00
[rtmpdump] INFO:   aacaot                2.00
[rtmpdump] INFO:   videoframerate        25.00
[rtmpdump] INFO:   audiosamplerate       48000.00
[rtmpdump] INFO:   audiochannels         2.00
[rtmpdump] INFO: trackinfo:
[rtmpdump] INFO:   length                88807000.00
[rtmpdump] INFO:   timescale             25000.00
[rtmpdump] INFO:   language              und
[rtmpdump] INFO: sampledescription:
[rtmpdump] INFO:   sampletype            avc1
[rtmpdump] INFO:   length                170509312.00
[rtmpdump] INFO:   timescale             48000.00
[rtmpdump] INFO:   language              und
[rtmpdump] INFO: sampledescription:
[rtmpdump] INFO:   sampletype            mp4a
[download] 1.13KiB at Unknown speed (00:02)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 49187 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download] 577.21KiB at Unknown speed (00:03)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 40 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwdone>
[download]  83.4% of ~987.06MiB at  2.37MiB/s ETA 01:08
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 6, len: 6
[rtmpdump] DEBUG: HandleCtrl, Ping 1065988359
[rtmpdump] DEBUG: sending ctrl. type: 0x0007
[download]  99.7% of ~1022.71MiB at  2.38MiB/s ETA 00:01
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 102 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetStream.Play.C
omplete>
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  status>
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:  425.00>
[rtmpdump] DEBUG: Property: <Name:              bytes, NUMBER:  1069687437.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 1, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream EOF 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 320 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetStream.Play.S
top>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Stopped playing
3200kbps/modav/bUnknown-8f8c78ad-acb6-47a1-af12-99efa8f24672_b05zmgw1_1434157197
244.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:  3200kbps/modav/b
Unknown-8f8c78ad-acb6-47a1-af12-99efa8f24672_b05zmgw1_1434157197244.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:  rAAYgwuA>
[rtmpdump] DEBUG: Property: <Name:             reason, STRING:  >
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Stop
[rtmpdump] DEBUG: Invoking deleteStream
[rtmpdump] DEBUG: Got Play.Complete or Play.Stop from server. Assuming stream is
 complete
[download]  99.9% of ~1021.15MiB at  2.38MiB/s ETA 00:00
[rtmpdump] DEBUG: RTMP_Read returned: 0
[rtmpdump] Download complete
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 1069686861 bytes
[download] 100% of 1020.13MiB

**Comment by yan12125** [comment]
Thanks for the report. Descriptions will be extracted correctly in the next version.
