### ISSUE TITLE
Abort  youtube-dl.exe?

### ISSUE THREAD

**Issue by PeterPanino** [rg3/youtube-dl#6011]
I use youtube-dl.exe 2015.06.15 in Windows. Is there a way to ABORT the running youtube-dl.exe? (maybe after having cleaned up the already downloaded part of the file? I use --no-part).

Or is it safe to just KILL it?

**Comment by jaimeMF** [comment]
You can kill it, but the files aren't deleted and since you use `--no-part` the download cannot be resumed.

**Comment by PeterPanino** [comment]
Wouldn't it be useful to implement something which allows to communicate with youtube-dl.exe? So I could send a message to youtube-dl.exe and tell him: Please abort the current download and cleanup. Or, when not using --no-part: Please pause the download. Or: Please resume the download.

**Comment by jaimeMF** [comment]
I don't think we are going to implement it directly in youtube-dl because it could complicate too much the tool, but we may consider a pull request or someone could use the python `youtube_dl` module to implement it in a separate program.
