### ISSUE TITLE
ComCarCoff (Comedians in Cars Getting Coffee) Fails

### ISSUE THREAD

**Issue by bonacker** [rg3/youtube-dl#6014]
Downloading any (I tried several) ep. of "Comedians in Cars Getting Coffee" fails. using the latest Windows build. Here is the log:
-------------------------------------------

C:\Progra~1\youtubedl>youtube-dl -v http://comediansincarsgettingcoffee.com
/jim-carrey-jim-carrey-we-love-breathing-what-youre-burning-baby
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://comediansincarsgettingcoffee.com/jim-carrey-jim-carrey-we-love-breathing-what-youre-burning-baby']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-44601-gcb3591e, ffprobe N-44601-gcb3591e, rtmpdump 2.3
[debug] Proxy map: {}
ffmpeg version N-44601-gcb3591e Copyright (c) 2000-2012 the FFmpeg developers built on Sep 19 2012 16:29:47 with gcc 4.7.1 (GCC)
 configuration: --disable-static --enable-shared --enable-gpl --enable-version3
 --disable-pthreads --enable-runtime-cpudetect --enable-avisynth --enable-bzlib --enable-frei0r --enable-libass --enable-libcelt --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-libnut --enable-libopenjpeg --enable-librtmp --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libutvideo --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      51. 73.101 / 51. 73.101
  libavcodec     54. 56.100 / 54. 56.100
  libavformat    54. 27.101 / 54. 27.101
  libavdevice    54.  2.100 / 54.  2.100
  libavfilter     3. 16.104 /  3. 16.104
  libswscale      2.  1.101 /  2.  1.101
  libswresample   0. 15.100 /  0. 15.100
  libpostproc    52.  0.100 / 52.  0.100
Unable to open key file https://content-ausc1.uplynk.com/check2?b=a24a6c5942a94d
71934ceb71293751c2&v=fe8d2f70bde54206a15fec0f55c5f28b&r=g&pbs=f50b393271e440b5ae
5e1bb853d102f8
[hls,applehttp @ 0003d720] Error when loading first segment 'http://stg-ec-ore-u
.uplynk.com/slices/a24/4f59ea65df184a2580ad8fc80d3eaa32/a24a6c5942a94d71934ceb71
293751c2/G00000000.ts?pbs=f50b393271e440b5ae5e1bb853d102f8'
http://content-ausc1.uplynk.com/fe8d2f70bde54206a15fec0f55c5f28b/g.m3u8?ad=crack
le_live&pbs=f50b393271e440b5ae5e1bb853d102f8: Invalid data found when processing
 input
ERROR: ffmpeg exited with code 1
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 405, in main
  File "youtube_dl\__init__.pyo", line 395, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1502, in download
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 707, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1173, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1435, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1377, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\hls.pyo", line 50, in real_download
  File "youtube_dl\downloader\common.pyo", line 155, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 528, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 490, in trouble
----------------------------------------------

**Comment by jaimeMF** [comment]
It works for me. From the output it seems that your copy of ffmpeg is from 2012, you should try to update it.
