### ISSUE TITLE
[Error 10061]

### ISSUE THREAD

**Issue by shubhamgupta1404** [rg3/youtube-dl#6020]
C:\Users\_________\Downloads>youtube-dl --verbose "http://www.youtube.com/watch?v=
q5nvr__J8bQ"

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.youtube.com/watch?v=q5nvr
__J8bQ']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {'http': 'http://localhost:9614', u'https': 'http://localhost
:9614'}
[youtube] q5nvr__J8bQ: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 10061] No connection co
uld be made because the target machine actively refused it> (caused by URLError(
error(10061, 'No connection could be made because the target machine actively re
fused it'),))
  File "youtube_dl\extractor\common.pyo", line 312, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1730, in urlopen
  File "urllib2.pyo", line 404, in open
  File "urllib2.pyo", line 422, in _open
  File "urllib2.pyo", line 382, in _call_chain
  File "youtube_dl\utils.pyo", line 713, in https_open
  File "urllib2.pyo", line 1184, in do_open

Why is it giving this error and why is it downloading the webpage?

**Comment by yan12125** [comment]
What's the proxy software at localhost:9614?

**Comment by shubhamgupta1404** [comment]
I don't know how to check that!!

**Comment by yan12125** [comment]
Are you using [Xtreme Download Manager](http://sourceforge.net/projects/xdman/)? Seems it's using port 9614.

**Comment by shubhamgupta1404** [comment]
I removed the proxy from my internet settings.
It's working now.
Thank You

**Comment by yan12125** [comment]
If you can watch videos in the browser with the original proxy settings, it should be possible to download them via youtube-dl. I'll examine the situation.

**Comment by yan12125** [comment]
Seems Xtreme Download Manager's proxy does not handle HTTPS connections properly. HTTPS is used extensively in youtube.com. Before Xtreme Download Manager implements full HTTPS support, there's nothing we can do in youtube-dl. Anyway, thanks for providing a workaround for the problem. Another possible workaround can be:
```
youtube-dl --verbose --proxy "" "http://www.youtube.com/watch?v=q5nvr__J8bQ"
```
Passing an empty string to ```--proxy``` makes youtube-dl ignore system proxy settings.

**Comment by shubhamgupta1404** [comment]
Great help.
Thanks
