### ISSUE TITLE
connection timeout issue. 

### ISSUE THREAD

**Issue by martingg88** [rg3/youtube-dl#6025]
what is timeout limit for youtube server. 

What is the possible way to prevent timeout for sending multiple simultaneous connection to youtube server for downloading a video?

**Comment by jaimeMF** [comment]
> what is timeout limit for youtube server. 

I don't know

> What is the possible way to prevent timeout for sending multiple simultaneous connection to youtube server for downloading a video?

If you are getting timeouts because you are downloading too many videos at the same time, you should avoid doing that. For example you can call youtube-dl with more that one URL and the will be downloaded in sequence.
