### ISSUE TITLE
youtube-dl closes on error before completing YouTube playlist

### ISSUE THREAD

**Issue by bryc** [rg3/youtube-dl#6028]
[download] Downloading video 32 of 106
    [youtube] gaAkuN-59Ls: Downloading webpage
    [youtube] gaAkuN-59Ls: Downloading video info webpage
    ERROR: gaAkuN-59Ls: YouTube said: This video contains content from x, who has
    blocked it in your country on copyright grounds.
    
    R:\>

This is the last thing I see - shouldn't it continue to the next in sequence rather than quit on this error? It works amazingly aside from this bug.

**Comment by dstftw** [comment]
This is not a bug. This is expected behavior. You can pass `-i` to ignore errors.
