### ISSUE TITLE
Can't download Youtube mix playlists

### ISSUE THREAD

**Issue by redanon** [rg3/youtube-dl#6031]
youtube-dl only downloads the 1st video of the youtube mix playlist , i was trying to download various mix playlists, but it keeps downloading only 1st video. 
here is the command 
youtube-dl -v -f 141 https://www.youtube.com/watch?v=51iquRYKPbs&list=RD51iquRYKPbs#t=0 
 [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'141', u'https://www.youtube.com/watch?v=51iquRYKPbs']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.6 - Linux-3.13.0-44-generic-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg 1.2.6-7, ffprobe 1.2.6-7, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 51iquRYKPbs: Downloading webpage
[youtube] 51iquRYKPbs: Extracting video information
[youtube] {22} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {43} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {18} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {5} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {36} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {17} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {137} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {248} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {136} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {247} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {135} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {244} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {134} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {243} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {133} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {242} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {160} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {278} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {140} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {171} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {249} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {250} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] {251} signature length 45.41, html5 player en_US-vflnSSUZV
[youtube] 51iquRYKPbs: Downloading DASH manifest
[debug] Invoking downloader on 'https://r4---sn-a5m7ln7r.googlevideo.com/videoplayback?id=e758aab9160a3dbb&itag=141&source=youtube&requiressl=yes&ms=au&mv=m&mm=31&mn=sn-a5m7ln7r&pl=20&ratebypass=yes&mime=audio/mp4&gir=yes&clen=9041962&lmt=1432152579451425&dur=283.585&mt=1434795980&key=dg_yt0&sver=3&signature=953011A390B16D04DFC481EB3CC5FAA143405C51.3F46F428497837B3EC9E63B3572C7BC9E03995D6&upn=Kv9tJXX6j9Y&fexp=9405637,9407141,9407663,9408142,9408420,9408710,9409208,9410705,9413053,9413503,9415304,9415556,9416074,9416115,9416126,9416217,9416456,9416502,952640&ip=117.213.17.101&ipbits=0&expire=1434817656&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,mm,mn,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Linkin Park - The Catalyst (Official Video)-51iquRYKPbs.m4a has already been downloaded
[download] 100% of 8.62MiB
[ffmpeg] Correcting container in "Linkin Park - The Catalyst (Official Video)-51iquRYKPbs.m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'Linkin Park - The Catalyst (Official Video)-51iquRYKPbs.m4a' -c copy -f mp4 'Linkin Park - The Catalyst (Official Video)-51iquRYKPbs.temp.m4a'

**Comment by dstftw** [comment]
[You have to escape `&` or put the URL in quotes](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).
