### ISSUE TITLE
Site support request: xhampster embed URLs

### ISSUE THREAD

**Issue by woodenphone** [rg3/youtube-dl#6032]
While xhampster is listed as supported, this video URL format used by embedded videos from this site is not supported
Could support for this kind of link be added?

Embed style url:
"http://xhamster.com/xembed.php?video=3328539"

Video page associated with this video:
"http://xhamster.com/movies/3328539/pen_masturbation.html?embed=comments&openC#commentBox&prs=261a178c0ec669ad89ad6f0c681fef3f:manyakisart.tumblr.com:55854131:e10"

Console session of attempt to save this URL:

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>yout
ube-dl.exe --update
youtube-dl is up-to-date (2015.06.15)

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>yout
ube-dl.exe http://xhamster.com/xembed.php?video=3328539
[generic] xembed: Requesting header
WARNING: Falling back on generic information extractor.
[generic] xembed: Downloading webpage
[generic] xembed: Extracting information
ERROR: Unsupported URL: http://xhamster.com/xembed.php?video=3328539

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>yout
ube-dl.exe -v http://xhamster.com/xembed.php?video=3328539
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://xhamster.com/xembed.php?video=332853
9']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] xembed: Requesting header
WARNING: Falling back on generic information extractor.
[generic] xembed: Downloading webpage
[generic] xembed: Extracting information
ERROR: Unsupported URL: http://xhamster.com/xembed.php?video=3328539
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1020, in _real_extract
  File "youtube_dl\utils.pyo", line 1558, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 64, column 114
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 650, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\generic.pyo", line 1571, in _real_extract
UnsupportedError: Unsupported URL: http://xhamster.com/xembed.php?video=3328539

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>

**Comment by dstftw** [comment]
XHamster embeds wil be supported in the next vesrion. Thanks for the report.
