### ISSUE TITLE
error: Unable to extract video id 

### ISSUE THREAD

**Issue by luluprat** [rg3/youtube-dl#6034]
hello
i am triing to download this video from french tv, i did youtube-dl -U and i have pdating to version 2015.06.15 ...
but i get this error:
youtube-dl http://www.francetvinfo.fr/economie/entreprises/les-entreprises-familiales-le-secret-de-la-reussite_933271.html
[francetvinfo.fr] les-entreprises-familiales-le-secret-de-la-reussite_933271: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

any help would be apriciate.

**Comment by yan12125** [comment]
This article contains a video hosted on Dailymotion cloud, which is not supported yet.

**Comment by yan12125** [comment]
Alright, thanks for reporting it. This video will be supported in the next version.
