### ISSUE TITLE
--yes-playlist and -playlist not allowing me to download the fucking playlist -_-

### ISSUE THREAD

**Issue by xrosax** [rg3/youtube-dl#6035]
I would like to download a playlist but for some reason your awesome tool doesn't allow me to do so anymore like it used too :/ ..

same error "bullshit"

D:\Videos\Youtube\NSCOPE\FO3>youtube-dl -playlist "https://www.youtube.com/playl
ist?list=PL4ED6672C5FFA8006"
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: account username missing

D:\Videos\Youtube\NSCOPE\FO3>

Why do I need to do this now don't you have a default account setup
 for this so we don't have to do all this stuff thanks.

**Comment by dstftw** [comment]
There is no such option `playlist`, moreover options should start with double dash `--`.
To download playlist you don't need to pass any extra option just a playlist URL:
`youtube-dl "https://www.youtube.com/playlist?list=PL4ED6672C5FFA8006"`
