### ISSUE TITLE
Get rid of numbers besides song name?

### ISSUE THREAD

**Issue by NickWinston123** [rg3/youtube-dl#6036]
Not really a bug, but it causes a bit of annoyance.

Is there anyway to get youtube-dl to not put the numbers beside the track name?

for example; A downloaded song from sound cloud  would be exported like this " Renzy - Rain Cloud-123412312.mp3 ".

I would just like it better if it didn't have all the numbers beside it. Thank you in advance.
![screenshot 2015-06-20 12 11 44](https://cloud.githubusercontent.com/assets/11579042/8268082/8e0b758a-1745-11e5-9e7f-3ff03d63dd3b.png)

**Comment by dstftw** [comment]
Use [output template](https://github.com/rg3/youtube-dl#output-template), e.g. `-o "%(title)s.%(ext)s"`.

**Comment by NickWinston123** [comment]
@dstftw thanks again!
