### ISSUE TITLE
adobe TV extractor does not support this url, also add subtitle

### ISSUE THREAD

**Issue by xubuntu4iran** [rg3/youtube-dl#6039]
http://video.tv.adobe.com/v/2456/?atvwatermark=fals

**Comment by yan12125** [comment]
Where did you get this link? Is it an embedded video from another web page?

**Comment by yan12125** [comment]
I've added support of such videos. This functionality will be available in the next version. If you find some other webpage with embedded adobe videos and youtube-dl fails to detect it, feel free to open a new issue.

**Comment by xubuntu4iran** [comment]
'Where did you get this link?' here:
https://helpx.adobe.com/acrobat/how-to/new-experience-acrobat-dc.html?set=acrobat--get-started--essential-beginners

**Comment by yan12125** [comment]
Thanks.
