### ISSUE TITLE
How to download videos from newgrounds?

### ISSUE THREAD

**Issue by laichiaheng** [rg3/youtube-dl#6041]
I see that it is on the list, but how do I download the video on the site?

**Comment by yan12125** [comment]
That depends. Which operating system are you using? If you're using Windows, #5802 may help.

**Comment by laichiaheng** [comment]
@yan12125 I'm using Linux.

**Comment by yan12125** [comment]
Then simply open a terminal, and then type commands. For example:
```
username@hostname:~ $ youtube-dl "http://www.newgrounds.com/audio/listen/549479"
[Newgrounds] 549479: Downloading webpage
[download] Destination: B7 - BusMode-549479.mp3
[download] 100% of 4.35MiB in 00:03
```
If you're encountering other problems, feel free to open a new issue.
