### ISSUE TITLE
mkv error

### ISSUE THREAD

**Issue by TarekSalama** [rg3/youtube-dl#6044]
Hello,

I get this error while trying to download: "WARNING: Requested formats are incompatible for merge and will be merged into mkv"

The configuration file I'm currently using is: "-U --no-overwrites --no-cache-dir --restrict-filenames --ignore-errors --batch-file /Users/tareksalama/Desktop/batchvideos.txt -o /Users/tareksalama/Desktop/downloads/Youtube/%(uploader)s/%(title)s_%(uploader)s_%(id)s.%(ext)s"

When I removed ffmpeg from my system, the error didn't come back.

However, earlier I was having an issue where the best available video quality wouldn't download until someone on here told me that I needed to download ffmpeg.

I'd love to be able to download the best available quality which is usually mp4 too. I don't care much about the audio but it has to be there too.

**Comment by yan12125** [comment]
It's a WARNING rather than an ERROR. It just tells you the final file has a different format than what YouTube provides. If you can play the downloaded file, just ignore the warning.

**Comment by TarekSalama** [comment]
So if I want to download the highest possible video quality while retaining the mp4 extension output, what should I do?

**Comment by yan12125** [comment]
Could you paste the video link so that I or others can examine the situation in more details?

**Comment by TarekSalama** [comment]
I don't have a specific link at the moment but earlier on my Windows machine, some videos wouldn't download at the highest available quality until I was told that I have to download ffmpeg. So on my Mac machine, I downloaded ffmpeg in order not to have the previous issue however I ended up getting that warning in my first post. So I removed ffmpeg (on my Mac) and now videos are downloaded in mp4 again. So yea, what should I do in order for me to download the best video quality as well as in mp4 format? I want to avoid mkv or any non mp4 formats while having the best video quality possible.

**Comment by yan12125** [comment]
In general it's impossible. This warning indicates there's no way to preserve mp4 format as well as qualities.

**Comment by TarekSalama** [comment]
Okay so let's say I forced it to download the highest video quality, would I get a video without audio as an output? 

Generally speaking, what are the disadvantages of forcing it to download the highest video quality other than getting an undesired output format?

Do I need ffmpeg in order for me to get the best video quality?

**Comment by yan12125** [comment]
> would I get a video without audio as an output?

No, unless you specify ```-f bestvideo```

> what are the disadvantages of forcing it to download the highest video quality other than getting an undesired output format

I think no.

> Do I need ffmpeg in order for me to get the best video quality?

Yes. YouTube serves the best quality video and the best quality audio separately. youtube-dl needs to merge them into a single video+audio file. This step requires ffmpeg.
