### ISSUE TITLE
Conversion of m4a to vorbis with ffmpeg does not work.

### ISSUE THREAD

**Issue by ZeroTheSavior** [rg3/youtube-dl#6045]
This is the command I used. the three ffmpeg binaries are in the same folder.
```
youtube-dl.exe --restrict-filenames -o %(title)s.%(ext)s -f bestaudio --audio-format vorbis fWyVaX3L77I
```
I've tried it with multiple videos and they are still in m4a format instead of ogg vorbis.

**Comment by yan12125** [comment]
What you need is ```--recode-video```. For example:
```
youtube-dl --restrict-filenames -o "%(title)s.%(ext)s" -f bestaudio --recode-video ogg fWyVaX3L77I
```
Indeed the option name is somewhat misleading. Anyway it's used for multimedia format conversion.

**Comment by jaimeMF** [comment]
Or you could add `--extract-audio`, which tells youtube-dl to run the postprocessor.
