### ISSUE TITLE
If it's in the archive, I want it completely skipped over, I don't even want it to download the video info

### ISSUE THREAD

**Issue by imconcerned** [rg3/youtube-dl#6048]
I use --download-archive, and recently I've been having very odd problems with being able to comment out videos so that it completely ignores them in the batch list. I made a horribly inefficient bash script that iterates through the archive.txt and matches videos in batch.txt and comments the matching ones out. For some reason, though, it's not commenting them out anymore, when I try to download videos, I have about fifty of them that are already recorded in archive, so they weren't commented out. I wouldn't need to do this if I could "--download-archive-dont-even-bother-downloading-the-video-webpage-just-skip-over-it-completely". That would make my content-consuming lifestyle on this god awful connection a lot easier. This utility is great, though, and I'm glad I found it, and can use it at all.

**Comment by jaimeMF** [comment]
For a lot of services the video id  can't be know just by looking into the url and we have to download the webpages, note that if you pass playlist urls from YouTube it won't download the info for already downloaded videos. I don't think we are going to add that optimization, you should just remove the urls from the batch file.
