### ISSUE TITLE
Error with ffprobe after update

### ISSUE THREAD

**Issue by dspstudio** [rg3/youtube-dl#6049]
dsp@localhost:~/mp3$ youtube-dl -t --extract-audio --audio-format mp3 --audio-quality 256k --audio-quality 0 https://www.youtube.com/watch?v=9EnSqnccMyY
[youtube] 9EnSqnccMyY: Downloading webpage
[youtube] 9EnSqnccMyY: Extracting video information
[youtube] 9EnSqnccMyY: Downloading js player en_US-vflnSSUZV
[youtube] 9EnSqnccMyY: Downloading DASH manifest
[download] Icona Pop - Emergency (Official Video)-9EnSqnccMyY.webm has already been downloaded
[download] 100% of 2.92MiB
ERROR: WARNING: unable to obtain file audio codec with ffprobe
dsp@localhost:~/mp3$ which ffprobe
/usr/bin/ffprobe
avprobe version 0.8.6-4:0.8.6-0ubuntu0.12.04.1, Copyright (c) 2007-2013 the Libav developers
  built on Apr  2 2013 17:02:36 with gcc 4.6.3

**Comment by jaimeMF** [comment]
avprobe 0.8.6 is quite old, you should upgrade it.
Could you post the output of `avprobe -show_streams 'Icona Pop - Emergency (Official Video)-9EnSqnccMyY.webm'`?

**Comment by dspstudio** [comment]
dsp@localhost:~/mp3$ sudo avprobe -show_streams 'Icona Pop - Emergency (Official Video)-9EnSqnccMyY.webm'
avprobe version 0.8.6-4:0.8.6-0ubuntu0.12.04.1, Copyright (c) 2007-2013 the Libav developers
  built on Apr  2 2013 17:02:36 with gcc 4.6.3
[matroska,webm @ 0x20c39c0] Unknown entry 0x56AA
[matroska,webm @ 0x20c39c0] Unknown entry 0x56BB
[matroska,webm @ 0x20c39c0] Unknown/unsupported CodecID A_OPUS.
[matroska,webm @ 0x20c39c0] Unknown entry 0x75A2
[matroska,webm @ 0x20c39c0] decoding for stream 0 failed
[matroska,webm @ 0x20c39c0] Estimating duration from bitrate, this may be inaccurate
Icona Pop - Emergency (Official Video)-9EnSqnccMyY.webm: Operation not permitted

ill try to update

**Comment by jaimeMF** [comment]
It's probably fixed in the recent versions of avprobe.

NOTE: **don't run avprobe or youtube-dl as the root user**, even if we and the avprobe developer try to make them as secure as possible, it's still an unnecessary risk.
