### ISSUE TITLE
Update support for fax.net

### ISSUE THREAD

**Issue by htgoebel** [rg3/youtube-dl#6050]
#1582 adds support for URLs like http://www.faz.net/multimedia/videos/...

Please add support for URLs following these schemas, all pointing the same article:

- http://www.faz.net/aktuell/politik/berlin-gabriel-besteht-zerreissprobe-ueber-datenspeicherung-13659345.html.
- http://www.faz.net/berlin-gabriel-besteht-zerreissprobe-ueber-datenspeicherung-13659345.html
- http://www.faz.net/-13659345.html
- http://www.faz.net/aktuell/politik/-13659345.html
- http://www.faz.net/foobarblafasel-13659345.html

The same extractor can be used, it's only the `_VALID_URL` pattern that needs to be updated.

Thanks!

**Comment by dstftw** [comment]
This issue will be fixed in the next version. Thanks for the report.

**Comment by htgoebel** [comment]
Wow, this was a quick reaction :-)
