### ISSUE TITLE
_sort_formats return None

### ISSUE THREAD

**Issue by remitamine** [rg3/youtube-dl#6059]
i'm trying to create an extractor for google drive and also picasa videos i made a working version but when i use the _sort_formats method the extractor stop working.
this is happen because of _sort_formats return None.
in the code i put here i'm using the python sorted function but i think it's better to use the _sort_formats.
if i find a solution i will return to use _sort_formats and try to fork and do a pull request(i didn't do it before)
[Google Drive extractor](https://gist.github.com/remitamine/09cc70f2c3a05546048d)
[Picasa extractor](https://gist.github.com/remitamine/1e2462ae3c25272dff6f)

**Comment by dstftw** [comment]
`_sort_formats` is supposed to work inplace, so it returns nothing and modifies `formats` passed in.

**Comment by remitamine** [comment]
:+1:  thank you it works i didn't notice that
