### ISSUE TITLE
Unable to extract iframe 

### ISSUE THREAD

**Issue by matiasw** [rg3/youtube-dl#6063]
Hi,
using youtube-dl through mpv's ytdl_hook, I'm unable to play video directly from this blog post: http://videomapping.tumblr.com/post/122253957381/sydney-opera-house-lighting-the-sails-2015
The error is `ERROR: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`, so here I am, reporting.
The complete output:
<pre><code>youtube-dl --verbose http://videomapping.tumblr.com/post/122253957381/sydney-opera-house-lighting-the-sails-2015
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://videomapping.tumblr.com/post/122253957381/sydney-opera-house-lighting-the-sails-2015']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.10 - Linux-4.0.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, ffmpeg 2.7-1, ffprobe 2.7-1, rtmpdump 2.4
[debug] Proxy map: {}
[Tumblr] 122253957381: Downloading webpage
ERROR: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/tumblr.py", line 43, in _real_extract
    webpage, 'iframe url')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.</pre></code>
Playing the embedded video, https://vimeo.com/128974882 , directly through Vimeo works.

**Comment by yan12125** [comment]
It's already fixed in git (see #5969) but not included in latest release yet. Please wait patiently or try the [git tarball](https://github.com/rg3/youtube-dl/archive/master.zip).
