### ISSUE TITLE
Playlist download doesn't work

### ISSUE THREAD

**Issue by wavic** [rg3/youtube-dl#6065]
I want to download this playlist for example:
https://www.youtube.com/watch?v=JF_qBFlR2MI&list=PL1A2CSdiySGJd0LJRRSwQZbPZaDP0q67j&index=1

Youtube-dl downloads the first video but nothing else. I use this command:
youtube-dl --playlist-start 1 --playlist-end 9 https://www.youtube.com/watch?v=JF_qBFlR2MI&list=PL1A2CSdiySGJd0LJRRSwQZbPZaDP0q67j
also --yes-playlist instead --playlist-start and --playliststop options.

It downloads the first video and stops. Here is --verbose output:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--playlist-start', u'1', u'--playlist-end', u'9', u'https://www.youtube.com/watch?v=JF_qBFlR2MI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.6 - Linux-3.16.0-31-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] JF_qBFlR2MI: Downloading webpage
[youtube] JF_qBFlR2MI: Extracting video information
[youtube] JF_qBFlR2MI: Downloading DASH manifest
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Invoking downloader on u'https://r2---sn-cap1vv-nv4e.googlevideo.com/videoplayback?key=yt5&sver=3&mv=m&expire=1435154921&initcwndbps=2672500&upn=_wC1GF3hI2k&ratebypass=yes&source=youtube&signature=4C0CD9D2C73D5EC75FA96C6B54BC972DB6DBE099.98D61DC00BE712EF4F50134F4AFA40B7F62D9EC7&lmt=1413357683222235&fexp=9407141%2C9408142%2C9408420%2C9408710%2C9413503%2C9414764%2C9415304%2C9416126%2C9416456%2C952640&pcm2cms=yes&ipbits=0&id=o-AFS4bGc2o6a-dgW94IXlMpLL_D43D7X3hLx0pvPOaHGG&dur=647.302&mime=video%2Fmp4&requiressl=yes&ms=au&mt=1435133228&itag=22&pl=22&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ip=130.204.161.112&mm=31&mn=sn-cap1vv-nv4e'
[download] Python3 Beginner Tutorial 2 - Variables & Data Structures-JF_qBFlR2MI.mp4 has already been downloaded
[download] 100% of 27.25MiB

The avconv is not developing as I know.

**Comment by yan12125** [comment]
You need to enclose the url in double quotes. For example:
```
youtube-dl --playlist-start 1 --playlist-end 9 "https://www.youtube.co/watch?v=JF_qBFlR2MI&list=PL1A2CSdiySGJd0LJRRSwQZbPZaDP0q67j"
```
See [this FAQ](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for more information.

**Comment by wavic** [comment]
It works! Thank you.
I didn't expect that. There is no spaces in the URL.

**Comment by yan12125** [comment]
The key is '&'. It has special meanings in most shells.

**Comment by wavic** [comment]
Yes it has. Is youtube-dl a python? I need to learn how to get specified links from a page.

**Comment by yan12125** [comment]
> Is youtube-dl a python?

Yes.

**Comment by santosh** [comment]
Isn't there way to control video quality?

**Comment by yan12125** [comment]
@santosh I think your problem is different. Could you open a new issue and provide more details?
