### ISSUE TITLE
Youtube-DL says [avconv] outdated

### ISSUE THREAD

**Issue by TechAndNews** [rg3/youtube-dl#6070]
AskUbuntu Forum says to install [libav-tools] and [ffmpeg]. Did that, and it said [ffmpeg is already the newest version. libav-tools is already the newest version. 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.]

Even after that, [youtube-dl] still says: [WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.]

It's like this on all my Ubuntu-based Computers that have [youtube-dl] installed.

Also, am running latest version of [youtube-dl] by running [sudo youtube-dl -U]

**Comment by dstftw** [comment]
libav is outdated in Ubuntu repos at least for precise (12.04LTS) and trusty (14.04LTS) - 9.x and 8.x correspondingly.

**Comment by TechAndNews** [comment]
Thank You. I will look to update [libav] by adding a [ppa].
