### ISSUE TITLE
InfoQ extractor too restrictive

### ISSUE THREAD

**Issue by Dridi** [rg3/youtube-dl#6071]
Hi,

InfoQ contents can be localized, and it would be great and not too hard to take it into account.

Lazy fix, without checking supported languages:
```python
_VALID_URL = r'https?://(?:www\.)?infoq\.com/(\w\w/)?[^/]+/(?P<id>[^/]+)$'
```

Cheers

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) it does not catch.

**Comment by Dridi** [comment]
Today's first presentation on the French front page:
http://www.infoq.com/fr/presentations/changez-avis-sur-javascript

**Comment by Dridi** [comment]
Thanks!
