### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by luklau88** [rg3/youtube-dl#6072]
Hi, 

Please accept my appreciation in advance:
Can someone help me to understand / resolve the following issue?

I was playing with an aws instance to run the following command through node.js.
I have not ran the command more than 20 times, and start getting the following error code.

- Will youtube block my IP for only ~20 requests?
- Can I work around the issue using a proxy server? if yes, how can I do that?
- Can using --source-address resolve this issue?

======================================

youtube-dl -g -f 140 RgKAFK5djSk -v
======================================

[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'-g', u'-f', u'140', u'RgKAFK5djSk', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.9 - Linux-3.14.44-32.39.amzn1.x86_64-x86_64-with-glibc2.2.5
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
This has been discussed a lot. You may want to read [FAQ entry on the issue](https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required) and [this discussion](https://github.com/rg3/youtube-dl/issues/5138).
