### ISSUE TITLE
Unable to extract json

### ISSUE THREAD

**Issue by Usinouv** [rg3/youtube-dl#6082]
$ youtube-dl --verbose "http://rmcdecouverte.bfmtv.com/mediaplayer-replay/?id=9572&title=STORAGE%20WARS%3AADJUGE%2CVENDU"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://rmcdecouverte.bfmtv.com/mediaplayer-replay/?id=9572&title=STORAGE%20WARS%3AADJUGE%2CVENDU']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] Proxy map: {}
[generic] ?id=9572&title=STORAGE%20WARS%3AADJUGE%2CVENDU: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?id=9572&title=STORAGE%20WARS%3AADJUGE%2CVENDU: Downloading webpage
[generic] ?id=9572&title=STORAGE%20WARS%3AADJUGE%2CVENDU: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: STORAGE WARS:ADJUGE,VENDU
[generic] playlist STORAGE WARS:ADJUGE,VENDU: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[Brightcove] 4306403325001: Downloading webpage
[Brightcove] 4306403325001: Extracting information
ERROR: Unable to extract json; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/brightcove.py", line 170, in _real_extract
    videoPlayer[0], query_str, query, referer=referer)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/brightcove.py", line 186, in _get_video_info
    info = self._search_regex(r'var experienceJSON = ({.*?});', webpage, 'json')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract json; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
You are using a quite OLD version (2014.02.17). Have a look at [update instructions](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl) if you have any problem on updating.
