### ISSUE TITLE
 Unable to download webpage

### ISSUE THREAD

**Issue by kaaboaye** [rg3/youtube-dl#6083]
When I try to download any video on my Raspberry pi 2b i see this error
ERROR: Unable to download webpage: <urlopen error [Errno 0] Error> (caused by URLError(OSError(0, 'Error'),))

I have Internet connection.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by kaaboaye** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=Q-XNWMSxmBo']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 3.4.3 - Linux-4.0.6-1-ARCH-armv7l-with-arch
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Q-XNWMSxmBo: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 0] Error> (caused by URLError(OSError(0, 'Error'),))
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/site-packages/youtube_dl/utils.py", line 713, in https_open
    req, **kwargs)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)

**Comment by dstftw** [comment]
What's the output of `wget -d https://www.youtube.com/watch?v=Q-XNWMSxmBo`?

**Comment by kaaboaye** [comment]
DEBUG output created by Wget 1.16.3 on linux-gnueabihf.

URI encoding = `UTF-8'
--2015-06-25 16:47:54--  https://www.youtube.com/watch?v=Q-XNWMSxmBo
Translacja www.youtube.com (www.youtube.com)... nieudane: Sukces.
wget: nie udało się rozwiązać adresu hosta `www.youtube.com'

Translation:

Translaction www.youtube.com (www.youtube.com)...Failed: Success.
wget: unable to resolve host address  `www.youtube.com'

**Comment by dstftw** [comment]
>wget: unable to resolve host address  `www.youtube.com'

That's it. You should fix your DNS.
