### ISSUE TITLE
--metadata-from-title "%(artist)s - %(title)s" appending video info to file name

### ISSUE THREAD

**Issue by ondrovic** [rg3/youtube-dl#6085]
When using the -metadata-from-title it appears to be appending the ?v=<VIDEOID> to the filename

     youtube-dl --add-metadata --metadata-from-title "%(artist)s - %(title)s" --extract-audio --audio-format mp3 --audio-quality 0 --embed-thumbnail --prefer-ffmpeg --youtube-skip-dash-manifest --ignore-errors --restrict-filenames --verbose --batch-file $f

**Comment by jaimeMF** [comment]
Post the full output you get when running the command.
