### ISSUE TITLE
what's wrong about this

### ISSUE THREAD

**Issue by lele2010lele** [rg3/youtube-dl#6091]
when i  downlown  st in youtube,it's always 32M loaded,what should i do ?

MacBook-Pro-A2X:~ apple$ youtube-dl --proxy http://127.0.0.1:8087 -f 18 https://www.youtube.com/watch?v=7Akvt9ZSOcg
[youtube] 7Akvt9ZSOcg: Downloading webpage
[youtube] 7Akvt9ZSOcg: Extracting video information
[youtube] 7Akvt9ZSOcg: Downloading DASH manifest
[download] Destination: Top 10 Awkward Moments in Live TV-7Akvt9ZSOcg.mp4
[download] 1.2% of 32.00MiB at 17.31KiB/s ETA 31:10

**Comment by jaimeMF** [comment]
[Post the output with the --verbose option] and explain exactly what's your problem.

**Comment by lele2010lele** [comment]
http://127.0.0.1:8087 -tc https://www.youtube.com/watch?v=PUevY8GHLiw
[generic] 127.0.0: Requesting header
WARNING: Could not send HEAD request to http://127.0.0.1:8087: ''
[generic] 127.0.0: Downloading webpage
WARNING: Falling back on generic information extractor.
WARNING: URL could be a direct video link, returning it as such.
ERROR: requested format not available
apple-de15cunMacBook-Pro:~ apple$ youtube-dl -verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-verbose']
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: invalid rate limit specified
apple-de15cunMacBook-Pro:~ apple$

**Comment by jaimeMF** [comment]
Post the output of `youtube-dl --proxy http://127.0.0.1:8087 -f 18 https://www.youtube.com/watch?v=7Akvt9ZSOcg --verbose` and explain your problem, it isn't clear in the first post.

**Comment by lele2010lele** [comment]
Last login: Sat Sep 12 09:10:40 on ttys000
apple-de15cunMacBook-Pro:~ apple$ youtube-dl --proxy http://127.0.0.1:8087 -f 18 https://www.youtube.com/watch?v=7Akvt9ZSOcg --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--proxy', u'http://127.0.0.1:8087', u'-f', u'18', u'https://www.youtube.com/watch?v=7Akvt9ZSOcg', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.03
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {u'http': u'http://127.0.0.1:8087', u'https': u'http://127.0.0.1:8087'}
[youtube] 7Akvt9ZSOcg: Downloading webpage
[youtube] 7Akvt9ZSOcg: Downloading video info webpage
[youtube] 7Akvt9ZSOcg: Extracting video information
[youtube] 7Akvt9ZSOcg: Downloading DASH manifest
[youtube] 7Akvt9ZSOcg: Downloading DASH manifest
[debug] Invoking downloader on u'https://r5---sn-tt17rn7r.googlevideo.com/videoplayback?ipbits=0&itag=18&key=yt5&ip=107.178.195.205&mime=video%2Fmp4&upn=I2RivS9vj9k&signature=758B221FF041FFC58BC3BEF405EF52A5B00A8761.C91686A8F1A1343B3B8027788339B1B28F2AA87B&lmt=1429593289179753&sparams=dur%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&id=o-APvW7MM2tL-woIeWlNN1cjcmqJl8kfuZNZr8-9WS0NnM&expire=1442042320&ratebypass=yes&mn=sn-tt17rn7r&source=youtube&mm=31&mv=m&mt=1442020678&fexp=9408351%2C9408490%2C9408710%2C9409069%2C9415365%2C9415485%2C9416008%2C9416023%2C9416126%2C9416344%2C9416575%2C9417707%2C9418153%2C9418204%2C9418448%2C9418455%2C9419253%2C9419444%2C9419772%2C9419797%2C9420348%2C9420796&ms=au&sver=3&pl=26&requiressl=yes&dur=790.964'
[download] Destination: Top 10 Awkward Moments in Live TV-7Akvt9ZSOcg.mp4
[download] 100% of 32.00MiB in 01:09
apple-de15cunMacBook-Pro:~ apple$ 

when i dl youtube,the video could not be dl as a full version,this is my problem
thanks for the help

**Comment by dstftw** [comment]
This can be caused by your proxy. What if you download without it?

**Comment by lele2010lele** [comment]
well,i am in China ,i have to use the proxy,  the stupid GreatFireWall stoped us(all the people) to visit others   ,thanks for all you did.

**Comment by lele2010lele** [comment]
Could you please help us to cross the GFW?
https://github.com/XX-net/XX-Net
the web is the proxy i used

**Comment by yan12125** [comment]
Can you watch the whole video in browsers with this proxy?

**Comment by lele2010lele** [comment]
yes，its pretty good，this is the only proxy we can use in China

**Comment by jaimeMF** [comment]
The problem is probably with the proxy, so we can't do anything (I think). Have you tried other formats like `-f bestvideo+bestaudio`, `-f 43` or `-f 5`?

**Comment by yan12125** [comment]
Works for me:
```
$ youtube-dl --no-check-certificate --proxy http://127.0.0.1:8087 -f 18 "https://www.youtube.com/watch?v=7Akvt9ZSOcg" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--no-check-certificate', u'--proxy', u'http://127.0.0.1:8087', u'-f', u'18', u'https://www.youtube.com/watch?v=7Akvt9ZSOcg', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {u'http': u'http://127.0.0.1:8087', u'https': u'http://127.0.0.1:8087'}
[youtube] 7Akvt9ZSOcg: Downloading webpage
[youtube] 7Akvt9ZSOcg: Downloading video info webpage
[youtube] 7Akvt9ZSOcg: Extracting video information
[youtube] 7Akvt9ZSOcg: Downloading DASH manifest
[youtube] 7Akvt9ZSOcg: Downloading DASH manifest
[debug] Invoking downloader on u'https://r5---sn-tt17rn7r.googlevideo.com/videoplayback?requiressl=yes&sparams=dur%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&source=youtube&ipbits=0&lmt=1429593289179753&key=yt5&mime=video%2Fmp4&fexp=9408710%2C9409069%2C9412836%2C9415365%2C9415485%2C9415875%2C9416023%2C9416126%2C9416324%2C9416556%2C9416612%2C9416729%2C9417117%2C9417707%2C9418153%2C9418203%2C9418448%2C9418786%2C9418905%2C9419296%2C9419866%2C9420348%2C9420797&itag=18&id=o-AASXW2ouhaQoDv__xjXECO3RvfN0ZRDz1cItmGifnb2o&signature=DBC3460880EB3589552AF038EB5DED21EF7A1FAB.084C74DCEC45EA61FE5846B351F86AAA9967D466&ms=au&mv=m&upn=48HZtSPkTCw&mt=1442081163&expire=1442102874&pl=26&dur=790.964&mn=sn-tt17rn7r&ip=107.178.194.88&mm=31&ratebypass=yes&sver=3'
[download] Destination: Top 10 Awkward Moments in Live TV-7Akvt9ZSOcg.mp4
[download] 100% of 47.67MiB in 02:19
```
I use the latest commit of XX-net and a newly created Google App. Have you tried a fresh install of XX-net?

**Comment by lele2010lele** [comment]
Great! its ok now,I installed  the lastest version proxy.


apple-de15cunMacBook-Pro:~ apple$ youtube-dl --no-check-certificate --proxy http://127.0.0.1:8087 -tc https://www.youtube.com/watch?v=NIP9SRdYGo8 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--no-check-certificate', u'--proxy', u'http://127.0.0.1:8087', u'-tc', u'https://www.youtube.com/watch?v=NIP9SRdYGo8', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {u'http': u'http://127.0.0.1:8087', u'https': u'http://127.0.0.1:8087'}
[youtube] NIP9SRdYGo8: Downloading webpage
[youtube] NIP9SRdYGo8: Downloading video info webpage
[youtube] NIP9SRdYGo8: Extracting video information
[youtube] NIP9SRdYGo8: Downloading DASH manifest
[youtube] NIP9SRdYGo8: Downloading DASH manifest
[debug] Invoking downloader on u'https://r15---sn-tt17rn7d.googlevideo.com/videoplayback?ipbits=0&itag=22&key=yt5&ip=107.178.195.197&mime=video%2Fmp4&upn=DXdt3Tt568A&signature=11BE543DC6FAF379185A1F3EB548C8DF101DE758.1E7F95E54E1ABA1CBDB01406BF02DE7F67F93D51&lmt=1429622956158651&sparams=dur%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&id=o-APbAt1aNcXyUJO0odc4oPAQ_XB3keL0yC6IDrPQK8Ndx&expire=1442131598&ratebypass=yes&mn=sn-tt17rn7d&source=youtube&mm=31&mv=m&mt=1442109937&fexp=9408087%2C9408710%2C9409069%2C9412755%2C9412837%2C9415365%2C9415485%2C9416023%2C9416126%2C9416334%2C9416729%2C9416916%2C9416985%2C9417707%2C9418083%2C9418153%2C9418448%2C9418562%2C9419299%2C9419333%2C9419444%2C9419789%2C9420217%2C9420282%2C9420288%2C9420348%2C9420796&ms=au&sver=3&pl=26&requiressl=yes&dur=1358.762'
[download] Destination: Faker - Best Plays of 2014 _ The God of Gods _ League of Legends-NIP9SRdYGo8.mp4
[download] 100% of 442.63MiB in 08:34
apple-de15cunMacBook-Pro:~ apple$ youtube-dl --no-check-certificate --proxy http://127.0.0.1:8087 -tc https://www.youtube.com/watch?v=rAiw2SXPS-4&list=RDrAiw2SXPS-4 --verbose
[1] 23233
-bash: --verbose: command not found
apple-de15cunMacBook-Pro:~ apple$ [youtube] rAiw2SXPS-4: Downloading webpage
[youtube] rAiw2SXPS-4: Downloading video info webpage
[youtube] rAiw2SXPS-4: Extracting video information
[youtube] rAiw2SXPS-4: Downloading DASH manifest
[download] Destination: Michael Jackson 'Billie Jean' 30th Anniversary Madison Square Garden NY-rAiw2SXPS-4.mp4
[download] 100% of 161.28MiB in 03:57

**Comment by zbinbinz** [comment]
Michael Jackson song  " Smooth Criminal " - The King of Pop
https://www.youtube.com/watch?v=Y9C4KWICcIw
