### ISSUE TITLE
[youtube] add support for new formats

### ISSUE THREAD

**Issue by sdsucks** [rg3/youtube-dl#6093]
https://www.youtube.com/watch?v=FIl7x6_3R5Y
youtube-dl misses at least 2 formats on the above video;
810x1440 vp9 30fps DASH video 189.1MB
1080x1920 vp9 30fps DASH video 440.85MB

I've found this using SaveFrom.net helper userscript.
https://sf-addon.com/helper/chrome/helper.user.js

**Comment by remitamine** [comment]
there is also two other formats (59,78) they are both an mp4 video with this resolution 854x480.
i find them in this video:http://www.youtube.com/embed/NUVB5kzp5ZA
youtube-dl -v -F http://www.youtube.com/embed/NUVB5kzp5ZA
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c', '--external-downloader-args', '-x 16 --check-certificate=false']
[debug] Command-line args: ['-v', '-F', 'http://www.youtube.com/embed/NUVB5kzp5ZA']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 3.4.3 - Linux-4.0.6-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] NUVB5kzp5ZA: Downloading webpage
[youtube] NUVB5kzp5ZA: Extracting video information
[youtube] NUVB5kzp5ZA: Downloading DASH manifest
[info] Available formats for NUVB5kzp5ZA:
format code  extension      resolution note
171          webm           audio only DASH audio   79k , audio@128k (44100Hz), 998.63KiB
140          m4a            audio only DASH audio  127k , m4a_dash container, aac  @128k (44100Hz), 1.72MiB
141          m4a            audio only DASH audio  255k , m4a_dash container, aac  @256k (44100Hz), 3.45MiB
160          mp4            256x144    DASH video  114k , 15fps, video only, 1.50MiB
278          webm           256x144    DASH video  122k , webm container, VP9, 1fps, video only, 895.94KiB
133          mp4            426x240    DASH video  251k , 30fps, video only, 3.24MiB
242          webm           426x240    DASH video  300k , 1fps, video only, 1.88MiB
134          mp4            640x360    DASH video  474k , 30fps, video only, 5.19MiB
243          webm           640x360    DASH video  575k , 1fps, video only, 3.55MiB
244          webm           854x480    DASH video  906k , 1fps, video only, 6.42MiB
135          mp4            854x480    DASH video 1106k , 30fps, video only, 12.28MiB
136          mp4            1280x720   DASH video 2255k , 30fps, video only, 25.15MiB
247          webm           1280x720   DASH video 2611k , 1fps, video only, 13.90MiB
248          webm           1920x1080  DASH video 3665k , 1fps, video only, 24.75MiB
137          mp4            1920x1080  DASH video 4228k , 30fps, video only, 48.11MiB
59           unknown_video  unknown    
78           unknown_video  unknown    
17           3gp            176x144    
36           3gp            320x240    
5            flv            400x240    
43           webm           640x360    
18           mp4            640x360    
22           mp4            1280x720   (best)

**Comment by dstftw** [comment]
59 and 78 are already supported - you are using an outdated version.
