### ISSUE TITLE
Get the bitrate of videos 

### ISSUE THREAD

**Issue by TheGr33k** [rg3/youtube-dl#6095]
Is it possible to get the bitrates of the individual youtube videos with youtube-dl

**Comment by dstftw** [comment]
Sometimes. `formats` fields of JSON output (`--dump-json` or `--write-info-json`) contains the list of format dictionaries, each may contain:
`tbr` for average bitrate of audio and video in KBit/s
`abr` for average audio bitrate in KBit/s
`vbr` for average video bitrate in KBit/s
