### ISSUE TITLE
What does --youtube-include-dash-manifest do?

### ISSUE THREAD

**Issue by mysteryx93** [rg3/youtube-dl#6099]
I'm currently updating some code to download from YouTube and am having some issues with format code 141. Apparently, youtube-dl can download a 256kb AAC audio stream with the --youtube-include-dash-manifest option, while if you open the web page and search "itag=141", the video stream definitely isn't there.

What exactly are you doing to get this 141 stream?

Here's a video
https://www.youtube.com/watch?v=Q3oItpVa9fs

itag=141 definitely isn't in the page. Yet, another download tool was able to get it at this URL. I want to know how to extract that URL.

https://r3---sn-j5caxh5nj5o-j0oe.googlevideo.com/videoplayback?id=437a08b6955af5fb&itag=141&source=youtube&requiressl=yes&ms=au&mv=m&mm=31&pl=21&mn=sn-j5caxh5nj5o-j0oe&ratebypass=yes&mime=audio/mp4&gir=yes&clen=11226600&lmt=1421394143029494&dur=352.107&upn=HrcakPuKNVc&mt=1435344694&key=dg_yt0&sver=3&fexp=9407141,9408142,9408420,9408710,9412491,9413006,9413155,9413503,9415052,9415560,9415828,9416048,9416126,9416144,9416456,9416729,9416846,952640&signature=0FE155AE3EBD09030F8EC53D102863736A5E52E2.2C58359C108562726726BEA8E0F0326322879DEE&ip=189.221.249.135&ipbits=0&expire=1435366409&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,mm,pl,mn,ratebypass,mime,gir,clen,lmt,dur

Thanks!

**Comment by dstftw** [comment]
`--youtube-include-dash-manifest` option is noop for quite a while now since it's enabled by default. [It downloads DASH manifest and extracts DASH formats from it](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1120-L1138).

**Comment by mysteryx93** [comment]
Thanks. This works. But then for some videos it fails to download the manifest file with "Access forbidden" while it works for others

How do you work around this?

Here's a video where it fails
https://www.youtube.com/watch?v=6ex1YkDXelo

Here's the DASH Manifest File
https://manifest.googlevideo.com/api/manifest/dash/ms/au/mt/1435354572/mv/m/id/o-AMUPnDgLvQXtsltgAI6SEP5-Bj2RqjxcLFQNP12iYzuz/pl/21/fexp/9407141%2C9407943%2C9408142%2C9408420%2C9408710%2C9408764%2C9409229%2C9413449%2C9413503%2C9414764%2C9415397%2C9415809%2C9416126%2C9416456%2C9416729%2C952640/ipbits/0/hfr/1/source/youtube/mm/31/ip/189.221.249.135/sver/3/mn/sn-j5caxh5nj5o-j0oe/pcm2cms/yes/gcr/mx/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm_sd_hd_clear%2Cwebm2_sd_hd_clear/sparams/as%2Cgcr%2Chfr%2Cid%2Cip%2Cipbits%2Citag%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cplayback_host%2Crequiressl%2Csource%2Cexpire/requiressl/yes/s/0C2A2AAB7247D8BB426ABF972F45D633AAA48B41.659C2195AD715493183CA55688FE9A5F0A33F8588/upn/gojQPqsy9Ws/expire/1435376226/itag/0/playback_host/r2---sn-j5caxh5nj5o-j0oe.googlevideo.com/key/yt5
