### ISSUE TITLE
How do you query DASH Manifest

### ISSUE THREAD

**Issue by mysteryx93** [rg3/youtube-dl#6102]
I'm trying to manually read the DASH manifest of videos. It works for some, while for others I get "Access forbidden". How do you work around this?

Here's a video where it fails
https://www.youtube.com/watch?v=6ex1YkDXelo

Here's the DASH Manifest File
https://manifest.googlevideo.com/api/manifest/dash/ms/au/mt/1435354572/mv/m/id/o-AMUPnDgLvQXtsltgAI6SEP5-Bj2RqjxcLFQNP12iYzuz/pl/21/fexp/9407141%2C9407943%2C9408142%2C9408420%2C9408710%2C9408764%2C9409229%2C9413449%2C9413503%2C9414764%2C9415397%2C9415809%2C9416126%2C9416456%2C9416729%2C952640/ipbits/0/hfr/1/source/youtube/mm/31/ip/189.221.249.135/sver/3/mn/sn-j5caxh5nj5o-j0oe/pcm2cms/yes/gcr/mx/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm_sd_hd_clear%2Cwebm2_sd_hd_clear/sparams/as%2Cgcr%2Chfr%2Cid%2Cip%2Cipbits%2Citag%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cplayback_host%2Crequiressl%2Csource%2Cexpire/requiressl/yes/s/0C2A2AAB7247D8BB426ABF972F45D633AAA48B41.659C2195AD715493183CA55688FE9A5F0A33F8588/upn/gojQPqsy9Ws/expire/1435376226/itag/0/playback_host/r2---sn-j5caxh5nj5o-j0oe.googlevideo.com/key/yt5

**Comment by dstftw** [comment]
By [decrypting signature](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L786-L790).
