### ISSUE TITLE
Unable to extract video GUID

### ISSUE THREAD

**Issue by Kuzy4ka** [rg3/youtube-dl#6109]
youtube-dl.exe -o "27_june_2015_14_263.mp4" "htt
p://www.newstube.ru/media/m24-ru-pokazhet-predstavleniya-mortido-raduga-sudorog-
i-r-j"
[Newstube] m24-ru-pokazhet-predstavleniya-mortido-raduga-sudorog-i-r-j: Download
ing page
ERROR: Unable to extract video GUID; please report this issue on https://yt-dl.o
rg/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete
 output.

**Comment by jaimeMF** [comment]
Thanks for the report, it will work in the next version.
For future reports please post the [output with the --verbose option](https://github.com/rg3/youtube-dl/blob/73c471e9efd3f888af060b391eb750b079a5822c/README.md#bugs).
