### ISSUE TITLE
Configuration file is ignored

### ISSUE THREAD

**Issue by J316** [rg3/youtube-dl#6110]
I put this line into /etc/youtube-dl.conf because i want it to download on an external hard drive by default
-o "PATH/%(title)s.%(ext)s"
but it's ignored everytime and it downloads into home folder. But if I put this line in terminal between the youtube-dl command and the url it downloads in the specified path. It always used to work in previous installation of Linux.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) and the output of `cat /etc/youtube-dl.conf`.

**Comment by J316** [comment]
sudo cat /etc/youtube-dl.conf
-o "/media/External/youtube-dl/%(title)s.%(ext)s"

youtube-dl --verbose https://www.youtube.com/watch?v=bls2D0jMK84
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=bls2D0jMK84']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.16.0-38-generic-x86_64-with-LinuxMint-17.2-rafaela
[debug] Proxy map: {}
[youtube] Setting language
[youtube] bls2D0jMK84: Downloading webpage
[youtube] bls2D0jMK84: Downloading video info webpage
[youtube] bls2D0jMK84: Extracting video information
[download] Destination: A Question of Origins (English Version)-bls2D0jMK84.mp4
[download]   7.2% of 155.86MiB at 738.79KiB/s ETA 03:20^C

**Comment by dstftw** [comment]
>output of `cat /etc/youtube-dl.conf`

**without** sudo.

**Comment by J316** [comment]
cat: /etc/youtube-dl.conf: Permission denied

**Comment by dstftw** [comment]
Give it permissions for reading for everyone: `sudo chmod a+r /etc/youtube-dl.conf`

**Comment by J316** [comment]
same as with sudo

**Comment by dstftw** [comment]
Same what?

**Comment by J316** [comment]
same output as with the sudo command

**Comment by J316** [comment]
why did you close this while still asking questions?

**Comment by dstftw** [comment]
Because I provided you a [solution](https://github.com/rg3/youtube-dl/issues/6110#issuecomment-116103731).

**Comment by J316** [comment]
yeah. sorry, I misunderstood it
