### ISSUE TITLE
Empty OGG files added when audio extraction fails

### ISSUE THREAD

**Issue by davidhedlund** [rg3/youtube-dl#6111]
youtube-dl -x -f 172/171/43/webm/ogg https://www.youtube.com/watch?v=elueA2rofoo
[youtube] elueA2rofoo: Downloading webpage
[youtube] elueA2rofoo: Extracting video information
[youtube] elueA2rofoo: Downloading DASH manifest
[download] Destination: Britney Spears - Gimme More-elueA2rofoo.webm
[download] 100% of 3.63MiB in 00:02
[avconv] Destination: Britney Spears - Gimme More-elueA2rofoo.ogg
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
ERROR: audio conversion failed: av_interleaved_write_frame(): Invalid argument

du -h Britney\ Spears\ -\ Gimme\ More-elueA2rofoo.ogg 
12K	Britney Spears - Gimme More-elueA2rofoo.ogg

**Comment by dstftw** [comment]
>WARNING: Your copy of avconv is **outdated**, **update avconv** to version 10-0 or newer **if you encounter any errors**.
>**ERROR**: **audio conversion failed**: av_interleaved_write_frame(): Invalid argument
