### ISSUE TITLE
Twitch no longer offering "Source/live" quality level

### ISSUE THREAD

**Issue by TheRyuu** [rg3/youtube-dl#6115]
When using youtube-dl Twitch doesn't seem to be offering the highest quality level anymore which would be "Source" in a browser and I believe was labeled "live" as the format code.  It becomes apparent when you watch a twitch vod in a browser then again using mpv+youtube-dl where the quality of the latter is worse.  I'm not sure exactly when this stopped working but I've tried older versions of youtube-dl and the result is the same which makes me think something changed on Twitch's end causing this.

Output of youtube-dl.exe with -v.  I believe previously there was a "live" quality option as well.  This occurs with all twitch vods I've tested.  I have not tried an actual live stream but I believe those also have this same problem.
```
youtube-dl.exe -v --list-formats http://www.twitch.tv/riotgames/v/6528877
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--list-formats', u'http://www.twitch.tv/riotgames/v/6528877']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.06.25
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[twitch:vod] 6528877: Downloading vod info JSON
[twitch:vod] 6528877: Downloading vod access token
[twitch:vod] 6528877: Downloading m3u8 information
[info] Available formats for v6528877:
format code  extension  resolution note
meta         mp4        multiple   Quality selection URL
Mobile       mp4        unknown     280k , avc1, mp4a
Low          mp4        unknown     628k , avc1, mp4a
Medium       mp4        unknown     893k , avc1, mp4a
High         mp4        unknown    1603k , avc1, mp4a  (best)
```

Not sure if I have to put this in here but the expected result would be for the source/live quality option to be available and selected as the the best quality level.  I looked through some of the recent issues and didn't notice anything like this before creating this ticket.

**Comment by yan12125** [comment]
Thanks for the report. This issue will be fixed in the next version.

**Comment by TheRyuu** [comment]
Well that was quick, nice.

I eagerly await a new Windows build to try it out again.
