### ISSUE TITLE
facebook is not supported .. how to download videos from facebook then ?

### ISSUE THREAD

**Issue by hichemius** [rg3/youtube-dl#6121]
Hello ,

I was trying to download an important personal  **video** from a previous facebook account that has been hacked via **"youtube-dl" under "ubuntu 15.04" .**
However , each time I put the link of the video I get the 'Unsupported URL' error .
What's the best solution to solve this problem ?

**Comment by RingoTheDog** [comment]
facebook IS supported...what is the URL?

**Comment by hichemius** [comment]
Here is  a snapshot of my terminal output :
![issue](https://cloud.githubusercontent.com/assets/2994504/8401778/da3cae1e-1e2b-11e5-9916-a6782c244e86.png)
help if possible .

**Comment by jaimeMF** [comment]
Post (as text, not an image) [the output you get with the --verbose option](https://github.com/rg3/youtube-dl/blob/1bbe660dfa713d377fdf0eeec6b6d6a5fa8c86d9/README.md#bugs).

**Comment by RingoTheDog** [comment]
this downloads OK...you might need to update your YouTube-DL version


C:\>youtube-dl -v "https://www.facebook.com/RB2000ps/videos/vb.139448822740695/9
91016994250536/?type=2&theater"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.facebook.com/RB2000ps/videos/vb
.139448822740695/991016994250536/?type=2&theater']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[facebook] 991016994250536: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/
bug . Make sure you are using the latest version; type  youtube-dl -U  to update
. Be sure to call youtube-dl with the --verbose flag and include its complete ou
tput.
[debug] Invoking downloader on u'https://video-sea1-1.xx.fbcdn.net/hvideo-xta1/v
/t42.1790-2/11199838_1435726020074183_158452998_n.mp4?efg=eyJybHIiOjQxMCwicmxhIj
o1MTJ9&rl=410&vabr=228&oh=de32f286a6714101075aa92dd88ee6b9&oe=55917C79'
[download] Destination:      ..       !-991016994250536.mp4
[download] 100% of 1.35MiB in 00:15

**Comment by hichemius** [comment]
Still can't download from my side.

I can't figure out the problem either .. so here's a screenshot of my terminal while running the "youtube-dl"  command on that same URL , below.
![issueverbose](https://cloud.githubusercontent.com/assets/2994504/8422685/d856f20c-1ed6-11e5-90d5-22e4cd15a21f.png)

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by hichemius** [comment]
Sadly I've updated it to the latest version via the command specified .. but I don't know why I'm still getting an outdated version. I dont' think this is from my side.

**Comment by dstftw** [comment]
youtube-dl in Ubuntu repos is usually outdated.

**Comment by hichemius** [comment]
ok thanks for the support , I'm installing through the curl link then .
