### ISSUE TITLE
Videos starting with a minus sign (-) fail to download

### ISSUE THREAD

**Issue by UltraPhil** [rg3/youtube-dl#6123]
Version is: 2015.06.15

Command output:

    >youtube-dl --ignore-errors --embed-subs --add-metadata --merge-output-format mkv -Vf7B3FMtto
    Usage: youtube-dl [OPTIONS] URL [URL...]

    youtube-dl: error: no such option: -V

But it is a valid youtube video, see here: https://www.youtube.com/watch?v=-Vf7B3FMtto

**Comment by jaimeMF** [comment]
Read this [FAQ entry](https://github.com/rg3/youtube-dl/blob/1bbe660dfa713d377fdf0eeec6b6d6a5fa8c86d9/README.md#how-do-i-download-a-video-starting-with-a---).

**Comment by UltraPhil** [comment]
Sorry, didn't see this entry.  Maybe it would be found easier if it mentioned "minus".  But it is well documented.
