### ISSUE TITLE
download failure  irish web site

### ISSUE THREAD

**Issue by kloro2006** [rg3/youtube-dl#6128]
thanks for your great program. below is log of only failure i can remember.

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://laroucheirishbrigade.com/2015/06/29/lyndon-larouche-addresses-manhattan-town-hall-event/']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.8
[debug] Proxy map: {}
[generic] lyndon-larouche-addresses-manhattan-town-hall-event: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lyndon-larouche-addresses-manhattan-town-hall-event: Downloading webpage
[generic] lyndon-larouche-addresses-manhattan-town-hall-event: Extracting information
ERROR: Unsupported URL: http://laroucheirishbrigade.com/2015/06/29/lyndon-larouche-addresses-manhattan-town-hall-event/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 457, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1417, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: undefined entity: line 32, column 2
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 752, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://laroucheirishbrigade.com/2015/06/29/lyndon-larouche-addresses-manhattan-town-hall-event/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
You need to update youtube-dl. Version 2015.06.25 works for me:
```
$ youtube-dl -v "http://laroucheirishbrigade.com/2015/06/29/lyndon-larouche-addresses-manhattan-town-hall-event/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://laroucheirishbrigade.com/2015/06/29/lyndon-larouche-addresses-manhattan-town-hall-event/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.25
[debug] Git HEAD: 0b16efd
[debug] Python version 3.4.3 - Linux-4.0.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] lyndon-larouche-addresses-manhattan-town-hall-event: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lyndon-larouche-addresses-manhattan-town-hall-event: Downloading webpage
[generic] lyndon-larouche-addresses-manhattan-town-hall-event: Extracting information
[soundcloud] 212280384: Downloading info JSON
[soundcloud] 212280384: Downloading track url
[soundcloud] 212280384: Checking download video format URL
[soundcloud] 212280384: Checking http_mp3_128_url video format URL
[debug] Invoking downloader on 'https://api.soundcloud.com/tracks/212280384/download?client_id=b45b1aa10f1ac2941910a7f0d10f8e28'
[download] Destination: Lyndon LaRouche Addresses Manhattan Town Hall Meeting-212280384.mp3
[download]   0.2% of 115.37MiB at 199.56KiB/s ETA 09:50^C
ERROR: Interrupted by user
```
If you encounter any problem on updating, have a look at [updating instructions](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl). Of course feel free to open a new issue if the problem is still after updating.
