### ISSUE TITLE
Trouble downloading from GoogleVideo

### ISSUE THREAD

**Issue by mrmayfield** [rg3/youtube-dl#6130]
Here's the URL that I'm trying to download from Google Video:

https://r13---sn-nx57ynl7.googlevideo.com/videoplayback?requiressl=yes&id=8c32fee141b840c8&itag=22&source=picasa&ip=24.244.23.219&ipbits=0&expire=1438213429&sparams=expire,id,ip,ipbits,itag,mm,mn,ms,mv,pl,requiressl,source&signature=35456C957C79C16F8F7F06C226485924D5AC394B.7F76BA2709DF3590CE7B4441E5C97643A05B6058&key=cms1&cms_redirect=yes&mm=31&mn=sn-nx57ynl7&ms=au&mt=1435621533&mv=m&pl=22

Ugly as sin, and I can't seem to trim any of these extra param's without blowing it up.

Any idea on how I can reformat this URL to be able to download it?

Here's the stacktrace: (I'm using nodeJS wrapper)
```
ERROR: requested format not available

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
```

**Comment by dstftw** [comment]
This is youtube-dl issue tracker. You should report this to node-youtube-dl or whatever wrapper you use.
