### ISSUE TITLE
can i disable some Extractors??

### ISSUE THREAD

**Issue by abdul202** [rg3/youtube-dl#6134]
I'm new to youtube-dl and I'm developing a PHP script to download videos but i want to disable Porno sites is there an easy way to that
i can do that using  PHP code to allow certain hosts and block the other but I'm wondering if there any option youtube-dl to handle that

**Comment by dstftw** [comment]
You can use `--age-limit YEARS` options that will refuse downloading all videos that require greater `age-limit`, e.g. `--age-limit 17` will restrict downloading from all 18+ sites.
Apart from this one there are no options to disable particular extractor. You can just remove some by hand.

**Comment by abdul202** [comment]
Thank you very much it works like a charm
