### ISSUE TITLE
Add Support For Vevo 4K

### ISSUE THREAD

**Issue by goldensun87** [rg3/youtube-dl#6135]
Apparently, this video has 4K resolution.

https://www.vevo.com/watch/connie-talbot/Gravity-(4K)/HKW291500152

**Comment by V0rTeXbg** [comment]
Nop

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=222520,RESOLUTION=416x234,CODECS="avc1.4d400c,mp4a.40.2"
64/hkw291500152_64k_416x234_h264_64_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=374618,RESOLUTION=416x234,CODECS="avc1.4d400c,mp4a.40.2"
200/hkw291500152_200k_416x234_h264_200_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=601437,RESOLUTION=480x270,CODECS="avc1.4d4015,mp4a.40.2"
400/hkw291500152_400k_480x270_h264_400_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=704907,RESOLUTION=640x360,CODECS="avc1.4d401e,mp4a.40.2"
500/hkw291500152_500k_640x360_h264_500_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1038281,RESOLUTION=640x360,CODECS="avc1.4d401e,mp4a.40.2"
800/hkw291500152_800k_640x360_h264_800_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1441271,RESOLUTION=960x540,CODECS="avc1.4d401f,mp4a.40.2"
1200/hkw291500152_1200k_960x540_h264_1200_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2771418,RESOLUTION=960x540,CODECS="avc1.4d401f,mp4a.40.2"
2400/hkw291500152_2400k_960x540_h264_2400_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3707137,RESOLUTION=1280x720,CODECS="avc1.4d401f,mp4a.40.2"
3200/hkw291500152_3200k_1280x720_h264_3200_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4791526,RESOLUTION=1920x1080,CODECS="avc1.4d4028,mp4a.40.2"
4200/hkw291500152_4200k_1920x1080_h264_4200_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5870053,RESOLUTION=1920x1080,CODECS="avc1.4d4028,mp4a.40.2"
5200/hkw291500152_5200k_1920x1080_h264_5200_aac_128.m3u8

Where do you see 4k?

**Comment by goldensun87** [comment]
Hmm, well that's unfortunate.  I was hoping it had 4K, because it's in the title, and the Youtube upload has 4K.  Apparently, Vevo doesn't have 4K yet, but the Youtube upload proves that the source video was 4K.  I'm curious what bitrate Vevo would use for their 4K encodes, if and when they start uploading 4K videos.

**Comment by jaimeMF** [comment]
Closing since from what you say Vevo doesn't provide 4k video.

**Comment by b1he1** [comment]
Looks like VEVO now actually supports 4k videos. youtube-dl also detects and downloads them correctly too.

> youtube-dl.exe -F "https://www.vevo.com/watch/connie-talbot/Gravity-(4K)/HKW291500152"
> [Vevo] Retrieving oauth token
> [Vevo] HKW291500152: Downloading api video info
> [Vevo] HKW291500152: Downloading video versions info
> [Vevo] HKW291500152: Downloading amazon MPD information
> [Vevo] HKW291500152: Downloading akamai MPD information
> [Vevo] HKW291500152: Downloading amazon m3u8 information
> [Vevo] HKW291500152: Downloading akamai m3u8 information
> [info] Available formats for HKW291500152:
> format code       extension  resolution note
> dash-akamai-12    m4a        audio only DASH audio  129k , mp4a.40.2 (44100Hz)
> dash-amazon-12    m4a        audio only DASH audio  129k , mp4a.40.2 (44100Hz)
> dash-akamai-10    mp4        416x234    DASH video   55k , avc1.4d400d, 25fps, video only
> dash-amazon-10    mp4        416x234    DASH video   55k , avc1.4d400d, 25fps, video only
> dash-akamai-3     mp4        416x234    DASH video  169k , avc1.4d400d, 25fps, video only
> dash-amazon-3     mp4        416x234    DASH video  169k , avc1.4d400d, 25fps, video only
> dash-akamai-6     mp4        480x270    DASH video  336k , avc1.4d4015, 25fps, video only
> dash-amazon-6     mp4        480x270    DASH video  336k , avc1.4d4015, 25fps, video only
> dash-akamai-8     mp4        640x360    DASH video  419k , avc1.4d401e, 25fps, video only
> dash-amazon-8     mp4        640x360    DASH video  419k , avc1.4d401e, 25fps, video only
> dash-akamai-11    mp4        640x360    DASH video  672k , avc1.4d401e, 25fps, video only
> dash-amazon-11    mp4        640x360    DASH video  672k , avc1.4d401e, 25fps, video only
> dash-akamai-2     mp4        960x540    DASH video 1006k , avc1.4d401f, 25fps, video only
> dash-amazon-2     mp4        960x540    DASH video 1006k , avc1.4d401f, 25fps, video only
> dash-akamai-4     mp4        960x540    DASH video 2026k , avc1.4d401f, 25fps, video only
> dash-amazon-4     mp4        960x540    DASH video 2026k , avc1.4d401f, 25fps, video only
> dash-akamai-5     mp4        1280x720   DASH video 2700k , avc1.4d401f, 25fps, video only
> dash-amazon-5     mp4        1280x720   DASH video 2700k , avc1.4d401f, 25fps, video only
> dash-akamai-7     mp4        1920x1080  DASH video 3531k , avc1.4d4028, 25fps, video only
> dash-amazon-7     mp4        1920x1080  DASH video 3531k , avc1.4d4028, 25fps, video only
> dash-akamai-9     mp4        1920x1080  DASH video 4380k , avc1.4d4028, 25fps, video only
> dash-amazon-9     mp4        1920x1080  DASH video 4380k , avc1.4d4028, 25fps, video only
> dash-akamai-1     mp4        3840x2160  DASH video 9293k , avc1.4d4028, 25fps, video only
> dash-amazon-1     mp4        3840x2160  DASH video 9293k , avc1.4d4028, 25fps, video only
> hls-akamai-225    mp4        416x234     225k , avc1.4d400d, mp4a.40.2
> hls-amazon-225    mp4        416x234     225k , avc1.4d400d, mp4a.40.2
> http-akamai-Low   mp4        256x144     328k , h264@ 200k, aac  @128k
> http-amazon-Low   mp4        256x144     328k , h264@ 200k, aac  @128k
> hls-akamai-369    mp4        416x234     369k , avc1.4d400d, mp4a.40.2
> hls-amazon-369    mp4        416x234     369k , avc1.4d400d, mp4a.40.2
> hls-akamai-576    mp4        480x270     576k , avc1.4d4015, mp4a.40.2
> hls-amazon-576    mp4        480x270     576k , avc1.4d4015, mp4a.40.2
> http-akamai-Med   mp4        640x360     628k , h264@ 500k, aac  @128k
> http-amazon-Med   mp4        640x360     628k , h264@ 500k, aac  @128k
> hls-akamai-690    mp4        640x360     690k , avc1.4d401e, mp4a.40.2
> hls-amazon-690    mp4        640x360     690k , avc1.4d401e, mp4a.40.2
> hls-akamai-1005   mp4        640x360    1005k , avc1.4d401e, mp4a.40.2
> hls-amazon-1005   mp4        640x360    1005k , avc1.4d401e, mp4a.40.2
> hls-akamai-1430   mp4        960x540    1430k , avc1.4d401f, mp4a.40.2
> hls-amazon-1430   mp4        960x540    1430k , avc1.4d401f, mp4a.40.2
> http-akamai-High  mp4        1280x720   2128k , h264@2000k, aac  @128k
> http-amazon-High  mp4        1280x720   2128k , h264@2000k, aac  @128k
> hls-akamai-2641   mp4        960x540    2641k , avc1.4d401f, mp4a.40.2
> hls-amazon-2641   mp4        960x540    2641k , avc1.4d401f, mp4a.40.2
> hls-akamai-3401   mp4        1280x720   3401k , avc1.4d401f, mp4a.40.2
> hls-amazon-3401   mp4        1280x720   3401k , avc1.4d401f, mp4a.40.2
> hls-akamai-4382   mp4        1920x1080  4382k , avc1.4d4028, mp4a.40.2
> hls-amazon-4382   mp4        1920x1080  4382k , avc1.4d4028, mp4a.40.2
> hls-akamai-5317   mp4        1920x1080  5317k , avc1.4d4028, mp4a.40.2
> hls-amazon-5317   mp4        1920x1080  5317k , avc1.4d4028, mp4a.40.2
> hls-akamai-10850  mp4        3840x2160  10850k , avc1.4d4028, mp4a.40.2
> hls-amazon-10850  mp4        3840x2160  10850k , avc1.4d4028, mp4a.40.2 (best)

**Comment by goldensun87** [comment]
@b1he1 Thanks, I had downloaded a more recent 4K upload, which was a Noah Cyrus video, and I did not expect Vevo to upload a 4K copy of an older video.  Although, Youtube's 4K videos are actually usually higher bitrate than Vevo's.  Which is ironic, because Youtube's 1080p has been getting compressed a lot more ever since they started using DASH video, and as far as I know, 720p and 1080p videos on Youtube get further compressed as time passes.  This is why I try to download a 1080p video on Youtube as soon as it is uploaded, because the initial stream file gets replaced by a smaller size file over time.

**Comment by b1he1** [comment]
@goldensun87 Really? Do they re-compress videos to a lower bitrate over time with the same codec? I thought after they started using DASH, their other strategy of saving bandwidth is to make vp9 versions.

**Comment by goldensun87** [comment]
Yup, they re-compress videos to a lower bitrate over time.  I'm still not sure about the VP9 thing though.  At first, I thought Youtube replaced H.264 with VP9 for 4K videos, but this is not the case.  It seems to me, the H.264 vs VP9 for 4K videos on Youtube, is user-specific.  Meaning, perhaps the codec is VP9 when the uploader is uploading, and Youtube is retaining that codec instead of converting the 4K video to H.264.  That is just my assessment, I do not know for sure.

**Comment by b1he1** [comment]
@goldensun87 YouTube seems to upload a VP9 version of a video only if it gets popular enough, or if someone uploads a 4K60/8K60 and/or HDR video since YouTube won't encode a H.264 version of these.
