### ISSUE TITLE
[Bug] NPO.nl stopped working

### ISSUE THREAD

**Issue by corone17** [rg3/youtube-dl#6136]
It looks like NPO.nl has changed some things in the background.
```bat
youtube-dl.exe -vF http://www.npo.nl/nos-journaal/30-06-2015/POW_00942064
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-vF', u'http://www.npo.nl/nos-journaal/30-06-2015/POW_00942064
']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.06.25
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-65810-g1b5ec6a
[debug] Proxy map: {}
[npo.nl] POW_00942064: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 410: Gone (caused by HTTPError()); pleas
e report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; t
ype youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
its complete output.
  File "youtube_dl\extractor\common.pyo", line 312, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1729, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
```
With Firefox's webconsole I can see that:
- The token-url is now `http://ida.omroep.nl/npoplayer/i.js?s=http://www.npo.nl/nos-journaal/30-06-2015/POW_00942064`. I don't know yet whether the trailing program-url is important or not.
- The ['metadata' jsonp-url](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/npo.py#L94) is still `http://e.omroep.nl/metadata/POW_00942064`, but the ['format_info' json-url](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/npo.py#L109) is now `http://ida.omroep.nl/odi/?prid=POW_00942064&puboptions=adaptive,h264_bb,h264_sb,h264_std&adaptive=yes&part=1&token=837v2rdvu2ck4lc0ehde61ltn4&callback=jQuery...`.
`&part=1` is new, as well as the enumeration of _all_ 'pubopties'. I don't know whether `%part=1` and `&callback=` are important, because I can't get beyond this point. I constantly get:
```json
{
  "success": false,
  "error_code": 403,
  "error": "Validation error"
}
```
- And the 'format_info' json when I open the url in Firefox's webconsole:
```json
{
  "success": true,
  "streams": [
    {
      "file": "http://odi.omroep.nl/video/ida/adaptive/5ce3ed983e7b1d1626cafe19ef560842/5592
f624/POW_00942064/1?extension=m3u8&type=jsonp&callback=?",
      "type": "adaptive",
      "quality": "adaptive",
      "label": "Adaptive"
    }
  ],
  "family": "adaptive"
}
```
The url is now a value in the object "file". [Line 118 of npo.py](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/npo.py#L118) then has to be: `streams[0][file] + '&type=json',`

**Comment by yan12125** [comment]
Thanks for the report and detailed descriptions. I think the two keys are changed metadata url (as you've mentioned) and the 'encrypted' token. The extraction is fixed and in the next version NPO.nl should work again.

**Comment by corone17** [comment]
Yesterday I discovered the token-obfuscate-function in npoplayer-min.js and I was about to let you know, but you beat me to it. And above all, you already fixed it! Thanks a lot!
