### ISSUE TITLE
I'm trying to download a video that has "cdnapisec.kaltura.com" as its source. (Kaltura is a youtube-dl supported site.)

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#6137]
I'm trying to download this hour-long video [here] (http://www.premierchristianradio.com/Shows/Saturday/Unbelievable/Conference-Videos/Os-Guinness-Is-It-Fools-Talk-Unbelievable-Conference-2014). When I check the page source, the "src" of the video seems to be  cdnapisec.kaltura.com/p/618072/sp/61807200/embedIframeJs/uiconf_id/25054252/partner_id/618072.

According to http://rg3.github.io/youtube-dl/supportedsites.html, Kaltura is a supported site. So how can I download this video? Thank you.

[phihag] (https://github.com/phihag) In another [post] (https://github.com/rg3/youtube-dl/issues/5081#issuecomment-76546082) says that this issue should have been fixed in Feb 28 2015 update.
```
 youtube-dl --verbose "cdnapisec.kaltura.com/p/618072/sp/61807200/embedIframeJs/uiconf_id/25054252/partner_id/618072"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'cdnapisec.kaltura.com/p/618072/sp/61807200/embedIframeJs/uiconf_id/25054252/partner_id/618072']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[generic] 618072: Requesting header
[redirect] Following redirect to http://cdnapi.kaltura.com/html5/html5lib/v2.29/mwEmbedLoader.php/p/618072/uiconf_id/25054252
[generic] 25054252: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 25054252: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/html5/html5lib/v2.29/mwEmbedLoader.php/p/618072/uiconf_id/25054252'
[download] 25054252-25054252.unknown_video has already been downloaded
[download] 100% of 59.36KiB
```

**Comment by Green957** [comment]
I had a look at the site and I think you've got the wrong url. Try this: http://cfvod.kaltura.com/pd/p/618072/sp/61807200/serveFlavor/entryId/1_a52wc67y/v/2/flavorId/0_a6xfygse/name/a.mp4

You can even manually download it from that page if you'd like

**Comment by hub2git** [comment]
Thanks, Green957. With your help, we didn't even need youtube-dl.
But for future kaltura-hosted videos that I'd like to download, is there a way to use youtube-dl and avoid having to look at the page source?

**Comment by dstftw** [comment]
This issue will be fixed in the next version. Thanks for the report.

**Comment by devwebcl** [comment]
In which version this was resolved ?

**Comment by akshayparwar** [comment]
m trying to download video from this url voot.com/shows/mtv-roadies-s01/1/366507
its been embed using kaltura player.
http://video.voot.com/edash/p/1982551/sp/198255100/serveFlavor/entryId/0_4m7338tl/v/2/pv/1/flavorId/0_,0jcfqjzi,jpl21siv,66smk1zw,/forceproxy/true/name/a.mp4.urlset/fragment-4-f1-v1.m4s
this is the url i got from networks tab. i tried to make it as above url mentioned by Green957 but of no use.
Please help me find the source of this video

**Comment by easkari26** [comment]
I have the same problem on another video. Can you please explain how you determined that URL?  How did you determine that when the exact URL is not listed in the source code?

**Comment by JonasOlson** [comment]
@Reverius
> I have the same problem on another video. Can you please explain how you determined that URL? How did you determine that when the exact URL is not listed in the source code?

I find that the URL _is_ present in the source code.

**Comment by klaaktu** [comment]
The URL format:
https://knowledge.kaltura.com/help/how-to-retrieve-the-download-or-streaming-url-using-api-calls
So only `PartnerId` and `EntryId` need to be found in the link or F12 network tab.
Example:
To download the original file (not transcoded by Kaltura)
https://cdnapisec.kaltura.com/p/[YourPartnerId]/sp/0/playManifest/entryId/[YourEntryId]/format/url/protocol/http/flavorParamId/0/video.mp4

p.s. I found the documentation from this answer https://stackoverflow.com/a/66533709
p.s. It seems that video with /v/1/ in their url triggers an error in youtube-dl. However it can be downloaded with the above method.

**Comment by ShantanuTonde** [comment]
> The URL format: https://knowledge.kaltura.com/help/how-to-retrieve-the-download-or-streaming-url-using-api-calls So only `PartnerId` and `EntryId` need to be found in the link or F12 network tab. Example: To download the original file (not transcoded by Kaltura) [https://cdnapisec.kaltura.com/p/[YourPartnerId]/sp/0/playManifest/entryId/[YourEntryId]/format/url/protocol/http/flavorParamId/0/video.mp4](https://cdnapisec.kaltura.com/p/%5BYourPartnerId%5D/sp/0/playManifest/entryId/%5BYourEntryId%5D/format/url/protocol/http/flavorParamId/0/video.mp4)
> 
> p.s. I found the documentation from this answer https://stackoverflow.com/a/66533709 p.s. It seems that video with /v/1/ in their url triggers an error in youtube-dl. However it can be downloaded with the above method.

Does using this tool alert the file uploader that someone has downloaded it?

**Comment by ShantanuTonde** [comment]
> Ask Kaltura. Obviously the server that responds to the download request knows about the request. What they do with that is up to them.

I see. Couldn't download the video though. After adding partnerid and entryid a bunch of links showup but none of them opened. They show 404 error.

**Comment by dirkf** [comment]
If you have a current problem with a Kaltura URL that isn't correctly handled by yt-d, please consider opening a new issue (according to #30839) where we can review the specific details.
