### ISSUE TITLE
twitch.tv support only downloads first 30 minutes

### ISSUE THREAD

**Issue by rmunn** [rg3/youtube-dl#614]
The twitch.tv support (https://github.com/rg3/youtube-dl/pull/592) ends up only downloading the first 30 minutes of the video, because that's all that the twitch.tv server provides through that API. One video where you can see this in action is http://www.twitch.tv/avidyazen/b/352351813 -- note that the twitch.tv player shows a length of 5 hours, 34 minutes and 30 seconds, but downloading via youtube-dl currently downloads only the first 30 minutes of the video.

If you experiment with the twitch.tv player by pausing it and letting it download as much of the video as it can, you'll find that it downloads 30 minutes of the video and then stops downloading; if you then jump to the 29-minute mark, you'll see the video stutter a bit at the 30-minute mark, then resume as the player starts downloading the segment from about 0:30:00 to about 1:00:00.

I don't know how to find the URLs for the other segments of the video, but maybe someone else who sees this issue will have in idea of how to find them.

**Comment by jaimeMF** [comment]
In the latest versions it should work fine. For example for http://www.twitch.tv/pibonacci/c/4043233 it downloads the stream in 7 parts. If you still have problems, feel free to open a new issue. Thanks for the report!
