### ISSUE TITLE
Udemy 401 error:"Oops, something went wrong."

### ISSUE THREAD

**Issue by maor700** [rg3/youtube-dl#6140]
It seems they did blocking robots interring more than 20 videos.
At first I could only download 20 videos of 50. Then I got a 401 error.
And even from the site can not login.
It seems they recognized that my account is trying to connect too many times and not from the site login blocked it.
it's happened to you too?
This output:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\maor>C:\Users\maor\Desktop\YouTube_Downloader\VDownload.bat

C:\Users\maor>C:\Users\maor\Desktop\YouTube_Downloader\WF\youtube-dl.exe -U --au
tonumber-size 2 -o  "C:\Users\maor\Desktop\YouTube_Downloader\Videos\%(playlist)
s\%(playlist_index)s_%(title)s.%(ext)s"  --username ******** --password
 ****** --write-sub --write-auto-sub --sub-lang iw,en --format best  "https:/
/www.udemy.com/web-design-secrets/?dtcode=WMORiSs3cw7n" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-U', u'--autonumber-size', u'2', u'-o', u'C:\\User
s\\maor\\Desktop\\YouTube_Downloader\\Videos\\%(playlist)s\\%(playlist_index)s_%
(title)s.%(ext)s', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--wri
te-sub', u'--write-auto-sub', u'--sub-lang', u'iw,en', u'--format', u'best', u'h
ttps://www.udemy.com/web-design-secrets/?dtcode=WMORiSs3cw7n', u'--verbose']
[debug] Encodings: locale cp1255, fs mbcs, out cp862, pref cp1255
[debug] youtube-dl version 2015.06.25
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-34549-g13b7781
[debug] Proxy map: {}
youtube-dl is up-to-date (2015.06.25)
[udemy:course] Downloading login popup
[udemy:course] Logging in as *************
ERROR: Udemy returned error #401: Error on Input - Oops, something went wrong.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 654, in extract_info
  File "youtube_dl\extractor\common.pyo", line 272, in extract
  File "youtube_dl\extractor\common.pyo", line 266, in initialize
  File "youtube_dl\extractor\udemy.pyo", line 67, in _real_initialize
  File "youtube_dl\extractor\udemy.pyo", line 97, in _login
  File "youtube_dl\extractor\udemy.pyo", line 63, in _download_json
  File "youtube_dl\extractor\udemy.pyo", line 43, in _handle_error
ExtractorError: Udemy returned error #401: Error on Input - Oops, something went
 wrong.

**Comment by dstftw** [comment]
If you can't login from the website there is nothing youtube-dl can do (since it uses the same method). For me it works as usual, just downloaded the whole course you provided two times without any issue.

**Comment by maor700** [comment]
than'x.
