### ISSUE TITLE
Crunchyroll not working on Archlinux 64bit

### ISSUE THREAD

**Issue by Xenphor** [rg3/youtube-dl#6142]
Here is what I get:

$ youtube-dl --verbose -f best http://www.crunchyroll.com/media-589804/culture-japan-1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-f', 'best', 'http://www.crunchyroll.com/media-589804/culture-japan-1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 3.4.3 - Linux-3.18.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 1: Downloading webpage
[Crunchyroll] 1: Downloading media info
[Crunchyroll] 1: Downloading media info for 360p
[Crunchyroll] 1: Downloading media info for 480p
[Crunchyroll] 1: Downloading media info for 720p
[debug] Invoking downloader on 'rtmpe://c6fs.fplive.net/c6?nvb=20150703011446&nva=20150703051546&token=000f0cf5e15de7574246b'
[download] Destination: Culture Japan Episode 1 – Rebuilding Japan after the 3.11-1.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://c6fs.fplive.net/c6?nvb=20150703011446&nva=20150703051546&token=000f0cf5e15de7574246b' -o 'Culture Japan Episode 1 – Rebuilding Japan after the 3.11-1.flv.part' --playpath mp4:s/ve762165/video.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : c6fs.fplive.net
[rtmpdump] DEBUG: Parsed app     : c6?nvb=20150703011446&nva=20150703051546&token=000f0cf5e15de7574246b
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : c6fs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:s/ve762165/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://c6fs.fplive.net:1935/c6?nvb=20150703011446&nva=20150703051546&token=000f0cf5e15de7574246b
[rtmpdump] DEBUG: app      : c6?nvb=20150703011446&nva=20150703051546&token=000f0cf5e15de7574246b
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : c6fs.fplive.net
[rtmpdump] DEBUG: Parsed app     : c6?nvb=20150703011446&nva=20150703051546&token=000f0cf5e15de7574246b
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : c6fs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:s/ve762165/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://c6fs.fplive.net:1935/c6?nvb=20150703011446&nva=20150703051546&token=000f0cf5e15de7574246b
[rtmpdump] DEBUG: app      : c6?nvb=20150703011446&nva=20150703051546&token=000f0cf5e15de7574246b
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.6.4.1', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 405, in main
    _real_main(argv)
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 395, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1502, in download
    res = self.extract_info(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 707, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1173, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1435, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1377, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 528, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 490, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by yan12125** [comment]
The same problem has been reported in #5881, while the cause is not clear yet.
