### ISSUE TITLE
francetvinfo downloader not working

### ISSUE THREAD

**Issue by jbnivoit** [rg3/youtube-dl#6145]
I tried to download http://www.francetvinfo.fr/societe/larguez-les-amarres-le-cobaturage-se-developpe_980101.html and it did not work. I put breakpoints in the debugger on youtube-dl running with this URL and found out that the daily motion URL pattern has slightly changed:
    _VALID_URL = r'http://api\.dmcloud\.net/embed/[^/]+/(?P<id>[^/?]+)'
should now be:
    _VALID_URL = r'http://api\.dmcloud\.net/player/embed/[^/]+/(?P<id>[^/?]+)'
(note the additional "/player" path element in the URL). With this change, I was able to download that video.

**Comment by dstftw** [comment]
This issue will be fixed in the next version. Thanks for the report.

**Comment by jbnivoit** [comment]
Thanks for this wonderful utility and the prompt fix!
