### ISSUE TITLE
dailymotion pulled urls not working

### ISSUE THREAD

**Issue by funfarooq** [rg3/youtube-dl#6150]
hi

 i am using 

python youtube-dl -f standard  -g  www.dailymotion.com/video/x2v5hz5

request on server hostgator and sending the link generated 

https://www.dailymotion.com/cdn/H264-512x384/video/x2v5hz5.mp4?auth=1436175378-2562-t3e3dyrb-9a1cb96e3bf7efa04972f11c5f77b424 

to the client computer and its not working .i mean to say is link is not downloading video there could you help me out with this

thanks in advance

**Comment by dstftw** [comment]
The final download URL is guaranteed to work only on the same machine/IP from which it has been obtained.

**Comment by funfarooq** [comment]
its not the case for youtube urls they are still working on other machines to. could you suggest me any alternatives or anything which may work out

**Comment by dstftw** [comment]
Youtube links may not work on different machines as well, e.g. #6004.
>could you suggest me any alternatives or anything which may work out

Extract URLs on the client side.

**Comment by funfarooq** [comment]
how do we that buddy in android is there any way

On Sat, Jul 4, 2015 at 3:35 PM, Sergey M. <notifications@github.com> wrote:

> Youtube links may not work on different machines as well, e.g. #6004
> <https://github.com/rg3/youtube-dl/issues/6004>.
>
> could you suggest me any alternatives or anything which may work out
>
> Extract URLs on the client side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rg3/youtube-dl/issues/6150#issuecomment-118497701>.
>



-- 
Farooq shaik
mohammadiya technologies

**Comment by funfarooq** [comment]
downloading to server and getting to client its taking for ever my server
hostgator one downloadnig file at speed of 50kb/sec may be due to heavy
load and client is waiting till it download there which is not possible
does set source ip will work. other people are bale to achieve it why can
not i

On Sun, Jul 5, 2015 at 9:39 AM, Farooq Shiak <shiakfarooq1@gmail.com> wrote:

> how do we that buddy in android is there any way
>
> On Sat, Jul 4, 2015 at 3:35 PM, Sergey M. <notifications@github.com>
> wrote:
>
>> Youtube links may not work on different machines as well, e.g. #6004
>> <https://github.com/rg3/youtube-dl/issues/6004>.
>>
>> could you suggest me any alternatives or anything which may work out
>>
>> Extract URLs on the client side.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rg3/youtube-dl/issues/6150#issuecomment-118497701>.
>>
>
>
>
> --
> Farooq shaik
> mohammadiya technologies
>



-- 
Farooq shaik
mohammadiya technologies
