### ISSUE TITLE
Site support request: Google drive/docs video

### ISSUE THREAD

**Issue by woodenphone** [rg3/youtube-dl#6155]
Example URLs:
https://docs.google.com/file/d/0B65n3MgU-72lODBoT0VLRkdCUGs/preview
https://docs.google.com/file/d/0B65n3MgU-72lODBoT0VLRkdCUGs/edit

https://drive.google.com/file/d/0B91rcCCetjGpNlY4VXhUZFJEQTA/preview

**Comment by jaimeMF** [comment]
Duplicate of #2231 and #1701
