### ISSUE TITLE
Playlist download stops on error in any video.

### ISSUE THREAD

**Issue by lordloh** [rg3/youtube-dl#6159]
https://www.youtube.com/playlist?list=PL7937001B2AAC1D02

One of the videos in this playlist is blocked. Once youtube-dl reaches this video, an error is encountered, and the remaining videos are not downloaded either. The remaining videos may be downloaded individually.

Expected behaviour should be to continue other videos,

**Comment by yan12125** [comment]
What you need is ```-i``` (```--ignore-errors```). For example:
```
youtube-dl -i "https://www.youtube.com/playlist?list=PL7937001B2AAC1D02"
```

**Comment by lordloh** [comment]
oops :-(

Thank you.
