### ISSUE TITLE
Error produced downloading gfycat embed URL. TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by woodenphone** [rg3/youtube-dl#6165]
I encountered this traceback when trying to save the embed URL for this video.
This embed style URL fails:
http://gfycat.com/ifr/JauntyTimelyAmazontreeboa
This normal URL succeeds:
http://gfycat.com/JauntyTimelyAmazontreeboa

Console log:
C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>yout
ube-dl.exe --update
youtube-dl is up-to-date (2015.07.04)

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>yout
ube-dl.exe -v http://gfycat.com/ifr/JauntyTimelyAmazontreeboa
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://gfycat.com/ifr/JauntyTimelyAmazontre
eboa']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.07.04
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Gfycat] ifr: Downloading video info
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 406, in main
  File "youtube_dl\__init__.pyo", line 396, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1501, in download
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 711, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1171, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1236, in process_info
TypeError: object of type 'NoneType' has no len()

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>yout
ube-dl.exe -v http://gfycat.com/JauntyTimelyAmazontreeboa
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://gfycat.com/JauntyTimelyAmazontreeboa
']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.07.04
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Gfycat] JauntyTimelyAmazontreeboa: Downloading video info
[debug] Invoking downloader on u'http://zippy.gfycat.com/JauntyTimelyAmazontreeb
oa.mp4'
[download] Destination: JauntyTimelyAmazontreeboa-JauntyTimelyAmazontreeboa.mp4
[download] 100% of 331.12KiB in 00:03

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>

**Comment by yan12125** [comment]
Thanks for the report. Embed URLs will work in the next version.
