### ISSUE TITLE
Feature: Use youtube ID as the only distinguisher for whether or not to download the file

### ISSUE THREAD

**Issue by Lakhman** [rg3/youtube-dl#6172]
Hi,

I think it would be awesome (and really useful for everyone) to be able to have the only the youtube ID checked when downloading files (instead of the whole filename):

Example:

Say I download a file:
```
cd /Videos
youtube-dl https://www.youtube.com/watch?v=C0DPdy98e4c
```

The file downloaded will be named: **TEST VIDEO-C0DPdy98e4c.mp4**
I now rename the file to: **My-custom-title-C0DPdy98e4c.mp4**

If I run `youtube-dl` again, It will redownload the file as **TEST VIDEO-C0DPdy98e4c.mp4**

I propose instead, if the youtube-id is the same (but anything before that is different) - then skip the download (as it's already been downloaded - but renamed (but we know it's the same video because of the **C0DPdy98e4c**)). This could be accomplished via regex. (http://stackoverflow.com/questions/6903823/regex-for-youtube-id)

This would make organizing videos much easier! You could have a bash script which holds all your URL's (which you can backup), and you can also rename your videos to something more friendly:

```
e.g: "STUPID NAME IN CAPS-C0DPdy98e4c.mp4" => "a.nicer.filename-C0DPdy98e4c.mp4"
```

This way all videos are still identifiable (you can go to youtube and search by id), you have nicer filenames to organize. If you specifically wanted to mark an item as "dont skip" - Maybe we could negate it in the youtube-id filename using a `!`:

```
youtube-dl https://www.youtube.com/watch?v=C0DPdy98e4c
# Downloads To: TEST VIDEO-C0DPdy98e4c.mp4

# Rename it
mv "TEST VIDEO-C0DPdy98e4c.mp4" "TEST VIDEO-!C0DPdy98e4c.mp4"

# Download again (will download as the name has a ` ! ` before the youtube id)
youtube-dl https://www.youtube.com/watch?v=C0DPdy98e4c
```

Not sure how this would work for other video providers (vimeo, etc) - But would be so useful for youtube (music videos, tutorials, etc).

---

I vote +1 for this as it should be relatively simple to implement, and shouldn't cause any nasty side effects or API changes, the benefits though are huge! - Being able to organize all your videos nicely (but still have the ID for future reference) - as well as making bash scripts to download and backup the links to your videos (rather then the videos themselves which could save backup space on external devices).

Thoughts?

**Comment by dstftw** [comment]
That's impossible since filename may contain no video id or be arbitrary at all when specified with [output template](https://github.com/rg3/youtube-dl#output-template). Output template is actually should be used to
>to organize all your videos nicely

**Comment by Lakhman** [comment]
ahh yeah, that'll do it, thanks!

**Comment by jaimeMF** [comment]
You may want to use `--download-archive`, which will register the downloaded videos in a file and will skip them (even if they are deleted).
