### ISSUE TITLE
Some videos can start with a dash, youtube-dl interprets them as options.

### ISSUE THREAD

**Issue by Sheldan** [rg3/youtube-dl#6178]
I only start youtube-dl by the actual ID, not the whole URL and some videos can contain dashes at the start, you youtube-dl thinks options are starting. An example of such a video is: -wXEuP0nM_A. The easiest workaround is, to pass the long URL directly to youtube-dl, but I want to continue using the functionality to directly pass the videoID instead of the whole URL.

**Comment by yan12125** [comment]
See [this FAQ entry](https://github.com/rg3/youtube-dl#how-do-i-download-a-video-starting-with-a---).
