### ISSUE TITLE
BBC iPlayer Radio 3 "Hi quality" stream don't seem to be downloadable even through a UK proxy

### ISSUE THREAD

**Issue by laconcombremasque** [rg3/youtube-dl#6183]
Hello, I'm not in UK and use MAC os 10.6.8. 

When trying to download a radio 3 episode on BBC's iplayer site with yt-dl, the list of available formats seem to be the same with / without proxy :

$ youtube-dl --proxy "195.40.6.43:8080" -F http://www.bbc.co.uk/programmes/b060zrkx
[bbc.co.uk] b060zrkx: Downloading video page
[bbc.co.uk] b060zrkx: Downloading playlist JSON
[bbc.co.uk] b060zrj0: Downloading media selection XML
[info] Available formats for b060zrj0:
format code                                      extension  resolution note
stream-nonuk-audio_streaming_aac_vlow_akamai     flv        unknown    aac  @ 48k
stream-nonuk-audio_streaming_aac_vlow_limelight  flv        unknown    aac  @ 48k (best)

>AAC "low quality"

But, I managed to download a higher quality stream (I believe, the 320kbs aac stream normally reserved for UK streaming) using another method [using the Hola extension for Chrome, and launch Jaksta for Mac]. It resulted in the download of a bigger file :
bUnknown-d181fef5-f43f-4214-8812-4f82f296e2e5_b060zrj0_1436296777741mp4.aac
AAC, Stéréo (G D), 48,000 Khz , 307.13 kbits/s

Is there something wrong with yt-dl ? Or did I misuse the --proxy command ? I did try with a couple of different "elite" UK proxies though.

I investigated further (with the Jaksta solution) because I know there is this 320kb aac stream available to UK listeners.

I hope my report can help yt-dl to fetch it !
all the best.

**Comment by yan12125** [comment]
Yes you need another proxy.
```
$ youtube-dl -vF --proxy "username:password@proxy_ip" "http://www.bbc.co.uk/programmes/b060zrkx"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vF', '--proxy', 'v', 'http://www.bbc.co.uk/programmes/b060zrkx']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.25
[debug] Git HEAD: c916714
[debug] Python version 3.4.3 - Linux-4.1.1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {'http': 'username:password@proxy_ip', 'https': 'username:password@proxy_ip'}
[bbc.co.uk] b060zrkx: Downloading video page
[bbc.co.uk] b060zrkx: Downloading playlist JSON
[bbc.co.uk] b060zrj0: Downloading media selection XML
[info] Available formats for b060zrj0:
format code                                   extension  resolution note
stream-uk-audio_streaming_aac_vlow_akamai     flv        unknown    aac  @ 48k
stream-uk-audio_streaming_aac_vlow_limelight  flv        unknown    aac  @ 48k
stream-uk-audio_streaming_aac_med_akamai      flv        unknown    aac  @128k
stream-uk-audio_streaming_aac_med_limelight   flv        unknown    aac  @128k
stream-uk-audio_streaming_aac_high_akamai     flv        unknown    aac  @320k
stream-uk-audio_streaming_aac_high_limelight  flv        unknown    aac  @320k (best)
```
I can't reveal the proxy here because it contains my username and password.
