### ISSUE TITLE
Not finding closed captions; am I doing it wrong?

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#6184]
I tried to get an episode of Nova with captions.

youtube-dl -f 'bestvideo[height<=480][ext=mp4]+bestaudio/[height <=? 480]' --write-sub --recode-video mp4 http://video.pbs.org/video/2365472415/

Subtitles/captions did NOT download. Am I using the right option? Is there a way to fetch just the subtitles?

**Comment by dstftw** [comment]
Subtitles are not supported for pbs.

**Comment by dstftw** [comment]
Subtitles will be supported in the next version. Thanks for the report.

**Comment by keybounce** [comment]
Any idea when this will be released?

**Comment by yan12125** [comment]
When @phihag has free time.
