### ISSUE TITLE
Letv Incomplete download

### ISSUE THREAD

**Issue by eternia478** [rg3/youtube-dl#6192]
Recent usage of youtube-dl with letv.com causes problems where the video is incompletely fetched. For example, using it on the following video:
<pre>
youtube-dl -f 350 http://www.letv.com/ptv/vplay/1839416.html
</pre>
will download a 24 MB file. But originally, the lowest resolution (at 350) should be 79 MB. The same goes for other resolutions. The video notably stops at around the 10 minute mark, even though the entire video should be much longer.

It may be that the videos by Letv are now split up like Youku and Tudou. The flvcd site, though, suggests this is not the case.

**Comment by yan12125** [comment]
Confirmed.
