### ISSUE TITLE
Udemy Courses "Method Not Allowed"

### ISSUE THREAD

**Issue by kerperlo** [rg3/youtube-dl#6201]
I am wanting to download a course from Udemy, but it keeps giving me this error. Any solutions?
![problem](https://cloud.githubusercontent.com/assets/10853197/8638772/0596ce28-288b-11e5-8cdb-9a3dabdddfd1.PNG)

**Comment by dstftw** [comment]
This course is not free, Have you purchased it?

**Comment by kerperlo** [comment]
Do I need to purchase them? Cause I heard that it works with Udemy-dl as well. People who get paid courses free.

**Comment by dstftw** [comment]
Of course you need. Without purchasing you can only download preview videos (use `-i` to skip errors). udemy-dl does not download it without purchasing as well.
