### ISSUE TITLE
How do I use "--format" now?

### ISSUE THREAD

**Issue by esamo** [rg3/youtube-dl#6202]
Hello.

I used to do `--format [prioritized formats]` and get the first matching format, that was very useful - but now all given formats are downloaded. How do I set up preference order now (just one format needed) instead of requesting all formats?

My goal is to get the lowest possible quality of looong videos - without checking available formats of each video. Worked fine before :/ .

---

`-f 36,5,43,18`

---

Regards & respect

**Comment by dstftw** [comment]
Have you read [FAQ](https://github.com/rg3/youtube-dl#format-selection)?
