### ISSUE TITLE
Please support Picarto.tv

### ISSUE THREAD

**Issue by laichiaheng** [rg3/youtube-dl#6205]
Please support this site.
https://www.picarto.tv/

**Comment by yan12125** [comment]
Here are some texts from [FAQ](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient):

> Site support requests must contain an example URL.

The main page of a website is not enough. Please provide page URLs.

**Comment by StylinGreymon** [comment]
I'd also like to see this site supported.
https://picarto.tv/Sunibee

**Comment by TheAMM** [comment]
I've implemented an extractor and issued a pull request: #12514

**Comment by Serkan-devel** [comment]
Any updates on this?
