### ISSUE TITLE
Youtube video ID gets mangled

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#6220]
youtube-dl -f 'bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]/[height<=?480]' --write-sub --recode-video mp4 'https://www.youtube.com/watch?v=-7r4vMlBWo-w'
[youtube] -7r4vMlBWo-: Downloading webpage
[youtube] -7r4vMlBWo-: Downloading video info webpage
ERROR: -7r4vMlBWo-: YouTube said: This video does not exist.

Note that there is a trailing "w" in the source, but it got lost in the download

**Comment by yan12125** [comment]
AFAIK all youtube IDs are 11 characters. The video you provide https://www.youtube.com/watch?v=-7r4vMlBWo-w redirects to https://www.youtube.com/watch?v=-7r4vMlBWo-, and the latter video does not exist. Can you watch it in browsers?

**Comment by keybounce** [comment]
Hmm, looks like the link i was trying to follow may be in error ...

Ok, the video is at https://www.youtube.com/watch?v=7r4vMlBWo-w
so the leading "-" is in error.


On 2015-07-13, at 11:20 PM, Yen Chi Hsuan <notifications@github.com> wrote:

> AFAIK all youtube IDs are 11 characters. The video you provide https://www.youtube.com/watch?v=-7r4vMlBWo-w redirects to https://www.youtube.com/watch?v=-7r4vMlBWo-, and the latter video does not exist. Can you watch it in browsers?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

---
Entertaining minecraft videos
http://YouTube.com/keybounce

**Comment by yan12125** [comment]
For me this video can be downloaded correctly. Please close this issue if there's no other problems.
