### ISSUE TITLE
Direct "stream" from youtube

### ISSUE THREAD

**Issue by jonnyrobbie** [rg3/youtube-dl#6223]
Is there a way to directly stream currently downloading youtube video/audio (dash) to external player like mpv? Like livestremaer, but with support for 60fps?

**Comment by jaimeMF** [comment]
mpv can play dash formats: `mpv 'https://www.youtube.com/watch?v=T3ny9zIckP0' --ytdl-format 'bestvideo+bestaudio'`, but due to a problem in ffmpeg (I think) the duration is not correctly reported. Is that what you are looking for?

**Comment by jonnyrobbie** [comment]
It seems to be working, thanks.
