### ISSUE TITLE
How do i install youtube dl on windows

### ISSUE THREAD

**Issue by Russ3lHD** [rg3/youtube-dl#6225]
I have an root on wich i have run an musik bot of friese. Now i wanna installl youtube dl and it runs short and close it after it opens a window. I read i had to put an path in the config but how do i doo this. I you are the wrong support i will say sorry.

TIm

**Comment by dstftw** [comment]
youtube-dl is a standalone CLI executable that doesn't require installation. You can put youtube-dl.exe in any folder of choice and [add this folder to PATH env variable](https://www.java.com/en/download/help/path.xml) if you want it to be recognized as `youtube-dl` from any place.
