### ISSUE TITLE
How doest it work? I need minimum network and cpu activity for every day incremental scraping 

### ISSUE THREAD

**Issue by muhahacz** [rg3/youtube-dl#6227]
Hi, i have a question.
For example, how does ytdl work with these arguments?

    ./youtube-dl https://www.youtube.com/playlist?list=UUXIyz409s7bNWVcM-vjfdVA"-e --get-id --get-       duration --playlist-reverse --no-warnings  --download-archive ./blacklist 

I want to scrap every day only newest( actualy i dont download videos, i just need three atributes: name, lenght and id of youtube videos) videos from specific youtube playlist.
For first time it would take a while, i now, but other day, at the incremental scrap if i have a blacklist, (ids of already downloaded/saved videos) would it scrap it faster i guess, or may i accelerate this task? 
I want to do it with ~50 youtube channels/playlists every day. So it would be great if it would take minimum network and cpu activity.

Thanks

**Comment by jaimeMF** [comment]
The info for videos in the archive won't be extracted but currently it gets all the video ids from the playlist, which may take some time depending on its size (it use to need to download 1 webpage every 50 videos or so, I don't know if it has changed too much).

Note, I'd recommend you to use `--dump-json` for getting the info. For YouTube videos it may not be a problem, but if the duration is unknown `--get-duration` won't print any line (potentially breaking your script).
