### ISSUE TITLE
When using an external downloader, self._make_cmd is considered as a list, not a str

### ISSUE THREAD

**Issue by arter97** [rg3/youtube-dl#6228]
On Python 2.7.2 ported over Android, using an external downloader results in an error.
http://pastebin.com/iwUJ4cHm

Seems like _make_cmd function does not return the cmd as a str.
Using a simple workaround like "return str(cmd)" or "return str(cmd).encode()" still does not work
http://pastebin.com/wxWiYV2V

Please take a look and suggest me a fix.
Thanks :)

**Comment by dstftw** [comment]
`self._make_cmd` is expected to be a list.

**Comment by arter97** [comment]
I'm a little Python noob, so excuse me.
The message "TypeError: execv() arg 2 must contain only strings" says it did not get a str on subprocess.Popen.
If self._make_cmd is expected to be a list, where am I supposed to touch and fix?
