### ISSUE TITLE
Any way to make bestvideo prefer mp4 over webm?

### ISSUE THREAD

**Issue by parkerlreed** [rg3/youtube-dl#6229]
I'm wanting to always pull the "best mp4" regardless of video. I see there is a --prefer-free-formats option but nothing for preferring mp4. Is this possible currently?

**Comment by dstftw** [comment]
`-f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best`

**Comment by parkerlreed** [comment]
Thanks.
