### ISSUE TITLE
Jeuxvideo.com link is not detect as _VALID_URL

### ISSUE THREAD

**Issue by kadogo** [rg3/youtube-dl#6230]
Hi, I got an error with the next URL for jeuxvideo.com (I think it's a problem from _VALID_URL

youtube-dl --version
2015.07.07

youtube-dl http://www.jeuxvideo.com/videos/chroniques/434220/l-histoire-du-jeu-video-la-saturn.htm
[generic] l-histoire-du-jeu-video-la-saturn: Requesting header
WARNING: Falling back on generic information extractor.
[generic] l-histoire-du-jeu-video-la-saturn: Downloading webpage
[generic] l-histoire-du-jeu-video-la-saturn: Extracting information
ERROR: Unsupported URL: http://www.jeuxvideo.com/videos/chroniques/434220/l-histoire-du-jeu-video-la-saturn.htm

Cheers

**Comment by jaimeMF** [comment]
Fixed, thanks for the report.
