### ISSUE TITLE
Error extracting DASH manifest, Error403

### ISSUE THREAD

**Issue by luisfcorreia** [rg3/youtube-dl#6233]
youtube-dl https://www.youtube.com/watch?v=nUCoYcxNMBE --verbose
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=nUCoYcxNMBE', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.04
[debug] Python version 2.7.10 - Linux-4.0.7-300.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[youtube] nUCoYcxNMBE: Downloading webpage
[youtube] nUCoYcxNMBE: Downloading video info webpage
[youtube] nUCoYcxNMBE: Extracting video information
[youtube] {22} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {43} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {18} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {5} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {36} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {17} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {266} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {313} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {264} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {271} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {137} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {248} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {136} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {247} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {135} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {244} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {134} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {243} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {133} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {242} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {160} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {278} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {140} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {171} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {249} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {250} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {251} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] nUCoYcxNMBE: Downloading DASH manifest
[youtube] nUCoYcxNMBE: Downloading player https://s.ytimg.com/yts/jsbin/html5player-en_US-vflVsMRd_/html5player.js
[youtube] nUCoYcxNMBE: Downloading DASH manifest
WARNING: [youtube] nUCoYcxNMBE: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
WARNING: Requested formats are incompatible for merge and will be merged into mkv.

**Comment by dstftw** [comment]
Dupicate of #5118.
