### ISSUE TITLE
Add contributing file TL;DR

### ISSUE THREAD

**Issue by mikhaelkh** [rg3/youtube-dl#6237]
I think contributing.md is too big, and useful tips are hard to find (not really, but people are lazy). You should create short step-by-step guide how to report an issue.

**Comment by jaimeMF** [comment]
Do you have any specific addition that you think it would help?

Note that it's build from some [README sections](https://github.com/rg3/youtube-dl/blob/f848215dfce232dfc6618c1cc49da44c3f7df75a/README.md#bugs), so if you make a PR you have to edit the readme.

**Comment by mikhaelkh** [comment]
ISSUE_TEMPLATE.md is what I had in mind.
