### ISSUE TITLE
Broken for a certain youtube video, "unable to download video data"

### ISSUE THREAD

**Issue by pps** [rg3/youtube-dl#6238]
Trying to dl https://www.youtube.com/watch?v=8a5ID0x932I. Video works in browser, but download is broken with youtube-dl:

```
$ youtube-dl https://www.youtube.com/watch?v=8a5ID0x932I
[youtube] 8a5ID0x932I: Downloading webpage
[youtube] 8a5ID0x932I: Downloading video info webpage
[youtube] 8a5ID0x932I: Extracting video information
[youtube] 8a5ID0x932I: Downloading DASH manifest
[youtube] 8a5ID0x932I: Downloading DASH manifest
ERROR: unable to download video data: HTTP Error 404: Not Found
```

Not sure if this is specific to only this video.

**Comment by jaimeMF** [comment]
The problem is that on the YouTube player the video's highest quality is 360p but on the dash manifest it list 480p and higher. As a workaround you can use `-f '134+140'`or `-f best`. Since the last one works and it's a 720p file, I'd guess that eventually the other fomats will be available.

**Comment by pps** [comment]
Perfect, thanks.

As a suggestion: I've got a youtube-dl config file with lots of fallback options. Couldn't youtube-dl check the next worst option in such a case too?

**Comment by jaimeMF** [comment]
I guess it could be done, open a new issue if you want it.

**Comment by pps** [comment]
I'll consider it. Thanks.
