### ISSUE TITLE
Fine tuning fix for #6151

### ISSUE THREAD

**Issue by Asadullah-Ahmad** [rg3/youtube-dl#6245]
Can some contributor please look at https://github.com/rg3/youtube-dl/commit/a742c0096587c29851655d3f7ae7e44d496d6f0e and suggest why `_search_regex` is having issues with that string, so it can be cleaned up for a possible merge/pull.

I came up with that search string by trial and error and can't shake that warning off. If I don't pass `fatal=False` flag, it raises *RegexNotFoundError*. Otherwise, it extracts the `video_url` successfully while still warning that it didn't execute search properly. I tried substituting `.{30}` with the exact string, but that didn't make a difference.

**Comment by jaimeMF** [comment]
I guess that not all formats are available for each video so some of the regex won't be found. You should probably use `default=None` instead.
