### ISSUE TITLE
Soundcloud and Youtube downloading non-functional on latest builds

### ISSUE THREAD

**Issue by korgano** [rg3/youtube-dl#6254]
It worked on both perfectly about a month or so ago, but now it's just erroring out instead of downloading anything. I even updated to the latest version to see if it would solve the problems, but it hasn't solved anything.

Here's my log:
ERROR: Unable to download webpage: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> (caused by URLError(error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'),))
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
Usage: youtube-dl.exe [OPTIONS] URL [URL...]
Usage: youtube-dl.exe [OPTIONS] URL [URL...]
WARNING: Falling back on generic information extractor.
WARNING: The url doesn't specify the protocol, trying with http
WARNING: The url doesn't specify the protocol, trying with http
WARNING: [soundcloud] 199067458: fallback video format URL is invalid, skipping
WARNING: Falling back on generic information extractor.
WARNING: Falling back on generic information extractor.
ERROR: An extractor error has occured. (caused by KeyError(u'show',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: The url doesn't specify the protocol, trying with http
WARNING: Falling back on generic information extractor.
WARNING: video doesn't have subtitles
WARNING: [soundcloud] 172174388: fallback video format URL is invalid, skipping

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by korgano** [comment]
I figured it out. My legacy settings from a previous build were incompatible with the newest versions, so the program was erroring out in a way that didn't provide any verbose logging. Once I removed the settings, everything started working again.

**Comment by dstftw** [comment]
According to log you are misusing youtube-dl that is clearly stated in log, at least you are specifying wrong format_id with `-f` in some calls:
```ERROR: requested format not available```
and incorrectly run it at all in another calls:
```Usage: youtube-dl.exe [OPTIONS] URL [URL...]```
Since you've figured it out and are not willing to post the verbose log I'm closing this.
