### ISSUE TITLE
Videomega.tv download not working

### ISSUE THREAD

**Issue by dankunwizard** [rg3/youtube-dl#6260]
Hello,

I'm trying to download a video from videomega.tv but fails. I can watch the video from below URL.

"http://www.bada.tv/bada/modalController/detail/mv_no/1019031/main_yn//mv_cate0/1/context_search/%EC%83%81%EC%86%8D%EC%9E%90%EB%93%A4.E19.131211/"

Below is youtube-dl verbose output.

$ youtube-dl --verbose http://videomega.tv/view.php?ref=090051111052065112106089103052052103089106112065052111051090
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://videomega.tv/view.php?ref=090051111052065112106089103052052103089106112065052111051090']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.8 - CYGWIN_NT-6.3-1.7.32-0.274-5-3-x86_64-64bit
[debug] exe versions: ffmpeg N-65142-gd76675d, ffprobe N-65142-gd76675d
[debug] Proxy map: {}
[generic] view: Requesting header
WARNING: Could not send HEAD request to http://videomega.tv/view.php?ref=090051111052065112106089103052052103089106112065052111051090: HTTP Error 404: Not Found
[generic] view: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1729, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
http://videomega.tv/view.php?ref=090051111052065112106089103052052103089106112065052111051090 gives me 404. Can you watch it by this link (not http://www.bada.tv/bada/modalController/detail/mv_no/1019031/main_yn//mv_cate0/1/context_search/%EC%83%81%EC%86%8D%EC%9E%90%EB%93%A4.E19.131211/)?

**Comment by dankunwizard** [comment]
No. For some reason it works only from this site "http://www.bada.tv/bada/modalController/detail/mv_no/1019031/main_yn//mv_cate0/1/context_search/%EC%83%81%EC%86%8D%EC%9E%90%EB%93%A4.E19.131211/".

I've captured HTTP headers comparing via bada.tv and direct access. After comparison I tried again with --user-agent and --referer options but no luck.

Via bada.tv
_________________________________________
http://videomega.tv/view.php?ref=090051111052065112106089103052052103089106112065052111051090

GET /view.php?ref=090051111052065112106089103052052103089106112065052111051090 HTTP/1.1
Host: videomega.tv
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://www.bada.tv/bada/modalController/detail/mv_no/1019031/main_yn//mv_cate0/1/context_search/%EC%83%81%EC%86%8D%EC%9E%90%EB%93%A4.E19.131211/
Connection: keep-alive

HTTP/1.1 200 OK
Date: Fri, 17 Jul 2015 20:23:56 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d193b031287db022371a19aaf592ed0c01437164635; expires=Sat, 16-Jul-16 20:23:55 GMT; path=/; domain=.videomega.tv; HttpOnly
Set-Cookie: __qjtra=z3o4apjyg4; expires=Fri, 17-Jul-2015 20:29:04 GMT
X-Powered-By: PHP/5.3.3
P3P: policyref="http://www.example.com/w3c/p3p.xml", CP="CURa ADMa DEVa CONo HISa OUR IND DSP ALL COR"
Server: cloudflare-nginx
CF-RAY: 2078aadd2f9118f6-AKL
Content-Encoding: gzip
_________________________________________


Direct access
_________________________________________
http://videomega.tv/view.php?ref=090051111052065112106089103052052103089106112065052111051090

GET /view.php?ref=090051111052065112106089103052052103089106112065052111051090 HTTP/1.1
Host: videomega.tv
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Cookie: __cfduid=d193b031287db022371a19aaf592ed0c01437164635; __qjtra=z3o4apjyg4
Connection: keep-alive

HTTP/1.1 302 Found
Date: Fri, 17 Jul 2015 20:24:58 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.3.3
P3P: policyref="http://www.example.com/w3c/p3p.xml", CP="CURa ADMa DEVa CONo HISa OUR IND DSP ALL COR"
Location: http://videomega.tv/404.php
Set-Cookie: __hodjg=z3o4apjyg4; expires=Fri, 17-Jul-2015 20:30:06 GMT
Server: cloudflare-nginx
CF-RAY: 2078ac606d3818f6-AKL
_________________________________________

**Comment by dstftw** [comment]
Should be fixed in the next version. Note that when downloading video from videomega with youtube-dl no other program (e.g. browser) should access this video, since look like videomega allows only single session per video file.
