### ISSUE TITLE
Twitch extractor breaks when uppercase letters used in URL

### ISSUE THREAD

**Issue by iamgreaser** [rg3/youtube-dl#6263]
This occurs in 2015.07.07.

Twitch usernames appear to be case-insensitive, but if you get fed a URL with an uppercase username you get a 404 error when it tries to fetch the m3u8 playlist.

The theoretical solution would be to downcase the username fed into the m3u8 URL.

Example:

* Works: http://www.twitch.tv/twitchplayspokemon
* Broken: http://www.twitch.tv/TWITCHPLAYSPOKEMON

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by iamgreaser** [comment]
Just edited the initial post.

**Comment by dstftw** [comment]
This issue will be fixed in the next version. Thanks for the report.
