### ISSUE TITLE
Rtmpdump?

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#6265]
I attempted to download a video series from Crunchyroll.

youtube-dl -f 'bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]/[height<=?480]' --write-sub --recode-video mp4 http://www.crunchyroll.com/is-it-wrong-to-try-to-pick-up-girls-in-a-dungeon
[crunchyroll:playlist] is-it-wrong-to-try-to-pick-up-girls-in-a-dungeon: Downloading webpage
[download] Downloading playlist: Is It Wrong to Try to Pick Up Girls in a Dungeon?
[crunchyroll:playlist] playlist Is It Wrong to Try to Pick Up Girls in a Dungeon?: Collected 13 video ids (downloading 13 of them)
[download] Downloading video 1 of 13
[Crunchyroll] 678135: Downloading webpage
[Crunchyroll] 678135: Downloading media info
[Crunchyroll] 678135: Downloading media info for 360p
[Crunchyroll] 678135: Downloading media info for 480p
[Crunchyroll] 678135: Downloading media info for 720p
[Crunchyroll] 678135: Downloading media info for 720p
[Crunchyroll] 678135: Downloading media info for 1080p
[Crunchyroll] 678135: Downloading media info for 1080p
[Crunchyroll] 678135: Downloading subtitles for English (US)
[Crunchyroll] 678135: Downloading subtitles for Español
[Crunchyroll] 678135: Downloading subtitles for Português (Brasil)
[Crunchyroll] 678135: Downloading subtitles for العربية
[info] Writing video subtitles to: Is It Wrong to Try to Pick Up Girls in a Dungeon Episode 1 – Bell Cranel _ Adventurer.arME.ass
[download] Destination: Is It Wrong to Try to Pick Up Girls in a Dungeon Episode 1 – Bell Cranel _ Adventurer.flv
ERROR: RTMP download detected but "rtmpdump" could not be run. Please install it.

So, some questions:
1. What is rtmpdump / where do I get it? (Mac).
2. How can I tell it to only fetch english subtitles?
3. I only need/want 480p, and it's fetching information for all sizes; is that normal, or do I have an error in my format spec?
4. Is there a way to fetch the original audio, and english subtitles?

**Comment by dstftw** [comment]
1. `brew install rtmpdump`
2. For crunchyroll that is not possible currently (#6264), all subtitles will be fetched during extraction. To save english subtitles use `--sub-lang enUS`. Use `--list-sub` to list all subtitles' codes.
3. That is expected - that's only information.
4. If there is a separated audio (`-f bestaudio`) otherwise you can only extract audio stream from videos (`--extract-audio`).

**Comment by keybounce** [comment]
Thank you.
