### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 410: Gone and bad option flag

### ISSUE THREAD

**Issue by phenom128** [rg3/youtube-dl#6269]
istr this happening before, an upgrade fixed??
stephen@i7:~$ youtube-dl --verbose --match-title wanhao https://www.youtube.com/user/vernonbarry/videos
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--match-title', 'wanhao', 'https://www.youtube.com/user/vernonbarry/videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.1
[debug] Proxy map: {}
[download] Downloading playlist: vernonbarry
[youtube:user] vernonbarry: Downloading video ids from 1 to 51
ERROR: Unable to download webpage: HTTP Error 410: Gone; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 203, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1231, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

tried this as well

youtube-dl --verbose --callhome --match-title wanhao https://www.youtube.com/user/vernonbarry/videos
Usage: youtube-dl [options] url [url...]

youtube-dl: error: no such option: --callhome
youtube-dl: error: no such option: --call-home

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by phenom128** [comment]
apols, should take my own advice:-)
i've just rebuilt it from github zip and all ok
stephen
