### ISSUE TITLE
Can't retrive video from culturebox website

### ISSUE THREAD

**Issue by abrahampersil** [rg3/youtube-dl#6272]
hello,

Just a report to ask for Culturebox support, which starts to have some content in France. I got an error and was requested to report that:

youtube-dl http://culturebox.francetvinfo.fr/live/musique/chanson-francaise/alcaline-le-concert-avec-calogero-212305 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://culturebox.francetvinfo.fr/live/musique/chanson-francaise/alcaline-le-concert-avec-calogero-212305', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.9 - Linux-4.1.0-1-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 2.5.7-0ubuntu0.15.04.1, ffprobe 2.5.7-0ubuntu0.15.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[culturebox.francetvinfo.fr] live/musique/chanson-francaise/alcaline-le-concert-avec-calogero-212305: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/francetv.py", line 286, in _real_extract
    r'"http://videos\.francetv\.fr/video/([^@]+@[^"]+)"', webpage, 'video id').split('@')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks for your help :)

Abraham.

**Comment by dstftw** [comment]
There are no videos on this page for me. Can you watch it in browser?

**Comment by abrahampersil** [comment]
No, but I was thinking it was linked to flash, sorry.

I can see the video there: http://www.tsprod.com/replay-du-concert-alcaline-de-calogero , but indeed, website not supported (even if it's embedded from somewhere else)

**Comment by dstftw** [comment]
Closing this then. You can create a new issue if you want tsprod to be supported.

**Comment by dstftw** [comment]
Francetv embeds (in particular tsprod.com) will be supported in the next version.
