### ISSUE TITLE
Can't download "Popular videos" playlist from YouTube user

### ISSUE THREAD

**Issue by jgluck** [rg3/youtube-dl#6287]
Running the following

```
youtube-dl "https://www.youtube.com/watch?v=3Awwne_NpJQ&list=PULx053rWZxCiYWsBETgdKrQ" --verbose
```

results in: 

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?    v=3Awwne_NpJQ&list=PULx053rWZxCiYWsBETgdKrQ', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.18
[debug] Python version 2.7.8 - Darwin-14.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PULx053rWZxCiYWsBETgdKrQ - add --no-playlist to just download video 3Awwne_NpJQ
[youtube:playlist] PULx053rWZxCiYWsBETgdKrQ: Downloading webpage
WARNING: [youtube:playlist] Youtube gives an alert message: Unknown error.
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1423, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1398, in _extract_playlist
    page, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 566, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 557, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jaimeMF** [comment]
If you are only interested in the video you can run `youtube-dl 'https://www.youtube.com/watch?v=3Awwne_NpJQ&list=PULx053rWZxCiYWsBETgdKrQ' --no-playlist`.

**Comment by jgluck** [comment]
Ah, it's the playlist I'm interested in though. Is there a better formatted URL for the same resources?

**Comment by jaimeMF** [comment]
The problem is that it's automatically generated and https://www.youtube.com/playlist?list=PULx053rWZxCiYWsBETgdKrQ doesn't work (that's what youtube-dl tries to use). We'll have to add support for it.

**Comment by jgluck** [comment]
Ah, that makes sense. If I manually create a playlist from the included videos, it should be able to extract them though? I can do that as a work-around if so.

(Thanks for the super quick responses.)

**Comment by jaimeMF** [comment]
>  If I manually create a playlist from the included videos, it should be able to extract them though?

Yes, normal playlists should work fine.

**Comment by jgluck** [comment]
Perfect, thanks.

**Comment by yan12125** [comment]
@jgluck The original problem is not solved yet. I guess this issue may affect other users, too. Would you like to reopen it?

**Comment by jgluck** [comment]
Sure I'll reopen it. Wasn't sure if it would be better to start a new ticket and reference this one or continue with this ticket.

**Comment by yan12125** [comment]
It's OK to continue this ticket.

**Comment by Oso-de-Oro** [comment]
Has this feature not been implemented yet? If not, I'd like to work on it if that's cool.

**Comment by Oso-de-Oro** [comment]
Actually, I believe this issue should be closed. I just tried the link from OP and it downloads the full playlist just fine now.

**Comment by yan12125** [comment]
This issue should be kept open as http://video.caixin.com/2016-11-10/101006167.html is still not supported.
