### ISSUE TITLE
I Can't Download Video

### ISSUE THREAD

**Issue by bilenyok** [rg3/youtube-dl#6288]
I get this error today, why?

![untitled](https://cloud.githubusercontent.com/assets/10195528/8766077/f7762782-2e32-11e5-9ed7-deab7177eef5.png)

**Comment by yan12125** [comment]
This is already fixed and will be available in the next version.
You can also fix this by updating python to 2.7.4 or later. Or you can use previous version `https://yt-dl.org/downloads/2015.07.07/youtube-dl`.
