### ISSUE TITLE
Adding support for GOD TV

### ISSUE THREAD

**Issue by malhonen** [rg3/youtube-dl#6299]
I would like to request you to add support for GOD TV, a Christian broadcasting service available at http://god.tv/. Here is an example URL of a video which fails to download with the generic extractor of youtube-dl 2015.07.18 on Linux amd64 ("Unsupported URL"):

http://god.tv/awakening-europe/video/awakening-europe/day-1-opening-session

By examining the source code of this page, I found a piece of JavaScript which says:

"ooyala": { "embed_type": "1", "content_id": "U1OGw2djo_XPbd9H1IWyZpRcg3UOlbr9" }

Apparently, the site's video streaming technology is provided by Ooyala if that helps any.

Thank you!

**Comment by dstftw** [comment]
god.tv will be supported in the next vesrsion.
