### ISSUE TITLE
[PornHD] ERROR: Unable to extract sources;

### ISSUE THREAD

**Issue by mrthrowaway** [rg3/youtube-dl#6305]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.pornhd.com/videos/4860/jenna-presley-is-a-horny-bombshell-hd-porn-video', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.18
[debug] Git HEAD: 2fe1ff8
[debug] Python version 2.7.6 - Linux-3.13.0-58-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg N-73632-g39a04eb, ffprobe N-73632-g39a04eb
[debug] Proxy map: {}
[PornHd] jenna-presley-is-a-horny-bombshell-hd-porn-video: Downloading webpage
ERROR: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/mrthrowaway/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/home/mrthrowaway/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/home/mrthrowaway/youtube-dl/youtube_dl/extractor/pornhd.py", line 50, in _real_extract
    webpage, 'sources')))
  File "/home/mrthrowaway/youtube-dl/youtube_dl/extractor/common.py", line 557, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

------------------
editing the regex to r"(?s)'sources'\s*:\s*(\{.+?\})\s*[;,)]" seems to get it to work

**Comment by dstftw** [comment]
Works fine with latest version.
