### ISSUE TITLE
/usr/bin/youtube-dl: 1: Syntax error: newline unexpected

### ISSUE THREAD

**Issue by vandana-iyer** [rg3/youtube-dl#631]
Upgraded youtube-dl using the command sudo youtube-dl -U. It got updated to version 9999.99.99.
When I try to download videos, I keep getting the error: 
/usr/bin/youtube-dl: 1: Syntax error: newline unexpected
After the upgrade, "sudo youtube-dl -U" too throws the same error.

**Comment by iyushaw** [comment]
I am using `python3 --version
Python 3.11.4
`
`Linux 14-IIL 6.2.0-26-generic #26-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 23:39:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`
`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.04
DISTRIB_CODENAME=lunar
DISTRIB_DESCRIPTION="Ubuntu 23.04"`

and am having same error.

**Comment by jbjorge** [comment]
It is probably due to the file being blocked by EU.
This also means that a bad actor could just inject some runnable code which most people will run if they follow the installation instructions 😬

`▶ cat /usr/local/bin/youtube-dl`
```
<h1>Access denied</h1>

<p>
  Due to a <a href="https://openjur.de/u/2466945.html" target="_blank">ruling</a> of the Hamburg Regional Court, access to this website is blocked.
</p>

<hr />

<h1>Zugriff gesperrt</h1>

<p>
  Aufgrund eines <a href="https://openjur.de/u/2466945.html" target="_blank">Urteils</a> des Landgerichts Hamburg ist der Zugriff auf diese Website gesperrt.
</p>
```

**Comment by adelynx** [comment]
I did had the same issue today, I solve it by installing the bin using pip instead curl or wget.

**Comment by whompyjaw** [comment]
Ya having same issue with python3.11.4 using the curl instructions on the readme.

**Comment by sharkwouter** [comment]
I can reproduce this when trying to download a Youtube playlist with the version I got from the curl install.

**Comment by phi0x** [comment]
> cat /usr/local/bin/youtube-dl

simply download from:
https://github.com/ytdl-org/youtube-dl/releases

**Comment by dirkf** [comment]
No, use the nightly release for now: #30839.

**Comment by dirkf** [comment]
Also, @iyushaw, it's not likely that a one-off release bug from 10 years ago would have suddenly recurred. Instead of necroposting in a probably irrelevant issue, it would be better to have followed the bug reporting procedure which would have led you to the actual solution. Other posters should have done the same and pointed to the solution.

**Comment by acassis** [comment]
@dirkf probably this is the issue he is facing:

```
$ sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl

$ cat /usr/local/bin/youtube-dl
<h1>Access denied</h1>

<p>
  Due to a <a href="https://openjur.de/u/2466945.html" target="_blank">ruling</a> of the Hamburg Regional Court, access to this website is blocked.
</p>

<hr />

<h1>Zugriff gesperrt</h1>

<p>
  Aufgrund eines <a href="https://openjur.de/u/2466945.html" target="_blank">Urteils</a> des Landgerichts Hamburg ist der Zugriff auf diese Website gesperrt.
</p>
```

**Comment by dirkf** [comment]
We all know what [issue](https://github.com/ytdl-org/youtube-dl/issues/631#issuecomment-1677316232) was being [reported](https://github.com/ytdl-org/youtube-dl/issues/631#issuecomment-1674417013). It has nothing to do with this issue which was solved and closed 10 years ago.

**Comment by sharkwouter** [comment]
@iyushaw Access to youtube-dl is actually blocked for legal reasons in Germany. I found that yt-dlp works fine, though. You can find it here: https://github.com/yt-dlp/yt-dlp

**Comment by dirkf** [comment]
Necroposting: 
>phihag closed this as completed Jan 12, 2013

Solution:
https://github.com/ytdl-org/youtube-dl/issues/631#issuecomment-1747278538

Explanation:
https://github.com/ytdl-org/youtube-dl/issues/631#issuecomment-1677316232

Relevant master issue: #32495 (and not this one)
