### ISSUE TITLE
Vevo said: Hmm, something went sideways! Please try another video.

### ISSUE THREAD

**Issue by g8keepa** [rg3/youtube-dl#6310]
Hey .. Long time user, first time poster.

Running MacOS 10.9.5 (Mavericks), here's what I get:

[Vevo] Retrieving oauth token
[Vevo] USUV71302440: Downloading JSON metadata
ERROR: Vevo said: Hmm, something went sideways! Please try another video.

Here's what I get in --verbose mode:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.vevo.com/watch/USUV71302440']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.18
[debug] Python version 2.7.9 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Vevo] Retrieving oauth token
[Vevo] USUV71302440: Downloading JSON metadata
ERROR: Vevo said: Hmm, something went sideways! Please try another video.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vevo.py", line 180, in _real_extract
    raise ExtractorError('%s said: %s' % (self.IE_NAME, response['statusMessage']), expected=True)
ExtractorError: Vevo said: Hmm, something went sideways! Please try another video.

Any ideas?

**Comment by jaimeMF** [comment]
Sorry for not checking the issue sooner. It's working for me currently, it could be a temporary error. If it still fails, can you play it on a browser?
