### ISSUE TITLE
Crunchyroll extractor look break

### ISSUE THREAD

**Issue by kadogo** [rg3/youtube-dl#6314]
Hi, yesterday it work without problems but today seem very strange.

Youtube-dl version : youtube-dl is up-to-date (2015.07.18)

I try a premium episode (I'm premium and use netrc to authentification).
https://zerobin.net/?a3502ee8836b8993#BIRmMlQHk4sxM0H/KQb1FD1HRclw0JWYsSfK8lNhJEM=

I try a older episode
https://zerobin.net/?76bb6004c2087c74#cZqSxHbmAPJxH/ilzIwjtpP5pcu6hMOiCHOqBYem47I=

Thanks for all.

**Comment by dstftw** [comment]
Post the *.dump files you'll get when running youtube-dl with `--write-pages`.

**Comment by kadogo** [comment]
Here the dump file for episode 3 and episode 2

https://zerobin.net/?bdbaf1c4241da595#mxMbokuANqbI+TIpdstwSLby5MQZZ5DROpW82jppBpg=
https://zerobin.net/?e70be5715a93e27a#jHly/+qwRcpWpYK+/+3FBdORb/1AInn2tFjpSsjVta8=

https://zerobin.net/?7cabfd35feb7c38f#qoGY5+T79vT4Fsh53212OlsuzKcUgq2EMZ5Os3+xZdU=
https://zerobin.net/?f98047d290cebd77#nCEHkrzIG5fI9esYoF7zyiXpVv+djZ8mDa3GmaW0m8w=
https://zerobin.net/?70d0a77e25a0457a#F+u5AC8O0n2czQnE30pjH3C5ir0jt9BPeg10b1J88/E=

**Comment by kadogo** [comment]
Sorry I missed one for episode 2
https://zerobin.net/?0c09adab55d0a07c#U68/EschZqDX6lDzqpsVb+8AGjXvevUqqeyM2ab+GXA=

**Comment by dstftw** [comment]
Can you download another premium videos? Doesn't your premium expired or so?

**Comment by kadogo** [comment]
Strange I juste tried this => http://www.crunchyroll.com/ace-of-the-diamond/episode-16-chain-reaction-678619

It work without problems (online and with youtube-dl).
But the episode 3 of gansta not work with youtube-dl (it work well online).

**Comment by kadogo** [comment]
Late me know if you need something other to determine the problem for gangsta's episodes.

**Comment by dstftw** [comment]
Can you try with latest version from master?

**Comment by kadogo** [comment]
I just tried.

First I update:
$ sudo youtube-dl -U
youtube-dl is up-to-date (2015.09.03)

I test the last epidode of this week:
https://zerobin.net/?b1309516db2de9eb#/+Hvto+fWG0Llcdsw/NWXfbLZnHpDC94/vGXY5iNujg=

I test the older episode too:
https://zerobin.net/?68ff8f3079ab5903#xxb/gUVI2Agy6Q1ZahVG3ZSF2SONnCowsoEI4xMzT2E=

(I tried an other episode too to verify my netrc auth)
https://zerobin.net/?19110985f9146305#/YNnp/Xavcehs0iZmYq2VpMRvzci6oPAxy+p4qpHQNg=

**Comment by dstftw** [comment]
It's not yet released. You need to check with version from repository.

**Comment by kadogo** [comment]
Ah ok, I try again.

**Comment by kadogo** [comment]
It's good I think.
I late you keep a look at the debug to be sure.

https://zerobin.net/?373734ac01d20f06#YycHEPI09Ymqf1duHOBQttWqY9N/cDEUFx5lJYP6e7k=

**Comment by dstftw** [comment]
And for http://www.crunchyroll.com/gangsta/episode-3-ergastulum-682687?

**Comment by kadogo** [comment]
It's ok, thanks for all ^^ !!!
https://zerobin.net/?89f677872b8a86b9#b48ijP+1HRY8q667cMgXg44yYD+Y4cGzTYb6fL/0fjA=

**Comment by dstftw** [comment]
Ok, I'm closing this then.
