### ISSUE TITLE
udemy playlist download

### ISSUE THREAD

**Issue by mefromthepast** [rg3/youtube-dl#6327]
Not sure if it should be possible to use udemy, though. Error report is "RegexNotFoundError: Unable to extract login-form form"

If you want to reproduce the bug or are interested in the topic, you can currently register for the series for free: https://www.udemy.com/learn-the-basics-of-ethical-hacking-and-penetration-testing/?couponCode=freebuf

user@host:~$ youtube-dl https://www.udemy.com/learn-the-basics-of-ethical-hacking-and-penetration-testing/ --username [username] --password [password] --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.udemy.com/learn-the-basics-of-ethical-hacking-and-penetration-testing/', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.8 - Linux-3.16.0-43-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as [username]
[udemy:course] learn-the-basics-of-ethical-hacking-and-penetration-testing: Downloading course JSON
[udemy:course] 27276: Enrolling in the course
[udemy:course] 27276: Already enrolled in
[udemy:course] 27276: Downloading course curriculum
[download] Downloading playlist: Learn The Basics of Ethical Hacking and Penetration Testing
[udemy:course] playlist Learn The Basics of Ethical Hacking and Penetration Testing: Collected 55 video ids (downloading 55 of them)
[download] Downloading video 1 of 55
[udemy] Downloading login popup
ERROR: Unable to extract login-form form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 274, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 268, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 68, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 83, in _login
    login_form = self._form_hidden_inputs('login-form', login_popup)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 726, in _form_hidden_inputs
    html, '%s form' % form_id, group='form')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 557, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract login-form form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This issue will be fixed in the next version. Thanks for the report.
