### ISSUE TITLE
Unable to extract video from rts.ch

### ISSUE THREAD

**Issue by tristelune1** [rg3/youtube-dl#6332]
Hello,

I want to download some videos from http://www.rts.ch and for some links it doesn't work. For example, in the following:

http://www.rts.ch/sport/golf/6958198-golf-sergio-garcia-en-vedette-a-crans-montana.html

it doesn't work and on this one:

http://www.rts.ch/play/tv/meteo-midi/video/meteo-midi?id=6957946

it works. 

I get the following from the first link:

% youtube-dl http://www.rts.ch/sport/golf/6958198-golf-sergio-
garcia-en-vedette-a-crans-montana.html
[RTS] golf-sergio-garcia-en-vedette-a-crans-montana: Downloading JSON metadata
[RTS] golf-sergio-garcia-en-vedette-a-crans-montana: Downloading webpage
ERROR: Unable to extract internal video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

The verbose version is:

% youtube-dl --verbose http://www.rts.ch/sport/golf/6958198-golf-sergio-garcia-en-vedette-a-crans-montana.html 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.rts.ch/sport/golf/6958198-golf-sergio-garcia-en-vedette-a-crans-montana.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21-gentoo_no_offensive_sites
[debug] Python version 2.7.10 - Linux-3.18.11-gentoo-x86_64-Intel-R-_Core-TM-_i3-2310M_CPU_@_2.10GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.7, ffprobe 2.7
[debug] Proxy map: {}
[RTS] golf-sergio-garcia-en-vedette-a-crans-montana: Downloading JSON metadata
[RTS] golf-sergio-garcia-en-vedette-a-crans-montana: Downloading webpage
ERROR: Unable to extract internal video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/rts.py", line 148, in _real_extract
    'internal video id')
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 566, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 557, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract internal video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I have seen there is another bug (https://github.com/rg3/youtube-dl/issues/5099), but because the error is not the same I have open a new bug. 

Just tell me if you need more inputs.

**Comment by dstftw** [comment]
Can find any video on http://www.rts.ch/sport/golf/6958198-golf-sergio-garcia-en-vedette-a-crans-montana.html.

**Comment by tristelune1** [comment]
I'm not sure to understand: you can or you can't find a video ? If you can, which arguments do you use ?

**Comment by dstftw** [comment]
Sorry, mistyped it. I **can't** find any video on this page, what do you expect youtube-dl to download from [this URL](http://www.rts.ch/sport/golf/6958198-golf-sergio-garcia-en-vedette-a-crans-montana.html)?

**Comment by tristelune1** [comment]
The videos on the right of the page. When I click on them I can watch them on my web browser. As I can see, the url doesn't change.

**Comment by dstftw** [comment]
Those videos are not related to 6958198-golf-sergio-garcia-en-vedette-a-crans-montana article.

**Comment by tristelune1** [comment]
Could you just explain me in a few words why ? Is it because youtube-dl doesn't find the video ? Or is there a way, for example by looking at the page source to know if the video is part of the page.

**Comment by dstftw** [comment]
Articles with videos on the right hand side will be supported in the next version. Example you provided was misleading since it has videos from different dates and they look unrelated to the article itself. Exploring another articles of similar layout I've find out some that are definetely relevant to the article.

**Comment by tristelune1** [comment]
Ok, thank you for your help!
