### ISSUE TITLE
[Udemy] Uable to extract login-form form

### ISSUE THREAD

**Issue by maor700** [rg3/youtube-dl#6335]
C:\Users\Maoran\Desktop\YouTube_Downloader\WF\udemy>C:\Users\Maoran\Desktop\YouT
ube_Downloader\WF\youtube-dl.exe -U --autonumber-size 2 -o  "C:\Users\Maoran\Des
ktop\YouTube_Downloader\Videos\%(playlist)s\%(playlist_index)s_%(title)s.%(ext)s
"  --username ********** --password *********** --write-sub  --sub-lang iw,
en --format best  "https://www.udemy.com/vocal-warm-up/?dtcode=0R9vVCg3jRji"
youtube-dl is up-to-date (2015.07.21)
[udemy:course] Downloading login popup
[udemy:course] Logging in as ***************
[udemy:course] vocal-warm-up: Downloading course JSON
[udemy:course] 65958: Enrolling in the course
[udemy:course] 65958: Already enrolled in
[udemy:course] 65958: Downloading course curriculum
[download] Downloading playlist: Professional Vocal Warm Up
[udemy:course] playlist Professional Vocal Warm Up: Collected 7 video ids (downl
oading 7 of them)
[download] Downloading video 1 of 7
[udemy] Downloading login popup
ERROR: Unable to extract login-form form; please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  t
o update. Be sure to call youtube-dl with the --verbose flag and include its com
plete output.

**Comment by dstftw** [comment]
This is already fixed and will be incorporated in the next version.

**Comment by maor700** [comment]
They changed the id of the input fields. maybe this is the reason.

**Comment by maor700** [comment]
thanx,
When the next version will be released?

**Comment by dstftw** [comment]
When the mantainer will have time.
