### ISSUE TITLE
cloudy -  Unable to extract file_key

### ISSUE THREAD

**Issue by huzaynr** [rg3/youtube-dl#6336]
Hi Team..

   Using yt-dl in windows, and executed following command:
youtube-dl --verbose --dump-intermediate-pages https://www.cloudy
.ec/embed.php?id=fcc33dd720e84
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--dump-intermediate-pages', u'https:
//www.cloudy.ec/embed.php?id=fcc33dd720e84']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Cloudy] fcc33dd720e84: Downloading webpage
[Cloudy] Dumping request to http://www.cloudy.ec/embed.php?id=fcc33dd720e84
PCFET0NUWVBFIGh0bWwgUFVCTElDICItLy9XM0MvL0RURCBIVE1MIDQuMDEvL0VOIj4KPGh0bWw+Cjxo
ZWFkPHRpdGxlPjwvdGl0bGU+PC9oZWFkPgo8Ym9keT4KICAKICA8IS0tVGhpcyBpcyBhIGNvbW1lbnQu
IENvbW1lbnRzIGFyZSBub3QgZGlzcGxheWVkIGluIHRoZSBicm93c2VyLS0+CiAgCjwvYm9keT4KPC9o
dG1sPg0K
ERROR: Unable to extract file_key; please report this issue on https://yt-dl.org
/bug . Make sure you are using the latest version; type  youtube-dl -U  to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete o
utput.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 656, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\cloudy.pyo", line 109, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 557, in _search_regex
RegexNotFoundError: Unable to extract file_key; please report this issue on http
s://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl
 -U  to update. Be sure to call youtube-dl with the --verbose flag and include i
ts complete output.

**Comment by yan12125** [comment]
Can you watch the video in browsers?

**Comment by huzaynr** [comment]
Yes Hsuan.. I could watch it on browser..

**Comment by huzaynr** [comment]
As per the page-source:

cid:"1", numOfErrors: "0", cid2: "", cid3:"", user:"", pass:"", domain: "
http://www.cloudy.ec",* key:
"115.249.242.252-dee3ae3d4ef0b7836a57535f8d672435-"*,
file:"fcc33dd720e84", crk:"1",
skin : "/play/skins/gblue.xml",

**Comment by yan12125** [comment]
Which browser are you using?

**Comment by huzaynr** [comment]
Google Chrome

**Comment by yan12125** [comment]
Does the following command work for you?
```
youtube-dl --verbose --user-agent "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36" "https://www.cloudy.ec/embed.php?id=fcc33dd720e84"
```

**Comment by huzaynr** [comment]
It's working like charm now :-) ..Thanks a lot Yen!!!

youtube-dl --verbose --user-agent "Mozilla/5.0 (Windows NT 6.1) A
ppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"
https://
www.cloudy.ec/embed.php?id=fcc33dd720e84
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--user-agent', u'Mozilla/5.0
(Window
s NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0
Safari/537.3
6', u'https://www.cloudy.ec/embed.php?id=fcc33dd720e84']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Cloudy] fcc33dd720e84: Downloading webpage
[Cloudy] fcc33dd720e84: Downloading player data
[Cloudy] fcc33dd720e84: Checking video URL
[debug] Invoking downloader on u'
http://5.104.175.82/dl/de3257c66b60558c07e22962
ee3dceb2/55b0a6fe/ff2c31723e611cd0aabe981c778250314b.flv'
[download] Destination: Premz-fcc33dd720e84.flv
[download]  15.8% of 634.28MiB at 136.02KiB/s ETA 01:06:58

**Comment by yan12125** [comment]
Does the original command (without ```--user-agent```) work? I'd like to know whether it's a temporary issue or we need a permanent change.

**Comment by huzaynr** [comment]
This is working without --user-agent now.. Thanks!

C:\Users\riyas>youtube-dl.exe --verbose
https://www.cloudy.ec/embed.php?id=fcc3
dd720e84

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'
https://www.cloudy.ec/embed.php?id=
cc33dd720e84']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Cloudy] fcc33dd720e84: Downloading webpage
[Cloudy] fcc33dd720e84: Downloading player data
[Cloudy] fcc33dd720e84: Checking video URL
[debug] Invoking downloader on u'
http://185.27.238.138/dl/918d47b76e4c27b0467c8
b733b1ed20/55b0aec3/ff2c31723e611cd0aabe981c778250314b.flv'
[download] Destination: Premz-fcc33dd720e84.flv
[download]   0.5% of 634.28MiB at 139.96KiB/s ETA 01:16:58

**Comment by yan12125** [comment]
Thanks for the help. I'm closing this issue now, If you encounter other problems, feel free to open a new issue.

**Comment by huzaynr** [comment]
Thanks to you too for the Help Yen!!..
