### ISSUE TITLE
Aptik not recognising youtube-dl as a package installed using apt-get

### ISSUE THREAD

**Issue by msj2** [rg3/youtube-dl#6344]
Ubuntu 14

I need to remove Ubuntu, as I need dual boot of Windows 7 & Ubuntu.

I tried to backup all PPA packages using Aptik, but it didn't show youtube-dl

**Comment by jaimeMF** [comment]
How did you install youtube-dl? Have you ever updated youtube-dl by running `youtube-dl -U`?

**Comment by dstftw** [comment]
This sounds like out of scope of youtube-dl. You may refer our FAQ for instructions on [installation](https://github.com/rg3/youtube-dl/blob/master/README.md#installation) or [updating](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl). Note that youtube-dl in the official Ubuntu 14 repos is outdated.
