### ISSUE TITLE
BBC iPlayer broken.

### ISSUE THREAD

**Issue by Nurple** [rg3/youtube-dl#6345]
Heya, it seems the iPlayer extractor is broken.

youtube-dl -F --verbose http://www.bbc.co.uk/iplayer/episode/b062nqpd/
[debug] System config: []
[debug] User config: [u'-o %(title)s.%(ext)s', u'--console-title', u'--ignore-errors', u'--no-overwrites', u'--prefer-ffmpeg', u'--write-description', u'-f', u'bestvideo[height<=?1080]+bestaudio/best']
[debug] Command-line args: [u'-F', u'--verbose', u'http://www.bbc.co.uk/iplayer/episode/b062nqpd/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-73510-g033dc39, ffprobe N-73510-g033dc39, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] b062nqpd: Downloading video page
[bbc.co.uk] b062nq8w: Downloading media selection XML
ERROR: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 656, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\bbccouk.pyo", line 361, in _real_extract
  File "youtube_dl\extractor\bbccouk.pyo", line 281, in _download_media_selector
  File "youtube_dl\extractor\bbccouk.pyo", line 218, in _extract_video
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by dstftw** [comment]
This issue will be fixed in the next version. Thanks for the report.
