### ISSUE TITLE
Dailymotion:user playlist broken since version 2015.05.20

### ISSUE THREAD

**Issue by badbubi** [rg3/youtube-dl#6346]
The downlod of all videos from a user is broken. 2015.05.20 is with me the last version that works to the playlist page 100. Dailymotion has a bug at playlist page 101, but that is an ather problem.

Updating to version 2015.07.21 ...

youtube-dl -v http://www.dailymotion.com/user/UnderProject/1

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.dailymotion.com/user/UnderProject/1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.6.6 - Linux-3.2.0-0.bpo.4-amd64-x86_64-with-debian-6.0.10
[debug] exe versions: ffmpeg N-63893-gc69defd, ffprobe 0.7.17, rtmpdump 2.3
[debug] Proxy map: {}
[generic] 1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1: Downloading webpage
[generic] 1: Extracting information
ERROR: Unsupported URL: http://www.dailymotion.com/user/UnderProject/1
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1123, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1562, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.6/xml/etree/ElementTree.py", line 963, in XML
    parser.feed(text)
  File "/usr/lib/python2.6/xml/etree/ElementTree.py", line 1245, in feed
    self._parser.Parse(data, 0)
ExpatError: not well-formed (invalid token): line 19, column 486
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1712, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.dailymotion.com/user/UnderProject/1

**Comment by dstftw** [comment]
Remove `/1` from the end to workaround.

**Comment by badbubi** [comment]
Thanks,
youtube-dl  http://www.dailymotion.com/user/UnderProject
works without the /1

There is only the problem from the playlist at page 101. Dailymotion shows starting on page 101 only page 100. youtube-dl don't stop at downloading Playlst Pages.

http://www.dailymotion.com/user/UnderProject/101 jump back to http://www.dailymotion.com/user/UnderProject/100.

should I open a new ticket / issue?
