### ISSUE TITLE
Dailymotion: Need a way to limit the playlist download page at 100.

### ISSUE THREAD

**Issue by badbubi** [rg3/youtube-dl#6347]
There is a problem at daylymotion webpage at playlist page 101.
Dailymotion shows starting on page 101 only page 100. youtube-dl don't stop at downloading Playlst Pages.

http://www.dailymotion.com/user/UnderProject/101 returns to http://www.dailymotion.com/user/UnderProject/100.

[dailymotion:user] UnderProject: Downloading page 98
[dailymotion:user] UnderProject: Downloading page 99
[dailymotion:user] UnderProject: Downloading page 100
[dailymotion:user] UnderProject: Downloading page 101
....
[dailymotion:user] UnderProject: Downloading page 234
... and so on.

**Comment by yan12125** [comment]
Thanks for the report. This might be a Dailymotion's bug, and in the next version youtube-dl will give a proper warning instead of downloading infinite pages.
