### ISSUE TITLE
[soundcloud] Downloading a large set gets 403.

### ISSUE THREAD

**Issue by CureGecko** [rg3/youtube-dl#6354]
I'm getting an error 403 likely because this set is large and it doesn't start downloading until youtube-dl knows of all the items in the set and knows their download url. I'm assuming that once it starts, the URL expires.

Maybe youtube-dl should start downloading as soon as it learns of a download URL and then once it's done downloading it moves on to finding info on the next track to be downloaded.

**Comment by dstftw** [comment]
Post the output of `youtube-dl -v`.

**Comment by CureGecko** [comment]
It seems to fix it, thank you.
