### ISSUE TITLE
Inconsistency in youtube vcodecs

### ISSUE THREAD

**Issue by wiiaboo** [rg3/youtube-dl#6358]
Trying to use [vcodec=vp9] to limit downloading to this codec fails to get formats which are marked with vcodec=VP9 (formats 278,302-315) and using [vcodec=VP9] fails at getting formats that aren't explicitely marked with vcodec=VP9 (formats 242-248,271-272).

Example:
![image](http://i.fsbn.eu/b3YS.png)

Solution:
either making the vcodec selector be case-insensitive or change formats 278,302-315 to use vcodec=vp9

**Comment by jaimeMF** [comment]
Thanks for the report, it will always set them in lowercase in the next version.
Note that if you are just interested in getting the webm files you can use `bestvideo[ext=webm]`, which will also pick vp8 formats.

**Comment by wiiaboo** [comment]
I was using that to fix behavior - since ffmpeg/mpv can't handle mp4 dash well but webm dash is okay - but I don't really want VP8. Would rather have messed up seeking with H.264 than using VP8.
