### ISSUE TITLE
BBC HD error message

### ISSUE THREAD

**Issue by HALofBorg** [rg3/youtube-dl#6359]
C:\Documents and Settings\HP_Owner>youtube-dl -cit http://www.bbc.co.uk/iplayer/
episode/b063hkgm/animal-super-parents-1-going-it-alone --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-cit', u'http://www.bbc.co.uk/iplayer/episode/b063
hkgm/animal-super-parents-1-going-it-alone', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-65916-g9e8ab36, ffprobe N-65916-g9e8ab36, rtmpdum
p 2.4
[debug] Proxy map: {'ftp': 'ftp://127.0.0.1:9050', 'http': 'http://127.0.0.1:905
0', 'https': 'https://127.0.0.1:9050'}
[bbc.co.uk] b063hkgm: Downloading video page
[bbc.co.uk] b063hkgh: Downloading media selection XML
ERROR: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 656, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\bbccouk.pyo", line 361, in _real_extract
  File "youtube_dl\extractor\bbccouk.pyo", line 281, in _download_media_selector

  File "youtube_dl\extractor\bbccouk.pyo", line 218, in _extract_video
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by dstftw** [comment]
Already fixed.

**Comment by HALofBorg** [comment]
Dear Sergey M.,
  With all respect, sir, this issue first occurred only two days ago. Prior
to now, I  successfully downloaded BBC HD streaming using  youtube-dl with
rtmpdump. Acouple of years ago, there was a problem with BBC servers, but
this is something malfunctioning in Python. I believe the BBC has changed
something in streaming, as  I detected f4f files. I have also tried
downloading with  HDS Link Detector using a PHP compiler. This works for
many flash movies, but never for BBC. Any attention to fixing this would be
appreciated. Please inform if there's anything else that could be helpful.
Don't take my word for this, as  I am not knowledgeable about coding, but
please try it for yourself from a Geolocation in the UK.

Thank-you

**Comment by dstftw** [comment]
As already said it's fixed and will be available in the next version. You could easily find out this yourself if bother with searching through closed issues.

**Comment by HALofBorg** [comment]
Sergey,
  Thank-you for your hard work on this project. It is the only remaining
working method I have for downloading BBC (and several others). In past
there were others.
 Should I contribute directly to you via PayPal? If so, please tell me how.
I am new to github.
                                                              -HALofBorg

**Comment by dstftw** [comment]
You can donate to the project by any of the methods described [here](http://rg3.github.io/youtube-dl/donations.html).
