### ISSUE TITLE
ExtractorError: Yahoo returned error: missing video tag

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#6364]
URL: https://www.yahoo.com/tv/the-man-in-the-high-castle-trailer-amazon-whats-123742891190.html

OUTPUT:
youtube-dl -v "https://www.yahoo.com/tv/the-man-in-the-high-castle-trailer-a
mazon-whats-123742891190.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.yahoo.com/tv/the-man-in-the-hig
h-castle-trailer-amazon-whats-123742891190.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[Yahoo] the-man-in-the-high-castle-trailer-amazon-whats: Downloading webpage
[Yahoo] the-man-in-the-high-castle-trailer-amazon-whats: Downloading video info
ERROR: Yahoo returned error: missing video tag
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 656, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\yahoo.pyo", line 191, in _real_extract
  File "youtube_dl\extractor\yahoo.pyo", line 214, in _get_info
ExtractorError: Yahoo returned error: missing video tag

Thanks...
Ringo

**Comment by yan12125** [comment]
The embedded URL shown in the video:
```
https://tv.yahoo.com/video/man-high-castle-comic-con-221500417.html
```
Works for youtube-dl.

**Comment by yan12125** [comment]
Apparently Yahoo has changed its site again and now it works with youtube-dl:
```
$ youtube-dl -v "https://www.yahoo.com/tv/the-man-in-the-high-castle-trailer-amazon-whats-123742891190.html" 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.yahoo.com/tv/the-man-in-the-high-castle-trailer-amazon-whats-123742891190.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.14
[debug] Git HEAD: a7acf868a
[debug] Python version 3.6.0 - Linux-4.9.0-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[Yahoo] the-man-in-the-high-castle-trailer-amazon-whats: Downloading webpage
[Yahoo] the-man-in-the-high-castle-trailer-amazon-whats: Downloading alias info
[Yahoo] the-man-in-the-high-castle-trailer-amazon-whats: Downloading webm video info
[Yahoo] the-man-in-the-high-castle-trailer-amazon-whats: Downloading mp4 video info
[Yahoo] a63e8d9d-1c1a-3ae4-a611-924409a8f0a5: Downloading m3u8 information
[debug] Invoking downloader on 'https://tpbrack04.vpg.cdn.yimg.com/yahootv/lotus/e299ea5a-ab07-4224-99a1-32f88de9aa34_zoK_wDJ2X5i2jkXZlSqCk0Tjb5vaN4Kxu06Gv5N9eBJTQd7Errn-H-NRPO0EWHrDlZQvpzYaH0g-_7_0.mp4?a=yahootv&b=10290&flags=marker_ar2&ib=sapi&m=video%2fmp4&mr=0&ns=c+i+ci+cii+ps+flags&ps=152c8t1c7mrjh&vid=a63e8d9d-1c1a-3ae4-a611-924409a8f0a5&x=1485129599&s=444e311aa9babdcb4b28f15bd2c4864b'
[download] Destination: 'The Man in the High Castle' Comic-Con Trailer-a63e8d9d-1c1a-3ae4-a611-924409a8f0a5.mp4
[download] 100% of 13.54MiB in 00:03
```
