### ISSUE TITLE
Error downloading Single Shots from Comedians In Cars Getting Coffee

### ISSUE THREAD

**Issue by sjmyst** [rg3/youtube-dl#6366]
Does youtube-dl support the Single Shots videos put out by Jerry Seinfield's Comedians In Cars Getting Coffee (CICGC)?

I am able to use youtube-dl for the actual videos where Jerry goes out for a coffee.  But, the CICGC web site also includes "out takes" called Single Shots.  When I tried to download one of those I get:

bash.exe"-3.1$ youtube-dl --verbose http://http://comediansincarsgettingcoffee.com/single-shots/tina-fey-brian-regan-sarah-silverman-donuts
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://comediansincarsgettingcoffee.com/singl
e-shots/tina-fey-brian-regan-sarah-silverman-donuts']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-67467-g2b14593, ffprobe N-67467-g2b14593, rtmpdump 2.4
[debug] Proxy map: {}
[ComCarCoff] single-shots: Downloading webpage
ERROR: An extractor error has occured. (caused by KeyError(u'tina-fey-brian-regan-sarah-s
ilverman-donuts',)); please report this issue on https://yt-dl.org/bug . Make sure you ar
e using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl wi
th the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\comcarcoff.pyo", line 39, in _real_extract
KeyError: u'tina-fey-brian-regan-sarah-silverman-donuts'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 656, in extract_info
  File "youtube_dl\extractor\common.pyo", line 281, in extract
ExtractorError: An extractor error has occured. (caused by KeyError(u'tina-fey-brian-rega
n-sarah-silverman-donuts',)); please report this issue on https://yt-dl.org/bug . Make su
re you are using the latest version; type  youtube-dl -U  to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.

Regards,
sjmyst

**Comment by dstftw** [comment]
Singleshots will be supported in the next version. Thanks for the report.
