### ISSUE TITLE
Skipping DASH manifest - 403

### ISSUE THREAD

**Issue by edouardduliege** [rg3/youtube-dl#6369]
Hello,
I use youtube-dl on Fedora 22 64b.
youtube-dl --version
2015.07.04

Just got this:
WARNING: [youtube] FndmvPkI1Ms: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on 'https://r2---sn-gxo5uxg-jqbe.googlevideo.com/videoplayback?id=167766bcf908d4cb&itag=141&source=youtube&requiressl=yes&pcm2cms=yes&gcr=fr&mn=sn-gxo5uxg-jqbe&mm=31&ms=au&mv=m&pl=18&ratebypass=yes&mime=audio/mp4&gir=yes&clen=6478313&lmt=1429874861434540&dur=203.174&fexp=901816,906335,9408710,9415365,9415485,9416126&signature=0EB39F083E529C1EEAC3920288F3C09F822650DB.34AE2CC8F886D725623198C1E7162F58B23A1AA2&upn=uhYLlhTjMjg&key=dg_yt0&mt=1437898173&sver=3&ip=193.54.89.181&ipbits=0&expire=1437919826&sparams=ip,ipbits,expire,id,itag,source,requiressl,pcm2cms,gcr,mn,mm,ms,mv,pl,ratebypass,mime,gir,clen,lmt,dur'

If you need any more information, let me know ;)

Best,
Edouard

**Comment by yan12125** [comment]
Your copy is outdated. Have a look at [update instructions](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl) if you have problems on updating.

**Comment by edouardduliege** [comment]
I've checked that but as I installed youtube-dl through dnf, I'm going to wait for the package to be updated (lazy french here, sorry ;). If the issue has been fixed in more recent versions, then great! Thanks for your reply and the good job
