### ISSUE TITLE
roosterteeth.com now unsupported

### ISSUE THREAD

**Issue by LordAro** [rg3/youtube-dl#6371]
roosterteeth.com recently revamped their site, changing from Blip.tv to an apparently self-hosted JWPlayer. My understanding is that JWPlayer is, in principle, supported by the generic extractor but in this case just results in an UnsupportedError exception

Example URL: http://roosterteeth.com/episode/red-vs-blue-season-13-episode-14

**Comment by TRox1972** [comment]
As of version 2016.05.21.2, the generic extractor is able to download the provided URL.

**Comment by yan12125** [comment]
Thanks.
