### ISSUE TITLE
[youku] Download geolocated videos without proxy

### ISSUE THREAD

**Issue by RomanEmelyanov** [rg3/youtube-dl#6377]
This error type should be warning:

./youtube-dl -g http://v.youku.com/v_show/id_XMTQ3MDcyNTYw.html
ERROR: Youku server reported error -8: 抱歉，此视频只限于中国内地播放。
Sorry, this video can only be streamed within Mainland China.; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Right way:

$ python3 you-get -u http://v.youku.com/v_show/id_XMTQ3MDcyNTYw.html
you_get: [Warning] This video can only be streamed within Mainland China!
you_get: Use '-y' to specify a proxy server for extracting stream data.

site:                优酷 (Youku)
title:               南北少林
stream:
    - format:        flv
      container:     flv
      video-profile: 标清
      size:          172.6 MiB (180962034 bytes)
    # download-with: you-get --format=flv [URL]

Real URLs:
http://103.224.233.13/6573A58482A4A841DF62BC5932/0300020E004B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
http://221.203.1.134/677661A78D14A83BA05D3D4B3D/0300020E014B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
http://218.26.232.31/65757846E7C4979481E726434/0300020E024B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
http://218.60.17.82/697A072B6144B8132008095A5C/0300020E034B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
http://218.60.17.42/65774B08E9E317C67C65C592E/0300020E044B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
http://218.61.211.44/697BD9EDD7248812D64EA16311/0300020E054B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts

Download outside Mainland China from real Urls works fine.

**Comment by jaimeMF** [comment]
Can the urls be extracted from a IP outside of China?

**Comment by RomanEmelyanov** [comment]
What you mean "urls be extracted from a IP"?
This soft works correct - https://github.com/soimort/you-get

**Comment by jaimeMF** [comment]
> This soft works correct - https://github.com/soimort/you-get

We can't reuse it's code, it's incompatible with our license.

> What you mean "urls be extracted from a IP"?

If you run `you-get` without using a proxy, can it get urls that work?

**Comment by remitamine** [comment]
you-get can download the video without using a proxy.
but for me working with youtube-dl is better because it can download with external downloaders.

**Comment by jaimeMF** [comment]
> you-get can download the video without using a proxy

I'll try to be more clearer. From the output:
```
you_get: [Warning] This video can only be streamed within Mainland China!
you_get: Use '-y' to specify a proxy server for extracting stream data.
```
it seems that you need a proxy to actually get the urls (even thought they work without a proxy). Is that the case, or can the urls be obtained without using a proxy?

> there is a deference you-get detect 6 parts while youtube-dl get 14 parts.

That's probably due to the formats system it uses (#6193).

**Comment by remitamine** [comment]
it's just a warning.you-get continue to work and download the video without a proxy.
about the parts i think it the same like youtube-dl because at the end the video is not complete but with youtube-dl it is complete.
this is the output using you-get without proxy(i'm using aria2c for speedup):
```
you-get -u http://v.youku.com/v_show/id_XMTQ3MDcyNTYw.html | aria2c -Z $(grep http://)
you_get: [Warning] This video can only be streamed within Mainland China!
you_get: Use '-y' to specify a proxy server for extracting stream data.

[#5dec65 12MiB/12MiB(99%) CN:1 DL:151KiB]                                      
07/27 22:55:44 [NOTICE] Download complete: /home/amine/Videos/0300020E004B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
[#bed6c1 12MiB/12MiB(97%) CN:1 DL:100KiB ETA:2s]                               
07/27 22:56:51 [NOTICE] Download complete: /home/amine/Videos/0300020E014B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
[#16341b 12MiB/12MiB(98%) CN:1 DL:122KiB ETA:1s]                               
07/27 22:57:55 [NOTICE] Download complete: /home/amine/Videos/0300020E024B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
[#7f677a 12MiB/12MiB(99%) CN:1 DL:179KiB]                                      
07/27 22:58:52 [NOTICE] Download complete: /home/amine/Videos/0300020E034B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
[#adf2b2 12MiB/12MiB(99%) CN:1 DL:174KiB]                                      
07/27 22:59:51 [NOTICE] Download complete: /home/amine/Videos/0300020E044B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
[#562398 12MiB/12MiB(97%) CN:1 DL:62KiB ETA:4s]                                
07/27 23:01:03 [NOTICE] Download complete: /home/amine/Videos/0300020E054B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
5dec65|OK  |   208KiB/s|/home/amine/Videos/0300020E004B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
bed6c1|OK  |   191KiB/s|/home/amine/Videos/0300020E014B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
16341b|OK  |   204KiB/s|/home/amine/Videos/0300020E024B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
7f677a|OK  |   223KiB/s|/home/amine/Videos/0300020E034B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
adf2b2|OK  |   221KiB/s|/home/amine/Videos/0300020E044B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts
562398|OK  |   178KiB/s|/home/amine/Videos/0300020E054B057BC5E4ED010FCB249BFCB9AD-A23E-A939-26CD-D05D6880A58A.flv.ts

Status Legend:
(OK):download completed.
```

**Comment by yan12125** [comment]
you-get used to use a proxy implicitly. However, it's broken for Youku now. If you know another way to bypass the georestriction, feel free to open a new issue.
