### ISSUE TITLE
Failure in one ComedyCentralShows video

### ISSUE THREAD

**Issue by bentley** [rg3/youtube-dl#6378]
$ youtube-dl -v http://thecolbertreport.cc.com/videos/br41hy/where-in-the-world-is-edward-snowdiego-
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'-v', u'http://thecolbertreport.cc.com/videos/br41hy/where-in-the-world-is-edward-snowdiego-']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.07.18
    [debug] Python version 2.7.10 - OpenBSD-5.8-amd64-64bit
    [debug] exe versions: ffmpeg git-N-72807-g6e94e77, ffprobe git-N-72807-g6e94e77
    [debug] Proxy map: {}
    [ComedyCentralShows] where-in-the-world-is-edward-snowdiego-: Downloading webpage
    ERROR: unable to find Flash URL in webpage http://thecolbertreport.cc.com/videos/br41hy/where-in-the-world-is-edward-snowdiego-; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 656, in extract_info
        ie_result = ie.extract(url)
      File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 275, in extract
        return self._real_extract(url)
      File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/comedycentral.py", line 198, in _real_extract
        raise ExtractorError('unable to find Flash URL in webpage ' + url)
    ExtractorError: unable to find Flash URL in webpage http://thecolbertreport.cc.com/videos/br41hy/where-in-the-world-is-edward-snowdiego-; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I’ve tried 30+ other videos from Colbert Report and Daily Show and this is the only one I’ve found that fails. For example, this link downloads successfully: http://thecolbertreport.cc.com/videos/eweibb/nsa-scandal-developments

**Comment by remitamine** [comment]
for me it's not playebale in the browser.
this is the message i get when i open the url in the browser:
```
Don't freak out but this video is no longer available.
Feel free to watch one of the thousands of other videos just a few clicks away.
```

**Comment by bentley** [comment]
Ah, you’re right. Guess this is not a bug in youtube-dl.
