### ISSUE TITLE
New version fails on Dailymotion with "RegexNotFoundError"

### ISSUE THREAD

**Issue by rnoremacc** [rg3/youtube-dl#6380]
Hi,

The 2015.07.21 version won't dl this new DailyMotion video, as documented below.
The program also won't dl the previous episode from 2 weeks ago, which the earlier version did successfully. (That was http://www.dailymotion.com/video/k7ddx3b6M4956fc1Jhh)

youtube-dl --verbose http://www.dailymotion.com/video/k5yyHJpz5lEktdccB8b
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.dailymotion.com/video/k5yyHJpz5lEktdccB8b']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.9 - Linux-3.16.0-28-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] k5yyHJpz5lEktdccB8b: Downloading webpage
[dailymotion] k5yyHJpz5lEktdccB8b: Extracting information
[dailymotion] k5yyHJpz5lEktdccB8b: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 120, in _real_extract
    'video info', flags=re.MULTILINE)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 557, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

Thank you for looking at the problem,
Regards,
Chris.

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl. Thanks for the report.
