### ISSUE TITLE
youtube-dl.exe download blocked with Norton

### ISSUE THREAD

**Issue by Jhillthegreat** [rg3/youtube-dl#6383]
http://gyazo.com/5293a753b3bbcb6b5497f4fb2934c135

Not sure if other norton users are also having this issue, but I came on today to find youtube-dl was removed from my computer and it says it has a virus inside it, I was wondering if someone could fix this with norton.

**Comment by dstftw** [comment]
It's only [Symantec](https://www.virustotal.com/ru/file/33e68832702ed47a62d8d799f792babfedcfc7954d465e765c6062112a549d12/analysis/). [False positive report](https://submit.symantec.com/false_positive/) has been already sent to them by some user yesterday.
