### ISSUE TITLE
http() error

### ISSUE THREAD

**Issue by piks3l** [rg3/youtube-dl#6385]
ERROR: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by HTTPError()); 

By trying to download : http://www.francetvinfo.fr/replay-jt/france-3/soir-3/jt-soir-3-vendredi-24-juillet-2015_1003319.html

Version up to date on Debian. Downloaded through the GitHub (not the package manager).

**Comment by jaimeMF** [comment]
It works for me, please post the [full output you get when you run it with the `--verbose` option](https://github.com/rg3/youtube-dl/blob/f993afb26d20ac79891621494922887b3c8df02b/README.md#bug).

**Comment by piks3l** [comment]
Ok this is wierd. Doing it with --verbose, make it work. Wierd?

**Comment by jaimeMF** [comment]
It was probably a temporary error. It should work without the `--verbose` option.
