### ISSUE TITLE
Dailymotion: Unable to extract video info. Player api canged.

### ISSUE THREAD

**Issue by badbubi** [rg3/youtube-dl#6391]
Dailymotion has changed the player app.

$ youtube-dl -v http://www.dailymotion.com/video/x2z50yv_ayo-fire-live-jazz-a-vienne-2015_music
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.dailymotion.com/video/x2z50yv_ayo-fire-live-jazz-a-vienne-2015_music']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.6 - Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.4.3-, ffprobe 2.4.3-, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://192.168.20.3:3128/', 'https': 'https://192.168.20.3:3128/', 'no': 'localhost,127.0.0.0/8,::1'}
[dailymotion] x2z50yv: Downloading webpage
[dailymotion] x2z50yv: Extracting information
[dailymotion] x2z50yv: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/dailymotion.py", line 128, in _real_extract
    'video info', flags=re.MULTILINE)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
