### ISSUE TITLE
YouTube said: This video is not available.

### ISSUE THREAD

**Issue by vippendu** [rg3/youtube-dl#6401]
i also try update latest version of youtube-dl but still showing this error on some videos

[root@malta1317 ~]# youtube-dl http://www.youtube.com/watch?v=j1uy3TlanSk
[youtube] j1uy3TlanSk: Downloading webpage
[youtube] j1uy3TlanSk: Downloading video info webpage
ERROR: j1uy3TlanSk: YouTube said: This video is not available.
[root@malta1317 ~]#

**Comment by jaimeMF** [comment]
Well, that's the message you get when you try to access the video in a browser. There's nothing we can do.

Additionally: don't run youtube-dl as root, is an unnecessary risk.
