### ISSUE TITLE
mitele.es support looks broken

### ISSUE THREAD

**Issue by DellDor** [rg3/youtube-dl#6414]
Hello!
In youtube-dl --list-extractors it's supose that yt-dl can manage mitele.es, but when I tried it, doesnt't work.
Thank you very much in advanced.
...¡y gracias por tan buen programa!

youtube-dl --verbose http://www.mitele.es/series-online/la-que-se-avecina/temporada-1/capitulo-13/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.mitele.es/series-online/la-que-se-avecina/temporada-1/capitulo-13/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.10 - Linux-4.1-3.dmz.1-liquorix-686-pae-i686-with-Sparky-4-Tyche
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[mitele.es] capitulo-13: Downloading webpage
ERROR: Unable to extract embed data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 279, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mitele.py", line 42, in _real_extract
    r'(?s)MSV\.embedData\[.*?\]\s*=\s*({.*?});', webpage, 'embed data',
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 561, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract embed data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ninosal** [comment]
Sorry, what mean "broken-IE"?
thanks in advance
