### ISSUE TITLE
youtube playlist 

### ISSUE THREAD

**Issue by Aravindaful** [rg3/youtube-dl#6418]
Hi,
I'm trouble with downloading youtube playlist.videos download without audio file.I want 480p quality so I tried only that quality.
here is some of I downloaded youtube play list
https://www.youtube.com/watch?v=tp3Gw-oWs2k&list=PL6gx4Cwl9DGDiJSXfsJTASx9eMq_HlenQ

Here is the code I tried
youtube-dl -citf 135 --playlist-start 1 --playlist-end 23  "https://www.youtube.com/watch?v=tp3Gw-oWs2k&list=PL6gx4Cwl9DGDiJSXfsJTASx9eMq_HlenQ"

please help me.
thank you

**Comment by jaimeMF** [comment]
> videos download without audio file.I want 480p quality so I tried only that quality.

the 135 format only contains the video, if you have ffmpeg installed you can use `-f 135+bestaudio` to get the video and audio formats and merge them.

If that doesn't solve it, please [explain with detail the problem you have and the output you get if you run the command with the `--verbose` option](https://github.com/rg3/youtube-dl/blob/f993afb26d20ac79891621494922887b3c8df02b/README.md#bugs).

**Comment by Aravindaful** [comment]
now it's working properly...
thanks alot........ :)
