### ISSUE TITLE
Error with link from liveleak

### ISSUE THREAD

**Issue by dspstudio** [rg3/youtube-dl#6424]
I got this verbose:
[root@myserver ~]# youtube-dl -g http://www.liveleak.com/view?i=2ed_1437499489 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-g', u'http://www.liveleak.com/view?i=2ed_1437499489', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.2 - Linux-2.6.32-042stab092.2-x86_64-with-redhat-5.11-Final
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 279, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/liveleak.py", line 79, in _real_extract
    webpage, 'embed URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 561, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
It's an embedded vimeo video, you can use `youtube-dl 'http://www.liveleak.com/view?i=2ed_1437499489' --force-generic-extractor` to download it.

Additional note: **don't run youtube-dl as the root user**, it's an unnecessary risk.

**Comment by dspstudio** [comment]
I understand, thank you.

It's my local vm playground test box without any important data.
