### ISSUE TITLE
How do I save the pages the videos are downloaded from and then the videos? TIA

### ISSUE THREAD

**Issue by miniscule** [rg3/youtube-dl#6432]
I looked through the command line switches but do not see a way to save the pages of the videos as well as the videos.  I have youtube-dl.exe in a directory by itself and python in its own directory elsewhere on the drive.  
Do I need to make some sort of batch file on windows with the command to save the video pages first and then a separate command to save the videos?
   TIA

**Comment by dstftw** [comment]
Use `--write-pages`.
