### ISSUE TITLE
version 2015.07.28 youtube error won't merge

### ISSUE THREAD

**Issue by gaming-hacker** [rg3/youtube-dl#6438]
downloading https://www.youtube.com/watch?v=1i-vcRaY5l8
[youtube] 1i-vcRaY5l8: Downloading webpage
[youtube] 1i-vcRaY5l8: Downloading video info webpage
[youtube] 1i-vcRaY5l8: Extracting video information
[youtube] 1i-vcRaY5l8: Downloading DASH manifest
[youtube] 1i-vcRaY5l8: Downloading DASH manifest
[download] Resuming download at byte 7927143
[download] Roll_the_Dice_by_Charles_Bukowski_read_by_Tom_O_Bedlam.f298.mp4 has already been downloaded
[download] 100% of 7.56MiB
[download] Resuming download at byte 3490397
[download] Roll_the_Dice_by_Charles_Bukowski_read_by_Tom_O_Bedlam.f141.m4a has already been downloaded
[download] 100% of 3.33MiB
[ffmpeg] Merging formats into "Roll_the_Dice_by_Charles_Bukowski_read_by_Tom_O_Bedlam.mp4"
ERROR:   Reason: image not found

youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.10 - Darwin-14.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg present, ffprobe present, rtmpdump 2.4
[debug] Proxy map: {}

**Comment by dstftw** [comment]
You have broken ffmpeg. Read [this thread](https://github.com/rg3/youtube-dl/issues/5662).

**Comment by gaming-hacker** [comment]
thanks, just checked and yes, ffmpeg is broken.
