### ISSUE TITLE
MDR extractor fail

### ISSUE THREAD

**Issue by z1atk0** [rg3/youtube-dl#6443]
"ERROR: No video formats found; please report this issue on https://yt-dl.org/bug" - okay, so here we go:

$ youtube-dl --verbose --proxy "" "http://www.mdr.de/mediathek/fernsehen/video287934_zc-7931f8bf_zs-2d7967f4.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--proxy', u'', u'http://www.mdr.de/mediathek/fernsehen/video287934_zc-7931f8bf_zs-2d7967f4.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.6.2 - Linux-4.1.3-i686-Intel-R-_Core-TM-_i3-3220_CPU_@_3.30GHz-with-slackware-13.0.0.0.0
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
[debug] Proxy map: {}
[MDR] 287934: Downloading webpage
[MDR] 287934: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 279, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mdr.py", line 58, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 735, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by z1atk0** [comment]
Note: seems to be a Python-2.6 thing, same URL works fine with the same youtube-dl version on a Python-2.7 system.

**Comment by jaimeMF** [comment]
Thanks for the report, it will work in the  next version.

I would recommend you to use the last python 2.7 or 3.x version (or in the worst case the last 2.6 version). The 2.6 is unmaintained and doesn't receive any security update.
