### ISSUE TITLE
Valid/invalid googlevideo.com URLs

### ISSUE THREAD

**Issue by jonathanasquier** [rg3/youtube-dl#6444]
Hi,
I have 2 identical VMs (Ubuntu 14.04, same config, mapped ports, everything) with 2 identical latest youtube-dl version
I do :
```
 youtube-dl https://youtu.be/YOUTUBE_ID --get-url -f best
``` 
Works well on one (on my local dev machine too), 403 forbidden on the other one. (Same behaviour with other youtube-dl versions)

Am I missing something? Could something prevent the other identical VM to work properly?

Thanks a lot!

**Comment by jaimeMF** [comment]
The urls you get with youtube-dl are only guaranteed to work from the same IP and with the same cookies. Please explain how you try to download the videos, does `youtube-dl URL -f best` correctly download the video?

**Comment by jonathanasquier** [comment]
Interessing, on the failing VM `youtube-dl URL -f best` downloads the video properly, and `wget`ing the URL works the same way.
But requesting the URL on another IP always fails when generated from the 1st VM, and always work when generated from the 2nd VM... (I have an API/client app architecture, my VMs are production and pre-production)

Sorcery? :P

**Comment by dstftw** [comment]
As already mentioned by @jaimeMF final download URLs are not guaranteed to work on another machine/IP apart from where it has beeen extracted. [More on this](https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-webbrowser).

**Comment by jonathanasquier** [comment]
Okay... just thought is was strange it had a different behaviour with the same URL... I believe I'm gonna have to deal with it!

**Comment by dstftw** [comment]
In addition, you can probably track these URLs with [this approach](https://github.com/rg3/youtube-dl/issues/6004#issuecomment-112849086) to apply different scenario for them.

**Comment by jonathanasquier** [comment]
Interesting, gcr=ie in the "failing" urls gcr=us in "working" urls, matches the VM's IP country obviously, but still no work around for me right now :) thanks!
