### ISSUE TITLE
Pornhub unable extract

### ISSUE THREAD

**Issue by alex1306** [rg3/youtube-dl#6446]
root@vps:~# youtube-dl -g http://www.pornhub.com/view_video.php?viewkey=1502879271 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-g', u'http://www.pornhub.com/view_video.php?viewkey=1502879271', u'--verbose']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.6 - Linux-2.6.32-042stab108.5-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 279, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/pornhub.py", line 113, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 735, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

root@vps:~#

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl. Thanks for the report.
