### ISSUE TITLE
Unclear message when proxy is needed

### ISSUE THREAD

**Issue by jesus2099** [rg3/youtube-dl#6449]
From some places, I need to use the ``proxy`` command line parameter.
Sometimes I forget this and the error I get is very confusing, usually I am not able to understand why it fails before some hours of trying many silly things.

> **youtube-dl any-youtube-ID**
> [youtube] any-youtube-ID: Downloading webpage
> Traceback (most recent call last):
>   File "__main__.py", line 19, in <module>
>   File "youtube_dl\__init__.pyo", line 410, in main
>   File "youtube_dl\__init__.pyo", line 400, in _real_main
>   File "youtube_dl\YoutubeDL.pyo", line 1504, in download
>   File "youtube_dl\YoutubeDL.pyo", line 656, in extract_info
>   File "youtube_dl\extractor\common.pyo", line 279, in extract
>   File "youtube_dl\extractor\youtube.pyo", line 916, in _real_extract
>   File "youtube_dl\extractor\common.pyo", line 430, in _download_webpage
>   File "youtube_dl\extractor\common.pyo", line 337, in _download_webpage_handle
>   File "youtube_dl\extractor\common.pyo", line 324, in _request_webpage
> **UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 58: ordinal not in range(128)**

In fact I have to use `youtube-dl --proxy my.proxy.fr:80 any-youtube-ID` (for instance) and it works. But the error message had nothing to help me finding this solution. :)

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by jesus2099** [comment]
OK, here it is. :)

```
C:\Users\m319937>youtube-dl --verbose --dump-pages C88xTb--Xw0
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--dump-pages', u'C88xTb--Xw0']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] C88xTb--Xw0: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 410, in main
  File "youtube_dl\__init__.pyo", line 400, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1504, in download
  File "youtube_dl\YoutubeDL.pyo", line 656, in extract_info
  File "youtube_dl\extractor\common.pyo", line 279, in extract
  File "youtube_dl\extractor\youtube.pyo", line 916, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 430, in _download_webpage
  File "youtube_dl\extractor\common.pyo", line 337, in _download_webpage_handle
  File "youtube_dl\extractor\common.pyo", line 324, in _request_webpage
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 58: ordinal not in range(128)
```
