### ISSUE TITLE
Can't DL Last Week Tonight...

### ISSUE THREAD

**Issue by sjmyst** [rg3/youtube-dl#6450]
Hi,

Trying to download Last Week Tonight with John Oliver and getting this error:

bash.exe"-3.1$ youtube-dl --verbose http://allmyvideos.net/embed-24qwefmwczgj.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://allmyvideos.net/embed-24qwefmwczgj.htm
l']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-67467-g2b14593, ffprobe N-67467-g2b14593, rtmpdump 2.4
[debug] Proxy map: {}
[Moniker] embed-24qwefmwczgj: Downloading webpage
[Moniker] embed-24qwefmwczgj: Downloading video page ...
ERROR: An extractor error has occured. (caused by KeyError(u'fname',)); please report thi
s issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  yout
ube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its
complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\common.pyo", line 279, in extract
  File "youtube_dl\extractor\moniker.pyo", line 64, in _real_extract
KeyError: u'fname'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 656, in extract_info
  File "youtube_dl\extractor\common.pyo", line 285, in extract
ExtractorError: An extractor error has occured. (caused by KeyError(u'fname',)); please r
eport this issue on https://yt-dl.org/bug . Make sure you are using the latest version; t
ype  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and inc
lude its complete output.

Is Last Week Tonight supported?

Regards,
sjmyst

**Comment by luceatnobis** [comment]
It is supported, but youtube-dl doesnt like embed- links. if you just youtube-dl http://allmyvideos.net/24qwefmwczgj.html it will download correctly.

**Comment by sjmyst** [comment]
Thank you for the tip.  That worked great for me.

Closing this issue.

Regards,
sjmyst
