### ISSUE TITLE
"No video formats found" in release 2015.07.28

### ISSUE THREAD

**Issue by goghpdg** [rg3/youtube-dl#6455]
Until a few weeks ago, the release 2014.02.17-1 was working with almost all websites.

Now, albeit having updated at version 2015.17.28, I get this error message:

youtube-dl http://www.pornhub.com/view_video.php?viewkey=1000377614 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.pornhub.com/view_video.php?viewkey=1000377614', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.6 - Linux-3.2.0-84-generic-pae-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[PornHub] 1000377614: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 279, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 113, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 735, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Nevertheless, the new version works with YouTube videos.

Thanks in advance.

**Comment by dstftw** [comment]
pornhub have changed the layout. This is already fixed and will be available in the next version.
