### ISSUE TITLE
How to download certain quality of a YouTube playlist?

### ISSUE THREAD

**Issue by santosh** [rg3/youtube-dl#6458]
I literally know how to download a playlist a video, it's something like:

    youtube-dl --playlist-start [start index] --playlist-end [end index] [url of playlist]

That I suspect downloads the highest possible quality of videos. 

Suppose I know that 1080p is the highest quality which user is uploading it's video. What if I want to download all the playlist in 480p?

**Comment by remitamine** [comment]
you can read here about how specify the formats to download: https://github.com/rg3/youtube-dl#format-selection

**Comment by jaimeMF** [comment]
The answer provided by @remitamine should work, therefore I'm closing the issue.

**Comment by jaimeMF** [comment]
Note: it's `[height<=480]`, not `[height<=480p]`
