### ISSUE TITLE
periscope 

### ISSUE THREAD

**Issue by haokah** [rg3/youtube-dl#6459]
I'm hoping you can add periscope support. It needs cookies and then the files are in multiple chunks with a playlist file.

From this url: https://replay.periscope.tv/Aa5MyH8SfnTxKoxidSvCUrx8TvIY3_C5_WcPg41q97ibd9ySRGjZG3kIZUjsSW9jkJO87UgqCY0PL1QMCpadsQ==

Video is split in multiple chunks like:

https://replay.periscope.tv/Aa5MyH8SfnTxKoxidSvCUrx8TvIY3_C5_WcPg41q97ibd9ySRGjZG3kIZUjsSW9jkJO87UgqCY0PL1QMCpadsQ==/chunk_15.ts

with a playlist:
https://replay.periscope.tv/Aa5MyH8SfnTxKoxidSvCUrx8TvIY3_C5_WcPg41q97ibd9ySRGjZG3kIZUjsSW9jkJO87UgqCY0PL1QMCpadsQ==/playlist.m3u8

Here's verbose output:

youtube-dl --verbose https://replay.periscope.tv/Aa5MyH8SfnTxKoxidSvCUrx8TvIY3_C5_WcPg41q97ibd9ySRGjZG3kIZUjsSW9jkJO87UgqCY0PL1QMCpadsQ==
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://replay.periscope.tv/Aa5MyH8SfnTxKoxidSvCUrx8TvIY3_C5_WcPg41q97ibd9ySRGjZG3kIZUjsSW9jkJO87UgqCY0PL1QMCpadsQ==']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-i686-athlon-with-LinuxMint-17.1-rebecca
[debug] exe versions: none
[debug] Proxy map: {}
[generic] Aa5MyH8SfnTxKoxidSvCUrx8TvIY3_C5_WcPg41q97ibd9ySRGjZG3kIZUjsSW9jkJO87UgqCY0PL1QMCpadsQ==: Requesting header
WARNING: Could not send HEAD request to https://replay.periscope.tv/Aa5MyH8SfnTxKoxidSvCUrx8TvIY3_C5_WcPg41q97ibd9ySRGjZG3kIZUjsSW9jkJO87UgqCY0PL1QMCpadsQ==: HTTP Error 403: Forbidden
[generic] Aa5MyH8SfnTxKoxidSvCUrx8TvIY3_C5_WcPg41q97ibd9ySRGjZG3kIZUjsSW9jkJO87UgqCY0PL1QMCpadsQ==: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 318, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1732, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by remitamine** [comment]
all the urls give this error `Missing Key-Pair-Id query parameter or cookie value`:
```
<?xml version="1.0" encoding="UTF-8"?><Error><Code>MissingKey</Code><Message>Missing Key-Pair-Id query parameter or cookie value</Message></Error>
```

**Comment by dstftw** [comment]
Post a working [example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by haokah** [comment]
The URL's only live a maximum of 24 hours by design. They worked when I posted them, I could view the video and it was the url from the app that I could use the share option through email, then view again.
Here's a new one that is 30 minutes old. https://www.periscope.tv/w/aJUQnjY3MjA3ODF8NTYxMDIyMDl2zCg2pECBgwTqRpQuQD352EMPTKQjT4uqlM3cgWFA-g==

![image](https://cloud.githubusercontent.com/assets/13645577/9145658/046033fa-3d1c-11e5-9de4-97931fd80cf6.png)

**Comment by dstftw** [comment]
Periscope will be supported in the next version.

**Comment by haokah** [comment]
That is awesome news! Thank you!!!
