### ISSUE TITLE
issue with xhamster.com

### ISSUE THREAD

**Issue by incose** [rg3/youtube-dl#6470]
C:\squid>youtube-dl.exe --verbose "http://xhamster.com/movies/4938284/magma_film_she_is_in_charge.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://xhamster.com/movies/4938284/magma_film_she_is_in_charge.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[XHamster] 4938284: Downloading webpage
WARNING: unable to extract thumbnail; please report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.
ERROR: Unable to extract media URL; please report this issue on https://yt-dl.org/bug .

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl.

**Comment by incose** [comment]
Awesome. I really love this tool. THE BEST.
