### ISSUE TITLE
lynda.com - Unable to log in

### ISSUE THREAD

**Issue by akasma74** [rg3/youtube-dl#6476]
Your script used to work 2 weeks ago, but today it is unable to log in. I updated it, but the result is the same:

~/youtube-dl/youtube-dl --username="xxxx" --password="xxxx" -o "raw/%(playlist_title)s|%(playlist_index)s %(title)s.%(ext)s" "http://www.lynda.com/Java-tutorials/Java-Essential-Training/377484-2.html" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--username=xxxx', u'--password=xxxx', u'-o', u'raw/%(playlist_title)s|%(playlist_index)s %(title)s.%(ext)s', u'http://www.lynda.com/Java-tutorials/Java-Essential-Training/377484-2.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.6.1 - Darwin-10.8.0-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Logging in as xxxx
[lynda:course] Confirming log in and log out from another device
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/Users/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 278, in extract
    self.initialize()
  File "/Users/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 272, in initialize
    self._real_initialize()
  File "/Users/youtube-dl/youtube-dl/youtube_dl/extractor/lynda.py", line 25, in _real_initialize
    self._login()
  File "/Users/youtube-dl/youtube-dl/youtube_dl/extractor/lynda.py", line 74, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment]
the output look the same as the the output in this issue https://github.com/rg3/youtube-dl/issues/6462.

**Comment by akasma74** [comment]
You are right, that's the same issue, but it's too early to close it.
Any idea when the next version will be available?

**Comment by remitamine** [comment]
i don't know but you can get the latest git version and work with until the next version released.

**Comment by akasma74** [comment]
I'm new to GitHub and youtube_dl and can only update the binary file to the current version.
Could you explain (or refer to an explanation) how to get the latest git version please?
I'm on OS X 10.6.8, just in case.

**Comment by remitamine** [comment]
i don't know if this apply also for Mac Os X(i use linux there are some simularities between them):
- download the latest version from here https://github.com/rg3/youtube-dl/archive/master.zip.
- extract it and enter the extracted folder.
- from the terminal execute this command:
`make`
- if there is a result file with this name `youtube-dl`.
- then you can execute youtube-dl like this.
`./youtube-dl [OPTIONS] URL [URL...]`
do not forget `./`
if this doesn't work than may someone who work in Mac OS X can help you.

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl.

**Comment by akasma74** [comment]
2 remitamine: thank you so much mate, it works now. I had to find a way to install make though, it doesn't come as standard with OS X ;)

2 dstftw: I think it's good idea to let people know somehow how to get the current version, Sergey?

**Comment by dstftw** [comment]
@akasma74 the good idea is to use search or at least [read FAQ](https://github.com/rg3/youtube-dl#developer-instructions).

**Comment by akasma74** [comment]
A bit rude, comrade :)
I apologise for not using search - just had a look at the last issues and didn't see anything to do with lynda.com
No offence, but I did read FAQ many times actually, and would be grateful if you could point out where exactly it mentions the method remitamine posted here as I haven't seen anything like that.

**Comment by dstftw** [comment]
It mentions a better idea - cloning the repository with `git clone` and maintaining it in sync with `git pull` instead of redownloading the source tarball over and over again.

**Comment by akasma74** [comment]
You see! That's why I'm suggesting to add this information.
I have no idea about git (and I can see only one place where git clone is mentioned - it's called "Adding support of a new site", and there is nothing about building the binary anyway), but I know how to use make, and it worked for me.
It never hurts to have an option, is it?
