### ISSUE TITLE
xhamster.com downloads broken

### ISSUE THREAD

**Issue by YuukieO** [rg3/youtube-dl#6478]
I'm trying to grab a video from xhamster, looks as if they changed their html (again).

youtube-dl --verbose http://de.xhamster.com/movies/3070725/hot_latex_lesbians.html 
[debug] System config: []
[debug] User config: [u'--title']
[debug] Command-line args: [u'--verbose', u'http://de.xhamster.com/movies/3070725/hot_latex_lesbians.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.8 - Linux-3.16.7-21-desktop-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {'no': 'localhost, 127.0.0.1, .eregion.de, .eregion.home'}
[XHamster] 3070725: Downloading webpage
WARNING: unable to extract thumbnail; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Unable to extract media URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 279, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/xhamster.py", line 100, in _real_extract
    video_url = extract_video_url(webpage)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/xhamster.py", line 52, in extract_video_url
    raise ExtractorError('Unable to extract media URL')
ExtractorError: Unable to extract media URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by gebn** [comment]
Can confirm that video starts downloading correctly using master. Looks like media URL extraction was fixed in 354b4b8604ec13ccf4bd89b9d1b77cb7246fe379, and thumbnail extraction in 251a44b776264c17d7799e017b856143c6cacd9a.

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl.
