### ISSUE TITLE
Support for 9tsu

### ISSUE THREAD

**Issue by limechord** [rg3/youtube-dl#6482]
Please add support for http://video.9tsu.com/
Thanks!

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by limechord** [comment]
Sorry.
Example URL:
http://video.9tsu.com/video/%E3%83%94%E3%82%BF%E3%82%B4%E3%83%A9%E8%A3%85%E7%BD%AE_%E5%A4%A7%E8%A7%A3%E8%AA%AC%E3%82%B9%E3%83%9A%E3%82%B7%E3%83%A3%E3%83%AB%E3%80%8C%E5%89%8D%E5%8D%8A%E6%88%A6%E3%80%8D_20150804

**Comment by TRox1972** [comment]
Provided URL redirects to http://video.9tsu.com/video/not_approved.

**Comment by yan12125** [comment]
Yes, and other videos on 9tsu.com can be downloaded. (via jwplayer)
