### ISSUE TITLE
Unsupported URL: macrumors.com

### ISSUE THREAD

**Issue by aaronvegh** [rg3/youtube-dl#6485]
Using the latest version 

$ youtube-dl --version
2015.08.06.1

http://www.macrumors.com/2015/07/24/steve-jobs-the-man-in-the-machine-first-trailer/

It contains an embedded video hosted by Ooyala, which I believe you support! This is what I get:

```
$ youtube-dl -g http://www.macrumors.com/2015/07/24/steve-jobs-the-man-in-the-machine-first-trailer/
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.macrumors.com/2015/07/24/steve-jobs-the-man-in-the-machine-first-trailer/
```

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version. Thanks for the report.
