### ISSUE TITLE
WARNING: Warning: Falling back to static signature algorithm [youtube] XC-Im_kRPxM: Downloading js player new WARNING: Automatic signature extraction failed: Traceback (most recent call last):

### ISSUE THREAD

**Issue by rudrakshya** [rg3/youtube-dl#6486]
cannot download this video 
https://www.youtube.com/watch?v=XC-Im_kRPxM
getting error 
WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. See [our FAQ](https://yt-dl.org/update) on how to update.
