### ISSUE TITLE
Downloading private videos using username and password

### ISSUE THREAD

**Issue by rojesh** [rg3/youtube-dl#6488]
I have updated youtube-dl to the latest version, but getting this error when trying to download video from my vimeo account using username and password.

[vimeo] Logging in
ERROR: Unable to extract login token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by machtwebseiten** [comment]
Duplicate/Regression bug of  #5082 (<- this one is closed)

Here's my output:

youtube-dl.exe --verbose -u myuser@gmail.com https://vimeo.com/55500033
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', 'https://vimeo.com/55500033']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.08.09
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] Logging in
ERROR: Unable to extract login token; please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 655, in extract_info
ie_result = ie.extract(url)
File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 285, in extract
self.initialize()
File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 279, in initialize
self._real_initialize()
File "C:\Python34\lib\site-packages\youtube_dl\extractor\vimeo.py", line 225, in _real_initialize
self._login()
File "C:\Python34\lib\site-packages\youtube_dl\extractor\vimeo.py", line 42, in _login
token = self._search_regex(r'xsrft":"(.*?)"', webpage, 'login token')
File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 568, in _search_regex
raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract login token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version.

**Comment by jubalh** [comment]
I get something similar using version 2016.11.18:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://vimeo.com/channels/somechannelicannotshare/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.18
[debug] Python version 2.7.12 - Linux-4.4.27-2-default-x86_64-with-SuSE-42.2-x86_64
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3
[debug] Proxy map: {}
[vimeo:channel] 914537: Downloading page 1
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by yan12125** [comment]
@jubalh Vimeo private channels are not supported yet. See #5644

**Comment by jubalh** [comment]
@yan12125 Uh! Thanks for the info!
