### ISSUE TITLE
anonymous download?

### ISSUE THREAD

**Issue by gaming-hacker** [rg3/youtube-dl#6493]
is there any way you can hook into a random public proxy that uses SSL/Hi Anon using lib curl?

**Comment by dstftw** [comment]
Just use `--proxy`.

**Comment by gaming-hacker** [comment]
that means manually entering the proxy every time, why not just a function that tests the randomizes a list.  libcurl is good at this

**Comment by dstftw** [comment]
That's out of scope you youtube-dl.
