### ISSUE TITLE
Unable to download embedded Vimeo video [HD]

### ISSUE THREAD

**Issue by goldenchariotcharterers** [rg3/youtube-dl#6495]
Hi, 

Could not download a vimeo video from the following URL : http://www.dailymotion.com/video/x1f26gz_bbc-our-secret-universe-the-hidden-life-of-the-cell-720p-hdtv_tech

The output is as follows with the --verbose flag : 

$ youtube-dl --verbose http://www.dailymotion.com/video/x1f26gz_bbc-our-secret-universe-the-hidden-life-of-the-cell-720p-hdtv_tech >> youtube-dl.error.log
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.dailymotion.com/video/x1f26gz_bbc-our-secret-universe-the-hidden-life-of-the-cell-720p-hdtv_tech']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.1
[debug] Proxy map: {}
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/dailymotion.py", line 114, in _real_extract
    'video info', flags=re.MULTILINE)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

glenn@debian:~/Videos$ cat *.log
[dailymotion] x1f26gz: Downloading webpage
[dailymotion] x1f26gz: Extracting information
[dailymotion] x1f26gz: Downloading embed page

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
