### ISSUE TITLE
"ERROR: Unable to download f4m manifest" on a previously working website

### ISSUE THREAD

**Issue by DiomFR** [rg3/youtube-dl#6496]
This is the issue when I try to -F the webpage : 'http://www.france5.fr/emissions/c-dans-l-air/videos/epargne_04-08-2015_851144?onglet=replay&page=1'

It has worked on this website (or http://pluzz.francetv.fr/videos/c_dans_lair_,125915888.html), but it's not working anymore on both sites (pluzz.francetv.fr & france5.fr).

Version : Version : 2015.06.04.1-1 (Debian Stretch)

youtube-dl -F works on Youtube

$ youtube-dl --verbose -F 'http://www.france5.fr/emissions/c-dans-l-air/videos/epargne_04-08-2015_851144?onglet=replay&page=1'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-F', u'http://www.france5.fr/emissions/c-dans-l-air/videos/epargne_04-08-2015_851144?onglet=replay&page=1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-3.16.0-4-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 2.6.1, avprobe 2.6.1, ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
[debug] Proxy map: {}
[francetv] epargne_04-08-2015_851144: Downloading webpage
[francetv] 125915888: Downloading video JSON
[francetv] 125915888: Downloading f4m manifest token
[francetv] 125915888: Downloading f4m manifest
ERROR: Unable to download f4m manifest: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by DiomFR** [comment]
Thank you for your answer.

I will have to consider installing youtube-dl aside from the dpkg system.
