### ISSUE TITLE
I get this error when downloading the audio of a playlist I made that is public.

### ISSUE THREAD

**Issue by TommieIV** [rg3/youtube-dl#6505]
tommieiv@tommieiv-HP-G62:~$ youtube-dl https://www.youtube.com/playlist?list=PLj1s5vDQ_ulwDFBZe67ZRKyCNxXOnBFCv --audio-format mp3 --extract-audio -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.youtube.com/playlist?list=PLj1s5vDQ_ulwDFBZe67ZRKyCNxXOnBFCv', '--audio-format', 'mp3', '--extract-audio', '-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.8 - Linux-3.16.0-44-generic-i686-with-Ubuntu-14.10-utopic
[debug] Proxy map: {}
[youtube:playlist] PLj1s5vDQ_ulwDFBZe67ZRKyCNxXOnBFCv: Downloading webpage
[download] Downloading playlist: Music
[youtube:playlist] playlist Music: Collected 8 video ids (downloading 8 of them)
[download] Downloading video #1 of 8
[youtube] Setting language
[youtube] lGPd9Z397YQ: Downloading webpage
[youtube] lGPd9Z397YQ: Downloading video info webpage
[youtube] lGPd9Z397YQ: Extracting video information
[debug] Invoking downloader on u'https://r1---sn-5uaezned.googlevideo.com/videoplayback?ip=68.62.130.26&requiressl=yes&ms=au&mt=1439088655&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mv=m&id=o-AHEvwA6VQMg1N4Dd3_9LTVjsU3JtJRFrMuFYafNBmghA&pl=19&mm=31&mn=sn-5uaezned&lmt=1417165134514382&signature=7DFABAAF43929ACD2E83A0AC2C12FC8F9A61A880.1053541ED6B9B9F9C26F29E69579F67DFF523F4A&upn=9AXXAgMdUpg&source=youtube&keepalive=yes&initcwndbps=878750&mime=audio%2Fmp4&gir=yes&key=yt5&nh=IgpwcjAyLmF0bDIyKgkxMjcuMC4wLjE&clen=3631073&itag=140&gcr=us&sver=3&ipbits=0&dur=226.138&fexp=9408511%2C9408710%2C9412859%2C9414903%2C9415365%2C9415485%2C9415530%2C9416023%2C9416126%2C9416374%2C9417122%2C9417998%2C9418063%2C9418153%2C9418203%2C9418823%2C9418906&expire=1439110290&ratebypass=yes'
[download] Destination: Payphone - Maroon 5 (No Rap_Clean Version) (Lyrics) HD-lGPd9Z397YQ.m4a
[download] 100% of 3.46MiB in 00:01
[avconv] Destination: Payphone - Maroon 5 (No Rap_Clean Version) (Lyrics) HD-lGPd9Z397YQ.mp3
[debug] ffmpeg command line: avconv -y -i 'Payphone - Maroon 5 (No Rap_Clean Version) (Lyrics) HD-lGPd9Z397YQ.m4a' -vn -acodec libmp3lame -q:a 5 'Payphone - Maroon 5 (No Rap_Clean Version) (Lyrics) HD-lGPd9Z397YQ.mp3'
Deleting original file Payphone - Maroon 5 (No Rap_Clean Version) (Lyrics) HD-lGPd9Z397YQ.m4a (pass -k to keep)
[download] Downloading video #2 of 8
[youtube] OzHZx66gVBQ: Downloading webpage
[youtube] OzHZx66gVBQ: Downloading video info webpage
[youtube] OzHZx66gVBQ: Extracting video information
[youtube] OzHZx66gVBQ: Encrypted signatures detected.
[youtube] {22} signature length 40.43, html5 player new
[youtube] OzHZx66gVBQ: Downloading js player new
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 860, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 489, in _decrypt_signature
    u'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

tommieiv@tommieiv-HP-G62:~$

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by TommieIV** [comment]
Thanks! I love the quick reply!
