### ISSUE TITLE
Dash manifest error 

### ISSUE THREAD

**Issue by tone87** [rg3/youtube-dl#6508]
if i try to download any video youtube dl show me this error 

[youtube] y74UPiaK7u0: Downloading webpage
[youtube] y74UPiaK7u0: Downloading video info webpage
[youtube] y74UPiaK7u0: Extracting video information
[youtube] {43} signature length 40.43, html5 player new
[youtube] {18} signature length 40.43, html5 player new
[youtube] {137} signature length 40.43, html5 player new
[youtube] {248} signature length 40.43, html5 player new
[youtube] {136} signature length 40.43, html5 player new
[youtube] {247} signature length 40.43, html5 player new
[youtube] {135} signature length 40.43, html5 player new
[youtube] {244} signature length 40.43, html5 player new
[youtube] {134} signature length 40.43, html5 player new
[youtube] {243} signature length 40.43, html5 player new
[youtube] {133} signature length 40.43, html5 player new
[youtube] {242} signature length 40.43, html5 player new
[youtube] {160} signature length 40.43, html5 player new
[youtube] {140} signature length 40.43, html5 player new
[youtube] {171} signature length 40.43, html5 player new
[youtube] y74UPiaK7u0: Downloading DASH manifest
[debug] Invoking downloader on u'https://r2---sn-uv2pm-ugoe.googlevideo.com/videoplayback?sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&itag=171&expire=1439143897&pl=21&mime=audio%2Fwebm&id=o-ABpfBH1WwO4RVWEKbmpz_gd5wFFoLonsEiR8wfsMnXXA&source=youtube&key=yt5&fexp=9407052%2C9407642%2C9408137%2C9408710%2C9415365%2C9415485%2C9415530%2C9415848%2C9416023%2C9416126%2C9416275%2C9418153%2C9418203%2C9418702%2C9418780&sver=3&requiressl=yes&upn=IhaTEJUVygw&lmt=1430195804438512&gcr=it&keepalive=yes&clen=3828372&ip=149.3.145.54&ms=au&mv=u&dur=246.911&mt=1439121999&gir=yes&mn=sn-uv2pm-ugoe&ipbits=0&mm=31&signature=5083C2B1B384405DCBFD1E64DCF684A37C4B9784D4.D78E85FC0E533955DFD275DD8FD3454076280431&ratebypass=yes'

**Comment by remitamine** [comment]
there is no error in the output.

**Comment by tone87** [comment]
ok but the downloader block at Downloading DASH manifest and not continue .. where's the problem ?

**Comment by remitamine** [comment]
> [debug] Invoking downloader

it doesn't block it extract the video url call the downloader.

**Comment by tone87** [comment]
no , the url who extrack don't work ... for example https://r2---sn-uv2pm-ugoe.googlevideo.com/videoplayback?gcr=it&upn=m697ljUY0AY&id=o-ACPcxsfMVD4RD-n6zA9Z0FnJxOh3k3osUQ_7RTiSNtsQ&lmt=1430195804438512&ip=149.3.145.54&fexp=9408710%2C9412839%2C9412927%2C9413121%2C9415365%2C9415485%2C9416023%2C9416104%2C9416126%2C9416837%2C9417353%2C9417527%2C9418103%2C9418153%2C9418199%2C9418203%2C9418959&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mv=u&mt=1439123248&ms=au&source=youtube&mime=audio%2Fwebm&keepalive=yes&key=yt5&requiressl=yes&clen=3828372&mn=sn-uv2pm-ugoe&mm=31&itag=171&ipbits=0&gir=yes&pl=21&sver=3&expire=1439144882&dur=246.911&signature=7D8E51B18B93579D14DDB8747A0C81A827C643FE25.73810FC79F352B7518CD2B0D6BAAA49626AA317B&ratebypass=yes 

if i try to open this on vlc media player the video not load .. is it possible to youtube block my ip ?

**Comment by remitamine** [comment]
post the original url to try and see what i get.

**Comment by tone87** [comment]
the url : https://www.youtube.com/watch?v=y74UPiaK7u0

the url who extract : 

https://r2---sn-uv2pm-ugoe.googlevideo.com/videoplayback?pl=21&ipbits=0&upn=uPy4nc2tU3o&clen=3828372&id=o-AFBuxnj3HqzW7LAbcEFGhIN0nuyZaYB0bPAjUbQMyXXl&mn=sn-uv2pm-ugoe&gir=yes&mm=31&gcr=it&ms=au&mv=u&mt=1439123469&ip=149.3.145.54&dur=246.911&keepalive=yes&lmt=1430195804438512&fexp=9405972%2C9407536%2C9407992%2C9408710%2C9408891%2C9410705%2C9412914%2C9415365%2C9415485%2C9416023%2C9416126%2C9416170%2C9416348%2C9416556%2C9417299%2C9417836%2C9417912%2C9418153%2C9418823&expire=1439145196&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&key=yt5&mime=audio%2Fwebm&requiressl=yes&sver=3&source=youtube&itag=171&signature=88BDA63B462DF8DE16B28D3AE669BBFFC16552FCEF.22B2358E0BD3BCF4ABDDBB7349E2AE8CCD916F65&ratebypass=yes

**Comment by remitamine** [comment]
for me it works for the same format you get(171)
```
youtube-dl -v -f 171 https://www.youtube.com/watch?v=y74UPiaK7u0
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c', '--external-downloader-args', '-x 16 --check-certificate=false', '-f', '[height<=?720]', '--sub-lang', 'ar,en', '--write-sub', '--age-limit', '0']
[debug] Command-line args: ['-v', '-f', '171', 'https://www.youtube.com/watch?v=y74UPiaK7u0']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 3.4.3 - Linux-4.1.4-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] y74UPiaK7u0: Downloading webpage
[youtube] y74UPiaK7u0: Downloading video info webpage
[youtube] y74UPiaK7u0: Extracting video information
WARNING: video doesn't have subtitles
[youtube] {22} signature length 40.43, html5 player new
[youtube] {43} signature length 40.43, html5 player new
[youtube] {18} signature length 40.43, html5 player new
[youtube] {5} signature length 40.43, html5 player new
[youtube] {36} signature length 40.43, html5 player new
[youtube] {17} signature length 40.43, html5 player new
[youtube] {137} signature length 40.43, html5 player new
[youtube] {248} signature length 40.43, html5 player new
[youtube] {136} signature length 40.43, html5 player new
[youtube] {247} signature length 40.43, html5 player new
[youtube] {135} signature length 40.43, html5 player new
[youtube] {244} signature length 40.43, html5 player new
[youtube] {134} signature length 40.43, html5 player new
[youtube] {243} signature length 40.43, html5 player new
[youtube] {133} signature length 40.43, html5 player new
[youtube] {242} signature length 40.43, html5 player new
[youtube] {160} signature length 40.43, html5 player new
[youtube] {140} signature length 40.43, html5 player new
[youtube] {171} signature length 40.43, html5 player new
[youtube] y74UPiaK7u0: Downloading DASH manifest
[debug] Invoking downloader on 'https://r17---sn-hpa7enls.googlevideo.com/videoplayback?id=cbbe143e268aeeed&itag=171&source=youtube&requiressl=yes&mn=sn-hpa7enls&mm=31&ms=au&mv=m&pl=17&gcr=dz&ratebypass=yes&mime=audio/webm&gir=yes&clen=3828372&lmt=1430195804438512&dur=246.911&fexp=9406194,9408710,9409172,9414763,9415365,9415435,9415485,9416023,9416126,9416295,9416575,9416838,9417456,9417701,9418082,9418153&mt=1439123757&upn=uuraU3LCB54&signature=3BB09260637965308324AADDD255D59A3B420266.2B5BD615B9B9CDBCB6B1DFC2698E1F55F2041DF1&key=dg_yt0&sver=3&ip=197.205.13.88&ipbits=0&expire=1439145454&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,mm,ms,mv,pl,gcr,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Madcon - Don't Worry feat. Ray Dalton (Official Video)-y74UPiaK7u0.webm
[debug] aria2c command line: aria2c -c -x 16 --check-certificate=false --out 'Madcon - Don'"'"'t Worry feat. Ray Dalton (Official Video)-y74UPiaK7u0.webm.part' --header 'Accept-Encoding: gzip, deflate' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-us,en;q=0.5' --header 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)' -- 'https://r17---sn-hpa7enls.googlevideo.com/videoplayback?id=cbbe143e268aeeed&itag=171&source=youtube&requiressl=yes&mn=sn-hpa7enls&mm=31&ms=au&mv=m&pl=17&gcr=dz&ratebypass=yes&mime=audio/webm&gir=yes&clen=3828372&lmt=1430195804438512&dur=246.911&fexp=9406194,9408710,9409172,9414763,9415365,9415435,9415485,9416023,9416126,9416295,9416575,9416838,9417456,9417701,9418082,9418153&mt=1439123757&upn=uuraU3LCB54&signature=3BB09260637965308324AADDD255D59A3B420266.2B5BD615B9B9CDBCB6B1DFC2698E1F55F2041DF1&key=dg_yt0&sver=3&ip=197.205.13.88&ipbits=0&expire=1439145454&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,mm,ms,mv,pl,gcr,ratebypass,mime,gir,clen,lmt,dur'
[#dce86a 880KiB/3.6MiB(23%) CN:4 DL:159KiB ETA:17s]
```

**Comment by tone87** [comment]
i think youtube block my ip address is it possible ?  'cause if i try to open the url extract of the video , vlc media player or windows media player show me an error ..  is is possible to use a proxy to change ip address for the video source ?

**Comment by remitamine** [comment]
> i think youtube block my ip address is it possible ?

try other formats and see if they also didn't work
> is is possible to use a proxy to change ip address for the video source ?

you can use proxy option `--proxy URL` https://github.com/rg3/youtube-dl#network-options

**Comment by tone87** [comment]
here's the error : 
WARNING: [youtube] y74UPiaK7u0: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',) ERROR: unable to download video data: HTTP Error 403: Forbidden

can i use option "--source-address 1.1.1.1" ?

**Comment by dstftw** [comment]
Remove cache with `--rm-cache-dir`.

**Comment by tone87** [comment]
YEAAAAAAAHHH ;-) THANKS ;-) WORKS !!!
