### ISSUE TITLE
[minor bug] bad formatting of man page

### ISSUE THREAD

**Issue by alexvong1995** [rg3/youtube-dl#6510]
Some sections in the man page are badly formatted, notably in the OPTIONS section and the FAQ section. The problem is most likely caused by hard-coded spaces/tabs and line breaks.

Consider python(1):
![python_1](https://cloud.githubusercontent.com/assets/10696787/9159001/def151a6-3f52-11e5-9c87-56edd35a5605.png)
and youtube-dl(1):
![youtube-dl_1](https://cloud.githubusercontent.com/assets/10696787/9159002/e95968ea-3f52-11e5-98f6-ebada016fc15.png)

Also the Debian bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793054

When I run `make youtube-dl.1`, it shows:

    python devscripts/prepare_manpage.py >youtube-dl.1.temp.md
    pandoc -s -f markdown -t man youtube-dl.1.temp.md -o youtube-dl.1
    rm -f youtube-dl.1.temp.md

Should I try augmenting `devscripts/prepare_manpage.py`? Thanks!

-- System Information:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-4.1.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {}

**Comment by jaimeMF** [comment]
It's fixed now, thanks for the report and the proposed solution.

**Comment by alexvong1995** [comment]
Thanks, this resolves https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793054.
