### ISSUE TITLE
question

### ISSUE THREAD

**Issue by humner** [rg3/youtube-dl#6516]
greetings, I use the following command to download and extract audio from a video file in the resulting xy mp3 seem not to be closed, the player (pc) still playback even when the file playing time has already ended.

the command:
 youtube-dl -x --audio-format mp3 --audio-quality 9 "url" -o "archivos_mp3/name.mp3"

There is an option for the closure program or end the resulting MP3 file?
because it seems not to be closed the file.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by humner** [comment]
software@software-desktop ~/nube/youtube $ youtube-dl --verbose -x --audio-format mp3 --audio-quality 9  https://www.youtube.com/watch?v=zJcBCmhhUoE -o "archivos_mp3/test4.mp3" 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-x', '--audio-format', 'mp3', '--audio-quality', '9', 'https://www.youtube.com/watch?v=zJcBCmhhUoE', '-o', 'archivos_mp3/test4.mp3']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] Proxy map: {}
[youtube] Setting language
[youtube] zJcBCmhhUoE: Downloading webpage
[youtube] zJcBCmhhUoE: Downloading video info webpage
[youtube] zJcBCmhhUoE: Extracting video information
[download] Destination: archivos_mp3/test4.mp3
[download] 100% of 921.12KiB in 00:04
[youtube] Post-process file archivos_mp3/test4.mp3 exists, skipping
software@software-desktop ~/nube/youtube $

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by humner** [comment]
umm ok I will update and try again.
Thank you

**Comment by humner** [comment]
all fine, now if the file is closed....
