### ISSUE TITLE
youtube-dl Truck Factor

### ISSUE THREAD

**Issue by gavelino** [rg3/youtube-dl#6521]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **youtube-dl** and obtained a value of **3**.

The developers responsible for this TF are:

Philipp Hagemeister - author of 59% of the files
Sergey M. - author of 20% of the files
Jaime Marquinez Ferrandiz - author of 19% of the files

To validate our results, we would like to ask **youtube-dl** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **youtube-dl**?

(b) Do you agree that **youtube-dl** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **youtube-dl** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by dstftw** [comment]
I don't think youtube-dl will ever be in trouble since it's public domain.
Closing as offtopic.
