### ISSUE TITLE
Does it possible to pull youtube download links without ip??

### ISSUE THREAD

**Issue by jakineog** [rg3/youtube-dl#6524]
Below are the two link,

https://r9---sn-q4f7dm7d.googlevideo.com/videoplayback?itag=22&lmt=1439218530647442&source=youtube&upn=AWoBdJ7ihfU&mn=sn-q4f7dm7d&mm=31&pl=24&id=o-AMWhYdMmPfAH8hczNHA57SySzfbuNKsL60ekc9kkC52W&requiressl=yes&fexp=9405264%2C9406004%2C9408710%2C9408860%2C9409218%2C9412756%2C9412774%2C9415365%2C9415485%2C9416023%2C9416126%2C9416362%2C9416557%2C9416612%2C9416882%2C9417502%2C9417926%2C9418153%2C9418780&ip=78.6.9.2&mv=u&sparams=dur%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mt=1439273889&ms=au&dur=138.065&ipbits=0&sver=3&expire=1439295659&ratebypass=yes&gcr=us&nh=EAE&key=yt5&mime=video%2Fmp4&signature=1DEC83162EFDC451964A57D62BD15B84808A2CFA.75A6ACF1B78AF9B96058BA6E9845F4CA7E09A270

http://r9---sn-aigllnl7.googlevideo.com/videoplayback?dur=138.065&lmt=1439218530647442&mt=1439273999&ratebypass=yes&source=youtube&ms=au&pl=22&mv=m&ipbits=0&id=b5b045569466b6f8&mn=sn-aigllnl7&mm=31&expire=1439295659&upn=LaD9x25nLYE&itag=22&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Csource%2Cupn%2Cexpire&sver=3&fexp=9407538%2C9408093%2C9408710%2C9415365%2C9415435%2C9415485%2C9415745%2C9416023%2C9416075%2C9416126%2C9416729%2C9417269%2C9418016%2C9418059%2C9418153&ip=146.185.29.12&initcwndbps=13345000&key=yt5&mime=video%2Fmp4&nh=IgpwcjAyLmxocjE0KgkxMjcuMC4wLjE&signature=58B07966CC33A947AF85B92EC953542A9EA06205.AFE26272390CC05C7D19AFC89FF1734737F3A5C6&title=Welcome+Back+%28Title+Track%29+VIDEO+Song+-+Mika+Singh+-+John+Abraham+-+Welcome+Back+-+T-Series

The first one is fetch through youtube-dl, which work only in the given ip. But the other one is fetch from savefrom.net, which works everywhere.

So how can i completely off the ip from the fetch links, so that the link work through any ips. Is it possible now??

**Comment by dstftw** [comment]
Both does not work for me. Generally, extracted download URLs are only [guaranteed to work on the same machine/IP](https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-webbrowser).
