### ISSUE TITLE
How do I donate to you guys?

### ISSUE THREAD

**Issue by cajund** [rg3/youtube-dl#6532]
Your software has contributed significantly during a migration of 13 sites. So far, I have downloaded more than 1000gb of videos, converting them to .mp4's (and I am only half way through the project). The folks on the team want to buy you guys a beer. Tell me how I do that!!!

Thanks for a great and handy piece of software!

**Comment by yan12125** [comment]
Thanks for loving this software! Here is some information: http://rg3.github.io/youtube-dl/donations.html
