### ISSUE TITLE
Extract Error Could not download dash manifest HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Bryannn** [rg3/youtube-dl#6545]
Hi, I'm not able to download any videos from YouTube it gives me this error. Extract Error Could not download dash manifest HTTP Error 403: Forbidden 
I have the latest version installed. Would downgrading to the last worked version fix this issue and if it would could someone give me the commands to downgrade to the previous version. Thanks

This is the exact error:

[youtube] Mk7-GRWq7wA: Downloading webpage
[youtube] Mk7-GRWq7wA: Downloading video info webpage
[youtube] Mk7-GRWq7wA: Extracting video information
[youtube] Mk7-GRWq7wA: Downloading DASH manifest
WARNING: [youtube] Mk7-GRWq7wA: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
ERROR: unable to download video data: HTTP Error 403: Forbidden

and then nothing happens.

**Comment by Djavvalen** [comment]
same issue, but i upgraded to windows 10 tho

**Comment by yangofzeal** [comment]
same issue here, Mac OSX on about any youtube video post HTML-5 upgrade.

**Comment by Djavvalen** [comment]
my friend helped me fix the problem, the solution:

open your cmd panel 
fill your path in together with the command --no-cache-dir (+ a random youtube link) 
into your cmd 

for example:
"C:\SinusBot\youtube-dl.exe" --no-cache-dir "https://www.youtube.com/watch?v=EpbjEttizy8"

and its fixed, no problem ;)

**Comment by yangofzeal** [comment]
Excellent.  Adding the -no-cache-dir option fixes the download.  Originally the problem sometimes only occurred when using -k option but adding no cache dir seems to fix it.  Thanks!

**Comment by Bryannn** [comment]
Thank you so much Djavvalen. This works like a charm. Appreciated!
