### ISSUE TITLE
ExtractorError: YouTube said: This video contains content from SME, who has blocked it in your country on copyright grounds.

### ISSUE THREAD

**Issue by yangofzeal** [rg3/youtube-dl#6547]
## from  US-based IP:
$ youtube-dl -k --verbose --no-cache-dir https://www.youtube.com/watch?v=OLzK_ewEilE
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-k', u'--verbose', u'--no-cache-dir', u'https://www.youtube.com/watch?v=OLzK_ewEilE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.10 - Darwin-12.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.3.3, ffprobe 2.3.3
[debug] Proxy map: {}
[youtube] OLzK_ewEilE: Downloading webpage
[youtube] OLzK_ewEilE: Downloading video info webpage
ERROR: OLzK_ewEilE: YouTube said: This video contains content from SME, who has blocked it in your country on copyright grounds.
Traceback (most recent call last):
  File "/Users/msyang/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/Users/msyang/bin/youtube-dl/youtube_dl/extractor/common.py", line 286, in extract
    return self._real_extract(url)
  File "/Users/msyang/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1063, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: OLzK_ewEilE: YouTube said: This video contains content from SME, who has blocked it in your country on copyright grounds.

**Comment by yan12125** [comment]
Can you watch this video in browsers without relays like proxies or VPNs?

**Comment by yangofzeal** [comment]
No.  I was wondering if there's an option to spoof an ip.

**Comment by yan12125** [comment]
```--proxy``` may be helpful.

**Comment by AurelFR** [comment]
i had the same error /what i did ?just copy the youtube link in tor browser ,run the link ,then copy the download link to ffmpeg /for me was working

**Comment by Droyk** [comment]
> i had the same error /what i did ?just copy the youtube link in tor browser ,run the link ,then copy the download link to ffmpeg /for me was working

Can you please explain what do you mean by that? I tried the same thing but it didn't work out I copied the link from my default browser to tor and press enter it is still showing 
>This video contains content from SME, who has blocked it in your country on copyright grounds.

I want to download this video https://www.youtube.com/watch?v=APY-dar9c10

**Comment by Droyk** [comment]
@yan12125 I tried using VPN & multiple proxies still can't download it nor I can watch it any help
this is the video https://www.youtube.com/watch?v=APY-dar9c10

**Comment by yan12125** [comment]
I don't think copyrighted videos can be downloaded. If you can watch it in browsers with some VPN or proxy and are not sure how to make youtube-dl to the same VPN/proxy, ask on IRC.
