### ISSUE TITLE
rental video mode - not supported

### ISSUE THREAD

**Issue by shevegen** [rg3/youtube-dl#6552]
Hi,

Perhaps no support for youtube-dl can be enabled for this BUT

perhaps the error message could be different such as "youtube-dl can
not support rental mode" or so.

Command used:

    youtube-dl --verbose  https://www.youtube.com/watch?v=nrcpzQLuKEE

Output of the above:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=nrcpzQLuKEE']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.10 - Linux-4.0.0-2-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2
[debug] Proxy map: {}
[youtube] nrcpzQLuKEE: Downloading webpage
[youtube] nrcpzQLuKEE: Downloading video info webpage
WARNING: Unable to extract video title

ERROR: "rental" videos not supported; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 286, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1125, in _real_extract
    raise ExtractorError('"rental" videos not supported')
ExtractorError: "rental" videos not supported; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
I don't see much difference. For me current message is even more clear since it states exactly what it can't do instead of ambiguous *unsupported rental mode*.
