### ISSUE TITLE
Lynda.com unable to login

### ISSUE THREAD

**Issue by attiqfsd** [rg3/youtube-dl#6556]
When I try to download lynda courses using my premium login, it gives this output:
"# youtube-dl http://www.lynda.com/Camera-Raw-tutorials/Adobe-Camera-Raw-Essential-Training/413123-2.html --username USERNAME --password PWD
[lynda:course] Logging in as USERNAME
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."
I am using latest version of youtube-dl.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by attiqfsd** [comment]
Like this?
# youtube-dl http://www.lynda.com/Camera-Raw-tutorials/Adobe-Camera-Raw-Essential-Training/413123-2.html --username USERNAME --password PASSWORD --verbose                    [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.lynda.com/Camera-Raw-tutorials/Adobe-Camera-Raw-Essential-Training/413123-2.html', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--verbose']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.6 - Linux-2.6.32-042stab103.6-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Logging in as USERNAME
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 285, in extract
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 279, in initialize
    self._real_initialize()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/lynda.py", line 24, in _real_initialize
    self._login()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/lynda.py", line 73, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Works fine for me. Post the output of:
```
youtube-dl --username USERNAME --password PASSWORD --dump-pages --verbose http://www.lynda.com/Camera-Raw-tutorials/Adobe-Camera-Raw-Essential-Training/413123-2.html
```

**Comment by attiqfsd** [comment]
Here it is.
http://pastebin.com/FRSCjFAN

**Comment by dstftw** [comment]
It states:
```
 lynda.com » login error
Permission denied

You no longer have access to lynda.com through your organization. Log in with your past profile information, start a new membership, and take your course history with you.
```

**Comment by dstftw** [comment]
In the next version youtube-dl will output login errors' description.
