### ISSUE TITLE
-o different filenames of multiple files when downloading more formats of a youtube-video

### ISSUE THREAD

**Issue by Klaus1189** [rg3/youtube-dl#6557]
If you want to download a video in different formats and want to build different filenames for the files, I don't find the solution to set up different filenames with -o 
May you please tell me how to do it?

If it's not possible, I want to make a feature request for this.

Thank you

**Comment by dstftw** [comment]
Read [FAQ on `-o`](https://github.com/rg3/youtube-dl#output-template).

**Comment by Klaus1189** [comment]
I don't get it. Which syntax do I need?

**Comment by Klaus1189** [comment]
I already read this, but I don't know how to put in different filenames for the different files. 
Please help me.

**Comment by yan12125** [comment]
What you need is ```format_id```. Here's a quick example:
```
$ youtube-dl -o "%(title)s-%(id)s-%(format_id)s.%(ext)s" --get-filename test:youtube
youtube-dl test video ''_ä↭𝕐-BaW_jenozKc-137+141.mp4
```
It's documented in [Filesystem options](https://github.com/rg3/youtube-dl#filesystem-options) section. However, it's not so easy to find, so I add an item in [Output template](https://github.com/rg3/youtube-dl#output-template) section.

**Comment by Klaus1189** [comment]
OK, thank you. So `%(format_id)s` is for the itag value.
My intention for this issue:
Is it possible to type in text for the different filenames by hand with `-o`?

**Comment by yan12125** [comment]
Not really sure what's the meaning of "by hand". Can you give a more concrete example?

**Comment by Klaus1189** [comment]
For example I want to download a video from youtube in two or more formats. But the files should be named abcdef.mp4 and ghijkl.mp4:
`youtube-dl -f 136,135 https://www.youtube.com/watch?v=YuOBzWF0Aws  -o "abcdef.%(ext)s" "ghijkl.%(ext)s"`

But this doesn't work, I need a separator for the two filename in `-o`
Without it it is recognized as one filename.

**Comment by Klaus1189** [comment]
Do you know how I can do that?

**Comment by yan12125** [comment]
It's not possible with youtube-dl only. A possible solution is using ```%(autonumber)s.%(ext)s``` and rename the files with another script.

**Comment by Klaus1189** [comment]
OK, I see. Can we make a feature request of this issue, so youtube-dl can do that?

**Comment by yan12125** [comment]
I prefer using extra scripts. Filename computation is a quite complex part in youtube-dl. Changing it is not a good idea.

**Comment by dstftw** [comment]
Why not just download separately?
```
youtube-dl -f 136 https://www.youtube.com/watch?v=YuOBzWF0Aws -o "abcdef.%(ext)s"
youtube-dl -f 135 https://www.youtube.com/watch?v=YuOBzWF0Aws -o "ghijkl.%(ext)s"
```

**Comment by Klaus1189** [comment]
If you download for example 5 videos and want each video in three formats, then you need to download 5 times instead of 15 times.
-> It would be a really usefull feature, only one time to download and you have all files you want of the desired video.
I know how to download with a batch-list, but this would be much better especially for most download usage scenarios.

**Comment by dstftw** [comment]
The only gain you'll get is that you'll download data needed for extraction once instead of 3 times for each video. But still this would be neglected by the same 15 media files you'll need to download in any case that will consume much more time and bandwidth in comparison to extraction data.
As already mentioned by @yan12125 just use `%(format_id)s` in output template and perform filename-based postprocessing substituting format codes by your strings.

**Comment by Klaus1189** [comment]
OK. I see.

I beg to add this funktionality to youtube-dl. 
Then it would be perfect. I'm sure it's possible to achieve that behavior. 
It's only a separator like `;;` or something like this and youtube-dl knows, OK, we download three files and there are two separators `;;` and then it puts the string to the right file. 

Please add this feature.

**Comment by dstftw** [comment]
Separator for what? If you want anything to be implemented you have to clearly formulate it in the first place.
I would prefer keeping output template as is since your suggestion of multiple -o args `-o "template1" "template2" ...` breaks the original idea of single output template and doesn't fit into current format selection mechanisms.

**Comment by Klaus1189** [comment]
`youtube-dl -f 136,135 https://www.youtube.com/watch?v=YuOBzWF0Aws -o "abcdef.%(ext)s" ;; "ghijkl.%(ext)s"`
separator between the strings of `-o`

Sounds like it's not possible to add that?

**Comment by dstftw** [comment]
No, that's counter-intuitive to regular CLI UX.

**Comment by Klaus1189** [comment]
What?

**Comment by dstftw** [comment]
The way command line programs are usually used.

**Comment by Klaus1189** [comment]
OK, I see. That would have been great, but now I know it can't be done. I'm sad now
Anyway, Thank you
BTW: Is it possible to link to a txt-file with proxy in it in `--proxy URL`

**Comment by dstftw** [comment]
>txt-file with proxy in it in `--proxy URL`

For what?

**Comment by Klaus1189** [comment]
Just a thought, so I can paste the proxy like `192.168.178.001:0123` in a txt-file and while using youtube-dl I give the path to the txt-file.

**Comment by dstftw** [comment]
I mean what is the scenario for youtube-dl to use this list?

**Comment by Klaus1189** [comment]
If I need a proxy because the video is blocked in bavaria and I need a proxy, then I look up for a proxy and paste it in the txt-file and the proxy-string in cmd.exe can stay like it is.

**Comment by dstftw** [comment]
This does not rationalize the need of proxy list instead of single proxy.

**Comment by Klaus1189** [comment]
No, not a list. 
Only one proxy in the txt-file, so I don't have to change my long string which contains the proxy several times. 
Then I only copy the new working proxy to the txt-file and youtube-dl reads the proxy in the txt-file and the string contains the links to the txt-file instead of the proxy itself.

**Comment by dstftw** [comment]
You can achieve this with [configuration file](https://github.com/rg3/youtube-dl#configuration) as well as put any default options in it.

**Comment by Klaus1189** [comment]
Do you have more information about the configuration file?

**Comment by dstftw** [comment]
What info you need?

**Comment by Klaus1189** [comment]
How do I set up such a file with the proxy setting for example and what things can I set up in the file? 
-> Which options are available? Something like that?  `--proxy 123.456.789:0123`

**Comment by dstftw** [comment]
Yes. Any option you pass in command line can be put into configuration file.

**Comment by Klaus1189** [comment]
So a configuration file for example only consist of ` --proxy 123.456.789:0123`
and then youtube-dl will always use that proxy?

**Comment by dstftw** [comment]
Exactly.

**Comment by Klaus1189** [comment]
Thank you very much.

**Comment by Klaus1189** [comment]
I copied config.txt to the location in appdata, but it doesn't work.

**Comment by Klaus1189** [comment]
Now I copied it to users ... youtube-dl.conf.
Now it works.
