### ISSUE TITLE
Unable to download some youtube videos

### ISSUE THREAD

**Issue by ZmotriN** [rg3/youtube-dl#6561]
https://www.youtube.com/watch?v=bYU3j-22360
https://www.youtube.com/watch?v=W5dYNkgCQn8

>youtube-dl -v bYU3j-22360
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'bYU3j-22360']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-73165-gf1e1730, ffprobe N-73165-gf1e1730, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] bYU3j-22360: Downloading webpage
[youtube] bYU3j-22360: Downloading video info webpage
[youtube] bYU3j-22360: Extracting video information
[youtube] {22} signature length 40.42, html5 player new
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {137} signature length 40.42, html5 player new
[youtube] {248} signature length 40.42, html5 player new
[youtube] {136} signature length 40.42, html5 player new
[youtube] {247} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {278} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] {249} signature length 40.42, html5 player new
[youtube] {250} signature length 40.42, html5 player new
[youtube] {251} signature length 40.42, html5 player new
[youtube] bYU3j-22360: Downloading DASH manifest
WARNING: [youtube] bYU3j-22360: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused
 by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to up
date. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r1---sn-4pcgxovpgx-t0ae.googlevideo.com/videoplayback?initcwndbps=7790000&sver=3&lmt=14394797749116
11&gcr=ca&expire=1439593430&ipbits=0&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2C
mn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&keepalive=yes&gir=yes&clen=337169516&itag=137&key=yt5&mime=video%2Fmp4&upn=XRPTXu7BfB
w&requiressl=yes&dur=993.840&id=o-AMQg0qGkmHAfAQ31o_dEKLbSv-9WwKINsSMTKRxALkX6&mn=sn-4pcgxovpgx-t0ae&pl=22&mm=31&fexp=9407573%2C9408710%2C94
09069%2C9409219%2C9412774%2C9415365%2C9415485%2C9415661%2C9416023%2C9416126%2C9416331%2C9416525%2C9416837%2C9416985%2C9417269%2C9417707%2C94
18153%2C9418184%2C9418393%2C9419052&ms=au&mv=m&source=youtube&mt=1439571749&ip=45.61.4.138&signature=C3D6E2ED0E682428663BD05B1D8572CD9E9B4B7
9.DED4DC647567D85E965D0EC73F67937A606162A7&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1579, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1527, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 60, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1860, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden

>youtube-dl -v W5dYNkgCQn8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'W5dYNkgCQn8']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-73165-gf1e1730, ffprobe N-73165-gf1e1730, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] W5dYNkgCQn8: Downloading webpage
[youtube] W5dYNkgCQn8: Downloading video info webpage
[youtube] W5dYNkgCQn8: Extracting video information
[youtube] {22} signature length 40.42, html5 player new
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.40, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {137} signature length 40.42, html5 player new
[youtube] {248} signature length 40.42, html5 player new
[youtube] {136} signature length 40.42, html5 player new
[youtube] {247} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] W5dYNkgCQn8: Downloading DASH manifest
WARNING: [youtube] W5dYNkgCQn8: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused
 by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to up
date. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r1---sn-4pcgxovpgx-t0ae.googlevideo.com/videoplayback?mime=video%2Fmp4&gcr=ca&dur=159.701&upn=7egqQ
u_JsXE&requiressl=yes&itag=137&gir=yes&ip=45.61.4.138&mn=sn-4pcgxovpgx-t0ae&mm=31&source=youtube&ms=au&id=o-AGXQZUuH9WE6NuAjwazCPrlTLqNefhyk
HMegmn3NwkXg&pl=22&mv=m&mt=1439571749&initcwndbps=7790000&key=yt5&ipbits=0&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2
Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&expire=1439593493&clen=66111792&lmt=14388897753
13204&keepalive=yes&fexp=9408710%2C9409069%2C9415365%2C9415485%2C9416023%2C9416126%2C9417707%2C9418153&sver=3&signature=7F812957A3F8D2AC25A0
8C01D762638C8E86BF62.283D77B27F392ABC66592BD01DA8F831A18CE3FC&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1579, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1527, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 60, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1860, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden

**Comment by jamiesonbecker** [comment]
Also https://www.youtube.com/watch?v=lydOsQEcTek&list=PL6n_XTD5fjYG7rpzqjHQ3vnYvTrYjgk0M

**Comment by jamiesonbecker** [comment]
Clearing youtube-dl cache worked for me. See https://github.com/rg3/youtube-dl/issues/6451

**Comment by ZmotriN** [comment]
Ok thanks. It works.
