### ISSUE TITLE
charmap coded can't encode character

### ISSUE THREAD

**Issue by r0f1** [rg3/youtube-dl#6566]
If I try downloading a video, that has special unicode chars in its title I get an exeception:

    b"'charmap' codec can't encode character '\\u2014' in position 45: character maps to <undefined>"

Example: Try this video

     https://www.youtube.com/watch?v=kMgP0lFyVXA

which contains a special dash in its title. The options I am using are: 

    options = {
        "outtmpl": u"%(title)s.%(ext)s",
        "restrict_filenames": True
    }

I there a way to tell the program (eg. via the output template parameter), that special chars in the title should be escaped?

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by r0f1** [comment]
Program:

    import sys
    from youtube_dl import YoutubeDL
		
    def print_progress(d):
	    k = dict(d)
	    if d["status"] == "downloading":
		    msg = "\r[%(status)s] %(_percent_str)s of %(_total_bytes_str)s %(filename)s"
	    else:
		    msg = "\n[%(status)s] %(filename)s"	

	    sys.stdout.write(msg % k)
	    sys.stdout.flush()
	
		
    options = {
	    "outtmpl": u"%(title)s.%(ext)s",
	    "postprocessors": [{
		    "key": "FFmpegExtractAudio",
		    "preferredcodec": "mp3"
	    }],
	    "progress_hooks": [print_progress],
	    "restrict_filenames": True,
	    "verbose": True
    }
	
    with YoutubeDL(options) as ydl:
	    ydl.download(["http://www.youtube.com/watch?v=kMgP0lFyVXA"])
		

Output: http://pastebin.com/Da5ECtML

I am using Windows 7 and Python Version: 3.4.1

**Comment by dstftw** [comment]
It fails in your code namely at this line:
```
sys.stdout.write(msg % k)
```
You have to use proper encoding that is supported by your terminal. If you don't want to deal with this yourself use `ydl.to_stdout` instead.
