### ISSUE TITLE
how to download update date?

### ISSUE THREAD

**Issue by massecre2** [rg3/youtube-dl#6570]
Hi. i wanna download upload today date and before videos. write this code in commant prompt 

youtube-dl --datebefore 20150816 "%(title)s.%(ext)s" ytsearch200:"blabla"

but this not working. i dont understand. sorry i'm a newbie.

**Comment by dstftw** [comment]
`youtube-dl --datebefore 20150816 ytsearch200:"blabla"`

**Comment by massecre2** [comment]
hi , thans for reply but i wanna download D: , so in C: is not enought space.

**Comment by dstftw** [comment]
Either `cd` to `D:/` or use [output template](https://github.com/rg3/youtube-dl#output-template).

**Comment by massecre2** [comment]
so thnx.

**Comment by massecre2** [comment]
i try but not download first video , go to 9. index and try not download 10 , 11 , 12 , 13 go to 14. index video and download.
