### ISSUE TITLE
Youtube DASH manifest: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by voidshard** [rg3/youtube-dl#6573]
Getting this error on youtube. I've updated to the latest version, tried multiple videos & playlists.

youtube-dl -i https://www.youtube.com/watch?v=xFrGuyw1V8s&list=PLE9F62B21C75C054C 

[youtube] xFrGuyw1V8s: Downloading webpage
[youtube] xFrGuyw1V8s: Downloading video info webpage
[youtube] xFrGuyw1V8s: Extracting video information
[youtube] xFrGuyw1V8s: Downloading DASH manifest
WARNING: [youtube] xFrGuyw1V8s: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by yan12125** [comment]
A duplicate of #6451.
