### ISSUE TITLE
wat.tv some videos can't be downloaded

### ISSUE THREAD

**Issue by dabiboo** [rg3/youtube-dl#6577]
Hello,

I'm having troubles downloading some wat.tv videos.
Ex : 
youtube-dl -v http://www.wat.tv/video/anna-bergendahl-for-you-2015-7dvjn_76lkz_.html

--> 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.wat.tv/video/anna-bergendahl-for-you-2015-7dvjn_76lkz_.html']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.08.16
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-43060-ga85b4a5, ffprobe N-43060-ga85b4a5
[debug] Proxy map: {}
[wat.tv] anna-bergendahl-for-you-2015: Downloading webpage
[wat.tv] 12404723: Downloading JSON metadata
ERROR: wat.tv returned error: <a href="http://www.wat.tv/video/anna-bergendahl-for-you-2015-7dvjn_76lkz_.html">Ce contenu n'est pas disponible directement dans ce player<br /><br />Pour le consulter cliquer ici</a>
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 655, in extract_info
  File "youtube_dl\extractor\common.pyo", line 287, in extract
  File "youtube_dl\extractor\wat.pyo", line 67, in _real_extract
ExtractorError: wat.tv returned error: <a href="http://www.wat.tv/video/anna-bergendahl-for-you-2015-7dvjn_76lkz_.html">Ce contenu n'est pas disponible directement dans ce player<br /><br />Pour le consulter cliquer ici</a>

Are theses videos protected or something ?

**Comment by dstftw** [comment]
Can you watch it in browser?

**Comment by dabiboo** [comment]
Yes, in my browser I can watch it.

I've just figured out the video is not reachable from the android app.

**Comment by dstftw** [comment]
I can't watch it in browser as well as download. However I can both view in browser and download, for example, this video http://www.wat.tv/video/20-heures-aout-2015-7jgjt_2i0u7_.html.

**Comment by dabiboo** [comment]
Ok so I guess you're not in France and this content is geoblocked. It cames from "Universal Music France"  so It makes sense they block it.

**Comment by dstftw** [comment]
No. For georestricted videos I get different error that clearly state this:
```
Ce contenu n'est pas disponible dans votre zone géographique
```

For http://www.wat.tv/video/anna-bergendahl-for-you-2015-7dvjn_76lkz_.html in browser I get
```
Cannot load M3U8:
No levels to play
```
with non-french IP and
```
Error loading player:
No playable sources found
```
with french IP.

**Comment by dabiboo** [comment]
Ok. I don't know why you can't open it. 
Anyway, It's not a real wat.tv video :
the page  http://www.wat.tv/video/anna-bergendahl-for-you-2015-7dvjn_76lkz_.html
is opening an iframe to :
http://www.universalmusic.fr/artiste/7415-anna-bergendahl/videos/4555-for-you-remix-lyric-video.iframe
Then the video doesn't seem to be protected.

So maybe we could create a new extractor "UniversalMusic" and redirect the wat extractor to this one in this case. I could try...

**Comment by dabiboo** [comment]
another case, another redirection needed : www.wat.tv/video/david-guetta-titanium-feat-sia-4v6p5_4v69t_.html
this video is hosted on ultimedia using an iframe :
http://www.ultimedia.com/deliver/musique/iframe/mdtk/01448585/zone/1/article/qzkfx3/width/640/height/360/
this link can't be downloaded by the ulmedia extractor but this one can : 
http://www.ultimedia.com/default/index/videomusic/id/qzkfx3

**Comment by dstftw** [comment]
wat.tv no longer exists.
