### ISSUE TITLE
No any items from youtube search!

### ISSUE THREAD

**Issue by marabu88** [rg3/youtube-dl#6578]
I use command for auto-download new videos from page with youtube search results:

youtube-dl --verbose -i --playlist-end 10 -f bestvideo+bestaudio --merge-output-format mkv "http://www.youtube.com/results?search_query=yoga+challenge&lclk=hour&filters=hour&search_sort=video_date_uploaded" 

but see only it:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-i', u'--playlist-end', u'10', u'-f'
, u'bestvideo+bestaudio', u'--merge-output-format', u'mkv', u'http://www.youtube
.com/results?search_query=yoga+challenge&lclk=hour&filters=hour&search_sort=vide
o_date_uploaded']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.08.16
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: avconv v11.1, avprobe v11.1
[debug] Proxy map: {}
[youtube:search_url] yoga challenge: Downloading webpage
[download] Downloading playlist: yoga challenge
[youtube:search_url] playlist yoga challenge: Collected 0 video ids (downloading 0 of them)

In all browsers this url open without any authorization with some videos! before it worked without any problems! what happened now?!

if google changed the format of the output or set some protection - what do I do?

**Comment by dstftw** [comment]
Will be fixed in the next version.

**Comment by marabu88** [comment]
thanks!
