### ISSUE TITLE
Playlist Missing OpenGraph Title.

### ISSUE THREAD

**Issue by TheNerdiestZeldaGeek** [rg3/youtube-dl#6579]
![screenshot](https://cloud.githubusercontent.com/assets/13821917/9294452/947bbfa6-4413-11e5-8257-f2fc3c8ff612.png)

I'm not sure what is up with this. I only got this issue after switching to Linux Mint. Previously I was using Zorin OS, but I switched and now I'm getting this problem.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by TheNerdiestZeldaGeek** [comment]
![screenshot-1](https://cloud.githubusercontent.com/assets/13821917/9294498/814239dc-4414-11e5-8697-a113ec38b3f8.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/13821917/9294499/8148641a-4414-11e5-8796-8f042e8a6644.png)

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by dstftw** [comment]
Next time you post bugreport, post it as log not a picture.
