### ISSUE TITLE
[Feature Request] Crop Embeded Thumbnail

### ISSUE THREAD

**Issue by xavhan** [rg3/youtube-dl#6580]
Most of the time when you download audio  via  youtube-dl and use the `--embed-thumbnail`, the purpose is to add it as the cover picture for the track in the audio metadatas.

Problem is that 99,99% of the time audio covers are square and 100% of the time youtube video thumbnails are not.

A `--crop-embed-thumbnail` would be great for that purpose. 
- By default cropping the biggest centered square possible in the downloaded thumbnail to match the cover picture (without the black background).
- Why not adding arguments for more detailled cropping.

It seems adding the ffmpeg crop filter would do the job :  `crop=in_h`

What do you think?

**Comment by soisme** [comment]
you can crop it by yourself using imagemagick

**Comment by xavhan** [comment]
@soisme I know thanks ;)
But I 'd like to do it at download time and  I still dont know how to pipe the cropping in the formatting process.  ¯\_(ツ)_/¯
