### ISSUE TITLE
dailymotion videos cannot download

### ISSUE THREAD

**Issue by nexusmillenium** [rg3/youtube-dl#6581]
When trying to download from http://www.dailymotion.com/video/x31ami9
I getting this error:
ERROR: Unable to download webpage: <urlopen error [Errno 6] _ssl.c:504: TLS/SSL connection has been closed> (caused by URLError(SSLError(6, '_ssl.c:504: TLS/SSL connection has been closed'),))

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by nexusmillenium** [comment]
I can't watch it in browser. Here is the full output...

bpi ~ :( # youtube-dl --verbose http://www.dailymotion.com/video/x31ami9
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.dailymotion.com/video/x31ami9']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16
[debug] Python version 2.7.3 - Linux-3.4.90-armv7l-with-debian-7.8
[debug] exe versions: avconv 9.14-6, avprobe 9.14-6, ffmpeg 0.8.17-6, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] x31ami9: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
>I can't watch it in browser

Therefore you can't download it.
