### ISSUE TITLE
How to Prevent webm downloading

### ISSUE THREAD

**Issue by MrPaulAR** [rg3/youtube-dl#6584]
I've tried using --prefer-free-formats and that doesn't work, at least not how I expect.  From what I can tell after messing with it & googling the mp4 is only used IF there is a resolution tie and bitrate tie.  I would like to never download a webm.

I've been doing this manually in the past with -f VIDEO+AUDIO (not using the numbers here as they vary) but would like something a bit more permanent.

Any suggestions?

**Comment by barsnick** [comment]
Using `--prefer-free-formats` will **not** prevent webm, it will *prefer* webm over mp4.

Assuming these formats are offered (they are with YouTube), you would use this option to ensure mp4:
`-f "bestvideo[ext=mp4]+bestaudio[ext=m4a]"`

**Comment by dstftw** [comment]
Use `-f 'bestvideo[ext!=webm]+bestaudio[ext!=webm]/best[ext!=webm]'`.

**Comment by jjgh** [comment]
Hi @dstftw, just to make sure I understand your example, will using `-f bestaudio[ext!=webm]` alone download the second best audio, if best audio is webm?

**Comment by dstftw** [comment]
Depends on what is the second best audio.
