### ISSUE TITLE
Error with new installation of youtube-dl

### ISSUE THREAD

**Issue by Dreeg** [rg3/youtube-dl#6589]
Hi all,
on RPi2 with Raspbian I just installed youtube-dl and when I try to DL a videos the software return me this error:

Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 75, in <module>
    import xml.etree.ElementTree
ValueError: bad marshal data (unknown type code)

**Comment by yan12125** [comment]
Can you run the following command:
```
$ python -c 'import xml.etree.ElementTree as ET; print(ET)'                   
```
The result should looks like:
```
<module 'xml.etree.ElementTree' from '/usr/lib/python3.4/xml/etree/ElementTree.py'>
```

**Comment by Dreeg** [comment]
The result of 
```
python -c 'import xml.etree.ElementTree as ET; print(ET)'
```
is

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: bad marshal data (unknown type code)
```

**Comment by yan12125** [comment]
This should be a Raspbian issue rather than youtube-dl's problem. Try to ask for help on RPi forums.
