### ISSUE TITLE
dailymotion download is broken

### ISSUE THREAD

**Issue by sputnick-dev** [rg3/youtube-dl#6606]
Hi,

    $ youtube-dl --version
    2015.08.16.1

linux Mint 17.1 Rebecca

tested 3 urls : 
http://www.dailymotion.com/video/x324740_une-femme-se-venge-de-son-mec-qui-l-a-trompe_news
http://www.dailymotion.com/video/x323ksp_atlas-de-boston-dynamics-un-robot-qui-marche_tech
http://www.dailymotion.com/video/x2fky74

none works. One example in verbose mode : 

    $ youtube-dl --verbose 'http://www.dailymotion.com/video/x324740_une-femme-se-venge-de-son-mec-qui-l-a-trompe_news'
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'--no-mtime', u'--verbose', u'http://www.dailymotion.com/video/x324740_une-femme-se-venge-de-son-mec-qui-l-a-trompe_news']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.08.16.1
    [debug] Python version 2.7.6 - Linux-3.13.0-57-generic-x86_64-with-LinuxMint-17.1-rebecca
    [debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.7.1-1, ffprobe 2.7.1-1
    [debug] Proxy map: {}
    [dailymotion] x324740: Downloading webpage
    ERROR: An extractor error has occured. (caused by KeyError(u'qualities',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
        return self._real_extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 128, in _real_extract
        for quality, media_list in metadata['qualities'].items():
    KeyError: u'qualities'
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
        ie_result = ie.extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 293, in extract
        raise ExtractorError('An extractor error has occured.', cause=e)
    ExtractorError: An extractor error has occured. (caused by KeyError(u'qualities',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Post the output of `youtube-dl -v --dump-pages http://www.dailymotion.com/video/x324740_une-femme-se-venge-de-son-mec-qui-l-a-trompe_news`.

**Comment by sputnick-dev** [comment]
Humm, the original command is working today, maybe dailymotion was down yesterday ? IF you still need to dump the page, tell me.
