### ISSUE TITLE
Download from vk.com not work

### ISSUE THREAD

**Issue by dimka11** [rg3/youtube-dl#6609]
Microsoft Windows [Version 6.3.9600]
(c) Корпорация Майкрософт (Microsoft Corporation), 2013. Все права защищены.

C:\Users\Dima>youtube-dl http://vk.com/videos-901607?section=all&z=video-901607_
171325410%2Fclub901607%2Calbum-901607%2Fpl_-901607
[generic] videos-901607?section=all: Requesting header
WARNING: Could not send HEAD request to http://vk.com/videos-901607?section=all:
 HTTP Error 501: Not Implemented
[generic] videos-901607?section=all: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] videos-901607?section=all: Extracting information
[redirect] Following redirect to http://vk.com/badbrowser.php
[generic] badbrowser: Requesting header
WARNING: Could not send HEAD request to http://vk.com/badbrowser.php: HTTP Error
 501: Not Implemented
[generic] badbrowser: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] badbrowser: Extracting information
ERROR: Unsupported URL: http://vk.com/badbrowser.php
"z" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

C:\Users\Dima>

**Comment by dstftw** [comment]
[Read FAQ](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).
