### ISSUE TITLE
YouTube said: This video contains content from, who has blocked it from display on this website

### ISSUE THREAD

**Issue by HemangShah1** [rg3/youtube-dl#6612]
Unable to download this youtube video: http://www.youtube.com/watch?v=USAXbz1JALw. Able to view this video in browser only when signed in to YouTube.

I have the latest youtube-dl (2015.08.16.1).

user@user:/tmp$ /home/user/install/youtube-dl/youtube-dl -v http://www.youtube.com/watch?v=USAXbz1JALw
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=USAXbz1JALw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.4 - Linux-3.8.0-29-generic-i686-with-Ubuntu-13.04-raring
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] USAXbz1JALw: Downloading webpage
[youtube] USAXbz1JALw: Downloading embed webpage
[youtube] USAXbz1JALw: Refetching age-gated info webpage
ERROR: USAXbz1JALw: YouTube said: This video contains content from Multi Screen Media, who has blocked it from display on this website.<br/><u><a href='http://www.youtube.com/watch?v=USAXbz1JALw&feature=player_embedded' target='_blank'>Watch on YouTube</a></u>
Traceback (most recent call last):
  File "/home/user/install/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/home/user/install/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/home/user/install/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1078, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: USAXbz1JALw: YouTube said: This video contains content from Multi Screen Media, who has blocked it from display on this website.<br/><u><a href='http://www.youtube.com/watch?v=USAXbz1JALw&feature=player_embedded' target='_blank'>Watch on YouTube</a></u>

**Comment by yan12125** [comment]
The approach youtube-dl uses for bypassing age restriction is not applicable for this video. You need to provide credentials via ```--username``` and ```--password``` or ```--netrc``` for downloading this video correctly.
