### ISSUE TITLE
site-support-request: cinema.arte.tv

### ISSUE THREAD

**Issue by snscltt** [rg3/youtube-dl#6613]
Several URLs on arte.tv are already supported, but not this one:

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://cinema.arte.tv/de/artikel/polizeifilm-von-wim-wenders']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 3.4.3 - Linux-3.17.4-hardened-r1-x86_64-AMD_Phenom-tm-_II_X4_965_Processor-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3
[debug] Proxy map: {}
[generic] polizeifilm-von-wim-wenders: Requesting header
WARNING: Falling back on generic information extractor.
[generic] polizeifilm-von-wim-wenders: Downloading webpage
[generic] polizeifilm-von-wim-wenders: Extracting information
ERROR: Unsupported URL: http://cinema.arte.tv/de/artikel/polizeifilm-von-wim-wenders
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/generic.py", line 1804, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://cinema.arte.tv/de/artikel/polizeifilm-von-wim-wenders
```

**Comment by crazyiop** [comment]
This video was only temporarily available. 
Other similar link such as http://cinema.arte.tv/fr/article/les-ailes-du-desir-de-julia-reck works fine.
Problem certainly was an unavailable video at the time.

**Comment by eimann** [comment]
@crazyiop This did not have anything to do with expiring links. The extractor was added in 2016.01.23, in this commit 4fcd9d147df9b06d954b8f8a1749b50609529ed4

IMHO @jaimeMF can close this issue as it is working now.

**Comment by snscltt** [comment]
I'm sorry to tell you that it's not ixed for me:
`youtube-dl -v http://cinema.arte.tv/de/artikel/polizeifilm-von-wim-wenders                      
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://cinema.arte.tv/de/artikel/polizeifilm-von-wim-wenders']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.10
[debug] Python version 2.7.10 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[arte.tv:cinema] artikel/polizeifilm-von-wim-wenders: Downloading webpage
[arte.tv:cinema] artikel/polizeifilm-von-wim-wenders: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'VTI',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 315, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/arte.py", line 84, in _real_extract
    return self._extract_from_webpage(webpage, video_id, lang)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/arte.py", line 111, in _extract_from_webpage
    return self._extract_from_json_url(json_url, video_id, lang)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/arte.py", line 121, in _extract_from_json_url
    title = player_info['VTI'].strip()
KeyError: u'VTI'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 321, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'VTI',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by crazyiop** [comment]
when you go to http://cinema.arte.tv/de/artikel/polizeifilm-von-wim-wenders
with your browser, are you able to actualy see the vidéo on the website ??

2016-02-11 19:35 GMT+01:00 a.h. <notifications@github.com>:
