### ISSUE TITLE
Site Support Request: Funimation

### ISSUE THREAD

**Issue by Krak-ON** [rg3/youtube-dl#6614]
I was wondering if it was possible to add Funimation support.

The video info is stored in the source code.

The actual video URL:
<code>http://wpc.8c48.edgecastcdn.net/008C48/SV/480/[FUNIMATIONID]/[FUNIMATIONID]-480-[BITRATE]K.mp4[AUTHTOKEN]</code>

So for: http://www.funimation.com/shows/blood-blockade-battlefront/videos/official/secret-society-of-the-magic-sealed-city?watch=dub

A search for<code>FUNImationID</code> returns <code>"FUNImationID":"BLOENG0001"}</code>

The bitrates are only viewable in the source with a Funimation Subscription.
<pre><code>"sdUrl":"http:\/\/wpc.8c48.edgecastcdn.net\/008C48\/SV\/480\/BLOENG0001\/BLOENG0001-480-1500K.mp4"
"hdUrl":"http:\/\/wpc.8c48.edgecastcdn.net\/008C48\/SV\/480\/BLOENG0001\/BLOENG0001-480-2500K.mp4"
"hd1080Url":"http:\/\/wpc.8c48.edgecastcdn.net\/008C48\/SV\/480\/BLOENG0001\/BLOENG0001-480-4000K.mp4"</pre></code>
They only show three in the player, but they're seem to be more:<code>1000,1500,2000,2500,3500,4000</code>
<pre><code>1000=480p [1.13 Mbit/s]
1500=480p [1.64 Mbit/s]
2000=480p [2.14 Mbit/s]
2500=720p [2.64 Mbit/s]
3500=720p [3.64 Mbit/s]
4000=1080p [4.16 Mbit/s][BEST]
</code></pre>
<b><i>^^Although I'm not entirely sure how they handle 360p for older videos^^</b></i>

Then a search for <code>authToken</code> returns <code>"authToken":"?OfCIkqEfAeub4cSbxSXwgu-a4BwthcLD8HbsUFFOLsu6TeZ93nz-8AGMuLcgN6Ieo5tPi7uAuFNDonRJgCdx7iUPU0DPPZrbThGPovMXsK-rUQV5K5GOKp4uSBkPJ_9sXlJ1fkFqXosWBxH0x4f6"</code>

They're is actually two different authTokens in the source, but they both seem to do the same.

So finally you're left with <code>http://wpc.8c48.edgecastcdn.net/008C48/SV/480/BLOENG0001/BLOENG0001-480-4000K.mp4?OfCIkqEfAeub4cSbxSXwgu-a4BwthcLD8HbsUFFOLsu6TeZ93nz-8AGMuLcgN6Ieo5tPi7uAuFNDonRJgCdx7iUPU0DPPZrbThGPovMXsK-rUQV5K5GOKp4uSBkPJ_9sXlJ1fkFqXosWBxH0x4f6</code>

**Comment by dstftw** [comment]
It's for subscribers only.

**Comment by Krak-ON** [comment]
The only info really needed is <code>FUNImationID</code>, and <code>authToken</code>.
Then plug them into:
<pre><code>wpc.8c48.edgecastcdn.net/008C48/SV/480/[FUNImationID]/[FUNImationID]-480-2000K.mp4[authToken] - for 480p
wpc.8c48.edgecastcdn.net/008C48/SV/480/[FUNImationID]/[FUNImationID]-480-3500K.mp4[authToken] - for 720p
wpc.8c48.edgecastcdn.net/008C48/SV/480/[FUNImationID]/[FUNImationID]-480-4000K.mp4[authToken] - for 1080p</code></pre>
Both <code>FUNImationID</code>, and <code>authToken</code>, can be found in the HTML page source. 
With or without a Funimation subscription.
<code>FUNImationID</code> can return two matches: 
<pre><code>"FUNImationID":"XXXENG####" - English Dubbed
"FUNImationID":"XXXJPN####" - English Subbed</code></pre>

<code>XXX</code> = Show specific ID.
<code>####</code> = Episode Number. <code>0001-9999</code>

**Comment by Krak-ON** [comment]
My bad, heres a non-subscribers only video.
http://www.funimation.com/shows/a-certain-scientific-railgun/videos/official/electromaster?watch=dub

**Comment by Slyneth** [comment]
Any plans about this?

**Comment by Slyneth** [comment]
https://github.com/rg3/youtube-dl/issues/7742

**Comment by Slyneth** [comment]
Alright, things are moving along. The scripts logins, recognizes three formats, downloads the one you want.

I have this problems and I am stuck with my limited knowledge (I didn't know anything at all 3 days ago). So, I need direction =)

Firstly; even if everything works, it keeps giving me this: *WARNING: Extractor Funimation returned a compat_list result. It needs to be updated.* I have no idea what this is.

Secondly; it logins (I even got it to say that logining is mandatory) but when wrong login information is given it just errors out. I want it to give a message saying login information was wrong.

Thirdly; tests doesn't work. It needs to login but tests gives me this: *AttributeError: 'module' object has no attribute '--username'*

Lastly, I have no idea how to use git, how can I send this to you when it is done?

This is the script:
```
# coding: utf-8
from __future__ import unicode_literals
from .common import InfoExtractor
from ..utils import (
	sanitized_Request,
	ExtractorError,
	urlencode_postdata,
)

import re

class FunimationBaseIE(InfoExtractor):
    _NETRC_MACHINE = 'funimation'
    _LOGIN_REQUIRED = True

    def _login(self):
        (username, password) = self._get_login_info()
	if username is None:
            if self._LOGIN_REQUIRED:
                raise ExtractorError('No login info available, needed for using %s.' % self.IE_NAME, expected=True)
            return
        self.report_login()
        login_url = 'http://www.funimation.com/login'
        data = urlencode_postdata({
            'formname': 'loginForm2',
            'email_field': username,
            'password_field': password,
        })
        login_request = sanitized_Request(login_url, data)
        login_request.add_header('Content-Type', 'application/x-www-form-urlencoded')
        self._download_webpage(login_request, None, False, login_url)

    def _real_initialize(self):
        self._login()

class FunimationIE(FunimationBaseIE):
    _VALID_URL = r'(?P<address>https?://(?:www\.)?funimation\.com/shows/.*/videos/official/.+\=\w+)'
    _USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7'

    _TEST = {
        'url': 'http://www.funimation.com/shows/shomin-sample/videos/official/kagurazaka-sama-is-here?watch=sub',
        'md5': '1d2840927cc587901a7ae4062666a3aa',
        'info_dict': {
            'id': 'SMSJPNFnsWOM0009',
            'ext': 'mp4',
            'title': 'Shomin Sample - Kagurazaka-sama is Here',
        }
    }

    def _real_extract(self, url):
	mobj = re.match(self._VALID_URL, url)

	request = sanitized_Request(url)
	request.add_header('User-Agent', self._USER_AGENT)

	video_address = mobj.group('address')
	webpage = self._download_webpage(request, video_address)

	self.report_extraction(video_address)

	video_base = self._search_regex(r'"hdUrl":"(.+?)(?:-2500K.mp4)"', webpage, 'video_base')
	video_id  = self._search_regex(r'"FUNImationID":"(.+?)"', webpage, 'video_id')
	video_auth = self._search_regex(r'"authToken":"(.+?)"', webpage, 'video_auth')  

	video_base = video_base.replace('\\', '')

        formats = [{
            'format_id': 'low',
            'quality': 1,
	    'resolution': '480p',
            'url': video_base + '-1500K.mp4' + video_auth,
        }, {
            'format_id': 'high',
            'quality': 2,
            'resolution': '720p',
            'url': video_base + '-2500K.mp4' + video_auth,
        }, {
            'format_id': 'highest',
            'quality': 3, 
            'resolution': '1080p',
            'url': video_base + '-4000K.mp4' + video_auth,
	    }]
        self._sort_formats(formats)

        return [{
            'id':        video_id,
            'ext':       'mp4',
            'title':     self._og_search_title(webpage),
	    'formats':   formats
        }]
```
Thanks for all your help!

**Comment by yan12125** [comment]
@slyneth Could you open a pull request?

By the way, for a single video just return:
```
        return {
            'id':        video_id,
            'ext':       'mp4',
            'title':     self._og_search_title(webpage),
        'formats':   formats
        }
```
Also, identation in your codes looks wrong. Have you tested it with both Python 2.x and Python 3.x?

**Comment by Slyneth** [comment]
Yes, spaces and tabs are wrong all over, but I just discovers flake8, I will fix it tonight. And make the test with a free to watch video (that one is subs only).

I will make the pull request tonight, after fixing those.

Thanks.

**Comment by Slyneth** [comment]
Right now it works with Python 2 and 3. Only problem is the test, I can't get it to work with login. Should I push like this?

This is final, working code:
```
# coding: utf-8
from __future__ import unicode_literals
from .common import InfoExtractor
from ..utils import (sanitized_Request, ExtractorError, urlencode_postdata)

import re

class FunimationBaseIE(InfoExtractor):
    _LOGIN_REQUIRED = True

    def _login(self):
        (username, password) = self._get_login_info()
        if username is None:
                if self._LOGIN_REQUIRED:
                    raise ExtractorError('No login info available, needed for using %s.' % self.IE_NAME, expected=True)
                return
        self.report_login()
        login_url = 'http://www.funimation.com/login'
        data = urlencode_postdata({
            'formname': 'loginForm2',
            'email_field': username,
            'password_field': password,
        })
        login_request = sanitized_Request(login_url, data)
        login_request.add_header('Content-Type', 'application/x-www-form-urlencoded')
        self._download_webpage(login_request, login_url)

    def _real_initialize(self):
        self._login()

class FunimationIE(FunimationBaseIE):
    _VALID_URL = r'(?P<address>https?://(?:www\.)?funimation\.com/shows/.*/videos/official/.+)'
    _USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7'

    def _real_extract(self, url):
        mobj = re.match(self._VALID_URL, url)

        request = sanitized_Request(url)
        request.add_header('User-Agent', self._USER_AGENT)

        video_address = mobj.group('address')
        webpage = self._download_webpage(request, video_address)

        self.report_extraction(video_address)

        video_base = self._search_regex(r'"hdUrl":"(.+?)(?:-2500K.mp4)"', webpage, 'video_base')
        video_id = self._search_regex(r'"FUNImationID":"(.+?)"', webpage, 'video_id')
        video_auth = self._search_regex(r'"authToken":"(.+?)"', webpage, 'video_auth')

        video_base = video_base.replace('\\', '')

        formats = [{
            'format_id': 'lowest',
            'quality': 1,
            'resolution': '480p',
            'url': video_base + '-1000K.mp4' + video_auth,
        }, {
            'format_id': 'lower',
            'quality': 2,
            'resolution': '480p',
            'url': video_base + '-1500K.mp4' + video_auth,
        }, {
            'format_id': 'low',
            'quality': 3,
            'resolution': '480p',
            'url': video_base + '-2000K.mp4' + video_auth,
        }, {
            'format_id': 'medium',
            'quality': 4,
            'resolution': '720p',
            'url': video_base + '-2500K.mp4' + video_auth,
        }, {
            'format_id': 'high',
            'quality': 5,
            'resolution': '720p',
            'url': video_base + '-3500K.mp4' + video_auth,
        }, {
            'format_id': 'highest',
            'quality': 6,
            'resolution': '1080p',
            'url': video_base + '-4000K.mp4' + video_auth,
        }]
        self._sort_formats(formats)

        return {
            'id': video_id,
            'ext': 'mp4',
            'title': self._og_search_title(webpage),
            'formats': formats
        }
```

**Comment by yan12125** [comment]
For testing ```_login```, [fc2.py](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/fc2.py) can be a good example. Just specifying ```'username'``` and ```'password'``` in ```'params'```. Don't forget to remove the actual password add a ```'skip'``` line before commit.

For Hulu videos, it's OK to raise a ```ExtractorError``` with ```expected=True```. Note that Hulu.com support hasn't reach the first stesp yet. See #1629.

**Comment by dstftw** [comment]
Funimation is supported for quite some time already.
