### ISSUE TITLE
Request for option to allow skipping of failed downloads in a playlist

### ISSUE THREAD

**Issue by StephenCasella** [rg3/youtube-dl#6617]
Currently when I download a large playlist the downloader will abort as soon as it hits a video that cannot be downloaded (one that's been deleted, region blocked, etc). I don't see an option for skipping those, so I need to manually take the video ID from the output and add it to the download archive index in order to resume the download. It would be great to have a flag I could pass to allow those to be skipped. Adding them to the archive file as I am doing now would be acceptable to prevent them from being attempted to be downloaded each time that playlist is synced.

If the above is in alignment with your vision for the app, I can submit a pull request myself for this functionality.

**Comment by dstftw** [comment]
This option is `--ignore-errors`.

**Comment by StephenCasella** [comment]
Thanks! Sorry I missed that before posting.
