### ISSUE TITLE
py TypeError

### ISSUE THREAD

**Issue by vaux42** [rg3/youtube-dl#6622]
Just encountered this issue whilst trying to run a download on 'https://soundcloud.com/deejaytrademark/tracks'

It seems the new '/tracks/' folder on soundlcoud is running into some issues.

<img width="716" alt="screen shot 2015-08-20 at 3 12 31 pm" src="https://cloud.githubusercontent.com/assets/4882590/9376253/ef3e8e0e-474d-11e5-9b1e-54e7b35b86fa.png">

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by vaux42** [comment]
<img width="721" alt="screen shot 2015-08-21 at 5 21 15 pm" src="https://cloud.githubusercontent.com/assets/4882590/9403293/17a94f06-4829-11e5-8974-3aa9207fd068.png">

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
