### ISSUE TITLE
You have been Featured/Recommended in eMagazine

### ISSUE THREAD

**Issue by speedily** [rg3/youtube-dl#6624]
Hello Creators of YOUTUBE-DL, We liked your work so much that we shared and recommended it to be used in our eMagazine on Page 8 (titled: The Replacer In Your Shells) of Smart Indies 15 August 2015. You can read it on PC/MAC/SMARTPHONE/TABLETs in ZOOM FULL SCREEN. Link: https://www.facebook.com/smartindies.officialpage/posts/1013835621993802

**Comment by dstftw** [comment]
Offtopic.
