### ISSUE TITLE
Could not download youtube video

### ISSUE THREAD

**Issue by yihjie** [rg3/youtube-dl#6630]
yihjie@Aspire-3830TG:~/Videos$ youtube-dl --verbose https://www.youtube.com/watch?v=B84Hhh5NPgo
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=B84Hhh5NPgo']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.10 - Linux-4.1.6-040106-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[youtube] B84Hhh5NPgo: Downloading webpage
[youtube] B84Hhh5NPgo: Downloading video info webpage
[youtube] B84Hhh5NPgo: Extracting video information
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {13} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {278} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] B84Hhh5NPgo: Downloading DASH manifest
WARNING: [youtube] B84Hhh5NPgo: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r4---sn-ipoxu-u2xz.googlevideo.com/videoplayback?fexp=9407991%2C9408710%2C9409069%2C9410705%2C9412913%2C9415365%2C9415485%2C9416023%2C9416126%2C9416524%2C9416673%2C9417707%2C9417833%2C9417947%2C9418144%2C9418153%2C9418449%2C9419330%2C9419444&dur=281.193&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&ms=au&id=07ce07861e4d3e0a&pl=18&mv=m&mt=1440131280&key=yt5&ip=223.137.124.143&mn=sn-ipoxu-u2xz&mm=31&ratebypass=yes&sver=3&source=youtube&upn=RNd4ybsOmK8&ipbits=0&initcwndbps=1002500&lmt=1433311957672867&expire=1440152948&mime=video%2Fmp4&itag=18&signature=85025BA49F960ADD832CBD8871776FEFB2BF292B.6BCD333AC2DFBCE4D5C014B083A45479C269741A'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1585, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by yupi2** [comment]
See https://github.com/rg3/youtube-dl/issues/6630

**Comment by yan12125** [comment]
Thanks @yupi2. Closing.
