### ISSUE TITLE
youtube-dl throwing error 403 on certain videos

### ISSUE THREAD

**Issue by kenrestivo** [rg3/youtube-dl#6633]
youtube-dl, latest release ( 2015.08.16.1) is throwing 403 errors on certain videos, but not others. They otherwise play fine in browsers, but youtube-dl cannot handle them anymore. Problem started today.

**Comment by dylanaraps** [comment]
Also getting this issue today, tried updating to the newest version and it still persists. Happened with this url for me: https://www.youtube.com/watch\?v\=QcIy9NiNbmo

**Comment by yan12125** [comment]
Duplicate of #6451. Remove the cache with ```youtube-dl --rm-cache-dir``` and try again.
