### ISSUE TITLE
RTMPDump Exited With Code 1 - Crunchyroll

### ISSUE THREAD

**Issue by johnku1** [rg3/youtube-dl#6634]
john@johns-Ubuntu-PC:~$ youtube-dl -v http://www.crunchyroll.com/gintama/episode-136-its-your-house-you-build-it-516250
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.crunchyroll.com/gintama/episode-136-its-your-house-you-build-it-516250']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.10 - Linux-4.1.0-3-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, ffmpeg 2.7.2-1build1, ffprobe 2.7.2-1build1, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 516250: Downloading webpage
[Crunchyroll] 516250: Downloading media info
[Crunchyroll] 516250: Downloading media info for 360p
[Crunchyroll] 516250: Downloading media info for 480p
[Crunchyroll] 516250: Downloading media info for 720p
[Crunchyroll] 516250: Downloading media info for 720p
[Crunchyroll] 516250: Downloading media info for 1080p
[Crunchyroll] 516250: Downloading media info for 1080p
[debug] Invoking downloader on 'rtmpe://c2fs.fplive.net/c2?nvb=20150822025002&nva=20150822065102&token=04760b5d3e5c8f2cdff95'
[download] Destination: Gintama Season 1 (Eps 100-150) Episode 136 – It’s Your House, You Build It-516250.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://c2fs.fplive.net/c2?nvb=20150822025002&nva=20150822065102&token=04760b5d3e5c8f2cdff95' -o 'Gintama Season 1 (Eps 100-150) Episode 136 – It’s Your House, You Build It-516250.flv.part' --playpath mp4:s/ve949063/v2/video.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : c2fs.fplive.net
[rtmpdump] DEBUG: Parsed app     : c2?nvb=20150822025002&nva=20150822065102&token=04760b5d3e5c8f2cdff95
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : c2fs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:s/ve949063/v2/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://c2fs.fplive.net:1935/c2?nvb=20150822025002&nva=20150822065102&token=04760b5d3e5c8f2cdff95
[rtmpdump] DEBUG: app      : c2?nvb=20150822025002&nva=20150822065102&token=04760b5d3e5c8f2cdff95
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : c2fs.fplive.net
[rtmpdump] DEBUG: Parsed app     : c2?nvb=20150822025002&nva=20150822065102&token=04760b5d3e5c8f2cdff95
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : c2fs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:s/ve949063/v2/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://c2fs.fplive.net:1935/c2?nvb=20150822025002&nva=20150822065102&token=04760b5d3e5c8f2cdff95
[rtmpdump] DEBUG: app      : c2?nvb=20150822025002&nva=20150822065102&token=04760b5d3e5c8f2cdff95
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1653, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 712, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1323, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1585, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 530, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 492, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by yan12125** [comment]
It's fixed in a01da8bbf83dfd4f87e3fdd105b9f7c850e76cad and will be included in the next version. Please wait patiently or try the git version.
