### ISSUE TITLE
site-support-request: m.vlive.tv

### ISSUE THREAD

**Issue by taeyeon-ss** [rg3/youtube-dl#6636]
hope youtube-dl can support http://m.vlive.tv/ in the feature

**Comment by yan12125** [comment]
It's implemented in #6621, which is still under discussion.

Don't forget to [provide an example URL](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient) the next time.

**Comment by yan12125** [comment]
vlive support is merged. Feel free to open new issues if there are still problems.
