### ISSUE TITLE
prioritze opus over other codecs, especially or at least if, no video is requested

### ISSUE THREAD

**Issue by Farfie** [rg3/youtube-dl#6637]
I realize the final muxing is probably while you're careful about getting opus. You could start by grabbing it, if at similar bitrate, when no video is requested, or at the very least, when -x is passed.

**Comment by yan12125** [comment]
How about: ```-f bestaudio[ext=opus]/best[ext=opus]```?

**Comment by Farfie** [comment]
That's great, but youtube-dl like a lot of programs, strives to have the "best quality defaults" as it even says in the readme of course. I'm more arguing for fullness here, rather than reporting a problem.

However, in messing around with some conditional passes, I can't seem to get youtube-dl to grab anything with opus without specifically -f x where x is the format code. For example, I tried even what yan12125 stated above, but it did nothing. If I added a "best" failsafe, then it would give me vorbis, but, it wasn't until I put -f 251 that I could get the program to grab an opus file.

**Comment by yan12125** [comment]
Which URL are you testing?

**Comment by Farfie** [comment]
https://www.youtube.com/watch?v=ib_1ATfr8wM

**Comment by jaimeMF** [comment]
You have to use `acodec` instead of `ext`: `bestaudio[acodec=opus]` seems to work for me.

**Comment by Farfie** [comment]
Ah, now why didn't I think of that? Good call. I still think the other way not working is a problem, and the original intention of the "issue" stands, but I don't intend these to be super important or anything...

Still, that works for me, for brevity.
