### ISSUE TITLE
youtube API and watching video

### ISSUE THREAD

**Issue by sylware** [rg3/youtube-dl#6638]
Probably has been asked many times: does the "youtube API" provides the data in order to fetch and play a video file (from the popular channel for instance)?
I could not find anything about this, except a "iframe API" for a fat browser embeded player on google dev support.
Am I wrong or "video streaming" www sites are using the inherent complexity of "open source" fat browsers as a kind of DRM system?

**Comment by dstftw** [comment]
youtube-dl does not use any kind of YouTube API.
Closing as offtopic.
