### ISSUE TITLE
[req] when downloading a playlist, put videos in ./{playlist-name} directory

### ISSUE THREAD

**Issue by chovy** [rg3/youtube-dl#6641]
[req] when downloading a playlist, put videos in ./{playlist-name} directory

**Comment by dstftw** [comment]
Use [output template](https://github.com/rg3/youtube-dl#output-template).

**Comment by chovy** [comment]
Does this work with directories?

`youtube-dl $1 -o "%(playlist)/%(autonumber)s-%(title)s.%(ext)s"`

**Comment by dstftw** [comment]
Yes. You forgot `s` after `%(playlist)`.

**Comment by chovy** [comment]
awesome. thanks! Is there anyway to download a README.md file or metadata about a video and/or playlist?

**Comment by dstftw** [comment]
README.md of what? Playlist metadata are optional and may contain `id`, `title` and `description`. It can be saved as JSON with `--dump-single-json --flat-playlist`.

**Comment by chovy** [comment]
that worked.
