### ISSUE TITLE
Best video stuck on 720p

### ISSUE THREAD

**Issue by Poilaucul** [rg3/youtube-dl#6642]
Hello,

No matter how I try to select one of the best quality for this video https://www.youtube.com/watch?v=q6kIwfEGLO4 it always gives me 720p

<a href="http://imgur.com/h1j9eVK"><img src="http://i.imgur.com/h1j9eVK.png" title="source: imgur.com" /></a>

I tried
>youtube-dl --list-formats --format "bestvideo+bestaudio" -v https://www.youtube.com/watch?v=q6kIwfEGLO4

With the same results
I am trying to get 4k streaming with mpv working, which works if I do:
>mpv --ytdl-format="bestvideo+bestaudio" https://www.youtube.com/watch?v=q6kIwfEGLO4

My setup is Firefox + [mpv-youtube-dl-binding](https://github.com/antoniy/mpv-youtube-dl-binding) > youtube-dl version 2015.08.16.1 > mpv v2.0.0

**Comment by dstftw** [comment]
You can't get streaming 4K since it's not served as single file but separate DASH audio and video.

**Comment by Poilaucul** [comment]
How come streaming works (sound + video) with MPV?
>mpv --ytdl-format="bestvideo+bestaudio" https://www.youtube.com/watch?v=q6kIwfEGLO4

**Comment by dstftw** [comment]
Ask mpv, not youtube-dl.

**Comment by Poilaucul** [comment]
Correct me if I'm wrong but MPV uses youtube-dl for streaming and you said It can't work so the command from MPV shouldn't work either, no?

**Comment by dstftw** [comment]
I said that streaming (piping to player) cannot be achieved for separate audio and video streams on fly. I have no idea how mpv implements `--ytdl-format="bestvideo+bestaudio"`.

**Comment by dstftw** [comment]
As for the screenshot: `best` means best single file media. `bestvideo` is best DASH video, `bestaudio` is best DASH audio.
