### ISSUE TITLE
Misplaced information in JSON?

### ISSUE THREAD

**Issue by rsd** [rg3/youtube-dl#6646]
Hello,

Looking at the JSON generated for a playlist, I have noted some entries that seem to be out of place.
e.g.
On each entry there is:
    height, width, ext, abr, acodec, format, vcodec, ...
where they are usually inside the formats[] array.

Is this right?  
Is there a meaning form them to be outside of formats[]?
Or this is simple how youtbe deliver the data.

Thanks

**Comment by dstftw** [comment]
Provide concrete example URLs.

**Comment by rsd** [comment]
Oops

http://pastebin.com/PZcQujje

**Comment by jaimeMF** [comment]
When a formats is chosen for downloading, its info from the `formats` fields is copied to the root dictionary. This is the expected behaviour.
