### ISSUE TITLE
[suggestion] add `text` sub-field in `subtitles` field of JSON

### ISSUE THREAD

**Issue by fqj1994** [rg3/youtube-dl#6647]
Hello,

Some sites (kuwo, neteasemusic, qqmusic which youtube-dl supports) doesn't have a url to download subtitles/lyrics but the subtitles/lyrics's content is just part of the HTML page or a field of API response.

Those 3 extractors parsed the subtitles/lyrics of the 3 sites but put it into the `description` field as `subtitles` property only have `url` field rather than `text` field or similar things.

Adding a new sub-field `text` (which can be exclusive with `url` sub-field) allow extractors to put parsed subtitles directly into the data if subtitles content is located in a field of the API response rather than another URL.

If the owner believes it's OK, I'll do some development and file a PR to update those three extractors.

**Comment by dstftw** [comment]
This is [already implemented](https://github.com/rg3/youtube-dl/blob/2b6bda1ed86e1b64242b33c032286dc315d541ae/youtube_dl/extractor/common.py#L164). Provide concrete example URLs when subtitles are not extracted.
