### ISSUE TITLE
yandexmusic.playlist download bad work

### ISSUE THREAD

**Issue by Sality777** [rg3/youtube-dl#6650]
Latest bin youtube-dl.exe, Windows10
example url: https://music.yandex.ru/users/ya.playlist/playlists/1180
LOG: 
...
[yandexmusic:playlist] 11260907: Downloading track location JSON
[yandexmusic:playlist] 4654322: Downloading track location JSON
[yandexmusic:playlist] 4257200: Downloading track location JSON
[yandexmusic:playlist] 638471: Downloading track location JSON
[yandexmusic:playlist] 15815448: Downloading track location JSON
[download] Downloading playlist: Топ 100: Диско
[yandexmusic:playlist] playlist Топ 100: Диско: Collected 100 video ids (downloading 100 of them)
[download] Downloading video 1 of 100
[download] Destination: Sister Sledge - We Are Family-1149450.mp3
[download] 100% of 9.33MiB in 00:19
[download] Downloading video 2 of 100
[download] Destination: Grace Jones - Send In The Clowns-21727853.mp3
[download] 100% of 10.37MiB in 00:20
[download] Downloading video 3 of 100
[download] Destination: Sare Havlicek - Movies for Lovers-23208179.mp3
[download] 100% of 6.11MiB in 00:12
[download] Downloading video 4 of 100
ERROR: unable to download video data: HTTP Error 400: Bad Request

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version. Thanks for the report.
