### ISSUE TITLE
How do I download from JW Player?

### ISSUE THREAD

**Issue by Xyrexus** [rg3/youtube-dl#6654]
A lot of people I watch now use the generic 'JW Player', I'm unsure how to download from these, can youtube-dl do it? I don't know how to get the download link however either.

Example video : http://channelawesome.com/nostalgia-critic-planet-of-the-apes/ (The top one), how can I get the link for this video, and will I need anything additional to download it?

**Comment by StephenVNelson** [comment]
I'm confused. This looks like your run of the mill youtube video.
