### ISSUE TITLE
New problem with dr.dk

### ISSUE THREAD

**Issue by PalleSorensen** [rg3/youtube-dl#6663]
Hello!
I used youtube-dl for dr.dk a long time and it worked like a charm, but today i got this failmsg when requesting formats:
$ youtube-dl -F http://www.dr.dk/tv/se/doedsgangen/doedsgangen-henrettelsen-1-3/
[generic] : Requesting header
WARNING: Falling back on generic information extractor.
[generic] : Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>

**Comment by PalleSorensen** [comment]
Okay, I should provide some more information, it seems like dr uses ssl on their video site dr.dk/tv now which they did not use to. So the url I provided is edited.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by johankj** [comment]
It’s been months since support for https on dr.dk was added.
I just tried to download the above file, but it is no longer available.
Other content I tested seems to work fine.
