### ISSUE TITLE
Create a playlist locally before downloading or by simulating?

### ISSUE THREAD

**Issue by zorrohere** [rg3/youtube-dl#6664]
I was looking for a feature where we can simulate and create a playlist(.m3u) on disk or maybe empty files with filename based on output template so we can add files to playlist and watch them while it is downloading.

I tried writing playlist using simulate but I couldn't find indexes etc. Is there anyway to do it? Or Is this feature possible?

**Comment by jaimeMF** [comment]
You can run `youtube-dl LIST--get-filename > playlist.m3u` and if you run `youtube-dl LIST --no-part -f best` you should be able to play it. Is that enough?

**Comment by zorrohere** [comment]
I feel stupid now, had seen this option once but forgot about it. Thanks.

**Comment by chovy** [comment]
It would be nice if there was a flag to generate the file in the output directory using the filename options specified with -o
