### ISSUE TITLE
Error when attempting to download playlist w/ Win10 x64 youtube-dl 2015.08.23

### ISSUE THREAD

**Issue by daved31415** [rg3/youtube-dl#6674]
I am trying to download this playlist with Win10 x64, youtube-dl v 2015.08.23:
  https://www.youtube.com/watch?v=C-Naa1HXeDQ&list=PL795aDbK_A8F5VWD4otZOXutge7rEugKC

The first song downloads and then I receive the following error: 

  'list' is not recognized as an internal or external command, operable program or batch file 

I tried changing "list" to "playlist" in the URL but the same thing happens.  Any ideas why this happens/  Can anyone verify if the playlist can be downloaded with other OS or versions? 

I am trying to download the playlist by typing: youtube-dl https://www.youtube.com/watch?v=C-Naa1HXeDQ&list=PL795aDbK_A8F5VWD4otZOXutge7rEugKC

I am able to download the entire video list using ytuser: but it would be nice to download individual playlists.

**Comment by dstftw** [comment]
[How to use shell properly](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).

**Comment by daved31415** [comment]
Quotes around the URL.  I should have figured that out.  Thanks.
