### ISSUE TITLE
Unable to download from Crunchyroll (Windows)

### ISSUE THREAD

**Issue by Vladinator** [rg3/youtube-dl#6677]
C:\Users\scott\Videos>youtube-dl.exe http://www.crunchyroll.com/flesh-for-the-beast-tsukikos-curse/episode-1-the-conjugal-corpse-677727?t=0&p720=1
[Crunchyroll] 677727: Downloading webpage
ERROR: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'p720' is not recognized as an internal or external command, operable program or batch file.

C:\Users\scott\Videos>youtube-dl.exe -U
youtube-dl is up-to-date (2015.08.23)

**Comment by dstftw** [comment]
As of
```
This content may be inappropriate for some people.
To view this, please log in to verify you are 18 or older. 
```
pass login and password to youtube-dl with `-u` and `-p`.
