### ISSUE TITLE
TF1 broken again

### ISSUE THREAD

**Issue by Cigaes** [rg3/youtube-dl#6678]
The following URL on TF1 replay does not work:
http://www.tf1.fr/tf1/mentalist/videos/replay-mentalist-episode-1-saison-07-de-nuages-a-l-horizon.html

With the following quick-and-dirty patch:

```
diff --git a/youtube_dl/extractor/tf1.py b/youtube_dl/extractor/tf1.py
index 3a68eaa..35899dc 100644
--- a/youtube_dl/extractor/tf1.py
+++ b/youtube_dl/extractor/tf1.py
@@ -6,7 +6,7 @@ from .common import InfoExtractor
 
 class TF1IE(InfoExtractor):
     """TF1 uses the wat.tv player."""
-    _VALID_URL = r'http://(?:(?:videos|www|lci)\.tf1|www\.tfou)\.fr/.*?-(?P<id>\d+)(?:-\d+)?\.html'
+    _VALID_URL = r'http://(?:(?:videos|www|lci)\.tf1|www\.tfou)\.fr/.*?(?:-(?P<id>\d+)(?:-\d+)?)?\.html'
     _TESTS = [{
         'url': 'http://videos.tf1.fr/auto-moto/citroen-grand-c4-picasso-2013-presentation-officielle-8062060.html',
         'info_dict': {
diff --git a/youtube_dl/extractor/wat.py b/youtube_dl/extractor/wat.py
index affcc52..cf4003b 100644
--- a/youtube_dl/extractor/wat.py
+++ b/youtube_dl/extractor/wat.py
@@ -12,7 +12,7 @@ from ..utils import (
 
 
 class WatIE(InfoExtractor):
-    _VALID_URL = r'http://www\.wat\.tv/video/(?P<display_id>.*)-(?P<short_id>.*?)_.*?\.html'
+    _VALID_URL = r'http://(?:www\.wat\.tv|wat\.replay\.tf1\.fr)/video/(?P<display_id>.*)-(?P<short_id>.*?)_.*?\.html'
     IE_NAME = 'wat.tv'
     _TESTS = [
         {
```

… I can get further, but it stops with:

```
[TF1] None: Downloading webpage
[TF1] Downloading embed player page
[TF1] Downloading JSON metadata
[wat.tv] replay-mentalist-episode-saison: Downloading webpage
[wat.tv] 12724203: Downloading JSON metadata
[wat.tv] 12724203: Downloading server time
[wat.tv] 12724203: Downloading SD video URL
[wat.tv] 12724203: Downloading server time
[wat.tv] 12724203: Downloading HD video URL
[f4m] Downloading f4m manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

Regards,

-- 
  Nicolas George

**Comment by robertoestivill** [comment]
Same 403 error here

```
$ youtube-dl https://www.youtube.com/watch?v=344KGcW0HRY --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--no-part', u'-o', u'%(title)s.%(ext)s', u'--extract-audio', u'--audio-format', u'mp3', u'https://www.youtube.com/watch?v=344KGcW0HRY', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.23
[debug] Python version 2.7.6 - Darwin-14.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5, ffprobe 2.5
[debug] Proxy map: {}
[youtube] 344KGcW0HRY: Downloading webpage
[youtube] 344KGcW0HRY: Downloading video info webpage
[youtube] 344KGcW0HRY: Extracting video information
[youtube] {22} signature length 40.43, html5 player new
[youtube] {43} signature length 40.43, html5 player new
[youtube] {18} signature length 40.43, html5 player new
[youtube] {5} signature length 40.43, html5 player new
[youtube] {36} signature length 40.43, html5 player new
[youtube] {17} signature length 40.43, html5 player new
[youtube] {13} signature length 40.43, html5 player new
[youtube] {137} signature length 40.43, html5 player new
[youtube] {248} signature length 40.43, html5 player new
[youtube] {136} signature length 40.43, html5 player new
[youtube] {247} signature length 40.43, html5 player new
[youtube] {135} signature length 40.43, html5 player new
[youtube] {244} signature length 40.43, html5 player new
[youtube] {134} signature length 40.43, html5 player new
[youtube] {243} signature length 40.43, html5 player new
[youtube] {133} signature length 40.43, html5 player new
[youtube] {242} signature length 40.43, html5 player new
[youtube] {160} signature length 40.43, html5 player new
[youtube] {140} signature length 40.43, html5 player new
[youtube] {171} signature length 40.43, html5 player new
[youtube] 344KGcW0HRY: Downloading DASH manifest
WARNING: [youtube] 344KGcW0HRY: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r7---sn-j5cax8pnpvo-x1x6.googlevideo.com/videoplayback?id=o-AHH_6r58yjXJBFxQqCe-gy8tMEajP6H7WWNFKsq3-rvi&mn=sn-j5cax8pnpvo-x1x6&mm=31&pl=20&dur=201.316&lmt=1429868841850809&ip=181.169.135.117&ms=au&keepalive=yes&mv=m&source=youtube&expire=1440726660&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=YWaxTWyT5uQ&gcr=ar&mt=1440704998&key=yt5&gir=yes&fexp=9407478%2C9408710%2C9409069%2C9415365%2C9415485%2C9416023%2C9416126%2C9417707%2C9418153%2C9418448&ipbits=0&mime=audio%2Fmp4&initcwndbps=1382500&itag=140&requiressl=yes&clen=3232634&sver=3&signature=D95DBCB2631C09AF34D3E450599AA7DD350ABC63.83CCCBCCEA7DBB620E6C97C6DFAAC49071E30F44&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1585, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by jaimeMF** [comment]
@robertoestivill It's a different issue, see #6451: remove cache with `youtube-dl --rm-cache-dir`.

**Comment by robertoestivill** [comment]
@jaimeMF My bad, feel free to delete the comment to keep the issue report clean

**Comment by yan12125** [comment]
I got the following error in browsers:
```
Ce contenu n'est pas disponible dans votre zone géographique
```
Or, "This content is not available in your area" in English. 

Can you watch this video in browsers? Are you in France? I tried several France proxies with no luck.

**Comment by Cigaes** [comment]
I just tried again and now it gets a 404; I suppose the video stays online only a week.
The second episode has the same scheme: http://www.tf1.fr/tf1/mentalist/videos/replay-mentalist-episode-2-saison-07-verrous.html

For some reason, their player thinks flash is not installed, except it is; not worrying about how to get flash working is one of my reasons for using youtube-dl so much. But I am located in France, so I should be able to access this particular video.

**Comment by yan12125** [comment]
Try to make the video available in browsers. One of youtube-dl's principles is that a video will not be supported unless someone can play it on browsers/mobile phones/etc.

**Comment by OlivierJeannet** [comment]
I live in France (Paris) and I also have the problem, I can't download anymore from the replay TV of TF1. I had youtube-dl version 2015.08.28 and was getting 404 error.
Now I upgraded to youtube-dl version 2015.09.03 , and for example this recent aired episode (today, 6 septembre 2015 17:10) doesn't work : 

~/youtube-dl -F http://www.tf1.fr/tf1/experts-miami/videos/experts-miami-episode-16-saison-06-grand-nettoyage.html

[generic] experts-miami-episode-16-saison-06-grand-nettoyage: Requesting header
WARNING: Falling back on generic information extractor.
[generic] experts-miami-episode-16-saison-06-grand-nettoyage: Downloading webpage
[generic] experts-miami-episode-16-saison-06-grand-nettoyage: Extracting information
ERROR: Unsupported URL: http://www.tf1.fr/tf1/experts-miami/videos/experts-miami-episode-16-saison-06-grand-nettoyage.html

If this helps to find a solution.

Best regards to the developpers of this wonderful tool.

**Comment by yan12125** [comment]
This video is geo-restricted, too :(

**Comment by campones** [comment]
but not in France obviously

**Comment by remitamine** [comment]
the f4m manifests are protected with Akamai Player Verification Token(the f4m fragment urls contain the pvtoken param).
taking http://www.tf1.fr/tf1/person-of-interest/videos/person-of-interest-episode-1-saison-04-une-vie-normale.html as an example.
the json data contain url to custom domain that use the same wat.tv layout(http://wat.replay.tf1.fr/video/person-of-interest-episode-7pjca_5n7c5_.html).
this is a url to fragment url that contain the pvtoken.
http://tf1vodhdscatchup-vh.akamaihd.net/z/H264-384x288/87/78/12948778.h264/0_6b2ff5ecca11e4fd_Seg1-Frag1?pvtoken=exp%3D9999999999%7Eacl%3D%252f%252a%7Edata%3DZXhwPTE0NTIzNzg0Njl+YWNsPSUyZip+ZGF0YT1wdmMsc35obWFjPWNlOTc0ZTA1NDU4ODM1ZWViMTY2YzgxY2NjZGFiZTJkOWFkYzg0MDJhYWY5YTQxZDliODRiNmJkODk2NDgwODE%3D%2147DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU%3D%7Ehmac%3DD96685FB26D558EF70B02478B1692442E6EDF6B7FE3C5194623CA3E6200E002D&hdntl=exp=1452378469~acl=%2f*~data=hdntl~hmac=4495126106eaa805be596bd51657fb469a6be89f74827ddd18ee87ab3e826ef8&bu=WAT&login=person-of-interest-tf1&i=178.32.69.217&u=d08e7f23d9526739cfca991332817762&sum=a980e017dfd196cff0e2e9312db1548d&start=0&als=0,2,0,0,0,NaN,0,0,0,26,f,0,2501.16,f,s,MFXTMUIVCRMN,2.11.3,26&hdcore=2.11.3

**Comment by Animis09** [comment]
TF1 seems to be broken again: 

root:~# youtube-dl -F http://www.tf1.fr/tf1/the-voice/videos/amandine-rend-dingue-mika-choisissant-florent-pagny.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'http://www.tf1.fr/tf1/the-voice/videos/amandine-rend-dingue-mika-choisissant-florent-pagny.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.30.2
[debug] Proxy map: {}
[TF1] amandine-rend-dingue-mika-choisissant-florent-pagny: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 421, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 411, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1736, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tf1.py", line 52, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 653, in _html_search_regex
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 623, in _search_regex
  File "/usr/lib/python2.7/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat

**Comment by yan12125** [comment]
@Animis09 Please open a new issue for that.

**Comment by yan12125** [comment]
@remitamine Since c5f51551006c9d9ad7263cb3d3d90d1c91c8c648 both m3u8 and f4m formats are extracted, while all links except the last one give 404. Is the issue resolved?

**Comment by remitamine** [comment]
> Is the issue resolved?

it should be.

**Comment by yan12125** [comment]
Thanks.
