### ISSUE TITLE
HTTP Error 429

### ISSUE THREAD

**Issue by AshleyDodd** [rg3/youtube-dl#6684]
When i try to download a video using Sinusbot, it says "Unable to download webpage: HTTP Error 429: Too Many Requests (cause by HTTPError())" and to report it here. I am using by OVH VPS.

Sorry for the lack of information.

**Comment by dstftw** [comment]
This has been discussed a lot. You may want to read [FAQ entry on the issue](https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required) and [this discussion](https://github.com/rg3/youtube-dl/issues/5138).

**Comment by ivan** [comment]
YouTube is probably still blocking all of OVH's IPv6 ranges, try youtube-dl with `-4` to use IPv4 instead.
