### ISSUE TITLE
Unable to download videos from youtube.com

### ISSUE THREAD

**Issue by Metamba** [rg3/youtube-dl#6687]
It gives this error after trying to download youtube videos,
ERROR: unable to download video data: <urlopen error [Errno 60] Operation timed out>.

I have tried several youtube links with the same result.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by Metamba** [comment]
[youtube] VObwmJXUdCY: Downloading webpage
[youtube] VObwmJXUdCY: Downloading video info webpage
[youtube] VObwmJXUdCY: Extracting video information
[youtube] VObwmJXUdCY: Downloading DASH manifest
[youtube] VObwmJXUdCY: Downloading DASH manifest
^C
ERROR: Interrupted by user
Doyins-MacBook-Pro:Downloads DOYMAC$ youtube-dl -f 22  https://www.youtube.com/watch?v=VObwmJXUdCY --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'22', u'https://www.youtube.com/watch?v=VObwmJXUdCY', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.23
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] VObwmJXUdCY: Downloading webpage
[youtube] VObwmJXUdCY: Downloading video info webpage
[youtube] VObwmJXUdCY: Extracting video information
[youtube] VObwmJXUdCY: Downloading DASH manifest
[youtube] VObwmJXUdCY: Downloading DASH manifest
[debug] Invoking downloader on u'https://r3---sn-h5povox-avne.googlevideo.com/videoplayback?signature=3D60CEAA39D88FAC0F7D58706514387C4B2FD436.3D7C84F5796403FB040B7379B29BC8FDDF7E608B&upn=iV8zI9vRGZM&dur=107.903&id=o-AIoU4Wb8BR-I191mAwjHSThwKbVw7tprzZjWBwYgB_1c&itag=22&pl=23&mt=1440619923&ratebypass=yes&requiressl=yes&ms=au&mn=sn-h5povox-avne&source=youtube&mm=31&sparams=dur%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=video%2Fmp4&key=yt5&lmt=1421799811429032&sver=3&fexp=9408710%2C9409069%2C9410705%2C9415365%2C9415485%2C9415555%2C9416023%2C9416074%2C9416126%2C9416347%2C9416729%2C9417204%2C9417707%2C9418153%2C9418448%2C9418477%2C9419167%2C9420020&ip=154.118.0.182&expire=1440641831&mv=u&ipbits=0'
ERROR: unable to download video data: <urlopen error [Errno 60] Operation timed out>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1585, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 749, in https_open
    req, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 60] Operation timed out>

**Comment by bennisen** [comment]
i think i have the same Problem. 
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by dstftw** [comment]
@bennisen no it's different, remove cache with `youtube-dl --rm-cache-dir`.

**Comment by bennisen** [comment]
thx works for me

**Comment by darshanime** [comment]
I have the same issue inspite of using the latest version : 

```
$ youtube-dl --verbose https://www.youtube.com/playlist?list=PLwxNMb28XmpckOvZZ_AZjD7WM2p9-6NBv
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/playlist?list=PLwxNMb28XmpckOvZZ_AZjD7WM2p9-6NBv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.23
[debug] Python version 2.7.10 - Linux-3.13.0-62-generic-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[youtube:playlist] PLwxNMb28XmpckOvZZ_AZjD7WM2p9-6NBv: Downloading webpage
[download] Downloading playlist: SELF
[youtube:playlist] playlist SELF: Downloading 38 videos
[download] Downloading video 1 of 38
[youtube] PaZ1EmPOE_k: Downloading webpage
[youtube] PaZ1EmPOE_k: Downloading video info webpage
[youtube] PaZ1EmPOE_k: Extracting video information
[youtube] PaZ1EmPOE_k: Downloading DASH manifest
WARNING: [youtube] PaZ1EmPOE_k: Skipping DASH manifest: ExtractorError(u"Could not download DASH manifest: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(error(104, 'Connection reset by peer'),))",)
[youtube] PaZ1EmPOE_k: Downloading DASH manifest
WARNING: [youtube] PaZ1EmPOE_k: Skipping DASH manifest: ExtractorError(u"Could not download DASH manifest: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(error(104, 'Connection reset by peer'),))",)
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Invoking downloader on u'https://r3---sn-huoa-cvhl.googlevideo.com/videoplayback?requiressl=yes&mv=m&mt=1440670655&ms=au&mn=sn-huoa-cvhl&mm=31&ratebypass=yes&fexp=9407881%2C9408093%2C9408710%2C9409069%2C9409171%2C9409208%2C9409248%2C9415365%2C9415485%2C9415951%2C9416023%2C9416126%2C9416485%2C9417190%2C9417204%2C9417707%2C9418153%2C9418203%2C9418448%2C9419244%2C9419984%2C9420020&pl=17&itag=22&mime=video%2Fmp4&signature=85DFA0526B88F27C7173C51298B7420235BE3B82.B1CCFF3B5D37566ADE4BA50044E239A947A2C026&upn=FpVpXlmt5-k&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ipbits=0&id=o-ADAzB9I9TuLPvAcF6-F3FO9xrwJpYm8AwKgy5FxyfU9m&initcwndbps=146250&source=youtube&lmt=1440590139716392&key=yt5&ip=182.57.90.234&expire=1440692386&dur=181.371&sver=3'
[download] On Feeling Melancholy-PaZ1EmPOE_k.mp4 has already been downloaded
[download] 100% of 44.15MiB
[download] Downloading video 2 of 38
[youtube] ghyamhuKpd8: Downloading webpage
[youtube] ghyamhuKpd8: Downloading video info webpage
ERROR: unable to download video info webpage: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(error(104, 'Connection reset by peer'),))
  File "/home/radar/anaconda/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/radar/anaconda/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/home/radar/anaconda/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/home/radar/anaconda/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/home/radar/anaconda/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/radar/anaconda/lib/python2.7/site-packages/youtube_dl/utils.py", line 749, in https_open
    req, **kwargs)
  File "/home/radar/anaconda/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
```

**Comment by Metamba** [comment]
This issue arose due to blocking of some addresses by my ISP and is not due to the program.  





On Wed, Aug 26, 2015 at 1:34 PM -0700, "bennisen" <notifications@github.com> wrote:












thx works for me

**Comment by jaimeMF** [comment]
I'm closing the issue then.

@darshanime that's probably a problem with your network connection.

**Comment by darshanime** [comment]
Erm, I am sure it is not because I can view the videos in my browser.
