### ISSUE TITLE
issue with the re with the cached name new in .js

### ISSUE THREAD

**Issue by CecoMastera** [rg3/youtube-dl#6691]
Hello,

Here is ex URL:
https://s.ytimg.com/yts/jsbin/html5player-new-bg_BG-vflEnZ74n/html5player-new.js

youtube.py - line 662:

    def _extract_signature_function(self, video_id, player_url, example_sig):
        id_m = re.match(
            r'.*?-(?P<id>[a-zA-Z0-9_-]+)(?:/watch_as3|/html5player)?\.(?P<ext>[a-z]+)$',
            player_url)
        if not id_m:
            raise ExtractorError('Cannot identify player %r' % player_url)
        player_type = id_m.group('ext')
        player_id = id_m.group('id')

player_id is always 'new"

Could you please fix it.

Regards,
Tsvetozar Tsolov

**Comment by yan12125** [comment]
It's fixed in 4bc8eec4ebf5ffcca3b2e17c864be08df5215f44. Thanks for the suggestion.
