### ISSUE TITLE
this channell blocked my ip ?

### ISSUE THREAD

**Issue by badpenguin** [rg3/youtube-dl#6692]
I cannot download video from this channell.
If i open the video with the browser from any computer in my LAN i got the message "video not available", while other friends can see it.
I've problems with only this channell, i successfully downloaded other videos from youtube yesterday.
Did the channell blocked my home's IP?

youtube-dl -r 400k --continue --verbose "https://www.youtube.com/playlist?list=PL8jk9jEnr_727RjRlBFIvywiMX-6deT5W"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-r', u'400k', u'--continue', u'--verbose', u'https://www.youtube.com/playlist?list=PL8jk9jEnr_727RjRlBFIvywiMX-6deT5W']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.9 - Linux-4.1.0-1-amd64-x86_64-with-debian-8.1
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2
[debug] Proxy map: {}
[youtube:playlist] PL8jk9jEnr_727RjRlBFIvywiMX-6deT5W: Downloading webpage
[download] Downloading playlist: Serie in simulcast - Ushio e Tora [Sub Ita]
[youtube:playlist] playlist Serie in simulcast - Ushio e Tora [Sub Ita]: Downloading 8 videos
[download] Downloading video 1 of 8
[youtube] uSfOY757jTU: Downloading webpage
[youtube] uSfOY757jTU: Downloading video info webpage
ERROR: uSfOY757jTU: YouTube said: This video is not available.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1078, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: uSfOY757jTU: YouTube said: This video is not available.

**Comment by jaimeMF** [comment]
I also get the same message, I guess it's georestricted. If you can't play it in your browser, there's nothing that youtube-dl can do.

**Comment by yan12125** [comment]
FYI: This video is only available in IT (Italy), SM (San Marino) and VA (Vatican City State.)

**Comment by badpenguin** [comment]
Yes, i'm in Italy!

Thanks. I figured out that my ISP gaved me a new IP that's not in Italy O.o

I wonder why my packets have to go thru' USA and then go back to Italy....
