### ISSUE TITLE
Request: TheCinemaSnob.com extractor for ScreenwaveMedia embeds

### ISSUE THREAD

**Issue by ssokolow** [rg3/youtube-dl#6695]
Given that there's an extractor for Cinemassacre (precedent) and that TheCinemaSnob.com appears to have switched to Screenwave Media embeds in response to YouTube ["holding the Elm Street 2: Freddy's Revenge episode hostage"](https://www.youtube.com/watch?v=Ui84pB-w154&t=1395), it'd probably be a good idea to add a TheCinemaSnob.com extractor to remove the need for users to poke around in the page source to find the specific ScreenwaveMedia URL that youtube-dl knows how to handle.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by ssokolow** [comment]
Whoops. Sorry about that. I wrote an example but, for some reason (can't remember), I used the mouse rather than `Ctrl+A Ctrl+C` to copy-paste into the browser (I don't trust my browser to keep longer posts safe.) and missed half of it without noticing.

I've already closed the copy of notepad I was using but the remaining half looked something like this:

> For example, if I load this URL, it uses Screenwave Media's self-hosted player embed and Screenwave provides no YouTube-like "view this directly on our site" link:
>
> http://www.thecinemasnob.com/the-cinema-snob/a-nightmare-on-elm-street-2-freddys-revenge1
>
> As such, I have to dig through the HTML until I find this URL and then feed that into youtube-dl:
>
> http://player2.screenwavemedia.com/player.php?id=cinemasnob-55d26273809dd

**Comment by dstftw** [comment]
Will be fixed in the next version.
