### ISSUE TITLE
Add option to print JSON escaped from simple quotes

### ISSUE THREAD

**Issue by heniotierra** [rg3/youtube-dl#6700]
Currently, if you want to use the JSON generated by -J option programatically, you're pretty fucked, because if there's a single quote (') in any part of the JSON, that won't allow you to parse the string.
Maybe make the -J option print the JSON with escaped single quotes by default?

**Comment by dstftw** [comment]
Post an example URL that produces the invalid JSON.

**Comment by heniotierra** [comment]
Actually the JSON is valid, but when I try to parse it in my code, it fails because of unescaped single quotes.

Here's  lil snippet from the code:

´´´
            ytcmd = self._YTLAUNCH_CMD % (yt_media_type, mediafile)
            print "      Youtube URL: " + mediafile
            print "      Youtube cmd: " + ytcmd
            self.ytprocess = pexpect.spawn(ytcmd)
            self.ytprocess.logfile = sys.stdout
            ytmediafound = self.ytprocess.expect([self._YT_REXP,
                                                     pexpect.TIMEOUT,
                                                     pexpect.EOF])
            if ytmediafound == 0:
                ytmediafile = self.ytprocess.match.group(1)
                print "      Youtube video URL: " + ytmediafile
´´´

**Comment by dstftw** [comment]
There is no problem then. Just parse it correctly with `json.loads()`.

**Comment by heniotierra** [comment]
Oh, but I do that. I'm sorry, I copied the wrong part of the code.
```
ytplst = json.loads(self.ytprocess.match.group(1))              # <- it fails here!
		plst_index = tboplayer.playlist.selected_track_index()
                tboplayer.track_titles_display.delete(plst_index,plst_index)
                tboplayer.playlist.remove(plst_index)
                tboplayer.blank_selected_track()
```
Also, I think it's not possible to escape the thing from inside my code. That must be done during file generation.

**Comment by dstftw** [comment]
`ValueError: Unterminated string starting at ...` has nothing to do with unescaped quotes. Most likely you are trying to load incomplete json that is returned by `self.ytprocess.match.group(1)`.

**Comment by heniotierra** [comment]
Hum... I thought of that possibility, but I don't understand why that would happen.
To make sure it was a problemm with unescaped characters, I copied the generated JSON and parsed it with in the javascript console. Agina, it's valid JSON, but in javascript it returnes a syntax error.
Javascript console says ```Uncaught SyntaxError: missing ) after argument list``` for the code below:
```var jota = JSON.parse(' <here camoes valid generated json> ')```

Now, it works for
```var jota = <here comes valid generated json>```

However, there's no way to use the json in my code without parsing it... Do you see the problem here? In the first case, if the single quotes are escaped, it will work.

**Comment by heniotierra** [comment]
Ok, I managed to fix this. Now it works! :)
I'll send a pull request soon.

**Comment by dstftw** [comment]
There is no need in PR since there is no problem.

**Comment by heniotierra** [comment]
Hum... It seems to me like you didn't understand what the problem here was.
The pull request is a one line changer which makes the whole thing I'm working on to work.
I don't why you're resisting this. I'm sorry, but I doubt you yourself are able to used the generated JSON in some other program of your if it comes with ' in some string.
I'll send the PR anyway, just so that you can close it. ;) I'm kidding, I mean no offense. But still, don't understand you resistence. Did you even try to use the generated JSON for something useful?

**Comment by dstftw** [comment]
Post full code you are using to parse it.

**Comment by heniotierra** [comment]
Ok... whis is part of code. Not the full doce, cos that's 1339 loc.

```
            ytcmd = self._YTLAUNCH_PLST_CMD % (mediafile)
            print "      Youtube URL: " + mediafile
            print "      Youtube cmd: " + ytcmd
            self.ytprocess = pexpect.spawn(ytcmd,timeout=90,maxread=17000,searchwindowsize=17000)
            #self.ytprocess.logfile = sys.stdout
            ytplstfound = self.ytprocess.expect([self._YT_REXP,
                                                     pexpect.TIMEOUT,
                                                     pexpect.EOF])
            if ytplstfound == 0:
                ytplst = json.loads(self.ytprocess.match.group(1))
           		plst_index = tboplayer.playlist.selected_track_index()
                tboplayer.track_titles_display.delete(plst_index,plst_index)
                tboplayer.playlist.remove(plst_index)
                tboplayer.blank_selected_track()
```

**Comment by dstftw** [comment]
The **full** code. How do I supposed to guess what `self._YT_REXP` equals to?
