### ISSUE TITLE
[req] e-learning -- skillfeed.com

### ISSUE THREAD

**Issue by chovy** [rg3/youtube-dl#6705]
Course page: https://www.skillfeed.com/courses/432-javascript-for-beginners
Video page: https://www.skillfeed.com/courses/432-javascript-for-beginners?video_id=3089-where-to-put-javascript

**Comment by TRox1972** [comment]
I'm unable to load the provided URLs. Also, http://skillfeed.com now redirects to http://www.bigstockphoto.com.

**Comment by chovy** [comment]
looks like its dead.
