### ISSUE TITLE
Disable VP9?

### ISSUE THREAD

**Issue by bugreport1** [rg3/youtube-dl#6709]
Could we have a **--prefer-non-free-formats** or **--no-vp9** option?
Something changed this last week, and now everything is downloading in the VP9 format instead of AVC1.
 
AVC1 uses the hardware decoder on my GPU, VP9 kills my CPU and I can't watch the videos.
I'd prefer not to be manually selecting formats for every video that I download.

**Comment by dstftw** [comment]
Use `-f 'bestvideo[ext!=webm]+bestaudio[ext!=webm]/best[ext!=webm]'`.

**Comment by bugreport1** [comment]
Thank you.
