### ISSUE TITLE
Updating problem?

### ISSUE THREAD

**Issue by Krassegrand** [rg3/youtube-dl#6718]
When I try to update I get this.

jorgen@jorgen-EasyNote-TE11HC:~$ youtube-dl -U
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
jorgen@jorgen-EasyNote-TE11HC:~$ 

I installed with this command
sudo apt-get install youtube-dl

Hoping for a solution!
Jörgen

**Comment by dstftw** [comment]
Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by Krassegrand** [comment]
Thank You!
