### ISSUE TITLE
ContentTooShortError

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#6732]
URL: https://www.youtube.com/watch?v=hqpp48q2MrA&feature=youtu.be

PLS NOTE: This only seems to happen when I use the "-f best" argument.  

youtube-dl.py -v -f best "https://www.youtube.com/watch?v=hqpp48q2MrA&feature=youtu.be"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'best', u'https://www.youtube.com/watch?v=hqpp48q2MrA&feature=youtu.be']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.08.28
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] hqpp48q2MrA: Downloading webpage
[youtube] hqpp48q2MrA: Downloading video info webpage
[youtube] hqpp48q2MrA: Extracting video information
[youtube] hqpp48q2MrA: Downloading DASH manifest
[youtube] hqpp48q2MrA: Downloading DASH manifest
[debug] Invoking downloader on u'https://r2---sn-cxaaj5o5q5-tt1k.googlevideo.com/videoplayback?expire=1441162324&ipbits=0&initcwndbps=12132500&itag=22&key=yt5&lmt=1417283040337773&dur=323.337&fexp=940
5633%2C9407117%2C9407991%2C9408710%2C9409069%2C9412774%2C9413122%2C9414603%2C9415365%2C9415485%2C9416023%2C9416103%2C9416126%2C9416985%2C9417430%2C9417707%2C9417815%2C9418153%2C9418356%2C9418448%2C941
9343%2C9420019&ip=199.85.73.12&pcm2cms=yes&id=o-AI1zTKqJZOTYVqT0dBpJsQsaiRzoOKEgMTYycr59OSmw&sver=3&ratebypass=yes&mn=sn-cxaaj5o5q5-tt1k&mm=31&upn=1JZndD8UwFA&mv=m&pl=24&mt=1441140600&ms=au&sparams=du
r%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&signature=C1F0D18173A2835380CD4AFCD4F09F50D8A6B1F9.466A8C095
CCF27EBEC6BC1C742B164F263E81B8B&source=youtube&mime=video%2Fmp4&requiressl=yes'
[download] Destination: Democratic Advancement Party of Canada (DAPC) About Video-hqpp48q2MrA.mp4
[download]   8.8% of 113.94MiB at  6.25MiB/s ETA 00:16 ERROR: content too short (expected 119469986 bytes and served 10486416)
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1585, in process_info
    success = dl(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\http.py", line 238, in real_download
    raise ContentTooShortError(byte_counter, int(data_len))
ContentTooShortError

Thanks
Ringo

**Comment by yan12125** [comment]
Looks like a network issue. Could you try again?

**Comment by RingoTheDog** [comment]
Yes, does seem to be working now....
thanks...
