### ISSUE TITLE
downloading error

### ISSUE THREAD

**Issue by Ngobito** [rg3/youtube-dl#6740]
mami@Diana-Studio-1737:~$ youtube-dl"https://www.youtube.com/watch?v=ku9vQostGys&list=PL0jLA2DJvZDaXHIvEt5SzNde0Bi8u0j4o"
bash: youtube-dlhttps://www.youtube.com/watch?v=ku9vQostGys&list=PL0jLA2DJvZDaXHIvEt5SzNde0Bi8u0j4o: No such file or directory
mami@Diana-Studio-1737:~$ youtube-dl "https://www.youtube.com/watch?v=ku9vQostGys&list=PL0jLA2DJvZDaXHIvEt5SzNde0Bi8u0j4o"
[youtube:playlist] Downloading playlist PLPL0jLA2DJvZDaXHIvEt5SzNde0Bi8u0j4o - add --no-playlist to just download video ku9vQostGys
[youtube:playlist] PL0jLA2DJvZDaXHIvEt5SzNde0Bi8u0j4o: Downloading page #1
WARNING: [youtube:playlist] PL0jLA2DJvZDaXHIvEt5SzNde0Bi8u0j4o: Playlist page is missing OpenGraph title, falling back ...
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update. 

mami@Diana-Studio-1737:~$ sudo apt-get install youtube-dl
[sudo] password for mami: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
youtube-dl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 342 not upgraded.
mami@Diana-Studio-1737:~$ youtube-dl
Usage: youtube-dl [options] url [url...]

**Comment by yan12125** [comment]
Please post the full verbose log with ```--verbose```. Note that the official version shipped with Debian/Ubuntu is usually out-of-dated. See [this FAQ entry](https://github.com/rg3/youtube-dl/#how-do-i-update-youtube-dl) for more information.
