### ISSUE TITLE
RegexNotFoundError: Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by rationalistquestioning** [rg3/youtube-dl#6741]
Hi ,

I am getting this error while i have latest update of youtube-dl.

sukanyar@sukanyar-K55VM:~$ sudo youtube-dl -U
youtube-dl is up-to-date (2015.08.28)
sukanyar@sukanyar-K55VM:~$ youtube-dl "https://www.youtube.com/watch?v=xdhY-uRL0Gw"
[youtube] Setting language
[youtube] xdhY-uRL0Gw: Downloading webpage
[youtube] xdhY-uRL0Gw: Downloading video info webpage
[youtube] xdhY-uRL0Gw: Extracting video information
[youtube] xdhY-uRL0Gw: Encrypted signatures detected.
[youtube] xdhY-uRL0Gw: Downloading js player new
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
sukanyar@sukanyar-K55VM:~$ youtube-dl --verbose "https://www.youtube.com/watch?v=xdhY-uRL0Gw"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=xdhY-uRL0Gw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.8 - Linux-3.16.0-44-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] Proxy map: {}
[youtube] Setting language
[youtube] xdhY-uRL0Gw: Downloading webpage
[youtube] xdhY-uRL0Gw: Downloading video info webpage
[youtube] xdhY-uRL0Gw: Extracting video information
[youtube] xdhY-uRL0Gw: Encrypted signatures detected.
[youtube] {22} signature length 44.40, html5 player new
[youtube] xdhY-uRL0Gw: Downloading js player new
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)

Please help me in finding a solution to this or fixing it.

Warm regards
Rationalist

**Comment by yan12125** [comment]
Look at this line in the verbose log
```
[debug] youtube-dl version 2014.08.05
```
Have you installed two or more versions of youtube-dl?

**Comment by rationalistquestioning** [comment]
hi Yen Chi Hsuan,

Thank you for your reply !

Looks like it is fixed in 2015.08.28

K55VM:~$ youtube-dl https://www.youtube.com/watch?v=TUrwH7dBaRI
[youtube] TUrwH7dBaRI: Downloading webpage
[youtube] TUrwH7dBaRI: Downloading video info webpage
[youtube] TUrwH7dBaRI: Extracting video information
[youtube] TUrwH7dBaRI: Downloading js player en_US-vfl90tmOk
[youtube] TUrwH7dBaRI: Downloading DASH manifest
[download] Destination: Cisco Live 2015 - Software Defined Networking (SDN)
Expert Joe Clarke-oIGrWuyof4o.f248.webm
[download]   1.9% of 51.11MiB at 141.12KiB/s ETA 06:03

No more errors..

Warm regards
Rationalist
