### ISSUE TITLE
how to download all the Soundcloud file for a user

### ISSUE THREAD

**Issue by windmaple** [rg3/youtube-dl#6743]
Say, https://soundcloud.com/akharris, has a bunch of file I want to grab. I tried 'youtube-dl https://soundcloud.com/akharris' and it doesn't work well. Also tried 'https://soundcloud.com/akharris/tracks', no luck either. I do see that soundcloud:tracks is a supported extractor. How do I use it? Thx

**Comment by dstftw** [comment]
*doesn't work well* and *no luck either* is not sufficient for a bug report. Read [bug reporting guidline](https://github.com/rg3/youtube-dl#bugs) carefully and open a new issue with proper info if you still can reproduce the problem.
