### ISSUE TITLE
YouTube JS player (?) issue

### ISSUE THREAD

**Issue by Aurosutru** [rg3/youtube-dl#6757]
Here is the output from trying to download a YouTube video, using the Linux Mint 17 latest version of youtube-dl.  Can't upgrade to the latest version on your website and will file an issue on that next.

tm@tm-K55A:~$ youtube-dl -f 18 https://www.youtube.com/watch?v=q0xEfdK-D1c --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', '18', 'https://www.youtube.com/watch?v=q0xEfdK-D1c', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-x86_64-with-LinuxMint-17-qiana
[debug] Proxy map: {}
[youtube] Setting language
[youtube] q0xEfdK-D1c: Downloading webpage
[youtube] q0xEfdK-D1c: Downloading video info webpage
[youtube] q0xEfdK-D1c: Extracting video information
[youtube] q0xEfdK-D1c: Encrypted signatures detected.
[youtube] encrypted signature length 85 (44.40), itag 22, html5 player new-en_US-vflCeB3p5\/html5player-new
[youtube] q0xEfdK-D1c: Downloading js player new
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 424, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 85 (44.40), itag 43, html5 player new-en_US-vflCeB3p5\/html5player-new
[youtube] q0xEfdK-D1c: Downloading js player new
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 424, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
