### ISSUE TITLE
downloading multi quality from same video

### ISSUE THREAD

**Issue by amayra** [rg3/youtube-dl#6761]
i have problem downloading multi quality from same video after i try everthing before i come here some time crash when i run mulit youtube-dl in same time or all stop downloading

**Comment by amayra** [comment]
my bat file just like :
youtube-dl.exe --id -w -f 249 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -w -f 250 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 251 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 160 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 242 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 243 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 133 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 134 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 244 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 247 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 135 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 248 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 136 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 137 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 271 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 264 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 13 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 17 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 36 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 5 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 43 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 18 https://www.youtube.com/watch?v=x1QTc5YeO6w
youtube-dl.exe --id -f 22 https://www.youtube.com/watch?v=x1QTc5YeO6w

**Comment by dstftw** [comment]
You don't need a batch file. Just pass comma separated list of format codes to `-f`, e.g. `youtube-dl.exe -f 249,250,... https://www.youtube.com/watch?v=x1QTc5YeO6w`. You may also want to use [output template](https://github.com/rg3/youtube-dl#output-template) with `%(format_id)s` to correctly process formats with the same extension.
