### ISSUE TITLE
Cannot download video -  Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by radoslaw** [rg3/youtube-dl#6767]
mac:vid cleverstep$ youtube-dl -t --verbose https://www.youtube.com/watch?v=ME7DunNmChk
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-t', '--verbose', 'https://www.youtube.com/watch?v=ME7DunNmChk']
[debug] Encodings: locale 'UTF-8', fs 'utf-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.08.2
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] Proxy map: {}
[youtube] Setting language
[youtube] ME7DunNmChk: Downloading webpage
[youtube] ME7DunNmChk: Downloading video info webpage
[youtube] ME7DunNmChk: Extracting video information
[youtube] ME7DunNmChk: Encrypted signatures detected.
[youtube] encrypted signature length 85 (44.40), itag 43, html5 player new-en_US-vflCeB3p5\/html5player-new
[youtube] ME7DunNmChk: Downloading js player new
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 956, in _decrypt_signature
    video_id, player_url, len(s)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 355, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 423, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 353, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 85 (44.40), itag 18, html5 player new-en_US-vflCeB3p5\/html5player-new
[youtube] ME7DunNmChk: Downloading js player new
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 956, in _decrypt_signature
    video_id, player_url, len(s)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 355, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 423, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 353, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

...

And loops forever

**Comment by yan12125** [comment]
```
[debug] youtube-dl version 2014.02.08.2
```
You are using a quite out-dated version. Read [this FAQ entry](https://github.com/rg3/youtube-dl/#how-do-i-update-youtube-dl) if you have any problem on updating.
