### ISSUE TITLE
No known format

### ISSUE THREAD

**Issue by go-nut** [rg3/youtube-dl#677]
I get no known format when trying to download "http://www.youtube.com/watch?v=wMKRFxETlY0"
version 2013.02.02

> youtube-dl "http://www.youtube.com/watch?v=wMKRFxETlY0" -v
[debug] youtube-dl version 2013.02.02
[debug] Python version 3.3.0 - Linux-3.7.5-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[youtube] Setting language
[youtube] wMKRFxETlY0: Downloading video webpage
[youtube] wMKRFxETlY0: Downloading video info webpage
[youtube] wMKRFxETlY0: Extracting video information
ERROR: no known formats available for video
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib/python3.3/site-packages/youtube_dl/__init__.py", line 512, in main
    _real_main()
  File "/usr/lib/python3.3/site-packages/youtube_dl/__init__.py", line 496, in _real_main
    retcode = fd.download(all_urls)
  File "/usr/lib/python3.3/site-packages/youtube_dl/FileDownloader.py", line 505, in download
    videos = ie.extract(url)
  File "/usr/lib/python3.3/site-packages/youtube_dl/InfoExtractors.py", line 93, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.3/site-packages/youtube_dl/InfoExtractors.py", line 496, in _real_extract
    self._downloader.trouble(u'ERROR: no known formats available for video')
  File "/usr/lib/python3.3/site-packages/youtube_dl/FileDownloader.py", line 230, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by remitamine** [comment]
i test all the urls mentioned in this issue.
now, it doesn't give `no known formats available for video` error:
```
youtube-dl https://www.youtube.com/watch?v=1XSvsFgvWr0
[youtube] 1XSvsFgvWr0: Downloading webpage
[youtube] 1XSvsFgvWr0: Downloading video info webpage
[youtube] 1XSvsFgvWr0: Extracting video information
WARNING: video doesn't have subtitles
ERROR: rtmpe downloads are not supported, see https://github.com/rg3/youtube-dl/issues/343 for more information.
```
```
youtube-dl -F https://www.youtube.com/watch?v=zx2g9QlsNdc
[youtube] zx2g9QlsNdc: Downloading webpage
[youtube] zx2g9QlsNdc: Downloading embed webpage
[youtube] zx2g9QlsNdc: Refetching age-gated info webpage
ERROR: zx2g9QlsNdc: YouTube said: Please sign in to view this video.
```
```
youtube-dl https://www.youtube.com/watch?v=wMKRFxETlY0
[youtube] wMKRFxETlY0: Downloading webpage
[youtube] wMKRFxETlY0: Downloading video info webpage
[youtube] wMKRFxETlY0: Extracting video information
ERROR: rtmpe downloads are not supported, see https://github.com/rg3/youtube-dl/issues/343 for more information.
```
