### ISSUE TITLE
probleme downloading pluzz

### ISSUE THREAD

**Issue by audrey2207** [rg3/youtube-dl#6770]
hello,
I got this problem, can you help me please:

youtube-dl http://pluzz.francetv.fr/videos/les_petits_meurtres_d_a_christie_,127336764.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://pluzz.francetv.fr/videos/les_petits_meurtres_d_a_christie_,127336764.html', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-62-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[pluzz.francetv.fr] les_petits_meurtres_d_a_christie_,127336764: Downloading webpage
[pluzz.francetv.fr] 127336764: Downloading XML config
ERROR: Unable to download XML: HTTP Error 400: Bad Request; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 191, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1157, in urlopen
    return self._opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

thanks a lot in advance

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by audrey2207** [comment]
thanks a lot,
