### ISSUE TITLE
Running youtube-dl via proxychains with python command?

### ISSUE THREAD

**Issue by interneteur** [rg3/youtube-dl#6775]
I was wondering if I had to use sub process when trying to run youtube-dl through proxychains?

or can you do something along the lines of 

```
ydl_opts = {
   'proxychain' : True,
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192',
    }],
    'logger': MyLogger(),
    'progress_hooks': [my_hook],
}
```

**Comment by jaimeMF** [comment]
You can run the script with proxychains: `proxychains python /path/to/your/script.py`. I don't know if there's any way to use proxychains only in some part of the script.
