### ISSUE TITLE
issue in downloading video on ubuntu 14

### ISSUE THREAD

**Issue by KishoreMeesala** [rg3/youtube-dl#6777]
File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name;

I got this issue when I was trying to download using the following command

youtube-dl @video link

**Comment by yan12125** [comment]
You need the latest version of youtube-dl. However, ubuntu often provides out-dated ones. Read [this FAQ entry](https://github.com/rg3/youtube-dl/#how-do-i-update-youtube-dl) for more information.
