### ISSUE TITLE
NBC URLs download unstiched fragments

### ISSUE THREAD

**Issue by bonacker** [rg3/youtube-dl#6780]
I appreciate the recent addition of the MSNBC extractor that I requested a few weeks ago. The MSNBC.com URLS are working properly. Thanks! 

Sometimes (I don't know why some work and others don't) NBC.com extractors do not stich the fragments together and instead put all of the individual fragments on the hard drive. 

Here's what occurs with http://www.nbc.com/meet-the-press/video/meet-the-press-august-30-2015/2894316?onid=210121#vc210121=1

I have tried different formats. They all give the same result. First, I have pasted the output from the list format option. Then, I have pasted the verbose output that occurs when the fragments download individually.

----------------------------------  LIST FORMATS------------------
[NBC] 2894316: Downloading webpage
[ThePlatform] 8YsFR2OqQC0u: Downloading config
[ThePlatform] 8YsFR2OqQC0u: Downloading SMIL data
[ThePlatform] 8YsFR2OqQC0u: Downloading f4m manif
[ThePlatform] 8YsFR2OqQC0u: Downloading f4m manif
[ThePlatform] 8YsFR2OqQC0u: Downloading f4m manif
[ThePlatform] 8YsFR2OqQC0u: Downloading f4m manif
[ThePlatform] 8YsFR2OqQC0u: Downloading f4m manif
[ThePlatform] 8YsFR2OqQC0u: Downloading f4m manif
[ThePlatform] 8YsFR2OqQC0u: Downloading JSON meta
[info] Available formats for 8YsFR2OqQC0u:
format code  extension  resolution note
hds-145-0    flv        unknown     145k
hds-145-1    flv        unknown     145k
hds-145-2    flv        unknown     145k
hds-145-3    flv        unknown     145k
hds-145-4    flv        unknown     145k
hds-145-5    flv        unknown     145k
hds-264-0    flv        unknown     264k
hds-264-1    flv        unknown     264k
hds-264-2    flv        unknown     264k
hds-264-3    flv        unknown     264k
hds-264-4    flv        unknown     264k
hds-264-5    flv        unknown     264k
hds-355-0    flv        unknown     355k
hds-355-1    flv        unknown     355k
hds-355-2    flv        unknown     355k
hds-355-3    flv        unknown     355k
hds-355-4    flv        unknown     355k
hds-355-5    flv        unknown     355k
hds-421-0    flv        unknown     421k
hds-421-1    flv        unknown     421k
hds-421-2    flv        unknown     421k
hds-421-3    flv        unknown     421k
hds-421-4    flv        unknown     421k
hds-421-5    flv        unknown     421k
hds-612-0    flv        unknown     612k
hds-612-1    flv        unknown     612k
hds-612-2    flv        unknown     612k
hds-612-3    flv        unknown     612k
hds-612-4    flv        unknown     612k
hds-612-5    flv        unknown     612k
hds-813-0    flv        unknown     813k
hds-813-1    flv        unknown     813k
hds-813-2    flv        unknown     813k
hds-813-3    flv        unknown     813k
hds-813-4    flv        unknown     813k
hds-813-5    flv        unknown     813k
hds-1014-0   flv        unknown    1014k
hds-1014-1   flv        unknown    1014k
hds-1014-2   flv        unknown    1014k
hds-1014-3   flv        unknown    1014k
hds-1014-4   flv        unknown    1014k
hds-1014-5   flv        unknown    1014k
hds-1414-0   flv        unknown    1414k
hds-1414-1   flv        unknown    1414k
hds-1414-2   flv        unknown    1414k
hds-1414-3   flv        unknown    1414k
hds-1414-4   flv        unknown    1414k
hds-1414-5   flv        unknown    1414k
hds-1812-0   flv        unknown    1812k
hds-1812-1   flv        unknown    1812k
hds-1812-2   flv        unknown    1812k
hds-1812-3   flv        unknown    1812k
hds-1812-4   flv        unknown    1812k
hds-1812-5   flv        unknown    1812k  (best)
  ---------------------------------------------- DOWNLOAD URL
  Downloading http://www.nbc.com/meet-the-press/video/meet-the-press-august-30-2015/2894316?onid=210121#vc210121=1

[NBC] 2894316: Downloading webpage
[ThePlatform] 8YsFR2OqQC0u: Downloading config
[ThePlatform] 8YsFR2OqQC0u: Downloading SMIL data
[ThePlatform] 8YsFR2OqQC0u: Downloading f4m manifest
[ThePlatform] 8YsFR2OqQC0u: Downloading f4m manifest
[ThePlatform] 8YsFR2OqQC0u: Downloading f4m manifest
[ThePlatform] 8YsFR2OqQC0u: Downloading f4m manifest
[ThePlatform] 8YsFR2OqQC0u: Downloading f4m manifest
[ThePlatform] 8YsFR2OqQC0u: Downloading f4m manifest
[ThePlatform] 8YsFR2OqQC0u: Downloading JSON metadata
[debug] Invoking downloader on u'http://nbcmpx-vh.akamaihd.net/z/video/703/238/150821_2894316_Meet_the_Press_August_30__2015_mpx_,1696,1296,896,696,496,306,240,150,64,.mp4.csmil/manifest.f4m?hdnea=st=1441593422~exp=1441594352~acl=/*~id=d8fce5e9-138e-431b-8f23-dfa40ece6333~hmac=24eb42842e381fbbd2ca8a9689d76f0bb5d2ad013b8db976817abe0a6d09368a&g=UXWGVKRWHFSP&hdcore=3.0.3'
[f4m] Downloading f4m manifest
[f4m] Total fragments: 502
[download] Destination: Meet the Press August 30, 2015-8YsFR2OqQC0u.flv

[download]   0.0% of ~31.83MiB at Unknown speed ETA 10:27:54
[download]   0.0% of ~31.83MiB at Unknown speed ETA 03:29:17
[download]   0.0% of ~31.83MiB at Unknown speed ETA 01:29:41
[download]   0.0% of ~31.83MiB at Unknown speed ETA 41:50   
[download]   0.0% of ~31.83MiB at  2.02MiB/s ETA 20:29      
[download]   0.0% of ~31.83MiB at  1.98MiB/s ETA 10:12      
[download]   0.0% of ~31.83MiB at  2.05MiB/s ETA 09:54      
[download]   0.2% of ~31.83MiB at  2.05MiB/s ETA 09:54      
[download]   0.2% of ~27.68MiB at 32.26KiB/s ETA 10:36      
[download]   0.2% of ~27.68MiB at 96.77KiB/s ETA 10:17      
[download]   0.2% of ~27.68MiB at 225.81KiB/s ETA 09:43     
[download]   0.2% of ~27.68MiB at 483.87KiB/s ETA 08:44     
[download]   0.2% of ~27.68MiB at 673.92KiB/s ETA 07:21     
[download]   0.2% of ~27.68MiB at 774.01KiB/s ETA 06:18     
[download]   0.4% of ~26.29MiB at 774.01KiB/s ETA 06:18     
[download]   0.1% of ~81.08MiB at Unknown speed ETA 19:42   
[download]   0.1% of ~81.08MiB at Unknown speed ETA 19:21   
[download]   0.1% of ~81.08MiB at Unknown speed ETA 18:42   
[download]   0.1% of ~81.08MiB at Unknown speed ETA 17:32   
[download]   0.1% of ~81.08MiB at  1.89MiB/s ETA 15:44      
[download]   0.1% of ~81.08MiB at  1.92MiB/s ETA 12:59      
[download]   0.1% of ~81.08MiB at  2.64MiB/s ETA 09:36      
[download]   0.1% of ~81.08MiB at  2.65MiB/s ETA 06:26      
[download]   0.1% of ~81.08MiB at  1.99MiB/s ETA 05:01      
[download]   0.4% of ~107.79MiB at  1.99MiB/s ETA 05:01     
[download]   0.7% of ~73.82MiB at 62.50KiB/s ETA 04:47      
[download]   0.7% of ~73.82MiB at 187.50KiB/s ETA 04:46     
[download]   0.7% of ~73.82MiB at 437.50KiB/s ETA 04:44     
[download]   0.7% of ~73.82MiB at 937.50KiB/s ETA 04:39     
[download]   0.7% of ~73.82MiB at 1000.00KiB/s ETA 04:33    
[download]   0.7% of ~73.82MiB at  1.98MiB/s ETA 04:17      
[download]   0.7% of ~73.82MiB at 564.71KiB/s ETA 04:18     
[download]   0.8% of ~69.47MiB at 564.71KiB/s ETA 04:18     
[download]   0.8% of ~70.08MiB at 62.50KiB/s ETA 04:19      
[download]   0.8% of ~70.08MiB at 187.50KiB/s ETA 04:18     
[download]   0.8% of ~70.08MiB at 437.50KiB/s ETA 04:18     
[download]   0.8% of ~70.08MiB at 483.87KiB/s ETA 04:15     
[download]   0.8% of ~70.08MiB at 1000.00KiB/s ETA 04:09    
[download]   0.8% of ~70.08MiB at  1.31MiB/s ETA 03:58      
[download]   0.8% of ~70.08MiB at  1.41MiB/s ETA 03:45      
[download]   1.0% of ~67.58MiB at  1.41MiB/s ETA 03:45      
[download]   0.9% of ~74.32MiB at 62.50KiB/s ETA 04:11      
[download]   0.9% of ~74.32MiB at 93.75KiB/s ETA 04:12      
[download]   0.9% of ~74.32MiB at 218.75KiB/s ETA 04:11     
[download]   0.9% of ~74.32MiB at 468.75KiB/s ETA 04:08     
[download]   0.9% of ~74.32MiB at 968.75KiB/s ETA 04:03     
[download]   0.9% of ~74.32MiB at  1.31MiB/s ETA 03:54      
[download]   0.9% of ~74.32MiB at  1.57MiB/s ETA 03:39      
[download]   0.9% of ~74.32MiB at  1.73MiB/s ETA 03:25      
[download]   1.1% of ~77.35MiB at  1.73MiB/s ETA 03:25      
[download]   1.3% of ~70.58MiB at 16.13KiB/s ETA 03:45      
[download]   1.3% of ~70.58MiB at 48.39KiB/s ETA 03:44      
[download]   1.3% of ~70.58MiB at 112.90KiB/s ETA 03:43     
[download]   1.3% of ~70.58MiB at 241.94KiB/s ETA 03:41     
[download]   1.3% of ~70.58MiB at 397.44KiB/s ETA 03:39     
[download]   1.3% of ~70.58MiB at 670.21KiB/s ETA 03:33     
[download]   1.3% of ~70.58MiB at 900.70KiB/s ETA 03:26     
[download]   1.5% of ~67.77MiB at 900.70KiB/s ETA 03:26     
[download]   1.5% of ~67.33MiB at 62.50KiB/s ETA 03:29      
[download]   1.5% of ~67.33MiB at 187.50KiB/s ETA 03:28     
[download]   1.5% of ~67.33MiB at 225.81KiB/s ETA 03:29     
[download]   1.5% of ~67.33MiB at 483.87KiB/s ETA 03:27     
[download]   1.5% of ~67.33MiB at 659.58KiB/s ETA 03:25     
[download]   1.5% of ~67.33MiB at 1000.00KiB/s ETA 03:20    
[download]   1.5% of ~67.33MiB at  1.41MiB/s ETA 03:14      
[download]   1.7% of ~64.80MiB at  1.41MiB/s ETA 03:14      
[download]   1.7% of ~64.38MiB at Unknown speed ETA 03:13   
[download]   1.7% of ~64.38MiB at Unknown speed ETA 03
    [I cut the output. It just continues like this]

**Comment by yan12125** [comment]
When the download is completed, all fragments are merged into a single file and then deleted.

**Comment by bonacker** [comment]
Thank you. I see that now, however the merged file doesn't playback correctly, at least on my machine. At the point when a new fragment is played, or every ~5 seconds, it replays about a .5 second of the end of the previous fragment. Is this being reproduced by other users? If so, is there an option that corrects this? Is it possible that a different format would not have this bug? I tried -f hds-145-0 and hds-145-1. Thanks.

**Comment by yan12125** [comment]
Which player are you using? I've tried mpv and VLC, and both work. I didn't notice repeated video fragments.

**Comment by bonacker** [comment]
Thanks for the fast replies. I appreciate it. I feel stupid that I didn't try alternative players. The file *does* play without repeating in a recent VLC (2.2.1) as well as an old 0.9 version. The problem occurred in SMPlayer 14.3.0 (mplayer Redxii-SVN-r36621-4.8.2). 

I wonder if this writing to disk of potentially 1000's of tiny files in a minute or two will stress the hard drive or file system or make the drive fail sooner if one were to download these files every day.

**Comment by yan12125** [comment]
Then it should be a mplayer/SMPlayer's bug. I'm closing this ticket here as there's nothing to do with youtube-dl.

For the second problem: it's different from the original one. Please open a new issue for discussion.
