### ISSUE TITLE
Downloading failed to new youtubbe videos.

### ISSUE THREAD

**Issue by kumarsandeep91** [rg3/youtube-dl#6788]
[youtube] Setting language
[youtube] opCjqS8wj4k: Downloading webpage
[youtube] opCjqS8wj4k: Downloading video info webpage
[youtube] opCjqS8wj4k: Extracting video information
[youtube] opCjqS8wj4k: Encrypted signatures detected.
[youtube] opCjqS8wj4k: Downloading js player new
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 424, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by kumarsandeep91** [comment]
I reinstalled it manually and its up to date now. it resolve the issue but it show some warning. what to do with this ??
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.

**Comment by dstftw** [comment]
How about to do what it suggest you to do?
