### ISSUE TITLE
Crunchyroll region issues

### ISSUE THREAD

**Issue by mixedCase** [rg3/youtube-dl#6797]
I'm using youtube-dl 2015.09.03 I just cloned from the repo and a video I can see perfectly fine in my web browser with no region issues  (http://www.crunchyroll.com/himouto-umaru-chan/episode-1-umaru-and-onii-chan-682801) is rejected by youtube-dl claiming there are in fact region issues:

```
[Crunchyroll] Logging in
[Crunchyroll] 682801: Downloading webpage
ERROR: crunchyroll returned error: Sorry, this video is not available in your region due to licensing restrictions.
```

And this is running from browser: https://i.imgur.com/FrfHWzM.png

Other series I'm watching (via premium account as well) do not show this behavior.

This is my youtube-dl -v output:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.03
[debug] Python version 3.4.3 - Linux-4.1.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```

Please let me know about any other information I could provide to help with this issue.

**Comment by dstftw** [comment]
Post the output of `youtube-dl -v --call-home http://www.crunchyroll.com/himouto-umaru-chan/episode-1-umaru-and-onii-chan-682801`. Post output from your browser for https://yt-dl.org/ip.

**Comment by mixedCase** [comment]
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--call-home', 'http://www.crunchyroll.com/himouto-umaru-chan/episode-1-umaru-and-onii-chan-682801']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.03
[debug] Python version 3.4.3 - Linux-4.1.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 167.61.133.139
[Crunchyroll] 682801: Downloading webpage
ERROR: crunchyroll returned error: Sorry, this video is not available in your region due to licensing restrictions.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/crunchyroll.py", line 252, in _real_extract
    raise ExtractorError('crunchyroll returned error: %s' % msg['message_body'], expected=True)
youtube_dl.utils.ExtractorError: crunchyroll returned error: Sorry, this video is not available in your region due to licensing restrictions.
```

And both my browser and curl are returning my ip from https://yt-dl.org/ip as 167.61.133.139

**Comment by dstftw** [comment]
What countries does this video is georestricted to? Can you provide uruguay proxy?

**Comment by mixedCase** [comment]
Not sure on georestriction. I got these uruguayan proxies off google: http://www.proxynova.com/proxy-server-list/country-uy/

I could set up something on my computer if needed.

**Comment by dstftw** [comment]
None of them work. Non-transparent proxy with IP from your region/country is required for test, ideally running right on your IP.

**Comment by mixedCase** [comment]
Easiest way to set-up a proxy?

**Comment by dstftw** [comment]
https://wiki.archlinux.org/index.php/Squid

**Comment by dstftw** [comment]
In private debugging session we have figured out that such behavior was caused by tricky crunchyroll logic on imposing georestriction that involves `Accept-Language` header.
Thanks for the report and collaboration.
