### ISSUE TITLE
yandex.music:playlist

### ISSUE THREAD

**Issue by kinik** [rg3/youtube-dl#6801]
paco@asus:~$ youtube-dl --verbose https://music.yandex.ru/users/mylogin/playlists/1000
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://music.yandex.ru/users/beef.myaso/playlists/1000']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.03
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {}
[yandexmusic:playlist] 1000: Downloading webpage
ERROR: An extractor error has occured. (caused by KeyError(u'pageData',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yandexmusic.py", line 142, in _real_extract
    playlist = mu['pageData']['playlist']
KeyError: u'pageData'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 293, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'pageData',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
404 not found.

**Comment by kinik** [comment]
I removed my login name in the link. Original link: https://music.yandex.ru/users/beef.myaso/playlists/1000

**Comment by dstftw** [comment]
I'm aware of that, 404 with both.

**Comment by Drezzler** [comment]
It is most likely region blocked ..

**Comment by dstftw** [comment]
No, I don't think so. All other URLs work fine, e.g. http://music.yandex.ru/users/music.partners/playlists/1245.
