### ISSUE TITLE
no conn, hlsvp or url_encoded_fmt_stream_map information

### ISSUE THREAD

**Issue by AlexeyBalin** [rg3/youtube-dl#6802]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.youtube.com/watch?v=Iq_ZV_-6glU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.03-gentoo_no_offensive_sites
[debug] Python version 2.7.9 - Linux-3.18.14-calculate-x86_64-AMD_A4-4000_APU_with_Radeon-tm-_HD_Graphics-with-gentoo-14.16.2
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[youtube] Iq_ZV_-6glU: Downloading webpage
[youtube] Iq_ZV_-6glU: Downloading video info webpage
[youtube] Iq_ZV_-6glU: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1355, in _real_extract
    raise ExtractorError('no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')
ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This live stream has not yet started.
