### ISSUE TITLE
eerno 13

### ISSUE THREAD

**Issue by boddcoward** [rg3/youtube-dl#6807]
getter the errno 13 message. what am i doing wrong and how do i fix this?

C:\Windows\System32>C:\Users\Chris\Downloads\youtube-dl.exe https://www.youtube.
com/watch?v=kmvcJuBOaQE -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=kmvcJuBOaQE', u'-v
']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.09.03
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] kmvcJuBOaQE: Downloading webpage
[youtube] kmvcJuBOaQE: Downloading video info webpage
[youtube] kmvcJuBOaQE: Extracting video information
[youtube] kmvcJuBOaQE: Downloading DASH manifest
[youtube] kmvcJuBOaQE: Downloading DASH manifest
[debug] Invoking downloader on u'https://r2---sn-q4f7sne7.googlevideo.com/videop
layback?mm=31&ipbits=0&mn=sn-q4f7sne7&ip=162.216.46.189&itag=22&dur=2000.817&ini
tcwndbps=1210000&id=o-AE1Yp2C7cfotFJDSLUrKXyYoteHggFD7Mz_63pduE8kX&pl=24&mt=1441
763886&source=youtube&mv=m&mime=video%2Fmp4&ms=au&signature=DE3100C72299A5AF1A02
5A45647F6BB40F612D9A.68072547735A3E42A7A35DBCABA11AFE8C14BB1D&fexp=9407002%2C940
7168%2C9408710%2C9409069%2C9415365%2C9415485%2C9416023%2C9416126%2C9416515%2C941
6574%2C9416729%2C9417157%2C9417707%2C9418028%2C9418153%2C9418235%2C9418391%2C941
8448%2C9418497%2C9418997%2C9419050%2C9420142%2C9420224%2C9420348&ratebypass=yes&
requiressl=yes&sver=3&nh=IgpwcjAyLmRmdzA2KgkxMjcuMC4wLjE&sparams=dur%2Cid%2Cinit
cwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crateby
pass%2Crequiressl%2Csource%2Cupn%2Cexpire&key=yt5&lmt=1438250743529672&upn=6_D7a
idS-oc&expire=1441785549'
ERROR: unable to open for writing: [Errno 13] Permission denied: u"Ross's Game D
ungeon - Battleforge-kmvcJuBOaQE.mp4.part"
Traceback (most recent call last):
  File "youtube_dl\downloader\http.pyo", line 174, in real_download
  File "youtube_dl\utils.pyo", line 256, in sanitize_open
IOError: [Errno 13] Permission denied: u"Ross's Game Dungeon - Battleforge-kmvcJ
uBOaQE.mp4.part"

C:\Windows\System32>

**Comment by fstirlitz** [comment]
You're trying to save the video file in `C:\Windows\System32` of all places. What else do you expect?

**Comment by boddcoward** [comment]
truth be told,i wasnt paying attention to the command line, and was just running youtube dl like i always have. which normally opens to C:\Users\Chris\ turns out when you pin Cmd to the start menu it changes the default path. lesson learned, thanks for showing me my mistake.
