### ISSUE TITLE
Dailymotion video fails to extract

### ISSUE THREAD

**Issue by aptwebapps** [rg3/youtube-dl#6808]
This url fails to extract. I also tested with http://www.dailymotion.com/video/x26hmm8_real-madrid-3-1-elche-goal-cristiano-ronaldo-23-09-2014_sport which I got from an old issue (#3819) and it's the same.

```
$ youtube-dl --verbose  http://www.dailymotion.com/video/x35p979_costa-rica-vs-uruguay-1-0-bryan-ruiz-goal-friendly-match-9-9-2015_sport
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.dailymotion.com/video/x35p979_costa-rica-vs-uruguay-1-0-bryan-ruiz-goal-friendly-match-9-9-2015_sport']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[dailymotion] x35p979: Downloading webpage
[dailymotion] x35p979: Extracting information
[dailymotion] x35p979: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 119, in _real_extract
    'video info', flags=re.MULTILINE)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info;
```

**Comment by jaimeMF** [comment]
The video has been removed by the user (that's what you get if you access the url in a browser), so we can't download it. Additionally you are using an outdated version, [you have to upgrade youtube-dl](https://github.com/rg3/youtube-dl/blob/8f9d522f6252f874d41045b2458256ca8cf1a312/README.md#how-do-i-update-youtube-dl).

**Comment by aptwebapps** [comment]
Ah, I did update via pip but apparently the some other Macports package installed youtube-dl as well and that one is first in my path. Sorry about that.

Side note: the actual url I first tested, the one in the dump, is still up. I just grabbed the other one from the other issue to see if it was a problem with the single url but should have checked in the browser first.

**Comment by jaimeMF** [comment]
I missed that url, it works with the last version.

**Comment by aptwebapps** [comment]
Yeah, it's all good. Fixed my path to get the Python scripts in front of the Macport binaries. Sorry for the false report.
