### ISSUE TITLE
Bandcamp support artist download

### ISSUE THREAD

**Issue by lightonflux** [rg3/youtube-dl#6809]
The extractor for Bandcamp works wonderful.  But only with with an album URL:

   https://thegrammarclub.bandcamp.com/album/bioavailable

Not with an artist URL:

    https://thegrammarclub.bandcamp.com/

Maybe yt-dl could look at the page and extract the album URLs and then proceed normally with track extraction.

**Comment by dstftw** [comment]
Duplicate of #6231.

**Comment by djvs** [comment]
@lightonflux  See script I gave on #6231
