### ISSUE TITLE
It seems Safaribooksonline updated their video files location or something?

### ISSUE THREAD

**Issue by moenad** [rg3/youtube-dl#6817]
I was downloading couple of videos (OSCon 2015) from safaribooksonline, I get video file not found even though I can watch the video online normally.

Not sure what exactly happened, I downloaded a few normally yesterday.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by moenad** [comment]
Oops sorry.

Here's a url 
https://www.safaribooksonline.com/library/view/oscon-2015-complete/9781491927991/part133.html

Here's the link I get from youtube-dl
http://brightcove.vo.llnwd.net/v1/uds/pd/1644572897001/201508/250/1644572897001_4448412050001_9781491927991-video217960-25c256fecdb96f9e8cbf9c7c1e74a104-copy.mp4

Error if I try to download, I had a list of links in my download manager. Everything was working fine yesterday, I even tried to regenerate the link from youtube-dl again but the error persisted. I can still watch the video online normally.

**Comment by dstftw** [comment]
Brightcove returns broken non-AMF links for these particular videos. AMF (those are played in browser) are not supported by youtube-dl.

**Comment by dstftw** [comment]
Not actual after switch to kaltura.

**Comment by janemaydaily** [comment]
Allavsoft also works
