### ISSUE TITLE
Downloading video *AND* audio, in a consistent way?

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#6818]
Is there a way to download video and audio in a consistent way?

Background: I have a wrapper script for Youtube-dl. At first, when I was playing with YouTube, 480p downloads gave .flv files, and asking for mp4's gave me 360p's with audio. Getting both video and audio from youtube required fetching two files, converting the flv to mp4, and combining.

Next, I found that other sites that had mp4's would return mp4 videos with audio already in them.

Youtube now makes 480p's in mp4 format, and the HTML5 player has been playing mp4's with nothing apparently special about them, so I adjusted my script to fetch mp4 files and be done.

But ... I've discovered that while I've gotten video plus audio from PBS for nova, and from Chrunchyroll for other TV shows, my youtube downloads have been video without audio.

What is the proper way to say "Fetch this video file, and only make an attempt to fetch an additional audio file if there isn't one already in the video"? 

For that matter,  is there a way to do the same thing with subtitles -- only fetch a subtitle if the video doesn't have one?

My current wrapper:
```
#!/bin/bash
set -x
# Usage: youtube-480 url
## youtube-dl -f "bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]/[height<=?480]" --sub-lang en --write-sub --recode-video mp4 "$@"
youtube-dl -f "bestvideo[height<=480][ext=mp4]" --list-sub "$@" | grep -m 1 '^[eE][nN]' | awk '{print $1}' > /tmp/yt-sub.$$
## youtube-dl -f "bestvideo[height<=480][ext=mp4]" --sub-lang $(cat /tmp/yt-sub.$$) --sub-format ass --write-sub --recode-video mp4 "$@"
youtube-dl -f "bestvideo[height<=480]" --sub-lang $(cat /tmp/yt-sub.$$) --write-sub --embed-subs --recode-video mp4 "$@"
```

**Comment by dstftw** [comment]
If you want video+audio as single file to have higher priority over other formats you should put it first when specifying preference with `/`, e.g. `-f best[height<=480]/bestvideo[height<=480]+bestaudio`.
For subtitles - it's not possible.

**Comment by keybounce** [comment]
Thank you.
