### ISSUE TITLE
How to download udemy videos ?

### ISSUE THREAD

**Issue by attiqfsd** [rg3/youtube-dl#6823]
What is syntax of downloading udemy paid course that I am enrolled in to.
Udemy-dl stopped working.

**Comment by dstftw** [comment]
`youtube-dl -u username -p password URL`.

**Comment by attiqfsd** [comment]
Thanks it worked like charm :)

**Comment by attiqfsd** [comment]
its not creating folders for every section. Like Udemy-dl
Can you please include that in next release?

**Comment by AnmolTomer** [comment]
yes it will just use the format i am giving 
youtube-dl -u xxxxxx@gmail.com -p xxxxxxx -o '~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s' URLofYourCourse

If you use this code then it will be downloaded in C:\Users\YourUserName\MyVideos\Coursename
Note : Mention full url till end of the course like ...../v4/overview
