### ISSUE TITLE
brightcove other URL type support

### ISSUE THREAD

**Issue by jcarlosgarciasegovia** [rg3/youtube-dl#6824]
http://www.dn.no/magasinet/2015/09/07/1606/Popcorn-Time/inside-popcorn-time--the-worlds-fastest-growing-piracy-site

**Comment by yan12125** [comment]
Note: Related to #6074. Both of them use Brightcove's [embed_in_page](http://docs.brightcove.com/en/perform/brightcove-player/guides/embed-in-page.html) feature.

**Comment by dstftw** [comment]
New Brightcover embeds will be supported in the next version of youtube-dl.
