### ISSUE TITLE
signature extraction bug

### ISSUE THREAD

**Issue by bendanon** [rg3/youtube-dl#6826]
hi,

I ran " youtube-dl https://youtu.be/OsYrBZqucpE --verbose >& bug" and bug got filled with the following -

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://youtu.be/OsYrBZqucpE', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out None, pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-63-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[youtube] Setting language
[youtube] OsYrBZqucpE: Downloading webpage
[youtube] OsYrBZqucpE: Downloading video info webpage
[youtube] OsYrBZqucpE: Extracting video information
[youtube] OsYrBZqucpE: Encrypted signatures detected.
[youtube] encrypted signature length 90 (46.43), itag 43, html5 player new-en_US-vflhlPTtB\/html5player-new
[youtube] OsYrBZqucpE: Downloading js player new
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 424, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 90 (46.43), itag 18, html5 player new-en_US-vflhlPTtB\/html5player-new
[youtube] OsYrBZqucpE: Downloading js player new
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 424, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 90 (46.43), itag 5, html5 player new-en_US-vflhlPTtB\/html5player-new
[youtube] OsYrBZqucpE: Downloading js player new
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 424, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 90 (46.43), itag 36, html5 player new-en_US-vflhlPTtB\/html5player-new
[youtube] OsYrBZqucpE: Downloading js player new

ERROR: Interrupted by user

**Comment by jaimeMF** [comment]
> [debug] youtube-dl version 2014.02.17

You are using an outdated version, [you have to upgrade youtube-dl](https://github.com/rg3/youtube-dl/blob/8f9d522f6252f874d41045b2458256ca8cf1a312/README.md#how-do-i-update-youtube-dl).

**Comment by bendanon** [comment]
$ youtube-dl -U
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
# apt-get upgrade youtube-dl
Reading package lists...
Building dependency tree...
Reading state information...
youtube-dl is already the newest version.
