### ISSUE TITLE
-U --update option has problems on windows if not given absolute path to youtube-dl.exe

### ISSUE THREAD

**Issue by henrik-jensen** [rg3/youtube-dl#6829]
Clarification:
'youtube-dl.exe' is placed in a dir. on the path that I have write permissions to.
Let's say I'm in 'C:\SomeDir' and 'youtube-dl.exe' is in 'c:\users\MyProfile\bin' that is on the path.
If I then run:
```
C:\SomeDir> youtube-dl.exe -U
```
I get the 'ERROR: no write permissions on youtube-dl' message

Giving the full path on the other hand works fine:
```
C:\SomeDir> c:\users\MyProfile\bin\youtube-dl.exe -U
```
and changing directory to where 'youtube-dl.exe' is placed also works:
```
c:\SomeDir> cd c:\users\MyProfile\bin\
c:\users\MyProfile\bin> youtube-dl.exe -U
```
This happen with the version '2015.09.03'
I can't check it with latest version ('2015.09.09') as this just tells me that it's up-to-date so it never tries to write to disk.

--henrik

**Comment by jaimeMF** [comment]
I think it's the same issue as #2718, could you confirm?

**Comment by henrik-jensen** [comment]
Yes, I can confirm. This issue, #6829, is a duplicate of #2718.
Should I close this issue?
