### ISSUE TITLE
cannot DL youtube SIZE>32M

### ISSUE THREAD

**Issue by lele2010lele** [rg3/youtube-dl#6830]
apple-de15cunMacBook-Pro:~ apple$ youtube-dl --proxy http://127.0.0.1:8087 -tc https://www.youtube.com/watch?v=PUevY8GHLiw
[youtube] PUevY8GHLiw: Downloading webpage
[youtube] PUevY8GHLiw: Downloading video info webpage
[youtube] PUevY8GHLiw: Extracting video information
[youtube] PUevY8GHLiw: Downloading js player new-en_US-vflhlPTtB
[youtube] PUevY8GHLiw: Downloading DASH manifest
[download] Destination: The Eagles-Hotel California (Live Melbourne 2005)-720p DTS.mkv-PUevY8GHLiw.mp4
[download]   4.5% of 32.00MiB at 129.10KiB/s ETA 04:02

ITS always 32M,
whats the matter please?

**Comment by remitamine** [comment]
you already opened an issue #6091 but it doesn't have a meaningful name it whould be better to just change it and not opening a new issue there is already instruction about this type of cases.
https://github.com/rg3/youtube-dl#is-the-issue-already-documented
