### ISSUE TITLE
youtube-dl 2015.09.09 ERROR: Signature extraction failed: Traceback (most recent call last):   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 771, in _decrypt_signature     video_id, player_url, s   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 663, in _extract_signature_function     raise ExtractorError('Cannot identify player %r' % player_url)

### ISSUE THREAD

**Issue by refr11** [rg3/youtube-dl#6833]
youtube-safe "http://youtube.com/watch?v=P2wPLqstMAA"
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 771, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 663, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflbPIo2O/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflbPIo2O/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
http://: Nombre de equipo inválido.
1 out of 1

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by refr11** [comment]
Well, Apparently it was a mistake from me, everything is ok, sorry for the false alarm. Bye!
