### ISSUE TITLE
Unable to update or download

### ISSUE THREAD

**Issue by jhb50** [rg3/youtube-dl#6834]
I have been getting these messages today. Any ideas why?

C:\Users\John>"C:\Program Files\Serviio\lib\youtube-dl.exe" https://www.youtube.
com/watch?v=e-hggs0GDjc
[youtube] e-hggs0GDjc: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 10038] An operation was
 attempted on something that is not a socket> (caused by URLError(error(10038, '
An operation was attempted on something that is not a socket'),))

C:\Users\John>"C:\Program Files\Serviio\lib\youtube-dl.exe" -U
ERROR: can't find the current version. Please try again later.

**Comment by dstftw** [comment]
Most likely a connectivity problem. Do you experience it now?

**Comment by jhb50** [comment]
HMM. Restoring my system fixed it. Strange. Thanks.
