### ISSUE TITLE
Mailing List.

### ISSUE THREAD

**Issue by anweshknayak** [rg3/youtube-dl#6838]
Is there a mailing list of your organisation?
I want to understand the codebase of youtube-dl and want to contribute for the org. I am new to reading open sourced codes. Can anyone guide me through or provide links for the same?

**Comment by yan12125** [comment]
Most discussions occur on Github. Just ask here. [Developer instructions](https://github.com/rg3/youtube-dl/#developer-instructions) may be a good start.
