### ISSUE TITLE
Download only new videos

### ISSUE THREAD

**Issue by zioalex** [rg3/youtube-dl#684]
Hi dear,
Is there a way to download only new video added to an existent playlist?

Actually the program try to download and see that the file is already here.

Thanks
Alex

**Comment by bartekbrak** [comment]
Also, it would be nice for the skip mechanism to take into account converted audio files (I use `--extract-audio --audio-format mp3`) as the original videos get deleted. So, when matching the already downloaded filename, skip the extension, perhaps.

**Comment by jaimeMF** [comment]
@bartekbrak it's not the perfect solution (implementing it could be a bit messy), but you can use `--download-archive`. Since you request is not directly related to this, please open a new issue if you have any problem.

**Comment by sindhus** [comment]
@jaimeMF thanks for the tip!
