### ISSUE TITLE
Download videos blocked on copyright grounds

### ISSUE THREAD

**Issue by m4gaikwad** [rg3/youtube-dl#6843]
I was downloading a playlist but some videos in it were blocked due to copyright infringement. Is there any way to download them ? Thanks in advance.

**Comment by dstftw** [comment]
If you can't watch it in browser then you can't download it.

**Comment by thomasf** [comment]
does youtube-dl always top on errors? I was downloading a large stream of videos and this error appeared and the execution stopped.. I can't tell if all other videos were downloaded or not but imho youtube-dl should not exit on errors in this situation but continue with th

**Comment by thomasf** [comment]
oh I found #1964

**Comment by woeterman94** [comment]
Not sure if this is helpful, but youtube studio has a download button next to your videos (even if it is blocked). 

![image](https://user-images.githubusercontent.com/5755057/62853035-6fc48f80-bceb-11e9-8864-af254794c048.png)
