### ISSUE TITLE
[http @ 03290ca0] HTTP error 403 Forbidden http://ftvodhdsecz-f.akamaihd.net Server returned 403 Forbidden (access denied)

### ISSUE THREAD

**Issue by chiquipe** [rg3/youtube-dl#6844]
I have a problem with this link http://culturebox.francetvinfo.fr/festivals/avignon-2015/les-memoires-du-festival/la-mouette-de-tchekhov-avignon-2012-137575.

This video is georestricted but i have already downloaded other videos with the command --proxy

>youtube-dl --proxy 46.105.39.156:3128 -f best http://culturebox.francetvinfo.fr/fest
ivals/avignon-2015/les-memoires-du-festival/la-mouette-de-tchekhov-avignon-2012-137575
[culturebox.francetvinfo.fr] festivals/avignon-2015/les-memoires-du-festival/la-
mouette-de-tchekhov-avignon-2012-137575: Downloading webpage
[culturebox.francetvinfo.fr] EV_1183: Downloading video JSON
[culturebox.francetvinfo.fr] EV_1183: Downloading geo restriction info
[culturebox.francetvinfo.fr] EV_1183: Downloading m3u8 information
[culturebox.francetvinfo.fr] EV_1183: Downloading m3u8 information
[download] Destination: La Mouette de Tchekhov - Avignon 2012-EV_1183.mp4
ffmpeg version N-74313-g9c0407e Copyright (c) 2000-2015 the FFmpeg developers
built with gcc 4.9.3 (GCC)
 configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-l
ibilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enab
le-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --en
able-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --ena
ble-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc
 --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enabl
e-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --ena
ble-decklink --enable-zlib
  libavutil      54. 30.100 / 54. 30.100
  libavcodec     56. 57.100 / 56. 57.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 32.100 /  5. 32.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[http @ 03290ca0] HTTP error 403 Forbidden
http://ftvodhdsecz-f.akamaihd.net/i/streaming-adaptatif_france-dom-tom/evt/pf-cu
lture/2012/07/66720671-20120724-,398k,632k,934k,.mp4.csmil/index_2_av.m3u8?null=
: Server returned 403 Forbidden (access denied)

ERROR: ffmpeg exited with code 1

any idea?

**Comment by dstftw** [comment]
ffmpeg has no `--proxy` option therefore on proxy passed to it. You have to set `HTTP_PROXY` env variable or use native youtube-dl hls `--hls-prefer-native`.

**Comment by chiquipe** [comment]
perfect !
