### ISSUE TITLE
Unable to download this pluzz.francetv.fr video.

### ISSUE THREAD

**Issue by powlpy** [rg3/youtube-dl#6846]
Hi !

youtube-dl http://pluzz.francetv.fr/videos/les_enquetes_de_murdoch_saison8_ep5_,127688505.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://pluzz.francetv.fr/videos/les_enquetes_de_murdoch_saison8_ep5_,127688505.html', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-x86_64-with-LinuxMint-17-qiana
[debug] Proxy map: {}
[pluzz.francetv.fr] les_enquetes_de_murdoch_saison8_ep5_,127688505: Downloading webpage
[pluzz.francetv.fr] 127688505: Downloading XML config
ERROR: Unable to download XML: HTTP Error 400: Bad Request; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 191, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1157, in urlopen
    return self._opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Warning, this is an example, on Pluzz, the links have a limited life !!!

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
