### ISSUE TITLE
-o oddities in windows batch files

### ISSUE THREAD

**Issue by enterprised1** [rg3/youtube-dl#6849]
i'm using a batch file in windows to change the filename to just the title and extension - basically remove the %(id)s.

here's what i have in the batch file:
set /p address=Enter video site address: 
youtubedl\youtube-dl.exe -v -o '%(title)s.%(ext)s' %address%

When attempting to run, i get the error:
"youtube-dl.exe: error: You must provide at least one URL."

When running the batch file without the -o option, it runs fine (but appends the %(id)s, which is what i'm trying to avoid).

running the same command directly in the command prompt works fine.  any ideas why it's not working when run from a batch file?

thanks!

-v debug:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-o', u"'address"]
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

**Comment by jaimeMF** [comment]
You may need to escape the `%` from the `-o` option in the batch file, could you post the output of the batch file (with the `-v` option)?

**Comment by dstftw** [comment]
Correct code:
```
set /p address=Enter video site address:
youtubedl\youtube-dl.exe -v -o "%%(title)s.%%(ext)s" %address%
```
