### ISSUE TITLE
Avconv not working in Debian Jessie

### ISSUE THREAD

**Issue by WeWin55** [rg3/youtube-dl#6856]
Hello,
Ive got Debian Jessie on my vServer and installed libav-tools (avconv).
On my Raspberry pi (Debian Wheezy) avconv works. 
Backport from Wheezy is not working on Jessie, because of other packages.

On Debian Jessie avconv -version is:

root@mo-server-on:~# avconv -version
avconv version 11.4-6:11.4-1~deb8u1, Copyright (c) 2000-2014 the Libav developers
  built on Jun  4 2015 19:39:02 with gcc 4.9.2 (Debian 4.9.2-10)
avconv 11.4-6:11.4-1~deb8u1
libavutil     54.  3. 0 / 54.  3. 0
libavcodec    56.  1. 0 / 56.  1. 0
libavformat   56.  1. 0 / 56.  1. 0
libavdevice   55.  0. 0 / 55.  0. 0
libavfilter    5.  0. 0 /  5.  0. 0
libavresample  2.  1. 0 /  2.  1. 0
libswscale     3.  0. 0 /  3.  0. 0

On the Raspberry pi it is:

pi@raspberrypi2 ~ $ avconv -version
avconv version 9.14-6:9.14-1rpi1rpi1, Copyright (c) 2000-2014 the Libav developers
  built on Jul 22 2014 15:08:12 with gcc 4.6 (Debian 4.6.3-14+rpi1)
avconv 9.14-6:9.14-1rpi1rpi1
libavutil     52.  3. 0 / 52.  3. 0
libavcodec    54. 35. 0 / 54. 35. 0
libavformat   54. 20. 4 / 54. 20. 4
libavdevice   53.  2. 0 / 53.  2. 0
libavfilter    3.  3. 0 /  3.  3. 0
libavresample  1.  0. 1 /  1.  0. 1
libswscale     2.  1. 1 /  2.  1. 1

Thanks in advance.

**Comment by dstftw** [comment]
How is this related to youtube-dl? Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by alexvong1995** [comment]
Hi, I think Debian has switched back to ffmpeg in Stretch and Sid (`avconv`, `avprobe` and `avplay` are symlinked to their ffmpeg's cousin), but this shouldn't affect Jessie since it is "stable", I will try to reproduce it on my Jessie box later at night.

**Comment by WeWin55** [comment]
Hello, 
thanks for replying.

Okay i though the development of ffmpeg was stopped and they are consentraded on avconv.

Here is the output:

root@mo-server-on:~# sh youtube.sh
Youtube ist erreichbar.
####Youtube-DL starts downloading. Press CTRL-C to cancel, you have 5 sec!#####
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'bestvideo[ext=mp4][fps<35][height=1080]+bestaudio[ext=m4a]', u'--audio-quality', u'6', u'--merge-output-format', u'mp4', u'--add-metadata', u'-c', u'-w', u'--no-mtime', u'--write-thumbnail', u'--download-archive', u'/media/PlexDL-Log.txt', u'--playlist-end', u'5', u'--verbose', u'--output', u'%(title)s - [%(resolution)s - %(uploader)s].%(ext)s', u'https://www.youtube.com/user/Trilluxe/videos?&ab_channel=Trilluxe']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.9 - Linux-3.16.0-042stab103.6-x86_64-with-debian-8.2
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6
[debug] Proxy map: {}
[youtube:user] Trilluxe: Downloading channel page
[youtube:playlist] UUHLywIFGrNhgHxeI1dRpfOg: Downloading webpage[download] Downloading playlist: Uploads from TrilluXe  CS:GO Channel
[youtube:playlist] playlist Uploads from TrilluXe  CS:GO Channel : Downloading 5 videos
[download] Downloading video 1 of 5
[download] NGM2f3iYa48 has already been recorded in archive
[download] Downloading video 2 of 5
[download] YuWECA0swvc has already been recorded in archive
[download] Downloading video 3 of 5
[download] QiCBSpiPhuA has already been recorded in archive
[download] Downloading video 4 of 5
[download] iTTkNjUTE4w has already been recorded in archive
[download] Downloading video 5 of 5
[youtube] VhfxyxsKuFM: Downloading webpage
[youtube] VhfxyxsKuFM: Downloading video info webpage
[youtube] VhfxyxsKuFM: Extracting video information
[youtube] VhfxyxsKuFM: Downloading DASH manifest
[youtube] VhfxyxsKuFM: Downloading DASH manifest
[youtube] VhfxyxsKuFM: Thumbnail is already present
[download] CS -GO - Let's Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [1920x1080 - TrilluXe  CS -GO Channel ].mp4 has already been downloaded and merged
[ffmpeg] Adding metadata to 'CS -GO - Let's Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [1920x1080 - TrilluXe  CS -GO Channel ].mp4'
[debug] ffmpeg command line: avconv -y -i 'CS -GO - Let'"'"'s Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [1920x1080 - TrilluXe  CS -GO Channel ].mp4' -c copy -metadata 'comment=Time to waste some money again and unbox cases together! :D
Steam Group: http://steamcommunity.com/groups/trilluxe
Vulcun: https://vulcun.com/affiliate/TrilluXe

 Mojo: https://www.youtube.com/user/MojoOnPC
 HOUNGOUNGAGNE: https://www.youtube.com/user/jeffw8nc
 Chaimbo: https://www.youtube.com/user/pOtchVideos

 If you want to donate something, you can use this link:  http://tinyurl.com/Donate4Trill
 Where I buy my Games: https://www.g2a.com/r/trilluxe


 Links


 Steam Group: http://steamcommunity.com/groups/trilluxe
 Facebook: https://www.facebook.com/TrilluXe
 Twitter: https://twitter.com/TrilluXeYT
 German Channel: https://www.youtube.com/TrilluXeLIVE
 Steam Profile: http://steamcommunity.com/id/TrilluXe


 Partners


 Vulcun - http://bit.ly/1Ic3apI - $10.000.000 Fantasy eSports League. Up to $1000 Bonus with the Signup Code '"'"'TrilluXe'"'"'. CSGOCasino - http://csgocasino.net/ - Feel lucky and want to gamble for Skins? Be sure to check out CSGOCasino!


 My Gaming Setup


 Mouse: Logitech G400s - http://amzn.to/1DgKpOI
 Keyboard: Corsair Vengeance K95 - http://amzn.to/1zyM1pz
 Mousepad: SteelSeries QcK+ - http://amzn.to/1CMpXqH
 Gaming Monitor: BenQ XL2720Z - http://amzn.to/1v48j0I
 Mouse Bungee: EpicGear Skorpios - http://amzn.to/1zyMA2A
 Headset: Beyerdynamic MMX300 - http://amzn.to/1v47GEv
 Microphone: Rode NT-1A - http://amzn.to/1v47Xai
 Audio Interface: PreSonus Audiobox - http://amzn.to/1CMqkl5
 Soundcard: Asus Xonar Essence STX - http://amzn.to/1x1RiF2

 Second Monitor: Acer S242HLCBID - http://amzn.to/1IEqwXE
 Third Monitor: BenQ G2420HDBL - http://amzn.to/1GYnX0j


 Config/Crosshair/Viewmodel


 My Config: http://tinyurl.com/TrillConfig
 My Crosshair: http://tinyurl.com/TrillCrosshair
 My Viewmodel: http://tinyurl.com/TrillViewmodel


 Music


 SpongeBob Trap Remix (TheKrustyKrab) [TheRakeHornPipe] [ORIGINAL]
 BRODYQUEST
 Sad Violin' -metadata 'description=Time to waste some money again and unbox cases together! :D
Steam Group: http://steamcommunity.com/groups/trilluxe
Vulcun: https://vulcun.com/affiliate/TrilluXe

 Mojo: https://www.youtube.com/user/MojoOnPC
 HOUNGOUNGAGNE: https://www.youtube.com/user/jeffw8nc
 Chaimbo: https://www.youtube.com/user/pOtchVideos

 If you want to donate something, you can use this link:  http://tinyurl.com/Donate4Trill
 Where I buy my Games: https://www.g2a.com/r/trilluxe


 Links


 Steam Group: http://steamcommunity.com/groups/trilluxe
 Facebook: https://www.facebook.com/TrilluXe
 Twitter: https://twitter.com/TrilluXeYT
 German Channel: https://www.youtube.com/TrilluXeLIVE
 Steam Profile: http://steamcommunity.com/id/TrilluXe


 Partners


 Vulcun - http://bit.ly/1Ic3apI - $10.000.000 Fantasy eSports League. Up to $1000 Bonus with the Signup Code '"'"'TrilluXe'"'"'. CSGOCasino - http://csgocasino.net/ - Feel lucky and want to gamble for Skins? Be sure to check out CSGOCasino!


 My Gaming Setup


 Mouse: Logitech G400s - http://amzn.to/1DgKpOI
 Keyboard: Corsair Vengeance K95 - http://amzn.to/1zyM1pz
 Mousepad: SteelSeries QcK+ - http://amzn.to/1CMpXqH
 Gaming Monitor: BenQ XL2720Z - http://amzn.to/1v48j0I
 Mouse Bungee: EpicGear Skorpios - http://amzn.to/1zyMA2A
 Headset: Beyerdynamic MMX300 - http://amzn.to/1v47GEv
 Microphone: Rode NT-1A - http://amzn.to/1v47Xai
 Audio Interface: PreSonus Audiobox - http://amzn.to/1CMqkl5
 Soundcard: Asus Xonar Essence STX - http://amzn.to/1x1RiF2

 Second Monitor: Acer S242HLCBID - http://amzn.to/1IEqwXE
 Third Monitor: BenQ G2420HDBL - http://amzn.to/1GYnX0j


 Config/Crosshair/Viewmodel


 My Config: http://tinyurl.com/TrillConfig
 My Crosshair: http://tinyurl.com/TrillCrosshair
 My Viewmodel: http://tinyurl.com/TrillViewmodel


 Music


 SpongeBob Trap Remix (TheKrustyKrab) [TheRakeHornPipe] [ORIGINAL]
 BRODYQUEST
 Sad Violin' -metadata 'artist=TrilluXe  CS:GO Channel ' -metadata 'title=CS:GO - Let'"'"'s Unbox Together #3 - w/ Mojo, HOUNGOUNGAGNE, & Chaimbo' -metadata date=20150830 -metadata 'purl=https://www.youtube.com/watch?v=VhfxyxsKuFM' 'CS -GO - Let'"'"'s Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [1920x1080 - TrilluXe  CS -GO Channel ].temp.mp4'
########################################################################################
root@mo-server-on:~#

**Comment by WeWin55** [comment]
Sorry for double post. 
But I checked and the above script hadn't downloaded the video. So I removed it from the list and the files itself. I will test it now on more videos and report back.

Here's the new output (meta data set, avconv worked):

root@mo-server-on:~# sh youtube.sh
Youtube ist erreichbar.
####Youtube-DL starts downloading. Press CTRL-C to cancel, you have 5 sec!#####
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'bestvideo[ext=mp4][fps<35][height=1080]+bestaudio[ext=m4a]', u'--audio-quality', u'6', u'--merge-output-format', u'mp4', u'--add-metadata', u'-c', u'-w', u'--no-mtime', u'--write-thumbnail', u'--download-archive', u'/media/PlexDL-Log.txt', u'--playlist-end', u'5', u'--verbose', u'--output', u'%(title)s - [%(resolution)s - %(uploader)s].%(ext)s', u'https://www.youtube.com/user/Trilluxe/videos?&ab_channel=Trilluxe']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.9 - Linux-3.16.0-042stab103.6-x86_64-with-debian-8.2
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6
[debug] Proxy map: {}
[youtube:user] Trilluxe: Downloading channel page
[youtube:playlist] UUHLywIFGrNhgHxeI1dRpfOg: Downloading webpage[download] Downloading playlist: Uploads from TrilluXe  CS:GO Channel
[youtube:playlist] playlist Uploads from TrilluXe  CS:GO Channel : Downloading 5 videos
[download] Downloading video 1 of 5
[download] NGM2f3iYa48 has already been recorded in archive
[download] Downloading video 2 of 5
[download] YuWECA0swvc has already been recorded in archive
[download] Downloading video 3 of 5
[download] QiCBSpiPhuA has already been recorded in archive
[download] Downloading video 4 of 5
[download] iTTkNjUTE4w has already been recorded in archive
[download] Downloading video 5 of 5
[youtube] VhfxyxsKuFM: Downloading webpage
[youtube] VhfxyxsKuFM: Downloading video info webpage
[youtube] VhfxyxsKuFM: Extracting video information
[youtube] VhfxyxsKuFM: Downloading DASH manifest
[youtube] VhfxyxsKuFM: Downloading DASH manifest
[youtube] VhfxyxsKuFM: Downloading thumbnail ...
[youtube] VhfxyxsKuFM: Writing thumbnail to: CS -GO - Let's Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [1920x1080 - TrilluXe  CS -GO Channel ].jpg
[debug] Invoking downloader on u'https://r13---sn-4g57km7l.googlevideo.com/videoplayback?ip=188.138.127.83&key=yt5&sver=3&signature=BA2A3FFC96E2293D323C51D2B81CBC624BEE67F8.8AA37A20430AFC2DF9593F7B7BE6C059F6FABFA9&nh=EAU&source=youtube&clen=189973457&upn=nJqT0IQGO3Q&keepalive=yes&mime=video%2Fmp4&gir=yes&requiressl=yes&lmt=1441096923306350&expire=1442234737&pl=23&mm=31&ipbits=0&mn=sn-4g57km7l&ms=au&itag=137&mt=1442212909&dur=784.599&mv=u&id=o-AEFMesPWyqjMlMFss63eX9TixOmbHJR8mfOenaeM7sXw&sparams=clen%2Cdur%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9406004%2C9407155%2C9407992%2C9408710%2C9409069%2C9410706%2C9415365%2C9415414%2C9415485%2C9415515%2C9416023%2C9416126%2C9416344%2C9416729%2C9417707%2C9418153%2C9418203%2C9418410%2C9418448%2C9418903%2C9419336%2C9419786%2C9419831%2C9420348%2C9420797&ratebypass=yes'
[download] Destination: CS -GO - Let's Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [1920x1080 - TrilluXe  CS -GO Channel ].f137.mp4
[download] 100% of 181.17MiB in 00:03
[debug] Invoking downloader on 'https://r13---sn-4g57km7l.googlevideo.com/videoplayback?id=5617f1cb1b0ab853&itag=140&source=youtube&requiressl=yes&mv=u&ms=au&mm=31&pl=23&mn=sn-4g57km7l&nh=EAU&ratebypass=yes&mime=audio/mp4&gir=yes&clen=12462475&lmt=1441096012711977&dur=784.648&key=dg_yt0&fexp=9406004,9407155,9407992,9408710,9409069,9410706,9415365,9415414,9415485,9415515,9416023,9416126,9416344,9416729,9417707,9418153,9418203,9418410,9418448,9418903,9419336,9419786,9419831,9420348,9420797&mt=1442212909&sver=3&upn=V9fi6-3UdHM&signature=6E4AC8F7B3D7BCC37420F9CE6FAB8756FEC7597F.6957B7C846DC54C712D98F2970362A7F959FB63A&ip=188.138.127.83&ipbits=0&expire=1442234737&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,mm,pl,mn,nh,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: CS -GO - Let's Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [NA - TrilluXe  CS -GO Channel ].f140.m4a
[download] 100% of 11.89MiB in 00:00
[ffmpeg] Merging formats into "CS -GO - Let's Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [1920x1080 - TrilluXe  CS -GO Channel ].mp4"
[debug] ffmpeg command line: avconv -y -i 'CS -GO - Let'"'"'s Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [1920x1080 - TrilluXe  CS -GO Channel ].f137.mp4' -i 'CS -GO - Let'"'"'s Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [NA - TrilluXe  CS -GO Channel ].f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'CS -GO - Let'"'"'s Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [1920x1080 - TrilluXe  CS -GO Channel ].temp.mp4'
Deleting original file CS -GO - Let's Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [1920x1080 - TrilluXe  CS -GO Channel ].f137.mp4 (pass -k to keep)
Deleting original file CS -GO - Let's Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [NA - TrilluXe  CS -GO Channel ].f140.m4a (pass -k to keep)
[ffmpeg] Adding metadata to 'CS -GO - Let's Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [1920x1080 - TrilluXe  CS -GO Channel ].mp4'
[debug] ffmpeg command line: avconv -y -i 'CS -GO - Let'"'"'s Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [1920x1080 - TrilluXe  CS -GO Channel ].mp4' -c copy -metadata 'comment=Time to waste some money again and unbox cases together! :D
Steam Group: http://steamcommunity.com/groups/trilluxe
Vulcun: https://vulcun.com/affiliate/TrilluXe

 Mojo: https://www.youtube.com/user/MojoOnPC
 HOUNGOUNGAGNE: https://www.youtube.com/user/jeffw8nc
 Chaimbo: https://www.youtube.com/user/pOtchVideos

 If you want to donate something, you can use this link:  http://tinyurl.com/Donate4Trill
 Where I buy my Games: https://www.g2a.com/r/trilluxe


 Links


 Steam Group: http://steamcommunity.com/groups/trilluxe
 Facebook: https://www.facebook.com/TrilluXe
 Twitter: https://twitter.com/TrilluXeYT
 German Channel: https://www.youtube.com/TrilluXeLIVE
 Steam Profile: http://steamcommunity.com/id/TrilluXe


 Partners


 Vulcun - http://bit.ly/1Ic3apI - $10.000.000 Fantasy eSports League. Up to $1000 Bonus with the Signup Code '"'"'TrilluXe'"'"'. CSGOCasino - http://csgocasino.net/ - Feel lucky and want to gamble for Skins? Be sure to check out CSGOCasino!


 My Gaming Setup


 Mouse: Logitech G400s - http://amzn.to/1DgKpOI
 Keyboard: Corsair Vengeance K95 - http://amzn.to/1zyM1pz
 Mousepad: SteelSeries QcK+ - http://amzn.to/1CMpXqH
 Gaming Monitor: BenQ XL2720Z - http://amzn.to/1v48j0I
 Mouse Bungee: EpicGear Skorpios - http://amzn.to/1zyMA2A
 Headset: Beyerdynamic MMX300 - http://amzn.to/1v47GEv
 Microphone: Rode NT-1A - http://amzn.to/1v47Xai
 Audio Interface: PreSonus Audiobox - http://amzn.to/1CMqkl5
 Soundcard: Asus Xonar Essence STX - http://amzn.to/1x1RiF2

 Second Monitor: Acer S242HLCBID - http://amzn.to/1IEqwXE
 Third Monitor: BenQ G2420HDBL - http://amzn.to/1GYnX0j


 Config/Crosshair/Viewmodel


 My Config: http://tinyurl.com/TrillConfig
 My Crosshair: http://tinyurl.com/TrillCrosshair
 My Viewmodel: http://tinyurl.com/TrillViewmodel


 Music


 SpongeBob Trap Remix (TheKrustyKrab) [TheRakeHornPipe] [ORIGINAL]
 BRODYQUEST
 Sad Violin' -metadata 'description=Time to waste some money again and unbox cases together! :D
Steam Group: http://steamcommunity.com/groups/trilluxe
Vulcun: https://vulcun.com/affiliate/TrilluXe

 Mojo: https://www.youtube.com/user/MojoOnPC
 HOUNGOUNGAGNE: https://www.youtube.com/user/jeffw8nc
 Chaimbo: https://www.youtube.com/user/pOtchVideos

 If you want to donate something, you can use this link:  http://tinyurl.com/Donate4Trill
 Where I buy my Games: https://www.g2a.com/r/trilluxe


 Links


 Steam Group: http://steamcommunity.com/groups/trilluxe
 Facebook: https://www.facebook.com/TrilluXe
 Twitter: https://twitter.com/TrilluXeYT
 German Channel: https://www.youtube.com/TrilluXeLIVE
 Steam Profile: http://steamcommunity.com/id/TrilluXe


 Partners


 Vulcun - http://bit.ly/1Ic3apI - $10.000.000 Fantasy eSports League. Up to $1000 Bonus with the Signup Code '"'"'TrilluXe'"'"'. CSGOCasino - http://csgocasino.net/ - Feel lucky and want to gamble for Skins? Be sure to check out CSGOCasino!


 My Gaming Setup


 Mouse: Logitech G400s - http://amzn.to/1DgKpOI
 Keyboard: Corsair Vengeance K95 - http://amzn.to/1zyM1pz
 Mousepad: SteelSeries QcK+ - http://amzn.to/1CMpXqH
 Gaming Monitor: BenQ XL2720Z - http://amzn.to/1v48j0I
 Mouse Bungee: EpicGear Skorpios - http://amzn.to/1zyMA2A
 Headset: Beyerdynamic MMX300 - http://amzn.to/1v47GEv
 Microphone: Rode NT-1A - http://amzn.to/1v47Xai
 Audio Interface: PreSonus Audiobox - http://amzn.to/1CMqkl5
 Soundcard: Asus Xonar Essence STX - http://amzn.to/1x1RiF2

 Second Monitor: Acer S242HLCBID - http://amzn.to/1IEqwXE
 Third Monitor: BenQ G2420HDBL - http://amzn.to/1GYnX0j


 Config/Crosshair/Viewmodel


 My Config: http://tinyurl.com/TrillConfig
 My Crosshair: http://tinyurl.com/TrillCrosshair
 My Viewmodel: http://tinyurl.com/TrillViewmodel


 Music


 SpongeBob Trap Remix (TheKrustyKrab) [TheRakeHornPipe] [ORIGINAL]
 BRODYQUEST
 Sad Violin' -metadata 'artist=TrilluXe  CS:GO Channel ' -metadata 'title=CS:GO - Let'"'"'s Unbox Together #3 - w/ Mojo, HOUNGOUNGAGNE, & Chaimbo' -metadata date=20150830 -metadata 'purl=https://www.youtube.com/watch?v=VhfxyxsKuFM' 'CS -GO - Let'"'"'s Unbox Together #3 - w_ Mojo, HOUNGOUNGAGNE, & Chaimbo - [1920x1080 - TrilluXe  CS -GO Channel ].temp.mp4'
########################################################################################
root@mo-server-on:~#

**Comment by WeWin55** [comment]
Its fixed now, dont know how, because ive done nothing.
But thanks anyway guys:)
