### ISSUE TITLE
ERROR: audio conversion failed: Error opening filters!

### ISSUE THREAD

**Issue by bealparslan** [rg3/youtube-dl#6862]
<b>How can I solve it? Thx</b>

<pre>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--rm-cache-dir', u'--no-cache-dir', u'-o', u'/root/%(id)s.%(ext)s', u'https://www.youtube.com/watch?v=SAWl2DNx1lE', u'--extract-audio', u'--audio-format', u'mp3', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.6.6 - Linux-2.6.32-504.30.3.el6.x86_64-x86_64-with-centos-6.6-Final
[debug] exe versions: ffmpeg 2.2.1, ffprobe 2.2.1
[debug] Proxy map: {}
Cache is disabled (Did you combine --no-cache-dir and --rm-cache-dir?)
[youtube] SAWl2DNx1lE: Downloading webpage
[youtube] SAWl2DNx1lE: Downloading video info webpage
[youtube] SAWl2DNx1lE: Extracting video information
[youtube] SAWl2DNx1lE: Downloading DASH manifest
[youtube] SAWl2DNx1lE: Downloading DASH manifest
[debug] Invoking downloader on u'https://r11---sn-25ge7ned.googlevideo.com/videoplayback?ipbits=0&pl=20&clen=3221813&requiressl=yes&mime=audio%2Fwebm&expire=1442296150&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&initcwndbps=3071250&mm=31&signature=3408372619423648922DEE8F4001E36F92E0C09D.1E0E594C94091C9DADE0B9B85A9621BDEA597895&mn=sn-25ge7ned&key=yt5&ip=MY_SERVER_IP&dur=208.581&keepalive=yes&sver=3&source=youtube&lmt=1441886775033146&id=o-AMqcuG8rGCcScBj31nfiTEwWMC-MU6soIV1ceYkzWt-F&ms=au&mt=1442274514&mv=m&fexp=9406990%2C9408710%2C9409069%2C9415365%2C9415485%2C9416023%2C9416126%2C9417707%2C9418153%2C9418448%2C9420348&upn=Cfe9cpW3MZ4&itag=251&gir=yes&ratebypass=yes'
[download] /root/SAWl2DNx1lE.webm has already been downloaded
[download] 100% of 3.07MiB
[debug] ffmpeg command line: ffprobe -show_streams /root/SAWl2DNx1lE.webm
[ffmpeg] Destination: /root/SAWl2DNx1lE.mp3
[debug] ffmpeg command line: ffmpeg -y -i /root/SAWl2DNx1lE.webm -vn -acodec libmp3lame -q:a 5 /root/SAWl2DNx1lE.mp3
ERROR: audio conversion failed: Error opening filters!
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1704, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 276, in run
    'audio conversion failed: ' + e.msg)
PostProcessingError
</pre>

**Comment by dstftw** [comment]
Update ffmpeg.

**Comment by mrkapqa** [comment]
i updated today ffmpeg on wheezy , but am still getting the same error

ffmpeg version 1.0.10 Copyright (c) 2000-2014 the FFmpeg developers
  built on Jul 12 2017 14:23:37 with gcc 4.7 (Debian 4.7.2-5)
  configuration: --enable-gpl --enable-nonfree --enable-libfaac --enable-libgsm --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libxvid --enable-zlib --enable-postproc --enable-swscale --enable-pthreads --enable-x11grab --enable-libdc1394 --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb                                                      
  libavutil      51. 73.101 / 51. 73.101                                        
  libavcodec     54. 59.100 / 54. 59.100                                        
  libavformat    54. 29.104 / 54. 29.104                                        
  libavdevice    54.  2.101 / 54.  2.101                                        
  libavfilter     3. 17.100 /  3. 17.100                                        
  libswscale      2.  1.101 /  2.  1.101                                        
  libswresample   0. 15.100 /  0. 15.100                                        
  libpostproc    52.  0.100 / 52.  0.100                                        
Hyper fast Audio and Video encoder                                              
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...                                       



rich@debian:~$ youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 https://www.youtube.com/watch?v=qDQxf_bpZRE&feature=youtu.be verbose             
[1] 23887                                                                       
bash: verbose: Kommando nicht gefunden.                                         
rich@debian:~$ [youtube] qDQxf_bpZRE: Downloading webpage                       
[youtube] qDQxf_bpZRE: Downloading video info webpage                           
[youtube] qDQxf_bpZRE: Extracting video information                             
[youtube] qDQxf_bpZRE: Downloading MPD manifest                                 
[download] KenFM am Telefon - Willy Wimmer über die Wiedereinführung Deutscher Grenzkontrollen-qDQxf_bpZRE.webm has already been downloaded
[download] 100% of 21.01MiB
[ffmpeg] Destination: KenFM am Telefon - Willy Wimmer über die Wiedereinführung Deutscher Grenzkontrollen-qDQxf_bpZRE.mp3
**ERROR: audio conversion failed: Error opening filters!**

**Comment by mrkapqa** [comment]
deleted

**Comment by siddht1** [comment]
@mrkapqa  I dont really know wheter debian actually still compiles ffmpeg or its supported.So my guess would be to remove ffmpeg once and instead try avconv.Use this  `sudo apt-get install libav-tools` to install avconv. Your ffmpeg is actually too old.  my ffmpeg on my lm is  `youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.09
[debug] Python version 2.7.12 - Linux-4.12.0-041200-lowlatency-x86_64-with-LinuxMint-18.2-sonya
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
`


I actually have no idea wheter your repo is frozen one or not.I wont recommend anything yet as I use LM a derivative of ubuntu.   So instead compile it youself or use sid repo for this one only

**Comment by siddht1** [comment]
@mrkapqa  deleted  or you meant purge of ffmpeg

**Comment by mrkapqa** [comment]
i am compiling missing libraries for ffmpeg, eg libmp3lame, libx264, hopefully enables it. i want to use ffmpeg, thanks
