### ISSUE TITLE
Request: Auto download a particular youtube channel's videos as they are uploaded 

### ISSUE THREAD

**Issue by BudworthFugBags** [rg3/youtube-dl#6863]
Is it possible to have a certain youtube channel's videos automatically downloaded when they are uploaded? I know youtube has a feature that automatically notifies you if a particular channel uploads a video, I was wondering if there was some way to use those notifications to automatically trigger a download of said video.  Sorry if this question has been submitted before, I tried my best to make sure it hasn’t been submitted in the past before I posted this request.

**Comment by jaimeMF** [comment]
I think this is out of scope for youtube-dl. youtube-dl downloads videos from given url, so you can write a small program that listens to this notification an run youtube-dl with the appropriate arguments.
