### ISSUE TITLE
ERROR: Unable to extract iframe

### ISSUE THREAD

**Issue by n1c0la** [rg3/youtube-dl#6866]
$ youtube-dl http://www.report.rai.it/dl/Report/puntata/ContentItem-86a1bd15-9fae-4c9c-a32e-03ec1e6dd735.html

$ youtube-dl -U
youtube-dl is up-to-date (2015.09.09)

platform: Mac OS X Darwin Kernel Version 12.6.0

**Comment by n1c0la** [comment]
$ youtube-dl --verbose http://www.report.rai.it/dl/Report/puntata/ContentItem-0c7a664b-d0f4-4b2c-8835-3f82e46f433e.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.report.rai.it/dl/Report/puntata/ContentItem-0c7a664b-d0f4-4b2c-8835-3f82e46f433e.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.10 - Darwin-12.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 2.8, ffprobe 2.8, rtmpdump 2.4
[debug] Proxy map: {}
[Rai] 0c7a664b-d0f4-4b2c-8835-3f82e46f433e: Downloading webpage
ERROR: Unable to extract iframe; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 95, in _real_extract
    webpage, 'iframe')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 575, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version. Thanks for the report.
