### ISSUE TITLE
Pornhub - HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by JohnMkaine** [rg3/youtube-dl#6868]
Pornhub link not supported : 

youtube-dl -t http://fr.pornhub.com/view_video.php?viewkey=ph55ca2f9760862
[generic] view_video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] view_video: Downloading webpage
[generic] view_video: Extracting information
ERROR: unable to download video data: HTTP Error 404: Not Found

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version. Thanks for the report.
