### ISSUE TITLE
[Q] How to disable a particular extractor?

### ISSUE THREAD

**Issue by nodiscc** [rg3/youtube-dl#6871]
Hi,

I wrote a simple tool to archive bookmark sets from bookmarking services/apps like [Shaarli](https://github.com/shaarli/shaarli) (delicious-like). It batch downloads links contents, and run youtube-dl on links which are specifically tagged `video`,`audio`... The tools works well with a few quirks, one of which is related to youtube-dl:

In my example bookmark set, there is a link to https://soundcloud.com/sjel-1. youtube-dl runs for this link since it is tagged `music`, and this is parsed through the `soundcloud:user` extractor. I expect my tool not to download entire soundcloud/vimeo/youtube channels even if I bookmarked them (unless the user specifies so). The simplest way I can imagine for this particular link is disabling the `soundcloud:user` extractor.

Is there a way to disable some extractors via config file/args? Right now it tends to download unwanted files. Or do I really have to blacklist URLs in my tool?

Thanks in advance

**Comment by dstftw** [comment]
There is no way to disable particular extractor. You can however disable sites with adults content `--age-limit` option.
