### ISSUE TITLE
Missing 4 seconds at end of Youtube Video

### ISSUE THREAD

**Issue by aldoilsant** [rg3/youtube-dl#6873]
When downloading this video: 

https://www.youtube.com/watch?v=iyzCccndc2w

There are 4 seconds missing at the end of the received file (online video 2:41, downloaded video 2:37). 

I have also seen slight variations in other videos. Can you help?

Here is a complete trace: 

Aldos-MacBook-Pro-2:~ aldoilsant$ /tmp/ytdl -v https://www.youtube.com/watch?v=iyzCccndc2w
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=iyzCccndc2w']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] iyzCccndc2w: Downloading webpage
[youtube] iyzCccndc2w: Downloading video info webpage
[youtube] iyzCccndc2w: Extracting video information
[youtube] {43} signature length 46.43, html5 player new-en_US-vflhlPTtB
[youtube] {18} signature length 46.43, html5 player new-en_US-vflhlPTtB
[youtube] {5} signature length 46.43, html5 player new-en_US-vflhlPTtB
[youtube] {36} signature length 46.43, html5 player new-en_US-vflhlPTtB
[youtube] {17} signature length 46.43, html5 player new-en_US-vflhlPTtB
[youtube] {13} signature length 46.43, html5 player new-en_US-vflhlPTtB
[youtube] {133} signature length 46.43, html5 player new-en_US-vflhlPTtB
[youtube] {242} signature length 46.43, html5 player new-en_US-vflhlPTtB
[youtube] {243} signature length 46.43, html5 player new-en_US-vflhlPTtB
[youtube] {160} signature length 46.43, html5 player new-en_US-vflhlPTtB
[youtube] {140} signature length 46.43, html5 player new-en_US-vflhlPTtB
[youtube] {171} signature length 46.43, html5 player new-en_US-vflhlPTtB
[youtube] iyzCccndc2w: Downloading DASH manifest
[debug] Invoking downloader on u'https://r12---sn-h5q7dn7d.googlevideo.com/videoplayback?expire=1442375395&ratebypass=yes&ipbits=0&requiressl=yes&mime=video%2Fmp4&lmt=1431846170146158&nh=IgpwcjAxLm1hZDA2KgkxMjcuMC4wLjE&initcwndbps=1125000&dur=161.959&sver=3&source=youtube&pl=16&id=o-ADxy_8SSUna5T7-Y75Msj_30Wp4dI6VunSj5anM-yyF6&ms=au&mt=1442353673&mv=m&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mn=sn-h5q7dn7d&key=yt5&ip=88.12.20.221&upn=3xPuq-N-ctU&itag=18&fexp=9408710%2C9409069%2C9415365%2C9415485%2C9416023%2C9416126%2C9417707%2C9418153%2C9418448%2C9420348&mm=31&signature=88C8584646B5B9880868F1B4A4EDEF1FD7AD5BD0.39FE0199CBC99F21D745431536655A73B16E79ED'
[download] Destination: The Drifters - Under the Boardwalk-iyzCccndc2w.mp4
[download] 100% of 3.20MiB in 00:05

**Comment by dstftw** [comment]
That's what YouTube serves. Download different format with `-f`, e.g. `-f 141`. `-F` for the list of formats available.
