### ISSUE TITLE
Using ':' in -o breaks ffmpeg

### ISSUE THREAD

**Issue by paulguy** [rg3/youtube-dl#6874]
I was trying to download a full playlist from youtube, and I wanted the videos numbered so I could watch in order, so I used:
youtube-dl --playlist-reverse -f bestvideo+171/bestvideo+140 -o "%(autonumber)s: %(title)s-%(id)s.%(ext)s" https://www.youtube.com/playlist?list=PL26B36130624FCAF5

The unfortunate side effect is that ffmpeg believes that the filename is specifying a protocol.  I could just use a different character, but I was able to fix it by modifying FFmpegPostProcessor.run_ffmpeg_multiple_files and simply prepending 'file:' to each input_path and the out_path.

**Comment by yan12125** [comment]
```input_path``` can be remote URLs. (for example M3U8 URLs)

**Comment by paulguy** [comment]
Well, obviously considerations like that are why I didn't make a pull request, but simply said what I did to fix it.  I'm just saying, if it's a file, it should be prefixed with file: so ffmpeg knows it's a file, and you don't get weird issues with filenames like that.

**Comment by yan12125** [comment]
Oh prepending the filename with './' works. For example:

```
youtube-dl --playlist-reverse -f bestvideo+171/bestvideo+140 -o "./%(autonumber)s: %(title)s-%(id)s.%(ext)s" "https://www.youtube.com/playlist?list=PL26B36130624FCAF5"
```

**Comment by paulguy** [comment]
That isn't really obvious when all you get is "Protocol not found" without searching for it, and there's no real indicator that's even coming from ffmpeg.  I had to dig around to find out even that much, then find out that it was because of the colon.  It'd make more sense if it just worked as expected, and it's not like it's something that can't be done.

**Comment by rg3** [comment]
I tend to agree with you here. If you create a script that calls "cp"
with user or external information you're expected to use "--" to
separate the options from the positional parameters.

If ffmpeg uses a proto:object syntax in the output file, the program
should add "file://" to prevent these problems.

My two cents.

**Comment by paulguy** [comment]
It does have an explicit protocol syntax, which will force the specific protocol.
http://www.ffmpeg.org/ffmpeg-protocols.html

**Comment by jaimeMF** [comment]
Thanks for the report, it will use the `file:` protocol in the next version.
