### ISSUE TITLE
Symantec Endpoint Protection always warning when run youtube-dl

### ISSUE THREAD

**Issue by kgp700** [rg3/youtube-dl#6875]
Symantec Endpoint Protection always warning when run youtube-dl.exe
please solve this problem

please see the screenshot : 
![si](https://cloud.githubusercontent.com/assets/888065/9896242/1875fdd0-5c74-11e5-866c-9552c22df050.png)

**Comment by yan12125** [comment]
If your file is downloaded from http://rg3.github.io/youtube-dl/download.html and the SHA256 checksum of ```youtube-dl.exe``` is correct (5db16a5288440cbdb9c66cbfedba70992dc6c9c3e634bc187987f037d0d28038), then it's a false alert. Please report it to Symantec.

**Comment by yan12125** [comment]
Here's the scan report of https://yt-dl.org/downloads/2015.09.09/youtube-dl.exe:
https://www.virustotal.com/en/file/5db16a5288440cbdb9c66cbfedba70992dc6c9c3e634bc187987f037d0d28038/analysis/
