### ISSUE TITLE
vk.com not working

### ISSUE THREAD

**Issue by yousufalim** [rg3/youtube-dl#6876]
downloads from vk.com not working.

[vk] -84761705_171276241: Downloading webpage
[debug] Invoking downloader on u'https://cs542309.vk.me/7/u320973199/videos/e5e3a56a4e.720.mp4?extra=GUS4rKmI4KJCKe2ktsFxhFDIju_BmqO3fjsiSTuhzcQJ1ZwqxxEEQPUIgoJvMBnIXiXWTtnliNrrfuLwPcs7SSwfTgy8UMbQil04TERe'
[download] Destination: Ella Hughes, Ariana Brown (Bi-Sexual Besties - Now First Time Lesbian Lovers)[14.09.2015,Porno,Sex,Ð›ÐµÑÐ±Ð¸ÑÐ½ÐºÐ¸,ÐŸÐ¾Ñ€Ð½Ð¾,HD 720p]-171276241.mp4
[debug] aria2c command line: aria2c -c --async-dns=false --max-connection-per-server=16 --out 'Ella Hughes, Ariana Brown (Bi-Sexual Besties - Now First Time Lesbian Lovers)[14.09.2015,Porno,Sex,Ð›ÐµÑÐ±Ð¸ÑÐ½ÐºÐ¸,ÐŸÐ¾Ñ€Ð½Ð¾,HD 720p]-171276241.mp4.part' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' --header 'Accept-Language: en-us,en;q=0.5' --header 'Accept-Encoding: gzip, deflate' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36' --check-certificate=true -- 'https://cs542309.vk.me/7/u320973199/videos/e5e3a56a4e.720.mp4?extra=GUS4rKmI4KJCKe2ktsFxhFDIju_BmqO3fjsiSTuhzcQJ1ZwqxxEEQPUIgoJvMBnIXiXWTtnliNrrfuLwPcs7SSwfTgy8UMbQil04TERe'
ERROR: unable to download video
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1658, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 671, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 717, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1328, in process_video_result
    self.process_info(new_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1595, in process_info
    raise UnavailableVideoError(err)
UnavailableVideoError: [Errno 2] No such file or directory

**Comment by yan12125** [comment]
Which URL are you trying to download?

**Comment by yousufalim** [comment]
tried multiple URLs, you may use this as an example.
http://vk.com/video-84761705_171277495

**Comment by yan12125** [comment]
This video requires login. Do you have publicly available examples?

**Comment by yousufalim** [comment]
user: admin@pixup.us
pass: testpass123

**Comment by yan12125** [comment]
Well, vk.com asks me to enter a verification code due to login from an unusual place.

**Comment by yousufalim** [comment]
hmmm what is it asking for

**Comment by yousufalim** [comment]
+923158404908 is the code.... you have to enter part of it i think, enter whatever part is suitable

**Comment by yan12125** [comment]
OK I've copied those numbers. Please remove them from this page. Github is a public place.

**Comment by yousufalim** [comment]
removed the pass and the code

**Comment by yan12125** [comment]
Got no errors for me. Could you try again with the following command?
```
youtube-dl --ignore-config --verbose --write-pages --username USERNAME --password PASSWORD "http://vk.com/video-84761705_171277495"
```
And paste/upload all *.dump files.

**Comment by yousufalim** [comment]
wierd... its the link is working now... let me check a few other links

**Comment by yousufalim** [comment]
closing this.... sorry for the time wasting i caused... seems to be in order
