### ISSUE TITLE
cant download video from iqiyi , Error

### ISSUE THREAD

**Issue by polarstars** [rg3/youtube-dl#6878]
[iqiyi] temp_id: download video page
[iqiyi] 9a2aaf09f9d1ca1bebb8d90adb9e078b: Downloading JSON metadata
ERROR: Unable to load data. Error code: A000001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
iQiyi extractor is fixed now. You can wait for the next version or try the latest git version.
Note that iQiyi.com changes its key quite often and it's possible youtube-dl will be broken again. Please open a new issue if that occurs.
