### ISSUE TITLE
Youporn is broken

### ISSUE THREAD

**Issue by whiskycharlie** [rg3/youtube-dl#6888]
python ./youtube-dl --verbose -j http://www.youporn.com/watch/11676707/the-stripper-scott-ward/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-j', u'http://www.youporn.com/watch/11676707/the-stripper-scott-ward/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.6 - Linux-3.13.0-63-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-74748-gbaeb8f5, ffprobe N-74748-gbaeb8f5
[debug] Proxy map: {}
ERROR: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/youtube_dl/extractor/common.py", line 282, in extract
    return self._real_extract(url)
  File "/youtube_dl/extractor/youporn.py", line 52, in _real_extract
    webpage, 'JSON parameters')
  File "/youtube_dl/extractor/common.py", line 564, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by fzg** [comment]
Confirmed, same exception.

[debug] Command-line args: [u'http://www.youporn.com/watch/9912017/sexe-alcool-et-vie-privee/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.28
[debug] Python version 2.7.10 - Linux-4.0.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 2.7.2-2, avprobe 2.7.2-2, ffmpeg 2.7.2-2, ffprobe 2.7.2-2, rtmpdump 2.4

**Comment by error39** [comment]
I worked out a fix for the extractor, how to submit?

**Comment by dstftw** [comment]
Open a pull request.

**Comment by error39** [comment]
I'm not very familiar with git I'm afraid.
I have a clone of the repository on my machine which now contains the edited extractor file.
Some directions on how and where to open a pull request?
Thanks!

**Comment by error39** [comment]
Or should I create a patch file and attach it to another comment?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#adding-support-for-a-new-site

**Comment by error39** [comment]
Thanks Sergey.

**Comment by error39** [comment]
Almost there, just seem to be doing something wrong when trying to submit the fix..

The steps:

$ git clone git@github.com:error39/youtube-dl.git
$ cd youtube-dl
$ nano youtube_dl/extractor/youporn.py #edited and saved the extractor file
$ git add youtube_dl/extractor/youporn.py
$ git commit -m '[youporn] Fixed the extractor by simplifying some parts'
[master 0fe9546] [youporn] Fixed the extractor by simplifying some parts
 1 files changed, 5 insertions(+), 27 deletions(-)
$ git push origin youporn
error: src refspec youporn does not match any.
error: failed to push some refs to 'git@github.com:error39/youtube-dl.git'

How should I do this? Instructions are for adding a new extractor, and therefore creating a new branch, is this necessary for editing an existing extractor too?

**Comment by dstftw** [comment]
Creating a branch is idiomatic for any changes.

**Comment by error39** [comment]
Got it working again,made a pull request, now wait for someone to review and possibly merge the fix.
