### ISSUE TITLE
ERROR: Unable to extract sts

### ISSUE THREAD

**Issue by IAmNotImportant** [rg3/youtube-dl#6890]
Hi everyone. I got bug and because it says I should post it here, I'm posting it.
(Ignore that video itself, pls)
I've reinstalled youtube-dl using "sudo aptitude reinstall youtube-dl", but it remained the same

b7@debian:~$ youtube-dl --verbose https://www.youtube.com/watch?v=2svVkkNuSq0
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=2svVkkNuSq0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
[debug] Proxy map: {}
[youtube] Setting language
[youtube] 2svVkkNuSq0: Downloading webpage
[youtube] 2svVkkNuSq0: Downloading video info webpage
[youtube] Confirming age
ERROR: Unable to extract sts; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 623, in _real_extract
    r'"sts"\s*:\s*(\d+)', video_webpage, 'sts'),
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract sts; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

youtube-dl -U says:
"It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update."

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by IAmNotImportant** [comment]
I feel dumb now. Thanks.
