### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by holaznog** [rg3/youtube-dl#6891]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.mitele.es/deportes/eurobasket-2015/semifinal/serbia-lituania/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.10.30
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[mitele.es] serbia-lituania: Downloading webpage
ERROR: Unable to extract embed data; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 533, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 198, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mitele.py", line 39, in _real_extract
    flags=re.DOTALL
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 432, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract embed data; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Thanks!!!!!!

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version. You are also using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
