### ISSUE TITLE
[youtube:history] It can wipe the watch history list

### ISSUE THREAD

**Issue by asparago** [rg3/youtube-dl#6893]
I was trying to get my YouTube Watch History. I needed only the file IDs, not the content. 

So I used: 

h@debian:~/ythistory$ youtube-dl -u myuser -p mypass https://www.youtube.com/feed/history --skip-download >> ytlist.txt

It successfully worked until there was an unavailable video, the 428th out of 8713... The download process was aborted. 

So I tried again adding the parameter "--ignore-errors", but only 4 files were listed. I checked on my YouTube account and the Watch History was empty. That was really sick. 

I don't know why it happened, is this a bug of the program? 

Also, is there a way to restore the watch history? 

Are IDs saved in a temporary file which I can restore in some way?

**Comment by jaimeMF** [comment]
As far as I know youtube-dl can't modify the Watch History list because we just extract the video urls from the feed, but I haven't tested it in a while. 
Maybe you accidentally deleted it in the browser interface?

> Also, is there a way to restore the watch history? 

Probably no.

> Are IDs saved in a temporary file which I can restore in some way?
youtube-dl doesn't store any info.

**Comment by asparago** [comment]
>Maybe you accidentally deleted it in the browser interface?

No way. I didn't open the browser while trying the program from shell.

Something could have happened it's a sort of "flood protection" by Google, because I made a lot of tries with different parameters.

**Comment by jaimeMF** [comment]
I have dowwloaded a history with 110 videos and it didn't wiped it, @dstftw how many videos did you have?

**Comment by dstftw** [comment]
I had 441 videos and started it with command `youtube-dl https://www.youtube.com/feed/history -u email -p password --skip-download`, then interrupted on video no. 313. After that it has wiped all videos apart from 24 latest.

**Comment by dstftw** [comment]
After I've watched another ~50 videos my whole history is back now. So this looks like an issue on YouTube side.

**Comment by asparago** [comment]
Today it's back to me, too. 

It's a YouTube problem (or flood protection?).
