### ISSUE TITLE
Dumping JSON for playlists returns invalid syntax

### ISSUE THREAD

**Issue by steebchen** [rg3/youtube-dl#6894]
When calling youtube-dl with the --dump-json argument and a playlist, like this:

    youtube-dl --dump-json https://www.youtube.com/watch?v=5Fjjgjcvj24&list=PLvMgpveoV8oRvM_kBZULuPn5wlQkUjPth

then it returns invalid json, which looks like that:

    { "upload_date":"20130922", .. } { "upload_date":"20130922", .. } { "upload_date":"20130922", .. } 

I can't JSON.parse() it, because first, there is no comma between each element, and second, it has to be an array, so it should like that:

    [{ "upload_date":"20130922", .. }, { "upload_date":"20130922", .. }, { "upload_date":"20130922", .. } ]

Or am I just missing something?
I'm using the latest version on npm.

As a workaround, you have to use --dump-single-json or -J to get a correct result.

**Comment by yan12125** [comment]
How about: 
```
string_from_youtube_dl.split('\n').map(JSON.parse)
```
Given you're using Javascript.

**Comment by dstftw** [comment]
This is expected behavior. `--dump-json` outputs JSON for each video separately.
