### ISSUE TITLE
arte.tv:creative - "Unable to extract json vp url"

### ISSUE THREAD

**Issue by lobotomi51** [rg3/youtube-dl#6895]
Hello,
youtube-dl seems to be unable to find the json url for this page : 
youtube-dl http://creative.arte.tv/fr/episode/osmosis

Here is the log in verbose mode :
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://creative.arte.tv/fr/episode/osmosis', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.9 - Linux-3.19.0-22-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[arte.tv:creative] episode/osmosis: Downloading webpage
ERROR: Unable to extract json vp url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/arte.py", line 75, in _real_extract
    return self._extract_from_webpage(webpage, video_id, lang)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/arte.py", line 80, in _extract_from_webpage
    webpage, 'json vp url')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 584, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 575, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract json vp url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Still it works fine on other pages of the same site, like this one :
http://creative.arte.tv/fr/episode/tu-mourras-moins-bete-130-la-peur-en-avion

I'm using the latest version of youtube-dl :
youtube-dl --version 
2015.09.09

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version. Thanks for the report.

**Comment by lobotomi51** [comment]
Hi, thanks for the fix and the overall great work.
