### ISSUE TITLE
maybe a bug?

### ISSUE THREAD

**Issue by p0we7** [rg3/youtube-dl#6896]
WARNING: [youtube] IUJhCTyH5l4: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by p0we7** [comment]
But the bug can't reproduce
