### ISSUE TITLE
[TMZArticle] ERROR: Unable to extract embedded video info

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#6898]
URL: http://www.tmz.com/2015/09/19/patti-labelle-concert-fan-stripping-kicked-out-nicki-minaj/

C:>youtube-dl -v "http://www.tmz.com/2015/09/19/patti-labelle-concert-fan-strip
ping-kicked-out-nicki-minaj/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.tmz.com/2015/09/19/patti-labelle
-concert-fan-stripping-kicked-out-nicki-minaj/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[TMZArticle] patti-labelle-concert-fan-stripping-kicked-out-nicki-minaj: Downloa
ding webpage
ERROR: Unable to extract embedded video info; please report this issue on https:
//yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -
U  to update. Be sure to call youtube-dl with the --verbose flag and include its
 complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 660, in extract_info
  File "youtube_dl\extractor\common.pyo", line 287, in extract
  File "youtube_dl\extractor\tmz.pyo", line 53, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 584, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 575, in _search_regex
RegexNotFoundError: Unable to extract embedded video info; please report this is
sue on https://yt-dl.org/bug . Make sure you are using the latest version; type
 youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag an
d include its complete output.

Direct link to video: http://www.tmz.com/videos/0_jerz7s3l    does work.

Thanks
Ringo

**Comment by RingoTheDog** [comment]
FWIW...came across another example today:
http://www.tmz.com/2016/01/28/adam-silver-sting-drake-blake-griffin/

**Comment by yan12125** [comment]
This shold be fixed in the next version (5d47b38)
