### ISSUE TITLE
Support AES encryption in native HLS downloader

### ISSUE THREAD

**Issue by fb39ca4** [rg3/youtube-dl#6899]
I am trying to get an extractor for daisuki.net working, but the M3U8 playlists have encryption keys.

Example:

    #EXTM3U
    #EXT-X-TARGETDURATION:10
    #EXT-X-ALLOW-CACHE:YES
    #EXT-X-KEY:METHOD=AES-128,URI="https://bngn-vh.akamaihd.net/i/43383936/35470338/smil/CA/00020/356591040701399.smil/crypt.key?null=&id=AgCAvZDZFzu8D7zB%2fVWWIHWJSVAxHhHvQvX7rIh3HuHom+D7tYdUh3WhlOWdnZuvwpxzfRMVvdeH8w%3d%3d"
    #EXT-X-PLAYLIST-TYPE:VOD
    #EXT-X-VERSION:3
    #EXT-X-MEDIA-SEQUENCE:1
    #EXTINF:10.000,
    http://bngn-vh.akamaihd.net/i/43383936/35470338/smil/CA/00020/356591040701399.smil/segment1_1000000_av.ts?null=&id=AgCAvZDZFzu8D7zB%2fVWWIHWJSVAxHhHvQvX7rIh3HuHom+D7tYdUh3WhlOWdnZuvwpxzfRMVvdeH8w%3d%3d
    #EXTINF:10.000,
    http://bngn-vh.akamaihd.net/i/43383936/35470338/smil/CA/00020/356591040701399.smil/segment2_1000000_av.ts?null=&id=AgCAvZDZFzu8D7zB%2fVWWIHWJSVAxHhHvQvX7rIh3HuHom+D7tYdUh3WhlOWdnZuvwpxzfRMVvdeH8w%3d%3d
    #EXTINF:10.000,
    http://bngn-vh.akamaihd.net/i/43383936/35470338/smil/CA/00020/356591040701399.smil/segment3_1000000_av.ts?null=&id=AgCAvZDZFzu8D7zB%2fVWWIHWJSVAxHhHvQvX7rIh3HuHom+D7tYdUh3WhlOWdnZuvwpxzfRMVvdeH8w%3d%3d
    ...

**Comment by jaimeMF** [comment]
There's a proposed implementation in #5882.
Note that ffmpeg should be able to download it (although it doesn't support ressuming)

**Comment by fb39ca4** [comment]
Haven't been able to pass cookies to ffmpeg successfully, which are needed for Daisuki.

**Comment by remitamine** [comment]
you can use the code in this commit https://github.com/remitamine/youtube-dl/commit/801cfb8fa9e221d2e729d8b0d44446fe4281df03 to be able to pass cookies to ffmpeg.

**Comment by remitamine** [comment]
> Haven't been able to pass cookies to ffmpeg successfully, which are needed for Daisuki.
it should work using the master branch (https://github.com/rg3/youtube-dl/pull/6267#issuecomment-142416339)

**Comment by yan12125** [comment]
Thanks to @remitamine (#8201), AES decryption will be supported in the next version.
