### ISSUE TITLE
youtube-dl tries to download video and audio separately

### ISSUE THREAD

**Issue by Sheldan** [rg3/youtube-dl#6900]
Before I always used both the format to download a video (audio + video). For some reason youtube-dl does not change this behavior. If I execute it with a straightforward argument, it still tries to download both formats and merge them afterwards. 

user@raspberry database$ youtube-dl 9DA9kvCfmU0 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'9DA9kvCfmU0', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.28
[debug] Python version 2.7.8 - Linux-3.12.26-1.20140808git4ab8abb.rpfr20.armv6hl.bcm2708-armv6l-with-fedora-20-Heisenbug
[debug] exe versions: ffmpeg N-68894-gd2838f0, ffprobe N-68894-gd2838f0
[debug] Proxy map: {}
[youtube] 9DA9kvCfmU0: Downloading webpage
[youtube] 9DA9kvCfmU0: Downloading video info webpage
[youtube] 9DA9kvCfmU0: Extracting video information
[youtube] 9DA9kvCfmU0: Downloading DASH manifest
[youtube] 9DA9kvCfmU0: Downloading DASH manifest
[debug] Invoking downloader on 'https://r5---sn-uxax3vh50nugp5-8pxe.googlevideo.com/videoplayback?id=f4303d92f09f994d&itag=302&source=youtube&requiressl=yes&mn=sn-uxax3vh50nugp5-8pxe&mm=31&ms=au&mv=m&pl=18&pcm2cms=yes&ratebypass=yes&mime=video/webm&gir=yes&clen=386215301&lmt=1442343846397019&dur=1508.267&key=dg_yt0&mt=1442696064&upn=dYZnE1JZRvo&sver=3&signature=5A717A1FACB0300AA166F33CFF164A5BA10F722B.82DA7CC591C1DEAEE2772BAD5BA30DC1B9D5009E&fexp=9406984,9408710,9409069,9415365,9415485,9416023,9416126,9417707,9418153,9418448,9420348,9421013&ip=178.191.222.77&ipbits=0&expire=1442717729&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,mm,ms,mv,pl,pcm2cms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: 8 Mindcrackers to Die (S3E3) - All Cool-9DA9kvCfmU0.f302.webm
[download]   0.1% of 368.32MiB at 226.25KiB/s ETA 27:45^C
ERROR: Interrupted by user

I tried the same on a different version (2015.09.09), but the result was still the same. I am not sure whats going wrong, as I used it without defining and merging formats before. I do not think, that there is some hidden config, as it states it has no user or system config to use.

**Comment by dstftw** [comment]
This is expected behavior. Read last two paragraphs of [this FAQ entry](https://github.com/rg3/youtube-dl#format-selection).

**Comment by Sheldan** [comment]
Why is it expected behavior to merge the two files? Wasn't it before, that it will download the best version of the full video (audio + video)?

**Comment by dstftw** [comment]
Video and audio streams in best single file media usually has lower quality that video-only and audio-only DASH streams. Therefore best overall quality media is only possible with merging.

**Comment by Sheldan** [comment]
Yeah, if I retrieve the formats with -F it says 
"22           mp4        1280x720   hd720 ,  mp4a.40.2, avc1.64001F (best)"
along other formats and as far as I know, youtube-dl interprets this as "best" and downloads this, not the separate video and audio streams.

**Comment by dstftw** [comment]
Have you read the FAQ link posted? It clearly explains that youtube-dl does not download `best` by default but `bestvideo+bestaudio/best` (meaning `bestvideo+bestaudio` if present and `best` otherwise).

**Comment by Sheldan** [comment]
I read it and I found that -f best does what I want. It was just weird, that I tried it after April 2015 and it chose the best single file option (without specifying any format). It works, so I'm fine.

**Comment by dstftw** [comment]
Probably you had no ffmpeg/avconv installed?

**Comment by Sheldan** [comment]
I'm pretty sure I had, but doesn't matter now.
