### ISSUE TITLE
HTTP Error 403

### ISSUE THREAD

**Issue by thetrekker** [rg3/youtube-dl#6908]
Below is an error received using youtube-dl.  Submitting here as requested.

youtube-dl --verbose -o "~/Videos/Rainierland Movies/Tomorrowland.mp4" "https://lh3.googleusercontent.com/EZSKUui-PCahXLmuDVeeCg8SQCGgAxB_-Gv1nwcqO0I=m22"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-o', '~/Videos/Rainierland Movies/Tomorrowland.mp4', 'https://lh3.googleusercontent.com/EZSKUui-PCahXLmuDVeeCg8SQCGgAxB_-Gv1nwcqO0I=m22']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.16.0-49-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[generic] EZSKUui-PCahXLmuDVeeCg8SQCGgAxB_-Gv1nwcqO0I=m22: Requesting header
WARNING: Falling back on generic information extractor.
[generic] EZSKUui-PCahXLmuDVeeCg8SQCGgAxB_-Gv1nwcqO0I=m22: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 191, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1157, in urlopen
    return self._opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by thetrekker** [comment]
I've installed the current version.  Wanna try again with your sarcasm?

youtube-dl --verbose -o "~/Videos/Rainierland Movies/Tomorrowland.mp4" "https://lh3.googleusercontent.com/EZSKUui-PCahXLmuDVeeCg8SQCGgAxB_-Gv1nwcqO0I=m22"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-o', u'~/Videos/Rainierland Movies/Tomorrowland.mp4', u'https://lh3.googleusercontent.com/EZSKUui-PCahXLmuDVeeCg8SQCGgAxB_-Gv1nwcqO0I=m22']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.6 - Linux-3.16.0-49-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] EZSKUui-PCahXLmuDVeeCg8SQCGgAxB_-Gv1nwcqO0I=m22: Requesting header
WARNING: Could not send HEAD request to https://lh3.googleusercontent.com/EZSKUui-PCahXLmuDVeeCg8SQCGgAxB_-Gv1nwcqO0I=m22: HTTP Error 403: Forbidden
[generic] EZSKUui-PCahXLmuDVeeCg8SQCGgAxB_-Gv1nwcqO0I=m22: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
