### ISSUE TITLE
Old binaries

### ISSUE THREAD

**Issue by campones** [rg3/youtube-dl#6910]
Hello thx for your software, been using for year.

Happen my server died few days ago and I realize the last version of youtube-dl is giving primarily preference to dash manifest download, which is really slower then just grabbing the regular mp4.
I was wondering where I could get old binaries from earlier version, since I make a  daily use of this, I also try minimizing the command line it takes to accomplish what I need to.

thx

**Comment by dstftw** [comment]
You can give priority to non DASH with `-f best`. Binaries for each version are located [here](http://yt-dl.org/downloads/), but you won't get any support for outdated versions.

**Comment by campones** [comment]
awesome, thanks for the repository!
