### ISSUE TITLE
youtube-dl extract audio erroe

### ISSUE THREAD

**Issue by duxim** [rg3/youtube-dl#6912]
duxim@kali:~$ sudo youtube-dl --extract-audio --audio-format mp3 -l https://www.youtube.com/watch?v=MdCEPhNBnrM
[youtube] Setting language
[youtube] MdCEPhNBnrM: Downloading webpage
[youtube] MdCEPhNBnrM: Downloading video info webpage
[youtube] MdCEPhNBnrM: Extracting video information
[youtube] MdCEPhNBnrM: Encrypted signatures detected.
[youtube] MdCEPhNBnrM: Downloading js player new
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by jaredmichaelsmith** [comment]
I am having this same issue.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
