### ISSUE TITLE
unable to download full soundcloud playlist

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [rg3/youtube-dl#6918]
https://soundcloud.com/skeewiff/sets/i-got-soul-1

There are 10 track total. All tracks can be downloaded on by one, but only 6 will be downloaded by
$ youtube-dl https://soundcloud.com/skeewiff/sets/i-got-soul-1

**Comment by skiddie9** [comment]
same problem whit downloading all tracks of specific user.

**Comment by dstftw** [comment]
@c-e-p-x-u-o there are only 6 tracks now on this page, all of them downloaded fine.

**Comment by dstftw** [comment]
@skiddie9 open new issue.

**Comment by c-e-p-x-u-o** [comment]
21 Sep 2015 there were 10 tracks. I've downloaded them all!
And now, 8 month later, when you've decided to check it, there are only 6 tracks.
Thank you for prompt response!

**Comment by kevindelord** [comment]
And few years later I have the same problem with a playlist with more than 100 tracks. The download stop after 5 downloaded songs.
