### ISSUE TITLE
youtube-dl error

### ISSUE THREAD

**Issue by alexanderpetrob89** [rg3/youtube-dl#6919]
Hello.
How are you ?
I got error in youtube-dl.
this error is  YouTube said: This video is available in Andorra, .... 
And some video file download is not correct.
example: http://www.youtube.com/watch?v=XbGs_qK2PQA. 
I am not sure what is the problem.
Can you help me ?

**Comment by yan12125** [comment]
Post the [full verbose log with ```-v```](https://github.com/rg3/youtube-dl/#bugs)

**Comment by dstftw** [comment]
Closing since no response from OP.
