### ISSUE TITLE
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by raychaudhuri-amitava** [rg3/youtube-dl#6920]
amitava@L-4BXP542:/Data/install/ashoka$ youtube-dl --verbose --no-check-certificate --audio-quality 0 --prefer-ffmpeg --include-ads --playlist-reverse --age-limit 80 --playlist-start 1 --merge-output-format mp4 --autonumber-size 4 -o "%(autonumber)s_AshokaSamrat_%(upload_date)s_%(resolution)s.%(ext)s" "https://www.youtube.com/playlist?list=PLcC6hSpO26KvnTm0wvNK6T-stRMMHL62Q"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--no-check-certificate', '--audio-quality', '0', '--prefer-ffmpeg', '--include-ads', '--playlist-reverse', '--age-limit', '80', '--playlist-start', '1', '--merge-output-format', 'mp4', '--autonumber-size', '4', '-o', '%(autonumber)s_AshokaSamrat_%(upload_date)s_%(resolution)s.%(ext)s', 'https://www.youtube.com/playlist?list=PLcC6hSpO26KvnTm0wvNK6T-stRMMHL62Q']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 3.4.0 - Linux-3.13.0-63-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] PLcC6hSpO26KvnTm0wvNK6T-stRMMHL62Q: Downloading webpage
[download] Downloading playlist: Chakravartin Ashoka Samrat
[youtube:playlist] PLcC6hSpO26KvnTm0wvNK6T-stRMMHL62Q: Downloading page #1
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/YoutubeDL.py", line 1865, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

This is happening when i am trying in office network.

**Comment by jaimeMF** [comment]
Can you use the `Load more` button at the end of the webpage in a browser from that network?

**Comment by raychaudhuri-amitava** [comment]
@jaimeMF "Load more" is working in browser from that network.

**Comment by raychaudhuri-amitava** [comment]
I ran the following command twice:
wget --no-check-certificate "https://youtube.com/browse_ajax?action_continuation=1&amp;continuation=4qmFsgIuEiRWTFBMY0M2aFNwTzI2S3ZuVG0wd3ZOSzZULXN0Uk1NSEw2MlEaBkNHVSUzRA%253D%253D"

That fixed the issue. I am not sure how this fixed though.
