### ISSUE TITLE
sorry.......

### ISSUE THREAD

**Issue by zenzem** [rg3/youtube-dl#6925]
I need to dl a private video on youtube.
So I installed Python3.5 and youtube-dl. 
And I run command　「 youtube-dl [https://www.youtube.com/watch?~~] 」　but it's invalid syntax.
Perhaps it's the initial mistake..., but would tell me how solutions?

**Comment by yan12125** [comment]
Please post the [full verbose log with ```-v```](https://github.com/rg3/youtube-dl#bugs). 'invalid syntax' does not provide sufficient information for digging the problem.

**Comment by zenzem** [comment]
Submissions command is all.(URL abridgement)
What should I write additional?......
![default](https://cloud.githubusercontent.com/assets/14798430/10037774/c2d67cce-61f5-11e5-8155-437772a79490.png)

**Comment by DVassilev** [comment]
The command should be:

youtube-dl https://youtube.com/watch?v=YOURID

**Comment by yan12125** [comment]
@DVassilev is right. Just open ```cmd.exe``` and type the commands.

**Comment by zenzem** [comment]
thank you,but I cant
![default](https://cloud.githubusercontent.com/assets/14798430/10038115/0e118ce2-61fb-11e5-82f7-fb0fc5646d6c.png)

ValueError:Invalid IPv6 URL
']' is not recognized as an internal or external command,
operable program or batch file.

**Comment by yan12125** [comment]
Brackets cause the error. Just type the URL:
```
youtube-dl.exe https://youtube.com/watch?v=YOURID
```
