### ISSUE TITLE
Choosing video quality to download

### ISSUE THREAD

**Issue by DVassilev** [rg3/youtube-dl#6926]
Hello,

Is it possible to select the a certain video quality (such as, 240p or 480p) and if they don't exist let the program choose which one to download as per usual?

Thanks,
Daniel

**Comment by yan12125** [comment]
You need complicated format filters. Here's an example:
```
youtube-dl -f 'bestvideo[height==480]+bestaudio/bestvideo+bestaudio/best' URL
```

**Comment by DVassilev** [comment]
@yan12125 Does that perform the functionality I described? My goal is to minimise the download time of the video so if the video is lower quality I presume it will download quicker.

**Comment by DVassilev** [comment]
@yan12125 Actually, I'm just extracting the audio so how can I select the quality of the audio in the same manner as described above?

**Comment by yan12125** [comment]
If you're downloading the lowest quality video, ```-f "worstvideo+worstaudio"``` may be what you need.
