### ISSUE TITLE
Filter videos by length

### ISSUE THREAD

**Issue by mikhaelkh** [rg3/youtube-dl#6929]
Is there a way to filter videos in Youtube playlist by length? For example, I want do download all videos shorter than 10 minutes from [here](https://www.youtube.com/playlist?list=PLirAqAtl_h2r5g8xGajEwdXd3x1sZh8hC). If not, please consider adding this feature.

**Comment by jaimeMF** [comment]
Use `--match-filter 'duration < 600'`

**Comment by mikhaelkh** [comment]
@jaimeMF, please add this to documentation.

**Comment by jaimeMF** [comment]
Added in 4c917d0314f0442fd17d6f8ec8e583252167512c.

**Comment by theredwillow** [comment]
I'm looking for a similar functionality, but not with filtering playlists, but rather ytsearch's. Does it exist? If not, should I open a feature request?

**Comment by genesor** [comment]
> I'm looking for a similar functionality, but not with filtering playlists, but rather ytsearch's. Does it exist? If not, should I open a feature request?

@theredwillow you can use the `--match-filter 'duration < 600'` with the `ytsearch` but you will need to do a search of more than 1 item using `ytsearch10:xxx` to retrieve 10 items for example. The items that do not match the filter will be ignored but still included in the 10 results of the search.
