### ISSUE TITLE
Unable to download JSON metadata: HTTP Error 401:

### ISSUE THREAD

**Issue by kikoshiro** [rg3/youtube-dl#6930]
$ youtube-dl --verbose  https://soundcloud.com/rizzoknor/live-garbicz-festival-2014
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://soundcloud.com/rizzoknor/live-garbicz-festival-2014']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.3 - Linux-3.5.0-17-generic-x86_64-with-LinuxMint-14-nadia
[debug] exe versions: avconv 0.8.10-6, avprobe 0.8.10-6, ffprobe 0.8.10-6, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] rizzoknor/live-garbicz-festival-2014: Resolving id
[soundcloud] rizzoknor/live-garbicz-festival-2014: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by pricejn2** [comment]
Thanks for the quick fix @dstftw. Any idea when we can expect the next release?

**Comment by clancye** [comment]
@dstftw thanks for the fix, looking forward to trying in next release.

**Comment by clancye** [comment]
@pricejn2 see answer on 6933, the tarball works.

**Comment by zampl1cg** [comment]
@clancye How does one actually use that tarball?  I can't get ./bin/youtube-dl to do anything other than spit out 

Traceback (most recent call last):
  File "youtube-dl", line 3, in <module>
    import youtube_dl
ImportError: No module named youtube_dl

**Comment by jischein** [comment]
will the fix be implemented in an update soon ?

**Comment by pricejn2** [comment]
@clancye good call, thanks.

@zampl1cg you can use `python -m youtube_dl` or `make; make install`

**Comment by lakecityransom** [comment]
Its confusing as a noob. Thanks yan12125. Here is the easy steps:
1. Download https://github.com/rg3/youtube-dl/archive/master.zip
2. In cmd prompt "PATH\youtube_dl__main__.py" THEURL
3. Wait for the new .exe to come out

**Comment by binhbeer** [comment]
client id is expired!

**Comment by alfredotavio** [comment]
you can use the parameter  --playlist-start to jump the videos already downloaded
because the client has expired

**Comment by BIGAL117** [comment]
What exactly do I need to do to fix my bot so I can play soundcloud music? Ive seen the code but dont know where to put it

**Comment by xxzozaxx** [comment]
@BIGAL117 same here
