### ISSUE TITLE
Soundcloud appears to be broken  - error 401

### ISSUE THREAD

**Issue by yoshi314** [rg3/youtube-dl#6933]
youtube-dl "https://soundcloud.com/feintdnb/we-wont-be-alone-feat-laura-brehm-mc-master" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://soundcloud.com/feintdnb/we-wont-be-alone-feat-laura-brehm-mc-master', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.10 - Linux-4.2.0-gentoo-x86_64-AMD_A10-6700_APU_with_Radeon-tm-_HD_Graphics-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] feintdnb/we-wont-be-alone-feat-laura-brehm-mc-master: Resolving id
[soundcloud] feintdnb/we-wont-be-alone-feat-laura-brehm-mc-master: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1865, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by clancye** [comment]
#6930

**Comment by yan12125** [comment]
Thanks @clancye. @yoshi314 This is fixed but not included in the latest release yet. Please wait for the next version or try the [latest git tarball](https://github.com/rg3/youtube-dl/archive/master.zip).

**Comment by clancye** [comment]
@yan12125 thanks! All good now.

**Comment by zampl1cg** [comment]
@clancye @yan12125  How does one actually use that tarball? I can't get ./bin/youtube-dl to do anything other than spit out

Traceback (most recent call last):
File "youtube-dl", line 3, in 
import youtube_dl
ImportError: No module named youtube_dl

**Comment by clancye** [comment]
@zampl1cg just go to the youtube-dl-master directory and run the exec from there. If you're in the terminal it will just be ./youtube-dl URL_HERE

**Comment by zampl1cg** [comment]
@clancye Maybe I'm going crazy but that file doesn't exist in https://github.com/rg3/youtube-dl/archive/master.zip  

$ tree youtube-dl-master/ |grep youtube-dl
youtube-dl-master/
│   └── youtube-dl
└── youtube-dl.plugin.zsh

**Comment by clancye** [comment]
@zampl1cg That's weird.  I'm running OSX but that shouldn't change the file structure. I don't know what to tell you =[

**Comment by zampl1cg** [comment]
@clancye can you re-download that master.zip, and "ls youtube-dl-master/" I'm telling you its not there.

$ ls youtube-dl-master/
AUTHORS          devscripts  Makefile     setup.cfg  tox.ini
bin              docs        MANIFEST.in  setup.py   youtube_dl
CONTRIBUTING.md  LICENSE     README.md    test       youtube-dl.plugin.zsh

**Comment by yan12125** [comment]
Running ```./youtube_dl/__main__.py``` or ```python -m youtube_dl``` should work.

**Comment by lakecityransom** [comment]
Its confusing as a noob. Thanks yan12125. Here is the easy steps:
1. Download https://github.com/rg3/youtube-dl/archive/master.zip
2. In cmd prompt "<path>\youtube_dl\__main__.py" <URL>
3. Wait for the new .exe to come out
