### ISSUE TITLE
GnuTLS: A TLS packet with unexpected length was received.

### ISSUE THREAD

**Issue by gilles-c** [rg3/youtube-dl#6937]
This is the configuration of one of my computers :
# uname -a
3.2.0-4-powerpc-smp #1 SMP Debian 3.2.68-1+deb7u3 ppc GNU/Linux
# cat /etc/debian_version 
7.9

After updating today linux-headers-3.2.0-4-common linux-headers-3.2.0-4-powerpc-smp linux-image-3.2.0-4-powerpc-smp linux-libc-dev 
~# apt-cache policy linux-image-3.2.0-4-powerpc-smp 
linux-image-3.2.0-4-powerpc-smp:
  Installé : 3.2.68-1+deb7u4
  Candidat : 3.2.68-1+deb7u4

I have tried to update youtube-dl. I started from ~# youtube-dl --verbose --version
2015.09.09
Then # youtube-dl -U
Updating to version 2015.09.22 ...
ERROR: unable to download latest version
 So I try with curl :
~# curl https://yt-dl.org/downloads/2015.09.22/youtube-dl -o /usr/local/bin/youtube-dl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (35) Unknown SSL protocol error in connection to yt-dl.org:443 

I insist with wget ;
# wget https://yt-dl.org/downloads/2015.09.22/youtube-dl -O /usr/local/bin/youtube-dl
--2015-09-23 20:52:29--  https://yt-dl.org/downloads/2015.09.22/youtube-dl
Résolution de yt-dl.org (yt-dl.org)... 95.143.172.170, 2001:1a50:11:0:5f:8f:acaa:177
Connexion vers yt-dl.org (yt-dl.org)|95.143.172.170|:443...connecté.
GnuTLS: A TLS packet with unexpected length was received.
Incapable d'établir une connexion SSL.

Here the result of :
$ aptitude search gnutls
p   dsyslog-module-gnutls                                         - advanced modular syslog daemon - GnuTLS support                         
p   gnutls-bin                                                    - GNU TLS library - commandline utilities                                 
v   gnutls-dev                                                    -                                                                         
p   gnutls-doc                                                    - GNU TLS library - documentation and examples                            
p   gnutls26-doc                                                  - GNU TLS library 2.x - documentation and examples                        
p   guile-gnutls                                                  - GNU TLS library - GNU Guile bindings                                    
p   libapache2-mod-gnutls                                         - Apache module for SSL and TLS encryption with GnuTLS                    
i A libcurl3-gnutls                                               - bibliothèque de transfert par URL côté client et simple d'utilisation - 
v   libcurl3-gnutls-dev                                           -                                                                         
p   libcurl4-gnutls-dev                                           - development files and documentation for libcurl (GnuTLS flavour)        
p   libghc-gnutls-dev                                             - bindings for GNU TLS                                                    
v   libghc-gnutls-dev-0.1.2-899f2                                 -                                                                         
v   libghc-gnutls-dev-0.1.4-dee44                                 -                                                                         
p   libghc-gnutls-doc                                             - bindings for GNU TLS; documentation                                     
p   libghc-gnutls-prof                                            - bindings for GNU TLS; profiling libraries                               
v   libghc-gnutls-prof-0.1.2-899f2                                -                                                                         
v   libghc-gnutls-prof-0.1.4-dee44                                -                                                                         
p   libgnutls-deb0-28                                             - GNU TLS library - main runtime library                                  
i A libgnutls-dev                                                 - GNU TLS library - development files                                     
i   libgnutls-openssl27                                           - bibliothèque GNU TLS - enveloppe OpenSSL                                
i   libgnutls26                                                   - Bibliothèque GNU TLS - bibliothèque exécutable                          
p   libgnutls26-dbg                                               - GNU TLS library - debugger symbols                                      
p   libgnutls28-dbg                                               - GNU TLS library - debugger symbols                                      
p   libgnutls28-dev                                               - GNU TLS library - development files                                     
i   libgnutlsxx27                                                 - GNU TLS library - C++ runtime library                                   
p   libgnutlsxx28                                                 - GNU TLS library - C++ runtime library                                   
i A libneon27-gnutls                                              - HTTP and WebDAV client library (GnuTLS enabled)                         
p   libneon27-gnutls-dbg                                          - Detached symbols for libneon27 (GnuTLS enabled)                         
p   libneon27-gnutls-dev                                          - Header and static library files for libneon27 (GnuTLS enabled)          
p   libxmlsec1-gnutls                                             - Gnutls engine for the XML security library                              
p   python-gnutls                                                 - Python wrapper for the GNUTLS library                                   
v   python2.6-gnutls                                              -                                                                         
v   python2.7-gnutls                                              -                                                                         
p   rsyslog-gnutls                                                - TLS protocol support for rsyslog

**Comment by gilles-c** [comment]
Then I go back to 2015.09.09 version with wget
0# wget https://yt-dl.org/downloads/2015.09.09/youtube-dl -O /usr/local/bin/youtube-dl
and I have again :
# youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.3 - Linux-3.2.0-4-powerpc-smp-ppc-with-debian-7.9
[debug] exe versions: avconv 10.1-6, avprobe 10.1-6, ffmpeg 0.8.17-6
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.

**Comment by jaimeMF** [comment]
It's really weird that you can download version 2015.09.09 but not 2015.09.22. Have you tried again? Can you download it with a webbrowser?

**Comment by gilles-c** [comment]
As Debian update ie, aptitude update and aptitude safe-upgrade says, I have updated today rpcbind, then I tried again to update youtube-dl and I have succeeded.
