### ISSUE TITLE
specify which videos to download from playlist

### ISSUE THREAD

**Issue by vapniks** [rg3/youtube-dl#694]
Feature request: allow specifying several ranges from a playlist, e.g to download vids 1 to 10 and 15 to 20 from <playlist URL>

youtube-dl --playlist-ranges 1-10,15-20 <playlist URL>

**Comment by remitamine** [comment]
isn't --playlist-items working for this case?
```
Playlist video items to download. Specify indices of the videos in the playlist separated by commas like: "--playlist-items 1,2,5,8" if you want to download videos indexed 1, 2, 5, 8 in the playlist. You can specify range: "--playlist-items 1-3,7,10-13", it will download the videos at index 1, 2, 3, 7, 10, 11, 12 and 13.
```

**Comment by jaimeMF** [comment]
As @remitamine said, `--playlist-items` has been available since January (see https://github.com/rg3/youtube-dl/pull/2662#issuecomment-71349375). Therefore I'm closing the issue, feel free to open a new one if that option is not enough for you.
