### ISSUE TITLE
ustream download has ceased to work

### ISSUE THREAD

**Issue by davidrabinowitz** [rg3/youtube-dl#6943]
It appears ustearm has changed something, as now U get the following error:

$ youtube-dl http://www.ustream.tv/recorded/73439996 --verbose
[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg']
[debug] Command-line args: [u'http://www.ustream.tv/recorded/73439996', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.8 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 2.8, ffmpeg 2.8, ffprobe 2.8
[debug] Proxy map: {}
[ustream] 73439996: Downloading JSON metadata
ERROR: This call is deprecated. Contact customer support for more details.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ustream.py", line 63, in _real_extract
    raise ExtractorError(params['error']['message'], expected=True)
ExtractorError: This call is deprecated. Contact customer support for more details.

**Comment by yan12125** [comment]
youtube-dl uses an old API to fetch video info, and now seems ustream has disabled the old API. The new API requires AMF (Action Message Format) support, which is quite complicated.

**Comment by davidrabinowitz** [comment]
In this case I would take ustream off the supported sites list, and perhaps notify the user immediately

**Comment by Ajnasz** [comment]
http://ustream.github.io/api-docs/channel.html

**Comment by CeruleanSky** [comment]
Haven't tested on live streams, but for theirs the info is now at 

https://api.ustream.tv/videos/73439996.json 

So change it to:
        params = self._download_json(
            'https://api.ustream.tv/videos/ + video_id + '.json')


and this to:
 video_url = params['media_urls']['flv']

Should download in theory: 

http://tcdn.ustream.tv/video/73439996?preset_id=1&e=1443673703&h=5e54fdfb89ffec05d0e06e6fc8aeeb00

Which my browser says is a bit over a gigabyte.

**Comment by davidrabinowitz** [comment]
Thanks @CeruleanSky , I've created a fix based on your comment

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version. Thanks for the report.
