### ISSUE TITLE
xhamster issue

### ISSUE THREAD

**Issue by incose** [rg3/youtube-dl#6944]
see log below:

C:\squid>youtube-dl.exe -v "http://xhamster.com/movies/5114337/delicious_anus_from_cheater_wife.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://xhamster.com/movies/5114337/delicious_anus_from_cheater_wife.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[XHamster] 5114337: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete outp
ut.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 660, in extract_info
  File "youtube_dl\extractor\common.pyo", line 287, in extract
  File "youtube_dl\extractor\xhamster.pyo", line 66, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 590, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 581, in _search_regex
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using
 the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its
complete output.

awesome tool!

**Comment by incose** [comment]
Still seems to be an issue with xhamster.com
thanks again

**Comment by yan12125** [comment]
It's fixed in git but not released yet. Please wait for the next release.

**Comment by incose** [comment]
ok!
