### ISSUE TITLE
WARNING: unable to extract duration

### ISSUE THREAD

**Issue by mgutierrezp** [rg3/youtube-dl#6946]
while downloading from streamcloud.eu

**Comment by jaimeMF** [comment]
[Read the bug reporting instructions](https://github.com/rg3/youtube-dl/blob/0391bc8176c22e586f1c866145bc31e9cd2c50ed/README.md#bugs) and post the required information.

**Comment by mgutierrezp** [comment]
sorry, was fixed in last version

**Comment by yan12125** [comment]
Glad to see that your problem is solved. Feel free to open new issues if you've encountered other problems.
