### ISSUE TITLE
Facebook falls back to generic extractor

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#6951]
URL: https://www.facebook.com/groups/2247187733/permalink/10153231044712734/

c:\Transmogrifier>youtube-dl.py -v "https://www.facebook.com/groups/2247187733/permalink/10153231044712734/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.facebook.com/groups/2247187733/permalink/10153231044712734/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 10153231044712734: Requesting header
[redirect] Following redirect to https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fgroups%2F2247187733%2Fpermalink%2F10153231044712734%2F
[generic] login.php?next=https://www.facebook: Requesting header
WARNING: Falling back on generic information extractor.
[generic] login.php?next=https://www.facebook: Downloading webpage
[generic] login.php?next=https://www.facebook: Extracting information
[redirect] Following redirect to https://www.facebook.com/login.php?next=https://www.facebook.com/groups/2247187733/permalink/10153231044712734/&_fb_noscript=1
[generic] &_fb_noscript=1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] &_fb_noscript=1: Downloading webpage
[generic] &_fb_noscript=1: Extracting information
ERROR: Unsupported URL: https://www.facebook.com/login.php?next=https://www.facebook.com/groups/2247187733/permalink/10153231044712734/&_fb_noscript=1
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 1239, in _real_extract
    doc = parse_xml(webpage)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\utils.py", line 1656, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 8, column 8094
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 287, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 1840, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.facebook.com/login.php?next=https://www.facebook.com/groups/2247187733/permalink/10153231044712734/&_fb_noscript=1

Thanks
Ringo

**Comment by dstftw** [comment]
It at least requires login.

**Comment by RingoTheDog** [comment]
oh sorry...so I guess it is the same as https://github.com/rg3/youtube-dl/issues/4902

...shall I close?

**Comment by yan12125** [comment]
They're different. Videos in groups are not supported yet.

**Comment by yan12125** [comment]
Videos in groups will be supported in the next version. Note that you need to provide credentials even for videos in public groups. Feel free to open a new issue if there are still problems regarding Facebook videos.
