### ISSUE TITLE
 youtube-dl --verbose -x --audio-format mp3 https://www.youtube.com/playlist?list=PLbHMttE9dKfsKFWh3fLDA7fAkgzUMoWML

### ISSUE THREAD

**Issue by dalaidakkar** [rg3/youtube-dl#6973]
youtube-dl --verbose -x --audio-format mp3 https://www.youtube.com/playlist?list=PLbHMttE9dKfsKFWh3fLDA7fAkgzUMoWML
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-x', '--audio-format', 'mp3', 'https://www.youtube.com/playlist?list=PLbHMttE9dKfsKFWh3fLDA7fAkgzUMoWML']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
[debug] Proxy map: {}
[youtube:playlist] PLbHMttE9dKfsKFWh3fLDA7fAkgzUMoWML: Downloading webpage
[download] Downloading playlist: punchis
[youtube:playlist] playlist punchis: Collected 16 video ids (downloading 16 of them)
[download] Downloading video #1 of 16
[youtube] Setting language
[youtube] dsxufU7X2Rw: Downloading webpage
[youtube] dsxufU7X2Rw: Downloading video info webpage
[youtube] dsxufU7X2Rw: Extracting video information
[debug] Invoking downloader on u'https://r5---sn-ug5onuxajv-jwnl.googlevideo.com/videoplayback?sver=3&signature=34A478E7BFAB5A0EB1F2EA7FF0288B50C80B9FAD.2D2E9F278D117F7996E62C9A95C43BACCA2D03A6&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&itag=140&upn=mo-CHfTOIEI&mt=1443215654&gir=yes&mime=audio%2Fmp4&key=yt6&initcwndbps=588750&keepalive=yes&requiressl=yes&gcr=mx&fexp=9405985%2C9408710%2C9409069%2C9415365%2C9415436%2C9415485%2C9415791%2C9416023%2C9416049%2C9416126%2C9416329%2C9416985%2C9417368%2C9417707%2C9418015%2C9418044%2C9418153%2C9418448%2C9419332%2C9419549%2C9420348%2C9421013%2C9421745&lmt=1428168765233558&dur=3480.717&source=youtube&clen=55880144&mm=31&expire=1443237363&id=o-ALCvDHMi1Od27Rc7UQbVY83Yog-jiMQYC-db-HCQqpGD&ipbits=0&mv=m&pl=19&ms=au&ip=189.202.32.5&mn=sn-ug5onuxajv-jwnl&ratebypass=yes'
[download] Destination: ULTRA 2015 - MAKJ ft. O.T. Genasis (Live Set) _ DJ MAKJ-dsxufU7X2Rw.m4a
[download] 100% of 53.29MiB in 00:23
[avconv] Destination: ULTRA 2015 - MAKJ ft. O.T. Genasis (Live Set) _ DJ MAKJ-dsxufU7X2Rw.mp3
[debug] ffmpeg command line: avconv -y -i 'ULTRA 2015 - MAKJ ft. O.T. Genasis (Live Set) _ DJ MAKJ-dsxufU7X2Rw.m4a' -vn -acodec libmp3lame -q:a 5 'ULTRA 2015 - MAKJ ft. O.T. Genasis (Live Set) _ DJ MAKJ-dsxufU7X2Rw.mp3'
Deleting original file ULTRA 2015 - MAKJ ft. O.T. Genasis (Live Set) _ DJ MAKJ-dsxufU7X2Rw.m4a (pass -k to keep)
[download] Downloading video #2 of 16
[youtube] YjvIPhxLzTY: Downloading webpage
[youtube] YjvIPhxLzTY: Downloading video info webpage
[youtube] YjvIPhxLzTY: Extracting video information
[debug] Invoking downloader on u'https://r4---sn-ug5onuxajv-jwne.googlevideo.com/videoplayback?fexp=9405985%2C9408710%2C9409069%2C9415365%2C9415436%2C9415485%2C9415791%2C9416023%2C9416049%2C9416126%2C9416329%2C9416985%2C9417368%2C9417707%2C9418015%2C9418044%2C9418153%2C9418448%2C9419332%2C9419549%2C9420348%2C9421013%2C9421745&upn=Qys4oMGr3DI&mime=audio%2Fmp4&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&initcwndbps=585000&gir=yes&signature=CD9E44D5D0D2AA661A1186308120776B6D2B49A1.22C9A258686DB19DF6C64E6DC70AEF7577D06AE8&pl=19&clen=4833311&ms=au&mt=1443215799&mv=m&sver=3&expire=1443237467&requiressl=yes&ipbits=0&mm=31&mn=sn-ug5onuxajv-jwne&id=o-AJvBoEtgVQ9rMnEAmHuDVYdQrYPk553CjyjTX_ooZDqK&itag=140&source=youtube&key=yt6&ip=189.202.32.5&dur=301.023&lmt=1409966883342707&ratebypass=yes'
[download] Destination: Cazette - Run For Cover (Deorro Remix)-YjvIPhxLzTY.m4a
[download] 100% of 4.61MiB in 00:18
[avconv] Destination: Cazette - Run For Cover (Deorro Remix)-YjvIPhxLzTY.mp3
[debug] ffmpeg command line: avconv -y -i 'Cazette - Run For Cover (Deorro Remix)-YjvIPhxLzTY.m4a' -vn -acodec libmp3lame -q:a 5 'Cazette - Run For Cover (Deorro Remix)-YjvIPhxLzTY.mp3'
Deleting original file Cazette - Run For Cover (Deorro Remix)-YjvIPhxLzTY.m4a (pass -k to keep)
[download] Downloading video #3 of 16
[youtube] _eVNU59Q_MU: Downloading webpage
[youtube] _eVNU59Q_MU: Downloading video info webpage
[youtube] _eVNU59Q_MU: Extracting video information
[youtube] _eVNU59Q_MU: Encrypted signatures detected.
[youtube] {22} signature length 42.40, html5 player new
[youtube] _eVNU59Q_MU: Downloading js player new
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 860, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 489, in _decrypt_signature
    u'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by dalaidakkar** [comment]
Thank you very much!   I updated and error is gone.
