### ISSUE TITLE
"bestaudio" option downloads a webm file

### ISSUE THREAD

**Issue by nick-s-b** [rg3/youtube-dl#6975]
Hello,
I've noticed several times that when I use a `-f bestaudio` youtube-dl actually downloads a webm file. For example, if I try the following: `youtube-dl -f bestaudio uRmEefcDGVQ` I end up with a webm file (instead of a usual m4a file.

Thanks.

**Comment by dstftw** [comment]
`bestaudio` for uRmEefcDGVQ is 251 and it's a webm:
```
format code  extension  resolution note
249          webm       audio only DASH audio   63k , opus @ 50k, 2.37MiB
250          webm       audio only DASH audio   87k , opus @ 70k, 3.22MiB
171          webm       audio only DASH audio  124k , vorbis@128k (44100Hz), 5.21MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, aac  @128k (44100Hz), 5.91MiB
251          webm       audio only DASH audio  152k , opus @160k, 6.20MiB
````

**Comment by jaimeMF** [comment]
If you only want a m4a file you can force it with `-f bestaudio[ext=m4a]`.

**Comment by gaming-hacker** [comment]
i use this
-f bestvideo[ext!=webm]+bestaudio[ext!=opus]/best
