### ISSUE TITLE
Can't Download from kisscartoon.me

### ISSUE THREAD

**Issue by thiwankaw** [rg3/youtube-dl#6977]
youtube-dl http://kisscartoon.me/Cartoon/Thundercats-1985/Season-01-Episode-025?id=9881 returned below error

[generic] Season-01-Episode-025?id=9881: Requesting header
WARNING: Could not send HEAD request to http://kisscartoon.me/Cartoon/Thundercats-1985/Season-01-Episode-025?id=9881: HTTP Error 503: Service Temporarily Unavailable
[generic] Season-01-Episode-025?id=9881: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by thiwankaw** [comment]
not really sure if they have " rights to distribute" 

but their footer (http://kisscartoon.me/ has below note)

From 2014-2015 KissCartoon.me. Copyrights and trademarks for the cartoon, and other promotional materials are held by their respective owners and their use is allowed under the fair use clause of the Copyright Law.

youtube-dl suggested "please report this issue on https://yt-dl.org/bug" when i tried kisscartoon.me. But if they are in violation of copyrights, may be this bug can be closed.

**Comment by thiwankaw** [comment]
youtube-dl does not support sites dedicated to copyright infringement

**Comment by dstftw** [comment]
According to disclaimer and DMCA note posted [here](http://kisscartoon.me/Message/CopyrightPolicy) they have no rights to distribute this content.
