### ISSUE TITLE
Youtube-dl should keep continue to download next video if one of the video on the playlist is failed

### ISSUE THREAD

**Issue by kokizzu** [rg3/youtube-dl#698]
for example if we download a playlist containing 100 videos, and the second one has an error (timeout or ERROR: unable to download video webpage: HTTP Error 404: Not Found), it should continue to next video instead of stopping the whole program

**Comment by mihajlo** [comment]
example to me more clear:

youtube-dl -f bestaudio --audio-quality 0 --audio-format mp3 -i -x --extract-audio https://www.youtube.com/playlist?list=PLa8z0Y9At06iw3PbaAepPJdwv2gXA1YET

**Comment by Lucidyan** [comment]
Make it default please. Big luck that I found this thread!

**Comment by Hrxn** [comment]
It's right here: https://github.com/rg3/youtube-dl#options

And right at the top if you do `youtube-dl -h`

**Comment by laurent22** [comment]
It would be better if it was a default, last time I googled this I found nothing and gave up. I think most Unix programs that deal with a lot of files continue even after an error, eg. `rsync`. If the concern is that the user might not see the errors, maybe they should be buffered and printed in full at the end of the process.

**Comment by laurent22** [comment]
Alternatively, maybe a good compromise would be to mention the required flag in the error message. For example:

    ERROR: hCpFeE68Yjg: YouTube said: This video is private. (Use the -i flag to ignore this error)

**Comment by Purgator** [comment]
I agree with the default or at least warning, but it should be default. Why you should expect to get only some videos but not some others ? That not having sense to me.
Thx for opening this issue btw, I was about to get mad :o

**Comment by eriknstr** [comment]
Make it default and make youtube-dl list the videos that failed to download at the end and exit non-zero.
