### ISSUE TITLE
xhamster seems to be broke....

### ISSUE THREAD

**Issue by kendalls63** [rg3/youtube-dl#6994]
http://xhamster.com/movies/5135690/honey_i_am_home.html

verbose output:
------------------------------------
E:\Vidcon>youtube-dl --verbose http://xhamster.com/movies/5135690/honey_i_am_home.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://xhamster.com/movies/5135690/honey_i_am_home.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-68756-g627f565, ffprobe N-68756-g627f565
[debug] Proxy map: {}
[XHamster] 5135690: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl
-U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 660, in extract_info
  File "youtube_dl\extractor\common.pyo", line 287, in extract
  File "youtube_dl\extractor\xhamster.pyo", line 66, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 590, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 581, in _search_regex
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
It's fixed but not included in the latest release. Please wait for the next release.
