### ISSUE TITLE
How can I specify path for downloaded files

### ISSUE THREAD

**Issue by asholok** [rg3/youtube-dl#7009]
Can I put downloaded file to custom directory or throw file thru django model:

> from __future__ import unicode_literals
>from my_app.models import Profile
>import youtube_dl
>
>def download_video(request):
>>ydl_opts = {}
>>with youtube_dl.YoutubeDL(ydl_opts) as ydl:
>>>info_dict = ydl.extract_info('http://www.youtube.com/watch?v=wRmxuEZj1v4', download=True)
>>>Profile.video.save(info_dict.get('title', ''), ydl._screen_file) 

* I want to avoid double save of video file, first to the script location, and second to the model location.

* if it's not possible how I can specify first save to the custom temp location

**Comment by jaimeMF** [comment]
Isn't [outtmpl`](https://github.com/rg3/youtube-dl/blob/6a3f4c3f829eaff87caacf162ae4fc60045bd059/youtube_dl/YoutubeDL.py#L139) enough? You can use:
```python
ydl_opts = {'outtmpl': '/path/to/folder/%(title)s-%(id)s.%(ext)s'}
```

**Comment by asholok** [comment]
Thx, It might help me.
