### ISSUE TITLE
NFL: Failed to parse JSON

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#7012]
URL: http://www.steelers.com/news/article-1/Tomlin-on-Ben-getting-Vick-ready/56399c96-4160-48cf-a7ad-1d17d4a3aef7

c:\Transmogrifier>youtube-dl.py -v "http://www.steelers.com/news/article-1/Tomlin-on-Ben-getting-Vick-ready/56399c96-4160-48cf-a7ad-1d17d4a3aef7"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.steelers.com/news/article-1/Tomlin-on-Ben-getting-Vick-ready/56399c96-4160-48cf-a7ad-1d17d4a3aef7']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.09.28
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[nfl.com] 56399c96-4160-48cf-a7ad-1d17d4a3aef7: Downloading webpage
[nfl.com] 56399c96-4160-48cf-a7ad-1d17d4a3aef7: Downloading player config
[nfl.com] 56399c96-4160-48cf-a7ad-1d17d4a3aef7: Downloading JSON metadata
ERROR: 56399c96-4160-48cf-a7ad-1d17d4a3aef7: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Ma
ng the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 481, in _parse_json
    return json.loads(json_string)
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 288, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\nfl.py", line 160, in _real_extract
    url_template.format(id=video_id), video_id)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 475, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 485, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: 56399c96-4160-48cf-a7ad-1d17d4a3aef7: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org
u are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

This link (same vid) does work:
http://www.steelers.com/videos/videos/Tomlin-looks-ahead-to-Ravens-on-a-short-week/12693586-6ea9-4743-9c1c-02c59e4a5ef2

Thanks
Ringo

**Comment by Xonshiz** [comment]
I don't think "http://www.steelers.com" is supported. As the output says so.

**Comment by Xonshiz** [comment]
http://prod.hdvideo.steelers.clubs.nfl.com//PIT/videos/dct/video_audio/2015/09-September/092815_TomlinPresser-,50,70,120,200,320,500,0k.mp4.csmil/bitrate=0?v=2.10.3&fp=WIN%2019,0,0,185&r=LXIRJ&g=OQFHYIRNDXNC&seek=0

You can get the video here though

**Comment by RingoTheDog** [comment]
Xonshiz 
dstftw recently added individual NFL team domains support:  
https://github.com/rg3/youtube-dl/commit/5b4c54631a8888d75fa766c0bd6ec1822e6caec5

the direct link to the video on steelers.com does work with latest YouTube-DL builds.
http://www.steelers.com/videos/videos/Tomlin-looks-ahead-to-Ravens-on-a-short-week/12693586-6ea9-4743-9c1c-02c59e4a5ef2
