### ISSUE TITLE
Downloading from crunchyroll won't embed subs

### ISSUE THREAD

**Issue by Xonshiz** [rg3/youtube-dl#7014]
when you try to download the video along with subs from crunchyroll.com , it doesn't merge the subs. It downloads video (in mp4 format) and subs. ffmpeg works on it, but, the output is "video.mp4". MP4 doesn't support softsubs and I can't seem to change the output format to mkv either.
Command I used :- 
youtube-dl "http://www.crunchyroll.com/naruto-shippuden/episode-429-killer-bee-rappuden-part-1-684435" -f 480p --sub-lang enUS --write-sub --sub-format ass --embed-subs

It downloads the file, but, subs aren't merged.

EDIT: - Output With --verbose

youtube-dl "http://www.crunchyroll.com/naruto-shippuden/episode-429-killer-bee-rappuden-part-1-684435" -f 480p --sub-lang enUS --write-sub --sub-format ass --embed-subs --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.crunchyroll.com/naruto-shippuden/episode-429-killer-bee-rappuden-part-1-684435', u'-f', u'480p', u'--sub-lang', u'enUS', u'--write-sub', u'--sub-format', u'ass', u'--embed-subs', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.8 - Windows-2012Server-6.2.9200
[debug] exe versions: ffmpeg N-75316-gcbbd906, rtmpdump 2.5
[debug] Proxy map: {}
[Crunchyroll] 684435: Downloading webpage
[Crunchyroll] 684435: Downloading media info
[Crunchyroll] 684435: Downloading media info for 360p
[Crunchyroll] 684435: Checking 360p URL
[Crunchyroll] 684435: Downloading media info for 480p
[Crunchyroll] 684435: Checking 480p URL
[Crunchyroll] 684435: Downloading media info for 720p
[Crunchyroll] 684435: Checking 720p URL
[Crunchyroll] 684435: Downloading media info for 720p
[Crunchyroll] 684435: Checking 720p URL
[Crunchyroll] 684435: Downloading media info for 1080p
[Crunchyroll] 684435: Checking 1080p URL
[Crunchyroll] 684435: Downloading media info for 1080p
[Crunchyroll] 684435: Checking 1080p URL
[Crunchyroll] 684435: Downloading subtitles for English (US)
[Crunchyroll] 684435: Downloading subtitles for ???????
[Crunchyroll] 684435: Downloading subtitles for Italiano
[Crunchyroll] 684435: Downloading subtitles for Deutsch
[info] Writing video subtitles to: Naruto Shippuden - Season 17 Episode 429 - Killer Bee Rappuden - Part 1-684435.enUS.ass
[debug] Invoking downloader on u'http://v.lvlt.crcdn.net/c19/s/ve1966395/video.mp4?nvb=20150929043825&nva=20150929083925&token=0d641de51a41b1fcac781'
[download] Destination: Naruto Shippuden - Season 17 Episode 429 - Killer Bee Rappuden - Part 1-684435.mp4
[download] 100% of 143.24MiB in 00:05
[ffmpeg] Embedding subtitles in 'Naruto Shippuden - Season 17 Episode 429 - Killer Bee Rappuden - Part 1-684435.mp4'
[debug] ffmpeg command line: ffmpeg -y -i 'Naruto Shippuden - Season 17 Episode429 - Killer Bee Rappuden - Part 1-684435.mp4' -i 'Naruto Shippuden - Season 17 Episode 429 - Killer Bee Rappuden - Part 1-684435.enUS.ass' -map 0 -c copy -map-0:s -c:s mov_text -map 1:0 -metadata:s:s:0 language=eng 'Naruto Shippuden - Season 17 Episode 429 - Killer Bee Rappuden - Part 1-684435.temp.mp4'Deleting original file Naruto Shippuden - Season 17 Episode 429 - Killer Bee Rappuden - Part 1-684435.enUS.ass (pass -k to keep)

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by Xonshiz** [comment]
nothing on this one yet? anyone? anything?

**Comment by percheperche** [comment]
Have you resolved? I'm having the same issue

**Comment by Xonshiz** [comment]
Nope. I had to create a tool on my own, [anime-dl](https://github.com/Xonshiz/anime-dl/).

**Comment by Xonshiz** [comment]
Check the documentation, everything is there. It's more or less like
youtube-dl.
