### ISSUE TITLE
ExtractError - Downloading DASH manifest

### ISSUE THREAD

**Issue by rcross** [rg3/youtube-dl#7016]
WARNING: [youtube] LWdNMhI0MoA: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)

WARNING: [youtube] QFsQAWHqs2U: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)

WARNING: [youtube] LWdNMhI0MoA: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)

WARNING: [youtube] u-6hRFssmbc: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)

WARNING: [youtube] U3S-NZmm674: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)

**Comment by jaimeMF** [comment]
[Post the full output you get with the `--verbose` flag](https://github.com/rg3/youtube-dl/blob/4c917d0314f0442fd17d6f8ec8e583252167512c/README.md#bugs).
