### ISSUE TITLE
Can't extract "video_id" from Neighbours replay source.

### ISSUE THREAD

**Issue by rnoremacc** [rg3/youtube-dl#7017]
Hi,
This worked up until last Monday, the last time I tried to catch up online. Now it fails.

:~$ youtube-dl --verbose http://tenplay.com.au/channel-eleven/neighbours/2015/9/22
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://tenplay.com.au/channel-eleven/neighbours/2015/9/22']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.28
[debug] Python version 2.7.9 - Linux-3.19.0-28-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[TenPlay] http://tenplay.com.au/channel-eleven/neighbours/2015/9/22: Downloading webpage
ERROR: Unable to extract video_id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 288, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tenplay.py", line 38, in _real_extract
    r'videoID: "(\d+?)"', webpage, 'video_id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 591, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 582, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video_id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks for looking at this problem.
Chris.

**Comment by remitamine** [comment]
it looks like they change to use the brightcove in page embed.
i can't test it because it is georestricted.
i get this message for the api request: `Access to this resource is forbidden by access policy.`
i will add some code to extract the error message in this pull request #6828.
