### ISSUE TITLE
YouTube Metadata from Title: Artist not being added correctly

### ISSUE THREAD

**Issue by typat** [rg3/youtube-dl#7019]
Here's the command:

    youtube-dl -i -x --no-mtime --audio-format "mp3" --audio-quality "320k" --add-metadata --metadata-from-title "%(artist)s - %(title)s" --embed-thumbnail --xattrs --prefer-ffmpeg -v https://www.youtube.com/watch?v=euqY7AOgr6Q

Here's the output:

    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'-i', u'-x', u'--no-mtime', u'--audio-format', u'mp3', u'--audio-quality', u'320k',     u'--add-metadata', u'--metadata-from-title', u'%(artist)s - %(title)s', u'--embed-thumbnail', u'--xattrs', u'--    prefer-avconv', u'-v', u'https://www.youtube.com/watch?v=euqY7AOgr6Q']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.09.28
    [debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
    [debug] exe versions: ffmpeg 2.8, ffprobe 2.8
    [debug] Proxy map: {}
    [youtube] euqY7AOgr6Q: Downloading webpage
    [youtube] euqY7AOgr6Q: Downloading video info webpage
    [youtube] euqY7AOgr6Q: Extracting video information
    [youtube] {22} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {43} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {18} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {5} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {36} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {17} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {13} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {136} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {247} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {298} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {302} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {135} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {244} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {134} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {243} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {133} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {242} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {160} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {140} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] {171} signature length 44.40, html5 player new-en_US-vfl9jbnCC
    [youtube] euqY7AOgr6Q: Downloading DASH manifest
    [youtube] euqY7AOgr6Q: Downloading thumbnail ...
    [youtube] euqY7AOgr6Q: Writing thumbnail to: Silento - Watch Me (Whip _ Nae Nae) (Sikdope Remix)-euqY7AOgr6Q.jpg
    [debug] Invoking downloader on 'https://r3---sn-a8au-xfge.googlevideo.com/    videoplayback?id=7aea98ec03a0afa4&itag=171&source=youtube&requiressl=yes&mv=m&ms=au&gcr=us&mn=sn-a8au-    xfge&mm=31&pl=24&ratebypass=yes&mime=audio/webm&gir=yes&clen=4315269&lmt=1436983088781556&dur=225.682&key=dg_yt0&    upn=J1y2MjOMa1U&signature=954CA8EE3CCF5BF46559EDC7C947A07E03BE8B1C.88D1F89F6BB5A6CE7C56EEEA5D63B7FE7F82EACA&sver=    3&fexp=9405349,9408145,9408214,9408710,9409069,9413313,9414703,9414764,9414856,9415365,9415435,9415485,9416023,94    16126,9417633,9417707,9418153,9418201,9418448,9419265,9419993,9420078,9420283,9420348,9420583,9421013,9421159&mt=    1443556237&ip=65.183.159.254&ipbits=0&expire=1443577974&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,    gcr,mn,mm,pl,ratebypass,mime,gir,clen,lmt,dur'
    [download] Destination: Silento - Watch Me (Whip _ Nae Nae) (Sikdope Remix)-euqY7AOgr6Q.webm
    [download] 100% of 4.12MiB in 00:00
    [fromtitle] parsed artist: Silento
    [fromtitle] parsed title: Watch Me (Whip / Nae Nae) (Sikdope Remix)
    [ffmpeg] Adding metadata to 'Silento - Watch Me (Whip _ Nae Nae) (Sikdope Remix)-euqY7AOgr6Q.webm'
    [debug] ffmpeg command line: ffmpeg -y -i 'file:Silento - Watch Me (Whip _ Nae Nae) (Sikdope Remix)-euqY7AOgr6Q.    webm' -c copy -metadata 'comment=Silento - Watch Me (Whip / Nae Nae) (Sikdope Remix)
    Subscribe here: http://trapcity.tv/subscribe
    Free Download: http://trapcity.tv/vw9T6
    
    ➥ Become a fan of Trap City:
    http://trapcity.tv/soundcloud
    http://trapcity.tv/facebook
    http://trapcity.tv/twitter
    http://trapcity.tv/instagram
    http://trapcity.tv/vine
    http://trapcity.tv/plugdj
    http://www.trapcity.net
    
    ➥ Follow Sikdope:
    http://www.soundcloud.com/sikdope
    http://www.facebook.com/sikdope
    http://www.twitter.com/sikdope
    http://www.instagram.com/sikdope' -metadata 'description=Silento - Watch Me (Whip / Nae Nae) (Sikdope Remix)
    Subscribe here: http://trapcity.tv/subscribe
    Free Download: http://trapcity.tv/vw9T6
    
    ➥ Become a fan of Trap City:
    http://trapcity.tv/soundcloud
    http://trapcity.tv/facebook
    http://trapcity.tv/twitter
    http://trapcity.tv/instagram
    http://trapcity.tv/vine
    http://trapcity.tv/plugdj
    http://www.trapcity.net
    
    ➥ Follow Sikdope:
    http://www.soundcloud.com/sikdope
    http://www.facebook.com/sikdope
    http://www.twitter.com/sikdope
    http://www.instagram.com/sikdope' -metadata artist=Silento -metadata 'title=Watch Me (Whip / Nae Nae) (Sikdope     Remix)' -metadata date=20150715 -metadata 'purl=https://www.youtube.com/watch?v=euqY7AOgr6Q' 'file:Silento -     Watch Me (Whip _ Nae Nae) (Sikdope Remix)-euqY7AOgr6Q.temp.webm'
    [debug] ffmpeg command line: ffprobe -show_streams 'file:Silento - Watch Me (Whip _ Nae Nae) (Sikdope Remix)-    euqY7AOgr6Q.webm'
    [ffmpeg] Destination: Silento - Watch Me (Whip _ Nae Nae) (Sikdope Remix)-euqY7AOgr6Q.mp3
    [debug] ffmpeg command line: ffmpeg -y -i 'file:Silento - Watch Me (Whip _ Nae Nae) (Sikdope Remix)-euqY7AOgr6Q.    webm' -vn -acodec libmp3lame -b:a 320k 'file:Silento - Watch Me (Whip _ Nae Nae) (Sikdope Remix)-euqY7AOgr6Q.mp3'
    Deleting original file Silento - Watch Me (Whip _ Nae Nae) (Sikdope Remix)-euqY7AOgr6Q.webm (pass -k to keep)
    [metadata] Writing metadata to file's xattrs
    [ffmpeg] Adding thumbnail to "Silento - Watch Me (Whip _ Nae Nae) (Sikdope Remix)-euqY7AOgr6Q.mp3"
    [debug] ffmpeg command line: ffmpeg -y -i 'file:Silento - Watch Me (Whip _ Nae Nae) (Sikdope Remix)-euqY7AOgr6Q.    mp3' -i 'file:Silento - Watch Me (Whip _ Nae Nae) (Sikdope Remix)-euqY7AOgr6Q.jpg' -c copy -map 0 -map 1 -    metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:Silento - Watch Me (Whip _ Nae     Nae) (Sikdope Remix)-euqY7AOgr6Q.temp.mp3'    

The error appears to come from this part:
`-metadata artist=Silento`

The title is being added correctly to the metadata and it looks like this:
`-metadata 'title=Watch Me (Whip / Nae Nae) (Sikdope     Remix)'`

Ive found that if I run the ffmpeg line again with single quotes around the artist metadata, it will add the artist correctly to the file.

**Comment by dstftw** [comment]
Works fine for me.

**Comment by typat** [comment]
really!?! does you artist metadata arg have quotes around it when run? ive been trying anything i can all day to get this to work.

**Comment by typat** [comment]
It appears to work fine sometimes. Adding -k to the args seems to help the consistency. Ill close this for now and see if I can find some pattern for it not working properly. Thanks.

**Comment by dstftw** [comment]
Here is the [explanation of problem](https://github.com/rg3/youtube-dl/issues/6587#issuecomment-131855936).

**Comment by typat** [comment]
ah awesome. thanks for the explanation.
