### ISSUE TITLE
Issue on playlist download

### ISSUE THREAD

**Issue by mainalikishan** [rg3/youtube-dl#7023]
While downloading a playlist, if any one of the video has error e.g: "The uploader hasn't made this video available in your country", then it immediately ends the process. I am requesting to skip those videos with error and continue to download other videos from the playlist. Is it already possible someway?

**Comment by yan12125** [comment]
[```--ignore-errors```](https://github.com/rg3/youtube-dl#options) does the trick.

**Comment by mainalikishan** [comment]
Thanks :)
