### ISSUE TITLE
download audio only without video

### ISSUE THREAD

**Issue by gaming-hacker** [rg3/youtube-dl#7026]
is there a way to download audio only without downloading the video then have to extract the audio?

**Comment by jaimeMF** [comment]
Running `youtube-dl -f bestaudio/best -x URL` will try first to download an audio only file format and fallback to the video+audio if it's not available ( `-f bestaudio/best` is [the default when you use `-x`](https://github.com/rg3/youtube-dl/blob/8870358b1b1a13c936277081b668f94c5abf95e3/youtube_dl/__init__.py#L184) and no extra config or arguments). Read the [FORMAT SELECTION section in the manual](https://github.com/rg3/youtube-dl/blob/4c917d0314f0442fd17d6f8ec8e583252167512c/README.md#format-selection) for the full information.

**Comment by gaming-hacker** [comment]
great thanks.
