### ISSUE TITLE
req:: audio format:: flac

### ISSUE THREAD

**Issue by gaming-hacker** [rg3/youtube-dl#7027]
could you consider adding support for flac? ffmpeg supports the conversion.

**Comment by brunini** [comment]
Considering that WAV and Opus are already supported . It would be consistent add support for FLAC.

**Comment by LaKing** [comment]
+1

**Comment by hcorion** [comment]
++1

**Comment by yan12125** [comment]
Thanks to @phihag (21bfcd3d6e41aed6113c874533fcfe41eb250d96), this will be supported in the next version.
