### ISSUE TITLE
RTMP download detected but "rtmpdump" could not be run although rtmpdump is installed

### ISSUE THREAD

**Issue by chodid** [rg3/youtube-dl#7029]
![eingabeaufforderung-rtmpdump](https://cloud.githubusercontent.com/assets/8632547/10216709/5cbe6d34-682b-11e5-977a-a9a3f8e116c3.png)
I get this error message even though rtmpdump is present in the /windows/system32 directory and can be run from command line.
I'd be grateful for any suggestions on this matter :) Thanks a lot in advance!

**Comment by jaimeMF** [comment]
[Post the output with the `--verbose` option](https://github.com/rg3/youtube-dl/blob/4c917d0314f0442fd17d6f8ec8e583252167512c/README.md#bugs).

**Comment by dstftw** [comment]
Closing due to no response for a long time.
