### ISSUE TITLE
vidto.me Unsupported URL

### ISSUE THREAD

**Issue by follex** [rg3/youtube-dl#7032]
Hi :)
if I use the command
<code> youtube-dl -F http://vidto.me/j38j9zd9g6ge.html </code>

It returns these errors
<code>
[generic] j38j9zd9g6ge: Requesting header
WARNING: Falling back on generic information extractor.
[generic] j38j9zd9g6ge: Downloading webpage
[generic] j38j9zd9g6ge: Extracting information
ERROR: Unsupported URL: http://vidto.me/j38j9zd9g6ge.html
</code>

Yet Vidto.me is in the list

**Comment by yan12125** [comment]
I guess you're looking at vid.me entry on [supported sites list](https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md)? They're different sites.

Another point is that this video looks like [a copyrighted artwork](https://en.wikipedia.org/wiki/Wag_the_Dog). [youtube-dl does not support sites with illegal media](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do you have evidence that vidto.me has the rights for playing this video? For example, did they buy/rent the copyright of this video from the original copyright owners?

**Comment by follex** [comment]
Oh sorry, I confused  Vid.me with Vidto.me

**Comment by yan12125** [comment]
According to [Google transparency report for vidme.to](https://www.google.com/transparencyreport/removals/copyright/domains/vidto.me/), this website is full of illegal contents. Sorry youtube-dl will NOT support it.
