### ISSUE TITLE
Tumblr: No Format selection / Gets low-res video only

### ISSUE THREAD

**Issue by Hrxn** [rg3/youtube-dl#7036]
This applies to all videos on Tumblr which have that nice 'HD' button in the lower right corner.

Tumblr now serves two different videos (two different files), or maybe even more, don't know about their API or backend.

2015-10-04:
~~I found an example: http://larastonesbitch.tumblr.com/post/130035771559/honestlyiconic~~
Great. Just a few days later, and that blog already moved..
Example is now here, it seems: http://larastoneswitch.tumblr.com/post/130035771559/honestlyiconic

    youtube-dl --get-url http://larastoneswitch.tumblr.com/post/130035771559

gives us this link:
https://www.tumblr.com/video_file/130279545660/tumblr_nvda1gkdqg1uqlov4/480
*(To get the file: Right-click, save link as)*

You will get a .mp4 file.

If you use this direct link:
https://www.tumblr.com/video_file/130279545660/tumblr_nvda1gkdqg1uqlov4

You get a different .mp4 file. Still the same video, but higher resolution (better quality)

*(You can also click the links directly, the video gets now played in your browser (usually), but you can clearly see the different videos/files/resolutions)*

Please note: The quality in general isn't that great in my example here, but this was just the first video I found that had the HD button.

**Edit:**

This video is SFW. Looks like a short clip from an older Victoria's Secret Fashion Show, I think.
Finding a NSFW video would have been faster, though ;-)

**Comment by Hrxn** [comment]
For the record:

The old example link is not longer working anymore.

The post with the video has moved here: http://larastoneswitch.tumblr.com/post/130035771559/honestlyiconic

OTOH, thank you, good job!

**Comment by dstftw** [comment]
HD videos will be supported in the next version.
