### ISSUE TITLE
Feature request: Screenwave support

### ISSUE THREAD

**Issue by Ketsuban** [rg3/youtube-dl#7039]
SF Debris has switched from Blip to Screenwave, so I cannot use youtube-dl on it anymore. Fortunately the Javascript is reasonably easy to read; the mechanism for retrieving video URLs is as follows.

1. Retrieve the source of the page (try `http://sfdebris.com/videos/animation/transformerss1e01.php` as a test case).
2. Match the regex `http://player[0-9]+.screenwavemedia.com/player.php?id=[^']+`.
3. Retrieve the source of the URL matched in step 2.
4. Make a note of the value of `vidid` in the `attributes` map.
5. Match the regex `http://player[0-9]+.screenwavemedia.com/player.js`.
6. Retrieve the source of the URL matched in step 4.
7. The `sources` list inside `jwoptions.playlist` contains the video URLs at decreasing levels of fidelity. `thisObj.options.videoserver` is a reference to an object declared earlier in the file; `playerVidId` is the value of `vidid` which was recorded in step 4.

Some of this errs on the side of trying not to take advantage of what may be coincidences and trying to minimise the possible necessity of future maintenance. For instance,

* The value of `vidid` recorded in step 4 is the same as the `id` parameter of the script whose URL is matched in step 2.
* There appears to be only one `player` server, `player2.screenwavemedia.com`, at the moment.

**Comment by ngld** [comment]
Thanks for your thorough research. However, youtube-dl already supports screenwavemedia links which means that only the first two steps need to be added.

My PR (linked above) adds support for SF Debris. Can you test it please?

**Comment by Ketsuban** [comment]
Looks good to me.

**Comment by dstftw** [comment]
Screenwave is already supported by youtube-dl and http://sfdebris.com/videos/animation/transformerss1e01.php is processed by generic extractor just fine.

**Comment by Angsereg** [comment]
Is there a chance that one of these two extractors could be updated to work with a page (coincidentally also at sfdebris.com (via channelawesome.com): http://channelawesome.com/the-terminator-sf-debris/ ?

While it works for the first video on the page, the second video is, seemingly, completely ignored. I ended up grabbing the download link for the first video via "youtube-dl -g", getting the video id from the page, changing the retrieved download link with the new video id, and then having wget grab the second video with the new url.
