### ISSUE TITLE
no sound in youtube video unless the audio .webm gets ffmpeg-ed into .ogg with "-c copy"  first

### ISSUE THREAD

**Issue by zazdxscf** [rg3/youtube-dl#7048]
`youtube-dl --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0" -k https://www.youtube.com/watch?v=DYGc-31mEec`

 That pulls a `*.f136.mp4` video, a `*.f251.webm` audio , and they get converted into a `.mkv` but with vlc there's no sound (either on the .webm or the .mkv files, in fact the sound card goes to sleep, even though statistics say that audio gets decoded just fine). 
 If I run `opusinfo *.webm` I get some errors which say that's not a valid ogg. Then if I convert the webm into ogg via ffmpeg(this shaves 453,728 bytes) then there's audio on the resulting .ogg; this ffmpeg command:
`ffmpeg -i "file: ASMR Ear (Cleaning) Groomers & Spa Roleplay  (unisex)-DYGc-31mEec.f251.webm" -c copy "file:stuff.ogg"`
 I tried renaming webm to ogg but there's still no audio, so that ffmpeg conversion is needed apparently. Maybe's my vlc acting out? (latest git, but config options may matter)

**EDIT:** forgot to mention youtube-dl version, since it's not latest git:
$ youtube-dl --version
2015.09.28-gentoo_no_offensive_sites

**Comment by zazdxscf** [comment]
Looks like for extracting audio only, the sound works fine(in vlc player) because it gets transformed from `webm` into `opus` by youtube-dl via this command:
`ffmpeg -y -i "file:Epic Action _ Path of Aroha - In The Shadow of a Colossus - EpicMusicVN-BNyuHH7kUJk.webm" -vn -acodec copy "file:Epic Action _ Path of Aroha - In The Shadow of a Colossus - EpicMusicVN-BNyuHH7kUJk.opus"`

Command I used:
`youtube-dl --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0" --extract-audio https://www.youtube.com/watch?v=BNyuHH7kUJk`

And if I pass the `-k` param, it gets the video file too, but vlc-ing the `webm` file (or the resulting `mkv`) still no sound! (good thing it does an `opus` too, with the `-k` arg, although maybe it shouldn't pull the video? guess that's another issue though)

```
$ downaudio -k https://www.youtube.com/watch?v=BNyuHH7kUJk
[youtube] BNyuHH7kUJk: Downloading webpage
[youtube] BNyuHH7kUJk: Downloading video info webpage
[youtube] BNyuHH7kUJk: Extracting video information
[youtube] BNyuHH7kUJk: Downloading DASH manifest
[youtube] BNyuHH7kUJk: Downloading DASH manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Epic Action _ Path of Aroha - In The Shadow of a Colossus - EpicMusicVN-BNyuHH7kUJk.f136.mp4
[download] 100% of 29.82MiB in 00:08
[download] Destination: Epic Action _ Path of Aroha - In The Shadow of a Colossus - EpicMusicVN-BNyuHH7kUJk.f251.webm
[download] 100% of 4.36MiB in 00:01
[ffmpeg] Merging formats into "Epic Action _ Path of Aroha - In The Shadow of a Colossus - EpicMusicVN-BNyuHH7kUJk.mkv"
[ffmpeg] Destination: Epic Action _ Path of Aroha - In The Shadow of a Colossus - EpicMusicVN-BNyuHH7kUJk.opus
```

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by zazdxscf** [comment]
```
$ cd /tmp;downvideo -k --verbose https://www.youtube.com/watch?v=DYGc-31mEec
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--user-agent', u'Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0', u'-k', u'--verbose', u'https://www.youtube.com/watch?v=DYGc-31mEec']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.09.28-gentoo_no_offensive_sites
[debug] Python version 2.7.10 - Linux-4.1.7-hardened-r1-g45b4b78-x86_64-AMD_A6-3400M_APU_with_Radeon-tm-_HD_Graphics-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8
[debug] Proxy map: {}
[youtube] DYGc-31mEec: Downloading webpage
[youtube] DYGc-31mEec: Downloading video info webpage
[youtube] DYGc-31mEec: Extracting video information
[youtube] DYGc-31mEec: Downloading DASH manifest
[youtube] DYGc-31mEec: Downloading DASH manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r1---sn-h5bt5guxax3vh-qxce.googlevideo.com/videoplayback?id=0d819cfb7d6611e7&itag=136&source=youtube&requiressl=yes&mn=sn-h5bt5guxax3vh-qxce&mm=31&ms=au&pl=20&mv=m&ratebypass=yes&mime=video/mp4&gir=yes&clen=281392417&lmt=1443527915463881&dur=2028.392&sver=3&mt=1443862895&upn=YpMeCBHRxjw&signature=3C75E272EF86A991C4B4D4E5CD82F3A7F7DB2131.4E7A9E5F3F45272D93E6E9C82E6F7EBB484E094A&fexp=9405998,9406852,9407116,9408710,9409069,9415365,9415485,9416023,9416126,9416729,9416838,9417707,9417815,9418153,9418391,9418448,9419743,9420348,9421013,9421252,9421351&key=dg_yt0&ip=84.2.91.186&ipbits=0&expire=1443884631&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,mm,ms,pl,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination:  ASMR Ear (Cleaning) Groomers & Spa Roleplay  (unisex)-DYGc-31mEec.f136.mp4
[download] 100% of 268.36MiB in 01:13
[debug] Invoking downloader on u'https://r1---sn-h5bt5guxax3vh-qxce.googlevideo.com/videoplayback?expire=1443884631&dur=2028.401&ipbits=0&sver=3&key=yt6&mime=audio%2Fwebm&gir=yes&signature=5F5F8CF2852A20A5A5804E03D7BA8B318347AEC8.45155720EC4DDA897517BD6B270239A8F1A95284&clen=34031062&itag=251&upn=EsLdmunxJdc&source=youtube&initcwndbps=902500&lmt=1443338875369980&keepalive=yes&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mv=m&mt=1443862895&ms=au&fexp=9405998%2C9406852%2C9407116%2C9408710%2C9409069%2C9415365%2C9415485%2C9416023%2C9416126%2C9416729%2C9416838%2C9417707%2C9417815%2C9418153%2C9418391%2C9418448%2C9419743%2C9420348%2C9421013%2C9421252%2C9421351&requiressl=yes&ip=84.2.91.186&mn=sn-h5bt5guxax3vh-qxce&mm=31&pl=20&id=o-APZzVMD8hSghX6adxuJzu6QsOfBULxljI48-K4IAbDdX&ratebypass=yes'
[download] Destination:  ASMR Ear (Cleaning) Groomers & Spa Roleplay  (unisex)-DYGc-31mEec.f251.webm
[download] 100% of 32.45MiB in 00:08
[ffmpeg] Merging formats into " ASMR Ear (Cleaning) Groomers & Spa Roleplay  (unisex)-DYGc-31mEec.mkv"
[debug] ffmpeg command line: ffmpeg -y -i 'file: ASMR Ear (Cleaning) Groomers & Spa Roleplay  (unisex)-DYGc-31mEec.f136.mp4' -i 'file: ASMR Ear (Cleaning) Groomers & Spa Roleplay  (unisex)-DYGc-31mEec.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file: ASMR Ear (Cleaning) Groomers & Spa Roleplay  (unisex)-DYGc-31mEec.temp.mkv'

real	1m28.506s
user	0m21.053s
sys	0m14.987s

```

**Comment by dstftw** [comment]
Works fine for me with vlc 2.2.0 and mplayer. So it's probably something wrong with either your ffmpeg or vlc.

**Comment by zazdxscf** [comment]
Thanks for looking into this.
I can confirm it works with mplayer.
Sorry for the trouble.

```
$ mplayer audio.webm 
Creating config file: /home/zazdxscf/.mplayer/config
MPlayer SVN-r37440 (Gentoo)-5.2.0 (C) 2000-2015 MPlayer Team

Playing audio.webm.
libavformat version 56.40.101 (external)
libavformat file format detected.
[lavf] stream 0: audio (opus), -aid 0, -alang eng
Clip info:
 encoder: google
Load subtitles in ./
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
libavcodec version 56.60.100 (external)
AUDIO: 48000 Hz, 2 ch, floatle, 0.0 kbit/0.00% (ratio: 0->384000)
Selected audio codec: [ffopus] afm: ffmpeg (FFmpeg opus)
==========================================================================
AO: [alsa] 48000Hz 2ch floatle (4 bytes per sample)
Video: no video
Starting playback...
A:  26.6 (26.6) of 2028.4 (33:48.4)  1.6% 

Exiting... (Quit)

```

**Comment by zazdxscf** [comment]
Can you look in vlc Tools->Messages(Ctrl+M) in the `Modules Tree` tab and say whether the demux is "avformat" or "ogg" while the audio of the .webm is working for you? That's under libvlc->playlist->input->demux...

Looks like for .opus is `demux "ogg"` but for .webm is `demux "avformat"` and in the latter case Audio decoded/played remains 0 (for me). (in Tools->Media Information(Ctrl+i) Statistics tab)
whether I'm using vlc 2.2.0 or the git version.
With or without ffmpeg compiled in. I've no idea how to fix it currently. But clearly since with mplayer works, it must be something on my side.

**Comment by dstftw** [comment]
This is for 251 webm:
![vlc](https://cloud.githubusercontent.com/assets/1908898/10265475/b9c7e6c0-6a53-11e5-8620-cae6b2ebee8f.PNG)

**Comment by zazdxscf** [comment]
Amazing! I didn't have `--enable-mkv` which is because gentoo has the `matroska` USE flag disabled by default, and now it works as it does for you, with `demux "mkv"` and audio works fine! It previously was `demux "avformat"` (with no audio being heard)

If any gentoo users stumble upon this no audio (no sound) issue on (some of) the .webm and .mkv files, just remember to USE=matroska when emerging vlc.

Thanks a lot for the help @dstftw ! Much appreciated!
