### ISSUE TITLE
CNet or DailyMotion and another websites failed

### ISSUE THREAD

**Issue by gokhanege** [rg3/youtube-dl#7051]
Forex:

http://www.cnet.com/videos/cancel-your-apple-music-subscription/
http://www.dailymotion.com/video/x38doel_origen-tender-passion_music
https://www.viewster.com/movie/1056-11757-000/bachelor-party-in-the-bungalow-of-the-damned/
http://www.engadget.com/video/519127636/
http://www.imdb.com/title/tt0111161/?pf_rd_m=A2FGELUUNOQJNL
http://www.izlesene.com/video/meric-oje-suruyor-el-bakim-rutini/8861081#
http://www.metacafe.com/watch/11373845/everything_wrong_with_transformers_age_of_extinction_part_1/
and more..

**Comment by jaimeMF** [comment]
As [explained in the bug reporting instructions](https://github.com/rg3/youtube-dl/blob/4c917d0314f0442fd17d6f8ec8e583252167512c/README.md#bugs):
1. Make sure you [are using the last version of youtube-dl](https://github.com/rg3/youtube-dl/blob/4c917d0314f0442fd17d6f8ec8e583252167512c/README.md#how-do-i-update-youtube-dl).
2. Post the ful output you get when running `youtube-dl -v URL`.

**Comment by jaimeMF** [comment]
Make sure you have updated, some of them works with the last version:

* http://www.cnet.com/videos/cancel-your-apple-music-subscription/ fails
* http://www.dailymotion.com/video/x38doel_origen-tender-passion_music works
* https://www.viewster.com/movie/1056-11757-000/bachelor-party-in-the-bungalow-of-the-damned/ works
* http://www.engadget.com/video/519127636/ fails
* http://www.imdb.com/title/tt0111161/?pf_rd_m=A2FGELUUNOQJNL only trailers are supported, http://www.imdb.com/video/imdb/vi3877612057/?ref_=tt_ov_vi in this case.
* http://www.izlesene.com/video/meric-oje-suruyor-el-bakim-rutini/8861081# works
* http://www.metacafe.com/watch/11373845/everything_wrong_with_transformers_age_of_extinction_part_1/ fails
