### ISSUE TITLE
Print JSON and conversion progress command?

### ISSUE THREAD

**Issue by DVassilev** [rg3/youtube-dl#7056]
Hello,

Is it possible to make a request with the following arguments "--extract-audio" and then get the app to return some JSON with details about the media (such as title, description and thumbnail) and the format of the audio (for example, the extension and quality and whatnot) before proceeding to display the regular conversion progress?

If it's not, could this be implemented as it would be a useful to get a summary in JSON form of the metadata of the format that is about to be downloaded.

Thanks,
Daniel

**Comment by dstftw** [comment]
You can dump metadata to file with `--write-info-json`. I don't see much sense mixing metadata and progress output in single stream.

**Comment by DVassilev** [comment]
@dstftw Does dumping it to --write-info-json give information just for the specific audio it downloaded or for the entire video? Because I would need the information specific for what was downloaded. And in addition, it can be quite useful to output both things to many people. Would be nice to have as an option instead of only being able to do it with the conversion progress being silent.

**Comment by dstftw** [comment]
It dumps a metadata for the file being downloaded in outder dict as well as all others formats under `formats` key. When metadata and non-metadata are mixed together you down know exactly where one finishes and another starts.

**Comment by DVassilev** [comment]
@dstftw I'll take a look but I'm sure some indicator could be added. Sure it may not be useful to everyone but having the option is always better than not. Is there some other command I could run that doesn't download it but would give me the metadata plus audio format as per required above? I suppose I could pslit them up in two commands.

**Comment by dstftw** [comment]
```
-j, --dump-json                  Simulate, quiet but print JSON information. See --output for a description of available keys.
-J, --dump-single-json           Simulate, quiet but print JSON information for each command-line argument. If the URL refers to a playlist, dump the whole playlist
                                 information in a single line.
```

**Comment by DVassilev** [comment]
@dstftw Thank you, but I would appreciate if you would add my suggestion as an enhancement in case someone decides to implement it.

**Comment by DVassilev** [comment]
@dstftw I do not understand what the difference between the two args is though.

**Comment by dstftw** [comment]
I would prefer avoiding any kind of options that require some obscure indicators or introduce nondeterminism.
The difference is this:
>If the URL refers to a playlist, dump the whole playlist information in a single line.

**Comment by DVassilev** [comment]
@dstftw Hmm ok, up to you. Is it at least possible to specify that if it a playlist is sent through to only download the first video or at most one video?

**Comment by dstftw** [comment]
Any of:
```
--playlist-end NUMBER            Playlist video to end at (default is last)
--playlist-items ITEM_SPEC       Playlist video items to download. Specify indices of the videos in the playlist separated by commas like: "--playlist-items 1,2,5,8"
                                 if you want to download videos indexed 1, 2, 5, 8 in the playlist. You can specify range: "--playlist-items 1-3,7,10-13", it will
                                 download the videos at index 1, 2, 3, 7, 10, 11, 12 and 13.
--max-downloads NUMBER           Abort after downloading NUMBER files
```

**Comment by DVassilev** [comment]
@dstftw Is it possible to specify a non-DASH audio format by default without having to check the formats of each one? And thank you for the above post.

**Comment by dstftw** [comment]
Yes, `-f best`. Note, there are no audio-only non-DASH formats.

**Comment by DVassilev** [comment]
@dstftw Hmm because I have issues wiht some of the audio files downloaded and struggle to play them - is there perhaps a recommended encoding setting or something to help eliminate problems?

**Comment by dstftw** [comment]
Too ambiguous to suggest annything.

**Comment by DVassilev** [comment]
@dstftw Is it possible to set a duration limit where if the media is above a certain duration to not download it or alternatively just download up to the limit?

And for the previous question I'm wondering if perhaps I need to change some encoding settings to make the audio playable.

**Comment by dstftw** [comment]
` --match-filter duration < 100`.
Until you provide `--verbose` log nothing can be suggested. If you decide to do that open a new issue.
