### ISSUE TITLE
Does not download full playlist....

### ISSUE THREAD

**Issue by bobhaha** [rg3/youtube-dl#7061]
I'm trying to download a playlist with over 50+ songs in it.

Link here:
https://www.youtube.com/watch?v=JBYy8Ion_LQ&list=RDJBYy8Ion_LQ

If you run youtube-dl on this playlist it finds the first 26. From 27 onwards the URL changes, for example

#27 = https://www.youtube.com/watch?v=sUoWkRggVig&list=RDJBYy8Ion_LQ&index=27
#28 = https://www.youtube.com/watch?v=iTwmVasMxCM&index=27&list=RDJBYy8Ion_LQ
#29 = https://www.youtube.com/watch?v=FCX6WBIzfQ8&list=RDJBYy8Ion_LQ&index=27
...
#33 = https://www.youtube.com/watch?v=SAG4wFcWunE&list=RDJBYy8Ion_LQ&index=28

Looks like the URL changes for each song but the index doesn't for a while, then it starts changing again. Could this be an api trick from youtube to stop people downloading playlists? 

Or is this an issue with youtube-dl?

**Comment by dstftw** [comment]
It's a mix and originally it contains 26 items when you open it. It grows as you navigate through the playlist and generally it's infinite. Downloading only 26 original items is expected behavior for now.
