### ISSUE TITLE
PHP will not execute command if warning appears.

### ISSUE THREAD

**Issue by styler2go** [rg3/youtube-dl#7062]
I ran into a bug where the execution of youtube-dl was aborted because one message was not run in stdout. The solution i used is adding ">> msg.log 2>> msg.log" to the end of the line.

More about the problem:
http://stackoverflow.com/questions/32935064/php-exec-output-does-not-return-and-execute-commands

**Comment by dstftw** [comment]
It's not a youtube-dl issue if it does work fine without PHP.
