### ISSUE TITLE
Twitch plugin not detect when failed login

### ISSUE THREAD

**Issue by Pincha** [rg3/youtube-dl#7063]
################################ Wrong password

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--hls-prefer-native', u'http://www.twitch.tv/gsl/b/682657097', u'--username', u'PRIVATE', u'-p', u'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.09.28
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[twitch:video] Downloading login page
[twitch:video] Logging in as thefatalsc
[twitch:video] 682657097: Downloading video info JSON
[twitch:video] 682657097: Downloading video playlist JSON
[download] Downloading playlist: 2015 HOT6 GSL Season 3 Code S Final
[twitch:video] playlist 2015 HOT6 GSL Season 3 Code S Final: Collected 0 video ids (downloading 0 of them)

################################ Correct password

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--hls-prefer-native', u'http://www.twitch.tv/gsl/b/682657097', u'--username', u'PRIVATE', u'-p', u'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.09.28
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[twitch:video] Downloading login page
[twitch:video] Logging in as thefatalsc
[twitch:video] 682657097: Downloading video info JSON
[twitch:video] 682657097: Downloading video playlist JSON
[download] Downloading playlist: 2015 HOT6 GSL Season 3 Code S Final
[twitch:video] playlist 2015 HOT6 GSL Season 3 Code S Final: Collected 0 video ids (downloading 0 of them)

**Comment by dstftw** [comment]
Authentication does not work at all now since they require to solve a captcha. You can workaround by passing cookies from browser as explained [here](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).

**Comment by txtsd** [comment]
It should be possible to use oauth to login like livestreamer does
