### ISSUE TITLE
[broken] adultswim 

### ISSUE THREAD

**Issue by lightonflux** [rg3/youtube-dl#7072]
youtube-dl http://www.adultswim.com/videos/rick-and-morty/the-wedding-squanchers/ --verbose     [15:12:47]
	[debug] System config: []
	[debug] User config: []
	[debug] Command-line args: [u'--add-metadata', u'-ct', u'-f', u'bestvideo[height<=?1080]+bestaudio/best', u'http://www.adultswim.com/videos/rick-and-morty/the-wedding-squanchers/', u'--verbose']
	[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
	[debug] youtube-dl version 2015.09.28
	[debug] Python version 2.7.9 - Linux-4.2.0-1-amd64-x86_64-with-debian-8.2
	[debug] exe versions: ffmpeg 2.8-1, ffprobe 2.8-1
	[debug] Proxy map: {}
	[AdultSwim] the-wedding-squanchers: Downloading webpage
	ERROR: An extractor error has occured. (caused by KeyError(u'clips',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 288, in extract
	    return self._real_extract(url)
	  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/adultswim.py", line 136, in _real_extract
	    segment_ids = [clip['videoPlaybackID'] for clip in video_info['clips']]
	KeyError: u'clips'
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
	    ie_result = ie.extract(url)
	  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 294, in extract
	    raise ExtractorError('An extractor error has occured.', cause=e)
	ExtractorError: An extractor error has occured. (caused by KeyError(u'clips',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This video requires cable service provider subscription. [Passing cookies from logged in browser](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl) may workaround this.

**Comment by lightonflux** [comment]
It worked a week ago (without cookie). Maybe they changed the authentication mechanism.

**Comment by dstftw** [comment]
They probably require subscription for recent series or so. After 20 minutes since from my post it became available without subscription.

**Comment by lightonflux** [comment]
Ah thanks.
