### ISSUE TITLE
webm is not 1fps

### ISSUE THREAD

**Issue by shawnl** [rg3/youtube-dl#7084]
'''
$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-4.2.0-14-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
$ youtube-dl -F https://www.youtube.com/watch?v=NOyUiuQRVS0
[youtube] NOyUiuQRVS0: Downloading webpage
[youtube] NOyUiuQRVS0: Extracting video information
[youtube] NOyUiuQRVS0: Downloading DASH manifest
[info] Available formats for NOyUiuQRVS0:
format code  extension  resolution note
171          webm       audio only DASH audio  132k , audio@128k (44100Hz), 83.62MiB
140          m4a        audio only DASH audio  135k , m4a_dash container, aac  @128k (44100Hz), 102.82MiB
141          m4a        audio only DASH audio  262k , m4a_dash container, aac  @256k (44100Hz), 204.20MiB
278          webm       256x144    DASH video  202k , webm container, VP9, 1fps, video only, 84.11MiB
160          mp4        256x144    DASH video  264k , 13fps, video only, 88.44MiB
133          mp4        426x240    DASH video  284k , 25fps, video only, 195.36MiB
242          webm       426x240    DASH video  286k , 1fps, video only, 119.71MiB
243          webm       640x360    DASH video  555k , 1fps, video only, 217.19MiB
134          mp4        640x360    DASH video  611k , 25fps, video only, 231.08MiB
244          webm       854x480    DASH video  954k , 1fps, video only, 362.81MiB
135          mp4        854x480    DASH video 1112k , 25fps, video only, 459.82MiB
247          webm       1280x720   DASH video 1896k , 1fps, video only, 672.37MiB
136          mp4        1280x720   DASH video 2211k , 25fps, video only, 876.16MiB
248          webm       1920x1080  DASH video 3251k , 1fps, video only, 1.14GiB
137          mp4        1920x1080  DASH video 4169k , 25fps, video only, 1.64GiB
17           3gp        176x144    
36           3gp        320x240    
5            flv        400x240    
43           webm       640x360    
18           mp4        640x360    
22           mp4        1280x720   (best)
'''

**Comment by yan12125** [comment]
It's exactly what reported by Youtube, and youtube-dl can do nothing about it.
