### ISSUE TITLE
Extractor channel9 returned a compat_list result. It needs to be updated.

### ISSUE THREAD

**Issue by ismail** [rg3/youtube-dl#7086]
I got a warning using channel 9 videos, youtube-dl version 2015.10.06.2 \:

λ youtube-dl https://channel9.msdn.com/Shows/Defrag-Tools/Defrag-Tools-142-Raymond-Chen-Old-New-Thing
[channel9] Shows/Defrag-Tools/Defrag-Tools-142-Raymond-Chen-Old-New-Thing: Downloading web page
WARNING: Extractor channel9 returned a compat_list result. It needs to be updated.
[download] Destination: Defrag Tools #142 - Raymond Chen - Old New Thing.mp4
[download]   0.2% of 955.72MiB at 896.04KiB/s ETA 18:09^C

Download is fine so I guess its a harmless warning.

**Comment by jaimeMF** [comment]
Thanks for the report, it will be fixed in the next version.
