### ISSUE TITLE
unsuported video

### ISSUE THREAD

**Issue by STR4NG3R** [rg3/youtube-dl#7101]
ERROR: Unsupported URL: https://www.youtube.com/?hl=es-419; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
This is the homepage of YouTube. You need to specify a video/channel/playlist/etc... URL.
