### ISSUE TITLE
[dailymotion] Unable to download video

### ISSUE THREAD

**Issue by micyew** [rg3/youtube-dl#7109]
Hi,

I'm having trouble downloading video clip from Dailymotion. The clip can be view from browser but it can't be download.

It always have this error "raise RegexNotFoundError('Unable to extract %s' % _name)" in the verbose output. Did I miss something or some bug in youtube-dl?

I tried Youtube clip and it works...

C:\>youtube-dl --verbose http://www.dailymotion.com/video/x38zwdy_the-world-s-steepest-400-meter-race-the-red-bull-400_sport
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.dailymotion.com/video/x38zwdy_the-world-s-steepest-400-meter-race-the-red-bull-400_sport']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.10.06.2
[debug] Python version 3.4.2 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[dailymotion] x38zwdy: Downloading webpage
[dailymotion] x38zwdy: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 290, in extract
    return self._real_extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\dailymotion.py", line 201, in _real_extract
    'video info', flags=re.MULTILINE),
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
This is fixed in git but not included in the latest stable version yet. Please wait for the next version.

**Comment by jaimeMF** [comment]
It's fixed with 54a5428518adc4ddca085bdac471bc4f286024e4, it will work in the next version, Thanks for the report!
