### ISSUE TITLE
Dailymotion unable to download video

### ISSUE THREAD

**Issue by AAnarchYsta** [rg3/youtube-dl#7128]
youtube-dl --verbose http://dai.ly/x37uo93
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://dai.ly/x37uo93']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.19.0-26-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[generic] x37uo93: Requesting header
[redirect] Following redirect to http://www.dailymotion.com/video/x37uo93_mlp-season-5-made-in-manehattan-ep-16_animals
[dailymotion] x37uo93: Downloading webpage
[dailymotion] x37uo93: Extracting information
[dailymotion] x37uo93: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/dailymotion.py", line 115, in _real_extract
    'video info', flags=re.MULTILINE)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
