### ISSUE TITLE
Failed to download on RTBF site

### ISSUE THREAD

**Issue by wwark** [rg3/youtube-dl#7133]
Hello,

There is the issue 
./youtube-dl https://www.rtbf.be/video/detail_la-regate?id=2049001 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.rtbf.be/video/detail_la-regate?id=2049001', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.09
[debug] Python version 3.5.0 - Linux-4.2.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8, rtmpdump 2.4
[debug] Proxy map: {}
[RTBF] 2049001: Downloading webpage
ERROR: Unable to extract data video; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/rtbf.py", line 39, in _real_extract
    r'data-video="([^"]+)"', webpage, 'data video')),
  File "./youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract data video; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Best regards,
Wark.

**Comment by jaimeMF** [comment]
The download should be fixed in the next version. Since the video you posted is georestricted I haven't been able to test it, but others like https://www.rtbf.be/video/detail_les-diables-au-coeur-episode-2?id=1921274 work again. If it fails to download the video you posted, please tell us and we'll reopen the issue (if you are comfortable using git I would appreciate if you could test with the version from the git repo) .
