### ISSUE TITLE
clyp.it support

### ISSUE THREAD

**Issue by 0x27** [rg3/youtube-dl#7134]
I can probably add this one myself, but its going to take a day or three to acquaint myself with the codebase properly, but if someone else gets there first or whatever thats cool :)

TL;DR, [here is my reference implementation for downloading individual files from clyp.it](https://github.com/0x27/clypdown). Its fairly straightforward.

Example URL: https://clyp.it/hrvttfzp  
Basically, you rewrite it to `https://api.clyp.it/hrvttfzp`, extract `Title` and `Mp3Url` from the JSON response, and download `Mp3Url`.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by 0x27** [comment]
Updated with example url and description of how their API is used in this instance. Still reading over some of the extractor examples, to figure out how youtube-dl does it :)

**Comment by CianLR** [comment]
Just made a pull request adding clyp.it

**Comment by dstftw** [comment]
Clyp will be supporte in the next version.
