### ISSUE TITLE
Crunchyroll Issue. Cannot download in 1080p

### ISSUE THREAD

**Issue by hdubb** [rg3/youtube-dl#7138]
I also noticed that if you type in youtube-dl -f with a lowercase f, it will not download but when it is -F with an uppercase f, it will download. I downloaded a video but it is 576p so I am trying to change it to 1080p

C:\Users\Desktop>youtube-dl -F http://www.crunchyroll.com/one-piece/episode-713-barrier-barrier-homage-holy-fist-strikes-681829
[Crunchyroll] 681829: Downloading webpage
[Crunchyroll] 681829: Downloading media info
[Crunchyroll] 681829: Downloading media info for 360p
[Crunchyroll] 681829: Checking 360p URL
[Crunchyroll] 681829: Downloading media info for 480p
[Crunchyroll] 681829: Checking 480p URL
[Crunchyroll] 681829: Downloading media info for 720p
[Crunchyroll] 681829: Checking 720p URL
[Crunchyroll] 681829: Downloading media info for 720p
[Crunchyroll] 681829: Checking 720p URL
[Crunchyroll] 681829: Downloading media info for 1080p
[Crunchyroll] 681829: Checking 1080p URL
[Crunchyroll] 681829: Downloading media info for 1080p
[Crunchyroll] 681829: Checking 1080p URL
[info] Available formats for 681829:
format code  extension  resolution note
360p         mp4        656x368
480p         mp4        848x480
720p-0       mp4        848x480
720p-1       mp4        848x480
1080p-0      mp4        848x480
1080p-1      mp4        848x480    (best)

C:\Users\Desktop>youtube-dl -F 1080p-1 http://www.crunchyroll.com/one-piece/episode-713-barrier-barrier-homage-holy-fist-strikes-681829
ERROR: u'1080p-1' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:1080p-1" ) to search YouTube

**Comment by dstftw** [comment]
`-F` is for listing formats, `-f` for selecting particular format. Correct command line is: `youtube-dl -f 1080p-1 http://www.crunchyroll.com/one-piece/episode-713-barrier-barrier-homage-holy-fist-strikes-681829`
