### ISSUE TITLE
OS X 10.11 El Capitan pip install issues, root SIP problems?

### ISSUE THREAD

**Issue by shaun10** [rg3/youtube-dl#7139]
Anyone else experiencing this? Seems the install no longer works properly after upgrade.

I guess the gist is that no user -- not even root -- can write to /usr, /bin, /System, and /sbin or debug protected processes.
![screen shot 2015-10-11 at 4 01 16 pm](https://cloud.githubusercontent.com/assets/7233643/10419613/6e826ea4-7031-11e5-9d5f-14d923b6d9b1.png)

Anyone have work around suggestions? Is the problem related to SIP changes and El Capitan?

**Comment by yan12125** [comment]
As of now you can install the package to the local user directory:
```
$ pip install --user youtube-dl
```
The script will reside at ```~/Library/Python/2.7/bin/youtube-dl```.

**Comment by yan12125** [comment]
Looks like an pip bug. I've reported it to https://github.com/pypa/pip/issues/3177.

**Comment by rishigb** [comment]
I did something rather simple (maybe stupid and it worked. I just added the path to .bash_profile. This is how it looks oh and it works!
![screen shot 2016-02-16 at 11 53 29 am](https://cloud.githubusercontent.com/assets/6417612/13068680/f99f24a6-d4a3-11e5-80a0-29932a480cc3.png)

`alias youtube-dl='/Users/userName/Library/python/2.7/bin/youtube-dl'`

Maybe give this is a shot, until everything else is fixed?
