### ISSUE TITLE
Crunchyroll Premium login not working. User not found.

### ISSUE THREAD

**Issue by hdubb** [rg3/youtube-dl#7140]
I typed
youtube-dl "-u username" "-p password" crunchyrollurl

This comes up:

[Crunchyroll] Logging in
[Crunchyroll] 681829: Downloading webpage
ERROR: crunchyroll returned error: User  username not found.

For username, I tried my email associated with my crunchyroll and the crunchyroll username. It still gives me the same message.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by hdubb** [comment]
C:\Users\H\Desktop>youtube-dl --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.10.12
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

**Comment by anasazy** [comment]
@hdubb
You should post the result of "youtube-dl -u <your username> --verbose <crunchyroll url>". ;-)

**Comment by hdubb** [comment]
For some reason, when I typed --verbose, it started working and downloaded the file.
