### ISSUE TITLE
vimeo password option is broken

### ISSUE THREAD

**Issue by joecrayne** [rg3/youtube-dl#7141]
> youtube-dl --verbose --video-password bernie2016 'https://vimeo.com/141725998'

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--video-password', u'PRIVATE', u'https://vimeo.com/141725998']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.09
[debug] Python version 2.7.10 - Linux-3.16.0-4-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 2.7.1, avprobe 2.7.1, ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 141725998: Downloading webpage
[vimeo] 141725998: Extracting information
[vimeo] 141725998: Verifying the password
ERROR: Wrong password: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/joe/bin/youtube-dl/youtube_dl/extractor/common.py", line 329, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/joe/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1872, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by joecrayne** [comment]
It says "Wrong password" but it works in the browser.

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl.
