### ISSUE TITLE
can't download youtube video!

### ISSUE THREAD

**Issue by wang20150419** [rg3/youtube-dl#7142]
ERROR: Unable to download webpage: <urlopen error [Errno 10054] > (caused by URLError(error(10054, ''),))

**Comment by yan12125** [comment]
Please post the [full verbose logwith ```-v```](https://github.com/rg3/youtube-dl/#bugs).

**Comment by yan12125** [comment]
Closing as no response for a long time. Usually error 10054 indicates unstable network environments.
