### ISSUE TITLE
cant download with brightcove format 

### ISSUE THREAD

**Issue by elad-n** [rg3/youtube-dl#7150]
brightcove format isnt downloading , with this link: 
http://reshet.tv/Shows/Survivor/videomarklist,241903/

WARNING: Falling back on generic information extractor.
[generic] videomarklist,241903: Downloading webpage
[generic] videomarklist,241903: Extracting information
[download] Destination: _-.unknown_video
[download] 100% of 109.16KiB in 00:00

**Comment by yan12125** [comment]
Superseded by #7652
