### ISSUE TITLE
[RTE Player] Unable to download JSON metadata

### ISSUE THREAD

**Issue by MrD37jncj** [rg3/youtube-dl#7157]
Hi, when i tried download video from rte.ie i get this error: Unable to download JSON metadata
<img width="1280" alt="screen shot 2015-10-13 at 1 14 39 pm" src="https://cloud.githubusercontent.com/assets/15100824/10447163/62a13d8c-71ac-11e5-9ace-54a28e101dcd.png">
But orther video is ok to download.

**Comment by jaimeMF** [comment]
For reference, the url that fails is http://www.rte.ie/player/ie/show/10478489/ (I know that copying text from the windows prompt may not be the easiest thing, but having to manually type an url is annoying and prone to errors).

I can't watch the video in the browser because it's georestricted, can you?

**Comment by MrD37jncj** [comment]
Hi, thank for reply.
In this case, i just want to download some video on rte player but i don't live in Ireland. So i search and get result that youtube-dl can download as i need but when i test some video for download it get error.
On image of first post i tested first link (full) is: http://www.rte.ie/player/ie/show/iwitness-862/10478715/ and i remove [/iwitness-862] and youtube-dl worked very good.
On second link (full) is: http://www.rte.ie/player/ie/show/home-and-away-1305/10478489/ with same method and it's get error Unable to download JSON metadata.

**Comment by jaimeMF** [comment]
Since the video is only available from Ireland, youtube-dl can't do anything. You'll need to use a proxy (or any other method that allows you to use a connection from Ireland).
