### ISSUE TITLE
Downloading video from BBC.com

### ISSUE THREAD

**Issue by harishpillay** [rg3/youtube-dl#7166]
I am trying to pull down the video from this UR: bbc.com/news/technology-34380436 and it fails.

Here's the debug output:
$ youtube-dl --verbose "http://www.bbc.com/news/technology-34380436"
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.bbc.com/news/technology-34380436']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.10 - Linux-4.1.10-200.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: ffmpeg 2.6.4, ffprobe 2.6.4, rtmpdump 2.4
[debug] Proxy map: {}
[bbc] technology-34380436: Downloading webpage
ERROR: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/bbc.py", line 725, in _real_extract
    webpage, 'playlist data'),
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 575, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
It works in the last version (2015.10.13), if the version in the Fedora repos is outdated you can [manually upgrade](https://github.com/rg3/youtube-dl/blob/bd5376c182bd5ee2103aec21144286dbefbeb797/README.md#how-do-i-update-youtube-dl).

**Comment by harishpillay** [comment]
Brilliant! Thanks for this. I did pip install --upgrade youtube-dl on my Fedora 22 system to update to the latest version and all works. Thank you.
