### ISSUE TITLE
[vier.be] Add login support

### ISSUE THREAD

**Issue by Robby-** [rg3/youtube-dl#7168]
When trying to download a video from vier.be, the following error occurs:

```
youtube-dl --verbose http://www.vier.be/deslimstemensterwereld/videos/aflevering-van-13-oktober-kathy-pauwels-kevin-janssens-en-kim-clijsters/1324756
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.vier.be/deslimstemensterwereld/videos/aflevering-van-13-oktober-kathy-pauwels-kevin-janssens-en-kim-clijsters/1324756']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.10.13
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-75976-gd59bfcd
[debug] Proxy map: {}
[vier] aflevering-van-13-oktober-kathy-pauwels-kevin-janssens-en-kim-clijsters:
Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 660, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\vier.pyo", line 43, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 584, in _search_regex
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jaimeMF** [comment]
When I try to view in the browser I get this message:
> Maak uw gratis account aan zodat u deze volledige afleveringen kunt bekijken.
> Met dit account kan u inloggen op zowel VIER en VIJF. Zo blijf je op de hoogte van de laatste nieuwtjes, kan je meespelen met onze wedstrijden en zelf reageren op onze video's en foto's.

Can you watch it in a browser without login with an account?

**Comment by Robby-** [comment]
Now that you mention it, no, you need to login first. Woops. So, I've tried specifying the login credentials with -u and -p but it still didn't work. It gave the exact same error message.

**Comment by jaimeMF** [comment]
> Now that you mention it, no, you need to login first. Woops. So, I've tried specifying the login credentials with -u and -p but it still didn't work. It gave the exact same error message.

Thanks for checking it, we'll need to add login support.

**Comment by MichaelDeBoey** [comment]
+1 for this!

**Comment by seghers** [comment]
+1

**Comment by midas02** [comment]
It seems there's a backdoor for retrieving the playlist bypassing the need for having to log in: https://bitbucket.org/basrieter/xbmc-online-tv/issues/809
