### ISSUE TITLE
[El-Capitan] Can't download and convert playlists

### ISSUE THREAD

**Issue by bisherbas** [rg3/youtube-dl#7179]
When running the command

`youtube-dl -ixv --audio-format mp3 --audio-quality 5 -o https://www.youtube.com/watch?v=6Ejga4kJUts&list=PLD6D47827CB1A4AE8`

gets stuck here:

[youtube] 6Ejga4kJUts: Downloading video info webpage
[youtube] 6Ejga4kJUts: Extracting video information
[youtube] 6Ejga4kJUts: Downloading DASH manifest
[download] Destination: The Cranberries - Zombie.f135.mp4
[download] 100% of 25.94MiB in 00:07
[download] Destination: The Cranberries - Zombie.f141.m4a
[download] 100% of 9.58MiB in 00:02
[ffmpeg] Merging formats into "The Cranberries - Zombie.mp4"
[ffmpeg] Destination: The Cranberries - Zombie.mp3

Can confirm I have write access to the folder.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by bisherbas** [comment]
Sorry I though `-v` would be sufficient.

`[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-ix', u'--verbose', u'--audio-format', u'mp3', u'--audio-quality', u'5', u'-o', u'https://www.youtube.com/watch?v=6Ejga4kJUts']
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: Cannot download a video and extract audio into the same file! Use "https://www.youtube.com/watch?v=6Ejga4kJUts.%(ext)s" instead of "https://www.youtube.com/watch?v=6Ejga4kJUts" as the output template`

**Comment by dstftw** [comment]
Correct command is `youtube-dl -ix --verbose --audio-format mp3 --audio-quality 5 'https://www.youtube.com/watch?v=6Ejga4kJUts&list=PLD6D47827CB1A4AE8'`.

**Comment by bisherbas** [comment]
Thanks.
