### ISSUE TITLE
Udemy Download not working

### ISSUE THREAD

**Issue by attiqfsd** [rg3/youtube-dl#7183]
I am trying to download udemy course that I am enrolled into but I am getting following output

[udemy:course] Downloading login popup
[udemy:course] Logging in as EMAIL
[udemy:course] create-custom-wordpress-themes-from-scratch: Downloading course JSON
[udemy:course] 308702: Enrolling in the course
[udemy:course] 308702: Downloading course curriculum
[download] Downloading playlist: Create Custom Wordpress Themes From Scratch
[udemy:course] playlist Create Custom Wordpress Themes From Scratch: Collected 47 video ids (downloading 47 of them)
[download] Downloading video 1 of 47
[udemy] Downloading login popup
[udemy] 1848740: Downloading lecture JSON
ERROR: unable to open for writing: [Errno 13] Permission denied: u'Course Introduction-2106582.mp4.part'
Can you please tell me where I am wrong?

 I am using this command
youtube-dl -u EMAIL -p PASS https://www.udemy.com/create-custom-wordpress-themes-from-scratch/learn/

**Comment by dstftw** [comment]
What is the directory you are running this command in? Do you have enough permissions for it?

**Comment by attiqfsd** [comment]
Yes I have permissions to download as I am running the command as root

**Comment by dbodily2000** [comment]
I had the same exact issue on Win7 downloading to desktop folder.  I found that malware protection was preventing YouTube-dl from running as it looked like malicious code and blocked the app.  I added YouTube-dl to the acceptable app list (block exclusion list) and it now is working beautifully.  Also run the command as Admin in Power shell (Windows system) Just FYI on my experience.
