### ISSUE TITLE
YouTube for Schools and "unable to extract uploader nickname"

### ISSUE THREAD

**Issue by gear3D** [rg3/youtube-dl#719]
Currently using YouTube for Schools (http://www.youtube.com/schools) on site. Have setup a user through the YouTube admin panel. User is able to login successfully and view content unrestricted.
Example video is allowed/unfiltered for YouTube for Schools. Also receive same error for blocked/filtered content even passed YouTube account credentials.

youtube-dl -i -ctf 22 -u USER_NAME -p PASSWORD http://www.youtube.com/watch?v=w3AdFjklR50
[youtube] Setting language
[youtube] Logging in
[youtube] Confirming age
[youtube] w3AdFjklR50: Downloading video webpage
[youtube] w3AdFjklR50: Downloading video info webpage
[youtube] w3AdFjklR50: Extracting video information
WARNING: unable to extract uploader nickname
ERROR: unexpected call to parse_endtag

youtube-dl -v[debug] youtube-dl version 2013.02.02
[debug] Python version 2.7.2+ - Linux-3.0.0-12-generic-i686-with-Ubuntu-11.10-oneiric

Couldn't see any other posts regarding YouTube for Schools restriction. Not sure if you've had to tackle this in the past.

**Comment by dstftw** [comment]
Works fine with latest version.
