### ISSUE TITLE
Feature Request: Support for vidio.com site

### ISSUE THREAD

**Issue by joglomedia** [rg3/youtube-dl#7195]
Hi all,

I want to download video from vidio.com use youtube-dl but never success.
Hope anyone can add the vidio.com to youtube-dl feature

Thanks

**Comment by yan12125** [comment]
[Please propose an example URL.](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient)

**Comment by joglomedia** [comment]
@yan12125 below the example url 

http://www.vidio.com/watch/165683-dj_ambred-booyah-live-2015

**Comment by ReyCervantes** [comment]
hello everyone!

I would like to download the following video using youtube-dl  but it says it's an unknown url. I hope anyone can help me fix this problem.

http://www.vidio.com/watch/97090-eng-sub-130130-mnet-wide-idol-arts-b1a4-ep-1-part-1-of-2
http://www.vidio.com/watch/97101-eng-sub-130130-mnet-wide-idol-arts-b1a4-ep-1-part-2-of-2
http://www.vidio.com/watch/97190-eng-sub-130206-mnet-wide-idol-arts-b1a4-ep-2-part-1-of-2
http://www.vidio.com/watch/97212-eng-sub-130206-mnet-wide-idol-arts-b1a4-ep-2-part-2-of-2
http://www.vidio.com/watch/103722-banasubbers-150325-mv-bank-stardust-b1a4-cut-eng-sub

**Comment by ReyCervantes** [comment]
Can somebody help me fix this problem 'cause I keep receiving this statements whenever I try to download  from vidio.com but not when it's from youtube itself. Can somebody please? Thank you so much and God bless for your time. ~^v^~
![picture1](https://cloud.githubusercontent.com/assets/15698886/11014884/0b126c12-8584-11e5-9ec7-bb7945157f01.png)

**Comment by dstftw** [comment]
vidio.com **is NOT** supported.

**Comment by ReyCervantes** [comment]
can it not be requested from features of youtube-dl?

**Comment by dstftw** [comment]
Can it what?

**Comment by ReyCervantes** [comment]
I mean, can't it be requested, to be added to youtube-dl's supported sites?

**Comment by dstftw** [comment]
Do you even read the title of this issue?

**Comment by ReyCervantes** [comment]
Yah. Thanks for reminding me.
