### ISSUE TITLE
Cookies missing lines after execution

### ISSUE THREAD

**Issue by felipemvieira** [rg3/youtube-dl#7196]
Hello guys,

I tried download videos from www.fixmyhog.com auth website, it redirects video to Brightcove. My steps are:

1) I logged in to the website.
2) Exported cookies using Cookie Exporter 1.5.1 - signed
3) Added "# Netscape HTTP Cookie File" (without cotes) to the file
4) And tried to execute the youtube-dl:

===== START ====
D:\Temporary Files>youtube-dl.exe --cookies cookies.txt -F --verbose http://www.fixmyhog.com/video/hd-primary-fluid-serv
ice-tc-103-009175/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--cookies', u'cookies.txt', u'-F', u'--verbose', u'http://www.fixmyhog.com/video/hd-primar
y-fluid-service-tc-103-009175/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.10.13
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[generic] hd-primary-fluid-service-tc-103-009175: Requesting header
WARNING: Falling back on generic information extractor.
[generic] hd-primary-fluid-service-tc-103-009175: Downloading webpage
[generic] hd-primary-fluid-service-tc-103-009175: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: HD Primary Fluid Service TC 103 | Fix My Hog
[generic] playlist HD Primary Fluid Service TC 103 | Fix My Hog: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Brightcove] 4449466296001: Downloading webpage
[Brightcove] 4449466296001: Extracting information
[info] Available formats for 4449466296001:
format code  extension  resolution note
0            mp4        400x224    2.36MiB
1            mp4        400x224    5.14MiB
2            mp4        480x268    7.97MiB
3            mp4        640x360    12.67MiB
4            mp4        720x404    18.83MiB
5            mp4        1280x720   28.56MiB (best)
===== END ======

My problem is the website permits to download a preview of the video without a login/password, and after you are loged in, you can download the full video. But after the youtube-dl execution, I noticied that my cookies file is modified and the lines containing login information is missing and with that I cant download full videos. Have any way to disable youtube-dl to modify the cookies file? I also tried using linux and I modified permission to chmod a-w (440) but now youtube-dl doesn´t execute using cookies.

Sorry about my mistakes in english.

**Comment by yan12125** [comment]
Currently cookies used will always be overwritten. Before "read-only cookiejars" feature is implemented, you need to backup your cookies.

**Comment by felipemvieira** [comment]
Hello Yan12125,

Thanks for the answer, but the problem is the authentication cookies is missing after the execution and maybe this is the cause that prevents to download the full videos from the website.

**Comment by felipemvieira** [comment]
For information, I tried download the videos through an old version (2015.01.11) and now it is OK (showing videos for premium users). Maybe there is a bug with cookies in early versions.

====== START ======
D:\Temporary Files>youtube-dl.exe --version
2015.01.11
D:\Temporary Files>youtube-dl.exe --cookies cookies.txt -F --verbose http://www.fixmyhog.com/video/hd-primary-fluid-service-tc-103-009175/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', '-F', '--verbose', 'http://www.fixmyhog.com/video/hd-primary-fluid-service-tc-103-009175/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.01.11
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[generic] hd-primary-fluid-service-tc-103-009175: Requesting header
WARNING: Falling back on generic information extractor.
[generic] hd-primary-fluid-service-tc-103-009175: Downloading webpage
[generic] hd-primary-fluid-service-tc-103-009175: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: HD Primary Fluid Service TC 103 | Fix My Hog
[generic] playlist HD Primary Fluid Service TC 103 | Fix My Hog: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Brightcove] 4449466303001: Downloading webpage
[Brightcove] 4449466303001: Extracting information
[info] Available formats for 4449466303001:
format code extension resolution  note
0           mp4       400x224     19.99MiB (worst)
1           mp4       400x224     42.90MiB
2           mp4       480x268     66.65MiB
3           mp4       640x360     106.88MiB
4           mp4       720x404     159.16MiB
5           mp4       1280x720    238.73MiB (best)
====== END ======

**Comment by mpenkov** [comment]
Looks like the problem is resolved and this issue can be closed.
