### ISSUE TITLE
Vimeo URLs returning .m3u8 using -g flag

### ISSUE THREAD

**Issue by oddmouse** [rg3/youtube-dl#7200]
I just noticed that Vimeo URLs have started returning .m3u8 when using the -g flag. By removing the extension it looks like the correct .mp4 URL that was previously returned.

Some examples:
```bash
youtube-dl -g https://vimeo.com/11470077
# -> https://15-lvl3-hls.vimeocdn.com/1445036443-ec11a7c94ab823d5db68f4c0e6dd11e2a0f351aa/01/2294/0/11470077/20292872.mp4.m3u8
```
```bash
youtube-dl -g https://vimeo.com/15697984
# -> https://13-lvl3-hls.vimeocdn.com/1445036099-241b3e046f8c95c712a5ca06499a8155d7e39c91/01/3139/0/15697984/30033083.mp4.m3u8
```

**Comment by dstftw** [comment]
hls formats are now also extracted. Since hls has better quality according to metadata it's listed as best and returned in `-g`. Use `-F` and `-f` to select other formats.
