### ISSUE TITLE
Support hqporner.com

### ISSUE THREAD

**Issue by codeballarina23** [rg3/youtube-dl#7201]
There is a nice and clean website called hqporner. Sadly youtube-dl doesn't have a extractor at the moment and generic doesn't work too. 

Would be awesome of you if you put support for hqporner.com into the program.

Thanks

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by codeballarina23** [comment]
Thanks for fast answer. 

Here example URL: http://hqporner.com/hdporn/80371-Orgasmic_massage_for_Emily_Bloom.html

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by codeballarina23** [comment]
I looked at the ToS but they only talk about user submissions and what user "aren't allowed" to submit. But nothing that strong enough to fit yt-dls requirements i think. So if nobody else finds a sufficient notice...
