### ISSUE TITLE
Bind to specific IP

### ISSUE THREAD

**Issue by Kottalizer** [rg3/youtube-dl#721]
Hi. How can I bind youtube-dl so that it uses a specific IP/interface, instead of the default one, while downloading?

**Comment by phihag** [comment]
Starting from youtube-dl 2015.01.10.1, you can make use of the [`--source-address` option](https://github.com/rg3/youtube-dl/blob/master/README.md#network-options). See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by codaman** [comment]
has anybody tried --source-adress option ? i cant use it

youtube-dl.exe --source-adsress [IP] -g [url]  not working

**Comment by dstftw** [comment]
@codaman open a new issue with [all necessary information](https://github.com/rg3/youtube-dl#bugs).

**Comment by codaman** [comment]
may be it is not a problem may be its my fault. youtube-dl.exe --source-adsress [IP] -g [url] is correct ?

**Comment by phihag** [comment]
@codaman How do you expect us to diagnose the problem when you don't show us even the error message? In any case, to answer your question, yes, I have tried the `--source-address` option after writing it. Also note that you seem to mistype it, it is `--source-address`, not `--source-adsress`.

**Comment by codaman** [comment]
youtube-dl --source-address 195.46.137.11 -g https://www.youtube.com/watch?v=R-qlQe8R2Cs

i'm getting this error

ERROR: Unable to download webpage: <urlopen error [Errno 49] Can't assign requested address> (caused by URLError(error(49, "Can't assign requested address"),))

**Comment by phihag** [comment]
@codaman Please [open a new issue](https://github.com/rg3/youtube-dl/issues/new).

**Comment by codaman** [comment]
@phihag thank you for advice. i've created a new issue
