### ISSUE TITLE
[Bandcamp]: ValueError: unknown url type

### ISSUE THREAD

**Issue by nick-s-b** [rg3/youtube-dl#7216]
Hello,
I started getting an error when trying to download bandcamp mp3 files with youtube-dl. For example, if you try to grab this URL  `http://phonelosers.bandcamp.com/track/i-need-my-medication` you will get an error that looks something like this: `ValueError: unknown url type: //popplers5.bandcamp.com/download/track...`
Thanks!

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
