### ISSUE TITLE
Debian want work caused by ValueError('No JSON object could be decoded',)

### ISSUE THREAD

**Issue by Sturmkater** [rg3/youtube-dl#7222]
First of all, thank you very much for your work!! On my mac it works like charm. I just struggle with my Raspberry. Since the repo version is outdated I installed it from your source, now it's up to date. But with a normal request I get: 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-config', u'--verbos', u'https://soundcloud.com/chloebaiano/best-before-final']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.16
[debug] Python version 2.7.9 - Linux-4.1.4v7-aufs-armv7l-with-debian-8.0
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] chloebaiano/best-before-final: Resolving id
[soundcloud] chloebaiano/best-before-final: Downloading info JSON
ERROR: Unable to download JSON metadata: <urlopen error [Errno 110] Connection timed out> (caused by URLError(error(110, 'Connection timed out'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 329, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1872, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 669, in http_open
    req)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)

When I go out over the school proxy: 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-config', u'--proxy', u'proxy.ethz.ch:3128', u'--no-check-certificate', u'--verbos', u'https://soundcloud.com/chloebaiano/best-before-final']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.16
[debug] Python version 2.7.9 - Linux-4.1.4v7-aufs-armv7l-with-debian-8.0
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {u'http': u'proxy.ethz.ch:3128', u'https': u'proxy.ethz.ch:3128'}
[soundcloud] chloebaiano/best-before-final: Resolving id
[soundcloud] chloebaiano/best-before-final: Downloading info JSON
ERROR: chloebaiano/best-before-final: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 483, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/soundcloud.py", line 244, in _real_extract
    info = self._download_json(info_json_url, full_title, 'Downloading info JSON')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 477, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 487, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: chloebaiano/best-before-final: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks for your help!

**Comment by dstftw** [comment]
Looks like connectivity issue. Can you access http://api.soundcloud.com/resolve.json?url=http://soundcloud.com/chloebaiano/best-before-final&client_id=02gUJC0hH2ct1EGOcYXQIzRFU91c72Ea from browser?

**Comment by Sturmkater** [comment]
Thanks for your answer. I don't have an User Interface installed, so no browser. Or are there command line browser out there? When I ping it, I get:

# ping: unknown host http://api.soundcloud.com/resolve.json?url=http://soundcloud.com/chloebaiano/best-before-final


Am 18.10.2015 um 15:03 schrieb Sergey M. <notifications@github.com>:

http://api.soundcloud.com/resolve.json?url=http://soundcloud.com/chloebaiano/best-before-final&client_id=02gUJC0hH2ct1EGOcYXQIzRFU91c72Ea <http://api.soundcloud.com/resolve.json?url=http://soundcloud.com/chloebaiano/best-before-final&client_id=02gUJC0hH2ct1EGOcYXQIzRFU91c72Ea>

**Comment by dstftw** [comment]
You can use wget or curl.

**Comment by dstftw** [comment]
Closing due to no response for a long time.
