### ISSUE TITLE
Dump json gives .m3u8 as url, not a video url

### ISSUE THREAD

**Issue by dban0001** [rg3/youtube-dl#7227]
I want to create a small gui for myself to enter a link and get the download link, but when I run youtube-dl --dump-json -f mp4 with some sites like Vimeo, it just gives me this as output:

    "url":"https://skyfire.vimeocdn.com/1445205097-0xc2bb37c4f1cb4c47210b7310747089f170d0a7bf/142216434/video/426773413/playlist.m3u8"

When I open it in the browser, it downloads the m3u8 playlists instead of the expected mp4 video. In the formats field are .mp4s available, that's why I'm wondering why it also doesn't work with `-f best` and no `-f` at all.

**Comment by dstftw** [comment]
Not all formats are direct links to files. You can select different format with `-F` and `-f format_code`.

**Comment by dban0001** [comment]
Ok thank you for the fast response.
