### ISSUE TITLE
stream url of some youtube video does not play in Video.js

### ISSUE THREAD

**Issue by uhfg123** [rg3/youtube-dl#7230]
I am using youtube-dl to get the stream url by info.url and send this stream url to video js to play the video on browser. Most of the stream url work fine but there are some stream url which do not work and give 403 forbidden error in console window of browser. How Can i play these not working stream url?
Not working stream url example:
www.youtube.com/watch?v=9wZhiAdQ2RA
www.youtube.com/watch?v=lOSe5SkMCOs
Also, In my country youtube is blocked. when i use a vpn then not working stream url work.But most work without vpn.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by uhfg123** [comment]
here is working stream url
link:www.youtube.com/watch?v=pU9Q6oiQNd0
stream url
https://r5---sn-25g7sne7.googlevideo.com/videoplayback?expire=1445250199&ipbits=0&mm=31&itag=18&ratebypass=yes&requiressl=yes&lmt=1429964183493638&signature=158C27A2F8C975D7A68662C3A9C1A7C01D7D8142.E2F8486C3D4D7F546CB9392E410198BE2054838D&mime=video%2Fmp4&pl=20&id=o-AEKWngfOny_L35xBT4q-B1VcBnIOemcMpYYGR1VsuuJF&dur=784.648&sver=3&mt=1445228497&ms=au&mv=m&source=youtube&sparams=dur%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9406012%2C9408710%2C9409207%2C9414764%2C9414875%2C9416126%2C9416729%2C9417707%2C9418401%2C9418702%2C9419063%2C9419444%2C9419838%2C9421253%2C9422339%2C9422562&mn=sn-25g7sne7&ip=104.155.18.208&key=yt6&upn=f7kZ2lPoDso

Becuase In my country youtube is blocked.
so in above stream url, i have to change "googlevideo" with "c.docs.google" and i put this change url in html5/videosjs player and the video starts to play without using vpn like hotspotsheild.
But some stream url do not work. 
Not working stream url
link:www.youtube.com/watch?v=9wZhiAdQ2RA
stream url:
https://r1---sn-25g7sn76.googlevideo.com/videoplaybackgcr=us&itag=18&requiressl=yes&expire=1445249458&key=yt6&fexp=9405264%2C9405988%2C9406851%2C9408710%2C9409207%2C9414764%2C9416126%2C9416555%2C9417629%2C9417707%2C9418204%2C9418400%2C9418438%2C9419038%2C9419354%2C9421169%2C9421941%2C9422453%2C9422487%2C9422908%2C9422921%2C9422948&source=youtube&dur=2523.614&ratebypass=yes&lmt=1416954902575945&upn=w78AVpWZpHs&ipbits=0&mn=sn25g7sn76&ip=104.155.18.208&mm=31&ms=au&mv=m&mt=1445227746&sparams=dur%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&pl=20&id=o-AMOY237H0_Es7Tr5ZbK5fPko6KCcj2cKU2alAyZEH&mime=video%2Fmp4&sver=3&signature=75689815AF9C6C32680A57901F170C0C40749627.93842F453F6B378F658672EFD47F5829E4F1ABA9

For this stream url i tried the above method i.e. i relaced "googlevideo" with "c.docs.google" and put this changed url in html5/videojs player but this does not play the video and the error is 403 forbidden. This stream url work by using vpn like hotspot sheild only.
So, Why stream url for some videos does not work using ?
How  can I play these not working stream url?

**Comment by jaimeMF** [comment]
> How can I play these not working stream url witout using vpn?

If your browser can't play the video from the YouTube page, there's nothing youtube-dl can do (keep in mind that we reproduce what the browser does, so we can't support modifying the video url).
