### ISSUE TITLE
Doesn't support Inc.com videos yet. I'd like to help if i can

### ISSUE THREAD

**Issue by sumanthneerumalla** [rg3/youtube-dl#7231]
I find myself wishing i could access the videos on Inc.com more often without having to use their slightly clunky interface when switching between videos, but the website isn't supported. I know python but i'm still new to working on programming projects. I've tried looking at the source code but i'm not sure where to start on understanding how the code in this project works. Any help would be appreciated.

If anyone else has the experience to know how to go about doing this or already is doing this, please let me know as i'd like to get a better understanding of this project.

**Comment by yan12125** [comment]
[Developer instructions](https://github.com/rg3/youtube-dl/#developer-instructions) may provide what you need.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by yan12125** [comment]
Closing due to no response for a long time.
