### ISSUE TITLE
downloads disappear after finished

### ISSUE THREAD

**Issue by LandisTwo** [rg3/youtube-dl#7232]
Hello, I've Never had any luck with yt-dl working.
recent version from opensuse / packman, has finally started downloading whole files, but...
After download is finished, there is NO 'new' file in the directory i chose, nor, well anywhere.
I've searched with kfind and console, find and No new files, no files resembling the dl file name.

Why?
Landis.

opensuse 13.2 up to date, kde 4.14.x up to date, youtube-dl version 2015.10.16 using firefox 43 to drag link from to youtube-dl applet on desktop.

**Comment by jaimeMF** [comment]
> using firefox 43 to drag link from to youtube-dl applet on desktop.

That can be the problem, youtube-dl downloads by default the video to the directory where it's called from. Which applet are you using? Do you actually have any problem when directly calling youtube-dl from the command line?

As explained in the [bug reporting instructions](https://github.com/rg3/youtube-dl/blob/2038ad6ee71c842420b83cb6c5ce3c6898e8e380/README.md#bugs) post the full output you get when running `youtube-dl --verbose THE_URL`.

**Comment by LandisTwo** [comment]
thank you for replying...
when you say 'which applet are you using?' - what do you mean by applet? youtube-dl version?
in the ~/.config/youtube-dl-applet/ last-dir indicates the ~/Downloads/Media/ directory I chose.
during download, YT-dl has progress bar and it looks as if it is downloading the file.

When you say, 'downloads by default the ... dir called from' - so would that be firefox directory and being ff is a system directory the file can't be written with user rights? Would it be different if I ran a development version of FF Aurora, installed in user's home dir?

Thank You. I wll read the 'bug reporting inst' and run the --v url command. in a little while.
Landis.

**Comment by LandisTwo** [comment]
I am running youtube-dl --verbose from the command line, working in /home/landis/ dir. so I have permission to write file. ETA is 40+ mins, so I can't give you more, right now.
Destination: FileName.mp4 (i'm assuming current dir /home/landis/FileName.mp4, yes?)

Landis.

**Comment by jaimeMF** [comment]
Since you said 
> using firefox 43 to drag link from to youtube-dl applet on desktop.

I thought you were using some kind of wrapper of youtube-dl. I think that's the case, because `~/.config/youtube-dl-applet/` is not used by youtube-dl (the config file is `~/.config/youtube-dl/config`).

> YT-dl has progress bar and it looks as if it is downloading the file

Could you copy the output? It would help.

> When you say, 'downloads by default the ... dir called from' - so would that be firefox directory and being ff is a system directory the file can't be written with user rights? Would it be different if I ran a development version of FF Aurora, installed in user's home dir?

If you open a terminal and run `cd ~/Downloads/Media`, when running youtube-dl the video is downloaded to `~/Downloads/Media`. But to be honest I can't know how Firefox is calling youtube-dl.

>  I am running youtube-dl --verbose from the command line, working in /home/landis/ dir. so I have permission to write file. ETA is 40+ mins, so I can't give you more, right now.
Destination: FileName.mp4 (i'm assuming current dir /home/landis/FileName.mp4, yes?)

Yes, it should be in `/home/landis/`, you can run `ls /home/landis/*.mp4.part` from other terminal window to verify it.

**Comment by LandisTwo** [comment]
> ~/.config/youtube-dl/config
I don't have this dir. Only ~/.config/youtube-dl-applet/ with the 3 files talked about in Documentation (https://github.com/rg3/youtube-dl/blob/master/README.md#configuration) 

> If you open a terminal and run cd ~/Downloads/Media, when running youtube-dl the video is ....
Yes, I know I saw the file in ~/Downloads/Media/FileName.mp4.part and the size was increasing.

> .... you can run ls /home/landis/*.mp4.part from other terminal window to verify it.
Yes I can view the portion of the file, thus far downloaded.

I guess we will see if it is an issue of using 'system' version of firefox to initiate the download, in about 24 mins. I should have used a smaller file, but I wanted to 'compare apples to apples' running YT-dl from command line (terminal) vs from Firefox.

Thanks again.
Landis.

**Comment by LandisTwo** [comment]
jaimeMF - So, running youtube-dl (YT-dl) from command line (terminal in KDE, opensuse) and saving to a 'User Owned' directory, the FileName.mp4 file remains, is saved, and is not lost.

I am going to run the same test using Aurora (firefox developer edition) run from my ~/USERDir and see if dragging the URL from Aurora to YouTube-DL residing on my desktop (KDE Plasma) will result in the downloaded file remaining after download is complete... I'll let you know. 
It makes sense that 'default save location' is where YT-dl is called from, but it asked me where I wanted to save it and during the DL process indicated it was saving it in chosen UserDir, and I could see it there as FileName.mp4.part... So, why did it disappear and why can I find no trace in temp/ tmp/ Temp/ ? 

Thanks again, 
Landis.

**Comment by dstftw** [comment]
I'm closing this issue since it works fine from command line therefore not a youtube-dl issue. You may want to file a bug to issue tracker of whatever applet you are using.

**Comment by LandisTwo** [comment]
jaimeMF - thanks for your help.
Landis.
