### ISSUE TITLE
Unable to download video data (SSLError: [Errno 1] _ssl.c:1429: error:1408F119:SSL)

### ISSUE THREAD

**Issue by xiaose** [rg3/youtube-dl#7235]
This error does not appear every time. Usually only 1 of 3/4 times and not for all URLs

*$ youtube-dl.exe* --version
```
2015.10.18
```
*$ youtube-dl.exe* --verbose -f 22 https://www.youtube.com/watch?v=KciWtUav65M
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-f', u'22', u'https://www.youtube.com/watch?v=KciWtUav65M']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.04.26
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-60835-ga3a4d07, ffprobe N-60835-ga3a4d07
[debug] Proxy map: {}
[youtube] KciWtUav65M: Downloading webpage
[youtube] KciWtUav65M: Extracting video information
[youtube] KciWtUav65M: Downloading DASH manifest
[debug] Invoking downloader on u'https://r7---sn-8xgp1vo-2ia6.googlevideo.com/videoplayback?initcwndbps=2167500&requiressl=yes&mime=video%2Fmp4&key=yt6&signature=8EE1008B3FA1FA4A04BCC3196F83C7F6357D5A4E.2DB8DE4FDC9DAB8058B0F6E028FB55BBBDD140C2&ratebypass=yes&fexp=9406004%2C9406813%2C9407704%2C9408710%2C9413311%2C9414764%2C9415436%2C9416126%2C9416729%2C9417707%2C9419292%2C9419966%2C9420584%2C9421166%2C9421290%2C9421512%2C9422899&ip=71.185.233.154&ms=au&mt=1445265604&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mv=m&id=o-AAgKQ34nzz0ucdI_SiXrATReFiQnVduBHwnUGCjfMtvt&mm=31&mn=sn-8xgp1vo-2ia6&pcm2cms=yes&upn=vYWIO24VlcQ&source=youtube&pl=16&itag=22&lmt=1415825572395523&sver=3&ipbits=0&dur=292.850&expire=1445287297'
[download] Destination: Alastair James _ Diamonds on the Soles of Her Shoes _ [Paul Simon Cover] - YCG S
essions Demo #3-KciWtUav65M.mp4
[download]  76.2% of 81.98MiB at  3.64MiB/s ETA 00:05 ERROR: unable to download video data: [Errno 1] _s sl.c:1429: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1414, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1363, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 150, in real_download
  File "socket.pyo", line 380, in read
  File "httplib.pyo", line 567, in read
  File "socket.pyo", line 380, in read
  File "ssl.pyo", line 246, in recv
  File "ssl.pyo", line 165, in read
SSLError: [Errno 1] _ssl.c:1429: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad re
cord mac
```

**Comment by dstftw** [comment]
>[debug] youtube-dl version 2015.04.26

You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by xiaose** [comment]
Okay...

$ youtube-dl.exe --verbose https://www.youtube.com/watch?v=KciWtUav65M -f 22
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=KciWtUav65M', u'-f', u'22']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.10.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-60835-ga3a4d07, ffprobe N-60835-ga3a4d07
[debug] Proxy map: {}
[youtube] KciWtUav65M: Downloading webpage
[youtube] KciWtUav65M: Downloading video info webpage
[youtube] KciWtUav65M: Extracting video information
[youtube] KciWtUav65M: Downloading DASH manifest
[youtube] KciWtUav65M: Downloading DASH manifest
[debug] Invoking downloader on u'https://r7---sn-8xgp1vo-2ia6.googlevideo.com/videoplayback?upn=FzFBW0sT3WY&ipbits=0&pcm2cms=yes&pl=16&source=youtube&signature=7C41B3BA5C113A2894C9567D479BE5DB0681ADA6.647F41BF59BC3D45D3915941E433BC8AC72AD35C&mt=1445274525&mv=m&ms=au&mm=31&mn=sn-8xgp1vo-2ia6&id=o-ALViqRhPxmTohKlEWnlU97DyGfZpq12YxTmr9Gpf1MW5&initcwndbps=2138750&mime=video%2Fmp4&key=yt6&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ip=71.185.233.154&expire=1445296160&fexp=9405994%2C9408710%2C9408940%2C9413011%2C9413140%2C9414764%2C9416126%2C9417630%2C9417707%2C9418400%2C9418702%2C9419399%2C9422508&lmt=1415825572395523&dur=292.850&itag=22&ratebypass=yes&sver=3&requiressl=yes'
[download] Destination: Alastair James _ Diamonds on the Soles of Her Shoes _ [Paul Simon Cover] - YCG S
essions Demo #3-KciWtUav65M.mp4
[download]  54.2% of 81.98MiB at  3.12MiB/s ETA 00:12 ERROR: unable to download video data: [Errno 1] _s
sl.c:1429: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1598, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1540, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 164, in real_download
  File "socket.pyo", line 380, in read
  File "httplib.pyo", line 567, in read
  File "socket.pyo", line 380, in read
  File "ssl.pyo", line 246, in recv
  File "ssl.pyo", line 165, in read
SSLError: [Errno 1] _ssl.c:1429: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac
```

**Comment by xiaose** [comment]
And this error happend only on Win comp and only in US. If I run it, for example, in Ukraine - no error!

**Comment by mrbryce** [comment]
similar issue with latest version, can you re-open or advise on possible setup issue ?

> PS ------\captvty\tools> .\youtube-dl.exe -v https://www.youtube.com/watch?v=cZXWAl2epCs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=cZXWAl2epCs']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-10
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[youtube] cZXWAl2epCs: Downloading webpage
[youtube] cZXWAl2epCs: Downloading video info webpage
[youtube] cZXWAl2epCs: Extracting video information
[youtube] cZXWAl2epCs: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r3---sn-25glenes.googlevideo.com/videoplayback---------------------------------------------
[download] Resuming download at byte 29784161
-------------------------------------------
[download]  35.8% of 121.54MiB at  2.46MiB/s ETA 00:31 ERROR: unable to download video data: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1748)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 1892, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 1831, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\http.py", line 287, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\http.py", line 180, in download
  File "C:\Python\Python34\lib\http\client.py", line 537, in read
  File "C:\Python\Python34\lib\http\client.py", line 576, in readinto
  File "C:\Python\Python34\lib\socket.py", line 378, in readinto
  File "C:\Python\Python34\lib\ssl.py", line 748, in recv_into
  File "C:\Python\Python34\lib\ssl.py", line 620, in read
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1748)

>
