### ISSUE TITLE
[--embed-thumbnail] ERROR: No such file or directory

### ISSUE THREAD

**Issue by AhmedKamal20** [rg3/youtube-dl#7238]
$ youtube-dl -x -i --audio-format mp3 --audio-quality 320K --embed-thumbnail p0OX_8YvFxA
[youtube] p0OX_8YvFxA: Downloading webpage
[youtube] p0OX_8YvFxA: Downloading video info webpage
[youtube] p0OX_8YvFxA: Extracting video information
[youtube] p0OX_8YvFxA: Downloading js player new-en_US-vflDpriqR
[youtube] p0OX_8YvFxA: Downloading DASH manifest
[youtube] p0OX_8YvFxA: Downloading thumbnail ...
[youtube] p0OX_8YvFxA: Writing thumbnail to: Heart Barracuda-p0OX_8YvFxA.jpg
[download] Destination: Heart Barracuda-p0OX_8YvFxA.m4a
[download] 100% of 8.04MiB in 00:07
[ffmpeg] Correcting container in "Heart Barracuda-p0OX_8YvFxA.m4a"
[avconv] Destination: Heart Barracuda-p0OX_8YvFxA.mp3
Deleting original file Heart Barracuda-p0OX_8YvFxA.m4a (pass -k to keep)
[ffmpeg] Adding thumbnail to "Heart Barracuda-p0OX_8YvFxA.mp3"
**ERROR**: file:Heart Barracuda-p0OX_8YvFxA.jpg: No such file or directory

**Comment by jaimeMF** [comment]
Post the [full output you get if you add the `-v` option](https://github.com/rg3/youtube-dl/blob/2038ad6ee71c842420b83cb6c5ce3c6898e8e380/README.md#bugs).

**Comment by AhmedKamal20** [comment]
$ youtube-dl -x -i --audio-format mp3 --audio-quality 320K --embed-thumbnail p0OX_8YvFxA -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-x', u'-i', u'--audio-format', u'mp3', u'--audio-quality', u'320K', u'--embed-thumbnail', u'p0OX_8YvFxA', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.18
[debug] Python version 2.7.6 - Linux-3.13.0-66-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] p0OX_8YvFxA: Downloading webpage
[youtube] p0OX_8YvFxA: Downloading video info webpage
[youtube] p0OX_8YvFxA: Extracting video information
[youtube] {43} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {18} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {5} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {36} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {17} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {135} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {244} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {134} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {243} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {133} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {242} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {160} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {278} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {140} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {171} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {249} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {250} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] {251} signature length 40.43, html5 player new-en_US-vflDpriqR
[youtube] p0OX_8YvFxA: Downloading DASH manifest
[youtube] p0OX_8YvFxA: Downloading thumbnail ...
[youtube] p0OX_8YvFxA: Writing thumbnail to: Heart Barracuda-p0OX_8YvFxA.jpg
[debug] Invoking downloader on 'https://r3---sn-uxaxjvhxbt2u-j5pz.googlevideo.com/videoplayback?id=a74397ffc62f1710&itag=141&source=youtube&requiressl=yes&mm=31&mn=sn-uxaxjvhxbt2u-j5pz&ms=au&mv=m&pl=19&ratebypass=yes&mime=audio/mp4&gir=yes&clen=8429726&lmt=1432891284841309&dur=264.382&upn=36cXrKAxE-U&key=dg_yt0&mt=1445283748&fexp=9407537,9408710,9412840,9413208,9414764,9414929,9416126,9417707,9418612,9418897,9419445,9420016,9420239,9421097,9422675,9422678,9422864&signature=3B641593CDC90671FAB21677B7D89E13FD7C2347.48AD10585FF0F3B5D9DE6A610AA528DC8835EC1C&sver=3&ip=41.36.7.129&ipbits=0&expire=1445305477&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Heart Barracuda-p0OX_8YvFxA.m4a
[download] 100% of 8.04MiB in 01:40
[ffmpeg] Correcting container in "Heart Barracuda-p0OX_8YvFxA.m4a"
[debug] ffmpeg command line: avconv -y -i 'file:Heart Barracuda-p0OX_8YvFxA.m4a' -c copy -f mp4 'file:Heart Barracuda-p0OX_8YvFxA.temp.m4a'
[debug] avconv command line: avprobe -show_streams 'file:Heart Barracuda-p0OX_8YvFxA.m4a'
[avconv] Destination: Heart Barracuda-p0OX_8YvFxA.mp3
[debug] ffmpeg command line: avconv -y -i 'file:Heart Barracuda-p0OX_8YvFxA.m4a' -vn -acodec libmp3lame -b:a 320k 'file:Heart Barracuda-p0OX_8YvFxA.mp3'
Deleting original file Heart Barracuda-p0OX_8YvFxA.m4a (pass -k to keep)
[ffmpeg] Adding thumbnail to "Heart Barracuda-p0OX_8YvFxA.mp3"
[debug] ffmpeg command line: avconv -y -i 'file:Heart Barracuda-p0OX_8YvFxA.mp3' -i 'file:Heart Barracuda-p0OX_8YvFxA.jpg' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:Heart Barracuda-p0OX_8YvFxA.temp.mp3'
ERROR: file:Heart Barracuda-p0OX_8YvFxA.jpg: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1712, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/embedthumbnail.py", line 50, in run
    self.run_ffmpeg_multiple_files([filename, thumbnail_filename], temp_filename, options)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 154, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

**Comment by jaimeMF** [comment]
This only happens with avconv, ffmpeg works fine, it can be "fixed" by removing the `file:` prefix. The bug should be reported to the libav developers.

If you have ffmpeg installed you can force youtube-dl to use it with `--prefer-ffmpeg`.

**Comment by plombix** [comment]
Dosent work with ffmpe either

**Comment by jaimeMF** [comment]
@plombix seems to work fine for me (with ffmpeg, it fails with avconv), [read this](https://github.com/rg3/youtube-dl/blob/6bb266693f4b8cd92e27ea0efd46356dc254115b/README.md#bugs) and open a new issue with the requested information.
