### ISSUE TITLE
SoundCloud downloads are only 128 kbps

### ISSUE THREAD

**Issue by DiamondKing099** [rg3/youtube-dl#7245]
When downloading SoundCloud tracks with youtube-dl, the bit rate is only 128 kbps. I'm able to download them at 320 kbps through another site.

Not sure if this is an issue or not, but it would be great if we could get higher quality downloads from SoundCloud.

**Comment by jaimeMF** [comment]
[As explained in the bug reporting instructions](https://github.com/rg3/youtube-dl/blob/2038ad6ee71c842420b83cb6c5ce3c6898e8e380/README.md#bugs): post an example URL and the output of `youtube-dl --verbose THE_URL`.

**Comment by dstftw** [comment]
SoundCloud [transcodes everything down to 128 kbps](http://help.soundcloud.com/customer/en/portal/articles/94796-i-just-uploaded-and-my-track-is-distorted-), you can't download anything higher. Most likely another site upconverts to 320 or provides media from another source.
