### ISSUE TITLE
"An extractor error has occured. (caused by KeyError(u'clips',));"

### ISSUE THREAD

**Issue by raincoats** [rg3/youtube-dl#7246]
Hi, I got this error and it told me to submit it here. [Here's the log.](https://gist.github.com/raincoats/31996a1529213e2fb28f)

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by raincoats** [comment]
ahah, sorry. it's early where i am.
