### ISSUE TITLE
Can't download artwork from SoundCloud

### ISSUE THREAD

**Issue by DiamondKing099** [rg3/youtube-dl#7247]
Here's the output:

C:\Users\owner\Music\Downloader>youtube-dl --embed-thumbnail https://soundcloud.
com/luka_v/oliver-heldens-shades-of-grey-luka-v-remix-1
[soundcloud] luka_v/oliver-heldens-shades-of-grey-luka-v-remix-1: Resolving id
[soundcloud] luka_v/oliver-heldens-shades-of-grey-luka-v-remix-1: Downloading in
fo JSON
[soundcloud] 229099825: Downloading track url
[soundcloud] 229099825: Checking fallback video format URL
[soundcloud] 229099825: Checking http_mp3_128_url video format URL
[soundcloud] 229099825: Downloading thumbnail ...
WARNING: Unable to download thumbnail "https://i1.sndcdn.com/artworks-0001332291
50-o0dmz2-t500x500.jpg": <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL
 routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
[download] Oliver Heldens - Shades Of Grey (Luka V Remix)-229099825.mp3 has alre
ady been downloaded
[download] 100% of 4.49MiB
[ffmpeg] Adding metadata to 'Oliver Heldens - Shades Of Grey (Luka V Remix)-2290
99825.mp3'
WARNING: Skipping embedding the thumbnail because the file is missing.

It does this with all SoundCloud tracks that I've tried so far.

**Comment by jaimeMF** [comment]
[As explained in the bug reporting instructions](https://github.com/rg3/youtube-dl/blob/2038ad6ee71c842420b83cb6c5ce3c6898e8e380/README.md#bugs) post  the output of `youtube-dl --verbose https://soundcloud.com/luka_v/oliver-heldens-shades-of-grey-luka-v-remix-1 --embed-thumbnail`
It works fine for me, can you see https://i1.sndcdn.com/artworks-000133229150-o0dmz2-t500x500.jpg with a browser.

**Comment by dstftw** [comment]
That's due to python 2.7.8 shipped with windows build.

**Comment by DiamondKing099** [comment]
Here's the verbose output:

C:\Users\owner\Music\Downloader>youtube-dl --verbose https://soundcloud.com/luka
_v/oliver-heldens-shades-of-grey-luka-v-remix-1 --embed-thumbnail
[debug] System config: []
[debug] User config: [u'--add-metadata', u'--audio-quality', u'0']
[debug] Command-line args: [u'--verbose', u'https://soundcloud.com/luka_v/oliver
-heldens-shades-of-grey-luka-v-remix-1', u'--embed-thumbnail']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.10.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-76144-ge91cd8a, ffprobe N-76144-ge91cd8a
[debug] Proxy map: {}
[soundcloud] luka_v/oliver-heldens-shades-of-grey-luka-v-remix-1: Resolving id
[soundcloud] luka_v/oliver-heldens-shades-of-grey-luka-v-remix-1: Downloading in
fo JSON
[soundcloud] 229099825: Downloading track url
[soundcloud] 229099825: Checking fallback video format URL
[soundcloud] 229099825: Checking http_mp3_128_url video format URL
[soundcloud] 229099825: Downloading thumbnail ...
WARNING: Unable to download thumbnail "https://i1.sndcdn.com/artworks-0001332291
50-o0dmz2-t500x500.jpg": <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL
 routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
[debug] Invoking downloader on u'https://ec-media.sndcdn.com/wTz60do2STuo.128.mp
3?f10880d39085a94a0418a7ef69b03d522cd6dfee9399eeb9a52205996cffbd3d20d34cc6a5f3a0
e5d5b430fb214d9aa4370cf7ca9b580dab37487411d14ffef1c77e373bb4'
[download] Oliver Heldens - Shades Of Grey (Luka V Remix)-229099825.mp3 has alre
ady been downloaded
[download] 100% of 4.49MiB
[ffmpeg] Adding metadata to 'Oliver Heldens - Shades Of Grey (Luka V Remix)-2290
99825.mp3'
[debug] ffmpeg command line: ffmpeg -y -i 'file:Oliver Heldens - Shades Of Grey
(Luka V Remix)-229099825.mp3' -c copy -metadata comment= -metadata description=
-metadata 'artist=Luka V' -metadata 'title=Oliver Heldens - Shades Of Grey (Luka
 V Remix)' -metadata date=20151019 -metadata purl=http://soundcloud.com/luka_v/o
liver-heldens-shades-of-grey-luka-v-remix-1 'file:Oliver Heldens - Shades Of Gre
y (Luka V Remix)-229099825.temp.mp3'
WARNING: Skipping embedding the thumbnail because the file is missing.


Yes, I can see the artwork with my browser.

I'm using the Windows .exe, is there another version that doesn't have this problem? I have Python 2.7.5 installed on my system.

**Comment by DiamondKing099** [comment]
Tried the script with Python 2.7.5. Same results.

**Comment by dstftw** [comment]
You need python 2.7.9 or greater.

**Comment by DiamondKing099** [comment]
I'll give it a try, thanks!

**Comment by DiamondKing099** [comment]
Works like a charm! Thanks for this awesome script!
