### ISSUE TITLE
Unrecognized option 'c'

### ISSUE THREAD

**Issue by adrianTNT** [rg3/youtube-dl#7251]
On CentOS 6.x with FFmpeg version 0.6.5 I tried this command but failed to get an Mp3:

    youtube-dl --audio-format mp3  https://www.youtube.com/watch?v=KMU0tzLwhbE

This is the output:

    [youtube] KMU0tzLwhbE: Downloading webpage
    [youtube] KMU0tzLwhbE: Downloading video info webpage
    [youtube] KMU0tzLwhbE: Extracting video information
    [youtube] KMU0tzLwhbE: Downloading DASH manifest
    [youtube] KMU0tzLwhbE: Downloading DASH manifest
    [download] Destination: Developers-KMU0tzLwhbE.f133.mp4
    [download] 100% of 5.26MiB in 00:00
    [download] Destination: Developers-KMU0tzLwhbE.f141.m4a
    [download] 100% of 5.53MiB in 00:00
    [ffmpeg] Merging formats into "Developers-KMU0tzLwhbE.mp4"
    WARNING: Your copy of ffmpeg is outdated, update ffmpeg to version 1.0 or newer if you encounter any errors.
    ERROR: Unrecognized option 'c'

It did create two files, but NOT an mp3:

    Developers-KMU0tzLwhbE.f133.mp4
    Developers-KMU0tzLwhbE.f141.m4a

Any way to fix this ? I can't seem to find a way to install avconv or update ffmpeg.

**Comment by dstftw** [comment]
Update ffmpeg.
