### ISSUE TITLE
Having problem in downloading playlist

### ISSUE THREAD

**Issue by saurabhdhankar** [rg3/youtube-dl#7253]
![screenshot from 2015-10-21 12 10 26](https://cloud.githubusercontent.com/assets/15226539/10629576/8c8c35a6-77ed-11e5-99d1-21d82b83d030.png)

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating. Also read how to [type URL correctly](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).
