### ISSUE TITLE
Unable to download BBC Four videos

### ISSUE THREAD

**Issue by vog** [rg3/youtube-dl#7257]
Unable to download BBC Four's documentation "BBC Four's Calculating Ada: The Countess of Computing" about Ada Lovelace.

Tried with latest master version of yt-dl (7308b8cb3df5a2df0a86e8050c83b951004a0aca) on latest Debian/Sid.

<pre>
$ youtube-dl --verbose 'http://www.bbc.co.uk/programmes/articles/3jNQLTMrPlYGTBn0WV6M2MS/not-your-typical-role-model-ada-lovelace-the-19th-century-programmer'

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.bbc.co.uk/programmes/articles/3jNQLTMrPlYGTBn0WV6M2MS/not-your-typical-role-model-ada-lovelace-the-19th-century-programmer']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.18
[debug] Python version 2.7.10+ - Linux-4.2.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 2.8-1, avprobe 2.8-1, ffmpeg 2.8-1, ffprobe 2.8-1
[debug] Proxy map: {}
[bbc.co.uk] articles: Downloading video page
[bbc.co.uk] articles: Downloading playlist JSON
[bbc.co.uk] articles: Downloading legacy playlist XML
ERROR: Unable to download XML: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/.../youtube_dl/extractor/common.py", line 330, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/.../youtube_dl/YoutubeDL.py", line 1873, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
</pre>

**Comment by yan12125** [comment]
Videos in this article will be supported in the next version. Thanks for the report.
