### ISSUE TITLE
Unable to download from soundcloud

### ISSUE THREAD

**Issue by Xonshiz** [rg3/youtube-dl#7260]
Seems like soundcloud download failed. O/P with verbose

--> youtube-dl "https://soundcloud.com/skrillex/skrillex-jauz-squad-out-feat-fatman-scoop" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://soundcloud.com/skrillex/skrillex-jauz-squad-out-feat-fatman-scoop', u'--verbose']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-62728-g6956b04, rtmpdump 2.5
[debug] Proxy map: {}
[soundcloud] skrillex/skrillex-jauz-squad-out-feat-fatman-scoop: Resolving id
[soundcloud] skrillex/skrillex-jauz-squad-out-feat-fatman-scoop: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 326, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1865, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
