### ISSUE TITLE
Unable to Download Video from Facebook

### ISSUE THREAD

**Issue by masbog** [rg3/youtube-dl#7265]
masbog$ youtube-dl https://www.facebook.com/willyfoo/videos/vb.96738939244/10152791075154245 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.facebook.com/willyfoo/videos/vb.96738939244/10152791075154245', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.18
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 10152791075154245: Downloading webpage
ERROR: An extractor error has occured. (caused by KeyError(0,)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 145, in _real_extract
    video_data = params['video_data'][0]
KeyError: 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 297, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(0,)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Facebook is fixed but not included in the latest release yet. Please wait patiently for the next version.

**Comment by masbog** [comment]
@yan12125 okey... thank you very much... 👍
