### ISSUE TITLE
Downloading a list of videos stops when one of the videos has been removed by the user

### ISSUE THREAD

**Issue by eksperimental** [rg3/youtube-dl#7266]
I think if one video has been removed, it should continue processing the list and not die.
im  getting
> "ERROR: <<ID_HERE>>: YouTube said: This video has been removed by the user.

**Comment by dstftw** [comment]
Use `--ignore-errors`.

**Comment by eksperimental** [comment]
thanks.
Shouldn't  a message explaining this be given when killing the app?
