### ISSUE TITLE
got error when trying to download facebook video

### ISSUE THREAD

**Issue by SpEcHiDe** [rg3/youtube-dl#7268]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.facebook.com/AjaySathyanSinger/videos/393289610861209/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.18
[debug] Python version 2.7.9 - Linux-4.0.0-os--name--
[debug] exe versions: ffmpeg N-75185-gf58e011, ffprobe N-75185-gf58e011, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 393289610861209: Downloading webpage
ERROR: An extractor error has occured. (caused by KeyError(0,)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 145, in _real_extract
    video_data = params['video_data'][0]
KeyError: 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 297, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(0,)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl.
