### ISSUE TITLE
An extractor error has occured. (caused by KeyError(0,));

### ISSUE THREAD

**Issue by gokhanege** [rg3/youtube-dl#7272]
[root@www html]# youtube-dl https://www.facebook.com/video.php?v=1053926811319469
[facebook] 1053926811319469: Downloading webpage
ERROR: An extractor error has occured. (caused by KeyError(0,)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by gokhanege** [comment]
[root@www html]# rpm -qa | grep youtube-dl
youtube-dl-2015.09.09-1.el6.noarch

**Comment by yan12125** [comment]
It's a known issue and already fixed. Please wait for the next version of youtube-dl.
