### ISSUE TITLE
YouTube: 0 videos grabbed for age-restricted user/channel

### ISSUE THREAD

**Issue by ivan** [rg3/youtube-dl#7277]
Whether or not you log in, youtube-dl sees 0 videos for this age-restricted user/channel:

```
# PYTHONPATH=. python3 -m youtube_dl "https://www.youtube.com/user/DeusExOfficial/videos"
[youtube:user] DeusExOfficial: Downloading channel page
[youtube:user] DeusExOfficial: Downloading page #1
[download] Downloading playlist: DeusExOfficial
[youtube:user] playlist DeusExOfficial: Downloading 0 videos

# PYTHONPATH=. python3 -m youtube_dl "https://www.youtube.com/channel/UCs0ifCMCm1icqRbqhUINa0w"
[youtube:channel] UCs0ifCMCm1icqRbqhUINa0w: Downloading channel page
[youtube:channel] UCs0ifCMCm1icqRbqhUINa0w: Downloading page #1
[download] Downloading playlist: UCs0ifCMCm1icqRbqhUINa0w
[youtube:channel] playlist UCs0ifCMCm1icqRbqhUINa0w: Downloading 0 videos
```

As a fix, https://www.youtube.com/channel/UCs0ifCMCm1icqRbqhUINa0w could be converted directly to https://www.youtube.com/playlist?list=UUs0ifCMCm1icqRbqhUINa0w, which is not age-restricted.

https://www.youtube.com/user/DeusExOfficial/videos redirects to https://www.youtube.com/verify_age?next_url=%2Fuser%2FDeusExOfficial%2Fvideos&action_display=1, which contains a

```
data-ytid="UCs0ifCMCm1icqRbqhUINa0w"
```

that could be converted to https://www.youtube.com/playlist?list=UUs0ifCMCm1icqRbqhUINa0w

**Comment by jaimeMF** [comment]
Thanks for the report and the proposed solution, it will work in the next version.
