### ISSUE TITLE
Support for 'YouTube auto generated playlist'

### ISSUE THREAD

**Issue by mainalikishan** [rg3/youtube-dl#7279]
Is there a way to download 'YouTube auto generated playlist'?
Example: https://www.youtube.com/watch?v=ASj81daun5Q&list=RDASj81daun5Q

**Comment by jaimeMF** [comment]
You just need to run `youtube-dl 'https://www.youtube.com/watch?v=ASj81daun5Q&list=RDASj81daun5Q'`.
