### ISSUE TITLE
mitele.es 

### ISSUE THREAD

**Issue by Zezaru** [rg3/youtube-dl#7280]
hi

youtube-dl http://www.mitele.es/series-online/la-que-se-avecina/temporada-8/capitulo-104/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.mitele.es/series-online/la-que-se-avecina/temporada-8/capitulo-104/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.10.23
[debug] Python version 3.4.3 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[MiTele] capitulo-104: Downloading webpage
[MiTele] capitulo-104: Downloading config JSON
[MiTele] capitulo-104: Downloading mmc JSON
[MiTele] capitulo-104: Downloading akamai JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HT
TPError()); please report this issue on https://yt-dl.org/bug . Make sure you ar
e using the latest version; see  https://yt-dl.org/update  on how to update. Be
sure to call youtube-dl with the --verbose flag and include its complete output.

  File "c:\python34\lib\site-packages\youtube_dl\extractor\common.py", line 330,
 in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1873, in ur
lopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python34\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "c:\python34\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python34\lib\urllib\request.py", line 507, in error
    return self._call_chain(*args)
  File "c:\python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "c:\python34\lib\urllib\request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by jaimeMF** [comment]
I think the error should be fixed in the next version (in my case it was an sporadic error, so I can't be 100% sure), thanks for the report.
