### ISSUE TITLE
have better names for infoq.com downloads

### ISSUE THREAD

**Issue by Siddhant** [rg3/youtube-dl#7281]
```
$ youtube-dl --proxy '' http://www.infoq.com/presentations/Thinking-Parallel-Programming
[InfoQ] Thinking-Parallel-Programming: Downloading webpage
[download] Destination: How to Think about Parallel Programming - Not!-10-oct-howtothink.flv
[download] 100% of 133.80MiB in 02:52
```
File name is "How to Think about Parallel Programming - Not!-10-oct-howtothink.flv"
Problem: repeated phrase 'hownottothink'
Preferred name: "How to Think about Parallel Programming - Not!.flv" or "How to Think about Parallel Programming - Not!-10-Oct.flv" or something which is at least better than current name.

Another request:
There are slides available with the presentation, and these can be downloaded (.pdf).
Though asking for youtube-dl to download the slides too might be too much to ask for,
can youtube-dl detect that slides are available and give a friendly note to the user, saying 'Hey, remember, if you wanna watch this offline, then you would like to download the slides too."

**Comment by phihag** [comment]
youtube-dl filenames follow the `-o` option. I believe your preferred file format can be achieved using `-o "%(title)s"` (put that and the proxy option in your [configuration file](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration)).

As mentioned in our [bug reporting instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#does-the-issue-involve-one-problem-and-one-problem-only), we can only handle one request per issue. Feel free to [open a new issue](https://github.com/rg3/youtube-dl/issues/new) if you have further questions.
