### ISSUE TITLE
Download each playlist into its own folder

### ISSUE THREAD

**Issue by darksimon** [rg3/youtube-dl#7283]
Hello, is it possible to download each playlist into its own folder ? ex. I have batch file with several playlists and I want to download each playlist into its own folder with the name of the playlist which would youtube-dl create automatically before start of download. Is it somehow possible ? Otherwise would it be possible to add this function to the next version of YouTube-dl ? Thank you very much for response.

**Comment by dstftw** [comment]
Use [output template](https://github.com/rg3/youtube-dl#output-template).
