### ISSUE TITLE
Can't download Twitter GIFs.

### ISSUE THREAD

**Issue by luigifreitas** [rg3/youtube-dl#7287]
When I try to download a normal Twitter video works fine. But if I try to download a Twitter video of a GIF (which YouTube converts automatically) I get this error: "ERROR: Unable to extract twitter card url;". Example: 

This should work: http://twitter.com/ErnietheFT/status/657265991135698944/video/1
This should not: http://twitter.com/giphz/status/657991469417025536/photo/1

**Comment by gaming-hacker** [comment]
OS X 10.11, latest youtube-dl, this works for me 

This should work: http://twitter.com/ErnietheFT/status/657265991135698944/video/1


Ernie_-_Serious_ear_flappage_going_on.mp4
[download] 100% of 1.42MiB in 00:05

**Comment by yan12125** [comment]
Twitter GIFs will be supported in the next version (cf5881fc4defe3902367fc02b8eb39d912572d5a, sorry I mix two irrelevant changes in a single commit). Note that the downloaded file is MP4 even if twitter says it's GIF.
