### ISSUE TITLE
nowtv download fails with error "rtmpdump exited with code 1"

### ISSUE THREAD

**Issue by grexe** [rg3/youtube-dl#7288]
$ youtube-dl -tv "http://www.nowtv.at/vox/auf-und-davon/kindheitstraum-argentinien/player"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-tv', 'http://www.nowtv.at/vox/auf-und-davon/kindheitstraum-argentinien/player']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.28
[debug] Python version 3.4.2 - Linux-4.1.4-1-CHAKRA-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 2.5.6, ffprobe 2.5.6, rtmpdump 2.4
[debug] Proxy map: {}
[NowTV] auf-und-davon/kindheitstraum-argentinien: Downloading JSON metadata
[debug] Invoking downloader on 'rtmpe://fms.rtl.de'
[download] Destination: Kindheitstraum - Argentinien-228571.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmpe://fms.rtl.de -o 'Kindheitstraum - Argentinien-228571.flv.part' --swfVfy http://rtl-now.rtl.de/includes/nc_player.swf --pageUrl http://www.nowtv.at/vox/auf-und-davon/kindheitstraum-argentinien/player --app voxnow --playpath mp4:173/V_871703_MUDC_22-22000733210_128663_h264-hq_49bcd0b3ea77717b6dd03f24882.f4v --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : fms.rtl.de
[rtmpdump] WARNING: No application or playpath in URL!
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] ERROR: RTMP_HashSWF: swfurl http://rtl-now.rtl.de/includes/nc_player.swf not found
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : fms.rtl.de
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:173/V_871703_MUDC_22-22000733210_128663_h264-hq_49bcd0b3ea77717b6dd03f24882.f4v
[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.rtl.de:1935/voxnow
[rtmpdump] DEBUG: swfUrl   : http://rtl-now.rtl.de/includes/nc_player.swf
[rtmpdump] DEBUG: pageUrl  : http://www.nowtv.at/vox/auf-und-davon/kindheitstraum-argentinien/player
[rtmpdump] DEBUG: app      : voxnow
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : fms.rtl.de
[rtmpdump] WARNING: No application or playpath in URL!
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] ERROR: RTMP_HashSWF: swfurl http://rtl-now.rtl.de/includes/nc_player.swf not found
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : fms.rtl.de
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:173/V_871703_MUDC_22-22000733210_128663_h264-hq_49bcd0b3ea77717b6dd03f24882.f4v
[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.rtl.de:1935/voxnow
[rtmpdump] DEBUG: swfUrl   : http://rtl-now.rtl.de/includes/nc_player.swf
[rtmpdump] DEBUG: pageUrl  : http://www.nowtv.at/vox/auf-und-davon/kindheitstraum-argentinien/player
[rtmpdump] DEBUG: app      : voxnow
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.09.28', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1658, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 671, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 717, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1328, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1590, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1532, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 535, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 497, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by grexe** [comment]
oops sorry, normally the Chakra community repo version was very fresh, so I didn't check...

**Comment by c1ko** [comment]
Looks still broken for me, same error. Fedora 23, youtube-dl 2015.11.19, rtmpdump-2.4-3.20131205.gitdc76f0a.fc22.x86_64

**Comment by yan12125** [comment]
rtmpdump 2.4 20140918 with commit a1900c3 works work me. You may want to upgrade to the latest rtmpdump. If the problem is still, open a new issue with [full verbose log](https://github.com/rg3/youtube-dl#bugs).

**Comment by grexe** [comment]
Thanks @yan12125 - even the older version 2.4.20140706-1 worked for me now! Just had to install the rtmpdump package separately which is picked up by youtube-dl now, just downloading the video, vlc could play the start already.
