### ISSUE TITLE
Soundcloud HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by paulnice** [rg3/youtube-dl#7290]
$bin/youtube-dl https://soundcloud.com/racheldarcy/dance-for-you 
[soundcloud] racheldarcy/dance-for-you: Resolving id
[soundcloud] racheldarcy/dance-for-you: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
