### ISSUE TITLE
audio/video conversion settings

### ISSUE THREAD

**Issue by gaming-hacker** [rg3/youtube-dl#7291]
for switch

--format bestaudio

how are  you determining the best audio? size? bitrate? sample rate?

also when youtube-dl selects ogg and you want format mp3, what settings is it using?

similar with video

you want mp4 but best video is webm, what conversion settings are used for ffmpeg?

**Comment by dban0001** [comment]
Please read the docs: https://github.com/rg3/youtube-dl#format-selection

**Comment by gaming-hacker** [comment]
i did already but it is insufficient, i'm looking for the exact settings you use for ffmpeg, like bitrate, sample frequency, quality settings.  what algorithm is used?  say for example, an old crappy avi file to an mp4 file?  are you de-interlacing?  witih bob? drop? etc or converting 64-bit wav to aac?  or a crappy mp3 to flac?

**Comment by yan12125** [comment]
There are just some simple heuristics. Detailed codes can be found in [```InfoExtractor._sort_formats()```](https://github.com/rg3/youtube-dl/blob/c137cc0d33fee8369b857c8f12a9116379248127/youtube_dl/extractor/common.py#L764-L825). I'm closing this issue as it's just for discussion but not an actual issue.

**Comment by gaming-hacker** [comment]
it's more of a documentation issue.  i've download some video files and used the internal youtube-dl flags for re-encoding and the audio was unsatisfactory so I'm going to bypass the internal flags and pipe youtube-dl output into ffmpeg with known settings.

**Comment by phihag** [comment]
@gaming-hacker Why don't you describe how to improve settings in your use cases? I'd very much prefer youtube-dl using satisfactory flags in the first place.
