### ISSUE TITLE
Site support request: vidbull.com

### ISSUE THREAD

**Issue by dban0001** [rg3/youtube-dl#7294]
It shows as playlist with gives me two mp4 files which should be a single file and they just have the html in it. Just an idea, don't know if it's good: maybe add the functionality that when the content-type header is text/html or text/plain return an error or something?

```
$ youtube-dl "http://vidbull.com/kotklqfnaa37.html" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://vidbull.com/kotklqfnaa37.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.6 - Linux-3.16.0-38-generic-x86_64-with-LinuxMint-17.2-rafaela
[debug] exe versions: ffmpeg N-75403-g3a8e447, ffprobe N-75403-g3a8e447
[debug] Proxy map: {}
[generic] kotklqfnaa37: Requesting header
WARNING: Falling back on generic information extractor.
[generic] kotklqfnaa37: Downloading webpage
[generic] kotklqfnaa37: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[debug] Invoking downloader on u'http://vidbull.com/vidembed-kotklqfnaa37.mp4'
[download] Destination: Watch Bobs Burgers S01E01 Human Flesh 720p Tunes DD5 264 CtrlHD  online - VidBull (1)-vidembed-kotklqfnaa37.mp4
[download] 100% of 22.54KiB in 00:00
[download] Downloading video 2 of 2
[debug] Invoking downloader on u'http://vidbull.com/vidembed-kotklqfnaa37.mp4'
[download] Destination: Watch Bobs Burgers S01E01 Human Flesh 720p Tunes DD5 264 CtrlHD  online - VidBull (2)-vidembed-kotklqfnaa37.mp4
[download] 100% of 22.54KiB in 00:00
```

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by dban0001** [comment]
I don't know, it was just an example url. They have the normal DMCA site & email address, like most other services (nowvideo etc). An url which works and I think it doesn't violate copyrights (but recognized as playlist, the two .mp4 files just have html in them): http://vidbull.com/me4gn6lxm01t.html

**Comment by PannenkoekenNL** [comment]
I would also like to request support for this website.

**Comment by dstftw** [comment]
http://vidbull.com is dead.
