### ISSUE TITLE
lynda cookie

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#7295]
hi i am using cookie command and its downloading only free vidoes from course here is my command
youtube-dl --cookies Desktop/cookies.txt http://www.lynda.com/3D-Animation-Architecture-tutorials/Alex-McDowell-World-Building-Narrative/362994-2.html

if its wrong then can you plz give me exact command 

thanks

**Comment by dstftw** [comment]
Read [this](https://github.com/rg3/youtube-dl#bugs) and [this](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).

**Comment by jaan143** [comment]
dstftw plz check your email

**Comment by jaan143** [comment]
check this error i got 

C:\Users\waqas\downloads> youtube-dl --cookies Desktop/cookies.txt --verbose http://www.lynda.com/C-tutorials/C-Smart
-Pointers/379655-2.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--cookies', 'Desktop/cookies.txt', '--verbose', 'http://www.lynda.com/C-tutorials/C-Smart-Pointers/379655-2.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.10.24
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] 379655: Downloading course JSON
WARNING: 6 videos are only available for members (or paid members) and will not be downloaded. Use --username and --password options to provide lynda.com account credentials.
[download] Downloading playlist: C++ Smart Pointers
[lynda:course] playlist C++ Smart Pointers: Collected 3 video ids (downloading 3 of them)
[download] Downloading video 1 of 3
[lynda] 419902: Downloading video JSON
[lynda] 419902: Checking 0-720 video format URL
[lynda] 419902: Checking 0-360 video format URL
[lynda] 419902: Checking 0-540 video format URL
[lynda] 419902: Checking 1-720 video format URL
[lynda] 419902: Checking 1-360 video format URL
[lynda] 419902: Checking 1-540 video format URL
[debug] Invoking downloader on 'http://files2.lynda.com/secure/courses/379655/VBR_MP4h264_main_HD720/379655_00_01_WL30_welcome.mp4?c3.ri=3773562105026827573&hashval=1445813664_1081fc915a11ade7328a1f684068ec89'
[download] Welcome-419902.mp4 has already been downloaded
[download] 100% of 22.24MiB
[download] Downloading video 2 of 3
[lynda] 419903: Downloading video JSON
[lynda] 419903: Checking 0-720 video format URL
[lynda] 419903: Checking 0-360 video format URL
[lynda] 419903: Checking 0-540 video format URL
[lynda] 419903: Checking 1-720 video format URL
[lynda] 419903: Checking 1-360 video format URL
[lynda] 419903: Checking 1-540 video format URL
[debug] Invoking downloader on 'http://files2.lynda.com/secure/courses/379655/VBR_MP4h264_main_HD720/379655_00_02_XR15_exfiles.mp4?c3.ri=3770184403592906667&hashval=1445813668_9f314b25be6ccc113026bfa4dd67cdad'
[download] Exercise files-419903.mp4 has already been downloaded
[download] 100% of 8.72MiB
[download] Downloading video 3 of 3
[lynda] 419905: Downloading video JSON
[lynda] 419905: Checking 0-720 video format URL
[lynda] 419905: Checking 0-360 video format URL
[lynda] 419905: Checking 0-540 video format URL
[lynda] 419905: Checking 1-720 video format URL
[lynda] 419905: Checking 1-360 video format URL
[lynda] 419905: Checking 1-540 video format URL
[debug] Invoking downloader on 'http://files2.lynda.com/secure/courses/379655/VBR_MP4h264_main_HD720/379655_01_01_XR15_whysmartpointers.mp4?c3.ri=3770184403592906732&hashval=1445813673_8f14b9e256d6d96f543f84d54f69a67f'
[download] Why smart pointers-419905.mp4 has already been downloaded
[download] 100% of 3.12MiB
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\youtube_dl\__init__.py", line 410, in main
    _real_main(argv)
  File "C:\Python34\lib\site-packages\youtube_dl\__init__.py", line 403, in _real_main
    retcode = 101
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 477, in __exit__
    self.cookiejar.save()
  File "C:\Python34\lib\http\cookiejar.py", line 2052, in save
    with open(filename, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Desktop/cookies.txt'
PS C:\Users\waqas\downloads>

**Comment by dstftw** [comment]
>No such file or directory: 'Desktop/cookies.txt'

**Comment by jaan143** [comment]
its in dekstop i make cookie via cookie exporter

**Comment by dstftw** [comment]
Specify **correct** path to cookies file `C:/Users/waqas/Desktop/cookies.txt`.
