### ISSUE TITLE
neteasemusic no longer works

### ISSUE THREAD

**Issue by theli-ua** [rg3/youtube-dl#7301]

**Comment by jaimeMF** [comment]
[You haven't posted all the required info](https://github.com/rg3/youtube-dl/blob/edeb3e7cb1ab2d82ff7c712a7cc1e338a9dcd8f8/README.md#bugs), once you post it we'll reopen the issue and try to help you.

**Comment by theli-ua** [comment]
I do believe description is self sufficient, current master will faill all of the tests in youtube_dl/extractor/neteasemusic.py

**Comment by theli-ua** [comment]
and btw the issue is just with hardcoded m1.music.126.net server you use, m2.music.126.net works just fine

**Comment by yan12125** [comment]
Confirmed.
