### ISSUE TITLE
removing non-ascii characters

### ISSUE THREAD

**Issue by daft117** [rg3/youtube-dl#7310]
is it me only or youtube-dl started to remove non-ascii characters in newer versions?

tested in ubuntu 14.04 with latest binary

by the way, i can suggest a parameter that fixes non-ascii characters via "unidecode" module from https://github.com/iki/unidecode

it basicly does:
Ş -> S 
kinda

**Comment by jaimeMF** [comment]
[As explained in the bug reporting instructions](https://github.com/rg3/youtube-dl/blob/edeb3e7cb1ab2d82ff7c712a7cc1e338a9dcd8f8/README.md#bugs): post the full output you get when you run `youtube-dl --verbose URL`.

**Comment by daft117** [comment]
http://pastebin.com/raw.php?i=z36bwSc6

**Comment by dstftw** [comment]
>[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
>ANSI_X3.4-1968

Correctly setup your locale.

**Comment by daft117** [comment]
i fixed it by adding "export LANG=en_US.utf8" to "~/.bashrc"
now works fine
