### ISSUE TITLE
Output Template ignored when using suggested format selection option

### ISSUE THREAD

**Issue by Zettt** [rg3/youtube-dl#7311]
I liked the idea suggested in ]format selection](https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection). Use `-f bestvideo[height<=?1080]+bestaudio/best` I modified this to `(mp4)[height<=?1080]+bestaudio/best`. I'm also using an output template: `%(uploader)s %(title)s.%(ext)s`.

1. This does work, but it leaves behind many audio files.
2. The output filenames have their format shorthand after them, e.g. `Einführung u. Grundlagen I.f141`

**Comment by jaimeMF** [comment]
[As explained in the bug reporting instructions](https://github.com/rg3/youtube-dl/blob/edeb3e7cb1ab2d82ff7c712a7cc1e338a9dcd8f8/README.md#bugs): post the full output you get when you run `youtube-dl --verbose URL OTHER_OPTIONS`.
