### ISSUE TITLE
'list' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by pratik98** [rg3/youtube-dl#7318]
I am using windows 7.
 here is a log ,

C:\Users\whatever>cd slidnerd_material_design

C:\Users\whatever\slidnerd_material_design>youtube-dl https://www.youtube.com/wa
tch?v=h57QpXp2TRg&list=PLonJJ3BVjZW6CtAMbJz1XD8ELUs1KXaTD
[youtube] h57QpXp2TRg: Downloading webpage
[youtube] h57QpXp2TRg: Downloading video info webpage
[youtube] h57QpXp2TRg: Extracting video information
[youtube] h57QpXp2TRg: Downloading DASH manifest
[youtube] h57QpXp2TRg: Downloading DASH manifest
[download] Destination: Android Material Design Tutorial 1 with Android Studio [
HD 1080p]-h57QpXp2TRg.mp4
[download] 100% of 56.99MiB in 01:29
'list' is not recognized as an internal or external command,
operable program or batch file.

only first video got downloaded.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by d3cline** [comment]
landed here, the above is a dead link. for me the solution was to place the entire url in quotes ""
