### ISSUE TITLE
nowvideo site upgrade

### ISSUE THREAD

**Issue by AnimAlf** [rg3/youtube-dl#7330]
It isn't a bug, it's a site update. Nowvideo now presents a condition before offering the video. Push "Continue to video".

and now: "ERROR: Unable to extract filekey;" ;-)
*Now this has changed*. I now see the following error: **Unable to download webpage**

The full output:
```
youtube-dl --verbose http://www.nowvideo.sx/video/9604260d92ac8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.nowvideo.sx/video/9604260d92ac8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10+ - Linux-4.2.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 2.8.1-1, avprobe 2.8.1-1, ffmpeg 2.8.1-1, ffprobe 2.8.1-1, rtmpdump 2.4
[debug] Proxy map: {}
[nowvideo] 9604260d92ac8: Downloading video page
ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 631, in http_open
    req)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
```
greetings

**Comment by dstftw** [comment]
[How to report bugs](https://github.com/rg3/youtube-dl#bugs).

**Comment by AnimAlf** [comment]
¿it¡s a bug?

**Comment by jaimeMF** [comment]
If you read the [bug reporting instructions](https://github.com/rg3/youtube-dl/blob/edeb3e7cb1ab2d82ff7c712a7cc1e338a9dcd8f8/README.md#bugs) (it includes problems caused by some changes in a webstie), we can't help you unless you post the **full output** you get when running `youtube-dl --verbose URL`.

**Comment by AnimAlf** [comment]
I 'm going to learn it, thank you.
Is this one the correct place to post the bug?
Sorry for my bad English.

**Comment by jaimeMF** [comment]
> Is this one the correct place to post the bug?
yes, but post the full output you get when running youtube-dl --verbose URL.

**Comment by AnimAlf** [comment]
I've modified the first msg to show the error output O:-)

**Comment by yan12125** [comment]
Confirmed.

**Comment by dstftw** [comment]
Will be fixed in the next version.

**Comment by AnimAlf** [comment]
:-) thnks
Waiting for the update
Wonderful your project
