### ISSUE TITLE
Download of CBS The Late Show with Stephen Colbert failed

### ISSUE THREAD

**Issue by hstracker90** [rg3/youtube-dl#7331]
Hello! As of today, I suddenly cannot download The Late Show With Stephen Colbert anymore. When the show started, this was no problem, but today I discovered that CBS must have changed something. I can stream the show all right, but downloading stopped working. I'll be very grateful if you could fix this. Thanks a lot!

Here is the youtube-dl output:
C:\Users\hstracker90\Downloads>youtube-dl --verbose http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/YOYMbZT
n_8wufiSaRgP_MXSIArFfeN3G/the-late-show-10-30-2015-charlie-rose-stacy-schiff-ghost-the-zombies-/
[debug] System config: []
[debug] User config: [u'-o', u'C:/Users/hstracker90/Downloads/%(title)s.%(ext)s']
[debug] Command-line args: [u'--verbose', u'http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/YOYMbZTn_8
wufiSaRgP_MXSIArFfeN3G/the-late-show-10-30-2015-charlie-rose-stacy-schiff-ghost-the-zombies-/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-68482-g92a596f, ffprobe N-68482-g92a596f, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] the-late-show-10-30-2015-charlie-rose-stacy-schiff-ghost-the-zombies-: Downloading webpage
[ThePlatform] Pc3FZluGUKp_: Downloading SMIL data
[ThePlatform] Pc3FZluGUKp_: Downloading JSON metadata
[debug] Invoking downloader on 'rtmp://cp48590.edgefcs.net/ondemand/?auth=daEaHdVdVbsaLa2dUaRdfc4bna.cccKdWdo-bwnjp_-h0-
HcDPjVrd&aifp=v001&slist=video/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/
2015/10/26/552320067914/'
[download] Destination: C:\Users\hstracker90\Downloads\The Late Show - 10_30_2015 (Charlie Rose, Stacy Schiff, Ghost, The Zom
bies).flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmp://cp48590.edgefcs.net/ondemand/?auth=daEaHdVdVbsaLa2dUaRdfc4b
na.cccKdWdo-bwnjp_-h0-HcDPjVrd&aifp=v001&slist=video/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Pro
duction_Entertainment/2015/10/26/552320067914/' -o 'C:\Users\hstracker90\Downloads\The Late Show - 10_30_2015 (Charlie Rose,
Stacy Schiff, Ghost, The Zombies).flv.part' --playpath mp4:video/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_r
obot/CBS_Production_Entertainment/2015/10/26/552320067914/CBS_COLBERT_0034_CONTENT_CIAN_STREAMCLIP_672807_1928.mp4 --res
ume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : cp48590.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=daEaHdVdVbsaLa2dUaRdfc4bna.cccKdWdo-bwnjp_-h0-HcDPjVrd&aifp=v001&slist
=video/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2015/10/26/552320067914/

[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : cp48590.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:video/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entert
ainment/2015/10/26/552320067914/CBS_COLBERT_0034_CONTENT_CIAN_STREAMCLIP_672807_1928.mp4
[rtmpdump] DEBUG: tcUrl    : rtmp://cp48590.edgefcs.net:1935/ondemand/?auth=daEaHdVdVbsaLa2dUaRdfc4bna.cccKdWdo-bwnjp_-h
0-HcDPjVrd&aifp=v001&slist=video/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainmen
t/2015/10/26/552320067914/
[rtmpdump] DEBUG: app      : ondemand/?auth=daEaHdVdVbsaLa2dUaRdfc4bna.cccKdWdo-bwnjp_-h0-HcDPjVrd&aifp=v001&slist=video
/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2015/10/26/552320067914/
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : cp48590.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=daEaHdVdVbsaLa2dUaRdfc4bna.cccKdWdo-bwnjp_-h0-HcDPjVrd&aifp=v001&slist
=video/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2015/10/26/552320067914/

[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : cp48590.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:video/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entert
ainment/2015/10/26/552320067914/CBS_COLBERT_0034_CONTENT_CIAN_STREAMCLIP_672807_1928.mp4
[rtmpdump] DEBUG: tcUrl    : rtmp://cp48590.edgefcs.net:1935/ondemand/?auth=daEaHdVdVbsaLa2dUaRdfc4bna.cccKdWdo-bwnjp_-h
0-HcDPjVrd&aifp=v001&slist=video/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainmen
t/2015/10/26/552320067914/
[rtmpdump] DEBUG: app      : ondemand/?auth=daEaHdVdVbsaLa2dUaRdfc4bna.cccKdWdo-bwnjp_-h0-HcDPjVrd&aifp=v001&slist=video
/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2015/10/26/552320067914/
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 410, in main
  File "youtube_dl\__init__.pyo", line 400, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1666, in download
  File "youtube_dl\YoutubeDL.pyo", line 672, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 743, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 718, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1336, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1598, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1540, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\rtmp.pyo", line 202, in real_download
  File "youtube_dl\downloader\common.pyo", line 155, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 536, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 498, in trouble

C:\Users\hstracker90\Downloads>

**Comment by dstftw** [comment]
Works fine for me. Remove the old file and download again.

**Comment by aerth** [comment]
I get an error like this when  trying to reproduce this issue: 

UnsupportedError: Unsupported URL: http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/YOYMbZT/


```
s:~$ youtube-dl --verbose http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/YOYMbZT
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/YOYMbZT']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.3 - Linux-2.6.32-042stab102.9-x86_64-with-debian-7.9
[debug] exe versions: avconv 0.8.17-6, avprobe 0.8.17-6, ffmpeg 0.8.17-6, ffprobe 0.8.17-6
[debug] Proxy map: {}
[generic] YOYMbZT: Requesting header
[redirect] Following redirect to http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/YOYMbZT/
[generic] YOYMbZT: Requesting header
WARNING: Falling back on generic information extractor.
[generic] YOYMbZT: Downloading webpage
[generic] YOYMbZT: Extracting information
ERROR: Unsupported URL: http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/YOYMbZT/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1240, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1667, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 164, column 86
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1838, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/YOYMbZT/

```

**Comment by hstracker90** [comment]
@dstfw Oops, thank you for encouraging a retry. Actually it does work now and I didn't download a new version of youtube-dl first.
So the website does seem to produce some problems but only sometimes?
Anyway, thank you for your help. This case can be closed.
