### ISSUE TITLE
[QUESTION] Try to dl 4Kwebm+opus in webm container

### ISSUE THREAD

**Issue by freechelmi** [rg3/youtube-dl#7333]
Hi I can't find how to get a webm muxed of vp9+ opus 

I tried youtube-dl -f webm+webm --merge-output-format webm

Which obviously failed ....

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by freechelmi** [comment]
Sorry it works perfectly with default ! Thanks for this great tool !

youtube-dl --prefer-free-formats https://www.youtube.com/watch?v=UceRgEyfSsc
[youtube] UceRgEyfSsc: Downloading webpage
[youtube] UceRgEyfSsc: Downloading video info webpage
[youtube] UceRgEyfSsc: Extracting video information
[youtube] UceRgEyfSsc: Downloading DASH manifest
[youtube] UceRgEyfSsc: Downloading DASH manifest
[download] Destination: The Curvature of Earth 4K 60FPS-UceRgEyfSsc.f315.webm
[download] 100% of 637.85MiB in 06:58
[download] Destination: The Curvature of Earth 4K 60FPS-UceRgEyfSsc.f251.webm
[download] 100% of 2.96MiB in 00:02
[ffmpeg] Merging formats into "The Curvature of Earth 4K 60FPS-UceRgEyfSsc.webm"
Deleting original file The Curvature of Earth 4K 60FPS-UceRgEyfSsc.f315.webm (pass -k to keep)
Deleting original file The Curvature of Earth 4K 60FPS-UceRgEyfSsc.f251.webm (pass -k to keep)

**Comment by dstftw** [comment]
Use `-f bestvideo[ext=webm]+bestaudio[ext=webm]/best[ext=webm]` if you don't want anything apart from webm ever to be downloaded.
