### ISSUE TITLE
c-span.org: Clip url downloads entire show

### ISSUE THREAD

**Issue by lamberta** [rg3/youtube-dl#7335]
For example, I just wanted the 3:17 video clip at http://www.c-span.org/video/?c4557667/internet-privacy, but entering that url downloads the entire show file (46:35, 210mb). So it worked, I guess, but an unexpected result.

~~~
~$ youtube-dl http://www.c-span.org/video/?c4557667/internet-privacy
[CSpan] c4557667: Downloading webpage
[CSpan] 293738: Downloading JSON metadata
[CSpan] 293738: Downloading XML
[download] Destination: Federal Investigations and Email Privacy-293738.mp4
[download] 100% of 209.50MiB in 01:50
~~~

**Comment by remitamine** [comment]
Will be fixed in the next version.

**Comment by lamberta** [comment]
Awesome, thanks!
