### ISSUE TITLE
[8tracks] extraction remain stuck forever

### ISSUE THREAD

**Issue by bubbleguuum** [rg3/youtube-dl#7349]
./youtube-dl http://8tracks.com/jayzdubz/breaking-barriers -J --flat-playlist --no-check-certificate --socket-timeout 30 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://8tracks.com/jayzdubz/breaking-barriers', u'-J', u'--flat-playlist', u'--no-check-certificate', u'--socket-timeout', u'30', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.3 - Linux-3.2.0-70-generic-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.10.12-7, avprobe 0.10.12-7, ffmpeg 0.10.12-7, ffprobe 0.10.12-7
[debug] Proxy map: {}
// at this point the process remains stuck forever. The argument timeout is not even taken into account

**Comment by yan12125** [comment]
It's the expected behavior. Without ```-J``` you'll see something like this:
```
$ youtube-dl http://8tracks.com/jayzdubz/breaking-barriers --flat-playlist --no-check-certificate --socket-timeout 30 --verbose   
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://8tracks.com/jayzdubz/breaking-barriers', '--flat-playlist', '--no-check-certificate', '--socket-timeout', '30', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.18
[debug] Git HEAD: f0a678e
[debug] Python version 3.5.0 - Linux-4.2.5-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1, rtmpdump 2.4
[debug] Proxy map: {}
[8tracks] breaking-barriers: Downloading webpage
[8tracks] breaking-barriers: Downloading song information 1/14
[8tracks] breaking-barriers: Downloading song information 2/14
[8tracks] breaking-barriers: Downloading song information 3/14
[8tracks] breaking-barriers: Downloading song information 4/14
[8tracks] breaking-barriers: Downloading song information 5/14
[8tracks] breaking-barriers: Waiting for 214.92857142857142 seconds
```
Because youtube-dl [waits for some time](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/eighttracks.py#L141) to prevent the problem mentioned in #2310.
