### ISSUE TITLE
Globo.com not working

### ISSUE THREAD

**Issue by bikabika** [rg3/youtube-dl#7351]
C:\youtube-dl>youtube-dl --verbose http://globoplay.globo.com/v/4581987/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://globoplay.globo.com/v/4581987/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-72362-g7ae805d, ffprobe N-72362-g7ae805d
[debug] Proxy map: {}
[Globo] v/4581987/: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org
/bug . Make sure you are using the latest version; type  youtube-dl -U  to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete o
utput.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\globo.pyo", line 357, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 584, in _search_regex
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks.

**Comment by dstftw** [comment]
Will be fixed in the next version.
