### ISSUE TITLE
youtube upgrading error

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#7358]
previous version not working sins today morning so i am trying to upgrade with your new release but i got error while upgrading so plz help me 
here is error msg 
 PS C:\Users\waqashanif> pip install --upgrade youtube-dl
Downloading/unpacking youtube-dl from https://pypi.python.org/packages/2.7/y/youtube_dl/youtube_dl-2015.11.02-py2.py3-n
ne-any.whl#md5=e55b859efe4e7f5cf7e5097de6f46b24
Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2015.10.18
    Uninstalling youtube-dl:
Cleaning up...
Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\shutil.py", line 522, in move
    os.rename(src, real_dst)
PermissionError: [WinError 5] Access is denied: 'c:\\python34\\etc\\bash_completion.d\\youtube-dl.bash-completion' -> '
:\\Users\\WAQASH~1\\AppData\\Local\\Temp\\4\\pip-eqza2de2-uninstall\\python34\\etc\\bash_completion.d\\youtube-dl.bash-
ompletion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\Python34\lib\site-packages\pip\req.py", line 1431, in install
    requirement.uninstall(auto_confirm=True)
  File "C:\Python34\lib\site-packages\pip\req.py", line 598, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "C:\Python34\lib\site-packages\pip\req.py", line 1836, in remove
    renames(path, new_path)
  File "C:\Python34\lib\site-packages\pip\util.py", line 295, in renames
    shutil.move(old, new)
  File "C:\Python34\lib\shutil.py", line 535, in move
    os.unlink(src)
PermissionError: [WinError 5] Access is denied: 'c:\\python34\\etc\\bash_completion.d\\youtube-dl.bash-completion'

Storing debug log for failure in C:\Users\waqashanif\pip\pip.log
PS C:\Users\waqashanif>

**Comment by dstftw** [comment]
Your account does not have enough rights to write to aforementioned directory. Use account with higher access or ask you administrator to do so.

**Comment by jaan143** [comment]
ok i will tell to admin but main problem is this i got error while downloading lynda course it was working fine last night but not working sins morning so i thought i have old version youtube-dl then i update in my own laptop but in my laptop also getting same error here is error plz check Sir
PS C:\Users\waqas> cd downloads
PS C:\Users\waqas\downloads> youtube-dl --verbose http://www.lynda.com/SQL-Server-tutorials/Database-Fundamentals-Admini
stration/385695-2.html --username *****@***.com --password *****
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.lynda.com/SQL-Server-tutorials/Database-Fundamentals-Administration/385695-2.html', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.02
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Logging in as *****@gmail.com
[lynda:course] 385695: Downloading course JSON
[download] Downloading playlist: Database Fundamentals: Administration
[lynda:course] playlist Database Fundamentals: Administration: Collected 31 video ids (downloading 31 of them)
[download] Downloading video 1 of 31
[lynda] Logging in as ****@gmail.com
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 289, in extract
    self.initialize()
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 283, in initialize
    self._real_initialize()
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\lynda.py", line 25, in _real_initialize
    self._login()
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\lynda.py", line 83, in _login
    raise ExtractorError('Unable to log in')
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

PS C:\Users\waqas\downloads>
