### ISSUE TITLE
Periscope: Unable to download JSON metadata

### ISSUE THREAD

**Issue by Crihub** [rg3/youtube-dl#7359]
I can't download any videos from periscope; here is the output.

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.periscope.tv/w/XXXXXXXXXXXX']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.6 - Linux-3.2.0-3-686-pae-i686-with-debian-wheezy-sid
[debug] exe versions: ffmpeg 1.2.4, ffprobe 1.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Periscope] XXXXXXXXXXXX: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/XXX/bin/youtube-dl/youtube_dl/extractor/common.py", line 329, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/XXX/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1873, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by Crihub** [comment]
> Post an example URL.

As I said, _any_ URL is failing :(

**Comment by dstftw** [comment]
As stated in [bug reporting guide](https://github.com/rg3/youtube-dl#bugs) you must provide concrete example URL. We are not going to find one ourselves.

**Comment by Crihub** [comment]
I apologize. Here you are a recent replay URL:
https://www.periscope.tv/w/1ZkKzPbMVggJv

Should the URL expire before you read this message, you can just go to http://onperiscope.com/ and click on any profile with the red "Off air" tag in the upper-right corner, and you'll get a recent replay URL to test.

**Comment by dstftw** [comment]
Videos with broascast_id will be supported in the next version. Note that token based URLs (e.g. https://www.periscope.tv/w/aQpiwDFkdkVPek5tRHBqWGV8MURYeHl3RE9ZQVBHTQ7G3W74JLXGS1ZLXePe8YZXl7q3TF5B9kTy1Bkp2w3-) still work as before.

**Comment by Crihub** [comment]
Thanks! Anyway I applied your patch and now I get a different error: "HTTP error 403 Forbidden", I tried both with both kind of URLs.

Here is the output, using the URL you provided in your last message (still works fine when viewed from the browser)

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.periscope.tv/w/aQpiwDFkdkVPek5tRHBqWGV8MURYeHl3RE9ZQVBHTQ7G3W74JLXGS1ZLXePe8YZXl7q3TF5B9kTy1Bkp2w3-']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.6 - Linux-3.2.0-3-686-pae-i686-with-debian-wheezy-sid
[debug] exe versions: ffmpeg 1.2.4, ffprobe 1.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Periscope] aQpiwDFkdkVPek5tRHBqWGV8MURYeHl3RE9ZQVBHTQ7G3W74JLXGS1ZLXePe8YZXl7q3TF5B9kTy1Bkp2w3-: Downloading JSON metadata
[Periscope] aQpiwDFkdkVPek5tRHBqWGV8MURYeHl3RE9ZQVBHTQ7G3W74JLXGS1ZLXePe8YZXl7q3TF5B9kTy1Bkp2w3-: Downloading JSON metadata
[debug] Invoking downloader on u'https://replay.periscope.tv/tvYcWo00kqcq4pFRJJkfGsOpuw9SEGU7XNC6TvXuttBG5n_bTjkqvTaa2POhT5HXRO8G5aiT_PjAEt58yTwDug==/playlist.m3u8'
[download] Destination: Stephanie Williams - Hey y'all! So for my birthday I want a party with live band! Any suggested places Hair..outfit..colors-1DXxywDOYAPGM.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: CloudFront-Signature=ej47Gr-d6m9ZNudZdUxy13eXF38xL9Ls-BbOWkHwYV9Mhg4OsavhLw1ghh1XRsIwvnP2ZgD65ozXqcie3g7i9UlHl9G4bTwimyl2adEuuKjfIEPHJSNwrkx~06dKgAcx0EvJmpN4Qe-NW5yz6SiKXJMHPpWoSezEsoWtcZnfx4fHc5so2GIPbVeVSnAGkA2HjDBNPuu4G-vKtFdDPGoUe4Ny8COH6Q8spd0EkW2iUAV1uehNPx8Tq-HUTbK7IiOrBkWK4TsDRSXbxAyLd9i7PVAZMzdqsGYFfTdjXCNeTPuuEL6u1BQSGZ17p~MP0knSMv3H~-9OYiWtS7vgGZigRg__; CloudFront-Key-Pair-Id=APKAIHCXHHQVRTVSFRWQ; CloudFront-Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9yZXBsYXkucGVyaXNjb3BlLnR2L3R2WWNXbzAwa3FjcTRwRlJKSmtmR3NPcHV3OVNFR1U3WE5DNlR2WHV0dEJHNW5fYlRqa3F2VGFhMlBPaFQ1SFhSTzhHNWFpVF9QakFFdDU4eVR3RHVnPT0qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDQ2ODA4NTU4fX19XX0_
' -i https://replay.periscope.tv/tvYcWo00kqcq4pFRJJkfGsOpuw9SEGU7XNC6TvXuttBG5n_bTjkqvTaa2POhT5HXRO8G5aiT_PjAEt58yTwDug==/playlist.m3u8 -f mp4 -c copy -bsf:a aac_adtstoasc 'file:Stephanie Williams - Hey y'"'"'all! So for my birthday I want a party with live band! Any suggested places Hair..outfit..colors-1DXxywDOYAPGM.mp4.part'
ffmpeg version 1.2.4 Copyright (c) 2000-2013 the FFmpeg developers
...
[https @ 0x8712dc0] HTTP error 403 Forbidden
[hls,applehttp @ 0x86efd20] Error when loading first segment 'https://replay.periscope.tv/tvYcWo00kqcq4pFRJJkfGsOpuw9SEGU7XNC6TvXuttBG5n_bTjkqvTaa2POhT5HXRO8G5aiT_PjAEt58yTwDug==/chunk_44.ts'
https://replay.periscope.tv/tvYcWo00kqcq4pFRJJkfGsOpuw9SEGU7XNC6TvXuttBG5n_bTjkqvTaa2POhT5HXRO8G5aiT_PjAEt58yTwDug==/playlist.m3u8: Input/output error

ERROR: ffmpeg exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/cri/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/home/cri/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/home/cri/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/cri/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1666, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/cri/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 672, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/cri/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 718, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/cri/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1336, in process_video_result
    self.process_info(new_info)
  File "/home/cri/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1598, in process_info
    success = dl(filename, info_dict)
  File "/home/cri/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1540, in dl
    return fd.download(name, info)
  File "/home/cri/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/home/cri/bin/youtube-dl/youtube_dl/downloader/hls.py", line 61, in real_download
    self.report_error('%s exited with code %d' % (ffpp.basename, retval))
  File "/home/cri/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/home/cri/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 536, in report_error
    self.trouble(error_message, tb)
  File "/home/cri/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 498, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by Crihub** [comment]
Ok, I confirm that current version (2015.11.13) works as expected, thanks!
