### ISSUE TITLE
Comedy Central The Daily Show won't load anymore

### ISSUE THREAD

**Issue by hstracker90** [rg3/youtube-dl#7360]
Hello! Yesterday it was no problem, today it's impossible: downloading The Daily Show with Trevor Noah. I can stream the video, but trying to download it I get the error that there is no video on the website. Please look into this.

C:\Windows>youtube-dl --verbose http://www.cc.com/full-episodes/wrv7ik/the-daily-show-with-trevor-noah-november-3--2015---gloria-steinem-season-21-ep-21018
[debug] System config: []
[debug] User config: [u'-o', u'C:/Users/robert/Downloads/%(title)s.%(ext)s']
[debug] Command-line args: [u'--verbose', u'http://www.cc.com/full-episodes/wrv7ik/the-daily-show-with-trevor-noah-november-3--2015---gloria-steinem-season-21-ep-21018']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-68482-g92a596f, ffprobe N-68482-g92a596f, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentral] the-daily-show-with-trevor-noah-november-3--2015---gloria-steinem-season-21-ep-21018: Downloading webpage
[ComedyCentral] 63e9c1a0-c66d-4ca6-ab7d-521926424a9a: Downloading info
[download] Downloading playlist: None
[ComedyCentral] playlist None: Collected 0 video ids (downloading 0 of them)

**Comment by jaimeMF** [comment]
I can't watch it in a browser (it's georestricted), but youtube-dl is currently working for me (it downloads 4 acts), can you check again?

**Comment by dstftw** [comment]
I can confirm it did not work 3 hours ago and does work now. This is probably due to some delay videos become available via http://comedycentral.com/feeds/mrss/. Current webplayer accesses video with different approach.

**Comment by hstracker90** [comment]
Am 04.11.2015 um 15:37 schrieb Sergey M.:
