### ISSUE TITLE
[lynda] Fix authentication

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#7361]
it was working very perfect till last night but today morning i got error while downloading lynda course so i thought i have old version youtube-dl then i update in my own laptop but in my laptop also getting same error here is error plz check Sir
PS C:\Users\waqas> cd downloads
PS C:\Users\waqas\downloads> youtube-dl --verbose http://www.lynda.com/SQL-Server-tutorials/Database-Fundamentals-Admini
stration/385695-2.html --username **@.com --password *****
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.lynda.com/SQL-Server-tutorials/Database-Fundamentals-Administration/385695-2.html', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.02
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Logging in as **@gmail.com
[lynda:course] 385695: Downloading course JSON
[download] Downloading playlist: Database Fundamentals: Administration
[lynda:course] playlist Database Fundamentals: Administration: Collected 31 video ids (downloading 31 of them)
[download] Downloading video 1 of 31
[lynda] Logging in as *@gmail.com
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 661, in extract_info
ie_result = ie.extract(url)
File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 289, in extract
self.initialize()
File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 283, in initialize
self._real_initialize()
File "C:\Python34\lib\site-packages\youtube_dl\extractor\lynda.py", line 25, in _real_initialize
self._login()
File "C:\Python34\lib\site-packages\youtube_dl\extractor\lynda.py", line 83, in _login
raise ExtractorError('Unable to log in')
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

PS C:\Users\waqas\downloads>

**Comment by OK77** [comment]
I have the same error while downloading Lynda courses. It  worked perfect till last night :-(

**Comment by rustybots** [comment]
Yes I can also confirm this was working up until last night.
If you click on the individual videos and use that URL it will download the video however it will not download the entire playlist using the main URL.
The output appears to hint it's trying to log in twice when download a playlist where as downloading individual videos only logs in once. Can't recall if that's normal.

PLAYLIST DOWNLOAD
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Logging in as xxx@hotmail.com
[lynda:course] Confirming log in and log out from another device
[lynda:course] 76336: Downloading course JSON
[download] Downloading playlist: Foundations of Photography: Lenses
[lynda:course] playlist Foundations of Photography: Lenses: Collected 37 video ids (downloading 37 of them)
[download] Downloading video 1 of 37
[lynda] Logging in as xxx@hotmail.com
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 289, in extract
  File "youtube_dl\extractor\common.pyo", line 283, in initialize
  File "youtube_dl\extractor\lynda.pyo", line 25, in _real_initialize
  File "youtube_dl\extractor\lynda.pyo", line 83, in _login
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

INDIVIDUAL DOWNLOAD
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[lynda] Logging in as xxx@hotmail.com
[lynda] 80257: Downloading video JSON
[lynda] 80257: Checking 1-540 video format URL
[lynda] 80257: Checking 1-720 video format URL
[lynda] 80257: Checking 1-360 video format URL
[lynda] 80257: Checking 0-540 video format URL
[lynda] 80257: Checking 0-720 video format URL
[lynda] 80257: Checking 0-360 video format URL
[debug] Invoking downloader on u'http://files3.lynda.com/secure/courses/76336/VBR_MP4h264_main_HD720/76336_01_02_MM30_whoFor.mp4?KXP1Oky4uHIU-BVK2oGfAnCbbORsk4LLdpziTnyNHpYmwzxkWfH1p8l7yDhOSXbtJISkkwCLaVlIoZRHz8V6dWPdL9R_yqAdKP2Y-_SVnNglBbO6JnzGjzvqHtQPQ8R4gyqyIDzlSP7fTQeA69lJ6EafXf5KFCg88fr1E9fYWNP41AKLM1dCH7cDPX8&c3.ri=3774407584135735739'
[download] Resuming download at byte 2582208
[download] Destination: NA\01 - Who is this course for.mp4
[download]  15.4% of 19.28MiB at 500.98KiB/s ETA 00:33

**Comment by jaan143** [comment]
but its hard to download one by one and other easy way also we can download one by one via idm but as i told you its hard thats why we need to back lynda in youtube-dl 
plz fix that error

**Comment by OK77** [comment]
youtube-dl worked fine with lynda a couple of days ago, but now I got the same error :-(

**Comment by brianhill2012** [comment]
Me too, it's not working any more. Used to getting this error a few times, but still downloaded the courses at last. Now it's completely not working and not even able to download one video from lynda.
