### ISSUE TITLE
Technical

### ISSUE THREAD

**Issue by malitech** [rg3/youtube-dl#7368]
Hello, I have been reviewing many youtube/video downloaders to finally write a blog post on a major site to let people know which youtube downloader is the best of all.

This is the video link I tested:
http://www.youtube.com/watch?v=UMkSPXHPG5E

I used many youtube downloaders to download a specific video for testing purposes. I wanted to download the best quality without re-encoding or converting, which is 1080p for this particular video. All youtube downloaders downloaded the audio file as "m4a" with 44Khz. But one of the 
youtube downloaders downloaded the audio file as "webm" audio which is 48Khz. So, I'm very confused and curious about this. I don't know what's going on. I want to find an answer to finalise my blog post.

1) Which audio source is the original? m4a or webm audio?

2) Why are most downloaders using m4a and not webm audio?

3) How to download the original video and audio in original format the uploader uploaded to youtube?

Please enlighten me. Thank you.

**Comment by dstftw** [comment]
1. Both original (in terms of media files served by YouTube). `-F` to list all original formats available.
2. Ask them why.
3. Probably you can't do that at all since YoutTube does not provide author-original formats but only reencoded to formats that YouTube serves.

**Comment by malitech** [comment]
Thanks. What does (best) mean? youtube-dl shows best for 720p. Can you tell me what that means?

They said webm doesn't play in players even if it is better in quality. Is that right?

Why are some 720p videos greater in size than muxed 1080p video and audio files?

**Comment by Hrxn** [comment]
> Why are some 720p videos greater in size than muxed 1080p video and audio files?

Theoretically possible, but very unlikely..
Do you have an example?

> They said webm doesn't play in players even if it is better in quality. Is that right?
All current players should handle .webm. VideoLAN definitely does.

**Comment by dstftw** [comment]
best is best quality file served as single file (most of the time it's worse that bestvideo+bestaudio). It's shows best because it meets aforementioned semantics.

>They said webm doesn't play in players even if it is better in quality. Is that right?

webm doesn't play in players? What a nonsense?

>Why are some 720p videos greater in size than muxed 1080p video and audio files?

Technically, filesize is not a measure of quality when comparing h264 and vp9.

**Comment by malitech** [comment]
This is an example:
https://www.youtube.com/watch?v=MqfesKdiXtc

Yes, I know. Webm plays fine, both audio and video webm files. Do you prefer m4a or webm audio?

If I want the best quality video and audio, what do you prefer? What command should I use?

**Comment by dstftw** [comment]
youtube-dl prefers formats according to metadata provided (bitrate, filesize and so on).
Read [FAQ on format selection](https://github.com/rg3/youtube-dl#format-selection).

**Comment by malitech** [comment]
Thanks. I read it. So, for the above example video, webm is the best.

I typed,
youtube-dl https://www.youtube.com/watch?v=MqfesKdiXtc
and it started downloading a 90.9mb file size which is not listed among the formats. Which file is this?

If I type,
youtube-dl -f https://www.youtube.com/watch?v=MqfesKdiXtc
it downloads the best webm files. After muxing, will it save it as webm? I don't want to re-encode.

**Comment by Hrxn** [comment]
> If I want the best quality video and audio, what do you prefer? What command should I use?

` -f bestvideo,bestaudio`

Two different streams, two different files.

No need to encode, just mux/merge.

**Comment by malitech** [comment]
What if the best video available is mp4 and audio is webm? How will it mux then?

**Comment by malitech** [comment]
Do you prefer ffmpeg or avconv?
