### ISSUE TITLE
Create Playlists as subfolder does not work (as expected)

### ISSUE THREAD

**Issue by elsakuh** [rg3/youtube-dl#7372]
As I read from here, the command line :
youtube-dl -ciw ytuser:XYZ -o d:\youtube\%(uploader)s\%(playlist)s\%(title)s.%(ext)s
should create a local hirarchy of \name of the channel \ name of the playlist(s) as a subfolder/s) \ title and extension video file.

What I get is d:\youtube\XYZ\ Uploads from XYZ\ all files flat out.

Is there something i am doing wrong with the command line or 
why does it not create playlists as subfolder and put the corresponding files in it

Edit:
If a URL from a playlist itself is used as an input, a corresponding directory with the playlist name  is created as expected

**Comment by jaimeMF** [comment]
> If a URL from a playlist itself is used as an input, a corresponding directory with the playlist name is created as expected

It can only know the playlist name if you use the playlist url. To clarify what's your exact problem, please post the full output of youtube-dl --verbose URL OTHER_OPTIONS` (as explained in [the bug reporting guide](https://github.com/rg3/youtube-dl/blob/edeb3e7cb1ab2d82ff7c712a7cc1e338a9dcd8f8/README.md#bugs).

**Comment by elsakuh** [comment]
Put the verbose Informations in two files one channel download and a specific plalistdownload
Sorry but what do you mean with "--verbose URL OTHER_OPTIONS"
are the provided informations with the text files what you expected?
Thanks

Tried to  attach txt files with the information but it is not allowed for me

Should I paste the whole text in here?

**Comment by elsakuh** [comment]
Channel downlaod fail subfolder:
D:\Youtube>D:\Youtube\youtube-dl\youtube-dl -ciw ytuser:TheSkillPedia -o d:\youtube\TheSkillPedia\%(playlist)s\%(title)s.%(ext)s --verbose
[debug] System config: []
[debug] User config: [u'--write-description', u'--write-info-json', u'--write-annotations', u'--write-thumbnail']
[debug] Command-line args: [u'-ciw', u'ytuser:TheSkillPedia', u'-o', u'd:\\youtube\\TheSkillPedia\\%(playlist)s\\%(title)s.%(ext)s', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:user] TheSkillPedia: Downloading channel page
[youtube:playlist] UUPlqr0Kb-DfJ9WvUIRYIK8Q: Downloading webpage
[download] Downloading playlist: Uploads from TheSkillPedia
[youtube:playlist] UUPlqr0Kb-DfJ9WvUIRYIK8Q: Downloading page #1
[youtube:playlist] playlist Uploads from TheSkillPedia: Downloading 97 videos
[download] Downloading video 1 of 97
[youtube] 2s78sCs3fbs: Downloading webpage
[youtube] 2s78sCs3fbs: Downloading video info webpage
[youtube] 2s78sCs3fbs: Extracting video information
[youtube] 2s78sCs3fbs: Searching for annotations.
[youtube] 2s78sCs3fbs: Downloading DASH manifest
[youtube] 2s78sCs3fbs: Downloading DASH manifest
[info] Video description is already present
[info] Video annotations are already present
[info] Video description metadata is already present
[youtube] 2s78sCs3fbs: Thumbnail is already present
[debug] Invoking downloader on u'https://r1---sn-4g57kn7e.googlevideo.com/videoplayback?expire=1446759132&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequ
iressl%2Csource%2Cupn%2Cexpire&upn=Fdb0E7uk3Bo&key=yt6&ipbits=0&fexp=9407117%2C9408710%2C9412837%2C9414764%2C9416126%2C9416985%2C9417683%2C9417707%2C9421585%2C9422596%2C9422618%2C9422868%2C9422945%2C9423663%2C9423789%2C9
423939&nh=IgpwcjAzLmZyYTE1KgkxMjcuMC4wLjE&initcwndbps=1018750&itag=18&ratebypass=yes&requiressl=yes&lmt=1435561690798283&signature=B0622293653724C932D6515E7E040A133F1D05EE.1837F349BF3C6906844072BC2D66D761AEBD8BEA&sver=3&
id=o-ACQDJyqpdSvwtCZYLhYxItZHkKil2a7rZ4P_qjqWRjfK&mm=31&mn=sn-4g57kn7e&mt=1446737365&dur=1893.633&pl=16&ip=84.164.13.164&mime=video%2Fmp4&ms=au&source=youtube&mv=m'
[download] d:\youtube\TheSkillPedia\Uploads from TheSkillPedia\SAP ASE 16 Learning Part 0 Introduction to SAP ASE   Sybase ASE.mp4 has already been downloaded

playlist download correct subfolder
D:\Youtube>D:\Youtube\youtube-dl\youtube-dl -ciw https://www.youtube.com/playlist?list=PLbPTI55vtiGvD3BRyV-V4vcuOliRMh88q -o d:\youtube\TheSkillPedia\%(playlist)s\%(title)s.%(ext)s --verbose
[debug] System config: []
[debug] User config: [u'--write-description', u'--write-info-json', u'--write-annotations', u'--write-thumbnail']
[debug] Command-line args: [u'-ciw', u'https://www.youtube.com/playlist?list=PLbPTI55vtiGvD3BRyV-V4vcuOliRMh88q', u'-o', u'd:\\youtube\\TheSkillPedia\\%(playlist)s\\%(title)s.%(ext)s', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] PLbPTI55vtiGvD3BRyV-V4vcuOliRMh88q: Downloading webpage
[download] Downloading playlist: Linux Tutorials for Beginners
[youtube:playlist] playlist Linux Tutorials for Beginners: Downloading 22 videos
[download] Downloading video 1 of 22
[youtube] p98FB90kufE: Downloading webpage
[youtube] p98FB90kufE: Downloading video info webpage
[youtube] p98FB90kufE: Extracting video information
[youtube] p98FB90kufE: Searching for annotations.
[youtube] p98FB90kufE: Downloading DASH manifest
[youtube] p98FB90kufE: Downloading DASH manifest
[info] Writing video description to: d:\youtube\TheSkillPedia\Linux Tutorials for Beginners\linux tutorial for beginners 1 History of Unix and Shell Basics.description
[info] Writing video annotations to: d:\youtube\TheSkillPedia\Linux Tutorials for Beginners\linux tutorial for beginners 1 History of Unix and Shell Basics.annotations.xml
[info] Writing video description metadata as JSON to: d:\youtube\TheSkillPedia\Linux Tutorials for Beginners\linux tutorial for beginners 1 History of Unix and Shell Basics.info.json
[youtube] p98FB90kufE: Downloading thumbnail ...
[youtube] p98FB90kufE: Writing thumbnail to: d:\youtube\TheSkillPedia\Linux Tutorials for Beginners\linux tutorial for beginners 1 History of Unix and Shell Basics.jpg
[debug] Invoking downloader on u'https://r6---sn-4g57kn6k.googlevideo.com/videoplayback?sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2C
upn%2Cexpire&requiressl=yes&fexp=9405825%2C9408710%2C9413271%2C9414764%2C9414977%2C9416126%2C9416179%2C9416556%2C9417298%2C9417683%2C9417707%2C9419837%2C9421942%2C9422596%2C9422618%2C9422902%2C9423420%2C9423510%2C9423518
%2C9423663%2C9423793&source=youtube&id=o-ABhcTIeqW5pzLmFAhuM6-1a-kvbidskzvr6pGfy7iJT1&pl=16&ms=au&mv=m&mt=1446737201&itag=22&mm=31&ip=84.164.13.164&ipbits=0&signature=1E312C17554DA27F66212D5FAD02D344B06FD7AD.C62C946AD919
83CC2B5CA9397E1E5AAEB730F977&initcwndbps=1012500&key=yt6&mime=video%2Fmp4&expire=1446758953&upn=H0iVRxYRMyI&dur=3262.287&lmt=1415906505327001&sver=3&mn=sn-4g57kn6k&nh=IgpwcjA0LmZyYTE1KgkxMjcuMC4wLjE&ratebypass=yes'
[download] Destination: d:\youtube\TheSkillPedia\Linux Tutorials for Beginners\linux tutorial for beginners 1 History of Unix and Shell Basics.mp4

**Comment by elsakuh** [comment]
for explanantion:
The goal here for me is to download once organized a channel and than, for example monthly,synchronize the channel with the same command, to stay in sync with the youtube web content of that channel

**Comment by dstftw** [comment]
As already mentioned by @jaimeMF it can only know the playlist when you pass playlist URL. So this behavior is expected.
Downloading all videos as playlists was already requested in #3817.

**Comment by elsakuh** [comment]
Ok Thanks,
So I unterstand that there is no downloading a channel incl Playlists organized by subfolders at the moment.
Would really appreaciate if this could be implemented, to, after initial download, keep the local channel folder/(playist-(subfolder) synchronized and up to date !
Thanks in advance

**Comment by elsakuh** [comment]
Workaround?
How can I do it inspite of that manually?
1. Is there a possibility to just extract a list of playlists of a channel and manually create a batch script that just run youtube-dl multiple times on each palylist?
2. Is there a possibility to the download all other videos exept that ones that are already downloaded and in a playlist to an unsorted folder?

**Comment by jaimeMF** [comment]
> 1. Is there a possibility to just extract a list of playlists of a channel and manually create a batch script that just run youtube-dl multiple times on each palylist?

As @dstftw has said, it's not implemented in youtube-dl (see #3817). You may want to write a script and/or implement it in youtube-dl.

> 2. Is there a possibility to the download all other videos exept that ones that are already downloaded and in a playlist to an unsorted folder?

Probably `--download-archive` is what you need.

**Comment by dstftw** [comment]
This feature will be supported in the next version for URLs of the following format: `http://www.youtube.com/user/user/playlists`.
