### ISSUE TITLE
Notice errors with TED videos

### ISSUE THREAD

**Issue by mayankrungta** [rg3/youtube-dl#7374]
I used to download TED talks without any issues earlier. Of late I am noticing this error with any talks that are on TED site and not on youtube. I wish to try youtube-dl installed running python3.x(using pip3) but I couldn't figure how to use that and not the one on python 2.x

Please advise.

youtube-dl https://www.ted.com/playlists/211/the_art_of_meaningful_conversa
[ted] the_art_of_meaningful_conversa: Downloading playlist webpage
[download] Downloading playlist: The art of meaningful conversation 
[ted] playlist The art of meaningful conversation : Collected 7 video ids (downloading 7 of them)
[download] Downloading video 1 of 7
[ted] julian_treasure_how_to_speak_so_that_people_want_to_listen: Downloading webpage
[ted] julian_treasure_how_to_speak_so_that_people_want_to_listen: Extracting information
[ted] julian_treasure_how_to_speak_so_that_people_want_to_listen: Downloading m3u8 information
[download] How to speak so that people want to listen-2034.mp4 has already been downloaded and merged
[download] Downloading video 2 of 7
[ted] marc_pachter_the_art_of_the_interview: Downloading webpage
[ted] marc_pachter_the_art_of_the_interview: Extracting information
[ted] marc_pachter_the_art_of_the_interview: Downloading m3u8 information
[download] Destination: The art of the interview-708.fhls-1882.mp4
avconv version 11.2-6:11.2-1, Copyright (c) 2000-2014 the Libav developers
  built on Jan 18 2015 05:12:33 with gcc 4.9.2 (Ubuntu 4.9.2-10ubuntu2)
[mpegts @ 0x16aec80] Continuity check failed for pid 0 expected 2 got 0
[mpegts @ 0x16aec80] Continuity check failed for pid 258 expected 6 got 0
[mpegts @ 0x16aec80] Continuity check failed for pid 257 expected 10 got 0
[mpegts @ 0x16aec80] Estimating duration from bitrate, this may be inaccurate
Input #0, hls,applehttp, from 'https://hls.ted.com/talks/708/video/1500k.m3u8':
  Duration: 00:20:40.19, start: 10.000000, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0.0: Video: h264 (High), yuv420p, 1280x720 [PAR 1:1 DAR 16:9], 24 fps, 90k tbn, 48 tbc
    Stream #0.1: Data: [21][0][0][0] / 0x0015
Output #0, mp4, to 'file:The art of the interview-708.fhls-1882.mp4.part':
  Metadata:
    encoder         : Lavf56.1.0
    Stream #0.0: Video: libx264, yuv420p, 1280x720 [PAR 1:1 DAR 16:9], q=2-31, 90k tbn, 90k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press ctrl-c to stop encoding
Non-monotonous DTS in output stream 0:0; previous: 1076250, current: 0; changing to 1076251. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076251, current: 3750; changing to 1076252. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076252, current: 7500; changing to 1076253. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076253, current: 11250; changing to 1076254. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076254, current: 15000; changing to 1076255. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076255, current: 18750; changing to 1076256. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076256, current: 22500; changing to 1076257. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076257, current: 26250; changing to 1076258. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076258, current: 30000; changing to 1076259. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076259, current: 33750; changing to 1076260. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076260, current: 37500; changing to 1076261. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076261, current: 41250; changing to 1076262. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076262, current: 45000; changing to 1076263. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076263, current: 48750; changing to 1076264. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076264, current: 52500; changing to 1076265. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076265, current: 56250; changing to 1076266. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076266, current: 60000; changing to 1076267. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076267, current: 63750; changing to 1076268. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076268, current: 67500; changing to 1076269. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076269, current: 71250; changing to 1076270. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076270, current: 75000; changing to 1076271. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076271, current: 78750; changing to 1076272. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076272, current: 82500; changing to 1076273. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076273, current: 86250; changing to 1076274. This may result in incorrect timestamps in the output file.

**Comment by jaimeMF** [comment]
I also get the same warning, but the final files play fine. If you have any problem, please explain your it in detail and post the full output you get with the `--verbose` flag (as explained in [the bug reporting guide](https://github.com/rg3/youtube-dl/blob/edeb3e7cb1ab2d82ff7c712a7cc1e338a9dcd8f8/README.md#bugs)).

> I wish to try youtube-dl installed running python3.x(using pip3) but I couldn't figure how to use that and not the one on python 2.x

It may be installed in a directory outside your PATH, run `pip3 show -f youtube-dl` to see where it's installed and add it to your PATH if you want.

**Comment by mayankrungta** [comment]
The files don't download for me. I see rather huge files but not really any data (I am sure the files aren't these big. Usually just about 100-200mb). These files used to download earlier -

➜  ArtOfMeaningfulConversations  ll
total 12G
-rw-r--r-- 1 mayank mayankr 1.2G Jul  5 15:40 How to speak so that people want to listen-2034.mp4
-rw-r--r-- 1 mayank mayankr  11G Nov  5 18:35 The art of the interview-708.fhls-1882.mp4.part

➜  ArtOfMeaningfulConversations  vlc How\ to\ speak\ so\ that\ people\ want\ to\ listen-2034.mp4 
VLC media player 2.2.0 Weatherwax (revision 2.2.0-0-g1349ef2)
[000000000224c118] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3664c4a340] moov atom not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3630c09f40] moov atom not found
[00007f3630c01968] avformat demux error: Could not open /home/mayank/Videos/TBV/TED/ArtOfMeaningfulConversations/How to speak so that people want to listen-2034.mp4: Unknown error 1052488119

Are you not able to reproduce the problem? The youbtube-dl version I am using is -
➜  ArtOfMeaningfulConversations  youtube-dl --version
2015.10.06.2

Putting here the output with the verbosity increased.
➜  ArtOfMeaningfulConversations  youtube-dl -v https://www.ted.com/playlists/211/the_art_of_meaningful_conversa
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.ted.com/playlists/211/the_art_of_meaningful_conversa']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.06.2
[debug] Python version 2.7.9 - Linux-3.19.0-31-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[ted] the_art_of_meaningful_conversa: Downloading playlist webpage
[download] Downloading playlist: The art of meaningful conversation 
[ted] playlist The art of meaningful conversation : Collected 7 video ids (downloading 7 of them)
[download] Downloading video 1 of 7
[ted] julian_treasure_how_to_speak_so_that_people_want_to_listen: Downloading webpage
[ted] julian_treasure_how_to_speak_so_that_people_want_to_listen: Extracting information
[ted] julian_treasure_how_to_speak_so_that_people_want_to_listen: Downloading m3u8 information
[download] How to speak so that people want to listen-2034.mp4 has already been downloaded and merged
[download] Downloading video 2 of 7
[ted] marc_pachter_the_art_of_the_interview: Downloading webpage
[ted] marc_pachter_the_art_of_the_interview: Extracting information
[ted] marc_pachter_the_art_of_the_interview: Downloading m3u8 information
[debug] Invoking downloader on u'https://hls.ted.com/talks/708/video/1500k.m3u8'
[download] Destination: The art of the interview-708.fhls-1882.mp4
[debug] avconv command line: avconv -y -headers 'Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: _abby=E0PJfu3oDjxr7Bu
' -i https://hls.ted.com/talks/708/video/1500k.m3u8 -f mp4 -c copy -bsf:a aac_adtstoasc 'file:The art of the interview-708.fhls-1882.mp4.part'
avconv version 11.2-6:11.2-1, Copyright (c) 2000-2014 the Libav developers
  built on Jan 18 2015 05:12:33 with gcc 4.9.2 (Ubuntu 4.9.2-10ubuntu2)
[mpegts @ 0x21fbc80] Continuity check failed for pid 0 expected 2 got 0
[mpegts @ 0x21fbc80] Continuity check failed for pid 258 expected 6 got 0
[mpegts @ 0x21fbc80] Continuity check failed for pid 257 expected 10 got 0
[mpegts @ 0x21fbc80] Estimating duration from bitrate, this may be inaccurate
Input #0, hls,applehttp, from 'https://hls.ted.com/talks/708/video/1500k.m3u8':
  Duration: 00:20:40.19, start: 10.000000, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0.0: Video: h264 (High), yuv420p, 1280x720 [PAR 1:1 DAR 16:9], 24 fps, 90k tbn, 48 tbc
    Stream #0.1: Data: [21][0][0][0] / 0x0015
Output #0, mp4, to 'file:The art of the interview-708.fhls-1882.mp4.part':
  Metadata:
    encoder         : Lavf56.1.0
    Stream #0.0: Video: libx264, yuv420p, 1280x720 [PAR 1:1 DAR 16:9], q=2-31, 90k tbn, 90k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press ctrl-c to stop encoding
Non-monotonous DTS in output stream 0:0; previous: 1076250, current: 0; changing to 1076251. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076251, current: 3750; changing to 1076252. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076252, current: 7500; changing to 1076253. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076253, current: 11250; changing to 1076254. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076254, current: 15000; changing to 1076255. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076255, current: 18750; changing to 1076256. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076256, current: 22500; changing to 1076257. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076257, current: 26250; changing to 1076258. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076258, current: 30000; changing to 1076259. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076259, current: 33750; changing to 1076260. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076260, current: 37500; changing to 1076261. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076261, current: 41250; changing to 1076262. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076262, current: 45000; changing to 1076263. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076263, current: 48750; changing to 1076264. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076264, current: 52500; changing to 1076265. This may result in incorrect timestamps in the output file.

**Comment by mayankrungta** [comment]
I was able to reproduce the problem on Python 3.x environment using virtualenv -

(Py-3.4_Dj-1.8)➜  ArtOfMeaningfulConversations  pip3 freeze
Django==1.8.2
selenium==2.47.1
youtube-dl==2015.11.02
(Py-3.4_Dj-1.8)➜  ArtOfMeaningfulConversations  which youtube-dl
/WD/WorkingDir/PythonDjango/Py-3.4_Dj-1.8/bin/youtube-dl

(Py-3.4_Dj-1.8)➜  ArtOfMeaningfulConversations  youtube-dl -v https://www.ted.com/playlists/211/the_art_of_meaningful_conversa
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.ted.com/playlists/211/the_art_of_meaningful_conversa']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 3.4.3 - Linux-3.19.0-31-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[ted] the_art_of_meaningful_conversa: Downloading playlist webpage
[download] Downloading playlist: The art of meaningful conversation 
[ted] playlist The art of meaningful conversation : Collected 7 video ids (downloading 7 of them)
[download] Downloading video 1 of 7
[ted] julian_treasure_how_to_speak_so_that_people_want_to_listen: Downloading webpage
[ted] julian_treasure_how_to_speak_so_that_people_want_to_listen: Extracting information
[ted] julian_treasure_how_to_speak_so_that_people_want_to_listen: Downloading m3u8 information
[download] How to speak so that people want to listen-2034.mp4 has already been downloaded and merged
[download] Downloading video 2 of 7
[ted] marc_pachter_the_art_of_the_interview: Downloading webpage
[ted] marc_pachter_the_art_of_the_interview: Extracting information
[ted] marc_pachter_the_art_of_the_interview: Downloading m3u8 information
[debug] Invoking downloader on 'https://hls.ted.com/talks/708/video/1500k.m3u8'
[download] Destination: The art of the interview-708.fhls-1882.mp4
[debug] avconv command line: avconv -y -headers 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: _abby=TQgQpGFial9hvR8
Accept-Language: en-us,en;q=0.5
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
' -i https://hls.ted.com/talks/708/video/1500k.m3u8 -f mp4 -c copy -bsf:a aac_adtstoasc 'file:The art of the interview-708.fhls-1882.mp4.part'
avconv version 11.2-6:11.2-1, Copyright (c) 2000-2014 the Libav developers
  built on Jan 18 2015 05:12:33 with gcc 4.9.2 (Ubuntu 4.9.2-10ubuntu2)
[mpegts @ 0x2031c80] Continuity check failed for pid 0 expected 2 got 0
[mpegts @ 0x2031c80] Continuity check failed for pid 258 expected 6 got 0
[mpegts @ 0x2031c80] Continuity check failed for pid 257 expected 10 got 0
[mpegts @ 0x2031c80] Estimating duration from bitrate, this may be inaccurate
Input #0, hls,applehttp, from 'https://hls.ted.com/talks/708/video/1500k.m3u8':
  Duration: 00:20:40.19, start: 10.000000, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0.0: Video: h264 (High), yuv420p, 1280x720 [PAR 1:1 DAR 16:9], 24 fps, 90k tbn, 48 tbc
    Stream #0.1: Data: [21][0][0][0] / 0x0015
Output #0, mp4, to 'file:The art of the interview-708.fhls-1882.mp4.part':
  Metadata:
    encoder         : Lavf56.1.0
    Stream #0.0: Video: libx264, yuv420p, 1280x720 [PAR 1:1 DAR 16:9], q=2-31, 90k tbn, 90k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press ctrl-c to stop encoding
Non-monotonous DTS in output stream 0:0; previous: 1076250, current: 0; changing to 1076251. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076251, current: 3750; changing to 1076252. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076252, current: 7500; changing to 1076253. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076253, current: 11250; changing to 1076254. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076254, current: 15000; changing to 1076255. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076255, current: 18750; changing to 1076256. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076256, current: 22500; changing to 1076257. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076257, current: 26250; changing to 1076258. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076258, current: 30000; changing to 1076259. This may result in incorrect timestamps in the output file.
Non-monotonous DTS in output stream 0:0; previous: 1076259, current: 33750; changing to 1076260. This may result in incorrect timestamps in the output file.

**Comment by jaimeMF** [comment]
I can reproduce the problem with avconv, but ffmpeg works fine (it sitll prints the warnings). You can either install ffmpeg or use `-f best` (it won't use ffmpeg or avconv).

**Comment by mayankrungta** [comment]
Sorry you are helping solve the wrong problem. I just want the regular file to download first. The file which shows as 11GB is supposed to be 140MB (https://www.ted.com/talks/marc_pachter_the_art_of_the_interview) and download in under 10 mins. The 11G file was a result after an hour of waiting at 50 Mbps - which hit my bandwidth. It isn't event complete. I really can't wait for such a file to complete download. Playing such a file is secondary.

So as of now if this problem isn't fixed I need to just go to the site and download the videos individually. I find this script very handy so filed the bug here. Hoping this problem gets resolved soon.

Thanks in advance,
Mayank

**Comment by jaimeMF** [comment]
As I said (maybe I wasn't clear), you can get that file if you run `youtube-dl -f best URL`.

**Comment by mayankrungta** [comment]
Sorry my bad. The option works.

Thanks,
Mayank
