### ISSUE TITLE
Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by octetoctet** [rg3/youtube-dl#7375]
Running against https://www.youtube.com/watch?v=ggLTPyRXUKc generates above error.

**Comment by jaimeMF** [comment]
Your are probably running an outdated version, you have [to update youtube-dl](https://github.com/rg3/youtube-dl/blob/edeb3e7cb1ab2d82ff7c712a7cc1e338a9dcd8f8/README.md#how-do-i-update-youtube-dl). If you still have the problem with the last version post the full output you get with the `--verbose` flag (as explained in [the bug reporting guide](https://github.com/rg3/youtube-dl/blob/edeb3e7cb1ab2d82ff7c712a7cc1e338a9dcd8f8/README.md#bugs)).

**Comment by octetoctet** [comment]
Works in latest, probably ubuntu 14.04.x release version issue.
