### ISSUE TITLE
YouTube DASH bestvideo+bestaudio excluding WebM?

### ISSUE THREAD

**Issue by wp9015362** [rg3/youtube-dl#7377]
Hello,

I read the format selection readme:

https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection

But I still have got a question:

What would the format selection have to look like if you would want to get YouTube DASH bestvideo+bestaudio excluding WebM?

I mean so that you will get the best H.264 video and the best AAC audio and ***not*** WebM.

I only need H.264 video and AAC audio because hardware acceleration does not work on WebM.

Regards

**Comment by wp9015362** [comment]
Would:

 -f bestvideo[ext=mp4]+bestaudio[ext=mp4]

be correct?

**Comment by dstftw** [comment]
Yes.
