### ISSUE TITLE
s3fs ERROR: unable to open for writing: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by allewwaly** [rg3/youtube-dl#738]
As the title says, when I tried to download a youtube video like:
 youtube-dl  www.youtube.com/watch?v=ZcUsR9DSSOk,
the result showed:
 s3fs ERROR: unable to open for writing: [Errno 13] Permission denied
What's the problem then? Thanks.

**Comment by monil20** [comment]
Try
$sudo youtube-dl [YouTube Link]

**Comment by JohnMcLear** [comment]
@monil20 that's not really good advice...

**Comment by cleanspin** [comment]
If you're doing this on gcp I think you don't have permission to write unless you invoke sudo
