### ISSUE TITLE
Not able to download several videos/parts from the same videolectures.net url

### ISSUE THREAD

**Issue by smuelas** [rg3/youtube-dl#7384]
Hi,

First of all thank you for this wonderful tool. I was trying to download the videos from a videolectures.net url (youtube-dl http://videolectures.net/mlss09uk_bishop_ibi/) but I have not been able to download all the videos that are listed in the web page (part1 and part2), it always downloads the first part. Is it possible to select which part to download? (I have used the playlist options but they seem not to work in this case).  I have used youtube-dl version 2015.11.02.

**Comment by dstftw** [comment]
Until it implemented in videolectures extractor you can download the second part with `youtube-dl  http://videolectures.net/mlss09uk_bishop_ibi/video/2/smil.xml`.

**Comment by smuelas** [comment]
Thank you for your quick answer!
