### ISSUE TITLE
NBC Stopped working 

### ISSUE THREAD

**Issue by jimbolaya** [rg3/youtube-dl#7385]
I was trying to figure out how to get subtitles from CBS, since youtube-dl didn't seem to support that so I was looking at the "Console" for that and decided to see what it looked like for NBC, since I was able to get the ttml subtitles for the "The Troll Farmer" from "The Blacklist" on October 2 when I was running the current (at the time) version of youtube-dl.
I had updated youtube-dl to 2015.11.02 to see if that would help. I also decided to run the download from NBC in verbose mode to see what that was doing. However, when I ran
```shell
youtube-dl --verbose 'http://www.nbc.com/the-blacklist/video/sir-crispin-crandall/2928790?onid=137781#vc137781=1'
```
I got an error "ExtractorError: No video formats found".
I've looked through some other posts and they were asked to run with "--verbose --write-pages", so here is the output for that 
```shell
$ youtube-dl --verbose --write-pages 'http://www.nbc.com/the-blacklist/video/sir-crispin-crandall/2928790?onid=137781#vc137781=1'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--write-pages', u'http://www.nbc.com/the-blacklist/video/sir-crispin-crandall/2928790?onid=137781#vc137781=1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.6 - Linux-3.13.0-30-generic-x86_64-with-LinuxMint-17-qiana
[debug] exe versions: avconv N-76045-g97be5d4, avprobe N-76045-g97be5d4, ffmpeg N-76045-g97be5d4, ffprobe N-76045-g97be5d4, rtmpdump 2.4
[debug] Proxy map: {}
[NBC] 2928790: Downloading webpage
[NBC] Saving request to 2928790_http_-_www.nbc.com_the-blacklist_video_sir-crispin-crandall_2928790onid=137781.dump
[ThePlatform] guid: Downloading SMIL data
[ThePlatform] Saving request to guid_http_-_link.theplatform.com_s_NnzsPC_media_guid_meta.smilformat=smil_mbr=true.dump
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 36, in _extract_theplatform_smil
    for n in meta.findall(_x('.//smil:ref'))
StopIteration
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 213, in _real_extract
    formats, subtitles = self._extract_theplatform_smil(smil_url, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 48, in _extract_theplatform_smil
    transform_rtmp_url=lambda streamer, src: (streamer, 'mp4:' + src))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1177, in _parse_smil_formats
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Here is the gist link to the dump files:
https://gist.github.com/jimbolaya/2fae3b44e2fec1c3da42

Please let me know if there's anything else I can do on this.

**Comment by gaming-hacker** [comment]
that site is really obfuscated, full of bugs and trackers.

**Comment by colomon** [comment]
I can confirm I'm seeing this problem too with 2015.11.02 (and an older version as well).  Downloading from the NBC site worked last week and does not work now.  I get essentially the same trace as jimbolaya did, will post it if that would be helpful.

(Mind you, it was a really pleasant surprise when youtube-dl worked for me on the NBC site the last few weeks.  I certainly didn't expect it to work when I tried, and I was delighted when it did!)

**Comment by snipem** [comment]
Same here
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--simulate', '--get-filename', '-v', 'http://nbc.com/saturday-night-live/video/november-7-donald-trump/2930067?onid=140196', '-o', '%(title)s-%(id)s.%(ext)s']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.11.02
[debug] Python version 3.5.0 - Linux-3.16.4-1-ARCH-i686-with-arch
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "../youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "../youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "../youtube-dl/youtube_dl/extractor/theplatform.py", line 213, in _real_extract
    formats, subtitles = self._extract_theplatform_smil(smil_url, video_id)
  File "../youtube-dl/youtube_dl/extractor/theplatform.py", line 48, in _extract_theplatform_smil
    transform_rtmp_url=lambda streamer, src: (streamer, 'mp4:' + src))
  File "../youtube-dl/youtube_dl/extractor/common.py", line 1177, in _parse_smil_formats
    self._sort_formats(formats)
  File "../youtube-dl/youtube_dl/extractor/common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by saapa** [comment]
Instead of having another one for the same problem I closed my ticket and am pasting what I had in here:



youtube-dl.exe --verbose http://www.nbc.com/days-of-our-lives/video/monday-november-9-2015/2931185?onid=137306#vc137306=1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.nbc.com/days-of-our-lives/video/monday-november-9-2015/2931185?onid=137306#vc137306=1']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.13
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-55159-gf118b41, rtmpdump 2.4
[debug] Proxy map: {}
[NBC] 2931185: Downloading webpage
[ThePlatform] guid: Downloading SMIL data
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "youtube_dl\extractor\theplatform.pyo", line 36, in _extract_theplatform_smil
StopIteration
Traceback (most recent call last):
File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
File "youtube_dl\extractor\common.pyo", line 290, in extract
File "youtube_dl\extractor\theplatform.pyo", line 213, in _real_extract
File "youtube_dl\extractor\theplatform.pyo", line 48, in _extract_theplatform_smil
File "youtube_dl\extractor\common.pyo", line 1177, in _parse_smil_formats
File "youtube_dl\extractor\common.pyo", line 766, in _sort_formats
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Example URL: http://www.nbc.com/days-of-our-lives/video/monday-november-9-2015/2931185?onid=137306#vc137306=1

This does not happen with all NBC shows. This: http://www.nbc.com/the-tonight-show/video/elizabeth-banks-jon-glaser-tim-mcgraw/2933418 works fine

**Comment by bonacker** [comment]
I get the same log as the above with nbcnews.com. NBCNEWS.COM is kind of important, and it has been very valuable for quite a while. I hope somebody fixes it. TIA, and thanks for all the work that's been done already that makes youtube-dl so great.

**Comment by bonacker** [comment]
I don't know if the geo-restricted tag was added to mean that the problem described by me and others above is due to geo-restriction.

I'm in California, so even if the content is unavailable to those outside the U.S. it isn't the reason I'm no longer able to download from NBC NEWS. I am able to view those shows in a browser.

The NBC entertainment shows may well be geo-restricted, but I wonder if the NBC NEWS shows are as well.

**Comment by dstftw** [comment]
Geo-restricted tag means that all provided example URLs are geo-restricted and nothing more.

**Comment by dstftw** [comment]
Should work in the next version.

**Comment by snipem** [comment]
Thank you big time

**Comment by timlet** [comment]
Latest Windows build is now returning this on NBC Meet the Press. Plays fine in browser, so not geo-restricted. Any thoughts? Thanks.

youtube-dl --verbose http://www.nbc.com/meet-the-press/video/meet-the-press-nov-8-2015/2933157?onid=210121#vc210121=1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.nbc.com/meet-the-press/vi
deo/meet-the-press-nov-8-2015/2933157?onid=210121#vc210121=1']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-50911-g9efcfbe
[debug] Proxy map: {}
[NBC] 2933157: Downloading webpage
[ThePlatform] guid: Downloading webpage
[ThePlatform] guid: Downloading SMIL data
[ThePlatform] guid: Downloading m3u8 information
[ThePlatform] guid: Downloading m3u8 information
[ThePlatform] guid: Downloading m3u8 information
[ThePlatform] guid: Downloading m3u8 information
[ThePlatform] guid: Downloading m3u8 information
[ThePlatform] guid: Downloading m3u8 information
[ThePlatform] guid: Downloading JSON metadata
[debug] Invoking downloader on u'https://nbcmpx-vh.akamaihd.net/i/video/626/819/
151106_2933157_Meet_the_Press___Nov__8__2015_mpx_,1696,1296,896,696,496,306,240,
150,64,.mp4.csmil/index_0_av.m3u8?null=&id=AgCC2EVduBx+ti5+V1axwYhoLp7lB+rqFASIC
1DbOx24Xdx632ybWZAHfMcTvry2223WZlqcKvkIvw%3d%3d&hdntl=exp=1448660910~acl=%2fi%2f
video%2f626%2f819%2f151106_2933157_Meet_the_Press___Nov__8__2015_mpx_*~data=hdnt
l~hmac=01cd621757f4f5ef5f1a27742a6e8e971f2b4f5a34f7679b88c7cd7303764408'
[download] Destination: Meet the Press - Nov. 8, 2015-guid.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Language: en-us,en;q=0.5

Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0
 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: _alid_=H3Ka9doA1aed9EVAm72Jpg==
' -i 'https://nbcmpx-vh.akamaihd.net/i/video/626/819/151106_2933157_Meet_the_Pre
ss___Nov__8__2015_mpx_,1696,1296,896,696,496,306,240,150,64,.mp4.csmil/index_0_a
v.m3u8?null=&id=AgCC2EVduBx+ti5+V1axwYhoLp7lB+rqFASIC1DbOx24Xdx632ybWZAHfMcTvry2
223WZlqcKvkIvw%3d%3d&hdntl=exp=1448660910~acl=%2fi%2fvideo%2f626%2f819%2f151106_
2933157_Meet_the_Press___Nov__8__2015_mpx_*~data=hdntl~hmac=01cd621757f4f5ef5f1a
27742a6e8e971f2b4f5a34f7679b88c7cd7303764408' -f mp4 -c copy -bsf:a aac_adtstoas
c 'file:Meet the Press - Nov. 8, 2015-guid.mp4.part'
ffmpeg version N-50911-g9efcfbe Copyright (c) 2000-2013 the FFmpeg developers
  built on Mar 13 2013 21:26:48 with gcc 4.7.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libg
sm --enable-libilbc --enable-libmp3lame --enable-libopencore-amrnb --enable-libo
pencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-li
bschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-lib
twolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enabl
e-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 19.100 / 52. 19.100
  libavcodec     55.  0.100 / 55.  0.100
  libavformat    55.  0.100 / 55.  0.100
  libavdevice    54.  4.100 / 54.  4.100
  libavfilter     3. 45.103 /  3. 45.103
  libswscale      2.  2.100 /  2.  2.100
  libswresample   0. 17.102 /  0. 17.102
  libpostproc    52.  2.100 / 52.  2.100
[https @ 037cf6e0] HTTP error 403 Forbidden
Unable to open key file https://nbcmpx-vh.akamaihd.net/i/video/626/819/151106_29
33157_Meet_the_Press___Nov__8__2015_mpx_,1696,1296,896,696,496,306,240,150,64,.m
p4.csmil/crypt.key?null=&id=AgCC2EVduBx+ti5+V1axwYhoLp7lB+rqFASIC1DbOx24Xdx632yb
WZAHfMcTvry2223WZlqcKvkIvw%3d%3d&hdntl=exp=1448660910~acl=/i/video/626/819/15110
6_2933157_Meet_the_Press___Nov__8__2015_mpx_*~data=hdntl~hmac=01cd621757f4f5ef5f
1a27742a6e8e971f2b4f5a34f7679b88c7cd7303764408
[http @ 037a9900] HTTP error 403 Forbidden
[crypto @ 037cf6e0] Unable to open input
[hls,applehttp @ 00303640] Error when loading first segment 'http://nbcmpx-vh.ak
amaihd.net/i/video/626/819/151106_2933157_Meet_the_Press___Nov__8__2015_mpx_,169
6,1296,896,696,496,306,240,150,64,.mp4.csmil/segment1_0_av.ts?null=&id=AgCC2EVdu
Bx+ti5+V1axwYhoLp7lB+rqFASIC1DbOx24Xdx632ybWZAHfMcTvry2223WZlqcKvkIvw%3d%3d&hdnt
l=exp=1448660910~acl=/i/video/626/819/151106_2933157_Meet_the_Press___Nov__8__20
15_mpx_*~data=hdntl~hmac=01cd621757f4f5ef5f1a27742a6e8e971f2b4f5a34f7679b88c7cd7
303764408'
https://nbcmpx-vh.akamaihd.net/i/video/626/819/151106_2933157_Meet_the_Press___N
ov__8__2015_mpx_,1696,1296,896,696,496,306,240,150,64,.mp4.csmil/index_0_av.m3u8
?null=&id=AgCC2EVduBx+ti5+V1axwYhoLp7lB+rqFASIC1DbOx24Xdx632ybWZAHfMcTvry2223WZl
qcKvkIvw%3d%3d&hdntl=exp=1448660910~acl=%2fi%2fvideo%2f626%2f819%2f151106_293315
7_Meet_the_Press___Nov__8__2015_mpx_*~data=hdntl~hmac=01cd621757f4f5ef5f1a27742a
6e8e971f2b4f5a34f7679b88c7cd7303764408: Input/output error


ERROR: ffmpeg exited with code 1
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 410, in main
  File "youtube_dl\__init__.pyo", line 400, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1669, in download
  File "youtube_dl\YoutubeDL.pyo", line 674, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 727, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 674, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 720, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1339, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1601, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1543, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\hls.pyo", line 61, in real_download
  File "youtube_dl\downloader\common.pyo", line 155, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 538, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 500, in trouble

**Comment by yan12125** [comment]
Could you download [ffmpeg version git-72eaf72 (2015-11-26)](http://ffmpeg.zeranoe.com/builds/) and try again? If not, please open a new issue.
