### ISSUE TITLE
multiple connections with aria2c

### ISSUE THREAD

**Issue by ExtendedDev** [rg3/youtube-dl#7398]
is it possible to properly configure aria2c for more than 4 connections. As is well known, by default using aria as ext dl 4 multiple connections are used. It would be a good idea to alter this arg number. For instance increase the number of ml connections to 6. Cl argument   -x16   is unusable. --max-connection-per-server=<NUM> also unusable in this case.  It's sufficiently complex to use multiple arguments in --external-downloader-args ARGS  It's difficult to find more detailed info in documentation of aria.

**Comment by dstftw** [comment]
You can use arbitrary command line to be passed to aria2c with `--external-downloader-args` and I don't see any problem using it.

**Comment by kidol** [comment]
Try this:
```
youtube-dl --external-downloader aria2c --external-downloader-args "-j 8 -s 8 -x 8 -k 5M"
```

The trick is that -j, -s and -x must all be defined. Also -k ("max part size") defaults to 20M which means if you have a video of 40M, you can not use more than 2 connections by default. So better to lower it...

**Comment by dstftw** [comment]
Then define them all, what's the problem? Current default command line until you provide your own with `--external-downloader-args` is `--min-split-size 1M --max-connection-per-server 4`.

**Comment by kidol** [comment]
No problem, just trying to help that guy.

**Comment by ExtendedDev** [comment]
Thanks, it works perfectly. The main mistake that I made before I had forgotten the quotation marks on args parameters. -j 12 -s 12 -x 12 in my case, gives quickest speed, that is supported on my specs.
