### ISSUE TITLE
[shahid] Add support for shows/playlists

### ISSUE THREAD

**Issue by nedz14** [rg3/youtube-dl#7401]
any chance to Add support for https://shahid.mbc.net/ar/shows.html
thanks.

**Comment by dstftw** [comment]
What should be downloaded by this URL?

**Comment by nedz14** [comment]
videos like this https://shahid.mbc.net/ar/show/49008/The-Voice.html?utm_source=hootsuite&utm_medium=web&utm_term=fomasoud&utm_content=&utm_campaign=smu
thx

**Comment by dstftw** [comment]
So your request is to download all videos of the show as playlist?

**Comment by nedz14** [comment]
yes please if possible.

**Comment by nedz14** [comment]
i have the intention to watch them in smplayer with mpv and youtube-dl.

**Comment by dstftw** [comment]
Individual videos are already supported.

**Comment by nedz14** [comment]
yes, i just try it.
thank u dstftw.

**Comment by kim0** [comment]
Downloading from "shows" sounds a little too aggressive to me, however I do hope we'll be able to support episodes from a season, example link
https://shahid.mbc.net/ar/series/127907/%D8%A3%D8%B1%D9%8A%D8%AF-%D8%B1%D8%AC%D9%84%D8%A7.html

**Comment by kim0** [comment]
@dstftw .. Just to be clear, the actual episodes are those in div with class "slider clips" on this for example: https://shahid.mbc.net/ar/series/141409/%D9%88%D8%B9%D8%AF.html

If there's no intention to fix this, can someone at least guide me how to modify the python code to add such functionality. Thanks for a great tool!

**Comment by kim0** [comment]
I just tried my hand with the following beautifulsoup code
```
[e['href'] for e in soup.select_one(".slider").select("a")]
```
where soup is the whole html loaded. It seems to get direct links to all the episodes, or at least the ones between episode 7-30 .. The ones before 7, seem to be loaded dynamically after you click the little left javascript arrow (sic) .. Unfortunately, I have no idea how to simulate that click in python! Any help is most welcome
