### ISSUE TITLE
can't download from movieclips.com

### ISSUE THREAD

**Issue by sackio** [rg3/youtube-dl#7404]
youtube-dl http://www.movieclips.com/videos/london-has-fallen-exclusive-trailer-1-558522435763?playlistId=5
[generic] london-has-fallen-exclusive-trailer-1-558522435763?playlistId=5: Requesting header
[redirect] Following redirect to http://www.movieclips.com/browser-unsupported
[generic] browser-unsupported: Requesting header
WARNING: Falling back on generic information extractor.
[generic] browser-unsupported: Downloading webpage
[generic] browser-unsupported: Extracting information
ERROR: Unsupported URL: http://www.movieclips.com/browser-unsupported

**Comment by jaimeMF** [comment]
Thanks for the report, it will work in the next version.
