### ISSUE TITLE
ERROR: no suitable InfoExtractor for URL When trying to extract audio from kit

### ISSUE THREAD

**Issue by vondiplo** [rg3/youtube-dl#7406]
On MIT's website there's an embedded youtube player. I'd like to download the youtube video directly from it's page.  This is the page - http://video.mit.edu/watch/in-profile-mits-catherine-tucker-12724/

When I run this command :
youtube-dl http://video.mit.edu/watch/in-profile-mits-catherine-tucker-12724/

I get the following error : 
ERROR: no suitable InfoExtractor for URL http://www.youtube.com/embed/0ZUoa9Wx7XQ?autoplay=1&hd=1&wmode=transparent&rel=0

I'd expect youtube-dl to find the embedded iframe on page and handle it, or am I mistaken?

**Comment by vondiplo** [comment]
should I pull latest repository then?

**Comment by dstftw** [comment]
If you don't want to wait for the next release.

**Comment by vondiplo** [comment]
ok, thanks !
