### ISSUE TITLE
Support for CMT.com?

### ISSUE THREAD

**Issue by dongy789** [rg3/youtube-dl#7407]
I think I am right in thinking that CMT.com is supported, but I seem to always get the 'unsupported url' message.
this is the video I am trying - http://www.cmt.com/shows/party-down-south/party-down-south-ep-407-gone-girl/1738172/playlist/#id=1738172

many thanks.

**Comment by dongy789** [comment]
so what exactly does this mean? forgive my ignorance, but I am not sure what the response meant.

**Comment by dstftw** [comment]
This issue will be fixed in the next verion of youtube-dl.

**Comment by dongy789** [comment]
wicked,,,appreciate it.
