### ISSUE TITLE
globotv changed to globoplay.globo.com

### ISSUE THREAD

**Issue by issamu2k** [rg3/youtube-dl#7408]
Apparently, brazilian channel globo reformulated his streaming video content website, now the address is globoplay.globo.com. 
Here is the output

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://globoplay.globo.com/v/4592439/', u'--verbose']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.6 - Linux-3.10.80-125-armv7l-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.4.3, ffprobe 2.4.3
[debug] Proxy map: {}
[Globo] v/4592439/: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/globo.py", line 357, in _real_extract
    video_id = self._search_regex(self._VIDEOID_REGEXES, webpage, 'video id')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by issamu2k** [comment]
Just updated it.

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl.
