### ISSUE TITLE
building from source errors:  removing fail/error tests

### ISSUE THREAD

**Issue by gaming-hacker** [rg3/youtube-dl#7410]
i'm building my own version and have all of the dependencies installed.
i did a git pull 5 minutes ago
no issues with make 
with make test

#nosetests --with-coverage --cover-package=youtube_dl --cover-html --verbose --processes 4 test
nosetests --verbose test

most tests pass with these exceptions

test_youporn (test.test_age_restriction.TestAgeRestriction) ... ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR

test_Allocine_1 (test.test_download.TestDownload) ... FAIL
test_Allocine_2 (test.test_download.TestDownload) ... FAIL
test_AlphaPorno (test.test_download.TestDownload) ... ERROR
test_AnySex (test.test_download.TestDownload) ... ERROR
test_Aol_1 (test.test_download.TestDownload) ... ERROR
test_Aparat (test.test_download.TestDownload) ... FAIL
test_AppleConnect (test.test_download.TestDownload) ... FAIL
test_ArchiveOrg_1 (test.test_download.TestDownload) ... FAIL
test_ArteTVConcert (test.test_download.TestDownload) ... FAIL
test_ArteTVCreative (test.test_download.TestDownload) ... ERROR
test_ArteTVCreative_1 (test.test_download.TestDownload) ... ERROR
test_ArteTVFuture (test.test_download.TestDownload) ... ERROR
test_AtresPlayer (test.test_download.TestDownload) ... ERROR
test_Audiomack_1 (test.test_download.TestDownload) ... ERROR
+ about 100 more

which tests are critical for testing functionality?

i'm going to remove all tests that fail or error from my build if they are not critical.

**Comment by jaimeMF** [comment]
Run `make offlinetest` for testing most of the core of youtube-dl. Use `nosetests -v test/test_download.py -m <IE>` (like `nosetests -v test/test_download.py -m Vimeo`) to run the test for an especific extractor.
