### ISSUE TITLE
Youtube-dl Config File Not Reading...

### ISSUE THREAD

**Issue by Waldoctg** [rg3/youtube-dl#7424]
I added it to ~/usr/local/etc and I set it to youtube-dl.conf in my system but it doesn't work. This is what I added:
    --extract-audio
    --no-mtime
    --audio-format wav
    --audio-quality 0
    --output "~/Downloads/%(title)s.%(ext)s"
I searched around a lot, but I can't find why it isn't reading. Any advice?

**Comment by dstftw** [comment]
`~/usr/local/etc` is not a valid configuration path. Read [FAQ](https://github.com/rg3/youtube-dl#configuration).

**Comment by Waldoctg** [comment]
It says `/etc/youtube-dl.conf` though...I'm confused, isn't that where I'm at?

**Comment by jaimeMF** [comment]
`/etc/youtube-dl.conf` is not in your home folder. If you want a config just for your user, you can use `~/.config/youtube-dl/config`.

**Comment by Waldoctg** [comment]
I try that too, but when I type `~/.config/youtube-dl/config` in Terminal, it says `-bash: cd: /Users/USERNAME/.config/youtube-dl/config: No such file or directory`

**Comment by dstftw** [comment]
Obviously you must create it first.

**Comment by jaimeMF** [comment]
To be clear: you must create the file `config` inside the `~/.config/youtube-dl` folder (which you obviously need to create first).

**Comment by Waldoctg** [comment]
Thanks!
