### ISSUE TITLE
youtube-dl.exe login error on lynda

### ISSUE THREAD

**Issue by web-gab** [rg3/youtube-dl#7430]
I am trying to download a playlist from lynda with youtube-dl.exe but it keeps giving this error "Unable to login". I am using this command:
youtube-dl.exe "" -o "D:\path-to-my-folder/%(autonumber)s-%(title)s.%(ext)s" --autonumber-size 2 --username myusername@gmail.com --password mypassword
It used to work ok since yesterday when I tried to download a playlist. It works if I download each video separately.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
