### ISSUE TITLE
Automatic signature extraction failed: Traceback (most recent call last): 

### ISSUE THREAD

**Issue by mitguru007** [rg3/youtube-dl#7435]
Hello! 
I am use latest version of youtube-dl (2015.11.10) but some video cant not download get bellow error 
"Automatic signature extraction failed: Traceback (most recent call last): "
i try: "youtube-dl https://www.youtube.com/watch?v=ffmTK9uKM_k"

when i install Version 2014.06.19 of youtube-dl and try for download then showing blank page because signature value is can not get full, some text missing from signature value so get error. 

* Request To Developer->  Please fix signature value problem in Latest version of youtube-dl. 
-Thanks

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by mitguru007** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.19
[debug] Python version 2.6.6 - Linux-3.14.32-xxxx-grs-ipv6-32-i686-with-centos-6.6-Final
[debug] Proxy map: {}
Usage: youtube-dl [options] url [url...]

**Comment by dstftw** [comment]
Post the output of `youtube-dl https://www.youtube.com/watch?v=ffmTK9uKM_k -v` when you run with latest version.

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by mitguru007** [comment]
Thanks my big brother. When update youtube-dl then fix the problem.  4 hours ago i 3 times time update but get same problem so i contact here.  may be today's latest version is update few minutes ago. 
i need another help. 
how to get  c.docs.google.com url in downloading url?
Ex. http://ytapi.com/?format=direct&vid=ffmTK9uKM_k&itag=18
currently i get googlevideo.com

**Comment by dstftw** [comment]
Open a new issue for different problem.
