### ISSUE TITLE
How To get  c.docs.google.com in downloading url?

### ISSUE THREAD

**Issue by mitguru007** [rg3/youtube-dl#7438]
Hello!
youtube-dl  video downloading url get with googlevideo.com.
how to get c.docs.google.com.
Ex. https://r13---sn-4g57km76.c.docs.google.com/videoplayback?sparams=dur,expire,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,nh,pl,ratebypass,requiressl,source,upn&lmt=1407437790345147&dur=163.213&signature=816A506545132105B55F7597E7ADB3CD0F9A2C51.496F2E6324093E0534218ECD17448026E8F6925A&sver=3&ratebypass=yes&ipbits=0&upn=VDBI6M_lDzI&key=cms1&fexp=9406983%2C9408710%2C9414764%2C9416126%2C9417683%2C9417707%2C9420453%2C9422596%2C9422618%2C9423644%2C9423662&itag=18&source=youtube&pl=24&requiressl=yes&mime=video%2Fmp4&ip=85.25.137.5&expire=1447175933&id=o-AIJTySCYzylmH-uYx1aYB36mtMD95kNOBYHaTjgQkElE&cms_redirect=yes&mm=31&mn=sn-4g57km76&ms=au&mt=1447165897&mv=m&nh=EAU
-Thanks

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) with URL you are trying to download.

**Comment by mitguru007** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.6.6 - Linux-2.6.32-504.12.2.el6.i686-i686-with-centos-6.7-Final
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

**Comment by dstftw** [comment]
**Closely** re-read my post.
