### ISSUE TITLE
How to download 1080p video?

### ISSUE THREAD

**Issue by mitguru007** [rg3/youtube-dl#7439]
How to download 1080p video in youtube-dl?
It's possible or not?

**Comment by dstftw** [comment]
You can select any available quality using [format selection](https://github.com/rg3/youtube-dl#format-selection).

**Comment by mitguru007** [comment]
when i use bellow code then not showing 1080p video format. but originally https://www.youtube.com/watch?v=4Ag3g198jaI  video is 1080p video.
"youtube-dl -j https://www.youtube.com/watch?v=4Ag3g198jaI"

**Comment by dstftw** [comment]
It does.
```
youtube-dl -j https://www.youtube.com/watch?v=4Ag3g198jaI
...
"requested_formats": [{"asr": null, "tbr": 4162, "format": "137 - 1920x1080 (DASH video)"
...
```

**Comment by mitguru007** [comment]
Get Error:
"ERROR: requested format not available"
Bro when i run " youtube-dl https://www.youtube.com/watch?v=4Ag3g198jaI --skip-download --list-formats" get bellow output:

[info] Available formats for 4Ag3g198jaI:
format code  extension  resolution note
249          webm       audio only DASH audio   55k , opus @ 50k, 804.41KiB
250          webm       audio only DASH audio   78k , opus @ 70k, 1.08MiB
140          m4a        audio only DASH audio  127k , m4a_dash container, aac  @128k (44100Hz), 1.88MiB
171          webm       audio only DASH audio  148k , vorbis@128k (44100Hz), 1.90MiB
251          webm       audio only DASH audio  151k , opus @160k, 2.11MiB
160          mp4        256x144    DASH video  110k , avc1.42c00c, 13fps, video only, 1.61MiB
278          webm       256x144    DASH video  122k , webm container, vp9, 13fps, video only, 1.47MiB
133          mp4        426x240    DASH video  249k , avc1.4d4015, 25fps, video only, 3.63MiB
242          webm       426x240    DASH video  253k , vp9, 25fps, video only, 3.26MiB
243          webm       640x360    DASH video  474k , vp9, 25fps, video only, 6.06MiB
134          mp4        640x360    DASH video  622k , avc1.4d401e, 25fps, video only, 8.09MiB
244          webm       854x480    DASH video  886k , vp9, 25fps, video only, 11.08MiB
135          mp4        854x480    DASH video 1125k , avc1.4d401e, 25fps, video only, 14.94MiB
247          webm       1280x720   DASH video 1694k , vp9, 25fps, video only, 21.86MiB
136          mp4        1280x720   DASH video 2220k , avc1.4d401f, 25fps, video only, 28.75MiB
248          webm       1920x1080  DASH video 2987k , vp9, 25fps, video only, 39.07MiB
137          mp4        1920x1080  DASH video 4162k , avc1.640028, 25fps, video only, 50.49MiB
17           3gp        176x144    small ,  mp4a.40.2, mp4v.20.3
36           3gp        320x240    small ,  mp4a.40.2, mp4v.20.3
5            flv        400x240    small
43           webm       640x360    medium ,  vorbis, vp8.0
18           mp4        640x360    medium ,  mp4a.40.2, avc1.42001E
22           mp4        1280x720   hd720 ,  mp4a.40.2, avc1.64001F (best)

**Comment by dstftw** [comment]
1080p
>248 webm 1920x1080 DASH video 2987k , vp9, 25fps, video only, 39.07MiB
137 mp4 1920x1080 DASH video 4162k , avc1.640028, 25fps, video only, 50.49MiB

**Comment by mitguru007** [comment]
Yes bro 1080 available but not get 1080p and 480p when run "youtube-dl -j https://www.youtube.com/watch?v=4Ag3g198jaI". 
can you give me command so i get all available format up to 1080p?

**Comment by dstftw** [comment]
Install ffmpeg or avconv.

**Comment by mitguru007** [comment]
i can not get url without install ffmpeg or avconv? Like 720p

**Comment by dstftw** [comment]
You can, but 1080p is DASH and has no audio. You'll need to mux yourself.

**Comment by mitguru007** [comment]
and 480p same as 1080p?  means no audio?

**Comment by dstftw** [comment]
Everything labelled "video only" has no audio.

**Comment by mitguru007** [comment]
ok brother thanks for help me.

**Comment by dreamchonghua** [comment]
Please tell me how to download  https://www.youtube.com/watch?v=OmCO26lDDjs   this url ,1920*1080video,and Synthesis,Thank you!!!

**Comment by yan12125** [comment]
@dreamchonghua Install ffmpeg and download.

**Comment by dreamchonghua** [comment]
@yan12125 how to ffmpeg,What command input in the CMD it, why I synthesized the document is relatively large, thank you，

**Comment by Hrxn** [comment]
For Windows?

Here: https://ffmpeg.zeranoe.com/builds/
