### ISSUE TITLE
super slow -j (json dumps) for soundcloud playlist 

### ISSUE THREAD

**Issue by greg218** [rg3/youtube-dl#7441]
I'm trying to quickly get the video info to a soundcloud playlist.  For example https://soundcloud.com/shaun-flint/sets/hip.

I run the command 
```
"youtube-dl -j https://soundcloud.com/shaun-flint/sets/hip"
```
and it iterates through everything but takes ages! 

**Is there any faster method to get all info?** 

I noticed that this is the same for youtube playlists.
Thanks.

**Comment by dstftw** [comment]
No, you can't extract everything without extracting everything.
There is a way to get only individual links with `--flat-playlist` but it's obviously not what you want.
