### ISSUE TITLE
Syntax Problem: vimeo - specific user and filenames

### ISSUE THREAD

**Issue by elsakuh** [rg3/youtube-dl#7446]
Try to download specific named files from vimeo "V8 Supercars 2015" from a user called: devilstorm:

Can't get the syntax working correct 
I have found the parameter  
--match-title REGEX              Download only matching titles (regex or
                                     caseless sub-string)
but do not understand how to integrate into commandline:
this is as far as I get:
D:\Youtube\youtube-dl\youtube-dl -ciw vimeo:devilstorm d:\youtube\vimeo\devilstorm\%%(playlist)s\%%(title)s.%%(ext)s ???--match-title  'V8 Supercars 2015*' ???

appreciate your help

**Comment by dstftw** [comment]
`youtube-dl -ciw https://vimeo.com/devilstorm d:\youtube\vimeo\devilstorm\%(playlist)s\%(title)s.%(ext)s --match-title "V8 Supercars 2015"`

**Comment by elsakuh** [comment]
Thank you very much appeciate your help!
