### ISSUE TITLE
ERROR: no write permissions on youtube-dl [windows 8]

### ISSUE THREAD

**Issue by 5shekel** [rg3/youtube-dl#745]
not a youtube-dl problem per se, but can effect users struggling with windows 8 machines.
even when opened as "elevated command line" still cant get youtube-dl to run or update.

```
C:\>youtube-dl --update
Hi! We changed distribution method and now youtube-dl needs to update itself on
 more time.
This will only happen once. Simply press enter to go on. Sorry for the trouble!
From now on, get the binaries from http://rg3.github.com/youtube-dl/download.ht
l, not from the git repository.

ERROR: no write permissions on youtube-dl
```

solution > http://i.imgur.com/9oJfcnL.jpg
set permissions on file>right click>properties>security

**Comment by lucaslopes** [comment]
## [SOLVED] on mac:

`ERROR: no write permissions on /path/to/youtube-dl`
1. go to that `path` shown in the error message, if is an `alias` then right click on it and select `Show Original`;
2. right click on `youtube-dl` file and then click `Get Info`, in `Sharing & Permissions` change the privilege of `admin` and your `user` from `Read only` to `Read & Write`;
3. drag the `youtube-dl` file on terminal and put `   -U` in the end of the line and hit `enter` to update it.

I suggest you first try skipping step 2; if doesn't work, then you repeat including it, but re-change the permissions to `Read only`, at least from your `user`.
