### ISSUE TITLE
asp.net web service latest version

### ISSUE THREAD

**Issue by codaman** [rg3/youtube-dl#7453]
i'm trying to code c# web service that using youtube-dl.exe in command and returns me all format output before i used 2015.10.18 version there is no problem but i update to latest version there is no output. In debug mode it also works but after publishing to real server i couldnt get no output. Can anyone help me. I tried all privilages

**Comment by yan12125** [comment]
Maybe there are error messages. Can you catch standard error (stderr) outputs in C#? If so, paste them here.

**Comment by codaman** [comment]
yes i'm getting this error

i'm using youtube-dl on .net web service it also get this error

Traceback (most recent call last): File "main.py", line 19, in File "youtube_dl__init__.pyo", line 410, in main File "youtube_dl__init__.pyo", line 377, in real_main File "youtube_dl\YoutubeDL.pyo", line 338, in __init_ File "youtube_dl\YoutubeDL.pyo", line 1969, in _setup_opener File "youtube_dl\utils.pyo", line 492, in make_HTTPS_handler File "ssl.pyo", line 440, in create_default_context File "ssl.pyo", line 391, in load_default_certs File "ssl.pyo", line 378, in _load_windows_store_certs WindowsError: [Error 5] Access is denied

but there is no problem 2015.10.18 and older versions

**Comment by codaman** [comment]
and i'm also checkin what cause this i'm searching commits after 2015.10.18 there is a a commit Fix py2exe build (#7276) this line added "dll_excludes": ['w9xpopen.exe', 'crypt32.dll'],. may be crypt32.dll cause this access problem. may be i have to rebuid and create and exe file

**Comment by dstftw** [comment]
With `crypt32.dll` bundled it does not work at all. As seen from log your issue is related to insufficient access when loading certificates.
What is the user account the service is running under? Try running under account with Administrator access. What happens when you run youtube-dl from cmd?

**Comment by codaman** [comment]
it works run on cmd in server. it also works my own computer web service debug mode but when i publish it to server, it isnt working. i gave all privilages to youtube-dl.exe and also its directory and also i closed firewall. nothing work

**Comment by dstftw** [comment]
Then it even more likely to be a problem with account rights. I'm closing this issues since it does not look like an issue in youtube-dl.

**Comment by codaman** [comment]
may be iis cant  access certificate store .i dont know how to grant iis to access. why 2015.10.18 there is no problem

**Comment by yan12125** [comment]
Version 2015.10.18 is built with Python 2.7.8, which does not check certificates at all.

Please **DO NOT** spam your problem on other issues anymore. They're totally different issues.

The following stackoverflow post may help you: http://stackoverflow.com/questions/33264502/windowserror-error-5-access-is-denied-using-urllib2. Your problem is outside the scope of youtube-dl.

**Comment by trandinhnam** [comment]
any updates package for this issue?

**Comment by codaman** [comment]
no need to update 
http://stackoverflow.com/questions/33264502/windowserror-error-5-access-is-denied-using-urllib2
this solution solve problem

**Comment by trandinhnam** [comment]
So, how to solve problem? Do you mean I download source code and modify it then build an other version? Because when i check on server, the issue still exist with the 09/01/2016 package? On the server, i cannot run package with administrator role. Everything is ok on my machine, but it's not working on web service server?

**Comment by yan12125** [comment]
After some investigation I believe it's actually a Python bug. See #7951 and http://bugs.python.org/issue25939 for more information. A possible solution can be running youtube-dl outside the web server.

**Comment by trandinhnam** [comment]
Request the IT host update new python for windows is ok?

**Comment by yan12125** [comment]
This bug exists in latest Python 2.7.11 and 3.5.1, so it won't help if I'm right.

**Comment by yan12125** [comment]
Another option is to build your own ```youtube-dl.exe``` with Python 2.7.8. It's simpler: 

1. Installing [Python 2.7.8](https://www.python.org/downloads/release/python-278/) and [py2exe for Python 2](http://sourceforge.net/projects/py2exe/files/py2exe/0.6.9/)
2. Download the [latest source tarball of youtube-dl](https://yt-dl.org/latest/youtube-dl.tar.gz) and extract it
3. Run the following commands:
```
C:\>cd youtube-dl
C:\youtube-dl>python.exe setup.py py2exe
```
Then there will be ```youtube-dl.exe```.

**Comment by trandinhnam** [comment]
Thank yan12125. Now it is working. 
But if source code update some features which use the library of Python 3x, this workaround may have issues.

**Comment by yan12125** [comment]
Don't worry. We'll support Python 2.7 for a long time. See #2396 for more information.
