### ISSUE TITLE
--get-url prints the requested URL twice

### ISSUE THREAD

**Issue by dexpl** [rg3/youtube-dl#7456]
`youtube-dl --get-url any_supported_url` prints the URL twice. For example,

[debug] System config: [u'--prefer-free-formats']
[debug] User config: [u'--continue', u'--ignore-errors', u'--netrc']
[debug] Command-line args: [u'--verbose', u'--get-url', u'http://youtu.be/5DPWNRsdW5k']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.16
[debug] Python version 2.7.10 - Linux-4.2.5-300.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: parsing .netrc: No authenticators for youtube (None, line None)
https://r3---sn-8ph2xajvh-8v1e.googlevideo.com/videoplayback?id=e433d6351b1d5b99&itag=134&source=youtube&requiressl=yes&pl=24&mv=m&ms=au&pcm2cms=yes&mn=sn-8ph2xajvh-8v1e&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=14495389&lmt=1387281102066917&dur=477.800&sver=3&mt=1447245197&signature=853B143FA1E9C8E0473310C3BDCC16FA25DD4CF9.3AB6D488A6F27F0C27BEE7E118E926AF43617A5B&key=dg_yt0&upn=l7S_VfvwoAs&fexp=9408710,9413208,9414764,9415516,9416126,9416179,9417298,9417683,9417707,9418810,9420453,9420539,9422454,9422596,9422618,9423662,9423667,9423793,9424306&ip=195.46.187.179&ipbits=0&expire=1447266927&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mv,ms,pcm2cms,mn,mm,ratebypass,mime,gir,clen,lmt,dur
https://r3---sn-8ph2xajvh-8v1e.googlevideo.com/videoplayback?id=e433d6351b1d5b99&itag=141&source=youtube&requiressl=yes&pl=24&mv=m&ms=au&pcm2cms=yes&mn=sn-8ph2xajvh-8v1e&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=15241173&lmt=1387281094758836&dur=478.029&sver=3&mt=1447245197&signature=10321439D83B7CC06351BDBDC11B7D90EABB88B2.1A09CF2897FD9DA3F0C103E9838BDDB2AEB72D80&key=dg_yt0&upn=l7S_VfvwoAs&fexp=9408710,9413208,9414764,9415516,9416126,9416179,9417298,9417683,9417707,9418810,9420453,9420539,9422454,9422596,9422618,9423662,9423667,9423793,9424306&ip=195.46.187.179&ipbits=0&expire=1447266927&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mv,ms,pcm2cms,mn,mm,ratebypass,mime,gir,clen,lmt,dur

while it was expected to print

https://r3---sn-8ph2xajvh-8v1e.googlevideo.com/videoplayback?id=e433d6351b1d5b99&itag=141&source=youtube&requiressl=yes&pl=24&mv=m&ms=au&pcm2cms=yes&mn=sn-8ph2xajvh-8v1e&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=15241173&lmt=1387281094758836&dur=478.029&sver=3&mt=1447245197&signature=10321439D83B7CC06351BDBDC11B7D90EABB88B2.1A09CF2897FD9DA3F0C103E9838BDDB2AEB72D80&key=dg_yt0&upn=l7S_VfvwoAs&fexp=9408710,9413208,9414764,9415516,9416126,9416179,9417298,9417683,9417707,9418810,9420453,9420539,9422454,9422596,9422618,9423662,9423667,9423793,9424306&ip=195.46.187.179&ipbits=0&expire=1447266927&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mv,ms,pcm2cms,mn,mm,ratebypass,mime,gir,clen,lmt,dur

only once

**Comment by dexpl** [comment]
Tested on 2015.11.10 with the same result

**Comment by dstftw** [comment]
This is expected behavior since by default youtube-dl prefers DASH `bestvideo+bestaudio` over `best` when not format selection is explicitly defined and ffmpeg/avconv is installed. So the first URL is for `bestvideo` and the second is for `bestaudio correspondingly`. If you want single file media to be preferred use `-f best` however you'll get worse quality in most cases since usually best qualitiy is served only via DASH formats.

**Comment by dexpl** [comment]
Thank you dstftw, '-f best' does exactly what I need.
