### ISSUE TITLE
Cannot idetify player "[...]/base.js"

### ISSUE THREAD

**Issue by Lesik** [rg3/youtube-dl#7457]
```
    The Prodigy - Out of Space [04:59]
                                                                                                                                                                              [1/11>
ERROR: Signature extraction failed: Traceback (most recent call last):                                                                                                                   ]   
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://s.ytimg.com/yts/jsbin/player-en_US-vflpe0o9N/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://s.ytimg.com/yts/jsbin/player-en_US-vflpe0o9N/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 0_7rmSwqwIc; webm 128k; 3 Mb; 00:00:39 [13%]  [=================>                                                                                                                       ]   
```

Doing as requested ("please report this issue on https://yt-dl.org/bug").

## What the problem is
This message appears, music plays nonetheless, player interface is distorted.
## How it could be fixed
Identify the player correctly? No idea. I'm using the newest version (0.2.5) with mpv.
## How your proposed solution would look like
?
## Reproductible?
Yes

Edit: The output looks distorted on Github, so I pasted it here: http://hastebin.com/exoloyaxed.coffee

**Comment by yan12125** [comment]
Thanks for the detailed report. It's actually already fixed in the latest version (2015.11.10). Please follow [update instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) to update your copy.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by Lesik** [comment]
Well 20151110 was yesterday, so there's pretty much no way I could've foreseen that this has already been fixed. ;)

On an unrelated note, if I installed mpsyt through pip, I can not use pip to update to 20151110 because it is on git, and not a release, right? I have to follow the "manual installation instructions".

**Comment by Lesik** [comment]
I just now realized that I'm in the wrong repository. I experienced this bug while using `mps-youtube`, which uses `youtube-dl` as backend. This is why the version number is off.
