### ISSUE TITLE
Upgrade brew tap 

### ISSUE THREAD

**Issue by droidekas** [rg3/youtube-dl#7458]
I face the same issue as  #7448 ,however I cannot update since brew has an older version of the package.Can that be updated?

**Comment by dstftw** [comment]
Even thought we don't manage homebrew it should be [up to date](https://github.com/Homebrew/homebrew/pull/45863). Alternatively read [our FAQ](https://yt-dl.org/update) on another ways to update.

**Comment by jaimeMF** [comment]
Homebrew [already has the last version](https://github.com/Homebrew/homebrew/blob/84bdd686010be37062df92b088877f616ab5e109/Library/Formula/youtube-dl.rb#L7), you may need to run `brew update` to update the formula.

Also: we aren't responsible of updating the version in the different package repositories, you should directly ask them (in the case of Homebrew, they encourage the users to submit the updates themselves and they quickly accept them).

**Comment by droidekas** [comment]
Ah,my bad.I kept running `brew upgrade youtube-dl` without `brew update`.  Thank You!
