### ISSUE TITLE
ExtractorError: Cannot identify player @ YouTube

### ISSUE THREAD

**Issue by ShadowCat8** [rg3/youtube-dl#7477]
Greetings,

I had youtube-dl fail on a download from YouTube and it told me to let you know.  I am running version 2015.04.03 on Gentoo with kernel version 3.10.25 and Python 2.7 as the active python profile.

The verbose output is as follows:

    tech8 /opt/pub/media/vids/U2bDL $ youtube-dl --verbose https://www.youtube.com/watch?v=rpD-yf_vHYA
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=rpD-yf_vHYA']
    WARNING: No ssl certificates were loaded, urls that use https won't work
    [debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
    [debug] youtube-dl version 2015.04.03-gentoo_no_offensive_sites
    [debug] Python version 2.7.9 - Linux-3.10.25-gentoo-ws-20140617-01-x86_64-Intel-R-_Core-TM-2_Quad_CPU_Q6700_@_2.66GHz-with-gentoo-2.2
    [debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
    [debug] Proxy map: {}
    [youtube] rpD-yf_vHYA: Downloading webpage
    [youtube] rpD-yf_vHYA: Extracting video information
    WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
    [youtube] {43} signature length 40.42, html5 player None
    ERROR: Signature extraction failed: Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 638, in _decrypt_signature
        video_id, player_url, s
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 530, in _extract_signature_function
        raise ExtractorError('Cannot identify player %r' % player_url)
    ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl5u6mls/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
     (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl5u6mls/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 638, in _decrypt_signature
        video_id, player_url, s
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 530, in _extract_signature_function
        raise ExtractorError('Cannot identify player %r' % player_url)
    ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl5u6mls/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 651, in extract_info
        ie_result = ie.extract(url)
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 275, in extract
        return self._real_extract(url)
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1076, in _real_extract
        encrypted_sig, video_id, player_url, age_gate)
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 648, in _decrypt_signature
        'Signature extraction failed: ' + tb, cause=e)
    ExtractorError: Signature extraction failed: Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 638, in _decrypt_signature
        video_id, player_url, s
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 530, in _extract_signature_function
        raise ExtractorError('Cannot identify player %r' % player_url)
    ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl5u6mls/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
     (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl5u6mls/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

    tech8 /opt/pub/media/vids/U2bDL $

I hope this helps.  If you need more info, let me know.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by ShadowCat8** [comment]
Thank you for your prompt response.  

Apparently neither the 2015.11.02 or 2015.11.10 versions had been fully tested by the Gentoo devs to be considered stable, so I had to keyword it to get it to install/update.  Got that done and it is working as expected.

Thanks again and keep up the good work.
