### ISSUE TITLE
Going fullscreen makes video darker

### ISSUE THREAD

**Issue by CrisBRM** [rg3/youtube-dl#7481]
Not sure if this is an mpv issue, however, whenever I go fullscreen, the video becomes significantly darker. This is not the case with 2015.04.03 (the 'stable' version on the gentoo repository), only happens with 2015.11.02 and 2015.11.10 (the other 2 versions there).

https://www.youtube.com/watch?v=q858mp9M2wQ

**Comment by dstftw** [comment]
That's unrelated to youtube-dl.

**Comment by CrisBRM** [comment]
The only thing that changed in between tests was the youtube-dl version, but alright, I'll post on mpv's bug tracker.
