### ISSUE TITLE
Export HTML5 <video> tags?

### ISSUE THREAD

**Issue by edent** [rg3/youtube-dl#7486]
When exporting a video, is it possible to auto-generate an HTML5 `<video>` snippet which includes the thumbnail, codecs, etc?

I was thinking something like
```
<video poster="thumbnail.jpg" >
  <source src="file.mp4" type="video/mp4; codecs=mp4a.40.2, avc1.42001E">
  <source src="file.webm" type="video/webm; codecs=vorbis, vp8.0">
  <track kind="subtitles" src="file.srt">
</video>
```

**Comment by jaimeMF** [comment]
I thinkt that's out of scope of youtube-dl, use the `--write-info-json` or `--dump-json` and write a script that process the json dict and creates the snippet.
