### ISSUE TITLE
'youtube-dl' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by idsharif** [rg3/youtube-dl#749]
I am a newbie. I think this is a simple problem too. But I need help on this. While using edx-downloader I'm receiving this error. How can I fix this. I've installed youtube-dl.
![problem](https://f.cloud.github.com/assets/2216621/293567/5a68e41c-9383-11e2-9506-c2685c91c1fa.jpg)
Thanks in advance.

**Comment by SubhashPeshwa** [comment]
@a58221 , I am getting the same error. I tried configuring PATH and PYTHONPATH variables in system properties (running Windows 7), but nothing seems to be working. Could you elaborate on your fix? Thanks.

**Comment by a58221** [comment]
I don't remember that much. But now you can use youtube-dl.exe. Then you won't face any issues.

http://youtube-dl.org/latest/youtube-dl.exe

**Comment by turbolego** [comment]
I still get the 'youtube-dl' is not recognized as an internal or external command,
operable program or batch file.' error after running the "youtube-dl.exe" file.

**Comment by jjayman27** [comment]
Facing the same problem in youtube-dl :(

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30950
