### ISSUE TITLE
youtube-dl does not recognize 720p stream from CBS.com

### ISSUE THREAD

**Issue by syncretic** [rg3/youtube-dl#7490]
For some reason when I use youtube-dl to download from CBS, the highest resolution it sees is 480p. However when I use Atresdownloader to download CBS shows, it shows 540p & 720p streams as well. I am currently using Atresdownloader to download my CBS shows in 720p, but I would much rather use youtube-dl instead. Why doesn't youtube-dl see the higher quality streams?

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by syncretic** [comment]
http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/cnW91SJbCULkwjE1N5LmCJHwtbwb0NDN/the-late-show-11-12-2015-jennifer-connelly-judd-apatow-the-internet-/

**Comment by dstftw** [comment]
I don't see anything higher than 480p served via theplatform. Post the output of `ffmpeg -i 720p_file_name`.

**Comment by syncretic** [comment]
http://pastebin.com/N0H9vFjJ

Also, I was looking in the files leftover from Adownloader and this was in a .m3u file:

http://pastebin.com/Wjjv5E2y
