### ISSUE TITLE
Safaribooksonline - ERROR: brightcove said: This player is not enabled for access without key.

### ISSUE THREAD

**Issue by jeromeza** [rg3/youtube-dl#7491]
I'm seeing this error on the latest version I just grabbed.

Trying to grab off Safaribooksonline.com and I see:

ERROR: brightcove said: This player is not enabled for access without key.

Any ideas?

Running:
youtube-dl --version
2015.11.13

Thanks,

**Comment by jaimeMF** [comment]
As [explained in the bug reporting instructions](https://github.com/rg3/youtube-dl/blob/edeb3e7cb1ab2d82ff7c712a7cc1e338a9dcd8f8/README.md#bugs) post the url you have problems with and the full output you get when running `youtube-dl --verbose THE_URL`.

**Comment by jeromeza** [comment]
As requested:

youtube-dl --autonumber-size 3 -o "%(autonumber)s - %(title)s.%(ext)s" https://www.safaribooksonline.com/library/view/red-hat-certified/9780133929171/ --username MYUSER --password MYPASSWORD --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--autonumber-size', u'3', u'-o', u'%(autonumber)s - %(title)s.%(ext)s', u'https://www.safaribooksonline.com/library/view/red-hat-certified/9780133929171/', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.13
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[safari:course] Downloading login form
[safari:course] Logging in MYUSER
[safari:course] Login successful
[safari:course] 9780133929171: Downloading course JSON
[download] Downloading playlist: Red Hat Certified Engineer (RHCE) Complete Video Course (Video Training)
[safari:course] playlist Red Hat Certified Engineer (RHCE) Complete Video Course (Video Training): Collected 172 video ids (downloading 172 of them)
[download] Downloading video 1 of 172
[safari] part00: Downloading webpage
[Brightcove] 3845446708001: Downloading webpage
ERROR: brightcove said: This player is not enabled for access without key.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 237, in _real_extract
    videoPlayer[0], query_str, query, referer=referer)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 261, in _get_video_info
    'brightcove said: %s' % error_msg, expected=True)
ExtractorError: brightcove said: This player is not enabled for access without key.

**Comment by jeromeza** [comment]
Jeromes-Air:~ jerome$ youtube-dl --version
2015.11.24

Still the same thing. Anything I can do assist?

**Comment by addersuk** [comment]
Looking into this issue it appears they have switched provider and are now using Kaltura instead of Brightcove, so when it tries to download via Brightcove the above error is returned.

**Comment by benklaasen** [comment]
It's an odd one, because a valid BrightCove object is returned. I don't understand the code well enough to fix this, but if there's anything I can do to help, please shout. I'd love to see a fix for this.

**Comment by gabrielcnr** [comment]
I am having the same problem and I got to the same conclusion as @addersuk. I tried to workaround the problem and make it use Kaltura extractor. But the full URL for the video is only available at the DOM after a bunch of execution of JavaScript and I couldn't make it work. Is anyone looking at this?

**Comment by remitamine** [comment]
it's simple to make it work with free video but i don't know if the same method will work for payed video.
in the video page there is this element:
```html
<div id="sbo-rt-content" data-reference-id="9780133929171-Introduction" data-partner-id="1926081" data-ui-id="29375172">
```
the information the element will be mapped to information used by kaltura:
partner-id -> wid(by adding _ at the beginning)
ui-id -> uiconf_id
reference-id -> referenceId
then you have to request the emebd web page using this information:
https://cdnapisec.kaltura.com/html5/html5lib/v2.37.1/mwEmbedFrame.php?wid=_1926081&uiconf_id=29375172&flashvars[referenceId]=9780133929171-Introduction
the web page contain all the information needed by the kaltura extractor(baseentry and flavorAsset).
if someone that have an account can confirm if this also work for payed videos.

**Comment by benklaasen** [comment]
Hi @remitamine - is your change checked in? I have an account, I'll test it now. Thank you very much for looking into this. More info to follow...

**Comment by remitamine** [comment]
no, i just read the js code and extract the method and i didn't work on the code,  because most of the videos work only with accout so it's not worth to add the code to support only few free videos.

**Comment by benklaasen** [comment]
No joy, unfortunately:

```
 $ youtube-dl --username redacted --password redacted "https://www.safaribooksonline.com/library/view/redacted/redacted/"
[safari:course] Downloading login form
[safari:course] Logging in as redacted
[safari:course] Login successful
[safari:course] 2957021859732: Downloading course JSON
[download] Downloading playlist: <Playlist Name>
[safari:course] playlist <Playlist Name>: Collected 24 video ids (downloading 24 of them)
[download] Downloading video 1 of 24
[safari] part00: Downloading webpage
[brightcove:legacy] 5076129579452: Downloading webpage
ERROR: brightcove said: This player is not enabled for access without key.
```

**Comment by remitamine** [comment]
if you or another one that has access:
- know how to code in python, than open a PR to fix the extraction.
- can provide an account to test with.
or:
- i can send the code that will work with free videos in a branch and check if it work with videos accessible with account but i can't fix it if it's didn't work(i didn't start working on it yet).

**Comment by jeromeza** [comment]
Hi,

* an provide an account to test with
- They provide a free trial. If you sign up you get full access, so that 
should solve the account requirement.

Thanks for the feedback!

**Comment by remitamine** [comment]
- the method i point at before should not work directly for payed videos as they use Kaltura session protected videos.
from the js code:
```
"isSessionRestricted":true
```
https://blog.kaltura.com/create-ks-protected-videos-with-free-preview/
> They provide a free trial. If you sign up you get full access, so that should solve the account requirement.

adding support for the site in youtube-dl is not a reason to signup for trial with fake identity.
