### ISSUE TITLE
Twitter - ERROR: Unable to extract data player config

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#7496]
URL:   https://twitter.com/DavidClinchNews/status/665289828897005568

>youtube-dl.py -v "https://twitter.com/DavidClinchNews/status/665289828897005568"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://twitter.com/DavidClinchNews/status/665289828897005568']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.13
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[twitter] 665289828897005568: Downloading webpage
[twitter:card] 665289828897005568: Downloading webpage
ERROR: Unable to extract data player config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure
with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 290, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\twitter.py", line 81, in _real_extract
    r'data-player-config="([^"]+)"', webpage, 'data player config'),
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract data player config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
l youtube-dl with the --verbose flag and include its complete output.

Thanks as always...
Ringo

**Comment by yan12125** [comment]
Thanks for the report. Tweets with Vine.co embeds will be supported in the next version.

**Comment by Fironet** [comment]
I've experienced this today on Twitter, using the latest version as of writing (2016-08-12).

Verbose output:

    PS D:\> youtube-dl -F https://twitter.com/hoochmooch/status/763385089518477313
    [twitter] 763385089518477313: Downloading webpage
    [twitter:card] 763385089518477313: Downloading webpage
    ERROR: Unable to extract data player config; please report this issue on https://yt-dl.org/bug . Make sure you are using
     the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its
    complete output.
    PS D:\> youtube-dl -F https://twitter.com/hoochmooch/status/763385089518477313 --verbose
    [debug] System config: []
    [debug] User config: ['-o', 'M:\\Videos\\%(title)s.%(ext)s', '--restrict-filenames', '--console-title']
    [debug] Command-line args: ['-F', 'https://twitter.com/hoochmooch/status/763385089518477313', '--verbose']
    [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
    [debug] youtube-dl version 2016.08.12
    [debug] Python version 3.4.4 - Windows-8.1-6.3.9600
    [debug] exe versions: ffmpeg N-80801-gc0cb53c, ffprobe N-80801-gc0cb53c, rtmpdump 2.4
    [debug] Proxy map: {}
    [twitter] 763385089518477313: Downloading webpage
    [twitter:card] 763385089518477313: Downloading webpage
    ERROR: Unable to extract data player config; please report this issue on https://yt-dl.org/bug . Make sure you are using
     the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its
    complete output.
    Traceback (most recent call last):
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzyhyyrce\build\youtube_dl\YoutubeDL.py", line 691,
    in extract_info
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzyhyyrce\build\youtube_dl\extractor\common.py", lin
    e 347, in extract
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzyhyyrce\build\youtube_dl\extractor\twitter.py", li
    ne 103, in _real_extract
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzyhyyrce\build\youtube_dl\extractor\common.py", lin
    e 659, in _html_search_regex
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzyhyyrce\build\youtube_dl\extractor\common.py", lin
    e 650, in _search_regex
    youtube_dl.utils.RegexNotFoundError: Unable to extract data player config; please report this issue on https://yt-dl.org
    /bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the -
