### ISSUE TITLE
periscope: add support for urls containing username instead of "w"

### ISSUE THREAD

**Issue by Crihub** [rg3/youtube-dl#7503]
At the moment this kind of url is supported:

  https://www.periscope.tv/w/STREAM-ID

But if you browse the periscope website, you sometimes find urls like:

  https://www.periscope.tv/USERNAME/STREAM-ID

i.e. with the periscope user's username replacing the "w" character.

This second kind of url works fine in web browsers, but it's not accepted by youtube-dl:

  ERROR: Unsupported URL

I'm attaching a patch for youtube_dl/extractor/periscope.py to allow this kind of urls.
The regexp I added requires at least two characters (that's the only requirement about periscope usernames I found on help.periscope.tv), and excludes the same characters forbidden in stream id's.

[periscope.py.txt](https://github.com/rg3/youtube-dl/files/34681/periscope.py.txt)

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).
We only accept PRs.

**Comment by dstftw** [comment]
Moreover this patch breaks https://www.periscope.tv/w/STREAM-ID URLs.
