### ISSUE TITLE
Choosing Resolution in Dramafever Playlist

### ISSUE THREAD

**Issue by Xonshiz** [rg3/youtube-dl#7507]
I've been trying to download videos from 'DramaFever' playlist. It works fine, but, I want to download all the videos in 1280x720 resolution.. with the single video I can download what I want. But, I can't seem to specify it in the playlist..

here's the show I've been trying to download :- http://www.dramafever.com/drama/4763/Twenty_Again/

**Comment by dstftw** [comment]
`-f best[width=1280][height=720]`.
