### ISSUE TITLE
ERROR: YouTube said: Invalid parameters. 

### ISSUE THREAD

**Issue by kid1412-net** [rg3/youtube-dl#751]
Thanks for coding such a great video download program. I tried to download this video but it's not working with latest version of youtube-dl.

http://www.youtube.com/watch?v=1XSa-u2ZgRc

Could you please fix this error?

Best Regards,
Hai

**Comment by clueserver** [comment]
youtube-dl -vt "http://www.youtube.com/watch?v=w1OBOhBVPF"
[debug] System config: ['-i', '--geo-bypass', '--playlist-reverse', '-o', '~/YouTubeDL/%(uploader)s/%(title)s-%(width)s-%(height)s-%(vcodec)s.%(ext)s', '--all-subs', '-u', 'PRIVATE', '-p', 'PRIVATE', '--audio-format', 'best', '--format', 'best', '--download-archive', '~/YouTubeDL/archive-list', '--write-description']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vt', 'http://www.youtube.com/watch?v=w1OBOhBVPF']
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: using output template conflicts with using title, video ID or auto number

**Comment by clueserver** [comment]
The previous error is caused by a video that is blocked in your current country.
