### ISSUE TITLE
Write Thumbnail to Downloaded File

### ISSUE THREAD

**Issue by alloxcwapx0u** [rg3/youtube-dl#7512]
Is it possible to download and write the thumbnail to the downloaded file's metadata? I can only figure out how to download the thumbnails but not write them to the downloaded video/audio file. If it's not possible, can you please add the functionality to youtube-dl? Thanks

**Comment by yan12125** [comment]
In [post-processing options](https://github.com/rg3/youtube-dl/blob/master/README.md#post-processing-options) there's ```--embed-thumbnail```. Note that the embedded thumbnail in MP3 files is not supported by Windows Media Player yet. (#5957)

**Comment by alloxcwapx0u** [comment]
Yes! But are there options that I can specify for the thumbnail such as the width and height? What parameters does FFmpeg use to do this? The output seems to be different than the output from this example: https://trac.ffmpeg.org/ticket/2221. That example also seems to be compatible with Windows Media Player.

**Comment by yan12125** [comment]
Which version of Windows Media Player are you using?

Also you may need to specify additional parameters to ffmpeg via ```--postprocessor-args``` for thumbnail dimensions. youtube-dl can't handle every possible cases.

**Comment by alloxcwapx0u** [comment]
It seems like the main difference from https://trac.ffmpeg.org/ticket/2221 and what's in embedthumbnail.py is that embedthumbnail.py doesn't have the option: id3v2_version 3.
