### ISSUE TITLE
DPlay Nordic

### ISSUE THREAD

**Issue by MrBrax** [rg3/youtube-dl#7515]
Discovery united all their channels on one domain in October, and e.g. kanal5play does not work anymore.
The new site is riddled with sessions, cookies, and stream requests, which is a pain to handle.

I've tried making a downloader myself, but i'm just not good enough at it to make it work.

**Comment by jaimeMF** [comment]
[Post an example URL](https://github.com/rg3/youtube-dl/blob/edeb3e7cb1ab2d82ff7c712a7cc1e338a9dcd8f8/README.md#bugs).

**Comment by MrBrax** [comment]
Sorry, missed that.

Base URL's do not contain any video id's:
http://www.dplay.se/nugammalt-77-handelser-som-format-sverige/season-1-svensken-lar-sig-njuta-av-livet/

The ID is on the page in multiple locations. It then does a GET request to here:
https://secure.dplay.se/secure/api/v2/user/authorization/stream/ID?stream_type=hls
Where it returns the stream URL. The cookies dsc-geo and \_alid_ need their contents set from the HLS playlist request.

**Comment by MrBrax** [comment]
svtplay-dl apparently handles dplay already: https://github.com/spaam/svtplay-dl/blob/master/lib/svtplay_dl/service/dplay.py

I don't know about stealing code or whatever.

**Comment by jaimeMF** [comment]
> svtplay-dl apparently handles dplay already: https://github.com/spaam/svtplay-dl/blob/master/lib/svtplay_dl/service/dplay.py

> I don't know about stealing code or whatever.

Its MIT license is incompatible with the public domain license of youtube-dl, therefore it can't be copied (I'm not a lawyer, but I think you also can't inspect the code and then write your own version for youtube-dl).

**Comment by MrBrax** [comment]
Well the method has to be the same at least, so that can't really be avoided.

**Comment by jaimeMF** [comment]
I have added support. Since downloading the hds streams requires some cookies that I haven't figured out, I used the hsl stream instead.

**Comment by MrBrax** [comment]
The cookies required are:
dsc-geo: {"countryCode":"SE","expiry": (timestamp) }
_alid_: gotten from the m3u8 playlist manifest link, in the headers

**Comment by jaimeMF** [comment]
I can't get it to work, feel free to open a PR.

**Comment by MrBrax** [comment]
I probably confused the two. HLS should work anyway yeah?

**Comment by jaimeMF** [comment]
> I probably confused the two. HLS should work anyway yeah?

It works in the videos I have tested.
