### ISSUE TITLE
Vimeo Sync Issues

### ISSUE THREAD

**Issue by remlap** [rg3/youtube-dl#7520]
Vimeo videos are downloading out of sync using hls-native and seem to be a broken mp4, any way to fix this?

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by remlap** [comment]
youtube-dl https://vimeo.com/121856032 -f hls-4737

**Comment by dstftw** [comment]
Produced media plays with mpv without any issue. Slight corruption on fragment borders is known issue and there is an open issue for that already.

**Comment by remlap** [comment]
Anything I can do except for remuxing with a 300ms delay?
