### ISSUE TITLE
Pluralsight appears to be broken

### ISSUE THREAD

**Issue by tdobson** [rg3/youtube-dl#7523]
So if I do:

tim@picknmix:~/Videos$ youtube-dl --verbose --username=email@example.com --password=nevergonnagiveyouup http://www.pluralsight.com/courses/angularjs-get-started
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--username=email@example.com', u'--password=nevergonnagiveyouup', u'http://www.pluralsight.com/courses/angularjs-get-started']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.3 - Linux-3.2.0-4-686-pae-i686-with-debian-7.9
[debug] exe versions: avconv 0.8.17-6, avprobe 0.8.17-6, ffmpeg 0.8.17-6, ffprobe 0.8.17-6
[debug] Proxy map: {}
[pluralsight:course] angularjs-get-started: Downloading course JSON
[pluralsight:course] angularjs-get-started: Downloading course data JSON
[download] Downloading playlist: AngularJS: Get Started
[pluralsight:course] playlist AngularJS: Get Started: Collected 44 video ids (downloading 44 of them)
[download] Downloading video 1 of 44
[pluralsight] Downloading login page
[pluralsight] Logging in as email@example.com
[pluralsight] angularjs-get-started-m1-introduction-0: Downloading webpage
ERROR: Unable to extract modules; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 90, in _real_extract
    webpage, 'modules'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract modules; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

If I reference the video more directly, the URL isn't detected:
tim@picknmix:~/Videos$ youtube-dl --verbose --username=email@example.com --password=nevergonnagiveyouup "https://app.pluralsight.com/training/player?course=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-introduction&clip=0&mode=live"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--username=email@example.com', u'--password=nevergonnagiveyouup', u'https://app.pluralsight.com/training/player?course=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-introduction&clip=0&mode=live']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.3 - Linux-3.2.0-4-686-pae-i686-with-debian-7.9
[debug] exe versions: avconv 0.8.17-6, avprobe 0.8.17-6, ffmpeg 0.8.17-6, ffprobe 0.8.17-6
[debug] Proxy map: {}
[generic] player?course=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-introduction&clip=0&mode=live: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player?course=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-introduction&clip=0&mode=live: Downloading webpage
[generic] player?course=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-introduction&clip=0&mode=live: Extracting information
[debug] Invoking downloader on u'https://app.pluralsight.com/training/player?course=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-introduction&clip=0&mode=live'
[download] Destination: Pluralsight Player-playercourse=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-introduction&clip=0&mode=live.unknown_video
[download] 351.9% of 21.04KiB at  6.21MiB/s ETA 00:00ERROR: content too short (expected 21546 bytes and served 75824)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1598, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1540, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 238, in real_download
    raise ContentTooShortError(byte_counter, int(data_len))

**Comment by robasta** [comment]
I am getting the error "no video formats found"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.pluralsight.com/courses/skeet-async', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.15
[debug] Python version 3.4.3 - Windows-8-6.2.9200`
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] skeet-async: Downloading course JSON
[pluralsight:course] skeet-async: Downloading course data JSON
[download] Downloading playlist: Asynchronous C# 5.0
[pluralsight:course] playlist Asynchronous C# 5.0: Collected 19 video ids (downloading 19 of them)
[download] Downloading video 1 of 19
[pluralsight] Downloading login page
[pluralsight] Logging in as bob@gmail.com
[pluralsight] skeet-async-m1-intro-0: Downloading webpage
[pluralsight] skeet-async-m1-intro-0: Downloading webm-high URL
WARNING: Unable to download webpage: HTTP Error 400: Bad Request
[pluralsight] skeet-async-m1-intro-0: Downloading mp4-low URL
WARNING: Unable to download webpage: HTTP Error 400: Bad Request
[pluralsight] skeet-async-m1-intro-0: Downloading mp4-medium URL
WARNING: Unable to download webpage: HTTP Error 400: Bad Request
[pluralsight] skeet-async-m1-intro-0: Downloading mp4-high URL
WARNING: Unable to download webpage: HTTP Error 400: Bad Request
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 290, in extract
    return self._real_extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\pluralsight.py", line 149, in _real_extract
    self._sort_formats(formats)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by CollinChaffin** [comment]
Looks like pluralsight changed all their links to APP.pluralsight.com.  Looking at the code I believe it parses for WWW.pluralsight.com or falls back to the generic extractor which of course fails.  Since they seem to ban accounts if you hit them like this too much, this should probably be fixed sooner rather than later before we all get ourselves banned. :)  Can the one line of regex in their extractor to allow for APP.pluralsight.com?

**Comment by CollinChaffin** [comment]
I created a pull request myself and proposed a fix to the code.  When I test against my test URLs, my new regex works properly.

**Comment by dstftw** [comment]
Pluralsight should work again in the next version of youtube-dl.

**Comment by tdobson** [comment]
Thanks for all your work and efforts - I really appreciate the time you've spent to try and get this working. :)

Should this have been fixed in 2015.11.24? It doesn't seem to have been for me. 

tdobson@tragicomix:~/Videos$ youtube-dl --version
2015.11.24

tdobson@tragicomix:~/Videos$ youtube-dl --username=username --password=pw http://app.pluralsight.com/courses/angularjs-get-started
[pluralsight:course] angularjs-get-started: Downloading course JSON
[pluralsight:course] angularjs-get-started: Downloading course data JSON
[download] Downloading playlist: AngularJS: Get Started
[pluralsight:course] playlist AngularJS: Get Started: Collected 44 video ids (downloading 44 of them)
[download] Downloading video 1 of 44
[pluralsight] Downloading login page
[pluralsight] Logging in as username
[pluralsight] angularjs-get-started-m1-introduction-0: Downloading webpage
[pluralsight] angularjs-get-started-m1-introduction-0: Downloading mp4-high URL
[pluralsight] angularjs-get-started-m1-introduction-0: Waiting for 3 seconds to avoid throttling
ERROR: An extractor error has occured. (caused by KeyError(u'clipName',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
tdobson@tragicomix:~/Videos$ youtube-dl --verbose --username=username --password=pw http://app.pluralsight.com/courses/angularjs-get-started
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--username=username', u'--password=pw', u'http://app.pluralsight.com/courses/angularjs-get-started']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.9
[debug] exe versions: avconv 0.8.17-6, avprobe 0.8.17-6, ffmpeg 0.8.17-6, ffprobe 0.8.17-6, rtmpdump 2.4
[debug] Proxy map: {}
[pluralsight:course] angularjs-get-started: Downloading course JSON
[pluralsight:course] angularjs-get-started: Downloading course data JSON
[download] Downloading playlist: AngularJS: Get Started
[pluralsight:course] playlist AngularJS: Get Started: Collected 44 video ids (downloading 44 of them)
[download] Downloading video 1 of 44
[pluralsight] Downloading login page
[pluralsight] Logging in as username
[pluralsight] angularjs-get-started-m1-introduction-0: Downloading webpage
[pluralsight] angularjs-get-started-m1-introduction-0: Downloading mp4-high URL
[pluralsight] angularjs-get-started-m1-introduction-0: Waiting for 5 seconds to avoid throttling
ERROR: An extractor error has occured. (caused by KeyError(u'clipName',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 219, in _real_extract
    'id': clip['clipName'],
KeyError: u'clipName'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 296, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'clipName',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

tdobson@tragicomix:~/Videos$ youtube-dl --verbose --username=username --password=pw http://app.pluralsight.com/courses/angularjs-get-started
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--username=username', u'--password=pw', u'http://app.pluralsight.com/courses/angularjs-get-started']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.9
[debug] exe versions: avconv 0.8.17-6, avprobe 0.8.17-6, ffmpeg 0.8.17-6, ffprobe 0.8.17-6, rtmpdump 2.4
[debug] Proxy map: {}
[pluralsight:course] angularjs-get-started: Downloading course JSON
[pluralsight:course] angularjs-get-started: Downloading course data JSON
[download] Downloading playlist: AngularJS: Get Started
[pluralsight:course] playlist AngularJS: Get Started: Collected 44 video ids (downloading 44 of them)
[download] Downloading video 1 of 44
[pluralsight] Downloading login page
[pluralsight] Logging in as username
[pluralsight] angularjs-get-started-m1-introduction-0: Downloading webpage
[pluralsight] angularjs-get-started-m1-introduction-0: Downloading mp4-high URL
[pluralsight] angularjs-get-started-m1-introduction-0: Waiting for 2 seconds to avoid throttling
ERROR: An extractor error has occured. (caused by KeyError(u'clipName',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 219, in _real_extract
    'id': clip['clipName'],
KeyError: u'clipName'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 296, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'clipName',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

tdobson@tragicomix:~/Videos$ youtube-dl --verbose --username=username --password=pw https://app.pluralsight.com/library/courses/angularjs-get-started/table-of-contents
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--username=username', u'--password=pw', u'https://app.pluralsight.com/library/courses/angularjs-get-started/table-of-contents']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.9
[debug] exe versions: avconv 0.8.17-6, avprobe 0.8.17-6, ffmpeg 0.8.17-6, ffprobe 0.8.17-6, rtmpdump 2.4
[debug] Proxy map: {}
[pluralsight:course] angularjs-get-started: Downloading course JSON
[pluralsight:course] angularjs-get-started: Downloading course data JSON
[download] Downloading playlist: AngularJS: Get Started
[pluralsight:course] playlist AngularJS: Get Started: Collected 44 video ids (downloading 44 of them)
[download] Downloading video 1 of 44
[pluralsight] Downloading login page
[pluralsight] Logging in as username
[pluralsight] angularjs-get-started-m1-introduction-0: Downloading webpage
[pluralsight] angularjs-get-started-m1-introduction-0: Downloading mp4-high URL
[pluralsight] angularjs-get-started-m1-introduction-0: Waiting for 4 seconds to avoid throttling
ERROR: An extractor error has occured. (caused by KeyError(u'clipName',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 219, in _real_extract
    'id': clip['clipName'],
KeyError: u'clipName'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 296, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'clipName',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

tdobson@tragicomix:~/Videos$ youtube-dl --verbose --username=username --password=pw https://app.pluralsight.com/training/player?course=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-introduction&clip=0&mode=live
[1] 31437
[2] 31438
[3] 31439
[4] 31440
[2]   Done                    author=scott-allen
[3]-  Done                    name=angularjs-get-started-m1-introduction
tdobson@tragicomix:~/Videos$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--username=username', u'--password=pw', u'https://app.pluralsight.com/training/player?course=angularjs-get-started']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.9
[debug] exe versions: avconv 0.8.17-6, avprobe 0.8.17-6, ffmpeg 0.8.17-6, ffprobe 0.8.17-6, rtmpdump 2.4
[debug] Proxy map: {}
[pluralsight] Downloading login page
[pluralsight] Logging in as username
ERROR: Invalid URL
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 101, in _real_extract
    raise ExtractorError('Invalid URL', expected=True)
ExtractorError: Invalid URL

**Comment by robasta** [comment]
I am using version 2015.11.21 on Windows and its working.
