### ISSUE TITLE
Python script for automated download-dl tasks

### ISSUE THREAD

**Issue by elsakuh** [rg3/youtube-dl#7524]
I am working hard on learning python and write scripts that help me to automate downloads.

At the moment I am not able to do so therfore I ask for some help to get started with
For an experienced programmer it may just some lines of code for me it is a wall banging my head at the moment
so if somebody wants to help I would be very thankful

What I try to achive is to fill a text file with either a channel user name or a Playlist url to feed download-dl
I made some bat template files with standard download-dl commandprompt:
youtube-dl -ciw ytuser:TheSkillPedia -o d:\youtube\TheSkillPedia\%%(playlist)s\%%(title)s.%%(ext)s
youtube-dl\youtube-dl -ciw URL-of-Playlist_of_xyz -o d:\youtube\xyz\%%(playlist)s\%%(title)s.%%(ext)s

that I fill manually by hand each time 
It would be really helpful to have a .py or .bat script that does analyze a simple text file formated like
user, Playlist_URL, Channel_URL
....
to run youtube-dl with parameters
youtube-dl\youtube-dl -ciw $Playlist_URL/&Channel_URL -o d:\youtube\$user\%%(playlist)s\%%(title)s.%%(ext)s

I kow this isn't a direct youtube-dl issue but hopfully someone can help
Thanks in advance

**Comment by dstftw** [comment]
Offtopic.
