### ISSUE TITLE
ExtractorError: Cannot identify player

### ISSUE THREAD

**Issue by hoijui** [rg3/youtube-dl#7526]
i imagine that youtube changed their JS scriptery...
seems to happen with all videos, since today (17. Nov. 2015) around 12:05 (GTM+1).
here one sample run with the error:

	$ youtube-dl --verbose https://www.youtube.com/watch?v=fXNk9pSnDuo
	[debug] System config: []
	[debug] User config: []
	[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=fXNk9pSnDuo']
	[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
	[debug] youtube-dl version 2015.10.06.2
	[debug] Python version 2.7.6
	[debug] exe versions: avconv 11.4, avprobe 11.4, rtmpdump 2.4
	[debug] Proxy map: {}
	[youtube] fXNk9pSnDuo: Downloading webpage
	[youtube] fXNk9pSnDuo: Downloading video info webpage
	[youtube] fXNk9pSnDuo: Extracting video information
	WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	[youtube] {43} signature length 41.40, html5 player None
	ERROR: Signature extraction failed: Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 771, in _decrypt_signature
	    video_id, player_url, s
	  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 663, in _extract_signature_function
	    raise ExtractorError('Cannot identify player %r' % player_url)
	ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflJENbn4/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflJENbn4/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 771, in _decrypt_signature
	    video_id, player_url, s
	  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 663, in _extract_signature_function
	    raise ExtractorError('Cannot identify player %r' % player_url)
	ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflJENbn4/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
	    ie_result = ie.extract(url)
	  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
	    return self._real_extract(url)
	  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1299, in _real_extract
	    encrypted_sig, video_id, player_url, age_gate)
	  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 781, in _decrypt_signature
	    'Signature extraction failed: ' + tb, cause=e)
	ExtractorError: Signature extraction failed: Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 771, in _decrypt_signature
	    video_id, player_url, s
	  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 663, in _extract_signature_function
	    raise ExtractorError('Cannot identify player %r' % player_url)
	ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflJENbn4/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflJENbn4/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
