### ISSUE TITLE
Request: lynda page

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#7529]
hi Dear
plz can you help me 
i want to add this lynda login page link in your lynda.py file 
https://www.lynda.com/portal/sip?org=melbourne.vic.gov.au

but i just replaced with login link and save file but its not working so if you making some changes here then i will change in my lynda file plz

**Comment by dstftw** [comment]
What are you trying to achieve in the first place? Clearly explain the intentions and [read bug reporting guide](https://github.com/rg3/youtube-dl#bugs).

**Comment by jaan143** [comment]
actually i want to add this lynda login url link instead of origina login url which you added so i just replaced this line but its not working so is that possible? if you check this login page and just text here with changes then i will replace all changes which you will suggest me
class LyndaBaseIE(InfoExtractor):
    _LOGIN_URL = https://www.lynda.com/portal/sip?org=melbourne.vic.gov.au'
    _ACCOUNT_CREDENTIALS_HINT = 'Use --username and --password options to provide lynda.com account credentials.'
    _NETRC_MACHINE = 'lynda'

**Comment by dstftw** [comment]
You did not answer the question why do you need this at all.

**Comment by jaan143** [comment]
because my lynda account is login in this url with unlimited access

**Comment by dstftw** [comment]
If it's organization login then it's not supported. You should use cookies instead.

**Comment by jaan143** [comment]
ok i will try cookies
thank you
