### ISSUE TITLE
--ignore-errors option doesn't work properly

### ISSUE THREAD

**Issue by akulovz** [rg3/youtube-dl#7535]
Hello.

Due to my weak internet connection `youtube-dl` rather often stops with errors like
```
ERROR: Unable to download webpage: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol> (caused by URLError(SSLError(8, '_ssl.c:510: EOF occurred in violation of protocol'),))
```
or
```
ERROR: content too short (expected 54847647 bytes and served 1977491)
```
or
```
ERROR: Unable to download webpage: <urlopen error Tunnel connection failed: 503 Service Unavailable> (caused by URLError(error('Tunnel connection failed: 503 Service Unavailable',),))
```
or things like that. Even I use `--ignore-errors` option.

So I have to wrap `youtube-dl` with bash. Say, I want to get a best quality video from Youtube:
`until [ -e *"$PREFIX"\.mp4 ] ; do youtube-dl "$PREFIX" ; done`

But a problem appears with batch file containing URLs or prefixes for download — I can't guess an extention for downloaded file so wrapper continues downloading an only file till I stop it.

Is there a way to fix it without branchyspreading shell-scripting?

**Comment by yan12125** [comment]
Just to clarify: ```--ignore-errors``` ignores individual video errors in _playlists_. Errors in single videos are still respected.
For your case, I guess using ```[ ! -e *.part ]``` is enough.

**Comment by akulovz** [comment]
Thank you for your reply, Yen.

But your code example won't work as when download starts, the ```*.part``` file doesn't exist yet.

So I have to wrap batch youtube downloads with this code:

```while read PREFIX QUALITY ; do until [ -e *"$PREFIX"\.mp4 ] ; do youtube-dl --recode-video mp4 http\:\/\/youtu\.be\/"$PREFIX" -f "$QUALITY" ; done ; done < tube```

where ```tube``` is two-fielded file with needed prefix in first field and quality in the second like this:

```
qsWl1--Niyg best
Med2XipHJJM best
rqSF_9Zf0n4 best
ogNr078W2HA worst
_k_pqFSVFxI worst
```

I guess this is the only way to make ```youtube-dl``` ignore **all** errors. :sigh:

Anyway, thank you for your work and great software!
