### ISSUE TITLE
Some video can download success, some video can't download

### ISSUE THREAD

**Issue by phukhanhlee** [rg3/youtube-dl#7537]
youtube-dl 'https://www.youtube.com/watch?v=YQHsXMglC9A' -> Hello Adele 

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 771, in _decrypt_signature

youtube-dl 'https://www.youtube.com/watch?v=Ue95eU4ZhTg' -> success

=> not all of youtube video can download mp3 ?

**Comment by phukhanhlee** [comment]
It's ok now for newest version. I will test more video. 
Thansk

**Comment by phihag** [comment]
In the future, please do post the entire output you get when you run youtube-dl with the `-v` option.

Can you explain to us how we can improve the error message? It should already contain the above information.
