### ISSUE TITLE
Unsupported URL: Chanel4.com

### ISSUE THREAD

**Issue by tarroyo8** [rg3/youtube-dl#7539]
youtube-dl.exe http://www.channel4.com/programmes/troy/on-demand/59867-001
[generic] 59867-001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 59867-001: Downloading webpage
[generic] 59867-001: Extracting information
ERROR: Unsupported URL: http://www.channel4.com/programmes/troy/on-demand/59867-
001

**Comment by jaimeMF** [comment]
Duplicate of #2050.
