### ISSUE TITLE
Help: getting error in lynda cookie

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#7540]
Dear plz plz help to figure out where i am making mistake 
i used these three commands with my cookies file but every command is downloading only free videos not paid here is command
youtube-dl --verbose --cookies /C/Dekstop/cookies.txt http://www.lynda.com/autocad-mac-tutorials/autocad-mac-2014-new-features/144563-2.html

youtube-dl --verbose --cookies /Dekstop/cookies.txt http://www.lynda.com/autocad-mac-tutorials/autocad-mac-2014-new-features/144563-2.html

youtube-dl --verbose --cookies /D/cookies.txt http://www.lynda.com/autocad-mac-tutorials/autocad-mac-2014-new-features/144563-2.html

here is error which i am facing
PS C:\Users\waqas\downloads> youtube-dl --verbose --cookies /D/cookies.txt http://www.lynda.com/autocad-mac-tutorials/au
tocad-mac-2014-new-features/144563-2.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--cookies', '/D/cookies.txt', 'http://www.lynda.com/autocad-mac-tutorials/autocad-mac-2014-new-features/144563-2.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.02
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] 144563: Downloading course JSON
[lynda:course] Logging out
WARNING: 10 videos are only available for members (or paid members) and will not be downloaded. Use --username and --password options to provide lynda.com account credentials.
[download] Downloading playlist: AutoCAD for Mac 2014 New Features
[lynda:course] playlist AutoCAD for Mac 2014 New Features: Collected 3 video ids (downloading 3 of them)
[download] Downloading video 1 of 3
[lynda] 154890: Downloading video JSON
[lynda] 154890: Checking 0-540 video format URL
[lynda] 154890: Checking 0-720 video format URL
[lynda] 154890: Checking 0-360 video format URL
[lynda] 154890: Checking 1-540 video format URL
[lynda] 154890: Checking 1-720 video format URL
[lynda] 154890: Checking 1-360 video format URL
[debug] Invoking downloader on 'http://files2.lynda.com/secure/courses/144563/VBR_MP4h264_main_HD720/144563_00_01_WX30_Welcome.mp4?c3.ri=3769905109169665877&hashval=1447856569_200519fb1fb300c77aa240c86056ab04'
[download] Welcome-154890.mp4 has already been downloaded
[download] 100% of 6.03MiB
[download] Downloading video 2 of 3
[lynda] 154891: Downloading video JSON
[lynda] 154891: Checking 0-540 video format URL
[lynda] 154891: Checking 0-720 video format URL
[lynda] 154891: Checking 0-360 video format URL
[lynda] 154891: Checking 1-540 video format URL
[lynda] 154891: Checking 1-720 video format URL
[lynda] 154891: Checking 1-360 video format URL
[debug] Invoking downloader on 'http://files2.lynda.com/secure/courses/144563/VBR_MP4h264_main_HD720/144563_00_02_MM30_Retina.mp4?c3.ri=3775253137697981691&hashval=1447856571_6f1971d6454538d4df300d43a8f7e366'
[download] Retina Display support-154891.mp4 has already been downloaded
[download] 100% of 4.25MiB
[download] Downloading video 3 of 3
[lynda] 154894: Downloading video JSON
[lynda] 154894: Checking 0-540 video format URL
[lynda] 154894: Checking 0-720 video format URL
[lynda] 154894: Checking 0-360 video format URL
[lynda] 154894: Checking 1-540 video format URL
[lynda] 154894: Checking 1-720 video format URL
[lynda] 154894: Checking 1-360 video format URL
[debug] Invoking downloader on 'http://files2.lynda.com/secure/courses/144563/VBR_MP4h264_main_HD720/144563_01_02_MM30_Package.mp4?c3.ri=3773845759998060799&hashval=1447856573_cbdcf5b53e657f2f01fba6bd5486bc5d'
[download] Packaging a drawing-154894.mp4 has already been downloaded
[download] 100% of 3.72MiB
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\youtube_dl\__init__.py", line 410, in main
    _real_main(argv)
  File "C:\Python34\lib\site-packages\youtube_dl\__init__.py", line 403, in _real_main
    retcode = 101
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 477, in __exit__
    self.cookiejar.save()
  File "C:\Python34\lib\http\cookiejar.py", line 2052, in save
    with open(filename, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/D/cookies.txt'
PS C:\Users\waqas\downloads>

but if i am using this command its download only free videos also but its showing 13 videos (All) but after downloaded 3 videos getting this error
PS C:\Users\waqas\downloads> youtube-dl --verbose --cookies C:\Users\waqas\Downloads\Programs\cookies.txt http://www.lyn
da.com/autocad-mac-tutorials/autocad-mac-2014-new-features/144563-2.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--cookies', 'C:\\Users\\waqas\\Downloads\\Programs\\cookies.txt', 'http://www.lynda.com/autocad-mac-tutorials/autocad-mac-2014-new-features/144563-2.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.02
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] 144563: Downloading course JSON
[lynda:course] Logging out
[download] Downloading playlist: AutoCAD for Mac 2014 New Features
[lynda:course] playlist AutoCAD for Mac 2014 New Features: Collected 13 video ids (downloading 13 of them)
[download] Downloading video 1 of 13
[lynda] 154890: Downloading video JSON
[lynda] 154890: Checking 1-360 video format URL
[lynda] 154890: Checking 1-540 video format URL
[lynda] 154890: Checking 1-720 video format URL
[lynda] 154890: Checking 0-360 video format URL
[lynda] 154890: Checking 0-540 video format URL
[lynda] 154890: Checking 0-720 video format URL
[debug] Invoking downloader on 'http://files3.lynda.com/secure/courses/144563/VBR_MP4h264_main_HD720/144563_00_01_WX30_Welcome.mp4?5obgMRoQ9jTLl4g8KBNyDZKaNR8lTVRnYPfPEBSg3CWfYZWoZPrsgCHhtmWwJ2whjZLjzV_SFX9Q7lgUMKlaGyF1qjz_JHVEvCDj7YrNi9F5EPmOn5van8J5r6WYnLCJ1qvo_30f-r4QQRH7Oqbs-fvAk0crmQLnORpFw57Qfj9ZtUYuFPEX2dnE8b6vlMk&c3.ri=3774127235512677633'
[download] Welcome-154890.mp4 has already been downloaded
[download] 100% of 6.03MiB
[download] Downloading video 2 of 13
[lynda] 154891: Downloading video JSON
[lynda] 154891: Checking 1-360 video format URL
[lynda] 154891: Checking 1-540 video format URL
[lynda] 154891: Checking 1-720 video format URL
[lynda] 154891: Checking 0-360 video format URL
[lynda] 154891: Checking 0-540 video format URL
[lynda] 154891: Checking 0-720 video format URL
[debug] Invoking downloader on 'http://files3.lynda.com/secure/courses/144563/VBR_MP4h264_main_HD720/144563_00_02_MM30_Retina.mp4?_EYDDJNF8BQtoWoJQXQ_gnwZmBIJcTzH6hz_CE24qSr62nDyZ_s_WuUA19XYhYP5PkJHkCRYLI1RK7m3iOZBqXHzF31yraic3AsGiMBLDfdjwSZp8zHutRX9xfcDHficxBbpcGNyO5elsqh9OohfZfLGStJ1KgzdPzqXIe4TevL3qkOkAXWpDadLZX7y4w&c3.ri=3770749534217261806'
[download] Retina Display support-154891.mp4 has already been downloaded
[download] 100% of 4.25MiB
[download] Downloading video 3 of 13
[lynda] 154893: Downloading video JSON
ERROR: lynda returned error: Session has expired
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 290, in extract
    return self._real_extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\lynda.py", line 123, in _real_extract
    'lynda returned error: %s' % video_json['Message'], expected=True)
youtube_dl.utils.ExtractorError: lynda returned error: Session has expired

PS C:\Users\waqas\downloads>

**Comment by jaan143** [comment]
closed please
file is updated 
sorry for inconvenience

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
