### ISSUE TITLE
Force youtube-dl to extract json file in diferrent signature length

### ISSUE THREAD

**Issue by pmesco** [rg3/youtube-dl#7541]
i want to force youtube-dl to extract json file in diferrent signature length.
for example:
js_en_US-vfltBCT02_40.40.json
js_en_US-vfltBCT02_41.42.json
and so on...

**Comment by jaimeMF** [comment]
We won't do that, youtube-dl will download the video from the url you give and I think that's all it needs to do.
The [code is available](https://github.com/rg3/youtube-dl/blob/50f84a9ae171233c08ada41e03f6555c5ed95236/youtube_dl/extractor/youtube.py), so feel free to modify it for your needs.
