### ISSUE TITLE
Site Request: NickJr.com

### ISSUE THREAD

**Issue by syncretic** [rg3/youtube-dl#7542]
Currently I use ffmpeg to download from NickJr.com, but I would rather use youtube-dl.

Example url: http://www.nickjr.com/little-charmers/videos/prince-not-so-charming-s1-ep101-full-episode/

Output:
E:\apps\youtube-dl>youtube-dl http://www.nickjr.com/little-charmers/videos/prince-not-so-charming-s1-ep101-full-episode/
[generic] prince-not-so-charming-s1-ep101-full-episode: Requesting header
WARNING: Falling back on generic information extractor.
[generic] prince-not-so-charming-s1-ep101-full-episode: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
[download] Destination: prince-not-so-charming-s1-ep101-full-episode-prince-not-so-charming-s1-ep101-full-episode.unknown_video
[download] 100% of 130.00KiB in 00:00

Here are some additional links:

http://media-utils.mtvnservices.com/services/MediaGenerator/mgid%3Aarc%3Avideo%3Anickjr.com%3A1da18f48-8b93-11e4-a3c3-0026b9414f30?acceptMethods=fms,hdn1,hds

http://media-utils.mtvnservices.com/services/MediaGenerator/mgid%3Aarc%3Avideo%3Anickjr.com%3A1dc5e6c2-8b93-11e4-a3c3-0026b9414f30?acceptMethods=fms,hdn1,hds

http://media-utils.mtvnservices.com/services/MediaGenerator/mgid%3Aarc%3Avideo%3Anickjr.com%3A1dccf188-8b93-11e4-a3c3-0026b9414f30?acceptMethods=fms,hdn1,hds

http://media-utils.mtvnservices.com/services/MediaGenerator/mgid%3Aarc%3Avideo%3Anickjr.com%3A1dd2419c-8b93-11e4-a3c3-0026b9414f30?acceptMethods=fms,hdn1,hds

**Comment by tnmannen** [comment]
I would like this as well..

**Comment by hdubb** [comment]
how do you use ffmpeg to download? what commands do you use?

**Comment by yan12125** [comment]
@hdubb This original video is no longer available. Do you have another working video?

**Comment by hdubb** [comment]
@yan12125 Here is a video that I would like to download

http://www.nickjr.com/paw-patrol/videos/pups-save-a-goldrush-s3-ep302-full-episode/

**Comment by yan12125** [comment]
It says ```Sorry, this video is unavailable from your location```. Which countries does it require?

**Comment by hdubb** [comment]
@yan12125 I am in the United States. Can you let me know what you are typing in the command prompt?

**Comment by yan12125** [comment]
Thanks. NickJr is not supported yet. I was trying to analyze the website and got the error message there.

**Comment by hdubb** [comment]
@yan12125 no problem. the website looks similar to Nick which is supported.

@syncretic said he could download from NickJr using ffmpeg so I was wondering what to type to download using that while youtube-dl adds support.

**Comment by yan12125** [comment]
nickjr.com will be supported in the next version.

From @syncretic's description, I guess he/she was also analyzing the website and got the final URL that ffmpeg accepts.

**Comment by syncretic** [comment]
I'm sorry I meant to say rtmpdump, not ffmpeg.

@hdubb That video is no longer available but if you take a video like this one:

http://www.nickjr.com/paw-patrol/videos/pups-save-apollo-s3-ep307-full-episode/

look at the source code and find "mgid"

mgid:arc:episode:nickjr.com:77ee3596-da02-11e5-8a89-0026b9414f30

Then put that at the end of this url

http://udat.mtvnservices.com/service1/dispatch.htm?feed=nick_arc_player_prime&mgid=

So you get this:

http://udat.mtvnservices.com/service1/dispatch.htm?feed=nick_arc_player_prime&mgid=mgid:arc:episode:nickjr.com:77ee3596-da02-11e5-8a89-0026b9414f30

Then search for "duration" and the episode will be in multiple segments, you have to download each segment and mux them together with mkvtoolnix.

**Comment by hdubb** [comment]
No problem but it is unnecessary now.

The newest update of youtube-dl supports nickjr.com downloads now.

**Comment by ShafferZee** [comment]
Forgive my my ignorance is there a special way for the command for be formatted for this to work with NickJr? I've tried many variants of using the "mgid" within different URLs but have been unsuccessful. Any help is much appreciated.

`[02:19:46]user@BRICK:~$ youtube-dl --version
2017.01.05
[02:19:57]user@BRICK:~$ youtube-dl www.nickjr.com/paw-patrol/videos/pups-bear-ly-save-danny-s3-ep316-full-episode/
WARNING: The url doesn't specify the protocol, trying with http
[nick.com] pups-bear-ly-save-danny-s3-ep316-full-episode: Downloading webpage
[nick.com] 4f9d55fc-3517-11e6-8a89-0026b9414f30: Downloading info
[nick.com] 4011734a-9954-42a4-ae9d-fc731cd0d0ee: Extracting information
[nick.com] 4011734a-9954-42a4-ae9d-fc731cd0d0ee: Downloading video urls
[nick.com] 6a459c80-58c3-4244-884a-1fd2f21da0bf: Extracting information
[nick.com] 6a459c80-58c3-4244-884a-1fd2f21da0bf: Downloading video urls
[nick.com] 398ac6d6-0820-436e-bbd8-b8719b9af129: Extracting information
[nick.com] 398ac6d6-0820-436e-bbd8-b8719b9af129: Downloading video urls
[nick.com] 4d7d5d26-cc9f-4019-90b4-42c1b5ff9e2d: Extracting information
[nick.com] 4d7d5d26-cc9f-4019-90b4-42c1b5ff9e2d: Downloading video urls
[nick.com] 5d4ba054-34e3-4120-87be-c9dd2412258c: Extracting information
[nick.com] 5d4ba054-34e3-4120-87be-c9dd2412258c: Downloading video urls
[nick.com] 36d52bd3-5b24-4ad6-a9c8-c04bfd11c76d: Extracting information
[nick.com] 36d52bd3-5b24-4ad6-a9c8-c04bfd11c76d: Downloading video urls
[download] Downloading playlist: PAW Patrol: "Pups Bear-ly Save Danny/Pups Save the Mayor's Tulips"
[nick.com] playlist PAW Patrol: "Pups Bear-ly Save Danny/Pups Save the Mayor's Tulips": Collected 6 video ids (downloading 6 of them)
[download] Downloading video 1 of 6
ERROR: unable to download video data: <urlopen error [Errno 110] Connection timed out>
[02:22:11]user@BRICK:~$
`

**Comment by yan12125** [comment]
@ShafferZee Can you watch videos on http://www.nickjr.com/paw-patrol/videos/pups-bear-ly-save-danny-s3-ep316-full-episode/? I got a black screen in Firefox.

**Comment by ShafferZee** [comment]
@yan12125 Works for me on Chrome, and after allowing flash on FF it works.

**Comment by yan12125** [comment]
Still no luck with Flash enabled. Anyway could you open a new issue? The error messages look quite different.

**Comment by RuneMagle** [comment]
It sucks :(

**Comment by yan12125** [comment]
Please open a new issue for fplive problems, thanks.
