### ISSUE TITLE
Failure to download m3u8 information from Vimeo

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#7543]
```
youtube-dl --ignore-config --verbose https://vimeo.com/129433664 https://vimeo.com/127444264 https://vimeo.com/119012293 
```

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-config', u'--verbose', u'https://vimeo.com/129433664', u'https://vimeo.com/127444264', u'https://vimeo.com/119012293']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.10 - Linux-4.2.0-18-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.2-1build1, ffprobe 2.7.2-1build1, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 129433664: Downloading webpage
[vimeo] 129433664: Extracting information
[vimeo] 129433664: Downloading webpage
[vimeo] 129433664: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[debug] Invoking downloader on u'https://10-lvl3-pdl.vimeocdn.com/01/886/5/129433664/374310577.mp4?expires=1447855702&token=013b157d61be0e68fd458'
[download] JUNNNKTANK.COM _ WKEND #62-129433664.mp4 has already been downloaded
[download] 100% of 29.85MiB
[vimeo] 127444264: Downloading webpage
[vimeo] 127444264: Extracting information
[vimeo] 127444264: Downloading webpage
[vimeo] 127444264: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[debug] Invoking downloader on u'https://10-lvl3-pdl.vimeocdn.com/01/488/5/127444264/365845817.mp4?expires=1447855702&token=0f156be818d4ae7796864'
[download] JUNNNKTANK.COM _ WKEND #59 f. Shima-127444264.mp4 has already been downloaded
[download] 100% of 50.96MiB
[vimeo] 119012293: Downloading webpage
[vimeo] 119012293: Extracting information
[vimeo] 119012293: Downloading webpage
[vimeo] 119012293: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[debug] Invoking downloader on u'https://10-lvl3-pdl.vimeocdn.com/01/3802/4/119012293/334189528.mp4?expires=1447855703&token=0f2cfc089fa7e0c3d0ef6'
[download] WKEND #46 f. Shima-119012293.mp4 has already been downloaded
[download] 100% of 51.80MiB
```

Edit: This problem appears only on some videos, not all. At a loss about how to reliably reproduce it although the above command _should_ do it.

**Comment by dstftw** [comment]
Works fine for me. Post the output of `youtube-dl --dump-pages https://vimeo.com/129433664`.

**Comment by vxbinaca** [comment]
If anyone else can't reproduce this I'm closing the issue.

**Comment by corone17** [comment]
```
youtube-dl.exe -vF https://vimeo.com/129433664 https://vimeo.com/127444264 https://vimeo.com/119012293
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-vF', u'https://vimeo.com/129433664', u'https://vimeo.com/127444264', u'https://vimeo.com/119012293']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-75746-g84b4998
[debug] Proxy map: {}
[vimeo] 129433664: Downloading webpage
[vimeo] 129433664: Extracting information
[vimeo] 129433664: Downloading webpage
[vimeo] 129433664: Downloading m3u8 information
[info] Available formats for 129433664:
format code  extension  resolution note
hls-meta     mp4        multiple   Quality selection URL
hls-632      mp4        640x360     632k
http-360p    mp4        640x360    , 30fps
hls-1915     mp4        1280x720   1915k
http-720p    mp4        1280x720   , 30fps (best)
[vimeo] 127444264: Downloading webpage
[vimeo] 127444264: Extracting information
[vimeo] 127444264: Downloading webpage
[vimeo] 127444264: Downloading m3u8 information
[info] Available formats for 127444264:
format code  extension  resolution note
hls-meta     mp4        multiple   Quality selection URL
hls-577      mp4        640x360     577k
http-360p    mp4        640x360    , 24fps
hls-1627     mp4        1280x720   1627k
http-720p    mp4        1280x720   , 24fps (best)
[vimeo] 119012293: Downloading webpage
[vimeo] 119012293: Extracting information
[vimeo] 119012293: Downloading webpage
[vimeo] 119012293: Downloading m3u8 information
[info] Available formats for 119012293:
format code  extension  resolution note
hls-meta     mp4        multiple   Quality selection URL
hls-614      mp4        640x360     614k
http-360p    mp4        640x360    , 24fps
hls-1803     mp4        1280x720   1803k
http-720p    mp4        1280x720   , 24fps (best)
```
No problem as you can see, but I've found one that seems to fail for another reason:
```
youtube-dl.exe -vF https://vimeo.com/145281255
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-vF', u'https://vimeo.com/145281255']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-75746-g84b4998
[debug] Proxy map: {}
[vimeo] 145281255: Downloading webpage
[vimeo] 145281255: Extracting information
[vimeo] 145281255: Downloading webpage
[vimeo] 145281255: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
[info] Available formats for 145281255:
format code  extension  resolution note
http-270p    mp4        480x270    , 24fps
http-360p    mp4        640x360    , 24fps
http-1080p   mp4        1920x1080  , 24fps (best)
```

**Comment by vxbinaca** [comment]
Perhaps a certain nation-state *ahem* is trying to MITM Vimeo? lol

**Comment by satellite1** [comment]
Hello, I'm able to repo. 

    # youtube-dl --ignore-config --verbose https://vimeo.com/129433664
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-config', u'--verbose', u'https://vimeo.com/129433664']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.6 - Linux-3.13.0-67-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] 129433664: Downloading webpage
[vimeo] 129433664: Extracting information
[vimeo] 129433664: Downloading webpage
[vimeo] 129433664: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Unavailable
[debug] Invoking downloader on u'https://11-lvl3-pdl.vimeocdn.com/01/886/5/129433664/374310577.mp4?expires=1449093858&token=05d342e661a369ebb7b2b'
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1878, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable

**Comment by Hrxn** [comment]
Did you try it again at a different time?

Because that was a HTTP 503.

If you get these, test in the browser.

Because right now it works for me..

**Comment by satellite1** [comment]
Appears to be working now. Probably my server was caching network data to vimeo, and that server it was talking to was taken offline, hence the 503. That's my guess at this point. That's why we were getting different results. Thanks for the reply and follow-up!
