### ISSUE TITLE
vimeo link stuck processing forever

### ISSUE THREAD

**Issue by amit777** [rg3/youtube-dl#7552]
eg:

python youtube-dl --dump-json https://vimeo.com/groups/travelhd/videos/146159746

The command seems to just get stuck forever. Is this a bug? I tried adding socket-timeout but no effect.

**Comment by phihag** [comment]
The link seems to be misdetected as the group - I assume you want to download just one video?

`--dump-json` is meant for machine-readable output, and therefore there is no status display. Leave it out and see that youtube-dl is dilligently fetching the information for all 40000 videos. Depending on your Internet connection, that may take a while.

**Comment by amit777** [comment]
oh, I see.  I just want to download the metadata for one video.  I don't need to actually download the full video.  Is it a bug in the detection algorithm or is this expected?  Also, is there any simple way to add a timeout to the script execution?
