### ISSUE TITLE
ERROR: Unable to extract title;

### ISSUE THREAD

**Issue by RandyMcMillan** [rg3/youtube-dl#7553]
randymcmillan at DSMacBookAir in ~/Mac2313/MITCalc3Lectures on master*
$ youtube-dl --verbose https://www.youtube.com/playlist?list=PL4EE732E1895F78A1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/playlist?list=PL4EE732E1895F78A1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2
[debug] Proxy map: {}
[youtube:playlist] PL4EE732E1895F78A1: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

randymcmillan at DSMacBookAir in ~/Mac2313/MITCalc3Lectures on master*
$

**Comment by jaimeMF** [comment]
Closing the issue since it's fixed in the last version.

> I have the same issue here, but if we use the Homebrew version aren't we at risk of breaking something if we use youtube-dl's own -U command for updating?

Probably. But you can submit the update to homebrew as a PR, they merge them quickly.
