### ISSUE TITLE
Got this 'unable to extract title' outta nowhere.

### ISSUE THREAD

**Issue by bibek22** [rg3/youtube-dl#7555]
Here's the link to pastebin of error with --verbose flag:

http://pastebin.com/VivLp3bk

This occured seemingly out of nowhere after already downloading 4 videos from the playlist.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by bibek22** [comment]
well, that's the latest version available in Arch Linux repo.
