### ISSUE TITLE
Youtube playlist backup and formats

### ISSUE THREAD

**Issue by Azenet** [rg3/youtube-dl#7560]
I use `youtube-dl` to backup a youtube playlist every day, but I'm running into an issue: very often I will get mp4 and mkv files of the same video in my folder. Both the files have video and audio. Is there a way I can avoid this happening ? I am running 2015.11.18, and the command line I am using is `youtube-dl -i playlistUrl`.

**Comment by jaimeMF** [comment]
So, what format you want? 
If you only want mp4 files you can use `-f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best`

**Comment by phihag** [comment]
You can also use `--download-archive`.

**Comment by Azenet** [comment]
Thanks for your answers, I am going to use `--download-archive archive -f best --merge-output-format mkv`, as I'd rather have mkv files, which seems to work for now. My actual issue was that youtube-dl would save sometimes in mp4 and sometimes in mkv, but `--download-archive` prevents that.

**Comment by dstftw** [comment]
`--download-archive` does not prevent that. What does prevent it is `--merge-output-format mkv`, i.e. always muxing `bestvideo+bestaudio` into `mkv`.

**Comment by Azenet** [comment]
@dstftw I meant downloading videos only once whatever the resulting format.
