### ISSUE TITLE
New Problems With video.pbs.org

### ISSUE THREAD

**Issue by wright546** [rg3/youtube-dl#7565]
I use youtube-dl to get PBS programs on a weekly basis.  I know this was working last week (and for many months before that), so I'm guessing PBS recently changed something.  I tested the URL in the below examples in Chrome and verified that the video is actually there and plays successfully.  I also updated to the most recent version of youtube-dl, 2015.11.18.  The first example below is from a FreeBSD 10.2 machine with Python 2.7.9, and the second example is from a Windows XP machine with Python 2.7.10.  Please let me know if I need to provide any further information.  Thank you!

8:17am ~ >./youtube-dl --verbose -F http://video.pbs.org/video/2365607036/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-F', u'http://video.pbs.org/video/2365607036/']
[debug] Encodings: locale US-ASCII, fs US-ASCII, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2015.11.18
[debug] Python version 2.7.9 - FreeBSD-10.2-RELEASE-p3-amd64-64bit-ELF
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[PBS] 2365607036: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/pbs.py", line 301, in _real_extract
    self._sort_formats(formats)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Files\Programs>c:\files\Programs\youtube-dl.exe --verbose -F http://video.pbs
.org/video/2365609360/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-F', u'http://video.pbs.org/video/23
65609360/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.18
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[PBS] 2365609360: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\pbs.pyo", line 301, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 766, in _sort_formats
ExtractorError: No video formats found; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.

**Comment by zacradke** [comment]
Same here, I used it a few weeks ago. I believe they are using a new flash-based video player, "JW Player". Had this issue with a handful of previous versions.

**Comment by phihag** [comment]
Thank you for the report. I believe this issue to be fixed in youtube-dl 2015.11.19 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by zacradke** [comment]
Excellent work! Just ran update and is working again.

**Comment by wright546** [comment]
It is working for me again as well.  Thanks very much for such a prompt fix!
