### ISSUE TITLE
"-i" doesn't work

### ISSUE THREAD

**Issue by Klaus1189** [rg3/youtube-dl#7566]
I use a conf file. If I download for example three videos batch as mp4, webm, m4a and one video isn't available as webm the it stops at webm and the m4a files are not downloaded.
For example:
`youtube-dl -f 160 -a x.txt -o "D:\%(title)s.%(ext)s" && youtube-dl -f 278 -a x.txt -o "D:\%(title)s.%(ext)s" && youtube-dl -f 141/140 -a x.txt -o "D:\y%(title)s.%(ext)s"`

If there is a better syntax let me know, but for some cases I need this `&&` and please fix this abort

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by Klaus1189** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Klaus\Downloads\youtube-dl>youtube-dl -f 138/266/264/299/137/298/136/135/134/133/160 -a x.txt -o "D:\youtube-dl\%(id)s\%(title)s.%(ext)s" && youtube-dl -f 315/272/313/308/27
1/303/248/302/247/244/243/242/278 -a x.txt -o "D:\youtube-dl\%(id)s\%(title)s.%(ext)s" && youtube-dl -f 141/140 -a x.txt -o "D:\youtube-dl\%(id)s\%(title)s.%(ext)s" && youtube-dl -f 171 -a x
.txt -o "D:\youtube-dl\%(id)s\%(title)s.vorbis.%(ext)s" && youtube-dl -f 251 -a x.txt -o "D:\youtube-dl\%(id)s\%(title)s.opus.%(ext)s" && youtube-dl --all-subs --skip-download -a x.txt -o "D
:\youtube-dl\%(id)s\%(title)s"
[debug] System config: []
[debug] User config: [u'-v', u'-i', u'--proxy', u'']
[debug] Command-line args: [u'-f', u'138/266/264/299/137/298/136/135/134/133/160', u'-a', u'x.txt', u'-o', u'D:\\youtube-dl\\%(id)s\\%(title)s.%(ext)s']
[debug] Batch file urls: [u'https://www.youtube.com/watch?v=R3FVyOtKM4U', u'https://www.youtube.com/watch?v=Z__uY3hksjQ']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.19
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] R3FVyOtKM4U: Downloading webpage
[youtube] R3FVyOtKM4U: Downloading video info webpage
[youtube] R3FVyOtKM4U: Extracting video information
[youtube] R3FVyOtKM4U: Downloading DASH manifest
[youtube] R3FVyOtKM4U: Downloading DASH manifest
[debug] Invoking downloader on u'https://r7---sn-uxax4vopj5qx-q0nl.googlevideo.com/videoplayback?id=477155c8eb4a3385&itag=137&source=youtube&requiressl=yes&pl=24&mm=31&mn=sn-uxax4vopj5qx-q0n
l&ms=au&mv=m&ratebypass=yes&mime=video/mp4&gir=yes&clen=10685693&lmt=1398511050750954&dur=31.364&key=dg_yt0&signature=9113AEF1C7E274317182094EEA031E7E835046B2.96EFB2D07192C81ED9DEB9540C895B6
4A1E990F7&upn=nFxcDSt3TXo&sver=3&mt=1447946404&fexp=9408710,9416126,9417683,9420452,9422494,9422596,9422618,9423662&ip=88.133.5.74&ipbits=0&expire=1447968208&sparams=ip,ipbits,expire,id,itag
,source,requiressl,pl,mm,mn,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: D:\youtube-dl\R3FVyOtKM4U\23.976 fps 23Hz testfile.mp4
[download] 100% of 10.19MiB in 00:17
[youtube] Z__uY3hksjQ: Downloading webpage
[youtube] Z__uY3hksjQ: Downloading video info webpage
[youtube] Z__uY3hksjQ: Extracting video information
[youtube] Z__uY3hksjQ: Downloading DASH manifest
[youtube] Z__uY3hksjQ: Downloading DASH manifest
[debug] Invoking downloader on u'https://r3---sn-uxax4vopj5qx-q0nl.googlevideo.com/videoplayback?id=67ffee637864b234&itag=137&source=youtube&requiressl=yes&ms=au&pl=24&mn=sn-uxax4vopj5qx-q0n
l&mm=31&mv=m&gcr=de&ratebypass=yes&mime=video/mp4&gir=yes&clen=70375643&lmt=1427614314227082&dur=325.074&fexp=9408710,9416126,9417683,9420452,9422494,9422596,9422618,9423662&mt=1447946404&sv
er=3&key=dg_yt0&upn=uVI9vw_DUDA&signature=0E4DA4BC88CB45B2E74A709837419A9D98B1FD4E.4097191A35E5112D3587B3A9A9D5624E2C3EABBB&ip=88.133.5.74&ipbits=0&expire=1447968227&sparams=ip,ipbits,expire
,id,itag,source,requiressl,ms,pl,mn,mm,mv,gcr,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: D:\youtube-dl\Z__uY3hksjQ\KYGO - Stole The Show (Official Video).mp4
[download] 100% of 67.12MiB in 00:53
[debug] System config: []
[debug] User config: [u'-v', u'-i', u'--proxy', u'']
[debug] Command-line args: [u'-f', u'315/272/313/308/271/303/248/302/247/244/243/242/278', u'-a', u'x.txt', u'-o', u'D:\\youtube-dl\\%(id)s\\%(title)s.%(ext)s']
[debug] Batch file urls: [u'https://www.youtube.com/watch?v=R3FVyOtKM4U', u'https://www.youtube.com/watch?v=Z__uY3hksjQ']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.19
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] R3FVyOtKM4U: Downloading webpage
[youtube] R3FVyOtKM4U: Downloading video info webpage
[youtube] R3FVyOtKM4U: Extracting video information
[youtube] R3FVyOtKM4U: Downloading DASH manifest
[youtube] R3FVyOtKM4U: Downloading DASH manifest
ERROR: requested format not available
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 672, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 718, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1328, in process_video_result
ExtractorError: requested format not available

[youtube] Z__uY3hksjQ: Downloading webpage
[youtube] Z__uY3hksjQ: Downloading video info webpage
[youtube] Z__uY3hksjQ: Extracting video information
[youtube] Z__uY3hksjQ: Downloading DASH manifest
[youtube] Z__uY3hksjQ: Downloading DASH manifest
[debug] Invoking downloader on u'https://r3---sn-uxax4vopj5qx-q0nl.googlevideo.com/videoplayback?id=67ffee637864b234&itag=248&source=youtube&requiressl=yes&gcr=de&pl=24&mn=sn-uxax4vopj5qx-q0
nl&mm=31&ms=au&mv=m&ratebypass=yes&mime=video/webm&gir=yes&clen=47205764&lmt=1427262483463481&dur=325.033&fexp=9408710,9413122,9416126,9417683,9417878,9420452,9420932,9421249,9422596,9422618
,9422674,9422863,9423392,9423510,9423662,9423718,9424198,9424509&upn=29C1Rb-DZa4&signature=06456E8F0551EAA3A07A23482DAB5EC24BC09D25.7EEE83BAEB12D83364DDD68FDE2D75911A97251B&sver=3&key=dg_yt0
&mt=1447946590&ip=88.133.5.74&ipbits=0&expire=1447968284&sparams=ip,ipbits,expire,id,itag,source,requiressl,gcr,pl,mn,mm,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: D:\youtube-dl\Z__uY3hksjQ\KYGO - Stole The Show (Official Video).webm
[download] 100% of 45.02MiB in 00:32

C:\Users\Klaus\Downloads\youtube-dl>

**Comment by dstftw** [comment]
In fact your log proves that `-i` actually works since `&&` does not evaluate next command if previous one has failed (that's similar to short circuit evalution in some sense). So, you should use single ampersand that does not have that check.

**Comment by Klaus1189** [comment]
Thank you for your help :+1:
