### ISSUE TITLE
youtube user's playlist videos in separate subfolders not working

### ISSUE THREAD

**Issue by ZubairLK** [rg3/youtube-dl#7570]
Hi,

I am trying to download all videos in all playlists in a channel and putting them in sub-folders.

Instead of putting them in sub-folders, it puts them in Uploads_by_Username

I have tried reading the docs. But might have missed something..

Here is my command line and output.

zubairlk@zubairlk-linux /mnt/khan $ youtube-dl -cw -f '(webm)[height<480]'  -o '/mnt/khanurdu/%(playlist)s_2/%(playlist_index)s_%(title)s_%(id)s.%(ext)s' --yes-playlist --restrict-filenames ytuser:khanacademy -R 10000 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-cw', u'-f', u'(webm)[height<480]', u'-o', u'/mnt/khanurdu/%(playlist)s_2/%(playlist_index)s_%(title)s_%(id)s.%(ext)s', u'--yes-playlist', u'--restrict-filenames', u'ytuser:khanacademy', u'-R', u'10000', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.19
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:user] khanacademy: Downloading channel page
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading webpage
[download] Downloading playlist: Uploads from Khan Academy
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #1
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #2
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #3
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #4
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #5
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #6
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #7
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #8
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #9
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #10
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #11
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #12
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #13
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #14
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #15
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #16
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #17
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #18
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #19
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #20
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #21
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #22
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #23
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #24
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #25
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #26
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #27
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #28
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #29
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #30
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #31
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #32
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #33
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #34
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #35
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #36
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #37
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #38
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #39
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #40
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #41
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #42
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #43
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #44
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #45
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #46
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #47
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #48
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #49
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #50
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #51
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #52
[youtube:playlist] UU4a-Gbdw7vOaccHmFo40b9g: Downloading page #53
[youtube:playlist] playlist Uploads from Khan Academy: Downloading 5285 videos
[download] Downloading video 1 of 5285
[youtube] DJfNr8WoXW4: Downloading webpage
[youtube] DJfNr8WoXW4: Downloading video info webpage
[youtube] DJfNr8WoXW4: Extracting video information
[youtube] DJfNr8WoXW4: Downloading DASH manifest
[youtube] DJfNr8WoXW4: Downloading DASH manifest
[debug] Invoking downloader on u'https://r1---sn-8pgbpohxqp5-ac5l.googlevideo.com/videoplayback?dur=0.000&ipbits=0&sver=3&lmt=1447726729336414&expire=1447996922&ratebypass=yes&signature=D740238E226D39DB6F5F07E8B6278B828A663DD3.6A059F287B52866874789A6EC0CEDA2DC91F9927&mn=sn-8pgbpohxqp5-ac5l&mm=31&pl=22&id=o-ANXS7uAy9x_UcusTqyEv_nxAY7LTJfUXblmNNtu7DDvg&requiressl=yes&ip=86.9.186.186&fexp=9407190%2C9408013%2C9408710%2C9408939%2C9416007%2C9416126%2C9416985%2C9417342%2C9417683%2C9418145%2C9420452%2C9421561%2C9422596%2C9422618%2C9423662%2C9423667%2C9424135%2C9424194%2C9424508%2C9424632&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mv=m&mt=1447975223&ms=au&initcwndbps=2043750&upn=F5Pmo3tQspw&source=youtube&itag=43&key=yt6&mime=video%2Fwebm'
[download] Destination: /mnt/khanurdu/Uploads_from_Khan_Academy_2/0001_Cell_signaling_in_yeast_reproduction_DJfNr8WoXW4.webm
[download] 100% of 9.59MiB in 00:01
[download] Downloading video 2 of 5285
[youtube] i7z7f-wnews: Downloading webpage
[youtube] i7z7f-wnews: Downloading video info webpage
[youtube] i7z7f-wnews: Extracting video information
[youtube] i7z7f-wnews: Downloading DASH manifest
[youtube] i7z7f-wnews: Downloading DASH manifest
[debug] Invoking downloader on u'https://r2---sn-8pgbpohxqp5-ac5e.googlevideo.com/videoplayback?pl=22&upn=1UM6t547bTU&ipbits=0&mm=31&mn=sn-8pgbpohxqp5-ac5e&id=o-ACGR5zJExf4qp01BMhJv3FEaSa-MyqUoIM0hd6Vom90L&source=youtube&initcwndbps=2043750&ip=86.9.186.186&signature=44BA2536CA0F24BAACB6FD90F0C6B11EA9946EC9.3B878258FE8C48B5543CFC29F830D75A49ACD331&mt=1447975223&mv=m&ms=au&lmt=1447698156065546&dur=0.000&mime=video%2Fwebm&key=yt6&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&expire=1447996925&fexp=9407190%2C9408013%2C9408710%2C9408939%2C9416007%2C9416126%2C9416985%2C9417342%2C9417683%2C9418145%2C9420452%2C9421561%2C9422596%2C9422618%2C9423662%2C9423667%2C9424135%2C9424194%2C9424508%2C9424632&sver=3&requiressl=yes&itag=43&ratebypass=yes'
[download] Destination: /mnt/khanurdu/Uploads_from_Khan_Academy_2/0002_Example_of_signal_transduction_pathway_i7z7f-wnews.webm
[download] 100% of 12.91MiB in 00:02
[download] Downloading video 3 of 5285
[youtube] RmFDLCwePAo: Downloading webpage
[youtube] RmFDLCwePAo: Downloading video info webpage
[youtube] RmFDLCwePAo: Extracting video information
[youtube] RmFDLCwePAo: Downloading DASH manifest
[youtube] RmFDLCwePAo: Downloading DASH manifest
[debug] Invoking downloader on u'https://r1---sn-8pgbpohxqp5-ac5e.googlevideo.com/videoplayback?ip=86.9.186.186&key=yt6&signature=73A8E592B23CAE1041BD6C3A207D3026B93E92C3.933F496EBD3789C0846DB2FD9BCBDDC4BA443352&mm=31&mn=sn-8pgbpohxqp5-ac5e&mt=1447975223&mv=m&id=o-AKX5SiIw5TkT69Xh5z93Sjyy81vQHFrRf8R2jiz3-g7D&ms=au&source=youtube&lmt=1446773700302667&dur=0.000&sver=3&pl=22&fexp=9407190%2C9408013%2C9408710%2C9408939%2C9416007%2C9416126%2C9416985%2C9417342%2C9417683%2C9418145%2C9420452%2C9421561%2C9422596%2C9422618%2C9423662%2C9423667%2C9424135%2C9424194%2C9424508%2C9424632&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&itag=43&upn=IhX_P2ShgO8&mime=video%2Fwebm&requiressl=yes&ipbits=0&ratebypass=yes&expire=1447996928&initcwndbps=2043750'
[download] Destination: /mnt/khanurdu/Uploads_from_Khan_Academy_2/0003_Introduction_to_nouns_and_verbs_RmFDLCwePAo.webm
[download] 100% of 6.06MiB in 00:00
[download] Downloading video 4 of 5285
[youtube] FQFBygnIONU: Downloading webpage
[youtube] FQFBygnIONU: Downloading video info webpage
^C
ERROR: Interrupted by user
zubairlk@zubairlk-linux /mnt/khan $ 

Is this a case of waiting until all those not in a playlist are downloaded, then the rest of the playlists will be downloaded?

Feels like the playlist id/title isn't being read correctly.

I tried reading the json output. Takes a ton of time for that channel, might want to try a different user.

But the playlist titles were all uploads by khanacademy. :/

Thanks,
ZubairLK

btw. youtube-dl is extremely awesome! +1 for the devs behind it!

**Comment by dstftw** [comment]
This is expected behavior. See #7372.

**Comment by ZubairLK** [comment]
Thank-you for the quick response!

**Comment by dstftw** [comment]
This feature will be supported in the next version for URLs of the following format: `http://www.youtube.com/user/<user>/playlists`.
