### ISSUE TITLE
Allow getting updated man page via -U

### ISSUE THREAD

**Issue by Vrihub** [rg3/youtube-dl#7580]
It would be nice if users who update their local copy via "youtube-dl -U" could also get an updated copy of the man page.

I guess this should imply adding a copy of the man page source file to the zipped youtube-dl executable, and adding a command-line option to generate/display the man page (something like "youtube-dl --man", following the example of "youtube-dl --help").

**Comment by yan12125** [comment]
Python's ```pip``` tool provides such a functionality. That is, man pages are installed and upgraded with the package. Check [installation instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#installation) and [upgrade instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) for how to use ```pip``` with youtube-dl.
