### ISSUE TITLE
Site request: REN.TV

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#7582]
Hello author !
What a great YOUTUBE-DL proggie, I appreciate you for this one !

Now I want to ask you to add extractor for REN.TV russian TV channel, it has many interesting documentary movies that many people would like to have on local HDD.

Example url is: http://ren.tv/novosti/2015-09-25/sluchaynyy-prohozhiy-poymal-avtougonshchika-v-murmanske-video

The youtube-dl -v log is pasted here: http://fpaste.org/292969/48057944/

Thanks in advance !!!
-t
ps. If this _is_ ffmpeg bug/unsupported ft, then tell me so, PLEASE:)

**Comment by yan12125** [comment]
Thanks for the report. This video will be supported in the next version.

**Comment by nmr50** [comment]
btw, I hope that not only _this_ video will be supported, but all the videos from ren.tv site?:)

If you mean only one video, let me paste more different urls so you can make more testings:
http://ren.tv/video/epizod/60486
http://ren.tv/video/epizod/6662
http://ren.tv/video/epizod/7486
-- these are from different sub-projects on the site, please, make sure all 4 videos I listed here and earlier will be downloadable:)

Thank you!

**Comment by yan12125** [comment]
All of the URLs listed above can be downloaded since 750b9ff. Feel free to open a new issue if there are still unsupported REN.tv videos when the next version is released.

**Comment by nmr50** [comment]
_Thank you very much_, I'm waiting for new version - current one is^
C:\temp>youtube-dl.exe -U
youtube-dl is up-to-date (2015.11.19)

**Comment by nmr50** [comment]
Hello, Yan! Got version update 2015.11.21, but still cannot download REN.TV files:
C:\temp>youtube-dl.exe -U
youtube-dl is up-to-date (2015.11.21)
C:\temp>youtube-dl.exe "http://ren.tv/video/epizod/58631"
[generic] 58631: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 58631: Downloading webpage
[generic] 58631: Extracting information
ERROR: Unsupported URL: http://ren.tv/video/epizod/58631

**Comment by dstftw** [comment]
@nmr50 there is no video on this page.

**Comment by nmr50** [comment]
Aha, I got another url: http://ren.tv/video/epizod/5620
Looks like youtube-dl works OK but I have one question:
C:\temp>youtube-dl.exe --list-formats "http://ren.tv/video/epizod/5620"
[generic] 5620: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 5620: Downloading webpage
[generic] 5620: Extracting information
[generic] playlist: Downloading m3u8 information
[info] Available formats for playlist:
format code  extension  resolution note
meta         mp4        multiple   Quality selection URL
1201         mp4        768x576    1201k , avc1,  mp4a (best)

Can I get full listing of what quality options are listed there or this message does mean that only one quality is available ?

**Comment by dstftw** [comment]
>this message does mean that only one quality is available

**Comment by nmr50** [comment]
ah, I see, thanks! so - youtube-dl is compatible with ren.tv extraction, let this issue to be closed a day after, I'll do more tests and reply back.

**Comment by nmr50** [comment]
OK, ren.tv seems to be working as needed, but I met another thingie with the site that _before_ worked ok! Let me open another issue..
