### ISSUE TITLE
Question: Is it possible to download from specified second of video to some other second

### ISSUE THREAD

**Issue by ademgashi** [rg3/youtube-dl#7585]
Hi, guys I really appreciate your work and kudos for this amazing tool that you have build.

I tried to search for this scenario but could not find (or maybe missed it) anything related to it.

I was wondering if it ti possible to do something like this 

youtube-dl 'https://www.youtube.com/watch?t=4&v=BaW_jenozKc' --60s

where t=4 it means start from 4th second of the video (stating the obvious)

and --60s means and continue another 60seconds and stop save and finish the process.

Hoping to hear soon from you.

**Comment by yan12125** [comment]
It's not implemented yet. See #642 and #622 for more information.
