### ISSUE TITLE
Unable to Extract Title on Channel Download

### ISSUE THREAD

**Issue by HorikawaOtane** [rg3/youtube-dl#7587]
I am trying to back up a YouTuber and it worked for awhile, but it appears to have stopped working recently. I'm using 2015.11.10 on arch linux. The command I'm using is:

` youtube-dl -f bestvideo+bestaudio --download-archive ~/sandbox/raocowDownloaded.txt -o "%(title)s-%(id)s.%(ext)s" --write-description --write-info-json --exec 'mv {} ~/amazon/raocow/; mv ~/butts/* ~/amazon/raocow' http://youtube.com/raocow;`

And this results in the error:

>[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio', '--download-archive', '/home/nimue/sandbox/raocowDownloaded.txt', '-o', '%(title)s-%(id)s.%(ext)s', '--write-description', '--write-info-json', '--exec', 'mv {} ~/amazon/raocow/; mv ~/butts/* ~/amazon/raocow', 'http://youtube.com/raocow', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 3.5.0 - Linux-4.1.5-x86_64-linode61-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:user] raocow: Downloading channel page
[youtube:playlist] UUjM-Wd2651MWgo0s5yNQRJA: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
You need to upgrade your copy to the latest version (2015.11.19). Check [update instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) if you have encountered any problem.
