### ISSUE TITLE
Site request: TNT online via Rutube.ru

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#7588]
Hello dear author!

I am very pleased you've answered on previous req, so let me put another one :)
We have TNT channel with some nice projects on it, yet it seems this site is posting videos on rutube video hosting. The example url is: http://rutube.ru/play/embed/8083783

What I see when I try to use youtube-dl -v:
C:\temp>youtube-dl.exe -v http://rutube.ru/play/embed/8083783
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://rutube.ru/play/embed/8083783']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.11.19
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-76479-gc878082
[debug] Proxy map: {}
[generic] 8083783: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 8083783: Downloading webpage
[generic] 8083783: Extracting information
ERROR: Unsupported URL: http://rutube.ru/play/embed/8083783
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1255, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 46, column 56
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\generic.pyo", line 1858, in _real_extract
UnsupportedError: Unsupported URL: http://rutube.ru/play/embed/8083783

Please, put this rutube.ru site as supported one in the next version. Thanks!
-t

**Comment by yan12125** [comment]
Rutube is supported while embedded Rutube ones not. Currently I can't test against this video due to the following error:
![screenshot_2015-11-21_18-30-32](https://cloud.githubusercontent.com/assets/1937689/11318054/1d1f0bc2-907e-11e5-8196-1cdb225164f0.png)
Could you try:
```
youtube-dl -v "http://rutube.ru/video/c1555fba62d71aec25f8bf69bf487e95/"
```

**Comment by nmr50** [comment]
Yes, man! It works! Here is the log:
C:\temp>youtube-dl -v "http://rutube.ru/video/c1555fba62d71aec25f8bf69bf487e95/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://rutube.ru/video/c1555fba62d71aec25f8
bf69bf487e95/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.11.19
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-76741-g8eadabf
[debug] Proxy map: {}
[rutube] c1555fba62d71aec25f8bf69bf487e95: Downloading video JSON
[rutube] c1555fba62d71aec25f8bf69bf487e95: Downloading options JSON
[rutube] c1555fba62d71aec25f8bf69bf487e95: Downloading m3u8 information
[debug] Invoking downloader on u'http://video-4-302.rutube.ru/hls-vod/gVltfVjlsw
samtIEps5StQ/1448109517/66/0x5000c50066d68d71/784fae05ac8349cfbdb5db78892634d6.mp4.m3u8?i=1280x720_3212'
[download] Destination: Битва экстрасенсов - сезон 16, серия 8-c1555fba62d71aec25f8bf69bf487e95.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Charset: ISO-8859-1,utf-
8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0
 (Chrome)
' -i 'http://video-4-302.rutube.ru/hls-vod/gVltfVjlswsamtIEps5StQ/1448109517/66/0x5000c50066d68d71/784fae05ac8349cfbdb5db78892634d6.mp4.m3u8?i=1280x720_3212' -f
 mp4 -c copy -bsf:a aac_adtstoasc 'file:Битва экстрасенсов - сезон 16, серия 8-c1555fba62d71aec25f8bf69bf487e95.mp4.part'
ffmpeg version N-76741-g8eadabf Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 5.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-l
ibilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enab
le-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --en
able-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --ena
ble-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc
 --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enabl
e-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --
enable-lzma --enable-decklink --enable-zlib
  libavutil      55.  7.100 / 55.  7.100
  libavcodec     57. 15.100 / 57. 15.100
  libavformat    57. 16.100 / 57. 16.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 15.100 /  6. 15.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, hls,applehttp, from 'http://video-4-302.rutube.ru/hls-vod/gVltfVjlswsa
mtIEps5StQ/1448109517/66/0x5000c50066d68d71/784fae05ac8349cfbdb5db78892634d6.mp4
.m3u8?i=1280x720_3212':
  Duration: 01:13:31.00, start: 0.700000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720
[SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, mono, fltp,
 195 kb/s
[mp4 @ 00000000039bb340] Codec for stream 0 does not use global headers but cont
ainer format requires global headers
[mp4 @ 00000000039bb340] Codec for stream 1 does not use global headers but cont
ainer format requires global headers
Output #0, mp4, to 'file:╨С╨╕╤В╨▓╨░ ╤Н╨║╤Б╤В╤А╨░╤Б╨╡╨╜╤Б╨╛╨▓ - ╤Б╨╡╨╖╨╛╨╜ 16, ╤Б
╨╡╤А╨╕╤П 8-c1555fba62d71aec25f8bf69bf487e95.mp4.part':
  Metadata:
    encoder         : Lavf57.16.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720 [SAR 1:
1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, mono, 195 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  199 fps=0.0 q=-1.0 size=    3268kB time=00:00:08.03 bitrate=3332.2kbits/
frame=  599 fps=410 q=-1.0 size=   10521kB time=00:00:24.03 bitrate=3586.2kbits/
frame=  811 fps=414 q=-1.0 size=   14220kB time=00:00:32.53 bitrate=3580.9kbits/
frame=  999 fps=406 q=-1.0 size=   17485kB time=00:00:40.03 bitrate=3578.2kbits/

-- I'll try to test with other videos and IF I get some difficulties - I'll post this info here or - will open another issue. [B]THANK YOU VERY MUCH !!![/B]
