### ISSUE TITLE
Downloading playlists from a channel into folders

### ISSUE THREAD

**Issue by miacaba** [rg3/youtube-dl#7591]
Hello,

I'm trying to get a channel playlist to download into folders. I tried using the following command but got this error:

youtube-dl -citw --youtube-skip-dash-manifest -f 18 "https://www.youtube.com/user/OUlearn/playlists" --get-filename -o "/%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s" --restrict-filenames

error: "using output template conflicts with using
title, video ID or auto number"

What is wrong with this? or what is the proper command? I would like to get them in 480p if possible, with each playlist in its own folder. Thank you.

**Comment by dstftw** [comment]
>error: "using output template conflicts with using title, video ID or auto number"
>output template conflicts with using title
>-o
>-ci**t**w

**Comment by miacaba** [comment]
What does this mean?

**Comment by dstftw** [comment]
I've highlighted the conflicting options that you specified in your command line or most likely copypasted from some third source.

**Comment by miacaba** [comment]
I removed the -citw and got this error:

ERROR: Unable to download JSON metadata: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol> (caused by URLError(SSLError(8, '_ssl.c:510: EOF occurred in violation of protocol'),))

**Comment by dstftw** [comment]
Read [bug reporting guidline](https://github.com/rg3/youtube-dl#bugs) and open a new issue.
