### ISSUE TITLE
ERROR: Unsupported URL: http://www.cc.com/video-clips/li3ubo/the-daily-show-with-jon-stewart-tv-banne

### ISSUE THREAD

**Issue by mpappasx** [rg3/youtube-dl#7597]
$ youtube-dl --verbose http://www.cc.com/video-clips/li3ubo/the-daily-show-with-jon-stewart-tv-banned/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.cc.com/video-clips/li3ubo/the-daily-show-with-jon-stewart-tv-banned/']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] Proxy map: {}
[generic] : Requesting header
[redirect] Following redirect to http://www.cc.com/video-clips/li3ubo/the-daily-show-with-jon-stewart-tv-banned
[generic] the-daily-show-with-jon-stewart-tv-banned: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-daily-show-with-jon-stewart-tv-banned: Downloading webpage
[generic] the-daily-show-with-jon-stewart-tv-banned: Extracting information
ERROR: Unsupported URL: http://www.cc.com/video-clips/li3ubo/the-daily-show-with-jon-stewart-tv-banned; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 380, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.cc.com/video-clips/li3ubo/the-daily-show-with-jon-stewart-tv-banned; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by jaimeMF** [comment]
You are using an horrible out of date version of youtube-dl (2014.02.17 is more than one year old, lots of sites won't work), read the [update instructions](https://github.com/rg3/youtube-dl/blob/741dd8ea65b276997f3eadae43b2879e9a229a80/README.md#how-do-i-update-youtube-dl) if you have any problem.
