### ISSUE TITLE
NowTV download fails

### ISSUE THREAD

**Issue by c1ko** [rg3/youtube-dl#7598]
Hi. Using 2015.11.19 and the latest rtmpdump from their git I am not able to download NowTV videos.

	youtube-dl -v http://www.nowtv.de/rtl/wer-wird-millionaer/wer-wird-millionaer-prominentenspecial/player[debug] System config: []
	[debug] User config: []
	[debug] Command-line args: [u'-v', u'http://www.nowtv.de/rtl/wer-wird-millionaer/wer-wird-millionaer-prominentenspecial/player']
	[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
	[debug] youtube-dl version 2015.11.19
	[debug] Python version 2.7.10 - Linux-4.2.5-300.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
	[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1, rtmpdump 2.4
	[debug] Proxy map: {}
	[NowTV] wer-wird-millionaer/wer-wird-millionaer-prominentenspecial: Downloading JSON metadata
	[debug] Invoking downloader on u'rtmpe://fms.rtl.de'
	[download] Destination: Prominentenspecial-234635.flv
	[debug] rtmpdump command line: rtmpdump --verbose -r rtmpe://fms.rtl.de -o Prominentenspecial-234635.flv.part --swfVfy http://cdn.static-fra.de/now/vodplayer.swf --pageUrl http://rtlnow.rtl.de --app rtlnow --playpath mp4:35/V_900654_JZGI_13-13000730962_130806_h264-hq_eabc271ad38c61eb8a538714ba8e3033.f4v --resume --skip 1
	[rtmpdump] RTMPDump v2.4
	[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
	[rtmpdump] DEBUG: Parsing...
	[rtmpdump] DEBUG: Parsed protocol: 2
	[rtmpdump] DEBUG: Parsed host    : fms.rtl.de
	[rtmpdump] WARNING: No application or playpath in URL!
	[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
	[rtmpdump] WARNING: Ignoring SWF hash, supply also the swf size  with --swfsize
	[rtmpdump] DEBUG: Protocol : RTMPE
	[rtmpdump] DEBUG: Hostname : fms.rtl.de
	[rtmpdump] DEBUG: Port     : 1935
	[rtmpdump] DEBUG: Playpath : mp4:35/V_900654_JZGI_13-13000730962_130806_h264-hq_eabc271ad38c61eb8a538714ba8e3033.f4v
	[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.rtl.de:1935/rtlnow
	[rtmpdump] DEBUG: swfUrl   : http://cdn.static-fra.de/now/vodplayer.swf
	[rtmpdump] DEBUG: pageUrl  : http://rtlnow.rtl.de
	[rtmpdump] DEBUG: app      : rtlnow
	[rtmpdump] DEBUG: live     : no
	[rtmpdump] DEBUG: timeout  : 30 sec
	[rtmpdump] DEBUG: Failed to get last keyframe.
	[rtmpdump] DEBUG: Closing connection.
	[rtmpdump] 0 bytes
	[rtmpdump] RTMPDump v2.4
	[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
	[rtmpdump] DEBUG: Parsing...
	[rtmpdump] DEBUG: Parsed protocol: 2
	[rtmpdump] DEBUG: Parsed host    : fms.rtl.de
	[rtmpdump] WARNING: No application or playpath in URL!
	[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
	[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
	[rtmpdump] WARNING: Ignoring SWF hash, supply also the swf size  with --swfsize
	[rtmpdump] DEBUG: Protocol : RTMPE
	[rtmpdump] DEBUG: Hostname : fms.rtl.de
	[rtmpdump] DEBUG: Port     : 1935
	[rtmpdump] DEBUG: Playpath : mp4:35/V_900654_JZGI_13-13000730962_130806_h264-hq_eabc271ad38c61eb8a538714ba8e3033.f4v
	[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.rtl.de:1935/rtlnow
	[rtmpdump] DEBUG: swfUrl   : http://cdn.static-fra.de/now/vodplayer.swf
	[rtmpdump] DEBUG: pageUrl  : http://rtlnow.rtl.de
	[rtmpdump] DEBUG: app      : rtlnow
	[rtmpdump] DEBUG: live     : no
	[rtmpdump] DEBUG: timeout  : 30 sec
	[rtmpdump] DEBUG: Failed to get last keyframe.
	[rtmpdump] DEBUG: Closing connection.

	ERROR: rtmpdump exited with code 1
	  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
		"__main__", fname, loader, pkg_name)
	  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
		exec code in run_globals
	  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
		youtube_dl.main()
	  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
		_real_main(argv)
	  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
		retcode = ydl.download(all_urls)
	  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1666, in download
		url, force_generic_extractor=self.params.get('force_generic_extractor', False))
	  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 672, in extract_info
		return self.process_ie_result(ie_result, download, extra_info)
	  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 718, in process_ie_result
		return self.process_video_result(ie_result, download=download)
	  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1336, in process_video_result
		self.process_info(new_info)
	  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1598, in process_info
		success = dl(filename, info_dict)
	  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1540, in dl
		return fd.download(name, info)
	  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
		return self.real_download(filename, info_dict)
	  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
		self.report_error('rtmpdump exited with code %d' % retval)
	  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
		self.ydl.report_error(*args, **kargs)
	  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 536, in report_error
		self.trouble(error_message, tb)
	  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 498, in trouble
		tb_data = traceback.format_list(traceback.extract_stack())

Last commit in my rtmpdump is a107cef9b392616dff54fabfd37f985ee2190a6f (Wed Jan 14 23:24:12 2015 +0200). OS is Fedora 23.

**Comment by AndroKev** [comment]
hi try to delete the "Prominentenspecial-234635.flv.part" file and try it then again!

**Comment by z0mt3c** [comment]
How about?
````log
youtube-dl http://www.nowtv.de/rtl/wer-wird-millionaer/wer-wird-millionaer-prominentenspecial/player -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.nowtv.de/rtl/wer-wird-millionaer/wer-wird-millionaer-prominentenspecial/player', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.21
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2, rtmpdump 2.4
[debug] Proxy map: {}
[NowTV] wer-wird-millionaer/wer-wird-millionaer-prominentenspecial: Downloading JSON metadata
ERROR: Unable to download JSON metadata: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 329, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1874, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 798, in https_open
    req, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
```
any idea?

**Comment by p-s-** [comment]
for me nowtv fails with:

ERROR: Unsupported URL: http://www.nowtv.at/vox/mein-himmlisches-hotel/jahr/2015/11/gruppe-stadt-vs-land-tag-5-finale/

Is it because I'm with an Austrian IP? Changing the .at in the URL to .de just redirects to the .at URL ...

**Comment by AndroKev** [comment]
@p-s- 
that the correct url: http://www.nowtv.at/vox/mein-himmlisches-hotel/gruppe-stadt-vs-land-tag-5-finale/player

**Comment by p-s-** [comment]
@AndroKev Oh wow! Yes! Thank You for helping a newbie! : )

**Comment by dstftw** [comment]
Superseded by #7831.
