### ISSUE TITLE
Unable to extract title

### ISSUE THREAD

**Issue by RoboTehnik** [rg3/youtube-dl#7600]
K:\5800\download>youtube-dl.exe --verbose -f mp4 --username XXX@gmail.com --password XXX https://www.youtube.com/feed/watch_later
Waiting for file handle to be closed ...
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-f', u'mp4', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://www.you
tube.com/feed/watch_later']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.11.13
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Logging in
[youtube:watchlater] WL: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version;
type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1933, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 1619, in _extract_playlist
  File "youtube_dl\extractor\common.pyo", line 593, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 584, in _search_regex
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the lat
est version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
