### ISSUE TITLE
videomega.tv is broken

### ISSUE THREAD

**Issue by myvidster** [rg3/youtube-dl#7606]
For videomega.tv a 100Kb file is downloaded and not the actual video.

# /usr/local/bin/youtube-dl -o /root/tmp/debug.mp4 http://videomega.tv/?ref=83yVRkJym44myJkRVy38 
[VideoMega] 83yVRkJym44myJkRVy38: Downloading webpage
[download] Destination: /root/tmp/debug.mp4
[download] 100% of 103.59KiB in 00:00

**Comment by alex-krestin** [comment]
Videomega encrypts link to real video file. I don't know how it can be bypassed in python, but in JS you need first extract eval function from videomega iframe page and then run it to get real link.

```
var webpage = ... ;                     // load iframe html

var regex = /(eval[^<]+)/;              // create regex
var str = regex.exec(webpage)[1];       // extract eval function
str = str.replace(/\$\("\d"\).\d/, ""); // replace jquery reference in code 
                                        // (otherwise we will get an error)

var res = eval(str);                    // evaluate extracted function

console.log(res);                       // show link to download ^_^
```

**Comment by myvidster** [comment]
I decoded the mp4 found in the eval function and the video still will not download.

eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('$("5").6("4","3://0.1.2.7/8/d.e?c=b&9=a-f");',16,16,'ab1|cdn|vizplay|http|src|video|attr|org|v|hash|0eOZNdBc9Q|OqWQxdqzJoKTxFx8E7Y0PQ|st|fb2ffbadf624a7cca80efd808f7747c2|mp4|476ZsZ5u7Tw'.split('|'),0,{}))


http://ab1.cdn.vizplay.org/v/fb2ffbadf624a7cca80efd808f7747c2.mp4?st=OqWQxdqzJoKTxFx8E7Y0PQ&hash=0eOZNdBc9Q-476ZsZ5u7Tw

**Comment by alex-krestin** [comment]
Con you post here original link from where

**Comment by myvidster** [comment]
Here you go.

http://videomega.tv/?ref=83yVRkJym44myJkRVy38

**Comment by alex-krestin** [comment]
Perfectly downloaded by my script. I'm currently develop an addon for Mozilla Firefox so the syntax is a little different than the clear JS. You need to do this steps to get a link:

```javascript
// 1) load original page html 
var content = ... ; 
// 2) extract valid link 
var videomegaUrlRegex = /(https?:\/\/(www\.)?videomega\.tv\/(view|iframe|cdn)\.php\?ref=([A-Za-z0-9]+))/;
var iframeUrl = videomegaUrlRegex.exec(content)[1];
// 3) send GET request to this link with next header (the site isn't important):
headers: { "Referer": "http://google.com/"},
// 4) get response html and extract eval expression
var iframeHtml = ...;
var regex = /(eval[^<]+)/;
var str = regex.exec(iframeHtml )[1];
str = str.replace(/\$\("\d"\).\d/, ""); // replace jquery reference
// 5) evaluate this string to get a download link
var downloadLink =  eval(str);
// 5) do something with this link
```

**Comment by myvidster** [comment]
Interesting, my download link works in Firefox and not in Chrome.  Before I was using chrome to download the url.  With that said, the URL is bound to the IP so I converted the code to php and attempted to fetch and pipe the download from my dev server with no luck.  Hopefully someone can fix youtube-dl.

**Comment by alex-krestin** [comment]
Chrome opens link as a media and you need to press Ctrl + S to download file.

**Comment by myvidster** [comment]
Great tip!  Is anyone working on fixing youtube-dl, it still only downloads a 100kbs file.

**Comment by Tek9x** [comment]
when i try to get the info , it gives me the black video that sounds like people in the backround and not the url link , i can get the url of the video in c# if i sniff http and grab it there but i am trying to do it all in python with youtube-dl. instead of grabbing the real link from c# and then download via python.

**Comment by alex-krestin** [comment]
I think it's not possible to do with youtube-dl unless developers didn't add dependency for PyExecJS or another library to evaluate JS expression. And I don't how it can be useful if only this site requires it.

**Comment by myvidster** [comment]
Other tube sites that uses JS eval.
powvideo.net
flashx.tv
videowood.tv

**Comment by Tek9x** [comment]
ok so this is really ugly but i took what alex said and put it into python and came up with 

    import requests
    import re
    import js2py

    header = {"Referer": "http://google.com/"}

    videomegaUrlRegex = '(https?:\/\/(www\.)?videomega\.tv\/(view|iframe|cdn)\.php\?ref=([A-Za-z0-9]+))'
    e = '(eval[^<]+)'
    web = requests.get('http://www.wtso.cc/video/vip/1118/eng/season_7_episode_4_bart_sells_his_soul')
    link = re.findall(videomegaUrlRegex, web.content)[0]
    p = link[0]
    print p

    web2 = requests.get(p, headers=header)
    q = re.findall(e, web2.content)[0]

    print q

    rep = '(\$\("\d"\).\d)'

    pel = re.sub(rep,'',q)

    test2 = js2py.eval_js(pel)

    print test2


it works perfectly , thank you alex for making me teach myself , this code is quick and dirty so all by means feel free to clean it up.

**Comment by dban0001** [comment]
Can someone add this to youtube-dl with a pull request?

**Comment by viewbowl** [comment]
I highly recommend Allavsoft to Download VideoMega Videos to MP4, WMV, AVI, FLV, MOV, etc on Mac or Windows.You may find it at 

http://www.allavsoft.com/how-to/videomega-downloader.html

**Comment by yan12125** [comment]
Videomega, at least http://videomega.tv/?ref=83yVRkJym44myJkRVy38, uses the same obfuscation technique as [iQiyi](https://github.com/rg3/youtube-dl/blob/e26cde092736c3356c1ab76c899a180fb3441d4b/youtube_dl/extractor/iqiyi.py#L144-L162). It can be handled with pure Python. It's not a good idea to use external libraries, especially dangerous ```eval()```.

**Comment by yan12125** [comment]
This site will work again in the next version. Thanks everyone that provides ideas.

**Comment by wahiba2** [comment]
i have the same problem on [streaming film](http://www.film-vf.stream/)
when click play sow me 404 not found

**Comment by yan12125** [comment]
@wahiba2 Please open a new issue and paste a concrete video URL instead of the homepage of a website.
