### ISSUE TITLE
youtube-dl not working on Fedora23

### ISSUE THREAD

**Issue by timloyd** [rg3/youtube-dl#7609]
Hi, since migrating to F23 (same problem in F22) I have not been able to use youtube-dl. I am using Gnome Classic as my desktop environment and I get the following message:

[tim@dragon ~]$ youtube-dl https://www.youtube.com/watch?v=WMPM1q_Uyxc
[youtube] WMPM1q_Uyxc: Downloading webpage
[youtube] WMPM1q_Uyxc: Downloading video info webpage
[youtube] WMPM1q_Uyxc: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 771, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 663, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflCIicNM/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflCIicNM/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by timloyd** [comment]
okay thanks. I have the latest version from the Fedora repo. I might 
first enquire why Fedora is lagging behind the latest

Regards
