### ISSUE TITLE
pornhd is now broken

### ISSUE THREAD

**Issue by arunsai123** [rg3/youtube-dl#7612]
**verbose output** 
laptop:~/Private$ youtube-dl  -g --batch-file=pornhd -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-g', u'--batch-file=pornhd', u'-v']
[debug] Batch file urls: [u'http://www.pornhd.com/videos/11431/busty-mom-sara-jay-gets-facialized-hd-porn-video', u'http://www.pornhd.com/videos/11552/blonde-brooke-wylde-gets-big-tits-fucked-hd-porn-video', u'http://www.pornhd.com/videos/18855/ripped-pantyhose-is-what-she-wants-hd-porn-video', u'http://www.pornhd.com/videos/19319/fucking-her-stepdad-hd-porn-movie', u'http://www.pornhd.com/videos/23972/sexy-blonde-milf-alix-lynx-gets-fucked-hd-porn-movie', u'http://www.pornhd.com/videos/24768/sweet-blonde-elsa-jean-yearns-for-her-first-bbc-hd-porn-movie', u'http://www.pornhd.com/videos/24943/busty-mexican-babe-fucking-her-masseur-hd-porn-movie', u'http://www.pornhd.com/videos/25098/hot-babe-with-huge-tits-strips-naked-hd-porn-movie']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2015.11.21
[debug] Python version 2.7.6 - Linux-3.19.0-28-generic-i686-with-elementary_OS-0.3.1-freya
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhd.py", line 39, in _real_extract
    r'<title>(.+) porn HD.+?</title>', webpage, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl.

**Comment by phihag** [comment]
Thank you for the report. I believe this issue to be fixed in youtube-dl 2015.11.23 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
