### ISSUE TITLE
cbsnews parse/download is not working

### ISSUE THREAD

**Issue by chrisdamato** [rg3/youtube-dl#7615]
Using version 2015-11-23, trying to capture video of niece on TV.

    $ youtube-dl http://www.cbsnews.com/videos/why-do-we-like-the-foods-we-like
    [debug] System config: [u'--prefer-free-formats']
    [debug] User config: []
    [debug] Command-line args: [u'http://www.cbsnews.com/videos/why-do-we-like-the-foods-we-like', u'--verbose']
    [debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
    [debug] youtube-dl version 2015.11.23
    [debug] Python version 2.7.5 - Linux-3.19.8-100.fc20.x86_64-x86_64-with-fedora-20-Heisenbug
    [debug] exe versions: ffmpeg 2.1.8, ffprobe 2.1.8
    [debug] Proxy map: {}
    [CBSNews] why-do-we-like-the-foods-we-like: Downloading webpage
    [debug] Invoking downloader on u'{manifest:none}rtmp://cp98363.edgefcs.net/ondemand/?auth=cbs&aifp=v001&slist={slistPrefix}{break}{slistFilePath}media/2015/11/22/572131907744/sunmo_taste_1122_469594_796.mp4{slistFilePath}{manifest:f4m}http://cbsnews-vh.akamaihd.net/z/{slist::true:false}.csmil/manifest.f4m{manifest:m3u}http://cbsnews-vh.akamaihd.net/i/{slist::true:false}.csmil/master.m3u8{manifest}'
    ERROR: unable to download video data: <urlopen error unknown url type: {manifest>
    Traceback (most recent call last):
      File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1601, in process_info
        success = dl(filename, info_dict)
      File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1543, in dl
        return fd.download(name, info)
      File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
        return self.real_download(filename, info_dict)
      File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
        data = self.ydl.urlopen(request)
      File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1878, in urlopen
        return self._opener.open(req, timeout=self._socket_timeout)
      File "/usr/lib64/python2.7/urllib2.py", line 404, in open
        response = self._open(req, data)
      File "/usr/lib64/python2.7/urllib2.py", line 427, in _open
        'unknown_open', req)
      File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "/usr/lib64/python2.7/urllib2.py", line 1249, in unknown_open
        raise URLError('unknown url type: %s' % type)
    URLError: <urlopen error unknown url type: {manifest>

Thanks

**Comment by kelciour** [comment]
Try^

**Comment by kelciour** [comment]
This is working for me:
```
youtube-dl -f RtmpMobileHigh http://www.cbsnews.com/videos/why-do-we-like-the-foods-we-like
```

**Comment by remitamine** [comment]
this will be fixed in the next version.

**Comment by sarah369** [comment]
Dr Miracle is a real spell caster, he is so powerful, unique, and amazing. Dr Miracle restored happiness to my life again by bringing my husband back to me with his powers. Dr Miracle is a gifted and a very powerful good man and if not for him what would my life turn to? Dr Miracle may your good gods continue to bless you for your good deeds. Dr Miracle words can not express how much good you have done for me and i believe that even a thousand words won't be enough to describe your good great works. If you are facing any spiritual problem i advice you not to cry just contact Dr Miracle on his email or and his web site and he will solve all your problems. Contact him on his email:
homeoflightandsolution@yahoo.com  and this is his website: http://homeoflightandsolution.webs.com/  contact him and get your solution now. Thank you Dr Miracle for you are indeed miraculous.

**Comment by sarah369** [comment]
Dr Miracle is a real spell caster, he is so powerful, unique, and amazing. Dr Miracle restored happiness to my life again by bringing my husband back to me with his powers. Dr Miracle is a gifted and a very powerful good man and if not for him what would my life turn to? Dr Miracle may your good gods continue to bless you for your good deeds. Dr Miracle words can not express how much good you have done for me and i believe that even a thousand words won't be enough to describe your good great works. If you are facing any spiritual problem i advice you not to cry just contact Dr Miracle on his email or and his web site and he will solve all your problems. Contact him on his email:
homeoflightandsolution@yahoo.com  and this is his website: http://homeoflightandsolution.webs.com/  contact him and get your solution now. Thank you Dr Miracle for you are indeed miraculous.
