### ISSUE TITLE
iprima: ERROR: Unable to extract zoneGEO

### ISSUE THREAD

**Issue by jpirko** [rg3/youtube-dl#7617]
$ youtube-dl http://play.iprima.cz/particka-113 --verbose                                                   
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'http://play.iprima.cz/particka-113', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.16
[debug] Python version 2.7.10 - Linux-4.2.5-201.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: ffmpeg 2.6.4, ffprobe 2.6.4, rtmpdump 2.4
[debug] Proxy map: {}
[IPrima] particka-113: Downloading webpage
[IPrima] particka-113: Downloading webpage
ERROR: Unable to extract zoneGEO; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/iprima.py", line 70, in _real_extract
    zoneGEO = self._html_search_regex(r'"zoneGEO":(.+?),', webpage, 'zoneGEO')
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract zoneGEO; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kibeb** [comment]
Same error even with the latest youtube-dl version 2015.12.13:

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://play.iprima.cz/particka/particka-92']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-70411-g7da7d26, rtmpdump 2.3
[debug] Proxy map: {}
[IPrima] particka-92: Downloading webpage
[IPrima] particka-92: Downloading webpage
ERROR: Unable to extract zoneGEO; please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --
verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\iprima.pyo", line 68, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 593, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 584, in _search_regex
RegexNotFoundError: Unable to extract zoneGEO; please report this issue on https://yt-dl.org/bug . M
ake sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-d
l with the --verbose flag and include its complete output.
```

There was a major redesign of the play.iprima.cz website in the last 3 days IMHO. Before that youtube-dl version 2015.09.09 worked just fine with it.

TIA.

**Comment by kibeb** [comment]
Is there something I could do to help solve this problem with iprima? I mean, not being able to code the fix myself, unfortunately...
Thanks in advance.
