### ISSUE TITLE
Nuvid gets stuck

### ISSUE THREAD

**Issue by arisboch** [rg3/youtube-dl#7620]
I downloaded the newest copy of youtube-dl coupla seconds age and when I use the browser, the video seems to work, but when I try to use youtube-dl, it simply gets "stuck". Here's the output of the program, hope it'll help:

stderr:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.nuvid.com/video/963818/night-club-exploding-in-male-stripper-bj-action']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2015.11.23
[debug] Python version 2.7.6 - Linux-3.16.0-38-generic-x86_64-with-LinuxMint-17.2-rafaela
[debug] exe versions: avconv 12_dev0-6, avprobe 12_dev0-6, ffmpeg N-76045-g97be5d4, ffprobe N-76045-g97be5d4
[debug] Proxy map: {}

ERROR: Interrupted by user

stdout:
[Nuvid] 963818: Downloading 3gp page

**Comment by yan12125** [comment]
Sorry for the late response. Nuvid will be fixed in the next version.
