### ISSUE TITLE
Vevo Region Issue

### ISSUE THREAD

**Issue by g8keepa** [rg3/youtube-dl#7628]
I'm trying to extract the following link:

http://www.vevo.com/watch/soul-for-real/If-You-Want-It/USUV70502689

It's on VEVO UK, I have a DNS service running (to get around the geo-blocking).  The link plays in any browser when I have my DNS enabled, but when I attempt to use youtube-dl in terminal I get:

ERROR: Vevo said: People who live where you live aren't allowed to watch this video. Not because we don't luv ya, but because the owners have some restrictions. The good news, is there are tens of thousands of other videos to choose from...

Does youtube-dl re-direct from another site that messes up the DNS?  Is there a way around this?  I've tried just enabling the DNS on the computer only, I've tried enabling it from the router end.  In both scenarios the video plays in Chrome/Safari, but it gives the same error message when I attempt an extract.

**Comment by jaimeMF** [comment]
[Post the full output you get with the --verbose option](https://github.com/rg3/youtube-dl/blob/032f2f260f7ef7a04d1499b26b97c1643fe993b0/README.md#bugs).

> Does youtube-dl re-direct from another site that messes up the DNS?

You can check [the `vevo.py` file](https://github.com/rg3/youtube-dl/blob/3d460ebdce6ef085e615e804edb8128890a1cd74/youtube_dl/extractor/vevo.py) to see if that's the case, we replicate what browsers do.

Note that I don't completely understand how you can avoid geoblocking with a different DNS, can't they just get your IP and block based on that?

**Comment by g8keepa** [comment]
Solved it with my DNS service lol.
