### ISSUE TITLE
Support for hotstar.com 

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#7630]
Hi all,  

Would be nice if there was a  way to support for hotstar.com . It is a streaming service just like youtube.com for Asian Sub-continent and is part of Star Network.

**Comment by jaimeMF** [comment]
[Post an example url](https://github.com/rg3/youtube-dl/blob/7689413e42334ff79e671a4c90869077e9f9835b/README.md#bugs).

**Comment by shirishag75** [comment]
Here  you go - 

http://www.hotstar.com/#!/sumit-sambhal-lega-5067/when-sumit-first-met-maya-1000077191-e

This is from the comedy series sumit sambhal lega.  I needed to register to the site to extract the URL. There are many hindi syndicated shows out there so would be useful to one and all.

**Comment by azadi** [comment]
Just to clarify: one doesn't need to register on the site to extract the URL. (Confirmed this before posting the comment.)

**Comment by siddht1** [comment]
yes  its   possible    as the foloowing code  needs  to be parsed  
 <object id="AVSFlashPlayer" name="AVSFlashPlayer" align="middle" width="952" height="536" type="application/x-shockwave-flash"
data="player/AVSFlashPlayer.swf?release=2.3.73d3b1e52c69806436dfcbed4a814522e6b8f903_25_Nov_v4">
<param name="quality" value="high">


for which  a   web fetch request ,with the link grabber  is required ,  we also need to check for  the param value for the quality to be high  as the site fetches data  differently for different platforms , devices etc   (confirmed by changing the useragent, used  different browser for android device in android , also processed the packet   data received by the hotstar app for android (used wireshark  ,Pc as Acess point)) .  Will  start to work on the code  asap.

**Comment by siddht1** [comment]
object id="AVSFlashPlayer" name="AVSFlashPlayer" align="middle" width="952" height="536" type="application/x-shockwave-flash"
 data="player/AVSFlashPlayer.swf?release=2.3.73d3b1e52c69806436dfcbed4a814522e6b8f903_25_Nov_v4">
param name="quality" value="high"

**Comment by siddht1** [comment]
By the way   simply download the video using this code in any download manager  till  the codes are  complete      http://www.hotstar.com/player/AVSFlashPlayer.swf?release=2.3.73d3b1e52c69806436dfcbed4a814522e6b8f903_25_Nov_v4

**Comment by shirishag75** [comment]
That doesn't work, or at least trying wget doesn't get me anywhere :-

        [$] wget http://www.hotstar.com/player/AVSFlashPlayer.swf\?release\=2.3.73d3b1e52c69806436dfcbed4a814522e6b8f903_25_Nov_v4          
    --2015-12-25 01:06:04--  http://www.hotstar.com/player/AVSFlashPlayer.swf?release=2.3.73d3b1e52c69806436dfcbed4a814522e6b8f903_25_Nov_v4
    Resolving www.hotstar.com (www.hotstar.com)... 117.239.240.8, 117.239.240.50
    Connecting to www.hotstar.com (www.hotstar.com)|117.239.240.8|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 435535 (425K) [application/x-shockwave-flash]
    Saving to: ‘AVSFlashPlayer.swf?release=2.3.73d3b1e52c69806436dfcbed4a814522e6b8f903_25_Nov_v4’
    
    AVSFlashPlayer.swf?release=2.3.73d3 100%[===================================================================>] 425.33K   176KB/s    in 2.4s    
    
    2015-12-25 01:06:07 (176 KB/s) - ‘AVSFlashPlayer.swf?release=2.3.73d3b1e52c69806436dfcbed4a814522e6b8f903_25_Nov_v4’ saved [435535/435535]

**Comment by remitamine** [comment]
i added an initial support for this site, it will take effect in the next version.
i test only few videos(most of the content is geo restricted).
