### ISSUE TITLE
--get-url prints url two times

### ISSUE THREAD

**Issue by perkint** [rg3/youtube-dl#7631]
I frequently use youtube-dl like this:

  youtube-dl --get-url --get-filename 'https://www.youtube.com/watch?v=F_7S1eqKsFk'

I have a downloader script that parses the output.  For some reason, the URL is printed twice before printing the filename.  It never used to be that way.  This makes my script sad...

But I'm happy for youtube-dl!!!  Thanks and keep up the good work...    :^)

**Comment by dstftw** [comment]
This is expected. First one for `bestvideo` second for `bestaudio`.

**Comment by phihag** [comment]
You can pass in `-f best` and you'll get only one file, albeit in lower quality than the mix of the two files.
