### ISSUE TITLE
[Youtube] AttributeError / ExtractorError

### ISSUE THREAD

**Issue by jonatanhal** [rg3/youtube-dl#7632]
Hello

I tried downloading a video, but youtube-dl crashes, generating a AttributeError / ExtractorError-exception. My (uneducated) guess is that maybe youtube changed something, crippling the current extractor?

See the gist below for the traceback & thank you in advance!

https://gist.github.com/jonatanhal/c6d2ec444222bd16ff77

**Comment by jaimeMF** [comment]
It's fixed in version 2015.11.24, [read our FAQ](https://github.com/rg3/youtube-dl/blob/7689413e42334ff79e671a4c90869077e9f9835b/README.md#how-do-i-update-youtube-dl) for the update instructions.
