### ISSUE TITLE
RTMPE: YouTube

### ISSUE THREAD

**Issue by Klaus1189** [rg3/youtube-dl#7646]
Hi, how do I download this video?
https://www.youtube.com/watch?v=lTurfn7vvCk

I have downloaded rtmpdump-2.4-2013-12-22. What syntax do I need?

**Comment by phihag** [comment]
YouTube RTMPE downloads are not supported yet. For more information, see #343.

**Comment by Klaus1189** [comment]
Is rtmpe not rtmp?
