### ISSUE TITLE
Can play while downloading?

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#765]
Now I have to open file manager or another terminal to find the downloading .part file and play it with a player such as mplayer. 
Can I play the downloading video with mplayer in the youtube-dl command?
I try to type this command:
  youtube-dl http://youtube_url -f 43 | mplayer
It failed.
Can somebody help me?

**Comment by ashutosh2k12** [comment]
For now, I created a small bash script, which uses python program(unnecessary if you already have youtube-dl), and youtube-dl to pipe data to stdout. Please find the script here https://github.com/ashutosh2k12/ytdl-streamer
