### ISSUE TITLE
site request audi mediatv

### ISSUE THREAD

**Issue by johny1** [rg3/youtube-dl#7654]
Request for a site. Thanks.

https://audimedia.tv/de/cat/sport

C:\Users\I\Desktop\ytdl>youtube-dl https://audimedia.tv/de/vid/60-seconds-of-a
udi-sport-104-2015-wec-bahrain-rookie-test
[generic] 60-seconds-of-audi-sport-104-2015-wec-bahrain-rookie-test: Requesting
header
WARNING: Falling back on generic information extractor.
[generic] 60-seconds-of-audi-sport-104-2015-wec-bahrain-rookie-test: Downloading
 webpage
[generic] 60-seconds-of-audi-sport-104-2015-wec-bahrain-rookie-test: Extracting
information
ERROR: Unsupported URL: https://audimedia.tv/de/vid/60-seconds-of-audi-sport-104
-2015-wec-bahrain-rookie-test

C:\Users\I\Desktop\ytdl>youtube-dl -v https://audimedia.tv/de/vid/60-seconds-o
f-audi-sport-104-2015-wec-bahrain-rookie-test
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://audimedia.tv/de/vid/60-seconds-of-a
udi-sport-104-2015-wec-bahrain-rookie-test']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {'https': 'https://127.0.0.1:65213'}
[generic] 60-seconds-of-audi-sport-104-2015-wec-bahrain-rookie-test: Requesting
header
WARNING: Falling back on generic information extractor.
[generic] 60-seconds-of-audi-sport-104-2015-wec-bahrain-rookie-test: Downloading
 webpage
[generic] 60-seconds-of-audi-sport-104-2015-wec-bahrain-rookie-test: Extracting
information
ERROR: Unsupported URL: https://audimedia.tv/de/vid/60-seconds-of-audi-sport-104
-2015-wec-bahrain-rookie-test
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1282, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 17, column 54
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\generic.pyo", line 1887, in _real_extract
UnsupportedError: Unsupported URL: https://audimedia.tv/de/vid/60-seconds-of-aud
i-sport-104-2015-wec-bahrain-rookie-test

**Comment by siddht1** [comment]
https://audimedia.tv/de/vid/60-seconds-of-audi-sport-104-2015-wec-bahrain-rookie-test    is not supported by youtube-dll  ,  but if you want to download the video use the url      http://pmdvod.audimedia.edgesuite.net/AudiMediaTV/output/delivery/37/26/37262c92-dc34-41c3-aa59-707339bf7cf2/NA000RIJ_60sec_104_WEC_Bahrain_Rookie_2015_AMTV_de_8000k.mp4?download

**Comment by siddht1** [comment]
If you want to add support fot the above mention url   , you can create a video package extractor for youtube-dll

**Comment by johny1** [comment]
Thanks siddht1, I didn't see that video had a download button!

However, the main videos I'm interested on that page are the full race and they don't have a download button. Such as this one

https://audimedia.tv/de/vid/audi-sport-tt-cup-2015-finale-hockenheim-rennen-1
