### ISSUE TITLE
[rtve] Broken download on rtve.es:alacarta 

### ISSUE THREAD

**Issue by liloman** [rg3/youtube-dl#7657]
Hi guys.

> youtube-dl http://www.rtve.es/alacarta/videos/fabrica-de-ideas/fabrica-ideas-17-10-15/3326605/  --verbose 

[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'http://www.rtve.es/alacarta/videos/fabrica-de-ideas/fabrica-ideas-17-10-15/3326605/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.13
[debug] Python version 2.7.10 - Linux-4.2.5-201.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2
[debug] Proxy map: {}
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] 3326605: Downloading JSON metadata
[rtve.es:alacarta] 3326605: Downloading url information
[rtve.es:alacarta] 3326605: Getting video url

----
I'm in Spain and overall this module almost has never worked.
I think it will be great to create a test for this module.

By the way, great software I use it a lot and saved me plenty of time/headaches. ;)

**Comment by jaimeMF** [comment]
Thanks for the report, it's already fixed in the last version. See [our FAQ](https://github.com/rg3/youtube-dl/blob/7689413e42334ff79e671a4c90869077e9f9835b/README.md#how-do-i-update-youtube-dl) if you have any problem updating.

**Comment by liloman** [comment]
Thanks for the check. :)

I checked it and It works with the latest version. 
I'm going to wait for the latest release on my distro and meanwhile use your binary. :) 

Un saludo :)
