### ISSUE TITLE
Russia.TV site suddenly unavailable to d/l video

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#7665]
Hello author and contributors!

I have never met the problems with http://russia.tv to get videos from this site, but now I see the problem. Here is the log, please inspect the thing and reply back - is it youtube-dl problem or site problem, Thanks !
C:\temp>youtube-dl.exe -v http://russia.tv/video/show/brand_id/5402/episode_id/986443/video_id/998716/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://russia.tv/video/show/brand_id/5402/episode_id/986443/video_id/998716/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-76741-g8eadabf
[debug] Proxy map: {}
[generic] 998716: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 998716: Downloading webpage
[generic] 998716: Extracting information
[RUTV] 796047: Downloading JSON
[RUTV] 796047: Downloading m3u8 information
ERROR: Failed to download m3u8 information: '' (caused by BadStatusLine("''",));
 please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1878, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 691, in http_open
  File "urllib2.pyo", line 1200, in do_open
  File "httplib.pyo", line 1132, in getresponse
  File "httplib.pyo", line 453, in begin
  File "httplib.pyo", line 417, in _read_status

In other hand I am able to DL (almost?) all videos from the same site:
C:\temp>youtube-dl.exe http://russia.tv/video/show/brand_id/5402/episode_id/1253957/video_id/1412995/
[generic] 1412995: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1412995: Downloading webpage
[generic] 1412995: Extracting information
[RUTV] 1453641: Downloading JSON
[RUTV] 1453641: Downloading m3u8 information
[download] Destination: Вести. Эфир от 26.11.2015 (17_00)-1453641.mp4
ffmpeg version N-76741-g8eadabf Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 5.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55.  7.100 / 55.  7.100
  libavcodec     57. 15.100 / 57. 15.100
  libavformat    57. 16.100 / 57. 16.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 15.100 /  6. 15.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, hls,applehttp, from 'http://cdn.v.rtr-vesti.ru/_cdn_auth/secure/v/vh/vod_hls/definst/smil:vh/smil/001/412/995_d20151126184511.smil/chunklist_w423434632_b1800000_pd2962000.m3u8':
  Duration: 00:49:21.12, start: 0.000000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)
    Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720
[SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:2: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 129 kb/s
[mp4 @ 00000000039b00c0] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 00000000039b00c0] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to 'file:╨Т╨╡╤Б╤В╨╕. ╨н╤Д╨╕╤А ╨╛╤В 26.11.2015 (17_00)-1453641.mp4.part':
  Metadata:
    encoder         : Lavf57.16.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 129 kb/s

Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  481 fps=0.0 q=-1.0 size=    4666kB time=00:00:19.22 bitrate=1988.8kbits/
frame=  961 fps=805 q=-1.0 size=    9122kB time=00:00:38.42 bitrate=1944.9kbits/
...

Thanks in advance!

-t

**Comment by dstftw** [comment]
Works fine for me. Should be a temporary issue. Is it reproducible now?

**Comment by nmr50** [comment]
I found the problem point. To get video as usual it need to be added /viewtype/picture at the end of address, like :  http://russia.tv/video/show/brand_id/5402/episode_id/986443/video_id/998716/viewtype/picture. I will close issue now, thanks anyway !:)

**Comment by dstftw** [comment]
/viewtype/picture at the end does not affect extraction in any way.

**Comment by nmr50** [comment]
Strange... I ran 1st step again: youtube-dl.exe -v http://russia.tv/video/show/brand_id/5402/episode_id/986443/video_id/998716/ , and video starts downloading w/o problems.

**Comment by nmr50** [comment]
btw, I found something interesting. When I run youtube-dl --list-formats http://russia.tv/brand/show/brand_id/59967/ -- I get this 'unsupported' stuff again, yet when I visit this url - video itself is NOT available, only screenshots are listed.
Adding "viewtype/picture" to the url I get list of all supported formats and one of them is hls-1800 (720p) - hooray, I discovered the hidden way to get videos from the russia.tv site b4 they officially post it to the public ;)
