### ISSUE TITLE
Support for EvilAngel.com, Pervcity.com, everythingbutt.com, gachinco.com, heydouga.com

### ISSUE THREAD

**Issue by laichiaheng** [rg3/youtube-dl#7668]
So many porn sites!!
If the trailers could be watched with youtube-dl, that would be great.

example:
http://www.evilangel.com/en/video/Perv-City-University-Anal-Majors-Scene-01/79601

http://www.pervcity.com/scenes/kate-england.html

http://www.everythingbutt.com/site/shoot/39234-Berretta-James-is-Trapped-in-Aiden-Starrs-Spill-room.html

http://www.gachinco.com/moviepages/ppv/1061/index.html

http://www.heydouga.com/moviepages/4030/1772/index.html

**Comment by yan12125** [comment]
Don't include multiple site requests in a single issue. Please open separate ones for them.
