### ISSUE TITLE
--list-formats can't be used alone

### ISSUE THREAD

**Issue by rptb1** [rg3/youtube-dl#7669]
Version 2015.11.21 on OS X 10.9.5 installed using MacPorts.

The man page says “You can get the list  of  avail-able  formats using --list-formats”, but:
> $ youtube-dl --list-formats
> Usage: youtube-dl [OPTIONS] URL [URL...]
>
> youtube-dl: error: You must provide at least one URL.
> Type youtube-dl --help to see a list of all options.

It does work if you specify a valid URL of a video, but you can't *just* list the formats.

Thanks.

**Comment by yan12125** [comment]
The description is updated. Thanks for discovering that.
