### ISSUE TITLE
Archive Channel Feature Request.

### ISSUE THREAD

**Issue by ZizzyDizzyMC** [rg3/youtube-dl#7672]
Hello. I am using this tool to archive channels from YouTube in the case a person decides to erase the channel from history. 

Many of these channels have videos that are important to my friends as well as myself.  So we're archiving like mad right now.

Currently the method of archiving a channel for us is using a tool to get a list of all youtube videos on a channel. (A list of URLs) We then copy this list and put them into a text file on our server(s). We use that as a batch file for a single channel.

I personally would love to skip this step all together and just be able to grab all the videos from a channel with a single flag.

Used as a flag, --channel "https://youtube/user/username"
Supporting username or channel ID / Name
The flag can be anything you want it to be. You choose. I just think it would be a lot faster to do this archiving with a single channel URL rather than having to maintain batch url files for each channel.  (I don't want to lump channels together)

What I'm using now for a script.

```

screen -dmS VideoArchive youtube-dl -a "/home/zizzydizzymc/archive/videolists/${1}.txt" -o "/home/zizzydizzymc/archive/ponyartistandmusicianarchive/${1}/%(title)s-%(uploader)s-%(upload_date)s-%(extractor)s-%(resolution)s.%(ext)s" --write-all-thumbnails -f bestvideo+bestaudio/best --sleep -interval 30 --download-archive "/home/zizzydizzymc/archive/archivelists/${1}-archivelist.txt" -r "8M" -i --prefer-ffmpeg --restrict-filenames
```

Called at console with ./archive.sh 'ArtistName' and it selects the video list I've created and placed in the videolists folder.

I would like to have a video list of the channel saved to the download archive list. That way I can update channel archives by re-running the tool.

Thank you for reading and have a good day.

**Comment by phihag** [comment]
You can already do
```
youtube-dl "https://youtube/user/username"
```
Is that what you want? If not, why not?

**Comment by ZizzyDizzyMC** [comment]
I had no idea it could do that. I will try it soon and post back if it works.

**Comment by ZizzyDizzyMC** [comment]
Seems to work like a charm! I never knew that. Thanks.
