### ISSUE TITLE
download multiple camera angle videos

### ISSUE THREAD

**Issue by beta2k** [rg3/youtube-dl#7675]
Youtube offers the possibility to do live streams with multiple camera angles. while the live stream is on, users can then choose between different angles.

If such a live stream is stored as a video afterwards, users again can choose one of the camera angles while watching the video. I would like to download each of the camera angles as a separate video, but youtube-dl doesn't allow to do that. I can only download the first/default camera stream.

One example of such a multi-camera angle video is this one: https://www.youtube.com/watch?v=WMCIdxt-tF0

Is it possible to implement a feature which allows for downloading each camera angle?

**Comment by dstftw** [comment]
youtube-dl does support multifeed videos for a long time already. You are using an outdated version.
```
> youtube-dl https://www.youtube.com/watch?v=WMCIdxt-tF0 --skip-download
[youtube] WMCIdxt-tF0: Downloading webpage
[youtube] WMCIdxt-tF0: Downloading video info webpage
[youtube] Downloading multifeed video (WMCIdxt-tF0, DZj-S5kRO7g) - add --no-playlist to just download video WMCIdxt-tF0
[download] Downloading playlist: Swiss International Finals
[youtube] playlist Swiss International Finals: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[youtube] WMCIdxt-tF0: Downloading webpage
[youtube] WMCIdxt-tF0: Downloading video info webpage
[youtube] WMCIdxt-tF0: Extracting video information
[youtube] WMCIdxt-tF0: Downloading DASH manifest
[youtube] WMCIdxt-tF0: Downloading DASH manifest
[download] Downloading video 2 of 2
[youtube] DZj-S5kRO7g: Downloading webpage
[youtube] DZj-S5kRO7g: Downloading video info webpage
[youtube] DZj-S5kRO7g: Extracting video information
[youtube] DZj-S5kRO7g: Downloading DASH manifest
[youtube] DZj-S5kRO7g: Downloading DASH manifest
[download] Finished downloading playlist: Swiss International Finals
```
