### ISSUE TITLE
Options not applying when downloading an entire channel

### ISSUE THREAD

**Issue by DiamondKing099** [rg3/youtube-dl#7676]
I'm trying to download every video on a channel as audio with -f bestaudio. However, when I apply -f bestaudio to an entire channel it does not download the correct format. If I download them individually it works just fine.

Here's my output with -v: http://pastebin.com/HDuix28k

**Comment by dstftw** [comment]
According to the log provided youtube-dl behavior is correct and both downloaded videos are `bestaudio`.
First file is `-eC9snfGpJY`. `bestaudio` is:
```
171          webm       audio only DASH audio  154k , vorbis@128k (44100Hz), **2.99MiB**
```
downloaded file is exactly `bestaudio`.
```
[download] Destination: Tobu & Itro - Fantasy--eC9snfGpJY.webm
[download] 100% of **2.99MiB** in 00:07
```
Same for the second file.
