### ISSUE TITLE
downloads only meta file on 3sat Mediathek

### ISSUE THREAD

**Issue by mcnesium** [rg3/youtube-dl#7680]
It only downloads some meta file with an RTMP URL in it:

    mcnesium@mcobst:~/Downloads$ youtube-dl -v "http://www.3sat.de/mediathek/?obj=55586"
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'-v', u'http://www.3sat.de/mediathek/?obj=55586']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.11.24
    [debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
    [debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2, rtmpdump 2.4
    [debug] Proxy map: {}
    [3sat] 55586: Downloading video details
    [debug] Invoking downloader on u'http://fstreaming.zdf.de/3sat/hd/15/11/151127_wohlstand_ard.meta'
    [download] Destination: Wohlstand für alle-55586.meta
    [download] 100% of 172.00B in 00:00
    mcnesium@mcobst:~/Downloads$ ll -h "Wohlstand für alle-55586.meta"
    -rw-r--r-- 1 mcnesium staff 172 Nov 23 15:39 Wohlstand für alle-55586.meta
    mcnesium@mcobst:~/Downloads$ cat Wohlstand\ für\ alle-55586.meta
    <metafile version="1.0">
      <default-stream-url>rtmp://cp125301.edgefcs.net/ondemand/mp4:3sat/15/11/151127_wohlstand_ard_3256k_p15v12.mp4</default-stream-url>
    </metafile>

**Comment by akirk** [comment]
In fact it seems that just a not very useful format is ranked top. You can get a list of videos with `-F` and then select the best version with `-f <versionname>`
