### ISSUE TITLE
Error Listing Formats and Download Youtube Videos

### ISSUE THREAD

**Issue by mtalhaakram** [rg3/youtube-dl#7683]
Hello,
      I have shifted my server to new data centre and install latest version of youtube-dl on it while python version is 2.6. When I am trying to run command for youtube, m getting error:

root@server [~]# youtube-dl -v --list-formats http://www.youtube.com/watch?v=Hp1-XBdAyz8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--list-formats', u'http://www.youtube.com/watch?v=Hp1-XBdAyz8']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.6.6 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-centos-6.7-Final
[debug] exe versions: ffmpeg N-76822-g12a419d-syslint
[debug] Proxy map: {}
[youtube] Hp1-XBdAyz8: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 329, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1878, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Please advise what could be possible reason behind it. 

Thanks & Regards,
Talha

**Comment by dstftw** [comment]
This is not a youtube-dl issue and has been discussed a lot. You may want to read [FAQ entry on the issue](https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required) and [this discussion](https://github.com/rg3/youtube-dl/issues/5138).
