### ISSUE TITLE
Unsupported URL

### ISSUE THREAD

**Issue by pjpd** [rg3/youtube-dl#7694]
youtube-dl ver 2015.11.27.1
python ver 3.5
mac 10.11.1

ERROR: Unsupported URL: https://www.youtube.com/watch?feature=player_embedded&amp;amp;v=V36LpHqtcDY

Used quotes as directed.

**Comment by dstftw** [comment]
Will be fixed in the next version. Yet you can remove `amp;amp;` to download.

**Comment by pjpd** [comment]
Thanks for the response! And for working on this. It's truly wonderful.
