### ISSUE TITLE
Vodlocker Embed - Fails to download video

### ISSUE THREAD

**Issue by OrbitalDan** [rg3/youtube-dl#7696]
The following trace occurred:

[debug] User config: []
[debug] Command-line args: [u'-o', u'test', 
u'http://vodlocker.com/embed-s7qozzeclum2-620x360.html', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-50911-g9efcfbe
[debug] Proxy map: {}
[Vodlocker] embed: Downloading webpage
ERROR: An extractor error has occured. (caused by KeyError(u'op',)); please 
report this issue on https://yt-dl.org/bug . Make sure you are using the latest 
version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the 
--verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\common.pyo", line 291, in extract
  File "youtube_dl\extractor\vodlocker.pyo", line 31, in _real_extract
KeyError: u'op'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 297, in extract
ExtractorError: An extractor error has occured. (caused by KeyError(u'op',)); 
please report this issue on https://yt-dl.org/bug . Make sure you are using the 
latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with 
the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
>This file was deleted

**Comment by OrbitalDan** [comment]
Thanks!  :)
