### ISSUE TITLE
new site: islamicinvitationturkey.com (Error: 403 forbidden)

### ISSUE THREAD

**Issue by zenaan** [rg3/youtube-dl#7701]
$ youtube-dl --verbose http://www.islamicinvitationturkey.com/2015/11/25/watch-yemen-hezbollahs-missile-rain-on-enemy-of-islam-zionist-servant-saudi-soldiers/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--prefer-ffmpeg', u'--verbose', u'http://www.islamicinvitationturkey.com/2015/11/25/watch-yemen-hezbollahs-missile-rain-on-enemy-of-islam-zionist-servant-saudi-soldiers/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.9 - Linux-4.1.0-0.bpo.2-rt-amd64-x86_64-with-debian-8.2
[debug] exe versions: avconv 2.6.2, avprobe 2.6.2, ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] watch-yemen-hezbollahs-missile-rain-on-enemy-of-islam-zionist-servant-saudi-soldiers: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch-yemen-hezbollahs-missile-rain-on-enemy-of-islam-zionist-servant-saudi-soldiers: Downloading webpage
[generic] watch-yemen-hezbollahs-missile-rain-on-enemy-of-islam-zionist-servant-saudi-soldiers: Extracting information
[debug] Invoking downloader on u'http://islamicinvitationturkey.com/video/12287698_912149195489135_1669201499_n.mp4?_=1'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/justa/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1601, in process_info
    success = dl(filename, info_dict)
  File "/home/justa/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1543, in dl
    return fd.download(name, info)
  File "/home/justa/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/home/justa/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/home/justa/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1878, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by remitamine** [comment]
i think it's a temporary error in the server.
```
youtube-dl http://www.islamicinvitationturkey.com/2015/11/25/watch-yemen-hezbollahs-missile-rain-on-enemy-of-islam-zionist-servant-saudi-soldiers/
[generic] watch-yemen-hezbollahs-missile-rain-on-enemy-of-islam-zionist-servant-saudi-soldiers: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch-yemen-hezbollahs-missile-rain-on-enemy-of-islam-zionist-servant-saudi-soldiers: Downloading webpage
[generic] watch-yemen-hezbollahs-missile-rain-on-enemy-of-islam-zionist-servant-saudi-soldiers: Extracting information
[download] Destination: WATCH Yemen Hezbollah’s Missile Rain on Enemy of Islam zionist Servant Saudi Soldiers! _ Islamic Invitation Turkey-12287698_912149195489135_1669201499_n.mp4
[#57fd06 1.1MiB/1.1MiB(98%) CN:1 DL:26KiB]                                     
01/08 14:41:26 [NOTICE] Download complete: /home/amine/youtube-dl/WATCH Yemen Hezbollah’s Missile Rain on Enemy of Islam zionist Servant Saudi Soldiers! _ Islamic Invitation Turkey-12287698_912149195489135_1669201499_n.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
57fd06|OK  |    21KiB/s|/home/amine/youtube-dl/WATCH Yemen Hezbollah’s Missile Rain on Enemy of Islam zionist Servant Saudi Soldiers! _ Islamic Invitation Turkey-12287698_912149195489135_1669201499_n.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 1249364 bytes
[download] 100% of 1.19MiB
```
