### ISSUE TITLE
404 Forbidden

### ISSUE THREAD

**Issue by AsepSow** [rg3/youtube-dl#7702]
I just try to youtube-dl, I found something strange, is there ever experienced what I experienced.

I try this:
      youtube-dl --verbose https://www.youtube.com/watch?v=-Cu0ihE490s

Response:
      [debug] System config: [] 
    [debug] User config: []
    [debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=-Cu0ihE490s']
    [debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968 
    [debug] youtube-dl version 2015.11.27.1 
    [debug] Python version 2.6.6 - Linux-2.6.32-042stab103.6-x86_64-with-centos-6.7-Final 
    [debug] exe versions: none 
    [debug] Proxy map: {} 
    [youtube] -Cu0ihE490s: Downloading webpage
    [youtube] -Cu0ihE490s: Downloading video info webpage 
    [youtube] -Cu0ihE490s: Extracting video information
    [youtube] -Cu0ihE490s: Downloading DASH manifest
    [youtube] -Cu0ihE490s: Downloading DASH manifest 
    [debug] Invoking downloader on u'https://r5---sn-a5m7znez.googlevideo.com/videoplayback?
ms=au&mt=1448847853&mv=u&lmt=1448542046072724&dur=239.095&mm=31&mn=sn-a5m7znez&sparams=dur%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9408710%2C9416126%2C9416778%2C9416851%2C9417683%2C9418203%2C9418401%2C9418750%2C9419445%2C9420452%2C9421525%2C9421734%2C9422436%2C9422596%2C9422618%2C9423242%2C9423662%2C9423717%2C9424620%2C9424965%
2C9424987&expire=1448869722&itag=22&mime=video%2Fmp4&ip=198.96.90.184&source=youtube&pl=25&requiressl=yes&sver=3&signature=B83F33C8D99568E634F9575A95F3A7E7C80366E3.92988044A431E19ACCB10D97283B76F1805D0F12&ratebypass=yes&id=o-AOFfqtnsqi0xFDtpwt8hA6eHFIcTI4rV-28Fa_sxXBmJ&upn=xGA-RblnD8o&ipbits=0&gcr=cn&key=yt6'
    [download] Destination: Isyana Sarasvati - Kau Adalah (feat. Rayi Putra)--Cu0ihE490s.mp4 
    [download] 0.0% of 34.75MiB at Unknown speed ETA Unknown ETA 
    [download] 0.0% of 34.75MiB at 2.92MiB/s ETA 00:12 
    [download] 0.0% of 34.75MiB at 5.54MiB/s ETA 00:06 
    [download] 0.0% of 34.75MiB at 9.87MiB/s ETA 00:03 
    [download] 0.1% of 34.75MiB at 12.57MiB/s ETA 00:02 
    [download] 0.2% of 34.75MiB at 18.89MiB/s ETA 00:01 
    [download] 0.4% of 34.75MiB at 18.64MiB/s ETA 00:01 
    [download] 0.7% of 34.75MiB at 19.45MiB/s ETA 00:01 
    [download] 1.4% of 34.75MiB at 19.02MiB/s ETA 00:01
    [download] 2.9% of 34.75MiB at 17.33MiB/s ETA 00:01 
    [download] 5.8% of 34.75MiB at 22.55MiB/s ETA 00:01 
    [download] 11.5% of 34.75MiB at 23.15MiB/s ETA 00:01
    [download] 23.0% of 34.75MiB at 29.79MiB/s ETA 00:00 
    [download] 34.5% of 34.75MiB at 28.43MiB/s ETA 00:00
    [download] 46.0% of 34.75MiB at 30.29MiB/
s ETA 00:00
    [download] 57.6% of 34.75MiB at 28.19MiB/s ETA 00:00 
    [download] 69.1% of 34.75MiB at 29.51MiB/s ETA 00:00 
    [download] 80.6% of 34.75MiB at 29.35MiB/s ETA 00:00
    [download] 92.1% of 34.75MiB at 29.39MiB/s ETA 00:00
    [download] 100.0% of 34.75MiB at 29.26MiB/s ETA 00:00
    [download] 100% of 34.75MiB in 00:01 262144

It successfully downloaded, I like this.

I try to do this
    youtube-dl --get-url https://www.youtube.com/watch?v=-Cu0ihE490s

This generates the url for streaming, but the url gives
403 Forbidden response ?? Why are things like this
could happen.

**Comment by phihag** [comment]
This is expected behavior. Please refer to [our FAQ](https://github.com/rg3/youtube-dl/blob/master/README.md#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-webbrowser) for more details.
