### ISSUE TITLE
paid udemy course higher resoulution 

### ISSUE THREAD

**Issue by muhasturk** [rg3/youtube-dl#7704]
Youtube-dl works well with paid udemy courses. However youtube-dl could not download video format higher than 720p which has higher resolution than 720p.

For example

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.udemy.com/ios9-swift/learn/#/lecture/3383208', u'-F', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[udemy] Downloading login popup
[udemy] Logging in as x@x.com
[udemy] 3383208: Downloading lecture JSON
[info] Available formats for 3962016:
format code  extension  resolution note
360p         mp4        unknown
720p         mp4        unknown    (best)
```

**Comment by dstftw** [comment]
You have to either provide free course example URL with resolution higher than 720p or provide account credentials to one of the core developers.

**Comment by muhasturk** [comment]
If one cıre developer asks one of paid udemy course I will give it that information. Feel free to ask me by email

**Comment by dstftw** [comment]
If you are willing to provide what I've suggested in my previous post you can contact me via `dstftw <at> gmail.com`. Prior to than can you also post the output of `youtube-dl -v --dump-pages https://www.udemy.com/ios9-swift/learn/#/lecture/3383208`?

**Comment by muhasturk** [comment]
http://paste2.org/eJABGpcM

**Comment by muhasturk** [comment]
I see you only handled up to 720p video from returned json file

```python
        video = download_url.get('Video') or download_url.get('video')
        video_480p = download_url.get('Video480p') or download_url.get('video_480p')

        formats = [
            {
                'url': video_480p[0],
                'format_id': '360p',
            },
            {
                'url': video[0],
                'format_id': '720p',
            },
        ]
```

**Comment by dstftw** [comment]
Yes. This is because formats in `asset['data']['outputs']` were never seen before.
Looks like they also limit the number of logins (even successful ones) per account per hour, so don't log off your browser. Currently I'm getting:
>You have exceeded the maximum number of requests per hour.

**Comment by dstftw** [comment]
Should work in the next version.
You may also want to use [cookies for authentication](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl) instead of passing `-u` and `-p` in order to not being caught by
>You have exceeded the maximum number of requests per hour.
