### ISSUE TITLE
Still have a problem with Bloomberg.com

### ISSUE THREAD

**Issue by bonacker** [rg3/youtube-dl#7705]
My Bloomberg.com issue #7685 was closed after an edit to youtube_dl/extractor/bloomberg.py however this doesn't seem to have fixed the problem. 

This is the link to the video I wanted. It gives an " Unsupported URL" in youtube-dl:

http://www.bloomberg.com/politics/videos/2015-11-25/with-all-due-respect-11-25-15-

If I change the URL as per the change in youtube_dl/extractor/bloomberg.py  (adding "news" after the domain) to 

http://www.bloomberg.com/news/politics/videos/2015-11-25/with-all-due-respect-11-25-15- 

It now does download a video but not the one requested. It downloads a different video from the same page where I found the link to the video I wanted. The main page with many video links is http://www.bloomberg.com/politics/

Further testing shows that whatever is put after "videos," even non-existent files, the same video is always downloaded.

http://www.bloomberg.com/news/politics/videos/blah-blah-blah

Log:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--no-playlist', u'-i', u'--write-info-json', u'http://www.bloomberg.com/news/politics/videos/blah-blah-blah', u'-o', u'c:/recordings\\%(title)s.mp5']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-76860-g72eaf72, ffprobe N-75426-g8c9853a, rtmpdump 2.3
[debug] Proxy map: {}
[Bloomberg] blah-blah-blah: Downloading webpage
[Bloomberg] HarfW5JsSLmKJmiiVx6eow: Downloading JSON metadata
[Bloomberg] HarfW5JsSLmKJmiiVx6eow: Downloading m3u8 information
[Bloomberg] HarfW5JsSLmKJmiiVx6eow: Downloading f4m manifest
[Bloomberg] HarfW5JsSLmKJmiiVx6eow: Downloading f4m manifest
[Bloomberg] HarfW5JsSLmKJmiiVx6eow: Downloading f4m manifest
[Bloomberg] HarfW5JsSLmKJmiiVx6eow: Downloading f4m manifest
[Bloomberg] HarfW5JsSLmKJmiiVx6eow: Downloading f4m manifest
[Bloomberg] HarfW5JsSLmKJmiiVx6eow: Downloading f4m manifest
[Bloomberg] HarfW5JsSLmKJmiiVx6eow: Downloading f4m manifest
[Bloomberg] HarfW5JsSLmKJmiiVx6eow: Downloading f4m manifest
[Bloomberg] HarfW5JsSLmKJmiiVx6eow: Downloading f4m manifest
[Bloomberg] HarfW5JsSLmKJmiiVx6eow: Downloading f4m manifest
[info] Writing video description metadata as JSON to: c:\recordings\Bloomberg Politics.mp5.info.json
[debug] Invoking downloader on u'http://bbgvod-mmd-cust.lldns.net/m/NjU2MjIwNA/JpagLCCy0AQ4Uiy5Tab.hWhCTJHl2fv5j3y2SPn1FgYxY2Q5/dmdwadra1016_,15,24,44,70,120,180,240,0.mp4.csmil/manifest.f4m?hdcore=1'
[f4m] Downloading f4m manifest
[f4m] Total fragments: 28
[download] Destination: c:\recordings\Bloomberg Politics.mp5

[download]   0.0% of ~45.14MiB at 66.67KiB/s ETA 01:11:38

**Comment by jaimeMF** [comment]
A new version haven't been released yet, the first URL (http://www.bloomberg.com/politics/videos/2015-11-25/with-all-due-respect-11-25-15-) works with the code from the git repo. You'll have to wait for the next version or run from source.

About the rest of URLs: they redirect to http://www.bloomberg.com/politics/, so it extracts the first video from there (I don't know if we should do anything special).

**Comment by bonacker** [comment]
With a new Win32 version, 2015.12.5.0, released, I can report that Bloomberg.com videos download perfectly. Thanks!
