### ISSUE TITLE
Pull request to a new "heroku" branch

### ISSUE THREAD

**Issue by kobiburnley** [rg3/youtube-dl#7709]
Please take a look at my fork to the awesome youtube-dl lib.
https://github.com/kobiburnley/youtube-dl/tree/heroku

It's a version of youtube-dl ready to be deployed to heroku and stream by URL like:
http://dl-youtube.herokuapp.com/?id=koeW4g8Y-lg&formats=22

Maybe you would like to add a "Heroku" branch to this repo.

Greetings, Kobi.

**Comment by jaimeMF** [comment]
I think that we are currently not interested in maintaining a web service in this repo, at least for now we maintain only the python module and the cli program. But feel free to work on this and improve it. I think the best way to develop it would be an external python program where the youtube_dl module is installed as a dependency (see https://github.com/jaimeMF/youtube-dl-api-server for example), the main advantage is that you don't have to constantly merge from the main youtube-dl repo.

**Comment by kobiburnley** [comment]
Thanks, I needed that solution of adding youtube-dl as a dependency. But I guess I'll still have to reinstall the dependency and redeploy every new youtube-dl version is released, what do you think?

Anyway, for anyone who will find it interesting, I created another repo for this. A very simple (for now :]) web service, streaming the media directly using a web browser,  and anyone can deploy it to Heroku: https://github.com/kobiburnley/youtube-dl-stream
