### ISSUE TITLE
Password Acceptance for Vimeo User Login

### ISSUE THREAD

**Issue by bmgentile** [rg3/youtube-dl#7710]
When trying to authenticate with Vimeo, I'm using a password that contains the character ```)```

And it is throwing the error
```-bash: syntax error near unexpected token `)'```

The specific script I'm using is:
```youtube-dl -u xxxxxxx@xxxxx.com -p xxx)xxxxxxxxxxxxx https://vimeo.com/userxxxxxx/review/xxxxxxxxxxxxx```

**Comment by jaimeMF** [comment]
Probably surrounding the password with `'` (single quote) or `"`(double quote) is enough.

Since this is not a problem on youtube-dl, I'm closing it.
