### ISSUE TITLE
Can not download Youku video

### ISSUE THREAD

**Issue by GL8666** [rg3/youtube-dl#7712]
C:\Users\Yuze>youtube-dl http://v.youku.com/v_show/id_XMTQwMDY5OTUxMg==.html
[youku] XMTQwMDY5OTUxMg: Downloading JSON metadata 1
ERROR: Unable to download JSON metadata: [Errno 10054]  (caused by error(10054, '')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Duplicate of #7627.
