### ISSUE TITLE
404 on m3u8 stops batch?

### ISSUE THREAD

**Issue by SpiralBrad** [rg3/youtube-dl#7714]
D:\youtube-dl\>youtube-dl.exe --verbose --batch batch.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--batch', u'batch.txt']
[debug] Batch file urls: [u'http://teamfourstar.com/video/tfs-abridged-parody-ep
isode-2-2/', u'http://next.url/doesnt-matter/never-runs-this/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-74427-gaffbecb, ffprobe N-74427-gaffbecb
[debug] Proxy map: {}
[TeamFour] tfs-abridged-parody-episode-2-2: Downloading webpage
[ScreenwaveMedia] TeamFourStar-aBm: Downloading player webpage
[ScreenwaveMedia] TeamFourStar-aBm: Downloading playerconfig webpage
[ScreenwaveMedia] TeamFourStar-aBm: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 404: Not Found (caused by
 HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you
 are using the latest version; type  youtube-dl -U  to update. Be sure to call y
outube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1878, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default

**Comment by dstftw** [comment]
This is expected. `-i` to ignore errors.
