### ISSUE TITLE
Unable to download from NRK - region locked

### ISSUE THREAD

**Issue by efpob** [rg3/youtube-dl#7715]
The error at the end states "NRK does not have the rights to show this video outside of Norway"
However, I am in Norway. Do you have any tips?

youtube-dl.exe -v http://www.nrk.no/norge/slik-blir-nye-oslo-lufthavn-1.12680261
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.nrk.no/norge/slik-blir-nye-oslo-lufthavn-1.12680261']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[NRKPlaylist] slik-blir-nye-oslo-lufthavn-1.12680261: Downloading webpage
[download] Downloading playlist: Slik blir nye Oslo lufthavn
[NRKPlaylist] playlist Slik blir nye Oslo lufthavn: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[NRK] 240597: Downloading media JSON
ERROR: NRK har ikke rettigheter til å vise dette programmet utenfor Norge
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\nrk.pyo", line 54, in _real_extract
ExtractorError: NRK har ikke rettigheter til \xe5 vise dette programmet utenfor Norge

**Comment by dstftw** [comment]
Can you watch it in browser in the first place?

**Comment by efpob** [comment]
Yeah, it works fine in my browsers (FF, Chrome, IE)

**Comment by dstftw** [comment]
Post the output of `youtube-dl http://www.nrk.no/norge/slik-blir-nye-oslo-lufthavn-1.12680261 -v --call-home --dump-pages`.
What IP is shown when you open https://yt-dl.org/ip in your browser?

**Comment by efpob** [comment]
It was a huge bunch of data, so I put it on pastebin http://pastebin.com/d4tjJ1wv

IP from the yt-dl.org shows as 89.11.244.206

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version. Thanks for the report.

**Comment by efpob** [comment]
Great! Thanks for that
