### ISSUE TITLE
Bash scripting on Windows

### ISSUE THREAD

**Issue by ExtendedDev** [rg3/youtube-dl#7717]
I noticed that there are a number of bash scripts for youtube-dl. As I have just seen them, they have no extensions. It seems that all tutorials about bash scripts for youtube-dl and not only for it is specifically for unix like systems, that certainly supports bash scripting. These scripts adds additional functionality. It can be said that bash scripting is primarily designed for other os like linux, but not for Windows. So, how to use youtube-dl bash scripts on windows? Is it required to convert bash scripts to batch, or maybe Python source files? I don't know those things. Thanks in advance.

**Comment by dstftw** [comment]
Either use cygwin or convert to batch/python/powershell.
