### ISSUE TITLE
Use template placeholder in --download-archive

### ISSUE THREAD

**Issue by dldummy** [rg3/youtube-dl#7719]
It seems that the placeholders %(xxx)s dont work in case of  --download-archive

Is it possible to implement some ... at least %(playlist)s  
like  --download-archive ".\LOG\%(playlist)s.dllog"

Thanks ....

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by dstftw** [comment]
Output template is not supposed to be used as argument to `--download-archive` because it's name must be stable otherwise it would defeat all the idea of download archive.

**Comment by dldummy** [comment]
Yes your right ... in case of %(title)s or other video dependant templates ....
But playlistname, uploader, format, .... can be usefull .....

Its usefull for me to seperate the archivefiles of different youtube-playlists ... 
Some viedeos are added to more than one "PROCESSING"-playlist (Video, AudioOnly, LoResVideo) ... 
with one archivefile it only DL it in one format, then ignore the existence in the other playlists .....

**Comment by Hrxn** [comment]
Then don't add these videos to the archive file? If you put the same link to process in different files, it will be downloaded more than once. If you don't want that, remove duplicate links beforehand.

This is not within scope of youtube-dl.

**Comment by afterdelight** [comment]
could you work on this
