### ISSUE TITLE
Gametrailers.com Extractor is broken

### ISSUE THREAD

**Issue by kristofferR** [rg3/youtube-dl#7722]
It seems like Gametrailers.com have changed to a completely different video system, making the old one broken.

Here's the video I tried to download with youtube-dl:
http://www.gametrailers.com/videos/view/gametrailers-com/116437-Just-Cause-3-Review

**Comment by HASJ** [comment]
```
youtube-dl test:gametrailers -v
[debug] System config: []
[debug] User config: [u'-f', u'298+bestaudio/136+bestaudio/best/135+bestaudio/134+bestaudio/133+bestaudio/160+bestaudio/0', u'-o', u'D:\\V\xeddeos\\[%(extractor)s] %(uploader)s-%(upload_date)s-%(playlist)s #%(playlist_index)s - %(title)s [%(id)s].%(ext)s', u'--external-downloader', u'aria2c', u'--external-downloader-args', u'--file-allocation=falloc --min-split-size=1M --split=16 --max-connection-per-server=16']
[debug] Command-line args: [u'test:gametrailers', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-75499-g7179add, ffprobe N-73696-g8250943, rtmpdump 2.4
[debug] Proxy map: {}
[TestURL] Test URL: http://www.gametrailers.com/videos/zbvr8i/mirror-s-edge-2-e3-2013--debut-trailer
[Gametrailers] mirror-s-edge-2-e3-2013--debut-trailer: Downloading webpage
ERROR: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\mtv.pyo", line 193, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 684, in _og_search_video_url
  File "youtube_dl\extractor\common.pyo", line 593, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 584, in _search_regex
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\mtv.pyo", line 209, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 584, in _search_regex
RegexNotFoundError: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Not working for me either.

**Comment by Hrxn** [comment]
I just threw a short glance at that page..

Visiting the page itself doesn't seem to load any video. This has to be a new trend...

Just an &lt;a&gt; element as the link, inside a &lt;div&gt; with just a .jpeg as background, that has to be clicked first.

And all that in an &lt;iframe&gt;, although with a useful src. The 'embed' link inside the share button works too:

http://embed.gametrailers.com/embed/2983958

Okay, the actual video is either streamed via HLS or HDS. That is ugly...

Well, so far I only have a flash video manifest:

http://wpc.10016.edgecastcdn.net/0210016/gtcomstor/958/983/2983958/just-cause-3-review-,496,864,2240,_kbps.mp4.f4m?1B608EE7AFCE3765E176F3C6FBB98002B3D18C64572F2307D769A87CA07DF6BDB1B6

And a .m3u8:

http://wpc.10016.edgecastcdn.net/0310016/gtcomstor/958/983/2983958/just-cause-3-review-,496,864,2240,_kbps.mp4.m3u8

Inside are .m3u8 with the different bitrates, and they contain some links to the transport stream segments.

Why are they doing it so complicated?

I'm getting to old for this crap..

**Comment by HASJ** [comment]
Hmm, Internet Download Manager didn't update and worked normally with GT. I'm not saying it does it's video detection the same way Y-DL does it.

**Comment by Hrxn** [comment]
Well, IDM has some video page grabber/flash video grabber functionality built-in, that is right..

And it does work, out of the box, for the example link in [comment 1](https://github.com/rg3/youtube-dl/issues/7722#issue-119755143)?

**Comment by HASJ** [comment]
@Hrxn 
Yes it did, quality detection and all.
My installed IDM version is at least two months old, mind you.

**Comment by jaimeMF** [comment]
Thanks for the report, it will work in the next version.

**Comment by Hrxn** [comment]
Thanks! :)

You could do it by hand with a script like [AdobeHDS.php](https://github.com/K-S-V/Scripts/blob/master/AdobeHDS.php), but I guess using youtube-dl is way easier
