### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by josephomorrow** [rg3/youtube-dl#7726]
Attached is a files containing the verbose output with related text . . .
[ytdl_20151201_debug.txt](https://github.com/rg3/youtube-dl/files/49162/ytdl_20151201_debug.txt)

**Comment by josephomorrow** [comment]
I have been getting this error occasionally, lately, while attempting to grab certain youTube videos.

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. See [our FAQ](https://yt-dl.org/update) if you need help updating.
