### ISSUE TITLE
Add audio files to already downloaded videos.

### ISSUE THREAD

**Issue by anweshknayak** [rg3/youtube-dl#7729]
Actually I downloaded the DASH manifest video files only . I had not checked before it contains only the video output without the audio. Is there any way I can download audio files and merge them to the already downloaded video files ?

**Comment by jaimeMF** [comment]
That's not supported, but on the second run something like `[download] Destination: <title>.f137.mp4` will be printed and you can do the following:
1. Stop youtube-dl
2. Rename the downloaded file to `<title>.f137.mp4` (it may be something different to `f137`)
3. Run youtube-dl again, the video won't be redownloaded
