### ISSUE TITLE
Beeg

### ISSUE THREAD

**Issue by campones** [rg3/youtube-dl#7736]
root@server:~/admin# youtube-dl --verbose --no-mtime -q http://beeg.com/4272290 http://beeg.com/9206276 http://beeg.com/7566648 http://beeg.com/2381524 &
[1] 18073
root@server:~/admin# [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--no-mtime', u'-q', u'http://beeg.com/4272290', u'http://beeg.com/9206276', u'http://beeg.com/7566648', u'http://beeg.com/2381524']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.21
[debug] Python version 2.7.6 - Linux-3.13.0-66-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-75403-g3a8e447, ffprobe N-75403-g3a8e447, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 329, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1874, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by Hrxn** [comment]
Please be aware, that
> [debug] youtube-dl version 2015.11.21

is not the latest version of youtube-dl at the time of your issue report.

https://github.com/rg3/youtube-dl#are-you-using-the-latest-version

**Comment by campones** [comment]
I did update after issuing that command, and I get the same result, knowing that it has been working fine for me before

**Comment by sudovijay** [comment]
they switched to API V4 now. this doesnt work anymore "http://beeg.com/api/v4/video/"

**Comment by yan12125** [comment]
@sudovijay Please post the output of ```youtube-dl --verbose [some URL]``` if you've found problems.

**Comment by sudovijay** [comment]
already resolved. sorry for posting here. my bad
