### ISSUE TITLE
Not pulling SoundClound JSON metadata

### ISSUE THREAD

**Issue by designerbrent** [rg3/youtube-dl#7738]
I'm trying to pull an file out of SoundCloud and am getting the following error:

> ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug .

**Comment by jaimeMF** [comment]
Please, read the [bug reporting instructions](https://github.com/rg3/youtube-dl/blob/bb6ac8369858e79b04e30e6ea25016500083628f/README.md#bugs) and post the required information.
