### ISSUE TITLE
Force update

### ISSUE THREAD

**Issue by latot** [rg3/youtube-dl#7747]
Hi, well i'm here agin to ask a feature.
Its becasue for example if we download manually youtube-dl to a custom dir or in windows we do a bin path for linux apps it don't permit update via -U, this is the super message:

```
It looks like you installed youtube-dl with a package manager, pip, setup.py or 
a tarball. Please use that to update.
```

Thx.

**Comment by dstftw** [comment]
What's your proposal?
If you've installed youtube-dl manually you'll be able to update with `-U`. If you installed it with any kind of package manager you should use it for updating since `-U` option may be removed by package managers at all.

**Comment by latot** [comment]
mm, a example wil be more easy, in windows. have a rute /hi/bin here i put my bineries of linux for windows like youtube-dl.exe.

so i download it and then i put the file in that directory.
The directory are in PATH env.

in a cmd i run
youtube-dl -U
and i get the message D:

**Comment by dstftw** [comment]
This is [known bug](https://github.com/rg3/youtube-dl/issues/2718).

**Comment by latot** [comment]
don't is that bug
is different, here youtube-dl detects the custom dir as a package manager installation, and i have write permiss.

**Comment by AGSPhoenix** [comment]
@dstftw, I think this is a different issue. This seems to be about youtube-dl thinking it was installed via package manager when it wasn't.

[This](https://github.com/rg3/youtube-dl/blob/c0384f221e5a8383c377a3c43f634cf9807eb634/youtube_dl/update.py#L55) seems to be the relevant code, though it has been so long since I've worked with the codebase that I'm not really sure how it behaves under each of the various distribution methods (compiled executable, source files, etc.).

@latot, what path is your youtube-dl installed in? I tried updating from `C:\hi\bin` without issue; was that just an example, or the actual path you're using? Are you sure you're using the prepackaged `youtube-dl.exe` and that there is no separate install from pip or setup.py?

**Comment by latot** [comment]
Hi, i test it with linux and windows, in windows i use this path this location /User/Cos/Documents/linux/bin in linux i try this but without path only running from terminal, /home/pipe/Documentos/youtube.dl (file)

i install both downloading from the instructions of main page, i don't install from pip, in windows i use the .exe version in the same page.

Cys.

**Comment by AGSPhoenix** [comment]
It works for me:

```
PS C:\Users\Phoenix\Documents\linux\bin> .\youtube-dl.exe -U -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-U', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.12.21
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-76776-g3c110b0, ffprobe N-76776-g3c110b0
[debug] Proxy map: {}
Updating to version 2015.12.23 ...
Waiting for file handle to be closed ...
PS C:\Users\Phoenix\Documents\linux\bin> Updated youtube-dl to version 2015.12.23.
```

Could you run the same command (`youtube-dl.exe -U -v`) and paste the output here?

**Comment by latot** [comment]
Hi, testing if i run the command from the directory it works, but calling with the PATH don't works (the rute of windows is in path).

don't working:
```
C:\Users\Cos>youtube-dl.exe -U -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-U', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.01.11
[debug] Python version 3.4.2 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77008-g085ab74, ffprobe N-77008-g085ab74
[debug] Proxy map: {}
It looks like you installed youtube-dl with a package manager, pip, setup.py or
a tarball. Please use that to update.
```

working from directory:
```
C:\Users\Cos\Documents\Linux\bin>youtube-dl.exe -U -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-U', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77008-g085ab74, ffprobe N-77008-g085ab74
[debug] Proxy map: {}
Updating to version 2015.12.23 ...
Waiting for file handle to be closed ...

C:\Users\Cos\Documents\Linux\bin>Updated youtube-dl to version 2015.12.23.
```

**Comment by AGSPhoenix** [comment]
Hmm. The behaviour of not being about to update without navigating to the directory the binary in is the same as with the other bug, but I have to wonder at what could be happening to cause that error.

@dstftw, I think this should be looked into. Could you consider reopening it?

**Comment by latot** [comment]
mm, only to be sure.
the other bug is the perms error? its feels very different, in that bug in fact affect the PATH, but the focus of the error are perms to write, here affects PATH too, but here its the recognition of the installation type (manual vs package manager)

**Comment by Hrxn** [comment]
That is the known bug that was mentioned earlier, #2718

**Comment by AGSPhoenix** [comment]
@Hrxn, #2718 presents itself as a `no write permissions` error, like so:

```
C:\Users\Phoenix>where youtube-dl
C:\Users\Phoenix\bin\youtube-dl.exe

C:\Users\Phoenix>youtube-dl -U
Updating to version 2015.12.23 ...
ERROR: no write permissions on youtube-dl
```
This check happens in `update.py` at either [line 108](https://github.com/rg3/youtube-dl/blob/c0384f221e5a8383c377a3c43f634cf9807eb634/youtube_dl/update.py#L108) or line 116 right below.

However, the message @latot is encountering is a result of the code at [line 55](https://github.com/rg3/youtube-dl/blob/c0384f221e5a8383c377a3c43f634cf9807eb634/youtube_dl/update.py#L55), which seems to be failing to determine the installation type correctly. They don't seem related to me.
