### ISSUE TITLE
How to download an entire channel

### ISSUE THREAD

**Issue by punit-naik** [rg3/youtube-dl#7749]
I want to download an entire youtube channel, how do I do it?

**Comment by yan12125** [comment]
Youtube channels [are supported](https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md). Just feed the channel URL to youtube-dl. Do you have problems on downloading?

**Comment by punit-naik** [comment]
I couldn't find the right command to do so actually.

**Comment by yan12125** [comment]
Which channel URL are you trying to download?

**Comment by punit-naik** [comment]
Basically I wanted to download all videos as mp3s from this user:
'https://www.youtube.com/user/mtvunpluggedindia'

**Comment by phihag** [comment]
Type
```
youtube-dl https://www.youtube.com/user/mtvunpluggedindia
```

**Comment by phihag** [comment]
Type
```
youtube-dl -x --audio-format-mp3 https://www.youtube.com/user/mtvunpluggedindia
```

**Comment by phihag** [comment]
Type
```
youtube-dl -x --audio-format mp3 https://www.youtube.com/user/mtvunpluggedindia
```

**Comment by punit-naik** [comment]
Okay thanks a lot @phihag :+1:
