### ISSUE TITLE
Suggestion - improve support for "random" sites

### ISSUE THREAD

**Issue by edrozenberg** [rg3/youtube-dl#7750]
youtube-dl doesn't always do a good job identifying and extracting video from "random" sites, such as for example the video embedded in the url below. I believe it should be possible to improve this based on my use of the GUI tool http://thelittleappfactory.com/grappler/ which usually manages to extract these random videos.

http://www.lamello.com/en/home/join-wood/invis-mx-system/invis-mx2.html

````
[generic] invis-mx2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] invis-mx2: Downloading webpage
[generic] invis-mx2: Extracting information
ERROR: Unsupported URL: http://www.lamello.com/en/home/join-wood/invis-mx-system/invis-mx2.html
````

**Comment by dstftw** [comment]
All these programs rely on web browser's engine and technically does not extract anything - browser does for them. youtube-dl does not rely on browser therefore does not have any kind of full strength JS interpreter and so and can't actually render the webpage but rather youtube-dl uses well-known extraction patterns and scenarios.

**Comment by edrozenberg** [comment]
Thanks that makes sense. No point embedding node-js into youtube-dl :).
