### ISSUE TITLE
issue on keezmovies.py

### ISSUE THREAD

**Issue by UnveilTech** [rg3/youtube-dl#7752]
Hi,
It seems not working:
./youtube-dl --all-formats "http://www.keezmovies.com/video/allison-wyte-kelly-the-coed-17-scene-2-440201"
[KeezMovies] 440201: Downloading webpage
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Thanks for the report. Videos on KeezMovies.com will be fixed in the next version.
