### ISSUE TITLE
Http Error 429 

### ISSUE THREAD

**Issue by ichzocks30** [rg3/youtube-dl#7757]
Hi I have a problem with the YouTube Downloader it gives the error 429 from (Unable to download webpage: HTTP Error 429: Too Many Requests (Caused by HTTP Error ()); please report this issue on https: // yt-dl. org / bug Make sure you are using the latest version;. type youtube-dl -U to update Be sure to call yo utube-dl with the --verbose flag and include its complete output..
)

**Comment by dstftw** [comment]
You may want to read [FAQ entry on the issue](https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required) and [this discussion](https://github.com/rg3/youtube-dl/issues/5138).
