### ISSUE TITLE
Site Support Request: srf.ch Radio / Audio

### ISSUE THREAD

**Issue by irem77** [rg3/youtube-dl#7760]
Srf.ch video works perfectly... audio support would be nice.

http://www.srf.ch/play/radio/hoerspielarchiv-srf-musikwelle/audio/saegel-ohni-wind-von-jakob-stebler?id=415bf3d3-6429-4de7-968d-95866e37cfbc

**Comment by yan12125** [comment]
Thanks for the report and the example URL. Audios on Srf.ch will be supported in the next version.

**Comment by irem77** [comment]
Thanks alot  !




Von Samsung-Tablet gesendetYen Chi Hsuan <notifications@github.com> hat geschrieben:Thanks for the report and the example URL. Audios on Srf.ch will be supported in the next version.
