### ISSUE TITLE
Metacafe not working

### ISSUE THREAD

**Issue by UnveilTech** [rg3/youtube-dl#7763]
Hi,
Error with metacafe.com:
./youtube-dl --ignore-errors --no-playlist --all-formats "http://www.metacafe.com/watch/11419724/thanksgiving_club_sandwich_epic_meal_time/"
[metacafe] Retrieving disclaimer
[metacafe] Confirming age
[metacafe] 11419724: Downloading webpage
[metacafe] 11419724: Extracting information
ERROR: Unsupported video type; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
Thanks for the report, it will be fixed in the next version.
