### ISSUE TITLE
Videoweed not working...

### ISSUE THREAD

**Issue by sjmyst** [rg3/youtube-dl#7764]
bash.exe"-3.1$ youtube-dl http://embed.videoweed.es/embed.php?v=e3b13e81e4a34
[videoweed] e3b13e81e4a34: Downloading video page
[videoweed] e3b13e81e4a34: Downloading continue to the video page
ERROR: Unable to extract filekey; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
bash.exe"-3.1$ youtube-dl --verbose http://embed.videoweed.es/embed.php?v=e3b13e81e4a34
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://embed.videoweed.es/embed.php?v=e3b13e81e4a34']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-67467-g2b14593, ffprobe N-67467-g2b14593, rtmpdump 2.4
[debug] Proxy map: {}
[videoweed] e3b13e81e4a34: Downloading video page
[videoweed] e3b13e81e4a34: Downloading continue to the video page
ERROR: Unable to extract filekey; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\novamov.pyo", line 73, in _real_extract
  File "youtube_dl\extractor\novamov.pyo", line 55, in extract_filekey
  File "youtube_dl\extractor\common.pyo", line 584, in _search_regex
RegexNotFoundError: Unable to extract filekey; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

bash.exe"-3.1$

**Comment by yan12125** [comment]
Thanks for the report and sorry for late response. Videoweed will work again in the next version.
