### ISSUE TITLE
Add 1280x720 resolution to pluralsight.py

### ISSUE THREAD

**Issue by alexzeitgeist** [rg3/youtube-dl#7766]
Hi,

Newer videos are now often available in 1280x720 (720p) resolution. It would be nice if it could be added to ALLOWED_QUALITIES.

Alex

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by alexzeitgeist** [comment]
Example URL: http://vid.pluralsight.com/expiretime=<expiretime>/<hash>/clip-videos/nate-taylor/professionalism-for-developers-m1/professionalism-for-developers-m1-01/1280x720mp4/20151203212644.mp4

(expiretime and hash stripped)

**Comment by dstftw** [comment]
Post the **initial** course URL not download URL.

**Comment by alexzeitgeist** [comment]
NP, URL updated.

**Comment by dstftw** [comment]
Can you provide free course URL with same quality video or pluralsight account credentials?

**Comment by alexzeitgeist** [comment]
@dstftw please check your e-mail.

**Comment by dstftw** [comment]
Widescreen videos will be available for download in the next version.
