### ISSUE TITLE
Issue with BBC videos

### ISSUE THREAD

**Issue by UnveilTech** [rg3/youtube-dl#7773]
Hi,
./youtube-dl --ignore-errors --no-playlist --all-formats "http://www.bbc.co.uk/music/clips/smp/p03b2hjh"
[bbc] p03b2hjh: Downloading webpage
ERROR: Unable to extract playlist title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
There is no video playable by this URL. Correct URL is http://www.bbc.co.uk/music/clips#p03b2hjh.
