### ISSUE TITLE
stream error sinus bot

### ISSUE THREAD

**Issue by LatiasTS** [rg3/youtube-dl#7777]
https://www.youtube.com/playlist?list=PLf-LHQp1nTdxc90yRcR1DK0ZAUIn3uu4v cannot be played

**Comment by jaimeMF** [comment]
If you don't provide [the required information] we can't do anything. And note that if you are using a wrapper around youtube-dl (sinus bot in this case?) you should report the problem to them and only to us if you can reproduce it in the command line program with the last version of youtube-dl.
