### ISSUE TITLE
[youtube] «video doesn't have subtitles»

### ISSUE THREAD

**Issue by fzg** [rg3/youtube-dl#7778]
Trying to grab the automatically generated subtitles yields nothing.

youtube-dl --write-srt --write-auto-sub "https://www.youtube.com/watch?v=yCoRzJY_ejw"

```
[...]
[debug] youtube-dl version 2015.12.06
[debug] Python version 2.7.10+ - Linux-4.2.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 2.8.3-1, avprobe 2.8.3-1, ffmpeg 2.8.3-1, ffprobe 2.8.3-1, rtmpdump 2.4
[...]
WARNING: video doesn't have subtitles
[...]
```

**Comment by jaimeMF** [comment]
It only has automatic subtitles but you also request the normal subtitles, that's why it shows the warning. Therefore it only downloads automatic subtitles.
