### ISSUE TITLE
ESPN / ESPNFC

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#7785]
URL: http://espn.go.com/video/clip?id=14307447

OUTPUT:
youtube-dl -v -f best "http://espn.go.com/video/clip?id=14307447"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'best', u'http://espn.go.com/video/cl
ip?id=14307447']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.06
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
WARNING: The program functionality for this site has been marked as broken, and
will probably not work.
[ESPN] clip?id=14307447: Downloading webpage
[ESPN] 14307447: Downloading webpage
[OoyalaExternal] 14307447: Downloading JSON metadata
[OoyalaExternal] 14307447: Downloading mp4 JSON
[OoyalaExternal] 14307447: Downloading m3u8 JSON
[OoyalaExternal] J4NDFkeTqiE2qJwa7cxgVrtr_j3jl_e9: Downloading m3u8 information
[OoyalaExternal] 14307447: Downloading hds JSON
[debug] Invoking downloader on u'http://hds.video-cdn.espn.com/z/motion/ESPNi/20
15/1206/int_151206_Must_See_Moments_Best_of_MLS_2015_season/int_151206_Must_See_
Moments_Best_of_MLS_2015_season_rel.smil/manifest.f4m'
[f4m] Downloading f4m manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1601, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1543, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\f4m.pyo", line 289, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1878, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default
HTTPError: HTTP Error 403: Forbidden

...and I suppose this is a site request, however the same video is also on ESPNFC but defaults to the general extractor

URL: http://www.espnfc.us/video/mls-highlights/150/video/2743663/must-see-moments-best-of-the-mls-season
OUTPUT: 
youtube-dl -v "http://www.espnfc.us/video/mls-highlights/150/video/2743663/m
ust-see-moments-best-of-the-mls-season"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.espnfc.us/video/mls-highlights/1
50/video/2743663/must-see-moments-best-of-the-mls-season']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.06
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[generic] must-see-moments-best-of-the-mls-season: Requesting header
WARNING: Falling back on generic information extractor.
[generic] must-see-moments-best-of-the-mls-season: Downloading webpage
[generic] must-see-moments-best-of-the-mls-season: Extracting information
[debug] Invoking downloader on u'https://sw88.go.com/b/ss/wdgespvideo/5.4/REDIR/
031615570333296051449504376310?D=..&url=https://once.unicornmedia.com/now/od/aut
o/07355f66-a73e-46c2-885b-e769dac7c817/20879ce0-ad85-4acf-b0b4-f4a91a6c1517/ac99
a7e5-7c12-4327-919f-a1a18597cd52/content.once?UMADPARAMreferer=http://espnfc.com
/video/espnfc/video?id=2743663&pe=media&mediaName=SOCCER::FCUS_MLS::+Must+See+Mo
ments:+Best+of+the+MLS+season_2743663&mediaLength=00:03:31&mediaPlayer=embed09&m
ediaSession=0-0&c3=videoid=SOCCER::FCUS_MLS::+Must+See+Moments:+Best+of+the+MLS+
season_2743663&v2=videoid=SOCCER::FCUS_MLS::+Must+See+Moments:+Best+of+the+MLS+s
eason_2743663&events=event1&v52=inlinePlayer&c52=inlinePlayer&v53=inlinePlayer:t
witter&c53=inlinePlayer:twitter'

ERROR: Did not get any data blocks
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 410, in main
  File "youtube_dl\__init__.pyo", line 400, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1669, in download
  File "youtube_dl\YoutubeDL.pyo", line 674, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 720, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1339, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1601, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1543, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 230, in real_download
  File "youtube_dl\downloader\common.pyo", line 155, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 538, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 500, in trouble

Thanks
Ringo

**Comment by yan12125** [comment]
Thanks to @remitamine this is fix partly in #7833 and the fix will be available in the next version. Here I keep this issue open as ```best``` format is incorrectly determined. (#7769) For this video, the best format can be downloaded with the following command:
```
youtube-dl -f hls-5293 "http://espn.go.com/video/clip?id=14307447"
```

**Comment by RingoTheDog** [comment]
You guys are amazing as always...THANK YOU!

Would you like me to open another thread for ESPNFC?  (I probably should have initially done that..sry)

**Comment by yan12125** [comment]
> Would you like me to open another thread for ESPNFC?

Yes please if you are willing to.

**Comment by remitamine** [comment]
format sorting has been fixed:
```
python2 __main__.py -F 'http://espn.go.com/video/clip?id=14307447'
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[ESPN] clip?id=14307447: Downloading webpage
[ESPN] 14307447: Downloading webpage
[OoyalaExternal] 14307447: Downloading JSON metadata
[OoyalaExternal] 14307447: Downloading mp4 JSON
[OoyalaExternal] 14307447: Downloading m3u8 JSON
[OoyalaExternal] J4NDFkeTqiE2qJwa7cxgVrtr_j3jl_e9: Downloading m3u8 information
[OoyalaExternal] 14307447: Downloading hds JSON
[OoyalaExternal] J4NDFkeTqiE2qJwa7cxgVrtr_j3jl_e9: Downloading f4m manifest
[OoyalaExternal] 14307447: Downloading rtmp JSON
[info] Available formats for J4NDFkeTqiE2qJwa7cxgVrtr_j3jl_e9:
format code  extension  resolution note
hls-meta     mp4        multiple   Quality selection URL 
mp4          mp4        unknown    
hds-271      flv        unknown     271k 
hls-334      mp4        unknown     334k , avc1, mp4a 
hds-545      flv        unknown     545k 
hls-647      mp4        unknown     647k , avc1, mp4a 
hds-1047     flv        unknown    1047k 
hls-1244     mp4        unknown    1244k , avc1, mp4a 
hds-1461     flv        unknown    1461k 
hls-1709     mp4        unknown    1709k , avc1, mp4a 
hds-2093     flv        unknown    2093k 
hls-2418     mp4        unknown    2418k , avc1, mp4a 
hds-3196     flv        unknown    3196k 
hls-3659     mp4        unknown    3659k , avc1, mp4a 
hds-4627     flv        unknown    4627k 
hls-5293     mp4        unknown    5293k , avc1, mp4a  (best)
```
