### ISSUE TITLE
Stream.pm

### ISSUE THREAD

**Issue by izelenov** [rg3/youtube-dl#7787]
Can You please add additional supported web page - Stream.pm (http://www.stream.pm/).
It is filial project of http://www.kinokopilka.tv/.
Format of pages for process is very simple.

http://www.stream.pm/videos/1L4vvX
  var video = {
    access: 'free',
    title:  'Minions',
    url:    'http://www.stream.pm/videos/1L4vvX/download.mp4'
  };

Here list of some videos from stream.pm:
http://www.stream.pm/videos/1L4vvX
http://www.stream.pm/videos/h4px0I
http://www.stream.pm/videos/41CU8O
http://www.stream.pm/videos/DXtVOb
http://www.stream.pm/videos/GVPcNQ

Here list of some seials:
http://www.stream.pm/containers/H473AL
http://www.stream.pm/containers/YxotHV
http://www.stream.pm/containers/uXTyrm

Thanks!

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by izelenov** [comment]
Yes, I think you right. Very likely it is copyrighted content.
So if this prohibited by project policy, please close this request.
