### ISSUE TITLE
[wdr] Allow to download the mp4 file

### ISSUE THREAD

**Issue by peternorman1900** [rg3/youtube-dl#7788]
hi,

youtube-dl --version 
2015.12.05

if you want to download or watch things through mplayer from wdr mediathek you load a lot of *.flv. (youtube-dl -t http://www1.wdr.de/mediathek/video/sendungen/machtan/videofolgeeinneueswir100.html)

the site recognize you useragent. if mobile useragent set you can download the whole mp4 but you need mobile useragent to get to the mobile site for each video.

sample: http://www1.wdr.de/fernsehen/sendungen_az/machtan/sendungen/das-lachen-der-anderen/videofolgemultiplesklerose100-videoplayer.html

change your useragent to ios 511 you can download the hq mp4.

description: iOS 5_1_1 - iPhone - Chrome (crios) 19.0.1084.60
useragent: Mozilla/5.0 (iPhone; U; CPU iPhone OS 5_1_1 like Mac OS X; da-dk) AppleWebKit/534.46.0 (KHTML, like Gecko) CriOS/19.0.1084.60 Mobile/9B206 Safari/7534.48.3

hope someone will add this feature into youtube-dl.

thank you !

**Comment by remitamine** [comment]
support for other formats and qualities will be added in the next version.
