### ISSUE TITLE
Unable to download a particular video

### ISSUE THREAD

**Issue by morronitech** [rg3/youtube-dl#7790]
I was unable to retrieve https://www.youtube.com/watch?v=QPRc0NIeQrQ

I checked other youtube videos and had no issue.  The tool is outputting the error in the attached text file.  Has anyone encountered
[yt-error.txt](https://github.com/rg3/youtube-dl/files/54635/yt-error.txt)
 this in the past?

**Comment by jaimeMF** [comment]
You are using an outdated version, [you have to update youtube-dl](https://github.com/rg3/youtube-dl/blob/535d7b681b05a37a3c2549c7501eb7fe9c8a5f4e/README.md#bugs).
