### ISSUE TITLE
youtube-dl stopped working on nbc.com

### ISSUE THREAD

**Issue by jimdays2788** [rg3/youtube-dl#7791]
Was working very nicely and suddenly stopped working. Tried latest youtube-dl but still same error message.
![clipboard01](https://cloud.githubusercontent.com/assets/16200374/11646151/eb40d57e-9d28-11e5-99b2-7166eab8be14.jpg)

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by jimdays2788** [comment]
I tried to use the -v command, and was expecting a txt file in my folder where the video normally appears, but there was no txt file. Here is the command I used (with verbose option):
youtube-dl.exe -v http://www.nbc.com/the-wiz-live/video/the-wiz-live/2943548?onid=248451#vc248451=1
![clipboard01](https://cloud.githubusercontent.com/assets/16200374/11655394/75cc4f3c-9d7b-11e5-9db0-fe8be30eea58.jpg)
Here is another command that shows the program works. 
youtube-dl -v -f 17 http://www.youtube.com/watch?v=P9pzm5b6FFY
![clipboard02](https://cloud.githubusercontent.com/assets/16200374/11655589/0451ac2e-9d7d-11e5-9d9c-0d84dd0bca96.jpg)
Just doesn't work on nbc.com anymore

**Comment by dstftw** [comment]
For further bug report: **do not post screenshots**, but copy as plain text.
