### ISSUE TITLE
Download playlist from youtube

### ISSUE THREAD

**Issue by accorreia123** [rg3/youtube-dl#7795]
Feature enabling download playlists from youtube is broken.

D:\Downloads\ac>D:\Downloads\youtube-dl -i -f 18/22 --verbose --write-sub  -o ./%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s https://www.youtube.com/playlist?list=PLQObLunIEgaQ7Drxp8yCmsJqidgSsTqlw
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-i', u'-f', u'18/22', u'--verbose', u'--write-sub', u'-o', u'./%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s', u'https://www.youtube.com/playlist?list=PLQObLunIEgaQ7Drxp8yCmsJqidgSsTqlw']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.08.23
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-72362-g7ae805d, ffprobe N-72362-g7ae805d, rtmpdump 2.3
[debug] Proxy map: {}
[youtube:playlist] PLQObLunIEgaQ7Drxp8yCmsJqidgSsTqlw: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 655, in extract_info
  File "youtube_dl\extractor\common.pyo", line 287, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1574, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 1549, in _extract_playlist
  File "youtube_dl\extractor\common.pyo", line 578, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 569, in _search_regex
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by anovicecodemonkey** [comment]
You need to update youtube-dl to the latest version. As the output states: "Make sure you are using the latest version; type youtube-dl -U to update".

**Comment by jaimeMF** [comment]
@anovicecodemonkey is right, [see the update instructions](https://github.com/rg3/youtube-dl/blob/535d7b681b05a37a3c2549c7501eb7fe9c8a5f4e/README.md#how-do-i-update-youtube-dl).
