### ISSUE TITLE
Vevo said: What the? The number you have reached has been disconnected or is no longer in service. Try again, over

### ISSUE THREAD

**Issue by g8keepa** [rg3/youtube-dl#7802]
Tried grabbing a video from vevo, got this error:

Vevo said: What the? The number you have reached has been disconnected or is no longer in service. Try again, over

 Only certain files are doing this, here's a link to one that's not working:

http://www.vevo.com/watch/k-camp-1/Till-I-Die/USUV71503000

**Comment by yan12125** [comment]
For developers: this video fails at ```AuthenticateVideo``` (no ```video_info```) while OK in ```_download_api_formats```.

**Comment by yan12125** [comment]
This will be fixed in the next version. Thanks for the report.
