### ISSUE TITLE
youtube-dl not working at whole with some videos on youtube 

### ISSUE THREAD

**Issue by abdulsalam1** [rg3/youtube-dl#7804]
Hi how are you 
i have problem with youtube-dl 
it's not working with almost the video which has more than 2 million 
this is the error 

[youtube] 7vZheETqNBQ: Downloading webpage
[youtube] 7vZheETqNBQ: Downloading video info webpage
[youtube] 7vZheETqNBQ: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 676, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 568, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflx9OkTA/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflx9OkTA/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

how can i solve it

**Comment by jaimeMF** [comment]
[Without the required information](https://github.com/rg3/youtube-dl/blob/3348243b7ba94e83dfb9d675fa0e701f97d3e220/README.md#bugs), we can't do too much to help you.

Anyways, it works for me with the last version, so I bet you are using an outdated version. If that's the case, [you have to update youtube-dl](https://github.com/rg3/youtube-dl/blob/3348243b7ba94e83dfb9d675fa0e701f97d3e220/README.md#how-do-i-update-youtube-dl).

**Comment by dstftw** [comment]
As already mentioned by @jaimeMF most likely you are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by abdulsalam1** [comment]
yes that's right i updated and every thing is good now
