### ISSUE TITLE
youtube to stream

### ISSUE THREAD

**Issue by no-paj** [rg3/youtube-dl#7807]
Hello,

I would like to know if it is possible to make a python stream object from a youtube video ? If yes, how ?

Thank you for your responses :)

**Comment by yan12125** [comment]
What's a "python stream object"? Can you give some code snippets for what you've tried and what's your expectation?

**Comment by no-paj** [comment]
Typically a stream object is `file = open("some_file_name.txt", 'r')`.
There are 3 types of stream object : Text, Binary and Raw. 
What I can do is typically download the video with youtuve-dl embedded in my code and then use `file = open("the_video", 'r')`.
But that's generating delay, it's not really what I want.

**Comment by jaimeMF** [comment]
You can use urlopen, either directly from [urllib.urlopen](https://docs.python.org/2/library/urllib.html#urllib.urlopen) or with YoutubeDL.urlopen:
```python
import youtube_dl
ydl = youtube_dl.YoutubeDL({'format': 'best'})

info = ydl.extract_info('http://www.youtube.com/watch?v=BaW_jenozKcj', download=False)

f = ydl.urlopen(info['url'])
try:
    print(f.read(100))
finally:
    f.close()
```
which produces:
```
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading video info webpage
[youtube] BaW_jenozKc: Extracting video information
[youtube] BaW_jenozKc: Downloading DASH manifest
[youtube] BaW_jenozKc: Downloading DASH manifest
b'\x00\x00\x00\x18ftypmp42\x00\x00\x00\x00isommp42\x00\x00\x14Qmoov\x00\x00\x00lmvhd\x00\x00\x00\x00\xce\xde\xfc\xd8\xce\xde\xfc\xd8\x00\x00\x02X\x00\x00\x17\x13\x00\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00'
```
