### ISSUE TITLE
Cannot download some video - Signature error 

### ISSUE THREAD

**Issue by rinaldohack** [rg3/youtube-dl#7808]
for example this : https://www.youtube.com/watch?v=ikhNSlFTpfw

http://musicstorage.club/downloader/video?url=https://www.youtube.com/watch?v=ikhNSlFTpfw
http://www.alltubedownload.net/video?url=https://www.youtube.com/watch?v=ikhNSlFTpfw

Except the directory path, the error is exactly same : 
ERROR: Signature extraction failed: Traceback (most recent call last): File "/home/rinaldo/public_html/downloader/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature video_id, player_url, s File "/home/rinaldo/public_html/downloader/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function cache_res = res(test_string) File "/home/rinaldo/public_html/downloader/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 796, in <lambda> return lambda s: initial_function([s]) File "/home/rinaldo/public_html/downloader/vendor/rg3/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf res, abort = self.interpret_statement(stmt, local_vars) File "/home/rinaldo/public_html/downloader/vendor/rg3/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement v = self.interpret_expression(expr, local_vars, allow_recursion) File "/home/rinaldo/public_html/downloader/vendor/rg3/youtube-dl/youtube_dl/jsinterp.py", line 135, in interpret_expression self._objects[variable] = self.extract_object(variable) File "/home/rinaldo/public_html/downloader/vendor/rg3/youtube-dl/youtube_dl/jsinterp.py", line 220, in extract_object fields = obj_m.group('fields') AttributeError: 'NoneType' object has no attribute 'group' (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 

Not sure where to report though, youtube-dl in terminal works.

**Comment by rinaldohack** [comment]
please note not every video gives an error. this one doesn't.

http://musicstorage.club/downloader/video?url=https://www.youtube.com/watch?v=agAVOrLum_k
.....

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
