### ISSUE TITLE
different Mac and Linux environment 

### ISSUE THREAD

**Issue by phukhanhlee** [rg3/youtube-dl#7809]
in Mac :
youtube-dl -g "https://www.youtube.com/watch?v=rYEDA3JcQqw"
https://r3---sn-8pxuuxa-nboe7.googlevideo.com/videoplayback?id=ad810303725c42ac&itag=170&source=youtube&requiressl=yes&pl=20&mm=31&mn=sn-8pxuuxa-nboe7&mv=m&ms=au&ratebypass=yes&mime=video/webm&gir=yes&clen=81629310&lmt=1366495546713728&dur=233.840&upn=yg4zHCrlPzQ&key=dg_yt0&signature=1684EFC80D57B0F0B023390AB04760A5BB7EF48E.5503CA539C22070A1AC2AD8D03344745B7C8CD2A&fexp=9416126,9416852,9417423,9418204,9418400,9420452,9422342,9422596,9423039,9423244,9423282,9423662,9424084,9424371&mt=1449654230&sver=3&ip=171.249.51.136&ipbits=0&expire=1449675968&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mm,mn,mv,ms,ratebypass,mime,gir,clen,lmt,dur
https://r3---sn-8pxuuxa-nboe7.googlevideo.com/videoplayback?id=ad810303725c42ac&itag=141&source=youtube&requiressl=yes&pl=20&mm=31&mn=sn-8pxuuxa-nboe7&mv=m&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=7459200&lmt=1394295263019491&dur=233.941&upn=yg4zHCrlPzQ&key=dg_yt0&signature=6A4C81B472CDED8EF8A71DCA4243E10DA8E69049.3057214B580184728E8551F243BBF698EB980A5F&fexp=9416126,9416852,9417423,9418204,9418400,9420452,9422342,9422596,9423039,9423244,9423282,9423662,9424084,9424371&mt=1449654230&sver=3&ip=171.249.51.136&ipbits=0&expire=1449675968&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mm,mn,mv,ms,ratebypass,mime,gir,clen,lmt,dur

-> we have both audio and video url 

in Ubuntu VPS :

youtube-dl -g "https://www.youtube.com/watch?v=rYEDA3JcQqw"
https://r13---sn-ab5l6n7r.googlevideo.com/videoplayback?fexp=9407116%2C9408213%2C9408495%2C9413141%2C9413272%2C9416126%2C9419451%2C9420452%2C9420716%2C9422596%2C9422927%2C9423662%2C9425057%2C9425962&ip=104.131.220.93&ratebypass=yes&itag=22&mm=31&ipbits=0&mn=sn-ab5l6n7r&mime=video%2Fmp4&ms=au&source=youtube&mv=m&initcwndbps=15757500&id=o-AJuIroq_ESDcInWQh2X4pErsVC7p0h_qYid8SlsmzDql&pl=21&dur=233.941&mt=1449654363&upn=9HbimbxRFQA&lmt=1394295353127708&expire=1449676094&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&sver=3&requiressl=yes&key=yt6&signature=CA0235E3F97277842596A27532DC4E798A9DAB4D.A00D9692FB50FFBD60B723EAFDDCAFF7972ADAE7

-> it's only return video url

There's something wrong here. I want to get audio for my service on VPS . Can you fixed it ?

**Comment by dstftw** [comment]
ffmpeg/avconv is installed in the first case and does not in the second case. [FAQ](https://github.com/rg3/youtube-dl#format-selection).

**Comment by phukhanhlee** [comment]
Ok thanks bro !!!
