### ISSUE TITLE
Mixcloud

### ISSUE THREAD

**Issue by mafrosis** [rg3/youtube-dl#7812]
> pip freeze | grep youtube-dl
    youtube-dl==2015.12.9
    > youtube-dl https://www.mixcloud.com/Pedestrian/dance-music-for-home-listening-vol1
    [mixcloud] Pedestrian-dance-music-for-home-listening-vol1: Downloading webpage
    [mixcloud] Pedestrian-dance-music-for-home-listening-vol1: Trying mp3 URL
    [mixcloud] Pedestrian-dance-music-for-home-listening-vol1: Trying m4a URL
    ERROR: Unable to extract track url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by mafrosis** [comment]
Apologies for not finding the `--verbose` flag. Nothing to see here :+1
