### ISSUE TITLE
Site Support Request: porn.com

### ISSUE THREAD

**Issue by UnveilTech** [rg3/youtube-dl#7815]
Hi,
Could you check porn.com and add it if possible, thanks in advance.

Have a nice day

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by UnveilTech** [comment]
Hi,
here is the sample:
./youtube-dl http://www.porn.com/videos/gorgeous-milf-hailey-loves-to-suck-on-cock-1941037
[generic] gorgeous-milf-hailey-loves-to-suck-on-cock-1941037: Requesting header
WARNING: Falling back on generic information extractor.
[generic] gorgeous-milf-hailey-loves-to-suck-on-cock-1941037: Downloading webpage
[generic] gorgeous-milf-hailey-loves-to-suck-on-cock-1941037: Extracting information
ERROR: Unsupported URL: http://www.porn.com/videos/gorgeous-milf-hailey-loves-to-suck-on-cock-1941037

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.
