### ISSUE TITLE
Some pages are returning 403, even after clearing cache

### ISSUE THREAD

**Issue by priestc** [rg3/youtube-dl#7835]
$ youtube-dl "http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/ZRnhDfUtggGkq5aSq0QHCZoUwjXnr4e4/the-late-show-12-9-2015-michelle-dockery-hugh-bonneville-allen-leech-adam-mckay-kurt-vile-/"
    [CBS] the-late-show-12-9-2015-michelle-dockery-hugh-bonneville-allen-leech-adam-mckay-kurt-vile-: Downloading webpage
    [ThePlatform] 1trh1IG6mVd6: Downloading SMIL data
    [ThePlatform] 1trh1IG6mVd6: Downloading m3u8 information
    [ThePlatform] 1trh1IG6mVd6: Downloading m3u8 information
    [ThePlatform] 1trh1IG6mVd6: Downloading m3u8 information
    [ThePlatform] 1trh1IG6mVd6: Downloading m3u8 information
    [ThePlatform] 1trh1IG6mVd6: Downloading m3u8 information
    [ThePlatform] 1trh1IG6mVd6: Downloading m3u8 information
    [ThePlatform] 1trh1IG6mVd6: Downloading m3u8 information
    [ThePlatform] 1trh1IG6mVd6: Downloading JSON metadata
    [download] Destination: The Late Show - 12_9_2015 (Michelle Dockery, Hugh Bonneville, Allen Leech, Adam McKay, Kurt Vile)-1trh1IG6mVd6.mp4
    WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
    avconv version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
      built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
    [https @ 0x22481a0] HTTP error 403 Forbidden
    Unable to open key file https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2015/12/07/581689923778/CBS_COLBERT_0055_CONTENT_CIAN_steamclip_701245_,548,3596,2596,1848,1248,848,298,158,000.mp4.csmil/crypt.key?null=&id=AgCuS0FjuLR8Hc0nalZ7HgiLIumlPUQKS5UF+4%2fR+zXX3tn7Kv1Q%2fX12cxjJhSUSHH2Qj57oclCKrw%3d%3d
    [http @ 0x2248360] HTTP error 403 Forbidden
    [crypto @ 0x22481a0] Unable to open input
    https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2015/12/07/581689923778/CBS_COLBERT_0055_CONTENT_CIAN_steamclip_701245_,548,3596,2596,1848,1248,848,298,158,000.mp4.csmil/index_1_av.m3u8?null=&id=AgCuS0FjuLR8Hc0nalZ7HgiLIumlPUQKS5UF+4%2fR+zXX3tn7Kv1Q%2fX12cxjJhSUSHH2Qj57oclCKrw%3d%3d: Input/output error

    ERROR: avconv exited with code 1

I tried doing `youtube-dl --rm-cache-dir` but I still get the 403 error.

Some videos work, some don't.

**Comment by remitamine** [comment]
this should be fixed with f1028194636e7acafb29fb38244cc7b1347d9313.
