### ISSUE TITLE
Destination folder defaults to 'SysWOW64'

### ISSUE THREAD

**Issue by Feltes** [rg3/youtube-dl#7836]
I found the files were being downloaded to 'C:\Windows\SysWOW64'. Every other time I've run, files downloaded to the exe directory. Is it pulling a resource from that directory and then not moving on? Any fix?

W10 64 bit

**Comment by dstftw** [comment]
Destination folder defaults to the current directory you execute youtube-dl from. Don't run it from `C:\Windows\SysWOW64` and you won't get files downloaded to this directory.

**Comment by Feltes** [comment]
I've run this from the user desktop in all cases. Just tested on a w7 64 bit and it DL'ed to C:/users/{user}

How is the program determining these output locations?
