### ISSUE TITLE
error during download movie from youtube

### ISSUE THREAD

**Issue by aep99** [rg3/youtube-dl#7840]
Dears,
I have gotten some error messages during download from Youtube:
===================================================================
kindly your support/ advice to solved it please.
Signature extraction failed: Traceback (most recent call last): 
File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", 
line 771, in _decrypt_signature video_id, player_url, s
File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", 
line 663, in _extract_signature_function 
raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player 
u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl2sXoyn/base.js'; 
==================================================================
Thank you in advance for your reply.
Best regards,
aep99.

**Comment by phihag** [comment]
Sorry, we cannot help you without the full output of youtube-dl when called with `-v`. See our [bug reporting guidelines for more information](https://yt-dl.org/reporting). In particular, this output will tell us whether you are using the newest version, 2015.12.10 as of writing. If you are not, please make sure to update to the newest version first.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
