### ISSUE TITLE
Break.com HTTP Error 404, when used with '-f best'

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#7845]
If I use the '-f best' option with:
http://www.break.com/video/alton-brown-reviews-strange-kitchen-gadgets-2986876
...it fails (see output below)

However 
A) if I do not use the '-f best' options is DOES work
b) if I use the '-f best' option with the direct YouTube URL (https://www.youtube.com/watch?v=FgFeVlw2Ywg)...it DOES work

Output: 
youtube-dl.py -v -f best "http://www.break.com/video/alton-brown-reviews-strange-kitchen-gadgets-2986876"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'best', u'http://www.break.com/video/alton-brown-reviews-strange-kitchen-gadgets-2986876']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.10
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[Break] 2986876: Downloading webpage
[youtube] FgFeVlw2Ywg: Downloading webpage
[youtube] FgFeVlw2Ywg: Downloading video info webpage
[youtube] FgFeVlw2Ywg: Extracting video information
[youtube] FgFeVlw2Ywg: Downloading DASH manifest
[youtube] FgFeVlw2Ywg: Downloading DASH manifest
[debug] Invoking downloader on u'https://r1---sn-cxaaj5o5q5-tt16.googlevideo.com/videoplayback?dur=338.570&initcwndbps=10890000&sver=3&expire=1449876488&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2C
itag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&source=youtube&upn=LbwckiqC9ok&signature=C8DBB42C1819E818E26420E0A7E4BF05C2B5C117.1EA722D3F00F50E
9806015CA7E146E664A00AC61&ratebypass=yes&lmt=1449690918520320&key=yt6&itag=22&pcm2cms=yes&mn=sn-cxaaj5o5q5-tt16&mm=31&pl=24&mime=video%2Fmp4&id=o-AIIBI6VsLTKnHHe1Ogs9e4OzMZZLy9wyavxTZEu08YmC&ipbits=0&
requiressl=yes&ip=199.85.73.12&mv=m&mt=1449854705&ms=au&fexp=9406983%2C9416126%2C9420452%2C9422596%2C9423662'
[download] Resuming download at byte 49807360
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1607, in process_info
    success = dl(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1549, in dl
    return fd.download(name, info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1884, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

Thanks always 
Ringo

**Comment by dstftw** [comment]
Works fine for me.
>[download] Resuming download at byte 49807360

Can you reproduce this with fresh download?

**Comment by RingoTheDog** [comment]
hmmm....
still failed multiple times yesterday...but seems to work today.

thanks and/or sorry to bother
