### ISSUE TITLE
Unexpected behaviour downloading from youtube with options '--prefer-ffmpeg -g': Repeats download link

### ISSUE THREAD

**Issue by putridp** [rg3/youtube-dl#7847]
Example: $youtube-dl --prefer-ffmpeg -g https://www.youtube.com/watch?v=YQHsXMglC9A

Observed behaviour: Outputs the download link to stdout twice.
Expected behaviour: Output download link only once.

**Comment by dstftw** [comment]
This is [expected behavior](https://github.com/rg3/youtube-dl/issues/7456#issuecomment-155783819).
