### ISSUE TITLE
Display current latest version on GitHub when using the `--update` option if other software management solution is used on system

### ISSUE THREAD

**Issue by Vdragon** [rg3/youtube-dl#7849]
Please support fetching & showing the latest release when using the `--update` option on systems using alternative software management solution, it's useful to check whether your youtube-dl distribution is the latest.

**Comment by dstftw** [comment]
We have no control over alternative software management solution therefore they decide themselves how to update their packages.

**Comment by Vdragon** [comment]
@dstftw 
Hi, I mean showing/printing only the latest upstream "version number" instead of updating the software, so it's not related to upgrading using alternative software management solution.

You can check the latest version by launching a web browser and browse the [Releases page](https://github.com/rg3/youtube-dl/releases) but it's better if youtube-dl could show it itself.

**Comment by dstftw** [comment]
I don't think mixing official version and package version is a good idea since it can be misleading. Moreover most likely this will be patched out by package maintainers.

**Comment by yan12125** [comment]
@Vdragon FYI: The latest version number can be fetched from https://rg3.github.io/youtube-dl/update/LATEST_VERSION.

**Comment by Vdragon** [comment]
@dstftw 
IMO as long as the message isn't misleading its a good idea.

@yan12125 
Thanks, highly appreciated!
