### ISSUE TITLE
Homebrew installed: cannot update using `youtube-dl -U`

### ISSUE THREAD

**Issue by quinncomendant** [rg3/youtube-dl#7853]
When using brew, `youtube-dl -U` fails because the program tries to update `/usr/local/bin/youtube-dl`, which is a symlink with no write permission. The program should detect if it is installed via brew and recommend `brew upgrade youtube-dl` instead.

**Comment by dstftw** [comment]
You should report this to homebrew. Note that it's [up to date in homebrew](https://github.com/Homebrew/homebrew/pull/46878).

**Comment by quinncomendant** [comment]
Yeah, I discovered that. I had to run `brew update` before the newer version was available to brew. :-|

Still might be useful to avoid displaying the message, `Make sure you are using the latest version; type  youtube-dl -U  to update`, and instead display `brew update && brew upgrade youtube-dl` if it is a brew install.

**Comment by dstftw** [comment]
When you type `youtube-dl -U` it will suggest using package manager. We can't determine all the package managers that exist and output corresponding message. User should know this himself.
