### ISSUE TITLE
Can you write the outtmp to memory?

### ISSUE THREAD

**Issue by nadermx** [rg3/youtube-dl#7855]
I've been trying for some time now to have youtube-dl output the mp3 into a temporary file so I can migrate it or write straight to amazon s3.

Every iteration I have tried from BytesIO to Lambda returns ```AttributeError: xxxinstance has no attribute 'startswith'``` 

I saw that there is the ``` '-o -': True``` option which streams the data.  What I'm wondering is if it would be possible to use that or how I would go about trying to get this to output to amazon S3

using the boto3 library you can do something along these lines 
```
    # Upload the file to S3
    s3_client.upload_file(temp_filepath, bucketname, output_filepath)

    # Download the file from S3
    s3_client.download_file(bucketname, output_filepath, output_filepath)
```

Here is what I currently have which is still not working.

```
    output = output_filepath = open('music/%s.mp3' % audio_filename)

    ydl_opts = {
    'format': 'bestaudio/best', # choice of quality
    'extractaudio' : True,      # only keep the audio
    'outtmpl': output,  # name the location
    # '-o -': True,               #to stream content out
    'noplaylist' : True,        # only download single song, not playlist
    'prefer-ffmpeg' : True,
    # 'verbose': True,
    'postprocessors': [{
            'key': 'FFmpegMetadata'
            },
            {
      'key': 'FFmpegExtractAudio',
      'preferredcodec': 'mp3',
      'preferredquality': '192',
      }],
    'logger': MyLogger(),
    'progress_hooks': [my_hook],
     }

    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
      result = ydl.download([url])


```

**Comment by dstftw** [comment]
You have been [already clarified that `outtmpl` **must** be string](https://github.com/rg3/youtube-dl/issues/7770). If you want to stream to stdout set `outtmpl` to `-`.
