### ISSUE TITLE
Format selection

### ISSUE THREAD

**Issue by Hazae41** [rg3/youtube-dl#7856]
When I use -f "best[height<=1440]" it selects 720p instead of 1440

**Comment by yan12125** [comment]
Which URL are you trying to download?

**Comment by Hrxn** [comment]
Depends on the availability of the formats..

But you seem to forgot to post the format list.

**Comment by Hazae41** [comment]
Any YouTube URL

144p, 240p, 360p, 480p, 720p, 1080p, 1440p, 2160p, ...

**Comment by dstftw** [comment]
@Hazae41 post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).
