### ISSUE TITLE
Site request: espnfc

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#7858]
ESPN Football site...I think should use the same extractor as ESPN, just need the URL to be recognized.

URL: http://www.espnfc.us/video/mls-highlights/150/video/2743663/must-see-moments-best-of-the-mls-season
OUTPUT: 
youtube-dl -v "http://www.espnfc.us/video/mls-highlights/150/video/2743663/m
ust-see-moments-best-of-the-mls-season"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.espnfc.us/video/mls-highlights/1
50/video/2743663/must-see-moments-best-of-the-mls-season']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.06
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[generic] must-see-moments-best-of-the-mls-season: Requesting header
WARNING: Falling back on generic information extractor.
[generic] must-see-moments-best-of-the-mls-season: Downloading webpage
[generic] must-see-moments-best-of-the-mls-season: Extracting information
[debug] Invoking downloader on u'https://sw88.go.com/b/ss/wdgespvideo/5.4/REDIR/
031615570333296051449504376310?D=..&url=https://once.unicornmedia.com/now/od/aut
o/07355f66-a73e-46c2-885b-e769dac7c817/20879ce0-ad85-4acf-b0b4-f4a91a6c1517/ac99
a7e5-7c12-4327-919f-a1a18597cd52/content.once?UMADPARAMreferer=http://espnfc.com
/video/espnfc/video?id=2743663&pe=media&mediaName=SOCCER::FCUS_MLS::+Must+See+Mo
ments:+Best+of+the+MLS+season_2743663&mediaLength=00:03:31&mediaPlayer=embed09&m
ediaSession=0-0&c3=videoid=SOCCER::FCUS_MLS::+Must+See+Moments:+Best+of+the+MLS+
season_2743663&v2=videoid=SOCCER::FCUS_MLS::+Must+See+Moments:+Best+of+the+MLS+s
eason_2743663&events=event1&v52=inlinePlayer&c52=inlinePlayer&v53=inlinePlayer:t
witter&c53=inlinePlayer:twitter'

ERROR: Did not get any data blocks
File "main.py", line 19, in 
File "youtube_dl__init__.pyo", line 410, in main
File "youtube_dl__init__.pyo", line 400, in _real_main
File "youtube_dl\YoutubeDL.pyo", line 1669, in download
File "youtube_dl\YoutubeDL.pyo", line 674, in extract_info
File "youtube_dl\YoutubeDL.pyo", line 720, in process_ie_result
File "youtube_dl\YoutubeDL.pyo", line 1339, in process_video_result
File "youtube_dl\YoutubeDL.pyo", line 1601, in process_info
File "youtube_dl\YoutubeDL.pyo", line 1543, in dl
File "youtube_dl\downloader\common.pyo", line 342, in download
File "youtube_dl\downloader\http.pyo", line 230, in real_download
File "youtube_dl\downloader\common.pyo", line 155, in report_error
File "youtube_dl\YoutubeDL.pyo", line 538, in report_error
File "youtube_dl\YoutubeDL.pyo", line 500, in trouble

(was originally part of: https://github.com/rg3/youtube-dl/issues/7785#issuecomment-164236130)

Thanks
Ringo

**Comment by davidjameshowell** [comment]
Hi,

I'm looking in to writing an extractor for this. I believe this should be a separate extractor due to the site differences. Although they belong to the same company, they use different platforms for delivery.

**Comment by davidjameshowell** [comment]
Actually looking into this (and some backend knowledge with ESPN), for FC content it'll use "intl:<id>" as a foreign key/video ID. 

I already made a ESPNFC extractor that utilizes Brightcove's Once link. I'll let the team decide what they want to do.
