### ISSUE TITLE
Site Support Request: porntube.com

### ISSUE THREAD

**Issue by ArtemProkopenko** [rg3/youtube-dl#7859]
youtube-dl http://www.porntube.com/videos/petra-short-lusty-babe-hard-ball-gagging_1043072
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.porntube.com/videos/petra-short-lusty-babe-hard-ball-gagging_1043072

**Comment by TristanMariachi** [comment]
You have download button in this site... :)
but nice video, thanks

**Comment by ArtemProkopenko** [comment]
Youtube-ld often used for automatic downloads within other programs.
