### ISSUE TITLE
Feature request (if the information is available in the API): Artist/song title information

### ISSUE THREAD

**Issue by blha303** [rg3/youtube-dl#7862]
Some videos have a Music section in the description that shows the artist and title of a recognized song. For example, [this video](https://www.youtube.com/watch?v=SrkeWsQZNyU) has *Music: "Mr. Brightside" by The Killers* at the bottom. Is there a way to retrieve that information with the Youtube API, and can that information be returned in the youtube-dl json or with a switch?

**Comment by dstftw** [comment]
These field will be available as `alt_title` and `creator` is JSON in the next version of youtube-dl.
