### ISSUE TITLE
Ffprobe error on php exec

### ISSUE THREAD

**Issue by BarisBey** [rg3/youtube-dl#7863]
ffprobe or avprobe not found

 Php command: exec('youtube-dl -4 https://www.youtube.com/watch?v=JP4kValjHmw --extract-audio --audio-format mp3 -o deneme.mp3');

Same with shell_exec.

But no problem in user or root ssh.

Ffmpeg, youtube-dl, ffprobe, libav-tools installed.

ffprobe not found problem is in PHP exec/shell_exec only.

    ffprobe version git-2015-12-13-906c0b7 Copyright (c) 2007-2015 the FFmpeg developers
  built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-16)
  configuration: --prefix=/root/ffmpeg_build --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --bindir=/usr/local/bin --pkg-config-flags=--static --enable-gpl --enable-nonfree --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265
  libavutil      55. 10.100 / 55. 10.100
  libavcodec     57. 17.100 / 57. 17.100
  libavformat    57. 20.100 / 57. 20.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 21.100 /  6. 21.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Simple multimedia streams analyzer
usage: ffprobe [OPTIONS] [INPUT_FILE]

You have to specify one input file.
Use -h to get full help or, even better, run 'man ffprobe'.

**Comment by yan12125** [comment]
Here's a similar case: #7278

**Comment by BarisBey** [comment]
my ffmpeg in /usr/local/bin
this is very spesific problem. i tried all search tips on google. Not found true solution for this.

**Comment by BarisBey** [comment]
and user's shell command running correctly. No problem on shell/shh commands. Problem is in PHP exec command only.

**Comment by BarisBey** [comment]
exec("/usr/local/bin/ffprobe -version 2>&1", $output);
var_dump($output);

array(11) { [0]=> string(84) "ffprobe version git-2015-12-13-906c0b7 Copyright (c) 2007-2015 the FFmpeg developers" [1]=> string(54) "built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-16)" [2]=> string(356) "configuration: --prefix=/root/ffmpeg_build --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --bindir=/usr/local/bin --pkg-config-flags=--static --enable-gpl --enable-nonfree --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265" [3]=> string(38) "libavutil 55. 10.100 / 55. 10.100" [4]=> string(38) "libavcodec 57. 17.100 / 57. 17.100" [5]=> string(38) "libavformat 57. 20.100 / 57. 20.100" [6]=> string(38) "libavdevice 57. 0.100 / 57. 0.100" [7]=> string(38) "libavfilter 6. 21.100 / 6. 21.100" [8]=> string(38) "libswscale 4. 0.100 / 4. 0.100" [9]=> string(38) "libswresample 2. 0.101 / 2. 0.101" [10]=> string(38) "libpostproc 54. 0.100 / 54. 0.100" }

**Comment by yan12125** [comment]
What's the output of:
```
exec("ffprobe -version 2>&1", $output);
```
If the command listed above fails on PHP, you should either set correct ```$PATH``` or append the following parameters to youtube-dl:
```
--ffmpeg-location /usr/local/bin/
```
See [Post-Processing options](https://github.com/rg3/youtube-dl#post-processing-options) for more information.

**Comment by BarisBey** [comment]
exec("ffprobe -version 2>&1", $output);
var_dump($output);

array(11) { [0]=> string(84) "ffprobe version git-2015-12-13-906c0b7 Copyright (c) 2007-2015 the FFmpeg developers" [1]=> string(54) "built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-16)" [2]=> string(356) "configuration: --prefix=/root/ffmpeg_build --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --bindir=/usr/local/bin --pkg-config-flags=--static --enable-gpl --enable-nonfree --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265" [3]=> string(38) "libavutil 55. 10.100 / 55. 10.100" [4]=> string(38) "libavcodec 57. 17.100 / 57. 17.100" [5]=> string(38) "libavformat 57. 20.100 / 57. 20.100" [6]=> string(38) "libavdevice 57. 0.100 / 57. 0.100" [7]=> string(38) "libavfilter 6. 21.100 / 6. 21.100" [8]=> string(38) "libswscale 4. 0.100 / 4. 0.100" [9]=> string(38) "libswresample 2. 0.101 / 2. 0.101" [10]=> string(38) "libpostproc 54. 0.100 / 54. 0.100" }

**Comment by BarisBey** [comment]
Yesssss! Finally! 

exec ("youtube-dl -4 " . escapeshellarg($url) . " --extract-audio --audio-format mp3 -o " .
          escapeshellarg($template).' --ffmpeg-location /usr/local/bin/');

resolved my problem. Thank you very much.

Best wishes from Turkey.

**Comment by yan12125** [comment]
Glad to see it's solved. Closing.
