### ISSUE TITLE
noco.tv: Unable to download JSON metadata: HTTP Error 401

### ISSUE THREAD

**Issue by MacCamintosh** [rg3/youtube-dl#7864]
Hello!
Since the lasts days, I'm unable to download videos from noco.tv.
youtube-dl is up-to-date (2015.12.13)
here's the log :

iMac-de-Camille:~ camille$ youtube-dl --verbose -u MacCamintosh http://noco.tv/emission/24657/nolife/kyo-no-wanko/4161-ryu
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-u', u'PRIVATE', u'http://noco.tv/emission/24657/nolife/kyo-no-wanko/4161-ryu']
Type account password and press [Return]: 
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8, rtmpdump 2.4
[debug] Proxy map: {}
[Noco] Logging in as MacCamintosh
[Noco] 24657: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 329, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1884, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dsferruzza** [comment]
Hi!

Same problem for me, on Win 7 :(

```
youtube-dl is up-to-date (2015.12.13)
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--no-part', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'http://noco.tv/emission/24538/nolife/l-hippodrole-de-nolife/13', u'-vv']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-74700-g628a73f, ffprobe N-74700-g628a73f
[debug] Proxy map: {}
[Noco] Logging in as [valid user; I can access to the website]
[Noco] 24538: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1884, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default
```

**Comment by dstftw** [comment]
Works fine for me. Can you watch it in browser in the first place?

**Comment by MacCamintosh** [comment]
Yes. I can play the video with Chrome without problems.

**Comment by dstftw** [comment]
Can you download the video from the second post with/without account credentials?

**Comment by dsferruzza** [comment]
The video from my post wasn't free (but I used my credentials).
I also have the problem with this free video, which I can watch in Firefox:

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-U', u'--no-part', u'http://noco.tv/emission/24672/nolife/le-point-sur-nolife/', u'-vv']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-74700-g628a73f, ffprobe N-74700-g628a73f
[debug] Proxy map: {}
youtube-dl is up-to-date (2015.12.13)
[Noco] 24672: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1884, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default
```

**Comment by dstftw** [comment]
Then you'll have to provide account credentials or suggest any other way to reproduce since it works fine for my account.

**Comment by MacCamintosh** [comment]
I tried with the video from the second post with and without my Noco.tv account : same result.
I also tried with this free (for a month) video : http://noco.tv/emission/24672/nolife/le-point-sur-nolife/ with and without my account : same.

**Comment by dsferruzza** [comment]
I have a bit more info using the `--print-traffic` flag:

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-vv', u'http://noco.tv/emission/24672/nolife/le-point-sur-nolife/', u'--print-traffic']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-74700-g628a73f, ffprobe N-74700-g628a73f
[debug] Proxy map: {}
[Noco] 24672: Downloading video JSON
send: u'GET /1.1/shows/24672/medias?ts=1450193412655&tk=74fd5a52e6b97429ce450de5953e09a4 HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: api.noco.tv\r\n\r\n'
reply: 'HTTP/1.1 401 Unauthorized\r\n'
header: Server: nginx
header: Date: Tue, 15 Dec 2015 15:34:27 GMT
header: Content-Type: text/html; charset=utf-8
header: Transfer-Encoding: chunked
header: Connection: close
header: cache-control: no-cache
header: Access-Control-Allow-Methods: GET, POST, PUT, DELETE
header: Allow: GET, POST, PUT, DELETE
header: Access-Control-Allow-Credentials: true
header: Access-Control-Allow-Origin: http://noco.tv
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1884, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default
```

*This video work in Firefox and is free (it works in Firefox even if I am not logged in).*

**Comment by MacCamintosh** [comment]
@dstftw Okay, I've just send to you my logins on your gmail box.

**Comment by dsferruzza** [comment]
It works perfectly for me since today's release! (`2015.12.18`)
Thanks a lot!
