### ISSUE TITLE
ExtractorError bbc iplayer on linux

### ISSUE THREAD

**Issue by perlop** [rg3/youtube-dl#7866]
$ youtube-dl --verbose http://www.bbc.co.uk/iplayer/cbbc/episode/b06s6hkw/the-next-step-series-3-29-shes-not-you
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.bbc.co.uk/iplayer/cbbc/episode/b06s6hkw/the-next-step-series-3-29-shes-not-you']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Linux-4.2.6-301.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] b06s6hkw: Downloading video page
[bbc.co.uk] b06s6hc3: Downloading media selection XML
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 400: Bad Request
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 483, in _real_extract
    self._sort_formats(formats)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
It's geo restricted. Can you watch it in browser?

**Comment by perlop** [comment]
Hi. When it is geo-restricted it throws an error. 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.bbc.co.uk/iplayer/cbbc/episode/b06s6hkw/the-next-step-series-3-29-shes-not-you']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Linux-4.2.6-301.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] b06s6hkw: Downloading video page
[bbc.co.uk] b06s6hc3: Downloading media selection XML
[bbc.co.uk] b06s6hc3: Downloading media selection XML
ERROR: bbc.co.uk returned error: geolocation
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 336, in _download_media_selector
    mediaselector_url % programme_id, programme_id)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 353, in _download_media_selector_url
    return self._process_media_selector(media_selection, programme_id)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 359, in _process_media_selector
    for media in self._extract_medias(media_selection):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 268, in _extract_medias
    raise BBCCoUkIE.MediaSelectionError(error.get('id'))
MediaSelectionError
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 473, in _real_extract
    formats, subtitles = self._download_media_selector(programme_id)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 342, in _download_media_selector
    self._raise_extractor_error(last_exception)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 329, in _raise_extractor_error
    expected=True)
ExtractorError: bbc.co.uk returned error: geolocation

I tried get_iplayer and it could rip although for some reason only the SD video. On chrome I get an error 'This content doesnt seem to be working' and a button 'try again', in both SD and HD.

**Comment by dstftw** [comment]
If you can't watch it in browser you won't be able to download it.
It's geo restricted and works with UK proxy:
```
> youtube-dl http://www.bbc.co.uk/iplayer/cbbc/episode/b06s6hkw/the-next-step-series-3-29-shes-not-you  -F --proxy 104.238.187.214:3128
[bbc.co.uk] b06s6hkw: Downloading video page
[bbc.co.uk] b06s6hc3: Downloading media selection XML
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
[info] Available formats for b06s6hc3:
format code                                                             extension  resolution note
stream-uk-iptv_streaming_concrete_combined_hd_mf_akamai_uk_hls-meta     mp4        multiple   Quality selection URL , h264@8490k
stream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_hls-meta  mp4        multiple   Quality selection URL , h264@8490k
iplayer_stb_streaming_sd_akamai_hls_open-meta                           mp4        multiple   Quality selection URL , h264@ 796k, 124.75MiB
iptv_streaming_1500_akamai_hls_open-meta                                mp4        multiple   Quality selection URL , h264@1500k, 233.42MiB
iplayer_stb_streaming_hd_akamai_hls_open-meta                           mp4        multiple   Quality selection URL , h264@2800k, 372.93MiB
iplayer_stb_streaming_sd_akamai_hls_open-796                            mp4        640x360     796k , h264@ 796k,  mp4a, 124.75MiB
iptv_streaming_1500_akamai_hls_open-796                                 mp4        832x468     796k , h264@1500k,  mp4a, 233.42MiB
iplayer_stb_streaming_hd_akamai_hls_open-796                            mp4        1280x720    796k , h264@2800k,  mp4a, 372.93MiB
stream-uk-iptv_streaming_concrete_combined_hd_mf_akamai_uk_hls-1012     mp4        1920x1080  1012k , h264@8490k, avc1
stream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_hls-1012  mp4        1920x1080  1012k , h264@8490k, avc1
iplayer_stb_streaming_sd_akamai_hls_open-1496                           mp4        640x360    1496k , h264@ 796k,  mp4a, 124.75MiB
iptv_streaming_1500_akamai_hls_open-1496                                mp4        832x468    1496k , h264@1500k,  mp4a, 233.42MiB
iplayer_stb_streaming_hd_akamai_hls_open-1496                           mp4        1280x720   1496k , h264@2800k,  mp4a, 372.93MiB
stream-uk-iptv_streaming_concrete_combined_hd_mf_akamai_uk_hls-1799     mp4        1920x1080  1799k , h264@8490k, avc1
stream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_hls-1799  mp4        1920x1080  1799k , h264@8490k, avc1
iplayer_stb_streaming_sd_akamai_hls_open-2395                           mp4        640x360    2395k , h264@ 796k,  mp4a, 124.75MiB
iptv_streaming_1500_akamai_hls_open-2395                                mp4        832x468    2395k , h264@1500k,  mp4a, 233.42MiB
iplayer_stb_streaming_hd_akamai_hls_open-2395                           mp4        1280x720   2395k , h264@2800k,  mp4a, 372.93MiB
stream-uk-iptv_streaming_concrete_combined_hd_mf_akamai_uk_hls-3116     mp4        1920x1080  3116k , h264@8490k, avc1
stream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_hls-3116  mp4        1920x1080  3116k , h264@8490k, avc1
stream-uk-iptv_streaming_concrete_combined_hd_mf_akamai_uk_hls-5509     mp4        1920x1080  5509k , h264@8490k, avc1
stream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_hls-5509  mp4        1920x1080  5509k , h264@8490k, avc1  (best)

> youtube-dl http://www.bbc.co.uk/iplayer/cbbc/episode/b06s6hkw/the-next-step-series-3-29-shes-not-you --proxy 104.238.187.214:3128
[bbc.co.uk] b06s6hkw: Downloading video page
[bbc.co.uk] b06s6hc3: Downloading media selection XML
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
[bbc.co.uk] b06s6hc3: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 170
[download] Destination: The Next Step, Series 3 - 29. She's Not You-b06s6hc3.mp4
[download]   0.0% of ~781.31MiB at 127.72KiB/s ETA 01:56:09
ERROR: Interrupted by user
```
