### ISSUE TITLE
Option "--yes-playlist" ignored.

### ISSUE THREAD

**Issue by IlyaIndigo** [rg3/youtube-dl#7867]
youtube-dl --yes-playlist https://www.youtube.com/watch?v=-TqYul6LOyQ&list=PL5FMLPRj1j6IChoB7nBKYNjCNQ-DBnaq7
By default, even when using --yes-playlist is loaded only video шт v= parameter.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by dstftw** [comment]
Most likely you [didn't escape the ampersands](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).

**Comment by IlyaIndigo** [comment]
ilya@ilya:/tmp> youtube-dl --yes-playlist --verbose https://www.youtube.com/watch?v=-TqYul6LOyQ&list=PL5FMLPRj1j6IChoB7nBKYNjCNQ-DBnaq7 
[1] 18948
ilya@ilya:/tmp> [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--yes-playlist', u'--verbose', u'https://www.youtube.com/watch?v=-TqYul6LOyQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.10
[debug] Python version 2.7.10 - Linux-4.3.0-2-default-x86_64-with-SuSE-20151209-x86_64
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3
[debug] Proxy map: {}
[youtube] -TqYul6LOyQ: Downloading webpage
[youtube] -TqYul6LOyQ: Downloading video info webpage
[youtube] -TqYul6LOyQ: Extracting video information
[youtube] -TqYul6LOyQ: Downloading DASH manifest
[youtube] -TqYul6LOyQ: Downloading DASH manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r2---sn-3c27ln7s.googlevideo.com/videoplayback?id=f93a98ba5e8b3b24&itag=137&source=youtube&requiressl=yes&mn=sn-3c27ln7s&mm=31&ms=au&mv=m&pl=22&ratebypass=yes&mime=video/mp4&gir=yes&clen=132198831&lmt=1449981287320450&dur=877.320&fexp=9408507,9413208,9416126,9418182,9418401,9418898,9419355,9420452,9422596,9423037,9423662,9424038,9424822,9424978,9425346,9425471,9425620,9425747&mt=1450111289&upn=Z7NXZP8UbJk&key=dg_yt0&signature=0AAAC937EA511F417926AFF4995BD00643ECF95B.7A976B110C6BAD08593D6B849F2A11481402E7F5&sver=3&ip=178.150.103.17&ipbits=0&expire=1450133114&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,mm,ms,mv,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Сетевые технологии с Дмитрием Бачило - Mosix--TqYul6LOyQ.f137.mp4
[download] 100% of 126.07MiB in 02:08
[debug] Invoking downloader on u'https://r2---sn-3c27ln7s.googlevideo.com/videoplayback?mime=audio%2Fwebm&requiressl=yes&signature=5AA74BDD9CCC0D66046120B6CD342D2FBA8EB4C8.27964CA7A2B7002DD5D9394167692515457251C4&source=youtube&clen=14011349&mn=sn-3c27ln7s&upn=hNjwm8BA6wE&itag=251&pl=22&mt=1450111467&ms=au&expire=1450133113&mm=31&keepalive=yes&id=o-AKuYWmCnaRk5eHwF-0zprz3NvCKRB7XFJOIYinIRbpNI&sver=3&gir=yes&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&key=yt6&lmt=1449586728382662&dur=877.381&fexp=9408507%2C9413208%2C9416126%2C9418182%2C9418401%2C9418898%2C9419355%2C9420452%2C9422596%2C9423037%2C9423662%2C9424038%2C9424822%2C9424978%2C9425346%2C9425471%2C9425620%2C9425747&ip=178.150.103.17&mv=m&ipbits=0&initcwndbps=3073750&ratebypass=yes'
[download] Destination: Сетевые технологии с Дмитрием Бачило - Mosix--TqYul6LOyQ.f251.webm
[download] 100% of 13.36MiB in 00:07
[ffmpeg] Merging formats into "Сетевые технологии с Дмитрием Бачило - Mosix--TqYul6LOyQ.mkv"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Сетевые технологии с Дмитрием Бачило - Mosix--TqYul6LOyQ.f137.mp4' -i 'file:Сетевые технологии с Дмитрием Бачило - Mosix--TqYul6LOyQ.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Сетевые технологии с Дмитрием Бачило - Mosix--TqYul6LOyQ.temp.mkv'
Deleting original file Сетевые технологии с Дмитрием Бачило - Mosix--TqYul6LOyQ.f137.mp4 (pass -k to keep)
Deleting original file Сетевые технологии с Дмитрием Бачило - Mosix--TqYul6LOyQ.f251.webm (pass -k to keep)

[1]+  Done                    youtube-dl --yes-playlist --verbose https://www.youtube.com/watch?v=-TqYul6LOyQ

**Comment by rg3** [comment]
You need to enclose the URL in single or double quotes, or the ampersand is going to be interpreted by the shell and youtube-dl will not receive the text after it. This type of problem is documented in the FAQ.

https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by IlyaIndigo** [comment]
Thank you, about escaping ampersand I understood.
But why --yes-playlist option is not used by default?
Youtube works with playlists this way. It is logical to set this behavior by default.

**Comment by dstftw** [comment]
`--yes-playlist` **is default**. You only need to properly escape `&`.

**Comment by IlyaIndigo** [comment]
Sorry. Indeed default.
It mpv without option "ytdl-raw-options=yes-playlist=" does not play a playlist.
