### ISSUE TITLE
Error 10061 No Connection coukd be made

### ISSUE THREAD

**Issue by Guennifresh** [rg3/youtube-dl#7868]
C:\Users\guenni\Downloads>youtube-dl --verbose https://www.youtube.com
/watch?v=5p7qal4D2Zk
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=5p7q
al4D2Zk']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {'ftp': 'ftp://localhost:8080', 'http': 'http://localhost:808
0', 'https': 'https://localhost:8080'}
[youtube] 5p7qal4D2Zk: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 10061] Es konnte keine
Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte> (
caused by URLError(error(10061, 'Es konnte keine Verbindung hergestellt werden,
da der Zielcomputer die Verbindung verweigerte'),))
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1878, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 805, in https_open
  File "urllib2.pyo", line 1197, in do_open

**Comment by dstftw** [comment]
Does your proxy up and running?

**Comment by Guennifresh** [comment]
Good day,
i have got no proxy running, i dunno if youtube-dl does read out of old iptables... youtube-dl worked fine about one year, but since a few month it stopped. 
It worked great and did a good job, thanks for that ! I did not change a thing in my usage.
Merry christmas :-)

**Comment by Hrxn** [comment]
I'd bet on some issue with a firewall.

Which firewall(s) are up and running?

**Comment by dstftw** [comment]
>[debug] Proxy map: {'ftp': 'ftp://localhost:8080', 'http': 'http://localhost:808
0', 'https': 'https://localhost:8080'}

You have proxy setup with env variable, remove `HTTP_PROXY` env variable or pass `--proxy ""` to youtube-dl.
