### ISSUE TITLE
Video Size, Video Thumb, Video Title

### ISSUE THREAD

**Issue by BarisBey** [rg3/youtube-dl#7869]
How can i get via php, the video size, video title, video thumb?

example: echo exec('youtube-dl videourl .......'); must echo video information (title or thumb or size) in PHP.
youtube-dl can do this? or i must use curl or api?

**Comment by BarisBey** [comment]
i found a solution for title and thumbnail. But i can not found the video size.

youtube-dl -4 http://www.dailymotion.com/video/x3i3e96_star-trek-beyond-trailer-2016-paramount-pictures_shortfilms --get-thumbnail --get-title

**Comment by jaimeMF** [comment]
You can get the json output with `--dump-json`, see [all the info it contains](https://github.com/rg3/youtube-dl/blob/62d231c00493c329a78a30b15a336f131fc392f9/youtube_dl/extractor/common.py#L51-L236).
