### ISSUE TITLE
youtube-dl

### ISSUE THREAD

**Issue by quinlanjohn** [rg3/youtube-dl#7881]
WARNING: [youtube:playlist] PLWdOqgJFQmEJEzw4iNiJFwuMLhULRZi_W: Playlist page is missing OpenGraph title, falling back ...
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
