### ISSUE TITLE
youtube-dl ignores --audio-format entirely

### ISSUE THREAD

**Issue by TheKorn2** [rg3/youtube-dl#7882]
youtube-dl ignores audio-format entirely when it's the only flag passed and instead downloads whatever it damn well feels like.

example:

~/.config/youtube-dl$ youtube-dl https://www.youtube.com/watch?v=-Hp4QhUX858 --audio-format aac,mp3,mp4a,wav  --ignore-config
[youtube] -Hp4QhUX858: Downloading webpage
[youtube] -Hp4QhUX858: Downloading video info webpage
[youtube] -Hp4QhUX858: Extracting video information
[youtube] -Hp4QhUX858: Downloading DASH manifest
[youtube] -Hp4QhUX858: Downloading DASH manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] The Muppets Are Pod People!--Hp4QhUX858.f137.mp4 has already been downloaded
[download] 100% of 76.00MiB
[download] Destination: The Muppets Are Pod People!--Hp4QhUX858.f251.webm
[download] 100% of 5.08MiB in 00:01
[ffmpeg] Merging formats into "The Muppets Are Pod People!--Hp4QhUX858.mkv"
Deleting original file The Muppets Are Pod People!--Hp4QhUX858.f137.mp4 (pass -k to keep)
Deleting original file The Muppets Are Pod People!--Hp4QhUX858.f251.webm (pass -k to keep)
vince@Mythtery:~/.config/youtube-dl$

There youtube-dl downloaded webm audio instead of pretty much any other format.  Doesn't matter if you hit audio-format with aac, mp4, wav, mp3 singly, it ALWAYS downloads the webm.  That wouldn't be so bad if it downloaded the webm and then converted it to whatever was asked for (not optimal but workable), but that doesn't happen, either.

**Comment by TheKorn2** [comment]
(my config file is empty, consisting of a single # line, in case it matters.)

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by dstftw** [comment]
`--audio-format` must be used with `--extract-audio`. It does not support comma separated list of formats.

**Comment by TheKorn2** [comment]
How can one force youtube-dl to avoid a certain audio codec, then?

**Comment by TheKorn2** [comment]
Bug is present even when a single, non-comma-separated format is present.

**Comment by dstftw** [comment]
Use [format selection](https://github.com/rg3/youtube-dl#format-selection).

**Comment by TheKorn2** [comment]
That's an ugly hack that doesn't work for putting in a global config file, you realize.  It would work a lot better if one could say "yeah, whatever *except* x,y,z" or "yeah, whatever of x, y, z".

**Comment by dstftw** [comment]
It covers this scenario and much more flexible in general.

**Comment by dstftw** [comment]
And yes, it works fine with config file like any other option.

**Comment by TheKorn2** [comment]
So it does.  Thanks!
