### ISSUE TITLE
-f bestvideo+acodec!=webm/best doesn't download actual best video

### ISSUE THREAD

**Issue by TheKorn2** [rg3/youtube-dl#7883]
youtube-dl downloads 1280x720 video even though 1920x1080 video is available when filter -f bestvideo+acodec!=webm/best is specified.

$ youtube-dl --ignore-config --list-formats https://www.youtube.com/watch?v=Zre9FhhxR7k
[youtube] Zre9FhhxR7k: Downloading webpage
[youtube] Zre9FhhxR7k: Downloading video info webpage
[youtube] Zre9FhhxR7k: Extracting video information
[youtube] Zre9FhhxR7k: Downloading DASH manifest
[youtube] Zre9FhhxR7k: Downloading DASH manifest
[info] Available formats for Zre9FhhxR7k:
format code  extension  resolution note
249          webm       audio only DASH audio   54k , opus @ 50k, 191.97KiB
250          webm       audio only DASH audio   73k , opus @ 70k, 262.78KiB
171          webm       audio only DASH audio  123k , vorbis@128k (44100Hz), 433.97KiB
140          m4a        audio only DASH audio  127k , m4a_dash container, aac  @128k (44100Hz), 469.78KiB
251          webm       audio only DASH audio  144k , opus @160k, 509.65KiB
160          mp4        256x144    DASH video  110k , avc1.42c00c, 15fps, video only, 402.74KiB
278          webm       256x144    DASH video  114k , webm container, vp9, 15fps, video only, 363.93KiB
133          mp4        426x240    DASH video  246k , avc1.4d4015, 30fps, video only, 901.06KiB
242          webm       426x240    DASH video  248k , vp9, 30fps, video only, 736.11KiB
243          webm       640x360    DASH video  451k , vp9, 30fps, video only, 1.32MiB
134          mp4        640x360    DASH video  568k , avc1.4d401e, 30fps, video only, 1.35MiB
244          webm       854x480    DASH video  821k , vp9, 30fps, video only, 2.30MiB
135          mp4        854x480    DASH video 1032k , avc1.4d401f, 30fps, video only, 2.51MiB
247          webm       1280x720   DASH video 1596k , vp9, 30fps, video only, 4.60MiB
136          mp4        1280x720   DASH video 1786k , avc1.4d401f, 30fps, video only, 4.52MiB
248          webm       1920x1080  DASH video 2651k , vp9, 30fps, video only, 7.44MiB
137          mp4        1920x1080  DASH video 3091k , avc1.640028, 30fps, video only, 8.05MiB
17           3gp        176x144    small ,  mp4a.40.2, mp4v.20.3
36           3gp        320x240    small ,  mp4a.40.2, mp4v.20.3
5            flv        400x240    small
43           webm       640x360    medium ,  vorbis, vp8.0
18           mp4        640x360    medium ,  mp4a.40.2, avc1.42001E
22           mp4        1280x720   hd720 ,  mp4a.40.2, avc1.64001F (best)

$ youtube-dl --ignore-config -f bestvideo+acodec!=webm/best --verbose https://www.youtube.com/wat
ch?v=Zre9FhhxR7k
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-config', u'-f', u'bestvideo+acodec!=webm/best', u'--verbose', u'https://www.youtube.com/watch?v=Zre9FhhxR7
k']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.10
[debug] Python version 2.7.3 - Linux-3.2.0-69-generic-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: ffmpeg git-2015-11-10-6e3244f, ffprobe git-2015-11-10-6e3244f, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Zre9FhhxR7k: Downloading webpage
[youtube] Zre9FhhxR7k: Downloading video info webpage
[youtube] Zre9FhhxR7k: Extracting video information
[youtube] Zre9FhhxR7k: Downloading DASH manifest
[youtube] Zre9FhhxR7k: Downloading DASH manifest
[debug] Invoking downloader on u'https://r3---sn-gjo-vgqe.googlevideo.com/videoplayback?mt=1450277746&mv=m&ms=au&ip=207.229.136.173&requiressl=ye
s&ipbits=0&mm=31&fexp=9407193%2C9407472%2C9416126%2C9418905%2C9420309%2C9420452%2C9420540%2C9422596%2C9423241%2C9423662%2C9425307%2C9425430%2C942
5619%2C9426059&mn=sn-gjo-vgqe&mime=video%2Fmp4&id=o-AHI_0L3YuzMB8Gy6NWovQecnULl7LrV-mQ9nkfN0jcLM&pl=19&sver=3&expire=1450299577&initcwndbps=23750
00&dur=30.232&source=youtube&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%
2Csource%2Cupn%2Cexpire&key=yt6&lmt=1449052723998098&itag=22&signature=600FA543249157B70325CA208EFD16365519EAC2.3FCB92893EF61FC2F4F0A118C2758C563
0D99D3B&upn=CNALLz0CAuc&ratebypass=yes'
[download] Destination: Carl's Jr and Hardee's _ Rick and Morty _ [sponsored content]-Zre9FhhxR7k.mp4
[download] 100% of 7.54MiB in 00:02

$ ffmpeg -i Carl's\ Jr\ and\ Hardee's\ _\ Rick\ and\ Morty\ _\ \[sponsored\ content\]-Zre9FhhxR7k
.mp4
ffmpeg version git-2015-11-10-6e3244f Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5)
  configuration: --enable-gpl --enable-libfaac --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librtmp --enabl
e-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-version3
  libavutil      55.  5.100 / 55.  5.100
  libavcodec     57. 15.100 / 57. 15.100
  libavformat    57. 14.100 / 57. 14.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 15.100 /  6. 15.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Carl's Jr and Hardee's _ Rick and Morty _ [sponsored content]-Zre9FhhxR7k.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2015-12-02 10:38:42
  Duration: 00:00:30.19, start: 0.000000, bitrate: 2096 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 1902 kb/s, 29.97 fps, 29.97 tbr, 3
0k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      creation_time   : 2015-12-02 10:38:43
      handler_name    : IsoMedia File Produced by Google, 5-11-2011
At least one output file must be specified

**Comment by dstftw** [comment]
You specified invalid format selection string, correct one: `-f bestvideo+bestaudio[acodec!=webm]/best`.

**Comment by TheKorn2** [comment]
Sure enough, thanks!
