### ISSUE TITLE
getting HLS stream with -f best option instead of single file URL 

### ISSUE THREAD

**Issue by gkreidl** [rg3/youtube-dl#7888]
I'm using youtube-dl in my omxplayerGUI application on the Raspberry Pi to extract the video URL (-g option) and to play it afterwards with omxplayer(GUI). HLS is not supported and so I have been using the "-f best" option to get the URL of a single stream (Audio+Video).
I updated today from github and now I'm getting HLS/m3u8 URLs from ard/mediathek instead of single stream URLs.
Is this a bug or are there better general options now to avoid HLS? I need a global format option that gets the best quality but always avoids HLS.

**Comment by fstirlitz** [comment]
`-f best[protocol!=m3u8][protocol!=m3u8_native]`?

**Comment by dstftw** [comment]
Yes, what @fstirlitz suggested should be enough to filter HLS.

**Comment by gkreidl** [comment]
No. this doesn't work. Here's an example:

youtube-dl -F "http://mediathek.daserste.de/Sportschau-live/Ski-Alpin-Abfahrt-der-Damen/Das-Erste/Video?documentId=25486050&topRessort&bcastId=723230"
[ARD:mediathek] 25486050: Downloading webpage
[ARD:mediathek] 25486050: Downloading media JSON
[ARD:mediathek] 25486050: Downloading m3u8 information
[info] Available formats for 25486050:
format code  extension      resolution note
a0-rtmp-1    unknown_video  unknown    
a0-rtmp-2    unknown_video  unknown    
a0-mp4-0     mp4            unknown    
a1-mp4-0     mp4            unknown    
a1-mp4-1     mp4            unknown    
a1-mp4-2-0   mp4            unknown    
a1-mp4-2-1   mp4            unknown    
a1-mp4-3     mp4            unknown    
hls-meta     mp4            multiple   Quality selection URL 
hls-61       mp4            unknown      61k , mp4a
hls-189      mp4            320x180     189k , avc1,  mp4a
hls-317      mp4            480x270     317k , avc1,  mp4a
hls-605      mp4            512x288     605k , avc1,  mp4a
hls-1148     mp4            640x360    1148k , avc1,  mp4a
hls-1988     mp4            960x540    1988k , avc1,  mp4a (best)

youtube-dl -f best[protocol!=m3u8][protocol!=m3u8_native] -g "http://mediathek.daserste.de/Sportschau-live/Ski-Alpin-Abfahrt-der-Damen/Das-Erste/Video?documentId=25486050&topRessort&bcastId=723230"
ERROR: requested format not available

**Comment by dstftw** [comment]
Correction -f best[protocol!=**?**m3u8][protocol!=**?**m3u8_native].
