### ISSUE TITLE
[pluralsight] Add support for new beta player

### ISSUE THREAD

**Issue by linuxeasy** [rg3/youtube-dl#7890]
# youtube-dl -u xxxxx -p xxxxxx https://app.pluralsight.com/library/courses/angularjs-fundamentals/table-of-contents --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://app.pluralsight.com/library/courses/angularjs-fundamentals/table-of-contents', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Darwin-15.2.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] angularjs-fundamentals: Downloading course JSON
[pluralsight:course] angularjs-fundamentals: Downloading course data JSON
[download] Downloading playlist: Angular Fundamentals
[pluralsight:course] playlist Angular Fundamentals: Collected 98 video ids (downloading 98 of them)
[download] Downloading video 1 of 98
[pluralsight] Downloading login page
[pluralsight] Logging in as xxxxx
[pluralsight] angularjs-fundamentals-m1-intro-0: Downloading webpage
[pluralsight] angularjs-fundamentals-m1-intro-0: Downloading mp4-high URL
[pluralsight] angularjs-fundamentals-m1-intro-0: Waiting for 3 seconds to avoid throttling
ERROR: An extractor error has occured. (caused by KeyError(u'clipName',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 235, in _real_extract
    'id': clip['clipName'],
KeyError: u'clipName'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 296, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'clipName',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Post the output of `-u xxxxx -p xxxxxx https://app.pluralsight.com/library/courses/angularjs-fundamentals/table-of-contents --verbose --dump-pages`.

**Comment by linuxeasy** [comment]
Sorry the limit for github comment exceeded, here is the link: http://pastebin.com/pLN8Hqei

**Comment by linuxeasy** [comment]
Here is the output http://pastebin.com/kQBKJU3p

**Comment by dstftw** [comment]
Similar to #7614.

**Comment by linuxeasy** [comment]
zxcvbnm,/asdffghjkl,;''

**Comment by daincredibleholg** [comment]
Same issue for me - let me know if you need a tester.

**Comment by zendyani** [comment]
Same here, this is a pull request to fix it #8215
