### ISSUE TITLE
youtube mp3 error

### ISSUE THREAD

**Issue by trevor23** [rg3/youtube-dl#7906]
when trying to download a youtube mp3 leaves me this erro:

WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

this and the command: 
----------------------------------------------------------------------------------------------------------------------------
 local command = 'youtube-dl --add-metadata -f "bestaudio/best" -o "/tmp/%(title)s.%(ext)s" --restrict-filenames -x --audio-format mp3 --audio-quality 192K '..yt_url
      local searchString = '%[ffmpeg] Destination: '
-------------------------------------------------------------------------------------------------------------------------------
What is wrong?

**Comment by phihag** [comment]
Your copy of avconv is outdated. Update avconv to version 10-0 or newer.

**Comment by trevor23** [comment]
@phihag how can I update it?

**Comment by phihag** [comment]
@trevor23 How did you install avconv? If you used a package manager of a distribution, contact the distribution's support. If you installed avconv from source, reinstall with the current version. If you used a binary avconv image, reinstall with the current version.

In any case, this sounds like out of scope for this issue tracker, which is about youtube-dl issues only.
