### ISSUE TITLE
ERROR: Did not get any data blocks

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#791]
This error occurs pretty frequently, usually with videos that have low views starting around 2013-04-16 12:00:00 GMT.  Here's a single example.  I'm using ec2 on us-west2.

UPDATE: The issue is no longer occurring.  Does anyone have any idea what the "ERROR: content too short" can mean?

$ youtube-dl -f 18 http://www.youtube.com/watch?v=lix0A-F6bz4
[youtube] Setting language
[youtube] lix0A-F6bz4: Downloading video webpage
[youtube] lix0A-F6bz4: Downloading video info webpage
[youtube] lix0A-F6bz4: Extracting video information
[download] Destination: lix0A-F6bz4.mp4
[download]  23.9% of 8.36M at  253.36k/s ETA 00:25
ERROR: content too short (expected 8763593 bytes and served 2097856)

$ youtube-dl -f 18 http://www.youtube.com/watch?v=lix0A-F6bz4
[youtube] Setting language
[youtube] lix0A-F6bz4: Downloading video webpage
[youtube] lix0A-F6bz4: Downloading video info webpage
[youtube] lix0A-F6bz4: Extracting video information
[download] Resuming download at byte 2097856

ERROR: Did not get any data blocks
$ youtube-dl -f 18 http://www.youtube.com/watch?v=lix0A-F6bz4
[youtube] Setting language
[youtube] lix0A-F6bz4: Downloading video webpage
[youtube] lix0A-F6bz4: Downloading video info webpage
[youtube] lix0A-F6bz4: Extracting video information
[download] Resuming download at byte 2097856

ERROR: Did not get any data blocks

Here's a list of some videos this is currently occurring for
http://www.youtube.com/watch?v=PdoXMXFdZxM
http://www.youtube.com/watch?v=ZZq1g35EV6g
http://www.youtube.com/watch?v=98x4IwjEaHM
http://www.youtube.com/watch?v=SjJCI01VtVM
https://www.youtube.com/watch?v=u6c_wz9qvYA

**Comment by ledlamp** [comment]
For anyone who has this issue on a particular video when downloading a list of videos, you want to use the `-i` option so youtube-dl will skip it instead of quitting.
