### ISSUE TITLE
bestvideo+bestaudio formats says "requested format not available"

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#7910]
Posting a couple of related issues that should be fixed.

Issue 1: When not specifying any format options, Flash Video is downloaded from this site, though MPEG-4 is available. MPEG-4 is clearly superior and should be default.

    youtube-dl https://tv.nrk.no/serie/historia-om-walt-disney/KOID24008615/sesong-1/episode-1

Issue 2: When trying to select best video/audio to get the best quality (MPEG-4 with highest bitrate), an error occurs. This seems like a bug that should be fixed.

    youtube-dl -f bestaudio+bestvideo https://tv.nrk.no/serie/historia-om-walt-disney/KOID24008615/sesong-1/episode-1
    ERROR: requested format not available

Formats on this site are named according to bitrate (eg. `hls-2389` for 2389k). Bitrate varies per video. Since `bestvideo` doesn't work, the best quality must be manually found with `-F` per video. Annoying.

**Comment by dstftw** [comment]
`bestvideo` and `bestaudio` are video-only and audio-only formats correspondingly. NRK serves no such formats therefore you get `requested format not available`.

**Comment by dstftw** [comment]
As for issue 1, preferring hls over hds is questionable and they both have same quality.

**Comment by forthrin** [comment]
I thought the `.flv` file was some sort of Flash video format, men I realise now that the `.flv` file contains `h264` video!. However, how do I get the file with a `.mp4` wrapper/extension rather than `.flv`?

**Comment by dstftw** [comment]
Use `--recode-video mp4`.

**Comment by forthrin** [comment]
The above does a full re-encoding of the video, which eats 100% CPU and takes forever. How can I do the equivalent of the following (which takes but a second) from the tool itself.

    ffmpeg -i video.flv -codec copy -video.mp4

**Comment by dstftw** [comment]
You can't.

**Comment by forthrin** [comment]
Flash being a dying and much-loathed technology, I propose `.mp4` to be a better default container and file extension. Can't see why anyone would prefer `.flv`.

**Comment by dstftw** [comment]
There is no such thing as a default container. youtube-dl downloads files as is. User decides what to do next.

**Comment by forthrin** [comment]
By specifying `mp4` from available formats, it downloads mp4 directly without `flv` as an intermediate format. However, it isn't possible without specifying the format manually like mentioned earlier:

    $ youtube-dl -F https://tv.nrk.no/serie/oeyeblikket/DMPV73050115/sesong-1/episode-1
    hls-2229     mp4        1280x720   2229k , avc1,  mp4a
    $ youtube-dl -f hls-2229 https://tv.nrk.no/serie/oeyeblikket/DMPV73050115/sesong-1/episode-1
    [download] Destination: Oppvasken-DMPV73050115.mp4

I still think there should be some intelligent way to get the `mp4` format. I can come up with some suggestions, but I guess the developers who know the product by heart would be better at this.

**Comment by dstftw** [comment]
There is [an intelligent way](https://github.com/rg3/youtube-dl#format-selection). `-f best[ext=mp4]`.

**Comment by forthrin** [comment]
Previous responses seemed to hint that this was impossible. Thanks for letting me know a shorthand way of getting the preferred format. PS! I still think `mp4` would be a considered as a better default than `flv`.

**Comment by dstftw** [comment]
You asked how to extract mp4 from flv - you've got responses about that. With format selection you simply download mp4 instead of flv. mp4 should not be default until native hls downloader is well enough to handle all kind of m3u8 streams.

**Comment by forthrin** [comment]
Sounds like it will be fixed in the future then. Evidently a bit of knowledge on formats and how the software is implemented is required to get the full picture of things :) Thanks!
