### ISSUE TITLE
--continue flag has no effect when downloading via ffmpeg

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#7911]
The `--continue` option has no effect `ffmpeg` is employed for downloading/transcoding, possibly because `ffmpeg` does not support resuming.

If downloading a long video is interrupted (lost network connection, etc.), you have to download the whole file again even though 99% of the file is already downloaded. Annoying, needless to say...

It should be considered to retrieve the video data in a way that honours the `--continue` flag. To reproduce, run the command, interrupt the download after a few seconds, and run it again.

    youtube-dl --continue -f hls-2389 https://tv.nrk.no/serie/historia-om-walt-disney/KOID24008615/sesong-1/episode-1

**Comment by dstftw** [comment]
You can use native hls downloader that supports continue with `--hls-prefer-native`.
