### ISSUE TITLE
Could not find JS function u'gr'

### ISSUE THREAD

**Issue by lele2010lele** [rg3/youtube-dl#7916]
apple-de15cunMacBook-Pro:~ apple$ youtube-dl --proxy http://127.0.0.1:8087 -tc https://www.youtube.com/watch?v=U58y6axpS-E
[youtube] U58y6axpS-E: Downloading webpage
[youtube] U58y6axpS-E: Downloading video info webpage
[youtube] U58y6axpS-E: Extracting video information
[youtube] U58y6axpS-E: Downloading js player en_US-vflrSqbyh
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phihag** [comment]
Be sure to call youtube-dl with the `--verbose` flag and include its complete output in the bug report. Otherwise, we cannot help you.

Most likely, you are not using the latest version; type `youtube-dl -U` to update.

**Comment by dstftw** [comment]
As already mentioned by @phihag you are almost definitely using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
