### ISSUE TITLE
arte.py needs to be fixed

### ISSUE THREAD

**Issue by wf4wfewr** [rg3/youtube-dl#7920]
Hi,
regarding https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/arte.py
it needs to be updated/fixed because they updated their site a few weeks ago and if one tries to download e.g. the first vid (today it's: http://www.arte.tv/guide/de/sendungen/XEN/xenius/?vid=048353-013_PLUS7-D), a different vid is downloaded.
Regards

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by coderkd10** [comment]
```
> youtube-dl -v http://www.arte.tv/guide/de/sendungen/XEN/xenius/?vid=048353-013_PLUS7-D
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.arte.tv/guide/de/sendungen/XEN/xenius/?vid=048353-013_PLUS7-D']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.09
[debug] Python version 2.7.6 - Linux-3.13.0-73-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 0.8.7-6, rtmpdump 2.4
[debug] Proxy map: {}
[arte.tv:+7] XEN: Downloading webpage
[arte.tv:+7] XEN: Downloading JSON metadata
[arte.tv:+7] XEN: Checking HTTP_MP4_MQ_1 video format URL
[arte.tv:+7] XEN: Checking HTTP_MP4_LQ_1 video format URL
[arte.tv:+7] XEN: Checking HLS_SQ_1 video format URL
[arte.tv:+7] XEN: Checking HTTP_MP4_SQ_1 video format URL
[arte.tv:+7] XEN: Checking HTTP_MP4_EQ_1 video format URL
[debug] Invoking downloader on u'http://arte.gl-systemhaus.de/am/tvguide/default/056817-002-A_EXT_SQ_1_VOA_02074797_MP4-2200_AMM-Tvguide_EXTRAIT.mp4'
[download] Destination: Xenius - Sind Erkältungen gut für uns-056817-002_EXTRAIT-D.mp4
[download] 100% of 24.16MiB in 00:03
```
Could not verify if the downloaded video was different, because the video on the website does not load at all!

**Comment by wf4wfewr** [comment]
coderkd10, you just verified the error I mean. 

"Could not verify if the downloaded video was different, because the video on the website does not load at all!"
It is different because if you'd try to download the second vid it'd still download the same vid. Also, the title is of course different.

Anyway I have the same error:
A fix is needed because the latest vid from today (21.) is a different as the one which is downloaded:
$ youtube-dl -v http://www.arte.tv/guide/de/sendungen/XEN/xenius/?vid=056817-002_PLUS7-D
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.arte.tv/guide/de/sendungen/XEN/xenius/?vid=056817-002_PLUS7-D']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.18
[debug] Python version 2.7.10 - Linux-4.2.0-22-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg N-76952-g6b978da, ffprobe N-76952-g6b978da
[debug] Proxy map: {}
[arte.tv:+7] XEN: Downloading webpage
[arte.tv:+7] XEN: Downloading JSON metadata
[arte.tv:+7] XEN: Checking HTTP_MP4_MQ_1 video format URL
[arte.tv:+7] XEN: Checking HTTP_MP4_LQ_1 video format URL
[arte.tv:+7] XEN: Checking HLS_SQ_1 video format URL
[arte.tv:+7] XEN: Checking HTTP_MP4_SQ_1 video format URL
[arte.tv:+7] XEN: Checking HTTP_MP4_EQ_1 video format URL
[debug] Invoking downloader on u'http://arte.gl-systemhaus.de/am/tvguide/default/057372-001-A_EXT_SQ_1_VOA_02076400_MP4-2200_AMM-Tvguide_EXTRAIT.mp4'
[download] Destination: Xenius - Haare - Was verraten sie über uns-057372-001_EXTRAIT-D.mp4
[download]   7.2% of 27.84MiB at  2.72MiB/s ETA 00:09^C
ERROR: Interrupted by user

Trying to download the next vid from yesterday downloads the same wrong vid.

**Comment by wf4wfewr** [comment]
Although Arte is of course controlled mass media.., from time to time they have relatively good docus.

**Comment by jaimeMF** [comment]
It will work in the next version, thanks for the report.
