### ISSUE TITLE
List from youtube site can't be downloaded

### ISSUE THREAD

**Issue by andyrozman** [rg3/youtube-dl#7923]
Hi !
I am trying to download whole list of youtube, but it doesn't work (anymore). When I start, I see that job was forked and after first it's stopped and is waiting...

youtube-dl --ignore-errors --playlist-start 1 --playlist-end 50 --yes-playlist --verbose  https://www.youtube.com/watch?v=ZN10WGBoJ2Y&list=PL58tmngiSlqq1U3laPLLCAac09g53D3gr
[1] 30815
andy@tardis:~/Videos/Simona_Weiss$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-errors', u'--playlist-start', u'1', u'--playlist-end', u'50', u'--yes-playlist', u'--verbose', u'https://www.youtube.com/watch?v=ZN10WGBoJ2Y']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.18
[debug] Python version 2.7.9 - Linux-3.19.0-41-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ZN10WGBoJ2Y: Downloading webpage
[youtube] ZN10WGBoJ2Y: Downloading video info webpage
[youtube] ZN10WGBoJ2Y: Extracting video information
[youtube] ZN10WGBoJ2Y: Downloading DASH manifest
[youtube] ZN10WGBoJ2Y: Downloading DASH manifest
[download] Simona Weiss - Ena želja-ZN10WGBoJ2Y.mp4 has already been downloaded and merged

And here it waits and waits.... In old times I could see more titles downloading... I added all additional parameters because it was said so by some other issues (I started without any on start)...

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
