### ISSUE TITLE
Feature Request: Download all videos that haven't been downloaded before

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#7924]
Take a look at [Apple Trailers Downloader] (https://github.com/aag/apple_trailer_downloader). It has the brilliant function of continuously downloading all new ("Latest") trailers from Apple, by keeping track of already downloaded trailers by checking a text file rather than local file existence. Thus trailers that are downloaded earlier and deleted are not downloaded again!

`youtube-dl` already supports Apple Trailers. Could a similar "download all videos that haven't been downloaded earlier" functionality be added for all sites that have video lists of some sort. I reckon a single text file would suffice for keeping track of all downloaded videos.

**Comment by dstftw** [comment]
Use `--download-archive`.

**Comment by forthrin** [comment]
You guys have thought of everything, haven't you? :) I really got to read the manual thoroughly some day! However, which URL do I give `youtube-dl` for downloading all (latest) Apple Trailers?

    youtube-dl --download-archive ~/.youtube-dl.txt http://trailers.apple.com/#section=justadded
    ERROR: Unsupported URL: http://trailers.apple.com/#section=justadded

**Comment by dstftw** [comment]
Trailers' playlists are unsupported currently.

**Comment by forthrin** [comment]
I'll ask the author of ATD if he would be willing to merge the functionality into `youtube-dl`. Both tools are Python which should make things easier.

**Comment by dstftw** [comment]
youtube-dl may not use BeautifulSoup.

**Comment by forthrin** [comment]
See comment https://github.com/aag/apple_trailer_downloader/issues/9#issuecomment-166712991 It would be nice if someone took the effort to support playlists at Apple Trailers.

**Comment by remitamine** [comment]
> support playlists at Apple Trailers.
will be supported in the next version.

**Comment by forthrin** [comment]
That's brilliant news! I really appreciate it and will use it a lot. I'm quite impressed with the prompt responses for this tool. Keep up the good work!
