### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by kevinp058** [rg3/youtube-dl#7933]
When using the bot, I am no longer able to pull youtube videos as it has been sending too many requests to youtube, so it's required to complete a captcha (which of course it can't do) so it fails to download the videos. Maybe implementing a spam filter or something may help stop this issue from occuring.

**Comment by dstftw** [comment]
Out of scope of youtube-dl.
As for captcha, you can [pass cookies](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl) from your browser after solving it.

**Comment by kevinp058** [comment]
How can I do this in conjunction with something such as SinusBot?

**Comment by dstftw** [comment]
Ask SinusBot support.
