### ISSUE TITLE
youtube dl download with specific resolution programmatically

### ISSUE THREAD

**Issue by moiseyo** [rg3/youtube-dl#7937]
I'm trying to set best restitution  to download from python code   
   ydl = youtube_dl.YoutubeDL({'outtmpl': '%s/%%(title)s.%%(ext)s -f bestvideo+bestaudio '%(out_dir),'f':' bestvideo+bestaudio'})

i know that  bestvideo+bestaudio   can be  using command
youtube-dl  -F

I'd like to make  complete code  from python 

Best Regards

**Comment by jaimeMF** [comment]
Use the `'format'` key:
```python
import youtube_dl

out_dir = '.'
ydl = youtube_dl.YoutubeDL({'outtmpl': '%s/%%(title)s.%%(ext)s' % out_dir, 'format':' bestvideo+bestaudio'})
ydl.extract_info('test:youtube')
```

The list of all the options is in [YoutubeDL.py](https://github.com/rg3/youtube-dl/blob/9b9c5355e4c0fe6f9028aaa3b1b8beb28a085433/youtube_dl/YoutubeDL.py#L125-L254).
