### ISSUE TITLE
Windows - Batch variables %% problem

### ISSUE THREAD

**Issue by Kdmeizk** [rg3/youtube-dl#7950]
@"%HOMEPATH%\Downloads\youtube-dl\youtube-dl.exe" --ignore-config --no-playlist --buffer-size 500000000 --no-cache-dir -o %%HOMEPATH%%\Desktop\%(title)s.%(ext)s --console-title -v --print-traffic --no-call-home --youtube-skip-dash-manifest --add-metadata %urlVideo%

Is possible the command prompt can read %HOMEPATH% for -o setting ? The first works, but not for -o. Even with %%%, but I think we are going into an infinite loop

**Comment by dstftw** [comment]
`-o "%HOMEPATH%\Desktop\%(title)s.%(ext)s"` works fine.

**Comment by Kdmeizk** [comment]
I don't know why your output works.

1) It's necessary to put the drive letter for the output before %HOMEPATH%, is possible to youtube-dl to know itself the drive letter used ? %HOMEPATH% = \Users\Username. Windows understands it and puts the drive letter automatically, youtube-dl doesn't it.
2) The file below shows you my result : the filename is (ext)s.

[output.txt](https://github.com/rg3/youtube-dl/files/71097/output.txt)

**Comment by dstftw** [comment]
1. `%HOMEDRIVE%`
2. `%`'s supposed to be plain characters must be escaped in batch file `-o "%HOMEPATH%\Desktop\%%(title)s.%%(ext)s"`.

**Comment by Kdmeizk** [comment]
Ok, my searches were bad, I didn't add one more % to youtube-dl's variables.
Thank you so much, it works !
