### ISSUE TITLE
Error: Could not find JS function 'gr'

### ISSUE THREAD

**Issue by miachm** [rg3/youtube-dl#7959]
When i execute: youtube-dl https://www.youtube.com/watch?v=t7k3B9U9T9c

I have a error:
youtube_dl.utils.ExtractorError: Could not find JS function 'gr'

Full error message with verbose here:
[error.txt](https://github.com/rg3/youtube-dl/files/71036/error.txt)

Only fails with this link

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
