### ISSUE TITLE
Unable to download the Playlist.

### ISSUE THREAD

**Issue by ayushman2013** [rg3/youtube-dl#7970]
youtube-dl https://www.youtube.com/playlist?list=PLjP-FzwmAXChcbQ1t0weZpcNcdoXaxfZD

[youtube:playlist] PLjP-FzwmAXChcbQ1t0weZpcNcdoXaxfZD: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by ayushman2013** [comment]
Thank you. I am using Ubuntu 15.10 and below code worked well for me.
sudo pip install -U youtube-dl

Thank you for your help.
