### ISSUE TITLE
[rai] Support content sets

### ISSUE THREAD

**Issue by video-dl** [rg3/youtube-dl#7987]
An error occurred while downloading the following video: http://www.rainews.it/dl/rainews/TGR/basic/PublishingBlock-8cbbd8fc-3365-4785-a7ec-950b73541553-archivio.html#
This is the output of youtube-dl --verbose

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-J', u'http://www.rainews.it/dl/rainews/TGR/basic/PublishingBlock-8cbbd8fc-3365-4785-a7ec-950b73541553-archivio.html#']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.12.21
[debug] Python version 2.7.6 - Linux-3.19.0-39-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
ERROR: Unable to extract iframe; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 109, in _real_extract
    webpage, 'iframe')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 586, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by davidjameshowell** [comment]
Plugging the ID in to the JSON returns a 404 versus valid data for the test within the extractor.
```
http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-8cbbd8fc-3365-4785-a7ec-950b73541553.html?json
```
