### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by animer3009** [rg3/youtube-dl#7988]
ERROR: Signature extraction failed: Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature video_id, player_url, s File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function res = self._parse_sig_js(code) File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js initial_function = jsi.extract_function(funcname) File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function raise ExtractorError('Could not find JS function %r' % funcname) ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ismh** [comment]
Seeing the same error on multiple YouTube URLs.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
