### ISSUE TITLE
Live stream in youtube

### ISSUE THREAD

**Issue by Kasher** [rg3/youtube-dl#7993]
Hi,

I've ran into this page today, which contains Sky News's live stream:
https://www.youtube.com/watch?v=y60wDzZt8yg

I've tried to download the video using youtube-dl, but I get a 404 error (Not Found).
I wonder if that's a bug, or is it the desired behaviour in such cases (of live-streams)?

Basically, what I would want is to get a direct link to the stream, one which I can use as an input to a media player to watch the video.

Thanks in advance!

**Comment by AGSPhoenix** [comment]
Works for me. Could you try the download again with the verbose flag (`youtube-dl.exe y60wDzZt8yg -v`), and post the output of it here?

**Comment by Kasher** [comment]
I've updated my youtube-dl version and now it works.
Sorry, Thanks!!
