### ISSUE TITLE
About making youtube-dl extremelly portable and lightweight: Possible with Python?

### ISSUE THREAD

**Issue by timofonic** [rg3/youtube-dl#8003]
Hello.

There's interesting projects about video players I'm following:

https://github.com/theScrabi/NewPipe
https://github.com/dodola/YoutubeDown
https://github.com/flaviotordini/minitube
https://github.com/bromix/plugin.video.youtube
https://github.com/zjc0516/crawl_youtube
https://github.com/gdkchan/Yuna
https://github.com/jxm262/slacktube
https://github.com/GabeMeister/YoutubeCollectionsConsoleApp
https://github.com/jolaf/vimeo-crawler
https://github.com/quackware/mobilevideodownloader 
https://github.com/grass0916/VoiceTube-subtitle-downloader
https://github.com/suphero/PDownloader 
https://github.com/while-loop/Android-Xposed-Vine-Downloader
https://github.com/sagarjoglekar/vineCrawl
https://github.com/Sheldan/yt_crawler
https://github.com/yytsui/VideoCrawler
https://github.com/bhattjigar/youtube-downloading-api
https://github.com/cynd7us/youtube-scrapper
https://github.com/shoekla/ScrapeC
https://github.com/fallingleaf/utube 
https://github.com/tyrone2015/crawler_video
https://github.com/digineo/media_crawler

I see don't think so and it's an issue, lots of repeated efforts are done, instead collaborating in a stronger project and reuse code.

What's missing in youtube-dl? I see there's lack of scrapping features, so you can't do an app able to replace the youtube web GUI or any other of other video provider.

I see embedding the code to other platforms can be a problem, specially Java and PHP.

If youtube-dl wants to stay with Python, there are many approachs to make youtube-dl a more widely used and universal framework for supporting video providers:

If continue using Python:

For using it in Android and Java:
https://github.com/kivy/python-for-android
http://www.jython.org

Usage on webpages (useful for OwnCloud client, for example):
http://pyjs.org
http://www.brython.info

For using it in .NET/C#
http://pythonnet.github.io
http://ironpython.net

Going to native!

https://github.com/kayhayen/Nuitka
https://github.com/numba/numba

Crazy idea: Switch to Lua

Why?

Lua is very lightweight.
Lua is a 200KB interpreter vs 2MB of Python. 
More comparct memory, Thread-safe
 Small & compact standard library.

... It's faster and very portable.

It would requite ~~back to the roots~~, maybe usinghttp://repo.or.cz/w/libquvi.git http://repo.or.cz/libquvi-scripts.git  libquvi + libquvi-script as a starting point.
(Lua for Python Programmers)[http://the4thwiki.com/lua/]

https://github.com/damonkohler/sl4a
https://github.com/mkottman/AndroLua
https://github.com/laruence/php-lua

http://programmers.stackexchange.com/questions/66590/why-python-and-not-lua 
http://lua-users.org/wiki/LuaVersusPython

Kind regards.

**Comment by dstftw** [comment]
If you have any concrete requests open a new issue per request. Note that any code to be merged in youtube-dl must be licensed under Unlicense.

**Comment by timofonic** [comment]
Sorry...

I don't have a "sane" request. I did read the proposal and is awfully written, I'm sorry.

The idea is making youtube-dl usable on all kind of platforms and add features of not only playing videos, but also act as complete wrappers of those sites. This code would be reused by lots of more projects, and having more potential collaborators.

Righ now, most projects write their own scrappers to look at the sites. It would be nice if there would be a common code that could be used on all kind of platforms. Maybe Python could be adapted, I see there's lots of projects managing to convert or use Python on different platforms (you could even convert Python to Javascript).

**Comment by Hrxn** [comment]
Yes.
This is called 'Reinventing the Wheel'.

But that's how it is, I didn't check your link collection up there, but different projects have different goals and different priorities.

You are theoretically right, in some way, but this is not going to happen soon, realistically.
