### ISSUE TITLE
Playlist information isn't added to filename when downloading individual videos.

### ISSUE THREAD

**Issue by Ryonez** [rg3/youtube-dl#8005]
I'm trying to include Playlist information into the filename if the video is part of a playlist. However, the file output options %(playlist)s and %(playlist_index)s do not work unless you use the playlist link itself, i.e.

https://www.youtube.com/watch?v=4SfjkpmE5-I  OR https://www.youtube.com/watch?v=4SfjkpmE5-I&list=PL3tRBEVW0hiD2DcetgW0Nu-OMp7EEbUvq&index=7 DOES NOT WORK.

https://www.youtube.com/playlist?list=PL3tRBEVW0hiD2DcetgW0Nu-OMp7EEbUvq DOES WORK

This would cause issues for me when I want to watch a playlist, as I normally download videos as they come out, one at a time.

The cmd output from https://www.youtube.com/watch?v=4SfjkpmE5-I which I stop after I can see the filename is missing the Playlist information:

C:\TMP PORT APPS\youtube-dl>youtube-dl.exe https://www.youtube.com/watch?v=4SfjkpmE5-I
[debug] System config: []
[debug] User config: [u'--verbose', u'--format', u'bestvideo[height<=?1080]+m4a/mp4/bestaudio', u'--embed-thumbnail', u'--write-description', u'--sub-lang', u'en', u'--write-sub', u'--no-overwrites', u'--output', u'/DOWNLOADING/%(extractor)s/%(uploader)s_TITLE-%(title)s_PLAYLIST-%(playlist)s_%(playlist_index)s_INFO-%(format)s_%(upload_date)s_%(id)s.%(ext)s']
[debug] Command-line args: [u'https://www.youtube.com/watch?v=4SfjkpmE5-I']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.23
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-71883-geb9fb50
[debug] Proxy map: {}
[youtube] 4SfjkpmE5-I: Downloading webpage
[youtube] 4SfjkpmE5-I: Downloading video info webpage
[youtube] 4SfjkpmE5-I: Extracting video information
WARNING: video doesn't have subtitles
[youtube] 4SfjkpmE5-I: Downloading DASH manifest
[youtube] 4SfjkpmE5-I: Downloading DASH manifest
[info] Writing video description to: DOWNLOADING\youtube\Markiplier_TITLE-JUST DO IT _ Will You Press The Button #4_PLAYLIST-NA_NA_INFO-299 - 1920x1080 (DASH video)+140 - audio only (DASH audio)_20151224_4SfjkpmE5-I.description
[youtube] 4SfjkpmE5-I: Downloading thumbnail ...
[youtube] 4SfjkpmE5-I: Writing thumbnail to: DOWNLOADING\youtube\Markiplier_TITLE-JUST DO IT _ Will You Press The Button #4_PLAYLIST-NA_NA_INFO-299 - 1920x1080 (DASH video)+140 - audio only (DASH audio)_20151224_4SfjkpmE5-I.jpg
[debug] Invoking downloader on u'https://r1---sn-no52-jijl.googlevideo.com/videoplayback?id=e127e3929984e7e2&itag=299&source=youtube&requiressl=yes&pcm2cms=yes&pl=19&mm=31&mn=sn-no52-jijl&ms=au&mv=m&ratebypass=yes&mime=video/mp4&gir=yes&clen=183595152&lmt=1450985732239236&dur=728.527&sver=3&signature=23C80B3918B749107C072F34CBEA808F90D9079F.36748C30056FB2E400CEDCF99B698032A8757D98&fexp=9410705,9413208,9415791,9416126,9418222,9418959,9420452,9422596,9423390,9423491,9423662,9424135,9424183,9424428,9426035&upn=CyRHYwXdoQk&mt=1451035875&key=dg_yt0&ip=123.255.47.249&ipbits=0&expire=1451057603&sparams=ip,ipbits,expire,id,itag,source,requiressl,pcm2cms,pl,mm,mn,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: DOWNLOADING\youtube\Markiplier_TITLE-JUST DO IT _ Will You Press The Button #4_PLAYLIST-NA_NA_INFO-299 - 1920x1080 (DASH video)_20151224_4SfjkpmE5-I.f299.mp4
[download]   2.5% of 175.09MiB at 573.22KiB/s ETA 05:05
ERROR: Interrupted by user

**Comment by dstftw** [comment]
With https://www.youtube.com/watch?v=4SfjkpmE5-I it impossible to know which playlist the video belongs to.
https://www.youtube.com/watch?v=4SfjkpmE5-I&list=PL3tRBEVW0hiD2DcetgW0Nu-OMp7EEbUvq&index=7  works fine if you pass the URL [correctly](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).

**Comment by Ryonez** [comment]
What? Should this be be in a "Cannot download a playlist" section in the fax?
I'm not getting any of those errors whatsoever. And I did paste the URL correctly, the way you said that kinda hurt a little >.>

Anyway, I wasn't expecting a reply so quickly! Go and enjoy Christmas mate.
