### ISSUE TITLE
Program does not update on Windows unless you are in the same directory as the executable

### ISSUE THREAD

**Issue by ismail** [rg3/youtube-dl#8006]
Demo:

C:\Users\ismail>youtube-dl.exe --update
Updating to version 2015.12.23 ...
ERROR: no write permissions on youtube-dl.exe

C:\Users\ismail>cd C:\bin\
C:\bin>dir youtube-dl.exe
 Volume in drive C is Meh
 Volume Serial Number is 38EF-2D07

 Directory of C:\bin

18-Dec-15  04:57 PM         6,192,768 youtube-dl.exe
               1 File(s)      6,192,768 bytes
               0 Dir(s)  189,261,316,096 bytes free

C:\bin>youtube-dl.exe --update
Updating to version 2015.12.23 ...

Waiting for file handle to be closed ...
C:\bin>Updated youtube-dl to version 2015.12.23.

So its not a permission problem.

**Comment by dstftw** [comment]
Dupicate of #2718.
