### ISSUE TITLE
latest youtube-dl :: can't find '__main__' module in './youtube-dl'

### ISSUE THREAD

**Issue by adriansev** [rg3/youtube-dl#8010]
Hi! With the latest youtube-dl (downloaded now) i have this error :
/usr/bin/python: can't find '__main__' module in './youtube-dl'

OS is Fedora 21 ; Python 2.7.8
Thank you for your work!

**Comment by yan12125** [comment]
How did you run youtube-dl? Could you please post the command and the output?

**Comment by adriansev** [comment]
sorry for the noise, it would seem that it was a corrupt download .. re-downloaded and it works : 
[Saturday 26.12.15 15:31] adrian@hal : ~  $
youtube-dl --version
2015.12.23
