### ISSUE TITLE
Support iQiyi playlists

### ISSUE THREAD

**Issue by N1CEyk** [rg3/youtube-dl#8019]
It is http://www.iqiyi.com/v_19rro6vzb8.html#vfrm=2-3-0-1&curid=390416300_75e8b856af43dff6dae99111e6a3b9ab not to be downloaded with yt-dl,which is Chinese url.I hope this bug can be solved.

**Comment by yan12125** [comment]
Works for me:
```
$ youtube-dl -v "http://www.iqiyi.com/v_19rro6vzb8.html#vfrm=2-3-0-1&curid=390416300_75e8b856af43dff6dae99111e6a3b9ab"   
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.iqiyi.com/v_19rro6vzb8.html#vfrm=2-3-0-1&curid=390416300_75e8b856af43dff6dae99111e6a3b9ab']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.23
[debug] Git HEAD: 607d65f
[debug] Python version 3.5.1 - Linux-4.3.3-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4, rtmpdump 2.4
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] 37bb7623391792cda62defefff2f2569: Downloading JSON metadata
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 1 for format h6
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 1 for format h6
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 2 for format h6
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 2 for format h6
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 3 for format h6
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 3 for format h6
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 4 for format h6
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 4 for format h6
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 1 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 1 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 2 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 2 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 3 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 3 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 4 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 4 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 5 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 5 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 6 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 6 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 7 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 7 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 8 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 8 for format h3
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 1 for format h5
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 1 for format h5
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 2 for format h5
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 2 for format h5
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 3 for format h5
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 3 for format h5
[iqiyi] 37bb7623391792cda62defefff2f2569: Download path key of segment 4 for format h5
[iqiyi] 37bb7623391792cda62defefff2f2569: Download video info of segment 4 for format h5
[download] Downloading playlist: 灌篮高手 第53集 大猩猩负伤！千钧一发？！
[iqiyi] playlist 灌篮高手 第53集 大猩猩负伤！千钧一发？！: Collected 8 video ids (downloading 8 of them)
[download] Downloading video 1 of 8
[debug] Invoking downloader on 'http://netcncoversea.inter.iqiyi.com/videos/v0/20150819/06/83/7c8b01fa322eb73d9fd05e741279f6e8.f4v?key=0dd592897a2177944c91a0cfc9fd6587a&src=iqiyi.com&tn=1451201328&qyid=effcabacbd044d28ba1943d84c44e94a&su=6ef94ea659d2493eae58c4895a839e74&ct=&client=&bt=&z=&uuid=8c70e6d8-567f935c-8a'
[download] Destination: 灌篮高手 第53集 大猩猩负伤！千钧一发？！-37bb7623391792cda62defefff2f2569_part1.f4v
[download]   0.7% of 37.71MiB at 22.32KiB/s ETA 28:38
```
Please post the full verbose log from the command
```
$ youtube-dl -v "http://www.iqiyi.com/v_19rro6vzb8.html#vfrm=2-3-0-1&curid=390416300_75e8b856af43dff6dae99111e6a3b9ab"   
```

**Comment by N1CEyk** [comment]
Thank you for solving this bug.I still have a question that the playlist on
the YouTuBe I can download  ,but the playlist like this,I don't know how to
do it

2015-12-27 15:32 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
The original URL works fine. Did you mean another URL? If so, please paste it here.

**Comment by N1CEyk** [comment]
like this ，http://www.iqiyi.com/a_19rrhb8ce1.html. And at the same time ,I
still find a bug url——
http://www.letv.com/ptv/vplay/22887359.html?ref=ym0401.I hope you can solve
them.

2015-12-27 21:01 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
http://www.iqiyi.com/a_19rrhb8ce1.html is a playlist, and iQiyi playlists are not supported yet.

For http://www.letv.com/ptv/vplay/22887359.html?ref=ym0401.I, it works for me. Note that you need ffmpeg (avconv fails as of now) for downloading Letv videos. If problem is still with ffmpeg, open a new issue.

**Comment by N1CEyk** [comment]
Thanks all the same

2015-12-28 0:42 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by N1CEyk** [comment]
I have a new bug site,it is not work to use youtube-dl -v .........  The
site is
http://www.iqiyi.com/v_19rrny4w8w.html?fc=87451bff3f7d2f4a#vfrm=2-3-0-1.Can
u solve it？

2015-12-28 10:03 GMT+08:00 Yk Yang <n1ce0571@gmail.com>:

**Comment by yan12125** [comment]
> 很抱歉，由於版權原因暫無法播放

(Sorry, unable to play it due to licensing issues)

This message is shown when I tried to play this video in my browser. Could you watch this video in browsers? If so, please open a new issue.

**Comment by N1CEyk** [comment]
The VIP account number can watch it.I give you it.Please have a try to
watch it with VIP account number. account number:   ads440@163.com
Password:    aa111222

2016-02-15 0:06 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
Public available 6-min preview of iQiyi VIP-only videos can be downloaded in the next version. Logging in is not implemented yet. You can use ```--cookies``` to pass cookies to youtube-dl.

For anyone who is interested in logging: https://github.com/yan12125/youtube-dl/tree/iqiyi-login-not-working-yet. I managed to mimic what browsers do, but always receive an HTTP 556 error. I don't know why.

**Comment by N1CEyk** [comment]
I don't know how to use this parameter,-- cookies.Maybe you need a proxy to
surf chinese site.

2016-02-16 1:34 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
There is some information at https://github.com/rg3/youtube-dl/issues/4539#issuecomment-118112193. There are also lots of browser extensions generating cookie.txt from browser cookies.

**Comment by N1CEyk** [comment]
I use "youtube --cookies 1.txt
http://www.iqiyi.com/v_19rrny4w8w.html?fc=87451bff3f7d2f4a#vfrm=2-3-0-1",but
the result is ERROR:fixed output name but moer than one file to
download.The 1.txt is "# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by EditThisCookie
# URL:
http://www.iqiyi.com/v_19rrny4w8w.html?fc=87451bff3f7d2f4a#vfrm=2-3-0-1
.iqiyi.com FALSE / FALSE 1455896841 c11210305716 1455893241675
.iqiyi.com FALSE / FALSE 1455979641 c241210305716 1455893241676
.iqiyi.com FALSE / FALSE Hm_lpvt_53b7374a63c37483e5dd97d78d9bb36e 1455893240
.iqiyi.com FALSE / FALSE 1487429239 Hm_lvt_53b7374a63c37483e5dd97d78d9bb36e
1455586863,1455623340,1455629916,1455893240
.iqiyi.com FALSE / FALSE 1463409527.397249 P00001
b4JPQZkZYIwlYxpvgEhm1m1q2OHNnrMZNyLKDjBvXllOVKm3m2DfozuoMVWwSql1UEPO9k86
.iqiyi.com FALSE / FALSE 1463409527.397793 P00002
%7B%22uid%22%3A%221210305716%22%2C%22user_name%22%3A%22ads440%40163.com
%22%2C%22email%22%3A%22ads440%40163.com
%22%2C%22nickname%22%3A%22ads440%22%2C%22pru%22%3A1210305716%2C%22type%22%3A10%2C%22pnickname%22%3A%22ads440%22%7D
.iqiyi.com FALSE / FALSE 1463409527.39736 P00003 1210305716
.iqiyi.com FALSE / FALSE 1463409527.397576 P00007
b4JPQZkZYIwlYxpvgEhm1m1q2OHNnrMZNyLKDjBvXllOVKm3m2DfozuoMVWwSql1UEPO9k86
.iqiyi.com FALSE / FALSE 1463409527.397432 P00010 1210305716
.iqiyi.com FALSE / FALSE 1463409527.397874 P000email ads440%40163.com
.iqiyi.com FALSE / FALSE 1463409527.397648 P00PRU 1210305716
.iqiyi.com FALSE / FALSE 1463409527.397502 P01010 1455638400
.iqiyi.com FALSE / FALSE 1487429239 QC006 1e0v81fgwlw65etf48j6tuwj
.iqiyi.com FALSE / FALSE QC007 DIRECT
.iqiyi.com FALSE / FALSE 1487429239 QC008 1455633456.1455893239.1455893239.4
.iqiyi.com FALSE / FALSE QC009 87451bff3f7d2f4a
.iqiyi.com FALSE / FALSE QC010 70394512
.iqiyi.com FALSE / FALSE 1487429241 QC025 1210305716-20160219
.iqiyi.com FALSE / FALSE 1487169527 QC116 ads440%40163.com
.iqiyi.com FALSE / FALSE 1487429248 QC118
%7B%22isFilterImage%22%3A0%2C%22hadTip%22%3A1%2C%22isOpen%22%3A0%7D
.iqiyi.com FALSE / FALSE 1487429242 QC134
%7B%221210305716%22%3A%5B1455893241660%5D%7D
.iqiyi.com FALSE / FALSE 1455895041.976907 QILINPUSH 1
.iqiyi.com FALSE / FALSE 1487169532.416205 QIYUECK
qy_pc_5eec39e72d214b2da4b3e298d0623f99
.iqiyi.com FALSE / FALSE 1455979685.251647 QY00001 1210305716
www.iqiyi.com TRUE / FALSE 1455979641 QC115 1"

2016-02-16 14:47 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
Python said 1.txt is not a valid cookie file. I guess formatting is changed in copying/pasting. Could you upload 1.txt directly? And please post further information at #8569. This issue is for iQiyi playlists but not iQiyi VIP videos.

**Comment by yan12125** [comment]
iQiyi playlists will be supported in the next version. Feel free to open new issues if there are more problems.

**Comment by N1CEyk** [comment]
I don't know where to upload.I use the google chrome's plugin,edit this cookie,to export 1.txt.

**Comment by yan12125** [comment]
Github allow uploading files to issues. [Here](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) are the steps. Please open a new issue and don't leave comments in a closed issue for different problems.

**Comment by N1CEyk** [comment]
Okay

2016-02-22 17:35 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:
