### ISSUE TITLE
Can not download playlist video from youku.com

### ISSUE THREAD

**Issue by c0ffee-cat** [rg3/youtube-dl#8020]
I'm using the latest youtube-dl. I found it can not download the playlist video from http://www.youku.com

$ youtube-dl --playlist-start 597 --playlist-end 650 http://www.youku.com/show_page/id_za7c275ecd7b411e1a19e.html

[generic] id_za7c275ecd7b411e1a19e: Requesting header
WARNING: Falling back on generic information extractor.
[generic] id_za7c275ecd7b411e1a19e: Downloading webpage
[generic] id_za7c275ecd7b411e1a19e: Extracting information
ERROR: Unsupported URL: http://www.youku.com/show_page/id_za7c275ecd7b411e1a19e.html

Really appreciate all your efforts and support.

Regards!

**Comment by kashuorg** [comment]
Additional information: 

$ youtube-dl --version
2015.12.23

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

**Comment by yan12125** [comment]
Youku shows will be fully supported in the next version.
