### ISSUE TITLE
Embed option not download DASH file

### ISSUE THREAD

**Issue by goelakash** [rg3/youtube-dl#8025]
How can I programmatically embed the option to not download the DASH manifest for every download.

I tried passing these params  (using Flask with python):

1. opts={   
    'youtube-skip-dash-manifest',
...}

2. opts={   
    'youtube-skip-dash-manifest':True,
...}

3. opts={   
    'youtube-skip-dash-manifest':"True",
...}

It downloads the DASH manifest regardless.

**Comment by dstftw** [comment]
```
ydl_opts = {
    'youtube_include_dash_manifest': False,
}
```
