### ISSUE TITLE
first time not able to DL a channel from youtube

### ISSUE THREAD

**Issue by GaelicGrime** [rg3/youtube-dl#8027]
this is the --verbose output

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-r', u'250k', u'-n', u'-o', u'YT_%(uploader)s/%(title)s.%(autonumber)s.%(id)s.%(ext)s', u'--verbose', u'-w', u'-i', u'--restrict-filenames', u'--max-downloads', u'20', u'ytuser:UCv0yBdt5opKGwv34MMV6ujQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.23
[debug] Python version 2.7.11 - Linux-4.2.0-1-686-pae-i686-with-debian-stretch-sid
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:user] UCv0yBdt5opKGwv34MMV6ujQ: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] UCv0yBdt5opKGwv34MMV6ujQ: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 330, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by AGSPhoenix** [comment]
It looks like the `ytuser:` syntax only works for YouTube users, not channels. To download the videos from a channel, use the full URL, like so:

`youtube-dl -r 250k -n -o 'YT_%(uploader)s/%(title)s.%(autonumber)s.%(id)s.%(ext)s' --verbose -w
 -i --restrict-filenames --max-downloads 20 https://www.youtube.com/channel/UCv0yBdt5opKGwv34MMV6ujQ`

**Comment by jaimeMF** [comment]
@AGSPhoenix is correct, you have to use the full URL.

**Comment by GaelicGrime** [comment]
same response to all forms I can think of

U_U will on _bigwill32_ [20151230.1959] /tz/z01/bu U_ youtube-dl -r 250k -n -o "YT_%(uploader)s/%(title)s.%(autonumber)s.%(id)s.%(ext)s" -w -i --restrict-filenames "ytuser:https://www.youtube.com/channel/UCv0yBdt5opKGwv34MMV6ujQ"
[youtube:user] https: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] https: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
U_U will on _bigwill32_ [20151230.1959] /tz/z01/bu U_ youtube-dl -r 250k -n -o "YT_%(uploader)s/%(title)s.%(autonumber)s.%(id)s.%(ext)s" -w -i --restrict-filenames "ytuser:https://www.youtube.com/channel/UCv0yBdt5opKGwv34MMV6ujQ/"
[youtube:user] https: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] https: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
U_U will on _bigwill32_ [20151230.1959] /tz/z01/bu U_ youtube-dl -r 250k -n -o "YT_%(uploader)s/%(title)s.%(autonumber)s.%(id)s.%(ext)s" -w -i --restrict-filenames "ytuser:https://www.youtube.com/channel/UCv0yBdt5opKGwv34MMV6ujQ/videos"
[youtube:user] https: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] https: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
U_U will on _bigwill32_ [20151230.2000] /tz/z01/bu U_ youtube-dl -r 250k -n -o "YT_%(uploader)s/%(title)s.%(autonumber)s.%(id)s.%(ext)s" -w -i --restrict-filenames "ytuser:https://www.youtube.com/channel/UCv0yBdt5opKGwv34MMV6ujQ/feed"
[youtube:user] https: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] https: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
U_U will on _bigwill32_ [20151230.2000] /tz/z01/bu U_ youtube-dl -r 250k -n -o "YT_%(uploader)s/%(title)s.%(autonumber)s.%(id)s.%(ext)s" -w -i --verbose --restrict-filenames "ytuser:https://www.youtube.com/channel/UCv0yBdt5opKGwv34MMV6ujQ/feed"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-r', u'250k', u'-n', u'-o', u'YT_%(uploader)s/%(title)s.%(autonumber)s.%(id)s.%(ext)s', u'-w', u'-i', u'--verbose', u'--restrict-filenames', u'ytuser:https://www.youtube.com/channel/UCv0yBdt5opKGwv34MMV6ujQ/feed']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.23
[debug] Python version 2.7.11 - Linux-4.3.0-1-686-pae-i686-with-debian-stretch-sid
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:user] https: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] https: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 330, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

U_U will on _bigwill32_ [20151230.2001] /tz/z01/bu U_

**Comment by dstftw** [comment]
>"ytuser:https://www.youtube.com/channel/UCv0yBdt5opKGwv34MMV6ujQ"

is not a
>full URL

**Comment by GaelicGrime** [comment]
and again after making sure to update to yesterday's version

sudo youtube-dl -U
[sudo] password for will:
Updating to version 2015.12.29 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
U_U will on _bigwill32_ [20151230.2003] /tz/z01/bu U_ youtube-dl -r 250k -n -o "YT_%(uploader)s/%(title)s.%(autonumber)s.%(id)s.%(ext)s" -w -i --verbose --restrict-filenames "ytuser:https://www.youtube.com/channel/UCv0yBdt5opKGwv34MMV6ujQ/feed"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-r', u'250k', u'-n', u'-o', u'YT_%(uploader)s/%(title)s.%(autonumber)s.%(id)s.%(ext)s', u'-w', u'-i', u'--verbose', u'--restrict-filenames', u'ytuser:https://www.youtube.com/channel/UCv0yBdt5opKGwv34MMV6ujQ/feed']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.11 - Linux-4.3.0-1-686-pae-i686-with-debian-stretch-sid
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:user] https: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] https: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 330, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

U_U will on _bigwill32_ [20151230.2003] /tz/z01/bu U_

**Comment by GaelicGrime** [comment]
what is a full URL?

**Comment by dstftw** [comment]
"https://www.youtube.com/channel/UCv0yBdt5opKGwv34MMV6ujQ" is full URL.

**Comment by GaelicGrime** [comment]
ok... when did ytuser: become unneeded? that has been in my script for a very long time and worked until this time?

**Comment by dstftw** [comment]
It was never needed for URLs and it never worked with channels.

**Comment by GaelicGrime** [comment]
ok. Thanks, I had put it in thinking it was needed long ago, and am not sure I have ever tried on a channel.  Thanks again :)

**Comment by dstftw** [comment]
Generally all these shorthands like `ytuser:` are just convenience for not typing the whole URL. When you have an URL just always pass the URL.

**Comment by GaelicGrime** [comment]
ahhh same with the other sites I assume? (vimeo is the only other site I have occasion to fetch a whole user on)
