### ISSUE TITLE
Given a video link from playlist, a whole playlist will be downloaded

### ISSUE THREAD

**Issue by nagisa** [rg3/youtube-dl#8028]
A link from playlist looks like this:

https://www.youtube.com/watch?v=3K0pu4yd9Lc&index=34&list=PLm9ij2x_v01EtvP5_-TNeaBL9Px1XdEw5

Note the `index` and the `list` parameters. `youtube-dl` will download all the videos in the list regardless of a precise video being selected and requested.

**Comment by AGSPhoenix** [comment]
You can use the `--no-playlist` parameter to suppress this behaviour.

```
PS C:\Users\Phoenix> youtube-dl "https://www.youtube.com/watch?v=3K0pu4yd9Lc&index=34&list=PLm9ij2x_v01EtvP5_-TNeaBL9Px1
XdEw5" --no-playlist
[youtube:playlist] Downloading just video 3K0pu4yd9Lc because of --no-playlist
[...]
[download] Destination: Let's Play Phoenix Wright - Ace Attorney - Part 34-3K0pu4yd9Lc.f298.mp4
[download]   5.4% of 214.29MiB at  3.85MiB/s ETA 00:52
```

If you never want the whole playlist, you can also add that parameter to your [configuration file](https://github.com/rg3/youtube-dl#configuration).

**Comment by nagisa** [comment]
The interesting thing that with a `-g` flag, it will only generate links for that exact video, making behaviours inconsistent all across the board.

**Comment by dstftw** [comment]
>The interesting thing that with a -g flag, it will only generate links for that exact video, making behaviours inconsistent all across the board.

Wrong. It will generate download URLs for each video in playlist if you [quote URL correctly](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).
