### ISSUE TITLE
i cant dowload videos from playvids.com

### ISSUE THREAD

**Issue by Tox86** [rg3/youtube-dl#8042]
hi is imposible download from playvids.com

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by Tox86** [comment]
Paste the URL you want to download: https://www.playvids.com/v/42sBOHAuwaG
[generic] 42sBOHAuwaG: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 42sBOHAuwaG: Downloading webpage
[generic] 42sBOHAuwaG: Extracting information
ERROR: Unsupported URL: https://www.playvids.com/v/42sBOHAuwaG

**Comment by Tox86** [comment]
im using this bath file for download

@echo off
 
set downloads=C:\Users\??????\Downloads
 
REM ---
 
echo.
echo.
echo.
echo This is a batch file that will use youtube-dl to download
echo a video from a live streaming site like YouTube and others.
echo.
echo.
set /p url="Paste the URL you want to download: "
 
if "%url%"=="" goto no_url
 
REM We need double '%' to escape them.
youtube-dl.exe %url% -i -w --restrict-filenames -o "%downloads%\%%(upload_date)s-%%(id)s-%%(title)s.%%(ext)s"
echo.
echo Finished!
goto end
 
:no_url
echo You didn't give me a URL
 
:end
echo ------------------------------
pause
exit

**Comment by daxterfellowesserversllc** [comment]
It appears that a valid test for Playvid is:

```
_VALID_URL = r'https?://www\.playvid\.com/watch(\?v=|/)(?P<id>.+?)(?:#|$)'
```

https://www.playvids.com/v/42sBOHAuwaG doesn't follow suit with that. Is this an alternative domain name for them?

**Comment by yan12125** [comment]
Well seems playvids.com is different from playvid.com. By the way, playvids.com always displays a blank page here. Is this website still working?

**Comment by towo** [comment]
Yep, playvids still works. Loads an encapsulated flash streamer; you can probably get the files by parsing the video_url argument of the flash player; it seems to take seriously long to start downloading, though.

**Comment by yan12125** [comment]
OK I can finally view it with a clean Firefox. However, the original example https://www.playvids.com/v/42sBOHAuwaG looks owned by shooshtime.com. youtube-dl's policy is that websites specializing in copyright infringement will not be supported. Though a logo does not that indicate shooshtime.com is the copyright holder, a safe example is better. Do you have another example?

**Comment by slrslr** [comment]
I am also getting Unsupported URL error

```
C:\youtube-dl>youtube-dl --verbose https://www.playvids.com/v/42sBOHAuwaG
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.playvids.com/v/42sBOHAuwaG']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 42sBOHAuwaG: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 42sBOHAuwaG: Downloading webpage
[generic] 42sBOHAuwaG: Extracting information
[generic] 42sBOHAuwaG: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
ERROR: Unsupported URL: https://www.playvids.com/v/42sBOHAuwaG
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\extractor\generic.py", line 3063, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.playvids.com/v/42sBOHAuwaG
```

The m4s files seems to be located on userscontent.net domain

**Comment by yan12125** [comment]
@slrslr: playvids.com is not going to be supported due to the reason stated in https://github.com/rg3/youtube-dl/issues/8042#issuecomment-238924997
