### ISSUE TITLE
i cant dowload videos from XVideos for android phone ， version 12.29

### ISSUE THREAD

**Issue by zorro0799** [rg3/youtube-dl#8047]
./youtube-dl -v --user-agent "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19" http://www.xvideos.com/video4588838/biker_takes_his_girl
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--user-agent', u'Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19', u'http://www.xvideos.com/video4588838/biker_takes_his_girl']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.10 - Darwin-15.2.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[XVideos] 4588838: Downloading webpage
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/xvideos.py", line 39, in _real_extract
    self._search_regex(r'flv_url=(.+?)&', webpage, 'video URL'))
  File "./youtube-dl/youtube_dl/extractor/common.py", line 586, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Hope to support android similar web sites o(*////▽////*)q， Thank you for all that you have done.，that‘s nice of you,thank you

**Comment by dstftw** [comment]
Do **NOT** change the user-agent.
