### ISSUE TITLE
[CBSNews]  ERROR: unable to download video data: <urlopen error unknown url type: {manifest>

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#8048]
Same video..different URLs...similar results:

http://www.cbsnews.com/news/hoverboards-parents-falling-videos-viral-social-media/
http://www.cbsnews.com/videos/injuries-spike-as-adults-try-to-ride-hoverboards

youtube-dl.py -v "http://www.cbsnews.com/videos/injuries-spike-as-adults-try-to-ride-hoverboards"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.cbsnews.com/videos/injuries-spike-as-adults-try-to-ride-hoverboards']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[CBSNews] injuries-spike-as-adults-try-to-ride-hoverboards: Downloading webpage
[debug] Invoking downloader on u'{manifest:none}rtmp://cp98363.edgefcs.net/ondemand/?auth=cbs&aifp=v001&slist={slistPrefix}{break}{slistFilePath}media/2015/12/28/592287811769/1228_C
_478933_796.mp4{slistFilePath}{manifest:f4m}http://cbsnews-vh.akamaihd.net/z/{slist::true:false}.csmil/manifest.f4m{manifest:m3u}http://cbsnews-vh.akamaihd.net/i/{slist::true:false}
manifest}'
ERROR: unable to download video data: <urlopen error unknown url type: {manifest>
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1609, in process_info
    success = dl(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1551, in dl
    return fd.download(name, info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 427, in _open
    'unknown_open', req)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1247, in unknown_open
    raise URLError('unknown url type: %s' % type)
URLError: <urlopen error unknown url type: {manifest>

Thanks
Ringo

**Comment by bonacker** [comment]
Both downloaded okay for me using my standard template for CBS NEWS

C:\progra~1\youtubedl\youtube-dl.exe -v  --no-mtime --write-info-json  -f RtmpMobileLow http://www.cbsnews.com/videos/injuries-spike-as-adults-try-to-ride-hoverboards  -o c:\recordings\%(title)s.mp5 

However I did get the error with this.

C:\progra~1\youtubedl\youtube-dl.exe -v http://www.cbsnews.com/news/hoverboards-parents-falling-videos-viral-social-media/ 

I don't know why this is happening.

•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
FIRST URL worked with my standard commandline for CBS NEWS

http://www.cbsnews.com/news/hoverboards-parents-falling-videos-viral-social-media/

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.cbsnews.com/news/hoverboards-parents-falling-videos-viral-social-media/', u'-v', u'--no-mtime', u'--write-info-json', u'-f', u'RtmpMobileLow', u'-o', u'c:\\recordings\\%(title)s.mp5']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-76860-g72eaf72, ffprobe N-75426-g8c9853a, rtmpdump 2.3
[debug] Proxy map: {}
[CBSNews] hoverboards-parents-falling-videos-viral-social-media: Downloading webpage
[info] Writing video description metadata as JSON to: c:\recordings\Videos of parents crashing off hoverboards go viral.mp5.info.json
[debug] Invoking downloader on u'http://download.cbsnews.com/media/mpx/2015/12/28/592287811769/1228_CTM_TRACY_Hoverboard_478933_240.mp4'
[download] c:\recordings\Videos of parents crashing off hoverboards go viral.mp5 has already been downloaded

[download] 100% of 5.64MiB


•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••


SECOND URL worked using my standard commandline for CBS NEWS


[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.cbsnews.com/videos/injuries-spike-as-adults-try-to-ride-hoverboards', u'-v', u'--no-mtime', u'--write-info-json', u'-f', u'RtmpMobileLow', u'-o', u'c:\\recordings\\%(title)s.mp5']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-76860-g72eaf72, ffprobe N-75426-g8c9853a, rtmpdump 2.3
[debug] Proxy map: {}
[CBSNews] injuries-spike-as-adults-try-to-ride-hoverboards: Downloading webpage
[info] Writing video description metadata as JSON to: c:\recordings\Injuries spike as adults try to ride hoverboards.mp5.info.json
[debug] Invoking downloader on u'http://download.cbsnews.com/media/mpx/2015/12/28/592287811769/1228_CTM_TRACY_Hoverboard_478933_240.mp4'
[download] Destination: c:\recordings\Injuries spike as adults try to ride hoverboards.mp5

[download]   0.0% of 5.64MiB at Unknown speed ETA Unknown ETA
[download]   0.1% of 5.64MiB at Unknown speed ETA Unknown ETA
[download]   0.1% of 5.64MiB at Unknown speed ETA Unknown ETA
[download]   0.3% of 5.64MiB at Unknown speed ETA Unknown ETA
[download]   0.5% of 5.64MiB at  1.89MiB/s ETA 00:02         
[download]   1.1% of 5.64MiB at  3.85MiB/s ETA 00:01         
[download]   2.2% of 5.64MiB at  2.64MiB/s ETA 00:02         
[download]   4.4% of 5.64MiB at  2.65MiB/s ETA 00:02         
[download]   8.8% of 5.64MiB at  2.90MiB/s ETA 00:01         
[download]  17.7% of 5.64MiB at  2.56MiB/s ETA 00:01         
[download]  35.4% of 5.64MiB at  2.61MiB/s ETA 00:01         
[download]  70.9% of 5.64MiB at  2.78MiB/s ETA 00:00         
[download] 100.0% of 5.64MiB at  1.92MiB/s ETA 00:00         
[download] 100% of 5.64MiB in 00:02                          

•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
FIRST URL did not download with this commandline
C:\progra~1\youtubedl\youtube-dl.exe -v http://www.cbsnews.com/news/hoverboards-parents-falling-videos-viral-social-media/ 


[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.cbsnews.com/news/hoverboards-parents-falling-videos-viral-social-media/', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-76860-g72eaf72, ffprobe N-75426-g8c9853a, rtmpdump 2.3
[debug] Proxy map: {}
[CBSNews] hoverboards-parents-falling-videos-viral-social-media: Downloading webpage
[debug] Invoking downloader on u'{manifest:none}rtmp://cp98363.edgefcs.net/ondemand/?auth=cbs&aifp=v001&slist={slistPrefix}{break}{slistFilePath}media/2015/12/28/592287811769/1228_CTM_TRACY_Hoverboard_478933_796.mp4{slistFilePath}{manifest:f4m}http://cbsnews-vh.akamaihd.net/z/{slist::true:false}.csmil/manifest.f4m{manifest:m3u}http://cbsnews-vh.akamaihd.net/i/{slist::true:false}.csmil/master.m3u8{manifest}'
ERROR: unable to download video data: <urlopen error unknown url type: {manifest>
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1609, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1551, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 58, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1886, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 454, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 1265, in unknown_open
URLError: <urlopen error unknown url type: {manifest>

**Comment by jaimeMF** [comment]
Thanks for the report, it will work in the next version.

@bonacker: note that this is a flv video, you may prefer to use `-o 'c:\recordings\%(title)s.%(ext)s'`, which will use `flv` as the extension.
