### ISSUE TITLE
Issues downloading subtitles from Dramafever, typo in extractor file?

### ISSUE THREAD

**Issue by codexchee** [rg3/youtube-dl#8049]
Could this be caused by subtitles being typed as subtitiles in the youtube_dl/extractor/dramafever.py file? Line 111.

info['subtitiles'].setdefault('English', [])?

[dramafever] 4766.13: Downloading episode info JSON
ERROR: An extractor error has occured. (caused by KeyError(u'subtitiles',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dramafever.py", line 111, in _real_extract
    info['subtitiles'].setdefault('English', []).append({
KeyError: u'subtitiles'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 297, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by codexchee** [comment]
youtube-dl --all-subs --sub-format "srt" http://www.dramafever.com/drama/3970/190/Running_Man/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--all-subs', u'--sub-format', u'srt', u'http://www.dramafever.com/drama/3970/190/Running_Man/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.10 - Linux-4.2.8-300.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
[debug] exe versions: none
[debug] Proxy map: {}
[dramafever] Downloading main.js
[dramafever] Downloading Akamai AMP feed
[dramafever] 3970.190: Downloading f4m manifest
[dramafever] 3970.190: Downloading m3u8 information
[dramafever] 3970.190: Downloading episode info JSON
ERROR: An extractor error has occured. (caused by KeyError(u'subtitiles',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dramafever.py", line 111, in _real_extract
    info['subtitiles'].setdefault('English', []).append({
KeyError: u'subtitiles'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 297, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'subtitiles',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Will be fixed in the next version.

**Comment by codexchee** [comment]
Thanks and thanks for all the work you guys do.
