### ISSUE TITLE
[dailymotion] .m3u8 sent instead of .mp4 stream

### ISSUE THREAD

**Issue by nsilberman** [rg3/youtube-dl#8054]
when trying to get the mp4 link, this command `youtube-dl -f 'mp4' -g http://www.dailymotion.com/video/x3k0dtv` send a .m3u8 link instead of a mp4
All the formats listed are 'mp4' but only a few of them are really a mp4 file. And I cannot use ffmpeg on my servers. 
Impossible to get the mp4 file easily (without parsing the file formats available)

**Comment by jaimeMF** [comment]
`m3u8` provides an mp4 file, so it's working as expected. Use `-f '[protocol!=?m3u8]'` instead, it won't pick a format that uses m3u8.
