### ISSUE TITLE
Make subtitles easier to obtain

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#8056]
Right now, including subtitles in downloaded videos comes off as rather complicated and longhand:

    youtube-dl -f mp4 --all-subs --embed-subs --convert-subtitles srt $URL

One option for wanting subtitles to begin with, one to embed them, and one to force the necessary format for the container. (VLC does not support `ttml`, possibly in the 3.0 release which seems to take aeons).

Possible suggestions:

1. Make `--embed-subs` imply `--all-subs`, and automatically convert subtitles to the necessary format without having to specify it manually.
2. Create a magical shorthand option (like `--cc` or `--st`) that does the same as above (basically saying: I want subtitles, just make it happen).

A side note: `--convert-subtitles` should be called `--convert-subs` to consistent with other options.

    ~$ youtube-dl --help | grep -i subtitle
    --write-sub                      Write subtitle file
    --write-auto-sub                 Write automatically generated subtitle file (YouTube only)
    --all-subs                       Download all the available subtitles of the video
    --list-subs                      List all available subtitles for the video
    --sub-format FORMAT              Subtitle format, accepts formats preference, for example: "srt" or
    --sub-lang LANGS                 Languages of the subtitles to download (optional) separated by commas,
    --embed-subs                     Embed subtitles in the video (only for mkv and mp4 videos)
    --convert-subtitles FORMAT       Convert the subtitles to other format (currently supported:
    ~$

**Comment by dstftw** [comment]
1. Those should not be mixed since `--all-subs` may involve additional network I/O. How is it supposed to know which subtitles format you want? You specify it youself in `--convert-subtitles`.
2. I'd prefer not to duplicate

**Comment by dstftw** [comment]
`--convert-subs` shorthand works as well.

**Comment by dstftw** [comment]
You can put these options in [config](https://github.com/rg3/youtube-dl#configuration) if you don't want to type them all the time.
