### ISSUE TITLE
HTTP Error 429 - I'm Blacklisted ?

### ISSUE THREAD

**Issue by Elilium** [rg3/youtube-dl#8058]
Since some days, I have this error when I try to upload a music from youtube. I have 40 users on my TeamSpeak server and 2 bots that are used all the time, this might be why I get this error.

"Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

Could it be possible to change something about it?

**Comment by dstftw** [comment]
You may want to read [FAQ entry on the issue](https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required) and [this discussion](https://github.com/rg3/youtube-dl/issues/5138).
