### ISSUE TITLE
support for tv3 co nz

### ISSUE THREAD

**Issue by johny1** [rg3/youtube-dl#8059]
Site request

url: http://www.tv3.co.nz/MOTORSPORT-SRS-SsangYong-Hampton-Downs-Round-3/tabid/3692/articleID/121615/MCat/2915/Default.aspx

>youtube-dl http://www.tv3.co.nz/MOTORSPORT-SRS-SsangYo
ng-Hampton-Downs-Round-3/tabid/3692/articleID/121615/MCat/2915/Default.aspx
[generic] Default: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Default: Downloading webpage
[generic] Default: Extracting information
ERROR: Unsupported URL: http://www.tv3.co.nz/MOTORSPORT-SRS-SsangYong-Hampton-Do
wns-Round-3/tabid/3692/articleID/121615/MCat/2915/Default.aspx

>youtube-dl -v http://www.tv3.co.nz/MOTORSPORT-SRS-Ssan
gYong-Hampton-Downs-Round-3/tabid/3692/articleID/121615/MCat/2915/Default.aspx
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.tv3.co.nz/MOTORSPORT-SRS-SsangYo
ng-Hampton-Downs-Round-3/tabid/3692/articleID/121615/MCat/2915/Default.aspx']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.12.23
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[generic] Default: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Default: Downloading webpage
[generic] Default: Extracting information
ERROR: Unsupported URL: http://www.tv3.co.nz/MOTORSPORT-SRS-SsangYong-Hampton-Do
wns-Round-3/tabid/3692/articleID/121615/MCat/2915/Default.aspx
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1287, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: mismatched tag: line 20, column 10
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 291, in extract
  File "youtube_dl\extractor\generic.pyo", line 1896, in _real_extract
UnsupportedError: Unsupported URL: http://www.tv3.co.nz/MOTORSPORT-SRS-SsangYong
-Hampton-Downs-Round-3/tabid/3692/articleID/121615/MCat/2915/Default.aspx

**Comment by davidjameshowell** [comment]
Just a heads up, this uses the Brightcove Smartplayer. Will probably be able to hook into the Brightcove extractor for this.
