### ISSUE TITLE
youtube-dl.exe fails to start if started from the path that has non-english alphabet characters

### ISSUE THREAD

**Issue by TomasPP** [rg3/youtube-dl#8062]
System: Windows 8.1 64bit

Steps to reproduce:
1. Create directory that contains only russian alphabet letters. Example folder name: "ф"
2. Download https://yt-dl.org/downloads/2015.12.29/youtube-dl.exe
 and copy youtube-dl.exe to "ф" directroy
3. run youtube-dl from the folder and get error: 
D:\media\?>youtube-dl.exe
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in <modul
e>
ImportError: No module named linecache
4. Copy one level up and run. Works without problem. 
D:\media>youtube-dl.exe
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

**Comment by dstftw** [comment]
Works fine for me:
```
C:\ф>youtube-dl.exe -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```

**Comment by TomasPP** [comment]
Sergey thanks for quick check. 
What about folder name with Greek letters : "πξκλ" (I get the same error as for "ф")

Probably the trick is to use characters which you do not have on your computer (can not type). 
I have pure Windows for English United States.
Location&Format&Region: United States 
The Only locale/language I can type is English US. 

I wanted to save some Russian youtube videos and copied video titles with russian characters from youtube into directory names :)  Hence the error report. Probably too obscure but anyways it was very weird to download exe and get this error :)

**Comment by dstftw** [comment]
Failed but with different error. However from cmd I neither can run any exe from this directory nor do anything within it, can you? So this is rather locale cmd issue.

**Comment by TomasPP** [comment]
I open command prompt directly for this directory by: (in windows explorer) holding SHIFT and right clicking on the directory then selecting "Open command window here". Then I can execute exe directly from command prompt. Anyway I see that my report describes weird combination of factors. Feel free to close it.

**Comment by dstftw** [comment]
Changing system locale to Greek fixed `πξκλ` folder but broke cyrillic one.
>selecting "Open command window here". Then I can execute exe directly from command prompt.

This work now for cyrillic folder with Greek locale but didn't work previously for greek folder with Russian locale.

**Comment by TomasPP** [comment]
Closing issue as locale cmd issue. youtube-dl.exe fails to start if run from the path that have characters that are outside of your windows locale/keyboard.  This is Windows cmd prompt quirk.
