### ISSUE TITLE
ERROR: unable to open for writing: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by waxcola** [rg3/youtube-dl#8066]
Getting the error message in the title when trying to download videos. Here's the full text using the -v option

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-o', u'G:\\Videos', u'https://www.youtube.c
om/watch?v=_xCIniRmLKw']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] _xCIniRmLKw: Downloading webpage
[youtube] _xCIniRmLKw: Downloading video info webpage
[youtube] _xCIniRmLKw: Extracting video information
[youtube] _xCIniRmLKw: Downloading DASH manifest
[youtube] _xCIniRmLKw: Downloading DASH manifest
[debug] Invoking downloader on u'https://r6---sn-8vq54vox2u-apne.googlevideo.com
/videoplayback?ipbits=0&key=yt6&ip=89.115.27.25&id=o-AHg6DTr29K4YEbdzGXcp71FM47P
VWLtSCrysaSzq2Ve0&upn=gnnvkgUbKzg&ratebypass=yes&initcwndbps=3091250&sver=3&requ
iressl=yes&signature=DEC689569049EE84D0D138F3BA6A45103FA159D7.45271BE8F78DD35794
8D2E41F7A56534B61BDC09&pl=16&pcm2cms=yes&source=youtube&mime=video%2Fmp4&expire=
1451544369&itag=22&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cm
ime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%
2Cexpire&fexp=9415516%2C9416126%2C9417581%2C9418203%2C9419670%2C9420260%2C942045
2%2C9422596%2C9422737%2C9423662%2C9424190%2C9424983%2C9425307%2C9425934&dur=4761
.948&mm=31&mn=sn-8vq54vox2u-apne&lmt=1447581364450551&ms=au&mt=1451522614&mv=m'
ERROR: unable to open for writing: [Errno 13] Permission denied: u'G:\\Videos'
Traceback (most recent call last):
  File "youtube_dl\downloader\http.pyo", line 172, in real_download
  File "youtube_dl\utils.pyo", line 295, in sanitize_open
IOError: [Errno 13] Permission denied: u'G:\\Videos'

C:\WINDOWS\system32>

**Comment by dstftw** [comment]
You are misusing `-o` option. Read [FAQ](https://github.com/rg3/youtube-dl#output-template).

**Comment by waxcola** [comment]
I should probably mention that I tried to download videos while youtube-dl.exe was inside a folder in the Program Files folder and on my desktop, to the default location, a pen drive and the same folder youtube-dl.exe was in, and with and without the -o option.

**Comment by waxcola** [comment]
Here's the full text using -v and not -o

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=_xCIniRmLKw
']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] _xCIniRmLKw: Downloading webpage
[youtube] _xCIniRmLKw: Downloading video info webpage
[youtube] _xCIniRmLKw: Extracting video information
[youtube] _xCIniRmLKw: Downloading DASH manifest
[youtube] _xCIniRmLKw: Downloading DASH manifest
[debug] Invoking downloader on u'https://r6---sn-8vq54vox2u-apne.googlevideo.com
/videoplayback?expire=1451544825&sver=3&ipbits=0&dur=4761.948&lmt=14475813644505
51&signature=1BB53D357A8D3ABCA24B50FDC885147C03A0950E.DB91BEA02E75FEB30485748519
25491DFB776F2F&ratebypass=yes&fexp=9416074%2C9416126%2C9417741%2C9420452%2C94225
96%2C9423662%2C9424372&mime=video%2Fmp4&pcm2cms=yes&initcwndbps=3101250&requires
sl=yes&key=yt6&id=o-AMxVFhWE1UedX0ekOnrnen1faRiRC7uk-guEz3qA1img&mm=31&mn=sn-8vq
54vox2u-apne&ms=au&mt=1451523121&mv=m&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbi
ts%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequire
ssl%2Csource%2Cupn%2Cexpire&ip=89.115.27.25&itag=22&pl=16&source=youtube&upn=stW
Y0g97t8U'
ERROR: unable to open for writing: [Errno 13] Permission denied: u"'Reflections'
 with vesslan-_xCIniRmLKw.mp4.part"
Traceback (most recent call last):
  File "youtube_dl\downloader\http.pyo", line 172, in real_download
  File "youtube_dl\utils.pyo", line 295, in sanitize_open
IOError: [Errno 13] Permission denied: u"'Reflections' with vesslan-_xCIniRmLKw.
mp4.part"


C:\WINDOWS\system32>

**Comment by dstftw** [comment]
The default location is the directory youtube-dl is running from. You are running it from `C:\WINDOWS\system32` where you have no rights to write to. Either run it from directory you have write access to or run under priviledged account.

**Comment by waxcola** [comment]
Changing the folder the program ran from to my desktop worked, thanks for the help. I know this is tangential, but perhaps you could help me. The only way I found of doing this was adding an autorun string to the registry entry of the command prompt with a cd to my desktop as the value. Do you know any other ways to do this?

**Comment by dstftw** [comment]
You should get familiar with cmd in the first place. [cd](https://en.wikipedia.org/wiki/Cd_%28command%29) is the command to change directory.

**Comment by pradipshirgaonkar** [comment]
change the drive or drive path

**Comment by Darthveloper21** [comment]
my command promt located on C:\ drive, and i want to download vid to D:\ drive, i tried to move youtubedl.exe to D:\ drive but it didn't work
