### ISSUE TITLE
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### ISSUE THREAD

**Issue by ricardolibra7** [rg3/youtube-dl#8071]
please help me with this error on fedora 23

**Comment by yan12125** [comment]
It's likely you're using an out-dated version. Please update to the latest version (2015.12.29) via [update instructions](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl). Feel free to open a new issue if the problem is still with the latest version.
