### ISSUE TITLE
cannot dl twitter video

### ISSUE THREAD

**Issue by rofl0r** [rg3/youtube-dl#8075]
for example https://amp.twimg.com/v/0ba0c3c7-0af3-4c0a-bed5-7efd1ffa2951

**Comment by jaimeMF** [comment]
Note that if you have the URL of the original tweet (https://twitter.com/BR_NBA/status/<something>`) it should work.

**Comment by yan12125** [comment]
Sorry for being late. Twitter smart URLs will be supported in the next version.
