### ISSUE TITLE
Can't get video from comediansincarsgettingcoffee.com

### ISSUE THREAD

**Issue by ndias** [rg3/youtube-dl#8083]
youtube-dl --verbose http://comediansincarsgettingcoffee.com/president-barack-obama-just-tell-him-you-re-the-president
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://comediansincarsgettingcoffee.com/president-barack-obama-just-tell-him-you-re-the-president']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.05
[debug] Python version 3.4.3 - Linux-4.2.8-300.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3
[debug] Proxy map: {}
[ComCarCoff] president-barack-obama-just-tell-him-you-re-the-president: Downloading webpage
ERROR: Unable to extract full data json; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/comcarcoff.py", line 36, in _real_extract
    webpage, 'full data json'))
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract full data json; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
