### ISSUE TITLE
can't DL from yahoo.com

### ISSUE THREAD

**Issue by touch444719** [rg3/youtube-dl#8084]
youtube-dl -j https://www.yahoo.com/movies/the-stars-of-daddys-home-have-very-different-212843197.html

ERROR: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Link for instance => https://www.yahoo.com/movies/the-stars-of-daddys-home-have-very-different-212843197.html

**Comment by davidjameshowell** [comment]
Please include output with the verbose flag included (-v).

**Comment by touch444719** [comment]
youtube-dl -v https://www.yahoo.com/movies/the-stars-of-daddys-home-have-very-different-212843197.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.yahoo.com/movies/the-stars-of-daddys-home-have-very-different-212843197.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.6 - Linux-3.13.0-66-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-76340-gcceed83, rtmpdump 2.4
[debug] Proxy map: {}
[Yahoo] the-stars-of-daddys-home-have-very-different: Downloading webpage
ERROR: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/yahoo.py", line 208, in _real_extract
    video_id = self._search_regex(CONTENT_ID_REGEXES, webpage, 'content ID')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 586, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
It will work in the next version, thanks for the report.
