### ISSUE TITLE
can't download from video.tt

### ISSUE THREAD

**Issue by touch444719** [rg3/youtube-dl#8085]
youtube-dl -j http://video.tt/watch_video.php?v=VOivryuNC

ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Link for instance => http://video.tt/watch_video.php?v=VOivryuNC

**Comment by touch444719** [comment]
youtube-dl -v http://video.tt/watch_video.php?v=VOivryuNC
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://video.tt/watch_video.php?v=VOivryuNC']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.6 - Linux-3.13.0-66-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-76340-gcceed83, rtmpdump 2.4
[debug] Proxy map: {}
[VideoTt] VOivryuNC: Downloading video JSON
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1271, in process_video_result
    raise ExtractorError('No video formats found!')
ExtractorError: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by TRox1972** [comment]
@touch444719 Are you able to watch the videos in your browser? For me, it loads indefinitely.

**Comment by touch444719** [comment]
The video is, indeed, loading forever. I guess their service is dead now.
Thanks for the answer tho ^^

**Comment by TRox1972** [comment]
@touch444719 Close the issue?

**Comment by TRox1972** [comment]
@yan12125 @dstftw Since the site doesn't seem to work anymore, should the extractor for it be removed?

**Comment by yan12125** [comment]
Could you find an official announcement that the site is no longer maintained?
