### ISSUE TITLE
Unable to extract title - Fail Download playlist youtube

### ISSUE THREAD

**Issue by rendergraf** [rg3/youtube-dl#8087]
youtube-dl.exe --extract-audio --audio-format mp3 -l https://www.youtube.com/playlist?list=PLRV
AmnwV_xPrvABqu9y5FIAYSnAP2g2bd
[youtube:playlist] PLRVAmnwV_xPrvABqu9y5FIAYSnAP2g2bd: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
