### ISSUE TITLE
Unable to download list and extract title

### ISSUE THREAD

**Issue by iapyeh** [rg3/youtube-dl#8093]
$ youtube-dl --yes-playlist "https://www.youtube.com/watch?v=xViga3wZK0E&index=23&list=PL920F4CC9CE56511F"
[youtube:playlist] Downloading playlist PL920F4CC9CE56511F - add --no-playlist to just download video xViga3wZK0E
[youtube:playlist] PL920F4CC9CE56511F: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by iapyeh** [comment]
Indeed! The following line would get rid of this problem.
"sudo pip install --upgrade youtube-dl" 
 Thank you very much.
