### ISSUE TITLE
youtube-dl 2015.12.31 does update over and over again

### ISSUE THREAD

**Issue by Klaus1189** [rg3/youtube-dl#8098]
2015.12.31 does update again and again if `youtube-dl -U` is used. Never had this behavior before.
It doesn't seem to recognize that it is up to date.

**Comment by dstftw** [comment]
Works fine for me:
```
C:\>youtube-dl.exe -U
youtube-dl is up-to-date (2015.12.31)
```
Post the output of `youtube-dl -v` then `youtube-dl -U`.

**Comment by Klaus1189** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Klaus\Downloads\youtube-dl>youtube-dl -v -U
[debug] System config: []
[debug] User config: [u'-i', u'--proxy', u'']
[debug] Command-line args: [u'-v', u'-U']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
Updating to version 2015.12.31 ...
Waiting for file handle to be closed ...

C:\Users\Klaus\Downloads\youtube-dl>Updated youtube-dl to version 2015.12.31.
youtube-dl -v -U
[debug] System config: []
[debug] User config: [u'-i', u'--proxy', u'']
[debug] Command-line args: [u'-v', u'-U']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
Updating to version 2015.12.31 ...
Waiting for file handle to be closed ...

C:\Users\Klaus\Downloads\youtube-dl>Updated youtube-dl to version 2015.12.31.
youtube-dl -v -U
[debug] System config: []
[debug] User config: [u'-i', u'--proxy', u'']
[debug] Command-line args: [u'-v', u'-U']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
Updating to version 2015.12.31 ...
Waiting for file handle to be closed ...

C:\Users\Klaus\Downloads\youtube-dl>Updated youtube-dl to version 2015.12.31.


I have to use `youtube-dl.exe -U` instead of `youtube-dl -U`, but in the past the second worked for me. Strange.

**Comment by Klaus1189** [comment]
I tested 2016.01.01 -> same behavior. I need ´.exe now´. But why?

**Comment by Klaus1189** [comment]
I know what was wrong. I got another copy on youtube-dl.exe in the same directory but without extension. I don't know how it came there but I deleted it and it was good.
