### ISSUE TITLE
Clarify abbreviations in manpage

### ISSUE THREAD

**Issue by porg** [rg3/youtube-dl#8099]
https://github.com/rg3/youtube-dl#format-selection mentions some less known abbreviations, without specifying them. I'd welcome a definition in brackets.

This works for filesize, height, width, tbr, abr, vbr, asr, and fps and the comparisons […]

My guess on the abbreviations:
tbr = target? bit rate
abr = average? bit rate
vbr = variable bit rate  (this one can be assumed by the tech savvy average user)
asr = ? sample rate
fps = frames per second (this one can be assumed by the tech savvy average user)

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/common.py#L89-L94

**Comment by porg** [comment]
The forementioned variables are stated in the documentation/manpage which target audience are ordinary application users. Whereas the resource you point me to -- thanks! -- is an explanation somewhere in source code. The actual abbreviation meanings prove that my assumptions have been mostly false, thus I would not have been able to operate features from the official documentation without further informal/sourcecode knowledge. It would really help to explain those uncommon abbreviations in the official documentation/manpage as well. Thanks.

**Comment by dstftw** [comment]
Format selection documentation reworked in b2dca40d8138cb044bd6c6f75a4e87ecb633fc00.

**Comment by porg** [comment]
I read through the updated documentation, and now these abbreviations and a lot more on format selection is documented well. Thanks!
