### ISSUE TITLE
Twitch.tv support - not working

### ISSUE THREAD

**Issue by szunyi** [rg3/youtube-dl#810]
Downloading videos from Twitch.tv is not working;
[youtube-dl is up-to-date (2013.04.28)]

I try this: youtube-dl http://www.twitch.tv/firmbelief/c/1757457

And i got this:
WARNING: Falling back on generic information extractor.
[generic] 1757457: Downloading webpage
[generic] 1757457: Extracting information
ERROR: Invalid URL: http://www.twitch.tv/firmbelief/c/1757457

Maybe the new twitch design?

**Comment by jaimeMF** [comment]
See https://github.com/rg3/youtube-dl/issues/614#issuecomment-71454590, it should work in the last version.
