### ISSUE TITLE
Error 10053: Unable to download XML

### ISSUE THREAD

**Issue by suimong** [rg3/youtube-dl#8102]
I encountered the error when downloading from this link: http://www.bbc.co.uk/iplayer/episode/b06t09rw/love-came-down-at-christmas

The verbose log looks like this:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-a', u'bbc christmas.txt', u'--verbose']
[debug] Batch file urls: [u'http://www.bbc.co.uk/iplayer/episode/b06t09rw/love-came-down-at-christmas', u'http://www.bbc.co.uk/iplayer/episode/b06t07cj/midnight-mass-2015-midnight-mass-from-st-georges-cathedral-southwark', u'http://www.bbc.co.uk/iplayer/episode/b06swwcl/christmas-celebration-2015', u'http://www.bbc.co.uk/iplayer/episode/b04w80ny/carols-from-kings-1954-a-festival-of-lessons-and-carols', u'http://www.bbc.co.uk/iplayer/episode/b06tg1tc/carols-from-kings-2015']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.01.01
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[bbc.co.uk] b06t09rw: Downloading video page
[bbc.co.uk] b06t09ll: Downloading media selection XML
ERROR: Unable to download XML: [Errno 10053] An established connection was aborted by the software in your host machine (caused by error(10053, 'An established connection was aborted by the software in your host machine')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 330, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1886, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 701, in http_open
  File "urllib2.pyo", line 1200, in do_open
  File "httplib.pyo", line 1132, in getresponse
  File "httplib.pyo", line 453, in begin
  File "httplib.pyo", line 409, in _read_status
  File "socket.pyo", line 480, in readline

**Comment by georGEO1989** [comment]
Are you downloading from outside the UK?

**Comment by suimong** [comment]
Yes, I tunneled in via VPN. It still worked just two days ago but with this specific url it wouldn't start from the beginning. On several other occasions, the exact same eroor were thrown out while download was in progress.

**Comment by dstftw** [comment]
This look like temporary issues on BBC side it fails each couple of requests out of 10.
