### ISSUE TITLE
Youtube playlist error

### ISSUE THREAD

**Issue by topche** [rg3/youtube-dl#8106]
root@microserver:/storages/sdc/tmp# youtube-dl -f bestaudio  "https://www.youtube.com/watch?v=1w7OgIMMRc4&list=PLP4CGQEPAJPJbZOnCv7MgdWSoZzeaqBpm" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'bestaudio', u'https://www.youtube.com/watch?v=1w7OgIMMRc4&list=PLP4CGQEPAJPJbZOnCv7MgdWSoZzeaqBpm', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-4.2.0-22-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.3-0ubuntu0.15.10.1, ffprobe 2.7.3-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLP4CGQEPAJPJbZOnCv7MgdWSoZzeaqBpm - add --no-playlist to just download video 1w7OgIMMRc4
[youtube:playlist] PLP4CGQEPAJPJbZOnCv7MgdWSoZzeaqBpm: Downloading webpage
[youtube:playlist] PLP4CGQEPAJPJbZOnCv7MgdWSoZzeaqBpm: Downloading page #1
[youtube:playlist] PLP4CGQEPAJPJbZOnCv7MgdWSoZzeaqBpm: Downloading page #2
[youtube:playlist] PLP4CGQEPAJPJbZOnCv7MgdWSoZzeaqBpm: Downloading page #3
[youtube:playlist] PLP4CGQEPAJPJbZOnCv7MgdWSoZzeaqBpm: Downloading page #4
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1365, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1339, in _extract_playlist
    page, 'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 564, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by vxbinaca** [comment]
Your version of youtube-dl is positively antique. You ca either gently prod the package maintainer to update it or remove the repository version and switch to Pip which is updated bi-weekly:

'''sudo apt-get remove youtube-dl'''

And you're gonna need to switch to the Pip repository version:

'''sudo apt-get install python-pip atomicparsley'''

Then install youtube-dl from pip:

'''sudo -H pip install --upgrade pip youtube_dl'''

From now on, use this to upgrade youtube-dl:

'''sudo -H pip install --upgrade youtube_dl'''

**Comment by vxbinaca** [comment]
Alternatively switch to the Pip version of the script which is updated MUCH more often, bi-weekly:

```sudo apt-get remove youtube-dl```
```sudo apt-get install python-pip atomicparsley```
```sudo -H pip install --upgrade pip youtube_dl```

To upgrade it in the future, run:

```sudo -H pip install --upgrade youtube_dl```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by topche** [comment]
Great guys! Thanks alot. It is working !
