### ISSUE TITLE
:ytsubs not stop after 'upload date is not in range'

### ISSUE THREAD

**Issue by stefanACM** [rg3/youtube-dl#8113]
When I execute this command it shows 2k+ videos available, then downloads thumbnail of last 24 hours videos and continue showing 'upload date is not in range' forever (until I guess go thru all 2k videos)
This should be easy to fix.

youtube-dl --write-thumbnail -u (e-mail) -p (password) :ytsubs --dateafter now-1day

**Comment by dstftw** [comment]
Because you are requesting only videos of the last 24 hours - `--dateafter now-1day`. Remove this part if you nee to download all videos.

**Comment by stefanACM** [comment]
You didnt read. I want last 24 hours videos. Problem is that app goes hronologically, download few videos that is really in range of 24h, and then continue forever checking all other videos and showing that is older then range.
It need to END app after first message 'upload date is not in range'

**Comment by dstftw** [comment]
In general playlist is not guaranteed to be in chronological order.
Duplicate of #1502.

**Comment by stefanACM** [comment]
I didn't try with standard playlists, but I did with subscribtions from 3 accounts and its perfectly chronological.
