### ISSUE TITLE
best way to check if update is available (?)

### ISSUE THREAD

**Issue by heniotierra** [rg3/youtube-dl#8114]
Hi,

I have incorporated youtube-dl in another program, and I just finished implementing youtube-dl automatic updating as the said program loads.  It's working, but the problem is that I'm not sure if my strategy was the best one. What the program currently does is access youtube-dl Download page (https://rg3.github.io/youtube-dl/download.html) and then grab the MD5 hash there and compare against the hash of the currently installed version, and if the hash differs then it updates youtube-dl. But I guess this may not be so good for maintainability, since the page source may be modified anytime. I know I could simply always call `sudo youtube-dl -U`, but I prefer to only use the update command if necessary, because of performance (the program is for the Raspberry Pi). So, what do you think? Is there a better way to do it?

Thanks!

**Comment by yan12125** [comment]
You may want to have at look at http://rg3.github.io/youtube-dl/update/versions.json and http://rg3.github.io/youtube-dl/update/LATEST_VERSION. These files are used internally for ```youtube-dl -U``` functionality.

**Comment by heniotierra** [comment]
Good, thanks!
