### ISSUE TITLE
Unable to download XML

### ISSUE THREAD

**Issue by Pat38** [rg3/youtube-dl#8115]
Hi everybody,

When executing this command : 
youtube-dl --all-subs http://www.bbc.co.uk/iplayer/episode/p0390wnv/sherlock-the-abominable-bride

the output is this : 
ERROR: Unable to download XML: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug

The version of youtube-dl used is : 2015.12.31

Thank you in advance for fixing this error.
Yours faithfully,
Patrick

**Comment by dstftw** [comment]
This look like temporary issues on BBC side it fails each couple of requests out of 10.

**Comment by Stuntaneous** [comment]
Same issue. Trying to download from the BBC's iPlayer site, through a proxy.
