### ISSUE TITLE
Getting 403 forbidden error

### ISSUE THREAD

**Issue by coolstreak** [rg3/youtube-dl#8117]
I sawed a youtube for downloading udemy courses for free but when i did all the steps it started downloading but stuck with error 403 forbidden i also tried to update it but i said that u have use a manager,pip, use that to update any help pls i new over here and dont know much about these things
![untitled](https://cloud.githubusercontent.com/assets/12906449/12074810/3f4699f4-b18f-11e5-94ad-c1f5561b8216.png)

**Comment by dstftw** [comment]
Read [bug reporting guide](https://github.com/rg3/youtube-dl#bugs).
