### ISSUE TITLE
HTTP Error 403: FORBIDDEN (caused by <HTTPError 403: 'FORBIDDEN'>)

### ISSUE THREAD

**Issue by rohanpro** [rg3/youtube-dl#8122]
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> pip install youtube-dl
Requirement already satisfied (use --upgrade to upgrade): youtube-dl in c:\users\rohan\desktop\python\lib\site-packages
PS C:\WINDOWS\system32> c:
PS C:\WINDOWS\system32> mkdir course2

    Directory: C:\WINDOWS\system32

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         1/3/2016   1:25 AM                course2

PS C:\WINDOWS\system32> cd course2
PS C:\WINDOWS\system32\course2> youtube-dl -u
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: -u option requires 1 argument
PS C:\WINDOWS\system32\course2> youtube-dl -u **********@gmail.com -p ***** https://www.udemy.com/the-complete-android-d
eveloper-course/?dtcode=ztaIRXY4hiRa
[udemy:course] Downloading login popup
[udemy:course] Logging in as *********@gmail.com
[udemy:course] the-complete-android-developer-course: Downloading webpage
[udemy:course] the-complete-android-developer-course: Downloading course JSON
[udemy:course] 428526: Enrolling in the course
[udemy:course] 428526: Downloading course curriculum
[download] Downloading playlist: The Complete Android Developer Course - Build 14 Apps
[udemy:course] playlist The Complete Android Developer Course - Build 14 Apps: Collected 131 video ids (downloading 131 of them)
[download] Downloading video 1 of 131
[udemy] Downloading login popup
[udemy] 3731782: Downloading webpage
[udemy] 3731782: Downloading lecture JSON
[udemy] 428526: Enrolling in the course
[udemy] 3731782: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN (caused by <HTTPError 403: 'FORBIDDEN'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
PS C:\WINDOWS\system32\course2>

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by rohanpro** [comment]
I actually have no clue about coding !
the above are just code to get videos from udemy !

if you can sir guide me how to use the verbose options etc please !

**Comment by dstftw** [comment]
Read the link provided **closely**.

**Comment by rohanpro** [comment]
PS C:\WINDOWS\system32\course2> youtube-dl -v https://www.udemy.com/the-complete-android-developer-course/?dtcode=ztaIRX
Y4hiRa
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.udemy.com/the-complete-android-developer-course/?dtcode=ztaIRXY4hiRa']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.01
[debug] Python version 3.5.1 - Windows-10-10.0.10240-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] the-complete-android-developer-course: Downloading webpage
[udemy:course] the-complete-android-developer-course: Downloading course JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\users\rohan\desktop\python\lib\site-packages\youtube_dl\extractor\common.py", line 330, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\rohan\desktop\python\lib\site-packages\youtube_dl\YoutubeDL.py", line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\rohan\desktop\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "c:\users\rohan\desktop\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\rohan\desktop\python\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "c:\users\rohan\desktop\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "c:\users\rohan\desktop\python\lib\urllib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by dstftw** [comment]
Sigh.
Post the output of `youtube-dl -v -u YOUR_EMAIL_HERE@gmail.com -p YOUR_PASSWORD_HERE https://www.udemy.com/the-complete-android-developer-course/?dtcode=ztaIRX`.

**Comment by rohanpro** [comment]
PS C:\WINDOWS\system32\course2> youtube-dl -v -u *************@gmail.com -p *********** https://www.udemy.com/the-complete-androi
d-developer-course/?dtcode=ztaIRXY4hiRa
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.udemy.com/the-complete-android-developer-course/?dtcode=ztaIRXY4hiRa']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.01
[debug] Python version 3.5.1 - Windows-10-10.0.10240-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as ********@gmail.com
[udemy:course] the-complete-android-developer-course: Downloading webpage
[udemy:course] the-complete-android-developer-course: Downloading course JSON
[udemy:course] 428526: Enrolling in the course
[udemy:course] 428526: Downloading course curriculum
[download] Downloading playlist: The Complete Android Developer Course - Build 14 Apps
[udemy:course] playlist The Complete Android Developer Course - Build 14 Apps: Collected 131 video ids (downloading 131 of them)
[download] Downloading video 1 of 131
[udemy] Downloading login popup
[udemy] 3731782: Downloading webpage
[udemy] 3731782: Downloading lecture JSON
[udemy] 428526: Enrolling in the course
[udemy] 3731782: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN (caused by <HTTPError 403: 'FORBIDDEN'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\users\rohan\desktop\python\lib\site-packages\youtube_dl\extractor\common.py", line 330, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\rohan\desktop\python\lib\site-packages\youtube_dl\YoutubeDL.py", line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\rohan\desktop\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "c:\users\rohan\desktop\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\rohan\desktop\python\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "c:\users\rohan\desktop\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "c:\users\rohan\desktop\python\lib\urllib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by dstftw** [comment]
This course is not free. Have you paid for it?

**Comment by rohanpro** [comment]
1-yes its not free
2-I havent paid for it

**Comment by dstftw** [comment]
You can't watch or download until you pay for it, that should be pretty obvious.
