### ISSUE TITLE
Videos, starting with "-"

### ISSUE THREAD

**Issue by boredom2** [rg3/youtube-dl#8123]
In case, Videos are starting with a "-", more or less nothing works.
For example youtube-dl -F '-6Pm6rLoY_g' leads to: "error: nmo such option -P"
I already tried to escape it or use Backticks or other kinds of quotation marks, but it just gets worse :)
Any way to overcome this Problem?

Thanks!

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#how-do-i-download-a-video-starting-with-a--

**Comment by boredom2** [comment]
Thank you, my fault!
