### ISSUE TITLE
[Errno 36] File name too long. -o templates don't support long names

### ISSUE THREAD

**Issue by Jimmm** [rg3/youtube-dl#813]
I think I've found a problem:
youtube-dl can't handle long templates.

Proof:
youtube-dl -o "02 Linear equations - 13 Evaluating expressions with unknown variables - 001 Evaluating expressions where individual variable values are unknown.mp4" TIwGXn4NalM
[youtube] Setting language
[youtube] TIwGXn4NalM: Downloading video webpage
[youtube] TIwGXn4NalM: Downloading video info webpage
[youtube] TIwGXn4NalM: Extracting video information
ERROR: unable to open for writing: [Errno 36] File name too long: '02 Linear equations - 13 Evaluating expressions with unknown variables - 001 Evaluating expressions where individual variable values are unknown.mp4.part'

**Comment by Xonshiz** [comment]
Isn't there any work around for this? I had a similar problem with a crunchyroll link :+1: 
http://www.crunchyroll.com/one-piece/episode-749-the-sword-technique-heats-up-law-and-zoro-finally-appear-715239?p360=1

**Comment by TRox1972** [comment]
@Xonshiz Specify a shorter output name using `-o`

**Comment by Xonshiz** [comment]
@TRox1972 I'm already following it.

-o "/Output/ %(title)s %(format)s.%(ext)s

**Comment by TRox1972** [comment]
@Xonshiz The title is too long to be included. You could e.g. use `-o "/Output/%(id)s.%(ext)s"` instead

**Comment by defead** [comment]
As it's using the python format , use '%(title).20s' to truncate a long title to 20 char limit.

Info: [string format](https://docs.python.org/2/library/stdtypes.html#string-formatting)
Truncating long strings  : https://pyformat.info/

**Comment by zz5678** [comment]
actually, I recommend such alias for fast downloading on youtuble-dl:
```
alias yt='youtube-dl --proxy http://127.0.0.1:1080 -o "$HOME/video/%(title).230s.%(ext)s"'
```
the filename limited to 230 characters, enough length for like:
`https://twitter.com/ABC/status/1180190308509859840`

errors occur if no such processing:
```
ERROR: unable to open for writing: [Errno 63] File name too long: '/Users/mm/temp/ABC News - Swedish climate activist Greta Thunberg at climate strike in Iowa - “We teenagers and children shouldn’t have to take the responsibility. But right now, the world leaders keep acting like children, and somebody needs to be the adult in the room.”.mp4.part'
```

especially for those people in China mainland
