### ISSUE TITLE
Trying to download a video from a site requiring a password results in "avconv exited with code 1"

### ISSUE THREAD

**Issue by AndrewSDL** [rg3/youtube-dl#8135]
I'm using the following line:
>  youtube-dl -f hls-4152 https://www.dramafever.com/drama/4465/1/The_Hippocratic_Crush/ -u *omitted* -p *omitted*

And I get the following
> [dramafever] Logging in as *omitted*
[dramafever] Downloading main.js
[dramafever] Downloading Akamai AMP feed
[dramafever] 4465.1: Downloading f4m manifest
[dramafever] 4465.1: Downloading m3u8 information
[dramafever] 4465.1: Downloading episode info JSON
[download] Destination: The Hippocratic Crush 4465.1-4465.1.mp4
avconv version 11.3, Copyright (c) 2000-2014 the Libav developers
  built on May 12 2015 19:33:29 with gcc 4.9.2 (Gentoo Hardened 4.9.2 p1.4, pie-0.6.2)
[http @ 0x7faf67668b40] HTTP error 403 Forbidden
http://dramafever-i.akamaihd.net/i/138561/region1/6e19a42d33562_,8282089,8282090,8335142,8282088,8335632,8282085,8282087,8282086,.mp4.csmil/index_0_av.m3u8?null=&hdntl=exp=1451986170~acl=%2fi%2f138561%2fregion1%2f6e19a42d33562_*~data=hdntl~hmac=c7ab04f23dca1de19f9f5a376c528af665ee163b1ba1ab9b8803d47b6de18d8f: Input/output error

> ERROR: avconv exited with code 1

I'm guessing this has to do avconv not having the login information

**Comment by dstftw** [comment]
Looks like hls-4152 is only available for premium user thus you'll have to provide account credentials with account that have access to this HD format.

**Comment by dstftw** [comment]
avconv related issue. Use `--prefer-ffmpeg` to force ffmpeg or use native hls downloader `--hls-prefer-native` or download hds format.

**Comment by AndrewSDL** [comment]
`--prefer-ffmpeg` gave a similar error. 
`--hls-prefer-native` worked perfectly.

**Comment by dstftw** [comment]
Most likely ffmpeg on your system is just a symlink to avconv.

**Comment by AndrewSDL** [comment]
Yes you're right, they turned out to be symlinked. Also, for future reference, I was wrong in saying this had something to do with passwords - all the hls videos failed with my version of avconv (11.3) and unfortunately I'm not in a position to update it.
