### ISSUE TITLE
Crunchyroll stopped working [SSL: UNKNOWN_PROTOCOL]

### ISSUE THREAD

**Issue by MartinWeingaertner** [rg3/youtube-dl#8137]
I'm using the Windows .exe on Windows 10 to download videos from Crunchyroll - this worked until about 12 hours ago. Today, I am getting the same error for every video. I can watch the videos on the website. I tried updating to the newest youtube-dl, but the error stays the same.

youtube-dl.exe "http://www.crunchyroll.com/shirobako/episode-19-did-you-catch-any-661949" -u user -p password --write-sub --sub-lang enUS --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.crunchyroll.com/shirobako/episode-19-did-you-catch-any-661949', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--write-sub', u'--sub-lang', u'enUS', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.01.01
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-76479-gc878082, ffprobe N-76479-gc878082
[debug] Proxy map: {}
[Crunchyroll] Logging in
ERROR: Wrong login info: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)'),))
  File "youtube_dl\extractor\common.pyo", line 330, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1886, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 815, in https_open
  File "urllib2.pyo", line 1197, in do_open

**Comment by oittaa** [comment]
Works for me in Debian Jessie.
```
$ youtube-dl "http://www.crunchyroll.com/shirobako/episode-19-did-you-catch-any-661949"
[Crunchyroll] 661949: Downloading webpage
[Crunchyroll] 661949: Downloading media info
[Crunchyroll] 661949: Downloading media info for 360p
[Crunchyroll] 661949: Checking 360p URL
[Crunchyroll] 661949: Downloading media info for 480p
[Crunchyroll] 661949: Checking 480p URL
[Crunchyroll] 661949: Downloading media info for 720p
[Crunchyroll] 661949: Checking 720p URL
[Crunchyroll] 661949: Downloading media info for 720p
[Crunchyroll] 661949: Checking 720p URL
[Crunchyroll] 661949: Downloading media info for 1080p
[Crunchyroll] 661949: Checking 1080p URL
[Crunchyroll] 661949: Downloading media info for 1080p
[Crunchyroll] 661949: Checking 1080p URL
[download] Destination: SHIROBAKO Episode 19 – Did You Catch Any-661949.mp4
[download] 100% of 153.13MiB in 01:44
```

Fails in Ubuntu 14.04 (which uses really old Python 2)
```
$ youtube-dl --verbose 'https://video.yahoo.com/amazing-alexander-000000031.html'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://video.yahoo.com/amazing-alexander-000000031.html']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-74-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[generic] amazing-alexander-000000031: Requesting header
WARNING: Falling back on generic information extractor.
[generic] amazing-alexander-000000031: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 191, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1157, in urlopen
    return self._opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 572, in https_open
    return self.do_open(HTTPSConnectionV3, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
```

I'm suspecting the Windows version is also using outdated urllib.

**Comment by oittaa** [comment]
@MartinWeingaertner what's your youtube-dl version?
```
youtube-dl --version
2016.01.01
```

**Comment by MartinWeingaertner** [comment]
Version was 2016.01.01, like it said in the dump. It started working for me again, so it appears this was a transient error of sorts. It's a very curious error message though, would have liked to know what the problem was.
Be that as it may, thank you for your help.
