### ISSUE TITLE
Got this error 403 error while downloading

### ISSUE THREAD

**Issue by coolstreak** [rg3/youtube-dl#8138]
PS H:\course> youtube-dl -v  -u    https://www.udemy.com/java-the-complete-java-developer-course/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'https://www.udemy.com/java-the-complete-java-developer-course/']

Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.01
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as 
[udemy:course] java-the-complete-java-developer-course: Downloading webpage
[udemy:course] java-the-complete-java-developer-course: Downloading course JSON
[udemy:course] 533682: Enrolling in the course
[udemy:course] 533682: Downloading course curriculum
[download] Downloading playlist: The Complete Java Developer Course
[udemy:course] playlist The Complete Java Developer Course: Collected 106 video ids (downloading 106 of them)
[download] Downloading video 1 of 106
[udemy] Downloading login popup
[udemy] 3132918: Downloading webpage
[udemy] 3132918: Downloading lecture JSON
[udemy] 533682: Enrolling in the course
[udemy] 3132918: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN (caused by HTTPError()); please report this issue on
https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be
sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 330, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

sorry cant show the username but i have entered it while doing this

**Comment by dstftw** [comment]
This is paid only course, have you paid for it?

**Comment by coolstreak** [comment]
No but I have seen this method on a YouTube video where he only said u will only need to register for this it worked for him
