### ISSUE TITLE
Download through link

### ISSUE THREAD

**Issue by chetanunadkat90** [rg3/youtube-dl#8145]
Not able to download through link generated by following :
-g, --get-url                    Simulate, quiet but print URL

Please help

**Comment by jaimeMF** [comment]
If you are trying to download from another machine see this [FAQ entry](https://github.com/rg3/youtube-dl/blob/40f796288afe634055c4600993b353da58e29a45/README.md#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-webbrowser).
