### ISSUE TITLE
Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError());

### ISSUE THREAD

**Issue by stuffz22** [rg3/youtube-dl#8148]
power shell is really giving me problems after installing it and trying to download a python tutorials from udemy this is the error i got ": Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError());" please i need help

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by dstftw** [comment]
No requested data provided, closing.
