### ISSUE TITLE
Can i just extract youtube video download url but not download ?

### ISSUE THREAD

**Issue by dfang** [rg3/youtube-dl#816]
Can i just extract youtube video download url but not download ?

Thanks !

**Comment by AdnanHussainTurki** [comment]
Hello guys, Sorry for late coming.

My issue is the filename of video downloaded from url fetched from youtube-dl -g

youtube-dl -g gives me a url look like:
https://r15---sn-4g57knlz.googlevideo.com/videoplayback?expire=1497021992&keepalive=yes&mv=m&mt=1497000273&ms=au&ei=yGk6WcLjCNqw8wSimYHgCQ&mn=sn-4g57knlz&mm=31&ipbits=0&requiressl=yes&itag=134&source=youtube&id=o-AG-urEi46umUqTe6H5w-0ZrCiqgqNw6bwDggUMhFUbEL&lmt=1496955572204598&dur=203.786&ip=167.114.210.100&key=yt6&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mime=video%2Fmp4&pl=25&gir=yes&initcwndbps=772500&clen=3330292&signature=4AE80109039EC8BD9B08120A1A5A1FFD0C7EA6A3.5430E1D3818868AC98DC4AEBC1080BB264913360&ratebypass=yes


when i try to download this. it gives me a file like videoplayback.mp4

what i need is a file whose name is not videoplayback but the video title.


Any suggestions?

**Comment by praburamWAPKA** [comment]
@AdnanHussainTurki 

`<?php
$url = 'https://youtube.com/watch?v='.$_GET['v'].'';

$cmd =' youtube-dl -g -f36  ' . escapeshellarg($url);
exec($cmd, $outputsd);

$results = print_r($outputsd[0], true);
$pat = '/^(https:\/\/)[a-zA-Z0-9\-.]+.googlevideo.com\//';
$results1 = preg_replace($pat, 'https://redirector.googlevideo.com/', $results);
$cmd2 =' youtube-dl -g -f18  ' . escapeshellarg($url);
exec($cmd2, $outputss);

$results2 = print_r($outputss[0], true);
$results3 = preg_replace($pat, 'https://redirector.googlevideo.com/', $results2);

$cmd3 =' youtube-dl -g -f22   ' . escapeshellarg($url);
exec($cmd3, $outputsss);
$results4 = print_r($outputsss[0], true);
$results5 = preg_replace($pat, 'https://redirector.googlevideo.com/', $results4);

$cmd4 =' youtube-dl -g -f17  ' . escapeshellarg($url);
exec($cmd4, $outputssss);

$name =' youtube-dl -e ' .  escapeshellarg($url);
exec($name, $outputs);
echo '<a href="'.$outputssss[0].'&title=[yoursite]'.$outputs[0].'.3gp">Download 3gp 176x144p</a>
<br/>
<a href="'.$results1.'&title=[yoursite]'.$outputs[0].'.mp4">Download MP4 320x240p</a><br/><a href="'.$results3.'&title=[yoursite]'.$outputs[0].'.mp4">Download MP4 640x360p</a><br/><a href="'.$results5.'&title=[yoursite]'.$outputs[0].'.mp4">Download MP4 HD720p</a><br/>
';
?>`

**Comment by AdnanHussainTurki** [comment]
@praburamWAPKA Thanks a lot, brother. It worked.

**Comment by AdnanHussainTurki** [comment]
@praburamWAPKA 
On analysing that replacement, I came to know this only works for 720p video + audio type video.

**Comment by praburamWAPKA** [comment]
you need to encode url and set filename well its similar to project
https://github.com/jeckman/YouTube-Downloader
you will get it :)

**Comment by abhisharkjangir** [comment]
@AdnanHussainTurki Add title query param at the end of the link.

**Comment by shaniax420** [comment]
> @AdnanHussainTurki
> 
> `<?php
> $url = '[https://youtube.com/watch?v='.$_GET['v']](https://youtube.com/watch?v='.$_GET%5B'v'%5D).'';
> 
> $cmd =' youtube-dl -g -f36 ' . escapeshellarg($url);
> exec($cmd, $outputsd);
> 
> $results = print_r($outputsd[0], true);
> $pat = '/^(https://)[a-zA-Z0-9-.]+.googlevideo.com//';
> $results1 = preg_replace($pat, 'https://redirector.googlevideo.com/', $results);
> $cmd2 =' youtube-dl -g -f18 ' . escapeshellarg($url);
> exec($cmd2, $outputss);
> 
> $results2 = print_r($outputss[0], true);
> $results3 = preg_replace($pat, 'https://redirector.googlevideo.com/', $results2);
> 
> $cmd3 =' youtube-dl -g -f22 ' . escapeshellarg($url);
> exec($cmd3, $outputsss);
> $results4 = print_r($outputsss[0], true);
> $results5 = preg_replace($pat, 'https://redirector.googlevideo.com/', $results4);
> 
> $cmd4 =' youtube-dl -g -f17 ' . escapeshellarg($url);
> exec($cmd4, $outputssss);
> 
> $name =' youtube-dl -e ' . escapeshellarg($url);
> exec($name, $outputs);
> echo '[Download 3gp 176x144p]('.$outputssss[0].'&title=[yoursite]'.$outputs[0].'.3gp)
> 
> 
> [Download MP4 320x240p]('.$results1.'&title=[yoursite]'.$outputs[0].'.mp4)
> [Download MP4 640x360p]('.$results3.'&title=[yoursite]'.$outputs[0].'.mp4)
> [Download MP4 HD720p]('.$results5.'&title=[yoursite]'.$outputs[0].'.mp4)
> 
> ';
> ?>`

can u fix this code pls its not working with me :(

**Comment by praburamWAPKA** [comment]
@shaniax420 
Make sure you have installed youtube-dl under /usr/local/bin this path

<?php

header('Content-Disposition:filename="video.mp4"');

$url = 'https://youtube.com/watch?v='.$_GET['v'].'';

$cmds  = ("/usr/local/bin/youtube-dl -g -f22 $url 2>&1 ")
;
exec($cmds,$out);

$link_720=print_r($out[1],true);


$cmdss  = ("/usr/local/bin/youtube-dl -g -f18 $url 2>&1 ")
;
exec($cmdss,$outt);

$link_360=print_r($outt[1],true);


$cmdsss  = ("/usr/local/bin/youtube-dl -g -f36 $url 2>&1 ")
;
exec($cmdsss,$outtt);

$link_240=print_r($outtt[1],true);



$cmdssss  = ("/usr/local/bin/youtube-dl -g -f140 $url 2>&1 ")
;
exec($cmdssss,$outttt);

$link_mp3=print_r($outttt[1],true);




$name =' /usr/local/bin/youtube-dl -e ' .  escapeshellarg($url);
exec($name, $outputs);

 

echo '<h1> <a href="'.$link_720.'&title='.$outputs[0].'(Domain.com).mp4">Download[720p]</a>';

echo '<h1> <a href="'.$link_360.'&title='.$outputs[0].'(Domain.com).mp4">Download[360p]</a>';

echo '<h1> <a href="'.$link_240.'&title='.$outputs[0].'(Domain.com).mp4">Download[240p]</a>';

echo '<h1> <a href="'.$link_mp3.'&title='.$outputs[0].'(Domain.com).mp3">Download [Mp3]</a>';
?>

**Comment by shaniax420** [comment]
@praburamWAPKA 

Happy to see your reaply but your code i cant see perfect 
Already installed in /usr/local/bin
getting error on my website http://prntscr.com/odw18j
your code look like this http://prntscr.com/odw1df


can you pls add your code in this website https://pastebin.com/   :)

**Comment by MSZ991** [comment]
Hi @praburamWAPKA  Can you help me? Actually I am getting 0 byte Txt file for some downloads ,The link is working perfect but its gives me 0 bytes .
Here is my code.
```
https.get(url, function(response) {
            console.log(url);
            filename = filename.split('%20').join('_');
            res.setHeader('Content-disposition', 'attachment; filename='+filename);
            response.pipe(res);
           
    })
```
my link is working https://r3---sn-hju7en7r.googlevideo.com/videoplayback?expire=1562976980&ei=dM4oXZ3KEIz8gQfvkY3IBw&ip=185.212.131.104&id=o-AOh3nXjLEMpmc3uJsLeRrmihesNKCZNC3HK_oN02Ji6K&itag=22&source=youtube&requiressl=yes&mime=video%2Fmp4&ratebypass=yes&dur=1665.265&lmt=1562883289242728&fvip=3&c=WEB&txp=4532432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIhAIP8ucS7-7UsWzvIWK-PU67whjhuqdiHT2rnakG7-OEfAiB5b2c7LCzdJqsl3NCyz1GKCKSbjyCJTkJaAOJpvBxzzA%3D%3D&rm=sn-5hnelr7s&req_id=c89a61829cc0a3ee&ipbypass=yes&cm2rm=sn-f5uxxo23-aixe7s,sn-ug5onfvgaq-3ipl7s&redirect_counter=3&cms_redirect=yes&mip=110.36.116.130&mm=30&mn=sn-hju7en7r&ms=nxu&mt=1562955329&mv=m&mvi=2&pl=22&lsparams=ipbypass,mip,mm,mn,ms,mv,mvi,pl&lsig=AHylml4wRgIhAMhMkGNeJ6zd6gFPCFTPAAlLYwdPPqXDnQdtQ9S1f1rZAiEAulMEdvpZ6BzCBtrNisWccM_hrn-v0PKt_SLmcYTQBVM=

**Comment by praburamWAPKA** [comment]
https://pastebin.com/LcLZz5rr

**Comment by praburamWAPKA** [comment]
@MSZ991 use this https://github.com/jeckman/YouTube-Downloader to generate links.... Don't forget to enable Ciphered Option on Config file(default.php) under Config folder

**Comment by shaniax420** [comment]
@praburamWAPKA  Thank you so much bro :) <3 

Vevo & Tseries videos  720x240 not working

**Comment by shaniax420** [comment]
720 no sound :(

**Comment by shaniax420** [comment]
Using this way but no sound 720 any way to get link 720 with Sound Vevo Videos


> <?php
 
header('Content-Disposition:filename="video.mp4"');
 
$url = 'https://youtube.com/watch?v='.$_GET['v'].'';
 
$cmdss  = ("/usr/local/bin/youtube-dl -g $url 2>&1 ")
;
exec($cmdss,$outt);

$link_720=print_r($outt[1],true);



?>

**Comment by scut-salmon** [comment]
Hi, I found that `-g` give me 
![image](https://user-images.githubusercontent.com/20534039/72874449-03839880-3d2d-11ea-8dd0-cff842b2af9f.png)
but what I really want is the url of the video such as 
https://www.youtube.com/watch?v=7E-cwdnsiow
how can I solve it?
Thanks

**Comment by melgu** [comment]
@scut-salmon Don’t you give that URL as input? You should already have it. Or am I misunderstanding your question?

**Comment by AhmedO9473** [comment]
> Hello guys, Sorry for late coming.
> 
> My issue is the filename of video downloaded from url fetched from youtube-dl -g
> 
> youtube-dl -g gives me a url look like: https://r15---sn-4g57knlz.googlevideo.com/videoplayback?expire=1497021992&keepalive=yes&mv=m&mt=1497000273&ms=au&ei=yGk6WcLjCNqw8wSimYHgCQ&mn=sn-4g57knlz&mm=31&ipbits=0&requiressl=yes&itag=134&source=youtube&id=o-AG-urEi46umUqTe6H5w-0ZrCiqgqNw6bwDggUMhFUbEL&lmt=1496955572204598&dur=203.786&ip=167.114.210.100&key=yt6&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mime=video%2Fmp4&pl=25&gir=yes&initcwndbps=772500&clen=3330292&signature=4AE80109039EC8BD9B08120A1A5A1FFD0C7EA6A3.5430E1D3818868AC98DC4AEBC1080BB264913360&ratebypass=yes
> 
> when i try to download this. it gives me a file like videoplayback.mp4
> 
> what i need is a file whose name is not videoplayback but the video title.
> 
> Any suggestions?

The default switch gives video without audio, to get them together use `-f22` LIKE this (this uses the forked project):
yt-dlp -g https://www.youtube.com/watch?v=M7Ew_zube4M -f22
which gives:
https://rr1---sn-8vq54voxxb-j5pk.googlevideo.com/videoplayback?expire=1688220907&ei=i-CfZI-MDc7OW5uLpIAL&ip=196.221.209.152&id=o-AMLSskzxMejmSAc9ACcwfgnexMDnuY17P3nuf4DmDVQp&itag=22&source=youtube&requiressl=yes&mh=HF&mm=31%2C29&mn=sn-8vq54voxxb-j5pk%2Csn-hpa7znz6&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=336250&spc=Ul2Sq_eYXZXW5O1tyj2zxyRLgSdEeL4&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=253.283&lmt=1688154968175300&mt=1688198957&fvip=2&fexp=24007246%2C51000022&beids=24350017&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOqLg-bXyGmQpPwdbjOpwPEr_GeqPg1RSioxMsxvE26rAiBMgeRyL1sayFB4UlsbauQ7BFhGAtzic5ygSH8A2zOsig%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgR-ZtCYY3IGkUTH9g-aWkoEyzgErXqJ2YQJ-104RikWICIHw61RpjEGTXLCOlQuHUoAMwPBNEjceVtneY8Tfcw8TY

**Comment by AhmedO9473** [comment]
> Using this way but no sound 720 any way to get link 720 with Sound Vevo Videos
> 
> > header('Content-Disposition:filename="video.mp4"');
> > $url = '[https://youtube.com/watch?v='.$_GET['v']](https://youtube.com/watch?v='.$_GET%5B'v'%5D).'';
> > $cmdss  = ("/usr/local/bin/youtube-dl -g $url 2>&1 ")
> > ;
> > exec($cmdss,$outt);
> > $link_720=print_r($outt[1],true);
> > ?>

use -f22 
and the screenshot for work:
![image](https://github.com/ytdl-org/youtube-dl/assets/137697048/9d0ac5a0-aef2-4853-9ff6-9f55ced430ef)
The -f22 info is:
22  mp4   1280x640    30  2 │ ≈ 11.37MiB   368k https │ avc1.64001F          mp4a.40.2       44k [en] 720p
