### ISSUE TITLE
Site request: schooltv.nl

### ISSUE THREAD

**Issue by ArchCarrier** [rg3/youtube-dl#8163]
It belongs to the npo.nl network of sites, so I suspect you can use the same code.
[Example url](http://www.schooltv.nl/video/ademhaling-de-hele-dag-haal-je-adem-maar-wat-gebeurt-er-dan-eigenlijk-in-je-lichaam/)
The ID of the video can be found in the `data-mid` attribute of a div with class `VideoPlayer`.

**Comment by dstftw** [comment]
SchoolTV will be supported in the next version.
