### ISSUE TITLE
[youtube] Signature extraction failure

### ISSUE THREAD

**Issue by rawshwpjhwhsa** [rg3/youtube-dl#8167]
Output from youtube-dl [--verbose] with version 2016.01.01. Oddly, some YouTube videos do work. But not many. 

C:\Users\richard\Downloads>youtube-dl --extract-audio --audio-format "mp3" "https://www.youtube.com/watch?v=9ZEURntrQOg" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--extract-audio', u'--audio-format', u'mp3', u'https://www.youtube.com/watch?v=9ZEURntrQOg', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-60161-g5554c6d, ffprobe N-60161-g5554c6d
[debug] Proxy map: {}
[youtube] 9ZEURntrQOg: Downloading webpage
[youtube] 9ZEURntrQOg: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube
-dl with the --verbose flag and include its complete output.
[youtube] {43} signature length 40.43, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 658, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 550, in _extract_signature_function
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl2TFPXm/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl2TFPXm/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using
 the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug
. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 658, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 550, in _extract_signature_function
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl2TFPXm/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 649, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1104, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 668, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 658, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 550, in _extract_signature_function
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl2TFPXm/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl2TFPXm/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using
 the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug
. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**

There's also a problem on Soundcloud. See --verbose output below.

C:\Users\richard\Downloads>youtube-dl --extract-audio --audio-format "mp3" "https://soundcloud.com/theweeknd/low-life-future-the-weeknd" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--extract-audio', u'--audio-format', u'mp3', u'https://soundcloud.com/theweeknd/low-life-future-the-weeknd', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-60161-g5554c6d, ffprobe N-60161-g5554c6d
[debug] Proxy map: {}
[soundcloud] theweeknd/low-life-future-the-weeknd: Resolving id
[soundcloud] theweeknd/low-life-future-the-weeknd: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; t
ype  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 312, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1712, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by rawshwpjhwhsa** [comment]
Perhaps you can put me right here. Running youtube-dl -U updates to version 2016.01.01. I've found the problem persistent for several versions.

Am I missing something?

**Comment by dstftw** [comment]
Open a new issue if you can reproduce with latest version with all required info provided.

**Comment by rawshwpjhwhsa** [comment]
Ah, I see the problem. Odd. Thank you.
