### ISSUE TITLE
Comedians in Cars Getting Coffee - Could not write header for output

### ISSUE THREAD

**Issue by nickv2002** [rg3/youtube-dl#8170]
Trying to download the new episode of Comedians in Cars Getting Coffee gets a big jumble of error:

    $ youtube-dl -v http://comediansincarsgettingcoffee.com/president-barack-obama-just-tell-him-you-re-the-president
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'-v', u'http://comediansincarsgettingcoffee.com/president-barack-obama-just-tell-him-you-re-the-president']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2016.01.01
    [debug] Python version 2.7.11 - Darwin-15.2.0-x86_64-i386-64bit
    [debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 2.8.4, ffprobe 2.8.4
    [debug] Proxy map: {}
    [ComCarCoff] president-barack-obama-just-tell-him-you-re-the-president: Downloading webpage
    [ComCarCoff] president-barack-obama-just-tell-him-you-re-the-president: Downloading m3u8 information
    [debug] Invoking downloader on u'http://content-ausc2.uplynk.com/1d9e56b0d9064718a47cb31ba169db10/g.m3u8?ad=crackle_live&pbs=9b37289a945d4cdcad4ce75a0e20dc14'
    [download] Destination: Just Tell Him You’re the President-president-barack-obama-just-tell-him-you-re-the-president.mp4
    [debug] avconv command line: avconv -y -headers 'Accept-Language: en-us,en;q=0.5
    Accept-Encoding: gzip, deflate
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
    Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
    Cookie: gt_cks_0="1\054c2ce1fd3de760438b20e534f30ddbfbfdb4596f0\054eNqlktuKAjEQRH9F8iyxL5lO4q+oiI6Xld1xxIz6YPTbbS/gILgsK01DvdSpCumjKev6ezVPpt8ZGLs4VNvKrudNhjxOZR6atHQUgciiK4gQgkhbUggAVqc7NOqB3EKgTk8XshpcAFJDBtPtvOQctprziPk/ZX+ltJrFKXsK5KLXvqha4vkuPJw/aFtuvl6CmINFix8wd6uZMhfgZCzEHmNALyzimNHx79zA3skbbmpuYCxQS/7hl1qskcJ+Jqmp6pmexvO5UvDpAiLSpiA"
    ' -i 'http://content-ausc2.uplynk.com/1d9e56b0d9064718a47cb31ba169db10/g.m3u8?ad=crackle_live&pbs=9b37289a945d4cdcad4ce75a0e20dc14' -f mp4 -c copy -bsf:a aac_adtstoasc 'file:Just Tell Him You’re the President-president-barack-obama-just-tell-him-you-re-the-president.mp4.part'
    avconv version 11.4, Copyright (c) 2000-2014 the Libav developers
      built on Oct 16 2015 09:05:58 with Apple LLVM version 7.0.0 (clang-700.0.72)
    Unable to open key file https://content-ausc2.uplynk.com/check2?b=7659b8803bb74d6fbd42665721351d5e&v=1d9e56b0d9064718a47cb31ba169db10&r=g&pbs=9b37289a945d4cdcad4ce75a0e20dc14
    Format detected only with low score of 1, misdetection possible!
    [mp3 @ 0x7fb929001400] Header missing
        Last message repeated 357 times
    [mp3 @ 0x7fb929001400] big_values too big
    [mp3 @ 0x7fb929001400] Error while decoding MPEG audio frame.
    [mp3 @ 0x7fb929001400] Header missing
        Last message repeated 219 times
    Unable to open key file https://content-ausc2.uplynk.com/check2?b=1d9e56b0d9064718a47cb31ba169db10&v=1d9e56b0d9064718a47cb31ba169db10&r=g&pbs=9b37289a945d4cdcad4ce75a0e20dc14
    [mp3 @ 0x7fb929001400] Header missing
        Last message repeated 432 times
    [mp3 @ 0x7fb928988800] Estimating duration from bitrate, this may be inaccurate
    [mp2 @ 0x7fb92a126800] Header missing
        Last message repeated 357 times
    [mp2 @ 0x7fb92a126800] big_values too big
    [mp2 @ 0x7fb92a126800] Error while decoding MPEG audio frame.
    [mp2 @ 0x7fb92a126800] Header missing
        Last message repeated 652 times
    Input #0, hls,applehttp, from 'http://content-ausc2.uplynk.com/1d9e56b0d9064718a47cb31ba169db10/g.m3u8?ad=crackle_live&pbs=9b37289a945d4cdcad4ce75a0e20dc14':
      Duration: 00:19:46.36, bitrate: 0 kb/s
      Program 0
        Metadata:
          variant_bitrate : 0
        Stream #0.0: Audio: mp2, stereo, s16p, 8 kb/s
    [mp4 @ 0x7fb92927fc00] sample rate not set
    Output #0, mp4, to 'file:Just Tell Him You’re the President-president-barack-obama-just-tell-him-you-re-the-president.mp4.part':
        Stream #0.0: Audio: mp2, stereo, 8 kb/s
    Stream mapping:
      Stream #0:0 -> #0:0 (copy)
    Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

    ERROR: avconv exited with code 1
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
        youtube_dl.main()
      File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
        _real_main(argv)
      File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
        retcode = ydl.download(all_urls)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1677, in download
        url, force_generic_extractor=self.params.get('force_generic_extractor', False))
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
        return self.process_ie_result(ie_result, download, extra_info)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
        return self.process_video_result(ie_result, download=download)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1347, in process_video_result
        self.process_info(new_info)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1609, in process_info
        success = dl(filename, info_dict)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1551, in dl
        return fd.download(name, info)
      File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
        return self.real_download(filename, info_dict)
      File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 63, in real_download
        self.report_error('%s exited with code %d' % (ffpp.basename, retval))
      File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
        self.ydl.report_error(*args, **kargs)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 540, in report_error
        self.trouble(error_message, tb)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 502, in trouble
        tb_data = traceback.format_list(traceback.extract_stack())

**Comment by dstftw** [comment]
Looks like avconv does not properly support AES-128. Works fine with recent ffmpeg.

**Comment by nickv2002** [comment]
Thanks: I tred with ffmpeg but Ubuntu version I have wasn't compiled with https either.  Not worth going down the rabbit hole of re-compiles, I'll just watch on the web. :smile:

**Comment by dstftw** [comment]
You can just grab the latest ffmpeg binaries from https://www.ffmpeg.org/download.html.

**Comment by nickv2002** [comment]
Actually just got it working on my Mac with: 
`youtube-dl --prefer-ffmpeg http://comediansincarsgettingcoffee.com/president-barack-obama-just-tell-him-you-re-the-president`

(Using the latest ffmpeg provided by Homebrew.)
