### ISSUE TITLE
Extract time period from video

### ISSUE THREAD

**Issue by bommelmuetz** [rg3/youtube-dl#8179]
I'd like to see the option to extract a sequence from a video defined by start and end timestamp, let's say from
https://www.youtube.com/watch?v=6exFuFJhfcA#t=0h08m19s 
to 
https://www.youtube.com/watch?v=6exFuFJhfcA#t=0h12m05s

So I don't have to download the complete video which is itself very big. What do you think?

**Comment by dstftw** [comment]
Duplicate of #622.
