### ISSUE TITLE
Unable to use more than one option

### ISSUE THREAD

**Issue by aleks5323** [rg3/youtube-dl#8180]
Hello! I have a problem with using more than one option.
In example:
I want to download some videos from the first added. I'm using:
C:\youtube-dl\youtube-dl.exe --playlist-reverse --playlist-end 2 https://youtube.com/user/channel_name
In this case program will start downloading from the last added video and will download only 2 videos. How can i start downloading from the first added video and the amount necessary to me.

**Comment by dstftw** [comment]
`--playlist-reverse --max-downloads 2`.

**Comment by aleks5323** [comment]
if i want to start from the 10th video what am i supposed to do then?

**Comment by dstftw** [comment]
[You can't](https://github.com/rg3/youtube-dl/issues/6845) without preliminary knowledge of videos count.
