### ISSUE TITLE
xhamster error

### ISSUE THREAD

**Issue by githubuserromi** [rg3/youtube-dl#8185]
youtube-dl -U                                                                                
youtube-dl is up-to-date (2016.01.01)

/usr/local/bin/youtube-dl -j http://xhamster.com/movies/5478812/bubble_butt_asian_bitch_has_a_nasty_threesome.html

ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl.
