### ISSUE TITLE
Soundcloud: Unable to download JSON metadata: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by RomainLG** [rg3/youtube-dl#8186]
Can't seem to download on https://soundcloud.com. Here's my console:

sessionR@kali:~$ sudo youtube-dl https://soundcloud.com/20syl/ibrahimmaalouf-20sylremix -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://soundcloud.com/20syl/ibrahimmaalouf-20sylremix', '-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-4.0.0-kali1-amd64-x86_64-with-Kali-2.0-sana
[debug] Proxy map: {}
[soundcloud] 20syl/ibrahimmaalouf-20sylremix: Resolving id
[soundcloud] 20syl/ibrahimmaalouf-20sylremix: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 203, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1231, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by RomainLG** [comment]
OK found out myself the reason... The stable version that you get using sudo apt-get install youtube-dl is outdated.

https://packages.debian.org/jessie/youtube-dl

**Comment by RomainLG** [comment]
@dstflw sorry for the unnecessary report. Thanks.

**Comment by RomainLG** [comment]
@dstftw sorry for the unnecessary report.

People finding this... Here's how to fix the situation:

sudo apt-get remove -y youtube-dl
sudo wget https://yt-dl.org/latest/youtube-dl -O /usr/local/bin/youtube-dl
sudo chmod a+x /usr/local/bin/youtube-dl
hash -r

**Comment by dstftw** [comment]
I've already pointed this out in my post.
