### ISSUE TITLE
Error while downloading, even with current version

### ISSUE THREAD

**Issue by djangman** [rg3/youtube-dl#8195]
[youtube] yNtKWhoK_sA: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\scripts\Libs\youtube-dl.py\youtube_dl\extractor\youtube.py", line 638
, in _decrypt_signature
    video_id, player_url, s
  File "C:\scripts\Libs\youtube-dl.py\youtube_dl\extractor\youtube.py", line 530
, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en
_US-vflra1XvP/base.js'; please report this issue on https://yt-dl.org/bug . Make
 sure you are using the latest version; type  youtube-dl -U  to update. Be sure
to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/js
bin/player-en_US-vflra1XvP/base.js'; please report this issue on https://yt-dl.o
rg/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete
 output.",)); please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; type  youtube-dl -U  to update. Be sure to call yo
utube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
