### ISSUE TITLE
“youtube-dl -g” option is not working.

### ISSUE THREAD

**Issue by juuk100** [rg3/youtube-dl#8202]
“youtube-dl -g” option is not working.

For example : 
youtube-dl -f 18 "https://www.youtube.com/watch?v=2t-fMNu-C_Y"
This command will work well and can download the file.

However,
youtube-dl -g -f 18 "https://www.youtube.com/watch?v=2t-fMNu-C_Y"
With this command “-g” option,  after I get the download URL,  
download doesn’t working with same URL.

youtube-dl -v -g -f 18 "https://www.youtube.com/watch?v=2t-fMNu-C_Y"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-g', u'-f', u'18', u'https://www.youtube.com/watch?v=2t-fMNu-C_Y']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.09
[debug] Python version 2.7.6 - Linux-3.13.0-48-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
https://r3---sn-oguesnle.googlevideo.com/videoplayback?mn=sn-oguesnle&mm=31&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=zAteOe-ix0Y&mv=m&mt=1452481103&itag=18&ms=au&initcwndbps=21162500&pl=19&mime=video%2Fmp4&expire=1452502747&nh=IgpwcjAyLm5ydDE5KgkxMjcuMC4wLjE&ip=52.192.169.213&key=yt6&dur=195.929&source=youtube&ratebypass=yes&lmt=1451098805674460&requiressl=yes&ipbits=0&fexp=9416008%2C9416126%2C9418200%2C9418203%2C9420452%2C9421931%2C9422596%2C9423662%2C9423749%2C9426036%2C9426760%2C9427108&sver=3&id=o-ABDFdVoLf5Qs0l625uAh8THQkZILu_3ma1mIbNVjJVex&gcr=jp&signature=33F05B77FF85A063EFB7A1E900F345A6C5B713AF.8AB60F6AC5A5040D0878090A70051A224C4E6F15

**Comment by dstftw** [comment]
`-g` is only supposed to print the download URL.
