### ISSUE TITLE
Feature request: Disabling 'ScaledBorderAndShadow' in ass files (especially crunchyroll)

### ISSUE THREAD

**Issue by Confruggy** [rg3/youtube-dl#8207]
I downloaded some Crunchyroll videos and noticed that the border of the fonts are ugly big. After checking the ass files i found a parameter calling 'ScaledBorderAndShadow' which is normally set to 'yes' but after setting it to 'no' the fonts are looking how they should like.

Example:
This is how it looks like
![](http://puu.sh/ms7N3/49f1bb1d28.png)

After setting 'ScaledBorderAndShadow' to 'no'
![](http://puu.sh/ms7R5/fa19529639.png)

So an option would be that the parameter is set automatically to 'no' while writing the sub files.

**Comment by vxbinaca** [comment]
Perhaps tag this item with "feature request" will speed a solution?

**Comment by misakitchi** [comment]
I want this option too! :)

**Comment by yan12125** [comment]
Related: #9028
Which is better, change ```ScaledBorderAndShadow: yes``` to ```ScaledBorderAndShadow: no``` or just remove ```ScaledBorderAndShadow: yes```?

**Comment by misakitchi** [comment]
Have an option to say "yes" or "no"
Some people like it with and some without...
But by default i prefere without: so "ScaledBorderAndShadow: no"

**Comment by yan12125** [comment]
Closing since #9028 merged.

More details:
As libass [defaults this value to yes](https://github.com/libass/libass/blob/e54c123/libass/ass.c#L1344), youtube-dl has to set it to false manually to override. If players want to override it again, they can call ```ass_set_style_overrides```, which MPlayer/mpv supports.

**Comment by yan12125** [comment]
FYI: I've revert previous changes. See @lachs0r's comments at #9028 for statements that persuaded me.
