### ISSUE TITLE
Direct link user in other loaction

### ISSUE THREAD

**Issue by trandinhnam** [rg3/youtube-dl#8211]
In the Documment, we have noted about the issue that using direct link from other machines
https://github.com/rg3/youtube-dl/blob/master/README.md#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-webbrowser
I have a server to get direct link, but the server is in other country, so i face the issue that in the server, some the direct links are working, but on the client, they are not working.
When i check some video from Youtube,I found that the direct link which contain country code is not working on client. 
For example: after using youtubedl.exe, i have direct link as
 
https://r4---sn-npo7zn7r.googlevideo.com/videoplayback?itag=18&ipbits=0&lmt=1410744354167120&sver=3&expire=1452610033&mime=video%2Fmp4&key=yt6&nh=IgpwcjAzLnNpbjAxKgkxMjcuMC4wLjE&requiressl=yes&ratebypass=yes&source=youtube&gcr=us&dur=2567.383&initcwndbps=742500&pl=24&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9407169%2C9416126%2C9417097%2C9418199%2C9418204%2C9418400%2C9420452%2C9422596%2C9423593%2C9423662%2C9424135%2C9425549%2C9426139%2C9426411%2C9426718%2C9427078&ip=12.58.52.15&id=o-AO-X5ppdnlbDRiXpNCknC1iOjSeHkAIRtt9aQafAcgY6&upn=GeGdqA8URiU&mm=31&mn=sn-npo7zn7r&mt=1452588363&mv=m&ms=au&signature=9AF45BE2D4318D4E26CF02E8CFB3D420D3D95A94.78B4766C0706EB1B5DA7610E7394D329B8967CDC

This link contain params gcr=us and this is reason why the client is in other country cannot reach the video. 
I try to google but i still don't find any workaround for this issue.
Anyone have any idea for this issue?
Thanks
Regards,
SSD

**Comment by phihag** [comment]
The `-g` option is known to only work if the download request comes from the same IP (12.58.52.15 in your example) with some sites, notably YouTube. It used to be that there were no such restrictions when the requests came over IPv6 for YouTube, but nowadays YouTube restricts even those. There is no other workaround.

**Comment by kidol** [comment]
@phihag What's the difference between the url you get with -g and the format url's you get on full output? Does the -g option use different code path?

**Comment by phihag** [comment]
Both URLs are the same.
