### ISSUE TITLE
ExtractorError@pluralsight.com

### ISSUE THREAD

**Issue by joshuatee** [rg3/youtube-dl#8219]
C:\Users\XXX\Desktop\Building Advanced PowerShell Functions and Modules>youtube-dl --username XXX --password XXX --verbose https://app.pluralsight.com/library/courses/powershell-modules-advanced-functions-building/table-of-contents
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--verbose', u'https://app.pluralsight.com/library/courses/powershell-modules-advanced-functions-building/table-of-contents']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.09
[debug] Python version 2.7.10 - Windows-2012Server-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] powershell-modules-advanced-functions-building: Downloading course JSON
[pluralsight:course] powershell-modules-advanced-functions-building: Downloading course data JSON
[download] Downloading playlist: Building Advanced PowerShell Functions and Modules
[pluralsight:course] playlist Building Advanced PowerShell Functions and Modules: Collected 40 video ids (downloading 40 of them)
[download] Downloading video 1 of 40
[pluralsight] Downloading login page
[pluralsight] Logging in as XXX
[pluralsight] powershell-modules-advanced-functions-building-m1-0: Downloading webpage
[pluralsight] powershell-modules-advanced-functions-building-m1-0: Downloading mp4-high URL
[pluralsight] powershell-modules-advanced-functions-building-m1-0: Waiting for 5 seconds to avoid throttling
ERROR: An extractor error has occured. (caused by KeyError(u'clipName',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\common.pyo", line 312, in extract
  File "youtube_dl\extractor\pluralsight.pyo", line 235, in _real_extract
KeyError: u'clipName'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 318, in extract
ExtractorError: An extractor error has occured. (caused by KeyError(u'clipName',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl.
