### ISSUE TITLE
Udemy Timeout Error

### ISSUE THREAD

**Issue by safa-sharpmind** [rg3/youtube-dl#8221]
I used this command to download a course which i have enrolled in udemy
youtube-dl https://www.udemy.com/aftereffects-beginners-complete -o 'videos_downloads/%(playlist_index)s-%(title)s.%(ext)s' -u myemail -p mypass

but i am getting this error after downloading some lectures

ERROR: Unable to download JSON metadata: HTTP Error 503: Connection timed out (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I am using the latest youtube-dl version. Please Help

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by safa-sharpmind** [comment]
@dstftw here is the output when i run this command with -v

Code I used

youtube-dl -v https://www.udemy.com/aftereffects-beginners-complete -o 'videos_downloads/%(playlist_index)s-%(title)s.%(ext)s' -u myemail -p mypass

Output

ERROR: Unable to download JSON metadata: HTTP Error 503: Connection timed out (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 351, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1890, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python34\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 507, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by dstftw** [comment]
This is not a full output. Nevertheless most likely you have an issue with your internet connection.

**Comment by safa-sharpmind** [comment]
Oh let me check on it then. Thanks for taking your precious time for commenting @dstftw
