### ISSUE TITLE
vodlocker does not work anymore

### ISSUE THREAD

**Issue by ibotty** [rg3/youtube-dl#8232]
There is a test case in extractor/vodlocker.py, that would show the problem. I can include the output nevertheless.

> youtube-dl --version
2015.12.23
> youtube-dl http://www.vodlocker.city/e8wvyzz4sl42 -v
[debug] System config: ['--prefer-free-formats']
[debug] User config: ['--ignore-errors', '--continue', '--no-mtime', '--all-subs', '--add-metadata', '--xattrs', '-f', '[height <? 720]']
[debug] Command-line args: ['http://www.vodlocker.city/e8wvyzz4sl42', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.23
[debug] Python version 3.4.3 - Linux-4.2.8-300.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4
[debug] Proxy map: {}
[Vodlocker] e8wvyzz4sl42: Downloading webpage
[Vodlocker] e8wvyzz4sl42: Waiting for 3 seconds
[Vodlocker] e8wvyzz4sl42: Downloading video page
ERROR: Unable to extract thumbnail; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/vodlocker.py", line 49, in _real_extract
    r'image:\s*"(http[^\"]+)",', webpage, 'thumbnail')
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 586, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract thumbnail; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I did not test HEAD, because there have not been updates to the vodlocker extractor since then.

**Comment by yan12125** [comment]
Sorry for the inconvenience, I've re-opened the original bug report #8231.
