### ISSUE TITLE
480p not downloading audio

### ISSUE THREAD

**Issue by saifsmailbox98** [rg3/youtube-dl#8235]
I am using this:

youtube-dl --no-check-certificate -f 135 https://www.youtube.com/watch?v=KyA9AtUOqRM

and only video is downloaded

but -f 22 (720p) is working fine. both audio and video is downloaded.

Maybe I am using video only format.

Please help. Also I want to have it in mp4.

**Comment by dstftw** [comment]
135 is DASH video format, i.e. video only format without audio. Use `-f video+audio`.

**Comment by saifsmailbox98** [comment]
Thanks.
