### ISSUE TITLE
having difficulty downloading a playlist from youtube

### ISSUE THREAD

**Issue by boddcoward** [rg3/youtube-dl#8237]
so ive been able to download playlists in their entirety in the past, and am now having difficulty doing so. i can download single videos no problem, i just keep running into the error below with playlists. is there something i forgot to do?

`C:\Users\Ba>C:\Users\Ba\Downloads\_a\youtube-dl.exe "https://www.youtube.com/wat
ch?v=6yhvv234oaA&list=PLfbHRQQzOkj0zKVzfDX0iNeFzMhHwLOxx" --yes-playlist --playl
ist-start 1 --playlist-end 13 -x --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=6yhvv234oaA&list=P
LfbHRQQzOkj0zKVzfDX0iNeFzMhHwLOxx', u'--yes-playlist', u'--playlist-start', u'1'
, u'--playlist-end', u'13', u'-x', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.09.03
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-76419-gdee7440, ffprobe N-76419-gdee7440
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLfbHRQQzOkj0zKVzfDX0iNeFzMhHwLOxx - add
 --no-playlist to just download video 6yhvv234oaA
[youtube:playlist] PLfbHRQQzOkj0zKVzfDX0iNeFzMhHwLOxx: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bu
g . Make sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete outp
ut.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 655, in extract_info
  File "youtube_dl\extractor\common.pyo", line 287, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1616, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 1591, in _extract_playlist
  File "youtube_dl\extractor\common.pyo", line 584, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 575, in _search_regex
RegexNotFoundError: Unable to extract title; please report this issue on https:/
/yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
  to update. Be sure to call youtube-dl with the --verbose flag and include its
complete output.`

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. See [our FAQ](https://yt-dl.org/update) if you need help updating.
