### ISSUE TITLE
Failed download from history.com

### ISSUE THREAD

**Issue by rif** [rg3/youtube-dl#8240]
python3 youtube-dl --verbose "http://www.history.com/shows/mountain-men/season-1/episode-1"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.history.com/shows/mountain-men/season-1/episode-1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.14
[debug] Python version 3.5.1 - Linux-4.3.3-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4, rtmpdump 2.4
[debug] Proxy map: {}
[History] episode-1: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "youtube-dl/youtube_dl/extractor/common.py", line 312, in extract
    return self._real_extract(url)
  File "youtube-dl/youtube_dl/extractor/history.py", line 29, in _real_extract
    webpage, 'video url')
  File "youtube-dl/youtube_dl/extractor/common.py", line 607, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment]
it's a change in history.com website.
will be fixed in the next version.

**Comment by rif** [comment]
:/

python3 youtube-dl --verbose "http://www.history.com/shows/mountain-men/season-1/episode-1"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.history.com/shows/mountain-men/season-1/episode-1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.15
[debug] Python version 3.5.1 - Linux-4.3.3-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.5, ffprobe 2.8.5, rtmpdump 2.4
[debug] Proxy map: {}
[AE] episode-1: Downloading webpage
[ThePlatform] eg47EERs_JsZ: Downloading SMIL data
ERROR: This content is not available in your location.
Traceback (most recent call last):
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "youtube-dl/youtube_dl/extractor/common.py", line 312, in extract
    return self._real_extract(url)
  File "youtube-dl/youtube_dl/extractor/theplatform.py", line 237, in _real_extract
    formats, subtitles = self._extract_theplatform_smil(smil_url, video_id)
  File "youtube-dl/youtube_dl/extractor/theplatform.py", line 42, in _extract_theplatform_smil
    raise ExtractorError(error_msg, expected=True)
youtube_dl.utils.ExtractorError: This content is not available in your location.

**Comment by remitamine** [comment]
the video is georestricted.
it can be played from USA.
