### ISSUE TITLE
pluralsight help

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#8258]
Hi 
i used this method to download pluralsight course but when i download complete course after 1 hour pluralsight Team blocked my account due to abuse their system 
i sended them email about unblock my account but they replied you used some automatic activities which is abuse
so anyother person using that trick and his account is save ?
and in this method any other way to wait second lecture atleast 1 minute after download first lecture ?
or i need to use speed command like 50kb per second ?

**Comment by dstftw** [comment]
You can't be safe until you only watch lectures in browser. For another waiting between download use `--sleep-interval`.
