### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Ale69** [rg3/youtube-dl#8259]
WARNING: [youtube:playlist] PLx0hmihIkZOGYntKwYkaaeCm1x4ci8V4x: Playlist page is missing OpenGraph title, falling back ...
ERROR: Unable to extract title; please report this issue

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by Ale69** [comment]
it helped me .thanx
