### ISSUE TITLE
VEVO SMIL Streams Not Downloadable

### ISSUE THREAD

**Issue by ds115** [rg3/youtube-dl#8263]
I haven't been able to get SMIL streams for new videos. Old videos continue to work as expected, with SMIL options still detected for them. 

youtube-dl.exe -F http://www.vevo.com/watch/adele/Hello/GBH481500074 -v
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'http://www.vevo.com/watch/adele/Hello/GBH48
1500074', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-59396-g4156df5, ffprobe N-59396-g4156df5
[debug] Proxy map: {}
[Vevo] Retrieving oauth token
[Vevo] GBH481500074: Downloading JSON metadata
[Vevo] GBH481500074: Downloading HLS formats
[Vevo] GBH481500074: Downloading m3u8 information
[Vevo] GBH481500074: Downloading SMIL file
WARNING: Unable to download SMIL file: HTTP Error 404: Not Found
[info] Available formats for GBH481500074:
format code extension resolution note
meta mp4 multiple Quality selection URL
Low mp4 176x144 H264@ 56k, AAC@128k
Med mp4 480x360 H264@ 500k, AAC@128k
High mp4 1280x720 H264@2000k, AAC@128k
1002 mp4 640x360 1002k , avc1, mp4a
1434 mp4 960x540 1434k , avc1, mp4a
2738 mp4 960x540 2738k , avc1, mp4a
3585 mp4 1280x720 3585k , avc1, mp4a
4661 mp4 1920x1080 4661k , avc1, mp4a
5885 mp4 1920x1080 5885k , avc1, mp4a (best)
```

**Comment by Hrxn** [comment]
FTR, the second link in the initial posting is wrong, ID gets terminated by Newline.

**Comment by ds115** [comment]
Isn't the point of the wrapping ('url') to prevent them from terminating incorrectly? 

All the older videos, with the same type of line breaks, still work perfectly fine. 

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'http://www.vevo.com/watch/adele/Rolling-in-
the-Deep/GB1411000094', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-59396-g4156df5, ffprobe N-59396-g4156df5
[debug] Proxy map: {}
[Vevo] Retrieving oauth token
[Vevo] GB1411000094: Downloading JSON metadata
[Vevo] GB1411000094: Downloading HLS formats
[Vevo] GB1411000094: Downloading m3u8 information
[Vevo] GB1411000094: Downloading SMIL file
C:\Users\User\Downloads\youtube-dl.exe\youtube_dl\extractor\vevo.py:236: Futur
eWarning: The behavior of this method will change in future versions.  Use speci
fic 'len(elem)' or 'elem is not None' test instead.
[info] Available formats for GB1411000094:
format code  extension  resolution note
meta         mp4        multiple   Quality selection URL
Low          mp4        176x144    H264@  56k, AAC@128k
Med          mp4        480x360    H264@ 500k, AAC@128k
High         mp4        1280x720   H264@2000k, AAC@128k
SMIL_564     mp4        512x288    x264@ 500k, quicktime@ 64k
SMIL_864     mp4        512x288    x264@ 800k, quicktime@ 64k
SMIL_1328    mp4        768x432    x264@1200k, quicktime@128k
SMIL_1728    mp4        768x432    x264@1600k, quicktime@128k
SMIL_2528    mp4        1280x720   x264@2400k, quicktime@128k
SMIL_3328    mp4        1280x720   x264@3200k, quicktime@128k
SMIL_4392    mp4        1920x1080  x264@4200k, quicktime@192k
SMIL_5392    mp4        1920x1080  x264@5200k, quicktime@192k
1023         mp4        640x360    1023k , avc1, mp4a
1461         mp4        960x540    1461k , avc1, mp4a
2691         mp4        1280x720   2691k , avc1, mp4a
3528         mp4        1280x720   3528k , avc1, mp4a
4440         mp4        1920x1080  4440k , avc1, mp4a
5477         mp4        1920x1080  5477k , avc1, mp4a  (best)

**Comment by ds115** [comment]
Tested the new version, SMIL (for new videos) still isn't working. 

youtube-dl.exe -F http://www.vevo.com/watch/lissie/Don
t-You-Give-Up-On-Me-%28Official-Video%29/GB4111501580 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'http://www.vevo.com/watch/lissie/Dont-You-G
ive-Up-On-Me-%28Official-Video%29/GB4111501580', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.23
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-59396-g4156df5, ffprobe N-59396-g4156df5
[debug] Proxy map: {}
[Vevo] Retrieving oauth token
[Vevo] GB4111501580: Downloading JSON metadata
[Vevo] GB4111501580: Downloading webpage
[Vevo] GB4111501580: Downloading HLS formats
[Vevo] GB4111501580: Downloading m3u8 information
[Vevo] GB4111501580: Downloading SMIL file
WARNING: Unable to download SMIL file: HTTP Error 404: Not Found
[info] Available formats for GB4111501580:
format code  extension  resolution note
meta         mp4        multiple   Quality selection URL
1030         mp4        640x360    1030k , avc1, mp4a
1495         mp4        960x540    1495k , avc1, mp4a
2811         mp4        960x540    2811k , avc1, mp4a
3659         mp4        1280x720   3659k , avc1, mp4a
4750         mp4        1920x1080  4750k , avc1, mp4a
5859         mp4        1920x1080  5859k , avc1, mp4a  (best)

**Comment by Hrxn** [comment]
> SMIL (for new videos) still isn't working.

Okay, just to get this right, you are explicitly trying to download the SMIL format and that format only, right?

I looked into it, and I actually had the same warning:
```
WARNING: Unable to download SMIL file: HTTP Error 404: Not Found
```

But `-f` uses `bestvideo+bestaudio\best` as default, and that gets you a good .mp4 file..

**Comment by Hrxn** [comment]
Oh well, just noticed, a commit from a couple of hours ago https://github.com/rg3/youtube-dl/commit/2975fe1a7be39b66d14fc7ef68ea7db948f0e40f seems to address this..

**Comment by ds115** [comment]
@Hrxn Yes, I am trying to get the SMIL formats specifically. The highest quality m3u8 version seems to always wind up being 25FPS which can cause playback issues if the master was originally 24. The SMIL options are also anamorphic in some cases, resulting in significantly better encoding & compression on them, because the m3u8 option has to waste bit-rate on the letterboxing. Basically, in a fair amount of cases, for HD videos, SMIL_5392 wound up producing the same, or higher quality results, even though they are never marked as the highest quality (from what I've seen). It's my personal default. I only go back and grab the m3u8 version if the SMIL one was 25FPS in full resolution (1920x1080). 

Here is a mediainfo comparison for a video. The first option is the default/bestvideo, versus the SMIL

http://pastebin.com/hUGb3uRD

That commit adds SMIL support for new videos? Awesome, can't wait to get it workin' again!

**Comment by Hrxn** [comment]
To be honest, I just skimmed that commit, but yes, it looks like it ;-)

**Comment by remitamine** [comment]
SMIL formats are not available for all videos.
we try to extract them when it's possible.
in the next version there will be more formats to choose from.
and also geo restricted videos will be downloaded from youtube.

**Comment by ds115** [comment]
Do you know if SMIL is something they don't support for new videos? I was aware it wasn't available for every past video, but from what I could tell, it wasn't working for anything from 2015 (and the second half of 2014), which made me think there was just a new method, like when they switched to v3.

**Comment by remitamine** [comment]
there are three sources for formats information(used by html and flash players):
- the video player service contain this formats(depend on the video): http, smil(http and rtmp), ism.
- the api video streams contain this formats(depend on the video): http, dash, ism, hls.
most of them are available from three hosting services: akamai, level3, amazon(aws).
- youtube formats.
after the change youtube-dl will extract http(akamai, level3, amazon), m3u8(akamai, level3, amazon), smil(level3 http) if its available and fallback to youtube for geo restricted videos.
there is another smil manifest but i didn't add extraction for it because for all formats i get almost the same size(2GB).
ism and dash are not supported.
so i think these is the best of what we can do for now.

**Comment by ds115** [comment]
OK, I'll wait to see what's up with the new update. I'm not sure how to get SMIL manifests to test it myself, but thank you for the update.

**Comment by ds115** [comment]
So just to wrap this up (I tested the new version), are you saying Vevo no longer supports SMIL for newer videos? It doesn't work on any video from like July, 2014 - present. This is different than some videos not having it available. Or am I doing something wrong? Does SMIL work on any newer videos (on Vevo) for anyone else?

I'm not sure what this is:  there is another smil manifest but i didn't add extraction for it because for all formats i get almost the same size(2GB)., but could it be the missing SMIL manifest, even if it produces files of the same file size? Previous SMIL downloads weren't bigger in size, they were just encoded better.

**Comment by remitamine** [comment]
the main reason why the SMIL can't be extracted for new video is that they only available using the api which contain http, dash, ism, hls.
the other SMIL manifest appear less than the one that youtube-dl extract.
for example:
for this video: http://www.vevo.com/watch/hurts/somebody-to-die-for/GB1101300280
the other SMIL manifest: http://smilstream.vevo.com/HDFlash/v1/smil/GB1101300280/gb1101300280.smil
you can exatrct this url(there are other formats) http://vstream.vevo.com/v1/smil/GB1101300280/gb1101300280_564k_512x288_x264_500_quicktime_64.mp4
when i try to download it:
```
aria2c http://vstream.vevo.com/v1/smil/GB1101300280/gb1101300280_564k_512x288_x264_500_quicktime_64.mp4
[#342a53 16KiB/1.9GiB(0%) CN:16 DL:130KiB ETA:4h27m19s]
```
even if it's the worst quality(this type of files also present in BrightcoveNewIE).

**Comment by ds115** [comment]
Okay, so new videos don't have the standard accessible SMIL files because Vevo doesn't have a video player service with that information anymore? 

Are these other SMIL manifest files still accessible for newer videos? Because, yeah, it loaded as 2GB, but it completed as a normal download after I let it download for a minute. I mean, if you can locate these for other videos still, that is exactly what I was looking for.
http://pastebin.com/sak3UsWJ

Even if they download slowly, in cases where they are anamorphic or the right frame rate, it'd be worth the wait. 

How do you get these SMIL manifest files? I can only find the m3u8 files when I try to find the manifests.

**Comment by remitamine** [comment]
both types of SMIL are accessible only from the video player service.
