### ISSUE TITLE
ffmped no longer embeds thumbnail

### ISSUE THREAD

**Issue by macneisj** [rg3/youtube-dl#8266]
$ youtube-dl -U
youtube-dl is up-to-date (2016.01.15)
___________________________________________

$ youtube-dl -v --embed-thumbnail --restrict-filenames --prefer-ffmpeg --extract-audio --audio-quality 0 --audio-format mp3 --no-playlist --output "%(title)s.%(ext)s" --add-metadata --metadata-from-title "%(title)s" https://www.youtube.com/watch?v=L_VEdra0wUE
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--embed-thumbnail', u'--restrict-filenames', u'--prefer-ffmpeg', u'--extract-audio', u'--audio-quality', u'0', u'--audio-format', u'mp3', u'--no-playlist', u'--output', u'%(title)s.%(ext)s', u'--add-metadata', u'--metadata-from-title', u'%(title)s', u'https://www.youtube.com/watch?v=L_VEdra0wUE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.7.6 - Linux-3.13.3-i686-with-glibc2.0
[debug] exe versions: avconv present, avprobe 10, ffmpeg 2.1.3, ffprobe 2.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] L_VEdra0wUE: Downloading webpage
[youtube] L_VEdra0wUE: Downloading video info webpage
[youtube] L_VEdra0wUE: Extracting video information
[youtube] {43} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {18} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {5} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {36} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {17} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {134} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {133} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {160} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {140} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {171} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {249} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {250} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] {251} signature length 41.43, html5 player en_US-vflGR-A-c
[youtube] L_VEdra0wUE: Downloading DASH manifest
[youtube] L_VEdra0wUE: Downloading thumbnail ...
[youtube] L_VEdra0wUE: Writing thumbnail to: Mot_rhead_-_I_Ain_t_No_Nice_Guy.jpg
[debug] Invoking downloader on u'https://r2---sn-gvbxgn-tt1d.googlevideo.com/videoplayback?id=2ff54476b6b4c141&itag=141&source=youtube&requiressl=yes&pl=18&ms=au&mv=m&mm=31&mn=sn-gvbxgn-tt1d&ratebypass=yes&mime=audio/mp4&gir=yes&clen=8746575&lmt=1428039661038833&dur=274.320&sver=3&signature=7937A1A591970CEB3D06E1541B85E315BBE8D189.9622DBEBA564C614B612CEEE53390B3EF2F99FBD&fexp=9408491,9415515,9416126,9417299,9420452,9422544,9422596,9423662,9424115,9425447,9425716,9426382,9426492,9427133&mt=1453076761&upn=hIMzD8np8jg&key=dg_yt0&ip=99.247.214.189&ipbits=0&expire=1453098441&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,ms,mv,mm,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Mot_rhead_-_I_Ain_t_No_Nice_Guy.m4a
[download] 100% of 8.34MiB in 00:09
[ffmpeg] Correcting container in "Mot_rhead_-_I_Ain_t_No_Nice_Guy.m4a"
[debug] ffmpeg command line: ffmpeg -y -i file:Mot_rhead_-_I_Ain_t_No_Nice_Guy.m4a -c copy -f mp4 file:Mot_rhead_-_I_Ain_t_No_Nice_Guy.temp.m4a
[fromtitle] parsed title: Motörhead - I Ain't No Nice Guy
[ffmpeg] Adding metadata to 'Mot_rhead_-_I_Ain_t_No_Nice_Guy.m4a'
[debug] ffmpeg command line: ffmpeg -y -i file:Mot_rhead_-_I_Ain_t_No_Nice_Guy.m4a -vn -acodec copy -metadata 'comment=Acoustic version, circa 2001. Unplugged Lemmy and Phil Campbell. Song is from the 1992 Album: March ör Die' -metadata 'description=Acoustic version, circa 2001. Unplugged Lemmy and Phil Campbell. Song is from the 1992 Album: March ör Die' -metadata artist=Diamondvd -metadata 'title=Motörhead - I Ain'"'"'t No Nice Guy' -metadata date=20080103 -metadata 'purl=https://www.youtube.com/watch?v=L_VEdra0wUE' file:Mot_rhead_-_I_Ain_t_No_Nice_Guy.temp.m4a
[debug] ffmpeg command line: ffprobe -show_streams file:Mot_rhead_-_I_Ain_t_No_Nice_Guy.m4a
[ffmpeg] Destination: Mot_rhead_-_I_Ain_t_No_Nice_Guy.mp3
[debug] ffmpeg command line: ffmpeg -y -i file:Mot_rhead_-_I_Ain_t_No_Nice_Guy.m4a -vn -acodec libmp3lame -q:a 0 file:Mot_rhead_-_I_Ain_t_No_Nice_Guy.mp3
Deleting original file Mot_rhead_-_I_Ain_t_No_Nice_Guy.m4a (pass -k to keep)
[ffmpeg] Adding thumbnail to "Mot_rhead_-_I_Ain_t_No_Nice_Guy.mp3"
[debug] ffmpeg command line: ffmpeg -y -i file:Mot_rhead_-_I_Ain_t_No_Nice_Guy.mp3 -i file:Mot_rhead_-_I_Ain_t_No_Nice_Guy.jpg -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' file:Mot_rhead_-_I_Ain_t_No_Nice_Guy.temp.mp3
ERROR: file:Mot_rhead_-_I_Ain_t_No_Nice_Guy.jpg: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1723, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/bin/youtube-dl/youtube_dl/postprocessor/embedthumbnail.py", line 50, in run
    self.run_ffmpeg_multiple_files([filename, thumbnail_filename], temp_filename, options)
  File "/usr/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 155, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError
________________________________________________________________________________

 $ ls
Mot_rhead_-_I_Ain_t_No_Nice_Guy.jpg
Mot_rhead_-_I_Ain_t_No_Nice_Guy.mp3

**Comment by dstftw** [comment]
You are using an old version of ffmpeg, update it.

**Comment by macneisj** [comment]
I am
ffmpeg version 2.1.3 Copyright (c) 2000-2013 the FFmpeg developers
  built on Oct 26 2014 12:08:36 with gcc 4.8.2 (GCC)
However updating ffmpeg is not a solution for many people, myself included. I built this distro from source and an upgrade of ffmpeg is not an easy task without breaking the system.  Not every one lives in a package world :)

I am hoping for a better solution!

Thanks
