### ISSUE TITLE
Ubable to download from BBC site

### ISSUE THREAD

**Issue by Alexx3142** [rg3/youtube-dl#8268]
I have tried to download as in the command below from the BBC website, see line 9. The error seems consistent. Don't know what the problem is, not enough knowledge to diagnose properly. Downloading from youtube is working without any problem. See the end of the list for system information. Thanks for any help you can give.

felix@ubuntu:~$ 
felix@ubuntu:~$ sudo apt-get install youtube-dl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
youtube-dl is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 31 not to upgrade.
felix@ubuntu:~$ 
felix@ubuntu:~$ youtube-dl --verbose -o ~/tmp/x2 http://www.bbc.co.uk/iplayer/episode/p039wd0f/war-and-peace-episode-1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-o', '/home/felix/tmp/x2', 'http://www.bbc.co.uk/iplayer/episode/p039wd0f/war-and-peace-episode-1']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-74-generic-i686-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[bbc.co.uk] p039wd0f: Downloading playlist XML
ERROR: Unable to download XML: HTTP Error 404: Not Found; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 191, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1157, in urlopen
    return self._opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

felix@ubuntu:~$ 
felix@ubuntu:~$ lsb_release -a
LSB Version:	core-2.0-ia32:core-2.0-noarch:core-3.0-ia32:core-3.0-noarch:core-3.1-ia32:core-3.1-noarch:core-3.2-ia32:core-3.2-noarch:core-4.0-ia32:core-4.0-noarch:core-4.1-ia32:core-4.1-noarch:security-4.0-ia32:security-4.0-noarch:security-4.1-ia32:security-4.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
felix@ubuntu:~$ 
felix@ubuntu:~$ uname -r
3.13.0-74-generic
felix@ubuntu:~$

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by Alexx3142** [comment]
Hi, read your FAQ and using that have loaded the latest version, all
    easy to understand. The latest Ubuntu one was well out of date.
    
    However, though the symptoms are completely different now there
    still seems to be a problem? I posted a new issue, #8275. Thanks for
    any help.
    
    Alex
    
    
    On 18/01/16 15:46, Sergey M. wrote:
    
    
      You are using an outdated version of youtube-dl. Read our FAQ
        if you have troubles updating.
      —
        Reply to this email directly or view
          it on GitHub.
