### ISSUE TITLE
Skip download if video is already downloaded?

### ISSUE THREAD

**Issue by bokisa12** [rg3/youtube-dl#8271]
So let's say I have a playlist with 3 videos that I want to download as MP3, I'll just do : 

'youtube-dl [playlist link here] <playlist link here> --playlist-start 1 --extract-audio --audio-format mp3'

Ok, so I download the playlist, but then I add 3 new videos, and I want to download them too. If I execute the same command as before, it will download ALL the videos in the playlist, even the ones that were already downloaded before.

How can I make it so that it doesn't download the playlist videos that are already downloaded?

**Comment by dstftw** [comment]
Use `--download-archive`.

**Comment by bokisa12** [comment]
I tried to use it, but it seems to require an argument (the list of IDs of all downloaded videos)??

**Comment by jaimeMF** [comment]
It requires the filename to know where to store and look for the downloaded videos.

**Comment by bokisa12** [comment]
Thank you!!
