### ISSUE TITLE
Problem (bug) with youtube-dl with videos on 1080p

### ISSUE THREAD

**Issue by littleboy62** [rg3/youtube-dl#8272]
Hello everyone.

My message will be "small", I think. ^^

First, sorry for mistakes, I'm french.

I've a problem (or a bug) on youtube-dl executable, on windows.

All videos are *successfully downloaded*... **excepted in 1080p**.

The video, in 1080p, *is successfully downloaded*, **but without sound**.

I use **command prompt**, with this line :
* youtube-dl.exe -f 137 https://www.youtube.com/watch?v=YIwuCs1Yovw 

(code format 137 for 1080p)
The video is successfully downloaded.... but without sound.

I use **command prompt** again, but with this line :
* youtube-dl.exe -f 22 https://www.youtube.com/watch?v=YIwuCs1Yovw

(code format 22 for 720p)
The video is successfully downloaded.... and with sound.

If the bug **has been already posted**, sorry.

Or maybe my command line **is wrong**.

Can you help me, please. ;)
Thanks by advance.

Best regards, thomas.

**Comment by iamriel** [comment]
Hi, based on the output of -F in your url, 137 is 'video only' format

`137          mp4        1920x1080  DASH video 4133k , avc1.640028, 24fps, video only, 45.75MiB`

As you can see above, there is `video only`, that means it does not have audio.  You need to combine it with one of the audio formats:
```
249          webm       audio only DASH audio   58k , opus @ 50k, 896.00KiB
250          webm       audio only DASH audio   80k , opus @ 70k, 1.14MiB
171          webm       audio only DASH audio  110k , vorbis@128k (44100Hz), 1.75MiB
140          m4a        audio only DASH audio  127k , m4a_dash container, aac  @128k (44100Hz), 2.32MiB
251          webm       audio only DASH audio  143k , opus @160k, 2.21MiB
141          m4a        audio only DASH audio  255k , m4a_dash container, aac  @256k (44100Hz), 4.66MiB
```

So for example, you want the format with code `141`, your command goes like this:

`youtube-dl -f 137+141 https://www.youtube.com/watch\?v\=YIwuCs1Yovw`

For windows:

`youtube-dl.exe -f 137+141 https://www.youtube.com/watch?v=YIwuCs1Yovw`

Let us know if it works.

**Comment by littleboy62** [comment]
Hi.

Thanks, really ! :+1: 

It works great.

I've  downloaded ffmpeg too.


Topic solved.

Best regards
