### ISSUE TITLE
Ubable to download from BBC site [2]

### ISSUE THREAD

**Issue by Alexx3142** [rg3/youtube-dl#8275]
Having a problem downloading - see command below. Each time I run this it downloads some more of the file and then comes out with the same error, about 6 times so far. I also noticed that it does not display any ETA time until it's been running for a while. Then when the ETA time is displayed it continuously INCREASES until the failure.

felix@ubuntu:~$ 
felix@ubuntu:~$ youtube-dl --verbose -o ~/tmp/x2 http://www.bbc.co.uk/iplayer/episode/p039wd0f/war-and-peace-episode-1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-o', u'/home/felix/tmp/x2', u'http://www.bbc.co.uk/iplayer/episode/p039wd0f/war-and-peace-episode-1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.7.6 - Linux-3.13.0-74-generic-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] p039wd0f: Downloading video page
[bbc.co.uk] b06x5mmg: Downloading media selection XML
[bbc.co.uk] b06x5mmg: Downloading m3u8 information
[bbc.co.uk] b06x5mmg: Downloading m3u8 information
[bbc.co.uk] b06x5mmg: Downloading m3u8 information
[bbc.co.uk] b06x5mmg: Downloading m3u8 information
[bbc.co.uk] b06x5mmg: Downloading m3u8 information
[debug] Invoking downloader on u'http://ic.021c947e.0f06e7.vod-hls-uk-live.bbcfmt.vo.llnwi.net/usp/auth/vod/piff_abr_full_hd/839622-b06x5mmg/vf_b06x5mmg_9315fe4f-05ee-4ea3-8a16-c00e641e7fd8.ism.hlsv2.ism/vf_b06x5mmg_9315fe4f-05ee-4ea3-8a16-c00e641e7fd8.ism.hlsv2-audio=128000-video=5070000.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 465
[download] Destination: /home/felix/tmp/x2
[download]  24.7% of ~2.22GiB at 355.62KiB/s ETA 45:44ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1609, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1551, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 101, in real_download
    success = ctx['dl'].download(frag_filename, {'url': frag_url})
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1890, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 716, in http_open
    req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>

felix@ubuntu:~$ 
felix@ubuntu:~$ 
felix@ubuntu:~$ 
felix@ubuntu:~$ lsb_release -a
LSB Version:	core-2.0-ia32:core-2.0-noarch:core-3.0-ia32:core-3.0-noarch:core-3.1-ia32:core-3.1-noarch:core-3.2-ia32:core-3.2-noarch:core-4.0-ia32:core-4.0-noarch:core-4.1-ia32:core-4.1-noarch:security-4.0-ia32:security-4.0-noarch:security-4.1-ia32:security-4.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
felix@ubuntu:~$ uname -r
3.13.0-74-generic
felix@ubuntu:~$ 
felix@ubuntu:~$ 
felix@ubuntu:~$ 
felix@ubuntu:~$ 
felix@ubuntu:~$ 
felix@ubuntu:~$ 
felix@ubuntu:~$ 
felix@ubuntu:~$ 
felix@ubuntu:~$ 
felix@ubuntu:~$ youtube-dl -U
youtube-dl is up-to-date (2016.01.15)
felix@ubuntu:~$

**Comment by dstftw** [comment]
Most likely you have an issue with your internet connection. It works fine for me without any issue even via public proxy.
