### ISSUE TITLE
Site support Request www.gute-filme.to

### ISSUE THREAD

**Issue by hasbond1** [rg3/youtube-dl#8282]
can u add support this site?

1.
youtube-dl -o - "http://www.gute-filme.to/movies/lektionen-in-finsternis/" | vlc-2.2.1\vlc -

[generic] lektionen-in-finsternis: Requesting headerWARNING: Falling back on generic information extractor.[generic] lektionen-in-finsternis: Downloading webpage[generic] lektionen-in-finsternis: Extracting informationERROR: Unsupported URL: http://www.gute-filme.to/movies/lektionen-in-finsternis/

2.
youtube-dl -v "http://www.gute-filme.to/movies/lektionen-in-finsternis/"

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.gute-filme.to/movies/lektionen-in-fin
sternis/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-77380-g2dba040
[debug] Proxy map: {}
[generic] lektionen-in-finsternis: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lektionen-in-finsternis: Downloading webpage
[generic] lektionen-in-finsternis: Extracting information
ERROR: Unsupported URL: http://www.gute-filme.to/movies/lektionen-in-finsternis/
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1289, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: undefined entity: line 27, column 0
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 312, in extract
  File "youtube_dl\extractor\generic.pyo", line 1908, in _real_extract
UnsupportedError: Unsupported URL: http://www.gute-filme.to/movies/lektionen-in-finst
ernis/

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by hasbond1** [comment]
this site not have copyright content.

**Comment by hasbond1** [comment]
I have e-mail traffic, he said that there is no copyright content available

**Comment by hasbond1** [comment]
this site not have copyright content.
I have e-mail traffic, he said that there is no copyright content available

**Comment by hasbond1** [comment]
this site not have copyright content.
I have e-mail traffic with him, he said that there is no copyright content available and may be used

**Comment by dstftw** [comment]
As of [wikipedia article](https://en.wikipedia.org/wiki/Lessons_of_Darkness) this film was produced by Canal+ who apparently owns the copyright. I have found neither mention of public domain dedication nor any evidence of rights to distribute this film by gute-filme.to (as well as couple of other random films).
With this in mind and looking at their FAQ page:
>Anders als andere “Warezseiten” bieten wir euch ein ordentliches

I tend to consider this to be clearly copyright infringement thus gute-filme.to can't be supported by youtube-dl.
