### ISSUE TITLE
windows version only accordingly install  python 2.7?

### ISSUE THREAD

**Issue by lweo** [rg3/youtube-dl#8284]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in <modul
e>
ImportError: No module named linecache
Traceback (most recent call last):
  File "<install zipextimporter>", line 1, in <module>
ImportError: No module named zipextimporter
Traceback (most recent call last):
  File "__main__.py", line 2, in <module>
ImportError: No module named __future__

I  have tried:

set path=C:\Python;%PATH%

set path=C:\Python32;%PATH%  (my python installed version is 3.2）

but it didn't work.

**Comment by dstftw** [comment]
What are you trying to do in the first place?

**Comment by robhook** [comment]
I had this same error.  I had an old install of Python27 on my system (C:\p27) and copied the executable to the C:\p27\Lib folder.  It ran fine from there.  I had already tried adding that folder the path, etc, but it didn't seem to help.  For some reason only moving the executable to the lib folder worked.  Weird.

**Comment by Hrxn** [comment]
This can't be right, the `youtube-dl.exe` listed as the official download on the youtube-dl website is a self-contained / standalone binary. You can run this from anywhere..

**Comment by robhook** [comment]
Don't know what to tell you.  It didn't work for several hours and I tried various things and this is what fixed it.  Maybe the conversion to stand-alone didn't work properly this time.  Who knows.
