### ISSUE TITLE
Unable to extract title

### ISSUE THREAD

**Issue by copycat9909** [rg3/youtube-dl#8285]
youtube-dl "https://www.youtube.com/watch?v=gf82KBJfvBo&index=86&list=PLdkHKvwbLCvldlHgOnn7qeWquYO6q1zAr"
[youtube:playlist] Downloading playlist PLdkHKvwbLCvldlHgOnn7qeWquYO6q1zAr - add --no-playlist to just download video gf82KBJfvBo
[youtube:playlist] PLdkHKvwbLCvldlHgOnn7qeWquYO6q1zAr: Downloading webpage
[youtube:playlist] PLdkHKvwbLCvldlHgOnn7qeWquYO6q1zAr: Downloading page #1
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
