### ISSUE TITLE
ERROR: content too short - ISSUE

### ISSUE THREAD

**Issue by szunyi** [rg3/youtube-dl#829]
Hello

My biggest problem about youtube-dl is the "ERROR: content too short"
[ youtube-dl is up-to-date (2013.05.07) ]

I use youtube-dl only for Youtube.
Mostly i get the error, when the download speed is getting low.
I have a 80/80 internet on my server so the problem is not belongs to me.

I tried the -R feature, but not working on these situation :(

Is anybody can describe the problem and/or fix this error?

Thanks!

**Comment by dogancelik** [comment]
I keep getting this error when downloading a batch of videos.
I'm not sure if it's related but I'm using `-f bestaudio` argument.
It would be nice if there was a way to retry instead of exiting program. (without using batch/bash)

**Comment by joepie91** [comment]
What's the status on this? There's a `--retries` parameter anyway, but it seems to (still) be ignored completely for 'content too short' errors.

**Comment by dstftw** [comment]
Duplicate of #809.
