### ISSUE TITLE
can't download from iqiyi.com

### ISSUE THREAD

**Issue by basheewang** [rg3/youtube-dl#8292]
C:>youtube-dl --verbose http://www.iqiyi.com/v_19rrl5ge6k.html#vfrm=2-3-0-1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.iqiyi.com/v_19rrl5ge6k.html#vfrm=2-3-0-1']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.01.15
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] a3239f129ebb5eb8bb304af28c0a7fd8: Downloading JSON metadata
ERROR: Unable to load data. Error code: A000001; please report this issue on https://yt-dl.org/bug . Make sure you are u
sing the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "c:\python34\lib\site-packages\youtube_dl\extractor\common.py", line 312, in extract
    return self._real_extract(url)
  File "c:\python34\lib\site-packages\youtube_dl\extractor\iqiyi.py", line 237, in _real_extract
    raise ExtractorError('Unable to load data. Error code: ' + raw_data['code'])
youtube_dl.utils.ExtractorError: Unable to load data. Error code: A000001; please report this issue on https://yt-dl.org
/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Thanks for the report. iQiYi will work again in the next version.
