### ISSUE TITLE
Automate cleaning up of old issues

### ISSUE THREAD

**Issue by maxnordlund** [rg3/youtube-dl#8296]
First let me say thanks for this awesome tool. I happened to notice there are more the 1300 issues, and I assume most of them have been abandoned/no longer relevant.

So I propose setting up something like Twitters [NO-CARRIER][1] to automate this. It could also be run from one of the maintainers computer from time to time, if a server is out of the question.

---

Twitter also made a [few other bots][2] to help/remind people how to write issues, but it's pretty specific to bootstrap. It does, however, serve as an excellent starting point for a similar system for youtube-dl, e.g. have the user included the full log/using the latest version (by examining the log output)/etc.

[1]: https://github.com/twbs/no-carrier
[2]: https://github.com/twbs/no-carrier#see-also

**Comment by phihag** [comment]
We close the issues that are not relevant. At the moment, we just get more issues than we have developers to solve.
