### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by osugo** [rg3/youtube-dl#8298]
I am using youtbe-dl to get the mp3 urls of youtube videos. It has been working great until recently when only a few of the links returned actually played music. The rest result in an error 403. All attempts to remedy this have failed. 

Is there anything that can be done about this?

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by osugo** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--rm-cache-dir', u'-x', u'-f', u'140', u'--verbose', u'https://www.youtube.com/watch?v=YqeW9_5kURI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.6.6 - Linux-2.6.32-573.8.1.el6.x86_64-x86_64-with-centos-6.7-Final
[debug] exe versions: ffmpeg 0.6.5, ffprobe 0.6.5
[debug] Proxy map: {}
Removing cache dir /root/.cache/youtube-dl ..
[youtube] YqeW9_5kURI: Downloading webpage
[youtube] YqeW9_5kURI: Downloading video info webpage
[youtube] YqeW9_5kURI: Extracting video information
[youtube] YqeW9_5kURI: Downloading DASH manifest
[youtube] YqeW9_5kURI: Downloading DASH manifest
[debug] Invoking downloader on u'https://r19---sn-o097zne6.googlevideo.com/videoplayback?id=62a796f7fe645112&itag=140&source=youtube&requiressl=yes&mm=31&mn=sn-o097zne6&nh=IgpwcjAxLnNqYzA3KgkxMjcuMC4wLjE&ms=au&pl=21&gcr=cn&mv=u&ratebypass=yes&mime=audio/mp4&gir=yes&clen=2873201&lmt=1427313829324648&dur=178.932&upn=qIieBVrP1Z8&key=dg_yt0&sver=3&fexp=9407190,9408499,9416126,9417577,9418223,9420452,9422596,9423662,9424214,9424862,9425517,9426724&signature=3621987327508D32CDA502727E23AC778B694C40.8BDD84B7A65C02414191ADEF4C6BA68E13DB1274&mt=1453464615&ip=198.57.171.34&ipbits=0&expire=1453486811&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,nh,ms,pl,gcr,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Major Lazer & DJ Snake - Lean On (feat. MØ) (Official Music Video)-YqeW9_5kURI.m4a has already been downloaded
[download] 100% of 2.74MiB
[ffmpeg] Correcting container in "Major Lazer & DJ Snake - Lean On (feat. MØ) (Official Music Video)-YqeW9_5kURI.m4a"
WARNING: Your copy of ffmpeg is outdated, update ffmpeg to version 1.0 or newer if you encounter any errors.
[debug] ffmpeg command line: ffmpeg -y -i 'file:Major Lazer & DJ Snake - Lean On (feat. MØ) (Official Music Video)-YqeW9_5kURI.m4a' -c copy -f mp4 'file:Major Lazer & DJ Snake - Lean On (feat. MØ) (Official Music Video)-YqeW9_5kURI.temp.m4a'
ERROR: Unrecognized option 'c'
Traceback (most recent call last):
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1723, in post_process
files_to_delete, info = pp.run(info)
File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 458, in run
self.run_ffmpeg(filename, temp_filename, options)
File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 159, in run_ffmpeg
self.run_ffmpeg_multiple_files([path], out_path, opts)
File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 155, in run_ffmpeg_multiple_files
raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

**Comment by dstftw** [comment]
>Your copy of ffmpeg is outdated, update ffmpeg to version 1.0 or newer if you encounter any errors.
