### ISSUE TITLE
Jython Support - locking

### ISSUE THREAD

**Issue by dustinschultz** [rg3/youtube-dl#8302]
Hi,

youtube-dl does not work with Jython (http://www.jython.org/), at least on Mac OS X (possibly on Windows). The problem is related to `import fcntl` which doesn't exist in Jython :(

https://github.com/rg3/youtube-dl/blob/6ec6cb4e956abbd76a6ff42336821770a5fbbcc7/youtube_dl/utils.py#L1219-L1225

Can additional support be added for "soft locking" ... for instance, like in this Python package: https://pypi.python.org/pypi/filelock/

Thanks,
Dustin

**Comment by mdPlusPlus** [comment]
Have you found a workaround for that yet? I'd like to embed youtube-dl in my java youtube downloader.

**Comment by jaimeMF** [comment]
Unless you need the `--download-archive` option, you can just remove that line and change the `setproctitle`(in the same file) to:
```python
def setproctitle(title):
    return
```
It seems to work fine.

**Comment by mdPlusPlus** [comment]
As far as I see editing the setproctitle() is not necessary. I removed the fcntl part however.

Now it works when I don't provide any parameters for ydl_opts, if I do I get the following error:

```
test
Exception in thread "MainThread" Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "__pyclasspath__/youtube_dl/YoutubeDL.py", line 292, in __init__
AttributeError: 'set' object has no attribute 'get'

Process finished with exit code 1
```

My code is the following:
```java
public class Main {
    public static void main(String[] args) {
        PythonInterpreter python = new PythonInterpreter();
        python.exec("print(\"test\")");
        python.exec(
            "from __future__ import unicode_literals\n" +
            "import youtube_dl\n" +
            "\n" +
            "ydl_opts = {'listformats'}\n" +
            "with youtube_dl.YoutubeDL(ydl_opts) as ydl:\n" +
            "   ydl.download(['http://www.youtube.com/watch?v=BaW_jenozKc'])"
        );

    }
}
```

**Comment by jaimeMF** [comment]
@mdPlusPlus `ydl_opts` must be a dictionary: `ydl_opts = {'listformats': True}`.

**Comment by mdPlusPlus** [comment]
Thank you, that worked.

**Comment by yan12125** [comment]
Basic Jython support will be included in the next version.

**Comment by yan12125** [comment]
Known issues on Jython:
* ```--no-check-certificate``` cause errors. A patch is needed, see http://bugs.jython.org/issue2481
* ```--console-title``` requires complete ctypes implementation. See http://bugs.jython.org/issue2148 and http://bugs.jython.org/issue1917
* ```--download-archive``` requires file locking. See http://bugs.jython.org/issue1943
