### ISSUE TITLE
Stops working when running in background without terminal

### ISSUE THREAD

**Issue by iampradip** [rg3/youtube-dl#8304]
I am using in Raspberry Pi. Trying to run this in ssh: `youtube-dl https://www.youtube.com/watch?v=xxxx &` starts downloading but closing ssh connection terminates youtube-dl. I tried putting several downloads in sh file and running it without terminal, but youtube-dl doesn't try to download any of them. wget works in same situation. In short, youtube-dl only works when terminal is active.

Note: This was not issue in previous versions when DASH formats were not supported.

**Comment by jaimeMF** [comment]
Can't you just use `nohup youtube-dl <ARGS> &`?

Wget chooses [to ignore SIGHUP](https://www.gnu.org/software/wget/manual/html_node/Signals.html), I don't know if we want to do this.

> Note: This was not issue in previous versions when DASH formats were not supported.

If you can point to the specific version that supposedly breaks it, we can try to revert the change. Without that info I can't know what can be the cause.

**Comment by iampradip** [comment]
> Can't you just use nohup youtube-dl <ARGS> &?

Thanks, this works.

> If you can point to the specific version that supposedly breaks it, we can try to revert the change. Without that info I can't know what can be the cause.

I am not sure which version was that, I had it installed from repository on Raspbian Wheezy.
