### ISSUE TITLE
error downloading video on facebook

### ISSUE THREAD

**Issue by MartinDelille** [rg3/youtube-dl#8307]
Link: https://www.facebook.com/lastvideo/videos/10153271516331003/

Output:

    $ youtube-dl https://www.facebook.com/lastvideo/videos/10153271516331003/
    [facebook] 10153271516331003: Downloading webpage
    ERROR: An extractor error has occured. (caused by KeyError(0,)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
