### ISSUE TITLE
Can't download Youtube Playlist

### ISSUE THREAD

**Issue by cornjuliox** [rg3/youtube-dl#8309]
Trying to download an entire Youtube playlist, around 102 videos in all. Im getting this error when I run it (pic attached)
![screen shot 2016-01-24 at 10 57 06 am](https://cloud.githubusercontent.com/assets/5615794/12534214/60223e48-c289-11e5-8f15-2e255744c5b7.png)

**Comment by dstftw** [comment]
[How to report bugs](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).
