### ISSUE TITLE
Download playlist as one mp3 file?

### ISSUE THREAD

**Issue by orschiro** [rg3/youtube-dl#8310]
Dear all,

youtube-dl's export and audio conversion feature for entire playlists is simply great!

One feature I am missing, however, is the option to automatically concatenate the individually downloaded and converted audio files into a single mp3 file that preserves the file position of the tracks according to the playlist. 

What is your opinion on such a feature?

Thankfully,

~Robert

**Comment by dstftw** [comment]
Duplicate of #5956.

**Comment by orschiro** [comment]
Dear @dstftw,

Thank you for referencing the already existing request!

~Robert
