### ISSUE TITLE
ERROR: Signature extraction failed:

### ISSUE THREAD

**Issue by orikidoz** [rg3/youtube-dl#8312]
Hi 
First I can see you fixed something that looks like the issue I'm reporting but updating didn't solve it for me.
I'm using the module inside python script using the following line pafy.new()
I'm using the youtube-dl module version 2015.11.10 and pafy 0.4.2

I'm getting the following error:
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 732, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 795, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/Library/Python/2.7/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'jr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'jr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks,
Ori

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by orikidoz** [comment]
What is the latest youtube dl?

I'm running pip instsall --upgrade 

Ori

**Comment by dstftw** [comment]
https://pypi.python.org/pypi/youtube_dl

**Comment by orikidoz** [comment]
Thanks
