### ISSUE TITLE
matchtv.ru live stream support ?

### ISSUE THREAD

**Issue by spvkgn** [rg3/youtube-dl#8313]
Is there a way add extractor to catch live stream from http://matchtv.ru/#live-player ?
Or at least get url to f4m manifest ?

**Comment by dstftw** [comment]
Матч ТВ will be supported in the next version.

**Comment by SlazE888** [comment]
At now, LiveTV streams from that site not playing. You can try: [https://matchtv.ru/vdl/player/media/133529](url)

**Comment by wb027** [comment]
`$ youtube-dl -U
Updating to version 2019.08.02 ...
Updated youtube-dl. Restart youtube-dl to use the new version.

$ youtube-dl https://matchtv.ru/vdl/player/media/133529
[SportBox] 133529: Downloading webpage
ERROR: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl --verbose https://matchtv.ru/vdl/player/media/133529
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://matchtv.ru/vdl/player/media/133529']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.02
[debug] Python version 2.7.15+ (CPython) - Linux-5.0.0-23-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[SportBox] 133529: Downloading webpage
ERROR: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/sportbox.py", line 62, in _real_extract
    webpage, 'sources'),
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`
