### ISSUE TITLE
Can I have some comments in batch file list?

### ISSUE THREAD

**Issue by saifsmailbox98** [rg3/youtube-dl#8315]
For example,
```
http://www.youtube.com/xxxxxxxxxxxxxxxxxxxxxxxx1     # Example Title Comment
http://www.youtube.com/xxxxxxxxxxxxxxxxxxxxxxxx2     # Example Title Comment
http://www.youtube.com/xxxxxxxxxxxxxxxxxxxxxxxx3     # Example Title Comment
http://www.youtube.com/xxxxxxxxxxxxxxxxxxxxxxxx3     # Example Title Comment
```
So that I can save title or anything else along with the batch file item
so that whatever after ```#``` or any other symbol you choose the command ignores it until ```next line``` is reached.

**Comment by dstftw** [comment]
Only this way:
```
# Example Title Comment
http://www.youtube.com/xxxxxxxxxxxxxxxxxxxxxxxx1
# Example Title Comment
http://www.youtube.com/xxxxxxxxxxxxxxxxxxxxxxxx2
```

**Comment by saifsmailbox98** [comment]
Okay, thanks.

**Comment by saifsmailbox98** [comment]
@dstftw Two more questions.

One: What if I have a youtube link after the hash sign in the batch list file?
```# http://www.youtube.com/xxxxxxxxxxxxxx```
Is it going to download this video?

Two: Can I leave blank lines in the batch list file?

**Comment by dstftw** [comment]
1. No, each line starting with `#`, `;` or `]` is ignored.
2. Yes.

**Comment by saifsmailbox98** [comment]
Thanks
