### ISSUE TITLE
youtube-dl -g, gives me always two separate links of audio and video

### ISSUE THREAD

**Issue by dennmtr** [rg3/youtube-dl#8316]
after december update i dont know how, youtube-dl stopped giving me a unique video and audio link to use. always separate links of audio and video . i cant work like this, i need it for scripts in debian. windows version keeps working fine. note, i have no configuration files at all. i removed and install everything again. debian release: raspbian jessie. keep it in mind

**Comment by phihag** [comment]
This is correct behavior - by default, youtube-dl will pick the best quality, and sometimes that happens to be a video + an audio stream. Pass in `-f best` to explicitly select the single best format (i.e. one which contains both video and audio).

**Comment by dennmtr** [comment]
fine! but i didnt use this option in the past. why now? thank you

**Comment by phihag** [comment]
Previously, the best quality of the videos you tested may have been in a single file, instead of multiple ones.

**Comment by dennmtr** [comment]
maybe, but i had no problems at all two years with no options (only -g). windows version keeps working fine without any option too. btw the problem solved and this is the point :)

**Comment by phihag** [comment]
youtube-dl has the same behavior on Windows. Most likely, you have not installed avconv or ffmpeg on Windows, or incorrectly configured them. Once you do, youtube-dl will notice and may return multiple links on Windows too.

**Comment by dennmtr** [comment]
for some reason avconv was removed... everything is ok after installing without any option! I have a warning message, but even that the direct links are single as i want them "Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this." I just ignore
