### ISSUE TITLE
cspan video - unable to download

### ISSUE THREAD

**Issue by rudolf323** [rg3/youtube-dl#8317]
I'm having this error while downloading a cspan video:

```
ERROR: unable to find video id and type; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
 update. Be sure to call youtube-dl with the --verbose flag and include its comp
lete output.

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.c-span.org/video/?4533454...']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.23
[debug] Python version 2.7.10 - Windows-2012Server-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[CSpan] 403595: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 352, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1904, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default

ERROR: unable to find video id and type; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
 update. Be sure to call youtube-dl with the --verbose flag and include its comp
lete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 666, in extract_info
  File "youtube_dl\extractor\common.pyo", line 313, in extract
  File "youtube_dl\extractor\cspan.pyo", line 77, in _real_extract
ExtractorError: unable to find video id and type; please report this issue on ht
tps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-
dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.

```

**Comment by rudolf323** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.c-span.org/video/?403595'
]
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.23
[debug] Python version 2.7.10 - Windows-2012Server-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[CSpan] 403595: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 352, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1904, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default

**Comment by phihag** [comment]
http://www.c-span.org/video/?403595 and http://www.c-span.org/video/?4533454... (not sure which one you wanted) are both 404 pages, so this is a correct error message. Which video did you want to download? I am closing this issue for now, since I believe youtube-dl's behavior to be correct - it emits a 404 error for a page that is a 404, what else could it do?

**Comment by rudolf323** [comment]
http://www.c-span.org/video/?401206-1/words-senators-trent-lott-tom-daschle

C:\Users\Administrator\Desktop>youtube-dl.exe --verbose "http://www.c-span.org/v
ideo/?401206-1/words-senators-trent-lott-tom-daschle"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.c-span.org/video/?401206-
1/words-senators-trent-lott-tom-daschle']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.23
[debug] Python version 2.7.10 - Windows-2012Server-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[CSpan] 401206: Downloading webpage
ERROR: unable to find video id and type; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
 update. Be sure to call youtube-dl with the --verbose flag and include its comp
lete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 666, in extract_info
  File "youtube_dl\extractor\common.pyo", line 313, in extract
  File "youtube_dl\extractor\cspan.pyo", line 77, in _real_extract
ExtractorError: unable to find video id and type; please report this issue on ht
tps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-
dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.
