### ISSUE TITLE
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info

### ISSUE THREAD

**Issue by jd1008** [rg3/youtube-dl#8318]
$ ytdl --verbose -F 'https://www.youtube.com/watch?v=zLDgV6cQeXg'
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://www.youtube.com/watch?v=zLDgV6cQeXg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.23
[debug] Python version 2.7.10 - Linux-4.2.8-200.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: ffmpeg 2.6.6, ffprobe N-51556-ge278500
[debug] Proxy map: {}
[youtube] zLDgV6cQeXg: Downloading webpage
[youtube] zLDgV6cQeXg: Downloading video info webpage
[youtube] zLDgV6cQeXg: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1508, in _real_extract
    raise ExtractorError('no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')
ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
1. This video is not available.
2. You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
