### ISSUE TITLE
Downloading channel into playlist folders

### ISSUE THREAD

**Issue by jurgenskrause** [rg3/youtube-dl#8319]
I am trying to use youtube-dl to download Khan Academy for an offline computer center.

My aim is to download then entire channel with each playlist in it's own folder

I use the following command:
youtube-dl -o "youtube/khanacademy/%(playlist_title)s/%(title)s.%(ext)s" --write-description --download-archive /youtube/log/khan.txt --ignore-errors ytuser:khanacademy

It downloads all of the videos from the channel into a single playlist folder called "Uploads from Khan Academy"

How do I get it to put each playlist in it's own folder without downloading each playlist individually?

Kindly
Jurgens

**Comment by dstftw** [comment]
Use playlists URL https://www.youtube.com/user/khanacademy/playlists.
