### ISSUE TITLE
Lynda videos not downloading...!?

### ISSUE THREAD

**Issue by frankiekam** [rg3/youtube-dl#8322]
Hiya Tech Support

I'm running on Windows 7 Professional I've downloaded Python27.0 32-bit and when I run the below script, it always hangs at the output for minutes(!):
**[lynda] 379150: Checking 1-540 video format URL**
and then finally it dumps out the error message: "ERROR: Unable to download webpage: timed out (caused by timeout('timed out',))"

I am stumped. I earlier tried it with Python34.0 64-bit and the same thing happened. Stuff at the last line hangs for a l-o-n-g time. Then it throws up the same error message.

Below is my script. I've changed my username and password. Everything else is exactly as I typed and the exact output. *What did I do wrong?*

Cheers
Frankie Kam, Malaysia
----------------------------------------------------------------------------------------------------------------------------

C:\Python270>youtube-dl.exe  --verbose http://www.lynda.com/Storyline-tutorials/
Up-Running-Articulate-Storyline-2/196582-2.html --username yeahright@gmail.com
 --password 123yeahright
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.lynda.com/Storyline-tutor
ials/Up-Running-Articulate-Storyline-2/196582-2.html', u'--username', u'PRIVATE'
, u'--password', u'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.23
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Logging in as yeahright@gmail.com
[lynda:course] Confirming log in and log out from another device
[lynda:course] 196582: Downloading course JSON
[lynda:course] Logging out
[download] Downloading playlist: Up and Running with Articulate Storyline 2
[lynda:course] playlist Up and Running with Articulate Storyline 2: Collected 42
 video ids (downloading 42 of them)
[download] Downloading video 1 of 42
[lynda] Logging in as yeahright@gmail.com
[lynda] 379150: Downloading video JSON
**[lynda] 379150: Checking 1-540 video format URL**

...very long pause....

[lynda] 379150: Checking 1-540 video format URL
ERROR: Unable to download webpage: timed out (caused by timeout('timed out',))
  File "youtube_dl\extractor\common.pyo", line 352, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1904, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 716, in http_open
  File "urllib2.pyo", line 1200, in do_open
  File "httplib.pyo", line 1132, in getresponse
  File "httplib.pyo", line 453, in begin
  File "httplib.pyo", line 409, in _read_status
  File "socket.pyo", line 480, in readline

**Comment by dstftw** [comment]
Can you watch it in browser in the first place? Post the output of `youtube-dl.exe --dump-pages --print-traffic --verbose http://www.lynda.com/Storyline-tutorials/Up-Running-Articulate-Storyline-2/196582-2.html --username yeahright@gmail.com --password 123yeahright`.
