### ISSUE TITLE
Youku Download Incomplete For Long Videos

### ISSUE THREAD

**Issue by temperson** [rg3/youtube-dl#8324]
Youku downloads only half of the video and stops (safely closes, no error messages), from my experience, only for videos greater than ~60 minutes.

Example URLs:
http://v.youku.com/v_show/id_XMTMwNzQwMTcwMA.html
http://v.youku.com/v_show/id_XOTUwMzc1MDI0.html

```
youtube-dl --verbose http://v.youku.com/v_show/id_XMTMwNzQwMTcwMA.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://v.youku.com/v_show/id_XMTMwNzQwMTcwMA.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.23
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-76822-g12a419d
[debug] Proxy map: {}
[youku] XMTMwNzQwMTcwMA: Downloading JSON metadata
[download] Downloading playlist: ???2
[youku] playlist ???2: Collected 16 video ids (downloading 16 of them)
[download] Downloading video 1 of 16
[debug] Invoking downloader on 'http://k.youku.com/player/getFlvPath/sid/9453833
68788412f9216d_00/st/flv/fileid/0300012500565CCE09A5682BEEFCF9017144F0-8D0B-8A39
-4D28-1B0BE8AD219D?hd=1&K=6d61c39bc2247024282b2292&myp=0&ypp=0&token=4124&ctype=
12&oip=1155809357&ep=eyaRGUGOVcgI4ivXjD8bMSXgdXFbXP4J9h%2BFgNBnALshTu3M6kvRzuy1S
PdAZIxsBFFwGevwrNHjbjYUYfg3qRoQ1z%2BrMPrkivLr5awhxOJ1bmhCcMzewFSaQjL1&ev=1'
[download] ???2-XMTMwNzQwMTcwMA_part1.flv has already been downloaded
[download] 100% of 28.09MiB
[download] Downloading video 2 of 16
[debug] Invoking downloader on 'http://k.youku.com/player/getFlvPath/sid/9453833
68788412f9216d_00/st/flv/fileid/0300012501565CCE09A5682BEEFCF9017144F0-8D0B-8A39
-4D28-1B0BE8AD219D?hd=1&K=ec4c3f0cb53ecbba261ecf8d&myp=0&ypp=0&token=4124&ctype=
12&oip=1155809357&ep=eyaRGUGOVcgI4ivXjD8bMSXgdXFbXP4J9h%2BFgNBnALohTu3M6kvRzuy1S
PdAZIxsBFFwGevwrNHjbjYUYfg3qRoQ1z%2BrMPrkivLr5awhxOJ1bmhCcMzewFSaQjL1&ev=1'
[download] ???2-XMTMwNzQwMTcwMA_part2.flv has already been downloaded
[download] 100% of 30.03MiB
**etc...**
**Downloads 3 - 15, etc...**
**etc...**
[download] Downloading video 16 of 16
[debug] Invoking downloader on 'http://k.youku.com/player/getFlvPath/sid/9453833
68788412f9216d_00/st/flv/fileid/030001250F565CCE09A5682BEEFCF9017144F0-8D0B-8A39
-4D28-1B0BE8AD219D?hd=1&K=94cdbf644cd21fb024127c88&myp=0&ypp=0&token=4124&ctype=
12&oip=1155809357&ep=eyaRGUGOVcgI4ivXjD8bMSXgdXFbXP4J9h%2BFgNBnAM0hTu3M6kvRzuy1S
PdAZIxsBFFwGevwrNHjbjYUYfg3qRoQ1z%2BrMPrkivLr5awhxOJ1bmhCcMzewFSaQjL1&ev=1'
[download] ???2-XMTMwNzQwMTcwMA_part16.flv has already been downloaded
[download] 100% of 23.80MiB
[download] Finished downloading playlist: ???2
```

**Comment by aonbyte** [comment]
Which videos work and which dont?

**Comment by temperson** [comment]
I don't know for sure if this occurs for all long videos, but the bug did occur for the two that I have listed in my original post. 

    On Monday, February 15, 2016 7:42 AM, Michael <notifications@github.com> wrote:
 

 Which videos work and which dont?—

**Comment by Celthi** [comment]
Did you try to merge the 16 videos to see how long the total time is?  I analyse the json data, and found the total time is 7156400ms, and 119 minutes, which equals the video's total time.

**Comment by temperson** [comment]
Yes, if I remember correctly, each of the 16 videos were around 3-4 minutes long. 

    On Sunday, March 27, 2016 9:41 PM, Evan Lu <notifications@github.com> wrote:
 

 Did you try to merge the 16 videos to see how long the total time is? I analyse the json data, and found the total time is 7156400ms, and 119 minutes, which equals the video's total time.—

**Comment by PannenkoekenNL** [comment]
Same problem, for example with this video http://v.youku.com/v_show/id_XNDM4ODU4Mzk2.html?old&&from=y1.2-1-100.3.2-2.1-1-1-1-0

**Comment by yan12125** [comment]
Both http://v.youku.com/v_show/id_XMTMwNzQwMTcwMA.html and http://v.youku.com/v_show/id_XNDM4ODU4Mzk2.html?old&&from=y1.2-1-100.3.2-2.1-1-1-1-0 will be  fixed (fully downloaded) in the next version. http://v.youku.com/v_show/id_XOTUwMzc1MDI0.html is restricted to China so I cann't test it. If there are still problems, feel free to leave comments below or open new an issue.
