### ISSUE TITLE
I met a problem when I try to download from bloomberg

### ISSUE THREAD

**Issue by KwToPA** [rg3/youtube-dl#8334]
youtube-dl --version
2016.01.27

youtube-dl http://www.bloomberg.com/news/videos/2016-01-21/george-soros-talks-eu-china-fed-and-donald-trump
[Bloomberg] george-soros-talks-eu-china-fed-and-donald-trump: Downloading webpage
ERROR: Unable to download webpage: [Errno 54] Connection reset by peer (caused by error(54, 'Connection reset by peer')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I don't know what's happened.

**Comment by KwToPA** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.27
[debug] Python version 2.7.6 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}

**Comment by yan12125** [comment]
Works for me. Usually ```Connection reset by peer``` indicates you have an unstable network environment. Can you watch this video in the browser without lagging? And can you try a few more times?

**Comment by KwToPA** [comment]
Thanks for commenting. It's the first time that I use youtube-dl. So I wonder that what it looks like if this command works? Could you show me the result by using this command 'youtube-dl --skip-download -g http://www.bloomberg.com/news/videos/2016-01-21/george-soros-talks-eu-china-fed-and-donald-trump'? Thank you.

**Comment by yan12125** [comment]
```
http://bbgvod-mmd-cust.lldns.net/m/NjY1NTI2Mw/PQYYnj31ZZtFpuV6XspTg7bURvzJbXQK6LsZN0PBxdowYmUy/dmd160121bmfullgs_,15,24,44,70,120,180,240,0.mp4.csmil/manifest.f4m?hdcore=1
```

It's a f4m manifest. And by the way, you don't need ```--skip-download``` when ```-g``` is given.

Please check one more thing: is the following command running in the terminal?
```
curl -vvv http://www.bloomberg.com/news/videos/2016-01-21/george-soros-talks-eu-china-fed-and-donald-trump
```

**Comment by KwToPA** [comment]
Thank you again
*   Trying 23.59.95.147...
* Connected to www.bloomberg.com (23.59.95.147) port 80 (#0)
> GET /news/videos/2016-01-21/george-soros-talks-eu-china-fed-and-donald-trump HTTP/1.1
> Host: www.bloomberg.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
------
Is this error 'Connection reset by peer' relating to the internet? And I wanted to use https proxy from http://www.sslproxies.org/  which command likes 'youtube-dl -proxy 115.160.137.139:8088' but it still not work.
youtube-dl: error: account username missing. I don't have the account username

-------
I found this url 'http://bbgvod-mmd-cust.lldns.net/m/NjY1NTI2Mw/PQYYnj31ZZtFpuV6XspTg7bURvzJbXQK6LsZN0PBxdowYmUy/dmd160121bmfullgs_,15,24,44,70,120,180,240,0.mp4.csmil/manifest.f4m?hdcore=1' by develop tools on chrome but I can't download the video in mp4 or flv

**Comment by yan12125** [comment]
> Is this error 'Connection reset by peer' relating to the internet?

Yep that indicates there's something wrong in the connection.

For the proxy, ```--proxy``` is the correct form. Note there are two minus signs there. For example:
```
youtube-dl -v --proxy 115.160.137.139:8088 http://www.bloomberg.com/news/videos/2016-01-21/george-soros-talks-eu-china-fed-and-donald-trump
```
Note that if this proxy accepts only https connections, explicit ```https://``` is necessary:
```
youtube-dl -v --proxy https://115.160.137.139:8088/ http://www.bloomberg.com/news/videos/2016-01-21/george-soros-talks-eu-china-fed-and-donald-trump
```

I'm closing this ticket now as it's not a problem of youtube-dl.
