### ISSUE TITLE
CBS.COM Videos not working FFMPEG=Invalid data found when processing input

### ISSUE THREAD

**Issue by witmore1** [rg3/youtube-dl#8336]
witmore@VM-Ubuntu:~$ youtube-dl http://www.cbs.com/shows/ncis_los_angeles/video/aexLenI0T_QSZMXe_wwsK0_38f_c_8_i/ncis-los-angeles-angels-daemons/ -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.cbs.com/shows/ncis_los_angeles/video/aexLenI0T_QSZMXe_wwsK0_38f_c_8_i/ncis-los-angeles-angels-daemons/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.27
[debug] Python version 2.7.6 - Linux-3.19.0-25-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avprobe v12_dev0-2253-ge917563, ffmpeg N-77962-g4a3cf18, ffprobe N-77962-g4a3cf18
[debug] Proxy map: {}
[CBS] ncis-los-angeles-angels-daemons: Downloading webpage
[ThePlatform] tLBiAoJcTi9J: Downloading SMIL data
[ThePlatform] tLBiAoJcTi9J: Downloading m3u8 information
[ThePlatform] tLBiAoJcTi9J: Downloading m3u8 information
[ThePlatform] tLBiAoJcTi9J: Downloading m3u8 information
[ThePlatform] tLBiAoJcTi9J: Downloading m3u8 information
[ThePlatform] tLBiAoJcTi9J: Downloading m3u8 information
[ThePlatform] tLBiAoJcTi9J: Downloading m3u8 information
[ThePlatform] tLBiAoJcTi9J: Downloading JSON metadata
[debug] Invoking downloader on u'https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2016/01/17/603228739880/CBS_NCISLA_711_CONTENT_CIAN_jignesh_vr_20M_725571_,548,3596,2596,1848,1248,848,298,158,000.mp4.csmil/index_1_av.m3u8?null=&id=AgBFL4aE0YU5VlcyqVbHQr32kJv+tWGxKiB%2flp3BugBHanydVYH5hE4tMZRWqz+lTvQzY+s7wshv%2fw%3d%3d'
[download] Destination: NCIS - Los Angeles - Angels & Daemons-tLBiAoJcTi9J.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: _alid_=+UmPCkpEUKkWWqnA6Z1Y/g==; hdntl=exp=1454015447~acl=%2fi%2ftemp_hd_gallery_video%2fCBS_Production_Outlet_VMS%2fvideo_robot%2fCBS_Production_Entertainment%2f2016%2f01%2f17%2f603228739880%2fCBS_NCISLA_711_CONTENT_CIAN_jignesh_vr_20M_725571_*~data=hdntl~hmac=6ccc50519104878df0511f095fdd7538e68a3235e0fb610fcf751a52c490b2d6
' -i 'https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2016/01/17/603228739880/CBS_NCISLA_711_CONTENT_CIAN_jignesh_vr_20M_725571_,548,3596,2596,1848,1248,848,298,158,000.mp4.csmil/index_1_av.m3u8?null=&id=AgBFL4aE0YU5VlcyqVbHQr32kJv+tWGxKiB%2flp3BugBHanydVYH5hE4tMZRWqz+lTvQzY+s7wshv%2fw%3d%3d' -f mp4 -c copy -bsf:a aac_adtstoasc 'file:NCIS - Los Angeles - Angels & Daemons-tLBiAoJcTi9J.mp4.part'
ffmpeg version N-77962-g4a3cf18 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --prefix=/home/witmore/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/witmore/ffmpeg_build/include --extra-ldflags=-L/home/witmore/ffmpeg_build/lib --bindir=/home/witmore/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-openssl --enable-libvpx --enable-libopus
  libavutil      55. 14.100 / 55. 14.100
  libavcodec     57. 22.100 / 57. 22.100
  libavformat    57. 22.100 / 57. 22.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 25.100 /  6. 25.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2016/01/17/603228739880/CBS_NCISLA_711_CONTENT_CIAN_jignesh_vr_20M_725571_,548,3596,2596,1848,1248,848,298,158,000.mp4.csmil/index_1_av.m3u8?null=&id=AgBFL4aE0YU5VlcyqVbHQr32kJv+tWGxKiB%2flp3BugBHanydVYH5hE4tMZRWqz+lTvQzY+s7wshv%2fw%3d%3d: Invalid data found when processing input

ERROR: ffmpeg exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1691, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 677, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 748, in process_ie_result
    new_result, download=download, extra_info=extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 723, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1361, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1623, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1565, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 72, in real_download
    self.report_error('%s exited with code %d' % (ffpp.basename, retval))
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 541, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 503, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by witmore1** [comment]
so does changing it to geo-restricted mean that is the cause of my problem? or that it is an issue that cant be looked at?

**Comment by dstftw** [comment]
Works fine with latest youtube-dl/ffmpeg.

**Comment by ergoen** [comment]
Did you get this working? I am having exactly the same errors, downloading with --hls-prefer-native seems to work, but the file is unplayable.

**Comment by Reino17** [comment]
Known FFMpeg bug: https://trac.ffmpeg.org/ticket/5248
