### ISSUE TITLE
download links for SSL certs (of youtube, vimeo, fb, etc.)

### ISSUE THREAD

**Issue by berrytsakala** [rg3/youtube-dl#8358]
Hi
While it is NOT youtube-dl's responsability for missing SSL certificate in windows (or just outdated),
It'd help if you maintain a list of download links + install instructions,
and point it out when this error occurs, on the readme, etc.

Otherwise people will keep failing and complaining on cert-related errors.

e.g.  https://pki.google.com/

**Comment by yan12125** [comment]
For the purpose of interacting with websites with SSL, people should never have additional certificates installed other than pre-installed root CAs. The correct solution can be found at https://github.com/rg3/youtube-dl/issues/7309#issuecomment-172354527.
