### ISSUE TITLE
Time for a name change?

### ISSUE THREAD

**Issue by leokhachatorians** [rg3/youtube-dl#8359]
I think this project is an absolute behemoth in terms of both capability and code, yet I feel as though the name itself portrays the exact opposite actually. While yes, this does revolve primarily around YouTube, I feel as though the amount of sites it's capable of rendering to be just too large for it to be simply called "youtube-dl".

**Comment by phihag** [comment]
This has been suggested multiple times. The effort would be horrendous, lots of stuff would break, we'd have double the costs for domains, and the upside would be minimal. We're keeping the name.
