### ISSUE TITLE
Getting traceback on YouTube video

### ISSUE THREAD

**Issue by Gumnos** [rg3/youtube-dl#8361]
As requested, here's the traceback with the latest executable from github:origin/master as of ~5min ago.

    $ cd bin/youtube-dl/
    $ git pull
    ...
    $ git st
    On branch master
    Your branch is up-to-date with 'origin/master'.
    nothing to commit, working directory clean
    
    $ ./youtube-dl --get-url --prefer-free-formats "https://www.youtube.com/watch?v=49tpIMDy9BE" --verbose
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['--get-url', '--prefer-free-formats', 'https://www.youtube.com/watch?v=49tpIMDy9BE', '--verbose']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.01.04
    [debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
    [debug] exe versions: avconv 11.4-6, avprobe 11.4-6
    [debug] Proxy map: {}
    WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
    ERROR: Signature extraction failed: Traceback (most recent call last):
      File "bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 601, in _decrypt_signature
        video_id, player_url, s
      File "bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 497, in _extract_signature_function
        raise ExtractorError('Cannot identify player %r' % player_url)
    ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflYjf147/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
     (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflYjf147/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 601, in _decrypt_signature
        video_id, player_url, s
      File "bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 497, in _extract_signature_function
        raise ExtractorError('Cannot identify player %r' % player_url)
    ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflYjf147/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "bin/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 592, in extract_info
        ie_result = ie.extract(url)
      File "bin/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 245, in extract
        return self._real_extract(url)
      File "bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1019, in _real_extract
        encrypted_sig, video_id, player_url, age_gate)
      File "bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 611, in _decrypt_signature
        'Signature extraction failed: ' + tb, cause=e)
    ExtractorError: Signature extraction failed: Traceback (most recent call last):
      File "bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 601, in _decrypt_signature
        video_id, player_url, s
      File "bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 497, in _extract_signature_function
        raise ExtractorError('Cannot identify player %r' % player_url)
    ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflYjf147/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
     (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflYjf147/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
```
[debug] youtube-dl version 2015.01.04
```
That's definitely not the last version :), you probably forgot to run `make youtube-dl`.

**Comment by Gumnos** [comment]
Odd. I don't remember needing to run `make youtube-dl` before, so I just had a nightly `cron` job doing a `git pull && git checkout origin/master` in that directory.  I'll update it to include the `make` command. Hadn't hit any issues until it failed for me this morning. Thanks.

**Comment by jaimeMF** [comment]
I don't know how is your setup, but the `youtube-dl` file was removed from the repo two years ago (in https://github.com/rg3/youtube-dl/commit/5c47fc68090db9f6259723d063ffa11392194642).

Note that unless you also need the auxiliary files, you can run `make youtube-dl` instead of `make`.
